### ISSUE TITLE
Using the extension "EssentialBusinessHeadlines" in your own extensions

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/ALAppExtensions#10]
Is it possible to also attach oneself to the Essential Business Headlines and thus profit from them on one's own role centres? I have looked at the code and there are objects in the C/AL as well as in the AL environment. That's all a bit confusing, and I don't quite understand the connections. All I want is to display information to the user in his own role center and address him there personally. Will there be a documentation here, or are these functionalities exclusively intended for Microsoft?

**Comment by JesperSchulz** [comment]
Hi!

Great to hear that you're interested in expanding the headlines capabilities! They are definately not meant for Microsoft only. We only provide a few sample headlines and hope that other developers create meaningful headlines for their customers.
We have released a short cookbook, which might point you in the right direction: https://community.dynamics.com/nav/w/designpatterns/312.extending-the-role-center-headlines.

Please take a look and let me know if that answers your questions. If not, chances are that we'll have to update the cookbook ;-)

**Comment by FSharpCSharp** [comment]
@JesperSchulz 
Thank you very much for the quick response to my question. It's almost a bit embarrassing that I didn't find this detailed article about "Headings". If I had known that there were even examples of it, I could have given myself this complete issue. With that, the issue is over in any case. I'm sorry again that I didn't find these detailed instructions for this design pattern.

**Comment by JesperSchulz** [comment]
I'm just glad I could help :-) It's not always easy to find help, as it is scattered around the internet. Best of luck with your headline extension! And if you'd like to contribute with a valuable headline for the community, I would be happy to process a pull request from you ;-)
