### ISSUE TITLE
[Enum Request] General Ledger Setup, Field 103 ("Bill-to/Sell-to VAT Calc.)

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#10007]
Please convert this option field to an extensible enum.

        field(103; "Bill-to/Sell-to VAT Calc."; Option)
        {
            Caption = 'Bill-to/Sell-to VAT Calc.';
            InitValue = "Sell-to/Buy-from No.";
            OptionCaption = 'Bill-to/Pay-to No.,Sell-to/Buy-from No.';
            OptionMembers = "Bill-to/Pay-to No.","Sell-to/Buy-from No.";
        }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
