### ISSUE TITLE
[Event Request] Codeunit 7041 "Price Asset - Item" - PutRelatedAssetsToList

### ISSUE THREAD

**Issue by DxCMakri-dev** [microsoft/ALAppExtensions#10004]
For the possibility to add other related asses to the list from the item price, I would like an event after the existing code

    procedure PutRelatedAssetsToList(PriceAsset: Record "Price Asset"; var PriceAssetList: Codeunit "Price Asset List")
    begin
        Item.Get(PriceAsset."Asset No.");
        if Item."Item Disc. Group" <> '' then begin
            PriceAssetList.SetLevel(PriceAsset.Level);
            PriceAssetList.Add(PriceAsset."Asset Type"::"Item Discount Group", Item."Item Disc. Group");
            +OnAfterPutRelatedAssetsToList(PriceAsset,PriceAssetList);
        end;
    end;

and this is the event it self:

    [IntegrationEvent(false, false)]
    local procedure OnAfterPutRelatedAssetsToList(PriceAsset: Record "Price Asset"; var PriceAssetList: Codeunit "Price Asset List")
    begin
    end;

So if you want to add i new price asset related to item like a price group it would be possible. Havent found any other way to solve that problem where its a new price asses related to an existing one on item. Like how the resource group prices are avaliable.

Thanks. 
Br Martin

**Comment by Jiribu73** [comment]
Hi, we need the same event, but must be at the end of the procedure.

Regards
Jiri

**Comment by DxCMakri-dev** [comment]
Hi. 
Its actually also where we need it, not inside the item disc. group section, it was an error to put it there from me.

procedure PutRelatedAssetsToList(PriceAsset: Record "Price Asset"; var PriceAssetList: Codeunit "Price Asset List")
begin
    Item.Get(PriceAsset."Asset No.");
    if Item."Item Disc. Group" <> '' then begin
        PriceAssetList.SetLevel(PriceAsset.Level);
        PriceAssetList.Add(PriceAsset."Asset Type"::"Item Discount Group", Item."Item Disc. Group");
    end;
    +OnAfterPutRelatedAssetsToList(PriceAsset,PriceAssetList);

end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
