### ISSUE TITLE
[Event Request] CU1012 "Job Jnl.-Post Line" - procedure OnAfterRunCode()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#10006]
```
----------------------- ADD VAR IN PARAMETER JobLedgEntryNo ----------------------

[IntegrationEvent(false, false)]
local procedure OnAfterRunCode(var JobJournalLine: Record "Job Journal Line"; VAR JobLedgEntryNo: Integer; var JobRegister: Record "Job Register")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
