### ISSUE TITLE
[Parameter by reference] Codeunit 7313 Create Put-away - OnBeforeCreateNewWhseActivity

### ISSUE THREAD

**Issue by clarasalvador** [microsoft/ALAppExtensions#10005]
In the existing OnBeforeCreateNewWhseActivity event of the Codeunit 7313 Create Put-away, the LineNo parameter is required to be by reference.

[IntegrationEvent(false, false)]
 local procedure OnBeforeCreateNewWhseActivity(PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; var WhseActivLine: Record "Warehouse Activity Line"; var WhseActivHeader: Record "Warehouse Activity Header"; var Location: Record Location; InsertHeader: Boolean; Bin: Record Bin; ActionType: Option ,Take,Place; **VAR LineNo**: Integer; BreakbulkNo: Integer; BreakbulkFilter: Boolean; QtyToHandleBase: Decimal; BreakPackage: Boolean; EmptyZoneBin: Boolean; Breakbulk: Boolean; CrossDockInfo: Option; PutAwayItemUOM: Record "Item Unit of Measure"; DoNotFillQtytoHandle: Boolean; var IsHandled: Boolean)
    begin
    end;

We have a certain urgency.
Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
