### ISSUE TITLE
[Event Request] Page 51 "Purchase Invoice" - procedure OnQueryClosePage()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#10010]
```
    trigger OnQueryClosePage(CloseAction: Action): Boolean
    begin

----------------------- ADD EVENT ----------------------
        IsHandled := false;
        OnQueryClosePageOnBeforeConfirmCloseUnposted(IsHandled);
        if not IsHandled then
----------------------------------------------------------

            if not DocumentIsPosted then
                exit(ConfirmCloseUnposted);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
