### ISSUE TITLE
[Request] Page 343 "Check Credit Limit" - Move variables

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#10016]
```
Move the variables var:

    NewOrderAmountLCY: Decimal
    DeltaAmount: Decimal;

To "protected var" to allow to retrieve them in an extension page.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
