### ISSUE TITLE
 [Request] Import to a data file

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#10019]
```
Problem reported by our customers to make an "Import to a data file" when there are not the same extensions between two databases. 
Why not propose at the time of "Export to a data file" the extensions to be recovered ? This will solve the problem for many of us !

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
