### ISSUE TITLE
Data replica will have no upgrade tags

### ISSUE THREAD

**Issue by rdebath** [microsoft/ALAppExtensions#10018]
https://github.com/microsoft/ALAppExtensions/blob/9f101082a819a997dca78bdf647273c62ec96531/Modules/System/Upgrade%20Tags/src/UpgradeTags.Table.al#L12

``` ReplicateData = false;```

The replica will have none of the tags set, but the data will have been processed by the upgrades.
Therefor on next upgrade ALL tagged upgrades will be run.

This seems bad.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by rdebath** [comment]
Ah, no.

The upgrade tags functionality is here; I'm saying that I think this data should be replicated (`ReplicateData = true;`) in the same way that the data that it applies to is replicated. By setting that flag `false` you are explicitly requesting that the platform breaks your data model.

This does not currently apply to any of our customers but we (I) will have to ensure that the fallback for broken tags is working correctly for any customer that ever wants to migrate from OnPrem to Cloud. (or recommend they not do that.)

**Comment by nikolakukrika** [comment]
Thanks for reporting. We have already fixed the issue. We have removed ReplicateData = true from this table in 14,15,16 and latest version. It will be released with the next CU. For the time being update the OnPrem instance to remove this property from the table and migrate the tags.
