### ISSUE TITLE
event request for modify the email body in approval & cancel notification emails 

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/ALAppExtensions#10021]
Hi everyone 
during development, I need an event to modify the details of email body 
![image](https://user-images.githubusercontent.com/38460823/100332455-6aca4300-2ff7-11eb-973e-c9b81355004d.png)

Report Name : 1320 "Notification Email"
function name: SetReportFieldPlaceholders 
event location : in the last of this procedure where i  can modify the details (variables ) like Field1Label,Field1Value, Field2Label, Field2Value etc.....

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by SahilGuptaBS** [comment]
@StanPesotskiy  here is the signature of event 

![image](https://user-images.githubusercontent.com/38460823/100445768-a76b6c80-30d3-11eb-9ba0-7f7770c1bee5.png)

**Comment by StanPesotskiy** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode **instead of screenshots**.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by dtkb** [comment]
The problem I see is that the event publisher `OnSetReportFieldPlaceholders()` passes `Field3Label, Field3Value` as `var` to subscribers, allowing us to set those fields to our own values - but then the `case "Notification Entry".Type` will override them in most cases, i.e. when `Type` is `Approval`.

A better fix might be to add a `var Handled: Boolean` argument to `OnSetReportFieldPlaceholders()`, and only enter the `case` if we have `not Handled` setting the fields in a subscriber. But I guess I'll wait and see if this change lands and is sufficient for us.

**Comment by StanPesotskiy** [comment]
@dtkb 
This request was closed but you added a new comment. We do not track the closed requests so your comment may be not registered and answered. If you want to continue discussion please create a new request and put a link to the closed one.

**Comment by dtkb** [comment]
@StanPesotskiy done; see link in mention above.
