### ISSUE TITLE
[Access Request] Page 5914 - Service Order Statistics

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#10023]
Hi Al team,

I would like to access the following variables from the extension object

```
protected var
        TotalServLineLCY: array[7] of Record "Service Line";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
