### ISSUE TITLE
Page "Items by Location"  procedure SetColumns  [Scope('OnPrem')]

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#10026]
could you delete in page "Items by Location" the Scope onPrem? We can not use this page in our cloud solution or have to complete copy it.

Old Code:
```
[Scope('OnPrem')]
procedure SetColumns(SetWanted: Option Initial,Previous,Same,Next)
var
    MatrixMgt: Codeunit "Matrix Management";
    CaptionFieldNo: Integer;
    CurrentMatrixRecordOrdinal: Integer;
begin
```

NewCode:
```
procedure SetColumns(SetWanted: Option Initial,Previous,Same,Next)
var
    MatrixMgt: Codeunit "Matrix Management";
    CaptionFieldNo: Integer;
    CurrentMatrixRecordOrdinal: Integer;
begin
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
