### ISSUE TITLE
[Event Request] Record::"Customized Calendar Entry" - Function GetCaption OnAfterGetCaption

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10020]
As we have some more Tables that use Cust. calendars, we need a possibility to control the caption accordingly. Therefore an event like "OnAfterGetCaption" (or OnBefore or something else) is needed. 

    [EventSubscriber(ObjectType::Table, Database::"Customized Calendar Entry", 'OnAfterGetCaption', '', true, true)]
    local procedure "Customized Calendar Entry_OnAfterGetCaption"
    (
        var CustomizedCalendarChange: Record "Customized Calendar Change";
		CustomizedCalendarEntry: Record "Customized Calendar Entry"
    )
    begin

    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
