### ISSUE TITLE
Request Event - Report 7315 - Calculate Whse. Adjustment

### ISSUE THREAD

**Issue by ValcLuisCosta** [microsoft/ALAppExtensions#10022]
Hello,
I'm using the AL Language version 6.1.362735 and BC version 17.1.
I need the following events on report 7315:

    dataset
    {
        dataitem(Item; Item)
        {
            DataItemTableView = SORTING("No.");
            RequestFilterFields = "No.", "Location Filter", "Variant Filter";
            dataitem("Integer"; "Integer")
            {
                DataItemTableView = SORTING(Number) WHERE(Number = CONST(1));

                trigger OnAfterGetRecord()
                var
                    AdjmtBin: Record Bin;
                    ReservationEntry: Record "Reservation Entry";
                    SNLotNumbersByBin: Query "Lot Numbers by Bin";
                begin
                    with AdjmtBinQuantityBuffer do begin
                        Location.Reset();
                        Item.CopyFilter("Location Filter", Location.Code);
                        Location.SetRange("Directed Put-away and Pick", true);
                        if Location.FindSet then
                            repeat
                                AdjmtBin.Get(Location.Code, Location."Adjustment Bin Code");

                                SNLotNumbersByBin.SetRange(Location_Code, Location.Code);
                                SNLotNumbersByBin.SetRange(Zone_Code, AdjmtBin."Zone Code");
                                SNLotNumbersByBin.SetRange(Bin_Code, AdjmtBin.Code);
                                SNLotNumbersByBin.SetRange(Item_No, Item."No.");
                                SNLotNumbersByBin.SetFilter(Variant_Code, Item.GetFilter("Variant Filter"));
                                SNLotNumbersByBin.SetFilter(Lot_No, Item.GetFilter("Lot No. Filter"));
                                SNLotNumbersByBin.SetFilter(Serial_No, Item.GetFilter("Serial No. Filter"));
                                **-------------- ADD EVENT -----------
                                Possibility to extend the query to get a value from created field and add an event on this place.
                                ---------------------------------------**
                                SNLotNumbersByBin.Open;

                                while SNLotNumbersByBin.Read do begin
                                    Init;
                                    "Item No." := SNLotNumbersByBin.Item_No;
                                    "Variant Code" := SNLotNumbersByBin.Variant_Code;
                                    "Location Code" := SNLotNumbersByBin.Location_Code;
                                    "Bin Code" := SNLotNumbersByBin.Bin_Code;
                                    "Unit of Measure Code" := SNLotNumbersByBin.Unit_of_Measure_Code;
                                    "Base Unit of Measure" := Item."Base Unit of Measure";
                                    "Lot No." := SNLotNumbersByBin.Lot_No;
                                    "Serial No." := SNLotNumbersByBin.Serial_No;
                                    "Qty. to Handle (Base)" := SNLotNumbersByBin.Sum_Qty_Base;
                                    OnBeforeAdjmtBinQuantityBufferInsert(AdjmtBinQuantityBuffer, WhseEntry, SNLotNumbersByBin);
                                    Insert;
                                end;
                            until Location.Next = 0;

                        Reset;
                        ReservationEntry.Reset();
                        ReservationEntry.SetCurrentKey("Source ID");
                        ItemJnlLine.Reset();
                        ItemJnlLine.SetCurrentKey("Item No.");
                        if FindSet then begin
                            repeat
                                ItemJnlLine.Reset();
                                ItemJnlLine.SetCurrentKey("Item No.");
                                ItemJnlLine.SetRange("Journal Template Name", ItemJnlLine."Journal Template Name");
                                ItemJnlLine.SetRange("Journal Batch Name", ItemJnlLine."Journal Batch Name");
                                ItemJnlLine.SetRange("Item No.", "Item No.");
                                ItemJnlLine.SetRange("Location Code", "Location Code");
                                ItemJnlLine.SetRange("Unit of Measure Code", "Unit of Measure Code");
                                ItemJnlLine.SetRange("Warehouse Adjustment", true);
                                if ItemJnlLine.FindSet then
                                    repeat
                                        ReservationEntry.SetRange("Source Type", DATABASE::"Item Journal Line");
                                        ReservationEntry.SetRange("Source ID", ItemJnlLine."Journal Template Name");
                                        ReservationEntry.SetRange("Source Batch Name", ItemJnlLine."Journal Batch Name");
                                        ReservationEntry.SetRange("Source Ref. No.", ItemJnlLine."Line No.");
                                        if "Lot No." <> '' then
                                            ReservationEntry.SetRange("Lot No.", "Lot No.");
                                        if "Serial No." <> '' then
                                            ReservationEntry.SetRange("Serial No.", "Serial No.");
                                        **-------------- ADD EVENT -----------
                                        OnAfterReservEntryFilter(AdjmtBinQuantityBuffer, ReservationEntry);
                                        ----------------------------------------**
                                        ReservationEntry.CalcSums("Qty. to Handle (Base)");
                                        if ReservationEntry."Qty. to Handle (Base)" <> 0 then begin
                                            "Qty. to Handle (Base)" += ReservationEntry."Qty. to Handle (Base)";
                                            OnBeforeAdjmtBinQuantityBufferModify(AdjmtBinQuantityBuffer, ReservationEntry);
                                            Modify;
                                        end;
                                    until ItemJnlLine.Next = 0;
                            until Next = 0;
                        end;
                    end;
                end;

    local procedure CreateReservationEntry(var ItemJournalLine: Record "Item Journal Line"; var TempBinContentBuffer: Record "Bin Content Buffer" temporary; EntryType: Option "Negative Adjmt.","Positive Adjmt."; UOMCode: Code[10])
    var
        WarehouseEntry: Record "Warehouse Entry";
        WarehouseEntry2: Record "Warehouse Entry";
        CreateReservEntry: Codeunit "Create Reserv. Entry";
        OrderLineNo: Integer;
    begin
        TempBinContentBuffer.FindSet;
        repeat
            WarehouseEntry.SetCurrentKey(
              "Item No.", "Bin Code", "Location Code", "Variant Code", "Unit of Measure Code", "Lot No.", "Serial No.", "Entry Type");
            WarehouseEntry.SetRange("Item No.", TempBinContentBuffer."Item No.");
            WarehouseEntry.SetRange("Bin Code", TempBinContentBuffer."Bin Code");
            WarehouseEntry.SetRange("Location Code", TempBinContentBuffer."Location Code");
            WarehouseEntry.SetRange("Variant Code", TempBinContentBuffer."Variant Code");
            WarehouseEntry.SetRange("Unit of Measure Code", UOMCode);
            WarehouseEntry.SetRange("Lot No.", TempBinContentBuffer."Lot No.");
            WarehouseEntry.SetRange("Serial No.", TempBinContentBuffer."Serial No.");
            WarehouseEntry.SetFilter("Entry Type", '%1|%2', EntryType, WarehouseEntry."Entry Type"::Movement);
            **-------------- ADD EVENT -----------
            OnAfterWarehouseEntryFilter(WarehouseEntry, TempBinContentBuffer);
            ----------------------------------------**
            if not WarehouseEntry.FindFirst then
                exit;

            TempReservationEntryBuffer.Reset();
            WarehouseEntry.CalcSums("Qty. (Base)", Quantity);
            UpdateWarehouseEntryQtyByReservationEntryBuffer(
              WarehouseEntry, WarehouseEntry."Lot No.", WarehouseEntry."Serial No.");

            WarehouseEntry2.CopyFilters(WarehouseEntry);
            case EntryType of
                EntryType::"Positive Adjmt.":
                    WarehouseEntry2.SetRange("Entry Type", WarehouseEntry2."Entry Type"::"Negative Adjmt.");
                EntryType::"Negative Adjmt.":
                    WarehouseEntry2.SetRange("Entry Type", WarehouseEntry2."Entry Type"::"Positive Adjmt.");
            end;
            WarehouseEntry2.CalcSums("Qty. (Base)", Quantity);
            UpdateWarehouseEntryQtyByReservationEntryBuffer(
              WarehouseEntry2, WarehouseEntry."Lot No.", WarehouseEntry."Serial No.");

            if Abs(WarehouseEntry2."Qty. (Base)") > Abs(WarehouseEntry."Qty. (Base)") then begin
                WarehouseEntry."Qty. (Base)" := 0;
                WarehouseEntry.Quantity := 0;
            end else begin
                WarehouseEntry."Qty. (Base)" += WarehouseEntry2."Qty. (Base)";
                WarehouseEntry.Quantity += WarehouseEntry2.Quantity;
            end;

            if WarehouseEntry."Qty. (Base)" <> 0 then begin
                if ItemJournalLine."Order Type" = ItemJournalLine."Order Type"::Production then
                    OrderLineNo := ItemJournalLine."Order Line No.";

                **-------------- ADD Parameter to event -----------
                OnBeforeCreateReservEntryFor(ItemJournalLine , WarehouseEntry);
                ------------------------------------------------------**

                CreateReservEntry.CreateReservEntryFor(
                  DATABASE::"Item Journal Line", ItemJournalLine."Entry Type".AsInteger(), ItemJournalLine."Journal Template Name",
                  ItemJournalLine."Journal Batch Name", OrderLineNo, ItemJournalLine."Line No.", ItemJournalLine."Qty. per Unit of Measure",
                  Abs(WarehouseEntry.Quantity), Abs(WarehouseEntry."Qty. (Base)"),
                  WarehouseEntry."Serial No.", WarehouseEntry."Lot No.");

                if WarehouseEntry."Qty. (Base)" < 0 then
                    CreateReservEntry.SetDates(WarehouseEntry."Warranty Date", WarehouseEntry."Expiration Date");

                OnCreateReservationEntryOnBeforeCreateReservEntryCreateEntry(ItemJournalLine);

                CreateReservEntry.CreateEntry(
                  ItemJournalLine."Item No.", ItemJournalLine."Variant Code", ItemJournalLine."Location Code", ItemJournalLine.Description,
                  0D, 0D, 0, TempReservationEntryBuffer."Reservation Status"::Prospect);
            end;
        until TempBinContentBuffer.Next = 0;
    end;

    local procedure UpdateWarehouseEntryQtyByReservationEntryBuffer(var WarehouseEntry: Record "Warehouse Entry"; LotNo: Code[50]; SerialNo: Code[50])
    begin
        if WarehouseEntry."Qty. (Base)" = 0 then
            exit;

        if LotNo <> '' then
            TempReservationEntryBuffer.SetRange("Lot No.", LotNo);
        if SerialNo <> '' then
            TempReservationEntryBuffer.SetRange("Serial No.", SerialNo);
        TempReservationEntryBuffer.SetRange(Positive, WarehouseEntry."Qty. (Base)" < 0);
        **-------------- ADD EVENT -----------
        OnAfterTempReservEntryBufferFilter(TempReservationEntryBuffer, WarehouseEntry);
        ------------------------------------------------------**        
        TempReservationEntryBuffer.CalcSums("Quantity (Base)", Quantity);

        WarehouseEntry."Qty. (Base)" += TempReservationEntryBuffer."Quantity (Base)";
        WarehouseEntry.Quantity += TempReservationEntryBuffer.Quantity;

        OnAfterUpdateWarehouseEntryQtyByReservationEntryBuffer(WarehouseEntry, TempReservationEntryBuffer);
    end;

Thank you,
Luís Costa

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
