### ISSUE TITLE
Codeunit 99000757 "Update Prod. Order Cost" - Consider SKU Unit Cost

### ISSUE THREAD

**Issue by EnricoAlbrecht** [microsoft/ALAppExtensions#10029]
Dear ALAppExtensions team,

in the entire codeunit, the unit costs of the stockkeeping units are not considered. We need at least the following code and event modifications:

    procedure UpdateUnitCostOnProdOrder(var ProdOrderLine: Record "Prod. Order Line"; MultipleLevels: Boolean; UpdateReservation: Boolean)
    var
        Item: Record Item;
        ProdOrderComp: Record "Prod. Order Component";
        ReservEntry: Record "Reservation Entry";
        TotalCostQty: Decimal;
        TotalUnitCost: Decimal;
        UnitCost: Decimal;
        ---------------- NEW VARIABLE -----------
        SKU: Record "Stockkeeping Unit";
        -----------------------------------------
    begin
        if not Item.Get(ProdOrderLine."Item No.") then
            exit;

        if Item."Costing Method".AsInteger() > Item."Costing Method"::Average.AsInteger() then
            exit;

        ProdOrderComp.SetRange(Status, ProdOrderLine.Status);
        ProdOrderComp.SetRange("Prod. Order No.", ProdOrderLine."Prod. Order No.");
        ProdOrderComp.SetRange("Prod. Order Line No.", ProdOrderLine."Line No.");

        if ProdOrderComp.Find('-') then
            repeat
                TotalCostQty := 0;
                TotalUnitCost := 0;
                Item.Get(ProdOrderComp."Item No.");
                
                ---------------- NEW CODE --------------
                if SKU.Get(ProdOrderComp."Location Code", ProdOrderComp."Item No.", ProdOrderComp."Variant Code") then
                    Item."Unit Cost" := SKU."Unit Cost";
                ----------------------------------------

                if Item."Costing Method".AsInteger() <= Item."Costing Method"::Average.AsInteger() then begin
                    ReservEntry."Source Type" := DATABASE::"Prod. Order Component";
                    ReservEntry.InitSortingAndFilters(true);
                    ProdOrderComp.SetReservationFilters(ReservEntry);
                    if ReservEntry.Find('-') then
                        SumTrackingCosts(ReservEntry, TotalUnitCost, TotalCostQty, MultipleLevels, Item);
                    ProdOrderComp.CalcFields("Reserved Qty. (Base)");
                    TotalUnitCost :=
                      TotalUnitCost +
                      (Item."Unit Cost" *
                       (ProdOrderComp."Expected Qty. (Base)" - ProdOrderComp."Reserved Qty. (Base)"));
                    TotalCostQty :=
                      TotalCostQty +
                      (ProdOrderComp."Expected Qty. (Base)" - ProdOrderComp."Reserved Qty. (Base)");
                    if TotalCostQty <> 0 then begin
                        UnitCost := TotalUnitCost / TotalCostQty * ProdOrderComp."Qty. per Unit of Measure";
                        if ProdOrderComp."Unit Cost" <> UnitCost then begin
                            ProdOrderComp.Validate("Unit Cost", UnitCost);
                            ProdOrderComp.Modify();
                        end;
                    end;
                end;
            until ProdOrderComp.Next = 0;

        ProdOrderLine.CalcFields(
          "Expected Operation Cost Amt.",
          "Total Exp. Oper. Output (Qty.)",
          "Expected Component Cost Amt.");

        if ProdOrderLine."Total Exp. Oper. Output (Qty.)" <> 0 then
            ProdOrderLine."Expected Operation Cost Amt." :=
              Round(
                ProdOrderLine."Expected Operation Cost Amt." /
                ProdOrderLine."Total Exp. Oper. Output (Qty.)" *
                ProdOrderLine.Quantity);

        ------------- MODIFY EVENT--------------
        -------------- OLD CODE ----------------
        OnUpdateUnitCostOnProdOrderOnBeforeValidateUnitCost(ProdOrderLine);
        -------------- NEW CODE ----------------
        OnUpdateUnitCostOnProdOrderOnBeforeValidateUnitCost(ProdOrderLine, MultipleLevels, UpdateReservation);
        ---------------------------------------

        ProdOrderLine.Validate(
          "Unit Cost",
          (ProdOrderLine."Expected Operation Cost Amt." + ProdOrderLine."Expected Component Cost Amt.") / ProdOrderLine.Quantity);

        ------------- MODIFY EVENT--------------
        -------------- OLD CODE ----------------
        OnUpdateUnitCostOnProdOrderOnAfterValidateUnitCost(ProdOrderLine);
        -------------- NEW CODE ----------------
        OnUpdateUnitCostOnProdOrderOnAfterValidateUnitCost(ProdOrderLine, MultipleLevels, UpdateReservation);
        ---------------------------------------

        ProdOrderLine.Modify();
        if UpdateReservation then begin
            ReservEntry.Reset();
            ReservEntry."Source Type" := DATABASE::"Prod. Order Line";
            ReservEntry.InitSortingAndFilters(false);
            ProdOrderLine.SetReservationFilters(ReservEntry);
            if ProdOrderLine."Qty. per Unit of Measure" <> 0 then
                UnitCost := Round(ProdOrderLine."Unit Cost" / ProdOrderLine."Qty. per Unit of Measure", 0.00001)
            else
                UnitCost := ProdOrderLine."Unit Cost";
            if ReservEntry.Find('-') then
                repeat
                    ModifyFor(ReservEntry, UnitCost);
                until ReservEntry.Next = 0;
        end;
    end;

    ------------- MODIFY EVENT--------------
    -------------- OLD CODE ----------------
    [IntegrationEvent(false, false)]
    local procedure OnUpdateUnitCostOnProdOrderOnAfterValidateUnitCost(var ProdOrderLine: Record "Prod. Order Line")
    begin
    end;
    -------------- NEW CODE ----------------
    [IntegrationEvent(false, false)]
    local procedure OnUpdateUnitCostOnProdOrderOnAfterValidateUnitCost(var ProdOrderLine: Record "Prod. Order Line";MultipleLevels: Boolean; UpdateReservation: Boolean)
    begin
    end;
    ---------------------------------------

    ------------- MODIFY EVENT--------------
    -------------- OLD CODE ----------------
    [IntegrationEvent(false, false)]
    local procedure OnUpdateUnitCostOnProdOrderOnBeforeValidateUnitCost(var ProdOrderLine: Record "Prod. Order Line")
    begin
    end;
    -------------- NEW CODE ----------------
    [IntegrationEvent(false, false)]
    local procedure OnUpdateUnitCostOnProdOrderOnBeforeValidateUnitCost(var ProdOrderLine: Record "Prod. Order Line";MultipleLevels: Boolean; UpdateReservation: Boolean)
    begin
    end;
    ---------------------------------------

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug partially related to the AL extensibility. In order to complete this fix we need to add some automated tests verifying the new behavior. 
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
