### ISSUE TITLE
[Event Request] Table Time Sheet Line - Function GetJobApproverID

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#10027]
Hello Team,

you already have an event in this function, but we need an enhancement of the Event:

OLD CODE:

        IsHandled := false;
        OnBeforeGetJobApproverID(ApproverID, IsHandled);
        if IsHandled then
            exit(ApproverID);

NEW CODE

        IsHandled := false;
        OnBeforeGetJobApproverID(ApproverID, IsHandled, Rec);
        if IsHandled then
            exit(ApproverID);

Thank you

**Comment by StanPesotskiy** [comment]
This event has IncludeSender=true, so you can use parameter Sender.
