### ISSUE TITLE
Page 42 "Sales Order" - Extend SubPageLink for "Item Invoicing FactBox" with Variant Code/Filter

### ISSUE THREAD

**Issue by EnricoAlbrecht** [microsoft/ALAppExtensions#10031]
Dear ALAppExtensions team,

when linking the FactBox "Item Invoicing FactBox" in Page 42 "Sales Order" we also need the variant code and location code:

> ---------------------- OLD CODE ------------------
> part(Control1901314507; "Item Invoicing FactBox")
> {
>     ApplicationArea = Basic, Suite;
>     Provider = SalesLines;
>     SubPageLink = "No." = FIELD("No.");
>     Visible = false;
> }
> --------------------------------------------------
> 
> ---------------------- NEW CODE ------------------
> part(Control1901314507; "Item Invoicing FactBox")
> {
>     ApplicationArea = Basic, Suite;
>     Provider = SalesLines;
>     SubPageLink = "No." = FIELD("No."), "Variant Filter" = FIELD("Variant Code"), "Location Filter" = FIELD("Location Code");
>     Visible = false;
> }
> --------------------------------------------------
>

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
