### ISSUE TITLE
[Question] Table 37 - CurrFieldNo

### ISSUE THREAD

**Issue by GlicPi** [Microsoft/ALAppExtensions#1003]
Hello,

I hope this is the right place to ask this =) 
Could you add an external Function to set the "CurrFieldNo" in Table 37?

**Comment by maksym-ch** [comment]
Hi @GlicPi,
You can create own SetCurrFiledNo function in table extension.
CU3 does not support this feature, but insider preview supports.
Please, refer to #4382 (https://github.com/Microsoft/AL/issues/4382), 
#4152 (https://github.com/Microsoft/AL/issues/4152)
Hope, I've helped you.
