### ISSUE TITLE
[Change Request] Codeunit 22 "Item Jnl.-Post Line" – Existing function “ItemQtyPosting”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10043]
Could we please have the existing function “ItemQtyPosting”, Codeunit 22 " Item Jnl.-Post Line”, be set to global?
```

*** start old code ***
    //local procedure ItemQtyPosting()
*** stop old code ***
*** start new code ***
    procedure ItemQtyPosting()
*** stop new code ***
    var
        IsReserved: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
