### ISSUE TITLE
[Event Request] Table 8622 Config. Line - OnBeforeOnBeforeGetRelatedTables

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10049]
We are migrating our code from NAV 2018 to BC16.4. In the Table 8622 "Config. Line", in the procedure GetRelatedTables, we need to add a condition to the use of the first line : "ConfigPackageMgt.SetFieldFilter(Field, "Table ID", 0);". To do so, we need a IsHandled flag and an event publisher, like this : 

![image](https://user-images.githubusercontent.com/34645582/100470637-e819b480-30d8-11eb-80f8-78971690ed2c.png)

And here is the event integration.
![image](https://user-images.githubusercontent.com/34645582/100470920-755d0900-30d9-11eb-926b-ff16c21f3105.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
