### ISSUE TITLE
[Event Request] Table 5405 "Production Order - OnBeforeGetNoSeriesCode

### ISSUE THREAD

**Issue by KuljitSinghParmar** [microsoft/ALAppExtensions#10048]
Hi Team,

In table 5405 "Production Order" , we need to have Integration event in the "GetNoSeriesCode()" procedure. Adding an event with handling in this procedure will work great for us.
![image](https://user-images.githubusercontent.com/61985025/100467876-2044d700-3088-11eb-9946-514525eeff70.png)

procedure GetNoSeriesCode(): Code[20]
var
        NoSeriesCode: Code[20];
        IsHandled: Boolean;
begin
        MfgSetup.Get();
        OnBeforeGetNoSeriesCode(Rec, MfgSetup, NoSeriesCode, IsHandled);
        if IsHandled then 
            exit(NoSeriesCode);
   
        case Status of
            Status::Simulated:
                exit(MfgSetup."Simulated Order Nos.");
            Status::Planned:
                exit(MfgSetup."Planned Order Nos.");
            Status::"Firm Planned":
                exit(MfgSetup."Firm Planned Order Nos.");
            Status::Released:
                exit(MfgSetup."Released Order Nos.");
        end;
   end;

[IntegrationEvent(false, false)]       
local procedure OnBeforeGetNoSeriesCode(var ProductionOrder: Record "Production Order"; MfgSetup: Record "Manufacturing Setup"; var NoSeriesCode: Code[20]; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
