### ISSUE TITLE
[Event Request] Table T36/38 Function ShouldLookFor...ByName

### ISSUE THREAD

**Issue by RaKuNbg** [microsoft/ALAppExtensions#10047]
Please add a publisher at the begin of function
Table 36 / Function ShouldSearchForCustomerByName
Table 38 / Function ShouldSearchForVendorByName

OnBeforeShouldSearchForCustomerByName that should include a Handled flag so the functionality can be disabled by code.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
