### ISSUE TITLE
[Change Request] Codeunit 22 "Item Jnl.-Post Line" – Existing function “ItemValuePosting”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10044]
Could we please have the existing function “ItemValuePosting”, Codeunit 22 " Item Jnl.-Post Line”, be set to global?
```

*** start old code***
    //local procedure ItemValuePosting()
*** stop old code ***
*** start new code ***
    procedure ItemValuePosting()
*** stop new code***
    begin
        with ItemJnlLine do begin
            if ("Value Entry Type" = "Value Entry Type"::"Direct Cost") and
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
