### ISSUE TITLE
ES Localization - 2 options for same language Spanish (Spain) 

### ISSUE THREAD

**Issue by prasadCherukumalli** [microsoft/ALAppExtensions#10051]
![image](https://user-images.githubusercontent.com/64625818/100569860-50031180-330a-11eb-9413-54ec0cd9eacd.png)
Hi,
Available languages show two options for Spanish (Spain) and there is no difference. (See the image)
When we publish a language app it is working only with 2nd option, 1st option needs to be removed.

Thank you,

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
