### ISSUE TITLE
[Event Request] Add Parameters to OnBeforeShowModifyAddressNotification in T36 "Sales Header"

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#10052]
Please add parameters to the already existing Event "OnBeforeShowModifyAddressNotification" in Table "Sales Header".

Currently only the parameter "IsHandled" is available there. It would be great if a few more parameters could be added:
 - Rec, 
 - CustomerNumber

Alternatively a Handled-Pattern at the beginning of the function "ModifyCustomerAddress" in the "Sales Header" would be conceivable.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
