### ISSUE TITLE
[Parameter Request] codeunit 99000854 "Inventory Profile Offsetting" - OnAfterFindLinesWithItemToPlan for TransSalesLineToProfile

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#10065]
Could you please add the following parameters to the event `OnAfterFindLinesWithItemToPlan`?

Old Signature:
```al
[IntegrationEvent(false, false)]
local procedure OnAfterFindLinesWithItemToPlan(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
begin
end;
```
New Signature:
```al
[IntegrationEvent(false, false)]
local procedure OnAfterFindLinesWithItemToPlan(var SalesLine: Record "Sales Line"; var InventoryProfile: Record "Inventory Profile"; var Item: Record Item; var NextLineNo: Integer; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
