### ISSUE TITLE
[Event Request] Codeunit 99000854 "Inventory Profile Offsetting" - New Event "OnBeforeTransRcptTransLineToProfile"

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#10069]
Could we please have a new publisher “OnBeforeTransRcptTransLineToProfile” in Function “TransRcptTransLineToProfile”, Codeunit 99000854 "Inventory Profile Offsetting”?

```al
    local procedure TransRcptTransLineToProfile(var InventoryProfile: Record "Inventory Profile"; var Item: Record Item; ToDate: Date)
    begin
        >>>> NEW CODE >>>>
        OnBeforeTransRcptTransLineToProfile(InventoryProfile,Item,ToDate);
        <<<< NEW CODE <<<<
        FilterIsSetOnLocation := Item.GetFilter("Location Filter") <> '';
        if TransLine.FindLinesWithItemToPlan(Item, true, true) then
            repeat
                if TransLine."Receipt Date" <> 0D then begin
        ...
```

```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransRcptTransLineToProfile(var InventoryProfile: Record "Inventory Profile"; var Item: Record Item; ToDate: Date)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
