### ISSUE TITLE
[Event Request] table 5741 "Transfer Line" - OnValidateVariantCodeOnBeforeCheckEmptyVariantCode

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#10061]
Can we please get the following event for the OnValidate Trigger of Table "Transfer Line"?
```al
field(30; "Variant Code"; Code[10])
{
    trigger OnValidate()
    var
        ItemVariant: Record "Item Variant";
    begin
       ...

        OnValidateVariantCodeOnBeforeCheckEmptyVariantCode(Rec, xRec, CurrFieldNo);//NEW
        if "Variant Code" = '' then
            exit;

      ...
    end;
}
```

```al
[IntegrationEvent(false, false)]
local procedure OnValidateVariantCodeOnBeforeCheckEmptyVariantCode(var TransferLine: Record "Transfer Line"; xTransferLine: Record "Transfer Line"; CurrentFieldNo: Integer)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
