### ISSUE TITLE
[Event Request] Codeunit 99000854 "Inventory Profile Offsetting" - New Event "OnBeforeTransItemLedgEntryToProfile"

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#10062]
Could we please have a new publisher “OnBeforeTransItemLedgEntryToProfile” in Function “TransItemLedgEntryToProfile”, Codeunit 99000854 "Inventory Profile Offsetting”?

```al
    local procedure TransItemLedgEntryToProfile(var InventoryProfile: Record "Inventory Profile"; var Item: Record Item)
    begin
        >>>> NEW CODE >>>>
        OnBeforeTransItemLedgEntryToProfile(InventoryProfile,Item);
        <<<< NEW CODE <<<<
        if ItemLedgEntry.FindLinesWithItemToPlan(Item, false) then
            repeat
                InventoryProfile.Init();
        ...
```

```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransItemLedgEntryToProfile(var InventoryProfile: Record "Inventory Profile"; var Item: Record Item)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
