### ISSUE TITLE
[EventRequest] Table 81 ""Applies-to Doc. No." OnBeforeLookUpAppliesToDocNo

### ISSUE THREAD

**Issue by dNsl9r** [microsoft/ALAppExtensions#10071]
Hi there,
we need to change the behaviour of the Lookup for "Applies-to Doc. No.".

We need to add a lookup possibility for General Ledger Entries.

To do so, we would suggest to you to add the following event:

`
            field(36; "Applies-to Doc. No."; Code[20])
                    {
            Caption = 'Applies-to Doc. No.';

            trigger OnLookup()
            var
                PaymentToleranceMgt: Codeunit "Payment Tolerance Management";
                AccType: Enum "Gen. Journal Account Type";
                AccNo: Code[20];
            begin
                IsHandled := false;
                OnBeforeLookUpAppliesToDocNo(Rec, IsHandled);
                if IsHandled then
                    exit;

                xRec.Amount := Amount;
                xRec."Currency Code" := "Currency Code";
                . . .
`

As you can see, a "OnBeforeLookUpAppliesToDocNo" with the IsHandled pattern would help.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
