### ISSUE TITLE
[Function Expose] GetWord - Codeunit 5054 WordManagement

### ISSUE THREAD

**Issue by fvet** [Microsoft/ALAppExtensions#1007]
In the latest BCoP CU3 release, a fix is shipped to avoid pending Winword.exe sessions. The solution is using a new WordApplicationHandler codeunit, subscribing to events raised in codeunit 5054 WordManagment. 5 new functions are added, most of them external (Activate, IsActive, ...)

In our solution, we've heavily customized the WordManagement codeunits (in a separate object). However, we'd like to apply the same pattern / fix, using the new WordApplicationHandler codeunit. Therefore we re-use the new functions (Activate, IsActive, ...) from codeunit 5054. However, function GetWord is not external. 

Sample code of our WordManagement codeunit (CreateWordAttachment function)
```
WordManagement.Activate(WordApplicationHandler,50000);
WordManagement.GetWord(WordApplication);  // GetWord is not EXTERNAL
...
WordManagement.Deactivate(50000);
```

Can you please set 'GetWord' to External?

**Comment by JesperSchulz** [comment]
We cannot set GetWord as external, as it contains a .NET parameter, which cannot be used in cloud extensions.

**Comment by JesperSchulz** [comment]
PS: Now that this issue is closed, please create a new one if you have alternative suggestions.
