### ISSUE TITLE
[Change Request] Table 5050 "Contact" - CreateCustomer  

### ISSUE THREAD

**Issue by jthoerner-tso** [microsoft/ALAppExtensions#10072]
Hallo 

in the function "CreateCustomer" (BC17.1) is probably a bug or the function has a different behaviour than I expected. 
There is a problem if you have activated the new templates and you specify a specific template in the parameter. 

In this case, the application would still show the new template list, even though a template was already given. 
In my code, this even leads to an error, because page objects are not allowed to be displayed. 

So this is the original code 

![image](https://user-images.githubusercontent.com/63199461/100752363-cf671280-33e8-11eb-90ec-9cbd3ac49585.png)

And that would be a better for my code
![image](https://user-images.githubusercontent.com/63199461/100753145-b4e16900-33e9-11eb-926d-7832adccae02.png)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
