### ISSUE TITLE
[Parameter Request] codeunit 5700 "User Setup Management" - OnBeforeIsPostingDateValidWithSetup(PostingDate, Result, IsHandled);

### ISSUE THREAD

**Issue by iyiannak** [microsoft/ALAppExtensions#10084]
Could you please add the parameter var SetupRecordID: RecordID to the event OnBeforeIsPostingDateValidWithSetup(PostingDate, Result, IsHandled)?

    procedure IsPostingDateValidWithSetup(PostingDate: Date; var SetupRecordID: RecordID) Result: Boolean
    var
        ...
    begin
        OnBeforeIsPostingDateValidWithSetup(PostingDate, Result, IsHandled);
        if IsHandled then
            exit(Result);
        ...
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsPostingDateValidWithSetup(PostingDate: Date; var SetupRecordID: RecordID; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
