### ISSUE TITLE
[Event Request] table 60 "Document Sending Profile" - OnSendCustomerRecordsOnBeforeLookupProfile OnSendVendorRecordsOnBeforeLookupProfile

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#10081]
Could you please fix the call of the following event `OnSendCustomerRecordsOnBeforeLookupProfile`
See issue: #9516
Within the loop I requested the event with the following parameter: **RecRefToSend**
```al
                    RecRefToSend := RecRefSource.Duplicate();
                    RecRefToSend.SetRecFilter();
                    CustomerNo := RecRefToSend.Field(CustomerFieldNo).Value;
                    DocumentNo := RecRefToSend.Field(DocumentFieldNo).Value;
                    OnSendCustomerRecordsOnBeforeLookupProfile(ReportUsage, RecordVariant, CustomerNo); ;//Current
                    OnSendCustomerRecordsOnBeforeLookupProfile(ReportUsage, RecRefToSend, CustomerNo); //NEW
```
Same for the purchase: `OnSendVendorRecordsOnBeforeLookupProfile` within the loop
There I made accidently Copy/Paste mistake.
```al
                    RecRef2.SetRecFilter;
                    VendorNo := RecRef2.Field(VendorFieldNo).Value;
                    DocumentNo := RecRef2.Field(DocumentFieldNo).Value;
                    //OnSendVendorRecordsOnBeforeLookupProfile(ReportUsage, RecordVariant, VendorNo);//Current
                    OnSendVendorRecordsOnBeforeLookupProfile(ReportUsage, RecRef2, VendorNo);//NEW
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
