### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnBeforeNewInvoice

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10080]
Hi, in the Codeunit 90 Purch.-Post, trigger CalcInvoice, would it be possible to get an event OnBeforeNewInVoice, like this :
![image](https://user-images.githubusercontent.com/75368955/100885434-ee31db80-34b2-11eb-9b9e-1cc7b866d0a7.png)
![image](https://user-images.githubusercontent.com/75368955/100879106-54b2fb80-34ab-11eb-8d60-8267b662ac7c.png)
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
