### ISSUE TITLE
[Event Request] Codeunit 5060 DuplicateManagement InsDuplContIndex - OnBeforeOnInsertSearchString

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10099]
[IntegrationEvent(false, false)]
local procedure OnBeforeOnInsertSearchString(var Contact: Record Contact; DuplSearchStringSetup: Record "Duplicate Search String Setup")
    begin
    end;

As we need to fill some more Information in the "Cont. Duplicate Search String" table, because we differentiate between Person or Company Contacts, we need an event like mentioned above.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
