### ISSUE TITLE
Table "Service Order Allocation" - OnBeforeValidateStartEndTime(var Rec: Record "Service Order Allocation"; var IsHandled Boolean)

### ISSUE THREAD

**Issue by CL2-SWECON** [microsoft/ALAppExtensions#10095]
local procedure ValidateStartEndTime()
    begin
        OnBeforeValidateStartEndTime(Rec; IsHandled);
        if IsHandled then 
          exit;
      ...
    end;

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.

**Comment by CL2-SWECON** [comment]
OnBeforeValidateStartEndTime(var Rec: Record "Service Order Allocation"; var IsHandled Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
