### ISSUE TITLE
Table "Standard Service Code" Fieldextension from Code[10] to Code[20] needed

### ISSUE THREAD

**Issue by CL2-SWECON** [microsoft/ALAppExtensions#10098]
Please extend Table "Standard Service Code" Field Code from Code[10] to Code[20] or give us the possibility to overwrite the standard fieldsize.

**Comment by StanPesotskiy** [comment]
The primary key change is not allowed on SQL Azure so we cannot do it.

**Comment by CL2-SWECON** [comment]
We want to do that onPrem, not in Azure.
Can you make it possible for OnPrem?

**Comment by StanPesotskiy** [comment]
No, we have the single code base.

**Comment by StanPesotskiy** [comment]
You can post this as an idea on https://experience.dynamics.com/ideas/ and let others vote for it. 
If this is really needed we can only make the replacement of this table.
