### ISSUE TITLE
Table "Service Header" - OnBeforeCheckBlockedBillToCustomer

### ISSUE THREAD

**Issue by CL2-SWECON** [microsoft/ALAppExtensions#10091]
Table "Service Header" - OnBeforeCheckBlockedBillToCustomer is missing, but needed.
Please add.

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by CL2-SWECON** [comment]
Singnatur which is needed is
OnBeforeCheckBlockedBillToCustomer(var Rec: Record "Service Header"; Customer: Record Customer; var IsHandled: Boolean)

**Comment by StanPesotskiy** [comment]
please also put the place in code where it is called from.

**Comment by CL2-SWECON** [comment]
field(4; "Bill-to Customer No."; Code[20])
        {
            Caption = 'Bill-to Customer No.';
            NotBlank = true;
            TableRelation = Customer;

            trigger OnValidate()
            var
                CustCheckCrLimit: Codeunit "Cust-Check Cr. Limit";
                ConfirmManagement: Codeunit "Confirm Management";
                IsHandled: Boolean;
            begin
                if (xRec."Bill-to Customer No." <> "Bill-to Customer No.") and
                   (xRec."Bill-to Customer No." <> '')
                then begin
                    if HideValidationDialog then
                        Confirmed := true
                    else
                        Confirmed :=
                          ConfirmManagement.GetResponseOrDefault(
                            StrSubstNo(Text005, FieldCaption("Bill-to Customer No.")), true);
                    if Confirmed then begin
                        ServLine.SetRange("Document Type", "Document Type");
                        ServLine.SetRange("Document No.", "No.");
                        if "Document Type" = "Document Type"::Order then
                            ServLine.SetFilter("Quantity Shipped", '<>0')
                        else
                            if "Document Type" = "Document Type"::Invoice then
                                ServLine.SetFilter("Shipment No.", '<>%1', '');

                        if ServLine.FindFirst then
                            if "Document Type" = "Document Type"::Order then
                                ServLine.TestField("Quantity Shipped", 0)
                            else
                                ServLine.TestField("Shipment No.", '');
                        ServLine.Reset();
                    end else
                        "Bill-to Customer No." := xRec."Bill-to Customer No.";
                end;

                GetCust("Bill-to Customer No.");

                IsHandled := false;
                OnBeforeCheckBlocked**BillTo**Customer(Rec, Cust, IsHandled)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
