### ISSUE TITLE
Table Service Header - Signature OnBeforeCheckBlockedCustomer

### ISSUE THREAD

**Issue by CL2-SWECON** [microsoft/ALAppExtensions#10093]
Please add
var Rec: Record "Service Header" 
or 
var Customer: Record Customer
to the signature of OnBeforeCheckBlockedCustomer in table Service Header

We have auto. substitution of some customers which has to be done here before checking blocked.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
