### ISSUE TITLE
Tables "Repair Status", "Service Status Priority Setup" - ENUM "Service Order Status"

### ISSUE THREAD

**Issue by CL2-SWECON** [microsoft/ALAppExtensions#10097]
Please add Enum "Service Order Status" to Table "Repair Status" and "Service Status Priority Setup"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
