### ISSUE TITLE
Table Service Item Line - Getter for HideDialogBox needed

### ISSUE THREAD

**Issue by CL2-SWECON** [microsoft/ALAppExtensions#10090]
There is no getter-procedure to get the HideDialogBox variable.
Please add that.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
