### ISSUE TITLE
[Event Request] Codeunit DuplicateManagement - Function InsDuplCont Events for adding filter criteria before find "Cont. Duplicate Search String" and ""Contact Duplicate"

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10100]
[IntegrationEvent(false, false)]
local procedure OnBeforeFindDuplContSearchString2(var DuplContSearchString: Record "Cont. Duplicate Search String"; DuplContSearchString2: Record "Cont. Duplicate Search String")
    begin
    end

AND

[IntegrationEvent(false, false)]
local procedure OnBeforeFindDuplCont(var DuplContSearchString: Record "Cont. Duplicate Search String")
begin
end;

As we differentiate between contact types person / company we need to add filter criteria fot both

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
