### ISSUE TITLE
Message during posting doesn't appear sometimes

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/ALAppExtensions#10103]
Subscribe any trigger raised in between posting and add a message.

do the posting.
at the start for few days it will appear.

after few days it doesn't.

debugger still goes to that line, but message not appear

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
