### ISSUE TITLE
[Application Request] T79 - Ship-to Post Code / Ship-to City - Onlookup

### ISSUE THREAD

**Issue by fvet** [Microsoft/ALAppExtensions#1010]
Partner Preview 4 contains additional code in the OnLookup tigger on the PostCode / City fields.

`PostCode.LookupPostCode(City,"Post Code",County,"Country/Region Code");`

Code is however not present on the 'Ship-to Post Code' / 'Ship-to-City' field in T79 (Company Information)

**Comment by JesperSchulz** [comment]
Nice catch! Let's get the issue to a team who will fix and backport it, as this repo only is for extensibility related issues in the upcoming release. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.

**Comment by fvet** [comment]
https://partner.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/170090
