### ISSUE TITLE
[Enum Request] "Budget Type"

### ISSUE THREAD

**Issue by dennisroczek** [microsoft/ALAppExtensions#10102]
There are multiple option fields in the database with Budget, Billable, Both Budget and Billable (and sometimes with an empty option).

e.g. in T39 Purchase Line in F 1002 "Job Line Type", but also at multiple other places.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
