### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnBeforeQtyToBeInvoiced 

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10109]
Hi, would it be possible to get an event subscriber in Codeunit 90 Puch Post, procedure OnBeforeQtyToBeInvoiced, like this :
![image](https://user-images.githubusercontent.com/75368955/101153725-180b0f80-3625-11eb-9822-b70e4e970e26.png)
![image](https://user-images.githubusercontent.com/75368955/101153927-51437f80-3625-11eb-9c5a-724105a64c25.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
