### ISSUE TITLE
[Event Modification] Codeunit 90 Purch.-Post - OnCheckExternalDocumentNumberOnAfterSetFilters

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10106]
Hi, would it be possible to modify the event OnCheckExternalDocumentNumberOnAfterSetFilters in codeunit 90 Purch Post to insert a IsHandled parameter, like this : 
![image](https://user-images.githubusercontent.com/73548802/101144061-1129d000-3618-11eb-947c-527edaef4faa.png)
?

Thanks

**Comment by StanPesotskiy** [comment]
please use the existing event OnBeforeCheckExternalDocumentNumber()
