### ISSUE TITLE
[Event Request] Codeunit 80 - Sales-Post - OnBeforePostJobContractLine with JobContractLine 

### ISSUE THREAD

**Issue by dennisroczek** [microsoft/ALAppExtensions#10101]
A follow up to #1457: the global boolean JobContractLine cannot be set from outside. It will be initial filled in PostJobContractLine. Sadly the existing event OnBeforePostJobContractLine is not able to set it. So you cannot Handle the code in that procedure as you cannot set that variable.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
