### ISSUE TITLE
[Parameter Request] codeunit 330 „ReqJnlManagement“ – OnAfterGetDescriptionAndRcptName

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10119]
Could we please have the parameter LastReqLine in  publisher OnAfterGetDescriptionAndRcptNamein of codeunit 330 „ReqJnlManagement“?

```

// >>>>>>>>>>>>>>>>>
//OnAfterGetDescriptionAndRcptName(ReqLine, Description, BuyFromVendorName);
OnAfterGetDescriptionAndRcptName(ReqLine, LastReqLine, Description, BuyFromVendorName);
// <<<<<<<<<<<<<<<<<
```

```
local procedure OnAfterGetDescriptionAndRcptName(var ReqLine: Record "Requisition Line"; var LastReqLine: Record "Requisition Line"; var Description: Text[100]; var BuyFromVendorName: Text[100])
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
