### ISSUE TITLE
[Function Request] Codeunit Sales-Post Function "GetPreviewMode"

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10113]
We have some processes that should only be done, when it is not Preview Mode. Setting is possible in the codeunit but not getting. The event that is causing this request is "OnAfterSalesInvLineInsert" in procedure "PostSalesLine". Would also be ok to have it as additional parameter for that event subscriber - but with a get function, it would be possible to get and use this information everywhere in the document :).

**Comment by SWE-Tina** [comment]
We need it also for the "OnAfterInsertShipmentLine" Event :)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
