### ISSUE TITLE
[Access Request] Page 6510 "Item Tracking Lines" - Variable CurrentSourceType, FormRunMode

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10116]
We already requested with issue [9272]
https://github.com/microsoft/ALAppExtensions/issues/9272
access to variable ItemTrackingCode. As it turned out, this is unfortunately not enough for our purposes. We also need access to the variables CurrentSourceType and FormRunMode.

```
     ...
     protected var
        ...
        // >>>>>>>>>>>>>>>>>>
        FormRunMode: Option ,Reclass,"Combined Ship/Rcpt","Drop Shipment",Transfer;
        CurrentSourceType: Integer;
        ItemTrackingCode: Record "Item Tracking Code";
        // <<<<<<<<<<<<<<<<<<
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
