### ISSUE TITLE
[Parameter Request] codeunit 80 "Sales-Post" publisher OnBeforeCheckCustBlockage parameter TempSalesLine

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10118]
We requested with Issue  [#8784](https://github.com/microsoft/ALAppExtensions/issues/8784) an new event.
There you pointed out that we should use the existing event OnBeforeCheckCustBlockage instead.
But this doesn't work because we don't have access to TempSalesLine, which is absolutely necessary to completely map the functionality.
Can you therefore extend the publisher OnBeforeCheckCustBlockage with the TempSalesLine parameter

```
local procedure CheckCustBlockage(SalesHeader: Record "Sales Header"; CustCode: Code[20]; ExecuteDocCheck: Boolean)
    var
        Cust: Record Customer;
        TempSalesLine: Record "Sales Line" temporary;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        // >>>>>>>>>>>>>>>>>>
        //OnBeforeCheckCustBlockage(SalesHeader, CustCode, ExecuteDocCheck, IsHandled);
        OnBeforeCheckCustBlockage(SalesHeader, TempSalesLineGlobal, CustCode, ExecuteDocCheck, IsHandled);
        // <<<<<<<<<<<<<<<<<<<
        if IsHandled then
            exit;
...
```

```
    [IntegrationEvent(false, false)]
   // >>>>>>>>>>>>>>>>>>
    //local procedure OnBeforeCheckCustBlockage(SalesHeader: Record "Sales Header"; CustCode: Code[20]; var ExecuteDocCheck: Boolean; var IsHandled: Boolean)
    local procedure OnBeforeCheckCustBlockage(SalesHeader: Record "Sales Header"; var TempSalesLineGlobal: Record "Sales Line" temporary; CustCode: Code[20]; var ExecuteDocCheck: Boolean; var IsHandled: Boolean)
    // <<<<<<<<<<<<<<<<<<<
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
