### ISSUE TITLE
[Event Request] Codeunit Sales-Post Function "CheckAndUpdate" Event OnAfterReleaseSalesDocument

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10112]
[EventSubscriber(ObjectType::Codeunit, Codeunit::"Sales-Post", 'OnAfterReleaseSalesDocument', '', true, true)]
    local procedure "Sales-Post_OnAfterReleaseSalesDocument"
    (
        SalesHeader: Record "Sales Header";
        PreviewMode: Boolean
    )

We need to create and calculate things for further processes after sales document is released and before further steps will be proceeded. Would be good to have the possibility to control steps to be proceeded after releasing a sales doc as well as it is possible on before releasing it.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
