### ISSUE TITLE
[Request for External] codeunit 99000787 "Create Prod. Order Lines" procedure CopyFromSalesOrder

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10123]
Can we please have external access to the procedure CopyFromSalesOrder of codeunit 99000787 "Create Prod. Order Lines"

```
    // <<<<<<<<<<<<<<<<
    // local procedure CopyFromSalesOrder(SalesHeader: Record "Sales Header"): Boolean
    procedure CopyFromSalesOrder(SalesHeader: Record "Sales Header"): Boolean
    var
        SalesPlanLine: Record "Sales Planning Line" temporary;
        Location: Record Location;
        LeadTimeMgt: Codeunit "Lead-Time Management";        
        ...
    // >>>>>>>>>>>>>>>>

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
