### ISSUE TITLE
OIOUBL app cannot be installed on fresh environment 

### ISSUE THREAD

**Issue by cvale** [microsoft/ALAppExtensions#10125]
Please check the following line:

https://github.com/microsoft/ALAppExtensions/blob/9a2dc1ae50e6eeb0032763dc5217ba7482e4ec5d/OIOUBL/src/upgrade/COD13623.MigrateToExtensionV2.al#L440

This approach does not allow a clean install of the app (Record "OIOUBL Profile" does not exist)!

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by cvale** [comment]
Well guys, this is YOUR bug?! Why won't you do something about it?

**Comment by StanPesotskiy** [comment]
This is not the right channel for reporting this. Here we mostly working on adding new events.
Something more complex should go the standard procedure that includes the whole process of fixing bugs properly.
