### ISSUE TITLE
[Request for External] codeunit 333 "Req. Wksh.-Make Order" publisher OnBeforeCheckRequisitionLines include sender

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10120]
Can we please have access to the sender codeunit in publisher OnBeforeCheckRequisitionLines of codeunit 333 "Req. Wksh.-Make Order"?
We need access to some procedures (CheckRecurringReqLine, CheckRequisitionLine) in the subscriber codeunit.

```
// >>>>>>>>>>>>>>>>>>>>>>
    //[IntegrationEvent(false, false)]
    [IntegrationEvent(true, false)]
    // <<<<<<<<<<<<<<<<<<<<<
    local procedure OnBeforeCheckRequisitionLines(var RequisitionLine: Record "Requisition Line"; var StartLineNo: Integer; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
