### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnAfterInsertPostedHeaders 

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10126]
Hi, in the Codeunit 90 Purch.-Post, would it be possible to add the argument PurchSetup in the event OnAfterInsertPostedHeaders like this:
![image](https://user-images.githubusercontent.com/75368955/101174170-cf168380-3643-11eb-900d-bf2dd6e2d2df.png)
![image](https://user-images.githubusercontent.com/75368955/101174630-7398c580-3644-11eb-864e-0617038d38ba.png)
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
