### ISSUE TITLE
BUG | BC Performance Testkit | codeunit: 149000 "BCPT Start Tests"

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/ALAppExtensions#10135]
While testing with the BCPT i found a serious bug.

there are 2 ways to let you Codeunit run, in session with iterations or on foreground.

the bug is with the foreground run. it only runs 1 foreground codeunit while i have 3 foreground codeunits in the suite.
*********************
local procedure StartBenchmarkTests(BCPTHeader: Record "BCPT Header")
    var
....
...
      BCPTHeader.Modify();
        Commit();
        BCPTLine.SetRange("Run in Foreground", true);
        **if BCPTLine.FindSet() then
            Codeunit.Run(Codeunit::"BCPT Role Wrapper", BCPTLine);**
    end;
*******************
the problem is with the findset without a repeat until around the codeunit run. 
so this will end up always run 1 codeunit foreground even if i have mutliple in the setup.
like here
![image](https://user-images.githubusercontent.com/48794854/101331128-d1f7bb00-3873-11eb-9e43-53e24217a4be.png)
i want these codeunits to run serial for whatever reason. but only CU will run.

solution:
*****************
local procedure StartBenchmarkTests(BCPTHeader: Record "BCPT Header")
    var
....
...
      BCPTHeader.Modify();
        Commit();
        BCPTLine.SetRange("Run in Foreground", true);
        **if BCPTLine.FindSet() then
            repeat
                  Codeunit.Run(Codeunit::"BCPT Role Wrapper", BCPTLine);
            until BCPTLine.NEXT() = 0;**
    end;
*************************

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
