### ISSUE TITLE
[Event Request] FR codeunit 10860 "Payment Management" - ProcessPaymentStep

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/ALAppExtensions#10137]
procedure ProcessPaymentStep(PaymentHeaderNo: Code[20]; PaymentStep: Record "Payment Step");

Should be great to add an event so we can include more functionnalities (base on Enum) :

**OnBeforeActionType(PaymentLine, Step, ActionValidated, Handled)**  (As an example)
CASE Step."Action Type" OF
  Step."Action Type"::None:
...
END;
**OnAfterActionType(PaymentLine, Step, ActionValidated)**  (As an example)

Generally, there is quite few events at all in the French Payment Slip module. Could be really interesting to get some more.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
