### ISSUE TITLE
Option to Enum Record::"Requisition Line" Field "Type"

### ISSUE THREAD

**Issue by SweJo** [microsoft/ALAppExtensions#10134]
Field Type ist still an Option. We need to make an Enum-Extension and use them in serveral Objects.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
