### ISSUE TITLE
[Access Request] table 5050 Contact procedure UpdateCustomerFromConversionTemplate

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10138]
We need access to the procedure UpdateCustomerFromConversionTemplate of table 5050 Contact.
Can you please make it available for us?

   ```
// >>>>>>>>>>>
    //local procedure UpdateCustomerFromConversionTemplate(var Cust: Record Customer; CustTemplate: Record "Customer Template")
    procedure UpdateCustomerFromConversionTemplate(var Cust: Record Customer; CustTemplate: Record "Customer Template")
    // <<<<<<<<<<<
```

**Comment by AlexanderYakunin** [comment]
This function will be removed once the Feature Key is removed. Will be replaced by ApplyCustomerTemplate() from CustomerTemplMgt codeunit.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
