### ISSUE TITLE
[Access Request] table 5050 Contact procedure UpdateQuotes

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10139]
We need access to the procedure UpdateQuotes of table 5050 Contact.
Can you please make it available for us?

   ```
// >>>>>>>>>>>
    //local procedure UpdateQuotes(Customer: Record Customer; CustomerTemplate: Code[10])
    procedure UpdateQuotes(Customer: Record Customer; CustomerTemplate: Code[10])
    // <<<<<<<<<<<
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
