### ISSUE TITLE
Why is CreateVendorLink() not usable in Contact Card in BC SaaS?

### ISSUE THREAD

**Issue by deadmouse** [microsoft/ALAppExtensions#10132]
In Contact Card, why is action(Vendor) in group("Link with existing") hidden if CLIENTTYPE is not Windows?

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
