### ISSUE TITLE
Add Default DropDown FieldGroups for Table  Item Variant, Item Cross Reference 

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#10149]
@JesperSchulz 

**Describe the bug**

Missing Fieldgroups on Table Item Variant and Item Cross Reference so unable to extend these with our field, these tables are hot tab

**To Reproduce**
Steps and to reproduce the behavior:
Check Table "Item Variants" and "Item Cross Reference" fieldgroups are empty

**Expected behavior**

Tried to exendt fieldgroups following: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-field-groups

Please add these to the next minor

**Screenshots**

**5. Versions:**
 - AL Language: 
 - Business Central:

**Comment by JesperSchulz** [comment]
Transferred issue, as this issue isn't related to the AL compiler/language, but to our AL Application. We will take a look at your issue shortly!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for releasee 17.
