### ISSUE TITLE
[Event Request] Table "Report Selections" - SaveReportAsHTML

### ISSUE THREAD

**Issue by GOB-Andrea** [microsoft/ALAppExtensions#10147]
Hey, would it be possible to add a publisher to the following function?

Table 77- "Report Selections" - SaveReportAsHTML

```
    local procedure SaveReportAsHTML(ReportID: Integer; RecordVariant: Variant; LayoutCode: Code[20]; ReportUsage: Enum "Report Selection Usage") FilePath: Text[250]
    var
        ReportLayoutSelection: Record "Report Layout Selection";
        FileMgt: Codeunit "File Management";
    begin
        OnBeforeSetReportLayout(RecordVariant, ReportUsage.AsInteger());
        FilePath := CopyStr(FileMgt.ServerTempFileName('html'), 1, 250);

	// BEGIN NEW 
	OnBeforeSetTempLayoutSelected(RecordVariant, ReportUsage, ReportID, LayoutCode);
	// END NEW 
        ReportLayoutSelection.SetTempLayoutSelected(LayoutCode);
        REPORT.SaveAsHtml(ReportID, FilePath, RecordVariant);
        ReportLayoutSelection.SetTempLayoutSelected('')

        Commit();
    end;
    
    // BEGIN NEW
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetTempLayoutSelected(RecordVariant: Variant; ReportUsage: Enum "Report Selection Usage"; var ReportID: Integer; var LayoutCode: Code[20])
    begin
    end;
    // END NEW
```
If you give us access, we would be able to change the report ID and layout code before printing. We consider it necessary, because we want to set up the layouts dependent on languages (new field). The language code we want to filter on comes from the record that is printed, but it is not included in any publisher or function when you determine the layout. Therefore, this would be the moment we have all the information we need to determine the layout ourselves.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
