### ISSUE TITLE
[Application Request - Event Request] Table 36/38 - Conditional Location Code (UserSetupMgt.GetLocation)

### ISSUE THREAD

**Issue by fvet** [Microsoft/ALAppExtensions#1014]
T36 / T38 contain various places where the Location Code is set based on the **UserSetupMgt.GetLocation**. Based on the vendor/customer location / resp. center location, the location code is updated. However, we'd like to avoid  update of the 'location code' in case of changing customer with no location and a user / resp. center with out location.

```
IF UserSetupMgt.GetLocation(0,Cust."Location Code","Responsibility Center") <> '' THEN // ADDED - only validate location if function returns a value
VALIDATE("Location Code",UserSetupMgt.GetLocation(0,Cust."Location Code","Responsibility Center"));
```
Adding a publisher seems overkill (since there's already an before/after, which can't be used)

An alternative would be providing a function UpdateLocationCode(0,Cust."Location Code","Responsibility Center") and foresee an OnBeforeUpdateLocationCode publisher with Handled pattern to allow skip of this code.

**Comment by SureshMukhi** [comment]
Thank you for this!!!
