### ISSUE TITLE
[Access Request] - Table 37 - CalcShipmentDateForLocation

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#10155]
Could you make this function global? CalcShipmentDateForLocation

![image](https://user-images.githubusercontent.com/35260264/101469826-81509280-3945-11eb-8e42-26603519dc08.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
