### ISSUE TITLE
[EventRequest] Table 5405 Production Order - OnBeforeTestNoSeries

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#10152]
Requesting a new event publisher on Table 5405 Production Order

Event
`OnBeforeTestNoSeries(ProductionOrder : Record "Production Order"; MfgSetup : Record "Manufacturing Setup"; VAR IsHandled : Boolean)`

**Code**
## [External] TestNoSeries()
```
MfgSetup.GET;
```
**>>> New Code**
```
IsHandled := FALSE;
OnBeforeTestNoSeries(Rec, MfgSetup, IsHandled);
IF IsHandled THEN
  EXIT;
```
**<<< New Code End**
```
CASE Status OF
  Status::Simulated:
    MfgSetup.TESTFIELD("Simulated Order Nos.");
  Status::Planned:
    MfgSetup.TESTFIELD("Planned Order Nos.");
  Status::"Firm Planned":
    MfgSetup.TESTFIELD("Firm Planned Order Nos.");
  Status::Released:
    MfgSetup.TESTFIELD("Released Order Nos.");
END;

In Our Solution we have a link between Jobs and Production. 
For Production Orders created out of Jobs we want to work with a Custom setup field which holds the No Series Code for new to create "Job" Production Orders. 
Therefore we need to have this publisher to extend. 
Please add the requested publisher.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
