### ISSUE TITLE
[Access Request] - Codeunit 5701 "Item Subst." - CalcCustPrice

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#10156]
Could you make CalcCustPrice as a global function?

![image](https://user-images.githubusercontent.com/35260264/101470138-e73d1a00-3945-11eb-9ff0-a1e319694717.png)

**Comment by AlexanderYakunin** [comment]
This procedure use global variable TempItemSubstitution: Record "Item Substitution" temporary. How you are going to use it after call of this procedure? Please provide more details.

**Comment by auzhhv** [comment]
> This procedure use global variable TempItemSubstitution: Record "Item Substitution" temporary. How you are going to use it after call of this procedure? Please provide more details.

Could you create a wrapper procedure. Like GetSalesHeader in table "Sales Line"?
```
procedure CalcCustPrice(var TempItemSubstitution: Record "Item Substitution" temporary; var ItemSubstitution: Record "Item Substitution"; var Item: Record Item; ShipmentDate: Date)
...
```

In sales line:
![image](https://user-images.githubusercontent.com/46031720/101733508-4a05f100-3abf-11eb-918b-9758bc99c2d2.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
