### ISSUE TITLE
[EventRequest] Codeunit 1002 Job Create-Invoice - OnAfterCreateSalesHeaderOnBeforeFindTempJobPlanningLine

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#10154]
![image](https://user-images.githubusercontent.com/35260264/101467823-23bb4680-3943-11eb-9b6b-273e0cf5dabc.png)

![image](https://user-images.githubusercontent.com/35260264/101467868-3170cc00-3943-11eb-986a-a842e3584346.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
