### ISSUE TITLE
[Event Request] Codeunit 2000040 "Coda Import Management" – New event “OnAfterInitCodaImport”

### ISSUE THREAD

**Issue by vanmito** [microsoft/ALAppExtensions#10164]
Hello,

**Could we please have a new event “OnAfterInitCodaImport” in function “InitCodaImport”, Codeunit 2000040 "Coda Import Management"?

    procedure InitCodaImport(BankAccNo: Code[20])
    var
        EnterpriseNoDec: Decimal;
    begin
        BankAcc.Get(BankAccNo);

        with CompanyInfo do begin
            EnterpriseNo := '';
            Get;
            // numbers in VAT No
            EnterpriseNo := PaymJnlManagement.ConvertToDigit("Enterprise No.", MaxStrLen(EnterpriseNo));
            if EnterpriseNo = '' then
                EnterpriseNo := '0';
            if Evaluate(EnterpriseNoDec, EnterpriseNo) then
                if EnterpriseNoDec = 0 then
                    EnterpriseNo := PadStr('', 11, '0')
                else begin
                    if not EnterpriseNoCheck.MOD97Check("Enterprise No.") then
                        Error(Text000);
                    EnterpriseNo := '0' + EnterpriseNo;
                end;
        end;
        Clear(LineCounter);
        Clear(TotalDebit);
        Clear(TotalCredit);

        // --- Begin New Code ---
        OnAfterInitCodaImport(BankAcc, EnterpriseNo, LineCounter, TotalDebit, TotalCredit);
        // --- End New Code ---

    end;

...

...

[IntegrationEvent(false, false)]
local procedure OnAfterInitCodaImport(var BankAcc: record "Bank Account"; var EnterpriseNo: Text[11]; var LineCounter: array[2] of Integer; var TotalDebit: array[2] of Decimal; var TotalCredit: array[2] of Decimal)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
