### ISSUE TITLE
[Event Change]  OnBeforeOnDatabaseModify - codeunit 49 GlobalTriggerManagement

### ISSUE THREAD

**Issue by Nagaraju17** [microsoft/ALAppExtensions#10162]
Hi,
We have a scenario like copying data from one company to the other dynamically using standard triggers 
**OnAfterOnDatabaseInsert,OnAfterOnDatabaseModify,OnAfterOnDatabaseDelete,OnAfterOnDatabaseRename**  (from CU 49)
But when insert or modify happens, It is executing the standard event subscriber functions (OnDatabaseInsert,OnDatabaseModify,OnDatabaseDelete,OnDatabaseRename) in codeunit 49 GlobalTriggerManagement. The code which is in this trigger function executing multiple times while moving data to other company . It would be better if we have extra parameter in the standard publishers to skip the execution.

For Eg:  OnAfterOnDatabaseModify 

![image](https://user-images.githubusercontent.com/30176345/101473106-6c88f480-396f-11eb-95b4-fc67d480e6ac.png)

We would like to have this change in all  Subscriber event triggers : 
OnDatabaseInsert,
OnDatabaseModify,
OnDatabaseDelete,
DatabaseRename

Thanks!
Nagaraju

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
