### ISSUE TITLE
[Protection Level] Codeunit "Sales-Post" Function "PostItemChargePerShpt" remove local

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10169]
We have some more "Applies-to Doc. Type" values that we treat in the case-block in the PostItemChargeLine or better to say with the "OnAfterPostItemChargeLine"-Event from that function. The two cases we have to add call the function "PostItemChargePerShpt" of "Sales-Post" Codeunit. Due to the protection level, we don't have the possibility to use this standard function anymore. We don't want to have a duplication of this, therefore we ask to remove local to make it reachable from the events. 

Code in the event that requires this:

[EventSubscriber(ObjectType::Codeunit, Codeunit::"Sales-Post", 'OnAfterPostItemChargeLine', '', true, true)]
    local procedure "Sales-Post_OnAfterPostItemChargeLine"
    (
        SalesLine: Record "Sales Line";
        SalesLineACY: Record "Sales Line"
    )
    var
        TempItemChargeAssgntSales: Record "Item Charge Assignment (Sales)" temporary;
begin
...
repeat
 CASE TempItemChargeAssgntSales."Applies-to Doc. Type" OF
  TempItemChargeAssgntSales."Applies-to Doc. Type"::Service:
  SalesPost.PostItemChargePerShpt(SalesHeader, SalesLine);
  TempItemChargeAssgntSales."Applies-to Doc. Type"::"Item Ledger Entry":
  SalesPost.PostItemChargePerShpt(SalesHeader, SalesLine);
end;
end;
until TempItemChargeAssgntSales.next() = 0;

**Comment by AlexanderYakunin** [comment]
Should we simple wrap this condition into procedure and let you extend this:

Before:
                case TempItemChargeAssgntSales."Applies-to Doc. Type" of
                    TempItemChargeAssgntSales."Applies-to Doc. Type"::Shipment:

After
                case TempItemChargeAssgntSales."Applies-to Doc. Type" of
                    IsItemChargeAppliesToShipment(TempItemChargeAssgntSales):

local procedure IsItemChargeAppliesToShipment(TempItemChargeAssgntSales) IsShipment: Boolean
begin
      IsShipment := TempItemChargeAssgntSales."Applies-to Doc. Type" = TempItemChargeAssgntSales."Applies-to Doc. Type"::Shipment;
      OnAfterIsItemChargeAppliesToShipment(TempItemChargeAssgntSales, IsShipment),
      exit(IsShipment);
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
