### ISSUE TITLE
[EventRequest] Codeunit 7322 Create Inventory Pick/movement - New Publishers 

### ISSUE THREAD

**Issue by TjaTrimit** [microsoft/ALAppExtensions#10165]
Hello 
To use the new procedure “RunCreatePickOrMoveLine” in Codeunit “Create Inventory Pick/Movement” (CU7322) we need to be able to set and get the “WareHouse Activity Header” and the “Warehouse Request”

This could be done without breaking change by adding 2 publisher  - 1 in the beginning and one in the end - both “WareHouse Activity Header” and the “Warehouse Request” records declared as VAR

(Could also be in the procedure it calls CreatePickOrMoveLine – adding a new in the start and on in the end (or instead of a new in the end - by adding parmeters to the last publisher OnAfterInsertWhseActivLine)

See the following screenshot for clarification 
![image](https://user-images.githubusercontent.com/54017538/101488513-ff219780-395f-11eb-8a2e-4b5c210f5870.png)

as seen on the screenshot, we would like those two new publishers to be called
1. OnBeforeRunCreatePickMoveLine(WhseActiveHeader, WhseRequest);
2. OnAfterRunCreatePickMoveLine(WhseActiveHeader, WhseRequest);

NOTE that its important that both WhseActiveHeader and WhseRequest is declared as VAR in both publishers

**Comment by RichardPostborg** [comment]
NOTE that its important that both WhseActiveHeader and WhseRequest is declared as VAR in both publishers

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
