### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnAfterSetPostingFlags

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10161]
Hi, would it be possible to get an event OnAfterSetPostingFlags in procedure SetPostingFlags (codeunit 90 Purch-Post), like this
![image](https://user-images.githubusercontent.com/73548802/101474646-be1f8800-394b-11eb-9a79-fea46d137118.png)
![image](https://user-images.githubusercontent.com/73548802/101474785-ddb6b080-394b-11eb-9467-31496cf38186.png)
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
