### ISSUE TITLE
[Field Request] "Sales Invoice Header", "Sales Cr. Memo Header" and "Sales Shipment Header"  IC-Fields  of Sales Header 

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10171]
Would be great if you could provide the IC-Fields of Sales Header in the posted tables. It would reduce errors and additional treatment when using Transferfields. 

- "Send IC Document";
- "IC Status"
- "Sell-to IC Partner Code"
- "Bill-to IC Partner Code"
- "IC Direction"

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
