### ISSUE TITLE
[Access Request] - Codeunit 11603 "EFT Management" - Various utility functions

### ISSUE THREAD

**Issue by shuyusheng** [microsoft/ALAppExtensions#10176]
We are implementing custom EFT functionality and would like the following function made available for extension development.
```
procedure Date2Text(Date: Date; Length: Integer): Text[6]
procedure ClearText(Text: Text[250]): Text[250]
procedure NFL(Text: Text[250]; Length: Integer): Text[250]
procedure TFL(Text: Text[250]; Length: Integer): Text[250]
procedure TFR(Text: Text[250]; Length: Integer): Text[250]
procedure BLK(Length: Integer): Text[250]
procedure Value1(Dec: Decimal; Length: Integer): Text[250]
procedure Value100(Dec: Decimal; Length: Integer): Text[250] 
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
