### ISSUE TITLE
[Application Request] Table 225 Postcode - Validate City

### ISSUE THREAD

**Issue by fvet** [Microsoft/ALAppExtensions#1017]
The OnValidate trigger on the field City in table 225 contains a test on 'Code'. In certain (African) countries there is no postcode and only the City field is registered. Please remove this test, either provide support to omit the test via events.

`TESTFIELD(Code);`

**Comment by JesperSchulz** [comment]
We cannot patch this easily, as code is part of the primary key. This would need a redesign/design change request, which exceeds the boundaries of issues in this repo. Please submit your idea on our ideas site (https://aka.ms/bcideas) or append to already existing idea about address refactoring.

**Comment by fvet** [comment]
https://experience.dynamics.com/ideas/idea/?ideaid=3fab5ab8-8e3a-e911-867a-0003ff68933e
