### ISSUE TITLE
[Event Request] Codeunit 427 ICInboxOutboxMgt

### ISSUE THREAD

**Issue by jstresinka** [microsoft/ALAppExtensions#10178]
Could you please add an event  OnMoveOutboxTransToHandledOutboxOnBeforeICOutboxPurchaseLineDelete  in Codeunit 427 (ICInboxOutboxMgt) in function MoveOutboxTransToHandledOutbox   before ICOutboxJnlLine.Delete()  ?  There is an similar event  OnMoveOutboxTransToHandledOutboxOnBeforeICOutboxSalesLineDelete  for sales line.
Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
