### ISSUE TITLE
Event on Codeunit 6500 procedure CopyHandledItemTrkgToInvLine

### ISSUE THREAD

**Issue by RudyJanssens** [microsoft/ALAppExtensions#10172]
procedure CopyHandledItemTrkgToInvLine(FromSalesLine: Record "Sales Line"; ToSalesInvLine: Record "Sales Line")
    var
        ItemEntryRelation: Record "Item Entry Relation";
    begin
        // Used for combined shipment/returns:
        if FromSalesLine.Type <> FromSalesLine.Type::Item then
            exit;
        OnBeforeCopyHandledItemTrkgToInvLine(FromSalesLine,ToSalesInvLine,Handled);
        IF Handled THEN
            EXIT;

        case ToSalesInvLine."Document Type" of
            ToSalesInvLine."Document Type"::Invoice:
                begin ….

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCopyHandledItemTrkgToInvLine(FromSalesLine: Record "Sales Line"; var ToSalesInvLine: Record "Sales Line",var IsHandled: boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
