### ISSUE TITLE
[Enum request] Table "Sales Header" Field "IC Status"

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10170]
The field is still an option, that leads to several warnings and conversion issues. Please provide an enum for that field. Thanks :).

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
