### ISSUE TITLE
Event on Codeunit 99000845 procedure CheckQuantityIsCompletelyReleased

### ISSUE THREAD

**Issue by RudyJanssens** [microsoft/ALAppExtensions#10173]
local procedure CheckQuantityIsCompletelyReleased(QtyToRelease: Decimal; DeleteAll: Boolean; CurrentItemTrackingSetup: Record "Item Tracking Setup"; ReservEntry: Record "Reservation Entry")
    begin
        OnBeforeCheckQuantityCompletelyReleased(ItemTrackingHandling,QtyToRelease,DeleteAll,CurrentSerialNo,CurrentLotNo,ReservEntry,IsHandled);
        IF IsHandled THEN
            EXIT;
        
        if QtyToRelease = 0 then
            exit;
 …..

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckQuantityCompletelyReleased(ItemTrackingHandling : Integer;QtyToRelease : Decimal;DeleteAll : Boolean;CurrentSerialNo : Code[20];CurrentLotNo : Code[20];ReservEntry : Record "Reservation Entry";VAR IsHandled : Boolean)
    begin
    end;

**Comment by StanPesotskiy** [comment]
Parameters CurrentSerialNo and CurrentLotNo you mentioned do not exist in the codeunit. Please check the requested code.

**Comment by RudyJanssens** [comment]
ok, this were parameters of NAV2017, for BC it should be

    local procedure CheckQuantityIsCompletelyReleased(QtyToRelease: Decimal; DeleteAll: Boolean; CurrentItemTrackingSetup: Record "Item Tracking Setup"; ReservEntry: Record "Reservation Entry")
    begin
        OnBeforeCheckQuantityCompletelyReleased(ItemTrackingHandling,QtyToRelease,DeleteAll,CurrentItemTrackingSetup,ReservEntry,IsHandled);
        IF IsHandled THEN
        EXIT;        
  
        if QtyToRelease = 0 then
            exit;

        if ItemTrackingHandling = ItemTrackingHandling::None then begin ……

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckQuantityCompletelyReleased(QtyToRelease: Decimal; DeleteAll: Boolean; CurrentItemTrackingSetup: Record "Item Tracking Setup"; ReservEntry: Record "Reservation Entry";var IsHandled: boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
