### ISSUE TITLE
[Event Request] Codeunit "Item Charge Assgnt. (Sales)" Function "AssignByWeight" Event OnBeforeTempItemChargeAssgntSalesDelete

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10184]
In case QtyRemainder is not 0, we proceed some further steps to handle rounding differences after everything is handled and calculated. To still be able to do this, we need an event like  "OnBeforeTempItemChargeAssgntSalesDelete".

   [IntegrationEvent(false, false)]
    local procedure OnBeforeTempItemChargeAssgntSalesDelete(var ItemChargeAssignmentSales: Record "Item Charge Assignment (Sales)"; QtyRemainder: Decimal; QtyToAssign: Decimal)
    begin
    end;

Placement in code:
```
local procedure AssignByWeight(var ItemChargeAssignmentSales: Record "Item Charge Assignment (Sales)"; Currency: Record Currency; TotalQtyToAssign: Decimal)
    var
        TempItemChargeAssgntSales: Record "Item Charge Assignment (Sales)" temporary;
        LineArray: array[3] of Decimal;
        TotalGrossWeight: Decimal;
        QtyRemaining: Decimal;
        AmountRemaining: Decimal;
        QtyRemainder: Decimal;
        QtyToAssign: Decimal;
    begin
     ...
        if TempItemChargeAssgntSales.FindSet(true) then begin
            repeat
                GetItemValues(TempItemChargeAssgntSales, LineArray);
                if TotalGrossWeight <> 0 then
                    TempItemChargeAssgntSales."Qty. to Assign" :=
                        (TotalQtyToAssign * LineArray[2] * LineArray[1]) / TotalGrossWeight + QtyRemaining
                else
                    TempItemChargeAssgntSales."Qty. to Assign" := 0;
                AssignSalesItemCharge(ItemChargeAssignmentSales, TempItemChargeAssgntSales, Currency, QtyRemaining, AmountRemaining);
            until TempItemChargeAssgntSales.Next = 0;
   **OnBeforeTempItemChargeAssgntSalesDelete**
        TempItemChargeAssgntSales.DeleteAll;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
