### ISSUE TITLE
[Event Request] Codeunit "Item Charge Assgnt. (Sales)" Function "AssignByWeight" Event OnAfterCalcTotalGrossWeight

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10183]
[IntegrationEvent(false, false)]
    local procedure OnAfterCalcTotalGrossWeight(var ItemChargeAssignmentSales: Record "Item Charge Assignment (Sales)"; TotalGrossWeight: Decimal)
    begin
    end;

We need an error message when TotalGrossWeight is 0, therefore and for further treatments after calculating the TotalGrossWeight an event would be needed. 

Placement in code:

```
    local procedure AssignByWeight(var ItemChargeAssignmentSales: Record "Item Charge Assignment (Sales)"; Currency: Record Currency; TotalQtyToAssign: Decimal)
    var
        TempItemChargeAssgntSales: Record "Item Charge Assignment (Sales)" temporary;
        LineArray: array[3] of Decimal;
        TotalGrossWeight: Decimal;
        QtyRemaining: Decimal;
        AmountRemaining: Decimal;
        QtyRemainder: Decimal;
        QtyToAssign: Decimal;
    begin
        repeat
            if not ItemChargeAssignmentSales.SalesLineInvoiced then begin
                TempItemChargeAssgntSales.Init;
                TempItemChargeAssgntSales := ItemChargeAssignmentSales;
                TempItemChargeAssgntSales.Insert;
                GetItemValues(TempItemChargeAssgntSales, LineArray);
                TotalGrossWeight := TotalGrossWeight + (LineArray[2] * LineArray[1]);
            end;
        until ItemChargeAssignmentSales.Next = 0;

**OnAfterCalcTotalGrossWeight(ItemChargeAssignmentSales, TotalGrossWeight);**
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
