### ISSUE TITLE
[Event Request] Codeunit "Item Charge Assgnt. (Purch.)" Function "AssignByWeight" Event OnAfterCalcTotalGrossWeight

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10186]
[IntegrationEvent(false, false)]
local procedure OnAfterCalcTotalGrossWeight(var ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)"; TotalGrossWeight: Decimal)
begin
end;

We need an error message when TotalGrossWeight is 0, therefore and for further treatments after calculating the TotalGrossWeight an event would be needed.

Placement in code:

```
   local procedure AssignByWeight(var ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)"; Currency: Record Currency; TotalQtyToAssign: Decimal)
    var
        TempItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)" temporary;
        LineAray: array[3] of Decimal;
        TotalGrossWeight: Decimal;
        QtyRemainder: Decimal;
        AmountRemainder: Decimal;
        QtyToAssign: Decimal;
    begin
        repeat
            if not ItemChargeAssgntPurch.PurchLineInvoiced then begin
                TempItemChargeAssgntPurch.Init;
                TempItemChargeAssgntPurch := ItemChargeAssgntPurch;
                TempItemChargeAssgntPurch.Insert;
                GetItemValues(TempItemChargeAssgntPurch, LineAray);
                TotalGrossWeight := TotalGrossWeight + (LineAray[2] * LineAray[1]);
            end;
        until ItemChargeAssgntPurch.Next = 0;
**OnAfterCalcTotalGrossWeight(ItemChargeAssgntPurch, TotalGrossWeight);**
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
