### ISSUE TITLE
[Event Request] Codeunit "Item Charge Assgnt. (Purch.)" Function "AssignByWeight" Event OnBeforeTempItemChargeAssgntPurchDelete

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10185]
In case QtyRemainder is not 0, we proceed some further steps to handle rounding differences after everything is handled and calculated. To still be able to do this, we need an event like "OnBeforeTempItemChargeAssgntPurchDelete".

[IntegrationEvent(false, false)]
local procedure OnBeforeTempItemChargeAssgntPurchDelete(var ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)"; QtyRemainder: Decimal; QtyToAssign: Decimal)
begin
end;

Placement in code:

```
local procedure AssignByWeight(var ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)"; Currency: Record Currency; TotalQtyToAssign: Decimal)
    var
        TempItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)" temporary;
        LineAray: array[3] of Decimal;
        TotalGrossWeight: Decimal;
        QtyRemainder: Decimal;
        AmountRemainder: Decimal;
        QtyToAssign: Decimal;
    begin
     ...
            repeat
                GetItemValues(TempItemChargeAssgntPurch, LineAray);
                if TotalGrossWeight <> 0 then
                    TempItemChargeAssgntPurch."Qty. to Assign" :=
                        (TotalQtyToAssign * LineAray[2] * LineAray[1]) / TotalGrossWeight + QtyRemainder
                else
                    TempItemChargeAssgntPurch."Qty. to Assign" := 0;
                AssignPurchItemCharge(ItemChargeAssgntPurch, TempItemChargeAssgntPurch, Currency, QtyRemainder, AmountRemainder);
            until TempItemChargeAssgntPurch.Next = 0;
 **OnBeforeTempItemChargeAssgntPurchDelete**
        TempItemChargeAssgntPurch.DeleteAll;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
