### ISSUE TITLE
[Request for external] codeunit 1280 "Map Currency Exchange Rate" - AssignValue

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#10181]
Can you remove "local" from procedure AssignValue in codeunit 1280 "Map Currency Exchange Rate".

**Comment by AlexanderYakunin** [comment]
This is TryFunction and it should be local. See here https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-tryfunction-attribute
