### ISSUE TITLE
[Event Request] Codeunit 5790 Available to Promise - OnBeforeCalcReservedRequirement

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10191]
Hi, in the Codeunit 5790 "Available to Promise", in the procedure CalcReservedRequirement, we would like to add our code instead of the standard code in the procedure. To do so, we would need an event publisher and a IsHandled flag, like this :

![image](https://user-images.githubusercontent.com/34645582/101754456-0bc6fc80-3ad4-11eb-94b2-636f3df852eb.png)

With this event publisher :
![image](https://user-images.githubusercontent.com/34645582/101754393-fbaf1d00-3ad3-11eb-9f31-10dd168814d7.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
