### ISSUE TITLE
[Event Request] Table 7302 "Bin Content" - OnCalcTotalQtyAvailToTakeOnBeforeExit

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10195]
Hi, in the Table 7302 "Bin Content", in the procedure CalcTotalQtyAvailToTake, we would like to add our code in the procedure just before the exit() method. To do so, we would need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/101765437-97935580-3ae1-11eb-9dbf-5f3603755ac6.png)

With the event integration : 
![image](https://user-images.githubusercontent.com/34645582/101765395-8a766680-3ae1-11eb-8ae9-5072c8f00dde.png)

Do you think it is possible ?

Thank for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
