### ISSUE TITLE
[Event Request] Table T38 / Field 20 "Posting Date": OnValidatePostingDateOnBeforeAssignDocumentDate

### ISSUE THREAD

**Issue by RaKuNbg** [microsoft/ALAppExtensions#10193]
Please insert a new publisher in Table38 in the validate trigger of field "Posting Date" according to the Sales Header

                IsHandled := false;
                OnValidatePostingDateOnBeforeAssignDocumentDate(Rec, IsHandled);
                if not IsHandled then
                    if "Incoming Document Entry No." = 0 then
                        Validate("Document Date", "Posting Date");

to avoid overwriting the "Document Date"

See also 
https://experience.dynamics.com/ideas/idea/?ideaid=46f57ba8-26ce-e911-b083-0003ff68be0c

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
