### ISSUE TITLE
[Event Request] Codeunit 1217 "Pre-map Incoming Purch. Doc" - OnBeforeInsertLineForTotalDocumentAmount

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#10196]
Hello,

Please add a new publisher event in function InsertLineForTotalDocumentAmount as follows:

    local procedure InsertLineForTotalDocumentAmount(EntryNo: Integer; HeaderRecordNo: Integer; RecordNo: Integer; VendorNo: Code[20])
    var
        PurchaseLine: Record "Purchase Line";
        PurchaseHeader: Record "Purchase Header";
        Vendor: Record Vendor;
        IntermediateDataImport: Record "Intermediate Data Import";
        LineDescription: Text[250];
        IsHandled: Boolean;
    begin
        OnBeforeInsertLineForTotalDocumentAmount(EntryNo, IsHandled);
        if IsHandled then
            exit;
        if not Vendor.Get(VendorNo) then
            exit;

New Publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertLineForTotalDocumentAmount(EntryNo: Integer; var IsHandled: Boolean)
    begin
    end;

The functional value of adding this event:
We have some functionality in which we can create purchase documents without purchase lines. The purchase lines will be added later or based on a purchase order no.
That's why, we would not need to have this line created for the total amount of the document.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
