### ISSUE TITLE
[Event Request] Table 18 Customer - OnAfterAssistEdit

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10199]
Hi, would it be possible to get an event OnAfterAssistEdit in table 18 Customer, procedure AssistEdit, like this : 
![image](https://user-images.githubusercontent.com/73548802/101798730-ba3a6400-3b0b-11eb-941c-38ce016ea8d8.png)

![image](https://user-images.githubusercontent.com/73548802/101798663-a131b300-3b0b-11eb-98ef-2a765bd8f3f6.png)
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
