### ISSUE TITLE
[Event Request] Table "Gen. Journal line" - Function "IsAdHocDescription" - OnBeforeCheckIfIsAdHocDescription

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10198]
Event signature
[Integration Event(false, false)]
local procedure OnBeforeCheckIfIsAdHocDescription(var GenJournalLine: Record "Gen. Journal Line", ExitHandling: Boolean)
    begin
    end;

Reason:
Would be good to have a possibility to control when to exit and place some more checks. We have e.g. another check on one more field before the case-block that leads to an exit and that would be needed to stay. 

Placement and changes in code: 

```
local procedure IsAdHocDescription(): Boolean
    var
        GLAccount: Record "G/L Account";
        Customer: Record Customer;
        Vendor: Record Vendor;
        BankAccount: Record "Bank Account";
        FixedAsset: Record "Fixed Asset";
        ICPartner: Record "IC Partner";
        Employee: Record Employee;
        **ExitHandling: Boolean;**
    begin
        if Description = '' then
            exit(false);
        if xRec."Account No." = '' then
            exit(true);

**OnBeforeCheckIfIsAdHocDescription(Rec, ExitHandling);
If ExitHandling = false then
 exit(false)
else
 exit(true);**
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
