### ISSUE TITLE
CU2001.SendToAzureML suddenly lost [External] tag

### ISSUE THREAD

**Issue by dkatson** [Microsoft/ALAppExtensions#102]
Hi team.
In the codeunit 2001 "Azure ML Connector" the function SendToAzureML suddenly lost [External] tag.

Maybe I missed something. 
But earlier you (and me also) used this function to send requests to Azure ML.

What should we use now?

**Comment by JesperSchulz** [comment]
The [External] tag was indeed removed on purpose, as the function isn't safe to be called like that from extensions. However, it should have been replaced with a safe alternative, which doesn't seem to have happened! I will follow up immediately and make sure we roll out a safe function for you to call asap. Sorry about the inconvenience!

**Comment by dkatson** [comment]
@JesperSchulz  My demo for the Directions EMEA is broken because of that :)
I solved it partly by making my app internal, but better suggest an alternative. Cos I will show how to make custom predictions, will be not very cool to show something which is not relevant

**Comment by JesperSchulz** [comment]
@dkatson We've got the fix ready. The SendToAzureML has been made external again. Only difference is, that the boolean parameter _TrackUsage_ has been removed. So your code will be very valid - only adjustment will be to remove the parameter from the call... Hope the "app as internal" hack doesn't ruin too much of your demo.
We will try to backport the change for uptake in update 20 (November release). Sorry again about the inconvenience!
On a different note: I wish I could attend your session! Sounds VERY interesting. Unfortunately I'm not going to Directions EMEA this year and hence won't be able see the show. Too bad the session wasn't at Directions NA. Hope to get a chance to see it at a different occasion!

**Comment by dkatson** [comment]
@JesperSchulz thanks! What image should i use to update my sandbox? microsoft/bcsandbox or bcinsider.azurecr.io/bcsandbox-master? 

Re Directions NA. Actually I was invited as a speaker, but due to VISA period of waiting, had to cancel my session. Hope, that next year the Directions NA committee will invite me once again.
Sadly that you will not attend Directions EMEA. Maybe you will  attend NavTechDays? I also will hold a session there.

**Comment by JesperSchulz** [comment]
Both should do! The change just went into master and the backporting job will finish in a couple of hours (if all goes well). The change should hence very soon be in both images. You may have to wait a day or two - I'm not sure how long exactly it takes for our changes to propagate out to our Docker images...
Unfortunately, I don't think I'll be going to TechDay's this year either - for the first time in a couple of years. I'll just have to get a resumé from one of my colleagues ;-)
