### ISSUE TITLE
[Event Request] Codeunit 9520 "Mail Management" - OnBeforeQualifyFromAddress_OnSend

### ISSUE THREAD

**Issue by GOB-Andrea** [microsoft/ALAppExtensions#10206]
Hey, would it be possible to add a publisher to the following function?

Codeunit 9520 "Mail Management" - Send

```
procedure Send(ParmEmailItem: Record "Email Item"; EmailScenario: Enum "Email Scenario"): Boolean
    begin
        TempEmailItem := ParmEmailItem;
	// START NEW
	OnBeforeQualifyFromAddress_OnSend(TempEmailItem, EmailScenario);
	// END NEW
        QualifyFromAddress(EmailScenario);
        MailSent := false;
        exit(DoSend);
    end;

    // START NEW
    [IntegrationEvent(false, false)]
    local procedure OnBeforeQualifyFromAddress_OnSend(var TempEmailItem: Record "Email Item" temporary; var EmailScenario: Enum "Email Scenario")
    begin
    end;
    // END NEW
```
Currently emails from interactions are sent with the default email scenario with no possibility to set up or change it during the process.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
