### ISSUE TITLE
[Event Request] Table 18 Customer - OnBeforeCustLedgerEntryDrillDown

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10202]
Hi, would it be possible to get an event OnBeforeCustLedgerEntryDrillDown in procedure OpenCustomerLedgerEntries, table 18 Customer, like this : 
![image](https://user-images.githubusercontent.com/73548802/101803574-f623f800-3b10-11eb-8a01-9df3573cb943.png)

![image](https://user-images.githubusercontent.com/73548802/101803520-e86e7280-3b10-11eb-8f55-97b192dcbd02.png)
?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
