### ISSUE TITLE
Bug - Entries are not rolling back if error occurs during posting on Bank/Giro Journal

### ISSUE THREAD

**Issue by sandrazh** [microsoft/ALAppExtensions#10201]
Bug exists on current BC Online (checked on 17.1.18256.19044).
Company CRONUS NL, without addons or extensions.
The journal and lines should be like this:
![image](https://user-images.githubusercontent.com/60361184/101800070-8401e200-3b15-11eb-9efe-3f722b5ce2d9.png)
On the last line there is wrong "VAT Prod. Posting Group". Post it - and you will get the error:
The VAT Posting Setup does not exist. Identification fields and values: VAT Bus. Posting Group='BINNENLAND',VAT Prod. Posting Group='FULL NORM'
Check Customer Ledger Entries, and you will find the entry:
![image](https://user-images.githubusercontent.com/60361184/101800447-f5da2b80-3b15-11eb-9dd8-6c296e01a9a1.png)
The lines are still exist in journal because of the error, but the entries are not rolling back. This occurs for all ledger entries (Customer, Vendor and G/L).
And you can post this journal again, and the entries will be created.

This bug is not present on versions 16.3 or earlier.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
