### ISSUE TITLE
[Event Request] Table 383 Detailed CV Ledg. Entry Buffer - OnAfterInsertDtldCVLedgEntry

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10209]
Hi, would it be possible to get an event OnAfterInsertDtldCVLedgEntry in table 383 Detailed CV Ledg. Entry Buffer , like this : 
![image](https://user-images.githubusercontent.com/73548802/101895858-62056f80-3ba8-11eb-8f9e-63d926fbb850.png)
![image](https://user-images.githubusercontent.com/73548802/101895890-6df13180-3ba8-11eb-9e91-d7ffdc8f0f46.png)
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
