### ISSUE TITLE
[Event Request] Table 18  Customer - OnAfterSetLastModifiedDateTime

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10203]
Hi, would it be possible to get an event OnAfterSetLastModifiedDateTime in Table 18 Customer, procedure SetLastModifiedDateTime, like this : 
![image](https://user-images.githubusercontent.com/73548802/101804300-b90c3580-3b11-11eb-8e5d-b9b11f3b166d.png)

?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
