### ISSUE TITLE
[Event Request] Codeunit::"Prod. Order Status Management" - Function FlushProdOrder - OnCheckAssociatedOrderLinesOnBeforeInsertSalesLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10214]
We like to request the following Event:
Object: Codeunit::"Prod. Order Status Management"
Function: FlushProdOrder
Publisher Event: OnCheckAssociatedOrderLinesOnBeforeInsertSalesLine
Reason: To implement custom business logic
Where is the event placed:
if NewStatus = NewStatus::Released then
                        QtyToPost := GetNeededQty(1, false)
                    else
                        QtyToPost := GetNeededQty(0, false);
                    IsHandled := false;
                    OnFlushProdOrderOnAfterCalculateQtyToPost(ProdOrderComp, QtyToPost, IsHandled);
                    if not IsHandled then
                        QtyToPost := UOMMgt.RoundToItemRndPrecision(QtyToPost, Item."Rounding Precision");
                    if QtyToPost <> 0 then begin
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterCalculateQtyToPost(ProdOrderComponent: Record "Prod. Order Component"; var QtyToPost: Decimal; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
