### ISSUE TITLE
[Event Request] Codeunit::"Sales Post" - Function CheckAndUpdate - OnCheckAndUpdateOnAfterSetPoszingFromWhseRef

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10218]
We like to request the following Event:
Object: Codeunit::"Sales Post"
Function: CheckAndUpdate
Publisher Event: OnCheckAndUpdateOnAfterSetPoszingFromWhseRef
Reason: To implement custom business logic
Where is the event placed:
InvtPickPutaway := "Posting from Whse. Ref." <> 0;
            "Posting from Whse. Ref." := 0;
            OnCheckAndUpdateOnAfterSetPoszingFromWhseRef (SalesHeader, InvtPickPutaway, "Posting from Whse. Ref.");
            CheckDimensions.CheckSalesDim(SalesHeader, TempSalesLineGlobal);
            CheckPostRestrictions(SalesHeader);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCheckAndUpdateOnAfterSetPoszingFromWhseRef (var SalesHeader: Record "Sales Header"; var InvtPickPutaway: Boolean; Var PostingFromWhseRef: Integer);
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
