### ISSUE TITLE
[Event Request] Codeunit::"Sales-Post" - Function local procedure InsertReturnReceiptLine - OnInsertReturnReceiptLineAfterReturnRcptLineInit

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10217]
We like to request the following Event:
Object: Codeunit::"Sales-Post"
Function: local procedure InsertReturnReceiptLine
Publisher Event: OnInsertReturnReceiptLineAfterReturnRcptLineInit
Reason: 
Where is the event placed:
OnBeforeInsertReturnReceiptLine(SalesLine, ReturnRcptLine, RemQtyToBeInvoiced, RemQtyToBeInvoicedBase);
        ReturnRcptLine.InitFromSalesLine(ReturnRcptHeader, xSalesLine);
        ReturnRcptLine."Quantity Invoiced" := RemQtyToBeInvoiced;
        ReturnRcptLine."Qty. Invoiced (Base)" := RemQtyToBeInvoicedBase;
        ReturnRcptLine."Return Qty. Rcd. Not Invd." := ReturnRcptLine.Quantity - ReturnRcptLine."Quantity Invoiced";
        OnInsertReturnReceiptLineAfterReturnRcptLineInit(ReturnRcptHeader, ReturnRcptLine, xSalesLine, CostBaseAmount, PostedWhseRcptHeader, WhseRcptHeader);
        if (SalesLine.Type = SalesLine.Type::Item) and (SalesLine."Return Qty. to Receive" <> 0) then begin
            if WhseReceive then
                if WhseRcptLine.GetWhseRcptLine(
                     WhseRcptHeader."No.", DATABASE::"Sales Line", SalesLine."Document Type", SalesLine."Document No.", SalesLine."Line No.")
                then begin
                    WhseRcptLine.TestField("Qty. to Receive", ReturnRcptLine.Quantity);
                    SaveTempWhseSplitSpec(SalesLine, TempHandlingSpecification);
                    WhsePostRcpt.CreatePostedRcptLine(
                      WhseRcptLine, PostedWhseRcptHeader, PostedWhseRcptLine, TempWhseSplitSpecification);
                end;
Event Code:
    [IntegrationEvent(false, false)]
    local procedure OnInsertShipmentLineAfterSalesShptLineInit(var SalesShptHeader: Record "Sales Shipment Header"; var SalesShptLine: Record "Sales Shipment Line"; var SalesLine: Record "Sales Line"; var CostBaseAmount: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
