### ISSUE TITLE
[Event Request] Codeunit:"Purchase Post" - InsertTrackingSpecification - OnBeforeInsertTrackingSpecification

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10213]
We like to request the following Event:
Object: 
Codeunit:"Purchase   Post"
Function: InsertTrackingSpecification 
Publisher Event: OnBeforeInsertTrackingSpecification
Reason: To implement custom business logic
Where is the event placed:

var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeInsertTrackingSpecification(PurchHeader, TempTrackingSpecification, IsHandled);
        if IsHandled then
            exit;

        TempTrackingSpecification.Reset();
  [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertTrackingSpecification(PurchHeader: Record "Purchase Header"; var TempTrackingSpecification: Record "Tracking Specification" temporary; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
