### ISSUE TITLE
[Event Request] Table 27 Item - OnBeforeCheckSerialNoQty

### ISSUE THREAD

**Issue by ghost** [microsoft/ALAppExtensions#10219]
Hi, would it be possible to create a new event OnBeforeCheckSerialNoQtyin table 27 Item, like this :
![image](https://user-images.githubusercontent.com/75368955/101913116-e238ce80-3bc2-11eb-801b-b410153ec87b.png)
![image](https://user-images.githubusercontent.com/75368955/101913660-8de21e80-3bc3-11eb-8853-f0bde530614f.png)
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
