### ISSUE TITLE
[Event Request] Codeunit::"Purch.-Post" - Function CheckAssociatedOrderLines - OnCheckAssociatedOrderLinesOnBeforeInsertSalesLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10211]
We like to request the following Event:
Object: Codeunit::"Purch.-Post"
Function: CheckAssociatedOrderLines
Publisher Event: OnCheckAssociatedOrderLinesOnBeforeInsertSalesLine
Reason: 
Where is the event placed:
local procedure CheckAssociatedOrderLines(PurchHeader: Record "Purchase Header")
    var
        PurchLine: Record "Purchase Line";
        SalesHeader: Record "Sales Header";
        SalesOrderLine: Record "Sales Line";
        TempSalesHeader: Record "Sales Header" temporary;
        TempSalesLine: Record "Sales Line" temporary;
        CheckDimensions: Codeunit "Check Dimensions";
        IsHandled: Boolean;
    begin
        with PurchHeader do begin
            PurchLine.Reset();
            PurchLine.SetRange("Document Type", "Document Type");
            PurchLine.SetRange("Document No.", "No.");
            PurchLine.SetFilter("Sales Order Line No.", '<>0');
            OnCheckAssociatedOrderLinesOnAfterSetFilters(PurchLine, PurchHeader);
            if PurchLine.FindSet() then
                repeat
                    IsHandled := false;
                    OnCheckAssociatedOrderLinesOnBeforeInsertSalesLine (PurchHeader, PurchLine, IsHandled, SalesOrderLine, TempSalesLine);
                    if not IsHandled then begin
                        SalesOrderLine.Get(
                          SalesOrderLine."Document Type"::Order, PurchLine."Sales Order No.", PurchLine."Sales Order Line No.");
                        TempSalesLine := SalesOrderLine;
                        TempSalesLine.Insert();
                    end;
                    if Invoice then begin
Event Code:

[IntegrationEvent(false,   false)]              local procedure   OnCheckAssociatedOrderLinesOnBeforeInsertSalesLine (PurchaseHeader: Record "Purchase   Header"; var PurchaseLine: Record "Purchase Line"; var IsHandled:   Boolean; SalesOrderLine: Record "Sales Line"; var TempSalesLine:   Record "Sales Line" temporary)              begin              end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
