### ISSUE TITLE
[Event Request] Codeunit::"Sales Post" - Function PostUpdateInvoiceLine - OnPostUpdateInvoiceLineBeforeLoop

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10221]
We like to request the following Event:
Object: Codeunit::"Sales Post"
Function: PostUpdateInvoiceLine
Publisher Event: OnPostUpdateInvoiceLineBeforeLoop
Reason: To implement custom business logic
Where is the event placed:
SalesShptLine.Get("Shipment No.", "Shipment Line No.");
                    SalesOrderLine.Get(
                      SalesOrderLine."Document Type"::Order,
                      SalesShptLine."Order No.", SalesShptLine."Order Line No.");
                    OnPostUpdateInvoiceLineBeforeLoop(TempSalesLine, SalesShptLine, SalesOrderLine);
                    if Type = Type::"Charge (Item)" then
                        UpdateSalesOrderChargeAssgnt(TempSalesLine, SalesOrderLine);
                    SalesOrderLine."Quantity Invoiced" += "Qty. to Invoice";
                    SalesOrderLine."Qty. Invoiced (Base)" += "Qty. to Invoice (Base)";
                    if Abs(SalesOrderLine."Quantity Invoiced") > Abs(SalesOrderLine."Quantity Shipped") then
                        Error(InvoiceMoreThanShippedErr, SalesOrderLine."Document No.");
                    OnPostUpdateInvoiceLineOnBeforeInitQtyToInvoice(SalesOrderLine, TempSalesLine);
                    SalesOrderLine.InitQtyToInvoice;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnPostUpdateInvoiceLineBeforeLoop(var TempSalesLine: Record "Sales Line" temporary; SalesShptLine: Record "Sales Shipment Line"; SalesOrderLine: Record "Sales Line");
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
