### ISSUE TITLE
[Event Request] Codeunit::"Sales Post" - Function PostItemTrackingLine - OnAfterRetrieveInvoiceSpecification

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10226]
We like to request the following Event:
Object: Codeunit::"Sales Post"
Function: PostItemTrackingLine
Publisher Event: OnAfterRetrieveInvoiceSpecification
Reason: To implement custom business logic
Where is the event placed:
if SalesLine."Prepayment Line" then
            exit;
        if SalesHeader.Invoice then
            if SalesLine."Qty. to Invoice" = 0 then
                TrackingSpecificationExists := false
            else
                TrackingSpecificationExists :=
                  ReserveSalesLine.RetrieveInvoiceSpecification(SalesLine, TempTrackingSpecification);
        OnPostItemTrackingLineOnAfterRetrieveInvoiceSpecification(SalesLine, TempTrackingSpecification, TrackingSpecificationExists);
        PostItemTracking(
          SalesHeader, SalesLine, TrackingSpecificationExists, TempTrackingSpecification,
          TempItemLedgEntryNotInvoiced, HasATOShippedNotInvoiced);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterRetrieveInvoiceSpecification(var SalesLine: Record "Sales Line"; var TempInvoicingSpecification: Record "Tracking Specification" temporary; var TrackingSpecificationExists: Boolean)
    begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
