### ISSUE TITLE
[Event Request] Codeunit::"Sales Post" - Function PostUpdateOrderLine - OnPostUpdateOrderLineBeforeInitQtyToInvoice

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10220]
We like to request the following Event:
Object: Codeunit::"Sales Post"
Function: PostUpdateOrderLine
Publisher Event: OnPostUpdateOrderLineBeforeInitQtyToInvoice
Reason: To implement custom business logic
Where is the event placed:
OnPostUpdateOrderLineOnSetDefaultQtyBlank(SalesHeader, TempSalesLine, SalesSetup, SetDefaultQtyBlank);
                    if WhseHandlingRequiredExternal(TempSalesLine) or SetDefaultQtyBlank then begin
                        if "Document Type" = "Document Type"::"Return Order" then begin
                            "Return Qty. to Receive" := 0;
                            "Return Qty. to Receive (Base)" := 0;
                        end else begin
                            "Qty. to Ship" := 0;
                            "Qty. to Ship (Base)" := 0;
                        end;
                        OnPostUpdateOrderLineBeforeInitQtyToInvoice(TempSalesLine, WhseShip, WhseReceive);
                        InitQtyToInvoice;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnPostUpdateOrderLineBeforeInitQtyToInvoice(var TempSalesLine: Record "Sales Line" temporary; WhseShip: Boolean; WhseReceive: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
