### ISSUE TITLE
[Event Request] Codeunit::"Sales Post" - Function PostItemChargePerShpt - OnBeforePostItemChargePerShpt

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10229]
We like to request the following Event:
Object: Codeunit::"Sales Post"
Function: PostItemChargePerShpt
Publisher Event: OnBeforePostItemChargePerShpt
Reason: To implement custom business logic
Where is the event placed:
OnBeforePostItemChargePerShpt(SalesHeader, SalesLine, SalesShptLine, TempItemLedgEntry, TempItemChargeAssgntSales, DistributeCharge);
        if DistributeCharge then
            PostDistributeItemCharge(
              SalesHeader, SalesLine, TempItemLedgEntry, SalesShptLine."Quantity (Base)",
              TempItemChargeAssgntSales."Qty. to Assign", TempItemChargeAssgntSales."Amount to Assign")
        else
            PostItemCharge(SalesHeader, SalesLine,
              SalesShptLine."Item Shpt. Entry No.", SalesShptLine."Quantity (Base)",
              TempItemChargeAssgntSales."Amount to Assign",
              TempItemChargeAssgntSales."Qty. to Assign");
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforePostItemChargePerShpt(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; SalesShptLine: Record "Sales Shipment Line"; TempItemLedgEntry: Record "Item Ledger Entry" temporary; var TempItemChargeAssgntSales: Record "Item Charge Assignment (Sales)" temporary; var DistributeCharge: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
