### ISSUE TITLE
[Event Request] Codeunit::"Sales Post" - Function PostUpdateReturnReceiptLine - OnPostUpdateReturnReceiptLineBeforeLoop

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10222]
We like to request the following Event:
Object: Codeunit::"Sales Post"
Function: PostUpdateReturnReceiptLine
Publisher Event: OnPostUpdateReturnReceiptLineBeforeLoop
Reason: To implement custom business logic
Where is the event placed:
if FindSet() then
                repeat
                    ReturnRcptLine.Get("Return Receipt No.", "Return Receipt Line No.");
                    SalesOrderLine.Get(
                      SalesOrderLine."Document Type"::"Return Order",
                      ReturnRcptLine."Return Order No.", ReturnRcptLine."Return Order Line No.");
                    OnPostUpdateReturnReceiptLineBeforeLoop(TempSalesLine, ReturnRcptLine, SalesOrderLine);
                    if Type = Type::"Charge (Item)" then
                        UpdateSalesOrderChargeAssgnt(TempSalesLine, SalesOrderLine);
                    SalesOrderLine."Quantity Invoiced" += "Qty. to Invoice";
                    SalesOrderLine."Qty. Invoiced (Base)" += "Qty. to Invoice (Base)";
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnPostUpdateReturnReceiptLineBeforeLoop(var TempSalesLine: Record "Sales Line" temporary; ReturnRcptLine: Record "Return Receipt Line"; SalesOrderLine: Record "Sales Line");
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
