### ISSUE TITLE
[Event Request] Codeunit::"Sales Post" - Function UpdateQtyToBeInvoicedForReturnReceipt - OnBeforeUpdateQtyToBeInvoicedForReturnReceipt

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10225]
We like to request the following Event:
Object: Codeunit::"Sales Post"
Function: UpdateQtyToBeInvoicedForReturnReceipt
Publisher Event: OnBeforeUpdateQtyToBeInvoicedForReturnReceipt
Reason: To implement custom business logic
Where is the event placed:
local procedure UpdateQtyToBeInvoicedForReturnReceipt(var QtyToBeInvoiced: Decimal; var QtyToBeInvoicedBase: Decimal; TrackingSpecificationExists: Boolean; SalesLine: Record "Sales Line"; ReturnReceiptLine: Record "Return Receipt Line"; InvoicingTrackingSpecification: Record "Tracking Specification")
    begin
        OnBeforeUpdateQtyToBeInvoicedForReturnReceipt(
          QtyToBeInvoiced, QtyToBeInvoicedBase, TrackingSpecificationExists, SalesLine, ReturnReceiptLine, InvoicingTrackingSpecification);
        if TrackingSpecificationExists then begin
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateQtyToBeInvoicedForReturnReceipt(var QtyToBeInvoiced: Decimal; var QtyToBeInvoicedBase: Decimal; TrackingSpecificationExists: Boolean; SalesLine: Record "Sales Line"; ReturnReceiptLine: Record "Return Receipt Line"; InvoicingTrackingSpecification: Record "Tracking Specification")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
