### ISSUE TITLE
[Change Request] - Codeunit::"Req. Wksh.-Make Order" -InsertPurchOrderLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10239]
We like to request the following change:
Object: Codeunit::"Req. Wksh.-Make Order"
Function: InsertPurchOrderLine
Reason: Please change the marked Parameter from 0.00001 to UofMgt.QtyRndPrecision()
Code to change:
Current Code: if PurchOrderLine."Drop Shipment" or PurchOrderLine."Special Order" then begin
                SalesOrderLine.LockTable();
                SalesOrderHeader.LockTable();
                SalesOrderHeader.Get(SalesOrderHeader."Document Type"::Order, "Sales Order No.");
                CheckPurchOrderLineShipToCode(ReqLine2);
                SalesOrderLine.Get(SalesOrderLine."Document Type"::Order, "Sales Order No.", "Sales Order Line No.");
                SalesOrderLine.TestField(Type, SalesOrderLine.Type::Item);
                if SalesOrderLine."Purch. Order Line No." <> 0 then
                    Error(Text006, SalesOrderLine."No.", SalesOrderLine."Document No.", SalesOrderLine."Purchase Order No.");
                if SalesOrderLine."Special Order Purchase No." <> '' then
                    Error(Text006, SalesOrderLine."No.", SalesOrderLine."Document No.", SalesOrderLine."Special Order Purchase No.");
                if not PurchOrderLine."Special Order" then
                    TestField("Sell-to Customer No.", SalesOrderLine."Sell-to Customer No.");
                TestField(Type, SalesOrderLine.Type);
                TestField(
                  Quantity,
                  Round(
                    SalesOrderLine."Outstanding Quantity" *
                    SalesOrderLine."Qty. per Unit of Measure" /
                    "Qty. per Unit of Measure",
                    **0.00001))**;
                TestField("No.", SalesOrderLine."No.");

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
