### ISSUE TITLE
[Event Request] Codeunit::"Sales Post" - Function CheckAssosOrderLines - OnBeforeCheckAssosOrderLines

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10234]
We like to request the following Event:
Object: Codeunit::"Sales Post"
Function: CheckAssosOrderLines
Publisher Event: OnBeforeCheckAssosOrderLines
Reason: To implement custom business logic
Where is the event placed:
local procedure CheckAssosOrderLines(SalesHeader: Record "Sales Header")
    var
        SalesLine: Record "Sales Line";
        PurchaseOrderLine: Record "Purchase Line";
        PurchaseHeader: Record "Purchase Header";
        TempPurchaseHeader: Record "Purchase Header" temporary;
        TempPurchaseLine: Record "Purchase Line" temporary;
        CheckDimensions: Codeunit "Check Dimensions";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckAssosOrderLines(SalesHeader, IsHandled);
        if IsHandled then
            exit;
        with SalesHeader do begin
            SalesLine.Reset();
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckAssosOrderLines(SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
