### ISSUE TITLE
[Event Change Request] - Database:: "VAT Amount Line" - OnAfterVATAmountText

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10237]
We like to request the following event change:
Object: Database:: "VAT Amount Line"
Function: OnAfterVATAmountText
Reason: Please change the IncludeSender to false
Code to change:
**[IntegrationEvent(false, false)]**
    local procedure OnAfterVATAmountText(VATPercentage: Decimal; FullCount: Integer; var Result: Text[30])
    begin
    end;

**Comment by StanPesotskiy** [comment]
This is the breaking change. We cannot do this. 
But you can remove the Sender parameter in the handler function if you don't need it.
