### ISSUE TITLE
[Fieldgroup Request] - Database::Manufacturer

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10236]
We like to request the following change:
Object: Database::Manufacturer
Function: 
Reason: Please add a Fieldgroup so we can extend it.
Code to change:
 fieldgroups
    {
        fieldgroup(DropDown; "Code", Name)
        {
        }
    }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
