### ISSUE TITLE
[Event Request] Codeunit::"Sales Post" - Function PostItemChargePerRetRcpt - OnBeforePostItemChargePerRetRcpt

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10230]
We like to request the following Event:
Object: Codeunit::"Sales Post"
Function: PostItemChargePerRetRcpt
Publisher Event: OnBeforePostItemChargePerRetRcpt
Reason: To implement custom business logic
Where is the event placed:
OnBeforePostItemChargePerRetRcpt(SalesHeader, SalesLine, ReturnRcptLine, TempItemLedgEntry, TempItemChargeAssgntSales, DistributeCharge);
        if DistributeCharge then
            PostDistributeItemCharge(
              SalesHeader, SalesLine, TempItemLedgEntry, ReturnRcptLine."Quantity (Base)",
              TempItemChargeAssgntSales."Qty. to Assign", TempItemChargeAssgntSales."Amount to Assign")
        else
            PostItemCharge(SalesHeader, SalesLine,
              ReturnRcptLine."Item Rcpt. Entry No.", ReturnRcptLine."Quantity (Base)",
              TempItemChargeAssgntSales."Amount to Assign",
              TempItemChargeAssgntSales."Qty. to Assign")
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforePostItemChargePerRetRcpt(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; ReturnRcptLine: Record "Return Receipt Line"; TempItemLedgEntry: Record "Item Ledger Entry" temporary; var TempItemChargeAssgntSales: Record "Item Charge Assignment (Sales)" temporary; var DistributeCharge: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
