### ISSUE TITLE
[Event Request] Codeunit::"Sales Post" - Function SetPostingFlags - OnBeforeCheckPostingFlags

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10233]
We like to request the following Event:
Object: Codeunit::"Sales Post"
Function: SetPostingFlags
Publisher Event: OnBeforeCheckPostingFlags
Reason: To implement custom business logic
Where is the event placed:
OnBeforeCheckPostingFlags(SalesHeader, IsHandled);
            if not IsHandled then
                if not (Ship or Invoice or Receive) then
                    Error(ShipInvoiceReceiveErr);
        end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckPostingFlags(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
