### ISSUE TITLE
[Event Request] Codeunit::"Sales Post" - Function UpdateAssosOrderPostingNos - OnBeforeUpdateAssosOrderPostingNos

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10232]
We like to request the following Event:
Object: Codeunit::"Sales Post"
Function: UpdateAssosOrderPostingNos
Publisher Event: OnBeforeUpdateAssosOrderPostingNos
Reason: To implement custom business logic
Where is the event placed:
local procedure UpdateAssosOrderPostingNos(SalesHeader: Record "Sales Header") DropShipment: Boolean
    var
        TempSalesLine: Record "Sales Line" temporary;
        PurchOrderHeader: Record "Purchase Header";
        NoSeriesMgt: Codeunit NoSeriesManagement;
        ReleasePurchaseDocument: Codeunit "Release Purchase Document";
        IsHandled: Boolean;
    begin
        OnBeforeUpdateAssosOrderPostingNos(SalesHeader, DropShipment, TempSalesLineGlobal, PreviewMode, IsHandled);
        if IsHandled then
            exit;
        with SalesHeader do begin
            ResetTempLines(TempSalesLine);
            TempSalesLine.SetFilter("Purch. Order Line No.", '<>0');
            DropShipment := not TempSalesLine.IsEmpty;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateAssosOrderPostingNos(var SalesHeader: Record "Sales Header"; var DropShipment: Boolean; var TempSalesLineGlobal: Record "Sales Line" temporary; PreviewMode: Boolean; var IsHandled: Boolean);
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
