### ISSUE TITLE
[Fieldgroup Request] - Database::"Item Variant"

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10235]
We like to request the following change:
Object: Database::"Item Variant"
Function: 
Reason: Please add a Fieldgroup so we can extend it.
Code to change:
fieldgroups
    {
        fieldgroup(DropDown; "Code", Description)
        {
        }
    }

**Comment by AlexanderYakunin** [comment]
We already have this here:
        fieldgroup(DropDown; "Item No.", "Code", Description)
        {
        }

Should we change it? Remove "Item No." from fieldgroup? 

Please clarify your ask.
