### ISSUE TITLE
[Event Change Request] - Database:: "VAT Amount Line" - OnInsertLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10238]
We like to request the following event change:
Object: Database:: "VAT Amount Line"
Function: OnInsertLine
Reason: Please add the missing var tag for the IsHandled Variable
Code to change:
[IntegrationEvent(false, false)]
    local procedure OnInsertLine(var VATAmountLine: Record "VAT Amount Line"; **var IsHandled: Boolean**)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
