### ISSUE TITLE
[Event Request] Codeunit::"Sales Post" - Function OnRun - OnBeforePostSalesLineEndLoop

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10231]
We like to request the following Event:
Object: Codeunit::"Sales Post"
Function: OnRun
Publisher Event: OnBeforePostSalesLineEndLoop
Reason: To implement custom business logic
Where is the event placed:
if RoundingLineInserted then
                    LastLineRetrieved := true
                else begin
                    BiggestLineNo := MAX(BiggestLineNo, TempSalesLineGlobal."Line No.");
                    LastLineRetrieved := TempSalesLineGlobal.Next() = 0;
                    if LastLineRetrieved and SalesSetup."Invoice Rounding" then
                        InvoiceRounding(SalesHeader, TempSalesLineGlobal, false, BiggestLineNo);
                end;
                OnBeforePostSalesLineEndLoop(SalesHeader, TempSalesLineGlobal, LastLineRetrieved);
            until LastLineRetrieved;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforePostSalesLineEndLoop(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; var LastLineRetrieved: Boolean);
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
