### ISSUE TITLE
[Event Request] Table 83 "Item Journal Line" - OnValidateItemNoOnAfterCreateDim

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10240]
Hi, in the Table 83 "Item Journal Line", in the field 3 "Item No.", in the trigger OnValidate, we would like to add our code in a specific place. To do so, we would need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/101923359-95a7c000-3bcf-11eb-89c3-272760ea22e8.png)

With the event integration :
![image](https://user-images.githubusercontent.com/34645582/101921782-a9522700-3bcd-11eb-8e02-f6894059e3a6.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by StanPesotskiy** [comment]
Is it ok for you to use existing event OnAfterCreateDimTableIDs for function CreateDim (parameter CurrFieldNo allows to identify the call from OnValidate trigger)?

**Comment by Magicrevette** [comment]
Yes it is ok. Thank you !

**Comment by Magicrevette** [comment]
Sorry, it doesn't fit my needs finally. CreateDim is called twice in the OnValidate trigger of field 3, and we want to add our code only after the first call. So the event OnAfterCreateDimTableIDs  with the CurrFieldNo parameter would not work.

**Comment by StanPesotskiy** [comment]
@Magicrevette please create a new request for this.
