### ISSUE TITLE
[Event Request] Codeunit::"Production Journal Mgt" - Function: InsertConsumptionItemJnlLine - OnInsertConsumptionItemJnlLineOnBeforeSetQuantity

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10247]
We like to request   the following Event:
--
Object:    Codeunit::"Production Journal Mgt"
Function: InsertConsumptionItemJnlLine
Publisher Event:  OnInsertConsumptionItemJnlLineOnBeforeSetQuantity
Reason: To  implement custom business logic
Where is the event placed:
ItemJnlLine.Description := Description;
            IsHandled := false;
OnInsertConsumptionItemJnlLineOnSetQuantity(ItemJnlLine, ProdOrderComp, NeededQty, IsHandled);
            if not IsHandled then
                if NeededQty <> 0 then
                    if Item."Rounding Precision" > 0 then
                        ItemJnlLine.Validate(Quantity, UOMMgt.RoundToItemRndPrecision(NeededQty, Item."Rounding Precision"))
                    else
                        ItemJnlLine.Validate(Quantity, Round(NeededQty, UOMMgt.QtyRndPrecision));

            ItemJnlLine.Validate("Location Code", "Location Code");
            if "Bin Code" <> '' then
                ItemJnlLine."Bin Code" := "Bin Code";

 [IntegrationEvent(false, false)]
    local procedure OnInsertConsumptionItemJnlLineOnBeforeSetQuantity(var ItemJnlLine: Record "Item Journal Line"; ProdOrderComponent: Record "Prod. Order Component"; NeededQty: Decimal; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
