### ISSUE TITLE
[Add Sender] CU13 Gen. Jnl.-Post Batch OnBeforeUpdateAndDeleteLines

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#10248]
Hello, can we change event signature from

`
[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateAndDeleteLines(var GenJournalLine: Record "Gen. Journal Line"; CommitIsSuppressed: Boolean; var IsHandled: Boolean)
`
to
`
[IntegrationEvent(true, false)]
    local procedure OnBeforeUpdateAndDeleteLines(var GenJournalLine: Record "Gen. Journal Line"; CommitIsSuppressed: Boolean; var IsHandled: Boolean)
`

to include sender, then we can use global methods in custom method implementation.

Thanks,
Bartek

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
