### ISSUE TITLE
[Event Request] codeunit 12179 "Export FatturaPA Document" - OnAfterCreateXML

### ISSUE THREAD

**Issue by Athon-dev** [microsoft/ALAppExtensions#10243]
We like to request the following change:

Object: Codeunit::"Export FatturaPA Document"
Function: GenerateXMLFile
Reason: to get XML Stream.
Code to change:

procedure GenerateXMLFile(var TempFatturaLine: Record "Fattura Line" temporary; TempFatturaHeader: Record "Fattura Header" temporary; ClientFileName: Text[250]): Text[250]
    var
	...
	**lCduTempBlob : Codeunit "Temp Blob";**
    begin
	...        
        // update Buffer
	TempXMLBuffer.FindFirst;
	TempXMLBuffer.Save(FileName);
	**Clear(lCduTempBlob);
	XMLBuffReader.SaveToTempBlob(lCduTempBlob TempXMLBuffer);
	OnAfterCreateXML(lCduTempBlob);**
        ...
    end;
  

**[IntegrationEvent(false, false)]
procedure OnAfterCreateXML(var TempBlob: Codeunit "Temp Blob");
begin  
end;**

thank's

**Comment by StanPesotskiy** [comment]
1.	XMLBuffReader is not defined.
2.	Is it ok to have event OnAfterCreateXML(TempXMLBuffer) where you can process it as you want?

**Comment by Athon-dev** [comment]
Yes it's ok have event OnAfterCreateXML(TempXMLBuffer). Great!! Thank's

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
