### ISSUE TITLE
[Event Request] Codeunit 22 OnBeforeSetupSplitJnlLine - make TrackingSpecExists a VAR

### ISSUE THREAD

**Issue by eric-silverw-com** [microsoft/ALAppExtensions#10244]
Currently the TrackingSpecExists parameter is not a var but it is used immediately after the event call.  This eliminates the ability of the event handler to create new tracking specification records.

        OnBeforeSetupSplitJnlLine(ItemJnlLine2, TrackingSpecExists, TempTrackingSpecification);

        if not ItemJnlLine2.Correction and (ItemJnlLine2."Quantity (Base)" <> 0) and TrackingSpecExists then begin
            if DisableItemTracking then begin

-----------------------------

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetupSplitJnlLine(var ItemJnlLine2: Record "Item Journal Line"; TrackingSpecExists: Boolean; var TempTrackingSpecification: Record "Tracking Specification" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
