### ISSUE TITLE
[Request For External] CU13 Gen Jnl.-Post Batch - UpdateDialog

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#10246]
Hello,
can we make this public please:

`
local procedure UpdateDialog(PostingState: Integer; LineNo: Integer; TotalLinesQty: Integer)
`

this will allow updating already opened dialog, i.e. in custom UpdateAndDeleteLines procedure.

Thanks,
Bartek

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
