### ISSUE TITLE
Event Request: "Reservation Management": GetSourceRecordValue

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#10259]
In Codeunit 99000845 "Reservation Management" there is a function `GetSourceRecordValue`. This function is calling the event `OnGetSourceRecordValue` to which various "[TableName]-Reserve" Codeunits subscribe to in order to provide the source quantity. This event has a few issues:

1. it does not implement the handled pattern. As such, I can not know if anyone already handled a given table.
2. I cannot add custom handlers for a specific scenario, because I cannot know if my handler comes before or after the ones from the base app.

I therefore suggest:
1. Add the `Handled`-Pattern to this event.
2. Provide a new event in the function `GetSourceRecordValue` that is called right after `OnGetSourceRecordValue`. Something like
    `OnAfterGetSourceRecordValue(var ReservEntry, var SetAsCurrent, ReturnOption, var SourceQty, vat SourceRecRef);`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
