### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnAfterInitCustLedgEntry

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10257]
Hi, would it be possible to get an event OnAfterInitCustLedgEntry in Codeunit 12 Gen. Jnl.-Post Line, like this : 
![image](https://user-images.githubusercontent.com/73548802/102094688-e6fbbd80-3e22-11eb-860d-e11fddfd0833.png)
![image](https://user-images.githubusercontent.com/73548802/102094940-317d3a00-3e23-11eb-8f23-3cc297578451.png)
?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
