### ISSUE TITLE
[Event Request] Codeunit 11 Gen. Jnl.-Check Line - OnAfterGetCustomerAccountNo

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10250]
Hi, would it be possible to get an event OnAfterGetCustomerAccountNo in Codeunit 11 Gen. Jnl.-Check Line, like this : 
![image](https://user-images.githubusercontent.com/73548802/102087550-06dab380-3e1a-11eb-8413-dedb875761ae.png)
(parameters being the same as in the OnBeforeCheckICPartner event, except for the IsHandled) ?

Thanks

**Comment by StanPesotskiy** [comment]
Can you use existing event OnBeforeCheckICPartner?
