### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnBeforeCheckBlock

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10253]
Hi, would it be possible to get an event OnBeforeCheckBlock in Codeunit 12 Gen. Jnl.-Post Line, like this 
![image](https://user-images.githubusercontent.com/73548802/102092205-1826be80-3e20-11eb-8fae-6bf4d85c090c.png)
![image](https://user-images.githubusercontent.com/73548802/102092384-50c69800-3e20-11eb-8d66-d470e08f4a06.png)
?

Thanks

**Comment by StanPesotskiy** [comment]
Is it ok to use existing event OnBeforeCheckBlockedCust for Cust.CheckBlockedCustOnJnls function?
