### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnNotCustBlockPaymentTolerance

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10258]
Hi, would it be possible to get an event OnNotCustBlockPaymentTolerance in codeunit 12 Gen. Jnl.-Post Line, like this : 
![image](https://user-images.githubusercontent.com/73548802/102096514-190e1f00-3e25-11eb-9120-8fb991a8da47.png)
![image](https://user-images.githubusercontent.com/73548802/102096677-42c74600-3e25-11eb-9c28-98b8aaccd9bf.png)
?
Thanks

**Comment by StanPesotskiy** [comment]
Is it ok to use existing event OnBeforeCalcPmtTolerancePossible?
