### ISSUE TITLE
[Request for Procedures] Access to the internal table "Email Message Attachment"

### ISSUE THREAD

**Issue by GOB-Andrea** [microsoft/ALAppExtensions#10254]
Hey, is it possible to access the attachments after an email has been sent? We need to edit the attachments after the sending process. It seems only possible to write from and read to the attachments during sending (via codeunit 8904 "Email Message")

If we want to access the attachments after the email is sent, we need the "Message Id" of that specific email to tell the codeunit what attachments need to be read. The "Message Id" field is set to internal in the "Sent Email" table, so while we can loop through its records, we can't identify the current email (message id).

Therefore ... 

1. Is it possible to add a function to the "Sent Email" table that returns the "Message Id"? E.g. like this: 

```
procedure GetMessageId(SentEmail: Record "Sent Email"): Guid
    begin
        exit(SentEmail. "Message Id");
    end;
```

2. Is it possible to filter the "Email Message Attachment" based on the "Message Id" and read the blob with a function? E.g. like this:

Codeunit 8904 "Email Message"
```
    /// <summary>
    /// Sets the Message Id of the current email
    /// </summary>
    /// <param name="MessageId">The id of the message you would like to refer to</param>.
    procedure SetMessageId(MessageId: Guid)
    begin
        EmailMessageImpl.Get(MessageId)
    end;
```

Afterwards we could use the two functions Attachments_First and Attachments_Next to loop through all attachments that are stored for the "Message Id" and read them out with the function Attachments_GetContent.

3. Can you add a function to remove the attachments from the blob fields? E.g. like this:

Codeunit 8904 "Email Message"
```
    /// <summary>
    /// Clears the blob content of the current attachment.
    /// </summary>
    procedure Attachments_ClearContent()
    begin
        EmailMessageImpl.ClearAttachmentContent();
    end;
```
And in the codeunit "Email Message Impl." the corresponding function:
```
procedure ClearAttachmentContent()
    begin
        Clear(Attachments.Attachment);
        Attachments.Modify();
    end;
```
With these new procedures you could keep the status internal for your fields and codeunits, but we would have the access we need to read and modify the email attachments. Please share your opinion. Thank you.

**Comment by darjoo** [comment]
Hey @GOB-Andrea, why exactly do you want to clear the attchment's contents? Is it to still keep track of the email, but remove the attachments to reduce db usage?

**Comment by GOB-Andrea** [comment]
@darjoo Hey, yes. The attachments can take up a lot of space. Therefore we would like to remove them after a certain time, but keep the core information.

**Comment by JesperSchulz** [comment]
Being able to delete attachments without the mail is a rather common request, that we may want to handle through the mail module itself (to be discussed and prioritized). Please allow us to get back to you on this request.

**Comment by GOB-Andrea** [comment]
@JesperSchulz Hi Jesper, I'm curious if you've come up with any ideas on this topic yet. We have recurring discussions on the topic, so it would be great if there is a solution available soon. Thanks a lot! :)

**Comment by JesperSchulz** [comment]
We're currently working on moving attachments into media fields, which do not increase your DB size (at least it doesn't count in our customer's data quota). The idea longer term is, that the platform will store these media blobs outside of the DB. Given that information, would you still need to delete attachments?

**Comment by GOB-Andrea** [comment]
@JesperSchulz  Hey Jesper, unfortunately storing in MediaSet fields is not enough. We are not concerned with the maximum database size in SaaS. Our goal is to store the files in other systems and only link them in BC. Storing the files inside the database then wouldn't be necessary. Therefore, we would like to delete the attachments, whether in BLOB or MediaSet fields.

**Comment by JesperSchulz** [comment]
ok, thanks! We'll look into it as soon as we find time to do so. I would expect that we can address this in a minor release of version 18.

**Comment by RafaelKoch** [comment]
@JesperSchulz : any news? This looks awfully abandoned... :(

**Comment by JesperSchulz** [comment]
It's not abandoned, but we didn't manage to get around to implement this yet. We had a few other "clean up the DB" initiatives, I wanted to see how play out, before we get to this. I hope we'll have time to find a solution very soon.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
