### ISSUE TITLE
[Event Request] Application “Tests-SM” Codeunit 137162 "SCM Warehouse - Shipping III"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10252]
[Event Request]Application “Tests-SCM”, 137162 "SCM Warehouse - Shipping III"

Could you please insert the Initialize procedure at the beginning of the test procedure Initialize?
![pic1](https://user-images.githubusercontent.com/45795262/102091606-57a0db00-3e1f-11eb-93d5-bbe015bc6dfb.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
