### ISSUE TITLE
[Change Request] table 39 "Purchase Line" publisher OnCheckWarehouseOnBeforeShowDialog Parameter PurchLine

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10262]
Is it possible to pass the parameter PurchLine in publisher OnCheckWarehouseOnBeforeShowDialog by reference?
Note: We had originally requested the event with Issue No. [8484](https://github.com/microsoft/ALAppExtensions/issues/8484)

```
    [IntegrationEvent(false, false)]
   // >>>>>>>>>>>>>>>>>>>>>
    //local procedure OnCheckWarehouseOnBeforeShowDialog(PurchLine: Record "Purchase Line"; Location2: Record Location; var ShowDialog: Option " ",Message,Error; var DialogText: Text[50])
    local procedure OnCheckWarehouseOnBeforeShowDialog(var PurchLine: Record "Purchase Line"; Location2: Record Location; var ShowDialog: Option " ",Message,Error; var DialogText: Text[50])
    begin
    end;
   // <<<<<<<<<<<<<<<<<<
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
