### ISSUE TITLE
[Access Request] page 7345 "Pick Worksheet" variables CurrentWkshTemplateName, CurrentWkshName, CurrentLocationCode, CurrentSortingMethod

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10267]
We would like to request access to the global variables CurrentWkshTemplateName, CurrentWkshName, CurrentLocationCode, CurrentSortingMethod of object page 7345 "Pick Worksheet"

    var
        WMSMgt: Codeunit "WMS Management";
        CrossDockMgt: Codeunit "Whse. Cross-Dock Management";
        UOMMgt: Codeunit "Unit of Measure Management";
        // >>>>>>>>>>>>>>>>>>>
        // CurrentWkshTemplateName: Code[10];
        // CurrentWkshName: Code[10];
        // CurrentLocationCode: Code[10];
        // CurrentSortingMethod: Enum "Whse. Activity Sorting Method";
        // <<<<<<<<<<<<<<<<<<
        
        ItemDescription: Text[100];
        QtyCrossDockedUOM: Decimal;
        QtyCrossDockedAllUOMBase: Decimal;
        QtyCrossDockedUOMBase: Decimal;
        OpenedFromBatch: Boolean;
    // >>>>>>>>>>>>>>>>>>>
    protected var
        CurrentWkshTemplateName: Code[10];
        CurrentWkshName: Code[10];
        CurrentLocationCode: Code[10];
        CurrentSortingMethod: Enum "Whse. Activity Sorting Method";
    // <<<<<<<<<<<<<<<<<<

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
