### ISSUE TITLE
[Event Request] Codeunit 1002 "Job Create-Invoice": OnAfterCreateJobPlanningLineInvoiceOnBeforeModifyJobPlanningLine

### ISSUE THREAD

**Issue by deadmouse** [microsoft/ALAppExtensions#10266]
[Event Request] Codeunit 1002 "Job Create-Invoice": OnAfterCreateJobPlanningLineInvoiceOnBeforeModifyJobPlanningLine

We would need to modify the "Qty. to Transfer to Invoice" for a custom quantity.

```
procedure CreateSalesInvoiceLines(JobNo: Code[20]; var JobPlanningLineSource: Record "Job Planning Line"; InvoiceNo: Code[20]; NewInvoice: Boolean; PostingDate: Date; CreditMemo: Boolean)
.
.
.
.
JobPlanningLine.UpdateQtyToTransfer;
///////// START
OnAfterCreateJobPlanningLineInvoiceOnBeforeModifyJobPlanningLine(JobPlanningLine);
///////// END
JobPlanningLine.Modify();
```

Signature:
```
[IntegrationEvent(false, false)]
local procedure OnAfterCreateJobPlanningLineInvoiceOnBeforeModifyJobPlanningLine(var JobPlanningLine: Record JobPlanningLine)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
