### ISSUE TITLE
Codeunit 8900 "Email Impl" - Draft Email - Apply a connector and sender

### ISSUE THREAD

**Issue by DevPrach** [microsoft/ALAppExtensions#10272]
Hello,
In the new "Email Impl" codeunit, can we have the possibility to send the connector and the sender when you create a draft mail.
The function "SaveAsDraft" send automatically empty values actually :

CreateOrUpdateEmailOutbox(EmailMessageImpl, EmptyGuid, EmptyConnector, Enum::"Email Status"::Draft, '', EmailOutbox);
    

I need this to store multiple draft emails in the "Email Outbox" table and sent them later (automatically with a task scheduler that's why I need all informations about connecter and sender filled).
Thanks.

**Comment by darjoo** [comment]
Sounds like a good idea, how would you feel about contributing it through a pull request? :smile:

**Comment by JesperSchulz** [comment]
The "delayed sending" mechanism is a quite common request, that may be better implemented directly in the email module, rather than through an extension. We would be happy to work with you on getting this going, if you'd like to contribute with some code. If you would prefer not to, we need to discuss if we can find the time to add this functionality ourselves :-)

**Comment by prachou** [comment]
I'm not sure that I can find time to propose a solution quickly so if you can work on this on your side, I appreciate.

**Comment by JesperSchulz** [comment]
From now closed related request:
Can we please have access to the Codeunit "Email Dispatcher" to have the possibility to schedule the sending of emails in draft.
codeunit 8888 "Email Dispatcher" { Access = Internal;
All details #10274.

**Comment by JesperSchulz** [comment]
We are quite busy with all sorts of requests these days. It might take us a little while to get this done, but we're looking at it :-)

**Comment by Groenbech96** [comment]
This issue has been solved in BC version 20.
