### ISSUE TITLE
[Event Request] Table 83 "Item Journal Line" - OnValidateAmountOnAfterTestField & OnValidateAmountOnAfterReadGLSetup

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10278]
Hi, in the Table 83 "Item Journal Line", in the field 18 "Amount", in the trigger OnValidate, we would like to add our code at two specific places, instead of "Unit Amount" variable assignation. To do so, we would need two events publisher and a IsHandled flag, like this :

![image](https://user-images.githubusercontent.com/34645582/102240837-98b8ee00-3ef8-11eb-8f3c-5f9074a7ef73.png)

With the events integration :
![image](https://user-images.githubusercontent.com/34645582/102240797-8a6ad200-3ef8-11eb-9fc2-d88b43b720cc.png)

Do you think it is possible ?

Thank for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
