### ISSUE TITLE
[REQUEST-FOR-EXTERNAL] Codeunit 8888 "Email Dispatcher"

### ISSUE THREAD

**Issue by prachou** [microsoft/ALAppExtensions#10274]
Hey,

Can we please have access to the Codeunit "Email Dispatcher" to have the possibility to schedule the sending of emails in draft.
`codeunit 8888 "Email Dispatcher"
{
    Access = Internal;`

![image](https://user-images.githubusercontent.com/6514179/102219285-8e3e2a80-3edf-11eb-8c73-329bb8f077b2.png)

**Comment by darjoo** [comment]
Is this related to #10272? 
We cannot make this external because this is the implementation details but we'll try to think of a solution.

**Comment by prachou** [comment]
Yes it's linked to #10272 
I'm interesting if you find a solution to call the sending of draft emails with a job queue.

**Comment by JesperSchulz** [comment]
Will close this issue and track the request in 10272 :-)
