### ISSUE TITLE
[Event Request] Table 83 "Item Journal Line" - OnValidateItemNoOnAfterAmount

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10270]
Hi, in the Table 83 "Item Journal Line", in the field 3 "Item No.", in the trigger OnValidate, we would like to add our code in a specific place. To do so, we would need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/102204273-f255f400-3ec9-11eb-83a3-0308e75a6d0b.png)

With the event integration :
![image](https://user-images.githubusercontent.com/34645582/102204222-dfdbba80-3ec9-11eb-9e4c-ef435cc76a6e.png)

Do you think it is possible ?

Thank for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
