### ISSUE TITLE
[Event Request] Table 83 "Item Journal Line" - OnValidateBinCodeOnBeforeNewBinCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10279]
Hi, in the Table 83 "Item Journal Line", in the field 5403 "Bin Code", in the trigger OnValidate, we would like to add our code in a specific place, and add a condition to an if statement. To do so, we would need an event publisher and a IsHandled flag, like this :

![image](https://user-images.githubusercontent.com/34645582/102241672-81c6cb80-3ef9-11eb-9185-357697dafbc4.png)

With the event integration :
![image](https://user-images.githubusercontent.com/34645582/102241585-6b207480-3ef9-11eb-8a55-f1cab217a501.png)

Do you think it is possible ?

Thank for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
