### ISSUE TITLE
[Event Request] Table 83 "Item Journal Line" - OnValidateLocationCodeOnBeforeGetUnitAmount

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10273]
Hi, in the Table 83 "Item Journal Line", in the field 9 "Location Code", in the trigger OnValidate, we would like to add our code in a specific place, and replace a if statement by our. To do so, we would need an event publisher and a IsHandled flag, like this :

![image](https://user-images.githubusercontent.com/34645582/102209668-62b44380-3ed1-11eb-8476-5b192b819110.png)

With the event integration :
![image](https://user-images.githubusercontent.com/34645582/102209629-53cd9100-3ed1-11eb-81ea-3376cb033d20.png)

Do you think it is possible ?

Thank for your work.

**Comment by StanPesotskiy** [comment]
Can you use the existing event OnBeforeValidateLocationCode()?

**Comment by Magicrevette** [comment]
It would not be efficient. The OnValidate trigger of the field 9 calls numerous local procedure, and I should copy/paste them to my event subscriber to still be able to call them, which would not allow our code to follow microsoft modification through updates.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
