### ISSUE TITLE
[Event Request] Codeunit 97 Blanket Purch. Order to Order - OnBeforeModifyPurchBlanketOrderLine

### ISSUE THREAD

**Issue by SER-KBROWN** [microsoft/ALAppExtensions#10284]
Please add this event:

if IsPurchOrderLineToBeInserted(PurchOrderLine) then begin
                        OnBeforeInsertPurchOrderLine(PurchOrderLine, PurchOrderHeader, PurchBlanketOrderLine, Rec);
                        PurchOrderLine.Insert;
                        OnAfterPurchOrderLineInsert(PurchOrderLine, PurchBlanketOrderLine);
                    end;
                    **OnBeforeModifyPurchBlanketOrderLine(PurchOrderLine, PurchBlanketOrderLine, PurchLine);**
                    if PurchBlanketOrderLine."Qty. to Receive" <> 0 then begin

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
