### ISSUE TITLE
[Event Request] Codeunit 97 Blanket Purch. Order to Order -OnBeforePurchLineFindSet

### ISSUE THREAD

**Issue by SER-KBROWN** [microsoft/ALAppExtensions#10283]
Please add this event: 

               then begin
                    PurchLine.SetCurrentKey("Document Type", "Blanket Order No.", "Blanket Order Line No.");
                    PurchLine.SetRange("Blanket Order No.", PurchBlanketOrderLine."Document No.");
                    PurchLine.SetRange("Blanket Order Line No.", PurchBlanketOrderLine."Line No.");
                    QuantityOnOrders := 0;
                    **OnBeforePurchLineFindSet(PurchLine);**
                    if PurchLine.FindSet then

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
