### ISSUE TITLE
[Event Request] Codeunit 12173 "Vendor Bill List - Post"

### ISSUE THREAD

**Issue by RobbieBonini** [microsoft/ALAppExtensions#10289]
Hi,

We would like to have an event added to Codeunit 12173 "Vendor Bill List - Post" procedure OnBeforeInsertPostedBillLine to be able to add our custom code at line 97 of CU. This will allow us to post our custom lines during vendor bill posting.

Function should be like that:

OnBeforeInsertPostedBillLine(VendorBillHeader, VendorBillLine, VendBillWithhTax, VendLedgEntry, BillCode, TaxType, PostedVendorBillHeader, BalanceAmountLCY);

Regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
