### ISSUE TITLE
[Event Request] Codeunit 2610 "Feature Management Impl." - UpdateData

### ISSUE THREAD

**Issue by hhoutaptean** [microsoft/ALAppExtensions#10288]
Hi,

We would like to have an event added to codeunit 2610 "Feature Management Impl.", procedure UpdateData() to be able to trigger our own extension data upgrade when the standard data upgrade is completed for standard tables.
Attention point is that extending the feature management facade (Access = Internal) is currently not possible.

 **Event:**
 ```
/// Runs the interface's data update method and updates the feature status.
procedure   UpdateData(var FeatureDataUpdateStatus: Record "Feature Data Update   Status"; FeatureDataUpdate: Interface "Feature Data Update")
   begin
     SetSessionInProgress(FeatureDataUpdateStatus);
     FeatureDataUpdate.UpdateData(FeatureDataUpdateStatus);
     FeatureDataUpdateStatus."Feature Status" := "Feature Status"::Complete;
     FeatureDataUpdateStatus.Modify();
     FeatureDataUpdate.AfterUpdate(FeatureDataUpdateStatus);
     // START EVENT ++             
     OnAfterUpdateData(FeatureDataUpdateStatus);
     // END EVENT --
end;                            
```
 
**Publisher function:**
```
[InternalEvent(false)]
local procedure OnAfterUpdateData (var FeatureDataUpdateStatus: Record "Feature Data Update Status")
begin
end;
```

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
