### ISSUE TITLE
[Event Request] Page 344 Navigate OnAfterNavigateFindExtRecords

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#10297]
In procedure FindExtRecords the call to UpdateFormAfterFindRecords is too early, beacuse it is before the trigger OnAfterNavigateFindExtRecords.
Please locate the UpdateFormAfterFindRecords as in the other routines after the publisher is called so the action ShowRecords is enabled after individual subsribing to OnAfterNavigateFindExtRecords:

old:
    local procedure FindExtRecords()
...
                    DocExists := FindFirst;

                    UpdateFormAfterFindRecords;
                    FoundRecords := DocExists;
                end;
            else
                Error(Text000);
        end;

        OnAfterNavigateFindExtRecords(Rec, ContactType, ContactNo, ExtDocNo, FoundRecords);

        if not FoundRecords then begin
            SetSource(0D, '', '', 0, '');
            Message(Text001);
        end;
    end;

new:
old:
    local procedure FindExtRecords()
...
                    DocExists := FindFirst;

                    FoundRecords := DocExists;
                end;
            else
                Error(Text000);
        end;

        OnAfterNavigateFindExtRecords(Rec, ContactType, ContactNo, ExtDocNo, FoundRecords);
//+++++++++++++++++
if FoundRecpords then
                    UpdateFormAfterFindRecords;
//--------------------------

        if not FoundRecords then begin
            SetSource(0D, '', '', 0, '');
            Message(Text001);
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
