### ISSUE TITLE
[Scope Change] Codeunit "Withholding - Contribution" All functions

### ISSUE THREAD

**Issue by RobbieBonini** [microsoft/ALAppExtensions#10290]
Hi,
Would it be possible that you removed the [Scope('OnPrem')] from all the functions inside Codeunit "Withholding - Contribution".

We need to copy the Codeunit 12173 "Vendor Bill List - Post" to add our customizations in a sections where there are no available events, but we need to use the functions inside Codeunit "Withholding - Contribution".

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
