### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnBeforeCheckBlockedCustOnJnls

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10295]
Hi, would it be possible to get an event OnBeforeCheckBlockedCustOnJnls in Codeunit 12 Gen. Jnl.-Post Line , like this : 
![image](https://user-images.githubusercontent.com/73548802/102356972-29053a80-3fae-11eb-9278-bec5729e8c02.png)
?

Thanks

**Comment by StanPesotskiy** [comment]
Is it ok to use existing event OnBeforeCheckBlockedCust for Cust.CheckBlockedCustOnJnls function?
