### ISSUE TITLE
[updated] event request - codeunit 11 "Gen. Jnl.-Check Line" - OnBeforeTestCheckTransmitted(var Handled)

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#10292]
`CheckAccountNo()` and `CheckBalAccountNo()` do this (for their corresponding `Account`s):

                "Account Type"::"Bank Account":
                    begin
                        [...]
                        if ("Bank Payment Type" = "Bank Payment Type"::"Electronic Payment") or
                           ("Bank Payment Type" = "Bank Payment Type"::"Electronic Payment-IAT")
                        then begin
                            TestField("Exported to Payment File", true);
                            TestField("Check Transmitted", true);
                        end;
                    end;

There's an obvious problem here that we keep running into and are agog that it hasn't been fixed yet: If exporting payment files from the journal via standard Exp Gen Jnl codeunits, they only set `Exported to Payment File` but not `Check Transmitted`. Thus the `TestField()` fails and every new BC customer complains and needs a subscriber added to work around this (by setting `Check Transmitted` to `true`, don't even need to `Modify()`.)

If this isn't going to be fixed in the base code, can we at least get an event to avoid it in a nicer way than 'faking' the value of `Check Transmitted` long enough for the check to pass?

                        if ("Bank Payment Type" = "Bank Payment Type"::"Electronic Payment") or
                           ("Bank Payment Type" = "Bank Payment Type"::"Electronic Payment-IAT")
                        then begin
                            TestField("Exported to Payment File", true);
                            
                            OnBeforeTestCheckTransmitted(GenJnlLine, Handled);

                            if not Handled then
                              TestField("Check Transmitted", true);
                        end;

where that publisher is declared as:

    local procedure OnBeforeTestCheckTransmitted(GenJournalLine: Record "Gen. Journal Line"; var Handled: Boolean)

This should be called from both `CheckAccountNo()` and `CheckBalAccountNo()`. Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
