### ISSUE TITLE
[Event Request] Page 344 Navigate OnAfterNavigateShowRecords

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#10296]
As ShowRecords is used from both after FindRecords and FindExtRecords we need additional parameters in the existing event OnAfterNavigateShowRecords:

old:
local procedure OnAfterNavigateShowRecords(TableID: Integer; DocNoFilter: Text; PostingDateFilter: Text; ItemTrackingSearch: Boolean; var TempDocumentEntry: Record "Document Entry" temporary; SalesInvoiceHeader: Record "Sales Invoice Header"; SalesCrMemoHeader: Record "Sales Cr.Memo Header"; PurchInvHeader: Record "Purch. Inv. Header"; PurchCrMemoHdr: Record "Purch. Cr. Memo Hdr."; ServiceInvoiceHeader: Record "Service Invoice Header"; ServiceCrMemoHeader: Record "Service Cr.Memo Header")
new:
local procedure OnAfterNavigateShowRecords(TableID: Integer; DocNoFilter: Text; PostingDateFilter: Text; ItemTrackingSearch: Boolean; var TempDocumentEntry: Record "Document Entry" temporary; SalesInvoiceHeader: Record "Sales Invoice Header"; SalesCrMemoHeader: Record "Sales Cr.Memo Header"; PurchInvHeader: Record "Purch. Inv. Header"; PurchCrMemoHdr: Record "Purch. Cr. Memo Hdr."; ServiceInvoiceHeader: Record "Service Invoice Header"; ServiceCrMemoHeader: Record "Service Cr.Memo Header";ContactType: Enum "Navigate Contact Type"; ContactNo: Code[250]; ExtDocNo: Code[250];);

or another possibility to get the three parameters  ContactType: Enum "Navigate Contact Type"; ContactNo: Code[250]; ExtDocNo: Code[250];

at OnAfterNavigateShowRecords, maybe with the pagesender as get-procedure, because OnAfterNavigateShowRecords already delivers the page navigate as includesender=true

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
