### ISSUE TITLE
"Data Compression".ExtractEntry() throws exception

### ISSUE THREAD

**Issue by sarocker** [microsoft/ALAppExtensions#10294]
Hi!

In the original function "Data Compression Impl.".ExtractEntry() the ZipArchiveEntry.Length() call throws an exception because it is called after ZipArchiveEntry.Open(). ZipArchiveEntry.Length() has to be moved up before opening entry to solve this problem.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
