### ISSUE TITLE
[Event Request] Codeunit 5005271 "Create Delivery Reminder" - OnFilterDelivReminLedgerEntries

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#10305]
Hi, in Codeunit 5005271 "Create Delivery Reminder" we would like to add filters to the delivery reminder entries. To do so, we would need an event publisher like this:
![image](https://user-images.githubusercontent.com/34675109/102470715-a08da500-4054-11eb-8929-b550a871fd5a.png)
publisher signature:
![image](https://user-images.githubusercontent.com/34675109/102470908-d6328e00-4054-11eb-8edd-d7f3733da5ed.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
