### ISSUE TITLE
[Event Request] Codeunit 21 Item Jnl.-Check Line - OnAfterCheckDimValuePosting

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10301]
Hi, would it be possible to get an event OnAfterCheckDimValuePosting in  Codeunit 21 Item Jnl.-Check Line, like this
![image](https://user-images.githubusercontent.com/73548802/102377805-62957000-3fc5-11eb-85c2-ba1a997935d4.png)
?

Thanks

**Comment by StanPesotskiy** [comment]
There is OnBeforeCheckDimensions() to avoid unnecessary checks. Ask for more parameters to this event if needed.
