### ISSUE TITLE
[updated] event request - codeunit 1535 "Approvals Mgmt." - OnAfterCanCancelApprovalForRecord(RecordId, var Handled, var HandledResult)

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#10306]
For certain types of document, we want the ability to cancel approval requests to be determined by something else, e.g. a User Setup checkbox or whatever. We want to do this right, at the source, rather than having to amend page actions' enabled prop for every list/card page related do that type of record. Therefore, please add the following event publisher method call to allow this:

```al
procedure CanCancelApprovalForRecord(RecID: RecordID): Boolean
var
    ApprovalEntry: Record "Approval Entry";
    UserSetup: Record "User Setup";
    Handled, HandledResult: Boolean; // ADD
begin
    if not UserSetup.Get(UserId) then
        exit(false);

    ApprovalEntry.SetRange("Table ID", RecID.TableNo);
    ApprovalEntry.SetRange("Record ID to Approve", RecID);
    ApprovalEntry.SetFilter(Status, '%1|%2', ApprovalEntry.Status::Created, ApprovalEntry.Status::Open);
    ApprovalEntry.SetRange("Related to Change", false);

    if not UserSetup."Approval Administrator" then
        ApprovalEntry.SetRange("Sender ID", UserId);

    // +ADD
    // exit(ApprovalEntry.FindFirst());

    if not ApprovalEntry.IsEmpty() then
        exit(true);

    OnAfterCanCancelApprovalForRecord(RecID, Handled, HandledResult);

    if Handled then
        exit(HandledResult);

    exit(false);
    // -ADD
end;
```

where that publisher will be declared as

        local procedure OnAfterCanCancelApprovalForRecord(RecordId: RecordId; var Handled: Boolean; var HandledResult: Boolean)

and subscribers will set `Handled := true` and `HandledResult := whatever` if they want to extend the standard behaviour.

Thanks!

**Comment by dtkb** [comment]
Thinking a bit more, this might be better done as

```al
procedure CanCancelApprovalForRecord(RecID: RecordID): Boolean
var
    ApprovalEntry: Record "Approval Entry";
    UserSetup: Record "User Setup";
    Handled, HandledResult: Boolean; // ADD
begin
    if not UserSetup.Get(UserId) then
        exit(false);

    ApprovalEntry.SetRange("Table ID", RecID.TableNo);
    ApprovalEntry.SetRange("Record ID to Approve", RecID);
    ApprovalEntry.SetFilter(Status, '%1|%2', ApprovalEntry.Status::Created, ApprovalEntry.Status::Open);
    ApprovalEntry.SetRange("Related to Change", false);

    if not UserSetup."Approval Administrator" then
        ApprovalEntry.SetRange("Sender ID", UserId);

    if not ApprovalEntry.IsEmpty() then
        exit(true);

    // +ADD
    OnAfterCanCancelApprovalForRecord(RecID, Handled, HandledResult);

    if Handled then
        exit(HandledResult);

    exit(false);
    // -ADD
end;
```

because that way, we can use the standard logic, and only add on our additional allowances to cancel if that fails.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
