### ISSUE TITLE
[Event Request] Codeunit 7000"Sales Price Calc. Mgt." - OnAfterCalcBestUnitPrice

### ISSUE THREAD

**Issue by robinfjelldal** [microsoft/ALAppExtensions#10307]
Hi MS,
Would like to add parameter "BestSalesPrice" to the event: OnAfterCalcBestUnitPrice in Codeunit 7000 "Sales Price Calc. Mgt.":

```
                    end;
                    end;
                until Next = 0;
        end;
        //>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        OnAfterCalcBestUnitPrice(SalesPrice,BestSalesPrice);
       //<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        // No price found in agreement
        if not BestSalesPriceFound then begin
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcBestUnitPrice(var SalesPrice: Record "Sales Price"; var BestSalesPrice: Record "Sales Price")
    begin
    end;
```

Thanks,
best regards,
Robin Fjelldal

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
