### ISSUE TITLE
[Event Request] Codeunit 21 Item Jnl.-Check Line - OnNotIsValueEntryForDeletedItem

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10300]
Hi, would it be possible to get an event OnNotIsValueEntryForDeletedItem in Codeunit 21 Item Jnl.-Check Line, like this
![image](https://user-images.githubusercontent.com/73548802/102374263-6cb56f80-3fc1-11eb-8dcc-cf7d0bfe5ff3.png)
![image](https://user-images.githubusercontent.com/73548802/102374321-7d65e580-3fc1-11eb-9b05-1ad7e451e436.png)
?
Thanks

**Comment by StanPesotskiy** [comment]
There is OnBeforeCheckDimensions() to avoid unnecessary checks. Ask for more parameters to this event if needed.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
