### ISSUE TITLE
Extensibility issues: Page 9233 G/L Balance by Dim. Matrix

### ISSUE THREAD

**Issue by matteomontanari** [microsoft/ALAppExtensions#10309]
We need new event to handle the behavior of the Drilldown method.

Something like:
`    [IntegrationEvent(false, false)]
    local procedure OnBeforeDrillDown(SetColFilter: Boolean; var GLAcc: Record "G/L Account"; AnalysisByDimParameters: Record "Analysis by Dim. Parameters"; var Handled: Boolean)`

The DrillDown procedure changed as following:

```
    local procedure DrillDown(SetColFilter: Boolean)
    var
        GLEntry: Record "G/L Entry";
        GLBudgetEntry: Record "G/L Budget Entry";
        Handled : Boolean; //Added Variable
    begin
        SetCommonFilters(GLAcc);
        SetDimFilters(GLAcc, 0);
        if SetColFilter then
            SetDimFilters(GLAcc, 1);

        //Start Added
        OnBeforeDrillDown(SetColFilter, GLAcc, AnalysisByDimParameters, Handled);
        if Handled then
            exit;
        //Stop Added
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
