### ISSUE TITLE
[Event Request] Table 83 "Item Journal Line" - OnRetrieveCostsOnBeforeUnitCost

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10316]
Hi, in the Table 83 "Item Journal Line", in the procedure RetrieveCosts, we would like to add our code in a specific place, and add a condition to an if statement. To do so, we would need an event publisher and a IsHandled flag, like this :

![image](https://user-images.githubusercontent.com/34645582/102605356-722bca80-4125-11eb-91d1-57c096dd341d.png)

With the event integration :
![image](https://user-images.githubusercontent.com/34645582/102605324-6809cc00-4125-11eb-88a3-27f417fd8ece.png)

Do you think it is possible ?

Thank for your work.

**Comment by StanPesotskiy** [comment]
Can't you use existing events OnBeforeRetrieveCosts or/and OnRetrieveCostsOnAfterSetUnitCost?

**Comment by Magicrevette** [comment]
Unfortunately, no. The first one requires to copy/paste local procedures in our codeunit, and the second one doesn't allow us to do what we would like to.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
