### ISSUE TITLE
Report 7318 - Add Code to OnPostReport to suppress error

### ISSUE THREAD

**Issue by SCreanor** [Microsoft/ALAppExtensions#1031]
Can code please be added to the OnPostReport section of this report to allow the suppression of the error thrown if nothing is found to handle. The same suppression available for the GetResultMessage function can be used.

Existing code to be changed as outlined below with a new check added;
```
IF WhseActivHeader.FIND('-') THEN BEGIN
  REPEAT
    IF SortActivity > 0 THEN
      WhseActivHeader.SortWhseDoc;
  UNTIL WhseActivHeader.NEXT = 0;

  IF PrintDoc THEN BEGIN
    IsHandled := FALSE;
    OnBeforePrintPickingList(WhseActivHeader,IsHandled);
    IF NOT IsHandled THEN
      REPORT.RUN(REPORT::"Picking List",FALSE,FALSE,WhseActivHeader);
  END;
END ELSE
  IF NOT HideValidationDialog THEN // ***** Inserted Line *****
    ERROR(NothingToHandleErr);`

**Comment by IhorHandziuk** [comment]
Thank you for your request @SCreanor 
We will introduce new function `SetHideNothingToHandleError` specifically for this purpose
