### ISSUE TITLE
[Event Request] Codeunit 21 Item Jnl.-Check Line - OnAfterDimMgtCheckDimIDComb2

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10312]
Hi, would it be possible to get an event OnAfterDimMgtCheckDimIDComb2 in codeunit 21 Item Jnl.-Check Line  procedure CheckDimensions, like this : 
![image](https://user-images.githubusercontent.com/73548802/102598501-6d164d80-411c-11eb-9f25-58b0f503676d.png)
![image](https://user-images.githubusercontent.com/73548802/102598614-9505b100-411c-11eb-94b5-3d82e9c9f779.png)
?
Thanks

**Comment by StanPesotskiy** [comment]
There is OnBeforeCheckDimensions() to avoid unnecessary checks. Ask for more parameters to this event if needed.
