### ISSUE TITLE
Extensibility: "Qty. to Handle (Base)" on Warehouse Activity Line is overwritten

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#10328]
In the table `Warehouse Activity Line`, when you validate the field `Qty. to Handle`, the field `Qty. to Handled (Base)` is overwritten with the value from `Outstanding Qty. (Base)` if it's greater than that. This is the code:

````

                if not UseBaseQty then begin
                    "Qty. to Handle (Base)" :=
                        UOMMgt.CalcBaseQty("Item No.", "Variant Code", "Unit of Measure Code", "Qty. to Handle", "Qty. per Unit of Measure");
                    if "Qty. to Handle (Base)" > "Qty. Outstanding (Base)" then // rounding error- qty same, not base qty
                        "Qty. to Handle (Base)" := "Qty. Outstanding (Base)";
                end;
````

Judging from the comment, this is to handle eventual rounding differences. But it seems a little harsh to just overwrite this. I suggest the following:
- Only adjust the quantities if the difference is within a given range (like .. 0.001 or 0.01 or something)
- Introduce an event to let us customize how - and if - the quantity is adjusted, or maybe the factor. Like:
  `OnAdjustQtyToHandleForRounding(WhseActLine: Record "Warehouse Activity Line"; OrigianalQtyToHandle: Decimal; var NewQtytoHandle: Decimal);`

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by hemisphera** [comment]
No. This is clearly *not* a bug report. The code is working as expected, it's just not extensible. Reopen the issue, thanks.

**Comment by StanPesotskiy** [comment]
What is the place in the existing code where OnAdjustQtyToHandleForRounding will be called from?

**Comment by hemisphera** [comment]
New or changed lines are marked with `// NEW`
````
                if not UseBaseQty then begin
                    "Qty. to Handle (Base)" :=
                        UOMMgt.CalcBaseQty("Item No.", "Variant Code", "Unit of Measure Code", "Qty. to Handle", "Qty. per Unit of Measure");
                    
                    if "Qty. to Handle (Base)" > "Qty. Outstanding (Base)" then begin // rounding error- qty same, not base qty
                        NewQtyToHandleBase := "Qty. Outstanding (Base)"; // NEW
                        OnAdjustQtyToHandleForRounding(Rec, "Qty. To Handle (Base)", NewQtyToHandleBase); // NEW
                        "Qty. to Handle (Base)" := NewQtyToHandleBase; // NEW
                    end;
                end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
