### ISSUE TITLE
Codeunit 5407 Prod. Order Status Management - Change signature of existing Publisher OnCopyFromProdOrderComp in local Function TransProdOrderComp

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#10326]
Requesting a change of Publisher OnCopyFromProdOrderComp in local function TransProdOrderComp

Existing Event
`OnCopyFromProdOrderComp(VAR ToProdOrderComp : Record "Prod. Order Component" ; FromProdOrderComp : Record "Prod. Order Component")`

Requested changed Event:
`OnCopyFromProdOrderComp(VAR ToProdOrderComp : Record "Prod. Order Component" ; VAR FromProdOrderComp : Record "Prod. Order Component")`

This is identical to the other Trans functiosn on the other production Tables,
TransProdOrder, Publisher OnAfterTransProdOrder for example

So could you please make the parameter FromProdOrderComp by Reference (VAR) in publisher OnCopyFromProdOrderComp?

We need this to prevent code execution by deleting Prod. Order Components during this process. In Status Changing new records are created the old ones are deleted. We have defined a subscriber for the OnAfterDelete on the Prod. Order Component. We have added a custom field which we want to set during Prod. Order Status change so the Subscriber can be exited during this process.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
