### ISSUE TITLE
[Parameter Request] Codeunit 99000845 "Reservation Management" - OnBeforeDeleteItemTrackingConfirm

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10323]
We would like to request an additional Parameter „Response“ in procedure OnBeforeDeleteItemTrackingConfirm of Codeunit 99000845 "Reservation Management":

```
    [IntegrationEvent(true, false)]
//    local procedure OnBeforeDeleteItemTrackingConfirm(var CalcReservEntry2: Record "Reservation Entry"; var IsHandled: Boolean)
    local procedure OnBeforeDeleteItemTrackingConfirm(var CalcReservEntry2: Record "Reservation Entry"; var Response: Boolean; var IsHandled: Boolean)
    begin
    end;
```

The new parameter should be used in Procedure „DeleteItemTrackingConfirm“ of the same Codeunit 99000845 "Reservation Management":

```
    procedure DeleteItemTrackingConfirm(): Boolean
    var
        ConfirmManagement: Codeunit "Confirm Management";
        IsHandled: Boolean;
// new
        Response: Boolean;
    begin
        IsHandled := false;
//        OnBeforeDeleteItemTrackingConfirm(CalcReservEntry2, IsHandled);
        OnBeforeDeleteItemTrackingConfirm(CalcReservEntry2, Response, IsHandled);
        if IsHandled then
//            exit;
            exit(Response);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
