### ISSUE TITLE
[EventRequest] Codeunit 5407 Prod. Order Status Management - OnChangeStatusOnProdOrderOnBeforeCostAdjustment

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#10325]
Requesting a new event publisher on Codeunit 5407 Prod. Order Status Management

Event
`OnChangeStatusOnProdOrderOnBeforeCostAdjustment(ProductionOrder : Record "Production Order"; VAR IsHandled :   Boolean)`

**Code**
## [External] ChangeStatusOnProdOrder(ProdOrder : Record "Production Order";NewStatus : 'Quote,Planned,Firm Planned,Released,Finished';NewPostingDate : Date;NewUpdateUnitCost : Boolean)
```
SetPostingInfo(NewStatus,NewPostingDate,NewUpdateUnitCost);
OnBeforeChangeStatusOnProdOrder(ProdOrder,NewStatus);
IF NewStatus = NewStatus::Finished THEN BEGIN
  CheckBeforeFinishProdOrder(ProdOrder);
  FlushProdOrder(ProdOrder,NewStatus,NewPostingDate);
  ReservMgt.DeleteDocumentReservation(DATABASE::"Prod. Order Line",ProdOrder.Status,ProdOrder."No.",FALSE);
  ErrorIfUnableToClearWIP(ProdOrder);
  TransProdOrder(ProdOrder);
```
**>>> New Code**
```
  IsHandled := FALSE;
  OnChangeStatusProdOrderOnBeforeCostAdjustment(
  OnChangeStatusOnProdOrderOnBeforeCostAdjustment(ProdOrder, IsHandled);
  IF NOT IsHandled THEN BEGIN

```
**<<< New Code End**
```
    InvtSetup.GET;
    IF InvtSetup."Automatic Cost Adjustment" <>
       InvtSetup."Automatic Cost Adjustment"::Never
    THEN BEGIN
      InvtAdjmt.SetProperties(TRUE,InvtSetup."Automatic Cost Posting");
      InvtAdjmt.MakeMultiLevelAdjmt;
    END;
```
**>>> New Code**
```
  END;
```
**<<< New Code End**
```
  WhseProdRelease.FinishedDelete(ProdOrder);
  WhseOutputProdRelease.FinishedDelete(ProdOrder);
END ELSE BEGIN
  TransProdOrder(ProdOrder);
  FlushProdOrder(ProdOrder,NewStatus,NewPostingDate);
  WhseProdRelease.Release(ProdOrder);
END;
OnAfterChangeStatusOnProdOrder(ProdOrder,ToProdOrder);

COMMIT;

CLEAR(InvtAdjmt);
```

In Our Solution we have a link between Jobs and Production. 
For Production Orders we which are linked to a Job we do not want to do Inventory Adjustments and want to skip this.
Please add the requested publisher.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
