### ISSUE TITLE
[Event Request] Table 1799 Data Migration Status- OnBeforeOnModify

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10327]
Hi, would it be possible to create a new event OnBeforeOnModifyin table 1799 Data Migration Status, like this :
![image](https://user-images.githubusercontent.com/76154006/102757569-d17e1a80-4371-11eb-8571-e32d4ef7377a.png)
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
