### ISSUE TITLE
[EventRequest] Codeunit 5895 Inventory Adjustment - OnWIPToAdjustExistsOnAfterSetFilters

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#10324]
Requesting a new event publisher on Codeunit 5895 Inventory Adjustment

Event
`OnWIPToAdjustExistsOnAfterSetFilters(VAR InventoryAdjmtEntryOrder : Record "Inventory Adjmt. Entry (Order)")`

**Code**
## LOCAL WIPToAdjustExist(VAR ToInventoryAdjmtEntryOrder : Record "Inventory Adjmt. Entry (Order)") : Boolean
```
WITH InventoryAdjmtEntryOrder DO BEGIN
  RESET;
  SETCURRENTKEY("Cost is Adjusted","Allow Online Adjustment");
  SETRANGE("Cost is Adjusted",FALSE);
  SETRANGE("Order Type","Order Type"::Production);
  SETRANGE("Is Finished",TRUE);
  IF IsOnlineAdjmt THEN
    SETRANGE("Allow Online Adjustment",TRUE);
```
**>>> New Code**
```
  OnWIPToAdjustExistOnAfterSetFilters(InventoryAdjmtEntryOrder);
```
**<<< New Code End**
```
  CopyOrderAdmtEntryToOrderAdjmt(InventoryAdjmtEntryOrder,ToInventoryAdjmtEntryOrder);
  EXIT(ToInventoryAdjmtEntryOrder.FINDFIRST);
END;

```

In Our Solution we have a link between Jobs and Production. 
We want to have the possibility to filter out any Production order WIP adjustments for Production Orders which are related to a Job (Field Job No. is populated in those records).
Please add the requested publisher.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
