### ISSUE TITLE
[Event Request] Codeunit 7307 - Whse.-Activity-Register - OnBeforeCheckAndRemoveOrderToOrderBinding

### ISSUE THREAD

**Issue by LucaMartinengo** [microsoft/ALAppExtensions#10337]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher OnBeforeCheckAndRemoveOrderToOrderBinding to be added to Codeunit 7307 Whse.-Activity-Register with the following signature:

`LOCAL [IntegrationEvent] OnBeforeCheckAndRemoveOrderToOrderBinding(VAR TempWhseActivLineToReserve : TEMPORARY Record "Warehouse Activity Line";VAR IsHandled : Boolean)`

with VAR parameters TempWhseActivLineToReserve  and IsHandled .
Which would be called as follows from CheckAndRemoveOrderToOrderBinding:

`LOCAL CheckAndRemoveOrderToOrderBinding(VAR TempWhseActivLineToReserve : TEMPORARY Record "Warehouse Activity Line")`
`// >> Call to new event`
`IsHandled := FALSE;`
`OnBeforeCheckAndRemoveOrderToOrderBinding(TempWhseActivLineToReserve, IsHandled);`
`IF IsHandled THEN`
`    EXIT;`
`// << Call to new event`
`IF TempWhseActivLineToReserve.FINDSET THEN`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
