### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - OnBeforeProcedureInsertValueEntry

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10331]
Hi, would it be possible to get an event OnBeforeProcedureInsertValueEntry in Codeunit 22 Item Jnl.-Post Line, procedure InsertValueEntry, like this : 
![image](https://user-images.githubusercontent.com/73548802/102768255-283f2080-4381-11eb-9a41-6e30d73d9209.png)
![image](https://user-images.githubusercontent.com/73548802/102768377-5b81af80-4381-11eb-8559-9a71c8bd5001.png)
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
