### ISSUE TITLE
[Event Request] Table 83 "Item Journal Line" - OnValidateItemNoOnAfterCreateDim V2

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10330]
Hello. I asked an event in the topic #10240, and you suggested me to use an already existing event. I told you it would fit to my needs, but I realised a short time later I was wrong. In the meantime, you closed the topic. So I create a new one with the event request than before. Here it is : 

In the Table 83 "Item Journal Line", in the field 3 "Item No.", in the trigger OnValidate, we would like to add our code in a specific place. To do so, we would need an event publisher, like this :

![image](https://user-images.githubusercontent.com/34645582/101923359-95a7c000-3bcf-11eb-89c3-272760ea22e8.png)

With the event integration :
![image](https://user-images.githubusercontent.com/34645582/101921782-a9522700-3bcd-11eb-8e02-f6894059e3a6.png)

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
