### ISSUE TITLE
Codeunit -57 : Document Totals

### ISSUE THREAD

**Issue by krishnaGottuparthi** [Microsoft/ALAppExtensions#1033]
Function Name : **CalculateSalesSubPageTotals** :Need parameter Change from **TotalSalesLine** to **TotalSalesLine2** and extra parameter **SalesLine** for event **OnAfterCalculateSalesSubPageTotals**.

![image](https://user-images.githubusercontent.com/35251581/52038018-dd327f00-2556-11e9-9ef5-ae31d77e8925.png)

We have subscribed **OnAfterCalculateSalesSubPageTotals** event and done some changes for **TotalSalesline** as it is VAR, but in the Last line **TotalSalesLine** is overridden by **TotalsalesLine2** which is clearing the changes done on **TotalSalesLine**.
Please change the parameter to **TotalSalesLine2** from **TotalSalesLine.**
And also need extra parameter **SalesLine** record from the page 46 – Sales Order Subform.

Regards,
Krishna.

**Comment by MatthewMcCarthy7** [comment]
This was solved in issue #837. It is in the updated daily build.
