### ISSUE TITLE
[Event Request] Codeunit 1303 "Correct Posted Sales Invoice"

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#10336]
End of the Function "CreateCopyDocument":
OnAfterCreateCopyDocument(var SalesHeader: Record "Sales Header"; var SalesInvoiceHeader: Record "Sales Invoice Header")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
