### ISSUE TITLE
Issues with Retention Policy Module

### ISSUE THREAD

**Issue by mynavblog** [microsoft/ALAppExtensions#10335]
Dear Team,

I was checking the Retention Policy Module and here are some issues which I found:

1. Instead of Table Caption in the header the Table Name is shown (which shows also the Prefix)
![image](https://user-images.githubusercontent.com/37371997/102779103-fa170c00-4393-11eb-9341-6256f6a342c6.png)

2. Expired Records field does not show correct values - even if records exist (before deleted with the manual run) the field always shows 0.

3. (Minor thing) Job Queue for Retention Policy does not have a description

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
