### ISSUE TITLE
[Event Request] Codeunit 6620 Copy Document Mgt. OnMoveNegLinesAfterValidateQuantity

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#10341]
We need new event publisher in codeunit 6620 Copy Document Mgt.  in the case of MoveNegativeLines=True and (Sales/PurchLine.type <> Sales/PurchLine.Type::" ") where quantity switches the signs, so we can also use this trigger to switch individual values:

For example:

        if MoveNegLines and (ToSalesLine.Type <> ToSalesLine.Type::" ") then begin
            ToSalesLine.Validate(Quantity, -FromSalesLine.Quantity);
/+++++++++++++++++++++++++++++++
OnMoveNegLinesAfterValidateQuantity(VAR TosalesLine,FromSalesLine);
/--------------------------------------
            ToSalesLine.Validate("Unit Price", FromSalesLine."Unit Price");
            ToSalesLine.Validate("Line Discount %", FromSalesLine."Line Discount %");
            ToSalesLine."Appl.-to Item Entry" := FromSalesLine."Appl.-to Item Entry";
            ToSalesLine."Appl.-from Item Entry" := FromSalesLine."Appl.-from Item Entry";
            ToSalesLine."Job No." := FromSalesLine."Job No.";
            ToSalesLine."Job Task No." := FromSalesLine."Job Task No.";
            ToSalesLine."Job Contract Entry No." := FromSalesLine."Job Contract Entry No.";
        end;

        if MoveNegLines and (ToSalesLine.Type <> ToSalesLine.Type::" ") then begin
            ToSalesLine.Validate(Quantity, -FromSalesLineArchive.Quantity);
/+++++++++++++++++++++++++++++++
OnMoveNegLinesAfterValidateQuantity(VAR TosalesLine,FromSalesLineArchive);
/--------------------------------------
            ToSalesLine.Validate("Line Discount %", FromSalesLineArchive."Line Discount %");
            ToSalesLine."Appl.-to Item Entry" := FromSalesLineArchive."Appl.-to Item Entry";
            ToSalesLine."Appl.-from Item Entry" := FromSalesLineArchive."Appl.-from Item Entry";
        end;

        if MoveNegLines and (ToPurchLine.Type <> ToPurchLine.Type::" ") then begin
            ToPurchLine.Validate(Quantity, -FromPurchLine.Quantity);
/+++++++++++++++++++++++++++++++
OnMoveNegLinesAfterValidateQuantity(VAR ToPurchLine,FromPurchLine);
/--------------------------------------
            ToPurchLine."Appl.-to Item Entry" := FromPurchLine."Appl.-to Item Entry"
        end;

        if MoveNegLines and (ToPurchLine.Type <> ToPurchLine.Type::" ") then begin
            ToPurchLine.Validate(Quantity, -FromPurchLineArchive.Quantity);
/+++++++++++++++++++++++++++++++
OnMoveNegLinesAfterValidateQuantity(VAR ToPurchLine,FromPurchLineArchive);
/--------------------------------------
            ToPurchLine."Appl.-to Item Entry" := FromPurchLineArchive."Appl.-to Item Entry"
        end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
