### ISSUE TITLE
[request-for-external] Codeunit 12 Make the functions InitVAT & PostVAT global

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#10342]
At the moment these 2 functions are local in codeunit 12. We want to use the functions to post VAT, but we cant because they are local. Can you make them global?

local procedure InitVAT(var GenJnlLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; var VATPostingSetup: Record "VAT Posting Setup")

local procedure PostVAT(GenJnlLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; VATPostingSetup: Record "VAT Posting Setup")

BC17.2

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
