### ISSUE TITLE
[Access Request] page 402 "Sales Order Statistics" - TotalAmount1

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#10347]
Can you change TotalAmount1 to protected var. As I need this to do additional calculations in page extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
