### ISSUE TITLE
[Scope Change] Table Sales Shipment Header - EmailRecords

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#10340]
Request to remove Scope('OnPrem') from function EmailRecords in table "Sales Shipment Header".

It would also be nice if an extra function to email Posted Shipments can be added to page "Posted Sales Shipments" similar to "Posted Sales Invoices".

**Comment by prachou** [comment]
Same need than @ajkauffmann 
Is it on the roadmap ?

**Comment by AlexanderYakunin** [comment]
Scope('OnPrem') removed. 

This is not the right place to ask about functional changes, instead you can always add new idea on http://aka.ms/bcideas. I think shipment e-mail story already requested here.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
