### ISSUE TITLE
[Request-for-external] page 343 "Check Credit Limit" - SalesHeaderShowWarning

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#10349]
Can you remove [Scope('OnPrem')] from procedure SalesHeaderShowWarning in page "Check Credit Limit".

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
