### ISSUE TITLE
[Event Request] page 398 "Sales Credit Memo Statistics" - OnAfterGetRecordOnAfterCalculateAdjProfitLCY

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#10344]
Can you add AmountLCY and TotalAdjCostLCY as paramater to event OnAfterGetRecordOnAfterCalculateAdjProfitLCY?

```
        //OnAfterGetRecordOnAfterCalculateAdjProfitLCY(Rec, AdjProfitLCY);
        OnAfterGetRecordOnAfterCalculateAdjProfitLCY(Rec, AdjProfitLCY, AmountLCY, TotalAdjCostLCY);
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterGetRecordOnAfterCalculateAdjProfitLCY(SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var AdjProfitLCY: Decimal; AmountLCY: Decimal; TotalAdjCostLCY: Decimal)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
