### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforeCopyDocumentFields

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10357]
Hi, in the Codeunit 80 Sales Post, would it be possible to get an event OnBeforeCopyDocumentFields, like this :
![image](https://user-images.githubusercontent.com/76154006/102983894-0a062b80-450d-11eb-816a-5fa5eaaa9366.png)
![image](https://user-images.githubusercontent.com/76154006/103205086-0f8eb780-48f9-11eb-9836-c8da38ef3b6c.png)

Thanks

**Comment by dtkb** [comment]
Shouldn't `OnBeforeCopyDocumentFields()` be called **before** `CopyDocumentFields()`...? Then should it have a `var Handled` to allow subscriber to opt out of `CopyDocumentFields()`? Finally, presumably the `GenJnlLine` argument should be `var` if you want to assign to fields?

**Comment by Herodoteux** [comment]
Sorry I made a typo.
excuse me for the inconvenience.

**Comment by StanPesotskiy** [comment]
It is not clear, what should be corrected. Please provide the required event's placement and its full signature.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
