### ISSUE TITLE
Table 5906 Service Comment Line field Table Subtype

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#10354]
Is it possible to make Table 5906 Service Comment Line field Table Subtype an Enum type of field?   Thanks.  

![image](https://user-images.githubusercontent.com/49729094/102935924-176fd700-4475-11eb-8637-b667db348773.png)

**Comment by AlexanderYakunin** [comment]
No, this is not possible, as this table used for different master tables, and values in Subtype can refer to different options/enums there. Please use this as Integer.
