### ISSUE TITLE
[Event Request] CU 5705 "TransferOrder-Post Receipt" OnRunOnBeforeFindTransline"

### ISSUE THREAD

**Issue by prisma-chku** [microsoft/ALAppExtensions#10356]
Could we please have a new publisher “OnRunOnBeforeFindTransline” in Function “OnRun”, Codeunit 5705 "TransferOrder-Post Receipt”?

```AL
...
// Insert receipt lines
LineCount := 0;
if WhseReceive then
    PostedWhseRcptLine.LockTable();
if InvtPickPutaway then
    WhseRqst.LockTable();
TransRcptLine.LockTable();
TransLine.SetRange(Quantity);
TransLine.SetRange("Qty. to Ship");
>>>>>>>>>> NEW CODE >>>>>>>>
OnRunOnBeforeFindTransline(TransLine, TransHeader, Location, WhseReceive);
<<<<<<<<<< NEW CODE <<<<<<<<
if TransLine.Find('-') then
    repeat
        LineCount := LineCount + 1;
        if GuiAllowed then
            Window.Update(2, LineCount);
...
```

```AL
[IntegrationEvent(false, false)]
local procedure OnRunOnBeforeFindTransline(var TransferLine: Record "Transfer Line"; TransferHeader: Record "Transfer Header"; Location: Record Location; WhseReceive: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by AndreiPanko** [comment]
@prisma-chku could you please clarify why do you need this event?
I'm asking as for the next version we are adding additional filter: Qty to Receive <> 0.

**Comment by prisma-chku** [comment]
Hello @AndreiPanko ,

actually we would like to use the event to prevent creation of posted rows with quantity = 0 if needed. This is equivalent to the filter you mentioned ("Qty. to Receive", '<>0').
