### ISSUE TITLE
[Request-for-external] table 39 "Purchase Line" - UpdateDirectUnitCostByField

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#10353]
Can you change procedure UpdateDirectUnitCostByField to global?

**Comment by AlexanderYakunin** [comment]
You should use this function

    procedure UpdateDirectUnitCost(CalledByFieldNo: Integer)
    begin
        ClearFieldCausedPriceCalculation();
        PlanPriceCalcByField(CalledByFieldNo);
        UpdateDirectUnitCostByField(CalledByFieldNo);
    end;
