### ISSUE TITLE
Add New Key "Variant Code" in multiple Tables

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#1035]
Hi, 
we need the Key "Variant Code" in the following Tables:

37
39
83
90
111
113
115
121
123
125
169
210
246
281
337
1003
1013
5110
5406
5407
5700
6651
6661
99000772
99000829

**Comment by JesperSchulz** [comment]
Hi! May I ask why you need that particular key in all of these tables? Is it for performance reasons?

**Comment by LFlamme** [comment]
Hi,
its for performance, but also for sorting. We have a big extension, where we use the Variant Code a lot. Its our main link to the BC-Standard.
Therefor this is a big performance issue for us.

**Comment by AlexanderYakunin** [comment]
Why this is "Variant Code" only? I assume we there are different variant per each Item No.? Or you only filter by Item No. and sort by Variant Code?
