### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforeBalacount

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10350]
Hi, in the Codeunit 80 Sales Post, would it be possible to get an event OnBeforeBalacount, like this :
![image](https://user-images.githubusercontent.com/76154006/102902992-01abe300-4470-11eb-8fb2-0f88d5b140fe.png)
![image](https://user-images.githubusercontent.com/76154006/102903395-9282be80-4470-11eb-947a-1b4036d17656.png)
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
