### ISSUE TITLE
[Event Request] table 39 "Purchase Line" - OnCopyFromItemOnAfterCheck

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#10358]
Can you add CurrFieldNo as parameter in event OnCopyFromItemOnAfterCheck?

```
        // >>>>>>>>>>>>>>>>
        //OnCopyFromItemOnAfterCheck(Rec, Item);
        OnCopyFromItemOnAfterCheck(Rec, Item, CurrFieldNo);
        // <<<<<<<<<<<<<<<<
```

```
    [IntegrationEvent(false, false)]
    local procedure OnCopyFromItemOnAfterCheck(PurchaseLine: Record "Purchase Line"; Item: Record Item, CalledByFieldNo:Integer)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
