### ISSUE TITLE
[EventPropertyRequest] GenJnlPostLine.Codeunit.al codeunit 12 "Gen. Jnl.-Post Line" - OnAfterCheckCarteraPostDtldVendLE 

### ISSUE THREAD

**Issue by antoniomirandalopez** [microsoft/ALAppExtensions#10368]
How "Gen Journal Document Type" field can be extended to add new values. I request modify CheckCarteraPostDtldCustLE procedure to can add new options for enum "Gen. Journal Document Type"

New code

[local procedure CheckCarteraPostDtldVendLE(GenJnlLine2: Record "Gen. Journal Line"; DtldVendLedgEntry3: Record "Detailed Vendor Ledg. Entry"; PayableAccAmtLCY: Decimal; PayableAccAmtAddCurr: Decimal; CreateBills: Boolean): Boolean
    var
        IsOK: Boolean;
    begin
        IsOK := false;
        if ((GenJnlLine2."Applies-to Doc. Type" = GenJnlLine2."Applies-to Doc. Type"::Bill) or
            ((GenJnlLine2."Document Type" = GenJnlLine2."Document Type"::Payment) and
             (DtldVendLedgEntry3."Initial Document Type" = DtldVendLedgEntry3."Initial Document Type"::Bill) and
           (GenJnlLine2."Applies-to ID" <> ''))) and (not IDBillSettlement)
         then
            SetFromSettlement(true);

        with DtldVendLedgEntry3 do
            case "Entry Type" of
                "Entry Type"::Application:
                    if (not FromBillSettlement) and (not IDBillSettlement) then
                        if (("Document Type" <> "Document Type"::"Credit Memo") and (GenJnlLine2."Applies-to ID" <> '')) or
                           CreateBills
                        then begin
                            if "Initial Document Type" = "Initial Document Type"::Bill then
                                IsOK := true;
                        end;
                else begin
                        if VendLedgEntryInserted2 or (PayableAccAmtLCY <> 0) or (PayableAccAmtAddCurr <> 0)
                           and (AddCurrencyCode <> '')
                        then
                            if (not FromBillSettlement) or (PayableAccAmtLCY <> 0) or (PayableAccAmtAddCurr <> 0) then
                                IsOK := true;
                    end;
            end;

        Clear(VendLedgEntryInserted2);
        Clear(DtldVendLedgEntry3);
        Clear(GenJnlLine2);

        // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  NEW CODE
        OnAfterCheckCarteraPostDtldVendLE(IsOK, GenJnlLine2, DtldVendLedgEntry3);
        // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  END NEW CODE
        exit(IsOK);
    end;

    // ----- NEW CODE
    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckCarteraPostDtldVendLE(var IsOk: Boolean; GenJnlLine2: Record "Gen. Journal Line"; DtldVendLedgEntry3: Record "Detailed Vendor Ledg. Entry")
    begin
    end;
    // ----- END NEW CODE](url)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
