### ISSUE TITLE
[Event Reques] Codeunit 10750 SII XML Creator - OnBeforeContraparteNode

### ISSUE THREAD

**Issue by IsmaelRosadoP** [microsoft/ALAppExtensions#10362]
Can you add event OnBeforeContraparteNode?

            FillOperationDescription(
              XMLNode, GetOperationDescriptionFromDocument(true, CustLedgerEntry."Document No."),
              CustLedgerEntry."Posting Date", CustLedgerEntry.Description);
            FillRefExternaNode(XMLNode, Format(SIIDocUploadState."Entry No"));
            FillSucceededCompanyInfo(XMLNode, SIIDocUploadState);
            if AddNodeForTotals then
                FillMacrodatoNode(XMLNode, TotalAmount);
            >>>>>>>>>>>>>>>
            OnBeforeContraparteNode(XMLNode, CustLedgerEntry );
            <<<<<<<<<<<<<<<
            if IncludeContraparteNodeBySalesInvType(InvoiceType) then begin
                XMLDOMManagement.AddElementWithPrefix(XMLNode, 'Contraparte', '', 'sii', SiiTxt, XMLNode);
                FillThirdPartyId(
                  XMLNode, Customer."Country/Region Code", Customer.Name, Customer."VAT Registration No.", Customer."No.", true,
                  SIIManagement.CustomerIsIntraCommunity(Customer."No."), Customer."Not in AEAT", SIIDocUploadState.IDType);
            end;

            XMLDOMManagement.AddElementWithPrefix(XMLNode, 'TipoDesglose', '', 'sii', SiiTxt, XMLNode);
            if DomesticCustomer then
                GenerateNodeForServicesOrGoodsDomesticCustomer(
                  TempGoodsVATEntryCalcNonExempt, TempServVATEntryCalcNonExempt, XMLNode, DesgloseFacturaXMLNode, DomesticXMLNode,
                  DesgloseTipoOperacionXMLNode, EUServiceXMLNode, NonEUServiceXMLNode, ExemptionCausePresent, ExemptionBaseAmounts,
                  NonExemptTransactionType, ExemptExists, CustLedgerEntry, DomesticCustomer, RegimeCode)
            else
                GenerateNodeForServicesOrGoodsForeignCustomer(
                  TempGoodsVATEntryCalcNonExempt, TempServVATEntryCalcNonExempt, XMLNode, DesgloseFacturaXMLNode, DomesticXMLNode,
                  DesgloseTipoOperacionXMLNode, EUServiceXMLNode, NonEUServiceXMLNode, ExemptionCausePresent, ExemptionBaseAmounts,
                  NonExemptTransactionType, ExemptExists, CustLedgerEntry, DomesticCustomer, RegimeCode);
            exit(true);`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
