### ISSUE TITLE
[Event Request] Table 83 "Item Journal Line" - OnBeforeConfirmOutputOnFinishedOperation

### ISSUE THREAD

**Issue by jngillard** [microsoft/ALAppExtensions#10361]
I need an integration event where I can skip the ConfirmOutputOnFinishedOperation in Table 83.

See sample below.

local procedure ConfirmOutputOnFinishedOperation()
    var
        ProdOrderRtngLine: Record "Prod. Order Routing Line";
        SkipConfirm: Boolean
    begin
        if ("Entry Type" <> "Entry Type"::Output) or ("Output Quantity" = 0) then
            exit;

        if not ProdOrderRtngLine.Get(
             ProdOrderRtngLine.Status::Released, "Order No.", "Routing Reference No.", "Routing No.", "Operation No.")
        then
            exit;

        if ProdOrderRtngLine."Routing Status" <> ProdOrderRtngLine."Routing Status"::Finished then
            exit;
        OnBeforeConfirmOutputOnFinishedOperation(skipConfirm);
        IF SkipConfirm THEN EXIT;

        if not Confirm(FinishedOutputQst) then
            Error(UpdateInterruptedErr);
    end;

[IntegrationEvent(false, false)]
    local procedure OnBeforeConfirmOutputOnFinishedOperation(var skpConfirm: boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
