### ISSUE TITLE
[Feature Request] Report 10885 "Export G/L Entries - Tax Audit"

### ISSUE THREAD

**Issue by CDelille** [microsoft/ALAppExtensions#10363]
Hi,

In the report 10885 "Export G/L Entries - Tax Audit", the G/L entries are filtered by Amount <> 0, but the fiscal administration in France wants to see all the entries so that there is no missing numbers.

Could you please add an option in the report to export the entries where Amount = 0 ?

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request seems to be asking for a regulatory feature and not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
