### ISSUE TITLE
[EventPropertyRequest] GenJnlPostLine.Codeunit.al codeunit 12 "Gen. Jnl.-Post Line" - OnAfterCheckCarteraPostDtldCustLE

### ISSUE THREAD

**Issue by antoniomirandalopez** [microsoft/ALAppExtensions#10367]
How "Gen Journal Document Type" field can be extended to add new values. I request modify  CheckCarteraPostDtldCustLE procedure to can add new options for enum "Gen. Journal Document Type"

New  code:

local procedure CheckCarteraPostDtldCustLE(GenJnlLine2: Record "Gen. Journal Line"; DtldCustLedgEntry3: Record "Detailed Cust. Ledg. Entry"; ReceivableAccAmtLCY: Decimal; ReceivableAccAmtAddCurr: Decimal; CreateBills: Boolean): Boolean
    var
        IsOK: Boolean;
    begin
        IsOK := false;
        if ((GenJnlLine2."Applies-to Doc. Type" = GenJnlLine2."Applies-to Doc. Type"::Bill) or
            ((GenJnlLine2."Document Type" = GenJnlLine2."Document Type"::Payment) and
             (DtldCustLedgEntry3."Initial Document Type" = DtldCustLedgEntry3."Initial Document Type"::Bill) and
             (GenJnlLine2."Applies-to ID" <> ''))) and (not IDBillSettlement)
        then
            SetFromSettlement(true);

        with DtldCustLedgEntry3 do
            case "Entry Type" of
                "Entry Type"::"Initial Entry":
                    if "Initial Document Type" = "Initial Document Type"::Bill then
                        if "Document Type" = "Document Type"::Bill then
                            if BillFromJournal then
                                IsOK := true;
                "Entry Type"::Application:
                    if (not FromBillSettlement) and (not IDBillSettlement) then
                        if (("Document Type" <> "Document Type"::"Credit Memo") and (GenJnlLine2."Applies-to ID" <> '')) or
                           CreateBills
                        then begin
                            if "Initial Document Type" = "Initial Document Type"::Bill then
                                IsOK := true;
                            if "Initial Document Type" = "Initial Document Type"::Invoice then
                                if "Document Situation" = "Document Situation"::"Closed BG/PO" then
                                    if "Document Status" = "Document Status"::Rejected then
                                        IsOK := true;
                        end;
                else begin
                        if CustLedgEntryInserted2 or (ReceivableAccAmtLCY <> 0) or (ReceivableAccAmtAddCurr <> 0)
                           and (AddCurrencyCode <> '')
                        then
                            if (not FromBillSettlement) or (ReceivableAccAmtLCY < 0) or (ReceivableAccAmtAddCurr < 0) then
                                if not BillFromJournal then
                                    IsOK := true;
                    end;
            end;

        Clear(CustLedgEntryInserted2);
        Clear(DtldCustLedgEntry3);
        Clear(GenJnlLine2);
        // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  NEW CODE
        OnAfterCheckCarteraPostDtldCustLE(IsOK,GenJnlLine2,DtldCustLedgEntry3);
        // **>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> END NEW CODE
        exit(IsOK);
    end;

    // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> NEW EVENT 
    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckCarteraPostDtldCustLE(var IsOk: Boolean; GenJnlLine2: Record "Gen. Journal Line"; DtldCustLedgEntry3: Record "Detailed Cust. Ledg. Entry")
    begin
    end;
    // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> END NEW EVENT

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
