### ISSUE TITLE
[EventPropertyRequest] GenJnlPostLine.Codeunit.al (codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeIsNotPayment

### ISSUE THREAD

**Issue by antoniomirandalopez** [microsoft/ALAppExtensions#10366]
How "Gen Journal Document Type" field can be extended to add new values. I request modify  IsNotPayment procedure to can add new options for enum "Gen. Journal Document Type"

New  code:

   local procedure IsNotPayment(DocumentType: Enum "Gen. Journal Document Type"): Boolean
    var
        ReturnValue : Boolean;
    begin
        ReturnValue := DocumentType in [DocumentType::Invoice,
                              DocumentType::"Credit Memo",
                              DocumentType::"Finance Charge Memo",
                              DocumentType::Reminder];
        OnBeforeIsNotPayment(ReturnValue,DocumentType);
        exit(ReturnValue);                              
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsNotPayment(var IsNotPayment : Boolean; DocumentType: Enum "Gen. Journal Document Type")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
