### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforeSaleShipmentHeader

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10360]
Hi, in the Codeunit 80 Sales Post, would it be possible to get an event OnBeforeSaleShipmentHeader , like this :
![image](https://user-images.githubusercontent.com/76154006/103202114-d9016e80-48f1-11eb-95d7-f9e314ee2a34.png)

![image](https://user-images.githubusercontent.com/76154006/103206780-e7a15300-48fc-11eb-8c83-3711da6ad61f.png)

Thanks

**Comment by StanPesotskiy** [comment]
Please use the existing event OnBeforeGetCountryCode().
