### ISSUE TITLE
[ENUM Request] Table 1022 - Job Planning Line Invoice - Document Type

### ISSUE THREAD

**Issue by frivadulla** [microsoft/ALAppExtensions#1036]
Hello,

if its possible i would like the field "Document Type" in the 1022 table to be a Enumeration.

Kind regards.

**Comment by marpacca** [comment]
I would also like to be able to extend it by one extension

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
