### ISSUE TITLE
[Object Request] XmlDsigC14NTransform for OnCLoud Extension

### ISSUE THREAD

**Issue by yuranshrestha** [microsoft/ALAppExtensions#10369]
XmlC14NTransform: DotNet XmlDsigC14NTransform;
Is there object that we can use for XmlC14NTransform? How can we use XmlC14NTransform in AL? Any alternative method available so that we can do Canonicalisation of XML.

**Comment by JesperSchulz** [comment]
This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central. Please refer to other channels for general questions. You are welcome to submit .NET wrapper modules in this repository, if you are lacking functionality. For an introduction, please visit [aka.ms/NewALModule](http://aka.ms/NewALModule).
