### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforeSellToCountry

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10372]
Hi, in the Codeunit 80 Sales Post, would it be possible to get an event OnBeforeSellToCountry, like this :
![image](https://user-images.githubusercontent.com/76154006/103206907-4c5cad80-48fd-11eb-9942-ba534b77425e.png)

![image](https://user-images.githubusercontent.com/76154006/103207801-875fe080-48ff-11eb-8dcf-7440b1415aad.png)

Thanks

**Comment by StanPesotskiy** [comment]
Clarify the placement of required event - on the picture it is inserted between functions.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by Herodoteux** [comment]
It's locate on the local procedure GetCountryCode
![image](https://user-images.githubusercontent.com/76154006/103516140-47a17780-4e70-11eb-8821-a89fc6f1b7ed.png)
    local procedure GetCountryCode(SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header"): Code[10]
    var
        SalesShipmentHeader: Record "Sales Shipment Header";
        CountryRegionCode: Code[10];
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetCountryCode(SalesHeader, SalesLine, CountryRegionCode, IsHandled);
        if IsHandled then
            exit(CountryRegionCode);

        if SalesLine."Shipment No." <> '' then begin
            SalesShipmentHeader.Get(SalesLine."Shipment No.");
            IsHandled := false;
            OnBeforeSaleShipmentHeader(SalesHeader, SalesShipmentHeader, SalesLine, IsHandled);
            if not IsHandled then
                exit(
                  GetCountryRegionCode(
                    SalesLine."Sell-to Customer No.",
                    SalesShipmentHeader."Ship-to Code",
                    SalesShipmentHeader."Sell-to Country/Region Code"));
        end;
        IsHandled := false;
        OnAfterGetCountryCode(SalesHeader, SalesLine, IsHandled);
        if not IsHandled then
            exit(
              GetCountryRegionCode(
                SalesLine."Sell-to Customer No.",
                SalesHeader."Ship-to Code",
                SalesHeader."Sell-to Country/Region Code"));
    end;

    _OnBeforeSellToCountry(SalesHeader, SalesLine, SalesShipmentHeader);___

**Comment by StanPesotskiy** [comment]
The line 5589:  " end;" is the end of the function GetCountryCode. We cannot call an event outside of the function.
You also want to name it OnBeforeSellToCountry though the function called GetCountryCode. What is the point?

**Comment by Herodoteux** [comment]
Yes sorry my mistake the event need to be in the procedure GetCountryCode mutch like this :
![image](https://user-images.githubusercontent.com/76154006/104931450-b6212200-59a6-11eb-85a2-0198217d2862.png)
![image](https://user-images.githubusercontent.com/76154006/104931473-be795d00-59a6-11eb-98ef-b5e1ea8a6f9c.png)
Sorry it's because in navision there is not begin end in procedure

**Comment by StanPesotskiy** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by StanPesotskiy** [comment]
The latest source code differs from code you described. You can use existent event OnBeforeGetCountryCode to overwrite the logic.
