### ISSUE TITLE
[request-for-external] Scope of CreateIRMark function in HMRCSubmissionHelpers is OnPrem

### ISSUE THREAD

**Issue by yuranshrestha** [microsoft/ALAppExtensions#10371]
in HMRCSubmissionHelpers codeunit, function "CreateIRMark" is marked as OnPrem. We want to use this function for HMRC related development. We know there is MTD (Making Tax Digital) extension but that extension does not have this function available. This functions creates IRMark and returns it as text.

**Comment by yuranshrestha** [comment]
Just following up, if this function could be used by extension in coming minor release.

**Comment by AlexanderYakunin** [comment]
This function contains dotnet parameters and extensions do not support use of such functions. Even if we will remove OnPrem it will not work in your extension. You need to find another option for your solution. 

procedure CreateIRMark(XMLDocument: DotNet XmlDocument; GovTalkNameSpace: Text; TaxNameSpace: Text): Text
