### ISSUE TITLE
Table1003 "Job Planning Line" make function "InitRoundingPrecisions" global

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#10373]
Can you make the function "InitRoundingPrecisions" global in table "Job Planning Line" (Table 1003) 

![image](https://user-images.githubusercontent.com/28901234/103207090-55e21780-48f5-11eb-90a4-184aedde10ba.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
