### ISSUE TITLE
Add new Key "Dimension Set ID" in multiple Tables

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#1037]
Hi,

we need a new Key "Dimension Set ID" in The following Tables:

32
36
5406

we also need this Key: "Document Type","Dimension Set ID"
in the following 2 Tables:

37
39

**Comment by AlexanderYakunin** [comment]
Can you please explain how you would like to use this key? We want to do this consistently, for example you want it in TAB36 but don;t mention TAB38 or TAB5900. Sames for TAB37 and TAB5902.

**Comment by LFlamme** [comment]
Hi, sry for the late reply. 

We have attributes on artikles, wich are used in the Dimensions. 
We use the keys in a page, where we can enter a Dimensionscode and value. Then we get information about where the attribute is used. we use those keys when filtering the records.
