### ISSUE TITLE
Table 1003 Job Planning Line, New Event Request in function RecalculateAmounts

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#10375]
Requesting a new integration event in Table 1003 (Job Planning Line), inside function RecalculateAmounts:

![image](https://user-images.githubusercontent.com/28901234/103217539-b92d7300-4910-11eb-9f34-f6d79bfa303a.png)

**LOCAL [IntegrationEvent] OnBeforeRecalculateAmounts(VAR JobPlanningLine : Record "Job Planning Line";VAR xJobPlanningLine : Record "Job Planning Line")**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
