### ISSUE TITLE
[Access Request] Page 474 - "VAT Statement Preview" – Global Variables Access

### ISSUE THREAD

**Issue by iyiannak** [microsoft/ALAppExtensions#10377]
Could you please change the accessibility of the global variables from default to protected.

page 474 "VAT Statement Preview"
{
   …
    var
        Selection: Option Open,Closed,"Open and Closed";
        PeriodSelection: Option "Before and Within Period","Within Period";
        UseAmtsInAddCurr: Boolean;
        DateFilter: Text[30];
   …
}

**Comment by AlexanderYakunin** [comment]
Already done

    protected var
        Selection: Enum "VAT Statement Report Selection";
        PeriodSelection: Enum "VAT Statement Report Period Selection";
        UseAmtsInAddCurr: Boolean;
        DateFilter: Text[30];
