### ISSUE TITLE
[Event Request] CU99000834 Purch. Line Reserve

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#10376]
Hello,
can we please add

`
[IntegrationEvent(false, false)]
    local procedure OnTransferToPurchLineOnBeforeCheckEntries(var OldPurchLine: record "Purchase Line"; var NewPurchLine: Record "Purchase Line")
    begin
    end;

procedure TransferPurchLineToPurchLine(var OldPurchLine: Record "Purchase Line"; var NewPurchLine: Record "Purchase Line"; TransferQty: Decimal)
    var
        OldReservEntry: Record "Reservation Entry";
        ReservStatus: Enum "Reservation Status";
    begin
        if not FindReservEntry(OldPurchLine, OldReservEntry) then
            exit;

        OldReservEntry.Lock;

        NewPurchLine.TestItemFields(OldPurchLine."No.", OldPurchLine."Variant Code", OldPurchLine."Location Code");

        for ReservStatus := ReservStatus::Reservation to ReservStatus::Prospect do begin
            if TransferQty = 0 then
                exit;
            OldReservEntry.SetRange("Reservation Status", ReservStatus);
            // --add
            OnTransferToPurchLineOnBeforeCheckEntries(OldPurchLine, NewPurchLine);
            // -- add
            if OldReservEntry.FindSet then
`

This will allow to perform some custom validation before transfer.

Thanks,
Bartek

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
