### ISSUE TITLE
[Event Request] Page 475 - "VAT Statement Preview Line" – OnBeforeOpenPageAccountTotaling

### ISSUE THREAD

**Issue by iyiannak** [microsoft/ALAppExtensions#10378]
Could you please add a new publisher on trigger OnDrillDown of field ColumnValue, Page 475 - "VAT Statement Preview Line", in order to set additional filters to G/L Entry.

field(ColumnValue; ColumnValue)
{
  …
  trigger OnDrillDown()
  begin
    case Type of
        Type::"Account Totaling":
            begin
                GLEntry.SetFilter("G/L Account No.", "Account Totaling");
                CopyFilter("Date Filter", GLEntry."Posting Date");
                >>>>>>>>>> NEW CODE >>>>>>>>
                OnBeforeOpenPageAccountTotaling(GLEntry, Rec);
                <<<<<<<<<< NEW CODE <<<<<<<<
                PAGE.Run(PAGE::"General Ledger Entries", GLEntry);
            end;
        Type::"VAT Entry Totaling":
  …
}

[IntegrationEvent(true, false)]
local procedure OnBeforeOpenPageAccountTotaling(var GLEntry: Record " G/L Entry"; var VATStatementLine: Record "VAT Statement Line")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
