### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnAfterGetCountryCode

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10370]
Hi, in the Codeunit 80 Sales Post, would it be possible to get an event OnAfterGetCountryCode, like this :
![image](https://user-images.githubusercontent.com/76154006/103205412-ca1eba00-48f9-11eb-9d32-bbb1d71507f4.png)
![image](https://user-images.githubusercontent.com/76154006/103206708-c8a2c100-48fc-11eb-8fc8-b4042fa585df.png)

Thanks

**Comment by StanPesotskiy** [comment]
Please use the existing event OnBeforeGetCountryCode().
