### ISSUE TITLE
[EventParameter] New parameter required in events OnBeforeAutoReserveXXX from codeunit Reservation Management

### ISSUE THREAD

**Issue by TriangleSPV** [microsoft/ALAppExtensions#10383]
Related to my other issue
https://github.com/microsoft/ALAppExtensions/issues/10255

We require the parameter CalcReservEntry, as it exists in event OnBeforeAutoReserveItemLedgEntry, of all the following events of codeunit 99000845 "Reservation Management":

OnBeforeAutoReservePurchLine
OnBeforeAutoReserveSalesLine
OnBeforeAutoReserveProdOrderLine
OnBeforeAutoReserveProdOrderComp
OnBeforeAutoReserveAssemblyHeader
OnBeforeAutoReserveAssemblyLine
OnBeforeAutoReserveTransLine
OnBeforeAutoReserveServLine
OnBeforeAutoReserveJobPlanningLine

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
