### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforePostInvoicePostBufferLineGenJnlLine

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10388]
Hi, in the Codeunit 80 Sales Post, would it be possible to get an event OnBeforePostInvoicePostBufferLineGenJnlLine, like this :
![image](https://user-images.githubusercontent.com/76154006/103280212-205e2c80-49d0-11eb-8972-114821acdd6e.png)
![image](https://user-images.githubusercontent.com/76154006/103280446-b98d4300-49d0-11eb-8d50-36c8c1e46c80.png)
Thanks

**Comment by StanPesotskiy** [comment]
Can you use the existing event OnBeforePostInvPostBuffer?

**Comment by Herodoteux** [comment]
I can't use the event OnBeforePostInvPostBuffer because I need to modify GenJnlLine values before enter in the if .
Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
