### ISSUE TITLE
[EventRequest] Codeunit 1012 Job Jnl.-Post Line - OnBeforeGetJobConsumptionValueEntry

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#10395]
Requesting a new event publisher on Codeunit 1012 Job Jnl.-Post Line

Event
`OnBeforeGetJobConsumptionValueEntry(JobJournalLine : Record "Job Journal Line"; VAR IsHandled : Boolean)`

**Code**
## LOCAL GetJobConsumptionValueEntry(VAR ValueEntry : Record "Value Entry";JobJournalLine : Record "Job Journal Line") : Boolean
**>>> New Code**
```
IsHandled := FALSE;
OnBeforeGetJobConsumptionValueEntry(JobJournalLine, IsHandled);
IF IsHandled THEN
  EXIT(TRUE);
```
**<<< New Code End**
```
WITH JobJournalLine DO BEGIN
  ValueEntry.SETCURRENTKEY("Job No.","Job Task No.","Document No.");
  ValueEntry.SETRANGE("Item No.","No.");
  ValueEntry.SETRANGE("Job No.","Job No.");
  ValueEntry.SETRANGE("Job Task No.","Job Task No.");
  ValueEntry.SETRANGE("Document No.","Document No.");
  ValueEntry.SETRANGE("Item Ledger Entry Type",ValueEntry."Item Ledger Entry Type"::"Negative Adjmt.");
  ValueEntry.SETRANGE("Job Ledger Entry No.",0);
  OnGetJobConsumptionValueEntryFilter(ValueEntry,JobJnlLine);
END;

EXIT(ValueEntry.FINDSET);
```

In Our Solution we have a link between Jobs and Production Orders. When posting Subcontracting we want to create a Job Ledger Entry, but there is no Value Entry to link the Job Ledger Entry to.
With this publisher we have that flexibility. Can you please add this publisher here?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
