### ISSUE TITLE
[Access Request] codeunit 6501 "Item Tracking Data Collection" RetreiveTempGlobalEntrySummary

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#10398]
Is it possible to get a procedure in codeunit 6501 "Item Tracking Data Collection" to retrieve TempGlobalEntrySummary after calling procedure RetrieveLookupData? Or a new procedure also called RetrieveLookupData with an extra parameter?

Example of usage:
```
ItemTrackingDataCollection.RetrieveLookupData(TrackingSpecification, true);
ItemTrackingDataCollection.GetTempGlobalEntrySummary(TempGlobalEntrySummary);
```

New procedure ex 1:
```
procedure GetTempGlobalEntrySummary(var TempGlobalEntrySummary2: Record "Entry Summary" temporary)
begin
    TempGlobalEntrySummary2.Copy(TempGlobalEntrySummary, true);
end;
```

New procedure ex 2:
```
procedure RetrieveLookupData(var TempGlobalEntrySummary2: Record "Entry Summary" temporary; var TempTrackingSpecification: Record "Tracking Specification" temporary; FullDataSet: Boolean)
begin
    RetrieveLookupData(TempTrackingSpecification, FullDataSet);
    TempGlobalEntrySummary2.Copy(TempGlobalEntrySummary, true);
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
