### ISSUE TITLE
[Event Request] CU 99000835 Item Jnl. Line-Reserve TransferItemJnlToItemLedgEntry

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#10402]
Hello, can we please add in this function:
`
    [IntegrationEvent(false, false)]
    local procedure OnTransferItemJnlToItemLedgEntryOnBeforeTestFields(ItemLedgEntry: Record "Item Ledger Entry"; ItemJnlLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnTransferItemJnlToItemLedgEntryOnBeforeTestOldReservEntryFields(OldReservEntry: record "Reservation Entry"; var ItemJnlLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;

// changed >>
OnTransferItemJnlToItemLedgEntryOnBeforeTestFields(ItemLedgEntry, ItemJnlLine, IsHandled);
        if not IsHandled then begin
            ItemLedgEntry.TestField("Item No.", ItemJnlLine."Item No.");
            ItemLedgEntry.TestField("Variant Code", ItemJnlLine."Variant Code");
            if ItemJnlLine."Entry Type" = ItemJnlLine."Entry Type"::Transfer then
                ItemLedgEntry.TestField("Location Code", ItemJnlLine."New Location Code")
            else
                ItemLedgEntry.TestField("Location Code", ItemJnlLine."Location Code");
        end;
        IsHandled := false;

                    // changed >>
                    IsHandled := false;
                    if not SkipThisRecord then begin
                        if ItemJnlLine."Entry Type" = ItemJnlLine."Entry Type"::Transfer then begin
                            if ItemLedgEntry.Quantity < 0 then
                                TestLocation := true;
                            CreateReservEntry.SetInbound(true);
                        end else
                            TestLocation := true;

                        OnTransferItemJnlToItemLedgEntryOnBeforeTestOldReservEntryFields(OldReservEntry, ItemJnlLine, IsHandled);
                        if (not IsHandled) and TestLocation then
                            OldReservEntry.TestField("Location Code", ItemJnlLine."Location Code");
                        // changed <<
                        TransferQty :=
                          CreateReservEntry.TransferReservEntry(
                            DATABASE::"Item Ledger Entry", 0, '', '', 0,
                            ItemLedgEntry."Entry No.", ItemLedgEntry."Qty. per Unit of Measure",
                            OldReservEntry, TransferQty);
                    end else
`

This will allow to perform custom validations during transfer.

Thanks,
Bartek

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
