### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforeInsertCrMemoHeader

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#10400]
Hi, would it be possible to get an event OnBeforeInsertCrMemoHeader in codeunit 80 Sales Post, in trigger OnRun, like this :
![image](https://user-images.githubusercontent.com/76153139/103355196-f7ac6480-4aad-11eb-8d77-61545d745bf1.png)
![image](https://user-images.githubusercontent.com/76153139/103355324-40fcb400-4aae-11eb-939f-5cbd4e36752a.png)
Thanks!

**Comment by StanPesotskiy** [comment]
Can you use the existing event OnBeforeSalesCrMemoHeaderInsert?

**Comment by Pepito-lab** [comment]
Hi, we need this event, it doesn't work with OnBeforeSalesCrMemoHeaderInsert.
Thanks

**Comment by StanPesotskiy** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
