### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforeLastLineRetrieved

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10401]
Hi, would it be possible to get an event OnBeforeLastLineRetrieved in Codeunit 80 Sales Post OnRun, like this : 
`        SalesLinesProcessed := false;
        if TempSalesLineGlobal.FindSet() then
            repeat
                ErrorMessageMgt.PushContext(ErrorContextElementPostLine, TempSalesLineGlobal.RecordId, 0, PostDocumentLinesMsg);
                ItemJnlRollRndg := false;
                LineCount := LineCount + 1;
                if not HideProgressWindow then
                    Window.Update(2, LineCount);

                PostSalesLine(
                  SalesHeader, TempSalesLineGlobal, EverythingInvoiced, TempInvoicePostBuffer, TempVATAmountLine, TempVATAmountLineRemainder,
                  TempItemLedgEntryNotInvoiced, HasATOShippedNotInvoiced, TempDropShptPostBuffer, ICGenJnlLineNo,
                  TempServiceItem2, TempServiceItemComp2);

                if RoundingLineInserted then
                    LastLineRetrieved := true
                else begin
                    BiggestLineNo := MAX(BiggestLineNo, TempSalesLineGlobal."Line No.");
                    LastLineRetrieved := TempSalesLineGlobal.Next() = 0;
                    if LastLineRetrieved and SalesSetup."Invoice Rounding" then
                        InvoiceRounding(SalesHeader, TempSalesLineGlobal, false, BiggestLineNo);
                end;
                **OnBeforeLastLineRetrieved(SalesHeader, TempSalesLineGlobal, SalesInvHeader, SalesCrMemoHeader);**
            until LastLineRetrieved;`

`    [IntegrationEvent(false, false)]
    local procedure OnBeforeLastLineRetrieved(var SalesHeader: Record "Sales Header"; TempSalesLineGlobal: Record "Sales Line"; SalesInvHeader: Record "Sales Inv. Header"; SalesCrMemoHeader: Record "Sales Cr. Memo Header")
    begin
    end;`

?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
