### ISSUE TITLE
[Event Modification] Codeunit 12 Gen. Jnl.-Post Line - OnBeforeInitGLEntry()

### ISSUE THREAD

**Issue by dsgobba** [microsoft/ALAppExtensions#10403]
Hi AL Team,

Could you update the event OnBeforeInitGLEntry:

**Actual**
OnBeforeInitGLEntry(GenJnlLine, GLAccNo, SystemCreatedEntry);

**New**
OnBeforeInitGLEntry(GenJnlLine, GLAccNo, SystemCreatedEntry, Amount, AmountAddCurr);

**Reason**
We want move the value in AmountAddCurr in a new extended field on GLEntry before the system loses this information.
AmountAddCurr contains value regardless the status of Additional Currency in General Ledger Setup.

Our goal is to manage original currency amount in GLEntry.

Thanks in Advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
