### ISSUE TITLE
[Event Request] CU 99000838 Prod. Order Comp.-Reserve

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#10405]
Hello,
can we please add
`
    [IntegrationEvent(false,false)]
    local procedure OnBeforeTransferPOCompToItemJnlLineCheckILE(var ProdOrderComp: Record "Prod. Order Component"; var ItemJnlLine: record "Item Journal Line")
    begin
    end;

procedure TransferPOCompToItemJnlLineCheckILE(var OldProdOrderComp: Record "Prod. Order Component"; var NewItemJnlLine: Record "Item Journal Line"; TransferQty: Decimal; CheckApplFromItemEntry: Boolean)
    var
        OldReservEntry: Record "Reservation Entry";
        OppositeReservationEntry: Record "Reservation Entry";
        ItemTrackingSetup: Record "Item Tracking Setup";
        ItemTrackingFilterIsSet: Boolean;
        EndLoop: Boolean;
        TrackedQty: Decimal;
        UnTrackedQty: Decimal;
        xTransferQty: Decimal;
    begin
        if not FindReservEntry(OldProdOrderComp, OldReservEntry) then
            exit;

        if CheckApplFromItemEntry then
            if OppositeReservationEntry.Get(OldReservEntry."Entry No.", not OldReservEntry.Positive) then
                if OppositeReservationEntry."Source Type" <> DATABASE::"Item Ledger Entry" then
                    exit;

        // added
        OnBeforeTransferPOCompToItemJnlLineCheckILE(OldProdOrderComp, NewItemJnlLine);
`

For custom validation.
Thanks,
Bartek

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
