### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function UpdateUnitCost - OnUpdateUnitCostOnBeforeUpdateLastDirectCost

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10409]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: UpdateUnitCost
Publisher Event: OnUpdateUnitCostOnBeforeUpdateLastDirectCost
Reason: To implement custom business logic
Where is the event placed:
if "Drop Shipment" then begin
                    if LastDirectCost <> 0 then begin
                        Item."Last Direct Cost" := LastDirectCost;
                        OnUpdateUnitCostOnBeforeUpdateLastDirectCost(ValueEntry, Item, LastDirectCost);
                        Item.Modify();
                        ItemCostMgt.SetProperties(false, "Invoiced Quantity");
                        ItemCostMgt.FindUpdateUnitCostSKU(Item, "Location Code", "Variant Code", true, LastDirectCost);
                    end;
                end else begin
                    ItemCostMgt.SetProperties(false, "Invoiced Quantity");
                    ItemCostMgt.UpdateUnitCost(Item, "Location Code", "Variant Code", LastDirectCost, 0, true, true, false, 0);
                end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnUpdateUnitCostOnBeforeUpdateLastDirectCost(var ValueEntry: Record "Value Entry"; var Item: Record Item; LastDirectCost: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
