### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function InsertValueEntry - OnAfterInsertValueEntryRelation

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10408]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: InsertValueEntry
Publisher Event: OnAfterInsertValueEntryRelation
Reason: To implement custom business logic
Where is the event placed:
InsertItemReg(0, 0, ValueEntry."Entry No.", 0);
            InsertPostValueEntryToGL(ValueEntry);
            if Item."Item Tracking Code" <> '' then begin
                TempValueEntryRelation.Init();
                TempValueEntryRelation."Value Entry No." := ValueEntry."Entry No.";
                TempValueEntryRelation.Insert();
            end;
            OnAfterInsertValueEntryRelation(ValueEntry, ItemJnlLine, TempValueEntryRelation);
        end;
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterInsertValueEntryRelation(var ValueEntry: Record "Value Entry"; ItemJnlLine: Record "Item Journal Line"; TempValueEntryRelation: Record "Value Entry Relation" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
