### ISSUE TITLE
[Enum Request] Chart Type

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#10406]
Can you please provide an enum '(Business) Chart Type'?

![image](https://user-images.githubusercontent.com/25268332/103482186-b08cdf00-4ddf-11eb-8eb9-b1a4aedc6806.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
