### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function UndoQuantityPosting - OnUndoQuantityPostingBeforeInsertApplEntry

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10416]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: UndoQuantityPosting
Publisher Event: OnUndoQuantityPostingBeforeInsertApplEntry
Reason: To implement custom business logic
Where is the event placed:
NewItemLedgEntry.Modify();
        UpdateAdjmtProperties(NewValueEntry, NewItemLedgEntry."Posting Date");
        OnUndoQuantityPostingBeforeInsertApplEntry(OldItemLedgEntry, OldItemLedgEntry);
        if NewItemLedgEntry.Positive then begin
            UpdateOrigAppliedFromEntry(OldItemLedgEntry."Entry No.");
            InsertApplEntry(
              NewItemLedgEntry."Entry No.", NewItemLedgEntry."Entry No.",
              OldItemLedgEntry."Entry No.", 0, NewItemLedgEntry."Posting Date",
              -OldItemLedgEntry.Quantity, false);
        end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnUndoQuantityPostingBeforeInsertApplEntry(GlobalItemLedgerEntry: Record "Item Ledger Entry"; OldItemLedgerEntry: Record "Item Ledger Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
