### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function ApplyItemLedgEntry - OnApplyItemLedgEntryBeforeInsertApplEntry

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10413]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: ApplyItemLedgEntry
Publisher Event: OnApplyItemLedgEntryBeforeInsertApplEntry
Reason: To implement custom business logic
Where is the event placed:
OldItemLedgEntry."Remaining Quantity" := OldItemLedgEntry."Remaining Quantity" + AppliedQty;
                OldItemLedgEntry.Open := OldItemLedgEntry."Remaining Quantity" <> 0;
                OnApplyItemLedgEntryBeforeInsertApplEntry(OldItemLedgEntry, ItemLedgEntry, GlobalItemLedgEntry, AppliedQty);
                if ItemLedgEntry.Positive then begin
                    if ItemLedgEntry."Posting Date" >= OldItemLedgEntry."Posting Date" then
                        InsertApplEntry(
                          OldItemLedgEntry."Entry No.", ItemLedgEntry."Entry No.",
                          OldItemLedgEntry."Entry No.", 0, ItemLedgEntry."Posting Date", -AppliedQty, false)
                    else
                        InsertApplEntry(
                          OldItemLedgEntry."Entry No.", ItemLedgEntry."Entry No.",
                          OldItemLedgEntry."Entry No.", 0, OldItemLedgEntry."Posting Date", -AppliedQty, false);
Event Code:
  [IntegrationEvent(false, false)]
    local procedure OnApplyItemLedgEntryBeforeInsertApplEntry(var OldItemLedgerEntry: Record "Item Ledger Entry"; var ItemLedgerEntry: Record "Item Ledger Entry"; GlobalItemLedgerEntry: Record "Item Ledger Entry"; AppliedQty: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
