### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function CostApply - OnCostApplyBeforeInsertApplEntry

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10412]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: CostApply
Publisher Event: OnCostApplyBeforeInsertApplEntry
Reason: To implement custom business logic
Where is the event placed:
if not ItemApplnEntry.CheckIsCyclicalLoop(ApplyWithItemLedgEntry, GlobalItemLedgEntry) then begin
            CreateItemJnlLineFromEntry(GlobalItemLedgEntry, GlobalItemLedgEntry.Quantity, ItemJnlLine);
            OnCostApplyBeforeInsertApplEntry(GlobalItemLedgEntry, ApplyWithItemLedgEntry."Entry No.");
            InsertApplEntry(
              GlobalItemLedgEntry."Entry No.", GlobalItemLedgEntry."Entry No.",
              ApplyWithItemLedgEntry."Entry No.", 0, GlobalItemLedgEntry."Posting Date",
              GlobalItemLedgEntry.Quantity, true);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCostApplyBeforeInsertApplEntry(GlobalItemLedgerEntry: Record "Item Ledger Entry"; AppliesFromEntryNo: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
