### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function SetupSplitJnlLine - OnAfterSetupTempSplitItemJnlLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10417]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: SetupSplitJnlLine
Publisher Event: OnAfterSetupTempSplitItemJnlLine
Reason: To implement custom business logic
Where is the event placed:
until TempTrackingSpecification.Next = 0;
            end;
        end else
            InsertTempSplitItemJnlLine(ItemJnlLine2);
        OnAfterSetupTempSplitItemJnlLine(ItemJnlLine2, TempSplitItemJnlLine, ItemJnlLineOrigin, TempTrackingSpecification, TrackingSpecExists, CalledFromAdjustment, PostponeReservationHandling, PostItemJnlLine);
        exit(PostItemJnlLine);
Event Code:
 [IntegrationEvent(false, false)]
    local procedure OnAfterSetupSplitJnlLine(var ItemJnlLine2: Record "Item Journal Line"; var TempSplitItemJnlLine: Record "Item Journal Line" temporary; var ItemJnlLineOrigin: Record "Item Journal Line"; var TempTrackingSpecification: Record "Tracking Specification" temporary; TrackingSpecExists: Boolean; CalledFromAdjustment: Boolean; PostponeReservationHandling: Boolean; var PostItemJnlLine: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
