### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function ApplyItemLedgEntry - OnApplyItemLedgEntryBeforeReserve

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10418]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: ApplyItemLedgEntry
Publisher Event: OnApplyItemLedgEntryBeforeReserve
Reason: To implement custom business logic
Where is the event placed:
if not CausedByTransfer and not PostponeReservationHandling then begin
                if Item."Costing Method" = Item."Costing Method"::Specific then
                    ItemJnlLine.TestField("Serial No.");
                Handled := false;
                OnApplyItemLedgEntryBeforeReserve(ItemJnlLine, StartApplication, FirstReservation, Handled);
                if not Handled then begin
                    if FirstReservation then begin
                        FirstReservation := false;
                        ReservEntry.Reset();
                        ReservEntry.SetCurrentKey(
                          "Source ID", "Source Ref. No.", "Source Type", "Source Subtype",
                          "Source Batch Name", "Source Prod. Order Line", "Reservation Status");
                        ReservEntry.SetRange("Reservation Status", ReservEntry."Reservation Status"::Reservation);
                        ReserveItemJnlLine.FilterReservFor(ReservEntry, ItemJnlLine);
                    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnApplyItemLedgEntryBeforeReserve(var ItemJournalLine: Record "Item Journal Line"; var StartApplication: Boolean; FirstReservation: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
