### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function InsertTransferEntry - OnInsertTransferEntryBeforeInsertApplEntry

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10415]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: InsertTransferEntry
Publisher Event: OnInsertTransferEntryBeforeInsertApplEntry
Reason: To implement custom business logic
Where is the event placed:
InitTransValueEntry(NewValueEntry, NewItemLedgEntry);
            OnInsertTransferEntryBeforeInsertApplEntry(NewItemLedgEntry, ItemLedgEntry."Entry No.");
            if AverageTransfer then begin
                InsertApplEntry(
                  NewItemLedgEntry."Entry No.", NewItemLedgEntry."Entry No.", ItemLedgEntry."Entry No.",
                  0, NewItemLedgEntry."Posting Date", NewItemLedgEntry.Quantity, true);
                NewItemLedgEntry."Completely Invoiced" := ItemLedgEntry."Completely Invoiced";
            end else begin
                InsertApplEntry(
                  NewItemLedgEntry."Entry No.", NewItemLedgEntry."Entry No.", ItemLedgEntry."Entry No.",
                  OldItemLedgEntry."Entry No.", NewItemLedgEntry."Posting Date", NewItemLedgEntry.Quantity, true);
                NewItemLedgEntry."Completely Invoiced" := OldItemLedgEntry."Completely Invoiced";
            end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnInsertTransferEntryBeforeInsertApplEntry(GlobalItemLedgerEntry: Record "Item Ledger Entry"; AppliesFromEntryNo: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
