### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function UnApply - OnUnApplyBeforeInsertApplEntry

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10411]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: UnApply
Publisher Event: OnUnApplyBeforeInsertApplEntry
Reason: To implement custom business logic
Where is the event placed:
// If cost application we need to insert a 0 application instead if there is none before
            OnUnApplyBeforeInsertApplEntry(ItemApplnEntry);
            if ItemApplnEntry.Quantity > 0 then
                if not ZeroApplication(ItemApplnEntry."Item Ledger Entry No.") then
                    InsertApplEntry(
                      ItemApplnEntry."Item Ledger Entry No.", ItemApplnEntry."Inbound Item Entry No.",
                      0, 0, ItemApplnEntry."Posting Date", ItemApplnEntry.Quantity, true);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnUnApplyBeforeInsertApplEntry(ItemApplnEntry: Record "Item Application Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
