### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function InsertPhysInventoryEntry - OnBeforeInsertPhysInventoryEntry

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10419]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: InsertPhysInventoryEntry
Publisher Event: OnBeforeInsertPhysInventoryEntry
Reason: To implement custom business logic
Where is the event placed:
var
        PhysInvtLedgEntry: Record "Phys. Inventory Ledger Entry";
        IsHandled: Boolean;
    begin
        OnBeforeInsertPhysInventoryEntry(ItemJnlLineOrigin, IsHandled);
        if IsHandled then
            exit;
        with ItemJnlLineOrigin do begin
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeInsertPhysInventoryEntry(var ItemJnlLineOrigin: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
