### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function ItemQtyPosting - OnItemQtyPostingBeforeInsertApplEntry

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10410]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: ItemQtyPosting
Publisher Event: OnItemQtyPostingBeforeInsertApplEntry
Reason: To implement custom business logic
Where is the event placed:
if (not "Phys. Inventory") or (Quantity <> 0) then begin
                InsertItemLedgEntry(GlobalItemLedgEntry, false);
                OnItemQtyPostingBeforeInsertApplEntry(GlobalItemLedgEntry, "Applies-from Entry");
                if GlobalItemLedgEntry.Positive then
                    InsertApplEntry(
                      GlobalItemLedgEntry."Entry No.", GlobalItemLedgEntry."Entry No.",
                      "Applies-from Entry", 0, GlobalItemLedgEntry."Posting Date",
                      GlobalItemLedgEntry.Quantity, true);
            end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnItemQtyPostingBeforeInsertApplEntry(GlobalItemLedgerEntry: Record "Item Ledger Entry"; AppliesFromEntryNo: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
