### ISSUE TITLE
New Key in Table 32

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#1042]
Hi,

we need a new Key in Table 32.
The Key should be:  "Variant Code",Open

**Comment by AlexanderYakunin** [comment]
We cannot add this key as Variant Code is related to Item No. and should be used together.

**Comment by LFlamme** [comment]
Hi,
if I get you right you mean we could get the key "Variant Code",Open,"Item No." ?
We could work with that aswell
