### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function Code - OnCodeBeforeCheckItemTracking

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10424]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: Code
Publisher Event: OnCodeBeforeCheckItemTracking
Reason: To implement custom business logic
Where is the event placed:
OnCheckPostingCostToGL(PostToGL);
            IsHandled := false;
            OnCodeBeforeCheckItemTracking(ItemJnlLine, DisableItemTracking, IsHandled);
            if not IsHandled then
                if ItemTrackingSetup.TrackingRequired() and ("Quantity (Base)" <> 0) and
                   ("Value Entry Type" = "Value Entry Type"::"Direct Cost") and
                   not DisableItemTracking and not Adjustment and
                   not Subcontracting and not IsAssemblyResourceConsumpLine
                then
                    CheckItemTracking();
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCodeBeforeCheckItemTracking(var ItemJnlLine: Record "Item Journal Line"; DisableItemTracking: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
