### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function PostConsumption - OnPostConsumptionBeforeLoop

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10421]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: PostConsumption
Publisher Event: OnPostConsumptionBeforeLoop
Reason: To implement custom business logic
Where is the event placed:
repeat
                    IsHandled := false;
                    OnPostConsumptionBeforeLoop(ProdOrderComp, ItemJnlLine, TempHandlingSpecification, RemQtyToPost, UseItemTrackingApplication, LastLoop, IsHandled);
                    if not IsHandled then
                        if UseItemTrackingApplication then begin
                            TempHandlingSpecification.SetRange("Source Ref. No.", "Line No.");
                            if LastLoop then begin
                                RemQtyToPostThisLine := "Remaining Qty. (Base)";
                                if TempHandlingSpecification.FindSet() then
                                    repeat
Event Code:
 [IntegrationEvent(false, false)]
    local procedure OnPostConsumptionBeforeLoop(var ProdOrderComp: Record "Prod. Order Component"; var ItemJnlLine: Record "Item Journal Line"; var TempHandlingSpecification: Record "Tracking Specification" temporary; RemQtyToPost: Decimal; UseItemTrackingApplication: Boolean; LastLoop: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
