### ISSUE TITLE
[Event Change] Codeunit::"Item Jnl.-Post Line" - Function ApplyItemLedgEntry - OnBeforeApplyItemLedgEntry

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10425]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: ApplyItemLedgEntry
Publisher Event: OnBeforeApplyItemLedgEntry
Reason: add an extra Parameter
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeApplyItemLedgEntry(var ItemLedgEntry: Record "Item Ledger Entry"; var OldItemLedgEntry: Record "Item Ledger Entry"; var ValueEntry: Record "Value Entry"; CausedByTransfer: Boolean; ItemJournalLi

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
