### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function PostConsumption - OnPostConsumptionBeforeRndRemQty

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10422]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: PostConsumption
Publisher Event: OnPostConsumptionBeforeRndRemQty
Reason: To implement custom business logic
Where is the event placed:
end else begin
                        if ("Remaining Qty. (Base)" * "Expected Qty. (Base)") >= 0 then
                            QtyToPost := "Remaining Qty. (Base)" - NewRemainingQty
                        else
                            QtyToPost := NewRemainingQty;
                        "Remaining Qty. (Base)" := NewRemainingQty;
                    end;
                    IsHandled := FALSE;
                    OnPostConsumptionBeforeRndRemQty(ProdOrderComp, ItemJnlLine, NewRemainingQty, QtyToPost, IsHandled);
                    if not IsHandled then
                        "Remaining Quantity" := Round("Remaining Qty. (Base)" / "Qty. per Unit of Measure", UOMMgt.QtyRndPrecision);
                    if QtyToPost <> 0 then begin
                        RemQtyToPost := RemQtyToPost - QtyToPost;
                        Modify();
                        if ProdOrderCompModified then
                            InsertConsumpEntry(ProdOrderComp, "Line No.", QtyToPost, false)
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnPostConsumptionBeforeRndRemQty(var ProdOrderComp: Record "Prod. Order Component"; var ItemJnlLine: Record "Item Journal Line"; var NewRemainingQty: Decimal; var QtyToPost: Decimal; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
