### ISSUE TITLE
[Event Change] Codeunit::"Item Jnl.-Post Line" - Function InsertConsumpEntry - OnBeforeInsertConsumpEntry

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10426]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: InsertConsumpEntry
Publisher Event: OnBeforeInsertConsumpEntry
Reason: add an extra Parameter
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeInsertConsumpEntry(var ProdOrderComponent: Record "Prod. Order Component"; var ItemJnlLine: Record "Item Journal Line"; QtyBase: Decimal; var ModifyProdOrderComp: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
