### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function PostConsumption - OnPostConsumptionBeforeRemQtyPost

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10423]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: PostConsumption
Publisher Event: OnPostConsumptionBeforeRemQtyPost
Reason: To implement custom business logic
Where is the event placed:
OnPostConsumptionBeforeRemQtyPost(ItemJnlLine);
            if RemQtyToPost <> 0 then
                InsertConsumpEntry(ProdOrderComp, ItemJnlLine."Prod. Order Comp. Line No.", RemQtyToPost, false);
        end;
        ProdOrderCompModified := false;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnPostConsumptionBeforeRemQtyPost(var ItemJnlLine: Record "Item Journal Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
