### ISSUE TITLE
[Event Request] Codeunit::"Item Jnl.-Post Line" - Function ItemValuePosting - OnItemValuePostingBeforeInsertOHValueEntry

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10420]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: ItemValuePosting
Publisher Event: OnItemValuePostingBeforeInsertOHValueEntry
Reason: 
Where is the event placed:
OnItemValuePostingOnAfterInsertValueEntry(GlobalValueEntry, GlobalItemLedgEntry, ValueEntryNo);
            if ("Value Entry Type" <> "Value Entry Type"::"Direct Cost") or
               ("Item Charge No." <> '')
            then begin
                if ("Value Entry Type" <> "Value Entry Type"::Rounding) and (not Adjustment) then begin
                    if GlobalItemLedgEntry.Positive then
                        GlobalItemLedgEntry.Modify();
                    **OnItemValuePostingBeforeInsertOHValueEntr**y(ItemJnlLine, GlobalValueEntry, GlobalItemLedgEntry, ValueEntryNo, IsHandled);
                    if not IsHandled then
                        if ((GlobalValueEntry."Valued Quantity" > 0) or
                            (("Applies-to Entry" <> 0) and ("Entry Type" in ["Entry Type"::Purchase, "Entry Type"::"Assembly Output"]))) and
                           (OverheadAmount <> 0)
                        then
                            InsertOHValueEntry(GlobalValueEntry, OverheadAmount, OverheadAmountACY);
                    if (Item."Costing Method" = Item."Costing Method"::Standard) and
                       ("Entry Type" = "Entry Type"::Purchase) and
                       (GlobalValueEntry."Entry Type" <> GlobalValueEntry."Entry Type"::Revaluation)
                    then
                        InsertVarValueEntry(
                          GlobalValueEntry,
                          -GlobalValueEntry."Cost Amount (Actual)" + OverheadAmount,
                          -(GlobalValueEntry."Cost Amount (Actual) (ACY)" + OverheadAmountACY));
                end;
            end else begin
                if IsBalanceExpectedCostFromRev(ItemJnlLine) then
                    InsertBalanceExpCostRevEntry(GlobalValueEntry);
                **OnItemValuePostingBeforeInsertOHValueEntry**(ItemJnlLine, GlobalValueEntry, GlobalItemLedgEntry, ValueEntryNo, IsHandled);
                if not IsHandled then
                    if ((GlobalValueEntry."Valued Quantity" > 0) or
                        (("Applies-to Entry" <> 0) and ("Entry Type" in ["Entry Type"::Purchase, "Entry Type"::"Assembly Output"]))) and
                       (OverheadAmount <> 0)
                    then
                        InsertOHValueEntry(GlobalValueEntry, OverheadAmount, OverheadAmountACY);
                if ((GlobalValueEntry."Valued Quantity" > 0) or ("Applies-to Entry" <> 0)) and
                   ("Entry Type" = "Entry Type"::Purchase) and
                   (Item."Costing Method" = Item."Costing Method"::Standard) and
                   (Round(VarianceAmount, GLSetup."Amount Rounding Precision") <> 0) or
                   VarianceRequired
                then
                    InsertVarValueEntry(GlobalValueEntry, VarianceAmount, VarianceAmountACY);
Event Code:
[IntegrationEvent(true, false)]
    local procedure OnItemValuePostingBeforeInsertOHValueEntry(var ItemJournalLine: Record "Item Journal Line"; var ValueEntry: Record "Value Entry"; var ItemLedgerEntry: Record "Item Ledger Entry"; var ValueEntryNo: Integer; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
