### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforeCheckAndUpdateControlBill

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10438]
Hi, in the Codeunit 80 Sales Post, would it be possible to get an event OnBeforeCheckAndUpdateControlBill, like this :
![image](https://user-images.githubusercontent.com/76154006/103545308-aa5f3700-4ea1-11eb-978c-df790f1609b7.png)
![image](https://user-images.githubusercontent.com/76154006/103545720-412bf380-4ea2-11eb-8f4f-2a58b9a4b34c.png)
Thanks

**Comment by StanPesotskiy** [comment]
Can you use the existing event OnCheckAndUpdateOnAfterSetPostingFlags with same parameters, but called few code lines before?
