### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforeWhseReceive

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#10430]
Hi, would it be possible to get an event OnBeforeWhseReceive in codeunit 80 Sales Post, in trigger OnRun, like this :
![image](https://user-images.githubusercontent.com/76153139/103539200-e7bec700-4e97-11eb-9dbb-c465bc535d81.png)
![image](https://user-images.githubusercontent.com/76153139/103539222-ef7e6b80-4e97-11eb-8be3-8f27b051224a.png)
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
