### ISSUE TITLE
[Event Change] Codeunit::"Item Jnl.-Post Line" - Function UnApply - OnUnApplyOnBeforeUpdateItemLedgerEntries

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10435]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: UnApply
Publisher Event: OnUnApplyOnBeforeUpdateItemLedgerEntries
Reason: add an extra Parameter
Where is the event placed:
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnUnApplyOnBeforeUpdateItemLedgerEntries(var ItemLedgerEntry1: Record "Item Ledger Entry"; var ItemLedgerEntry2: Record "Item Ledger Entry"; ItemApplnEntry: Record "Item Application Entry")
    begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
