### ISSUE TITLE
[Event Change] Codeunit::"Item Jnl.-Post Line" - Function InitValueEntry - OnInitValueEntryOnAfterAssignFields

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10431]
We like to request the following Event:
Object: Codeunit::"Item Jnl.-Post Line"
Function: InitValueEntry
Publisher Event: OnInitValueEntryOnAfterAssignFields
Reason: add an extra Parameter
Where is the event placed:
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnInitValueEntryOnAfterAssignFields(var ValueEntry: Record "Value Entry"; ItemLedgEntry: Record "Item Ledger Entry"; ItemJournalLine: Record "Item Journal Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
