### ISSUE TITLE
[Event Modification] Codeunit 80 Sales.-Post - OnBeforeSalesLineDeleteAll() 

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#10437]
Hi, would it be possible to modify the event OnBeforeSalesLineDeleteAll in codeunit 80 SalesPost to insert a SalesHeader parameter, like this :
![image](https://user-images.githubusercontent.com/76153139/103543493-ea70ea80-4e9e-11eb-92c9-8b280da064a4.png)
![image](https://user-images.githubusercontent.com/76153139/103543523-f2c92580-4e9e-11eb-9208-dd275a7a97e0.png)
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
