### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforePostSalesLineOnLineIsItem

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10448]
Hi, would it be possible to get an event OnBeforePostSalesLineOnLineIsItem in Codeunit 80 Sales Post, procedure PostSalesLine, like this

```
    local procedure PostSalesLine
    begin
        with SalesLine do begin
            if Type = Type::Item then begin
                CostBaseAmount := "Line Amount";

                OnBeforePostSalesLineOnLineIsItem(SalesHeader,TempSalesLineGlobal,SalesLine);

                if ("No." <> '') and ("Qty. Shipped (Base)" = 0) then
                    TestField("Unit of Measure Code");
            end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostSalesLineOnLineIsItem(SalesHeader: Record "Sales Header"; TempSalesLineGlobal: Record "Sales Line" ; SalesLine: Record "Sales Line")
    begin
    end;    
```

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
