### ISSUE TITLE
[Enum Request] Table "Profile Questionaire Header" OptionMembers to Enums

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10442]
Enums are sadly missing in this table for priority, type etc. Would be good to have these options as well as enums.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
