### ISSUE TITLE
[Event Request] Codeunit 10140 Deposit Post - OnBeforePostBalancingEntry

### ISSUE THREAD

**Issue by SER-KBROWN** [microsoft/ALAppExtensions#10446]
Please add the following parameter:

"Source Currency Amount" := DepositHeader."Total Deposit Amount";
            Validate(Amount);
            "Amount (LCY)" := -TotalAmountLCY;
            OnBeforePostBalancingEntry(GenJnlLine, DepositHeader, **GenJnlPostLine**);
            GenJnlPostLine.RunWithCheck(GenJnlLine);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
