### ISSUE TITLE
[Event Modification] Codeunit 80 Sales.-Post - OnBeforePostBalancingEntry

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#10457]
Hi, would it be possible to modify the event OnBeforePostBalancingEntry in codeunit 80 SalesPost to insert a SalesHeader parameter, like this : 
![image](https://user-images.githubusercontent.com/76153139/103658317-5882e380-4f6b-11eb-85a4-bef3630f81ef.png)
![image](https://user-images.githubusercontent.com/76153139/103658213-35f0ca80-4f6b-11eb-8c65-40c5d9f8ef58.png)
Thanks

**Comment by StanPesotskiy** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

The current signature already includes SalesHeader.
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostBalancingEntry(var GenJnlLine: Record "Gen. Journal Line"; **SalesHeader: Record "Sales Header";** var TotalSalesLine: Record "Sales Line"; var TotalSalesLineLCY: Record "Sales Line"; CommitIsSuppressed: Boolean; PreviewMode: Boolean)
