### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnAfterInitItemJnlLine

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10453]
Hi, would it be possible to get an event OnAfterInitItemJnlLine in codeunit 80 Sales Post, procedure PostItemJnlLine, like this : 
```
    procedure PostItemJnlLine
    begin
        IsHandled := false;
        OnBeforePostItemJnlLine(
          SalesHeader, SalesLine, QtyToBeShipped, QtyToBeShippedBase, QtyToBeInvoiced, QtyToBeInvoicedBase,
          ItemLedgShptEntryNo, ItemChargeNo, TrackingSpecification, IsATO, SuppressCommit, IsHandled);
        if IsHandled then
            exit;

        ClearRemAmtIfNotItemJnlRollRndg(SalesLine);

        with ItemJnlLine do begin
            Init;
            OnAfterInitItemJnlLine(ItemJnlLine, SalesHeader, SalesLine);
            CopyFromSalesHeader(SalesHeader);
```
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterInitItemJnlLine(var ItemJnlLine: Record "Item Journal Line";var SalesHeader: Record "Sales Header";SalesLine : Record "Sales Line")
    begin
    end;    
```
?
Thanks

**Comment by StanPesotskiy** [comment]
There is  the event  OnPostItemJnlLineOnBeforeCopyTrackingFromSpec(TrackingSpecification, ItemJnlLine, SalesHeader, SalesLine,...); called after fields copied from sales header/line:

        with ItemJnlLine do begin
            Init();
            OnAfterInitItemJnlLine(ItemJnlLine, SalesHeader, SalesLine);
            CopyFromSalesHeader(SalesHeader);
            CopyFromSalesLine(SalesLine);
            "Country/Region Code" := GetCountryCode(SalesLine, SalesHeader);

            OnPostItemJnlLineOnBeforeCopyTrackingFromSpec(TrackingSpecification, ItemJnlLine, SalesHeader, SalesLine, SalesInvHeader, SalesCrMemoHeader);

Can't you use it instead?
