### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforeCheckAndUpdateArchiveUnpostedOrder

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10464]
Hi, in the Codeunit 80 Sales Post, would it be possible to get an event OnBeforeCheckAndUpdateArchiveUnpostedOrder, like this :
![image](https://user-images.githubusercontent.com/76154006/103668466-69395680-4f77-11eb-8445-8183c3ae8ab5.png)
![image](https://user-images.githubusercontent.com/76154006/103668932-01cfd680-4f78-11eb-8f50-8c3b5851b7d9.png)
Thanks

**Comment by StanPesotskiy** [comment]
There is already an event:
```
            ReleaseSalesDocument(SalesHeader);
            OnCheckAndUpdateOnAfterReleaseSalesDocument(SalesHeader, PreviewMode);
