### ISSUE TITLE
[Event Request] codeunit 1102 "CA Jnl.-Post Line" - OnAfterRunWithCheck

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#10467]
Could you please extend the OnAfterRunWithCheck integration event in codeunit 1102 "CA Jnl.-Post Line" to **include the sender**?

Event signature:
```
[IntegrationEvent(true, false)]
local procedure OnAfterRunWithCheck(var CostJournalLine: Record "Cost Journal Line")
begin
end;
```

It should be similar to integration event OnAfterRunWithCheck in codeunit 12 "Gen. Jnl.-Post Line".
We created recurring cost journals and we would like to extend the posting routine (same as in standard general posting).

This event was originally requested by us but the IntegrationEvent properties were not specified:
https://github.com/microsoft/ALAppExtensions/issues/4830

Thank you very much!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
