### ISSUE TITLE
New Event - Codeunit 13 - Function CopyFields

### ISSUE THREAD

**Issue by dagnybjork** [microsoft/ALAppExtensions#10466]
Requesting a new event in codeunit 13, inside function CopyFields as follows

![image](https://user-images.githubusercontent.com/28901234/103749874-faeba700-4ffd-11eb-94ef-096dd6f060d8.png)

**LOCAL [IntegrationEvent] OnBeforeCopyFields(VAR GenJnlLine : Record "Gen. Journal Line";VAR IsHandled : Boolean)**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
