### ISSUE TITLE
[Event Modification] Codeunit 80 Sales.-Post - OnBeforeUpdateShippingNo

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10460]
Hi, would it be possible to modify the event OnBeforeUpdateShippingNo in codeunit 80 SalesPost to insert SalesSetup and NoSeriesMgt parameters, like this :
![image](https://user-images.githubusercontent.com/76154006/103660662-27f07900-4f6e-11eb-8aaa-38cc9eed9a70.png)
![image](https://user-images.githubusercontent.com/76154006/103660913-6f770500-4f6e-11eb-9cbb-d0bbb46156be.png)
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
