### ISSUE TITLE
[Event Request] codeunit 99000815 "Reservation-Check Date Confl.": SalesLineCheck

### ISSUE THREAD

**Issue by TimCsr** [microsoft/ALAppExtensions#10469]
Object: codeunit 99000815 "Reservation-Check Date Confl."

Function: SalesLineCheck

Integration Event:

OnSalesLineCheckOnBeforeUpdateDate(ReservEntry, PurchLine, IsHandled);
![image](https://user-images.githubusercontent.com/50943286/103751694-fd073300-5008-11eb-9946-8a475df91212.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
