### ISSUE TITLE
[Event Request] COD419 - IsAllowedPath

### ISSUE THREAD

**Issue by SKeiler** [Microsoft/ALAppExtensions#1047]
Hi,

we have a local cloud environment for our ISV. The customers uses the web client. To handle the file handling, we use a defined network folder for every customer to upload and download files (and to send batch files to the printer). 

To prevent, that a customer has the chance to read or write in a file folder from another customer, we would like to use the IsAllowedPath in COD419. Could you please add an Event so that we has the possibility to check is the path valid for the customer.

![2019-02-01_15h43_16](https://user-images.githubusercontent.com/45033081/52130199-d6306d00-2639-11e9-9676-83584cce9418.jpg)

Maybe in this case the call of the IsAllowedPath-Function could be added in the missing Server-functions (DownloadHandler,DownloadToFile,DownloadTempFile,...)

**Comment by AlexanderYakunin** [comment]
This is cannot be done as event as we cannot expose server path. I've assigned this to Extensibility enhancement to forward for more detailed review.

**Comment by AndreiPanko** [comment]
If "local cloud environment" means that you have access to the code please implement this in your ISV solution.
