### ISSUE TITLE
[Event Request] Table 10752 SII Doc. Upload State - OnCreateNewRequestInternalOnBeforeSIIDocUploadStateInsert

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10478]
We need a new event   in Table 10752 "SII Doc. Upload State" named   **OnCreateNewRequestInternalOnBeforeSIIDocUploadStateInsert**:

    [IntegrationEvent(false, false)]
    local procedure OnCreateNewRequestInternalOnBeforeSIIDocUploadStateInsert(var SIIDocUploadState: Record "SII Doc. Upload State"; EntryNo: Integer; InvEntryNo: Integer; DocumentSource: Enum "SII Doc. Upload State Document Source"; DocumentType: Enum "SII Doc. Upload State Document Type"; DocumentNo: Code[35]; ExternalDocumentNo: Code[35]; PostingDate: Date)
    begin
    end;

called from:
     
**local procedure CreateNewRequestInternal**(EntryNo: Integer; InvEntryNo: Integer; DocumentSource: Enum "SII Doc. Upload State Document Source"; DocumentType: Enum "SII Doc. Upload State Document Type"; DocumentNo: Code[35]; ExternalDocumentNo: Code[35]; PostingDate: Date)
    var
        SIIHistory: Record "SII History";
        SIIDocUploadState: Record "SII Doc. Upload State";
        TempSIIDocUploadState: Record "SII Doc. Upload State" temporary;
        SIIManagement: Codeunit "SII Management";
        SIIXMLCreator: Codeunit "SII XML Creator";
        IsCVPayment: Boolean;
    begin
        if not SIIManagement.IsSIISetupEnabled then
            exit;
        .....
        .....
        .....
        SIIDocUploadState."Inv. Entry No" := InvEntryNo;
        SIIDocUploadState.GetCorrectionInfo(SIIDocUploadState."Corrected Doc. No.", SIIDocUploadState."Corr. Posting Date", SIIDocUploadState."Posting Date");
        SIIDocUploadState."Version No." := GetSIIVersionNo();
        SetStatus(SIIDocUploadState);
        **//INIT INSERT 
OnCreateNewRequestInternalOnBeforeSIIDocUploadStateInsert(SIIDocUploadState,EntryNo,InvEntryNo,DocumentSource,DocumentType,DocumentNo,ExternalDocumentNo,PostingDate);
       //END INSERT**
        SIIDocUploadState.Insert();
        SIIHistory.CreateNewRequest(SIIDocUploadState.Id, SIIHistory."Upload Type"::Regular, 4, false, false);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
