### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post -  OnAfterSalesShptHeaderTransferfields

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10475]
Hi, would it be possible to get an event OnAfterSalesShptHeaderTransferfields in codeunit 80 Sales Post, procedure InsertShipmentHeader, like this 

```
 local procedure InsertShipmentHeader
        with SalesHeader do begin
            SalesShptHeader.Init();
            CalcFields("Work Description");
            SalesShptHeader.TransferFields(SalesHeader);

            OnAfterSalesShptHeaderTransferfields(SalesHeader,SalesShptHeader);

```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSalesShptHeaderTransferfields(SalesHeader: Record "Sales Header";SalesShptHeader: Record "Sales Shipment Header")
    begin
    end;
```

?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
