### ISSUE TITLE
[Event Request] Table 10752 SII Doc. Upload State - OnAfterValidateDocInfo 

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10477]
We need a new event in Table 10752 "SII Doc. Upload State" named **OnAfterValidateDocInfo**:

[IntegrationEvent(false, false)]
local procedure OnAfterValidateDocInfo(var TempSIIDocUploadState: Record "SII Doc. Upload State" temporary; EntryNo: Integer; DocumentSource: Enum "SII Doc. Upload State Document Source"; DocumentType: Enum "SII Doc. Upload State Document Type"; DocumentNo: Code[35])
begin
end;

called from

procedure **ValidateDocInfo**(var TempSIIDocUploadState: Record "SII Doc. Upload State" temporary; EntryNo: Integer; DocumentSource: Enum "SII Doc. Upload State Document Source"; DocumentType: Enum "SII Doc. Upload State Document Type"; DocumentNo: Code[35])
    var
        CustLedgerEntry: Record "Cust. Ledger Entry";
        VendLedgEntry: Record "Vendor Ledger Entry";
        SalesInvoiceHeader: Record "Sales Invoice Header";
        ServiceHeader: Record "Service Header";
        SalesCrMemoHeader: Record "Sales Cr.Memo Header";
        PurchInvHeader: Record "Purch. Inv. Header";
        PurchCrMemoHdr: Record "Purch. Cr. Memo Hdr.";
        SIIManagement: Codeunit "SII Management";
    begin
        TempSIIDocUploadState.Validate("Entry No", EntryNo);
        TempSIIDocUploadState.Validate("Document Source", DocumentSource);
        TempSIIDocUploadState.Validate("Document Type", DocumentType);
        TempSIIDocUploadState.Validate("Is Credit Memo Removal", 
        .......
        .......
        .......
                              VendLedgEntry."Succeeded Company Name", VendLedgEntry."Succeeded VAT Registration No.", VendLedgEntry."ID Type");
                        end;
                end;
        end;
        **//INIT INSERT
        OnAfterValidateDocInfo(TempSIIDocUploadState, EntryNo, DocumentSource, DocumentType, DocumentNo);
        //END INSERT**
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
