### ISSUE TITLE
[Enum Request] "Entry Type" in Tables

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#10483]
Please replace option field "Entry Type" with an extensible enum in the following tables:

Table 379 "Detailed Cust. Ledg. Entry"
Table 380 "Detailed Vendor Ledg. Entry"
Table 383 "Detailed CV Ledg. Entry Buffer"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
