### ISSUE TITLE
[Event Request] OBJECT Codeunit 1509 Notification Entry Dispatcher

### ISSUE THREAD

**Issue by afrancioli** [microsoft/ALAppExtensions#10485]
Please add this event in codeunit  1509 Notification Entry Dispatcher

   LOCAL PROCEDURE CreateMailAndDispatch@13(VAR NotificationEntry@1005 : Record 1511;Email@1003 : Text);
    VAR
      NotificationSetup@1004 : Record 1512;
      DocumentMailing@1002 : Codeunit 260;
      BodyText@1007 : Text;
      bMailCreated@1101345000 : Boolean;
    BEGIN
      **//PSA EvtMgt Begin
      OnBeforeCreateMailAndDispatch(NotificationEntry,Email,bMailCreated);
      IF bMailCreated THEN
        EXIT;
      //PSA EvtMgt End**
      IF GetHTMLBodyText(NotificationEntry,BodyText) THEN
        IF DocumentMailing.EmailFileWithSubjectAndSender(
             '','',HtmlBodyFilePath,NotificationMailSubjectTxt,Email,TRUE,NotificationEntry."Sender User ID")
        THEN
          NotificationManagement.MoveNotificationEntryToSentNotificationEntries(
            NotificationEntry,BodyText,TRUE,NotificationSetup."Notification Method"::Email)
        ELSE BEGIN
          NotificationEntry.SetErrorMessage(GETLASTERRORTEXT);
          CLEARLASTERROR;
          NotificationEntry.MODIFY(TRUE);
        END;
    END;

    [Integration(TRUE)]
    **LOCAL PROCEDURE OnBeforeCreateMailAndDispatch@1101345002(VAR NotificationEntry@1101345001 : Record 1511;Email@1101345000 : Text;VAR bMailCreated@1101345002 : Boolean);**
    BEGIN
    END;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
