### ISSUE TITLE
[Event Request] OBJECT Codeunit 1535 Approvals Mgmt.

### ISSUE THREAD

**Issue by afrancioli** [microsoft/ALAppExtensions#10486]
Please add this event in codeunit OBJECT Codeunit 1535 Approvals Mgmt.

  LOCAL PROCEDURE **CreateApprovalRequestForApproverChain**@46(WorkflowStepArgument@1008 : Record 1523;ApprovalEntryArgument@1000 : Record 454;SufficientApproverOnly@1003 : Boolean);
    VAR
      ApprovalEntry@1001 : Record 454;
      UserSetup@1007 : Record 91;
      ApproverId@1002 : Code[50];
      SequenceNo@1006 : Integer;
      bApprovalCreated@1101345000 : Boolean;
      MaxCount@1004 : Integer;
      i@1005 : Integer;
    BEGIN
      **//PSA EvtMgt Begin
      OnBeforeCreateApprovalRequestForApproverChain(WorkflowStepArgument,ApprovalEntryArgument,SufficientApproverOnly,IsHandled);
      IF IsHandled THEN
        EXIT;
      //PSA EvtMgt End**
      ApproverId := USERID;

      WITH ApprovalEntry DO BEGIN
        SETCURRENTKEY("Record ID to Approve","Workflow Step Instance ID","Sequence No.");
        SETRANGE("Table ID",ApprovalEntryArgument."Table ID");
        SETRANGE("Record ID to Approve",ApprovalEntryArgument."Record ID to Approve");
        SETRANGE("Workflow Step Instance ID",ApprovalEntryArgument."Workflow Step Instance ID");
        SETRANGE(Status,Status::Created);
        IF FINDLAST THEN
          ApproverId := "Approver ID"
        ELSE
          IF (WorkflowStepArgument."Approver Type" = WorkflowStepArgument."Approver Type"::"Salesperson/Purchaser") AND
             (WorkflowStepArgument."Approver Limit Type" = WorkflowStepArgument."Approver Limit Type"::"First Qualified Approver")
          THEN BEGIN
            FindUserSetupBySalesPurchCode(UserSetup,ApprovalEntryArgument);
            ApproverId := UserSetup."User ID";
          END;
      END;

    [Integration(TRUE)]
    [External]
    LOCAL PROCEDURE OnBeforeCreateApprovalRequestForApproverChain@1101345001(WorkflowStepArgument@1101345002 : Record 1523;ApprovalEntryArgument@1101345001 : Record 454;SufficientApproverOnly@1101345000 : Boolean;VAR IsHandled@1101345003 : Boolean);
    BEGIN
    END;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
