### ISSUE TITLE
"Sales Line" procedure ShowItemSub

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#10482]
In the Sales Line the procecure ShowItemSub is set to scope OnPrem?
On for example "Prod. Order Component" or  "Assembly Line" the same  procedure is not scope onPrem.
We want to use this procedure in the  Sales Line also on Target= Cloud.
Thank you.

Old Code:
```
[Obsolete('Function scope will be changed to OnPrem', '15.1')]
procedure ShowItemSub()
var
    IsHandled: Boolean;
begin

```
NewCode:
```
procedure ShowItemSub()
var
    IsHandled: Boolean;
begin

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
