### ISSUE TITLE
Report dataset field request

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/ALAppExtensions#10480]
I need in the report 1307 the field "Corrected Invoice No." (10705) for an rdlc personalization

**Comment by AlexanderYakunin** [comment]
Is this related to local functionality?

**Comment by AlvaroRosadoP** [comment]
Yes, is functionality for ESP location

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
