### ISSUE TITLE
[Event Request] CU 1247 Process Gen Jnl Lines ImportBankStatement

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#10488]
Hello,
can we please add

`
    [IntegrationEvent(false, false)]
    local procedure OnBeforeImportBankStatement(var GenJnlLine: record "Gen. Journal Line"; var GenJnlBatch: Record "Gen. Journal Batch"; var IsHandled: boolean)
    begin
    end;

procedure ImportBankStatement(GenJnlLine: Record "Gen. Journal Line")
    var
        GenJnlBatch: Record "Gen. Journal Batch";
        BankAcc: Record "Bank Account";
        BankExportImportSetup: Record "Bank Export/Import Setup";
        DataExchDef: Record "Data Exch. Def";
        DataExchMapping: Record "Data Exch. Mapping";
        DataExchLineDef: Record "Data Exch. Line Def";
        DataExch: Record "Data Exch.";
        GenJnlLineTemplate: Record "Gen. Journal Line";
        ProgressWindow: Dialog;
        IsHandled: Boolean;
    begin
        GenJnlBatch.Get(GenJnlLine."Journal Template Name", GenJnlLine."Journal Batch Name");

        OnBeforeImportBankStatement(GenJnlLine, GenJnlBatch, IsHandled);
        if IsHandled then
            exit;
`
it will allow to handle custom import.

Thanks,
Bartek

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
