### ISSUE TITLE
All AL Tests fails first because Errors are not translated to ES-ES under Test Runner

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/ALAppExtensions#10489]
I've just installed Docker artifacts with **BC v17.0.16993.0 ES-ES OnPrem**

I open **AL Test Tool Page**, load all Codeunits, select __Test Runner - Isol. Codeunit__ as Test Runner engine.

**When I RUN all the Tests, all they end with _FAILURE_....**

*In many of them, the Test fails simply because the error message received in Spanish does not match the one expected that is still in English.*

Does this mean that it is not possible to pass the standard tests in the versions localized to other languages?

![image](https://user-images.githubusercontent.com/5801847/103941659-78630480-512f-11eb-9663-cc38ac31736d.png)

I have also seen that the expected error messages are **defined as Labels** within the code of the test Codeunits themselves so they seem extremely fragile for this reason too ... maybe they should extract the exact text string from the Test target Codeunit that you have defined instead of having them all replicated in every Test Function.

**Comment by AlexanderYakunin** [comment]
All tests should be run in ENU language layer. When they will run successfully for any local version.

**Comment by JavierFuentes** [comment]
Ok @AlexanderYakunin,
in that case, maybe, all the standard Test should set ENU as GLOBALLANGUAGE automatically as a Inicialization preset...

Do you think it's possible?
