### ISSUE TITLE
[Event Request] Codeunit 6620 Copy Document Mgt. procedure CheckFromSalesHeader

### ISSUE THREAD

**Issue by afrancioli** [microsoft/ALAppExtensions#10487]
Is it possible to add an event in codeunit 6620 Copy Document Mgt.

Procedure CheckFromSalesHeader. The new event should condition the execution of the standard code since we need to avoid some testfields.

    LOCAL PROCEDURE CheckFromSalesHeader@105(SalesHeaderFrom@1000 : Record 36;SalesHeaderTo@1001 : Record 36);
    BEGIN
      WITH SalesHeaderTo DO BEGIN
        **//PSAIT001.Begin
        IsHandled := false;
        OnBeforeCheckFromSalesHeader(SalesHeaderFrom, SalesHeaderTo,ISHandled);
        if IsHandled then 
           exit;
        //PSAIT001.End**
        SalesHeaderFrom.TESTFIELD("Bill-to Customer No.","Bill-to Customer No.");
        SalesHeaderFrom.TESTFIELD("Customer Posting Group","Customer Posting Group");
        SalesHeaderFrom.TESTFIELD("Gen. Bus. Posting Group","Gen. Bus. Posting Group");
        SalesHeaderFrom.TESTFIELD("Currency Code","Currency Code");
        SalesHeaderFrom.TESTFIELD("Prices Including VAT","Prices Including VAT");
      END;
    END;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
