### ISSUE TITLE
[Event Request] Codeunit 10755 SII Initial Doc. Upload - OnHandleExistingCustomerLedgerEntriesOnBeforeCreateNewRequest

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10491]
We need a new event in Codeunit 10755 "SII Initial Doc. Upload" named **OnHandleExistingCustomerLedgerEntriesOnBeforeCreateNewRequest**:
 
   [IntegrationEvent(false, false)]
    **local procedure OnHandleExistingCustomerLedgerEntriesOnBeforeCreateNewRequest(VAR CustLedgerEntry: Record "Cust. Ledger Entry");**
    begin
    end;

called from:

**local procedure HandleExistingCustomerLedgerEntries()**
    var
        SIIDocUploadState: Record "SII Doc. Upload State";
        CustLedgerEntry: Record "Cust. Ledger Entry";
    begin
        CustLedgerEntry.SetRange("Posting Date", StartDate, EndDate);
        if CustLedgerEntry.FindSet then begin
            repeat
                **//INIT INSERT
                OnHandleExistingCustomerLedgerEntriesOnBeforeCreateNewRequest(CustLedgerEntry);
                //END INSERT**
                if CustLedgerEntry."Document Type" in [CustLedgerEntry."Document Type"::"Credit Memo",
                                                       CustLedgerEntry."Document Type"::Invoice]
                then
                    SIIDocUploadState.CreateNewRequest(
                      CustLedgerEntry."Entry No.", SIIDocUploadState."Document Source"::"Customer Ledger",
                      CustLedgerEntry."Document Type", CustLedgerEntry."Document No.", CustLedgerEntry."External Document No.",
                      CustLedgerEntry."Posting Date");
            until CustLedgerEntry.Next = 0;
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
