### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnPostDtldVendLedgEntriesOnAfterGetAccNo

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10499]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnPostDtldVendLedgEntriesOnAfterGetAccNo**:

[IntegrationEvent(false, false)]
    **local procedure OnPostDtldVendLedgEntriesOnAfterGetAccNo**(VAR GenJournalLine: Record "Gen. Journal Line"; VAR AccountNo: Code[20])
    begin
    end;

called from:

**local procedure PostDtldVendLedgEntries**(GenJnlLine: Record "Gen. Journal Line"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; VendPostingGr: Record "Vendor Posting Group"; LedgEntryInserted: Boolean) DtldLedgEntryInserted: Boolean
    var
        TempInvPostBuf: Record "Invoice Post. Buffer" temporary;
        DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry";
        Currency: Record Currency;
        GLEntry: Record "G/L Entry";
        DtldVendLedgEntry2: Record "Detailed Vendor Ledg. Entry";
        AdjAmount: array[4] of Decimal;
        DtldVendLedgEntryNoOffset: Integer;
        SaveEntryNo: Integer;
        PayableAccAmtLCY: Decimal;
        PayableAccAmtAddCurr: Decimal;
        ExistDtldCVLedgEntryBuf: Boolean;
        FindBill: Boolean;
    begin
        if GenJnlLine."Account Type" <> GenJnlLine."Account Type"::Vendor then
            exit;

if DtldVendLedgEntry.FindLast then
            DtldVendLedgEntryNoOffset := DtldVendLedgEntry."Entry No."
        else
            DtldVendLedgEntryNoOffset := 0;
        DtldCVLedgEntryBuf.Reset();
        DtldCVLedgEntryBuf.SetRange("Initial Document Type", DtldCVLedgEntryBuf."Initial Document Type"::Bill);
        if DtldCVLedgEntryBuf.FindFirst then
            FindBill := true;

DtldCVLedgEntryBuf.Reset();
        if DtldCVLedgEntryBuf.FindSet() then begin
            if LedgEntryInserted or FindBill then begin
                SaveEntryNo := NextEntryNo;
                NextEntryNo := NextEntryNo + 1;
                NextEntryNo2 := NextEntryNo;
            end;
            repeat
                InsertDtldVendLedgEntry(GenJnlLine, DtldCVLedgEntryBuf, DtldVendLedgEntry, DtldVendLedgEntryNoOffset);
                UpdateVendLedgEntryStats(DtldVendLedgEntry."Vendor Ledger Entry No.");
                UpdateTotalAmounts(TempInvPostBuf, GenJnlLine."Dimension Set ID", DtldCVLedgEntryBuf);
                if ((DtldCVLedgEntryBuf."Amount (LCY)" <> 0) or
                    (DtldCVLedgEntryBuf."VAT Amount (LCY)" <> 0)) or
                   ((AddCurrencyCode <> '') and (DtldCVLedgEntryBuf."Additional-Currency Amount" <> 0))
                then
                    case DtldCVLedgEntryBuf."Entry Type" of
                        DtldCVLedgEntryBuf."Entry Type"::Application:
                            if CheckCarteraPostDtldVendLE(
                                 GenJnlLine, DtldVendLedgEntry, PayableAccAmtLCY, PayableAccAmtAddCurr, false)
                            then begin
                                GetCurrency(Currency, DtldCVLedgEntryBuf."Currency Code");
                                CheckNonAddCurrCodeOccurred(Currency.Code);
                                CreateGLEntry(GenJnlLine,
                                  VendPostingGr.GetPayablesAccount, -DtldCVLedgEntryBuf."Amount (LCY)", 0,
                                  DtldCVLedgEntryBuf."Currency Code" = AddCurrencyCode);
                            end;
                        else
                            PostDtldVendLedgEntry(GenJnlLine, DtldCVLedgEntryBuf, VendPostingGr, AdjAmount);
                    end;
            until DtldCVLedgEntryBuf.Next() = 0;

ExistDtldCVLedgEntryBuf := not DtldCVLedgEntryBuf.IsEmpty;
            DtldLedgEntryInserted := not DtldCVLedgEntryBuf.IsEmpty;
            DtldCVLedgEntryBuf.DeleteAll();

if UseGLBillsAccount(GenJnlLine) then begin
                VendPostingGr.TestField("Bills Account");
                AccNo := VendPostingGr."Bills Account";
            end else begin
                VendPostingGr.TestField("Payables Account");
                AccNo := VendPostingGr."Payables Account";
            end;
            **//INIT INSERT
            OnPostDtldVendLedgEntriesOnAfterGetAccNo(GenJnlLine, AccNo);
            //END INSERT**
            if CollDocAmountLCY <> 0 then
                case GenJnlLine."Applies-to Doc. Type" of
                    GenJnlLine."Applies-to Doc. Type"::Bill:
                        AccNo := VendPostingGr.GetBillsInPmtOrderAccount;
                    GenJnlLine."Applies-to Doc. Type"::Invoice:
                        AccNo := VendPostingGr.GetInvoicesInPmtOrderAccount;
                end;
        ......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
