### ISSUE TITLE
[Event Request] Codeunit 10752 SII Doc. Upload Management - OnBeforeExecutePendingRequestsPerDocument

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10493]
We need a new event in Codeunit 10752 "SII Doc. Upload Management" named **OnBeforeExecutePendingRequestsPerDocument**:

[IntegrationEvent(false, false)]
    local procedure OnBeforeExecutePendingRequestsPerDocument(var SIIDocUploadState: Record "SII Doc. Upload State"; var TempSIIHistoryBuffer: Record "SII History" temporary; var XMLDoc: DotNet XmlDocument; var IsInvokeSoapRequest: Boolean; SIISessionId: Integer)
    begin
    end;

called from:

**local procedure ExecutePendingRequestsPerDocument**(var SIIDocUploadState: Record "SII Doc. Upload State"; var TempSIIHistoryBuffer: Record "SII History" temporary; var XMLDoc: DotNet XmlDocument; var IsInvokeSoapRequest: Boolean; SIISessionId: Integer)
    var
        DotNetExceptionHandler: Codeunit "DotNet Exception Handler";
        IsSupported: Boolean;
        Message: Text;
    begin
        **//INIT INSERT
        OnBeforeExecutePendingRequestsPerDocument(SIIDocUploadState, TempSIIHistoryBuffer, XMLDoc, IsInvokeSoapRequest, SIISessionId);
        //END INSERT**
        TempSIIHistoryBuffer.SetRange("Document State Id", SIIDocUploadState.Id);
        if TempSIIHistoryBuffer.FindSet then
            repeat
        ......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
