### ISSUE TITLE
[Event Request] Codeunit 10750 SII XML Creator - OnBeforeGenerateClaveRegimenNodeSales

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10495]
We need a new event in Codeunit 10750 "SII XML Creator" named **OnBeforeGenerateClaveRegimenNodeSales** with a local boolean variable "IsHandled":

[IntegrationEvent(false, false)]
    local procedure OnBeforeGenerateClaveRegimenNodeSales(SIIDocUploadState: Record "SII Doc. Upload State"; CustLedgerEntry: Record "Cust. Ledger Entry"; Customer: Record Customer; var RegimeCode: Code[2]; var IsHandled: Boolean)
    begin
    end;

called from:

    
**local procedure GenerateClaveRegimenNodeSales**(var XMLNode: DotNet XmlNode; SIIDocUploadState: Record "SII Doc. Upload State"; CustLedgerEntry: Record "Cust. Ledger Entry"; Customer: Record Customer) RegimeCode: Code[2]
    var
        SIIInitialDocUpload: Codeunit "SII Initial Doc. Upload";
        TempXMLNode: DotNet XmlNode;
        CustLedgerEntryRecRef: RecordRef;
        RegimeCode: Code[2];
        **IsHandled: Boolean**;
    begin
        **//INIT INSERT
        OnBeforeGenerateClaveRegimenNodeSales(SIIDocUploadState, CustLedgerEntry, Customer, RegimeCode, IsHandled);
        if IsHandled then
            exit(RegimeCode);
        //END INSERT**

if SIIInitialDocUpload.DateWithinInitialUploadPeriod(CustLedgerEntry."Posting Date") then
            RegimeCode := '16'
        else begin
            DataTypeManagement.GetRecordRef(CustLedgerEntry, CustLedgerEntryRecRef);
            if SIIManagement.IsLedgerCashFlowBased(CustLedgerEntryRecRef) then
......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
