### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnPostVendOnAfterGetPayablesAccount

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10497]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnPostVendOnAfterGetPayablesAccount**:

[IntegrationEvent(false, false)]
    local procedure OnPostVendOnAfterGetPayablesAccount(VAR GenJournalLine: Record "Gen. Journal Line"; VAR PayablesAccount: Code[20])
    begin
    end;

called from:
**local procedure PostVend**(GenJnlLine: Record "Gen. Journal Line"; Balancing: Boolean)
    var
        Vend: Record Vendor;
        VendPostingGr: Record "Vendor Posting Group";
        VendLedgEntry: Record "Vendor Ledger Entry";
        CVLedgEntryBuf: Record "CV Ledger Entry Buffer";
        TempDtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer" temporary;
        DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry";
        PurchSetup: Record "Purchases & Payables Setup";
        PayablesAccount: Code[20];
        DtldLedgEntryInserted: Boolean;
        CheckExtDocNoHandled: Boolean;
    begin
        OnBeforePostVend(GenJnlLine);

AppliesToDocType := 0;

PurchSetup.Get();
        with GenJnlLine do begin
            DocAmountLCY := 0;
            CollDocAmountLCY := 0;

Vend.Get("Account No.");
            Vend.CheckBlockedVendOnJnls(Vend, "Document Type", true);

if "Posting Group" = '' then begin
                Vend.TestField("Vendor Posting Group");
                "Posting Group" := Vend."Vendor Posting Group";
            end;
            GetVendorPostingGroup(GenJnlLine, VendPostingGr);
            if "Document Type" = "Document Type"::Bill then
                PayablesAccount := VendPostingGr.GetBillsAccount()
            else
                PayablesAccount := VendPostingGr.GetPayablesAccount();

**//INIT INSERT
            OnPostVendOnAfterGetPayablesAccount(GenJnlLine, PayablesAccount);
            //END INSERT**
DtldVendLedgEntry.LockTable();
            VendLedgEntry.LockTable();

InitVendLedgEntry(GenJnlLine, VendLedgEntry);
......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
