### ISSUE TITLE
[Event Request] Codeunit 10755 SII Initial Doc. Upload - OnHandleExistingVendorLedgerEntriesOnBeforeCreateNewRequest

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10492]
We need a new event in Codeunit 10755 "SII Initial Doc. Upload" named **OnHandleExistingVendorLedgerEntriesOnBeforeCreateNewRequest**:

[IntegrationEvent(false, false)]
    local procedure OnHandleExistingVendorLedgerEntriesOnBeforeCreateNewRequest(VAR VendorLedgerEntry: Record "Vendor Ledger Entry");
    begin
    end;

called from:

**local procedure HandleExistingVendorLedgerEntries()**
    var
        SIIDocUploadState: Record "SII Doc. Upload State";
        VendorLedgerEntry: Record "Vendor Ledger Entry";
    begin
        VendorLedgerEntry.SetRange("Posting Date", StartDate, EndDate);
        if VendorLedgerEntry.FindSet then begin
            repeat
                **//INIT INSERT
                OnHandleExistingVendorLedgerEntriesOnBeforeCreateNewRequest(VendorLedgerEntry);
                //END INSERT**
                if VendorLedgerEntry."Document Type" in [VendorLedgerEntry."Document Type"::"Credit Memo",
                                                         VendorLedgerEntry."Document Type"::Invoice]
                then
                    SIIDocUploadState.CreateNewRequest(
                      VendorLedgerEntry."Entry No.", SIIDocUploadState."Document Source"::"Vendor Ledger",
                      VendorLedgerEntry."Document Type", VendorLedgerEntry."Document No.", VendorLedgerEntry."External Document No.",
                      VendorLedgerEntry."Posting Date");
            until VendorLedgerEntry.Next = 0;
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
