### ISSUE TITLE
[Event Request] Codeunit 10752 SII Doc. Upload Management - OnAfterExecutePendingRequestsPerDocument

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10494]
We need a new event in Codeunit 10752 "SII Doc. Upload Management" named **OnAfterExecutePendingRequestsPerDocument**:

[IntegrationEvent(false, false)]
    local procedure OnAfterExecutePendingRequestsPerDocument(var SIIDocUploadState: Record "SII Doc. Upload State"; var TempSIIHistoryBuffer: Record "SII History" temporary; var XMLDoc: DotNet XmlDocument; var IsInvokeSoapRequest: Boolean; SIISessionId: Integer)
    begin
    end;

called from:

**local procedure ExecutePendingRequestsPerDocument**(var SIIDocUploadState: Record "SII Doc. Upload State"; var TempSIIHistoryBuffer: Record "SII History" temporary; var XMLDoc: DotNet XmlDocument; var IsInvokeSoapRequest: Boolean; SIISessionId: Integer)
    var
        DotNetExceptionHandler: Codeunit "DotNet Exception Handler";
        IsSupported: Boolean;
        Message: Text;
    begin
        TempSIIHistoryBuffer.SetRange("Document State Id", SIIDocUploadState.Id);
        if TempSIIHistoryBuffer.FindSet then
            repeat
                TempSIIHistoryBuffer."Session Id" := SIISessionId;
                if not TryGenerateXml(SIIDocUploadState, TempSIIHistoryBuffer, XMLDoc, IsSupported, Message) then begin
                    DotNetExceptionHandler.Collect;
                    TempSIIHistoryBuffer.Status := TempSIIHistoryBuffer.Status::Failed;
                    TempSIIHistoryBuffer."Error Message" :=
                      CopyStr(DotNetExceptionHandler.GetMessage, 1, MaxStrLen(TempSIIHistoryBuffer."Error Message"));
                    SIIDocUploadState.Status := SIIDocUploadState.Status::Failed;
                    SIIDocUploadState.Modify();
                end else
                    if not IsSupported then begin
                        TempSIIHistoryBuffer.Status := TempSIIHistoryBuffer.Status::"Not Supported";
                        SIIDocUploadState.Status := SIIDocUploadState.Status::"Not Supported";
                        TempSIIHistoryBuffer."Error Message" := CopyStr(Message, 1, MaxStrLen(TempSIIHistoryBuffer."Error Message"));
                        SIIDocUploadState.Modify();
                    end else
                        IsInvokeSoapRequest := true or IsInvokeSoapRequest;
                TempSIIHistoryBuffer.Modify();
            until TempSIIHistoryBuffer.Next = 0;
        **//INIT INSERT
        OnAfterExecutePendingRequestsPerDocument(SIIDocUploadState, TempSIIHistoryBuffer, XMLDoc, IsInvokeSoapRequest, SIISessionId);
        //END INSERT**

end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
