### ISSUE TITLE
[Event Request] Codeunit 10750 SII XML Creator - OnBeforeGenerateClaveRegimenNodePurchases

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10496]
We need a new event in Codeunit 10750 "SII XML Creator" named **OnBeforeGenerateClaveRegimenNodePurchases** with a local boolean variable "IsHandled":

[IntegrationEvent(false, false)]
    local procedure OnBeforeGenerateClaveRegimenNodePurchases(SIIDocUploadState: Record "SII Doc. Upload State"; VendLedgerEntry: Record "Vendor Ledger Entry"; Vendor: Record Vendor; var RegimeCode: Code[2]; var IsHandled: Boolean)
    begin
    end;

called from:

**local procedure GenerateClaveRegimenNodePurchases**(var XMLNode: DotNet XmlNode; SIIDocUploadState: Record "SII Doc. Upload State"; VendorLedgerEntry: Record "Vendor Ledger Entry"; Vendor: Record Vendor) RegimeCode: Code[2]
    var
        SIIInitialDocUpload: Codeunit "SII Initial Doc. Upload";
        TempXMLNode: DotNet XmlNode;
        VendorLedgerEntryRecRef: RecordRef;
        RegimeCode: Code[2];
        **IsHandled: Boolean**;
    begin
        **//INIT INSERT
        OnBeforeGenerateClaveRegimenNodePurchases(SIIDocUploadState, VendorLedgerEntry, Vendor, RegimeCode, IsHandled);
        if IsHandled then
            exit(RegimeCode);
        //END INSERT**

if SIIInitialDocUpload.DateWithinInitialUploadPeriod(VendorLedgerEntry."Posting Date") then
            RegimeCode := '14'
        else begin
            DataTypeManagement.GetRecordRef(VendorLedgerEntry, VendorLedgerEntryRecRef);

......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
