### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnPostPayableDocsOnBeforeCreateGLEntryBalAcc

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10500]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnPostPayableDocsOnBeforeCreateGLEntryBalAcc**:

[IntegrationEvent(false, false)]
    local procedure OnPostPayableDocsOnBeforeCreateGLEntryBalAcc(VAR GenJournalLine: Record "Gen. Journal Line"; VAR VendorPostingGroup: Record "Vendor Posting Group"; VAR AccountNo: Code[20])
    begin
    end;

called from (two calls):

**local procedure PostPayableDocs**(GenJnlLine: Record "Gen. Journal Line"; VendPostingGr: Record "Vendor Posting Group")
    var
        GLAccNo: Code[20];
    begin
        if (DocAmountLCY <> 0) or (CollDocAmountLCY <> 0) then
            if NextEntryNo2 = NextEntryNo then
                NextEntryNo := NextEntryNo - 1;
        if DocAmountLCY <> 0 then begin
            GLAccNo := GetGLAccountForPayablesDocs(GenJnlLine, VendPostingGr, DocAmountLCY, CollDocAmountLCY);
            **//INIT INSERT
            OnPostPayableDocsOnBeforeCreateGLEntryBalAcc(GenJnlLine, VendPostingGr, GLAccNo);
            //END INSERT**
            CreateGLEntryBalAcc(GenJnlLine,
              GLAccNo, DocAmountLCY, DocAmtCalcAddCurrency(GenJnlLine, DocAmountLCY),
              GenJnlLine."Bal. Account Type", GenJnlLine."Bal. Account No.");
        end;
        if CollDocAmountLCY <> 0 then begin
            GLAccNo := GetGLAccountForPayablesDocs(GenJnlLine, VendPostingGr, 0, CollDocAmountLCY);
            **//INIT INSERT
            OnPostPayableDocsOnBeforeCreateGLEntryBalAcc(GenJnlLine, VendPostingGr, GLAccNo);
            //END INSERT**
            CreateGLEntryBalAcc(GenJnlLine,
              GLAccNo, CollDocAmountLCY, DocAmtCalcAddCurrency(GenJnlLine, CollDocAmountLCY),
              GenJnlLine."Bal. Account Type", GenJnlLine."Bal. Account No.");
        end;
        exit;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
