### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnPostReceivableDocsOnBeforeCreateGLEntryBalAcc

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10508]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnPostReceivableDocsOnBeforeCreateGLEntryBalAcc**:

[IntegrationEvent(false, false)]
    **local procedure OnPostReceivableDocsOnBeforeCreateGLEntryBalAcc**(VAR GenJournalLine: Record "Gen. Journal Line"; VAR CustomerPostingGroup: Record "Customer Posting Group"; VAR AccountNo: Code[20])
    begin
    end;

called from (two calls):

**local procedure PostReceivableDocs**(GenJnlLine: Record "Gen. Journal Line"; CustPostingGr: Record "Customer Posting Group")
    var
        DocAmountAddCurr: Decimal;
        GLAccNo: Code[20];
    begin
        if (DocAmountLCY <> 0) or (DiscDocAmountLCY <> 0) or (CollDocAmountLCY <> 0) or (RejDocAmountLCY <> 0) or
           (DiscRiskFactAmountLCY <> 0) or (DiscUnriskFactAmountLCY <> 0) or (CollFactAmountLCY <> 0)
        then
            if NextEntryNo2 = NextEntryNo then
                NextEntryNo := NextEntryNo - 1;
        if DocAmountLCY <> 0 then begin
            if GenJnlLine."Currency Code" = AddCurrency.Code then
                DocAmountAddCurr := GenJnlLine.Amount
            else
                DocAmountAddCurr := DocAmtCalcAddCurrency(GenJnlLine, DocAmountLCY);
            GLAccNo := GetGLAccountForReceivableDocs(GenJnlLine, CustPostingGr, DocAmountLCY, CollDocAmountLCY);
            **//INIT INSERT
            OnPostReceivableDocsOnBeforeCreateGLEntryBalAcc(GenJnlLine, CustPostingGr, GLAccNo);
            //END INSERT**
            CreateGLEntryBalAcc(
              GenJnlLine, GLAccNo, DocAmountLCY, DocAmountAddCurr,
              GenJnlLine."Bal. Account Type", GenJnlLine."Bal. Account No.");
        end;
        if DiscDocAmountLCY <> 0 then begin
            CustPostingGr.TestField("Discted. Bills Acc.");
            CreateGLEntryBalAcc(GenJnlLine,
              CustPostingGr."Discted. Bills Acc.", DiscDocAmountLCY, DocAmtCalcAddCurrency(GenJnlLine, DiscDocAmountLCY),
              GenJnlLine."Bal. Account Type", GenJnlLine."Bal. Account No.");
        end;
        if CollDocAmountLCY <> 0 then begin
            GLAccNo := GetGLAccountForReceivableDocs(GenJnlLine, CustPostingGr, 0, CollDocAmountLCY);
            **//INIT INSERT
            OnPostReceivableDocsOnBeforeCreateGLEntryBalAcc(GenJnlLine, CustPostingGr, GLAccNo);
            //END INSERT**
            CreateGLEntryBalAcc(GenJnlLine,
              GLAccNo, CollDocAmountLCY, DocAmtCalcAddCurrency(GenJnlLine, CollDocAmountLCY),
              GenJnlLine."Bal. Account Type", GenJnlLine."Bal. Account No.");
        end;
        ......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
