### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnPostCustOnAfterGetReceivablesAccount

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10501]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnPostCustOnAfterGetReceivablesAccount**:

[IntegrationEvent(false, false)]
    **local procedure OnPostCustOnAfterGetReceivablesAccount**(VAR GenJournalLine: Record "Gen. Journal Line"; VAR ReceivablesAccount: Code[20])
    begin
    end;

called from:

**local procedure PostCust**(var GenJnlLine: Record "Gen. Journal Line"; Balancing: Boolean)
    var
        LineFeeNoteOnReportHist: Record "Line Fee Note on Report Hist.";
        Cust: Record Customer;
        CustPostingGr: Record "Customer Posting Group";
        CustLedgEntry: Record "Cust. Ledger Entry";
        CVLedgEntryBuf: Record "CV Ledger Entry Buffer";
        TempDtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer" temporary;
        DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry";
        SalesSetup: Record "Sales & Receivables Setup";
        ReceivablesAccount: Code[20];
        DtldLedgEntryInserted: Boolean;
    begin
        AppliesToDocType := 0;

SalesSetup.Get();
        with GenJnlLine do begin
            DocAmountLCY := 0;
            DiscDocAmountLCY := 0;
            CollDocAmountLCY := 0;
            RejDocAmountLCY := 0;
            DiscRiskFactAmountLCY := 0;
            DiscUnriskFactAmountLCY := 0;
            CollFactAmountLCY := 0;
            TempRejCustLedgEntry.Reset();
            TempRejCustLedgEntry.DeleteAll();

Cust.Get("Account No.");
            Cust.CheckBlockedCustOnJnls(Cust, "Document Type", true);

if "Posting Group" = '' then begin
                Cust.TestField("Customer Posting Group");
                "Posting Group" := Cust."Customer Posting Group";
            end;
            CustPostingGr.Get("Posting Group");
            if "Document Type" = "Document Type"::Bill then
                ReceivablesAccount := CustPostingGr.GetBillsAccount(false)
            else
                ReceivablesAccount := CustPostingGr.GetReceivablesAccount();

**//INIT INSERT
            OnPostCustOnAfterGetReceivablesAccount(GenJnlLine, ReceivablesAccount);
            //END INSERT**
            DtldCustLedgEntry.LockTable();
            CustLedgEntry.LockTable();

InitCustLedgEntry(GenJnlLine, CustLedgEntry);

......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
