### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnCustUnrealizedVATOnAfterSetBillDoc

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10506]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnCustUnrealizedVATOnAfterSetBillDoc**:

[IntegrationEvent(false, false)]
    **local procedure OnCustUnrealizedVATOnAfterSetBillDoc**(VAR CustLedgerEntry: Record "Cust. Ledger Entry"; VAR VATEntry: Record "VAT Entry")
    begin
    end;

called from:

**local procedure CustUnrealizedVAT**(GenJnlLine: Record "Gen. Journal Line"; var CustLedgEntry2: Record "Cust. Ledger Entry"; SettledAmount: Decimal)
    var
        VATEntry2: Record "VAT Entry";
        TaxJurisdiction: Record "Tax Jurisdiction";
        VATPostingSetup: Record "VAT Posting Setup";
        VATPart: Decimal;
        VATAmount: Decimal;
        VATBase: Decimal;
        VATAmountAddCurr: Decimal;
        VATBaseAddCurr: Decimal;
        PaidAmount: Decimal;
        TotalUnrealVATAmountLast: Decimal;
        TotalUnrealVATAmountFirst: Decimal;
        SalesVATAccount: Code[20];
        SalesVATUnrealAccount: Code[20];
        LastConnectionNo: Integer;
        Doc: Record "Cartera Doc.";
        ClosedDoc: Record "Closed Cartera Doc.";
        PostedDoc: Record "Posted Cartera Doc.";
        FromDocInPostedBillGr: Boolean;
        FromDoc: Boolean;
        CustLedgEntry3: Record "Cust. Ledger Entry";
        CustLedgEntry4: Record "Cust. Ledger Entry";
        FromJnl: Boolean;
        GLEntryNo: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCustUnrealizedVAT(GenJnlLine, CustLedgEntry2, SettledAmount, IsHandled);
        if IsHandled then
            exit;

CustLedgEntry4.Copy(CustLedgEntry2);

FromDoc := false;
        FromDocInPostedBillGr := false;

Doc.SetCurrentKey(Type, "Document No.");
        Doc.SetRange(Type, Doc.Type::Receivable);
        Doc.SetRange("Document No.", CustLedgEntry4."Document No.");
        ClosedDoc.SetCurrentKey(Type, "Document No.");
        ClosedDoc.SetRange(Type, ClosedDoc.Type::Receivable);
        ClosedDoc.SetRange("Document No.", CustLedgEntry4."Document No.");
        ClosedDoc.SetRange("No.", CustLedgEntry4."Bill No.");
        PostedDoc.SetCurrentKey(Type, "Document No.");
        PostedDoc.SetRange(Type, PostedDoc.Type::Receivable);
        PostedDoc.SetRange("Document No.", CustLedgEntry4."Document No.");
        PostedDoc.SetRange("No.", CustLedgEntry4."Bill No.");
        FromDoc := (Doc.FindFirst and (not ClosedDoc.FindFirst));
        FromDocInPostedBillGr := PostedDoc.FindFirst;

......
	......
	......

if VATEntry2.FindSet() and (not FromDocInPostedBillGr) then begin
            LastConnectionNo := 0;
            repeat
                VATPostingSetup.Get(VATEntry2."VAT Bus. Posting Group", VATEntry2."VAT Prod. Posting Group");
                if LastConnectionNo <> VATEntry2."Sales Tax Connection No." then begin
                    InsertSummarizedVAT(GenJnlLine);
                    LastConnectionNo := VATEntry2."Sales Tax Connection No.";
                end;
                VATEntry2.SetBillDoc(IsCustBillDoc(CustLedgEntry4));

**//INIT INSERT
                OnCustUnrealizedVATOnAfterSetBillDoc(CustLedgEntry4, VATEntry2);
                //END INSERT**
                VATPart :=
                  VATEntry2.GetUnrealizedVATPart(
                    GetCustSettledAmount(SettledAmount, CustLedgEntry4, CustLedgEntry3, CustLedgEntry2),
                    PaidAmount,
                    GetCustOriginalAmtLCY(CustLedgEntry4, CustLedgEntry3, CustLedgEntry2),
                    TotalUnrealVATAmountFirst,
                    TotalUnrealVATAmountLast);

OnCustUnrealizedVATOnAfterVATPartCalculation(
                  GenJnlLine, CustLedgEntry2, PaidAmount, TotalUnrealVATAmountFirst, TotalUnrealVATAmountLast, SettledAmount, VATEntry2);
......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
