### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnVendUnrealizedVATOnBeforeApplyFilters

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10504]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnVendUnrealizedVATOnBeforeApplyFilters** with a local boolean variable "IsHandled":

[IntegrationEvent(false, false)]
    **local procedure OnVendUnrealizedVATOnBeforeApplyFilters**(VAR VATEntry: Record "VAT Entry"; VAR VendLedgerEntry4: Record "Vendor Ledger Entry"; VAR VendLedgerEntry3: Record "Vendor Ledger Entry"; VAR VendLedgerEntry2: Record "Vendor Ledger Entry" temporary; CarteraDoc: Record "Cartera Doc."; PostedCarteraDoc: Record "Posted Cartera Doc."; ClosedCarteraDoc: Record "Closed Cartera Doc."; VAR IsHandled: Boolean)
    begin
    end;

called from:

**local procedure VendUnrealizedVAT**(GenJnlLine: Record "Gen. Journal Line"; var VendLedgEntry2: Record "Vendor Ledger Entry"; SettledAmount: Decimal)
    var
        VATEntry2: Record "VAT Entry";
        TaxJurisdiction: Record "Tax Jurisdiction";
        VATPostingSetup: Record "VAT Posting Setup";
        VATPart: Decimal;
        VATAmount: Decimal;
        VATBase: Decimal;
        VATAmountAddCurr: Decimal;
        VATBaseAddCurr: Decimal;
        PaidAmount: Decimal;
        TotalUnrealVATAmountFirst: Decimal;
        TotalUnrealVATAmountLast: Decimal;
        PurchVATAccount: Code[20];
        PurchVATUnrealAccount: Code[20];
        PurchReverseAccount: Code[20];
        PurchReverseUnrealAccount: Code[20];
        LastConnectionNo: Integer;
        Doc: Record "Cartera Doc.";
        ClosedDoc: Record "Closed Cartera Doc.";
        PostedDoc: Record "Posted Cartera Doc.";
        FromDocInPostedPmtOrd: Boolean;
        FromDoc: Boolean;
        VendLedgEntry3: Record "Vendor Ledger Entry";
        VendLedgEntry4: Record "Vendor Ledger Entry";
        FromJnl: Boolean;
        GLEntryNo: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeVendUnrealizedVAT(GenJnlLine, VendLedgEntry2, SettledAmount, IsHandled);
        if IsHandled then
            exit;

VendLedgEntry4.Copy(VendLedgEntry2);

FromDoc := false;
        FromDocInPostedPmtOrd := false;

Doc.SetCurrentKey(Type, "Document No.");
        Doc.SetRange(Type, Doc.Type::Payable);
        Doc.SetRange("Document No.", VendLedgEntry4."Document No.");
        ClosedDoc.SetCurrentKey(Type, "Document No.");
        ClosedDoc.SetRange(Type, ClosedDoc.Type::Payable);
        ClosedDoc.SetRange("Document No.", VendLedgEntry4."Document No.");
        ClosedDoc.SetRange("No.", VendLedgEntry4."Bill No.");
        PostedDoc.SetCurrentKey(Type, "Document No.");
        PostedDoc.SetRange(Type, PostedDoc.Type::Payable);
        PostedDoc.SetRange("Document No.", VendLedgEntry4."Document No.");
        PostedDoc.SetRange("No.", VendLedgEntry4."Bill No.");
        FromDoc := (Doc.FindFirst and (not ClosedDoc.FindFirst));
        FromDocInPostedPmtOrd := PostedDoc.FindFirst;

VATEntry2.Reset();
        VATEntry2.SetCurrentKey("Transaction No.");
        **//INIT INSERT
        IsHandled := FALSE;
        OnVendUnrealizedVATOnBeforeApplyFilters(VATEntry2, VendLedgEntry4, VendLedgEntry3, VendLedgEntry2, Doc, PostedDoc, ClosedDoc, IsHandled);
        IF NOT IsHandled THEN
        //END INSERT**
            if VendLedgEntry4."Document Type" = VendLedgEntry4."Document Type"::Bill then begin
                FromJnl := false;
                if Doc."From Journal" or PostedDoc."From Journal" or ClosedDoc."From Journal" then
                    FromJnl := true;
                VendFindVATSetup(VATPostingSetup, VendLedgEntry4, FromJnl);
                if (VATPostingSetup."Unrealized VAT Type" > VATPostingSetup."Unrealized VAT Type"::Percentage) and
                   (not FromDocInPostedPmtOrd)
                then
                    Error(Text1100000);
                VendLedgEntry3.SetCurrentKey("Document No.", "Document Type", "Vendor No.");
                VendLedgEntry3.SetRange("Document Type", VendLedgEntry3."Document Type"::Invoice);
                VendLedgEntry3.SetRange("Document No.", VendLedgEntry4."Document No.");
......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
