### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnCustUnrealizedVATOnBeforeApplyFilters

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10503]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnCustUnrealizedVATOnBeforeApplyFilters** with a local boolean variable "IsHandled": 

[IntegrationEvent(false, false)]
    **local procedure OnCustUnrealizedVATOnBeforeApplyFilters**(VAR VATEntry: Record "VAT Entry"; VAR CustLedgerEntry4: Record "Cust. Ledger Entry"; VAR CustLedgerEntry3: Record "Cust. Ledger Entry"; VAR CustLedgerEntry2: Record "Cust. Ledger Entry" temporary; CarteraDoc: Record "Cartera Doc."; PostedCarteraDoc: Record "Posted Cartera Doc."; ClosedCarteraDoc: Record "Closed Cartera Doc."; VAR IsHandled: Boolean)
    begin
    end;

called from:

**local procedure CustUnrealizedVAT**(GenJnlLine: Record "Gen. Journal Line"; var CustLedgEntry2: Record "Cust. Ledger Entry"; SettledAmount: Decimal)
    var
        VATEntry2: Record "VAT Entry";
        TaxJurisdiction: Record "Tax Jurisdiction";
        VATPostingSetup: Record "VAT Posting Setup";
        VATPart: Decimal;
        VATAmount: Decimal;
        VATBase: Decimal;
        VATAmountAddCurr: Decimal;
        VATBaseAddCurr: Decimal;
        PaidAmount: Decimal;
        TotalUnrealVATAmountLast: Decimal;
        TotalUnrealVATAmountFirst: Decimal;
        SalesVATAccount: Code[20];
        SalesVATUnrealAccount: Code[20];
        LastConnectionNo: Integer;
        Doc: Record "Cartera Doc.";
        ClosedDoc: Record "Closed Cartera Doc.";
        PostedDoc: Record "Posted Cartera Doc.";
        FromDocInPostedBillGr: Boolean;
        FromDoc: Boolean;
        CustLedgEntry3: Record "Cust. Ledger Entry";
        CustLedgEntry4: Record "Cust. Ledger Entry";
        FromJnl: Boolean;
        GLEntryNo: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCustUnrealizedVAT(GenJnlLine, CustLedgEntry2, SettledAmount, IsHandled);
        if IsHandled then
            exit;

CustLedgEntry4.Copy(CustLedgEntry2);

FromDoc := false;
        FromDocInPostedBillGr := false;

Doc.SetCurrentKey(Type, "Document No.");
        Doc.SetRange(Type, Doc.Type::Receivable);
        Doc.SetRange("Document No.", CustLedgEntry4."Document No.");
        ClosedDoc.SetCurrentKey(Type, "Document No.");
        ClosedDoc.SetRange(Type, ClosedDoc.Type::Receivable);
        ClosedDoc.SetRange("Document No.", CustLedgEntry4."Document No.");
        ClosedDoc.SetRange("No.", CustLedgEntry4."Bill No.");
        PostedDoc.SetCurrentKey(Type, "Document No.");
        PostedDoc.SetRange(Type, PostedDoc.Type::Receivable);
        PostedDoc.SetRange("Document No.", CustLedgEntry4."Document No.");
        PostedDoc.SetRange("No.", CustLedgEntry4."Bill No.");
        FromDoc := (Doc.FindFirst and (not ClosedDoc.FindFirst));
        FromDocInPostedBillGr := PostedDoc.FindFirst;

PaidAmount := CustLedgEntry2."Amount (LCY)" - CustLedgEntry2."Remaining Amt. (LCY)";
        VATEntry2.Reset();
        VATEntry2.SetCurrentKey("Transaction No.");
        VATEntry2.SetRange("Transaction No.", CustLedgEntry2."Transaction No.");
        **//INIT INSERT
        IsHandled := FALSE;
        OnCustUnrealizedVATOnBeforeApplyFilters(VATEntry2, CustLedgEntry4, CustLedgEntry3, CustLedgEntry2, Doc, PostedDoc, ClosedDoc, IsHandled);
        IF NOT IsHandled THEN
        //END INSERT**
            if CustLedgEntry4."Document Type" = CustLedgEntry4."Document Type"::Bill then begin
                FromJnl := false;
                if Doc."From Journal" or PostedDoc."From Journal" or ClosedDoc."From Journal" then
                    FromJnl := true;
                CustFindVATSetup(VATPostingSetup, CustLedgEntry4, FromJnl);
                if (VATPostingSetup."Unrealized VAT Type" > VATPostingSetup."Unrealized VAT Type"::Percentage) and
                   (not FromDocInPostedBillGr)
                then
                    Error(Text1100000);
                CustLedgEntry3.SetCurrentKey("Document No.", "Document Type", "Customer No.");
                CustLedgEntry3.SetRange("Document Type", CustLedgEntry3."Document Type"::Invoice);
                CustLedgEntry3.SetRange("Document No.", CustLedgEntry4."Document No.");
                FromDoc := false;

......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
