### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnPostDtldCustLedgEntriesOnAfterGetAccNo

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10507]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnPostDtldCustLedgEntriesOnAfterGetAccNo**:

[IntegrationEvent(false, false)]
    **local procedure OnPostDtldCustLedgEntriesOnAfterGetAccNo**(VAR GenJournalLine: Record "Gen. Journal Line"; VAR AccountNo: Code[20])
    begin
    end;

called from:

**local procedure PostDtldCustLedgEntries**(GenJnlLine: Record "Gen. Journal Line"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; CustPostingGr: Record "Customer Posting Group"; LedgEntryInserted: Boolean) DtldLedgEntryInserted: Boolean
    var
        TempInvPostBuf: Record "Invoice Post. Buffer" temporary;
        DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry";
        Currency: Record Currency;
        GLEntry: Record "G/L Entry";
        DtldCustLedgEntry2: Record "Detailed Cust. Ledg. Entry";
        AdjAmount: array[4] of Decimal;
        DtldCustLedgEntryNoOffset: Integer;
        SaveEntryNo: Integer;
        ReceivableAccAmtLCY: Decimal;
        ReceivableAccAmtAddCurr: Decimal;
        ExistDtldCVLedgEntryBuf: Boolean;
        FindBill: Boolean;
    begin
        if GenJnlLine."Account Type" <> GenJnlLine."Account Type"::Customer then
            exit;

if DtldCustLedgEntry.FindLast then
            DtldCustLedgEntryNoOffset := DtldCustLedgEntry."Entry No."
        else
            DtldCustLedgEntryNoOffset := 0;

DtldCVLedgEntryBuf.Reset();
        DtldCVLedgEntryBuf.SetRange("Initial Document Type", DtldCVLedgEntryBuf."Initial Document Type"::Bill);
        if DtldCVLedgEntryBuf.FindFirst() then
            FindBill := true;
        DtldCVLedgEntryBuf.Reset();
        if DtldCVLedgEntryBuf.FindSet() then begin
            if LedgEntryInserted or FindBill then begin
                SaveEntryNo := NextEntryNo;
                NextEntryNo := NextEntryNo + 1;
                NextEntryNo2 := NextEntryNo;
            end;
            repeat
                InsertDtldCustLedgEntry(GenJnlLine, DtldCVLedgEntryBuf, DtldCustLedgEntry, DtldCustLedgEntryNoOffset);
                UpdateCustLedgEntryStats(DtldCustLedgEntry."Cust. Ledger Entry No.");
                UpdateTotalAmounts(TempInvPostBuf, GenJnlLine."Dimension Set ID", DtldCVLedgEntryBuf);
                if ((DtldCVLedgEntryBuf."Amount (LCY)" <> 0) or
                    (DtldCVLedgEntryBuf."VAT Amount (LCY)" <> 0)) or
                   ((AddCurrencyCode <> '') and (DtldCVLedgEntryBuf."Additional-Currency Amount" <> 0))
                then
                    case DtldCVLedgEntryBuf."Entry Type" of
                        DtldCVLedgEntryBuf."Entry Type"::"Initial Entry":
                            if CheckCarteraPostDtldCustLE(
                                 GenJnlLine, DtldCustLedgEntry, ReceivableAccAmtLCY, ReceivableAccAmtAddCurr, false)
                            then
                                DocAmountLCY := DtldCVLedgEntryBuf."Amount (LCY)";
                        DtldCVLedgEntryBuf."Entry Type"::Application:
                            if CheckCarteraPostDtldCustLE(
                                 GenJnlLine, DtldCustLedgEntry, ReceivableAccAmtLCY, ReceivableAccAmtAddCurr, false)
                            then begin
                                GetCurrency(Currency, DtldCVLedgEntryBuf."Currency Code");
                                CheckNonAddCurrCodeOccurred(Currency.Code);
                                **//INIT INSERT
                                OnPostDtldCustLedgEntriesOnBeforeCreateGLEntry(GenJnlLine, CustPostingGr);
                                //END INSERT**
                                CreateGLEntry(
                                  GenJnlLine, CustPostingGr.GetReceivablesAccount, -DtldCVLedgEntryBuf."Amount (LCY)", 0,
                                  DtldCVLedgEntryBuf."Currency Code" = AddCurrencyCode);
                            end;
                        DtldCVLedgEntryBuf."Entry Type"::Redrawal:
                            ;
                        DtldCVLedgEntryBuf."Entry Type"::Rejection:
                            ;
                        else
                            PostDtldCustLedgEntry(GenJnlLine, DtldCVLedgEntryBuf, CustPostingGr, AdjAmount);
                    end;
            until DtldCVLedgEntryBuf.Next() = 0;
......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
