### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnVendUnrealizedVATOnAfterGetPurchVATAccounts

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10505]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnVendUnrealizedVATOnAfterGetPurchVATAccounts**:

[IntegrationEvent(false, false)]
    **local procedure OnVendUnrealizedVATOnAfterGetPurchVATAccounts**(VATEntry: Record "VAT Entry"; VATPostingSetup: Record "VAT Posting Setup"; VAR PurchVATAccount: Code[20]; VAR PurchVATUnrealAccount: Code[20]; VAR PurchReverseAccount: Code[20]; VAR PurchReverseUnrealAccount: Code[20])
    begin
    end;

called from:

**local procedure VendUnrealizedVAT**(GenJnlLine: Record "Gen. Journal Line"; var VendLedgEntry2: Record "Vendor Ledger Entry"; SettledAmount: Decimal)
    var
        VATEntry2: Record "VAT Entry";
        TaxJurisdiction: Record "Tax Jurisdiction";
        VATPostingSetup: Record "VAT Posting Setup";
        VATPart: Decimal;
        VATAmount: Decimal;
        VATBase: Decimal;
        VATAmountAddCurr: Decimal;
        VATBaseAddCurr: Decimal;
        PaidAmount: Decimal;
        TotalUnrealVATAmountFirst: Decimal;
        TotalUnrealVATAmountLast: Decimal;
        PurchVATAccount: Code[20];
        PurchVATUnrealAccount: Code[20];
        PurchReverseAccount: Code[20];
        PurchReverseUnrealAccount: Code[20];
        LastConnectionNo: Integer;
        Doc: Record "Cartera Doc.";
        ClosedDoc: Record "Closed Cartera Doc.";
        PostedDoc: Record "Posted Cartera Doc.";
        FromDocInPostedPmtOrd: Boolean;
        FromDoc: Boolean;
        VendLedgEntry3: Record "Vendor Ledger Entry";
        VendLedgEntry4: Record "Vendor Ledger Entry";
        FromJnl: Boolean;
        GLEntryNo: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeVendUnrealizedVAT(GenJnlLine, VendLedgEntry2, SettledAmount, IsHandled);
        if IsHandled then
            exit;

VendLedgEntry4.Copy(VendLedgEntry2);

FromDoc := false;
        FromDocInPostedPmtOrd := false;

Doc.SetCurrentKey(Type, "Document No.");
        Doc.SetRange(Type, Doc.Type::Payable);
        Doc.SetRange("Document No.", VendLedgEntry4."Document No.");
        ClosedDoc.SetCurrentKey(Type, "Document No.");
        ClosedDoc.SetRange(Type, ClosedDoc.Type::Payable);
        ClosedDoc.SetRange("Document No.", VendLedgEntry4."Document No.");
        ClosedDoc.SetRange("No.", VendLedgEntry4."Bill No.");
        PostedDoc.SetCurrentKey(Type, "Document No.");
        PostedDoc.SetRange(Type, PostedDoc.Type::Payable);
        PostedDoc.SetRange("Document No.", VendLedgEntry4."Document No.");
        PostedDoc.SetRange("No.", VendLedgEntry4."Bill No.");
        FromDoc := (Doc.FindFirst and (not ClosedDoc.FindFirst));
        FromDocInPostedPmtOrd := PostedDoc.FindFirst;

......
	......
	......

if VATPart > 0 then begin
                    case VATEntry2."VAT Calculation Type" of
                        VATEntry2."VAT Calculation Type"::"Normal VAT",
                        VATEntry2."VAT Calculation Type"::"Full VAT":
                            begin
                                PurchVATAccount := VATPostingSetup.GetPurchAccount(false);
                                PurchVATUnrealAccount := VATPostingSetup.GetPurchAccount(true);
                            end;
                        VATEntry2."VAT Calculation Type"::"Reverse Charge VAT":
                            begin
                                PurchVATAccount := VATPostingSetup.GetPurchAccount(false);
                                PurchVATUnrealAccount := VATPostingSetup.GetPurchAccount(true);
                                PurchReverseAccount := VATPostingSetup.GetRevChargeAccount(false);
                                PurchReverseUnrealAccount := VATPostingSetup.GetRevChargeAccount(true);
                            end;
                        VATEntry2."VAT Calculation Type"::"Sales Tax":
                            if (VATEntry2.Type = VATEntry2.Type::Purchase) and VATEntry2."Use Tax" then begin
                                TaxJurisdiction.Get(VATEntry2."Tax Jurisdiction Code");
                                PurchVATAccount := TaxJurisdiction.GetPurchAccount(false);
                                PurchVATUnrealAccount := TaxJurisdiction.GetPurchAccount(true);
                                PurchReverseAccount := TaxJurisdiction.GetRevChargeAccount(false);
                                PurchReverseUnrealAccount := TaxJurisdiction.GetRevChargeAccount(true);
                            end else begin
                                TaxJurisdiction.Get(VATEntry2."Tax Jurisdiction Code");
                                PurchVATAccount := TaxJurisdiction.GetPurchAccount(false);
                                PurchVATUnrealAccount := TaxJurisdiction.GetPurchAccount(true);
                            end;
                    end;

**//INIT INSERT
                    OnVendUnrealizedVATOnAfterGetPurchVATAccounts(VATEntry2, VATPostingSetup, PurchVATAccount, PurchVATUnrealAccount, PurchReverseAccount, PurchReverseUnrealAccount);
                    //END INSERT**

if VATPart = 1 then begin
                        VATAmount := VATEntry2."Remaining Unrealized Amount";
                        VATBase := VATEntry2."Remaining Unrealized Base";
                        VATAmountAddCurr := VATEntry2."Add.-Curr. Rem. Unreal. Amount";
                        VATBaseAddCurr := VATEntry2."Add.-Curr. Rem. Unreal. Base";
                    end else
                        CalcVendRealizedVATAmt(
                          VATBase, VATAmount, VATBaseAddCurr, VATAmountAddCurr, VATEntry2, VendLedgEntry4, VATPart);

OnVendUnrealizedVATOnBeforeInitGLEntryVAT(GenJnlLine, VATEntry2, VATAmount, VATBase, VATAmountAddCurr, VATBaseAddCurr);

......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
