### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnApplyCustLedgEntryOnBeforeUnrealizedVAT

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10516]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnApplyCustLedgEntryOnBeforeUnrealizedVAT**:

[IntegrationEvent(false, false)]
    **local procedure OnApplyCustLedgEntryOnBeforeUnrealizedVAT**(VAR GenJournalLine: Record "Gen. Journal Line"; VAR CVLedgerEntryBuffer: Record "CV Ledger Entry Buffer"; VAR CustLedgerEntry: Record "Cust. Ledger Entry")
    begin
    end;

called from:

**local procedure ApplyCustLedgEntry**(var NewCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; GenJnlLine: Record "Gen. Journal Line"; Cust: Record Customer)
    var
        OldCustLedgEntry: Record "Cust. Ledger Entry";
        OldCVLedgEntryBuf: Record "CV Ledger Entry Buffer";
        NewCustLedgEntry: Record "Cust. Ledger Entry";
        NewCVLedgEntryBuf2: Record "CV Ledger Entry Buffer";
        TempOldCustLedgEntry: Record "Cust. Ledger Entry" temporary;
        Completed: Boolean;
        AppliedAmount: Decimal;
        NewRemainingAmtBeforeAppln: Decimal;
        ApplyingDate: Date;
        PmtTolAmtToBeApplied: Decimal;
        AllApplied: Boolean;
        IsAmountToApplyCheckHandled: Boolean;
        CarteraManagement: Codeunit CarteraManagement;
    begin
        OnBeforeApplyCustLedgEntry(NewCVLedgEntryBuf, DtldCVLedgEntryBuf, GenJnlLine, Cust, IsAmountToApplyCheckHandled);
        if not IsAmountToApplyCheckHandled then
            if NewCVLedgEntryBuf."Amount to Apply" = 0 then
                exit;

AllApplied := true;
        if (GenJnlLine."Applies-to Doc. No." = '') and (GenJnlLine."Applies-to ID" = '') and
           not
           ((Cust."Application Method" = Cust."Application Method"::"Apply to Oldest") and
            GenJnlLine."Allow Application")
        then
            exit;

......
	......
	......

if (NewCustLedgEntry."Document Type" = NewCustLedgEntry."Document Type"::Bill) or
           (NewCustLedgEntry."Document Situation" <> 0)
        then begin
            if (NewCustLedgEntry."Document Situation" in [
                                                          NewCustLedgEntry."Document Situation"::"Closed Documents",
                                                          NewCustLedgEntry."Document Situation"::"Closed BG/PO"])
            then
                FromClosedDoc := true
            else
                FromClosedDoc := false;
            DocPost.UpdateReceivableDoc(
              NewCustLedgEntry, GenJnlLine, AppliedAmountLCY2 + DeltaUnrealAmount + DeltaAmountLCY,
              DocAmountLCY, RejDocAmountLCY, DiscDocAmountLCY, CollDocAmountLCY,
              DiscRiskFactAmountLCY, DiscUnriskFactAmountLCY, CollFactAmountLCY);
        end;

**//INIT INSERT
        OnApplyCustLedgEntryOnBeforeUnrealizedVAT(GenJnlLine, NewCVLedgEntryBuf, NewCustLedgEntry);
        //END INSERT**
        if GLSetup."Unrealized VAT" or
           (GLSetup."Prepayment Unrealized VAT" and NewCVLedgEntryBuf.Prepayment)
        then
        ......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
