### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnApplyCustLedgEntryOnBeforeUpdateCalcInterest

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10514]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnApplyCustLedgEntryOnBeforeUpdateCalcInterest**:

[IntegrationEvent(false, false)]
   **local procedure OnApplyCustLedgEntryOnBeforeUpdateCalcInterest**(VAR GenJournalLine: Record "Gen. Journal Line"; VAR CVLedgerEntryBuffer: Record "CV Ledger Entry Buffer"; VAR CustLedgerEntry: Record "Cust. Ledger Entry")
    begin
    end;

called from:

**local procedure ApplyCustLedgEntry**(var NewCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; GenJnlLine: Record "Gen. Journal Line"; Cust: Record Customer)
    var
        OldCustLedgEntry: Record "Cust. Ledger Entry";
        OldCVLedgEntryBuf: Record "CV Ledger Entry Buffer";
        NewCustLedgEntry: Record "Cust. Ledger Entry";
        NewCVLedgEntryBuf2: Record "CV Ledger Entry Buffer";
        TempOldCustLedgEntry: Record "Cust. Ledger Entry" temporary;
        Completed: Boolean;
        AppliedAmount: Decimal;
        NewRemainingAmtBeforeAppln: Decimal;
        ApplyingDate: Date;
        PmtTolAmtToBeApplied: Decimal;
        AllApplied: Boolean;
        IsAmountToApplyCheckHandled: Boolean;
        CarteraManagement: Codeunit CarteraManagement;
    begin
        OnBeforeApplyCustLedgEntry(NewCVLedgEntryBuf, DtldCVLedgEntryBuf, GenJnlLine, Cust, IsAmountToApplyCheckHandled);
        if not IsAmountToApplyCheckHandled then
            if NewCVLedgEntryBuf."Amount to Apply" = 0 then
                exit;

......
	......
	......

Completed := FindNextOldCustLedgEntryToApply(GenJnlLine, TempOldCustLedgEntry, NewCVLedgEntryBuf);
        until Completed;

DtldCVLedgEntryBuf.SetCurrentKey("CV Ledger Entry No.", "Entry Type");
        DtldCVLedgEntryBuf.SetRange("CV Ledger Entry No.", NewCVLedgEntryBuf."Entry No.");
        DtldCVLedgEntryBuf.SetRange(
          "Entry Type",
          DtldCVLedgEntryBuf."Entry Type"::Application);
        DtldCVLedgEntryBuf.CalcSums("Amount (LCY)", Amount);

CalcCurrencyUnrealizedGainLoss(
          NewCVLedgEntryBuf, DtldCVLedgEntryBuf, GenJnlLine, DtldCVLedgEntryBuf.Amount, NewRemainingAmtBeforeAppln);

CalcAmtLCYAdjustment(NewCVLedgEntryBuf, DtldCVLedgEntryBuf, GenJnlLine);

NewCVLedgEntryBuf."Applies-to ID" := '';
        NewCVLedgEntryBuf."Amount to Apply" := 0;

**//INIT INSERT
        OnApplyCustLedgEntryOnBeforeUpdateCalcInterest(GenJnlLine, NewCVLedgEntryBuf, NewCustLedgEntry);
        //END INSERT**
        if not NewCVLedgEntryBuf.Open then
            UpdateCalcInterest(NewCVLedgEntryBuf);

if (NewCustLedgEntry."Document Type" = NewCustLedgEntry."Document Type"::Bill) or
           (NewCustLedgEntry."Document Situation" <> 0)
        then begin
......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
