### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnApplyVendLedgEntryOnBeforeTempOldVendLedgEntryDelete

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10512]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnApplyVendLedgEntryOnBeforeTempOldVendLedgEntryDelete**:

[IntegrationEvent(false, false)]
    **local procedure OnApplyVendLedgEntryOnBeforeTempOldVendLedgEntryDelete**(VAR GenJournalLine: Record "Gen. Journal Line"; VAR VendorLedgerEntry: Record "Vendor Ledger Entry" temporary; AppliedAmount: Decimal)
    begin
    end;

called from:

**local procedure ApplyVendLedgEntry**(var NewCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; GenJnlLine: Record "Gen. Journal Line"; Vend: Record Vendor)
    var
        OldVendLedgEntry: Record "Vendor Ledger Entry";
        OldCVLedgEntryBuf: Record "CV Ledger Entry Buffer";
        NewVendLedgEntry: Record "Vendor Ledger Entry";
        NewCVLedgEntryBuf2: Record "CV Ledger Entry Buffer";
        TempOldVendLedgEntry: Record "Vendor Ledger Entry" temporary;
        Completed: Boolean;
        AppliedAmount: Decimal;
        NewRemainingAmtBeforeAppln: Decimal;
        ApplyingDate: Date;
        PmtTolAmtToBeApplied: Decimal;
        AllApplied: Boolean;
        IsAmountToApplyCheckHandled: Boolean;
    begin
        OnBeforeApplyVendLedgEntry(NewCVLedgEntryBuf, DtldCVLedgEntryBuf, GenJnlLine, Vend, IsAmountToApplyCheckHandled);
        if not IsAmountToApplyCheckHandled then
            if NewCVLedgEntryBuf."Amount to Apply" = 0 then
                exit;

AllApplied := true;
        if (GenJnlLine."Applies-to Doc. No." = '') and (GenJnlLine."Applies-to ID" = '') and
           not
           ((Vend."Application Method" = Vend."Application Method"::"Apply to Oldest") and
            GenJnlLine."Allow Application")
        then
            exit;
......
	......
	......
            OnAfterOldVendLedgEntryModify(OldVendLedgEntry);

if GLSetup."Unrealized VAT" or
               (GLSetup."Prepayment Unrealized VAT" and TempOldVendLedgEntry.Prepayment)
            then
                if (IsNotPayment(TempOldVendLedgEntry."Document Type") or
                    (TempOldVendLedgEntry."Document Type" = TempOldVendLedgEntry."Document Type"::Bill)) and
                   (NewCVLedgEntryBuf."Document Type" <> 0) and
                   (not (TempOldVendLedgEntry."Document Status" = TempOldVendLedgEntry."Document Status"::Redrawn)) and
                   (not FromClosedDoc)
                then begin
                    TempOldVendLedgEntry.RecalculateAmounts(
                      NewCVLedgEntryBuf."Currency Code", TempOldVendLedgEntry."Currency Code", NewCVLedgEntryBuf."Posting Date");
                    OnApplyVendLedgEntryOnAfterRecalculateAmounts(TempOldVendLedgEntry, OldVendLedgEntry, NewCVLedgEntryBuf, GenJnlLine);
                    VendUnrealizedVAT(
                      GenJnlLine,
                      TempOldVendLedgEntry,
                      CurrExchRate.ExchangeAmount(
                        AppliedAmount, NewCVLedgEntryBuf."Currency Code",
                        TempOldVendLedgEntry."Currency Code", NewCVLedgEntryBuf."Posting Date"));
                end;

**//INIT INSERT
            OnApplyVendLedgEntryOnBeforeTempOldVendLedgEntryDelete(GenJnlLine, TempOldVendLedgEntry, AppliedAmount);
            //END INSERT**
            TempOldVendLedgEntry.Delete();

Completed := FindNextOldVendLedgEntryToApply(GenJnlLine, TempOldVendLedgEntry, NewCVLedgEntryBuf);
        until Completed;
        ......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
