### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnBeforeIsCustBillDoc

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10517]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnBeforeIsCustBillDoc** with a local boolean variable "IsHandled" and "IsBillDoc":

[IntegrationEvent(false, false)]
    **local procedure OnBeforeIsCustBillDoc**(CustLedgerEntry: Record "Cust. Ledger Entry"; IsHandled: Boolean; IsBillDoc: Boolean)
    begin
    end;

called from:

**local procedure IsCustBillDoc**(UnrealCustLedgEntry: Record "Cust. Ledger Entry"): Boolean
    var
        IsHandled: Boolean;
        IsBillDoc: Boolean;
    begin
        **//INIT INSERT
        OnBeforeIsCustBillDoc(UnrealCustLedgEntry, IsHandled, IsBillDoc);
        IF IsHandled THEN
            EXIT(IsBillDoc);
        //END INSERT**
        exit(UnrealCustLedgEntry."Document Type" = UnrealCustLedgEntry."Document Type"::Bill);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
