### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnVendFindVATSetupOnBeforePurchLineApplyFilters

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10510]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnVendFindVATSetupOnBeforePurchLineApplyFilters** with a local boolean variable "IsHandled":

[IntegrationEvent(false, false)]
    **local procedure OnVendFindVATSetupOnBeforePurchLineApplyFilters**(VAR PurchInvLine: Record "Purch. Inv. Line"; VAR VendLedgerEntry: Record "Vendor Ledger Entry"; VAR IsHandled: Boolean);
    begin
    end;

called from:

**procedure VendFindVATSetup**(var VATSetup: Record "VAT Posting Setup"; VendLedgEntry4: Record "Vendor Ledger Entry"; IsFromJournal: Boolean): Boolean
    var
        Vendor: Record Vendor;
        ProdPostingGroup: Code[20];
        PurchLine2: Record "Purch. Inv. Line";
        Text1100003: Label 'Unrealized VAT Type must be "Percentage" in VAT Posting Setup.';
        ErrorMessage: Boolean;
        ExistsVATNoReal: Boolean;
        GLEntry: Record "G/L Entry";
        BusPostingGroup: Code[20];
        IsHandled: Boolean;
    begin
        ErrorMessage := false;
        ExistsVATNoReal := false;
        Vendor.Get(VendLedgEntry4."Vendor No.");

VATSetup.SetCurrentKey("VAT Bus. Posting Group", "VAT Prod. Posting Group");
        if IsFromJournal then begin
            GLEntry.SetCurrentKey("Document No.", "Posting Date");
            GLEntry.SetRange("Document No.", VendLedgEntry4."Document No.");
            if GLEntry.FindFirst then begin
                BusPostingGroup := GLEntry."VAT Bus. Posting Group";
                ProdPostingGroup := GLEntry."VAT Prod. Posting Group";
                VATSetup.SetRange("VAT Bus. Posting Group", BusPostingGroup);
                VATSetup.SetRange("VAT Prod. Posting Group", ProdPostingGroup);
                if VATSetup.Find('-') and (VATSetup."Unrealized VAT Type" >= VATSetup."Unrealized VAT Type"::Percentage) then
                    if VATSetup."Unrealized VAT Type" > VATSetup."Unrealized VAT Type"::Percentage then
                        ErrorMessage := true
                    else
                        ExistsVATNoReal := true;
            end;
        end else begin
            PurchLine2.SetRange("Document No.", VendLedgEntry4."Document No.");
            PurchLine2.SetFilter(Type, '<>%1', 0);
            **//INIT INSERT
            IsHandled := false;
            OnVendFindVATSetupOnBeforePurchLineApplyFilters(PurchLine2, VendLedgEntry4, IsHandled);
            IF NOT IsHandled THEN
            //END INSERT**
                PurchLine2.Find('-');
            BusPostingGroup := PurchLine2."VAT Bus. Posting Group";
            VATSetup.SetRange("VAT Bus. Posting Group", BusPostingGroup);
        ......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
