### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnBeforeIsVendBillDoc

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10518]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnBeforeIsVendBillDoc** with a local boolean variable "IsHandled" and "IsBillDoc":

[IntegrationEvent(false, false)]
    **local procedure OnBeforeIsVendBillDoc**(VendorLedgerEntry: Record "Vendor Ledger Entry"; IsHandled: Boolean; IsBillDoc: Boolean)
    begin
    end;

called from:

**local procedure IsVendBillDoc**(UnrealVendLedgEntry: Record "Vendor Ledger Entry"): Boolean
    var
        IsHandled: Boolean;
        IsBillDoc: Boolean;
    begin
        **//INIT INSERT
        OnBeforeIsVendBillDoc(UnrealVendLedgEntry, IsHandled, IsBillDoc);
        IF IsHandled THEN
            EXIT(IsBillDoc);
        //END INSERT**
        exit(UnrealVendLedgEntry."Document Type" = UnrealVendLedgEntry."Document Type"::Bill);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
