### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnBeforePostDeferralPostBuffer

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10519]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnBeforePostDeferralPostBuffer**:

[IntegrationEvent(false, false)]
    **local procedure OnBeforePostDeferralPostBuffer**(VAR GenJournalLine: Record "Gen. Journal Line")
    begin
    end;

called from:

**local procedure PostDeferralPostBuffer**(GenJournalLine: Record "Gen. Journal Line")
    var
        DeferralPostBuffer: Record "Deferral Posting Buffer";
        GLEntry: Record "G/L Entry";
        PostDate: Date;
    begin
        **//INIT INSERT
        OnBeforePostDeferralPostBuffer(GenJournalLine);
        //END INSERT**
        with GenJournalLine do begin
            if "Source Type" = "Source Type"::Customer then
                DeferralDocType := DeferralDocType::Sales
            else
                DeferralDocType := DeferralDocType::Purchase;

DeferralPostBuffer.SetRange("Deferral Doc. Type", DeferralDocType);
            DeferralPostBuffer.SetRange("Document No.", "Document No.");
            DeferralPostBuffer.SetRange("Deferral Line No.", "Deferral Line No.");
            OnPostDeferralPostBufferOnAfterSetFilters(DeferralPostBuffer, GenJournalLine);
......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
