### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnApplyVendLedgEntryOnBeforeUnrealizedVAT

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10515]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnApplyVendLedgEntryOnBeforeUnrealizedVAT**:

[IntegrationEvent(false, false)]
    **local procedure OnApplyVendLedgEntryOnBeforeUnrealizedVAT**(VAR GenJournalLine: Record "Gen. Journal Line"; VAR CVLedgerEntryBuffer: Record "CV Ledger Entry Buffer"; VAR VendorLedgerEntry: Record "Vendor Ledger Entry")
    begin
    end;

called from:

**local procedure ApplyVendLedgEntry**(var NewCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; GenJnlLine: Record "Gen. Journal Line"; Vend: Record Vendor)
    var
        OldVendLedgEntry: Record "Vendor Ledger Entry";
        OldCVLedgEntryBuf: Record "CV Ledger Entry Buffer";
        NewVendLedgEntry: Record "Vendor Ledger Entry";
        NewCVLedgEntryBuf2: Record "CV Ledger Entry Buffer";
        TempOldVendLedgEntry: Record "Vendor Ledger Entry" temporary;
        Completed: Boolean;
        AppliedAmount: Decimal;
        NewRemainingAmtBeforeAppln: Decimal;
        ApplyingDate: Date;
        PmtTolAmtToBeApplied: Decimal;
        AllApplied: Boolean;
        IsAmountToApplyCheckHandled: Boolean;
    begin
        OnBeforeApplyVendLedgEntry(NewCVLedgEntryBuf, DtldCVLedgEntryBuf, GenJnlLine, Vend, IsAmountToApplyCheckHandled);
        if not IsAmountToApplyCheckHandled then
            if NewCVLedgEntryBuf."Amount to Apply" = 0 then
                exit;

AllApplied := true;

......
	......
	......

NewCVLedgEntryBuf."Applies-to ID" := '';
        NewCVLedgEntryBuf."Amount to Apply" := 0;
        if (NewVendLedgEntry."Document Type" = NewVendLedgEntry."Document Type"::Bill) or
           (NewVendLedgEntry."Document Situation" <> 0)
        then begin
            FromClosedDoc :=
              NewVendLedgEntry."Document Situation" in [NewVendLedgEntry."Document Situation"::"Closed Documents",
                                                        NewVendLedgEntry."Document Situation"::"Closed BG/PO"];
            DocPost.UpdatePayableDoc(
              NewVendLedgEntry, GenJnlLine, DocAmountLCY, AppliedAmountLCY2 + DeltaUnrealAmount + DeltaAmountLCY,
              DocLock, CollDocAmountLCY);
        end;
        **//INIT INSERT
        OnApplyVendLedgEntryOnBeforeUnrealizedVAT(GenJnlLine, NewCVLedgEntryBuf, NewVendLedgEntry);
        //END INSERT**
        if GLSetup."Unrealized VAT" or
           (GLSetup."Prepayment Unrealized VAT" and NewCVLedgEntryBuf.Prepayment)
        then
        ......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
