### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnAfterPostDeferralPostBuffer

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10520]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnAfterPostDeferralPostBuffer**:

[IntegrationEvent(false, false)]
    **local procedure OnAfterPostDeferralPostBuffer**(VAR GenJournalLine: Record "Gen. Journal Line")
    begin
    end;

called from:

**local procedure PostDeferralPostBuffer**(GenJournalLine: Record "Gen. Journal Line")
    var
        DeferralPostBuffer: Record "Deferral Posting Buffer";
        GLEntry: Record "G/L Entry";
        PostDate: Date;
    begin
        with GenJournalLine do begin
            if "Source Type" = "Source Type"::Customer then
                DeferralDocType := DeferralDocType::Sales
            else
                DeferralDocType := DeferralDocType::Purchase;

......
	......
	......

until DeferralPostBuffer.Next() = 0;
                DeferralPostBuffer.DeleteAll();
            end;
        end;
        **//INIT INSERT
        OnAfterPostDeferralPostBuffer(GenJournalLine);
        //END INSERT**
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
