### ISSUE TITLE
[Event Request] Report 94 Close Income Statement - OnBeforeGenJnlPost

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10528]
We need a new event in Report 94 "Close Income Statement" named **OnBeforeGenJnlPost** with a local boolean variable "IsHandled":

[IntegrationEvent(false, false)]
    **local procedure OnBeforeGenJnlPost**(VAR GenJournalLine: Record "Gen. Journal Line"; VAR IsHandled: Boolean);
    begin
    end;

called from:

**trigger OnPostReport()**
    var
        UpdateAnalysisView: Codeunit "Update Analysis View";
        IsHandled: Boolean;
    begin
        InsBalLines;

if not GenJnlLine.Find('-') then
            exit;

**//INIT INSERT
        OnBeforeGenJnlPost(GenJnlLine, IsHandled);
if IsHandled then
            exit;
        //END INSERT**

Window.Close;
        Window.Open(
          Text1100100);

......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
