### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnPostVendOnBeforeApplyVendLedgEntry

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10522]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnPostVendOnBeforeApplyVendLedgEntry**:

[IntegrationEvent(false, false)]
    **local procedure OnPostVendOnBeforeApplyVendLedgEntry**(VAR GenJournalLine: Record "Gen. Journal Line"; VAR CVLedgerEntryBuffer: Record "CV Ledger Entry Buffer"; VAR FromBillSettlement: Boolean)
    begin
    end;

called from:

**local procedure PostVend**(GenJnlLine: Record "Gen. Journal Line"; Balancing: Boolean)
    var
        Vend: Record Vendor;
        VendPostingGr: Record "Vendor Posting Group";
        VendLedgEntry: Record "Vendor Ledger Entry";
        CVLedgEntryBuf: Record "CV Ledger Entry Buffer";
        TempDtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer" temporary;
        DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry";
        PurchSetup: Record "Purchases & Payables Setup";
        PayablesAccount: Code[20];
        DtldLedgEntryInserted: Boolean;
        CheckExtDocNoHandled: Boolean;
    begin
        OnBeforePostVend(GenJnlLine);

AppliesToDocType := 0;

PurchSetup.Get();

......
	......
	......

// Check the document no.
            if "Recurring Method" = 0 then
                if IsNotPayment("Document Type") then begin
                    GenJnlCheckLine.CheckPurchDocNoIsNotUsed(GenJnlLine);
                    OnBeforeCheckPurchExtDocNo(GenJnlLine, VendLedgEntry, CVLedgEntryBuf, CheckExtDocNoHandled);
                    if not CheckExtDocNoHandled then
                        CheckPurchExtDocNo(GenJnlLine);
                end;

OriginalEntryExist := IsOriginalEntryExist(GenJnlLine);
            **//INIT INSERT
            OnPostVendOnBeforeApplyVendLedgEntry(GenJnlLine, CVLedgEntryBuf, FromBillSettlement);
            //END INSERT**
            // Post application
            ApplyVendLedgEntry(CVLedgEntryBuf, TempDtldCVLedgEntryBuf, GenJnlLine, Vend);

if ("Applies-to ID" = '') and
               ("Applies-to Doc. Type" = "Applies-to Doc. Type"::" ")
            then
                "Applies-to Doc. Type" := AppliesToDocType;
......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
