### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnVendPostApplyVendLedgEntryOnAfterVendLedgEntryTransferFields

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10524]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnVendPostApplyVendLedgEntryOnAfterVendLedgEntryTransferFields**:

[IntegrationEvent(false, false)]
    **local procedure OnVendPostApplyVendLedgEntryOnAfterVendLedgEntryTransferFields**(VAR VendorLedgerEntry: Record "Vendor Ledger Entry"; VAR GenJournalLine: Record "Gen. Journal Line")
    begin
    end;

called from:

**procedure VendPostApplyVendLedgEntry**(var GenJnlLinePostApply: Record "Gen. Journal Line"; var VendLedgEntryPostApply: Record "Vendor Ledger Entry")
    var
        Vend: Record Vendor;
        VendPostingGr: Record "Vendor Posting Group";
        VendLedgEntry: Record "Vendor Ledger Entry";
        DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry";
        TempDtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer" temporary;
        CVLedgEntryBuf: Record "CV Ledger Entry Buffer";
        GenJnlLine: Record "Gen. Journal Line";
        DtldLedgEntryInserted: Boolean;
    begin
        OnBeforeVendPostApplyVendLedgEntry(GenJnlLinePostApply);

GenJnlLine := GenJnlLinePostApply;
        VendLedgEntry.TransferFields(VendLedgEntryPostApply);
        **//INIT INSERT
        OnVendPostApplyVendLedgEntryOnAfterVendLedgEntryTransferFields(VendLedgEntry, GenJnlLine);
        //END INSERT**
        with GenJnlLine do begin
            "Source Currency Code" := VendLedgEntryPostApply."Currency Code";
            "Applies-to ID" := VendLedgEntryPostApply."Applies-to ID";

GenJnlCheckLine.RunCheck(GenJnlLine);
......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
