### ISSUE TITLE
[Event Request] Report 94 Close Income Statement - OnInsBalLinesOnBeforeGenJnlLineInsert

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10529]
We need a new event in Report 94 "Close Income Statement" named **OnInsBalLinesOnBeforeGenJnlLineInsert**:

[IntegrationEvent(false, false)]
    **local procedure OnInsBalLinesOnBeforeGenJnlLineInsert**(VAR GenJournalLine: Record "Gen. Journal Line"; BalLineBuffer: Record "Inc. Stmt. Clos. Buffer" temporary);
    begin
    end;

called from:

**procedure InsBalLines()**
    begin
        if BalLineBuffer.Find('-') then
            repeat
                GenJnlLine."Line No." := GenJnlLine."Line No." + 10000;
                GenJnlLine."Account No." := BalLineBuffer."Account No.";
                GenJnlLine."Source Code" := SourceCodeSetup."Close Income Statement";
                GenJnlLine."Reason Code" := GenJnlBatch."Reason Code";
                GenJnlLine."Additional-Currency Posting" :=
                  GenJnlLine."Additional-Currency Posting"::None;
                if GLSetup."Additional Reporting Currency" <> '' then begin
                    GenJnlLine."Source Currency Code" := GLSetup."Additional Reporting Currency";
                    if (GenJnlLine.Amount = 0) and
                       (GenJnlLine."Source Currency Amount" <> 0)
                    then begin
                        GenJnlLine.Validate(Amount, -BalLineBuffer."Additional-Currency Amount");
                        GenJnlLine.Validate("Source Currency Amount", 0);
                        GenJnlLine."Additional-Currency Posting" :=
                          GenJnlLine."Additional-Currency Posting"::"Additional-Currency Amount Only";
                    end else begin
                        GenJnlLine.Validate(Amount, -BalLineBuffer.Amount);
                        GenJnlLine.Validate("Source Currency Amount", -BalLineBuffer."Additional-Currency Amount");
                    end;
                end else
                    GenJnlLine.Validate(Amount, -BalLineBuffer.Amount);
                GenJnlLine."System-Created Entry" := true;
                **//INIT INSERT
                OnInsBalLinesOnBeforeGenJnlLineInsert(GenJnlLine, BalLineBuffer);
                //END INSERT**
                GenJnlLine.Insert();
            until BalLineBuffer.Next = 0;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
