### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnPostCustOnBeforeApplyCustLedgEntry

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10521]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnPostCustOnBeforeApplyCustLedgEntry**:

[IntegrationEvent(false, false)]
    **local procedure OnPostCustOnBeforeApplyCustLedgEntry**(VAR GenJournalLine: Record "Gen. Journal Line"; VAR CVLedgerEntryBuffer: Record "CV Ledger Entry Buffer"; VAR FromBillSettlement: Boolean)
    begin
    end;

called from:

**local procedure PostCust**(var GenJnlLine: Record "Gen. Journal Line"; Balancing: Boolean)
    var
        LineFeeNoteOnReportHist: Record "Line Fee Note on Report Hist.";
        Cust: Record Customer;
        CustPostingGr: Record "Customer Posting Group";
        CustLedgEntry: Record "Cust. Ledger Entry";
        CVLedgEntryBuf: Record "CV Ledger Entry Buffer";
        TempDtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer" temporary;
        DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry";
        SalesSetup: Record "Sales & Receivables Setup";
        ReceivablesAccount: Code[20];
        DtldLedgEntryInserted: Boolean;
    begin
        AppliesToDocType := 0;

SalesSetup.Get();
        with GenJnlLine do begin
            DocAmountLCY := 0;
            DiscDocAmountLCY := 0;
            CollDocAmountLCY := 0;
            RejDocAmountLCY := 0;
            DiscRiskFactAmountLCY := 0;
            DiscUnriskFactAmountLCY := 0;
            CollFactAmountLCY := 0;
            TempRejCustLedgEntry.Reset();
            TempRejCustLedgEntry.DeleteAll();

......
	......
	......

// Check the document no.
            if "Recurring Method" = 0 then
                if IsNotPayment("Document Type") then begin
                    GenJnlCheckLine.CheckSalesDocNoIsNotUsed(GenJnlLine);
                    CheckSalesExtDocNo(GenJnlLine);
                end;
            OriginalEntryExist := IsOriginalEntryExist(GenJnlLine);

**//INIT INSERT
            OnPostCustOnBeforeApplyCustLedgEntry(GenJnlLine, CVLedgEntryBuf, FromBillSettlement);
            //END INSERT**

// Post application
            ApplyCustLedgEntry(CVLedgEntryBuf, TempDtldCVLedgEntryBuf, GenJnlLine, Cust);

if ("Applies-to ID" = '') and
               ("Applies-to Doc. Type" = "Applies-to Doc. Type"::" ")
            then
                "Applies-to Doc. Type" := AppliesToDocType;
......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
