### ISSUE TITLE
[Event Request] Codeunit 7000005 Invoice-Split Payment - OnBeforeSplitPurchInvTestPaymentMethod

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10526]
We need a new event in Codeunit 7000005 "Invoice-Split Payment" named **OnBeforeSplitPurchInvTestPaymentMethod** with a local boolean variable "IsHandled":

[IntegrationEvent(false, false)]
    **local procedure OnBeforeSplitPurchInvTestPaymentMethod**(VAR PurchHeader: Record "Purchase Header"; VAR PaymentMethod: Record "Payment Method"; VAR PaymentTerms: Record "Payment Terms"; VAR IsHandled: Boolean)
    begin
    end;

called from (two calls):

**procedure SplitPurchInv**(var PurchHeader: Record "Purchase Header"; var VendLedgEntry: Record "Vendor Ledger Entry"; var Window: Dialog; SourceCode: Code[10]; GenJnlLineExtDocNo: Code[35]; GenJnlLineDocNo: Code[20]; VATAmount: Decimal)
    var
        VATPostingSetup: Record "VAT Posting Setup";
        BillNo: Integer;
        IsHandled: Boolean;
    begin
        with PurchHeader do begin
            if not PaymentMethod.Get("Payment Method Code") then
                exit;
            if (not PaymentMethod."Create Bills") and (not PaymentMethod."Invoices to Cartera") then
                exit;
            **//INIT INSERT
            IsHandled := FALSE;
            OnBeforeSplitPurchInvTestPaymentMethod(PurchHeader, PaymentMethod, PaymentTerms, IsHandled);
            IF NOT IsHandled THEN
            //END INSERT**
                if PaymentMethod."Create Bills" and ("Document Type" = "Document Type"::"Credit Memo") then
                    Error(
                      Text1100000,
                      FieldCaption("Payment Method Code"));

if "Currency Code" = '' then
                CurrencyFactor := 1
            else
                CurrencyFactor := "Currency Factor";

GLSetup.Get();
            PurchSetup.Get();
            TestField("Payment Terms Code");
            PaymentTerms.Get("Payment Terms Code");
            PaymentTerms.CalcFields("No. of Installments");
            if PaymentTerms."No. of Installments" = 0 then
                PaymentTerms."No. of Installments" := 1;
            **//INIT INSERT
            IsHandled := FALSE;
            OnBeforeSplitPurchInvTestPaymentMethod(PurchHeader, PaymentMethod, PaymentTerms, IsHandled);
            IF NOT IsHandled THEN
            //END INSERT**
                if PaymentMethod."Invoices to Cartera" and (PaymentTerms."No. of Installments" > 1) then
                    Error(
                      Text1100001,
                      PaymentTerms.FieldCaption("No. of Installments"),
                      PaymentMethod.FieldCaption("Invoices to Cartera"),
                      PaymentMethod.TableCaption);
            VendLedgEntry.Find('+');
            VendLedgEntry.CalcFields("Remaining Amount", "Remaining Amt. (LCY)");
            if VendLedgEntry."Remaining Amount" = 0 then
                exit;
            TotalAmount := VendLedgEntry."Remaining Amount";
            TotalAmountLCY := VendLedgEntry."Remaining Amt. (LCY)";
            RemainingAmount := VendLedgEntry."Remaining Amount";
            RemainingAmountLCY := VendLedgEntry."Remaining Amt. (LCY)";

// close invoice entry
            if PaymentMethod."Create Bills" then begin
......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
