### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnCustPostApplyCustLedgEntryOnAfterCustLedgEntryTransferFields

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10523]
We need a new event in Codeunit 12 "Gen. Jnl.-Post Line" named **OnCustPostApplyCustLedgEntryOnAfterCustLedgEntryTransferFields**:

[IntegrationEvent(false, false)]
    **local procedure OnCustPostApplyCustLedgEntryOnAfterCustLedgEntryTransferFields**(VAR CustLedgerEntry: Record "Cust. Ledger Entry"; VAR GenJournalLine: Record "Gen. Journal Line")
    begin
    end;

called from:

**procedure CustPostApplyCustLedgEntry**(var GenJnlLinePostApply: Record "Gen. Journal Line"; var CustLedgEntryPostApply: Record "Cust. Ledger Entry")
    var
        Cust: Record Customer;
        CustPostingGr: Record "Customer Posting Group";
        CustLedgEntry: Record "Cust. Ledger Entry";
        DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry";
        TempDtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer" temporary;
        CVLedgEntryBuf: Record "CV Ledger Entry Buffer";
        GenJnlLine: Record "Gen. Journal Line";
        DtldLedgEntryInserted: Boolean;
    begin
        OnBeforeCustPostApplyCustLedgEntry(GenJnlLinePostApply);

GenJnlLine := GenJnlLinePostApply;
        CustLedgEntry.TransferFields(CustLedgEntryPostApply);
        **//INIT INSERT
        OnCustPostApplyCustLedgEntryOnAfterCustLedgEntryTransferFields(CustLedgEntry, GenJnlLine);
        //END INSERT**
        with GenJnlLine do begin
            "Source Currency Code" := CustLedgEntryPostApply."Currency Code";
            "Applies-to ID" := CustLedgEntryPostApply."Applies-to ID";

GenJnlCheckLine.RunCheck(GenJnlLine);

......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
