### ISSUE TITLE
[Event Request] Codeunit 7000000 CarteraManagement - OnVendUnrealizedVATOnBeforeVATEntryModify

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10525]
We need a new event in Codeunit 7000000 "CarteraManagement" named **OnVendUnrealizedVATOnBeforeVATEntryModify**:

[IntegrationEvent(false, false)]
    **local procedure OnVendUnrealizedVATOnBeforeVATEntryModifY**(VAR VATEntry: Record "VAT Entry"; VendorLedgerEntry: Record "Vendor Ledger Entry"; GenJournalLine: Record "Gen. Journal Line")
    begin
    end;

called from:

**local procedure VendUnrealizedVAT**(var VendLedgEntry2: Record "Vendor Ledger Entry"; SettledAmount: Decimal; GenJnlLine: Record "Gen. Journal Line"; var ExistVATEntry: Boolean; var FirstVATEntryNo: Integer; var LastVATEntryNo: Integer; var NoRealVATBuffer: Record "BG/PO Post. Buffer"; PostedDocumentNo: Code[20])
    var
        VATEntry: Record "VAT Entry";
        VATEntry2: Record "VAT Entry";
        VATEntry3: Record "VAT Entry";
        PurchInvHeader: Record "Purch. Inv. Header";
        PaymentTerms: Record "Payment Terms";
        VATPart: Decimal;
        VATAmount: Decimal;
        VATBase: Decimal;
        VATAmountAddCurr: Decimal;
        VATBaseAddCurr: Decimal;
        CurrencyFactor: Decimal;
        PurchVATAccount: Code[20];
        PurchVATUnrealAccount: Code[20];
        LastConnectionNo: Integer;
        Test1: Boolean;
        Test2: Boolean;
        PaymentTermsCode: Code[20];
        ReverseChrgVATAcc: Code[20];
        ReverseChrgVATUnrealAcc: Code[20];
    begin
        OnBeforeVendUnrealizedVAT(
          VendLedgEntry2, SettledAmount, GenJnlLine, ExistVATEntry, FirstVATEntryNo, LastVATEntryNo,
          NoRealVATBuffer, PostedDocumentNo, PaymentTermsCode, VATPostingSetup);

if PostedDocumentNo <> '' then begin
            PurchInvHeader.Get(PostedDocumentNo);
            PaymentTermsCode := PurchInvHeader."Payment Terms Code";
        end;

......
	......
	......

VATEntry."User ID" := UserId;
                        VATEntry."Source Code" := GenJnlLine."Source Code";
                        VATEntry."Reason Code" := GenJnlLine."Reason Code";
                        VATEntry."Closed by Entry No." := 0;
                        VATEntry.Closed := false;
                        VATEntry."Transaction No." := VendLedgEntry2."Transaction No.";
                        VATEntry."Unrealized VAT Entry No." := VATEntry2."Entry No.";
                        VATEntry.UpdateRates(VATPostingSetup);
                        Test1 := VATEntry.Insert();

VATEntry2."Remaining Unrealized Amount" :=
                          VATEntry2."Remaining Unrealized Amount" - VATEntry.Amount;
                        VATEntry2."Remaining Unrealized Base" :=
                          VATEntry2."Remaining Unrealized Base" - VATEntry.Base;
                        VATEntry2."Add.-Curr. Rem. Unreal. Amount" :=
                          VATEntry2."Add.-Curr. Rem. Unreal. Amount" - VATEntry."Additional-Currency Amount";
                        VATEntry2."Add.-Curr. Rem. Unreal. Base" :=
                          VATEntry2."Add.-Curr. Rem. Unreal. Base" - VATEntry."Additional-Currency Base";

**//INIT INSERT
                        OnVendUnrealizedVATOnBeforeVATEntryModifY(VATEntry, VendLedgEntry2, GenJnlLine);
                        //END INSERT**

Test2 := VATEntry2.Modify();
                        LastVATEntryNo := VATEntryNo;
                    end;
                end;
......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
