### ISSUE TITLE
[Event Modification] Codeunit 80 Sales.-Post - OnAfterPostSalesDoc

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10539]
Hi, would it be possible to modify the event OnAfterPostSalesDoc in codeunit 80 SalesPost to insert SalesCrMemoHeader and SalesInvHeader parameters, like this :
![image](https://user-images.githubusercontent.com/76154006/104008393-aedd6580-51a9-11eb-907b-b11ed3bf6ac3.png)
![image](https://user-images.githubusercontent.com/76154006/104008670-054aa400-51aa-11eb-9b6f-7170c0530b64.png)
Thanks

**Comment by RomanZanizdra** [comment]
Hi @Herodoteux . There are SalesInvHeader."No." and SalesCrMemoHeader."No." in this event. Why you just cannot get headers by their numbers in your code?

**Comment by Herodoteux** [comment]
Yes I can do that, sorry for the inconvenience. I find the solution with your advice. 
Thanks
