### ISSUE TITLE
[Event Request] Report 595 Adjust Exchange Rates - OnBeforePostGenJnlLine

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10530]
We need a new event in Report 595 "Adjust Exchange Rates" named **OnBeforePostGenJnlLine**:

[IntegrationEvent(false, false)]
    **local procedure OnBeforePostGenJnlLine**(VAR GenJournalLine: Record "Gen. Journal Line");
    begin
    end;

called from:

**local procedure PostGenJnlLine**(var GenJnlLine: Record "Gen. Journal Line"; var DimSetEntry: Record "Dimension Set Entry"): Integer
    begin
        GenJnlLine."Shortcut Dimension 1 Code" := GetGlobalDimVal(GLSetup."Global Dimension 1 Code", DimSetEntry);
        GenJnlLine."Shortcut Dimension 2 Code" := GetGlobalDimVal(GLSetup."Global Dimension 2 Code", DimSetEntry);
        GenJnlLine."Dimension Set ID" := DimMgt.GetDimensionSetID(TempDimSetEntry);
        **//INIT INSERT
        OnBeforePostGenJnlLine(GenJnlLine);
        //END INSERT**
        GenJnlPostLine.Run(GenJnlLine);
        exit(GenJnlPostLine.GetNextTransactionNo);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
