### ISSUE TITLE
[Event Request] Codeunit 13636 OIOUBL-Export Sales Invoice

### ISSUE THREAD

**Issue by AlexanderPallesen** [microsoft/ALAppExtensions#10534]
We would like to have the possibility to overrule the payment means inserted in the OIOUBL file.

In order to do that we would like the following publishing event in Codeunit 13636:
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertPaymentMeans(var InvoiceElement: XmlElement; SalesInvoiceHeader: Record "Sales Invoice Header"; var PaymentMeansInserted; Boolean)
begin
end; 

Called from procedure CreateXML:
...
        // Invoice->Delivery
        DeliveryAddress.Address := SalesInvoiceHeader."Ship-to Address";
        DeliveryAddress."Address 2" := SalesInvoiceHeader."Ship-to Address 2";
        DeliveryAddress.City := SalesInvoiceHeader."Ship-to City";
        DeliveryAddress."Post Code" := SalesInvoiceHeader."Ship-to Post Code";
        DeliveryAddress."Country/Region Code" := SalesInvoiceHeader."Ship-to Country/Region Code";
        OIOUBLXMLGenerator.InsertDelivery(XMLCurrNode, DeliveryAddress, SalesInvoiceHeader."Shipment Date");

        // Invoice->PaymentMeans
        **OnBeforeInsertPaymentMeans(XMLCurrNode; SalesInvoiceHeader; PaymentMeansInserted);**
        **if not PaymentMeansInserted then**
        OIOUBLXMLGenerator.InsertPaymentMeans(XMLCurrNode, SalesInvoiceHeader."Due Date");

        // Invoice->PaymentTerms
        SalesInvLine2.RESET();
        SalesInvLine2.COPY(SalesInvLine);
...

Regards
Alexander

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
