### ISSUE TITLE
[Event Request] Codeunit 10750 SII XML Creator - OnBeforeGenerateXML

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10533]
We need to change the parameters of procedure of issue #5257:

**//BEFORE
    local procedure OnBeforeGenerateXML(LedgerEntry : Variant;VAR XMLDocOut : DotNet "System.Xml.XmlDocument";UploadType : Option;IsCreditMemoRemoval : Boolean;VAR IsHandled : Boolean;VAR Result : Boolean)
    //AFTER
    local procedure OnBeforeGenerateXML(LedgerEntry: Variant; var XMLDocOut: DotNet XmlDocument; UploadType: Option; IsCreditMemoRemoval: Boolean; RetryAccepted: Boolean; SIIVersion: Option; var ResultValue: Boolean; var IsHandled: Boolean)**

called from:

**procedure GenerateXml**(LedgerEntry: Variant; var XMLDocOut: DotNet XmlDocument; UploadType: Option; IsCreditMemoRemoval: Boolean): Boolean
    var
        CustLedgerEntry: Record "Cust. Ledger Entry";
        VendorLedgerEntry: Record "Vendor Ledger Entry";
        DetailedCustLedgEntry: Record "Detailed Cust. Ledg. Entry";
        DetailedVendorLedgEntry: Record "Detailed Vendor Ledg. Entry";
        RecRef: RecordRef;
        IsHandled: Boolean;
        ResultValue: Boolean;
    begin
        IsHandled := false;
        **//BEFORE
        OnBeforeGenerateXML(LedgerEntry, XMLDocOut, UploadType, IsCreditMemoRemoval, ResultValue, IsHandled);
        //AFTER        
        OnBeforeGenerateXML(LedgerEntry, XMLDocOut, UploadType, IsCreditMemoRemoval, RetryAccepted, SIIVersion, ResultValue, IsHandled);**
        IF IsHandled THEN
            EXIT(ResultValue);

......
	......
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
