### ISSUE TITLE
[Event Request] Report 5688 Cancel FA Ledger Entries - OnBeforeInsertGenJnlLine

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10531]
We need a new event in Report 5688 "Cancel FA Ledger Entries" named **OnBeforeInsertGenJnlLine**:

[IntegrationEvent(false, false)]
    **local procedure OnBeforeInsertGenJnlLine**(VAR GenJnlLine: Record "Gen. Journal Line"; FALedgEntry: Record "FA Ledger Entry"; VAR BalAccount: Boolean)
    begin
    end;

called from:

**local procedure InsertGenJnlLine**(var FALedgEntry: Record "FA Ledger Entry")
    var
        FAInsertGLAcc: Codeunit "FA Insert G/L Account";
    begin
        if FirstGenJnl then begin
            GenJnlLine.LockTable();
            FAJnlSetup.GenJnlName(DeprBook, GenJnlLine, GenJnlNextLineNo);
            NoSeries2 := FAJnlSetup.GetGenNoSeries(GenJnlLine);
            if DocumentNo = '' then
                DocumentNo2 := FAJnlSetup.GetGenJnlDocumentNo(GenJnlLine, GetPostingDate(FALedgEntry."FA Posting Date"), true)
            else
                DocumentNo2 := DocumentNo;
        end;
        FirstGenJnl := false;
        with GenJnlLine do begin
            FALedgEntry.MoveToGenJnl(GenJnlLine);
            "Shortcut Dimension 1 Code" := FALedgEntry."Global Dimension 1 Code";
            "Shortcut Dimension 2 Code" := FALedgEntry."Global Dimension 2 Code";
            "Dimension Set ID" := FALedgEntry."Dimension Set ID";
            Validate("Depreciation Book Code", DeprBookCode);
            Validate(Amount, -Amount);
            "FA Error Entry No." := FALedgEntry."Entry No.";
            Validate(Correction, DeprBook."Mark Errors as Corrections");
            "Document No." := DocumentNo2;
            "Posting No. Series" := NoSeries2;
            "Document Type" := "Document Type"::" ";
            "External Document No." := '';
            if PostingDescription <> '' then
                Description := PostingDescription;
            GenJnlNextLineNo := GenJnlNextLineNo + 10000;
            "Line No." := GenJnlNextLineNo;
            **//INIT INSERT
            OnBeforeInsertGenJnlLine(GenJnlLine, FALedgEntry, BalAccount);
            //END INSERT**
            Insert(true);
            if BalAccount then begin
                FAInsertGLAcc.GetBalAcc(GenJnlLine);
                if FindLast then;
                GenJnlNextLineNo := "Line No.";
            end;
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
