### ISSUE TITLE
[Event Request] Codeunit 23 Item Jnl.-Post Batch - OnAfterCheckItemAvailability

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10547]
Hi, would it be possible to get an event OnAfterCheckItemAvailability in Codeunit 23 Item Jnl.-Post Batch, like this : 
![image](https://user-images.githubusercontent.com/73548802/104033695-28884a00-51d0-11eb-980d-f2e3d94c178d.png)

```
IsHandled := false;
            OnAfterCheckItemAvailability(ItemJnlLine,IsHandled);
            if not IsHandled then begin
                
                if ItemJnlTemplate.Recurring then
                    Window.Open(
                    Text001 +
                    Text002 +
                    Text003 +
                    Text004)
                else
                    Window.Open(
                    Text001 +
                    Text002 +
                    Text005);

                Window.Update(1, "Journal Batch Name");

            end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckItemAvailability(var ItemJournalLine: Record "Item Journal Line"; IsHandled: Boolean)
    begin
    end;
```
?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
