### ISSUE TITLE
[Event Request] Codeunit 23 Item Jnl.-Post Batch - OnAfterCopyItemJnlLine3

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10549]
Hi, would it be possible to get an event OnAfterCopyItemJnlLine3 in Codeunit 23 Item Jnl.-Post Batch, codeunit HandleNonRecurringLine, like this :

![image](https://user-images.githubusercontent.com/73548802/104039477-b7986080-51d6-11eb-97bb-1c520f95d83c.png)

 ```
with ItemJnlLine do begin
            ItemJnlLine2.CopyFilters(ItemJnlLine);
            ItemJnlLine2.SetFilter("Item No.", '<>%1', '');
            if ItemJnlLine2.FindLast then; // Remember the last line
            ItemJnlLine2."Entry Type" := OldEntryType;

            ItemJnlLine3.Copy(ItemJnlLine);

            OnAfterCopyItemJnlLine3(ItemJnlLine,ItemJnlLine3);
            
            ItemJnlLine3.DeleteAll();
            ItemJnlLine3.Reset();
            ItemJnlLine3.SetRange("Journal Template Name", "Journal Template Name");
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyItemJnlLine3(var ItemJournalLine: Record "Item Journal Line"; var ItemJournalLine3: Record "Item Journal Line")
    begin
    end;
```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
