### ISSUE TITLE
[Event Modification] Codeunit 80 Sales.-Post - OnBeforePostSalesLines

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10543]
Hi, would it be possible to modify the event OnBeforePostSalesLines in codeunit 80 SalesPost to insert SalesSetup parameter, like this :
![image](https://user-images.githubusercontent.com/76154006/104024394-55823000-51c3-11eb-9074-962cdf537019.png)
![image](https://user-images.githubusercontent.com/76154006/104024437-68950000-51c3-11eb-8ba2-c3ad93e54411.png)
Thanks

**Comment by RomanZanizdra** [comment]
Hi @Herodoteux . I suppose you want to update SalesSetup before enter the loop. In the beginning of OnRun() there is GetSalesSetup() procedure and OnAfterGetSalesSetup(SalesSetup) event inside. Does it fit for you to update SalesSetup?

**Comment by Herodoteux** [comment]
Hi @RomanZanizdra  my problem it's that I need to had un procedure in this place and I miss just this argument to do so, I use SalesHeader and TempSalesLineGlobal too.
Thank you.

**Comment by RomanZanizdra** [comment]
Hi again @Herodoteux , I'm not sure I fully understand your reply. You ask for a SalesSetup parameter in OnBeforePostSalesLines() event. The first usage of SalesSetup variable after this event is the following code in the loop below. And I suppose that you need to have SalesSetup updated on your own purposes (may be select/deselect "Invoice Rounding"). If this is your purpose then I suggest you to use other event OnAfterGetSalesSetup() in GetSalesSetup() procedure to update SalesSetup. If not then I just don't understand why do you need SalesSetup as parameter and why you just cannot read in your code. Does it make sense?

```
...
                    if LastLineRetrieved and **SalesSetup."Invoice Rounding"** then
                        InvoiceRounding(SalesHeader, TempSalesLineGlobal, false, BiggestLineNo);
...
```

**Comment by Herodoteux** [comment]
Hi again, before the repeat I want to modify SalesLine after a if with SalesSetup as a condition. To do so I need to read SalesSetup Record to get the value of "Apply Inv. Round. Amt. To VAT" field.
I think add the parameter in this event it's the only way to do so.
Thank you

**Comment by RomanZanizdra** [comment]
You have a subscriber like this. Why can't you read setup directly in the subscriber?
```
    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Sales-Post", 'OnBeforePostSalesLines', '', false, false)]
    local procedure OnBeforePostSalesLinesHandler(var SalesHeader: Record "Sales Header"; var TempSalesLineGlobal: Record "Sales Line"; var TempVATAmountLine: Record "VAT Amount Line")
    var
        SalesReceivablesSetup: Record "Sales & Receivables Setup";
    begin
        SalesReceivablesSetup.Get();
    end;

```

**Comment by Herodoteux** [comment]
Thank you for your answer @RomanZanizdra, I fix my problem with your advice. 
Sorry for the inconvenience.
Thanks again.
