### ISSUE TITLE
[Event Request] Codeunit 5705 "TransferOrder-Post Receipt" Event  OnAfterPostItemJnlLine Add parameter Codeunit "Item Jnl.-Post Line"

### ISSUE THREAD

**Issue by aconcato** [microsoft/ALAppExtensions#10540]
**Could you please add Codeunit "Item Jnl.-Post Line" by reference on event OnAfterPostItemJnlLine Codeunit 5705 "TransferOrder-Post Receipt" ?**

Definition..

//Current 

 [IntegrationEvent(false, false)]
 local procedure OnAfterPostItemJnlLine(ItemJnlLine: Record "Item Journal Line"; var TransLine3: Record "Transfer Line"; 
                   var TransRcptHeader2: Record "Transfer Receipt Header"; var TransRcptLine2: Record "Transfer Receipt Line")

// New Parameter  var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line"

 [IntegrationEvent(false, false)]
 local procedure OnAfterPostItemJnlLine(ItemJnlLine: Record "Item Journal Line"; var TransLine3: Record "Transfer Line"; 
                   var TransRcptHeader2: Record "Transfer Receipt Header"; var TransRcptLine2: Record "Transfer Receipt Line"; 
                   **var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line"**)   

Call Method..

//Current

OnAfterPostItemJnlLine(ItemJnlLine, TransLine3, TransRcptHeader2, TransRcptLine2);

// New Parameter  ItemJnlPostLine

OnAfterPostItemJnlLine(ItemJnlLine, TransLine3, TransRcptHeader2, TransRcptLine2, **ItemJnlPostLine** );

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
