### ISSUE TITLE
[Event Request] Codeunit 13636 OIOUBL-Export Sales Invoice

### ISSUE THREAD

**Issue by AlexanderPallesen** [microsoft/ALAppExtensions#10541]
We would like to have the possibility to embed a pdf of the posted docunemt into the OIOUBL file.

In order to do that we would need a new publisher in Codeunit 13636:
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertAccountingSupplierParty(var InvoiceElement: XmlElement; SalesInvoiceHeader: Record "Sales Invoice Header")
begin
end;

Called from procedure CreateXML:
...
        // Invoice->OrderReference
        if SalesInvoiceHeader."Order No." <> '' then
            OIOUBLXMLGenerator.InsertOrderReference(XMLCurrNode,
              SalesInvoiceHeader."External Document No.",
              SalesInvoiceHeader."Order No.",
              SalesInvoiceHeader."Order Date")
        else
            OIOUBLXMLGenerator.InsertOrderReference(XMLCurrNode,
              SalesInvoiceHeader."External Document No.",
              SalesInvoiceHeader."Pre-Assigned No.",
              SalesInvoiceHeader."Order Date");

        **OnBeforeInsertAccountingSupplierParty(XMLCurrNode, SalesInvoiceHeader);**

        // Invoice->AccountingSupplierParty
        OIOUBLXMLGenerator.InsertAccountingSupplierParty(XMLCurrNode, SalesInvoiceHeader."Salesperson Code");

Regards
Alexander

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
