### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnAftrePostSalesLineLastLineRetrieved

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#10545]
Hi, would it be possible to get an event OnAftrePostSalesLineLastLineRetrievedin codeunit 80 Sales Post, in trigger OnRun, like this :
![image](https://user-images.githubusercontent.com/76153139/104029461-4a7ece00-51ca-11eb-917c-d7d0134d6950.png)
![image](https://user-images.githubusercontent.com/76153139/104029377-333fe080-51ca-11eb-902b-eac3650ce09a.png)
Because we need to put our code before "until LastLineRetrieved".
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
