### ISSUE TITLE
[Event Request] Codeunit 5510 Production Journal Mgt - OnBeforeHandling

### ISSUE THREAD

**Issue by TCutullic** [microsoft/ALAppExtensions#10546]
Hi, would it be possible to have an event just at the start of the procedure "Handling" like OnBeforeHandling(ProdOrder: record Production Order).

![image](https://user-images.githubusercontent.com/70213459/104031621-3be5e600-51cd-11eb-894c-75465d53e2fe.png)
![image](https://user-images.githubusercontent.com/70213459/104031649-486a3e80-51cd-11eb-82ee-17b07f177bb0.png)

That would help a lot.
Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
