### ISSUE TITLE
[Event Request] Codeunit 13637 OIOUBL-Export Sales Cr. Memo

### ISSUE THREAD

**Issue by AlexanderPallesen** [microsoft/ALAppExtensions#10542]
We would like to have the possibility to embed a pdf of the posted docunemt into the OIOUBL file.

In order to do that we would need a new publisher in Codeunit 13637:
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertAccountingSupplierParty(var InvoiceElement: XmlElement; SalesCrMemoHeader: Record "Sales Cr.Memo Header")
begin
end;

Called from procedure CreateXML:
...
        InsertDiscrepancyResponse(XMLCurrNode);
        OIOUBLXMLGenerator.InsertOrderReference(XMLCurrNode,
          SalesCrMemoHeader."External Document No.",
          SalesCrMemoHeader."Applies-to Doc. No.",
          SalesCrMemoHeader."Posting Date");

         **OnBeforeInsertAccountingSupplierParty(XMLCurrNode, SalesCrMemoHeader);**

        // Credit Memo->AccountingSupplierParty
        OIOUBLXMLGenerator.InsertAccountingSupplierParty(XMLCurrNode, SalesCrMemoHeader."Salesperson Code");

Regards
Alexander

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
