### ISSUE TITLE
FromBase64 convert issue

### ISSUE THREAD

**Issue by siimsalu** [microsoft/ALAppExtensions#10553]
Hi all,

On 2019 release wave 2, FromBase64String in Tempblob record is to be replaced by FromBase64 method in Base64 Convert codeunit. The problem is the replacement is not really adequate. Previously it was possible to decode a base 64 string of a file correctly to a blob, now it doesn't seem to be the case. 

This is the new implementation (not working)

    procedure ConvertFromBase64(var pTempBlob: Codeunit "Temp Blob"; Base64Value: Text)
    var
        Base64Convert: Codeunit "Base64 Convert";
        OutStream: OutStream;
    begin
        pTempBlob.CreateOutStream(OutStream, TextEncoding::UTF8);
        OutStream.Write(Base64Convert.FromBase64(Base64Value));
    end;

This implementation is using Tempblob record FromBase64String(working).

    procedure ConvertFromBase64(var pTempBlob: Codeunit "Temp Blob"; Base64Value: Text)
    var
        TempBlob: Record TempBlob temporary;
        InStream: InStream;
        OutStream: OutStream;
    begin
        TempBlob.Init();
        TempBlob.Insert();
        TempBlob.FromBase64String(Base64Value);
        TempBlob.Blob.CreateInStream(InStream, TextEncoding::UTF8);
        pTempBlob.CreateOutStream(OutStream, TextEncoding::UTF8);
        CopyStream(OutStream, InStream);
    end;

I believe the problem lies in FromBase64 method as it is returning text while the previous System.Convert was writing a blob, byte by byte. It is difficult to tell as codeunit 4111 seems to be off-limits for security reasons. Perhaps there is a workaround that I am not aware of?

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
