### ISSUE TITLE
[Event Request] Codeunit 5704 TransferOrder-Post  - OnBeforeInsertShipmentLines

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10552]
Hi, would it be possible to get an event OnBeforeInsertShipmentLines in Codeunit 5704 TransferOrder-Post, like this : 
![image](https://user-images.githubusercontent.com/73548802/104165699-0a059700-53fa-11eb-92f1-34450a07da2d.png)

`OnBeforeInsertShipmentLines(WhseShptHeader,WhseShptLine);`

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertShipmentLines(var WhseShptHeader : Record "Warehouse Shipment Header" ; var WarehouseShipmentLine: Record "Warehouse Shipment Line")
    begin
    end;   
```
?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
