### ISSUE TITLE
[Event Request] Codeunit 5530 "Calc. Item Availability" - OnAfterGetPlanningLinesFromReqLine

### ISSUE THREAD

**Issue by sauerkreut** [microsoft/ALAppExtensions#10555]
**Attn: Please also include this event into BC14 (Cumulative Update 15 ?)**
We would like to request an event in codeunit 5530 "Calc. Item Availability" in the procedure "GetPlanningLines":

           WITH ReqLine DO BEGIN
              SETRANGE(Type,Type::Item);
              SETRANGE("No.",Item."No.");
              SETFILTER("Location Code",Item.GETFILTER("Location Filter"));
              SETFILTER("Variant Code",Item.GETFILTER("Variant Filter"));
             IF FINDSET THEN
                REPEAT
                .....
                .....
             UNTIL NEXT = 0;
             OnAfterGetPlanningLinesFromReqLine(InvtEventBuf, Item, ReqLine, RecRef.RECORDID);
             END;

Integration Event:

    [IntegrationEvent(flase, false)]
    local procedure OnAfterGetPlanningLinesFromReqLine(var InvtEventBuf : Record "Inventory Event Buffer"; Item : Record "Item";ReqLine : Record "Requisition Line";FromRecRef : RecordRef)
    begin
    end;

Thank you for your attention
Kind regards
Walter

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
