### ISSUE TITLE
[Event Request] - Table 37 "Sales Line"

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#10557]
Please provide the same events in the function "GetFAPostingGroup" as in the Tabe 39 "Sales Line".
- OnBeforeGetFAPostingGroup(Rec, IsHandled);
- OnAfterGetFAPostingGroup(Rec, LocalGLAcc);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
