### ISSUE TITLE
[Event Request] Codeunit 7000 "Sales Price Calc. Mgt.", OnAfterCopyJobResPriceToJobJnlLine

### ISSUE THREAD

**Issue by HeidarOrn** [microsoft/ALAppExtensions#10554]
Good day, I would like to ask for a new event to solve a problem that we are having with our customization on Jobs, but we need to be able to edit the "Job Journal Line" record at the end of the function "CopyJobResPriceToJobJnlLine".
![image](https://user-images.githubusercontent.com/5692559/104173345-88b00380-53fd-11eb-8b5a-1e7a2522486a.png)
![image](https://user-images.githubusercontent.com/5692559/104173718-1ab80c00-53fe-11eb-8b94-4441b276f55b.png)

Regards Heiðar

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
