### ISSUE TITLE
[Event Request] Codeunit 5763 Whse.-Post Shipment - OnInitSourceDocumentHeaderOnAfterValidateSalesHeader

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10563]
Hi, would it be possible to get an event OnInitSourceDocumentHeaderOnAfterValidateSalesHeader in Codeunit 5763 Whse.-Post Shipment, procedure InitSourceDocumentHeader, like this 
![image](https://user-images.githubusercontent.com/73548802/104329060-ca6ba780-54ec-11eb-9631-5e49b6f68867.png)

`OnInitSourceDocumentHeaderOnAfterValidateSalesHeader(SalesHeader);`

```
    [IntegrationEvent(false, false)]
    local procedure OnInitSourceDocumentHeaderOnAfterValidateSalesHeader( SalesHeader: Record "Sales Header"; Invoice: Boolean)
    begin
    end;   
```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
