### ISSUE TITLE
[Event Request] report 117 "Reminder": OnPreDataItem (LetterText)

### ISSUE THREAD

**Issue by TimCsr** [microsoft/ALAppExtensions#10565]
Object: codeunit 117 "Reminder"

Function: OnPreDataItem (LetterText)

Integration Event:

OnAfterPreDataItem(AmtDueTxt,"Issued Reminder Header");
**Why?**
In our opinion "Due Date" is the wrong date to put in the email body, because this is the due date of the reminder and not the invoice. 

![image](https://user-images.githubusercontent.com/50943286/104334869-29341f80-54f3-11eb-85d3-89666a3dc720.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
