### ISSUE TITLE
[Event Request] Codeunit 5763 Whse.-Post Shipment - OnPurchaseLineOnBeforePurchPostRun & OnPurchaseLineOnBeforePurchPostRun2

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10569]
Hi, would it be possible to get two events OnPurchaseLineOnBeforePurchPostRun and OnPurchaseLineOnBeforePurchPostRun2, in Codeunit 5763 Whse.-Post Shipment procedure PostSourceDocument like this : 
![image](https://user-images.githubusercontent.com/73548802/104429878-60074580-5586-11eb-9469-4b7808719f5a.png)

`OnPurchaseLineOnBeforePurchPostRun(PurchHeader);`

```
    [IntegrationEvent(false, false)]
    local procedure OnPurchaseLineOnBeforePurchPostRun(var PurchaseHeader: Record "Purchase Header")
    begin
    end;    
```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
