### ISSUE TITLE
logical error vs functionality in 1099 

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/ALAppExtensions#10562]
hi everyone, 
today i was working with 1099 report. I found some wired code which looks like that it is an issues.

while creating any report, for each vendor we are calling following function 
![image](https://user-images.githubusercontent.com/38460823/104323030-aa97ac00-550b-11eb-89ea-213d7ea781d6.png)
in this function, we are fetching entries from vendor ledger enteries and from that function, for each of entry we are calling another function to calculate 1099 amount 
![image](https://user-images.githubusercontent.com/38460823/104323083-c3a05d00-550b-11eb-85f4-1a2d874a6e27.png)

after calculating 1099 amount, we are updating array of amount in the following function
![image](https://user-images.githubusercontent.com/38460823/104323229-efbbde00-550b-11eb-9516-876f5fbc14bd.png)

and in this function, we are adding the adjustment amount
![image](https://user-images.githubusercontent.com/38460823/104323305-06facb80-550c-11eb-9e26-017d17d841e6.png)

so, which means for every vendor ledger entry line we are adding adjustment amount and means in future if end user has many lines then it will going to add adjustment(s) for each line which doesn't make any sense. 

but still i want to confirm with you guys?

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. 
Please try to provide a business scenario that shows the problem you described from AL code point of view.
Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
