### ISSUE TITLE
[Extensibility Request] "Item Availability by BOM Level"

### ISSUE THREAD

**Issue by sirhc101** [microsoft/ALAppExtensions#10560]
Hi there,

To be able to extend `Item Availability by BOM Level` page and be aware of all filters (e.g. `LocationFilter`, `VariantFilter`) it would be very helpful to add `protected` access modifier to `Item` global variable.

This would put us in the situation to consider all Item related filters in our extensions, because the `Item` record is updated in `RefreshPage` procedure:
```al
local procedure RefreshPage()
    var
        CalcBOMTree: Codeunit "Calculate BOM Tree";
    begin
        Item.SetRange("Date Filter", 0D, DemandDate);
        Item.SetFilter("Location Filter", LocationFilter);
        Item.SetFilter("Variant Filter", VariantFilter);
        Item.SetFilter("No.", ItemFilter);
        CalcBOMTree.SetItemFilter(Item);
        [...]
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
