### ISSUE TITLE
[Event Request] CU5895 Invt Adjustment

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#10566]
Hello,
can we please add

`
local procedure InitAdjmtJnlLine(var ItemJnlLine: Record "Item Journal Line"; OrigValueEntry: Record "Value Entry"; EntryType: Enum "Cost Entry Type"; VarianceType: Enum "Cost Variance Type"; InvoicedQty: Decimal)
    begin
        with OrigValueEntry do begin
            ItemJnlLine."Value Entry Type" := EntryType;
            ItemJnlLine."Partial Revaluation" := "Partial Revaluation";
            ItemJnlLine.Description := Description;
            ItemJnlLine."Source Posting Group" := "Source Posting Group";
            ItemJnlLine."Source No." := "Source No.";
            ItemJnlLine."Salespers./Purch. Code" := "Salespers./Purch. Code";
            ItemJnlLine."Source Type" := "Source Type";
            ItemJnlLine."Reason Code" := "Reason Code";
            ItemJnlLine."Drop Shipment" := "Drop Shipment";
            ItemJnlLine."Document Date" := "Document Date";
            ItemJnlLine."External Document No." := "External Document No.";
            ItemJnlLine."Quantity (Base)" := "Valued Quantity";
            ItemJnlLine."Invoiced Qty. (Base)" := InvoicedQty;
            if "Item Ledger Entry Type" = "Item Ledger Entry Type"::Output then
                ItemJnlLine."Output Quantity (Base)" := ItemJnlLine."Quantity (Base)";
            ItemJnlLine."Item Charge No." := "Item Charge No.";
            ItemJnlLine."Variance Type" := VarianceType;
            ItemJnlLine.Adjustment := true;
            ItemJnlLine."Applies-to Value Entry" := "Entry No.";
            ItemJnlLine."Return Reason Code" := "Return Reason Code";
        end;
        //add
            OnAfterInitAdjmtJnlLine(ItemJnlLine, OrigValueEntry, EntryType, VarianceType, InvoicedQty);
    end;

[IntegrationEvent(false, false)]
    local procedure OnAfterInitAdjmtJnlLine(var ItemJnlLine: Record "Item Journal Line"; OrigValueEntry: Record "Value Entry"; EntryType: Enum "Cost Entry Type"; VarianceType: Enum "Cost Variance Type"; InvoicedQty: Decimal)
    begin
    end;
`
It will allow to assign custom fields.
Thanks,
Bartek

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
