### ISSUE TITLE
[Event Request] Codeunit 5763 Whse.-Post Shipment - OnDocumentStatusNotReleasedOnBeforeError

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10561]
Hi, would it be possible to get an event OnDocumentStatusNotReleasedOnBeforeError in Codeunit 5763 Whse.-Post Shipment, procedure Code, like this : 
![image](https://user-images.githubusercontent.com/73548802/104321705-47465380-54e4-11eb-9ed8-358dfba3d60e.png)
`OnDocumentStatusNotReleasedOnBeforeError(IsHandled,WhseShptLine);`

```
    [IntegrationEvent(false, false)]
    local procedure OnDocumentStatusNotReleasedOnBeforeError( var IsHandled : Boolean ; var WhseShptLine: Record "Warehouse Shipment Line")
    begin
    end;  
```
?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
