### ISSUE TITLE
[Event Request] Codeunit 5763 Whse.-Post Shipment - OnBeforeSalesPostRunSalesHeader

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10564]
Hi, would it be possible to get an event OnBeforeSalesPostRunSalesHeader in Codeunit 5763 Whse.-Post Shipment, procedure PostSourceDocument, like this : 
![image](https://user-images.githubusercontent.com/73548802/104332869-ecffbf80-54f0-11eb-9316-e326eac4632e.png)

`OnBeforeSalesPostRunSalesHeader(IsHandled,SalesHeader);`

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesPostRunSalesHeader( IsHandled : Boolean ; SalesHeader: Record "Sales Header"; Invoice: Boolean)
    begin
    end;     
```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
