### ISSUE TITLE
[Event Request] Codeunit 5704 TransferOrder-Post - OnBeforeWhsePostShptPostUpdateWhseDocuments

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10575]
Hi, would it be possible to get an event OnBeforeWhsePostShptPostUpdateWhseDocuments in Codeunit 5704 TransferOrder-Post, in the OnRun, like this : 
![image](https://user-images.githubusercontent.com/73548802/104446254-7919f180-559a-11eb-93f9-13f024b2ba94.png)

`OnBeforeWhsePostShptPostUpdateWhseDocuments(WhseShptHeader);`

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeWhsePostShptPostUpdateWhseDocuments(WhseShptHeader: Record "Warehouse Shipment Header")
    begin
    end;    
```
?
Thanks

**Comment by StanPesotskiy** [comment]
Can't you use the existing event OnBeforePostUpdateWhseDocuments() of WhsePostShpt codeunit.
