### ISSUE TITLE
[Event Request] OnBeforeInsertAnalysisLine @ Codeunit 7111 "Insert Analysis Line"

### ISSUE THREAD

**Issue by J-KVS** [microsoft/ALAppExtensions#10579]
I'd like to propose the Event `OnBeforeInsertAnalysisLine` in Codeunit `Insert Analysis Line`. It'd be nice if we can use the handled pattern with the Event as shown in my proposition below.

The Table Triggers/Events can't be used because `MoveAnalysisLines()` inserts also lines.

Please let me know if you need additional information from me.

``` al
    local procedure InsertAnalysisLine(var AnalysisLine: Record "Analysis Line"; var AnalysisLineNo: Integer; Text: Text[100]; No: Code[20]; Type2: Enum "Analysis Line Type"; Bold2: Boolean; Indent: Integer)
    // START
    var
        IsHandled: Boolean;
    // STOP
    begin
        with AnalysisLine do begin
            Init;
            "Line No." := AnalysisLineNo;
            AnalysisLineNo := AnalysisLineNo + 10000;
            Description := Text;
            Range := No;
            "Row Ref. No." := CopyStr(No, 1, MaxStrLen("Row Ref. No."));
            Type := Type2;
            Bold := Bold2;
            Indentation := Indent;
            // START
            OnBeforeInsertAnalysisLine(AnalysisLine, IsHandled);
            if IsHandled then
                exit;
            // STOP
            Insert(true);
        end;
    end;

    // START
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertAnalysisLine(var AnalysisLine: Record "Analysis Line"; var IsHandled: Boolean)
    begin
    end;
    // STOP
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
