### ISSUE TITLE
[Request for External] Make InsertGroup() @ Codeunit 7111 "Insert Analysis Line" public

### ISSUE THREAD

**Issue by J-KVS** [microsoft/ALAppExtensions#10578]
I'd like to request that you make the function `InsertGroup()` public so that we as partners can extend the functionality.

Please let me know if you need more information from me.

``` al
// Status Quo:
local procedure InsertGroup(var AnalysisLine: Record "Analysis Line"; GroupDimCode: Code[20]; TotalingType: Enum "Analysis Line Type")
// Requested:
procedure InsertGroup(var AnalysisLine: Record "Analysis Line"; GroupDimCode: Code[20]; TotalingType: Enum "Analysis Line Type")
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
