### ISSUE TITLE
[Event Request] Codeunit 5763 Whse.-Post Shipment - OnAfterModifyLine 

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10572]
Hi, would it be possible to get an event OnAfterModifyLine in Codeunit 5763 Whse.-Post Shipment, procedure HandleSalesLine, like this : 
![image](https://user-images.githubusercontent.com/73548802/104441019-694adf00-5593-11eb-9a82-e5e63631aec4.png)

`OnAfterModifyLine(SalesLine,ModifyLine)`

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterModifyLine(var SalesLine: Record "Sales Line"; ModifyLine : Boolean );
    begin
    end;
```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
