### ISSUE TITLE
[Event Request] Table 5901 - Service Item Line

### ISSUE THREAD

**Issue by danielzuppiger** [microsoft/ALAppExtensions#10589]
Hi,

we would like the following Event/Code added to Table 5901 "Service Item Line". 
<img width="742" alt="t5901_event" src="https://user-images.githubusercontent.com/48677055/104600285-16e3ee00-5679-11eb-9c85-f9c6cc01a5ce.png">
`[IntegrationEvent(false, false)]`
`local procedure OnBeforeCheckFaultReportingCodes(var ServiceItemLine: Record "Service Item Line"; xServiceItemLine: Record "Service Item Line"; var IsHandled: Boolean)`
`begin`
`end;`

The goal is to send a custom message/disable it.

I know it's version 14.x and we can just add it to the code but we would like to use it in newer versions as well.

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
