### ISSUE TITLE
[Event Request] Report 5753 Get Source Documents - OnBeforeShowReceiptDialog

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#10585]
Hello Team,

In Report 5753 we need possibility to have our additional checks and/or avoid using standard code. Having event with IsHandled in the beginning of procedure ShowReceiptDialog would be a perfect solution. I saw that there is a request in ticket #9120. But that publisher would not help us, because of posibility to throw error in the begining. It would be great if you could add a new publisher or suggest on how to implement with already requested one:

![image](https://user-images.githubusercontent.com/70525691/104589464-96ba8a00-5672-11eb-9bf8-cb70cd051639.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowReceiptDialog(var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
