### ISSUE TITLE
Reply to Email Header for AL

### ISSUE THREAD

**Issue by Kushal5** [microsoft/ALAppExtensions#10580]
Currently, we do not have a way to set Reply to on Email Headers. Will this be a feature request?

**Comment by JesperSchulz** [comment]
Our backlog on feature requests for the new email module is long and I would expect this particular one to take a while to get processed. If you need this feature urgently, I would suggest that you create a PR for [the mail module](https://github.com/microsoft/ALAppExtensions/tree/master/Modules/System/Email). You can learn more about how to do that on [aka.ms/ChangeALModule](https://aka.ms/ChangeALModule). Would you consider that?

**Comment by Kushal5** [comment]
Thanks Jesper, I will consider creating a PR :)

Best,
Kushal

**Comment by JesperSchulz** [comment]
That sounds great! I would love to process a PR from you :-)

If you don't find the time to implement a solution yourself after all, please log an idea on [aka.ms/bcideas](http://aka.ms/bcideas) and try to get enough votes for the idea to make it into our backlog. A PR would be the much faster solution though ;-)
