### ISSUE TITLE
[Additional Parameter Request] Codeunit 5751 Get Source Doc. Inbound - OnCreateWhseReceiptHeaderFromWhseRequest

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#10583]
Hello Team,

In codeunit 5751 we need possibility to have additional checks in the procedure `CreateWhseReceiptHeaderFromWhseRequest`. Publisher requested in ticket #8690 is missing pass by reference on variable `WarehouseRequest`, which was ofcourse my mistake. If you could fix this issue, it would be a perfect solution.

![image](https://user-images.githubusercontent.com/70525691/104586627-6375fc00-566e-11eb-8aa3-c68cdd096ea2.png)

    [IntegrationEvent(false, false)]
    local procedure OnCreateWhseReceiptHeaderFromWhseRequest(var WarehouseRequest: Record "Warehouse Request"; var GetSourceDocuments: Report "Get Source Documents"; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
