### ISSUE TITLE
[Event Request] Codeunit 7314 WarehouseAvailabilityMgt - OnBeforeCalcReservQtyOnPicksShipsWithItemTracking

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#10582]
Hello Team,

In Codeunit 7314 we need possibility to have our additional checks and/or avoid using standard code. Having event with IsHandled in the beginning of procedure CalcReservQtyOnPicksShipsWithItemTracking would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/104585605-f01fba80-566c-11eb-966b-820942d4cba5.png)

	[IntegrationEvent(false,false)]
	local procedure OnBeforeCalcReservQtyOnPicksShipsWithItemTracking(LocationCode: Code[10]; ItemNo: Code[20]; VariantCode: Code[10]; var ResPickShipQty: Decimal; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
