### ISSUE TITLE
[Event Request] Table 5050 Contact - OnTypeChangeOnBeforeFindContact

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#10584]
Hello Team,

In Table 5050 we need possibility to have our additional checks and/or avoid using standard code. Having event in procedure `TypeChange` would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/104587152-2d854780-566f-11eb-8f46-d19485e3368a.png)

    [IntegrationEvent(false, false)]
    local procedure OnTypeChangeOnBeforeFindContact(var Contact: Record Contact; CurrentContact: Record Contact)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
