### ISSUE TITLE
[Additional Parameter Request] Codeunit 12 Gen. Jnl.-Post Line - OnFinishPostingOnBeforeCheckIsTransactionConsistent

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#10586]
Hello Team,

In codeunit 5751 we need possibility to have additional checks in the procedure `FinishPosting`. Publisher requested in ticket #8707 would suit us if you could add pass by reference on variable `IsGLRegInserted`,. If you could fix this issue, it would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/104590074-7808c300-5673-11eb-817c-33c6577a4d3f.png)

    [IntegrationEvent(false, false)]
    local procedure OnFinishPostingOnBeforeCheckIsTransactionConsistent(IsTransactionConsistent: Boolean; **var IsGLRegInserted: Boolean;** var GLReg: Record "G/L Register"; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
