### ISSUE TITLE
[Event Request] Codeunit 5005271 Create Delivery Reminder - OnBeforeFindPurchaseHeader

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#10587]
Hello Team,

In Codeunit 5005271 we need possibility to have our additional checks and/or avoid using standard code. Having event in procedure `SuggestLines` would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/104592296-a045f100-5676-11eb-9a07-16221dd0efb4.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindPurchaseHeader(var PurchaseHeader: Record "Purchase Header")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
