### ISSUE TITLE
[Request for External] CU6620 Copy document Mgt

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#10592]
Hello,
can we please make
`procedure CopySalesDocSalesLine(FromSalesHeader: Record "Sales Header"; var ToSalesHeader: Record "Sales Header"; var LinesNotCopied: Integer; NextLineNo: Integer)`

as external?

As well with
```
[IntegrationEvent(true, false)]
    local procedure OnCopySalesDocOnBeforeCopyLines(FromSalesHeader: Record "Sales Header"; var ToSalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;
```
It will allow access to sender, both changes will make possible to run standard copy lines procedure with custom documents.

Thanks,
Bartek

**Comment by AlexanderYakunin** [comment]
First of all, integration events should always be local. You should not call event directly as procedure call. 

Please explain what do you mean by custom documents?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
