### ISSUE TITLE
[Event Request] Report 99001025 - Refresh Production Order - OnBeforeModifyRoutingNo

### ISSUE THREAD

**Issue by TCutullic** [microsoft/ALAppExtensions#10591]
Hi, would it be possible to have an event just before modify the Routing No in the Report Refresh Production Order ?
![image](https://user-images.githubusercontent.com/70213459/104709451-42b9af00-571f-11eb-9201-2beb38937637.png)

![image](https://user-images.githubusercontent.com/70213459/104709305-0be39900-571f-11eb-9353-28245662a3f6.png)

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
