### ISSUE TITLE
[Event Request] Application “Tests-SMB” Codeunit 138008 "Cust/Vend/Item/Empl Templates"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10596]
[Event Request]Application “Tests-SMB”, 138008 "Cust/Vend/Item/Empl Templates"

Could you please insert the event OnTestInitialize at the beginning of the procedure Initialize?
![pic1](https://user-images.githubusercontent.com/45795262/104729747-2c205180-5739-11eb-98ef-fd32ccda9457.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
