### ISSUE TITLE
Request to change OnPrem on SetCheckDim in Codeunit "Gen. Jnl.-Post Line"

### ISSUE THREAD

**Issue by MSIngest** [microsoft/ALAppExtensions#10593]
Hello 
could we make

procedure SetCheckDim(CheckDimTmp: Boolean)
begin
CheckDim := CheckDimTmp;
end;

in Codeunit "Gen. Jnl.-Post Line"

available on cloud development please? This method has OnPrem scope.
 
Thanks you,
MS

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
