### ISSUE TITLE
Access Request] Page 344 Navigate - ExtDocNo and ContactType 

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10597]
Would you please make the global variables ExtDocNo and ContactType protected? That way we can access them in our extension.

```
    protected var
        ExtDocNo: Code[250];
        ContactType: Enum "Navigate Contact Type";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
