### ISSUE TITLE
[Event Request] Application “Tests-ERM” Codeunit 134156 "Service Table Fields UT"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10599]
[Event Request]Application “Tests-ERM”, 134156 "Service Table Fields UT"

Could you please insert the event OnTestInitialize at the beginning of the procedure Initialize?
![pic1](https://user-images.githubusercontent.com/45795262/104730465-650cf600-573a-11eb-8598-1702b7c4aa50.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
