### ISSUE TITLE
Codeunit 13 "Gen. Jnl.-Post Batch" - OnProcessLinesOnAfterPostGenJnlLines

### ISSUE THREAD

**Issue by TonyHemy** [microsoft/ALAppExtensions#10606]
Any chance of getting PreviewMode bool added to the parameters of this existing publisher?

```
[IntegrationEvent(false, false)]
    local procedure OnProcessLinesOnAfterPostGenJnlLines(GenJournalLine: Record "Gen. Journal Line"; GLRegister: Record "G/L Register"; var GLRegNo: Integer)
    begin
    end;
```

Cheers

t

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
