### ISSUE TITLE
[Event Request] CU 6648 Purch Get Return Shipments

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#10605]
Hello,
can we please add

`
[IntegrationEvent(false, false)]
    local procedure OnBeforeTestVendor(ReturnShptHeader: record "Return Shipment Header"; PurchHeader: Record "Purchase Header"; ReturnShptLine: record Return Shipment Line; var IsHandled: Boolean)
    begin
    end;
`

`
procedure CreateInvLines(var ReturnShptLine2: Record "Return Shipment Line")
    var
        DifferentCurrencies: Boolean;
        IsHandled: boolean;
    begin
        with ReturnShptLine2 do begin
            SetFilter("Return Qty. Shipped Not Invd.", '<>0');
            if Find('-') then begin
                PurchLine.LockTable();
                PurchLine.SetRange("Document Type", PurchHeader."Document Type");
                PurchLine.SetRange("Document No.", PurchHeader."No.");
                PurchLine."Document Type" := PurchHeader."Document Type";
                PurchLine."Document No." := PurchHeader."No.";

                repeat
                    if ReturnShptHeader."No." <> "Document No." then begin
                        ReturnShptHeader.Get("Document No.");
                        OnBeforeTestVendor(ReturnShptHeader, PurchHeader, ReturnShptLine2, IsHandled);
                        IsHandled := false;
                        if not IsHandled then
                            ReturnShptHeader.TestField("Pay-to Vendor No.", PurchHeader."Pay-to Vendor No.");
                        DifferentCurrencies := false;
`
This will allow to perform custom tests together with different pay to vendor.
Thanks,
Bartek

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
