### ISSUE TITLE
Expand Table 201 "Resource Price"

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#10604]
Hello, is it possible to expand the table 201 „Resource Price“ with the fields „Starting Date“ (Type Date) and „Customer No.“ (Type Code) and
change the primary key from „Type,Code,Work Type Code,Currency Code“ to „Type,Code,Work Type Code,Currency Code,Starting Date,Customer No.“?
We have customers who use this in a similar way to table 7002 „Sales Price“.

**Comment by StanPesotskiy** [comment]
Changing the primary key is the breaking change.
Also consider moving to the new price engine that is built on the table "Price List Line". 
"Sales Price" and "Resource Price" tables will be removed with the update 20.0 (Q2 2022).
