### ISSUE TITLE
[Event Request] CU700 Page Mgt

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#10609]
Hello,
can we please add

`
[IntegrationEvent(false, false)]
    local procedure OnBeforeGetConditionalCardPageID(RecRef: RecordRef; var CardPageID: Integer; var IsHandled: Boolean)
    begin
    end;
`

`
procedure GetConditionalCardPageID(RecRef: RecordRef): Integer
    var
        CardPageID: Integer;
        IsHandled: Boolean;
    begin
        OnBeforeGetConditionalCardPageID(RecRef, CardPageID, IsHandled);
        if IsHandled then
            exit(CardPageID);
        case RecRef.Number of
            DATABASE::"Gen. Journal Template":
`
This way we have a possbility to customize page seleection with cards.
Thanks,
Bartek

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
