### ISSUE TITLE
[Extensibility] OnAfterFinalizePostingOnBeforeCommit in codeunit 5980 Service-Post should IncludeSender

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#10603]
Hello, it looks like there is no obvious way of calling the `SetSuppressCommit` procedure in the codeunit 5980 `Service-Post`.

I believe this would be easily solved by changing the `OnAfterFinalizePostingOnBeforeCommit` `IntegrationEvent` attribute to set `IncludeSender` to **true**:

```
    [IntegrationEvent(true, false)]
    local procedure OnAfterFinalizePostingOnBeforeCommit(var ServiceHeader: Record "Service Header"; var ServiceLine: Record "Service Line"; var ServDocumentsMgt: Codeunit "Serv-Documents Mgt."; var PassedShip: Boolean; var PassedConsume: Boolean; var PassedInvoice: Boolean)
    begin
    end;
```

This way, as I already can do for Sales and Purchases, I can just call `sender.SetSuppressCommit(true)` when subscribing to this event.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
