### ISSUE TITLE
[Event Request] Table 477 "Report Inbox"

### ISSUE THREAD

**Issue by supercruel** [microsoft/ALAppExtensions#10608]
Would it be possible to give us a "OnBeforeShowReport" event in table 477 "Report Inbox":

    procedure ShowReport()
    var
        Instr: InStream;
        Downloaded: Boolean;
        FileName: Text;
        IsHandled: Boolean;
    begin
        if "Entry No." = 0 then
            Error(NoReportsToShowErr);

        //+New
        IsHandled := false;
        OnBeforeShowReport(Rec, IsHandled);
        if IsHandled then
            exit;
        //-New

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
