### ISSUE TITLE
[Event Request] CU7320 Whse Undo Quantity

### ISSUE THREAD

**Issue by BWilczewski** [microsoft/ALAppExtensions#10607]
Helllo,
can we please add
`
[IntegrationEvent(false,false)]
    local procedure OnBeforeUpdateWhseRequestShpt(var PostedWhseShptLine: Record "Posted Whse. Shipment Line"; IsHandled: Boolean)
    begin
    end;
`

`
local procedure UpdateWhseRequestShpt(var PostedWhseShptLine: Record "Posted Whse. Shipment Line")
    var
        PurchLine: Record "Purchase Line";
        SalesLine: Record "Sales Line";
        IsHandled: boolean;
    begin
        OnBeforeUpdateWhseRequestShpt(PostedWhseShptLine, IsHandled);
        if IsHandled then
            exit;
        with PostedWhseShptLine do begin
            case "Source Type" of
                DATABASE::"Sales Line":
                    begin
                        SalesLine.Get("Source Subtype", "Source No.", "Source Line No.");
                        if not (SalesLine."Quantity Shipped" < SalesLine.Quantity) then
                            exit;
                    end;
                DATABASE::"Purchase Line":
                    begin
                        PurchLine.Get("Source Subtype", "Source No.", "Source Line No.");
                        if not (PurchLine."Return Qty. Shipped" < PurchLine.Quantity) then
                            exit;
                    end;
            end;
            UpdateWhseRequest("Source Type", "Source Subtype", "Source No.", "Location Code");
        end;

        OnAfterUpdateWhseRequestShpt(PostedWhseShptLine);
    end;
`

It will allow to specify custom conditions for an update.
Thanks,
Bartek

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
