### ISSUE TITLE
[Request for External] codeunit 6503 "Item Tracking Doc. Management"

### ISSUE THREAD

**Issue by MiljanSinghammer** [microsoft/ALAppExtensions#10601]
Please switch function FindTrackingEntries in the Codeunit 6503 "Item Tracking Doc. Management" externally available in a same way as FindReservEntries.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
