### ISSUE TITLE
Event Request Codeunit 431 - IC Outbox Export Function RunOutboxTransactions

### ISSUE THREAD

**Issue by MGerits** [microsoft/ALAppExtensions#10610]
Hello,
Requesting a new event publisher on codeunit 431 - IC Outbox Export

I would like to request the following publisher with IsHandled Pattern in Function RunOutboxTransactions

```
 procedure RunOutboxTransactions(var ICOutboxTransaction: Record "IC Outbox Transaction")
var
    CopyICOutboxTransaction: Record "IC Outbox Transaction";
    >>> New Code Begin
    IsHandled: Boolean;
    <<< New Code End
begin
    >>> New Code Begin
    OnBeforeRunOutboxTransactions(ICOutboxTransaction, IsHandled);
    if IsHandled then
        exit;
    <<< New Code End
    CompanyInfo.Get();
    CopyICOutboxTransaction.Copy(ICOutboxTransaction);

```
The signature of the publisher is:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeRunOutboxTransactions(var ICOutboxTransaction: Record "IC Outbox Transaction"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
