### ISSUE TITLE
Add OnAfterCreateNewCreditTransferEntry to Codeunit "SEPA CT-Fill Export Buffer"

### ISSUE THREAD

**Issue by tyurm** [microsoft/ALAppExtensions#10617]
Could you please add new event to "SEPA CT-Fill Export Buffer" FillExportBuffer function:

![image](https://user-images.githubusercontent.com/45788765/104928454-5bd69000-59ab-11eb-9cec-7f3ee2ce7792.png)

We want to link Payment Journal to Credit Transfer Entries.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
