### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnAfterCopyDocumentFields

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10619]
Hi, in the Codeunit 80 Sales Post, would it be possible to get an event OnAfterCopyDocumentFields, like this :
![image](https://user-images.githubusercontent.com/76154006/104936055-50379900-59ac-11eb-880a-79915d350ed1.png)
![image](https://user-images.githubusercontent.com/76154006/104936132-66ddf000-59ac-11eb-887b-e2090866e1ee.png)

  ```
  [IntegrationEvent(false, false)]
    local procedure OnAfterCopyDocumentFields(var SalesHeader: Record "Sales Header"; var GenJnlLine: Record "Gen. Journal Line")
    begin
    end;

```
Thanks

**Comment by StanPesotskiy** [comment]
Is it ok for you to use one of the existing events:
•	OnAfterCopyFromSalesHeaderApplyTo
•	OnAfterCopyFromSalesHeaderPayment
•	OnBeforePostCustomerEntry
If not, could you, please explain what prevents you from doing this?
