### ISSUE TITLE
[Enum Request] Table: Sales Header Archive Field: Shipping Advice 

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10614]
Please add the Enum "Sales Header Shipping Advice" of the Sales Header also for the relating field "Shipping advice" in the archive. Currently it is still an option. 
Thanks :).

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
