### ISSUE TITLE
Codeunit 431 - IC Outbox Export Function ReturnToInbox

### ISSUE THREAD

**Issue by MGerits** [microsoft/ALAppExtensions#10613]
Hello,
Requesting a new event publisher on codeunit 431 - IC Outbox Export

I would like to request the following publisher with IsHandled Pattern in Function ReturnToInbox

```
local procedure ReturnToInbox(var ICOutboxTrans: Record "IC Outbox Transaction")
var
    ICPartner: Record "IC Partner";
    MoveICTransToPartnerCompany: Report "Move IC Trans. to Partner Comp";
    >>> New Code Begin
    IsHandled: Boolean;
    <<< New Code End
begin
    >>> New Code Begin
    OnBeforeReturnToInbox(ICOutboxTrans, IsHandled);
    if IsHandled then
        exit;
    <<< New Code End
    if ICOutboxTrans.Find('-') then
        repeat
```

The signature of the publisher is:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeReturnToInbox(var ICOutboxTrans: Record "IC Outbox Transaction"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
