### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnAfterPostPurchLines

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10620]
Hi, would it be possible to modify the event OnAfterPostPurchLines in Codeunit 90 Purch.-Post in order to add PurchLine and TempInvoiceBuffer as parameters ? 

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterPostPurchLines(var PurchHeader: Record "Purchase Header"; var PurchRcptHeader: Record "Purch. Rcpt. Header"; var PurchInvHeader: Record "Purch. Inv. Header"; var PurchCrMemoHdr: Record "Purch. Cr. Memo Hdr."; var ReturnShipmentHeader: Record "Return Shipment Header"; WhseShip: Boolean; WhseReceive: Boolean; var PurchLinesProcessed: Boolean; CommitIsSuppressed: Boolean; EverythingInvoiced: Boolean;
    var PurchLine : Record "Purchase Line" ; TempInvoicePostBuffer : Record "Invoice Post Buffer")
    begin
    end;
```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
