### ISSUE TITLE
[Event Request] Table 233 - Item Journal Batch - SetupNewBatch() - OnAfterSetupNewBatch()

### ISSUE THREAD

**Issue by i-dhahri** [microsoft/ALAppExtensions#10624]
Hello, would it be possible to have an event "OnAfterSetupNewBatch" in Table 233 - "Item Journal Batch", procedure SetupNewBatch(), Like this :

![image](https://user-images.githubusercontent.com/77328410/105019560-86295b80-5a46-11eb-8f90-da74d0584cee.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
