### ISSUE TITLE
[Event Request] Codeunit 5813 "Undo Purchase Receipt Line" - OnBeforePurchRcpt

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#10623]
Hi, would it be possible to get an event OnBeforePurchRcpt in codeunit 5813 "Undo Purchase Receipt Line", like this : 
`    local procedure "Code"()
    var
        PostedWhseRcptLine: Record "Posted Whse. Receipt Line";
        PurchLine: Record "Purchase Line";
        Window: Dialog;
        ItemRcptEntryNo: Integer;
        DocLineNo: Integer;
        PostedWhseRcptLineFound: Boolean;
        IsHandled: Boolean;
    begin
        with PurchRcptLine do begin
            SetFilter(Quantity, '<>0');
            SetRange(Correction, false);
            IsHandled := False;
            OnBeforePurchRcpt(IsHandled);
            if not IsHandled then begin
            if IsEmpty then
                Error(AllLinesCorrectedErr);
            end;
            FindFirst();
            repeat
                if not HideDialog then
                    Window.Open(Text003);
                CheckPurchRcptLine(PurchRcptLine);
            until Next = 0;`

`    [IntegrationEvent(false, false)]
    local procedure OnBeforePurchRcpt(var IsHandled : Boolean)
    begin
    end;`
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
