### ISSUE TITLE
[Event Request] Codeunit 5750 Whse.-Create Source Document - OnBeforeUpdateShptLineWhseShptLine

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10622]
Hi, in the Codeunit 5750 Whse.-Create Source Document, would it be possible to get an event OnBeforeUpdateShptLineWhseShptLine, like this :
![image](https://user-images.githubusercontent.com/76154006/105010093-94be4580-5a3b-11eb-94b3-2d54e15fe4a6.png)
![image](https://user-images.githubusercontent.com/76154006/105010217-b61f3180-5a3b-11eb-946b-caf436af2f4a.png)
`    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateShptLineWhseShptLine(var WhseShptLine: Record "Warehouse Shipment Line"; var SalesLine: Record "Sales Line" )
    begin
    end;
`
Thanks

**Comment by StanPesotskiy** [comment]
You can use existing event OnBeforeUpdateShptLine. It has WhseShptLine parameter which can give you a link to Sales Line.
