### ISSUE TITLE
Public Event Request on Codeunit 1290 - SOAP Web Service Request Mgt. - Procedure CreateSoapRequest

### ISSUE THREAD

**Issue by bgonzalez-ib** [microsoft/ALAppExtensions#10626]
We need a new Event on Codeunit 1290 - SOAP Web Service Request Mgt. - Procedure CreateSoapRequest:

local procedure CreateSoapRequest(RequestOutStream: OutStream; BodyContentInStream: InStream; Username: Text; Password: Text)
    var
        XmlDoc: DotNet XmlDocument;
        BodyXmlNode: DotNet XmlNode;
        **//INIT INSERT
        IsHandled: Boolean;
        //END INSERT**
    begin
        **//INIT INSERT
        OnBeforeCreateSoapRequest(RequestOutStream, BodyContentInStream, XMLDoc, UserName, Password, TraceLogEnabled, IsHandled);
        If IsHandled then
          exit;
        //END INSERT**
        CreateEnvelope(XmlDoc, BodyXmlNode, Username, Password);
        AddBodyToEnvelope(BodyXmlNode, BodyContentInStream);
        XmlDoc.Save(RequestOutStream);
        TraceLogXmlDocToTempFile(XmlDoc, 'FullRequest');
    end;

The new event would be:
    **//INIT INSERT
    [IntegrationEvent(false, false)]  
    local procedure OnBeforeCreateSoapRequest(  var RequestOutStream: OutStream; var BodyContentInStream: InStream; var XmlDoc: DotNet XmlDocument; var Username: Text; var Password: Text; var TraceLogEnabled: Boolean; var IsHandled: Boolean)
    begin
    end;
    //END INSERT**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
