### ISSUE TITLE
[Event Request] Codeunit 5813 "Undo Purchase Receipt Line" - OnBeforeOnRun2

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#10625]
Hi, would it be possible to get an event OnBeforeOnRun2 in codeunit 5813 "Undo Purchase Receipt Line", like this :

`trigger OnRun()
    var
        SkipTypeCheck: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeOnRun(Rec, IsHandled, SkipTypeCheck);
        if IsHandled then
            exit;

        if not HideDialog then
            if not Confirm(Text000) then
                exit;
    
        OnBeforeOnRun2();

        PurchRcptLine.Copy(Rec);
        Code;
        Rec := PurchRcptLine;
    end;`

`    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnRun2()
    begin
    end;`

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
