### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnBeforeInitPricesInclundingVAT

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10629]
hi, would it be possible to get an event OnBeforeInitPricesInclundingVAT in codeunit 90, procedure PostItemJnlLine, like this : 
![image](https://user-images.githubusercontent.com/73548802/105046294-36a85700-5a69-11eb-9dd8-189cd8eb703e.png)

`OnBeforeInitPricesInclundingVAT(PurchHeader,ItemJnlLine,RemAmt);`

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitPricesInclundingVAT(var PurchHeader: Record "Purchase Header"; ItemJnlLine : Record "Item Journal Line" ; RemAmt : Decimal)
    begin
    end;    
```
?
Thanks

**Comment by StanPesotskiy** [comment]
You can use existing event OnPostItemJnlLineOnAfterPrepareItemJnlLine to recalculate Amount related fields on your need.
