### ISSUE TITLE
[Event Modification] Codeunit 5750 Whse.-Create Source Document - OnBeforeCreateReceiptLineFromSalesLine

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10628]
Hi, in the Codeunit 5750 Whse.-Create Source Document, would it be possible to modify the event OnBeforeCreateReceiptLineFromSalesLine, and add a argument IsHandled like this :

![image](https://user-images.githubusercontent.com/76154006/105028285-22586000-5a51-11eb-97a5-67c2a35d7667.png)
![image](https://user-images.githubusercontent.com/76154006/105028339-31d7a900-5a51-11eb-9559-437d7b3b859e.png)
![image](https://user-images.githubusercontent.com/76154006/105028420-4c118700-5a51-11eb-88c8-b8227c172b2a.png)
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
