### ISSUE TITLE
[Event Request] Codeunit 5804 ItemCostManagement - OnAfterCheckItem

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#10630]
Hi, would it be possible to get an event OnAfterCheckItem in codeunit 5804 ItemCostManagement, like this :

```
         if CheckItem.Get("No.") then
                IsHandled := false;
                OnAfterCheckItem(IsHandled,Item);
                if not IsHandled then begin
                    if CalledByFieldNo <> 0 then
                        Modify(true)
                    else
                        Modify();
                end;
```

```

    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckItem(var IsHandled: Boolean;var Item: Record Item)
    begin
    end;
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
