### ISSUE TITLE
Sales Credit Memo remaining Amount

### ISSUE THREAD

**Issue by Iamabdul** [microsoft/ALAppExtensions#10636]
Hello 👋👋 noobster here

I can see that the [salesCreditMemos ](https://github.com/microsoft/ALAppExtensions/blob/master/Apps/W1/APIV2/app/src/pages/APIV2SalesCreditMemos.Page.al)
endpoint doesn't contain a remaining amount property, would it be possible to include that? 

I can see that there is a remaining amount in Table 114 Sales Cr.Memo Header, is there anyway we can use that to link to the table currently being used in this page?

Thank you!

**Comment by StanPesotskiy** [comment]
This requires some work including upgrade code on Sales Cr. Memo Entity Buffer table. 
Could you please submit a this suggestion on https://aka.ms/bcideas so we can see if there's a traction on it?

**Comment by Iamabdul** [comment]
@StanPesotskiy  will do no worries, I added it [here](https://experience.dynamics.com/ideas/idea/?ideaid=ff5a01aa-495c-eb11-8fed-0003ff68ec39)

**Comment by StanPesotskiy** [comment]
Thanks. It seems to be OK.
