### ISSUE TITLE
[Request-for-external]  Codeunit 90 Purch.-Post - CalcInvoiceDiscountPosting

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10637]
Hi, I was wondering if it would be possible to change the procedure CalcInvoiceDiscountPosting Codeunit 90 from local to external.
My team and I use this procedure a lot in our code, and changing it to external would be a huge help.

Thanks for your work, have a nice day

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
