### ISSUE TITLE
[Event Request] Codeunit 5750 Whse.-Create Source Document - OnBeforePurchLine2ReceiptLine

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10635]
Hi, in the Codeunit 5750 Whse.-Create Source Document, would it be possible to get an event OnBeforePurchLine2ReceiptLine, like this :
![image](https://user-images.githubusercontent.com/76154006/105070635-e094dd00-5a83-11eb-9593-141d48480976.png)

![image](https://user-images.githubusercontent.com/76154006/105070745-03bf8c80-5a84-11eb-8f7c-38beae629c0e.png)

`    [IntegrationEvent(false, false)]
    local procedure OnBeforePurchLine2ReceiptLine(var PurchLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;
`
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
