### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnBeforeRunGenJnlPostLine

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10639]
Hi, would it be possible to get an event OnBeforeRunGenJnlPostLine in Codeunit 90, procedure RunGenJnlPostLine, like this : 
![image](https://user-images.githubusercontent.com/73548802/105157244-116d2480-5b0d-11eb-9c5d-24fb0bd94a78.png)
?

Thanks

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
