### ISSUE TITLE
[Event Request] Page Sales Quote Subform - add Parameter

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10631]
Please add the xRec, as standard code does, we also use it for further checks and tracings. 

...Like this:

    [EventSubscriber(ObjectType::Page, Page::"Sales Quote Subform", 'OnNewRecordEvent', '', true, true)]
    local procedure "Sales Quote Subform_OnNewRecordEvent"
    (
        var Rec: Record "Sales Line";
        xRec: Record "Sales Line";
        BelowxRec: Boolean
    )

**Comment by StanPesotskiy** [comment]
Internal page OnNewRecord event cannot be modified because it is a platform one. If you need a new event calling from trigger OnNewRecord then provide information about event signature and needed place in the code.
