### ISSUE TITLE
[Event Request] Codeunit 5804 ItemCostManagement - OnBeforeUnitCost

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#10632]
Hi, would it be possible to get an event OnBeforeUnitCost in codeunit 5804 ItemCostManagement, like this :

`IsHandled := false; OnBeforeUnitCost(IsHandled, InvoicedQty, LastDirectCost, Item); if not IsHandled then begin if ("Unit Cost" = 0) or ((InvoicedQty > 0) and (LastDirectCost <> 0)) then begin CalcFields("Net Invoiced Qty."); IsHandled := false; OnUpdateUnitCostOnBeforeNetInvoiceQtyCheck(Item, IsHandled); if ("Net Invoiced Qty." > 0) and ("Net Invoiced Qty." <= InvoicedQty) and not IsHandled then "Unit Cost" := LastDirectCost; end; end;`

`[IntegrationEvent(false, false)] local procedure OnBeforeUnitCost(var IsHandled: Boolean; var InvoicedQty: Decimal; var LastDirectCost: Decimal; var Item: Record Item) begin end;`

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
