### ISSUE TITLE
[Event Request] CodeUnit 99000809 - Planning Line Management - OnAfterRecalculateWithOptionalModify

### ISSUE THREAD

**Issue by TCutullic** [microsoft/ALAppExtensions#10633]
Hi, would it be possible de have an event in the RecalculateWithOptionalModify procedure please : 
![image](https://user-images.githubusercontent.com/70213459/105061546-ed143800-5a79-11eb-9344-1d9dc0ef588a.png)

![image](https://user-images.githubusercontent.com/70213459/105061669-0e752400-5a7a-11eb-839d-7a2477558c8e.png)

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
