### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnAfterDeleteApprovalEntries

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10634]
Hi, would it be possible to get an event OnAfterDeleteApprovalEntries in Codeunit 90 Purch.-Post in procedure FinalizePosting, like this : 
![image](https://user-images.githubusercontent.com/73548802/105065438-25b61080-5a7e-11eb-8820-81ddf6d76d22.png)
`OnAfterDeleteApprovalEntries(PurchHeader,IsHandled);`

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterDeleteApprovalEntries(var PurchaseHeader: Record "Purchase Header"; var IsHandled : Boolean )
    begin
    end;   
```
?
Thanks

**Comment by StanPesotskiy** [comment]
You can use existing event OnBeforeDeleteAfterPosting()
