### ISSUE TITLE
[Reminder][Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeInsertSummarizedVATOnVatEntry2CalcPmtDiscIfAdjVAT

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#10646]
Could we please have an event OnBeforeInsertSummarizedVATOnVatEntry2CalcPmtDiscIfAdjVAT in Codeunit 12 in function `CalcPmtDiscIfAdjVAT`?

Event Caller:
```
if VATPostingSetup."Adjust for Payment Discount" then begin
  if LastConnectionNo <> VATEntry2."Sales Tax Connection No." then begin
    if LastConnectionNo <> 0 then begin
      DtldCVLedgEntryBuf := DtldCVLedgEntryBuf2;
      DtldCVLedgEntryBuf."VAT Amount (LCY)" := -TotalVATAmount;
      DtldCVLedgEntryBuf.InsertDtldCVLedgEntry(DtldCVLedgEntryBuf, NewCVLedgEntryBuf, false);
+    OnBeforeInsertSummarizedVATOnVatEntry2CalcPmtDiscIfAdjVAT(DtldCVLedgEntryBuf, OldCVLedgEntryBuf);
      InsertSummarizedVAT(GenJnlLine);
    end;
```

Event Publisher:
```
+ [IntegrationEvent(TRUE, false)]
+ local procedure OnBeforeInsertSummarizedVATOnVatEntry2CalcPmtDiscIfAdjVAT(DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; OldCVLedgEntryBuf: Record "CV Ledger Entry Buffer");
+ begin
+ end;
```

Thank you and kind regards

Event Request #5580 was set to ships-in-future-update in Jan 2020. Still not there in Preview 18.0.21117.0

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
