### ISSUE TITLE
[Event Request] Codeunit 13: Modification of Event OnBeforeCheckCorrection(GenJournalLine, IsHandled) released  in Update 17.2 for Microsoft Dynamics 365 Business Central 2020 Release Wave 2 

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#10643]

**Comment by IgnacioPeq** [comment]
Sorry I've not written then comment...

Could you please, modify the event OnBeforeCheckCorrection(GenJournalLine, IsHandled) to have access to the variables: GenJournalTemplate, LastDate, LastDocType, LastDocNo, LastTempTransNo and DocCorrection?

Object: Codeunit 13 "Gen. Jnl.-Post Batch"
Reason: To implement custom business logic migrating from Dynamics NAV 2016 database.

we need you add the specified variables to the current event: OnBeforeCheckCorrection

replacing the current call to the event:
OnBeforeCheckCorrection(GenJournalLine, IsHandled);
![image](https://user-images.githubusercontent.com/73465025/105167970-bb52ae00-5b19-11eb-91e6-de61bb784055.png)

by this one:
OnBeforeCheckCorrection(GenJournalLine, GenJnlTemplate; LastDate; LastDocType; LastDocNo; LastTempTransNo; DocCorrection; IsHandled);
![image](https://user-images.githubusercontent.com/73465025/105168253-2a300700-5b1a-11eb-8eb3-5d46fb48e8bf.png)

And modify the event code adding the mentioned variables:
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckCorrection(GenJournalLine: Record "Gen. Journal Line"; GenJnlTemplate: Record "Gen. Journal Template"; var LastDate: Date; var LastDocType: Enum "Gen. Journal Document Type"; var LastDocNo: Code[20]; var LastTempTransNo: Integer; var DocCorrection: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
