### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnInsertReceiptLineOnAfterInitPurchRcptLine

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10642]
Hi, would it be possible to modify the event OnInsertReceiptLineOnAfterInitPurchRcptLine to add xPurchLine as a parameter ? 

`OnInsertReceiptLineOnAfterInitPurchRcptLine(PurchRcptLine, PurchLine, ItemLedgShptEntryNo,xPurchLine);`

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
