### ISSUE TITLE
[Event Request] Codeunit 5750 Whse.-Create Source Document - OnBeforeSetQtysOnRcptLine

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10640]
Hi, in the Codeunit 5750 Whse.-Create Source Document, would it be possible to get an event OnBeforeSetQtysOnRcptLine, like this :

![image](https://user-images.githubusercontent.com/76154006/105159895-e801c800-5b0f-11eb-99c9-4a32c069f91a.png)

![image](https://user-images.githubusercontent.com/76154006/105159940-f223c680-5b0f-11eb-977c-005ec95e2c97.png)

`       [IntegrationEvent(false, false)]
    local procedure OnBeforeSetQtysOnRcptLine(var WarehouseReceiptLine: Record "Warehouse Receipt Line"; var Qty: Decimal)
    begin
    end;
`
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
