### ISSUE TITLE
[Event Modification] Codeunit 5751 "Get Source Doc. Inbound" - OnBeforeCreateFromPurchOrder

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10644]
Hi, in the Codeunit 5751 "Get Source Doc. Inbound", would it be possible to modify the event OnBeforeCreateFromPurchOrder, and add a argument IsHandled like this :
![image](https://user-images.githubusercontent.com/76154006/105166920-55b1f200-5b18-11eb-908d-e14214101a2f.png)
![image](https://user-images.githubusercontent.com/76154006/105166960-6a8e8580-5b18-11eb-877e-242b6318afd6.png)
`    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateFromPurchOrder(var PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
    begin
    end;
`

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
