### ISSUE TITLE
[Event Modification] Codeunit 5751 "Get Source Doc. Inbound" - OnBeforeCreateFromInbndTransferOrder

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10647]
Hi, in the Codeunit 5751 "Get Source Doc. Inbound", would it be possible to modify the event OnBeforeCreateFromInbndTransferOrder, and add a argument IsHandled like this :

![image](https://user-images.githubusercontent.com/76154006/105181384-05dd2600-5b2c-11eb-9f95-8f17397ae0d3.png)
`    procedure CreateFromInbndTransferOrder(TransHeader: Record "Transfer Header")
    var
    IsHandled: Boolean;
    begin
        IsHandled:= false;
        OnBeforeCreateFromInbndTransferOrder(TransHeader, IsHandled);
        if not IsHandled then
        ShowDialog(CreateFromInbndTransferOrderHideDialog(TransHeader));
    end;
`
![image](https://user-images.githubusercontent.com/76154006/105181425-0f668e00-5b2c-11eb-946b-07a795622f82.png)
`    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateFromInbndTransferOrder(var TransferHeader: Record "Transfer Header"; var IsHandled: Boolean)
    begin
    end;
`
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
