### ISSUE TITLE
NorwegianSAFT table "VAT Code"

### ISSUE THREAD

**Issue by mattias-s** [microsoft/ALAppExtensions#10649]
Hi.

In the NorwegianSAFT app there is some references to a table named "VAT Code".
ex: tableextension 10675 "SAF-T VAT Code" extends "VAT Code"

Where does that table comes from? It´s missing in my BC17 installation.

**Comment by StanPesotskiy** [comment]
table 10602 "VAT Code" is the part of the NO base application.
There are many NO objects referencing to this table, e.g.

```
table 325 "VAT Posting Setup"
...
        field(10606; "VAT Code"; Code[10])
        {
            Caption = 'VAT Code';
            TableRelation = "VAT Code".Code;
```
