### ISSUE TITLE
[Event Request] Codeunit 5813 Undo Purchase Receipt Line - OnBeforeCode

### ISSUE THREAD

**Issue by bleisibach** [Microsoft/ALAppExtensions#1065]
Requesting 1 new event publisher on codeunit "Undo Purchase Receipt Line" - OnBeforeCode

Event
`LOCAL [IntegrationEvent] OnBeforeCode(VAR PurchRcptLine : Record "Purch. Rcpt. Line")`

**Code**
```
LOCAL Code()
>>> New Code
OnBeforeCode(PurchRcptLine);
<<< New Code End

WITH PurchRcptLine DO BEGIN
  SETRANGE(Correction,FALSE);
  IF ISEMPTY THEN
    ERROR(AllLinesCorrectedErr);
.
.
.
```

**Comment by AlexanderYakunin** [comment]
Event already exist

OnRun(VAR Rec : Record "Purch. Rcpt. Line")
IsHandled := FALSE;
OnBeforeOnRun(Rec,IsHandled);
IF IsHandled THEN
  EXIT;
