### ISSUE TITLE
[Access Request] Page 344 Navigate - procedure FindExtRecords()

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10659]
Could you please remove the „local“ from procedure FindExtRecords() in Page 344, to make it available in PageExtensions.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
