### ISSUE TITLE
parameter request - codeunit 1509 "Notification Entry Dispatcher" - OnBeforeCreateMailAndDispatch() - BodyText / HtmlBodyFilePath

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#10658]
We need to CC a specific email address here for certain notifications/records. But we can't append `;otheraddress@example.com` to `var Email` argument because it seems that Document-Mailing or SMTP Mail don't like that, and no email gets sent if there are 2 concatenated like that.

Thus, please can you pass the `BodyText` and the `HtmlBodyFilePath` to the event subscriber, so we can get the body (either of these ways) and run our own code to send the same notification again to the CC address?

Either that, or add some way to add CC recipients here, but I guess you won't want to do that since in BC17 there is the new email functionality and hopefully that natively provides same?

![image](https://user-images.githubusercontent.com/63455896/105356009-c0cbf900-5bea-11eb-8892-4a7d93cc7c40.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
