### ISSUE TITLE
table 5406 "Prod. Order Line" OnAfterGetSKU event problem

### ISSUE THREAD

**Issue by robertoscaringella** [microsoft/ALAppExtensions#10653]
Hi,

Microsoft_Base Application_17.1.18256.18792
table 5406 "Prod. Order Line"
Source code:

local procedure GetSKU() Result: Boolean
begin
    if (SKU."Location Code" = "Location Code") and
       (SKU."Item No." = "Item No.") and
       (SKU."Variant Code" = "Variant Code")
    then
        exit(true);

    if SKU.Get("Location Code", "Item No.", "Variant Code") then
        exit(true);

    Result := false;
    OnAfterGetSKU(Rec, Result);
end;

Problem: In this procedure we can find the event OnAfterGetSKU only if the SKU.Get fails. Maybe for you have a sense, but this procedure is called by to reference in the same table:
- local procedure GetUpdateFromSKU
- Field "Unit Cost" trigger OnValidate()

and on both case, doesn't exist a specific event for manage the recovered SKU in the procedure GetSKU.

So, or change the local procedure GetSKU or add a new event in the reference after GetSKU calling.

Thank you,
Roberto.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
