### ISSUE TITLE
[Event Modification] Table 210 "Job Journal Line" - OnBeforeValidateChargeable 

### ISSUE THREAD

**Issue by DominikWidmann** [microsoft/ALAppExtensions#10654]
Hi, in Addition to the event publisher requested in the closed issue [#7637](https://github.com/microsoft/ALAppExtensions/issues/7637) would it be possible to add xRec as a parameter to the event publisher? 
The goal is to check for changed field values as it is done in the standard Validate-Trigger of the field Chargeable.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
