### ISSUE TITLE
[Event Request] Codeunit 5340 CRM Integration Table Synch. OnSynchNAVTableToCRMOnAfterFindModifiedLocalRecords

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/ALAppExtensions#10650]
I need to apply something similar as the ChildRecord in the Integration Management.

I would need the event OnSynchNAVTableToCRMOnAfterFindModifiedLocalRecords on the following postion:
![grafik](https://user-images.githubusercontent.com/46522333/105201782-89554200-5b41-11eb-8889-ce74770a8603.png)

Also I would need the procedure SyncNAVRecordToCRM globally available or a facade to it.

Thank you in Advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
