### ISSUE TITLE
[Event-Request] Codeunit 229 - Document-Print - GetPurchDocTypeUsage

### ISSUE THREAD

**Issue by DominikWidmann** [microsoft/ALAppExtensions#10655]
Hi, as requested in the closed issues [#2373](https://github.com/microsoft/ALAppExtensions/issues/2373) and [#556](https://github.com/microsoft/ALAppExtensions/issues/556):
Please add a new event publisher "OnBeforeGetPurchDocTypeUsage" in the function "GetPurchDocTypeUsage" of Codeunit Document-Print the same way as it is done in the event publisher "OnBeforeGetSalesDocTypeUsage" in function "GetSalesDocTypeUsage" of this codeunit.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
