### ISSUE TITLE
[Event Request] codeunit 5752 "Get Source Doc. Outbound"- OnBeforeOpenWarehouseShipmentPage

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10651]
Hi, in the codeunit 5752 "Get Source Doc. Outbound", would it be possible to get an event OnBeforeOpenWarehouseShipmentPage, like this :
![image](https://user-images.githubusercontent.com/76154006/105203883-e520ca80-5b43-11eb-9727-eb56b3869d88.png)
```
    local procedure OpenWarehouseShipmentPage()
    var
        WarehouseShipmentHeader: Record "Warehouse Shipment Header";
        IsHandled: Boolean;
    begin
        IsHandled:=false;
        OnBeforeOpenWarehouseShipmentPage(WarehouseShipmentHeader, IsHandled)
        if not  IsHandled then
        GetSourceDocuments.GetLastShptHeader(WarehouseShipmentHeader);
        PAGE.Run(PAGE::"Warehouse Shipment", WarehouseShipmentHeader);
    end;

```
![image](https://user-images.githubusercontent.com/76154006/105204173-2add9300-5b44-11eb-9ab1-1efac68ca192.png)
```
  [IntegrationEvent(false, false)]
    local procedure OnBeforeOpenWarehouseShipmentPage(var IsHandled: Boolean; WarehouseShipmentHeader: Record "Warehouse Shipment Header")
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
