### ISSUE TITLE
[Event Request] codeunit 6154 "API Webhook Notification Send": SendRequest

### ISSUE THREAD

**Issue by TimCsr** [microsoft/ALAppExtensions#10656]
Object: codeunit 6154 "API Webhook Notification Send"

Function: SendRequest

Reason: we want to add extra header to our http request

Integration Event:

OnBeforeSendRequestAndReadTextResponse(HttpWebRequestMgt);
![image](https://user-images.githubusercontent.com/50943286/105328525-6aea5780-5bd0-11eb-813e-f0d470967f67.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
