### ISSUE TITLE
request for external - codeunit 1509 "Notification Entry Dispatcher" - GetTargetRecRef()

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#10657]
I've had several times in my NAV/BC dev career to make this public (NAV) or copy-and-paste it (BC). For example, now I need to check what the original record of the Notification Entry is, in "Notification Email" OnBeforeCreateMailAndDispatch(), and if it's for a Purchase Order, then I need to add an additional recipient to the Email Item. I'm going to have to copy/paste as there's no way of calling it. Please can it be made public so we can use it without duplication?

Said function:
![image](https://user-images.githubusercontent.com/63455896/105352498-e276b180-5be5-11eb-8204-fa4a1b00ca74.png)

Note also: report 1320 "Notification Email" reinvents the same wheel. In a past life, I made it just call the former function in the codeunit. Perhaps do the same as a cleanup, while there?
![image](https://user-images.githubusercontent.com/63455896/105352522-ec98b000-5be5-11eb-8ac1-67f24f681eee.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
