### ISSUE TITLE
[Event Request] Codeunit 5777 WhseValisateSourceLine- OnBeforeLocationin 

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#10652]
Hi, would it be possible to get an event OnBeforeLocationin codeunit 5777 WhseValisateSourceLine, like this :

`                    IsHandled: Boolean;`

`                    begin
                        TestField("Order Type", "Order Type"::Production);
                        IsHandled:=false ;
                        OnBeforeLocation(IsHandled);
                        if not IsHandled then begin
                        if Location.Get("Location Code") and Location."Require Pick" and Location."Require Shipment" then
                            if ProdOrderComp.Get(
                                 ProdOrderComp.Status::Released,
                                 "Order No.", "Order Line No.", "Prod. Order Comp. Line No.") and
                               (ProdOrderComp."Flushing Method" = ProdOrderComp."Flushing Method"::Manual) and
                               (Quantity >= 0)
                            then begin
                                QtyRemainingToBePicked :=
                                  Quantity - CalcNextLevelProdOutput(ProdOrderComp) -
                                  ProdOrderComp."Qty. Picked" + ProdOrderComp."Expected Quantity" - ProdOrderComp."Remaining Quantity";
                                CheckQtyRemainingToBePickedForConsumption(NewItemJnlLine, OldItemJnlLine, ProdOrderComp, QtyRemainingToBePicked);
                                QtyChecked := true;
                            end;
                        end;`

`    [IntegrationEvent(false, false)]
    local procedure OnBeforeLocation(var IsHandled: Boolean)
    begin
    end;
`

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
