### ISSUE TITLE
[Event Request] Codeunit 11 Gen. Jnl.-Check Line - CheckDocType

### ISSUE THREAD

**Issue by martonnagy** [Microsoft/ALAppExtensions#1066]
**Dear Development Team,**

can we have an Event Publisher in Codeunit 11 Gen. Jnl.-Check Line - CheckDocType function before ErrorIfNegative with Handled? Using this new Publisher we could post Negative Purchase Invoices.

![image](https://user-images.githubusercontent.com/39408604/52219433-8699ad80-2894-11e9-8f85-7615d85e64e1.png)

Cheers!

**Comment by AlexanderYakunin** [comment]
Yes, we already implemented event here:
LOCAL CheckDocType(GenJnlLine : Record "Gen. Journal Line")
IsHandled := FALSE;
OnBeforeCheckDocType(GenJnlLine,IsHandled);
IF IsHandled THEN
  EXIT;

**Comment by martonnagy** [comment]
Hi Alexander,

you're right.

Thank you,
Marton
