### ISSUE TITLE
[Change Request] codeunit 1720 "Deferral Utilities" Event OnBeforeCheckPostingDate Parameter DeferralLine

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10660]
We would like to politely ask if it would be possible to pass the DeferralLine parameter by reference in Event OnBeforeCheckPostingDate .

```
    [IntegrationEvent(false, false)]
    // >>>>>>>>
    //local procedure OnBeforeCheckPostingDate(DeferralHeader: Record "Deferral Header"; DeferralLine: record "Deferral Line"; var IsHandled: Boolean)
    local procedure OnBeforeCheckPostingDate(DeferralHeader: Record "Deferral Header"; var DeferralLine: record "Deferral Line"; var IsHandled: Boolean)
    // <<<<<<<<
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
