### ISSUE TITLE
Event Request in procedure Initialize of the Calc. Inventory Page Data codeunit

### ISSUE THREAD

**Issue by Rub19Luc21** [microsoft/ALAppExtensions#10666]
Hello,

I would like to request an OnAfterInitialize event in the procedure Initialize of the Calc. Inventory Page Data codeunit.
This event should include all parameters of the Initialize procedure.

**Comment by Rub19Luc21** [comment]
Dear Stan,

I see you added the missing info tag on this request.
What additional information do you need?

**Comment by Rub19Luc21** [comment]
We want to add additional Inventory Event Buffer Records (in the same buffer table) for complementary items.
So basically we call the same function again for another item.
We do that for special items (prepacks) that are closely related to the sellable items and therefore they are within the Item Availability scope.

We want to include all supply and demand for these complementary items (so document entries, Anticipated Demand from forecasts and Blanket Orders, and all Planning Entries (Planning Lines, -Components and - Transfer Demand). So calling the entire function again would be the easiest way for us.

An alternative would be to add event subscribers in all the functions that are called from the CalcNewInvtEventBuf procedure in the Item Availability codeunit. However, we think we might be able to optimize performance if we can handlle all supply and demand in one function.

We have already done some tests with the combined output for multiple items using the document entries and that part is working fine. We do need to implement some special handling for the inventory records, but that seems doable for us. 
However, currently we cannot add Anticipated Demands and Planning Entries because of missing events.

I hopes this clarifies it.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
