### ISSUE TITLE
Event Request OnAfterCalcQuantities in the Item Avail. by Location Lines page

### ISSUE THREAD

**Issue by Rub19Luc21** [microsoft/ALAppExtensions#10663]
Hello,

I would like to request an OnAfterCalcQuantities event in the procedure CalcAvailQuantities of the Item Avail. by Location Lines page.

The parameters of this event should include Rec, Item and all the globals on the page (e.g. GrossRequirement,  ScheduledRcpt, etc..), all as VAR.

See also the Item Avail. by Variant Lines page, that has already has such an event.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
