### ISSUE TITLE
[Event Request] Codeunit 5761 Whse.-Post Receipt (Yes/No)- OnBeforeClear

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#10661]
Hi, would it be possible to get an event OnBeforeClear codeunit 5761 Whse.-Post Receipt (Yes/No), like this :

`        with WhseReceiptLine do begin
            if Find then
                if not HideDialog then
                    if not Confirm(Text000, false) then
                        exit;

            OnAfterConfirmPost(WhseReceiptLine);

            WhsePostReceipt.Run(WhseReceiptLine);
            OnBeforeClear(WhseReceiptLine);
            WhsePostReceipt.GetResultMessage;
            Clear(WhsePostReceipt);
        end;`

`
        [IntegrationEvent(false, false)]
    local procedure OnBeforeClear(var WhseReceiptLine: Record "Warehouse Receipt Line" )
    begin
    end;`

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
