### ISSUE TITLE
[EventRequest] Page 1040 Copy Job - OnLookupToJobTaskNoOnAfterSetJobTaskFilters

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#10672]
Requesting a new event publisher on Page 1040 Copy Job

Event
`OnLookupToJobTaskNoOnAfterSetJobTaskFilters(VAR JobTask : Record "Job Task";FromJobTaskNo : Code[20])`

**Code**
## ToJobTaskNo - OnLookup(VAR Text : Text) : Boolean
```
IF SourceJob."No." <> '' THEN BEGIN
  JobTask.SETRANGE("Job No.",SourceJob."No.");
```
**>>> New Code**
```
  OnLookUpToJobTaskNoOnAfterSetJobTaskFilters(JobTask, FromJobTaskNo);
```
**<<< New Code End**
```
  IF PAGE.RUNMODAL(PAGE::"Job Task List",JobTask) = ACTION::LookupOK THEN
    ToJobTaskNo := JobTask."Job Task No.";
END;
```

In Our Solution we have a link between Jobs and Production Orders. We create additional Job Tasks per Production Order. When copying Job Tasks from and to Jobs we want to filter out these Job Tasks (Marked with a boolean field in Job Task Table). Can you please add this publisher here?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
