### ISSUE TITLE
Request for event in codeunit 11

### ISSUE THREAD

**Issue by srinivasbanny** [microsoft/ALAppExtensions#1067]
We would like to avoid the error with "Job No." as empty for this we need a publisher for it

In codeunit 11 CheckBalAccountNo() function we need a on publisher with

OnAfterCheckBalAccountNo(GenJnlLine,CheckDone);

![image](https://user-images.githubusercontent.com/39740300/52219958-bc09bf80-28c3-11e9-8a41-644f124ead39.png)

**Comment by AlexanderYakunin** [comment]
We already have that:

LOCAL CheckBalAccountNo(GenJnlLine : Record "Gen. Journal Line")
OnBeforeCheckBalAccountNo(GenJnlLine,CheckDone);
IF CheckDone THEN
  EXIT;

**Comment by srinivasbanny** [comment]
@AlexanderYakunin  we need  OnAfterCheckBalAccountNo(GenJnlLine,CheckDone)
