### ISSUE TITLE
report 82 "Export Budget to Excel" - OnPreDataItem() - OnBeforeAssignTempPeriod()

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#10673]
We have a client who views their G/L Budgets by Accounting Period. Their Accounting Periods are not calendar months or otherwise consistent; they are very specific. When they use the Export Budget To Excel report, expecting an equivalent result, just in Excel instead of on-screen, they find they can only choose a fixed period length from a given start. Thus the Export lacks a key feature the page has, and the customer can't export what they see/want.

This worked in NAV in the sense that although I don't think said Report had this functionality, it was in NAV possible to press Ctrl+E and get the standard Excel export of the entire page, and that included the main budget matrix with Acc Pd dates as on the page. But in BC, there is no standard way to export to Excel; it seems we must code every one... Thus it is a clear regression from NAV to BC in the eyes of this client and indeed ourselves.

In the hope that we won't always have to 'fix' this by copying/pasting/modifying/substituting the standard report, I'll be requesting event(s) that might one day help us avoid doing that, perhaps in conjunction with the new report extension functionality once that finally arrives.

Please can you therefore add the event `OnBeforeAssignTempPeriod()` in the location below, through which we will be able to override the default assignment to the `TempPeriod` fields before `Insert()`, thus hopefully letting us get the periods' dates from Acc Periods instead?

![image](https://user-images.githubusercontent.com/63455896/105489492-34353f80-5cab-11eb-8a14-4bcb6dd5000d.png)

publisher signature:
```al
local procedure OnBeforeAssignTempPeriod(var TempPeriod: Record "Date" temporary; StartDate: Date; PeriodLength: DateFormula; PeriodNo: Integer; var Handled: Boolean);
```

With that, we can hopefully `Handle` the event, and assign the `Period Start`/`End` dates from the `i`th `Accounting Period` starting >= the `StartDate`.

Thanks!

**Comment by dtkb** [comment]
As it would be better to fix this in the base app, so that all BC users can export what they see/need, instead of devs having to work around it - I filed a BC Idea:
https://experience.dynamics.com/ideas/idea/?ideaid=f6f9b27b-ab5c-eb11-8fed-0003ff68ec39

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
