### ISSUE TITLE
VariantCode in BC18 in Table 5405 Production Order

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#10676]
With Business Central 18.0.21265.0 the new field 12 "Variant Code" in Table 5405 is established.

It is essential, that other processing codes are adapted to this new feature because we are using this at the moment as individual enhancement app to add our own field "Variant Code" to table 5405 and want to switch to the standard functionality in future:

Codeunit "Carry out Action" Procedure "InsertProdOrder" must also set the new field:

ProdOrder."Source No." := ReqLine."No.";
ProdOrder."Variant Code" := ReqLine."Variant Code";  // <-- new assignment

Report "Copy Production Order Document" must also set the new field:

ToProdOrder."Source No." := FromProdOrder."Source No.";
ToProdOrder."Variant Code" := FromProdOrder."Variant Code";  // <-- new assignment

Report "Replan Production Order" 
ProdOrder."Source Type" := ProdOrder."Source Type"::Item;
                            ProdOrder.Validate("Source No.", prodOrderComp"Item No.");
ProdOrder."Variant Code" := prodOrderComp."Variant Code";  // <-- new assignment

Table 5405 Field 12
Changes might not be allowed if CheckProdOrderStatus

On Changes if "Source No." = '' or "Soruce Type" <> xrec."Source Type" is validated, the "Variant Code" should be empty.

If ItemVariant exists the description fields should be updated from ItemVariant in the OnValidate-Trigger of the new field:

...
if itemVariant.Get(rec."Source No.", rec."Variant Code") then begin
            rec.Description := itemVariant.Description;
            rec."Description 2" := itemVariant."Description 2";
        end;

**Comment by GuntherGebauer** [comment]
ToolTips on Pages "ReleasedProdOrder", "FinishedProdOrder", "SimlulatedProdOrder" are wrong, "FirmPlannedProdOrder" missing ?

The field "Variant Code" does not speicifiy the numbe rof the source document, 

field("Variant Code"; "Variant Code")
                {
                    ApplicationArea = Manufacturing;
                    ToolTip = 'Specifies the number of the source document that the entry originates from.';

correct ToolTip:
ToolTip = 'Specifies the variant of the item on the production order.';

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels as specified in Product Support 
On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f 
On line – read more here https://docs.microsoft.com/en-ca/dynamics365/business-central/dev-itpro/administration/manage-technical-support or contact your partner 
If you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by StanPesotskiy** [comment]
There was a mistake in the previous message above. Sorry for that.

Please reach out to the relevant support channels:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.

**Comment by GuntherGebauer** [comment]
you are kidding. I will not
