### ISSUE TITLE
[Event Request] CodeUnit 99000757 - Update Prod Order Cost - OnBeforeCalculateTotalUnitCost

### ISSUE THREAD

**Issue by TCutullic** [microsoft/ALAppExtensions#10675]
Hi, would it be possible to have en event before calculate the Total unit cost in the UpdateUnitCostOnProdOrder procedure : 
![image](https://user-images.githubusercontent.com/70213459/105513217-568e8380-5cd2-11eb-9dd1-f84401bf35d4.png)

![image](https://user-images.githubusercontent.com/70213459/105513231-5a220a80-5cd2-11eb-84ad-c63f421068e3.png)

Thanks a lot.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
