### ISSUE TITLE
[Request-for-external] Codeunit 80 Sales Post - ResetTempLines

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10680]
Hi, would it be possible to change the procedure ResetTempLines in Codeunit 80 from local to external ? 

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
