### ISSUE TITLE
[Event Request] Table 7320 "Warehouse Shipment Header" – New Event “OnDeleteOnBeforeDeleteWarehouseShipmentLines”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10689]
Could we please have a new publisher “OnDeleteOnBeforeDeleteWarehouseShipmentLines” in Function “OnDelete”, Table 7320 “Warehouse Shipment Header”?
```

    trigger OnDelete()
    begin
        TestField(Status, Status::Open);
*** start new code ***
        OnDeleteOnBeforeDeleteWarehouseShipmentLines(Rec, HideValidationDialog);
*** stop new code ***
        DeleteWarehouseShipmentLines;
        DeleteRelatedLines;
    end;
…
*** start new code ***
    [IntegrationEvent(false, false)]
    local procedure OnDeleteOnBeforeDeleteWarehouseShipmentLines(WarehouseShipmentHeader: Record "Warehouse Shipment Header"; HideValidationDialog: Boolean)
    begin
    end;
*** stop new code ***
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
