### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforeCheckAndUpdateReceive

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10683]
Hi, would it be possible to get an event OnBeforeCheckAndUpdateReceive in Codeunit 80 Sales Post, procedure CheckAndUpdate, like this : 
![image](https://user-images.githubusercontent.com/73548802/105697839-5b874900-5f05-11eb-8af5-0e7ef3a8a917.png)

`OnBeforeCheckAndUpdateReceive(IsHandled);`

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckAndUpdateReceive( IsHandled : Boolean)
    begin
    end;   
```
?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
