### ISSUE TITLE
[Event Request] CodeUnit 241 - Item Jnl.-Post - Code() - OnBeforeItemJnlPostBatch

### ISSUE THREAD

**Issue by i-dhahri** [microsoft/ALAppExtensions#10684]
Hello, would it be possible to have an event "OnBeforeItemJnlPostBatch" in Codeunit 241 "Item Jnl.-Post" , procedure Code(), with "ItemJnlLine" parameter Like this :

![image](https://user-images.githubusercontent.com/77328410/105698883-d309a800-5f06-11eb-84ed-b24778411ad9.png)

Cordially.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
