### ISSUE TITLE
codeunit 7204 "CDS Setup Defaults" - Event Publisher OnBeforeResetCustomerAccountMapping

### ISSUE THREAD

**Issue by GregorGrabner** [microsoft/ALAppExtensions#10690]
in procedure ResetCustomerAccountMapping 
>> START Code on Top of procedure
OnBeforeResetCustomerAccountMapping(IntegrationTableMappingName, EnqueueJobQueEntry, IsHandled);
if IsHandled then
    exit;
<< END Code

  similar to procedure ResetItemProductMapping in codeunit 5334 "CRM Setup Defaults" 
        to OnBeforeResetItemProductMapping

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
