### ISSUE TITLE
[Event Request] Codeunit "Record Restriction Mgt."

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#10700]
We need an event in function  CustomerCheckSalesPostRestrictions in codeunit "Record Restriction Mgt."

`OnBeforeCustomerCheckSalesPostRestrictions(SalesHeader: Record "Sales Header", IsHandled: Boolean)`

The reason is that it may happen that sales headers don't have a sell-to customer no. The Customer.Get in this function will fail in that case.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
