### ISSUE TITLE
[Event Request] New publisher in Table "Purchase Header" - function RecreatePurchLines

### ISSUE THREAD

**Issue by obisang** [microsoft/ALAppExtensions#10707]
Requesting a new publisher event in Table "Purchase Header" in the function "RecreatePurchLines" named OnBeforeRecreatePurchLinesHandler (like in the same funtion on table "Sales Header"

"Purchase Header"
![grafik](https://user-images.githubusercontent.com/33934838/105803940-d486af00-5f9e-11eb-93de-af245a15dbbf.png)

"Sales Header"
![grafik](https://user-images.githubusercontent.com/33934838/105803956-e1a39e00-5f9e-11eb-95d3-011515cc891f.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
