### ISSUE TITLE
[Event Modification] Codeunit 5760 "Whse.-Post Receipt"- OnBeforeCheckWhseJnlLine

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10701]
Hi, would it be possible to modify the event OnBeforeCheckWhseJnlLinein Codeunit 5760 "Whse.-Post Receipt" to insert a WMSMgt parameter, like this :

![image](https://user-images.githubusercontent.com/76154006/105725835-b0d55180-5f29-11eb-99ef-61c224a10a5e.png)

```
    local procedure CheckWhseJnlLine(var TempWhseJnlLine: Record "Warehouse Journal Line" temporary)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckWhseJnlLine(TempWhseJnlLine, WMSMgt, IsHandled);
        if IsHandled then
            exit;

        WMSMgt.CheckWhseJnlLine(TempWhseJnlLine, 0, 0, false);
    end;

```

![image](https://user-images.githubusercontent.com/76154006/105725964-d95d4b80-5f29-11eb-970c-deca1d2fe1d1.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckWhseJnlLine(var TempWhseJnlLine: Record "Warehouse Journal Line" temporary; var WMSMgt: Codeunit "WMS Management"; var IsHandled: Boolean)
    begin
    end;
```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
