### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnTempTrackingSpecificationInvLoopOnBeforeRunWithCheck

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10706]
Hi, would it be possible to get an event OnTempTrackingSpecificationInvLoopOnBeforeRunWithCheck in codeunit80, procedure PostItemChargePerOrder, like this : 
![image](https://user-images.githubusercontent.com/73548802/105734968-78d30c00-5f33-11eb-8232-43b1c1253fb6.png)

```
 [IntegrationEvent(false, false)]
    local procedure OnTempTrackingSpecificationInvLoopOnBeforeRunWithCheck(var IsHandled: Boolean; ItemJnlLine2 : Record "Item Journal Line" ; var SalesLine: Record "Sales Line" )
    begin
    end;
```
?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
