### ISSUE TITLE
[Event Request] T83 "Item Journal Line" - procedure OnBeforePickDimension()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#10708]
```
 ------- ADD PARAMETERS : CurrFieldNo, TableArray, CodeArray, InheritFromDimSetID, InheritFromTableNo ---------

[IntegrationEvent(false, false)]
local procedure OnBeforePickDimension(var ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean,
CurrFieldNo: Integer, TableArray: array[10] of Integer, CodeArray: array[10] of Code[20], InheritFromDimSetID: Integer, InheritFromTableNo: Integer)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
