### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforeInvDiscAmountPerShippedQty

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10703]
Hi, would it be possible to get an event OnBeforeInvDiscAmountPerShippedQty in Codeunit 80 Sales Post, procedure PostItemJnlLinePrepareJournalLine, like this : 
![image](https://user-images.githubusercontent.com/73548802/105728384-64d7dc00-5f2c-11eb-88e9-f81295bba676.png)
?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
