### ISSUE TITLE
codeunit 90 "Purch.-Post" - Event Publisher OnAfterProcessAssocItemJnlLine and OnBeforeTempFindDropShpmtPostBuffer

### ISSUE THREAD

**Issue by Easystep2** [microsoft/ALAppExtensions#10702]
To Enable Drop-Shipments for Service Management we need additional events to return the TempDropShipmentBuffer in procedure ProcessAssocItemJnlLine. This way we can fill the Drop Shipment Buffer to be processed at the events:

local procedure ProcessAssocItemJnlLine(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer" temporary)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeProcessAssocItemJnlLine(PurchLine, IsHandled);
        if IsHandled then
            exit;

        if (PurchLine."Qty. to Receive" <> 0) and (PurchLine."Sales Order Line No." <> 0) then begin
            TempDropShptPostBuffer."Order No." := PurchLine."Sales Order No.";
            TempDropShptPostBuffer."Order Line No." := PurchLine."Sales Order Line No.";
            TempDropShptPostBuffer.Quantity := PurchLine."Qty. to Receive";
            TempDropShptPostBuffer."Quantity (Base)" := PurchLine."Qty. to Receive (Base)";
            TempDropShptPostBuffer."Item Shpt. Entry No." :=
              PostAssocItemJnlLine(PurchHeader, PurchLine, TempDropShptPostBuffer.Quantity, TempDropShptPostBuffer."Quantity (Base)");
            OnBeforeTempDropShptPostBufferInsert(TempDropShptPostBuffer, PurchLine);
            TempDropShptPostBuffer.Insert();
        end;

<<<<----- START Code  ----->>>>
       OnAfterProcessAssocItemJnlLine(PurchaseLine,TempDropShipmentBuffer);
<<<<----- END Code ----->>>>

    end;

[IntegrationEvent(false, false)]
local procedure OnAfterProcessAssocItemJnlLine(var PurchaseLine: Record "Purchase Line";var TempDropShipmentBuffer: Record "Drop Shpt. Post. Buffer" temporary)

And  to handle the Update of the Service Order in the procedure we need an additional Event in procedure UpdateAssocOrder

procedure UpdateAssocOrder(var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer" temporary)
    var
        SalesSetup: Record "Sales & Receivables Setup";
        SalesOrderHeader: Record "Sales Header";
        SalesOrderLine: Record "Sales Line";
        ReserveSalesLine: Codeunit "Sales Line-Reserve";
    begin
        TempDropShptPostBuffer.Reset();

<<<<----- START Code  ----->>>>
       OnBeforeTempFindDropShpmtPostBuffer(TempDropShptPostBuffer, IsHandled);

       if IsHandled then
            exit;
<<<<----- END Code  ----->>>>

        if TempDropShptPostBuffer.IsEmpty then
            exit;
        SalesSetup.Get();
        if TempDropShptPostBuffer.FindSet() then begin
   

[IntegrationEvent(false, false)]
OnBeforeTempFindDropShpmtPostBuffer(var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer" temporary; IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
