### ISSUE TITLE
[Event Request] Table 18 "Customer" - OnBeforeValidateEmail

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#10715]
Hi Team,

In table 18, please provide **xRec** as a parameter to **OnBeforeValidateEmail** event in **ValidateEmail** procedure and provide actual 'Record' with references.

**Actual Event:**
 [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateEmail(Customer: Record Customer; var IsHandled: Boolean)
    begin
    end;

**Required Event:**
 [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateEmail(**var Rec: Record Customer; xRec: Record Customer;** var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
