### ISSUE TITLE
[Event Request] T81 "Gen. Journal Line" - procedure OnBeforeCreateDim()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#10718]
```
 ------- ADD PARAMETER : CurrFieldNo ---------

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateDim(var GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean; CurrFieldNo: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
