### ISSUE TITLE
[Event Request] Codeunit 5804 - Item Cost Management OnAfterRecalcStdCostItem 

### ISSUE THREAD

**Issue by Easystep2** [microsoft/ALAppExtensions#10711]
Adding Additional Cost Components in Manufacturing for Personnel and Tooling Cost

at procedure RecalcStdCostItem(var Item: Record Item)
    begin
        WITH Item DO BEGIN
          "Single-Level Material Cost" := "Standard Cost";
          "Single-Level Mfg. Ovhd Cost" := 0;
          "Single-Level Capacity Cost" := 0;
          "Single-Level Subcontrd. Cost" := 0;
          "Single-Level Cap. Ovhd Cost" := 0;
          "Rolled-up Material Cost" := "Standard Cost";
          "Rolled-up Mfg. Ovhd Cost" := 0;
          "Rolled-up Capacity Cost" := 0;
          "Rolled-up Subcontracted Cost" := 0;
          "Rolled-up Cap. Overhead Cost" := 0;

          // << START Code Add Resource and Tooling Cost
          OnAfterRecalcStdCostItem(Item);
          // >> END Code
        END;

and add **publisher**
local procedure OnAfterRecalcStdCostItem(var Item: Record Item)

**Comment by Easystep2** [comment]
#10713

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
