### ISSUE TITLE
[Event Request] Page 5830 "Demand Overview" - OnBeforeLookupDemandNo

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#10719]
Hi Team,

In Page 5830, please provide  **Text** with references in **OnBeforeLookupDemandNo** event in **OnLookup** trigger of field - DemandNoCtrl

**Actual Event:**
    [IntegrationEvent(false, false)]
    local procedure OnBeforeLookupDemandNo(var AvailabilityCalcOverview: Record "Availability Calc. Overview"; DemandType: Option; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;

**Required Event:**
    [IntegrationEvent(false, false)]
    local procedure OnBeforeLookupDemandNo(var AvailabilityCalcOverview: Record "Availability Calc. Overview"; DemandType: Option;**var Text: Text;** var Result: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
