### ISSUE TITLE
[Event Request] Codeunit 5812 - "Calculate Standard Cost" Multiple events

### ISSUE THREAD

**Issue by Easystep2** [microsoft/ALAppExtensions#10713]
Adding Additional Cost Components in Manufacturing for Personnel and Tooling Cost

at Procedure **CalcAssemblyItem**

if BOMComp.FindSet then begin
            Item."Rolled-up Material Cost" := 0;
            Item."Rolled-up Capacity Cost" := 0;
            Item."Rolled-up Cap. Overhead Cost" := 0;
            Item."Rolled-up Mfg. Ovhd Cost" := 0;
            Item."Rolled-up Subcontracted Cost" := 0;
            Item."Single-Level Material Cost" := 0;
            Item."Single-Level Capacity Cost" := 0;
            Item."Single-Level Cap. Ovhd Cost" := 0;
            Item."Single-Level Subcontrd. Cost" := 0;

// << BEGIN Code
            OnAfterResetItemRolledupCost(Item);
// << END Code

            repeat
                case BOMComp.Type of
                    BOMComp.Type::Item:
                        begin
                            GetItem(BOMComp."No.", CompItem);
                            ComponentQuantity :=
                              BOMComp."Quantity per" *
                              UOMMgt.GetQtyPerUnitOfMeasure(CompItem, BOMComp."Unit of Measure Code");
                            if CompItem.IsAssemblyItem or CompItem.IsMfgItem then begin
                                if CompItem.IsAssemblyItem then
                                    CalcAssemblyItem(BOMComp."No.", CompItem, Level + 1, CalcMfgItems)
                                else
                                    if CalcMfgItems then
                                        CalcMfgItem(BOMComp."No.", CompItem, Level + 1);
                                Item."Rolled-up Material Cost" += ComponentQuantity * CompItem."Rolled-up Material Cost";
                                Item."Rolled-up Capacity Cost" += ComponentQuantity * CompItem."Rolled-up Capacity Cost";
                                Item."Rolled-up Cap. Overhead Cost" += ComponentQuantity * CompItem."Rolled-up Cap. Overhead Cost";
                                Item."Rolled-up Mfg. Ovhd Cost" += ComponentQuantity * CompItem."Rolled-up Mfg. Ovhd Cost";
                                Item."Rolled-up Subcontracted Cost" += ComponentQuantity * CompItem."Rolled-up Subcontracted Cost";
                                Item."Single-Level Material Cost" += ComponentQuantity * CompItem."Standard Cost"

// << BEGIN Code
                                OnAfterCalculateItemRolledupComponentCost(Item, CompItem);
// << END Code
                            end else begin
                                Item."Rolled-up Material Cost" += ComponentQuantity * CompItem."Unit Cost";
                                Item."Single-Level Material Cost" += ComponentQuantity * CompItem."Unit Cost"
// << BEGIN Code
                                OnAfterCalculateItemRolledupPurchaseCost(Item, CompItem);
// << END Code
                            end
                        end;
                    BOMComp.Type::Resource:
                        begin
                            LotSize := 1;
                            if BOMComp."Resource Usage Type" = BOMComp."Resource Usage Type"::Fixed then
                                if Item."Lot Size" <> 0 then
                                    LotSize := Item."Lot Size";

                            GetResCost(BOMComp."No.", TempPriceListLine);
                            Res.Get(BOMComp."No.");
                            ComponentQuantity :=
                              BOMComp."Quantity per" *
                              UOMMgt.GetResQtyPerUnitOfMeasure(Res, BOMComp."Unit of Measure Code") /
                              LotSize;
                            Item."Single-Level Capacity Cost" += ComponentQuantity * TempPriceListLine."Direct Unit Cost";
                            Item."Single-Level Cap. Ovhd Cost" += ComponentQuantity * (TempPriceListLine."Unit Cost" - TempPriceListLine."Direct Unit Cost");
                        end;
                end;
            until BOMComp.Next = 0;

            Item."Single-Level Mfg. Ovhd Cost" :=
                          Round(
                            (Item."Single-Level Material Cost" +
                             Item."Single-Level Capacity Cost" +
                             Item."Single-Level Cap. Ovhd Cost") * Item."Indirect Cost %" / 100 +
                            Item."Overhead Rate",
                            GLSetup."Unit-Amount Rounding Precision");
                        Item."Rolled-up Material Cost" :=
                          Round(
                            Item."Rolled-up Material Cost",
                            GLSetup."Unit-Amount Rounding Precision");
                        Item."Rolled-up Capacity Cost" :=
                          Round(
                            Item."Rolled-up Capacity Cost" + Item."Single-Level Capacity Cost",
                            GLSetup."Unit-Amount Rounding Precision");
                        Item."Rolled-up Cap. Overhead Cost" :=
                          Round(
                            Item."Rolled-up Cap. Overhead Cost" + Item."Single-Level Cap. Ovhd Cost",
                            GLSetup."Unit-Amount Rounding Precision");
                        Item."Rolled-up Mfg. Ovhd Cost" :=
                          Round(
                            Item."Rolled-up Mfg. Ovhd Cost" + Item."Single-Level Mfg. Ovhd Cost",
                            GLSetup."Unit-Amount Rounding Precision");
                        Item."Rolled-up Subcontracted Cost" :=
                          Round(
                            Item."Rolled-up Subcontracted Cost",
                            GLSetup."Unit-Amount Rounding Precision");

// << BEGIN Code
                         OnAfterCalculateItemRolledupCost(Item);
// << END Code

                        Item."Standard Cost" :=
                          Round(
                            Item."Single-Level Material Cost" +
                            Item."Single-Level Capacity Cost" +
                            Item."Single-Level Cap. Ovhd Cost" +
                            Item."Single-Level Mfg. Ovhd Cost" +
                            Item."Single-Level Subcontrd. Cost",
                            GLSetup."Unit-Amount Rounding Precision");
                        Item."Single-Level Capacity Cost" :=
                          Round(
                            Item."Single-Level Capacity Cost",
                            GLSetup."Unit-Amount Rounding Precision");
                        Item."Single-Level Cap. Ovhd Cost" :=
                          Round(
                            Item."Single-Level Cap. Ovhd Cost",
                            GLSetup."Unit-Amount Rounding Precision");

// << BEGIN Code
                         OnAfterCalculateItemSingleLevelCost(Item);
// << END Code

                        Item."Last Unit Cost Calc. Date" := CalculationDate;

                        TempItem := Item;
                        TempItem.Insert
                    end
                end;

**Add additional Publishers:**
      OnAfterResetItemRolledupCost(var Item: Record Item);

      OnAfterCalculateItemRolledupComponentCost(var Item: Record Item; CompItem: Record Item);

      OnAfterCalculateItemRolledupPurchaseCost(var Item: Record Item; CompItem: Record Item);

      OnAfterCalculateItemRolledupCost(var Item: Record Item);

      OnAfterCalculateItemSingleLevelCost(var Item: Record Item);

**Comment by Easystep2** [comment]
#10710

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
