### ISSUE TITLE
[Event Request] Codeunit 5836 - "Cost Calculation Management" Multiple events Part II

### ISSUE THREAD

**Issue by Easystep2** [microsoft/ALAppExtensions#10714]
Adding Additional Cost Components in Manufacturing for Personnel and Tooling Cost

**at Procedure CalcProdOrderLineStdCost**

IF InvtAdjmtEntryOrder.GET(InvtAdjmtEntryOrder."Order Type"::Production,"Prod. Order No.","Line No.") AND
             InvtAdjmtEntryOrder."Completely Invoiced"
          THEN BEGIN
            Item."Single-Level Material Cost" := InvtAdjmtEntryOrder."Single-Level Material Cost";
            Item."Single-Level Capacity Cost" := InvtAdjmtEntryOrder."Single-Level Capacity Cost";
            Item."Single-Level Subcontrd. Cost" := InvtAdjmtEntryOrder."Single-Level Subcontrd. Cost";
            Item."Single-Level Cap. Ovhd Cost" := InvtAdjmtEntryOrder."Single-Level Cap. Ovhd Cost";
            Item."Single-Level Mfg. Ovhd Cost" := InvtAdjmtEntryOrder."Single-Level Mfg. Ovhd Cost";

            // << BEGIN Code
           OnTransferSingleLevelCostToItem(Item, InvtAdjmtEntryOrder);
            // >> END Code

            QtyBase := "Finished Qty. (Base)";
          END ELSE BEGIN
            Item.GET("Item No.");
            QtyBase := "Quantity (Base)";
          END;

**and publisher**

OnTransferSingleLevelCostToItem(var Item: record Item; InvtAdjmtEntryOrder: record "Inventory Adjmt. Entry (Order)" );

**Comment by Easystep2** [comment]
I' looking for a way to overcome the hardcoded parameters for additional cost in the procedures:

CalcProdOrderLineStdCost

CalcProdOrderLineExpCost

CalcProdOrderLineActCost

this are the only left not being able to use events

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
