### ISSUE TITLE
[Event Request] Page 46 "Sales Order Subform" - OnBeforeCalculateTotals , OnBeforeAfterGetCurrRecord 

### ISSUE THREAD

**Issue by Rambabu-Billuri** [microsoft/ALAppExtensions#10716]
Hi Team,

In page 46, please provide **DocumentTotals** (codeunit variable) with reference in **OnBeforeCalculateTotals** event in **CalculateTotals** procedure,
also provide **TotalSalesHeader** and **Currency** with references in **OnBeforeAfterGetCurrRecord** event  in **OnAfterGetCurrRecord** trigger.
1.
**Actual Event:**
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculateTotals(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Required Event:**
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculateTotals(var SalesLine: Record "Sales Line";**var DocumentTotal: codeunit "Document Totals"**; var IsHandled: Boolean)
    begin
    end;

2.
**Actual Event:**
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAfterGetCurrRecord(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Required Event:**
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAfterGetCurrRecord(var SalesLine: Record "Sales Line";**var TotalSalesHeader: Record "Sales Header"; var Currency: Record Currency;** var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
