### ISSUE TITLE
[Event Request] Codeunit 99000810 - Calculate Planning Route Line  OnAfterCalulateExpectedUnitCost

### ISSUE THREAD

**Issue by Easystep2** [microsoft/ALAppExtensions#10710]
Adding Additional Cost Components in Manufacturing for Personnel and Tooling Cost

at **Procedure CreatePlanningCapNeed**

if PlanningRoutingLine."Unit Cost Calculation" = PlanningRoutingLine."Unit Cost Calculation"::Time then begin
            if (TimeType = TimeType::"Run Time") or MfgSetup."Cost Incl. Setup" then begin
                PlanningRoutingLine."Expected Operation Cost Amt." :=
                  PlanningRoutingLine."Expected Operation Cost Amt." +
                  NeedQty * PlanningRoutingLine."Unit Cost per";
                PlanningRoutingLine."Expected Capacity Ovhd. Cost" :=
                  PlanningRoutingLine."Expected Capacity Ovhd. Cost" +
                  NeedQty *
                  (PlanningRoutingLine."Direct Unit Cost" *
                   PlanningRoutingLine."Indirect Cost %" / 100 + PlanningRoutingLine."Overhead Rate");
            end;
        end else begin
            PlanningRoutingLine."Expected Operation Cost Amt." :=
              PlanningRoutingLine."Input Quantity" * PlanningRoutingLine."Unit Cost per";
            PlanningRoutingLine."Expected Capacity Ovhd. Cost" :=
              PlanningRoutingLine."Input Quantity" *
              (PlanningRoutingLine."Direct Unit Cost" *
               PlanningRoutingLine."Indirect Cost %" / 100 + PlanningRoutingLine."Overhead Rate");
        end;

<----- BEGIN Code
           OnAfterCalulateExpectedUnitCost(PlanningRoutingLine, TimeType, PlanningRoutingLine."Input Quantity");
-------> END Code

        ProdOrderCapNeed."Time Type" := TimeType;

**Add additional Publisher:**

OnAfterCalulateExpectedUnitCost(var PlanningRoutingLine: Record "Planning Routing Line"imeType: Option "Setup Time","Run Time";NeedQty: Decimal)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
