### ISSUE TITLE
[Event Request] Codeunit 260 "Document-Mailing" - OnBeforeGetEmailSubject()

### ISSUE THREAD

**Issue by kennetlindberg** [microsoft/ALAppExtensions#10729]
procedure GetEmailSubject(PostedDocNo: Code[20]; EmailDocumentName: Text[250]; ReportUsage: Integer) Subject: Text[250]
    var
        EmailParameter: Record "Email Parameter";
        CompanyInformation: Record "Company Information";
        ReportSelections: Record "Report Selections";
        SalesHeader: Record "Sales Header";
        EnvInfoProxy: Codeunit "Env. Info Proxy";
        DocumentType: Enum "Sales Document Type";
        IsHandled: Boolean
    begin
        _OnBeforeGetEmailSubject(PostedDocNo, EmailDocumentName, ReportUsage, Subject, IsHandled);
        if IsHandled then
            exit;_

        if EmailParameter.GetParameterWithReportUsage(PostedDocNo, "Report Selection Usage".FromInteger(ReportUsage), EmailParameter."Parameter Type"::Subject) then
            exit(EmailParameter.GetParameterValue);
        CompanyInformation.Get();
        if EnvInfoProxy.IsInvoicing then begin
            ReportSelections.ConvertReportUsageToSalesDocumentType(DocumentType, "Report Selection Usage".FromInteger(ReportUsage));
            case DocumentType of
                SalesHeader."Document Type"::Invoice:
                    exit(StrSubstNo(InvoiceEmailSubjectTxt, CompanyInformation.Name));
                SalesHeader."Document Type"::Quote:
                    exit(StrSubstNo(QuoteEmailSubjectTxt, CompanyInformation.Name));
            end;
        end;
        if PostedDocNo = '' then
            Subject := CopyStr(
                StrSubstNo(EmailSubjectPluralCapTxt, CompanyInformation.Name, EmailDocumentName), 1, MaxStrLen(Subject))
        else
            Subject := CopyStr(
                StrSubstNo(EmailSubjectCapTxt, CompanyInformation.Name, EmailDocumentName, PostedDocNo), 1, MaxStrLen(Subject))
    end;

    _[IntegrationEvent(false, false)]
    local procedure OnBeforeGetEmailSubject(PostedDocNo: Code[20]; EmailDocumentName: Text[250]; ReportUsage: Integer; var EmailSubject: Text[250]; var IsHandled: Boolean)
    begin
    end;_

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
