### ISSUE TITLE
[Event Request] codeunit 5752 "Get Source Doc. Outbound"- OnBeforeCheckSalesHeaderLocation 

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10721]
Hi, in the codeunit 5752 "Get Source Doc. Outbound", would it be possible to get an event OnBeforeCheckSalesHeaderLocation in the procedure CheckSalesHeader, like this:
![image](https://user-images.githubusercontent.com/76154006/105850462-0a00bc00-5fe2-11eb-8329-f71fa58d7563.png)
```
            if SalesLine.FindSet then begin
                IsHandled:= false;
                OnBeforeCheckSalesHeaderLocation(SalesLine, SalesHeader, ShowError, SalesOrder, Result, IsHandled);
                if IsHandled then
                    exit(Result);

                LocationCode := SalesLine."Location Code";
                SetItemVariant(CurrItemVariant, SalesLine."No.", SalesLine."Variant Code");
                TotalNoOfRecords := SalesLine.Count();

```
![image](https://user-images.githubusercontent.com/76154006/105850560-2dc40200-5fe2-11eb-9dce-f1512645c51f.png)
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckSalesHeaderLocation(var SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header"; ShowError: Boolean; SalesOrder: Page "Sales Order"; Result: Boolean; IsHandled: Boolean)
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
