### ISSUE TITLE
[Event Request] CU1200 "Import Bank Statement" - procedure OnBeforeInsertColumn()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#10726]
```
------- ADD PARAMETERS: Path, Value ---------

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertColumn(var DataExchLineDef: Record "Data Exch. Line Def"; EntryNo: Integer; LineNo: Integer; NodeId: Text[250]; Name: Text; var ProgressWindow: Dialog; var IsHandled: Boolean; Path: Text; Value: Text)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
