### ISSUE TITLE
[Event Request] Report 840 - Event for filter BudgetEntry

### ISSUE THREAD

**Issue by asaez85** [microsoft/ALAppExtensions#10727]
We need an event for filter BudgetEntry
![image](https://user-images.githubusercontent.com/2249576/105875310-f19e9a80-5ffd-11eb-9758-6789ce4c8b69.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
