### ISSUE TITLE
Event Request Table 5740 - Transfer Header - Function UpdateTransLines

### ISSUE THREAD

**Issue by MGerits** [microsoft/ALAppExtensions#10728]
Hello,
Requesting a new event publisher on table 5740 - Transfer Header

I would like to request the following publisher with IsHandled Pattern in Function UpdateTransLines

```
procedure UpdateTransLines(TransferHeader: Record "Transfer Header"; FieldID: Integer)
var
    TransferLine: Record "Transfer Line";
    TempTransferLine: Record "Transfer Line" temporary;
    >>> New Code Begin
    IsHandled: Boolean;
    <<< New Code End
begin
    >>> New Code Begin
    OnBeforeUpdateTransLines(TransferHeader, FieldID, IsHandled);
    if IsHandled then
        exit;
    <<< New Code End
    TransferLine.SetRange("Document No.", "No.");
    TransferLine.SetFilter("Item No.", '<>%1', '');
```

The signature of the publisher is:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateTransLines(TransferHeader: Record "Transfer Header"; FieldID: Integer; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
