### ISSUE TITLE
[Request-for-external] Codeunit 80 Sales Post - UpdateInvoicePostBuffer

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10724]
Hi, would it be possible to change the procedure UpdateInvoicePostBuffer in codeunit 80 from local to external ? 
I'm trying to implement an alternative method for the FillInvoicePostingBuffer and having UpdateInvoicePostBuffer as an external procedure would be a huge help.

Thanks

**Comment by AlexanderYakunin** [comment]
No, we will not expose it now. We may need some refactoring here for some countries and would like to keep this procedure local in W1. Instead you can use TempInvoicePostBuffer.Update().
