### ISSUE TITLE
[Event Request] Codeunit 5750 Whse.-Create Source Document - OnBeforeTransLine2ReceiptLine

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10733]
Hi, in the Codeunit 5750 Whse.-Create Source Document, would it be possible to get an event OnBeforeTransLine2ReceiptLine, like this :
![image](https://user-images.githubusercontent.com/76154006/105974601-5b668500-608e-11eb-886e-2274e399b119.png)
```
    procedure TransLine2ReceiptLine(WhseReceiptHeader: Record "Warehouse Receipt Header"; TransLine: Record "Transfer Line"): Boolean
    var
        WhseReceiptLine: Record "Warehouse Receipt Line";
        UnitOfMeasureMgt: Codeunit "Unit of Measure Management";
        WhseInbndOtsdgQty: Decimal;
        IsHandled: Boolean;
    begin
        IsHandled:= false;
        OnBeforeTransLine2ReceiptLine(TransLine,IsHandled);
        if IsHandled then
        exit;
        with WhseReceiptLine do begin
            InitNewLine(WhseReceiptHeader."No.");
            SetSource(DATABASE::"Transfer Line", 1, TransLine."Document No.", TransLine."Line No.");
            TransLine.TestField("Unit of Measure Code");

```
![image](https://user-images.githubusercontent.com/76154006/105974788-89e46000-608e-11eb-9505-1d51c509199d.png)
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransLine2ReceiptLine(var TransLine: Record "Transfer Line"; IsHandled: Boolean)
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
