### ISSUE TITLE
[Event Request] Codeunit 7008 "Price Calculation Buffer Mgt." - OnAfterGetSources2

### ISSUE THREAD

**Issue by mhoury** [microsoft/ALAppExtensions#10739]
Could we please have a new published event OnAfterGetSources2 in Codeunit 7008 "_Price Calculation Buffer Mgt._" for the function _GetSources(var NewPriceSourceList: Codeunit "Price Source List")_ ?

Based on the previous request #9924.

    procedure GetSources(var NewPriceSourceList: Codeunit "Price Source List")
    begin
        NewPriceSourceList.Copy(PriceSourceList);
    +   OnAfterGetSources2(PriceCalculationBuffer, NewPriceSourceList);
    end;

with the new event published as follows:

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetSources2(PriceCalculationBuffer: Record "Price Calculation Buffer"; var NewPriceSourceList: Codeunit "Price Source List")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
