### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforeIncludePrepayments

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10737]
Hi, would it be possible to get an event OnBeforeIncludePrepayments in codeunit 80 in procedure DivideAmount, like this : 
![image](https://user-images.githubusercontent.com/73548802/105984293-2d873d80-609a-11eb-887d-48740d05bc88.png)

`OnBeforeIncludePrepayments(SalesHeader,SalesLine,SalesLineQty,IsHandled);`

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeIncludePrepayments(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; SalesLineQty: Decimal; IsHandled: Boolean )
    begin
    end; 
```

?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
