### ISSUE TITLE
[Event Modification] Codeunit 80 Sales.-Post - OnAfterFindCustLedgEntry

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10746]
Hi, would it be possible to get an event OnAfterFindCustLedgEntry in codeunit 80 Sales Post in procedure PostBalancingEntry, like this : 
![image](https://user-images.githubusercontent.com/73548802/106019766-4eb05400-60c3-11eb-9625-17323cb42c7f.png)

`OnAfterFindCustLedgEntry(CustLedgEntry);`

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterFindCustLedgEntry(var CustLedgEntry: Record "Cust. Ledger Entry")
    begin
    end;    
```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
