### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnAfterCopyDocumentFields

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10741]
Hi, would it be possible to get an event OnAfterCopyDocumentFields in codeunit 80 in procedure PostCustomerEntry like this : 
![image](https://user-images.githubusercontent.com/73548802/106014820-26722680-60be-11eb-9deb-614075ddfc79.png)

`OnAfterCopyDocumentFields(SalesHeader,GenJnlLine);`

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyDocumentFields(var SalesHeader: Record "Sales Header" ; var GenJnlLine : Record "Gen. Journal Line" )
    begin
    end;   
```
?
Thanks

**Comment by StanPesotskiy** [comment]
Duplicate to https://github.com/microsoft/ALAppExtensions/issues/10619
