### ISSUE TITLE
Event on function CalcLineTotal on repor 12

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/ALAppExtensions#10742]
Hi,

I need a new event on the case option is: "VATStmtLine2.Type::"Account Totaling":", copy of the event: "OnCalcLineTotalOnBeforeCalcTotalAmountVATEntryTotaling(VATStmtLine2, VATEntry, Amount);"

The new event can name: "OnCalcLineTotalOnBeforeCalcTotalAmountAccountTotaling(VATStmtLine2, VATEntry, Amount);"

Thanks!

**Comment by dtkb** [comment]
You should include the required signature of the publisher, not just the call, because MS need to know whether any of the arguments should be passed as `var` to enable subscribers to update them.

**Comment by AlvaroRosadoP** [comment]
[IntegrationEvent(false, false)]
    local procedure OnCalcLineTotalOnBeforeCalcTotalAmountVATEntryTotaling(VATStmtLine: Record "VAT Statement Line"; var VATEntry: Record "VAT Entry"; var Amount: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
