### ISSUE TITLE
[Event Modification] Codeunit 80 Sales.-Post - OnInsertShipmentHeaderOnAfterTransferfields

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10748]
Hi, would it be possible to get an event OnInsertShipmentHeaderOnAfterTransferfields in codeunit 80, procedure InsertShipmentHeader, like this : 
![image](https://user-images.githubusercontent.com/73548802/106024608-3bec4e00-60c8-11eb-80ef-a2eedd67e1af.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnInsertShipmentHeaderOnAfterTransferfields(var SalesShipmentHeader: Record "Sales Shipment Header")
    begin
    end;    
```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
