### ISSUE TITLE
[Event Modification] Codeunit 5720 "Item Reference Management" - OnAfterValidatePurchaseReferenceNo

### ISSUE THREAD

**Issue by gpfannes** [microsoft/ALAppExtensions#10745]
Please add the Parameter ReturnedItemReference to the Parameter List of Publisher OnAfterValidatePurchaseReferenceNo in Codeunit 5720 "Item Reference Management".

Modified Call in Function ValidatePurchaseReferenceNo:
```
- OnAfterValidatePurchaseReferenceNo(SalesLine, ItemReference);
+ OnAfterValidatePurchaseReferenceNo(SalesLine, ItemReference, ReturnedItemReference);
```
Modified Publisher:
```
- local procedure OnAfterValidatePurchaseReferenceNo(var PurchaseLine: Record "Purchase Line"; ItemReference: Record "Item Reference")
+ local procedure OnAfterValidatePurchaseReferenceNo(var PurchaseLine: Record "Purchase Line"; ItemReference: Record "Item Reference"; ReturnedItemReference: Record "Item Reference")
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
