### ISSUE TITLE
Request the ability to return Attributes linked to an Item in Items page

### ISSUE THREAD

**Issue by bretto36** [microsoft/ALAppExtensions#10755]
Are we able to add the attributes linked to an item in the response from the API

/items?$expand=attributes

Or at least have an endpoint where we can find the mapping of attribute values to items?

**Comment by AndreiPanko** [comment]
Thank you for reaching out. Your issue doesn't seems to be an event request, request for making a function external or general code contribution in for a product. 

Please create an idea instead: https://aka.ms/bcideas

Read more about finding right resource and providing feedback on this blog post: 
https://community.dynamics.com/business/b/financials/archive/2018/12/04/find-the-right-resources-and-provide-feedback 

Sincerely, 
Andrei Panko
PM, Microsoft
