### ISSUE TITLE
[Event Request] Table 14 Location - "Bin Mandatory" field OnValidate trigger OnBeforeWhseEntrySetRange

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10758]
Hello. In table 14 Location, inside the trigger OnValide of the field "Bin Mandatory", we used to add some code on NAV 2018. We are now migrating our code to BC 17.3 and we would like to add a condition before the WhseEntry.SetRange. To do so, we would need an event publisher here : 

                if not "Bin Mandatory" and xRec."Bin Mandatory" then begin

                    OnBeforeWhseEntrySetRange(Rec, WhseEntry);

                    WhseEntry.SetRange("Location Code", Code);
                    WhseEntry.CalcSums("Qty. (Base)");
                    if WhseEntry."Qty. (Base)" <> 0 then
                        Error(Text002, FieldCaption("Bin Mandatory"));
                end;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeWhseEntrySetRange(var Location: Record Location ; var WhseEntry : record "Warehouse Entry");
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
