### ISSUE TITLE
[Event Request] Codeunit 3 "G/L Account-Indent".Indent 

### ISSUE THREAD

**Issue by Softstore** [microsoft/ALAppExtensions#10752]
Include the possibilty to subscrive the OnBeforeIndent to give the possibility to ident with other account types

 procedure Indent()
    begin
        **//------------------------------------------------- 
        IsHandheld := false;
        OnBeforeIndent(GLAcc,IsHandeld);
        IF IsHandeld then
          exit;
        //-------------------------------------------------** 
     Window.Open(Text004);

        with GLAcc do
            if Find('-') then
                repeat
                    Window.Update(1, "No.");

                    if "Account Type" = "Account Type"::"End-Total" then begin
                        if i < 1 then
                            Error(
                              Text005,
                              "No.");
                        if Totaling = '' then
                            Totaling := AccNo[i] + '..' + "No.";
                        i := i - 1;
                    end;

                    Validate(Indentation, i);
                    Modify;

                    if "Account Type" = "Account Type"::"Begin-Total" then begin
                        i := i + 1;
                        if i > ArrayLen(AccNo) then
                            Error(ArrayExceededErr, ArrayLen(AccNo));
                        AccNo[i] := "No.";
                    end;
                until Next = 0;

        Window.Close;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeIndent(var GLAcc: Record "G/L Account"; var IsHandheld: boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
