### ISSUE TITLE
Could not upgrade the extension 'Base Application' | The General Ledger Setup does not exist

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/ALAppExtensions#10757]
Hello,

i am updating my database from BC 17.2 to BC17.3 and i got this error while publising the new BaseApp. 
![image](https://user-images.githubusercontent.com/48794854/106107071-bf4c8480-6146-11eb-8d4b-377a0afbb158.png)

You can ask the question how this record is empty, its a new company and the record is not there.

![image](https://user-images.githubusercontent.com/48794854/106107765-9f699080-6147-11eb-95fd-798271e141e0.png)

I got this problem also on an upgrade pipeline which upgrades a database with a new created company.
In the pipeline it is the Start-NAVAppDataUpgrade that fails
![image](https://user-images.githubusercontent.com/48794854/106112092-210fed00-614d-11eb-89a6-12d46b4019c4.png)

so new company in 17.2 (do not open) upgrade to 17.3 and boem.

Can this bad **get** be changed into 

if not GeneralLedgerSetup.get then
exit;

Because if the record is not there, the upgrade is not applicable. 

Is it not the common rule? never do a hard **get** in an upgrade?

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap in an update for the current version.
