### ISSUE TITLE
[Request] Page 98 "Purch. Cr. Memo Subform" - Move variables

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#10765]
```
Move the variables var:
- InvoiceDiscountAmount: Decimal;
- InvoiceDiscountPct: Decimal;
- VATAmount: Decimal;

To "protected var" to allow to retrieve them in an extension page.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
