### ISSUE TITLE
[Request] Page 232 "Apply Customer Entries" - Move variables

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#10769]
Move the variables var:
- ApplnRounding: Decimal
- VATAmount: Decimal;
- VATAmountText: Text[30];
- ProfitLCY: Decimal;
- ProfitPct: Decimal;
- ApplnDate: Date;
- ApplnType: Option " ","Applies-to Doc. No.","Applies-to ID";
- CalcType: Option Direct,GenJnlLine,SalesHeader,ServHeader;

To "protected var" to allow to retrieve them in an extension page.

**Comment by AlexanderYakunin** [comment]
All these variables already in protected var section in 18.x
