### ISSUE TITLE
[Event Request] Codeunit 5720 "Item Reference Management".SalesReferenceNoLookup - OnBeforeSalesReferenceNoLookup

### ISSUE THREAD

**Issue by fekramer** [microsoft/ALAppExtensions#10763]
In the new "Item Reference" Feature (BC17ff) it is possible to handle the Item Selection in function
ReferenceLookupSalesItem like:
<img width="908" alt="image" src="https://user-images.githubusercontent.com/24778982/106131084-80c4c300-6162-11eb-824f-1cad07748ae7.png">

In addition it would be nice to complete the LookupHandler also to be able to add consistent changes,
e.g. to have a different Lookup-Page.
Followig suggestion:
<img width="640" alt="PastedGraphic-8" src="https://user-images.githubusercontent.com/24778982/106130112-4870b500-6161-11eb-9ab1-9b77f6ac28bb.png">

        IsHandled:Boolean;
    begin
        IsHandled := false;
        OnBeforeSalesReferenceNoLookup(var SalesLine: Record "Sales Line";SalesHeader: record "Sales Header"; IsHandled:Boolean);
        If IsHandled then
        exit;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesReferenceNoLookup(var SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header";IsHandled:Boolean)
    begin
    end;

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
