### ISSUE TITLE
[Request] Table 1006 Job WIP Method - Enum

### ISSUE THREAD

**Issue by MarioSopena** [microsoft/ALAppExtensions#10778]
Hello team,
I think it would be very interesting to have this option fields ,'Recognized Costs','Recognized Sales' as Enum, to make them extensible, in order to implement another WIP calculation methods.

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
