### ISSUE TITLE
[Request-for-external] - Table 5407 "Prod. Order Component" - local procedure CheckBin

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10773]
Hello,

In table 5407 "Prod. Order Component", is it possible de make the procedure CheckBin external ? We would like to use it in the event OnBeforeValidateBinCode(), but we can't because it is a local procedure.

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
