### ISSUE TITLE
Report Issue - FIK

### ISSUE THREAD

**Issue by Hornsyld** [Microsoft/ALAppExtensions#1077]
When doing customization on reports you usally copy the report to your own id range and do the changes right? So in case I would change report 206 - Sales Invoice I make it ect. to 50206 and do my changes there and then in report selection change Sales Invocie to my new report ID.

Altough this is not possible with the danish FIK-mangement extension.

How to re-create issue. Make a sales invoice w. FIK on (Set a Credit No. in company information and on customer set payment code to FIK-71).
Print report 206 and check if FIK-string is set. Notice FIK-String is set here.
Copy report to ect. 50206 and print same report on same invoice data. FIK-string wont be showed here.

If you look at the FIK-Management codeunit 13657 you can find the line below which hardcodes that the FIK-String only can be used from "Sales - Invoice". The FIK-extension is not available in the ALAppExtension repository so you can't make pull request on this.

`    //report 206
    [EventSubscriber(ObjectType::Report,Report::"Sales - Invoice",'OnAfterGetRecordSalesInvoiceHeader','',false,false)]
    procedure OnAfterGetRecordSalesInvoiceHeader(SalesInvoiceHeader : Record "Sales Invoice Header";DocumentReference: Text;DocumentReferenceTxt:Text);
    VAR
        FIKMgt: Codeunit FIKManagement;
    begin
        DocumentReference := '';
        DocumentReferenceTxt := '';
        DocumentReference :=  FIKMgt.GetFIK71String(SalesInvoiceHeader."No.");
        IF DocumentReference <> '' THEN
          DocumentReferenceTxt := DocumentReferenceCaptionbl;
    end;`

**Comment by AndreiPanko** [comment]
Good news! FIK extension was added to the repo:
https://github.com/Microsoft/ALAppExtensions/tree/master/FIK

Looking forward to seeing your pull request :)
