### ISSUE TITLE
[Event Request] CU1000 "Job Calculate WIP"

### ISSUE THREAD

**Issue by MarioSopena** [microsoft/ALAppExtensions#10783]
Hello team,
This issue is related with #10778.

In order to be able to handle potential new calculation methods, it would be interesting to add 2 new events.

//Current Code------------------------------------------------
local procedure CalcWIP(var JobTask: Record "Job Task"; JobWIPTotal: Record "Job WIP Total")
    var
        JobWIPMethod: Record "Job WIP Method";
    begin
        if JobComplete then begin
            JobTask."Recognized Sales Amount" := JobTask."Contract (Invoiced Price)";
            JobTask."Recognized Costs Amount" := JobTask."Usage (Total Cost)";
            exit;
        end;

        with JobWIPMethod do begin
            Get(JobWIPTotal."WIP Method");
            case "Recognized Costs" of
                "Recognized Costs"::"Cost of Sales":
                    CalcCostOfSales(JobTask, JobWIPTotal);
                "Recognized Costs"::"Cost Value":
                    CalcCostValue(JobTask, JobWIPTotal);
                "Recognized Costs"::"Contract (Invoiced Cost)":
                    CalcContractInvoicedCost(JobTask);
                "Recognized Costs"::"Usage (Total Cost)":
                    CalcUsageTotalCostCosts(JobTask);
            end;
            case "Recognized Sales" of
                "Recognized Sales"::"Contract (Invoiced Price)":
                    CalcContractInvoicedPrice(JobTask);
                "Recognized Sales"::"Usage (Total Cost)":
                    CalcUsageTotalCostSales(JobTask);
                "Recognized Sales"::"Usage (Total Price)":
                    CalcUsageTotalPrice(JobTask);
                "Recognized Sales"::"Percentage of Completion":
                    CalcPercentageofCompletion(JobTask, JobWIPTotal);
                "Recognized Sales"::"Sales Value":
                    CalcSalesValue(JobTask, JobWIPTotal);
            end;
        end;
    end;
//end Current Code------------------------------------------------

//Suggested Code----------------------------------------------
local procedure CalcWIP(var JobTask: Record "Job Task"; JobWIPTotal: Record "Job WIP Total")
    var
        JobWIPMethod: Record "Job WIP Method";
    begin
        if JobComplete then begin
            JobTask."Recognized Sales Amount" := JobTask."Contract (Invoiced Price)";
            JobTask."Recognized Costs Amount" := JobTask."Usage (Total Cost)";
            exit;
        end;

        with JobWIPMethod do begin
            Get(JobWIPTotal."WIP Method");

//New Event--------------
         OnBeforeCalcCosts(JobTask,JobWIPTotal,JobWIPMethod,IsHandled);
//New Event--------------
            
         If not IsHandled then begin
            case "Recognized Costs" of
                "Recognized Costs"::"Cost of Sales":
                    CalcCostOfSales(JobTask, JobWIPTotal);
                "Recognized Costs"::"Cost Value":
                    CalcCostValue(JobTask, JobWIPTotal);
                "Recognized Costs"::"Contract (Invoiced Cost)":
                    CalcContractInvoicedCost(JobTask);
                "Recognized Costs"::"Usage (Total Cost)":
                    CalcUsageTotalCostCosts(JobTask);
            end;
         end;

//New Event--------------
         OnBeforeCalcSales(JobTask,JobWIPTotal,JobWIPMethod,IsHandled);
//New Event--------------
            
         If not IsHandled then begin
            case "Recognized Sales" of
                "Recognized Sales"::"Contract (Invoiced Price)":
                    CalcContractInvoicedPrice(JobTask);
                "Recognized Sales"::"Usage (Total Cost)":
                    CalcUsageTotalCostSales(JobTask);
                "Recognized Sales"::"Usage (Total Price)":
                    CalcUsageTotalPrice(JobTask);
                "Recognized Sales"::"Percentage of Completion":
                    CalcPercentageofCompletion(JobTask, JobWIPTotal);
                "Recognized Sales"::"Sales Value":
                    CalcSalesValue(JobTask, JobWIPTotal);
            end;
        end;
    end;
end;
//end Suggested Code----------------------------------------------

[IntegrationEvent(false, false)]
local procedure OnBeforeCalcCosts( var JobTask : Record "Job Task"; var JobWIPTotal : Record "Job WIP Total"; var JobWIPMethod : Record "Job WIP Method"; var IsHandled : Boolean )
begin
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeCalcSales( var JobTask : Record "Job Task"; var JobWIPTotal : Record "Job WIP Total"; var JobWIPMethod : Record "Job WIP Method"; var IsHandled : Boolean )
begin
end;

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
