### ISSUE TITLE
Codeunit 1255 "Match Bank Payments" procedure MatchEntries

### ISSUE THREAD

**Issue by tyurm** [microsoft/ALAppExtensions#10789]
Please add event to MatchEntries procedure:

![image](https://user-images.githubusercontent.com/45788765/106181434-43822480-61a6-11eb-9105-d85b635420dd.png)

Code from screenshot:
```
//Required Event >>
IsHandled := false;
OnMatchEntriesOnBeforeGetApplicableRemainingAmount(TempLedgerEntryMatchingBuffer, BankAccReconciliationLine, UsePaymentDiscounts, RemainingAmount, IsHandled);
if not IsHandled then
//Required Event <<
	RemainingAmount := TempLedgerEntryMatchingBuffer.GetApplicableRemainingAmount(BankAccReconciliationLine, UsePaymentDiscounts);
```

```
procedure OnMatchEntriesOnBeforeGetApplicableRemainingAmount(var TempLedgerEntryMatchingBuffer: Record "Ledger Entry Matching Buffer" temporary; var BankAccReconciliationLine: Record "Bank Acc. Reconciliation Line"; UsePaymentDiscounts: Boolean; var RemainingAmount: Decimal; var IsHandled: Boolean)
begin
end;
```

We need to change the RemainingAmount value according to internal logic.

**Comment by StanPesotskiy** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please replace the screenshots with text.

**Comment by tyurm** [comment]
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
> Please replace the screenshots with text.

Hello, just have updated the initial request with code from screenshot.

**Comment by StanPesotskiy** [comment]
Keep few lines of code before and after the place where you want to put the call of the event. Now it is good enough. Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
