### ISSUE TITLE
[Event Request] CodeUnit 311 - Item-Check Avail. - SalesLineShowWarning() - OnSalesLineShowWarningOnBeforeShowWarning()

### ISSUE THREAD

**Issue by i-dhahri** [microsoft/ALAppExtensions#10798]
Hello, would it be possible to have  two other parameters in the event "OnSalesLineShowWarningOnBeforeShowWarning" in CodeUnit 311 - "Item-Check Avail.", procedure : SalesLineShowWarning(), Like this :

![image](https://user-images.githubusercontent.com/77328410/106252985-2e91a980-6217-11eb-999e-3fb369b72cc8.png)

Cordially.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
