### ISSUE TITLE
parameter request - codeunit 12 "Gen. Jnl.-Post Line" - FinishPosting() - OnAfterInsertGlobalGLEntry() - GenJnlLine

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#10790]
`OnBeforeInsertGLEntry()` passes the source `GenJnlLine`, but `OnAfterInsertGLEntry()` does not. This is inconsistent and inconvenient.

We need to take some action after the real `G/L Entry` is inserted, which depends on the `GenJnlLine` from which it is inserted.

It seems that right now we will have to use `OnAfterFinishPosting()`, which _does_ receive the `GenJnlLine`, and filter based on its received `GLReg`'s `From` and `To Entry No.` to determine which G/L Entries to affect, if that even works...

The proper solution would be for `OnAfterInsertGLEntry()` also to receive the `GenJnlLine`, so we'd get a call for each GLE created and be able to do what we need to, based on the GJL.

So, please change like this:
```al
    procedure FinishPosting(GenJnlLine: Record "Gen. Journal Line") IsTransactionConsistent: Boolean
    [...]
        if TempGLEntryBuf.FindSet() then begin
            repeat
                [...]
                OnBeforeInsertGlobalGLEntry(GlobalGLEntry, GenJnlLine, GLReg);
                GlobalGLEntry.Insert(true);

		// from
                // OnAfterInsertGlobalGLEntry(GlobalGLEntry, TempGLEntryBuf, NextEntryNo);
		// to
                OnAfterInsertGlobalGLEntry(GlobalGLEntry, GenJnlLine, TempGLEntryBuf, NextEntryNo);
            until TempGLEntryBuf.Next() = 0;

            [...]
        OnAfterFinishPosting(GlobalGLEntry, GLReg, IsTransactionConsistent, GenJnlLine);
    end;
```

and like this:
```al
    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertGlobalGLEntry(var GLEntry: Record "G/L Entry"; GenJournalLine: Record "Gen. Journal Line"; var TempGLEntryBuf: Record "G/L Entry"; var NextEntryNo: Integer)
    begin
    end;
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
