### ISSUE TITLE
Add Publishers in Item Tracking Navigate Mgt. Codeunit

### ISSUE THREAD

**Issue by PavlosPGP** [microsoft/ALAppExtensions#10807]
No suitable event publishers exist in codeunit (6529) "Item Tracking Navigate Mgt." in order to extend the base functionality. More precisely in function "FindTrackingRecords" should be at least one event publisher to make it possible to fill in the buffer with records from custom table(s).

Thank you.

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
