### ISSUE TITLE
Add Parameter in OnBeforeCustPostApplyCustLedgEntry publisher in Codeunit 226

### ISSUE THREAD

**Issue by PavlosPGP** [microsoft/ALAppExtensions#10805]
Hi Team,
The event publisher "OnBeforeCustPostApplyCustLedgEntry" that exists in codeunit 226 - "CustEntry-Apply Posted Entries" currently takes one parameter to HideProgressWindow which is useful. However, this is the only parameter that currently has and this makes the publisher useless. A parameter for "Customer Ledger Entry" should be added as well.

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
