### ISSUE TITLE
[Event Request] T77 "Report Selections" - procedure GetPurchaseOrderEmailAddress()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#10804]
```
    local procedure GetPurchaseOrderEmailAddress(BuyFromVendorNo: Code[20]; RecVar: Variant; ReportUsage: Enum "Report Selection Usage"): Text[250]
    var
        PurchaseHeader: Record "Purchase Header";
        OrderAddress: Record "Order Address";
        RecRef: RecordRef;
    begin

----------------------- ADD EVENT ----------------------
       IsHandled := false;
       OnBeforeGetPurchaseOrderEmailAddress(BuyFromVendorNo, RecVar, ReportUsage, OrderAddress, IsHandled);
       if IsHandled then
           exit(OrderAddress."E-Mail");
----------------------------------------------------------

        if BuyFromVendorNo = '' then
            exit('');

        if ReportUsage <> Usage::"P.Order" then
            exit('');

        RecRef.GetTable(RecVar);
        if RecRef.Number <> DATABASE::"Purchase Header" then
            exit('');

        PurchaseHeader := RecVar;
        if PurchaseHeader."Order Address Code" = '' then
            exit('');

        if not OrderAddress.Get(BuyFromVendorNo, PurchaseHeader."Order Address Code") then
            exit('');

        exit(OrderAddress."E-Mail");
    end;

......

[IntegrationEvent(false, false)]
local procedure OnBeforeGetPurchaseOrderEmailAddress(BuyFromVendorNo: Code[20]; RecVar: Variant; ReportUsage: Enum "Report Selection Usage"; var OrderAddress: Record "Order Address"; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by dtkb** [comment]
The publisher added was

    local procedure OnBeforeGetPurchaseOrderEmailAddress(BuyFromVendorNo: Code[20]; RecVar: Variant; ReportUsage: Enum "Report Selection Usage"; var OrderAddress: Record "Order Address"; var EmailAddress: Text[250]; var IsHandled: Boolean)

The `var OrderAddress` there is pointless, since (a) the subscriber just gets a brand-new uninitialised record, and (b) if they did anything to change it via the `var` that would just get trampled anyway by the `OrderAddress.Get()` later in `GetPurchaseOrderEmailAddress()`. I see no reason to pass `OrderAddress`, `var` or not.

**Comment by StanPesotskiy** [comment]
@dtkb, please create a new request with the link to this one if you need a correction. 
We do not track already closed GitHub requests.

**Comment by dtkb** [comment]
https://github.com/microsoft/ALAppExtensions/issues/11996
