### ISSUE TITLE
Codeunit 90 "CheckAndUpdate" execution order

### ISSUE THREAD

**Issue by Bleika** [microsoft/ALAppExtensions#1080]
Hi,

While testing my BC project, I realized that code execution order in COD90 has changed.

If Warehouse Receipt is mandatory, then it should be impossible to post an order directly from it's card.
If a user tries to post it directly, he/she must receive an error indicating that it's not allowed.

All this standard code is still in place, but in BC the WhseReceipt condition check isn't performed until way AFTER the progress Dialog is opened. Was this changed intentionally or was an accident?
_(As a matter of fact it's only checked when you're far into execution - too far to even fit in a single screenshot)_ 

I've marked the interesting code in bold:

**LOCAL CheckAndUpdate(VAR PurchHeader : Record "Purchase Header")**
WITH PurchHeader DO BEGIN
  // Check
  CheckMandatoryHeaderFields(PurchHeader);
  IF GenJnlCheckLine.DateNotAllowed("Posting Date") THEN
    FIELDERROR("Posting Date",PostingDateNotAllowedErr);

  IF TransportMethod.GET("Transport Method") AND TransportMethod."Port/Airport" THEN
    TESTFIELD("Entry Point");

  PaymentTerms.GET("Payment Terms Code");
  SetPostingFlags(PurchHeader);
  **InitProgressWindow(PurchHeader);**   <--- Dialog opens

  InvtPickPutaway := "Posting from Whse. Ref." <> 0;
  "Posting from Whse. Ref." := 0;

  CheckDim(PurchHeader);

  IF Invoice THEN
    CheckFAPostingPossibility(PurchHeader);

  CheckPostRestrictions(PurchHeader);

  CheckICDocumentDuplicatePosting(PurchHeader);

  IF IsCreditDocType AND Invoice THEN BEGIN
    IF PurchSetup."Correct. Doc. No. Mandatory" THEN
      TESTFIELD("Corrected Invoice No.")
    ELSE BEGIN
      IF "Corrected Invoice No." = '' THEN
        IF NOT CONFIRM(Text1100000,FALSE) THEN
          ERROR(Text1100011);
    END;
    IF "Corrected Invoice No." <> '' THEN
      "Posting Description" := FORMAT(Text1100104) + ' ' + "No."
  END;

  IF (Receive OR Invoice) AND (NOT IsCreditDocType) THEN BEGIN
    TESTFIELD("Payment Method Code");
    TESTFIELD("Payment Terms Code");
  END;

  IF Invoice THEN
    Invoice := CalcInvoice(PurchHeader);

  IF Invoice THEN
    CopyAndCheckItemCharge(PurchHeader);

  IF Invoice AND NOT IsCreditDocType THEN BEGIN
    TESTFIELD("Due Date");
    PaymentTerms.VerifyMaxNoDaysTillDueDate("Due Date","Document Date",FIELDCAPTION("Due Date"));
  END;

  IF Receive THEN BEGIN
    Receive := **CheckTrackingAndWarehouseForReceive(PurchHeader);** <-- check is within this fx
    IF NOT InvtPickPutaway THEN
      IF CheckIfInvPutawayExists(PurchHeader) THEN
        ERROR(InvPutAwayExistsErr);
  END;

**Comment by AlexanderYakunin** [comment]
Why do you think it is a problem?
