### ISSUE TITLE
[Event Request] - Table 5406 "Prod. Order Line" - OnBeforeGetUpdateFromSKU 

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10808]
Hello. In Table 5406 Prod. Order Line, we use the event OnBeforeGetUpdateFromSKU to change the Item record and the SKU record under some conditions. But these two event parameters don't have "var" in front of them, so if we change them in our event subscriber, our changes won't be saved outside of it.

Is it possible to add "var" in front of the two parameters "Item" and "SKU" in this event ?

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetUpdateFromSKU(var ProdOrderLine: Record "Prod. Order Line"; VAR SKU: Record "Stockkeeping Unit"; VAR Item: Record Item; var IsHandled: Boolean)
    begin
    end;

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
