### ISSUE TITLE
 Missing Publishers in Codeunit 370 Bank Acc. Reconsiliation Post

### ISSUE THREAD

**Issue by PavlosPGP** [microsoft/ALAppExtensions#10806]
Can you please add the following publishers in codeunit 370 in order to be able to extend the functionality of Bank Reconsiliation Post?

1. Function TransferToBankStmt inside the loop of BankAccReconLine record before the Insert of BankAccStmtLine.

2. Function CloseCheckLedgEntry inside the loop of CheckLedgEntry before the modify of BankAccLedgEntry.

Thank you.

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
