### ISSUE TITLE
Added Missing Parameter from Publishers in Codeunit 99000832 function TransferSalesLineToItemJnlLine

### ISSUE THREAD

**Issue by PavlosPGP** [microsoft/ALAppExtensions#10809]
In Codeunit "Sales Line-Reserve" (ID: 99000832). function "TransferSalesLineToItemJnlLine", the ItemJnlLine record variable is missing from all the publishers in this functions. The Item Journal Line variable together with Sales Line are the main variables for this function and should exists in all publishers. Sales Line exists but Item Journal Line is missing and should be added, otherwise cannot take advantage of the existing publishers as is.

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
