### ISSUE TITLE
[Request-for-external] Codeunit 10752 "SII Doc. Upload Management" - UploadManualDocument

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10813]
Can you remove [Scope('OnPrem')] from procedure UploadManualDocument in codeunit 10752 "SII Doc. Upload Management"?

**Comment by AlexanderYakunin** [comment]
No, this procedure calls other procedures with dotnet variables, so you will not be able to run this procedure in extensions.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
