### ISSUE TITLE
[Request-for-external] Codeunit 10753 "SII Job Upload Pending Docs." - CreateSIIRequestForVendLedgEntry

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10811]
Can you remove [Scope('OnPrem')] from procedure CreateSIIRequestForVendLedgEntry in codeunit 10753 "SII Job Upload Pending Docs."

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
