### ISSUE TITLE
[Event Request] Codeunit 92 "Purch.-Post + Print" - OnBeforeOnRun

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#10818]
Hi, would it be possible to get an event OnBeforeOnRunin codeunit 92 "Purch.-Post + Print", like this :

```
    trigger OnRun()
    var
        PurchHeader: Record "Purchase Header";
    begin
        OnBeforeOnRun(PurchHeader);
        PurchHeader.Copy(Rec);
        Code(PurchHeader);
        Rec := PurchHeader;
    end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnRun(var PurchHeader: Record "Purchase Header")
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
