### ISSUE TITLE
[Event Request] Codeunit 10 "Type Helper"- OnBeforeGetFieldLength

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10819]
Hi, in the codeunit 10 "Type Helper", would it be possible to get an event OnBeforeGetFieldLength, like this :

![image](https://user-images.githubusercontent.com/76154006/106290199-7c73d500-624a-11eb-8cd5-8265a9f1add9.png)
```
    procedure GetFieldLength(TableNo: Integer; FieldNo: Integer): Integer
    var
        "Field": Record "Field";
        IsHandled: Boolean;
    begin
        IsHandled: false;
        OnBeforeGetFieldLength(Field, IsHandled);
        if IsHandled then
        exit(Field.Len);
        if GetField(TableNo, FieldNo, Field) then
            exit(Field.Len);

        exit(0);
    end;

```
![image](https://user-images.githubusercontent.com/76154006/106290721-0d4ab080-624b-11eb-8b17-ea78dc378c9e.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetFieldLength(var "Field": Record "Field"; var IsHandled: Boolean)
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
