### ISSUE TITLE
[Request-for-external] Codeunit 7000003 "BG/PO-Post and Print" - PayablePostOnly

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#10810]
Can you remove [Scope('OnPrem')] from procedure PayablePostOnly in codeunit 7000003 "BG/PO-Post and Print"?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
