### ISSUE TITLE
[Event Request] Codeunit 7002 "Price Calculation - V16" - OnBeforeCalcBestAmount

### ISSUE THREAD

**Issue by mhoury** [microsoft/ALAppExtensions#10815]
[Event Request] Codeunit 7002 "Price Calculation - V16" - OnBeforeCalcBestAmount

Could we please have a new published event OnBeforeCalcBestAmount
 in Codeunit 7002 "_Price Calculation - V16_" within the _CalcBestAmount(...)_ function?

    procedure CalcBestAmount(AmountType: Enum "Price Amount Type"; var PriceCalculationBufferMgt: Codeunit "Price Calculation Buffer Mgt."; var PriceListLine: Record "Price List Line") FoundBestPrice: Boolean;
    var
        BestPriceListLine: Record "Price List Line";
    begin
    +   OnBeforeCalcBestAmount(AmountType, PriceCalculationBufferMgt, PriceListLine)

        PriceListLine.SetRange(Status, PriceListLine.Status::Active);
        if PriceListLine.FindSet() then
            repeat
                if PriceCalculationBufferMgt.IsInMinQty(PriceListLine) then begin
                    PriceCalculationBufferMgt.ConvertAmount(AmountType, PriceListLine);
                    PickBestLine(AmountType, PriceListLine, BestPriceListLine, FoundBestPrice);
                end;
            until PriceListLine.Next() = 0;
        if FoundBestPrice then
            PriceListLine := BestPriceListLine;
    end;

with the new event published as follows:

    +   [IntegrationEvent(false, false)]
    +   local procedure OnBeforeCalcBestAmount(AmountType: Enum "Price Amount Type"; var PriceCalculationBufferMgt: Codeunit "Price Calculation Buffer Mgt."; var PriceListLine: Record "Price List Line")
    +   begin
    +   end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
