### ISSUE TITLE
Purchase Order Over-Receiving in code

### ISSUE THREAD

**Issue by JayDashti** [microsoft/ALAppExtensions#10828]
Could we have this option to over receive a Purchase Order in code as well? When we validate Qty To Receive in code it does not work because the base app is relying on CurrentFieldNo and xRec right now which are not available in code!

PurchaseLine.Get(...)
PurchaseLine.Validate("Qty. To Receive", n) //where n is a value greater than PurchaseLine.Quantity
...

I wanted to know if writing several subscribers and bunch of IsHandled=true is my only option to get around this or you have this requirement in the queue to be added in a future release. Thanks!

This is on an integration where the receipt qty is being imported from a third party solution using API and Qty to receive gets validated and order gets posted with over received qty all in API backend code.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
