### ISSUE TITLE
[Event Request] Codeunit 227 "VendEntry-Apply Posted Entries"- OnBeforeApplyVendEntryFormEntry

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10824]
Hi, in the Codeunit 227 "VendEntry-Apply Posted Entries", would it be possible to get an event OnAfterVendPostApplyVendLedgEntry, like this :

![image](https://user-images.githubusercontent.com/76154006/106303689-b51baa80-625a-11eb-9440-90175b8dd45f.png)

```
    procedure ApplyVendEntryFormEntry(var ApplyingVendLedgEntry: Record "Vendor Ledger Entry")
    var
        VendLedgEntry: Record "Vendor Ledger Entry";
        ApplyVendEntries: Page "Apply Vendor Entries";
        VendEntryApplID: Code[50];
        IsHandled: Boolean;
    begin
        IsHandled:= false;
        OnBeforeApplyVendEntryFormEntry(IsHandled);
        if not IsHandled then
        if not ApplyingVendLedgEntry.Open then
            Error(CannotApplyClosedEntriesErr);

```
![image](https://user-images.githubusercontent.com/76154006/106303751-ca90d480-625a-11eb-9464-f46449caf5e3.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeApplyVendEntryFormEntry(var IsHandled: Boolean);
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
