### ISSUE TITLE
[Request-for-external] table 37 "Sales Line" - GetSKU()

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#10827]
Can you change GetSKU to be able to get SKU as reference parameter? Like the GetSalesHeader procedure?

```
    local procedure GetSKU(): Boolean
    // >>>>>>>>>>>>>>>>>>>>>
    begin
        exit(GetSKU(SKU));
    end;

    procedure GetSKU(var SKU: Record "Stockkeeping Unit") Result: Boolean
    // <<<<<<<<<<<<<<<<<<<<<<
    begin
        if (SKU."Location Code" = "Location Code") and
           (SKU."Item No." = "No.") and
           (SKU."Variant Code" = "Variant Code")
        then
            exit(true);
        if SKU.Get("Location Code", "No.", "Variant Code") then
            exit(true);

        Result := false;
        OnAfterGetSKU(Rec, Result);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
