### ISSUE TITLE
[Event Request] Table 49 "Invoice Post. Buffer" - OnBeforeCalcDiscountNoVAT

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10829]
Hello. In Table 49 Invoice Post. Buffer, in procedure CalcDiscountNoVAT we would like to replace standard code by our. To do so, we would need a IsHandled and an event publisher, like this : 

    procedure CalcDiscountNoVAT(DiscountAmount: Decimal; DiscountAmountACY: Decimal)
    var
        IsHandled : boolean;
    begin
        IsHandled := false;
        OnBeforeCalcDiscountNoVAT(Rec, IsHandled);
        if IsHandled then
            exit;

        "VAT Base Amount" := DiscountAmount;
        "VAT Base Amount (ACY)" := DiscountAmountACY;
        Amount := "VAT Base Amount";
        "Amount (ACY)" := "VAT Base Amount (ACY)";
        "VAT Base Before Pmt. Disc." := "VAT Base Amount";
    end;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcDiscountNoVAT(var InvoicePostBuffer : Record "Invoice Post. Buffer"; var IsHandled : boolean)
    begin
    end;

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
