### ISSUE TITLE
[Request-for-external] table 83 "Item Journal Line" - GetUnitAmount

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#10826]
Can you change procedure GetUnitAmount in table 83 "Item Journal Line" to global?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
