### ISSUE TITLE
[Event Request] Codeunit 74 "Purch.-Get Receipt"- OnBeforeInsertLines

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10822]
Hi, would it be possible to modify the event OnBeforeInsertLines in Codeunit 74 "Purch.-Get Receipt" to insert PurchLine parameter, like this :
![image](https://user-images.githubusercontent.com/76154006/106296982-93b6c080-6252-11eb-9014-a920b32bb2ef.png)
```
    procedure CreateInvLines(var PurchRcptLine2: Record "Purch. Rcpt. Line")
    var
        TransferLine: Boolean;
        PrepmtAmtToDeductRounding: Decimal;
        IsHandled: Boolean;
        ShowDifferentPayToVendMsg: Boolean;
    begin
        IsHandled := false;
        OnBeforeCreateInvLines(PurchRcptLine2, TransferLine, IsHandled);
        if IsHandled then
            exit;

        with PurchRcptLine2 do begin
            SetFilter("Qty. Rcd. Not Invoiced", '<>0');
            OnCreateInvLinesOnBeforeFind(PurchRcptLine2);
            if Find('-') then begin
                PurchLine.LockTable();
                PurchLine.SetRange("Document Type", PurchHeader."Document Type");
                PurchLine.SetRange("Document No.", PurchHeader."No.");
                PurchLine."Document Type" := PurchHeader."Document Type";
                PurchLine."Document No." := PurchHeader."No.";

                OnBeforeInsertLines(PurchLine, PurchHeader);

```
![image](https://user-images.githubusercontent.com/76154006/106297067-a4ffcd00-6252-11eb-8862-51a9f062603a.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertLines(var PurchLine: Record "Purchase Line"; var PurchaseHeader: Record "Purchase Header")
    begin
    end;
```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
