### ISSUE TITLE
[Event Request] Codeunit 227 "VendEntry-Apply Posted Entries"- OnAfterVendPostApplyVendLedgEntry

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#10823]
Hi, in the Codeunit 227 "VendEntry-Apply Posted Entries", would it be possible to get an event OnAfterVendPostApplyVendLedgEntry, like this :

![image](https://user-images.githubusercontent.com/76154006/106302986-ec3d8c00-6259-11eb-8cb7-798b19e8eb43.png)
```
            EntryNoAfterApplication := FindLastApplDtldVendLedgEntry;
            if EntryNoAfterApplication = EntryNoBeforeApplication then
                Error(NoEntriesAppliedErr, GenJnlLine.FieldCaption("Applies-to ID"));

            if PreviewMode then
                GenJnlPostPreview.ThrowError;

            Commit();
            Window.Close;

            IsHandled:= false;
            OnAfterVendPostApplyVendLedgEntry(IsHandled);
            if not IsHandled then
            UpdateAnalysisView.UpdateAll(0, true);
        end;
    end;

```

![image](https://user-images.githubusercontent.com/76154006/106303009-f19ad680-6259-11eb-819a-32e6fc7d89f3.png)
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterVendPostApplyVendLedgEntry(var IsHandled: Boolean);
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
