### ISSUE TITLE
Select Folder Path

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/ALAppExtensions#1082]
Hello,

On Business Central I pretend to save a path on a page field.
First I tried to use the FileMgt.SelectFolderDialog but then I got a .Net Error since its a webclient.
Then I tried to Use the UPLOAD function but found out I can't use it in extensions.
Is it possible to do this in BC?

**Comment by JesperSchulz** [comment]
BC in the cloud does not support files, files paths or anything file like. Please use streams for your cloud solution. If you need more info, please post your question in one of our forums:

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
