### ISSUE TITLE
[Event Request] Codeunit 81 Sales-Post (Yes/No) - OnConfirmPostOnBeforeSetSelection

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10838]
Hi, would it possible to get an event OnConfirmPostOnBeforeSetSelection in codeunit 81, procedure Confirm Post, like this : 
![image](https://user-images.githubusercontent.com/73548802/106573669-395f7d80-653a-11eb-80ee-c542b87501cc.png)
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
