### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnBeforeOnDeleteSpecialOrderSaleLine

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10832]
Hello. In Table 39 "Purchase Line", in trigger OnDelete, we would like to add a condition at a specific place. To do so, we would need a IsHandled flag and an event publisher, like this : 

        IsHandled := false;
        OnBeforeOnDeleteSpecialOrderSaleLine(Rec, SalesOrderLine, IsHandled);
        if not IsHandled then
        if ("Special Order Sales Line No." <> 0) and ("Quantity Invoiced" = 0) then begin
            LockTable();
            SalesOrderLine.LockTable();
            if SalesOrderLine.Get(
                 SalesOrderLine."Document Type"::Order, "Special Order Sales No.", "Special Order Sales Line No.")
            then begin
                SalesOrderLine."Special Order Purchase No." := '';
                SalesOrderLine."Special Order Purch. Line No." := 0;
                SalesOrderLine.Modify();
            end;
        end;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnDeleteSpecialOrderSaleLine(var PurchaseLine: Record "Purchase Line"; var SalesOrderLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
