### ISSUE TITLE
[Event Request] Table 39 - "Purchase Line" - OnBeforeInitOutstandingAndQtyToShipReceive

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10837]
Hello. In table 39 "Purchase Line", in the procedure InitOutstandingAndQtyToShipReceive, in the event OnBeforeInitOutstandingAndQtyToShipReceive, I would like to manipulate xRec. But it's not in the event parameters. Is it possible to add it please. Like in this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitOutstandingAndQtyToShipReceive(var PurchaseLine: Record "Purchase Line"; var xPurchaseLine: Record "Purchase Line"; var TempPurchLine: Record "Purchase Line" temporary; var IsHandled: Boolean)
    begin
    end;

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
