### ISSUE TITLE
[Event Request] Codeunit 81 - OnBeforeSalesPostRun

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10834]
Hi, would it be possible to get an event OnBeforeSalesPostRun in Codeunit 80 Sales Post (Yes/No), procedure Code, like this : 
![image](https://user-images.githubusercontent.com/73548802/106477910-f1dce100-64a8-11eb-8d3f-fb987649c807.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesPostRun(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean )
    begin
    end; 
```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
