### ISSUE TITLE
[Event Request] Codeunit 81 - Sales-Post (Yes/No) - OnBeforeRun

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10833]
Hi, would it be possible to get an event OnBeforeRun in codeunit 80, trigger OnRun, like this : 
![image](https://user-images.githubusercontent.com/73548802/106477167-269c6880-64a8-11eb-9a7d-d5040681e119.png)
?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
