### ISSUE TITLE
[Access Request] Page 55 - "Purch. Invoice Subform" – Global Variable: DocumentTotals

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#10836]
Could you please move the global variable definition for „DocumentTotals“ into the protected var section. That way we can access it from our extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
