### ISSUE TITLE
[Event Request] Codeunit 81 - Sales-Post (Yes/No) - OnConfirmPostOnDocumentTypeIsOrder

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10839]
Hi, would it possible to get an event OnConfirmPostOnDocumentTypeIsOrder in codeunit 81, procedure ConfirmPost, like this : 
![image](https://user-images.githubusercontent.com/73548802/106577726-010e6e00-653f-11eb-930c-036e6946af49.png)
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
