### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnPostItemTrackingForReceiptOnAfterRepeat

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10830]
HI, would it be possible to get an event OnPostItemTrackingForReceiptOnAfterRepeat in codeunit 80, procedure PostItemTracking, like this : 
![image](https://user-images.githubusercontent.com/73548802/106453443-a23aed00-6489-11eb-840a-337d31005356.png)

` OnPostItemTrackingForReceiptOnAfterRepeat(TempTrackingSpecification,ReturnRcptLine,ItemEntryRelation,IsHandled);`

```
    [IntegrationEvent(false, false)]
    local procedure OnPostItemTrackingForReceiptOnAfterRepeat( TempTrackingSpecification : Record "Tracking Specification" ; var ReturnRcptLine : Record "Return Receipt Line" ; var ItemEntryRelation : Record "Item Entry Relation" ; var IsHandled: Boolean)
    begin
    end; 
```
?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
