### ISSUE TITLE
Codeunit 82 Sales-Post + Print - OnBeforeSalesPostRun

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10842]
Hi, would it be possible to get an event OnBeforeSalesPostRun in codeunit 82, procedure Code, like this : 
![image](https://user-images.githubusercontent.com/73548802/106584568-a37e1f80-6546-11eb-88fe-2320f7a279ae.png)

   ```
 local procedure "Code"(var SalesHeader: Record "Sales Header")
    var
        SalesSetup: Record "Sales & Receivables Setup";
        SalesPostViaJobQueue: Codeunit "Sales Post via Job Queue";
        HideDialog: Boolean;
        IsHandled: Boolean;
        DefaultOption: Integer;
    begin
        HideDialog := false;
        IsHandled := false;
        DefaultOption := 3;
        OnBeforeConfirmPost(SalesHeader, HideDialog, IsHandled, SendReportAsEmail, DefaultOption);
        if IsHandled then
            exit;

        if not HideDialog then
            if not ConfirmPost(SalesHeader, DefaultOption) then
                exit;

        OnAfterConfirmPost(SalesHeader);

        SalesSetup.Get();
        if SalesSetup."Post & Print with Job Queue" and not SendReportAsEmail then
            SalesPostViaJobQueue.EnqueueSalesDoc(SalesHeader)
        else begin
            IsHandled := false;
            OnBeforeSalesPostRun(SalesHeader,IsHandled);
            if not IsHandled then begin
                CODEUNIT.Run(CODEUNIT::"Sales-Post", SalesHeader);
                GetReport(SalesHeader);
            end;
        end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesPostRun(var SalesHeader: Record "Sales Header"; var IsHandled : Boolean)
    begin
    end;
```

?
Thanks

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by VMotin** [comment]
updated

**Comment by StanPesotskiy** [comment]
Please put the code surrounding the place where you expect a new event call as a text not as a screenshot. It helps us quickly finding the right place if you put enough code to identify the unique place. Just copy&paste the code you have on the screenshot.

Are you sure that IsHandled parameter should be passed by value, without VAR? 
We have many event requests to process every day, if you make a mistake in your request it means double work for us and more time for you to get what you really need. Please be more careful.

**Comment by VMotin** [comment]
IsHandled should indeed be a Var, sorry for my mistake and the inconveniance, my comment has been updated

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
