### ISSUE TITLE
Codeunit 82 Sales-Post + Print - OnBeforeConfirmPost

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10843]
Hi, would it be possible to get an event OnBeforeConfirmPost in codeunit 82, procedure ConfirmPost like this : 
![image](https://user-images.githubusercontent.com/73548802/106586194-703c9000-6548-11eb-8df3-31a4c907a838.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeConfirmPost(var SalesHeader: Record "Sales Header")
    begin
    end;
```

?
Thanks

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by VMotin** [comment]
updated

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
