### ISSUE TITLE
Codeunit 82 Sales-Post + Print - OnConfirmPostOnDocumentTypeIsOrder

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10844]
Hi, would it be possible to get an event OnConfirmPostOnDocumentTypeIsOrder in codeunit 82, procedure ConfirmPost, like this : 
![image](https://user-images.githubusercontent.com/73548802/106586917-46d03400-6549-11eb-940d-a2ecd50d47ad.png)
?

```
local procedure ConfirmPost(var SalesHeader: Record "Sales Header"; DefaultOption: Integer): Boolean
    var
        ConfirmManagement: Codeunit "Confirm Management";
        Selection: Integer;
        IsHandled : Boolean;
    begin
        if DefaultOption > 3 then
            DefaultOption := 3;
        if DefaultOption <= 0 then
            DefaultOption := 1;

        with SalesHeader do begin
            case "Document Type" of
                "Document Type"::Order:
                    begin
                        IsHandled := false;
                        OnConfirmPostOnDocumentTypeIsOrder(SalesHeader,IsHandled);
                        if not IsHandled then begin
                            Selection := StrMenu(ShipInvoiceQst, DefaultOption);
                            if Selection = 0 then
                                exit(false);
                            Ship := Selection in [1, 3];
                            Invoice := Selection in [2, 3];
                        end;
                    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnConfirmPostOnDocumentTypeIsOrder(var SalesHeader: Record "Sales Header"; var IsHandled : Boolean)
    begin
    end;
```

Thanks

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by VMotin** [comment]
updated

**Comment by StanPesotskiy** [comment]
Please put the code surrounding the place where you expect a new event call as a text not as a screenshot. It helps us quickly finding the right place if you put enough code to identify the unique place. Just copy&paste the code you have on the screenshot.

Are you sure that IsHandled parameter should be passed by value, without VAR? 
We have many event requests to process every day, if you make a mistake in your request it means double work for us and more time for you to get what you really need. Please be more careful.

**Comment by VMotin** [comment]
IsHandled should indeed be a Var, sorry for my mistake and the inconveniance, my comment has been updated

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
