### ISSUE TITLE
[EventRequest] Codeunit 80 "Sales Post" - OnBeforeCheckMandatoryCustNoFields

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#10847]
Hi,

We would need an event publisher in codeunit 80 in **CheckMandatoryHeaderFields** function, like this:

![image](https://user-images.githubusercontent.com/44637002/106596462-32396f00-653c-11eb-9115-66c5f953d69d.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckMandatoryCustNoFields(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;

We need this event publisher because in some situations we create vacancy invoices, without "Sell-to Customer No." and "Bill-to Customer No.". In these situations, we need to skip testing of mandatory fields for "Sell-to Customer No." and "Bill-to Customer No.".

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
