### ISSUE TITLE
report 15000061 "Rem. Payment Order  - Export"

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [microsoft/ALAppExtensions#10846]
The downloaded file is in UTF-8 format but the bank only accepts ISO-8859-1. Can you add the option in the page 1200 "Bank Export/Import Setup" to choose the encoding for the downloaded file?

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
