### ISSUE TITLE
[Change Request] - Page (Diffrent Subforms) - CalculateTotals

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10856]
We like to request the following changes:
Objects: 
- Page "Sales Order Subform"
- Page "Sales Quote Subform"
- Page "Sales Invoice Subform"
- Page "Sales Cr. Memo Subform"
- Page "Blanket Sales Order Subform"

Function: CalculateTotals
Reason: Please make the function global so we can access the function in all pages mentioned above
Code to change: 
**procedure** CalculateTotals()
    var
        IsHandled: Boolean;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
