### ISSUE TITLE
[Field Change Request] - Table "Document Entry" - Field "Document Type"

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10858]
We like to request the following change:
Object: Table "Document Entry"
Field:  field(8; "Document Type")
Reason: Please change the type to an enum, to make it extensible so we can add our custom types.
Code to change: 
field(8; "Document Type"; Enum "Document Entry Doc Type")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
