### ISSUE TITLE
[IncludeSender Event Change Request] - Page "Item Avail. by Variant Lines" - OnAfterSet

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10855]
We like to request the following change:
Page "Item Avail. by Variant Lines"
Function: OnAfterSet
Reason: We need access to the global methods in the object while subscribing to the event
Code to change: set the IncludeSender to true
[IntegrationEvent(true, false)]
    local procedure OnAfterSet(ItemVariant: Record "Item Variant"; var Item: Record Item; AmountType: Option "Net Change","Balance at Date")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
