### ISSUE TITLE
[Event Request] Codeunit 261 MoveEntries - OnMoveVendorEntriesOnBeforeAccountingPeriod

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10852]
Hi, would it be possible to get an event OnMoveVendorEntriesOnBeforeAccountingPeriod in codeunit 261, procedure MoveVendorEntries, like this : 
![image](https://user-images.githubusercontent.com/73548802/106617533-04b9e900-656f-11eb-8483-09f4052098d1.png)

?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
