### ISSUE TITLE
[Event Request] Table 18 "Customer" - OnAfterLookupCity

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/ALAppExtensions#10850]
Table Customer, Field City, trigger OnLookup
Please add an event here:

![grafik](https://user-images.githubusercontent.com/46522333/106614788-08983c00-656c-11eb-99f6-299e45d38790.png)

![grafik](https://user-images.githubusercontent.com/46522333/106614726-f6b69900-656b-11eb-977c-35d91f084626.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
