### ISSUE TITLE
[Event Request] Codeunit 363 PostSales-Delete - OnInitDeleteHeaderOnAfterTransferFields

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10854]
Hi, would it be possible to get an event OnInitDeleteHeaderOnAfterTransferFields in Codeunit 363, procedure InitDeleteHeader, like this : 
![image](https://user-images.githubusercontent.com/73548802/106619657-1b613f80-6571-11eb-9543-f853a1191b6f.png)
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
