### ISSUE TITLE
[Event Request] Codeunit 364 PostPurch-Delete - OnAfterPurchInvHeaderPrepmtTransferFields

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10859]
Hi, would it be possible to get an event OnAfterPurchInvHeaderPrepmtTransferFields in codeunit 364, procedure InitDeleteHeader, like this : 
![image](https://user-images.githubusercontent.com/73548802/106632042-a0eaec80-657d-11eb-9421-e084d39ff773.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterPurchInvHeaderPrepmtTransferFields(var PurchHeader: Record "Purchase Header" )
    begin
    end;  
```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
