### ISSUE TITLE
[Request Event] Codeunit 5510 Production Journal Mgt OnAfterInitSetupValues

### ISSUE THREAD

**Issue by RCORELLA** [microsoft/ALAppExtensions#10853]
Hi,

I would like to ask for a new event in codeunit 5510 (Production Journal Mgt) in procedure InitSetupValues (onAfterInitSetupValues). Standard put directly the Workdate in a variable PostingDate, but maybe it is necessary to modify this date with other date. Really I can modify the item journal lines in other events, but the variable PostingDate in the page it is not possible modify it.

Signature would be:

OnAfterInitSetupValues (PostingDate: date; CalcBasedOn:Option "Actual Output","Expected Output")

Thanks in advance,

Roberto Corella
Dynasoft 2008

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
