### ISSUE TITLE
[Event Request] Codeunit 7322 "Create Inventory Pick/Movement" - SetFilterInternalMomement

### ISSUE THREAD

**Issue by hhoutaptean** [microsoft/ALAppExtensions#10867]
We would like to request an event in in "Create Inventory Pick/Movement" (CodeUnit 7322) called from “Internal Movement” (Page 7399) so we can add extra check(s) on Create Inventory Movement.
For our check it is required to be able apply several filters to reduce the lines and inventory movements created. 

**Event:**

```
  local procedure SetFilterInternalMomement(var InternalMovementLine: Record "Internal Movement Line"; InternalMovementHeader: Record "Internal Movement Header"): Boolean
    begin
        with InternalMovementLine do begin
            SetRange("No.", InternalMovementHeader."No.");
            SetFilter("Qty. (Base)", '>0');
           // START EVENT ++
           OnAfterSetFilterInternalMovement(InternalMovementLine, InternalMovementHeader);
           // END EVENT --
            exit(Find('-'));
        end;
    end;

```

**Publisher function:**
```
 [IntegrationEvent(false, false)]
 local procedure OnAfterSetFilterInternalMovement(var InternalMovementLine: Record "Internal Movement Line"; InternalMovementHeader: Record "Internal Movement Header")
 begin
 end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
