### ISSUE TITLE
[Event Request] table 36 "Sales Header" - OnAfterSetFieldsBilltoCustomer

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#10865]
Can you add xRec to event OnAfterSetFieldsBilltoCustomer?

```
        Reserve := BillToCustomer.Reserve;
        if "Document Type" = "Document Type"::Order then
            "Prepayment %" := BillToCustomer."Prepayment %";
        "Tax Area Code" := BillToCustomer."Tax Area Code";
        if ("Ship-to Code" = '') or ("Sell-to Customer No." <> BillToCustomer."No.") then
            "Tax Liable" := BillToCustomer."Tax Liable";

        // >>>>>>>>>>>>
        //OnAfterSetFieldsBilltoCustomer(Rec, BillToCustomer);
        OnAfterSetFieldsBilltoCustomer(Rec, xRec, BillToCustomer);
        // <<<<<<<<<<<<
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
