### ISSUE TITLE
[Event Request] Report 5685 - Copy Fixed Asset

### ISSUE THREAD

**Issue by AndreaRux** [microsoft/ALAppExtensions#10861]
Please add new Event 
Report 5685 - Copy Fixed Asset
in Trigger OnPreReport
OnAfterInsertFACopy(FA2,FA);

![image](https://user-images.githubusercontent.com/34539583/106737378-df80b580-6616-11eb-9629-73c3ff5e2608.png)

![image](https://user-images.githubusercontent.com/34539583/106737196-ad6f5380-6616-11eb-8ddd-f6e3a48f8dff.png)

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.

**Comment by AndreaRux** [comment]
Please Add new Event in
report 5685 "Copy Fixed Asset" 
in Trigger OnPreReport

![image](https://user-images.githubusercontent.com/34539583/106863166-68a3f500-66c8-11eb-8e38-9f73aaac7bc6.png)


    trigger OnPreReport()
    begin
        DefaultDim.LockTable();
        FADeprBook.LockTable();
        FA.LockTable();
        if FANo = '' then
            Error(Text000, FA.TableCaption, FA.FieldCaption("No."));
        if (FirstFANo = '') and not UseFANoSeries then
            Error(Text001);
        FA.Get(FANo);
        FADeprBook."FA No." := FANo;
        FADeprBook.SetRange("FA No.", FANo);
        DefaultDim."Table ID" := DATABASE::"Fixed Asset";
        DefaultDim."No." := FANo;
        DefaultDim.SetRange("Table ID", DATABASE::"Fixed Asset");
        DefaultDim.SetRange("No.", FANo);
        DefaultDim2 := DefaultDim;
        for I := 1 to NumberofCopies do begin
            FA2 := FA;
            FA2."No." := '';
            FA2."Last Date Modified" := 0D;
            FA2."Main Asset/Component" := FA2."Main Asset/Component"::" ";
            FA2."Component of Main Asset" := '';
            if UseFANoSeries then
                FA2.Insert(true)
            else begin
                FA2."No." := FirstFANo;
                if NumberofCopies > 1 then
                    FirstFANo := IncStr(FirstFANo);
                if FA2."No." = '' then
                    Error(Text002, FA.TableCaption, FA.FieldCaption("No."));
                FA2.Insert(true);
            end;
            if DefaultDim.Find('-') then
                repeat
                    DefaultDim2 := DefaultDim;
                    DefaultDim2."No." := FA2."No.";
                    DefaultDim2.Insert(true);
                until DefaultDim.Next = 0;
            if FADeprBook.Find('-') then
                repeat
                    FADeprBook2 := FADeprBook;
                    FADeprBook2."FA No." := FA2."No.";
                    FADeprBook2.Insert(true);
                until FADeprBook.Next = 0;
            if FA2.Find then begin
                ;
                FA2."Last Date Modified" := 0D;
                FA2.Modify();
            end;
            // Add new Event here, after all Inserts and Modifys
            OnAfterInsertFACopy(FA2, FA);
        
        end;
    end;

...

    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertFACopy(FA2: Record "Fixed Asset"; FA: Record "Fixed Asset")
    begin
        // new Event
    end;

see also attached File

[CopyFixedAsset.Report.al.txt](https://github.com/microsoft/ALAppExtensions/files/5924086/CopyFixedAsset.Report.al.txt)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
