### ISSUE TITLE
[Request-for-external] table 37 "Sales Line" - ValidateUnitCostLCYOnGetUnitCost(Item: Record Item)

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#10868]
Can you change procedure ValidateUnitCostLCYOnGetUnitCost(Item: Record Item) to global?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
