### ISSUE TITLE
[Change Request] - Sales Pages (Subform)- add protected variabels

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10879]
We like to request the following change:
Object:s 
- Page "Blanket Sales Order Subform"
- Page "Sales Quote Subform"
- Page "Sales Order Subform"
- Page "Sales Return Order Subform"
Reason: Please make the variables mentioned below to protected vars. So we can access them to calculate our values.
Code to change:
 protected var
    	TotalSalesHeader: Record "Sales Header";
        TotalSalesLine: Record "Sales Line";
VATAmount: Decimal;
	InvoiceDiscountAmount: Decimal;
        InvoiceDiscountPct: Decimal;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
