### ISSUE TITLE
Remove OnPrem scope on CheckContractGroupAccounts procedure in Codeunit 5940 ServContractManagement

### ISSUE THREAD

**Issue by sauerkreut** [microsoft/ALAppExtensions#10877]
Hello,

we want to use the CheckContractGroupAccounts procedure in Codeunit 5940 ServContractManagement in cloud environment but the scope is set to OnPrem. Can you remove the OnPrem scope? 
Thank you for your attention.
Walter

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
