### ISSUE TITLE
 Make standard page global variables accessible

### ISSUE THREAD

**Issue by clasalal** [microsoft/ALAppExtensions#10871]
Hello,

I need to make the global variable of totals of the following pages accessible to the pageextension as is the variable "TotalPurchaseLine" from the page "Purch. Invoice Subform":

![image](https://user-images.githubusercontent.com/64960257/106769672-7eb8a380-663d-11eb-922d-566f3efdb98d.png)

- "Purch. Cr. Memo Subform": variable "TotalPurchaseLine".
- "Blanket Purchase Order Subform": variable "TotalPurchaseLine".
- "Purchase Order Subform": variable "TotalPurchaseLine".
- "Purchase Quote Subform": variable "TotalPurchaseLine".
- "Purchase Return Order Subform": variable "TotalPurchaseLine".
- "Posted Purch. Cr. Memo Subform": variable "TotalPurchCrMemoHdr".
- "Posted Purch. Invoice Subform": variable "TotalPurchInvHdr".
- "Sales Invoice Subform": variable "TotalSalesLine".
- "Sales Cr. Memo Subform": variable "TotalSalesLine".
- "Blanket Sales Order Subform": variable "TotalSalesLine".
- "Sales Order Subform": variable "TotalSalesLine".
- "Sales Quote Subform": variable "TotalSalesLine".
- "Sales Return Order Subform": variable "TotalSalesLine".
- "Posted Sales Cr. Memo Subform": variable "TotalSalesCrMemoHdr".
- "Posted Sales Invoice Subform": variable "TotalSalesInvoiceHdr".

Please let me know as soon as it is available.
Thank you very much in advance.

Best Regards
Clara

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
