### ISSUE TITLE
[Event Request] Codeunit 392 Reminder-Make - OnBeforeCustLedgEntryOnHold

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10870]
Hi, would it be possible to get an event OnBeforeCustLedgEntryOnHold in codeunit 392, procedure FindAndMarkReminderCandidates, like this : 
![image](https://user-images.githubusercontent.com/73548802/106762627-4bbee180-6636-11eb-805a-1a40d9ac8518.png)

 ```
repeat
            FilterCustLedgEntries(ReminderLevel);
            if CustLedgEntry.FindSet then
                repeat
                    if CustLedgEntry."On Hold" = '' then begin
                        IsHandled := false;
                        OnBeforeCustLedgEntryOnHold(CustLedgEntry,IsHandled);
                        if not IsHandled then begin
```
```
 [IntegrationEvent(false, false)]
    local procedure OnBeforeCustLedgEntryOnHold(var CustLedgEntry: Record "Cust. Ledger Entry"; var IsHandled: Boolean)
    begin
    end;    
```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
