### ISSUE TITLE
Table 85 "Acc. Schedule Line", Filed 16 "Show": Change to Enum

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#10874]
We like to request the following change:
Object: Table "Acc. Schedule Line"
Field: field(16; "Show")
Reason: Please change the type to an enum, to make it extensible so we can add our custom types.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
