### ISSUE TITLE
[Change Request] - Purchase Pages (Subform)- add protected variabels

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10878]
We like to request the following change:
Object:s 
- Page "Purchase Quote Subform"
- Page "Purchase Order Subform"
- Page "Purchase Return Order Subform"
Reason: Please make the variables mentioned below to protected vars. So we can access them to calculate our values.
Code to change:
protected var
    	TotalPurchaseHeader: Record "Purchase Header";
        TotalPurchaseLine: Record "Purchase Line";
VATAmount: Decimal;
	InvoiceDiscountAmount: Decimal;
        InvoiceDiscountPct: Decimal;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
