### ISSUE TITLE
[Event Request] Codeunit 1012 "Job Jnl.-Post Line"

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#10881]
We miss the following events:
`OnBeforeRunWithCheck` and `OnAfterRunWithCheck`

Codeunit 1012:
![image](https://user-images.githubusercontent.com/45654195/106874426-d6a2e900-66d5-11eb-88ac-89790c7e21ec.png)

Codeunit 12:
![image](https://user-images.githubusercontent.com/45654195/106874457-e02c5100-66d5-11eb-89a8-9c8a9968805c.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
