### ISSUE TITLE
[EventRequest] Table 5901 "Service Item Line"

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#10888]
Hello MS,
Please help us in migrating our verticalized solution by adding below events to function RecreateServLines in "Service Item Line" table .
Version (BC17 Cu03). Requested event OnBeforeRecreateServLines.

    local procedure RecreateServLines(var ServLine2: Record "Service Line")
    var
        TempServLine: Record "Service Line" temporary;
    begin
        if ServLine2.Find('-') then begin
            ServLine2.LockTable();
            repeat
                TempServLine := ServLine2;
                TempServLine.Insert();
            until ServLine2.Next = 0;

            TempServLine.Find('-');

            OnBeforeRecreateServLines(ServLine2,Rec,xRec,IsHandled)

            repeat
                ServLine2.Get(TempServLine."Document Type", TempServLine."Document No.", TempServLine."Line No.");
                ServLine2.SetHideReplacementDialog(true);
                if TempServLine."No." <> '' then begin
                    ServLine.SetHideCostWarning(true);
                    ServLine2.Validate("No.", TempServLine."No.");
                    ServLine2."Spare Part Action" := TempServLine."Spare Part Action";
                    ServLine2."Component Line No." := TempServLine."Component Line No.";
                    ServLine2."Replaced Item No." := TempServLine."Replaced Item No.";
                    if TempServLine.Quantity <> 0 then
                        ServLine2.Validate(Quantity, TempServLine.Quantity);
                    ServLine2."Location Code" := TempServLine."Location Code";
                    if ServLine2.Type <> ServLine2.Type::" " then begin
                        if ServLine2.Type = ServLine2.Type::Item then begin
                            ServLine2.Validate("Variant Code", TempServLine."Variant Code");
                            if ServLine2."Location Code" <> '' then
                                ServLine2."Bin Code" := TempServLine."Bin Code";
                        end;
                        ServLine2.Validate("Unit of Measure Code", TempServLine."Unit of Measure Code");
                        ServLine2."Fault Reason Code" := TempServLine."Fault Reason Code";
                        ServLine2."Exclude Warranty" := TempServLine."Exclude Warranty";
                        ServLine2."Exclude Contract Discount" := TempServLine."Exclude Contract Discount";
                        ServLine2.Validate(Warranty, TempServLine.Warranty);
                    end;
                    ServLine2.Description := TempServLine.Description;
                    ServLine2."Description 2" := TempServLine."Description 2";
                    OnRecreateServLine(ServLine2, TempServLine);
                end;
                ServLine2.Modify(true);
            until TempServLine.Next = 0;
            TempServLine.DeleteAll();
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeRecreateServLines(var ServiceLine: Record "Service Line"; var ServiceItemLine: Record "Service Item Line"; xServiceItemLine: Record "Service Item Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.

**Comment by OSH-ZT** [comment]
> Please always put the full detailed signature of the requested events.
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
> Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot.
> It helps us finding the right place quickly if you put enough code to identify the unique place.

Done, thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
