### ISSUE TITLE
[EventRequest] Table 15 "G/L Account"

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#10883]
Hello MS,
Please help us in migrating our verticalized solution by adding below events in "G/L Account" table.
Standard Code (BC17 Cu03)
![image](https://user-images.githubusercontent.com/66109755/106895240-a7ea3a00-66f8-11eb-9999-2834d496bde8.png)

Modified Code
![image](https://user-images.githubusercontent.com/66109755/106895526-00213c00-66f9-11eb-903f-01a4897ffd5a.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
