### ISSUE TITLE
[Change Request] - Page "Purchase Order Subform"

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#10885]
We like to request the following change:
Object:  Page "Purchase Order Subform" 
Reason: Please add the bold code lines below. It is wrong to call the NoOnAfterValidate Logic when just changing the description. This code is the same as in the sales order subform - Description OnValidate Trigger
Code to change:
field(Description; Description)
                {
                    ApplicationArea = Suite;
                    ToolTip = 'Specifies a description of the entry of the product to be purchased. To add a non-transactional text line, fill in the Description field only.';

                    trigger OnValidate()
                    begin
                        DeltaUpdateTotals();

                        **if "No." = xRec."No." then
                            exit;**

                        NoOnAfterValidate();
                    end;
                }

![image](https://user-images.githubusercontent.com/68000891/106896187-86d21b00-66f1-11eb-9d42-6c0afe6c9c07.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
