### ISSUE TITLE
Wrong Parameter on OnDeleteAfterPostingOnAfterDeleteLinks event in codeunit 80 "Sales-Post"

### ISSUE THREAD

**Issue by PavlosPGP** [microsoft/ALAppExtensions#10889]
In function DeleteAfterPosting (codeunit 80 "Sales-Post") publisher OnDeleteAfterPostingOnAfterDeleteLinks takes as parameter the SalesLine variable which is not initialized at that point of code so this parameter is useless. Instead, the TempSalesLine should be passed as parameter for this publisher. I added the screenshot below for your convenience (parameter marked in red cycle).

![image](https://user-images.githubusercontent.com/63713670/106897848-272d3d00-66fc-11eb-8272-985352c513d5.png)

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
