### ISSUE TITLE
[Event Request] -codeunit 211 "Res. Jnl.-Check Line"

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#10880]
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckDimensions(var GenJnlLine: Record "Gen. Journal Line"; var CheckDone: Boolean)
    begin
    end;
```

Dimensionscheck in codeunit 211:  
![image](https://user-images.githubusercontent.com/45654195/106872660-d275cc00-66d3-11eb-9b34-770cea1ad3f5.png)

Dimensionscheck in Codeunit 11:  
![image](https://user-images.githubusercontent.com/45654195/106872795-fe914d00-66d3-11eb-8cba-c05ff5714a88.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
