### ISSUE TITLE
[Event Request] New parameter CalcType to OnBeforeSetApplyingCustLedgEntry() event, Page 232 "Apply Customer Entries"

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#10892]
Hello.
Our customer needs to use variable CalcType in OnBeforeSetApplyingCustLedgEntry event in Page 232 "Apply Customer Entries".
Could you please add this new parameter to this event?

Function:

    procedure SetApplyingCustLedgEntry()
        var
            Customer: Record Customer;
        begin
            OnBeforeSetApplyingCustLedgEntry(AppliedCustLedgEntry, GenJnlLine, SalesHeader,CalcType);
            case CalcType of
                CalcType::SalesHeader:
                    begin
                        ApplyingCustLedgEntry."Entry No." := 1;
                        ApplyingCustLedgEntry."Posting Date" := SalesHeader."Posting Date";
                        if SalesHeader."Document Type" = SalesHeader."Document Type"::"Return Order" then
                            ApplyingCustLedgEntry."Document Type" := ApplyingCustLedgEntry."Document Type"::"Credit Memo"
                        else
                            ApplyingCustLedgEntry."Document Type" := ApplyingCustLedgEntry."Document Type"::Invoice;
            ......................................................................................

Signature:

    [IntegrationEvent(true, false)]
    local procedure OnBeforeSetApplyingCustLedgEntry(var ApplyingCustLedgEntry: Record "Cust. Ledger Entry"; GenJournalLine: Record "Gen. Journal Line"; SalesHeader: Record "Sales Header"; var CalcType: Option)
    begin
    end;

Version of AL Language: 6.1.397164
Business Central Version: 17.3

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by MrPashkovskiy** [comment]
> Please always put the full detailed signature of the requested events.
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

Done.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
