### ISSUE TITLE
[Enum Request] Variable CalcType in Page 232 "Apply Customer Entries" need to become enum

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#10891]
Hello.
Our customer needs to extand variable CalcType in Page 232 "Apply Customer Entries".
But this variable is still Option, could you please make transform variable to Enum?

![image](https://user-images.githubusercontent.com/8793706/106900231-f26eb500-66fe-11eb-905c-460a039c2fb5.png)

Version of AL Language: 6.1.397164
Business Central Version: 17.3

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
