### ISSUE TITLE
[EventRequest] Table 246 "Requisition Line"

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#10894]
Hello MS,
Please help us in migrating our verticalized solution by adding below events to function ValidateLocationChange in "Requisition Line" table.
Version (BC17 Cu03). Requested event OnValidateLocationChange

    local procedure ValidateLocationChange()
    var
        Purchasing: Record Purchasing;
        SalesOrderLine: Record "Sales Line";
    begin
        case true of
            "Location Code" = xRec."Location Code":
                exit;
            "Purchasing Code" = '':
                exit;
            not Purchasing.Get("Purchasing Code"):
                exit;
            not Purchasing."Special Order":
                exit;
            not SalesOrderLine.Get(SalesOrderLine."Document Type"::Order, "Sales Order No.", "Sales Order Line No."):
                exit;
            "Location Code" = SalesOrderLine."Location Code":
                exit;
            OnValidateLocationChange(Rec,IsHandled);
        end;

        Error(Text028, FieldCaption("Location Code"), TableCaption);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnValidateLocationChange(var RequisitionLine: Record "Requisition Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.

**Comment by OSH-ZT** [comment]
> Please always put the full detailed signature of the requested events.
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
> Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot.
> It helps us finding the right place quickly if you put enough code to identify the unique place.

Done.
