### ISSUE TITLE
[EventRequest] Table 5902 "Service Line"

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#10897]
Hello MS,
Please help us in migrating our verticalized solution by adding below events to function ShowNonstock in "Service Line" table.
Version (BC17 Cu03). Requested event OnAfterShowNonstock

    procedure ShowNonstock()
    var
        NonstockItem: Record "Nonstock Item";
        ConfigTemplateHeader: Record "Config. Template Header";
        ItemTemplate: Record "Item Template";
    begin
        TestField(Type, Type::Item);
        TestField("No.", '');
        if PAGE.RunModal(PAGE::"Catalog Item List", NonstockItem) = ACTION::LookupOK then begin
            NonstockItem.TestField("Item Template Code");
            ConfigTemplateHeader.SetRange("Table ID", DATABASE::Item);
            ConfigTemplateHeader.SetRange(Code, NonstockItem."Item Template Code");
            ConfigTemplateHeader.SetRange(Enabled, true);
            ConfigTemplateHeader.FindFirst;

            TestConfigTemplateLineField(NonstockItem."Item Template Code", ItemTemplate.FieldNo("Gen. Prod. Posting Group"));
            TestConfigTemplateLineField(NonstockItem."Item Template Code", ItemTemplate.FieldNo("Inventory Posting Group"));

            "No." := NonstockItem."Entry No.";
            CatalogItemMgt.NonStockFSM(Rec);
            Validate("No.", "No.");
            Validate("Unit Price", NonstockItem."Unit Price");

            OnAfterShowNonstock(Rec);
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterShowNonstock(var ServiceLine: Record "Service Line")
    begin
    end;

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.

**Comment by OSH-ZT** [comment]
> Please always put the full detailed signature of the requested events.
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
> Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot.
> It helps us finding the right place quickly if you put enough code to identify the unique place.

Done.
