### ISSUE TITLE
[Event Request] Report 6653 and Report 295 - Function InsertSalesInvHeader

### ISSUE THREAD

**Issue by bcmako** [Microsoft/ALAppExtensions#1089]
We need an event before inserting the Sales Header in Function InsertSalesInvHeader. The event is required to use separate number series for the document.

![image](https://user-images.githubusercontent.com/47382840/52333620-fecfb280-29fd-11e9-882b-113dd696c3cb.png)

The same event is required in Report 295 Combine Shipments:

![image](https://user-images.githubusercontent.com/47382840/52333766-5c63ff00-29fe-11e9-8479-4b9419f0d6f7.png)

**Comment by AlexanderYakunin** [comment]
Both events already exists

**Comment by bcmako** [comment]
In which version are the events available? I have checked the BC master docker image and can't find the events there:
![image](https://user-images.githubusercontent.com/47382840/52852084-f53dfd00-3117-11e9-9d46-716a7e1c79d9.png)

**Comment by bcmako** [comment]
@AlexanderYakunin Could you please check this?

**Comment by AlexanderYakunin** [comment]
I agree on new event if you want to manage document numbers. I will add it shortly.
