### ISSUE TITLE
[Event Request] OnBeforeCheckRounding(CalcType, IsHandled) in standard function CheckRounding, Page 232 "Apply Customer Entries"

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#10896]
Hello.
Our customer needs to have new event OnBeforeCheckRounding(CalcType, IsHandled) in standard function CheckRounding, Page 232 "Apply Customer Entries".
Could you please add this new event? 

Function:

    procedure CheckRounding()
    var
        IsHandled: Boolean;
    begin
        ApplnRounding := 0;

        IsHandled := false;
        OnBeforeCheckRounding(CalcType, IsHandled);
        if IsHandled then
            exit;

        case CalcType of
            CalcType::SalesHeader, CalcType::ServHeader:
                exit;
            CalcType::GenJnlLine:
                if (GenJnlLine."Document Type" <> GenJnlLine."Document Type"::Payment) and
                   (GenJnlLine."Document Type" <> GenJnlLine."Document Type"::Refund)
                then
                    exit;
        end;

        if ApplnCurrencyCode = '' then
            ApplnRoundingPrecision := GLSetup."Appln. Rounding Precision"
        else begin
            if ApplnCurrencyCode <> "Currency Code" then
                Currency.Get(ApplnCurrencyCode);
            ApplnRoundingPrecision := Currency."Appln. Rounding Precision";
        end;

        if (Abs((AppliedAmount - PmtDiscAmount) + ApplyingAmount) <= ApplnRoundingPrecision) and DifferentCurrenciesInAppln then
            ApplnRounding := -((AppliedAmount - PmtDiscAmount) + ApplyingAmount);
    end;

Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckRounding(var CalcType: Option; var IsHandled: Boolean)
    begin
    end;

Version of AL Language: 6.1.397164
Business Central Version: 17.3

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.

**Comment by MrPashkovskiy** [comment]
> Please always put the full detailed signature of the requested events.
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
> Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot.
> It helps us finding the right place quickly if you put enough code to identify the unique place.

Done.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
