### ISSUE TITLE
[EventRequest] Table 5998 "Standard Service Item Gr. Code"

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#10890]
Hello MS,
Please help us in migrating our verticalized solution by adding below events to function InsertServiceLines in "Standard Service Item Gr. Code" table.
Version (BC17 Cu03). Request event OnAfterCalculateUnitPrice

    procedure InsertServiceLines(ServItemLine: Record "Service Item Line")
    var
        Currency: Record Currency;
        ServHeader: Record "Service Header";
        ServLine: Record "Service Line";
        StdServLine: Record "Standard Service Line";
        StdServItemGrCode: Record "Standard Service Item Gr. Code";
        StdServItemGrCodesForm: Page "Standard Serv. Item Gr. Codes";
        Factor: Integer;
    begin
        ServItemLine.TestField("Line No.");

        Clear(StdServItemGrCodesForm);
        StdServItemGrCode.Reset();
        if ServItemLine."Service Item Group Code" <> '' then
            StdServItemGrCode.SetRange("Service Item Group Code", ServItemLine."Service Item Group Code");
        StdServItemGrCodesForm.SetRecord(StdServItemGrCode);
        StdServItemGrCodesForm.SetTableView(StdServItemGrCode);
        StdServItemGrCodesForm.LookupMode := true;

        if not (StdServItemGrCodesForm.RunModal = ACTION::LookupOK) then
            exit;
        StdServItemGrCodesForm.GetRecord(StdServItemGrCode);
        StdServItemGrCode.TestField(Code);
        StdServCode.Get(StdServItemGrCode.Code);

        StdServCode.TestField(Code);
        ServHeader.Get(ServItemLine."Document Type", ServItemLine."Document No.");
        if StdServCode."Currency Code" <> ServHeader."Currency Code" then
            Error(
              Text001,
              StdServCode.FieldCaption("Currency Code"),
              ServHeader.FieldCaption("Currency Code"), ServHeader.TableCaption);
        StdServLine.SetRange("Standard Service Code", StdServCode.Code);
        Currency.Initialize(StdServCode."Currency Code");
        ServLine."Document Type" := ServItemLine."Document Type";
        ServLine."Document No." := ServItemLine."Document No.";
        ServLine.SetRange("Document Type", ServItemLine."Document Type");
        ServLine.SetRange("Document No.", ServItemLine."Document No.");
        if ServHeader."Prices Including VAT" then
            Factor := 1
        else
            Factor := 0;
        ServLine.LockTable();
        StdServLine.LockTable();
        if StdServLine.Find('-') then
            repeat
                ServLine.Init();
                ServLine."Line No." := 0;
                ServLine.Validate(Type, StdServLine.Type);
                if ServHeader."Link Service to Service Item" then
                    ServLine.Validate("Service Item Line No.", ServItemLine."Line No.");
                if StdServLine.Type = StdServLine.Type::" " then begin
                    ServLine.Validate("No.", StdServLine."No.");
                    ServLine.Description := StdServLine.Description
                end else
                    if not StdServLine.EmptyLine then begin
                        StdServLine.TestField("No.");
                        ServLine.Validate("No.", StdServLine."No.");
                        if StdServLine."Variant Code" <> '' then
                            ServLine.Validate("Variant Code", StdServLine."Variant Code");
                        ServLine.Validate(Quantity, StdServLine.Quantity);
                        if StdServLine."Unit of Measure Code" <> '' then
                            ServLine.Validate("Unit of Measure Code", StdServLine."Unit of Measure Code");
                        ServLine.Description := StdServLine.Description;
                        if StdServLine.Type = StdServLine.Type::"G/L Account" then
                            ServLine.Validate(
                              "Unit Price",
                              Round(StdServLine."Amount Excl. VAT" *
                                (ServLine."VAT %" / 100 * Factor + 1), Currency."Unit-Amount Rounding Precision"));
                        
                        OnAfterCalculateUnitPrice(ServLine,StdServLine)
                    end;

                ServLine."Shortcut Dimension 1 Code" := StdServLine."Shortcut Dimension 1 Code";
                ServLine."Shortcut Dimension 2 Code" := StdServLine."Shortcut Dimension 2 Code";

                CombineDimensions(ServLine, StdServLine);

                if StdServLine.InsertLine then begin
                    ServLine."Line No." := ServLine.GetLineNo();
                    OnBeforeInsertServLine(ServLine);
                    ServLine.Insert(true);
                    InsertExtendedText(ServLine);
                end;
            until StdServLine.Next = 0;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalculateUnitPrice(var ServiceLine: Record "Service Line";var StdServLine: Record "Standard Service Line")
    begin
    end;

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.

**Comment by OSH-ZT** [comment]
> Please always put the full detailed signature of the requested events.
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
> Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot.
> It helps us finding the right place quickly if you put enough code to identify the unique place.

Done.
