### ISSUE TITLE
[Enum Request] In the table "Tax Area" field "Country/Region" should be Enum

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#10908]
Hello,
Our customer needs to extend the field "Country/Region" in "Tax Area", this is critical.
But this field still Option, could you please make transform field to Enum?
![image](https://user-images.githubusercontent.com/66109755/106912662-e3423400-670b-11eb-8f41-f6b94a07012a.png)

Version: BC17Cu03

**Comment by StanPesotskiy** [comment]
Please add [Enum Request] prefix to the title if you requesting for a new enum or a change to the existing enum.

**Comment by AlexanderYakunin** [comment]
We apologize for inconvenience for this customer, but we cannot make this change for you. We have W1 base app with Colombian localization from partner in Colombia and would like to all solutions to be built on top of this. We cannot expose internal elements of US/CA implementation. See more here https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations
