### ISSUE TITLE
[Event Request] New event OnAfterSetParentControl(ParentControl), page 576 "VAT Specification Subform"

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#10903]
Hello.
Need add new event OnAfterSetParentControl(ParentControl) to function SetParentControl, page 576 "VAT Specification Subform"
Version of AL Language: 6.1.397164
Business Central Version: 17.3

Function:

    procedure SetParentControl(ID: Integer)
    begin
        ParentControl := ID;
        OnAfterSetParentControl(ParentControl);
    end;

Signature:

    [IntegrationEvent(false, false)]
    procedure OnAfterSetParentControl(var ParentControl: integer)
    begin
    end;

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.

**Comment by StanPesotskiy** [comment]
Please add [Event Request] prefix to the title if you requesting for a new event or for a modification in the existing event.

**Comment by MrPashkovskiy** [comment]
> Please always put the full detailed signature of the requested events.
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
> Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot.
> It helps us finding the right place quickly if you put enough code to identify the unique place.

Done.

> Please add [Event Request] prefix to the title if you requesting for a new event or for a modification in the existing event.

Done.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
