### ISSUE TITLE
[Protection Level] Codeunit "Sales-Post" Function "PostDistributeItemCharge" and "PostItemCharge" remove local

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#10905]
We need to access the functions from an event (for further description of why it is needed and what event it is, please have a look on issue  #10169 ) - to not have duplicates of this functions, we need them to be global.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
