### ISSUE TITLE
In table "Requisition Line" field "Type" should be Enum

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#10907]
Hello,
Our customer needs to extend the field "Type" in "Requisition Line", this is critical.
But this field still Option, could you please make transform field to Enum?
![image](https://user-images.githubusercontent.com/66109755/106912337-98282100-670b-11eb-9c4c-ff967664d1f2.png)

Version: BC17 Cu03

**Comment by StanPesotskiy** [comment]
Please add [Enum Request] prefix to the title if you requesting for a new enum or a change to the existing enum.

**Comment by AlexanderYakunin** [comment]
This is already implemented in 18.x

        field(4; Type; Enum "Requisition Line Type")
        {
            Caption = 'Type';
