### ISSUE TITLE
Variable ReportUsage2 in Page 306 "Report Selection - Sales" needs to become enum

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#10904]
Hello.
Our customer needs to extand variable ReportUsage2 in Page 306 "Report Selection - Sales"
But this variable is still Option, could you please make transform variable to Enum?
Version of AL Language: 6.1.397164
Business Central Version: 17.3
![image](https://user-images.githubusercontent.com/8793706/106909245-c35d4100-6708-11eb-927e-79bae15dca2e.png)

**Comment by StanPesotskiy** [comment]
Please add [Enum Request] prefix to the title if you requesting for a new enum or a change to the existinng enum.

**Comment by AlexanderYakunin** [comment]
Please be aware what we do not provide new enum implementation to production versions, we can do it for 18.x only. This enum is already implemented in 18.x.
