### ISSUE TITLE
New function GetApplnType(), Page 232 "Apply Customer Entries

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#10901]
Hello.
Need add function GetApplnType() that will return ApplnType value, Page 232 "Apply Customer Entries"
Version of AL Language: 6.1.397164
Business Central Version: 17.3

Function:

    procedure GetApplnType(): Integer
    begin
        exit(ApplnType);
    end;

**Comment by StanPesotskiy** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by MrPashkovskiy** [comment]
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

Done.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
