### ISSUE TITLE
[Event Request] T37/39 OnInitQtyToInvoiceBeforeCalcInvDisc

### ISSUE THREAD

**Issue by GuntherGebauer** [Microsoft/ALAppExtensions#1090]
we Need an additional Event in InitQtyToInvoice before the invoice Discounts will be calculated. The existing one OnAfterInitQtyToInvoice cannot be used because we Need to set field values which affects the invoice Discount calculation and value for this salesline/purchaseline

[External] InitQtyToInvoice()
"Qty. to Invoice" := MaxQtyToInvoice;
"Qty. to Invoice (Base)" := MaxQtyToInvoiceBase;

//FVA +++++++++++++++++++++++++++++++++++++++++++++++++++
OnInitQtyToInvoiceBeforeCalcInvDisc(VAR rec:SalesLine2,CurrFieldNo);  <-- NewEvent
//FVA ---------------------------------------------------

"VAT Difference" := 0;
CalcInvDiscToInvoice;
IF SalesHeader."Document Type" <> SalesHeader."Document Type"::Invoice THEN
  CalcPrepaymentToDeduct;

OnAfterInitQtyToInvoice(Rec,CurrFieldNo);

**Comment by NKarolak** [comment]
According to the BC Insider, we shall use publisher OnBeforeCalcInvDiscToInvoice instead - is that correct, @JesperSchulz?
