### ISSUE TITLE
EventSubscriber to 'OnAfterSubstituteReport' event for a report with custom layout

### ISSUE THREAD

**Issue by clasalal** [microsoft/ALAppExtensions#10916]
Hello,

I have a problem with automatic reports substitution.
In the report selection for sales, report 1306 is selected for invoices:
![image](https://user-images.githubusercontent.com/64960257/106914070-f1d91d00-6704-11eb-94a9-c92a4c7f7ca6.png)

The customer 30000 has an standard Word document layout selected for the 1306 report:
![image](https://user-images.githubusercontent.com/64960257/106914730-96f3f580-6705-11eb-9cb2-54691e2fa4cc.png)

In my application we subscribe to event 'OnAfterSubstituteReport' to replace report 1306 with one of ours (with rdlc layout) and the problem is that report 1306 is replaced by ours but applies the selected word layout for report 1306, causing an error:
![image](https://user-images.githubusercontent.com/64960257/106915452-4e890780-6706-11eb-9d82-c6be23d784a7.png)

The word layout from the replaced report shouldn't be applied, right?

I hope you can tell me something as soon as possible. Thanks in advance.

Best regards
Clara

**Comment by clasalal** [comment]
By the way, related to the above, is there any way to Know if a custom layout is being applied for a report in the 'OnAfterSubstituteReport' event? For example, to not replace a report to which a custom layout is being applied.

Thanks

**Comment by AlexanderYakunin** [comment]
Maybe you need update Custom Report Selection setup to use your report? You don't need  OnAfterSubstitureReport for this purpose.

**Comment by clasalal** [comment]
My purpose is to replace the standard bc 1306 sales invoice report with one of my extension with rdlc layout and the problem is that, when replacing it, it tries to apply the custom word layout of the replaced report (1306 in this case) and we do not want the user to have to indicate the number of our report in the report selection, so, without doing anything, when installing our extension, as long as the standard report is selected, it will be replaced by ours, and it will not be done if a non-standard report has been selected.

I understand that the 'OnAfterSubstitureReport' event does not work properly because it does replace the report but tries to apply the custom layout of the replaced report.

**Comment by mazhelez** [comment]
Hi @clasalal 

Sorry for paying attention to this issue so late.

However, I got curious about the following

> we do not want the user to have to indicate the number of our report in the report selection, so, without doing anything, when installing our extension, as long as the standard report is selected, it will be replaced by ours

What is the reason to want such behavior? While it might be convenient in some cases, in others it might be quite baffling - the users sees one report in the setup but another is being used underneath. A lot of the users can't actually see the installed extensions.

**Comment by clasalal** [comment]
Hello,

Over all we do it so that, if the extension is uninstalled, without having to modify the reports selection, everything works without errors ... Specially, for example, when someone installs the extension to test it and, after testing it, teh extension is uninstalled.

**Comment by mazhelez** [comment]
Hey @clasalal 

Just got feedback from a colleague of mine that what you are trying to do isn't possible.
Substitution is only valid if layouts are compatible or you only use built-in layouts.

A team will be working on the root cause of this issue but for now the only way to go is to use Custom Report Selection.
