### ISSUE TITLE
[Event Request] New event OnBeforeServiceLineShowWarning in function ServiceLineShowWarning, page 343 "Check Credit Limit"

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#10915]
Hello
Need event OnBeforeServiceLineShowWarning(ServLine, Result, IsHandled) in standard functions ServiceLineShowWarning like in same function for sales documents SalesLineShowWarning(event - OnBeforeSalesLineShowWarning), page 343 "Check Credit Limit".
Need to add Result as return variable in same way.
Version of AL Language: 6.1.397164
Business Central Version: 17.3

Function:

    procedure ServiceLineShowWarning(ServLine: Record "Service Line") Result: Boolean
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeServiceLineShowWarning(ServLine, Result, IsHandled);
        if IsHandled then
            exit(Result);

        SalesSetup.Get();
        if SalesSetup."Credit Warnings" =
           SalesSetup."Credit Warnings"::"No Warning"
        then
            exit(false);
    ..........................................................................................
    end;

Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeServiceLineShowWarning(var ServLine: Record "Service Line"; var Result: Boolean; var IsHandled: Boolean);
    begin
    end;

**Comment by MrPashkovskiy** [comment]
@StanPesotskiy Done.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
