### ISSUE TITLE
[Function Exposure] COD12 InitLastDocDate

### ISSUE THREAD

**Issue by martinhocosta88** [microsoft/ALAppExtensions#1091]
Would Like to request to expose the InitLastDocDate including an event call. It's purpose is to init a specific field.

**Comment by AlexanderYakunin** [comment]
This information is not sufifcient. Please provide description of requested event.

**Comment by martinhocosta88** [comment]
Sorry, here you go. No var needed in the argument 
![image](https://user-images.githubusercontent.com/13696679/56054027-98dd0f80-5d4d-11e9-96b5-e372d101aa79.png)
