### ISSUE TITLE
[Enum Request] In table "Service Cr.Memo Header" field "Document Exchange Status" should be Enum

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#10911]
Hello,
Our customer needs to extend the field "Document Exchange Status" in "Service Cr.Memo Header", this is critical.
But this field still Option, could you please make transform field to Enum?
![image](https://user-images.githubusercontent.com/66109755/106913326-8c892a00-670c-11eb-8991-36b3df85bf2c.png)

Version: BC17 Cu03

**Comment by StanPesotskiy** [comment]
Please add [Enum Request] prefix to the title if you requesting for a new enum or a change to the existing enum.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
