### ISSUE TITLE
[Enum Request] In table "Sales Tax Amount Difference" field "Document Product Area" should be Enum

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#10912]
Hello,
Our customer needs to extend the field "Document Product Area" in "Sales Tax Amount Difference", this is critical.
But this field still Option, could you please make transform field to Enum?
![image](https://user-images.githubusercontent.com/66109755/106913531-c22e1300-670c-11eb-8b3f-b9be3473245c.png)

Version: BC17 cu03 NA localization.

**Comment by StanPesotskiy** [comment]
Please add [Enum Request] prefix to the title if you requesting for a new enum or a change to the existing enum.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
