### ISSUE TITLE
[Event Request] New event OnAfterCalcExitValueOverdueBalanceLCY in function ShowWarning(), page 343 "Check Credit Limit

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#10919]
Hello
Need event OnAfterCalcExitValueOverdueBalanceLCY(Rec, var ExitValue) in standard function ShowWarning(), page 343 "Check Credit Limit". ExitValue parameter should be used with var.

Function:

    procedure ShowWarning(NewCustNo: Code[20]; NewOrderAmountLCY2: Decimal; OldOrderAmountLCY2: Decimal; CheckOverDueBalance: Boolean) Result: Boolean
    var
        CustCheckCrLimit: Codeunit "Cust-Check Cr. Limit";
        ExitValue: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeShowWarning(Rec, NewOrderAmountLCY, OldOrderAmountLCY, OrderAmountTotalLCY, ShippedRetRcdNotIndLCY, CustCreditAmountLCY, DeltaAmount, CheckOverDueBalance, Heading, Result, IsHandled);
        if IsHandled then
            exit(Result);

        if NewCustNo = '' then
            exit;
        CustNo := NewCustNo;
        NewOrderAmountLCY := NewOrderAmountLCY2;
        OldOrderAmountLCY := OldOrderAmountLCY2;
        Get(CustNo);
        SetRange("No.", "No.");
        Cust2.Copy(Rec);

        if (SalesSetup."Credit Warnings" in
            [SalesSetup."Credit Warnings"::"Both Warnings",
             SalesSetup."Credit Warnings"::"Credit Limit"]) and
           CustCheckCrLimit.IsCreditLimitNotificationEnabled(Rec)
        then begin
            CalcCreditLimitLCY;
            if (CustCreditAmountLCY > "Credit Limit (LCY)") and ("Credit Limit (LCY)" <> 0) then
                ExitValue := 1;
        end;
        if CheckOverDueBalance and
           (SalesSetup."Credit Warnings" in
            [SalesSetup."Credit Warnings"::"Both Warnings",
             SalesSetup."Credit Warnings"::"Overdue Balance"]) and
           CustCheckCrLimit.IsOverdueBalanceNotificationEnabled(Rec)
        then begin
            CalcOverdueBalanceLCY;
            if "Balance Due (LCY)" > 0 then
                ExitValue := ExitValue + 2;
            OnAfterCalcExitValueOverdueBalanceLCY(Rec, ExitValue);
        end;
    ............................................................................................
    end;

Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcExitValueOverdueBalanceLCY(var Customer: Record Customer; var ExitValue: Integer);
    begin
    end;

Version of AL Language: 6.1.397164
Business Central Version: 17 cu3

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place. 

Please add [Event Request] prefix to the title if you requesting for a new event or for a modification in the existing event.

**Comment by MrPashkovskiy** [comment]
> Please always put the full detailed signature of the requested events.
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
> Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot.
> It helps us finding the right place quickly if you put enough code to identify the unique place.
> 
> Please add [Event Request] prefix to the title if you requesting for a new event or for a modification in the existing event.

Done.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
