### ISSUE TITLE
[Event Request] New event OnBeforeServiceHeaderShowWarning in function ServiceHeaderShowWarning, page 343 "Check Credit Limit"

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#10914]
Hello
Need event OnBeforeServiceHeaderShowWarning(ServHeader, Result, IsHandled) in standard functions ServiceHeaderShowWarning like in same function for sales documents SalesHeaderShowWarning(event - OnBeforeSalesHeaderShowWarning), page 343 "Check Credit Limit"
Need to add Result as return variable in same way.

Function:

    procedure ServiceHeaderShowWarning(ServHeader: Record "Service Header")Result: Boolean
    var
        ServSetup: Record "Service Mgt. Setup";
        OldServHeader: Record "Service Header";
        AssignDeltaAmount: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeServiceHeaderShowWarning(ServHeader, Result, IsHandled);
        if IsHandled then
            exit(Result);
        ServSetup.Get();
        SalesSetup.Get();
        if SalesSetup."Credit Warnings" =
           SalesSetup."Credit Warnings"::"No Warning"
        then
            exit(false);
    .......................................................................
    end;

Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeServiceHeaderShowWarning(var ServiceHeader: Record "Service Header"; var Result: Boolean; var IsHandled: Boolean);
    begin
    end;

Version of AL Language: 6.1.397164
Business Central Version: 17.3

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place. 

Please add [Event Request] prefix to the title if you requesting for a new event or for a modification in the existing event.

**Comment by MrPashkovskiy** [comment]
> Please always put the full detailed signature of the requested events.
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
> Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot.
> It helps us finding the right place quickly if you put enough code to identify the unique place.
> 
> Please add [Event Request] prefix to the title if you requesting for a new event or for a modification in the existing event.

Done.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
