### ISSUE TITLE
 [Enum Request] In the table "Tax Jurisdiction" field "Country/Region" should be Enum

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#10910]
Hello,
Our customer needs to extend the field "Country/Region" in "Tax Jurisdiction", this is critical.
But this field still Option, could you please make transform field to Enum?
![image](https://user-images.githubusercontent.com/66109755/106913002-3ddb9000-670c-11eb-9ab9-6d78fd7acf12.png)

Version: BC17 Cu03 NA localization.

**Comment by StanPesotskiy** [comment]
Please add [Enum Request] prefix to the title if you requesting for a new enum or a change to the existing enum.

**Comment by AlexanderYakunin** [comment]
What country you are talinig about?

**Comment by OSH-ZT** [comment]
> What country you are talking about?

North America

**Comment by AlexanderYakunin** [comment]
We only have 2 countries with Sales Tax support, US and CA. Which option is missing in this field? Do you need another country?

**Comment by OSH-ZT** [comment]
> We only have 2 countries with Sales Tax support, US and CA. Which option is missing in this field? Do you need another country?

Yes, I need another country. Colombia (CO).
Customer change option string from "US,CA" to "US,CA,CO".

**Comment by sorenfriisalexandersen** [comment]
@OSH-ZT Can you elaborate more on what it is you are trying to achieve?

**Comment by OSH-ZT** [comment]
@sorenfriisalexandersen Customer changed this option and want to use this customization in BC Cloud. Customer use this field in different places, so I can not skip this moment. 
Thanks

![image](https://user-images.githubusercontent.com/66109755/107340507-87d6c400-6ac6-11eb-87c5-5bae8e9631eb.png)

**Comment by sorenfriisalexandersen** [comment]
@OSH-ZT Please elaborate some more.

1. Where is the customer located?
2. Why do they want to use/change this code?

**Comment by OSH-ZT** [comment]
@sorenfriisalexandersen 
These changes created by some company that created an addon for standard NAV.
It is the addon that uses many customers. I assume they did it because there was a request from customers.
I didn`t find any places in objects where "Colombia" value can be filled by code. It can be manual.

**Comment by AlexanderYakunin** [comment]
We cannot go forward with your requests about CO until we understand how you are going to use BC in CO. I can see that you are converting 14.x solution to BC, and probably add-in have been created on top of NA code base for Columbia. 

We have different architecture in BC, there ALL country localizations created on top of W1, not NA. Currently we support US, CA and MX based on NA codebase, and there is local extension for Columbia. 

The field you are asking to convert to enum is US/CA specific and this is legacy design. We may ned toc change it to another solution going forward.

Please provide more information about how you need to deploy your project, is this multi-country or single tenant? If you can provide your partner name and name of this add-on, it will simplify our discussion.

**Comment by OSH-ZT** [comment]
@AlexanderYakunin thanks for the information. I will clarify some details with my partner and go back.
Thank you very much, I appreciate your time.

**Comment by AlexanderYakunin** [comment]
Any update? Or should we close this request?

**Comment by OSH-ZT** [comment]
> Any update? Or should we close this request?

It is an RMI addon. They have one customer in Colombia. They modified the standard and use the same functionality with taxes for Colombia too, as I understand.

**Comment by OSH-ZT** [comment]
We investigate how we can implement this customization. But most likely we cannot do without Enum here.

**Comment by AlexanderYakunin** [comment]
We apologize for inconvenience for this customer, but we cannot make this change for you. We have W1 base app with Colombian localization from partner in Colombia and would like to all solutions to be built on top of this. We cannot expose internal elements of US/CA implementation. See more here https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations
