### ISSUE TITLE
Need to have access to standard variables CL, PL, P, C from page 1025 "Job Statistics"

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#10923]
Hello
Need to have access(need become protected var or add Get functions) to standard variables CL, PL, P, C from page 1025 "Job Statistics"

    var
        JobCalcStatistics: Codeunit "Job Calculate Statistics";
        Text000: Label 'Placeholder';
    protected var
        CL: array[16] of Decimal;
        PL: array[16] of Decimal;
        P: array[16] of Decimal;
        C: array[16] of Decimal;

Version of AL Language: 6.1.397164
Business Central Version: 17 cu3

**Comment by StanPesotskiy** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by MrPashkovskiy** [comment]
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

Done.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
