### ISSUE TITLE
[Event Request] New parameters in event OnBeforeNavigateShowRecords in function ShowRecords, page 344 Navigate

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#10920]
Hello.
Need new parameters var GLEntry, var VATEntry,var VendLedgEntry, var WarrantyLedgerEntry in event OnBeforeNavigateShowRecords, in function ShowRecords page 344 Navigate

Function:

    local procedure ShowRecords()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeNavigateShowRecords(
          "Table ID", DocNoFilter, PostingDateFilter, ItemTrackingSearch, Rec, IsHandled,
          SalesInvHeader, SalesCrMemoHeader, PurchInvHeader, PurchCrMemoHeader, ServInvHeader, ServCrMemoHeader,
          SOSalesHeader, SISalesHeader, SCMSalesHeader, SROSalesHeader, GLEntry, VATEntry, VendLedgEntry, WarrantyLedgerEntry);
        if IsHandled then
            exit;

        if ItemTrackingSearch then
            ItemTrackingNavigateMgt.Show("Table ID")
        else
            case "Table ID" of
                DATABASE::"Incoming Document":
                    PAGE.Run(PAGE::"Incoming Document", IncomingDocument);
                DATABASE::"Sales Header":
        ......................................................................
    end;

Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeNavigateShowRecords(TableID: Integer; DocNoFilter: Text; PostingDateFilter: Text; ItemTrackingSearch: Boolean; var TempDocumentEntry: Record "Document Entry" temporary; var IsHandled: Boolean; var SalesInvoiceHeader: Record "Sales Invoice Header"; var SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var PurchInvHeader: Record "Purch. Inv. Header"; var PurchCrMemoHdr: Record "Purch. Cr. Memo Hdr."; var ServiceInvoiceHeader: Record "Service Invoice Header"; var ServiceCrMemoHeader: Record "Service Cr.Memo Header"; var SOSalesHeader: Record "Sales Header"; var SISalesHeader: Record "Sales Header"; var SCMSalesHeader: Record "Sales Header"; var SROSalesHeader: Record "Sales Header"; var GLEntry: Record "G/L Entry"; var VATEntry: Record "VAT Entry"; var VendLedgEntry: Record "Vendor Ledger Entry"; var WarrantyLedgerEntry: Record "Warranty Ledger Entry")
    begin
    end;
Version of AL Language: 6.1.397164
Business Central Version: 17 cu3

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place. 

Please add [Event Request] prefix to the title if you requesting for a new event or for a modification in the existing event.

**Comment by MrPashkovskiy** [comment]
> Please always put the full detailed signature of the requested events.
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
> Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot.
> It helps us finding the right place quickly if you put enough code to identify the unique place.
> 
> Please add [Event Request] prefix to the title if you requesting for a new event or for a modification in the existing event.

Done.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
