### ISSUE TITLE
[Event Request] New parameter sender: Page Navigate in event OnFindRecordsOnAfterSetSource, in function FindRecords page 344 Navigate

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#10921]
Hello.
Need add new parameter sender: Page Navigate in event OnFindRecordsOnAfterSetSource, in function FindRecords page 344 Navigate

Function:

      local procedure FindRecords()
      var
          DocType2: Text[100];
          DocNo2: Code[20];
          SourceType2: Integer;
          SourceNo2: Code[20];
          PostingDate: Date;
          IsSourceUpdated: Boolean;
          HideDialog: Boolean;
      begin
          OnBeforeFindRecords(HideDialog);
          if not HideDialog then
              Window.Open(Text002);
          Reset;
          DeleteAll();
          "Entry No." := 0;
  
          FindPostedDocuments;
          FindLedgerEntries;
  
          OnAfterNavigateFindRecords(Rec, DocNoFilter, PostingDateFilter);
          DocExists := FindFirst;
  
          SetSource(0D, '', '', 0, '');
          if DocExists then begin
              if (NoOfRecords(DATABASE::"Cust. Ledger Entry") + NoOfRecords(DATABASE::"Vendor Ledger Entry") <= 1) and
                 (GetDocumentCount <= 1)
              then begin
                  SetSourceForService;
                  SetSourceForSales;
                  SetSourceForPurchase;
                  SetSourceForServiceDoc;
  
                  IsSourceUpdated := false;
                  OnFindRecordsOnAfterSetSource(
                    Rec, PostingDate, DocType2, DocNo2, SourceType2, SourceNo2, DocNoFilter, PostingDateFilter, IsSourceUpdated);
      ..................................................................................................
      end;

Signature:

    [IntegrationEvent(true, false)]
    local procedure OnFindRecordsOnAfterSetSource(var DocumentEntry: Record "Document Entry"; var PostingDate: Date; var DocType2: Text[100]; var DocNo: Code[20]; var SourceType2: Integer; var SourceNo: Code[20]; var DocNoFilter: Text; var PostingDateFilter: Text; var IsHandled: Boolean)
    begin
    end;

Version of AL Language: 6.1.397164
Business Central Version: 17 cu3

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place. 

Please add [Event Request] prefix to the title if you requesting for a new event or for a modification in the existing event.

**Comment by MrPashkovskiy** [comment]
> Please always put the full detailed signature of the requested events.
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
> Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot.
> It helps us finding the right place quickly if you put enough code to identify the unique place.
> 
> Please add [Event Request] prefix to the title if you requesting for a new event or for a modification in the existing event.

Done.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
