### ISSUE TITLE
[Event Request] Need add event to Codeunit 5988 function PostServiceResourceLine

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10928]
Hi

Please add an event OnBeforePostServiceResourceLine to function PostServiceResourceLine

    local procedure PostServiceResourceLine(var ServLine: Record "Service Line"; var WarrantyNo: Integer)
    var
        TempServLine: Record "Service Line" temporary;
        TempVATAmountLineForSLE: Record "VAT Amount Line" temporary;
    begin
        with ServLine do begin
            TempServLine := ServLine;

            OnBeforePostServiceResourceLine(ServLine);

            ServPostingJnlsMgt.CalcSLEDivideAmount("Qty. to Ship", ServHeader, TempServLine, TempVATAmountLineForSLE);

            if Ship and ("Document Type" = "Document Type"::Order) then
                WarrantyNo :=
                  ServPostingJnlsMgt.InsertWarrantyLedgerEntry(
                    NextWarrantyLedgerEntryNo, ServHeader, TempServLine, ServItemLine, "Qty. to Ship", ServHeader."Shipping No.");

            if "Document Type" = "Document Type"::"Credit Memo" then
                ServPostingJnlsMgt.PostResJnlLineUndoUsage(ServLine, GenJnlLineDocNo, GenJnlLineExtDocNo)
            else
                PostResourceUsage(TempServLine);

            if "Qty. to Invoice" <> 0 then
                ServPostingJnlsMgt.PostResJnlLineSale(ServLine, GenJnlLineDocNo, GenJnlLineExtDocNo);
        end;
    end;

Event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostServiceResourceLine(var ServLine: Record "Service Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
