### ISSUE TITLE
[Event Request] Request for new event publisher OnAfterCreateCustomerLink in Table5050

### ISSUE THREAD

**Issue by SerhiiKurinnyi** [microsoft/ALAppExtensions#10925]
After Customer Link has been created in the function **CreateCustomerLink** in Table 5050. i would like to be able to intervene with code, so please add new integration event called OnAfterCreateCustomerLink at the end of the function CreateCustomerLink

	procedure CreateCustomerLink()
	var
			Cust: Record Customer;
			ContBusRel: Record "Contact Business Relation";
	begin
			CheckForExistingRelationships(ContBusRel."Link to Table"::Customer);
			CheckIfPrivacyBlockedGeneric;
			RMSetup.Get();
			RMSetup.TestField("Bus. Rel. Code for Customers");
			CreateLink(
				PAGE::"Customer Link",
				RMSetup."Bus. Rel. Code for Customers",
				ContBusRel."Link to Table"::Customer);

			ContBusRel.SetCurrentKey("Link to Table", "Contact No.");
			ContBusRel.SetRange("Link to Table", ContBusRel."Link to Table"::Customer);
			ContBusRel.SetRange("Contact No.", "Company No.");
			if ContBusRel.FindFirst then
					if Cust.Get(ContBusRel."No.") then
							UpdateQuotes(Cust, '');
							
			OnAfterCreateCustomerLink(Rec); //New event request
	end;

	[IntegrationEvent(false, false)]
	local procedure OnAfterCreateCustomerLink (var Contact: Record Contact)
	begin
	end;

**Comment by StanPesotskiy** [comment]
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.

**Comment by StanPesotskiy** [comment]
Please add [Event Request] prefix to the title if you requesting for a new event or for a modification in the existing event.

**Comment by SerhiiKurinnyi** [comment]
> Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot.
> It helps us finding the right place quickly if you put enough code to identify the unique place.

done

**Comment by SerhiiKurinnyi** [comment]
> Please add [Event Request] prefix to the title if you requesting for a new event or for a modification in the existing event.

done
