### ISSUE TITLE
Type of standard function SetSource should be changed from protected to global, page 344 Navigate

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#10922]
Hello.
Type of standard function SetSource, page 344 Navigate, should be changed from protected to global, to have posibility to call it in event subscriber from here https://github.com/microsoft/ALAppExtensions/issues/10921

Function:

     procedure SetSource(PostingDate: Date; DocType2: Text[100]; DocNo: Text[50]; SourceType2: Integer; SourceNo2: Code[20])
        begin
            if SourceType2 = 0 then begin
                DocType := '';
                SourceType := '';
                SourceNo := '';
                SourceName := '';
            end else begin
                DocType := DocType2;
                SourceNo := SourceNo2;
                SetRange("Document No.", DocNo);
                SetRange("Posting Date", PostingDate);
                DocNoFilter := GetFilter("Document No.");
                PostingDateFilter := GetFilter("Posting Date");
                case SourceType2 of
                    1:
                        begin
                            SourceType := Cust.TableCaption;
                            if not Cust.Get(SourceNo) then
                                Cust.Init();
                            SourceName := Cust.Name;
                        end;
                    2:
                        begin
                            SourceType := Vend.TableCaption;
                            if not Vend.Get(SourceNo) then
                                Vend.Init();
                            SourceName := Vend.Name;
                        end;
                    4:
                        begin
                            SourceType := Bank.TableCaption;
                            if not Bank.Get(SourceNo) then
                                Bank.Init();
                            SourceName := Bank.Name;
                        end;
                end;
            end;
            DocTypeEnable := SourceType2 <> 0;
            SourceTypeEnable := SourceType2 <> 0;
            SourceNoEnable := SourceType2 <> 0;
            SourceNameEnable := SourceType2 <> 0;
    
            OnAfterSetSource(SourceType2, SourceType, SourceNo, SourceName);
        end;

Version of AL Language: 6.1.397164
Business Central Version: 17 cu3

**Comment by StanPesotskiy** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by MrPashkovskiy** [comment]
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

Done.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
