### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnValidateLocationCodeOnBeforeTestField

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10924]
Hello. In table 39 Purchase Line, in field 7 "Location Code", in trigger OnValidate, we would like to add a condition at a specific moment. To do so, we would need a IsHandled flag and an event publisher here : 

                if xRec."Location Code" <> "Location Code" then begin
                    if "Prepmt. Amt. Inv." <> 0 then
                        if not ConfirmManagement.GetResponseOrDefault(
                             StrSubstNo(
                               Text046, FieldCaption("Direct Unit Cost"), FieldCaption("Location Code"), PRODUCTNAME.Full), true)
                        then begin
                            "Location Code" := xRec."Location Code";
                            exit;
                        end;

                    IsHandled := false;
                    OnValidateLocationCodeOnBeforeTestField(Rec, IsHandled);
                    if not IsHandled then begin
                        TestField("Qty. Rcd. Not Invoiced", 0);
                        TestField("Receipt No.", '');

                        TestField("Return Qty. Shipped Not Invd.", 0);
                        TestField("Return Shipment No.", '');
                    end;
                end;

With the event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnValidateLocationCodeOnBeforeTestField(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

Thank you for your work.

**Comment by StanPesotskiy** [comment]
You asked for IsHandled parameter that is not used after it is passed to the event call? Don't you miss 'if IsHanded then exit'?

**Comment by Magicrevette** [comment]
You're right, sorry for that. I edited my post.
