### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnValidateQuantityOnBeforeTypeItem

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10929]
Hello. In table 39 Purchase Line, in field 15 Quantity, in trigger OnValidate, we would like to add a condition to the a if statement. To do so, we would need a IsHandled flag and an event publisher before this if statement : 

                IsHandled := false;
                OnValidateQuantityOnBeforeTypeItem(Rec, IsHandled);
                if not IsHandled then
                    if Type <> Type::Item then
                        Validate("Line Discount %");

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnValidateQuantityOnBeforeTypeItem(var PurchaseLine: Record "Purchase Line"; var IsHandled : boolean)
    begin
    end;

Do you think it is possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
