### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - field Quantity - OnValidate, if CurrFieldNo <> 0

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10927]
Hello. In table 39 Purchase Line, in field 15 Quantity, in trigger OnValidate, I would like to add some code of mine after the if statement testing if CurrField <> 0. To do so, I see two ways : 
1) Adding an event publisher inside this if statement, or...
2) Adding the parameter CurrFieldNo in the event publisher after this if statement (OnValidateQuantityOnBeforeCheckRcptRetShptRelation) in order to reproduce this test.

Whatever solution is ok for me. Wich one is the best for you ?

                if (Type = Type::"Charge (Item)") and (CurrFieldNo <> 0) then begin
                    if (Quantity = 0) and ("Qty. to Assign" <> 0) then
                        FieldError("Qty. to Assign", StrSubstNo(Text011, FieldCaption(Quantity), Quantity));
                    if (Quantity * "Qty. Assigned" < 0) or (Abs(Quantity) < Abs("Qty. Assigned")) then
                        FieldError(Quantity, StrSubstNo(Text004, FieldCaption("Qty. Assigned")));
    -> An event publisher here, or...
                end;

                OnValidateQuantityOnBeforeCheckRcptRetShptRelation(Rec, -> CurrFieldNo here);
                if "Receipt No." <> '' then
                    CheckReceiptRelation
                else
                    if "Return Shipment No." <> '' then
                        CheckRetShptRelation;

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
