### ISSUE TITLE
[Event Request] Add please event to Codeunit 5988 function UpdateServLinesOnPostOrder

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10931]
Please add  event OnBeforeUpdateServLinesOnPostOrder to function UpdateServLinesOnPostOrder

    local procedure UpdateServLinesOnPostOrder()
    var
        CalcInvDiscAmt: Boolean;
        OldInvDiscountAmount: Decimal;
    begin
        CalcInvDiscAmt := false;
        with ServLine do begin
            if Find('-') then
                repeat
                    if Quantity <> 0 then begin
                        OldInvDiscountAmount := "Inv. Discount Amount";

                        OnBeforeUpdateServLinesOnPostOrder(ServLine)

                        if Ship then begin
                            "Quantity Shipped" := "Quantity Shipped" + "Qty. to Ship";
                            "Qty. Shipped (Base)" := "Qty. Shipped (Base)" + "Qty. to Ship (Base)";
                        end;

                        if Consume then begin
                            if Abs("Quantity Consumed" + "Qty. to Consume") >
                               Abs("Quantity Shipped" - "Quantity Invoiced")
                            then begin
                                Validate("Qty. to Consume", "Quantity Shipped" - "Quantity Invoiced" - "Quantity Consumed");
                                "Qty. to Consume (Base)" := "Qty. Shipped (Base)" - "Qty. Invoiced (Base)" - "Qty. Consumed (Base)";
                            end;
                            "Quantity Consumed" := "Quantity Consumed" + "Qty. to Consume";
                            "Qty. Consumed (Base)" := "Qty. Consumed (Base)" + "Qty. to Consume (Base)";
                            Validate("Qty. to Consume", 0);
                            "Qty. to Consume (Base)" := 0;
                        end;

                        if Invoice then begin
                            if Abs("Quantity Invoiced" + "Qty. to Invoice") >
                               Abs("Quantity Shipped" - "Quantity Consumed")
                            then begin
                                Validate("Qty. to Invoice", "Quantity Shipped" - "Quantity Invoiced" - "Quantity Consumed");
                                "Qty. to Invoice (Base)" := "Qty. Shipped (Base)" - "Qty. Invoiced (Base)" - "Qty. Consumed (Base)";
                            end;
                            "Quantity Invoiced" := "Quantity Invoiced" + "Qty. to Invoice";
                            "Qty. Invoiced (Base)" := "Qty. Invoiced (Base)" + "Qty. to Invoice (Base)";
                        end;

                        InitOutstanding;
                        InitQtyToShip;

                        if "Inv. Discount Amount" <> OldInvDiscountAmount then
                            CalcInvDiscAmt := true;

                        Modify;
                    end;
                until Next = 0;

            if Find('-') then
                if SalesSetup."Calc. Inv. Discount" or CalcInvDiscAmt then begin
                    ServHeader.Get("Document Type", "Document No.");
                    Clear(ServCalcDisc);
                    ServCalcDisc.CalculateWithServHeader(ServHeader, PServLine, ServLine);
                end;
        end;
    end;
    
    
Event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateServLinesOnPostOrder(ServLine: Record "Service Line";)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
