### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" OnAfterApplyVendLedgEntry

### ISSUE THREAD

**Issue by jaromirchaloupka** [microsoft/ALAppExtensions#10932]
Hello, please add new event called **OnAfterApplyVendLedgEntry** into Codeunit 12 "Gen. Jnl.-Post Line" at the end of **ApplyVendLedgEntry** procedure. If possible, could it be done similar way as OnAfterApplyCustLedgEntry event in ApplyCustLedgEntry procedure? In that case it will help us to hook our custom logic for Vendor Ledger Entries as well. Thanks in advance.

`OnAfterApplyVendLedgEntry(GenJnlLine, NewCVLedgEntryBuf, OldVendLedgEntry);`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
