### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnValidateLineDiscountAmountOnBeforeUpdateLineDiscPct

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10937]
Hello. In Table 39 "Purchase Line", in field 28 Line Discount Amount, in trigger OnValidate, we would like to add a condition to the if statement. To do so, we would need a IsHandled flag and an event publisher, like this :

                GetPurchHeader;
                "Line Discount Amount" := Round("Line Discount Amount", Currency."Amount Rounding Precision");
                TestStatusOpen;
                TestField(Quantity);

                IsHandled := false;
                OnValidateLineDiscountAmountOnBeforeUpdateLineDiscPct(Rec, xRec, IsHandled);
                if not IsHandled then

                if xRec."Line Discount Amount" <> "Line Discount Amount" then
                    UpdateLineDiscPct;
                "Inv. Discount Amount" := 0;
                "Inv. Disc. Amount to Invoice" := 0;
                UpdateAmounts;
                UpdateUnitCost;
                NotifyOnMissingSetup(FieldNo("Line Discount Amount"));

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnValidateLineDiscountAmountOnBeforeUpdateLineDiscPct(var PurchaseLine: Record "Purchase Line"; var xPurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)  
    begin
    end;

Do you think it could be possible ?

I tried to do what I want with the event publisher OnBeforeValidateLineDiscountAmount, but I can't call numerous local procedure.

Thank you for your work.

**Comment by StanPesotskiy** [comment]
Is it ok for you to use existing event OnBeforeUpdateLineDiscPct() if we will add a CurrFieldNo parameter there?

**Comment by Magicrevette** [comment]
Yes, it's ok for me.
