### ISSUE TITLE
[Parameter Request] Need add one extra parameter to event OnAfterPrepareInvoiceHeader(ServInvHeader, ServHeader); Codeunit 5988

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10930]
Please add one extra parameter to event OnAfterPrepareInvoiceHeader(ServInvHeader, ServHeader);

    procedure PrepareInvoiceHeader(var Window: Dialog): Code[20]
    var
        RecordLinkManagement: Codeunit "Record Link Management";
    begin
        with ServHeader do begin
            ServInvHeader.Init();
            ServInvHeader.TransferFields(ServHeader);
            if "Document Type" = "Document Type"::Order then begin
                ServInvHeader."No." := "Posting No.";
                ServInvHeader."Pre-Assigned No. Series" := '';
                ServInvHeader."Order No. Series" := "No. Series";
                ServInvHeader."Order No." := "No.";
                Window.Update(1, StrSubstNo(Text007, "Document Type", "No.", ServInvHeader."No."));
            end else begin
                ServInvHeader."Pre-Assigned No. Series" := "No. Series";
                ServInvHeader."Pre-Assigned No." := "No.";
                if "Posting No." <> '' then begin
                    ServInvHeader."No." := "Posting No.";
                    Window.Update(1, StrSubstNo(Text007, "Document Type", "No.", ServInvHeader."No."));
                end;
            end;
            if ServMgtSetup."Copy Comments Order to Invoice" then
                RecordLinkManagement.CopyLinks(ServHeader, ServInvHeader);
            ServInvHeader."Source Code" := SrcCode;
            ServInvHeader."User ID" := UserId;
            ServInvHeader."No. Printed" := 0;
            OnBeforeServInvHeaderInsert(ServInvHeader, ServHeader);
            ServInvHeader.Insert();
            OnAfterServInvHeaderInsert(ServInvHeader, ServHeader);

            Clear(ServLogMgt);
            case "Document Type" of
                "Document Type"::Invoice:
                    ServLogMgt.ServInvoicePost("No.", ServInvHeader."No.");
                "Document Type"::Order:
                    ServLogMgt.ServOrderInvoicePost("No.", ServInvHeader."No.");
            end;

            SetGenJnlLineDocNos(2,// Invoice
              ServInvHeader."No.", "No.");

            if ("Document Type" = "Document Type"::Invoice) or
               ("Document Type" = "Document Type"::Order) and ServMgtSetup."Copy Comments Order to Invoice"
            then
                ServOrderMgt.CopyCommentLinesWithSubType(
                  "Service Comment Table Name"::"Service Header".AsInteger(),
                  "Service Comment Table Name"::"Service Invoice Header".AsInteger(),
                  "No.", ServInvHeader."No.", "Document Type".AsInteger());

            OnAfterPrepareInvoiceHeader(ServInvHeader,ServItemLine, ServHeader);
            exit(ServInvHeader."No.");
        end;
    end;
    
    
Event:

    [IntegrationEvent(false, false)]
    local procedure OnAfterPrepareInvoiceHeader(var ServiceInvHeader: Record "Service Invoice Header"; ServItemLine: Record "Service Item Line" temporary; ServiceHeader: Record "Service Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
