### ISSUE TITLE
Bug Table 27 Item Function UpdateItemCategoryCode

### ISSUE THREAD

**Issue by MGerits** [microsoft/ALAppExtensions#10935]
Hello,

from my point of view in table 27 item functions UpdateItemCategoryCode the if condition is wrong. The if condition shold contain a **not** as it is also in the functions UpdateUnitOfMeasureCode and UpdateTaxGroupCode. Otherwise the the item category code will be always cleared.
```
local procedure UpdateItemCategoryCode()
    var
        ItemCategory: Record "Item Category";
    begin
        if IsNullGuid("Item Category Id") then
            ItemCategory.GetBySystemId("Item Category Id");

        "Item Category Code" := ItemCategory.Code;
    end;
```

The if condition should be

  ` if not IsNullGuid("Item Category Id") then`

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
