### ISSUE TITLE
[Event Request] table 472 "Job Queue Entry" - procedure HandleExecutionError() - OnHandleExecutionErrorOnBeforeSendNotification

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#10939]
Could You please, add the following event to the table 472 "Job Queue Entry"

Object: table 472 "Job Queue Entry"
procedure HandleExecutionError() 

Publisher Event: OnHandleExecutionErrorOnBeforeSendNotification

Reason: To implement custom business logic and avoid send notifications in some scenarios
Where is the event placed (see image attached)?:

![image](https://user-images.githubusercontent.com/73465025/107025586-eee43800-67a9-11eb-9123-2ecb829a2249.png)

before calling the CODEUNIT.Run 
Insert the next 3 lines

**IsHandled := false;
OnHandleExecutionErrorOnBeforeSendNotification(Rec, IsHandled);
if not IsHandled then**

Event Code:
[IntegrationEvent(false, false)]
local procedure OnHandleExecutionErrorOnBeforeSendNotification(var JobQueueEntry: Record "Job Queue Entry"; var IsHandled: Boolean)
begin
end;

Thanks in Advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
