### ISSUE TITLE
[Event Request] Codeunit 414 Release Sales Document  - OnBeforeReopenSalesDoc

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10936]
Hi, would it be possible to modify the event OnBeforeReopenSalesDoc in codeunit 414 Release Sales, procedure Reopen, like this : 
![image](https://user-images.githubusercontent.com/73548802/107019640-3666c600-67a2-11eb-8ea8-077edd052858.png)

```
 procedure Reopen(var SalesHeader: Record "Sales Header")
    var
        IsHandled : Boolean;
    begin
        IsHandled := false;
        OnBeforeReopenSalesDoc(SalesHeader, PreviewMode,IsHandled);
        if not Ishandled then exit;
        
        with SalesHeader do begin
            if Status = Status::Open then
                exit;
            Status := Status::Open;

            if "Document Type" <> "Document Type"::Order then
                ReopenATOs(SalesHeader);

            OnReopenOnBeforeSalesHeaderModify(SalesHeader);
            Modify(true);
            if "Document Type" in ["Document Type"::Order, "Document Type"::"Return Order"] then
                WhseSalesRelease.Reopen(SalesHeader);
        end;

        OnAfterReopenSalesDoc(SalesHeader, PreviewMode);
    end;
```
?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
