### ISSUE TITLE
[Event Request] Need event at the end of the function JobCalculateCommonFilters Codeunit 1008

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10941]
Add please event OnAfterJobCalculateCommonFilters at the end of the function JobCalculateCommonFilters

    procedure JobCalculateCommonFilters(var Job: Record Job)
    begin
        ClearAll;
        JobPlanningLine.SetCurrentKey("Job No.", "Job Task No.");
        JobLedgEntry.SetCurrentKey("Job No.", "Job Task No.", "Entry Type");
        JobPlanningLine.FilterGroup(2);
        JobLedgEntry.SetRange("Job No.", Job."No.");
        JobPlanningLine.SetRange("Job No.", Job."No.");
        JobPlanningLine.FilterGroup(0);
        JobLedgEntry.SetFilter("Posting Date", Job.GetFilter("Posting Date Filter"));
        JobPlanningLine.SetFilter("Planning Date", Job.GetFilter("Planning Date Filter"));

        OnAfterJobCalculateCommonFilters(Job);
    end;
    
Event:

    [IntegrationEvent(false, false)]
    local procedure OnAfterJobCalculateCommonFilters(var Job: Record Job)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
