### ISSUE TITLE
Regarding to #3143 change of table purchase line, publisher OnAfterValidateCrossReferenceNo

### ISSUE THREAD

**Issue by CarstenHeu** [microsoft/ALAppExtensions#10947]
Hello,
regarding to the case #3143 you added the eventpublisher OnAfterValidateCrossReferenceNo to the purchase line and sales line. But in the purchase line you missed to set the PurchaseLine parameter to set to a var parameter. In the sales line the SalesLine Parameter is correct set to a var parameter.
Please could you change it in the purchase line to a var parameter too? It helps if you want make changes to the purchase line in the event subscriber based on the choosen item cross reference (in our current case a description 3 + 4). Currently we could only make an modify to the given purchase line in the subscriber, causing an double modify with version conflict with the page modify!
Kind regards,
Carsten.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
