### ISSUE TITLE
[Event Request] Need event in function ReportAnalysis Codeunit 1008

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10943]
Please add an event OnAfterCalculateAmounts in the function ReportAnalysis (at the end of FOR cycle)

    procedure ReportAnalysis(var Job2: Record Job; var JT: Record "Job Task"; var Amt: array[8] of Decimal; AmountField: array[8] of Option " ",SchPrice,UsagePrice,ContractPrice,InvoicedPrice,SchCost,UsageCost,ContractCost,InvoicedCost,SchProfit,UsageProfit,ContractProfit,InvoicedProfit; CurrencyField: array[8] of Option LCY,FCY; JobLevel: Boolean)
        var
            PL: array[16] of Decimal;
            CL: array[16] of Decimal;
            P: array[16] of Decimal;
            C: array[16] of Decimal;
            I: Integer;
        begin
            if JobLevel then
                JobCalculateCommonFilters(Job2)
            else
                JTCalculateCommonFilters(JT, Job2, true);
            CalculateAmounts;
            GetLCYCostAmounts(CL);
            GetCostAmounts(C);
            GetLCYPriceAmounts(PL);
            GetPriceAmounts(P);
            Clear(Amt);
            for I := 1 to 8 do begin
                if AmountField[I] = AmountField[I] ::SchPrice then
                    if CurrencyField[I] = CurrencyField[I] ::LCY then
                        Amt[I] := PL[4]
                    else
                        Amt[I] := P[4];
                if AmountField[I] = AmountField[I] ::UsagePrice then
                    if CurrencyField[I] = CurrencyField[I] ::LCY then
                        Amt[I] := PL[8]
                    else
                        Amt[I] := P[8];
                if AmountField[I] = AmountField[I] ::ContractPrice then
                    if CurrencyField[I] = CurrencyField[I] ::LCY then
                        Amt[I] := PL[12]
                    else
                        Amt[I] := P[12];
                if AmountField[I] = AmountField[I] ::InvoicedPrice then
                    if CurrencyField[I] = CurrencyField[I] ::LCY then
                        Amt[I] := PL[16]
                    else
                        Amt[I] := P[16];
    
                if AmountField[I] = AmountField[I] ::SchCost then
                    if CurrencyField[I] = CurrencyField[I] ::LCY then
                        Amt[I] := CL[4]
                    else
                        Amt[I] := C[4];
                if AmountField[I] = AmountField[I] ::UsageCost then
                    if CurrencyField[I] = CurrencyField[I] ::LCY then
                        Amt[I] := CL[8]
                    else
                        Amt[I] := C[8];
                if AmountField[I] = AmountField[I] ::ContractCost then
                    if CurrencyField[I] = CurrencyField[I] ::LCY then
                        Amt[I] := CL[12]
                    else
                        Amt[I] := C[12];
                if AmountField[I] = AmountField[I] ::InvoicedCost then
                    if CurrencyField[I] = CurrencyField[I] ::LCY then
                        Amt[I] := CL[16]
                    else
                        Amt[I] := C[16];
    
                if AmountField[I] = AmountField[I] ::SchProfit then
                    if CurrencyField[I] = CurrencyField[I] ::LCY then
                        Amt[I] := PL[4] - CL[4]
                    else
                        Amt[I] := P[4] - C[4];
                if AmountField[I] = AmountField[I] ::UsageProfit then
                    if CurrencyField[I] = CurrencyField[I] ::LCY then
                        Amt[I] := PL[8] - CL[8]
                    else
                        Amt[I] := P[8] - C[8];
                if AmountField[I] = AmountField[I] ::ContractProfit then
                    if CurrencyField[I] = CurrencyField[I] ::LCY then
                        Amt[I] := PL[12] - CL[12]
                    else
                        Amt[I] := P[12] - C[12];
                if AmountField[I] = AmountField[I] ::InvoicedProfit then
                    if CurrencyField[I] = CurrencyField[I] ::LCY then
                        Amt[I] := PL[16] - CL[16]
                    else
                        Amt[I] := P[16] - C[16];
    
                OnAfterCalculateAmounts(AmountField, CurrencyField, Amt);
            end;
        end;
        
Event:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalculateAmounts(AmountField: array[8] of Option " ",SchPrice,UsagePrice,ContractPrice,InvoicedPrice,SchCost,UsageCost,ContractCost,InvoicedCost,SchProfit,UsageProfit,ContractProfit,InvoicedProfit; CurrencyField: array[8] of Option LCY,FCY; var Amt: array[8] of Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
