### ISSUE TITLE
[Event Request] Need event in function WhseLinesExist cudeunit 5777

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10948]
Add please event OnBeforeSetSourceFilterForWhseRcptLine in function WhseLinesExist

    procedure WhseLinesExist(SourceType: Integer; SourceSubType: Option; SourceNo: Code[20]; SourceLineNo: Integer; SourceSublineNo: Integer; SourceQty: Decimal): Boolean
    var
        WhseRcptLine: Record "Warehouse Receipt Line";
        WhseShptLine: Record "Warehouse Shipment Line";
        WhseManagement: Codeunit "Whse. Management";
    begin
        if not WhseRcptLine.ReadPermission then
            exit;
        if ((SourceType = DATABASE::"Purchase Line") and (SourceSubType = 1) and (SourceQty >= 0)) or
           ((SourceType = DATABASE::"Purchase Line") and (SourceSubType = 5) and (SourceQty < 0)) or
           ((SourceType = DATABASE::"Sales Line") and (SourceSubType = 1) and (SourceQty < 0)) or
           ((SourceType = DATABASE::"Sales Line") and (SourceSubType = 5) and (SourceQty >= 0)) or
           ((SourceType = DATABASE::"Transfer Line") and (SourceSubType = 1))
        then begin
            OnBeforeSetSourceFilterForWhseRcptLine(SourceType,SourceSubType,SourceQty);

            WhseManagement.SetSourceFilterForWhseRcptLine(WhseRcptLine, SourceType, SourceSubType, SourceNo, SourceLineNo, true);
            if not WhseRcptLine.IsEmpty then begin
                TableCaptionValue := WhseRcptLine.TableCaption;
                exit(true);
            end;
        end;

        if ((SourceType = DATABASE::"Purchase Line") and (SourceSubType = 1) and (SourceQty < 0)) or
           ((SourceType = DATABASE::"Purchase Line") and (SourceSubType = 5) and (SourceQty >= 0)) or
           ((SourceType = DATABASE::"Sales Line") and (SourceSubType = 1) and (SourceQty >= 0)) or
           ((SourceType = DATABASE::"Sales Line") and (SourceSubType = 5) and (SourceQty < 0)) or
           ((SourceType = DATABASE::"Transfer Line") and (SourceSubType = 0)) or
           ((SourceType = DATABASE::"Service Line") and (SourceSubType = 1))
        then begin
            WhseShptLine.SetSourceFilter(SourceType, SourceSubType, SourceNo, SourceLineNo, true);
            if not WhseShptLine.IsEmpty then begin
                TableCaptionValue := WhseShptLine.TableCaption;
                exit(true);
            end;
        end;
    end;
    
Event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetSourceFilterForWhseRcptLine(SourceType: Integer; SourceSubType: Option; SourceNo: Code[20];SourceQty: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
