### ISSUE TITLE
Report 699 OnBeforeSkipPlanningForItemOnReqWksh

### ISSUE THREAD

**Issue by msoleolivia** [Microsoft/ALAppExtensions#1094]
OnBeforeSkipPlanningForItemOnReqWksh(Item,SkipPlanning)

+If SkipPlanning then
    EXIT;

WITH Item DO
  IF (CurrWorksheetType = CurrWorksheetType::Requisition) AND
     ("Replenishment System" = "Replenishment System"::Purchase) AND
     ("Reordering Policy" <> "Reordering Policy"::" ")
  THEN
    EXIT(FALSE);

**Comment by AlexanderYakunin** [comment]
Already implemented

LOCAL SkipPlanningForItemOnReqWksh(Item : Record Item) : Boolean
IsHandled := FALSE;
SkipPlanning := FALSE;

OnBeforeSkipPlanningForItemOnReqWksh(Item,SkipPlanning,IsHandled);
IF IsHandled THEN
  EXIT(SkipPlanning);
