### ISSUE TITLE
[Event Request] Need event in function NonStockSales Codeunit 5703

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10953]
Please add event OnAfterNonStockSales to function NonStockSales

    procedure NonStockSales(var SalesLine2: Record "Sales Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeNonStockSales(NonStock, SalesLine2, IsHandled);
        If IsHandled then
            exit;
        if (SalesLine2."Document Type" in
            [SalesLine2."Document Type"::"Return Order", SalesLine2."Document Type"::"Credit Memo"])
        then
            Error(Text002, SalesLine2."Document Type");

        NonStock.Get(SalesLine2."No.");
        if NonStock."Item No." <> '' then begin
            SalesLine2."No." := NonStock."Item No.";
            exit;
        end;

        SalesLine2."No." :=
          GetNewItemNo(
            NonStock, StrLen(NonStock."Vendor Item No."), StrLen(NonStock."Manufacturer Code"));
        NonStock."Item No." := SalesLine2."No.";
        NonStock.Modify();
        OnNonStockSalesOnBeforeInsertItemUnitOfMeasure(NonStock);
        InsertItemUnitOfMeasure(NonStock."Unit of Measure", SalesLine2."No.");

        NewItem.SetRange("No.", SalesLine2."No.");
        if NewItem.FindFirst() then
            exit;

        ProgWindow.Open(Text003 +
          Text004 +
          Text005 +
          Text006 +
          Text007);
        ProgWindow.Update(1, NonStock."Manufacturer Code");
        ProgWindow.Update(2, NonStock."Vendor No.");
        ProgWindow.Update(3, NonStock."Vendor Item No.");
        ProgWindow.Update(4, SalesLine2."No.");

        CreateNewItem(SalesLine2."No.", NonStock);
        OnNonStockSalesOnAfterCreateNewItem(NewItem);

        if CheckLicensePermission(DATABASE::"Item Vendor") then
            NonstockItemVend(NonStock);
        if CheckLicensePermission(DATABASE::"Item Reference") and ItemReferenceMgt.IsEnabled() then
            NonstockItemReference(NonStock);
        if CheckLicensePermission(DATABASE::"Item Cross Reference") and not ItemReferenceMgt.IsEnabled() then
            NonstockItemCrossRef(NonStock);

        OnAfterNonStockSales(NonStock; NewItem);

        ProgWindow.Close();
    end;
    
    
Event:

    [IntegrationEvent(false, false)]
    local procedure OnAfterNonStockSales(NonStock: Record "Nonstock Item"; NewItem: Record Item)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
