### ISSUE TITLE
[Event Request] Need add event to Codeunit 5703 function DelNonStockItem

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10956]
Add please event OnBeforeFindNonStock to fuction DelNonStockItem

    local procedure DelNonStockItem(var Item: Record Item)
    var
        SalesLineArch: Record "Sales Line Archive";
        IsHandled: Boolean;
    begin
        ItemLedgEntry.SetCurrentKey("Item No.");
        ItemLedgEntry.SetRange("Item No.", Item."No.");
        if ItemLedgEntry.FindFirst() then
            exit;

        SalesLine.SetCurrentKey(Type, "No.");
        SalesLine.SetRange(Type, SalesLine.Type::Item);
        SalesLine.SetRange("No.", Item."No.");
        if SalesLine.FindFirst() then
            exit;

        PurchLine.SetCurrentKey(Type, "No.");
        PurchLine.SetRange(Type, PurchLine.Type::Item);
        PurchLine.SetRange("No.", Item."No.");
        if PurchLine.FindFirst() then
            exit;

        ServInvLine.SetCurrentKey(Type, "No.");
        ServInvLine.SetRange(Type, ServInvLine.Type::Item);
        ServInvLine.SetRange("No.", Item."No.");
        if ServInvLine.FindFirst() then
            exit;

        BOMComp.SetCurrentKey(Type, "No.");
        BOMComp.SetRange(Type, BOMComp.Type::Item);
        BOMComp.SetRange("No.", Item."No.");
        if BOMComp.FindFirst() then
            exit;

        SalesLineArch.SetCurrentKey(Type, "No.");
        SalesLineArch.SetRange(Type, SalesLineArch.Type::Item);
        SalesLineArch.SetRange("No.", Item."No.");
        if not SalesLineArch.IsEmpty then
            exit;

        ProdBOMLine.Reset();
        ProdBOMLine.SetCurrentKey(Type, "No.");
        ProdBOMLine.SetRange(Type, ProdBOMLine.Type::Item);
        ProdBOMLine.SetRange("No.", Item."No.");
        if ProdBOMLine.Find('-') then
            repeat
                if ProdBOMHeader.Get(ProdBOMLine."Production BOM No.") and
                   (ProdBOMHeader.Status = ProdBOMHeader.Status::Certified)
                then
                    exit;
            until ProdBOMLine.Next = 0;

        NewItem.Get(Item."No.");

        IsHandled := false;
        OnBeforeFindNonStock(NewItem,NonStock,IsHandled)

        if not IsHandled then begin
            if NewItem.Delete(true) then begin
                NonStock.SetRange("Item No.", Item."No.");
                if NonStock.Find('-') then
                    repeat
                        NonStock."Item No." := '';
                        NonStock.Modify();
                    until NonStock.Next = 0;
            end;
        end;
    end;
    
    
Event;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindNonStock(NewItem: Record Item;NonStock: Record "Nonstock Item";IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
