### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnSelectItemEntryOnBeforeSetRangeLocationCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10959]
Hello. In Table 39 "Purchase Line", in local procedure SelectItemEntry, we would like to manipulate the record ItemLedgEntry to modify the SetRange. To do so, we would need the parameter ItemLedgEntry be added to the event publisher OnSelectItemEntryOnBeforeSetRangeLocationCode, like this :

    local procedure SelectItemEntry()
    var
        ItemLedgEntry: Record "Item Ledger Entry";
    begin
        TestField("Prod. Order No.", '');
        ItemLedgEntry.SetCurrentKey("Item No.", Open);
        ItemLedgEntry.SetRange("Item No.", "No.");
        ItemLedgEntry.SetRange(Open, true);
        ItemLedgEntry.SetRange(Positive, true);
        OnSelectItemEntryOnBeforeSetRangeLocationCode(Rec, ItemLedgEntry);
        if "Location Code" <> '' then
            ItemLedgEntry.SetRange("Location Code", "Location Code");
        ItemLedgEntry.SetRange("Variant Code", "Variant Code");

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnSelectItemEntryOnBeforeSetRangeLocationCode(var PurchaseLine: Record "Purchase Line")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
