### ISSUE TITLE
[Event Request] Need add event to Codeunit 5703

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10950]
Add please event OnBeforeNonStock2TestField to function NonstockAutoItem

    procedure NonstockAutoItem(NonStock2: Record "Nonstock Item")
    var
        IsHandled: Boolean;
    begin
        OnBeforeNonstockAutoItem(NonStock2);
        if NewItem.Get(NonStock2."Item No.") then
            Error(Text000, NonStock2."Item No.");

        NonStock2."Item No." :=
          GetNewItemNo(
            NonStock2, StrLen(NonStock2."Vendor Item No."), StrLen(NonStock2."Manufacturer Code"));
        NonStock2.Modify();
        OnNonstockAutoItemOnBeforeInsertItemUnitOfMeasure(NonStock2);
        InsertItemUnitOfMeasure(NonStock2."Unit of Measure", NonStock2."Item No.");

        IsHandled := false;
        OnBeforeNonStock2TestField(NonStock2,IsHandled);
        if not IsHandled then begin
            NonStock2.TestField("Vendor No.");
            NonStock2.TestField("Vendor Item No.");
            NonStock2.TestField("Item Template Code");
        end;

        if NewItem.Get(NonStock2."Item No.") then
            Error(Text000, NonStock2."Item No.");

        CreateNewItem(NonStock2."Item No.", NonStock2);
        OnNonstockAutoItemOnAfterCreateNewItem(NewItem);
        Message(Text001, NonStock2."Item No.");

        if CheckLicensePermission(DATABASE::"Item Vendor") then
            NonstockItemVend(NonStock2);
        if CheckLicensePermission(DATABASE::"Item Reference") and ItemReferenceMgt.IsEnabled() then
            NonstockItemReference(NonStock2);
        if CheckLicensePermission(DATABASE::"Item Cross Reference") and not ItemReferenceMgt.IsEnabled() then
            NonstockItemCrossRef(NonStock2);
    end;
    
Event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeNonStock2TestField(NonStock: Record "Nonstock Item"; IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
