### ISSUE TITLE
[Event Request] Table 37 OnAfterCheckInCopyFromItem

### ISSUE THREAD

**Issue by GuntherGebauer** [Microsoft/ALAppExtensions#1095]
we Need a new Publisher in table 37 to execute individual checks in CopyFromItem:

LOCAL CopyFromItem()
GetItem(Item);
Item.TESTFIELD(Blocked,FALSE);
Item.TESTFIELD("Gen. Prod. Posting Group");
IF Item."Sales Blocked" THEN
  ERROR(SalesBlockedErr);
IF Item.Type = Item.Type::Inventory THEN BEGIN
  Item.TESTFIELD("Inventory Posting Group");
  "Posting Group" := Item."Inventory Posting Group";
END;

//FVA +++++++++++++++++++++++++++++
OnAfterCheckInCopyFromItem(VAR rec:SalesLine2,Item);  <-- NewEvent
//FVA -----------------------------

**Comment by GuntherGebauer** [comment]
the same new Event is also required in table 39

**Comment by AlexanderYakunin** [comment]
You an add extra checks into OnAfterCopyFromItem(Rec,Item);

**Comment by GuntherGebauer** [comment]
I do not yet have the trigger "OnAfterCopyFromItem" (CU03) - but only OnAfterAssignItemValues within CopyfromItem.

Trigger OnAfterAssignItemValues is not usable here because I Need a check before a Validate on Quantity is done. In CopyfromItem the function calls InitDeferralCode and SetDefaultItemQuantity both validate fields which is then done without my own checks.
