### ISSUE TITLE
App publishing in the BC17 Mexico localization is not possible

### ISSUE THREAD

**Issue by michuanni** [microsoft/ALAppExtensions#10955]
When we try to publish our app in the Mexico localization than we receive the following error: 

Publish-NAVApp : Extension compilation failed
src/codeunit/MasterDoc.Codeunit.al(1731,39): error AL0135: There is no argument given that corresponds to the required formal parameter 'IsPrepayment' of 'InsertNewLine(Code[20], Enum 
"Tax Calculation Type", Code[20], Code[20], Boolean, Decimal, Boolean, Boolean)'
In Zeile:1 Zeichen:1
+ Publish-NAVApp -ServerInstance $ServiceName -Path 'E:\UTT\Apps\
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$UTTMXBC17/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp

The function InsertNewLine in the VAT Amount Line table have been changed in the Mexico localization.

How can we create a app for the global use, when there a major changes in the standard objects?

Yours 

Michael

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 17.
