### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnAfterInitHeaderDefaults with TempPurchLine

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10958]
Hello. We are migrating our code from nav 2018 to BC 17.3. In table 39 Purchase Line, in field 06 - "No.", in trigger OnValidate, we used to send to the local procedure InitHeaderDefaults a second parameter : TempPurchLine. We used it in the procedure to change the value of some Rec fields.

We would like to add this parameter TempPurchLine to the procedure InitHeaderDefaults and to the event publisher OnAfterInitHeaderDefaults to be able to use it in our event subscriber , like this : 

        field(6; "No."; Code[20])
        {
            ...
            trigger OnValidate()
            var
                TempPurchLine: Record "Purchase Line" temporary;
            begin
                ...

                GetPurchHeader;
                InitHeaderDefaults(PurchHeader, TempPurchLine);
                UpdateLeadTimeFields;
                UpdateDates;

                ....
            end;

    ...

    local procedure InitHeaderDefaults(PurchHeader: Record "Purchase Header"; TempPurchLine : record "Purchase Line" temporary)
    begin
        ...
        OnAfterInitHeaderDefaults(Rec, PurchHeader, TempPurchLine);
    end;

    ...

        [IntegrationEvent(false, false)]
    local procedure OnAfterInitHeaderDefaults(var PurchLine: Record "Purchase Line"; PurchHeader: Record "Purchase Header"; TempPurchLine : record "Purchase Line" temporary)
    begin
    end;

We figured out no other way to reach the TempPurchLine from the event subscriber OnAfterInitHeaderDefaults. Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
