### ISSUE TITLE
[Request-for-external] table 37 "Sales Line" - GetPriceCalculationHandler

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#10957]
Can you change GetPriceCalculationHandler to global?

When I use event OnUpdateUnitPriceOnBeforeFindPrice and set IsHandled := true, I want to get the same price calculation interface. I have now copied the procedure as a temp. fix.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
