### ISSUE TITLE
[Event Request] Need add event to Codeunit 5703

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10951]
Add please event OnBeforeNonStockTestFieldCreateItemFromNonstock to function CreateItemFromNonstock

    procedure CreateItemFromNonstock(Nonstock2: Record "Nonstock Item")
    begin
        OnBeforeCreateItemFromNonstock(Nonstock2);
        if NewItem.Get(Nonstock2."Item No.") then
            Error(Text000, Nonstock2."Item No.");

        Nonstock2."Item No." :=
          GetNewItemNo(
            Nonstock2, StrLen(Nonstock2."Vendor Item No."), StrLen(Nonstock2."Manufacturer Code"));
        Nonstock2.Modify();
        OnCreateItemFromNonstockOnBeforeInsertItemUnitOfMeasure(NonStock2);
        InsertItemUnitOfMeasure(Nonstock2."Unit of Measure", Nonstock2."Item No.");

        IsHandled := false;
        OnBeforeNonStockTestFieldCreateItemFromNonstock(NonStock2,IsHandled);
        if not IsHandled then begin
            NonStock2.TestField("Vendor No.");
            NonStock2.TestField("Vendor Item No.");
            NonStock2.TestField("Item Template Code");
        end;

        if NewItem.Get(Nonstock2."Item No.") then
            Error(Text000, Nonstock2."Item No.");

        CreateNewItem(Nonstock2."Item No.", Nonstock2);

        if CheckLicensePermission(DATABASE::"Item Vendor") then
            NonstockItemVend(Nonstock2);
        if CheckLicensePermission(DATABASE::"Item Reference") and ItemReferenceMgt.IsEnabled() then
            NonstockItemReference(Nonstock2);
        if CheckLicensePermission(DATABASE::"Item Cross Reference") and not ItemReferenceMgt.IsEnabled() then
            NonstockItemCrossRef(Nonstock2);
    end;
    
Event;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeNonStockTestFieldCreateItemFromNonstock(NonStock: Record "Nonstock Item"; IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
