### ISSUE TITLE
[Event Request] Codeunit 1372 Purchase Batch Post Mgt - OnBeforeRunBatch 

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10961]
Hi, would it be possible to get an event OnBeforeRunBatch in codeunit 1372, procedure RunBatch, like this : 
![image](https://user-images.githubusercontent.com/73548802/107056976-329f6780-67d3-11eb-95c8-115f04857d9b.png)

```
procedure RunBatch(var PurchaseHeader: Record "Purchase Header"; ReplacePostingDate: Boolean; PostingDate: Date; ReplaceDocumentDate: Boolean; CalcInvoiceDiscount: Boolean; Receive: Boolean; Invoice: Boolean)
    var
        TempErrorMessage: Record "Error Message" temporary;
        PurchaseBatchPostMgt: Codeunit "Purchase Batch Post Mgt.";
        ErrorMessages: Page "Error Messages";
    begin

        OnBeforeRunBatch(ReplacePostingDate,PostingDate,ReplaceDocumentDate,Receive,Invoice);
        
        if ReplacePostingDate and (PostingDate = 0D) then
            Error(PostingDateIsNotSetErr);

```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeRunBatch(ReplacePostingDate : Boolean ; PostingDate : Date ; ReplaceDocumentDate : Boolean ; Receive : Boolean ; Invoice : Boolean)
    begin
    end;    

```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
