### ISSUE TITLE
[Event Request] Need add event to Codeunit 5818 function InsertNewShipmentLine

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10969]
Please add event OnBeforeInsertItemEntryRelation to function InsertNewShipmentLine

    local procedure InsertNewShipmentLine(OldServShptLine: Record "Service Shipment Line"; ItemShptEntryNo: Integer)
    var
        NewServShptLine: Record "Service Shipment Line";
    begin

        OnBeforeInsertItemEntryRelation(OldServShptLine, NewServShptLine, TempGlobalItemEntryRelation)

        with OldServShptLine do begin
            NewServShptLine.Reset();
            NewServShptLine.Init();
            NewServShptLine.Copy(OldServShptLine);
            NewServShptLine."Line No." := "Line No." + GetCorrectiveShptLineNoStep("Document No.", "Line No.");
            NewServShptLine."Item Shpt. Entry No." := ItemShptEntryNo;
            NewServShptLine."Appl.-to Service Entry" := "Appl.-to Service Entry";
            NewServShptLine.Quantity := -Quantity;
            NewServShptLine."Qty. Shipped Not Invoiced" := 0;
            NewServShptLine."Qty. Shipped Not Invd. (Base)" := 0;
            NewServShptLine."Quantity (Base)" := -"Quantity (Base)";
            NewServShptLine."Quantity Invoiced" := NewServShptLine.Quantity;
            NewServShptLine."Qty. Invoiced (Base)" := NewServShptLine."Quantity (Base)";
            NewServShptLine.Correction := true;
            NewServShptLine."Dimension Set ID" := "Dimension Set ID";
            OnBeforeNewServiceShptLineInsert(NewServShptLine, OldServShptLine);
            NewServShptLine.Insert();

            InsertItemEntryRelation(TempGlobalItemEntryRelation, NewServShptLine);
        end;
    end;
    
Event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertItemEntryRelation(OldServShptLine: Record "Service Shipment Line"; NewServShptLine: Record "Service Shipment Line"; TempGlobalItemEntryRelation: Record "Item Entry Relation")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
