### ISSUE TITLE
[Event Request] Need add event to Codeunit 5818 function SetHideDialog

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10968]
Add please event OnBeforeInsertNewShipmentLine to function SetHideDialog

    procedure SetHideDialog(NewHideDialog: Boolean)
    begin
        HideDialog := NewHideDialog;
    end;

    local procedure "Code"()
    var
        PostedWhseShptLine: Record "Posted Whse. Shipment Line";
        ServiceLine: Record "Service Line";
        ServItem: Record "Service Item";
        ServLedgEntriesPost: Codeunit "ServLedgEntries-Post";
        ConfirmManagement: Codeunit "Confirm Management";
        Window: Dialog;
        ItemShptEntryNo: Integer;
        ServLedgEntryNo: Integer;
        WarrantyLedgEntryNo: Integer;
        DeleteServItems: Boolean;
        PostedWhseShptLineFound: Boolean;
        IsHandled: Boolean;
    begin
        with ServShptLine do begin
            Clear(ItemJnlPostLine);
            SetRange(Correction, false);
            FindFirst;
            repeat
                if not HideDialog then
                    Window.Open(Text003);
                CheckServShptLine(ServShptLine);
            until Next = 0;

            ServItem.SetCurrentKey("Sales/Serv. Shpt. Document No.");
            ServItem.SetRange("Sales/Serv. Shpt. Document No.", "Document No.");
            ServItem.SetRange("Sales/Serv. Shpt. Line No.", "Line No.");
            ServItem.SetRange("Shipment Type", ServItem."Shipment Type"::Service);

            if ServItem.FindFirst then
                if not HideDialog then
                    DeleteServItems := ConfirmManagement.GetResponseOrDefault(Text005, true)
                else
                    DeleteServItems := true;

            ServLedgEntriesPost.InitServiceRegister(ServLedgEntryNo, WarrantyLedgEntryNo);
            Find('-');
            repeat
                TempGlobalItemLedgEntry.Reset();
                if not TempGlobalItemLedgEntry.IsEmpty then
                    TempGlobalItemLedgEntry.DeleteAll();
                TempGlobalItemEntryRelation.Reset();
                if not TempGlobalItemEntryRelation.IsEmpty then
                    TempGlobalItemEntryRelation.DeleteAll();

                if not HideDialog then
                    Window.Open(Text001);

                PostedWhseShptLineFound :=
                    WhseUndoQty.FindPostedWhseShptLine(
                        PostedWhseShptLine, DATABASE::"Service Shipment Line", "Document No.",
                        DATABASE::"Service Line", ServiceLine."Document Type"::Order.AsInteger(), "Order No.", "Order Line No.");

                if Type = Type::Item then
                    ItemShptEntryNo := PostItemJnlLine(ServShptLine)
                else
                    ItemShptEntryNo := 0;

                if Type = Type::Resource then
                    PostResJnlLine(ServShptLine);

                IsHandled := false;
                OnBeforeInsertNewShipmentLine(ServShptLine, ItemShptEntryNo, IsHandled);

                if not IsHandled then
                    InsertNewShipmentLine(ServShptLine, ItemShptEntryNo);

                OnAfterInsertNewShipmentLine(ServShptLine, PostedWhseShptLine, PostedWhseShptLineFound);

                if PostedWhseShptLineFound then
                    WhseUndoQty.UndoPostedWhseShptLine(PostedWhseShptLine);

                ServLedgEntriesPost.ReverseServLedgEntry(ServShptLine);
                if Type in [Type::Item, Type::Resource] then
                    ServLedgEntriesPost.ReverseWarrantyEntry(ServShptLine);

                UpdateOrderLine(ServShptLine);
                if PostedWhseShptLineFound then
                    WhseUndoQty.UpdateShptSourceDocLines(PostedWhseShptLine);

                if DeleteServItems then
                    DeleteServShptLineServItems(ServShptLine);

                "Quantity Invoiced" := Quantity;
                "Qty. Invoiced (Base)" := "Quantity (Base)";
                "Qty. Shipped Not Invoiced" := 0;
                "Qty. Shipped Not Invd. (Base)" := 0;
                Correction := true;
                Modify;

            until Next = 0;
            ServLedgEntriesPost.FinishServiceRegister(ServLedgEntryNo, WarrantyLedgEntryNo);

            InvtSetup.Get();
            if InvtSetup."Automatic Cost Adjustment" <>
               InvtSetup."Automatic Cost Adjustment"::Never
            then begin
                ServShptHeader.Get("Document No.");
                InvtAdjmt.SetProperties(true, InvtSetup."Automatic Cost Posting");
                InvtAdjmt.SetJobUpdateProperties(true);
                InvtAdjmt.MakeMultiLevelAdjmt;
            end;
            WhseUndoQty.PostTempWhseJnlLine(TempWhseJnlLine);
        end;

        OnAfterCode(ServShptLine);
    end;
    
Event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertNewShipmentLine(ServShptLine: Record "Service Shipment Line"; ItemShptEntryNo: Integer; IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
