### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnUpdateDirectUnitCostByFieldOnBeforeUpdateItemReference

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10962]
Hello. In Table 39 "Purchase Line", in local procedure UpdateDirectUnitCostByField, in the event subscriber to OnUpdateDirectUnitCostByFieldOnBeforeUpdateItemReference, we would like to test CalledByFieldNo in a if statement. But it isn't in the event parameters. Is it possible to add it ? Like this : 

        OnUpdateDirectUnitCostByFieldOnBeforeUpdateItemReference(Rec, CalledByFieldNo);
        if Type = Type::Item then
            if CalledByFieldNo in [FieldNo("No."), FieldNo("Variant Code"), FieldNo("Location Code")] then
                UpdateItemReference;

With the event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnUpdateDirectUnitCostByFieldOnBeforeUpdateItemReference(var PurchaseLine: Record "Purchase Line"; CalledByFieldNo : integer)
    begin
    end;

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
