### ISSUE TITLE
[Event Request] Need add event to Codeunit 5940 function CreateInvoice

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10967]
Please add event OnBeforeCreateAllServLines to function CreateInvoice

    [Scope('OnPrem')]
    procedure CreateInvoice(ServiceContractHeader: Record "Service Contract Header") InvNo: Code[20]
    var
        InvoicedAmount: Decimal;
        InvoiceFromDate: Date;
        InvoiceToDate: Date;
    begin
        OnBeforeCreateInvoice(ServiceContractHeader);
        ServiceContractHeader.TestField("Change Status", ServiceContractHeader."Change Status"::Locked);
        GetNextInvoicePeriod(ServiceContractHeader, InvoiceFromDate, InvoiceToDate);
        CreateInvoiceSetPostingDate(ServiceContractHeader, InvoiceFromDate, InvoiceToDate, PostingDate);

        InvoicedAmount := CalcContractAmount(ServiceContractHeader, InvoiceFromDate, InvoiceToDate);
        if InvoicedAmount = 0 then
            Error(Text007);

        InvNo := CreateRemainingPeriodInvoice(ServiceContractHeader);

        if InvNo = '' then
            InvNo := CreateServHeader(ServiceContractHeader, PostingDate, false);

        if InvoicingStartingPeriod then begin
            GetNextInvoicePeriod(ServiceContractHeader, InvoiceFromDate, InvoiceToDate);
            PostingDate := InvoiceFromDate;
            InvoicedAmount := CalcContractAmount(ServiceContractHeader, InvoiceFromDate, InvoiceToDate);
        end;

        if not CheckIfServiceExist(ServiceContractHeader) then
            Error(
              Text010,
              ServiceContractHeader."Contract No.",
              ServiceContractHeader.FieldCaption("Invoice after Service"));

        OnBeforeCreateAllServLines(ServiceContractHeader,InvoiceFromDate, InvoiceToDate, InvoicedAmount, PostingDate, InvoicingStartingPeriod, InvNo)

        CreateAllServLines(InvNo, ServiceContractHeader);

        OnAfterCreateInvoice(ServiceContractHeader, PostingDate);
    end;
    
    
Event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateAllServLines(ServiceContractHeader: Record "Service Contract Header"; InvoiceFromDate: Date; InvoiceToDate: Date;  var InvoicedAmount: Decimal; var PostingDate: Date; InvoicingStartingPeriod: Boolean; InvNo: Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
