### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnUpdateVATAmountsOnBeforeAmountIncludingVAT

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10965]
Hello. In table 39, in the procedure UpdateVATAmounts, we would like to change the way the field "Amount Including VAT" is calculated. To do so, we would need a IsHandled flag and an event publisher. Like this : 

            if PurchHeader."Prices Including VAT" then
                case "VAT Calculation Type" of
                    "VAT Calculation Type"::"Normal VAT",
                    "VAT Calculation Type"::"Reverse Charge VAT":
                        begin
                            Amount :=
                              Round(
                                (TotalLineAmount - TotalInvDiscAmount + CalcLineAmount) / (1 + "VAT %" / 100),
                                Currency."Amount Rounding Precision") -
                              TotalAmount;
                            "VAT Base Amount" :=
                              Round(
                                Amount * (1 - PurchHeader."VAT Base Discount %" / 100),
                                Currency."Amount Rounding Precision");

                             IsHandled := false;
                             OnUpdateVATAmountsOnBeforeAmountIncludingVAT(Rec, PurchHeader, Currency, TotalAmount, TotalAmountInclVAT, IsHandled);
                             if not IsHandled then

                            "Amount Including VAT" :=
                              TotalLineAmount + "Line Amount" -
                              Round(
                                (TotalAmount + Amount) * (PurchHeader."VAT Base Discount %" / 100) * "VAT %" / 100,
                                Currency."Amount Rounding Precision", Currency.VATRoundingDirection) -
                              TotalAmountInclVAT - TotalInvDiscAmount - "Inv. Discount Amount";
                        end;

With this event publisher : 

    [IntegrationEvent(false, false)]
    local procedure OnUpdateVATAmountsOnBeforeAmountIncludingVAT(var PurchaseLine: Record "Purchase Line"; PurchHeader : record "Purchase Header"; Currency : record Currency; TotalAmount : Decimal; TotalAmountInclVAT : Decimal; var IsHandled: Boolean)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
