### ISSUE TITLE
[Event Request] CU 226 - Add parameter in Event "OnApplyApplyCustEntryFormEntryOnAfterCustLedgEntrySetFilters"

### ISSUE THREAD

**Issue by manishs-acumencentral** [microsoft/ALAppExtensions#10963]
Hi Team,

This event is published in codeunit 226 "CustEntry-Apply Posted Entries"
Can you please add one boolean parameter (IsHandled) in event OnApplyApplyCustEntryFormEntryOnAfterCustLedgEntrySetFilters and also some code. i.e. if not IsHandled then execute the below code.

Current
[IntegrationEvent(false, false)]
local procedure OnApplyApplyCustEntryFormEntryOnAfterCustLedgEntrySetFilters(var CustLedgerEntry: Record "Cust. Ledger Entry"; var ApplyingCustLedgerEntry: Record "Cust. Ledger Entry" temporary);
begin
end;

Perposed :
[IntegrationEvent(false, false)]
local procedure OnApplyApplyCustEntryFormEntryOnAfterCustLedgEntrySetFilters(var CustLedgerEntry: Record "Cust. Ledger Entry"; var ApplyingCustLedgerEntry: Record "Cust. Ledger Entry" temporary; var IsHandled: Boolean);
begin
end;

Thanks,
Manish Sinha

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
