### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnRunOnBeforeMakeInventoryAdjustment

### ISSUE THREAD

**Issue by maw-notora** [microsoft/ALAppExtensions#10975]
In order for our code to function in BC15 and forward, we need a specific event-publisher in codeunit 80 and 90 that is able to pass the right instance of the sales/purchase header as well as the right instance of the codeunit "Gen. Jnl.-Post Line". 

In codeunit 80, there has already been added a publisher function in the correct spot: 
![image](https://user-images.githubusercontent.com/78422825/107214266-f4d85400-6a09-11eb-974d-11f9bdf63332.png)

But it does not provide the correct instance of the variable "GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line", please add GenJnlPostLine as a variable to OnRunOnBeforeMakeInventoryAdjustment:

![image](https://user-images.githubusercontent.com/78422825/107214623-6fa16f00-6a0a-11eb-8899-e5e8096ec0b9.png)

We have tried using other events, but no other event-publishers supply the needed instances of the variables Sales-/Purchase Header and the GenJnlPostLine Codeunit.

I will create a seperate issue for the event-request for Codeunit 90. Let me know if you have any inquiries.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
