### ISSUE TITLE
[Event Request] CodeUnit 10801 - RIB Key - Check() - OnBeforeCheck |  CheckRemaining

### ISSUE THREAD

**Issue by i-dhahri** [microsoft/ALAppExtensions#10972]
Hello, would it be possible to have two events "OnBeforeCheck" and "CheckRemaining" in Codeunit 10801 "RIB Key" , procedure Check(), Like this :

![image](https://user-images.githubusercontent.com/77328410/107213424-ad9d9380-6a08-11eb-9203-7efcdb3fe9c6.png)

Cordially.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
