### ISSUE TITLE
[Event Request] Need add event to Codeunit "Purch.-Post" function PostItemChargePerOrder

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10976]
Add please event OnBeforeTempTrackingSpecificationChargeAssmt to function PostItemChargePerOrder

        local procedure PostItemChargePerOrder(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; ItemJnlLine2: Record "Item Journal Line"; ItemChargePurchLine: Record "Purchase Line"; var TempTrackingSpecificationChargeAssmt: Record "Tracking Specification" temporary)
    var
        NonDistrItemJnlLine: Record "Item Journal Line";
        CurrExchRate: Record "Currency Exchange Rate";
        OriginalAmt: Decimal;
        OriginalAmtACY: Decimal;
        OriginalDiscountAmt: Decimal;
        OriginalQty: Decimal;
        QtyToInvoice: Decimal;
        Factor: Decimal;
        SignFactor: Integer;
        IsHandled: Boolean;
    begin
        OnBeforePostItemChargePerOrder(
          PurchHeader, PurchLine, ItemJnlLine2, ItemChargePurchLine, TempTrackingSpecificationChargeAssmt, SuppressCommit,
          TempItemChargeAssgntPurch);

        with TempItemChargeAssgntPurch do begin
            PurchLine.TestField("Allow Item Charge Assignment", true);
            ItemJnlLine2."Document No." := GenJnlLineDocNo;
            ItemJnlLine2."External Document No." := GenJnlLineExtDocNo;
            ItemJnlLine2."Item Charge No." := "Item Charge No.";
            ItemJnlLine2.Description := ItemChargePurchLine.Description;
            ItemJnlLine2."Document Line No." := ItemChargePurchLine."Line No.";
            ItemJnlLine2."Unit of Measure Code" := '';
            ItemJnlLine2."Qty. per Unit of Measure" := 1;
            if "Document Type" in ["Document Type"::"Return Order", "Document Type"::"Credit Memo"] then
                QtyToInvoice :=
                  CalcQtyToInvoice(PurchLine."Return Qty. to Ship (Base)", PurchLine."Qty. to Invoice (Base)")
            else
                QtyToInvoice :=
                  CalcQtyToInvoice(PurchLine."Qty. to Receive (Base)", PurchLine."Qty. to Invoice (Base)");
            if ItemJnlLine2."Invoiced Quantity" = 0 then begin
                ItemJnlLine2."Invoiced Quantity" := ItemJnlLine2.Quantity;
                ItemJnlLine2."Invoiced Qty. (Base)" := ItemJnlLine2."Quantity (Base)";
            end;
            ItemJnlLine2.Amount := "Amount to Assign" * ItemJnlLine2."Invoiced Qty. (Base)" / QtyToInvoice;
            if "Document Type" in ["Document Type"::"Return Order", "Document Type"::"Credit Memo"] then
                ItemJnlLine2.Amount := -ItemJnlLine2.Amount;
            ItemJnlLine2."Unit Cost (ACY)" :=
              Round(
                ItemJnlLine2.Amount / ItemJnlLine2."Invoiced Qty. (Base)",
                Currency."Unit-Amount Rounding Precision");

            PreciseTotalChargeAmt += ItemJnlLine2.Amount;

            if PurchHeader."Currency Code" <> '' then
                ItemJnlLine2.Amount :=
                  CurrExchRate.ExchangeAmtFCYToLCY(
                    Usedate, PurchHeader."Currency Code", PreciseTotalChargeAmt + TotalPurchLine.Amount, PurchHeader."Currency Factor") -
                  RoundedPrevTotalChargeAmt - TotalPurchLineLCY.Amount
            else
                ItemJnlLine2.Amount := PreciseTotalChargeAmt - RoundedPrevTotalChargeAmt;

            RoundedPrevTotalChargeAmt += Round(ItemJnlLine2.Amount, GLSetup."Amount Rounding Precision");

            ItemJnlLine2."Unit Cost" := Round(
                ItemJnlLine2.Amount / ItemJnlLine2."Invoiced Qty. (Base)", GLSetup."Unit-Amount Rounding Precision");
            ItemJnlLine2."Applies-to Entry" := ItemJnlLine2."Item Shpt. Entry No.";
            ItemJnlLine2."Overhead Rate" := 0;

            if TaxOption = TaxOption::SalesTax then
                ItemJnlLine2.Amount +=
                  ItemChargePurchLine."Tax To Be Expensed" * "Qty. to Assign" / ItemChargeQtyToAssign(ItemChargePurchLine);

            if PurchHeader."Currency Code" <> '' then
                ItemJnlLine2."Discount Amount" := Round(
                    CurrExchRate.ExchangeAmtFCYToLCY(
                      Usedate, PurchHeader."Currency Code", (ItemChargePurchLine."Inv. Discount Amount" +
                                                           ItemChargePurchLine."Line Discount Amount") *
                      ItemJnlLine2."Invoiced Qty. (Base)" /
                      ItemChargePurchLine."Quantity (Base)" * "Qty. to Assign" / QtyToInvoice,
                      PurchHeader."Currency Factor"), GLSetup."Amount Rounding Precision")
            else
                ItemJnlLine2."Discount Amount" := Round(
                    (ItemChargePurchLine."Line Discount Amount" + ItemChargePurchLine."Inv. Discount Amount") *
                    ItemJnlLine2."Invoiced Qty. (Base)" /
                    ItemChargePurchLine."Quantity (Base)" * "Qty. to Assign" / QtyToInvoice,
                    GLSetup."Amount Rounding Precision");

            ItemJnlLine2."Shortcut Dimension 1 Code" := ItemChargePurchLine."Shortcut Dimension 1 Code";
            ItemJnlLine2."Shortcut Dimension 2 Code" := ItemChargePurchLine."Shortcut Dimension 2 Code";
            ItemJnlLine2."Dimension Set ID" := ItemChargePurchLine."Dimension Set ID";
            ItemJnlLine2."Gen. Prod. Posting Group" := ItemChargePurchLine."Gen. Prod. Posting Group";

            OnPostItemChargePerOrderOnAfterCopyToItemJnlLine(
              ItemJnlLine2, ItemChargePurchLine, GLSetup, QtyToInvoice, TempItemChargeAssgntPurch);
        end;

        IsHandled := false;
        OnBeforeTempTrackingSpecificationChargeAssmt(TempTrackingSpecificationInv, IsHandled);

        if not IsHandled then begin
            with TempTrackingSpecificationChargeAssmt do begin
                Reset;
                SetRange("Source Type", DATABASE::"Purchase Line");
                SetRange("Source ID", TempItemChargeAssgntPurch."Applies-to Doc. No.");
                SetRange("Source Ref. No.", TempItemChargeAssgntPurch."Applies-to Doc. Line No.");
                if IsEmpty then
                    RunItemJnlPostLine(ItemJnlLine2)
                else begin
                    FindSet;
                    NonDistrItemJnlLine := ItemJnlLine2;
                    OriginalAmt := NonDistrItemJnlLine.Amount;
                    OriginalAmtACY := NonDistrItemJnlLine."Amount (ACY)";
                    OriginalDiscountAmt := NonDistrItemJnlLine."Discount Amount";
                    OriginalQty := NonDistrItemJnlLine."Quantity (Base)";
                    if ("Quantity (Base)" / OriginalQty) > 0 then
                        SignFactor := 1
                    else
                        SignFactor := -1;
                    repeat
                        Factor := "Quantity (Base)" / OriginalQty * SignFactor;
                        if Abs("Quantity (Base)") < Abs(NonDistrItemJnlLine."Quantity (Base)") then begin
                            ItemJnlLine2."Quantity (Base)" := "Quantity (Base)";
                            ItemJnlLine2."Invoiced Qty. (Base)" := ItemJnlLine2."Quantity (Base)";

                            PreciseTotalChargeAmt += OriginalAmt * Factor;
                            PreciseTotalChargeAmtACY += OriginalAmtACY * Factor;

                            ItemJnlLine2.Amount := PreciseTotalChargeAmt - RoundedPrevTotalChargeAmt;
                            ItemJnlLine2."Amount (ACY)" := PreciseTotalChargeAmtACY - RoundedPrevTotalChargeAmtACY;

                            RoundedPrevTotalChargeAmt += Round(ItemJnlLine2.Amount, GLSetup."Amount Rounding Precision");
                            RoundedPrevTotalChargeAmtACY += Round(ItemJnlLine2."Amount (ACY)", Currency."Amount Rounding Precision");

                            ItemJnlLine2."Unit Cost (ACY)" :=
                            Round(ItemJnlLine2.Amount / ItemJnlLine2."Invoiced Qty. (Base)",
                                Currency."Unit-Amount Rounding Precision") * SignFactor;
                            ItemJnlLine2."Unit Cost" :=
                            Round(ItemJnlLine2.Amount / ItemJnlLine2."Invoiced Qty. (Base)",
                                GLSetup."Unit-Amount Rounding Precision") * SignFactor;
                            ItemJnlLine2."Discount Amount" :=
                            Round(OriginalDiscountAmt * Factor, GLSetup."Amount Rounding Precision");
                            ItemJnlLine2."Item Shpt. Entry No." := "Item Ledger Entry No.";
                            ItemJnlLine2."Applies-to Entry" := "Item Ledger Entry No.";
                            ItemJnlLine2.CopyTrackingFromSpec(TempTrackingSpecificationChargeAssmt);
                            RunItemJnlPostLine(ItemJnlLine2);
                            ItemJnlLine2."Location Code" := NonDistrItemJnlLine."Location Code";
                            NonDistrItemJnlLine."Quantity (Base)" -= "Quantity (Base)";
                            NonDistrItemJnlLine.Amount -= (ItemJnlLine2.Amount * SignFactor);
                            NonDistrItemJnlLine."Amount (ACY)" -= (ItemJnlLine2."Amount (ACY)" * SignFactor);
                            NonDistrItemJnlLine."Discount Amount" -= (ItemJnlLine2."Discount Amount" * SignFactor);
                        end else begin
                            NonDistrItemJnlLine."Quantity (Base)" := "Quantity (Base)";
                            NonDistrItemJnlLine."Invoiced Qty. (Base)" := "Quantity (Base)";
                            NonDistrItemJnlLine."Unit Cost" :=
                            Round(NonDistrItemJnlLine.Amount / NonDistrItemJnlLine."Invoiced Qty. (Base)",
                                GLSetup."Unit-Amount Rounding Precision") * SignFactor;
                            NonDistrItemJnlLine."Unit Cost (ACY)" :=
                            Round(NonDistrItemJnlLine.Amount / NonDistrItemJnlLine."Invoiced Qty. (Base)",
                                Currency."Unit-Amount Rounding Precision") * SignFactor;
                            NonDistrItemJnlLine."Item Shpt. Entry No." := "Item Ledger Entry No.";
                            NonDistrItemJnlLine."Applies-to Entry" := "Item Ledger Entry No.";
                            NonDistrItemJnlLine.CopyTrackingFromSpec(TempTrackingSpecificationChargeAssmt);
                            RunItemJnlPostLine(NonDistrItemJnlLine);
                            NonDistrItemJnlLine."Location Code" := ItemJnlLine2."Location Code";
                        end;
                    until Next() = 0;
                end;
            end;
        end;
    end;
    
    
Event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTempTrackingSpecificationChargeAssmt(var TempTrackingSpecificationInv: Record "Tracking Specification"; IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
