### ISSUE TITLE
[Event request] codeunit 408 DimensionManagement procedure GetDefaultDimID

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#10973]
Hi,

we need additional parameter on event OnGetDefaultDimIDOnBeforeTempDimSetEntryInsert , SourceCode.:
![image](https://user-images.githubusercontent.com/53824412/107215723-facf3480-6a0b-11eb-96d5-35810c594d37.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
