### ISSUE TITLE
[Event Request] Codeunit 90 Purchase Post - OnBeforeMakeInventoryAdjustment

### ISSUE THREAD

**Issue by maw-notora** [microsoft/ALAppExtensions#10978]
In order for our code to function in BC15 and forward, we need a specific event-publisher in codeunit 80 and 90 that is able to pass the right instance of the sales/purchase header as well as the right instance of the codeunit "Gen. Jnl.-Post Line". 

In codeunit 90, at this spot:
![image](https://user-images.githubusercontent.com/78422825/107216858-a6c54f80-6a0d-11eb-999c-e1e908e454dc.png)

Please add the publisher event :
![image](https://user-images.githubusercontent.com/78422825/107216935-c197c400-6a0d-11eb-8a84-84843538c6b4.png)

We have tried using other events, but no other event-publishers supply the needed instances of the variables Sales-/Purchase Header and the GenJnlPostLine Codeunit.

I have created a seperate issue for the event-request for Codeunit 80. Let me know if you have any inquiries.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
