### ISSUE TITLE
[Parameter Request] Need add event to Codeunit "Purch.-Post" function PostItemJnlLineTracking

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10982]
Add please one extra parameter to the event OnBeforePostResourceLine

    local procedure PostResourceLine(PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePostResourceLine(PurchaseHeader, PurchaseLine, IsHandled, TempDropShptPostBuffer);
        if not IsHandled then
            PostResJnlLine(PurchaseHeader, PurchaseLine);
    end;
    
Event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostResourceLine(PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean; var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer")
    begin
    end;

**Comment by StanPesotskiy** [comment]
Requested parameter TempDropShptPostBuffer does not exist inside the PostResourceLine.

**Comment by AlexanderYakunin** [comment]
Closing, please create new request with consistent information about required event.
