### ISSUE TITLE
[Event Request] Codeunit 7301 - Whse. Jnl.-Register Line - OnInsertToBinContentOnBeforeGetBin

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#10986]
hi, would it be possible to get an event OnInsertToBinContentOnBeforeGetBin in codeunit 7301, procedure InsertToBinContent, like this : 
![image](https://user-images.githubusercontent.com/73548802/107238609-560f2000-6a28-11eb-95ac-d54799f4880b.png)

```
local procedure InsertToBinContent(WhseEntry: Record "Warehouse Entry")
    var
        BinContent: Record "Bin Content";
        WhseIntegrationMgt: Codeunit "Whse. Integration Management";
        IsHandled : Boolean;
    begin
        OnBeforeInsertToBinContent(WhseEntry);
        with WhseEntry do begin
            OnInsertToBinContentOnBeforeGetBin(WhseEntry,IsHandled);
            if not IsHandled then
                GetBin("Location Code", "Bin Code");
            BinContent.Init();
```

 ```
   [IntegrationEvent(false, false)]
    local procedure OnInitWhseEntryCopyFromWhseJnlLine(var WarehouseEntry: Record "Warehouse Entry" ; var IsHandled : Boolean)
    begin
    end; 
```
?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
