### ISSUE TITLE
[Parameter Request] Need add event to Codeunit "Purch.-Post" function PostItemLine

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#10981]
Add please one extra parameter to the event OnAfterPostItemLine

    local procedure PostItemLine(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer" temporary)
    var
        DummyTrackingSpecification: Record "Tracking Specification";
    begin
        OnBeforePostItemLine(PurchHeader, PurchLine, PurchRcptHeader, RemQtyToBeInvoiced);
        ItemLedgShptEntryNo := 0;
        with PurchHeader do begin
            if RemQtyToBeInvoiced <> 0 then
                ItemLedgShptEntryNo :=
                  PostItemJnlLine(
                    PurchHeader, PurchLine,
                    RemQtyToBeInvoiced, RemQtyToBeInvoicedBase,
                    RemQtyToBeInvoiced, RemQtyToBeInvoicedBase,
                    0, '', DummyTrackingSpecification);
            if IsCreditDocType then begin
                if Abs(PurchLine."Return Qty. to Ship") > Abs(RemQtyToBeInvoiced) then
                    ItemLedgShptEntryNo :=
                      PostItemJnlLine(
                        PurchHeader, PurchLine,
                        PurchLine."Return Qty. to Ship" - RemQtyToBeInvoiced,
                        PurchLine."Return Qty. to Ship (Base)" - RemQtyToBeInvoicedBase,
                        0, 0, 0, '', DummyTrackingSpecification);
            end else begin
                if Abs(PurchLine."Qty. to Receive") > Abs(RemQtyToBeInvoiced) then
                    ItemLedgShptEntryNo :=
                      PostItemJnlLine(
                        PurchHeader, PurchLine,
                        PurchLine."Qty. to Receive" - RemQtyToBeInvoiced,
                        PurchLine."Qty. to Receive (Base)" - RemQtyToBeInvoicedBase,
                        0, 0, 0, '', DummyTrackingSpecification);
                ProcessAssocItemJnlLine(PurchHeader, PurchLine, TempDropShptPostBuffer);
            end;

            OnAfterPostItemLine(PurchLine, SuppressCommit, PurchHeader, RemQtyToBeInvoiced, RemQtyToBeInvoicedBase, TempDropShptPostBuffer);
        end;
    end;
    
Event:

    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterPostItemLine(PurchaseLine: Record "Purchase Line"; CommitIsSupressed: Boolean; PurchaseHeader: Record "Purchase Header"; RemQtyToBeInvoiced: Decimal; RemQtyToBeInvoicedBase: Decimal; var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
