### ISSUE TITLE
codeunit 5632 "FA Jnl.-Post Line"

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#10983]
You forgot to replace the "Get" with the function "GetPostingGroup".  
![image](https://user-images.githubusercontent.com/45654195/107223926-11c75400-6a17-11eb-8bca-c2742e02fd47.png)

**Comment by StanPesotskiy** [comment]
GitHub issue #6254

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
