### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnUpdateVATOnLinesOnBeforeProcessPurchLines

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10998]
Hello. In Table 39 Purchase Line, in procedure UpdateVATOnline, I would like to use the event publisher OnUpdateVATOnLinesOnBeforeProcessPurchLines(), but it misses a parameter for my use : QtyType. Is it possible to add it ? Like this : 

        IsHandled := false;
        OnUpdateVATOnLinesOnBeforeProcessPurchLines(Rec, xRec, PurchHeader, VATAmountLine, TempVATAmountLineRemainder, LineWasModified, QtyType, IsHandled);
        if IsHandled then
            exit(LineWasModified);
 
With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnUpdateVATOnLinesOnBeforeProcessPurchLines(
        var PurchaseLine: Record "Purchase Line";
        xPurchaseLine: Record "Purchase Line"; 
        var PurchHeader: Record "Purchase Header"; 
        var VATAmountLine: Record "VAT Amount Line"; 
        var TempVATAmountLineRemainder: Record "VAT Amount Line" temporary; 
        QtyType: Option General,Invoicing,Shipping;
        var LineWasModified: Boolean; 
        var IsHandled: Boolean)
    begin
    end;

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
