### ISSUE TITLE
[Event Request] codeunit 394 "FinChrgMemo-Make" - OnBeforeFinChargeMemoLineInsert in MakeLines2 for changing grace period changes

### ISSUE THREAD

**Issue by Manoj-MG-MS** [microsoft/ALAppExtensions#10995]
Can we have OnBeforeFinChargeMemoLinesInsert trigger to make changes to the fields.

 local procedure MakeLines2(CurrencyCode: Code[10]; Checking: Boolean)
    begin
        with Cust do
            if CustLedgEntry.Find('-') then
                repeat
                    Clear(FinChrgMemoLine);
                    NextLineNo := GetLastLineNo(FinChrgMemoHeader."No.") + 10000;
                    FinChrgMemoLine.Init();
                    FinChrgMemoLine."Finance Charge Memo No." := FinChrgMemoHeader."No.";
                    FinChrgMemoLine."Line No." := NextLineNo;
                    FinChrgMemoLine.SetFinChrgMemoHeader(FinChrgMemoHeader);
                    FinChrgMemoLine.Type := FinChrgMemoLine.Type::"Customer Ledger Entry";
                    FinChrgMemoLine.SetCheckingMode(Checking);
                    FinChrgMemoLine.Validate("Entry No.", CustLedgEntry."Entry No.");
                    if CurrencyCode <> '' then begin
                        CustAmountLCY :=
                          CustAmountLCY +
                          CurrExchRate.ExchangeAmtFCYToLCY(
                            FinChrgMemoHeader."Posting Date", CurrencyCode, FinChrgMemoLine.Amount,
                            CurrExchRate.ExchangeRate(
                              FinChrgMemoHeader."Posting Date", CurrencyCode))
                    end else
                        CustAmountLCY := CustAmountLCY + FinChrgMemoLine.Amount;
                    if (CustAmountLCY >= FinChrgTerms."Minimum Amount (LCY)") and
                       (FinChrgMemoHeader."Document Date" > CalcDate(FinChrgTerms."Grace Period", FinChrgMemoLine."Due Date"))
                    then
                        OverDue := true;
                    if FinChrgMemoLine.Amount <> 0 then
                      **New event call here**
                      OnBeforeFinChargeMemoLineInsert(FinChrgMemoLine, Checking);
                        if not Checking then
                            FinChrgMemoLine.Insert

[IntegrationEvent(false, false)]
    local procedure OnBeforeFinChargeMemoLineInsert(var FinanceChargeMemoLine: Record "Finance Charge Memo Line"; Checking: Boolean)
    begin

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
