### ISSUE TITLE
[Event Request] Table 11510 - "Swiss QR-Bill Buffer"- ValidateIBAN

### ISSUE THREAD

**Issue by meckerlen** [microsoft/ALAppExtensions#10992]
Is it possible to add event triggers ( on before, on after... ) into this function on table table 11510 "Swiss QR-Bill Buffer" to be able to change the qr iban before printing it ? ( helps to change IBAN on QR depending on customs setup ) 
Thanks per advance,

>

[IntegrationEvent(false, false)]

    local procedure OnBeforeValidateIBAN(VAR IBAN : code[50])
    begin
    end;

>

[IntegrationEvent(false,` false)]

    local procedure OnAfterValidateIBAN(VAR IBAN : code[50])
    begin
    end;

> 

local procedure ValidateIBAN()

    var
        CompanyInformation: Record "Company Information";
    begin
        OnBeforeValidateIBAN(IBAN);
        CompanyInformation.Get();
        if "IBAN Type" = "IBAN Type"::"QR-IBAN" then begin
            CompanyInformation.TestField("Swiss QR-Bill IBAN");
            IBAN := SwissQRBillMgt.FormatIBAN(CompanyInformation."Swiss QR-Bill IBAN");
        end else begin
            CompanyInformation.TestField(IBAN);
            IBAN := SwissQRBillMgt.FormatIBAN(CompanyInformation.IBAN);
        end;
       OnAfterValidateIBAN(IBAN);
    end;

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.

**Comment by meckerlen** [comment]
better now ?

**Comment by StanPesotskiy** [comment]
Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
