### ISSUE TITLE
[Event Request] Codeunit 5055 CustVendBank-Update - OnAfterVAT

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#10997]
Hi, would it be possible to get an event OnAfterVAT codeunit 5055 "CustVendBank-Update", like this :

```
            Modify;
            if ("VAT Registration No." <> '') and ("VAT Registration No." <> VATRegNo) then
                VATRegistrationLogMgt.LogCustomer(Cust);
            OnAfterVAT(Cont,ContBusRel);
        end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterVAT(var Cont: Record Contact ; var ContBusRel: Record "Contact Business Relation")
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
