### ISSUE TITLE
[Request-for-external] Table 39 "Purchase Line" - UpdatePrepmtAmounts & UpdateBaseAmounts & UpdateDeferralAmounts

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#10996]
Hello. In Table 39 Purchase Line, in procedure UpdateVATOnLines, I would like to use the event publisher OnUpdateVATOnLinesOnBeforeProcessPurchLines(). But by doing this, I need to use three local procedures from my event publisher : UpdatePrepmtAmounts(), UpdateBaseAmounts() and UpdateDeferralAmounts(). Is it possible to pass them in global ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
