### ISSUE TITLE
[Event Modification] Codeunit 5055 CustVendBank-Update - OnAfterUpdateBankAccount

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11001]
Hi, would it be possible to modify the event OnAfterUpdateBankAccount in Codeunit 5055 CustVendBank-Update to insert ContBusRel parameter, like this :
```
            "No. Series" := NoSeries;
            "Our Contact Code" := OurContactCode;
            "Last Date Modified" := Today;
            OnAfterUpdateBankAccount(BankAcc, Cont, ContBusRel);
            Modify;
        end;
    end;
```
    ```
[IntegrationEvent(false, false)]
    local procedure OnAfterUpdateBankAccount(var BankAccount: Record "Bank Account"; Contact: Record Contact; var ContactBusinessRelation: Record "Contact Business Relation")
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
