### ISSUE TITLE
[Event Request] CodeUnit 10821 - Export DEB DTI - AddItems() - OnBeforeAddItem

### ISSUE THREAD

**Issue by i-dhahri** [microsoft/ALAppExtensions#11005]
Hello, would it be possible to have an event "OnBeforeAddItem"  in Codeunit 10821 "Export DEB DTI" , procedure AddItems()  ; we have made specific changes in AddItem() Procedure 
Like this :
 

![image](https://user-images.githubusercontent.com/77328410/107348902-e5b7db80-6ac7-11eb-845f-9b00b7ce32d4.png)

Cordially.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
