### ISSUE TITLE
[Event Modification] Codeunit 5520 Get Unplanned Demand - OnBeforeOpenPlanningWindow

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11006]
Hi, would it be possible to modify the event OnBeforeOpenPlanningWindowin codeunit Codeunit 5520 Get Unplanned Demand  to insert a ProdOrderComp parameter, like this :

![image](https://user-images.githubusercontent.com/76154006/107350944-55c76100-6aca-11eb-8d22-f37141d07a68.png)
```
    trigger OnRun()
    begin
        if IncludeMetDemandForSpecificSalesOrderNo <> '' then
            SetFilterToSpecificSalesOrder();

        DeleteAll();
        SalesLine.SetFilter("Document Type", '%1|%2', SalesLine."Document Type"::Order, SalesLine."Document Type"::"Return Order");
        ProdOrderComp.SetFilter(
            Status, '%1|%2|%3', ProdOrderComp.Status::Planned, ProdOrderComp.Status::"Firm Planned", ProdOrderComp.Status::Released);
        ServLine.SetRange("Document Type", ServLine."Document Type"::Order);
        AsmLine.SetRange("Document Type", AsmLine."Document Type"::Order);
        JobPlanningLine.SetRange(Status, JobPlanningLine.Status::Order);

        RecordCounter := SalesLine.Count + ProdOrderComp.Count + ServLine.Count + JobPlanningLine.Count;
        OnBeforeOpenPlanningWindow(ProdOrderComp, RecordCounter);
        OpenWindow(ProgressMsg, RecordCounter);

```

![image](https://user-images.githubusercontent.com/76154006/107351093-7d1e2e00-6aca-11eb-82ae-813260ade34a.png)
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOpenPlanningWindow(var ProdOrderComp: Record "Prod. Order Component"; var RecordCounter: Integer)
    begin
    end;
```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
