### ISSUE TITLE
[Event Request] Codeunit 9178 "Application Area Mgmt." - OnBeforeGetApplicationAreas

### ISSUE THREAD

**Issue by zulezmaj** [microsoft/ALAppExtensions#11004]
Hi, I would like to ask to add an event to procedure GetApplicationAreas in Codeunit 9178 "Application Area Mgmt." like this, if possible?

![image](https://user-images.githubusercontent.com/40229810/107349457-87d7c380-6ac8-11eb-9ced-169b2f4624ac.png)

![image](https://user-images.githubusercontent.com/40229810/107349526-9d4ced80-6ac8-11eb-8d20-273145f17ec9.png)

Thank you in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
