### ISSUE TITLE
Report 790 - GetLocation and InsertItemJnlLine Visibility

### ISSUE THREAD

**Issue by SCreanor** [Microsoft/ALAppExtensions#1100]
Can the 2 functions below in Report 790 - Calculate Inventory please be changed from their current 'Local' / 'Internal' visibility to those shown below.

`[External] GetLocation(LocationCode : Code[10]) : Boolean`

`[External] InsertItemJnlLine(ItemNo : Code[20];VariantCode2 : Code[10];DimEntryNo2 : Integer;BinCode2 : Code[20];Quantity2 : Decimal;PhysInvQuantity : Decimal)`

**Comment by RomanZanizdra** [comment]
Hi SCreanor. May I ask you a question, how are you going to use these functions in report when they started to be an external, what is the case/scenario?

**Comment by SCreanor** [comment]
As part of an extension we are writing, we need the ability to insert physical inventory journal lines from our extension. By enabling the 2 functions to be external we can use the standard functionality normally used to add a journal line as part of the calculate inventory, to be called from our extension. There are a number of checks, etc. that require the data to be added via the InsertItemJnlLine function and if we attempt to add it manually from outside the table, it requires a lot of re-work that can be avoided simply by marking these functions as external, and the GetLocation needs to be external to set up the correct location for the insertion call.
