### ISSUE TITLE
[Request-for-external] Table 39 "Purchase Line" - GetVATAmountLineOfMaxAmt 

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11016]
Hello. In table 39 "Purchase Line", in procedure CalcVATAmountLines, I would like to skip the whole procedure thanks to the event OnBeforeCalcVATAmountLines, and add my own code in it. I want to call the standard procedure GetVATAmountLineOfMaxAmt but it's a local procedure. Is it possible to pass it in global ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
