### ISSUE TITLE
[Event Request] Codeunit 5520 Get Unplanned Demand - OnBeforeInsertSalesLine 

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11019]
Hi, would it be possible to get an event OnBeforeInsertSalesLine codeunit 5520 , procedure InsertSalesLine, like this :

![image](https://user-images.githubusercontent.com/76154006/107386706-668ccc80-6af4-11eb-8cf9-376fe1ef1b5b.png)

```
    local procedure InsertSalesLine(var UnplannedDemand: Record "Unplanned Demand")
    var
        UnplannedDemand2: Record "Unplanned Demand";
    begin
        with UnplannedDemand do begin
            UnplannedDemand2.Copy(UnplannedDemand);
            InitRecord(
              SalesLine."Line No.", 0, SalesLine."No.", SalesLine.Description, SalesLine."Variant Code", SalesLine."Location Code",
              SalesLine."Bin Code", SalesLine."Unit of Measure Code", SalesLine."Qty. per Unit of Measure",
              DemandQtyBase, SalesLine."Shipment Date");
              OnBeforeInsertSalesLine(UnplannedDemand, SalesLine);
            Reserve := SalesLine.Reserve = SalesLine.Reserve::Always;
            "Special Order" := SalesLine."Special Order";
            "Purchasing Code" := SalesLine."Purchasing Code";
            Insert;
            Copy(UnplannedDemand2);
        end;
    end;

```
![image](https://user-images.githubusercontent.com/76154006/107386572-43fab380-6af4-11eb-8a8e-86a84fc243c2.png)
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertSalesLine( var UnplannedDemand: Record "Unplanned Demand"; var SalesLine: Record "Sales Line")
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
