### ISSUE TITLE
[Event Request] Codeunit 5522 Order Planning Mgt. - OnBeforeGetOrdersToPlan 

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11027]
Hi, would it be possible to get an event OnBeforeGetOrdersToPlan codeunit 5522 , procedure GetOrdersToPlan, like this :

![image](https://user-images.githubusercontent.com/76154006/107484933-64258380-6b83-11eb-80f2-7cb3ede07448.png)

```
    procedure GetOrdersToPlan(var ReqLine: Record "Requisition Line")
    var
        IsHandled: Boolean;
    begin
        PrepareRequisitionRecord(ReqLine);
        IsHandled := false;
        OnBeforeGetOrdersToPlan(TempUnplannedDemand, IsHandled);
        if not IsHandled then
            CODEUNIT.Run(CODEUNIT::"Get Unplanned Demand", TempUnplannedDemand);
        TransformUnplannedDemandToRequisitionLines(ReqLine);
    end;

```

![image](https://user-images.githubusercontent.com/76154006/107484955-6b4c9180-6b83-11eb-9252-d0c4425ec479.png)
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetOrdersToPlan(var UnplannedDemand: Record "Unplanned Demand"; var IsHandled: Boolean)
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
