### ISSUE TITLE
[Event Request] Codeunit 5522 Order Planning Mgt. - OnInsertDemandHeaderOnBeforeLineNoAffectation 

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11029]
Hi, would it be possible to get an event OnInsertDemandHeaderOnBeforeLineNoAffectation codeunit 5522 , procedure InsertDemandHeader, like this :

![image](https://user-images.githubusercontent.com/76154006/107490838-b0c08d00-6b8a-11eb-9977-e909c7a20f11.png)

```
    local procedure InsertDemandHeader(UnplannedDemand: Record "Unplanned Demand"; var ReqLine: Record "Requisition Line")
    var
    IsHandled: Boolean;
    begin
        with ReqLine do begin
            Init;
            "Journal Batch Name" := GetJnlBatchNameForOrderPlanning();
            case UnplannedDemand."Demand Type" of
                UnplannedDemand."Demand Type"::Sales:
                    "Demand Type" := DATABASE::"Sales Line";
                UnplannedDemand."Demand Type"::Production:
                    "Demand Type" := DATABASE::"Prod. Order Component";
                UnplannedDemand."Demand Type"::Service:
                    "Demand Type" := DATABASE::"Service Line";
                UnplannedDemand."Demand Type"::Job:
                    "Demand Type" := DATABASE::"Job Planning Line";
                UnplannedDemand."Demand Type"::Assembly:
                    "Demand Type" := DATABASE::"Assembly Line";
            end;
            "Demand Subtype" := UnplannedDemand."Demand SubType";
            "Demand Order No." := UnplannedDemand."Demand Order No.";
            Status := UnplannedDemand.Status;
            "Demand Date" := UnplannedDemand."Demand Date";
            Description := UnplannedDemand.Description;

            Level := 0;
            "Replenishment System" := "Replenishment System"::" ";
            IsHandled:= false;
            OnInsertDemandHeaderOnBeforeLineNoAffectation(UnplannedDemand, ReqLine, IsHandled);
            if not IsHandled then
            "Line No." := "Line No." + 10000;
            "User ID" := UserId;
            OnInsertDemandHeaderOnBeforeReqLineInsert(UnplannedDemand, ReqLine);
            Insert;
            OnInsertDemandHeaderOnAfterReqLineInsert(UnplannedDemand, ReqLine);
        end;
    end;

```

![image](https://user-images.githubusercontent.com/76154006/107490872-c03fd600-6b8a-11eb-9c41-0d47fb49e812.png)
```
    [IntegrationEvent(false, false)]
    local procedure OnInsertDemandHeaderOnBeforeLineNoAffectation(var UnplannedDemand: Record "Unplanned Demand"; var ReqLine: Record "Requisition Line"; var IsHandled: Boolean)
    begin
    end;

```
Thanks

**Comment by StanPesotskiy** [comment]
You can rollback "Line No." if needed inside the existing event OnInsertDemandHeaderOnBeforeReqLineInsert

**Comment by Herodoteux** [comment]
If we exceed the capacity of the integer when we affect 10000 to "Line No." will we have an error message before entering the event OnInsertDemandHeaderOnBeforeReqLineInsert?

**Comment by StanPesotskiy** [comment]
Subscribe and try it to see where error would occur.

**Comment by Herodoteux** [comment]
The error come when we affect +10000 to "Line No." we still have an error when we use the event OnInsertDemandHeaderOnBeforeReqLineInsert.

**Comment by StanPesotskiy** [comment]
What error do you get?

**Comment by Herodoteux** [comment]
Hi, my problem is that I exceed the capacity of the integer, it because I have a large database.

**Comment by StanPesotskiy** [comment]
I don't get how the requested event would help. 
I see, you skip the "Line No." increment, but then insert is going to fail as the "line no." would be not changed.

**Comment by Herodoteux** [comment]
I reafect +1000 to "Line no." insted of +10000 in my event.

**Comment by StanPesotskiy** [comment]
Can't you do: 
`Line No. -= 9000;`
in the handler OnInsertDemandHeaderOnBeforeReqLineInsert(UnplannedDemand, ReqLine);

**Comment by Herodoteux** [comment]
Ok I try this. Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
