### ISSUE TITLE
[Event Request] codeunit 5611 "Calculate Normal Depreciation"-OnBeforeExit

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11023]
Hi, would it be possible to get an event OnBeforeExit codeunit 5611 "Calculate Normal Depreciation", like this :
```
        if SLPercent > 0 then
            IsHandled:=false;
            OnBeforeExit(IsHandled,FADeprBook,BookValue,DeprBasis,DaysInFiscalYear,NumberOfDays,SLPercent);
            if not IsHandled then begin
                exit((-SLPercent / 100) * (NumberOfDays / DaysInFiscalYear) * DeprBasis);
            end else if IsHandled then
                    exit(Result);

```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeExit(var IsHandled: Boolean;var Result: Decimal;var FADeprBook: Record "FA Depreciation Book";var BookValue: Decimal;var DeprBasis: Decimal;var DaysInFiscalYear: Integer;var NumberOfDays: Integer;var SLPercent: Decimal)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
