### ISSUE TITLE
[Event Request] Codeunit 5520 Get Unplanned Demand - OnBeforeInsertUnplannedDemand

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11020]
Hi, would it be possible to get an event OnBeforeInsertUnplannedDemand codeunit 5520 , procedure InsertUnplannedDemand, like this :
![image](https://user-images.githubusercontent.com/76154006/107393379-06e5ef80-6afb-11eb-9014-0fc494b2e144.png)

```
    local procedure InsertUnplannedDemand(var UnplannedDemand: Record "Unplanned Demand"; DemandType: Enum "Unplanned Demand Type"; DemandSubtype: Integer; DemandOrderNo: Code[20]; DemandStatus: Integer)
    var
    IsHandled: Boolean;
    begin
        with UnplannedDemand do begin
            Init;
            "Demand Type" := DemandType;
            "Demand SubType" := DemandSubtype;
            Validate("Demand Order No.", DemandOrderNo);
            Status := DemandStatus;
            Level := 0;
            OnBeforeInsertUnplannedDemand(UnplannedDemand, IsHandled);
            if not IsHandled then
            Insert;
        end;
    end;

```
![image](https://user-images.githubusercontent.com/76154006/107390628-2a5b6b00-6af8-11eb-91bb-033d6fb7d266.png)
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertUnplannedDemand( var UnplannedDemand: Record "Unplanned Demand"; var IsHandled: Boolean)
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
