### ISSUE TITLE
[Change Request] Page 30 "Item Card" – Procedure CreateItemFromTemplate passed empty Item record (w/o filters)

### ISSUE THREAD

**Issue by Drakonian** [microsoft/ALAppExtensions#11026]
In the **CreateItemFromTemplate** procedure from **"Item Card"** page, the **InsertItemFromTemplate** function is called, but a completely empty local variable is passed. And this means that if the record was previously filtered, then if the templates are active, we **lose these filters.**

I suggest passing a record with filters to the procedure, or adding an additional parameter so that we can absolutely accurately determine the entry point when creating an item with a template.

![image](https://user-images.githubusercontent.com/16802407/107429996-49c0bb00-6b2d-11eb-895f-eb74fdc29c03.png)

**Comment by RomanZanizdra** [comment]
Hi @Drakonian .
Could you be so kind to share the scenario behind your request? For example, you will be able to set filters on the "Item" variable before call of InsertItemFromTemplate(), what will you do with them?

**Comment by RomanZanizdra** [comment]
@Drakonian , and one more question. Even when you filter item list, then open the card (or create new directly from the list), and try to create new item, there are no filters on the Rec. From where do you plan to get them?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
