### ISSUE TITLE
[Event Request]: Table 38 in function FindPostedDocumentWithSameExternalDocNo

### ISSUE THREAD

**Issue by dojab** [microsoft/ALAppExtensions#1103]
Hi,
we have to implement additional checks to avoid purchase documents with the same external document numbers. For this requirement a new event "OnBeforeFindPostedDocumentWithSameExternalDocNo" in OnValidate of  "FindPostedDocumentWithSameExternalDocNo" would be helpful.
![image](https://user-images.githubusercontent.com/47024592/52399418-795f0780-2abc-11e9-89f9-298ddd2e2c5e.png)

Alternatively the following event is also possible:
![image](https://user-images.githubusercontent.com/47024592/52399838-b5469c80-2abd-11e9-8593-a26933015310.png)

Thanks

**Comment by AlexanderYakunin** [comment]
This is not needed anymore, we support disabling this notification in BaseApp

**Comment by dojab** [comment]
I know this function. We want to leave the notification activated and run our own checks in our vertical solution. Therefore we need this event, please reopen
