### ISSUE TITLE
[Event Request] Codeunit 5522 Order Planning Mgt. - OnBeforeExitCalcATPQty 

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11033]
Hi, would it be possible to get an event OnBeforeExitCalcATPQty codeunit 5522 , procedure CalcATPQty, like this :

![image](https://user-images.githubusercontent.com/76154006/107515873-eaee5680-6bab-11eb-9427-54ca08e5b9d7.png)

```
    procedure CalcATPQty(ItemNo: Text[250]; VariantFilter: Text[250]; LocationFilter: Text[250]; DemandDate: Date): Decimal
    var
        Item: Record Item;
        AvailableToPromise: Codeunit "Available to Promise";
        GrossRequirement: Decimal;
        ScheduledRcpt: Decimal;
        ODF: DateFormula;
        Result: Decimal;
        IsHandled: Boolean;
    begin
        if ItemNo = '' then
            exit(0);

        Item.Get(ItemNo);
        Item.SetRange("Variant Filter", VariantFilter);
        Item.SetRange("Location Filter", LocationFilter);
        Item.SetRange("Date Filter", 0D, DemandDate);
        Item.SetRange("Drop Shipment Filter", false);
        if DemandDate = 0D then
            DemandDate := WorkDate;
        Evaluate(ODF, '<0D>');

        OnBeforeExitCalcATPQty(Item);
        exit(AvailableToPromise.QtyAvailabletoPromise(Item, GrossRequirement, ScheduledRcpt, DemandDate, 0, ODF))
    end;

```
![image](https://user-images.githubusercontent.com/76154006/107515915-f80b4580-6bab-11eb-807a-77d97c78c1dd.png)
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeExitCalcATPQty(var Item: Record Item)
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
