### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnBeforeGetDefaultBin

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11031]
Hello. In table 39 Purchase Line, in procedure GetDefaultBin(), I would like to add my code in the event publisher OnBeforeGetDefaultBin. But it misses the parameter xRec for my use. Is it possible to add it ? Like this : 

    local procedure GetDefaultBin()
    var
        WMSManagement: Codeunit "WMS Management";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetDefaultBin(Rec, xRec, IsHandled);
        if IsHandled then
            exit;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetDefaultBin(var PurchaseLine: Record "Purchase Line"; xPurchaseLine : record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
