### ISSUE TITLE
[Event Request] CodeUnit 5349 Auto Create Sales Orders - OnCreateNAVSalesOrderOnBeforeFindset

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#11047]
Can you guys please add this event? Thank you very much :)

![image](https://user-images.githubusercontent.com/35260264/107630503-e84f3800-6c63-11eb-9e89-b29b00e6b3f8.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
