### ISSUE TITLE
[Event Request] CodeUnit 87 Blanket Sales Order to Order - OnBlanketSalesOrderToOrderOnAfterSetFilters

### ISSUE THREAD

**Issue by acjdekorte** [microsoft/ALAppExtensions#11043]
We would like to request on event to set some additional filters on BlanketOrderSalesLine before its FindSet. 

![image](https://user-images.githubusercontent.com/36184654/107623796-2c3d3f80-6c5a-11eb-836b-404d164f3ef8.png)

 A simular kind of event is present in Copy Document Mgt. Codeunit

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
