### ISSUE TITLE
[Event Request] CodeUnit 87 Blanket Sales Order to Order - OnBeforeUpdateSalesOrderLine(BlanketOrderLine, var SalesOrderLine)

### ISSUE THREAD

**Issue by acjdekorte** [microsoft/ALAppExtensions#11044]
We would like to request the following event in order to set some suspend function to avoid some data to be modified in the validations, which follow.

![image](https://user-images.githubusercontent.com/36184654/107624492-43306180-6c5b-11eb-919c-b485608c2386.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
