### ISSUE TITLE
[Event Request] Codeunit 5944 "SignServContractDoc" CheckServContractNonZeroAmounts

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#11049]
We would like to request a handled pattern for function CheckServContractNonZeroAmounts in codeunit 5944 - SignServContractDoc.

    local procedure CheckServContractNonZeroAmounts(ServContractHeader: Record "Service Contract Header")
    begin
        // START ->
        OnBeforeCheckServContractNonZeroAmounts(ServContractHeader, VAR IsHandled);
        if IsHandled then
            exit;
        // <- END
        
       if ServContractHeader.IsInvoicePeriodInTimeSegment() then begin
            if ServContractHeader."Annual Amount" = 0 then
                Error(Text020);
            ServContractHeader.TestField("Amount per Period");
        end;
    end;

Many thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
