### ISSUE TITLE
[Event Request] Page 1171 "User Task Card" and 1170 "User Task List"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#11041]
We need a new event in procedure RunReportOrPageLink with isHandled to execute our own Task Item in Pages 1170 "User Task List" and 1171 "User Task Card":

local procedure RunReportOrPageLink()
    var
        AllObjWithCaption: Record AllObjWithCaption;
    begin
        //++++++++++++++++++++++++++++++++++++
        OnBeforeExecuteUserTaskItem(var Rec;isHandled: Boolean);
        if isHandled then
          exit;
        //-------------------------------------------
        if ("Object Type" = 0) or ("Object ID" = 0) then
            exit;
        if "Object Type" = AllObjWithCaption."Object Type"::Page then
            PAGE.Run("Object ID")
        else
            REPORT.Run("Object ID");
    end;

In best conditions we would like to execute a specific card page with a record assigned to the user task. So an additional field "Assigned to RecordID" would be helpful, but we can add that in our own extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
