### ISSUE TITLE
[Event Request] CodeUnit 87 Blanket Sales Order to Order - OnAfterInsertAllSalesLines

### ISSUE THREAD

**Issue by acjdekorte** [microsoft/ALAppExtensions#11040]
Hi,

We would like to request to change the parameter SalesOrderHeader of OnAfterInsertAllSalesOrderLines of CodeUnit 87 to be passed by reference instead of by value. We would like to use this event to do update/modify a field on the Sales Header. Since the Sales Header is modified later in standard code, we end up with record is already updated error.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
