### ISSUE TITLE
Enum is Required for Field Type in Table 952

### ISSUE THREAD

**Issue by raawasthi** [microsoft/ALAppExtensions#11042]
Please create an enum for Field No. 4 Type . It is required for one of our customisation.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
