### ISSUE TITLE
[Event Request] CodeUnit 87 Blanket Sales Order to Order - OnAfterValidateShipmentDate

### ISSUE THREAD

**Issue by acjdekorte** [microsoft/ALAppExtensions#11045]
We would like to request to OnAfterValidateShipmentDate(BlanketOrderLine, var SalesOrderLine) event in Codeunit 87 Blanket Sales Order to Order. We need to perform some additional actions on our own custom fields based on the new information of the shipmentdate. 

![image](https://user-images.githubusercontent.com/36184654/107625323-73c4cb00-6c5c-11eb-84a1-142ad4803adb.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
