### ISSUE TITLE
[Event Request] Application “Tests-Misc”, Codeunit 134590 "Mandatory Fields Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#11056]
[Event Request]Application “Tests-Misc”, 134590 "Mandatory Fields Tests"

Could you please insert the OnTestInitialize Event at the beginning of the test procedure MandatoryFieldsOnSalesDocuments:
![pic1](https://user-images.githubusercontent.com/45795262/107659637-9fa97600-6c87-11eb-853d-28f27dade769.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
