### ISSUE TITLE
Page 6510 "Item Tracking Lines" – Protected procedure SynchronizeWarehouseItemTracking()

### ISSUE THREAD

**Issue by abhishekv290691** [microsoft/ALAppExtensions#11059]
Could you please change the scope of the function  **SynchronizeWarehouseItemTracking()** in page 6510 "**Item Tracking Lines**" to **protected**.

![image](https://user-images.githubusercontent.com/49511747/107726294-93332500-6d3c-11eb-873a-343e9c788ad3.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
