### ISSUE TITLE
[Request-for-external] Table 27 "Item"  - SetLastDateTimeModified

### ISSUE THREAD

**Issue by SteinleMossGaewers** [microsoft/ALAppExtensions#11054]
Can you change procedure SetLastDateTimeModified in table 27 "Item" to global?

**Comment by AlexanderYakunin** [comment]
Why? You can use system fields below any time:

![image](https://user-images.githubusercontent.com/31849120/107748019-75a89000-6d29-11eb-9b93-370e5fab6461.png)

**Comment by SteinleMossGaewers** [comment]
There appear to be two separate fields:
![grafik](https://user-images.githubusercontent.com/71119587/107752815-881dcc00-6d1f-11eb-8a86-db49b3074f76.png)

Some functions in the Base Application are using the Field "Last DateTime Modified" (E.g. XmlPort 5801) which is why the access to the function SetLastDateTimeModified would be great.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
