### ISSUE TITLE
[Event Request] Application “Tests-User”, Codeunit 134202 "Document Approval - Users"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#11055]
[Event Request] Application “Tests-User”, Codeunit 134202 "Document Approval - Users"

Could you please insert the OnTestInitialize Event at the beginning the following test procedure:
-	ApproveRequestForPurchBlanketOrder
-	DelegateRequestForPurchBlanketOrder
-	DelegateRequestForPurchCrMemo
-	DelegateRequestForPurchInvoice
-	DelegateRequestForPurchOrder
-	DelegateRequestForPurchQuote
-	DelegateRequestForPurchReturnOrder
-	ModifyApprovedSalesQuote
-	ApproveRequestWithCommentForSalesQuoteAndMakeOrder

![pic1](https://user-images.githubusercontent.com/45795262/107659315-50634580-6c87-11eb-9b75-79bacd1057c6.png)
![pic2](https://user-images.githubusercontent.com/45795262/107659336-5527f980-6c87-11eb-8b27-3433bce30d12.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
