### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 136142 "Service Warehouse Integration"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#11058]
[Event Request]Application “Tests-ERM”, 136142 "Service Warehouse Integration"

Could you please insert the OnTestInitialize Event at the beginning each test procedure:
![pic1](https://user-images.githubusercontent.com/45795262/107662280-6d4d4800-6c8a-11eb-8b81-017b4aa45157.png)
![pic2](https://user-images.githubusercontent.com/45795262/107662301-70e0cf00-6c8a-11eb-8cd7-760ad79e8778.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
