### ISSUE TITLE
[Event Request] Codeunit 22 Procedure InsertItemLedgEntry

### ISSUE THREAD

**Issue by LdrAms** [microsoft/ALAppExtensions#11053]
We would like to request a new event to bypass the Error(Text018... at procedure InsertItemLedgEntry. Something like this:

```
ItemLedgEntry.VerifyOnInventory;
OnInsertItemLedgEntryOnBeforeQtyCheck(ItemJnlLine, IsHandled);
if not IsHandled then
    if not (("Document Type" in ["Document Type"::"Purchase Return Shipment", "Document Type"::"Purchase Receipt"]) and
                        ("Job No." <> ''))
                then
                    if (ItemLedgEntry.Quantity < 0) and
                       (ItemTrackingCode."SN Specific Tracking" or ItemTrackingCode."Lot Specific Tracking")
                    then
                        Error(Text018, "Serial No.", "Lot No.", "Item No.", "Variant Code");

```
Thank you,
-- Alejandro --

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
