### ISSUE TITLE
Table 10751 "SII Setup"

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/ALAppExtensions#11052]
In table 10751 of the tin location I need an event "OnValidateEnabled"

field(2; Enabled; Boolean)
        {
            Caption = 'Enabled';

            trigger OnValidate()
            begin
                //EventRequestStart
                OnValidateEnabled(Rec,IsHandled);
                if is handled then
                  exit;
                //EventRequestEnd
                if Enabled and ("Certificate Code" = '') then
                    Error(CannotEnableWithoutCertificateErr);
            end;
        }

[IntegrationEvent(false, false)]
local procedure OnValidateEnabled(var SIISetup: Record "SII Setup"; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
