### ISSUE TITLE
[Event Request] Application “Tests-Misc”, Codeunit 135000 "Error Message Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#11057]
[Event Request]Application “Tests-Misc”, 135000 "Error Message Tests"

Could you please insert the OnTestInitialize Event at the beginning of procedure Initialize:
![pic1](https://user-images.githubusercontent.com/45795262/107661474-98836780-6c89-11eb-93e1-4425f24852c0.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
