### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnValidateBuyFromVendorNoOnAfterUpdateBuyFromCont

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11065]
Hello. In table 38 Purchase Header, in field 2, in the event publisher OnValidateBuyFromVendorNoOnAfterUpdateBuyFromCont, I need to manipulate xRec in the event subscriber, but it's not a parameter of this event. Is it possible to add it ? Like this :

OnValidateBuyFromVendorNoOnAfterUpdateBuyFromCont(Rec, xRec);

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnValidateBuyFromVendorNoOnAfterUpdateBuyFromCont(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader : record "Purchase Header")
    begin
    end;

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
