### ISSUE TITLE
[Event Request] Table 5741 - OnAfterGetDefaultBin

### ISSUE THREAD

**Issue by MS-IbrahimShehade** [microsoft/ALAppExtensions#11069]
Please add a new integration event OnAfterGetDefaultFromBin(Rec,FromLocation); in Table 5741 & OnAfterGetDefaultToBin(Rec,ToLocation);:

trigger GetDefaultBin(FromLocationCode: Code[10]; ToLocationCode: Code[10])
BEGIN
IF (FromLocationCode <> '') AND ("Item No." <> '') THEN BEGIN
  GetLocation(FromLocationCode);
  IF Location."Bin Mandatory" AND NOT Location."Directed Put-away and Pick" THEN BEGIN
    WMSManagement.GetDefaultBin("Item No.","Variant Code",FromLocationCode,"Transfer-from Bin Code");
    HandleDedicatedBin(FALSE);
  END;
  **_OnAfterGetDefaultFromBin(Rec,FromLocation);_**
END;

IF (ToLocationCode <> '') AND ("Item No." <> '') THEN BEGIN
  GetLocation(ToLocationCode);
  IF Location."Bin Mandatory" AND NOT Location."Directed Put-away and Pick" THEN
    WMSManagement.GetDefaultBin("Item No.","Variant Code",ToLocationCode,"Transfer-To Bin Code");
  **_OnAfterGetDefaultToBin(Rec,ToLocation);_**
END;
END;

_**[IntegrationEvent(false, false)]**_
_**local procedure OnAfterGetDefaultFromBin(var TransferLine: Record "Transfer Line";var LocationCode: Code[10])**_
_**begin**_
_**end;**_

_**[IntegrationEvent(false, false)]**_
_**local procedure OnAfterGetDefaultToBin(var TransferLine: Record "Transfer Line";var LocationCode: Code[10])**_
_**begin**_
_**end;**_

**Comment by MS-IbrahimShehade** [comment]
Hello, 
Hope you doing well,

Any update on this request, please,

Thank you,
Best Regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
