### ISSUE TITLE
Code analysis incorrect work for on-premise BC

### ISSUE THREAD

**Issue by ABaludin** [Microsoft/ALAppExtensions#1106]
Tested on runtime 2.3 BC on-premise RU localization.
If I'm activating Enable Code Analysis mark in VS Code - it behave itself like for cloud version.
1. "target": "Internal" - throws an exception (prohibited to use)
2. "features": ["TranslationFile"] - become mandatory to use

So I have to disable Code Analysis to set Internal target.

**Comment by crisnicolas** [comment]
Hi,

There are 4 different code analyzers.
When you enable code analysis, you enable the 4 of them.
One of the analyzers checks for AppSource requirements. Another checks cloud version requirements. 

You can enable the code analyzer, but not all 4 of them. You can choose which one to enable.

It is explained here:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-using-code-analysis-tool
