### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnValidatePayToVendorNoOnBeforeGetPayToVend

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11068]
Hello. In table 38 Purchase Header, in field 4 "Pay-to Vendor No.", in trigger OnValidate, we would like to do a test with some parameters in the event publisher OnValidatePayToVendorNoOnBeforeGetPayToVend, and exit the trigger if the test is not passed. To do so, we would need new parameters in this event, and a IsHandled flag. Like this : 

    OnValidatePayToVendorNoOnBeforeGetPayToVend(Rec, xRec, Confirmed, IsHandled);
    if IsHandled then
        exit;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnValidatePayToVendorNoOnBeforeGetPayToVend(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader : record "Purchase Header"; Confirmed : boolean ; var IsHandled : boolean)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
