### ISSUE TITLE
[Event Request] CodeUnit 7302 - WMS Management - OnBeforeCheckWhseJnlLine 

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11064]
Hi, would it be possible to get an event OnBeforeCheckWhseJnlLine codeunit 7302, procedure CheckWhseJnlLine, like this :

![image](https://user-images.githubusercontent.com/76154006/107755411-0cbe1980-6d23-11eb-9c6e-401e50d336f5.png)

```
     procedure CheckWhseJnlLine(var WhseJnlLine: Record "Warehouse Journal Line"; SourceJnl: Option " ",ItemJnl,OutputJnl,ConsumpJnl,WhseJnl; DecreaseQtyBase: Decimal; ToTransfer: Boolean)
    var
        BinContent: Record "Bin Content";
        ItemTrackingCode: Record "Item Tracking Code";
        QtyAbsBase: Decimal;
        IsHandled: Boolean;
    begin
        GetItem(WhseJnlLine."Item No.");
        IsHandled:=false;
        OnBeforeCheckWhseJnlLine(Item, WhseJnlLine, IsHandled);
        if IsHandled then
        exit;
        with WhseJnlLine do begin
            TestField("Location Code");
            GetLocation("Location Code");

            if SourceJnl = SourceJnl::WhseJnl then
                CheckAdjBinCode(WhseJnlLine);

```
![image](https://user-images.githubusercontent.com/76154006/107755580-4db62e00-6d23-11eb-8a87-a9cb35074480.png)

```
       [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckWhseJnlLine(var Item: Record Item; var WhseJnlLine: Record "Warehouse Journal Line"; var IsHandled: Boolean)
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
