### ISSUE TITLE
[Event Request] codeunit 6620 "Copy Document Mgt."-OnBeforeInvoice

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11062]
Hi, would it be possible to get an event OnBeforeInvoice codeunit 6620 "Copy Document Mgt.", like this :
```
    var
        OldSalesHeader: Record "Sales Header";
        IsHandled: Boolean;
```
```
            IsHandled:=false;
            OnBeforeInvoice(IsHandled);
            if not IsHandled then begin
                Invoice := false;
                Ship := false;
            end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInvoice(var IsHandled: Boolean)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
