### ISSUE TITLE
[Event Request] CodeUnit 7302 - WMS Management - OnBeforeGetDefaultDirectedPutawayAndPickLocation 

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11076]
Hi, would it be possible to get an event OnBeforeGetDefaultDirectedPutawayAndPickLocation codeunit 7302, procedure GetDefaultDirectedPutawayAndPickLocation, like this :

![image](https://user-images.githubusercontent.com/76154006/107795645-38f48d00-6d59-11eb-9dc1-0e80374cec7b.png)

```
    procedure GetDefaultDirectedPutawayAndPickLocation(): Code[10]
    var
        Location: Record Location;
        IsHAndled: Boolean;
    begin
        if Location.Get(GetDefaultLocation) then begin
            IsHandled := false;
            OnBeforeGetDefaultDirectedPutawayAndPickLocation(Location, IsHandled);
            if IsHandled then
                exit(Location.Code);
            if Location."Directed Put-away and Pick" then
                exit(Location.Code);
        end;
        Error(DefaultLocationNotDirectedPutawayPickErr, UserId);
    end;

```

![image](https://user-images.githubusercontent.com/76154006/107795710-4e69b700-6d59-11eb-8782-429e2489fed3.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetDefaultDirectedPutawayAndPickLocation(var Location: Record Location; var IsHandled: Boolean)
    begin
    end;

```

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
