### ISSUE TITLE
[Event Request] Table 37 Sales Line: add OnBeforeCheckPrepmtAmtInvoice event

### ISSUE THREAD

**Issue by Nyryus** [microsoft/ALAppExtensions#11073]
Hello, please consider adding the following event to table 37 Sales Line OnBeforeCheckPrepmtAmtInvoice
```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckPrepmtAmtInvoice(SalesLine: Record "Sales Line"; var IsHandled: Boolean)
begin
end;
```

and raise it inside the trigger "VAT Prod. Posting Group"

```
        field(90; "VAT Prod. Posting Group"; Code[20])
        {
            Caption = 'VAT Prod. Posting Group';
            TableRelation = "VAT Product Posting Group";

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                TestStatusOpen();
				
                IsHandled := false;
                OnBeforeCheckPrepmtAmtInvoice(Rec, IsHandled);
                if ("Prepmt. Amt. Inv." <> 0) and (not IsHandled) then
                    Error(CannotChangeVATGroupWithPrepmInvErr);
                VATPostingSetup.Get("VAT Bus. Posting Group", "VAT Prod. Posting Group");
                "VAT Difference" := 0;

```

The control is also present in the Table 39 Purchase Line, the event could be also good to have also there.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
