### ISSUE TITLE
[Event Request] report 15000001 "Suggest Remittance Payments" - OnAfterOpenPage

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#11078]
Hi. Has the event request in issue #9757 been forgotten?

Still nothing in BC 17.4:

![image](https://user-images.githubusercontent.com/46031720/107857900-82b0a680-6e31-11eb-9c52-b62bce12765c.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
