### ISSUE TITLE
[Access Request] page 402 "Sales Order Statistics" - TotalAmount1

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#11079]
Hi. Has issue #10347 been forgotten? Variabel has not been changed to protected var in 17.4.
It has been changed in the "Sales Statistics" page a few CUs ago.

**Comment by AlexanderYakunin** [comment]
No, it is not forgotten. Please read how we implement different type of requests (see FAQ):

We use labels for categorizing issues into types and tracking the issue lifecycle. Issues fall into the following types:

Enum-request: Request an enum. We implement these only in major releases.
**Request-for-external: Request to mark a function as external. We normally only implement these in major releases.**
Event-request: Request a new event. We implement these in major and usually next minor releases.
Extensibility-enhancement: Larger suggestions for improving extensibility. We consider these for future releases.
Extensibility-bug: Smaller suggestions for improving extensibility. We consider these for the current release.
