### ISSUE TITLE
[Event Request] CodeUnit 7302 - WMS Management - OnBeforeCheckWhseJnlLineBeforeTestFieldLocation

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11071]
Hi, would it be possible to get an event OnBeforeCheckWhseJnlLineBeforeTestFieldLocation codeunit 7302, procedure CheckWhseJnlLine, like this :

![image](https://user-images.githubusercontent.com/76154006/107783973-2f642880-6d4b-11eb-9387-03ef3aac3346.png)

```
                    if "From Bin Code" = '' then
                        Error(
                          Text006,
                          FieldCaption("Bin Code"), "Whse. Document Type",
                          FieldCaption("Whse. Document No."), "Whse. Document No.",
                          FieldCaption("Line No."), "Whse. Document Line No.");
                end else
                IsHandled:= false;
                OnBeforeCheckWhseJnlLineBeforeTestFieldLocation(WhseJnlLine, ToTransfer,  Location, IsHandled);
                if not IsHandled then
                    if ("Entry Type" <> "Entry Type"::Movement) or not ToTransfer then begin
                        if Location."Directed Put-away and Pick" then
                            TestField("From Zone Code");
                        TestField("From Bin Code");
                    end;

```

![image](https://user-images.githubusercontent.com/76154006/107784147-68040200-6d4b-11eb-9829-c383b11f8b62.png)
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckWhseJnlLineBeforeTestFieldLocation(var WhseJnlLine: Record "Warehouse Journal Line"; var ToTransfer: Boolean; var Location: Record Location; var IsHandled: Boolean)
    begin
    end;
```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
