### ISSUE TITLE
[Event Request] CodeUnit 7302 - WMS Management - OnBeforeGetDefaultBin

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11077]
Hi, would it be possible to get an event OnBeforeGetDefaultBin codeunit 7302, procedure GetDefaultBin , like this :
![image](https://user-images.githubusercontent.com/76154006/107798338-42332900-6d5c-11eb-82e1-48101cd87d16.png)

```
    procedure GetDefaultBin(ItemNo: Code[20]; VariantCode: Code[10]; LocationCode: Code[10]; var BinCode: Code[20]): Boolean
    var
        BinContent: Record "Bin Content";
        IsHandled: Boolean;
    begin
        IsHandled:= false;
        OnBeforeGetDefaultBin(BinContent, IsHandled);
        if not IsHandled then begin
        BinContent.SetCurrentKey(Default);
        BinContent.SetRange(Default, true);
        BinContent.SetRange("Location Code", LocationCode);
        BinContent.SetRange("Item No.", ItemNo);
        BinContent.SetRange("Variant Code", VariantCode);
        if BinContent.FindFirst then begin
            BinCode := BinContent."Bin Code";
            exit(true);
        end;
        end;
    end;

```

![image](https://user-images.githubusercontent.com/76154006/107797776-9c7fba00-6d5b-11eb-9635-3c3644a5d13e.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetDefaultBin(var BinContent: Record "Bin Content"; var IsHandled: Boolean)
    begin
    end;

```

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
