### ISSUE TITLE
[Request-for-external] codeunit 7321 "Create Inventory Put-away" - FindReservationEntry 

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11081]
Hi, I was wondering if it would be possible to change the procedure FindReservationEntry in codeunit 7321 "Create Inventory Put-away"  from local to external.

Thanks for your work, have a nice day!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
