### ISSUE TITLE
[Event Request] codeunit 7321 "Create Inventory Put-away" - OnBeforeCommit

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11091]
Hi, would it be possible to get an event OnBeforeCommit codeunit 7321 "Create Inventory Put-away", like this :

```
        if AutoCreation and not LineCreated then begin
            WhseActivHeader."No." := '';
            WhseActivHeader.Insert(true);
            UpdateWhseActivHeader(WhseRequest);
            NextLineNo := 10000;
            OnBeforeCommit(NewWhseActivLine, WhseActivHeader);
            Commit();
```
```
    [IntegrationEvent(false, false)] 
    local procedure OnBeforeCommit(var NewWhseActivLine: record "Warehouse Activity Line";var WhseActivHeader:record "Warehouse Activity Header")
    begin
    end;
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
