### ISSUE TITLE
[Event Request] CodeUnit 10842 - G/L Entry Application - GetLetter() - OnBeforeNextLetter

### ISSUE THREAD

**Issue by i-dhahri** [microsoft/ALAppExtensions#11092]
Hello, would it be possible to have an event "OnBeforeNextLetter" in Codeunit 10842 "G/L Entry Application" , procedure GetLetter() Like this :

![image](https://user-images.githubusercontent.com/77328410/108042463-1952b280-7040-11eb-86af-024926c32702.png)

Cordially.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
