### ISSUE TITLE
[Event Request] Codeunit 7171 "Sales Info-Pane Management" OnBeforeCalcReservedRequirements 

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11098]
Hi, would it be possible to get an event OnBeforeCalcReservedRequirements codeunit 7171 , procedure CalcReservedRequirements, like this:

![image](https://user-images.githubusercontent.com/76154006/108051349-13ae9a00-704b-11eb-81e5-9beec4535f00.png)

```
    procedure CalcReservedRequirements(var SalesLine: Record "Sales Line"): Decimal
    begin
        if GetItem(SalesLine) then begin
            SetItemFilter(Item, SalesLine);
            OnBeforeCalcReservedRequirements(Item);

            exit(
              ConvertQty(
                AvailableToPromise.CalcReservedReceipt(Item),
                SalesLine."Qty. per Unit of Measure"));
        end;
    end;


```
![image](https://user-images.githubusercontent.com/76154006/108051376-1b6e3e80-704b-11eb-9d78-8dfd55a8eca7.png)
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcReservedRequirements(var Item: Record Item)
    begin
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
