### ISSUE TITLE
[Event Request] Codeunit 7171 "Sales Info-Pane Management" OnBeforeCalcGrossRequirements

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11097]
Hi, would it be possible to get an event OnBeforeCalcScheduledReceipt codeunit 7171 , procedure CalcScheduledReceipt, like this:
![image](https://user-images.githubusercontent.com/76154006/108050623-2a082600-704a-11eb-84af-dbcd0f1a74b4.png)
```
    procedure CalcGrossRequirements(var SalesLine: Record "Sales Line"): Decimal
    begin
        if GetItem(SalesLine) then begin
            SetItemFilter(Item, SalesLine);
            OnBeforeCalcGrossRequirements(Item);

            exit(
              ConvertQty(
                AvailableToPromise.CalcGrossRequirement(Item),
                SalesLine."Qty. per Unit of Measure"));
        end;
    end;

```
![image](https://user-images.githubusercontent.com/76154006/108050667-38564200-704a-11eb-8966-3132885bfb5b.png)
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcGrossRequirements(var Item: Record Item)
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
