### ISSUE TITLE
[Event Request] codeunit 9520 "Mail Management" - OnAfterValidateEmailAddressField

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11093]
Hi, would it be possible to get an event OnAfterValidateEmailAddressField codeunit 9520 "Mail Management", like this :

```
    procedure ValidateEmailAddressField(var EmailAddress: Text)
    var
        IsHandled: Boolean;
    begin
        EmailAddress := DelChr(EmailAddress, '<>');

        if EmailAddress = '' then
            exit;
        IsHandled:= false;
        OnAfterValidateEmailAddressField(EmailAddress,IsHandled);
        if not IsHandled then
            CheckValidEmailAddress(EmailAddress);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterValidateEmailAddressField(var EmailAdress: Text; var IsHandled: Boolean)
    begin
    end;
```

Thanks!

**Comment by StanPesotskiy** [comment]
Why can't you use the existing event OnBeforeCheckValidEmailAddr?

**Comment by Pepito-lab** [comment]
Hi, I can't use OnBeforeCheckValidEmailAddr because we use CheckValidateEmailAddress in other procedure and we want to call CheckValidateEmailAddresses. Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
