### ISSUE TITLE
[Event Request] CodeUnit 10860 - Payment Management - CopyLigBor() - OnBeforeInitHeader/OnBeforeInsertToPaymentLine

### ISSUE THREAD

**Issue by i-dhahri** [microsoft/ALAppExtensions#11099]
Hello, would it be possible to have two events "OnBeforeInitHeader" and "OnBeforeInsertToPaymentLine" in Codeunit 10860 "Payment Management" , procedure CopyLigBor(), Like this :
![image](https://user-images.githubusercontent.com/77328410/108051541-4fe1fa80-704b-11eb-9975-7229b3eb2d96.png)

Cordially.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
