### ISSUE TITLE
[Event Request] codeunit 9520 "Mail Management" - OnBeforeMailManagement 

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11101]
Hi, would it be possible to get an event OnBeforeMailManagement codeunit 9520 "Mail Management", like this :

```
    begin
        MailManagement.InitializeFrom(HideMailDialog, not IsBackground());
        if MailManagement.IsEnabled() then
            if MailManagement.Send(TempEmailItem, EmailScenario) then begin
                OnBeforeMailManagement(MailManagement);
                MailSent := MailManagement.IsSent();
                exit;
            end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeMailManagement(var MailManagement: Codeunit "Mail Management")
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
