### ISSUE TITLE
[Extensibility Bug] codeunit 6620 "Copy Document Mgt." - GetNewLineNumber

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#11104]
Hi. 

I found a bug when using event OnAfterCopySalesLineExtText and parameter TransferOldExtLines.
From table TransferOldExtLines i use procedure GetNewLineNumber.
It returns a single digit number instead of a document line no. Usually 10000...
In procedure SplitPstdSalesLinesPerILE it uses the procedure AddSalesDocLine.
But it adds the buffer line no to the DocumentLineNo parameter.

I think this is how it should be:
```
                    OnSplitPstdSalesLinesPerILETransferFields(FromSalesHeader, FromSalesLine, TempSalesLineBuf, ToSalesHeader);
                    TempSalesLineBuf.Insert();
                    // >>>>>>>>>>>>>>>>>>>>
                    //AddSalesDocLine(TempDocSalesLine, TempSalesLineBuf."Line No.", "Document No.", TempSalesLineBuf."Line No.");
                    AddSalesDocLine(TempDocSalesLine, TempSalesLineBuf."Line No.", "Document No.", "Document Line No.");
                    // <<<<<<<<<<<<<<<<<<<<
                end;
```

I'm guessing that this also will cause an issue with "Attached to Line No." field.
Should i post this issue somewhere else?

**Comment by Oleg-Romashkov** [comment]
Sorry for late reply. 

Unfortunately, suggested fix breaks other existing scenarios. For example, test case TestGetShptInvoiceFromOrder of test codeunit 137025 "SCM Purchase Correct Invoice" (SCMPurchaseCorrectInvoice.Codeunit.al)

Could you provide a full user scenario when you have a described problem?

**Comment by auzhhv** [comment]
> Sorry for late reply.
> 
> Unfortunately, suggested fix breaks other existing scenarios. For example, test case TestGetShptInvoiceFromOrder of test codeunit 137025 "SCM Purchase Correct Invoice" (SCMPurchaseCorrectInvoice.Codeunit.al)
> 
> Could you provide a full user scenario when you have a described problem?

It has been a while since i found this, but I will try to find the code path.
AddSalesDocLine is called 3 times. Two of the times the correct line no. is used in the last parameter.

When copying a document, "Attached to Line No." must be changed for text lines if the associated lines gets a new line no.
In procedure CopySalesLineExtText the field "Attached to Line No." is updated based on the old line no.
This will not work correctly.

Lets say we are going to copy a posted sales invoice to a sales order. (same for sales shipment)
The following procedures will be called:
CopySalesDoc
CopySalesDocInvLine
CopySalesInvLinesToDoc
SplitPstdSalesLinesPerILE
AddSalesDocLine

TempDocSalesLine will now contain records with 
"Shipment Line No."  = 1, 2, 3.. (incremented in code)
"Document No." = "Document No." from item ledger entry
"Line No." = same as "Shipment Line No." (should be "Document Line No." from item ledger entry)

Then we backtrack to procedure CopySalesInvLinesToDoc with TempDocSalesLine as reference parameter and the following procedures will be called:
GetSalesLineNo is called with TempDocSalesLine as parameter, and will return "Line No." from TempDocSalesLine. This "Line No." is now 1, 2, 3.. and not 10000, 20000, 30000.. as it contains the same value as "Shipment Line No." in TempDocSalesLine.
CopySalesDocLine is called with the result of GetSalesLineNo as parameter DocLineNo
CopySalesLineExtText is called with DocLineNo as parameter DocLineNo
TransferExtendedText is called with DocLineNo as parameter OldLineNo
InsertLineNumbers is called with parameter OldLineNo as OldLineNo and NewLineNo (where NewLineNo is the new line number of the line that is inserted).
Then we backtrack to TransferExtendedText for the next lines and GetNewLineNumber is called with the "Attachment Line No." from the posted sales invoice line. GetNewLineNumber will then try to find what the new line number based on the old.
But as the old line no. in this buffer is now 1, 2, 3.. it will not match with "Attachment Line No.".

Let me do a simplified example..

Line No.              Type               No.          Description         Attached To Line No.
10000                  Item              1234        My Item              0
20000                  Comment                     My Comment     10000

When the document is copied lets say a new text line is inserted as the first line.
Then line 10000 will be line 20000..
The procedure GetNewLineNumber should then return 20000, so "Attached to Line No." is updated.
But its not going to as the first line in LineNoBuffer in codeunit "Transfer Old Ext. Text Lines" was inserted with the wrong line no.

Hope this helps :)

**Comment by Oleg-Romashkov** [comment]
I tried to run copy posted sales invoice scenario when it has extended text lines and it works ok. Maybe I missed some important steps. Could you provide user scenario with more details.
For example:
1. Add extended text lines to item 1000 (line 1 "ext text 1", line 2 "ext text 2")
2. Create invoice with item 1000 and run action Insert extended lines. As a result invoice has 3 lines:
Line No.	Type	No.		Description	Attached to Line No.
10000		Item	1000	Bicycle		0
20000	 				ext text 1	       10000
30000	 				ext text 2	       10000
3. Post invoice
4. Create new invoice, run Copy Document action, pick Document Type = Posted Invoice, Document No. = number of invoice from step 3, Recalculate lines = false

**Actual result:** 
created sales lines:

Line No.	Type	No.	Description	Attached to Line No.
10000			Invoice No. 103032:	0
30000	Item	1000	Bicycle	0
40000			ext text 1	30000
50000			ext text 2	30000

**Expected result:**
...

**Comment by auzhhv** [comment]
> I tried to run copy posted sales invoice scenario when it has extended text lines and it works ok. Maybe I missed some important steps. Could you provide user scenario with more details.
> For example:
> 
> 1. Add extended text lines to item 1000 (line 1 "ext text 1", line 2 "ext text 2")
> 2. Create invoice with item 1000 and run action Insert extended lines. As a result invoice has 3 lines:
>    Line No.	Type	No.		Description	Attached to Line No.
>    10000		Item	1000	Bicycle		0
>    20000	 				ext text 1	       10000
>    30000	 				ext text 2	       10000
> 3. Post invoice
> 4. Create new invoice, run Copy Document action, pick Document Type = Posted Invoice, Document No. = number of invoice from step 3, Recalculate lines = false
> 
> **Actual result:**
> created sales lines:
> 
> Line No. Type No. Description Attached to Line No.
> 10000 Invoice No. 103032: 0
> 30000 Item 1000 Bicycle 0
> 40000 ext text 1 30000
> 50000 ext text 2 30000
> 
> **Expected result:**
> ...

Hi Oleg,

I will try to recreate the issue as soon as possible.

As this is not an urgent matter for the customer and we have a few other priority cases, I will come back to you later this week or next week.

-Håkon

**Comment by Oleg-Romashkov** [comment]
Please create a new request when you will be ready with full scenario.
