### ISSUE TITLE
[Event Request] Table 81 "Gen. Lournal Line" - Function RenumberDocNoOnLines - OnAfterRenumberDocNoOnLines

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11107]
We added a dialog to show the amount of lines to be renumber. With OnBeforeRenumberDocNoOnLines opening is possible, OnAfterRenumberDocNoOnLines would make it possible to close by system. 

    [EventSubscriber(ObjectType::Table, Database::"Gen. Journal Line", 'OnAfterRenumberDocNoOnLines', '', true, true)]
    local procedure "Gen. Journal Line_OnAfterRenumberDocNoOnLines"
    (
        var DocNo: Code[20];
        var GenJnlLine2: Record "Gen. Journal Line";
        var IsHandled: Boolean
    )

**Comment by StanPesotskiy** [comment]
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.

**Comment by SWE-Tina** [comment]
```
                    GenJnlLine3.Get("Journal Template Name", "Journal Batch Name", "Line No.");
                    CheckJobQueueStatus(GenJnlLine3);
                    GenJnlLine3."Document No." := DocNo;
                    GenJnlLine3.Modify();
                    First := false;
                    LastGenJnlLine := GenJnlLine2
                until Next = 0;
               **OnAfterRenumberDocNoOnLines** 
            end
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
