### ISSUE TITLE
Codeunit Graph Mgt - Inc Doc Attachment

### ISSUE THREAD

**Issue by georgii01** [Microsoft/ALAppExtensions#1110]
**Versions:**

* AL Langauge: 2.1.69331
* Business Central: 13.2.26556.0 (SE)
* Codeunit: 5509 Graph Mgt - Inc Doc Attachment
* Procedure: UpdateRelatedDocument

**LOCAL UpdateRelatedDocument(VAR IncomingDocumentAttachment : Record "Incoming Document Attachment")**
IF IncomingDocumentAttachment.ISTEMPORARY OR (NOT GraphMgtGeneralTools.IsApiEnabled) THEN
EXIT;

IF NOT IncomingDocument.GET(IncomingDocumentAttachment."Incoming Document Entry No.") THEN
EXIT;

IF NOT IncomingDocument.GetRecord(RelatedDocument) THEN
EXIT;

**RelatedRecRef := RelatedDocument;**
_RelatedRecRef – rec reference RelatedDocument – variant_

IF NOT RelatedRecRef.WRITEPERMISSION THEN BEGIN
SENDTRACETAG('00006WH',AttachmentCategoryLbl,VERBOSITY::Error,NoPermissionErr,DATACLASSIFICATION::SystemMetadata);
EXIT;
END;

IF NOT IntegrationManagement.IsIntegrationRecord(RelatedRecRef.NUMBER) THEN
EXIT;

RelatedRecRef.MODIFY(TRUE);`

Incoming Documents -> Incoming Document Files -> Attach File
There is no possibility to add file.

Scenario:
Incoming Documents -> Incoming Document Files -> Attach File
The result: File not added, no error message.

**Comment by finn777** [comment]
Looks like bug 299273 - No file is added through Attach File action in the Incoming Document Files just registered for this story.

**Comment by JesperSchulz** [comment]
Correct. This issue is tracked through a bug. Also, this repo is for extensibility requests only, not gerneral bug reports.
