### ISSUE TITLE
Codeunit 12 - OnBeforeRun... Events are using emtpry records

### ISSUE THREAD

**Issue by AxelLeder** [microsoft/ALAppExtensions#11109]
The Events OnBeforeRunWithCheck and OnBeforeRunWithoutCheck are using an unitialized local record GenJnlLine.
It should raised after GenJnlLine.Copy(GenJnlLine2).

```
    procedure RunWithCheck(var GenJnlLine2: Record "Gen. Journal Line"): Integer
    var
        GenJnlLine: Record "Gen. Journal Line";
    begin
        OnBeforeRunWithCheck(GenJnlLine);

        GenJnlLine.Copy(GenJnlLine2);
        Code(GenJnlLine, true);
        OnAfterRunWithCheck(GenJnlLine);
        GenJnlLine2 := GenJnlLine;
        exit(GLEntryNo);
    end;
```

```
    procedure RunWithoutCheck(var GenJnlLine2: Record "Gen. Journal Line"): Integer
    var
        GenJnlLine: Record "Gen. Journal Line";
    begin
        OnBeforeRunWithoutCheck(GenJnlLine);

        GenJnlLine.Copy(GenJnlLine2);
        Code(GenJnlLine, false);
        OnAfterRunWithoutCheck(GenJnlLine);
        GenJnlLine2 := GenJnlLine;
        exit(GLEntryNo);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
