### ISSUE TITLE
[Protection Level] Codeunit "Purch.-Explode BOM" - Function "ExplodeBOMCompLines" remove local

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11102]
Due to calling the function from an event, we need it as global.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
