### ISSUE TITLE
[Function Request] Record::"Transfer Header" - Function GetHideValidationDialog

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11105]
As HideValidationDialog is protected but is useful and in our case needed, we would like to have a function in table "Transfer Header" to call the state of HideValidationDialog. 

```
procedure GetHideValidationDialog(): Boolean
begin
  exit(HideValidationDialog);
end;
```

**Comment by StanPesotskiy** [comment]
Already added
