### ISSUE TITLE
[Protection Level] Table "Gen. Journal Line" Function "RenumberAppliesToID" remove local

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11112]
Please remove local - we have renumbering functions especially for recurring ones and used the standard function for it and want to avoid having unnecessary duplicates.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
