### ISSUE TITLE
[Event Request] Page "Sales Statistics" Integration Event "OnAfterCalculateTotals" globals accessible needed

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11111]
We need to have access to globals and procedures. Please make this accessible in the event. 

```
**_[IntegrationEvent(true, true)]_**
local procedure OnAfterCalculateTotals(var SalesHeader: Record "Sales Header"; var TotalSalesLine: Record "Sales Line"; var TotalSalesLineLCY: Record "Sales Line"; var TempVATAmountLine: Record "VAT Amount Line" temporary; var TotalAmt1: Decimal; var TotalAmt2: Decimal)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
