### ISSUE TITLE
[Event Request] codeunit 10801 "RIB Key" - OnAfterCheck

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11117]
Hi, would it be possible to get an event OnAfterCheck codeunit 10801 "RIB Key", like this :

```
        Remaining := 0;
        for Index := 1 to 23 do
            Remaining := (Remaining * 10 + (LongAccountNum[Index] - '0')) mod 97;

        OnAfterCheck(Remaining);

        exit(Remaining = 0);
```
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCheck(Remaining: Integer)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
