### ISSUE TITLE
[Event Request] Page "Sales Statistics" OnAfterUpdateHeaderInfo Additional Parameters

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11110]
TotalAmount 1 and Total Amount 2 are changed in our case due to exchange part management. Therefore we need 2 more parameters. 

```
[EventSubscriber(ObjectType::Page, Page::"Sales Statistics", 'OnAfterUpdateHeaderInfo', '', true, true)]
local procedure "Sales Statistics_OnAfterUpdateHeaderInfo"(TotalSalesLineLCY: Record "Sales Line"; var TotalAmt1: Decimal; var TotalAmt2: Decimal )
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
