### ISSUE TITLE
[Change Request] Codeunit 8618 Config. Excel Exchange

### ISSUE THREAD

**Issue by PaulFurlet** [microsoft/ALAppExtensions#11119]
Function IsImportFromExcelConfirmed checks GUI and HideDialog before actual parsing Excel file.
It would be correct to have TempConfigPackageTable being filled before exiting function if no user involvement is required.
At the moment if no request shown excel sheet is not processed.

```
local procedure IsImportFromExcelConfirmed(var TempConfigPackageTable: Record "Config. Package Table" temporary): Boolean
var
    ConfigPackageImportPreview: Page "Config. Package Import Preview";
begin
    // old code start
    // if GuiAllowed and not HideDialog then
    //      if ReadPackageTableKeysFromExcel(TempConfigPackageTable) then begin
    // old code end
    // new code start
    if ReadPackageTableKeysFromExcel(TempConfigPackageTable) then
        if GuiAllowed and not HideDialog then begin
    // new code end
            ConfigPackageImportPreview.SetData(SelectedConfigPackage.Code, TempConfigPackageTable);
            ConfigPackageImportPreview.RunModal;
            exit(ConfigPackageImportPreview.IsImportConfirmed);
        end;
    exit(true);
end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
