### ISSUE TITLE
Var Parameter for OnAfterConfirmPost IntegrationEvents

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#11125]
Hello,

please insert **var** Parameter Flag for existing Parameter PurchaseHeader in IntegrationEvent OnAfterConfirmPost in Codeunit "Purch.-Post (Yes/No)" and "Purch.-Post + Print" like in Sales.

Purchase Post:
    [IntegrationEvent(false, false)]
    local procedure OnAfterConfirmPost(PurchaseHeader: Record "Purchase Header")
    begin
    end;

Sales Post:
    [IntegrationEvent(false, false)]
    local procedure OnAfterConfirmPost(**var** SalesHeader: Record "Sales Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
