### ISSUE TITLE
[Event Request] Table 5900 "Service Header": OnValidateShipToCodeOnBeforeDleereLines

### ISSUE THREAD

**Issue by deadmouse** [microsoft/ALAppExtensions#11120]
[Event Request] Table 5900 "Service Header": OnValidateShipToCodeOnBeforeDleereLines

Event is misspelled. It is currently named as "OnValidateShipToCodeOnBeforeDleereLines" and it should be "OnValidateShipToCodeOnBeforeDeleteLines

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
