### ISSUE TITLE
[Event Request] New IntegrationEvent in Codeunit 82 "Sales-Post + Print" and Coduenit 92 "Purch.-Post + Print"

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#11127]
Hello,

please insert new IntegrationEvent in Codeunit 82 "Sales-Post + Print" and 92 "Purch.-Post + Print". The function should have a VAR Record Parameter.

```
        PurchSetup.Get();
        if PurchSetup."Post & Print with Job Queue" then
            PurchasePostViaJobQueue.EnqueuePurchDoc(PurchHeader)
        else begin
// Start kvs.dde
OnBeforeRunPurchPost(PurchaseHeader);
// Stop kvs.dde
            CODEUNIT.Run(CODEUNIT::"Purch.-Post", PurchHeader);
            GetReport(PurchHeader);
        end;
```

```
        SalesSetup.Get();
        if SalesSetup."Post & Print with Job Queue" and not SendReportAsEmail then
            SalesPostViaJobQueue.EnqueueSalesDoc(SalesHeader)
        else begin
// Start kvs.dde
OnBeforeRunSalesPost(SalesHeader);
// Stop kvs.dde
            CODEUNIT.Run(CODEUNIT::"Sales-Post", SalesHeader);
            GetReport(SalesHeader);
        end;
```

**Comment by AlexanderYakunin** [comment]
We already have this (same for Purchase side):

    local procedure RunSalesPost(var SalesHeader: Record "Sales Header")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeRunSalesPost(SalesHeader, IsHandled);
        if IsHandled then
            exit;

        Codeunit.Run(Codeunit::"Sales-Post", SalesHeader);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
