### ISSUE TITLE
[Change Request]  "Tax Jurisdiction Code" field length.

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#11121]
Hello, some customers changed the "Tax Jurisdiction Code" field length from Code[10] to Code[40].
List of tables: "Gen. Journal Line", "VAT Entry", "VAT Statement Line", "VAT Amount Line", "Tax Area Line", "Tax Jurisdiction",
"Tax Detail", "Detailed Vendor Ledg. Entry", "Detailed CV Ledg. Entry Buffer", "Sales Tax Amount Line", "Sales Tax Amount Difference".  We update from NAV2016 to BC17 cloud version. 

Is it possible to implement it in the next release version?

**Comment by StanPesotskiy** [comment]
Increasing the field length is a breaking change. We are not doing this.

For the new features please submit a product suggestion on https://aka.ms/bcideas
