### ISSUE TITLE
[Event Request] Codeunit 99000774 "Calculate Routing Line" – New Event “OnBeforeCalcRoutingLineBack”

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#11123]
Hi
Could we please have a new publisher “OnBeforeCalcRoutingLineBack” in Function “CalcRoutingLineBack” in Codeunit 99000774 "Calculate Routing Line”, including a IsHandled pattern?

    local procedure CalcRoutingLineBack(CalculateEndDate: Boolean)
    var
        ProdOrderRoutingLine2: Record "Prod. Order Routing Line";
        ProdOrderRoutingLine3: Record "Prod. Order Routing Line";
        ConstrainedCapacity: Record "Capacity Constrained Resource";
        ParentWorkCenter: Record "Capacity Constrained Resource";
        TmpProdOrderRtngLine: Record "Prod. Order Routing Line" temporary;
        SendAheadLotSize: Decimal;
        ParentIsConstrained: Boolean;
        ResourceIsConstrained: Boolean;
        // Start new Code
        IsHandled: Boolean;
        // End new Code
    begin
        // Start new Code
        IsHandled := false;
        OnBeforeCalcRoutingLineBack(ProdOrderRoutingLine, CalculateEndDate, IsHandled);
        if IsHandled then
            exit;
        // End new Code

        CalendarEntry.SetRange(Date, 0D, ProdOrderRoutingLine."Ending Date");

        ProdEndingTime := ProdOrderRoutingLine."Ending Time";
        ProdEndingDate := ProdOrderRoutingLine."Ending Date";
        ProdStartingTime := ProdOrderRoutingLine."Ending Time";
        ProdStartingDate := ProdOrderRoutingLine."Ending Date";

        FirstEntry := true;
        ...

    // Start new Code
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcRoutingLineBack(var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; CalculateEndDate: Boolean; var IsHandled: Boolean)
    begin
    end;
    // End new Code

Thanks, Anders

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
