### ISSUE TITLE
[Event Request] Table "Sales Line" - Function OpenItemTrackingLines - Event "OnAfterOpenItemTrackingLines" needed

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11131]
After the Item Tracking Page was opened, there are some things to be proceeded(depending on serial no. getting other values etc.). Therefore a OnAfterOpenItemTrackingLines is needed.

` [EventSubscriber(ObjectType::Table, Database::"Sales Line", 'OnAfterOpenItemTrackingLines', '', true, true)]
    local procedure "Sales Line_OnAfterOpenItemTrackingLines"(SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin`

Placement in code:
```
OpenItemTrackingLines()
IsHandled := FALSE;
OnBeforeOpenItemTrackingLines(Rec,IsHandled);
IF IsHandled THEN
  EXIT;

TESTFIELD(Type,Type::Item);
TESTFIELD("No.");
TESTFIELD("Quantity (Base)");
IF "Job Contract Entry No." <> 0 THEN
  ERROR(Text048,TABLECAPTION,Job.TABLECAPTION);
ReserveSalesLine.CallItemTracking(Rec);

**OnAfterOpenItemTrackingLines**
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
