### ISSUE TITLE
[Event Request] codeunit 10821 "Export DEB DTI" - OnAfterAddItem2

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11136]
Hi, would it be possible to get an event OnAfterAddItem2 codeunit 10821 "Export DEB DTI", like this :
```
            XMLDomMgt.AddNode(XMLNode, 'netMass', FormatToXML(IntrastatJnlLine."Total Weight"));
        IsHandled:= false
        OnAfterAddItem2(XMLNode,XMLDomMgt,IntrastatJnlLine,IsHandled);
        if not IsHandled then begin
            if IntrastatJnlLine.Quantity <> 0 then
                XMLDomMgt.AddNode(XMLNode, 'quantityInSU', FormatToXML(IntrastatJnlLine.Quantity));
        end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterAddItem2(var XMLNode: DotNet XMLNode;var XMLDomMgt: Codeunit "XML DOM Management"; var IntrastatJnlLine: Record "Intrastat Jnl. Line";IsHandled: Boolean)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
