### ISSUE TITLE
[Event Request] Codeunit 10842 "G/L Entry Application"- OnBeforeGetLetter

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11137]
Hi, would it be possible to get an event OnBeforeGetLetter codeunit 8614, procedure GetLetter, like this :

![image](https://user-images.githubusercontent.com/76154006/108230578-36bb7580-7141-11eb-9997-d9ffe5be7fbb.png)

```
    procedure GetLetter()
    var
        GLEntry2: Record "G/L Entry";
        IsHandled: Boolean;
    begin
        if LetterToSet <> '' then
            exit;
        GLEntry2.SetFilter("G/L Account No.", GLEntry."G/L Account No.");
        GLEntry2.SetCurrentKey("G/L Account No.", Letter);
        IsHandled:= false;
        OnBeforeGetLetter(GLEntry2, LetterToSet, IsHandled);
        if not IsHandled then begin
        if GLEntry2.FindLast then
            LetterToSet := UpperCase(GLEntry2.Letter);
        NextLetter(LetterToSet);
        end;
    end;

```

![image](https://user-images.githubusercontent.com/76154006/108230627-433fce00-7141-11eb-9887-7c32ed1edbf6.png)
```
[IntegrationEvent(false, false)]
local procedure OnBeforeGetLetter(var  GLEntry2: Record "G/L Entry"; var LetterToSet: Text[10]; IsHandled: Boolean)
begin
end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
