### ISSUE TITLE
[Event Request] codeunit 10821 "Export DEB DTI" - OnAfterAddItem

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11132]
Hi, would it be possible to get an event OnAfterAddItem codeunit 10821 "Export DEB DTI", like this :
```
        end;
        OnAfterAddItem(XMLNode,XMLDomMgt,IntrastatJnlLine);
        if IntrastatJnlLine."Country/Region of Origin Code" <> '' then
            XMLDomMgt.AddNode(XMLNode, 'countryOfOriginCode', IntrastatJnlLine."Country/Region of Origin Code");
        if IntrastatJnlLine."Entry/Exit Point" <> '' then
            XMLDomMgt.AddNode(XMLNode, 'paysProvenance', IntrastatJnlLine."Entry/Exit Point");
```
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterAddItem(var XMLNode: DotNet XMLNode;var XMLDomMgt: Codeunit "XML DOM Management"; var IntrastatJnlLine: Record "Intrastat Jnl. Line")
    begin
    end;
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
