### ISSUE TITLE
[Event Request] table 130 "Incoming Document" - OnRemoveReferenceToWorkingDocumentOnBeforeModify

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#11135]
Could you please add the following event.

```al
procedure RemoveReferenceToWorkingDocument(EntryNo: Integer)
begin
    if EntryNo = 0 then
        exit;
    if not Get(EntryNo) then
        exit;

    ...

    OnRemoveReferenceToWorkingDocumentOnBeforeModify(Rec); //NEW
    Modify;
end;
```

```al
[IntegrationEvent(false, false)]
local procedure OnRemoveReferenceToWorkingDocumentOnBeforeModify(var IncomingDocument: Record "Incoming Document")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
