### ISSUE TITLE
[Event Request] codeunit 10821 "Export DEB DTI" - OnAfterAddNode

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11139]
Hi, would it be possible to get an event OnAfterAddNode codeunit 10821 "Export DEB DTI", like this :

```
        end;

        if IntrastatJnlLine."Transport Method" <> '' then
            XMLDomMgt.AddNode(XMLNode, 'modeOfTransportCode', IntrastatJnlLine."Transport Method");

        OnAfterAddNode(XMLNode,XMLDomMgt, CompanyInfo);
    end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterAddNode(var XMLNode: DotNet XMLNode;var XMLDomMgt: Codeunit "XML DOM Management";var CompanyInfo: Record "Company Information")
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
