### ISSUE TITLE
[Request-for-external] Codeunit 7312 Create Pick - CalcPickQtyAssigned

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#11133]
Hi, would it be possible to modify the procedure CalcPickQtyAssigned in codeunit 7312 from local to external ?

Thanks

**Comment by AlexanderYakunin** [comment]
This function use TempWhseActivLine, which is global variable. Than means external call of this function can give unpredictable results. Are you sure?

**Comment by AlexanderYakunin** [comment]
This procedure use global variable, we cannot expose it.
