### ISSUE TITLE
Missing field "Bank Account" in Sales Cr.Memo Header and Sales Shipment Header

### ISSUE THREAD

**Issue by gpintaudi** [microsoft/ALAppExtensions#11148]
Hi all,
field(12172; "Bank Account"; Code[20]) is missing from above tables.
This field is managed in Sales Invoice Header (transferred from Sales Header with the posting).
We need this field added in Sales Shipment Header and Sales Cr.Memo Header as well.

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
