### ISSUE TITLE
Codeunit 6520 Item Tracing Mgt.

### ISSUE THREAD

**Issue by afrancioli** [microsoft/ALAppExtensions#11146]
We need a new event in codeunit 6520 Item Tracing Mgt. . The request is to handle a different  description 2 depending on our Jobs management Add on.
The code below is just a sample. Feel free to change the name.

    [Integration]
    **LOCAL PROCEDURE OnInsertRecordAfterCase@1101345001(VAR TempTrackEntry@1101345000 : Record 6520;VAR 
    RecRef@1101345002 : RecordRef);**
    BEGIN
    END;

    
    LOCAL PROCEDURE InsertRecord@1000000004(VAR TempTrackEntry@1002 : Record 6520;ParentID@1003 : Integer) : Boolean;
    VAR
      TempTrackEntry2@1004 : Record 6520;
      ProductionOrder@1000 : Record 5405;
      ItemLedgerEntry@1005 : Record 32;
      Job@1006 : Record 167;
      RecRef@1001 : RecordRef;
      InsertEntry@1007 : Boolean;
      Description2@1008 : Text[100];
    BEGIN
      WITH TempTrackEntry DO BEGIN
        TempTrackEntry2 := TempTrackEntry;
        RESET;
        SETCURRENTKEY("Item Ledger Entry No.");
        SETRANGE("Item Ledger Entry No.","Item Ledger Entry No.");

        // Mark entry if already in search result
        TempTrackEntry2."Already Traced" := FINDFIRST;

        IF CurrentLevel = 1 THEN BEGIN
          SETRANGE("Parent Item Ledger Entry No.",ParentID);
          SETFILTER(Level,'<>%1',CurrentLevel);
        END;

        InsertEntry := TRUE;
        IF CurrentLevel <= 1 THEN
          InsertEntry := NOT FINDFIRST;

        IF InsertEntry THEN BEGIN
          TempTrackEntry2.RESET;
          TempTrackEntry := TempTrackEntry2;
          TempLineNo += 1;
          "Line No." := TempLineNo;
          SetRecordID(TempTrackEntry);
          "Parent Item Ledger Entry No." := ParentID;
          IF FORMAT("Record Identifier") = '' THEN
            Description2 := STRSUBSTNO('%1 %2',"Entry Type","Document No.")
          ELSE BEGIN
            IF RecRef.GET("Record Identifier") THEN
              CASE RecRef.NUMBER OF
                DATABASE::"Production Order":
                  BEGIN
                    RecRef.SETTABLE(ProductionOrder);
                    Description2 :=
                      STRSUBSTNO('%1 %2 %3 %4',ProductionOrder.Status,RecRef.CAPTION,"Entry Type","Document No.");
                  END;
                DATABASE::"Posted Assembly Header":
                  Description2 := STRSUBSTNO('%1 %2',"Entry Type","Document No.");
                DATABASE::"Item Ledger Entry":
                  BEGIN
                    RecRef.SETTABLE(ItemLedgerEntry);
                    IF ItemLedgerEntry."Job No." <> '' THEN BEGIN
                      //Orginal Code
                      Job.GET(ItemLedgerEntry."Job No.");
                      Description2 := FORMAT(STRSUBSTNO('%1 %2',Job.TABLECAPTION,ItemLedgerEntry."Job No."),-50);
                      **//Code We Need to move
      //                IF CheckJobManagement.UseJobManagemtAction THEN
      //                  BEGIN
      //                    JobAction.GET(ItemLedgerEntry."Job No. ANW");
      //                    Description2 := FORMAT(STRSUBSTNO('%1 %2',JobAction.TABLECAPTION,ItemLedgerEntry."Job No."),-50);
      //                  END ELSE BEGIN
      //                    Job.GET(ItemLedgerEntry."Job No.");
      //                   Description2 := FORMAT(STRSUBSTNO('%1 %2',Job.TABLECAPTION,ItemLedgerEntry."Job No."),-50);
      //              END;
                      //PSAIT9.00 End**
                    END;
                  END;
              END;
              **//Code Change Start
              //Suggested Event Publisher
              OnInsertRecordAfterCase(TempTrackEntry,RecRef);
              //Code Change End**
            IF Description2 = '' THEN
              Description2 := STRSUBSTNO('%1 %2',RecRef.CAPTION,"Document No.");
          END;
          SetDescription(Description2);
          INSERT;
          EXIT(TRUE);
        END;
        EXIT(FALSE);
      END;
    END;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
