### ISSUE TITLE
[Event Request] - CRM Int. Subscriber - OnBeforeUpdateCRMInvoiceBeforeInsertRecord

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#11149]
![image](https://user-images.githubusercontent.com/35260264/108369763-37fda880-71fc-11eb-8f0c-44ae62f848f5.png)

We have a customer that is using Contact in CRM as Customers in BC.
There for i need to be able to synch invoices.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
