### ISSUE TITLE
[Event Request] Codeunit 408 “DimensionManagement", - OnBeforeCreateDimSetFromJobTaskDim

### ISSUE THREAD

**Issue by nathanbrittles** [microsoft/ALAppExtensions#11145]
We need a new Event function in Codeunit 408 “CarteraManagement", named OnBeforeCreateDimSetFromJobTaskDim:

[IntegrationEvent(false, false)]
local procedure OnBeforeCreateDimSetFromJobTaskDim(JobNo: Code[20]; JobTaskNo: Code[20]; var GlobalDimVal1: Code[20]; var GlobalDimVal2: Code[20]; var IsHandled: Boolean; var NewDimSetID: Integer)
begin
end

called from:

    procedure CreateDimSetFromJobTaskDim(JobNo: Code[20]; JobTaskNo: Code[20]; var GlobalDimVal1: Code[20]; var GlobalDimVal2: Code[20]) NewDimSetID: Integer
    var
        JobTaskDimension: Record "Job Task Dimension";
        DimValue: Record "Dimension Value";
        TempDimSetEntry: Record "Dimension Set Entry" temporary;
    begin
       // init insert
       OnBeforeCreateDimSetFromJobTaskDim(JobNo,JobTaskNo,GlobalDimVal1,GlobalDimVal2,IsHandled,NewDimSetID)
      if IsHandled then
      exit;

       // end insert
        with JobTaskDimension do begin
            SetRange("Job No.", JobNo);
            SetRange("Job Task No.", JobTaskNo);
            if FindSet then begin
                repeat
                    DimValue.Get("Dimension Code", "Dimension Value Code");
                    TempDimSetEntry."Dimension Code" := "Dimension Code";
                    TempDimSetEntry."Dimension Value Code" := "Dimension Value Code";
                    TempDimSetEntry."Dimension Value ID" := DimValue."Dimension Value ID";
                    TempDimSetEntry.Insert(true);
                until Next = 0;
                NewDimSetID := GetDimensionSetID(TempDimSetEntry);
                UpdateGlobalDimFromDimSetID(NewDimSetID, GlobalDimVal1, GlobalDimVal2);
            end;
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
