### ISSUE TITLE
[Event Request] Codeunit 10842 "G/L Entry Application"- OnBeforeNextLetter 

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11140]
Hi, would it be possible to get an event OnBeforeNextLetter codeunit 8614, procedure NextLetter, like this :

![image](https://user-images.githubusercontent.com/76154006/108231098-b6494480-7141-11eb-8854-6aece41dc965.png)

```
    procedure NextLetter(var Letter: Text[10])
    var
    IsHandled: boolean;
    begin
        IsHandled:= false;
        OnBeforeNextLetter(Letter, IsHandled);
        if IsHandled then
        exit;
        case Letter of
            '':
                Letter := 'AAA';
            'AAA' .. 'ZZY':
                IncrementAlphabeticString(Letter, 1, 3);
            'ZZZ':
                Letter := 'ZZZ.000000';
            'ZZZ.000000' .. 'ZZZ.999998':
                Letter := IncStr(Letter);
            'ZZZ.999999':
                Letter := 'ZZZ.AAAAAA';
            'ZZZ.AAAAAA' .. 'ZZZ.ZZZZZY':
                IncrementAlphabeticString(Letter, 5, 10);
        end;
    end;

```

![image](https://user-images.githubusercontent.com/76154006/108230975-974ab280-7141-11eb-987a-023f804994ae.png)

```
[IntegrationEvent(false, false)]
local procedure OnBeforeNextLetter(var Letter: Text[10]; IsHandled: Boolean)
begin
end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
