### ISSUE TITLE
[Event Request] Page 1170 "User Task List" OnBeforeRunReportOrPageLink

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#11144]
We need the same event trigger OnBeforeRunReportOrPageLink from Page 1171 "User Task Card" also in Page 1170 "User Task List".

Maybe it would be better to implement the function RunReportOrPageLink as external function in Table 1170 "User Task" and to call the procedure from both pages. I dont see any harm with this function being external.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
