### ISSUE TITLE
[Event Request] codeunit 10861 "Payment-Apply" - OnAfterValidate

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11143]
Hi, would it be possible to get an event OnAfterValidate codeunit 10861 "Payment-Apply", like this :
```
        "Amount (LCY)" := GenJnlLine."Amount (LCY)";
        Validate(Amount);
        Validate("Amount (LCY)");
        if ("Direct Debit Mandate ID" = '') and (GenJnlLine."Direct Debit Mandate ID" <> '') then
            Validate("Direct Debit Mandate ID", GenJnlLine."Direct Debit Mandate ID");
            OnAfterValidate(GenJournalLine);
```
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterValidate(GenJournalLine: Record "Gen. Journal Line")
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
