### ISSUE TITLE
[Enum Request] In the table "Workflow Step Argument", fields "Approver Type" and "Approver Limit Type" should be Enum

### ISSUE THREAD

**Issue by castordafonte** [microsoft/ALAppExtensions#11153]
One of our customers needs to extend fields "Approver Type" (field 12) and "Approver Limit Type" (field 13) in "Workflow Step Argument" (table 1523). 
Could you please make them Enum?
Thanks.

![tempsnip](https://user-images.githubusercontent.com/19787321/108379697-79935100-7206-11eb-9c8d-ab2f137ee8a7.png)

**Comment by AlexanderYakunin** [comment]
This is already implemented for 18.0

        field(12; "Approver Type"; Enum "Workflow Approver Type")
        {
            Caption = 'Approver Type';
        }
        field(13; "Approver Limit Type"; Enum "Workflow Approver Limit Type")
        {
            Caption = 'Approver Limit Type';
        }

**Comment by castordafonte** [comment]
Thank you @AlexanderYakunin
