### ISSUE TITLE
[Event Request] Sales Line - On delete trigger - OnBeforeChecktheBlanketOrderLine

### ISSUE THREAD

**Issue by MRevanth96** [microsoft/ALAppExtensions#11152]
Hi Team,

In sales line, Ondelete trigger, I need to skip the below mentioned function based on few conditions. 

        if "Document Type" = "Document Type"::"Blanket Order" then begin
            SalesLine2.Reset();
            SalesLine2.SetCurrentKey("Document Type", "Blanket Order No.", "Blanket Order Line No.");
            SalesLine2.SetRange("Blanket Order No.", "Document No.");
            SalesLine2.SetRange("Blanket Order Line No.", "Line No.");
            if SalesLine2.FindFirst then
                SalesLine2.TestField("Blanket Order Line No.", 0);
        end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
