### ISSUE TITLE
[Event Request] codeunit 99000792 Create Prod. Order from Sale

### ISSUE THREAD

**Issue by TCutullic** [microsoft/ALAppExtensions#11159]
Hi, would it be possible to have 2 events in the procedure CreateProdOrder from codeunit 99000792 "Create Prod. Order from Sale" ?
![image](https://user-images.githubusercontent.com/70213459/108482554-e86dba00-7299-11eb-943e-cd04cc4361f6.png)

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
