### ISSUE TITLE
[Event Request] CU 225 trigger OnRun - new event raise and publisher OnExtendAccTypeCase()

### ISSUE THREAD

**Issue by GeWuNAV** [Microsoft/ALAppExtensions#1115]
Hello,

at the moment it is not possible to apply account types other than Customer, Vendor or Employee.
For applying e.g. the type "G/L Account" there is no possibility to extend it.

May I suggest a solution approach?
![image](https://user-images.githubusercontent.com/40358071/52404766-12e0e600-2aca-11e9-801e-faf291e1ac15.png)

Thank you in advance!

Thanks in advance,
best regards,
G.

Side note: TextConstant Text005 must be different then, or at least include the type "Employee" ("The %1 or %2 must be Customer or Vendor.").

**Comment by AlexanderYakunin** [comment]
We are going to provide apply functionality for G/L Accounts for Fall 2019 release.
