### ISSUE TITLE
[Event Modification] Codeunit 12: Change OnAfterVendLedgEntryInsert's IntegrationEvent to [true, false]

### ISSUE THREAD

**Issue by dibyanugraha** [microsoft/ALAppExtensions#11157]
I am in a middle of implementing something in the purchase and the sales process until I notice the OnAfterCustLedgEntryInsert's IntegrationEvent is currently sets to [true, false] while the OnAfterVendLedgEntryInsert is not. I don't know what the reason behind the differences, but I need the OnAfterVendLedgEntryInsert's IntegrationEvent also to be the same as OnAfterCustLedgEntryInsert.

In short: change this in the Codeunit 12
``` AL
    [IntegrationEvent(false, false)]
    local procedure OnAfterVendLedgEntryInsert(var VendorLedgerEntry: Record "Vendor Ledger Entry"; GenJournalLine: Record "Gen. Journal Line"; var DtldLedgEntryInserted: Boolean)
    begin
    end;
```

Into this:
``` AL
    [IntegrationEvent(true, false)]
    local procedure OnAfterVendLedgEntryInsert(var VendorLedgerEntry: Record "Vendor Ledger Entry"; GenJournalLine: Record "Gen. Journal Line"; var DtldLedgEntryInserted: Boolean)
    begin
    end;
```

I really appreciate if this request is granted.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
