### ISSUE TITLE
request for external/public - page 26 "Vendor Card" - local procedure RunReport()

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#11151]
The Customer Card has this procedure as public, so that page extensions can easily replicate running a given report for the currently shown Customer. The Vendor Card should expose its version too for the same reason, so then we won't have to reinvent the same wheel.

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
