### ISSUE TITLE
[Event Request] Codeunit 99000833 Req. Line-Reserve - OnBeforeVerifyQuantity

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#11168]
Hi, would it be possible to get an event OnBeforeVerifyQuantity in Codeunit 99000833 Req. Line-Reserve, procedure VerifyQuantity, like this : 

```
procedure VerifyQuantity(var NewReqLine: Record "Requisition Line"; var OldReqLine: Record "Requisition Line")
    var
        ReqLine: Record "Requisition Line";
        IsHandled : Boolean;
    begin
        IsHandled := false;
        OnBeforeVerifyQuantity(NewReqLine,OldReqLine,IsHandled);
        if IsHandled then
            exit;

        if Blocked then
            exit;
```
```
[IntegrationEvent(false, false)]
    local procedure OnBeforeVerifyQuantity(var NewReqLine: Record "Requisition Line"; var OldReqLine: Record "Requisition Line"; var IsHandled: Boolean)
    begin
    end; 

```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
