### ISSUE TITLE
[Request-for-external] codeunit 99000855 "Planning-Get Parameters"

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11169]
Hi, I was wondering if it would be possible to change the procedure AssignToArray in codeunit 99000855 "Planning-Get Parameters" from local to external.
My team and I use this procedure a lot in our code, and changing it to external would be a huge help.
Thanks

**Comment by AlexanderYakunin** [comment]
This functions is not specific to Planning and can be located at any place. If you use this often, just add this procedure to you shared code library. I don't like to expose it as this implementation can be changed to more up-to-date design.
