### ISSUE TITLE
[Event Request] codeunit 10861 "Payment-Apply" - OnAfterValidate #11143

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11163]
Hi, would it be possible to get an event OnAfterValidate codeunit 10861 "Payment-Apply", like this :
```
    procedure DeleteApply(Rec: Record "Payment Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeDeleteApply(Rec,CustLedgEntry,VendLedgEntry,IsHandled);
        If not IsHandled then
            exit;
        if Rec."Applies-to ID" = '' then
            exit;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteApply(Rec: Record "Payment Line";CustLedgEntry: Record "Cust. Ledger Entry";VendLedgEntry: Record "Vendor Ledger Entry"; IsHandled : Boolean)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
