### ISSUE TITLE
[Event Request] Codeunit 99000854 Inventory Profile Offsetting - OnBeforeInitSupply

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#11173]
Hi, would it be possible to get an event OnBeforeInitSupply in codeunit 99000854, procedure CreateSupply, like this : 
```
local procedure CreateSupply(var SupplyInvtProfile: Record "Inventory Profile"; var DemandInvtProfile: Record "Inventory Profile"; ProjectedInventory: Decimal; IsExceptionOrder: Boolean; RespectPlanningParm: Boolean)
    var
        ReorderQty: Decimal;
    begin
        OnBeforeInitSupply(SupplyInvtProfile,DemandInvtProfile);
        InitSupply(SupplyInvtProfile, 0, DemandInvtProfile."Due Date", DemandInvtProfile."Due Time");
        ReorderQty := DemandInvtProfile."Untracked Quantity";

```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitSupply(var SupplyInvtProfile: Record "Inventory Profile"; var DemandInvtProfile : Record "Inventory Profile")
    begin
    end;

```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
