### ISSUE TITLE
[Enum Request] table "Item" field "Price/Profit Calculation"

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#11189]
Hi al-team,

we want to extend the field "Price/Profit Calculation" (field 19) in table "Item" (table 27).
Can you change the data type in Enum?

![image](https://user-images.githubusercontent.com/48024891/108690714-f2dabe80-74fa-11eb-8e33-c242cccc8db5.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
