### ISSUE TITLE
[Event Request] Codeunit 10 "Type Helper"- OnBeforeGetField

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11187]
Hi, in the codeunit 10 "Type Helper", would it be possible to get an event OnBeforeGetField, like this :

![image](https://user-images.githubusercontent.com/76154006/108684533-4fd27680-74f3-11eb-8571-fc50cc259deb.png)

```
    procedure GetField(TableNo: Integer; FieldNo: Integer; var "Field": Record "Field"): Boolean
    var
        IsHandled: Boolean;
    begin
        IsHandled:= false;
        OnBeforeGetField(IsHandled);
        if IsHandled then
            exit;
        exit(Field.Get(TableNo, FieldNo) and (Field.ObsoleteState <> Field.ObsoleteState::Removed));
    end;


```

![image](https://user-images.githubusercontent.com/76154006/108684573-5d87fc00-74f3-11eb-82af-2810344e8f58.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetField(var IsHandled: Boolean)
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
