### ISSUE TITLE
Requet GlobalVarAccess to Integration Publisher OnBeforeSalesBatchPostMgt

### ISSUE THREAD

**Issue by pt-menon** [microsoft/ALAppExtensions#11185]
Hello,

We would like to have the event property **GlobalVarAccess**  set to true for the **Integration Publisher OnBeforeSalesBatchPostMgt** in Report 296 - Batch Post Sales Orders. 

Would this be possible ?

![image](https://user-images.githubusercontent.com/49899346/108620663-e9cfeb80-742d-11eb-851e-d4f0e66448e1.png)

**Comment by AlexanderYakunin** [comment]
We do not accept requests based on C/SIDE and C/AL code base. I see 14.x on screenshots. Please use latest code base to requests events (currently 17.x or 18.x).

FYI - this property had been discontinued long time ago.

**Comment by prat1800** [comment]
Hi AlexanderYakunin, Thank you for your response.

You mentioned that this property is discontinued long ago, but I still see it in BC 17.x

New integration event signature
![image](https://user-images.githubusercontent.com/28594745/120755613-7babc200-c50e-11eb-8c5d-66e2016fc603.png)


Report 296
![image](https://user-images.githubusercontent.com/28594745/120755661-8cf4ce80-c50e-11eb-9bf4-ef95941c3914.png)

Please could u elaborate on this? Does 'discontinued' mean that despite GlobalVarAccess = false, it will have no impact?

**Comment by AlexanderYakunin** [comment]
Since April release we do not add events to 17.x, we only do it for Master (=19.x) and 18.x. FYI - GlobalVarAcces replaced by protected attribute, you can read about this here - https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-protected-variables. 

Here is current state for this event, we can also add more parameters if needed:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesBatchPostMgt(var SalesHeader: Record "Sales Header"; var ShipReq: Boolean; var InvReq: Boolean)
    begin
    end;
