### ISSUE TITLE
request for getter or protected - page 1872 "Item Availability Check" - LocationCode

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#11181]
We want to extend this page to show various other quantities, which like the main Inventory fields on the page, must be filtered by the LocationCode received from `InitializeFrom*()`. But said variable is not `protected`, and there is no `GetLocationCode()` that we can use to get it (like e.g. `"Item Avail. by Location Lines"` provides `GetItem()` to get the `Item No.` shown).

Please add a public `GetLocationCode()` function so that page extensions can use the `LocationCode`, or perhaps even make it `protected` although that would mean it was modifiable and I personally see no need for that right now.

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
