### ISSUE TITLE
[Request-for-External] codeunit 5752 "Get Source Doc. Outbound"- OpenWarehouseShipmentPage

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11196]
Hi, I was wondering if it would be possible to change the procedure OpenWarehouseShipmentPage in Codeunit 5752 from local to external.
My team and I use this procedure a lot in our code, and changing it to external would be a huge help.
Thanks

**Comment by AlexanderYakunin** [comment]
Please explain why do you need this global? This procedure is only 2 lines, you can easily use it 

        GetSourceDocuments.GetLastShptHeader(WarehouseShipmentHeader);
        PAGE.Run(PAGE::"Warehouse Shipment", WarehouseShipmentHeader);
