### ISSUE TITLE
[Event Request] table 39 "Purchase Line" - OnBeforeInitJobFields

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#11195]
Can you extend the OnBeforeInitJobFields event with the CurrFieldNo as an integer?
**OnBeforeInitJobFields(Rec, xRec, IsHandled, CurrFieldNo );**

```
    local procedure InitJobFields()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeInitJobFields(Rec, xRec, IsHandled);
        if IsHandled then
            exit;

        if "Job No." <> xRec."Job No." then begin
            Validate("Job Task No.", '');
            Validate("Job Planning Line No.", 0);
        end;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
