### ISSUE TITLE
[Event Request] Page::"Apply Customer Entries" - Function HandleChosenEntries - OnHandleChosenEntriesOnBeforeDeleteTempAppliedCustLedgEntry

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11207]
We like to request the following Event:
Object: Page::"Apply Customer Entries"
Function: HandleChosenEntries
Publisher Event: OnHandleChosenEntriesOnBeforeDeleteTempAppliedCustLedgEntry
Reason: To implement custom business logic
Where is the event placed:
OnHandleChosenEntriesOnBeforeDeleteTempAppliedCustLedgEntry(Rec, TempAppliedCustLedgEntry, CurrencyCode);
TempAppliedCustLedgEntry.Delete();
TempAppliedCustLedgEntry.SetRange(Positive);
Event Code:
[IntegrationEvent(false, false)]
local procedure OnHandleChosenEntriesOnBeforeDeleteTempAppliedCustLedgEntry(var AppliedCustLedgEntry: Record "Cust. Ledger Entry"; TempAppliedCustLedgEntry: Record "Cust. Ledger Entry" temporary; CurrencyCode: Code[10])
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
