### ISSUE TITLE
Event Request Codeunit 80 Sales Post Function PostUpdateInvoiceLine

### ISSUE THREAD

**Issue by afrancioli** [microsoft/ALAppExtensions#11204]
In Codeunit 80 Sales Post Function PostUpdateInvoiceLine we need to override standard control between qty shipped and qty invoiced.
We suggest a new event like this:

LOCAL PostUpdateInvoiceLine()
ResetTempLines(TempSalesLine);
WITH TempSalesLine DO BEGIN
  SETFILTER("Shipment No.",'<>%1','');
  SETFILTER(Type,'<>%1',Type::" ");
  IF FINDSET THEN
    REPEAT
      SalesShptLine.GET("Shipment No.","Shipment Line No.");
      SalesOrderLine.GET(
        SalesOrderLine."Document Type"::Order,
        SalesShptLine."Order No.",SalesShptLine."Order Line No.");
      IF Type = Type::"Charge (Item)" THEN
        UpdateSalesOrderChargeAssgnt(TempSalesLine,SalesOrderLine);
      SalesOrderLine."Quantity Invoiced" += "Qty. to Invoice";
      SalesOrderLine."Qty. Invoiced (Base)" += "Qty. to Invoice (Base)";
      IF ABS(SalesOrderLine."Quantity Invoiced") > ABS(SalesOrderLine."Quantity Shipped") THEN
        ERROR(InvoiceMoreThanShippedErr,SalesOrderLine."Document No."); 
      **//Change Request Start
      IsHandled := FALSE;
      OnPostUpdateInvoiceLineBeforeCheckRounding(TempSalesLine,SalesOrderLine,SalesShptLine,IsHandled);
      IF not IsHandled THEN 
      //Change Request End**
      IF ABS(SalesOrderLine."Quantity Invoiced") > ABS(SalesOrderLine."Quantity Shipped") THEN
        ERROR(InvoiceMoreThanShippedErr,SalesOrderLine."Document No.");
      SalesOrderLine.InitQtyToInvoice;
      IF SalesOrderLine."Prepayment %" <> 0 THEN BEGIN
        SalesOrderLine."Prepmt Amt Deducted" += "Prepmt Amt to Deduct";
        SalesOrderLine."Prepmt VAT Diff. Deducted" += "Prepmt VAT Diff. to Deduct";
        DecrementPrepmtAmtInvLCY(
          TempSalesLine,SalesOrderLine."Prepmt. Amount Inv. (LCY)",SalesOrderLine."Prepmt. VAT Amount Inv. (LCY)");
        SalesOrderLine."Prepmt Amt to Deduct" :=
          SalesOrderLine."Prepmt. Amt. Inv." - SalesOrderLine."Prepmt Amt Deducted";
        SalesOrderLine."Prepmt VAT Diff. to Deduct" := 0;
      END;
      SalesOrderLine.InitOutstanding;
      SalesOrderLine.MODIFY;
.....

   Publisher event definitiion:
   
      **[Integration]
    LOCAL PROCEDURE OnPostUpdateInvoiceLineBeforeCheckRounding@1101345001(VAR TempSalesLine@1101345000 : TEMPORARY Record 37;VAR SalesOrderLine@1101345002 : Record 37;VAR SalesShptLine@1101345001 : Record 111;VAR IsHandled@1101345003 : Boolean);
    BEGIN
    END;**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
