### ISSUE TITLE
[Function Request] "Item-Check Avail." Codeunit UseOrderPromise

### ISSUE THREAD

**Issue by mynavblog** [microsoft/ALAppExtensions#11203]
Dear Team,

At this moment it is hard to extend 311 "Item-Check Avail." codeunit. The issue which I am facing at this moment is that in any way I cannot pass the the boolean to this codeunit - UseOrderPromise. Could you add the function to the codeunit which will set the UseOrderPromise. Example below:

`    procedure SetUseOrderPromise(NewUseOrderPromise: Boolean)
    begin
       UseOrderPromise :=  NewUseOrderPromise
    end;
}`

Thank you in advance

Krzysztof

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
