### ISSUE TITLE
[Event Request] Codeunit 1535 "ApprovalsMgmt." OnCreateApprReqForApprType

### ISSUE THREAD

**Issue by castordafonte** [microsoft/ALAppExtensions#11200]
<img width="462" alt="2021-02-22 16_57_08-Codeunit 1535 Approvals Mgmt  - Base Application al - BC_MMA_OP - Visual Studio " src="https://user-images.githubusercontent.com/19787321/108733985-47982c80-752f-11eb-8ebb-e70a30e1bde2.png">

We need one more statment in the function "CreateApprovalRequests" of the codeunit 1535:

> case WorkflowStepArgument."Approver Type" of 

for the extended values in enum "Workflow Approver Type".
Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
