### ISSUE TITLE
[Request-for-external] Codeunit 80 Sales Post - FillInvoicePostingBuffer

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11202]
Hi, I was wondering if it would be possible to change the procedure FillInvoicePostingBuffer in Codeunit 80 from local to external.
My team and I use this procedure a lot in our code, and changing it to external would be a huge help.

Thanks for your work, have a nice day

**Comment by AlexanderYakunin** [comment]
Let me inform you that we implement external changes in next version only, so it will not be available for 17.x or 18.x. We plan do refactor this implementation to make it extendable in 19.x, therefore we cannot make it external right now.
