### ISSUE TITLE
[Event Change] Codeunit::"Assembly Line Management" - Function AddBOMLine - OnAddBOMLineAfterValidatedNo

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11209]
We like to request the following Event:
Object: Codeunit::"Assembly Line Management"
Function: AddBOMLine 
Publisher Event: OnAddBOMLineAfterValidatedNo
Reason: To implement custom business logic
Where is the event placed:
AssemblyLine.Validate(Type, BOMComponent.Type);
AssemblyLine.Validate("No.", BOMComponent."No.");
OnAddBOMLineAfterValidatedNo(AssemblyHeader, AssemblyLine, BOMComponent);
if AssemblyLine.Type = AssemblyLine.Type::Resource then
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAddBOMLineAfterValidatedNo(AssemblyHeader: Record "Assembly Header"; var AssemblyLine: Record "Assembly Line"; BOMComponent: Record "BOM Component")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
