### ISSUE TITLE
[Event Request] Database::"Assembly Line" - Function "Quantity per" - OnValidate - OnValidateQuantityperOnAfterRoundQty

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11208]
We like to request the following Event:
Object: Database::"Assembly Line"
Function: "Quantity per" - OnValidate
Publisher Event: OnValidateQuantityperOnAfterRoundQty
Reason: To implement custom business logic
Where is the event placed:
RoundQty("Quantity per");
OnValidateQuantityperOnAfterRoundQty(Rec);
GetHeader;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnValidateQuantityperOnAfterRoundQty(var AssemblyLine: Record "Assembly Line");
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
