### ISSUE TITLE
[Event Request] Table 5404 (Item unit of Measure) in Function CalcCubage() 

### ISSUE THREAD

**Issue by Delbast** [microsoft/ALAppExtensions#11205]
Dear Team,

We would like to have a publisher in the following piece of the function. We need this to bypass the calculation of the cubage.

```C
local procedure CalcCubage()
begin
 //Start New Event	
  OnBeforeCalcCubage(Rec,xRec,Handled);
  if handled then 
    exit;
  // Stop New Event
  Cubage := Length * Width * Height;

  OnAfterCalcCubage(Rec);
end;
```
```C
[IntegrationEvent(false, false)]
local procedure OnBeforeCalcCubage(var ItemUnitOfMeasure: Record "Item Unit of Measure"; var xItemUnitOfMeasure: record "Item Unit of Measure"; var Handled: boolean)
 begin
 end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
