### ISSUE TITLE
[Event Request] codeunit 5870 "Calculate BOM Tree" - OnBeforeTempItem

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11201]
Hi, would it be possible to get an event OnBeforeTempItem codeunit 5870 "Calculate BOM Tree", like this :
```
                    TempItemAvailByDate."Variant Code" := "Variant Code";
                    if LocationSpecific then
                        TempItemAvailByDate."Location Code" := "Location Code";

                    Clear(AvailableToPromise);
                    OnBeforeTempItem(BOMItem);
                    TempItemAvailByDate."Available Qty" :=
                      AvailableToPromise.QtyAvailabletoPromise(BOMItem, "Gross Requirement", "Scheduled Receipts", "Needed by Date", 0, ZeroDF);
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTempItem(BOMItem: Record Item)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
