### ISSUE TITLE
[Event Request] Codeunit::"Correct Posted Sales Invoice" - Function UnapplyCostApplication - OnBeforeUnApplyCostApplication

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11219]
We like to request the following Event:
Object: Codeunit::"Correct Posted Sales Invoice"
Function: UnapplyCostApplication
Publisher Event: OnBeforeUnApplyCostApplication
Reason: To implement custom business logic
Where is the event placed:
IsHandled: Boolean;
begin
IsHandled := false;
OnBeforeUnApplyCostApplication(InvNo, IsHandled);
if IsHandled then
exit;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeUnApplyCostApplication(InvNo: Code[20]; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
