### ISSUE TITLE
[Event Change] Codeunit::"Copy Document Mgt." - Function CopySalesShptLinesToDoc - OnAfterCopySalesLineFromSalesShptLineBuffer

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11218]
We like to request the following Event:
Object: Codeunit::"Copy Document Mgt."
Function: CopySalesShptLinesToDoc
Publisher Event: OnAfterCopySalesLineFromSalesLineBuffer
Reason: add an extra Parameter
Where is the event placed:
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterCopySalesLineFromSalesShptLineBuffer(var ToSalesLine: Record "Sales Line"; FromSalesInvLine: Record "Sales Invoice Line"; IncludeHeader: Boolean; RecalculateLines: Boolean; var TempDocSalesLine: Record "Sales Line" temporary; ToSalesHeader: Record "Sales Header"; FromSalesLineBuf: Record "Sales Line"; var FromSalesLine2: Record "Sales Line"; FromSalesLine: Record "Sales Line"; ExactCostRevMandatory: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
