### ISSUE TITLE
[Event Request] Codeunit::"Copy Document Mgt." - Function IsSplitItemLedgEntry - OnIsSplitItemLedgEntryOnFilter

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11215]
We like to request the following Event:
Object: Codeunit::"Copy Document Mgt."
Function: IsSplitItemLedgEntry
Publisher Event: OnIsSplitItemLedgEntryOnFilter
Reason: To implement custom business logic
Where is the event placed:
ItemLedgEntry.SetRange("Serial No.", "Serial No.");
ItemLedgEntry.SetFilter("Entry No.", '<%1', "Entry No.");
OnIsSplitItemLedgEntryOnFilter(ItemLedgEntry, OrgItemLedgEntry);
exit(not ItemLedgEntry.IsEmpty);
end;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnIsSplitItemLedgEntryOnFilter(var ItemLedgEntry: Record "Item Ledger Entry"; OrgItemLedgEntry: Record "Item Ledger Entry")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
