### ISSUE TITLE
[Event Change] Report::"Calculate Inventory Value" - Function Item - OnAfterGetRecord - OnItemAfterGetRecordOnAfterItemLedgEntrySetFilters

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11211]
We like to request the following Event:
Object: Report::"Calculate Inventory Value"
Function: Item - OnAfterGetRecord
Publisher Event: OnItemAfterGetRecordOnAfterItemLedgEntrySetFilters
Reason: add an extra Parameter
Where is the event placed:
Event Code:
[IntegrationEvent(false, false)]
local procedure OnItemAfterGetRecordOnAfterItemLedgEntrySetFilters(var Item: Record Item; var ItemLedgerEntry: Record "Item Ledger Entry")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
