### ISSUE TITLE
[Event Request] Codeunit::"Copy Document Mgt." - Function CreateToAsmLines - OnAfterModifyToAssemblyLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11214]
We like to request the following Event:
Object: Codeunit::"Copy Document Mgt."
Function: CreateToAsmLines
Publisher Event: OnAfterModifyToAssemblyLine
Reason: To implement custom business logic
Where is the event placed:
CopyFromAsmOrderDimToLine(ToAssemblyLine, FromAsmLine, BasicAsmOrderCopy);
OnCreateToAsmLinesOnBeforeToAssemblyLineModify(ToAsmHeader, ToAssemblyLine, FromAsmLine, ToSalesLine, BasicAsmOrderCopy, AvailabilityCheck);
ToAssemblyLine.Modify(not AvailabilityCheck);
OnAfterModifyToAssemblyLine(ToAsmHeader, FromAsmLine, ToAssemblyLine, ToSalesLine, BasicAsmOrderCopy, AvailabilityCheck);
until FromAsmLine.Next = 0;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterModifyToAssemblyLine(ToAsmHeader: Record "Assembly Header"; var FromAsmLine: Record "Assembly Line"; var ToAssemblyLine: Record "Assembly Line"; ToSalesLine: Record "Sales Line"; BasicAsmOrderCopy: Boolean; AvailabilityCheck: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
