### ISSUE TITLE
[Event Request] Database::"BOM Buffer" - Function GetItemCosts - OnAfterGetItemCost

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11210]
We like to request the following Event:
Object: Database::"BOM Buffer"
Function: GetItemCosts
Publisher Event: OnAfterGetItemCost
Reason: To implement custom business logic
Where is the event placed:
if "Qty. per Top Item" <> 0 then
"Rolled-up Scrap Cost" := "Rolled-up Material Cost" * "Scrap Qty. per Top Item" / "Qty. per Top Item";
RoundCosts(UOMMgt.GetQtyPerUnitOfMeasure(Item, "Unit of Measure Code") * "Qty. per Top Item");
OnAfterGetItemCost(Rec);
end;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterGetItemCost(var BOMBuffer: Record "BOM Buffer")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
