### ISSUE TITLE
[Event Request] Codeunit::"Carry Out Action" - Function InsertProdOrderLine - OnBeforeTransferInsertProdOrderLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11212]
We like to request the following Event:
Object: Codeunit::"Carry Out Action"
Function: InsertProdOrderLine
Publisher Event: OnBeforeTransferInsertProdOrderLine
Reason: To implement custom business logic
Where is the event placed:
ProdOrderLine.Modify();
IsHandled := false;
OnBeforeTransferInsertProdOrderLine(ProdOrderLine, ReqLine, ProdOrder, Item, IsHandled);
if not IsHandled then begin
SetProdOrderLineBinCodeFromPlanningRtngLines(ProdOrder, ProdOrderLine, ReqLine, Item);
TransferBOM(ReqLine, ProdOrder, ProdOrderLine."Line No.");
TransferCapNeed(ReqLine, ProdOrder, ProdOrderLine."Routing No.", ProdOrderLine."Routing Reference No.");
end;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeTransferInsertProdOrderLine(var ProdOrderLine: Record "Prod. Order Line"; ReqLine: Record "Requisition Line"; ProdOrder: Record "Production Order"; Item: Record Item; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
