### ISSUE TITLE
[Event Request] Database::Customer - Function GetCustNoOpenCard - OnGetCustNoOpenCardOnAfterCustomerFilterFromStart

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11226]
We like to request the following Event:
Object: Database::Customer
Function: GetCustNoOpenCard
Publisher Event: OnGetCustNoOpenCardOnAfterCustomerFilterFromStart
Reason: To implement custom business logic
Where is the event placed:
Customer.SetFilter(Name, CustomerFilterFromStart);
OnGetCustNoOpenCardOnAfterCustomerFilterFromStart(Customer);
if Customer.FindFirst then
exit(Customer."No.");
Event Code:
[IntegrationEvent(false, false)]
local OnGetCustNoOpenCardOnAfterCustomerFilterFromStart(var Customer: Record Customer)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
