### ISSUE TITLE
[Event Request] Codeunit 5987 Serv-Posting Journals Mgt.: OnBeforePostCustomerEntry - Add Parameters

### ISSUE THREAD

**Issue by tinestaric** [microsoft/ALAppExtensions#11220]
Hey,

we would need an additional parameter on the OnBeforePostCustomerEntry of type Codeunit "Gen. Jnl.-Post Line" that is passed on by reference.

Ideally both the OnBeforePostCustomerEntry and OnAfterPostCustomerEntry in the "Serv-Posting Journals Mgt." Codeunit would behave exactly the same to their Sales and Purchase posting counterparts:

Sales:

     [IntegrationEvent(false, false)]
    local procedure OnBeforePostCustomerEntry(var GenJnlLine: Record "Gen. Journal Line"; var SalesHeader: Record "Sales Header"; var TotalSalesLine: Record "Sales Line"; var TotalSalesLineLCY: Record "Sales Line"; CommitIsSuppressed: Boolean; PreviewMode: Boolean; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterPostCustomerEntry(var GenJnlLine: Record "Gen. Journal Line"; var SalesHeader: Record "Sales Header"; var TotalSalesLine: Record "Sales Line"; var TotalSalesLineLCY: Record "Sales Line"; CommitIsSuppressed: Boolean; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line")
    begin
    end;

Thank you.

Regards,
Tine

**Comment by RomanZanizdra** [comment]
@tinestaric , what did you mean saying "Codeunit would behave exactly the same to their Sales and Purchase posting counterparts:"? I didn't find similar events for purchase side.

**Comment by tinestaric** [comment]
@RomanZanizdra In the Codeunit 90 Purch.-Post we have the same set of events OnBeforePostVendorEntry and OnAfterPostVendorEntry that have the same set of Parameters (with the Header and Lines of course pointing to the Purchase records) as the events on the Sales side. 

The request is about having the same logic on the Service posting codeunit.

Purchase side Events

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostVendorEntry(var GenJnlLine: Record "Gen. Journal Line"; var PurchHeader: Record "Purchase Header"; var TotalPurchLine: Record "Purchase Line"; var TotalPurchLineLCY: Record "Purchase Line"; PreviewMode: Boolean; CommitIsSupressed: Boolean; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterPostVendorEntry(var GenJnlLine: Record "Gen. Journal Line"; var PurchHeader: Record "Purchase Header"; var TotalPurchLine: Record "Purchase Line"; var TotalPurchLineLCY: Record "Purchase Line"; CommitIsSupressed: Boolean; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line")
    begin
    end;

**Comment by tinestaric** [comment]
here are the Service OnBeforePostCustomerEntry and OnAfterPostCustomerEntry
As seen, they each lack certain parameters that are present on the Sales and Purchase equivalents:

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostCustomerEntry(var GenJournalLine: Record "Gen. Journal Line"; ServiceHeader: Record "Service Header"; var TotalServiceLine: Record "Service Line")
    begin
    end;

    local procedure OnAfterPostCustomerEntry(var GenJournalLine: Record "Gen. Journal Line"; var ServiceHeader: Record "Service Header"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
