### ISSUE TITLE
[Event Change] Codeunit::"Create Pick" - Function SetWhseShipment - OnAfterSetWhseShipment

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11223]
We like to request the following Event:
Object: Codeunit::"Create Pick"
Function: SetWhseShipment
Publisher Event: OnAfterSetWhseShipment
Reason: add an extra Parameter
Where is the event placed:
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterSetWhseShipment(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; TempNo2: Integer; ShippingAgentCode2: Code[10]; ShippingAgentServiceCode2: Code[10]; ShipmentMethodCode2: Code[10])
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
