### ISSUE TITLE
[Event Request] Codeunit::"Dimension Buffer Management" - Function InsertDimensionsUsingEntryNo - OnBeforeInsertTempDimBuf

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11227]
We like to request the following Event:
Object: Codeunit::"Dimension Buffer Management"
Function: InsertDimensionsUsingEntryNo
Publisher Event: OnBeforeInsertTempDimBuf
Reason: To implement custom business logic
Where is the event placed:
if DimBuf.Find('-') then
repeat
IsHandled := false;
OnBeforeInsertTempDimBuf(TempDimBuf, DimBuf, EntryNo, IsHandled);
if not IsHandled then begin
TempDimBuf.Init();
TempDimBuf := DimBuf;
TempDimBuf."Entry No." := EntryNo;
TempDimBuf."No. Of Dimensions" := DimCount;
TempDimBuf.Insert();
end;
until DimBuf.Next = 0;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertTempDimBuf(var TempDimBuf: Record "Dimension Buffer"; var DimBuf: Record "Dimension Buffer"; EntryNo: Integer; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
