### ISSUE TITLE
[Event Change] Codeunit::"Create Pick" - Function CalcPickBin - OnBeforeCalcPickBin

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11224]
We like to request the following Event:
Object: Codeunit::"Create Pick"
Function: CalcPickBin 
Publisher Event: OnBeforeCalcPickBin
Reason: add an extra Parameter
Where is the event placed:
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeCalcPickBin(var TempWarehouseActivityLine: Record "Warehouse Activity Line" temporary; var TotalQtytoPick: Decimal; var TotalQtytoPickBase: Decimal; var TempWhseItemTrackingLine: Record "Whse. Item Tracking Line" temporary; CrossDock: Boolean; WhseTrackingExists: Boolean; WhseSource: Option "Pick Worksheet",Shipment,"Movement Worksheet","Internal Pick",Production,Assembly; LocationCode: Code[10]; ItemNo: Code[20]; VariantCode: Code[10]; UnitofMeasureCode: Code[10]; ToBinCode: Code[20]; QtyPerUnitofMeasure: Decimal; var IsHandled: Boolean)
begin
end;

**Comment by RomanZanizdra** [comment]
Hi @acadonAG-dev . 
Do you want just exit from the procedure by "IsHandled" pattern or other action?

**Comment by acadonAG-dev** [comment]
Hello @RomanZanizdra.
Correct, just the possibility to handle the procedure completely.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
