### ISSUE TITLE
[Event Change] Database::"Finance Charge Memo Line" - Function CalcFinChrg - OnBeforeCalcFinCharge

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11228]
We like to request the following Event:
Object: Database::"Finance Charge Memo Line"
Function: CalcFinChrg
Publisher Event: OnBeforeCalcFinCharge
Reason: add an extra Parameter
Where is the event placed:
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeCalcFinCharge(var FinanceChargeMemoLine: Record "Finance Charge Memo Line"; var FinanceChargeMemoHeader: Record "Finance Charge Memo Header"; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
