### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnValidatePayToVendorNoOnBeforeGetPayToVend

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11238]
Hello. In table 38 purchase Header, in the field 4 "Pay-to Vendor No.", in trigger OnValidate, I would like to make a test in the event publisher OnValidatePayToVendorNoOnBeforeGetPayToVend on Rec and xRec. If this test is not passed, I would like to exit the OnValidate trigger. To do so, I would need xRec and a IsHandled flag in the event publisher, like this : 

                OnValidatePayToVendorNoOnBeforeGetPayToVend(Rec, xRec, IsHandled);
                if IsHandled then 
                    exit;
                GetVend("Pay-to Vendor No.");
                CheckBlockedVendOnDocs(Vend);
                Vend.TestField("Vendor Posting Group");
                PostingSetupMgt.CheckVendPostingGroupPayablesAccount("Vendor Posting Group");
                OnAfterCheckPayToVendor(Rec, xRec, Vend);

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnValidatePayToVendorNoOnBeforeGetPayToVend(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader : record "Purchase Header"; var IsHandled : Boolean)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by StanPesotskiy** [comment]
Can you use the existing event OnBeforeValidatePayToVendorNo?

**Comment by Magicrevette** [comment]
Indeed, I can and I will. Thank you for your help.
