### ISSUE TITLE
[Event Request] codeunit 6620 "Copy Document Mgt." - OnBeforeUpdatePurchCreditMemoHeader

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11237]
Hi, would it be possible to get an event OnBeforeUpdatePurchCreditMemoHeader codeunit 6620 "Copy Document Mgt.", like this :
```
            else
                Clear(PaymentTerms);
            if not PaymentTerms."Calc. Pmt. Disc. on Cr. Memos" then begin
                OnBeforeUpdatePurchCreditMemoHeader(PurchaseHeader);
                "Payment Discount %" := 0;
                "Pmt. Discount Date" := 0D;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdatePurchCreditMemoHeader(PurchaseHeader: Record "Purchase Header")
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
