### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnValidatePayToVendorNoOnBeforeRecallModifyAddressNotification

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11245]
Hello. In table 38 purchase Header, in the field 4 "Pay-to Vendor No.", in trigger OnValidate, I would like to add my own code in the event OnValidatePayToVendorNoOnBeforeRecallModifyAddressNotification and use in the subscriber the xRec and the Vend record. To do so, I would need xRec and Vend parameters in the event publisher, like this :

        field(4; "Pay-to Vendor No."; Code[20])
        {
            trigger OnValidate()
            begin
                ...
                OnValidatePayToVendorNoOnBeforeRecallModifyAddressNotification(Rec, xRec, Vend);
                if (xRec."Pay-to Vendor No." <> '') and (xRec."Pay-to Vendor No." <> "Pay-to Vendor No.") then
                    RecallModifyAddressNotification(GetModifyPayToVendorAddressNotificationId);
            end;
        }

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnValidatePayToVendorNoOnBeforeRecallModifyAddressNotification(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader: Record "Purchase Header"; Vendor: Record Vendor)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
