### ISSUE TITLE
[Request-for-external] Codeunit 6620 "Copy Document Mgt."- CheckItemAvailability

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11244]
Hi, I was wondering if it would be possible to change the procedure CheckItemAvailability in Codeunit 6620 "Copy Document Mgt." from local to external.
My team and I use this procedure a lot in our code, and changing it to external would be a huge help.
Thanks

**Comment by AlexanderYakunin** [comment]
This procedure use global variables therefore we cannot expose it.
