### ISSUE TITLE
Change Event Behavior On Service Header - Customer No. - OnValidate

### ISSUE THREAD

**Issue by dharma534** [microsoft/ALAppExtensions#11247]
Dear Team,

When customer no. changing to different value from Service Quote page, then system used to delete service item line (if not blank). this is default behavior for all NAV versions but it not working under BC version. 

Below is the confirm message when customer no. changing to different value.

*When you change the Customer No. the existing Service item line and service line will be deleted.
Do you want to change the Customer No.?* 

After choosing 'Yes' to continue but service item line not deleting.

Find some event added before deleting service item line
T5900 (Service Header)-->Customer No. - OnValidate()

```
IsHandled := false;
OnValidateCustomerNoOnBeforeDeleteLines(Rec, IsHandled);
if IsHandled then begin
      ServLine.LockTable();
      ServLine.Reset();
      ServLine.SetRange("Document Type", "Document Type");
      ServLine.SetRange("Document No.", "No.");
      ServLine.DeleteAll(true);*

      ServItemLine.LockTable();
      ServItemLine.Reset();
      ServItemLine.SetRange("Document Type", "Document Type");
      ServItemLine.SetRange("Document No.", "No.");
      ServItemLine.DeleteAll(true);
end
```

I checked above code and understood IsHandled blocking service item line deletion loop. To make this possible, can you please make `IsHandled` variable to true 

```
IsHandled := true;
OnValidateCustomerNoOnBeforeDeleteLines(Rec, IsHandled);
if IsHandled then begin
```

**Comment by AlexanderYakunin** [comment]
Thanks, it should be **if NOT IsHandled**. We will correct it.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
