### ISSUE TITLE
[Enum Request] Table 263 "Intrastat Jnl. Line" - Field "Source Type"

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#11248]
Hi,
Could you please change field 11 (**Source Type**) of table 263 (**Intrastat Jnl. Line**) from option to enum?
```AL
        field(11; "Source Type"; Option)
        {
            BlankZero = true;
            Caption = 'Source Type';
            OptionCaption = ',Item Entry,Job Entry';
            OptionMembers = ,"Item Entry","Job Entry";
            trigger OnValidate()
            begin
                if Type = Type::Shipment then begin
                    "Country/Region of Origin Code" := GetCountryOfOriginCode();
                    "Partner VAT ID" := GetPartnerID();
                end;
            end;
        }
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
