### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnValidatePurchaseHeaderPayToVendorNo

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11242]
Hello. In table 38 purchase Header, in the field 4 "Pay-to Vendor No.", in trigger OnValidate, I would like to add my own code in the event OnValidatePurchaseHeaderPayToVendorNo and use in the subscriber the xRec. To do so, I would need xRec parameter in the event publisher, like this :

                "Prices Including VAT" := Vend."Prices Including VAT";
                "Currency Code" := Vend."Currency Code";
                "Invoice Disc. Code" := Vend."Invoice Disc. Code";
                "Language Code" := Vend."Language Code";
                SetPurchaserCode(Vend."Purchaser Code", "Purchaser Code");
                Validate("Payment Terms Code");
                Validate("Prepmt. Payment Terms Code");
                Validate("Payment Method Code");
                Validate("Currency Code");
                Validate("Creditor No.", Vend."Creditor No.");

                OnValidatePurchaseHeaderPayToVendorNo(Vend, Rec, xRec);

With this event publisher : 

    [IntegrationEvent(TRUE, false)]
    procedure OnValidatePurchaseHeaderPayToVendorNo(Vendor: Record Vendor; var PurchaseHeader: Record "Purchase Header"; var xPurchaseHeader: Record "Purchase Header")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
