### ISSUE TITLE
Price Calculation Request

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#11249]
Hello, our company prepare NAV addon to BC cloud version for app source. Do we need rewrite sales prices to price calculation?
Because in many places of the standard code, sales prices have not even been rewritten. Price Calculation Setup is absent. I can enable Price Calculation only with using code (Set boolean to TRUE).

Sorry, I didn`t find any repo where I can ask this question.
If I made a mistake with the repository, please tell me where I can ask this question, since the question is quite serious and concerns App Source.

**Comment by AlexanderYakunin** [comment]
@StanPesotskiy - please help

**Comment by StanPesotskiy** [comment]
To see the new UX you have to enable the feature in the feature management page:
![image](https://user-images.githubusercontent.com/41332028/109476698-3f3c7600-7a88-11eb-9af2-2018dbd25d3b.png)

**Comment by JesperSchulz** [comment]
Hoping Stan's answer did the trick :-) Closing this issue. If the issue persists, please reopen.
