### ISSUE TITLE
[Event Request] codeunit 6620 "Copy Document Mgt."- OnAfterSalesToPurchLine

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11253]
Hi, would it be possible to get an event OnAfterSalesToPurchLine codeunit 6620 "Copy Document Mgt.", like this :
```
    procedure TransfldsFromSalesToPurchLine(var FromSalesLine: Record "Sales Line"; var ToPurchLine: Record "Purchase Line")
    var
        DimMgt: Codeunit DimensionManagement;
        DimensionSetIDArr: array[10] of Integer;
        IsHandled: Boolean;
```
```
                Validate(Quantity, FromSalesLine."Outstanding Quantity");
            Validate("Return Reason Code", FromSalesLine."Return Reason Code");
            Validate("Direct Unit Cost");
            Description := FromSalesLine.Description;
            "Description 2" := FromSalesLine."Description 2";
            IsHandled:= false;
            OnAfterSalesToPurchLine(FromSalesLine);
            if not IsHandled then
                exit;
            if "Dimension Set ID" <> FromS
```
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSalesToPurchLine(var FromSalesLine: Record "Sales Line")
    begin
    end;
```
Thanks!

**Comment by RomanZanizdra** [comment]
Hi @Pepito-lab . The event by itself and its' processing looks strange. Why do you need to exit there, you don't need dimension set or what? Is it ok if we add "IsHandled->exit" pattern in the beginning of the procedure and you will be able to process it how you want?

**Comment by RomanZanizdra** [comment]
@Pepito-lab , any update from your side?

**Comment by RomanZanizdra** [comment]
Closed by mistake, missed button control.

**Comment by RomanZanizdra** [comment]
@Pepito-lab , let's close this request for now. Feel free to reopen it when you will have the possibility to provide the answer.

**Comment by Pepito-lab** [comment]
Hi, we need to exit here because we didn't use the rest of the procedure and we need to add our code. Thank you.

**Comment by RomanZanizdra** [comment]
Please open a new request if still need event.
