### ISSUE TITLE
[Event Request] codeunit 6620 "Copy Document Mgt."- OnBeforeCopyPurchPostedDeferralsModify

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11259]
Hi, would it be possible to get an event OnBeforeCopyPurchPostedDeferralsModify codeunit 6620 "Copy Document Mgt.", like this :
![image](https://user-images.githubusercontent.com/76154006/108986888-f0ab6800-7692-11eb-9637-51a4b440e802.png)
```
    local procedure CopyPurchPostedDeferrals(ToPurchaseLine: Record "Purchase Line"; DeferralDocType: Enum "Deferral Document Type"; FromDocType: Integer; FromDocNo: Code[20]; FromLineNo: Integer; ToDocType: Integer; ToDocNo: Code[20]; ToLineNo: Integer)
    var
    IsHandled: Boolean;
    begin
        ToPurchaseLine."Returns Deferral Start Date" :=
            CopyPostedDeferrals(
                DeferralDocType, FromDocType, FromDocNo, FromLineNo, ToDocType, ToDocNo, ToLineNo);
        IsHandled:= false;
        OnBeforeCopyPurchPostedDeferralsModify(ToPurchaseLine, IsHandled);
        if not IsHandled then
        ToPurchaseLine.Modify();
    end;

```
![image](https://user-images.githubusercontent.com/76154006/108986945-015bde00-7693-11eb-94e7-e47c5524abd3.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCopyPurchPostedDeferralsModify(var ToPurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
