### ISSUE TITLE
[Event Request] codeunit 6620 "Copy Document Mgt."- OnAfterCopySalesDocLine

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11258]
Hi, would it be possible to get an event OnAfterCopySalesDocLine codeunit 6620 "Copy Document Mgt.", like this :
```
            then begin
                InvDiscountAmount := ToSalesLine."Inv. Discount Amount";
                ToSalesLine.Validate("Line Discount %");
                IsHandled:= true;
                OnAfterCopySalesDocLine(IsHandled);
                if not IsHandled then
                    ToSalesLine.Validate("Inv. Discount Amount", InvDiscountAmount);
            end;
        end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCopySalesDocLine(IsHandled: Boolean)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
