### ISSUE TITLE
[Extensibility Enhancement] Table 5741 "Transfer Line" –  TestStatusOpen

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#1125]
Can we please have a „StatusCheckSuspended“ functionality as an exit criterion for TestStatusOpen Table 5741 "Transfer Line"?

```
LOCAL TestStatusOpen()
// >>>>>>>>
IF StatusCheckSuspended THEN BEGIN
  EXIT;
END;
// <<<<<<<<

TESTFIELD("Document No.");
IF TransHeader."No." <> "Document No." THEN
  TransHeader.GET("Document No.");
TransHeader.TESTFIELD(Status,TransHeader.Status::Open);

// >>>>>>>>
SuspendStatusCheck(Suspend : Boolean)
StatusCheckSuspended := Suspend;
// <<<<<<<<
```

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
