### ISSUE TITLE
[Request-For-External] Table 38 "Purchase Header" - Variable StatusCheckSuspended

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#11257]
Hi, could you please make the value of the global variable **SuspendStatusCheck** available with a getter in table 38 (**Purchase Header**), like this:
```AL
    procedure GetStatusCheckSuspended(): Boolean
    begin
        exit(StatusCheckSuspended);
    end;
```
Also, maybe it makes sense to add the **protected** keyword to the **SuspendStatusCheck**  variable.

_Note_: both of these changes are already added to table 36 (**Sales Header**), table 37 (**Sales Line**), table 39 (**Purchase Line**). Just one difference between headers and lines is the procedure name (in lines it is called **GetSuspendedStatusCheck**).
#6310

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
