### ISSUE TITLE
[Event Request] Table 5050 Contact - OnBeforeCreateBankAccount, OnAfterCreateBankAccount

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#11251]
Hi, would it be possible to get **OnBeforeCreateBankAccount**, **OnAfterCreateBankAccount** events in table 5050 (**Contact**), like this (similar to events in the **CreateVendor**, **CreateCustomer** procedures):
```AL
    procedure CreateBankAccount() BankAccountNo: Code[20];
    var
        BankAcc: Record "Bank Account";
        ContComp: Record Contact;
        ContBusRel: Record "Contact Business Relation";
        IsHandled: Boolean;
    begin
        // New Event begin
        IsHandled := false;
        OnBeforeCreateBankAccount(Rec, BankAccountNo, IsHandled);
        if IsHandled then
            exit;
        // New Event end

        TestField("Company No.");
        RMSetup.Get();
        RMSetup.TestField("Bus. Rel. Code for Bank Accs.");

        Clear(BankAcc);
        BankAcc.SetInsertFromContact(true);
        OnBeforeBankAccountInsert(BankAcc);
        BankAcc.Insert(true);
        BankAccountNo := BankAcc."No.";
        BankAcc.SetInsertFromContact(false);

        if Type = Type::Company then
            ContComp := Rec
        else
            ContComp.Get("Company No.");

        ContBusRel."Contact No." := ContComp."No.";
        ContBusRel."Business Relation Code" := RMSetup."Bus. Rel. Code for Bank Accs.";
        ContBusRel."Link to Table" := ContBusRel."Link to Table"::"Bank Account";
        ContBusRel."No." := BankAcc."No.";
        ContBusRel.Insert(true);

        CheckIfPrivacyBlockedGeneric;

        UpdateCustVendBank.UpdateBankAccount(ContComp, ContBusRel);

        if not HideValidationDialog then
            Message(RelatedRecordIsCreatedMsg, BankAcc.TableCaption);

        OnAfterCreateBankAccount(Rec, BankAcc);  // New Event
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateBankAccount(var Contact: Record Contact; var BankAccountNo: Code[20]; var IsHandled: Boolean);
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCreateBankAccount(var Contact: Record Contact; var BankAccount: Record "Bank Account");
    begin
    end;
```
Thanks!

**Comment by pri-kise** [comment]
Do you really want to suppress the execution of the OnAfterCreateBankAccount Event if someone did set the `Handled` of the OnBeforeEvent?

**Comment by AndriiSeverin** [comment]
We are not going to use **IsHandled** for our current functional case. The most important thing for us to have **OnBeforeCreateBankAccount**, **OnAfterCreateBankAccount** events with **Rec** passed using **var**. 
However, to make events more generic and similar to events in other standard procedures (such **CreateVendor**, **CreateCustomer**) we suggest the mentioned procedure declaration. We think that it will not cause any issues with that as there is already the same logic in other procedures.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
