### ISSUE TITLE
[Event Request] Table 9053 "Sales Cue", OnBeforeResponsibilityCenterFilter

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#11269]
Hello, in Table 9053 Function SetRespCenterFilter an event (OnBeforeResponsibilityCenterFilter), with IsHandle return, is required. 

procedure SetRespCenterFilter()
  var
      UserSetupMgt: Codeunit "User Setup Management";
      RespCenterCode: Code[10];
  begin
      RespCenterCode := UserSetupMgt.GetSalesFilter;
      **OnBeforeResponsibilityCenterFilter()**
      if RespCenterCode <> '' then begin
          FilterGroup(2);
          SetRange("Responsibility Center Filter", RespCenterCode);
          FilterGroup(0);
      end;
  end;

**Comment by SteinleMossWahlers** [comment]
The event must offer the possibility to change the filter (SetRange ("Responsibility Center Filter")).

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
