### ISSUE TITLE
[Request-for-external] Codeunit 6620 "Copy Document Mgt."- HandleAsmAttachedToSalesLine

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11264]
Hi, I was wondering if it would be possible to change the procedure HandleAsmAttachedToSalesLine in Codeunit 6620 "Copy Document Mgt." from local to external.
My team and I use this procedure a lot in our code, and changing it to external would be a huge help.
Thanks

**Comment by AlexanderYakunin** [comment]
Please explain how you us it? This procedure use several global variables.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
