### ISSUE TITLE
Parameter Request: Please add ServiceLineACY to IntegrationEvent OnAfterFillInvoicePostBuffer in Codeunit "Serv-Amounts Mgt."

### ISSUE THREAD

**Issue by CL2-SWECON** [microsoft/ALAppExtensions#11265]
Current signature: OnAfterFillInvoicePostBuffer(var InvoicePostBuffer: Record "Invoice Post. Buffer"; ServiceLine: Record "Service Line"; var TempInvoicePostBuffer: Record "Invoice Post. Buffer"; SuppressCommit: Boolean)

Needed signature: OnAfterFillInvoicePostBuffer(var InvoicePostBuffer: Record "Invoice Post. Buffer"; ServiceLine: Record "Service Line"; ServiceLineACY: Record "Service Line"; var TempInvoicePostBuffer: Record "Invoice Post. Buffer"; SuppressCommit: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
