### ISSUE TITLE
[Event Request] table 38 "Purchase Header" OnBeforeRecreatePurchLinesHandler

### ISSUE THREAD

**Issue by laurbag** [microsoft/ALAppExtensions#11262]
Hello,
Could you please add a new event called OnBeforeRecreatePurchLinesHandler into table 38 "Purchase Header" at the beginning of the RecreatePurchLines procedure.
If possible, could it be done with the same logic as the OnBeforeRecreateSalesLinesHandler event in RecreateSalesLines procedure from table 36 "Sales Header"?

```
IsHandled := false;
OnBeforeRecreatePurchLinesHandler(Rec, xRec, ChangedFieldName, IsHandled);
if IsHandled then
     exit;
```

**Comment by StanPesotskiy** [comment]
Already exists:
```
    procedure RecreatePurchLines(ChangedFieldName: Text[100])
...
    begin
        if not PurchLinesExist() then
            exit;

        IsHandled := false;
        OnBeforeRecreatePurchLinesHandler(Rec, xRec, ChangedFieldName, IsHandled);
        if IsHandled then
            exit;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
