### ISSUE TITLE
[Request for External] Codeunit 99000773 Calculate Prod. Order - TransferBOM

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#11277]
Hi, would it be possible to modify TransferBOM in codeunit 99000773 from local to external ?
We are trying to deal with the call to TransferBOM within the TransferBOM procedure in an event subscriber, an having the procedure TransferBOM as an external would really help us to achieve that.

Thanks

**Comment by AlexanderYakunin** [comment]
Can you please explain with the code what you are going to achieve? This is clearly internal procedure with references to other global variables.

**Comment by VMotin** [comment]
I'm not sure what would be the best way to handle what i'm trying to do. I want to modify the code in the TransferBom procedure, but the code I'm trying to add in TransferBom calls the TransferBom procedure itself. This is why i would like it as an external procedure, that way i could add it in a event.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
