### ISSUE TITLE
[Event Request] codeunit 6620 "Copy Document Mgt."- OnBeforeClearPurchLastNoSFields

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11279]
Hi, would it be possible to get an event OnBeforeClearPurchLastNoSFields codeunit 6620 "Copy Document Mgt.", like this :
```
    procedure ClearPurchLastNoSFields(var PurchaseHeader: Record "Purchase Header")
    var 
        IsHandled: Boolean;
    begin
        IsHandled:= false;
        OnBeforeClearPurchLastNoSFields(IsHandled);
        if IsHandled then
            exit;
        with PurchaseHeader do begin
            "Last Receiving No." := '';
            "Last Posting No." := '';
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeClearPurchLastNoSFields(var IsHandled: Boolean)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
