### ISSUE TITLE
[Access Request] Report 11503 - Item ABC Analysis 

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#11273]
Hi al-team,

we are checking if our app still works with the BC18 Base app. 
We have tried the new ReportExt objects and would like to have access to the following variable: 

```
    protected var
        ABC: Text[1];
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
