### ISSUE TITLE
[Event Request] Codeunit 7301 "Whse. Jnl.-Register Line" - OnUpdateDefaultBinContentOnBeforeBinContentModify

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#11285]
Hi, would it be possible to call the event **OnUpdateDefaultBinContentOnBeforeBinContentModify** in codeunit 7301 (**Whse. Jnl.-Register Line**) in front of both modifys? Currently it is only called infront the Modify of BinContent but we need it in front of the Modify of BinContent2 too, like this:

```
local procedure UpdateDefaultBinContent(ItemNo: Code[20]; VariantCode: Code[10]; LocationCode: Code[10]; BinCode: Code[20])
    var
        BinContent: Record "Bin Content";
        BinContent2: Record "Bin Content";
    begin
        BinContent.SetCurrentKey(Default);
        BinContent.SetRange(Default, true);
        BinContent.SetRange("Location Code", LocationCode);
        BinContent.SetRange("Item No.", ItemNo);
        BinContent.SetRange("Variant Code", VariantCode);
        if BinContent.FindFirst then
            if BinContent."Bin Code" <> BinCode then begin
                BinContent.Default := false;
                OnUpdateDefaultBinContentOnBeforeBinContentModify(BinContent);
                BinContent.Modify();
            end;

        if BinContent."Bin Code" <> BinCode then begin
            BinContent2.SetRange("Location Code", LocationCode);
            BinContent2.SetRange("Item No.", ItemNo);
            BinContent2.SetRange("Variant Code", VariantCode);
            BinContent2.SetRange("Bin Code", BinCode);
            BinContent2.FindFirst;
            BinContent2.Default := true;
            OnUpdateDefaultBinContentOnBeforeBinContentModify(BinContent2);
            BinContent2.Modify();
        end;
    end;
```

If this would be a problem another solution would be to get an event **OnUpdateDefaultBinContentOnBeforeBinContent2Modify** that is called like mentioned above. The parameters would be the same.
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
