### ISSUE TITLE
event request - codeunit 1327 "Adjust Item Inventory" - procedure PostMultipleAdjustmentsToItemLedger() - OnBeforeInsertItemJnlLine()

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#11289]
I'm trying to develop an Adjust Inventory page that, as well as having Locations down the rows, also has a given set of Variants along the columns. I intend to store the inventory quantities for each Location/Variant intersection in a temporary Dimension Code Amount Buffer. Then, OnQueryClosePage(), I'll convert said buffer into a set of temporary Item Journal Lines to post. I want to reuse the existing public procedures in `codeunit 1327 "Adjust Item Inventory"` for this.

However, said codeunit only copies certain fields from the `TempItemJournalLine` to its `ItemJnlLine` that actually gets posted, and `Variant Code` is not one of such fields. Equally, it doesn't use the `Variant Code` when calculating the current inventory, i.e. what to change.

Therefore, please add here:
```al
    procedure PostMultipleAdjustmentsToItemLedger(var TempItemJournalLine: Record "Item Journal Line" temporary) LastErrorText: Text
    var
        Item: Record Item;
        ItemJnlLine: Record "Item Journal Line";
        ItemTemplate: Code[10];
        ItemBatch: Code[10];
    begin
        if not TempItemJournalLine.FindSet then
            exit;

        ItemTemplate := SelectItemTemplateForAdjustment;
        ItemBatch := CreateItemBatch(ItemTemplate);

        repeat
            Item.Get(TempItemJournalLine."Item No.");
            Item.SetFilter("Location Filter", '%1', TempItemJournalLine."Location Code");

            // +NEW
            OnPostMultipleAdjustmentsToItemLedgerOnBeforeCalcItemInventory(TempItemJournalLine, Item);
            // - NEW

            Item.CalcFields(Inventory);

            if Item.Inventory <> TempItemJournalLine.Quantity then begin
                CreateItemJnlLine(ItemJnlLine, Item, ItemTemplate, ItemBatch, TempItemJournalLine.Quantity);
                ItemJnlLine.Validate("Line No.", TempItemJournalLine."Line No.");
                ItemJnlLine.Validate("Location Code", TempItemJournalLine."Location Code");

                // +NEW
                OnPostMultipleAdjustmentsToItemLedgerOnBeforeInsertItemJnlLine(TempItemJournalLine, ItemJnlLine);
                // -NEW

                ItemJnlLine.Insert(true);
            end;
        until TempItemJournalLine.Next = 0;

        ItemJnlLine.SetRange("Journal Template Name", ItemTemplate);
        ItemJnlLine.SetRange("Journal Batch Name", ItemBatch);
        if ItemJnlLine.IsEmpty then
            exit;

        LastErrorText := PostItemJnlLines(ItemJnlLine);
    end;

```
The events with these signatures:
```al
[IntegrationEvent(false, false)]
local procedure OnPostMultipleAdjustmentsToItemLedgerOnBeforeCalcItemInventory(TempItemJournalLine: Record "Item Journal Line" temporary; var Item: Record Item);

[IntegrationEvent(false, false)]
local procedure OnPostMultipleAdjustmentsToItemLedgerOnBeforeInsertItemJnlLine(TempItemJournalLine: Record "Item Journal Line" temporary; var ItemJournalLine: Record "Item Journal Line");
```

where `Item` is `var` so that I can add a filter on `Variant Code` to calculate current `Inventory`, and the about-to-be-inserted `ItemJournalLine` is `var` so that I can set its `Variant Code`. In both cases, the `TempItemJournalLine` must be the source of said variant.

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
