### ISSUE TITLE
[Event Request] codeunit 6620 "Copy Document Mgt."- OnBeforeUpdatePurchWhenCopyFromPurchHeader

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11284]
Hi, would it be possible to get an event OnBeforeUpdatePurchWhenCopyFromPurchHeader codeunit 6620 "Copy Document Mgt.", like this :
```
    procedure UpdatePurchHeaderWhenCopyFromPurchHeader(var PurchaseHeader: Record "Purchase Header"; OriginalPurchaseHeader: Record "Purchase Header"; FromDocType: Enum "Purchase Document Type From")
    var
        IsHandled: Boolean;
    begin
        IsHandled:= false;
        OnBeforeUpdatePurchWhenCopyFromPurchHeader(IsHandled);
        if IsHandled then
            exit;
        ClearPurchLastNoSFields(PurchaseHeader);
        with PurchaseHeader do begin
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdatePurchWhenCopyFromPurchHeader(var IsHandled: Boolean)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
