### ISSUE TITLE
Enum Request: Table "Requisition Line" field "Type"

### ISSUE THREAD

**Issue by CL2-SWECON** [microsoft/ALAppExtensions#11286]
Please provide 
field "Type" of 
table "Requisition Line"
as Enum

We need that, because we´ve extended the OptionString in the past releases.

**Comment by AlexanderYakunin** [comment]
Please use latest version, this is already implemented

        field(4; Type; Enum "Requisition Line Type")
        {
            Caption = 'Type';

**Comment by CL2-SWECON** [comment]
present in v18.0
