### ISSUE TITLE
Change SII fields from "option" type to "enum" type

### ISSUE THREAD

**Issue by yomar297** [microsoft/ALAppExtensions#11295]
Would it be possible to change the type of some SII fields from type "option" to type "enum" to facilitate adding more options in an extended way and thus avoid replicating fields? The fields would be the following:

**Table 36** “Sales Header” -> field: **10709** "Special Scheme Code"
**Table 112** “Sales Invoice Header” -> field: **10709** "Special Scheme Code"
**Table 114** “Sales Cr.Memo Header” -> field: **10709** "Special Scheme Code"
**Table 38** “Purchase Header” -> field: **10709** "Special Scheme Code"
**Table 122** “Purch. Inv. Header ”-> field: **10709** " Special Scheme Code "
**Table 124** “Purch. Cr.Memo Hdr. " -> field: **10709** "Special Scheme Code"
**Table 10752** “SII Doc. Upload State” -> fields: **22** "Sales Special Scheme Code" and **25** "Purch. Special Scheme Code"

thanks for your help

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
