### ISSUE TITLE
[Request-for-external] Codeunit 6620 "Copy Document Mgt."- CheckItemAvailable

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11292]
Hi, I was wondering if it would be possible to change the procedure CheckItemAvailable in Codeunit 6620 "Copy Document Mgt." from local to external.
My team and I use this procedure a lot in our code, and changing it to external would be a huge help.
Thanks

**Comment by AlexanderYakunin** [comment]
Please explain how you would like to use it? This procedure use global variables.

**Comment by AlexanderYakunin** [comment]
This procedure use global variables therefore we cannot expose it.
