### ISSUE TITLE
Event Request: codeunit 5817 "Undo Posting Management": OnBeforeVerifyQuantity

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#11294]
Codeunit 5817 "Undo Posting Management"

There are currently 4 instances of a call to `VerifyQuantity` on the related `<TableName>Reserv` codeunit that checks consistency of item tracking lines after a document line has been undone. These 4 calls should all be equipped with a  `OnBefore<TableName>VerifyQuantity`  event that allows us to override this behaviour (Handled)

These methods are:
`UpdatePurchLine` => `OnBeforePurchLineVerifyQuantity(PurchLine, xPurchLine, var IsHandled);`
`UpdateSalesLine` => `OnBeforeSalesLineVerifyQuantity(SalesLine, xSalesLine, var IsHandled);`
`UpdateServLine` =>  `OnBeforeServLineVerifyQuantity(ServLine, xServLine, var IsHandled);`
`UpdateServLineCnsm` =>  `OnBeforeServLineCnsmVerifyQuantity(ServLineCnsm, xServLineCnsm, var IsHandled);`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
