### ISSUE TITLE
[Event Request] Table 36 Sales Header - Ship-To Code - OnValidate

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#11305]
We would like to execute standard code also for credit doc types. To make this possible we would like to request the following event and changes to the ship-to code validation on sales header to be able to overrule IsCreditDocType.

                if ("Document Type" = "Document Type"::Order) and
                   (xRec."Ship-to Code" <> "Ship-to Code")
                then begin
                    SalesLine.SetRange("Document Type", SalesLine."Document Type"::Order);
                    SalesLine.SetRange("Document No.", "No.");
                    SalesLine.SetFilter("Purch. Order Line No.", '<>0');
                    if not SalesLine.IsEmpty then
                        Error(
                          Text006,
                          FieldCaption("Ship-to Code"));
                    SalesLine.Reset();
                end;

                // START ->
                //if not IsCreditDocType then
                OnProcessShipToCodeChangeForCreditDocuments(Rec: record "Sales Header", VAR ProcessShipToCodeChange: Boolean);
                if (not IsCreditDocType) OR ProcessShipToCodeChange then
                // <- END
                    if "Ship-to Code" <> '' then begin
                        if xRec."Ship-to Code" <> '' then begin
                            GetCust("Sell-to Customer No.");
                            if Cust."Location Code" <> '' then
                                Validate("Location Code", Cust."Location Code");
                            "Tax Area Code" := Cust."Tax Area Code";
                        end;

Many thanks.

**Comment by StanPesotskiy** [comment]
Use the existing event OnValidateShipToCodeOnBeforeCopyShipToAddress:
```
                CopyShipToAddress := not IsCreditDocType;
                OnValidateShipToCodeOnBeforeCopyShipToAddress(Rec, xRec, CopyShipToAddress);
                if CopyShipToAddress then
```
