### ISSUE TITLE
[Event Change] T77 "Report Selections" - procedure GetPurchaseOrderEmailAddress()

### ISSUE THREAD

**Issue by theoguyonnetgroupeadinfocom** [microsoft/ALAppExtensions#11316]
```
------------------ Change IntegrationEvent Attribute ----------------------
IncludeSender : true, GlobalVarAccess : true
-------------------------------------------------------------------------------

[IntegrationEvent(TRUE, TRUE)]
local procedure OnBeforeGetPurchaseOrderEmailAddress(BuyFromVendorNo: Code[20]; RecVar: Variant; ReportUsage: Enum "Report Selection Usage"; var OrderAddress: Record "Order Address"; var IsHandled: Boolean)
begin
end;
```

**Comment by StanPesotskiy** [comment]
GlobalVarAccess was deprecated in 16.x, there is concept of protected var instead. You can list here the global vars that have to be protected and accessible from extensions.

Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.
