### ISSUE TITLE
[Event Change] CU444 "Purchase-Post Prepayments" - procedure PostVendorEntry() 

### ISSUE THREAD

**Issue by theoguyonnetgroupeadinfocom** [microsoft/ALAppExtensions#11323]
```
------------------ Change IntegrationEvent Attribute ----------------------
IncludeSender : true, GlobalVarAccess : true
-------------------------------------------------------------------------------

[IntegrationEvent(TRUE, TRUE)]
local procedure  OnAfterInitNewLineOnGenJnlLine(var GenJnlLine: Record "Gen. Journal Line"; PurchHeader: Record "Purchase Header");
begin
end;
```

**Comment by StanPesotskiy** [comment]
GlobalVarAccess was deprecated in 16.x, there is concept of protected var instead. You can list here the global vars that have to be protected and accessible from extensions.

Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.
