### ISSUE TITLE
[Event Request] Report 88 "VAT- VIES Declaration Disk" - OnBeforeOnPostReport

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11345]
Hi, would it be possible to get an event OnBeforeOnPostReport Report 88 "VAT- VIES Declaration Disk", like this :

![image](https://user-images.githubusercontent.com/76154006/109287948-89252200-7824-11eb-984e-3804b6b0452e.png)

```
    trigger OnPostReport()
    var
    IsHandled: Boolean;
    begin
        if not HideFileDialog then begin
            IsHandled:= false;
            OnBeforeOnPostReport(FileName, ToFileNameTxt, IsHandled);
            if not IsHandled then
            FileManagement.DownloadHandler(FileName, '', '', FileManagement.GetToFilterText('', FileName), ToFileNameTxt);
            FileManagement.DeleteServerFile(FileName);
        end
    end;

```
![image](https://user-images.githubusercontent.com/76154006/109287966-904c3000-7824-11eb-92d3-1537c7619c6e.png)

```
[IntegrationEvent(false, false)]
local procedure OnBeforeOnPostReport(var FileName: Text; ToFileNameTxt: Text ; var IsHandled: Boolean)
begin
end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
