### ISSUE TITLE
[Event Change] Page 6641 "Purchase Return Order Subform" - procedure InsertExtendedText()

### ISSUE THREAD

**Issue by theoguyonnetgroupeadinfocom** [microsoft/ALAppExtensions#11344]
```
------------------ Change IntegrationEvent Attribute ----------------------
IncludeSender : true, GlobalVarAccess : true
-------------------------------------------------------------------------------

[IntegrationEvent(TRUE, TRUE)]
local procedure OnBeforeInsertExtendedText(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
begin
end;
```

**Comment by AlexanderYakunin** [comment]
Please explain why you created so many requests with same change ask. We cannot use property GlobalVarAccess and will not add property IncludeSender without really good purpose. As I can see you don;t need both, but some knowledge how to use existing events.

**Comment by theoguyonnetgroupeadinfocom** [comment]
OK so explain me without the IncludeSender and the GlobalVarAccess :
How I can use one or many global variable in my event?
Or how I can use in the event the sender.procedure() without losing context?

**Comment by AlexanderYakunin** [comment]
GlobalVarAccess was deprecated in 16.x, there is concept of protected var instead. Protected vars available for extensions.

You have var PurchaseLine here, it will be your context.

**Comment by theoguyonnetgroupeadinfocom** [comment]
"You have var PurchaseLine here, it will be your context."
Yes the Rec context but what about the page context?
Or in codeunit case's, the codunit context?

**Comment by AlexanderYakunin** [comment]
Can you provide code sample to demonstate what you need to achive? It will help understand your needs.

**Comment by theoguyonnetgroupeadinfocom** [comment]
For exemple : In my first [issue](https://github.com/microsoft/ALAppExtensions/issues/11290)

I have to add a case type at the end of the "Code" procedure
![image](https://user-images.githubusercontent.com/60341959/109284623-5aa54800-7820-11eb-9543-ee7c04f87057.png)

So i used the OnAfterRunCode event like this :
![image](https://user-images.githubusercontent.com/60341959/109284779-858f9c00-7820-11eb-9f08-224ed4dc2211.png)

But here my problem is that I can't go back in the codeunit "Job Jnl.-Post Line" without the sender?
That's why I created a local function.

The problem is the local var JobJnlPostLine isn't initialized.
So in the CreateJobLedgEntry's method, all globals variables are nullable.

**Comment by AlexanderYakunin** [comment]
Yes, in this case you need access to JobJnlPostLine as sender, we use this for selected events. it is valid case.

But this is not for this request, how about this page and InsertExtendedText?

**Comment by theoguyonnetgroupeadinfocom** [comment]
I used the OnBeforeInsertExtendedText for `IsHandled := true;`.
Does the `IncludeSender = true` use more memory than `IncludeSender = false`?

**Comment by theoguyonnetgroupeadinfocom** [comment]
I've migrated all my code from 14.x to 17.x in extention **without testing**. And I'm afraid to write an issue and wait for the next CU every time there's a bug. My test phase can last 3 years at this rate......
