### ISSUE TITLE
[Event Change] T83 "Item Journal Line" - procedure OnBeforePickDimension()

### ISSUE THREAD

**Issue by theoguyonnetgroupeadinfocom** [microsoft/ALAppExtensions#11340]
```
------------------ Change IntegrationEvent Attribute ----------------------
IncludeSender : true, GlobalVarAccess : true
-------------------------------------------------------------------------------

[IntegrationEvent(TRUE, TRUE)]
local procedure OnBeforePickDimension(var ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean,
CurrFieldNo: Integer, TableArray: array[10] of Integer, CodeArray: array[10] of Code[20], InheritFromDimSetID: Integer, InheritFromTableNo: Integer)
begin
end;
```

**Comment by AlexanderYakunin** [comment]
What is you version? Property GlobalVarAcces have been obsoleted long time ago? And why you need IncludeSender property, you already have ItemJournalLine parameter with var?

**Comment by StanPesotskiy** [comment]
GlobalVarAccess was deprecated in 16.x, there is concept of protected var instead. You can list here the global vars that have to be protected and accessible from extensions.

Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.
