### ISSUE TITLE
[Request for External] Codeunit 5940 "ServContractManagement" - SetServLedgEntryAmounts

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#11349]
Hi, would it be possible to modify SetServLedgEntryAmounts in codeunit 5940 from local to external?
Having the procedure SetServLedgEntryAmounts as an external would really help us.
We need it for the event mentioned in #11348 .
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
