### ISSUE TITLE
[Protection Level] Table "Customer" Function "IsContactUpdateNeeded" remove local

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11343]
Depending on the function "IsContactUpdateNeeded" we control a mailing for customer update notification. We want to avoid having duplicate function for therefore we ask for removing local.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
