### ISSUE TITLE
[Event Request] - Page 9192 "Company Creation Wizard" - OnValidateNewCompanyName

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#11358]
Requesting 1 new event publisher on page 9192 - "Company Creation Wizard" 

**Event**
```
[IntegrationEvent(false, false)]
local procedure OnValidateNewCompanyName(var NewCompanyName: Text[30])
begin
end;
```

**Execution**

```
field(CompanyName; NewCompanyName)
{
    ApplicationArea = Basic, Suite;
    ShowCaption = false;
    ShowMandatory = true;

    trigger OnValidate()
    var
        Company: Record Company;
    begin
        NewCompanyName := DelChr(NewCompanyName, '<>');
        Company.SetFilter(Name, '%1', '@' + NewCompanyName);
        if Company.FindFirst then
            Error(CompanyAlreadyExistsErr);
        >>>> New Code
        OnValidateNewCompanyName(NewCompanyName);
        <<<< New Code End
    end;
}
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
