### ISSUE TITLE
IntegrationEvent Request: Please Add OnBeforeInsertServComponentFromBOM() in Codeunit "ServComponent-Copy from BOM"

### ISSUE THREAD

**Issue by CL2-SWECON** [microsoft/ALAppExtensions#11357]
IntegrationEvent Request
Please Add in Codeunit "ServComponent-Copy from BOM" in OnRun() trigger:

Signature:
OnBeforeInsertServComponentFromBOM(var ServItemComponent: Record "Service Item Component"; BOMComp: Record "BOM Component"; Item: Record Item) 

Place in Code:
....
  ServItemComponent."Description 2" := Item."Description 2";
  ServItemComponent."From Line No." := 0;
OnBeforeInsertServComponentFromBOM(var ServItemComponent: Record "Service Item Component"; BOMComp: Record "BOM Component"; Item: Record Item) 
  if not ServItemComponent.Insert() then
      ServItemComponent.Modify();
....

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
