### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnBuyFromCityOnBeforeOnLookup

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11350]
Hello. In table 38 purchase Header, in the field 83 "Buy-from City", in trigger OnLookup, I would like to add my own code instead of the standard one. To do so, I would need an event publisher, like this :

        field(83; "Buy-from City"; Text[30])
        {
            ...
            trigger OnLookup()
            var
                IsHandled : boolean;
            begin
                IsHandled := false;
                OnBuyFromCityOnBeforeOnLookup(Rec, PostCode, IsHandled);
                if IsHandled then
                    exit;
                LookupPostCode("Buy-from City", "Buy-from Post Code", "Buy-from County", "Buy-from Country/Region Code", CurrFieldNo);
            end;
            ...
          }

With this event integration : 

    [IntegrationEvent(TRUE, false)]
    procedure OnBuyFromCityOnBeforeOnLookup(var PurchaseHeader: Record "Purchase Header"; PostCode : record "Post Code"; var IsHandled : boolean)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by StanPesotskiy** [comment]
Why do you need [IntegrationEvent(**TRUE**, false)] if you have the first parameter taking Rec as var?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
