### ISSUE TITLE
Request Event - Codeunit 99000768 - Production BOM-Copy

### ISSUE THREAD

**Issue by ValcLuisCosta** [microsoft/ALAppExtensions#11351]
Hello,
I'm using the AL Language version 6.5.413786 and BC version 17.3.
I need the following event on Codeunit 99000768 "Production BOM-Copy":

    procedure CopyBOM(BOMHeaderNo: Code[20]; FromVersionCode: Code[20]; CurrentBOMHeader: Record "Production BOM Header"; ToVersionCode: Code[20])
    var
        FromProdBOMLine: Record "Production BOM Line";
        ToProdBOMLine: Record "Production BOM Line";
        FromProdBOMCompComment: Record "Production BOM Comment Line";
        ToProdBOMCompComment: Record "Production BOM Comment Line";
        ProdBOMVersion: Record "Production BOM Version";
        SkipBOMDeletion: Boolean;
        LineNo: Integer;
    begin
        if (CurrentBOMHeader."No." = BOMHeaderNo) and
           (FromVersionCode = ToVersionCode)
        then
            Error(Text000, CurrentBOMHeader.TableCaption);

        if ToVersionCode = '' then begin
            if CurrentBOMHeader.Status = CurrentBOMHeader.Status::Certified then
                Error(
                  Text001,
                  CurrentBOMHeader.FieldCaption(Status),
                  CurrentBOMHeader.TableCaption,
                  CurrentBOMHeader."No.",
                  CurrentBOMHeader.Status);
        end else begin
            ProdBOMVersion.Get(
              CurrentBOMHeader."No.", ToVersionCode);
            if ProdBOMVersion.Status = ProdBOMVersion.Status::Certified then
                Error(
                  Text002,
                  ProdBOMVersion.FieldCaption(Status),
                  ProdBOMVersion.TableCaption,
                  ProdBOMVersion."Production BOM No.",
                  ProdBOMVersion."Version Code",
                  ProdBOMVersion.Status);
        end;

        LineNo := 0;
        SkipBOMDeletion := false;
        OnBeforeCopyBOM(CurrentBOMHeader, BOMHeaderNo, FromVersionCode, ToVersionCode, SkipBOMDeletion, LineNo);
        if not SkipBOMDeletion then begin
            ToProdBOMLine.SetRange("Production BOM No.", CurrentBOMHeader."No.");
            ToProdBOMLine.SetRange("Version Code", ToVersionCode);
            ToProdBOMLine.DeleteAll();

            ToProdBOMCompComment.SetRange("Production BOM No.", CurrentBOMHeader."No.");
            ToProdBOMCompComment.SetRange("Version Code", ToVersionCode);
            ToProdBOMCompComment.DeleteAll();
        end;

        FromProdBOMLine.SetRange("Production BOM No.", BOMHeaderNo);
        FromProdBOMLine.SetRange("Version Code", FromVersionCode);
        if FromProdBOMLine.Find('-') then
            repeat
                ToProdBOMLine := FromProdBOMLine;
                ToProdBOMLine."Production BOM No." := CurrentBOMHeader."No.";
                ToProdBOMLine."Version Code" := ToVersionCode;
                if SkipBOMDeletion then
                    ToProdBOMLine."Line No." := LineNo;
                OnBeforeInsertProdBOMComponent(ToProdBOMLine, FromProdBOMLine);
                ToProdBOMLine.Insert();
                OnAfterInsertProdBOMComponent(ToProdBOMLine, FromProdBOMLine, CurrentBOMHeader, SkipBOMDeletion, LineNo);
            until FromProdBOMLine.Next = 0;

        if SkipBOMDeletion then
            exit;

        FromProdBOMCompComment.SetRange("Production BOM No.", BOMHeaderNo);
        FromProdBOMCompComment.SetRange("Version Code", FromVersionCode);
        if FromProdBOMCompComment.Find('-') then
            repeat
                ToProdBOMCompComment := FromProdBOMCompComment;
                ToProdBOMCompComment."Production BOM No." := CurrentBOMHeader."No.";
                ToProdBOMCompComment."Version Code" := ToVersionCode;
                ToProdBOMCompComment.Insert();
            until FromProdBOMCompComment.Next = 0;

        **-------------- ADD EVENT -----------
        IF BOMHeaderNo <> CurrentBOMHeader."No." THEN
            OnAfterCopyBom(BOMHeaderNo, CurrentBOMHeader."No.")
        ---------------------------------------**
    end;

Thanks,
Luís Costa

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
