### ISSUE TITLE
New event "OnAfterCalculatePostedPurchCreditMemoTotals" in "CalculatePostedPurchCreditMemoTotals" function in "Document Totals" codeunit.

### ISSUE THREAD

**Issue by clasalal** [microsoft/ALAppExtensions#11359]
Related to issue #10871  created and resolved recently.

The event "OnAfterCalculatePostedPurchCreditMemoTotals" is missing in the function "CalculatePostedPurchCreditMemoTotals" in the codeunit "Document Totals", as it is for the rest of the sales and purchasing documents therefore, even if the global variable was made visible, I cannot update my custom fields as the requested event does not exist.

![image](https://user-images.githubusercontent.com/64960257/109485388-ebc72980-7a81-11eb-84ad-ac829574f7d9.png)

Thanks in advance

Clara

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
