### ISSUE TITLE
[Event Request] Codeunit 99000854 - Add. Param. for OnPlanItemAfterCalcIsReorderPointPlanning

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11366]
Please add new Parameters to Publisher OnPlanItemAfterCalcIsReorderPointPlanning of Codeunit 99000854 "Inventory Profile Offsetting"

Add Parameter ReqLine, PlanningTransparency, PlanningResilicency, CurrTemplateName and CurrWorksheetName to Call of Publisher

````
                 IsReorderPointPlanning := IsSKUSetUpForReorderPointPlanning(TempSKU);
-                OnPlanItemAfterCalcIsReorderPointPlanning(TempSKU, IsReorderPointPlanning);
+                OnPlanItemAfterCalcIsReorderPointPlanning(TempSKU, IsReorderPointPlanning, ReqLine, PlanningTransparency, PlanningResilicency, CurrTemplateName, CurrWorksheetName);

                 BucketSize := TempSKU."Time Bucket";
````

Adjust Publisher:

Add Parameters and set var Flag for existing TempSKU Parameter

````
     [IntegrationEvent(false, false)]
-    local procedure OnPlanItemAfterCalcIsReorderPointPlanning(TempSKU: Record "Stockkeeping Unit"; var IsReorderPointPlanning: Boolean)
+    local procedure OnPlanItemAfterCalcIsReorderPointPlanning(var TempSKU: Record "Stockkeeping Unit"; var IsReorderPointPlanning: Boolean; var RequisitionLine: Record "Requisition Line"; var PlanningTransparency: Codeunit "Planning Transparency"; PlanningResilicency: Boolean; var CurrTemplateName: Code[10]; var CurrWorksheetName: Code[10])
     begin
     end;
````

**Comment by wweidl** [comment]
Any news on this issue ?

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
