### ISSUE TITLE
[Request for External] - Codeunit 9 - Acc. Sched. KPI Dimensions

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#11362]
We would like to reuse other functions of this code unit.

Can you please change the following procedures from local to external?
- ConflictAmountType
- CombineFilters
- CheckAddDimsToResult
- PassToResult

Can you please add a procedure that allows the TempAccSchedKPIBuffer to be set externally?

```
procedure SetTempAccSchedKPIBuffer(NewTempAccSchedKPIBuffer: Record "Acc. Sched. KPI Buffer" temporary)
begin
   TempAccSchedKPIBuffer := NewTempAccSchedKPIBuffer;  
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
