### ISSUE TITLE
[Event Request] Codeunit 99000854 - OnAfterUnfoldItemTracking

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11369]
Please add a new Publisher Call OnAfterUnfoldItemTracking in Procedure UnfoldItemTracking of Codeunit 99000854 "Inventory Profile Offsetting"

Add Call of Publisher in procedure UnfoldItemTracking

````
             until ParentInvProfile.Next = 0;
+        OnAfterUnfoldItemTracking(ParentInvProfile, ChildInvProfile);
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnAfterUnfoldItemTracking(var ParentInvProfile: Record "Inventory Profile"; var ChildInvProfile: Record "Inventory Profile")
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
