### ISSUE TITLE
[Event Request] Codeunit 99000854 - OnBeforeUnfoldItemTracking

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11368]
Please add a new Publisher Call OnBeforeUnfoldItemTracking in Procedure UnfoldItemTracking of Codeunit 99000854 "Inventory Profile Offsetting"

Add Call of Publisher in procedure UnfoldItemTracking

````
+       OnBeforeUnfoldItemTracking(ParentInvProfile, ChildInvProfile, TempItemTrkgEntry);
        ParentInvProfile.Reset();
        TempItemTrkgEntry.Reset();
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnCalculatePlanFromWorksheetOnBeforeUnfoldItemTracking(var InventoryProfile: Record "Inventory Profile"; var Item: Record Item; ToDate: Date; var LineNo: Integer; var TempTrkgReservEntry: Record "Reservation Entry" temporary);
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
