### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnValidateOrderAddressCodeOnAfterCopyBuyFromVendorAddressFieldsFromVendor

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11364]
Hello. In table 38 Purchase Header, in the field 95 "Order Address Code", in trigger OnValidate, I would like to add my own code instead of the standard one with the event publisher OnValidateOrderAddressCodeOnAfterCopyBuyFromVendorAddressFieldsFromVendor. But I need the parameter Vend in this event. Like this :

        field(95; "Order Address Code"; Code[10])
        {
            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                    ...
                    OnValidateOrderAddressCodeOnAfterCopyBuyFromVendorAddressFieldsFromVendor(Rec, Vend);
                    ...
            end;
        }

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnValidateOrderAddressCodeOnAfterCopyBuyFromVendorAddressFieldsFromVendor(var PurchaseHeader: Record "Purchase Header"; Vend: Record Vendor);
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
