### ISSUE TITLE
[Change Event Request] - Codeunit 9 - Acc. Sched. KPI Dimensions

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#11361]
Please add a new parameter (TempAccSchedKPIBuffer) to event OnBeforeAddCostTypeDimensions in Codeunit 9 - Acc. Sched. KPI Dimensions

```
[IntegrationEvent(false, false)]
local procedure OnBeforeAddCostTypeDimensions( TempAccSchedKPIBuffer: Record "Acc. Sched. KPI Buffer" temporary; var CostType: Record "Cost Type"; var AccSchedLine: Record "Acc. Schedule Line"; ColumnLayout: Record "Column Layout"; var AccSchedKPIBuffer: Record "Acc. Sched. KPI Buffer"; var IsHandled: Boolean)
begin
end;
```

**Comment by StanPesotskiy** [comment]
Please separate the request asking for a new event or modification to the existing event from the request for making variables or procedures public(protected).

**Comment by bleisibach** [comment]
Thanks for pointing this out, Stan. Is done.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
