### ISSUE TITLE
[Event Request] Table 336 OnAfterInitFromTransLine

### ISSUE THREAD

**Issue by GuntherGebauer** [Microsoft/ALAppExtensions#1136]
The existing Publisher function Needs an additonal Parameter "Direction" , so that we use this Event correctly for Transfer shipment and receipt:

[External] InitFromTransLine(VAR TransLine : Record "Transfer Line";VAR AvalabilityDate : Date;Direction : 'Outbound,Inbound')
CASE Direction OF
  Direction::Outbound:
    BEGIN
      INIT;
      SetItemData(
        TransLine."Item No.",TransLine.Description,TransLine."Transfer-from Code",TransLine."Variant Code",
        TransLine."Transfer-from Bin Code",TransLine."Qty. per Unit of Measure");
      SetSource(
        DATABASE::"Transfer Line",Direction,TransLine."Document No.",TransLine."Line No.",'',
        TransLine."Derived From Line No.");
      SetQuantities(
        TransLine."Quantity (Base)",TransLine."Qty. to Ship",TransLine."Qty. to Ship (Base)",TransLine.Quantity,
        TransLine."Quantity (Base)",TransLine."Qty. Shipped (Base)",0);
      AvalabilityDate := TransLine."Shipment Date";
    END;
  Direction::Inbound:
    BEGIN
      INIT;
      SetItemData(
        TransLine."Item No.",TransLine.Description,TransLine."Transfer-to Code",TransLine."Variant Code",
        TransLine."Transfer-To Bin Code",TransLine."Qty. per Unit of Measure");
      SetSource(
        DATABASE::"Transfer Line",Direction,TransLine."Document No.",TransLine."Line No.",'',
        TransLine."Derived From Line No.");
      SetQuantities(
        TransLine."Quantity (Base)",TransLine."Qty. to Receive",TransLine."Qty. to Receive (Base)",TransLine.Quantity,
        TransLine."Quantity (Base)",TransLine."Qty. Received (Base)",0);
      AvalabilityDate := TransLine."Receipt Date";
    END;
END;

OnAfterInitFromTransLine(VAR Rec,TransLine;Direction : 'Outbound,Inbound');    <-- Change Event

**Comment by AlexanderYakunin** [comment]
Already done
