### ISSUE TITLE
[Event Request] Codeunit 99000854 - OnCreateSupplyOnBeforeInsertSupply

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11379]
Please add a new Publisher Call OnCreateSupplyOnBeforeInsertSupply in Procedure CreateSupply of Codeunit 99000854 "Inventory Profile Offsetting"

Add Call of Publisher in procedure CreateSupply

````
         TransferAttributes(SupplyInvtProfile, DemandInvtProfile);
         SupplyInvtProfile."Is Exception Order" := IsExceptionOrder;
+        OnCreateSupplyOnBeforeInsertSupply(SupplyInvtProfile, TempSKU);
         SupplyInvtProfile.Insert();
         if (not IsExceptionOrder or RespectPlanningParm) and (OverflowLevel > 0) then
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnCreateSupplyOnBeforeInsertSupply(var SupplyInvtProfile: Record "Inventory Profile"; var SKU: Record "Stockkeeping Unit")
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
