### ISSUE TITLE
[Event Request] Codeunit 99000854 - OnAfterMatchAttributes

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11371]
Please add a new Publisher Call OnAfterMatchAttributes in Procedure MatchAttributes of Codeunit 99000854 "Inventory Profile Offsetting"

Add Call of Publisher in procedure MatchAttributes

````
         DemandInvtProfile.CopyFilters(xDemandInvtProfile);
         SupplyInvtProfile.CopyFilters(xSupplyInvtProfile);
+        OnAfterMatchAttributes(SupplyInvtProfile, DemandInvtProfile, TempTrkgReservEntry);
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnAfterMatchAttributes(var SupplyInvtProfile: Record "Inventory Profile"; var DemandInvtProfile: Record "Inventory Profile"; var TrackingReservEntry: Record "Reservation Entry")
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
