### ISSUE TITLE
[Request for External] Codeunit 7312 "Create Pick" - CalcAvailableQty

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#11374]
Hi, would it be possible to modify CalcAvailableQty in codeunit 7312 from local to external?
Having the procedure CalcAvailableQty as an external would really help us.
Thanks

**Comment by AlexanderYakunin** [comment]
This local procedure design based on global variables, how you are going to get correct results using this procedure?
