### ISSUE TITLE
[Event Request] Codeunit 99000854 - OnAfterPlanItemNextStateStartOver

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11376]
Please add a new Publisher Call OnAfterPlanItemNextStateStartOver in Procedure PlanItemNextStateStartOver of Codeunit 99000854 "Inventory Profile Offsetting"

Add Call of Publisher in procedure PlanItemNextStateStartOver

````
                 if SupplyExists then
                     NextState := NextState::ReduceSupply
                 else
                     NextState := NextState::CloseLoop;
+        OnAfterPlanItemNextStateStartOver(SupplyInvtProfile, TempSKU);
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnAfterPlanItemNextStateStartOver(var SupplyInvtProfile: Record "Inventory Profile"; var SKU: Record "Stockkeeping Unit")
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
