### ISSUE TITLE
[Event Request] Codeunit 99000854 - OnBeforeIncreaseQty

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11377]
Please add a new Publisher Call OnBeforeIncreaseQty in Procedure IncreaseQty of Codeunit 99000854 "Inventory Profile Offsetting"

Add Call of Publisher in procedure IncreaseQty

````
+        OnBeforeIncreaseQty(SupplyInvtProfile, NeededQty, TempSKU);
         TempQty := SupplyInvtProfile."Remaining Quantity (Base)";
 
         if not SupplyInvtProfile."Is Exception Order" or RespectPlanningParm then
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnBeforeIncreaseQty(var SupplyInvtProfile: Record "Inventory Profile"; NeededQty: Decimal; var SKU: Record "Stockkeeping Unit")
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
