### ISSUE TITLE
[Event Request] Codeunit 99000854 - OnBeforeDecreaseQty

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11378]
Please add a new Publisher Call OnBeforeDecreaseQty in Procedure DecreaseQty of Codeunit 99000854 "Inventory Profile Offsetting"

Add Call of Publisher in procedure DecreaseQty

````
+        OnBeforeDecreaseQty(SupplyInvtProfile, ReduceQty, TempSKU);
         if not CanDecreaseSupply(SupplyInvtProfile, ReduceQty) then begin
             if (ReduceQty <= DampenerQty) and (SupplyInvtProfile."Planning Level Code" = 0) then
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnBeforeDecreaseQty(var SupplyInvtProfile: Record "Inventory Profile"; ReduceQty: Decimal; var SKU: Record "Stockkeeping Unit")
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
