### ISSUE TITLE
[Event Request] Codeunit 802 "Online Map Management" - OnGetSetupBeforeGet

### ISSUE THREAD

**Issue by SteinleMossGaewers** [microsoft/ALAppExtensions#11389]
Hi, would it be possible to get an event  OnGetSetupBeforeGet in Codeunit 802 (Online Map Management), like this:

```
local procedure GetSetup()
    begin
        OnlineMapSetup.Get();
        OnlineMapSetup.TestField("Map Parameter Setup Code");
        OnGetSetupBeforeGet(OnlineMapParameterSetup);
        OnlineMapParameterSetup.Get(OnlineMapSetup."Map Parameter Setup Code");
    end;
```

```
[IntegrationEvent(false, false)]
local procedure OnGetSetupBeforeGet(var OnlineMapParameterSetup: Record "Online Map Parameter Setup")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
