### ISSUE TITLE
[Event Request] Codeunit 1302 - Function SetFilterForPostedDocs

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#11383]
Hello, would it be possible to get an event OnBeforSetFilterForPostedDocs (CustLedgEntry as var) in Codeunit 1302 Function SetFilterForPostedDocs, like this:    

local procedure SetFilterForPostedDocs(var CustLedgEntry: Record "Cust. Ledger Entry"; CustNo: Code[20]; DocumentType: Enum "Gen. Journal Document Type")
    begin
        with CustLedgEntry do begin
            OnBeforSetFilterForPostedDocs(CustLedgEntry);
            SetRange("Customer No.", CustNo);
            SetFilter("Posting Date", GetCurrentYearFilter);
            SetRange("Document Type", DocumentType);
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
