### ISSUE TITLE
[Event Request] Codeunit 1302 - Function SetFilterForUnpostedLines

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#11384]
Hello, would it be possible to get an event OnBeforSetFilterForUnpostedLines (SalesLine as var) in Codeunit 1302 Function SetFilterForUnpostedLines, like this:

local procedure SetFilterForUnpostedLines(var SalesLine: Record "Sales Line"; CustNo: Code[20]; DocumentType: Enum "Sales Document Type"; Posted: Boolean)
    begin
        with SalesLine do begin
            **OnBeforSetFilterForUnpostedLines(SalesLine)**
            SetRange("Bill-to Customer No.", CustNo);
            if Posted then
                SetFilter("Posting Date", GetCurrentYearFilter);

            SetRange("Document Type", DocumentType);
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
