### ISSUE TITLE
[Event Request] Codeunit 99000854 - OnCheckSupplyWithSKUOnInvtProfileLoop

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11388]
Please add a new Publisher Call OnCheckSupplyWithSKUOnInvtProfileLoop in Procedure CheckSupplyWithSKU of Codeunit 99000854 "Inventory Profile Offsetting"

Add Call of Publisher in procedure CheckSupplyWithSKU

````
                if Find('-') then
                    repeat
+                       OnCheckSupplyWithSKUOnInvtProfileLoop(InventoryProfile, SKU);
                        if (SKU."Maximum Order Quantity" > "Max. Quantity") and
                           ("Quantity (Base)" > 0) and
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnCheckSupplyWithSKUOnInvtProfileLoop(var InventoryProfile: Record "Inventory Profile"; var SKU: Record "Stockkeeping Unit")
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
