### ISSUE TITLE
[Event Request] Table 80 Gen. Journal Line - Function CopyFromIssuedReminderLine

### ISSUE THREAD

**Issue by swecompany** [microsoft/ALAppExtensions#11386]
Hello,
would it be possible to get an event OnAfterCopyFromIssuedReminderLine(IssuedReminderLine, Rec) like this:

[IntegrationEvent(false, false)]
local procedure OnAfterCopyFromIssuedReminderLine(IssuedReminderLine: Record "Issued Reminder Line"; var GenJournalLine: Record "Gen. Journal Line")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
