### ISSUE TITLE
[Event Request] Codeunit 99000854 - OnAfterAdjustPlanLine

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11387]
Please add a new Publisher Call OnAfterAdjustPlanLine in Procedure AdjustPlanLine of Codeunit 99000854 "Inventory Profile Offsetting"

Add Call of Publisher in procedure AdjustPlanLine

````
             if (ReqLine."Starting Date" = 0D) or
                (ReqLine."Starting Date" > ReqLine."Ending Date")
             then
                 ReqLine."Starting Date" := ReqLine."Ending Date";
         end;
+        OnAfterAdjustPlanLine(ReqLine, SupplyInventoryProfile);
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnAfterAdjustPlanLine(var RequisitionLine: Record "Requisition Line"; var SupplyInventoryProfile: Record "Inventory Profile")
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
