### ISSUE TITLE
[Event Request] Report 99001017 - OnBeforeDeletePlanningErrorLog

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11399]
Please add a new Publisher Call OnBeforeDeletePlanningErrorLog in Trigger OnPreDataItem of Dataitem Item of Report 99001017 "Calculate Plan - Plan. Wksh."

Add Call of Publisher in Trigger OnPreDataItem of Dataitem Item

- Add new loc. Var. IsHandled:Boolean

````
                if PlanningErrorLog.FindFirst and ReqLine.FindFirst then
                    SetAtStartPosition := not Confirm(Text009);

+               IsHandled := false;
+               OnBeforeDeletePlanningErrorLog(PlanningErrorLog, IsHandled);
+               if not IsHandled then
                    PlanningErrorLog.DeleteAll();
                ClearLastError;
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnBeforeDeletePlanningErrorLog(var PlanningErrorLog: Record "Planning Error Log"; var IsHandled: Boolean)
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
