### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnBeforeInitRecord

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11397]
Hello. In table 38 Purchase Header, in the procedure InitRecord, I would like to use the event publisher OnBeforeInitRecord to add my own code instead of the standard one. But I need the parameters PurchSetup and GLSetup in this event. Like this :

    procedure InitRecord()
    var
        ArchiveManagement: Codeunit ArchiveManagement;
        IsHandled: Boolean;
    begin
        GetPurchSetup();
        IsHandled := false;
        OnBeforeInitRecord(Rec, IsHandled, xRec, PurchSetup, GLSetup);
        ...

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitRecord(var PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean; xPurchaseHeader: Record "Purchase Header";  PurchSetup: Record "Purchases & Payables Setup"; GLSetup: Record "General Ledger Setup")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
