### ISSUE TITLE
[Event Request] Codeunit 99000854 - OnCreateSupplyForInitialSafetyStockWarningOnBeforeInsertSupply

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11395]
Please add a new Publisher Call OnCreateSupplyForInitialSafetyStockWarningOnBeforeInsertSupply in Procedure CreateSupplyForInitialSafetyStockWarning of Codeunit 99000854 "Inventory Profile Offsetting"

Add Call of Publisher in procedure CreateSupplyForInitialSafetyStockWarning

````
            SupplyInventoryProfile."Order Relation" := SupplyInventoryProfile."Order Relation"::"Safety Stock";
            SupplyInventoryProfile."Is Exception Order" := true;
+           OnCreateSupplyForInitialSafetyStockWarningOnBeforeInsertSupply(SupplyInventoryProfile, TempSKU);
            SupplyInventoryProfile.Insert();

            DummyInventoryProfileTrackBuffer."Warning Level" := DummyInventoryProfileTrackBuffer."Warning Level"::Exception;
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnCreateSupplyForInitialSafetyStockWarningOnBeforeInsertSupply(var SupplyInvtProfile: Record "Inventory Profile"; var SKU: Record "Stockkeeping Unit")
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
