### ISSUE TITLE
[Event Request] Report 99001017 - OnBeforeStartItemPlanning

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11396]
Please add a new Publisher Call OnBeforeStartItemPlanning in Trigger OnAfterGetRecord of Dataitem Item of Report 99001017 "Calculate Plan - Plan. Wksh."

Add Call of Publisher in Trigger OnAfterGetRecord of Dataitem Item

````
                UpdateWindow;

+               OnBeforeStartItemPlanning(Item);
+
                if not SetAtStartPosition then begin
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnBeforeStartItemPlanning(Item: Record Item)
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
