### ISSUE TITLE
[Event Request] Codeunit 99000854 - OnScheduleAllOutChangesSequenceOnBeforeInsertSupply

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11394]
Please add a new Publisher Call OnScheduleAllOutChangesSequenceOnBeforeInsertSupply in Procedure ScheduleAllOutChangesSequence of Codeunit 99000854 "Inventory Profile Offsetting"

Add Call of Publisher in procedure ScheduleAllOutChangesSequence

````
                SupplyInvtProfile.Delete();
                SupplyInvtProfile := TempRescheduledSupplyInvtProfile;
                SupplyInvtProfile."Line No." := NextLineNo;
+               OnScheduleAllOutChangesSequenceOnBeforeInsertSupply(SupplyInvtProfile);
                SupplyInvtProfile.Insert();
                if not HasLooped then begin
````

New Publisher:

````
+    [IntegrationEvent(true, false)]
+    local procedure OnScheduleAllOutChangesSequenceOnBeforeInsertSupply(var SupplyInvtProfile: Record "Inventory Profile")
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
