### ISSUE TITLE
[Event Request] Report 99001017 - OnAfterPlanningErrorLogSetJnlBatch

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11398]
Please add a new Publisher Call OnAfterPlanningErrorLogSetJnlBatch in Trigger OnAfterGetRecord of Dataitem Item of Report 99001017 "Calculate Plan - Plan. Wksh."

Add Call of Publisher in Trigger OnAfterGetRecord of Dataitem Item

````
                                ClearLastError;
                            PlanningErrorLog.SetJnlBatch(CurrTemplateName, CurrWorksheetName, "No.");
+                           OnAfterPlanningErrorLogSetJnlBatch(Item, PlanningErrorLog);
                            PlanningErrorLog.SetError(
                              CopyStr(StrSubstNo(ErrorText, TableCaption, "No."), 1, 250), 0, GetPosition);
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnAfterPlanningErrorLogSetJnlBatch(Item: Record Item; var PlanningErrorLog: Record "Planning Error Log")
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
