### ISSUE TITLE
[Event Request] Codeunit 99000854 - OnCreateSupplyForwardOnBeforeInsertSupply

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11390]
Please add a new Publisher Call OnCreateSupplyForwardOnBeforeInsertSupply in Procedure CreateSupplyForward of Codeunit 99000854 "Inventory Profile Offsetting"

Add Call of Publisher in procedure CreateSupplyForward

````
            SupplyInvtProfile."Fixed Date" := SupplyInvtProfile."Due Date";
            SupplyInvtProfile."Order Priority" := 1000; // Make sure to give last priority if supply exists on the same date
            SupplyInvtProfile."Attribute Priority" := 1000;
+           OnCreateSupplyForwardOnBeforeInsertSupply(SupplyInvtProfile, TempSKU);
            SupplyInvtProfile.Insert();

            // Planning Transparency
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnCreateSupplyForwardOnBeforeInsertSupply(var SupplyInvtProfile: Record "Inventory Profile"; var SKU: Record "Stockkeeping Unit")
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
