### ISSUE TITLE
[Event Request] Codeunit 99000854 - OnAfterAllowScheduleIn

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11391]
Please add a new Publisher Call OnAfterAllowScheduleIn in Procedure AllowScheduleIn of Codeunit 99000854 "Inventory Profile Offsetting"

Add Call of Publisher in procedure AllowScheduleIn

````
        CanReschedule := CalcDate(TempSKU."Rescheduling Period", TargetDate) >= SupplyInvtProfile."Due Date";
+       OnAfterAllowScheduleIn(SupplyInvtProfile, TargetDate, CanReschedule);
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnAfterAllowScheduleIn(SupplyInvtProfile: Record "Inventory Profile"; TargetDate: Date; var CanReschedule: Boolean)
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
