### ISSUE TITLE
[Event Request] Codeunit 1535 "Approvals Mgmt." - OnBeforeIsPurchaseApprovalsWorkflowEnabled

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#11407]
Hi, would it be possible to get an **OnBeforeIsPurchaseApprovalsWorkflowEnabled** event in codeunit 1535 (**Approvals Mgmt.**), like this:
```AL
    procedure IsPurchaseApprovalsWorkflowEnabled(var PurchaseHeader: Record "Purchase Header"): Boolean
    begin
        OnBeforeIsPurchaseApprovalsWorkflowEnabled(PurchaseHeader);  // New Event

        exit(WorkflowManagement.CanExecuteWorkflow(PurchaseHeader, WorkflowEventHandling.RunWorkflowOnSendPurchaseDocForApprovalCode));
    end;
```
```AL
    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsPurchaseApprovalsWorkflowEnabled(var PurchaseHeader: Record "Purchase Header");
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
