### ISSUE TITLE
Request Event Parameters - Report 99001017 - Calculate Plan - Plan. Wksh.

### ISSUE THREAD

**Issue by ValcLuisCosta** [microsoft/ALAppExtensions#11408]
Hello,
I'm using the AL Language version 6.5.413786 and BC version 17.3.
I need the following parameters on the event OnAfterItemOnPostDataItem on Report 99001017 - Calculate Plan - Plan. Wksh. :

    trigger OnPostDataItem()
    begin
        CalcItemPlan.Finalize;
        CloseWindow;

        **-------------- ADD Parameters to EVENT -----------
                OnAfterItemOnPostDataItem(VAR CurrTemplateName : Code[10];VAR CurrWorksheetName : Code[10]);
        ---------------------------------------**
    end;

Thanks,
Luís Costa

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events.

**Comment by ValcLuisCosta** [comment]
Hi StanPesotskiy,
I already updated the ticket.
Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
