### ISSUE TITLE
[Request-for-external] Table 38 "Purchase Header" -  ValidateEmptySellToCustomerAndLocation and UpdateInboundWhseHandlingTime 

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11402]
Hello. In table 38 Purchase Header, in the procedure InitRecord, I would like to use the event publisher OnBeforeInitRecord to add my own code instead of the standard one. From my event subscriber, I would like to use local procedures ValidateEmptySellToCustomerAndLocation and UpdateInboundWhseHandlingTime, but they are local ones. Is possible to pass them in global please ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
