### ISSUE TITLE
Request Event - Report 99001020 - Carry Out Action Msg. - Plan.

### ISSUE THREAD

**Issue by ValcLuisCosta** [microsoft/ALAppExtensions#11409]
Hello,
I'm using the AL Language version 6.5.413786 and BC version 17.3.
I need the following event on Report 99001020 - Carry Out Action Msg. - Plan.:

    local procedure CheckLine()
    var
        SalesLine: Record "Sales Line";
        ProdOrderComp: Record "Prod. Order Component";
        ServLine: Record "Service Line";
        JobPlanningLine: Record "Job Planning Line";
        AsmLine: Record "Assembly Line";
        ReqLine2: Record "Requisition Line";
    begin
        with "Requisition Line" do begin
            if "Planning Line Origin" <> "Planning Line Origin"::"Order Planning" then
                exit;

            CheckAssociations("Requisition Line");

            if "Planning Level" > 0 then
                exit;

            if "Replenishment System" in ["Replenishment System"::Purchase,
                                          "Replenishment System"::Transfer]
            then
                TestField("Supply From");

            **-------------- ADD EVENT -----------
            OnBeforeCheckDemandType(var RequisitionLine: Record "Requisition Line");
            ---------------------------------------**

            case "Demand Type" of
                DATABASE::"Sales Line":
                    begin
                        SalesLine.Get("Demand Subtype", "Demand Order No.", "Demand Line No.");
                        SalesLine.TestField(Type, SalesLine.Type::Item);
                        if not (("Demand Date" = WorkDate) and (SalesLine."Shipment Date" in [0D, WorkDate])) then
                            TestField("Demand Date", SalesLine."Shipment Date");
                        TestField("No.", SalesLine."No.");
                        TestField("Qty. per UOM (Demand)", SalesLine."Qty. per Unit of Measure");
                        TestField("Variant Code", SalesLine."Variant Code");
                        TestField("Location Code", SalesLine."Location Code");
                        SalesLine.CalcFields("Reserved Qty. (Base)");
                        TestField(
                          "Demand Quantity (Base)",
                          -SalesLine.SignedXX(SalesLine."Outstanding Qty. (Base)" - SalesLine."Reserved Qty. (Base)"))
                    end;
                DATABASE::"Prod. Order Component":
                    begin
                        ProdOrderComp.Get("Demand Subtype", "Demand Order No.", "Demand Line No.", "Demand Ref. No.");
                        TestField("No.", ProdOrderComp."Item No.");
                        if not (("Demand Date" = WorkDate) and (ProdOrderComp."Due Date" in [0D, WorkDate])) then
                            TestField("Demand Date", ProdOrderComp."Due Date");
                        TestField("Qty. per UOM (Demand)", ProdOrderComp."Qty. per Unit of Measure");
                        TestField("Variant Code", ProdOrderComp."Variant Code");
                        TestField("Location Code", ProdOrderComp."Location Code");
                        ProdOrderComp.CalcFields("Reserved Qty. (Base)");
                        TestField(
                          "Demand Quantity (Base)",
                          ProdOrderComp."Remaining Qty. (Base)" - ProdOrderComp."Reserved Qty. (Base)");
                        if (ProdOrderChoice = ProdOrderChoice::Planned) and Reserve then
                            ReserveforPlannedProd := true;
                    end;
                DATABASE::"Service Line":
                    begin
                        ServLine.Get("Demand Subtype", "Demand Order No.", "Demand Line No.");
                        ServLine.TestField(Type, ServLine.Type::Item);
                        if not (("Demand Date" = WorkDate) and (ServLine."Needed by Date" in [0D, WorkDate])) then
                            TestField("Demand Date", ServLine."Needed by Date");
                        TestField("No.", ServLine."No.");
                        TestField("Qty. per UOM (Demand)", ServLine."Qty. per Unit of Measure");
                        TestField("Variant Code", ServLine."Variant Code");
                        TestField("Location Code", ServLine."Location Code");
                        ServLine.CalcFields("Reserved Qty. (Base)");
                        TestField(
                          "Demand Quantity (Base)",
                          -ServLine.SignedXX(ServLine."Outstanding Qty. (Base)" - ServLine."Reserved Qty. (Base)"))
                    end;
                DATABASE::"Job Planning Line":
                    begin
                        JobPlanningLine.SetRange("Job Contract Entry No.", "Demand Line No.");
                        JobPlanningLine.FindFirst;
                        JobPlanningLine.TestField(Type, JobPlanningLine.Type::Item);
                        JobPlanningLine.TestField("Job No.");
                        JobPlanningLine.TestField(Status, JobPlanningLine.Status::Order);
                        if not (("Demand Date" = WorkDate) and (JobPlanningLine."Planning Date" in [0D, WorkDate])) then
                            TestField("Demand Date", JobPlanningLine."Planning Date");
                        TestField("No.", JobPlanningLine."No.");
                        TestField("Qty. per UOM (Demand)", JobPlanningLine."Qty. per Unit of Measure");
                        TestField("Variant Code", JobPlanningLine."Variant Code");
                        TestField("Location Code", JobPlanningLine."Location Code");
                        JobPlanningLine.CalcFields("Reserved Qty. (Base)");
                        TestField(
                          "Demand Quantity (Base)",
                          JobPlanningLine."Remaining Qty. (Base)" - JobPlanningLine."Reserved Qty. (Base)")
                    end;
                DATABASE::"Assembly Line":
                    begin
                        AsmLine.Get("Demand Subtype", "Demand Order No.", "Demand Line No.");
                        AsmLine.TestField(Type, AsmLine.Type::Item);
                        if not (("Demand Date" = WorkDate) and (AsmLine."Due Date" in [0D, WorkDate])) then
                            TestField("Demand Date", AsmLine."Due Date");
                        TestField("No.", AsmLine."No.");
                        TestField("Qty. per UOM (Demand)", AsmLine."Qty. per Unit of Measure");
                        TestField("Variant Code", AsmLine."Variant Code");
                        TestField("Location Code", AsmLine."Location Code");
                        AsmLine.CalcFields("Reserved Qty. (Base)");
                        TestField(
                          "Demand Quantity (Base)",
                          -AsmLine.SignedXX(AsmLine."Remaining Quantity (Base)" - AsmLine."Reserved Qty. (Base)"))
                    end;
            end;

            ReqLine2.SetCurrentKey(
              "User ID", "Demand Type", "Demand Subtype", "Demand Order No.", "Demand Line No.", "Demand Ref. No.");
            ReqLine2.SetFilter("User ID", '<>%1', UserId);
            ReqLine2.SetRange("Demand Type", "Demand Type");
            ReqLine2.SetRange("Demand Subtype", "Demand Subtype");
            ReqLine2.SetRange("Demand Order No.", "Demand Order No.");
            ReqLine2.SetRange("Demand Line No.", "Demand Line No.");
            ReqLine2.SetRange("Demand Ref. No.", "Demand Ref. No.");
            ReqLine2.DeleteAll(true);
        end;
    end;

Thanks,
Luís Costa

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
