### ISSUE TITLE
[Event Request] Codeunit 7312 "Create Pick" - OnBeforeGetBinTypeFilter

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#11404]
Hi, would it be possible to get an event **OnBeforeGetBinTypeFilter** in codeunit 7312 (**Create Pick**), like this:

```
procedure GetBinTypeFilter(Type: Option Receive,Ship,"Put Away",Pick,"Put Away only"): Text[1024]
    var
        BinType: Record "Bin Type";
        "Filter": Text[1024];
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetBinTypeFilter(IsHandled);
        if IsHandled then
            exit;
        with BinType do begin
        ...
     end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeGetBinTypeFilter(var IsHandled: Boolean)
begin
end;
```

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
