### ISSUE TITLE
[Event Request] Report 99001017 - OnBeforeShowPlanningErrorLog

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11400]
Please add a new Publisher Call OnBeforeShowPlanningErrorLog in Procedure CloseWindow of Report 99001017 "Calculate Plan - Plan. Wksh."

Add Call of Publisher in Procedure CloseWindow

````
        if Counter > CounterOK then begin
            Message(Text007, Counter - CounterOK);
-           if PlanningErrorLog.FindFirst then
-               PAGE.RunModal(0, PlanningErrorLog);
+           if PlanningErrorLog.FindFirst then begin
+               OnBeforeShowPlanningErrorLog(Item, PlanningErrorLog);
+               PAGE.RunModal(0, PlanningErrorLog);
+           end;
        end;
````

New Publisher:

````
+    [IntegrationEvent(false, false)]
+    local procedure OnBeforeShowPlanningErrorLog(Item: Record Item; var PlanningErrorLog: Record "Planning Error Log")
+    begin
+    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
