### ISSUE TITLE
Error in FIK app: Payment and Reconciliation Formats (DK)

### ISSUE THREAD

**Issue by it-ribe** [microsoft/ALAppExtensions#11412]
When exporting payment files from Payment Journal, it hits COD13653 (3 places).
Here it tries to find a EMU currency regardless if you use currency or EMU currency.
This should be change to be conditional if findfirst is true.

![image](https://user-images.githubusercontent.com/42299148/109618203-8df51900-7b37-11eb-9fea-e54bd567a1e1.png)

![image](https://user-images.githubusercontent.com/42299148/109618603-065bda00-7b38-11eb-9536-3ae596d564fe.png)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.

**Comment by it-ribe** [comment]
It IS related!!
I have itendfied the culprint.
If i uninstall the extensions all works fine.

**Comment by StanPesotskiy** [comment]
Please put the complete repro steps to the relevant support channel.
