### ISSUE TITLE
Extend No. of Address Array from 8 to 10 (or as a list)

### ISSUE THREAD

**Issue by AdamRicks** [Microsoft/ALAppExtensions#1141]
Is it possible to extend the address arrays from 8 to 10 (or to define them as a list)?
In the German environment a name 3 and a Packstationnr. is not unusual, so that 8 address fields can be too few.

**Comment by JesperSchulz** [comment]
Thanks for sharing your idea with us. We're always looking for better ways to do things. However, this isn't the right place to share it. You'll have better luck getting it implemented and noticed by other partners if you post it to the following resources:

- For functional improvements, go to [Business Central - Ideas](http://aka.ms/bcideas)
- For feature suggestions for the AL compiler and developer tools, visit [Github.com/Microsoft/AL](https://github.com/Microsoft/AL/issues)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
