### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnUpdatePurchLinesByFieldNoOnBeforeValidateFields

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11416]
Hello. In table 38 Purchase Header, in the procedure UpdatePurchLinesByFieldNo, I would like to use the event publisher OnUpdatePurchLinesByFieldNoOnBeforeValidateFields to add my own code instead of the standard one inside the case of statement. But I need the parameters Rec and IsHandled, and a IsHandled flag to do so. Like this :

    procedure UpdatePurchLinesByFieldNo(ChangedFieldNo: Integer; AskQuestion: Boolean)
    ...
    OnUpdatePurchLinesByFieldNoOnBeforeValidateFields(PurchLine, xPurchLine, ChangedFieldNo, Rec, IsHandled);
    if not IsHandled then
        case ChangedFieldNo of

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnUpdatePurchLinesByFieldNoOnBeforeValidateFields(var PurchaseLine: Record "Purchase Line"; xPurchaseLine: Record "Purchase Line"; ChangedFieldNo: Integer; var PurchaseHeader : record "Purchase Header"; var IsHandled : boolean)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
