### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnAfterUpdatePurchLinesByFieldNo

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11417]
Hello. In table 38 Purchase Header, in the procedure UpdatePurchLinesByFieldNo, I would like to add my own code just after the last Case... OF statement. To do so, I would need an event publisher, just here :

    procedure UpdatePurchLinesByFieldNo(ChangedFieldNo: Integer; AskQuestion: Boolean)
                ...
                end;
                OnAfterUpdatePurchLinesByFieldNo(Rec, xRec, PurchLine);
                PurchLine.Modify(true);
                PurchLineReserve.VerifyChange(PurchLine, xPurchLine);
            until PurchLine.Next() = 0;
    end;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdatePurchLinesByFieldNo(var PurchaseHeader : record "Purchase Header"; var xPurchaseHeader : record "Purchase Header"; PurchaseLine: Record "Purchase Line")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
