### ISSUE TITLE
[Event Request] Codeunit 5845 "Get Inventory Report" - OnDrillDownGLBeforeRunPage

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#11411]
Hi, would it be possible to get an event **OnDrillDownGLBeforeRunPage** in codeunit 5845 (**Get Inventory Report**), like this:

```
local procedure DrillDownGL(var InvtReportEntry: Record "Inventory Report Entry")
    var
        GLEntry: Record "G/L Entry";
    begin
        with GLEntry do begin
            SetRange("G/L Account No.", InvtReportEntry."No.");
            SetFilter("Posting Date", InvtReportEntry.GetFilter("Posting Date Filter"));
            OnDrillDownGLBeforeRunPage(GLEntry,InvtReportEntry);
            PAGE.Run(0, GLEntry, Amount);
        end;
    end;
```

```
[IntegrationEvent(false, false)]
local procedure OnDrillDownGLBeforeRunPage(var GLEntry: Record "G/L Entry"; var InvtReportEntry: Record "Inventory Report Entry")
begin
end;
```

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
