### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnBeforeConfirmResvDateConflict

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11415]
Hello. In table 38 "Purchase Header", in procedure UpdatePurchLines, we would like to expend the value set of the "CASE ChangedFieldName OF" statement. To do so, we would need to send the parameter ChangedFieldName to the procedure ConfirmResvDateConflict(), and then to the event publisher OnBeforeConfirmResvDateConflict, in order to add a new CASE ChangedFieldName OF ... in our event subscriber. Like this : 

    local procedure ConfirmResvDateConflict(ChangedFieldNo: Integer)
    var
        ResvEngMgt: Codeunit "Reservation Engine Mgt.";
        ConfirmManagement: Codeunit "Confirm Management";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeConfirmResvDateConflict(Rec, IsHandled, ChangedFieldNo);
        if IsHandled then
            exit;

        if ResvEngMgt.ResvExistsForPurchHeader(Rec) then
            if not ConfirmManagement.GetResponseOrDefault(Text050, true) then
                Error('');
    end;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeConfirmResvDateConflict(var PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean; ChangedFieldNo: Integer)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
