### ISSUE TITLE
[Event Request] Codeunit 5895 "Inventory Adjustment" - OnAdjustItemAvgCostAfterRestart,OnAdjustItemAvgCostAfterLastTempTempAvgCostAdjmtEntryPoint

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#11426]
Hi, would it be possible to get an event **OnAdjustItemAvgCostAfterRestart** and **OnAdjustItemAvgCostAfterLastTempTempAvgCostAdjmtEntryPoint** in codeunit 5895 (**Inventory Adjustment**), like this:

```
local procedure AdjustItemAvgCost()
    var
        TempOutbndValueEntry: Record "Value Entry" temporary;
        TempExcludedValueEntry: Record "Value Entry" temporary;
        TempAvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point" temporary;
        AvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point";
        PeriodFormMgt: Codeunit PeriodFormManagement;
        RemainingOutbnd: Integer;
        Restart: Boolean;
        EndOfValuationDateReached: Boolean;
        IsHandled: Boolean;
    begin
        if not IsAvgCostItem() then
            exit;

        UpDateWindow(WindowAdjmtLevel, WindowItem, Text008, WindowFWLevel, WindowEntry, 0);
        ...
        with AvgCostAdjmtEntryPoint do
            while AvgCostAdjmtEntryPointExist(TempAvgCostAdjmtEntryPoint) do begin
                repeat
                    ...
                     while not Restart and AvgValueEntriesToAdjustExist(
                            TempOutbndValueEntry, TempExcludedValueEntry, AvgCostAdjmtEntryPoint) and not EndOfValuationDateReached
                    do begin
                        ...
                        Restart := FindFirst and not "Cost Is Adjusted";
                        OnAdjustItemAvgCostAfterRestart(TempExcludedValueEntry,Restart);
                    end;
                until (TempAvgCostAdjmtEntryPoint.Next = 0) or Restart;
                IsHandled := false;
                OnAdjustItemAvgCostAfterLastTempTempAvgCostAdjmtEntryPoint(IsHandled);
                if IsHandled then
                    break;
            end;
    end;
```

```
[IntegrationEvent(false, false)]
local procedure OnAdjustItemAvgCostAfterRestart(var TempExcludedValueEntry: Record "Value Entry" temporary; var Restart: Boolean)
begin
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnAdjustItemAvgCostAfterLastTempTempAvgCostAdjmtEntryPoint(var IsHandled: Boolean)
begin
end;
```

Thanks

**Comment by StanPesotskiy** [comment]
There are no additional parameters in OnAdjustItemAvgCostAfterLastTempTempAvgCostAdjmtEntryPoint. 
Do you want to exit unconditionally? E.g. there is Restart that can also cause the exit from the repeat until loop.
Can't you adjust TempAvgCostAdjmtEntryPoint in the event inside the loop somehow that after the first run of the while loop AvgCostAdjmtEntryPointExist(TempAvgCostAdjmtEntryPoint) would return false?

**Comment by SteinleMossFeldhaus** [comment]
No we can't do that. We dont want to exit the while loop after the first run. In the first Event we set the Restart under a certain condition to false. So that won't work either.

**Comment by StanPesotskiy** [comment]
So if you want to manage the number of runs through the Restart variable it should be passed to the event OnAdjustItemAvgCostAfterLastTempTempAvgCostAdjmtEntryPoint or otherwise if you subscribed and retirned IsHandled = true you will always finish the while loop after the first run.

**Comment by SteinleMossFeldhaus** [comment]
We set Restart in the OnAdjustItemAvgCostAfterRestart event as needed.
We dont manage the number of runs through the Restart variable in the event OnAdjustItemAvgCostAfterLastTempTempAvgCostAdjmtEntryPoint instead we will set a variable in OnAdjustItemAvgCostAfterRestart and if that variable is set in the OnAdjustItemAvgCostAfterLastTempTempAvgCostAdjmtEntryPoint we set IsHandled true. Through the Restart Variable we actually dont know if it is handled or not. We have to use our own variable otherwise the inner loop wouldn't work.

We need the Restart variable in the first event because it is a condition for our own variable.

If you think that it only makes sense, to pass Restart in both events, then do so.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
