### ISSUE TITLE
Request for remove local in Page::"FA Depreciation Books Subform"

### ISSUE THREAD

**Issue by CL2-SWECON** [microsoft/ALAppExtensions#11425]
In Page::"FA Depreciation Books Subform"

please remove local from following procedures

1. ShowFALedgEntries
2. ShowFAErrorLedgEntries
3. ShowMaintenanceLedgEntries
4. ShowStatistics
5. ShowMainAssetStatistics

We have another MainPage that uses these procedures...

**Comment by AlexanderYakunin** [comment]
Please explain how you would like to use it? These procedures works in scope of subform, why do you need global access? Or should you use protected?

**Comment by CL2-SWECON** [comment]
We have the actions for these procedures in the menu of its main-page to make the usability for the user more comfortable. With local procedures this won´t work.

**Comment by AlexanderYakunin** [comment]
There is no Depreciation Book Code field on main FA page, so these functions cannot be used there. Instead you need to create you own functions without filtering on Depreciation Book Code. No need to use local functions from sub form.
