### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnInitFromVendorOnAfterInit

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11427]
Hello. In table 38 Purchase Header, in the procedure InitFromVendor, I would like to give a value to one my fields after the init in some cases. To do so, I would need an event publisher just after the Init method, and before the GetPurchSetup() procedure. Like this :

    local procedure InitFromVendor(VendorNo: Code[20]; VendorCaption: Text): Boolean
    begin
        PurchLine.SetRange("Document Type", "Document Type");
        PurchLine.SetRange("Document No.", "No.");
        if VendorNo = '' then begin
            if not PurchLine.IsEmpty() then
                Error(Text005, VendorCaption);
            Init;
      
            OnInitFromVendorOnAfterInit(Rec, xRec);

            GetPurchSetup();
            "No. Series" := xRec."No. Series";
            OnInitFromVendorOnBeforeInitRecord(Rec, xRec);
            InitRecord;
            InitNoSeries;
            exit(true);
        end;
    end;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnInitFromVendorOnBeforeInitRecord( var PurchaseHeader : record "Purchase Header"; xPurchaseHeader: Record "Purchase Header")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by StanPesotskiy** [comment]
InitRecord is started with GetPurchSetup(); so I will just remove the call of GetPurchSetup(); in InitFromVendor so OnInitFromVendorOnBeforeInitRecord will be the event to subscribe.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
