### ISSUE TITLE
Enum and Event Request for "Bank Payment Type"

### ISSUE THREAD

**Issue by crisnicolas** [microsoft/ALAppExtensions#1142]
I would like to have the following Option fields converted to enums:

- Table 81 Gen. Journal Line. Field 70 **Bank Payment Type**
- Table 721 Standard Gen. Journal Line. Field 70 **Bank Payment Type**
- Table 272 Check Ledger Entry. Field 12 **Bank Payment Type**

If possible, I would like them to be the same enum used on the 3 tables, instead of 3 different enums, as they are actually the same field replicated in different tables.

And, I would also like this enum to be used in Report 393 Suggest Vendor Payments.
In this report, global variable **BankPmtType** is an option variable that defines the same options that the Bank Payment Type field has on the various tables mentioned.

To be able to extend this enum, some additional events should also be introduced or modified:

- Codeunit 12 Gen. Jnl.-Post Line. Procedure **PostBankAcc**
After the Bank Account Ledger Entry has been inserted, an IF and a CASE decide if a Check Ledger Entry has to be created whenever Bank Payment Type is either Manual Check or Computer Check
I would like to have an event here to be able to decide if a Check Ledger Entry has to be created when the value of Bank Payment Type is one of the values of the enum that I’ve extended.
 There is a workaround here. The already existing OnPostBankAccOnAfterBankAccLedgEntryInsert() event could be used. But a specific event to create Check Ledger Entries would be better.

- Codeunit 367 CheckManagement. Procedure **VoidCheck**
There is an event here OnBeforeVoidCheck, but it does not implement the Handled pattern.
Right after the event, the following line of code
GenJnlLine.TESTFIELD("Bank Payment Type",GenJnlLine2."Bank Payment Type"::"Computer Check"); 
will fail for any of the extended values of Bank Payment Type.

- Codeunit 367 CheckManagement. Procedure **FinancialVoidCheck**
There is an event here OnBeforeFinancialVoidCheck, but it does not implement the Handled pattern.
So, the ledger entries that this procedure creates cannot be avoided in case we have an extended value of Bank Payment Type for which we want to create Check Ledger Entries, but not intermediate financial transactions.

Thanks

**Comment by crisnicolas** [comment]
Hello,

Are there any news on this request?

Regards,
Cristina Nicolàs

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
