### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnBeforeDeletePurchaseLines

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11424]
Hello. In table 38 Purchase Header, in the procedure DeletePurchaseLines, I would like to use the event publisher OnBeforeDeletePurchaseLines to add my own code. But I need the parameter Rec. Like this :

    local procedure DeletePurchaseLines()
    begin
        IsHandled := false;
        OnBeforeDeletePurchaseLines(Rec, PurchLine, IsHandled);
        if IsHandled then
            exit;
    ...
    end;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeletePurchaseLines(var PurchaseHeader : record "Purchase Header"; var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
