### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnRecreateTempPurchLinesOnAfterTempPurchLineInsert

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11439]
Hello. In table 38 Purchase Header, in the procedure RecreateTempPurchLines, I would like to use the event publisher OnRecreateTempPurchLinesOnAfterTempPurchLineInsert to add my own code. But I need the parameter PurchLine. Like this :

    local procedure RecreateTempPurchLines(var TempPurchLine: Record "Purchase Line")
    begin
        repeat
            TestPurchLineFieldsBeforeRecreate();
            TempPurchLine := PurchLine;
            if PurchLine.Nonstock then begin
                PurchLine.Nonstock := false;
                PurchLine.Modify();
            end;
            OnRecreatePurchLinesOnBeforeTempPurchLineInsert(TempPurchLine, PurchLine);
            TempPurchLine.Insert();
            OnRecreateTempPurchLinesOnAfterTempPurchLineInsert(Rec, PurchLine);
        until PurchLine.Next() = 0;
    end;

With this event integrationn : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeletePurchaseLines(var PurchaseHeader : record "Purchase Header"; var PurchLine : Record "Purchase Line")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
