### ISSUE TITLE
Add "Serial No." to an existing event ("Lot No." is already added)

### ISSUE THREAD

**Issue by rwe12345** [microsoft/ALAppExtensions#11430]
In codeunit 7326 "Whse. Item Tracking FEFO" there is an event OnAfterIsItemTrackingBlocked in function IsItemTrackingBlocked.
This event has already an parameter "Lot No." from the item tracking setup.
Please add "Serial No." from the Item tracking sutup.

Current line:
OnAfterIsItemTrackingBlocked(SourceReservationEntry, ItemNo, VariantCode, ItemTrackingSetup."Lot No.", IsBlocked);

Example:
OnAfterIsItemTrackingBlocked(SourceReservationEntry, ItemNo, VariantCode, ItemTrackingSetup."Lot No.", **ItemTrackingSetup."Serial No."**, IsBlocked);

![Procedure IsItemTrackingBlocked](https://user-images.githubusercontent.com/44321194/109679880-4349c000-7b7c-11eb-9488-8107e2f4fd7c.png)

**Comment by AlexanderYakunin** [comment]
In latest version we already have this, so you can use ItemTrackingSetup parameter for all tracking data:

    [IntegrationEvent(false, false)]
    local procedure OnAfterIsItemTrackingBlocked(var ReservEntry: Record "Reservation Entry"; ItemNo: Code[20]; VariantCode: Code[10]; LotNo: Code[50]; var IsBlocked: Boolean; ItemTrackingSetup: Record "Item Tracking Setup")
    begin
    end;
