### ISSUE TITLE
Filter on "Responsibility Center" on pages is not always in the same way. 

### ISSUE THREAD

**Issue by rwe12345** [microsoft/ALAppExtensions#11432]
Filter on "Responsibility Center" on pages is not always in the same way. Please use a function with an event. Just like on the sales credit memo page.

Sales
On the sales credit memo page the filter on "Responsibility Center" will be set by the function SetSecurityFilterOnRespCenter

 
![image](https://user-images.githubusercontent.com/44321194/109707592-a1859b80-7b9a-11eb-9efd-543ef1a6398a.png)

On the sales order list page the filter on the "Responsibility Center" is set with a filter in the “OnOpenPage” 
 
![image](https://user-images.githubusercontent.com/44321194/109707616-a9ddd680-7b9a-11eb-9e20-60a80382fce3.png)

Please change this and make it equal as the sales credit memo page with a function and an event.
Idem voor :
SetRange("Responsibility Center", UserMgt.GetSalesFilter);

page 41 "Sales Quote"
page 42 "Sales Order"
page 43 "Sales Invoice"
page 44 "Sales Credit Memo"
page 507 "Blanket Sales Order"
page 6630 "Sales Return Order"
page 9305 "Sales Order List"

 
Purchase

Also for the next purchase documents:

SetRange("Responsibility Center", UserMgt.GetPurchasesFilter);

page 49 "Purchase Quote"
page 50 "Purchase Order"
page 51 "Purchase Invoice"
page 52 "Purchase Credit Memo"
page 509 "Blanket Purchase Order"
page 6640 "Purchase Return Order"

In the purchase header table is an event available (OnBeforeSetSecurityFilterOnRespCenter). 
![image](https://user-images.githubusercontent.com/44321194/109707691-bf530080-7b9a-11eb-91c1-62e6a05cd91e.png)
 
This filter is not available in the 
table 120 "Purch. Rcpt. Header"
table 122 "Purch. Inv. Header"
table 124 "Purch. Cr. Memo Hdr."
table 5109 "Purchase Header Archive"
table 6650 "Return Shipment Header"

 
Also for the next service documents: 
SetRange("Responsibility Center", UserMgt.GetServiceFilter);

table 5965 "Service Contract Header"
page 5900 "Service Order"
page 5915 "Service Tasks"
page 5964 "Service Quote"
page 6000 "Dispatch Board"
page 6050 "Service Contract"
page 6053 "Service Contract Quote"

In the purchase header table is an event available (OnBeforeSetSecurityFilterOnRespCenter). 
 
![image](https://user-images.githubusercontent.com/44321194/109707709-c548e180-7b9a-11eb-8136-708eb72cc4d4.png)

This filter is not available in the 
table 5900 "Service Header"
table 5990 "Service Shipment Header"
table 5992 "Service Invoice Header"
table 5994 "Service Cr.Memo Header"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
