### ISSUE TITLE
[Event Request] Codeunit 1218 "Map Incoming Doc to Purch Doc" - OnProcessLinesNotFound

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#11445]
Hello,

Please add a new publisher event in function ProcessLines as follows:

    local procedure ProcessLines(PurchaseHeader: Record "Purchase Header"; DataExch: Record "Data Exch."; ParentRecordNo: Integer)
    var
        IntermediateDataImport: Record "Intermediate Data Import";
        RecRef: RecordRef;
        CurrRecordNo: Integer;
    begin
        CurrRecordNo := -1;

        with IntermediateDataImport do begin
            SetRange("Data Exch. No.", DataExch."Entry No.");
            SetRange("Table ID", DATABASE::"Purchase Line");
            SetRange("Parent Record No.", ParentRecordNo);
            SetCurrentKey("Record No.");

            if not FindSet then begin
                OnProcessLinesNotFound(DataExch, PurchaseHeader);
                exit;
            end;

New Publisher event:
    [IntegrationEvent(false, false)]
    local procedure OnProcessLinesNotFound(var DataExch: Record "Data Exch."; var PurchaseHeader: Record "Purchase Header")
    begin
    end;

The functional value of adding this event:
In a later request, we asked for an event to skip the creation of a purchase line for the total document amount (https://github.com/microsoft/ALAppExtensions/issues/10196).

There can be situations when there is no line to be processed when getting to this ProcessLines function.
In the Incoming Document, there is a field called Order No. We have a development task to create purchase lines based on the Order No. In case there is no line to be processed, we need this new event to create purchase lines based on the Order No,

**Comment by CameliaPopescu** [comment]
version to implement the event >=17.4

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
