### ISSUE TITLE
[Request-for-external] Table 38 "Purchase Header" - TransferSavedFieldsDropShipment

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11441]
Hello. In table 38 Purchase Header, in the procedure RecreatePurchLines, I would like to use the event publisher OnRecreatePurchLinesOnBeforeTransferSavedFields to add my own code instead of the standard one. From my event subscriber, I would like to use local procedure TransferSavedFieldsDropShipment, but it is local one. Is possible to pass it in global please ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
