### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnAfterRecreatePurchLine

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11456]
Hello. In table 38 Purchase Header, in the procedure RecreatePurchLines, I would like to use the event publisher OnAfterRecreatePurchLine to add my own code. But I need the parameter Rec in it. Like this :

     OnAfterRecreatePurchLine(Rec, PurchLine, TempPurchLine);

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnAfterRecreatePurchLine(var PurchaseHeader: Record "Purchase Header"; var PurchLine : record "Purchase Line"; var TempPurchLine: Record "Purchase Line" temporary)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
