### ISSUE TITLE
[Event Request] Codeunit 5850 "Invt. Doc.-Post Receipt" - OnAfterCopyItemJnlLineFromInvtReceiptLine

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/ALAppExtensions#11453]
Would it be possible to add an event for this new feature?

```
local procedure PostItemJnlLine(InvtRcptHeader2: Record "Invt. Receipt Header"; InvtRcptLine2: Record "Invt. Receipt Line")
        //...

        OriginalQuantity := ItemJnlLine.Quantity;
        OriginalQuantityBase := ItemJnlLine."Quantity (Base)";

        **OnAfterCopyItemJnlLineFromInvtReceiptLine(InvtRcptHeader2, InvtRcptLine2, ItemJnlLine);**

        ItemJnlPostLine.RunWithCheck(ItemJnlLine);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
