### ISSUE TITLE
[Event Request] Codeunit 5850 "Invt. Doc.-Post Receipt" - OnBeforeInsertInvtRcptHeader

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/ALAppExtensions#11454]
```
trigger OnRun()
            //...
            InvtRcptHeader."Posting Description" := "Posting Description";
            InvtRcptHeader.Correction := Correction;
            InvtRcptHeader."Dimension Set ID" := "Dimension Set ID";

            **OnBeforeInsertInvtRcptHeader(InvtDocHeader, InvtRcptHeader)**;

            InvtRcptHeader.Insert();
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
