### ISSUE TITLE
[Event Request] Codeunit 7310 "Whse.-Shipment Release" - OnReleaseBeforeWhseShipLineIsEmpty

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#11451]
Hi, would it be possible to get an event **OnReleaseBeforeWhseShipLineIsEmpty** in codeunit 7310 (**Whse.-Shipment Release**), like this:

```
procedure Release(var WhseShptHeader: Record "Warehouse Shipment Header")
    var
        Location: Record Location;
        WhsePickRqst: Record "Whse. Pick Request";
        WhseShptLine: Record "Warehouse Shipment Line";
        ATOLink: Record "Assemble-to-Order Link";
        AsmLine: Record "Assembly Line";
        IsHandled: Boolean;
    begin
        with WhseShptHeader do begin
            if Status = Status::Released then
                exit;

            OnBeforeRelease(WhseShptHeader);

            WhseShptLine.SetRange("No.", "No.");
            WhseShptLine.SetFilter(Quantity, '<>0');
            IsHandled := false;
            OnReleaseBeforeWhseShipLineIsEmpty(WhseShptLine,IsHandled);
            if not IsHandled then
              if not WhseShptLine.Find('-') then
                  Error(Text000, TableCaption, "No.");
            ...
    end;
```

```
[IntegrationEvent(false, false)]
local procedure OnReleaseBeforeWhseShipLineIsEmpty(var WhseShptLine: Record "Warehouse Shipment Line"; var IsHandled: Boolean)
begin
end;
```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by CL2-SWECON** [comment]
When (in which version) do you provide the fix for this issue?

**Comment by JesperSchulz** [comment]
This will ship with 18.1 any day now.

**Comment by CL2-SWECON** [comment]
Thank you for information, Jesper.
Is it possible to prvide this information (in which version will a fix shipped) for all issues by default?
This would be very very helpful for everyone.

**Comment by JesperSchulz** [comment]
Unfortunately it has proven to be difficult to do that, as we backport event requests from our master branch to our release branch in batches, rather than as individual issues. By doing to, the link between the GitHub issue and our internal work items are lost. You are not alone with your request and I will try to bring it up once more, but so far the decision has always been to prioritize efficiency in the backport process rather than traceability.
