### ISSUE TITLE
[Request for External] table 77 "Report Selections" - GetEmailAddressIgnoringLayout

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#11479]
You we please get acces to the procedure `GetEmailAddressIgnoringLayout` table 77 "Report Selections" ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
