### ISSUE TITLE
[Event Request] Codeunit 1151 "COHUB Core" - OnBeforeGetFixedWebServicesUrl

### ISSUE THREAD

**Issue by Mike-1984** [microsoft/ALAppExtensions#11474]
Hello colleagues,

I know that CompanyHub extension is promoted to be used only in the cloud, but is it possible to extend it with some events, so we can adapt it to the On-Premise environment?

For instance, is it possible to implement the folowing event:

```
codeunit 1151 "COHUB Core"
...
    procedure GetFixedClientUrl(): Text;
    var
        IsHandled: Boolean;
        Result: Text;
    begin
        IsHandled := false;
        OnBeforeGetFixedClientUrl(Result, IsHandled);
        if IsHandled then
            exit(Result);
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetFixedClientUrl(var Result: Text; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
