### ISSUE TITLE
Insider built - Crash when opening company: Could not open the '' company. Call to the function 'INSERT' is not allowed inside the call to 'TryDownloadCompanyDetailsFromMicrosoft365' when it is used as a TryFunction. Date and time: F

### ISSUE THREAD

**Issue by mhenricus** [microsoft/ALAppExtensions#11477]
**Describe the bug**
Client crashes when opening a newly created company where setting 'Enable Assisted Company Setup' is check marked.

**To Reproduce**
Steps and to reproduce the behavior:
- Create a new Company in page Companies, with the Action 'Create New Company'.
- Check mark 'Enable Assisted Company Setup'
- Open the new company in the browser.
- A strmenu is shown with the question: The extension 'Base Application by Microsoft' is making a request to an external service. - Do you want to allow this request?
- Whatever option is chosen, the client crashes

``` AL Code to reproduce the issue ```
- None

**Expected behavior**
- No crash

**Screenshots**
![image](https://user-images.githubusercontent.com/69308907/109277738-01391b00-7818-11eb-9995-d687a0ee1ff9.png)

![image](https://user-images.githubusercontent.com/69308907/109277642-e5357980-7817-11eb-8435-a367141afb5f.png)

![image](https://user-images.githubusercontent.com/69308907/109277710-f8e0e000-7817-11eb-87c9-074368afb100.png)

**5. Versions:**

 - AL Language: na

 - Business Central: Version: W1 19.0 (Platform 18.0.22439.0 + Application 19.0.22474.0)

Docker container

**Comment by PooyaKharamesh** [comment]
This repository is no longer dedicated to handling application requests and enhancements. 
Instead please use the following repository: https://github.com/Microsoft/ALAppExtensions
