### ISSUE TITLE
[Event Request] New IntegrationEvent in Table 7320 "Warehouse Shipment Header", function DeleteWarehouseShipmentLines

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#11484]
Hello,

please insert new IntegrationEvent in Table 7320 "Warehouse Shipment Header", function DeleteWarehouseShipmentLines

    local procedure DeleteWarehouseShipmentLines()
    var
        WhseShptLine: Record "Warehouse Shipment Line";
        Confirmed: Boolean;
        IsHandled: Boolean;
    begin
        // Start kvs.dde
        OnBeforeDeleteWarehouseShipmentLines(Rec, isHandled);
        if isHandled then begin
            exit;
        end;
        // Stop kvs.dde  

        WhseShptLine.SetRange("No.", "No.");
        if WhseShptLine.Find('-') then
            repeat
                if WhseShptLine."Qty. Shipped" < WhseShptLine."Qty. Picked" then begin
                    IsHandled := false;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
