### ISSUE TITLE
[Request for External] codeunit 409 "Dimension Value-Indent"

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#11487]
Can you add a procedure in codeunit 409 "Dimension Value-Indent" to run Indent without Confirm, but with filter on "Dimension Code".

Ex:
```
    procedure Indent(DimensionValue: Record "Dimension Value")
    begin
        DimVal.SetRange("Dimension Code", DimensionValue."Dimension Code");
        Indent;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
