### ISSUE TITLE
[Event Request] Table 1003 "Job Planning Line" - OnAfterAssignFieldsForNo

### ISSUE THREAD

**Issue by tdkumar** [microsoft/ALAppExtensions#11485]
HI,

Need an Event for Table "Job Planning Line", "No." field OnValidate trigger, as we are extending "Type"(Enum) field.

        field(7; "No."; Code[20])
        {
            Caption = 'No.';
            TableRelation = IF (Type = CONST(Resource)) Resource
            ELSE
            IF (Type = CONST(Item)) Item WHERE(Blocked = CONST(false))
            ELSE
            IF (Type = CONST("G/L Account")) "G/L Account"
            ELSE
            IF (Type = CONST(Text)) "Standard Text";

            trigger OnValidate()
            begin
                ValidateModification(xRec."No." <> "No.");

                CheckUsageLinkRelations;

                UpdateReservation(FieldNo("No."));

                UpdateDescription;

                if ("No." = '') or ("No." <> xRec."No.") then begin
                    "Unit of Measure Code" := '';
                    "Qty. per Unit of Measure" := 1;
                    "Variant Code" := '';
                    "Work Type Code" := '';
                    "Gen. Bus. Posting Group" := '';
                    "Gen. Prod. Posting Group" := '';
                    DeleteAmounts;
                    "Cost Factor" := 0;
                    if Type = Type::Item then begin
                        "Bin Code" := '';
                        if ("No." <> '') and ("Location Code" <> '') then begin
                            GetLocation("Location Code");
                            if IsDefaultBin() then
                                WMSManagement.GetDefaultBin("No.", "Variant Code", "Location Code", "Bin Code");
                        end;
                    end;
                    if "No." = '' then
                        exit;
                end;

                GetJob;
                "Customer Price Group" := Job."Customer Price Group";
                "Price Calculation Method" := Job.GetPriceCalculationMethod();
                "Cost Calculation Method" := Job.GetCostCalculationMethod();

                case Type of
                    Type::Resource:
                        CopyFromResource();
                    Type::Item:
                        CopyFromItem();
                    Type::"G/L Account":
                        CopyFromGLAccount();
                    Type::Text:
                        CopyFromStandardText();
                end;
                
                **//New Event begin**
                OnAfterAssignFieldsForNo(Rec, xRec);
                **//New Event end**

                if Type <> Type::Text then
                    Validate(Quantity);
            end;
        }

New Event:

    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignFieldsForNo(var JobPlanningLine: Record "JobPlanning Line"; var xJobPlanningLine: Record "Job Planning Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
