### ISSUE TITLE
Event Request: Codeunit 5940 "ServContractManagement"

### ISSUE THREAD

**Issue by Roberto-cyber** [microsoft/ALAppExtensions#11481]
We need an event in the function "CreateServiceLedgerEntry":

CreateServiceLedgerEntry(ServHeader2 : Record "Service Header";ContractType : Integer;ContractNo : Code[20];InvFrom : Date;InvTo : Date;SigningContract : Boolean;AddingNewLines : Boolean;LineNo : Integer) ReturnLedgerEntry : Integer
ServiceContractHeaderFound := ServContractHeader.GET(ContractType,ContractNo);
IF NOT ServiceContractHeaderFound OR (ServContractHeader."Invoice Period" = ServContractHeader."Invoice Period"::None) THEN
  EXIT;

ServContractHeader.CALCFIELDS("Calcd. Annual Amount");
CheckServiceContractHeaderAmts(ServContractHeader);
Currency.InitRoundingPrecision;
ReturnLedgerEntry := NextEntry;
CLEAR(ServLedgEntry);
InitServLedgEntry(ServLedgEntry,ServContractHeader,ServHeader2."No.");
CLEAR(NonDistrAmount);
CLEAR(InvAmount);
CLEAR(InvRoundedAmount);

IF ServContractHeader.Prepaid AND NOT SigningContract THEN BEGIN
  ServLedgEntry."Moved from Prepaid Acc." := FALSE;
  FirstLineEntry := NextEntry;
  FilterServContractLine(
    ServContractLine,ServContractHeader."Contract No.",ServContractHeader."Contract Type",LineNo);
  IF AddingNewLines THEN
    ServContractLine.SETRANGE("New Line",TRUE)
  ELSE
    ServContractLine.SETFILTER("Starting Date",'<=%1|%2..%3',ServContractHeader."Next Invoice Date",
      ServContractHeader."Next Invoice Period Start",ServContractHeader."Next Invoice Period End");
  IF ServContractLine.FIND('-') THEN BEGIN
    REPEAT
      YearContractCorrection := FALSE;
      Days := 0;
      WDate := CALCDATE('<-CM>',InvFrom);
      IF (InvFrom <= ServContractLine."Contract Expiration Date") OR
         (ServContractLine."Contract Expiration Date" = 0D)
      THEN BEGIN
        NoOfPayments := 0;
        REPEAT
          NoOfPayments := NoOfPayments + 1;
          WDate := CALCDATE('<1M>',WDate);
        UNTIL (WDate >= InvTo) OR
              ((WDate > ServContractLine."Contract Expiration Date") AND
               (ServContractLine."Contract Expiration Date" <> 0D));
        CountOfEntryLoop := NoOfPayments;

**EventNameRequest(ServContractHeader, var CountOfEntryLoop);**

        // Partial period ranged by "Starting Date" and end of month. Full period is shifted by one month
        IF ServContractLine."Starting Date" > InvFrom THEN BEGIN
          Days := CALCDATE('<CM>',InvFrom) - ServContractLine."Starting Date";
          PartInvFrom := ServContractLine."Starting Date";
          PartInvTo := CALCDATE('<CM>',InvFrom);
          InvFrom := PartInvFrom;
          NewInvFrom := CALCDATE('<CM+1D>',InvFrom);
          CountOfEntryLoop := CountOfEntryLoop - 1;
          NoOfPayments := NoOfPayments - 1;
        END;

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
