### ISSUE TITLE
[Event Request] Codeunit 91 Purch.-Post (Yes No) - OnBeforeRun

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#11486]
Hi, would it be possible to get an event OnBeforeRun in codeunit 91, trigger OnRun, like this : 
```
    trigger OnRun()
    var
        PurchaseHeader: Record "Purchase Header";
    begin
        
        OnBeforeRun(PurchaseHeader);
        if not Find then
            Error(NothingToPostErr);

        PurchaseHeader.Copy(Rec);
        Code(PurchaseHeader);
        Rec := PurchaseHeader;
    end;

```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeRun(var PurchaseHeader: Record "Purchase Header")
    begin
    end;

```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
