### ISSUE TITLE
Please Convert  field Shipping Advice to enum in "Sales Header" 

### ISSUE THREAD

**Issue by raawasthi** [microsoft/ALAppExtensions#1148]
Hi Team,

We need to add few more option for field Shipping Advice. But it is a option field not enum so we can't.
Please convert it to enum so that we can extend it and add one more option in this field.

Best Regards,
Ratnesh Awasthi

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
