### ISSUE TITLE
[Enum Request] WantedMatrixSet

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#11492]
Please provide an new "WantedMatrixSet" Enum with these valeus:
Initial, Previous, Same, Next, PreviousColumn, NextColumn

In the Base Application this Options are mostly referenced as `SetWanted`-Variable.

Since many Partners using the same option in there matrix pages it would be useful when we could all use the same enum.

I think extensibility is not Required at this Time.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
