### ISSUE TITLE
In Event Request "OnAfterApplyItemLedgEntrySetFilters" in Codeunit 22 Please add two more parameter ItemJournalLine & ItemTrackingcode 

### ISSUE THREAD

**Issue by raawasthi** [microsoft/ALAppExtensions#1149]
Hi Team,

In Event Request "OnAfterApplyItemLedgEntrySetFilters" in Codeunit 22 Please add two more parameter ItemJournalLine & ItemTrackingcode. Currently for our customisation I have created a global variable 
ItemJournalLineG and I am trying to use "OnBeforePostItemJnlLine" Event for getting the value of this variable. Is it a right approach?

Example:-

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Item Jnl.-Post Line", 'OnBeforePostItemJnlLine', '', false, false)]
    local procedure OnBeforePostItemJnlLine_GetVariable(VAR ItemJournalLine: Record "Item Journal Line")
    begin
        ItemJournalLineG := ItemJournalLine;
    end;

**Comment by AlexanderYakunin** [comment]
It may not be a right approach. We do not provide events for your global variables. Please explain what are you trying to achieve to provide better answer.

**Comment by raawasthi** [comment]
local procedure OnAfterApplyItemLedgEntrySetFilters_Codeunit22(VAR ItemLedgerEntry2: Record "Item Ledger Entry"; ItemLedgerEntry: Record "Item Ledger Entry")
    var
        Location: Record Location;
        Item: Record Item;
        ItemTrackingCode: Record "Item Tracking Code";
    begin
        IF Location.GET(ItemLedgerEntry."Location Code") THEN
            IF Location."Use As In-Transit" THEN BEGIN
                ItemLedgerEntry2.SETRANGE("Order Type", ItemLedgerEntry."Order Type"::Transfer);
                ItemLedgerEntry2.SETRANGE("Order No.", ItemLedgerEntry."Order No.");
                Item.GET(ItemLedgerEntry."Item No.");
                IF Item."Item Tracking Code" <> '' THEN
                    ItemTrackingCode.Get(Item."Item Tracking Code");

                IF (ItemLedgerEntry."Entry Type" = ItemLedgerEntry."Entry Type"::Transfer) AND
                   (ItemLedgerEntry."Order No." <> '') AND
                   (ItemJournalLineG."Purch. Receipt No. (Voyage)" <> '') AND
                   (ItemJournalLineG."Receipt Line No. (Voyage)" <> 0) AND
                   NOT ItemLedgerEntry.Positive AND
                   NOT Location."Use As In-Transit" AND
                   ItemTrackingCode."Lot Specific Tracking"
                THEN BEGIN
                    ItemLedgerEntry2.SETRANGE("Document Type", ItemLedgerEntry2."Document Type"::"Purchase Receipt");
                    ItemLedgerEntry2.SETRANGE("Document No.", ItemJournalLineG."Purch. Receipt No. (Voyage)");
                    ItemLedgerEntry2.SETRANGE("Document Line No.", ItemJournalLineG."Receipt Line No. (Voyage)");
                END;
            END;
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Item Jnl.-Post Line", 'OnBeforePostItemJnlLine', '', false, false)]
    local procedure OnBeforePostItemJnlLine_GetVariable(VAR ItemJournalLine: Record "Item Journal Line")
    begin
        ItemJournalLineG := ItemJournalLine;
    end;

**Comment by raawasthi** [comment]
Please find the above code for my requirement. I have mapped it in above way.

**Comment by AlexanderYakunin** [comment]
You don't need tochange event, you can do all this in your extension code.
