### ISSUE TITLE
Using Reservation Management from own table

### ISSUE THREAD

**Issue by damse60** [microsoft/ALAppExtensions#11497]
I'm working on a solution where I will be making reservations (table 337) from an uses defined table (equivalent to Sales Line).

There is a problem in this, when using the function  procedure "SetReservSource(NewSourceRecRef: RecordRef; Direction: Enum "Transfer Direction")" and the functions SetExternalDocumentResEntry, both in the Reservation Management codeunit. 
Both functions start with a clear all.

In short, when coming to the procedure "AutoReserveOneLine". No matter how I use things, either the variable "Positive" is always false, or the variable "SourceRecRef" is not initiated, depending on the sequence in using the functions.

First screen print below shows the example where positive is always false.
Second screen print show the example where SourceRefRec is always undefined (=> 

Suggestion one or all of the following:
1. Public procedure to set the variables "SourceRecRef" and "Positive" without further actions
2. Removing the ClearAll from the mentioned procedures to only clearing relevant variables

![image](https://user-images.githubusercontent.com/32761466/110107067-bd5f8c00-7daa-11eb-925d-49c5dd0f17c5.png)

![image](https://user-images.githubusercontent.com/32761466/110107475-365ee380-7dab-11eb-8e87-f2703f5548ee.png)

**Comment by damse60** [comment]
PS! Version 17.1 but not changed in 17.3

**Comment by damse60** [comment]
Any chance of this being changed any time soon?

**Comment by AlexanderYakunin** [comment]
I have a question. Why don't you use events in SetReservSource? You simply need to add your table and *Reserve.Codeunit.al for your table into event subscriptions. Procedure SetExternalDocumentresEntry is not used in our base app, so you can check which pattern we use and just follow it. We usually have

        SalesLineReserve.ReservQuantity(Rec, QtyToReserve, QtyToReserveBase);
        if QtyToReserveBase <> 0 then begin
            TestField("Shipment Date");
            ReservMgt.SetReservSource(Rec);
            ReservMgt.AutoReserve(FullAutoReservation, '', "Shipment Date", QtyToReserve, QtyToReserveBase);
            Find();
            SalesSetup.Get();
            if (not FullAutoReservation) and (not SalesSetup."Skip Manual Reservation") then begin
                Commit();
                if ConfirmManagement.GetResponse(ManualReserveQst, true) then begin
                    ShowReservation();
                    Find();
                end;
            end;
        end;

**Comment by RasmusTidselbak** [comment]
Hi @AlexanderYakunin ,

Arne and I tried exactly that, but the variable "Positive" will be reset to false during execution.

Can you share an example where you have a custom table with a reservation implementation?

**Comment by AlexanderYakunin** [comment]
The principle is the same for any table, involved into reservation. You can take SalesLineReserve.Codeunit.al or other *Reserve.Codeunit which is more similar to your table (depends on sign, if this is supply or demand). And Implement same subscribers and procedures for your table.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
