### ISSUE TITLE
[Event Request] Table 121 "Purch Rcpt Line" - OnAfterCopyFromPurchRcptLine

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11490]
Hello. In table 121 Purch Rcpt Line, in the procedure CopyFromPurchRcptLine, I would like to use the event publisher OnAfterCopyFromPurchRcptLine to add my own code. But I need the parameter TempPurchLine. Like this :

    local procedure CopyFromPurchRcptLine(var PurchLine: Record "Purchase Line"; PurchOrderLine: Record "Purchase Line"; TempPurchLine: Record "Purchase Line"; NextLineNo: Integer)
    begin
        ...

        OnAfterCopyFromPurchRcptLine(PurchLine, Rec, TempPurchLine);
    end;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyFromPurchRcptLine(var PurchaseLine: Record "Purchase Line"; PurchRcptLine: Record "Purch. Rcpt. Line"; var TempPurchLine: Record "Purchase Line")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
