### ISSUE TITLE
[Request-for-external] Table 36 "Sales Header" - SetSalespersonCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11512]
Hello. In table 36 Sales Header, in the procedure SetBillToCustomerAddressFieldsFromCustomer, I would like to use the event publisher OnBeforeSetBillToCustomerAddressFieldsFromCustomer to add my own code instead of the standard one. From my event subscriber, I would like to use local procedure SetSalespersonCode, but it is a local one. Is possible to pass it in global please ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
