### ISSUE TITLE
Employee relative - fields 4-6 - ES version

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#11519]
We're trying to target as much countries with a single non-localized app and have app validation failures on our app not being compatible with the Spanish BC version, due to (legacy) table schema differences between W1 and ES.

![image](https://user-images.githubusercontent.com/25268332/110329945-8349f080-801d-11eb-8ef0-420eff43dc4b.png)

Is there any chance in having both tables using the same field names (don't care how, by obsoleting ES fields?)

**Comment by fvet** [comment]
We fixed it using recref in the meanwhile. (Issue is no longer urgent)

**Comment by StanPesotskiy** [comment]
If we obsolete these fields in ES version then fields with these ID will be blocked for further usage as fields cannot be removed.
Changing names is also a breaking change. We could change the captions in ES version to match W1 captions, but names will stay unchanged. Will it require an upgrade code moving data between these fields? What would be the correct relations with W1 fields? 
Name - "First Name"
"First Family Name" - "Middle Name"
"Second Family Name" - "Last Name"
