### ISSUE TITLE
[Event Change] Codeunit 5815 - Undo Sales Shipment Line - OnBeforePostItemJnlLine

### ISSUE THREAD

**Issue by mhoury** [microsoft/ALAppExtensions#11514]
Hello,
The event _OnBeforePostItemJnlLine_ published in Codeunit Codeunit 5815 - _Undo Sales Shipment Line_ is missing a _**var**_ on the _DocLineNo_ variable.
This is needed since the _PostItemJnlLine_ function itself takes the _DocLineNo_ parameter as _**var**_, modifies it so that it could be used upward along the chain in the codeunit.

Suggested change:
From

    -    local procedure OnBeforePostItemJnlLine(var SalesShipmentLine: Record "Sales Shipment Line"; DocLineNo: Integer; var ItemLedgEntryNo: Integer; var IsHandled: Boolean)
    +    local procedure OnBeforePostItemJnlLine(var SalesShipmentLine: Record "Sales Shipment Line"; var DocLineNo: Integer; var ItemLedgEntryNo: Integer; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
