### ISSUE TITLE
[Event Request] Table 5998 "Standard Service Item Gr. Code" in OnBeforeStdServiceLineDelete()

### ISSUE THREAD

**Issue by BenjaminHochstetter** [microsoft/ALAppExtensions#11510]
Hello togehter,
Please add an Event to skip the deletion of the StdServiceLines.

```
OnBeforeStdServiceLineDelete(Rec, SkipDelete);
if not SkipDelete then Begin
  StdServiceLine.RESET;
  StdServiceLine.SETRANGE("Standard Service Code",Code);
  IF NOT StdServiceLine.ISEMPTY THEN
    StdServiceLine.DELETEALL(TRUE);
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
