### ISSUE TITLE
[Event Request] Codeunit 5760 "Whse.-Post Receipt" - OnGetResultMessageBeforeMessage

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#11522]
Hi, would it be possible to get an event **OnGetResultMessageBeforeMessage** in codeunit 5760 (**Whse.-Post Receipt**), like this:

```
procedure GetResultMessage()
    var
        MessageText: Text[250];
    begin
        MessageText := Text002;
        if CounterPutAways > 0 then
            MessageText := MessageText + '\\' + Text003;
        OnGetResultMessageBeforeMessage(CounterPutAways,MessageText);
        Message(MessageText, CounterSourceDocOK, CounterSourceDocTotal, CounterPutAways);
    end;
```

```
[IntegrationEvent(false, false)]
local procedure OnGetResultMessageBeforeMessage(CounterPutAways: Integer; var MessageText: Text[250])
begin
end;
```

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
