### ISSUE TITLE
[Event Request] Table 81 - OnAppliesToDocNoOnValidateOnAfterEmplLedgEntrySetFilters

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#11526]
In table 81 "Gen. Journal Line", can a new event be added which is similar to two existing events (OnAppliesToDocNoOnValidateOnAfterCustLedgEntrySetFilters and OnAppliesToDocNoOnValidateOnAfterVendLedgEntrySetFilters) in the same trigger:

```
        field(36; "Applies-to Doc. No."; Code[20])
        {
            ...
            trigger OnValidate()
            ...
                        TempGenJnlLine."Account Type"::Employee:
                            begin
                                ...
                                EmplLedgEntry.SetRange(Open, true);
                                OnAppliesToDocNoOnValidateOnAfterEmplLedgEntrySetFilters(Rec, EmplLedgEntry);   //NEW
                                if EmplLedgEntry.FindFirst then begin
                                ...
        }
```

    [IntegrationEvent(false, false)]
    local procedure OnAppliesToDocNoOnValidateOnAfterEmplLedgEntrySetFilters(var GenJournalLine: Record "Gen. Journal Line"; var EmplLedgerEntry: Record "Employee Ledger Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
