### ISSUE TITLE
[Event Request] Codeunit::"Item Reference Management" - Function SetFiltersTypeAndTypeNoItemRef - OnAfterSetFiltersTypeAndTypeNoItemReference

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11534]
We like to request the following Event:
Object: Codeunit::"Item Reference Management"
Function: SetFiltersTypeAndTypeNoItemRef
Publisher Event: OnAfterSetFiltersTypeAndTypeNoItemReference
Reason: To implement custom business logic
Where is the event placed:
ItemReference.SetRange("Reference Type", ItemRefType);
ItemReference.SetRange("Reference Type No.", ItemRefTypeNo);
OnAfterSetFiltersTypeAndTypeNoItemReference(ItemReference, ItemRefType, ItemRefTypeNo);
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterSetFiltersTypeAndTypeNoItemReference(var ItemReference: Record "Item Reference"; ItemRefType: Enum "Item Reference Type"; ItemRefTypeNo: Code[30])
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
