### ISSUE TITLE
[Event Request] Database::"Item Vendor" - Function UpdateItemReference - OnBeforeUpdateItemReference

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11537]
We like to request the following Event:
Object: Database::"Item Vendor"
Function: UpdateItemReference
Publisher Event: OnBeforeUpdateItemReference
Reason: To implement custom business logic
Where is the event placed:
begin
IsHandled := false;
OnBeforeUpdateItemReference(Rec, IsHandled);
if IsHandled then
exit;
if ItemReference.WritePermission then
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateItemReference(var ItemVendor: Record "Item Vendor"; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
