### ISSUE TITLE
[Event Change] Database::"Job Journal Line" - Function CheckItemAvailable - OnBeforeCheckItemAvailable

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11538]
We like to request the following Event:
Object: Database::"Job Journal Line"
Function: CheckItemAvailable
Publisher Event: OnBeforeCheckItemAvailable
Reason: add an extra Parameter
Where is the event placed:
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckItemAvailable(var JobJournalLine: Record "Job Journal Line"; var ItemJournalLine: Record "Item Journal Line"; var CheckedAvailability: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
