### ISSUE TITLE
[Event Request] Database::"Job Planning Line" - Function "Quantity" - OnValidate - OnValidateQuantityOnBeforeValidateRemainingQuantity

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11539]
We like to request the following Event:
Object: Database::"Job Planning Line"
Function: "Quantity" - OnValidate
Publisher Event: OnValidateQuantityOnBeforeValidateRemainingQuantity
Reason: To implement custom business logic
Where is the event placed:
CalcQuantityBase();
IsHandled := false;
OnValidateQuantityOnBeforeValidateRemainingQuantity(Rec, xRec, IsHandled);
if not IsHandled then
if "Usage Link" and (xRec."No." = "No.") then begin
Delta := Quantity - xRec.Quantity;
Validate("Remaining Qty.", "Remaining Qty." + Delta);
Validate("Qty. to Transfer to Journal", "Qty. to Transfer to Journal" + Delta);
end;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnValidateQuantityOnBeforeValidateRemainingQuantity(var JobPlanningLine: Record "Job Planning Line"; xJobPlanningLine: Record "Job Planning Line"; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
