### ISSUE TITLE
[Event Request] Codeunit::"Item Reference Management" - Function EnterSalesItemReference - OnBeforeFindItemReference

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11535]
We like to request the following Event:
Object: Codeunit::"Item Reference Management"
Function: EnterSalesItemReference
Publisher Event: OnBeforeFindItemReference
Reason: To implement custom business logic
Where is the event placed:
if Type = Type::Item then begin
IsHandled := false;
OnBeforeFindItemReference(SalesLine2, ItemReference, Found, IsHandled);
if not IsHandled then begin                
ItemReference.Reset();
ItemReference.SetRange("Item No.", "No.");
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeFindItemReference(var SalesLine: Record "Sales Line"; var ItemReference: Record "Item Reference"; var Found: Boolean; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
