### ISSUE TITLE
[Event Request] Codeunit::"Job Post-Line" - Function TestSalesLine - OnBeforeTestLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11540]
We like to request the following Event:
Object: Codeunit::"Job Post-Line"
Function: TestSalesLine
Publisher Event: OnBeforeTestLine
Reason: To implement custom business logic
Where is the event placed:
begin
OnBeforeTestLine(SalesLine, IsHandled);
if IsHandled then
exit;
if SalesLine."Job Contract Entry No." = 0 then
exit;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeTestLine(var SalesLine: Record "Sales Line"; var Handled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
