### ISSUE TITLE
[Event Request] Codeunit::"Lead-Time Management" - Function PlannedEndingDate - OnBeforePlannedEndingDate

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11541]
We like to request the following Event:
Object: Codeunit::"Lead-Time Management"
Function: PlannedEndingDate
Publisher Event: OnBeforePlannedEndingDate
Reason: To implement custom business logic
begin
// Returns Ending Date calculated backward from Due Date
OnBeforePlannedEndingDate(ItemNo, LocationCode, VariantCode, DueDate, VendorNo, RefOrderType, EndingDate, IsHandled);
if IsHandled then
exit(EndingDate);
GetPlanningParameters.AtSKU(SKU, ItemNo, VariantCode, LocationCode);
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforePlannedEndingDate(ItemNo: Code[20]; LocationCode: Code[10]; VariantCode: Code[10]; DueDate: Date; VendorNo: Code[20]; RefOrderType: Option " ",Purchase,"Prod. Order",Transfer,Assembly; var EndingDate: Date; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
