### ISSUE TITLE
[Event Request] Codeunit::"Mail Management" - Function IsEnabled - OnBeforeIsEnabled

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11546]
We like to request the following Event:
Object: Codeunit::"Mail Management"
Function: IsEnabled
Publisher Event: OnBeforeIsEnabled
Reason: To implement custom business logic
Where is the event placed:
Enabled: Boolean;
Handled: Boolean;
begin
OnBeforeIsEnabled(OutlookSupported, Enabled, Handled);
if Handled then
exit(Enabled);
if EmailFeature.IsEnabled() then
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeIsEnabled(var OutlookSupported: Boolean; var Enabled: Boolean; var Handled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
