### ISSUE TITLE
[Event Request] Codeunit::"Output Jnl.-Expl. Route" - Function OnRun - OnRunOnAfterFilterProdOrderRtngLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11547]
We like to request the following Event:
Object: Codeunit::"Output Jnl.-Expl. Route"
Function: OnRun
Publisher Event: OnRunOnAfterFilterProdOrderRtngLine
Reason: To implement custom business logic
Where is the event placed:
repeat
ProdOrderRtngLine.SetRange("Routing No.", ProdOrderLine."Routing No.");
ProdOrderRtngLine.SetRange("Routing Reference No.", ProdOrderLine."Routing Reference No.");
OnRunOnAfterFilterProdOrderRtngLine(ProdOrderRtngLine);
if ProdOrderRtngLine.Find('-') then begin
repeat
Event Code:
[IntegrationEvent(false, false)]
local procedure OnRunOnAfterFilterProdOrderRtngLine(var ProdOrderRoutingLine: Record "Prod. Order Routing Line")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
