### ISSUE TITLE
[Event Request] Codeunit::"Lead-Time Management" - Function PlannedDueDate - OnBeforePlannedDueDate

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11542]
We like to request the following Event:
Object: Codeunit::"Lead-Time Management"
Function: PlannedDueDate
Publisher Event: OnBeforePlannedDueDate
Reason: To implement custom business logic
begin
// Returns Due Date calculated forward from Ending Date
OnBeforePlannedDueDate(ItemNo, LocationCode, VariantCode, EndingDate, VendorNo, RefOrderType, DueDate, IsHandled);
if IsHandled then
exit(DueDate);
GetPlanningParameters.AtSKU(SKU, ItemNo, VariantCode, LocationCode);
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforePlannedDueDate(ItemNo: Code[20]; LocationCode: Code[10]; VariantCode: Code[10]; EndingDate: Date; VendorNo: Code[20]; RefOrderType: Option " ",Purchase,"Prod. Order",Transfer,Assembly; var DueDate: Date; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
