### ISSUE TITLE
[Event Request] Codeunit::"PostSales-Delete" - Function DeleteSalesShptLines - OnBeforeDeleteSalesShptLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11549]
We like to request the following Event:
Object: Codeunit::"PostSales-Delete"
Function: DeleteSalesShptLines
Publisher Event: OnBeforeDeleteSalesShptLine
Reason: To implement custom business logic
Where is the event placed:
if SalesShptLine.Find('-') then
repeat
OnBeforeDeleteSalesShptLine(SalesShptLine);
SalesShptLine.TestField("Quantity Invoiced", SalesShptLine.Quantity);
SalesShptLine.Delete(true);
until SalesShptLine.Next = 0;
Event Code:
[IntegrationEvent(false, false)]
local procedure procedure OnBeforeDeleteSalesShptLine(var SalesShptLine: Record "Sales Shipment Line")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
