### ISSUE TITLE
[Event Request] Codeunit::"Prod. Order Status Management" - Function FlushProdOrder - OnAfterPostFlushItemJnlLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11555]
We like to request the following Event:
Object: Codeunit::"Prod. Order Status Management"
Function: FlushProdOrder
Publisher Event: OnAfterPostFlushItemJnlLine
Reason: To implement custom business logic
Where is the event placed:
if Item."Item Tracking Code" <> '' then
ItemTrackingMgt.CopyItemTracking(RowID1, ItemJnlLine.RowID1, false);
PostFlushItemJnlLine(ItemJnlLine);
OnAfterPostFlushItemJnlLine(ItemJnlLine);
end;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterPostFlushItemJnlLine(var ItemJournalLine: Record "Item Journal Line")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
