### ISSUE TITLE
[Event Request] Codeunit::"PostSales-Delete" - Function DeleteSalesRcptLines - OnBeforeDeleteSalesRcptLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11552]
We like to request the following Event:
Object: Codeunit::"PostSales-Delete"
Function: DeleteSalesRcptLines
Publisher Event: OnBeforeDeleteSalesRcptLine
Reason: To implement custom business logic
Where is the event placed:
if SalesRcptLine.Find('-') then
repeat
OnBeforeDeleteSalesRcptLine(SalesRcptLine);
SalesRcptLine.TestField("Quantity Invoiced", SalesRcptLine.Quantity);
SalesRcptLine.Delete();
until SalesRcptLine.Next = 0;
Event Code:
[IntegrationEvent(false, false)]
local procedure procedure OnBeforeDeleteSalesRcptLine(var SalesRcptLine: Record "Return Receipt Line")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
