### ISSUE TITLE
[Event Change] Codeunit::"Production Journal Mgt" - Function CreateJnlLines - OnCreateJnlLinesOnAfterFindProdOrderRtngLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11559]
We like to request the following Event:
Object: Codeunit::"Production Journal Mgt"
Function: CreateJnlLines
Publisher Event: OnCreateJnlLinesOnAfterFindProdOrderRtngLine
Reason: add extra Parameter
Where is the event placed:
Event Code:
[IntegrationEvent(false, false)]
local procedure OnCreateJnlLinesOnAfterFindProdOrderRtngLine(var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var ItemJnlLine: Record "Item Journal Line"; var NextLineNo: Integer; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
