### ISSUE TITLE
[Event Request] Codeunit::"Price Calculation Buffer Mgt." - Function IsInMinQty - OnBeforeIsInMinQty

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11553]
We like to request the following Event:
Object: Codeunit::"Price Calculation Buffer Mgt."
Function: IsInMinQty
Publisher Event: OnBeforeIsInMinQty
Reason: To implement custom business logic
Where is the event placed:
var
IsHandled: Boolean;
begin
IsHandled := false;
OnBeforeIsInMinQty(PriceListLine, PriceCalculationBuffer, Result, IsHandled);
if IsHandled then
exit(Result);
Event Code:
[IntegrationEvent(false, false)]
local procedure procedure OnBeforeIsInMinQty(PriceListLine: Record "Price List Line"; PriceCalculationBuffer: Record "Price Calculation Buffer"; var Result: Boolean; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
