### ISSUE TITLE
[Event Change] Codeunit::"Prod. Order Status Management" - Function ChangeProdOrderStatus - OnBeforeChangeStatusOnProdOrder

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11558]
We like to request the following Event:
Object: Codeunit::"Prod. Order Status Management"
Function: ChangeProdOrderStatus
Publisher Event: OnBeforeChangeStatusOnProdOrder
Reason: use Enum in event code
Where is the event placed:
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeChangeStatusOnProdOrder(var ProductionOrder: Record "Production Order"; NewStatus: Enum "Production Order Status"; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
