### ISSUE TITLE
[Event Request] Database::"Requisition Line" - Function UpdateOrderReceiptDate - OnAfterUpdateOrderReceiptDate

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11561]
We like to request the following Event:
Object: Database::"Requisition Line"
Function: UpdateOrderReceiptDate
Publisher Event: OnAfterUpdateOrderReceiptDate
Reason: To implement custom business logic
Where is the event placed:
SetActionMessage;
UpdateDatetime;
OnAfterUpdateOrderReceiptDate(LeadTimeCalc);
end;
Event Code:
[IntegrationEvent(true, false)]
local procedure OnAfterUpdateOrderReceiptDate(LeadTimeCalc: DateFormula)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
