### ISSUE TITLE
[Event Change] Database::"Requisition Line" - Function CalcStartingDate - OnBeforeCalcStartingDate

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11566]
We like to request the following Event:
Object: Database::"Requisition Line"
Function: CalcStartingDate
Publisher Event: OnBeforeCalcStartingDate
Reason: add an extra Parameter
Where is the event placed:
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeCalcStartingDate(var LeadTime: Code[20]; var Rec: Record "Requisition Line")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
