### ISSUE TITLE
R2000005 File SEPA Payments to tempblob

### ISSUE THREAD

**Issue by Joriek** [microsoft/ALAppExtensions#11569]
Hello

We have R2000005 File SEPA Payments to generate and download a SEPA file based on the payment journal lines.
Currently this report is hard coded to always download the file. We need it to put this file into a tempblob so we can use the generated data in our own custom logic (in our case, to automatically upload this file to the bank its environment).
I already moved all the logic in the report to custom code which uses the "new" XML objects instead of the old dotnet XML objects, but I would like to keep using as much as base code as possible. Exposing this new tempblob for extensions would resolve this issue.

![image](https://user-images.githubusercontent.com/6583705/110464583-93bca280-80d3-11eb-8997-f7963d4bb682.png)

Thank you in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
