### ISSUE TITLE
[Event Request] Database::"Requisition Line" - Function TransferFromActionMessage - OnAfterTransferFromActionMessage

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11563]
We like to request the following Event:
Object: Database::"Requisition Line"
Function: TransferFromActionMessage
Publisher Event: OnAfterTransferFromActionMessage
Reason: To implement custom business logic
Where is the event placed:
case ReservEntry."Source Type" of
DATABASE::"Transfer Line",
DATABASE::"Prod. Order Line",
DATABASE::"Purchase Line",
DATABASE::"Requisition Line",
DATABASE::"Assembly Header":
"Ending Date" :=
LeadTimeMgt.PlannedEndingDate(
ReservEntry."Item No.", ReservEntry."Location Code", ReservEntry."Variant Code",
"Due Date", "Vendor No.", "Ref. Order Type");
end;
OnAfterTransferFromActionMessage(ActionMessageEntry);
end;
Event Code:
[IntegrationEvent(true, false)]
local procedure OnAfterTransferFromActionMessage(var ActionMessageEntry: Record "Action Message Entry")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
