### ISSUE TITLE
[Protection Level] Page "Contact Profile Answers" globar var access "Set"

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11564]
Please make this global var accessible as we work with this in our page extension in several triggers and also in OnValidates.

**Comment by SWE-Tina** [comment]
Additionally I need a Function "GetSet" to work with this var not just via events.

```
procedure GetSet(): Boolean
begin
exit(Set);
end;
```

**Comment by AlexanderYakunin** [comment]
Can we make this variable protected?

**Comment by SWE-Tina** [comment]
As I need the information in the OnAfterGetRecord of the PageExt. and additionally in an OnValdidate, it won't be sufficient to have it as protected var. Furthermore we need a possibility to set the set-variable;

procedure SetSet(pSet: Boolean)
begin
Set := pSet;
end;

**Comment by SWE-Tina** [comment]
Yes, it is possible :)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
