### ISSUE TITLE
[Event Request] Codeunit::"Reminder-Make" - Function FindAndMarkReminderCandidates - OnAfterFindCustLedgEntry

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11560]
We like to request the following Event:
Object: Codeunit::"Reminder-Make"
Function: FindAndMarkReminderCandidates
Publisher Event: OnAfterFindCustLedgEntry
Reason: To implement custom business logic
Where is the event placed:
if CustLedgEntry.FindSet then
repeat
OnAfterFindCustLedgEntry(CustLedgEntry, ReminderHeaderReq);
if CustLedgEntry."On Hold" = '' then begin
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterFindCustLedgEntry(var CustLedgerEntry: Record "Cust. Ledger Entry"; var ReminderHeader: Record "Reminder Header")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
