### ISSUE TITLE
[Event Change] Database::"Requisition Line" - Function SetReplenishmentSystemFromTransfer - OnAfterSetReplenishmentSystemFromTransfer

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11565]
We like to request the following Event:
Object: Database::"Requisition Line"
Function: SetReplenishmentSystemFromTransfer
Publisher Event: OnAfterSetReplenishmentSystemFromTransfer
Reason: add an extra Parameter
Where is the event placed:
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterSetReplenishmentSystemFromTransfer(var RequisitionLine: Record "Requisition Line"; Item: Record Item; StockkeepingUnit: Record "Stockkeeping Unit"; CurrFieldNo: Integer)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
