### ISSUE TITLE
Change the scope of several functions in the table 79 - "Company Information"

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#11571]
Could yoo please change the scope from Local to global for the next 5 functions declared in the table 79 "Company Information"?

local procedure ConvertIBAN(var IBANCode: Code[100])
local procedure CalcModulus(Number: Code[10]; Modulus97: Integer): Code[10]
local procedure ConvertLetter(var IBANCode: Code[100]; Letter: Code[1]; LetterPlace: Integer): Boolean
local procedure IsDigit(LetterChar: Char): Boolean
local procedure IBANError(WrongIBAN: Text).

We need it to avoid duplicate code to implement our custom business logic.

Thanks in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
