### ISSUE TITLE
[External Function] Report 840 "Suggest Worksheet Lines" - InsertTempCFWorksheetLine

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#11572]
Related to #5103

Please make **InsertTempCFWorksheetLine** global / protected (for report extensions).

We want to extend report 840 by adding additional entities / data items to be included in the cash flow forecast. This requires us to call InsertTempCFWorksheetLine for each extra dataitem (if hopefully report extensions would allow us extending the cash flow forecast report).

**Comment by fvet** [comment]
Just putting the function to external won't due, since we need to be able to pass a CF Worskheet Line. (currently CFWorksheetLine2 is used, but not accessible via report extension)

Proposal:

```
 local procedure InsertTempCFWorksheetLine(MaxPmtTolerance: Decimal) 
    begin
        InsertTempCFWorksheetLine(MaxPmtTolerance, CFWorksheetLine2) // Move function call to new global function
    end;

    // Introduce new global function to support global var CFWorksheetLine2 access
    procedure InsertTempCFWorksheetLine(MaxPmtTolerance: Decimal; CFWorksheetLine: Record "Cash Flow Worksheet Line")  
    begin
        with TempCFWorksheetLine do begin
            LineNo := LineNo + 100;
            TransferFields(CFWorksheetLine); // 
            "Cash Flow Forecast No." := "Cash Flow Forecast"."No.";
            "Line No." := LineNo;

            CalculateCFAmountAndCFDate;
            SetCashFlowDate(TempCFWorksheetLine, "Cash Flow Date");

            if Abs("Amount (LCY)") < Abs(MaxPmtTolerance) then
                "Amount (LCY)" := 0
            else
                "Amount (LCY)" := "Amount (LCY)" - MaxPmtTolerance;

            if InsertConditionMet then
                Insert
        end;
    end;
```

PS: Please ensure to include the new procedure in all localisations, include Spain / Italy.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
