### ISSUE TITLE
[Event Request] table 79 "Company Information" - procedure CheckIBAN(IBANCode: Code[100]) - OnBeforeCheckIBAN

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#11570]
Could You please, add the following event to the table 79 "Company Information"?
Object: 79 "Company Information"
procedure CheckIBAN(IBANCode: Code[100])

Publisher Event: OnBeforeCheckIBAN

Reason: To implement additional controls over the IBAN code

Where is the event placed (see image attached)?:

![image](https://user-images.githubusercontent.com/73465025/110465750-214cc200-80d5-11eb-8ab7-f51f316f8007.png)

Between the lines 624 and 525, after checking if the IBANCode is void, insert the next code line:

OnBeforeCheckIBAN(IBANCode);

Event Code:
[IntegrationEvent(true, false)]
local procedure OnBeforeCheckIBAN(IBANCode: Code[100])
begin
end;

Thanks in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
