### ISSUE TITLE
New event after the SetFilter in function InsertPlanningLine in codeunit 99000809 "Planning Line Management"

### ISSUE THREAD

**Issue by rwe12345** [microsoft/ALAppExtensions#11575]
Please add an event after the SetFilter in function InsertPlanningLine in codeunit 99000809 "Planning Line Management".
Current code:

![image](https://user-images.githubusercontent.com/44321194/110476836-bbffcd80-80e2-11eb-8048-7659c8b983a8.png)

Please add next event (OnInsertPlanningLinenAfterRegLineSetFilters):

![image](https://user-images.githubusercontent.com/44321194/110476864-c4f09f00-80e2-11eb-92c7-a7d9fd79120f.png)

![image](https://user-images.githubusercontent.com/44321194/110476887-c9b55300-80e2-11eb-84d0-c3f71b7c3f24.png)

[IntegrationEvent(false, false)]
    local procedure OnInsertPlanningLinenAfterRegLineSetFilters(var RequisitionLine2: Record "Requisition Line";var RequisitionLine: Record "Requisition Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
