### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - function CheckPurchExtDocNo

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#11578]
We'd like to have the option of bypassing the external document no. check when posting a purchase document Gen. Journal Line:

```
    local procedure CheckPurchExtDocNo(GenJnlLine: Record "Gen. Journal Line")
    var
        PurchSetup: Record "Purchases & Payables Setup";
        OldVendLedgEntry: Record "Vendor Ledger Entry";
        VendorMgt: Codeunit "Vendor Mgt.";
        IsHandled: Boolean;       //NEW
    begin
        OnBeforeCheckPurchExtDocNo(GenJnlLine, IsHandled);       //NEW
        if IsHandled then       //NEW
            exit;       //NEW
            
        PurchSetup.Get();
        ...
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckPurchExtDocNo(GenJnlLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by RomanZanizdra** [comment]
Hi @complord .
There is already existing event OnBeforeCheckPurchExtDocNo(), subscribing on it you will be able to skip the check. Is it OK for you?
```
                    OnBeforeCheckPurchExtDocNo(GenJnlLine, VendLedgEntry, CVLedgEntryBuf, CheckExtDocNoHandled);
                    if not CheckExtDocNoHandled then
                        CheckPurchExtDocNo(GenJnlLine);

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
