### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - function CheckSalesExtDocNo

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#11577]
We'd like to have the option of bypassing the external document no. check when posting a sales document Gen. Journal Line:

```
    local procedure CheckSalesExtDocNo(GenJnlLine: Record "Gen. Journal Line")
    var
        SalesSetup: Record "Sales & Receivables Setup";
        IsHandled: Boolean;       //NEW
    begin
        OnBeforeCheckSalesExtDocNo(GenJnlLine, IsHandled);       //NEW
        if IsHandled then       //NEW
            exit;       //NEW
            
        SalesSetup.Get();
        ...
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckSalesExtDocNo(GenJnlLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
