### ISSUE TITLE
[Event Request] New Event after Printing or PDF creation needed

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/ALAppExtensions#11581]
We need to archive, for example, posted sales documents or purchase orders in a document management system after they have been printed or emailed as PDFs. Since BC17 we cannot use the **OnAfterDocumentPrintReady()** event, because this is only called when an extension printer is present. ([Details](https://github.com/microsoft/AL/issues/6521)).

To make the integration as simple as possible without having to wire up every report to be passed to the document management system via events in AL, a global event is needed. E.g. something like this in Codeunit "Reporting Triggers". It would be important that **RecVarToPrint** contains all records, when printing multiple sales invoices at once.

```
[BusinessEvent(false)]
local procedure OnAfterPrint(ReportId: Integer; RecVarToPrint: Variant)
begin
end;
```

**Comment by JesperSchulz** [comment]
We're cooking on a solution for the 2021 Wave 2 release for this. When ready, we would very much appreciate your input, if what we've build meets your requirements.
Would a fix in the next major be sufficient, or do you need a work around right here, right now? I've been told that you could create a dummy printer to keep the event firing, but it doesn't sound very clean to me. But if you cannot wait for another half a year, we may want to get some details on that hack. What do you say?

**Comment by Spycoclown** [comment]
It would be great to have the stream of the printed object.

**Comment by DanielGoehler** [comment]
Hello @JesperSchulz, thank you very much. Right now we are using the **OnAfterPrintDocument** event of the **Report Selections** table and could additionally subscribe to multiple reports individually. Our long term goal would be to have a generic solution with configuration capabilities without having to wire it up via code.
We are looking forward to 2021 Wave 2 and would love to provide feedback on this.

**Comment by JesperSchulz** [comment]
That sounds great! I'll put you on the list of people to notify, once we've got something to test. Work is already in progress :-)

**Comment by JesperSchulz** [comment]
I will close this issue, as this is being taken care of as part of larger feature work and hence won't be addressed as a "standalone issue". But we're on the case :-)

**Comment by JesperSchulz** [comment]
Let me check how far we've gotten!

**Comment by JesperSchulz** [comment]
I received a reply from the developer. Unfortunately, we ran into some challenges with our test suite, which took a little more time to fix than initially anticipated. Hence the release got slightly delayed and the changes did not make the 19.0 release. We're optimistic though, that the changes will make it into the next major branch "within the next weeks" (not my words :-D). I sense a Christmas present coming your way - if all goes well... The changes should then release with the next major.

**Comment by JesperSchulz** [comment]
The development team confirmed, that the new events OnAfterDocumentReady and OnAfterDocumentDownload will be ready for early testing next week. We will release some early documentation and a sample PTE as well 🥳

**Comment by JesperSchulz** [comment]
Sample PTE is ready, but not ready to be officially shared yet. Please send me a PM on Yammer, if you'd like to get your hands on the sample extension 😊
