### ISSUE TITLE
[Parameter Request] Codeunit DuplicationManagement Event "OnInsDuplContOnAfterDuplContSetFilters"

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11580]
Please also add the parameter for "Duplicate Search String Setup" as we also filter on this to differentiate between Company or person Contacts (see also #10100 for further explanation and original request):
  ```
  [EventSubscriber(ObjectType::Codeunit, Codeunit::"DuplicateManagement", 'OnInsDuplContOnAfterDuplContSetFilters', '', true, true)]
    local procedure "DuplicateManagement_OnInsDuplContOnAfterDuplContSetFilters"
    (
        var DuplCont: Record "Contact Duplicate";
        var DuplContSearchString: Record "Cont. Duplicate Search String";
var DuplSearchStringSetup: Record "Duplicate Search String Setup";

    )
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
