### ISSUE TITLE
[Event Request] Application “Tests-ERM”, 134804 "RED Test Unit for Purch Doc"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#11589]
[Event Request]Application “Tests-ERM”, 134804 "RED Test Unit for Purch Doc"

Could you please insert the OnTestInitialize Event at the beginning the following test procedures:
-	TestPurchaseQuoteWithItem
-	TestPurchaseBlanketOrderWithItem
-	TestChangingPurchaseLineType
-	TestChangingPurchaseLineNo
-	TestClearingPurchaseLineDeferralCode
-	TestDeletingPurchaseLine

![pic1](https://user-images.githubusercontent.com/45795262/110494554-03db2080-80f4-11eb-930c-bdfef0635137.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
