### ISSUE TITLE
[Event Request]Application “Tests-ERM”, 134805 "RED Test Unit for Sales Doc"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#11588]
Could you please insert the OnTestInitialize Event at the beginning the following test procedures:
-	TestSalesQuoteWithItem
-	TestSalesBlanketOrderWithItem
-	TestChangingSalesLineType
-	TestChangingSalesLineNo
-	TestClearingSalesLineDeferralCode
-	TestDeletingSalesLine

![pic1](https://user-images.githubusercontent.com/45795262/110492704-b9a56f80-80f2-11eb-9413-76f4d7babefd.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
