### ISSUE TITLE
[Parameter Request ] Codeunit  Event"Item Charge Assgnt. (Purch.)" "OnAssignByWeightOnBeforeTempItemChargeAssgntPurchDelete" 

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11586]
I forgot or have overseen that also currency is needed in the event you have already provided (#10185) please be so kind and add "Currency: Record Currency":

local procedure OnAssignByWeightOnBeforeTempItemChargeAssgntPurchDelete(var ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)"; **Currency: Record Currency;** QtyRemainder: Decimal; QtyToAssign: Decimal);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
