### ISSUE TITLE
Suggestion: Please document breaking changes!

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/ALAppExtensions#11583]
I today I learned that OnAfterDocumentPrintReady() in Codeunit ReportManagement will not called after upgrade to BC 17.   

I got the following response:
> Is the selected printer an extension printer ? The trigger is only called for printers that are defined as extension printers, not called for browser printing and windows printers.  
That was a bug in the 16 version at some stage long time ago causing lots of issues in other scenarios. OnDocumentPrintReady is only for extension printers, so that partner will have to declare an extension printer and set that as the default printer in print selection.”  

This issue was reported before microsoft/AL#6224. 

Please document such [breaking changes](https://github.com/microsoft/ALAppExtensions/blob/master/BREAKINGCHANGES.md) and update the [documention](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-onafterdocumentprintready-event).

**Comment by DanielGoehler** [comment]
@atoader: You are right, sorry.

**Comment by JesperSchulz** [comment]
There is a lot of confusion about the breaking change documentation. The GitHub document you are referring to was supposed to get retired, when we moved to our deprecation model - the idea being, that all breaking changes are documented in the code's deprecation properties and hence don't need a document of their own. And as a rule of thumb, no unannounced breaking changes should occur - emphasis on should. That being said, every now and then a breaking change without deprecation still does come along and we have so far failed to document those in the right and/or consistent manner. There are many reasons that we struggle with that, which I don't want to do bore you with. But I can assure you that we're working on improving the situation. When a breaking change is introduced, it must be properly documented! We hope to be able to improve on this situation very soon.
And I will see what I can do about your specific example, of course.
