### ISSUE TITLE
[Parameter Request ] Codeunit Event"Item Charge Assgnt. (Sales)" "OnAssignByWeightOnAfterCalcTotalGrossWeight" 

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11587]
Same as in issue #11586 ... forgot to mention parameter Currency also on the sales side, please add it :).

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Item Charge Assgnt. (Sales)", 'OnAssignByWeightOnAfterCalcTotalGrossWeight', '', false, false)]
    local procedure ItemChargeAssgntSales_OnAssignByWeightOnAfterCalcTotalGrossWeight(var ItemChargeAssignmentSales: Record "Item Charge Assignment (Sales)"; **Currency: Record Currency;** TotalGrossWeight: Decimal);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
