### ISSUE TITLE
[Parameter Request] Table Event "Item Journal Line" "OnBeforeCheckProdOrderCompBinCode" 

### ISSUE THREAD

**Issue by ValentinoEnz** [microsoft/ALAppExtensions#11597]
Could you change the formal parameter "ItemJournalLine" to be passed by reference instead of passed by value?

```
[IntegrationEvent(false, false)]
 local procedure OnBeforeCheckProdOrderCompBinCode(var ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean)
 ```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
