### ISSUE TITLE
[Event Request] Codeunit 5763 Whse.-Post Shipment - OnBeforePostSourceSalesDocument

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#11602]
Hi, would it be possible to get an event OnBeforePostSourceSalesDocument in codeunit 5763, procedure PostSourceSalesDocument, like this : 
```
    local procedure PostSourceSalesDocument(var SalesPost: Codeunit "Sales-Post")
    begin
        OnBeforePostSourceSalesDocument(SalesPost);
        SalesPost.Run(SalesHeader);
        CounterSourceDocOK := CounterSourceDocOK + 1;
    end;

```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostSourceSalesDocument(SalesPost: Codeunit "Sales-Post")
    begin
    end;

```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
