### ISSUE TITLE
[Global Access] Report 840 "Suggest Worksheet Lines" - GetParameters(Summarized)

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#11605]
We're extending report 840 via 'Report Extensions' with custom dataitems. We'd like to access the value of the Summarized boolean / shown on the options requestpage. Not sure if we have access in any other ways to report global variables or if we need to request a **GetParameters(var Summarized)** function instead?

![image](https://user-images.githubusercontent.com/25268332/110681897-9d7cfd80-81da-11eb-833c-dcba38439a9c.png)

**Comment by fvet** [comment]
**UPDATE : Or make the variable protected (for use by report extensions).**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
