### ISSUE TITLE
[Event Edit] Codeunit 22 "Item Jnl.-Post Line" - OnPostItemOnAfterGetSKU

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#11609]
Hi, would it be possible to edit an event **OnPostItemOnAfterGetSKU** in codeunit 22(**Item Jnl.-Post Line**), like this:

```
procedure PostItem()
    var
        IsHandled: Boolean;
    begin
        OnBeforePostItem(ItemJnlLine, IsHandled);

        with ItemJnlLine do begin
            SKUExists := SKU.Get("Location Code", "Item No.", "Variant Code");
            IsHandled := false;
            OnPostItemOnAfterGetSKU(ItemJnlLine, SKUExists, IsHandled);
            if not IsHandled then
                if "Item Shpt. Entry No." <> 0 then begin
                    "Location Code" := '';
                    "Variant Code" := '';
                end;
           ...
        end;
    end;
```

```
[IntegrationEvent(false, false)]
local procedure OnPostItemOnAfterGetSKU(var ItemJnlLine: Record "Item Journal Line"; var SKUExists: Boolean; var IsHandled: Boolean)
begin
end;
```

The event was created for Issue #9335 and there should be no problem with this change.

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
