### ISSUE TITLE
[Event Request] codeunit 2580 "Dimension Correction Mgt" - OnAfterVerifyIfDimensionCanBeChanged

### ISSUE THREAD

**Issue by dkatson** [microsoft/ALAppExtensions#11606]
Hi team, please add OnAfterVerifyIfDimensionCanBeChanged to the procedure VerifyIfDimensionCanBeChanged
<img width="718" alt="image" src="https://user-images.githubusercontent.com/29101017/110746132-e9798200-826e-11eb-9db9-681c3263402e.png">

This will be used to add more checks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
