### ISSUE TITLE
[Event Request] T39 "Purchase Line" - procedure OnBeforeCheckPrepmtAmounts()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#11601]
------- ADD PARAMETER : xRec ---------

    IsHandled := false;
    OnBeforeCheckPrepmtAmounts(Rec, PurchHeader, CurrFieldNo, IsHandled, xRec);
    if IsHandled then
        exit;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckPrepmtAmounts(var PurchaseLine: Record "Purchase Line"; PurchHeader: Record "Purchase Header"; CurrentFieldNo: Integer; var IsHandled: Boolean; var xPurchaseLine : Record "Purchase Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
