### ISSUE TITLE
[Enum Request] Table 1248 Ledger Entry Matching Buffer

### ISSUE THREAD

**Issue by stryzhak** [microsoft/ALAppExtensions#11604]
Hi, 
Could you please change field "Account Type" type from option to enum? 

![image](https://user-images.githubusercontent.com/29860849/110678627-2eee6e80-81df-11eb-8f96-1a94816e3250.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
