### ISSUE TITLE
[Event Request] Database::"Sales Header" - Function CheckCreditMaxBeforeInsert - OnCheckCreditMaxBeforeInsertOnBeforeSalesHeaderCheck

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11616]
We like to request the following Event:
Object: Database::"Sales Header"
Function: CheckCreditMaxBeforeInsert
Publisher Event: OnCheckCreditMaxBeforeInsertOnBeforeSalesHeaderCheck
Reason: To implement custom business logic
Where is the event placed:
else
SalesHeader."Bill-to Customer No." := Cust."No.";
OnCheckCreditMaxBeforeInsertOnBeforeSalesHeaderCheck(SalesHeader);
CustCheckCreditLimit.SalesHeaderCheck(SalesHeader);
end else
Event Code:
[IntegrationEvent(true, false)]
local procedure OnCheckCreditMaxBeforeInsertOnBeforeSalesHeaderCheck(var SalesHeader: Record "Sales Header")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
