### ISSUE TITLE
[Event Request] Database::"Sales Header" - Function UpdateAllLineDim - OnUpdateAllLineDimOnBeforeConfirm

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11617]
We like to request the following Event:
Object: Database::"Sales Header"
Function: UpdateAllLineDim
Publisher Event: OnUpdateAllLineDimOnBeforeConfirm
Reason: To implement custom business logic
Where is the event placed:
if NewParentDimSetID = OldParentDimSetID then
exit;
IsHandled := false;
OnUpdateAllLineDimOnBeforeConfirm(Rec, IsHandled);
if not IsHandled then
if not GetHideValidationDialog and GuiAllowed then
if not ConfirmUpdateAllLineDim(NewParentDimSetID, OldParentDimSetID) then
exit;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnUpdateAllLineDimOnBeforeConfirm(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
begin
end;

**Comment by RomanZanizdra** [comment]
Hi @acadonAG-dev .
There is already "IsHandled" event in ConfirmUpdateAllLineDim() procedure, you can skip it there. Does fit to you?
```
    local procedure ConfirmUpdateAllLineDim(NewParentDimSetID: Integer; OldParentDimSetID: Integer) Confirmed: Boolean;
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeConfirmUpdateAllLineDim(Rec, xRec, NewParentDimSetID, OldParentDimSetID, Confirmed, IsHandled);
        if not IsHandled then
            Confirmed := Confirm(Text064);
    end;

```

**Comment by RomanZanizdra** [comment]
Hi @acadonAG-dev , any update from your side?

**Comment by acadonAG-dev** [comment]
Hello @RomanZanizdra , yes, this event should be sufficient. Thank you for your response.
