### ISSUE TITLE
[Event Request] codeunit 2584 "Dim Corr Analysis View" - OnAfterShouldUpdateAnalysisView

### ISSUE THREAD

**Issue by dkatson** [microsoft/ALAppExtensions#11613]
Hi team, 
please add OnAfterShouldUpdateAnalysisView() to the procedure ShouldUpdateAnalysisView()

<img width="990" alt="image" src="https://user-images.githubusercontent.com/29101017/110764365-8d6e2800-8285-11eb-8a1b-3c8dacf0fabc.png">

The reason is additional control which Analysis Views to update (for example by adding a field "Don't update on Dimension Correction")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
