### ISSUE TITLE
[Event Request] Codeunit::"Sales Line - Price" - Function ValidatePrice - OnAfterValidatePrice

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11618]
We like to request the following Event:
Object: Codeunit::"Sales Line - Price"
Function: ValidatePrice
Publisher Event: OnAfterValidatePrice
Reason: To implement custom business logic
Note: Please implement this event for all implementations of "Line With Price" (e.g. ItemJournalLine, ...)
CurrPriceType::Purchase:
SalesLine.Validate("Unit Cost (LCY)");
end;
end;
OnAfterValidatePrice(SalesLine, CurrPriceType, AmountType);
end;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterValidatePrice(var SalesLine: Record "Sales Line"; CurrPriceType: Enum "Price Type"; AmountType: Enum "Price Amount Type")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
