### ISSUE TITLE
[Event Request] Codeunit 1535 "Approvals Mgmt." - OnBeforeApproveSelectedApprovalRequest

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#11610]
Hello,

We would need an event **OnBeforeApproveSelectedApprovalRequest** at the start of the function **ApproveSelectedApprovalRequest**.
I noticed there is already a request for an event in https://github.com/microsoft/ALAppExtensions/issues/11403.

    local procedure ApproveSelectedApprovalRequest(var ApprovalEntry: Record "Approval Entry")
    var
        IsHandled: Boolean;
    begin
        // begin new event 
        IsHandled := false;
        OnBeforeApproveSelectedApprovalRequest(ApprovalEntry, IsHandled);
        if IsHandled then
            exit;
        // end new event
        IsHandled := false;
        OnApproveSelectedApprovalRequestOnBeforeCheckStatus(ApprovalEntry, IsHandled);
        if not IsHandled then
            if ApprovalEntry.Status <> ApprovalEntry.Status::Open then
                Error(ApproveOnlyOpenRequestsErr);
        if ApprovalEntry."Approver ID" <> UserId then
            CheckUserAsApprovalAdministrator(ApprovalEntry);

        ApprovalEntry.Validate(Status, ApprovalEntry.Status::Approved);
        ApprovalEntry.Modify(true);
        OnApproveApprovalRequest(ApprovalEntry);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeApproveSelectedApprovalRequest(var ApprovalEntry: Record "Approval Entry"; var IsHandled: Boolean);
    begin
    end;

We have some checks in this function and if they are not met we do an exit. That's why, this event needs to be before the one already requested.

**Comment by CameliaPopescu** [comment]
version to implement >= 17.4

**Comment by StanPesotskiy** [comment]
By the rules we merge a new event to the previous version only. As the current master version is 19.0 it will be merged to the next update for the version 18 -> 18.1.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
