### ISSUE TITLE
[Event Request] Codeunit::"Sales Line - Price" - Function IsDiscountAllowed - OnAfterIsDiscountAllowed

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11620]
We like to request the following Event:
Object: Codeunit::"Sales Line - Price"
Function: IsDiscountAllowed
Publisher Event: OnAfterIsDiscountAllowed
Reason: To implement custom business logic
Note: Please implement this event for all implementations of "Line With Price" (e.g. ItemJournalLine, ...)
begin
Result := SalesLine."Allow Line Disc." or not PriceCalculated;
OnAfterIsDiscountAllowed(SalesLine, PriceCalculated, Result);
end;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterIsDiscountAllowed(SalesLine: Record "Sales Line"; PriceCalculated: Boolean; var Result: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
