### ISSUE TITLE
[Event Request] Codeunit::"TransferOrder-Post Shipment" - Function PostWhseJnlLine - OnBeforePostWhseJnlLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11622]
We like to request the following Event:
Object: Codeunit::"TransferOrder-Post Shipment"
Function: PostWhseJnlLine
Publisher Event: OnBeforePostWhseJnlLine
Reason: To implement custom business logic
Where is the event placed:
IsHandled: Boolean;
begin
IsHandled := false;
OnBeforePostWhseJnlLine(ItemJnlLine, OriginalQuantity, OriginalQuantityBase, IsHandled);
if IsHandled then
exit;
with ItemJnlLine do begin
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforePostWhseJnlLine(ItemJnlLine: Record "Item Journal Line"; OriginalQuantity: Decimal; OriginalQuantityBase: Decimal; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
