### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Activity-Register" - Function UpdateWhseSourceDocLine - OnAfterUpdateSourceLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11629]
We like to request the following Event:
Object: Codeunit::"Whse.-Activity-Register"
Function: UpdateWhseSourceDocLine
Publisher Event: OnAfterUpdateSourceLine
Reason: To implement custom business logic
Where is the event placed:
"Whse. Document Type"::"Internal Put-away":
if "Action Type" <> "Action Type"::Take then
UpdateWhseIntPutAwayLine(WhseActivLine);
end;
OnAfterUpdateSourceLine(WhseActivLine, WhseDocType2);
if "Activity Type" = "Activity Type"::"Invt. Movement" then
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterUpdateSourceLine(var WarehouseActivityLine: Record "Warehouse Activity Line"; WhseDocType2: Option)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
