### ISSUE TITLE
[Event Request] Codeunit::"TransferOrder-Post Receipt" - Function InsertTransRcptLine - OnBeforeFindWhseRcptLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11621]
We like to request the following Event:
Object: Codeunit::"TransferOrder-Post Receipt"
Function: InsertTransRcptLine
Publisher Event: OnBeforeFindWhseRcptLine
Reason: To implement custom business logic
WhseRcptLine.SetRange("Source Type", DATABASE::"Transfer Line");
WhseRcptLine.SetRange("Source No.", TransLine."Document No.");
WhseRcptLine.SetRange("Source Line No.", TransLine."Line No.");
OnBeforeFindWhseRcptLine(TransLine, TransRcptLine, WhseRcptLine);
if WhseRcptLine.FindFirst then begin
WhseRcptLine.TestField("Qty. to Receive", TransRcptLine.Quantity);
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeFindWhseRcptLine(var TransLine: Record "Transfer Line"; var TransRcptLine: Record "Transfer Receipt Line"; var WhseRcptLine: Record "Warehouse Receipt Line")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
