### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Activity-Register" - Function RegisterWhseActivityLines - OnRegisterWhseActivityLinesOnBeforeValidateQuantityFields

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11628]
We like to request the following Event:
Object: Codeunit::"Whse.-Activity-Register"
Function: RegisterWhseActivityLines
Publisher Event: OnRegisterWhseActivityLinesOnBeforeValidateQuantityFields
Reason: To implement custom business logic
Where is the event placed:
end else begin
QtyDiff := "Qty. Outstanding" - "Qty. to Handle";
QtyBaseDiff := "Qty. Outstanding (Base)" - "Qty. to Handle (Base)";
IsHandled := false;
OnRegisterWhseActivityLinesOnBeforeValidateQuantityFields(WarehouseActivityLine, QtyDiff, QtyBaseDiff, HideDialog, IsHandled);
if not IsHandled then begin
UpdateWhseActivLineQtyOutstanding(WarehouseActivityLine, QtyDiff, QtyBaseDiff);
Validate("Qty. to Handle", QtyDiff);
Event Code:
[IntegrationEvent(false, false)]
local procedure OnRegisterWhseActivityLinesOnBeforeValidateQuantityFields(var WarehouseActivityLine: Record "Warehouse Activity Line"; var QtyDiff: Decimal; var QtyBaseDiff: Decimal; HideDialog: Boolean; var IsHandled: Boolean)
begin
end;

**Comment by AlexanderYakunin** [comment]
Look like we already implemented this event

    local procedure UpdateWhseActivLineQtyOutstanding(var WarehouseActivityLine: Record "Warehouse Activity Line"; QtyDiff: Decimal; QtyBaseDiff: Decimal)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateWhseActivLineQtyOutstanding(WarehouseActivityLine, QtyDiff, QtyBaseDiff, HideDialog, IsHandled);
        if IsHandled then
            exit;

        with WarehouseActivityLine do begin
            Validate("Qty. Outstanding", QtyDiff);
            if "Qty. Outstanding (Base)" > QtyBaseDiff then // round off error- qty same, not base qty
                "Qty. Outstanding (Base)" := QtyBaseDiff;
        end;
    end;

**Comment by acadonAG-dev** [comment]
We need to handle that quantity validations like that.

QtyDiff := "Qty. Outstanding" - "Qty. to Handle";
QtyBaseDiff := "Qty. Outstanding (Base)" - "Qty. to Handle (Base)";
IsHandled := false;
OnRegisterWhseActivityLinesOnBeforeValidateQuantityFields(WarehouseActivityLine, QtyDiff, QtyBaseDiff, HideDialog, IsHandled);
if not IsHandled then begin
    UpdateWhseActivLineQtyOutstanding(WarehouseActivityLine, QtyDiff, QtyBaseDiff);
    Validate("Qty. to Handle", QtyDiff);
    if "Qty. to Handle (Base)" > QtyBaseDiff then // round off error- qty same, not base qty
        "Qty. to Handle (Base)" := QtyBaseDiff;
    if HideDialog then
        Validate("Qty. to Handle", 0);
    Validate("Qty. Handled", Quantity - "Qty. Outstanding");
end;
OnBeforeWhseActivLineModify(WarehouseActivityLine);
Modify;
