### ISSUE TITLE
[Event Request] Codeunit::"Whse. Jnl.-Register Line" - Function DeleteFromBinContent - OnAfterClearFilterFromBinContent

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11632]
We like to request the following Event:
Object: Codeunit::"Whse. Jnl.-Register Line"
Function: DeleteFromBinContent
Publisher Event: OnAfterClearFilterFromBinContent
Reason: To implement custom business logic
Where is the event placed:
FromBinContent.ClearTrackingFilters();
OnAfterClearFilterFromBinContent(WhseEntry2, FromBinContent, WhseEntry);
FromBinContent.CalcFields("Quantity (Base)");
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterClearFilterFromBinContent(var WarehouseEntry2: Record "Warehouse Entry"; var BinContent: Record "Bin Content"; WarehouseEntry: Record "Warehouse Entry")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
