### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Shipment" - Function PostSourceDocument - OnPostSourceDocumentAfterGetWhseShptHeader

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11638]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Shipment"
Function: PostSourceDocument
Publisher Event: OnPostSourceDocumentAfterGetWhseShptHeader
Reason: To implement custom business logic
Where is the event placed:
with WhseShptLine do begin
WhseShptHeader.Get("No.");
OnPostSourceDocumentAfterGetWhseShptHeader(WhseShptLine, WhseShptHeader);
case "Source Type" of
DATABASE::"Sales Line":
Event Code:
[IntegrationEvent(false, false)]
local procedure OnPostSourceDocumentAfterGetWhseShptHeader(WhseShptLine: Record "Warehouse Shipment Line"; var WhseShptHeader: Record "Warehouse Shipment Header")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
