### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Receipt" - Function InitSourceDocumentHeader - OnBeforeInitSalesSourceDocumentHeader

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11635]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Receipt"
Function: InitSourceDocumentHeader
Publisher Event: OnBeforeInitSalesSourceDocumentHeader
Reason: To implement custom business logic
Where is the event placed:
DATABASE::"Sales Line": // Return Order
begin
OnBeforeInitSalesSourceDocumentHeader(WhseRcptHeader, WhseRcptLine, SalesHeader);
if (SalesHeader."Posting Date" = 0D) or
(SalesHeader."Posting Date" <> WhseRcptHeader."Posting Date")
then begin
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeInitSalesSourceDocumentHeader(var WhseReceiptHeader: Record "Warehouse Receipt Header"; var WhseReceiptLine: Record "Warehouse Receipt Line"; var SalesHeader: Record "Sales Header")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
