### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Activity-Register" - Function CheckBinContent - OnAfterGetItemBeforeSetQtyToHandle

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11631]
We like to request the following Event:
Object: Codeunit::"Whse.-Activity-Register"
Function: CheckBinContent
Publisher Event: OnAfterGetItemBeforeSetQtyToHandle
Reason: To implement custom business logic
Where is the event placed:
BreakBulkQtyBaseToPlace := CalcBreakBulkQtyToPlace(TempBinContentBuffer);
GetItem("Item No.");
IsHandled := false;
OnAfterGetItemBeforeSetQtyToHandle(TempBinContentBuffer, Item, IsHandled);
if not IsHandled then begin
AbsQtyToHandleBase := Abs("Qty. to Handle (Base)");
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterGetItemBeforeSetQtyToHandle(var TempBinContentBuffer: Record "Bin Content Buffer"; Item: Record Item; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
