### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Receipt" - Function InitSourceDocumentHeader - OnBeforeInitPurchSourceDocumentHeader

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11634]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Receipt"
Function: InitSourceDocumentHeader
Publisher Event: OnBeforeInitPurchSourceDocumentHeader
Reason: To implement custom business logic
Where is the event placed:
DATABASE::"Purchase Line":
begin
OnBeforeInitPurchSourceDocumentHeader(WhseRcptHeader, WhseRcptLine, PurchHeader);
if (PurchHeader."Posting Date" = 0D) or
(PurchHeader."Posting Date" <> WhseRcptHeader."Posting Date")
then begin
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeInitPurchSourceDocumentHeader(var WhseReceiptHeader: Record "Warehouse Receipt Header"; var WhseReceiptLine: Record "Warehouse Receipt Line"; var PurchHeader: Record "Purchase Header")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
