### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Receipt" - Function "Code" - OnAfterWhseRcptLineSetFilters

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11633]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Receipt"
Function: "Code"
Publisher Event: OnAfterWhseRcptLineSetFilters
Reason: To implement custom business logic
Where is the event placed:
SetRange("No.", "No.");
SetFilter("Qty. to Receive", '>0');
OnAfterWhseRcptLineSetFilters(WhseRcptLine);
if Find('-') then
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterWhseRcptLineSetFilters(var WhseReceiptLine: Record "Warehouse Receipt Line")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
