### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Activity-Register" - Function CheckBinContent - OnAfterCheckBinContent

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11630]
We like to request the following Event:
Object: Codeunit::"Whse.-Activity-Register"
Function: CheckBinContent
Publisher Event: OnAfterCheckBinContent
Reason: To implement custom business logic
Where is the event placed:
end else begin
Bin.Get("Location Code", "Bin Code");
Bin.CheckWhseClass("Item No.", false);
end;
OnAfterCheckBinContent(TempBinContentBuffer, Bin);
until Next = 0;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterCheckBinContent(var TempBinContentBuffer: Record "Bin Content Buffer"; var Bin: Record Bin)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
