### ISSUE TITLE
PromotedActionCategories in Page Extensions have an error...

### ISSUE THREAD

**Issue by NeilHalliday** [microsoft/ALAppExtensions#11648]
When changing the PromotedActionCategories in a page extension the standard property does not work, however the PromotedActionCategoriesML does work. The multi-language element generates a warning however and will be an error at some point.

Here is an example of what I mean.

I'm extending the warehouse shipment page, and have the following property change in it.

![image](https://user-images.githubusercontent.com/17927660/110822829-61ed3c80-8289-11eb-84a6-29afbad3f81a.png)

When using just the PromotedActionCategories property, the result is as follows...

![image](https://user-images.githubusercontent.com/17927660/110822951-847f5580-8289-11eb-86f7-b16a54927b7a.png)

If you then change it to the PromotedActionCategoriesML the result is as follows...

![image](https://user-images.githubusercontent.com/17927660/110823313-e344cf00-8289-11eb-85b6-a46d0066fcac.png)

For the moment we can carry on using the multi-language property, but will be unable to when that is deprecated.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
