### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Shipment" - Function HandleTransferLine - OnBeforeFindWhseShptLineForTransLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11641]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Shipment"
Function: HandleTransferLine
Publisher Event: OnBeforeFindWhseShptLineForTransLine
Reason: To implement custom business logic
Where is the event placed:
repeat
SetRange("Source Line No.", TransLine."Line No.");
IsHandled := false;
OnBeforeFindWhseShptLineForTransLine(WhseShptLine, TransLine, WhseShptHeader, ModifyLine, IsHandled);
if not IsHandled then begin
if Find('-') then begin
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeFindWhseShptLineForTransLine(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var TransLine: Record "Transfer Line"; WhseShptHeader: Record "Warehouse Shipment Header"; var ModifyLine: Boolean; var IsHandled: Boolean)
begin
end;

**Comment by AlexanderYakunin** [comment]
We already have an event for this

    local procedure HandleTransferLine(var WhseShptLine: Record "Warehouse Shipment Line")
    var
        TransLine: Record "Transfer Line";
        ModifyLine: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeHandleTransferLine(WhseShptLine, TransLine, WhseShptHeader, ModifyLine, IsHandled);
        if IsHandled then
            exit;

**Comment by acadonAG-dev** [comment]
This should be sufficient, thank you.
