### ISSUE TITLE
[Event Request] Codeunit::"Whse. Undo Quantity" - Function UpdateWhseRcptLine - OnBeforeUpdateWhseRcptLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11644]
We like to request the following Event:
Object: Codeunit::"Whse. Undo Quantity"
Function: UpdateWhseRcptLine
Publisher Event: OnBeforeUpdateWhseRcptLine
Reason: To implement custom business logic
Where is the event placed:
IsHandled: Boolean;
begin
OnBeforeUpdateWhseRcptLine(PostedWhseRcptLine, IsHandled);
if IsHandled then
exit;
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateWhseRcptLine(var PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
