### ISSUE TITLE
[Event Request] Codeunit::"Whse.-Post Shipment" - Function HandlePurchaseLine - OnBeforeFindWhseShptLineForPurchLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11640]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Shipment"
Function: HandlePurchaseLine
Publisher Event: OnBeforeFindWhseShptLineForPurchLine
Reason: To implement custom business logic
Where is the event placed:
repeat
SetRange("Source Line No.", PurchLine."Line No.");
IsHandled := false;
OnBeforeFindWhseShptLineForPurchLine(WhseShptLine, PurchLine, WhseShptHeader, ModifyLine, IsHandled);
if not IsHandled then begin
if Find('-') then begin
Event Code:
[IntegrationEvent(false, false)]
local procedure OnBeforeFindWhseShptLineForPurchLine(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var PurchLine: Record "Purchase Line"; WhseShptHeader: Record "Warehouse Shipment Header"; var ModifyLine: Boolean; var IsHandled: Boolean)
begin
end;

**Comment by AlexanderYakunin** [comment]
We already have this event

        IsHandled := false;
        OnBeforeHandlePurchaseLine(WhseShptLine, PurchLine, WhseShptHeader, ModifyLine, IsHandled);
        if IsHandled then
            exit;

**Comment by acadonAG-dev** [comment]
This should be sufficient, thank you.
