### ISSUE TITLE
[Event Change] Codeunit::"Whse.-Post Shipment" - Function InitSourceDocumentHeader - OnInitSourceDocumentHeaderOnBeforeReopenPurchHeader

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11643]
We like to request the following Event:
Object: Codeunit::"Whse.-Post Shipment"
Function: InitSourceDocumentHeader
Publisher Event: OnInitSourceDocumentHeaderOnBeforeReopenPurchHeader
Reason: add an extra Parameter
Where is the event placed:
Event Code:
[IntegrationEvent(false, false)]
local procedure OnInitSourceDocumentHeaderOnBeforeReopenPurchHeader(var WhseShptLine: Record "Warehouse Shipment Line"; var PurchHeader: Record "Purchase Header")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
