### ISSUE TITLE
Event request report 7000099 "Post Bill Group"

### ISSUE THREAD

**Issue by vianju** [microsoft/ALAppExtensions#11646]
Please add a new event with signature OnBeforeCalcBankAccount(BankAcc2: Code[20]; Amount2: Decimal; EntryNo: Integer; var TempBankAccPostBuffer: Record "BG/PO Post. Buffer"; var IsHandled: Boolean). 

This event already exists in report 7000098 "Settle Docs. in Post. Bill Gr.". We need aswell in report 7000099 "Post Bill Group" in the same function.

[Scope('OnPrem')]
procedure CalcBankAccount(BankAcc2: Code[20]; Amount2: Decimal; EntryNo: Integer)
begin
    //-New event
   OnBeforeCalcBankAccount(BankAcc2, Amount2, EntryNo, BankAccPostBuffer, IsHandled);
    if IsHandled then
       exit;
   //+New event
    if TempBankAccPostBuffer.Get(BankAcc2, '', EntryNo) then begin
        TempBankAccPostBuffer.Amount := TempBankAccPostBuffer.Amount + Amount2;
        TempBankAccPostBuffer.Modify();
    end else begin
        TempBankAccPostBuffer.Init();
        TempBankAccPostBuffer.Account := BankAcc2;
        TempBankAccPostBuffer."Entry No." := EntryNo;
        TempBankAccPostBuffer.Amount := Amount2;
        TempBankAccPostBuffer.Insert();
    end;
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
