### ISSUE TITLE
[Event Request] Codeunit::"Whse. Undo Quantity" - Function InsertTempWhseJnlLine - OnAfterInitWhseJnlLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11645]
We like to request the following Event:
Object: Codeunit::"Whse. Undo Quantity"
Function: InsertTempWhseJnlLine
Publisher Event: OnAfterInitWhseJnlLine
Reason: To implement custom business logic
Where is the event placed:
repeat
TempWhseJnlLine.Init();
OnAfterInitWhseJnlLine(ItemJnlLine, WhseEntry, TempWhseJnlLine);
if WhseEntry."Entry Type" = WhseEntry."Entry Type"::"Positive Adjmt." then
"Entry Type" := "Entry Type"::"Negative Adjmt."
Event Code:
[IntegrationEvent(false, false)]
local procedure OnAfterInitWhseJnlLine(var ItemJnlLine: Record "Item Journal Line"; var WarehouseEntry: Record "Warehouse Entry"; var WarehouseJournalLine: Record "Warehouse Journal Line")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
