### ISSUE TITLE
[Application Enhancement] codeunit 5057 "VendCont-Update", function OnModify, strange TransferFields

### ISSUE THREAD

**Issue by Drakonian** [microsoft/ALAppExtensions#11649]
This function sync changes from Vendor to Contact

```
     procedure OnModify(var Vend: Record Vendor)
    var
        Cont: Record Contact;
        OldCont: Record Contact;
        ContBusRel: Record "Contact Business Relation";
        ContNo: Code[20];
        NoSeries: Code[20];
        SalespersonCode: Code[20];
        IsHandled: Boolean;
    begin
        with ContBusRel do begin
            SetCurrentKey("Link to Table", "No.");
            SetRange("Link to Table", "Link to Table"::Vendor);
            SetRange("No.", Vend."No.");
            if not FindFirst then
                exit;
            if not Cont.Get("Contact No.") then begin
                Delete();
                Session.LogMessage('0000B36', StrSubstNo(VendContactUpdateTelemetryMsg, "Contact No.", "Business Relation Code"), Verbosity::Normal, DataClassification::EndUserIdentifiableInformation, TelemetryScope::ExtensionPublisher, 'Category', VendContactUpdateCategoryTxt);
                exit;
            end;
            OldCont := Cont;
        end;

        ContNo := Cont."No.";
        NoSeries := Cont."No. Series";
        SalespersonCode := Cont."Salesperson Code";

        OnBeforeTransferFieldsFromVendToCont(Cont, Vend);
        Cont.Validate("E-Mail", Vend."E-Mail");
        Cont.TransferFields(Vend);
        OnAfterTransferFieldsFromVendToCont(Cont, Vend);

        IsHandled := false;
        OnModifyOnBeforeAssignNo(Cont, IsHandled);
        if not IsHandled then begin
            Cont."No." := ContNo;
            Cont."No. Series" := NoSeries;
        end;
        Cont."Salesperson Code" := SalespersonCode;
        Cont.Validate(Name);
        Cont.DoModify(OldCont);
        Cont.Modify(true);

        Vend.Get(Vend."No.");

        OnAfterOnModify(Cont, OldCont, Vend);
    end;
```
I am worried about the line **Cont.TransferFields (Vend)**, it seems to me it is not necessary to synchronize these two tables through the TransferFields function. On my current project, TableExtensions were created and fields were added to both the Vendor and the Contact table, since the IDs matched, but the types did not, this caused an obvious error. 
![image](https://user-images.githubusercontent.com/16802407/110866640-1d37c480-82ce-11eb-98ca-6e2c4dcc4eb9.png)

At the moment, I will of course correct this mistake by changing the IDs so that they do not match. But I'm sure that we shouldn't keep an eye on field IDs, even Microsoft shouldn't keep an eye on this in the context of Vendor-Contact tables.

Perhaps you should use a simple assignment of the required fields?

**Version**: AU Business Central 17.4 (Platform 17.0.21485.23038 + Application 17.4.21491.21531)

**Comment by AlexanderYakunin** [comment]
We use TransferFields in many places and main purpose is to copy all fields with same ID and data type.  If someone add own fields in extension, they will be copied as well without additional coding. You should consider this when you design your extension and use same ID's and data types to copy them without run time errors. If we add manual assignment here, it will be breaking change for many partner extensions and require code change each time you need to copy new field.

**Comment by Drakonian** [comment]
I understand, but then the problem remains that simply without knowing about it, you can get an unexpected error by simply adding fields to the tables. Moreover, there is a risk that it may be revealed after development.

**Comment by AlexanderYakunin** [comment]
We have many places for TransferFields and you should follow design principles to add fields consistently across related tables. This is basic NAV principle. You should also test your development before going to production. If you have ideas on how to improve this scenario, you can always publish this idea on aka.ms/bcideas portal and involve more partners into this discussion. When idea get enough supporting votes, we take it into planning and development.
