### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnBeforeSetBillToCustomerAddressFieldsFromCustomer

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11659]
Hello. In table 36 Sales Header, in the procedure SetBillToCustomerAddressFieldsFromCustomer, I would like to use the event publisher OnBeforeSetBillToCustomerAddressFieldsFromCustomer to add my own code. But I need the parameter xRec and GLSetup in it. Like this :

    procedure SetBillToCustomerAddressFieldsFromCustomer(var BillToCustomer: Record Customer)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetBillToCustomerAddressFieldsFromCustomer(Rec, BillToCustomer, SkipBillToContact, IsHandled, xRec, GLSetup);
        if IsHandled then
            exit;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetBillToCustomerAddressFieldsFromCustomer(
    var SalesHeader: Record "Sales Header"; 
    var BillToCustomer: Record Customer; 
    var SkipBillToContact: Boolean; 
    var IsHandled: Boolean; 
    xSalesHeader: Record "Sales Header";  
    var GLSetup: Record "General Ledger Setup")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
