### ISSUE TITLE
[Protection Level] Page "Email Editor" fields Description, ToField, CcField, BccField.

### ISSUE THREAD

**Issue by jwynndev** [microsoft/ALAppExtensions#11658]
I have a business requirement to make some changes to the "Email Editor" Page. I need to be able to get the "Description" field. I also need to get and set the ToField, CcField, BccField.

**Comment by JesperSchulz** [comment]
Could you elaborate a little on the business requirement? It would make it easier for us to evaluate, if we indeed would want to expose those implementation details, or if we could provide you with a different solution to your problem.

**Comment by jwynndev** [comment]
We need to add a drildown on the To, CC, BCC fields. The drilldown would open a list of contacts filtered down for the specific customer or vendor.

**Comment by JesperSchulz** [comment]
Solution suggested in #12559.

**Comment by JesperSchulz** [comment]
We won't make these fields accessible through events. Instead, we're working on an extensible "address book", which should cover your needs. We're developing that address book in the open and would be happy to receive feedback or even code change requests on PR #13165.
