### ISSUE TITLE
Autoformat keyword casing like C/Side

### ISSUE THREAD

**Issue by JSebastianN** [microsoft/ALAppExtensions#11657]
Feature request.

An option to have the formatter correct the casing of keywords.

C/Side "setrange" becomes "SETRANGE"
AL should correct it to "SetRange" 

I know, there are other options like building you own formatter or using "AL Formatter" extension.

But this should be part of AL Extension and not something extra 😉

**Comment by StanPesotskiy** [comment]
For the new features please submit a product suggestion on https://aka.ms/bcideas
