### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnBeforeValidateShippingAgentCode 

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11662]
Hello. In table 36 Sales Header, in the field 105 "Shipping Agent Code", in trigger OnValidate , I would like to use the event publisher OnBeforeValidateShippingAgentCode to add my own code. But I need the parameter xRec ans CurrFieldNo. Like this :

     OnBeforeValidateShippingAgentCode(Rec, IsHandled, xRec, CurrFieldNo);

With this integration event : 

    local procedure OnBeforeValidateShippingAgentCode(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean; var xSalesHeader: Record "Sales Header"; CurrFieldNo: Integer)

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
