### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnValidateBillToCustomerNoOnBeforeRecallModifyAddressNotification

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11661]
Hello. In table 36 Sales Header, in the field 4 "Bill-to Customer No.", in trigger OnValidate , I would like to use the event publisher OnValidateBillToCustomerNoOnBeforeRecallModifyAddressNotification to add my own code. But I need the parameter xRec. Like this :

                OnValidateBillToCustomerNoOnBeforeRecallModifyAddressNotification(Rec, xRec);
                if (xRec."Bill-to Customer No." <> '') and (xRec."Bill-to Customer No." <> "Bill-to Customer No.") then
                    RecallModifyAddressNotification(GetModifyBillToCustomerAddressNotificationId);

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnValidateBillToCustomerNoOnBeforeRecallModifyAddressNotification(var SalesHeader: Record "Sales Header"; var xSalesHeader: Record "Sales Header" )
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
