### ISSUE TITLE
[Event Request] Codeunit 90 - Function CheckAndUpdate: OnCheckAndUpdateOnAfterCalcInvoice

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#11666]
Hello, would it be possible to get an event OnCheckAndUpdateOnAfterCalcInvoice (PurchHeader as var) in Codeunit 90 Function CheckAndUpdate, like this:

           CheckICDocumentDuplicatePosting(PurchHeader);

            if Invoice then
                Invoice := CalcInvoice(PurchHeader);

            if Invoice then
                CopyAndCheckItemCharge(PurchHeader);
            **OnCheckAndUpdateOnAfterCalcInvoice(PurchHeader);** //New

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
