### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnBeforeUpdateSalesLinesByFieldNo 

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11668]
Hello. In table 36 Sales Header, in the procedure UpdateSalesLinesByFieldNo, I would like to use the event publisher OnBeforeUpdateSalesLinesByFieldNo to add my own code. But I need the parameter xRec in this event publisher. Like this :

    procedure UpdateSalesLinesByFieldNo(ChangedFieldNo: Integer; AskQuestion: Boolean; CurrFieldNo : Integer)
    begin
        IsHandled := false;
        OnBeforeUpdateSalesLinesByFieldNo(Rec, ChangedFieldNo, AskQuestion, IsHandled, xRec);
        if IsHandled then
            exit;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateSalesLinesByFieldNo(var SalesHeader: Record "Sales Header"; ChangedFieldNo: Integer; var AskQuestion: Boolean; var IsHandled: Boolean; xSalesHeader: Record "Sales Header")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
