### ISSUE TITLE
[Event Request] Codeunit 90 - Function CheckAndUpdate: OnCheckAndUpdateOnBeforeSetPostingFlags

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#11665]
Hello, would it be possible to get an event OnCheckAndUpdateOnBeforeSetPostingFlags (PurchHeader as var) in Codeunit 90 Function CheckAndUpdate, like this:

        with PurchHeader do begin
            // Check
            ErrorMessageMgt.PushContext(ErrorContextElement, RecordId, 0, CheckPurchHeaderMsg);
            CheckMandatoryHeaderFields(PurchHeader);
            if GenJnlCheckLine.IsDateNotAllowed("Posting Date", SetupRecID) then
                ErrorMessageMgt.LogContextFieldError(
                  FieldNo("Posting Date"), StrSubstNo(PostingDateNotAllowedErr, FieldCaption("Posting Date")),
                  SetupRecID, ErrorMessageMgt.GetFieldNo(SetupRecID.TableNo, GLSetup.FieldName("Allow Posting From")),
                  ForwardLinkMgt.GetHelpCodeForAllowedPostingDate);
            **OnCheckAndUpdateOnBeforeSetPostingFlags(PurchHeader, TempPurchLineGlobal); //New**
            SetPostingFlags(PurchHeader);
            OnCheckAndUpdateOnAfterSetPostingFlags(PurchHeader, TempPurchLineGlobal);

            InitProgressWindow(PurchHeader);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
