### ISSUE TITLE
Event request - page 6631 "Sales Return Order Subform"

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#11664]
Hello,

Please add publisher OnBeforeSetDefaultType(Rec, xRec, IsHandled) in page 6631 "Sales Return Order Subform":

![image](https://user-images.githubusercontent.com/34686682/111052816-c01f4880-845e-11eb-8fde-ac9e8766bf5c.png)

There are similar events in other Sales subform pages (Order, Invoice), but return order is skipped for some reason.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
