### ISSUE TITLE
[Event Publisher] table 840 "Cash Flow Forecast" - GetParameters / OnAfterCalculateAllAmounts

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#11660]
We'd like to extend the 'Cash Flow Date List' report via report extensions by including new amounts / source types and adding it these amounts to the report layouts / totals. 

- [ ] Issue 1

We need to get access to **read** some report globals: CurrentDateFrom, CurrentDateTo.  This to perform the same period calculation on our extra source types. 

Please provide a global report function **GetParameters(var CurrentDateFrom, var CurrentDateTo)** (or GetCurrentDateFrom and GetCurrentDateTo if setting the values by var would be prohibited)

**UPDATE : Or make the variables protected (for use by report extensions).**

- [ ] Issue 2

We need to be able to update the NewCFSumTotal value (adding totals from new source types) We're looking into extending CalculateAllAmounts . However, this function is not extensible, since it has a fixed array[14] (or 15). Best option we see currently to move forward is getting an OnAfterCalculateAllAmounts publisher on table 840 "Cash Flow Forecast" to at least update NewCFSumTotal. 

Suggested code:

```
procedure CalculateAllAmounts(FromDate: Date; ToDate: Date; var Amounts: array[14] of Decimal; var TotalAmount: Decimal)
    var
        SourceType: Integer;
    begin
        Clear(Amounts);
        SetCashFlowDateFilter(FromDate, ToDate);
        for SourceType := 1 to ArrayLen(Amounts) do
            Amounts[SourceType] := CalcSourceTypeAmount("Cash Flow Source Type".FromInteger(SourceType));
        TotalAmount := CalcSourceTypeAmount("Cash Flow Source Type".FromInteger(0));

        OnAfterCalculateAllAmounts(FromDate, ToDate, TotalAmount); // Add new publisher here
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalculateAllAmounts(FromDate: Date; ToDate: Date; var TotalAmount: Decimal)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
