### ISSUE TITLE
[Event Request] Codeunit 90 - Function PostPurchLine: OnPostPurchLineOnAfterCreatePostedDeferralScheduleFromPurchDoc

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#11669]
Hello, would it be possible to get an event OnPostPurchLineOnAfterCreatePostedDeferralScheduleFromPurchDoc in Codeunit 90 Function PostPurchLine, like this:
                       end;
                        OnAfterPurchInvLineInsert(
                            PurchInvLine, PurchInvHeader, PurchLine, ItemLedgShptEntryNo, WhseShip, WhseReceive, SuppressCommit);
                        CreatePostedDeferralScheduleFromPurchDoc(xPurchLine, PurchInvLine.GetDocumentType,
                            PurchInvHeader."No.", PurchInvLine."Line No.", PurchInvHeader."Posting Date");
                        **OnPostPurchLineOnAfterCreatePostedDeferralScheduleFromPurchDoc(
                            PurchInvLine, PurchInvHeader, PurchLine, ItemLedgShptEntryNo, WhseShip, WhseReceive, SuppressCommit)**
                    end;
                end else begin // Credit Memo

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
