### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnPostCustAfterTempDtldCVLedgEntryBufInit

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#11676]
Hi, would it be possible to get an event **OnPostCustAfterTempDtldCVLedgEntryBufInit** in codeunit 12 (**Gen. Jnl.-Post Line**), like this:

```
local procedure PostCust(var GenJnlLine: Record "Gen. Journal Line"; Balancing: Boolean)
    var
        LineFeeNoteOnReportHist: Record "Line Fee Note on Report Hist.";
        Cust: Record Customer;
        ...
    begin
        SalesSetup.Get();
        with GenJnlLine do begin
            TempDtldCVLedgEntryBuf.DeleteAll();
            TempDtldCVLedgEntryBuf.Init();
            OnPostCustOnBeforeTempDtldCVLedgEntryBufCopyFromGenJnlLine(GenJnlLine, CustLedgEntry, Cust, GLReg);
            TempDtldCVLedgEntryBuf.CopyFromGenJnlLine(GenJnlLine);
            OnPostCustAfterTempDtldCVLedgEntryBufInit(GenJnlLine,TempDtldCVLedgEntryBuf);
            TempDtldCVLedgEntryBuf."CV Ledger Entry No." := CustLedgEntry."Entry No.";
            ...
    end;
```

```
[IntegrationEvent(false, false)]
local procedure OnPostCustAfterTempDtldCVLedgEntryBufInit(GenJnlLine: Record "Gen. Journal Line"; var TempDtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer" temporary)
begin
end;
```

Thanks

**Comment by StanPesotskiy** [comment]
Can you use existing event OnAfterCopyFromGenJnlLine of table 383 "Detailed CV Ledg. Entry Buffer"?

**Comment by SteinleMossFeldhaus** [comment]
No this would not work.

**Comment by StanPesotskiy** [comment]
Could you please describe a scenario when it does not work?

**Comment by SteinleMossFeldhaus** [comment]
I only want to set a certain value in this particular instance, if it gets set at the other instance it will lead to problems.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
