### ISSUE TITLE
[Event Request] Codeunit 90 - OnBeforePostItemLine

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#11673]
Hello, could you please add another value (TempPurchLineGlobal) in codeunit 90 Event OnBeforePostItemLine:

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostItemLine(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; PurchRcptHeader: Record "Purch. Rcpt. Header"; RemQtyToBeInvoiced: Decimal; **TempPurchLineGlobal: Record "Purchase Line" temporary)**
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
