### ISSUE TITLE
[Event Request] Page 347 Report Selection - Purchase - OnSetUsageFilterOnAfterSetFiltersByReportUsage

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11671]
We need possibility to have our additional checks in case statement. Please add an event at the end of procedure SetUsageFilter in the else state like in issue #9053 "[Event Request] Page 306 Report Selection - Sales - OnSetUsageFilter". 

Placement in Code:
 ```
     ReportUsage2::"Vendor Remittance":
        SetRange(Usage,Usage::"V.Remittance");
      ReportUsage2::"Vendor Remittance - Posted Entries":
        SetRange(Usage,Usage::"P.V.Remit.");
    end;
        **OnSetUsageFilterOnAfterSetFiltersByReportUsage(Rec, ReportUsage2);**
    FilterGroup(0);
    CurrPage.Update;
```

```
[IntegrationEvent(false, false)]
local procedure OnSetUsageFilterOnAfterSetFiltersByReportUsage(var ReportSelections: Record "Report Selections"; ReportUsage2: Enum "ReportUsage2")
```
Name of enum like definied in / set because of issue #10059

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
