### ISSUE TITLE
[Event Request] Codeunit 90 - Function PostItemChargeLine: OnPostItemChargeLineOnAfterPostItemCharge

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#11675]
Hello, would it be possible to get an event OnPostItemChargeLineOnAfterPostItemCharge(TempItemChargeAssgntPurch, PurchHeader, PurchaseLineBackup) in Codeunit 90 Function PostItemChargeLine:

                    TempItemChargeAssgntPurch."Applies-to Doc. Type"::Order,
                  TempItemChargeAssgntPurch."Applies-to Doc. Type"::Invoice,
                  TempItemChargeAssgntPurch."Applies-to Doc. Type"::"Return Order",
                  TempItemChargeAssgntPurch."Applies-to Doc. Type"::"Credit Memo":
                        CheckItemCharge(TempItemChargeAssgntPurch);
                end;

                **OnPostItemChargeLineOnAfterPostItemCharge(TempItemChargeAssgntPurch, PurchHeader, PurchLine, PurchaseLineBackup);** //New

            until TempItemChargeAssgntPurch.Next() = 0;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
