### ISSUE TITLE
[Event Request] Page 44 "Sales Credit Memo" - OnBeforeOpenPage

### ISSUE THREAD

**Issue by Pepito-lab** [microsoft/ALAppExtensions#11679]
Hi, would it be possible to get an event OnBeforeOpenPage page 44 "Sales Credit Memo", like this :

```
    trigger OnOpenPage()
    var
        EnvironmentInfo: Codeunit "Environment Information";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeOpenPage(IsHandled);
        if not IsHandled then begin
            if UserMgt.GetSalesFilter <> '' then begin
                FilterGroup(2);
                SetRange("Responsibility Center", UserMgt.GetSalesFilter);
                FilterGroup(0);
            end;
        end;
```

    ```
[IntegrationEvent(false, false)]
    local procedure OnBeforeOpenPage(IsHandled: Boolean)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
