### ISSUE TITLE
[Event Request] Application “Tests-SCM” Codeunit 137621 "SCM Costing Bugs II"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#11689]
[Event Request]Application “Tests-SCM”, 137621 "SCM Costing Bugs II"

Could you please insert the OnTestInitialize Event at the beginning of each test procedure ?
![pic1](https://user-images.githubusercontent.com/45795262/111305874-c9bfd080-8657-11eb-872a-224a9eaa7810.png)

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
