### ISSUE TITLE
[Event Request] Application “Tests-SCM” Codeunit 137401 "SCM Item Budget"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#11688]
[Event Request]Application “Tests-SCM”, 137401 "SCM Item Budget"

Could you please insert the OnTestInitialize Event at the beginning of the test procedure SalesAnalysisByDimMatrixForBudgetAmount?
![pic1](https://user-images.githubusercontent.com/45795262/111305522-5b7b0e00-8657-11eb-88da-cf8de50eae20.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
