### ISSUE TITLE
[Event Request] Please add OnAfterSetTableNoBeforeElseCase in page 802 "Online Map Address Selector"

### ISSUE THREAD

**Issue by CL2-SWECON** [microsoft/ALAppExtensions#11683]
In page 802 "Online Map Address Selector"    

please add IntegrationEvent OnAfterSetTableNoBeforeElseCase in 

    procedure SetTableNo()
    var
        IsHandled: Boolean;
    begin
        case LookupSelection of
            LookupSelection::" ":
                SelectedTableNo := 0;
            LookupSelection::Bank:
                SelectedTableNo := DATABASE::"Bank Account";
            LookupSelection::Contact:
                SelectedTableNo := DATABASE::Contact;
            LookupSelection::Customer:
                SelectedTableNo := DATABASE::Customer;
            LookupSelection::Employee:
                SelectedTableNo := DATABASE::Employee;
            LookupSelection::Job:
                SelectedTableNo := DATABASE::Job;
            LookupSelection::Location:
                SelectedTableNo := DATABASE::Location;
            LookupSelection::Resource:
                SelectedTableNo := DATABASE::Resource;
            LookupSelection::Vendor:
                SelectedTableNo := DATABASE::Vendor;
            LookupSelection::"Ship-to Address":
                SelectedTableNo := DATABASE::"Ship-to Address";
            LookupSelection::"Order Address":
                SelectedTableNo := DATABASE::"Order Address";
            
            OnAfterSetTableNoBeforeElseCase(LookupSelection, SelectedTableNo, IsHandled);
            
            else begin
                    IsHandled := false;
                    OnSetTableNoElseCase(LookupSelection, SelectedTableNo, IsHandled);
                    if not IsHandled then
                        Error(Text001);
                end;
        end;
    end;

**Comment by StanPesotskiy** [comment]
Can you use existing event OnSetTableNoElseCase?

**Comment by CL2-SWECON** [comment]
In general yes, I could use OnSetTableNoElseCase, but the else cases are normally for non mappable cases...
So I would prefer to get my requested integration event at the right place (at the end inside the cases).
OnSetTableNoElseCase can only be a temporary workaraound to place a new case for TableNo.

**Comment by StanPesotskiy** [comment]
Could you please describe a scenario when it does not work?

**Comment by CL2-SWECON** [comment]
For example when you add an error or other functionality in else case in the future

**Comment by StanPesotskiy** [comment]
The code you suggested (at the end inside the cases) cannot be compiled. 
If you want an ability to overwrite the result of the cases that exist you need to ask for OnAfterSetTableNo() event that is called in the end.
If you want to handle the case that does not exist you use the existing OnSetTableNoElseCase() event.

**Comment by CL2-SWECON** [comment]
We just want to extend the case with our extended LookupSelection.

**Comment by StanPesotskiy** [comment]
then OnAfterSetTableNo() will solve your problem. CASE will set some value in SelectedTableNo and you overwrite it in the end.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
