### ISSUE TITLE
[Event Request] Page 40 - Item Journal - OnOpenPage() - OnBeforeOpenJnl() / OnBeforeTemplateSelection()

### ISSUE THREAD

**Issue by i-dhahri** [microsoft/ALAppExtensions#11687]
Hello, would it be possible to have two events **OnBeforeOpenJnl**() and **OnBeforeTemplateSelection**() in Page 40 - "Item Journal", Trigger : OnOpenPage()  Like this :

![image](https://user-images.githubusercontent.com/77328410/111298314-e73c6c80-864e-11eb-8a43-07e4add9113c.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
