### ISSUE TITLE
[Enum Request] Please add Enum in page 802 "Online Map Address Selector" for LookupSelection

### ISSUE THREAD

**Issue by CL2-SWECON** [microsoft/ALAppExtensions#11682]
Please add Enum for LookupSelection in page 802 "Online Map Address Selector" 

field(LookupSelection; LookupSelection)
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Table Selection';
                    OptionCaption = ' ,Bank,Contact,Customer,Employee,Job,Location,Resource,Vendor,Ship-to Address,Order Address';

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
