### ISSUE TITLE
[Event Request] Add. Event Parameters - codeunit 7313 "Create Put-away" - OnCalcQtyToPutAwayOnAfterSetQtyToPutAwayBase

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#11685]
Could you please add the following Parameters to Event OnCalcQtyToPutAwayOnAfterSetQtyToPutAwayBase in Codeunit 7313 "Create Put-away"

var EverythingHandled
var RemQtyToPutAwayBase

Adjusted Publisher Call in Fct. CalcQtyToPutAway

````

- OnCalcQtyToPutAwayOnAfterSetQtyToPutAwayBase(PostedWhseRcptLine, Location, Bin, CrossDockInfo, EmptyZoneBin, QtyToPutAwayBase);
+ OnCalcQtyToPutAwayOnAfterSetQtyToPutAwayBase(PostedWhseRcptLine, Location, Bin, CrossDockInfo, EmptyZoneBin, QtyToPutAwayBase, EverythingHandled, RemQtyToPutAwayBase);

````

Adjusted Publisher 

Add Parameters EverythingHandled, RemQtyToPutAwayBase

!!! Add both Parameters with var !!!

````

-    local procedure OnCalcQtyToPutAwayOnAfterSetQtyToPutAwayBase(PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; Location: Record Location; Bin: Record Bin; CrossDockInfo: Option; EmptyZoneBin: Boolean; var QtyToPutAwayBase: Decimal)
+    local procedure OnCalcQtyToPutAwayOnAfterSetQtyToPutAwayBase(PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; Location: Record Location; Bin: Record Bin; CrossDockInfo: Option; EmptyZoneBin: Boolean; var QtyToPutAwayBase: Decimal; var EverythingHandled: Boolean; var RemQtyToPutAwayBase: Decimal)


````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
