### ISSUE TITLE
[Event Request] Page 5097 "Create Task" - Procedure "EnableFields" "OnAfterEnableFields"

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11681]
Please make following global vars protected for an access per (below requested) event:
- EndingTimeEnable
- StartTimeEnable
- SalespersonCodeEditable
- TeamTodoEditable

Please provide an OnAfterEnableFields-Event as have on a few vars a different controlling of editability. 

Integration Event[true, true] 
local procedure OnAfterEnableFields(var Sender: Page "Create Task", Todo: Record "To-Do")
begin
end;

**Comment by StanPesotskiy** [comment]
GlobalVarAccess was deprecated in 16.x, there is concept of protected var instead. 
You can list here the global vars that have to be protected and accessible from extensions.

**Comment by SWE-Tina** [comment]
Global vars are listed in the comment, but here again:

- EndingTimeEnable
- StartTimeEnable
- SalespersonCodeEditable
- TeamTodoEditable

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
