### ISSUE TITLE
[Event Fix] Codeunit 5520 - Get Unplanned Demand - OnBeforeGetSalesLineNeededQty is missing statement to exit if IsHandled = true

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#11697]
Dear ALAppExtensions team,
Through this issue we would like to request a fix for the implementation of event `OnBeforeGetSalesLineNeededQty` in codeunit 5520 Get Unplanned Demand.
The event was requested in #4530, but it is missing a statement that acts on the value of the `IsHandled` parameter.

To fix this we would like to suggest the following change:
```al
    local procedure GetSalesLineNeededQty(SalesLine: Record "Sales Line") NeededQty: Decimal
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetSalesLineNeededQty(SalesLine, NeededQty, IsHandled);
        // >> ADD THIS STATEMENT
        if IsHandled then
            exit(NeededQty);
        // << ADD THIS STATEMENT

        with SalesLine do begin
            if Planned or ("No." = '') or (Type <> Type::Item) or "Drop Shipment" or "Special Order"
            then
                exit(0);

            CalcFields("Reserved Qty. (Base)");
            exit(-SignedXX("Outstanding Qty. (Base)" - "Reserved Qty. (Base)"));
        end;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
