### ISSUE TITLE
[Event Request] Page 54 - Purchase Order Subform - OnBeforeOpenSpecOrderSalesOrderForm

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#11699]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeOpenSpecOrderSalesOrderForm` to be added to Page 54 Purchase Order Subform with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOpenSpecOrderSalesOrderForm(var PurchaseLine: Record "Purchase Line"; var SalesHeader: Record "Sales Header"; var SalesOrder: Page "Sales Order"; var IsHandled: Boolean)
    begin
    end;
```
with **VAR** parameters.

which would be called as follows from `OpenSpecOrderSalesOrderForm`:
```al
    local procedure OpenSpecOrderSalesOrderForm()
    var
        SalesHeader: Record "Sales Header";
        SalesOrder: Page "Sales Order";
        IsHandled: Boolean;
    begin
        // >> NEW EVENT
        IsHandled := false;
        OnBeforeOpenSpecOrderSalesOrderForm(Rec, SalesHeader, SalesOrder, IsHandled);
        if IsHandled then
            exit;
        // << NEW EVENT

        TestField("Special Order Sales No.");
        SalesHeader.SetRange("No.", "Special Order Sales No.");
        SalesOrder.SetTableView(SalesHeader);
        SalesOrder.Editable := false;
        SalesOrder.Run;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
