### ISSUE TITLE
[Event Question] Table 38 - Strange parameter published by an existing event

### ISSUE THREAD

**Issue by Bleika** [Microsoft/ALAppExtensions#1169]
Hi,

Working on Table 38, I need to catch UpdatePurchLinesByFieldNo to update T39.
This function publishes an event within the CASE-loop that determines which field has triggered the call.
As a last option (ELSE) within the loop, the event is published in the following way:

OnUpdatePurchLinesByChangedField**Name**(Rec,PurchLine,**Field."Field Caption"**); 

Bearing in mind the definition of the publisher function:
UpdatePurchLinesByFieldNo(ChangedFieldNo : Integer;AskQuestion : Boolean),
wouldn't it be logical either just to pass FieldNo along or expose FieldName as a parameter in the Event?

**As is, any subscriber code must use FieldCaption and obviously the event signature is very misleading (says FieldName when it's actually FieldCaption)**

It seems quite twisted - I was expecting to write either of these 2:

case **ChangedFieldNo** of
PurchHeader.**FieldNo**(AnyTableExtensionField) :
_(standard code way)_

or directly

case **ChangedFieldName** of 
PurchHeader.**AnyTableExtensionField** :
_(standard code when not dealing with FieldNo)_

But instead, the code must read as follows:

case **ChangedFieldName** of
            PurchHeader.**FieldCaption**(AnyTableExtensionField) :

Since you're just dealing with a string, if you don't notice that FieldName is actually FieldCaption, you'll end up with buggy code...

**Comment by JesperSchulz** [comment]
Tagging as event request, as it is related to an event we've introduced.

**Comment by Bleika** [comment]
That's fine Jesper - I've adjusted the label as well.
Anyhow, in hindsight I think my perfectionism maybe took me a little over-board on this one ;-)
