### ISSUE TITLE
[Event Request] Codeunit::"Copy Document Mgt." - Function CopySalesDocLine - OnCopySalesDocLineOnInitShipmentlineOnExactCostRevMandandory

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11690]
We like to request the following Event:
Object: Codeunit::"Copy Document Mgt."
Function: CopySalesDocLine
Publisher Event: OnCopySalesDocLineOnInitShipmentlineOnExactCostRevMandandory
Reason: To implement custom business logic
Where is the event placed:
IsHandled := false;
        OnCopySalesDocLineOnBeforeCheckLocationOnWMS(ToSalesHeader, ToSalesLine, FromSalesLine, IsHandled);
        if not IsHandled then
            ToSalesLine.CheckLocationOnWMS;

        **IsHandled := false;
        OnCopySalesDocLineOnInitShipmentlineOnExactCostRevMandandory(ToSalesHeader, ToSalesLine, FromSalesLine, Currency, ExactCostRevMandatory, RecalculateAmount, CreateToHeader, MoveNegLines, IsHandled);**
        If not IsHandled then begin
            if ExactCostRevMandatory and
            (FromSalesLine.Type = FromSalesLine.Type::Item) and
            (FromSalesLine."Appl.-from Item Entry" <> 0) and
            not MoveNegLines
            then begin
                if RecalculateAmount then
                    RecalculateSalesLineAmounts(FromSalesLine, ToSalesLine, Currency);
                ToSalesLine.Validate("Appl.-from Item Entry", FromSalesLine."Appl.-from Item Entry");
                if not CreateToHeader then
                    if ToSalesLine."Shipment Date" = 0D then
                        InitShipmentDateInLine(ToSalesHeader, ToSalesLine);
            end;
        end;

        if MoveNegLines and (ToSalesLine.Type <> ToSalesLine.Type::" ") then begin
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCopySalesDocLineOnInitShipmentlineOnExactCostRevMandandory(var ToSalesHeader: Record "Sales Header"; var ToSalesLine: Record "Sales Line"; var FromSalesLine: Record "Sales Line"; Currency: Record Currency; ExactCostRevMandatory: Boolean; RecalculateAmount: Boolean; CreateToHeader: Boolean; MoveNegLines: Boolean ; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
