### ISSUE TITLE
[Event Request] Codeunit::"Create Prod. Order Lines" - Function CopyFromSalesOrder- OnCopyFromSalesOrderOnAfterSalesPlanLinesInsert

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11691]
We like to request the following Event:
Object: Codeunit::"Create Prod. Order Lines"
Function: CopyFromSalesOrder
Publisher Event: OnCopyFromSalesOrderOnAfterSalesPlanLinesInsert 
Reason: To implement custom business logic
Where is the event placed:

local procedure CopyFromSalesOrder(SalesHeader: Record "Sales Header"): Boolean
    var
        SalesPlanLine: Record "Sales Planning Line" temporary;
        Location: Record Location;
        LeadTimeMgt: Codeunit "Lead-Time Management";
        ItemTrackingMgt: Codeunit "Item Tracking Management";
        SalesLineReserve: Codeunit "Sales Line-Reserve";
        LocationCode: Code[20];
        ErrorOccured: Boolean;
        QuantityBase: Decimal;
    begin
        OnBeforeCopyFromSalesOrder(SalesHeader, SalesLine, ProdOrder, NextProdOrderLineNo);

        SalesLine.SetRange("Document Type", SalesHeader."Document Type");
        SalesLine.SetRange("Document No.", SalesHeader."No.");
        if SalesLine.FindSet then
            repeat
                SalesLine.CalcFields("Reserved Quantity");
                if (SalesLine.Type = SalesLine.Type::Item) and
                   (SalesLine."No." <> '') and
                   ((SalesLine."Outstanding Quantity" - SalesLine."Reserved Quantity") <> 0)
                then
                    if IsReplSystemProdOrder(SalesLine."No.", SalesLine."Variant Code", SalesLine."Location Code") then begin
                        SalesPlanLine.Init();
                        SalesPlanLine."Sales Order No." := SalesLine."Document No.";
                        SalesPlanLine."Sales Order Line No." := SalesLine."Line No.";
                        SalesPlanLine.Validate("Item No.", SalesLine."No.");
                        OnCopyFromSalesOrderOnBeforeSalesPlanLineInsert(SalesLine, SalesPlanLine);
                        SalesPlanLine.Insert();
                    end;
            until SalesLine.Next = 0;

        **OnCopyFromSalesOrderOnAfterSalesPlanLinesInsert(SalesLine);**

        SalesPlanLine.SetCurrentKey("Low-Level Code");

Event Code:
** [IntegrationEvent(false, false)]
    local procedure OnCopyFromSalesOrderOnAfterSalesPlanLinesInsert(var SalesLine: Record "Sales Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
