### ISSUE TITLE
[Event Request] Page 99000818 - Prod. Order Components - OnBeforeReserveComp (new parameters)

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#11698]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeReserveComp` in Page 99000818 Prod. Order Components to be extended so that it gets the following signature:
```al
    [IntegrationEvent(true, false)]
    local procedure OnBeforeReserveComp(var ProdOrderComp: Record "Prod. Order Component"; var xProdOrderComp: Record "Prod. Order Component"; var ReserveComp: Boolean)
    begin
    end;
```
with `IncludeSender` = true and a new **VAR** parameter `ReserveComp`.

which would be called as follows from `ReserveComp`:
```al
    procedure ReserveComp()
    var
        Item: Record Item;
        ReserveComp: Boolean;
    begin
        ReserveComp := false;
        if (xRec."Remaining Qty. (Base)" <> "Remaining Qty. (Base)") or
           (xRec."Item No." <> "Item No.") or
           (xRec."Location Code" <> "Location Code")
        then
            if Item.Get("Item No.") then
                ReserveComp := Item.Reserve = Item.Reserve::Always;

        OnBeforeReserveComp(Rec, xRec, ReserveComp);

        if ReserveComp then begin
            CurrPage.SaveRecord;
            AutoReserve();
            CurrPage.Update(false);
        end;
    end;
```

So what it comes down to, we would like to have a way of extending (or replacing) the condition of when `AutoReserve` is called and the CurrPage-methods are called.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
