### ISSUE TITLE
[Event Change] Codeunit::"Gen. Jnl.-Post Line" - Function PostDeferral - OnBeforePostDeferral

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#11692]
We like to request the following event change:
Object: Codeunit::"Gen. Jnl.-Post Line"
Function: PostDeferral
Publisher Event: OnBeforePostDeferral
Reason: To implement custom business logic. Please add the IsHandled Parameter.
Where is the event placed: 
local procedure PostDeferral(var GenJournalLine: Record "Gen. Journal Line"; AccountNo: Code[20])
    var
        DeferralTemplate: Record "Deferral Template";
        DeferralHeader: Record "Deferral Header";
        DeferralLine: Record "Deferral Line";
        GLEntry: Record "G/L Entry";
        CurrExchRate: Record "Currency Exchange Rate";
        DeferralUtilities: Codeunit "Deferral Utilities";
        PerPostDate: Date;
        PeriodicCount: Integer;
        AmtToDefer: Decimal;
        AmtToDeferACY: Decimal;
        EmptyDeferralLine: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePostDeferral(GenJournalLine, AccountNo, IsHandled);
        if IsHandled then
            exit;

        with GenJournalLine do begin

Event Code:
 [IntegrationEvent(false, false)]
    local procedure OnBeforePostDeferral(var GenJournalLine: Record "Gen. Journal Line"; var AccountNo: Code[20]; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
