### ISSUE TITLE
ServiceHeader - Use of global variable instead of local in CopyShipToCustomerAddressFieldsFromCust

### ISSUE THREAD

**Issue by rwe12345** [microsoft/ALAppExtensions#11693]
In the "Service Header" table, there is a new function CopyShipToCustomerAddressFieldsFromCust with a parameter SellToCustomer. 
In this function the ship to address will be set. Before this function there is a event and after this function there is an event, super.

However, for the SetShipTAddress function you use the global Cust instead of the local SellToCustomer.
Please do not use the global variable Cust in this function but the local SellToCustomer so we can change values of the customer.

![image](https://user-images.githubusercontent.com/44321194/111319762-a3556180-8666-11eb-9d39-0d381c9ca6b1.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
