### ISSUE TITLE
[Access Request] Page 1287 "Payment Application Review" - Global Variables Access

### ISSUE THREAD

**Issue by stryzhak** [microsoft/ALAppExtensions#11701]
Hi, 

Could you please make global variables in the page to be protected? We need to recalculate them using different "Account Type" and show correct ones. 

RelatedPartyMatchedText
AmountMatchText
DocumentMatchedText
DirectDebitMatchedText
DirectDebitMatched
NoOfLedgerEntriesWithinAmountTolerance
NoOfLedgerEntriesOutsideAmountTolerance
RelatedPartyMatchInfoText
DocumentMatchInfoText
DocumentMatchDetailsEnabled

P.S There is unnecessary clear variable in Clear Globals function second time
![image](https://user-images.githubusercontent.com/29860849/111352334-bb3fdc00-868c-11eb-8c3b-e7af8634e0f4.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
