### ISSUE TITLE
[Event Request] Table 1294 "Applied Payment Entry"

### ISSUE THREAD

**Issue by stryzhak** [microsoft/ALAppExtensions#11705]
Hi,

Could you please add event before each function that have case statement for "Account Type" - we need to extend logic with new type and handle it?

Functions and trigger affected :
- GetRemAmt
- GetLedgEntryInfo
- CalcAmountToApply
- CheckCurrencyCombination
- Trigger OnLookup() on field "Applies-to Entry No"

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeGetRemAmt(AppliedPaymentEntry: Record "Applied Payment Entry"; var RemainAmt: Decimal;var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetLedgEntryInfo(var AppliedPaymentEntry: Record "Applied Payment Entry";var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeLookupAppliesToDocNo(var AppliedPaymentEntry: Record "Applied Payment Entry";var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcAmountToApply(AppliedPaymentEntry: Record "Applied Payment Entry"; var RemainingAmount: Decimal;var IsHandled : Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckCurrencyCombination(AppliedPaymentEntry: Record "Applied Payment Entry"; var IsHandled : Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
