### ISSUE TITLE
[Protection Level] Page 223 "Resource Statistics" - global var access

### ISSUE THREAD

**Issue by SteinleMossGaewers** [microsoft/ALAppExtensions#11708]
Please make these global vars "ResUsagePrice", "Profit", "UnitPrice", "ResUsageCost", "ResDateName", "InvoicedPct", "ResProfitPct" accessible as we work with this in our page extension in several triggers.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
