### ISSUE TITLE
[Event Request] Table 274 "Bank Acc. Reconciliation Line"

### ISSUE THREAD

**Issue by stryzhak** [microsoft/ALAppExtensions#11703]
Hi, 

Could you please add event before each function that have `case` statement for "Account Type" - we need to extend logic with new type and handle it? 

Functions affected : 
- GetAccountName
- OpenAccountPage
- DrillDownOnNoOfLedgerEntriesBasedOnAmount

```
 [IntegrationEvent(false, false)]
    local procedure OnBeforeGetAccountName(AccountType: Option; AccountNo: Code[20]; var Name: Text; var IsHandled: Boolean)
    begin
    end;
```

```
  [IntegrationEvent(false, false)]
  local procedure OnBeforeOpenAccountPage(AccountType: Option; AccountNo: Code[20]; var IsHandled: Boolean)
  begin
  end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDrillDownOnNoOfLedgerEntriesBasedOnAmount(BankAccRecLine: Record "Bank Acc. Reconciliation Line"; AmountFilter: Text; var IsHandled: Boolean)
    begin
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
