### ISSUE TITLE
Obsolete Pending in Dataverse Connector

### ISSUE THREAD

**Issue by LorenzVanroey** [microsoft/ALAppExtensions#11709]
Dear Ms/Mr,

For custom connections between Business Central and Dataverse I used the standard function “CreateRecord” from Record “Integration Table Mapping”. But now I receive the following obsolete warning: 

“Method 'CreateRecord' is marked for removal. Reason: Use another implementation of CreateRecord. Tag: 17.0.” 

When I search for another implementation like suggested I can only find a function that has the “onprem” tag. What solution do you recommend for us?

Kind regards
Lorenz

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
The replacement method will be available in Cloud (id 393776).
