### ISSUE TITLE
[EventRequest] PurchPost.Codeunit.al (codeunit 90 "Purch.-Post") AU

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/ALAppExtensions#11719]
Hi MS,
Please help us in migrating our verticalized solution by adding below events in PurchPost.Codeunit.al Codeunit.

Standard Code (Screenshot from PostPurchLine Function)
..
PostItemTrackingLine(PurchHeader, PurchLine);

        case Type of
            Type::"G/L Account":
                PostGLAccICLine(PurchHeader, PurchLine, ICGenJnlLineNo);
            Type::Item:
                PostItemLine(PurchHeader, PurchLine, TempDropShptPostBuffer);
            Type::Resource:
                PostResourceLine(PurchHeader, PurchLine);
            Type::"Charge (Item)":
                PostItemChargeLine(PurchHeader, PurchLine);
        end;

        if (Type <> Type::" ") and ("Qty. to Invoice" <> 0) then begin
            AdjustPrepmtAmountLCY(PurchHeader, PurchLine);
            FillInvoicePostBuffer(PurchHeader, PurchLine, PurchLineACY, TempInvoicePostBuffer, InvoicePostBuffer);
            InsertPrepmtAdjInvPostingBuf(PurchHeader, PurchLine, TempInvoicePostBuffer, InvoicePostBuffer);
        end;
..

Modified Code
..
PostItemTrackingLine(PurchHeader, PurchLine);

        case Type of
            Type::"G/L Account":
                PostGLAccICLine(PurchHeader, PurchLine, ICGenJnlLineNo);
            Type::Item:
                PostItemLine(PurchHeader, PurchLine, TempDropShptPostBuffer);
            Type::Resource:
                PostResourceLine(PurchHeader, PurchLine);
            Type::"Charge (Item)":
                PostItemChargeLine(PurchHeader, PurchLine);
        end;

        OnPostPurchLineOnAfterPostByType(PurchHeader, PurchLine, GenJnlPostLine);

        if (Type <> Type::" ") and ("Qty. to Invoice" <> 0) then begin
            AdjustPrepmtAmountLCY(PurchHeader, PurchLine);
            FillInvoicePostBuffer(PurchHeader, PurchLine, PurchLineACY, TempInvoicePostBuffer, InvoicePostBuffer);
            InsertPrepmtAdjInvPostingBuf(PurchHeader, PurchLine, TempInvoicePostBuffer, InvoicePostBuffer);
        end;
..

Event Signature
..
[IntegrationEvent(false, false)]
local procedure OnPostPurchLineOnAfterPostByType(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line")
begin
end;
..

NOTE : The same event is requested earlier by me for NA and W1 localization . This time we needs it for AU localization.

Thanks
SUD

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by SUD-D365** [comment]
HI @JesperSchulz ,

Thanks for adding this event, but i am not able to find the requested parameter.

```
[IntegrationEvent(false, false)]
local procedure OnPostPurchLineOnAfterPostByType(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; **var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"**)
begin
end;
```

Can you please add this parameter into this event?

Thanks
SUD

**Comment by JesperSchulz** [comment]
@SUD-D365, any chance you could create a new issue, where you reference this one? Once processed and closed, the issues fall of the radar of the team that is processing them. Sorry to bother you with rigid processes, but this way of getting trailing problems fixed has proven to be by far the most efficient :-) Thanks!

**Comment by SUD-D365** [comment]
Ok thanks, I have just created #12653
