### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnInitRecordOnBeforeAssignWorkDateToPostingDate

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11710]
Hello. In table 36 Sales Header, in the InitRecord, I would like to use the event publisher OnInitRecordOnBeforeAssignWorkDateToPostingDate to add my own code instead. But I need a if statement with the IsHandled flag. Like this :

        IsHandled := false;
        OnInitRecordOnBeforeAssignWorkDateToPostingDate(Rec, IsHandled);
        if not IsHandled then
            if not ("Document Type" in ["Document Type"::"Blanket Order", "Document Type"::Quote]) and
               ("Posting Date" = 0D)
            then
                "Posting Date" := WorkDate;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
