### ISSUE TITLE
Enum request for "Type Filter" field in TImeSheetHeader Table

### ISSUE THREAD

**Issue by mohit0989** [microsoft/ALAppExtensions#11714]
Hi Team,

Request you to provide an enum field for "Type Filter" in Table 950 "Time Sheet Header".

Thanks
Mohit

**Comment by AlexanderYakunin** [comment]
This is already implemented in 18.0

        field(35; "Type Filter"; Enum "Time Sheet Line Type")
        {
            Caption = 'Type Filter';
            FieldClass = FlowFilter;
        }
