### ISSUE TITLE
[Request-for-external]  Page 54 "Purchase Order Subform" - OpenSpecOrderSalesOrderForm()

### ISSUE THREAD

**Issue by i-dhahri** [microsoft/ALAppExtensions#11718]
Hi, I was wondering if it would be possible to change the procedure OpenSpecOrderSalesOrderForm in Page 54  "Purchase Order Subform"  from **local** to **external**.

![image](https://user-images.githubusercontent.com/77328410/111457622-bb85b900-8718-11eb-850f-056b8d9b2733.png)

Cordially.

**Comment by AlexanderYakunin** [comment]
We can change it to protected. Is this ok?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
