### ISSUE TITLE
[Event Request] OnAfterLookupExperienceTier (ApplicationAreaMgmt.Codeunit.al)

### ISSUE THREAD

**Issue by wdet** [microsoft/ALAppExtensions#11728]
We would like to send a notification if the user has selected our experience tier. For this, we would need a new event in the function LookupExperienceTier in the codeunit "Application Area Mgmt." (Exposed via the facade codeunit).

Sample code:
```
    [Scope('OnPrem')]
    procedure LookupExperienceTier(var NewExperienceTier: Text): Boolean
    var
        TempExperienceTierBuffer: Record "Experience Tier Buffer" temporary;
        ExperienceTierSetup: Record "Experience Tier Setup";
    begin
...
        OnBeforeLookupExperienceTier(TempExperienceTierBuffer);
        if PAGE.RunModal(0, TempExperienceTierBuffer, TempExperienceTierBuffer."Experience Tier") = ACTION::LookupOK then begin
            NewExperienceTier := TempExperienceTierBuffer."Experience Tier";
            OnAfterLookupExperienceTier(NewExperienceTier);
            exit(true);
        end;
    end;
```

Integration event:

```
[IntegrationEvent(false, false)]
local procedure OnAfterLookupExperienceTier(NewExperienceTier: Text)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
