### ISSUE TITLE
[Event Request] CodeUnit 5055 - CustVendBank-Update 

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#11723]
In the codeunit 5055 Customers, Vendors & BankAccounts are created/updated from Contacts. BUT the biggest issue is that this is done via a TransferFields. The issue with this is, when a field is not the same, there is no way to skip the Transferfields and handle the issue yourself. If you look at the function **UpdateEmployee** you see that there is no TransferFields in this. This is a better way to handle the create/update. Cant you add Events So we can choose to Skip the **TransferFields**?

procedure UpdateCustomer(var Cont: Record Contact; var ContBusRel: Record "Contact Business Relation")
    var
        VATRegistrationLogMgt: Codeunit "VAT Registration Log Mgt.";
        VATRegNo: Text[20];
    begin
        with Cust do begin
            Get(ContBusRel."No.");
            NoSeries := "No. Series";
            VATRegNo := "VAT Registration No.";
            _OnBeforeTransferfieldsCustomer(Cust, Cont,IsHanled);_
            _if not IsHandled then_
                **TransferFields(Cont);**
            "No." := ContBusRel."No.";
            "No. Series" := NoSeries;
            "Last Modified Date Time" := CurrentDateTime;
            "Last Date Modified" := Today;
            OnAfterUpdateCustomer(Cust, Cont);
            Modify;
            if ("VAT Registration No." <> '') and ("VAT Registration No." <> VATRegNo) then
                VATRegistrationLogMgt.LogCustomer(Cust);
        end;
    end;

_[IntegrationEvent(false, false)]
local procedure OnBeforeTransferfieldsCustomer(var Customer: Record Customer; Contact: Record Contact; var IsHandled: Boolean)
begin
end;_

And also add the same structure for **UpdateVendor,UpdateBankAccount**.

*for some reason the spacing is gone? How do I solve this?

**Comment by guidorobben** [comment]
Sorry to put 4 codeunit is one issue, but the thing is, they all have the same issue so it would be nice if it was fixed at the same time.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
