### ISSUE TITLE
[Enum Request] Field 10800 Marital Status in table Employee

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/ALAppExtensions#11729]
Could you make the field Marital Status (localization FRA) an enum instead of option?

![image](https://user-images.githubusercontent.com/44807684/111649829-054bcd80-8805-11eb-82bb-ab2d4f11bca4.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
