### ISSUE TITLE
[Event Request] Page 43 "Sales Invoice" - OnBeforeShowPreview

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#11720]
Hi, would it be possible to get an event OnBeforeShowPreview page 43 "Sales Invoice", like this :
```
    local procedure ShowPreview()
    var
        SalesPostYesNo: Codeunit "Sales-Post (Yes/No)";
    begin
        OnBeforeShowPreview(Rec);
        SalesPostYesNo.Preview(Rec);
    end;

```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowPreview(var Rec: Record "Sales Header")
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
