### ISSUE TITLE
[Event Modification] Codeunit 408 DimensionManagement "OnCheckDimValuePostingOnBeforeLogErrors"

### ISSUE THREAD

**Issue by antony-acumencentral** [microsoft/ALAppExtensions#11724]
There is no value in DimSetEntry variable. Please change the parameter to Variable so we can access the filter that applied to the record

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
