### ISSUE TITLE
[Event-Request] Report 99001026  "Replan Production Order" - Possibility to decide which production orders are created

### ISSUE THREAD

**Issue by PatrickJakubassa** [microsoft/ALAppExtensions#11725]
Hi MS,
we need for a customer customization the possibility to decide which production orders are created by the "Replan Production Order" report.

For this we would need an event point in line 135 with the IsHandled pattern.

> Standard Code:

                      MainProdOrder.Get("Production Order".Status, "Prod. Order No.");

                       if CompItem."Replenishment System" = CompItem."Replenishment System"::"Prod. Order" then begin

                            ProdOrder.Status := MainProdOrder.Status;
                            ProdOrder."Replan Ref. No." := MainProdOrder."Replan Ref. No.";
                            ProdOrder."Replan Ref. Status" := MainProdOrder."Replan Ref. Status";
                            ProdOrder.Insert(true);

> Modified Code

                        MainProdOrder.Get("Production Order".Status, "Prod. Order No.");

                        OnProdOrderCompOnBeforeCreateProdOrder(CompItem, IsHandled);
                        if not IsHandled then
                        
                            if ((CompItem."Replenishment System" = CompItem."Replenishment System"::"Prod. Order")
                                ProdOrder.Status := MainProdOrder.Status;
                                ProdOrder."Replan Ref. No." := MainProdOrder."Replan Ref. No.";
                                ProdOrder."Replan Ref. Status" := MainProdOrder."Replan Ref. Status";
                                ProdOrder.Insert(true);

 

> Event

    [IntegrationEvent(false, false)]
    local procedure OnProdOrderCompOnBeforeCreateProdOrder(var CompItem: Record Item; var IsHandled: Boolean)
    begin
    end;

Would it be possible to create the event?

Thanks
Patrick

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
