### ISSUE TITLE
[Event Request] Table 900 - Assembly Header - OnBeforeCheckIsNotAsmToOrder

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#11736]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeCheckIsNotAsmToOrder`to be added to Table 900 Assembly Header with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckIsNotAsmToOrder(var AssemblyHeader: Record "Assembly Header"; var IsHandled: Boolean)
    begin
    end;
```

which would be called as follows from `CheckIsNotAsmToOrder`:
```al
    procedure CheckIsNotAsmToOrder()
    var
        IsHandled: Boolean;
    begin
        // << NEW EVENT BEGIN
        IsHandled := false;
        OnBeforeCheckIsNotAsmToOrder(Rec, IsHandled);
        if IsHandled then
            exit;
        // << NEW EVENT END

        CalcFields("Assemble to Order");
        TestField("Assemble to Order", false);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
