### ISSUE TITLE
[Event Request] Table 900 - Assembly Header - OnAfterCalcStartDateFromEndDate

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#11733]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnAfterCalcStartDateFromEndDate`to be added to Table 900 Assembly Header with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcStartDateFromEndDate(var AssemblyHeader: Record "Assembly Header")
    begin
    end;
```

which would be called as follows from `CalcStartDateFromEndDate`:
```al
    local procedure CalcStartDateFromEndDate(EndingDate: Date): Date
    var
        ReqLine: Record "Requisition Line";
        LeadTimeMgt: Codeunit "Lead-Time Management";
    begin
        OnBeforeCalcStartDateFromEndDate(Rec);

        exit(
          LeadTimeMgt.PlannedStartingDate(
            "Item No.", "Location Code", "Variant Code", '',
            LeadTimeMgt.ManufacturingLeadTime("Item No.", "Location Code", "Variant Code"),
            ReqLine."Ref. Order Type"::Assembly, EndingDate));

        OnAfterCalcStartDateFromEndDate(Rec); << NEW EVENT
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
