### ISSUE TITLE
[procedures local to global Request] Table 900 - Assembly Header - ValidateDueDate, ValidateEndDate, ValidateStartDate

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#11737]
Dear ALAppExtensions team,

Through this issue we would like to request to make the procedures `ValidateDueDate, ValidateEndDate, ValidateStartDate`to be added to Table 900 Assembly Header global.

These procedures are needed to validate the regarding Assembly Header date without validating the other dates.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
