### ISSUE TITLE
[Event Request] Table 274 "Bank Acc. Reconciliation Line" - RemoveAppliedPaymentEntries

### ISSUE THREAD

**Issue by stryzhak** [microsoft/ALAppExtensions#11739]
Hi, 

Could you please add following event to the end of function RemoveAppliedPaymentEntries - OnAfterRemoveAppliedPaymentEntries(Rec) ?

```
[IntegrationEvent(false, false)]
    local procedure OnAfterRemoveAppliedPaymentEntries(var BankAccRecLine: Record "Bank Acc. Reconciliation Line")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
