### ISSUE TITLE
[Event Request] Page 6510 - Item Tracking Lines - OnBeforeSynchronizeLinkedSources

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#11730]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeSynchronizeLinkedSources`to be added to Page 6510 Item Tracking Lines with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSynchronizeLinkedSources(FormRunMode: Option ,Reclass,"Combined Ship/Rcpt","Drop Shipment",Transfer; CurrentSourceType: Integer; CurrentSourceRowID: Text[250]; SecondSourceRowID: Text[250]; var DialogText: Text[250])
    begin
    end;
```
with **VAR** parameter DialogText.

which would be called as follows from `SynchronizeLinkedSources`:
```al
    procedure SynchronizeLinkedSources(DialogText: Text[250]): Boolean
    begin
        OnBeforeSynchronizeLinkedSources(FormRunMode, CurrentSourceType, CurrentSourceRowID, SecondSourceRowID, DialogText); // << NEW EVENT

        if CurrentSourceRowID = '' then
            exit(false);
        if SecondSourceRowID = '' then
            exit(false);

        ItemTrackingMgt.SynchronizeItemTracking(CurrentSourceRowID, SecondSourceRowID, DialogText);

        OnAfterSynchronizeLinkedSources(FormRunMode, CurrentSourceType, CurrentSourceRowID, SecondSourceRowID);
        exit(true);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
