### ISSUE TITLE
[Event Request] T156 Resource - procedure OnBeforeOnInsert()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#11746]
```
------- ADD PARAMETER : xRec ---------

IsHandled := false;
OnBeforeOnInsert(Rec, IsHandled, xRec);
if IsHandled then
    exit;

[IntegrationEvent(false, false)]
local procedure OnBeforeOnInsert(var Resource: Record Resource; var IsHandled: Boolean; var xResource: Record Resource)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
