### ISSUE TITLE
cannot convert from 'Text[80]' to 'List of [Text]'

### ISSUE THREAD

**Issue by mahdyg** [microsoft/ALAppExtensions#11745]
Hi

BC SaaS v 18.0.23023.0 email mentioned the following error for one of our App. Any idea how we can resolve this issue? Thanks 

Error AL0133: Argument 3: cannot convert from 'Text[80]' to 'List of [Text]'

**Comment by darjoo** [comment]
Hi @mahdyg,

Below is an example of how you can convert the Text variable into a List of [Text]

```
local procedure Example()
var
    ListOfText: List of [Text];
    Text: Text[80];
begin
    Text := 'Example Text';
    ListOfText.Add(Text);
    CallAPI(ListOfText);
end;
```

I hope I understood your question properly and that was the answer you were seeking. Otherwise please reopen the issue.

**Comment by mahdyg** [comment]
Hi Darjoo 

Thanks for your answer. I will try it and see if that solve the issue.
