### ISSUE TITLE
[Event Request] Page 99000882 "Change Status on Prod. Order"

### ISSUE THREAD

**Issue by TCutullic** [microsoft/ALAppExtensions#11741]
Hi,
Is it possible ti have an event after initialise the editable button on fonction Set plz ?
![image](https://user-images.githubusercontent.com/70213459/111763652-af2d6780-88a2-11eb-8943-da5e1257df6b.png)
![image](https://user-images.githubusercontent.com/70213459/111763740-c2d8ce00-88a2-11eb-81dc-ff40d006c19d.png)

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
