### ISSUE TITLE
Drilldown on Navigate page list part doesn't work

### ISSUE THREAD

**Issue by Avanti05** [microsoft/ALAppExtensions#11742]
We have a field with drilldown on a Navigate list part. 

In BC18 insider this no longer works. 

example of field below.
```
field(Status; Status)
{
    ApplicationArea = all;
    Editable = false;
    ShowCaption = false;
    Style = StrongAccent;
    StyleExpr = TRUE;
    DrillDown = true;
    trigger OnDrillDown();
    begin
         ResolveConflicts();
    end;
```

**Comment by AlexanderYakunin** [comment]
Please provide more specific information like repro steps. Which object you are talking about? Navigate page do not contain this code.

Even better, if you report bugs to technical support, this way it will be addressed much faster.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL extensibility. Please reach out to the relevant support channels:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
