### ISSUE TITLE
[Event Request] New publisher in Codeunit 90   OnBeforeUpdatePostingDescriptionOnInvoice    

### ISSUE THREAD

**Issue by Kayo-2021** [microsoft/ALAppExtensions#11740]
In Codeunit 80 we have this Event

![grafik](https://user-images.githubusercontent.com/80951868/111762690-940e2800-88a1-11eb-9abf-a59ef8cb38b1.png)

We should have the same for Codeunit 90. Here the Event is missing.

![grafik](https://user-images.githubusercontent.com/80951868/111762965-e8190c80-88a1-11eb-8b1d-25f6753f4958.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
