### ISSUE TITLE
[Event Request] Codeunit 7010 - Purch. Price Calc. Mgt - OnBeforeIsInMinQty

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#11754]
Hi, would it be possible to get an event OnBeforeIsInMinQty in codeunit 7010, procedure IsInMinQty, like this : 

```
    local procedure IsInMinQty(UnitofMeasureCode: Code[10]; MinQty: Decimal): Boolean
    var
        IsHandled : Boolean;
        IsInMinQty : Boolean;
    begin
        IsHandled := false;
        OnBeforeIsInMinQty(Item, IsInMinQty, IsHandled);
        if not IsHandled then begin
            if UnitofMeasureCode = '' then
                exit(MinQty <= QtyPerUOM * Qty);
            exit(MinQty <= Qty);
        end else 
            exit(IsInMinQty);
    end;

```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsInMinQty(var Item: Record Item; var IsInMinQty : Boolean; var IsHandled: Boolean)
    begin
    end; 
```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
