### ISSUE TITLE
How to add pages to departments menu

### ISSUE THREAD

**Issue by arosadop** [microsoft/ALAppExtensions#11759]
How can we add menu option to this menu?

![image](https://user-images.githubusercontent.com/11178964/111966224-f744c800-8af6-11eb-9667-6ca17dbd4506.png)

When we add custom pages we can only access it by adding them to the rolecenter or through the search engine

**Comment by jacobwj** [comment]
There are 2 ways to add to [the Role Explorer](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-role-explorer), which is the successor to Department pages:
1. Create a new profile that uses a role center page with the navigation items you would like to add
2. Extend a role center page that is used by an existing profile to add the desired navigation items

Here's info about developing role center pages: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-designing-role-centers
Here's info about add navigation items: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-adding-menus-to-navigation-pane

Lastly, make sure the Profile (Role) you target has the 'Show in Role Explorer' flag set.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
