### ISSUE TITLE
[Event Request] CU1020 JobJnlManagement 

### ISSUE THREAD

**Issue by frivadulla** [Microsoft/ALAppExtensions#1175]
It would be nice to have the following event, in order to filter the Job Journal Batch to show in the Job Journal page.
Event location:

```
[External] LookupName(VAR CurrentJnlBatchName : Code[10];VAR JobJnlLine : Record "Job Journal Line")
COMMIT;
JobJnlBatch."Journal Template Name" := JobJnlLine.GETRANGEMAX("Journal Template Name");
JobJnlBatch.Name := JobJnlLine.GETRANGEMAX("Journal Batch Name");
//NEW EVENT
OnBeforeFilterJobJnlBatch(JobJnlBatch);
//NEW EVENT
JobJnlBatch.FILTERGROUP(2);
JobJnlBatch.SETRANGE("Journal Template Name",JobJnlBatch."Journal Template Name");
JobJnlBatch.FILTERGROUP(0);
IF PAGE.RUNMODAL(0,JobJnlBatch) = ACTION::LookupOK THEN BEGIN
  CurrentJnlBatchName := JobJnlBatch.Name;
  SetName(CurrentJnlBatchName,JobJnlLine);
END;
```

Event declaration:

`LOCAL [BusinessEvent] OnBeforeFilterJobJnlBatch(VAR JobJnlBatch : Record "Job Journal Batch")`

Kind regards

**Comment by alexlang24** [comment]
This is exactly what we need as well. Please add this event publisher.
But in my mind it would be better to place it after the filter and call it
 "OnAfterFilterJobJnlBatch(JobJnlBatch);"

or even both publishers.

**Comment by frivadulla** [comment]
> 
> 
> This is exactly what we need as well. Please add this event publisher.
> But in my mind it would be better to place it after the filter and call it
> "OnAfterFilterJobJnlBatch(JobJnlBatch);"
> 
> or even both publishers.

I think that it will work the same, but maybe the 2 events would be nice.

Hope this will be implemented soon.

**Comment by AlexanderYakunin** [comment]
I think this event should 1). be OnAfterFilter and 2). placed inside of FILTERGROUP definition. Like this:

JobJnlBatch.FILTERGROUP(2);
JobJnlBatch.SETRANGE("Journal Template Name",JobJnlBatch."Journal Template Name");
OnLookupNameOnAfterSetFilters(JobJnlBatch);"
JobJnlBatch.FILTERGROUP(0);

**Comment by frivadulla** [comment]
> 
> 
> I think this event should 1). be OnAfterFilter and 2). placed inside of FILTERGROUP definition. Like this:
> 
> JobJnlBatch.FILTERGROUP(2);
> JobJnlBatch.SETRANGE("Journal Template Name",JobJnlBatch."Journal Template Name");
> OnLookupNameOnAfterSetFilters(JobJnlBatch);"
> JobJnlBatch.FILTERGROUP(0);

Yes i place it according to my needs, but your option is better. I hope this will be implemented soon.

Kind regards.
