### ISSUE TITLE
[Protection Level] Page "Item Tracking Lines" Function "AssignSerialNoBatch" remove local

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11768]
We need to access the function from an event..

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
