### ISSUE TITLE
[Event Request] CodeUnit 5763 "Whse.-Post Shipment" - OnInitSourceDocumentLines

### ISSUE THREAD

**Issue by CentralPrograms** [microsoft/ALAppExtensions#11764]
local procedure InitSourceDocumentLines(var WhseShptLine: Record "Warehouse Shipment Line")
    var
        WhseShptLine2: Record "Warehouse Shipment Line";
    begin
        WhseShptLine2.Copy(WhseShptLine);
        case WhseShptLine2."Source Type" of
            DATABASE::"Sales Line":
                HandleSalesLine(WhseShptLine2);
            DATABASE::"Purchase Line": // Return Order
                HandlePurchaseLine(WhseShptLine2);
            DATABASE::"Transfer Line":
                HandleTransferLine(WhseShptLine2);
            DATABASE::"Service Line":
                HandleServiceLine(WhseShptLine2);
            else
                   OnInitSourceDocumentLines(WhseShptLine2);
        end;
        WhseShptLine2.SetRange("Source Line No.");
    end;

You included an "else" event object in the other main work functions of this posting codeunit but not this one, I think you forgot one.  Please add it.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
