### ISSUE TITLE
[Protection Level] Page "Navigate" - Protected vars needed

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11767]
Please make 
- ContactNo
- ExtDocNo
to protected vars.

We have another header table for which we have to fond unposted document; therefore accessing / using this vars is required.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
