### ISSUE TITLE
[Protection Level] Codeunit 90 "Purch.-Post" Function "CalcInvoice" remove local

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#11762]
Hello,
we need to access the functions from an event, to not have duplicates of this functions, we need them to be global.

procedure CalcInvoice

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
