### ISSUE TITLE
[Event Request] Page "Navigate" - Function "FindExtRecords"  and "FindRecords" events needed

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11765]
All events needed for both functions and same places... 

1. OnAfterSetSalesInvoiceFilter
`[EventSubscriber(ObjectType::Page, Page::Navigate, 'OnAfterSetSalesInvoiceFilter', '', false, false)]
local procedure OnAfterSetSalesInvoiceFilter(var Sender: Page Navigate; var SalesInvoiceHeader: Record "Sales Invoice Header");
begin
end;`
Placement in code:
```
      IF SalesInvHeader.READPERMISSION THEN BEGIN
        SalesInvHeader.RESET;
        SalesInvHeader.SETCURRENTKEY("Sell-to Customer No.","External Document No.");
        SalesInvHeader.SETFILTER("Sell-to Customer No.",ContactNo);
        SalesInvHeader.SETFILTER("External Document No.",ExtDocNo);
        **OnAfterSetSalesInvoiceFilter(SalesInvHeader)**

```
2. OnAfterSetSalesCrMemoFilter
`[EventSubscriber(ObjectType::Page, Page::Navigate, 'OnAfterSetSalesCrMemoFilter', '', false, false)]
local procedure OnAfterSetSalesCrMemoFilter(var Sender: Page Navigate; var SalesCrMemoHeader: Record "Sales Cr. Memo Header");
begin
end;`

Placement in code:
```
      IF SalesCrMemoHeader.READPERMISSION THEN BEGIN
        SalesCrMemoHeader.RESET;
        SalesCrMemoHeader.SETCURRENTKEY("Sell-to Customer No.","External Document No.");
        SalesCrMemoHeader.SETFILTER("Sell-to Customer No.",ContactNo);
        SalesCrMemoHeader.SETFILTER("External Document No.",ExtDocNo);
        **OnAfterSetSalesCrMemoFilter(SalesCrMemoHeader)**
```
3. OnAfterSetFilters
```
[EventSubscriber(ObjectType::Page, Page::Navigate, 'OnAfterSetFilters', '', false, false)]
local procedure OnAfterSetFilters(var Sender: Page Navigate; var Rec: "Document Entry"; var SalesInvoiceHeader: Record "Sales Invoice Header"; var SalesCrMemoHeader: Record "Sales Cr. Memo Header");
begin
end;
```
Placement in code:
```

      **OnAfterSetFilters(SalesCrMemoHeader)**
...
      UpdateFormAfterFindRecords;
...END;
```
All 3 would be perfect to use existing code and to just be able to add additional filter criteria;  **Number 3 is needed in any case** to implement our extra filters and include additional header tables (rental and trade-ins e.g.).

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
