### ISSUE TITLE
Wrong customer variable in function CopyShipToCustomerAddressFieldsFromCustomer in table "Sales Header"

### ISSUE THREAD

**Issue by rwe12345** [microsoft/ALAppExtensions#11761]
In the table "Sales Header", function CopyShipToCustomerAddressFieldsFromCustomer, the ship to address fields are filled from the Cust global variable in stead of the local SellToCustomer. 
We can use the events in this function. The events used the local variable SellToCustomer, so the shipp to address fields should be filled from the local SellToCustomer, see the new code proposal.

Original code:
![image](https://user-images.githubusercontent.com/44321194/111978017-bb642f80-8b03-11eb-979c-f872d09e45a6.png)

New code:

    local procedure CopyShipToCustomerAddressFieldsFromCustomer(var SellToCustomer: Record Customer)
    var
        SellToCustTemplate: Record "Customer Template";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCopyShipToCustomerAddressFieldsFromCustomer(Rec, SellToCustomer, IsHandled);
        if IsHandled then
            exit;

        "Ship-to Name" := SellToCustomer.Name;
        "Ship-to Name 2" := SellToCustomer."Name 2";
        if SellToCustomerIsReplaced or ShipToAddressEqualsOldSellToAddress then begin
            "Ship-to Address" := SellToCustomer.Address;
            "Ship-to Address 2" := SellToCustomer."Address 2";
            "Ship-to City" := SellToCustomer.City;
            "Ship-to Post Code" := SellToCustomer."Post Code";
            "Ship-to County" := SellToCustomer.County;
            Validate("Ship-to Country/Region Code", SellToCustomer."Country/Region Code");
        end;
        "Ship-to Contact" := SellToCustomer.Contact;
        if SellToCustomer."Shipment Method Code" <> '' then
            Validate("Shipment Method Code", SellToCustomer."Shipment Method Code");
        if not SellToCustTemplate.Get("Sell-to Customer Template Code") then begin
            "Tax Area Code" := SellToCustomer."Tax Area Code";
            "Tax Liable" := SellToCustomer."Tax Liable";
        end;
        SetCustomerLocationCode();
        "Shipping Agent Code" := SellToCustomer."Shipping Agent Code";
        "Shipping Agent Service Code" := SellToCustomer."Shipping Agent Service Code";

        OnAfterCopyShipToCustomerAddressFieldsFromCustomer(Rec, SellToCustomer);
    end;

**Comment by dannoe** [comment]
At least in 17.4 SellToCustomer and Cust are the same record. This is the only call inside the sales header table:

``` al
if "Sell-to Customer No." <> '' then begin
    GetCust("Sell-to Customer No.");
    CopyShipToCustomerAddressFieldsFromCust(Cust);
end;
```

**Comment by rwe12345** [comment]
Hello,

Thank you for your mail.
It’s correct that Cust and SellToCustomer are the same record.

My problem is that in this function we can use the events (onbeforecopyshiptocustomeraddressfieldsfromcustomer and onaftercopyshiptocustomeraddressfieldsfromcustomer).
These events use the record variabele SellToCustomer and that’s correct, but in this function some fields were filled from the global variabele Cust and that’s not correct.
The variabele with the red line should use SellToCustomer instead of Cust.

***@***.***D72178.7E1CAE80]

Best regards,
René Welmerink



Van: ***@***.***>
Verzonden: woensdag 24 maart 2021 21:49
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [microsoft/ALAppExtensions] Wrong customer variable in function CopyShipToCustomerAddressFieldsFromCustomer in table "Sales Header" (#11761)


At least in 17.4 SellToCustomer and Cust are the same record. This is the only call inside the sales header table:

if "Sell-to Customer No." <> '' then begin

    GetCust("Sell-to Customer No.");

    CopyShipToCustomerAddressFieldsFromCust(Cust);

end;

**Comment by rwe12345** [comment]
Thank you for your comment.

It’s correct that Cust and SellToCustomer are the same record.

My problem is that in this function we can use the events (onbeforecopyshiptocustomeraddressfieldsfromcustomer and onaftercopyshiptocustomeraddressfieldsfromcustomer).
These events use the record variabele SellToCustomer and that’s correct, but in this function some fields were filled from the global variabele Cust and that’s not correct. 
The variabele with the red line should use SellToCustomer instead of Cust.

![image](https://user-images.githubusercontent.com/44321194/112471843-b229cb80-8d6c-11eb-9120-9cbd9ea37c86.png)

**Comment by dannoe** [comment]
Yes it is definitley bad that they use different variables for the same records and should fix this.
But you should be able to do everything with a subscription at the OnBefore or OnAfter event.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
