### ISSUE TITLE
[Event Request] Page "Service Order Statistic" "OnAfterCalcTotalAmount" 

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11775]
Exchange Part Calculation...

```
   [IntegrationEvent(true, true)]
    local procedure OnAfterCalcTotalAmount()
    begin
    end;
```
Proteced needed:
- TotalAmount2
- i

Placement in Code:

```

            AdjProfitLCY[i] := TotalServLineLCY[i].Amount - TotalAdjCostLCY[i];

            if TotalServLineLCY[i].Amount <> 0 then
                AdjProfitPct[i] := Round(100 * AdjProfitLCY[i] / TotalServLineLCY[i].Amount, 0.1);

            if "Prices Including VAT" then begin
                TotalAmount2[i] := TotalServLine[i].Amount;
                TotalAmount1[i] := TotalAmount2[i] + VATAmount[i];
                TotalServLine[i]."Line Amount" := TotalAmount1[i] + TotalServLine[i]."Inv. Discount Amount";
            end else begin
                TotalAmount1[i] := TotalServLine[i].Amount;
                TotalAmount2[i] := TotalServLine[i]."Amount Including VAT";
            end;

**OnAfterCalcTotalAmount**

```

**Comment by StanPesotskiy** [comment]
variable TotalServLineLCY does not exist in page 402 "Sales Order Statistics".

GlobalVarAccess was deprecated in 16.x, there is concept of protected var instead. You can list here the global vars that have to be protected and accessible from extensions.

**Comment by SWE-Tina** [comment]
Same mistake - wrong headline, excuse me. Protected vars are already listed.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
