### ISSUE TITLE
[Protection Level] Page "Service Order Statistics" functions "VATLinesDrillDown" and "UpdateHeaderInfo" as protected function needed 

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11772]
...to make it accessible from Page Extension. 
Additionally the global var "TempVATAmountLine1" needs to be a protected var too.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
