### ISSUE TITLE
[Protection Level] Page "Service Order Statistics" protected vars needed

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11773]
Again the exchange part calculation... please make 
-         TotalAmount2: array[7] of Decimal;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
