### ISSUE TITLE
[Event Request] Page "Service Order Statistics"  Function "UpdateHeaderInfo" OnAfterCalcTotalAmount2

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11776]
Again Exchange Part Calculation

```
 [IntegrationEvent(true, true)]
    local procedure OnAfterUpdateHeaderInfo()
    begin
    end;
```
Proteced Var
        TotalAmount2: array[7] of Decimal;
        IndexNo: Integer;
```
 local procedure UpdateHeaderInfo(IndexNo: Integer; var VATAmountLine: Record "VAT Amount Line")
    var
        CurrExchRate: Record "Currency Exchange Rate";
        UseDate: Date;
begin
        TotalServLine[IndexNo]."Inv. Discount Amount" := VATAmountLine.GetTotalInvDiscAmount;
        TotalAmount1[IndexNo] :=
          TotalServLine[IndexNo]."Line Amount" - TotalServLine[IndexNo]."Inv. Discount Amount";
        VATAmount[IndexNo] := VATAmountLine.GetTotalVATAmount;
        if "Prices Including VAT" then begin
            TotalAmount1[IndexNo] := VATAmountLine.GetTotalAmountInclVAT;
            TotalAmount2[IndexNo] := TotalAmount1[IndexNo] - VATAmount[IndexNo];
            TotalServLine[IndexNo]."Line Amount" :=
              TotalAmount1[IndexNo] + TotalServLine[IndexNo]."Inv. Discount Amount";
        end else
            TotalAmount2[IndexNo] := TotalAmount1[IndexNo] + VATAmount[IndexNo];
**OnAfterCalcTotalAmount2()**
        if "Prices Including VAT" then
            TotalServLineLCY[IndexNo].Amount := TotalAmount2[IndexNo]
        else
```

**Comment by StanPesotskiy** [comment]
1. Please always put the full detailed signature of the requested events and the parameters passed in the call.
2. GlobalVarAccess was deprecated in 16.x, there is concept of protected var instead. You can list here the global vars that have to be protected and accessible from extensions.

**Comment by SWE-Tina** [comment]
1. Done :)
2. Protected vars not needed, wenn Sender is included. I changed it and removed parameter.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
