### ISSUE TITLE
[Event Request] Page "Service Order Statistic" "OnVATLinesDrillDownOnBeforeRun"

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11777]
```
 [IntegrationEvent(true, false)]
    local procedure OnVATLinesDrillDownOnBeforeRun()
    begin
    end;
```
Placement in Code:
```
  Clear(VATLinesForm);
    VATLinesForm.SetTempVATAmountLine(VATLinesToDrillDown);
    VATLinesForm.InitGlobals(
      "Currency Code",AllowVATDifference,AllowVATDifference and ThisTabAllowsVATEditing,
      "Prices Including VAT",AllowInvDisc,"VAT Base Discount %");
**OnVATLinesDrillDownOnBeforeRun**
    VATLinesForm.RunModal;
```

**Comment by StanPesotskiy** [comment]
What is the point in the event without parameters?

**Comment by SWE-Tina** [comment]
Protected var would be needed, pardon too many statistics pages and requests that evening..

Protected var needed as we call another procedure before running that page:
- VATLinesForm: Page "VAT Amount Lines";

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
