### ISSUE TITLE
fieldgroup request: "Customer Bank Account", "Vendor Bank Account"

### ISSUE THREAD

**Issue by Katarina-BS** [microsoft/ALAppExtensions#11778]
Please add fieldgroup DropDown to tables "Customer Bank Account" and "Vendor Bank Account" so we can extend it.
Gest regards,
Katarina

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
