### ISSUE TITLE
[Event Request] Page "Service Order Statistic" "OnBeforeCalcTotalAmount"

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11774]
Exchange Part Calculation...
```
   [IntegrationEvent(true, true)]
    local procedure OnBeforeCalcTotalAmount(var TempServLine: Record "Service Line" temporary; i: Integer)
    begin
    end;

```

Placement in Code:
```

            AdjProfitLCY[i] := TotalServLineLCY[i].Amount - TotalAdjCostLCY[i];

            if TotalServLineLCY[i].Amount <> 0 then
                AdjProfitPct[i] := Round(100 * AdjProfitLCY[i] / TotalServLineLCY[i].Amount, 0.1);

**OnBeforeCalcTotalAmount(TempServLine, i)**

            if "Prices Including VAT" then begin
                TotalAmount2[i] := TotalServLine[i].Amount;
                TotalAmount1[i] := TotalAmount2[i] + VATAmount[i];
                TotalServLine[i]."Line Amount" := TotalAmount1[i] + TotalServLine[i]."Inv. Discount Amount";
            end else begin
                TotalAmount1[i] := TotalServLine[i].Amount;
                TotalAmount2[i] := TotalServLine[i]."Amount Including VAT";
            end;
```

**Comment by StanPesotskiy** [comment]
GlobalVarAccess was deprecated in 16.x, there is concept of protected var instead. You can list here the global vars that have to be protected and accessible from extensions.
Would OnBeforeCalcTotalAmount makes sense without GlobalVarAccess?

**Comment by StanPesotskiy** [comment]
variable TotalServLine  does not exist in page 402 "Sales Order Statistics"

**Comment by SWE-Tina** [comment]
Pardon, it's Page Service Order Statistics; I'll immediately correct the headline. 

Protected Var needed: 
- i: Integer;

**Comment by StanPesotskiy** [comment]
lease always put the full detailed signature of the requested events and the parameters passed in the call. 
You provided the signature, but you put '**OnBeforeCalcTotalAmount**' without parameters as a call definition.

Another point, if we add protected variables maybe we don't need to pass them as parameters to the event that includes sender?

Please go through your requests and correct this.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
