### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnAfterUpdateItemCrossRef in UpdateItemReference()

### ISSUE THREAD

**Issue by bpiechowicz** [microsoft/ALAppExtensions#11779]
Hi. 
I would like to be able to control the changes to Purchase Line (e.g. to skip item description update in UpdateItemReference on 'Unit of Measure' update). Please add the below event:

**Table 39, Purchase Line,**
**LOCAL UpdateItemReference()**
UpdateItemCrossRef;
IF Type <> Type::Item THEN
  EXIT;
IF "Cross-Reference No." = '' THEN
  SetVendorItemNo
ELSE
  VALIDATE("Vendor Item No.","Cross-Reference No.");
**OnAfterUpdateItemCrossRef(xRec, Rec);**

**Requested publisher:**
[IntegrationEvent] OnAfterUpdateItemCrossRef(xPurchaseLine : Record "Purchase Line";VAR PurchaseLine : Record "Purchase Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
