### ISSUE TITLE
[Protection Level] Page "Sales Credit Memo Statistics" protected vars needed

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#11771]
Please make 
- SalesCrMemoLine
- AmountInclVAT
to protected vars (need to have to right calculation for and due exchange parts amounts)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
