### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnBeforeCreateSalesLine

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11784]
Hello. In table 36 Sales Header, in the procedure CreateSalesLine, I would like to add my own code instead of the standard one, thanks to the event publisher OnBeforeCreateSalesLine. To do so, I need two more parameters : Rec and SalesLine. Like this :

    local procedure CreateSalesLine(var TempSalesLine: Record "Sales Line" temporary)
    var
        IsHandled: Boolean;
    begin
        OnBeforeCreateSalesLine(Rec, SalesLine, TempSalesLine, IsHandled);
        if IsHandled then
            exit;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateSalesLine(var SalesHeader : record "Sales Header" ; var SalesLine: Record "Sales Line" ; var TempSalesLine: Record "Sales Line" temporary; var IsHandled: Boolean)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by dannoe** [comment]
Immediately after these lines an ```SalesLine.Init()``` is called. How do you plan to use "SalesLine"?

**Comment by Magicrevette** [comment]
You're right. I don't need "SalesLine" parameter.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
