### ISSUE TITLE
TestBlocked in Table 167 incomplete

### ISSUE THREAD

**Issue by alexlang24** [Microsoft/ALAppExtensions#1178]
In function [External] TestBlocked() the field Blocked is checked on option value "empty":

IF Blocked = Blocked::" " THEN
  EXIT;
ERROR(TestBlockedErr,TABLECAPTION,"No.",Blocked);

I am missing the difference between Blocked::All and Blocked::Posting.

// possible solution
[External] TestBlocked(CheckValue BOOLEAN)
IF CheckValue THEN BEGIN
  IF (Blocked = Blocked::" ") OR (Blocked = Blocked::Posting) THEN
    EXIT;
END ELSE
  IF Blocked = Blocked::" " THEN
    EXIT;
ERROR(TestBlockedErr,TABLECAPTION,"No.",Blocked);

Blocked::Posting means, it is not allowed to post anything related to this job but entering the job no. in e.g. job time journal or sales documents is allowed.

**Comment by JesperSchulz** [comment]
Thanks for sharing your idea with us. We're always looking for better ways to do things. However, this isn't the right place to share it. You'll have better luck getting it implemented and noticed by other partners if you post it to the following resources:

- For functional improvements, go to [Business Central - Ideas](http://aka.ms/bcideas)
- For feature suggestions for the AL compiler and developer tools, visit [Github.com/Microsoft/AL](https://github.com/Microsoft/AL/issues)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
