### ISSUE TITLE
[extensibility-enhancement] Allow to extend the OnLookup trigger in tables

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#11785]
At the moment we can only extend the Validate trigger in Extension by using the OnAfterValidate trigger. Could you make it possible to extend the Lookup trigger from tables? The only way to create lookups now is by using the TableRelation for Fields from the BC App.

I dont want to add an OnAfterLookup event, I want to add a possibility to add a real OnLookup Event. 

So maybe you could make it possible to do something like this. And maybe add an IsHandled so we know if another Extension handled it already.

````
Modify("Job No")
{
    Trigger OnLookup(IsHandled: boolean)
    begin
       if IsHandled then 
         exit;

       //Building my own Lookup
    end;
}

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL application extensibility. Please reach out to the relevant support channels:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
