### ISSUE TITLE
Request for option to enum data type conversion of "Cross-Reference Type" Table 5717 "Item Cross Reference" 

### ISSUE THREAD

**Issue by mohit0989** [microsoft/ALAppExtensions#11783]
Request for creation of enum data type for field "Cross-Reference Type" Table 5717 "Item Cross Reference" which is currently an option data
![image](https://user-images.githubusercontent.com/47515024/112191488-142ee780-8c2c-11eb-80f5-6755b11b754f.png)

**Comment by dannoe** [comment]
This table is replaced by Item Reference in 17.0 and will be obsoleted in 18.0.

**Comment by AlexanderYakunin** [comment]
Item Cross Reference have been replaced by Item Reference to support longer Vendor Item No./Item Reference No. up to 50 chars. There is already an enum "Item Reference Type". You can enable Item Reference i Feature management, it will be default feature from 19.0. I'd recommend to use new feature for your extensions.
