### ISSUE TITLE
How to fix 'Permission denied" exception 

### ISSUE THREAD

**Issue by himanshu2599** [microsoft/ALAppExtensions#11789]
https://github.com/microsoft/ALAppExtensions/blob/84835b80463f5445876badc37dc2c06781ef1c49/Modules/System/OAuthClientAddIn/js/OAuthIntegration.js#L120

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
