### ISSUE TITLE
[Event Request] Page 402 "Sales Order Statistics"- Function RefreshOnAfterGetRecord: OnRefreshOnAfterGetRecordOnAfterCalcTotalAmount

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#11786]
Hello, would it be possible to get an event OnRefreshOnAfterGetRecordOnAfterCalcTotalAmount (parameters as var) in Page 402 Function RefreshOnAfterGetRecord, like this:
           .....
           SalesPost.SumSalesLinesTemp(
              Rec, TempSalesLine, i - 1, TotalSalesLine[i], TotalSalesLineLCY[i],
              VATAmount[i], VATAmountText[i], ProfitLCY[i], ProfitPct[i], TotalAdjCostLCY[i], false);

            if i = 3 then
                TotalAdjCostLCY[i] := TotalSalesLineLCY[i]."Unit Cost (LCY)";

            AdjProfitLCY[i] := TotalSalesLineLCY[i].Amount - TotalAdjCostLCY[i];
            if TotalSalesLineLCY[i].Amount <> 0 then
                AdjProfitPct[i] := Round(AdjProfitLCY[i] / TotalSalesLineLCY[i].Amount * 100, 0.1);

            if "Prices Including VAT" then begin
                TotalAmount2[i] := TotalSalesLine[i].Amount;
                TotalAmount1[i] := TotalAmount2[i] + VATAmount[i];
                TotalSalesLine[i]."Line Amount" := TotalAmount1[i] + TotalSalesLine[i]."Inv. Discount Amount";
            end else begin
                TotalAmount1[i] := TotalSalesLine[i].Amount;
                TotalAmount2[i] := TotalSalesLine[i]."Amount Including VAT";
            end;
            **OnRefreshOnAfterGetRecordOnAfterCalcTotalAmount(Rec, TempSalesLine, TotalAmount2[i], TotalAmount1[i]);**
        end;
        ......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
