### ISSUE TITLE
[Event Request] Page 402 "Sales Order Statistics"- Function UpdateHeaderInfo: OnUpdateHeaderInfoOnBeforeAmount 

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#11787]
Hello, would it be possible to get an event OnUpdateHeaderInfoOnBeforeAmount (parameters as var) in Page 402 Function UpdateHeaderInfo:
       ....
       if "Prices Including VAT" then begin
            TotalAmount1[IndexNo] := VATAmountLine.GetTotalAmountInclVAT;
            TotalAmount2[IndexNo] := TotalAmount1[IndexNo] - VATAmount[IndexNo];
            TotalSalesLine[IndexNo]."Line Amount" :=
              TotalAmount1[IndexNo] + TotalSalesLine[IndexNo]."Inv. Discount Amount";
        end else
            TotalAmount2[IndexNo] := TotalAmount1[IndexNo] + VATAmount[IndexNo];

        **OnUpdateHeaderInfoOnBeforeAmount(Rec, TotalAmount1[IndexNo], TotalAmount2[IndexNo], TotalSalesLine[IndexNo]);**

        if "Prices Including VAT" then
            TotalSalesLineLCY[IndexNo].Amount := TotalAmount2[IndexNo]
        else
            TotalSalesLineLCY[IndexNo].Amount := TotalAmount1[IndexNo];
        if "Currency Code" <> '' then
            if "Posting Date" = 0D then
                UseDate := WorkDate
            else
                UseDate := "Posting Date";

        TotalSalesLineLCY[IndexNo].Amount :=
          CurrExchRate.ExchangeAmtFCYToLCY(
            UseDate, "Currency Code", TotalSalesLineLCY[IndexNo].Amount, "Currency Factor");
        ....

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
