### ISSUE TITLE
[Protection Level] Page 21 "Customer Card" protected vars needed

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#11788]
Hi, would it be possible to get these variables protected in Page 21 (**Customer Card**):

- OverduePaymentsMsg: Label 'Overdue Payments';
- PostedInvoicesMsg: Label 'Posted Invoices (%1)', Comment = 'Invoices (5)';
- NoPostedInvoices: Integer;
- CreditMemosMsg: Label 'Posted Credit Memos (%1)', Comment = 'Credit Memos (3)';
- NoPostedCrMemos: Integer;
- OutstandingInvoicesMsg: Label 'Ongoing Invoices (%1)', Comment = 'Ongoing Invoices (4)';
- NoOutstandingInvoices: Integer;
- OutstandingCrMemosMsg: Label 'Ongoing Credit Memos (%1)', Comment = 'Ongoing Credit Memos (4)';
- NoOutstandingCrMemos: Integer;
- IsOfficeAddin: Boolean;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
