### ISSUE TITLE
[Event Request] Table 5050 Contact - OnBeforeIsUpdateNeeded

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#11780]
Hi, would it be possible to modify the **OnBeforeIsUpdateNeeded** event in table 5050 (**Contact**) by adding the **var** keyword to the **Contact** parameter, like this:
```AL
    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsUpdateNeeded(var Contact: Record Contact; xContact: Record Contact; var UpdateNeeded: Boolean)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
