### ISSUE TITLE
request for fieldgroup - table 14 Location - DropDown

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#11797]
Please add the `DropDown` fieldgroup to this table so that we can add fields to it (or, better yet, make it possible to declare _new_ fieldgroups in extensions!...)

![image](https://user-images.githubusercontent.com/63455896/112470983-3a0ad800-8d63-11eb-8c01-a6995829feab.png)

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
