### ISSUE TITLE
[Event Request] CU6620 "Copy Document Mgt." - procedure CopyPurchLinesToBuffer()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#11796]
```
------- ADD PARAMETER : FromPurchLine ---------

OnAfterCopyPurchLinesToBufferFields(TempPurchLineBuf, FromPurchLine2, FromPurchLine);

[IntegrationEvent(false, false)]
local procedure OnAfterCopyPurchLinesToBufferFields(var TempPurchaseLine: Record "Purchase Line" temporary; FromPurchaseLine2: Record "Purchase Line"; FromPurchaseLine: Record "Purchase Line")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by E80Yc9Aesf8Y7l** [comment]
Hi, where is the event in the BC180- CU2 when the request is 3 month old?

**Comment by JesperSchulz** [comment]
I actually can't see that this change was made, when I look at the issue. I'll ping the developer and ask what's up and down here. If this change somehow was lost, we're going to get this done asap.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
