### ISSUE TITLE
[Event Request] CU6620 "Copy Document Mgt." - procedure CopyPurchLineExtText() 

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#11795]
------- ADD PARAMETER : RecalculateLines AND CopyExtText ---------

IsHandled := false;
OnBeforeCopyPurchLineExtText(ToPurchHeader, ToPurchLine, FromPurchHeader, FromPurchLine, DocLineNo, NextLineNo, IsHandled, RecalculateLines , CopyExtText);
if IsHandled then
    exit;

[IntegrationEvent(false, false)]
local procedure OnBeforeCopyPurchLineExtText(ToPurchHeader: Record "Purchase Header"; var ToPurchLine: Record "Purchase Line"; FromPurchHeader: Record "Purchase Header"; FromPurchLine: Record "Purchase Line"; DocLineNo: Integer; var NextLineNo: Integer; var IsHandled: Boolean; RecalculateLines: Boolean; CopyExtText: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
