### ISSUE TITLE
[Traduction FR] Problem

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#11799]
On the FR version of the Business Central, some translations are not correct, can I request the corrections here ?

"En suspens" ->"En attente"
"Commande cadre" -> "Commande ouverte"
"Correct" -> "Correction"

Microsoft Dynamics 365 Business Central 2020 Release Wave 2 -> version 17.5

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
