### ISSUE TITLE
[Event Request] codeunit 5763 "Whse.-Post Shipment" GetSourceDocument procedure

### ISSUE THREAD

**Issue by CentralPrograms** [microsoft/ALAppExtensions#11798]
Please add a else OnElseGetSourceDocument(SourceHeader); to the case statement in the GetSourceDocument procedure.   I have attached the suggested code change.
[Change.txt](https://github.com/microsoft/ALAppExtensions/files/6205044/Change.txt)

**Comment by CentralPrograms** [comment]
It turns out this is not needed.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
