### ISSUE TITLE
[Event Request] Codeunit 5760 "Whse.-Post Receipt" Function PostSourceDocument - OnPostSourceDocumentOnAfterPostSalesHeader(SalesHeader);

### ISSUE THREAD

**Issue by amr-wafa** [microsoft/ALAppExtensions#11790]
Hi,
Is it possible to add "OnPostSourceDocumentOnAfterPostSalesHeader(SalesHeader);" in Codeunit 5760 in "PostSourceDocument" Function? similar to the event published for PurchaseHeader : OnPostSourceDocumentOnAfterPostPurchaseHeader(PurchHeader);

`begin
     ...

                        PurchPost.SetWhseRcptHeader(WhseRcptHeader);
                        case WhseSetup."Receipt Posting Policy" of
                            WhseSetup."Receipt Posting Policy"::"Posting errors are not processed":
                                PostPurchErrorsNotProcessed(PurchPost);
                            WhseSetup."Receipt Posting Policy"::"Stop and show the first posting error":
                                begin
                                    PurchPost.Run(PurchHeader);
                                    CounterSourceDocOK := CounterSourceDocOK + 1;
                                end;
                        end;
                        OnPostSourceDocumentOnAfterPostPurchaseHeader(PurchHeader);
                        Clear(PurchPost);
                    end;
                DATABASE::"Sales Line": // Return Order
                    begin
                        if "Source Document" = "Source Document"::"Sales Order" then
                            SalesHeader.Ship := true
                        else
                            SalesHeader.Receive := true;
                        SalesHeader.Invoice := false;

                        SalesPost.SetWhseRcptHeader(WhseRcptHeader);
                        case WhseSetup."Receipt Posting Policy" of
                            WhseSetup."Receipt Posting Policy"::"Posting errors are not processed":
                                begin
                                    if SalesPost.Run(SalesHeader) then
                                        CounterSourceDocOK := CounterSourceDocOK + 1;
                                end;
                            WhseSetup."Receipt Posting Policy"::"Stop and show the first posting error":
                                begin
                                    SalesPost.Run(SalesHeader);
                                    CounterSourceDocOK := CounterSourceDocOK + 1;
                                end;
                        end;
                        **OnPostSourceDocumentOnAfterPostSalesHeader(SalesHeader);** //Here
                        Clear(SalesPost);
                    end;
                DATABASE::"Transfer Line":
                    begin
                        if HideValidationDialog then
                            TransferPostReceipt.SetHideValidationDialog(HideValidationDialog);
                        TransferPostReceipt.SetWhseRcptHeader(WhseRcptHeader);
                        case WhseSetup."Receipt Posting Policy" of
                            WhseSetup."Receipt Posting Policy"::"Posting errors are not processed":
                                begin
                                    if TransferPostReceipt.Run(TransHeader) then
                                        CounterSourceDocOK := CounterSourceDocOK + 1;
                                end;
                            WhseSetup."Receipt Posting Policy"::"Stop and show the first posting error":
                                begin
                                    TransferPostReceipt.Run(TransHeader);
                                    CounterSourceDocOK := CounterSourceDocOK + 1;
                                end;
                        end;
                        Clear(TransferPostReceipt);
                    end;
                else
                    OnPostSourceDocument(WhseRcptHeader, WhseRcptLine);
            end;
        end;`
Here is the Integration Event:

`[IntegrationEvent(false, false)]
    local procedure OnPostSourceDocumentOnAfterPostSalesHeader(SalesHeader: record "Sales Header")
    begin
    end;`

Thanks alot,
Amr.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
