### ISSUE TITLE
[Procedure Request] Codeunit 5763 "Whse.-Post Shipment" -GetCounterSourceDocTotal,GetCounterSourceDocOK

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#11791]
Hi, would it be possible to get a procedure **GetCounterSourceDocTotal** and **GetCounterSourceDocOK** in codeunit 5763 (**Whse.-Post Shipment**), like this:

```
procedure GetCounterSourceDocTotal(): Integer;
begin
    exit(CounterSourceDocTotal);
end;

procedure GetCounterSourceDocOK(): Integer;
begin
    exit(CounterSourceDocOK);
end;
```

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
