### ISSUE TITLE
[Event Request] T18 Customer - procedure IsContactUpdateNeeded()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#11803]
```
------- ADD PARAMETER : ForceUpdateContact---------

OnBeforeIsContactUpdateNeeded(Rec, xRec, UpdateNeeded, ForceUpdateContact);

[IntegrationEvent(false, false)]
local procedure OnBeforeIsContactUpdateNeeded(Customer: Record Customer; xCustomer: Record Customer; var UpdateNeeded: Boolean; ForceUpdateContact : Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
