### ISSUE TITLE
[Event Request] codeunit 5760 "Whse.-Post Receipt" : GetSourceDocument procedure

### ISSUE THREAD

**Issue by CentralPrograms** [microsoft/ALAppExtensions#11800]
Please add a else OnElseGetSourceDocument(Source Header); to the Case statement.  I have attached an example of the change.
[Change.txt](https://github.com/microsoft/ALAppExtensions/files/6205096/Change.txt)

**Comment by CentralPrograms** [comment]
It turns out this is not needed.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
