### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnCheckCreditMaxBeforeInsertOnBeforeSalesHeaderCheck

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11811]
Hello. In table 36 Sales Header, in the procedure CheckCreditMaxBeforeInsert, I would like to add a test before calling the procedure  CustCheckCreditLimit.SalesHeaderCheck(). To do so, I need an IsHandled flag and an event subscriber. Like this :

    procedure CheckCreditMaxBeforeInsert()
    var
         ...
    begin
        IsHandled := false;
        OnBeforeCheckCreditMaxBeforeInsert(Rec, IsHandled, HideCreditCheckDialogue);
        if IsHandled then
            exit;

        if HideCreditCheckDialogue then
            exit;

        if (GetFilterCustNo <> '') or ("Sell-to Customer No." <> '') then begin

            ...

            IsHandled := false;
            OnCheckCreditMaxBeforeInsertOnBeforeSalesHeaderCheck(Rec, IsHandled);
            if not IsHandled then
                CustCheckCreditLimit.SalesHeaderCheck(SalesHeader);

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnCheckCreditMaxBeforeInsertOnBeforeSalesHeaderCheck(var SalesHeader: Record "Sales Header"; var IsHandled: boolean)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by StanPesotskiy** [comment]
You can use existing event OnBeforeCheckCreditMaxBeforeInsert

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
