### ISSUE TITLE
Table 1304 "Sales Price and Line Disc Buff" - InsertTempCampaignFromSegmentLines

### ISSUE THREAD

**Issue by criorza** [microsoft/ALAppExtensions#11813]
From BC160 CU10 (21502) to BC160 CU11 ( 22526), the parameters of this procedure have been changed.

CU 7
`local procedure InsertTempCampaignFromSegmentLines(var TempCampaign: Record Campaign temporary; SegmentLine: Record "Segment Line")`

CU10
`local procedure InsertTempCampaignFromSegmentLines(var TempCampaign: Record Campaign temporary; _**var**_ SegmentLine: Record "Segment Line")`
    
CU11
`local procedure InsertTempCampaignFromSegmentLines(var TempCampaign: Record Campaign temporary; SegmentLine: Record "Segment Line")`
    
In cumative 7 we detected a performance issue in customer card and customer list navigation. This issue we saw fixed in CU10 but when instaling CU11 this change has been lost. If the Segment Line parameter is not _### "var"_, for each contact of the company contact customer, all the segment line records are read without any filter.
 
Please, could you confirm us that in next cumulative will be fixed again?

Thanks in advance for your help.
Best Regards.

**Comment by AlexanderYakunin** [comment]
I can see this fix in 17.x only. Last change for 16.x for this procedure parameter list was made in May 2019. Please confirm you need this to be merged to 16.x too.

**Comment by criorza** [comment]
It’s strange. I can't see the fix in W1 but in ES cumulative 10 is fixed…

Yes please we need it in 16.

Thanks!!

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 16.
