### ISSUE TITLE
[Extensibility enhancements] Locations API page (`table 14 Location`) and location code (`table 37 "Sales Line"`)

### ISSUE THREAD

**Issue by kyrylkov** [microsoft/ALAppExtensions#11818]
- Expose `location` (`table 14 Location`) as a separate API page
- Add location code (`field(7; "Location Code"; Code[10])` of `table 37 "Sales Line"`) to the following existing API pages:
  - PurchReceiptLines.Page.al
  - PurchaseInvoiceLines.Page.al
  - PurchaseOrderLines.Page.al
  - SalesCreditMemLines.Page.al
  - SalesInvoiceLines.Page.al
  - SalesOrderLines.Page.al
  - SalesQuoteLines.Page.al
  - SalesShipmentLines.Page.al

https://docs.microsoft.com/en-us/learn/modules/intro-dynamics-365-business-central/4-supply-chain#locations

**Comment by AlexanderYakunin** [comment]
Please explain what is location resource type? And what is "expose locations" in pages - location code field is already available in these pages?

**Comment by kyrylkov** [comment]
There is a separate location table (`SourceTable = "Location"`) which is currently not exposed via APIV2 at all.  

Also each sales line table (i.e. `SourceTable = "Sales Invoice Line"`) has `Location Code` record, which is not exposed via APIV2 also. 

This is basic out-of-the-box functionality and the absence of locations in APIV2 makes it unusable for pretty much all inventory workflows.

**Comment by kyrylkov** [comment]
@AlexanderYakunin Could we get any feedback on this?   Will this be implemented?

**Comment by onbuyuka** [comment]
@kyrylkov Hi, yes this is being implemented and location endpoint and locationId field on documents in API v2.0 will be included in the upcoming minor releases.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by kyrylkov** [comment]
@JesperSchulz  It's OK if you don't answer, but AFAIK major releases are semiannual, correct?  What about minor ones?

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Comment by kyrylkov** [comment]
@JesperSchulz Thanks!  How often are these updates on average?  One per month, per quarter, etc.

**Comment by JesperSchulz** [comment]
This will ship with 18.1, beginning of April :-)
