### ISSUE TITLE
Page 96 Sales Cr. Memo Subform - OnBeforeInsertExtendedText in InsertExtendedText procedure

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#11819]
page 96 Sales Cr. Memo Subform. OnBeforeInsertExtendedText event within InsertExtendedText procedure.  Could you please add xREC Parameter?  Thanks.   
![image](https://user-images.githubusercontent.com/49729094/112874577-1a402080-9091-11eb-86c9-d51fa7e1aaa1.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
