### ISSUE TITLE
On Insert Phys Inventory Order Recording Line

### ISSUE THREAD

**Issue by pranav4186** [microsoft/ALAppExtensions#11820]
Hello,

We have a requirement to break Physical Inventory Recording Lines by Lot No. for that we are subscribing to OnAfterPhysInvtRecordLineInsert event on InsertRecordingLine function of Report - 5881 - Make Phys. Invt. Recording.
Since we are creating new lines, could you please change below code in that function to increment NextLineNo based on Line No. of PhysInvtRecordLine? 
Current Code:
![image](https://user-images.githubusercontent.com/35543761/112916681-e7f4ea00-90b5-11eb-8237-dbf34d24b5c6.png)

Proposed Change:

            OnBeforePhysInvtRecordLineInsert(PhysInvtRecordLine, PhysInvtOrderLine);
            Insert;
            OnAfterPhysInvtRecordLineInsert(PhysInvtRecordLine, PhysInvtOrderLine);
            NextLineNo := PhysInvtRecordLine."Line No."+ 10000;

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
