### ISSUE TITLE
Add Parameter to OnIsIntegrationRecordChild

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#11821]
Current code:
![image](https://user-images.githubusercontent.com/35260264/112950783-f0433880-913a-11eb-81a3-85740855006d.png)

The change i want:
![image](https://user-images.githubusercontent.com/35260264/112950954-24b6f480-913b-11eb-9a99-95a98f15a541.png)

Reason for the change:
I want to be able to synchronize sales line, and add them to the CRM Integration Record.
Our customer are synchronizing Sales Quotes(BC) to Opportunity(CRM), if i dont have that event i will have to delete and synch all sales line each time there is a change in the quote.

Thank you :)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
