### ISSUE TITLE
[Request-for-external] Codeunit 7307 - Whse.-Activity-Register - CheckWhseItemTrkgLine

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#11826]
Hi, would it be possible to change the procedure CheckWhseItemTrkgLine in codeunit 7307 from local to external ?
Thanks for your time

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
