### ISSUE TITLE
API v2.0 Contact Endpoint not available in BC 17.3

### ISSUE THREAD

**Issue by MichaelSchauer98** [microsoft/ALAppExtensions#11823]
I'm currently testing the API v2.0 on a BC 17.3 onprem environment and the contact endpoint is not available although it should be according to the documentation. https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v2.0/resources/dynamics_contact.
Json Response when invoking the metadata of the API v2.0
[APIv2_0_Response.txt](https://github.com/microsoft/ALAppExtensions/files/6227641/APIv2_0_Response.txt)

When trying to invoke the contact endpoint by companies(companyid)/contacts, I received the response that the resource contact is not available:
![26-03-_2021_08-52-36](https://user-images.githubusercontent.com/72799416/112959607-e540d600-9143-11eb-892a-fbb94596a2f7.png)

I also opened the table 2000000193 in the web client to check if the contact Api is published, but its not listed here as well.
![26-03-_2021_08-17-44](https://user-images.githubusercontent.com/72799416/112960088-60a28780-9144-11eb-9de4-daac3682697d.png)

I'm experiencing the same issue on a BC sandbox environment on version 17.5.

Is the Contact API not available in API v2.0 yet? 

Thank you

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
