### ISSUE TITLE
[Event Request] Table 5405 "Production Order" - OnBeforeShowErrorOnRename

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11829]
Hello. In table 5405 Production Order, in the procedure ShowErrorOnRename, I would like to use the event publisher OnBeforeShowErrorOnRename and do a test in it. To do so, I need Rec as a parameter. Like this :

    local procedure ShowErrorOnRename()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeShowErrorOnRename(IsHandled, Rec);
        if IsHandled then
            exit;

        Error(Text001, TableCaption);
    end;

With this integration event : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowErrorOnRename(ProductionOrder: Record "Production Order" ; var IsHandled: Boolean)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by StanPesotskiy** [comment]
Already implemented
```
    local procedure ShowErrorOnRename()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeShowErrorOnRename(IsHandled, Rec);
        if IsHandled then
            exit;
```
