### ISSUE TITLE
[Event Request] Table 5621 "FA Journal Line" - OnAfterSetUpNewLine

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#11839]
Request a new event in function SetUpNewLine in table 5621 "FA Journal Line":

    procedure SetUpNewLine(LastFAJnlLine: Record "FA Journal Line")
    begin
        ...
        "Reason Code" := FAJnlBatch."Reason Code";
        "Posting No. Series" := FAJnlBatch."Posting No. Series";

        OnAfterSetUpNewLine(Rec, FAJnlTemplate, FAJnlBatch, LastFAJnlLine);    //NEW
    end;

    //NEW
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetUpNewLine(var FAJournalLine: Record "FA Journal Line"; FAJnlTemplate: Record "FA Journal Template"; FAJnlBatch: Record "FA Journal Batch"; LastFAJnlLine: Record "FA Journal Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
