### ISSUE TITLE
Unable to set up a web service access key

### ISSUE THREAD

**Issue by glachana** [microsoft/ALAppExtensions#11835]
I am unable to configure a web service key for one of my customers on a french Saas environment in version : 17.5.22499.22680
I have the following message:
![image](https://user-images.githubusercontent.com/55086553/113009236-0f13f000-9178-11eb-84b5-469a8af01581.png)

Here is the code that triggers the error:
![image](https://user-images.githubusercontent.com/55086553/113009266-13d8a400-9178-11eb-8065-cb210fe4579b.png)

I know that Web Service Access Keys will be removed on saas environements in the near future, but they should be operational until the release of Business Central 2022 release wave 1, right?

Thank you in advance for your help.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
