### ISSUE TITLE
parameter request - table 60 "Document Sending Profile" - TrySendToEMail() - OnBeforeTrySendToEmail() - var IsCustomer: Boolean

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#11834]
This function always calls `TrySendToEMailGroupedMultipleSelection()` with its argument `IsCustomer: Boolean` set to `true`.

This makes `TrySendToEMail` useless if we want to send to a **Vendor**, not a Customer. We can't even use its `OnBefore` event, set `Handled := true`, and copy and paste nearly all the code and just call `TrySendToEMailGroupedMultipleSelection()` differently... because that is a `local procedure`, and besides we don't have the `Sender` to assign as the standard implementation does.

Therefore, please asap give us the possibility of stating that for a given `ReportUsage`, `IsCustomer := false` so that we can send to vendors.

Please add `var IsCustomer: Boolean` to the event arguments of `OnBeforeTrySendToEMail()`, pass it to subscribers so that they can change it if needed, and pass the resulting value through to `TrySendToEMailGroupedMultipleSelection()` instead of always `true`.

Thanks!

updated publisher:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTrySendToEMail(ReportUsage: Integer; RecordVariant: Variant; DocumentNoFieldNo: Integer; DocName: Text[150]; CustomerFieldNo: Integer; ShowDialog: Boolean; var IsCustomer: Boolean; var Handled: Boolean)
    begin
    end;
```

updated caller:
```al
    procedure TrySendToEMail(ReportUsage: Integer; RecordVariant: Variant; DocumentNoFieldNo: Integer; DocName: Text[150]; CustomerFieldNo: Integer; ShowDialog: Boolean)
    var
        IsCustomer: Boolean; // NEW
        Handled: Boolean;
    begin
        IsCustomer := true; // NEW
        OnBeforeTrySendToEMail(ReportUsage, RecordVariant, DocumentNoFieldNo, DocName, CustomerFieldNo, ShowDialog, IsCustomer, Handled); // ADDED

        if Handled then
            exit;

        if ShowDialog then
            "E-Mail" := "E-Mail"::"Yes (Prompt for Settings)"
        else
            "E-Mail" := "E-Mail"::"Yes (Use Default Settings)";

        "E-Mail Attachment" := "E-Mail Attachment"::PDF;

        TrySendToEMailGroupedMultipleSelection(
            "Report Selection Usage".FromInteger(ReportUsage), RecordVariant, DocumentNoFieldNo, DocName, CustomerFieldNo, IsCustomer); // PASSED
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
