### ISSUE TITLE
[Event Request] Table 10121 "Bank Rec. Line" - OnAfterValidateShortcutDimCode

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#11838]
Request a new event in function ValidateShortcutDimCode in table 10121 "Bank Rec. Line":

    procedure ValidateShortcutDimCode(FieldNumber: Integer; var ShortcutDimCode: Code[20])
    begin
        DimMgt.ValidateShortcutDimValues(FieldNumber, ShortcutDimCode, "Dimension Set ID");

        OnAfterValidateShortcutDimCode(Rec, xRec, FieldNumber, ShortcutDimCode);   //NEW
    end;

    //NEW
    [IntegrationEvent(false, false)]
    local procedure OnAfterValidateShortcutDimCode(var BankRecLine: Record "Bank Rec. Line"; xBankRecLine: Record "Bank Rec. Line"; FieldNumber: Integer; var ShortcutDimCode: Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
