### ISSUE TITLE
[Event Request] Table 5405 "Production Order" - OnValidateDueDateOnAfterModify

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11837]
Hello. In table 5405 Production Order, in the field 24 "Due Date", in the trigger OnValidate, I need an event publisher at the end of the else statement to add my own code. Like this :

        field(24; "Due Date"; Date)
        {
            Caption = 'Due Date';

            trigger OnValidate()
            begin
                       
                        ...

                        end;
                        AdjustStartEndingDate;
                        Modify;
                    end;
                    OnValidateDueDateOnAfterModify(Rec);
                end;
            end;
        }

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnValidateDueDateOnAfterModify(ProductionOrder: Record "Production Order")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
