### ISSUE TITLE
[Event Change] Codeunit 81 - OnAfterConfirmPost

### ISSUE THREAD

**Issue by mbertelsmann** [Microsoft/ALAppExtensions#1183]
Hi,

we need a change in an event in codeunit 81 Sales-Post (Yes/No).
Please add the call by reference VAR property to Sales Header.

Changed publisher function:
```
    [Integration]
+   // >> START  
+   LOCAL PROCEDURE OnAfterConfirmPost@5020300(VAR SalesHeader@5020300 : Record 36);
+   // << END     
    BEGIN
    END;
```

**Comment by AlexanderYakunin** [comment]
Please provide location of event in procedure code

**Comment by mbertelsmann** [comment]
The event is located in the "Code" function. Please note that we did not request a new event but requested a change in this already existing event:

![image](https://user-images.githubusercontent.com/47027562/53327550-4ef8b100-38e8-11e9-9670-7a2703cb20f6.png)

We'd like to ask for adding the "VAR" to the Sales Header parameter.

Current event publisher:
```
    [Integration]
    LOCAL PROCEDURE OnAfterConfirmPost@7(SalesHeader@1000 : Record 36);
    BEGIN
    END;
```
Event publisher after requested change:
```
    [Integration]
    LOCAL PROCEDURE OnAfterConfirmPost@7(VAR SalesHeader@1000 : Record 36);
    BEGIN
    END;
```
