### ISSUE TITLE
Remove OnPrem scope on MatchCBGStatement and SetHideMessages procedures in Codeunit 11000006 CBG Statement Reconciliation

### ISSUE THREAD

**Issue by Chielve** [microsoft/ALAppExtensions#11831]
Hello,

we want to use the MatchCBGStatement and the SetHideMessages procedures in Codeunit 11000006 CBG Statement Reconciliation in our app but the scope is set to OnPrem. Could the OnPrem scope be removed?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
