### ISSUE TITLE
[Event Request] Table 18 - Function CustBlockedErrorMessage: OnBeforeCustBlockedErrorMessage

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#11847]
Hello, would it be possible to get an event OnBeforeCustBlockedErrorMessage (with IsHandle) in Table 18 Function CustBlockedErrorMessage:

    procedure CustBlockedErrorMessage(Cust2: Record Customer; Transaction: Boolean)
    var
        "Action": Text[30];
        **"IsHandled ": Boolean;**
    begin
        **OnBeforeCustBlockedErrorMessage(Cust2, Transaction, IsHandled);
        IF IsHandled then
            exit;**
        if Transaction then
            Action := Text004
        else
            Action := Text005;
        Error(Text006, Action, Cust2."No.", Cust2.Blocked);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCustBlockedErrorMessage(Cust2: Record Customer; Transaction: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
