### ISSUE TITLE
Page : "Job Item Prices" is marked for removal. Obsoletestate Pending

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/ALAppExtensions#11848]
Hi,

we are not able to extend Page - "Job Item Prices", because it is marked for removal. In the page - "Job Item Prices" , ObsoleteState is updated as pending. 

I mean: we have an app that alters how prices are calculated, so the interfaces are great. But to do so, we add a few new fields to the "Job Item Prices". and the table - "Job Item Prices" is also marked as obsolete. Are there any new tables that we should be aware of?.

And when can we expect that ObsoleteState will be marked for Removal. so, that we will update our changes to our app.

![image](https://user-images.githubusercontent.com/28556102/113139618-fa515e00-9244-11eb-99a6-2d462049979c.png)
![image](https://user-images.githubusercontent.com/28556102/113139663-0b01d400-9245-11eb-8c2d-10c9a4e8f828.png)

**Comment by StanPesotskiy** [comment]
The new pricing feature will be enabled automatically with the release 20.0 in April 2022.
Now you can enable it manually in the page Feature Management.
The content of the table "Job Item Prices" will be copied to the table "Price List Line". 
See https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extending-best-price-calculations for more details.
