### ISSUE TITLE
[Event Request] Report 699 "Calculate Plan - Req. Wksh." - OnBeforeOnPreReport

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#11849]
Hi, would it be possible to get an **OnBeforeOnPreReport** event in report 699 (**Calculate Plan - Req. Wksh.**), like this:
```AL
    trigger OnPreReport()
    var
        ProductionForecastEntry: Record "Production Forecast Entry";
    begin
        OnBeforeOnPreReport(CurrTemplateName, CurrWorksheetName); // New Event
        Counter := 0;
        if FromDate = 0D then
            Error(Text002);
        if ToDate = 0D then
            Error(Text003);
        PeriodLength := ToDate - FromDate + 1;
        if PeriodLength <= 0 then
            Error(Text004);

        if (Item.GetFilter("Variant Filter") <> '') and
           (MfgSetup."Current Production Forecast" <> '')
        then begin
            ProductionForecastEntry.SetRange("Production Forecast Name", MfgSetup."Current Production Forecast");
            Item.CopyFilter("No.", ProductionForecastEntry."Item No.");
            if MfgSetup."Use Forecast on Locations" then
                Item.CopyFilter("Location Filter", ProductionForecastEntry."Location Code");
            if not ProductionForecastEntry.IsEmpty() then
                Error(Text005);
        end;

        ReqLine.SetRange("Worksheet Template Name", CurrTemplateName);
        ReqLine.SetRange("Journal Batch Name", CurrWorksheetName);

        Window.Open(
          Text006 +
          Text007);
    end;
```
```AL
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnPreReport(var TemplateName: Code[10]; var WorksheetName: Code[10])
    begin
    end;
```
_Note_: in view of introducing a new object type - reportextension (https://docs.microsoft.com/en-us/dynamics365-release-plan/2021wave1/smb/dynamics365-business-central/report-extensibility), this event can be replaced just by adding the **protected** keyword to **TemplateName**, **WorksheetName**, **ReqLine** variables. This approach will be also suitable for us.

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
