### ISSUE TITLE
[Event Request] Item Tracking Data Collection Codeunit 6501

### ISSUE THREAD

**Issue by dpodjasek** [microsoft/ALAppExtensions#11859]
Hello, we are creating an app that needs to be able to override the Serial No. code that limits the quantity to one.  We were happy to see that in nearly all places where this is done in the system, there is already an event providing an "IsHandled" variable to override the serial quantity checking.  There are a few places where this has not been provided though, and I will be making requests to add events for them.

Event Request:
Item Tracking Data Collection Codeunit 6501
Procedure AssistEditTrackingNo

This procedure has a few lines of code that, if a serial number is used, overrides the quantity assigned to one.  This is painful because the way we are using serials, they may have a larger quantity, and the user always has to override the quantity back to the proper number.  An event to override this behavior and not change the quantity to one is requested.

Thank you, 
David Podjasek

![image](https://user-images.githubusercontent.com/48566556/113240117-aa3cc080-9271-11eb-99a2-16d41b6c3a25.png)

**Comment by RomanZanizdra** [comment]
Hi @dpodjasek .
In the latest version the code looks like below, so there is a possibility to define NewQtyOnLine by yourself. Let me if if fits to you or not.
```
...
NewQtyOnLine := CalcNewQtyOnLine(TempTrackingSpecification, QtyOnLine, AdjustmentQty, QtyHandledOnLine);
...

    local procedure CalcNewQtyOnLine(var TempTrackingSpecification: Record "Tracking Specification" temporary; QtyOnLine: Decimal; AdjustmentQty: Decimal; QtyHandledOnLine: Decimal) NewQtyOnLine: Decimal
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalcNewQtyOnLine(TempTrackingSpecification, QtyOnLine, AdjustmentQty, QtyHandledOnLine, NewQtyOnLine, IsHandled);
        if IsHandled then
            exit(NewQtyOnLine);

        NewQtyOnLine := QtyOnLine + AdjustmentQty + QtyHandledOnLine;
        if TempTrackingSpecification."Serial No." <> '' then
            if Abs(NewQtyOnLine) > 1 then
                NewQtyOnLine := NewQtyOnLine / Abs(NewQtyOnLine); // Set to a signed value of 1.
    end;

```

**Comment by RomanZanizdra** [comment]
Hi @dpodjasek . Any update from your side?

**Comment by dpodjasek** [comment]
Sorry, missed the notification.  Yes, that looks like it will work perfectly!  

Is this new code currently released?  I haven't seen it yet.

Thanks!!

**Comment by AlexanderYakunin** [comment]
Check April release

**Comment by dpodjasek** [comment]
So, I have downloaded symbols and the latest it downloads is "Microsoft_Base Application_17.5.22499.24170.app".

This version still seems to have the original code.  Do I need to be on a preview version or something?  Thanks for any info you can provide, I'm afraid I'm new to this...

**Comment by AlexanderYakunin** [comment]
Latest version is 18.0 (2021 Wave 1), released on April 1st.
