### ISSUE TITLE
[Protection Level] Table 370 "Excel Buffer" - Protected vars needed

### ISSUE THREAD

**Issue by SteinleMossGaewers** [microsoft/ALAppExtensions#11851]
Hi, We would like to have access to the global variables :
CurrentRow, CurrentCol, XlWrkBkReader, XlWrkShtWriter, XlWrkBkWriter, XlWrkBks, XlApp, XlWrkBk, XlWrkSht, XlWrkShts, UseInfoSheet . 

Can you make those protected?

Many thanks.

**Comment by AlexanderYakunin** [comment]
Hello! Can you provide more information why you need it?

**Comment by SteinleMossGaewers** [comment]
Hi @AlexanderYakunin,

we would like to add Functions to the Excel Buffer that are not give in the Standard.
For example one function we would like to implement sets the Border of a cell, that functionality is possible in the dotnet variable but not given as a function in Table 370 "Excel Buffer". Therefore we need access to the aforementioned variables.

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot expose dotnet variables in events. If you can provide code you want to add, we can implement it as part of Excel Buffer table.
