### ISSUE TITLE
[Event Request] Table 83 "Item Journal Line" - OnAfterShowDimensions

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#11856]
Request a new event in function ShowDimensions in table 83 "Item Journal Line":

```
    procedure ShowDimensions()
    begin
        "Dimension Set ID" :=
          DimMgt.EditDimensionSet(
            "Dimension Set ID", StrSubstNo('%1 %2 %3', "Journal Template Name", "Journal Batch Name", "Line No."),
            "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");

        OnAfterShowDimensions(Rec);    //NEW
    end;

    //NEW
    [IntegrationEvent(false, false)]
    local procedure OnAfterShowDimensions(var ItemJournalLine: Record "Item Journal Line")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
