### ISSUE TITLE
[Event Request] Report 5607 "Fixed Asset - Projected Value" - OnAfterOpenPage

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#11855]
Hi, would it be possible to get an **OnAfterOpenPage** event in report 5607 (**Fixed Asset - Projected Value**), like this:
```AL
        trigger OnOpenPage()
        begin
            GetFASetup;
            OnAfterOpenPage(DeprBookCode, StartingDate, EndingDate); // New Event
        end;
```
```AL
    [IntegrationEvent(false, false)]
    local procedure OnAfterOpenPage(var DeprBookCode: Code[10]; var StartingDate: Date; var EndingDate: Date)
    begin
    end;
```
_Note_: in view of introducing a new object type - **reportextension** (https://docs.microsoft.com/en-us/dynamics365-release-plan/2021wave1/smb/dynamics365-business-central/report-extensibility), this event can be replaced just by adding the **protected** keyword to **DeprBookCode**, **StartingDate**, **EndingDate** variables. This approach will be also suitable for us.

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
