### ISSUE TITLE
Codeunit 7312 Create Pick - Procedure CreateAssemblyPickLine()----Event Request

### ISSUE THREAD

**Issue by pradeepmn91** [microsoft/ALAppExtensions#11854]
Procedure CreateAssemblyPickLine(AsmLine: Record "Assembly Line")
    var
        QtyToPickBase: Decimal;
        QtyToPick: Decimal;
    begin
        with AsmLine do begin
            TestField("Qty. per Unit of Measure");
            QtyToPickBase := CalcQtyToPickBase;
            QtyToPick := CalcQtyToPick;

           OnBeforeSetAssemblyLine(AsmLine , QtyToPickBase , QtyToPick );

            if QtyToPick > 0 then begin
                SetAssemblyLine(AsmLine, 1);
                SetTempWhseItemTrkgLine(
                  "Document No.", DATABASE::"Assembly Line", '', 0, "Line No.", "Location Code");
                CreateTempLine(
                  "Location Code", "No.", "Variant Code", "Unit of Measure Code", '', "Bin Code",
                  "Qty. per Unit of Measure", QtyToPick, QtyToPickBase);
            end;
        end;
    end;

 [IntegrationEvent(false, false)]
    local procedure OnBeforeSetAssemblyLine(var AsmLine : Record "Assembly Line"; var QtyToPickBase : Decimal ; var QtyToPick : Decimal )
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
