### ISSUE TITLE
[Event Request] Item Tracking Lines Page 6510

### ISSUE THREAD

**Issue by dpodjasek** [microsoft/ALAppExtensions#11858]
Hello, we are creating an app that needs to be able to override the Serial No. code that limits the quantity to one.  We were happy to see that in nearly all places where this is done in the system, there is already an event providing an "IsHandled" variable to override the serial quantity checking.  There are a few places where this has not been provided though, and I will be making requests to add events for them.

Event Request:
Item Tracking Lines Page 6510
Function TestTempSpecificationExists

This page function checks to ensure that no other record in the temporary recordset has the same serial number as the current record.  We would like to be able to enter multiple lines with the same serial number, but different lot numbers.  An event to override the default handling of this function is requested.

Thank you, 
David Podjasek

![image](https://user-images.githubusercontent.com/48566556/113239455-63020000-9270-11eb-804f-e0bb14bd7b5e.png)

**Comment by RomanZanizdra** [comment]
Hi @dpodjasek .
Please check the latest version. The code was changed/updated in the area and there are new events appeared. So let me know if fits for you or not.

**Comment by RomanZanizdra** [comment]
Hi @dpodjasek . Any update from your side?

**Comment by dpodjasek** [comment]
Sorry for the delay, looking into it... will respond after testing

**Comment by dpodjasek** [comment]
Ok, after some testing I can see what the issue is.  Using the OnTestTempSpecificationExistsOnAfterSetFilters event, I can override so that the lines are filtered by both serial and lot, which prevents the error when trying to define multiple lines with same serial but different lots.  However, during serial validate this code occurs on P6510:

![image](https://user-images.githubusercontent.com/48566556/113957715-5851e880-97e5-11eb-9730-8eb639ef8073.png)

This causes it to look at the other tracking lines with the same serial, and retrieve the first one.  It then passes back the lot numebr of that line, and fills it to the current line lot number.  This then causes TestTempSpecificationExists to run again, and this time it is looking for a match of both serial and lot, which it just created and erros.

So it would appear that what I really need is an event that lets me skip over the Serial validtion code on the page that calls

**Comment by RomanZanizdra** [comment]
@dpodjasek , just let me know where and what event you need in terms of new code. We will implement it.

**Comment by dpodjasek** [comment]
For clarity, I have created a new issue thread, with a simplified explanation of the new event I would like. (https://github.com/microsoft/ALAppExtensions/issues/11985)

This thread can now be closed.  

Thank you!
