### ISSUE TITLE
[Event Request] codeunit 5765 Whse.-Post Shipment + Print - Function Code

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11869]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5765 function Code, of course without the prefix DIN.

            if Find then
                if not HideDialog then begin
                    // DINNL <<
                    DINOnSetSelection(Selection, DINIsHandled);
                    if not DINIsHandled then
                        // DINNL >>
                    Selection := StrMenu(ShipInvoiceQst, 1);

local procedure DINOnSetSelection(var Selection: Integer; var IsHandled: Boolean)

**Comment by RomanZanizdra** [comment]
Hi @DirkGijsen .
I don't think you need one more event here. You can use the existing one. Setting HideDialog to true you will be able to skip show menu, you also will be able to set Selection and Invoice parameters there. Let me know if it fits for you.
`OnBeforeCode(WhseShptLine, HideDialog, Invoice, IsPosted, Selection);`

**Comment by DirkGijsen** [comment]
Hi Roman,

Thanks for your reply.
I agree on using the OnBeforeCode event.
It fits for our functionality.

Regards
Dirk


Van: RomanZanizdra ***@***.***>
Verzonden: maandag 5 april 2021 15:59
Aan: microsoft/ALAppExtensions ***@***.***>
CC: Dirk Gijsen ***@***.***>; Mention ***@***.***>
Onderwerp: [EXTERNAL] Re: [microsoft/ALAppExtensions] [Event Request] codeunit 5765 Whse.-Post Shipment + Print - Function Code (#11869)

EXTERNAL
________________________________


Hi @DirkGijsen<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDirkGijsen&data=04%7C01%7Cdirk.gijsen%40aptean.com%7C2a691464b7124c45c60708d8f83af62a%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637532279911331013%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IhGooSJosBtpHhcUJ%2FQFozYVfwE5PJWGVXmdeRgGjRE%3D&reserved=0> .
I don't think you need one more event here. You can use the existing one. Setting HideDialog to true you will be able to skip show menu, you also will be able to set Selection and Invoice parameters there. Let me know if it fits for you.
OnBeforeCode(WhseShptLine, HideDialog, Invoice, IsPosted, Selection);

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FALAppExtensions%2Fissues%2F11869%23issuecomment-813407069&data=04%7C01%7Cdirk.gijsen%40aptean.com%7C2a691464b7124c45c60708d8f83af62a%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637532279911341017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1ss8l2rqLsCvFixvAFdgT%2Bez9eiVOmObJigR%2Fvf5hhw%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKUUR3LRTERBLHK2QMIJJ7DTHG62BANCNFSM42G7C5HA&data=04%7C01%7Cdirk.gijsen%40aptean.com%7C2a691464b7124c45c60708d8f83af62a%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637532279911341017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vBa1FV4D9Lf%2Beua4DudzlK4N7rmNkDvOrroQyapww3U%3D&reserved=0>.

This message contains information that is confidential and/or may be privileged. If you are not the intended recipient, you are hereby notified that any use, dissemination, distribution or copy of this message and/or its attachments is strictly prohibited. If you have received this message in error, please advise the sender immediately by replying to this email and delete this message. We are committed to your privacy. For more information, please see our Privacy Policy at https://www.aptean.com/privacy-statement
