### ISSUE TITLE
[Event Request] codeunit 5764 Whse.-Post Shipment (Yes/No) - Function Code

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11868]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5764 function Code, of course without the prefix DIN.

            if Find then
                if not HideDialog then begin
                    // DINNL <<
                    DINOnSetSelection(Selection, DINIsHandled);
                    if not DINIsHandled then
                    // DINNL >>
                    Selection := StrMenu(ShipInvoiceQst, 1);

local procedure DINOnSetSelection(var Selection: Integer; var IsHandled: Boolean)

**Comment by RomanZanizdra** [comment]
Hi @DirkGijsen .
The question and suggestion is like here: https://github.com/microsoft/ALAppExtensions/issues/11869. Let me know your opinion.

**Comment by DirkGijsen** [comment]
Hi Roman,

Thanks for your reply.

This suggested event is not sufficient for us.
We mis the parameter Selection, perhaps you could add this ?
***@***.***D72AD1.E57A54D0]

Regards
Dirk


Van: RomanZanizdra ***@***.***>
Verzonden: maandag 5 april 2021 16:13
Aan: microsoft/ALAppExtensions ***@***.***>
CC: Dirk Gijsen ***@***.***>; Mention ***@***.***>
Onderwerp: [EXTERNAL] Re: [microsoft/ALAppExtensions] [Event Request] codeunit 5764 Whse.-Post Shipment (Yes/No) - Function Code (#11868)

EXTERNAL
________________________________


Hi @DirkGijsen<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDirkGijsen&data=04%7C01%7Cdirk.gijsen%40aptean.com%7C540fe0f3ea154477f90d08d8f83ce17e%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637532287666868661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wDdhbzJlLbamZzjtcb%2BByAoDtcBUkW%2BUXCW6W0kvDjo%3D&reserved=0> .
The question and suggestion is like here: #11869<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FALAppExtensions%2Fissues%2F11869&data=04%7C01%7Cdirk.gijsen%40aptean.com%7C540fe0f3ea154477f90d08d8f83ce17e%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637532287666868661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=B3U8SmeRFrXoe9Q0tvA%2F9k5feXRfeMDYUhYmi3jfef0%3D&reserved=0>. Let me know your opinion.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FALAppExtensions%2Fissues%2F11868%23issuecomment-813413629&data=04%7C01%7Cdirk.gijsen%40aptean.com%7C540fe0f3ea154477f90d08d8f83ce17e%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637532287666878656%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=F4vl6ozx9Um8r57DxUwVei4ACXmmyiAr9yHZe1YK3gs%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKUUR3LSL3SQOPGAQBQQVBLTHHANPANCNFSM42G66GMQ&data=04%7C01%7Cdirk.gijsen%40aptean.com%7C540fe0f3ea154477f90d08d8f83ce17e%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637532287666878656%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N6Rj9eEhr3q8rGj%2Fff6QCJBnMyCrDomYxcDjrDkgLoU%3D&reserved=0>.

This message contains information that is confidential and/or may be privileged. If you are not the intended recipient, you are hereby notified that any use, dissemination, distribution or copy of this message and/or its attachments is strictly prohibited. If you have received this message in error, please advise the sender immediately by replying to this email and delete this message. We are committed to your privacy. For more information, please see our Privacy Policy at https://www.aptean.com/privacy-statement

**Comment by RomanZanizdra** [comment]
@DirkGijsen , deal. I'll add "Selection" parameter in event.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
