### ISSUE TITLE
[Event Request] codeunit 240 ItemJnlManagement - Function GetItem

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11864]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 240 function GetItem , ofcourse without the prefix DIN.

        if ItemNo <> OldItemNo then begin
            ItemDescription := '';
            if ItemNo <> '' then
                if Item.Get(ItemNo) then
                    ItemDescription := Item.Description;
            OldItemNo := ItemNo;
            // DINNL <<
            DINOnAfterGetItem(Item, ItemDescription);
            // DINNL >>

local procedure DINOnAfterGetItem(var Item: Record Item; var ItemDescription: Text)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
