### ISSUE TITLE
[Event Request] Table 370 Excel Buffer - OnWriteCellFormulaBeforeGetCellDecorator

### ISSUE THREAD

**Issue by SteinleMossGaewers** [microsoft/ALAppExtensions#11863]
Hi, would it be possible to get an event OnWriteCellFormulaBeforeGetCellDecoratorin Table 370 "Excel Buffer", like this:

```
    procedure WriteCellFormula(ExcelBuffer: Record "Excel Buffer")
    var
        Decorator: DotNet CellDecorator;
        IsHandled: Boolean;
    begin
        with ExcelBuffer do begin
            IsHandled := false,
            OnWriteCellFormulaBeforeGetCellDecoratorin(Rec, IsHandled);
            if not IsHandled then begin
                GetCellDecorator(Bold, Italic, Underline, "Double Underline", Decorator);

                XlWrkShtWriter.SetCellFormula("Row No.", xlColID, GetFormula, NumberFormat, Decorator);
            end;
        end;
    end;
```

```
[IntegrationEvent(false, false)]
local procedure OnWriteCellValueBeforeGetCellDecorator(var Rec: Record "Excel Buffer"; var IsHandled: Boolean)
begin
end;
```

**Comment by RomanZanizdra** [comment]
Hi @SteinleMossGaewers , unfortunately we will not be able to provide .NET variable as parameter in event request. You need to find another solution without it. Let me know if "Excel Buffer" will be enough for current request, we will implement it.

**Comment by RomanZanizdra** [comment]
Hi @SteinleMossGaewers . I suggest to close this request for now. Feel free to reopen it.

**Comment by SteinleMossGaewers** [comment]
Hi @RomanZanizdra,
 thanks for checking. Yes, please provide the publisher with the Excel Buffer as parameter. I updated the signature of the event publisher. 

Could you also set the function "GetCellDecorator" to global? That way i can get access to the information i need.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
