### ISSUE TITLE
[Event Request] codeunit 353 ItemAvailabilityFormsMgt- Function FilterItem

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11865]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 353 function FilterItem, ofcourse without the prefix DIN.

        Item.SetRange("No.", Item."No.");
        Item.SetRange("Date Filter", 0D, Date);
        Item.SetRange("Variant Filter", VariantCode);
        Item.SetRange("Location Filter", LocationCode);
        // DINNL <<
        DINOnAfterFilterItem(Item, LocationCode, VariantCode, Date);
        // DINNL >>

local procedure DINOnAfterFilterItem(var Item: Record Item; LocationCode: Code[20]; VariantCode: Code[20]; Date: Date)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
