### ISSUE TITLE
[Event Request] codeunit 5404 Lead-Time Management- Function PurchaseLeadTime

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11867]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5404 function PurchaseLeadTime, of course without the prefix DIN.

        GetItem(ItemNo);
        ItemVend."Vendor No." := VendorNo;
        ItemVend."Variant Code" := VariantCode;
        Item.FindItemVend(ItemVend, LocationCode);
        // DINNL <<
        DINOnBeforeExitPurchaseLeadTime(ItemVend);
        // DINNL >>
        exit(Format(ItemVend."Lead Time Calculation"));

local procedure DINOnBeforeExitPurchaseLeadTime(var ItemVend: Record "Item Vendor")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
