### ISSUE TITLE
[Extensibility Enhancement] Item Tracking Lines Page 6510

### ISSUE THREAD

**Issue by dpodjasek** [microsoft/ALAppExtensions#11860]
Hello, we are creating an app that needs to be able to override the Serial No. code that limits the quantity to one.  We were happy to see that in nearly all places where this is done in the system, there is already an event providing an "IsHandled" variable to override the serial quantity checking.  There are a few places where this has not been provided though, and I will be making requests to add events for them.

Extensibility Enhancement Request:
Item Tracking Lines Page 6510

We need to create some functions very similar to the standard "Assign Serial No." function.  Because our handling of serials is quite different, we would like to make a new page similar to "Enter Quantity to Create", but with our different logic.  In other words, we need to be able to create procedures similar to the standard AssignSerialNo and AssignSerialNoBatch.

Unfortunately, nearly all of the variables needed are not declared as protected, and cannot be accessed by our page extension.

These variables include:
UndefinedQtyArray
QtySignFactor
TempItemTrackLineInsert
SourceQuantityArray
CurrentSignFactor

Thank you, 
David Podjasek

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
