### ISSUE TITLE
event request - report 297 "Batch Post Sales Invoices" - OnPreDataItem() - OnBeforeRunBatch(var SalesBatchPostMgt)

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#11866]
We have a need to call `SalesBatchPostMgt.SetPostingCodeunitId()` on the instance of `codeunit 1371 "Sales Batch Post Mgt."` called by this report, but there's nowhere to do that.

Please add this event publisher:

            trigger OnPreDataItem()
            var
                SalesBatchPostMgt: Codeunit "Sales Batch Post Mgt.";
            begin
                SalesBatchPostMgt.SetParameter("Batch Posting Parameter Type"::Print, PrintDoc);

                OnBeforeRunBatch(SalesBatchPostMgt); // <- NEW and COOL

                SalesBatchPostMgt.RunBatch("Sales Header", ReplacePostingDate, PostingDateReq, ReplaceDocumentDate, CalcInvDisc, false, true);

                CurrReport.Break();
            end;

declared like so:

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeRunBatch(var SalesBatchPostMgt);
```

We can then subscribe to that and set the posting codeunit ID. (Somehow... I didn't figure out a method yet. It'll probably involve global variables somehow, till we get report exts! Anyway, this is one piece of the puzzle that seems required.)

Thanks!

**Comment by RomanZanizdra** [comment]
Hi @dtkb .
I have another suggestion for you. There is event (below) in "Sales Batch Post Mgt." codeunit, not so new but also cool. I can set IncludeSender = true there and then you will be able to set posting codeunit Id there. Or make some other actions. Does it fit for you?
```
[IntegrationEvent(false, false)]
    local procedure OnBeforeRunBatch(var SalesHeader: Record "Sales Header";var ReplacePostingDate: Boolean; PostingDate: Date; ReplaceDocumentDate: Boolean; Ship: Boolean; Invoice: Boolean)
    begin
    end;

```

**Comment by dtkb** [comment]
Hi @RomanZanizdra and thanks! I didn't realise the event you mentioned existed; I've been referring to source for BC 17.3 that I have lying around, which is obviously getting a bit old... So what you said sounds fine, if it'll let us achieve the same possibilities, and putting the event in the codeunit seems better and more widely useful than putting it just in the one report. Cheers!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
