### ISSUE TITLE
[Event Request] codeunit 6502 Late Binding Management- Function PrepareTempDataSet

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11874]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 6502 function PrepareTempDataSet, of course without the prefix DIN.

        ItemLedgEntry.SetRange("Location Code", TempTrackingSpecification."Location Code");
        ItemLedgEntry.SetRange(Positive, true);
        ItemLedgEntry.SetRange(Open, true);

        // DINNL <<
        DINOnPrepareTempDataSet(ItemLedgEntry, TempTrackingSpecification);
        // DINNL >>
        if ItemLedgEntry.FindSet then
            repeat
                TempTrackingSpecification.SetTrackingFilterFromItemLedgEntry(ItemLedgEntry);

local procedure DINOnPrepareTempDataSet(var ItemLedgEntry: Record "Item Ledger Entry"; var TempTrackingSpecification: Record "Tracking Specification" temporary)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
