### ISSUE TITLE
[Event Request] codeunit 7313 Create Put-away - Function Code

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11876]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 7313 function Code, of course without the prefix DIN.

            end else
                if MessageText = '' then
                    if Location."Directed Put-away and Pick" then
                        MessageText := Text002
                    else
                        MessageText := Text003;
        end
        // DINNL <<
        ;
        DINOnAfterCode(WhseActivHeader);
        // DINNL >>
    end;

local procedure DINOnAfterCode(WarehouseActivityHeader: Record "Warehouse Activity Header")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
