### ISSUE TITLE
[Event Request] codeunit 5988 Serv-Documents Mgt. - Function PrepareShipmentHeader

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11873]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5988 function PrepareShipmentHeader, of course without the prefix DIN.

                        // set mgt. date and service dates
                        if (ServItemLine."Contract No." <> '') and (ServItemLine."Contract Line No." <> 0) and
                           ("Contract No." <> '')
                        then begin
                            ServLine.SetRange("Document Type", "Document Type");
                            ServLine.SetRange("Document No.", "No.");
                            ServLine.SetFilter("Quantity Shipped", '>%1', 0);
                            if not ServLine.FindFirst then
                                ServOrderMgt.CalcContractDates(ServHeader, ServItemLine);
                        end;
                        // DINNL <<
                        DINOnBeforeCalcServItemDates(ServHeader, ServItemLine, DINIsHandled);
                        if not DINIsHandled then
                            // DINNL >>
                        ServOrderMgt.CalcServItemDates(ServHeader, ServItemLine."Service Item No.");

local procedure DINOnBeforeCalcServItemDates(var TempServHeader: Record "Service Header" temporary; var TempServItemLine: Record "Service Item Line" temporary; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
