### ISSUE TITLE
[Function Expose] Page 55/98 - Purch. Invoice/Cr. MemoSubform - UpdateAfterChangingHeader

### ISSUE THREAD

**Issue by rvanbekkum** [Microsoft/ALAppExtensions#1187]
Dear ALAppExtensions team,

Through this issue we would like to request the following procedure to be made external so that it can be used from custom page actions:

```pascal
[External]
UpdateAfterChangingHeader()
IF PurchasesPayablesSetup."Show Totals on Purch. Inv./CM." THEN BEGIN
  IF PurchHeader.GET("Document Type","Document No.") THEN BEGIN
    PurchLine.SETRANGE("Document Type","Document Type");
    PurchLine.SETRANGE("Document No.","Document No.");
    PurchLine.SETFILTER(Type,'<>%1',PurchLine.Type::" ");
    PurchLine.SETFILTER(Quantity,'<>0');
    IF PurchLine.FIND('-') THEN BEGIN
      ReleasePurchDoc.Release(PurchHeader,PurchLine,FALSE,FALSE);
      MakeTotals;
    END;
  END;
END;
```

Please note that this procedure is **not** available in W1, but in the NL localization (and other localizations that use this function for totals).

**Comment by IhorHandziuk** [comment]
Hello @rvanbekkum. Thank you for the request , and sorry for the late reply. As was discussed in the issue #568, this functionality will be aligned with W1 in the next major release. Thanks for your patience
