### ISSUE TITLE
[Event Request] codeunit 99000774 Calculate Routing Line - Functions CalcRoutingLineBack / CalcRoutingLineForward

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11878]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 99000774 functions CalcRoutingLineBack / CalcRoutingLineForward, of course without the prefix DIN.

CalcRoutingLineBack 

        if ProdOrderRoutingLine."Schedule Manually" then // Move and wait time has been calculated
            exit;

        repeat
            LotSize := SendAheadLotSize;
            RemainNeedQty :=
              LotSize *
              ProdOrderRoutingLine.RunTimePer;
            // DINNL <<
            DINOnCalculateMinMaxProcessTime(ProdOrderRoutingLine, RemainNeedQty);
            // DINNL >>
            RemainNeedQty :=
              Round(
                RemainNeedQty *
                CalendarMgt.TimeFactor(ProdOrderRoutingLine."Run Time Unit of Meas. Code") /
                CalendarMgt.TimeFactor(Workcenter."Unit of Measure Code"),
                Workcenter."Calendar Rounding Precision");

CalcRoutingLineForward

        repeat
            if (InputQtyDiffTime > 0) and (TotalLotSize = MaxLotSize) then
                SetMaxDateTime(
                  ProdStartingDate, ProdStartingTime, ProdOrderRoutingLine2."Ending Date", ProdOrderRoutingLine2."Ending Time");

            LotSize := SendAheadLotSize;
            RemainNeedQty := LotSize * ProdOrderRoutingLine.RunTimePer;
            // DINNL <<
            DINOnCalculateMinMaxProcessTime(ProdOrderRoutingLine, RemainNeedQty);
            // DINNL >>
            RemainNeedQty :=
              Round(
                RemainNeedQty *
                CalendarMgt.TimeFactor(ProdOrderRoutingLine."Run Time Unit of Meas. Code") /
                CalendarMgt.TimeFactor(Workcenter."Unit of Measure Code"),
                Workcenter."Calendar Rounding Precision");

local procedure DINOnCalculateMinMaxProcessTime(ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var RemainNeedQty: Decimal)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
