### ISSUE TITLE
[Event Request] codeunit 99000809 Planning Line Management - Function TransferBOM

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11879]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 99000809 function TransferBOM, of course without the prefix DIN.

                        ReqQty :=
                          ProdBOMLine[Level].Quantity *
                          (1 + ProdBOMLine[Level]."Scrap %" / 100) *
                          (1 + PlanningRtngLine2."Scrap Factor % (Accumulated)") *
                          LineQtyPerUOM /
                          ItemQtyPerUOM +
                          PlanningRtngLine2."Fixed Scrap Qty. (Accum.)";
                    end else
                        ReqQty :=
                          ProdBOMLine[Level].Quantity *
                          (1 + ProdBOMLine[Level]."Scrap %" / 100) *
                          LineQtyPerUOM /
                          ItemQtyPerUOM;
                    // DINNL <<
                    DINOnTransferBomCalculateReqQty(ReqQty, ProdBOMLine[Level]);
                    // DINNL >>
                    case ProdBOMLine[Level].Type of
                        ProdBOMLine[Level].Type::Item:
                            begin
                                IsHandled := false;
                                UpdateCondition := ReqQty <> 0;
                                OnTransferBOMOnBeforeUpdatePlanningComp(ProdBOMLine[Level], UpdateCondition, IsHandled);

local procedure DINOnTransferBomCalculateReqQty(var ReqQty: Decimal; ProdBOMLine: Record "Production BOM Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
