### ISSUE TITLE
[Event Request] codeunit 7323 Whse.-Act.-Post (Yes/No)- Functions SelectForPutAway + SelectForOtherTypes

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11877]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 7323 functions SelectForPutAway + SelectForOtherTypes, of course without the prefix DIN.

SelectForPutAway 

        with WhseActivLine do
            if ("Source Document" = "Source Document"::"Prod. Output") or
               ("Source Document" = "Source Document"::"Inbound Transfer") or
               ("Source Document" = "Source Document"::"Prod. Consumption")
            then begin
                if not Confirm(Text002, false, "Activity Type", "Source Document") then
                    exit(false);
            end else begin
                // DINNL <<
                DINOnSetSelectionFromWhseActPost(WhseActivLine, Selection, DINIsHandled);
                if not DINIsHandled then
                    // DINNL >>
                Selection := StrMenu(Text000, DefaultOption);
                if Selection = 0 then
                    exit(false);
            end;

SelectForOtherTypes

        with WhseActivLine do
            if ("Source Document" = "Source Document"::"Prod. Consumption") or
               ("Source Document" = "Source Document"::"Outbound Transfer")
            then begin
                if not Confirm(Text002, false, "Activity Type", "Source Document") then
                    exit(false);
            end else begin
                // DINNL <<
                DINOnSetSelectionFromWhseActPost(WhseActivLine, Selection, DINIsHandled);
                if not DINIsHandled then
                    // DINNL >>
                Selection := StrMenu(Text001, DefaultOption);
                if Selection = 0 then
                    exit(false);
            end;

local procedure DINOnSetSelectionFromWhseActPost(var WhseActivLine: Record "Warehouse Activity Line"; var Selection: Integer; var IsHandled: Boolean)

**Comment by RomanZanizdra** [comment]
Hi @DirkGijsen . Let's do it in a little bit other way. I'll add OnBefore... events for both procedures based on the "IsHandled" and "Result" pattern. So you will just to set "Result" parameter as you need.

**Comment by DirkGijsen** [comment]
Hi Roman,

I agree with the suggested solution.
Thanks

Van: RomanZanizdra ***@***.***>
Verzonden: woensdag 7 april 2021 12:52
Aan: microsoft/ALAppExtensions ***@***.***>
CC: Dirk Gijsen ***@***.***>; Mention ***@***.***>
Onderwerp: [EXTERNAL] Re: [microsoft/ALAppExtensions] [Event Request] codeunit 7323 Whse.-Act.-Post (Yes/No)- Functions SelectForPutAway + SelectForOtherTypes (#11877)

EXTERNAL
________________________________


Hi @DirkGijsen<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDirkGijsen&data=04%7C01%7Cdirk.gijsen%40aptean.com%7C1f9b47b4a9094cd379b908d8f9b32613%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637533895122715449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=x5GZTf7rd1m11rxVOZ46N0UJmIsK6sclM8dCtAtq6xM%3D&reserved=0> . Let's do it in a little bit other way. I'll add OnBefore... events for both procedures based on the "IsHandled" and "Result" pattern. So you will just to set "Result" parameter as you need.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FALAppExtensions%2Fissues%2F11877%23issuecomment-814813566&data=04%7C01%7Cdirk.gijsen%40aptean.com%7C1f9b47b4a9094cd379b908d8f9b32613%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637533895122715449%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MwNiE2eATajpPiBcZh5HDzJwLM%2FSk06zE74gooAJ%2BF4%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKUUR3OJIIXXYFNLT3C2T23THQ2MDANCNFSM42HBWYYA&data=04%7C01%7Cdirk.gijsen%40aptean.com%7C1f9b47b4a9094cd379b908d8f9b32613%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637533895122725445%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sPOLom0EflBcGt0ZR9sTqYjQA0yciYEs8O8%2B1opwLcQ%3D&reserved=0>.

This message contains information that is confidential and/or may be privileged. If you are not the intended recipient, you are hereby notified that any use, dissemination, distribution or copy of this message and/or its attachments is strictly prohibited. If you have received this message in error, please advise the sender immediately by replying to this email and delete this message. We are committed to your privacy. For more information, please see our Privacy Policy at https://www.aptean.com/privacy-statement

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
