### ISSUE TITLE
[Event Request] codeunit 7310 Whse.-Shipment Release - Function CreateWhsePickRequest

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11875]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 7310 function CreateWhsePickRequest, of course without the prefix DIN.

                WhsePickRequest."Zone Code" := "Zone Code";
                WhsePickRequest."Bin Code" := "Bin Code";
                CalcFields("Completely Picked");
                WhsePickRequest."Completely Picked" := "Completely Picked";
                // DINNL <<
                DINOnBeforeWhsePickRequestInsert(WhsePickRequest, WhseShptHeader);
                // DINNL >>		
                WhsePickRequestInsert(WhsePickRequest, WhseShptHeader);

local procedure DINOnBeforeWhsePickRequestInsert(var WhsePickRequest: Record "Whse. Pick Request"; WarehouseShipmentHeader: Record "Warehouse Shipment Header")

**Comment by RomanZanizdra** [comment]
Hi @DirkGijsen .
Is it ok for you to use OnBeforeWhsePickRequestInsert() event in the WhsePickRequestInsert() ?

```
    local procedure WhsePickRequestInsert(var WhsePickRequest: Record "Whse. Pick Request"; var WhseShptHeader: Record "Warehouse Shipment Header")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeWhsePickRequestInsert(WhsePickRequest, WhseShptHeader, IsHandled);
        if IsHandled then
            exit;

        if not WhsePickRequest.Insert() then
            WhsePickRequest.Modify();
        OnAfterWhsePickRequestInsert(WhsePickRequest);
    end;

```

**Comment by RomanZanizdra** [comment]
Hi @DirkGijsen . Any update from your side?

**Comment by DirkGijsen** [comment]
Hi Roman,

Yes this is fine for me.
Thanks.

Van: RomanZanizdra ***@***.***>
Verzonden: woensdag 7 april 2021 12:16
Aan: microsoft/ALAppExtensions ***@***.***>
CC: Dirk Gijsen ***@***.***>; Mention ***@***.***>
Onderwerp: [EXTERNAL] Re: [microsoft/ALAppExtensions] [Event Request] codeunit 7310 Whse.-Shipment Release - Function CreateWhsePickRequest (#11875)

EXTERNAL
________________________________


Hi @DirkGijsen<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDirkGijsen&data=04%7C01%7Cdirk.gijsen%40aptean.com%7Cd148135bd9e44d22cbca08d8f9ae1eb8%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637533873532474671%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=m7AOgXLEPilttngX6Wuc3JhdXHXLsPeXw8cXLoFckeY%3D&reserved=0> .
Is it ok for you to use OnBeforeWhsePickRequestInsert() event in the WhsePickRequestInsert() ?

    local procedure WhsePickRequestInsert(var WhsePickRequest: Record "Whse. Pick Request"; var WhseShptHeader: Record "Warehouse Shipment Header")

    var

        IsHandled: Boolean;

    begin

        IsHandled := false;

        OnBeforeWhsePickRequestInsert(WhsePickRequest, WhseShptHeader, IsHandled);

        if IsHandled then

            exit;



        if not WhsePickRequest.Insert() then

            WhsePickRequest.Modify();

        OnAfterWhsePickRequestInsert(WhsePickRequest);

    end;



-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FALAppExtensions%2Fissues%2F11875%23issuecomment-814792448&data=04%7C01%7Cdirk.gijsen%40aptean.com%7Cd148135bd9e44d22cbca08d8f9ae1eb8%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637533873532484664%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fwdG6VMQ94cdO5Wm3uSJKxwkjGfGNkvkxSPQdrxeZ1o%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKUUR3LP4YTKN3LK7OGOTWTTHQWFHANCNFSM42HA5MHQ&data=04%7C01%7Cdirk.gijsen%40aptean.com%7Cd148135bd9e44d22cbca08d8f9ae1eb8%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637533873532484664%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Wq5%2BWXiVTsdnQHCqYob3CuKrQuUyx7sMkHuKs2l1p%2Fc%3D&reserved=0>.

This message contains information that is confidential and/or may be privileged. If you are not the intended recipient, you are hereby notified that any use, dissemination, distribution or copy of this message and/or its attachments is strictly prohibited. If you have received this message in error, please advise the sender immediately by replying to this email and delete this message. We are committed to your privacy. For more information, please see our Privacy Policy at https://www.aptean.com/privacy-statement
