### ISSUE TITLE
[Event Request] codeunit 5900 ServOrderManagement - Function InsertServCost

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11871]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5900 function InsertServCost, of course without the prefix DIN.

            1: // Starting Fee
                begin
                    ServMgtSetup.Get();
                    ServMgtSetup.TestField("Service Order Starting Fee");
                    ServCost.Get(ServMgtSetup."Service Order Starting Fee");
                    // DINNL <<
                    DINOnGetServCost(ServHeader, ServCost);
                    // DINNL >>
                    ServInvLine2.Init();
                    if LinktoServItemLine then begin

local procedure DINOnGetServCost(var ServiceHeader: Record "Service Header"; var ServiceCost: Record "Service Cost");

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
