### ISSUE TITLE
[Event Request] codeunit 5777 Whse. Validate Source Line - Function ItemLineVerifyChange

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11870]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5777 function ItemLineVerifyChange, of course without the prefix DIN.

    if Location.Get("Location Code") and Location."Require Pick" and Location."Require Shipment" then
        if ProdOrderComp.Get(
            ProdOrderComp.Status::Released,
            "Order No.", "Order Line No.", "Prod. Order Comp. Line No.") and
            (ProdOrderComp."Flushing Method" = ProdOrderComp."Flushing Method"::Manual) and
            (Quantity >= 0)
        then begin
            QtyRemainingToBePicked :=
                Quantity - CalcNextLevelProdOutput(ProdOrderComp) -
                ProdOrderComp."Qty. Picked" + ProdOrderComp."Expected Quantity" - ProdOrderComp."Remaining Quantity";
                // DINNL <<
                DINOnItemLineVerifyChangeBeforeCheckQtyRemainingToBePicked(QtyRemainingToBePicked);
                // DINNL >>
                CheckQtyRemainingToBePickedForConsumption(NewItemJnlLine, OldItemJnlLine, ProdOrderComp, QtyRemainingToBePicked);
                QtyChecked := true;

local procedure DINOnItemLineVerifyChangeBeforeCheckQtyRemainingToBePicked(var QtyRemainingToBePicked: Decimal)

**Comment by RomanZanizdra** [comment]
Hi @DirkGijsen .
What is the purpose for this event? You asked only QtyRemainingToBePicked  parameter, so looks like you just want to set it to zero. If so then I suggest you to use CheckQtyRemainingToBePickedForConsumption with "IsHandled" event and skip the check.

**Comment by DirkGijsen** [comment]
Hi Roman,

Thanks for your correct analyses.
We can indeed use the suggested event.

Regards
Dirk

Van: RomanZanizdra ***@***.***>
Verzonden: maandag 5 april 2021 16:11
Aan: microsoft/ALAppExtensions ***@***.***>
CC: Dirk Gijsen ***@***.***>; Mention ***@***.***>
Onderwerp: [EXTERNAL] Re: [microsoft/ALAppExtensions] [Event Request] codeunit 5777 Whse. Validate Source Line - Function ItemLineVerifyChange (#11870)

EXTERNAL
________________________________


Hi @DirkGijsen<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDirkGijsen&data=04%7C01%7Cdirk.gijsen%40aptean.com%7Cdb4da65e38344e9d7fe308d8f83c9b3d%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637532286471652709%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BhW1R6M88qKhPk6Msn9mjxUVnmHJuDICnsWbTrhOy9I%3D&reserved=0> .
What is the purpose for this event? You asked only QtyRemainingToBePicked parameter, so looks like you just want to set it to zero. If so then I suggest you to use CheckQtyRemainingToBePickedForConsumption with "IsHandled" event and skip the check.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FALAppExtensions%2Fissues%2F11870%23issuecomment-813412679&data=04%7C01%7Cdirk.gijsen%40aptean.com%7Cdb4da65e38344e9d7fe308d8f83c9b3d%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637532286471652709%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=e99GBc2XVi0M6UxpzczaVKcW2dODvzGehWYevTmVpKg%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKUUR3K2DG2TDLDNFRWAPADTHHAF5ANCNFSM42G7LHVQ&data=04%7C01%7Cdirk.gijsen%40aptean.com%7Cdb4da65e38344e9d7fe308d8f83c9b3d%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637532286471662706%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hCG6CrWsPem5B4vQ4%2FusC5ZPEwiaV9N7xJRv%2BLchxRM%3D&reserved=0>.

This message contains information that is confidential and/or may be privileged. If you are not the intended recipient, you are hereby notified that any use, dissemination, distribution or copy of this message and/or its attachments is strictly prohibited. If you have received this message in error, please advise the sender immediately by replying to this email and delete this message. We are committed to your privacy. For more information, please see our Privacy Policy at https://www.aptean.com/privacy-statement
