### ISSUE TITLE
[Event Request] codeunit 5943 Lock-OpenServContract- Function LockServContract

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11872]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5943 function LockServContract, of course without the prefix DIN.

            if "Annual Amount" < 0 then
                Error(Text003);
            // DINNL <<
            DINOnAllowServiceContractsWithZeroAmount(DINIsHandled);
            if not DINIsHandled then
            // DINNL >>
            if IsInvoicePeriodInTimeSegment() then
                if "Annual Amount" = 0 then
                    Error(Text004);

local procedure DINOnAllowServiceContractsWithZeroAmount(var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
