### ISSUE TITLE
[Event Request] codeunit 99000832 Sales Line-Reserve - Function CallItemTrackingSecondSource

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11883]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 99000832 function CallItemTrackingSecondSource, of course without the prefix DIN.

        if SecondSourceQuantityArray[1] = DATABASE::"Warehouse Shipment Line" then
            ItemTrackingLines.SetSecondSourceID(DATABASE::"Warehouse Shipment Line", AsmToOrder);

        TrackingSpecification.InitFromSalesLine(SalesLine);
        // DINNL <<
        DINOnCallItemTrackingSecondSource(SalesLine, SecondSourceQuantityArray, TrackingSpecification, DINIsHandled);
        if DINIsHandled then
            exit;
        // DINNL >>
        ItemTrackingLines.SetSourceSpec(TrackingSpecification, SalesLine."Shipment Date");
        ItemTrackingLines.SetSecondSourceQuantity(SecondSourceQuantityArray);
        ItemTrackingLines.RunModal;

local procedure DINOnCallItemTrackingSecondSource(var SalesLine: Record "Sales Line"; SecondSourceQuantityArray: array[3] of Decimal; TrackingSpecification: Record "Tracking Specification"; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
