### ISSUE TITLE
[Event Request] Request for new event publisher OnBeforeStartSalesTaxCalculation in codeunit 398

### ISSUE THREAD

**Issue by SerhiiKurinnyi** [microsoft/ALAppExtensions#11889]
i would like to be able to intervene with code, so please add new integration event called OnBeforeStartSalesTaxCalculation at the start of the function StartSalesTaxCalculation

`    
    procedure StartSalesTaxCalculation()
    begin
        OnBeforeStartSalesTaxCalculation(); //New event request
        TempSalesTaxLine.Reset();
        TempSalesTaxLine.DeleteAll();
        TempTaxAmountDifference.Reset();
        TempTaxAmountDifference.DeleteAll();
        ClearAll;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeStartSalesTaxCalculation ()
    begin
    end;`

**Comment by AlexanderYakunin** [comment]
Which parameters do you need here?

**Comment by SerhiiKurinnyi** [comment]
@al

**Comment by SerhiiKurinnyi** [comment]
> Which parameters do you need here?

Could we have event without any parameters?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
