### ISSUE TITLE
[Event Request] Codeunit 76 "Purch.-Get Drop Shpt."

### ISSUE THREAD

**Issue by aconcato** [microsoft/ALAppExtensions#11887]
Could you please add the Purchase Header on these 2 events ?

OnCodeOnAfterSalesLineSetFilters(SalesLine); 
OnCodeOnAfterSalesLineSetFilters(PurchHeader,SalesLine);  

OnCodeOnBeforeProcessPurchaseLine(SalesLine, IsHandled);
OnCodeOnBeforeProcessPurchaseLine(PurchHeader,SalesLine, IsHandled);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
