### ISSUE TITLE
[Event Request] codeunit 99000834 Purch Line-Reserve - Function RetrieveInvoiceSpecification2

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11885]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 99000834  function RetrieveInvoiceSpecification2, of course without the prefix DIN.

        repeat
            ReservEntry.TestField("Reservation Status", ReservEntry."Reservation Status"::Prospect);
            ReservEntry.TestField("Item Ledger Entry No.");
            TrackingSpecification.Get(ReservEntry."Item Ledger Entry No.");
            TempInvoicingSpecification := TrackingSpecification;
            TempInvoicingSpecification."Qty. to Invoice (Base)" := ReservEntry."Qty. to Invoice (Base)";
            TempInvoicingSpecification."Qty. to Invoice" :=
              Round(ReservEntry."Qty. to Invoice (Base)" / ReservEntry."Qty. per Unit of Measure", UOMMgt.QtyRndPrecision);
            TempInvoicingSpecification."Buffer Status" := TempInvoicingSpecification."Buffer Status"::MODIFY;
            // DINNL <<
            DINOnRetrieveInvoiceSpecification2BeforeInsert(ReservEntry, TempInvoicingSpecification);
            // DINNL >>
            TempInvoicingSpecification.Insert();
            ReservEntry.Delete();
        until ReservEntry.Next() = 0;

local procedure DINOnRetrieveInvoiceSpecification2BeforeInsert(ReservationEntry: Record "Reservation Entry"; var TempInvoicingSpecification: Record "Tracking Specification" temporary)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
