### ISSUE TITLE
[Event Request] codeunit 99000854 Inventory Profile Offsetting - Function MaintainPlanningLine

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11886]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 99000854 function MaintainPlanningLine, of course without the prefix DIN.

        if NewPhase = NewPhase::Obsolete then begin
            if SupplyInvtProfile."Planning Line No." <> ReqLine."Line No." then
                ReqLine.Get(CurrTemplateName, CurrWorksheetName, SupplyInvtProfile."Planning Line No.");
            ReqLine.Delete(true);
            SupplyInvtProfile."Planning Line No." := 0;
            SupplyInvtProfile."Planning Line Phase" := SupplyInvtProfile."Planning Line Phase"::" ";
        end;

        SupplyInvtProfile.Modify();
        // DINNL <<
        DINOnAfterMaintainPlanningLine(ReqLine);
        // DINNL >>
    end;

local procedure DINOnAfterMaintainPlanningLine(RequisitionLine: Record "Requisition Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
