### ISSUE TITLE
[Event Request] codeunit 99000831 Reservation Engine Mgt. - Function ModifyItemTrkgByReservStatus

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11881]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 99000831 function ModifyItemTrkgByReservStatus, of course without the prefix DIN.

    begin
        // DINNL <<
        DINOnBeforeModifyItemTrkgByReservStatus(DINIsHandled);
        if DINIsHandled then
        // DINNL >>
        if QtyToAdd = 0 then
            exit;

        TempReservEntry.SetRange("Reservation Status", ReservStatus);
        if TempReservEntry.FindSet() then

local procedure DINOnBeforeModifyItemTrkgByReservStatus(var IsHandled: Boolean)

**Comment by AlexanderYakunin** [comment]
Event implementation should not alter existing business logic. Please explain what you need to achieve? Would you like to override whole function or need to change condition QtyToAdd = 0 for exit?

**Comment by DirkGijsen** [comment]
Hi,

We have functionality with a Dual Unit of Measure and a field DualQtyToAdd.
In some scenarios it is possible that the QtyToAdd = 0 but our field DualQtyToAdd not, and then we want to execute the function and not get an exit.
So in case that our field DualQtyToAdd <> 0, IsHandeld stays false and the exit is not executed.


Van: Alexander Yakunin ***@***.***>
Verzonden: woensdag 7 april 2021 10:12
Aan: microsoft/ALAppExtensions ***@***.***>
CC: Dirk Gijsen ***@***.***>; Author ***@***.***>
Onderwerp: [EXTERNAL] Re: [microsoft/ALAppExtensions] [Event Request] codeunit 99000831 Reservation Engine Mgt. - Function ModifyItemTrkgByReservStatus (#11881)

EXTERNAL
________________________________


Event implementation should not alter existing business logic. Please explain what you need to achieve? Would you like to override whole function or need to change condition QtyToAdd = 0 for exit?

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FALAppExtensions%2Fissues%2F11881%23issuecomment-814704003&data=04%7C01%7Cdirk.gijsen%40aptean.com%7Cb03408a2043d4dc00dd008d8f99ce23e%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637533799515496692%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dfGweu4dNcRng2LQWjtDMlYtgXMw1th2SkHDipWTe5s%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKUUR3LE6R46GGQ6IRO5S73THQHWNANCNFSM42HFP4EQ&data=04%7C01%7Cdirk.gijsen%40aptean.com%7Cb03408a2043d4dc00dd008d8f99ce23e%7C560ec2b0df0c4e8c9848a15718863bb6%7C0%7C0%7C637533799515496692%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BBs0o5X9k7CUKh5fco72NHN5L0Tksm5EbweBKusm6s0%3D&reserved=0>.

This message contains information that is confidential and/or may be privileged. If you are not the intended recipient, you are hereby notified that any use, dissemination, distribution or copy of this message and/or its attachments is strictly prohibited. If you have received this message in error, please advise the sender immediately by replying to this email and delete this message. We are committed to your privacy. For more information, please see our Privacy Policy at https://www.aptean.com/privacy-statement

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
