### ISSUE TITLE
[Event Request] codeunit 99000831 Reservation Engine Mgt. - Function ModifyItemTrackingOnTempRec

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11882]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 99000831 function ModifyItemTrackingOnTempRec, of course without the prefix DIN.

            if EntryMismatch then
                LastEntryNo := 0;

            ReservEntry1.Validate("Quantity (Base)", ReservEntry1."Quantity (Base)" - QtyToAdd);
            // DINNL <<
            DINOnModifyItemTrackingOnTempRecBeforeModifyReservEntry(ReservEntry1);
            // DINNL >>
            ReservEntry1.Modify();
            TempReservEntry := ReservEntry1;
            if not CalledRecursively then begin
                TempReservEntry := ReservEntry2;
                if TempReservEntry."Quantity (Base)" <> 0 then
                    TempReservEntry.Insert();
                TempReservEntry := ReservEntry1;
                TempReservEntry.Modify();

local procedure DINOnModifyItemTrackingOnTempRecBeforeModifyReservEntry(var ReservEntry: Record "Reservation Entry")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
