### ISSUE TITLE
[Event Request] codeunit 99000810 Calculate Planning Route Line- Functions CalcRoutingLineBack / CalcRoutingLineForward

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11880]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 99000810 functions CalcRoutingLineBack / CalcRoutingLineForward, of course without the prefix DIN.

CalcRoutingLineBack 

        repeat
            LotSize := SendAheadLotSize;
            RemainNeedQty :=
              LotSize *
              PlanningRoutingLine.RunTimePer;
            // DINNL <<
            DINOnCalculateMinMaxProcessTime(PlanningRoutingLine, RemainNeedQty);
            // DINNL >>
            RemainNeedQty :=
              Round(
                RemainNeedQty *
                CalendarMgt.TimeFactor(PlanningRoutingLine."Run Time Unit of Meas. Code") /
                CalendarMgt.TimeFactor(WorkCenter."Unit of Measure Code"),
                WorkCenter."Calendar Rounding Precision");

CalcRoutingLineForward

        repeat
            if (InputQtyDiffTime > 0) and (TotalLotSize = MaxLotSize) then begin
                if ProdStartingDate < PlanningRoutingLine2."Ending Date" then begin
                    ProdStartingDate := PlanningRoutingLine2."Ending Date";
                    ProdStartingTime := PlanningRoutingLine2."Ending Time";
                end else
                    if PlanningRoutingLine2."Ending Date" = ProdEndingDate then
                        if PlanningRoutingLine2."Ending Time" > ProdStartingTime then
                            ProdStartingTime := PlanningRoutingLine2."Ending Time";
            end;

            LotSize := SendAheadLotSize;
            RemainNeedQty := LotSize * PlanningRoutingLine.RunTimePer;
            // DINNL <<
            DINOnCalculateMinMaxProcessTime(PlanningRoutingLine, RemainNeedQty);
            // DINNL >>
            RemainNeedQty :=
              Round(
                RemainNeedQty *
                CalendarMgt.TimeFactor(PlanningRoutingLine."Run Time Unit of Meas. Code") /
                CalendarMgt.TimeFactor(WorkCenter."Unit of Measure Code"),
                WorkCenter."Calendar Rounding Precision");

local procedure DINOnCalculateMinMaxProcessTime(PlanningRoutingLine: Record "Planning Routing Line"; var RemainNeedQty: Decimal)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
