### ISSUE TITLE
[Event Request] Request for new event publisher OnAfterGetSalesTaxAmountLineTablein codeunit 398

### ISSUE THREAD

**Issue by SerhiiKurinnyi** [microsoft/ALAppExtensions#11892]
i would like to be able to intervene with code, so please add new integration event called OnAfterGetSalesTaxAmountLineTableat the end of the function GetSalesTaxAmountLineTable

`    
    procedure GetSalesTaxAmountLineTable(var SalesTaxLine2: Record "Sales Tax Amount Line" temporary)
    begin
        TempSalesTaxLine.Reset();
        if TempSalesTaxLine.FindSet then
            repeat
                SalesTaxLine2.Copy(TempSalesTaxLine);
                SalesTaxLine2.Insert();
            until TempSalesTaxLine.Next() = 0;
        
        OnAfterGetSalesTaxAmountLineTable(SalesTaxLine2); //New event request
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetSalesTaxAmountLineTable(var SalesTaxLine2: Record "Sales Tax Amount Line" temporary)
    begin
    end;`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
