### ISSUE TITLE
CodeUnit 5703 - Nonstock Item Management - GetNewItemNo

### ISSUE THREAD

**Issue by vinpicci** [microsoft/ALAppExtensions#11896]
Hi, would it be possible to change the procedure GetNewItemNo in codeunit 5703 from local to external?
Thanks for your time

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
