### ISSUE TITLE
[Request-for-external] Page 161 "Purchase Statistics" - GetCaptionClass / UpdateInvDiscAmount / UpdateTotalAmount

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11898]
Dear ALAppExtensions Team,

We would like to request the following : Is it possible to change the functions GetCaptionClass / UpdateInvDiscAmount / UpdateTotalAmount in Page 161 from [Local] to [External] ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
