### ISSUE TITLE
[Event Request] Request for new event publisher OnAfterSetFilterTempSalesTaxLineOnAddSalesLine in codeunit 398

### ISSUE THREAD

**Issue by SerhiiKurinnyi** [microsoft/ALAppExtensions#11891]
I would like to change filter on function AddSalesLine after SetRange("Tax Group Code", SalesLine."Tax Group Code"); Could you please add new event OnAfterSetFilterTempSalesTaxLineOnAddSalesLine

`    procedure AddSalesLine(SalesLine: Record "Sales Line")
    var
        TaxDetail: Record "Tax Detail";
        SalesTaxAmountLineCalc: Codeunit "Sales Tax Amount Line Calc";
        TotalPositive: Boolean;
        SalesLinePositive: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeAddSalesLine(SalesLine, IsHandled);
        if IsHandled then
            exit;

        if not SalesHeaderRead then begin
            if TempSalesHeader.Get(SalesLine."Document Type", SalesLine."Document No.") then
                SalesHeader := TempSalesHeader
            else
                SalesHeader.Get(SalesLine."Document Type", SalesLine."Document No.");
            SalesHeaderRead := true;
            SalesHeader.TestField("Prices Including VAT", false);
            if not GetSalesTaxCountry(SalesHeader."Tax Area Code") then
                exit;
            SetUpCurrency(SalesHeader."Currency Code");
            if SalesHeader."Currency Code" <> '' then
                SalesHeader.TestField("Currency Factor");
            if SalesHeader."Currency Factor" = 0 then
                ExchangeFactor := 1
            else
                ExchangeFactor := SalesHeader."Currency Factor";
            CopyTaxDifferencesToTemp(
              TaxAmountDifference."Document Product Area"::Sales,
              SalesLine."Document Type".AsInteger(),
              SalesLine."Document No.");
            SalesHeader.CalcFields(Amount);
        end;
        if not GetSalesTaxCountry(SalesLine."Tax Area Code") then
            exit;

        SalesLine.TestField("Tax Group Code");
        with TempSalesTaxLine do begin
            Reset;
            case TaxCountry of
                TaxCountry::US:  // Area Code
                    begin
                        SetRange("Tax Area Code for Key", SalesLine."Tax Area Code");
                        "Tax Area Code for Key" := SalesLine."Tax Area Code";
                    end;
                TaxCountry::CA:  // Jurisdictions
                    begin
                        SetRange("Tax Area Code for Key", '');
                        "Tax Area Code for Key" := '';
                    end;
            end;
            SetRange("Tax Group Code", SalesLine."Tax Group Code");
            OnAfterSetFilterTempSalesTaxLineOnAddSalesLine(TempSalesTaxLine);  //New event request
            
            TaxAreaLine.SetCurrentKey("Tax Area", "Calculation Order");
            TaxAreaLine.SetRange("Tax Area", SalesLine."Tax Area Code");

            TotalPositive := SalesHeader.Amount > 0;
            SalesLinePositive := SalesLine."Line Amount" > 0;
            TaxDetail.SetRange("Tax Group Code", SalesLine."Tax Group Code");
            TaxDetail.SetFilter("Effective Date", '<=%1', SalesHeader."Posting Date");

            if TaxAreaLine.FindSet then
                repeat
                    SetRange("Tax Jurisdiction Code", TaxAreaLine."Tax Jurisdiction Code");
                    "Tax Jurisdiction Code" := TaxAreaLine."Tax Jurisdiction Code";

                    SetRange(Positive, SalesLinePositive);
                    Positive := SalesLinePositive;
                    TaxDetail.SetRange("Tax Jurisdiction Code", TaxAreaLine."Tax Jurisdiction Code");
                    if (TotalPositive <> SalesLinePositive) and (SalesHeader.Amount <> 0) then
                        if TaxDetail.FindLast then
                            if TaxDetail."Maximum Amount/Qty." <> 0 then begin
                                SetRange(Positive, TotalPositive);
                                Positive := TotalPositive;
                            end;

                    if not FindFirst then begin
                        Init;
                        "Tax Group Code" := SalesLine."Tax Group Code";
                        "Tax Area Code" := SalesLine."Tax Area Code";
                        "Tax Jurisdiction Code" := TaxAreaLine."Tax Jurisdiction Code";
                        if TaxCountry = TaxCountry::US then begin
                            "Round Tax" := TaxArea."Round Tax";
                            TaxJurisdiction.Get("Tax Jurisdiction Code");
                            "Is Report-to Jurisdiction" := ("Tax Jurisdiction Code" = TaxJurisdiction."Report-to Jurisdiction");
                        end;
                        SalesTaxAmountLineCalc.SetTaxBaseAmount(
                            TempSalesTaxLine, SalesLine."Line Amount" - SalesLine."Inv. Discount Amount", ExchangeFactor, false);
                        "Line Amount" := SalesLine."Line Amount" / ExchangeFactor;
                        "Tax Liable" := SalesLine."Tax Liable";
                        Quantity := SalesLine."Quantity (Base)";
                        "Invoice Discount Amount" := SalesLine."Inv. Discount Amount";
                        "Calculation Order" := TaxAreaLine."Calculation Order";

                        Insert;
                    end else begin
                        "Line Amount" := "Line Amount" + (SalesLine."Line Amount" / ExchangeFactor);
                        "Tax Liable" := SalesLine."Tax Liable";
                        SalesTaxAmountLineCalc.SetTaxBaseAmount(
                            TempSalesTaxLine, SalesLine."Line Amount" - SalesLine."Inv. Discount Amount", ExchangeFactor, true);
                        "Tax Amount" := 0;
                        Quantity := Quantity + SalesLine."Quantity (Base)";
                        "Invoice Discount Amount" := "Invoice Discount Amount" + SalesLine."Inv. Discount Amount";
                        Modify;
                    end;
                until TaxAreaLine.Next() = 0;
        end;

        OnAfterAddSalesLine(TempSalesTaxLine, SalesLine, SalesHeader, ExchangeFactor);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetFilterTempSalesTaxLineOnAddSalesLine(var TempSalesTaxLine: Record "Sales Tax Amount Line" temporary;)
    begin
    end;`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
