### ISSUE TITLE
[Event Request]  Request for new event publisher OnAfterSetFilterTempSalesTaxLineOnAddPurchLine in codeunit 398

### ISSUE THREAD

**Issue by SerhiiKurinnyi** [microsoft/ALAppExtensions#11890]
I would like to change filter on function AddPurchLine after SetRange("Use Tax", PurchLine."Use Tax"); Could you please add new event OnAfterSetFilterTempSalesTaxLineOnAddPurchLine 

`    
procedure AddPurchLine(PurchLine: Record "Purchase Line")
    var
        TaxDetail: Record "Tax Detail";
        SalesTaxAmountLineCalc: Codeunit "Sales Tax Amount Line Calc";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeAddPurchLine(PurchLine, IsHandled); 
        if IsHandled then
            exit;

        if not PurchHeaderRead then begin
            PurchLine.GetPurchHeader();
            PurchHeader.Get(PurchLine."Document Type", PurchLine."Document No.");
            PurchHeaderRead := true;
            PurchHeader.TestField("Prices Including VAT", false);
            if not GetSalesTaxCountry(PurchHeader."Tax Area Code") then
                exit;
            SetUpCurrency(PurchHeader."Currency Code");
            if PurchHeader."Currency Code" <> '' then
                PurchHeader.TestField("Currency Factor");
            if PurchHeader."Currency Factor" = 0 then
                ExchangeFactor := 1
            else
                ExchangeFactor := PurchHeader."Currency Factor";
            CopyTaxDifferencesToTemp(
              TaxAmountDifference."Document Product Area"::Purchase,
              PurchLine."Document Type".AsInteger(),
              PurchLine."Document No.");
        end;
        if not GetSalesTaxCountry(PurchLine."Tax Area Code") then
            exit;

        PurchLine.TestField("Tax Group Code");

        with TempSalesTaxLine do begin
            Reset;
            case TaxCountry of
                TaxCountry::US:  // Area Code
                    begin
                        SetRange("Tax Area Code for Key", PurchLine."Tax Area Code");
                        "Tax Area Code for Key" := PurchLine."Tax Area Code";
                    end;
                TaxCountry::CA:  // Jurisdictions
                    begin
                        SetRange("Tax Area Code for Key", '');
                        "Tax Area Code for Key" := '';
                    end;
            end;
            SetRange("Tax Group Code", PurchLine."Tax Group Code");
            SetRange("Use Tax", PurchLine."Use Tax");
            OnAfterSetFilterTempSalesTaxLineOnAddPurchLine(TempSalesTaxLine);  //New event request
            TaxAreaLine.SetCurrentKey("Tax Area", "Calculation Order");
            TaxAreaLine.SetRange("Tax Area", PurchLine."Tax Area Code");
            if TaxAreaLine.FindSet then
                repeat
                    SetRange("Tax Jurisdiction Code", TaxAreaLine."Tax Jurisdiction Code");
                    "Tax Jurisdiction Code" := TaxAreaLine."Tax Jurisdiction Code";
                    if not FindFirst then begin
                        Init;
                        "Tax Group Code" := PurchLine."Tax Group Code";
                        "Tax Area Code" := PurchLine."Tax Area Code";
                        "Tax Jurisdiction Code" := TaxAreaLine."Tax Jurisdiction Code";
                        if TaxCountry = TaxCountry::US then begin
                            "Round Tax" := TaxArea."Round Tax";
                            TaxJurisdiction.Get("Tax Jurisdiction Code");
                            "Is Report-to Jurisdiction" := ("Tax Jurisdiction Code" = TaxJurisdiction."Report-to Jurisdiction");
                        end;
                        SalesTaxAmountLineCalc.SetTaxBaseAmount(
                            TempSalesTaxLine, PurchLine."Line Amount" - PurchLine."Inv. Discount Amount", ExchangeFactor, false);
                        "Line Amount" := PurchLine."Line Amount" / ExchangeFactor;
                        "Tax Liable" := PurchLine."Tax Liable";
                        "Use Tax" := PurchLine."Use Tax";
                        SetTaxDetailFilter(TaxDetail, "Tax Jurisdiction Code", "Tax Group Code", PurchHeader."Posting Date");
                        if "Use Tax" then
                            TaxDetail.SetFilter("Tax Type", '%1|%2', TaxDetail."Tax Type"::"Sales and Use Tax",
                              TaxDetail."Tax Type"::"Use Tax Only")
                        else
                            TaxDetail.SetFilter("Tax Type", '%1|%2', TaxDetail."Tax Type"::"Sales and Use Tax",
                              TaxDetail."Tax Type"::"Sales Tax Only");

                        if TaxDetail.FindLast then
                            "Expense/Capitalize" := TaxDetail."Expense/Capitalize";

                        "Calculation Order" := TaxAreaLine."Calculation Order";
                        Quantity := PurchLine."Quantity (Base)";
                        "Invoice Discount Amount" := PurchLine."Inv. Discount Amount";
                        Insert;
                    end else begin
                        "Line Amount" := "Line Amount" + (PurchLine."Line Amount" / ExchangeFactor);
                        "Tax Liable" := PurchLine."Tax Liable";
                        SalesTaxAmountLineCalc.SetTaxBaseAmount(
                            TempSalesTaxLine, PurchLine."Line Amount" - PurchLine."Inv. Discount Amount", ExchangeFactor, true);
                        "Tax Amount" := 0;
                        Quantity := Quantity + PurchLine."Quantity (Base)";
                        "Invoice Discount Amount" := "Invoice Discount Amount" + PurchLine."Inv. Discount Amount";
                        Modify;
                    end;
                until TaxAreaLine.Next() = 0;
        end;

        OnAfterAddPurchLine(TempSalesTaxLine, PurchLine, PurchHeader, ExchangeFactor);
    end;
    
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetFilterTempSalesTaxLineOnAddPurchLine(var TempSalesTaxLine: Record "Sales Tax Amount Line" temporary;)
    begin
    end;``

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
