### ISSUE TITLE
[Typo] OnGeforeGetMyFilterText

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#11894]
codeunit 9150 "My Records Filter Sub."
OnGeforeGetMyFilterText must be OnBeforeGetMyFilterText

![image](https://user-images.githubusercontent.com/25268332/113413808-c8aed300-93bb-11eb-9a42-8c51b8781947.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
