### ISSUE TITLE
[Request-for-External] CodeUnit 99000757 - Update Prod Order Cost - ModifyFor

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#11895]
Hi, would it be possible to modify the procedure ModifyFor in codeunit 99000757 from local to external ? 

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
