### ISSUE TITLE
[Event Request] Codeunit 5703 Catalog Item Management - OnCreateNewItemOnBeforeInsertItem

### ISSUE THREAD

**Issue by vinpicci** [microsoft/ALAppExtensions#11900]
[Event Request]
Object: Codeunit 5703 Catalog Item Management
Procedure: CreateNewItem(ItemNo: Code[20]; NonstockItem: Record "Nonstock Item")
Event: OnCreateNewItemOnBeforeInsertItem(var Item: Record Item; NonstockItem: Record "Nonstock Item")

    .........
    local procedure CreateNewItem(ItemNo: Code[20]; NonstockItem: Record "Nonstock Item")
    var
        Item: Record Item;
    begin
        .........
        Item."Manufacturer Code" := NonstockItem."Manufacturer Code";
        Item."Created From Nonstock Item" := true;
        OnCreateNewItemOnBeforeInsertItem(Item, NonstockItem);
        Item.Insert();

        OnAfterCreateNewItem(Item);
    end;
    ..........

Could you please add this event?

Tks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
