### ISSUE TITLE
[Event Request] Table 99000850 "Planning Assignment" - OnBeforeChkAssignOne

### ISSUE THREAD

**Issue by teddyhacumen** [microsoft/ALAppExtensions#11909]
Hi,

Can we add a new event request before ChkAssignOne on Table 99000850 "Planning Assignment" ?

procedure ChkAssignOne(ItemNo: Code[20]; VariantCode: Code[10]; LocationCode: Code[10]; UpdateDate: Date)
    var
        Item: Record Item;
        SKU: Record "Stockkeeping Unit";
        ReorderingPolicy: Enum "Reordering Policy";
        IsHandled: Boolean; //New
    begin
        OnBeforeChkAssignOne(ItemNo, VariantCode, LocationCode, UpdateDate,IsHandled);  //New
        if IsHandled then  //New
            exit;  //New

        ReorderingPolicy := Item."Reordering Policy"::" ";

        if SKU.Get(LocationCode, ItemNo, VariantCode) then
            ReorderingPolicy := SKU."Reordering Policy"
        else
            if Item.Get(ItemNo) then
                ReorderingPolicy := Item."Reordering Policy";

        if ReorderingPolicy <> Item."Reordering Policy"::" " then
            AssignOne(ItemNo, VariantCode, LocationCode, UpdateDate);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
