### ISSUE TITLE
[Event Request] Table 5900 "Service Header" - OnBeforeValidateAppliesToDocNo

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#11906]
Request a new event in field "Applies-to Doc. No." trigger OnValidate in table 5900 "Service Header":

        field(53; "Applies-to Doc. No."; Code[20])
        {
            ...

            trigger OnValidate()
            var
                IsHandled: Boolean    //NEW
            begin
                //<NEW>
                IsHandled := false
                OnBeforeValidateAppliesToDocNo(Rec, xRec, CustLedgEntry, IsHandled);
                if IsHandled then
                    exit;                
                //</NEW>
            ...                
            end;
        }

    //<NEW>
    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateAppliesToDocNo(var ServiceHeader: Record "Service Header"; xServiceHeader: Record "Service Header"; var CustLedgEntry: Record "Cust. Ledger Entry"; var IsHandled: Boolean);
    begin
    end;
    //</NEW>

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
