### ISSUE TITLE
[Event Request] Table 83 "Item Journal Line" - OnValidateItemNoOnBeforeIndirectCostPrct

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11912]
Hi, in the Table 83 "Item Journal Line", in the field 3 "Item No.", in the trigger OnValidate, we would like to add our code in a specific place. To do so, we would need an event publisher here:

                if ("Value Entry Type" <> "Value Entry Type"::"Direct Cost") or
                   ("Item Charge No." <> '')
                then begin
                    if "Item No." <> xRec."Item No." then begin
                        TestField("Partial Revaluation", false);
                        RetrieveCosts;

                        OnValidateItemNoOnBeforeIndirectCostPrct(Rec, Item);

                        "Indirect Cost %" := 0;
                        "Overhead Rate" := 0;
                        "Inventory Value Per" := "Inventory Value Per"::" ";
                        Validate("Applies-to Entry", 0);
                        "Partial Revaluation" := false;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnValidateItemNoOnBeforeIndirectCostPrct(var ItemJournalLine: Record "Item Journal Line"; var Item: Record Item)
    begin
    end;

I thought about using the OnBeforeRetrieveCosts or OnRetrieveCostsOnAfterSetUnitCost events, but the procedure RetrieveCosts is called several times in the field 3. Or I want to add my code at just one place, not after every time RetrieveCosts is called.

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
