### ISSUE TITLE
[Request-for-external] Table 7000019 Fee Range - GetTotalPmtOrdCollExpensesAmt

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#11917]
Can you remove [Scope('OnPrem')] from procedure GetTotalPmtOrdCollExpensesAmt in Table 7000019 Fee Range?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
