### ISSUE TITLE
[Permission Request] on Table 36 "Sales Header"

### ISSUE THREAD

**Issue by teddyhacumen** [microsoft/ALAppExtensions#11910]
Hi,

Can we add modify permission for table 900 "Assembly Header" on Table 36 "Sales Header" ?
I need to have indirect modify permission for team member license.

Currently when a team member update the posting date on Sales Header, it will cause the error on Assembly Header modify.

Thanks,

Teddy

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
