### ISSUE TITLE
[Event Request] Table 83 "Item Journal Line" - OnValidateItemNoOnAfterCalcUnitAmount

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11929]
Hello, in the Table 83 "Item Journal Line", in the field 3 "Item No.", in the trigger OnValidate, I would like to use the event publisher OnValidateItemNoOnAfterCalcUnitAmount(Rec) to add my code. But I need two more parameters : WorkCenter and MachineCenter. Like this : 

                if (("Entry Type" = "Entry Type"::Output) and (WorkCenter."No." = '') and (MachineCenter."No." = '')) or
                   ("Entry Type" <> "Entry Type"::Output) or
                   ("Value Entry Type" = "Value Entry Type"::Revaluation)
                then
                    "Gen. Prod. Posting Group" := Item."Gen. Prod. Posting Group";

                case "Entry Type" of
                    "Entry Type"::Purchase,
                    "Entry Type"::Output,
                    "Entry Type"::"Assembly Output":
                        ApplyPrice(PriceType::Purchase, FieldNo("Item No."));
                    "Entry Type"::"Positive Adjmt.",
                    "Entry Type"::"Negative Adjmt.",
                    "Entry Type"::Consumption,
                    "Entry Type"::"Assembly Consumption":
                        "Unit Amount" := UnitCost;
                    "Entry Type"::Sale:
                        ApplyPrice(PriceType::Sale, FieldNo("Item No."));
                    "Entry Type"::Transfer:
                        begin
                            "Unit Amount" := 0;
                            "Unit Cost" := 0;
                            Amount := 0;
                        end;
                end;
                OnValidateItemNoOnAfterCalcUnitAmount(Rec, WorkCenter, MachineCenter);

Event integration : 

    local procedure OnValidateItemNoOnAfterCalcUnitAmount(var ItemJournalLine: Record "Item Journal Line"; WorkCenter: Record "Work Center"; MachineCenter: Record "Machine Center")

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
