### ISSUE TITLE
[Request-for-external] Report 7000085 Partial Settl. - Payable - SetInitValue

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#11928]
Can you remove [Scope('OnPrem')] from procedure SetInitValue in Report 7000085 Partial Settl. - Payable?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
