### ISSUE TITLE
[Event Request] Table 38 Purchase Header - Function RecreateTempPurchLines

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11939]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 38 - Function RecreateTempPurchLines, of course without the prefix DIN.

    local procedure RecreateTempPurchLines(var TempPurchLine: Record "Purchase Line")
    begin
        repeat
            TestPurchLineFieldsBeforeRecreate();
            TempPurchLine := PurchLine;
            if PurchLine.Nonstock then begin
                PurchLine.Nonstock := false;
                PurchLine.Modify();
            end;
            OnRecreatePurchLinesOnBeforeTempPurchLineInsert(TempPurchLine, PurchLine);
            TempPurchLine.Insert();
            OnRecreateTempPurchLinesOnAfterTempPurchLineInsert(Rec);
            // DINNL <<
            DINOnRecreatePurchLinesOnAfterTempPurchLineInsert(TempPurchLine, PurchLine);
            // DINNL >>	    
        until PurchLine.Next() = 0;
    end;

local procedure DINOnRecreatePurchLinesOnAfterTempPurchLineInsert(var TempPurchaseLine: Record "Purchase Line" temporary; PurchaseLine: Record "Purchase Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
