### ISSUE TITLE
[Request-for-external] Page 9223 "Item Statistics Matrix" - InsertRow / SetCommonFilters / SetFilters

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11933]
Dear ALAppExtensions Team,

We would like to request the following : Is it possible to change the functions InsertRow / SetCommonFilters / SetFilters in Page 9223 from [Local] to [External] ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
