### ISSUE TITLE
[Event Request] Page 5050 Contact - OnAssistEdit Name

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11931]
Dear ALAppExtensions Team,

We would like to request the following event publisher in page 5050 - OnAssistEdit Name , of course without the prefix DIN.

          trigger OnAssistEdit()
          var
              Contact: Record Contact;
          begin
              CurrPage.SaveRecord();
              Commit();

              Contact := Rec;
              Contact.SetRecFilter();
              // DINNL <<
              DINNameOnAssistEdit(Contact, DINIsHandled);
              if not DINIsHandled then
              // DINNL <<
              if Contact.Type = Contact.Type::Person then begin
                      Clear(NameDetails);
                      NameDetails.SetTableView(Contact);
                      NameDetails.SetRecord(Contact);
                      NameDetails.RunModal;
                  end else begin
                      Clear(CompanyDetails);
                      CompanyDetails.SetTableView(Contact);
                      CompanyDetails.SetRecord(Contact);
                      CompanyDetails.RunModal;
                  end;
              Rec := Contact;
              CurrPage.Update(false);
          end;

local procedure DINNameOnAssistEdit(var Contact: Record Contact; var DINIsSHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
