### ISSUE TITLE
[Event Request] Page 99000914 Change Production Order Status - OnAction "Change Status"

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11935]
Dear ALAppExtensions Team,

We would like to request the following event publisher in page 99000914 - OnAction "Change Status" , of course without the prefix DIN.

              begin
                  ChangeStatusForm.Set(Rec);

                  if ChangeStatusForm.RunModal <> ACTION::Yes then
                      exit;

                  ChangeStatusForm.ReturnPostingInfo(NewStatus, NewPostingDate, NewUpdateUnitCost);

                  NoOfRecords := Count;

                  Window.Open(
                    StrSubstNo(Text000, SelectStr(NewStatus.AsInteger() + 1, LocalText000)) +
                    Text001);

                  POCount := 0;

                  if Find('-') then
                      repeat
                          POCount := POCount + 1;
                          Window.Update(1, "No.");
                          Window.Update(2, Round(POCount / NoOfRecords * 10000, 1));
                          // DINNL <<
                          DINOnBeforeChangeStatusOnProdOrder(Rec, NewStatus, NewPostingDate, NewUpdateUnitCost, DINIsHandled);
                          if not DINIsHandled then
                              // DINNL >>
                          ProdOrderStatusMgt.ChangeProdOrderStatus(Rec, NewStatus, NewPostingDate, NewUpdateUnitCost);
                          Commit();
                      until Next() = 0;
              end;

local procedure DINOnBeforeChangeStatusOnProdOrder(ProductionOrder: Record "Production Order"; NewStatus: Option Quote,Planned,"Firm Planned",Released,Finished; NewPostingDate: Date; NewUpdateUnitCost: Boolean; var DINIsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
