### ISSUE TITLE
[Event Request] Table 36 Sales Header -  Function RecreateSalesLinesHandleSupplementTypes

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11938]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 36  - Function RecreateSalesLinesHandleSupplementTypes, of course without the prefix DIN.

        if TempSalesLine."Attached to Line No." = 0 then begin
            CreateSalesLine(TempSalesLine);
            ExtendedTextAdded := false;
            OnAfterRecreateSalesLine(SalesLine, TempSalesLine);

            if SalesLine.Type = SalesLine.Type::Item then
                RecreateSalesLinesFillItemChargeAssignment(SalesLine, TempSalesLine, TempItemChargeAssgntSales);

            if SalesLine.Type = SalesLine.Type::"Charge (Item)" then begin
                TempInteger.Init();
                TempInteger.Number := SalesLine."Line No.";
                TempInteger.Insert();
            end;
        end else
            if not ExtendedTextAdded then begin
                TransferExtendedText.SalesCheckIfAnyExtText(SalesLine, true);
                TransferExtendedText.InsertSalesExtText(SalesLine);
                OnAfterTransferExtendedTextForSalesLineRecreation(SalesLine, TempSalesLine);

                SalesLine.FindLast();
                ExtendedTextAdded := true;
            end;
        // DINNL <<
        DINOnAfterRecreateSalesLinesHandleSupplementTypes(Rec);
        // DINNL >>

    local procedure DINOnAfterRecreateSalesLinesHandleSupplementTypes(var SalesHeader: Record "Sales Header")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
