### ISSUE TITLE
Change variables to Protected on several pages.

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#11932]
Requesting variable ShortcutDimCode be set to Protected on the following pages:

284 "Allocations"
36723 "Bank Rec. Adj. Lines"
10123 "Bank Rec. Adj. Lines Subform"
10141 "Deposit Subform"
10128 "Posted Bank Rec. Adj Lines Sub"
10029 "Sales Order Invoice Subform"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
