### ISSUE TITLE
codeunit "Create Prod. Order Lines" event OnBeforeInsertProdOrderLine

### ISSUE THREAD

**Issue by josejggil** [microsoft/ALAppExtensions#11937]
Currently the definition is

![image](https://user-images.githubusercontent.com/47104041/113722564-d84a5680-96f0-11eb-8846-97ba9c400e6e.png)

I propose 

![image](https://user-images.githubusercontent.com/47104041/113722770-0760c800-96f1-11eb-95d7-502c26c9c9bf.png)

to be able to modify the InsertNew parameter

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
