### ISSUE TITLE
[Event Request] Page 99000902 Item Availability Line List - Function LookupEntries

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11934]
Dear ALAppExtensions Team,

We would like to request the following event publisher in page 99000902 - Function LookupEntries , of course without the prefix DIN.

    begin
        // DINNL <<
        DINOnBeforeLookupEntries(Item, Rec."Table No.", Rec.QuerySource, DINIsHandled);
        IF DINIshandled then
            exit;
        // DINNL >>

        case "Table No." of
            DATABASE::"Item Ledger Entry":
                begin
                    ItemLedgerEntry.SetCurrentKey("Item No.", "Entry Type", "Variant Code", "Drop Shipment", "Location Code", "Posting Date");
                    ItemLedgerEntry.SetRange("Item No.", Item."No.");
                    ItemLedgerEntry.SetFilter("Variant Code", Item.GetFilter("Variant Filter"));

local procedure DINOnBeforeLookupEntries(var Item: Record Item; TableID: Integer; QuerySource: Integer; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
