### ISSUE TITLE
[Event Request] Application “Tests-User”, Codeunit 134202 "Document Approval - Users"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#11942]
[Event Request]Application “Tests-User”, 134202 "Document Approval - Users"

Could you please insert the OnTestInitialize Event at the beginning the following test procedure:
-	ApproveRequestForPurchBlanketOrder
-	DelegateRequestForPurchBlanketOrder
-	DelegateRequestForPurchCrMemo
-	DelegateRequestForPurchInvoice
-	DelegateRequestForPurchOrder
-	DelegateRequestForPurchQuote
-	DelegateRequestForPurchReturnOrder
-	ModifyApprovedSalesQuote
-	ApproveRequestWithCommentForSalesQuoteAndMakeOrder
![pic1](https://user-images.githubusercontent.com/45795262/113735020-20bb4180-96fc-11eb-9882-8e095c442f19.png)

**Comment by StanPesotskiy** [comment]
ApproveRequestForPurchBlanketOrder runs ApproveRequestForPurchDocument that starts from Initialize() that runs LibraryTestInitialize.OnTestInitialize(Codeunit::"Document Approval - Users"); 
Isn't it enough?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
