### ISSUE TITLE
[Event Request] Table 336 Tracking Specification - Function CheckSerialNoQty

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11944]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 336 - Function CheckSerialNoQty, of course without the prefix DIN.

    local procedure CheckSerialNoQty()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckSerialNoQty(Rec, IsHandled);
        if IsHandled then
            exit;

        if SkipSerialNoQtyValidation then
            exit;

        if "Serial No." = '' then
            exit;
        if not ("Quantity (Base)" in [-1, 0, 1]) then
            Error(Text003, FieldCaption("Quantity (Base)"), FieldCaption("Serial No."));
        if not ("Qty. to Handle (Base)" in [-1, 0, 1]) then
            Error(Text003, FieldCaption("Qty. to Handle (Base)"), FieldCaption("Serial No."));
        if not ("Qty. to Invoice (Base)" in [-1, 0, 1]) then
            Error(Text003, FieldCaption("Qty. to Invoice (Base)"), FieldCaption("Serial No."));
        // DINNL <<
        DINOnAfterCheckSerialNoQty(Rec);
        // DINNL >>
    end;

local procedure DINOnAfterCheckSerialNoQty(var TrackingSpecification: Record "Tracking Specification")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
