### ISSUE TITLE
[Request-for-external] Table 5900 "Service Header" - MessageIfServLinesExist

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11949]
Dear ALAppExtensions Team,

We would like to request the following : Is it possible to change the function MessageIfServLinesExist in Table 5900 from [Local] to [External] ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
