### ISSUE TITLE
[Function Expose] Page 233 - Apply Vendor Entries - CalcApplnAmount

### ISSUE THREAD

**Issue by rvanbekkum** [Microsoft/ALAppExtensions#1194]
Dear ALAppExtensions team,

With this issue we would like to request procedure `CalcApplnAmount` in page 233 Apply Vendor Entries to be exposed (global + external) conform page 232 Apply Customer Entries where this procedure is external as well.

**Comment by darjoo** [comment]
Hi @rvanbekkum,
The function you have requested has been exposed and will be available in a future release.
