### ISSUE TITLE
[Event Request] Table 27, Field 7380 "Phys Invt Counting Period Code": OnBeforePhysInvtCountingPeriodCodeErrorMessage

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#11940]
Hello, would it be possible to get an event OnBeforePhysInvtCountingPeriodCodeErrorMessage (with IsHandle) in Table 27 Field 7380 "Phys Invt Counting Period Code":

        field(7380; "Phys Invt Counting Period Code"; Code[10])
        {
            Caption = 'Phys Invt Counting Period Code';
            TableRelation = "Phys. Invt. Counting Period";

            trigger OnValidate()
            var
                PhysInvtCountPeriod: Record "Phys. Invt. Counting Period";
                PhysInvtCountPeriodMgt: Codeunit "Phys. Invt. Count.-Management";
            begin
                if ("Phys Invt Counting Period Code" <> '') and
                   ("Phys Invt Counting Period Code" <> xRec."Phys Invt Counting Period Code")
                then begin
                    PhysInvtCountPeriod.Get("Phys Invt Counting Period Code");
                    PhysInvtCountPeriod.TestField("Count Frequency per Year");
                    **IsHandled := false;
                    OnBeforePhysInvtCountingPeriodCodeErrorMessage(Rec, xRec, PhysInvtCountPeriod, IsHandled);
                    if not IsHandled then**
                        if xRec."Phys Invt Counting Period Code" <> '' then
                            if CurrFieldNo <> 0 then
                                if not Confirm(
                                     Text7380,
                                     false,
                                     FieldCaption("Phys Invt Counting Period Code"),
                                     FieldCaption("Next Counting Start Date"),
                                     FieldCaption("Next Counting End Date"))
                                then
                                    Error(Text7381);

                    if "Last Counting Period Update" = 0D then
                        PhysInvtCountPeriodMgt.CalcPeriod(
                          "Last Counting Period Update", "Next Counting Start Date", "Next Counting End Date",
                          PhysInvtCountPeriod."Count Frequency per Year");
                end else begin
                    if CurrFieldNo <> 0 then
                        if not Confirm(Text003, false, FieldCaption("Phys Invt Counting Period Code")) then
                            Error(Text7381);
                    "Next Counting Start Date" := 0D;
                    "Next Counting End Date" := 0D;
                    "Last Counting Period Update" := 0D;
                end;
            end;
        }

    [IntegrationEvent(false, false)]
    local procedure OnBeforePhysInvtCountingPeriodCodeErrorMessage(var Rec: Record Item; xRec: Record Item; PhysInvtCountPeriod: Record "Phys. Invt. Counting Period"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
