### ISSUE TITLE
[Event Request] Table 5406 Prod. Order Line - Function DeleteRelations

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11947]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 5406 - Function DeleteRelations, of course without the prefix DIN.

    begin
        OnBeforeDeleteRelations(Rec);

        ProdOrderLine.SetRange(Status, Status);
        ProdOrderLine.SetRange("Prod. Order No.", "Prod. Order No.");
        ProdOrderLine.SetRange("Routing No.", "Routing No.");
        ProdOrderLine.SetFilter("Line No.", '<>%1', "Line No.");
        ProdOrderLine.SetRange("Routing Reference No.", "Routing Reference No.");
        if not ProdOrderLine.FindFirst then begin
            ProdOrderRoutingLine.SetRange(Status, Status);
            ProdOrderRoutingLine.SetRange("Prod. Order No.", "Prod. Order No.");
            ProdOrderRoutingLine.SetRange("Routing No.", "Routing No.");
            ProdOrderRoutingLine.SetRange("Routing Reference No.", "Routing Reference No.");
            if ProdOrderRoutingLine.FindSet(true) then
                repeat
                    ProdOrderRoutingLine.SetSkipUpdateOfCompBinCodes(true);
                    ProdOrderRoutingLine.Delete(true);
                until ProdOrderRoutingLine.Next() = 0;
        end;

        ProdOrderComp.Reset();
        ProdOrderComp.SetRange(Status, Status);
        ProdOrderComp.SetRange("Prod. Order No.", "Prod. Order No.");
        ProdOrderComp.SetRange("Prod. Order Line No.", "Line No.");
        // DINNL <<
        DINDeleteRelationsOnBeforeProdOrderCompDeleteAll(ProdOrderComp, Blocked, DINIsHandled);
        if not DINIsHandled then
        // DINNL >>
        ProdOrderComp.DeleteAll(true);

        if not CalledFromComponent then begin
            ProdOrderComp.SetRange("Prod. Order Line No.");
            ProdOrderComp.SetRange("Supplied-by Line No.", "Line No.");
            OnDeleteRelationsNotCalledFromComponentFilter(Rec, ProdOrderComp);

local procedure DINDeleteRelationsOnBeforeProdOrderCompDeleteAll(var ProdOrderComponent: Record "Prod. Order Component"; Blocked: Boolean; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
