### ISSUE TITLE
[Event Request] Table 5406 Prod. Order Line - Add parameters to function OnBeforeUpdateProdOrderComp

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11948]
Dear ALAppExtensions Team,

Is it possible to add parameters to function OnBeforeUpdateProdOrderComp in Table 5406 ?

- OnBeforeUpdateProdOrderComp(Rec, QtyPerUnitOfMeasure, CurrFieldNo, IsHandled);
+OnBeforeUpdateProdOrderComp(Rec, QtyPerUnitOfMeasure, CurrFieldNo, IsHandled,ProdOrderComp, Blocked);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
