### ISSUE TITLE
[Event Request] Table 338 Entry Summary - Function UpdateAvailable

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11946]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 338 - Function UpdateAvailable, of course without the prefix DIN.

    procedure UpdateAvailable()
    begin
        "Total Available Quantity" :=
          "Total Quantity" -
          "Total Requested Quantity" -
          "Current Pending Quantity" +
          "Double-entry Adjustment";
        // DINNL <<
        DINOnAfterUpdateAvailable(Rec);
        // DINNL >>
    end;

local procedure DINOnAfterUpdateAvailable(var EntrySummary: Record "Entry Summary")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
