### ISSUE TITLE
[Bug] Table 6550 LookupTrackingSummary

### ISSUE THREAD

**Issue by Bleika** [microsoft/ALAppExtensions#1195]
Hi,

The function LookupTrackingSummary in Table 6550 is used to provide for AssistEdit on Item Tracking for tables 7311 "Warehouse Journal Line" and 7326 "Warehouse Worksheet Line".

Table 5767 "Warehouse Activity Line" has its own LookupTrackingSummary function which works correctly and the user can clearly see what Lots/Serial Nos. are stocked in the Bin.

As to T7311 & T7326, if the user introduces a Bin Code before opening the Item Tracking lines, there's already functionality in place to update the available quantity by Item Tracking for that bin.
However, there are important lines of code missing, so the process looses sight of the Bin Code.
Also: ReclassJnlLines use "From Bin Code" instead of "Bin Code".

Please apply the following code fixes to LookupTrackingSummary in Table 6550 to fix this and provide a better lookup experience for users:

Fix no. 1 (treat ReclassJnl) T6550:
**[External] LookUpTrackingSummary(VAR WhseItemTrackingLine : Record "Whse. Item Tracking Line";TrackingType : 'SerialNo,LotNo';MaxQuantity : Decimal;SignFactor : Integer;SearchForSupply : Boolean)**
IsHandled := FALSE;
OnBeforeLookUpTrackingSummary(WhseItemTrackingLine,0,MaxQuantity,-1,TRUE,IsHandled);
IF IsHandled THEN
  EXIT;

WITH WhseItemTrackingLine DO BEGIN
  CASE "Source Type" OF
    DATABASE::"Warehouse Journal Line":
      BEGIN
        WhseJnlLine.GET("Source Batch Name","Source ID","Location Code","Source Ref. No.");
        **//-NEW CODE**
        IF WhseJnlLine.IsReclass(WhseJnlLine."Journal Template Name") THEN
          BinCode := WhseJnlLine."From Bin Code"
        ELSE
        **//+NEW CODE**
        BinCode := WhseJnlLine."Bin Code";
      END;
[...]

Fix no. 2 (don't loose sight of BinCode before calling CU6501) T6550:
**[External] LookUpTrackingSummary(VAR WhseItemTrackingLine : Record "Whse. Item Tracking Line";TrackingType : 'SerialNo,LotNo';MaxQuantity : Decimal;SignFactor : Integer;SearchForSupply : Boolean)**
[...]
  TempTrackingSpecification.INIT;  
  TempTrackingSpecification.SetItemData(
    "Item No.",Description,"Location Code","Variant Code",BinCode,"Qty. per Unit of Measure");
  TempTrackingSpecification.SetSource( 
    "Source Type","Source Subtype","Source ID","Source Ref. No.","Source Batch Name","Source Prod. Order Line");
  TempTrackingSpecification."Quantity (Base)" := "Quantity (Base)";
  TempTrackingSpecification."Qty. to Handle" := "Qty. to Handle";
  TempTrackingSpecification."Qty. to Handle (Base)" := "Qty. to Handle (Base)";
  CLEAR(ItemTrackingDataCollection);
  **//-NEW CODE**
  IF NOT Item.GET("Item No.") THEN Item.INIT;
  IF ItemTracking.GET(Item."Item Tracking Code") 
  AND (BinCode <> '') THEN
    ItemTrackingDataCollection.SetCurrentBinAndItemTrkgCode(BinCode,ItemTracking);
  **//+NEW CODE**

Even though COD6501 seems to repeat the same:
ItemTrackingSummaryForm.SetCurrentBinAndItemTrkgCode(CurrBinCode,CurrItemTrackingCode);
the problem is that T5767 calls it with BinCode in scope but T6550 has lost sight of it for T7311/T7326.

_Actually I believe the Parameter for ItemTracking is redundant here: validation will take place upon Lot/Serial No validation, but the important line is the call to CU6501 to set the current bin.
It's shared with T5767.LookupTrackingSummary, so if the ItemTracking parameter is removed, it must also be removed from the call in T5767..._

**Comment by JesperSchulz** [comment]
The following lines make our test suite fail:

IF NOT Item.GET("Item No.") THEN
  Item.INIT;
IF ItemTracking.GET(Item."Item Tracking Code") AND (BinCode <> '') THEN
  ItemTrackingDataCollection.SetCurrentBinAndItemTrkgCode(BinCode,ItemTracking);

Test codeunit 137294 - SCM Inventory Miscellaneous II, test SuggestItemForAdjustmentBin will fail with message "Item tracking lines defined for the source line must account for the same quantity as you have entered." Could you verify that your changes don't have any undesired side effects?

**Comment by AlexanderYakunin** [comment]
Partially implemented.
