### ISSUE TITLE
[Event Request] Table 77 Report Selections - Add new event in FUN GetNextEmailAddressFromCustomReportSelection

### ISSUE THREAD

**Issue by manishs-acumencentral** [microsoft/ALAppExtensions#11953]
Hi Team,

Can you add event in Function GetNextEmailAddressFromCustomReportSelection. The new code will be like this:

LOCAL GetNextEmailAddressFromCustomReportSelection(VAR CustomReportSelection : Record "Custom Report Selection";DefaultEmailAddress : Text;UsageValue : Option;SequenceText : Text) : Text
IF EVALUATE(SequenceInteger,SequenceText) THEN BEGIN
  CustomReportSelection.SETRANGE(Usage,UsageValue);
  CustomReportSelection.SETRANGE(Sequence,SequenceInteger);
  // New Code >>
  OnFindCustomReportSelection(CustomReportSelection);
  // New Code <<
  IF CustomReportSelection.FINDFIRST THEN
    IF CustomReportSelection."Send To Email" <> '' THEN
      EXIT(CustomReportSelection."Send To Email");
END;
EXIT(DefaultEmailAddress);

And the event definition will be like this: Here VAR is important.
LOCAL [IntegrationEvent] OnFindCustomReportSelection(**VAR** CustomReportSelection : Record "Custom Report Selection")

This event allow us to add more filter on Table Custom Report Selection.

Thanks, 
Manish

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
