### ISSUE TITLE
[Event Request] Table 7302 Bin Content - Add parameter to function OnCalcTotalQtyAvailToTakeOnAfterCalcPickQuantityBase

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11951]
Dear ALAppExtensions Team,

Is it possible to add a parameter to function OnCalcTotalQtyAvailToTakeOnAfterCalcPickQuantityBase in Table 7302 ?

- OnCalcTotalQtyAvailToTakeOnAfterCalcPickQuantityBase(Rec, ExcludeQtyBase);
+OnCalcTotalQtyAvailToTakeOnAfterCalcPickQuantityBase(Rec, ExcludeQtyBase, TotalNegativeAdjmtQtyBase);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
