### ISSUE TITLE
[Event Request] Table 6661 Return Receipt Line - Function InsertInvLineFromRetRcptLine

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11950]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 6661 - Function InsertInvLineFromRetRcptLine, of course without the prefix DIN.

            OnAfterCopyFieldsFromReturnReceiptLine(Rec, SalesLine);

            if not ExtTextLine then begin
                IsHandled := false;
                OnInsertInvLineFromRetRcptLineOnBeforeValidateSalesLineQuantity(Rec, SalesLine, IsHandled);
                if not IsHandled then
                    SalesLine.Validate(Quantity, Quantity - "Quantity Invoiced");

                CopySalesLinePriceAndDiscountFromSalesOrderLine(SalesLine, SalesOrderLine);
                // DINNL <<
                DINOnInsertInvLineFromRetRcptLineAfterValidateInvDiscountAmount(SalesLine, SalesOrderLine, Rec, SalesHeader."Prices Including VAT");
                // DINNL >>
            end;
            SalesLine."Attached to Line No." :=
              TransferOldExtLines.TransferExtendedText(
                SalesOrderLine."Line No.",
                NextLineNo,
                "Attached to Line No.");

local procedure DINOnInsertInvLineFromRetRcptLineAfterValidateInvDiscountAmount(var SalesInvoiceLine: Record "Sales Line"; SalesOrderLine: Record "Sales Line"; ReturnReceiptLine: Record "Return Receipt Line"; PricesIncludingVAT: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
