### ISSUE TITLE
[Event Request] Table 7302 Bin Content - Function CalcTotalNegativeAdjmtQtyBase

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#11952]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 7302 - Function CalcTotalNegativeAdjmtQtyBase, of course without the prefix DIN.

    local procedure CalcTotalNegativeAdjmtQtyBase() TotalNegativeAdjmtQtyBase: Decimal
    var
        WarehouseJournalLine: Record "Warehouse Journal Line";
        WhseItemTrackingLine: Record "Whse. Item Tracking Line";
    begin
        WarehouseJournalLine.SetRange("Location Code", "Location Code");
        WarehouseJournalLine.SetRange("From Bin Code", "Bin Code");
        WarehouseJournalLine.SetRange("Item No.", "Item No.");
        WarehouseJournalLine.SetRange("Variant Code", "Variant Code");
        OnCalcTotalNegativeAdjmtQtyBaseOnAfterSetFilters(WarehouseJournalLine, Rec);
        if not TrackingFiltersExist then begin
            WarehouseJournalLine.CalcSums("Qty. (Absolute, Base)");
            TotalNegativeAdjmtQtyBase := WarehouseJournalLine."Qty. (Absolute, Base)";
        end else begin
            WhseItemTrackingLine.SetRange("Location Code", "Location Code");
            WhseItemTrackingLine.SetRange("Item No.", "Item No.");
            WhseItemTrackingLine.SetRange("Variant Code", "Variant Code");
            WhseItemTrackingLine.SetTrackingFilterFromBinContent(Rec);
            WhseItemTrackingLine.SetRange("Source Type", DATABASE::"Warehouse Journal Line");
            if WarehouseJournalLine.FindSet then
                repeat
                    WhseItemTrackingLine.SetRange("Source ID", WarehouseJournalLine."Journal Batch Name");
                    WhseItemTrackingLine.SetRange("Source Batch Name", WarehouseJournalLine."Journal Template Name");
                    WhseItemTrackingLine.SetRange("Source Ref. No.", WarehouseJournalLine."Line No.");
                    WhseItemTrackingLine.CalcSums("Quantity (Base)");
                    TotalNegativeAdjmtQtyBase += WhseItemTrackingLine."Quantity (Base)";
                until WarehouseJournalLine.Next() = 0;
        end;
        // DINNL <<
        DINOnAfterCalcTotalNegativeAdjmtQtyBase(Rec, WarehouseJournalLine, TotalNegativeAdjmtQtyBase);
        // DINNL >>
    end;

local procedure DINOnAfterCalcTotalNegativeAdjmtQtyBase(var BinContent: Record "Bin Content"; var WarehouseJournalLine: Record "Warehouse Journal Line"; var TotalNegativeAdjmtQtyBase: Decimal)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
