### ISSUE TITLE
[Event Request] Purchase Line Table, location code OnValidate - what happend to UpdateDirectUnitCostByField()?

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#11954]
in 17.4, "Location Code" - OnValidate had this line at the END of the OnValidate:

364-                UpdateDirectUnitCostByField(FieldNo("Location Code"));

Now instead, in 17.5, we see these lines (which run the same code already within UpdateDirectUnitCostByField):

297                  "Bin Code" := '';
298
299+                GetPurchHeader();
300+                GetPriceCalculationHandler(PurchHeader, PriceCalculation);
301+                if not ("Copied From Posted Doc." and IsCreditDocType()) then 
302+                    PriceCalculation.ApplyPrice(FieldNo("Location Code"));
303+                GetLineWithCalculatedPrice(PriceCalculation);
304+                Validate("Direct Unit Cost");
305 
306                  PurchSetup.Get();

*ALSO WITHIN* procedure UpdateDirectUnitCostByField was the event OnUpdateDirectUnitCostBeforeFindPrice.

Now in 17.5 I can now no longer control DirectUnitCost when "Location Code" changes because it does not call UpdateDirectUnitCostByField and it does not go through the event OnUpdateDirectUnitCostBeforeFindPrice().

Why was this done? Can we return to 17.4? Otherwise, can we put a new event in front of lines 299-303? with an OnHandled var parameter? so I can skip lines 299-303?

See Suggestion below for new event OnBeforeValidateDirectUnitCostOnValidateLocationCode:

297                  "Bin Code" := '';
298
++                   OnBeforeValidateDirectUnitCostOnValidateLocationCode(Rec, IsHandled);
++                   If not IsHandled then begin
299+                    GetPurchHeader();
300+                    GetPriceCalculationHandler(PurchHeader, PriceCalculation);
301+                    if not ("Copied From Posted Doc." and IsCreditDocType()) then 
302+                        PriceCalculation.ApplyPrice(FieldNo("Location Code"));
303+                    GetLineWithCalculatedPrice(PriceCalculation);
++                  end;
304+               Validate("Direct Unit Cost");
305 
306                  PurchSetup.Get();

**Comment by StanPesotskiy** [comment]
This is a known issue. This change was incorrect and will be reverted. Working on it. There will be a hotfix for 17.5 and later versions.

**Comment by AndreiPanko** [comment]
@grantbrimhall do you have extension that updates prices/discounts based on location? Because standard product doesn't not so from this perspective we should not trigger UpdateDirectUnitCostByField function at all as it resets manual changes to prices/discounts when user changes location code.

**Comment by grantbrimhall** [comment]
Hi:

We have a client that writes purchase orders for items that have very fluid market pricing (so a purchase price table or last direct cost never are useful, and in fact cause errors after a quote price has been firmed on the purchase document).

I have used the OnUpdateDirectUnitCostBeforeFindPrice() event (called from within the UpdateDirectUnitCostByField procedure) on "No." to set "Direct Unit Cost" to $0, and on "Location Code" and Quantity to do nothing to "Direct Unit Cost" (essentially IsHandled = true).

With the latest change to 17.5, since the "Location Code" OnValidate code no longer calls UpdateDirectUnitCostByField (and therefore has no path through OnUpdateDirectUnitCostBeforeFindPrice() Event), any time they change the "Location Code" they lose the quote price they have already stored on the Purchase document (and it reverts to Last direct Cost).

I got a note yesterday from Sam Pesotskiy that said this was a mistake to make this change in the code, and that it will be reverted. Is that no longer the case?

-Grant

Grant Brimhall
SENIOR ERP ARCHITECT
O: 385.381.2822  |  M: 801.717.5712
JourneyTEAM  |  www.journeyteam.com<https://nam04.safelinks.protection.outlook.com/?url=www.journeyteam.com&data=02%7C01%7Cgrant.brimhall%40journeyteam.com%7C0d64a5c8884e43335d4e08d7c5154eab%7Cb59c07c69496463aab8177697ac73d11%7C1%7C0%7C637194568818019651&sdata=p25w61X7xEz2kxQ5op6W8AQjaTwqh7Q5%2B7ehnRN6lhA%3D&reserved=0>

***@***.***D73107.B2B1D550]

**Comment by AndreiPanko** [comment]
@grantbrimhall 
Thank you for the fast reply and explanation about your scenario.
The change you saw in 17.5 will be reverted as it caused some issues with subcontracting. However, the change was introduced to solve another problem when system reverts manually set discounts/direct cost when user changed the location, that sounds similar to your scenario.

**Comment by grantbrimhall** [comment]
Ok. I think as long as there is an Event with IsHandled that will allow me to sidestep a recalculation of Direct Unit Cost during Location Code OnValidate, then I (and the client) will be happy.

-Grant

Grant Brimhall
SENIOR ERP ARCHITECT
O: 385.381.2822  |  M: 801.717.5712
JourneyTEAM  |  www.journeyteam.com<https://nam04.safelinks.protection.outlook.com/?url=www.journeyteam.com&data=02%7C01%7Cgrant.brimhall%40journeyteam.com%7C0d64a5c8884e43335d4e08d7c5154eab%7Cb59c07c69496463aab8177697ac73d11%7C1%7C0%7C637194568818019651&sdata=p25w61X7xEz2kxQ5op6W8AQjaTwqh7Q5%2B7ehnRN6lhA%3D&reserved=0>

***@***.***D7311E.C3A26A20]

**Comment by grantbrimhall** [comment]
Is there an estimated time frame when this will be reverted back? is the long run solution to put UpdateDirectUnitCostByField() back into Location Code OnValidate?

**Comment by StanPesotskiy** [comment]
The deployment of the fix to 17.5 and 18.0 is in the progress since April 16.  Should be finished in a few days.
