### ISSUE TITLE
[Event Request] Application “Tests-SCM”, Codeunit 137266 "SCM Package Tracking Transfer"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#11969]
[Event Request] Application “Tests-SCM”, 137266 "SCM Package Tracking Transfer"

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize():
![pic1](https://user-images.githubusercontent.com/45795262/114013937-609f3780-9868-11eb-9179-d3df2772b45c.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
