### ISSUE TITLE
[Event Request] Table 83 "Item Journal Line" - OnSetUpNewLineOnAfterFindItemJnlLine

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11965]
Hello, in the Table 83 "Item Journal Line", in the procedure SetUpNewLine, I would like to use the event publisher OnSetUpNewLineOnAfterFindItemJnlLine to add my code. But I need one more parameter : LastItemJnlLine, the parameter received by the procedure SetUpNewLine . Like this :

    procedure SetUpNewLine(LastItemJnlLine: Record "Item Journal Line")
    begin
        MfgSetup.Get();
        ItemJnlTemplate.Get("Journal Template Name");
        ItemJnlBatch.Get("Journal Template Name", "Journal Batch Name");
        ItemJnlLine.SetRange("Journal Template Name", "Journal Template Name");
        ItemJnlLine.SetRange("Journal Batch Name", "Journal Batch Name");
        if ItemJnlLine.FindFirst then begin
            OnSetUpNewLineOnAfterFindItemJnlLine(Rec, ItemJnlLine, LastItemJnlLine);

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnSetUpNewLineOnAfterFindItemJnlLine(var ItemJournalLine: Record "Item Journal Line"; var FirstItemJournalLine: Record "Item Journal Line"; var LastItemJnlLine: Record "Item Journal Line")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
