### ISSUE TITLE
Possible bug - cannot choose the row on the list page with the field setting with multi-line

### ISSUE THREAD

**Issue by RED-Lin** [microsoft/ALAppExtensions#11966]
We create an extension for our customers.

There is a list page with a field that has multi-line property.
When the user trying to select the second row on the page, the system selects the third row.

Could you help to fix this?

![image](https://user-images.githubusercontent.com/54092477/113967912-9d692f80-9864-11eb-9a47-a7e23be1d565.png)
![image](https://user-images.githubusercontent.com/54092477/113968026-d903f980-9864-11eb-9954-4edfdb36b226.png)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
