### ISSUE TITLE
[Event Request] Table 37 Sales Line - OnShowNonstockOnBeforeCatalogItemListPageRun

### ISSUE THREAD

**Issue by vinpicci** [microsoft/ALAppExtensions#11967]
[Event Request]
Object: Table 37 Sales Line
Procedure: ShowNonstock()
Event: OnShowNonstockOnBeforeCatalogItemListPageRun(var SalesLine: Record "Sales Line"; var NonstockItem: Record "Nonstock Item")

    .........
    procedure ShowNonstock()
    begin
        TestField(Type, Type::Item);
        if "No." <> '' then
            Error(SelectNonstockItemErr);
        OnShowNonstockOnBeforeCatalogItemListPageRun(Rec, NonstockItem);
        if PAGE.RunModal(PAGE::"Catalog Item List", NonstockItem) = ACTION::LookupOK then begin
            CheckNonstockItemTemplate(NonstockItem);
     
            "No." := NonstockItem."Entry No.";
            CatalogItemMgt.NonStockSales(Rec);
            Validate("No.", "No.");
            UpdateUnitPriceFromNonstockItem();

            OnAfterShowNonStock(Rec, NonstockItem);
        end;
    end;
    ..........

Could you please add this event?

Tks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
