### ISSUE TITLE
[Event Request] Application “Tests-SCM”, Codeunit 137268 "SCM Package Tracking Fixes"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#11968]
[Event Request]Application “Tests-SCM”, 137268 "SCM Package Tracking Fixes"

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize():
![pic1](https://user-images.githubusercontent.com/45795262/114013591-fd150a00-9867-11eb-9ef8-734f5ee827e2.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
