### ISSUE TITLE
[Event Request] Table 83 "Item Journal Line" - OnvalidateConcurrentCapacityOnAfterCalcTotalTime

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#11961]
Hello, in the Table 83 "Item Journal Line", in the field 5849 "Concurrent Quantity", in the trigger OnValidate, I would like to use the event publisher OnvalidateConcurrentCapacityOnAfterCalcTotalTime to add my code. But I need one more parameter : xRec. Like this :

        field(5849; "Concurrent Capacity"; Decimal)
        {

            trigger OnValidate()
                ...
                TestField("Starting Time");
                TestField("Ending Time");
                TotalTime := CalendarMgt.CalcTimeDelta("Ending Time", "Starting Time");
                OnvalidateConcurrentCapacityOnAfterCalcTotalTime(Rec, TotalTime, xRec);
                if "Ending Time" < "Starting Time" then
                    TotalTime := TotalTime + 86400000;
                ...
         }

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnvalidateConcurrentCapacityOnAfterCalcTotalTime(var ItemJournalLine: Record "Item Journal Line"; var TotalTime: Integer; xItemJournalLine: Record "Item Journal Line")
    begin
    end;

Do you think it is possible ?

Thank for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
