### ISSUE TITLE
[Request for External] Codeunit 5703 Catalog Item Management - CreateNewItem

### ISSUE THREAD

**Issue by vinpicci** [microsoft/ALAppExtensions#11963]
Hi, would it be possible to change the procedure CreateNewItem in codeunit 5703 from local to external?
Thanks for your time

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
