### ISSUE TITLE
[Event Request] Codeunit 10750 - SII XML Creator - OnAfterCalcCuotaDeducible

### ISSUE THREAD

**Issue by Dynam1co** [Microsoft/ALAppExtensions#1197]
Dear Microsoft ALAppExtensions team,

Through this issue we would like to request the following event-publisher to be added in codeunit Codeunit 10750 - SII XML Creator. This event will help us to personalize SII functionality in Spain.

`LOCAL [IntegrationEvent] OnAfterCalcCuotaDeducible(VAR pCuotaDeducible : Decimal;VAR pVATAmount : Decimal;VAR pVATEntry : Record "VAT Entry")`

Which would be called from the 'CalculateExempAndNonExemptVATEntries' procedure, as shown below:

```
ExemptionCodePresents := GetExemptionCode(VATEntry,ExemptionCode);
IF (NOT ExemptionCodePresents) OR IsPurchEUExemptionCodeE5(VATEntry,ExemptionCode) THEN
  CuotaDeducibleValue += VATAmount;

//NEW EVENT
OnAfterCalcCuotaDeducible(CuotaDeducibleValue, VATAmount, VATEntry);
//NEW EVENT

IF UseReverseChargeNotIntracommunity(VATEntry."VAT Calculation Type",VendorNo,PostingDate) THEN
  CalculateNonExemptVATEntries(TempVATEntryReverseChargeCalculated,VATEntry,TRUE,VATAmount)
ELSE
  CalculateNonExemptVATEntries(TempVATEntryNormalCalculated,VATEntry,TRUE,VATAmount);
```

Thank you so much

**Comment by AlcobaG** [comment]
We need an Event in this CDU too, for the same legal requirement applicable in Spain "Not deductible VAT"  ("Prorrata de IVA"). In our case, we need OnAfterCalcCuotaSoportada.
Is there any progress on this or any anticipation of an answer?
[SII con prorrata de IVA.docx](https://github.com/Microsoft/ALAppExtensions/files/3086907/SII.con.prorrata.de.IVA.docx)
