### ISSUE TITLE
[Event Request] Application “Tests-SCM”, Codeunit 137265 "SCM Package Tracking Purchase"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#11970]
[Event Request]Application “Tests-SCM”, 137265 "SCM Package Tracking Purchase"

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize():

![pic1](https://user-images.githubusercontent.com/45795262/114014265-b7a50c80-9868-11eb-8205-98150c1c9609.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
