### ISSUE TITLE
[Event Request] codeunit 5705 "TransferOrder-Post Receipt" - OnRunOnBeforeTestTransLineItemBlocked

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#11978]
Can we please get the following event to disable the Testfield for special cases?

```al
trigger OnRun()
var
    //...
    IsHandled: Boolean; //NEW
begin
   
    //...

    with TransHeader do begin
        
        //...

        if TransLine.Find('-') then
            repeat
                LineCount := LineCount + 1;
                if GuiAllowed then
                    Window.Update(2, LineCount);

                if TransLine."Item No." <> '' then begin
                    Item.Get(TransLine."Item No.");
                    //+NEW
                   IsHandled := false;
                   OnRunOnBeforeTestTransLineItemBlocked(TransLine, Item, TransHeader, Location, WhseReceive, IsHandled);
                   if not IsHandled then
                    //-NEW
                        Item.TestField(Blocked, false);
                end;

                OnCheckTransLine(TransLine, TransHeader, Location, WhseReceive);

                InsertTransRcptLine(TransRcptHeader."No.", TransRcptLine, TransLine);
            until TransLine.Next() = 0;

       ...
end;
```

```al
[IntegrationEvent(false, false)]
local procedure OnRunOnBeforeTestTransLineItemBlocked(TransferLine: Record "Transfer Line"; Item: Record Item; TransferHeader: Record "Transfer Header"; Location: Record Location; WhseReceive: Boolean; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by AndreiPanko** [comment]
@pri-kise could you please clarify which "special case" your refer to?
I'm asking as for next version we are limiting this check to lines where Qty to Receive <> 0.

**Comment by pri-kise** [comment]
@AndreiPanko this seems to be the only case when we are currently using this event to skip this check:

This is our code right now:
```al
[EventSubscriber(ObjectType::Codeunit, Codeunit::"TransferOrder-Post Receipt", 'OnRunOnBeforeCheckItemBlocked', '', false, false)]
local procedure PostReceipt_OnRunOnBeforeCheckItemBlocked(TransLine: Record "Transfer Line"; var IsHandled: Boolean)
begin
    IsHandled := TransLine."Qty. to Receive" = 0;
end;
```

Are you limiting this check on the reverse part, too?
(See `codeunit 5704 "TransferOrder-Post Shipment"` CheckItemNotBlocked only for `TransferLine."Qty. to Ship" <> 0;`)

**Comment by AndreiPanko** [comment]
@pri-kise Yes, both sides:

codeunit 5705 "TransferOrder-Post Receipt"

            TransRcptLine.LockTable();
            TransLine.SetRange(Quantity);
            TransLine.SetFilter("Qty. to Receive", '<>0');    << ADDED
            OnRunOnAfterTransLineSetFiltersForRcptLines(TransLine, TransHeader, Location, WhseReceive);
            if TransLine.Find('-') then
                repeat


codeunit 5704 "TransferOrder-Post Shipment"

                TransShptLine.LockTable();
                TransLine.SetRange(Quantity);
                TransLine.SetFilter("Qty. to Ship", '<>0');   << ADDED
                OnRunOnAfterTransLineSetFiltersForShptLines(TransLine, TransHeader, Location, WhseShip);
                if TransLine.Find('-') then
                    repeat
