### ISSUE TITLE
[Event Parameter Request] table 37 "Sales Line" - Add xRec to OnAfterInitQtyToAsm

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#11979]
Could you please add the xRec to the event `OnAfterInitQtyToAsm`?
```al
local procedure InitQtyToAsm()
begin
    
   ...

    //-OnAfterInitQtyToAsm(Rec, CurrFieldNo);//OLD
    OnAfterInitQtyToAsm(xRec, Rec, CurrFieldNo);//NEW
end;
```
```al
[IntegrationEvent(false, false)]
local procedure OnAfterInitQtyToAsm(xSalesLine: Record "Sales Line"; var SalesLine: Record "Sales Line"; CallingFieldNo: Integer)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
