### ISSUE TITLE
[Event Request] codeunit 1002 "Job Create-Invoice" -OnBeforeTestBilltoCustomerNo

### ISSUE THREAD

**Issue by sandeepchapte** [microsoft/ALAppExtensions#11972]
I need this event to handle the testfield in my code.

Below is Object and image is for reference :
Object : codeunit 1002 "Job Create-Invoice"
Function: CreateSalesHeader
**Parameters SalesHeader & IsHandled with VAR**

![image](https://user-images.githubusercontent.com/36148210/114014050-d2d24500-9885-11eb-9840-9c487cfb91f6.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
