### ISSUE TITLE
[Event Request] Codeunit 1002 "Job Create-Invoice", OnCreateSalesInvoiceJobTaskTestJob

### ISSUE THREAD

**Issue by HeidarOrn** [microsoft/ALAppExtensions#11976]
Good day.
Is it possible to extend the following publisher: OnCreateSalesInvoiceJobTaskTestJob(var Job: Record Job)
with additional parameters:
OnCreateSalesInvoiceJobTaskTestJob(var Job: Record Job; VAR JobPlanningLine: Record "Job Planning Line"; PostingDate: Date)

Regards Heiðar.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
