### ISSUE TITLE
[Event Request] OnAfterRecordChanged in Page 1351 "Posted Purch. Invoice - Update", 1353 "Posted Return Receipt - Update" and 1352 "Posted Return Shpt. - Update"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#11974]
In the existing event trigger OnAfterRecordChanged we need the previouslay assign xPurchInvHeader, xReturnReceiptHeader and xReturnShipmentHeader as parameter:

old:
OnAfterRecordChanged(Rec, xRec, IsChanged);
new:
OnAfterRecordChanged(Rec, xReturnReceiptHeader , IsChanged);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
