### ISSUE TITLE
[Event Request] Application “Tests-SCM”, Codeunit 137264 "SCM Package Tracking Sales"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#11971]
[Event Request]Application “Tests-SCM”, 137264 "SCM Package Tracking Sales"

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize():
![pic1](https://user-images.githubusercontent.com/45795262/114014523-005cc580-9869-11eb-9a30-340285cd71c7.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
