### ISSUE TITLE
[Event Request] Codeunit 1002 "Job Create-Invoice", OnBeforeCopyJobPlanningLine 

### ISSUE THREAD

**Issue by HeidarOrn** [microsoft/ALAppExtensions#11975]
Good day.
I would like to ask for a new event in the function "CreateSalesInvoiceLines" before "JobPlaningLine" is copied.

![image](https://user-images.githubusercontent.com/5692559/114022407-41e97280-9861-11eb-8a5d-eb9cc3722e35.png)

![image](https://user-images.githubusercontent.com/5692559/114022298-28482b00-9861-11eb-9ee9-5b9b09c1a79c.png)

Regards Heiðar

**Comment by RomanZanizdra** [comment]
Hi @HeidarOrn . What is the reason to JobPlanningLine as var parameter in event if further it will be "over written" from JobPlanningLineSource by Copy function? Or I miss something?

**Comment by HeidarOrn** [comment]
Hi @RomanZanizdra, There is an error in my request, the event should take JobPlanningLineSource and not JobPlanningLine.

![image](https://user-images.githubusercontent.com/5692559/114680597-e1dd4b00-9cfc-11eb-9f1c-8dfa7f4f400c.png)

![image](https://user-images.githubusercontent.com/5692559/114680676-ef92d080-9cfc-11eb-9ee7-c4630decdb85.png)

Thanks for pointing this out.

Regards Heiðar

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
