### ISSUE TITLE
[Event Request] Application “Tests-SCM”, Codeunit 137263 "SCM Tracking Package Base"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#11973]
[Event Request]Application “Tests-SCM”, 137263 "SCM Tracking Package Base"

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize():
![pic1](https://user-images.githubusercontent.com/45795262/114014867-5d587b80-9869-11eb-8e40-f6f84f2d08af.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
