### ISSUE TITLE
[Event Request] Table 210 "Job Journal Line" OnBeforeOnLookupJobNo

### ISSUE THREAD

**Issue by HeidarOrn** [microsoft/ALAppExtensions#11977]
Good day.

Is it possible to get a new Event in OnLookup in the field "Job No.":

![image](https://user-images.githubusercontent.com/5692559/114038629-8ed54500-9871-11eb-8704-839d74aedbd8.png)
 
![image](https://user-images.githubusercontent.com/5692559/114038404-60f00080-9871-11eb-9f87-df215f5ae217.png)

Regards Heiðar

**Comment by AlexanderYakunin** [comment]
We already have standard trigger here, can you use this?
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers/devenv-onafterlookup-trigger
