### ISSUE TITLE
[Event Request] Item Tracking Lines Page 6510 - "Serial No." OnValidate

### ISSUE THREAD

**Issue by dpodjasek** [microsoft/ALAppExtensions#11985]
**Event Request:**
Item Tracking Lines Page 6510
Function "Serial No." OnValidate Trigger

I am creating a set of modifications that will allow serial nos to be used in a manner more similar to lots.  The quantity will not be limited to 1 (I have seen there are many events already that facilitate this), and one serial may be used with multiple lots.

In the "Serial No." OnValidate trigger, there is code that looks for an existing tracking with the same serial number as was just validated, and fills the lot number of the current line to match the previously defined lot for that serial.  I wish to skip this code, as one serial may now be used with multiple lots.

**PROPOSED CODE CHANGE:**

![image](https://user-images.githubusercontent.com/48566556/114103202-509a4e80-988e-11eb-93c9-f550b32c3d74.png)

(Both Rec and IsHandled should be passed by reference with var.)

This is a new request that was created as a simplified explanation of this thread:
https://github.com/microsoft/ALAppExtensions/issues/11858

Thank you,
David Podjasek

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
