### ISSUE TITLE
SMTP Deprecated - Not possible to create "App Only" email accounts with the new Email Accounts feature

### ISSUE THREAD

**Issue by quadfin** [microsoft/ALAppExtensions#11986]
The the existing (legacy) SMTP Mail implementations (SMTP Mail, DotNetSmtpMessage) are targeted for deprecation.
Those interfaces enable the app developer to define email accounts that are only visible within the application.  
It is not possible to do the same with the new Email Account implementation.

"App Only" email accounts may be used for application support or other messaging that should not be publicly accessible.
With the above pending deprecation, that loss of functionality breaks apps relying upon it.

This situation could be resolved by:
1. Not deprecating one of the SMTP interfaces
2. Modifying the SMTP Email Account interface to allow app access to its internals
3. Wrapping the DotNet SMTPClient class

#3 would provide a flexible solution.
#1 would be the least impactful.

**Comment by pri-kise** [comment]
Is there any plan that this will be solved in the near future?
What is the preferred solution on MS perspective? 
Is there already someone/ some team of MS working on this (in my opinion) very important topic?

I can think of one other option.
Allowing to setup Mail Accounts via Code, that can be set to be only accesible (used to send mails) and editalbe by the app that created those accounts.

**Comment by JesperSchulz** [comment]
We've got work planned for version 20. It's kind of required, before we actually deprecate the old SMTP capabilities. We did not retire the old SMTP implementation, as we didn't have a replacement for this scenario. But we hope to be able to deliver such replacement and to be able to remove the legacy SMTP functionality with the upcoming major.

**Comment by darjoo** [comment]
Below is an example code snippet

```
  procedure SMTPAPIExample()
  var
      BlobStorage: Codeunit "Temp Blob";
      Auth: codeunit "SMTP Authentication";
      Message: Codeunit "SMTP Message";
      Client: Codeunit "SMTP Client";
      ToRecipients: List of [Text];
      CcRecipients: List of [Text];
      BccRecipients: List of [Text];
      Attachment: InStream;
  begin
      // Add recipients
      ToRecipients.add('ToRecipient@contoso.com');
      Message.SetToRecipients(ToRecipients);
      CcRecipients.add('CcRecipient@contoso.com');
      Message.SetCcRecipients(CcRecipients);
      BccRecipients.add('BccRecipient@contoso.com');
      Message.SetBccRecipients(CcRecipients);

      // Who is this being sent from
      Message.AddFrom('FromName', 'FromEmailAddress');

      // Subject and body details
      Message.SetSubject('Email subject title');
      Message.SetBody('My email message body');

      // Adding attachments
      BlobStorage.CreateInStream(Attachment);
      Message.AddAttachment(Attachment, 'MyAttachment.txt');

      // Providing authentication information
      Auth.SetBasicAuthInfo('UserId', 'Password');
      // Possible to login with Oauth token as well
      //Auth.SetOAuth2AuthInfo('UserInfo', 'Token');

      // Connecting to mail server
      // Host, port, secure connection
      Client.Connect('SMTPHostUrl.com', 587, true);

      // Authenticating
      Client.Authenticate(Enum::"SMTP Authentication Types"::Basic, Auth);
      //Client.Authenticate(Enum::"SMTP Authentication Types"::"OAuth 2.0", Auth);

      // Sending
      Client.Send(Message);
  end;
```
