### ISSUE TITLE
[Event Request] Table 210 "Job Journal Line" OnValidateNoOnBeforeValidateQuantity

### ISSUE THREAD

**Issue by HeidarOrn** [microsoft/ALAppExtensions#11980]
Good Day.

I would like to ask for a new event in OnValidate in the field No. and IsHandeld Boolean:

![image](https://user-images.githubusercontent.com/5692559/114042722-33a55180-9875-11eb-8309-c04578ffa407.png)
![image](https://user-images.githubusercontent.com/5692559/114042777-3ef87d00-9875-11eb-8a68-4d8225f1dd23.png)

Regards Heiðar

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
