### ISSUE TITLE
[Event Request] Table 210 "Job Journal Line"  OnBeforeUpdateAllAmounts

### ISSUE THREAD

**Issue by HeidarOrn** [microsoft/ALAppExtensions#11983]
Good day.
Is it possible to extend the following publisher: 
![image](https://user-images.githubusercontent.com/5692559/114045655-b3342000-9877-11eb-8223-3cbb97203257.png)

with additional parameters:
![image](https://user-images.githubusercontent.com/5692559/114045386-8253eb00-9877-11eb-9ae5-676e80ebe4fb.png)

And add the following Handel code after the Event:

![image](https://user-images.githubusercontent.com/5692559/114045943-f2fb0780-9877-11eb-9cfa-6de3c5519487.png)

Regards Heiðar

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
