### ISSUE TITLE
[Extensibility] IncludeSender in OnBeforeInitPost in codeunit 900 Assembly-Post

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#11989]
Hello, please set `IncludeSender` as true in codeunit 900 `Assembly-Post` on this integration event:

```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeInitPost(var AssemblyHeader: Record "Assembly Header"; SuppressCommit: Boolean)
    begin
    end;
```

This is the same as issues #10602 and #10603, as currently we have no way of calling the `SetSuppressCommit` procedure while the standard code runs.

Thank you.

**Comment by AlexanderYakunin** [comment]
Will be added to OnBeforeRun() event.

    [IntegrationEvent(true, false)]
    local procedure OnBeforeOnRun(var AssemblyHeader: Record "Assembly Header"; SuppressCommit: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
