### ISSUE TITLE
Event Request] Item Jnl.-Post Line OnPostOutputOnBeforeProdOrderRtngLineModify

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#11987]
I want to add a new variable Last Operation to OnPostOutputOnBeforeProdOrderRtngLineModify.

// OLD+
  LastOperation := (not NextOperationExist(ProdOrderRtngLine));
  OnPostOutputOnBeforeProdOrderRtngLineModify(ProdOrderRtngLine, ProdOrderLine, ItemJnlLine);
  ProdOrderRtngLine.Modify();

    [IntegrationEvent(false, false)]
    local procedure OnPostOutputOnBeforeProdOrderRtngLineModify(var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var ProdOrderLine: Record "Prod. Order Line"; var ItemJournalLine: Record "Item Journal Line")
    begin
    end;
// OLD-

// NEW+
  LastOperation := (not NextOperationExist(ProdOrderRtngLine));
  OnPostOutputOnBeforeProdOrderRtngLineModify(ProdOrderRtngLine, ProdOrderLine, ItemJnlLine, LastOperation);  
  ProdOrderRtngLine.Modify();

    [IntegrationEvent(false, false)]
    local procedure OnPostOutputOnBeforeProdOrderRtngLineModify(var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var ProdOrderLine: Record "Prod. Order Line"; var ItemJournalLine: Record "Item Journal Line"; var LastOperation: Boolean)
    begin
    end;
// NEW-

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
