### ISSUE TITLE
Codeunit 12 "Gen. Jnl.-Post Line" - OnAfterStartPosting

### ISSUE THREAD

**Issue by LubomirUrx** [microsoft/ALAppExtensions#11994]
I'd like to propose the Event OnAfterStartPosting in Codeunit Gen. Jnl.-Post Line (IncludeSender = true). 

    procedure StartPosting(GenJnlLine: Record "Gen. Journal Line")
    var
        GenJnlTemplate: Record "Gen. Journal Template";
        AccountingPeriodMgt: Codeunit "Accounting Period Mgt.";
    begin
        OnBeforeStartPosting(GenJnlLine);

        with GenJnlLine do begin
            InitNextEntryNo();
            FirstTransactionNo := NextTransactionNo;

            InitLastDocDate(GenJnlLine);
            CurrentBalance := 0;

            FiscalYearStartDate := AccountingPeriodMgt.GetPeriodStartingDate;

            GetGLSetup();

            if not GenJnlTemplate.Get("Journal Template Name") then
                GenJnlTemplate.Init();

            VATEntry.LockTable();
            if VATEntry.FindLast then
                NextVATEntryNo := VATEntry."Entry No." + 1
            else
                NextVATEntryNo := 1;
            NextConnectionNo := 1;
            FirstNewVATEntryNo := NextVATEntryNo;

            GLReg.LockTable();
            if GLReg.FindLast then
                GLReg."No." := GLReg."No." + 1
            else
                GLReg."No." := 1;
            GLReg.Init();
            GLReg."From Entry No." := NextEntryNo;
            GLReg."From VAT Entry No." := NextVATEntryNo;
            GLReg."Creation Date" := Today;
            GLReg."Creation Time" := Time;
            GLReg."Source Code" := "Source Code";
            GLReg."Journal Batch Name" := "Journal Batch Name";
            GLReg."User ID" := UserId;
            IsGLRegInserted := false;

            OnAfterInitGLRegister(GLReg, GenJnlLine);

            GetCurrencyExchRate(GenJnlLine);
            TempGLEntryBuf.DeleteAll();
            CalculateCurrentBalance(
               "Account No.", "Bal. Account No.", IncludeVATAmount, "Amount (LCY)", "VAT Amount");
		
            //START
            OnAfterStartPosting(GenJnlLine);
            //END
        end;
    end;

    //START
    [IntegrationEvent(true, false)]
    local procedure OnAfterStartPosting(GenJournalLine: Record "Gen. Journal Line")
    begin
    end;
    //END

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
