### ISSUE TITLE
[Event Request] Table 330 Currency Exchange Rate - Function FindCurrency

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#11995]
Dear ALAppExtensions Team,

We would like to request the following event publisher

>procedure FindCurrency(Date: Date; CurrencyCode: Code[10]; CacheNo: Integer)
    begin
        if (CurrencyCode2[CacheNo] = CurrencyCode) and (Date2[CacheNo] = Date) then
            Rec := CurrencyExchRate2[CacheNo]
        else begin
            if Date = 0D then
                Date := WorkDate;
            CurrencyExchRate2[CacheNo].SetRange("Currency Code", CurrencyCode);
            CurrencyExchRate2[CacheNo].SetRange("Starting Date", 0D, Date);
            **//event request**
            **OnAfterCurrencyExchRate2Filter(CurrencyExchRate2,CacheNo,Date);**
            **//event request**
            CurrencyExchRate2[CacheNo].FindLast;
            Rec := CurrencyExchRate2[CacheNo];
            CurrencyCode2[CacheNo] := CurrencyCode;
            Date2[CacheNo] := Date;
        end;
        OnAfterFindCurrency(Rec, CurrencyExchRate2);
    end;

local procedure OnAfterCurrencyExchRate2Filter(var CurrencyExchRate2: Record "Currency Exchange Rate",CacheNo,Date)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
