### ISSUE TITLE
unusable parameter - [Event Request] T77 "Report Selections" - procedure GetPurchaseOrderEmailAddress() - OrderAddress

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#11996]
https://github.com/microsoft/ALAppExtensions/issues/10804

The publisher added was

    local procedure OnBeforeGetPurchaseOrderEmailAddress(BuyFromVendorNo: Code[20]; RecVar: Variant; ReportUsage: Enum "Report Selection Usage"; var OrderAddress: Record "Order Address"; var EmailAddress: Text[250]; var IsHandled: Boolean)

The `var OrderAddress` there is pointless, since (a) the subscriber just gets a brand-new uninitialised record, and (b) if they did anything to change it via the `var` that would just get trampled anyway by the `OrderAddress.Get()` later in `GetPurchaseOrderEmailAddress()`. I see no reason to pass `OrderAddress`, `var` or not.

**Comment by StanPesotskiy** [comment]
We cannot remove an existing parameter. What would be a correction to make OrderAddress useful?

**Comment by dtkb** [comment]
I have no idea; that's why it should've been thought about properly while adding the event!

The original requestor presumably included the parameter because their suggestion was to `if IsHandled then exit(OrderAddress."E-Mail")`. But MS's code does `if IsHandled then exit(EmailAddress)`. Which makes more sense; there'd be no point passing a record just to set/get one of its fields' values. But it seems that wasn't thought about, and it got left in.

Passed `OrderAddress` is not used again in the function until many lines later, after many other possible exit points, and then its 'use' is only to overwrite all its values via a `.Get()`.

So I don't see how it can possibly be of any use to anyone, and anyone writing to it via `var` or expecting you to `exit(OrderAddress."E-Mail")` is going to be disappointed, as it won't be used.

**Comment by dtkb** [comment]
Full current code from 17.5 for reference:

    local procedure GetPurchaseOrderEmailAddress(BuyFromVendorNo: Code[20]; RecVar: Variant; ReportUsage: Enum "Report Selection Usage") EmailAddress: Text[250]
    var
        PurchaseHeader: Record "Purchase Header";
        OrderAddress: Record "Order Address";
        RecRef: RecordRef;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetPurchaseOrderEmailAddress(BuyFromVendorNo, RecVar, ReportUsage, OrderAddress, EmailAddress, IsHandled);
        if IsHandled then
            exit(EmailAddress);

        if BuyFromVendorNo = '' then
            exit('');

        if ReportUsage <> Usage::"P.Order" then
            exit('');

        RecRef.GetTable(RecVar);
        if RecRef.Number <> DATABASE::"Purchase Header" then
            exit('');

        PurchaseHeader := RecVar;
        if PurchaseHeader."Order Address Code" = '' then
            exit('');

        if not OrderAddress.Get(BuyFromVendorNo, PurchaseHeader."Order Address Code") then
            exit('');

        exit(OrderAddress."E-Mail");
    end;

**Comment by StanPesotskiy** [comment]
You are absolutely right. 
Though there is only one way to get rid of this parameter is to obsolete this event and create another one without this parameter. But it will lead to the code like this:
```
    IsHandled := false;
    OnBeforeGetPurchaseOrderEmailAddress(BuyFromVendorNo, RecVar, ReportUsage, OrderAddress, EmailAddress, IsHandled);
    **NewOnBeforeGetPurchaseOrderEmailAddress(BuyFromVendorNo, RecVar, ReportUsage, EmailAddress, IsHandled);**
    if IsHandled then
        exit(EmailAddress);
```
and we will be able to remove OnBeforeGetPurchaseOrderEmailAddress in 3 versions later (18+ months from now).
As this parameter may cause some confusion as you mentioned, but having two twin events seems to look even worse. 
I prefer to keep that unnecessary parameter as removing it brings more noise than help. Would you agree?

**Comment by dtkb** [comment]
Yes, I think right now the best thing is just to leave it, and have this issue as a reference for how we know it doesn't do anything.

Could there be a way to deprecate individual arguments, at least for events? That way we could signal clearly that they're not used/useful, omit them by default when looking-up events, warn if still present in old code or manually added, etc.

**Comment by StanPesotskiy** [comment]
As I know there is no such an "obsolete parameter" feature in the backlog. 
You could submit a product suggestion on https://aka.ms/bcideas

**Comment by dtkb** [comment]
done: https://experience.dynamics.com/ideas/idea/?ideaid=9243395f-769b-eb11-89ee-0003ff45b7ac

**Comment by StanPesotskiy** [comment]
Great! Thank you.
