### ISSUE TITLE
[Event Request] Codeunit 14 & 15

### ISSUE THREAD

**Issue by guidorobben** [Microsoft/ALAppExtensions#1199]
Please add events for the OnRun code in Codeunit 14 & 15. This will make it easier to show a card or entries for you own extension.

**Comment by JesperSchulz** [comment]
Again, please provide more details.

**Comment by guidorobben** [comment]
[cod14.txt](https://github.com/Microsoft/ALAppExtensions/files/2863943/cod14.txt)
[Cod15.txt](https://github.com/Microsoft/ALAppExtensions/files/2863944/Cod15.txt)

Hi Jesper, 

Sorry for the lack of info, this was my first attempt to request an event. And the codeunits only contain 1 function, so I thought it would be logical. My bad. learned my lesson.

I attached the new codeunits how I want it to be.
Guido

**Comment by JesperSchulz** [comment]
No worries :-) We're on it!
