### ISSUE TITLE
[Request-for-external] Table 37 "Sales Line" - GetDefaultBin

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#11993]
Dear ALAppExtensions Team,

We would like to request the following : Is it possible to change the function GetDefaultBinin Table 37 from [Local] to [External]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
