### ISSUE TITLE
[Event Request] table 900 "Assembly Header" - OnValidateDatesOnBeforeConfirm

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#11992]
Could you please add the following event snippet / Pattern around every confirm in the ValidateDates Procedure?
If you need more  details, feel free to ask.

```al
procedure ValidateDates(FieldNumToCalculateFrom: Integer; DoNotValidateButJustAssign: Boolean)
var
    NewDueDate: Date;
    NewEndDate: Date;
    NewStartDate: Date;
    IsHandled: Boolean;
    UpdateConfirmed: Boolean;
begin
    ...

    //Before every confirm add the following event snippet/Pattern:
    IsHandled := false;
    OnValidateDatesOnBeforeConfirm(Rec, FieldNumToCalculateFrom, DoNotValidateButJustAssign, IsHandled, UpdateConfirmed);
    if not IsHandled then
        UpdateConfirmed := Confirm(.....);
    if UpdateConfirmed then 
    ....

    ....

end;
```
```al
[IntegrationEvent(false, false)]
local procedure OnValidateDatesOnBeforeConfirm(var AssemblyHeader: Record "Assembly Header"; FieldNumToCalculateFrom: Integer; DoNotValidateButJustAssign: Boolean; var IsHandled: Boolean; var UpdateConfirmed: Boolean)
begin
end;
```

**Comment by AlexanderYakunin** [comment]
We already have several events for this purpose. First, each call of ValidateDates have handled OnBefore event. Second, there is OnBeforeValidateDates event, and you an overwrite our code by yours. Not sure we should add more events for each Confirm.

**Comment by pri-kise** [comment]
We only want to disable the confirm in some cases. This is the smallest change in the business logic compared to handle the full code.
That's why I requested those events. 
I know i could copy the whole function and set this to handled, but looking forward to updates I would prefer having the possiblity to simple replace the confirm by code.

It's a common need for our customers that they want to avoid some confirms and confirm always the same based on the current value or a setup value.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
