### ISSUE TITLE
[Event Request] Table 81 Gen. Journal Line - Field 93 "Bal. VAT Prod. Posting Group" OnValidate Trigger

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#11998]
Dear ALAppExtensions Team,

We would like to request the following event publisher like "VAT Prod. Posting Group" OnValidate Trigger    

    //BEFORE
    "Bal. VAT %" := 0;
    "Bal. VAT Calculation Type" := "Bal. VAT Calculation Type"::"Normal VAT";
    if "Bal. Gen. Posting Type" <> "Bal. Gen. Posting Type"::" " then begin
        GetVATPostingSetup("Bal. VAT Bus. Posting Group", "Bal. VAT Prod. Posting Group");
        "Bal. VAT Calculation Type" := VATPostingSetup."VAT Calculation Type";
        case "Bal. VAT Calculation Type" of
            "Bal. VAT Calculation Type"::"Normal VAT":
                "Bal. VAT %" := VATPostingSetup."VAT %";
            "Bal. VAT Calculation Type"::"Full VAT":
                case "Bal. Gen. Posting Type" of
                    "Bal. Gen. Posting Type"::Sale:
                        TestField("Bal. Account No.", VATPostingSetup.GetSalesAccount(false));
                    "Bal. Gen. Posting Type"::Purchase:
                        TestField("Bal. Account No.", VATPostingSetup.GetPurchAccount(false));
                end;
        end;
    end;
    Validate("Bal. VAT %");
    -----------------------------------------------------------------------------------------------------------------
    //AFTER
    "Bal. VAT %" := 0;
    "Bal. VAT Calculation Type" := "Bal. VAT Calculation Type"::"Normal VAT";
    //-->event request
    IsHandled := false;
    OnValidateBalVATProdPostingGroupOnBeforeVATCalculationCheck(Rec, VATPostingSetup, IsHandled);
    if not IsHandled then
    //<--event request
      if "Bal. Gen. Posting Type" <> "Bal. Gen. Posting Type"::" " then begin
          GetVATPostingSetup("Bal. VAT Bus. Posting Group", "Bal. VAT Prod. Posting Group");
          "Bal. VAT Calculation Type" := VATPostingSetup."VAT Calculation Type";
          case "Bal. VAT Calculation Type" of
              "Bal. VAT Calculation Type"::"Normal VAT":
                  "Bal. VAT %" := VATPostingSetup."VAT %";
              "Bal. VAT Calculation Type"::"Full VAT":
                  case "Bal. Gen. Posting Type" of
                      "Bal. Gen. Posting Type"::Sale:
                          TestField("Bal. Account No.", VATPostingSetup.GetSalesAccount(false));
                      "Bal. Gen. Posting Type"::Purchase:
                          TestField("Bal. Account No.", VATPostingSetup.GetPurchAccount(false));
                  end;
          end;
      end;
    Validate("Bal. VAT %");

   [IntegrationEvent(false, false)]
    local procedure OnValidateBalVATProdPostingGroupOnBeforeVATCalculationCheck(var GenJournalLine: Record "Gen. Journal 
    Line"; var VATPostingSetup: Record "VAT Posting Setup"; var IsHandled: Boolean)
    begin
    end;

**Comment by Hakan-6Gen** [comment]
Can you add the same event publishers for field 91 "VAT Prod. Posting Group" and field 93 "Bal. VAT Prod. Posting Group" in table 81 "Gen. Journal Line" for table 751 "Standard General Journal Line".

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
