### ISSUE TITLE
[Request for global] - "CRM Integration Management" - AddIntegrationTableMapping

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#11999]
![image](https://user-images.githubusercontent.com/35260264/114392475-2059f500-9b99-11eb-9d10-abc2821cc59b.png)

Can you make this function global?

**Comment by onbuyuka** [comment]
Hi, we do not have any plans to make the procedure global. IntegrationTableMapping.CreateRecord is already a public procedure as documented here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-custom-cds-integration. This should cover custom Dataverse scenarios.
You can have your own implementation of AddIntegrationTableMapping by copying if you need to.
