### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by mazhelez** [Microsoft/ALAppExtensions#12]
Issue for test purposes with **some** _markdown_

**Comment by jobulsin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by jobulsin** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 14.

**Comment by bc-ghost** [comment]
Thanks for submitting this issue. We will publish a fix for it in the next minor update for release 14.
