### ISSUE TITLE
Add parameter to event in "Gen. Jnl.-Post Line"

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/ALAppExtensions#12004]
Codeunit "Gen. Jnl.-Post Line", event 'OnPostFixedAssetOnBeforeInsertGLEntry' i need the parameter GLEntry2.

Original: 
local procedure OnPostFixedAssetOnBeforeInsertGLEntry(var GenJournalLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; var IsHandled: Boolean; var TempFAGLPostBuf: Record "FA G/L Posting Buffer" temporary)

Modified:
local procedure OnPostFixedAssetOnBeforeInsertGLEntry(var GenJournalLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; var IsHandled: Boolean; var TempFAGLPostBuf: Record "FA G/L Posting Buffer" temporary;GLEntry2: Record "G/L Entry")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
