### ISSUE TITLE
Table 1003 - Add parameters in the event OnBeforeFindPriceAndDiscount

### ISSUE THREAD

**Issue by rswaldia** [microsoft/ALAppExtensions#12007]
Request for Adding parameter "Rec" and "xRec" in event OnBeforeFindPriceAndDiscount in function FindPriceAndDiscount.

OnBeforeFindPriceAndDiscount(var JobPlanningLine: Record "Job Planning Line"; var xJobPlanningLine: Record "Job Planning Line"; CalledByFieldNo: Integer; var IsHandled: Boolean); //two New parameters Rec and xRec with type var.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
