### ISSUE TITLE
[Request for global] - "CRM Integration Management" - EnqueueSyncJob

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#12000]
![image](https://user-images.githubusercontent.com/35260264/114392732-75960680-9b99-11eb-8306-1e74e16273b1.png)

Can you make this fucntion global?

**Comment by onbuyuka** [comment]
"CRM Setup Defaults"- CreateJobQueueEntry is already a global procedure and it should be enough. You can have your own implementation of EnqueueSyncJob by copying if you need to.
