### ISSUE TITLE
[Event Request] codeunit 1605 "PEPPOL Management" - OnAfterGetLineItemInfo

### ISSUE THREAD

**Issue by cghasvi** [microsoft/ALAppExtensions#12006]
procedure GetLineItemInfo(SalesLine: Record "Sales Line"; var Description: Text; var Name: Text; var SellersItemIdentificationID: Text; var StandardItemIdentificationID: Text; var StdItemIdIDSchemeID: Text; var OriginCountryIdCode: Text; var OriginCountryIdCodeListID: Text)
    var
........
    begin

.........
.........
 
        // At very end at procedure       
 OnAfterGetLineItemInfo(SalesLine;Description;Name;SellersItemIdentificationID;StandardItemIdentificationID;StdItemIdIDSchemeID;OriginCountryIdCode;OriginCountryIdCodeListID);

    end;

************************
    [IntegrationEvent(false, false)]
    local procedure OnAfterGetLineItemInfo(SalesLine: Record "Sales Line"; var Description: Text; var Name: Text; var SellersItemIdentificationID: Text; var StandardItemIdentificationID: Text; var StdItemIdIDSchemeID: Text; var OriginCountryIdCode: Text; var OriginCountryIdCodeListID: Text)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
