### ISSUE TITLE
Table 36 Sales Header in TestNoSeries

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [Microsoft/ALAppExtensions#1200]
Please Insert a new Publisher in TestNoSeries 

OnBeforeTestNoSeries(Rec,Handled);

for setup own NoSeries

**Comment by AlexanderYakunin** [comment]
Already done

[External] TestNoSeries()
SalesSetup.GET;
IsHandled := FALSE;
OnBeforeTestNoSeries(Rec,IsHandled);
IF NOT IsHandled THEN
