### ISSUE TITLE
[Event Request] Codeunit 7018 "Price UX Management" OnBeforeGetPriceSource and OnAfterGetPriceSource events

### ISSUE THREAD

**Issue by jaromirchaloupka** [microsoft/ALAppExtensions#12005]
Please add **OnBeforeGetPriceSource** and **OnAfterGetPriceSource** events into _GetPriceSource_ procedures in Codeunit 7018 "Price UX Management" in order to control _Temp Price Source_ records creation in _Price Source List_ codeunit in case we have new fields in source tables (e.g. Customer) which could affect which lines will be displayed when click on Sales Price Lists action on Customer Card for example.

**Comment by jaromirchaloupka** [comment]
`[IntegrationEvent(false, false)]
local procedure OnBeforeGetPriceSource (Customer: Record Customer; var PriceSourceList: Codeunit "Price Source List")
begin
end;

[IntegrationEvent(false, false)]
local procedure OnAfterGetPriceSource (Customer: Record Customer; var PriceSourceList: Codeunit "Price Source List")
begin
end;`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
