### ISSUE TITLE
[Event Request] Codeunit 5836 "Cost Calculation Management" FindRoutingLine

### ISSUE THREAD

**Issue by THillemeier** [microsoft/ALAppExtensions#12015]
Hello,

in codeunit 5836 "Cost Calculation Management", function "FindRoutingLine", please add the following event:

![image](https://user-images.githubusercontent.com/82493733/114661254-ffa7b180-9cf6-11eb-96d4-2acf3a3303d7.png)

![image](https://user-images.githubusercontent.com/82493733/114661305-151cdb80-9cf7-11eb-9487-c8da9a249c73.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
