### ISSUE TITLE
{Event Request] Table 5870 "BOM Buffer" RoundCosts

### ISSUE THREAD

**Issue by THillemeier** [microsoft/ALAppExtensions#12014]
Hello,

In Table 5870, please add the following event in function "RoundCosts":

![image](https://user-images.githubusercontent.com/82493733/114660832-45b04580-9cf6-11eb-842f-96ac5925b521.png)

![image](https://user-images.githubusercontent.com/82493733/114660868-506ada80-9cf6-11eb-826a-8e4538d9865e.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
