### ISSUE TITLE
Table 36 Sales Header in GetNoSeriesCode

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [Microsoft/ALAppExtensions#1201]
Please insert a new Publisher in function GetNoSeriesCode

OnBeforeGetNoSeriesCode(Rec,SalesSetup,NoSeriesCode,Handled);
if Handled then
  exit;

**Comment by fvet** [comment]
@jobulsin 

I wonder the usecase for the OnBeforeGetNoSeriesCode publisher since it provides no option to set the **return value** (Code[20]) of the GetNoSeriesCode function, neither do I see a reason to pass a local variable 'NoSeriesCode' ??

**Comment by ThorstenEngelsGOB** [comment]
@jobulsin Hm, I think I created the request to keep the code the same as in the TestNoSeries function, for example. I also wanted to be able to use my own number series for documents in order to control them using an indicator. But you are right, the required subscriber is not necessary, because the following subscriber OnAfterGetNoSeriesCode can do this as well. The entry can be deleted/rejected. Kind regards

**Comment by JalmarazMartn** [comment]
Not completly done: I think the code must be this way:

OnBeforeGetNoSeriesCode(Rec,SalesSetup,NoSeriesCode,Handled);
if Handled then
exit(**NoSeriesCode**);

If we don´t return **NoSeriesCode**, the event isn´t so usefull.

Please can you review this? Regards.
