### ISSUE TITLE
[Event Request] Codeunit 6500 "Item Tracking Management" on the local procedure SynchronizeItemTracking2

### ISSUE THREAD

**Issue by sauerkreut** [microsoft/ALAppExtensions#12013]
Hi team,
we would like to request an event on the local procedure SynchronizeItemTracking2 on the "Item Tracking Management"-Codeunit (6500)

On the local procedure SynchronizeItemTracking2 you find the following code block:

            TempTrkgSpec1.Reset();
            TempTrkgSpec2.Reset();
            TempTrkgSpec1.SetCurrentKey("Lot No.", "Serial No.");
            TempTrkgSpec2.SetCurrentKey("Lot No.", "Serial No.");
            if TempTrkgSpec1.FindSet then
                repeat
                    TempTrkgSpec2.SetTrackingFilterFromSpec(TempTrkgSpec1);
                    if TempTrkgSpec2.FindFirst then begin
                        if TempTrkgSpec2."Quantity (Base)" * SignFactor2 <> TempTrkgSpec1."Quantity (Base)" * SignFactor1 then begin
                            TempTrkgSpec3 := TempTrkgSpec2;
                            TempTrkgSpec3.Validate("Quantity (Base)",
                              (TempTrkgSpec1."Quantity (Base)" * SignFactor1 - TempTrkgSpec2."Quantity (Base)" * SignFactor2));
                            TempTrkgSpec3."Entry No." := LastEntryNo + 1;
                            TempTrkgSpec3.Insert();
                        end;
                        TempTrkgSpec2.Delete();
                    end else begin
                        TempTrkgSpec3 := TempTrkgSpec1;
                        TempTrkgSpec3.Validate("Quantity (Base)", TempTrkgSpec1."Quantity (Base)" * SignFactor1);
                        TempTrkgSpec3."Entry No." := LastEntryNo + 1;
                        TempTrkgSpec3.Insert();
                    end;
                    LastEntryNo := TempTrkgSpec3."Entry No.";
                    TempTrkgSpec1.Delete();
                until TempTrkgSpec1.Next = 0;

Due to an IF-statement we can't reach the "TempTrkgSpec3.Insert();" statement. We have further conditions (OR) on that IF-statement. Therefor we request the following event to handle it by our self: 

                    if TempTrkgSpec2.FindFirst then begin
                        // Implementation
                        OnBeforeInsertTempItemTrkgSpec3(TempTrkgSpec2, TempTrkgSpec3, IsHandled);
                        if not IsHandled then 
                        // Implementation
                            if TempTrkgSpec2."Quantity (Base)" * SignFactor2 <> TempTrkgSpec1."Quantity (Base)" * SignFactor1 then begin
                                TempTrkgSpec3 := TempTrkgSpec2;
                                TempTrkgSpec3.Validate("Quantity (Base)",
                                (TempTrkgSpec1."Quantity (Base)" * SignFactor1 - TempTrkgSpec2."Quantity (Base)" * SignFactor2));
                                TempTrkgSpec3."Entry No." := LastEntryNo + 1;
                                TempTrkgSpec3.Insert();
                            end;
                        TempTrkgSpec2.Delete();
                    end else begin
                        TempTrkgSpec3 := TempTrkgSpec1;
                        TempTrkgSpec3.Validate("Quantity (Base)", TempTrkgSpec1."Quantity (Base)" * SignFactor1);
                        TempTrkgSpec3."Entry No." := LastEntryNo + 1;
                        TempTrkgSpec3.Insert();

Signature:

	[IntegrationEvent(false,false)]
	local procedure OnBeforeInsertTempItemTrkgSpec3(var TempTrkgSpec2: Record "Tracking Specification" temporary; var TempTrkgSpec3: Record "Tracking Specification" temporary; IsHandled: Boolean)
	begin
	end;

Thank you for your attention/
sauerkreut

**Comment by sauerkreut** [comment]
@StanPesotskiy ,
I hope it's not too late. I was wrong with my Event and the signature. Can you please implement it like this:
                    // Implementation
                    OnBeforeInsertTempItemTrkgSpec3(TempTrkgSpec1, TempTrkgSpec2, TempTrkgSpec3, IsHandled);

with this signature:
        [IntegrationEvent(false,false)]
        local procedure OnBeforeInsertTempItemTrkgSpec3(var TempTrkgSpec1: Record "Tracking Specification" temporary; var TempTrkgSpec2: Record "Tracking Specification" temporary; var TempTrkgSpec3: Record "Tracking Specification" temporary; IsHandled: Boolean)
        begin
        end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
