### ISSUE TITLE
[Event Request] Table 32 (ILE) - FilterLinesWithItemToPlan

### ISSUE THREAD

**Issue by ephilpott** [microsoft/ALAppExtensions#12012]
Hello,

I am requesting that a new event publisher be added to Table 32 "Item Ledger Entry" in function FilterLinesWithItemToPlan for the ability to apply further filters to the ILE. Something like:

OnAfterSetFilterLinesWithItemToPlan(var Rec: Record "Item Ledger Entry";Item : Record Item;NetChange : Boolean)

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
