### ISSUE TITLE
[Event Request] Table 5896 "Inventory Adjmt. Entry (Order)" CalcDiff

### ISSUE THREAD

**Issue by THillemeier** [microsoft/ALAppExtensions#12016]
Hello,

in table 5896 "Inventory Adjmt. Entry (Order)", function CalcDiff, please add the following event:

![image](https://user-images.githubusercontent.com/82493733/114661726-c15ec200-9cf7-11eb-8585-1e76b21be9dc.png)

![image](https://user-images.githubusercontent.com/82493733/114661787-db000980-9cf7-11eb-9426-4fbea640e1e8.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
