### ISSUE TITLE
[Event Request] Codeunit 1535 "Approvals Mgmt." - OnBeforeApproveApprovalRequests

### ISSUE THREAD

**Issue by nybragaramos** [microsoft/ALAppExtensions#12010]
Hi,
In codeunit 1535 "Approvals Mgmt.", function ApproveApprovalRequests please add the following event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeApproveApprovalRequests(var ApprovalEntry: Record "Approval Entry"; var IsHandled: Boolean)
    begin
    end;

    procedure ApproveApprovalRequests(var ApprovalEntry: Record "Approval Entry")
    var
        ApprovalEntryToUpdate: Record "Approval Entry";
        IsHandled: Boolean;
    begin
        //------> NEW
        IsHandled := false;
        OnBeforeRejectApprovalRequests(ApprovalEntry, IsHandled);
        if IsHandled then
            exit;
        //<------ NEW

        if ApprovalEntry.FindSet() then
            repeat
                ApprovalEntryToUpdate := ApprovalEntry;
                ApproveSelectedApprovalRequest(ApprovalEntryToUpdate);
            until ApprovalEntry.Next = 0;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
