### ISSUE TITLE
[Event Request] - Report "OCR Payment - BBS" - OnCreatePayment

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#12028]
In function CreatePayment, can you add this event?

![image](https://user-images.githubusercontent.com/35260264/114690040-a0f23000-9d16-11eb-8bf4-f1b44288ee67.png)

![image](https://user-images.githubusercontent.com/35260264/114690108-b1a2a600-9d16-11eb-800c-a8b202336f26.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
