### ISSUE TITLE
[Event Request] Page 233 "Apply Vendor Entries" OnBeforePostDirectApplication

### ISSUE THREAD

**Issue by mfalk118** [microsoft/ALAppExtensions#12029]
Please implement same event as in page 232  local procedure PostDirectApplication(PreviewMode: Boolean) on page 233

    local procedure PostDirectApplication(PreviewMode: Boolean)
    var
        VendEntryApplyPostedEntries: Codeunit "VendEntry-Apply Posted Entries";
        PostApplication: Page "Post Application";
        Applied: Boolean;
        ApplicationDate: Date;
        NewApplicationDate: Date;
        NewDocumentNo: Code[20];
        IsHandled: Boolean; //PLEASE ADD
    begin
//>>PLEASE ADD START
        IsHandled := false;
        OnBeforePostDirectApplication(Rec, PreviewMode, IsHandled);
        if IsHandled then
            exit;
//<<PLEASE ADD END
        if CalcType = CalcType::Direct then begin

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
