### ISSUE TITLE
[Event Request] codeunit 550 VAT Rate Change Conversion - Function AreTablesSelected

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12038]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 550 function AreTablesSelected, of course without the prefix DIN.

            if "Update Purchase Documents" <> "Update Purchase Documents"::No then
                exit(true);
            if "Update Production Orders" <> "Update Production Orders"::No then
                exit(true);
            if "Update Work Centers" <> "Update Work Centers"::No then
                exit(true);
            if "Update Machine Centers" <> "Update Machine Centers"::No then
                exit(true);
            if "Update Reminders" <> "Update Reminders"::No then
                exit(true);
            if "Update Finance Charge Memos" <> "Update Finance Charge Memos"::No then
                exit(true);
            // DINNL <<
            DINIsHandled := false;
            DINOnAfterAreTablesSelected(VATRateChangeSetup, DINIsHandled);
            if DINIsHandled then
                exit(true);
            // DINNL >>
        end;
        exit(false)
    end;

    [IntegrationEvent(TRUE, false)]
    local procedure DINOnAfterAreTablesSelected(VATRateChangeSetup: Record "VAT Rate Change Setup"; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
