### ISSUE TITLE
[Event Request] codeunit 550 VAT Rate Change Conversion - Function UpdateTable

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12037]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 550 function UpdateTable, of course without the prefix DIN.

    begin
        // DINNL <<
        DINIsHandled := false;
        DINOnBeforeUpdateTable(TableID, DINIsHandled);
        if not DINIsHandled then
            exit;
        // DINNL >>
        if not ConvertVATProdPostingGroup and not ConvertGenProdPostingGroup then
            exit;
        RecRef.Open(TableID);
        ProgressWindow.Update(1, Format(RecRef.Caption));
        I := 0;
        ProgressWindow.Update(3, RecRef.Count);
        if RecRef.Find('-') then
            repeat
                I := I + 1;
                ProgressWindow.Update(2, I);
                UpdateRec(RecRef, ConvertVATProdPostingGroup, ConvertGenProdPostingGroup);
            until RecRef.Next() = 0;
    end;

    local procedure DINOnBeforeUpdateTable(TableIdPint: Integer; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
