### ISSUE TITLE
[Event Request] Codeunit 10750 SII XML Creator - OnBeforeGenerateXMLOnCloud

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#12039]
In the Codeunit 10750 "SII XML Creator", there are a event called "OnBeforeGenerateXML"

**OnBeforeGenerateXML(LedgerEntry, XMLDocOut, UploadType, IsCreditMemoRemoval, ResultValue, IsHandled);**

that has a parameter of type DotNet XMLDocument.

In a Cloud scenario, our code of this event cannot use Dotnet variables. So, in the event, we cannot create a different Xml. 

Then, we need a new event, that pass a parameter of type XMLDocument, and after call it, in BC, converts to a DotNet XMLDocument. Another solution, may be change all calls of DotNet XmlDocument to XmlDocument, in all call procedures.

In the first case, the new event must be:

**local procedure OnBeforeGenerateXMLOnCloud(LedgerEntry: Variant; var XMLDocOut: DotNet XmlDocument;var XMLDocOutXmlDocument: XmlDocument; UploadType: Option; IsCreditMemoRemoval: Boolean; var ResultValue: Boolean; var IsHandled: Boolean)**

called from:

**procedure GenerateXml(LedgerEntry: Variant; var XMLDocOut: DotNet XmlDocument; UploadType: Option; IsCreditMemoRemoval: Boolean): Boolean**
    var
        CustLedgerEntry: Record "Cust. Ledger Entry";
        VendorLedgerEntry: Record "Vendor Ledger Entry";
        DetailedCustLedgEntry: Record "Detailed Cust. Ledg. Entry";
        DetailedVendorLedgEntry: Record "Detailed Vendor Ledg. Entry";
        RecRef: RecordRef;
        IsHandled: Boolean;
        ResultValue: Boolean;
	XMLDocOutXmlDocument: XmlDocument;
    begin
        IsHandled := false;
        OnBeforeGenerateXML(LedgerEntry, XMLDocOut, UploadType, IsCreditMemoRemoval, ResultValue, IsHandled);
        IF IsHandled THEN
            EXIT(ResultValue);
        **//INIT INSERT
        OnBeforeGenerateXMLCloud(LedgerEntry, XMLDocOut, XMLDocOutXmlDocument, UploadType, IsCreditMemoRemoval, ResultValue, IsHandled);
        if IsHandled then begin
	    //------------------
	    This code is on BC. Copy  XMLDocOutXmlDocument to XmlDocument  
              xmldocout := XMLDocOutXmlDocument;
	    --------------------//
            EXIT(ResultValue);
        end;
	//END INSERT**
        GetSIISetup;
        SiiTxt := SIISetup."SuministroInformacion Schema";
        SiiLRTxt := SIISetup."SuministroLR Schema";
        if not IsInitialized then
            XMLDocOut := XMLDocOut.XmlDocument;
	......

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
