### ISSUE TITLE
[Event Request] codeunit 378 Transfer Extended Text - Function InsertSalesExtTextRetLast

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12035]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 378 function InsertSalesExtTextRetLast, of course without the prefix DIN.

        OnBeforeInsertSalesExtText(SalesLine, TempExtTextLine, IsHandled, MakeUpdateRequired);
        if IsHandled then
            exit;

        ToSalesLine.Reset();
        ToSalesLine.SetRange("Document Type", SalesLine."Document Type");
        ToSalesLine.SetRange("Document No.", SalesLine."Document No.");
        ToSalesLine := SalesLine;
        // DINNL <<
        DINOnInsertSalesExtTextOnBeforeFindNext(ToSalesLine);
        // DINNL >>
        if ToSalesLine.Find('>') then begin
            LineSpacing :=
              (ToSalesLine."Line No." - SalesLine."Line No.") div
              (1 + TempExtTextLine.Count);
            if LineSpacing = 0 then
                Error(Text000);
        end else
            LineSpacing := 10000;

    local procedure DINOnInsertSalesExtTextOnBeforeFindNext(var SalesLine: Record "Sales Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
