### ISSUE TITLE
Change "Line No." and LineSpacing in InsertPostedWhseShptLine and InsertPostedWhseRcptLine in codeunit 7320 "Whse. Undo Quantity"

### ISSUE THREAD

**Issue by stephanpl** [microsoft/ALAppExtensions#12036]
In our add-on, we use consecutive line numbers, raised by one, assigned to lines within a certain group. 
This caused the undo functions for such grouped lines to fail because there is no line spacing between the lines in such a group.
With your help, we already were able to solve this issue in several other places.

But there still is an issue with warehouse undo.
In this situation, we are missing a suitable point of departure, a publisher.
What we would need is a way to manipulate at least the Linespacing and the “Line No.” field of the OldPostedWhseShptLine record variable in the local procedure called InsertPostedWhseShptLine in codeunit 7320 "Whse. Undo Quantity".
To enable this, we could use a publisher with an Ishandled parameter and Linespacing and “Line No.” of the OldPostedWhseShptLine as parameters.

Something like this:

    local procedure InsertPostedWhseShptLine(OldPostedWhseShptLine: Record "Posted Whse. Shipment Line")
    var
        NewPostedWhseShptLine: Record "Posted Whse. Shipment Line";
        LineSpacing: Integer;
    begin
            ...

            OnBeforeSetLineSpacing(OldLineNo,LineSpacing,IsHandled);
            if not IsHandled then 
                if NewPostedWhseRcptLine.Find('>') then begin
                    LineSpacing := (NewPostedWhseRcptLine."Line No." - "Line No.") div 2;
                    if LineSpacing = 0 then
                        Error(Text001);
                end else
                    LineSpacing := 10000;

            ...
            
            NewPostedWhseRcptLine.Copy(OldPostedWhseRcptLine);
            // NewPostedWhseRcptLine."Line No." := "Line No." + LineSpacing;
            NewPostedWhseRcptLine."Line No." := OldLineNo + LineSpacing;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetLineSpacing (var OldLineNo: Integer; var LineSpacing: Integer; var IsHandled: Boolean)
    begin
    end;

Alternatively, you could make the parameter  OldPostedWhseRcptLine of the publisher procedure OnBeforeOldPostedWhseRcptLineModify to be passed by reference (=var). This will also do for us.

The same applies to the local procedure called InsertPostedWhseRcptLine in the same codeunit.

**Comment by Oleg-Romashkov** [comment]
Could you check if following solution fits you need?
![image](https://user-images.githubusercontent.com/82887855/115666823-b63a1080-a34d-11eb-965d-f261604aa7e7.png)
![image](https://user-images.githubusercontent.com/82887855/115666903-d4a00c00-a34d-11eb-892d-8a4e13daccf4.png)

**Comment by stephanpl** [comment]
Dear Oleg,

Thank you for your quick response.
I estimate indeed that the proposed solution will fit our needs.
Best regards,

Stephan Pluijmers
Developer

[K3pebblestone on appsource ***@***.***D73852.21F75510]

www.k3btg.com<http://www.k3btg.com/>

K3 Software Solutions (company number 50227580) is part of the K3 Business Technology Group plc registered in England and Wales, company number 02641001, at Baltimore House, 50 Kansas Avenue, Manchester M50 2GL United Kingdom. The information in this e-mail, and any attachments therein, is confidential and for use by the addressee only. If you are not the intended recipient, please return the e-mail to the sender and delete it from your computer. Any prices quoted in this e mail or its attachments are subject to our standard terms and conditions, which are available on request or from our web site. Although we attempt to sweep e-mail and attachments for viruses, we do not guarantee that either are virus-free and accept no liability for any damage sustained

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
