### ISSUE TITLE
[Event Request] codeunit 60 Sales-Calc. Discount - Function CalculateInvoiceDiscount

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12031]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 60 function CalculateInvoiceDiscount, of course without the prefix DIN.

            if SalesLine2.FindSet(true, false) then
                repeat
                    SalesLine2."Unit Price" := 0;
                    SalesLine2.Modify();
                    TempServiceChargeLine := SalesLine2;
                    TempServiceChargeLine.Insert();
                until SalesLine2.Next() = 0;

            SalesLine2.Reset();
            SalesLine2.SetRange("Document Type", "Document Type");
            SalesLine2.SetRange("Document No.", "Document No.");
            SalesLine2.SetFilter(Type, '<>0');
            // DINNL <<
            DINOnCalculateInvoiceDiscount(SalesLine2);
            // DINNL >>
            if SalesLine2.FindFirst then;

    local procedure DINOnCalculateInvoiceDiscount(var SalesLine: Record "Sales Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
