### ISSUE TITLE
RemainingQtyToReserve is passed twice in OnBeforeAutoReserveSalesLine 

### ISSUE THREAD

**Issue by louagej** [microsoft/ALAppExtensions#12034]
## Version

- W1 18.0 (Platform 18.0.22893.23773 Application 18.0.23013.23795)

### Function AutoReserveSalesLine ()

when Calling OnBeforeAutoReserveSalesLine, the variable RemainingQtyToReserve is passed twice as a parameter instead of
`RemainingQtyToReserve` , `RemainingQtyToReserveBase`

Current function call is:
```al
OnBeforeAutoReserveSalesLine(ReservSummEntryNo, RemainingQtyToReserve, RemainingQtyToReserve, Description, AvailabilityDate, IsReserved, Search, NextStep, CalcReservEntry);
```

Based on the IntegrationEvent, I guess it should be
```al
OnBeforeAutoReserveSalesLine(ReservSummEntryNo, RemainingQtyToReserve, RemainingQtyToReserveBase, Description, AvailabilityDate, IsReserved, Search, NextStep, CalcReservEntry);
```

the IntegrationEvent looks like:
```al
[IntegrationEvent(false, false)]
    local procedure OnBeforeAutoReserveSalesLine(ReservSummEntryNo: Integer; var RemainingQtyToReserve: Decimal; var RemainingQtyToReserveBase: Decimal; Description: Text[100]; AvailabilityDate: Date; var IsReserved: Boolean; Search: Text[1]; NextStep: Integer; CalcReservEntry: Record "Reservation Entry")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
