### ISSUE TITLE
[EventRequest] Table 5902 "Service Line"

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#12030]
Could you please add event subscriber OnAfterValidateUnitPriceShowNonstock

    procedure ShowNonstock()
    var
        NonstockItem: Record "Nonstock Item";
    begin
        TestField(Type, Type::Item);
        TestField("No.", '');
        if PAGE.RunModal(PAGE::"Catalog Item List", NonstockItem) = ACTION::LookupOK then begin
            CheckNonstockItemTemplate(NonstockItem);

            "No." := NonstockItem."Entry No.";
            CatalogItemMgt.NonStockFSM(Rec);
            Validate("No.", "No.");
            Validate("Unit Price", NonstockItem."Unit Price");
            OnAfterValidateUnitPriceShowNonstock(Rec, xRec,);
        end;

        OnAfterShowNonstock(Rec);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterValidateUnitPriceShowNonstock(var ServiceLine: Record "Service Line"; var xServiceLine: Record "Service Line";)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
