### ISSUE TITLE
[Event Request] codeunit 87 Blanket Sales Order to Order - Function CheckAvailability

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12032]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 87 function CheckAvailability, of course without the prefix DIN.

            if FindSet then
                repeat
                    if "Qty. to Ship" > 0 then begin
                        SalesLine := BlanketOrderSalesLine;
                        ResetQuantityFields(SalesLine);
                        SalesLine.Quantity := "Qty. to Ship";
                        SalesLine."Quantity (Base)" := Round(SalesLine.Quantity * SalesLine."Qty. per Unit of Measure", UOMMgt.QtyRndPrecision);
                        SalesLine."Qty. to Ship" := SalesLine.Quantity;
                        SalesLine."Qty. to Ship (Base)" := SalesLine."Quantity (Base)";
                        SalesLine.InitOutstanding;
                        if ATOLink.AsmExistsForSalesLine(BlanketOrderSalesLine) then begin
                            SalesLine."Qty. to Assemble to Order" := SalesLine.Quantity;
                            SalesLine."Qty. to Asm. to Order (Base)" := SalesLine."Quantity (Base)";
                            SalesLine."Outstanding Quantity" -= SalesLine."Qty. to Assemble to Order";
                            SalesLine."Outstanding Qty. (Base)" -= SalesLine."Qty. to Asm. to Order (Base)";
                        end;
                        if SalesLine.Reserve <> SalesLine.Reserve::Always then
                            if not HideValidationDialog then
                                // DINNL <<
                                DINOnSalesLineCheckforBlanketOrder(DINIsHandled);
                                if DINIsHandled then
                                // DINNL >>
                                if ItemCheckAvail.SalesLineCheck(SalesLine) then
                                    ItemCheckAvail.RaiseUpdateInterruptedError;
                    end;
                until Next() = 0;

    local procedure DINOnSalesLineCheckforBlanketOrder(var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
