### ISSUE TITLE
[Feature Request] Page type Worksheet - Repeater control - selected row background colour not changed

### ISSUE THREAD

**Issue by HHynynen** [microsoft/ALAppExtensions#12048]
When a line is selected on a repeater control which is on a worksheet typed page the background colour of the row does not change. The only column where it changes is the column with three dots. It is necessary to be able to select the row and see which row is selected e.g. if there are a lot of columns and you need to click a checkbox on certain row. To avoid clicking the wrong row this selection should be visible. Colouring works fine on list pages but not on worksheet pages. 

Also the possibility to colour every other row with different background colour would be appreciated.

**Comment by HHynynen** [comment]
Here is an example picture:
![selected row](https://user-images.githubusercontent.com/70518711/114993669-b4330600-9ea4-11eb-9464-6eebaf601c94.jpg)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug or a suggestion not related to the AL **application** extensibility. Please reach out to the relevant support channels:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
