### ISSUE TITLE
[Event Request] OnBeforeAddItems on Purchase and Sales Lines

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#12041]
Hi ALAppExtension Team,

We would like to extend the functionality of already existing events in the purchase and sales lines to be like this:

![image](https://user-images.githubusercontent.com/64962632/114727843-da3e9600-9d3e-11eb-83dc-5edb45fdb5c0.png)

![image](https://user-images.githubusercontent.com/64962632/114728097-13770600-9d3f-11eb-930c-0df96c3238cf.png)

---

Before for Sales Line:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAddItems(var SalesLine: Record "Sales Line")
    begin
    end;
```

After for Sales Line:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAddItems(var SalesLine: Record "Sales Line"; SelectionFilter: Text)
    begin
    end;
```

---

Before for Purchase Line:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAddItems(var PurchaseLine: Record "Purchase Line")
    begin
    end;
```

After for Purchase Line:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAddItems(var PurchaseLine: Record "Purchase Line"; SelectionFilter: Text)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
