### ISSUE TITLE
[Event Request] Codeunit 5657

### ISSUE THREAD

**Issue by guidorobben** [Microsoft/ALAppExtensions#1204]
Add an event for the CopyFromJnlLine function

**Comment by JesperSchulz** [comment]
We would need a few more details before we can process this request. Where would you like the event? What parameters do you need? Please get inspired by other event requests about the level of details we need.

**Comment by guidorobben** [comment]
Hi Jesper.

I want it to work like the OnAfterCopyFromFAJnlLine function from codeunit 5647. I attached the codeunit on how I want it.

[Cod5657.txt](https://github.com/Microsoft/ALAppExtensions/files/2863976/Cod5657.txt)
