### ISSUE TITLE
[Request-for-external] table 77 "Report Selections" - GetEmailAddressIgnoringLayout

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#12049]
Can you change procedure GetEmailAddressIgnoringLayout to global in table 77 "Report Selections"?

I need to check if the email is going to be sent via job queue or directly.
Even better would be to get the lines marked with yellow in its own procedure and call that procedure instead..
![image](https://user-images.githubusercontent.com/46031720/114991523-f60a7f00-9e99-11eb-8391-e05d6956d78b.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
