### ISSUE TITLE
[Event Request] codeunit 550 VAT Rate Change Conversion - Function UpdateServPriceAdjDetail

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12040]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 550 function UpdateServPriceAdjDetail, of course without the prefix DIN.

    begin
        // DINNL <<
        DINIsHandled := false;
        DINOnBeforeUpdateServPriceAdjDetail(DATABASE::"Serv. Price Adjustment Detail", DINIsHandled);
        if not DINIsHandled then
            exit;
        // DINNL >>
        if VATRateChangeSetup."Update Serv. Price Adj. Detail" <>
           VATRateChangeSetup."Update Serv. Price Adj. Detail"::"Gen. Prod. Posting Group"
        then
            exit;
        VatRateChangeConversion.SetRange(Type, VatRateChangeConversion.Type::"Gen. Prod. Posting Group");
        if VatRateChangeConversion.FindSet then
            repeat
                with ServPriceAdjustmentDetail do begin

    local procedure DINOnBeforeUpdateServPriceAdjDetail(TableIdPint: Integer; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
