### ISSUE TITLE
[Event Request] codeunit 550 VAT Rate Change Conversion - Function CanUpdateSales

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12042]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 550 function CanUpdateSales, of course without the prefix DIN.

            SetRange("Document Type", SalesHeader."Document Type");
            SetRange("Document No.", SalesHeader."No.");
            if FindSet then
                repeat
                    DescriptionTxt := '';
                    if LineInScope("Gen. Prod. Posting Group", "VAT Prod. Posting Group", ConvertGenProdPostingGroup, ConvertVATProdPostingGroup) then begin
                        if "Drop Shipment" and ("Purchase Order No." <> '') then
                            DescriptionTxt := StrSubstNo(Text0004, "Line No.");
                        if "Special Order" and ("Special Order Purchase No." <> '') then
                            DescriptionTxt := StrSubstNo(Text0005, "Line No.");
                        // DINNL <<
                        DINIsHandled := false;
                        DINOnCanUpdateSales(DATABASE::"Warehouse Shipment Header", DINIsHandled);
                        if DINIsHandled then
                        // DINNL >>
                        if ("Outstanding Quantity" <> Quantity) and
                           WhseValidateSourceLine.WhseLinesExist(DATABASE::"Sales Line", "Document Type".AsInteger(), "Document No.", "Line No.", 0, Quantity)
                        then
                            DescriptionTxt := Text0006;
                        if ("Outstanding Quantity" <> Quantity) and (Type = Type::"Charge (Item)") then
                            DescriptionTxt := StrSubstNo(Text0014, "Line No.", Type::"Charge (Item)");
                        if "Prepmt. Amount Inv. Incl. VAT" <> 0 then
                            DescriptionTxt := Text0011;
                        if "Qty. to Assemble to Order" <> 0 then
                            DescriptionTxt := Text0018;
                    end;
                until (Next() = 0) or (DescriptionTxt <> '');

    local procedure DINOnCanUpdateSales(TableIdPint: Integer; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
