### ISSUE TITLE
[Event Request] Codeunit "Cost Calculation Management"- Procedure "CalcProdOrderExpCapNeed"

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#12046]
We need a new PublisherEvent to re-calculate ExpectedCapNeed with some more data.
![image](https://user-images.githubusercontent.com/40287548/114830054-153adb00-9dcc-11eb-9c12-b830045bb0de.png)

For our needs please add the following parameters: 
- ExpectedCapNeed as "By Reference"
- ProdOrderRtngLine "By Value"
-  WorkCenter "By Value"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
