### ISSUE TITLE
[Event Request] Table 37 Sales Line - OnValidate Qty. to Assemble to Order

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12058]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 37 - OnValidate Qty. to Assemble to Order.

        field(900; "Qty. to Assemble to Order"; Decimal)
        {
            AccessByPermission = TableData "BOM Component" = R;
            Caption = 'Qty. to Assemble to Order';
            DecimalPlaces = 0 : 5;

            trigger OnValidate()
            var
                SalesLineReserve: Codeunit "Sales Line-Reserve";
            begin
                // DINNL <<
                IsHandled := false;
                OnValidateQuantityOnBeforeSalesLineVerifyChange(Rec, StatusCheckSuspended, IsHandled);
                if not IsHandled then
                // DINNL >>
                WhseValidateSourceLine.SalesLineVerifyChange(Rec, xRec);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
