### ISSUE TITLE
[Extensibility Enhancement] page 5806 "Purch. Receipt Lines"

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#12053]
Please change the FromPurchRcptLine variable so that the FlowFields can be added to this page on which the sorting can be used.

From
`FromPurchRcptLine: Record "Purch. Rcpt. Line";`
to

```
[SecurityFiltering(SecurityFilter::Filtered)]
FromPurchRcptLine: Record "Purch. Rcpt. Line";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
