### ISSUE TITLE
[Event Request] Table 5740 Transfer Header - OnValidate Direct Transfer

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12056]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 5740 - OnValidate Direct Transfer, of course without the prefix DIN.

        field(70; "Direct Transfer"; Boolean)
        {
            Caption = 'Direct Transfer';

            trigger OnValidate()
            var
                DINIsHandled: Boolean;
            begin
                if "Direct Transfer" then begin
                    VerifyNoOutboundWhseHandlingOnLocation("Transfer-from Code");
                    VerifyNoInboundWhseHandlingOnLocation("Transfer-to Code");
                    // DINNL <<
                    DINOnValidateDirectTransferOnBeforeValidateInTransitCode(Rec, DINIsHandled);
                    if not DINIsHandled then
                    // DINNL >>
                    Validate("In-Transit Code", '');
                end;

                Modify(true);
                UpdateTransLines(Rec, FieldNo("Direct Transfer"));
            end;

    local procedure DINOnValidateDirectTransferOnBeforeValidateInTransitCode(var TransferHeader: Record "Transfer Header"; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
