### ISSUE TITLE
[Event Request] Table 5767 Warehouse Activity Line - Function SplitLine

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12054]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 5767 - Function SplitLine, of course without the prefix DIN.

        CheckSplitLine(WhseActivLine);

        NewWhseActivLine := WhseActivLine;
        NewWhseActivLine.SetRange("No.", WhseActivLine."No.");
        if NewWhseActivLine.Find('>') then
            LineSpacing :=
              (NewWhseActivLine."Line No." - WhseActivLine."Line No.") div 2
        else
            LineSpacing := 10000;

        // DINNL <<
        DINOnSplitLineOnBeforeRenumberAllLines(WhseActivLine, LineSpacing);
        // DINNL >>
        if LineSpacing = 0 then
            ReNumberWhseActivityLines(NewWhseActivLine, WhseActivLine, NewLineNo, LineSpacing);

    local procedure DINOnSplitLineOnBeforeRenumberAllLines(var WarehouseActivityLine: Record "Warehouse Activity Line"; var LineSpacing: Integer)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
