### ISSUE TITLE
[Event Request] Table 39 Purchase Line - Add parameter to function OnValidateNoOnCopyFromTempPurchLine

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12057]
Dear ALAppExtensions Team,

Is it possible to add a parameter to function OnValidateNoOnCopyFromTempPurchLinein Table 39 ?
 -OnValidateNoOnCopyFromTempPurchLine(Rec, TempPurchLine);
+OnValidateNoOnCopyFromTempPurchLine(Rec, TempPurchLine, xRec);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
