### ISSUE TITLE
[Event Request] Table 5409 Prod. Order Routing Line - Function AdjustComponents

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12055]
Dear ALAppExtensions Team,

We would like to request the following event publisher in table 5409 - Function AdjustComponents, of course without the prefix DIN.

    local procedure AdjustComponents(var ProdOrderLine: Record "Prod. Order Line")
    var
        ProdOrderComp: Record "Prod. Order Component";
    begin
        // DINNL <<
        DINOnBeforeAdjustComponents(ProdOrderComp);
        // DINNL >>
        ProdOrderComp.SetRange(Status, Status);
        ProdOrderComp.SetRange("Prod. Order No.", "Prod. Order No.");
        ProdOrderComp.SetRange("Prod. Order Line No.", ProdOrderLine."Line No.");

        if ProdOrderComp.Find('-') then
            repeat
                ProdOrderComp.Validate("Routing Link Code");
                ProdOrderComp.Modify();
            until ProdOrderComp.Next() = 0;
    end;

    local procedure DINOnBeforeAdjustComponents(var ProdOrderComp: Record "Prod. Order Component")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
