### ISSUE TITLE
[Request-for-external] Table 83 Item Jornal Line - PhysInvtEntered as Protected Var

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12063]
Dear ALAppExtensions Team,

We would like to request the following : Is it possible to change the global variable "PhysInvtEntered" from var to Protected Var ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
