### ISSUE TITLE
[Event Request] codeunit 1535 Approvals Mgmt. - Function CreateApprReqForApprTypeWorkflowUserGroup

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12068]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 1535 function CreateApprReqForApprTypeWorkflowUserGroup, of course without the prefix DIN.

        with WorkflowUserGroupMember do begin
            SetCurrentKey("Workflow User Group Code", "Sequence No.");
            SetRange("Workflow User Group Code", WorkflowStepArgument."Workflow User Group Code");

            if not FindSet then
                Error(NoWFUserGroupMembersErr);

            repeat
                ApproverId := "User Name";
                if not UserSetup.Get(ApproverId) then
                    Error(WFUserGroupNotInSetupErr, ApproverId);
                // DINNL <<
                DINOnCheckIfApprovalEntryWillNotBeApproved(WorkflowUserGroupMember, DINIsHandled);
                if DINIsHandled then
                // DINNL >>
                MakeApprovalEntry(ApprovalEntryArgument, SequenceNo + "Sequence No.", ApproverId, WorkflowStepArgument);
            until Next() = 0;
        end;

    local procedure DINOnCheckIfApprovalEntryWillNotBeApproved(var WorkflowUserGroupMember: Record "Workflow User Group Member"; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
