### ISSUE TITLE
[Event Request] codeunit 1535 Approvals Mgmt. - Function RejectSelectedApprovalRequest

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12067]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 1535 function RejectSelectedApprovalRequest, of course without the prefix DIN.

    local procedure RejectSelectedApprovalRequest(var ApprovalEntry: Record "Approval Entry")
    begin
        if ApprovalEntry.Status <> ApprovalEntry.Status::Open then
            Error(RejectOnlyOpenRequestsErr);

        if ApprovalEntry."Approver ID" <> UserId then
            CheckUserAsApprovalAdministrator(ApprovalEntry);

        OnRejectApprovalRequest(ApprovalEntry);
        ApprovalEntry.Get(ApprovalEntry."Entry No.");
        ApprovalEntry.Validate(Status, ApprovalEntry.Status::Rejected);
        ApprovalEntry.Modify(true);
        // DINNL <<
        DINOnAfterRejectSelectedApprovalRequest(ApprovalEntry);
        // DINNL >>
    end;

    local procedure DINOnAfterRejectSelectedApprovalRequest(var ApprovalEntry: Record "Approval Entry")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
