### ISSUE TITLE
Codeunit 229 "Document-Print" change accessibility to global

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/ALAppExtensions#12062]
Hello,

in the codeunit 229 "Document-Print" is one function still local, all the other functions which are in the same context are global.

`local procedure GetServHeaderDocTypeUsage(ServiceHeader: Record "Service Header"): Enum "Report Selection Usage"`

Please change this one too to global, like this function:
`procedure GetSalesDocTypeUsage(SalesHeader: Record "Sales Header") ReportSelectionUsage: Enum "Report Selection Usage"`

That would be great.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
