### ISSUE TITLE
[Event Request] Codeunit 1535 Approvals Mgmt - Add parameter to function OnBeforeApprovalEntryInsert

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12069]
Dear ALAppExtensions Team,

Is it possible to add a parameter to function OnBeforeApprovalEntryInsert in codeunit 1535 ?

-OnBeforeApprovalEntryInsert(ApprovalEntry, ApprovalEntryArgument);
+OnBeforeApprovalEntryInsert(ApprovalEntry, ApprovalEntryArgument,WorkflowStepArgument);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
