### ISSUE TITLE
[Event Request] codeunit 1535 Approvals Mgmt. - Function CanCancelApprovalForRecord 

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12070]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 1535 function CanCancelApprovalForRecord , of course without the prefix DIN.

    begin
        if not UserSetup.Get(UserId) then
            exit(false);

        ApprovalEntry.SetRange("Table ID", RecID.TableNo);
        ApprovalEntry.SetRange("Record ID to Approve", RecID);
        ApprovalEntry.SetFilter(Status, '%1|%2', ApprovalEntry.Status::Created, ApprovalEntry.Status::Open);
        ApprovalEntry.SetRange("Related to Change", false);

        // DINNL <<
        DINOnCanCancelApprovalForRecord(ApprovalEntry, DINIsHandled);
        if not DINIsHandled then
        // DINNL >>
        if not UserSetup."Approval Administrator" then
            ApprovalEntry.SetRange("Sender ID", UserId);
        Result := ApprovalEntry.FindFirst();
        OnAfterCanCancelApprovalForRecord(RecID, Result);
    end;

    local procedure DINOnCanCancelApprovalForRecord(var ApprovalEntry: Record "Approval Entry"; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by ITPW666** [comment]
Where is this publisher?
![obraz](https://github.com/microsoft/ALAppExtensions/assets/156428286/b470c89b-f3a0-4592-99f6-7407eef3189c)

From BC 23.0.12034.14561

    procedure CanCancelApprovalForRecord(RecID: RecordID) Result: Boolean
    var
        ApprovalEntry: Record "Approval Entry";
        UserSetup: Record "User Setup";
    begin
        if not UserSetup.Get(UserId) then
            exit(false);

        ApprovalEntry.SetRange("Table ID", RecID.TableNo);
        ApprovalEntry.SetRange("Record ID to Approve", RecID);
        ApprovalEntry.SetFilter(Status, '%1|%2', ApprovalEntry.Status::Created, ApprovalEntry.Status::Open);
        ApprovalEntry.SetRange("Related to Change", false);

        if not UserSetup."Approval Administrator" then
            ApprovalEntry.SetRange("Sender ID", UserId);
        Result := ApprovalEntry.FindFirst();
        OnAfterCanCancelApprovalForRecord(RecID, Result, ApprovalEntry, UserSetup);
    end;

**Comment by ITPW666** [comment]
[@JesperSchulz](https://twitter.com/JesperSchulz)

> Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
@AlexanderYakunin, could you look into this case? The publisher doesn't seem to exist.

**Comment by AlexanderYakunin** [comment]
You can use existing event OnAfterCanCancelApprovalForRecord(RecID, Result, ApprovalEntry, UserSetup) to achieve same result. No need to add extra event here.
