### ISSUE TITLE
Extend codeunit 99000835 "Item Jnl. Line-Reserve"::OnBeforeVerifyQuantity() event

### ISSUE THREAD

**Issue by bcbrain** [microsoft/ALAppExtensions#12074]
Please extend OnBeforeVerifyQuantity():216 with handled-pattern **var isHandled : Boolean** and access to **Blocked:218** and **var ReservMgt**

File: ItemJnlLineReserve.Codeunit.al
212:     procedure VerifyQuantity(var NewItemJnlLine: Record "Item Journal Line"; var OldItemJnlLine: Record "Item Journal Line")
213:     var
214:         ItemJnlLine: Record "Item Journal Line";
215:     begin
216:         OnBeforeVerifyQuantity(NewItemJnlLine, OldItemJnlLine);

File: ItemJnlLineReserve.Codeunit.al
218:         if Blocked then
219:             exit;

as this would allow for custom logic regarding removal of reserve-entries.

thanks
fabian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
