### ISSUE TITLE
[Event Request] Codeunit 7313 Create Put-away - OnAfterGetDefaultBin

### ISSUE THREAD

**Issue by GaryFrostick2** [microsoft/ALAppExtensions#12072]
In the Create Put-away codeunit (7313) is it possible to have a new event in the code procedure as follows:

//Existing Code
   end else begin
                Clear(Bin);
                if WMSMgt.GetDefaultBin("Item No.", "Variant Code", "Location Code", Bin.Code) then
                    Bin.Get(Location.Code, Bin.Code);
                QtyToPutAwayBase := RemQtyToPutAwayBase;
                CalcQtyToPutAway(false, false);
            end;

//New Code
   end else begin
                Clear(Bin);
                if WMSMgt.GetDefaultBin("Item No.", "Variant Code", "Location Code", Bin.Code) then
                    Bin.Get(Location.Code, Bin.Code);
                OnAfterCodeGetDefaultBin("Item No.", "Variant Code", "Location Code", Bin) then
                QtyToPutAwayBase := RemQtyToPutAwayBase;
                CalcQtyToPutAway(false, false);
            end;

Currently there are events to handle the selection of a bin for directed pick and put-away scenarios but it is impossible to influence the bin selection for non directed pick and put-away scenarios The proposed event will allow the default bin to be altered by passing the selected bin record.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
