### ISSUE TITLE
[Event Request] Codeunit 5720 "Item Reference Management" - OnFillItemReferenceFromItemVendorBeforeCheckUnitOfMeasure

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#12075]
Hi, would it be possible to get an event **OnFillItemReferenceFromItemVendorBeforeCheckUnitOfMeasure** in codeunit 5720 (**Item Reference Management**), like this:

```
local procedure FillItemReferenceFromItemVendor(var ItemReference: Record "Item Reference"; ItemVend: Record "Item Vendor")
    var
        IsHandled: Boolean;
    begin
        ItemReference.Init();
        ItemReference.Validate("Item No.", ItemVend."Item No.");
        ItemReference.Validate("Variant Code", ItemVend."Variant Code");
        ItemReference.Validate("Reference Type", ItemReference."Reference Type"::Vendor);
        ItemReference.Validate("Reference Type No.", ItemVend."Vendor No.");
        ItemReference."Reference No." := ItemVend."Vendor Item No.";
        IsHandled := false;
        OnFillItemReferenceFromItemVendorBeforeCheckUnitOfMeasure(ItemReference,IsHandled)
        if ItemReference."Unit of Measure" = '' then begin
            Item.Get(ItemVend."Item No.");
            ItemReference.Validate("Unit of Measure", Item."Base Unit of Measure");
        end;
    end;
```

```
[IntegrationEvent(false, false)]
local procedure OnFillItemReferenceFromItemVendorBeforeCheckUnitOfMeasure(var ItemReference: Record "Item Reference"; var IsHandled: Boolean)
begin
end;
```

Thanks

**Comment by SteinleMossWahlers** [comment]
Hello, there is still one line of code missing:

local procedure FillItemReferenceFromItemVendor(var ItemReference: Record "Item Reference"; ItemVend: Record "Item Vendor")
    var
        IsHandled: Boolean;
    begin
        ItemReference.Init();
        ItemReference.Validate("Item No.", ItemVend."Item No.");
        ItemReference.Validate("Variant Code", ItemVend."Variant Code");
        ItemReference.Validate("Reference Type", ItemReference."Reference Type"::Vendor);
        ItemReference.Validate("Reference Type No.", ItemVend."Vendor No.");
        ItemReference."Reference No." := ItemVend."Vendor Item No.";
        IsHandled := false;
        OnFillItemReferenceFromItemVendorBeforeCheckUnitOfMeasure(ItemReference,IsHandled)
        **if not IsHandled then**
          if ItemReference."Unit of Measure" = '' then begin
              Item.Get(ItemVend."Item No.");
              ItemReference.Validate("Unit of Measure", Item."Base Unit of Measure");
          end;
    end;

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
