### ISSUE TITLE
[Event Request] Codeunit 8622 "Config. Insert With Validation" - OnBeforeInsertWithValidation

### ISSUE THREAD

**Issue by YellowOrangeTree** [microsoft/ALAppExtensions#12085]
Dear ALAppExtensions team,

we currently have issues with importing Rapid Start Package. Therefore we would like to request an event to be added to the Codeunit 8622 "Config. Insert With Validation".

    local procedure InsertWithValidation()
    // S/ Event Request
    var
        IsHandled: Boolean;
    // E/ Event Request
    begin
        // S/ Event Request
        OnBeforeInsertWithValidation(RecRefToInsert, IsHandled);
        if not IsHandled then
            // E/ Event Request
            RecRefToInsert.Insert(true);
    end;

    // S/ Event Request
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertWithValidation(var RecRefToInsert: RecordRef; var IsHandled: Boolean)
    begin
    end;
    // E/ Event Request

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
