### ISSUE TITLE
[Event Request] Codeunit 8611 "Config. Package Management" - InsertPackageRecord

### ISSUE THREAD

**Issue by YellowOrangeTree** [microsoft/ALAppExtensions#12084]
Dear ALAppExtensions team, 

we currently have issues with importing Rapid Start Package. Therefore we would like to request a couple of events to be added to the Codeunit 8611 "Config. Package Management". Requested changes are shown in the attachment to this post and marked using tags as such:
// S/ Event Request
OnBefore...
// E/ Event Request

Requested Events:

-  OnInsertRecordOnBeforeInsertRecRef(RecRef, ConfigPackageRecord, IsHandled)
-  OnModifyRecordDataFieldsOnBeforeRecRefInsert(RecRef, ConfigPackageTable, IsHandled);
-  OnModifyRecordDataFieldsOnBeforeRecRefModify(RecRef, ConfigPackageTable, RecordsModifiedCount, IsHandled);

[ConfigPackageManagement.txt](https://github.com/microsoft/ALAppExtensions/files/6343992/ConfigPackageManagement.txt)

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
