### ISSUE TITLE
[EventRequest] Codeunit 11 "Gen. Jnl.-Check Line" OnBeforeCheckAppliesToID

### ISSUE THREAD

**Issue by hparusel** [microsoft/ALAppExtensions#12088]
Hi there,
we need to extend the behaviour of the Journal Check for "Applies-to ID" in Codeunit 11 "Gen. Jnl.-Check Line" OnBeforeCheckAppliesToID. 

We (akquinet) have a module for Open Ledger Entries and need to make it possible to apply G/L Entries. Currently, there is the following check in the codeunit mentioned above, which does not allow us to do applications based on "Applies-to ID":

` if (("Account Type" = "Account Type"::"G/L Account") and
    ("Bal. Account Type" = "Bal. Account Type"::"G/L Account")) or
    ("Applies-to Doc. No." <> '')
 then
     LogTestField(GenJnlLine, FieldNo("Applies-to ID"), '');`

Could you move this check into a separate function with an "IsHandled" pattern and including an event? 

Similar to the existing check "CheckAppliesToDocNo" (also in Codeunit 11):

`if ("Account Type" = "Account Type"::"G/L Account") and
   ("Bal. Account Type" = "Bal. Account Type"::"G/L Account")
then
    CheckAppliesToDocNo(GenJnlLine); 
`

    local procedure CheckAppliesToDocNo(GenJnlLine: Record "Gen. Journal Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := true;
        OnBeforeCheckAppliesToDocNo(GenJnlLine, IsHandled);
        if IsHandled then
            exit;

        LogTestField(GenJnlLine, GenJnlLine.FieldNo("Applies-to Doc. No."), '');
    end;

**Comment by AlexanderYakunin** [comment]
We already have this.

**Comment by hparusel** [comment]
Hi,
could you point out where this is impelmented? I just checked the current Version and there is still the following check:

`if (("Account Type" = "Account Type"::"G/L Account") and
    ("Bal. Account Type" = "Bal. Account Type"::"G/L Account")) or
    ("Applies-to Doc. No." <> '')
then
   LogTestField(GenJnlLine, FieldNo("Applies-to ID"), '');`

This leads to an Testfielderror as soon as "Account Type" = "Account Type"::"G/L Account" and "Bal. Account Type" = "Bal. Account Type"::"G/L Account" and field "Applies-to ID" is filled. Because our extensions enables the user to apply G/L Accounts to each other this is a valid case and should not lead to a Testfield-Error.

Thanks in advance!
