### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnBeforeCheckLine

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#12080]
Hi, would it be possible to get an event OnBeforeCheckLine Page 6510 "Item Tracking Lines" , like this :

```
    local procedure CheckLine(TrackingLine: Record "Tracking Specification")
    begin
        OnBeforeCheckLine(Rec);
        if TrackingLine."Quantity (Base)" * SourceQuantityArray[1] < 0 then
            if SourceQuantityArray[1] < 0 then
                Error(Text002, Text003)
            else
                Error(Text002, Text004);
    end;

```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckLine(var Rec: Record "Tracking Specification")
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
