### ISSUE TITLE
Excel Report Builder functionality from RU version - move to W1

### ISSUE THREAD

**Issue by sergeyol** [microsoft/ALAppExtensions#12087]
Russian localization for Business Central contains Excel Report Builder functionality that allows to create Excel reports similar to how one would create Word report. You are able to define a template with sections (e.g. header, line, footer) and then build a report adding section by section and filling them with data.

This functionality allows to create precise layouts which is important when you need to create sophisticated reporting documentation. It is also quite universal.

The module consists of:

1. .NET library Microsoft.Dynamics.NAV.RU.ExcelReportBuilder.dll, which uses OpenXML to do the job
2. Several AL files: 
- ExcelReportBuilderManager.Codeunit.al
- ExcelTemplate.Table.al
- ExcelTemplates.Page.al
- ExcelTemplateSection.Table.al
- ExcelTemplateSheet.Table.al
- ExcelTemplateSheetBuffer.Table.al

Please consider making this functionality available as part of W1 base (or system) application.

Also, if the decision to move to W1 would be positive, we would like to share our small and safe updates to the .NET library that expand its features.

**Comment by StanPesotskiy** [comment]
For the new features please submit a product suggestion on https://aka.ms/bcideas

**Comment by sergeyol** [comment]
Thanks for response, I have created an idea request: https://experience.dynamics.com/ideas/idea/?ideaid=6ef3e67f-92a2-eb11-89ee-0003ff45c351

Considered this a technical decision and not a new idea though.

**Comment by StanPesotskiy** [comment]
Thank you very much.
