### ISSUE TITLE
[Event Request] Table 83 "Item Journal Line" - OnValidateItemNoOnAfterProdOrderCompSetFilters #11595 missing parameter

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#12089]
Please see #11595 - the IsHandled in source code and the parameter itself in the event is still missing. Please provide asap, thanks - otherwise the provided event isn't really helpful :(.

**Comment by Oleg-Romashkov** [comment]
The request #11595 has been already implemented and will be available in nearest update - 18.1

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
