### ISSUE TITLE
Bugg: Possible to change value in non editable page field

### ISSUE THREAD

**Issue by CarlOhlsson** [microsoft/ALAppExtensions#12086]
While testing some of our custom I wanted to change the "ToBin" on the pick but noticed that it was non editable. However while trying to do so I still somehow managed to open the Lookup window as can be seen in the images below. I did some more digging into what was going on and can now reproduce it myself.

If standing the the line that contains the non editable field and you try to navigate and select the field "ToBin" it can not be selected as expected. However if standing on the line above or below where the same field is actually editable and you then click the "ToBin" field on the non editable line you can see the small lookup dots to the right. They seem to be visible until the arrow on the left moves to the new selected line. If the user is fast it is very easy to click the lookup icon and open up the bin selection page before it becomes non editable. Now all the user have to do is click OK and the new value is placed into "ToBin". 

This is not an AL code issue, it seems to be an issue with the web client and I think this is possible to do in many places. 

Please note: If you try my example you will get an error message from standard AL code, I have disabled this error in my customization. 

See my images below on how to reproduce this.

![NonEditableField](https://user-images.githubusercontent.com/11760980/115456460-77a83700-a223-11eb-804a-394df453ef1f.PNG)

![LookupSymbol](https://user-images.githubusercontent.com/11760980/115456457-77a83700-a223-11eb-9136-0494eb293a8b.png)

![SelectBin](https://user-images.githubusercontent.com/11760980/115456461-7840cd80-a223-11eb-8919-c94848ad5e8f.PNG)

![BinChanged](https://user-images.githubusercontent.com/11760980/115456454-770fa080-a223-11eb-81c1-50ea4ca9648c.PNG)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a web client bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
