### ISSUE TITLE
[Event Request] - wrong implementation of requested Publishers in Codeunit CalculateRoutingLine

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#12090]
With EventRequest https://github.com/microsoft/ALAppExtensions/issues/3640 we requested 2 Publishers in August 2019. 
Sadly, in the meantime these 2 Publishers are placed "inside" the procedure "CalcCostInclSetup" and not outside.

With your implementation we are only able to process our code if MfgSetup."Cost incl. Setup" is true!
If MfgSetup."Cost incl. Setup" is false, our process will never be triggered and we get wrong results!

So we urgently need 2 new Publishers:
1) 'After Calculation TotalCapacityPerOperation := ...' AND 'Before if MfgSetup."Cost Incl. Setup" then'
2) Before "CalcExpectedCost(..."

![image](https://user-images.githubusercontent.com/40287548/115540437-57698e00-a29e-11eb-9740-925d9055e26d.png)

The parameter should be same as requested in https://github.com/microsoft/ALAppExtensions/issues/3640

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call. 
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by AndreBreitenbach** [comment]
Both Publishers need the same signature than the 2 Publishers available inside procedure "OnBeforeCalcCostInclSetup" and "OnAfterCalcCostInclSetup"

![image](https://user-images.githubusercontent.com/40287548/115835901-22347b80-a417-11eb-9718-a2f93bb478a2.png)


1) [IntegrationEvent(false, false)]
    local procedure OnAfterCalcTotalCapacityPerOperation(ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var TotalCapacityPerOperation: Decimal)
    
2) [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcExpectedCost(ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var TotalCapacityPerOperation: Decimal)

Please let me know if you need further information.

**Comment by Oleg-Romashkov** [comment]
Thanks!

Are you ok to use existing events OnBeforeCalcCostInclSetup and OnAfterCalcCostInclSetup in case of adding event OnCalculateRoutingLineOnAfterCalcShouldCalcCostInclSetup:

        TotalCapacityPerOperation :=
          Round(
            TotalQtyPerOperation *
            ProdOrderRoutingLine.RunTimePer *
            CalendarMgt.QtyperTimeUnitofMeasure(
              ProdOrderRoutingLine."Work Center No.", ProdOrderRoutingLine."Run Time Unit of Meas. Code"),
            UOMMgt.QtyRndPrecision);

        ShouldCalcCostInclSetup := MfgSetup."Cost Incl. Setup";
        OnCalculateRoutingLineOnAfterCalcShouldCalcCostInclSetup(MfgSetup, ShouldCalcCostInclSetup);
        if ShouldCalcCostInclSetup then
            CalcCostInclSetup(ProdOrderRoutingLine, TotalCapacityPerOperation);

        CalcExpectedCost(ProdOrderRoutingLine, TotalQtyPerOperation, TotalCapacityPerOperation);

**Comment by AndreBreitenbach** [comment]
No, that is why i mentioned the old EventRequest #3640! 
We definitely need the Publishers regardless of the switch MfgSetup."Cost Incl. Setup".

**Comment by Oleg-Romashkov** [comment]
You will able to do this by updating ShouldCalcCostInclSetup. Right?

**Comment by AndreBreitenbach** [comment]
No, not really.
With the Publisher 1 we save some values in the background.
We calculate several additional stuff with the saved values from Publisher1 and possible changes after CostInclSetup.
So it is necessary to have a possibility to save values at the requested positions.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
