### ISSUE TITLE
[Event Request] OnBeforeItemAttributeValueDelete in table Item Attribute Value Mapping

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#12098]
Hello, please consider adding the following event to table 7505 "Item Attribute Value Mapping":

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeItemAttributeValueDelete(var Rec: Record "Item Attribute Value Mapping"; var IsHandled: Boolean)
    begin
    end;
```

and raise it in the OnDelete trigger, like so:

```
    trigger OnDelete()
    var
        [...]
        IsHandled: Boolean;
    begin
        [...]

        ItemAttributeValueMapping := Rec;
        if ItemAttributeValueMapping.Find then begin
            OnBeforeItemAttributeValueDelete(Rec, IsHandled);
            if not IsHandled then
                ItemAttributeValue.Delete();
        end;
    end;
```

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
