### ISSUE TITLE
[Event Request] table 5964 "Service Contract Line" - "Service Item No."

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#12091]
We added a field to this type to make it possible to have have a service contract line with something other than a service item. But  the Code is not that extendable at the moment. The biggest issue is the Validate of "Service Item No." because we need different get on different tables.

We added the following fields in a TableExtension
 
```
fields
    {
        modify("Service Item No.")
        {
            TableRelation = if ("Line Type" = const(Equipment)) Equipment where("Lease Equipment" = const(true))
            else
            if ("Line Type" = const(Object)) "Building Object";


        }

        field(11002000; "Line Type"; Option)
        {
            Caption = 'Line Type';
            Description = 'BV A806';
            OptionCaption = 'Service Item,Equipment,Object';
            OptionMembers = "Service Item",Equipment,"Object";

            trigger OnValidate()
            begin
                //ServLineMgt.LineTypeOnValidate(xRec, Rec); //BV A893
            end;
        }
    }
```
As you can imagine we need to bypass certain Standard BC code. So I would like to add certain events

```
field(5; "Service Item No."; Code[20])
{
    Caption = 'Service Item No.';
    TableRelation = "Service Item";

    trigger OnValidate()
    begin
       .... Line 56
      if (ServContractHeader.Status = ServContractHeader.Status::Signed) and
         (not "New Line")
      then
        Error(Text013, FieldCaption("Service Item No."));

     OnBeforeGetServiceItem(Rec,IsHandled); //NEW

     if ("Service Item No." <> '') and not IsHandled then begin //MODIFY


//NEW
local [IntegrationEvent] OnBeforeGetServiceItem(VAR ServiceContractLine : Record "Service Contract Line";VAR IsHandled : Boolean)
begin
end;
//NEW
```

Next there is a part where the service contract line is rebuild. In this function we want to add our own field, but there is no event.
This could be solved in to put this code in a different function and give an option to create our own transfer, or add an event to add field to the Rec. In BC18 there is an Event OnValidateServiceItemNoOnBeforeModify, but this does not the ServContractLine. So maybe we can add these to the Event. 

```
... line 124
ServContractLine := Rec;
INIT;
"Line Type" := ServContractLine."Line Type"; //This is the Line we need to add. 
```

The following issue is that the ServItem is copied to Rec. It would be nice if we are able to skip this. But I think this code does not cause an error it everything in blanc. It is just not necessary to be executed.

```
... line 138
if "Service Item No." = '' then
    exit;

IsHandled := FALSE; //NEW
OnBeforeTransferServiceItem(Rec,IsHandled); //NEW

if not IsHandled then begin //NEW
  Description := ServItem.Description;
  "Serial No." := ServItem."Serial No.";


//NEW
local [IntegrationEvent] OnBeforeTransferServiceItem(VAR ServiceContracLine : Record "Service Contract Line";VAR IsHandled : Boolean)
begin
end;

//This is the Validate we want to do in OnBeforeTransferServiceItem and set IsHandled to true
CASE Rec."Line Type" OF
  Rec."Line Type"::Equipment:
    BEGIN
     //Code
    END;
  Rec."Line Type"::Object:
    BEGIN
       //Code
    END;
END;

```

**Comment by Oleg-Romashkov** [comment]
1. The first part of request will be realized like this:

                if (ServContractHeader.Status = ServContractHeader.Status::Signed) and
                   (not "New Line")
                then
                    Error(Text013, FieldCaption("Service Item No."));

                ServiceItemNoIsNotEmpty := "Service Item No." <> '';
                OnValidateServiceItemNoOnAfterCalcServiceItemNoIsNotEmpty(Rec, ServiceItemNoIsNotEmpty);
                if ServiceItemNoIsNotEmpty then begin
                    GetServItem;
                    TestField("Customer No.");


2. As for OnValidateServiceItemNoOnBeforeModify, it defined with IncludeSender = true:

```
    [IntegrationEvent(true, false)]
    local procedure OnValidateServiceItemNoOnBeforeModify(ServItem: Record "Service Item"; ServContractHeader: Record "Service Contract Header")
    begin
    end;
```
So you can use parameter Sender as a Service Contract Line Rec. 

Is it ok for you to have only 1 new event OnValidateServiceItemNoOnAfterCalcServiceItemNoIsNotEmpty from p.1 and using Sender from p. 2 for the second part of your request?

**Comment by guidorobben** [comment]
Hi Oleg,

I tested your solution and it works. I missed the Sender parameter in the 2nd part so that works as well. I'm glad with this. Because We overrule the Get on the Service Item, so the code below is performed with a blanc service item. 
```
Line 137..
               if "Service Item No." = '' then
                    exit;
                
               Description := ServItem.Description;
                "Serial No." := ServItem."Serial No.";
                "Service Item Group Code" := ServItem."Service Item Group Code";
                "Item No." := ServItem."Item No.";
                "Variant Code" := ServItem."Variant Code";
                "Unit of Measure Code" := ServItem."Unit of Measure Code";
                if (ServContractHeader."Response Time (Hours)" < ServItem."Response Time (Hours)") and
                   (ServContractHeader."Response Time (Hours)" <> 0)
                then
                    "Response Time (Hours)" := ServContractHeader."Response Time (Hours)"
                else
                    if ServItem."Response Time (Hours)" <> 0 then
                        "Response Time (Hours)" := ServItem."Response Time (Hours)"
                    else
                        "Response Time (Hours)" := ServContractHeader."Response Time (Hours)";
                ServMgtSetup.Get();
                Validate("Line Cost", ServItem."Default Contract Cost");
                Validate("Line Value", ServItem."Default Contract Value");
                Validate("Line Discount %", ServItem."Default Contract Discount %");

```

maybe change this:

```
if "Service Item No." = '' then
   exit;

Description := ServItem.Description;
...
```

to this:

```
if "Service Item No." = '' then begin
  Description := ServItem.Description;
  Serial No." := ServItem."Serial No.";
...

```
This way no unnecessary code is executed.

**Comment by Oleg-Romashkov** [comment]
What about: 
1. Add parameter ServContractLine to event OnValidateServiceItemNoOnBeforeModify
2. or add event 

                ServContractLine := Rec;
                Init;
                OnValidateServiceItemNoOnAfterInit(Rec, ServContractLine);
                "Starting Date" := ServContractLine."Starting Date";
                "Contract Expiration Date" := ServContractLine."Contract Expiration Date";

**Comment by guidorobben** [comment]
Thanks for the quick update. I checked the the options and I my preference goes to option 2.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
