### ISSUE TITLE
[Event Request] Trigger Events on Reports

### ISSUE THREAD

**Issue by krajniks** [microsoft/ALAppExtensions#12105]
I was just testing out new reportextension funcionality and I think that Trigger Events, similar like the one that exists on Tables and Pages, would be a great addition to reportextension functionality. This predefined events would give an option to subscribe on before and after current report triggers, with specific DataItem or Column or Request Page item defined in ItemName of EventSubscription.

This would make current options for extending reports even more compelling and would reduce requests for new events on standard reports. And everyone is happy. 

Is something like that already planned or in the works maybe? Is there any hope of something like this being implemented?

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
