### ISSUE TITLE
[Event Request] codeunit 5763 Whse.-Post Shipment - Function HandleSalesLine

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12101]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5763 function HandleSalesLine.

                        if ModifyLine then begin
                            if "Source Document" = "Source Document"::"Sales Order" then
                                SalesLine.Validate("Qty. to Ship", 0)
                            else
                                SalesLine.Validate("Return Qty. to Receive", 0);
                            SalesLine.Validate("Qty. to Invoice", 0);
                        end;
                    end;
                    OnBeforeSalesLineModify(SalesLine, WhseShptLine, ModifyLine, Invoice);
                    if ModifyLine then
                        SalesLine.Modify();
                until SalesLine.Next() = 0;
            // DINNL <<
            DINOnHandleSalesLineAfterModifySalesLines(SalesHeader);
            // DINNL >>
        end;

    local procedure DINOnHandleSalesLineAfterModifySalesLines(SalesHeader: Record "Sales Header")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
