### ISSUE TITLE
[Event Request] Report 292 "Copy Sales Document" - Add Parameter in OnBeforeValidateIncludeHeader

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#12108]
Please add the FromSalesHeader as we have some additional checks:

[IntegrationEvent(false, false)]
local procedure OnBeforeValidateIncludeHeader(var DoIncludeHeader: Boolean; **FromSalesHeader: Record "Sales Header"**)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
