### ISSUE TITLE
[Event Request] codeunit 5763 Whse.-Post Shipment - Function HandlePurchaseLine

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12100]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5763 function HandlePurchaseLine.

                        if ModifyLine then begin
                            if "Source Document" = "Source Document"::"Purchase Order" then
                                PurchLine.Validate("Qty. to Receive", 0)
                            else
                                PurchLine.Validate("Return Qty. to Ship", 0);
                            PurchLine.Validate("Qty. to Invoice", 0);
                        end;
                    end;
                    OnBeforePurchLineModify(PurchLine, WhseShptLine, ModifyLine, Invoice);
                    if ModifyLine then
                        PurchLine.Modify();
                until PurchLine.Next() = 0;
            // DINNL <<
            DINOnHandlePurchaseLineAfterModifyPurchLines(PurchHeader);
            // DINNL >>

    local procedure DINOnHandlePurchaseLineAfterModifyPurchLines(PurchaseHeader: Record "Purchase Header")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
