### ISSUE TITLE
Translation Issue:Txt2Al: The Change is not a known trigger

### ISSUE THREAD

**Issue by mohit0989** [microsoft/ALAppExtensions#12103]
We are trying to upgrade BC 14 to BC 17.

We are not able to convert the CAL to AL with Translation format script. 

The captions are not generating for German(DE) language.
 
The script we are using:
txt2al --source="D:\Translations\Delta001" --target="D:\BC17\AL007" --extensionStartId=5015850 –translationFormat=Xliff

The error which we were getting:
---- ERROR ----
Error converting file: C: \ Txt2AL \ Delta84 \ TAB84.DELTA
The change is not a known trigger.
Parameter name: elementType

We are getting this error only for table extension and page extensions only. 

This issue is resolved by removing the Caption Property in the objects. But that is not the solution for us. We require the captions.

Is this a known bug or do we have a solution for this?

Thanks,
Mohit

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
•	For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
•	For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
•	For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
•	For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
