### ISSUE TITLE
[Event Request] Table 5767 - Warehouse Activity Line OnAfterCopyTrackingFromSpec

### ISSUE THREAD

**Issue by pranav4186** [Microsoft/ALAppExtensions#1210]
Hello,

Would you please add new event - OnAfterCopyTrackingFromSpec(Rec,TrackingSpecification) in the function CopyTrackingFromSpec of Table 5767.
![image](https://user-images.githubusercontent.com/35543761/52667283-9f761480-2ecd-11e9-9e89-7ec6e133aa9b.png)
![image](https://user-images.githubusercontent.com/35543761/52667350-c2a0c400-2ecd-11e9-810d-ca2e03c04650.png)

Thanks

**Comment by pranav4186** [comment]
![image](https://user-images.githubusercontent.com/35543761/52667606-802bb700-2ece-11e9-8e74-0574d53fedc5.png)

**Comment by AlexanderYakunin** [comment]
Event already implemented
