### ISSUE TITLE
[Event Request] Table 5767  Warehouse Activity Line - OnAfterSetTrackingFilter

### ISSUE THREAD

**Issue by pranav4186** [Microsoft/ALAppExtensions#1211]
Hello,

Would you please add new event - OnAfterSetTrackingFilter(Rec) in the function SetTrackingFilter of Table 5767 Warehouse Activity Line?

![image](https://user-images.githubusercontent.com/35543761/52667490-38a52b00-2ece-11e9-8a40-310f84ae64d0.png)

![image](https://user-images.githubusercontent.com/35543761/52667547-58d4ea00-2ece-11e9-9f96-7c0498b71da6.png)

Thanks

**Comment by grobyns** [comment]
looks like this was implemented together with request #1209
