### ISSUE TITLE
ES SII extensibility - Change [Scope('OnPrem')]

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/ALAppExtensions#12116]
I need use any ESP location functions OnPrem in a Saas enviroment. The functions are:

Codeunit 10746 SII Management(All global functions):
- GetSIIStyle
- GetNoTaxablePurchAmount
- GetNoTaxableSalesAmount
- SIIStateDrilldown
- IsVATEntryCashFlowBased
- IsDetailedLedgerCashFlowBased
- IsLedgerCashFlowBased
- IsIntracommunity
- FindVatEntriesFromLedger
- FindOriginalLedgerFromDetailedPaymentLedger
- FindOriginalLedgerFromPaymentLedger
- FindVatEntriesReferringToDocLedger
- FindDetailedPaymentApplicationLedgerFromLedger
- FindDetailedLedgerFromVatEntry
- FindLedgerFromVatEntry
- FindPaymentDetailedCustomerLedgerEntries
- FindPaymentDetailedVendorLedgerEntries
- NoTaxableEntriesExistPurchase
- NoTaxableEntriesExistSales
- DoesPaymentDetailedLedgerCloseInvoice
- DoesPaymentLedgerCloseInvoice
- CountryIsLocal
- CountryAndVATRegNoAreLocal
- IsDomesticCustomer
- CustomerIsIntraCommunity
- VendorIsIntraCommunity
- CombineOperationDescription
- SplitOperationDescription
- CharIsCapitalLetter
- IsAllowedSalesInvType
- IsAllowedServInvType
- Run347DeclarationToGenerateCollectionsInCash

Codeunit 6224 XML DOM Management
Any function receive dotnet, i need to convert that to native xml var

- procedure AddDeclaration(var XMLDoc: XmlDocument; Version: Text; Encoding: Text; Standalone: Text)
- 
- procedure AddGroupNode(var XMLNode: XmlNode; NodeName: Text)
- 
- procedure AddNode(var XMLNode: XmlNode; NodeName: Text; NodeText: Text)
- 
- procedure AddLastNode(var XMLNode: XmlNode; NodeName: Text; NodeText: Text)
- 
- procedure AddNamespaces(var XmlNamespaceManager: XmlNamespaceManager; XmlDocument: XmlDocument)

Codeunit 10755 SII InitialDoc Upload (All globalfunctions):

- ScheduleInitialUpload
- GetInitialStartDate
- GetInitialEndDate
- DateWithinInitialUploadPeriod

Table 9 Country/Region:

- EUCountryFound
- GetVATRegistrationNoLimitedBySetup

Thanks,

**Comment by AlexanderYakunin** [comment]
Hello! Please be more specific and explain what you need to change? Do you want us to remove all [OnPrem] scope limitations? And what is purpose of this changes for you, SII is regulatory feature and should be used properly? Do you see some functional limitations which we need to fix?

**Comment by AlvaroRosadoP** [comment]
Hi! The OnPrem scope of this functionality is not linked to the fact that the functionality should only be used OnPrem (It does not use dotnet) The purpose is that either we can use the functionality in SaaS or else the codeunit 10750 "SII XML Creator" is converted from dotnet to xml variables to allow extensibility through events created but shared by dotnet variables (Request 12111 on github)

Thanks!

**Comment by AlexanderYakunin** [comment]
Yes, SII feature was build by using the XML DotNet variable. We cannot expose DotNet for the third-party events. We have plans to move SII from the BaseApp to extension and replacing DotNet with native XML AL.

**Comment by AlvaroRosadoP** [comment]
ok, that's what I would need, and that the current events that have dotnet are native xml to be able to use them in the saas extension

Thank you!

**Comment by deadmouse** [comment]
@AlexanderYakunin @StanPesotskiy Could please review the SII module in Spanish localization? It has many procedures with scope OnPrem which are nonsense. For instance, in **codeunit 10756 "SII Management"**: FindVatEntriesFromLedger or FindNoTaxableEntriesFromLedger. There is no DotNet in there.

**Comment by AlexanderYakunin** [comment]
Hello! If you create new request and provide list of places to remove OnPrem scope, it will be done much faster.

**Comment by deadmouse** [comment]
@AlexanderYakunin Done: #20615
