### ISSUE TITLE
Open Payment Journal from bank account

### ISSUE THREAD

**Issue by Joriek** [microsoft/ALAppExtensions#12117]
Hello

We need some extra functions on page 2000001 "EB Payment Journal" in order to properly open it from other pages.
We use the following function which is called from the bank account list and card.
There is a template for each bank account, a template can have multiple batches but he last one should be used.

`
    #region PSIBOpenPaymentJournal
    procedure PSIBOpenPaymentJournal();
    var
        PayJnlLineTemplate: Record "Payment Journal Template";
        PaymentJournalLine: Record "Payment Journal Line";
        PayJnlBatch: Record "Paym. Journal Batch";
        EBPaymentJournal: Page "EB Payment Journal";
    begin
        PayJnlLineTemplate.SetRange("Bank Account", Rec."No.");
        PayJnlLineTemplate.FindFirst();
        PayJnlBatch.SetRange("Journal Template Name", PayJnlLineTemplate.Name);
        PayJnlBatch.FindLast();

        PaymentJournalLine.SetRange("Journal Template Name", PayJnlLineTemplate.Name);
        PaymentJournalLine."Journal Batch Name" := PayJnlBatch.Name;
        EBPaymentJournal.SetTableView(PaymentJournalLine);
        EBPaymentJournal.SetRecord(PaymentJournalLine);
        EBPaymentJournal.Run();
    end;
    #endregion PSIBOpenPaymentJournal
`

This type of algorithm usually works for opening other journals but for some reason it doesn't work for the EB Payment Journal.

![image](https://user-images.githubusercontent.com/6583705/115867629-a26cd800-a43b-11eb-9ff7-135b433caeff.png)

Opens:

![image](https://user-images.githubusercontent.com/6583705/115868342-9af9fe80-a43c-11eb-8faa-4f3abf3dff82.png)

The values used for the template name and bank account are the last values you entered before closing the page (I cannot find any code that explains this behaviour). All of the other global variables used to control this page are correct, except for these 2. 
On the page these are defined as the CurrentJnlBatchName and BankAccountCodeFilter variables.
It seems like these variables are impossible to control via extensions. The OnOpenPage trigger uses the CurrentJnlBatchName, when I try to debug, the value of this variable is as expected but when the page opens, a different value is shown.
We require a function to open the journal but also control these 2 variables (and the logic behind the onvalidate trigger)

Thank you in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
