### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - procedure ApplyCustLedgEntry

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#12110]
The event requested here https://github.com/microsoft/ALAppExtensions/issues/10514 is ambiguous because there are multiple places in this function where UpdateCalcInterest is called.

We would like to request two events to distinguish between two situations:

Event1:

```
            // NEW >>
            OnApplyCustLedgEntryOnBeforeUpdateCalcInterestWithOldCVLedgEntryBuf(OldCVLedgEntryBuf, Cust, SkipUpdateCalcInterest);
            if not SkipUpdateCalcInterest then
            // << NEW

            if not OldCVLedgEntryBuf.Open then begin
                UpdateCalcInterest(OldCVLedgEntryBuf);
                UpdateCalcInterest(OldCVLedgEntryBuf, NewCVLedgEntryBuf);
            end;
```

Event 2:

```
            // NEW >>
            SkipUpdateCalcInterest := false;
            OnApplyCustLedgEntryOnBeforeUpdateCalcInterestWithNewCVLedgEntryBuf(OldCVLedgEntryBuf, Cust, SkipUpdateCalcInterest);
            if not SkipUpdateCalcInterest then
            // << NEW

            if not NewCVLedgEntryBuf.Open then
                UpdateCalcInterest(NewCVLedgEntryBuf);
```

Alternatively the parameter SkipUpdateCalcInterest is only calculated once and reused the second time because the same rules will apply. Then we only need the first event.

It would also work if SkipUpdateCalcInterest is added as a parameter to event OnBeforeApplyCustLedgEntry

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
