### ISSUE TITLE
Problem with dotnet parameter in event subcription

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/ALAppExtensions#12111]
In event Codeunit 10750 SII XML Creator - OnBeforeContraparteNode  when I subscribe from a cloud extension it asks me to create a dotnet, for XmlNode, being cloud it does not allow me to create a dotnet object, I need to modify that XmlNode, how can I proceed?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
