### ISSUE TITLE
[Event Request] codeunit 6620 Copy Document Mgt. - Add parameter to function OnCopySalesInvLinesToDocOnAfterCopySalesDocLine

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12127]
Dear ALAppExtensions Team,

Is it possible to add a parameter to function OnCopySalesInvLinesToDocOnAfterCopySalesDocLine in codeunit 6620 ?

-OnCopySalesInvLinesToDocOnAfterCopySalesDocLine(ToSalesLine);
+OnCopySalesInvLinesToDocOnAfterCopySalesDocLine(ToSalesLine,FromSalesInvLine);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
