### ISSUE TITLE
[Event Request] codeunit 6620 Copy Document Mgt. - Function CopySalesShptLinesToDoc

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12124]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 6620 function CopySalesShptLinesToDoc.

                            if CopySalesDocLine(
                                 ToSalesHeader, ToSalesLine, FromSalesHeader, FromSalesLineBuf, NextLineNo, LinesNotCopied, false,
                                 "Sales Document Type From".FromInteger(DeferralTypeForSalesDoc("Sales Document Type From"::"Posted Shipment".AsInteger())),
                                 CopyPostedDeferral, FromSalesLineBuf."Line No.")
                            then begin
                                if CopyItemTrkg then begin
                                    if SplitLine then
                                        ItemTrackingDocMgt.CollectItemTrkgPerPostedDocLine(
                                          TempItemTrkgEntry, TempTrkgItemLedgEntry, false, FromSalesLineBuf."Document No.", FromSalesLineBuf."Line No.")
                                    else
                                        ItemTrackingDocMgt.CopyItemLedgerEntriesToTemp(TempTrkgItemLedgEntry, ItemLedgEntry);

                                    ItemTrackingMgt.CopyItemLedgEntryTrkgToSalesLn(
                                      TempTrkgItemLedgEntry, ToSalesLine,
                                      FillExactCostRevLink and ExactCostRevMandatory, MissingExCostRevLink,
                                      FromSalesHeader."Prices Including VAT", ToSalesHeader."Prices Including VAT", true);
                                end;
                                OnAfterCopySalesLineFromSalesShptLineBuffer(
                                  ToSalesLine, FromSalesShptLine, IncludeHeader, RecalculateLines, TempDocSalesLine, ToSalesHeader, FromSalesLineBuf);
                            end;
                        until FromSalesLineBuf.Next() = 0;
                    end;
                    // DINNL <<
                    DINOnAfterCopySalesShptLinesToDoc(FromSalesShptLine, ToSalesLine);
                   // DINNL >>
                until Next() = 0;

    local procedure DINOnAfterCopySalesShptLinesToDoc(FromSalesShptLine: Record "Sales Shipment Line"; ToSalesLine: Record "Sales Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
