### ISSUE TITLE
[Event Request] codeunit 6620 Copy Document Mgt. - Function IsSplitItemLedgEntry

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12126]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 6620 function IsSplitItemLedgEntry.

    local procedure IsSplitItemLedgEntry(OrgItemLedgEntry: Record "Item Ledger Entry"): Boolean
    var
        ItemLedgEntry: Record "Item Ledger Entry";
    begin
        ItemLedgEntry.SetCurrentKey("Document No.");
        ItemLedgEntry.SetRange("Document No.", OrgItemLedgEntry."Document No.");
        ItemLedgEntry.SetRange("Document Type", OrgItemLedgEntry."Document Type");
        ItemLedgEntry.SetRange("Document Line No.", OrgItemLedgEntry."Document Line No.");
        ItemLedgEntry.SetTrackingFilterFromItemLedgEntry(OrgItemLedgEntry);
        ItemLedgEntry.SetFilter("Entry No.", '<%1', OrgItemLedgEntry."Entry No.");
        // DINNL <<
        DINOnAfterIsSplitItemLedgEntry(OrgItemLedgEntry, ItemLedgEntry);
        // DINNL >>
        exit(not ItemLedgEntry.IsEmpty());
    end;

    local procedure DINOnAfterIsSplitItemLedgEntry(OrgItemLedgEntry: Record "Item Ledger Entry"; var ItemLedgerEntry: Record "Item Ledger Entry")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
