### ISSUE TITLE
Font Barcode in BC Cloud

### ISSUE THREAD

**Issue by LucaDonatoSEDP** [microsoft/ALAppExtensions#12123]
In BC cloud 18 I try to print in report rdlc a font IDAutomation Code128 but doesn't work.
On my Pc have installed the demo version downloaded from IDAutomation site, and in rdlc I select IDAutormationSC128M Demo fort.
![image](https://user-images.githubusercontent.com/59683494/115883780-79097780-a44e-11eb-8f93-87e27be97dbc.png)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
