### ISSUE TITLE
[Event Request] codeunit 6503 Item Tracking Doc. Management - Function ItemTrackingExistsInBuffer

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12131]
Dear ALAppExtensions Team,

We would like to request the following event publishers in codeunit 6503 function ItemTrackingExistsInBuffer

    local procedure ItemTrackingExistsInBuffer(var TempTrackingSpecBuffer: Record "Tracking Specification" temporary; Type: Integer; Subtype: Integer; ID: Code[20]; BatchName: Code[10]; ProdOrderLine: Integer; RefNo: Integer; ItemTrackingSetup: Record "Item Tracking Setup"): Boolean
    begin
        // searches after existing record in TempTrackingSpecBuffer
        TempTrackingSpecBuffer.SetSourceFilter(Type, Subtype, ID, RefNo, true);
        TempTrackingSpecBuffer.SetSourceFilter(BatchName, ProdOrderLine);
        TempTrackingSpecBuffer.SetTrackingFilterFromItemTrackingSetup(ItemTrackingSetup);
        // DINNL <<
        DINOnItemTrackingExistsInBuffer(TempTrackingSpecBuffer);
        // DINNL >>
        if not TempTrackingSpecBuffer.IsEmpty() then begin
            TempTrackingSpecBuffer.FindFirst();
            exit(true);
        end;
        exit(false);
    end;

    local procedure DINOnItemTrackingExistsInBuffer(var TempTrackingSpecBuffer: Record "Tracking Specification" temporary)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
