### ISSUE TITLE
Codeunit 5763 - Whse.-Post Shipment: SuppressCommit variable not passed by var

### ISSUE THREAD

**Issue by demiliani** [microsoft/ALAppExtensions#12132]
In Codeunit 5763 (Whse.-Post Shipment) there is a global variable called SuppressCommit that avoids Commits during warehouse posting.

To change this variable, there is the following event, but SuppressCommit variable is not passed with “var" and we cannot change its value after subscribing the event:

[IntegrationEvent(false, false)]
local procedure OnAfterCheckWhseShptLines(var WhseShptHeader: Record "Warehouse Shipment Header"; var WhseShptLine: Record "Warehouse Shipment Line"; Invoice: Boolean; SuppressCommit: Boolean)
begin
end;

![MSErr_01](https://user-images.githubusercontent.com/33155438/116041850-070f7900-a66e-11eb-8a7a-f1629745df99.jpg)

We would like to have this event signature, with SuppressCommit passed by reference:

[IntegrationEvent(false, false)]
local procedure OnAfterCheckWhseShptLines(var WhseShptHeader: Record "Warehouse Shipment Header"; var WhseShptLine: Record "Warehouse Shipment Line"; Invoice: Boolean; var SuppressCommit: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
