### ISSUE TITLE
[Event Request] table 39 "Purchase Line" - SelectMultipleItems

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#12133]
Can I get the same changes in the purchase module as in issue #12092?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
