### ISSUE TITLE
Event Request - Report 12152 "Create Subcontr.Transf. Order"

### ISSUE THREAD

**Issue by MattiaPassarella** [microsoft/ALAppExtensions#12136]
Sometimes there's no need to open Transfer Order page when created from Subcontracting Purchase Order.
Is it possible to add the following Event into Report 12152 "Create Subcontr.Transf. Order"?

Thank you

    procedure ShowDocument()
    var
        TransfOrderForm: Page "Subcontr. Transfer Order";
        //>>>>>new var
        IsHandled: Boolean;
        //<<<<<
    begin
        //>>>>>new event
        OnBeforeShowDocument(TransferHeader, IsHandled);
        if IsHandled then
            exit;
        //<<<<<

        Commit();
        TransferHeader.Reset();
        TransferHeader.SetRecFilter;
        TransfOrderForm.SetTableView(TransferHeader);
        TransfOrderForm.Editable(false);
        TransfOrderForm.RunModal;
    end;

    //>>>>>new event
    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowDocument(var TransferHeader: Record "Transfer Header"; var IsHandled: Boolean)
    begin
    end;
    //<<<<<

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
