### ISSUE TITLE
[Event Request] codeunit 6503 Item Tracking Doc. Management - Function AddTempRecordToSet

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12130]
Dear ALAppExtensions Team,

We would like to request the following event publishers in codeunit 6503 function AddTempRecordToSet.

    local procedure AddTempRecordToSet(var TempItemLedgEntry: Record "Item Ledger Entry" temporary; SignFactor: Integer)
    var
        TempItemLedgEntry2: Record "Item Ledger Entry" temporary;
    begin
        if SignFactor <> 1 then begin
            TempItemLedgEntry.Quantity *= SignFactor;
            TempItemLedgEntry."Remaining Quantity" *= SignFactor;
            TempItemLedgEntry."Invoiced Quantity" *= SignFactor;
        end;
        ItemTrackingMgt.RetrieveAppliedExpirationDate(TempItemLedgEntry);
        TempItemLedgEntry2 := TempItemLedgEntry;
        TempItemLedgEntry.Reset();
        TempItemLedgEntry.SetTrackingFilterFromItemLedgEntry(TempItemLedgEntry2);
        TempItemLedgEntry.SetRange("Warranty Date", TempItemLedgEntry2."Warranty Date");
        TempItemLedgEntry.SetRange("Expiration Date", TempItemLedgEntry2."Expiration Date");
        // DINNL <<
        DINAddTempRecordToSetOnBeforeFindFirst(TempItemLedgEntry, TempItemLedgEntry2);
        // DINNL >>
        if TempItemLedgEntry.FindFirst() then begin
            TempItemLedgEntry.Quantity += TempItemLedgEntry2.Quantity;
            TempItemLedgEntry."Remaining Quantity" += TempItemLedgEntry2."Remaining Quantity";
            TempItemLedgEntry."Invoiced Quantity" += TempItemLedgEntry2."Invoiced Quantity";
            // DINNL <<
            DINAddTempRecordToSetOnBeforeModify(TempItemLedgEntry, TempItemLedgEntry2);
            // DINNL >>
            TempItemLedgEntry.Modify();
        end else
            TempItemLedgEntry.Insert();

        OnAfterAddTempRecordToSet(TempItemLedgEntry, TempItemLedgEntry2, SignFactor);
        TempItemLedgEntry.Reset();
    end;

    [IntegrationEvent(false, false)]
    local procedure DINAddTempRecordToSetOnBeforeFindFirst(var TempItemLedgEntry: Record "Item Ledger Entry" temporary; TempItemLedgEntry2: Record "Item Ledger Entry" temporary)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure DINAddTempRecordToSetOnBeforeModify(var TempItemLedgerEntry: Record "Item Ledger Entry" temporary; TempItemLedgerEntry2: Record "Item Ledger Entry" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
