### ISSUE TITLE
[Request for External] codeunit 1605 "PEPPOL Management" - GetTaxCategories and GetTaxExemptionReason

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#12143]
Can you change procedure GetTaxCategories and GetTaxExemptionReason to external in codeunit 1605 "PEPPOL Management"?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
