### ISSUE TITLE
[Extensibility Enhancement] table 1237 "Transformation Rule" - "Next Transformation Rule"

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#12145]
Can you change InsertFindAndReplaceRule to global in table 1237 "Transformation Rule"?
That way I don't need to check if it exists myself.
And add a procedure equal to InsertFindAndReplaceRule that also takes "Next Transformation Rule" as parameter?

**Comment by AlexanderYakunin** [comment]
Is it possible to provide code sample for this ask? 
And add a procedure equal to InsertFindAndReplaceRule that also takes "Next Transformation Rule" as parameter?

**Comment by auzhhv** [comment]
> Is it possible to provide code sample for this ask?
> And add a procedure equal to InsertFindAndReplaceRule that also takes "Next Transformation Rule" as parameter?

These are just copies of InsertFindAndReplaceRule and ReplaceRule with an extra parameter. The procedures should probably be combined to avoid duplicte code :)

```
    local procedure InsertFindAndReplaceRule(NewCode: Code[20]; NewDescription: Text[100]; NewTransformationType: Option; NewFindValue: Text[250]; NewReplaceValue: Text[250]; NextTransformationRule:Code[20])
    var
        TransformationRule: Record "Transformation Rule";
    begin
        if TransformationRule.Get(NewCode) then
            exit;

        TransformationRule.ReplaceRule(NewCode, NewDescription, NewTransformationType, NewFindValue, NewReplaceValue, NextTransformationRule);
    end;

    procedure ReplaceRule(NewCode: Code[20]; NewDescription: Text[100]; NewTransformationType: Option; NewFindValue: Text[250]; NewReplaceValue: Text[250]; NextTransformationRule:Code[20])
    begin
        Init();
        Validate(Code, NewCode);
        Validate(Description, NewDescription);
        Validate("Transformation Type", NewTransformationType);
        Validate("Find Value", NewFindValue);
        Validate("Replace Value", NewReplaceValue);
        Validate("Next Transformation Rule", NextTransformationRule);
        Insert(true);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
