### ISSUE TITLE
[EventRequest] Report Post Prepaid Contract Entries - New events in function PostGenJnlLine

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#12140]
Hi,
we need a new events in this report in function PostGenJnlLine:

![image](https://user-images.githubusercontent.com/47414309/116089007-b49c7f80-a6a2-11eb-85d4-824168474f9b.png)

The new publisher should look like this (all parameter as var):

![image](https://user-images.githubusercontent.com/47414309/116089412-21177e80-a6a3-11eb-9dcc-a90b6467697a.png)

Thanks!

**Comment by Oleg-Romashkov** [comment]
Use existing events OnBeforePostNonPrepaidAccount and OnBeforePostPrepaidAccount

**Comment by AJasp** [comment]
We originally requested the events in this request: [https://github.com/microsoft/ALAppExtensions/issues/5629](url)
It was not implemented as requested an at this place we have to clone the code until line "GenJnlPostLine.Run" and we want to avoide to clone standard code
