### ISSUE TITLE
Page 9658 "Vendor Report Selections" - Make Usage2 extensible

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12141]
Hi al-team,

I would like to add another value to Usage2. 
Can you convert the option value to an enum? Also, I would need an event at the points where Usage2 is compared to Usage via a Case statement.

Or is there another plan to make the page extensible?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
