### ISSUE TITLE
[Access Request] Table 5050 - Contact - UpdateSearchName

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12157]
Hi Al team,

I would like to access the following function from the extension object

   ```
 // local procedure UpdateSearchName()
    protected procedure UpdateSearchName()
    var
        IsHandled: Boolean;
    begin
        OnBeforeUpdateSearchName(Rec, xRec, IsHandled);
        if IsHandled then
            exit;
        if ("Search Name" = UpperCase(xRec.Name)) or ("Search Name" = '') then
            "Search Name" := Name;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
