### ISSUE TITLE
[Enum Request] In the table "Tax Jurisdiction" field "Country/Region" should be Enum

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#12159]
Hello,
Our customer needs to extend the field "Country/Region" in "Tax Jurisdiction", this is critical.
But this field still Option, could you please make transform the field to Enum?
![image](https://user-images.githubusercontent.com/66109755/116255047-89855f00-a77a-11eb-8629-a0afcf7f9776.png)

**Comment by AlexanderYakunin** [comment]
Duplicate to previous requests, we cannot do it.
