### ISSUE TITLE
[Event Request] Table 77 - Report Selections - OnSaveAsDocumentAttachmentOnBeforeSaveAttachment, OnSaveAsDocumentAttachmentOnBeforeShowNotification

### ISSUE THREAD

**Issue by VitalyLebedev** [microsoft/ALAppExtensions#12153]
Dear ALAppExtensions team,
We would like to request event publishers `OnSaveAsDocumentAttachmentOnBeforeSaveAttachment` and `OnSaveAsDocumentAttachmentOnBeforeShowNotification` to be added to **Table 77 - Report Selections** with the following signatures:
```al
local procedure OnSaveAsDocumentAttachmentOnBeforeAttachDocument(RecRef: RecordRef; var ReportSelections: Record "Report Selections"; DocumentNo: Code[20]; AccountNo: Code[20]; var TempBlob: Codeunit "Temp Blob"; var IsHandled: Boolean)

local procedure OnSaveAsDocumentAttachmentOnBeforeShowNotification(RecordVariant: Variant; NumberOfReportsAttached: Integer; ShowAction: Boolean; var IsHandled: Boolean)
```
These events would be called as follows from SaveAsDocumentAttachment procedure:
![image](https://user-images.githubusercontent.com/46499611/116228367-deff4300-a75d-11eb-9465-fc21ed51cee2.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
