### ISSUE TITLE
[Event Request] Table 904 "Assemble-to-Order Link"

### ISSUE THREAD

**Issue by THillemeier** [microsoft/ALAppExtensions#12169]
Plase add the following Event in table 904 "Assemble-to-Order Link", function GetATOLink:

![image](https://user-images.githubusercontent.com/82493733/116357897-5637e400-a7fd-11eb-92c4-6d0a2390c71c.png)

![image](https://user-images.githubusercontent.com/82493733/116358110-913a1780-a7fd-11eb-9317-25b6117d346e.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
