### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" field "Unit Cost"

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#12162]
Hello MS,
Please help us in migrating our verticalized solution by adding the below events to the field "Unit Cost" in "Requisition Line" table.
Version (BC18 Cu00). Requested event OnBeforeValidateUnitCost

        field(99000901; "Unit Cost"; Decimal)
        {
            AutoFormatType = 2;
            Caption = 'Unit Cost';
            MinValue = 0;

            trigger OnValidate()
            var 
				IsHandled : Boolean;
            begin
                IsHandled := false;
				OnBeforeValidateUnitCost(Rec, IsHandled)
				if IsHandled then
					exit;

                TestField(Type, Type::Item);
                TestField("No.");

                Item.Get("No.");
                if Item."Costing Method" = Item."Costing Method"::Standard then begin
                    if CurrFieldNo = FieldNo("Unit Cost") then
                        Error(
                          Text006,
                          FieldCaption("Unit Cost"), Item.FieldCaption("Costing Method"), Item."Costing Method");
                    "Unit Cost" := Item."Unit Cost" * "Qty. per Unit of Measure";
                end;
                "Cost Amount" := Round("Unit Cost" * Quantity);
            end;
        }

        [IntegrationEvent(false, false)]
        local procedure OnBeforeValidateUnitCost(var RequisitionLine: Record "Requisition Line"; var IsHandled: Boolean)
        begin
        end

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
