### ISSUE TITLE
[Enum Request] In the table 10012  "Sales Tax Amount Difference" field "Document Product Area" should be Enum

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#12160]
Hello MS team. 
Could you please make change from option to enum.
Thanks.

![image](https://user-images.githubusercontent.com/66109755/116256107-8d65b100-a77b-11eb-93e3-1f1ee0bae9ab.png)

**Comment by AlexanderYakunin** [comment]
Seems duplicate request, already done
