### ISSUE TITLE
Procedure LookupCustomer on Customer Table

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#12168]
In the table Customer the procecure LookupCustomeris set to scope OnPrem

can you also allow this function on target cloud? We did copy this fucttion because of this but I see no reason why this should ony work onPrem...

Old Code:

```
 [Scope('OnPrem')]
 procedure LookupCustomer(var Customer: Record Customer): Boolean
 var
     CustomerLookup: Page "Customer Lookup";
     Result: Boolean;
 begin
     CustomerLookup.SetTableView(Customer);
    ..
```

NewCode:

```
procedure LookupCustomer(var Customer: Record Customer): Boolean
var
    CustomerLookup: Page "Customer Lookup";
    Result: Boolean;
begin
    CustomerLookup.SetTableView(Customer);
    ...
```

**Comment by AlexanderYakunin** [comment]
There is wrapper for this procedure available for the cloud scope:

    procedure SelectCustomer(var Customer: Record Customer): Boolean
    begin
        exit(LookupCustomer(Customer));
    end;
