### ISSUE TITLE
[Enum Request] In the table 10012 "Sales Tax Amount Difference" field "Document Type" should be Enum

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#12161]
Hello MS team.
Could you please make a change from option to enum?
Thanks.

![image](https://user-images.githubusercontent.com/66109755/116256602-0238eb00-a77c-11eb-82da-5f180da246a9.png)

**Comment by AlexanderYakunin** [comment]
This field get values from different document headers: Sales: Purchase and Services. They contains different values, so you should use Integer value instead of enum here.
