### ISSUE TITLE
[Event Request] Codeunit 398 "Sales Tax Calculate" function EndSalesTaxCalculation

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#12163]
Hello MS,
Please help us in migrating our verticalized solution by adding the below events to the function EndSalesTaxCalculation in "Sales Tax Calculate" Codeunit. Requested event OnBeforeModifyTempSalesTaxLine
    
    procedure EndSalesTaxCalculation(Date: Date)
    var
        SalesTaxAmountLine2: Record "Sales Tax Amount Line" temporary;
        TaxDetail: Record "Tax Detail";
        AddedTaxAmount: Decimal;
        TotalTaxAmount: Decimal;
        MaxAmount: Decimal;
        TaxBaseAmt: Decimal;
        LastTaxAreaCode: Code[20];
        LastTaxType: Integer;
        LastTaxGroupCode: Code[20];
        RoundTax: Option "To Nearest",Up,Down;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        case true of
            SalesHeaderRead:
                OnBeforeEndSalesTaxCalculationSales(SalesHeader, TempSalesTaxLine, IsHandled);
            PurchHeaderRead:
                OnBeforeEndSalesTaxCalculationPurchase(PurchHeader, TempSalesTaxLine, IsHandled);
            ServHeaderRead:
                OnBeforeEndSalesTaxCalculationService(ServiceHeader, TempSalesTaxLine, IsHandled);
        end;
        if IsHandled then
            exit;

        with TempSalesTaxLine do begin
            Reset;
            SetRange("Tax Type", "Tax Type"::"Sales and Use Tax");
            if FindSet then
                repeat
                    SetTaxDetailFilter(TaxDetail, "Tax Jurisdiction Code", "Tax Group Code", Date);
                    TaxDetail.SetRange("Tax Type", TaxDetail."Tax Type"::"Sales and Use Tax");
                    if "Use Tax" then
                        TaxDetail.SetFilter("Tax Type", '%1|%2', TaxDetail."Tax Type"::"Sales and Use Tax",
                          TaxDetail."Tax Type"::"Use Tax Only")
                    else
                        TaxDetail.SetFilter("Tax Type", '%1|%2', TaxDetail."Tax Type"::"Sales and Use Tax",
                          TaxDetail."Tax Type"::"Sales Tax Only");
                    if not TaxDetail.FindLast then
                        Delete;
                    TaxDetail.SetRange("Tax Type", TaxDetail."Tax Type"::"Excise Tax");
                    if TaxDetail.FindLast then begin
                        "Tax Type" := "Tax Type"::"Excise Tax";
                        Insert;
                        "Tax Type" := "Tax Type"::"Sales and Use Tax";
                    end;
                until Next() = 0;
            Reset;
            if FindSet(true) then
                repeat
                    TempTaxAmountDifference.Reset();
                    TempTaxAmountDifference.SetRange("Tax Area Code", "Tax Area Code for Key");
                    TempTaxAmountDifference.SetRange("Tax Jurisdiction Code", "Tax Jurisdiction Code");
                    TempTaxAmountDifference.SetRange("Tax Group Code", "Tax Group Code");
                    TempTaxAmountDifference.SetRange("Expense/Capitalize", "Expense/Capitalize");
                    TempTaxAmountDifference.SetRange("Tax Type", "Tax Type");
                    TempTaxAmountDifference.SetRange("Use Tax", "Use Tax");
                    TempTaxAmountDifference.SetRange(Positive, Positive);
                    if TempTaxAmountDifference.FindFirst then begin
                        "Tax Difference" := TempTaxAmountDifference."Tax Difference";
                        OnBeforeModifyTempSalesTaxLine(TempSalesTaxLine);	
                        Modify;
                    end;
                until Next() = 0;
            Reset;
            SetCurrentKey("Tax Area Code for Key", "Tax Group Code", "Tax Type", "Calculation Order");
            ----------next code of std function----------

    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyTempSalesTaxLine(var TempSalesTaxLine: Record "Sales Tax Amount Line" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
