### ISSUE TITLE
[Event Request] Codeunit 398 "Sales Tax Calculate" function EndSalesTaxCalculation

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#12164]
Hello MS,
Please help us in migrating our verticalized solution by adding the below events to the function EndSalesTaxCalculation in "Sales Tax Calculate" Codeunit. Requested event OnAfterCalculateMaxAmount

    procedure EndSalesTaxCalculation(Date: Date)
    var
        SalesTaxAmountLine2: Record "Sales Tax Amount Line" temporary;
        TaxDetail: Record "Tax Detail";
        AddedTaxAmount: Decimal;
        TotalTaxAmount: Decimal;
        MaxAmount: Decimal;
        TaxBaseAmt: Decimal;
        LastTaxAreaCode: Code[20];
        LastTaxType: Integer;
        LastTaxGroupCode: Code[20];
        RoundTax: Option "To Nearest",Up,Down;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        case true of
            SalesHeaderRead:
                OnBeforeEndSalesTaxCalculationSales(SalesHeader, TempSalesTaxLine, IsHandled);
            PurchHeaderRead:
                OnBeforeEndSalesTaxCalculationPurchase(PurchHeader, TempSalesTaxLine, IsHandled);
            ServHeaderRead:
                OnBeforeEndSalesTaxCalculationService(ServiceHeader, TempSalesTaxLine, IsHandled);
        end;
        if IsHandled then
            exit;

        with TempSalesTaxLine do begin
            Reset;
            SetRange("Tax Type", "Tax Type"::"Sales and Use Tax");
            if FindSet then
                repeat
                    SetTaxDetailFilter(TaxDetail, "Tax Jurisdiction Code", "Tax Group Code", Date);
                    TaxDetail.SetRange("Tax Type", TaxDetail."Tax Type"::"Sales and Use Tax");
                    if "Use Tax" then
                        TaxDetail.SetFilter("Tax Type", '%1|%2', TaxDetail."Tax Type"::"Sales and Use Tax",
                          TaxDetail."Tax Type"::"Use Tax Only")
                    else
                        TaxDetail.SetFilter("Tax Type", '%1|%2', TaxDetail."Tax Type"::"Sales and Use Tax",
                          TaxDetail."Tax Type"::"Sales Tax Only");
                    if not TaxDetail.FindLast then
                        Delete;
                    TaxDetail.SetRange("Tax Type", TaxDetail."Tax Type"::"Excise Tax");
                    if TaxDetail.FindLast then begin
                        "Tax Type" := "Tax Type"::"Excise Tax";
                        Insert;
                        "Tax Type" := "Tax Type"::"Sales and Use Tax";
                    end;
                until Next() = 0;
            Reset;
            if FindSet(true) then
                repeat
                    TempTaxAmountDifference.Reset();
                    TempTaxAmountDifference.SetRange("Tax Area Code", "Tax Area Code for Key");
                    TempTaxAmountDifference.SetRange("Tax Jurisdiction Code", "Tax Jurisdiction Code");
                    TempTaxAmountDifference.SetRange("Tax Group Code", "Tax Group Code");
                    TempTaxAmountDifference.SetRange("Expense/Capitalize", "Expense/Capitalize");
                    TempTaxAmountDifference.SetRange("Tax Type", "Tax Type");
                    TempTaxAmountDifference.SetRange("Use Tax", "Use Tax");
                    TempTaxAmountDifference.SetRange(Positive, Positive);
                    if TempTaxAmountDifference.FindFirst then begin
                        "Tax Difference" := TempTaxAmountDifference."Tax Difference";
                        OnBeforeModifyTempSalesTaxLine(TempSalesTaxLine);	
                        Modify;
                    end;
                until Next() = 0;
            Reset;
            SetCurrentKey("Tax Area Code for Key", "Tax Group Code", "Tax Type", "Calculation Order");
            if FindLast then begin
                LastTaxAreaCode := "Tax Area Code for Key";
                LastCalculationOrder := -9999;
                LastTaxType := "Tax Type";
                LastTaxGroupCode := "Tax Group Code";
                RoundTax := "Round Tax";
                repeat
                    if (LastTaxAreaCode <> "Tax Area Code for Key") or
                       (LastTaxGroupCode <> "Tax Group Code")
                    then begin
                        HandleRoundTaxUpOrDown(SalesTaxAmountLine2, RoundTax, TotalTaxAmount, LastTaxAreaCode, LastTaxGroupCode);
                        LastTaxAreaCode := "Tax Area Code for Key";
                        LastTaxType := "Tax Type";
                        LastTaxGroupCode := "Tax Group Code";
                        TaxOnTaxCalculated := false;
                        LastCalculationOrder := -9999;
                        CalculationOrderViolation := false;
                        TotalTaxAmount := 0;
                        RoundTax := "Round Tax";
                    end;
                    if "Tax Type" = "Tax Type"::"Sales and Use Tax" then
                        TaxBaseAmt := "Tax Base Amount"
                    else
                        TaxBaseAmt := Quantity;
                    if LastCalculationOrder = "Calculation Order" then
                        CalculationOrderViolation := true;
                    LastCalculationOrder := "Calculation Order";

                    SetTaxDetailFilter(TaxDetail, "Tax Jurisdiction Code", "Tax Group Code", Date);
                    TaxDetail.SetRange("Tax Type", "Tax Type");
                    if "Tax Type" = "Tax Type"::"Sales and Use Tax" then
                        if "Use Tax" then
                            TaxDetail.SetFilter("Tax Type", '%1|%2', "Tax Type"::"Sales and Use Tax",
                              "Tax Type"::"Use Tax Only")
                        else
                            TaxDetail.SetFilter("Tax Type", '%1|%2', "Tax Type"::"Sales and Use Tax",
                              "Tax Type"::"Sales Tax Only");
                    if TaxDetail.FindLast then begin
                        TaxOnTaxCalculated := TaxOnTaxCalculated or TaxDetail."Calculate Tax on Tax";
                        if TaxDetail."Calculate Tax on Tax" and ("Tax Type" = "Tax Type"::"Sales and Use Tax") then
                            TaxBaseAmt := "Tax Base Amount" + TotalTaxAmount;
                        if "Tax Liable" then begin
                            if (Abs(TaxBaseAmt) <= TaxDetail."Maximum Amount/Qty.") or
                               (TaxDetail."Maximum Amount/Qty." = 0)
                            then
                                AddedTaxAmount := TaxBaseAmt * TaxDetail."Tax Below Maximum"
                            else begin
                                if "Tax Type" = "Tax Type"::"Sales and Use Tax" then
                                    MaxAmount := TaxBaseAmt / Abs("Tax Base Amount") * TaxDetail."Maximum Amount/Qty."
                                else
                                    MaxAmount := Quantity / Abs(Quantity) * TaxDetail."Maximum Amount/Qty.";
                                AddedTaxAmount :=
                                  (MaxAmount * TaxDetail."Tax Below Maximum") +
                                  ((TaxBaseAmt - MaxAmount) * TaxDetail."Tax Above Maximum");
                                OnAfterCalculateMaxAmount(TempSalesTaxLine, TaxDetail, MaxAmount, AddedTaxAmount, TaxBaseAmt);  
                            end;
                            if "Tax Type" = "Tax Type"::"Sales and Use Tax" then
                                AddedTaxAmount := AddedTaxAmount / 100.0;
                        end else
                            AddedTaxAmount := 0;
                        "Tax Amount" := "Tax Amount" + AddedTaxAmount;
                        TotalTaxAmount := TotalTaxAmount + AddedTaxAmount;
                    end;

 	[IntegrationEvent(false, false)]
    local procedure OnAfterCalculateMaxAmount(var TempSalesTaxLine: Record "Sales Tax Amount Line" temporary; TaxDetail: Record "Tax Detail"; var MaxAmount : Decimal; var AddedTaxAmount : Decimal; TaxBaseAmt : Decimal);
	begin
	end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
