### ISSUE TITLE
[Event Request] Page 10842 Apply GL Entries - OnBeforePostApplication

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#12166]
Hi, would it be possible to get an event OnBeforePostApplication in page 10842, in the trigger OnAction of the Action PostApplication, like this : 

```
                    trigger OnAction()
                    begin
                        OnBeforePostApplication(Rec, IsHandled);
                        if not IsHandled then 
                            exit;

                        GLEntriesApplication.Validate(Rec);
                    end;

```

```
   [IntegrationEvent(false, false)]
    local procedure OnBeforePostApplication(var Rec: Record "G/L Entry"; var IsHandled: Boolean);
    begin
    end;

```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
