### ISSUE TITLE
[Event Request] Table 81 "Gen. Journal Line", procedure SetApplyToAmount()

### ISSUE THREAD

**Issue by supercruel** [microsoft/ALAppExtensions#12165]
Would it be possible to give us a "OnBeforeSetApplyToAmount" event or/and a OnAfterSetApplyToAmount in table 81 "Gen. Journal Line" in procedure SetApplyToAmount():

    procedure SetApplyToAmount()
    begin
        //+New
        OnBeforeSetApplyToAmount(Rec);
        //-New

        case "Account Type" of
            "Account Type"::Customer:

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
