### ISSUE TITLE
[Request for External] Codeunit 7321 "Create Inventory Put-Away" - InsertWhseActivLine

### ISSUE THREAD

**Issue by THillemeier** [microsoft/ALAppExtensions#12170]
Please modify function InsertWhseActivLine in Codeunit 7321 "Create Inventory Put-Away" from local to external.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
