### ISSUE TITLE
Extended Price Calculation

### ISSUE THREAD

**Issue by domingosbarreto** [microsoft/ALAppExtensions#12185]
Hi,

When upgrading a customer from NAV2016 to BC17.1 we've migrated the old price structure to the new Price Lists (v16).

When implementing NAV2016 there was a customer specific request to develop a functionality to avoid creating prices/cost for every combination of Resource/Group and Work Type Code, since there is a global cost/price for every Work Types and a specific cost/price for a specific Work Type. 

That customization was made in codeunit 220 Resource-Find Cost, adding the following code:
![image](https://user-images.githubusercontent.com/83361918/116442713-bf921400-a84a-11eb-9669-89ec5678a1c8.png)

That way the user does not have to set up the price for every combination of Resource/Group and Work Type Code. He just needs to specify the global price (Work Type Code = '') and the exceptions for a specific Work Type.

Is there a way to apply this to the new functionality of price calculation v16? Or is the user always obliged to set up the prices for all possible combinations?

**Comment by StanPesotskiy** [comment]
Will be added two new events:
- `OnAfterPutRelatedAssetsToList(PriceAsset, var PriceAssetList);` to codeunit 7043 "Price Asset - Resource"
- `OnAfterPutRelatedAssetsToList(PriceAsset, var PriceAssetList);` to codeunit 7044 "Price Asset - Resource Group"

These events return **PriceAssetList** that should be modified to add more assets at different levels with different parameters.

In your case you would need to add another price asset for the resource group and the blank work type code to the list below the asset for the resource group and the filled work type code that is added by "Price Asset - Resource" codeunit.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
