### ISSUE TITLE
[Event Request] UpdateUserChecklistStatus from codeunit 1996 "Checklist Banner"

### ISSUE THREAD

**Issue by TimothyWatkins** [microsoft/ALAppExtensions#12188]
The ability to disable/enable the new CheckList Banner on logging in or opening the role center... maybe this function needs to be added to the "System Action Triggers" codeunit instead.

[IntegrationEvent(false, false)]
procedure UpdateUserChecklistStatus(UserName: Text; NewStatus: Enum "Checklist Status")
begin
end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
