### ISSUE TITLE
Codeunit 11601 - BAS Management - Change Function Visibility

### ISSUE THREAD

**Issue by SCreanor** [Microsoft/ALAppExtensions#1218]
Could the following 2 functions in this codeunit be changed to have their Function Visibility changed from 'Internal' to 'External' please so they can be used for extension development.

```
VendorRegistered
GetUnregGSTProdPostGroup
```

**Comment by darjoo** [comment]
Hi @SCreanor,
The functions you have requested have been exposed and will be available in a future release.
