### ISSUE TITLE
new event request + event bugfix for codeunit 6501 Item Tracking Data Collection

### ISSUE THREAD

**Issue by SteveKrisjanovsD365** [microsoft/ALAppExtensions#12186]
First issue:

there is an event currently raised in procedure AssistEditTrackingNo as follows:

```
OnAssistEditTrackingNoOnBeforeRetrieveLookupData(TempTrackingSpecification, TempGlobalEntrySummary, FullGlobalDataSetExists, IsHandled);
```

The IsHandled var boolean isn't handled at all however in the procedure that raises the event. If we subscribe to the event, assigning IsHandled := true has no effect on bypassing the code in the COD6501. Please exit the AssistEditTrackingNo procedure  if IsHandled = true. 

Second issue:

There needs to be a similar event raised in SelectMultipleTrackingNo that uses the IsHandled pattern e.g.

```
OnSelectMultipleTrackingNoOnBeforeRetrieveLookupData(...)
```

Currently there is no such event. Just like OnAssistEditTrackingNoOnBeforeRetrieveLookupData, this event needs to be raised before TempGlobalReservEntry.Reset(); is called. If IsHandled = true then abort further processing.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
