### ISSUE TITLE
[Enum Request] Table "Profile Questionaire Line" OptionMembers to Enums 

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#12182]
**Type**, Customer Class. Field, "Vendor Class. Field","Contact Class. Field"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
