### ISSUE TITLE
[Enum Request] table 5089 "Contact Profile Answer" OptionMember to Enums

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#12183]
"Answer Priority"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
