### ISSUE TITLE
Soften requirements for "To"-Address being mandatory in Codeunit 8905 "Email Message Impl."

### ISSUE THREAD

**Issue by ptijsma** [microsoft/ALAppExtensions#12193]
When I want to use the nice email editor in BC, it won't allow me to send a mail to a "BCC"-address only.

![image](https://user-images.githubusercontent.com/18245218/116539191-cb341800-a8e8-11eb-8cc3-c0a4f9c73af4.png)

This is because the code in Procedure ValidateRecepients is way to strict and should be changed to allow for an empty "To"-address when there is a "BCC"-address (or multiple) specified:

```
    procedure ValidateRecipients(Recipients: List of [Text]; RecipientType: Enum "Email Recipient Type")
    var
        EmailAccount: Codeunit "Email Account";
        Recipient: Text;
    begin
        // The below check should be changed
        if (RecipientType = RecipientType::"To") and (Recipients.Count() = 0) then
            Error(NoToAccountErr);
.
.

```

Outlook also supports messages with only a BCC specified:

![image](https://user-images.githubusercontent.com/18245218/116538869-62e53680-a8e8-11eb-82e9-5541ba7c1137.png)

Result:

![image](https://user-images.githubusercontent.com/18245218/116538886-6b3d7180-a8e8-11eb-8791-252dbc41fe76.png)

**Comment by JesperSchulz** [comment]
We're working on a fix. We expect to ship it with version 18.2.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
