### ISSUE TITLE
EMail Module Body Text does not respect Plain Text

### ISSUE THREAD

**Issue by eivindgiske** [microsoft/ALAppExtensions#12194]
In the new Email Module:
When assigning a custom body text to a TempEmailItem using SetBodyText, or by modifying the blob, the EMailMessage."HTML Formatted Body" Does not get set. It retains it's initvalue of True. Because of this Email outbox will load the HTML editor, and the mail gets formatted wrong.

I am using this code to set the body (in an event sub on Codeunit::"Document-Mailing", 'OnBeforeSendEmail'):
TempEmailItem.SetBodyText(BodyText);
TempEmailItem."Plaintext Formatted" := true;
TempEmailItem."Body File Path" := '';

Suggestion: The Email message implementation CU8905, function SetBody, shold include a Message."HTML Formatted Body" := false.

**Comment by eivindgiske** [comment]
Verified by modifying HTML Formatted Body in the database and refreshing EMailEditor.Page:

![before](https://user-images.githubusercontent.com/25768013/116544560-98415280-a8ef-11eb-8ae9-9c5b9791dc72.JPG)
![after](https://user-images.githubusercontent.com/25768013/116544563-98d9e900-a8ef-11eb-9807-be6770f481e3.JPG)

**Comment by mazhelez** [comment]
@eivindgiske I'm not entirely familiar with your case, but codeunit [Email Message](https://github.com/microsoft/ALAppExtensions/blob/master/Modules/System/Email/src/Message/EmailMessage.Codeunit.al) has a few overloads to create a message with plain text (see parameter `HtmlFormatted`).

Could you maybe alter your approach to _not_ use `TempEmailItem`?

**Comment by eivindgiske** [comment]
Hi @mazhelez,
I'm connecting with the event publishers in Codeunit Document-Mailing, to be able to modify the Body before the editor launches. The use case is setting a body text just for e-mailing Purchase Orders to Vendors. I have also tried various other events, also using EmailItem in the new e-mail module, but they all appear to act the same way. When inspecting CU, function SetBody, it seems obvious to me, because the InitValue of HTML Formatted Body is True, and SetBody never overrides that.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
