### ISSUE TITLE
OnBeforeConfirmDownloadShipmentAlsoQst(IsHandled);

### ISSUE THREAD

**Issue by Sleina** [microsoft/ALAppExtensions#12190]
Please include the following with each issue:

1. Describe the bug
Hi

In BC I would like to hide the Dialog which asks to download the shipment document after we use post and send.
![image](https://user-images.githubusercontent.com/55833917/116521193-f06a5b80-a8d3-11eb-95fb-d1f9e105eb6b.png)

Right now there is no integration event which allows me to hide this Dialog.

2. To Reproduce

Go to Sales Order
Create new Sales Order
Post and Send
Ship and Invoice
-> after the posting information the following Dialog pops up:
You can also download the Sales - Shipment document now. Alternatively, you can access it from the Posted Sales Shipments window later.\Do you want to download the Sales - Shipment document now?
Yes/No

    Go to 'Codeunit 80 Sales-Post'
    "if not ConfirmManagement.GetResponseOrDefault(DownloadShipmentAlsoQst, true)"
    begin
    OnSendSalesDocument(Invoice and Ship, SuppressCommit);
    if Invoice then begin
    SalesInvHeader.Get("Last Posting No.");
    SalesInvHeader.SetRecFilter;
    SalesInvHeader.SendProfile(DocumentSendingProfile);
    end;
    if Ship and Invoice and not OfficeManagement.IsAvailable then
    if not ConfirmManagement.GetResponseOrDefault(DownloadShipmentAlsoQst, true) then
    exit;
    if Ship then begin
    SalesShipmentHeader.Get("Last Shipping No.");
    SalesShipmentHeader.SetRecFilter;
    SalesShipmentHeader.SendProfile(DocumentSendingProfile);
    end;
    end;
    3. Expected behavior
    An Integration Event in order to hide the DownloadShipmentAlsoQst Dialog or Workaround.

5. Versions:

    AL Language: v7.1.441584
    Visual Studio Code: March 2021 (version 1.55)
    Business Central: 17.5.22499.22680

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
