### ISSUE TITLE
[EventRequest] Codeunit 7110 (Analysis Report Managment), Function SetItemRowFilters ==> OnAfterSetItemRowFilters 

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#12206]
Hi,
we want to add additional filters on "Item Statistics Buffer" in function "SetItemRowFilters" and therefore we suggest the following Event (see line 620):
![image](https://user-images.githubusercontent.com/47414309/116658150-d55d2180-a98f-11eb-8311-51f7f1ca85b5.png)

The Event should look like this:
![image](https://user-images.githubusercontent.com/47414309/116657966-916a1c80-a98f-11eb-9cf9-0fae71b395da.png)
Please define both parameter as var.

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
