### ISSUE TITLE
[Event Request] Table 7311 "Warehouse Journal Line" - OnValidateQuantityOnBeforeGetWhseItemTrkgSetup

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12209]
Hello, in the Table 7311 "Warehouse Journal Line", in the OnValidate trigger of field 10 "Quantity", I would like to add my own code instead of the standard one at a specific place. To do so, I would need an event publisher and a IsHandled . Like this :

    field(10; Quantity; Decimal)
    {
        ...
        trigger OnValidate()
        var
            ...
            IsHandled : boolean;
        begin
            ...

            OnValidateQuantityOnBeforeGetWhseItemTrkgSetup(Rec, WhseItemTrackingSetup, IsHandled);
            if not IsHandled then

                ItemTrackingMgt.GetWhseItemTrkgSetup("Item No.", WhseItemTrackingSetup);
                if WhseItemTrackingSetup."Serial No. Required" and not "Phys. Inventory" and
                   ("Serial No." <> '') and ((Quantity < 0) or (Quantity > 1))
                then
                    Error(Text006, FieldCaption(Quantity));
            ...
    }

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetItemFields(var WarehouseJournalLine: Record "Warehouse Journal Line"; var WhseItemTrackingSetup: Record "Item Tracking Setup"; var IsHandled: Boolean)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
