### ISSUE TITLE
[Event Request] table 5050 Contact: GetNewCustomerTemplateCode

### ISSUE THREAD

**Issue by TimCsr** [microsoft/ALAppExtensions#12207]
Object: table 5050 Contact

Function: GetNewCustomerTemplateCode

Reason: we don't want the customer to receive the confirm dialogues

Integration Event:

OnbeforeGetNewCustomerTemplateCode(CustTemplate,IsHandled);
![image](https://user-images.githubusercontent.com/50943286/116663822-e90c8600-a997-11eb-9dd0-f1f0ee586659.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
