### ISSUE TITLE
[Event Request] Report "Adjust Cost - Item Entries" - add parameter "var Item: Record Item"

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#12208]
As we have additional filters for item.

    local procedure "Adjust Cost - Item Entries_OnBeforePreReport"
    (
        var Sender: Report "Adjust Cost - Item Entries";
        **var Item: Record Item;**
        ItemNoFilter: Text[250];
        ItemCategoryFilter: Text[250];
        PostToGL: Boolean
    )

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
