### ISSUE TITLE
[Extensibility Enhancement] Codeunit 408 "Dimension Management" - GetGLSetup procedure

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#12216]
Could you make GetGLSetup global?

Thanks :)

**Comment by AlexanderYakunin** [comment]
Can you please explain with code how you are going to use it in extension code?

**Comment by DanielHaglo** [comment]
Hi,

Se image below:
![image](https://user-images.githubusercontent.com/35260264/117106667-8e50a100-ad80-11eb-9ae2-6f711be0c474.png)

**Comment by AlexanderYakunin** [comment]
This is customization of codeunit 408, correct? If we make this function global, how you are going to use it in your extension code? this function set internal variable GLSetupShortcutDimCode, which is not available outside of this codeunit. Do you need some events instead?

**Comment by AlexanderYakunin** [comment]
GLSetupShortcutDimCode is global variable in codeunit Dimension Management, but we cannot use protected attribute in codeunits. Instead, we need to add this as parameter for GetGLSetup(var GLSetupShortcutDimCode: array[8] of Code[20]). In this case you can call this procedure and get this variable in extension. Is it ok for you?

**Comment by DanielHaglo** [comment]
That is perfect! Thank you.
