### ISSUE TITLE
[Request For External] Report "Adjust Cost - Item Entries" - protected vars needed

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#12210]
PostToGL: Boolean;
ItemNoFilter: Text[250];

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
