### ISSUE TITLE
Change VAT Report Type fields from Option to Enum

### ISSUE THREAD

**Issue by LubomirUrx** [microsoft/ALAppExtensions#12214]
Could you change following fields to extensible Enum  ?

```
Table VAT Report Configuration        field VAT Report Type
Table VAT Report Header               field VAT Report Config. Code
Table VAT Statement Report Line       field VAT Report Config. Code
```

**Comment by AlexanderYakunin** [comment]
Looks like we cannot implement VAT Report Type enum due to different implementation of options for VAT Report Type in several countries compared to W1. Do you need this for specific country?

**Comment by RadoArvay** [comment]
Yes, we do. We are implementing Slovak legislation and we have decided to use this funcionality for all VAT reports we use. If it is complicated to change the option to the enum, would it be possible to add a new option to those fields? We want to implement a new report - we call it "VAT Check Statement". Till now we have had a standalone functionality for that and we want to put them together and the VAT Reports seem ideal.
(note: there is very similar funcionality in Czech legislation based on Slovak legislation - maybe, one day, they will use the new option - or enum - in the future)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
