### ISSUE TITLE
[Event Request] Table 7311 "Warehouse Journal Line" - OnValidateToBinCodeOnBeforeToZoneCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12211]
Hello, in the Table 7311 "Warehouse Journal Line", in the OnValidate trigger of field 28 "To Bin Code", I would like to add my own code at a specific place. To do so, I would need an event publisher. Like this :

        field(28; "To Bin Code"; Code[20])
        {
            ...
            trigger OnValidate()
            begin
                ...

                Bin.CalcFields("Adjustment Bin");
                if Bin."Adjustment Bin" and ("Entry Type" <> "Entry Type"::"Negative Adjmt.") then
                    Bin.FieldError("Adjustment Bin");

                OnValidateToBinCodeOnBeforeToZoneCode(Rec, Bin);

                if "To Bin Code" <> '' then
                    "To Zone Code" := Bin."Zone Code";

                if "Entry Type" = "Entry Type"::"Positive Adjmt." then
                    SetUpAdjustmentBin;
            end;
        }

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetItemFields(var WarehouseJournalLine: Record "Warehouse Journal Line"; var Bin: Record Bin;)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
