### ISSUE TITLE
[New Function Request] codeunit "Job Link Usage" 

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#12217]
Could you please create global function? So that when using onbeforeMatchUsageSpecified, we dont have to duplate code.
Thanks.

![image](https://user-images.githubusercontent.com/35260264/116849281-c32cee80-abee-11eb-93a1-695c3988dede.png)

![image](https://user-images.githubusercontent.com/35260264/116849244-b27c7880-abee-11eb-9db0-9b2eb0394ce0.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
