### ISSUE TITLE
[Event-Request] Codeunit 99000856 "Planning Transparency" OnLogSurplus

### ISSUE THREAD

**Issue by THillemeier** [microsoft/ALAppExtensions#12227]
Hello,

please add the following event to codeunit 99000856 "Planning Transparency", function "LogSurplus":

![image](https://user-images.githubusercontent.com/82493733/116855963-9383e380-abfa-11eb-9303-6581fcb8eac6.png)

![image](https://user-images.githubusercontent.com/82493733/116856219-0d1bd180-abfb-11eb-89b6-193dfc85de3e.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
