### ISSUE TITLE
[Protection Level] Codeunit::"Whse. Jnl.-Register Line" - UpdateDefaultBinContent make global

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#12226]
We need to access it from an event.

**Comment by AlexanderYakunin** [comment]
This is global.

**Comment by AlexanderYakunin** [comment]
Please read our rules here, you should not expect external requests to be implemented in PROD version:
https://github.com/Microsoft/ALAppExtensions/blob/master/FAQ.md#what-do-all-the-labels-assigned-to-issues-mean

**Comment by AlexanderYakunin** [comment]
Are you a partner or customer? We are supporting partner extension development on this forum, partners should know what their requests will be completed in Master and release in next major release. The only exception is events, we deliver this in monthly updates. So you should not expect this in 18.1, it will be in 19.0 only. Partner get preview builds in advance to update their extentions for 19.0.

**Comment by AlexanderYakunin** [comment]
Closing
