### ISSUE TITLE
[Event-Request] Table 5802 "Value Entry" OnSumCostsTillValuationDateOnAfterCalsums

### ISSUE THREAD

**Issue by THillemeier** [microsoft/ALAppExtensions#12221]
Hello,

please add the following event to table 5802 "Value Entry", function "SumCostsTillValuationDate":

![image](https://user-images.githubusercontent.com/82493733/116852801-46514300-abf5-11eb-8c49-aec21d9351f3.png)

![image](https://user-images.githubusercontent.com/82493733/116852829-5537f580-abf5-11eb-8506-b6a107aad537.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
