### ISSUE TITLE
[Event-Request] Table 5896 "Inventory Adjmt. Entry (Order)" OnAfterCalcDirectCostFromCostShare

### ISSUE THREAD

**Issue by THillemeier** [microsoft/ALAppExtensions#12222]
Hello,

please add the following event to table 5896 "Inventory Adjmt. Entry (Order), function "CalcDirectCostFromCostShares":

![image](https://user-images.githubusercontent.com/82493733/116854428-f2942900-abf7-11eb-9642-3eb239a32fcc.png)

![image](https://user-images.githubusercontent.com/82493733/116854462-fc1d9100-abf7-11eb-925c-aafef952e5a8.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
