### ISSUE TITLE
[Remove Scope-request] - Codeunit 10610 "E-Invoice Document Encode" - GetVATRegNo 

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#12220]
Could you make this accessible for cloud development?

![image](https://user-images.githubusercontent.com/35260264/116851135-2b310400-abf2-11eb-95a8-304f6389966d.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
