### ISSUE TITLE
[Event-Request] Table 5767 "Warehouse Activity Line" OnBeforeCalcQty

### ISSUE THREAD

**Issue by THillemeier** [microsoft/ALAppExtensions#12229]
Hello,

please add the following event to table 5767 "Warehouse Activity Line", function "CalcQty":

![image](https://user-images.githubusercontent.com/82493733/116856957-486ad000-abfc-11eb-875f-9a336fbaf42a.png)

![image](https://user-images.githubusercontent.com/82493733/116856981-53bdfb80-abfc-11eb-83a0-227625086fb7.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
