### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnBeforeValidateStartingTime

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12237]
Hello. In the table 246 "Requisition Line", in the trigger OnValidate of the field 99000895 "Starting Time", I would like to use the event publisher OnBeforeValidateStartingTime, but I would need 3 more parameters : CurrFieldNo, CurrentFieldNo and xRec . Like this :

        field(99000895; "Starting Time"; Time)
        {
            Caption = 'Starting Time';

            trigger OnValidate()
            var
                ShouldSetDueDate: Boolean;
                IsHandled: Boolean;
            begin
                IsHandled := false;
                OnBeforeValidateStartingTime(Rec, ShouldSetDueDate, IsHandled, CurrFieldNo, CurrentFieldNo, xRec);
                if IsHandled then
                    exit;
                ...
            end;
        }

With this integration event : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateStartingTime(var RequisitionLine: Record "Requisition Line"; var ShouldSetDueDate: Boolean; var IsHandled: Boolean; CurrFieldNo : Integer ; CurrentFieldNo : Integer ; xRequisitionLine: Record "Requisition Line")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
