### ISSUE TITLE
Question regarding issues #11760

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#12230]
In which version will the mark "local" be removed? 
We have several places that are calling this function(PostItemCharge - Purch.-Post)...

**Comment by AlexanderYakunin** [comment]
Usually in master (=next major version)

**Comment by SWE-Tina** [comment]
That's not really satisfying to hear as this would mean approx. next year / at least a couple of months :( - for removing a local in front of a procedure (an that in a main codeunit like purchase post) and on the other way now for us a couple of hours to handle this problem for the meantime.

**Comment by AlexanderYakunin** [comment]
Removing a local in PROD environment can be breaking change for existing PTE's. We already have this experience. Therefore we have established policy for implementation of extensibility requests, new integration events will be implemented in both Master and PROD versions only. Other type of requests can be considered individually based on hotfix requests coming from ISV partners via technical support or ISV program managers. You can follow this path if this is your case.
