### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnBeforeValidateEndingTime

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12239]
Hello. In the table 246 "Requisition Line", in the trigger OnValidate of the field 99000897 "EndingTime", I would like to use the event publisher OnBeforeValidateEndingTime, but I would need 2 more parameters : CurrFieldNo and CurrentFieldNo. Like this :

        field(99000897; "Ending Time"; Time)
        {
            ...
            trigger OnValidate()
            var
                ShouldSetDueDate: Boolean;
                IsHandled: Boolean;
            begin
                IsHandled := false;
                OnBeforeValidateEndingTime(Rec, ShouldSetDueDate, IsHandled, CurrFieldNo, CurrentFieldNo);
                if IsHandled then
                    exit;

                ...
        }

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateEndingTime(var RequisitionLine: Record "Requisition Line"; var ShouldSetDueDate: Boolean; var IsHandled: Boolean; CurrFieldNo : Integer ; CurrentFieldNo : Integer)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
