### ISSUE TITLE
[Event-Request] Page 5870 "BOM Structure" OnBeforeRefreshPage

### ISSUE THREAD

**Issue by THillemeier** [microsoft/ALAppExtensions#12234]
Hello,

please add the following event in page 5870 "BOM Structure", function "RefreshPage":

![image](https://user-images.githubusercontent.com/82493733/116967071-d1900e80-acb1-11eb-8de5-3b176e39af35.png)

![image](https://user-images.githubusercontent.com/82493733/116967108-e2d91b00-acb1-11eb-9d60-28135835795c.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
