### ISSUE TITLE
[Event Request] GetBBAN

### ISSUE THREAD

**Issue by LucaCestaro** [microsoft/ALAppExtensions#12238]
Hello, i need a new event in 
GetBBAN Procedure of table 288 "Vendor Bank Account"

    [Scope('OnPrem')]
    procedure GetBBAN()
    begin
        if (ABI <> '') and (CAB <> '') and ("Bank Account No." <> '') then
            BBAN := AbiCabCodes.CalcBBAN(ABI, CAB, "Bank Account No.")
        else
            BBAN := '';
        IBAN := '';
        //>> Start New Publisher Call
        OnAfterSetIBAN(IBAN); 
        //<< End New Publisher Call
    end;

New publisher event:

   LOCAL [IntegrationEvent] OnAfterSetIBAN(VAR  IBAN: Code[50])

Thank You

![image](https://user-images.githubusercontent.com/83650017/117006335-952bd500-ace8-11eb-93b3-a5a8f7377c32.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
