### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnValidateLocationCodeOnBeforeGetDefaultBin

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12236]
Hello. In the table 246 "Requisition Line", in the trigger OnValidate of the field 17 "Location Code", I would like to use the event publisher OnValidateLocationCodeOnBeforeGetDefaultBin, but I would need another parameter : Location. Like this : 

        field(17; "Location Code"; Code[10])
        {
           ...
            trigger OnValidate()
            var
                ItemVend: Record "Item Vendor";
                ShouldGetDefaultBin: Boolean;
            begin
                ...
                if Type = Type::Item then begin
                    UpdateReplenishmentSystem;
                    if "Location Code" <> xRec."Location Code" then
                        if ("Location Code" <> '') and ("No." <> '') and not IsDropShipment then begin
                            GetLocation("Location Code");
                            ShouldGetDefaultBin := Location."Bin Mandatory" and not Location."Directed Put-away and Pick";

                            OnValidateLocationCodeOnBeforeGetDefaultBin(Rec, ShouldGetDefaultBin, Location);

                            if ShouldGetDefaultBin then
                                WMSManagement.GetDefaultBin("No.", "Variant Code", "Location Code", "Bin Code");
                        end;
                    if ItemVend.Get("Vendor No.", "No.", "Variant Code") then
                        "Vendor Item No." := ItemVend."Vendor Item No.";
                end;
                GetDirectCost(FieldNo("Location Code"));
            end;
        }

With this integration event : 

    [IntegrationEvent(false, false)]
    local procedure OnValidateLocationCodeOnBeforeGetDefaultBin(RequisitionLine: Record "Requisition Line"; var ShouldGetDefaultBin: Boolean; Location: Record Location)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
