### ISSUE TITLE
Event Request Codeunit 427 - ICInboxOutboxMgt Function SendSalesDoc

### ISSUE THREAD

**Issue by MGerits** [microsoft/ALAppExtensions#12246]
Hello,
Requesting a new event publisher on codeunit 427 - ICInboxOutboxMgt

I would like to request the following publisher with IsHandled Pattern in Function SendSalesDoc

```
procedure SendSalesDoc(var SalesHeader: Record "Sales Header"; Post: Boolean)
var
    ICPartner: Record "IC Partner";
    IsHandled: Boolean;
begin
    // New Code Begin
    OnBeforeSendSalesDoc(SalesHeader, Post, IsHandled);
    if IsHandled then
        exit;
    // New Code End
```

The signature of the publisher is:
```
[IntegrationEvent(false,false)]
local procedure OnBeforeSendSalesDoc(var SalesHeader: Record "Sales Header"; var Post: Boolean; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
