### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnSetReplenishmentSystemFromPurchaseOnBeforeValidateTransferFromCode

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12243]
Hello. In the table 246 "Requisition Line", in the procedure SetReplenishmentSystemFromPurchase , I would like to add my code at a specific place, in order to modify the field "Vendor Item No." before entering in the trigger OnValidate of "Vendor No.". To do so, I would need an event publisher here :

    local procedure SetReplenishmentSystemFromPurchase(StockkeepingUnit: Record "Stockkeeping Unit")
    begin
        "Ref. Order Type" := "Ref. Order Type"::Purchase;
        Clear("Ref. Order Status");
        "Ref. Order No." := '';
        DeleteRelations;
        Validate("Production BOM No.", '');
        Validate("Routing No.", '');
        UpdateUnitOfMeasureCodeFromItemPurchUnitOfMeasure();
        Validate("Transfer-from Code", '');

        OnSetReplenishmentSystemFromPurchaseOnBeforeValidateTransferFromCode(Rec, StockkeepingUnit);

        if StockkeepingUnit."Vendor No." = '' then
            Validate("Vendor No.")
        else
            Validate("Vendor No.", StockkeepingUnit."Vendor No.");

        OnAfterSetReplenishmentSystemFromPurchase(Rec, Item, StockkeepingUnit);
    end;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnSetReplenishmentSystemFromPurchaseOnBeforeValidateTransferFromCode(var RequisitionLine: Record "Requisition Line"; StockkeepingUnit: Record "Stockkeeping Unit")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
