### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnSetReplenishmentSystemFromProdOrderOnBeforeProcessPlannedOrderNosField

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12247]
Hello. In the table 246 "Requisition Line", in the procedure SetReplenishmentSystemFromProdOrder, I would like to use the event publisher OnSetReplenishmentSystemFromProdOrderOnBeforeProcessPlannedOrderNosField, but I would need 2 more parameters : CurrFieldNo and CurrentFieldNo. Like this :

        OnSetReplenishmentSystemFromProdOrderOnBeforeProcessPlannedOrderNosField(Rec, IsHandled, xRec);

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnSetReplenishmentSystemFromProdOrderOnBeforeProcessPlannedOrderNosField(var RequisitionLine: Record "Requisition Line"; var IsHandled: Boolean; xRequisitionLine: Record "Requisition Line")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
