### ISSUE TITLE
Incorrect Code in Guided Experience

### ISSUE THREAD

**Issue by OlegLobakov** [microsoft/ALAppExtensions#12241]
Procedure Remove removes nothing.

It's need to use ObjectType as a parameter for FilterGuidedExperienceItem procedure.
 

 ```
  procedure Remove(GuidedExperienceType: Enum "Guided Experience Type"; **ObjectType**: ObjectType; ObjectID: Integer)
    var
        GuidedExperienceItem: Record "Guided Experience Item";
        GuidedExperienceObjectType: Enum "Guided Experience Object Type";
    begin
        if not GuidedExperienceItem.WritePermission() then
            exit;

        FilterGuidedExperienceItem(GuidedExperienceItem, GuidedExperienceType, **GuidedExperienceObjectType**, ObjectID, '');

        Delete(GuidedExperienceItem);
    end;
```

**Comment by OlegLobakov** [comment]
This error calls an error in Assisted Setup Page
![bcerror](https://user-images.githubusercontent.com/34211051/117017498-50119e00-acfc-11eb-8f23-32c2a4ec937d.png)
 when Some Wizard is closed.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
