### ISSUE TITLE
[Event Request] Codeunit 1400 "DocumentNoVisibility" - Function "CheckNumberSeries" - OnBeforeCheckNumberSeries

### ISSUE THREAD

**Issue by pearljo** [microsoft/ALAppExtensions#12249]
Hi, would it be possible to get an event OnBeforeCheckNumberSeries Codeunit 1400 "DocumentNoVisibility" - Function "CheckNumberSeries", like this :

procedure CheckNumberSeries(RecVariant: Variant; NoSeriesCode: Code[20]; FieldNo: Integer)
var
        NoSeries: Record "No. Series";
        NoSeriesMgt: Codeunit NoSeriesManagement;
        RecRef: RecordRef;
        FieldRef: FieldRef;
        NewNo: Code[20];
begin
        **OnBeforeCheckNumberSeries(RecVariant, NoSeriesCode, FieldNo, NoSeries);**
        if RecVariant.IsRecord and (NoSeriesCode <> '') and NoSeries.Get(NoSeriesCode) then begin
            NewNo := NoSeriesMgt.DoGetNextNo(NoSeriesCode, 0D, false, true);
            RecRef.GetTable(RecVariant);
            FieldRef := RecRef.Field(FieldNo);
            FieldRef.SetRange(NewNo);
            if RecRef.FindFirst then begin
                NoSeriesMgt.SaveNoSeries;
                CheckNumberSeries(RecRef, NoSeriesCode, FieldNo);
            end;
        end;
end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckNumberSeries(var RecVariant: Variant; var NoSeriesCode: Code[20]; FieldNo: Integer; var NoSeries: Record "No. Series")
    begin
    end;

Please let me know if this event has been published on the next minor / major release.
Thanks in advance :)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
