### ISSUE TITLE
Bug Transfer Header

### ISSUE THREAD

**Issue by GiorgioOngaroVelika** [microsoft/ALAppExtensions#12255]
Hi,

when I try to post & print a transfer order without having specified the default shipping agent code in "Transfer Route Specification" I don't see errors because on the Transfer Shipment created the shipping agent code is blank.
When I populate the "shipping agent code" in "Transfer Route Specification" and I insert, "post & print" the transfer order, BC return an error because, in the printing step, the procedure check the "TDD Prepared By" wich is blank on the Transfer Shipment Header.
Same error if i try to print the Transfer Shipment.

I solved with the following code: 

```
    [EventSubscriber(ObjectType::Table, Database::"Transfer Shipment Header", 'OnAfterCopyFromTransferHeader', '', false, false)]
    local procedure OnAfterCopyFromTransferHeader(var TransferShipmentHeader: Record "Transfer Shipment Header"; TransferHeader: Record "Transfer Header")
    begin
        TransferShipmentHeader."TDD Prepared By" := TransferHeader."TDD Prepared By";
    end;
```

can it be added to the standard?
Thanks,
Giorgio

**Comment by dannoe** [comment]
"TDD Prepared By" is not in the base app of microsoft. It is probably added by a PTE or appsource app.

**Comment by GiorgioOngaroVelika** [comment]
Thanks for the reply, the field is in the base app but on the italian localization.

![image](https://user-images.githubusercontent.com/80888445/117584785-26e37a00-b10f-11eb-8426-0ffb2327d18d.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
