### ISSUE TITLE
[External] Query on Device table

### ISSUE THREAD

**Issue by shuyusheng** [microsoft/ALAppExtensions#12257]
We would like to request a Query to read data from the Device table, similar to query 774 "Users in Plans".
This will be used for licensing for our apps where we will charge a cost per device.

Ideally all the current 4 fields will be made available: MAC Address, Name, Device Type, Enabled. But if MAC Address cannot be exposed then we would like the internal System ID field to be exposed instead, so we at least have an unique identifier.

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
The following query was implemented:
// ------------------------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// ------------------------------------------------------------------------------------------------

/// <summary>
/// Displays a list of devices.
/// </summary>
query 776 Device
{
    Caption = 'Device';
    Permissions = tabledata Device = r;

    elements
    {
        dataitem(Device; Device)
        {
            column(MAC_Address; "MAC Address")
            {
            }
            column(Name; Name)
            {
            }
            column(Device_Type; "Device Type")
            {
            }
            column(Enabled; Enabled)
            {
            }
        }
    }
}

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
