### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnBeforeTransferFromUnplannedDemand

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12251]
Hello. In the table 246 "Requisition Line", in the procedure TransferFromUnplannedDemand, I would like to add my code at a specific place, in order to increment "Line No." by 1000 instead of 10000. To do so, I would need an event publisher and a IsHandled flag, like this :

    procedure TransferFromUnplannedDemand(var UnplannedDemand: Record "Unplanned Demand")
    var
        IsHandled : boolean;    
    begin
        Init;

        IsHandled := false;
        OnBeforeTransferFromUnplannedDemand(Rec, IsHandled);
        if not IsHandled then begin
            "Journal Batch Name" := GetJnlBatchNameForOrderPlanning();
            "Line No." := "Line No." + 10000;
            "Planning Line Origin" := "Planning Line Origin"::"Order Planning";
        end;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferFromUnplannedDemand(var RequisitionLine: Record "Requisition Line"; var IsHandled : boolean)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
