### ISSUE TITLE
[Event Request] codeunit 1605 "PEPPOL Management" - OnAfterGetAccountingCustomerPartyContact

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#12256]
Can you add event OnAfterGetAccountingCustomerPartyContact in codeunit 1605 "PEPPOL Management"?
Include all parameters from GetAccountingCustomerPartyContact and the customer record.

```
        if Customer.Get(SalesHeader."Bill-to Customer No.") then begin
            CustContactTelephone := Customer."Phone No.";
            CustContactTelefax := Customer."Telex No.";
            CustContactElectronicMail := Customer."E-Mail";
        end;
        // >>>>>>>>>>>>>>>>>>>>>>>
        OnAfterGetAccountingCustomerPartyContact(SalesHeader, Customer, CustContactID, CustContactName, CustContactTelephone, CustContactTelefax, CustContactElectronicMail)
        // <<<<<<<<<<<<<<<<<<<<<<<
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
