### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - OnTransferFromUnplannedDemandOnBeforeSetStatus

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12252]
Hello. In the table 246 "Requisition Line", in the procedure TransferFromUnplannedDemand, I would like to use the event publisher OnTransferFromUnplannedDemandOnBeforeSetStatus, but I would need 1 more parameter : Vend. Like this :

        OnTransferFromUnplannedDemandOnBeforeSetStatus(Rec, UnplannedDemand, Vend);

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnTransferFromUnplannedDemandOnBeforeSetStatus(var RequisitionLine: Record "Requisition Line"; var UnplannedDemand: Record "Unplanned Demand"; var Vend: Record Vendor)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by Oleg-Romashkov** [comment]
There is no variable Vend (or Vendor) neither local no global. Please, check the latest code version.
