### ISSUE TITLE
[Event Request] Table 5965"Service Contract Header" - OnBeforeReturnNoOfPer

### ISSUE THREAD

**Issue by tbrdr** [microsoft/ALAppExtensions#12258]
Hi
To be able to handle other invoice periods than the standard ones, we would need an event publisher which allows us to replace the calculation in ReturnNoOfPer on 5965 "Service Contract Header".

As a second request we would like to have the type of the the return value (RetPer) changed from Integer to Decimal, to accommodate for invoice periods > 1y. 

```
procedure ReturnNoOfPer(InvoicePeriod: Enum "Service Contract Header Invoice Period") RetPer: Decimal
    var 
    isHandled: Boolean;
    begin
    isHandled := false;
    OnBeforeReturnNoOfPer(IncoicePeriod, RetPer, IsHandled);
    if IsHandled then
        exit;
    //Standard Code of the procedure...
        end;
    end;


[IntegrationEvent(false,false)]
local procedure OnBeforeReturnNoOfPer(IncoicePeriod: Enum "Service Contract Header Invoice Period"; var RetPer; var IsHandled: Boolean)
begin
end;
```

Thank you for your consideration.
Best regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
