### ISSUE TITLE
Amount must have a value in Gen. Journal Line issue

### ISSUE THREAD

**Issue by OSH-ZT** [microsoft/ALAppExtensions#12253]
Hello MS team.
I got an error during posting a service order with a warranty when the order had a 100 percentage line discount.
Previous versions allowed do this procedure.
If I choose the wrong repository could you please suggest? Because it is a very critical standard issue.

BC18 NA localization
(Database without any customization and additional extensions)
![image](https://user-images.githubusercontent.com/66109755/117154252-58351080-adc4-11eb-93c4-349bdf6938df.png)

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
As this repository is only for issues related to the AL compiler in latest developer preview environment for Dynamics 365 Business Central. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.
Anyway, if you still think this is a bug, please reach out to the relevant support channels as specified in Product Support.
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot process bug reports here, it should go through technical support to collect needed information and repro steps.
