### ISSUE TITLE
Report 493 "Carry Out Action Msg. - Req.": New Function "GetHideDialog"

### ISSUE THREAD

**Issue by RaKuNbg** [microsoft/ALAppExtensions#12254]
Can we get a new function "GetHideDialog" in Report 493 that returns the value of the HideDialog variable.

We need a possibility to react on this field when subscribing to the OnBeforePostReport event.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
