### ISSUE TITLE
[Parameter Request ] Codeunit Event"Item Charge Assgnt. (Sales)" -"OnAssignByWeightOnBeforeTempItemChargeAssgntSalesDelete"

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#12268]
Currency would be needed...:

    [IntegrationEvent(false, false)]
    local procedure OnAssignByWeightOnBeforeTempItemChargeAssgntSalesDelete(var ItemChargeAssignmentSales: Record "Item Charge Assignment (Sales)"; QtyRemaining: Decimal; TotalQtyToAssign: Decimal; **Currency: Record Currency**)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
