### ISSUE TITLE
[Event Request] Codeunit 10750 “SII XML Creator” – OnAfterPlaceFiltersVatEntryOnCalculateNonExemptVATEntries -OnAfterRemoveFiltersVatEntryOnCalculateNonExemptVATEntries -OnHandleReplacementPurchCorrectiveInvoiceOnAfterAddElementDetalleIVA -OnAfterPlaceFiltersVatEntryOnFillDetalleIVANode -OnAfterRemoveFiltersVatEntryOnFillDetalleIVANode

### ISSUE THREAD

**Issue by cristinacarr** [microsoft/ALAppExtensions#12265]
Hi, Could you please add the following 5 events in the codeunit 10750.

Reason: To implement custom business logic and new tags after the execution of the functions.

1st and 2nd Events in the Function: CalculateNonExemptVATEntries

Publisher Event: OnAfterPlaceFiltersVatEntryOnCalculateNonExemptVATEntries
Publisher Event: OnAfterRemoveFiltersVatEntryOnCalculateNonExemptVATEntries

Where is the event placed (see code and image attached)?:

    local procedure CalculateNonExemptVATEntries(var TempVATEntryOut: Record "VAT Entry" temporary; TempVATEntry: Record "VAT Entry" temporary; SplitByEUService: Boolean; VATAmount: Decimal)
     begin
        TempVATEntryOut.SetRange("VAT %", TempVATEntry."VAT %");
        TempVATEntryOut.SetRange("EC %", TempVATEntry."EC %");
        if SplitByEUService then
            TempVATEntryOut.SetRange("EU Service", TempVATEntry."EU Service");
        >>>>>>>>>>>>>>>>>>>>
        OnAfterPlaceFiltersVatEntryOnCalculateNonExemptVATEntries(TempVATEntryOut; TempVATEntry; SplitByEUService; VATAmount);
        <<<<<<<<<<<<<<<<<<<<

        if TempVATEntryOut.FindFirst then begin
            TempVATEntryOut.Amount += VATAmount;
            TempVATEntryOut.Base += TempVATEntry.Base + TempVATEntry."Unrealized Base";
            TempVATEntryOut.Modify();
        end else begin
            TempVATEntryOut.Init();
            TempVATEntryOut.Copy(TempVATEntry);
            TempVATEntryOut.Amount := VATAmount;
            TempVATEntryOut.Base := TempVATEntryOut.Base + TempVATEntryOut."Unrealized Base";
            TempVATEntryOut.Insert();
        end;
        TempVATEntryOut.SetRange("VAT %");
        TempVATEntryOut.SetRange("EC %");
        TempVATEntryOut.SetRange("EU Service");

        >>>>>>>>>>>>>>>>
        OnAfterRemoveFiltersVatEntryOnCalculateNonExemptVATEntries(TempVATEntryOut);
        <<<<<<<<<<<<<<<<

    end;

![image](https://user-images.githubusercontent.com/74407941/117266033-1ef8b100-ae55-11eb-82e3-24c2a2f351ad.png)

Events Code:
[IntegrationEvent(false, false)]
local procedure OnAfterPlaqceFiltersVatEntryOnCalculateNonExemptVATEntries(var TempVATEntryOut: Record "VAT Entry" temporary; TempVATEntry: Record "VAT Entry" temporary; SplitByEUService: Boolean; VATAmount: Decimal)
    begin
    end;

 [IntegrationEvent(false, false)]
 local procedure OnAfterRemoveFiltersVatEntryOnCalculateNonExemptVATEntries(var TempVATEntryOut: Record "VAT Entry" temporary)
 begin
 end;

3rd Event in the Function: HandleReplacementPurchCorrectiveInvoice:

Publisher Event: OnHandleReplacementPurchCorrectiveInvoiceOnAfterAddElementDetalleIVA

Where is the event placed (see code and image attached)?:

        // calculate Credit memo differences grouped by VAT %
        CalcNonExemptVATEntriesWithCuotaDeducible(TempVATEntryPerPercent, CuotaDeducibleDecValue, VendorLedgerEntry, 1);
        CuotaDeducibleDecValue := Abs(CuotaDeducibleDecValue);
         XMLDOMManagement.AddElementWithPrefix(XMLNode, 'DesgloseFactura', '', 'sii', SiiTxt, XMLNode);

        // calculate old and new VAT totals grouped by VAT %
        CalcNonExemptVATEntriesWithCuotaDeducible(TempOldVATEntryPerPercent, CuotaDeducibleDecValue, OldVendorLedgerEntry, -1);
        CuotaDeducibleDecValue := Abs(CuotaDeducibleDecValue);

        // loop over and fill diffs
        TempVATEntryPerPercent.Reset();
        TempVATEntryPerPercent.SetCurrentKey("VAT %", "EC %");
        if TempVATEntryPerPercent.FindSet then begin
            XMLDOMManagement.AddElementWithPrefix(XMLNode, 'DesgloseIVA', '', 'sii', SiiTxt, XMLNode);
            repeat
                CalcTotalDiffAmounts(
                  BaseAmountDiff, VATAmountDiff, ECPercentDiff, ECAmountDiff, TempOldVATEntryPerPercent, TempVATEntryPerPercent);

                // fill XML
                OnHandleReplacementPurchCorrectiveInvoiceOnBeforeAddElementDetalleIVA(XMLNode, VendorLedgerEntry);
                XMLDOMManagement.AddElementWithPrefix(XMLNode, 'DetalleIVA', '', 'sii', SiiTxt, XMLNode);

                >>>>>>>>>>>>>>>>>
	            OnHandleReplacementPurchCorrectiveInvoiceOnAfterAddElementDetalleIVA(XMLNode, VendorLedgerEntry, TempVATEntryPerPercent);
                <<<<<<<<<<<<<<<<<

                XMLDOMManagement.AddElementWithPrefix(
                  XMLNode, 'TipoImpositivo', FormatNumber(TempVATEntryPerPercent."VAT %"), 'sii', SiiTxt, TempXMLNode);
                XMLDOMManagement.AddElementWithPrefix(XMLNode, 'BaseImponible', FormatNumber(BaseAmountDiff), 'sii', SiiTxt, TempXMLNode);
                OnBeforeAddVATAmountPurchDiffElement(TempVATEntryPerPercent, VATAmountDiff);
                XMLDOMManagement.AddElementWithPrefix(XMLNode, 'CuotaSoportada', FormatNumber(VATAmountDiff), 'sii', SiiTxt, TempXMLNode);

                GenerateRecargoEquivalenciaNodes(XMLNode, ECPercentDiff, ECAmountDiff);
                XMLDOMManagement.FindNode(XMLNode, '..', XMLNode);
                ECVATEntryExists := ECVATEntryExists or (ECPercentDiff <> 0);
            until TempVATEntryPerPercent.Next() = 0;
            XMLDOMManagement.FindNode(XMLNode, '..', XMLNode);
        end;
        XMLDOMManagement.FindNode(XMLNode, '..', XMLNode);

![image](https://user-images.githubusercontent.com/74407941/117266896-0341da80-ae56-11eb-989b-e7fbde957197.png)

Event Code:
 [IntegrationEvent(false, false)]
 local procedure OnHandleReplacementPurchCorrectiveInvoiceOnAfterAddElementDetalleIVA(var XMLNode: DotNet XmlNode; VendorLedgerEntry: Record "Vendor Ledger Entry";var TempVATEntryPerPercent: Record “VAT Entry” temporary)
 begin
 end;

4th and 5th Events in the Function: FillDetalleIVANode

Publisher Event: OnAfterPlaceFiltersVatEntryOnFillDetalleIVANode(TempVATEntry);

Publisher Event: OnAfterRemoveFiltersVatEntryOnFillDetalleIVANode(TempVATEntry);

Where is the event placed (see code and image attached)?:

        

        local procedure FillDetalleIVANode(var XMLNode: DotNet XmlNode; var TempVATEntry: Record "VAT Entry" temporary; UseSign: Boolean; Sign: Integer; FillEUServiceNodes: Boolean; NonExemptTransactionType: Option S1,S2,S3,Initial; RegimeCodes: array[3] of Code[2]; AmountNodeName: Text)
    var
        TempXmlNode: DotNet XmlNode;
        Base: Decimal;
        Amount: Decimal;
        ECPercent: Decimal;
        ECAmount: Decimal;
        VATPctText: Text;
    begin
        TempVATEntry.SetRange("VAT %", TempVATEntry."VAT %");
        TempVATEntry.SetRange("EC %", TempVATEntry."EC %");

        >>>>>>>>>>>>>>>>>>>
        OnAfterPlaceFiltersVatEntryOnFillDetalleIVANode(TempVATEntry);
        <<<<<<<<<<<<<<<<<<<

        repeat
            if UseSign then begin
                Base += TempVATEntry.Base * Sign;
                Amount += TempVATEntry.Amount * Sign;
            end else begin
                Base += Abs(TempVATEntry.Base);
                Amount += Abs(TempVATEntry.Amount);
            end;
        until TempVATEntry.Next() = 0;
        if TempVATEntry."EC %" <> 0 then begin
            ECPercent := TempVATEntry."EC %";
            ECAmount += CalculateECAmount(Base, TempVATEntry."EC %");
            Amount := Amount - ECAmount;
        end;

        TempVATEntry.SetRange("VAT %");
        TempVATEntry.SetRange("EC %");

        >>>>>>>>>>>>>>>>>>>>>
        OnAfterRemoveFiltersVatEntryOnFillDetalleIVANode(TempVATEntry);
        <<<<<<<<<<<<<<<<<<<<<

        VATPctText :=
          FormatNumber(CalcTipoImpositivo(NonExemptTransactionType, RegimeCodes, Base, TempVATEntry."VAT %"));

        XMLDOMManagement.AddElementWithPrefix(XMLNode, 'DetalleIVA', '', 'sii', SiiTxt, XMLNode);
        OnFillDetalleIVANodeOnBeforeExportTipoImpositivo(XMLNode, TempVATEntry);
        if ExportTipoImpositivo(TempVATEntry, RegimeCodes) then

![image](https://user-images.githubusercontent.com/74407941/117267155-456b1c00-ae56-11eb-9451-6906330126a5.png)

Events Code:
 [IntegrationEvent(false, false)]
 local procedure OnAfterPlaceFiltersVatEntryOnFillDetalleIVANode(var TempVATEntry: Record "VAT Entry" temporary)
 begin
 end;

 [IntegrationEvent(false, false)]
 local procedure OnAfterRemoveFiltersVatEntryOnFillDetalleIVANode(var TempVATEntry: Record "VAT Entry" temporary)
 begin
 end;

Best Regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
