### ISSUE TITLE
[Event Request] report 950 "Create Time Sheets" - OnBeforeCheckPermissions

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#12266]
Please  allow us to handle the permission checks ourself without substituting the report.
Business Case: Every User sould be allowed to create time sheets for himself.
```
    trigger OnPreReport()
    var
        UserSetup: Record "User Setup";
        i: Integer;
        LastDate: Date;
        FirstAccPeriodStartingDate: Date;
        LastAccPeriodStartingDate: Date;
   +    Handled : Boolean;
    begin
   +    OnBeforeCheckPermissions(Handled)
   +    if not Handled then begin
            if (not UserSetup.Get(UserId) or not UserSetup."Time Sheet Admin.") and UserSetup.WritePermission then
                if Confirm(OpenUserSetupQst, true) then
                    PAGE.RunModal(PAGE::"User Setup");

            if not UserSetup.Get(UserId) or not UserSetup."Time Sheet Admin." then
                Error(Text002);
   +    end;
        if StartingDate = 0D then
            Error(Text004, Text005);
```
Better would be to move the checks to a new function but i think this way its more comprehensible

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
