### ISSUE TITLE
[Event Request] Table 36 Sales Header - TestQuantityShippedField - OnBeforeTestQuantityShippedField

### ISSUE THREAD

**Issue by DominikWidmann** [microsoft/ALAppExtensions#12270]
We need a new event in the procedure TestQuantityShippedField of Table "Sales Header" before the Testfield is done to do extended checks.

Suggested Code:

```
    procedure TestQuantityShippedField(SalesLine: Record "Sales Line")
    var
      IsHandled: Boolean; // New local variable
    begin
        // START 
        IsHandled := false;
        OnAfterTestQuantityShippedField(SalesLine, IsHandled);
        if IsHandled then
          exit;
        //END
        SalesLine.TESTFIELD("Quantity Shipped",0);
        OnAfterTestQuantityShippedField(SalesLine);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
