### ISSUE TITLE
[Function Request] table 39 "Purchase Line" / table 7317 "Warehouse Receipt Line" function "SetCurrFieldNo"

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#12277]
It would be nice if the Current Field No could be set from outside via function.

Of course, it would be best to have such a function in every table.
This would largely avoid duplicating the standard code in the OnValidate trigger for your own fields.

**Comment by AlexanderYakunin** [comment]
Please read this https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-system-defined-variables. We cannot set system variable from application code, it can be set by platform. If you have good justification for changing this approach, please create requests for platform team here https://github.com/microsoft/AL

**Comment by sschuh** [comment]
thanks for your answer...

In C\AL it was possible to create a function like:

Int: = MyRecord.GetCurrFieldNo();

MyRecord.SetCurrFieldNo() = Int;

i created an indea:
https://experience.dynamics.com/ideas/idea/?ideaid=ba826870-5ab1-eb11-89ee-0003ff457d07
