### ISSUE TITLE
[Event Request] codeunit 1255 "Match Bank Payments"

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/ALAppExtensions#12279]
I need events to add custom filters in these procedures:
UpdatePaymentMatchDetails
DeletePaymentMatchDetails

like:
OnFilterAppliedPaymentEntry(var AppliedPaymentEntry: Record "Applied Payment Entry")
OnFilterPaymentMatchingDetails(var PaymentMatchingDetails: Record "Payment Matching Details")

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.

**Comment by stefanoPrimo** [comment]
Here you are!
(I've made also a change to that event signature, I've added a new parameter)

```

    local procedure DeletePaymentMatchDetails(BankAccReconciliation: Record "Bank Acc. Reconciliation")
    var
        PaymentMatchingDetails: Record "Payment Matching Details";
    begin
        PaymentMatchingDetails.SetRange("Statement Type", BankAccReconciliation."Statement Type");
        PaymentMatchingDetails.SetRange("Bank Account No.", BankAccReconciliation."Bank Account No.");
        PaymentMatchingDetails.SetRange("Statement No.", BankAccReconciliation."Statement No.");
        OnFilterPaymentMatchingDetails(PaymentMatchingDetails, BankAccReconciliation)
        PaymentMatchingDetails.DeleteAll(true);
    end;

    local procedure DeleteAppliedPaymentEntries(BankAccReconciliation: Record "Bank Acc. Reconciliation")
    var
        AppliedPaymentEntry: Record "Applied Payment Entry";
    begin
        AppliedPaymentEntry.SetRange("Statement Type", BankAccReconciliation."Statement Type");
        AppliedPaymentEntry.SetRange("Bank Account No.", BankAccReconciliation."Bank Account No.");
        AppliedPaymentEntry.SetRange("Statement No.", BankAccReconciliation."Statement No.");
        OnFilterAppliedPaymentEntry(AppliedPaymentEntry, BankAccReconciliation)
        AppliedPaymentEntry.DeleteAll(true);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnFilterAppliedPaymentEntry(var AppliedPaymentEntry: Record "Applied Payment Entry")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnFilterPaymentMatchingDetails(var PaymentMatchingDetails: Record "Payment Matching Details")
    begin
    end;
```

![image](https://user-images.githubusercontent.com/36199751/118094469-0f3a1900-b3cf-11eb-90f4-d51659d84123.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
