### ISSUE TITLE
[Event Request] Codeunit 1620 "PEPPOL Validation": Run Event OnBeforeRun

### ISSUE THREAD

**Issue by hemmsi** [microsoft/ALAppExtensions#12288]
Hi.

I need an event in Codeunit 1620 "PEPPOL Validation" at the begininig of the OnRun trigger since the localization I am using (Norwegian) always runs this codeunit when __E-Invoice__ is enabled for a Sales Header. I therefore have no way of using the standard E-Invoicing functionality for a different format.

The event needs to have either an IsHandled parameter or return value.

The OnRun trigger could look like this:

```pascal
    trigger OnRun()
    var
        IsHandled: Boolean;
    begin
        OnBeforeRun(Rec, IsHandled);
        if IsHandled then
             exit;

        CheckSalesDocument(Rec);
        CheckSalesDocumentLines(Rec);
    end;
```

and the event like this:

```pascal
    [IntegrationEvent(false, false)]
    local procedure OnBeforeRun(SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
