### ISSUE TITLE
[Event Request] Codeunit 5705 "TransferOrder-Post Receipt" - OnBeforeTransferOrderPostReceipt - Missing "Sender" parameter

### ISSUE THREAD

**Issue by vdevmt** [microsoft/ALAppExtensions#12285]
The OnBeforeTransferOrderPostReceipt event in codeunit 5705 "TransferOrder-Post Receipt" doesn't expose Sender parameter:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferOrderPostReceipt(var TransferHeader: Record "Transfer Header"; CommitIsSuppressed: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
