### ISSUE TITLE
Bug ReportDataset Codeunit

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#12280]
Hello,

we did an Upgrade from BC16 to BC18 and one of our tests fails. We test, if the dataset of a report contains the number of the sales lines.
This still works, if there is only one sales line. If I have two sales lines, the test fails. In the debugger it appears that only the first sales line is found. 
The test fails because of this Assert-Function:
``LibraryAssert.AreNotEqual(-1, LibraryReportDataset.FindRow('No_SalesLine', SalesLine."No."), 'No. not found');``

Maybe I do something wrong. Can you help me with this issue?
Thanks.

**Comment by AlexanderYakunin** [comment]
No, we cannot help with this request based on provided information. You need to debug your test to understand what is wrong. It really depends on the code in your test method.
