### ISSUE TITLE
[Event Request] codeunit 22 Item Jnl.-Post Line. - Add parameter to function OnCodeOnBeforeCheckItemTracking

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12295]
Dear ALAppExtensions Team,

Is it possible to add a parameter to function OnCodeOnBeforeCheckItemTracking in codeunit 22?

-OnCodeOnBeforeCheckItemTracking(ItemJnlLine, DisableItemTracking, IsHandled);
+OnCodeOnBeforeCheckItemTracking(ItemJnlLine, DisableItemTracking, IsHandled, TempTrackingSpecification);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
