### ISSUE TITLE
[Event Request] Add possibility to extend OnFindRecord and OnNextRecord triggers from pageextension objects

### ISSUE THREAD

**Issue by KosPav** [microsoft/ALAppExtensions#12291]
Could you please add possibility to extend **OnFindRecord** and **OnNextRecord** triggers from pageextension objects? Currently it is not supported. But this are very useful and powerfull triggers, which developers often use.
Sometimes the only way is to use this triggers to add needed cusom logic to a page object.
![Screenshot 2021-05-10 212239](https://user-images.githubusercontent.com/45877997/117706389-e569d200-b1d5-11eb-9853-aa851999bca2.png)

**Comment by Stepanenko-Vadim** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
