### ISSUE TITLE
[Event Request] OnCreateItemReferenceBeforeInsert in Codeunit "Item Reference Management"

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#12292]
We are trying to transfer our own fields from the item vendor to the item reference and need the following events to accomplish this:

```al
    local procedure CreateItemReference(ItemVend: Record "Item Vendor")
    var
        ItemReference2: Record "Item Reference";
    begin
        FillItemReferenceFromItemVendor(ItemReference2, ItemVend);
        // ################### NEW START
        OnCreateItemReferenceBeforeInsert(ItemReference2, ItemVend);
        // ################### NEW END
        ItemReference2.Insert();
    end;
```

with the following event signature

```al
    [IntegrationEvent(false, false)]
    local procedure OnCreateItemReferenceBeforeInsert(var ItemReference: Record "Item Reference"; ItemVendor: Record "Item Vendor")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
