### ISSUE TITLE
New Publisher DefaultDimOnDelete in Codeunit 408 DimensionManagement

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#12299]
Please add a new publisher event OnBeforeDefaultDimOnDelete (In codeunit 408 DimensionManagement, function “DefaultDimOnDelete” as shown below:
![image](https://user-images.githubusercontent.com/64889775/117805808-b432e580-b259-11eb-8e48-ec40670b7112.png)

New publisher Event:
    local procedure OnBeforeDefaultDimOnDelete(var DefaultDimension: Record "Default Dimension"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
