### ISSUE TITLE
 Codeunit : 6501 Item Tracking Data Collection

### ISSUE THREAD

**Issue by sami3187** [microsoft/ALAppExtensions#12293]
Codeunit : 6501 Item Tracking Data Collection
Request : 1)add New function  and 2)add condition as per below 

1)
Add New function 
 procedure SetHideValidationDialog(NewHideValidationDialog: Boolean)
    begin
        HideValidationDialog := NewHideValidationDialog;
    end;

2)
procedure SelectMultipleTrackingNo
![Capture](https://user-images.githubusercontent.com/64240684/117769629-84d6a580-b266-11eb-84d6-07e035ef2d1e.JPG)

  **IF NOT HideValidationDialog THEN**  ///add this Line 
 if not (ItemTrackingSummaryForm.RunModal = ACTION::LookupOK) then
                exit;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
