### ISSUE TITLE
Please add a new publisher event OnAfterCalculateTotalPurchaseLineAndVATAmount (In codeunit 57 Document Totals`)

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#12296]
Please add a new publisher event OnAfterCalculateTotalPurchaseLineAndVATAmount (In codeunit 57 Document Totals, function “CalculateTotalPurchaseLineAndVATAmount” as shown below:

![image](https://user-images.githubusercontent.com/64889775/117794786-d9b9f200-b24d-11eb-9e83-c45d3e3b7c9d.png)

New publiher Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterCalculateTotalPurchaseLineAndVATAmount(PurchaseHeader: Record "Purchase Header"; var VATAmount: Decimal; var TempTotalPurchaseLine: Record "Purchase Line" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
