### ISSUE TITLE
New Publisher InsertJobTaskDim in Codeunit 408 DimensionManagement

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#12300]
Please add a new publisher event OnBefore InsertJobTaskDim (In codeunit 408 DimensionManagement, function “InsertJobTaskDim” as shown below:
![image](https://user-images.githubusercontent.com/64889775/117805884-cca30000-b259-11eb-9866-b5f6c782743b.png)

New publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertJobTaskDim(JobNo: Code[20]; JobTaskNo: Code[20]; var GlobalDim1Code: Code[20]; var GlobalDim2Code: Code[20]; var IsHandled: Boolean)
    begin
    end;

**Comment by Oleg-Romashkov** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
