### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - Function PostFlushedConsump

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12305]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 22 Item Jnl.-Post Line - Function PostFlushedConsump
 
            OldTempTrackingSpecification.Reset();
            OldTempTrackingSpecification.DeleteAll();
            TempTrackingSpecification.Reset();
            if TempTrackingSpecification.FindSet then
                repeat
                    OldTempTrackingSpecification := TempTrackingSpecification;
                    OldTempTrackingSpecification.Insert();
                until TempTrackingSpecification.Next() = 0;
            // DINNL <<
            DINOnPostFlushedConsumpOnBeforeTransferPOCompToItemJnlLine(ItemJnlLine, ProdOrderComp);
            // DINNL >>
            ProdOrderCompReserve.TransferPOCompToItemJnlLine(
              ProdOrderComp, ItemJnlLine, Round(QtyToPost * ProdOrderComp."Qty. per Unit of Measure", UOMMgt.QtyRndPrecision));

            OnBeforePostFlushedConsumpItemJnlLine(ItemJnlLine);

            PrepareItem(ItemJnlLine);
            TrackingSpecExists := ItemTrackingMgt.RetrieveItemTracking(ItemJnlLine, TempTrackingSpecification);
            PostItemJnlLine := SetupSplitJnlLine(ItemJnlLine, TrackingSpecExists);

    local procedure DINOnPostFlushedConsumpOnBeforeTransferPOCompToItemJnlLine(ItemJournalLine: Record "Item Journal Line"; ProdOrderComponent: Record "Prod. Order Component")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
