### ISSUE TITLE
New Publisher CreateRowWithColumnsCaptions in Codeunit 424 Export Analysis View

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#12307]
Please add a new publisher event OnAfterFillNextCellRowsCreateRowWithColumnsCaptions (In codeunit 424 Export Analysis View, function “CreateRowWithColumnsCaptions” as shown below:
![image](https://user-images.githubusercontent.com/64889775/117827999-bdc84780-b271-11eb-9a35-fa9a315aff63.png)

New publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterFillNextCellRowsCreateRowWithColumnsCaptions(AnalysisViewEntry : Record "Analysis View Entry";VAR TempExcelBuffer : Record "Excel Buffer" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
