### ISSUE TITLE
[Event Request] Change Publisher OnBeforeCreateGLEntryForTotalAmountsForInvPostBuf in Codeunit 12 Gen. Jnl.-Post Line

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#12304]
Please change the publisher event OnBeforeCreateGLEntryForTotalAmountsForInvPostBuf (In codeunit 12 Gen. Jnl.-Post Line:

**Old** publisher Event:
    [IntegrationEvent(**_false_**, false)]
    local procedure OnBeforeCreateGLEntryForTotalAmountsForInvPostBuf(var GenJnlLine: Record "Gen. Journal Line"; InvPostBuf: Record "Invoice Post. Buffer"; var GLAccNo: Code[20])
    begin
    end;

**Changed** publisher Event:
    [IntegrationEvent(**_true_**, false)]
    local procedure OnBeforeCreateGLEntryForTotalAmountsForInvPostBuf(var GenJnlLine: Record "Gen. Journal Line"; InvPostBuf: Record "Invoice Post. Buffer"; var GLAccNo: Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
