### ISSUE TITLE
New Publisher GetBalAccLocal in Codeunit 5601 FA Insert  G/L Account

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#12309]
Please add a new publisher event OnGetBalAccOnAfterInsertGenJnlLine (In codeunit 5601 FA Insert  G/L Account, function “GetBalAccLocal” as shown below:
![image](https://user-images.githubusercontent.com/64889775/117832139-8360a980-b275-11eb-9f9d-8be2da01716f.png)

New publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnGetBalAccOnAfterInsertGenJnlLine(var GenJournalLine: Record "Gen. Journal Line"; var TempFAGLPostBuf: Record "FA G/L Posting Buffer" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
