### ISSUE TITLE
[Event Request] COD 5763 CreatePostedShptHeader

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/ALAppExtensions#1230]
Would like to request an event OnAfterPostedWhseShptHeaderInsert(PostedWhseShptHeader,WhseShptHeader) on Cod 5763 in the function CreatePostedShptHeader.

**Comment by AlexanderYakunin** [comment]
We already have 2 events here, can you use it?
![image](https://user-images.githubusercontent.com/31849120/53404541-ef250780-39c6-11e9-8a7a-92d8c7f82b4c.png)

**Comment by martinhocosta88** [comment]
@AlexanderYakunin Yes I can. Have to update my docker image thanks.
