### ISSUE TITLE
New Publisher CreateAnalysisViewEntryPart in Codeunit 424 Export Analysis View

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#12306]
Please add a new publisher event OnAfterFillNextCellRowsCreateAnalysisViewEntryPart (In codeunit 424 Export Analysis View, function “CreateAnalysisViewEntryPart” as shown below:
![image](https://user-images.githubusercontent.com/64889775/117827892-a5582d00-b271-11eb-9b0e-23af249c01a5.png)

New publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterFillNextCellRowsCreateAnalysisViewEntryPart(AnalysisViewEntry : Record "Analysis View Entry";VAR TempExcelBuffer : Record "Excel Buffer" temporary)
    begin
    end;

**Comment by Oleg-Romashkov** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
