### ISSUE TITLE
[Event Request] Table 38 Purchase Header - UpdatePurchLinesByFieldNo Function

### ISSUE THREAD

**Issue by AycaE** [microsoft/ALAppExtensions#12317]
Hi,
I would like to request an event publisher shown below. (Table 38 Purchase Header - UpdatePurchLinesByFieldNo Function)

![Event Request  Table 38 Purchase Header - UpdatePurchLinesByFieldNo Function](https://user-images.githubusercontent.com/36567815/117934750-a8076080-b30b-11eb-8e78-2fb481791c07.jpg)

**Comment by Stepanenko-Vadim** [comment]
There is already an event at exactly that place called **OnUpdatePurchLinesByFieldNoOnBeforeValidateFields**.
It's only missing a ChangedFieldNo param from what you are requesting so we will add that param to that event instead of creating a new one.

**Comment by Stepanenko-Vadim** [comment]
The **OnUpdatePurchLinesByFieldNoOnBeforeValidateFields** actually has all the params you want and is situated in the same exact place in code, you should use that event

**Comment by AycaE** [comment]
Hi,
Thanks for quick response. 
ChangedFieldNo and also PurchaseHeader(Rec) needed.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
