### ISSUE TITLE
[Scope Change] codeunit 226 "CustEntry-Apply Posted Entries" procedure SetCheckDim

### ISSUE THREAD

**Issue by GiorgioOngaroVelika** [microsoft/ALAppExtensions#12314]
Please remove the scope OnPrem for procedure SetCheckDim in codeunit 226 "CustEntry-Apply Posted Entries".

thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
