### ISSUE TITLE
Codeunit 46 SelectionFilterManagement with RecordRef from different company

### ISSUE THREAD

**Issue by contecarli** [microsoft/ALAppExtensions#12316]
Hello,

there is a problem in codeunit 46 SelectionFilterManagement: if the RecordRef parameter is set to a different company, the local RecordRef is still opened within the current company. The RecordRef is opened without specifying the company of the input parameter. The correct call would be:
`RecRef.Open(TempRecRef.Number, false, TempRecRef.CurrentCompany);`

![image](https://user-images.githubusercontent.com/64744086/117882049-3b0fae80-b2aa-11eb-9090-beccdf128eb5.png)

Best regards,
Karl

**Comment by AlexanderYakunin** [comment]
I don't think this functionality have been designed for multi company. Can you provide scenario why this is needed?

**Comment by contecarli** [comment]
This is used in reporting functions over multiple companies to get the filters from different setup tables.

For example, depending on the company, only certain entries should be considered in the reporting function, which the user can choose in a setup table. The filter string is then determined by filtering the setup tables (e.g. based on different flags in the table) and calling the function from the selection filter mgt. This string is then used in the subsequent filters.

However, the input should be handled correctly in any case.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
