### ISSUE TITLE
[Event Request] Need old functionality from Codeunit 7000.OnAfterGetSalesLinePrice into new Price Functionality

### ISSUE THREAD

**Issue by KristjanGaukur** [microsoft/ALAppExtensions#12311]
I am using the Event OnAfterGetSalesLinePrice from Codeunit 7000 that is now marked obsolete.
This event has not been moved over to the new Price functionality, and my best guess on where it should be is:

in Table 37 function "PickPrice" get the event OnAfterPickPrice as the last line, with the same parameters as the old event
  :: LOCAL [IntegrationEvent] OnAfterGetSalesLineLineDisc(VAR SalesLine : Record "Sales Line";VAR SalesLineDiscount : Record "Sales Line Discount")

If there is a different place that is better for this event, then I'm fine with that.
What I need is to be able to grab the results of the "Get Price" actions in the document subforms for the "Sales Line" table (which seem to call T37.PickPrice).

Cheers,
Kristján Gaukur Kristjánsson

**Comment by Stepanenko-Vadim** [comment]
Please note that since Sales Line Discount is also obsolete, it's not needed(used) here and will not be provided only Sales Line will be provided as parameter, if you discover that you need something else, let us know in another issue.

**Comment by KristjanGaukur** [comment]
I need to know which price entry was found, so I can utilize my extension fields in that entry. (Be it "Sales Price" while it is not yet discontinued, and the "Price List Line" that is taking over.)
That is what the Event OnAfterGetSalesLinePrice from Codeunit 7000 is giving me now.

(Why do I need to create another issue?)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
