### ISSUE TITLE
Change Publisher OnAfterCopyItemJnlLineFromPurchRcpt in Codeunit 5813 Undo Purchase Receipt Line

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#12319]
Please change the publisher event OnAfterCopyItemJnlLineFromPurchRcpt (In codeunit 5813 Undo Purchase Receipt Line (PurchRcptLine set var):

**_Old_** publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyItemJnlLineFromPurchRcpt(var ItemJournalLine: Record "Item Journal Line"; PurchRcptHeader: Record "Purch. Rcpt. Header"; PurchRcptLine: Record "Purch. Rcpt. Line")
    begin
    end;

**_Changed_** publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyItemJnlLineFromPurchRcpt(var ItemJournalLine: Record "Item Journal Line"; PurchRcptHeader: Record "Purch. Rcpt. Header"; **_var_** PurchRcptLine: Record "Purch. Rcpt. Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
