### ISSUE TITLE
[Event Request] Codeunit 5845 "Get Inventory Report" - OnCheckPostingDateToGLNotTheSameBeforeTempInvtPostingSetupFindFirst #11413 missing parameters #12302

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#12328]
Please also add parameter  WindowPostingType: Text[80]

[IntegrationEvent(false, false)]
local procedure OnCheckPostingDateToGLNotTheSameBeforeTempInvtPostingSetupFindFirst(var TempInvtentoryPostingSetup: Record "Inventory Posting Setup" temporary; var InvtentoryPostingSetup: Record "Inventory Posting Setup"; var InvtentoryReportHeader: Record "Inventory Report Header"; var InventoryReportLine: Record "Inventory Report Entry"; var TotalInventory: Decimal;  **WindowPostingType: Text[80];** var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
