### ISSUE TITLE
Please add protected var for ReqShipDate in Codeunit 5790 additional to #11446

### ISSUE THREAD

**Issue by CL2-SWECON** [microsoft/ALAppExtensions#12325]
Please add in Codeunit 5790:
protected var
  ReqShipDate

**Comment by AlexanderYakunin** [comment]
Protected var does not work in codeunits as they cannot be extended. Instead we need to add this procedure

    procedure GetRequiredShipmentDate(): Date
    begin
        exit(ReqShipDate);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
