### ISSUE TITLE
[Event Request] Table 5900 Service Header - UpdateServLinesByFieldNo Function

### ISSUE THREAD

**Issue by AycaE** [microsoft/ALAppExtensions#12323]
Hi,
I would like to request an event publisher shown below. (able 5900 Service Header - UpdateServLinesByFieldNo Function)

![Event Request  Table 5900 Service Header - UpdateServLinesByFieldNo Function](https://user-images.githubusercontent.com/36567815/117951842-3b955d00-b31d-11eb-86e8-4c7c0906ea25.jpg)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
