### ISSUE TITLE
Additional request for #12075

### ISSUE THREAD

**Issue by CL2-SWECON** [microsoft/ALAppExtensions#12326]
local procedure FillItemReferenceFromItemVendor(var ItemReference: Record "Item Reference"; ItemVend: Record "Item Vendor")
    begin
        ItemReference.Init();
        ItemReference.Validate("Item No.", ItemVend."Item No.");
        ItemReference.Validate("Variant Code", ItemVend."Variant Code");
        ItemReference.Validate("Reference Type", ItemReference."Reference Type"::Vendor);
        ItemReference.Validate("Reference Type No.", ItemVend."Vendor No.");
        ItemReference."Reference No." := ItemVend."Vendor Item No.";
        IsHandled := false;
        OnFillItemReferenceFromItemVendorBeforeCheckUnitOfMeasure(ItemReference, IsHandled);
      **  if not IsHandled then **
        if ItemReference."Unit of Measure" = '' then
        begin
            Item.Get(ItemVend."Item No.");
            ItemReference.Validate("Unit of Measure", Item."Base Unit of Measure");
        end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
