### ISSUE TITLE
[Event Request] Codeunit 7307 "Whse.-Activity-Register" - OnCodeOnBeforeWhseActivLineIsEmpty #11433

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#12327]
in issue #11433 is one parameter missing, please include also HideDialog:
    [IntegrationEvent(false, false)]
    local procedure OnCodeOnBeforeWhseActivLineIsEmpty(var WarehouseActivityLine: Record "Warehouse Activity Line"; **var HideDialog: Boolean;** var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
