### ISSUE TITLE
[Event Request] Codeunit 5817 "Undo Posting Management" - OnUpdateServLineAfterInitQtyToShip #11511

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#12324]
Error in issue #11511 - Name of event does not equal between placement in Code / headline and integration event. Here is the correct integration event for the issue 11511:

[IntegrationEvent(false, false)]
local procedure OnUpdateServLineAfterInitQtyToShip(var ServLine: Record "Service Line")
begin
end;

**Comment by Stepanenko-Vadim** [comment]
It was not an error. My colleague implementing the event refactored code around a bit and to make it uniform with several other requests of events in this code unit it was decided to place the event **OnBeforeRevertPostedItemTrackingFromServiceLine** inside local procedure **RevertPostedItemTrackingFromServiceLine** which is called one step further down the code, the only difference is that there is a modify between those. 
Please consider using this event instead.
If this modify is something you really-really cannot work around, let us know and we will discuss possible approaches
