### ISSUE TITLE
New Publisher PostItemJnlLineAppliedToList in Codeunit 5817 Undo Posting Management

### ISSUE THREAD

**Issue by LLeeman** [microsoft/ALAppExtensions#12320]
Please add a new publisher event OnAfterPostItemJnlLine (In codeunit 5817 Undo Posting Management, function “PostItemJnlLineAppliedToList” as shown below:
![image](https://user-images.githubusercontent.com/64889775/117948651-9fb22400-b311-11eb-8cd3-bc64f4a07e32.png)

New publisher Event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterPostItemJnlLine(var ItemJournalLine: Record "Item Journal Line"; TempApplyToItemLedgEntry: Record "Item Ledger Entry" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
