### ISSUE TITLE
[Event Request] Page 490 "Acc. Schedule Overview" - GetStyle Function

### ISSUE THREAD

**Issue by Celicienta** [microsoft/ALAppExtensions#12322]
Dear ALAppExtensions Team,

I would like to request the following event publisher in page 490 "Acc. Schedule Overview" - GetStyle Function.

![image](https://user-images.githubusercontent.com/74307312/117950435-785c5680-b313-11eb-82c0-21506baab714.png)
New publisher Event:
[IntegrationEvent(false, false)]
local procedure OnBeforeAssignColumnStyle(AccSchLine: Record "Acc. Schedule Line";ColumnNo: Integer;RowLineNo: Integer; 
                                                                          ColumnLineNo: Integer; var ColumnStyle: Text);
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
