### ISSUE TITLE
[Event Request] Extend IntegrationEvent in Codeunit 79 "Sales-Post and Send", function ConfirmPostAndSend

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#12339]
Hello,

please extends IntegrationEvent in Codeunit 79 "Sales-Post and Send", function ConfirmPostAndSend

            Commit();
            TempDocumentSendingProfile.Copy(DocumentSendingProfile);
            TempDocumentSendingProfile.SetDocumentUsage(SalesHeader);
            TempDocumentSendingProfile.Insert();

            // Start kvs.dde
            //OnBeforeConfirmAndSend(SalesHeader, TempDocumentSendingProfile);
            OnBeforeConfirmAndSend(SalesHeader, TempDocumentSendingProfile, IsHandled, ReturnValue);
            if ishandled then begin
                exit(ReturnValue);
            end;
            // Start kvs.dde

            if PAGE.RunModal(PAGE::"Post and Send Confirmation", TempDocumentSendingProfile) <> ACTION::Yes then
                exit(false);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
