### ISSUE TITLE
[Extensibility Request] Add a Procedure CopyTranslations to Translation Module

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#12342]
Could you consider adding a procedure 
```al
CopyTranslations(FromRecordVariant: Variant; ToRecordVariant)
CopyTranslations(FromRecordVariant: Variant; ToRecordVariant; FieldNo: Integer)
```
to the translation Module?
https://github.com/microsoft/ALAppExtensions/blob/master/Modules/System/Translation/src/Translation.Codeunit.al

This can also be a PR, but I still have problems to publish my customized System Application?
Is there some tutorial to get this working?

**Comment by JesperSchulz** [comment]
A PR would be much preferred :-) Have you tried to follow the steps in this article: https://aka.ms/changealmodule? Which issues are you experiencing?

**Comment by pri-kise** [comment]
My main issue, were the missing dynamics DLLs.
A collegue helped with getting these from the DVD Image, but maybe the documentation could be improved were the DLLs can be found.
I know that there is a setting called al.assemlbypath, but I didn't know wich paths are needed.
Additionally I wasn't sure if i can publish my changes on a docker with a cloud sandbox image /artifacts or if system application changes can only be published to OnPremise Artifacts...?

**Comment by JesperSchulz** [comment]
We've received your PR and have left some code review comments. Closing this issue, as we'll address this one via the linked PR.
