### ISSUE TITLE
open access to table 9500 Email item fields "Source Table" and "Source System id"

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#12344]
on table 9500 Email item there are 2 fields
Source table
Source System id
which are now internal.
could this be made accesible for extensions?

when sending custom mails, it would be usefull to be able te enter these fields so that  this info is transferred to the table "email related records" and that user can go to the source record from the "sent mails" page.

**Comment by duichwer** [comment]
You should check out the procedure that is added with version 18.1
AddSourceDocument 
https://github.com/microsoft/ALAppExtensions/discussions/9768#discussioncomment-692223

**Comment by StanPesotskiy** [comment]
Please use AddSourceDocument() method.
