### ISSUE TITLE
Report 5199 - Update Contact Classification - Check GuiAllowed

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12341]
Hi Al team,

we would like to run the report on job queue in the background. For this we need to check guiallowed on Window.Update.
Can you check GuiAllowed every time the Window variable is used?
As an alternative, you could always call a function like this: 

```
protected procedure UpdateWindow(UpdateNumber: Integer; UpdateValue: Integer)
    begin
        if GuiAllowed then
            Window.Update(UpdateNumber, UpdateValue);
    end;

    protected procedure UpdateWindow(UpdateNumber: Integer; UpdateValue: Code[20])
    begin
        if GuiAllowed then
            Window.Update(UpdateNumber, UpdateValue);
    end;

```

**Comment by AlexanderYakunin** [comment]
This is not needed, as platform will suppress Window dialog if GuiAllowed = false. Did you try?

**Comment by MattiLE** [comment]
Hi, you are right. It was an old modification that is actually no longer necessary. Thanks a lot
