### ISSUE TITLE
[Event Request] Item Tracking Data Collection Codeunit 6501 (Repost)

### ISSUE THREAD

**Issue by dpodjasek** [microsoft/ALAppExtensions#12348]
Hello, I am still having an issue with overriding the behavior of serial number tracking overriding the quantity to 1, as described in issue 11859 here:
https://github.com/microsoft/ALAppExtensions/issues/11859

I am now looking at "Microsoft_Base Application_18.0.23013.25150.app", and the code in AssistEditTrackingNo looks essentially the same...

I don't see a function called CalcNewQtyOnLine in C6501, as shown in the reply to my message.  Can someone point me to where that code is?  I think I still need a new event to be able to override the resetting of the quantity of 1 when serials are used.

Thanks!

**Comment by dpodjasek** [comment]
For reference, here is the code I see in the AssistEditTrackiongNo function in the current version (or at least 18.0.23013.25150):

```
            TransferExpDateFromSummary(TempTrackingSpecification, TempGlobalEntrySummary);
            if TempTrackingSpecification.IsReclass or DirectTransfer then
                TempTrackingSpecification.CopyNewTrackingFromTrackingSpec(TempTrackingSpecification);
            OnAssistEditTrackingNoOnAfterCopyNewTrackingFromTrackingSpec(TempTrackingSpecification, DirectTransfer);

            NewQtyOnLine := QtyOnLine + AdjustmentQty + QtyHandledOnLine;
            if TempTrackingSpecification."Serial No." <> '' then
                if Abs(NewQtyOnLine) > 1 then
                    NewQtyOnLine := NewQtyOnLine / Abs(NewQtyOnLine); // Set to a signed value of 1.

            TempTrackingSpecification.Validate("Quantity (Base)", NewQtyOnLine);
```

**Comment by Oleg-Romashkov** [comment]
You can find this code in application version 18.1. Please create a new request based on new code if you still need it.
