### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - Function PostItem

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12354]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 22 Item Jnl.-Post Line - Function PostItem

    procedure PostItem()
    var
        IsHandled: Boolean;
    begin
        OnBeforePostItem(ItemJnlLine, IsHandled);

        with ItemJnlLine do begin
            SKUExists := SKU.Get("Location Code", "Item No.", "Variant Code");
            OnPostItemOnAfterGetSKU(ItemJnlLine, SKUExists);
            if "Item Shpt. Entry No." <> 0 then begin
                "Location Code" := '';
                "Variant Code" := '';
            end;

            if GetItem("Item No.", false) then begin
                if not CalledFromAdjustment then
                    DisplayErrorIfItemIsBlocked(Item);
                Item.CheckBlockedByApplWorksheet;
            end;
            // DINNL <<
            OnPostItemOnAfterCheckItemBlocked(ItemJnlLine, CalledFromAdjustment);
            // DINNL >>

            if ("Inventory Posting Group" = '') and (Item.Type = Item.Type::Inventory) then begin
                Item.TestField("Inventory Posting Group");
                "Inventory Posting Group" := Item."Inventory Posting Group";
            end;

local procedure OnPostItemOnAfterCheckItemBlocked(var ItemJnlLine: Record "Item Journal Line"; CalledFromAdjustment: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
