### ISSUE TITLE
[Scope Change] table 81 "Gen. Journal Line" procedure DeleteTmpWithhSocSec

### ISSUE THREAD

**Issue by GiorgioOngaroVelika** [microsoft/ALAppExtensions#12350]
Please remove the scope OnPrem for procedure DeleteTmpWithhSocSec in table 81 "Gen. Journal Line".

thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
