### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - Function UpdateUnitCost

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12359]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 22 Item Jnl.-Post Line - Function UpdateUnitCost

     if IsInbound and
                   (("Cost Amount (Actual)" + "Discount Amount" > 0) or Item.IsNonInventoriableType) and
                   (ItemJnlLine."Value Entry Type" = ItemJnlLine."Value Entry Type"::"Direct Cost") and
                   (ItemJnlLine."Item Charge No." = '') and not Item."Inventory Value Zero"
                then begin
                    TotalAmount := ItemJnlLine.Amount + ItemJnlLine."Discount Amount";
                    IsHandled := false;
                    OnUpdateUnitCostOnBeforeCalculateLastDirectCost(TotalAmount, ItemJnlLine, ValueEntry, Item, IsHandled);
                    if not IsHandled then
                        LastDirectCost := Round(TotalAmount / "Valued Quantity", GLSetup."Unit-Amount Rounding Precision")
                    // DINNL <<
                    ;
                    DINOnUpdateUnitCost(ValueEntry, LastDirectCost, ItemCostMgt, Item, ItemJnlLine);
                    // DINNL >>
                end;

local procedure DINOnUpdateUnitCost(var ValueEntry: Record "Value Entry"; var LastDirectCost: Decimal; var ItemCostMgt: Codeunit ItemCostManagement; Item: Record Item; ItemJournalLine: Record "Item Journal Line")

**Comment by Stepanenko-Vadim** [comment]
Can you use **OnUpdateUnitCostOnBeforeCalculateLastDirectCost** event instead (it's a couple of lines before the requested one) if we add LastDirectCost, ItemCostMgt to it?

**Comment by NeleBollen** [comment]
I've looked at it and yes, that would be possible if you add var LastDirectCost and var ItemCostMgt.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
