### ISSUE TITLE
[Event Request] Report 1095 "Update Job Item Cost" - OnBeforePostTotalCostAdjustment

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#12369]
Hi, would it be possible to modify the **OnBeforePostTotalCostAdjustment** event in report 1095 (**Update Job Item Cost**) by adding the **var** keyword to the **JobLedgerEntryCostValue**, **JobLedgerEntryCostValueACY** parameters, like this:
```AL
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostTotalCostAdjustment(var JobLedgEntry: Record "Job Ledger Entry"; ItemLedgerEntry: Record "Item Ledger Entry"; var JobLedgerEntryCostValue: Decimal; var JobLedgerEntryCostValueACY: Decimal; var AdjustJobCost: Decimal; var AdjustJobCostLCY: Decimal; var NoOfJobLedgEntry: Integer; var IsHandled: Boolean)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
