### ISSUE TITLE
[Event Request] codeunit 22 Item Jnl.-Post Line. - Change parameter in function OnInsertTransferEntryOnBeforeInitTransValueEntry

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12363]
Dear ALAppExtensions Team,

Is it possible to change parameter NewItemLedgEntry to VAR in function OnInsertTransferEntryOnBeforeInitTransValueEntry in codeunit 22?

-OnInsertTransferEntryOnBeforeInitTransValueEntry(var TempItemEntryRelation: Record "Item Entry Relation"; NewItemLedgEntry: Record "Item Ledger Entry"; Item: Record Item)
+OnInsertTransferEntryOnBeforeInitTransValueEntry(var TempItemEntryRelation: Record "Item Entry Relation"; var NewItemLedgEntry: Record "Item Ledger Entry"; Item: Record Item)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
