### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - Function ApplyItemLedgEntry

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12366]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 22 Item Jnl.-Post Line - Function ApplyItemLedgEntry

            if (ItemLedgEntry."Entry Type" = ItemLedgEntry."Entry Type"::Transfer) and
                   (AppliedQty < 0) and
                   not CausedByTransfer
                then begin
                    if ItemLedgEntry."Completely Invoiced" then
                        ItemLedgEntry."Completely Invoiced" := OldItemLedgEntry."Completely Invoiced";
                    if AverageTransfer then
                        TotalAppliedQty := TotalAppliedQty + AppliedQty
                    else
                        InsertTransferEntry(ItemLedgEntry, OldItemLedgEntry, AppliedQty);
                end;

                ItemLedgEntry."Remaining Quantity" := ItemLedgEntry."Remaining Quantity" - AppliedQty;
                ItemLedgEntry.Open := ItemLedgEntry."Remaining Quantity" <> 0;
                // DINNL <<
                DINOnAppItemLedgEntryFillDualRemainingQty(ItemLedgEntry, DINAppliedDualQty);
                // DINNL >>

                ItemLedgEntry.CalcFields("Reserved Quantity");
                if ItemLedgEntry."Remaining Quantity" + ItemLedgEntry."Reserved Quantity" = 0 then
                    exit;

local procedure DINOnAppItemLedgEntryFillDualRemainingQty(var ItemLedgerEntry: Record "Item Ledger Entry"; AppliedDualQty: Decimal)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
