### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - Function InsertTransferEntry

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12367]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 22 Item Jnl.-Post Line - Function InsertTransferEntry

            OnBeforeInsertTransferEntry(NewItemLedgEntry, OldItemLedgEntry, ItemJnlLine);

            InsertItemLedgEntry(NewItemLedgEntry, true);
            InsertValueEntry(NewValueEntry, NewItemLedgEntry, true);

            UpdateUnitCost(NewValueEntry);
            // DINNL <<
            DINOnAfterInsertTransferEntry(ItemJnlLine, NewItemLedgEntry."Entry No.");
            // DINNL >>
        end;
    end;

    local procedure DINOnAfterInsertTransferEntry(var ItemJnlLine: Record "Item Journal Line"; ItemLedgerEntryNo: Integer)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
