### ISSUE TITLE
[Event Modification] Codeunit 5870 "Calculate BOM Tree" – Integrationevent  “OnAfterTransferFromProdItem”

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#12362]
Hi
Could we please have the Integrationevent OnAfterTransferFromProdItem modified to include the global variable EntryNo as a var parameter?

    local procedure GenerateProdCompSubTree(ParentItem: Record Item; var BOMBuffer: Record "BOM Buffer") FoundSubTree: Boolean
    ...
                                Type::Item:
                                    begin
                                        BOMBuffer.SetLocationVariantFiltersFrom(ItemFilter);
                                        BomQtyPerUom :=
                                        GetQtyPerBOMHeaderUnitOfMeasure(
                                            ParentItem, ParentBOMBuffer."Production BOM No.",
                                            VersionMgt.GetBOMVersion(ParentBOMBuffer."Production BOM No.", WorkDate, true));
                                        BOMBuffer.TransferFromProdComp(
                                        EntryNo, ProdBOMLine, ParentBOMBuffer.Indentation + 1,
                                        Round(
                                            ParentBOMBuffer."Qty. per Top Item" *
                                            UOMMgt.GetQtyPerUnitOfMeasure(ParentItem, ParentBOMBuffer."Unit of Measure Code"), UOMMgt.QtyRndPrecision),
                                        Round(
                                            ParentBOMBuffer."Scrap Qty. per Top Item" *
                                            UOMMgt.GetQtyPerUnitOfMeasure(ParentItem, ParentBOMBuffer."Unit of Measure Code"), UOMMgt.QtyRndPrecision),
                                        ParentBOMBuffer."Scrap %",
                                        CalcCompDueDate(ParentBOMBuffer."Needed by Date", ParentItem, "Lead-Time Offset"),
                                        ParentBOMBuffer."Location Code",
                                        ParentItem, BomQtyPerUom);

                                        if ParentItem."Production BOM No." <> ParentBOMBuffer."Production BOM No." then begin
                                            BOMBuffer."Qty. per Parent" := BOMBuffer."Qty. per Parent" * ParentBOMBuffer."Qty. per Parent";
                                            BOMBuffer."Scrap Qty. per Parent" := BOMBuffer."Scrap Qty. per Parent" * ParentBOMBuffer."Qty. per Parent";
                                            BOMBuffer."Qty. per BOM Line" := BOMBuffer."Qty. per BOM Line" * ParentBOMBuffer."Qty. per Parent";
                                        end;
                                        // Start new code
                                        // OnAfterTransferFromProdItem(BOMBuffer, ProdBOMLine);
                                        OnAfterTransferFromProdItem(BOMBuffer, ProdBOMLine, EntryNo);
                                        // End new code
                                        GenerateItemSubTree("No.", BOMBuffer);
                                    end;
    ...
    
    
    // Start new code
    // [IntegrationEvent(false, false)]
    // local procedure OnAfterTransferFromProdItem(var BOMBuffer: Record "BOM Buffer"; ProdBOMLine: Record "Production BOM Line")
    // begin
    // end;
    [IntegrationEvent(false, false)]
    local procedure OnAfterTransferFromProdItem(var BOMBuffer: Record "BOM Buffer"; ProdBOMLine: Record "Production BOM Line"; var EntryNo: Integer)
    begin
    end;
    // End new code

Thanks, Anders

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
