### ISSUE TITLE
[Event Request] codeunit 22 Item Jnl.-Post Line. - Change parameter in function OnAfterInitItemLedgEntry

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12368]
Dear ALAppExtensions Team,

Is it possible to change parameter ItemJournalLine to VAR in function OnAfterInitItemLedgEntryin codeunit 22?

-local procedure OnAfterInitItemLedgEntry(var NewItemLedgEntry: Record "Item Ledger Entry"; ItemJournalLine: Record "Item Journal Line"; var ItemLedgEntryNo: Integer)
+local procedure OnAfterInitItemLedgEntry(var NewItemLedgEntry: Record "Item Ledger Entry"; var ItemJournalLine: Record "Item Journal Line"; var ItemLedgEntryNo: Integer)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
