### ISSUE TITLE
[Event Request]  EarliestAvailabilityDate Codeunit 5790

### ISSUE THREAD

**Issue by Frmog** [microsoft/ALAppExtensions#12360]
procedure EarliestAvailabilityDate(var Item: Record Item; NeededQty: Decimal; StartDate: Date; ExcludeQty: Decimal; ExcludeOnDate: Date; var AvailableQty: Decimal; PeriodType: Option Day,Week,Month,Quarter,Year; LookaheadDateFormula: DateFormula): Date
    var
        Date: Record Date;
        DummyItem: Record Item;
        AvailabilityAtDate: Record "Availability at Date" temporary;
        CalendarManagement: Codeunit "Calendar Management";
        QtyIsAvailable: Boolean;
        ExactDateFound: Boolean;
        ScheduledReceipt: Decimal;
        GrossRequirement: Decimal;
        AvailableQtyPeriod: Decimal;
        AvailableDate: Date;
        PeriodStart: Date;
        PeriodEnd: Date;
//>> New
       IsHandled : Boolean;
//<< New

    begin
        AvailableQty := 0;

        Item.CopyFilter("Date Filter", DummyItem."Date Filter");
        Item.SetRange("Date Filter", 0D, GetLookAheadPeriodEndDate(LookaheadDateFormula, PeriodType, StartDate));
        CalculateAvailability(Item, AvailabilityAtDate);
        UpdateScheduledReceipt(AvailabilityAtDate, ExcludeOnDate, ExcludeQty);
        CalculateAvailabilityByPeriod(AvailabilityAtDate, PeriodType);

//>> New
      OnBeforeFindAvailableDate(Item, NeededQty, StartDate, AvailableQty, PeriodType, LookaheadDateFormula, AvailabilityAtDate, AvailableDate, IsHandled);
              if IsHandled then
                  exit(AvailableDate);
//<< New
        Date.SetRange("Period Type", PeriodType);
        Date.SetRange("Period Start", 0D, StartDate);
        if Date.FindLast then begin

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
