### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - Function InsertApplEntry

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12371]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 22 Item Jnl.-Post Line - Function InsertApplEntry

        if Quantity < 0 then begin
            OldItemApplnEntry.SetCurrentKey("Inbound Item Entry No.", "Item Ledger Entry No.", "Outbound Item Entry No.");
            OldItemApplnEntry.SetRange("Inbound Item Entry No.", InboundItemEntry);
            OldItemApplnEntry.SetRange("Item Ledger Entry No.", ItemLedgEntryNo);
            OldItemApplnEntry.SetRange("Outbound Item Entry No.", OutboundItemEntry);
            if OldItemApplnEntry.FindFirst then begin
                ItemApplnEntry := OldItemApplnEntry;
                ItemApplnEntry.Quantity := ItemApplnEntry.Quantity + Quantity;
                ItemApplnEntry."Last Modified Date" := CurrentDateTime;
                ItemApplnEntry."Last Modified By User" := UserId;
                // DINNL <<
                DINOnInsertApplEntry(ItemApplnEntry);
                // DINNL >>
                ItemApplnEntry.Modify();
                ItemApplnEntryExists := true;
            end;
        end;

    local procedure DINOnInsertApplEntry(var ItemApplicationEntry: Record "Item Application Entry")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
