### ISSUE TITLE
[Function Expose] UpdateSubForm in Page 474 VAT Statement Preview

### ISSUE THREAD

**Issue by ernestasju** [Microsoft/ALAppExtensions#1237]
Hello,

~We need to use function UpdateSubForm in Page 474 VAT Statement Preview.~ There is exposed function UpdateForm in the subpage, but it requires knowing globals on the main page.

*Update:* It would be better to just have access to page variables using new external function (GetParameters) in Page 474 VAT Statement Preview. See [my comment](https://github.com/Microsoft/ALAppExtensions/issues/1237#issuecomment-465021502) below.

![image](https://user-images.githubusercontent.com/3514528/53393479-28e51680-39a5-11e9-9998-6f177958a0e7.png)

Thanks.

**Comment by mazhelez** [comment]
Hi, @ernestasju 

Correct me if I'm wrong, but isn't the function in question only calling `UpdateForm` in page 475 (which is already _external_).

`UpdateSubForm` in page 474 is local and we tend not to expose local function as this locks the API and we cannot change it in a minor release.

**Comment by ernestasju** [comment]
I knew about that function, but it takes parameters NewSelection, NewPeriodSelection and UseAmtsInAddCurr, which are not accessible from extension (not shown in CurrPage intellisense, and also it is not possible to get their values by modifying page fields or event subscribers).

![image](https://user-images.githubusercontent.com/3514528/52997233-9aaee480-3428-11e9-9b90-6986d16a0f72.png)

I suppose adding external function to get page field values would be better - in our localization extension we also need to modify behavior of how subform calculates column amounts.
