### ISSUE TITLE
[Event Request] PurchPost.Codeunit.al- OnAfterSetWhseRef

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#12384]
We like to request the following Event:
Object: PurchPost.Codeunit.al
Function: CheckAndUpdate
Where is the event placed:
local procedure CheckAndUpdate(var PurchHeader: Record "Purchase Header")
    var
        GenJnlCheckLine: Codeunit "Gen. Jnl.-Check Line";
        CheckDimensions: Codeunit "Check Dimensions";
        ErrorContextElement: Codeunit "Error Context Element";
        ForwardLinkMgt: Codeunit "Forward Link Mgt.";
        SetupRecID: RecordID;
        ModifyHeader: Boolean;
        RefreshTempLinesNeeded: Boolean;
        IsHandled: Boolean;
        CopyAndCheckNeeded: Boolean;
    begin
        with PurchHeader do begin
            // Check
            ErrorMessageMgt.PushContext(ErrorContextElement, RecordId, 0, CheckPurchHeaderMsg);
            CheckMandatoryHeaderFields(PurchHeader);
            if GenJnlCheckLine.IsDateNotAllowed("Posting Date", SetupRecID) then
                ErrorMessageMgt.LogContextFieldError(
                  FieldNo("Posting Date"), StrSubstNo(PostingDateNotAllowedErr, FieldCaption("Posting Date")),
                  SetupRecID, ErrorMessageMgt.GetFieldNo(SetupRecID.TableNo, GLSetup.FieldName("Allow Posting From")),
                  ForwardLinkMgt.GetHelpCodeForAllowedPostingDate);

            SetPostingFlags(PurchHeader);
            OnCheckAndUpdateOnAfterSetPostingFlags(PurchHeader, TempPurchLineGlobal);

            InitProgressWindow(PurchHeader);

            InvtPickPutaway := "Posting from Whse. Ref." <> 0;
            "Posting from Whse. Ref." := 0;
            **OnAfterSetWhseRef(InvtPickPutaway, "Posting from Whse. Ref.");**

            CheckDimensions.CheckPurchDim(PurchHeader, TempPurchLineGlobal);

Event Code:
 local procedure OnAfterSetWhseRef(var InvtPickPutaway: Boolean; Var PostingFromWhseRef: Integer);
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
