### ISSUE TITLE
[Event Request] - PurchPost.Codeunit.al - OnBeforeCopyAndCheckItemCharge

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#12387]
We like to request the following Event:
Object: PurchPost.Codeunit.al
Where is the event placed:
procedure CheckAndUpdate
...
OnAfterSetWhseRef(InvtPickPutaway, "Posting from Whse. Ref.");

            CheckDimensions.CheckPurchDim(PurchHeader, TempPurchLineGlobal);

            if Invoice then
                CheckFAPostingPossibility(PurchHeader);

            CheckPostRestrictions(PurchHeader);

            CheckICDocumentDuplicatePosting(PurchHeader);

            if Invoice then
                Invoice := CalcInvoice(PurchHeader);

            CopyAndCheckNeeded := false;
            **OnBeforeCopyAndCheckItemCharge(PurchHeader, CopyAndCheckNeeded);**
            if Invoice or CopyAndCheckNeeded then
                CopyAndCheckItemCharge(PurchHeader);
            OnCheckAndUpdateOnAfterCopyAndCheckItemCharge(PurchHeader);
Event Code:
  [IntegrationEvent(false, false)]
    local procedure OnBeforeCopyAndCheckItemCharge(PurchHeader: Record "Purchase Header"; var CopyAndCheckNeeded: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
