### ISSUE TITLE
[BUG (?)] Different Fieldtype in the table "Tariff Number" for field "Supplementary Units" in localization BE & CZ

### ISSUE THREAD

**Issue by TimCsr** [microsoft/ALAppExtensions#12382]
Hello,
For a particular customer, we synchronize tables in different environments & tenants. One of the synchronizations is the "Tariff Number" table between the localization BE (Belgium) and CZ (Czech). Now we noticed that the field "Supplementary Units" in BE is a "normal" field and in CZ a Flowfield. So this field cannot be synchronized. 
Can you look into this and solve it? In which localization is this correct? 
![image](https://user-images.githubusercontent.com/50943286/118466390-1af54a80-b703-11eb-9347-567c8d152a7b.png)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
