### ISSUE TITLE
[Extensibility Enhancement] Add Check for Max Field Length - Translation Module

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#12381]
I'm using the translation module and I would like to know what do you think about a check for the Translation table that returns an error if the translation text exceeds the Max. Length of the table field?
https://github.com/microsoft/ALAppExtensions/blob/5c490ab80d8f5c4ac26641604eba79dbe1b1eb47/Modules/System/Translation/src/Translation.Table.al#L33

I could create a PR, which throws an error if you agree that this is the expected behaviour.

**Comment by mazhelez** [comment]
@pri-kise interesting suggestion. Can you elaborate on that?

What are the scenarios you want to cover? What could be a useful reaction to such an error?

**Comment by pri-kise** [comment]
In my opinion the common use case for the translation module is to enable the user to store translations for specific fields that are used as an alternative for Language Specific Documents / Records.
If i look into the baseapp that current has its own translation tables (Item Translation, Payment Method Translation), they are commonly used to transfer the translations as replacement of the default value (Default Language).
Therefore I would like to throw the error early in the process - while storing the translations - instead of resulting in a shortened translated text during runtime.

**Comment by JesperSchulz** [comment]
I see your point! However, I'm not sure if an error maybe isn't too harsh? What if you'd like to store the proper translation, even if it doesn't fit into the field? Would that never be a scenario? Also, what about the system, where users already have stored translations which exceed the field length? How would we handle those once your rule has been implemented? Would we just truncate them?

Maybe this validation could be an optional thing you configure? Maybe it could just be a warning, which informs you that you've added a string which exceeds the field length?

I do see a valid use case here and we would love to see your PR, but you should rethink if an hard stop error is the right thing to implement :-)

Closing this issue and waiting eagerly to see your solution as a PR. Have a lovely weekend!
