### ISSUE TITLE
[Event Request] - PurchPost.Codeunit.al - PostCombineSalesOrderShipment

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#12386]
We like to request the following Event:
Object: PurchPost.Codeunit.al
Where is the event placed:
procedure PostCombineSalesOrderShipment
...
until TempDropShptPostBuffer.Next() = 0;
                    TempDropShptPostBuffer.SetRange("Order No.");
                    OnAfterInsertCombinedSalesShipment(SalesShptHeader);
                until TempDropShptPostBuffer.Next() = 0;
            end;
        OnAfterPostCombineSalesOrderShipment(PurchHeader, TempDropShptPostBuffer);
    end;
Event Code:
  [IntegrationEvent(false, false)]
    local procedure OnAfterPostCombineSalesOrderShipment(var PurchaseHeader: Record "Purchase Header"; var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
