### ISSUE TITLE
[Event Request] Table 50 "Accounting Period" - OnCheckOpenFiscalYearsOnBeforeError

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12383]
Hello. In the table 50 "Accounting Period", in the procedure CheckOpenFiscalYears, I would like to skip the standard code at the verification of NoOfOpenFiscalYears > 2. To do so, I need an event publisher and a IsHandled flag. Like this :

    procedure CheckOpenFiscalYears()
    var
        IsHandled : boolean;
    begin
        AccountingPeriod2.Reset();
        AccountingPeriod2.SetRange("New Fiscal Year", true);
        AccountingPeriod2.SetRange("Fiscally Closed", false);
        NoOfOpenFiscalYears := AccountingPeriod2.Count();
        if AccountingPeriod2.FindFirst then;

        // check last period of previous fiscal year
        AccountingPeriod2.SetRange("New Fiscal Year");
        AccountingPeriod2.SetRange("Fiscally Closed");
        if AccountingPeriod2.Find('<') then
            if not AccountingPeriod2."Fiscally Closed" then
                NoOfOpenFiscalYears := NoOfOpenFiscalYears + 1;

        IsHandled := false;
        OnCheckOpenFiscalYearsOnBeforeError(Rec, IsHandled);
        if not IsHandled then
            if NoOfOpenFiscalYears > 2 then
                Error(Text10801);
    end;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnCheckOpenFiscalYearsOnBeforeError(var AccountingPeriod: Record "Accounting Period"; var IsHandled: Boolean)
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
