### ISSUE TITLE
[Event Request] - PurchPost.Codeunit.al

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#12385]
We like to request the following Event:
Object: PurchPost.Codeunit.al
Where is the event placed:
local procedure PostItemJnlLineCopyProdOrder(PurchLine: Record "Purchase Line"; var ItemJnlLine: Record "Item Journal Line"; QtyToBeReceived: Decimal; QtyToBeInvoiced: Decimal)
    var
        IsHandled: Boolean;
    begin
        OnBeforePostItemJnlLineCopyProdOrder(ItemJnlLine, PurchLine, PurchRcptHeader, QtyToBeReceived, QtyToBeInvoiced, SuppressCommit, IsHandled);
        if IsHandled then
            exit;

        with PurchLine do begin
Event Code:
 [IntegrationEvent(false, false)]
    local procedure OnBeforePostItemJnlLineCopyProdOrder(var ItemJnlLine: Record "Item Journal Line"; PurchLine: Record "Purchase Line"; PurchRcptHeader: Record "Purch. Rcpt. Header"; QtyToBeReceived: Decimal; QtyToBeInvoiced: Decimal; CommitIsSupressed: Boolean; var IsHandled: Boolean);
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
