### ISSUE TITLE
[Event Request] - PurchPost.Codeunit.al - OnPostUpdateOrderLineBeforeLoop

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#12398]
We like to request the following Event:
Object: PurchPost.Codeunit.al
Where is the event placed:
 local procedure PostUpdateOrderLine(PurchHeader: Record "Purchase Header")
    var
        TempPurchLine: Record "Purchase Line" temporary;
        SetDefaultQtyBlank: Boolean;
    begin
        OnBeforePostUpdateOrderLine(PurchHeader, TempPurchLineGlobal, SuppressCommit, PurchSetup);

        ResetTempLines(TempPurchLine);
        with TempPurchLine do begin
            SetRange("Prepayment Line", false);
            SetFilter(Quantity, '<>0');
            if FindSet then
                repeat
                    OnPostUpdateOrderLineBeforeLoop(PurchHeader, TempPurchLine);
                    if PurchHeader.Receive then begin
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnPostUpdateOrderLineBeforeLoop(PurchHeader: Record "Purchase Header"; var TempPurchLine: Record "Purchase Line" temporary);
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
