### ISSUE TITLE
[Event Request] - PurchPost.Codeunit.al - OnSumPurchLines2AfterDivideAmount

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#12393]
We like to request the following Event:
Object: PurchPost.Codeunit.al
Where is the event placed:
local procedure SumPurchLines2(PurchHeader: Record "Purchase Header"; var NewPurchLine: Record "Purchase Line"; var OldPurchLine: Record "Purchase Line"; QtyType: Option General,Invoicing,Shipping; InsertPurchLine: Boolean)
    var
        PurchLine: Record "Purchase Line";
        TempVATAmountLine: Record "VAT Amount Line" temporary;
        TempVATAmountLineRemainder: Record "VAT Amount Line" temporary;
        PurchLineQty: Decimal;
        BiggestLineNo: Integer;
        IsHandled: Boolean;
    begin
        OnBeforeSumPurchLines2(PurchHeader, NewPurchLine, OldPurchLine, QtyType, InsertPurchLine, IsHandled);
        if IsHandled then
            exit;

        TempVATAmountLineRemainder.DeleteAll();
        OldPurchLine.CalcVATAmountLines(QtyType, PurchHeader, OldPurchLine, TempVATAmountLine);
        with PurchHeader do begin
            GetGLSetup();
            GetPurchSetup();
            GetCurrency("Currency Code");
            OldPurchLine.SetRange("Document Type", "Document Type");
            OldPurchLine.SetRange("Document No.", "No.");
            OnSumPurchLines2OnAfterSetFilters(OldPurchLine, PurchHeader);
            RoundingLineInserted := false;
            if OldPurchLine.FindSet() then
                repeat
                    if not RoundingLineInserted then
                        PurchLine := OldPurchLine;
                    case QtyType of
                        QtyType::General:
                            PurchLineQty := PurchLine.Quantity;
                        QtyType::Invoicing:
                            PurchLineQty := PurchLine."Qty. to Invoice";
                        QtyType::Shipping:
                            begin
                                if IsCreditDocType then
                                    PurchLineQty := PurchLine."Return Qty. to Ship"
                                else
                                    PurchLineQty := PurchLine."Qty. to Receive"
                            end;
                    end;
                    DivideAmount(PurchHeader, PurchLine, QtyType, PurchLineQty, TempVATAmountLine, TempVATAmountLineRemainder);
                    **OnSumPurchLines2AfterDivideAmount**(PurchHeader, PurchLine, QtyType, PurchLineQty, TempVATAmountLine, TempVATAmountLineRemainder);
                    PurchLine.Quantity := PurchLineQty;
Event Code:
   [IntegrationEvent(false, false)]
    local procedure OnSumPurchLines2AfterDivideAmount(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; QtyType: Option General,Invoicing,Shipping; PurchLineQty: Decimal; var TempVATAmountLine: Record "VAT Amount Line" temporary; var TempVATAmountLineRemainder: Record "VAT Amount Line" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
