### ISSUE TITLE
[Event Change] Table 81 - OnBeforeLookUpAppliesToDocCust

### ISSUE THREAD

**Issue by RaKuNbg** [Microsoft/ALAppExtensions#1239]
The publisher should contain a "Handled"-Flag and the record should be passed as VAR

![image](https://user-images.githubusercontent.com/46022628/52777539-572d3280-3044-11e9-9a75-2f25ec9b6145.png)

![image](https://user-images.githubusercontent.com/46022628/52777326-cce4ce80-3043-11e9-93fe-9629d0b417aa.png)

Same for publisher
- OnBeforeLookUpAppliesToDocEmpl
- OnBeforeLookUpAppliesToDocVend

**Comment by AJasp** [comment]
Hi,
i have a question about the implementation of the event request - why are the records for the three events are **not** passed as var (see the above request)?
