### ISSUE TITLE
[Event Request] - PurchPost.Codeunit.al - OnPostUpdateOrderLineBeforeInitQtyToInvoice

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#12399]
We like to request the following Event:
Object: PurchPost.Codeunit.al
Where is the event placed:
procedure PostUpdateOrderLine
...
InitOutstanding();

                    SetDefaultQtyBlank := PurchSetup."Default Qty. to Receive" = PurchSetup."Default Qty. to Receive"::Blank;
                    OnPostUpdateOrderLineOnSetDefaultQtyBlank(PurchHeader, TempPurchLine, PurchSetup, SetDefaultQtyBlank);
                    if WhseHandlingRequiredExternal(TempPurchLine) or SetDefaultQtyBlank then begin
                        if "Document Type" = "Document Type"::"Return Order" then begin
                            "Return Qty. to Ship" := 0;
                            "Return Qty. to Ship (Base)" := 0;
                        end else begin
                            "Qty. to Receive" := 0;
                            "Qty. to Receive (Base)" := 0;
                        end;
                        OnPostUpdateOrderLineBeforeInitQtyToInvoice(TempPurchLine, WhseShip, WhseReceive);
                        InitQtyToInvoice;
                    end else begin
                        if "Document Type" = "Document Type"::"Return Order" then
                            InitQtyToShip
                        else
                            InitQtyToReceive2;
                    end;
                    SetDefaultQuantity;
                    OnBeforePostUpdateOrderLineModifyTempLine(TempPurchLine, WhseShip, WhseReceive, SuppressCommit, PurchHeader);
                    ModifyTempLine(TempPurchLine);
                    OnAfterPostUpdateOrderLine(TempPurchLine, WhseShip, WhseReceive, SuppressCommit);
                until Next() = 0;
        end;
    end;

    local procedure UpdateQtyToInvoiceForOrder(PurchHeader: Record "Purchase Header"; var TempPurchLine: Record "Purchase Line" temporary)
    var
Event Code:
 [IntegrationEvent(false, false)]
    local procedure OnPostUpdateOrderLineBeforeInitQtyToInvoice(var TempPurchaseLine: Record "Purchase Line" temporary; WhseShip: Boolean; WhseReceive: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
