### ISSUE TITLE
[Event Request] - PurchPost.Codeunit.al -OnBeforeUpdateItemChargeAssgnt

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#12391]
We like to request the following Event:
Object: PurchPost.Codeunit.al
Where is the event placed:
local procedure FinalizePosting(var PurchHeader: Record "Purchase Header"; var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer" temporary; EverythingInvoiced: Boolean)
    var
        TempPurchLine: Record "Purchase Line" temporary;
        GenJnlPostPreview: Codeunit "Gen. Jnl.-Post Preview";
        ArchiveManagement: Codeunit ArchiveManagement;
        IsHandled: Boolean;
    begin
        OnBeforeFinalizePosting(PurchHeader, TempPurchLineGlobal, EverythingInvoiced, SuppressCommit, GenJnlPostLine);

        with PurchHeader do begin
            if ("Document Type" in ["Document Type"::Order, "Document Type"::"Return Order"]) and
               (not EverythingInvoiced)
            then begin
                Modify;
                InsertTrackingSpecification(PurchHeader);
                PostUpdateOrderLine(PurchHeader);
                UpdateAssocOrder(TempDropShptPostBuffer);
                UpdateWhseDocuments;
                WhsePurchRelease.Release(PurchHeader);

                **OnBeforeUpdateItemChargeAssgnt**(PurchHeader, IsHandled);
                if not IsHandled then
                    UpdateItemChargeAssgnt();
                OnFinalizePostingOnAfterUpdateItemChargeAssgnt(PurchHeader);
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateItemChargeAssgnt(var PurchHeader: Record "Purchase Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
