### ISSUE TITLE
[Event Change Request] - PurchPost.Codeunit.al - OnAfterCheckTrackingAndWarehouseForShip

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#12416]
We like to request the following event change:
Object: PurchPost.Codeunit.al
ToDo: add TempPurchLine
Where is the event placed:
if Ship then begin
                CheckTrackingSpecification(PurchHeader, TempPurchLine);
                if not (WhseShip or WhseReceive or InvtPickPutaway) then
                    CheckWarehouse(TempPurchLine);
            end;
            OnAfterCheckTrackingAndWarehouseForShip(PurchHeader, Ship, SuppressCommit, TempPurchLine);
            exit(Ship);
        end;
    end;
Event Code:
[IntegrationEvent(false, false)]
    local procedure OnAfterCheckTrackingAndWarehouseForShip(var PurchaseHeader: Record "Purchase Header"; var Ship: Boolean; CommitIsSupressed: Boolean; var TempPurchaseLine: Record "Purchase Line" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
