### ISSUE TITLE
[Event Change Request] - PurchPost.Codeunit.al - OnBeforePurchInvLineInsert

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#12422]
We like to request the following event change:
Object: PurchPost.Codeunit.al
ToDo: add xPurchaseLine
Where is the event placed:
end else
                            if PurchRcptLine.Get("Receipt No.", "Receipt Line No.") then begin
                                PurchInvLine."Order No." := PurchRcptLine."Order No.";
                                PurchInvLine."Order Line No." := PurchRcptLine."Order Line No.";
                            end;
                        OnBeforePurchInvLineInsert(PurchInvLine, PurchInvHeader, PurchLine, xPurchLine, SuppressCommit);
                        if not IsNullGuid(PurchLine.SystemId) then begin
Event Code:
 [IntegrationEvent(false, false)]
    local procedure OnBeforePurchInvLineInsert(var PurchInvLine: Record "Purch. Inv. Line"; var PurchInvHeader: Record "Purch. Inv. Header"; var PurchaseLine: Record "Purchase Line"; var xPurchaseLine: Record "Purchase Line"; CommitIsSupressed: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
