### ISSUE TITLE
[request-for-external] Page 810 Web Services: Add Reload as an global function

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#12434]
We have added an button on the Web services to add our own Webservices. After running the function we have to reload the page to show the new web services. Because there is no Refresh function on the page we have to build this one ourselves. Could you Add a global **Reload** function to the page?

At the moment we have to declare WebServiceManagement: Codeunit "Web Service Management". So why not create the following function:

```
procedure Reload()
begin
    WebServiceManagement.LoadRecords(Rec);
end;
```

This way you can also use this in the **OnOpenPage** function and in **action(Reload)** and we can use this in our extension.

An extra advantage is, may the function to reload ever change, we do not need to make any changes.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
