### ISSUE TITLE
[Event Change Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnPostUnapplyAfterInsertTempVatEntry

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#12433]
Hi, would it be possible to change NextVATEntryNo in the OnPostUnapplyAfterInsertTempVatEntry Event as mentioned in #11678 to var, so that it is possible to increase it?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
