### ISSUE TITLE
add Fuction in Codeunit 1266 "Crypthography Management"

### ISSUE THREAD

**Issue by MiguelMercadoActual** [microsoft/ALAppExtensions#12441]
Hi, in the codeunit "Cryptography Management" you have the following methods:
 
• GenerateHash
• GenerateHashAsBase64String
• GenerateBase64KeyedHashAsBase64String
 
But we are missing the method: **GenerateBase64KeyedHash** that receives the key in base64 but that the hash does not convert it to base64.

Could it be possible to integrate this function with the new versions of Business central? 

It is necessary to integrate with Amazon and be able to calculate the signature, as indicated in its documentation: https://docs.aws.amazon.com/general/latest/gr/sigv4-calculate-signature.html

**Comment by MiguelMercadoActual** [comment]
Hi Jesper,

I have already created the pull request, this is the pull: https://github.com/microsoft/ALAppExtensions/pull/12578

Thanks for your help!

**Comment by JesperSchulz** [comment]
Excellent! We'll process as quickly as we can :-) Closing this issue, as further progress will be tracked in your PR.
