### ISSUE TITLE
MakeRecurringsTexts global and multiusable

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#12457]
Please make local Procedure MakeRecurringsTexts global and multiusable.
The identical procedure is coded in several TestReports and PostBatch Codeunits. We need this procedure as well in our apps.

It would be very convenient, to have a multiusable global procedure e.g. in table "Accounting Period" as follows:

procedure MakeRecurringsTexts (No: Code[20]; PostingDate: Date; RecurringMethod: Integer; var DocumentNo: Code[20]; var Description: Text[100]);
Begin
            if (PostingDate <> 0D) and (No <> '') and (RecurringMethod <> 0) then begin
                Day := Date2DMY(PostingDate, 1);
                Week := Date2DWY(PostingDate, 2);
                Month := Date2DMY(PostingDate, 2);
                MonthText := Format(PostingDate, 0, Text023Txt);
                AccountingPeriod.SetRange("Starting Date", 0D, PostingDate);
                if not AccountingPeriod.FindLast() then
                    AccountingPeriod.Name := '';
                DocumentNo :=
                  DelChr(
                    PadStr(
                      StrSubstNo(DocumentNo, Day, Week, Month, MonthText, AccountingPeriod.Name),
                      MaxStrLen(DocumentNo)),
                    '>');
                Description :=
                  DelChr(
                    PadStr(
                      StrSubstNo(Description, Day, Week, Month, MonthText, AccountingPeriod.Name),
                      MaxStrLen(Description)),
                    '>');
            end;
End;

This could be used as well in the following Standard BC objects:
report 317 "Vendor Pre-Payment Journal"
report 2 "General Journal - Test"
report 6250 "Auto Posting Errors"
codeunit 213 "Res. Jnl.-Post Batch"
report 1102 "Resource Journal - Test"
codeunit 5633 "FA Jnl.-Post Batch"
report 702 "Inventory Posting - Test"
codeunit 23 "Item Jnl.-Post Batch"
codeunit 1013 "Job Jnl.-Post Batch"
report 1005 "Job Journal - Test"
codeunit 13 "Gen. Jnl.-Post Batch"
codeunit 333 "Req. Wksh.-Make Order"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
