### ISSUE TITLE
[Event Request] Codeunit 12182 "Datifattura Export" - procedure AddVendAddress - OnBeforeAddVendAddress; procedure AddInvoiceAmountsData - OnAddInvoiceAmountsDataOnAfterExportDatiIVA

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#12456]
Could You please, add the following events to the Codeunit 12182 "Datifattura Export"? 

The required events must be placed in the Italian Localization for Business Central

**1st event:** 
placed in the local procedure AddVendAddress(Vendor: Record Vendor; var AltriDatiIdentificativiXmlNode: DotNet XmlNode)

Publisher Event: **OnBeforeAddVendAddress**

Reason: To implement changes required by the customer.

Where is the event placed (see image attached)?:

![image](https://user-images.githubusercontent.com/73465025/118800574-5a0cd280-b8a0-11eb-845e-37526d58362f.png)

At the begining of the procedure add the call to the event and exit taking into account the IsHandled variable;

    local procedure AddVendAddress(Vendor: Record Vendor; var AltriDatiIdentificativiXmlNode: DotNet XmlNode)
    var
        AddressXmlNode: DotNet XmlNode;
        XmlNode: DotNet XmlNode;
        IsResident: Boolean;
    begin

        >>>>>>>>>>>>>>>>>>>>>>>
	    OnBeforeAddVendAddress(Vendor, AltriDatiIdentificativiXmlNode, ErrorMessage, IsHandled);
	    if IsHandled then
		   exit;
	    <<<<<<<<<<<<<<<<<<<<<<<

        IsResident := Vendor.Resident = Vendor.Resident::Resident;
        if IsResident then
            XMLDOMManagement.AddElement(AltriDatiIdentificativiXmlNode, 'Sede', '', '', AddressXmlNode)
        else
            XMLDOMManagement.AddElement(AltriDatiIdentificativiXmlNode, 'StabileOrganizzazione', '', '', AddressXmlNode);

        XMLDOMManagement.AddElement(AddressXmlNode, 'Indirizzo', Vendor.Address, '', XmlNode);
        if (not IsResident) or (Vendor."Post Code" <> '') then begin
            ErrorMessage.LogIfEmpty(Vendor, Vendor.FieldNo("Post Code"), ErrorMessage."Message Type"::Error);
            if Vendor."Country/Region Code" <> 'IT' then
                XMLDOMManagement.AddElement(AddressXmlNode, 'CAP', '00000', '', XmlNode)
            else
                XMLDOMManagement.AddElement(AddressXmlNode, 'CAP', Vendor."Post Code", '', XmlNode);
        end;

**Event Code:**
[IntegrationEvent(true, false)]
local procedure OnBeforeAddVendAddress_Cu12182(var Vendor: Record Vendor; var AltriDatiIdentificativiXmlNode: DotNet XmlNode; var ErrorMessage: Record "Error Message"; var IsHandled)
begin
end;

**2nd event:**

placed in the local procedure AddInvoiceAmountsData(VATReportLine: Record "VAT Report Line"; var InvoiceXmlNode: DotNet XmlNode)

Publisher Event: **OnAddInvoiceAmountsDataOnAfterExportDatiIVA**

Reason: To implement changes required by the customer.

Where is the event placed (see image attached)?:

![image](https://user-images.githubusercontent.com/73465025/118800536-50836a80-b8a0-11eb-83a5-e401000e79e8.png)

After the line 604 add the call to the event:

    local procedure AddInvoiceAmountsData(VATReportLine: Record "VAT Report Line"; var InvoiceXmlNode: DotNet XmlNode)
    var
        VATPostingSetup: Record "VAT Posting Setup";
        DatiRiepilogoXmlNode: DotNet XmlNode;
        DatiIVAXmlNode: DotNet XmlNode;
        XmlNode: DotNet XmlNode;
        DocumentType: Text;
    begin
        // 2.2.3.2 DatiRiepilogo node
        XMLDOMManagement.AddElement(InvoiceXmlNode, 'DatiRiepilogo', '', '', DatiRiepilogoXmlNode);

        DocumentType := GetDocumentType(VATReportLine);

        if (DocumentType = Format(DocumentTypes::TD07)) or (DocumentType = Format(DocumentTypes::TD08)) then
            XMLDOMManagement.AddElement(
              DatiRiepilogoXmlNode, 'ImponibileImporto', FormatAmount(Abs(VATReportLine."Amount Incl. VAT")), '', XmlNode)
        else
            XMLDOMManagement.AddElement(DatiRiepilogoXmlNode, 'ImponibileImporto', FormatAmount(Abs(VATReportLine.Base)), '', XmlNode);

        if VATPostingSetup.Get(VATReportLine."VAT Bus. Posting Group", VATReportLine."VAT Prod. Posting Group") then begin
            // DatiIVA
            XMLDOMManagement.AddElement(DatiRiepilogoXmlNode, 'DatiIVA', '', '', DatiIVAXmlNode);
            XMLDOMManagement.AddElement(DatiIVAXmlNode, 'Imposta', FormatAmount(Abs(VATReportLine.Amount)), '', XmlNode);
            XMLDOMManagement.AddElement(DatiIVAXmlNode, 'Aliquota', FormatAmount(VATPostingSetup."VAT %"), '', XmlNode);

            if (VATReportLine.Amount = 0) or
               (VATPostingSetup."VAT Calculation Type" = VATPostingSetup."VAT Calculation Type"::"Reverse Charge VAT")
            then
                XMLDOMManagement.AddElement(DatiRiepilogoXmlNode, 'Natura', VATReportLine."VAT Transaction Nature", '', XmlNode);

		>>>>>>>>>>>>>>>>>>>>>>>
		OnAddInvoiceAmountsDataOnAfterExportDatiIVA(DatiRiepilogoXmlNode, InvoiceXmlNode, XmlNode, VATReportLine, VATPostingSetup);
		<<<<<<<<<<<<<<<<<<<<<<<                
        end;

        AddEsigibilitaIVATag(DatiRiepilogoXmlNode, XmlNode, VATReportLine);
    end;

**Event Code:**
[IntegrationEvent(true, false)]
local procedure OnAddInvoiceAmountsDataOnAfterExportDatiIVA(var DatiRiepilogoXmlNode: DotNet XmlNode; var InvoiceXmlNode: DotNet XmlNode; var XmlNode: DotNet XmlNode; VATReportLine: Record "VAT Report Line"; VATPostingSetup: Record "VAT Posting Setup")
begin
end;

Thanks in advance.

**Comment by Stepanenko-Vadim** [comment]
We cannot expose dotnet variables in parameters of events. 
Will these events work for you if the dotnet variable is excluded in params? If yes, then we can implement the events without the dotnet params, if no then we will have to decline the request.

**Comment by IgnacioPeq** [comment]
Hi Vadim,
we need these variables to be exposed, 
the question then is:

Could you convert the codeunit to use native xml functions in the same way that the standard do with the SII module for Spain database connection with the legal tax agency?

The development is not needed for SaaS, for this client is OnPrem, 

The other way is to protect the events with [Scope:OnPrem]

Thanks in advance for your answer

**Comment by Stepanenko-Vadim** [comment]
Sorry, but after some attempts to refactor the codeunit it would appear to be too big of a scope just for an event request so we cannot do that and since we still cannot expose dotnet variables in events so as I said stated previously we will have to deny this request.

**Comment by Stepanenko-Vadim** [comment]
I am not aware of anything new regarding this area.
Exposing dotnet variables still doesn't work in SaaS, so such event is still not possible.
