### ISSUE TITLE
Page "Item Tracing" (ID 6520) Trigger OnOpenPage possibility to overwrite TraceMethod and ShowComponents default value

### ISSUE THREAD

**Issue by CarstenHeu** [microsoft/ALAppExtensions#12464]
We want to open up the "Item Tracing" page completly filtered and with own preset options. This is quite possible using the InitFilters function. But in the OnOpenPage Trigger the new values set up in the event OnAfterInitFilters for TraceMethod and ShowComponents are again overwritten by the default values of the page!
So best way would be to not set the values for TraceMethod and ShowComponents in OnOpen Page again, if the InitFilters procedure was already called or to give a possibility (new event publisher OnAfterOpenPage(var TraceMethod: Option Forward,Backward; var ShowComponents: Option No,"Item-tracked only",All)) in the OnOpenPage Trigger to overwrite the default Values again.
Kind regards,
Carsten Heu.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
