### ISSUE TITLE
[Function Overload] COD 260 "Document-Mailing" : overload for SourceReference to SourceTables / SourceIDs

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#12461]
@JesperSchulz 

The BC 18.1 base app contains new EmailFile procedures including SourceReference, to add a Source Document link to the email item (for mails to allow the 'Show Source' to work properly). The current SourceReference supports multiple source documents, since the recordref is looped.

```
procedure EmailFile(AttachmentStream: Instream; AttachmentName: Text; HtmlBodyFilePath: Text; EmailSubject: Text; ToEmailAddress: Text; HideDialog: Boolean; EmailScenario: Enum "Email Scenario"; SourceReference: RecordRef): Boolean
    var
        TempEmailItem: Record "Email Item" temporary;
    begin
        repeat
            TempEmailItem.AddSourceDocument(SourceReference.Number(), SourceReference.Field(SourceReference.SystemIdNo()).Value());
        until SourceReference.Next() = 0;
```

However, we'd like to provide the option to add multiple source documents, originating from **different** tables. With recordref, I don't see how this can be achieved. However, the **SourceTables / SourceIDs** approach would provide a solution.

```
procedure EmailFile(AttachmentStream: Instream; AttachmentName: Text; HtmlBodyFilePath: Text; EmailSubject: Text; ToEmailAddress: Text; HideDialog: Boolean; EmailScenario: Enum "Email Scenario"; SourceTables: List of [Integer]; SourceIDs: List of [Guid]): Boolean
    var
        TempEmailItem: Record "Email Item" temporary;
    begin
        TempEmailItem.SetSourceDocuments(SourceTables, SourceIDs); // Already supported in standard BC

```

Can you provide EmailFile overloads for all procedures using SourceReference in codeunit 260 "Document-Mailing" and provide support for passing multi-table source documents via new SourceTables / SourceIDs arguments?

**Comment by JesperSchulz** [comment]
Would you consider creating a pull request with the required API (more details on [aka.ms/ChangeALModule](aka.ms/ChangeALModule))?

**Comment by JesperSchulz** [comment]
Sounds like something we could look into :-)

**Comment by aholstrup** [comment]
@fvet Thank you for your input. We're currently in the process of extending our use of source documents, which will include the ability to add multiple source documents from different tables. Stay tuned :)
