### ISSUE TITLE
Event in codeunit 233

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/ALAppExtensions#12474]
I need in codeunit 233 the event:

if not ConfirmManagement.GetResponseOrDefault(Text000, true) then
   exit;

>>>>>>>>>NEW EVENT>>>>>>>>
OnBeforePostJournalBatch(GenJnlBatch);
<<<<<<<<<<<<<<<<<

Find('-');
repeat

[IntegrationEvent(false, false)]
    local procedure OnBeforePostJournalBatch(var GenJournalBatch: Record "Gen. Journal Batch")
    begin
    end;

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
