### ISSUE TITLE
[Enum Request] Intercompany Line Tables field Document Type

### ISSUE THREAD

**Issue by MGerits** [microsoft/ALAppExtensions#12475]
Could you change following table fields to extensible Enum? The document type field in the related header tables is already changed to enum. 

table 427 "IC Outbox Sales Line"                     field 1  "Document Type" 
table 429 "IC Outbox Purchase Line"              field 1  "Document Type"
table 431 "Handled IC Outbox Sales Line"      field 1  "Document Type"
table 433 "Handled IC Outbox Purch. Line"    field 1  "Document Type"
table 435 "IC Inbox Sales Line"                       field 1  "Document Type"
table 437 "IC Inbox Purchase Line"                 field 1  "Document Type"
table 439 "Handled IC Inbox Sales Line"         field 1  "Document Type"
table 441 "Handled IC Inbox Purch. Line"       field 1  "Document Type"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
