### ISSUE TITLE
[Request-For-External] Page 1327 "Adjust Inventory" variables

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#12488]
please make the global variables accessable.

page 1327 "Adjust Inventory"

```
        Item: Record Item;
        TempItemJournalLine: Record "Item Journal Line" temporary;
        LocationCount: Integer;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
