### ISSUE TITLE
[Event Request] Codeunit 414 Release Sales Document - Function Code

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12496]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 414 Release Sales Document - Function Code

            if PrepaymentMgt.TestSalesPrepayment(SalesHeader) and ("Document Type" = "Document Type"::Order) then begin
                Status := Status::"Pending Prepayment";
                Modify(true);
                OnAfterReleaseSalesDoc(SalesHeader, PreviewMode, LinesWereModified);
                exit;
            end;
            // DINNL <<
            DINOnRelease(SalesHeader, DINCalledFromManualRelease);
            // DINNL >>
            Status := Status::Released;

    local procedure DINOnRelease(var SalesHeader: Record "Sales Header"; DINCalledFromManualRelease: Boolean)

**Comment by Stepanenko-Vadim** [comment]
What is the DINCalledFromManualRelease parameter that you want the event to expose?

**Comment by Stepanenko-Vadim** [comment]
Also there are two event in 5 lines of code before: OnBeforeModifySalesDoc and OnAfterReleaseSalesDoc, what is the usecase where you can't use those instead?
