### ISSUE TITLE
[Event Request] Table 38 (Purchase Header) on Buy-from Vendor No. and Pay-to Vendor No.

### ISSUE THREAD

**Issue by PunkyGP** [microsoft/ALAppExtensions#12493]
Dear Team,

is it possible to add 2 new Events to the Purchase Header please? Similar events are present in de Sales Header but missing in the Purchase Header.

    field(2; "Buy-from Vendor No."; Code[20])
        {
            Caption = 'Buy-from Vendor No.';
            TableRelation = Vendor;

            trigger OnValidate()
            var
                StandardCodesMgt: Codeunit "Standard Codes Mgt.";
            begin
                if "No." = '' then
                    InitRecord();
                TestStatusOpen();
                if ("Buy-from Vendor No." <> xRec."Buy-from Vendor No.") and
                   (xRec."Buy-from Vendor No." <> '')
                then begin
                    CheckDropShipmentLineExists();
                    if GetHideValidationDialog or not GuiAllowed then
                        Confirmed := true
                    else
                        Confirmed := Confirm(ConfirmChangeQst, false, BuyFromVendorTxt);
                    if Confirmed then begin
                        if InitFromVendor("Buy-from Vendor No.", FieldCaption("Buy-from Vendor No.")) then
                            exit;

                        CheckReceiptInfo(PurchLine, false);
                        CheckPrepmtInfo(PurchLine);
                        CheckReturnInfo(PurchLine, false);

                        PurchLine.Reset();
                    end else begin
                        Rec := xRec;
                        exit;
                    end;
                end;

                GetVend("Buy-from Vendor No.");
                //Start New Event
                IsHandled := false;
                OnValidateBuyFromVendorNoOnBeforeCheckBlockedVendOnDocs(Rec, Vend, IsHandled);
                if not IsHandled then                
                //Stop New Event
                    CheckBlockedVendOnDocs(Vend);
                if not ApplicationAreaMgmt.IsSalesTaxEnabled then
                    Vend.TestField("Gen. Bus. Posting Group");
                OnAfterCheckBuyFromVendor(Rec, xRec, Vend);

    field(4; "Pay-to Vendor No."; Code[20])
        {
            Caption = 'Pay-to Vendor No.';
            NotBlank = true;
            TableRelation = Vendor;

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                IsHandled := false;
                OnBeforeValidatePayToVendorNo(Rec, xRec, Confirmed, IsHandled);
                if IsHandled then
                    exit;

                TestStatusOpen();
                if (xRec."Pay-to Vendor No." <> "Pay-to Vendor No.") and
                   (xRec."Pay-to Vendor No." <> '')
                then begin
                    if GetHideValidationDialog or not GuiAllowed then
                        Confirmed := true
                    else
                        Confirmed := Confirm(ConfirmChangeQst, false, PayToVendorTxt);
                    if Confirmed then begin
                        PurchLine.SetRange("Document Type", "Document Type");
                        PurchLine.SetRange("Document No.", "No.");

                        CheckReceiptInfo(PurchLine, true);
                        CheckPrepmtInfo(PurchLine);
                        CheckReturnInfo(PurchLine, true);

                        PurchLine.Reset();
                    end else
                        "Pay-to Vendor No." := xRec."Pay-to Vendor No.";
                end;

                OnValidatePayToVendorNoOnBeforeGetPayToVend(Rec);
                GetVend("Pay-to Vendor No.");
                //Start New Event
                IsHandled := false;
                OnValidatePayToVendorNoOnBeforeCheckBlockedCustOnDocs(Rec, Vend, IsHandled);
                if not IsHandled then                
                //Stop New Event
                    CheckBlockedVendOnDocs(Vend);
                Vend.TestField("Vendor Posting Group");

    [IntegrationEvent(false, false)]
    local procedure OnValidateBuyFromVendorNoOnBeforeCheckBlockedVendOnDocs(var PurchaseHeader: Record "Purchase Header"; var Vend: Record Vendor; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnValidatePayToVendorNoOnBeforeCheckBlockedVendOnDocs(var PurchaseHeader: Record "Purchase Header"; var Vend: Record Vendor; var IsHandled: Boolean)
    begin
    end;

Thanks in advance,
Gunter

**Comment by Stepanenko-Vadim** [comment]
There is a **OnBeforeCheckBlockedVendOnDocs** event in the **CheckBlockedVendOnDocs** that has same params and can be used to stop the check. Is there a reason you cannot use that instead?

**Comment by PunkyGP** [comment]
Hi, 

this Event has indeed the same params but I need the Vendor record by Var.
And there is current no event for.

I need to update some variables on the vendor record only in the creation of the Header.

Another alternative is to create on "OnAfterGetVend" event in function "GetVend" with the parm Vend by Var.

**Comment by Stepanenko-Vadim** [comment]
We will add 'var' to the event mentioned above so that you can change the vendor record then.

**Comment by PunkyGP** [comment]
Yes, this will be great. Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
