### ISSUE TITLE
[Event Request] Codeunit 415 Release Purchase Document - Function Code

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12497]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 415 Release Purchase Document - Function Code

            if PrepaymentMgt.TestPurchasePrepayment(PurchaseHeader) and ("Document Type" = "Document Type"::Order) then begin
                Status := Status::"Pending Prepayment";
                Modify(true);
                OnAfterReleasePurchaseDoc(PurchaseHeader, PreviewMode, LinesWereModified);
                exit;
            end;
            // DINNL <<
            DINOnRelease(PurchaseHeader);
            // DINNL >>
            Status := Status::Released;

    local procedure DINOnRelease(var PurchHeader: Record "Purchase Header")

**Comment by Stepanenko-Vadim** [comment]
Please use **OnBeforeModifyPurchaseDoc** and **OnAfterReleasePurchaseDoc** which are already available. If not possible, you can always open a new issue and clarify the use case where you can't use those and can only use this one
