### ISSUE TITLE
Item OnAfterDelete event fires during manufacturing transactions

### ISSUE THREAD

**Issue by jason-chance** [Microsoft/ALAppExtensions#1249]
I have an extension that hooks into the OnAfterDelete event of the Item table.  
![image](https://user-images.githubusercontent.com/47641108/52806989-58685a80-3058-11e9-94f0-82c8f58fa0c9.png)

When I post a production journal or finish a production order the OnAfterDelete event of the Item is triggered.  Why on earth???  Here's an example from posting a production journal.  
![image](https://user-images.githubusercontent.com/47641108/52807074-8f3e7080-3058-11e9-8266-97ea7fc6759f.png)

I know there is new Item event: OnAfterDeleteRelatedData that I can probably use in my extension, but why does the Item OnAfterDelete event fire during a transaction?  How is that not a bug?

**Comment by AlexanderYakunin** [comment]
OnAfterDelete is system event and always appear after deleting of record in table.

**Comment by jason-chance** [comment]
Jesper, thanks for the reply.  I understand how the OnAfterDelete event works.  My issue is that this event is triggered while posting a production journal or when finishing a production order.  If I'm posting a production journal, I'm not deleting any items, so why does this event fire?  This seems like a bug.

**Comment by JesperSchulz** [comment]
The first reply wasn't from me :-) But this one is. It's hard for me to debug the entire execution stack of your function call, but I'm pretty sure that if you single-step your way through the code with a debugger, you will find that somewhere an item is deleted and the event is triggered - **remember that it could be a temporary item!** Try to attach the debugger and check which item is deleted and try to verify if it is temporary. And if this is messing with your code, remember to add the following, as we have in many of our event subscribers:
IF Rec.ISTEMPORARY THEN
  EXIT;
