### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - Function InitTransValueEntry

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12490]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 22 Item Jnl.-Post Line - Function InitTransValueEntry

    local procedure InitTransValueEntry(var ValueEntry: Record "Value Entry"; ItemLedgEntry: Record "Item Ledger Entry")
    var
        AdjCostInvoicedLCY: Decimal;
        AdjCostInvoicedACY: Decimal;
        DiscountAmount: Decimal;
        IsHandled: Boolean;
    begin
        InitValueEntry(ValueEntry, ItemLedgEntry);
	// DINNL <<
	DINOnInitTransValueEntryOnAfterInitValueEntry(ValueEntry, ItemLedgEntry);
	// DINNL >>
        ValueEntry."Valued Quantity" := ItemLedgEntry.Quantity;
        ValueEntry."Invoiced Quantity" := ValueEntry."Valued Quantity";
        ValueEntry."Location Code" := ItemLedgEntry."Location Code";
        ValueEntry."Valuation Date" := GlobalValueEntry."Valuation Date";

local procedure DINOnInitTransValueEntryOnAfterInitValueEntry(var ValueEntry: Record "Value Entry"; ItemLedgEntry: Record "Item Ledger Entry")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
