### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - Function InsertTempSplitItemJnlLine

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12491]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 22 Item Jnl.-Post Line - Function InsertTempSplitItemJnlLine

    local procedure InsertTempSplitItemJnlLine(ItemJnlLine2: Record "Item Journal Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeInsertTempSplitItemJnlLine(ItemJnlLine2, IsServUndoConsumption, PostponeReservationHandling, TempSplitItemJnlLine, IsHandled);
        if IsHandled then
            exit;

        TempSplitItemJnlLine := ItemJnlLine2;
        TempSplitItemJnlLine.Insert();
        // DINNL <<
        DINOnSetupSplitJnlLineItemAlwaysOnInventory(TempSplitItemJnlLine, ItemJnlLine2);
        // DINNL >>
    end;

    local procedure DINOnSetupSplitJnlLineItemAlwaysOnInventory(var TempSplitItemJnlLine: Record "Item Journal Line" temporary; var ItemJnlLine2: Record "Item Journal Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
