### ISSUE TITLE
[Request-For-External] Codeunit 5150 "Integration Management" - AddToIntegrationPageList

### ISSUE THREAD

**Issue by percova** [microsoft/ALAppExtensions#12494]
Hi, could you please change the local **AddToIntegrationPageList** procedure of codeunit 5150 (**Integration Management**) to a global one?
```AL
local procedure AddToIntegrationPageList(PageId: Integer; TableId: Integer; var TempNameValueBuffer: Record "Name/Value Buffer" temporary; var NextId: Integer)
    begin
        with TempNameValueBuffer do begin
            Init;
            ID := NextId;
            NextId := NextId + 1;
            Name := Format(PageId);
            Value := Format(TableId);
            Insert;
        end;
    end;
```
Thanks!

**Comment by AlexanderYakunin** [comment]
This codeunit was obsoleted. here is the message

    ObsoleteReason = 'Integration Management will be removed. Refactor the code to use systemID and other system fields such as systemLastModifiedDateTime.';
    ObsoleteState = Pending;
    ObsoleteTag = '17.0';
