### ISSUE TITLE
[Enum Request] Warehouse Tables and codeunit procedure variables

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#12507]
Hi team,
Could you change following table fields to extensible Enum?

Table 7309 "Warehouse Journal Template" field Type
Table 7310 "Warehouse Journal Batch" field "Template Type"
Table 7324 "Whse. Put-away Request" field "Document Type"
Table 7325 "Whse. Pick Request" field "Document Type"

Could you change following codeunit procedures variables to extensible Enum?

Codeunit 5775 "Whse. Management" procedure GetSourceDocument variable SourceDocument
Codeunit 7302 "WMS Management" procedure ShowWhseDocLine variable WhseDocType

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
