### ISSUE TITLE
[Enum Request] tables Accounting Period field, Inventory Setup

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#12509]
Hi team,
Could you change following table fields to extensible Enum?

Table Accounting Period field "Average Cost Calc. Type"
Table Inventory Setup field "Average Cost Calc. Type"

That would help a lot with our custom options.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
