### ISSUE TITLE
[Additional Parameter Request] Table 81 Gen. Journal Line - OnBeforeCheckIfPostingDateIsEarlier

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#12519]
Hello Team,

In table 81 we need possibility to have additional checks in the end of procedure `CheckIfPostingDateIsEarlier`. Publisher `OnBeforeCheckIfPostingDateIsEarlier` would suit us if you could add variable `CustLedgEntry: Record "Cust. Ledger Entry"`. If you could add this feature, it would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/119377896-490bf900-bcc6-11eb-927f-ec94d6092f03.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckIfPostingDateIsEarlier(CustLedgEntry: Record "Cust. Ledger Entry"; GenJournalLine: Record "Gen. Journal Line"; ApplyPostingDate: Date; ApplyDocType: Option " ",Payment,Invoice,"Credit Memo","Finance Charge Memo",Reminder,Refund; ApplyDocNo: Code[20]; var IsHandled: Boolean; RecordVariant: Variant)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
