### ISSUE TITLE
[Event Request] Codeunit 7307 Whse.-Activity-Register - OnRegisterWhseItemTrkgLineOnAfterSetDueDate

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#12515]
Hello Team,

In Codeunit 7307 we need possibility to have our additional checks and/or avoid using standard code. Having event in procedure `RegisterWhseItemTrkgLine` would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/119368239-71dac100-bcbb-11eb-941e-5cea2ad75b8b.png)

    [IntegrationEvent(false, false)]
    local procedure OnRegisterWhseItemTrkgLineOnAfterSetDueDate(WhseActivLine: Record "Warehouse Activity Line"; var DueDate: Date)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
