### ISSUE TITLE
[Enum Request] table RM Matrix Management field "Task Status Filter"

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#12511]
Hi team,

Could you change table RM Matrix Management "Task Status Filter" to extensible Enum? That would help a lot with our custom options.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
