### ISSUE TITLE
[Event Request] Codeunit 13 OnBeforeCommit

### ISSUE THREAD

**Issue by Kowa63** [Microsoft/ALAppExtensions#1251]
Codeunit 13 Gen. Jnl.-Post Batch in Procedure ProcessLines 
OnBeforeCommit(GLRegNo)

![grafik](https://user-images.githubusercontent.com/16236672/52842593-d469ad80-30ff-11e9-87df-0bafe57714f7.png)
![grafik](https://user-images.githubusercontent.com/16236672/52845718-10a10c00-3108-11e9-8fd8-48a4e3d9dd29.png)

**Comment by Rama-M** [comment]
Can GlobalVarAccess is set to Yes on this as well ?  So that potentially the event subscriber can access valuables from codeunit 13 at the same time.
