### ISSUE TITLE
[Event Request] Table 38 - "PurhaseHeader" OnValidateLocationCodeBeforeTestStatusOpen

### ISSUE THREAD

**Issue by iyiannak** [microsoft/ALAppExtensions#12514]
Could you please add an integration event OnValidate of "Location Code" field of table 38, as per below sample of code? 

field(28; "Location Code"; Code[10])
        {
            Caption = 'Location Code';
            TableRelation = Location WHERE("Use As In-Transit" = CONST(false));

            trigger OnValidate()
            begin
               **_**OnValidateLocationCodeBeforeTestStatusOpen(Rec, IsHandled);
               if IsHandled then
                    exit;**_**

                TestStatusOpen();
                if ("Location Code" <> xRec."Location Code") and
                   (xRec."Buy-from Vendor No." = "Buy-from Vendor No.")
                then
                    MessageIfPurchLinesExist(FieldCaption("Location Code"));

                UpdateShipToAddress();
                UpdateInboundWhseHandlingTime;
            end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
