### ISSUE TITLE
[Additional Parameter Request] Codeunit 5760 Whse.-Post Receipt - OnAfterCode

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#12516]
Hello Team,

In codeunit 5760 we need possibility to have additional checks in the end of procedure `Code`. Publisher `OnAfterCode` would suit us if you could add variable `WhseRcptLine: Record "Warehouse Receipt Line"`. If you could add this feature, it would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/119372363-e57ecd00-bcbf-11eb-90a9-f2c74f9e925b.png)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCode(var WarehouseReceiptHeader: Record "Warehouse Receipt Header"; WhseRcptLine: Record "Warehouse Receipt Line")
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
