### ISSUE TITLE
[Additional Parameter Request] Table 81 Gen. Journal Line - OnAfterLookUpAppliesToDocVend

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#12517]
Hello Team,

In table 81 we need possibility to have additional checks in the end of procedure `LookUpAppliesToDocVend`. Publisher `OnAfterLookUpAppliesToDocVend` would suit us if you could add variables `CustLedgEntry: Record "Cust. Ledger Entry"` and `ApplyVendEntries: Page "Apply Vendor Entries"`. If you could add this feature, it would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/119377459-d1d66500-bcc5-11eb-8aa0-86cb285d7138.png)

    [IntegrationEvent(false, false)]
    local procedure OnAfterLookUpAppliesToDocVend(var GenJournalLine: Record "Gen. Journal Line"; CustLedgEntry: Record "Cust. Ledger Entry"; VendLedgEntry: Record "Vendor Ledger Entry"; ApplyVendEntries: Page "Apply Vendor Entries")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
