### ISSUE TITLE
[Event Request] Table 81 Gen. Journal Line - OnBeforeCheckCreditLimit

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#12518]
Hello Team,

In Table 81 we need possibility to have our additional checks and/or avoid using standard code. Having event in procedure ValidateAmount would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/119377685-1235e300-bcc6-11eb-9ad0-9ec73544a136.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckCreditLimit(var GenJournalLine: Record "Gen. Journal Line"; CurrFieldNo: Integer; CustCheckCreditLimit: Codeunit "Cust-Check Cr. Limit"; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
