### ISSUE TITLE
[Code Defect] Check on unique mail addresses in SetRecipients fails on a Cronus BE database (CI_AS collation)

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#12520]
@JesperSchulz 

When sending an email containing multiple 'duplicate' mail addresses (e.g. same email in both **lowercase** and **uppercase** added to the recipients list), all works fine on a **W1** Cronus (database collation is set by default to C**S**_AS), resulting in 2 email addresses to be added.

`EmailMessage.Create('FVET@NAVITRANS.EU;fvet@navitrans.eu', 'Test', 'Test');`

Doing the same on a **BE** Cronus (where the default database collation is set to C**I**_AS), an error is thrown.

![image](https://user-images.githubusercontent.com/25268332/119396099-b7f04e80-bcd4-11eb-9e0f-3ee781c3c7c6.png)

This is due to the unique test using dictionaries, not using the database collation and thus adding 2 entries to the dictionary, but the EmailRecipientRecord Insert statement failing (using the database collation C**I**_AS) on the entry already inserted / PK constraint failure.

![image](https://user-images.githubusercontent.com/25268332/119396210-deae8500-bcd4-11eb-9fd4-4e6dc3d1c88e.png)

I can create a PR for this, although would like the advice on how to best fix.

- [ ] Option 1 could be to do a **ToLower** on the recipient, before adding to the unique dictionary:

`Recipient := DelChr(Recipient, '<>').ToLower(); // trim the whitespaces around`

As a consequence, all recipients will then be **lowercased**.

- [ ] Option 2 could be to replace the unique recipient test by an **additional database call**

```
EmailRecipientRecord.SetRange("Email Message Id", Message.Id);
EmailRecipientRecord.SetRange("Email Recipient Type", RecipientType);
EmailRecipientRecord.SetRange("Email Address", CopyStr(Recipient, 1, MaxStrLen(EmailRecipientRecord."Email Address")));
if not EmailRecipientRecord.IsEmpty() then
```

**Comment by darjoo** [comment]
Hi @fvet,

I'd go with option 1. Since emails aren't case sensitive, there's no issue with them all being lowercase.
Additional database calls is less desired since there'll be as many database calls as recipients.

This sounds like a relatively quick fix and review. Tag me in the PR when it is ready and I'll get on it.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
