### ISSUE TITLE
Codeunit 6620 "Copy Document Mgt." - OnAfterCopySalesDocument, OnAfterCopyPurchaseDocument with Enum FromDocType as Parameter instead of Option

### ISSUE THREAD

**Issue by MichaelSchauer98** [microsoft/ALAppExtensions#12523]
Hi, would it be possible to move 1st paramter of the existing events OnAfterCopySalesDocument and OnAfterCopyPurchaseDocument to Enum instead of options? It would save me some necessary conversions because of warnings.

![25-05-_2021_10-01-31](https://user-images.githubusercontent.com/72799416/119461685-3cc48200-bd40-11eb-932f-537a9e83ee73.png)

Thanks

**Comment by AlexanderYakunin** [comment]
This is breaking change, can be done by obsoleting exiting event and introducing new one instead. Cost of this change will be much higher compared with conversion of values. I don't think we should do it now.

**Comment by AlexanderYakunin** [comment]
Closing for now, we will consider this kind of changes later. You can always use construction like

SalesDocTypeAsEnum := "Sales Document Type".FromInteger(SalesDocTypeAsOption) 

in your extension code to convert option value to normal enum.
