### ISSUE TITLE
[Request for External] page 499 "Available - Sales Lines"- Access to function "GetReservedQtyInLine()"

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#12524]
Please make the local procedure in accessable.

page 499 "Available - Sales Lines"

local procedure GetReservedQtyInLine(): Decimal

Should be done with, but you may missed this one function.
https://github.com/microsoft/ALAppExtensions/issues/12192#issue-870873949
Insider Build Version: Microsoft Base Application 19.0.25970.0

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
