### ISSUE TITLE
[Event Request] Email OnAfterValidateEmailMessage

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#12537]
@JesperSchulz / @darjoo 

We'd like to prevent sending out emails to 'external' addresses unintentionally on our **test / sandbox** environments. Therefore we've added a setting to specify a list of allowed domains / mail addresses that are allowed when **sending** an email.

In an attempt to find a valid event that is raised upon sending an email message, none was found. We used to subscribe to EmailAccount.OnAfterValidateEmailAddress (called via EmailMessageImpl.ValidateRecipients in EmailImpl.Send, thus just before sending), but this results in no longer being able to enter e.g. an email address on a customer card as well (if it does not match the allowed domains)

Ideally an event must be available just after all validations have been performed on the emailMessage to be sent.

![image](https://user-images.githubusercontent.com/25268332/119527837-fe9b8280-bd80-11eb-8803-199675a445f3.png)

- Wanted to create a PR, but find it difficult to create a working version of the system-workspace. Would love to find more documentation on where to get the netpackages / assemblyprobingpaths files (using a Docker based environments) to package all. As well as any options on how to easily package just the 'Email' app and publish so I can test the changes.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
