### ISSUE TITLE
[Request-For-External] Page 950 "Time Sheet" - TimeSheetHeader

### ISSUE THREAD

**Issue by percova** [microsoft/ALAppExtensions#12531]
Hi, could you please change the global **TimeSheetHeader** variable's protection level on page 950 (**Time Sheet**) to a **protected**?
```AL
    protected var
        TimeSheetHeader: Record "Time Sheet Header";
```
#12528 #12529
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
