### ISSUE TITLE
[Code Defect] Table 37 "Sales Line" - wrong field for CheckAssocPurchOrder

### ISSUE THREAD

**Issue by ViktorasDanielius** [microsoft/ALAppExtensions#12530]
Hi,

On Table 37 "Sales Line" OnValidate of field 5711 "Purchasing Code" following code is calling CheckAssocPurchOrder function:
CheckAssocPurchOrder(FieldCaption(Type));

Please change it to the correct one:
CheckAssocPurchOrder(FieldCaption("Purchasing Code"));

![Sales Line - Purchasing Code - OnValidate](https://user-images.githubusercontent.com/72807031/119482530-a5215c80-bd5c-11eb-9add-6a2ea32fe4cf.jpg)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
