### ISSUE TITLE
[Bug] Codeunit 90 Purch.-Post missing var on Publisher OnBeforeProcessAssocItemJnlLine

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#12540]
In Codeunit 90 Purch.-Post, Event OnBeforeProcessAssocItemJnlLine is missing var on IsHandled parameter.
![image](https://user-images.githubusercontent.com/59221826/119556521-6cef3d80-bd9f-11eb-8d89-f2a653b4d700.png)
![image](https://user-images.githubusercontent.com/59221826/119556611-898b7580-bd9f-11eb-90d4-0e97d59ddcea.png)

Best regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
