### ISSUE TITLE
table 11000002 "Payment History Line" generates overflow in GetAccHolderPostalAddr

### ISSUE THREAD

**Issue by mboon75** [microsoft/ALAppExtensions#12544]
In function GetAccHolderPostalAddr has variable AddrLine length 70
![image](https://user-images.githubusercontent.com/32514251/119633091-acef0880-be11-11eb-92cf-f4c591d6cf50.png)

While "Account Holder Address" has length 100

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
