### ISSUE TITLE
[AAD Application] Permission Granted never updated

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/ALAppExtensions#12551]
Hi,

I don't know if it's the correct place to put the issue (and sorry if it's not).

In the AAD Application table, the field `Permission Granted` cannot be used as it is never updated.

I use this table to store the client id of an app and perform some requests from/to outside but I cannot use this table to test if the permission has been granted by administrator using the `Permission Granted` field.

What I want to achieve:
- Setup an AAD Application Record
- Test `MyAADApplication.PermissionGranted`
- if it's true, then use this record to perform some requests

In the baseapp code (v18) the `GrantConsent ` procedure called by the `Grand Consent action` on the A`AD Application Card page` does not update the field:
![image](https://user-images.githubusercontent.com/29598240/119689826-77661180-be49-11eb-84bc-671007799420.png)

I think this could be the place where it is updated.

Also, there is no reference to this field if any place of the code.

Is it possible to update this field to true when the consent is granted by an admin ?

(if it's not the right place for this issue, please tell me where I can post it, thanks!)

Thanks for your help!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
