### ISSUE TITLE
[Event Request] T5050 Contact - procedure UpdateQuotesFromTemplate()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#12557]
```
procedure UpdateQuotesFromTemplate(Customer: Record Customer; CustomerTemplate: Code[20])
var
begin
  ----------------------- ADD EVENT ----------------------
  IsHandled := false;
  OnBeforeUpdateQuotesFromTemplate(Customer, CustomerTemplate, IsHandled)
  if IsHandled then
     exit;
  ----------------------------------------------------------

....................
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateQuotesFromTemplate(Customer: Record Customer; CustomerTemplate: Code[20], var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by CyrilleJsmt** [comment]
Hi, where is the event in the BC180- CU2 when the request is 29 days old ?

**Comment by JesperSchulz** [comment]
It shouldn't be :-) I assume it will release with 18.3 in July, if all went according to plan. Did you by any chance grab a preview build of some sort?
