### ISSUE TITLE
[Enum request] Table 435 "IC Inbox Sales Line"

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#12563]
Could you please change "Document Type" field to an enum.
Thank you.

**Comment by AlexanderYakunin** [comment]
Implemented recently. please check latest builds for master

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
