### ISSUE TITLE
[Event Request] Codeunit 5640 Duplicate Depr. Book (4 Events)

### ISSUE THREAD

**Issue by Kowa63** [Microsoft/ALAppExtensions#1256]
In PROCEDURE InsertLine 
4 Events are required
OnBeforeInsertGenJnlLineGenJnlPosting(GenJnlLine)
OnBeforeInsertGenJnlLineFAJnlPosting(GenJnlLine,FAJnlLine)
OnBeforeInsertFaJnlLineGenJnlPosting(FAJnlLine,GenJnlLine)
OnBeforeInsertFaJnlLineFAJnlPosting(FAJnlLine)

![grafik](https://user-images.githubusercontent.com/16236672/52843356-2c091880-3102-11e9-9d88-fc5c44d78e84.png)
![grafik](https://user-images.githubusercontent.com/16236672/52843368-31fef980-3102-11e9-84cc-1c039906954a.png)
![grafik](https://user-images.githubusercontent.com/16236672/52845659-f109e380-3107-11e9-9451-0027d42a0fe7.png)

**Comment by AndreaRux** [comment]
Hello,
We still miss the events in CU5640. Is there any news on this issue? When can we expect the events?
Thank you in advance for any information.

**Comment by Kowa63** [comment]
Implemented as 2 Publishers in BC 14 CU 03.
![grafik](https://user-images.githubusercontent.com/16236672/63930694-1e8afe80-ca54-11e9-99da-eab0f6c835f7.png)
