### ISSUE TITLE
[Event Request] Codeunit 181 "Copy Gen. Journal Mgt.", procedure CheckIfCanBeCopied()

### ISSUE THREAD

**Issue by supercruel** [microsoft/ALAppExtensions#12570]
Would it be possible to give us a "OnAfterCheckIfCanBeCopied" event in Codeunit 181 "Copy Gen. Journal Mgt.", procedure CheckIfCanBeCopied()?
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
