### ISSUE TITLE
[Request-for-external] page 343 "Check Credit Limit" - SalesLineShowWarning

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#12573]
Can you please remove [Scope('OnPrem')] from procedure SalesLineShowWarning in page "Check Credit Limit" (343).

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
