### ISSUE TITLE
[Event Request] Report 593 "Intrastat - Make Disk Tax Auth"

### ISSUE THREAD

**Issue by BourgeoisDirk** [microsoft/ALAppExtensions#12574]
Dear Team,

Is it possible to add an event to this report on trigger OnPreReport(), right above the function call CreateXMLDocument() ?
`trigger OnPreReport()
var
    CompanyInformation: Record "Company Information";
    VATLogicalTests: Codeunit VATLogicalTests;
begin
    if IntrastatJnlLine.GetFilter(Type) = '' then
        IntrastatJnlLine.FieldError(Type, ReceiptShipmentErr);

    if ThirdPartyVatRegNo <> '' then
        EnterpriseNo := DelChr(ThirdPartyVatRegNo, '=', DelChr(ThirdPartyVatRegNo, '=', '0123456789'))
    else begin
        CompanyInformation.Get();
        if not VATLogicalTests.MOD97Check(CompanyInformation."Enterprise No.") then
            Error(EnterpriseNoNotValidErr);
        EnterpriseNo := DelChr(CompanyInformation."Enterprise No.", '=', DelChr(CompanyInformation."Enterprise No.", '=', '0123456789'));
    end;

    CreateXMLDocument;
end;`

Maybe an event OnBeforeCreateXMLDocument(var EnterpriseNo: Text[30])
Or an OnBeforeGetEnterpriseNo(var) with a Handled, to skip the code and replace the EnterpriseNo value.

Now I had to Save-As the entire report, modify the FileManagement and DotNet usage so it is Cloud-friendly, and get my EnterpriseNo from somehwere else. Keeping this saved-as report updated with all future changes is not something I'm looking forward to.

Kind regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
