### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - OnPostPurchLineOnBeforeInsertCrMemoLine

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12577]
Hello. In codeunit 90 "Purch.-Post", in the local procedure PostPurchLine, I would like to use a different PurchCrMemoLine record than the one used in standard code. I would like to use the event publisher OnPostPurchLineOnBeforeInsertCrMemoLine, but I need the paramet PurchCrMemoLine to be added to this event. Like this :

    local procedure PostPurchLine(var PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; var TempInvoicePostBuffer: Record "Invoice Post. Buffer" temporary; var TempVATAmountLine: Record "VAT Amount Line" temporary; var TempVATAmountLineRemainder: Record "VAT Amount Line" temporary; var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer" temporary; var EverythingInvoiced: Boolean; var ICGenJnlLineNo: Integer)
    begin
            ...
            if PurchHeader.Invoice then
                ...
                end else begin // Credit Memo

                    OnPostPurchLineOnBeforeInsertCrMemoLine(PurchHeader, PurchLine, IsHandled, PurchCrMemoLine);

                    if not IsHandled then begin
                        PurchCrMemoLine.InitFromPurchLine(PurchCrMemoHeader, xPurchLine);
                        ItemJnlPostLine.CollectValueEntryRelation(TempValueEntryRelation, CopyStr(PurchCrMemoLine.RowID1, 1, 100));
                        if "Document Type" = "Document Type"::"Return Order" then begin
                            PurchCrMemoLine."Order No." := "Document No.";
                            PurchCrMemoLine."Order Line No." := "Line No.";
                        end;
    ...
    end;

With this event integration : 

    [IntegrationEvent(false, false)]
    local procedure OnPostPurchLineOnBeforeInsertCrMemoLine(PurchaseHeader: Record "Purchase Header"; PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean; var PurchCrMemoLine: Record "Purch. Cr. Memo Line");
    begin
    end;

Do you think it is possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
