### ISSUE TITLE
report 120 "Aged Accounts Receivable" - TempCustLedgEntry is not accessible to report extensions

### ISSUE THREAD

**Issue by dtkb** [microsoft/ALAppExtensions#12579]
The report inserts entries into the TempCustLedgEntry table to determine what finally gets shown/summed. But that data item is done using a `TempCustLedgEntryLoop; Integer`, not the `TempCustLedgEntry` record itself. Therefore, we can't e.g. check `OnAfterAfterGetItem()` and add or check fields in the entry, change logic or skip, etc.

Right now, we are adding a request page option to Show Only Open Entries, and that seems workable, but we can't then (if that option is `false`) add the `Open` field from the `TempCustLedgEntry` record to show on the extended report layout, which seems useful.

Please add a solution, such as 
1. preferable: Remove the legacy `Integer` faff, and just make the dataitem **be** `TempCustLedgEntryLoop` directly, thanks to the 'newer' `UseTemporary = true` property. Hopefully this can't break anyone's use of the report, since it seems like just an implementation detail? I don't know though.
2. otherwise: Make `TempCustLedgEntry` into a `protected` variable, so that when we add triggers to `TempCustLedgEntryLoop` we can actually access the record it loops. (This presumes `protected` works to allow report extensions access to report variables. Right?)

Thanks!

**Comment by dtkb** [comment]
The same goes for `Aged Accounts Payable`:

![image](https://user-images.githubusercontent.com/63455896/122387610-f2ad7580-cf66-11eb-9b8e-2d8a0229d9cd.png)

Can you please update both at the same time, since they're basically mirrored copies of each other?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
