### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - OnPostItemJnlLineOnAfterSetFactor

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12588]
Hello. In codeunit 90 "Purch.-Post", in the procedure PostItemJnlLine, I would like to change the value of a field in the ItemJnlLine record at a specific moment of the code. I would like to use the event publisher OnPostItemJnlLineOnAfterSetFactor, but I need the parameter ItemJnlLine to be added to this event. Like this :

    procedure PostItemJnlLine(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; QtyToBeReceived: Decimal; QtyToBeReceivedBase: Decimal; QtyToBeInvoiced: Decimal; QtyToBeInvoicedBase: Decimal; ItemLedgShptEntryNo: Integer; ItemChargeNo: Code[20]; TrackingSpecification: Record "Tracking Specification"): Integer
    begin
        ...
            if QtyToBeInvoiced <> 0 then begin
                if (QtyToBeInvoicedBase <> 0) and (PurchLine.Type = PurchLine.Type::Item) then
                    Factor := QtyToBeInvoicedBase / PurchLine."Qty. to Invoice (Base)"
                else
                    Factor := QtyToBeInvoiced / PurchLine."Qty. to Invoice";

                OnPostItemJnlLineOnAfterSetFactor(ItemJnlLine, PurchLine, Factor, GenJnlLineExtDocNo);
        ...
    end;

With this integration event : 

    [IntegrationEvent(false, false)]
    local procedure OnPostItemJnlLineOnAfterSetFactor(var PurchaseLine: Record "Purchase Line"; var Factor: Decimal; var GenJnlLineExtDocNo: Code[35]; var ItemJournalLine: Record "Item Journal Line")
    begin
    end;

Do you think it could be possible ?

Thank you for work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
