### ISSUE TITLE
Codeunit 6620 Copy Document Mgt. - Add Parameter to SetProperties function

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12595]
Hi al-team,

we need to set the flag "SkipCopyFromDescription" from external. Currently, the field can only be set using the SetPropertiesForInvoiceCorrection function, which is not sufficient.
Maybe it makes sense to extend the function SetProperties by one parameter. Then there would be twice the function with different parameters. The function with fewer parameters calls the function with more parameters.
This is what it could look like: 

```
procedure SetProperties(NewIncludeHeader: Boolean; NewRecalculateLines: Boolean; NewMoveNegLines: Boolean; NewCreateToHeader: Boolean; NewHideDialog: Boolean; NewExactCostRevMandatory: Boolean; NewApplyFully: Boolean)
    begin
        SetProperties(NewIncludeHeader, NewRecalculateLines, NewMoveNegLines, NewCreateToHeader, NewHideDialog, NewExactCostRevMandatory, NewApplyFully, false)
    end;

    procedure SetProperties(NewIncludeHeader: Boolean; NewRecalculateLines: Boolean; NewMoveNegLines: Boolean; NewCreateToHeader: Boolean; NewHideDialog: Boolean; NewExactCostRevMandatory: Boolean; NewApplyFully: Boolean; NewSkipCopyFromDescription: Boolean)
    begin
        IncludeHeader := NewIncludeHeader;
        RecalculateLines := NewRecalculateLines;
        MoveNegLines := NewMoveNegLines;
        CreateToHeader := NewCreateToHeader;
        HideDialog := NewHideDialog;
        ExactCostRevMandatory := NewExactCostRevMandatory;
        ApplyFully := NewApplyFully;
        AskApply := false;
        ReappDone := false;
        SkippedLine := false;
        SomeAreFixed := false;
        SkipCopyFromDescription := NewSkipCopyFromDescription;
        SkipTestCreditLimit := false;

        OnAfterSetProperties(IncludeHeader, RecalculateLines, MoveNegLines, CreateToHeader, HideDialog, ExactCostRevMandatory, ApplyFully);
    end;


```

**Comment by DavidMaravic** [comment]
As a workaround, you could try to use OnBeforeInsertOldPurchDocNoLine or OnBeforeInsertOldSalesDocNoLine to skip the insert of the additional Source line. It would be easier if we can use Set the parameter as you proposed.
Also OnCopySalesInvLinesToDocOnBeforeInsertOldSalesDocNoLine can be used to override the SkipCopyFromDescription.

**Comment by MattiLE** [comment]
Hi @DavidMaravic  thanks for the hint with the OnBeforeInsertOldSalesDocNoLine event. This works for my process. :)
