### ISSUE TITLE
Auto sign service contract without a dialoog

### ISSUE THREAD

**Issue by renevanbeekum** [microsoft/ALAppExtensions#12594]
Changes in codeunit 5943 Lock-OpenServContract to lock a service contract without a dialoog.

Global var
DoAutoSign: Boolean;

New procedure:
procedure SetAutoSign()
begin
    DoAutoSign := true;
end;

And changes in procedure LockServContract

Old:
                if not ServContractLine.IsEmpty() then begin
                    if not ConfirmManagement.GetResponseOrDefault(Text002, true) then
                        exit;
                    SignServContractDoc.AddendumToContract(ServContractHeader);
                end;

New:
                if not ServContractLine.IsEmpty then begin
                    if not DoAutoSign then //Changes
                        if not ConfirmManagement.ConfirmProcess(Text002, true) then
                            exit;
                    //Changes Begin
                    if DoAutoSign then
                        SignServContractDoc.SetHideDialog(true);
                    //Changes End
                    SignServContractDoc.AddendumToContract(ServContractHeader);
                end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
