### ISSUE TITLE
[Code Change Request] Table - 5941 "Service Item component" - onModify trigger

### ISSUE THREAD

**Issue by srinivasGangadhara** [microsoft/ALAppExtensions#12598]
Please change the code from **ServItemComponent.Insert();** to **ServItemComponent.Insert(True);**

![image](https://user-images.githubusercontent.com/29703512/120174346-9c2fff80-c222-11eb-928b-e0c1b33a64b5.png)

Thanks!
srinivas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
