### ISSUE TITLE
[Enum Request] Table : Service Ledger Entry - Field 50 -Entry type should be converted to ENum

### ISSUE THREAD

**Issue by srinivasGangadhara** [microsoft/ALAppExtensions#12597]
Please convert Entry type field from option to Enum.

Table- 5907 - "Service Ledger Entry" - Field 50

![image](https://user-images.githubusercontent.com/29703512/120170407-8d474e00-c21e-11eb-991d-21d96f08e405.png)

Thanks!
srinivas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
