### ISSUE TITLE
[Request for external] - PostSalesOrder - Sales Order

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#12609]
Hi, 

PostDocument is deprecated. Could you please make PostSalesOrder global? 

![image](https://user-images.githubusercontent.com/35260264/120228795-29d41500-c24c-11eb-9a5e-4e844c4bd3b2.png)

Thank you.

**Comment by AlexanderYakunin** [comment]
PostSalesOrder is protected procedure, which is available in page extensions.

**Comment by DanielHaglo** [comment]
Hi Alexander, PostSalesOrder is local in 18.1 also. When is it becoming protected? I cannot see that now.
