### ISSUE TITLE
[Enum Request] table 5936 "Service Document Register" - option Field "Source Document Type" convert to Enum

### ISSUE THREAD

**Issue by srinivasGangadhara** [microsoft/ALAppExtensions#12600]
Please convert option field 1 in to Enum,

field(1; "Source Document Type"; Option)
        {
            Caption = 'Source Document Type';
            OptionCaption = 'Order,Contract';
            OptionMembers = "Order",Contract;
        }

Thanks!

regards
srinivas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
