### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - OnAfterDeleteApprovalEntries

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12608]
Hello. In codeunit 90 "Purch.-Post", in the procedure DeleteApprovalEntries, I would like to add my code just after the call of the DeleteApprovalEntries procedure, and before the call of the DeleteAfterPosting procedure. To do so, I need an event publisher. Like this :

    local procedure DeleteApprovalEntries(var PurchHeader: Record "Purchase Header")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeDeleteApprovalEntries(PurchHeader, IsHandled);
        if IsHandled then
            exit;

        ApprovalsMgmt.DeleteApprovalEntries(PurchHeader.RecordId());

        OnAfterDeleteApprovalEntries((PurchHeader, PurchInvHeader);
    end;

With this integration event : 

    [IntegrationEvent(false, false)]
    local procedure OnAfterDeleteApprovalEntries(var PurchaseHeader: Record "Purchase Header"; var PurchInvHeader: Record "Purch. Inv. Header")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
