### ISSUE TITLE
[Request-for-external] Codeunit 12 Gen. Jnl.-Post Line - SummarizeVAT

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#12607]
Can you make SummarizeVAT in Codeunit 12 "Gen. Jnl.-Post Line" global?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
