### ISSUE TITLE
FieldGroups - Some tables need default DropDown FieldGroup

### ISSUE THREAD

**Issue by Wilkai8** [microsoft/ALAppExtensions#12605]
It is not possible to extend a FieldGroup without it already existing. E.g. the "Posted Gen. Journal Line" (181) table has no DropDown FieldGroup so I can't add any field from a tableextension to the default dropdown in a lookup. It defaults to just Description.

Could you please add the default DropDown and Brick fieldgroup to:
"Posted Gen. Journal Line" (181)
Thank you in advance.

**Comment by JesperSchulz** [comment]
Will process request :-)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
