### ISSUE TITLE
[Extendsibility Enhancement] Page 99000811 "Prod. BOM Where-Used" - ShowLevel Protected var

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#12603]
Hello, Is it possible to get ShowLevel as Protected var?
```
        ShowLevel: Option Single,Multi;
        //>>>>>>>>>>>>>>>>>>>>>>>>>
    protected var
        ShowLevel: Option Single,Multi;
        //<<<<<<<<<<<<<<<<<<<<<<<<<
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
