### ISSUE TITLE
[Enum Request] table 5077 "Segment Line" - Evaluation option field to Enum Convert

### ISSUE THREAD

**Issue by srinivasGangadhara** [microsoft/ALAppExtensions#12613]
Please convert option field to Enum

![image](https://user-images.githubusercontent.com/29703512/120266185-039b8d00-c2bf-11eb-844d-cbf985c62b41.png)

Thanks!
srinivas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
