### ISSUE TITLE
New event for Item Cost Management (C5804)

### ISSUE THREAD

**Issue by Rama-M** [Microsoft/ALAppExtensions#1261]
We need the following 3 Integration type Event in UpdateUnitCost function in codeunit 5804.  It will help various integration/development projects.  See the proposed 3 events below.

1) OnBeforeUpdateUnitCost(Item) - 

OnBeforeUpdateUnitCost(Item); //New Event
WITH Item DO BEGIN
  IF NewStdCost <> 0 THEN
    "Standard Cost" := NewStdCost;

  IF "Costing Method" = "Costing Method"::Standard THEN
    "Unit Cost" := "Standard Cost"

2) OnBeforePriceProfitCalculationUpdate(Handled)

OnBeforePriceProfitCalculationUpdate(Handled);  //New Event
  IF NOT Handled Begin
    VALIDATE("Price/Profit Calculation");

    IF CheckItem.GET("No.") THEN
      IF CalledByFieldNo <> 0 THEN
        MODIFY(TRUE)
      ELSE
        MODIFY;
  END;

3) OnBeforeUnitCostSKU(UpdateSKU);

  OnBeforeUnitCostSKU(UpdateSKU);  //New Event
  IF UpdateSKU THEN
    FindUpdateUnitCostSKU(Item,LocationCode,VariantCode,FilterSKU,LastDirectCost);

**Comment by AlexanderYakunin** [comment]
Hello! I cannot accept you request. Please specify procedure and exact location for each event with list of required parameters. Please also check existing events before asking for new, events for 1 and 3 already exists. Please correct ask 2.

**Comment by Rama-M** [comment]
Hi Jesper,
Forgot about request 1 and 3. 
For two the parameter is "Handled" of type Boolean. See my request and example code in my request.  The C/Side code also need updated to work on this "Handled" variable. See my request above.
