### ISSUE TITLE
[Enum Request] table 5065 "Interaction Log Entry" - Evaluation field option to Enum convert

### ISSUE THREAD

**Issue by srinivasGangadhara** [microsoft/ALAppExtensions#12614]
Please convert option to enum.

![image](https://user-images.githubusercontent.com/29703512/120266344-4f4e3680-c2bf-11eb-893c-fe39ded4d41b.png)

if issue #12613  is same for this option , otherwise please accept as Enum request.

Thanks!
Srinivas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
