### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" NothingToPostErr

### ISSUE THREAD

**Issue by Mikhail-MSC** [microsoft/ALAppExtensions#12612]
Event required before `Error(NothingToPostErr)` to handle customized posting scenarios:
```
if not (Ship or Invoice or Receive) then
    Error(NothingToPostErr);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
