### ISSUE TITLE
[Event Request] Codeunit 99000854 "Inventory Profile Offsetting"

### ISSUE THREAD

**Issue by Mikhail-MSC** [microsoft/ALAppExtensions#12611]
Multiple "OnAfter" publishers required after the `TransferFrom<...>Line` function is called in the following procedures:

`SetPurchase`
`SetProdOrder`
`SetAssembly`
`SetTransfer`

Example:

    local procedure SetPurchase(var PurchaseLine: Record "Purchase Line"; var InventoryProfile: Record "Inventory Profile")
    begin
        with ReqLine do begin
            "Ref. Order Type" := "Ref. Order Type"::Purchase;
            "Ref. Order No." := InventoryProfile."Source ID";
            "Ref. Line No." := InventoryProfile."Source Ref. No.";
            PurchaseLine.Get(PurchaseLine."Document Type"::Order, "Ref. Order No.", "Ref. Line No.");
            TransferFromPurchaseLine(PurchaseLine);
            //new publisher start
            OnAfterTransferFromPurchaseLine(PurchaseLine,ReqLine,InventoryProfile);
            //new publisher end
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
