### ISSUE TITLE
Can't subscribe to Event Publisher OnBeforeConfirmPost in Codeunit 91

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#12618]
Hi, I hope this is the right place to report my issue. If not please let me know.

I'm having trouble subscribing to the Event OnBeforeConfirmPost in codeunit 91 "Purch.-Post (Yes/No)".

While i'm debugging, the code in my event subscriber doesn't seem to be executed and the value of the variable IsHandled isn't modified. 
Here is my event subscriber
```
[EventSubscriber(ObjectType::Codeunit, Codeunit::"Purch.-Post (Yes/No)", 'OnBeforeConfirmPost', '', true, true)]
    local procedure OnBeforeConfirmPost(var PurchaseHeader: Record "Purchase Header"; var DefaultOption: Integer; var HideDialog: Boolean; var IsHandled: Boolean)
```

Have I done something wrong or is there something not working with this particular event ?

Thanks

**Comment by StanPesotskiy** [comment]
It looks fine, no special tricks needed for this event. It is one of many regular events.
Try to open page 9510 to see if your subscription is active. If parameters do not match the subscription may become inactive.
Try to recreate the subscription by "AL: Find Event" command in VS Code.

**Comment by VMotin** [comment]
Thanks for your answer, unfortunately that's not it. My subscription seems fine in page 9510
![image](https://user-images.githubusercontent.com/73548802/120330983-9eab5b80-c2ed-11eb-8d63-67743a7f0d28.png)
and recreating the subscription with AL:Find Event didn't do the trick

**Comment by StanPesotskiy** [comment]
Then you better file a bug with simple reproducible steps. 
This is just a regular event. It should work as any other.

**Comment by VMotin** [comment]
Thanks for your answer, where can i file a bug ?

**Comment by StanPesotskiy** [comment]
Please reach out to the relevant support channels:
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
