### ISSUE TITLE
[Event Request] - Codeunit CRM Sales Order to Sales Order - OnBeforeGetCoupledCustomer

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#12616]
![image](https://user-images.githubusercontent.com/35260264/120294504-8d028d80-c2c6-11eb-99a8-9ba6dc3fdb11.png)

Can you create this event?
Customer needs to be VAR

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
