### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - OnPostBalancingEntryOnAfterInitNewLine

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12619]
Hello. In codeunit 90 "Purch.-Post", in the procedure PostBalancingEntry, I would like to my code at a specific moment. To do so, I need an event publisher here : 

    local procedure PostBalancingEntry(PurchHeader: Record "Purchase Header"; TotalPurchLine2: Record "Purchase Line"; TotalPurchLineLCY2: Record "Purchase Line"; DocType: Enum "Gen. Journal Document Type"; DocNo: Code[20]; ExtDocNo: Code[35]; SourceCode: Code[10])
    begin
        FindVendorLedgerEntry(DocType, DocNo, VendLedgEntry);

        with GenJnlLine do begin
            InitNewLine(
              PurchHeader."Posting Date", PurchHeader."Document Date", PurchHeader."Posting Description",
              PurchHeader."Shortcut Dimension 1 Code", PurchHeader."Shortcut Dimension 2 Code",
              PurchHeader."Dimension Set ID", PurchHeader."Reason Code");

            OnPostBalancingEntryOnAfterInitNewLine(PurchHeader, GenJnlLine);

            CopyDocumentFields("Gen. Journal Document Type"::" ", DocNo, ExtDocNo, SourceCode, '');
            ...
    end;

With this integration event : 

    [IntegrationEvent(false, false)]
    local procedure OnPostBalancingEntryOnAfterInitNewLine(PurchHeader: Record "Purchase Header"; GenJnlLine: Record "Gen. Journal Line")
    begin
    end;

Do you think it could be possible ?

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
