### ISSUE TITLE
[Event Request] Codeunit 99000830 "Create Reserv. Entry" - function CreateReservEntryFrom

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12629]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 99000830 "Create Reserv. Entry" - function CreateReservEntryFrom    

    procedure CreateReservEntryFrom(FromTrackingSpecification: Record "Tracking Specification")
    begin
        InsertReservEntry2.Init();
        InsertReservEntry2.SetSource(
            FromTrackingSpecification."Source Type",
            FromTrackingSpecification."Source Subtype",
            FromTrackingSpecification."Source ID",
            FromTrackingSpecification."Source Ref. No.",
            FromTrackingSpecification."Source Batch Name",
            FromTrackingSpecification."Source Prod. Order Line");
        InsertReservEntry2."Qty. per Unit of Measure" := FromTrackingSpecification."Qty. per Unit of Measure";
        InsertReservEntry2.CopyTrackingFromSpec(FromTrackingSpecification);

        InsertReservEntry2.TestField("Qty. per Unit of Measure");
        // DINNL <<
        DINOnAfterCreateReservEntryFrom(InsertReservEntry2);
        // DINNL >>
    end;

    local procedure DINOnAfterCreateReservEntryFrom(var ReservationEntry: Record "Reservation Entry")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
