### ISSUE TITLE
[Event Request] Table 5870 "BOM Buffer" - OnAfterGetItemCost

### ISSUE THREAD

**Issue by jbakach** [microsoft/ALAppExtensions#12620]
Hello. In Table 5870 "BOM Buffer", I think that it would be really great to have more events. There are few, but more are needed.

`procedure GetItemCosts()
    var
        Item: Record Item;
        UOMMgt: Codeunit "Unit of Measure Management";
    begin
        TestField(Type, Type::Item);
        Item.Get("No.");

        "Unit Cost" := Item."Unit Cost";
        "Single-Level Material Cost" := "Unit Cost";
        "Rolled-up Material Cost" := "Single-Level Material Cost";

        if "Qty. per Parent" <> 0 then
            "Single-Level Scrap Cost" := "Single-Level Material Cost" * "Scrap Qty. per Parent" / "Qty. per Parent";
        if "Qty. per Top Item" <> 0 then
            "Rolled-up Scrap Cost" := "Rolled-up Material Cost" * "Scrap Qty. per Top Item" / "Qty. per Top Item";
        RoundCosts(UOMMgt.GetQtyPerUnitOfMeasure(Item, "Unit of Measure Code") * "Qty. per Top Item");
        **OnAfterGetItemCosts(Rec,Item);**
    end;`

Integration Event definition:

**[IntegrationEvent(false, false)]
local procedure OnAfterGetItemCosts(var BOMBuffer:Record "BOM Buffer";Item:Record Item)
begin
end;**

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
