### ISSUE TITLE
[Event Request] Table 5870 "BOM Buffer" - OnBeforeReturnLineOk

### ISSUE THREAD

**Issue by jbakach** [microsoft/ALAppExtensions#12621]
Hello. In Table 5870 "BOM Buffer":

procedure IsLineOk(LogWarning: Boolean; var BOMWarningLog: Record "BOM Warning Log"): Boolean
    begin
        exit(
          IsLowLevelOk(LogWarning, BOMWarningLog) and
          IsQtyPerOk(LogWarning, BOMWarningLog) and
          IsProdBOMOk(LogWarning, BOMWarningLog) and
          IsRoutingOk(LogWarning, BOMWarningLog) and
          IsReplenishmentOk(LogWarning, BOMWarningLog));
    end;

To:

`procedure IsLineOk(LogWarning: Boolean; var BOMWarningLog: Record "BOM Warning Log")LineOK: Boolean
    begin
           LineOK :=
               IsLowLevelOk(LogWarning, BOMWarningLog) and
               IsQtyPerOk(LogWarning, BOMWarningLog) and
               IsProdBOMOk(LogWarning, BOMWarningLog) and
               IsRoutingOk(LogWarning, BOMWarningLog) and
               IsReplenishmentOk(LogWarning, BOMWarningLog));
       **OnBeforeReturnLineOk(LineOK,Rec,BOMWarningLog);**
    end;
Integration Event definition:

[IntegrationEvent(false, false)]
local procedure OnBeforeReturnLineOk(var LineOK:Boolean; var BOMBuffer:Record "BOM Buffer";var BOMWarningLog: Record "BOM Warning Log")
begin
end;

Thank you for your work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
