### ISSUE TITLE
[Event Request] codeunit 99000830 "Create Reserv. Entry". - Add parameters to function OnAfterCopyFromInsertReservEntry

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12627]
Dear ALAppExtensions Team,

Is it possible to add 2 parameters to function OnAfterCopyFromInsertReservEntry in codeunit 99000830 ?

-OnAfterCopyFromInsertReservEntry(InsertReservEntry2, ReservEntry2, ReservEntry);
+OnAfterCopyFromInsertReservEntry(InsertReservEntry2, ReservEntry2, ReservEntry, Status, QtyToHandleAndInvoiceIsSet);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
