### ISSUE TITLE
[Event Request] Codeunit 99000830 "Create Reserv. Entry" - function CreateReservEntryFor

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12628]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 99000830 "Create Reserv. Entry" - function CreateReservEntryFor

    procedure CreateReservEntryFor(ForType: Option; ForSubtype: Integer; ForID: Code[20]; ForBatchName: Code[10]; ForProdOrderLine: Integer; ForRefNo: Integer; ForQtyPerUOM: Decimal; Quantity: Decimal; QuantityBase: Decimal; ForReservEntry: Record "Reservation Entry")
    var
        Sign: Integer;
    begin
        InsertReservEntry.SetSource(ForType, ForSubtype, ForID, ForRefNo, ForBatchName, ForProdOrderLine);
        Sign := SignFactor(InsertReservEntry);
        InsertReservEntry.Quantity := Sign * Quantity;
        InsertReservEntry."Quantity (Base)" := Sign * QuantityBase;
        InsertReservEntry."Qty. per Unit of Measure" := ForQtyPerUOM;
        InsertReservEntry.CopyTrackingFromreservEntry(ForReservEntry);

        InsertReservEntry.TestField("Qty. per Unit of Measure");
        // DINNL <<
        DINOnAfterCreateReservEntryFor(InsertReservEntry, Sign);
        // DINNL >>
    end;

    local procedure DINOnAfterCreateReservEntryFor(var ReservationEntry: Record "Reservation Entry"; Sign: Integer)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
