### ISSUE TITLE
[Event Request] Codeunit 11000006 CBG Statement Reconciliation - function UpdateAccount

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12625]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 11000006 CBG Statement Reconciliation - function UpdateAccount.

                if not RecChanged and (CBGStatementLine.Credit <= 0) then
                    if FindNAC(Name, Address, City, TempReconciliationBuffer."Source Type"::Employee, CBGStatementLine."Account No.") then begin
                        CBGStatementLine."Account Type" := CBGStatementLine."Account Type"::Employee;
                        CBGStatementLine.Validate("Account No.", CBGStatementLine."Account No.");
                        CBGStatementLine."Reconciliation Status" := CBGStatementLine."Reconciliation Status"::Changed;
                        NumberOfLinesChanged := NumberOfLinesChanged + 1;
                        RecChanged := true;
                    end;
                // DINNL <<
                DINOnAfterUpdateAccount(RecChanged, CBGStatementLine, NumberOfLinesChanged);
                // DINNL >>
            end;
        end;
    end;

    local procedure DINOnAfterUpdateAccount(var RecChanged: Boolean; var CBGStatementLine: Record "CBG Statement Line"; var NumberOfLinesChanged: Integer)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
