### ISSUE TITLE
[Scope Change] Codeunit 1259 "Certificate Management"

### ISSUE THREAD

**Issue by jazadv** [microsoft/ALAppExtensions#12622]
Can you please remove [Scope('OnPrem')] from procedures GetPassword and GetCertAsBase64String in Codeunit 1259 "Certificate Management".

**Comment by AlexanderYakunin** [comment]
Please explain why you need this?

**Comment by jazadv** [comment]
I have a code like this

`    procedure ExampleProcedure()
    var
        IsolatedCertificate: Record "Isolated Certificate";
        CertificateManagement: Codeunit "Certificate Management";
        NewSetupTable: Record "New Setup Table";
        Cert: Text;
        Pass: Text;
        Client: HttpClient;
    begin
        NewSetupTable.get;
        IF NewSetupTable."Certificate Code" <> '' then begin
            IsolatedCertificate.get(NewSetupTable."Certificate Code");
            Pass := CertificateManagement.GetPassword(IsolatedCertificate);
            Cert := CertificateManagement.GetCertAsBase64String(IsolatedCertificate);
            Client.AddCertificate(Cert, Pass);
            .......................
        end;
    end;`

All procedures in this codeunit are local or have OnPrem scope. There is no way to retrieve certificate data related to "Isolated Certificate" table.

**Comment by WaelAbuSeada** [comment]
You should use cryptography management module in system modules. 

Isolated certificate is a solution for baseapp application only as it utilizes isolated storage, which ensure separation of isolated data between extension.
