### ISSUE TITLE
[Event Request] Table 5870 "BOM Buffer" - OnAfterInsertFromProdComp

### ISSUE THREAD

**Issue by jbakach** [microsoft/ALAppExtensions#12623]
procedure TransferFromProdComp(var EntryNo: Integer; ProdBOMLine: Record "Production BOM Line"; NewIndentation: Integer; ParentQtyPer: Decimal; ParentScrapQtyPer: Decimal; ParentScrapPct: Decimal; NeedByDate: Date; ParentLocationCode: Code[10]; ParentItem: Record Item; BOMQtyPerUOM: Decimal)
    var
        BOMItem: Record Item;
        UOMMgt: Codeunit "Unit of Measure Management";
        CostCalculationMgt: Codeunit "Cost Calculation Management";
    begin
        Init;
        EntryNo += 1;
        "Entry No." := EntryNo;
        Type := Type::Item;

        BOMItem.Get(ProdBOMLine."No.");
        InitFromItem(BOMItem);

        if ParentItem."Lot Size" = 0 then
            ParentItem."Lot Size" := 1;

        Description := ProdBOMLine.Description;
        "Qty. per Parent" :=
          CostCalculationMgt.CalcCompItemQtyBase(
            ProdBOMLine, WorkDate,
            CostCalculationMgt.CalcQtyAdjdForBOMScrap(ParentItem."Lot Size", ParentScrapPct), ParentItem."Routing No.", true) /
          UOMMgt.GetQtyPerUnitOfMeasure(BOMItem, ProdBOMLine."Unit of Measure Code") /
          BOMQtyPerUOM / ParentItem."Lot Size";
        "Qty. per Top Item" := Round(ParentQtyPer * "Qty. per Parent", UOMMgt.QtyRndPrecision);
        "Qty. per Parent" := Round("Qty. per Parent", UOMMgt.QtyRndPrecision);

        "Scrap Qty. per Parent" := "Qty. per Parent" - (ProdBOMLine.Quantity / BOMQtyPerUOM);
        "Scrap Qty. per Top Item" :=
          "Qty. per Top Item" -
          Round((ParentQtyPer - ParentScrapQtyPer) * ("Qty. per Parent" - "Scrap Qty. per Parent"), UOMMgt.QtyRndPrecision);
        "Scrap Qty. per Parent" := Round("Scrap Qty. per Parent", UOMMgt.QtyRndPrecision);

        "Qty. per BOM Line" := ProdBOMLine."Quantity per";
        "Unit of Measure Code" := ProdBOMLine."Unit of Measure Code";
        "Variant Code" := ProdBOMLine."Variant Code";
        "Location Code" := ParentLocationCode;
        "Lead-Time Offset" := ProdBOMLine."Lead-Time Offset";
        "Needed by Date" := NeedByDate;
        Indentation := NewIndentation;

        OnTransferFromProdCompCopyFields(Rec, ProdBOMLine, ParentItem, ParentQtyPer);
        Insert(true);
    end;

To:

procedure TransferFromProdComp(var EntryNo: Integer; ProdBOMLine: Record "Production BOM Line"; NewIndentation: Integer; ParentQtyPer: Decimal; ParentScrapQtyPer: Decimal; ParentScrapPct: Decimal; NeedByDate: Date; ParentLocationCode: Code[10]; ParentItem: Record Item; BOMQtyPerUOM: Decimal)
    var
        BOMItem: Record Item;
        UOMMgt: Codeunit "Unit of Measure Management";
        CostCalculationMgt: Codeunit "Cost Calculation Management";
    begin
        Init;
        EntryNo += 1;
        "Entry No." := EntryNo;
        Type := Type::Item;

        BOMItem.Get(ProdBOMLine."No.");
        InitFromItem(BOMItem);

        if ParentItem."Lot Size" = 0 then
            ParentItem."Lot Size" := 1;

        Description := ProdBOMLine.Description;
        "Qty. per Parent" :=
          CostCalculationMgt.CalcCompItemQtyBase(
            ProdBOMLine, WorkDate,
            CostCalculationMgt.CalcQtyAdjdForBOMScrap(ParentItem."Lot Size", ParentScrapPct), ParentItem."Routing No.", true) /
          UOMMgt.GetQtyPerUnitOfMeasure(BOMItem, ProdBOMLine."Unit of Measure Code") /
          BOMQtyPerUOM / ParentItem."Lot Size";
        "Qty. per Top Item" := Round(ParentQtyPer * "Qty. per Parent", UOMMgt.QtyRndPrecision);
        "Qty. per Parent" := Round("Qty. per Parent", UOMMgt.QtyRndPrecision);

        "Scrap Qty. per Parent" := "Qty. per Parent" - (ProdBOMLine.Quantity / BOMQtyPerUOM);
        "Scrap Qty. per Top Item" :=
          "Qty. per Top Item" -
          Round((ParentQtyPer - ParentScrapQtyPer) * ("Qty. per Parent" - "Scrap Qty. per Parent"), UOMMgt.QtyRndPrecision);
        "Scrap Qty. per Parent" := Round("Scrap Qty. per Parent", UOMMgt.QtyRndPrecision);

        "Qty. per BOM Line" := ProdBOMLine."Quantity per";
        "Unit of Measure Code" := ProdBOMLine."Unit of Measure Code";
        "Variant Code" := ProdBOMLine."Variant Code";
        "Location Code" := ParentLocationCode;
        "Lead-Time Offset" := ProdBOMLine."Lead-Time Offset";
        "Needed by Date" := NeedByDate;
        Indentation := NewIndentation;

        OnTransferFromProdCompCopyFields(Rec, ProdBOMLine, ParentItem, ParentQtyPer);
        Insert(true);
        **OnAfterInsertFromProdComp(Rec,ProdBOMLine,ParentItem,EntryNo);**
    end;

**OnAfterInsertFromProdComp(var BOMBuffer:Record "BOM Buffer"; ProdBOMLine: Record "Production BOM Line"; ParentItem: Record Item;var EntryNo: Integer );**

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
