### ISSUE TITLE
[Event Request] Codeunit 99000830 "Create Reserv. Entry" - function CreateRemainingReservEntry

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12630]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 99000830 "Create Reserv. Entry" - function CreateRemainingReservEntry

    procedure CreateRemainingReservEntry(var OldReservEntry: Record "Reservation Entry"; RemainingQuantity: Decimal; RemainingQuantityBase: Decimal)
    var
        OldReservEntry2: Record "Reservation Entry";
        FromTracingSpecification: Record "Tracking Specification";
    begin
        // DINNL <<
        DINCreateRemainingReservEntryOnBeforeCreateReservEntryFor(OldReservEntry);
        // DINNL >>
        CreateReservEntryFor(
          OldReservEntry."Source Type", OldReservEntry."Source Subtype",
          OldReservEntry."Source ID", OldReservEntry."Source Batch Name",
          OldReservEntry."Source Prod. Order Line", OldReservEntry."Source Ref. No.",
          OldReservEntry."Qty. per Unit of Measure", RemainingQuantity, RemainingQuantityBase,
          OldReservEntry);

    local procedure DINCreateRemainingReservEntryOnBeforeCreateReservEntryFor(var ReservationEntry: Record "Reservation Entry")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
