### ISSUE TITLE
[Event Request] Codeunit 99000830 "Create Reserv. Entry" - function CreateRemainingReservEntry

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12631]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 99000830 "Create Reserv. Entry" - function CreateRemainingReservEntry 

        if (OldReservEntry."Reservation Status" = OldReservEntry."Reservation Status"::Reservation) or
            (OldReservEntry."Reservation Status" = OldReservEntry."Reservation Status"::Tracking)
        then
            if OldReservEntry2.Get(OldReservEntry."Entry No.", not OldReservEntry.Positive) then begin // Get the related entry
                FromTracingSpecification.SetSourceFromReservEntry((OldReservEntry2));
                FromTracingSpecification."Qty. per Unit of Measure" := OldReservEntry2."Qty. per Unit of Measure";
                FromTracingSpecification.CopyTrackingFromReservEntry(OldReservEntry2);
                // DINNL <<
                DINCreateRemainingReservEntryOnBeforeCreateReservEntryFrom(OldReservEntry2);
                // DINNL >>
                CreateReservEntryFrom(FromTracingSpecification);
                InsertReservEntry2."Warranty Date" := OldReservEntry2."Warranty Date";
                InsertReservEntry2."Expiration Date" := OldReservEntry2."Expiration Date";
                OnBeforeCreateRemainingNonSurplusReservEntry(InsertReservEntry2, OldReservEntry2);
            end;

    local procedure DINCreateRemainingReservEntryOnBeforeCreateReservEntryFrom(var ReservationEntry: Record "Reservation Entry")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
