### ISSUE TITLE
[Event Request] Codeunit 99000830 "Create Reserv. Entry" - function CreateWhseItemTrkgLines

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12636]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 99000830 "Create Reserv. Entry" - CreateWhseItemTrkgLinesTransferReservEntry

    local procedure CreateWhseItemTrkgLines(ReservEntry: Record "Reservation Entry")
    var
        WhseShipmentLine: Record "Warehouse Shipment Line";
        WhseWkshLine: Record "Whse. Worksheet Line";
        ReservationEntry: Record "Reservation Entry";
        ItemTrackingSetup: Record "Item Tracking Setup";
        ItemTrkgMgt: Codeunit "Item Tracking Management";
        WhseItemTrkgQtyBase: Decimal;
        ReservEntryQtyBase: Decimal;
    begin
        with WhseShipmentLine do begin
            // DINNL <<
            DINOnBeforeCreateWhseItemTrkgLines(ReservEntry);
            // DINNL >>
            SetSourceFilter(
              ReservEntry."Source Type", ReservEntry."Source Subtype", ReservEntry."Source ID", ReservEntry."Source Ref. No.", true);
            if not FindFirst() then
                exit;

    local procedure DINOnBeforeCreateWhseItemTrkgLines(ReservEntry: Record "Reservation Entry")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
