### ISSUE TITLE
Need to set GlobalVarAccess = TRUE

### ISSUE THREAD

**Issue by Rama-M** [Microsoft/ALAppExtensions#1263]
Can All Integration Type Event's property to be changed so that GlobalVarAccess = TRUE.  Can this be a default setting for all new and future event creations.

**Comment by JesperSchulz** [comment]
No, this we cannot do, as that would mean that changing a global variable would be a breaking change going forward. Please be more specific about the issue you would like to address, and we will take a look at your requests one by one.

**Comment by Rama-M** [comment]
Jasper, This is a generic request to have better scope to interact and manipulate global variables in the event publishing codeunits.  If this is implemented, it will lead to less direct code change to manipulate global variables as you can access them in the event subscripting codeunit.
