### ISSUE TITLE
Move code to function Codeunit 99000773 Calculate Prod. Order; Function TransferRouting

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#12632]
Hi,
in #229 i requested to have some code moved to new global functions. 
The code inside the repeat of function TransferRouting of codeunit 99000773 "Calculate Prod. Order" still wasn´t moved to a new function. We really need this. For now we duplicated the code, that however has some huge disadvantages especially with the Publishers in the code, wich will now be skipped for other apps.

kind regards,
Lennart

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
