### ISSUE TITLE
[Code Refactoring] CU 6620 - InitAndCheckSalesDocuments

### ISSUE THREAD

**Issue by jacmax** [microsoft/ALAppExtensions#12638]
Hello,
In the InitAndCheckSalesDocuments procedure is variable FromDocType2
The line where the value is assigned is below the OnBeforeInitAndCheckSalesDocuments procedure where the varable is used.
Is it possible to move the initialization line to the beginning of the procedure?

![obraz](https://user-images.githubusercontent.com/16525376/120384666-beab4100-c326-11eb-9704-e714c7ae8ae2.png)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
