### ISSUE TITLE
[Scope Change] Codeunit 81 PostAndSend

### ISSUE THREAD

**Issue by StephenNorfolk-DC** [microsoft/ALAppExtensions#12649]
Can PostAndSend on Codeunit 81 have the OnPrem flag removed?

We are currently having to use a manual event subscriber to set the PostAndSend flag in this codeunit to true, then using SalesPostYesNo.Run.
It would be easier (and use less objects) to be able to call SalesPostYesNo.PostAndSend directly, as all it does is set the PostAndSend flag to true.

We have bespoke document sending functionality that hooks into the standard solution, and we need to call this function.

**Comment by AlexanderYakunin** [comment]
Already done for Master
