### ISSUE TITLE
OnAfterCopyItemJnlFromStdJnl missing parameter

### ISSUE THREAD

**Issue by acicatech** [microsoft/ALAppExtensions#12646]
Event "OnAfterCopyItemJnlFromStdJnl" in Table 752 "Standard Item Journal" doesnt expose source table "Standard Item Journal" in order to pass custom fields to destination "Item Journal Line" table.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
