### ISSUE TITLE
Expose function FldRefHasValue in codeunit Error Message Management

### ISSUE THREAD

**Issue by daansaveyn** [microsoft/ALAppExtensions#12644]
Please expose the function **FldRefHasValue** in codeunit "Error Message Management" so it can be accessed by other extensions. Ideally, this function should be moved to the System App.

![image](https://user-images.githubusercontent.com/48217797/120439422-cc8eaf80-c382-11eb-84d6-eee739d0aa15.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
