### ISSUE TITLE
Surname in Contact table to 50

### ISSUE THREAD

**Issue by renevanbeekum** [microsoft/ALAppExtensions#12640]
Do you want to extend the length of the surname to 50, because the surnames in the Netherlands are getting longer and longer.

**Comment by AlexanderYakunin** [comment]
We cannot change field length, this is breaking change. Adding new field and obsoleting old one is large code change, probably not the optimal solution for this quite rare issue.

As surname is only used for composing Full name, you can make small extension to add field (like Surname 2) and update Full Name creation. 

If this is not possible, please create Idea, if this is really necessary and will be supported by many, we will plan this change.
