### ISSUE TITLE
[Scope Change] Codeunit 80 SendPostedDocumentRecord

### ISSUE THREAD

**Issue by StephenNorfolk-DC** [microsoft/ALAppExtensions#12648]
Can SendPostedDocumentRecord on Codeunit 80 have the OnPrem flag removed?

Currently have to copy the whole function out into a separate codeunit to use it in a cloud app. If there are subfunctions that use OnPrem functionality (such as SendToDisk on Document Sending Profile), can these be skipped or error if the environment IsSaaS?

We have bespoke document sending functionality that hooks into the standard solution, and we need to call this function.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
