### ISSUE TITLE
[Extensibility Bug] Table 5050 "OnBeforeIsUpdateNeeded" - IsUpdateNeeded

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/ALAppExtensions#12647]
Hello,

Its about Table Contact 5050

Sinds some versions there has been a fix around the **x**contact record, the **x**rec is not reliable through modify via code.
This is fixed in the base application 
![image](https://user-images.githubusercontent.com/48794854/120453035-f8b22c80-c392-11eb-8376-7550b8729041.png)
but the check IsUpdateNeeded does not make use of the ContactBeforeModify, this way the check in IsUpdateNeeded is faulty. 
and The event Publiser in IsUpdateNeeded

![image](https://user-images.githubusercontent.com/48794854/120453058-fea80d80-c392-11eb-891c-37a6addad6f5.png)
![image](https://user-images.githubusercontent.com/48794854/120453504-64949500-c393-11eb-8067-8326b9ee408c.png)
OnBeforeIsUpdateNeeded does also not make use of the new **x**rec (ContactBeforeModify), so our own fields that we check also come out false (because **x**contact is not different from the contact) the ContactBeforeModify contains the truth.

So its a event parameter change request, but its very possible also a bug because the IsUpdateNeeded wil not function well on modify called by code.

suggested solution:

![image](https://user-images.githubusercontent.com/48794854/120454279-074d1380-c394-11eb-94f6-b931cd6f4e13.png)

awaiting your answer

**Comment by hvandenborn** [comment]
See also the BC14 code
Here the the same check is done, but the Xrec itself is beeing used for the find.

![image](https://user-images.githubusercontent.com/48794854/120456824-40868300-c396-11eb-881e-d38461cc5a0b.png)
So in BC14 the IsUpdateNeeded in table 5050 works fine, but sinds the ContactBeforeModify, it does not work on modify through code.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
