### ISSUE TITLE
Enum request on table 7000002 - Cartera Doc. ESP Location

### ISSUE THREAD

**Issue by AlvaroRosadoP** [microsoft/ALAppExtensions#12655]
Hello,

I need an enum for the field 1 - "Type"

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
