### ISSUE TITLE
[Event Request] CU 79 "Sales-Post and Send" OnBeforeValidateElectronicFormat

### ISSUE THREAD

**Issue by StephenNorfolk-DC** [microsoft/ALAppExtensions#12651]
Can you add an OnBeforeValidateElectronicFormats with IsHandled to the function "ValidateElectronicFormats" in Codeunit 79 "Sales-Post and Send"?

Example below:

```
    local procedure ValidateElectronicFormats(DocumentSendingProfile: Record "Document Sending Profile")
    var
        ElectronicDocumentFormat: Record "Electronic Document Format";
    begin
        //<< NEW
        OnBeforeValidateElectronicFormats(SalesHeader,DocumentSendingProfile,IsHandled);
        if IsHandled then
            exit();
        //>> NEW

        if (DocumentSendingProfile."E-Mail" <> DocumentSendingProfile."E-Mail"::No) and
           (DocumentSendingProfile."E-Mail Attachment" <> DocumentSendingProfile."E-Mail Attachment"::PDF)
        then begin
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
