### ISSUE TITLE
[Enum Request] Table 90 BOM Component Field 3 "Type"

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#12658]
We need to be able to extend the options defined on Field "Type" in Table 90 BOM Comopnent. Can you implement this field as a ENUM?
Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
