### ISSUE TITLE
[Event Request] table 5468 "Picture Entity" OnAfterGetRecordRefFromFilter

### ISSUE THREAD

**Issue by B-Steijn** [microsoft/ALAppExtensions#12657]
Currently the procedure only checks the following tables: Customer, Item, Vendor, Employee & Contact.
We however would like to use the functionality on other tables as well and propose to add an event to the following procedure:

    local procedure GetRecordRefFromFilter(IDFilter: Text; var ParentRecordRef: RecordRef): Boolean
    var
        Customer: Record Customer;
        Item: Record Item;
        Vendor: Record Vendor;
        Employee: Record Employee;
        Contact: Record Contact;
        RecordFound: Boolean;
    begin
        Item.SetFilter(SystemId, IDFilter);
        if Item.FindFirst() then begin
            ParentRecordRef.GetTable(Item);
            RecordFound := true;
        end;

        Customer.SetFilter(SystemId, IDFilter);
        if Customer.FindFirst() then
            if not RecordFound then begin
                ParentRecordRef.GetTable(Customer);
                RecordFound := true;
            end else
                Error(MultipleParentsFoundErr);

        Vendor.SetFilter(SystemId, IDFilter);
        if Vendor.FindFirst() then
            if not RecordFound then begin
                ParentRecordRef.GetTable(Vendor);
                RecordFound := true;
            end else
                Error(MultipleParentsFoundErr);

        Employee.SetFilter(SystemId, IDFilter);
        if Employee.FindFirst() then
            if not RecordFound then begin
                ParentRecordRef.GetTable(Employee);
                RecordFound := true;
            end else
                Error(MultipleParentsFoundErr);

        Contact.SetFilter(SystemId, IDFilter);
        if Contact.FindFirst() then
            if not RecordFound then begin
                ParentRecordRef.GetTable(Contact);
                RecordFound := true;
            end else
                Error(MultipleParentsFoundErr);
        
        ***OnAfterGetRecordRefFromFilter(IDFilter: Text; var ParentRecordRef: RecordRef; var RecordFound )***
        exit(RecordFound);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
