### ISSUE TITLE
Use of function instead of double code in table Sales Header

### ISSUE THREAD

**Issue by rwe12345** [microsoft/ALAppExtensions#12656]
In table 36 "Sales Header" in the onvalidate of field "Sell-to Customer No." there is code which is the same as in the still available function InitFromContact in this table. This function is used in the onvalidate of "Sell-to Contact No.".

Please use this function instead of the code.

![image](https://user-images.githubusercontent.com/44321194/120624648-31203c00-c461-11eb-8c6a-c02f05d22fe5.png)

Below the current code and the  requested code
![image](https://user-images.githubusercontent.com/44321194/120625578-26b27200-c462-11eb-947d-6a21fc6e3584.png)

**Comment by AlexanderYakunin** [comment]
This function code differ from the code we have in field Sell-to Customer No. Procedure InitFromContact should be used in Contact fields, not in Customer fields. And you suggestion does not work properly and result in failing tests. Better keep this "as is".
