### ISSUE TITLE
[Event Request] Report 5754 - "Create Pick" - OnAfterIntegerOnPreDataItem

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12665]
Hi AL-Team,
can you please add the following Publisher with IncludeSender in Integer OnPreDataItem?

```
trigger OnPreDataItem()
            begin
                Clear(CreatePick);
                CreatePick.SetValues(
                  AssignedID, 0, SortPick, 1, MaxNoOfSourceDoc, MaxNoOfLines, PerZone,
                  DoNotFillQtytoHandle, BreakbulkFilter, PerBin);

                NEW >>>>
                OnAfterIntegerOnPreDataItem();
                NEW <<<<
            end;

[IntegrationEvent(true, false)]
    local procedure OnAfterIntegerOnPreDataItem()
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
