### ISSUE TITLE
[Access Request] Report 5754  - Create Pick - CU CreatePick protected

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12666]
Hi Al team,

I would like to access the following variable from the extension object

```
protected var
        CreatePick: Codeunit "Create Pick";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
