### ISSUE TITLE
[Event Request] Report 790 - "Calculate Inventory" - OnBeforeItemOnAfterGetRecord

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12664]
Hi AL-Team,
can you please add the following Publisher with IncludeSender in Item OnAfterGetRecord?

```
trigger OnAfterGetRecord()
            begin
                // NEW >>>>
                OnBeforeItemOnAfterGetRecord(Item);
                // NEW <<<<
                if not HideValidationDialog then
                    Window.Update;
                TempSKU.DeleteAll();
            end;

[IntegrationEvent(true, false)]
    local procedure OnBeforeItemOnAfterGetRecord(var Item: Record Item)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
