### ISSUE TITLE
[Event Request] Codeunit 5817"Undo Posting Management" - function UpdatePurchLine

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12671]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5817"Undo Posting Management" - function UpdatePurchLine

            // DINNL <<
            OnBeforeUpdatePurchline(PurchLine);
            // DINNL >>
            Modify;
            RevertPostedItemTracking(TempUndoneItemLedgEntry, "Expected Receipt Date");
            xPurchLine."Quantity (Base)" := 0;
            PurchLineReserve.VerifyQuantity(PurchLine, xPurchLine);

            UpdateWarehouseRequest(DATABASE::"Purchase Line", "Document Type".AsInteger(), "Document No.", "Location Code");

            OnAfterUpdatePurchline(PurchLine);

            
           local procedure OnBeforeUpdatePurchline(var PurchLine: Record "Purchase Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
