### ISSUE TITLE
[Event Request] Codeunit 5817"Undo Posting Management" - function RevertPostedItemTracking

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12673]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5817"Undo Posting Management" - function RevertPostedItemTracking

       with TempItemLedgEntry do
            if Find('-') then begin
                repeat
                    TrackingSpecification.Get("Entry No.");
                    if not TrackingIsATO(TrackingSpecification) then begin
                        ReservEntry.Init();
                        ReservEntry.TransferFields(TrackingSpecification);
                        ReservEntry.Validate("Quantity (Base)");
                        ReservEntry."Reservation Status" := ReservEntry."Reservation Status"::Surplus;
                        if ReservEntry.Positive then
                            ReservEntry."Expected Receipt Date" := AvailabilityDate
                        else
                            ReservEntry."Shipment Date" := AvailabilityDate;
                        ReservEntry."Entry No." := 0;
                        ReservEntry.UpdateItemTracking;
                        // DINNL <<
                        DINOnRevertPostedItemTrackingOnBeforeInsert(ReservEntry, TempItemLedgEntry);
                        // DINNL >>
                        ReservEntry.Insert();

                        TempReservEntry := ReservEntry;
                        TempReservEntry.Insert();
                    end;
                    TrackingSpecification.Delete();
                until Next() = 0;

    local procedure DINOnRevertPostedItemTrackingOnBeforeInsert(var ReservationEntry: Record "Reservation Entry"; TempItemLedgerEntry: Record "Item Ledger Entry" temporary)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
