### ISSUE TITLE
[Event Request] codeunit 5815 "Undo Sales Shipment Line". - Add parameter to function OnAfterInsertNewShipmentLine

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12679]
Dear ALAppExtensions Team,

Is it possible to add a parameter to function OnAfterInsertNewShipmentLine in codeunit 5815?

- OnAfterInsertNewShipmentLine(SalesShptLine, PostedWhseShptLine, PostedWhseShptLineFound, DocLineNo);
+ OnAfterInsertNewShipmentLine(SalesShptLine, PostedWhseShptLine, PostedWhseShptLineFound, DocLineNo, ItemShptEntryNo);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
