### ISSUE TITLE
[Event Request] Codeunit 5817"Undo Posting Management" - function UpdateSalesLine

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12672]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5817"Undo Posting Management" - function UpdateSalesLine

            // DINNL <<
            OnBeforeUpdateSalesLine(SalesLine);
            // DINNL >>
            Modify;
            RevertPostedItemTracking(TempUndoneItemLedgEntry, "Shipment Date");
            xSalesLine."Quantity (Base)" := 0;
            SalesLineReserve.VerifyQuantity(SalesLine, xSalesLine);

            UpdateWarehouseRequest(DATABASE::"Sales Line", "Document Type".AsInteger(), "Document No.", "Location Code");

            OnAfterUpdateSalesLine(SalesLine);

           local procedure OnBeforeUpdateSalesLine(var SalesLine: Record "Sales Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
