### ISSUE TITLE
[Enum Request] Page 5870 "BOM Structure" - Make ShowBy an Enum

### ISSUE THREAD

**Issue by mtaanquist** [microsoft/ALAppExtensions#12678]
In order to generate a BOM Structure for an Item Variant, we have extended the ShowBy option with another option, "Item Variant". In later versions of Business Central, this is not possible, and requires copying the entire page to a new object to make changes.

Changing it to an Enum would allow us to extend the page. All line numbers are for the AL file from BC18.0. Suggested changes:

```
Line 290
-       ShowBy: Option Item,Assembly,Production;
+       ShowBy: Enum "BOM Structure Show By";
```

Enum:
```
enum id "BOM Structure Show By"
{
    Extensible = true;

    value(0; Item) { }
    value(1; Assembly) { }
    value(2; Production) { } 
}
```

There needs to be a new public function where you can pass in the ShowBy-enum:
```
Line Number 314
    procedure SetShowBy(NewShowBy: Enum "BOM Structure Show By")
    begin
        ShowBy := NewShowBy;
    end;
```

To go along with this, the function RefreshPage should be updated to include an else-case:

```
Line Number 335
            ShowBy::Production:
                CalcBOMTree.GenerateTreeForProdLine(ProdOrderLine, Rec, 0);
            ShowBy::Assembly:
                CalcBOMTree.GenerateTreeForAsm(AsmHeader, Rec, 0);
+           else
+               OnRefreshPage(Item, ProdOrderLine, AsmHeader, Rec);
        end;
```

Please let me know if you have any questions to this, I'll be happy to answer them.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
