### ISSUE TITLE
[Event Request] Table 27 "Item" - OnBeforeReturnMfgItem

### ISSUE THREAD

**Issue by jbakach** [microsoft/ALAppExtensions#12675]
Hello,

original:

    **procedure IsMfgItem(): Boolean
    begin
        exit("Replenishment System" = "Replenishment System"::"Prod. Order");
    end;**

New:

**    procedure IsMfgItem()MfgItem: Boolean
    begin
       MfgItem := "Replenishment System" = "Replenishment System"::"Prod. Order";
        _OnBeforeReturnMfgItem(Rec,MfgItem);_
    end;**

**_	[IntegrationEvent(false,false)]
	local procedure OnBeforeReturnMfgItem(Rec: Record Item; var MfgItem: Boolean)
	begin
	end;_**

Thanks for your effort.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
