### ISSUE TITLE
[Event Request] Codeunit 5816 "Undo Return Receipt Line" - function UpdateOrderLine

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12677]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5816 - function UpdateOrderLine

    procedure UpdateOrderLine(ReturnRcptLine: Record "Return Receipt Line")
    var
        SalesLine: Record "Sales Line";
    begin
        with ReturnRcptLine do begin
            SalesLine.Get(SalesLine."Document Type"::"Return Order", "Return Order No.", "Return Order Line No.");
            // DINNL <<
            DINOnUpdateOrderLineOnBeforeUpdateSalesLine(ReturnRcptLine);
            // DINNL >>
            UndoPostingMgt.UpdateSalesLine(SalesLine, Quantity, "Quantity (Base)", TempGlobalItemLedgEntry);
            OnAfterUpdateSalesLine(ReturnRcptLine, SalesLine);
        end;
    end;

    local procedure DINOnUpdateOrderLineOnBeforeUpdateSalesLine(var ReturnRcptLine: Record "Return Receipt Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
