### ISSUE TITLE
Codeunit 5814 "Undo Return Shipment Line" - function UpdateOrderLine

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12684]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5814 - function UpdateOrderLine

    procedure UpdateOrderLine(ReturnShptLine: Record "Return Shipment Line")
    var
        PurchLine: Record "Purchase Line";
    begin
        with ReturnShptLine do begin
            PurchLine.Get(PurchLine."Document Type"::"Return Order", "Return Order No.", "Return Order Line No.");
            // DINNL <<
            DINOnUpdateOrderLineOnBeforeUpdatePurchLine(ReturnShptLine);
            // DINNL >>
            UndoPostingMgt.UpdatePurchLine(PurchLine, Quantity, "Quantity (Base)", TempGlobalItemLedgEntry);
            OnAfterUpdatePurchLine(PurchLine, ReturnShptLine);
        end;
    end;

    local procedure DINOnUpdateOrderLineOnBeforeUpdatePurchLine(var ReturnShptLine: Record "Return Shipment Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
