### ISSUE TITLE
[Event Request] Codeunit 5815 "Undo Sales Shipment Line" - function Code

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12680]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5815 "Undo Sales Shipment Line" - function Code

            Find('-');
            repeat
                // DINNL <<
                DINOnBeforeUndoSalesShipmentLine(SalesShptLine);
                // DINNL >>
                TempGlobalItemLedgEntry.Reset();

         
               local procedure DINOnBeforeUndoSalesShipmentLine(SalesShipmentLine: Record "Sales Shipment Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
