### ISSUE TITLE
Codeunit 5813 "Undo Purchase Receipt Line" - function UpdateOrderLine

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12685]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5814 - function UpdateOrderLine   

    procedure UpdateOrderLine(PurchRcptLine: Record "Purch. Rcpt. Line")
    var
        PurchLine: Record "Purchase Line";
    begin
        with PurchRcptLine do begin
            PurchLine.Get(PurchLine."Document Type"::Order, "Order No.", "Order Line No.");
            // DINNL <<
            DINOnUpdateOrderLineOnBeforeUpdatePurchLine(PurchRcptLine);
            // DINNL >>
            UndoPostingMgt.UpdatePurchLine(PurchLine, Quantity - "Quantity Invoiced", "Quantity (Base)" - "Qty. Invoiced (Base)", TempGlobalItemLedgEntry);
            UndoPostingMgt.UpdatePurchaseLineOverRcptQty(PurchLine, "Over-Receipt Quantity");
            OnAfterUpdateOrderLine(PurchRcptLine, PurchLine);
        end;
    end;

    local procedure DINOnUpdateOrderLineOnBeforeUpdatePurchLine(var PurchRcptLine: Record "Purch. Rcpt. Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
