### ISSUE TITLE
[Event Request] Codeunit 5815 "Undo Sales Shipment Line" - function UpdateOrderLine

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12683]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5815 - function UpdateOrderLine

    procedure UpdateOrderLine(SalesShptLine: Record "Sales Shipment Line")
    var
        SalesLine: Record "Sales Line";
    begin
        with SalesShptLine do begin
            // DINNL <<
            DINOnUpdateOrderLineOnBeforeUpdateSalesLine(SalesShptLine);
            // DINNL >>
            SalesLine.Get(SalesLine."Document Type"::Order, "Order No.", "Order Line No.");
            UndoPostingMgt.UpdateSalesLine(SalesLine, Quantity - "Quantity Invoiced", "Quantity (Base)" - "Qty. Invoiced (Base)", TempGlobalItemLedgEntry);
            OnAfterUpdateSalesLine(SalesLine, SalesShptLine);
        end;
    end;

    local procedure DINOnUpdateOrderLineOnBeforeUpdateSalesLine(var SalesShptLine: Record "Sales Shipment Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
