### ISSUE TITLE
Table 'Invoice Post. Buffer' is marked for removal.

### ISSUE THREAD

**Issue by sankarvinop** [microsoft/ALAppExtensions#12687]
Hi, I am using this table 49 Invoice Post. Buffer in my extension which is published in app source.
Now getting warning message as per below and its marked for removal.

Table 'Invoice Post. Buffer' is marked for removal. Reason: This table will be marked as temporary. Please ensure you do not store any data in the table.. Tag: 18.0.

Could you advice, What is the alternative for this table? any documentation available for this?

**Comment by mrabus** [comment]
Can you show us what you are doing with the table? (pseudo code is fine, too) 

From my point of view, the table will still be usable in future releases but I will not allow to write to SQL anymore. Maybe it would be better to avoid the obsoletion.

**Comment by sankarvinop** [comment]
As part of localization, we keep details of VAT Entry. For example, if Sales or purchase order got two lines with Type as Item. Once its invoiced, In standard , it will be combined as one Entry in VAT Entry table, where as in our table, we keep track of individual entry and additional information which need to keep it VAT Entry table also.

Caption is changed from VAT to GST
![image](https://user-images.githubusercontent.com/18752566/120927437-5dfb7a00-c713-11eb-827d-bf3b095e4c84.png)

GST Entry --> VAT Entry
GST Sale Entry --> Localization table
This GST Sales Entry and GST Entry will be linked as-well.

![image](https://user-images.githubusercontent.com/18752566/120927484-87b4a100-c713-11eb-9b43-75d0dd9a6533.png)


Additional fields like , FULL GST Based Amount. if Particular Purchase Line is FULL Vat then, we need to capture what is Base amount for that. It has to go all the way from Invoice Post. Buffer to VAT Entry.

>   [EventSubscriber(ObjectType::Table, database::"Gen. Journal Line", 'OnAfterCopyGenJnlLineFromInvPostBuffer', '', false, false)]
>     local procedure OnAfterCopyGenJnlLineFromInvPostBuffer(InvoicePostBuffer: Record "Invoice Post. Buffer"; VAR GenJournalLine: Record "Gen. Journal Line")
>     begin
>         GetGLSetup();
>         if not RecGLSetup.SGL_GSTReport_XXX then
>             EXIT;
>         GenJournalLine.Description := InvoicePostBuffer.SGL_PostDescr_XXX;
>         GenJournalLine.SGL_FullGSTBaseSGD_UOB := InvoicePostBuffer.SGL_FullGSTBaseSGD_XXX
>         GenJournalLine.SGL_PurcInvNo_UOB := InvoicePostBuffer.SGL_PurcInvNo_XXX;
>     end;
> 


For capturing detail entry below event and store it before its summarizing in standard by Items, or GL. in invoice posting buffer.

 [EventSubscriber(ObjectType::Codeunit, Codeunit::"Purch.-Post", 'OnAfterFillInvoicePostBuffer', '', true, false)]

**Comment by AlexanderYakunin** [comment]
Current Invoice Post. Buffer should be temporary table, so obsolete statement added to remind you than this variable should be always used with 'temporary'.

Going forward we will replace this implementation with interface to let you switch to your own implementation of invoice posting (depending on regulatory and tax requirements). It will be possible without change of primary key (this is limitation for current implementation).

**Comment by sankarvinop** [comment]
We are using temporary only.  
Noted on Interface method. Thanks.

**Comment by db-bc** [comment]
> Current Invoice Post. Buffer should be temporary table, so obsolete statement added to remind you than this variable should be always used with 'temporary'.

That is not the correct way to mark this. If the table is not obsolete, _don't mark it as such!!_

There is now a property on the table level for whether it must always be temporary, `TableType = Temporary`, and if set to `true` no table will be created in SQL, so no danger of writing to a real database by mistake:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-temporary-tables#setting-the-tabletype-to-temporary

If the user then forgets `temporary`, no matter, the table is **always** temporary.

Please consider using this instead of misusing the `Obsolete` properties for an unrelated purpose.
