### ISSUE TITLE
[Event Request] Codeunit 99000815 "Reservation-Check Date Confl".OnAfterDateConflict

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#12693]
Please add new paramater "ForceRequest".
``` 
   [IntegrationEvent(false, false)]
    local procedure OnAfterDateConflict(var ReservationEntry: Record "Reservation Entry"; var Date: Date; var IsConflict: Boolean; var ForceRequest: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
