### ISSUE TITLE
[Event Request] Codeunit 5531 "Calc. Inventory Page Data" - function UpdateInventory

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12695]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5531- function UpdateInventory   

    local procedure UpdateInventory(var InvtPageData: Record "Inventory Page Data"; var InvtEventBuf: Record "Inventory Event 
    Buffer")
    begin
        with InvtEventBuf do begin
            if "Action Message" <> "Action Message"::" " then
                InvtPageData."Suggested Projected Inventory" += "Remaining Quantity (Base)"
            else
                if Type = Type::Forecast then
                    InvtPageData."Forecasted Projected Inventory" += "Remaining Quantity (Base)"
                else
                    InvtPageData."Projected Inventory" += "Remaining Quantity (Base)";
            // DINNL <<
            OnAfterUpdateInventory(InvtPageData, InvtEventBuf);
            // DINNL >>
        end;
    end;

    local procedure OnAfterUpdateInventory(var InvtPageData: Record "Inventory Page Data"; var InvtEventBuf: Record "Inventory Event Buffer")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
