### ISSUE TITLE
[Event Request] Codeunit 5530 "Calc. Item Availability"- function GetAnticipatedDemand

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12698]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5530 "Calc. Item Availability"- function GetAnticipatedDemand

    local procedure GetAnticipatedDemand(var InvtEventBuf: Record "Inventory Event Buffer"; var Item: Record Item; ForecastName: Code[10]; ExcludeForecastBefore: Date; IncludeBlanketOrders: Boolean)
        begin
            if ForecastName <> '' then
                GetRemainingForecast(InvtEventBuf, Item, ForecastName, ExcludeForecastBefore);
            if IncludeBlanketOrders then
                GetBlanketSalesOrders(InvtEventBuf, Item);
            // DINNL <<
            OnAfterGetAnticipatedDemand(InvtEventBuf, Item, ForecastName, ExcludeForecastBefore, IncludeBlanketOrders, EntryNo);
            // DINNL >>
        end;

    local procedure OnAfterGetAnticipatedDemand(var InvtEventBuf: Record "Inventory Event Buffer"; var Item: Record Item; ForecastName: Code[10]; ExcludeForecastBefore: Date; IncludeBlanketOrders: Boolean; EntryNo: Integer)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
