### ISSUE TITLE
[Event Request] codeunit 5705 "TransferOrder-Post Receipt" - Add parameter to function OnBeforePostItemJournalLine

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12696]
Dear ALAppExtensions Team,

Is it possible to add a parameter to function OnBeforePostItemJournalLine in codeunit 5705?

-OnBeforePostItemJournalLine(ItemJnlLine, TransLine3, TransRcptHeader2, TransRcptLine2, SuppressCommit, TransLine);
+OnBeforePostItemJournalLine(ItemJnlLine, TransLine3, TransRcptHeader2, TransRcptLine2, SuppressCommit, TransLine, PostedWhseRcptHeader);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
