### ISSUE TITLE
[Event Request] codeunit 5531 "Calc. Inventory Page Data" - Add parameters to function OnAfterTransferToPeriodDetails

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12694]
Dear ALAppExtensions Team,

Is it possible to add 2 parameters to function OnAfterTransferToPeriodDetails in codeunit 5531?

-OnAfterTransferToPeriodDetails(InventoryPageData, FromInvtEventBuf);
+OnAfterTransferToPeriodDetails(InventoryPageData, FromInvtEventBuf, SourceType, SourceSubtype);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
