### ISSUE TITLE
[Event Request] Codeunit 5530 "Calc. Item Availability"- function TryGetQtyOnInventory

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12699]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5530 "Calc. Item Availability"- function TryGetQtyOnInventory

        ItemLedgEntry.SetRange("Variant Code", ItemLedgEntry."Variant Code");
        ItemLedgEntry.SetRange("Location Code", ItemLedgEntry."Location Code");

        if IncludeLocation then begin
            ItemLedgEntry.CalcSums("Remaining Quantity");
            if ItemLedgEntry."Remaining Quantity" <> 0 then begin
                InvtEventBuf.TransferInventoryQty(ItemLedgEntry);
                // DINNL <<
                OnTryGetQtyOnInventoryOnBeforeInsertEntry(InvtEventBuf, ItemLedgEntry);
                // DINNL >>
                InsertEntry(InvtEventBuf);
            end;
        end;

        ItemLedgEntry.Find('+');

    local procedure OnTryGetQtyOnInventoryOnBeforeInsertEntry(var InvtEventBuf: Record "Inventory Event Buffer"; var ItemLedgerEntry: Record "Item Ledger Entry")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
