### ISSUE TITLE
[Event Request] Codeunit 1202 "Import Payroll Transaction" - OnBeforeGetFileName

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#12703]
Hello, is it possible to  Tempblob as reference like this?
```   
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetFileName(var GenJournalLine: Record "Gen. Journal Line"; var TempBlob: Codeunit "Temp Blob"; DataExchDefCode: Code[20]; var FileName: Text)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
