### ISSUE TITLE
[Parameter Request] Table 5771 OnBeforeSetTableView

### ISSUE THREAD

**Issue by Bleika** [Microsoft/ALAppExtensions#1270]
Hi,

In order to make use of the 5771 record when applying filters, the Rec must also be exposed in this event.

Please make the following change to the Event declaration:

**BEFORE:**
LOCAL [IntegrationEvent] OnBeforeSetTableView(VAR WarehouseRequest : Record "Warehouse Request";VAR SalesHeader : Record "Sales Header";VAR SalesLine : Record "Sales Line";VAR PurchaseLine : Record "Purchase Line";VAR TransferLine : Record "Transfer Line"; VAR ServiceHeader : Record "Service Header"; VAR ServiceLine : Record "Service Line")

**AFTER:**
LOCAL [IntegrationEvent] OnBeforeSetTableView(VAR WarehouseRequest : Record "Warehouse Request";VAR SalesHeader : Record "Sales Header";VAR SalesLine : Record "Sales Line";VAR PurchaseLine : Record "Purchase Line";VAR TransferLine : Record "Transfer Line"; VAR ServiceHeader : Record "Service Header"; VAR ServiceLine : Record "Service Line"; **Rec : Record "Warehouse Source Filter"**)

**New publishing statement:**
OnBeforeSetTableView(WhseRequest,SalesHeader,SalesLine,PurchLine,TransLine,ServiceHeader,ServiceLine,**Rec**);

**Comment by FrankAuwers** [comment]
Also include the VAR PurchaseHeader: Record "Purchase Header" as a parameter. 
And add in the body the statement GetSourceBatch.SETTABLEVIEW(PurchHeader);
