### ISSUE TITLE
ChangeScope

### ISSUE THREAD

**Issue by Stefangur** [microsoft/ALAppExtensions#12704]
CU 905, Assembly Line Management
Procedure: ExplodeAsmList

-> Remove Scope 'onPrem' to be abel to call from an extension.

Reason: when the line is a BOM, it should be expoded

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
