### ISSUE TITLE
[Event Request] codeunit 442 "Sales-Post Prepayments" - Add parameters to function OnBeforePostCustomerEntry

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12702]
Dear ALAppExtensions Team,

Is it possible to add 2 parameters to function OnBeforePostCustomerEntry in codeunit 442 "Sales-Post Prepayments"

-OnBeforePostCustomerEntry(GenJnlLine, TotalPrepmtInvLineBuffer, TotalPrepmtInvLineBufferLCY, SuppressCommit);
+OnBeforePostCustomerEntry(GenJnlLine, TotalPrepmtInvLineBuffer, TotalPrepmtInvLineBufferLCY, SuppressCommit, SalesHeader, DocumentType);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
