### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line"- OnPostVATAfterInsertFullVAT

### ISSUE THREAD

**Issue by SteinleMossFeldhaus** [microsoft/ALAppExtensions#12708]
Hello!

In order to consistently work in the same context, we require sender to be included in the IntegrationEvent OnPostVATAfterInsertFullVAT(GenJnlLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; TaxDetail: Record "Tax Detail"; var NextConnectionNo: Integer; var AddCurrGLEntryVATAmt: Decimal; AddCurrencyCode: Code[10]; UseCurrFactorOnly: Boolean).

Thanks

**Comment by Oleg-Romashkov** [comment]
Hi,

There is no event with this name. Could you please verify the code for latest application version.

Rgds,
Oleg.

**Comment by SteinleMossFeldhaus** [comment]
Hi,

this event was mentioned in #11686 and accepted.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
