### ISSUE TITLE
[Bug] Codeunit 99000889 "AvailabilityManagement".CalcAvailableQty

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#12700]
If CalcAvailableQty is called from different object variable "CompanyInfo" is not initialized. 

``` 
procedure CalcAvailableQty(var OrderPromisingLine: Record "Order Promising Line"): Decimal
var
    GrossRequirement: Decimal;
    ScheduledReceipt: Decimal;
    AvailabilityDate: Date;
begin
    //---------------------------------------GetCompanyInfo:BEGIN
    GetCompanyInfo();
    //---------------------------------------GetCompanyInfo:END
    Item.Get(OrderPromisingLine."Item No.");
    Item.SetRange("Variant Filter", OrderPromisingLine."Variant Code");
    Item.SetRange("Location Filter", OrderPromisingLine."Location Code");
    Item.SetRange("Date Filter", 0D, OrderPromisingLine."Original Shipment Date");

    if OrderPromisingLine."Original Shipment Date" <> 0D then
        AvailabilityDate := OrderPromisingLine."Original Shipment Date"
    else
        AvailabilityDate := WorkDate;

    OrderPromisingLine."Unavailability Date" :=
      AvailToPromise.AdjustedEndingDate(
        CalcDate(CompanyInfo."Check-Avail. Period Calc.", AvailabilityDate), CompanyInfo."Check-Avail. Time Bucket");

    AvailToPromise.SetPromisingReqShipDate(OrderPromisingLine);
    exit(
      AvailToPromise.QtyAvailabletoPromise(
        Item, GrossRequirement, ScheduledReceipt, AvailabilityDate,
        CompanyInfo."Check-Avail. Time Bucket", CompanyInfo."Check-Avail. Period Calc."));
end;
```

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
