### ISSUE TITLE
[Event Modification] Codeunit 23 Item Jnl.-Post Batch - OnBeforeCheckLines

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#12714]
Hi, would it be possible to modify the event OnBeforeCheckLines in codeunit 23, procedure CheckLines, to add WindowsIsOpen parameter like this :

```
    local procedure CheckLines(var ItemJnlLine: Record "Item Journal Line")
    begin
        OnBeforeCheckLines(ItemJnlLine, WindowIsOpen );

        with ItemJnlLine do begin
            LineCount := 0;
            StartLineNo := "Line No.";
            repeat
                LineCount := LineCount + 1;
                if WindowIsOpen then
                    Window.Update(2, LineCount);
                CheckRecurringLine(ItemJnlLine);

```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckLines(var ItemJnlLine: Record "Item Journal Line", var WindowIsOpen: Boolean)
    begin
    end;

```
thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
