### ISSUE TITLE
[EventRequest] Page6510 Item Tracking Lines

### ISSUE THREAD

**Issue by Easystep2** [microsoft/ALAppExtensions#12711]
Create Indentical Function to create a new Serial No and Package No as with creating a new Lot No.

Functions Called 

1.  AssignNewSerialNo()
2.  AssignNewPackageNo()

And call them at the right places in the page

local procedure AssignNewLotNo()
    var
        IsHandled: Boolean;
    begin
        **OnBeforeAssignNewLotNo(Rec, IsHandled);**
        if IsHandled then
            exit;

        Item.TestField("Lot Nos.");
        Rec.Validate("Lot No.", NoSeriesMgt.GetNextNo(Item."Lot Nos.", WorkDate, true));
    end;

**Comment by Easystep2** [comment]
Alexander,

What does this status mean?

**Comment by AlexanderYakunin** [comment]
This is more than event request. We need to add business logic and few setup fields. basically this is new feature.

I also need more information about there we should add calls to AssignNewSerialNo and AssignNewPackageNo? And what is the purpose of AssignNewSerialNo, as we already have AssignSerialNo and AssignSerialNoBatch?

**Comment by Easystep2** [comment]
Hi Alexander, Its just I don't have any events to change the formatting of the Serial No and PAckage No. Like I have with the Lot No.

There its implemented calling a function with an event called CreateNewLotNo within the function AssignLotNo and some more, Can send you the object on how it should be, changes are very small and not creating new features, just making it extendible

**Comment by Easystep2** [comment]
[Item Tracking Lines.Page.al.zip](https://github.com/microsoft/ALAppExtensions/files/6637105/Item.Tracking.Lines.Page.al.zip)


I can imagine if you delay the Package No. part but the changes for the SerialNo are easy:-)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
