### ISSUE TITLE
[Access Request] Report 7390 - Whse. Calculate Inventory

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12710]
Hi Al team,

I would like to access the following variable from the extension object

```
protected var
        HideValidationDialog: Boolean;
        // NEW >>>>
        WhseJnlLine: Record "Warehouse Journal Line";
        NextLineNo: Integer;
        RegisteringDate: Date;
        Bin: Record Bin;
        Location: Record Location;
        WhseJnlBatch: Record "Warehouse Journal Batch";
        PhysInvtCountCode: Code[10];
        CycleSourceType: Option " ",Item,SKU;
        NextDocNo: Code[20];
        // NEW <<<<
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
