### ISSUE TITLE
[Event Modification] Codeunit 23 Item Jnl.-Post Batch - OnHandleRecurringLineOnBeforeItemJnlLine2Loop

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#12717]
Hi, would it be possible to modify the event OnHandleRecurringLineOnBeforeItemJnlLine2Loop in codeunit 23, procedure HandleRecurringLine, to add WindowIsOpen parameter like this :

```
        repeat
            OnHandleRecurringLineOnBeforeItemJnlLine2Loop(ItemJnlLine, ItemJnlLine2, WindowIsOpen);
            LineCount := LineCount + 1;
            if WindowIsOpen then begin
                Window.Update(5, LineCount);
                Window.Update(6, Round(LineCount / NoOfRecords * 10000, 1));

```
```
    [IntegrationEvent(false, false)]
    local procedure OnHandleRecurringLineOnBeforeItemJnlLine2Loop(var ItemJnlLine: Record "Item Journal Line"; var ItemJnlLine2: Record "Item Journal Line"; var WindowIsOpen : Boolean)
    begin
    end;

```
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
