### ISSUE TITLE
CU7000 "Sales Price Calc. Mgt." add OnBeforeServLinePriceExists and add the unchanged Record to OnAfterFind*LinePrice 

### ISSUE THREAD

**Issue by BenjaminHochstetter** [Microsoft/ALAppExtensions#1271]
Hello togehter, 

Please add `OnBeforeServLinePriceExists` to `CU7000 "Sales Price Calc. Mgt."`
`OnBeforeServLinePriceExists(ServHeader, ServLine, ShowAll, ExistsRet, Handled, TempSalesPrice);`

add the unchanged Record to OnAfterFind*LinePrice:
```
OnAfterFindSalesLinePrice(SalesLine, xSalesLine, SalesHeader,TempSalesPrice,ResPrice,CalledByFieldNo);
OnAfterFindServLinePrice(ServLine, xServLine, ServHeader,TempSalesPrice,ResPrice,ServCost,CalledByFieldNo);
```

**Comment by AlexanderYakunin** [comment]
We already have first event. 

There is no xSalesLine or xServLine in the code, please specify full change.

**Comment by AlexanderYakunin** [comment]
Closing as there is no response
