### ISSUE TITLE
[EventRequest] Table381 VAT Registration No. Format

### ISSUE THREAD

**Issue by Solmyr1982** [microsoft/ALAppExtensions#12712]
Hi,
In the NL localization, there is a function in table 381: CheckCompanyInfo.
We need to have an event at the beginning of this function:

        IsHandled := false;
        OnBeforeCheckCompany(VATRegNo, Number, IsHandled);
        if IsHandled then
            exit;

All other similar functions in this table (CheckCust, CheckVendor, CheckContact) do have this event, so it's logical to have this event in the CheckCompanyInfo as well.
Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
