### ISSUE TITLE
[Event Change] Report 492 - "Copy Purchase Document" - OnBeforeValidateIncludeHeader

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12718]
Hi AL-Team,

can you please add the variable PurchHeader and FromPurchHeader to the following Publisher?

```
[IntegrationEvent(false, false)]
    // NEW >>>>
    // local procedure OnBeforeValidateIncludeHeader(var DoIncludeHeader: Boolean; DocType: Option)
    local procedure OnBeforeValidateIncludeHeader(var DoIncludeHeader: Boolean; DocType: Option; PurchHeader: Record "Purchase Header"; FromPurchHeader: Record "Purchase Header")
    // NEW <<<<
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
