### ISSUE TITLE
[Event Request]Table 352 "Default Dimension" - OnUpdateCustGlobalDimCodeOnCaseElse

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#12729]
Request a new event in procedure UpdateCustGlobalDimCode in table 352 "Default Dimension":

```
local procedure UpdateCustGlobalDimCode(GlobalDimCodeNo: Integer; CustNo: Code[20]; NewDimValue: Code[20])
var
    Cust: Record Customer;
begin
    if Cust.Get(CustNo) then begin
        case GlobalDimCodeNo of
            1:
                Cust."Global Dimension 1 Code" := NewDimValue;
            2:
                Cust."Global Dimension 2 Code" := NewDimValue;
            //<NEW>
            else
                OnUpdateCustGlobalDimCodeOnCaseElse(GlobalDimCodeNo, GLAccNo, NewDimValue);
            //</NEW>
        end;
        Cust.Modify(true);
    end;
end;

//<NEW>
[IntegrationEvent(false, false)]
local procedure OnUpdateCustGlobalDimCodeOnCaseElse(GlobalDimCodeNo: Integer; GLAccNo: Code[20]; NewDimValue: Code[20])
begin
end;

```

**Comment by complord** [comment]
Realized later that this procedure is only called for Global Dimensions 1 and 2.  By using the DimMgt.DefaultDimOn... calls, this request is unnecessary.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
