### ISSUE TITLE
[Paramter request] - Codeunitt "Copy Document Mgt." - Event OnAfterInsertToSalesLine

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#12725]
Could you add NextLineNo as reference paramter to event OnAfterInsertToSalesLine?

OnCopySalesDocLineOnBeforeCopyThisLine(ToSalesHeader, ToSalesLine, FromSalesLine);
if CopyThisLine then begin
  OnBeforeInsertToSalesLine(ToSalesLine, FromSalesLine, FromSalesDocType.AsInteger(), RecalculateLines, ToSalesHeader, DocLineNo, NextLineNo);
            ToSalesLine.Insert();
            HandleAsmAttachedToSalesLine(ToSalesLine);
            IsHandled := false;
            OnCopySalesDocLineOnBeforeAutoReserve(ToSalesHeader, ToSalesLine, IsHandled);
            if not IsHandled then
                if ToSalesLine.Reserve = ToSalesLine.Reserve::Always then
                    ToSalesLine.AutoReserve();
            OnAfterInsertToSalesLine(ToSalesLine, FromSalesLine, RecalculateLines, DocLineNo, FromSalesDocType, FromSalesHeader,NextLineNo);
        end else
            LinesNotCopied := LinesNotCopied + 1;

        exit(CopyThisLine);

   --- Event
[IntegrationEvent(false, false)]`
  local procedure OnAfterInsertToSalesLine(var ToSalesLine: Record "Sales Line"; FromSalesLine: Record "Sales Line"; RecalculateLines: Boolean; DocLineNo: Integer; FromSalesDocType: Enum "Sales Document Type From"; FromSalesHeader: Record "Sales Header",var NextLineNo:Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
