### ISSUE TITLE
Breaking change [CommitBehavior] added to Preview Posting

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/ALAppExtensions#12726]
Apparently a relatively new feature [CommitBehavior] has been added to Gen. Jnl.-Post Preview in 18.1.26444.

This breaks our solution where relatively complex prevalidation procedures must be run in the same manner during posting preview as in ordinary posting.

As far as I can tell, the only reasonable way for us to log the issues encountered during the validation, is to commit the changes to the log table. How do we do this now, when we run into "Commit if prohibited in the current scope." ?

**Comment by SiholstMicrosoft** [comment]
We have added an integration event you can use to perform commits before the preview posting begins.
It is part of **codeunit 19 "Gen. Jnl.-Post Preview"** and has the following declaration:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeRunPreview(Subscriber: Variant; RecVar: Variant)
```

**Comment by AlexanderYakunin** [comment]
And please use temporary table for your logs, like we do in Posting Preview.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
