### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforeGetReturnRcptLineFromTrackingOrUpdateItemEntryRelation

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#12723]
Hi, would it be possible to modify the event OnBeforeGetReturnRcptLineFromTrackingOrUpdateItemEntryRelation in codeunit 80 in order to add the parameter TrackingSpecificationExists (Boolean) ?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
