### ISSUE TITLE
[Event Request] New IntegrationEvent in Codeunit 79 "Sales-Post and Send", function Code

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#12722]
Hello,

please insert new IntegrationEvent in Codeunit 79 "Sales-Post and Send", function Code
New Event "OnAfterConfirmPost" like in Codeunit Codeunit::"Sales-Post + Print" or "Sales-Post (Yes/No)"

    local procedure "Code"()
    var
        TempDocumentSendingProfile: Record "Document Sending Profile" temporary;
        SalesPost: Codeunit "Sales-Post";
        SalesPostYesNo: Codeunit "Sales-Post (Yes/No)";
        HideDialog: Boolean;
    begin
        HideDialog := false;

        OnBeforePostAndSend(SalesHeader, HideDialog, TempDocumentSendingProfile);
        if not HideDialog then
            with SalesHeader do
                case "Document Type" of
                    "Document Type"::Invoice,
                  "Document Type"::"Credit Memo",
                  "Document Type"::Order:
                        if not ConfirmPostAndSend(SalesHeader, TempDocumentSendingProfile) then
                            exit;
                    else
                        Error(NotSupportedDocumentTypeErr, "Document Type");
                end;
        // Start kvs.dde
        OnAfterConfirmPost(SalesHeader);
        // Stop kvs.dde
        TempDocumentSendingProfile.CheckElectronicSendingEnabled;
        ValidateElectronicFormats(TempDocumentSendingProfile);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
