### ISSUE TITLE
[Event Request] OnBeforeLogInStart in Codeunit 40 LogInManagement

### ISSUE THREAD

**Issue by crisnicolas** [Microsoft/ALAppExtensions#1273]
In Codeunit 40 LogInManagement there is a procedure called OnBeforeLogInStart() that I think was meant to be an IntegrationEvent, but it is not.
Please update the properties of this procedure to convert it into an event.

![image](https://user-images.githubusercontent.com/35073177/52947126-23207d00-3376-11e9-9805-b532a64300e6.png)

This image is from BC CU3, ES localization

**Comment by NKarolak** [comment]
Confirmed in DE BC 13.03
