### ISSUE TITLE
[Event Change] Report 292 - "Copy Sales Document" - OnBeforeValidateIncludeHeader

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12730]
Hi AL-Team,

can you please add IncludeSender to the following Publisher?

  ```
  // NEW >>>>
    // [IntegrationEvent(false, false)]
    [IntegrationEvent(true, false)]
    // NEW <<<<
    local procedure OnBeforeValidateIncludeHeader(var DoIncludeHeader: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
