### ISSUE TITLE
[External] Table 38 - IsApprovedForPosting

### ISSUE THREAD

**Issue by fvet** [Microsoft/ALAppExtensions#1274]
Please set function 'IsApprovedForPosting' to External in table 38 Purchase Header.

**Comment by mazhelez** [comment]
Hi, @fvet

The function in question is _internal_ and we are reluctant to expose internal functions as this pollutes the API unnecessarily.

Could you please provide us with more info on why you want to call `IsApprovedForPosting`?

**Comment by fvet** [comment]
We've extended the BC purchase documents with types 'Self-billing Invoice' and 'Self-billing Creditnote', with their custom posting codeunits. We've also duplicated the function below, to allow calling the custom posting codeunit. 

```
[External] SendToPosting(PostingCodeunitID : Integer)
IF NOT IsApprovedForPosting THEN
  EXIT;
CODEUNIT.RUN(PostingCodeunitID,Rec);
```

However, in our case, the posting codeunit is not called via Codeunit.RUN, but by using codeunit variables, allow to call some extra SetFunctions. 

```
IF NOT IsApprovedForPosting THEN // Function is not accessible
  EXIT;

WITH Rec DO BEGIN
  CASE "Document Type" OF
    "Document Type"::"Settlement Proposal Invoice" :
      BEGIN
        PostPrintSettlPropInv.Setxxx(TRUE);
        PostPrintSettlPropInv.RUN(Rec);
```

Since the procedure 'IsApprovedForPostingBatch' is set to external, it makes sense to set 'IsApprovedForPosting' to external as well.
