### ISSUE TITLE
Request to utilize the Send As or Send On Behalf functionality of SMTP email

### ISSUE THREAD

**Issue by IndubhusanGiri** [microsoft/ALAppExtensions#12768]
Hi,

As Organisation Send-As policy allow user to send as or send on behalf of a group.

For example, if Megan Bowen is part of the Training Microsoft 365 group, and has Send as permissions on the group, if she sends an email as the group, it will look like the Training group sent the email.

The Send on Behalf permission lets a user send email on behalf of a Microsoft 365 group. For example, if Alex Wilber is a part of the Marketing Microsoft 365 group, and has Send on Behalf permissions and sends an email as the group, the email looks like it was sent by Alex Wilber on behalf of Marketing.

The above functionality is not achievable by the new Enhanced email functionality (SMTP) as it always take the "From address" from the "Email Accounts" record depending upon  the "Email Scenario" or the default one.

I am expecting the same functionality to be available as Microsoft Exchange gives the feature. for more details:
[https://docs.microsoft.com/en-us/microsoft-365/solutions/allow-members-to-send-as-or-send-on-behalf-of-group?view=o365-worldwide](Microsoft 365)

**Comment by IhorHandziuk** [comment]
Hi @IndubhusanGiri, indeed, this sounds like a good idea, but I think this isn't really an extensibility request/defect, but rather a small feature request (normally to be logged on aka.ms/bcideas).

SMTP Connector is open-sourced here on GitHub, would you be interested in contributing code directly to introduce this functionality? 😊

**Comment by JesperSchulz** [comment]
Closing issue, as this isn't a extensibility request/defect. Please either log idea or submit a PR for us to process.
