### ISSUE TITLE
[Request for external] Codeunit 392 Reminder-Make - FilterCustLedgEntries and SetReminderLine

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#12763]
Hi, I was wondering if it would be possible to change the procedures FilterCustLedgEntries and SetReminderLine  Codeunit 392 from local to external.
My team and I use this procedure a lot in our code, and changing it to external would be a huge help.

Thanks for your work, have a nice day

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
