### ISSUE TITLE
[Event Request] Codeunit 5804 ItemCostManagement - OnBeforeUpdateStdCostShares

### ISSUE THREAD

**Issue by tdkumar** [microsoft/ALAppExtensions#12767]
Hi, 
Need an Event in Codeunit "ItemCostManagement", procedure "UpdateStdCostShares".
To calculate cost shares for different Lot Sizes in runtime and not to update default Item values.

procedure UpdateStdCostShares(FromItem: Record Item)
    var
        Item: Record Item;
**//New Event begin**
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateStdCostShares(FromItem, IsHandled);
        if IsHandled then
            exit;
**//New Event end**
        with FromItem do begin
            Item.Get("No.");
            Item.Validate("Standard Cost", "Standard Cost");
            Item."Single-Level Material Cost" := "Single-Level Material Cost";
            Item."Single-Level Capacity Cost" := "Single-Level Capacity Cost";
            Item."Single-Level Subcontrd. Cost" := "Single-Level Subcontrd. Cost";
            Item."Single-Level Cap. Ovhd Cost" := "Single-Level Cap. Ovhd Cost";
            Item."Single-Level Mfg. Ovhd Cost" := "Single-Level Mfg. Ovhd Cost";
            Item."Rolled-up Material Cost" := "Rolled-up Material Cost";
            Item."Rolled-up Capacity Cost" := "Rolled-up Capacity Cost";
            Item."Rolled-up Subcontracted Cost" := "Rolled-up Subcontracted Cost";
            Item."Rolled-up Mfg. Ovhd Cost" := "Rolled-up Mfg. Ovhd Cost";
            Item."Rolled-up Cap. Overhead Cost" := "Rolled-up Cap. Overhead Cost";
            Item."Last Unit Cost Calc. Date" := "Last Unit Cost Calc. Date";
            OnUpdateStdCostSharesOnAfterCopyCosts(Item, FromItem);
            Item.Modify();
        end;
    end;

New Event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateStdCostShares(var Item: Record Item; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
