### ISSUE TITLE
[Modify Event] - Report 7000082 Settle Docs. in Posted PO - OnBeforePostedDocOnPostDataItem

### ISSUE THREAD

**Issue by marpacca** [microsoft/ALAppExtensions#12762]
We need  modify event in report 7000082 "Settle Docs. in Posted PO":

LOCAL [IntegrationEvent] OnBeforePostedDocOnPostDataItem(VAR PostedDoc : Record "Posted Cartera Doc.";VAR PostedPmtOrd : Record "Posted Payment Order";VAR BankAccPostBuffer : Record "BG/PO Post. Buffer"; **var IsHandled: Boolean**)

And modify the code

            trigger OnPostDataItem()
            var
                VendLedgEntry2: Record "Vendor Ledger Entry";
                PostedDoc2: Record "Posted Cartera Doc.";
                IsHandled: Boolean;
            begin
                if (DocCount = 0) or (GroupAmount = 0) then begin
                    if DueOnly then
                        Error(Text1100003 + Text1100004);

                    Error(Text1100003 + Text1100005);
                end;

                **IsHandled := false;**
                OnBeforePostedDocOnPostDataItem(PostedDoc, PostedPmtOrd, BankAccPostBuffer**,IsHandled**);
                if **not IsHandled and** BankAccPostBuffer.Find('-') then
                    repeat
                        VendLedgEntry2.Get(BankAccPostBuffer."Entry No.");
                        PostedDoc2.Get(1, VendLedgEntry2."Entry No.");
                        PostedPmtOrd.Get(PostedDoc2."Bill Gr./Pmt. Order No.");
                        BankAcc.Get(PostedPmtOrd."Bank Account No.");
                        GenJnlLineNextNo := GenJnlLineNextNo + 10000;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
