### ISSUE TITLE
[Event Request] Table 5878 "Phys. Invt. Record Line"

### ISSUE THREAD

**Issue by Kirstein45** [microsoft/ALAppExtensions#12769]
To allow serial numbers with different quantity than 1, I need a publisher in trigger OnValidate from Field "Quantity":

Currently:
![image](https://user-images.githubusercontent.com/85668757/121480238-24ed2f00-c9cb-11eb-8c1e-b8c98484e7fb.png)

shall be:
![image](https://user-images.githubusercontent.com/85668757/121481239-3aaf2400-c9cc-11eb-833b-40027f5b4926.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
