### ISSUE TITLE
[Request for exernal] - Codeunit Activities Mgt. - Procedure SetFilterOverdueSalesInvoice

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#12775]
SetFilterOverdueSalesInvoice is onPrem. Can you remove this?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
