### ISSUE TITLE
[Event Request] codeunit 229 "Document-Print" - OnGetSalesOrderUsage

### ISSUE THREAD

**Issue by DominikWidmann** [microsoft/ALAppExtensions#12770]
Could you please add an Event "OnGetSalesOrderUsage" in the ELSE of the switch CASE of the procedure "GetSalesOrderUsage"?

In the closed issue #260 it was mentioned that this event was planned to be shipped...

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
