### ISSUE TITLE
[Event Request] codeunit 1006 "Copy Job" OnAfterCopyJobTaskDimensions

### ISSUE THREAD

**Issue by ddagsinghsingh** [microsoft/ALAppExtensions#12772]
Can you add an event OnAfterCopyJobTaskDimensions to the function "CopyJobTaskDimensions" in Codeunit 1006 "Copy Job"?

Example below:

```
    local procedure CopyJobTaskDimensions(SourceJobTask: Record "Job Task"; TargetJobTask: Record "Job Task")
    var
        DimensionManagement: Codeunit DimensionManagement;
    begin
        DimensionManagement.CopyJobTaskDimToJobTaskDim(SourceJobTask."Job No.",
          SourceJobTask."Job Task No.",
          TargetJobTask."Job No.",
          TargetJobTask."Job Task No.");
        //<< NEW
        
        OnAfterCopyJobTaskDimensions(SourceJobTask, TargetJobTask);
        //>> NEW
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
