### ISSUE TITLE
[Event Request] codeunit 5851 "Invt. Doc.-Post Shipment" - OnRun

### ISSUE THREAD

**Issue by robertoscaringella** [microsoft/ALAppExtensions#12779]
Hi,
this codeunit was released in BC18 without events, and in 18.1 have one event. See below this requests, because is very difficult customize without.

    trigger OnRun()
    var
        Item: Record Item;
        SourceCodeSetup: Record "Source Code Setup";
        InvtSetup: Record "Inventory Setup";
        InventoryPostingSetup: Record "Inventory Posting Setup";
        NoSeriesMgt: Codeunit NoSeriesManagement;
        UpdateAnalysisView: Codeunit "Update Analysis View";
        UpdateItemAnalysisView: Codeunit "Update Item Analysis View";
        InvtAdjmt: Codeunit "Inventory Adjustment";
        Window: Dialog;
        LineCount: Integer;
    begin
        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        OnBeforePostInvtShipmentDoc(Rec, SuppressCommit, HideProgressWindow);
        <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

        Rec.TestField("Document Type", "Document Type"::Shipment);

        InvtDocHeader := Rec;
        InvtDocHeader.SetHideValidationDialog(HideValidationDialog);

        with InvtDocHeader do begin
            >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            IsHandled := false;
            OnBeforeCheckMandatoryHeaderFields(InvtDocHeader, IsHandled);
            if not IsHandled then begin
            <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                InvtDocHeader.TestField("No.");
                InvtDocHeader.TestField("Posting Date");
            >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            end;
            OnAfterCheckMandatoryFields(InvtDocHeader);
            <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
            CheckDim();

            InvtDocLine.Reset();
            InvtDocLine.SetRange("Document Type", "Document Type");
            InvtDocLine.SetRange("Document No.", "No.");
            InvtDocLine.SetFilter(Quantity, '>0');
            >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            OnAfterInvtDocLineSetFilters(InvtDocLine,InvtDocHeader);
            <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
            if not InvtDocLine.Find('-') then
                Error(NothingToPostErr);

            GetLocation("Location Code");
            if Location."Require Pick" or Location."Require Shipment" then
                Error(WarehouseHandlingRequiredErr, "Location Code");

            >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            if not HideProgressWindow then begin
            <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                Window.Open('#1#################################\\' + PostingLinesMsg);

                Window.Update(1, StrSubstNo(PostingDocumentTxt, "No."));
            >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            end;
            <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

            SourceCodeSetup.Get();
            SourceCode := SourceCodeSetup."Invt. Shipment";
            InvtSetup.Get();
            InvtSetup.TestField("Posted Invt. Shipment Nos.");
            InventoryPostingSetup.SetRange("Location Code", "Location Code");
            if InventoryPostingSetup.IsEmpty() then
                error(InventoryPostingSetupMissingErr, "Location Code");

            if Status = Status::Open then begin
                CODEUNIT.Run(CODEUNIT::"Release Invt. Document", InvtDocHeader);
                Status := Status::Open;
                >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
                if not SuppressCommit then begin
                <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                    Modify();
                    Commit();
                >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
                end;
                IsHandled := false;
                OnReleaseSalesDocumentOnBeforeSetStatus(InvtDocHeader,InvtDocLine,IsHandled, SuppressCommit);
                
                if not IsHandled then
                <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                    Status := Status::Released;
            end;

            TestField(Status, Status::Released);

            NoSeriesLine.LockTable();
            if NoSeriesLine.FindLast() then;
            if InvtSetup."Automatic Cost Posting" then begin
                GLEntry.LockTable();
                if GLEntry.FindLast() then;
            end;

            // Insert shipment header
            InvtShptHeader.LockTable();
            InvtShptHeader.Init();
            >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            OnRunOnAfterInvtShptHeaderInit(InvtShptHeader, InvtDocHeader);
            <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
            InvtShptHeader."Location Code" := "Location Code";
            InvtShptHeader."Posting Date" := "Posting Date";
            InvtShptHeader."Document Date" := "Document Date";
            InvtShptHeader."Salesperson Code" := "Salesperson/Purchaser Code";
            InvtShptHeader."Shortcut Dimension 1 Code" := "Shortcut Dimension 1 Code";
            InvtShptHeader."Shortcut Dimension 2 Code" := "Shortcut Dimension 2 Code";
            InvtShptHeader."Shipment No." := "No.";
            InvtShptHeader."External Document No." := "External Document No.";
            InvtShptHeader."Gen. Bus. Posting Group" := "Gen. Bus. Posting Group";
            InvtShptHeader."No. Series" := InvtSetup."Posted Invt. Shipment Nos.";
            InvtShptHeader."No." :=
              NoSeriesMgt.GetNextNo(
                InvtSetup."Posted Invt. Shipment Nos.", "Posting Date", true);
            "Posting No." := InvtShptHeader."No.";
            InvtShptHeader."Posting Description" := "Posting Description";
            InvtShptHeader.Correction := Correction;
            InvtShptHeader."Dimension Set ID" := "Dimension Set ID";
            OnRunOnBeforeInvtShptHeaderInsert(InvtShptHeader, InvtDocHeader);
            InvtShptHeader.Insert();
            >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            OnRunOnAfterInvtShptHeaderInsert(InvtShptHeader, InvtDocHeader);
            <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

            if InvtSetup."Copy Comments to Invt. Doc." then
                CopyCommentLines(
                    "Inventory Comment Document Type"::"Inventory Shipment",
                    "Inventory Comment Document Type"::"Posted Inventory Shipment",
                    "No.", InvtShptHeader."No.");

            // Insert shipment lines
            LineCount := 0;
            InvtShptLine.LockTable();
            InvtDocLine.SetRange(Quantity);
            >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            OnAfterSetFiltersOnBeforeInvtDocLineInsert(InvtDocLine,InvtDocHeader);
            <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
            if InvtDocLine.Find('-') then
                repeat
                    LineCount := LineCount + 1;
                    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
                    if not HideProgressWindow then
                    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                      Window.Update(2, LineCount);

                    if InvtDocLine."Item No." <> '' then begin
                        Item.Get(InvtDocLine."Item No.");
                        Item.TestField(Blocked, false);
                    end;

                    InvtShptLine.Init();
                    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
                    OnRunOnAfterInvtShptLineInit(InvtShptLine, InvtDocLine, InvtShptHeader, InvtDocHeader);
                    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                    InvtShptLine."Document No." := InvtShptHeader."No.";
                    InvtShptLine."Posting Date" := InvtShptHeader."Posting Date";
                    InvtShptLine."Document Date" := InvtShptHeader."Document Date";
                    InvtShptLine."Line No." := InvtDocLine."Line No.";
                    InvtShptLine."Item No." := InvtDocLine."Item No.";
                    InvtShptLine.Description := InvtDocLine.Description;
                    InvtShptLine.Quantity := InvtDocLine.Quantity;
                    InvtShptLine."Unit Amount" := InvtDocLine."Unit Amount";
                    InvtShptLine."Unit Cost" := InvtDocLine."Unit Cost";
                    InvtShptLine.Amount := InvtDocLine.Amount;
                    InvtShptLine."Indirect Cost %" := InvtDocLine."Indirect Cost %";
                    InvtShptLine."Unit of Measure Code" := InvtDocLine."Unit of Measure Code";
                    InvtShptLine."Shortcut Dimension 1 Code" := InvtDocLine."Shortcut Dimension 1 Code";
                    InvtShptLine."Shortcut Dimension 2 Code" := InvtDocLine."Shortcut Dimension 2 Code";
                    InvtShptLine."Gen. Bus. Posting Group" := InvtDocLine."Gen. Bus. Posting Group";
                    InvtShptLine."Gen. Prod. Posting Group" := InvtDocLine."Gen. Prod. Posting Group";
                    InvtShptLine."Inventory Posting Group" := InvtDocLine."Inventory Posting Group";
                    InvtShptLine."Quantity (Base)" := InvtDocLine."Quantity (Base)";
                    InvtShptLine."Qty. per Unit of Measure" := InvtDocLine."Qty. per Unit of Measure";
                    InvtShptLine."Unit of Measure Code" := InvtDocLine."Unit of Measure Code";
                    InvtShptLine."Gross Weight" := InvtDocLine."Gross Weight";
                    InvtShptLine."Net Weight" := InvtDocLine."Net Weight";
                    InvtShptLine."Unit Volume" := InvtDocLine."Unit Volume";
                    InvtShptLine."Variant Code" := InvtDocLine."Variant Code";
                    InvtShptLine."Units per Parcel" := InvtDocLine."Units per Parcel";
                    InvtShptLine."Location Code" := InvtDocLine."Location Code";
                    InvtShptLine."Bin Code" := InvtDocLine."Bin Code";
                    InvtShptLine."Item Category Code" := InvtDocLine."Item Category Code";
                    InvtShptLine."FA No." := InvtDocLine."FA No.";
                    InvtShptLine."Depreciation Book Code" := InvtDocLine."Depreciation Book Code";
                    InvtShptLine."Applies-to Entry" := InvtDocLine."Applies-to Entry";
                    InvtShptLine."Applies-from Entry" := InvtDocLine."Applies-from Entry";
                    InvtShptLine."Reason Code" := InvtDocLine."Reason Code";
                    InvtShptLine."Dimension Set ID" := InvtDocLine."Dimension Set ID";
                    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
                    OnRunOnBeforeInvtShptLineInsert(InvtShptLine, InvtDocLine, InvtShptHeader, InvtDocHeader);
                    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                    InvtShptLine.Insert();
                    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
                    OnRunOnAfterInvtShptLineInsert(InvtShptLine, InvtDocLine, InvtShptHeader, InvtDocHeader);
                    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

                    PostItemJnlLine(InvtShptHeader, InvtShptLine);
                    ItemJnlPostLine.CollectValueEntryRelation(TempValueEntryRelation, InvtShptLine.RowID1());
                until InvtDocLine.Next() = 0;

            InvtSetup.Get();
            if InvtSetup."Automatic Cost Adjustment" <>
               InvtSetup."Automatic Cost Adjustment"::Never
            then begin
                InvtAdjmt.SetProperties(true, InvtSetup."Automatic Cost Posting");
                InvtAdjmt.MakeMultiLevelAdjmt();
            end;

            LockTable();
            Delete(true);

            InsertValueEntryRelation();
            >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            OnRunOnBeforeCommitPostInvtShptDoc(InvtDocHeader, InvtDocLine, InvtShptHeader, InvtShptLine, ItemJnlLine, SuppressCommit);
            if not SuppressCommit then
            <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                Commit();
            >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
            OnRunOnAfterCommitPostInvtShptDoc(InvtDocHeader, InvtDocLine, InvtShptHeader, InvtShptLine, ItemJnlLine, SuppressCommit);

            if not HideProgressWindow then
            <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                Window.Close();
        end;

        UpdateAnalysisView.UpdateAll(0, true);
        UpdateItemAnalysisView.UpdateAll(0, true);
        Rec := InvtDocHeader;
        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        OnBeforePostInvtShipmentDoc(Rec, InvtDocHeader, InvtDocLine, InvtShptHeader, InvtShptLine);
        <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    end;

Thank you,
Roberto.

**Comment by Stepanenko-Vadim** [comment]
Please keep it one-two events max per request, so that's easier to process.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
