### ISSUE TITLE
[Enum Request] table 27 - Item -  field "Price/Profit Calculation"

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12776]
Hi al-team,

can you change the data type of field 19 "Price/Profit Calculation" to an enum?

**Comment by AlexanderYakunin** [comment]
We already have this

enum 19 "Item Price Profit Calculation"
{
    Extensible = true;
    AssignmentCompatibility = true;

    value(0; "Profit=Price-Cost") { Caption = 'Profit=Price-Cost'; }
    value(1; "Price=Cost+Profit") { Caption = 'Price=Cost+Profit'; }
    value(2; "No Relationship") { Caption = 'No Relationship'; }
}
