### ISSUE TITLE
[Event Request] Table 458 "Overdue Approval Entry" - Function ShowRecord - OnBeforeShowRecord

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#12774]
Can you please add an event OnBeforeShowRecord to function ShowRecord in table "Overdue Approval Entry"?

The function could be a copy from table "Approval Entry", (requested earlier https://github.com/microsoft/ALAppExtensions/issues/9669)

```
    procedure ShowRecord()
    var
        RecRef: RecordRef;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeShowRecord(Rec, IsHandled);
        if IsHandled then
            exit;

        if not RecRef.Get("Record ID to Approve") then
            exit;
        RecRef.SetRecFilter;
        PageManagement.PageRun(RecRef);
    end;
```

**Comment by ajkauffmann** [comment]
Please add the line RecRef.SetRecFilter as well. Just the same as in table Approval Entry.

**Comment by CameliaPopescu** [comment]
Version to implement >= 18.1

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
