### ISSUE TITLE
[Event Request] codeunit 5851 "Invt. Doc.-Post Shipment" - PostItemJnlLine

### ISSUE THREAD

**Issue by robertoscaringella** [microsoft/ALAppExtensions#12786]
Hi, request this events...

    local procedure PostItemJnlLine(InvtShptHeader2: Record "Invt. Shipment Header"; InvtShptLine2: Record "Invt. Shipment Line")
    var
        TempHandlingSpecification: Record "Tracking Specification" temporary;
        OriginalQuantity: Decimal;
        OriginalQuantityBase: Decimal;
    begin
        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        IsHandled := false;
        OnBeforePostItemJnlLine(InvtShptHeader2, InvtShptLine2,IsHandled);

        if IsHandled then
        <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
            exit;

        ItemJnlLine.Init();
        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        OnPostItemJnlLineOnAfterItemJnlLineInit(ItemJnlLine,InvtShptHeader2, InvtShptLine2);
        <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        ItemJnlLine."Posting Date" := InvtShptHeader2."Posting Date";
        ItemJnlLine."Document Date" := InvtShptHeader2."Document Date";
        ItemJnlLine."Document No." := InvtShptHeader2."No.";
        ItemJnlLine."Document Type" := ItemJnlLine."Document Type"::"Inventory Shipment";
        ItemJnlLine."Document Line No." := InvtShptLine2."Line No.";
        ItemJnlLine."External Document No." := InvtShptHeader2."External Document No.";
        ItemJnlLine."Entry Type" := ItemJnlLine."Entry Type"::"Negative Adjmt.";
        ItemJnlLine."Item No." := InvtShptLine2."Item No.";
        ItemJnlLine.Description := InvtShptLine2.Description;
        ItemJnlLine."Shortcut Dimension 1 Code" := InvtShptLine2."Shortcut Dimension 1 Code";
        ItemJnlLine."Shortcut Dimension 2 Code" := InvtShptLine2."Shortcut Dimension 2 Code";
        ItemJnlLine."Location Code" := InvtShptHeader2."Location Code";

        if InvtShptHeader2.Correction then begin
            ItemJnlLine.Quantity := -InvtShptLine2.Quantity;
            ItemJnlLine."Invoiced Quantity" := -InvtShptLine2.Quantity;
            ItemJnlLine."Quantity (Base)" := -InvtShptLine2."Quantity (Base)";
            ItemJnlLine."Invoiced Qty. (Base)" := -InvtShptLine2."Quantity (Base)";
            ItemJnlLine.Amount := -InvtShptLine2.Amount;
        end
        else begin
            ItemJnlLine.Quantity := InvtShptLine2.Quantity;
            ItemJnlLine."Invoiced Quantity" := InvtShptLine2.Quantity;
            ItemJnlLine."Quantity (Base)" := InvtShptLine2."Quantity (Base)";
            ItemJnlLine."Invoiced Qty. (Base)" := InvtShptLine2."Quantity (Base)";
            ItemJnlLine.Amount := InvtShptLine2.Amount;
        end;
        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        OnAfterFillQuantityAmountItemJnlLine(ItemJnlLine, InvtShptHeader2, InvtShptLine2);
        <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

        ItemJnlLine."Unit Amount" := InvtShptLine2."Unit Amount";
        ItemJnlLine."Unit Cost" := InvtShptLine2."Unit Cost";
        ItemJnlLine."Indirect Cost %" := InvtShptLine2."Indirect Cost %";
        ItemJnlLine."Source Code" := SourceCode;
        ItemJnlLine."Gen. Bus. Posting Group" := InvtShptLine2."Gen. Bus. Posting Group";
        ItemJnlLine."Gen. Prod. Posting Group" := InvtShptLine2."Gen. Prod. Posting Group";
        ItemJnlLine."Inventory Posting Group" := InvtShptLine2."Inventory Posting Group";
        ItemJnlLine."Unit of Measure Code" := InvtShptLine2."Unit of Measure Code";
        ItemJnlLine."Qty. per Unit of Measure" := InvtShptLine2."Qty. per Unit of Measure";
        ItemJnlLine."Variant Code" := InvtShptLine2."Variant Code";
        ItemJnlLine."Item Category Code" := InvtShptLine2."Item Category Code";
        ItemJnlLine."Applies-to Entry" := InvtShptLine2."Applies-to Entry";
        ItemJnlLine."Applies-from Entry" := InvtShptLine2."Applies-from Entry";

        ItemJnlLine."Bin Code" := InvtShptLine2."Bin Code";
        ItemJnlLine."Dimension Set ID" := InvtShptLine2."Dimension Set ID";

        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        OnPostItemJnlLineOnBeforeTransferInvtDocToItemJnlLine(InvtDocLine, ItemJnlLine, InvtShptHeader2, InvtShptLine2);
        <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        ReserveInvtDocLine.TransferInvtDocToItemJnlLine(InvtDocLine, ItemJnlLine, ItemJnlLine.Quantity);

        OriginalQuantity := ItemJnlLine.Quantity;
        OriginalQuantityBase := ItemJnlLine."Quantity (Base)";
        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        OnPostItemJnlLineOnBeforePostRunWithCheckItemJnlLine(ItemJnlLine, InvtShptHeader2, InvtShptLine2,OriginalQuantity,OriginalQuantityBase);
        <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        ItemJnlPostLine.RunWithCheck(ItemJnlLine);

        ItemJnlPostLine.CollectTrackingSpecification(TempHandlingSpecification);
        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        OnPostItemJnlLineOnBeforePostWhseJnlLine(ItemJnlLine, OriginalQuantity, OriginalQuantityBase, TempHandlingSpecification);
        <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        PostWhseJnlLine(ItemJnlLine, OriginalQuantity, OriginalQuantityBase, TempHandlingSpecification);

        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        OnAfterPostItemJnlLine(ItemJnlLine, OriginalQuantity, OriginalQuantityBase, TempHandlingSpecification, InvtShptHeader2, InvtShptLine2);
        <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    end;

Thank you,
Roberto.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
