### ISSUE TITLE
[Event request] codeunit 12182 "Datifattura Export" - OnBeforeAddVatElement

### ISSUE THREAD

**Issue by VeronicaGoglia** [microsoft/ALAppExtensions#12783]
Hi AL-Team,
can you please add a new event in the method AddInvoiceAmountsData

//New Event
OnBeforeAddVatElement(VATReportLine, XMLDOMManagement, IsHandled);
if not isHandled then 
//New Event

if VATPostingSetup.Get(VATReportLine."VAT Bus. Posting Group", VATReportLine."VAT Prod. Posting Group") then begin
            // DatiIVA
            XMLDOMManagement.AddElement(DatiRiepilogoXmlNode, 'DatiIVA', '', '', DatiIVAXmlNode);
            XMLDOMManagement.AddElement(DatiIVAXmlNode, 'Imposta', FormatAmount(Abs(VATReportLine.Amount)), '', XmlNode);
            XMLDOMManagement.AddElement(DatiIVAXmlNode, 'Aliquota', FormatAmount(VATPostingSetup."VAT %"), '', XmlNode);

            if (VATReportLine.Amount = 0) or
               (VATPostingSetup."VAT Calculation Type" = VATPostingSetup."VAT Calculation Type"::"Reverse Charge VAT")
            then
                XMLDOMManagement.AddElement(DatiRiepilogoXmlNode, 'Natura', VATReportLine."VAT Transaction Nature", '', XmlNode);
        end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
