### ISSUE TITLE
[Event "IncludeSender = true" Request] Page 99000818 - Prod. Order Components - OnBeforeReserveComp

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#12795]
Dear ALAppExtensions team,

Through this issue we would like to request "IncludeSender = true" for event publisher OnBeforeReserveComp of Page 99000818 Prod. Order Components.  OnBeforeReserveComp then will get the following signature:
```al
    [IntegrationEvent(true, false)]
    local procedure OnBeforeReserveComp(var ProdOrderComp: Record "Prod. Order Component"; var xProdOrderComp: Record "Prod. Order Component"; var ReserveComp: Boolean)
    begin
    end;
```
This makes it possible to AutoReserve indepent from the Item.AutoReserve value.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
