### ISSUE TITLE
Event Request OBJECT Table 274 Bank Acc. Reconciliation Line

### ISSUE THREAD

**Issue by nitinnexon** [microsoft/ALAppExtensions#12799]
Can we have a new OnBeforeBankAccLedgerEntryPageRun trigger with function DisplayApplication on Table 274

**PROCEDURE DisplayApplication@2();**
    VAR
      PaymentApplication@1000 : Page 1292;
    BEGIN
      CASE "Statement Type" OF
        "Statement Type"::"Bank Reconciliation":
          CASE Type OF
            Type::"Bank Account Ledger Entry":
              BEGIN
                BankAccLedgEntry.RESET;
                BankAccLedgEntry.SETCURRENTKEY("Bank Account No.",Open);
                BankAccLedgEntry.SETRANGE("Bank Account No.","Bank Account No.");
                BankAccLedgEntry.SETRANGE(Open,TRUE);
                BankAccLedgEntry.SETRANGE(
                  "Statement Status",BankAccLedgEntry."Statement Status"::"Bank Acc. Entry Applied");
                BankAccLedgEntry.SETRANGE("Statement No.","Statement No.");
                IF "Applied Bank Acc. Ledger Entry" <> 0 THEN //HBSRP 2017-08-11
                  BankAccLedgEntry.SETRANGE("Entry No.","Applied Bank Acc. Ledger Entry")
                ELSE
                  BankAccLedgEntry.SETRANGE("Statement Line No.","Statement Line No.");
  	**OnBeforeBankAccLedgerEntryPageRun(); // New Event Required Here**
                PAGE.RUN(0,BankAccLedgEntry);
              END;
            Type::"Check Ledger Entry":…………………………

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
