### ISSUE TITLE
[Code Change Request] Codeunit 333 - "Req. Wksh.-Make Order" - GetCreatedDocumentBuffer

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12791]
Hi AL-team, 

a set function for the variable TempDocumentEntry already exists in the codeunit. Can you add an associated get function?
The Get function could look like this:

```
procedure GetCreatedDocumentBuffer(var TempDocumentEntryNew: Record "Document Entry" temporary)
    begin
        TempDocumentEntryNew.Copy(TempDocumentEntry, true);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
