### ISSUE TITLE
[Event Change] Codeunit 5763 "Whse.-Post Shipment" - OnBeforeSalesLineModify

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12794]
Hi AL-Team,

can you add the var parameter to WarehouseShipmentLine?

[IntegrationEvent(false, false)]
    // NEW >>>>
    // local procedure OnBeforeSalesLineModify(var SalesLine: Record "Sales Line"; WarehouseShipmentLine: Record "Warehouse Shipment Line"; var ModifyLine: Boolean; Invoice: Boolean)
    local procedure OnBeforeSalesLineModify(var SalesLine: Record "Sales Line"; var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var ModifyLine: Boolean; Invoice: Boolean)
    // NEW <<<<
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
