### ISSUE TITLE
[Scope Change Request] Table 900 - Assembly Header - ValidateDates

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#12796]
Dear ALAppExtensions team,

Can you please REMOVE the [Scope('OnPrem')] modifier from the Table 900 - Assembly Header - ValidateDates procedure:
```al
    // [Scope('OnPrem')] << PLEASE REMOVE SCOPE OnPrem which cannot be explained from the code
    procedure ValidateDates(FieldNumToCalculateFrom: Integer; DoNotValidateButJustAssign: Boolean)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
