### ISSUE TITLE
[Enum Request] Codeunit 5611 Procedure CalculateDeprAmount() --> [DeprMethod]

### ISSUE THREAD

**Issue by dharma534** [microsoft/ALAppExtensions#12793]
We want to extend [DeprMethod] option defined in Codeunit 5611 under procedure CalculateDeprAmount(). There is already enum with name "FA Depreciation Method" for table field[5612] **Depreciation Method** but [DeprMethod] in codeunit which is using totally different behavior.  
We need to execute **OnCalculateDeprAmountOnDeprMethodCaseLastEntry()** procedure based our custom DeprMethod::XXX value. As you see below code, there is no possibility to execute procedure **OnCalculateDeprAmountOnDeprMethodCaseLastEntry()** with our custom [DeprMethod] value
```
case DeprMethod of
                        DeprMethod::StraightLine:
                            Amount := CalcSLAmount;
                        DeprMethod::DB1:
                            Amount := CalcDB1Amount;
                        DeprMethod::DB2:
                            Amount := CalcDB2Amount;
                        DeprMethod::DB1SL,
                        DeprMethod::DB2SL:
                            Amount := CalcDBSLAmount;
                        DeprMethod::Manual:
                            Amount := 0;
                        DeprMethod::"User-Defined":
                            Amount := CalcUserDefinedAmount(UntilDate);
                        DeprMethod::BelowZero:
                            Amount := DepreciationCalc.CalcRounding(DeprBookCode, CalcBelowZeroAmount);
                        else
                            OnCalculateDeprAmountOnDeprMethodCaseLastEntry(
                                FADeprBook, BookValue, DeprBasis, DeprYears, DaysInFiscalYear, NumberOfDays, Amount, DateFromProjection, UntilDate);
                    end;
```

**Comment by AlexanderYakunin** [comment]
What exactly you are asking for? Should we add DeprMethod as parameter in event OnCalculateDeprAmountOnDeprMethodCaseLastEntry?

**Comment by dharma534** [comment]
No. I want to execute else part function **OnCalculateDeprAmountOnDeprMethodCaseLastEntry** based on **DeprMethod::JDB** (JDB is our localization value). if there is enum extensibility for option variable **[DeprMethod]** then we can assign our own value by extending [DeprMethod] & call else part. Our main requirement is Enum Request for **[DeprMethod]** option variable.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
