### ISSUE TITLE
Event request on OBJECT Report 1496 Suggest Bank Acc. Recon. Lines

### ISSUE THREAD

**Issue by nitinnexon** [microsoft/ALAppExtensions#12803]
Can we have a new event request as per subject line with the blow function?
LOCAL PROCEDURE EnterBankAccLine@2(VAR BankAccLedgEntry2@1000 : Record 271);
    BEGIN
      BankAccReconLine.INIT;
      BankAccReconLine."Statement Line No." := BankAccReconLine."Statement Line No." + 10000;
      BankAccReconLine."Transaction Date" := BankAccLedgEntry2."Posting Date";
      BankAccReconLine.Description := BankAccLedgEntry2.Description;
      BankAccReconLine."Document No." := BankAccLedgEntry2."Document No.";
      BankAccReconLine."Statement Amount" := BankAccLedgEntry2."Remaining Amount";
      BankAccReconLine."Applied Amount" := BankAccReconLine."Statement Amount";
      BankAccReconLine.Type := BankAccReconLine.Type::"Bank Account Ledger Entry";
      BankAccReconLine."Applied Entries" := 1;
      BankAccSetStmtNo.SetReconNo(BankAccLedgEntry2,BankAccReconLine,0);//HBSRP
New parameter required in the last.      
BankAccSetStmtNo.SetReconNo(BankAccLedgEntry2,BankAccReconLine,0);
**OnBeforeBankAccReconLineInsert()  // New Event required here**
      BankAccReconLine.INSERT;
    END

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by nitinnexon** [comment]
> Please always put the full detailed signature of the requested events and the parameters passed in the call.

Yes will do in future, thanks Oleg
