### ISSUE TITLE
Event request on OBJECT Report 1408 Bank Acc. Recon. – Test

### ISSUE THREAD

**Issue by nitinnexon** [microsoft/ALAppExtensions#12802]
{ 1210;2   ;DataItem;                    ;
               DataItemTable=Table274;
               DataItemTableView=SORTING(Bank Account No.,Statement No.,Statement Line No.);
               OnPreDataItem=BEGIN
                               CurrReport.CREATETOTALS("Statement Amount","Applied Amount",Difference);
                               TotalAmount := 0;
                               TotalAppliedAmount := 0;
                               TotalDiff := 0;
                               ErrorLabel := 1;
                             END;
                OnAfterGetRecord=BEGIN
                                  AppliedAmount := 0;
                                  ErrorLabel := 1;

                                  CASE Type OF
                                    Type::"Bank Account Ledger Entry":
                                      BEGIN
                                        IF "Bank Acc. Reconciliation"."Statement Type" =
                                           "Bank Acc. Reconciliation"."Statement Type"::"Bank Reconciliation"
                                        THEN BEGIN
                                          BankAccLedgEntry.SetFilterBankAccNoOpen("Bank Account No.");
                                          BankAccLedgEntry.SETRANGE(
                                            "Statement Status",BankAccLedgEntry."Statement Status"::"Bank Acc. Entry Applied");
                                          BankAccLedgEntry.SETRANGE("Statement No.","Statement No.");
                                          //HBSRP 2017-08-11 Start:
                                          IF "Bank Acc. Reconciliation Line"."Applied Bank Acc. Ledger Entry" <> 0 THEN
                                            BankAccLedgEntry.SETRANGE("Entry No.","Bank Acc. Reconciliation Line"."Applied Bank Acc. Ledger Entry")
                                          ELSE
                                          //HBSRP 2017-08-11 End:
                                            BankAccLedgEntry.SETRANGE("Statement Line No.","Statement Line No.");
**OnBeforeBankAccLedgEntryFind() // New Event required here.**
                                          IF BankAccLedgEntry.FIND('-') THEN
                                            REPEAT
                                              AppliedAmount := AppliedAmount + BankAccLedgEntry.Amount;
                                              VerifyCheckLedgerEntry(BankAccLedgEntry);
                                            UNTIL BankAccLedgEntry.NEXT = 0;
                                        END ELSE
                                          AppliedAmount := GetPaymentReconciliationAppliedAmount("Bank Acc. Reconciliation Line");
                                      END;
                                    Type::"Check Ledger Entry":
                                      BEGIN
                                        IF "Bank Acc. Reconciliation"."Statement Type" =
                                           "Bank Acc. Reconciliation"."Statement Type"::"Bank Reconciliation"
                                        THEN BEGIN
                                          CheckLedgEntry.SetFilterBankAccNoOpen("Bank Account No.");
                                          CheckLedgEntry.SETRANGE(
                                            "Statement Status",CheckLedgEntry."Statement Status"::"Check Entry Applied");
                                          CheckLedgEntry.SETRANGE("Statement No.","Statement No.");
                                          CheckLedgEntry.SETRANGE("Statement Line No.","Statement Line No.");
                                          IF CheckLedgEntry.FIND('-') THEN
                                            REPEAT
                                              AppliedAmount := AppliedAmount - CheckLedgEntry.Amount;
                                              BankAccLedgEntry.GET(CheckLedgEntry."Bank Account Ledger Entry No.");
                                              IF NOT BankAccLedgEntry.Open THEN
                                                AddError(
                                                  STRSUBSTNO(
                                                    TableValueWrongErr,
                                                    BankAccLedgEntry.FIELDCAPTION(Open),TRUE,
                                                    BankAccLedgEntry.TABLECAPTION,BankAccLedgEntry."Entry No."));
                                              IF BankAccLedgEntry."Statement Status" <> BankAccLedgEntry."Statement Status"::"Check Entry Applied" THEN
                                                AddError(
                                                  STRSUBSTNO(
                                                    TableValueWrongErr,
                                                    BankAccLedgEntry.FIELDCAPTION("Statement Status"),
                                                    BankAccLedgEntry."Statement Status"::"Check Entry Applied",
                                                    BankAccLedgEntry.TABLECAPTION,BankAccLedgEntry."Entry No."));
                                              IF BankAccLedgEntry."Statement No." <> '' THEN
                                                AddError(
                                                  STRSUBSTNO(
                                                    TableValueWrongErr,
                                                    BankAccLedgEntry.FIELDCAPTION("Statement No."),'',
                                                    BankAccLedgEntry.TABLECAPTION,BankAccLedgEntry."Entry No."));
                                              IF BankAccLedgEntry."Statement Line No." <> 0 THEN
                                                AddError(
                                                  STRSUBSTNO(
                                                    TableValueWrongErr,
                                                    BankAccLedgEntry.FIELDCAPTION("Statement Line No."),0,
                                                    BankAccLedgEntry.TABLECAPTION,BankAccLedgEntry."Entry No."));
                                            UNTIL CheckLedgEntry.NEXT = 0;
                                        END ELSE
                                          AppliedAmount := GetPaymentReconciliationAppliedAmount("Bank Acc. Reconciliation Line");
                                      END;
                                    Type::Difference:
                                      IF "Bank Acc. Reconciliation"."Statement Type" =
                                         "Bank Acc. Reconciliation"."Statement Type"::"Payment Application"
                                      THEN BEGIN
                                        AppliedAmount := "Applied Amount";
                                        TotalDiff := TotalDiff + ("Statement Amount" - "Applied Amount");
                                      END ELSE
                                        TotalDiff := TotalDiff + "Statement Amount";
                                  END;
		**OnBeforeRaiseAppliedError() // New event required here**
                                  IF ("Applied Amount" <> AppliedAmount)
                                    AND ("Bank Acc. Reconciliation Line"."Applied Bank Acc. Ledger Entry" = 0) // HBSRP
                                  THEN
                                    AddError(STRSUBSTNO(AmountWrongErr,FIELDCAPTION("Applied Amount"),AppliedAmount));
                                  TotalAmount := TotalAmount + "Statement Amount";
                                  TotalAppliedAmount := TotalAppliedAmount + AppliedAmount;

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
