### ISSUE TITLE
Event Request on OBJECT Table 274 Bank Acc. Reconciliation Line

### ISSUE THREAD

**Issue by nitinnexon** [microsoft/ALAppExtensions#12800]
Can we have a new event on function LOCAL PROCEDURE RemoveApplication@1(AppliedType@1000 : Option); as per below?

LOCAL PROCEDURE RemoveApplication@1(AppliedType@1000 : Option);
    BEGIN
      IF "Statement Type" = "Statement Type"::"Bank Reconciliation" THEN
        CASE AppliedType OF
          Type::"Bank Account Ledger Entry":
            BEGIN
              BankAccLedgEntry.RESET;
              BankAccLedgEntry.SETCURRENTKEY("Bank Account No.",Open);
              BankAccLedgEntry.SETRANGE("Bank Account No.","Bank Account No.");
              BankAccLedgEntry.SETRANGE(Open,TRUE);
              BankAccLedgEntry.SETRANGE(
                "Statement Status",BankAccLedgEntry."Statement Status"::"Bank Acc. Entry Applied");
              BankAccLedgEntry.SETRANGE("Statement No.","Statement No.");
              IF "Applied Bank Acc. Ledger Entry" <> 0 THEN //HBSRP 2017-08-11
                BankAccLedgEntry.SETRANGE("Entry No.","Applied Bank Acc. Ledger Entry")
              ELSE
                BankAccLedgEntry.SETRANGE("Statement Line No.","Statement Line No.");
  	**OnBeforeBankAccLedgerEntryLock(); // New Event Required Here**

              BankAccLedgEntry.LOCKTABLE;
              CheckLedgEntry.LOCKTABLE;
              IF BankAccLedgEntry.FIND('-') THEN

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
