### ISSUE TITLE
Event request on OBJECT Codeunit 370 Bank Acc. Reconciliation Post

### ISSUE THREAD

**Issue by nitinnexon** [microsoft/ALAppExtensions#12804]
Can we have a new event request in below function?

LOCAL PROCEDURE InitPost@2(BankAccRecon@1000 : Record 273);
    BEGIN
      WITH BankAccRecon DO
        CASE "Statement Type" OF
          "Statement Type"::"Bank Reconciliation":
            BEGIN
              TESTFIELD("Statement Date");
              CheckLinesMatchEndingBalance(BankAccRecon,Difference);
	**OnAfterMatchEndingBalance() // New Event required here**
              CheckBankLedgerEntriesApplAmount(BankAccRecon."Statement No."); 
            END;
          "Statement Type"::"Payment Application":
            BEGIN
              SourceCodeSetup.GET;
              SourceCode := SourceCodeSetup."Payment Reconciliation Journal";
              PostPaymentsOnly := "Post Payments Only";
            END;
        END;
    END;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
