### ISSUE TITLE
Event Request on OBJECT Page 381 Apply Bank Acc. Ledger Entries

### ISSUE THREAD

**Issue by nitinnexon** [microsoft/ALAppExtensions#12808]
Can we have a new event required based on below?

    PROCEDURE ToggleMatchedFilter@5(SetFilterOn@1000 : Boolean);
    BEGIN
      IF SetFilterOn THEN BEGIN
        SETRANGE("Statement Status","Statement Status"::Open);
        SETRANGE("Statement No.",'');
        **//SETRANGE("Statement Line No.",0); //HBSRP 2017-08-11**
      END ELSE
        RESET;
      CurrPage.UPDATE;
    END;

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.
