### ISSUE TITLE
Event Request on OBJECT Table 276 Bank Account Statement Line

### ISSUE THREAD

**Issue by nitinnexon** [microsoft/ALAppExtensions#12801]
Can we have a new event on     LOCAL PROCEDURE DisplayApplication@1(); as per below position

    LOCAL PROCEDURE DisplayApplication@1();
    BEGIN
      CASE Type OF
        Type::"Bank Account Ledger Entry":
          BEGIN
            BankAccLedgEntry.RESET;
            BankAccLedgEntry.SETCURRENTKEY("Bank Account No.",Open);
            BankAccLedgEntry.SETRANGE("Bank Account No.","Bank Account No.");
            BankAccLedgEntry.SETRANGE(Open,FALSE);
            BankAccLedgEntry.SETRANGE("Statement Status",BankAccLedgEntry."Statement Status"::Closed);
            BankAccLedgEntry.SETRANGE("Statement No.","Statement No.");
            IF "Applied Bank Acc. Ledger Entry" <> 0 THEN //HBSRP 2017-08-11:
              BankAccLedgEntry.SETRANGE("Entry No.","Applied Bank Acc. Ledger Entry")
            ELSE
              BankAccLedgEntry.SETRANGE("Statement Line No.","Statement Line No.");
  	**OnBeforeBankAccLedgerEntryPageRun (); // New Event Required Here**
            PAGE.RUN(0,BankAccLedgEntry);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
