### ISSUE TITLE
[Event Request] Report 1003 - Post Invt. Cost to G/L - Test - OnAfterOnPreDataItem

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12809]
Hi AL-Team,

can you please add the following Publisher to PostValueEntryToGL OnPreDataItem? The event already exisits. 

```
trigger OnPreDataItem()
                begin
                    InvtPost.SetRunOnlyCheck(false, true, true);
                    TempCapValueEntry.DeleteAll;
                    // NEW >>>>
                    OnAfterOnPreDataItem(PostValueEntryToGL, CompanyName)
                    // NEW <<<<
                end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
