### ISSUE TITLE
Event request on OBJECT Codeunit 1252 Match Bank Rec. Lines

### ISSUE THREAD

**Issue by nitinnexon** [microsoft/ALAppExtensions#12807]
Can we have a new event request as per below?
    PROCEDURE MatchManually@1(VAR SelectedBankAccReconciliationLine@1004 : Record 274;VAR SelectedBankAccountLedgerEntry@1003 : Record 271);
    VAR
      BankAccReconciliationLine@1006 : Record 274;
      BankAccountLedgerEntry@1002 : Record 271;
      BankAccEntrySetReconNo@1000 : Codeunit 375;
    BEGIN
**OnBeforeBankRecoLineGet() // New Event required here**
      //HBSRP 2017-08-11:START
      CASE TRUE OF
        (SelectedBankAccReconciliationLine.COUNT = 1) AND (SelectedBankAccountLedgerEntry.COUNT >= 1),
        (SelectedBankAccReconciliationLine.COUNT = 1) AND (SelectedBankAccountLedgerEntry.COUNT = 1): // One-to-Many or One-to-One
          BEGIN
            IF SelectedBankAccountLedgerEntry.FINDSET THEN
              REPEAT
                BankAccReconciliationLine.GET(
                  SelectedBankAccReconciliationLine."Statement Type",
                  SelectedBankAccReconciliationLine."Bank Account No.",
                  SelectedBankAccReconciliationLine."Statement No.",
                  SelectedBankAccReconciliationLine."Statement Line No.");

                IF BankAccReconciliationLine.Type = BankAccReconciliationLine.Type::"Bank Account Ledger Entry" THEN BEGIN
                  BankAccountLedgerEntry.GET(SelectedBankAccountLedgerEntry."Entry No.");
                  BankAccEntrySetReconNo.RemoveApplication(BankAccountLedgerEntry);
                  BankAccEntrySetReconNo.ApplyEntries(BankAccReconciliationLine,BankAccountLedgerEntry,Relation::"One-to-Many");
                END;
              UNTIL SelectedBankAccountLedgerEntry.NEXT = 0;
          END;
**OnBeforeSelectBankRecRecoLine() // new event required here.**
        (SelectedBankAccReconciliationLine.COUNT > 1) AND (SelectedBankAccountLedgerEntry.COUNT = 1): // Many-to-One
          BEGIN

            IF SelectedBankAccReconciliationLine.FINDSET THEN
              REPEAT
                BankAccReconciliationLine.GET(
                SelectedBankAccReconciliationLine."Statement Type",
                SelectedBankAccReconciliationLine."Bank Account No.",
                SelectedBankAccReconciliationLine."Statement No.",
                SelectedBankAccReconciliationLine."Statement Line No.");

                IF BankAccReconciliationLine.Type = BankAccReconciliationLine.Type::"Bank Account Ledger Entry" THEN BEGIN
                  BankAccountLedgerEntry.GET(SelectedBankAccountLedgerEntry."Entry No.");
                  //BankAccEntrySetReconNo.RemoveApplication(BankAccountLedgerEntry);
                  BankAccEntrySetReconNo.ApplyEntries(BankAccReconciliationLine,BankAccountLedgerEntry,Relation::"Many-to-One");
                END;
              UNTIL SelectedBankAccReconciliationLine.NEXT = 0;

            BankAccountLedgerEntry."Statement Status" :=
              BankAccountLedgerEntry."Statement Status"::"Bank Acc. Entry Applied";
            BankAccountLedgerEntry."Statement No." := SelectedBankAccReconciliationLine."Statement No.";
            BankAccountLedgerEntry.MODIFY;
          END;
      END;

    PROCEDURE RemoveMatch@2(VAR SelectedBankAccReconciliationLine@1001 : Record 274;VAR SelectedBankAccountLedgerEntry@1000 : Record 271);
    VAR
      BankAccReconciliationLine@1004 : Record 274;
      BankAccountLedgerEntry@1003 : Record 271;
      BankAccEntrySetReconNo@1002 : Codeunit 375;
    BEGIN
      IF SelectedBankAccReconciliationLine.FINDSET THEN
        REPEAT
          BankAccReconciliationLine.GET(
            SelectedBankAccReconciliationLine."Statement Type",
            SelectedBankAccReconciliationLine."Bank Account No.",
            SelectedBankAccReconciliationLine."Statement No.",
            SelectedBankAccReconciliationLine."Statement Line No.");
          BankAccountLedgerEntry.SETRANGE("Bank Account No.",BankAccReconciliationLine."Bank Account No.");
          BankAccountLedgerEntry.SETRANGE("Statement No.",BankAccReconciliationLine."Statement No.");
         **OnBeforeBankAccLedfindset() // New event required here**
          IF SelectedBankAccReconciliationLine."Applied Bank Acc. Ledger Entry" <> 0 THEN //HBSRP
            BankAccountLedgerEntry.SETRANGE("Entry No.",SelectedBankAccReconciliationLine."Applied Bank Acc. Ledger Entry")
          ELSE
            BankAccountLedgerEntry.SETRANGE("Statement Line No.",BankAccReconciliationLine."Statement Line No.");
          BankAccountLedgerEntry.SETRANGE(Open,TRUE);
          BankAccountLedgerEntry.SETRANGE("Statement Status",BankAccountLedgerEntry."Statement Status"::"Bank Acc. Entry Applied");
          IF BankAccountLedgerEntry.FINDSET THEN
            REPEAT
              BankAccEntrySetReconNo.RemoveApplication(BankAccountLedgerEntry);
            UNTIL BankAccountLedgerEntry.NEXT = 0;
        UNTIL SelectedBankAccReconciliationLine.NEXT = 0;

      IF SelectedBankAccountLedgerEntry.FINDSET THEN
        REPEAT
          BankAccountLedgerEntry.GET(SelectedBankAccountLedgerEntry."Entry No.");
          BankAccEntrySetReconNo.RemoveApplication(BankAccountLedgerEntry);
        UNTIL SelectedBankAccountLedgerEntry.NEXT = 0;
    END;

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.

Events without parameters seem meaningless.
