### ISSUE TITLE
Event Request on OBJECT Codeunit 375 Bank Acc. Entry Set Recon.-No.

### ISSUE THREAD

**Issue by nitinnexon** [microsoft/ALAppExtensions#12806]
Can we have a new parameter in below functions?

Please Add one more option in the parameter as per mark RED
    PROCEDURE ApplyEntries@1(VAR BankAccReconLine@1000 : Record 274;VAR BankAccLedgEntry@1001 : Record 271;Relation@1002 : 'One-to-One,One-to-Many,**Many-to-One**') : Boolean;

    PROCEDURE ApplyEntries@1(VAR BankAccReconLine@1000 : Record 274;VAR BankAccLedgEntry@1001 : Record 271;Relation@1002 : 'One-to-One,One-to-Many,Many-to-One') : Boolean;
    BEGIN
      BankAccLedgEntry.LOCKTABLE;
      CheckLedgEntry.LOCKTABLE;
      BankAccReconLine.LOCKTABLE;
      BankAccReconLine.FIND;

      IF BankAccLedgEntry.IsApplied THEN
        EXIT(FALSE);

      IF (Relation = Relation::"One-to-One") AND (BankAccReconLine."Applied Entries" > 0) THEN
        EXIT(FALSE);

      CASE Relation OF
        Relation::"One-to-One",Relation::"One-to-Many":
          BEGIN
            BankAccReconLine.TESTFIELD(Type,BankAccReconLine.Type::"Bank Account Ledger Entry");
            BankAccReconLine."Ready for Application" := TRUE;
            SetReconNo(BankAccLedgEntry,BankAccReconLine,Relation);
            BankAccReconLine."Applied Amount" += BankAccLedgEntry."Remaining Amount";
            BankAccReconLine."Applied Entries" := BankAccReconLine."Applied Entries" + 1;
            BankAccReconLine.VALIDATE("Statement Amount");
            BankAccReconLine.MODIFY;
          END;
**OnCaseManytoOne() // new event required here**
        Relation::"Many-to-One":
          BEGIN
            BankAccReconLine.TESTFIELD(Type,BankAccReconLine.Type::"Bank Account Ledger Entry");
            BankAccReconLine."Ready for Application" := TRUE;
            SetReconNo(BankAccLedgEntry,BankAccReconLine,Relation);
            BankAccReconLine."Applied Amount" := BankAccReconLine."Statement Amount";
            BankAccReconLine."Applied Entries" := BankAccReconLine."Applied Entries" + 1;
            BankAccReconLine.VALIDATE("Statement Amount");
            BankAccReconLine.MODIFY;
          END;
      END;

      EXIT(TRUE);
    END;

    **PROCEDURE RemoveApplication@4(VAR BankAccLedgEntry@1001 : Record 271);**
    VAR
      BankAccReconLine@1000 : Record 274;
      BankAccReconLine2@1000000002 : Record 274;
      BankAccLedgEntry2@1000000001 : Record 271;
      BankAccLedgEntrySave@1000000000 : Record 271;
    BEGIN
      BankAccLedgEntrySave := BankAccLedgEntry;
**OnBeforeRemoveApplication() // New event required here.**
      BankAccLedgEntry.LOCKTABLE;
      CheckLedgEntry.LOCKTABLE;
      BankAccReconLine.LOCKTABLE;
**OnBeforeCheckManytoOne() // New event required here.**
 IF (BankAccLedgEntry."Statement Line No." = 0) AND (BankAccLedgEntry."Statement No." <> '') THEN BEGIN // CAREPOINT1.00 Many-to-one
        BankAccReconLine.SETRANGE("Statement Type",BankAccReconLine."Statement Type"::"Bank Reconciliation");
        BankAccReconLine.SETRANGE("Statement No.",BankAccLedgEntry."Statement No.");
        BankAccReconLine.SETRANGE("Applied Bank Acc. Ledger Entry",BankAccLedgEntry."Entry No.");
        IF BankAccReconLine.ISEMPTY THEN
          EXIT;
      END ELSE BEGIN
        IF NOT BankAccReconLine.GET(
          BankAccReconLine."Statement Type"::"Bank Reconciliation",
          BankAccLedgEntry."Bank Account No.",
          BankAccLedgEntry."Statement No.",BankAccLedgEntry."Statement Line No.")
        THEN
          EXIT;
       **OnbeforeBankAccReconLineSetRecFilters() // New event required here**
        BankAccReconLine.SETRECFILTER;
      END;

      IF BankAccReconLine.FINDSET THEN REPEAT
        BankAccReconLine.TESTFIELD("Statement Type",BankAccReconLine."Statement Type"::"Bank Reconciliation");
        BankAccReconLine.TESTFIELD(Type,BankAccReconLine.Type::"Bank Account Ledger Entry");
        IF (BankAccLedgEntrySave."Statement Line No." = 0) AND (BankAccLedgEntrySave."Statement No." <> '') THEN
          BankAccReconLine."Applied Amount" := 0
        ELSE
          BankAccReconLine."Applied Amount" -= BankAccLedgEntry."Remaining Amount";
        BankAccLedgEntry2.GET(BankAccLedgEntry."Entry No.");
        IF BankAccLedgEntry2."Statement No." <> '' THEN
      **OnBeforeRemoveRconNo() // New event requird here**
          RemoveReconNo(BankAccLedgEntry,BankAccReconLine,TRUE);
        BankAccReconLine."Applied Bank Acc. Ledger Entry" := 0;
        BankAccReconLine."Applied Entries" := BankAccReconLine."Applied Entries" - 1;
        BankAccReconLine.VALIDATE("Statement Amount");
        BankAccReconLine.MODIFY;

**// Add new parameter in the SetReconNo function in the last**
    **PROCEDURE SetReconNo@2(VAR BankAccLedgEntry@1000 : Record 271;VAR BankAccReconLine@1001 : Record 274;Relation@1000000000 : 'One-to-One,One-to-Many,Many-to-One');**

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.

Events without parameters seem meaningless.
