### ISSUE TITLE
Event request on OBJECT Codeunit 370 Bank Acc. Reconciliation Post

### ISSUE THREAD

**Issue by nitinnexon** [microsoft/ALAppExtensions#12805]
Can we have new event request as per below function?

LOCAL PROCEDURE Post@3(BankAccRecon@1000 : Record 273);
    VAR
      BankAccReconLine@1001 : Record 274;
      AppliedAmount@1002 : Decimal;
      TotalTransAmtNotAppliedErr@1003 : Text;
    BEGIN

      WITH BankAccRecon DO BEGIN
        // Run through lines
        BankAccReconLine.FilterBankRecLines(BankAccRecon);
        TotalAmount := 0;
        TotalAppliedAmount := 0;
        TotalDiff := 0;
        Lines := 0;
        IF BankAccReconLine.ISEMPTY THEN
          ERROR(Text002);
        BankAccLedgEntry.LOCKTABLE;
        CheckLedgEntry.LOCKTABLE;

        IF BankAccReconLine.FINDSET THEN
          REPEAT
            Lines := Lines + 1;
            Window.UPDATE(2,Lines);
            AppliedAmount := 0;
            // Adjust entries
            // Test amount and settled amount
            CASE "Statement Type" OF
              "Statement Type"::"Bank Reconciliation":
                CASE BankAccReconLine.Type OF
                  BankAccReconLine.Type::"Bank Account Ledger Entry":
                    CloseBankAccLedgEntry(BankAccReconLine,AppliedAmount);
                  BankAccReconLine.Type::"Check Ledger Entry":
                    CloseCheckLedgEntry(BankAccReconLine,AppliedAmount);
                  BankAccReconLine.Type::Difference:
                    TotalDiff += BankAccReconLine."Statement Amount";
                END;
              "Statement Type"::"Payment Application":
                PostPaymentApplications(BankAccReconLine,AppliedAmount);
            END;
            //HBSRP 2017-08-11 Start:
            IF BankAccReconLine."Applied Bank Acc. Ledger Entry" <> 0 THEN BEGIN
              TotalAmount += BankAccReconLine."Statement Amount";
              TotalAppliedAmount += AppliedAmount;
            END ELSE BEGIN
            //HBSRP 2017-08-11 End:
              BankAccReconLine.TESTFIELD("Applied Amount",AppliedAmount);
              TotalAmount += BankAccReconLine."Statement Amount";
              TotalAppliedAmount += AppliedAmount;
            END;
	
          UNTIL BankAccReconLine.NEXT = 0;
	**OnAfterBankAccReconAppliedAmount() // New event required here**
        // Test amount
        IF "Statement Type" = "Statement Type"::"Payment Application" THEN
          TotalTransAmtNotAppliedErr := NotFullyAppliedErr
        ELSE
          TotalTransAmtNotAppliedErr := Text003;

    LOCAL PROCEDURE CloseBankAccLedgEntry@7(BankAccReconLine@1000 : Record 274;VAR AppliedAmount@1001 : Decimal);
    BEGIN
      BankAccLedgEntry.RESET;
      BankAccLedgEntry.SETCURRENTKEY("Bank Account No.",Open);
      BankAccLedgEntry.SETRANGE("Bank Account No.",BankAccReconLine."Bank Account No.");
      BankAccLedgEntry.SETRANGE(Open,TRUE);
      BankAccLedgEntry.SETRANGE(
        "Statement Status",BankAccLedgEntry."Statement Status"::"Bank Acc. Entry Applied");
      BankAccLedgEntry.SETRANGE("Statement No.",BankAccReconLine."Statement No.");
      IF BankAccReconLine."Applied Bank Acc. Ledger Entry" <> 0 THEN //HBSRP 2017-08-11
        BankAccLedgEntry.SETRANGE("Entry No.",BankAccReconLine."Applied Bank Acc. Ledger Entry")
      ELSE
        BankAccLedgEntry.SETRANGE("Statement Line No.",BankAccReconLine."Statement Line No.");
**OnBeforeFindBankAccLedgEntry(); // New event required here**
      IF BankAccLedgEntry.FIND('-') THEN
        REPEAT
          AppliedAmount += BankAccLedgEntry."Remaining Amount";
          BankAccLedgEntry."Remaining Amount" := 0;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
