### ISSUE TITLE
[Event Request] codeunit 12179 "Export FatturaPA Document" - OnBeforePaymentData

### ISSUE THREAD

**Issue by Athon-dev** [microsoft/ALAppExtensions#12814]
We like to request the following change:
Object: Codeunit::"Export FatturaPA Document"
Function: PopulatePaymentData
Reason: manage 'CondizioniPagamento' tag.
Code to change:

local procedure PopulatePaymentData(var TempFatturaLine: Record "Fattura Line" temporary; TempFatturaHeader: Record "Fattura Header" temporary)
begin

  //>INSERT HERE

  // 2.4. DatiPagamento - Payment Data
  with TempXMLBuffer do begin
    TempFatturaLine.Reset();
    TempFatturaLine.SetRange("Line Type", TempFatturaLine."Line Type"::Payment);
    if TempFatturaLine.FindSet then begin
      AddGroupElement('DatiPagamento');
      AddNonEmptyElement('CondizioniPagamento', TempFatturaHeader."Fattura Payment Terms Code");
        repeat
          AddGroupElement('DettaglioPagamento');
          AddNonEmptyElement('ModalitaPagamento', TempFatturaHeader."Fattura PA Payment Method");
          AddNonEmptyElement(
             'DataScadenzaPagamento', FormatDate(TempFatturaLine."Due Date"));
          AddNonEmptyElement('ImportoPagamento', FormatAmount(TempFatturaLine.Amount));
          AddNonEmptyLastElement('IBAN', CompanyInformation.IBAN);
        until TempFatturaLine.Next() = 0;
      end;
  end;
end;

//>THIS IS THE CODE TO INSERT

IsHandled := false;
OnBeforePaymentData(TempFatturaLine, TempFatturaHeader, TempXMLBuffer, IsHandled); //NEWEVENT
if IsHandled then
  exit();  

[IntegrationEvent(false, false)]
local procedure OnBeforePaymentData(var TempFatturaLine: Record "Fattura Line" temporary; TempFatturaHeader: Record "Fattura Header" temporary;var TempXMLBuffer: record "XML Buffer";var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
