### ISSUE TITLE
[Event Request] codeunit 12179 "Export FatturaPA Document" - OnAfterCreateXML

### ISSUE THREAD

**Issue by Athon-dev** [microsoft/ALAppExtensions#12815]
We like to request the following change:
Object: Codeunit::"Export FatturaPA Document"
Function: GenerateXMLFile
Reason: to get fileName from Event.
Code to change:

procedure GenerateXMLFile(var TempFatturaLine: Record "Fattura Line" temporary; TempFatturaHeader: Record "Fattura Header" temporary; ClientFileName: Text[250]): Text[250]
    var
	...
	FileName: Text;
    begin
	...        
        // update Buffer
        FileManagement.DeleteServerFile(FileName);
        TempXMLBuffer.FindFirst();
        TempXMLBuffer.Save(FileName);

	TO MODIFY
        OnAfterCreateXML(TempXMLBuffer, FileName);
        ...
    end;
  

[IntegrationEvent(false, false)]
local procedure OnAfterCreateXML(var TempXMLBuffer: Record "XML Buffer" temporary, FileName: Text);
begin  
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
