### ISSUE TITLE
[Access Request] Table 37 - Sales Line - SetReserveWithoutPurchasingCode

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12813]
Hi Al team,

I would like to access the following functions from external object

```
// NEW >>>>
    // local procedure SetReserveWithoutPurchasingCode()
    procedure SetReserveWithoutPurchasingCode()
    // NEW <<<<
    var
        Item: Record Item;
    begin
        GetItem(Item);
        if Item.Reserve = Item.Reserve::Optional then begin
            GetSalesHeader();
            Reserve := SalesHeader.Reserve;
        end else
            Reserve := Item.Reserve;

        OnAfterSetReserveWithoutPurchasingCode(Rec, SalesHeader, Item);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
