### ISSUE TITLE
[Access Request] Table 37 - Sales Line - UpdatePrepmtAmounts

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12812]
Hi Al team,

I would like to access the following functions from external object

```
// NEW >>>>
    // local procedure UpdatePrepmtAmounts()
    procedure UpdatePrepmtAmounts()
    // NEW <<<<
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdatePrepmtAmounts(Rec, SalesHeader, IsHandled);
        if IsHandled then
            exit;

        if SalesHeader."Document Type" <> SalesHeader."Document Type"::Invoice then begin
            "Prepayment VAT Difference" := 0;
            if not PrePaymentLineAmountEntered then begin
                "Prepmt. Line Amount" := Round("Line Amount" * "Prepayment %" / 100, Currency."Amount Rounding Precision");
                if abs("Inv. Discount Amount" + "Prepmt. Line Amount") > abs("Line Amount") then
                    "Prepmt. Line Amount" := "Line Amount" - "Inv. Discount Amount";
            end;
            PrePaymentLineAmountEntered := false;
        end;

        if not IsTemporary() then
            CheckPrepmtAmounts();
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
