### ISSUE TITLE
[Event Request] Table 5767 "Warehouse Activity Line" - OnBeforeGetUOMCode

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#12817]
Hi, would it be possible to modify the event OnBeforeGetUOMCode in table 5767 Warehouse Activity Line to add the record Location as a parameter, like this : 
```
    local procedure GetUOMCode() UOMCode: Code[10];
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetUOMCode(Rec, UOMCode, Location, IsHandled);
        if IsHandled then
            exit(UOMCode);

        if Location."Directed Put-away and Pick" then
            UOMCode := "Unit of Measure Code"
        else
            UOMCode := WMSMgt.GetBaseUOM("Item No.");
    end;
```
?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
