### ISSUE TITLE
[Question] Related Barcode Generator- in Word Layout - RDLC Layout

### ISSUE THREAD

**Issue by srinivasGangadhara** [microsoft/ALAppExtensions#12822]
Hi,

we have found we can encode data to barcode, we have followed below link , But that is not working.

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-add-barcodes

Can you Explain how we can use the barcodes in Saas Environment

Regards,
Srinivas

**Comment by AlexanderYakunin** [comment]
Can you ask specific questions?

**Comment by srinivasGangadhara** [comment]
Hi,

i have created Report to show my barcode in report,

report 50100 ItemBarcodeReport
{
    UsageCategory = ReportsAndAnalysis;
    ApplicationArea = All;
    DefaultLayout = RDLC;
    Caption = 'Item Barcode';
    RDLCLayout = './ItemBarcode.rdl';

    dataset
    {
        dataitem(Items; Item)
        {
            DataItemTableView = sorting("No.");
            RequestFilterFields = "No.";

            column(No_; "No.")
            {

            }
            column(Description; Description)
            {

            }
            column(Barcode; BarcodeTxt)
            {

            }
            trigger OnAfterGetRecord()
            var
                BarcodeSymbology: Enum "Barcode Symbology";
                BarcodeFontProvider: Interface "Barcode Font Provider";
                BarcodeString: Text;
            begin
                BarcodeFontProvider := Enum::"Barcode Font Provider"::IDAutomation1D;
                BarcodeSymbology := Enum::"Barcode Symbology"::Code39;
                BarcodeString := 'AGGGHB78777HGJKK';
                BarcodeFontProvider.ValidateInput(BarcodeString, BarcodeSymbology);
                BarcodeTxt := BarcodeFontProvider.EncodeFont(BarcodeString, BarcodeSymbology);
            end;

        }
    }
    var
        BarcodeTxt: Text;
}


we have not done anything in rdlc , as we see the above code will encode string to barcode, But when we see output of the report it's showing string only.

am missing anything here? Please explain.


thanks!

Regards
srinivas

**Comment by srinivasGangadhara** [comment]
Any Update on this?

**Comment by AlexanderYakunin** [comment]
@JesperSchulz - can you help?

**Comment by JesperSchulz** [comment]
I'm afraid, GitHub issues aren't the right tool to get answers to general questions. The community doesn't look through issues to answer them, and the development team at Microsoft doesn't have capacity to support the entire community on this platform.

Try posting your question to the following resources instead:

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

Yammer is also a great place to get help of issues of this sort!

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
