### ISSUE TITLE
[Event request] codeunit 2851 "Dim Correction Run" - OnAfterUpdateGlEntry

### ISSUE THREAD

**Issue by VeronicaGoglia** [microsoft/ALAppExtensions#12828]
Hi AL-Team,
can you please add a new event in the method UpdateGLEntry

GLEntry."Last Dim. Correction Entry No." := DimensionCorrectionEntryNo;
GLEntry."Last Dim. Correction Node" := TempInvalidatedDimCorrection."Node Id";
GLEntry.Modify(true);

//New Event
OnAfterUpdateGlEntry(GlEntry, TempDimCorrectionSetBuffer);
//New Event

exit(true);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
