### ISSUE TITLE
[Extensibility] Codeunit 12 - Gen. Jnl.-Post Line - PostBankAcc method

### ISSUE THREAD

**Issue by Wiechardt** [microsoft/ALAppExtensions#12824]
Hi there,

Please can I ask you to change the GenJnlLine parameter to be sent by reference to the PostBankAcc method as shown below:

Before
local procedure PostBankAcc(GenJnlLine: Record "Gen. Journal Line"; Balancing: Boolean)

After
local procedure PostBankAcc(**var** GenJnlLine: Record "Gen. Journal Line"; Balancing: Boolean)

Thanks,
Wiechardt

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
