### ISSUE TITLE
[Event Request] Page 161 "Purchase Statistics" OnCalculateTotalsOnAfterPurchPostSumPurchLinesTemp Additional parameters needed

### ISSUE THREAD

**Issue by SweconThomasH** [microsoft/ALAppExtensions#12826]
TotalAmount1 and TotalAmount2 are changed in our case due to exchange part management. Therefore we need 2 more parameters. This is similar to issue #11110: there it concerned the Sales side; we need this here for Purchase also.

`   [EventSubscriber(ObjectType::Page, Page::"Purchase Statistics", 'OnCalculateTotalsOnAfterPurchPostSumPurchLinesTemp', '', true, true)]
local procedure "Purchase Statistics_OnCalculateTotalsOnAfterPurchPostSumPurchLinesTemp" (var PurchHeader: Record "Purchase Header"; var TempPurchLine: Record "Purchase Line"; var AllowVATDifference: Boolean; var TotalAmount1: Decimal; var TotalAmount2: Decimal)`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
