### ISSUE TITLE
Table 740 VAT Report Header - OnBeforeLookupOriginalReportNo

### ISSUE THREAD

**Issue by LubomirUrx** [microsoft/ALAppExtensions#12827]
I'd like to propose the event OnBeforeLookupOriginalReportNo in table "VAT Report Header" on field "Original Report No.".

`trigger OnLookup()
var
    LookupVATReportHeader: Record "VAT Report Header";
    VATReportList: Page "VAT Report List";
    ShowLookup: Boolean;
    TypeFilterText: Text[1024];
    IsHandled: Boolean;
begin
    //Start
    IsHandled := false;
    OnBeforeLookupOriginalReportNo(Rec, IsHandled);
    if IsHandled then
        exit;
    //End

    TypeFilterText := '';
    ShowLookup := false;

    case "VAT Report Type" of
        "VAT Report Type"::Corrective, "VAT Report Type"::Supplementary:
            ShowLookup := true;
    end;

    if ShowLookup then begin
        LookupVATReportHeader.SetFilter("No.", '<>' + "No.");
        LookupVATReportHeader.SetRange(Status, Status::Accepted);
        LookupVATReportHeader.SetFilter("VAT Report Type", TypeFilterText);
        VATReportList.SetTableView(LookupVATReportHeader);
        VATReportList.LookupMode(true);
        if VATReportList.RunModal = ACTION::LookupOK then begin
            VATReportList.GetRecord(LookupVATReportHeader);
            Validate("Original Report No.", LookupVATReportHeader."No.");
        end;
    end;
end;`

`//Start
[IntegrationEvent(false, false)]
local procedure OnBeforeLookupOriginalReportNo(var VATReportHeader: Record "VAT Report Header"; var IsHandled: Boolean)
begin
end;
//End`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
