### ISSUE TITLE
[Event Request] Service Line table InitQtyToShip procedure

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#12831]
Could you please add 2 events as below.  Thanks very much.

Existing Codes:

    procedure InitQtyToShip()
    begin
        if LineRequiresShipmentOrReceipt then begin
            "Qty. to Ship" := 0;
            "Qty. to Ship (Base)" := 0;
        end else begin
            "Qty. to Ship" := "Outstanding Quantity";
            "Qty. to Ship (Base)" := "Outstanding Qty. (Base)";
        end;
        Validate("Qty. to Consume");
        InitQtyToInvoice;

        OnAfterInitQtyToShip(Rec, CurrFieldNo);
    end;
------------------------------------------------------------------------------------------
New Codes:

  procedure InitQtyToShip()
    begin
        ****OnBeforeInitQtytoShip(Rec, CurrField);
        if LineRequiresShipmentOrReceipt then begin
            "Qty. to Ship" := 0;
            "Qty. to Ship (Base)" := 0;
        end else begin
            "Qty. to Ship" := "Outstanding Quantity";
            "Qty. to Ship (Base)" := "Outstanding Qty. (Base)";
        end;
        Validate("Qty. to Consume");

        ****OnInitQtyToShipOnBeforeInitQtyToInvoice(Rec, InHandled);
        ****If NOT IsHandled then
        InitQtyToInvoice;
        
        OnAfterInitQtyToShip(Rec, CurrFieldNo);
    end;

where
[IntegrationEvent(false, false)]
    local procedure OnBeforeInitQtytoShip(var ServiceLine: Record "Services Line", CallingFieldNo: Integer)
    begin
    end;

[IntegrationEvent(false, false)]
    local procedure OnInitQtyToShipOnBeforeInitQtyToInvoice(var ServiceLine: Record "Services Line", var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
