### ISSUE TITLE
[Scope Change Request] codeunit 6300,"Azure AD Mgt." GetGuestAccessToken()

### ISSUE THREAD

**Issue by jwikman** [microsoft/ALAppExtensions#12834]
Hi,

Please remove the `[Scope('OnPrem')]` from procedure GetGuestAccessToken in codeunit 6300 "Azure AD Mgt."
```
    [Scope('OnPrem')]
    [NonDebuggable]
    procedure GetGuestAccessToken(ResourceUrl: Text; GuestTenantId: Text) AccessToken: Text
```

This function is used by the Company Hub and seems to provide the functionality we need to call a Web Service in another tenant with the logged on user's credentials.

Thanks,
Johannes

**Comment by IhorHandziuk** [comment]
Hi Johannes!

Unfortunately we do not plan to expose this function, as we want users to explicitly consent when 3d party extensions attempt to get access tokens with certain permissions.
We recommend to use the functions in the OAuth2 module (accepting ClientID and secret / certificate) for your scenario 😊
