### ISSUE TITLE
[Feature Request] Possibility to refresh a OBO token from cache for another Tenant

### ISSUE THREAD

**Issue by jwikman** [microsoft/ALAppExtensions#12833]
I need to communicate to other BC Tenants through Web Services from within a BC tenant. The user is licensed and has permissions in all Tenants, so that should be possible.

Scenario:
Tenant0: An administrative tenant where the user belong. Let's call the user "Admin"
Tenant1, Tenant2, etc.: Other tenants that should be handled from Tenant0. 
Admin will call Tenant1 through WS to start different tasks.
Some tasks that Admin starts in Tenant1 takes a long time, so the WS call can not wait for it to finish since the WS would time out.
In Tenant0 a background session will need to check now and then if the task in Tenant1 is completed. 

We use the On-Behalf-Of flow to solve above.

I use `OAuth2.AcquireOnBehalfAccessTokenAndTokenCache()` in Tenant0 to get the Access Token and Token Cache for Tenant1. This works great, the WS call gets authenticated and a task gets started in Tenant1.
As long as the Access Token is valid the background session can use the same Access Token to call Tenant1 to check if task is completed. 

BUT if the Access Token is expired, the background session would need to get a new Access Token, using the Token Cache returned by `OAuth2.AcquireOnBehalfAccessTokenAndTokenCache()`. To get a new token from that cache we would use `OAuth2.AcquireOnBehalfOfTokenByTokenCache(LoginHint,..)`. `OAuth2.AcquireOnBehalfOfTokenByTokenCache(LoginHint,..)` works fine as long you are requesting a token for the tenant you are running in, but it cannot handle requests for Access Tokens for another tenant....

I would like to have an overloaded function for `OAuth2.AcquireOnBehalfOfTokenByTokenCache(LoginHint,..)` that also have the `OAuthAuthorityUrl` parameter, like this:
```
    [NonDebuggable]
    procedure AcquireOnBehalfOfTokenByTokenCache(OAuthAuthorityUrl: Text; LoginHint: Text; RedirectURL: Text; Scopes: List of [Text]; RefreshToken: Text; var AccessToken: Text; var NewRefreshToken: Text)
    var
        ScopesArray: DotNet StringArray;
    begin
        FillScopesArray(Scopes, ScopesArray);
        Initialize(OAuthAuthorityUrl, RedirectURL);
        AccessToken := AuthFlow.ALAcquireTokenFromTokenCacheState(ScopesArray, LoginHint, RefreshToken, NewRefreshToken);
    end;
```
Is it an intentional omission of this function, that I don't get the reasons for, or would it be possible to add this function to codeunit 502 OAuth2Impl and codeunit 501 OAuth2?

Thanks,
Johannes

**Comment by jwikman** [comment]
I can of course create a PR for this if it would help...

**Comment by IhorHandziuk** [comment]
Hi @jwikman , the scenario sounds very reasonable and I believe there is no reason for us to not allow this.

Please, create a PR, and we will process it as soon as we can 😊

**Comment by jwikman** [comment]
Hi Ihor!

Since we now got it working with the logic from your sample mentioned in PR #12960, I just want to share our code for this:

```
   var
        IsInitialized: Boolean;
        [NonDebuggable]
        ClientId: Text;
        [NonDebuggable]
        ClientSecret: Text;

    [TryFunction]
    [NonDebuggable]
    local procedure TryGetAccessToken(var pvAccessToken: Text; pAadTenantId: Text)
    var
        OAuthErr: Text;
        CouldNotGetAccessTokenErr: Label 'Could not get access token. Please, try to log out and log in again.';
    begin
        Initialize(); // Gets the global ClientId from settings and ClientSecret from Isolated Storage

        // Blank RedirectUrl -> Default to current web url
        if (not gOAuth2.AcquireAuthorizationCodeTokenFromCache(ClientId, ClientSecret, '', GetMicrosoftOAuth2Url(pAadTenantId), GetScopes(), pvAccessToken)) or (pvAccessToken = '') then
            gOAuth2.AcquireTokenByAuthorizationCode(ClientId, ClientSecret, GetMicrosoftOAuth2Url(pAadTenantId), '', GetScopes(), Enum::"Prompt Interaction"::None, pvAccessToken, OAuthErr);

        if pvAccessToken = '' then
            Error(CouldNotGetAccessTokenErr);
    end;

    local procedure GetScopes() rScopes: List of [Text]
    var
        ResourceURLTxt: Label 'https://api.businesscentral.dynamics.com/.default', Locked = true;
    begin
        rScopes.Add(ResourceURLTxt);
        exit(rScopes);
    end;

    local procedure GetMicrosoftOAuth2Url(pAadTenantId: Text): Text
    var
        MicrosoftOAuth2Url: Text;
        MicrosoftOAuth2UrlTxt: Label 'https://login.microsoftonline.com/%1/oauth2/', Locked = true, Comment = '%1 = Tenant ID / Tenant domain';
    begin
        MicrosoftOAuth2Url := StrSubstNo(MicrosoftOAuth2UrlTxt, pAadTenantId);
        exit(MicrosoftOAuth2Url);
    end;
```

The prerequisites for this is that an Global Admin has consented to our app registration (the one with the ClientId above).

The easiest way for this, at least in our scenario where the user getting the token is not able to do the consent, is to create a consent url and send to the Global Admin of the tenant you want to connect to:
`https://login.microsoftonline.com/common/adminconsent?client_id=[CLIENT_ID]
`
Where you replace [CLIENT_ID] with the "Application (client) ID" found on the overview page for the App Registration in the AAD Portal. the "common" part of the consent URL can also be changed to the TenantID (useful if the Global Administrator user is from another AAD)

This issue is now considered closed, now that we've got a proper solution in place. 🙂
