### ISSUE TITLE
[Event Request] Report "Refresh Production Order" - OnAfterInitRequestPage

### ISSUE THREAD

**Issue by Delpixe** [microsoft/ALAppExtensions#12836]
Hello,

Some customers have requested the opening of the request page with some flags turned off, is it possible to insert an event? 
Something like this?

![image](https://user-images.githubusercontent.com/38073933/121857521-000ff900-ccf6-11eb-945a-c5900ac26972.png)

![image](https://user-images.githubusercontent.com/38073933/121857566-0c945180-ccf6-11eb-80d8-7ebc8b0cd746.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
