### ISSUE TITLE
[Event Request] Service Line table InitQtyToConsume procedure

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#12832]
Could you please modify the existing event as below. Thanks very much.    

Existing Codes:

    procedure InitQtyToConsume()
    begin
        "Qty. to Consume" := MaxQtyToConsume;
        "Qty. to Consume (Base)" := MaxQtyToConsumeBase;
        OnAfterInitQtyToConsume(Rec, CurrFieldNo);

        InitQtyToInvoice;
    end;
--------------------------------------------------------------------------
New Codes:

    procedure InitQtyToConsume()
    begin
        "Qty. to Consume" := MaxQtyToConsume;
        "Qty. to Consume (Base)" := MaxQtyToConsumeBase;
        OnAfterInitQtyToConsume(Rec, CurrFieldNo, **IsHandled)**;

        InitQtyToInvoice;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
