### ISSUE TITLE
[Event Change] Report 5199 "Update Contact Classification" - OnFindContactValuesOnBeforeContLoop IncludeSender

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12843]
Hi AL-Team,

can you add IncludeSender to OnFindContactValuesOnBeforeContLoop?

```
// NEW >>>>
    // [IntegrationEvent(false, false)]
    [IntegrationEvent(true, false)]
    // NEW <<<<
local procedure OnFindContactValuesOnBeforeContLoop(ProfileQuestionnaireLine: Record "Profile Questionnaire Line"; var Contact: Record Contact)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
