### ISSUE TITLE
[Event Request] Table Customer - OnAfterInsert(Rec)

### ISSUE THREAD

**Issue by rswaldia** [microsoft/ALAppExtensions#12849]
Request for new Event **### OnAfterInsert** ### in Customer table inside **OnInsert** trigger.

DimMgt.UpdateDefaultDim(
          DATABASE::Customer, "No.",
          "Global Dimension 1 Code", "Global Dimension 2 Code");
//  New Event   BEGIN //
**_OnAfterInsert(Rec)_**
//  New Event   END //
UpdateReferencedIds;
SetLastModifiedDateTime;

**_[IntegrationEvent(false, false)]
local procedure OnAfterInsert(var Customer: Record Customer)
begin
end;_**

**Comment by dannoe** [comment]
Why are you not using this event: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/events/table/devenv-onafterinsertevent-table-trigger

**Comment by rswaldia** [comment]
Thanks dannoe. This event can be used.
