### ISSUE TITLE
[Event Request] Table "Segment Line", Procedure "FinishSegLineWizard"

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#12848]
We need a new Publisher in Table "Segment Line", Procedure "FinishSegLineWizard"
![image](https://user-images.githubusercontent.com/40287548/121891857-48421200-cd1c-11eb-8f9d-fcb984724aac.png)

Please add the following parameters:
![image](https://user-images.githubusercontent.com/40287548/121891924-60b22c80-cd1c-11eb-8757-735b93361251.png)

**Comment by Oleg-Romashkov** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by AndreBreitenbach** [comment]
Hi Oleg, please find the requested Code below (Code is marked with "// >>>>>> NEW <<<<<<<<<")

 procedure FinishSegLineWizard(IsFinish: Boolean)
    var
        InteractionLogEntry: Record "Interaction Log Entry";
        SegManagement: Codeunit SegManagement;
        WordManagement: Codeunit WordManagement;
        WordApplicationHandler: Codeunit WordApplicationHandler;
        Send: Boolean;
        Flag: Boolean;
        HTMLAttachment: Boolean;
        HTMLContentBodyText: Text;
        CustomLayoutCode: Code[20];
    begin

        // >>>>>> NEW <<<<<<<<<
        OnBeforeFinishWizard(Rec,IsFinish);
        // >>>>>> NEW <<<<<<<<<
        HTMLAttachment := IsHTMLAttachment;
        Flag := false;
        if IsFinish then
            Flag := true
        else
            Flag := Confirm(Text007);

        if Flag then begin
            CheckStatus;
.....

    // >>>>>> NEW <<<<<<<<<
    [IntegrationEvent(false, false)]
    local procedure OnBeforeFinishWizard(var SegmentLine: Record "Segment Line"; IsFinish: Boolean)
    begin
    end;
    // >>>>>> NEW <<<<<<<<<

**Comment by Oleg-Romashkov** [comment]
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
