### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134395 "ERM Document Totals UT"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#12851]
[Event Request] Application “Tests-ERM”, 134395 "ERM Document Totals UT"

Could you please insert the OnTestInitialize Event at the beginning of the procedure PurchaseUpdateTotalsControlsRecalculatesIfTheRecordIsChanged?
![pic1](https://user-images.githubusercontent.com/45795262/121913226-80a01b00-cd31-11eb-9c64-d1199404bd90.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
