### ISSUE TITLE
[Event Request] codeunit 1907 Camera - OnAfterPictureAdded

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#12854]
Can we get a new Event after a Media/MediaSet Field of a Record was Updated?
https://github.com/microsoft/ALAppExtensions/blob/a598cfc8f86aa68891983abe5225e8030bb340f8/Modules/System/Camera%20and%20Media%20Interaction/src/Camera.Codeunit.al#L42

We need this Event to Trigger Update of External Locations that make use of the Item Picture and we want to avoid to Export the Picture every time the picture is being updated, with a Camera.

```al
procedure AddPicture(RecordVariant: Variant; FieldNo: Integer)Result: Boolean
begin
    Result := CameraImpl.AddPicture(RecordVariant, FieldNo)
    OnAfterPictureAdded(RecordVariant, FieldNo, Result);
end;

```
```al
[IntegrationEvent(false, false)]
local procedure OnAfterPictureAdded(RecordVariant: Variant; FieldNo: Integer; PictureTakenAndAdded: Boolean)
begin
end;
```

**Comment by IhorHandziuk** [comment]
Hi @pri-kise, as a general rule we try to avoid very general events unless they make total sense in the context (as they are often misused). In your case, wouldn't it make more sense to subscribe to `OnAfterModify` of the `Item` to get the same information?

**Comment by pri-kise** [comment]
The OnAfterModify Event doesn't include the information if the Picture has changed. And we only want to peform some updates.
Exporting the Item Picture to external services if it has changed and not on every update of the picture. 
Imagine I would upload the picture to an external storage every thime the Item is modified instead of only updating the external source only if the picture is changed on this way.
I know we would miss updates caused by background changes, but the picture is only changed by users via this page.

**Comment by IhorHandziuk** [comment]
There is an event coming in the next minor release that seem to address your scenario:

`OnAfterTakeNewPicture(var Item: Record Item; IsPictureAdded: Boolean)` that will be raised every time a new picture is taken.

Would this option work for you? 😊
