### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134065 "Test Reten. Pol. Doc. Arch."

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#12859]
[Event Request]Application “Tests-ERM”, 134065 "Test Reten. Pol. Doc. Arch."

Could you please insert the OnTestInitialize Event at the beginning of the procedure Initialize?
![pic1](https://user-images.githubusercontent.com/45795262/122069141-3b452180-cdf5-11eb-9f35-fe9195cb8a50.png)

**Comment by Oleg-Romashkov** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
