### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - procedure OpenPurchaseOrderStatistics

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#12857]
Please add the event in that procedure (the same way as it exists in Sales Header - OpenSalesOrderStatistics)
```
procedure OpenPurchaseOrderStatistics()
var  //new
    IsHandled: Boolean;  //new
begin
    OnBeforeOpenPurchaseOrderStatistics(Rec, IsHandled);  //new
    if IsHandled then  //new
        exit;  //new

    CalcInvDiscForHeader;
    CreateDimSetForPrepmtAccDefaultDim;
    Commit();
    PAGE.RunModal(PAGE::"Purchase Order Statistics", Rec);
end;

[IntegrationEvent(false, false)]  //new
local procedure OnBeforeOpenPurchaseOrderStatistics(var PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)  //new
begin  //new
end;  //new
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
