### ISSUE TITLE
[Event Request] page 346 "Item Picture" - OnAfterPictureDeleted

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#12855]
Can we please get the following Event?

```al
procedure DeleteItemPicture()
begin
    TestField("No.");

    if not Confirm(DeleteImageQst) then
        exit;

    Clear(Picture);
    Modify(true);
    OnAfterPictureDeleted(Rec);//NEW
end;
```

```al
[IntegrationEvent(false, false)]
local procedure OnAfterPictureDeleted(var Item: Record Item)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
