### ISSUE TITLE
[Event Request] Service Line table CheckItemAvailable procedure

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#12852]
Current codes:

procedure CheckItemAvailable(CalledByFieldNo: Integer)
    var
        ItemCheckAvail: Codeunit "Item-Check Avail.";
        IsHandled: Boolean;
    begin
        if "Needed by Date" = 0D then begin
            GetServHeader;
            if ServHeader."Order Date" <> 0D then
                Validate("Needed by Date", ServHeader."Order Date")
            else
                Validate("Needed by Date", WorkDate);
        end;
.
.
.
.
.
        if Nonstock then
            exit;
        if not ("Document Type" in ["Document Type"::Order, "Document Type"::Invoice]) then
            exit;

        if ItemCheckAvail.ServiceInvLineCheck(Rec) then
            ItemCheckAvail.RaiseUpdateInterruptedError;
------------------------------------------------------------------------------
Request Event location

procedure CheckItemAvailable(CalledByFieldNo: Integer)
    var
        ItemCheckAvail: Codeunit "Item-Check Avail.";
        IsHandled: Boolean;
    begin       
         if "Needed by Date" = 0D then begin
            GetServHeader;
            //AI7.01 start
              IF ServHeader."Response Date" <> 0D THEN
                VALIDATE("Needed by Date",ServHeader."Response Date")
              ELSE
                BEGIN
              //AI7.01 end
                      if ServHeader."Order Date" <> 0D then
                          Validate("Needed by Date", ServHeader."Order Date")
                      else
                          Validate("Needed by Date", WorkDate);
                  end;

.
.
.
.
.
        if Nonstock then
            exit;
        if not ("Document Type" in ["Document Type"::Order, "Document Type"::Invoice]) then
            exit;

        if ItemCheckAvail.ServiceInvLineCheck(Rec) then
            ItemCheckAvail.RaiseUpdateInterruptedError;

--------------------------------------------------------------
What we need is to check the Response Date of Service Header first before checking the Order Date of Service Header.   Item Needed by date is more driven by the Response date first.  What would be a good way to add an event at that spot?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
