### ISSUE TITLE
[Event Modification] Table 36 "Purchase Header" - OnBeforeLookupAppliesToDocNo

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#12868]
Requesting update parameter in integration event OnBeforeLookupAppliesToDocNo in table 36 "Purchase Header", add "var" to parameter VendorLedgEntry:

Currently:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeLookupAppliesToDocNo(var PurchaseHeader: Record "Purchase Header"; VendorLedgEntry: Record "Vendor Ledger Entry"; var IsHandled: Boolean)
    begin
    end;
```

Requested:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeLookupAppliesToDocNo(var PurchaseHeader: Record "Purchase Header"; var VendorLedgEntry: Record "Vendor Ledger Entry"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
