### ISSUE TITLE
[Event Request] table 334 Column Layout - GetCaptionClass

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#12865]
Please, , add a new event to procedure "GetCaptionClass" in table 334.
`OnBeforeGetCaptionClass(AnalysisViewDimType,ColumnLayoutName,Caption,IsHandled);`

[External]
PROCEDURE GetCaptionClass@4(AnalysisViewDimType@1000 : Integer) : Text[250];
VAR
  IsHandled@5562063 : Boolean;
  Caption@5562062 : Text[250];
BEGIN
  GetColLayoutSetup;
  **// new
  OnBeforeGetCaptionClass(AnalysisViewDimType,ColumnLayoutName,Caption,IsHandled);
  IF IsHandled THEN
    EXIT(Caption);
  //**
  CASE AnalysisViewDimType OF
...

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
