### ISSUE TITLE
[Event Request] codeunit 8 AccSchedManagement - CheckAnalysisView

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#12866]
Please, add a new event to procedure CheckAnalysisView in codeunit 8.
`OnAfterCheckAnalysisView(AccSchedName,ColumnLayoutName);`

[External]
    PROCEDURE CheckAnalysisView@36(CurrentSchedName@1000 : Code[10];CurrentColumnName@1001 : Code[10];TestColumnName@1002 : Boolean);
    VAR
      ColumnLayout2@1003 : Record 334;
      AnyColumnDimensions@1004 : Boolean;
    BEGIN
      IF NOT AnalysisViewRead THEN BEGIN
        AnalysisViewRead := TRUE;
        IF CurrentSchedName <> AccSchedName.Name THEN BEGIN
          CheckTemplateName(CurrentSchedName);
          AccSchedName.GET(CurrentSchedName);
        END;
...
       END;
      END;
      **// new
      OnAfterCheckAnalysisView(AccSchedName,ColumnLayoutName);
      //** 
    END;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
