### ISSUE TITLE
[Event Request] Table 85 Acc. Schedule Line - GetCaptionClass

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#12863]
Please, add new event to procedure "GetCaptionClass" in table 85 Acc. Schedule Line
`OnBeforeGetCaptionClass(AnalysisViewDimType,AccSchedName,Caption,IsHandled);`

    [External]
    PROCEDURE GetCaptionClass@7(AnalysisViewDimType@1000 : Integer) : Text[250];
    VAR
      IsHandled@5562062 : Boolean;
      Caption@5562063 : Text[250];
    BEGIN
      GetAccSchedSetup;

      //  new
      OnBeforeGetCaptionClass(AnalysisViewDimType,AccSchedName,Caption,IsHandled);
      IF IsHandled THEN
        EXIT(Caption);
      // end-new

      CASE AnalysisViewDimType OF
        1:
          BEGIN
            IF AnalysisView."Dimension 1 Code" <> '' THEN
              EXIT('1,6,' + AnalysisView."Dimension 1 Code");

            EXIT(Text006);
          END;
        2:

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
