### ISSUE TITLE
[Event Request] table 334 Column Layout - LookUpDimFilter

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#12864]
Please, add a new event to procedure "LookupDimFilter" in table 334.
`OnBeforeLookUpDimFilter(DimNo,Text,ColumnLayoutName,IsHandled,Result);`

[External]
    PROCEDURE LookUpDimFilter@57(DimNo@1000 : Integer;VAR Text@1001 : Text[250]) : Boolean;
    VAR
      DimVal@1002 : Record 349;
      CostAccSetup@1004 : Record 1108;
      DimValList@1003 : Page 560;
      IsHandled@5562063 : Boolean;
      Result@5562062 : Boolean;
    BEGIN
      GetColLayoutSetup;
      **// new
      IsHandled := FALSE;
      OnBeforeLookUpDimFilter(DimNo,Text,ColumnLayoutName,IsHandled,Result);
      IF IsHandled THEN
        EXIT(Result);
      //** 
      IF CostAccSetup.GET THEN;
...

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
