### ISSUE TITLE
[Bug] Table 5050 Mobile Phone No. missing in IsUpdateNeeded

### ISSUE THREAD

**Issue by PunkyGP** [microsoft/ALAppExtensions#12869]
Hello, 

some updates ago you have introduced a default field Mobile Phone No. on the Customer table. This was indeed missing.
Now we found that the sync between contact (type company) doesn't work if you only change the Mobile Phone No on the contact card.

When you change some other field it works fine.

The bug is in the procedure "IsUpdateNeeded". You also need to check the diff for Mobile Phone No.

       local procedure IsUpdateNeeded(): Boolean
    var
        UpdateNeeded: Boolean;
    begin
        UpdateNeeded :=
          (Name <> xRec.Name) or
          ("Search Name" <> xRec."Search Name") or
          ("Name 2" <> xRec."Name 2") or
          (Address <> xRec.Address) or
          ("Address 2" <> xRec."Address 2") or
          (City <> xRec.City) or
          ("Phone No." <> xRec."Phone No.") or
          // Missing Begin
          ("Mobile Phone No." <> xRec."Mobile Phone No.") or
          // Missing Begin
          ("Telex No." <> xRec."Telex No.") or
          ("Territory Code" <> xRec."Territory Code") or
          ("Currency Code" <> xRec."Currency Code") or
          ("Language Code" <> xRec."Language Code") or
          ("Salesperson Code" <> xRec."Salesperson Code") or
          ("Country/Region Code" <> xRec."Country/Region Code") or
          ("Fax No." <> xRec."Fax No.") or
          ("Telex Answer Back" <> xRec."Telex Answer Back") or
          ("VAT Registration No." <> xRec."VAT Registration No.") or
          ("Post Code" <> xRec."Post Code") or
          (County <> xRec.County) or
          ("E-Mail" <> xRec."E-Mail") or
          ("Search E-Mail" <> xRec."Search E-Mail") or
          ("Home Page" <> xRec."Home Page") or
          (Type <> xRec.Type);

        OnBeforeIsUpdateNeeded(Rec, xRec, UpdateNeeded);
        exit(UpdateNeeded);
    end;

Kind regards,
Gunter Peeters

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
