### ISSUE TITLE
[Event Request] Page 490  Acc. Schedule Overview - UpdateColumnCaptions

### ISSUE THREAD

**Issue by agarriazu** [microsoft/ALAppExtensions#12872]
Please create onBefore and OnAfter events for this procedure.

>     local procedure UpdateColumnCaptions()
>     var
>         ColumnNo: Integer;
>         i: Integer;
>         IsHandled: Boolean;  //new
>     begin
>      OnBeforeUpdateColumnCaptions(ColumnCaptions,IsHandled);//new
>         Clear(ColumnCaptions);
>         if TempColumnLayout.FindSet then
>             repeat
>                 ColumnNo := ColumnNo + 1;
>                 if (ColumnNo > ColumnOffset) and (ColumnNo - ColumnOffset <= ArrayLen(ColumnCaptions)) then
>                     ColumnCaptions[ColumnNo - ColumnOffset] := TempColumnLayout."Column Header";
>             until (ColumnNo - ColumnOffset = ArrayLen(ColumnCaptions)) or (TempColumnLayout.Next() = 0);
>         // Set unused columns to blank to prevent RTC to display control ID as caption
>         for i := ColumnNo - ColumnOffset + 1 to ArrayLen(ColumnCaptions) do
>             ColumnCaptions[i] := ' ';
>         NoOfColumns := ColumnNo;
>      OnAfterUpdateColumnCaptions(ColumnCaptions,IsHandled);//new
>     end;

**Comment by Oleg-Romashkov** [comment]
Not clear why do you need IsHandled for both events. We need to have event design which could be used by other developers.

Is it ok to have typical handled event?

```
local procedure UpdateColumnCaptions()
    var
        ColumnNo: Integer;
        i: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateColumnCaptions(ColumnCaptions, ColumnOffset, TempColumnLayout, NoOfColumns, IsHandled);
        if IsHandled then
            exit;
        Clear(ColumnCaptions);
        if TempColumnLayout.FindSet then
            repeat
                ColumnNo := ColumnNo + 1;
                if (ColumnNo > ColumnOffset) and (ColumnNo - ColumnOffset <= ArrayLen(ColumnCaptions)) then
                    ColumnCaptions[ColumnNo - ColumnOffset] := TempColumnLayout."Column Header";
            until (ColumnNo - ColumnOffset = ArrayLen(ColumnCaptions)) or (TempColumnLayout.Next() = 0);
        // Set unused columns to blank to prevent RTC to display control ID as caption
        for i := ColumnNo - ColumnOffset + 1 to ArrayLen(ColumnCaptions) do
            ColumnCaptions[i] := ' ';
        NoOfColumns := ColumnNo;
    end;
```

**Comment by agarriazu** [comment]
> Not clear why do you need IsHandled for both events. We need to have event design which could be used by other developers.
> 
> Is it ok to have typical handled event?
> 
> ```
> local procedure UpdateColumnCaptions()
>     var
>         ColumnNo: Integer;
>         i: Integer;
>         IsHandled: Boolean;
>     begin
>         IsHandled := false;
>         OnBeforeUpdateColumnCaptions(ColumnCaptions, ColumnOffset, TempColumnLayout, NoOfColumns, IsHandled);
>         if IsHandled then
>             exit;
>         Clear(ColumnCaptions);
>         if TempColumnLayout.FindSet then
>             repeat
>                 ColumnNo := ColumnNo + 1;
>                 if (ColumnNo > ColumnOffset) and (ColumnNo - ColumnOffset <= ArrayLen(ColumnCaptions)) then
>                     ColumnCaptions[ColumnNo - ColumnOffset] := TempColumnLayout."Column Header";
>             until (ColumnNo - ColumnOffset = ArrayLen(ColumnCaptions)) or (TempColumnLayout.Next() = 0);
>         // Set unused columns to blank to prevent RTC to display control ID as caption
>         for i := ColumnNo - ColumnOffset + 1 to ArrayLen(ColumnCaptions) do
>             ColumnCaptions[i] := ' ';
>         NoOfColumns := ColumnNo;
>     end;
> ```
Hi Oleg

Indeed this would be the better solution

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
