### ISSUE TITLE
[Event modification] OnSetCustApplIdAfterCheckAgainstApplnCurrency in page 232 "Apply Customer Entries"

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#12876]
Request additional parameters in eventOnSetCustApplIdAfterCheckAgainstApplnCurrency in page 232 "Apply Customer Entries".

Currently:

```
    procedure SetCustApplId(CurrentRec: Boolean)
    begin
        ..
        OnSetCustApplIdAfterCheckAgainstApplnCurrency(Rec, CalcType.AsInteger(), GenJnlLine);
        ...
    end;

    [IntegrationEvent(false, false)]
    local procedure OnSetCustApplIdAfterCheckAgainstApplnCurrency(var CustLedgerEntry: Record "Cust. Ledger Entry"; CalcType: Option; GenJnlLine: Record "Gen. Journal Line")
    begin
    end;
```

Requested:

    procedure SetCustApplId(CurrentRec: Boolean)
    begin
        ..
        OnSetCustApplIdAfterCheckAgainstApplnCurrency(Rec, CalcType.AsInteger(), GenJnlLine, SalesHeader, ServHeader, ApplyingCustLedgEntry);
        ...
    end;

    [IntegrationEvent(false, false)]
    local procedure OnSetCustApplIdAfterCheckAgainstApplnCurrency(var CustLedgerEntry: Record "Cust. Ledger Entry"; CalcType: Option; GenJnlLine: Record "Gen. Journal Line"; SalesHeader: Record "Sales Header"; ServHeader: Record "Service Header"; ApplyingCustLedgEntry: Record "Cust. Ledger Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
