### ISSUE TITLE
Update on below Requests

### ISSUE THREAD

**Issue by srinivasGangadhara** [microsoft/ALAppExtensions#12871]
Please update on below requests, when they are going to release?

#12542
#12543 
#12587 
#12597 
#12598 
#12600 
#12613 
#12614

**Comment by StanPesotskiy** [comment]
Event requests are implemented for version 19.0 and ported down to 18.x, so will be shipped with 18.3.
Enum requests are implemented for version 19.0 and not ported down to the current version according to our policy.
