### ISSUE TITLE
[Event Request] New IntegrationEvent in Codeunit 8905 "Email Message Impl.", function SetRecipients

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#12877]
Hello,

please insert new IntegrationEvent in Codeunit 8905 "Email Message Impl.", function SetRecipients

The Parameters RecipientType & Recipients should get the VAR Property

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetRecipients(Message: Record "Email Message"; var RecipientType: Enum "Email Recipient Type"; var Recipients: List of [Text])
    begin
        // Start kvs.dde
        // Stop kvs.dde
    end;

    procedure SetRecipients(RecipientType: Enum "Email Recipient Type"; Recipients: List of [Text])
    var
        EmailRecipientRecord: Record "Email Recipient";
        UniqueRecipients: Dictionary of [Text, Text];
        Recipient: Text;
    begin
        // Start kvs.dde
        OnBeforeSetRecipients(Message, RecipientType, Recipients)
        // Stop kvs.dde

        EmailRecipientRecord.SetRange("Email Message Id", Message.Id);
        EmailRecipientRecord.SetRange("Email Recipient Type", RecipientType);

        if not EmailRecipientRecord.IsEmpty() then
            EmailRecipientRecord.DeleteAll();

        foreach Recipient in Recipients do begin
            Recipient := DelChr(Recipient, '<>'); // trim the whitespaces around
            if Recipient <> '' then

**Comment by GiorgosPa** [comment]
What do you want to achieve with this event? We cannot provide this event as it will allow a malicious extension to add a malicious recipient and track all the outgoing emails sent out from Business Central

**Comment by danieldetzel** [comment]
I would like to replace always the recipient mail address in test system. We have real customer data but we want to test the Mail functions in sales/purchase.
Without replacement, there is a risk that users will make mistakes and mails from the test system will be sent to real customers.

**Comment by GiorgosPa** [comment]
Well this event won't even help you achieve this as not all emails will go through the email editor page. 

Right now this can be done with a new connector that is set up in use in the test system and that it ignores the recipient values of the message. This connector can send the email by forwarding the altered message to any of the existing connectors.

Another approach would be to introduce this functionality in the main module. We could have a test mode where if enabled all message are sent to a specific address. Would you like to create a Pull Request for this?
