### ISSUE TITLE
Problem on printing Invt. Shipment and Invt. Receipt

### ISSUE THREAD

**Issue by sdelikostov** [microsoft/ALAppExtensions#12879]
In pages 6567 Posted Invt. Receipt, 6569 Posted Invt. Receipts , 6570 Posted Invt. Shipment and 6572 Posted Invt. Shipments  there is a problem when using the button Print - the record was filtered by empty string.
Missing line in a code:
                trigger OnAction()
                begin
                    CurrPage.SetSelectionFilter(InvtShptHeader);
                    InvtShptHeader.PrintRecords(true);
                end;
Should be:
                trigger OnAction()
                begin
                    InvtShptHeader := Rec;
                    CurrPage.SetSelectionFilter(InvtShptHeader);
                    InvtShptHeader.PrintRecords(true);
                end;
(reference page 132 Posted Sales Invoice)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
