### ISSUE TITLE
[ENUM REQUEST] Same document type in intercompany documents for header and lines

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#12870]
The IC Inbox Sales Line has this document type.
table 427 "IC Outbox Sales Line"
```
{
    Caption = 'IC Outbox Sales Line';

    fields
    {
        field(1; "Document Type"; Option)
        {
            Caption = 'Document Type';
            Editable = false;
            OptionCaption = 'Order,Invoice,Credit Memo,Return Order';
            OptionMembers = "Order",Invoice,"Credit Memo","Return Order";
        }
...
```

But the IC Inbox Sales Header has an enum for the document type. So I can only extend the header. This should be the same.
```table 434 "IC Inbox Sales Header"
{
    Caption = 'IC Inbox Sales Header';

    fields
    {
        field(1; "Document Type"; Enum "IC Sales Document Type")
        {
            Caption = 'Document Type';
            Editable = false;
        }
...
```

This affects at least these tables:
Table	427	IC Outbox Sales Line
Table	429	IC Outbox Purchase Line
Table	431	Handled IC Outbox Sales Line
Table	433	Handled IC Outbox Purch. Line
Table	435	IC Inbox Sales Line
Table	437	IC Inbox Purchase Line
Table	439	Handled IC Inbox Sales Line
Table	441	Handled IC Inbox Purch. Line

**Comment by AlexanderYakunin** [comment]
Hello!

This is  already implemented in next major (=19.0). Please do not expect new enum(s) in 18.x versions.
