### ISSUE TITLE
[Exposure request] Publisher Event "OnBeforeCalculateSalesTax" for Report 1305 / 1303 same like 1304

### ISSUE THREAD

**Issue by chavansachin20** [microsoft/ALAppExtensions#12884]
Microsoft has marked reports (204, 205, 206, 207) as "Obsolete" with  Obsolete status "Pending" and Reason "Replaced with the report below Standard.

- Report 204 will be replaced by Report 1304.
- Report 205 will be replaced by Report 1305.
- Report 206 will be replaced by Report 1306.
- Report 207 will be replaced by Report 1307

Current :
As reports will be replaced in future BC releases and we want to add integration to all respective Reports.  Based on old git hub ticket MS added events to 1304 / 1306 / 1307 against https://github.com/microsoft/ALAppExtensions/issues/6507

Report | Comments
-- | --
report&nbsp;1304&nbsp;"Standard&nbsp;Sales&nbsp;-&nbsp;Quote" | MS made changes as requested OnAfterCalculateSalesTax / OnBeforeCalculateSalesTax
report 1305 "Standard Sales - Order Conf." | **_MS changes not found against https://github.com/microsoft/ALAppExtensions/issues/6507_**
report&nbsp;1306&nbsp;"Standard&nbsp;Sales&nbsp;-&nbsp;Invoice" | MS made changes as requested OnAfterCalculateSalesTax / OnBeforeCalculateSalesTax
report&nbsp;1307&nbsp;"Standard&nbsp;Sales&nbsp;-&nbsp;Credit&nbsp;Memo" | MS made changes as requested OnAfterCalculateSalesTax / OnBeforeCalculateSalesTax

<p></p>

Expected : 

- Need publisher event and respective code for OnAfterCalculateSalesTax / OnBeforeCalculateSalesTax on Report 1305
- Need publisher event and respective code for OnAfterCalculateSalesTax / OnBeforeCalculateSalesTax on Report 1303

attached modified and base report object text files for reference.
[Modified AL Reports.zip](https://github.com/microsoft/ALAppExtensions/files/6669865/Modified.AL.Reports.zip)

Versions:
Version: US Business Central 18.0 (Platform 18.0.22893.23773 + Application 18.0.23013.23795)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
