### ISSUE TITLE
Request to add OnBeforeStatisticsAction Event for all Service Module Transaction pages

### ISSUE THREAD

**Issue by chavansachin20** [microsoft/ALAppExtensions#12883]
**Describe the bug**
we have **OnBeforeStatisticsAction** Event for all Sales module transaction pages, but for Service Module same Publisher events are not available. 

**Current behavior**
No Publisher event available in below Service module transaction pages
1. Page	- 5900	- Service Order
2. Page	- 5933	- Service Invoice
3. Page	- 5935	- Service Credit Memo
4. Page	- 5964	- Service Quote
5. Page	- 6050	- Service Contract
6. Page	- 9317	- Service Quotes
7. Page	- 9318	- Service Orders
8. Page	- 9319	- Service Invoices
9. Page	- 9320	- Service Credit Memos
10. Page	- 9321	- Service Contracts

**Expected behavior**
we are requesting for below two changes on above pages
**Change 01** : **Add publisher Event on each transaction page**
`
[IntegrationEvent(false, false)]
    local procedure OnBeforeStatisticsAction(var SalesHeader: Record "Sales Header"; var Handled: Boolean)
    begin
    end;
`
**Change 02** : **Use Handled in OnAction() trigger of Statistics Action**
![image](https://user-images.githubusercontent.com/5293496/120789854-c6016300-c54f-11eb-8fe3-8d512577b608.png)

Thanks 
Sachin Chavan

Ref old ticket : https://github.com/microsoft/AL/issues/6650

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
