### ISSUE TITLE
[Change Request] Codeunit 6500 "Item Tracking Management" – New Event “OnCopyItemLedgEntryTrkgToSalesLnOnBeforeSetQtyBaseToShippedQtyNotReturned”

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#12886]
Could we please have the new event “OnCopyItemLedgEntryTrkgToSalesLnOnBeforeSetQtyBaseToShippedQtyNotReturned” in function “CopyItemLedgEntryTrkgToSalesLn” including a handle pattern?

    procedure CopyItemLedgEntryTrkgToSalesLn(var TempItemLedgEntryBuf: Record "Item Ledger Entry" temporary; ToSalesLine: Record "Sales Line"; FillExactCostRevLink: Boolean; var MissingExCostRevLink: Boolean; FromPricesInclVAT: Boolean; ToPricesInclVAT: Boolean; FromShptOrRcpt: Boolean)
    var
        TempReservEntry: Record "Reservation Entry" temporary;
        ReservEntry: Record "Reservation Entry";
        CopyDocMgt: Codeunit "Copy Document Mgt.";
        ReservMgt: Codeunit "Reservation Management";
        ReservEngineMgt: Codeunit "Reservation Engine Mgt.";
        TotalCostLCY: Decimal;
        ItemLedgEntryQty: Decimal;
        QtyBase: Decimal;
        SignFactor: Integer;
        LinkThisEntry: Boolean;
        EntriesExist: Boolean;
*** start new code ***
        IsHandled: Boolean;
*** stop new code ***
    begin
        if (ToSalesLine.Type <> ToSalesLine.Type::Item) or (ToSalesLine.Quantity = 0) then
…
                    LinkThisEntry := "Entry No." > 0;

                    if FillExactCostRevLink then
*** start new code ***
                    begin
                        IsHandled := false;
                        OnCopyItemLedgEntryTrkgToSalesLnOnBeforeSetQtyBaseToShippedQtyNotReturned("Shipped Qty. Not
                            Returned", ToSalesLine, QtyBase, IsHandled);
                        if not (IsHandled) then
*** stop new code ***
                            QtyBase := "Shipped Qty. Not Returned" * SignFactor
*** start new code ***
                    end
*** stop new code ***
                    else
                        QtyBase := Quantity * SignFactor;
…
*** start new code ***
    [IntegrationEvent(false, false)]
    local procedure OnCopyItemLedgEntryTrkgToSalesLnOnBeforeSetQtyBaseToShippedQtyNotReturned(ShippedQtyNotReturned: Decimal;
    ToSalesLine: Record "Sales Line"; var QtyBase: Decimal; var IsHandled: Boolean);
    begin
    end;
*** stop new code ***

**Comment by Oleg-Romashkov** [comment]
Hi,

The latest version of CopyItemLedgEntryTrkgToSalesLn function code is already updated:
```
                    if FillExactCostRevLink then
                        QtyBase := GetQtyBaseFromShippedQtyNotReturned("Shipped Qty. Not Returned", SignFactor, ToSalesLine)
                    else
                        QtyBase := Quantity * SignFactor;
```

```
    local procedure GetQtyBaseFromShippedQtyNotReturned(ShippedQtyNotReturned: Decimal; SignFactor: Integer; ToSalesLine: Record "Sales Line") Result: Decimal
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetQtyBaseFromShippedQtyNotReturned(ShippedQtyNotReturned, ToSalesLine, Result, IsHandled);
        if IsHandled then
            exit(Result);

        Result := ShippedQtyNotReturned * SignFactor;
    end;
```

Is it ok for you to use existing event OnBeforeGetQtyBaseFromShippedQtyNotReturned?

Rgds,
Oleg.
