### ISSUE TITLE
Fix publisher OnGetJobConsumptionValueEntryFilter codeunit 1012 "Job Jnl.-Post Line"

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#12882]
Can you please fix the publisher, that it uses the local variable JobJounalLine and not the global JobJnlLine. Thx.
    local procedure GetJobConsumptionValueEntry(var ValueEntry: Record "Value Entry"; JobJournalLine: Record "Job Journal Line") Result: Boolean
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetJobConsumptionValueEntry(JobJournalLine, Result, IsHandled, ValueEntry);
        if IsHandled then
            exit(Result);

        with JobJournalLine do begin
            ValueEntry.SetCurrentKey("Job No.", "Job Task No.", "Document No.");
            ValueEntry.SetRange("Item No.", "No.");
            ValueEntry.SetRange("Job No.", "Job No.");
            ValueEntry.SetRange("Job Task No.", "Job Task No.");
            ValueEntry.SetRange("Document No.", "Document No.");      
            ValueEntry.SetRange("Item Ledger Entry Type", ValueEntry."Item Ledger Entry Type"::"Negative Adjmt.");
            ValueEntry.SetRange("Job Ledger Entry No.", 0);
            // -FIX
            //OnGetJobConsumptionValueEntryFilter(ValueEntry, JobJnlLine);
            OnGetJobConsumptionValueEntryFilter(ValueEntry, JobJournalLine);            
            // +FIX
        end;
        exit(ValueEntry.FindSet);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
