### ISSUE TITLE
[Event Request] Codeunit 442 - Sales-Post Prepayments - OnBeforeRunGenJnlPostLine

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12896]
Hi AL-Team,
can you please add the following Publisher in RunGenJnlPostLine?

```
local procedure RunGenJnlPostLine(var GenJnlLine: Record "Gen. Journal Line")
    begin
        // NEW >>>>
        OnBeforeRunGenJnlPostLine(GenJnlLine);
        // NEW <<<
        GenJnlPostLine.RunWithCheck(GenJnlLine);
    end;

[IntegrationEvent(false, false)]
    local procedure OnBeforeRunGenJnlPostLine(var GenJournalLine: Record "Gen. Journal Line")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
