### ISSUE TITLE
[Event Request] To skip testfield(Quantity) in Service Line - Field "Line Amount"

### ISSUE THREAD

**Issue by srinivasGangadhara** [microsoft/ALAppExtensions#12899]
Hi 

we need to Handle Quantity in service line Line Amount OnValidate trigger, for that we need as below Event,

![image](https://user-images.githubusercontent.com/29703512/122507831-8b52fc80-d01e-11eb-837a-d8bcf58a75f3.png)

Thanks!
Regards
srinivas

**Comment by srinivasGangadhara** [comment]
Here you can find the parameters

OnValidate Trigger: 

**field(28; "Line Discount Amount"; Decimal)
        {
            AutoFormatExpression = "Currency Code";
            AutoFormatType = 1;
            Caption = 'Line Discount Amount';

            trigger OnValidate()
            var
                Handle: Boolean;
            begin
                TestStatusOpen;
                GetServHeader;
                OnBeforeQuantityTestfield(Rec, xRec, Handle);
                if not Handle then
                    TestField(Quantity);
                if "Line Discount Amount" <> xRec."Line Discount Amount" then
                    UpdateLineDiscPct;
                "Inv. Discount Amount" := 0;
                "Inv. Disc. Amount to Invoice" := 0;
                Validate("Line Discount %");
            end;
        }**

IntegrationEvent: 

**[IntegrationEvent(false, false)]
    local procedure OnBeforeQuantityTestfield(var ServiceLine: Record "Service Line"; var xServiceLine: Record "Service Line";Handled: Boolean)
    begin
    end;**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
