### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post - OnAfterPostPurchLines

### ISSUE THREAD

**Issue by Magicrevette** [microsoft/ALAppExtensions#12906]
Hello, in codeunit 90 Purch.-Post, in trigger OnRun, I would like to use the event OnAfterPostPurchLines but I miss the parameter TempPurchLineGlobal for my use. Could it be possible to have it added ? Like this : 

        OnAfterPostPurchLines(
          PurchHeader, PurchRcptHeader, PurchInvHeader, PurchCrMemoHeader, ReturnShptHeader, WhseShip, WhseReceive, PurchaseLinesProcessed, SuppressCommit, EverythingInvoiced, TempInvoicePostBuffer, TempPurchLineGlobal); 

With the integration event : 

    [IntegrationEvent(false, false)]
    local procedure OnAfterPostPurchLines(var PurchHeader: Record "Purchase Header"; var PurchRcptHeader: Record "Purch. Rcpt. Header"; var PurchInvHeader: Record "Purch. Inv. Header"; var PurchCrMemoHdr: Record "Purch. Cr. Memo Hdr."; var ReturnShipmentHeader: Record "Return Shipment Header"; WhseShip: Boolean; WhseReceive: Boolean; var PurchLinesProcessed: Boolean; CommitIsSuppressed: Boolean; EverythingInvoiced: Boolean; var TempInvoicePostBuffer: Record "Invoice Post. Buffer" temporary; TempPurchLineGlobal: Record "Purchase Line" temporary)
    begin
    end;

Thnak you for your work.

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
