### ISSUE TITLE
Event Request - OnAfterPostWhseActivityLine

### ISSUE THREAD

**Issue by nmahate** [microsoft/ALAppExtensions#12903]
We are backporting some code for our app. But we're missing an event in codeunit 7324 "Whse.-Activity-Post" for BC15 and BC14

From BC16 onwards we have the following, can we get the same event (same location) in older versions of BC

![image](https://user-images.githubusercontent.com/27202612/122530590-8ab66800-d016-11eb-9c7c-7a802d051f0a.png)

**Comment by Oleg-Romashkov** [comment]
If you need events for for BC15 and BC14 you should open Support Request to CSS through PartnerSource portal or contact your Service Account Manager (SAM) in the local subsidiary.
