### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - function CheckAndUpdate

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12907]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 90 "Purch.-Post" - function CheckAndUpdate

           if Invoice then
                if "Document Type" in ["Document Type"::Invoice, "Document Type"::"Credit Memo"] then begin
                    CalcFields(Amount, "Amount Including VAT");
                    CheckDocumentTotalAmounts(PurchHeader);
                end;

            // DINNL <<
            OnCheckAndUpdateOnBeforeLockTables(PurchHeader);
            // DINNL >>
            LockTables(PurchHeader);

            SourceCodeSetup.Get();
            SrcCode := SourceCodeSetup.Purchases;

        [IntegrationEvent(false, false)]
        local procedure OnCheckAndUpdateOnBeforeLockTables(var PurchaseHeader: Record "Purchase Header")

**Comment by AlexanderYakunin** [comment]
We already have event OnBeforeLockTables(PurchHeader, PreviewMode, SuppressCommit);
