### ISSUE TITLE
[Event Request] Codeunit "Item Jnl.-Post Line", Procedure "CalcCapLedgerEntriesSetupRunTime"

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#12901]
We need a new Publisher to apply some more filters to table "CapLedgerEntry"
![image](https://user-images.githubusercontent.com/40287548/122530155-7d04e080-d01e-11eb-84fb-155bc822ab62.png)

Please add the following Parameter
![image](https://user-images.githubusercontent.com/40287548/122530289-9dcd3600-d01e-11eb-9bbd-07a3f7e24bf8.png)

Thanks!

**Comment by Oleg-Romashkov** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
