### ISSUE TITLE
[Event Request] Codeunit 7324 "Whse.-Activity-Post" - function Code

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12908]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 7324 - function Code

            // Check Lines
            OnBeforeCheckLines(WhseActivHeader);
            LineCount := 0;
            if WhseActivLine.Find('-') then begin
                TempWhseActivLine.SetCurrentKey(
                  "Source Type", "Source Subtype", "Source No.", "Source Line No.", "Source Subline No.");
                repeat
                    LineCount := LineCount + 1;
                    if not HideDialog then
                        Window.Update(2, LineCount);
                    WhseActivLine.TestField("Item No.");
                    if Location."Bin Mandatory" then begin
                        WhseActivLine.TestField("Unit of Measure Code");
                        WhseActivLine.TestField("Bin Code");
                    end;
                    // DINNL <<
                    OnAfterCodeCheckLines(WhseActivLine, WhseActivHeader);
                    // DINNL >>
                    ItemTrackingRequired := CheckItemTracking(WhseActivLine);
                    InsertTempWhseActivLine(WhseActivLine, ItemTrackingRequired);
                until WhseActivLine.Next() = 0;
                CheckWhseItemTrackingAgainstSource();
            end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCodeCheckLines(var WarehouseActivityLine: Record "Warehouse Activity Line"; var WarehouseActivityHeader: Record "Warehouse Activity Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
