### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - function PostPurchLine

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12909]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 90 "Purch.-Post" - function PostPurchLine:

             OnAfterPurchInvLineInsert(
               PurchInvLine, PurchInvHeader, PurchLine, ItemLedgShptEntryNo, WhseShip, WhseReceive, SuppressCommit);
             CreatePostedDeferralScheduleFromPurchDoc(xPurchLine, PurchInvLine.GetDocumentType,
               PurchInvHeader."No.", PurchInvLine."Line No.", PurchInvHeader."Posting Date");
              // DINNL <<
               OnAfterCreatePostedDeferralScheduleFromPurchDoc(xPurchLine, PurchInvLine."Document No.", 
                 PurchInvLine."Line No.", PurchInvLine."Quantity (Base)");
              // DINNL >>
           end;

     local procedure OnAfterCreatePostedDeferralScheduleFromPurchDoc(TempPurchLine: Record "Purchase Line" temporary;  
       DocumentNo: Code[20]; LineNo: Integer; QuantityBase: Decimal)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
