### ISSUE TITLE
[Event Request] codeunit 5802 "Inventory Posting To G/L". - Add parameter to function OnSetAccNoOnBeforeCheckAccNo

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12905]
Dear ALAppExtensions Team,

Is it possible to add a VAR parameter to function OnSetAccNoOnBeforeCheckAccNo in codeunit 5802 "Inventory Posting To G/L"?

-OnSetAccNoOnBeforeCheckAccNo(InvtPostBuf, InvtPostingSetup, GenPostingSetup, CalledFromItemPosting);
+OnSetAccNoOnBeforeCheckAccNo(InvtPostBuf, InvtPostingSetup, GenPostingSetup, CalledFromItemPosting,ValueEntry);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
