### ISSUE TITLE
Document Attachment Details - Access to FromRecRef

### ISSUE THREAD

**Issue by evoaaron** [microsoft/ALAppExtensions#12919]
We're trying to extend the Document Attachment Details page on BC18 & put our own behavior into the OnDrillDown trigger for the Name control. 

As the global variable FromRecRef is not accessible to page extensions it's limiting our ability to do this without also extending the Document Attachment Factbox and calling our own procedure immediately after OpenForRecRef(RecRef: RecordRef). 

As a result we have to override the OnDrillDown on the Documents control and duplicate the standard code, just adding in our function to pass the same instance of the RecordRef over. 

Could the FromRecRef variable on the Document Attachment Details be marked as protected in a future release?
That way we can access it directly in our page extensions.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
