### ISSUE TITLE
[Event Modification Request] Service Line table procedure ReplaceServItem 

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#12918]
(1) Within the protected procedure ReplaceServItem() , there is an existing event, OnReplaceServItemOnAfterAssignVariantCode().  Is it possible to add an extra parameter 'IsHandled'?  

From OnReplaceServItemOnAfterAssignVariantCode(Rec, ServItemReplacement, SerialNo);
to OnReplaceServItemOnAfterAssignVariantCode(Rec, ServItemReplacement, SerialNo, IsHandled);

(2) There is also a local procedure ClearFields() in Service Line table.  Is it possible to make it a Protected Procedure so we can access it from an event?  

from local procedure ClearFields() to Protected procedure ClearFields()

Thank you very much.

**Comment by AlexanderYakunin** [comment]
1. We can add IsHandled as parameter but how it should be used. To handle which code?
2. Please do not ask for event and protected in same request, as we can have one tag only. And we merge events only to 18.x, not protected.

**Comment by Teming** [comment]
Created ticket 13085 for the second one.  Thanks.

**Comment by Teming** [comment]
For (1) 
From  
            "Variant Code" := VariantCode;
            OnReplaceServItemOnAfterAssignVariantCode(Rec, ServItemReplacement, SerialNo);
            Validate(Quantity, 1);
            TempTrackingSpecification.DeleteAll();
            TempTrackingSpecification."Serial No." := SerialNo;
            TempTrackingSpecification."Variant Code" := VariantCode;
            TempTrackingSpecification.Insert();
            if "Line No." <> 0 then
                InsertItemTracking;
            case ServItemReplacement.ReturnReplacement of
                0:
                    "Spare Part Action" := "Spare Part Action"::"Temporary";
                1:
                    "Spare Part Action" := "Spare Part Action"::Permanent;
            end;
            "Copy Components From" := ServItemReplacement.ReturnCopyComponentsFrom;
            OnReplaceServItemOnCopyFromReplacementItem(Rec);
            exit(true);
        end;
        ServiceLineReserve.DeleteLine(Rec);

to

            "Variant Code" := VariantCode;
            OnReplaceServItemOnAfterAssignVariantCode(Rec, ServItemReplacement, SerialNo, IsHandled);
            If Not IsHandled then begin    // Add this one please
              Validate(Quantity, 1);
              TempTrackingSpecification.DeleteAll();
              TempTrackingSpecification."Serial No." := SerialNo;
              TempTrackingSpecification."Variant Code" := VariantCode;
              TempTrackingSpecification.Insert();
              if "Line No." <> 0 then
                InsertItemTracking;
              case ServItemReplacement.ReturnReplacement of
                0:
                    "Spare Part Action" := "Spare Part Action"::"Temporary";
                1:
                    "Spare Part Action" := "Spare Part Action"::Permanent;
                 end;
              end;    //Add this one 
            "Copy Components From" := ServItemReplacement.ReturnCopyComponentsFrom;
            OnReplaceServItemOnCopyFromReplacementItem(Rec);
            exit(true);
        end;
        ServiceLineReserve.DeleteLine(Rec);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
