### ISSUE TITLE
[Event Request] Codeunit 7324 "Whse.-Activity-Post" - function InitSourceDocument

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#12911]
Dear ALAppExtensions Team,

We would like to request the following event publishers in codeunit 7324 - function InitSourceDocument

1.        with WhseActivHeader do
            case "Source Type" of
                DATABASE::"Purchase Line":
                    begin
                        PurchHeader.Get("Source Subtype", "Source No.");
                        PurchLine.SetRange("Document Type", "Source Subtype");
                        PurchLine.SetRange("Document No.", "Source No.");
                        // DINNL <<
                        OnInitSourceDocumentOnAfterSetPurchaseLineFilters(PurchLine);
                        // DINNL >>
                        if PurchLine.Find('-') then
                            repeat

    [IntegrationEvent(false, false)]
    local procedure OnInitSourceDocumentOnAfterSetPurchaseLineFilters(var PurchaseLine: Record "Purchase Line")
    begin
    end;

2.                DATABASE::"Sales Line":
                    begin
                        SalesHeader.Get("Source Subtype", "Source No.");
                        SalesLine.SetRange("Document Type", "Source Subtype");
                        SalesLine.SetRange("Document No.", "Source No.");
                        if SalesHeader."Shipping Advice" = SalesHeader."Shipping Advice"::Complete then
                            SalesLine.SetRange(Type, SalesLine.Type::Item);
                        // DINNL <<
                        OnInitSourceDocumentOnAfterSetSalesLineFilters(SalesLine);
                        // DINNL >>
                        if SalesLine.Find('-') then

    [IntegrationEvent(false, false)]
    local procedure OnInitSourceDocumentOnAfterSetSalesLineFilters(var SalesLine: Record "Sales Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
