### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post". - Add parameters to function OnAfterUpdatePurchLineBeforePost

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12917]
Dear ALAppExtensions Team,

Is it possible to add 2 parameters to function OnAfterUpdatePurchLineBeforePost in codeunit 90 "Purch.-Post"?

-OnAfterUpdatePurchLineBeforePost(PurchLine, WhseShip, WhseReceive);
+OnAfterUpdatePurchLineBeforePost(PurchLine, WhseShip, WhseReceive, PurchHeader, RoundingLineInserted);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
