### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - function PostAssocItemJnlLine

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12915]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 90 "Purch.-Post" - function PostAssocItemJnlLine

           TransferReservToItemJnlLine(SalesOrderLine, ItemJnlLine, PurchLine, QtyToBeShippedBase, true);
            OnBeforePostAssocItemJnlLine(ItemJnlLine, SalesOrderLine, SuppressCommit, PurchLine);
            RunItemJnlPostLine(ItemJnlLine);
            // DINNL <<
            DINOnAfterPostAssocItemJnlLine(ItemJnlLine."Document No.", ItemJnlPostLine);
            // DINNL >>

            local procedure DINOnAfterPostAssocItemJnlLine(DocumentNo: Code[20]; var ItemJnlPostLine: Codeunit "Item Jnl.-Post 
            Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
