### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - function PostItemChargePerSalesShpt

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12914]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 90 "Purch.-Post" - function PostItemChargePerSalesShpt

    local procedure PostItemChargePerSalesShpt(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line")
    var
        SalesShptLine: Record "Sales Shipment Line";
        TempItemLedgEntry: Record "Item Ledger Entry" temporary;
        ItemTrackingMgt: Codeunit "Item Tracking Management";
        Sign: Decimal;
        DistributeCharge: Boolean;
        IsHandled: Boolean;
    begin
        // DINNL <<
        DINPurchPostOnBeforePostItemChargePerSalesShpt(TempItemChargeAssgntPurch, PurchLine);
        // DINNL >>
        if not SalesShptLine.Get(
             TempItemChargeAssgntPurch."Applies-to Doc. No.", TempItemChargeAssgntPurch."Applies-to Doc. Line No.")
        then
            Error(RelatedItemLedgEntriesNotFoundErr);

    [IntegrationEvent(false, false)]
    local procedure DINPurchPostOnBeforePostItemChargePerSalesShpt(var TempItemChargeAssignmentPurch: Record "Item 
        Charge Assignment (Purch)"; var PurchaseLine: Record "Purchase Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
