### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post". - Add parameter to function OnAfterInitAssocItemJnlLine

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#12916]
Dear ALAppExtensions Team,

Is it possible to add a parameter to function OnAfterInitAssocItemJnlLinein codeunit 90 "Purch.-Post"?

-OnAfterInitAssocItemJnlLine(ItemJnlLine, SalesOrderHeader, SalesOrderLine, PurchHeader);
+OnAfterInitAssocItemJnlLine(ItemJnlLine, SalesOrderHeader, SalesOrderLine, PurchHeader, QtytoBeShipped);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
