### ISSUE TITLE
[Event Request] Service Line table GETSKU() Function

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#12921]
Existing Codes:
procedure GetSKU() Result: Boolean
    begin
        if (SKU."Location Code" = "Location Code") and
           (SKU."Item No." = "No.") and
           (SKU."Variant Code" = "Variant Code")
        then
            exit(true);
        if SKU.Get("Location Code", "No.", "Variant Code") then
            exit(true);

        Result := false;
        OnAfterGetSKU(Rec, Result);
    end;
-------------------------------------------------------------------------
Event Request:

procedure GetSKU() Result: Boolean
    begin
  ****OnBeforeGetSKU(Rec, Result, IsHandled);      
  ****if IsHandled then
  ****     exit(Result);

        if (SKU."Location Code" = "Location Code") and
           (SKU."Item No." = "No.") and
           (SKU."Variant Code" = "Variant Code")
        then
            exit(true);
        if SKU.Get("Location Code", "No.", "Variant Code") then
            exit(true);

        Result := false;
        OnAfterGetSKU(Rec, Result);
    end;

[IntegrationEvent(false, false)]
    local procedure OnBeforeGetSKU(ServiceLine: Record "Service Line"; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
