### ISSUE TITLE
[Event Request] Service Line table procedure UpdateAmounts()

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#12920]
Existing codes:
procedure UpdateAmounts()
    var
        CustCheckCrLimit: Codeunit "Cust-Check Cr. Limit";
        ExpectedLineAmount: Decimal;
    begin
        if GuiAllowed and (CurrFieldNo <> 0) then
            ConfirmAdjPriceLineChange;
.
.
.
.        
        if ServHeader."Tax Area Code" = '' then
            UpdateVATAmounts;

        InitOutstandingAmount;
        if not IsCustCrLimitChecked and (CurrFieldNo <> 0) then begin
            IsCustCrLimitChecked := true;
            CustCheckCrLimit.ServiceLineCheck(Rec);
        end;
        UpdateRemainingCostsAndAmounts;
    end;
--------------------------------------------------------------------------------------------
Event Requested 

procedure UpdateAmounts()
    var
        CustCheckCrLimit: Codeunit "Cust-Check Cr. Limit";
        ExpectedLineAmount: Decimal;
    begin
        if GuiAllowed and (CurrFieldNo <> 0) then
            ConfirmAdjPriceLineChange;
.
.
.
.        
        if ServHeader."Tax Area Code" = '' then
            UpdateVATAmounts;

        InitOutstandingAmount;
*****OnServiceLineUpdateAmountbeforeCustCrLimitCheck(Rec, IsCustCrLimitChecked, CurrFieldNo, IsHandled);
*****if not IsCustCrLimitChecked and (CurrFieldNo <> 0) **and (not Ishandled)** then begin
            IsCustCrLimitChecked := true;
            CustCheckCrLimit.ServiceLineCheck(Rec);
        end;
        UpdateRemainingCostsAndAmounts;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnServiceLineUpdateAmountbeforeCustCrLimitCheck(var ServiceLine: Record "Service Line"; IsCustCrLimitChecked: Boolean; CurrFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
