### ISSUE TITLE
[Event Modification] Codeunit 22 "Item Jnl.-Post Line" – Signature modification for event “OnInsertOHValueEntryOnBeforeInsertValueEntry”

### ISSUE THREAD

**Issue by andersnordmann** [microsoft/ALAppExtensions#12927]
Hi

Is it possible for us to get the publisher “OnInsertOHValueEntryOnBeforeInsertValueEntry” in Function “InsertOHValueEntry” in Codeunit 22 "Item Jnl.-Post Line” changed to the below signature?:

    IsHandled := false;
    // >> Modification
    OnInsertOHValueEntryOnBeforeInsertValueEntry(ValueEntry, ItemJnlLine, GlobalItemLedgEntry, ValueEntryNo, IsHandled);
    // << Modification
    if not IsHandled then

    [IntegrationEvent(true, false)]
    // >> Modification
    local procedure OnInsertOHValueEntryOnBeforeInsertValueEntry(var ValueEntry: Record "Value Entry"; ItemJnlLine: Record "Item Journal Line"; var GlobalItemLedgEntry: Record "Item Ledger Entry"; var ValueEntryNo: Integer; var IsHandled: Boolean)
    // << Modification
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
