### ISSUE TITLE
Misc typo

### ISSUE THREAD

**Issue by j2associates** [microsoft/ALAppExtensions#12922]
Validates whether a text can be encoded. The validation is based at a regular expression accoring to

should be

Validates whether a text can be encoded. The validation is based at a regular expression according to

**Comment by StanPesotskiy** [comment]
Can you share more context, repro steps? Where do you get this message?

**Comment by pri-kise** [comment]
See: https://github.com/microsoft/ALAppExtensions/blob/a598cfc8f86aa68891983abe5225e8030bb340f8/Modules/System/Barcode/src/Barcode%20Font%20Provider/BarcodeFontEncoder.Interface.al#L21

**Comment by JesperSchulz** [comment]
Thanks :-) We'll get that fixed.

**Comment by j2associates** [comment]
These are both from a598cfc8f8
ALAppExtensions/Modules/System/Barcode/src/Barcode Font Provider/BarcodeFontEncoder.Interface.al
https://github.com/microsoft/ALAppExtensions/blob/a598cfc8f86aa68891983abe5225e8030bb340f8/Modules/System/Barcode/src/Barcode%20Font%20Provider/BarcodeFontEncoder.Interface.al#L21

1. Comments for 
procedure IsValidInput(InputText: Text; var BarcodeEncodeSettings: Record "Barcode Encode Settings"): Boolean;

Actually,

Validates whether a text can be encoded. The validation is based **at** a regular expression according to

should be

Validates whether a text can be encoded. The validation is based **on** a regular expression according to

2. Just above are comments for
procedure EncodeFont(InputText: Text; var BarcodeEncodeSettings: Record "Barcode Encode Settings"): Text;

Encodes **a** input text to a barcode font.

should be

Encodes **an** input text to a barcode font.

Thanks

**Comment by j2associates** [comment]
As I was checking out #12922, I noticed another misc typo in the
documentation for the previous method. I added a comment there pertaining
to the typo.

Thanks

**Comment by JesperSchulz** [comment]
I noticed and fixed the at -> on, when I was correcting the typo. That one is already being processed in our build system :-) The a -> an I didn't spot :-S 
We should get a spell checker on our code comments. Currently, you need to enable it in VSCode yourself. Clearly, not all developers are doing so...

**Comment by j2associates** [comment]
How do you enable Spell Checking for document comments in VS Code?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
