### ISSUE TITLE
[Event Change] Codeunit 408 - "DimensionManagement" - OnBeforeCheckDim

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12931]
Hi al-Team,

I would like to change the Company on the variable Dim. Can you add the parameter Dim per var for this?

```
[IntegrationEvent(false, false)]
    // NEW >>>>
    // local procedure OnBeforeCheckDim(DimCode: Code[20]; var Result: Boolean; var IsHandled: Boolean)
    local procedure OnBeforeCheckDim(DimCode: Code[20]; var Result: Boolean; var IsHandled: Boolean; var Dim: Record Dimension)
    // NEW <<<<
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
