### ISSUE TITLE
[Event Request] Codeunit 2000000005 "Reporting Triggers" - OnAfterDocumentPrinted

### ISSUE THREAD

**Issue by TCMatthiasMartin** [microsoft/ALAppExtensions#12936]
Hi al-Team,

can you add an event like "OnAfterDocumentPrinted" with the following parameters:

`OnAfterDocumentPrinted(ObjectType: Option "Report","Page"; ObjectId: Integer; ReportAction: Option SaveAsPdf,SaveAsWord,SaveAsExcel,Preview,Print,SaveAsHtml; ObjectPayload: JsonObject; DocumentStream: InStream; var Success: Boolean);`

It would be perfect to use it; everytime a document was printed or send.
This event would make it possible to get the original document that was send to a customer. 
If we have the original document, we're able to save it into a DMS. 
In germany it's necessery to save the original file.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Codeunit 2000000005 "Reporting Triggers" is part of the platform. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
