### ISSUE TITLE
[REQUEST-FOR-EXTERNAL] Table 5965 "Service Contract Header" Function CalculateEndPeriodDate

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#12935]
Can you make CalculateEndPeriodDate to be global/external, curently it is local.
I have subscribed to Event OnBeforeValidateNextInvoicePeriod and I would like to call this function

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
