### ISSUE TITLE
[Event Change] Codeunit 408 - "DimensionManagement" - OnBeforeCheckDimValuePosting

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12930]
Hi al-Team,

I would like to change the Company on the variable DimSetEntry. Can you add the parameter DimSetEntry per var for this?

```
[IntegrationEvent(false, false)]
    // NEW >>>>
    // local procedure OnBeforeCheckDimValuePosting(TableID: array[10] of Integer; No: array[10] of Code[20]; DimSetID: Integer; var IsChecked: Boolean; var IsHandled: Boolean)
    local procedure OnBeforeCheckDimValuePosting(TableID: array[10] of Integer; No: array[10] of Code[20]; DimSetID: Integer; var IsChecked: Boolean; var IsHandled: Boolean; var DimSetEntry: Record "Dimension Set Entry")
    // NEW <<<<
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
