### ISSUE TITLE
[Event Change] Codeunit 311 "Item-Check Avail." OnCalculateOnBeforeCalcInitialQtyAvailable

### ISSUE THREAD

**Issue by LucaDonatoSEDP** [microsoft/ALAppExtensions#12938]
Hi all,

Can you modify the parameters SchedRcpt,ReservedRcpt,GrossReq,ReservedReq of event OnCalculateOnBeforeCalcInitialQtyAvailable in var?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by rstefanetti** [comment]
Great!
