### ISSUE TITLE
[Event Change] Codeunit 5895 - "Inventory Adjustment" - OnMakeSingleLevelAdjmtOnAfterUpdateItemUnitCost

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#12934]
Hi al-Team,

Can you add the parameter IsOnlineAdjmt to OnMakeSingleLevelAdjmtOnAfterUpdateItemUnitCost?

```
[IntegrationEvent(false, false)]
    // NEW >>>>
    // local procedure OnMakeSingleLevelAdjmtOnAfterUpdateItemUnitCost(var TheItem: Record Item; var TempAvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point" temporary; var LevelExceeded: Boolean)
    local procedure OnMakeSingleLevelAdjmtOnAfterUpdateItemUnitCost(var TheItem: Record Item; var TempAvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point" temporary; var LevelExceeded: Boolean; IsOnlineAdjmt: Boolean)
    // NEW <<<<
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
