### ISSUE TITLE
[Event Request / Expose Functions] 1218 "Map Incoming Doc to Purch Doc"

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#12944]
- [x] OnBeforeProcessIntermediateData

We would like to manipulate some of the IntermediateDataImport records first before processing. 

Signature: 

`OnBeforeProcessIntermediateData(DataExch: Record "Data Exch.")`

Location:
```

procedure ProcessIntermediateData(DataExch: Record "Data Exch.")
    begin
        OnBeforeProcessIntermediateData(DataExch); // NVT

        ProcessHeaders(DataExch);
```

- [x] OnAfterProcessLines

When an UBL '**Freight** Invoice' is imported, we not only import the purchase header and lines, but want to import 'detail' records as well (custom table). This can be achieved after the ProcessLines

Signature: 

`procedure OnAfterProcessLines(PurchaseHeader: Record "Purchase Header"; DataExch: Record "Data Exch."; ParentRecordNo: Integer)`

Location

![image](https://user-images.githubusercontent.com/25268332/122892902-1cd7ac80-d346-11eb-904f-0760b8f68b4d.png)

- [x] OnCreateNewPurchHdrBeforeInsert

In the BE version, we need to select a 'Journal Template' before creating a purchase document (invoice). This is a field required to define the no. series of the purchase header. So, next to the 'document type', the 'journal template' field needs to be set before insert.

Signature

`procedure OnCreateNewPurchHdrOnBeforeInsert(var RecRef: RecordRef; var IntermediateDataImport: Record "Intermediate Data Import")`

Location

![image](https://user-images.githubusercontent.com/25268332/122895791-bb650d00-d348-11eb-8e6d-9ee768c56f2f.png)

- [ ] ProcessField, GetValueFromIntermediate, IsFieldProcessed

Please make the functions global, so we can process our own fields (in OnAfterProcessLines).

**Comment by Stepanenko-Vadim** [comment]
In the future please stick to 1-2 requests of the same type per issue, so that the request types are not mixed up, I've implemented the requested events, the extensibility request such as making variables global should come in a separate issue if you still need those.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
