### ISSUE TITLE
[Request-for-External] Page 1350 "Posted Sales Shipmetn - Update" - procedure SetRec

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/ALAppExtensions#12947]
Please remove the 

[Scope('OnPrem')]

from the function.  The function is required to be able to load the shipment into the temporary table for update

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
