### ISSUE TITLE
[Bug] Report 7390 "Whse. Calculate Inventory" - Items Not on Inventory not working from 18.1

### ISSUE THREAD

**Issue by PunkyGP** [microsoft/ALAppExtensions#12946]
Hello,

currently we are upgrading our product to 18.2. Now we found a bug in Report 7390 "Whse. Calculate Inventory".
Luckily we had enough Testcodeunits and we noticed there was something changed in the default behaviour.

On Report 7390 "Whse. Calculate Inventory", there is a option to include items without inventory in the journal.
<img width="605" alt="Screen Shot 2021-06-22 at 12 34 17" src="https://user-images.githubusercontent.com/16012756/122910268-4bf61a00-d356-11eb-9b3d-fef454d4b574.png">

But this boolean isn't working anymore due to the following update. The remove of a ";" makes a big difference and will break the normal behaviour.
<img width="1863" alt="Screen Shot 2021-06-22 at 12 04 22" src="https://user-images.githubusercontent.com/16012756/122910414-70ea8d00-d356-11eb-9447-3b794954793d.png">

Maybe this is a fix.
<img width="605" alt="Screen Shot 2021-06-22 at 12 40 05" src="https://user-images.githubusercontent.com/16012756/122910969-169dfc00-d357-11eb-8cdb-6a1dc772c726.png">

Kind regards,
Gunter Peeters

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
