### ISSUE TITLE
[Protected var & Protected procedure Request] Report 698 - Get Sales Orders - protected var ReqWkshName, LineNo, SpecOrder, ReqLine, and protected procedure InsertReqWkshLine

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#12943]
Through this issue we would like to request procedure InsertReqWkshLine, and certain global vars to become protected.

```al
    protected var
        ReqWkshName: Record "Requisition Wksh. Name";
        LineNo: Integer;
        SpecOrder: Integer;
        ReqLine: Record "Requisition Line";

    var
        Text000: Label 'Processing sales lines  #1######';
        Text001: Label 'There are no sales lines to retrieve.';
        ReqWkshTmpl: Record "Req. Wksh. Template";
        // ReqWkshName: Record "Requisition Wksh. Name";
        // ReqLine: Record "Requisition Line";
        SalesHeader: Record "Sales Header";
        PurchasingCode: Record Purchasing;
        ItemTrackingMgt: Codeunit "Item Tracking Management";
        LeadTimeMgt: Codeunit "Lead-Time Management";
        UOMMgt: Codeunit "Unit of Measure Management";
        Window: Dialog;
        LineCount: Integer;
        // SpecOrder: Integer;
        GetDim: Option Item,"Sales Line";
        // LineNo: Integer;


    // local procedure InsertReqWkshLine(SalesLine: Record "Sales Line")
    protected procedure InsertReqWkshLine(SalesLine: Record "Sales Line")
```

Existing local procedure InsertReqWkshLine(SalesLine: Record "Sales Line") is the hart of the creation of Requistion Lines from Sales Lines with a Purchasing Code in Business Central (Drop Shipment or Special Order) .

Therefore several Event Publishers are implemented already in this function, and therefore this function must be used to create Requistion Lines from Sales Lines with a Purchasing Code.

Therefore opening up this report by means of protected vars and a protected procedure InsertReqWkshLine would be a great step forward in terms of expandability.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
