### ISSUE TITLE
[Event Request] Report 6655 "Batch Post Sales Return Orders"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#12945]
Please add a new event OnBeforeSalesBatchPostMgt in Report 6655. This is already realised in Report 296 "Batch Post Sales Orders":

            trigger OnPreDataItem()
            var
                SalesBatchPostMgt: Codeunit "Sales Batch Post Mgt.";
            begin
               //+++++++++++++++++++++++++++++
                OnBeforeSalesBatchPostMgt(var "Sales Header", var ReceiveReq, var InvReq);
             //-------------------------------------

                SalesBatchPostMgt.SetParameter("Batch Posting Parameter Type"::Receive, ReceiveReq);
                SalesBatchPostMgt.SetParameter("Batch Posting Parameter Type"::Print, PrintDoc);
                SalesBatchPostMgt.RunBatch("Sales Header", ReplacePostingDate, PostingDateReq, ReplaceDocumentDate, CalcInvDisc, false, InvReq);

                CurrReport.Break();
            end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
