### ISSUE TITLE
[event request] Sales Inv. Header - Edit

### ISSUE THREAD

**Issue by TheDenSter** [microsoft/ALAppExtensions#12953]
This is about codeunit 1409 "Sales Inv. Header - Edit". We're finally getting an "Update Document" for the posted sales invoice in 18.3, but it does not have an event to extend it. Would be great if you could rectify this before 18.3 comes out, so I don't have to have two update functions on the posted sales invoice.

Please add this event:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesInvHeaderModify(var SalesInvHeader: Record "Sales Invoice Header"; SalesInvHeaderRec: Record "Sales Invoice Header")
    begin
    end;
```

And raise it before SalesInvoiceHeader.TestField.

You can look at codeunit 1405 "Purch. Inv. Header - Edit" for how this works for the purchase invoice.

**Comment by TheDenSter** [comment]
One other thing you need there is an 'OnAfterRecordChanged' event in the "Posted Sales Inv. - Update" page (number 1355) to catch record changes. See page 1354 "Pstd. Sales Cr. Memo - Update" for how that works on the Credit Memo side.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
