### ISSUE TITLE
[Event Request] Page Item Tracking Lines - OnbeforeSerialNo/LotNoAssistEdit

### ISSUE THREAD

**Issue by TCutullic** [microsoft/ALAppExtensions#12957]
Hi, is it possible to have one more parameter (MaxQuantity) in OnBeforeSerialNoAssistEdit pls ?
![image](https://user-images.githubusercontent.com/70213459/123075981-fdf61a80-d418-11eb-9a06-7aaf309ce7ed.png)

Furthermore, can we have the sames procedure in Lot No AssistEdit pls (with IsHandled) ?
![image](https://user-images.githubusercontent.com/70213459/123076576-91c7e680-d419-11eb-93e3-d35a06466885.png)

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
