### ISSUE TITLE
[Request for External] Codeunit 5940 ServContractManagement Function CheckServiceContractHeaderAmts

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#12968]
This Function is set to local even if the parameter is var and is changed within the function.

I am changing behaviour of CreateServiceLedgerEntry function from Codeunit 5940 ServContractmanagement, and it would be really nice that I can access all functions that are currently set to local but actually they are not dependent on Codeunit as all important parameters are sent in a call of functions.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
