### ISSUE TITLE
[Event Request] report 594 Get Item Ledger Entries - OnBeforeHasCrossedBorder

### ISSUE THREAD

**Issue by nicmartino** [microsoft/ALAppExtensions#12962]
[Event Request]
Object: Report 594 Get Item Ledger Entries
Procedure: HasCrossedBorder()
Event: OnBeforeHasCrossedBorder (ItemLedgEntry: Record "Item Ledger Entry"; var HasCrossed: Boolean; var IsHandled: Boolean)

     ........
     local procedure HasCrossedBorder(ItemLedgEntry: Record "Item Ledger Entry"): Boolean
     var
          ItemLedgEntry2: Record "Item Ledger Entry";
          Location: Record Location;
          Include: Boolean;
          isHandled: Boolean;
          HasCrossed: Boolean;
     begin
          isHandled:= false;
          OnBeforeHasCrossedBorder (ItemLedgEntry, HasCrossed, IsHandled);
          if IsHandled then
               exit(HasCrossed);
          with ItemLedgEntry do
      ........

Could you please add this event?
Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
