### ISSUE TITLE
[Event Request] Codeunit 12 - Pass Detailed CV Ledg. Entry Buffer by VAR

### ISSUE THREAD

**Issue by Joneleth84** [microsoft/ALAppExtensions#12977]
Hi!

Please consider passing Buffer tables by VAR, especially via

- OnPostDtldCustLedgEntriesOnBeforeCreateGLEntriesForTotalAmounts
- OnPostDtldVendLedgEntriesOnBeforeCreateGLEntriesForTotalAmounts

![24-06-_2021_16-04-01](https://user-images.githubusercontent.com/56401325/123277135-20199680-d506-11eb-98db-fd6d62fe6424.jpg)

Thank you and best regards,
Johannes

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
