### ISSUE TITLE
[Request for External] Codeunit 5940 ServContractManagement Function SetServLedgEntryAmounts

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#12974]
This Function is set to local even if the parameter is var and is changed within the function.

I am changing behaviour of CreateServiceLedgerEntry function from Codeunit 5940 ServContractmanagement, and it would be really nice that I can access all functions that are currently set to local but actually they are not dependent on Codeunit as all important parameters are sent in a call of functions.

**Comment by AlexanderYakunin** [comment]
Already made global
