### ISSUE TITLE
Shortcut Dimension 1 & 2 Code Missing from Invoice Aggregates

### ISSUE THREAD

**Issue by kculpepperhpc** [microsoft/ALAppExtensions#12979]
Trying to use the Purch/Sales Aggregates for my API Pages and noticed that the `Shortcut Dimension 1 Code` and `Shortcut Dimension 2 Code` properties are missing.  See below referenced Page:

https://github.com/microsoft/ALAppExtensions/blob/master/Apps/W1/APIV2/app/src/pages/APIV2SalesInvoices.Page.al

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
