### ISSUE TITLE
Local functions Table 31020 "Purch. Advance Letter Header"

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#12984]
Please remove local from functions: 

local procedure UpdateCurrencyFactor()
local procedure UpdateVATCurrencyFactor()

**Comment by fridrichovsky** [comment]
Hello I would like ask you if you have any information about my request. We need process our issue.

**Comment by Jiribu73** [comment]
@AlexanderYakunin - we need any reaction.
It is blocking our business and we need to resolve it as soon as possible.
Thanks
Jiří Bureš
CEO

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
