### ISSUE TITLE
[Protection Level] Page Item Tracking Lines - procedure AssignLotNo

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/ALAppExtensions#12982]
Hi Team,

at the moment the protection level is local, but I would like to access it from my PageExtension.
Would be great if you could change the protection level.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
