### ISSUE TITLE
[Enum Request] Page "Item Tracking Lines" Option Controls to Enum

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/ALAppExtensions#12980]
Hi Team,

The Option "Controls: Option Handle,Invoice,Quantity,Reclass,Tracking" please change to Enum.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
