### ISSUE TITLE
Table 31000 "Sales Advance Letter Header".UpdateCurrencyFactor

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#12994]
Please remove local from procedure:
local procedure UpdateCurrencyFactor()

**Comment by fridrichovsky** [comment]
Hello I would like ask you if you have any information about my request. We need process our issue.

**Comment by Jiribu73** [comment]
@AlexanderYakunin - we need any reaction. 
It is blocking our business and we need to resolve it as soon as possible.
Thanks
Jiří Bureš
CEO

**Comment by AlexanderYakunin** [comment]
Please explain your expectations, we implement change to global requests for next major version only. Currently this is October 2021 release.

You can read details in Wiki/FAQ section, I copy it here:

We use labels for categorizing issues into types and tracking the issue lifecycle. Issues fall into the following types:

Enum-request: Request an enum. We implement these only in major releases.
Request-for-external: Request to mark a function as external. We normally only implement these in major releases.
Event-request: Request a new event. We implement these in major and usually next minor releases.
Extensibility-enhancement: Larger suggestions for improving extensibility. We consider these for future releases.
Extensibility-bug: Smaller suggestions for improving extensibility. We consider these for the current release.

**Comment by Jiribu73** [comment]
If you confirm that it will be in the next major version than it should be enought but **we have not received any confirmation** and if it will be only in the next version 190 or in the actual version (180) too.
But we are implementing customer on-prem for the version 180 and could not go-live without all events are done in the Czech legislative module.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Comment by fridrichovsky** [comment]
Hello I would like ask you if you can allow showing code for Czech legislation extensions in NEXT versions. We can't suggest events and other changes for next version before release. If you add some features to major releases only it means that you release version 19 and we will have our suggestion in version 20, becuase we can see code after release in onprem container only.

If we download snadbox for BC18 we can't see code, but if we download onprem container we have there zip files with codes. Problem is that NextMajor and NextMinor version can be download as sandbox only and another problem is that Czech legislation extesions have hide code. It means that "Go to definition" does not work. We have to see the code otherwise it is not possible to develop our products that are dependent on Czech legislation.
