### ISSUE TITLE
Codeunit 80 "Sales-Post".OnDivideAmountOnAfterInitLineDiscountAmount

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#12996]
Please do parameter SalesLine returnable by VAR.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
