### ISSUE TITLE
[Event Request] Codeunit 1013 "Job Jnl.-Post Batch".Code

### ISSUE THREAD

**Issue by giann85** [microsoft/ALAppExtensions#12999]
Please , can you add new event and procedure:

    var (global)
    //-------------------------------OnBeforeCode:BEGIN
        SuppressCommit: Boolean;
    //-------------------------------OnBeforeCode:END

    local procedure "Code"()
    var
        InvtSetup: Record "Inventory Setup";
        InvtAdjmt: Codeunit "Inventory Adjustment";
        UpdateAnalysisView: Codeunit "Update Analysis View";
        UpdateItemAnalysisView: Codeunit "Update Item Analysis View";
        IsHandled: Boolean;
    begin
        with JobJnlLine do begin
            //-------------------------------OnBeforeCode:BEGIN
            OnBeforeCode(JobJnlLine, SuppressCommit);
            //-------------------------------OnBeforeCode:END

      ......................
      ......................

        //-------------------------------OnBeforeCode:BEGIN
        // if not Find('=><') then begin   //OLD CODE
        if not ((Find('=><')) or SuppressCommit) then begin       //NEW CODE
        //-------------------------------OnBeforeCode:END

            "Line No." := 0;
            Commit();
            exit;
        end;

      ......................
      ......................
      ......................
      ......................
      ......................
      ......................

     UpdateAndDeleteLines;
     OnAfterPostJnlLines(JobJnlBatch, JobJnlLine, JobRegNo);

     IF NOT SuppressCommit THEN //-------------------------------OnBeforeCode
            Commit();
      end;
      UpdateAnalysisView.UpdateAll(0, true);
      UpdateItemAnalysisView.UpdateAll(0, true);
      IF NOT SuppressCommit THEN  //-------------------------------OnBeforeCode
           Commit();
    end;
    
    //-------------------------------OnBeforeCode:BEGIN
    procedure SetSuppressCommit(NewSuppressCommit: Boolean)
    begin
        SuppressCommit := NewSuppressCommit;
    end;
    //-------------------------------OnBeforeCode:END;

Thank you and kind regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
