### ISSUE TITLE
[Event Request] Codeunit 1021 "Job Jnl.-Post".Code

### ISSUE THREAD

**Issue by giann85** [microsoft/ALAppExtensions#13000]
Please,  can you add new event and procedure:

    var (global)
    //-------------------------------OnBeforeCode:BEGIN
        HideDialog: Boolean;
        SuppressCommit: Boolean;
    //-------------------------------OnBeforeCode:END

    local procedure "Code"()
    var
        JobJnlPostbatch**: Codeunit "Job Jnl.-Post Batch";  //-------------------------------OnBeforeCode
    begin
        with JobJnlLine do begin
            //-------------------------------OnBeforeCode:BEGIN
            OnBeforeCode(JobJnlLine, HideDialog, SuppressCommit);
            //-------------------------------OnBeforeCode:END

            JobJnlTemplate.Get("Journal Template Name");
            JobJnlTemplate.TestField("Force Posting Report", false);
            if JobJnlTemplate.Recurring and (GetFilter("Posting Date") <> '') then
                FieldError("Posting Date", Text000);

            if not HideDialog then          //-------------------------------OnBeforeCode
                if not Confirm(Text001) then
                    exit;

            OnCodeOnAftreConfirm(JobJnlLine);

            TempJnlBatchName := "Journal Batch Name";

            //-------------------------------OnBeforeCode:BEGIN

            // CODEUNIT.Run(CODEUNIT::"Job Jnl.-Post Batch", JobJnlLine);   OLD CODE
            //NEW CODE
            JobJnlPostbatch.SetSuppressCommit(SuppressCommit);
            JobJnlPostbatch.Run(JobJnlLine);
            //-------------------------------OnBeforeCode:END

            if not HideDialog then          //-------------------------------OnBeforeCode
                if "Line No." = 0 then
                    Message(Text002)
                else
                    if TempJnlBatchName = "Journal Batch Name" then
                        Message(Text003)
                    else
                        Message(
                          Text004 +
                          Text005,
                          "Journal Batch Name");

            if not Find('=><') or (TempJnlBatchName <> "Journal Batch Name") then begin
                Reset;
                FilterGroup(2);
                SetRange("Journal Template Name", "Journal Template Name");
                SetRange("Journal Batch Name", "Journal Batch Name");
                FilterGroup(0);
                "Line No." := 1;
            end;
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCodeOnAftreConfirm(var JobJnlLine: Record "Job Journal Line")
    begin
    end;

    //-------------------------------OnBeforeCode:BEGIN
    procedure SetHideDialog(NewHideDialog: Boolean)
    begin
        HideDialog := NewHideDialog;
    end;

    procedure SetSuppressCommit(NewSuppressCommit: Boolean)
    begin
        SuppressCommit := NewSuppressCommit;
    end;

    [IntegrationEvent(false, false)]
    procedure OnBeforeCode(VAR JobJnlLine: Record "Job Journal Line"; VAR HideDialog: Boolean; VAR SuppressCommit: 
    Boolean)
    begin
    end;
    //-------------------------------OnBeforeCode:END

Please edit  standard event's name: it's wrong  "OnCodeOn**After**...." instead actually "...**Aftre**....".

This request is linked to  other  opened issue  https://github.com/microsoft/ALAppExtensions/issues/12999

Thank you and kind regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by giann85** [comment]
Great! Thank you very much for your work.
