### ISSUE TITLE
Permission request: Add indirect modify permission to Codeunit 882

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/ALAppExtensions#13009]
Today a user needs to be able modify OCR Service Setup (Table 1270) to be able to work with OCR.  This is because Codeunit 884 "ReadSoft OCR Master Data Sync" is updating the OCR Service Setup.
Please add 

Permisson = tabledata "OCR Service Setup" = m;

to Codeunit 884

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
