### ISSUE TITLE
[Event Change Request] Codeunit 5802 Inventory Posting to G/L-OnBe3foreBufferInvtPosting

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/ALAppExtensions#13006]
Please add **CalledFromTestReport** as a new parameter to Event **OnBeforeBufferInvtPosting**

```
  PostBufDimNo := 0;
  IsHandled := FALSE;
  OnBeforeBufferInvtPosting(ValueEntry, Result, IsHandled, RunOnlyCheck, CalledFromTestReport);
  IF IsHandled THEN
    EXIT(Result);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
