### ISSUE TITLE
[Request-for-External] Table 2158 "O365 Document Sent History" - procedure SetHistoryForDocumentAsNotified

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#13001]
Hello, is it possible to make this procedure accessible for my "O365 Document Sent History" table extention?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
