### ISSUE TITLE
Make GetCardpageID in Purchase and Sales Header obsolete

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#13015]
These functions (on the right) should be marked as obsolete in favor of the "Page Management" codeunit.

![grafik](https://user-images.githubusercontent.com/7450586/123672493-e4950a00-d82e-11eb-9c86-531ffc3b0ad3.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
