### ISSUE TITLE
event request - Codeunit 365 Format Address - GetCompanyAddr() - OnGetCompanyAddrOnAfterAssignToCompInfo()

### ISSUE THREAD

**Issue by db-bc** [microsoft/ALAppExtensions#13012]
We have a customer whose NAV 2017 code has additional fields being copied from the RespCenter to the CompanyInfo, in order to display different data on invoices etc depending on their Resp Ctr, and so we need to request the following event. Thanks!

    procedure GetCompanyAddr(RespCenterCode: Code[10]; var ResponsibilityCenter: Record "Responsibility Center"; var CompanyInfo: Record "Company Information"; var CompanyAddr: array[8] of Text[100])
    begin
        if ResponsibilityCenter.Get(RespCenterCode) then begin
            RespCenter(CompanyAddr, ResponsibilityCenter);
            CompanyInfo."Phone No." := ResponsibilityCenter."Phone No.";
            CompanyInfo."Fax No." := ResponsibilityCenter."Fax No.";

            OnGetCompanyAddrOnAfterAssignToCompInfo(ResponsibilityCenter, CompanyInfo); // NEW
        end else
            Company(CompanyAddr, CompanyInfo);
    end;

where that event would look like

```al
[IntegrationEvent(false, false)]
local procedure OnGetCompanyAddrOnAfterAssignToCompInfo(ResponsibilityCenter: Record "Responsibility Center"; var CompanyInformation: Record "Company Information");
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
