### ISSUE TITLE
Request for an IsHandled pattern to FindCurrency function in Table 330 - "Currency Exchange Rate" or a new event publisher.

### ISSUE THREAD

**Issue by daryobahar** [microsoft/ALAppExtensions#13014]
We are preparing localization for Turkey.

As a common market practice, we want to test if the exchange rate for that specific date (Posting Date) is entered.

This functionality was there until BC14 by modifying the standard code.

We need either an "IsHandled" pattern for the function 

**[External] FindCurrency**(Date : Date;CurrencyCode : Code[10];CacheNo : Integer) 

or  an event publisher like 

OnAfterFindCurrencyWithDate(Date : Date; CurrencyCode : Code[10]) 

where the parameters "Date" and "Currency Code" are the input parameters of the function FindCurrency

Thank you for your support.

Daryo Bahar
Infotek A.S.
daryo.bahar@infotekas.com.tr

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
