### ISSUE TITLE
[Event Change Request] Table 38 Purchase Header - OnAfterDeleteAllTempPurchLines event parameter

### ISSUE THREAD

**Issue by ViktorasDanielius** [microsoft/ALAppExtensions#13010]
Please add PurchaseHeader parameter (as VAR) to Table 38 Purchase Header OnAfterDeleteAllTempPurchLines event which is called from RecreatePurchLines function. Currently it doesn't have any parameters and there is no use of it.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
