### ISSUE TITLE
[Event Request] OnBeforeIsActiveProductionBOM @ Codeunit 99000770 "Where-Used Management"

### ISSUE THREAD

**Issue by J-KVS** [microsoft/ALAppExtensions#13011]
I'd like to propose the Event `OnBeforeIsActiveProductionBOM` in Codeunit `"Where-Used Management"` with the Handled-Pattern. Please let me know if you need additional information from me.

``` al
local procedure IsActiveProductionBOM(ProductionBOMLine: Record "Production BOM Line"): Boolean
// START
var
    IsHandled: Boolean;
    Result: Boolean;
begin
    OnBeforeIsActiveProductionBOM(ProductionBOMLine, Result, IsHandled);
    if IsHandled then
        exit(Result);

// STOP
    if ProductionBOMLine."Version Code" = '' then
        exit(not IsProductionBOMClosed(ProductionBOMLine));

    exit(not IsProdBOMVersionClosed(ProductionBOMLine));
end;


// START
[IntegrationEvent(false, false)]
local procedure OnBeforeIsActiveProductionBOM(ProductionBOMLine: Record "Production BOM Line"; var Result: Boolean; var IsHandled: Boolean)
begin
end;
// STOP
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
