### ISSUE TITLE
[Request-for-External] Table 5900 Service Header - Function UpdateCurrencyFactor

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#13027]
Dear ALAppExtensions Team,
We would like to request the following change

    local procedure UpdateCurrencyFactor()
    local procedure ConfirmCurrencyFactorUpdate()
    
    //--> change request remove local
    procedure UpdateCurrencyFactor()
    procedure ConfirmCurrencyFactorUpdate()
    //<-- change request remove local

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
