### ISSUE TITLE
[Event Request] table 5965 "Service Contract Header" OnValidate Field "Last Invoice Date"

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#13021]
Last Invoice Date - OnValidate()
----------------------- ADD EVENT ----------------------
	OnBeforeLastInvoiceDateValidate(Rec, xRec, isHandled);
	if isHandled then
	exit;
----------------------------------------------------------

[IntegrationEvent(false, false)]
local procedure OnAfterUpdateInvoicePeriodNextInvoiceDate(var Rec: Record "Service Contract Header"; var xRec: Record "Service Contract Header"; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
