### ISSUE TITLE
[Event Request] Table 5900 Service Header - Function UpdateCurrencyFactor

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#13026]
Dear ALAppExtensions Team,
We would like to request the following change and event publisher

    local procedure UpdateCurrencyFactor()
    var
        UpdateCurrencyExchangeRates: Codeunit "Update Currency Exchange Rates";
        ConfirmManagement: Codeunit "Confirm Management";
    begin
        //--> event request
        OnBeforeUpdateCurrencyFactor(Rec, CurrExchRate);
        //<-- event request
        if "Currency Code" <> '' then begin
            CurrencyDate := "Posting Date";
            if UpdateCurrencyExchangeRates.ExchangeRatesForCurrencyExist(CurrencyDate, "Currency Code") then begin
                "Currency Factor" := CurrExchRate.ExchangeRate(CurrencyDate, "Currency Code");
                if "Currency Code" <> xRec."Currency Code" then
                    RecreateServLines(FieldCaption("Currency Code"));
            end else begin
                if ConfirmManagement.GetResponseOrDefault(
                     StrSubstNo(MissingExchangeRatesQst, "Currency Code", CurrencyDate), true)
                then begin
                    UpdateCurrencyExchangeRates.OpenExchangeRatesPage("Currency Code");
                    UpdateCurrencyFactor;
                end else
                    RevertCurrencyCodeAndPostingDate;
            end;
        end else begin
            "Currency Factor" := 0;
            if "Currency Code" <> xRec."Currency Code" then
                RecreateServLines(FieldCaption("Currency Code"));
        end;
    end;

    //--> event request
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateCurrencyFactor(var ServiceHeader: Record "Service Header"; var CurrExchRate: Record "Currency Exchange Rate")
    begin
    end;
    //<-- event request

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
