### ISSUE TITLE
[Event Request] Table 330 Currency Exchange Rate - Function FindCurrency

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#13023]
Dear ALAppExtensions Team,

We would like to request the following change and event publisher

    procedure FindCurrency(Date: Date; CurrencyCode: Code[10]; CacheNo: Integer)
    //--> change request
    var
      CurrExchRate2CacheNoExist: Boolean;
    //<-- change request
    begin
        //--> change and event request
        //if (CurrencyCode2[CacheNo] = CurrencyCode) and (Date2[CacheNo] = Date) then
        CurrExchRate2CacheNoExist := (CurrencyCode2[CacheNo] = CurrencyCode) and (Date2[CacheNo] = Date);
        OnBeforeFindCurrency(Rec, CurrExchRate2CacheNoExist, CacheNo);
        if CurrExchRate2CacheNoExist then
        //<-- change and event request
            Rec := CurrencyExchRate2[CacheNo]
        else begin
            if Date = 0D then
                Date := WorkDate;
            CurrencyExchRate2[CacheNo].SetRange("Currency Code", CurrencyCode);
            CurrencyExchRate2[CacheNo].SetRange("Starting Date", 0D, Date);
            OnFindCurrencyOnAfterCurrencyExchRate2SetFilters(CurrencyExchRate2[CacheNo], CurrencyCode, Date);
            CurrencyExchRate2[CacheNo].FindLast;
            Rec := CurrencyExchRate2[CacheNo];
            CurrencyCode2[CacheNo] := CurrencyCode;
            Date2[CacheNo] := Date;
        end;
        //--> change request
        OnAfterFindCurrency(Rec, CurrencyExchRate2, CacheNo);
       //<-- change request
    end;

    //--> event request
    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindCurrency(var CurrencyExchangeRate: Record "Currency Exchange Rate"; var CurrExchRate2CacheNoExist: Boolean; CacheNo: Integer)
    begin
    end;
    //<-- event request

    //--> change request
    [IntegrationEvent(false, false)]
    local procedure OnAfterFindCurrency(var CurrencyExchangeRate: Record "Currency Exchange Rate"; var CurrencyExchangeRateArray: array[2] of Record "Currency Exchange Rate"; CacheNo: Integer)
    begin
    end;
    //<-- change request

**Comment by Hakan-6Gen** [comment]
CacheNo parameter change added OnBeforeFindCurrency event.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
