### ISSUE TITLE
[Event Request] table 5965 "Service Contract Header" OnValidate field "Next Invoice Date"

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#13022]
field(34; "Next Invoice Date"; Date)
            trigger OnValidate()
            var
                ServLedgEntry: Record "Service Ledger Entry";
                IsHandled: Boolean;
            begin
                if "Next Invoice Date" = 0D then begin
                    "Next Invoice Period Start" := 0D;
                    "Next Invoice Period End" := 0D;
                    exit;
                end;
                if "Last Invoice Date" <> 0D then
                    if "Last Invoice Date" > "Next Invoice Date" then begin
                        ServLedgEntry.SetRange(Type, ServLedgEntry.Type::"Service Contract");
                        ServLedgEntry.SetRange("No.", "Contract No.");
                        if not ServLedgEntry.IsEmpty() then
                            Error(Text023, FieldCaption("Next Invoice Date"), FieldCaption("Last Invoice Date"));
                        "Last Invoice Date" := 0D;
                    end;

                if "Next Invoice Date" < "Starting Date" then
                    Error(Text024, FieldCaption("Next Invoice Date"), FieldCaption("Starting Date"));

                if Prepaid then begin
                    if "Next Invoice Date" <> CalcDate('<-CM>', "Next Invoice Date") then begin
                        IsHandled := false;
                        OnValidateNextInvoiceDateOnBeforeCheck(Rec, IsHandled);
                        if not IsHandled then
                            Error(Text026, FieldCaption("Next Invoice Date"));
                    end;
                    TempDate := CalculateEndPeriodDate(true, "Next Invoice Date");
                    if "Expiration Date" <> 0D then
                        if "Next Invoice Date" > "Expiration Date" then
                            "Next Invoice Date" := 0D
                        else
                            if TempDate > "Expiration Date" then
                                TempDate := "Expiration Date";
                    if ("Next Invoice Date" <> 0D) and (TempDate <> 0D) then begin
                        "Next Invoice Period Start" := "Next Invoice Date";
                        "Next Invoice Period End" := TempDate;
                    end else begin
                        "Next Invoice Period Start" := 0D;
                        "Next Invoice Period End" := 0D;
                    end;
                end else begin
                    if "Next Invoice Date" <> CalcDate('<CM>', "Next Invoice Date") then begin
                        IsHandled := false;
                        OnValidateNextInvoiceDateOnBeforeCheck(Rec, IsHandled);
                        if not IsHandled then
                            Error(Text028, FieldCaption("Next Invoice Date"));
                    end;
                    TempDate := CalculateEndPeriodDate(false, "Next Invoice Date");
                    if TempDate < "Starting Date" then
                        TempDate := "Starting Date";

                    if "Expiration Date" <> 0D then
                        if "Expiration Date" < TempDate then
                            "Next Invoice Date" := 0D
                        else
                            if "Expiration Date" < "Next Invoice Date" then
                                "Next Invoice Date" := "Expiration Date";

                    if ("Next Invoice Date" <> 0D) and (TempDate <> 0D) then begin
                        "Next Invoice Period Start" := TempDate;
                        "Next Invoice Period End" := "Next Invoice Date";
                    end else begin
                        "Next Invoice Period Start" := 0D;
                        "Next Invoice Period End" := 0D;
                    end;
                end;

----------------------- ADD EVENT ----------------------
OnBeforeValidateNextInvoicePeriod_OnValidateNextInvoiceDate(Rec, xRec);
----------------------------------------------------------
                ValidateNextInvoicePeriod;
            end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateNextInvoicePeriod_OnValidateNextInvoiceDate(var ServiceContractHeader: Record "Service Contract Header"; var xServiceContractHeader: Record "Service Contract Header")
    begin
    end;

**Comment by Stepanenko-Vadim** [comment]
There is already a **OnBeforeValidateNextInvoicePeriod**, we will add xRec param to that so you an use it instead

**Comment by OlgicaA** [comment]
Sorry I forgot to write with IsHandled parameter, I want to rewrite onvalidate trigger completely

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
