### ISSUE TITLE
[Event Request] codeunit 80 "Sales-Post" - 

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#13039]
Can you make it the same in codeunit 80 as in codeunit 90? I need the possibility for an exit when I make my own code. So I need the "IsHandled" parameter.

Example from cu90:
![image](https://user-images.githubusercontent.com/45654195/123940736-c1d33480-d999-11eb-8296-1ec1f14610f2.png)

**Comment by Stepanenko-Vadim** [comment]
It already exists in codeunit 80 and the code you've provided is from codeunit 80.
I assume you want similar event in codeunit 90 in **FillInvoicePostBuffer** procedure and implement that

**Comment by ddagkappeler** [comment]
I'm sorry, I make a mistake  
This is cu 90 and there I don't have the posibility to "exit if handled" and this is what i need.
![image](https://user-images.githubusercontent.com/45654195/124449505-cfb2fc00-dd83-11eb-9b7f-3c9ef884ada1.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
