### ISSUE TITLE
BCPT - Incomplete API 

### ISSUE THREAD

**Issue by waldo1001** [microsoft/ALAppExtensions#13037]
I found out that BCPT does have an API - but looking into it, it seems to be incomplete.

I might be wrong, but what I seem to be missing is:
- a way to start a suite 
- getting the Log

Is this somewhere on the roadmap?

**Comment by AlexanderYakunin** [comment]
@nikolakukrika - can you help to answer?

**Comment by StanPesotskiy** [comment]
Your request is not related to the AL **application** extensibility. 
Please post it at https://www.yammer.com/dynamicsnavdev/ where the wider community may give you a valid answer.
