### ISSUE TITLE
[Event Request] page 5872 BOM Cost Shares - Function RefreshPage

### ISSUE THREAD

**Issue by NicolaAlberini** [microsoft/ALAppExtensions#13038]
We would like to propose the event:
`OnBeforeGenerateBOMTree(Rec, Item, AsmHeader, ProdOrderLine, ShowBy, ItemFilter, IsHandled);`
In page 5872 - "BOM Cost Shares" in the function "RefreshPage".

The event is already present in page 5870 "BOM Structure" function "GenerateBOMTree".
Without that event we cannot use the same logic for building both trees.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
