### ISSUE TITLE
[Event Request] New IntegrationEvent in Codeunit 80 "Sales-Post", function SendPostedDocumentRecord

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#13041]
Hello,

please insert new IntegrationEvent in Codeunit 80 "Sales-Post", function SendPostedDocumentRecord.

                        OnSendSalesDocument(Invoice and Ship, SuppressCommit);
                        if Invoice then begin
                            SalesInvHeader.Get("Last Posting No.");
                            SalesInvHeader.SetRecFilter;
                            SalesInvHeader.SendProfile(DocumentSendingProfile);
                        end;
                        // Start kvs.dde
                        //if Ship and Invoice and not OfficeManagement.IsAvailable then
                        if Ship and Invoice and not OfficeManagement.IsAvailable then begin
                            OnBeforeConfirmDownloadShipmentAlso(IsHandled);
                            if not IsHandled then
                        // Stop kvs.dde
                                if not ConfirmManagement.GetResponseOrDefault(DownloadShipmentAlsoQst, true) then
                                    exit;
                        // Start kvs.dde
                        end;
                        // Stop kvs.dde
                        if Ship then begin
                            SalesShipmentHeader.Get("Last Shipping No.");
                            SalesShipmentHeader.SetRecFilter;
                            SalesShipmentHeader.SendProfile(DocumentSendingProfile);
                        end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
