### ISSUE TITLE
Page Navigate. Function SetPostingDate set to global

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#13046]
On page Navigate I suggest make SetPostingDate to global, or add an event where we can change PostingDateFilter based on the NewSourceRecVar variable.

It's needed for a document that was posted 2 times with different posting dates.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
