### ISSUE TITLE
Temporary records are not taken into account, so when temporary records are deleted, physical records “item cross reference” and “item reference” are also deleted.

### ISSUE THREAD

**Issue by RonaldGAC** [microsoft/ALAppExtensions#13044]
We encountered an error in standard BC during development.

It concerns 3 event subscribers on delete records from:
- Article
- Supplier
- Customer
Temporary records are not taken into account, so when temporary records are deleted, physical records “item cross reference” and “item reference” are also deleted.

Possible Solution: The subscribers should start with: “IF Rec.IsTemporary then exit”;

**Codeunit 5702: "Dist. Integration"**
[EventSubscriber(ObjectType::Table, Database::Item, 'OnAfterDeleteRelatedData', '', false, false)]
local procedure ItemOnAfterDeleteRelatedData(Item: Record Item)
begin
#if not CLEAN16
ItemCrossReference.SetRange("Item No.", Item."No.");
ItemCrossReference.DeleteAll();
#endif
ItemReference.SetRange("Item No.", Item."No.");
ItemReference.DeleteAll();
end;

[EventSubscriber(ObjectType::Table, Database::Customer, 'OnAfterDeleteEvent', '', false, false)]
local procedure CustomerOnAfterDelete(var Rec: Record Customer)
begin
#if not CLEAN16
ItemCrossReference.SetCurrentKey("Cross-Reference Type", "Cross-Reference Type No.");
ItemCrossReference.SetRange("Cross-Reference Type", ItemCrossReference."Cross-Reference Type"::Customer);
ItemCrossReference.SetRange("Cross-Reference Type No.", Rec."No.");
ItemCrossReference.DeleteAll();
#endif
ItemReference.SetCurrentKey("Reference Type", "Reference Type No.");
ItemReference.SetRange("Reference Type", ItemReference."Reference Type"::Customer);
ItemReference.SetRange("Reference Type No.", Rec."No.");
ItemReference.DeleteAll();
end;

[EventSubscriber(ObjectType::Table, Database::Vendor, 'OnAfterDeleteEvent', '', false, false)]
local procedure VendorOnAfterDelete(var Rec: Record Vendor)
begin
#if not CLEAN16
ItemCrossReference.SetCurrentKey("Cross-Reference Type", "Cross-Reference Type No.");
ItemCrossReference.SetRange("Cross-Reference Type", ItemCrossReference."Cross-Reference Type"::Vendor);
ItemCrossReference.SetRange("Cross-Reference Type No.", Rec."No.");
ItemCrossReference.DeleteAll();
#endif
ItemReference.SetCurrentKey("Reference Type", "Reference Type No.");
ItemReference.SetRange("Reference Type", ItemReference."Reference Type"::Vendor);
ItemReference.SetRange("Reference Type No.", Rec."No.");
ItemReference.DeleteAll();
end;
codeunit
[Eventsubscribers with error.pdf](https://github.com/microsoft/ALAppExtensions/files/6741859/Eventsubscribers.with.error.pdf)

**Comment by AlexanderYakunin** [comment]
Thank you for information, why do you think this is an error? We used to have this code in C/Al for long time, and this is same code moved to subscribers? If we remove entity like Customer, vendor or Item, we should also remove related data, including References.

**Comment by RonaldGAC** [comment]
> Thank you for information, why do you think this is an error? We used to have this code in C/Al for long time, and this is same code moved to subscribers? If we remove entity like Customer, vendor or Item, we should also remove related data, including References.

Hi Alexander,
Table ItemReference is quite new I think.
But anyway, my problem is that when a temporary record in item, customer or vendor, is deleted, also itemreference (non temporary) is deleted.
Is there a way to prevent that in the code?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
