### ISSUE TITLE
[Protection Level] report 20 "Calc. and Post VAT Settlement"

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#13050]
Can you change the variabel GLAccSettle to protected var in report 20 "Calc. and Post VAT Settlement"?

And/or move this code to a protected procedure with a parameter to be able to set the account no...
```
                    field(SettlementAcc; GLAccSettle."No.")
                    {
                        ApplicationArea = Basic, Suite;
                        Caption = 'Settlement Account';
                        TableRelation = "G/L Account";
                        ToolTip = 'Specifies the number of the VAT settlement account. Select the field to see the chart of account. This field must be filled in.';

                        trigger OnValidate()
                        begin
                            // This code ---->
                            if GLAccSettle."No." <> '' then begin
                                GLAccSettle.Find();
                                GLAccSettle.CheckGLAcc();
                            end;
                            // <-----
                        end;
                    }
```

I have made a report extension and I have added a field to the request page.
When the user changes the value in the new field I want to set settlement account based on a setup.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
