### ISSUE TITLE
[Event Request] Codeunit 5945 - OnBeforeOnRun

### ISSUE THREAD

**Issue by RWeston6** [microsoft/ALAppExtensions#13058]
New event needed in Codeunit 5945 (CreateCreditfromContractLines) - OnBeforeOnRun

```
codeunit 5945 CreateCreditfromContractLines
{
   //<< NEW
 [IntegrationEvent(false, false)]
    local procedure OnBeforeOnRun(var ServiceContractLine: Record "Service Contract Line"; LinesToDelete: integer; var IsHandled: Boolean)
    begin
    end;
//>> NEW

    trigger OnRun()
    var
        IsHandled      //NEW
    begin
//<< NEW
        OnBeforeOnRun(Rec, LinesToDelete, IsHandled)
        if IsHandled then
            exit;
//>> NEW
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
