### ISSUE TITLE
[Event Request]  InitLastDocDate COD12

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/ALAppExtensions#1305]
I would like to request an event on function InitLastDocDate in COD12. We have a transaction no. that makes sense to be inited inside the standard function.

**Comment by JesperSchulz** [comment]
If you could provide the event signature and position, it would be helpful. Please refer to any other event request for examples.

**Comment by martinhocosta88** [comment]
Sorry Jesper,

Bellow you can find the standard Function with our new line:

`LOCAL InitLastDocDate(GenJnlLine : Record "Gen. Journal Line")
WITH GenJnlLine DO BEGIN
  LastDocType := "Document Type";
  LastDocNo := "Document No.";
  LastDate := "Posting Date";
  **LastTempTransNo := "Transaction No."; //New Line**
END;`

In order to suite us, we needed a onAfterInitLastDocDate or a OnBeforeLastInitLastDocDate event with (GenJnlLine, var LastTempTransNo) as parameters.

**Comment by martinhocosta88** [comment]
![image](https://user-images.githubusercontent.com/13696679/53242305-4dd34400-369c-11e9-83b3-c154f0c3aa7d.png)

**Comment by AlexanderYakunin** [comment]
We already have global variable NextTransactionNo. I'd suggest you think how to rework you solution using existing COD12 and events instead of converting you legacy code 1:1 using events. You can finally get better solution.
