### ISSUE TITLE
[Event Change Request] - ItemJnlPostLine.Codeunit.al - OnItemValuePostingOnBeforeInsertOHValueEntry

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#13055]
We like to request the following event change:
Object: ItemJnlPostLine.Codeunit.al
ToDo: include Sender
Event Code:
```al
[IntegrationEvent(true, false)]
local procedure OnItemValuePostingOnBeforeInsertOHValueEntry(var ItemJnlLine: Record "Item Journal Line"; var GlobalValueEntry: Record "Value Entry"; var GlobalItemLedgEntry: Record "Item Ledger Entry"; var ValueEntryNo: Integer; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
