### ISSUE TITLE
[Event Request] Table 1003 Job Planning Line - UpdateCurrencyFactor

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#13060]
Dear ALAppExtensions Team,
We would like to request the following event publisher

    procedure UpdateCurrencyFactor()
    begin
        if "Currency Code" <> '' then begin
            if "Currency Date" = 0D then
                CurrencyDate := WorkDate
            else
                CurrencyDate := "Currency Date";
            //--> event request
            OnBeforeGetJobPlanningCurrencyFactor(Rec, CurrExchRate);
            //<-- event request
            "Currency Factor" := CurrExchRate.ExchangeRate(CurrencyDate, "Currency Code");
        end else
            "Currency Factor" := 0;
    end;

    //--> event request
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetJobPlanningCurrencyFactor(JobPlanningLine: Record "Job Planning Line"; var CurrExchRate: Record "Currency Exchange Rate")
    begin
    end;
    //<-- event request

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
