### ISSUE TITLE
Report 7000082 Settle Docs. in Posted PO - SetHidePrintDialog

### ISSUE THREAD

**Issue by jmezquita2** [microsoft/ALAppExtensions#13069]
Hi,

Could we get the "OnPrem" scope removed from this function?

```
[Scope('OnPrem')]
procedure SetHidePrintDialog(NewHidePrintDialog: Boolean)
begin
    HidePrintDialog := NewHidePrintDialog;
end;
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
