### ISSUE TITLE
[Event Request] Table 210 Job Journal Line - Function UpdateCurrencyFactor

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#13062]
Dear ALAppExtensions Team,
We would like to request the following event publisher

    local procedure UpdateCurrencyFactor()
    begin
        if "Currency Code" <> '' then begin
            if "Posting Date" = 0D then
                CurrencyDate := WorkDate
            else
                CurrencyDate := "Posting Date";
            //--> event request
            OnBeforeGetJobJournalLineCurrencyFactor(Rec, CurrExchRate);
            //<-- event request
            "Currency Factor" := CurrExchRate.ExchangeRate(CurrencyDate, "Currency Code");
        end else
            "Currency Factor" := 0;
    end;

    //--> event request
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetJobJournalLineCurrencyFactor(JobJournalLine: Record "Job Journal Line"; var CurrExchRate: Record "Currency Exchange Rate")
    begin
    end;
     //<-- event request

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
