### ISSUE TITLE
[Event Request] Table 179 Reversal Entry - OnBeforeCheckMaintenance

### ISSUE THREAD

**Issue by jmezquita2** [microsoft/ALAppExtensions#13067]
Please add a new publisher event to the function CheckMaintenance follows:

```
local procedure CheckMaintenance(MaintenanceLedgEntry: Record "Maintenance Ledger Entry")
//>> Start New Publisher Call
OnBeforeCheckMaintenance(MaintenanceLedgEntry);
//<< End New Publisher Call
FA.Get(MaintenanceLedgEntry."FA No.");
.
.

```

New Publisher Event:

```
[IntegrationEvent(true, false)]
local procedure OnBeforeCheckMaintenance(var MaintenanceLedgEntry: Record "Maintenance Ledger Entry")
begin
end;
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
