### ISSUE TITLE
[Enum Request] MatrixPeriodType

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#13065]
Please provide an new "MatrixPeriodType" Enum with these valeus:
Day,Week,Month,Quarter,Year,"Accounting Period"

In the Base Application this Options are mostly referenced as PeriodType-Variable.

Since many Partners using the same option in there matrix pages it would be useful when we could all use the same enum.

I think extensibility is not Required at this Time.

**Comment by AlexanderYakunin** [comment]
This is large rework for many pages and global procedures (100+ objects). Not sure we should spend resources for this work now. Probably we can simply add this enum without reworking of existing objects as pattern for new partners? What do you think?

**Comment by ChrisBlankDe** [comment]
That would be fine for me.

A complete rebuild of the solution wouldn't be that tragic i think . you only have to change from option to enum everywhere. afaik you don't even need a mapping to other enums. But you are right: the number of touched objects would be high.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
