### ISSUE TITLE
Lot No. Information Table 6505 - add default fieldgroup DropDown 

### ISSUE THREAD

**Issue by frivadulla** [microsoft/ALAppExtensions#13071]
Good morning everyone,

can you please add the default dropdown fieldgroup to the lot no. information table, in order to add some custom fields?

Kind regards.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
