### ISSUE TITLE
[Request-for-External] codeunit 10610 "E-Invoice Document Encode" - Open for cloud

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#13084]
Can you please remove [Scope('OnPrem')] from all procedures in codeunit 10610 "E-Invoice Document Encode".

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
