### ISSUE TITLE
[Event Request] Table 5902 "Service Line" - OnBeforeMaxQtyToConsumeBase

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#13083]
Can you please add OnBeforeMaxQtyToConsumeBase to Table 5902 "Service Line" with Decimal ReturnValue in procedure MaxQtyToConsumeBase?

```
procedure MaxQtyToConsumeBase(): Decimal
// >>>>>>>>>>
var
IsHandled: Boolean;
ReturnValue: Decimal;
begin
    IsHandled := false;
    OnBeforeMaxQtyToConsumeBase(Rec, ReturnValue, IsHandled);        
    if IsHandled then
        exit(ReturnValue);
    // <<<<<<<<<<
    exit("Quantity (Base)" - "Qty. Shipped (Base)");
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeMaxQtyToConsumeBase(var ServiceLine: Record "Service Line"; var ReturnValue: Decimal; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
