### ISSUE TITLE
[Access Request] Page 255 "Cash Receipt Journal" make ApplyEntriesActionEnabled protected

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/ALAppExtensions#13088]
Hi, 
Could you please make variable ApplyEntriesActionEnabled protected, so we could utilize it within our extension.

Best Regads, 
Gintautas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
