### ISSUE TITLE
Service Line table local procedure ClearFields to protected procedure 

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#13085]
There is also a local procedure ClearFields() in Service Line table. Is it possible to make it a Protected Procedure so we can access it from an event?

from local procedure ClearFields() to Protected procedure ClearFields()

Thank you very much.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
