### ISSUE TITLE
[Event Request] Codeunit 5940 ServContractManagement - Function CreateServHeader

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#13091]
Dear ALAppExtensions Team,
We would like to request the following event publisher

    procedure CreateServHeader(ServContract2: Record "Service Contract Header"; PostDate: Date; ContractExists: Boolean) ServInvNo: Code[20]
    var
        ServHeader2: Record "Service Header";
        Cust: Record Customer;
        ServDocReg: Record "Service Document Register";
        CurrExchRate: Record "Currency Exchange Rate";
        GLSetup: Record "General Ledger Setup";
        Cust2: Record Customer;
        UserMgt: Codeunit "User Setup Management";
        RecordLinkManagement: Codeunit "Record Link Management";
    begin
        .........................
        ServHeader2."Currency Code" := ServContract2."Currency Code";
        //--> event request
        OnBeforeGetServHeader2CurrencyFactor(ServHeader2, CurrExchRate);
        //<-- event request
        ServHeader2."Currency Factor" :=
          CurrExchRate.ExchangeRate(
            ServHeader2."Posting Date", ServHeader2."Currency Code");
        ..........................
    end;

    //--> event request
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetServHeader2CurrencyFactor(ServHeader2: Record "Service Header"; var CurrExchRate: Record "Currency Exchange Rate")
    begin
    end;
    //<-- event request

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
