### ISSUE TITLE
[Event Request] Transfer header Table No. series is not extensible

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/ALAppExtensions#13096]
we don't have this trigger in transfer header table(OnBeforeTestNoSeries), similar to sales/purchase header.

Request to provide the same with handled pattern.

we need signature same as it is in sales header table.(please look into sales header table for this trigger)

OnBeforeTestNoSeries(Rec, IsHandled);
if not IsHandled then

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
