### ISSUE TITLE
[Event Request] Codeunit 5987 Serv-Posting Journals Mgt. - Function PostJobJnlLine

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#13090]
Dear ALAppExtensions Team,
We would like to request the following event publisher

    procedure PostJobJnlLine(var ServHeader: Record "Service Header"; ServLine: Record "Service Line"; QtyToBeConsumed: Decimal): Boolean
    var
        JobJnlLine: Record "Job Journal Line";
        SourceCodeSetup: Record "Source Code Setup";
        ServiceCost: Record "Service Cost";
        Job: Record Job;
        JobTask: Record "Job Task";
        Item: Record Item;
        Customer: Record Customer;
        JobJnlPostLine: Codeunit "Job Jnl.-Post Line";
        CurrencyFactor: Decimal;
        UnitPriceLCY: Decimal;
        IsHandled: Boolean;
        Result: Boolean;
    begin
        IsHandled := false;
        OnBeforePostJobJnlLine(ServHeader, ServLine, QtyToBeConsumed, Result, IsHandled);
        if IsHandled then
            exit(Result);

        with ServLine do begin
            if ("Job No." = '') or (QtyToBeConsumed = 0) then
                exit(false);

            TestField("Job Task No.");
            Job.LockTable();
            JobTask.LockTable();
            Job.Get("Job No.");
            JobTask.Get("Job No.", "Job Task No.");

            JobJnlLine.Init();
            JobJnlLine.DontCheckStdCost;
            JobJnlLine.Validate("Job No.", "Job No.");
            JobJnlLine.Validate("Job Task No.", "Job Task No.");
            JobJnlLine.Validate("Line Type", "Job Line Type");
            JobJnlLine.Validate("Posting Date", "Posting Date");
            JobJnlLine."Job Posting Only" := true;
            JobJnlLine."No." := "No.";

            case Type of
                Type::"G/L Account":
                    JobJnlLine.Type := JobJnlLine.Type::"G/L Account";
                Type::Item:
                    JobJnlLine.Type := JobJnlLine.Type::Item;
                Type::Resource:
                    JobJnlLine.Type := JobJnlLine.Type::Resource;
                Type::Cost:
                    begin
                        ServiceCost.SetRange(Code, "No.");
                        ServiceCost.FindFirst;
                        JobJnlLine.Type := JobJnlLine.Type::"G/L Account";
                        JobJnlLine."No." := ServiceCost."Account No.";
                    end;
            end; // Case Type

            OnPostJobJnlLineOnBeforeValidateNo(JobJnlLine, ServLine);

            JobJnlLine.Validate("No.");
            JobJnlLine.Description := Description;
            JobJnlLine."Description 2" := "Description 2";
            JobJnlLine."Variant Code" := "Variant Code";
            JobJnlLine."Unit of Measure Code" := "Unit of Measure Code";
            JobJnlLine."Qty. per Unit of Measure" := "Qty. per Unit of Measure";
            JobJnlLine.Validate(Quantity, -QtyToBeConsumed);
            JobJnlLine."Document No." := ServHeader."Shipping No.";
            JobJnlLine."Service Order No." := "Document No.";
            JobJnlLine."External Document No." := ServHeader."Shipping No.";
            JobJnlLine."Posted Service Shipment No." := ServHeader."Shipping No.";
            if Type = Type::Item then begin
                Item.Get("No.");
                if Item."Costing Method" = Item."Costing Method"::Standard then
                    JobJnlLine.Validate("Unit Cost (LCY)", Item."Standard Cost")
                else
                    JobJnlLine.Validate("Unit Cost (LCY)", "Unit Cost (LCY)")
            end else
                JobJnlLine.Validate("Unit Cost (LCY)", "Unit Cost (LCY)");

            Currency.Initialize("Currency Code");
            Customer.Get("Customer No.");
            if Customer."Prices Including VAT" then
                Validate("Unit Price", Round("Unit Price" / (1 + ("VAT %" / 100)), Currency."Unit-Amount Rounding Precision"));

            if "Currency Code" = Job."Currency Code" then
                JobJnlLine.Validate("Unit Price", "Unit Price");
            if "Currency Code" <> '' then begin
                //--> event request
                OnBeforeGetServLineCurrencyFactor(ServLine, CurrExchRate);
                //<-- event request
                CurrencyFactor := CurrExchRate.ExchangeRate("Posting Date", "Currency Code");
                UnitPriceLCY :=
                  Round(CurrExchRate.ExchangeAmtFCYToLCY("Posting Date", "Currency Code", "Unit Price", CurrencyFactor),
                    Currency."Amount Rounding Precision");
                JobJnlLine.Validate("Unit Price (LCY)", UnitPriceLCY);
            end else
                JobJnlLine.Validate("Unit Price (LCY)", "Unit Price");

            JobJnlLine.Validate("Line Discount %", "Line Discount %");
            JobJnlLine."Job Planning Line No." := "Job Planning Line No.";
            JobJnlLine."Remaining Qty." := "Job Remaining Qty.";
            JobJnlLine."Remaining Qty. (Base)" := "Job Remaining Qty. (Base)";
            JobJnlLine."Location Code" := "Location Code";
            JobJnlLine."Entry Type" := JobJnlLine."Entry Type"::Usage;
            JobJnlLine."Posting Group" := "Posting Group";
            JobJnlLine."Gen. Bus. Posting Group" := "Gen. Bus. Posting Group";
            JobJnlLine."Gen. Prod. Posting Group" := "Gen. Prod. Posting Group";
            JobJnlLine."Customer Price Group" := "Customer Price Group";
            SourceCodeSetup.Get();
            JobJnlLine."Source Code" := SourceCodeSetup."Service Management";
            JobJnlLine."Work Type Code" := "Work Type Code";
            JobJnlLine."Shortcut Dimension 1 Code" := "Shortcut Dimension 1 Code";
            JobJnlLine."Shortcut Dimension 2 Code" := "Shortcut Dimension 2 Code";
            JobJnlLine."Dimension Set ID" := "Dimension Set ID";
            OnAfterTransferValuesToJobJnlLine(JobJnlLine, ServLine);
        end;

        JobJnlPostLine.RunWithCheck(JobJnlLine);
        exit(true);
    end;

    //--> event request
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetServLineCurrencyFactor(ServLine: Record "Service Line"; var CurrExchRate: Record "Currency Exchange Rate");
    begin
    end;
    //<-- event request

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
