### ISSUE TITLE
[Access Request] page 6510 "Item Tracking Lines" make ItemTrackingDataCollection protected

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/ALAppExtensions#13095]
in page 6510 "Item Tracking Lines":
Would it be possible to set the variable ItemTrackingDataCollection: Codeunit "Item Tracking Data Collection"; to protected?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
