### ISSUE TITLE
[EventRequest]Codeunit 1303 Correct Posted Sales Invoice

### ISSUE THREAD

**Issue by wokw** [microsoft/ALAppExtensions#13097]
Due to Polish localization app building, we need a publisher in Codeunit 1303. We want to allow our customers to post sales correction before the whole invoice has been shipped.
Function: TestSalesLines

...
if SalesInvoiceLine.Type = SalesInvoiceLine.Type::Item then begin
    if (SalesInvoiceLine.Quantity > 0) and (SalesInvoiceLine."Job No." = '') and
       WasNotCancelled(SalesInvoiceHeader."No.")
    then begin
        SalesInvoiceLine.CalcShippedSaleNotReturned(ShippedQtyNoReturned, RevUnitCostLCY, false);
// START
        OnAfterCalcShippedSaleNotReturned(SalesInvoiceLine, ShippedQtyNoReturned);
// STOP
        if SalesInvoiceLine.Quantity <> ShippedQtyNoReturned then
            ErrorHelperLine(ErrorType::ItemIsReturned, SalesInvoiceLine);
    end;
Publisher signature: LOCAL [IntegrationEvent] OnAfterCalcShippedSaleNotReturned(SalesInvoiceLine: Record "Sales Invoice Line"; var ShippedQtyNoReturned: Decimal)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
