### ISSUE TITLE
[Access Request] GetCurrency - report 12 "VAT Statement"

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#13099]
Can you change procedure GetCurrency to protected in report 12 "VAT Statement"?
I need this in report extension to use it for a new column in property AutoFormatExpression.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
