### ISSUE TITLE
[Event Request] Extend IntegrationEvent in Table 38 "Purchase Header", function SendProfile

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#13102]
Hello,

please extends IntegrationEvent in Table 38 "Purchase Header", function SendProfile.
Both Parameters should have the VAR Property.

    procedure SendProfile(var DocumentSendingProfile: Record "Document Sending Profile")
    var
        DummyReportSelections: Record "Report Selections";
        ReportDistributionMgt: Codeunit "Report Distribution Management";
    begin
        CheckMixedDropShipment;

        // Start kvs.dde
        IsHandled := false;
        OnBeforeSendProfile(Rec, IsHandled);
        if IsHandled then
            exit;
        // Stop kvs.dde

        DocumentSendingProfile.SendVendor(
          DummyReportSelections.Usage::"P.Order".AsInteger(), Rec, "No.", "Buy-from Vendor No.",
          ReportDistributionMgt.GetFullDocumentTypeText(Rec), FieldNo("Buy-from Vendor No."), FieldNo("No."));
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
