### ISSUE TITLE
[Event Request] Extend IntegrationEvent in Table 38 "Purchase Header", function PrintRecords

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#13101]
Hello,

please extends IntegrationEvent in Table 38 "Purchase Header", function PrintRecords.
Both Parameters should have the VAR Property.

    procedure PrintRecords(ShowRequestForm: Boolean)
    var
        DocumentSendingProfile: Record "Document Sending Profile";
        DummyReportSelections: Record "Report Selections";
    begin
        CheckMixedDropShipment;
        OnPrintRecordsOnAfterCheckMixedDropShipment(Rec);

        // Start kvs.dde
        IsHandled := false;
        OnBeforeSendRecords(Rec, IsHandled);
        if IsHandled then
            exit;
        // Stop kvs.dde

        DocumentSendingProfile.TrySendToPrinterVendor(
          DummyReportSelections.Usage::"P.Order".AsInteger(), Rec, FieldNo("Buy-from Vendor No."), ShowRequestForm);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
