### ISSUE TITLE
Missing Controls and Event Publisher from W1 in IT

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#13103]
In the Italien localization we are missing the `"External Document No."` Control on the "Sales Invoice" and "Sales Order" Pages.
Also we are missing the `OnCalculateCFAmountAndCFDateOnAfterAssignApplyCFPaymentTerm `Event from `table 846 "Cash Flow Worksheet Line"`

All three exist in W1 but where removed in localization which blocks our app from installation.
I think the external signature of an localization should be additive only.
please add the controls and set them to visible=false if not needed.
also please add the event and do not trigger it when not required.

Tested with these Artifacts:
https://bcartifacts.azureedge.net/sandbox/18.3.27240.27581/w1
https://bcartifacts.azureedge.net/sandbox/18.3.27240.27581/it

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
