### ISSUE TITLE
[Event Request] Codeunit 1850 "Sales Forecast Handler": OnAfterSetItemLedgerEntryFilters

### ISSUE THREAD

**Issue by deadmouse** [microsoft/ALAppExtensions#13108]
[Event Request] Codeunit 1850 "Sales Forecast Handler": OnAfterSetItemLedgerEntryFilters

We would need to modify the filters in order to be able to forecast by Entry Type: Sales and Negative Adjustments.

```
procedure SetItemLedgerEntryFilters(var ItemLedgerEntry: Record "Item Ledger Entry"; ItemNo: Code[20])
.
.
.
.
ItemLedgerEntry.SetRange("Item No.", ItemNo);
///////// START
OnAfterSetItemLedgerEntryFilters(ItemLedgerEntry);
///////// END

```

Signature:
```
[IntegrationEvent(false, false)]
local procedure OnAfterSetItemLedgerEntryFilters(var ItemLedgerEntry: Record "Item Ledger Entry")
begin
end;
```

Also, modify the [documentation ](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-extensions-sales-forecast#data-required-for-forecast) to inform that Sales and Negative adjustaments are required.

**Comment by AndreiPanko** [comment]
@deadmouse thank you for your suggestion.
The extension is published on github: https://github.com/microsoft/ALAppExtensions/blob/master/Apps/W1/SalesAndInventoryForecast/app/src/SalesForecastHandler.Codeunit.al
Could you please create a pull request with proposed changes? 

Sincerely,
Andrei Panko
Program Manager
