### ISSUE TITLE
Error in the new page/function "Data Administration" (Action Refresh)

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#13104]
Error in the new page/function ["Data Administration"](https://docs.microsoft.com/en-us/dynamics365-release-plan/2021wave1/smb/dynamics365-business-central/data-clean-up-tasks-page). When the data is updated (Refresh) and the language is set to German (Germany) you get this error:
![image](https://user-images.githubusercontent.com/39938430/124547431-6804bb80-de2c-11eb-8e21-99eeaf9e99bd.png)

Tested with these Artifacts:
[https://bcartifacts.azureedge.net/onprem/18.3.27240.27480/de](https://bcartifacts.azureedge.net/onprem/18.3.27240.27480/de)

**Comment by stkillen** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
