### ISSUE TITLE
[Access Request] protected var - report 38 "Trial Balance by Period"

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#13100]
Can you change the variables **ColumnValuesAsText** and **MaxCount** to protected var in report 38 "Trial Balance by Period"?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
