### ISSUE TITLE
[Event Request And Code] Page 99000883 Sales Order Planning - Function CreateOrders

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#13105]
We need a new Publisher and Codeline in Page "Sales Order Planning", Function CreateOrders

    local procedure CreateOrders() OrdersCreated: Boolean
    var
        xSalesPlanLine: Record "Sales Planning Line";
        Item: Record Item;
        SalesLine: Record "Sales Line";
        SKU: Record "Stockkeeping Unit";
        CreateProdOrder: Boolean;
        EndLoop: Boolean;
        IsHandled: Boolean;
        ApplySetSelectionFilter: Boolean;
    begin
        xSalesPlanLine := Rec;

        // ###########  event request and code #############
        OnBeforeCurrPageSetSelectionFilter(ApplySetSelectionFilter);
        if ApplySetSelectionFilter then
            CurrPage.SetSelectionFilter(Rec);
        // ###########  event request and code #############

        if not FindSet() then
            exit;

        repeat
            ....
        until (Next() = 0) or EndLoop;

        Rec := xSalesPlanLine;
    end;

     // ###########  event request #############
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCurrPageSetSelectionFilter(var ApplySetSelectionFilter: Boolean)
    begin
    end;
     // ###########  event request #############

**Comment by AndreBreitenbach** [comment]
To make this "request" more useable for more scenarios add "Rec , xSalesPlanLine and SalesLine" as additional parameters.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
