### ISSUE TITLE
[Event Request] codeunit 8614 "Config. XML Exchange" - OnAfterSetConfigPackageFieldFilterOnCreateRecordNodes

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13112]
We would like a new event OnAfterSetConfigPackageFieldFilterOnCreateRecordNodes in the following procedure.
This event procedure must be called twice in CreateRecordNodes.
The exact same base code filtering on ConfigPackageField exists 2 times. 

local procedure CreateRecordNodes(var PackageXML: DotNet XmlDocument; ConfigPackageTable: Record "Config. Package Table")
.
.
.
ConfigPackageField.SetRange("Package Code", ConfigPackageTable."Package Code");
                ConfigPackageField.SetRange("Table ID", ConfigPackageTable."Table ID");
                ConfigPackageField.SetRange("Include Field", true);
                ConfigPackageField.SetRange(Dimension, false);
                ConfigPackageField.SetCurrentKey("Package Code", "Table ID", "Processing Order");
                OnAfterSetConfigPackageFieldFilterOnCreateRecordNodes(ConfigPackageField); //A100F0001.Event.n A200F0003.Event.n
                if ConfigPackageField.FindSet then

Event signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetConfigPackageFieldFilterOnCreateRecordNodes(var ConfigPackageField: Record "Config. Package Field")
    begin
        //A100F0001.Event A200F0003.Event 
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
