### ISSUE TITLE
[Event Request] codeunit 8614 "Config. XML Exchange" - OnAfterCreateRecordNodes

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13113]
We would like to add a new event OnAfterCreateRecordNodes in the following procedure:

    
local procedure CreateRecordNodes(var PackageXML: DotNet XmlDocument; ConfigPackageTable: Record "Config. Package Table")
.
.
.

                if ConfigPackageTable."Dimensions as Columns" and ExcelMode then
                    AddDimensionFields(ConfigPackageField, RecRef, PackageXML, RecordNode, FieldNode, true);
                OnAfterCreateRecordNodes(ConfigPackageTable, ConfigPackageField, RecRef, PackageXML, RecordNode, FieldNode, ExcelMode, true); //A100F0001.Event.n A200F0003.Event.n
                ExportMetadata := false;
                ProcessedRecordCount += 1;

            if ConfigPackageTable."Dimensions as Columns" and ExcelMode then
                AddDimensionFields(ConfigPackageField, RecRef, PackageXML, RecordNode, FieldNode, false);
            OnAfterCreateRecordNodes(ConfigPackageTable, ConfigPackageField, RecRef, PackageXML, RecordNode, FieldNode, ExcelMode, false); //A100F0001.Event.n A200F0003.Event.n                
        end;

Event signature:

[IntegrationEvent(false, false)]
    local procedure OnAfterCreateRecordNodes(ConfigPackageTable: Record "Config. Package Table"; var ConfigPackageField: Record "Config. Package Field"; var RecRef: RecordRef; var PackageXML: DotNet XmlDocument; var RecordNode: DotNet XmlNode; var FieldNode: DotNet XmlNode; ExcelMode: Boolean; ExportValue: Boolean)
    begin
        //A100F0001.Event A200F0003.Event 
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
