### ISSUE TITLE
[Event Request] report 5405 "Calc. Consumption" - OnBeforeModifyExistingItemJournalLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13117]
We would like to add a new event OnBeforeModifyExistingItemJournalLine in the following procedure:

    local procedure CreateConsumpJnlLine(LocationCode: Code[10]; BinCode: Code[20]; QtyToPost: Decimal)
    var
        Location: Record Location;
        IsHandled: Boolean;
    begin
        OnBeforeCreateConsumpJnlLine(LocationCode, BinCode, QtyToPost);

        Window.Update(3, QtyToPost);

        if Location.Get(LocationCode) and Location."Require Pick" and Location."Require Shipment" then
            "Prod. Order Component".AdjustQtyToQtyPicked(QtyToPost);

        //A200F0000.Event.ns
        IsHandled := false;
        OnBeforeModifyExistingItemJournalLine(ItemJnlLine, IsHandled);
        //A200F0000.Event.ne
        if (ItemJnlLine."Item No." = "Prod. Order Component"."Item No.") and
            not IsHandled and //A200F0000.Event
           (LocationCode = ItemJnlLine."Location Code") and
           (BinCode = ItemJnlLine."Bin Code")
        then begin

Event signature:

[IntegrationEvent(false, false)]
    local procedure OnBeforeModifyExistingItemJournalLine(var ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
