### ISSUE TITLE
[Event Request] page 5847 "Average Cost Calc. Overview" - OnSetAverageCostCalcOverviewItemFilter

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13110]
We would like an event in the following two procedures based on 17.5 base:

procedure InitTempTable()
    var
        AvgCostCalcOverviewFilters: Record "Average Cost Calc. Overview";
    begin
        AvgCostCalcOverview."Item No." := Item."No.";
        AvgCostCalcOverview.SetFilter("Valuation Date", Item.GetFilter("Date Filter"));
        AvgCostCalcOverview.SetFilter("Location Code", Item.GetFilter("Location Filter"));
        AvgCostCalcOverview.SetFilter("Variant Code", Item.GetFilter("Variant Filter"));
        OnSetAverageCostCalcOverviewItemFilter(AvgCostCalcOverview, item); //A200F0002.Event

local procedure ExpandAll(var AvgCostCalcOverview: Record "Average Cost Calc. Overview")
    var
        AvgCostCalcOverviewFilters: Record "Average Cost Calc. Overview";
    begin
        AvgCostCalcOverview."Item No." := Item."No.";
        AvgCostCalcOverview.SetFilter("Valuation Date", Item.GetFilter("Date Filter"));
        AvgCostCalcOverview.SetFilter("Location Code", Item.GetFilter("Location Filter"));
        AvgCostCalcOverview.SetFilter("Variant Code", Item.GetFilter("Variant Filter"));
        OnSetAverageCostCalcOverviewItemFilter(AvgCostCalcOverview, item); //A200F0002.Event

Event signature:

 [IntegrationEvent(false, false)]
    local procedure OnSetAverageCostCalcOverviewItemFilter(var AverageCostCalcOverview: Record "Average Cost Calc. Overview"; var Item: Record Item)
    begin
        //A200F0002.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
