### ISSUE TITLE
[Event Request] report 5405 "Calc. Consumption" - OnAfterCreateItemJournalLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13118]
We would like to add a new event OnAfterCreateItemJournalLine in the following procedure:

    local procedure CreateConsumpJnlLine(LocationCode: Code[10]; BinCode: Code[20]; QtyToPost: Decimal)
.
.
.
            if Item."Item Tracking Code" <> '' then
                AssignItemTracking("Prod. Order Component", ItemJnlLine);
            OnAfterCreateItemJournalLine(ItemJnlLine, NextConsumpJnlLineNo); //A200F0000.Event
        end;

Event signature:

 [IntegrationEvent(false, false)]
    local procedure OnAfterCreateItemJournalLine(var ItemJournalLine: Record "Item Journal Line"; var NextLineNo: Integer)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
