### ISSUE TITLE
[Event Request] codeunit 8614 "Config. XML Exchange" - OnAfterGetPackageTableValueFromXML

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13114]
We would like to add a new event OnAfterCreateRecordNodes in the following procedure:   

local procedure FillPackageMetadataFromXML(var PackageCode: Code[20]; TableID: Integer; var TableNode: DotNet XmlNode)
.
.
.
                if Value <> '' then
                    Evaluate(ConfigPackageTable."Created by User ID", CopyStr(Value, 1, 50));
                OnAfterGetPackageTableValueFromXML(ConfigPackageTable, TableNode); //A100F0001.Event A200F0003.Event
                ConfigPackageTable."Data Template" :=
                  CopyStr(

Event signature:

[IntegrationEvent(false, false)]
    local procedure OnAfterGetPackageTableValueFromXML(ConfigPackageTable: Record "Config. Package Table"; var TableNode: DotNet XmlNode)
    begin
        //A100F0001.Event A200F0003.Event 
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
