### ISSUE TITLE
[Event Request] codeunit 8614 "Config. XML Exchange" - OnAfterInitConfigPackageData

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13115]
We would like to add a new event OnAfterInitConfigPackageData in the following procedure:

local procedure FillPackageDataFromXML(PackageCode: Code[20]; TableID: Integer; var TableNode: DotNet XmlNode)
.
.
.
                            ConfigPackageData.Init();
                            OnAfterInitConfigPackageData(ConfigPackageData, TempConfigPackageField); //A100F0001.Event A200F0003.Event
                            ConfigPackageData."Package Code" := TempConfigPackageField."Package Code";
                            ConfigPackageData."Table ID" := TempConfigPackageField."Table ID";
                            ConfigPackageData."Field ID" := TempConfigPackageField."Field ID";
                            ConfigPackageData."No." := ConfigPackageRecord."No.";
                            if FieldNodeExists(RecordNode, GetElementName(TempConfigPackageField."Field Name")) or
                               TempConfigPackageField.Dimension

    
Event signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterInitConfigPackageData(var ConfigPackageData: Record "Config. Package Data"; var ConfigPackageField: Record "Config. Package Field")
    begin
        //A100F0001.Event A200F0003.Event 
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
