### ISSUE TITLE
[Event Request] codeunit 8614 "Config. XML Exchange" - OnAfterAddTableAttributes

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13111]
We would like a new event OnAfterAddTableAttributes in the following procedure:

local procedure AddTableAttributes(ConfigPackageTable: Record "Config. Package Table"; var PackageXML: DotNet XmlDocument; var TableNode: DotNet XmlNode)
.
.
.
if "Dimensions as Columns" then begin
                FieldNode := PackageXML.CreateElement(GetElementName(FieldName("Dimensions as Columns")));
                FieldNode.InnerText := '1';
                TableNode.AppendChild(FieldNode);
            end;
            OnAfterAddTableAttributes(ConfigPackageTable, PackageXML, TableNode); //A100F0001.Event A200F0003.Event
end;

Event signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterAddTableAttributes(ConfigPackageTable: Record "Config. Package Table"; var PackageXML: DotNet XmlDocument; var TableNode: DotNet XmlNode)
    begin
        //A100F0001.Event A200F0003.Event 
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
