### ISSUE TITLE
request for protected variable - report 1316 "Standard Statement" - CustBalance

### ISSUE THREAD

**Issue by db-bc** [microsoft/ALAppExtensions#13126]
I previously requested events that enabled us to implement the extremely common client request of showing only entries that are still open in their statements. Those were supplied. Thanks!

And now it looks like report extension triggers enable doing the same thing in another way. Even better! It's IMO considerably preferable to implement such changes in a report extension, rather than a subscriber codeunit.

However, doing that means the cumulative CustBalance is wrong, as it sums the Amount of the detailed entries, but if showing only Open entries, we need to show their Remaining Amount (because for a partially applied invoice, the payment will be closed, so its Amount won't be added/subtracted from the cumulative CustBalance).

We therefore need to modify the `CustBalance` to only add the Remaining Amount if showing only Open entries. Therefore, please can you make said variable `protected`, so that we can modify it in a report extension? _How_ to modify it seems like it'll be a bit of a faff, but just being _able_ to should help us get there.

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
