### ISSUE TITLE
[Enum Request] Table 1248 Ledger Entry Matching Buffer

### ISSUE THREAD

**Issue by stryzhak** [microsoft/ALAppExtensions#13129]
Could you please change field "Account Type" type from option to enum?

![image](https://user-images.githubusercontent.com/29860849/125049725-f20d8800-e0a9-11eb-8243-6b7cfb23bc88.png)

P.S 

#11604 hasn't shipped yet.

**Comment by AlexanderYakunin** [comment]
We implement enums in next major only, it is done for 19.0
