### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134227 "ERM PostRecurringJournal"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#13124]
[Event Request]Application “Tests-ERM”, 134227 "ERM PostRecurringJournal"

Could you please insert the OnTestInitialize Event at the beginning of the procedure PostMultipleRecurringJournalLineUserSetupNotAllowedPostingPeriod?

![pic1](https://user-images.githubusercontent.com/45795262/124804905-173fb080-df5b-11eb-89e0-576fe0f1a8a9.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
