### ISSUE TITLE
[Event Request] codeunit 97 "Blanket Purch. Order to Order" - OnBeforeTransferPurchaseBlanketOrderLineToPurchaseOrderLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13121]
We would like to add a new event OnBeforeModifyExistingItemJournalLine

 if PurchOrderLine.Quantity <> 0 then
                            PurchOrderLine.Validate("Inv. Discount Amount", PurchBlanketOrderLine."Inv. Discount Amount");
                        PurchBlanketOrderLine.CalcFields("Reserved Qty. (Base)");
                        OnBeforeTransferPurchaseBlanketOrderLineToPurchaseOrderLine(Rec, PurchBlanketOrderLine, PurchOrderHeader, PurchOrderLine); //A108F0093.Event
                        if PurchBlanketOrderLine."Reserved Qty. (Base)" <> 0 then
                            ReservePurchLine.TransferPurchLineToPurchLine(
                              PurchBlanketOrderLine, PurchOrderLine, -PurchBlanketOrderLine."Qty. to Receive (Base)");

Event signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferPurchaseBlanketOrderLineToPurchaseOrderLine(PurchaseBlanketOrder: Record "Purchase Header"; var PurchaseBlanketOrderLine: Record "Purchase Line"; PurchaseOrder: Record "Purchase Header"; var PurchaseOrderLine: Record "Purchase Line")
    begin
        //A108F0093.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
