### ISSUE TITLE
[EventParameter] New parameter required in event OnAfterShouldFinalizeSalesInvHeader of report "Combine Return Receipts"

### ISSUE THREAD

**Issue by TriangleSPV** [microsoft/ALAppExtensions#13125]
We need that the event OnAfterShouldFinalizeSalesInvHeader from the report 6653 "Combine Return Receipts" contains the same paremeters than the same event of the report 295 "Combine Shipments".

In the report 295 there is a 4th parament with the sales shipment line that we are looping. In the report 6653 there are only 3 parameters and we need the "Return Receipt Line" that we are looping.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
