### ISSUE TITLE
[Event Request] Table 5906 Service Comment Line - OnInsert

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#13128]
Hi,

Is it possible to stuff all the code in the OnInsert Event of table 5906 "Service Comment Line" into a seperate function and include a handled pattern to this function? We would like to overrule the check that "Table Line No." is filled. We tried working arround it, however that is difficult to achieve because both Type and Table Line No. are part of the primary key.

```
    trigger OnInsert()
    begin
        if Type in ["Service Comment Line Type"::Fault, "Service Comment Line Type"::Resolution,
                    "Service Comment Line Type"::Accessory, "Service Comment Line Type"::Internal]
        then
            TestField("Table Line No.");
    end;
```

New Solution:

```
   trigger OnInsert()
   begin
       TestTableLineNo();
   end;

   procedure TestTableLineNo()
   var
       IsHandled: Boolean;
   begin
        OnBeforeTestTableLineNo(Rec, IsHandled);
        if IsHandled then
            exit;

        if Type in ["Service Comment Line Type"::Fault, "Service Comment Line Type"::Resolution,
                    "Service Comment Line Type"::Accessory, "Service Comment Line Type"::Internal]
        then
            TestField("Table Line No.");
   end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
