### ISSUE TITLE
[Event Request] table 5050 Contact - OnAfterOnInsert

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13123]
We would like to add a new event OnAfterOnInsert in the following trigger:

    trigger OnInsert()
.
.
.
        TypeChange;
        SetLastDateTimeModified;
        SetSearchEmail();
 OnAfterOnInsert(Rec, xRec); //A113F0000.Event

Event signature:

local procedure OnAfterOnInsert(var Contact: Record Contact; var xContact: Record Contact)
    begin
        //A113F0000.Event
    end;

**Comment by db-bc** [comment]
I'm curious why anyone would need a new event publisher, when system table events `OnBeforeInsert` and `OnAfterInsert` exist?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
