### ISSUE TITLE
[Function Expose] Codeunit 11514 Swiss QR-Bill Image Mgt. function GenerateSwissQRCodeImage  

### ISSUE THREAD

**Issue by Kowa63** [microsoft/ALAppExtensions#13127]
Would it be possible to change the  visibility of function _GenerateSwissQRCodeImage_ in Codeunit 11514 to external?  
https://github.com/microsoft/ALAppExtensions/blob/master/Apps/CH/SwissQRBill/app/src/core/ImageMgt.Codeunit.al
![grafik](https://user-images.githubusercontent.com/16236672/124931062-27f73180-e002-11eb-9e3e-84f9500e6d76.png)

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
