### ISSUE TITLE
[Event Request] codeunit 87 "Blanket Sales Order to Order" - OnBeforeTransferSalesBlanketOrderLineToSalesOrderLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13120]
We would like to add a new event OnBeforeTransferSalesBlanketOrderLineToSalesOrderLine:

if SalesOrderLine.Quantity <> 0 then
  SalesOrderLine.Validate("Inv. Discount Amount", BlanketOrderSalesLine."Inv. Discount Amount");
OnBeforeTransferSalesBlanketOrderLineToSalesOrderLine(Rec, BlanketOrderSalesLine, SalesOrderHeader, SalesOrderLine); //A108F0093.Event
SalesLineReserve.TransferSaleLineToSalesLine(BlanketOrderSalesLine, SalesOrderLine, BlanketOrderSalesLine."Qty. to Ship (Base)");

Event signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferSalesBlanketOrderLineToSalesOrderLine(SalesBlanketOrder: Record "Sales Header"; var SalesBlanketOrderLine: Record "Sales Line"; SalesOrder: Record "Sales Header"; var SalesOrderLine: Record "Sales Line")
    begin
        //A108F0093.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
