### ISSUE TITLE
[Access Request] page 1286 "Payment Rec Match Details" - Global Variables Access

### ISSUE THREAD

**Issue by stryzhak** [microsoft/ALAppExtensions#13131]
Hi,

Could you please make global variables in the page to be protected? We need to recalculate them using different "Account Type" and show correct ones.

RelatedPartyMatchedText
AmountMatchText
DocumentMatchedText
DirectDebitMatchedText
DirectDebitMatched
NoOfLedgerEntriesWithinAmountTolerance
NoOfLedgerEntriesOutsideAmountTolerance
RelatedPartyMatchInfoText
RelatedPartyMatchInfoEnabled
DocumentMatchInfoText
DocumentMatchDetailsEnabled

#11702 hasn't shipped yet.

**Comment by AlexanderYakunin** [comment]
This is already done for 19.0.
