### ISSUE TITLE
[Event Request] codeunit 8611 "Config. Package Management" - OnBeforeValidateConfigPackageFieldID, OnBeforeSetConfigPackageFieldRelationTableID and OnBeforeInsertConfigPackageField.

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13134]
We would like to add 3 events OnBeforeValidateConfigPackageFieldID, OnBeforeSetConfigPackageFieldRelationTableID, OnBeforeInsertConfigPackageField in the following procedure:

    procedure InsertPackageField(var ConfigPackageField: Record "Config. Package Field"; PackageCode: Code[20]; TableID: Integer; FieldID: Integer; FieldName: Text[30]; FieldCaption: Text[250]; SetInclude: Boolean; SetValidate: Boolean; SetLocalize: Boolean; SetDimension: Boolean)
    var
        SkipRelationTableID: Boolean;
    begin
        if not ConfigPackageField.Get(PackageCode, TableID, FieldID) then begin
            ConfigPackageField.Init();
            ConfigPackageField.Validate("Package Code", PackageCode);
            ConfigPackageField.Validate("Table ID", TableID);
            ConfigPackageField.Validate(Dimension, SetDimension);
            OnBeforeValidateConfigPackageFieldID(ConfigPackageField); //A100F0001.Event
            ConfigPackageField.Validate("Field ID", FieldID);
            ConfigPackageField.Validate("Field Name", FieldName);
            ConfigPackageField."Field Caption" := FieldCaption;
            ConfigPackageField."Primary Key" := ConfigValidateMgt.IsKeyField(TableID, FieldID);
            ConfigPackageField."Include Field" := SetInclude or ConfigPackageField."Primary Key";
            //if not SetDimension then begin A100F0001.Event.o
            //A100F0001.Event.ns
            SkipRelationTableID := not SetDimension;
            OnBeforeSetConfigPackageFieldRelationTableID(ConfigPackageField, SkipRelationTableID);
            if SkipRelationTableID then begin
                //A100F0001.Event.ne
                ConfigPackageField."Relation Table ID" := ConfigValidateMgt.GetRelationTableID(TableID, FieldID);
                ConfigPackageField."Validate Field" :=
                  ConfigPackageField."Include Field" and SetValidate and not ValidateException(TableID, FieldID);
            end;
            ConfigPackageField."Localize Field" := SetLocalize;
            ConfigPackageField.Dimension := SetDimension;
            if SetDimension then
                ConfigPackageField."Processing Order" := ConfigPackageField."Field ID";
            OnBeforeInsertConfigPackageField(ConfigPackageField); //A100F0001.Event
            ConfigPackageField.Insert();
        end;
    end;

Event signature 1:

[IntegrationEvent(false, false)]
    local procedure OnBeforeValidateConfigPackageFieldID(var ConfigPackageField: Record "Config. Package Field")
    begin
        //A100F0001.Event
    end;

Event signature 2:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetConfigPackageFieldRelationTableID(var ConfigPackageField: Record "Config. Package Field"; var SkipRelationTableID: Boolean)
    begin
        //A100F0001.Event
    end;

Event signature 3:

    [IntegrationEvent(false, false)]
    local procedure  (var ConfigPackageField: Record "Config. Package Field")
    begin
        //A100F0001.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
