### ISSUE TITLE
[Event Request] codeunit 7600 "Calendar Management" - OnBeforeSetSourceShippingAgentServices 

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13132]
We would like to add a new event OnBeforeSetSourceShippingAgentServices in the following procedure:

    local procedure SetSourceShippingAgentServices(RecRef: RecordRef; var CustomCalendarChange: Record "Customized Calendar Change")
    var
        ShippingAgentServices: Record "Shipping Agent Services";
    begin
        RecRef.SetTable(ShippingAgentServices);
        OnBeforeSetSourceShippingAgentServices(ShippingAgentServices); //A108F0071.Event
        CustomCalendarChange.SetSource(
            CustomCalendarChange."Source Type"::"Shipping Agent", ShippingAgentServices."Shipping Agent Code",
            ShippingAgentServices.Code, ShippingAgentServices."Base Calendar Code");

    Event signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetSourceShippingAgentServices(var ShippingAgentServices: Record "Shipping Agent Services")
    begin
        //A108F0071.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
