### ISSUE TITLE
[Event Request] codeunit 8611 "Config. Package Management" - OnBeforeValidateException

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13136]
We would like to add a new event OnBeforeValidateException in the following procedure:

    procedure ValidateException(TableID: Integer; FieldID: Integer): Boolean
    var
        IsHandled: Boolean;
        ResultValue: Boolean;
    begin
        //A100F0001.Event.ns
        OnBeforeValidateException(TableID, FieldID, ResultValue, IsHandled);
        if IsHandled then
            exit(ResultValue);
        //A100F0001.Event.ne
        case TableID of

Event signature 

[IntegrationEvent(false, false)]
    local procedure OnBeforeValidateException(TableID: Integer; FieldID: Integer; var ResultValue: Boolean; var IsHandled: Boolean)
    begin
        //A100F0001.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
