### ISSUE TITLE
[Event Request] codeunit 7322 "Create Inventory Pick/Movement" - OnAfterPrepareItemTrackingFromWhseItemTracking

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13139]
We would like to add a new event OnAfterPrepareItemTrackingFromWhseItemTracking in the following procedure:

    local procedure PrepareItemTrackingFromWhseIT(SourceType: Integer; SourceSubtype: Integer; SourceNo: Code[20]; SourceLineNo: Integer; SignFactor: Integer)
    var
        WhseItemTrackingLine: Record "Whse. Item Tracking Line";
        EntryNo: Integer;
    begin
        if TempReservEntry.FindLast() then
            EntryNo := TempReservEntry."Entry No.";

        WhseItemTrackingLine.SetSourceFilter(SourceType, SourceSubtype, SourceNo, SourceLineNo, true);
        if WhseItemTrackingLine.Find('-') then
            repeat
                TempReservEntry.TransferFields(WhseItemTrackingLine);
                EntryNo += 1;
                TempReservEntry."Entry No." := EntryNo;
                TempReservEntry."Reservation Status" := TempReservEntry."Reservation Status"::Surplus;
                if SignFactor < 0 then
                    TempReservEntry.Validate("Quantity (Base)", -TempReservEntry."Quantity (Base)");
                TempReservEntry.Positive := (TempReservEntry."Quantity (Base)" > 0);
                TempReservEntry.UpdateItemTracking;
                OnBeforeTempReservEntryInsert(TempReservEntry, WhseItemTrackingLine);
                TempReservEntry.Insert();
            until WhseItemTrackingLine.Next() = 0;
        OnAfterPrepareItemTrackingFromWhseItemTracking(TempReservEntry, EntryNo); //A200F0000.Event
    end;

Event signature

    [IntegrationEvent(false, false)]
    local procedure OnAfterPrepareItemTrackingFromWhseItemTracking(var ReservationEntryBuffer: Record "Reservation Entry"; var EntryNo: Integer)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
