### ISSUE TITLE
[Event Request] codeunit 8611 "Config. Package Management" - OnBeforeHandleRecRefModification

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13135]
We would like to add a new event OnBeforeHandleRecRefModification in the following procedure:

local procedure ModifyRecordDataFields(var RecRef: RecordRef; ConfigPackageRecord: Record "Config. Package Record"; DoModify: Boolean; DelayedInsert: Boolean)
.
.
.
 if not DoModify then
   exit;
  if not RecRef.IsDirty() then
   exit;
  OnBeforeHandleRecRefModification(RecRef, ConfigPackageRecord, DoModify, DelayedInsert); //A100F0001.Event

  if DelayedInsert then
  RecRef.Insert(true)
  else begin
   RecRef.Modify(not ConfigPackageTable."Skip Table Triggers");
   OnModifyRecordDataFieldsOnAfterRecRefModify(RecRef);
  RecordsModifiedCount += 1;
  end;

Event signature

[IntegrationEvent(false, false)]
    local procedure OnBeforeHandleRecRefModification(var RecRef: RecordRef; ConfigPackageRecord: Record "Config. Package Record"; DoModify: Boolean; DelayedInsert: Boolean)
    begin
        //A100F0001.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
