### ISSUE TITLE
[Event Request] codeunit 99000813 "Carry Out Action" - OnBeforeCheckInsertTransferHeader

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13133]
We would like to add a new event OnBeforeCheckInsertTransferHeader in the following procedure:

    procedure InsertTransLine(ReqLine: Record "Requisition Line"; var TransHeader: Record "Transfer Header")
    var
        TransLine: Record "Transfer Line";
        NextLineNo: Integer;
        Result: Boolean;
    begin
        OnBeforeCheckInsertTransferHeader(ReqLine, TransHeader, Result); //A114F0000.Event
        if (ReqLine."Transfer-from Code" <> TransHeader."Transfer-from Code") or
          Result or //A114F0000.Event
           (ReqLine."Location Code" <> TransHeader."Transfer-to Code")
        then
            InsertTransHeader(ReqLine, TransHeader);

Event signature:

[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckInsertTransferHeader(RequisitionLine: Record "Requisition Line"; TransferHeader: Record "Transfer Header"; var Result: Boolean)
    begin
        //A114F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
