### ISSUE TITLE
[Event Request] codeunit 7322 "Create Inventory Pick/Movement" - OnBeforeRun

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13138]
We would like to add a new event OnBeforeRun in the following trigger:

    trigger OnRun()
    begin
        OnBeforeRun(Rec); //A113F0005.Event
        WhseActivHeader := Rec;
        Code;
        Rec := WhseActivHeader;
    end;

Event signature

    [IntegrationEvent(false, false)]
    local procedure OnBeforeRun(var WarehouseActivityHeader: Record "Warehouse Activity Header")
    begin
        //A113F0005.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
