### ISSUE TITLE
[Access Request] Page 1287 "Payment Application Review" - Global Variables Access 

### ISSUE THREAD

**Issue by stryzhak** [microsoft/ALAppExtensions#13130]
Could you please make global variables in the page to be protected? We need to recalculate them using different "Account Type" and show correct ones.

RelatedPartyMatchedText
AmountMatchText
DocumentMatchedText
DirectDebitMatchedText
DirectDebitMatched
NoOfLedgerEntriesWithinAmountTolerance
NoOfLedgerEntriesOutsideAmountTolerance
RelatedPartyMatchInfoText
DocumentMatchInfoText
DocumentMatchDetailsEnabled

#11701 hasn't shipped yet.

**Comment by AlexanderYakunin** [comment]
This is already done for 19.0.

    protected var
        AmountMatchText: Text;
        DirectDebitMatchedText: Text;
        DirectDebitMatched: Boolean;
        DocumentMatchDetailsEnabled: Boolean;
        DocumentMatchedText: Text;
        DocumentMatchInfoText: Text;
        RelatedPartyMatchedText: Text;
        RelatedPartyMatchInfoText: Text;
        NoOfLedgerEntriesWithinAmountTolerance: Integer;
        NoOfLedgerEntriesOutsideAmountTolerance: Integer;
