### ISSUE TITLE
[Event Request] codeunit 5847 "Get Average Cost Calc Overview" - OnAfterSetAvgCostAdjmtEntryPointFilter

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13142]
We would like to add a new event OnAfterSetAvgCostAdjmtEntryPointFilter in the following trigger:

    trigger OnRun()
    begin
        AvgCostAdjmtEntryPoint.SetRange("Item No.", "Item No.");
        AvgCostAdjmtEntryPoint.SetFilter("Location Code", GetFilter("Location Code"));
        AvgCostAdjmtEntryPoint.SetFilter("Variant Code", GetFilter("Variant Code"));
        AvgCostAdjmtEntryPoint.SetFilter("Valuation Date", GetFilter("Valuation Date"));
        OnAfterSetAvgCostAdjmtEntryPointFilter(AvgCostAdjmtEntryPoint, Rec); //A200F0002.Event

        Reset;

Event signature

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetAvgCostAdjmtEntryPointFilter(var AvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point"; var AvgCostCalcOverview: Record "Average Cost Calc. Overview")
    begin
        //A200F0002.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
