### ISSUE TITLE
[Event Request] codeunit 5847 "Get Average Cost Calc Overview" - OnAfterSetValueEntryFilter

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13144]
We would like to add a new event OnAfterSetValueEntryFilter in the following procedure:

    procedure EntriesExist(var AvgCostCalcOverview: Record "Average Cost Calc. Overview"): Boolean
    begin
        with ValueEntry do begin
            Item.Get(AvgCostCalcOverview."Item No.");
            OnEntriesExistOnAfterGetItem(Item, AvgCostCalcOverview);

            Reset;
            SetCurrentKey("Item No.", "Valuation Date", "Location Code", "Variant Code");
            SetRange("Item No.", AvgCostCalcOverview."Item No.");

            if Item."Costing Method" = Item."Costing Method"::Average then begin
                CalendarPeriod."Period Start" := AvgCostCalcOverview."Valuation Date";
                AvgCostAdjmtEntryPoint."Valuation Date" := AvgCostCalcOverview."Valuation Date";
                AvgCostAdjmtEntryPoint.GetValuationPeriod(CalendarPeriod);
                SetRange("Valuation Date", CalendarPeriod."Period Start", CalendarPeriod."Period End");
            end else
                SetRange("Valuation Date", AvgCostCalcOverview."Valuation Date");

            if not AvgCostAdjmtEntryPoint.IsAvgCostCalcTypeItem(AvgCostCalcOverview."Valuation Date") or
               not (Item."Costing Method" = Item."Costing Method"::Average)
            then begin
                SetRange("Location Code", AvgCostCalcOverview."Location Code");
                SetRange("Variant Code", AvgCostCalcOverview."Variant Code");
            end;
            OnAfterSetValueEntryFilter(ValueEntry, Item, AvgCostCalcOverview); //A200F0002.Event
            exit(Find('-'));
        end;

Event signature

   [IntegrationEvent(false, false)]
    local procedure OnAfterSetValueEntryFilter(var ValueEntry: Record "Value Entry"; var Item: Record Item; var AvgCostCalcOverview: Record "Average Cost Calc. Overview")
    begin
        //A200F0002.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
