### ISSUE TITLE
[Event Request] codeunit 5847 "Get Average Cost Calc Overview" - OnAfterCopyItemLedgerEntryToAvgCostCalcOverview

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13145]
We would like to add a new event OnAfterCopyItemLedgerEntryToAvgCostCalcOverview in the following procedure :

    local procedure InsertAvgCostCalcOvervwFromILE(var AvgCostCalcOverview: Record "Average Cost Calc. Overview"; ValueEntry: Record "Value Entry"; ValuationDate: Date)
.
.
.
            if not ModifyLine then begin
                ItemLedgEntry.Get(ValueEntry."Item Ledger Entry No.");
                Init;
                "Item No." := ItemLedgEntry."Item No.";
                "Location Code" := ItemLedgEntry."Location Code";
                "Variant Code" := ItemLedgEntry."Variant Code";
                "Posting Date" := ItemLedgEntry."Posting Date";
                "Item Ledger Entry No." := ItemLedgEntry."Entry No.";
                "Entry Type" := ItemLedgEntry."Entry Type";
                "Document Type" := ItemLedgEntry."Document Type".AsInteger();
                "Document No." := ItemLedgEntry."Document No.";
                "Document Line No." := ItemLedgEntry."Document Line No.";
                Description := ItemLedgEntry.Description;
                OnAfterCopyItemLedgerEntryToAvgCostCalcOverview(AvgCostCalcOverview, ItemLedgEntry); //A200F0002.Event
                "Entry No." := CopyOfAvgCostCalcOverview."Entry No." + 1;
                case true of
                    ValueEntry."Partial Revaluation":
                        Type := Type::Revaluation;

Event signature

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyItemLedgerEntryToAvgCostCalcOverview(var AvgCostCalcOverview: Record "Average Cost Calc. Overview"; ItemLedgerEntry: Record "Item Ledger Entry")
    begin
        //A200F0002.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
