### ISSUE TITLE
[Event Request] codeunit 5520 "Get Unplanned Demand" - OnBeforeInsertSalesLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13147]
We would like to add a new event OnBeforeInsertSalesLine in the following procedure:

    local procedure InsertSalesLine(var UnplannedDemand: Record "Unplanned Demand")
    var
        UnplannedDemand2: Record "Unplanned Demand";
    begin
        with UnplannedDemand do begin
            UnplannedDemand2.Copy(UnplannedDemand);
            InitRecord(
              SalesLine."Line No.", 0, SalesLine."No.", SalesLine.Description, SalesLine."Variant Code", SalesLine."Location Code",
              SalesLine."Bin Code", SalesLine."Unit of Measure Code", SalesLine."Qty. per Unit of Measure",
              DemandQtyBase, SalesLine."Shipment Date");
            OnInsertSalesLineOnAfterInitRecord(UnplannedDemand, SalesLine);
            Reserve := SalesLine.Reserve = SalesLine.Reserve::Always;
            "Special Order" := SalesLine."Special Order";
            "Purchasing Code" := SalesLine."Purchasing Code";
            OnBeforeInsertSalesLine(UnplannedDemand, SalesLine); //A200F0000.n
            Insert;
            Copy(UnplannedDemand2);
        end;

Event Signature

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertSalesLine(var UnplannedDemand: Record "Unplanned Demand"; SalesLine: Record "Sales Line")
    begin
        //A200F0000.event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
