### ISSUE TITLE
Event on MakeRecurringTexts (Codeunit 13) or add function to template External Document No. for Recurring Journals

### ISSUE THREAD

**Issue by LoanVision** [Microsoft/ALAppExtensions#1314]
Event on MakeRecurringTexts (Codeunit 13) or add function to template External Document No. for Recurring Journals, something like:
`          "External Document No." :=
            DELCHR(
              PADSTR(
                STRSUBSTNO("External Document No.",Day,Week,Month,MonthText,AccountingPeriod.Name),
                MAXSTRLEN("External Document No.")),
              '>');`

Thanks!

**Comment by AlexanderYakunin** [comment]
Can you be more specific about evenbt parameters and location?
