### ISSUE TITLE
[Event Request] codeunit 7313 "Create Put-away" - OnBeforeBinCalcQtyToPutAway

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13140]
We would like to add a new event OnBeforeBinCalcQtyToPutAway in the following procedure:

    local procedure CalcQtyToPutAway(EmptyZoneBin: Boolean; NewBinContent: Boolean)
    var
        ActionType: Option ,Take,Place;
    begin
        if Location."Bin Mandatory" then begin
            ActionType := ActionType::Place;
            if not EmptyZoneBin and Location."Directed Put-away and Pick" then
                CalcAvailCubageAndWeight;
            OnBeforeBinCalcQtyToPutAway(Item, Location, QtyToPutAwayBase, RemQtyToPutAwayBase); //A200F0000.Event.n
            if QtyToPutAwayBase >= RemQtyToPutAwayBase then begin
                QtyToPutAwayBase := RemQtyToPutAwayBase;
                EverythingHandled := true;
            end else

Event signature

    [IntegrationEvent(false, false)]
    local procedure OnBeforeBinCalcQtyToPutAway(Item: Record Item; Location: Record Location; var QtyToPutAwayBase: Decimal; var RemQtyToPutAwayBase: Decimal)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
