### ISSUE TITLE
[Event Request] codeunit 5520 "Get Unplanned Demand" - OnBeforeInsertProdOrderComponent

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13148]
We would like to add a new event OnBeforeInsertProdOrderComponent in the following procedure:

    local procedure InsertProdOrderCompLine(var UnplannedDemand: Record "Unplanned Demand")
    var
        UnplannedDemand2: Record "Unplanned Demand";
        Item: Record Item;
    begin
        with UnplannedDemand do begin
            UnplannedDemand2.Copy(UnplannedDemand);
            InitRecord(
              ProdOrderComp."Prod. Order Line No.", ProdOrderComp."Line No.", ProdOrderComp."Item No.", ProdOrderComp.Description,
              ProdOrderComp."Variant Code", ProdOrderComp."Location Code", ProdOrderComp."Bin Code", ProdOrderComp."Unit of Measure Code",
              ProdOrderComp."Qty. per Unit of Measure", DemandQtyBase, ProdOrderComp."Due Date");
            Item.Get("Item No.");
            Reserve :=
              (Item.Reserve = Item.Reserve::Always) and
              not (("Demand Type" = "Demand Type"::Production) and
                   ("Demand SubType" = ProdOrderComp.Status::Planned.AsInteger()));
            OnBeforeInsertProdOrderComponent(UnplannedDemand, ProdOrderComp); //A200F0000.n
            Insert;
            Copy(UnplannedDemand2);
        end;

Event Signature

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertProdOrderComponent(var UnplannedDemand: Record "Unplanned Demand"; ProdOrderComponent: Record "Prod. Order Component")
    begin
        //A200F0000.event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
