### ISSUE TITLE
[Event Request] codeunit 5847 "Get Average Cost Calc Overview" - OnAfterCopyAvgCostAdjmtEntryPointToAvgCostCalcOverview

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13143]
We would like to add a new event OnAfterCopyAvgCostAdjmtEntryPointToAvgCostCalcOverview in the following trigger:
 
   trigger OnRun()
.
.
.
            repeat
                Init;
                Type := Type::"Closing Entry";
                "Entry No." := "Entry No." + 1;
                "Item No." := AvgCostAdjmtEntryPoint."Item No.";
                "Variant Code" := AvgCostAdjmtEntryPoint."Variant Code";
                "Location Code" := AvgCostAdjmtEntryPoint."Location Code";
                "Valuation Date" := AvgCostAdjmtEntryPoint."Valuation Date";
                OnAfterCopyAvgCostAdjmtEntryPointToAvgCostCalcOverview(Rec, AvgCostAdjmtEntryPoint); //A200F0002.Event
                "Attached to Valuation Date" := "Valuation Date";
                "Attached to Entry No." := "Entry No.";
                "Cost is Adjusted" := AvgCostAdjmtEntryPoint."Cost Is Adjusted";
                if EntriesExist(Rec) then begin
                    OnBeforeAvgCostAdjmtEntryPointInsert(Rec, AvgCostAdjmtEntryPoint);
                    Insert();
                end else
                    AvgCostAdjmtEntryPoint.Delete();
            until AvgCostAdjmtEntryPoint.Next() = 0;
    end;

Event signature

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyAvgCostAdjmtEntryPointToAvgCostCalcOverview(var AvgCostCalcOverview: Record "Average Cost Calc. Overview"; var AvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point")
    begin
        //A200F0002.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
