### ISSUE TITLE
[Event Request] codeunit 7153 "Item Analysis Management" - OnAfterFilterItemAnalysisViewEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13159]
We would like to add a new event OnAfterFilterItemAnalysisViewEntry in the following procedure:

    local procedure FilterItemAnalyViewEntry(var ItemStatisticsBuffer: Record "Item Statistics Buffer"; var ItemAnalysisViewEntry: Record "Item Analysis View Entry")
    begin
        with ItemStatisticsBuffer do begin
            CopyFilter("Analysis Area Filter", ItemAnalysisViewEntry."Analysis Area");
            CopyFilter("Analysis View Filter", ItemAnalysisViewEntry."Analysis View Code");

            if GetFilter("Item Filter") <> '' then
                CopyFilter("Item Filter", ItemAnalysisViewEntry."Item No.");

            if GetFilter("Date Filter") <> '' then
                CopyFilter("Date Filter", ItemAnalysisViewEntry."Posting Date");

            if GetFilter("Location Filter") <> '' then
                CopyFilter("Location Filter", ItemAnalysisViewEntry."Location Code");

            if GetFilter("Dimension 1 Filter") <> '' then
                CopyFilter("Dimension 1 Filter", ItemAnalysisViewEntry."Dimension 1 Value Code");

            if GetFilter("Dimension 2 Filter") <> '' then
                CopyFilter("Dimension 2 Filter", ItemAnalysisViewEntry."Dimension 2 Value Code");

            if GetFilter("Dimension 3 Filter") <> '' then
                CopyFilter("Dimension 3 Filter", ItemAnalysisViewEntry."Dimension 3 Value Code");
            0(ItemStatisticsBuffer, ItemAnalysisViewEntry); //A200F0010.Event
        end;

    Event Signature

    [IntegrationEvent(false, false)]
    local procedure OnAfterFilterItemAnalysisViewEntry(var ItemStatisticsBuffer: Record "Item Statistics Buffer"; var ItemAnalysisViewEntry: Record "Item Analysis View Entry")
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
