### ISSUE TITLE
[Event Request] codeunit 7153 "Item Analysis Management" - OnAfterSetLineAndColDim

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13158]
We would like to add a new event OnAfterSetLineAndColDim in the following procedure:

    procedure SetLineAndColDim(ItemAnalysisView: Record "Item Analysis View"; var LineDimCode: Text[30]; var LineDimOption: Option Item,Period,Location,"Dimension 1","Dimension 2","Dimension 3"; var ColumnDimCode: Text[30]; var ColumnDimOption: Option Item,Period,Location,"Dimension 1","Dimension 2","Dimension 3")
    var
        Item: Record Item;
    begin
        if (LineDimCode = '') and (ColumnDimCode = '') then begin
            LineDimCode := Item.TableCaption;
            ColumnDimCode := Text000;
        end;
        LineDimOption := DimCodeToOption(LineDimCode, ItemAnalysisView);
        ColumnDimOption := DimCodeToOption(ColumnDimCode, ItemAnalysisView);
        OnAfterSetLineAndColDim(ItemAnalysisView, LineDimCode, LineDimOption, ColumnDimCode, ColumnDimOption); //A200F0010.Event
    end;

    Event Signature

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetLineAndColDim(ItemAnalysisView: Record "Item Analysis View"; var LineDimCode: Text[30]; var LineDimOption: Option Item,Period,Location,"Dimension 1","Dimension 2","Dimension 3"; var ColumnDimCode: Text[30]; var ColumnDimOption: Option Item,Period,Location,"Dimension 1","Dimension 2","Dimension 3")
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
