### ISSUE TITLE
[Event Request] codeunit 99000854 "Inventory Profile Offsetting" - OnAfterNewRequisitionLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13154]
We would like to add a new event OnAfterNewRequisitionLine in the following procedure:

    local procedure MaintainPlanningLine(var SupplyInvtProfile: Record "Inventory Profile"; DemandInvtProfile: Record "Inventory Profile"; NewPhase: Option " ","Line Created","Routing Created",Exploded,Obsolete; Direction: Option Forward,Backward)
.
.
.
                        OnMaintainPlanningLineOnBeforeValidateNo(ReqLine, SupplyInvtProfile, TempSKU);
                        Validate("No.");
                        if "Production BOM No." = '' then //A108B0073.n
                            Validate("Unit of Measure Code", SupplyInvtProfile."Unit of Measure Code");
                        "Starting Time" := ManufacturingSetup."Normal Starting Time";
                        "Ending Time" := ManufacturingSetup."Normal Ending Time";
                        OnAfterNewRequisitionLine(ReqLine, SupplyInvtProfile, TempSKU); //A200F0000.Event
                    end else
                        case SupplyInvtProfile."Source Type" of
                            DATABASE::"Purchase Line":
                                SetPurchase(PurchaseLine, SupplyInvtProfile);
                            DATABASE::"Prod. Order Line":
                                SetProdOrder(ProdOrderLine, SupplyInvtProfile);
                            DATABASE::"Assembly Header":
                                SetAssembly(AsmHeader, SupplyInvtProfile);
                            DATABASE::"Transfer Line":
                                SetTransfer(TransLine, SupplyInvtProfile);
                        end;

   Event Signature

    [IntegrationEvent(false, false)]
    local procedure OnAfterNewRequisitionLine(var RequisitionLine: Record "Requisition Line"; InventoryProfile: Record "Inventory Profile"; StockkeepingUnit: Record "Stockkeeping Unit")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
