### ISSUE TITLE
[Event Request] codeunit 5520 "Get Unplanned Demand" - OnBeforeInsertJobPlanningLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13151]
We would like to add a new event OnBeforeInsertJobPlanningLine in the following procedure:

    local procedure InsertJobPlanningLine(var UnplannedDemand: Record "Unplanned Demand")
    var
        UnplannedDemand2: Record "Unplanned Demand";
    begin
        with UnplannedDemand do begin
            UnplannedDemand2.Copy(UnplannedDemand);
            InitRecord(
              JobPlanningLine."Job Contract Entry No.", 0, JobPlanningLine."No.", JobPlanningLine.Description, JobPlanningLine."Variant Code",
              JobPlanningLine."Location Code", JobPlanningLine."Bin Code", JobPlanningLine."Unit of Measure Code",
              JobPlanningLine."Qty. per Unit of Measure", DemandQtyBase, JobPlanningLine."Planning Date");
            Reserve := JobPlanningLine.Reserve = JobPlanningLine.Reserve::Always;
            OnBeforeInsertJobPlanningLine(UnplannedDemand, JobPlanningLine); //A200F0000.n
            Insert;
            Copy(UnplannedDemand2);
        end;

Event Signature

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertJobPlanningLine(var UnplannedDemand: Record "Unplanned Demand"; JobPlanningLine: Record "Job Planning Line")
    begin
        //A200F0000.event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
