### ISSUE TITLE
[Event Request] codeunit 99000854 "Inventory Profile Offsetting" - OnBeforeInsertReservationEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13157]
We would like to add a new event OnBeforeInsertReservationEntry in the following procedure:

    local procedure CommitTracking()
    var
        PrevTempEntryNo: Integer;
        PrevInsertedEntryNo: Integer;
    begin
        if not TempTrkgReservEntry.Find('-') then
            exit;

        repeat
            ReservEntry := TempTrkgReservEntry;
            if TempTrkgReservEntry."Entry No." = PrevTempEntryNo then
                ReservEntry."Entry No." := PrevInsertedEntryNo
            else
                ReservEntry."Entry No." := 0;
            ReservEntry.UpdateItemTracking;
            UpdateAppliedItemEntry(ReservEntry);
            OnBeforeInsertReservationEntry(ReservEntry, TempItemTrkgEntry); //A200F0000.Event
            ReservEntry.Insert();
            PrevTempEntryNo := TempTrkgReservEntry."Entry No.";
            PrevInsertedEntryNo := ReservEntry."Entry No.";
            TempTrkgReservEntry.Delete();
        until TempTrkgReservEntry.Next() = 0;
        Clear(TempTrkgReservEntry);
    end;

    Event Signature

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertReservationEntry(var ReservationEntry: Record "Reservation Entry"; var TempItemTrkgEntry: Record "Reservation Entry")
    begin
        //A200F0000.Event
    end;

**Comment by Stepanenko-Vadim** [comment]
The event will be added to the end of **UpdateAppliedItemEntry** instead of that spot
