### ISSUE TITLE
[Event Request] codeunit 5520 "Get Unplanned Demand" - OnBeforeInsertServiceLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13150]
We would like to add a new event OnBeforeInsertServiceLine in the following procedure:

    local procedure InsertServLine(var UnplannedDemand: Record "Unplanned Demand")
    var
        UnplannedDemand2: Record "Unplanned Demand";
    begin
        with UnplannedDemand do begin
            UnplannedDemand2.Copy(UnplannedDemand);
            InitRecord(
              ServLine."Line No.", 0, ServLine."No.", ServLine.Description, ServLine."Variant Code", ServLine."Location Code",
              ServLine."Bin Code", ServLine."Unit of Measure Code", ServLine."Qty. per Unit of Measure",
              DemandQtyBase, ServLine."Needed by Date");
            Reserve := ServLine.Reserve = ServLine.Reserve::Always;
            OnBeforeInsertServiceLine(UnplannedDemand, ServLine); //A200F0000.n
            Insert;
            Copy(UnplannedDemand2);
        end;

Event Signature

 [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertServiceLine(var UnplannedDemand: Record "Unplanned Demand"; ServiceLine: Record "Service Line")
    begin
        //A200F0000.event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
