### ISSUE TITLE
[Event Request] Page 605 - IC Chart of Accounts - procedure CopyFromChartOfAccounts

### ISSUE THREAD

**Issue by mrabus** [microsoft/ALAppExtensions#13168]
Event Signature: 
[IntegrationEvent(false,false)]
local procedure OnBeforeInsertICGLAccFromGLAcc(var ICGLAcc: Record "IC G/L Account"; GLAcc: Record "G/L Account")
begin
end;

Event Placement:
    local procedure CopyFromChartOfAccounts()
    var
        GLAcc: Record "G/L Account";
        ICGLAcc: Record "IC G/L Account";
        ConfirmManagement: Codeunit "Confirm Management";
        ChartofAcc: Page "Chart of Accounts";
        ICGLAccEmpty: Boolean;
        ICGLAccExists: Boolean;
        PrevIndentation: Integer;
    begin
        if not ConfirmManagement.GetResponseOrDefault(StrSubstNo(Text004, ChartofAcc.Caption), true) then
            exit;

        ICGLAccEmpty := not ICGLAcc.FindFirst;
        ICGLAcc.LockTable();
        if GLAcc.Find('-') then
            repeat
                if GLAcc."Account Type" = GLAcc."Account Type"::"End-Total" then
                    PrevIndentation := PrevIndentation - 1;
                if not ICGLAccEmpty then
                    ICGLAccExists := ICGLAcc.Get(GLAcc."No.");
                if not ICGLAccExists and not GLAcc.Blocked then begin
                    ICGLAcc.Init();
                    ICGLAcc."No." := GLAcc."No.";
                    ICGLAcc.Name := GLAcc.Name;
                    ICGLAcc."Account Type" := GLAcc."Account Type";
                    ICGLAcc."Income/Balance" := GLAcc."Income/Balance";
                    ICGLAcc.Validate(Indentation, PrevIndentation);
                    OnBeforeInsertICGLAccFromGLAcc(ICGLAcc, GLAcc); //new event 
                    ICGLAcc.Insert();
                end;
                PrevIndentation := GLAcc.Indentation;
                if GLAcc."Account Type" = GLAcc."Account Type"::"Begin-Total" then
                    PrevIndentation := PrevIndentation + 1;
            until GLAcc.Next() = 0;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
