### ISSUE TITLE
Expose UpdatePostedTotalCost procedure in report 1095 "Update Job Item Cost"

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#13163]
Please remove the local qualifier from the `UpdatePostedTotalCost` procedure in the `"Update Job Item Cost"` Report so it can be used from outside the report.

```
-    local procedure UpdatePostedTotalCost(var JobLedgerEntry: Record "Job Ledger Entry"; AdjustJobCost: Decimal; AdjustJobCostLCY: Decimal)
+    procedure UpdatePostedTotalCost(var JobLedgerEntry: Record "Job Ledger Entry"; AdjustJobCost: Decimal; AdjustJobCostLCY: Decimal)

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
