### ISSUE TITLE
Data Exchange Field Mapping Bug

### ISSUE THREAD

**Issue by jmezquita2** [microsoft/ALAppExtensions#13170]
Hi, I've noticed a little Bug in Data Exchange Field Mapping.

If you go to a Data Exchange definition Card and use the action "Field Mapping".

![image](https://user-images.githubusercontent.com/72610992/125257836-106bc180-e2fe-11eb-8544-d624dc5687ef.png)

If you mark the boolean "Use as Intermediate Table" and you try yo map a field with a large caption it throws an error (for example the field 93 from table 37).

![image](https://user-images.githubusercontent.com/72610992/125258241-73f5ef00-e2fe-11eb-9d5b-83b7ab37c818.png)

It could be a mess with the table relation and the field length.

Thanks.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
