### ISSUE TITLE
[Enum Request] Table 9650 - Custom Report Layout - Field 6 "Type"

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#1317]
Dear ALAppExtensions team,

Through this issue we would like to request to have the _Option_ field "Type" in the Custom Report Layout table changed into an **_Extensible_ Enum**.
This would allow extensions to add support for layout types other than the built-in RDLC and Word types.
Of course this would (at least) require the procedures in this table to be extended with new event publishers which can be used to handle any new layout types that are added through extensions.

I hope you have sufficient information for this request, but if you need any more info, please let us know.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
