### ISSUE TITLE
[Event Request]: OnBeforeTrackingAvailable codeunit 6501 "Item Tracking Data Collection" missing parameter

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/ALAppExtensions#13171]
the actual code there it is not possible to set the result, i can handle the function and exit it, but it will always exit with false.

 procedure TrackingAvailable(TempTrackingSpecification: Record "Tracking Specification" temporary; LookupMode: Enum "Item Tracking Type"): Boolean

before
```
IsHandled := false;
OnBeforeTrackingAvailable(TempTrackingSpecification, IsHandled);
if IsHandled then
    exit(Result);
```
after
```
IsHandled := false;
OnBeforeTrackingAvailable(TempTrackingSpecification, IsHandled, Result);
if IsHandled then
    exit(Result);
```

before
```
[IntegrationEvent(false, false)]
local procedure OnBeforeTrackingAvailable(var TempTrackingSpecification: Record "Tracking Specification"; var IsHandled: Boolean);
    begin
    end;
```
after
```
[IntegrationEvent(false, false)]
local procedure OnBeforeTrackingAvailable(var TempTrackingSpecification: Record "Tracking Specification"; var IsHandled: Boolean; var Result: Boolean);
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
