### ISSUE TITLE
[Access Request] Table 39 "Purchase Line" - Global variables

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#13172]
We would like to access these variables from a tableextension for Purchase Line. Can they be placed under protected var?

* PurchHeader
* Currency

The reason is that it is possible to call GetPurchHeader, but the updated global variables can't be accessed. So we always need to use local variables instead, which makes it inefficient.

**Comment by CameliaPopescu** [comment]
Version to implement >= 18.2

**Comment by AlexanderYakunin** [comment]
Please use procedure GetPurchHeader(var OutPurchHeader: Record "Purchase Header"; var OutCurrency: Record Currency) instead.
