### ISSUE TITLE
[Event Request] OnBeforePrintRecords in Table 5746 "Transfer Receipt Header"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#13173]
In Table 5746 "Transfer Receipt Header" we need the same event trigger OnBeforePrintRecords  as in table 5744 "Transfer Shipment Header":

    procedure PrintRecords(ShowRequestForm: Boolean)
    var
        ReportSelection: Record "Report Selections";
       TransRcptHeader: Record "Transfer Receipt Header";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePrintRecords(Rec, ShowRequestForm, IsHandled);
        if IsHandled then
            exit;

        with TransRcptHeader do begin
            Copy(Rec);
            ReportSelection.PrintWithDialogForCust(
                ReportSelection.Usage::Inv3, TransRcptHeader, ShowRequestForm, 0);
        end;
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
