### ISSUE TITLE
GetCallerModuleInfo ->  Cloud development

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#13177]
Hi,

i found the GetCallerModuleInfo function, wich is exactly what i need.
Unfortunately the function is not allowed for Cloud development. Is it possible to have it opened to cloud development. 
It is the perfekt fix for my problem

kind regards,
Lennart

**Comment by AlexanderYakunin** [comment]
@JesperSchulz - ask for SystemApp

**Comment by jehelles** [comment]
GetCallerModuleInfo has been opened up for Cloud development from runtime 8.0 (2021 Wave 2)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
