### ISSUE TITLE
[Extensibility Enhancements] Table 39 Purchase Line, procedure GetPurchHeader

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#13174]
There is the procedure GetPurchHeader in Purchase Line table with two parameters:
`procedure GetPurchHeader(var OutPurchHeader: Record "Purchase Header"; OutCurrency: Record Currency)`
OutCurrency variable is not accessible from outside because ByRef keyword (var) is missing.
(version 18.3)

**Comment by CameliaPopescu** [comment]
Version to implement >= 18.2

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
