### ISSUE TITLE
[Extensibility Enhancements] OnInit Trigger of Request Page on Report 1305 "Standard Sales - Order Conf."

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#13176]
OnInit Trigger of RequestPage is not reachable in ReportExtension. We added parameter and there is no way where we can set default value of Field UploadToSharePoint to true

reportextension 50250 "DBH StandardSalesOrderConf" extends "Standard Sales - Order Conf."
{
    requestpage
    {
        layout
        {
            addlast(content)
            {
                group(DBH)
                {
                    Caption = 'DBH', Comment = 'DBH';
                    field(UploadToSharepointField; UploadToSharepoint)
                    {
                        Caption = 'Upload to Sharepoint';
                        ApplicationArea = Basic, Suite;
                    }
                }
            }
        }
    }

**Comment by AlexanderYakunin** [comment]
Please specify what do you need, probably event?

**Comment by OlgicaA** [comment]
Hi Alexander,

Yes correct we need OnInit trigger of Request page to be reachable from ReportExtension (this will solve all reports at once)
or second posibility is:
We need one Event OnInit trigger where we can subscribe (this should be done than per report, and we have more to come)

**Comment by OlgicaA** [comment]
BEFORE
        trigger OnInit()
        begin
            LogInteractionEnable := true;
            ArchiveDocument := SalesSetup."Archive Orders";
        end;
AFTER
        trigger OnInit()
        begin
            LogInteractionEnable := true;
            ArchiveDocument := SalesSetup."Archive Orders";
	    OnInitRequestPage("Sales Header");
        end;

    [IntegrationEvent(false, false)]
    local procedure OnInitRequestPage(var SalesHeader: Record "Sales Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by db-bc** [comment]
> We added parameter and there is no way where we can set default value of Field UploadToSharePoint to true

Can't you just use `requestpage` => `trigger OnOpenPage()` ?

**Comment by OlgicaA** [comment]
NO! we cannot, it is the same issue like with OnInitPage - it is not reachable outside of report
![image](https://user-images.githubusercontent.com/86241544/127145569-099953be-a03b-40ba-b928-843e0b93fafe.png)

**Comment by db-bc** [comment]
but if you are creating a report extension, in which that new variable/control is declared, you can in the same extension AL object add `trigger onOpenPage()` within the `requestpage` block, and access/set said variable/control

**Comment by OlgicaA** [comment]
![image](https://user-images.githubusercontent.com/86241544/127146998-90087c61-74d8-405c-a506-4617bacd6e4f.png)
Thank you very much for the tip! It works with OnOpenPage() 
OnInit() is not reachable and the name is OnInit() not OnInitPage()
![image](https://user-images.githubusercontent.com/86241544/127147146-f12c62dc-dd9f-43ef-88f8-535381b1210a.png)
