### ISSUE TITLE
[Event Request] codeunit 7153 "Item Analysis Management" - OnAfterSetCommonFilters

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13186]
We would like to add a new event OnAfterSetCommonFilters in the following procedure:

    procedure SetCommonFilters(CurrentAnalysisArea: Option; var ItemStatisticsBuffer: Record "Item Statistics Buffer"; CurrentAnalysisViewCode: Code[10]; ItemFilter: Text; LocationFilter: Text; DateFilter: Text; Dim1Filter: Text; Dim2Filter: Text; Dim3Filter: Text; BudgetFilter: Text)
    begin
        with ItemStatisticsBuffer do begin
            Reset;
            SetRange("Analysis Area Filter", CurrentAnalysisArea);
            SetRange("Analysis View Filter", CurrentAnalysisViewCode);

            if ItemFilter <> '' then
                SetFilter("Item Filter", ItemFilter);
            if LocationFilter <> '' then
                SetFilter("Location Filter", LocationFilter);
            if DateFilter <> '' then
                SetFilter("Date Filter", DateFilter);
            if Dim1Filter <> '' then
                SetFilter("Dimension 1 Filter", Dim1Filter);
            if Dim2Filter <> '' then
                SetFilter("Dimension 2 Filter", Dim2Filter);
            if Dim3Filter <> '' then
                SetFilter("Dimension 3 Filter", Dim3Filter);
            if BudgetFilter <> '' then
                SetFilter("Budget Filter", BudgetFilter);
        end;
        OnAfterSetCommonFilters(CurrentAnalysisArea, ItemStatisticsBuffer); //A200F0010.Event
    end;

Event Signature

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetCommonFilters(CurrentAnalysisArea: Option Sales,Purchase,Inventory; var ItemStatisticsBuffer: Record "Item Statistics Buffer")
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
