### ISSUE TITLE
[Event Request] codeunit 7153 "Item Analysis Management" - OnBeforeDimCodeToOption

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13188]
We would like to add a new event OnBeforeDimCodeToOption in the following procedure:

    local procedure DimCodeToOption(DimCode: Text[30]; ItemAnalysisView: Record "Item Analysis View"): Integer
    var
        Location: Record Location;
        Item: Record Item;
        OptionValue: Integer;
    begin
        //A200F0010.Event.ns
        OnBeforeDimCodeToOption(DimCode, ItemAnalysisView, OptionValue);
        if OptionValue > 0 then
            exit(OptionValue);
        //A200F0010.Event.ne
        case DimCode of
            Item.TableCaption:
                exit(0);
            Text000:
                exit(1);
            Location.TableCaption:
                exit(2);
            ItemAnalysisView."Dimension 1 Code":
                exit(3);
            ItemAnalysisView."Dimension 2 Code":
                exit(4);
            ItemAnalysisView."Dimension 3 Code":
                exit(5);
            else
                exit(-1);
        end;

Event Signature

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDimCodeToOption(DimCode: Text[30]; ItemAnalysisView: Record "Item Analysis View"; var OptionValue: Integer)
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
