### ISSUE TITLE
Remove deletion of Job Queue Entries inside Codeunit 448 JobQueueDispatcher Function WaitForOthersWithSameCategory Line #106

### ISSUE THREAD

**Issue by nicdiblasiFS** [microsoft/ALAppExtensions#13185]
Hi, 
17.6 introduced new functionality that deletes Job Queue Entries that are in process in the same JQ Category if the system can't find a related Task Process - this is causing JQEs to be deleted incorrectly. Please revert back to version 17.4 for function WaitForOthersWithSameCategory. 

![image](https://user-images.githubusercontent.com/87403142/125553250-36588d25-006d-49e6-bdbd-be12088a778e.png)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
