### ISSUE TITLE
[Event Request] codeunit 7153 "Item Analysis Management" - OnBeforeDimCodeNotAllowed

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13189]
We would like to add a new event OnBeforeDimCodeNotAllowed in the following procedure:

    local procedure DimCodeNotAllowed(DimCode: Text[30]; ItemAnalysisView: Record "Item Analysis View"): Boolean
    var
        Item: Record Item;
        Location: Record Location;
        DimCodeAllowed: Boolean;
        IsHandled: Boolean;
    begin
        //A200F0010.Event.ns
        OnBeforeDimCodeNotAllowed(DimCode, ItemAnalysisView, DimCodeAllowed, IsHandled);
        if IsHandled then
            exit(Not DimCodeAllowed);
        //A200F0010.Event.ne
        exit(
          not (UpperCase(DimCode) in
               [UpperCase(Item.TableCaption),
                UpperCase(Location.TableCaption),
                UpperCase(Text000),
                ItemAnalysisView."Dimension 1 Code",
                ItemAnalysisView."Dimension 2 Code",
                ItemAnalysisView."Dimension 3 Code",
                '']));
    end;

Event Signature

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDimCodeNotAllowed(DimCode: Text[30]; ItemAnalysisView: Record "Item Analysis View"; var DimCodeAllowed: Boolean; var IsHandled: Boolean)
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
