### ISSUE TITLE
[Event Request] codeunit 7153 "Item Analysis Management" - OnInsertDimensionSelectionBuffer

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13190]
We would like to add a new event OnInsertDimensionSelectionBuffer in the following procedure:

    procedure GetDimSelection(OldDimSelCode: Text[30]; var ItemAnalysisView: Record "Item Analysis View"): Text[30]
    var
        Item: Record Item;
        Location: Record Location;
        DimSelection: Page "Dimension Selection";
    begin
        DimSelection.InsertDimSelBuf(false, Item.TableCaption, Item.TableCaption);
        DimSelection.InsertDimSelBuf(false, Location.TableCaption, Location.TableCaption);
        DimSelection.InsertDimSelBuf(false, Text000, Text000);
        if ItemAnalysisView."Dimension 1 Code" <> '' then
            DimSelection.InsertDimSelBuf(false, ItemAnalysisView."Dimension 1 Code", '');
        if ItemAnalysisView."Dimension 2 Code" <> '' then
            DimSelection.InsertDimSelBuf(false, ItemAnalysisView."Dimension 2 Code", '');
        if ItemAnalysisView."Dimension 3 Code" <> '' then
            DimSelection.InsertDimSelBuf(false, ItemAnalysisView."Dimension 3 Code", '');
        OnInsertDimensionSelectionBuffer(DimSelection, ItemAnalysisView); //A200F0010.Event

        DimSelection.LookupMode := true;
        if DimSelection.RunModal = ACTION::LookupOK then
            exit(DimSelection.GetDimSelCode);
        exit(OldDimSelCode);
    end;

Event Signature

    [IntegrationEvent(false, false)]
    local procedure OnInsertDimensionSelectionBuffer(var DimensionSelection: Page "Dimension Selection"; var ItemAnalysisView: Record "Item Analysis View")
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
