### ISSUE TITLE
[Event Request] codeunit 244 "Item Jnl.-B.Post+Print" - OnAfterGetItemRegister

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13194]
We would like to add a new event OnAfterGetItemRegister in the following procedure:
    local procedure "Code"()
    var
        HideDialog: Boolean;
        PrintPostingReport: Boolean;
        PrintWarehouseseRegisterReport: Boolean;
    begin
        with ItemJnlBatch do begin
            ItemJnlTemplate.Get("Journal Template Name");
            ItemJnlTemplate.TestField("Posting Report ID");

            HideDialog := false;
            OnBeforePostJournalBatch(ItemJnlBatch, HideDialog);
            if not HideDialog then
                if not Confirm(Text000, false) then
                    exit;

            Find('-');
            repeat
                ItemJnlLine."Journal Template Name" := "Journal Template Name";
                ItemJnlLine."Journal Batch Name" := Name;
                ItemJnlLine."Line No." := 1;
                Clear(ItemJnlPostBatch);
                if ItemJnlPostBatch.Run(ItemJnlLine) then begin
                    OnAfterPostJournalBatch(ItemJnlBatch);
                    Mark(false);
                    if ItemReg.Get(ItemJnlPostBatch.GetItemRegNo) then begin
                        ItemReg.SetRecFilter;
                        //A200F0000.Event.ns
                        PrintPostingReport := true;
                        OnAfterGetItemRegister(ItemReg, ItemJnlTemplate, PrintPostingReport);
                        if PrintPostingReport then
                            //A200F0000.Event.ne
                        REPORT.Run(ItemJnlTemplate."Posting Report ID", false, false, ItemReg);
                    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetItemRegister(ItemRegister: Record "Item Register"; ItemJournalTemplate: Record "Item Journal Template"; var PrintPostingReport: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
