### ISSUE TITLE
[Event Request] codeunit 7153 "Item Analysis Management" - OnElseNextRec

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13192]
We would like to add a new event OnElseNextRec in the following procedure:

    procedure NextRec(var ItemAnalysisView: Record "Item Analysis View"; DimOption: Option Item,Period,Location,"Dimension 1","Dimension 2","Dimension 3"; var DimCodeBuf: Record "Dimension Code Buffer"; Steps: Integer; ItemFilter: Code[250]; LocationFilter: Code[250]; PeriodType: Option Day,Week,Month,Quarter,Year,"Accounting Period"; DateFilter: Text[30]; Dim1Filter: Code[250]; Dim2Filter: Code[250]; Dim3Filter: Code[250]): Integer
.
.
.
            DimOption::"Dimension 3":
                begin
                    if Dim3Filter <> '' then
                        DimVal.SetFilter(Code, Dim3Filter);
                    DimVal."Dimension Code" := ItemAnalysisView."Dimension 3 Code";
                    DimVal.SetRange("Dimension Code", DimVal."Dimension Code");
                    DimVal.Code := DimCodeBuf.Code;
                    ResultSteps := DimVal.Next(Steps);
                    if ResultSteps <> 0 then
                        CopyDimValueToBuf(DimVal, DimCodeBuf);
                end;
            else
                OnElseNextRec(ItemAnalysisView, DimOption, DimCodeBuf, Steps, ItemFilter, ResultSteps); //A200F0010.Event
        end;
        exit(ResultSteps);
    end;

Event Signature

    [IntegrationEvent(false, false)]
    local procedure OnElseNextRec(var ItemAnalysisView: Record "Item Analysis View"; DimOption: Option; var DimCodeBuf: Record "Dimension Code Buffer"; Steps: Integer; ItemFilter: Text; var ResultSteps: Integer)
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
