### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" - OnBeforeSplitFlushedConsumptionItemJournalLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13197]
We would like to add a new event OnBeforeSplitFlushedConsumptionItemJournalLine in the following procedure:

    procedure PostFlushedConsump(ProdOrder: Record "Production Order"; ProdOrderLine: Record "Prod. Order Line"; ProdOrderComp: Record "Prod. Order Component"; var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; OldItemJnlLine: Record "Item Journal Line")
.
.
.
            PrepareItem(ItemJnlLine);
            TrackingSpecExists := ItemTrackingMgt.RetrieveItemTracking(ItemJnlLine, TempTrackingSpecification);
            OnBeforeSplitFlushedConsumptionItemJournalLine(ItemJnlLine); //A200F0000.Event
            PostItemJnlLine := SetupSplitJnlLine(ItemJnlLine, TrackingSpecExists);

            while SplitItemJnlLine(ItemJnlLine, PostItemJnlLine) do begin
                ItemJnlLine.CheckTrackingIfRequiredNotBlank(GlobalItemTrackingSetup);

                if not DimsAreTaken then begin
                    "Dimension Set ID" := GetCombinedDimSetID(ProdOrderLine."Dimension Set ID", ProdOrderComp."Dimension Set ID");
                    DimsAreTaken := true;
                end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSplitFlushedConsumptionItemJournalLine(var ItemJournalLine: Record "Item Journal Line")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
