### ISSUE TITLE
[Event Request] codeunit 99000835 "Item Jnl. Line-Reserve" - OnBeforeCallItemTracking

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13196]
We would like to add a new event OnBeforeCallItemTracking in the following procedure:

    procedure Block(SetBlocked: Boolean)
    begin
        Blocked := SetBlocked;
    end;

    procedure CallItemTracking(var ItemJnlLine: Record "Item Journal Line"; IsReclass: Boolean)
    var
        TrackingSpecification: Record "Tracking Specification";
        ReservEntry: Record "Reservation Entry";
        ItemTrackingLines: Page "Item Tracking Lines";
        IsHandled: Boolean;
    begin
        //A200F0000.Event.ns
        OnBeforeCallItemTracking(ItemJnlLine, IsReclass, IsHandled);
        if IsHandled then
            exit;
        //A200F0000.Event.ne
        ItemJnlLine.TestField("Item No.");
        if not ItemJnlLine.ItemPosting then begin
            ReservEntry.InitSortingAndFilters(false);
            ItemJnlLine.SetReservationFilters(ReservEntry);
            ReservEntry.ClearTrackingFilter;
            if ReservEntry.IsEmpty() then
                Error(Text006, ItemJnlLine.FieldCaption("Operation No."), ItemJnlLine."Operation No.");
        end;
        TrackingSpecification.InitFromItemJnlLine(ItemJnlLine);
        if IsReclass then
            ItemTrackingLines.SetFormRunMode(1);
        ItemTrackingLines.SetSourceSpec(TrackingSpecification, ItemJnlLine."Posting Date");
        ItemTrackingLines.SetInbound(ItemJnlLine.IsInbound);
        OnCallItemTrackingOnBeforeItemTrackingLinesRunModal(ItemJnlLine, ItemTrackingLines);
        ItemTrackingLines.RunModal();
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCallItemTracking(var ItemJournalLine: Record "Item Journal Line"; IsReclass: Boolean; IsHandled: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
