### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" - OnAfterCheckItemTrackingOfComp

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13198]
We would like to add a new event OnAfterCheckItemTrackingOfComp in the following procedure:

    local procedure CheckItemTrackingOfComp(TempHandlingSpecification: Record "Tracking Specification"; ItemJnlLine: Record "Item Journal Line")
    var
        ItemTrackingSetup2: Record "Item Tracking Setup";
    begin
        ItemTrackingSetup2 := GlobalItemTrackingSetup;
        ItemTrackingSetup2.CopyTrackingFromTrackingSpec(TempHandlingSpecification);
        ItemJnlLine.CheckTrackingIfRequired(ItemTrackingSetup2);
        OnAfterCheckItemTrackingOfComp(TempHandlingSpecification, ItemJnlLine); //A201F0000.Event.n
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckItemTrackingOfComp(TempHandlingSpecification: Record "Tracking Specification"; ItemJnlLine: Record "Item Journal Line")
    begin
        //A201F0000.Event.n
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
