### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" - OnAfterRetrieveItemTrackingOnRunWithCheck

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13199]
We would like to add a new event OnAfterRetrieveItemTrackingOnRunWithCheck in the following procedure:

    procedure RunWithCheck(var ItemJnlLine2: Record "Item Journal Line"): Boolean
    var
        TrackingSpecExists: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeRunWithCheck(
          ItemJnlLine2, CalledFromAdjustment, CalledFromInvtPutawayPick, CalledFromApplicationWorksheet,
          PostponeReservationHandling, IsHandled);
        if IsHandled then
            exit;

        PrepareItem(ItemJnlLine2);
        TrackingSpecExists := ItemTrackingMgt.RetrieveItemTracking(ItemJnlLine2, TempTrackingSpecification);
        OnAfterRetrieveItemTrackingOnRunWithCheck(ItemJnlLine2, TempTrackingSpecification, TrackingSpecExists, PostponeReservationHandling); //A200F0000.Event
        exit(PostSplitJnlLine(ItemJnlLine2, TrackingSpecExists));
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterRetrieveItemTrackingOnRunWithCheck(var ItemJournalLine: Record "Item Journal Line"; var TempTrackingSpecification: Record "Tracking Specification"; var TrackingSpecExists: Boolean; PostponeReservationHandling: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
