### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnAfterCalcWhseItemTrkgLineToPutAwayAndPick

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13208]
We would like to add a new event OnAfterCalcWhseItemTrkgLineToPutAwayAndPick in the following procedure:

    procedure CalcWhseItemTrkgLine(var WhseItemTrkgLine: Record "Whse. Item Tracking Line")
    var
        WhseActivQtyBase: Decimal;
    begin
        case WhseItemTrkgLine."Source Type" of
            DATABASE::"Posted Whse. Receipt Line":
                WhseItemTrkgLine."Source Type Filter" := WhseItemTrkgLine."Source Type Filter"::Receipt;
            DATABASE::"Whse. Internal Put-away Line":
                WhseItemTrkgLine."Source Type Filter" := WhseItemTrkgLine."Source Type Filter"::"Internal Put-away";
            DATABASE::"Warehouse Shipment Line":
                WhseItemTrkgLine."Source Type Filter" := WhseItemTrkgLine."Source Type Filter"::Shipment;
            DATABASE::"Whse. Internal Pick Line":
                WhseItemTrkgLine."Source Type Filter" := WhseItemTrkgLine."Source Type Filter"::"Internal Pick";
            DATABASE::"Prod. Order Component":
                WhseItemTrkgLine."Source Type Filter" := WhseItemTrkgLine."Source Type Filter"::Production;
            DATABASE::"Assembly Line":
                WhseItemTrkgLine."Source Type Filter" := WhseItemTrkgLine."Source Type Filter"::Assembly;
            DATABASE::"Whse. Worksheet Line":
                WhseItemTrkgLine."Source Type Filter" := WhseItemTrkgLine."Source Type Filter"::"Movement Worksheet";
        end;
        WhseItemTrkgLine.CalcFields("Put-away Qty. (Base)", "Pick Qty. (Base)");
        OnAfterCalcWhseItemTrkgLineToPutAwayAndPick(WhseItemTrkgLine); //A200F0000.Event

        if WhseItemTrkgLine."Put-away Qty. (Base)" > 0 then
            WhseActivQtyBase := WhseItemTrkgLine."Put-away Qty. (Base)";
        if WhseItemTrkgLine."Pick Qty. (Base)" > 0 then
            WhseActivQtyBase := WhseItemTrkgLine."Pick Qty. (Base)";

        if not Registering then
            WhseItemTrkgLine.Validate("Quantity Handled (Base)",
              WhseActivQtyBase + WhseItemTrkgLine."Qty. Registered (Base)")
        else
            WhseItemTrkgLine.Validate("Quantity Handled (Base)",
              WhseItemTrkgLine."Qty. Registered (Base)");

        if WhseItemTrkgLine."Quantity (Base)" >= WhseItemTrkgLine."Quantity Handled (Base)" then
            WhseItemTrkgLine.Validate("Qty. to Handle (Base)",
              WhseItemTrkgLine."Quantity (Base)" - WhseItemTrkgLine."Quantity Handled (Base)");
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcWhseItemTrkgLineToPutAwayAndPick(var WhseItemTrkgLine: Record "Whse. Item Tracking Line")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
