### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnAfterCopyItemLedgerEntryTrkgToSalesLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13207]
We would like to add a new event OnAfterCopyItemLedgerEntryTrkgToSalesLine in the following procedure: 

    procedure CopyItemLedgEntryTrkgToSalesLn(var TempItemLedgEntryBuf: Record "Item Ledger Entry" temporary; ToSalesLine: Record "Sales Line"; FillExactCostRevLink: Boolean; var MissingExCostRevLink: Boolean; FromPricesInclVAT: Boolean; ToPricesInclVAT: Boolean; FromShptOrRcpt: Boolean)
.
.
.
                if FillExactCostRevLink and not MissingExCostRevLink then begin
                    ToSalesLine.Validate(
                      "Unit Cost (LCY)", Abs(TotalCostLCY / ItemLedgEntryQty) * ToSalesLine."Qty. per Unit of Measure");
                    if not FromShptOrRcpt then
                        CopyDocMgt.CalculateRevSalesLineAmount(ToSalesLine, ItemLedgEntryQty, FromPricesInclVAT, ToPricesInclVAT);
                    OnAfterCopyItemLedgerEntryTrkgToSalesLine(ToSalesLine, TempItemLedgEntryBuf); //A200F0000.Event
                    ToSalesLine.Modify();
                end;
            end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyItemLedgerEntryTrkgToSalesLine(var SalesLine: Record "Sales Line"; var ItemLedgerEntryBuffer: Record "Item Ledger Entry" temporary)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
