### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" - OnBeforeTransferReservationEntriesFromJobPlanningLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13200]
We would like to add a new event OnBeforeTransferReservationEntriesFromJobPlanningLine in the following procedure:

    procedure PostItem()
.
.
.
            then begin
                AverageTransfer := true;
                TotalAppliedQty := 0;
            end else
                AverageTransfer := false;

            //A200F0000.Event.ns
            IsHandled := false;
            OnBeforeTransferReservationEntriesFromJobPlanningLine(ItemJnlLine, IsHandled);
            if not IsHandled then
                //A200F0000.Event.ne
                if "Job Contract Entry No." <> 0 then
                    TransReserveFromJobPlanningLine("Job Contract Entry No.", ItemJnlLine);

            if Item."Costing Method" = Item."Costing Method"::Standard then begin
                "Overhead Rate" := Item."Overhead Rate";
                "Indirect Cost %" := Item."Indirect Cost %";
            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferReservationEntriesFromJobPlanningLine(var ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
