### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnAfterDeleteReservationEntriesOnRetrievedTracingSpecifications

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13213]
We would like to add a new event OnAfterDeleteReservationEntriesOnRetrievedTracingSpecifications in the following 2 procedures:

    procedure RetrieveItemTrackingFromReservEntry(ItemJnlLine: Record "Item Journal Line"; var ReservEntry: Record "Reservation Entry"; var TempTrackingSpec: Record "Tracking Specification" temporary): Boolean
    begin
        if ItemJnlLine.Subcontracting then
            exit(RetrieveSubcontrItemTracking(ItemJnlLine, TempTrackingSpec));

        ReservEntry.SetSourceFilter(
          DATABASE::"Item Journal Line", ItemJnlLine."Entry Type".AsInteger(), ItemJnlLine."Journal Template Name", ItemJnlLine."Line No.", true);
        ReservEntry.SetSourceFilter(ItemJnlLine."Journal Batch Name", 0);
        OnAfterReserveEntryFilter(ItemJnlLine, ReservEntry);
        ReservEntry.SetFilter("Qty. to Handle (Base)", '<>0');
        OnRetrieveItemTrackingFromReservEntryFilter(ReservEntry, ItemJnlLine);
        if SumUpItemTracking(ReservEntry, TempTrackingSpec, false, true) then begin
            ReservEntry.SetRange("Reservation Status", ReservEntry."Reservation Status"::Prospect);
            ReservEntry.SetRange("Qty. to Handle (Base)"); //A108B0012.n
            if not ReservEntry.IsEmpty() then
                ReservEntry.DeleteAll();
            OnAfterDeleteReservationEntriesOnRetrievedTracingSpecifications(TempTrackingSpec); //A200F0000.Event
            exit(true);
        end;
        exit(false);
    end;

and:
    local procedure RetrieveSubcontrItemTracking(ItemJnlLine: Record "Item Journal Line"; var TempHandlingSpecification: Record "Tracking Specification" temporary) Result: Boolean
    var
        ReservEntry: Record "Reservation Entry";
        ProdOrderRoutingLine: Record "Prod. Order Routing Line";
        IsLastOperation: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeRetrieveSubcontrItemTracking(ItemJnlLine, TempHandlingSpecification, Result, IsHandled);
        if IsHandled then
            exit(Result);

        if not ItemJnlLine.Subcontracting then
            exit(false);

        if ItemJnlLine."Operation No." = '' then
            exit(false);

        ItemJnlLine.TestField("Routing No.");
        ItemJnlLine.TestField("Order Type", ItemJnlLine."Order Type"::Production);
        if not ProdOrderRoutingLine.Get(
             ProdOrderRoutingLine.Status::Released, ItemJnlLine."Order No.",
             ItemJnlLine."Routing Reference No.", ItemJnlLine."Routing No.", ItemJnlLine."Operation No.")
        then
            exit(false);

        IsLastOperation := ProdOrderRoutingLine."Next Operation No." = '';
        OnRetrieveSubcontrItemTrackingOnBeforeCheckLastOperation(ProdOrderRoutingLine, IsLastOperation);
        if not IsLastOperation then
            exit(false);

        ReservEntry.SetSourceFilter(DATABASE::"Prod. Order Line", 3, ItemJnlLine."Order No.", 0, true);
        ReservEntry.SetSourceFilter('', ItemJnlLine."Order Line No.");
        ReservEntry.SetFilter("Qty. to Handle (Base)", '<>0');
        if SumUpItemTracking(ReservEntry, TempHandlingSpecification, false, true) then begin
            ReservEntry.SetRange("Reservation Status", ReservEntry."Reservation Status"::Prospect);
            ReservEntry.SetRange("Qty. to Handle (Base)"); //A108B0012.n
            if not ReservEntry.IsEmpty() then
                ReservEntry.DeleteAll();
            OnAfterDeleteReservationEntriesOnRetrievedTracingSpecifications(TempHandlingSpecification); //A200F0000.Event
            exit(true);
        end;
        exit(false);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterDeleteReservationEntriesOnRetrievedTracingSpecifications(var TrackingSpecificationBuffer: Record "Tracking Specification")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
