### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnBeforeInsertReservationEntryFromTrackingSpecification

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13212]
We would like to add a new event OnBeforeInsertReservationEntryFromTrackingSpecification in the following procedure:

    local procedure InsertReservEntryFromTrackingSpec(TrackingSpecification: Record "Tracking Specification"; SourceSubtype: Option; SourceID: Code[20]; SourceRefNo: Integer; QtyBase: Decimal)
    var
        ReservEntry: Record "Reservation Entry";
    begin
        if QtyBase = 0 then
            exit;

        with ReservEntry do begin
            Init;
            TransferFields(TrackingSpecification);
            "Source Subtype" := SourceSubtype;
            "Source ID" := SourceID;
            "Source Ref. No." := SourceRefNo;
            "Reservation Status" := "Reservation Status"::Prospect;
            "Quantity Invoiced (Base)" := 0;
            Validate("Quantity (Base)", QtyBase);
            Positive := ("Quantity (Base)" > 0);
            "Entry No." := 0;
            "Item Tracking" := GetItemTrackingEntryType();
            OnBeforeInsertReservationEntryFromTrackingSpecification(ReservEntry, TrackingSpecification); //A109F0006.Event
            Insert();
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertReservationEntryFromTrackingSpecification(var ReservationEntry: Record "Reservation Entry"; TrackingSpecification: Record "Tracking Specification")
    begin
        //A109F0006.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
