### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnBeforeSplitPostedWarehouseReceiptLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13217]
We would like to add a new event OnBeforeSplitPostedWarehouseReceiptLine in the following procedure:

    procedure SplitPostedWhseRcptLine(PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; var TempPostedWhseRcptLine: Record "Posted Whse. Receipt Line" temporary)
    var
        WhseItemEntryRelation: Record "Whse. Item Entry Relation";
        WhseItemTrackingSetup: Record "Item Tracking Setup";
        ItemLedgEntry: Record "Item Ledger Entry";
        LineNo: Integer;
        CrossDockQty: Decimal;
        CrossDockQtyBase: Decimal;
        IsHandled: Boolean;
    begin
        TempPostedWhseRcptLine.Reset();
        TempPostedWhseRcptLine.DeleteAll();

        //A200F0000.Event.ns
        IsHandled := false;
        OnBeforeSplitPostedWarehouseReceiptLine(PostedWhseRcptLine, TempPostedWhseRcptLine, IsHandled);
        if IsHandled then
            exit;
        //A200F0000.Event.ne

        if not GetWhseItemTrkgSetup(PostedWhseRcptLine."Item No.", WhseItemTrackingSetup) then begin
            TempPostedWhseRcptLine := PostedWhseRcptLine;
            TempPostedWhseRcptLine.Insert();
            OnAfterSplitPostedWhseReceiptLine(PostedWhseRcptLine, TempPostedWhseRcptLine);
            exit;
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSplitPostedWarehouseReceiptLine(PostedWhseReceiptLine: Record "Posted Whse. Receipt Line"; var TempPostedWhseReceiptLine: Record "Posted Whse. Receipt Line"; var IsHandled: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
