### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnBeforeModifyTransferReservationEntries

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13218]
We would like to add a new event OnBeforeModifyTransferReservationEntries in the following procedure:

    local procedure ModifyTemp337SetIfTransfer(var TempReservEntry: Record "Reservation Entry" temporary)
    var
        TransLine: Record "Transfer Line";
        IsHandled: Boolean;
    begin
        //A200F0000.Event.ns
        IsHandled := false;
        OnBeforeModifyTransferReservationEntries(TempReservEntry, IsHandled);
        if IsHandled then
            exit;
        //A200F0000.Event.ne
        if TempReservEntry."Source Type" = DATABASE::"Transfer Line" then begin
            TransLine.Get(TempReservEntry."Source ID", TempReservEntry."Source Ref. No.");
            TempReservEntry.ModifyAll("Reservation Status", TempReservEntry."Reservation Status"::Surplus);
            if TempReservEntry."Source Subtype" = 0 then begin
                TempReservEntry.ModifyAll("Location Code", TransLine."Transfer-from Code");
                TempReservEntry.ModifyAll("Expected Receipt Date", 0D);
                TempReservEntry.ModifyAll("Shipment Date", TransLine."Shipment Date");
            end else begin
                TempReservEntry.ModifyAll("Location Code", TransLine."Transfer-to Code");
                TempReservEntry.ModifyAll("Expected Receipt Date", TransLine."Receipt Date");
                TempReservEntry.ModifyAll("Shipment Date", 0D);
            end;
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyTransferReservationEntries(var ReservationEntryBuffer: Record "Reservation Entry"; var IsHandled: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
