### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnAfterSynchronizeWhseItemTrackingSpecification

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13210]
We would like to add a new event OnAfterSynchronizeWhseItemTrackingSpecification in the following procedure:

    procedure SynchronizeWhseItemTracking(var TempTrackingSpecification: Record "Tracking Specification" temporary; RegPickNo: Code[20]; Deletion: Boolean)
.
.
.
                                if IsReservedFromTransferShipment(ReservEntry) then
                                    UpdateItemTrackingInTransferReceipt(ReservEntry);
                            until (ReservEntry.Next() = 0) or (Qty = 0);
                    end;
                    TempTrackingSpecification.Delete();
                end;
                OnAfterSynchronizeWhseItemTrackingSpecification(TempTrackingSpecification, RegPickNo, Deletion); //A201F0000.Event.n
            until TempTrackingSpecification.Next() = 0;

        RegisterNewItemTrackingLines(TempTrackingSpecification);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSynchronizeWhseItemTrackingSpecification(var TempTrackingSpecification: Record "Tracking Specification" temporary; RegPickNo: Code[20]; Deletion: Boolean)
    begin
        //A201F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
