### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnAfterInsertReservationEntryForPurchaseLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13215]
We would like to add a new event OnAfterInsertReservationEntryForPurchaseLine in the following procedure:

    local procedure InsertReservEntryForPurchLine(ItemLedgEntryBuf: Record "Item Ledger Entry"; PurchaseLine: Record "Purchase Line"; QtyBase: Decimal; AppliedToItemEntry: Boolean; var EntriesExist: Boolean)
    var
        ReservEntry: Record "Reservation Entry";
    begin
        if QtyBase = 0 then
            exit;

        with ReservEntry do begin
            InitReservEntry(ReservEntry, ItemLedgEntryBuf, QtyBase, PurchaseLine."Expected Receipt Date", EntriesExist);
            SetSource(DATABASE::"Purchase Line", PurchaseLine."Document Type".AsInteger(), PurchaseLine."Document No.", PurchaseLine."Line No.", '', 0);
            if PurchaseLine."Document Type" in [PurchaseLine."Document Type"::Order, PurchaseLine."Document Type"::"Return Order"] then
                "Reservation Status" := "Reservation Status"::Surplus
            else
                "Reservation Status" := "Reservation Status"::Prospect;
            if AppliedToItemEntry then
                "Appl.-to Item Entry" := ItemLedgEntryBuf."Entry No.";
            Description := PurchaseLine.Description;
            OnCopyItemLedgEntryTrkgToDocLine(ItemLedgEntryBuf, ReservEntry);
            UpdateItemTracking;
            OnBeforeInsertReservEntryForPurchLine(ReservEntry, PurchaseLine);
            Insert;
            OnAfterInsertReservationEntryForPurchaseLine(ReservEntry, PurchaseLine);
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertReservationEntryForPurchaseLine(var ReservationEntry: Record "Reservation Entry"; PurchaseLine: Record "Purchase Line")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
