### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnAfterRemoveItemTrackingFromWarehouseShipmentReservationEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13214]
We would like to add a new event OnAfterRemoveItemTrackingFromWarehouseShipmentReservationEntry in the following procedure:

    local procedure RemoveItemTrkgFromReservEntry(WhseItemTrackingLine: Record "Whse. Item Tracking Line")
    var
        ReservEntry: Record "Reservation Entry";
        WarehouseShipmentLine: Record "Warehouse Shipment Line";
        OriginalReservEntry: Record "Reservation Entry";
    begin
        WarehouseShipmentLine.SetRange("No.", WhseItemTrackingLine."Source ID");
        WarehouseShipmentLine.SetRange("Line No.", WhseItemTrackingLine."Source Ref. No.");
        if not WarehouseShipmentLine.FindFirst then
            exit;

        ReservEntry.SetSourceFilter(
          WarehouseShipmentLine."Source Type", WarehouseShipmentLine."Source Subtype",
          WarehouseShipmentLine."Source No.", WarehouseShipmentLine."Source Line No.", true);
        ReservEntry.SetTrackingFilterFromWhseSpec(WhseItemTrackingLine);
        if ReservEntry.FindSet then
            repeat
                OriginalReservEntry := ReservEntry; //A200F0000.Event
                case ReservEntry."Reservation Status" of
                    ReservEntry."Reservation Status"::Surplus:
                        ReservEntry.Delete(true);
                    else begin
                            ReservEntry.ClearItemTrackingFields;
                            ReservEntry.Modify(true);
                        end;
                end;
                OnAfterRemoveItemTrackingFromWarehouseShipmentReservationEntry(ReservEntry, OriginalReservEntry); //A200F0000.Event
            until ReservEntry.Next() = 0;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterRemoveItemTrackingFromWarehouseShipmentReservationEntry(var ReservationEntry: Record "Reservation Entry"; OriginalReservEntry: Record "Reservation Entry")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
