### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnAfterInsertReservationEntryForSalesLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13216]
We would like to add a new event OnAfterInsertReservationEntryForSalesLine in the following procedure:

    local procedure InsertReservEntryForSalesLine(var ReservEntry: Record "Reservation Entry"; ItemLedgEntryBuf: Record "Item Ledger Entry"; SalesLine: Record "Sales Line"; QtyBase: Decimal; AppliedFromItemEntry: Boolean; var EntriesExist: Boolean)
    begin
        if QtyBase = 0 then
            exit;

        with ReservEntry do begin
            InitReservEntry(ReservEntry, ItemLedgEntryBuf, QtyBase, SalesLine."Shipment Date", EntriesExist);
            SetSource(
              DATABASE::"Sales Line", SalesLine."Document Type".AsInteger(), SalesLine."Document No.", SalesLine."Line No.", '', 0);
            if SalesLine."Document Type" in [SalesLine."Document Type"::Order, SalesLine."Document Type"::"Return Order"] then
                "Reservation Status" := "Reservation Status"::Surplus
            else
                "Reservation Status" := "Reservation Status"::Prospect;
            if AppliedFromItemEntry then
                "Appl.-from Item Entry" := ItemLedgEntryBuf."Entry No.";
            Description := SalesLine.Description;
            OnCopyItemLedgEntryTrkgToDocLine(ItemLedgEntryBuf, ReservEntry);
            UpdateItemTracking;
            OnBeforeInsertReservEntryForSalesLine(ReservEntry, SalesLine);
            Insert;
            OnAfterInsertReservationEntryForSalesLine(ReservEntry, SalesLine); //A200F0000.Event
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertReservationEntryForSalesLine(var ReservationEntry: Record "Reservation Entry"; SalesLine: Record "Sales Line")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
