### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnBeforeTempReservationEntryInsertOnCopyItemTracking

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13211]
We would like to add a new event OnBeforeTempReservationEntryInsertOnCopyItemTracking in the following procedure:

    local procedure CopyItemTracking3(var ReservEntry: Record "Reservation Entry"; ToRowID: Text[250]; SwapSign: Boolean; SkipReservation: Boolean)
    var
        ReservEntry1: Record "Reservation Entry";
        TempReservEntry: Record "Reservation Entry" temporary;
    begin
        OnBeforeCopyItemTracking3(ReservEntry, ToRowID, SwapSign, SkipReservation);

        if SkipReservation then
            ReservEntry.SetFilter("Reservation Status", '<>%1', ReservEntry."Reservation Status"::Reservation);
        if ReservEntry.FindSet then begin
            repeat
                if ReservEntry.TrackingExists then begin
                    TempReservEntry := ReservEntry;
                    TempReservEntry."Reservation Status" := TempReservEntry."Reservation Status"::Prospect;
                    TempReservEntry.SetPointer(ToRowID);
                    if SwapSign then begin
                        TempReservEntry."Quantity (Base)" := -TempReservEntry."Quantity (Base)";
                        TempReservEntry.Quantity := -TempReservEntry.Quantity;
                        TempReservEntry."Qty. to Handle (Base)" := -TempReservEntry."Qty. to Handle (Base)";
                        TempReservEntry."Qty. to Invoice (Base)" := -TempReservEntry."Qty. to Invoice (Base)";
                        TempReservEntry."Quantity Invoiced (Base)" := -TempReservEntry."Quantity Invoiced (Base)";
                        TempReservEntry.Positive := TempReservEntry."Quantity (Base)" > 0;
                        TempReservEntry.ClearApplFromToItemEntry;
                        //OnCopyItemTracking3OnBeforeSwapSign(TempReservEntry); A200F0000.Event.o
                        OnCopyItemTracking3OnBeforeSwapSign(TempReservEntry, ReservEntry); //A200F0000.Event.n
                    end;
                    OnBeforeTempReservationEntryInsertOnCopyItemTracking(TempReservEntry); //A109F0006.Event
                    TempReservEntry.Insert();
                end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTempReservationEntryInsertOnCopyItemTracking(var ReservationEntry: Record "Reservation Entry")
    begin
        //A109F0006.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
