### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnBeforeCalcWhseItemTrkgLines

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13224]
We would like to add a new event OnBeforeCalcWhseItemTrkgLines in the following procedure:

    procedure InitTrackingSpecification(WhseWkshLine: Record "Whse. Worksheet Line")
    var
        WhseItemTrkgLine: Record "Whse. Item Tracking Line";
        PostedWhseReceiptLine: Record "Posted Whse. Receipt Line";
        TempWhseItemTrkgLine: Record "Whse. Item Tracking Line" temporary;
        WhseManagement: Codeunit "Whse. Management";
        SourceType: Integer;
        IsHandled: Boolean;
    begin
        SourceType := WhseManagement.GetSourceType(WhseWkshLine);
        with WhseWkshLine do begin
            if "Whse. Document Type" = "Whse. Document Type"::Receipt then begin
                PostedWhseReceiptLine.SetRange("No.", "Whse. Document No.");
                PostedWhseReceiptLine.SetRange("Line No.", "Whse. Document Line No.");
                if PostedWhseReceiptLine.FindFirst then
                    InsertWhseItemTrkgLines(PostedWhseReceiptLine, SourceType);
            end;

            if SourceType = DATABASE::"Prod. Order Component" then begin
                WhseItemTrkgLine.SetSourceFilter(SourceType, "Source Subtype", "Source No.", "Source Subline No.", true);
                WhseItemTrkgLine.SetRange("Source Prod. Order Line", "Source Line No.");
            end else
                WhseItemTrkgLine.SetSourceFilter(SourceType, -1, "Whse. Document No.", "Whse. Document Line No.", true);

            WhseItemTrkgLine.LockTable();
            //if WhseItemTrkgLine.FindSet then begin //A200F0000.Event.o
            //A200F0000.Event.ns
            IsHandled := false;
            OnBeforeCalcWhseItemTrkgLines(WhseWkshLine, WhseItemTrkgLine, IsHandled);
            if WhseItemTrkgLine.FindSet and not IsHandled then begin
                //A200F0000.Event.ne
                repeat
                    CalcWhseItemTrkgLine(WhseItemTrkgLine);
                    WhseItemTrkgLine.Modify();
                    if SourceType in [DATABASE::"Prod. Order Component", DATABASE::"Assembly Line"] then begin
                        TempWhseItemTrkgLine := WhseItemTrkgLine;
                        TempWhseItemTrkgLine.Insert();
                    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcWhseItemTrkgLines(var WhseWorksheetLine: Record "Whse. Worksheet Line"; var WhseItemTrackingLine: Record "Whse. Item Tracking Line"; var IsHandled: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
