### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnBeforeSyncNewTrackingSpecification

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13221]
We would like to add a new event OnBeforeSyncNewTrackingSpecification in the following procedure:

    local procedure SynchronizeItemTracking2(var FromReservEntry: Record "Reservation Entry"; ToRowID: Text[250]; DialogText: Text[250])
.
.
.

                    end else begin
                        TempTrkgSpec3 := TempTrkgSpec1;
                        OnBeforeSyncNewTrackingSpecification(TempTrkgSpec3, TempTrkgSpec1, TempSourceSpec); //A200F0000.Event
                        TempTrkgSpec3.Validate("Quantity (Base)", TempTrkgSpec1."Quantity (Base)" * SignFactor1);
                        TempTrkgSpec3."Entry No." := LastEntryNo + 1;
                        TempTrkgSpec3.Insert();
                    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSyncNewTrackingSpecification(var NewTrackingSpecification: Record "Tracking Specification"; TrackingSpecification: Record "Tracking Specification"; SourceTrackingSpecification: Record "Tracking Specification")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
