### ISSUE TITLE
[Event Request] codeunit 99000837 "Prod. Order Line-Reserve" - OnAfterModifyReservationEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13228]
We would like to add a new event OnAfterModifyReservationEntry in the following procedure:

    procedure DeleteLineConfirm(var ProdOrderLine: Record "Prod. Order Line"): Boolean
.
.
.

            if not Confirm(ConfirmMessage, false, ProdOrderLine.Status, ProdOrderLine.TableCaption, ProdOrderLine."Line No.") then
                exit(false);

            SetFilter("Source Type", '%1|%2', DATABASE::"Prod. Order Line", DATABASE::"Prod. Order Component");
            SetRange("Source Ref. No.");
            if FindSet then
                repeat
                    ReservEntry2 := ReservEntry;
                    ReservEntry2.ClearItemTrackingFields;
                    ReservEntry2.Modify();
                    OnAfterModifyReservationEntry(ReservEntry); //A200F0000.Event
                until Next() = 0;
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterModifyReservationEntry(var ReservationEntry: Record "Reservation Entry")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
