### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnBeforeCreateWhseItemTrckReservationEntries

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13223]
We would like to add a new event OnBeforeCreateWhseItemTrckReservationEntries in the following procedure:

    local procedure CreateWhseItemTrkgBatch(WhseWkshLine: Record "Whse. Worksheet Line")
    var
        SourceItemTrackingLine: Record "Reservation Entry";
        WhseManagement: Codeunit "Whse. Management";
        SourceType: Integer;
        IsHandled: Boolean;
    begin
        SourceType := WhseManagement.GetSourceType(WhseWkshLine);

        with WhseWkshLine do begin
            case SourceType of
                DATABASE::"Prod. Order Component":
                    begin
                        SourceItemTrackingLine.SetSourceFilter("Source Type", "Source Subtype", "Source No.", "Source Subline No.", true);
                        SourceItemTrackingLine.SetSourceFilter('', "Source Line No.");
                    end;
                else begin
                        SourceItemTrackingLine.SetSourceFilter("Source Type", "Source Subtype", "Source No.", "Source Line No.", true);
                        SourceItemTrackingLine.SetSourceFilter('', 0);
                    end;
            end;
            //A200F0000.Event.ns
            IsHandled := false;
            OnBeforeCreateWhseItemTrckReservationEntries(WhseWkshLine, SourceItemTrackingLine, SourceType, IsHandled);
            if not IsHandled then
                //A200F0000.Event.ne
                if SourceItemTrackingLine.FindSet then
                    repeat
                        CreateWhseItemTrkgForResEntry(SourceItemTrackingLine, WhseWkshLine);
                    until SourceItemTrackingLine.Next() = 0;
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateWhseItemTrckReservationEntries(WhseWorksheetLine: Record "Whse. Worksheet Line"; var ReservationEntry: Record "Reservation Entry"; SourceType: Integer; var IsHandled: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
