### ISSUE TITLE
[Event Request] codeunit 5406 "Output Jnl.-Expl. Route" - OnAfterCopyItemTracking

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13225]
We would like to add 2 new events OnAfterCopyItemTracking in the following trigger: 

    trigger OnRun()
.
.
.

                        if not SkipRecord then begin
                            InsertOutputJnlLine(
                              Rec, NextLineNo, LineSpacing,
                              ProdOrderLine."Line No.",
                              ProdOrderLine."Item No.",
                              ProdOrderLine."Variant Code",
                              ProdOrderLine."Location Code",
                              ProdOrderLine."Bin Code",
                              ProdOrderLine."Routing No.", ProdOrderLine."Routing Reference No.",
                              ProdOrderRtngLine."Operation No.",
                              ProdOrderLine."Unit of Measure Code",
                              BaseQtyToPost / ProdOrderLine."Qty. per Unit of Measure",
                              IsLastOperation);
                            OnRunOnAfterInsertOutputJnlLineWithRtngLine(ItemJnlLine, ProdOrderLine, ProdOrderRtngLine, NextLineNo);
                            if IsLastOperation then
                                ItemTrackingMgt.CopyItemTracking(ProdOrderLine.RowID1, LastItemJnlLine.RowID1, false);
                            OnAfterCopyItemTracking(LastItemJnlLine, IsLastOperation, NextLineNo); //A200F0000.Event
                        end;
                    end;

and:

                if ProdOrderLine."Remaining Quantity" > 0 then begin
                    OnBeforeInsertOutputJnlLineWithoutRtngLine(Rec, ProdOrderLine);
                    InsertOutputJnlLine(
                      Rec, NextLineNo, LineSpacing,
                      ProdOrderLine."Line No.",
                      ProdOrderLine."Item No.",
                      ProdOrderLine."Variant Code",
                      ProdOrderLine."Location Code",
                      ProdOrderLine."Bin Code",
                      ProdOrderLine."Routing No.", ProdOrderLine."Routing Reference No.", '',
                      ProdOrderLine."Unit of Measure Code",
                      ProdOrderLine."Remaining Quantity",
                      true);
                    OnAfterInsertOutputJnlLineWithoutRtngLine(ItemJnlLine, ProdOrderLine, ProdOrderRtngLine, NextLineNo);
                    ItemTrackingMgt.CopyItemTracking(ProdOrderLine.RowID1, LastItemJnlLine.RowID1, false);
                    OnAfterCopyItemTracking(LastItemJnlLine, true, NextLineNo); //A200F0000.Event
                end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyItemTracking(var ItemJournalLine: Record "Item Journal Line"; LastOperation: Boolean; var NextLineNo: Integer)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
