### ISSUE TITLE
[Event Request] codeunit 99000837 "Prod. Order Line-Reserve" - OnBeforeTransferReservationEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13229]
We would like to add a new event OnBeforeTransferReservationEntry in the following procedure:

    procedure TransferPOLineToItemJnlLine(var OldProdOrderLine: Record "Prod. Order Line"; var NewItemJnlLine: Record "Item Journal Line"; TransferQty: Decimal)
.
.
.

        if ReservEngineMgt.InitRecordSet(OldReservEntry) then
            repeat
                if NewItemJnlLine.TrackingExists then
                    CreateReservEntry.SetNewTrackingFromItemJnlLine(NewItemJnlLine);
                OldReservEntry.TestItemFields(OldProdOrderLine."Item No.", OldProdOrderLine."Variant Code", OldProdOrderLine."Location Code");
                //A200F0000.Event.ns
                CancelThisReservEntry := false;
                OnBeforeTransferReservationEntry(OldProdOrderLine, NewItemJnlLine, OldReservEntry, CancelThisReservEntry);
                if not CancelThisReservEntry then
                    //A200F0000.Event.ne

                    TransferQty := CreateReservEntry.TransferReservEntry(DATABASE::"Item Journal Line",
                       NewItemJnlLine."Entry Type".AsInteger(), NewItemJnlLine."Journal Template Name", NewItemJnlLine."Journal Batch Name", 0,
                       NewItemJnlLine."Line No.", NewItemJnlLine."Qty. per Unit of Measure", OldReservEntry, TransferQty);

                if TransferQty <> 0 then //A108P0011.n
                    if ReservEngineMgt.NEXTRecord(OldReservEntry) = 0 then
                        if ItemTrackingFilterIsSet then begin
                            OldReservEntry.ClearTrackingFilter;
                            ItemTrackingFilterIsSet := false;
                            OldReservEntry.SetRange("Item Tracking", OldReservEntry."Item Tracking"::None); //A108B0041.n
                            EndLoop := not ReservEngineMgt.InitRecordSet(OldReservEntry);
                        end else
                            EndLoop := true;

            until EndLoop or (TransferQty = 0);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferReservationEntry(var ProdOrderLine: Record "Prod. Order Line"; var ItemJournalLine: Record "Item Journal Line"; var ReservationEntry: Record "Reservation Entry"; var CancelThisReservEntry: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
