### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnBeforeModifySynchedWarehouseItemTrackingLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13222]
We would like to add a new event OnBeforeModifySynchedWarehouseItemTrackingLine in the following procedure:

    procedure SynchronizeWhseItemTracking(var TempTrackingSpecification: Record "Tracking Specification" temporary; RegPickNo: Code[20]; Deletion: Boolean)
.
.
.

                                if Abs(ReservEntry."Qty. to Handle (Base)") > Abs(ReservEntry."Quantity (Base)") then begin
                                    Qty := ReservEntry."Qty. to Handle (Base)" - ReservEntry."Quantity (Base)";
                                    ReservEntry."Qty. to Handle (Base)" := ReservEntry."Quantity (Base)";
                                    ReservEntry."Qty. to Invoice (Base)" := ReservEntry."Quantity (Base)";
                                end else
                                    Qty := 0;
                                OnBeforeModifySynchedWarehouseItemTrackingLine(ReservEntry, TempTrackingSpecification, RegPickNo, Deletion); //A200F0000.Event
                                ReservEntry.Modify();

                                if IsReservedFromTransferShipment(ReservEntry) then
                                    UpdateItemTrackingInTransferReceipt(ReservEntry);
                            until (ReservEntry.Next() = 0) or (Qty = 0);
                    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifySynchedWarehouseItemTrackingLine(var ReservationEntry: Record "Reservation Entry"; TrackingSpecification: Record "Tracking Specification"; RegPickNo: Code[20]; Deletion: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
