### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnBeforeDeleteSyncTrackingSpecification

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13220]
We would like to add a new event OnBeforeDeleteSyncTrackingSpecification in the following procedure:

    local procedure SynchronizeItemTracking2(var FromReservEntry: Record "Reservation Entry"; ToRowID: Text[250]; DialogText: Text[250])
.
.
.

            if TempTrkgSpec1.FindSet then
                repeat
                    TempTrkgSpec2.SetTrackingFilterFromSpec(TempTrkgSpec1);
                    if TempTrkgSpec2.FindFirst then begin
                        ShouldInsertTrkgSpec := TempTrkgSpec2."Quantity (Base)" * SignFactor2 <> TempTrkgSpec1."Quantity (Base)" * SignFactor1;
                        OnSynchronizeItemTracking2OnAfterCalcShouldInsertTrkgSpec(TempTrkgSpec1, TempTrkgSpec2, TempTrkgSpec3, SignFactor1, SignFactor2, ShouldInsertTrkgSpec);
                        if ShouldInsertTrkgSpec then begin
                            TempTrkgSpec3 := TempTrkgSpec2;
                            OnBeforeSyncBothExistingTrackingSpecification(TempTrkgSpec3, TempTrkgSpec1, TempTrkgSpec2); //A200F0000.Event
                            TempTrkgSpec3.Validate("Quantity (Base)",
                              (TempTrkgSpec1."Quantity (Base)" * SignFactor1 - TempTrkgSpec2."Quantity (Base)" * SignFactor2));
                            TempTrkgSpec3."Entry No." := LastEntryNo + 1;
                            TempTrkgSpec3.Insert();
                        end;
                        OnBeforeDeleteSyncTrackingSpecification(TempTrkgSpec3, TempTrkgSpec1, TempTrkgSpec2, SignFactor1, SignFactor2, LastEntryNo); //A200F0000.Event
                        TempTrkgSpec2.Delete();
                    end else begin
                        TempTrkgSpec3 := TempTrkgSpec1;
                        OnBeforeSyncNewTrackingSpecification(TempTrkgSpec3, TempTrkgSpec1, TempSourceSpec); //A200F0000.Event
                        TempTrkgSpec3.Validate("Quantity (Base)", TempTrkgSpec1."Quantity (Base)" * SignFactor1);
                        TempTrkgSpec3."Entry No." := LastEntryNo + 1;
                        TempTrkgSpec3.Insert();
                    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteSyncTrackingSpecification(var TrackingSpecification3: Record "Tracking Specification"; TrackingSpecification1: Record "Tracking Specification"; TrackingSpecification2: Record "Tracking Specification"; SignFactor1: Integer; SignFactor2: Integer; var LastEntryNo: Integer)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
