### ISSUE TITLE
[Event Request] codeunit 7002 "Price Calculation - V16" implements "Price Calculation" - OnAfterIsDegradedLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13226]
We would like to add a new event OnAfterIsDegradedLine in the following procedure:

    local procedure IsDegradedLine(PriceListLine: Record "Price List Line"; BestPriceListLine: Record "Price List Line") Result: Boolean
    begin
        Result :=
            IsBlankedValue(PriceListLine."Currency Code", BestPriceListLine."Currency Code") or
            IsBlankedValue(PriceListLine."Variant Code", BestPriceListLine."Variant Code");

        OnAfterIsDegradedLine(PriceListLine, BestPriceListLine, Result); //A101F0000.Event
    end;

    local procedure IsBlankedValue(LineValue: Text; BestLineValue: Text): Boolean
    begin
        exit((BestLineValue <> '') and (LineValue = ''));
    end;

Event Signature:

    [IntegrationEvent(true, false)]
    local procedure OnAfterIsDegradedLine(PriceListLine: Record "Price List Line"; BestPriceListLine: Record "Price List Line"; var Result: Boolean)
    begin
        //A101F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
