### ISSUE TITLE
[Event Request] codeunit 74 "Purch.-Get Receipt" - OnBeforeTransferLineToPurchaseDocLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13233]
We would like to add a new event OnBeforeTransferLineToPurchaseDocLine in the following procedure:

    procedure CreateInvLines(var PurchRcptLine2: Record "Purch. Rcpt. Line")
.
.
.

                        if ShowDifferentPayToVendMsg then begin
                            Message(
                              Text000,
                              PurchHeader.FieldCaption("Pay-to Vendor No."),
                              PurchHeader.TableCaption, PurchHeader."No.",
                              PurchRcptHeader.TableCaption, PurchRcptHeader."No.");
                            TransferLine := false;
                        end;
                        OnBeforeTransferLineToPurchaseDoc(PurchRcptHeader, PurchRcptLine2, PurchHeader, TransferLine);
                    end;
                    //A108F0019.Event.ns
                    TransferThisLine := true;
                    OnBeforeTransferLineToPurchaseDocLine(PurchRcptHeader, PurchRcptLine2, PurchHeader, TransferThisLine);
                    if TransferThisLine then
                    //A108F0019.Event.ne
                    if TransferLine then begin
                        PurchRcptLine := PurchRcptLine2;
                        PurchRcptLine.InsertInvLineFromRcptLine(PurchLine);
                        CalcUpdatePrepmtAmtToDeductRounding(PurchRcptLine, PurchLine, PrepmtAmtToDeductRounding);
                    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferLineToPurchaseDocLine(var PurchRcptHeader: Record "Purch. Rcpt. Header"; var PurchRcptLine: Record "Purch. Rcpt. Line"; var PurchaseHeader: Record "Purchase Header"; var TransferLine: Boolean)
    begin
        //A108F0019.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
