### ISSUE TITLE
[Event Request] codeunit 6648 "Purch.-Get Return Shipments" - OnBeforeTransferLineToPurchaseDocLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13236]
We would like to add a new event OnBeforeTransferLineToPurchaseDocLine in the following procedure:

    procedure CreateInvLines(var ReturnShptLine2: Record "Return Shipment Line")
    var
        DifferentCurrencies: Boolean;
        TransferThisLine: Boolean;
    begin
        with ReturnShptLine2 do begin
            SetFilter("Return Qty. Shipped Not Invd.", '<>0');
            OnCreateCrMemoLinesOnBeforeFind(ReturnShptLine2); //A108F0019.Event
            if Find('-') then begin
                PurchLine.LockTable();
                PurchLine.SetRange("Document Type", PurchHeader."Document Type");
                PurchLine.SetRange("Document No.", PurchHeader."No.");
                PurchLine."Document Type" := PurchHeader."Document Type";
                PurchLine."Document No." := PurchHeader."No.";

                repeat
                    if ReturnShptHeader."No." <> "Document No." then begin
                        ReturnShptHeader.Get("Document No.");
                        CheckReturnShptPayToVendorNo(ReturnShptHeader, PurchHeader, ReturnShptLine2);
                        DifferentCurrencies := false;
                        if ReturnShptHeader."Currency Code" <> PurchHeader."Currency Code" then begin
                            Message(Text000,
                              PurchHeader.FieldCaption("Currency Code"),
                              PurchHeader.TableCaption, PurchHeader."No.",
                              ReturnShptHeader.TableCaption, ReturnShptHeader."No.");
                            DifferentCurrencies := true;
                        end;
                        OnBeforeTransferLineToPurchaseDoc(ReturnShptHeader, ReturnShptLine2, PurchHeader, DifferentCurrencies);
                    end;
                    //A108F0019.Event.ns
                    TransferThisLine := true;
                    OnBeforeTransferLineToPurchaseDocLine(ReturnShptHeader, ReturnShptLine2, PurchHeader, TransferThisLine);
                    if TransferThisLine then
                        //A108F0019.Event.ne
                        if not DifferentCurrencies then begin
                            ReturnShptLine := ReturnShptLine2;
                            ReturnShptLine.InsertInvLineFromRetShptLine(PurchLine);
                            if Type = Type::"Charge (Item)" then
                                GetItemChargeAssgnt(ReturnShptLine2, PurchLine."Qty. to Invoice");
                        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferLineToPurchaseDocLine(var ReturnShipmentHeader: Record "Return Shipment Header"; var ReturnShipmentLine: Record "Return Shipment Line"; var PurchaseHeader: Record "Purchase Header"; var TransferLine: Boolean)
    begin
        //A108F0019.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
