### ISSUE TITLE
[Event Request] codeunit 5510 "Production Journal Mgt" - OnAfterCopyItemTracking

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13232]
We would like to add a new event OnAfterCopyItemTracking in the following 2 procedures: 

    procedure InsertConsumptionItemJnlLine(ProdOrderComp: Record "Prod. Order Component"; ProdOrderLine: Record "Prod. Order Line"; Level: Integer)
.
.
.

            OnBeforeInsertConsumptionJnlLine(ItemJnlLine, ProdOrderComp, ProdOrderLine, Level);
            ItemJnlLine.Insert();
            OnAfterInsertConsumptionJnlLine(ItemJnlLine);

            if Item."Item Tracking Code" <> '' then
                ItemTrackingMgt.CopyItemTracking(RowID1, ItemJnlLine.RowID1, false);
            OnAfterCopyItemTracking(ItemJnlLine, Item."Item Tracking Code" <> '', NextLineNo); //A200F0000.Event                
        end;

and:

    procedure InsertOutputItemJnlLine(ProdOrderRtngLine: Record "Prod. Order Routing Line"; ProdOrderLine: Record "Prod. Order Line")
.
.
.

            OnBeforeInsertOutputJnlLine(ItemJnlLine, ProdOrderRtngLine, ProdOrderLine);
            ItemJnlLine.Insert();
            OnAfterInsertOutputJnlLine(ItemJnlLine);

            if IsLastOperation(ProdOrderRtngLine) then
                ItemTrackingMgt.CopyItemTracking(RowID1, ItemJnlLine.RowID1, false);
            OnAfterCopyItemTracking(ItemJnlLine, IsLastOperation(ProdOrderRtngLine), NextLineNo); //A200F0000.Event
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyItemTracking(var ItemJournalLine: Record "Item Journal Line"; LastOperation: Boolean; var NextLineNo: Integer)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
