### ISSUE TITLE
[Event Request] codeunit 99000834 "Purch. Line-Reserve" - OnBeforeTransferReservationEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13237]
We would like to add a new event OnBeforeTransferReservationEntry in the following procedure:

    procedure TransferPurchLineToItemJnlLine(var PurchLine: Record "Purchase Line"; var ItemJnlLine: Record "Item Journal Line"; TransferQty: Decimal; var CheckApplToItemEntry: Boolean): Decimal
.
.
.

                    if OldReservEntry."Item Tracking" <> OldReservEntry."Item Tracking"::None then begin
                        OldReservEntry.TestField("Appl.-to Item Entry");
                        CreateReservEntry.SetApplyToEntryNo(OldReservEntry."Appl.-to Item Entry");
                        CheckApplToItemEntry := false;
                    end;
                end;

                //A109F0006.event.ns
                IsHandled := false;
                OnBeforeTransferReservationEntry(OldReservEntry, PurchLine, ItemJnlLine, IsHandled);
                if not IsHandled then
                    //A109F0006.event.ne
                    TransferQty := CreateReservEntry.TransferReservEntry(DATABASE::"Item Journal Line",
                    ItemJnlLine."Entry Type".AsInteger(), ItemJnlLine."Journal Template Name",
                    ItemJnlLine."Journal Batch Name", 0, ItemJnlLine."Line No.",
                    ItemJnlLine."Qty. per Unit of Measure", OldReservEntry, TransferQty);

            until (ReservEngineMgt.NEXTRecord(OldReservEntry) = 0) or (TransferQty = 0);
            CheckApplToItemEntry := CheckApplToItemEntry and NotFullyReserved;
        end;
        exit(TransferQty);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferReservationEntry(var ReservationEntry: Record "Reservation Entry"; PurchaseLine: Record "Purchase Line"; ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean);
    begin
        //A109F0006.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
