### ISSUE TITLE
EventPublisher request / change needed urgently - Contact table (OnBeforeBankAccountInsert) is missing Rec. 

### ISSUE THREAD

**Issue by eque2al** [microsoft/ALAppExtensions#13234]
As per title the publisher event OnBeforeBankAccountInsert on the Contact table only contains the BankAccount record and it must contain the BankAccount and Contact (Rec) record to be useful.

Please can you let me know urgently which release this will be targeted for?

**This halts our product development until it is resolved - so it really is urgent!**

This has been reported before but hasn't been done...

https://github.com/microsoft/ALAppExtensions/issues/8446

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
