### ISSUE TITLE
[Event Request] codeunit 99000837 "Prod. Order Line-Reserve" - OnBeforeTestItemJournalLineFields

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13230]
We would like to add a new event OnBeforeTestItemJournalLineFields in the following procedure:

    procedure TransferPOLineToItemJnlLine(var OldProdOrderLine: Record "Prod. Order Line"; var NewItemJnlLine: Record "Item Journal Line"; TransferQty: Decimal)
.
.
.

            end;

        //A200F0000.Event.ns
        OnBeforeTestItemJournalLineFields(NewItemJnlLine, OldProdOrderLine, IsHandled);
        if not IsHandled then
            //A200F0000.Event.ne
            NewItemJnlLine.TestItemFields(OldProdOrderLine."Item No.", OldProdOrderLine."Variant Code", OldProdOrderLine."Location Code");

        if TransferQty = 0 then
            exit;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTestItemJournalLineFields(var ItemJournalLine: Record "Item Journal Line"; var ProdOrderLine: Record "Prod. Order Line"; var IsHandled: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
