### ISSUE TITLE
request for SaaS/cloud/non-OnPrem - table 372 "Payment Buffer" - CopyFieldsFromVendorLedgerEntry() and CopyFieldsToGenJournalLine()

### ISSUE THREAD

**Issue by db-bc** [microsoft/ALAppExtensions#13246]
These two procedures are marked as for `OnPrem` use only, but it's not at all clear why that should be the case, as all they do is copy some field values. Please can you remove that `Scope` so that SaaS extensions can use these?

I noticed this while having to copy-and-paste `report 393 "Suggest Vendor Payments"` (for unrelated reasons, for which I'll also request events), and I'll have to copy-and-paste these functions too until they are available outwith `OnPrem`.

Thanks!

code:
```al
    [Scope('OnPrem')]
    procedure CopyFieldsFromVendorLedgerEntry(VendorLedgerEntry: Record "Vendor Ledger Entry")
    begin
        "Creditor No." := VendorLedgerEntry."Creditor No.";
        "Payment Reference" := VendorLedgerEntry."Payment Reference";
        "Exported to Payment File" := VendorLedgerEntry."Exported to Payment File";
        "Applies-to Ext. Doc. No." := VendorLedgerEntry."External Document No.";

        OnCopyFieldsFromVendorLedgerEntry(VendorLedgerEntry, Rec);
    end;

    [Scope('OnPrem')]
    procedure CopyFieldsToGenJournalLine(var GenJournalLine: Record "Gen. Journal Line")
    begin
        GenJournalLine."Creditor No." := "Creditor No.";
        GenJournalLine."Payment Reference" := "Payment Reference";
        GenJournalLine."Exported to Payment File" := "Exported to Payment File";
        GenJournalLine."Applies-to Ext. Doc. No." := "Applies-to Ext. Doc. No.";

        OnCopyFieldsToGenJournalLine(Rec, GenJournalLine);
    end;
```

errors:
![image](https://user-images.githubusercontent.com/63455896/125630945-213feca9-a74a-4281-8b68-cacfa18aafd6.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
