### ISSUE TITLE
[Event Request] codeunit 6638 "Sales-Get Return Receipts" - OnCreateCrMemoLinesOnBeforeFind

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13247]
We would like to add a new event OnCreateCrMemoLinesOnBeforeFind in the following procedure:

    procedure CreateInvLines(var ReturnRcptLine2: Record "Return Receipt Line")
    var
        DifferentCurrencies: Boolean;
        TransferThisLine: Boolean;
    begin
        with ReturnRcptLine2 do begin
            SetFilter("Return Qty. Rcd. Not Invd.", '<>0');
            OnCreateCrMemoLinesOnBeforeFind(ReturnRcptLine2); //A108F0019.Event
            if Find('-') then begin
                SalesLine.LockTable();
                SalesLine.SetRange("Document Type", SalesHeader."Document Type");
                SalesLine.SetRange("Document No.", SalesHeader."No.");
                SalesLine."Document Type" := SalesHeader."Document Type";
                SalesLine."Document No." := SalesHeader."No.";

                repeat
                    if ReturnRcptHeader."No." <> "Document No." then begin
                        ReturnRcptHeader.Get("Document No.");
                        ReturnRcptHeader.TestField("Bill-to Customer No.", "Bill-to Customer No.");
                        DifferentCurrencies := false;
                        if ReturnRcptHeader."Currency Code" <> SalesHeader."Currency Code" then begin
                            Message(Text001,
                              SalesHeader.FieldCaption("Currency Code"),
                              SalesHeader.TableCaption, SalesHeader."No.",
                              ReturnRcptHeader.TableCaption, ReturnRcptHeader."No.");
                            DifferentCurrencies := true;
                        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnCreateCrMemoLinesOnBeforeFind(var ReturnReceiptLine: Record "Return Receipt Line")
    begin
        //A108F0019.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
