### ISSUE TITLE
[Event Request] codeunit 99000833 "Req. Line-Reserve" - OnBeforeCheckSellToCustomerNo

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13241]
We would like to add a new event OnBeforeCheckSellToCustomerNo in the following procedure:

    procedure Caption(ReqLine: Record "Requisition Line") CaptionText: Text
.
.
.

        if NewReqLine."Sales Order Line No." <> 0 then
            if ShowError then
                NewReqLine.FieldError("Sales Order Line No.", Text003)
            else
                HasError := true;

        //A114F0000.Event.ns
        IsHandled := false;
        OnBeforeCheckSellToCustomerNo(NewReqLine, OldReqLine, IsHandled);
        //A114F0000.Event.ne
        //if NewReqLine."Sell-to Customer No." <> '' then A114F0000.o
        if (NewReqLine."Sell-to Customer No." <> '') and not IsHandled then //A114F0000.Event.n
            if ShowError then
                NewReqLine.FieldError("Sell-to Customer No.", Text003)
            else
                HasError := true;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckSellToCustomerNo(var NewRequisitionLine: Record "Requisition Line"; var OldRequisitionLine: Record "Requisition Line"; var IsHandled: Boolean)
    begin
        //A114F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
