### ISSUE TITLE
[Event Request] codeunit 6638 "Sales-Get Return Receipts" - OnBeforeTransferLineToSalesDocLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13248]
We would like to add a new event OnBeforeTransferLineToSalesDocLine in the following procedure: 

    procedure CreateInvLines(var ReturnRcptLine2: Record "Return Receipt Line")
.
.
.

                    end;
                    //A108F0019.Event.ns
                    TransferThisLine := true;
                    OnBeforeTransferLineToSalesDocLine(ReturnRcptHeader, ReturnRcptLine2, SalesHeader, TransferThisLine);
                    if TransferThisLine then
                    //A108F0019.Event.ne
                    if not DifferentCurrencies then begin
                        ReturnRcptLine := ReturnRcptLine2;
                        ReturnRcptLine.TestField("VAT Bus. Posting Group", SalesHeader."VAT Bus. Posting Group"); //A108F0019.n
                        ReturnRcptLine.InsertInvLineFromRetRcptLine(SalesLine);
                        if Type = Type::"Charge (Item)" then
                            GetItemChargeAssgnt(ReturnRcptLine2, SalesLine."Qty. to Invoice");
                    end;

Event Signature:

   [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferLineToSalesDocLine(var ReturnReceiptHeader: Record "Return Receipt Header"; var ReturnReceiptLine: Record "Return Receipt Line"; var SalesHeader: Record "Sales Header"; var TransferLine: Boolean)
    begin
        //A108F0019.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
