### ISSUE TITLE
[Event Request] codeunit 99000845 "Reservation Management" - OnAfterModifyDocumentReservationEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13244]
We would like to add a new event OnAfterModifyDocumentReservationEntry in the following procedure:

    procedure DeleteDocumentReservation(TableID: Integer; DocType: Option; DocNo: Code[20]; HideValidationDialog: Boolean)
.
.
.

        if ReservEntry.FindSet() then
            repeat
                ReservEntry2 := ReservEntry;
                ReservEntry2.ClearItemTrackingFields();
                ReservEntry2.Modify();
                OnAfterModifyDocumentReservationEntry(ReservEntry); //A200F0000.Event
            until ReservEntry.Next() = 0;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterModifyDocumentReservationEntry(var ReservationEntry: Record "Reservation Entry")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
