### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnBeforePostItemChargePerTransferReceiptLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13240]
We would like to add a new event OnBeforePostItemChargePerTransferReceiptLine in the following procedure:

    local procedure PostItemChargePerTransfer(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line")
.
.
.

    begin
        with TempItemChargeAssgntPurch do begin
            TransRcptLine.Get("Applies-to Doc. No.", "Applies-to Doc. Line No.");
            PurchLine2 := PurchLine;
            PurchLine2."No." := "Item No.";
            PurchLine2."Variant Code" := TransRcptLine."Variant Code";
            PurchLine2."Location Code" := TransRcptLine."Transfer-to Code";
            PurchLine2."Bin Code" := '';
            PurchLine2."Line No." := "Document Line No.";
            OnBeforePostItemChargePerTransferReceiptLine(TransRcptLine, PurchLine2); //A108F0086.Event

            if TransRcptLine."Item Rcpt. Entry No." = 0 then
                PostItemChargePerITTransfer(PurchHeader, PurchLine, TransRcptLine)
            else begin
                TotalAmountToPostFCY := "Amount to Assign";
                if PurchHeader."Currency Code" <> '' then
                    TotalAmountToPostLCY :=
                      CurrExchRate.ExchangeAmtFCYToLCY(
                        Usedate, PurchHeader."Currency Code",
                        TotalAmountToPostFCY, PurchHeader."Currency Factor")
                else

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostItemChargePerTransferReceiptLine(TransferReceiptLine: Record "Transfer Receipt Line"; var PurchaseLine: Record "Purchase Line")
    begin
        //A108F0086.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
