### ISSUE TITLE
[Event Request] codeunit 60 "Sales-Calc. Discount" - OnBeforeCalculateServiceCharge

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13245]
We would like to add a new event OnBeforeCalculateServiceCharge in the following procedure:

    local procedure CalculateInvoiceDiscount(var SalesHeader: Record "Sales Header"; var SalesLine2: Record "Sales Line")

            if SalesHeader."Posting Date" = 0D then
                CurrencyDate := WorkDate
            else
                CurrencyDate := SalesHeader."Posting Date";

            CustInvDisc.GetRec(
              SalesHeader."Invoice Disc. Code", SalesHeader."Currency Code", CurrencyDate, ChargeBase);

            //A108B0103.ns
            if SkipServiceCostLine then
                CustInvDisc."Service Charge" := 0;
            //A108B0103.ne
            OnBeforeCalculateServiceCharge(CustInvDisc, SalesHeader); //A108F0020.Event
            if CustInvDisc."Service Charge" <> 0 then begin
                OnCalculateInvoiceDiscountOnBeforeCurrencyInitialize(CustPostingGr);
                Currency.Initialize(SalesHeader."Currency Code");
                if not UpdateHeader then
                    SalesLine2.SetSalesHeader(SalesHeader);
                if not TempServiceChargeLine.IsEmpty() then begin
                    TempServiceChargeLine.FindLast;
                    SalesLine2.Get("Document Type", "Document No.", TempServiceChargeLine."Line No.");
                    SetSalesLineServiceCharge(SalesHeader, SalesLine2);
                    SalesLine2.Modify();
                end else begin

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculateServiceCharge(var CustInvoiceDisc: Record "Cust. Invoice Disc."; var SalesHeader: Record "Sales Header")
    begin
        //A108F0020.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
