### ISSUE TITLE
event requests - report 393 Suggest Vendor Payments - OnBeforeIncludeVendor() and OnBeforeClearNegative()

### ISSUE THREAD

**Issue by db-bc** [microsoft/ALAppExtensions#13257]
We would like to provide an option to include vendors with credit balances in the payment suggestion. Therefore, can we please:

*** 

(1) replace the various bits of code that do something like this:

```al
                CalcFields("Balance (LCY)");
                VendorBalance := "Balance (LCY)";

                if VendorBalance > 0 then begin
                    GetVendLedgEntries(true, false);
                    GetVendLedgEntries(false, false);
                    CheckAmounts(false);
                    ClearNegative;
                end;
```

specifically, in each, replace

```al
                if VendorBalance > 0 then begin
```

with

```al
                if IncludeVendor(Vendor, VendorBalance) then begin
```

where this new function would look like

```al
local procedure IncludeVendor(Vendor: Record Vendor; VendorBalance: Decimal) Result: Boolean
var
    IsHandled: Boolean;
begin
    OnBeforeIncludeVendor(Vendor, VendorBalance, IsHandled, Result);

    if not IsHandled then
        exit(VendorBalance > 0);
end;
```

calling an event like

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeIncludeVendor(Vendor: Record Vendor; VendorBalance: Decimal; var IsHandled: Boolean; var Result: Boolean)
```

***

(2) This alone is not enough; we then also need to suppress `ClearNegative()` so that as well as not ignoring Vendors with credit Balance (LCY), we don't then regardless delete their temp entries per currency in credit. So, add here:

```al
    local procedure ClearNegative()
    var
        TempCurrency: Record Currency temporary;
        PayableVendLedgEntry2: Record "Payable Vendor Ledger Entry" temporary;
        CurrencyBalance: Decimal;
        IsHandled: Boolean;
    begin
        OnBeforeClearNegative(IsHandled);

        if IsHandled then
            exit;

        [...]
```

where that new event will be

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeClearNegative(var IsHandled: Boolean)
```

***

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
