### ISSUE TITLE
[Event Request] codeunit 64 "Sales-Get Shipment" - OnBeforeTransferLineToSalesDocLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13250]
We would like to add a new event OnBeforeTransferLineToSalesDocLine in the following procedure:

    procedure CreateInvLines(var SalesShptLine2: Record "Sales Shipment Line")
.
.
.

                    end;
                    //A108F0019.Event.ns
                    TransferThisLine := true;
                    OnBeforeTransferLineToSalesDocLine(SalesShptHeader, SalesShptLine2, SalesHeader, TransferLine);
                    if TransferThisLine then
                        //A108F0019.Event.ne
                        if TransferLine then begin
                            SalesShptLine := SalesShptLine2;
                            SalesShptLine.InsertInvLineFromShptLine(SalesLine);
                            CalcUpdatePrepmtAmtToDeductRounding(SalesShptLine, SalesLine, PrepmtAmtToDeductRounding);
                        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferLineToSalesDocLine(SalesShipmentHeader: Record "Sales Shipment Header"; SalesShipmentLine: Record "Sales Shipment Line"; var SalesHeader: Record "Sales Header"; var TransferLine: Boolean)
    begin
        //A108F0019.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
