### ISSUE TITLE
[Event Request] codeunit 7324 "Whse.-Activity-Post" - OnAfterSetPurchaseLineFilters

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13258]
We would like to add a new event OnAfterSetPurchaseLineFilters in the following procedure:

    local procedure InitSourceDocument()
    var
        SalesLine: Record "Sales Line";
        ModifyHeader: Boolean;
        IsHandled: Boolean;
    begin
        OnBeforeInitSourceDocument(WhseActivHeader);

        with WhseActivHeader do
            case "Source Type" of
                DATABASE::"Purchase Line":
                    begin
                        PurchHeader.Get("Source Subtype", "Source No.");
                        PurchLine.SetRange("Document Type", "Source Subtype");
                        PurchLine.SetRange("Document No.", "Source No.");
                        OnAfterSetPurchaseLineFilters(PurchLine, PurchHeader, WhseActivHeader); //A108B0056.Event
                        if PurchLine.Find('-') then
                            repeat
                                if "Source Document" = "Source Document"::"Purchase Order" then
                                    PurchLine.Validate("Qty. to Receive", 0)
                                else
                                    PurchLine.Validate("Return Qty. to Ship", 0);
                                PurchLine.Validate("Qty. to Invoice", 0);
                                ModifyPurchaseLine(PurchLine);
                                OnAfterPurchLineModify(PurchLine);
                            until PurchLine.Next() = 0;

                        ReleasePurchDocument(ModifyHeader);

                        if "External Document No." <> '' then begin
                            PurchHeader."Vendor Shipment No." := "External Document No.";
                            ModifyHeader := true;
                        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetPurchaseLineFilters(var PurchaseLine: Record "Purchase Line"; PurchaseHeader: Record "Purchase Header"; WarehouseActivityHeader: Record "Warehouse Activity Header");
    begin
        //A108B0056.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
