### ISSUE TITLE
[Event Request] codeunit 7150 "Update Item Analysis View" - OnAfterInitItemAnalysisViewBudgetEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13253]
We would like to add a new event OnAfterInitItemAnalysisViewBudgetEntry in the following procedure:

    local procedure UpdateAnalysisViewBudgetEntry(DimValue1: Code[20]; DimValue2: Code[20]; DimValue3: Code[20])
    begin
        TempItemAnalysisViewBudgEntry."Analysis Area" := ItemAnalysisView."Analysis Area";
        TempItemAnalysisViewBudgEntry."Analysis View Code" := ItemAnalysisView.Code;
        TempItemAnalysisViewBudgEntry."Budget Name" := ItemBudgetEntry."Budget Name";
        TempItemAnalysisViewBudgEntry."Location Code" := ItemBudgetEntry."Location Code";
        TempItemAnalysisViewBudgEntry."Item No." := ItemBudgetEntry."Item No.";
        TempItemAnalysisViewBudgEntry."Source Type" := ItemBudgetEntry."Source Type";
        TempItemAnalysisViewBudgEntry."Source No." := ItemBudgetEntry."Source No.";

        if ItemBudgetEntry.Date < ItemAnalysisView."Starting Date" then
            TempItemAnalysisViewBudgEntry."Posting Date" := ItemAnalysisView."Starting Date" - 1
        else begin
            TempItemAnalysisViewBudgEntry."Posting Date" :=
              CalculatePeriodStart(ItemBudgetEntry.Date, ItemAnalysisView."Date Compression");
            if TempItemAnalysisViewBudgEntry."Posting Date" < ItemAnalysisView."Starting Date" then
                TempItemAnalysisViewBudgEntry."Posting Date" := ItemAnalysisView."Starting Date";
        end;
        TempItemAnalysisViewBudgEntry."Dimension 1 Value Code" := DimValue1;
        TempItemAnalysisViewBudgEntry."Dimension 2 Value Code" := DimValue2;
        TempItemAnalysisViewBudgEntry."Dimension 3 Value Code" := DimValue3;
        TempItemAnalysisViewBudgEntry."Entry No." := ItemBudgetEntry."Entry No.";
        OnAfterInitItemAnalysisViewBudgetEntry(TempItemAnalysisViewBudgEntry, ItemBudgetEntry, ItemAnalysisView); //A102F0000.Event

        if TempItemAnalysisViewBudgEntry.Find then begin
            AddValue(TempItemAnalysisViewBudgEntry."Sales Amount", ItemBudgetEntry."Sales Amount");
            AddValue(TempItemAnalysisViewBudgEntry."Cost Amount", ItemBudgetEntry."Cost Amount");
            AddValue(TempItemAnalysisViewBudgEntry.Quantity, ItemBudgetEntry.Quantity);
            TempItemAnalysisViewBudgEntry.Modify();
        end else begin
            TempItemAnalysisViewBudgEntry."Sales Amount" := ItemBudgetEntry."Sales Amount";
            TempItemAnalysisViewBudgEntry."Cost Amount" := ItemBudgetEntry."Cost Amount";
            TempItemAnalysisViewBudgEntry.Quantity := ItemBudgetEntry.Quantity;
            TempItemAnalysisViewBudgEntry.Insert();
            NoOfEntries := NoOfEntries + 1;
        end;
        if NoOfEntries >= 10000 then
            FlushAnalysisViewBudgetEntry;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterInitItemAnalysisViewBudgetEntry(var ItemAnalysisViewBudgEntry: Record "Item Analysis View Budg. Entry"; var ItemBudgetEntry: Record "Item Budget Entry"; var ItemAnalysisView: Record "Item Analysis View")
    begin
        //A102F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
