### ISSUE TITLE
[Event Request] codeunit 7324 "Whse.-Activity-Post" - OnAfterSetSalesLineFilters

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13259]
We would like to add a new event OnAfterSetSalesLineFilters in the following procedure: 

    local procedure InitSourceDocument()
.
.
.

                    begin
                        SalesHeader.Get("Source Subtype", "Source No.");
                        SalesLine.SetRange("Document Type", "Source Subtype");
                        SalesLine.SetRange("Document No.", "Source No.");
                        if SalesHeader."Shipping Advice" = SalesHeader."Shipping Advice"::Complete then
                            SalesLine.SetRange(Type, SalesLine.Type::Item);
                        OnAfterSetSalesLineFilters(SalesLine, SalesHeader, WhseActivHeader); //A108B0056.Event
                        if SalesLine.Find('-') then
                            repeat
                                IsHandled := false;
                                OnInitSourceDocumentOnBeforeSalesLineLoopIteration(SalesHeader, SalesLine, WhseActivHeader, IsHandled);
                                if not IsHandled then begin
                                    if "Source Document" = "Source Document"::"Sales Order" then
                                        SalesLine.Validate("Qty. to Ship", 0)
                                    else
                                        SalesLine.Validate("Return Qty. to Receive", 0);
                                    SalesLine.Validate("Qty. to Invoice", 0);
                                    ModifySalesLine(SalesLine);
                                    OnAfterSalesLineModify(SalesLine);
                                end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetSalesLineFilters(var SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header"; WarehouseActivityHeader: Record "Warehouse Activity Header");
    begin
        //A108B0056.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
