### ISSUE TITLE
Code change request - IF wrapper

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#1325]
We are trying to port a popular NAV add-on to an extension, and are hitting a number of roadblocks.  Here's the latest one...

We would like to request a small code change to the GetDimensionSet function in Codeunit 408.  There is currently a line in that function for:

        TempDimSetEntry.INSERT;

We need this changed to:

        IF TempDimSetEntry.INSERT THEN;

Basically, this call is preventing our functionality from working.  We have logic that populates dimension value(s) based on OTHER dimension values.  Because our logic may have already triggered the addition of another dimension value to the dimension set, the INSERT above is erroring out because the record already exists.  In the NAV version of our product we made the code change above and it works great...but of course we have no way to do that in an extension.

**Comment by RHansenEpimatic** [comment]
I found a way to work around this...but it's a bit ugly.  It would be cleaner with my suggested change, but if you don't want to make the change i'll be okay.

**Comment by JesperSchulz** [comment]
If you found a workaround, we would prefer to prioritize other issues for which there are no workarounds yet. Thank you for reporting! If this comes up again at a later time, please log again and we'll look more closely into it.
