### ISSUE TITLE
[Event Request] codeunit 7324 "Whse.-Activity-Post" - OnInitItemJournalLineOnPostOutputLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13255]
We would like to add a new event OnInitItemJournalLineOnPostOutputLine in the following procedure:

    local procedure PostOutputLine(ProdOrder: Record "Production Order"; ProdOrderLine: Record "Prod. Order Line")
    var
        ItemJnlLine: Record "Item Journal Line";
        ItemJnlPostLine: Codeunit "Item Jnl.-Post Line";
        ReservProdOrderLine: Codeunit "Prod. Order Line-Reserve";
    begin
        with TempWhseActivLine do begin
            ItemJnlLine.Init();
            OnInitItemJournalLineOnPostOutputLine(ItemJnlLine, SourceCodeSetup); //A108B0045.Event
            ItemJnlLine.Validate("Entry Type", ItemJnlLine."Entry Type"::Output);
            ItemJnlLine.Validate("Posting Date", WhseActivHeader."Posting Date");
            ItemJnlLine."Document No." := ProdOrder."No.";
            ItemJnlLine.Validate("Order Type", ItemJnlLine."Order Type"::Production);
            ItemJnlLine.Validate("Order No.", ProdOrder."No.");
            ItemJnlLine.Validate("Order Line No.", ProdOrderLine."Line No.");
            ItemJnlLine.Validate("Routing Reference No.", ProdOrderLine."Routing Reference No.");
            ItemJnlLine.Validate("Routing No.", ProdOrderLine."Routing No.");
            ItemJnlLine.Validate("Item No.", ProdOrderLine."Item No.");
            if ItemJnlLine."Unit of Measure Code" <> "Unit of Measure Code" then
                ItemJnlLine.Validate("Unit of Measure Code", "Unit of Measure Code");
            ItemJnlLine."Qty. per Unit of Measure" := "Qty. per Unit of Measure";
            ItemJnlLine."Location Code" := "Location Code";
            ItemJnlLine."Bin Code" := "Bin Code";
            ItemJnlLine."Variant Code" := "Variant Code";
            ItemJnlLine.Description := Description;
            if ProdOrderLine."Routing No." <> '' then
                ItemJnlLine.Validate("Operation No.", CalcLastOperationNo(ProdOrderLine));
            ItemJnlLine.Validate("Output Quantity", "Qty. to Handle");
            ItemJnlLine."Source Code" := SourceCodeSetup."Output Journal";
            ItemJnlLine."Dimension Set ID" := ProdOrderLine."Dimension Set ID";
            OnPostOutputLineOnAfterCreateItemJnlLine(ItemJnlLine, ProdOrderLine, TempWhseActivLine);
            ReservProdOrderLine.TransferPOLineToItemJnlLine(
              ProdOrderLine, ItemJnlLine, ItemJnlLine."Quantity (Base)");
            ItemJnlPostLine.SetCalledFromInvtPutawayPick(true);
            ItemJnlPostLine.RunWithCheck(ItemJnlLine);
            ReservProdOrderLine.UpdateItemTrackingAfterPosting(ProdOrderLine);
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnInitItemJournalLineOnPostOutputLine(var ItemJournalLine: Record "Item Journal Line"; SourceCodeSetup: Record "Source Code Setup")
    begin
        //A108B0045.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
