### ISSUE TITLE
[Event Request] codeunit 5803 "Show Avg. Calc. - Item" - OnAfterSetValueEntryFilters

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13252]
We would like to add a new event OnAfterSetValueEntryFilters in the following trigger:

    trigger OnRun()
    var
        ValueEntry: Record "Value Entry";
    begin
        with ValueEntry do begin
            SetCurrentKey("Item No.", "Valuation Date", "Location Code", "Variant Code");
            SetRange("Item No.", Rec."No.");
            SetFilter("Valuation Date", Rec.GetFilter("Date Filter"));
            SetFilter("Location Code", Rec.GetFilter("Location Filter"));
            SetFilter("Variant Code", Rec.GetFilter("Variant Filter"));
            OnAfterSetValueEntryFilters(ValueEntry, Rec); //A200F0002.Event
        end;
        PAGE.RunModal(PAGE::"Value Entries", ValueEntry, ValueEntry."Cost Amount (Actual)");
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetValueEntryFilters(ValueEntry: Record "Value Entry"; var Item: Record Item)
    begin
        //A200F0002.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
