### ISSUE TITLE
[Event Request] codeunit 5057 "VendCont-Update" - OnAfterTransferFieldsNewContactFromVendor

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13254]
We would like to add a new event OnAfterTransferFieldsNewContactFromVendor in the following procedure:

    procedure InsertNewContact(var Vend: Record Vendor; LocalCall: Boolean)
    var
        Cont: Record Contact;
        ContBusRel: Record "Contact Business Relation";
        NoSeriesMgt: Codeunit NoSeriesManagement;
        IsHandled: Boolean;
        OldCont: Record Contact;
    begin
        IsHandled := false;
        OnBeforeInsertNewContact(Vend, LocalCall, IsHandled);
        if IsHandled then
            exit;

        if not LocalCall then begin
            RMSetup.Get();
            RMSetup.TestField("Bus. Rel. Code for Vendors");
        end;

        if ContBusRel.UpdateEmptyNoForContact(Vend."No.", Vend."Primary Contact No.", ContBusRel."Link to Table"::Vendor) then
            exit;

        with Cont do begin
            Init;
            TransferFields(Vend);
            //OnAfterTransferFieldsFromVendToCont(Cont,Vend); A113F0002.Event.o
            OnAfterTransferFieldsFromVendToCont(Cont, OldCont, Vend); //A113F0002.Event.n
            OnAfterTransferFieldsNewContactFromVendor(Cont, Vend, RMSetup, LocalCall); //A113F0002.Event
            Validate(Name);
            Validate("E-Mail");
            IsHandled := false;
            OnInsertNewContactOnBeforeAssignNo(Cont, IsHandled, Vend);
            if RMSetup."Contact Nos." <> "No. Series" then //A108F0049.n
	    
            if not IsHandled then begin
                "No." := '';
                "No. Series" := '';
                RMSetup.TestField("Contact Nos.");
                NoSeriesMgt.InitSeries(RMSetup."Contact Nos.", '', 0D, "No.", "No. Series");
            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterTransferFieldsNewContactFromVendor(var Contact: Record Contact; Vendor: Record Vendor; MarketingSetup: Record "Marketing Setup"; LocalCall: Boolean)
    begin
        //A113F0002.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
