### ISSUE TITLE
[Event Request] codeunit 7324 "Whse.-Activity-Post" - OnInitItemJournalLineOnPostConsumptionLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13256]
We would like to add a new event OnInitItemJournalLineOnPostConsumptionLine in the following procedure:

    local procedure PostConsumptionLine(ProdOrder: Record "Production Order"; ProdOrderComp: Record "Prod. Order Component")
    var
        ItemJnlLine: Record "Item Journal Line";
        ProdOrderLine: Record "Prod. Order Line";
        ItemJnlPostLine: Codeunit "Item Jnl.-Post Line";
        ProdOrderCompReserve: Codeunit "Prod. Order Comp.-Reserve";
    begin
        with TempWhseActivLine do begin
            ProdOrderLine.Get("Source Subtype", "Source No.", "Source Line No.");
            ItemJnlLine.Init();
            OnInitItemJournalLineOnPostConsumptionLine(ItemJnlLine, SourceCodeSetup); //A108B0045.Event
            ItemJnlLine.Validate("Entry Type", ItemJnlLine."Entry Type"::Consumption);
            ItemJnlLine.Validate("Posting Date", WhseActivHeader."Posting Date");
            ItemJnlLine."Source No." := ProdOrderLine."Item No.";
            ItemJnlLine."Source Type" := ItemJnlLine."Source Type"::Item;
            ItemJnlLine."Document No." := ProdOrder."No.";
            ItemJnlLine.Validate("Order Type", ItemJnlLine."Order Type"::Production);
            ItemJnlLine.Validate("Order No.", ProdOrder."No.");
            ItemJnlLine.Validate("Order Line No.", ProdOrderLine."Line No.");
            ItemJnlLine.Validate("Item No.", "Item No.");
            if ItemJnlLine."Unit of Measure Code" <> "Unit of Measure Code" then
                ItemJnlLine.Validate("Unit of Measure Code", "Unit of Measure Code");
            ItemJnlLine.Validate("Prod. Order Comp. Line No.", ProdOrderComp."Line No.");
            ItemJnlLine."Qty. per Unit of Measure" := "Qty. per Unit of Measure";
            ItemJnlLine.Description := Description;
            if "Activity Type" = "Activity Type"::"Invt. Pick" then
                ItemJnlLine.Validate(Quantity, "Qty. to Handle")
            else
                ItemJnlLine.Validate(Quantity, -"Qty. to Handle");
            ItemJnlLine.Validate("Unit Cost", ProdOrderComp."Unit Cost");
            ItemJnlLine."Location Code" := "Location Code";
            ItemJnlLine."Bin Code" := "Bin Code";
            ItemJnlLine."Variant Code" := "Variant Code";
            ItemJnlLine."Source Code" := SourceCodeSetup."Consumption Journal";
            ItemJnlLine."Gen. Bus. Posting Group" := ProdOrder."Gen. Bus. Posting Group";
            GetItem("Item No.");
            ItemJnlLine."Gen. Prod. Posting Group" := Item."Gen. Prod. Posting Group";
            OnPostConsumptionLineOnAfterCreateItemJnlLine(ItemJnlLine, ProdOrderLine, WhseActivLine);
            ProdOrderCompReserve.TransferPOCompToItemJnlLineCheckILE(ProdOrderComp, ItemJnlLine, ItemJnlLine."Quantity (Base)", true);
            ItemJnlPostLine.SetCalledFromInvtPutawayPick(true);
            ItemJnlPostLine.RunWithCheck(ItemJnlLine);
            ProdOrderCompReserve.UpdateItemTrackingAfterPosting(ProdOrderComp);
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnInitItemJournalLineOnPostConsumptionLine(var ItemJournalLine: Record "Item Journal Line"; SourceCodeSetup: Record "Source Code Setup")
    begin
        //A108B0045.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
