### ISSUE TITLE
[Event Request] codeunit 99000832 "Sales Line-Reserve" - OnBeforeTransferReservationEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13251]
We would like to add a new event OnBeforeTransferReservationEntry in the following procedure:

    procedure TransferSalesLineToItemJnlLine(var SalesLine: Record "Sales Line"; var ItemJnlLine: Record "Item Journal Line"; TransferQty: Decimal; var CheckApplFromItemEntry: Boolean; OnlyILEReservations: Boolean): Decimal
.
.
.

                end;
                //A200F0001.ne
                //A109F0006.event.ns
                IsHandled := false;
                OnBeforeTransferReservationEntry(OldReservEntry, SalesLine, ItemJnlLine, IsHandled);
                if not IsHandled then
                    //A109F0006.event.ne
                    if not (ItemJnlLine."Assemble to Order" xor OldReservEntry."Disallow Cancellation") then
                        if not VerifyPickedQtyReservToInventory(OldReservEntry, SalesLine, TransferQty) then
                            if OnlyILEReservations and OppositeReservEntry.Get(OldReservEntry."Entry No.", not OldReservEntry.Positive) then begin
                                if OppositeReservEntry."Source Type" = DATABASE::"Item Ledger Entry" then
                                    TransferQty := CreateReservEntry.TransferReservEntry(
                                        DATABASE::"Item Journal Line", ItemJnlLine."Entry Type".AsInteger(), ItemJnlLine."Journal Template Name",
                                        ItemJnlLine."Journal Batch Name", 0, ItemJnlLine."Line No.",
                                        ItemJnlLine."Qty. per Unit of Measure", OldReservEntry, TransferQty);
                            end else
                                TransferQty := CreateReservEntry.TransferReservEntry(
                                    DATABASE::"Item Journal Line", ItemJnlLine."Entry Type".AsInteger(), ItemJnlLine."Journal Template Name",
                                    ItemJnlLine."Journal Batch Name", 0, ItemJnlLine."Line No.",
                                    ItemJnlLine."Qty. per Unit of Measure", OldReservEntry, TransferQty);
            until (ReservEngineMgt.NEXTRecord(OldReservEntry) = 0) or (TransferQty = 0);
            CheckApplFromItemEntry := CheckApplFromItemEntry and NotFullyReserved;
        end;
        exit(TransferQty);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferReservationEntry(var ReservationEntry: Record "Reservation Entry"; SalesLine: Record "Sales Line"; ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean);
    begin
        //A109F0006.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
