### ISSUE TITLE
EventPublisher request / change needed urgently - Contact table (OnBeforeBankAccountInsert) is missing Rec.

### ISSUE THREAD

**Issue by eque2al** [microsoft/ALAppExtensions#13261]
As per title the publisher event OnBeforeBankAccountInsert on the Contact table only contains the BankAccount record and it must contain the BankAccount and Contact (Rec) record to be useful.

Please can you let me know urgently which release this will be targeted for?

This will stop some of our development until it is resolved.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
