### ISSUE TITLE
[Event Change Request] Table 5050 Contact - OnBeforeProcessPersonNameChange event parameters

### ISSUE THREAD

**Issue by ViktorasDanielius** [microsoft/ALAppExtensions#13266]
Please add parameters to Table 5050 Contatc OnBeforeProcessPersonNameChange event which is called from ProcessPersonNameChange function. Currently it doesn't have any parameters and there is no use of it. I think Rec, Customer and Vendor should be added.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
