### ISSUE TITLE
[Event Request] Report 292 "Copy Sales Document" OnAfterValidateIncludeHeaderField

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#13268]
We would like to access the IncludeHeader Variable in report 292 after it is validated by a user.
Therefore, we need a new Publisher:
![image](https://user-images.githubusercontent.com/34675109/125764570-32f0cf62-9837-4dd1-824a-f6f43f845cae.png)
The "IncludeSender" property is important for us in this case.
I called it "Field" at the end because of the existing Publisher in the ValidateDocNo procedure.

Thanks

**Comment by Oleg-Romashkov** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
