### ISSUE TITLE
[Access Request] protected var - report 1308 "Standard Sales - Shipment"

### ISSUE THREAD

**Issue by TriangleSPV** [microsoft/ALAppExtensions#13267]
In the report 1303 we need to print the Expiration date in the Serial/Lot Number Appendix.
To do it with a report extension, we need access to the variable TempTrackingSpecBuffer which must be protected.

The same request shoud be applied in all the similar document reports.

Another option is that you show this field as a standard column in the Serial/Lot Number Appendix.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
