### ISSUE TITLE
[Event Request] codeunit 5005272 "Deliv.-Rem. Ext. Text Transfer"

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#13269]
Can you please provide those two publishers. (Code and publishers should be similiar like in codeunit 378 "Transfer Extended Text")

    procedure ReminderCheckIfAnyExtText(var DeliveryReminderLine: Record "Delivery Reminder Line"; Unconditionally: Boolean): Boolean
    var
        DeliveryReminder: Record "Delivery Reminder Header";
        ExtTextHeader: Record "Extended Text Header";
    begin
        MakeUpdateRequired := false;
        if DeliveryReminderLine."Line No." <> 0 then
            MakeUpdateRequired := DeleteDellivReminLine(DeliveryReminderLine);

        if Unconditionally then
            AutoText := true
        else
            case DeliveryReminderLine.Type of
                DeliveryReminderLine.Type::" ":
                    AutoText := true;
                DeliveryReminderLine.Type::"Account (G/L)":
                    if GLAcc.Get(DeliveryReminderLine."No.") then
                        AutoText := GLAcc."Automatic Ext. Texts";
            end;

        if AutoText then begin
            DeliveryReminderLine.TestField("Document No.");
            DeliveryReminder.Get(DeliveryReminderLine."Document No.");
            ExtTextHeader.SetRange("Table Name", DeliveryReminderLine.Type);
            ExtTextHeader.SetRange("No.", DeliveryReminderLine."No.");
            ExtTextHeader.SetRange("Delivery Reminder", true);
            // -NEW
            OnDeliveryReminderCheckIfAnyExtTextAutoText(ExtTextHeader, DeliveryReminder, DeliveryReminderLine, Unconditionally, MakeUpdateRequired);
            // +NEW
            exit(ReadLines(ExtTextHeader, DeliveryReminder."Document Date", DeliveryReminder."Language Code"));
        end;
    end;

    local procedure ReadLines(var ExtTextHeader: Record "Extended Text Header"; DocDate: Date; LanguageCode: Code[10]): Boolean
    var
        ExtTextLine: Record "Extended Text Line";
    begin
        ExtTextHeader.SetCurrentKey(
          "Table Name", "No.", "Language Code", "All Language Codes", "Starting Date", "Ending Date");
        ExtTextHeader.SetRange("Starting Date", 0D, DocDate);
        ExtTextHeader.SetFilter("Ending Date", '%1..|%2', DocDate, 0D);
        if LanguageCode = '' then begin
            ExtTextHeader.SetRange("Language Code", '');
            if not ExtTextHeader.Find('+') then
                exit;
        end else begin
            ExtTextHeader.SetRange("Language Code", LanguageCode);
            if not ExtTextHeader.Find('+') then begin
                ExtTextHeader.SetRange("All Language Codes", true);
                ExtTextHeader.SetRange("Language Code", '');
                if not ExtTextHeader.Find('+') then
                    exit;
            end;
        end;

        ExtTextLine.SetRange("Table Name", ExtTextHeader."Table Name");
        ExtTextLine.SetRange("No.", ExtTextHeader."No.");
        ExtTextLine.SetRange("Language Code", ExtTextHeader."Language Code");
        ExtTextLine.SetRange("Text No.", ExtTextHeader."Text No.");
        if ExtTextLine.Find('-') then begin
            TmpExtTextLine.DeleteAll();
            repeat
                TmpExtTextLine := ExtTextLine;
                TmpExtTextLine.Insert();
            until ExtTextLine.Next() = 0;
            exit(true);
        end;
        // -NEW
        OnAfterReadLines(TmpExtTextLine, ExtTextHeader, LanguageCode);
        // +NEW
    end;

    // -NEW
    [IntegrationEvent(false, false)]
    local procedure OnDeliveryReminderCheckIfAnyExtTextAutoText(var ExtendedTextHeader: Record "Extended Text Header"; var DeliveryReminderHeader: Record "Delivery Reminder Header"; var DeliveryReminderLine: Record "Delivery Reminder Line"; Unconditionally: Boolean; var MakeUpdateRequired: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterReadLines(var TempExtendedTextLine: Record "Extended Text Line" temporary; var ExtendedTextHeader: Record "Extended Text Header"; LanguageCode: Code[10])
    begin
    end;
    // +NEW

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
