### ISSUE TITLE
[Event Request] codeunit 7324 "Whse.-Activity-Post" - OnAfterSetTransferLineFilters 

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13260]
We would like to add a new event OnAfterSetTransferLineFilters in the following procedure:

                    begin
                        TransHeader.Get("Source No.");
                        TransLine.SetRange("Document No.", TransHeader."No.");
                        TransLine.SetRange("Derived From Line No.", 0);
                        TransLine.SetFilter("Item No.", '<>%1', '');
                        OnAfterSetTransferLineFilters(TransLine, TransHeader, WhseActivHeader); //A108B0056.Event                        
                        if TransLine.Find('-') then
                            repeat
                                TransLine.Validate("Qty. to Ship", 0);
                                TransLine.Validate("Qty. to Receive", 0);
                                ModifyTransferLine(TransLine);
                                OnAfterTransLineModify(TransLine);
                            until TransLine.Next() = 0;

                        ReleaseTransferDocument(ModifyHeader); //A109F0001.Event.n
                        //A109F0001.Event.os
                        //if (TransHeader."Posting Date" <> "Posting Date") and ("Posting Date" <> 0D) then begin
                        //    TransHeader.CalledFromWarehouse(true);
                        //    TransHeader.Validate("Posting Date", "Posting Date");
                        //    ModifyHeader := true;
                        //end;
                        //A109F0001.Event.oe
                        if "External Document No." <> '' then begin
                            TransHeader."External Document No." := "External Document No.";
                            ModifyHeader := true;
                        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetTransferLineFilters(var TransferLine: Record "Transfer Line"; TransferHeader: Record "Transfer Header"; WarehouseActivityHeader: Record "Warehouse Activity Header");
    begin
        //A108B0056.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
