### ISSUE TITLE
[Event Request] Codeunit 426 "Payment Tolerance Managemet" - OnAfterForLoopAppliedVendLedgEntry

### ISSUE THREAD

**Issue by rswaldia** [microsoft/ALAppExtensions#13265]
Request for new Event in Codeunit 426 inside CalcVendApplnAmount() function For loop.

            for i := 1 to 2 do begin
                if SetPositiveFilter then begin
                    if i = 2 then
                        AppliedVendLedgEntry.SetRange(Positive, PositiveFilter);
                end else
                    i := 2;

                with AppliedVendLedgEntry do begin ...
                end;
		// **OnAfterForLoopAppliedVendLedgEntry(AppliedVendLedgEntry)** ;
            end;
        end else
            if VendledgEntry."Applies-to Doc. No." <> '' then begin
                AppliedVendLedgEntry.SetCurrentKey("Vendor No.", Open);

**[IntegrationEvent(false, false)]
local procedure OnAfterForLoopAppliedVendLedgEntry(var AppliedVendLedgEntry: Record "Vendor Ledger Entry")
begin
end;**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
