### ISSUE TITLE
[Event Request] Codeunit 426 "Payment Tolerance Management" - OnAfterForLoopAppliedCustLedgEntry

### ISSUE THREAD

**Issue by rswaldia** [microsoft/ALAppExtensions#13263]
Request for new Event in Codeunit 426 inside CalcCustApplnAmount() function For loop.

            for i := 1 to 2 do begin
                if SetPositiveFilter then begin
                    if i = 2 then
                        AppliedCustLedgEntry.SetRange(Positive, not PositiveFilter);
                end else
                    i := 2;

                with AppliedCustLedgEntry do begin ...
                end;
		// **OnAfterForLoopAppliedCustLedgEntry(AppliedCustLedgEntry)** ;
            end;
        end else
            if CustledgEntry."Applies-to Doc. No." <> '' then begin
                AppliedCustLedgEntry.SetCurrentKey("Customer No.", Open);

    **[IntegrationEvent(false, false)]
    local procedure OnAfterForLoopAppliedCustLedgEntry(var AppliedCustLedgEntry: Record "Cust. Ledger Entry")
    begin
    end;**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
