### ISSUE TITLE
[Event Request] Codeunit 426 - Inside CalcCustApplnAmount() function

### ISSUE THREAD

**Issue by rswaldia** [microsoft/ALAppExtensions#13262]
Request for new Event in Codeunit 426 inside CalcCustApplnAmount() function.

            if AppliedCustLedgEntry.Find('-') then begin
                ApplyingAmount := CustledgEntry."Remaining Amount";
                TempAmount := CustledgEntry."Remaining Amount";
                AppliedCustLedgEntry.SetRange(Positive);
                AppliedCustLedgEntry.Find('-');
                repeat
                    // **OnBeforeUpdateCustAmountsForApplication(AppliedCustLedgEntry, CustledgEntry, AppliedCustLedgEntryTemp);** 
                    UpdateCustAmountsForApplication(AppliedCustLedgEntry, CustledgEntry, AppliedCustLedgEntryTemp);
                    CheckCustPaymentAmountsForAppliesToID(
                      CustledgEntry, AppliedCustLedgEntry, AppliedCustLedgEntryTemp, MaxPmtTolAmount, AvailableAmount, TempAmount,
                      ApplnRoundingPrecision);
                until AppliedCustLedgEntry.Next() = 0;

**[IntegrationEvent(false, false)] 
local procedure OnBeforeUpdateCustAmountsForApplication(var AppliedCustLedgEntry: Record "Cust. Ledger Entry"; var CustledgEntry: Record "Cust. Ledger Entry"; var AppliedCustLedgEntryTemp: Record "Cust. Ledger Entry" temporary )
    begin
    end;**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
