### ISSUE TITLE
[Event Request] table 5902 "Service Line" - OnBeforeApplyDiscount

### ISSUE THREAD

**Issue by PavlosPGP** [microsoft/ALAppExtensions#13274]
New Event OnBeforeApplyDiscount  in function "ApplyDiscount" as follows:

    procedure ApplyDiscount(ServiceHeader: Record "Service Header")
    var
        PriceCalculation: Interface "Price Calculation";
        PriceType: Enum "Price Type";
        IsHandled: Boolean;  //New Line
    begin
        // New Event -> Start
        IsHandled := false; 
        OnBeforeApplyDiscount(ServiceHeader, Rec, IsHandled);  
        if IsHandled then 
            exit;  
        // New Event <- End
        GetPriceCalculationHandler(PriceType::Sale, ServiceHeader, PriceCalculation);
        PriceCalculation.ApplyDiscount();
        GetLineWithCalculatedPrice(PriceCalculation);
    end;

Event Signature: 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeApplyDiscount(ServiceHeader: Record "Service Header"; var ServiceLine: Record "Service Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
