### ISSUE TITLE
[Event Request Change] codeunit 99000831 "Reservation Engine Mgt."

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#13277]
Can you please change publisher from InternalEvent to IntegrationEvent

    // -NEW
    //[InternalEvent(false]
    [IntegrationEvent(false, false)]
    // +NEW
    local procedure OnGetActivePointerFieldsOnBeforeAssignArrayValues(TableID: Integer; var PointerFieldIsActive: array[6] of Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
