### ISSUE TITLE
Bug Excel Buffer Function WriteAllToCurrentSheet

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#13278]
Hi,
I found a bug in the Excel Buffer table. 
Function WriteAllToCurrentSheet
In ExcelBuffer loop we check if the Formula is empty, but we need to check it in ExcelBuffer variable, not rec.
![image](https://user-images.githubusercontent.com/43178739/125809754-fbcf7ff1-e350-4881-8923-03dcbd5569cd.png)

Thanks for your support))

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
