### ISSUE TITLE
[Event Request] table 210 "Job Journal Line" please provide better "Ishandled" pattern

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#13273]
in the following scenario the ShouldRetrieveCostPrice cannot be handled very well (especially, if you subscribe and want to return false as value for ShouldRetrieveCostPrice, then the standard functionality is executed, which one tries to prevent).

it would be better if you provide a IsHandled pattern.

    
local procedure RetrieveCostPrice(): Boolean
    var
        ShouldRetrieveCostPrice: Boolean;
        // -NEW
       IsHandled :Boolean;
       // +NEW
    begin
        // -NEW
        // OnBeforeRetrieveCostPrice(Rec, xRec, ShouldRetrieveCostPrice);
        // if ShouldRetrieveCostPrice then
        //    exit(true);
        OnBeforeRetrieveCostPrice(Rec, xRec, ShouldRetrieveCostPrice);
        if IsHandled then
           exit (ShouldRetrieveCostPrice)
        // +NEW

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
