### ISSUE TITLE
[Event Request] table 5065 "Interaction Log Entry"

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#13270]
Can you please provide the following IsHandled Pattern

   procedure ShowDocument()
    var
        SalesHeader: Record "Sales Header";
        SalesHeaderArchive: Record "Sales Header Archive";
        SalesInvHeader: Record "Sales Invoice Header";
        SalesShptHeader: Record "Sales Shipment Header";
        SalesCrMemoHeader: Record "Sales Cr.Memo Header";
        IssuedReminderHeader: Record "Issued Reminder Header";
        PurchHeader: Record "Purchase Header";
        PurchHeaderArchive: Record "Purchase Header Archive";
        PurchInvHeader: Record "Purch. Inv. Header";
        PurchRcptHeader: Record "Purch. Rcpt. Header";
        PurchCrMemoHeader: Record "Purch. Cr. Memo Hdr.";
        ServHeader: Record "Service Header";
        ReturnRcptHeader: Record "Return Receipt Header";
        IssuedFinChargeMemoHeader: Record "Issued Fin. Charge Memo Header";
        ReturnReceiptHeader: Record "Return Receipt Header";
        ReturnShipmentHeader: Record "Return Shipment Header";
        ServiceContractHeader: Record "Service Contract Header";
        // -NEW
        IsHandled: Boolean;
    // +NEW
    begin
        // -NEW
        OnBeforeShowDocument(Rec, IsHandled);
        if IsHandled then
            exit;
        // +NEW
     ....
     end

    // -NEW
    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowDocument(var InteractionLogEntry: Record "Interaction Log Entry"; var IsHandled: Boolean)
    begin
    end;
    // +NEW

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
