### ISSUE TITLE
[Event Request] table 5902 "Service Line" - OnAfterCheckApplFromItemLedgEntry()

### ISSUE THREAD

**Issue by PavlosPGP** [microsoft/ALAppExtensions#13276]
New event OnAfterCheckApplFromItemLedgEntry in function CheckApplFromItemLedgEntry as follows:

    local procedure CheckApplFromItemLedgEntry(var ItemLedgEntry: Record "Item Ledger Entry")
    var
        ItemTrackingLines: Page "Item Tracking Lines";
        QtyBase: Decimal;
        ShippedQtyNotReturned: Decimal;
    begin
        if "Appl.-from Item Entry" = 0 then
            exit;

        TestField(Type, Type::Item);
        TestField(Quantity);
        if "Document Type" in ["Document Type"::"Credit Memo"] then begin
            if Quantity < 0 then
                FieldError(Quantity, Text029);
        end else begin
            if Quantity > 0 then
                FieldError(Quantity, Text030);
        end;

        ItemLedgEntry.Get("Appl.-from Item Entry");
        ItemLedgEntry.TestField(Positive, false);
        ItemLedgEntry.TestField("Item No.", "No.");
        ItemLedgEntry.TestField("Variant Code", "Variant Code");
        if ItemLedgEntry.TrackingExists then
            Error(Text040, ItemTrackingLines.Caption, FieldCaption("Appl.-from Item Entry"));

        if "Document Type" in ["Document Type"::"Credit Memo"] then
            QtyBase := "Quantity (Base)"
        else
            QtyBase := "Qty. to Ship (Base)";

        if Abs(QtyBase) > -ItemLedgEntry."Shipped Qty. Not Returned" then begin
            if "Qty. per Unit of Measure" = 0 then
                ShippedQtyNotReturned := ItemLedgEntry."Shipped Qty. Not Returned"
            else
                ShippedQtyNotReturned :=
                  Round(ItemLedgEntry."Shipped Qty. Not Returned" / "Qty. per Unit of Measure", UOMMgt.QtyRndPrecision);
            Error(
              Text039,
              -ShippedQtyNotReturned, ItemLedgEntry.TableCaption, ItemLedgEntry."Entry No.");
        end;

        OnAfterCheckApplFromItemLedgEntry(Rec,ItemLedgEntry);  //New Event
    end;

Event Signature:

    [IntegrationEvent(false,false)]
    local procedure OnAfterCheckApplFromItemLedgEntry(var ServiceLine: Record "Service Line"; var ItemLedgerEntry: Record "Item Ledger Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
