### ISSUE TITLE
request for protected variables - report 1316 "Standard Statement" - StartDate and EndDate

### ISSUE THREAD

**Issue by db-bc** [microsoft/ALAppExtensions#13279]
We are implementing a "Show Only Open Entries" option and need in Customer On(Before/After)AfterGetRecord() to detemine whether to PrintLine for a given customer. One of the ways we have considered to do this will involve access to the `StartDate` and `EndDate` request page variables. And it seems that, even if we end up finding another way, those are generally useful for developers extending this report anyway. Therefore, please can you make them both `protected` so that extensions can access them? Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
