### ISSUE TITLE
[Event Request] table 5902 "Service Line" - OnAfterUpdateAmounts()

### ISSUE THREAD

**Issue by PavlosPGP** [microsoft/ALAppExtensions#13275]
New Event OnAfterUpdateAmounts in function UpdateAmounts() as follows:

    procedure UpdateAmounts()
    var
        CustCheckCrLimit: Codeunit "Cust-Check Cr. Limit";
        ExpectedLineAmount: Decimal;
    begin
        if GuiAllowed and (CurrFieldNo <> 0) then
            ConfirmAdjPriceLineChange;

        GetServHeader;

        if "Line Amount" <> xRec."Line Amount" then
            "VAT Difference" := 0;
        ExpectedLineAmount := Round(
                     CalcChargeableQty * "Unit Price",
                     Currency."Amount Rounding Precision") - "Line Discount Amount";
        if "Line Amount" <> ExpectedLineAmount then begin
            "Line Amount" := ExpectedLineAmount;
            "VAT Difference" := 0;
        end;
        if ServHeader."Tax Area Code" = '' then
            UpdateVATAmounts;

        InitOutstandingAmount;
        if not IsCustCrLimitChecked and (CurrFieldNo <> 0) then begin
            IsCustCrLimitChecked := true;
            CustCheckCrLimit.ServiceLineCheck(Rec);
        end;
        UpdateRemainingCostsAndAmounts;

        OnAfterUpdateAmounts(Rec);  // New Event
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateAmounts(var ServiceLine: Record "Service Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
