### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line"

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#13271]
Hello,
I think there should be a statement like the following in codeunit 22, otherwise the IsHandled param makes no sense.

    procedure PostItem()
    var
        IsHandled: Boolean;
    begin
        OnBeforePostItem(ItemJnlLine, IsHandled, CalledFromAdjustment);
        // -New
        if IsHandled then
            exit;
        // +New

        with ItemJnlLine do begin
            SKUExists := SKU.Get("Location Code", "Item No.", "Variant Code");
            IsHandled := false;
            OnPostItemOnAfterGetSKU(ItemJnlLine, SKUExists, IsHandled);

**Comment by Duffy77** [comment]
As i mentioned here
#13167

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
