### ISSUE TITLE
[Event Change Request] - Table 5901 "Service Item Line" add parameters to OnValidateServiceItemNoOnBeforeEmptyContractNoFindServContractLine publisher

### ISSUE THREAD

**Issue by PavlosPGP** [microsoft/ALAppExtensions#13272]
Request to add Handled functionality and additional parameters to the OnValidateServiceItemNoOnBeforeEmptyContractNoFindServContractLine event in the OnValidate trigger of field "Service Item No." as follows:

                    IsHandled := false;  //New Line
                    OnValidateServiceItemNoOnBeforeEmptyContractNoFindServContractLine(Rec, ServHeader, ServItem, ServContractLine, ServContractExist, IsHandled);  //Added parameters

                    if not IsHandled then  //New line
                        if ServHeader."Contract No." = '' then begin
                            ServContractLine.Reset();
                            ServContractLine.FilterGroup(2);
                            ServContractLine.SetCurrentKey("Service Item No.", "Contract Status");
                            ServContractLine.SetRange("Service Item No.", ServItem."No.");
                            ServContractLine.SetRange("Contract Status", ServContractLine."Contract Status"::Signed);
                            ServContractLine.SetRange("Contract Type", ServContractLine."Contract Type"::Contract);
                            ServContractLine.SetRange("Customer No.", ServHeader."Customer No.");
                            ServContractLine.SetFilter("Starting Date", '<=%1', ServHeader."Order Date");
                            ServContractLine.SetFilter("Contract Expiration Date", '>=%1 | =%2', ServHeader."Order Date", 0D);
                            ServContractLine.FilterGroup(0);

                            if ServContractLine.Find('-') then
                                if ServContractLine.Next > 0 then begin
                                    if ConfirmManagement.GetResponse(
                                         StrSubstNo(Text047, "Service Item No."), true)
                                    then begin
                                        ServContractList.SetTableView(ServContractLine);
                                        ServContractList.LookupMode(true);
                                        if ServContractList.RunModal = ACTION::LookupOK then begin
                                            ServContractList.GetRecord(ServContractLine);
                                            ServContractExist := true;
                                        end;
                                    end;
                                end else begin
                                    ServContractLine.FindFirst;
                                    ServContractExist := true;
                                end;
                        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnValidateServiceItemNoOnBeforeEmptyContractNoFindServContractLine(var ServiceItemLine: Record "Service Item Line"; ServiceHeader: Record "Service Header"; ServiceItem: Record "Service Item"; var ServContractLine: Record "Service Contract Line"; var ServContractExists: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
