### ISSUE TITLE
[Event request] Table 12182 "Vendor Bill Line" - OnBeforeUpdateVendBillWithhTaxWHTAmounts

### ISSUE THREAD

**Issue by VeronicaGoglia** [microsoft/ALAppExtensions#13286]
Hi AL-Team,
can you please add a new event in the method CreateVendBillWithhTax

VendBillWithhTax."Withholding Tax Code" := CompWithhTax."Withholding Tax Code";

//New Event
OnBeforeUpdateVendBillWithhTaxWHTAmounts(VendBillWithhTax, CompWithhTax);
//New Event

UpdateVendBillWithhTaxWHTAmounts(VendBillWithhTax, CompWithhTax);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
