### ISSUE TITLE
[Event request] Table 12182 "Vendor Bill Line" - OnBeforeInsertVendBillWithhTax and OnAfterInsertVendBillWithhTax

### ISSUE THREAD

**Issue by VeronicaGoglia** [microsoft/ALAppExtensions#13287]
Hi AL-Team,
can you please add new events in the method CreateVendBillWithhTax

if VendBillWithhTax."Withholding Tax Code" <> '' then
                
//New Event
OnBeforeInsertVendBillWithhTax(VendBillWithhTax, Vend);
//New Event

VendBillWithhTax.Insert();

//New Event
OnAfterInsertVendBillWithhTax(VendBillWithhTax);
//New Event

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
