### ISSUE TITLE
[Event request] Table 12113 "Tmp Withholding Contribution" - OnAfterCalculateWithholdingTax

### ISSUE THREAD

**Issue by VeronicaGoglia** [microsoft/ALAppExtensions#13281]
Hi AL-Team,
can you please add a new event in the method CalculateWithholdingTax

"Withholding Tax Amount" := Round("Taxable Base" * "Withholding Tax %" / 100);

//New Event
OnAfterCalculateWithholdingTax(Rec);
//New Event

if "Taxable Base" < 0 then
	Error(NegativeTaxableBaseErr);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
