### ISSUE TITLE
[Event request] Table 12116 "Withholding Tax" - OnAfterValorizzaRitenute

### ISSUE THREAD

**Issue by VeronicaGoglia** [microsoft/ALAppExtensions#13282]
Hi AL-Team,
can you please add a new event in the method ValorizzaRitenute

"Source-Withholding Tax" := WithholdCode."Source-Withholding Tax";

//New Event
OnAfterValorizzaRitenute(Rec);
//New Event

ClearRelatedNonTaxableLines();

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
