### ISSUE TITLE
[Event request] Table 12137 "Purch. Withh. Contribution" - OnAfterValorizzaRitenute

### ISSUE THREAD

**Issue by VeronicaGoglia** [microsoft/ALAppExtensions#13285]
Hi AL-Team,
can you please add a new event in the method ValorizzaRitenute

 "Non Taxable Amount" := "Total Amount" -
          "Base - Excluded Amount" -
          "Non Taxable Amount By Treaty" -
          "Taxable Base";

//New Event
OnAfterValorizzaRitenute(Rec);
//New Event

Validate("Withholding Tax Amount", Round("Taxable Base" * "Withholding Tax %" / 100, Curr."Amount Rounding Precision"));

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
