### ISSUE TITLE
[Event request] Table 12185 "Vendor Bill Withholding Tax" - OnAfterCalculateWithholdingTax

### ISSUE THREAD

**Issue by VeronicaGoglia** [microsoft/ALAppExtensions#13288]
Hi AL-Team,
can you please add new events in the method CalculateWithholdingTax

GetCurrency("Currency Code");
"Withholding Tax Amount" := Round("Taxable Base" * "Withholding Tax %" / 100, Currency."Amount Rounding Precision");
                
//New Event
OnAfterCalculateWithholdingTax(Rec);
//New Event

if "Taxable Base" < 0 then
	Error(Text12100, FieldCaption("Taxable Base"));

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
