### ISSUE TITLE
event request - report 1316 "Standard Statement" - OnCustomerOnAfterGetRecordOnBeforeSetPrintLine(var CustLedgerEntry, var PrintLine)

### ISSUE THREAD

**Issue by db-bc** [microsoft/ALAppExtensions#13280]
The report does this to check whether entries exist in the period. We want to implement a "Show Only Open Entries" option and so, if that is ticked, add a filter on the Open field of the ledger entries to check whether to print a given customer or not.

Can we therefore get this new event?

signature:
```al
[IntegrationEvent(false, false)]
local procedure OnCustomerAfterGetRecordOnBeforeSetPrintLine(Customer: Record Customer; var CustLedgerEntry: Record "Cust. Ledger Entry"; var IsHandled: Boolean; var PrintLine: Boolean)
```

emission:
```al
                if (not PrintLine) and PrintAllHavingEntry then begin
                    CustLedgerEntry.Reset();
                    CustLedgerEntry.SetCurrentKey("Customer No.", "Posting Date");
                    CustLedgerEntry.SetRange("Customer No.", "No.");
                    CustLedgerEntry.SetRange("Posting Date", StartDate, EndDate);
                    CopyFilter("Currency Filter", CustLedgerEntry."Currency Code");

                    // +NEW
                    OnCustomerAfterGetRecordOnBeforeSetPrintLine(Customer, CustLedgerEntry, IsHandled, PrintLine);

                    if not IsHandled then // -NEW
                        PrintLine := not CustLedgerEntry.IsEmpty();
                end;
```

The `var` on `CustLedgerEntry` will let us add filters as required. `IsHandled := true` will mean we can override the standard check for `IsEmpty`, if needed. If `IsHandled := false` then it will still query it, but we can have added new filters to the `var` ledger entry.

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
