### ISSUE TITLE
[Event Request] codeunit 5900 ServOrderManagement - OnAfterCopyCustFromServiceHeader

### ISSUE THREAD

**Issue by PavlosPGP** [microsoft/ALAppExtensions#13296]
New Event OnAfterCopyCustFromServiceHeader in function CopyCustFromServiceHeader as follows:

    local procedure CopyCustFromServiceHeader(var Cust: Record Customer; ServiceHeader: Record "Service Header")
    begin
        Cust."No." := '';
        Cust.Validate(Name, ServiceHeader.Name);
        Cust."Name 2" := ServiceHeader."Name 2";
        Cust.Address := ServiceHeader.Address;
        Cust."Address 2" := ServiceHeader."Address 2";
        Cust.City := ServiceHeader.City;
        Cust."Post Code" := ServiceHeader."Post Code";
        Cust.Contact := ServiceHeader."Contact Name";
        Cust."Phone No." := ServiceHeader."Phone No.";
        Cust."E-Mail" := ServiceHeader."E-Mail";
        Cust.Blocked := Cust.Blocked::" ";

        OnAfterCopyCustFromServiceHeader(Cust, ServiceHeader);  // New Event
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyCustFromServiceHeader(var Cust: Record Customer; ServiceHeader: Record "Service Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
