### ISSUE TITLE
[Event Request] - Table: Purchase Line - Procedure: GetAbsMin

### ISSUE THREAD

**Issue by alessandrowolf87** [microsoft/ALAppExtensions#13292]
Hi,
can you please add a new event in the procedure GetAbsMin of Purchase Line table

//>New Event
OnBeforeGetAbsMin(var Rec: Record "Purchase Line" ,var QtyHandled: Decimal ,var isHandled: boolean);
//<New Event

//>Old Procedure

local procedure GetAbsMin(QtyToHandle: Decimal; QtyHandled: Decimal): Decimal
begin
        if Abs(QtyHandled) < Abs(QtyToHandle) then
            exit(QtyHandled);

        exit(QtyToHandle);
end;
//<Old Procedure

//>New Procedure

local procedure GetAbsMin(QtyToHandle: Decimal; QtyHandled: Decimal): Decimal
var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetAbsMin(Rec,QtyHandled, IsHandled);
        if IsHandled then
            exit(QtyHandled);

        if Abs(QtyHandled) < Abs(QtyToHandle) then
            exit(QtyHandled);

        exit(QtyToHandle);
end;
//<New Procedure

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
