### ISSUE TITLE
[Event Request] codeunit 5942 "ServContractQuote-Tmpl. Upd."  OnBeforeApplyServiceContractQuoteTemplate

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#13295]
After selection of Service Contract Template fields are not updated in Service Contract Header beacause this variable is not forwarded as var

before 
[IntegrationEvent(false, false)]
    local procedure OnBeforeApplyServiceContractQuoteTemplate(ServiceContractHeader: Record "Service Contract Header"; var IsHandled: Boolean)
    begin
    end;

---------------
after
 [IntegrationEvent(false, false)]
    local procedure OnBeforeApplyServiceContractQuoteTemplate(**var** ServiceContractHeader: Record "Service Contract Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
