### ISSUE TITLE
[Event Request] codeunit 7307 "Whse.-Activity-Register" - OnBeforeCheckWhseActLineToRegister

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13299]
We would like to add a new event OnBeforeCheckWhseActLineToRegister in the following procedure:

    local procedure CheckWhseItemTrkgLine(var WhseActivLine: Record "Warehouse Activity Line")
.
.
.

            until TempWhseActivLine.Next() = 0;

        TempWhseActivLine.Reset();
        TempWhseActivLine.SetCurrentKey(
          "Source Type", "Source Subtype", "Source No.", "Source Line No.", "Source Subline No.");
        TempWhseActivLine.SetRange("Breakbulk No.", 0);
        OnBeforeCheckWhseActLineToRegister(TempWhseActivLine); //A109F0000.Event
        if TempWhseActivLine.Find('-') then
            repeat
                ItemTrackingMgt.GetWhseItemTrkgSetup(TempWhseActivLine."Item No.", WhseItemTrackingSetup);
                // Per document
                TempWhseActivLine.SetSourceFilter(
                  TempWhseActivLine."Source Type", TempWhseActivLine."Source Subtype", TempWhseActivLine."Source No.",
                  TempWhseActivLine."Source Line No.", TempWhseActivLine."Source Subline No.", false);

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckWhseActLineToRegister(var WarehouseActivityLine: Record "Warehouse Activity Line")
    begin
        //A109F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
