### ISSUE TITLE
[Event Request] codeunit 80 "Sales-Post" - OnAfterGetItemChargeSalesLineToPost

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13298]
We would like to add a new event OnAfterGetItemChargeSalesLineToPost in the following procedure:

    local procedure PostItemJnlLineItemCharges(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; var OriginalItemJnlLine: Record "Item Journal Line"; ItemShptEntryNo: Integer)
    var
        ItemChargeSalesLine: Record "Sales Line";
    begin
        with SalesLine do begin
            ClearItemChargeAssgntFilter;
            TempItemChargeAssgntSales.SetCurrentKey(
              "Applies-to Doc. Type", "Applies-to Doc. No.", "Applies-to Doc. Line No.");
            TempItemChargeAssgntSales.SetRange("Applies-to Doc. Type", "Document Type");
            TempItemChargeAssgntSales.SetRange("Applies-to Doc. No.", "Document No.");
            TempItemChargeAssgntSales.SetRange("Applies-to Doc. Line No.", "Line No.");
            if TempItemChargeAssgntSales.FindSet() then
                repeat
                    TestField("Allow Item Charge Assignment");
                    GetItemChargeLine(SalesHeader, ItemChargeSalesLine);
                    OnAfterGetItemChargeSalesLineToPost(ItemChargeSalesLine, SalesLine); //A108F0086.Event
                    ItemChargeSalesLine.CalcFields("Qty. Assigned");
                    if (ItemChargeSalesLine."Qty. to Invoice" <> 0) or
                       (Abs(ItemChargeSalesLine."Qty. Assigned") < Abs(ItemChargeSalesLine."Quantity Invoiced"))
                    then begin
                        OriginalItemJnlLine."Item Shpt. Entry No." := ItemShptEntryNo;
                        PostItemChargePerOrder(SalesHeader, SalesLine, OriginalItemJnlLine, ItemChargeSalesLine);
                        TempItemChargeAssgntSales.Mark(true);
                    end;
                until TempItemChargeAssgntSales.Next() = 0;
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetItemChargeSalesLineToPost(var ItemChargeSalesLine: Record "Sales Line"; SalesLine: Record "Sales Line")
    begin
        //A108F0086.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
