### ISSUE TITLE
Allow setting of SuppressCommit in Codeunit 81 Sales-Post (Yes/No)

### ISSUE THREAD

**Issue by PeterConijn** [microsoft/ALAppExtensions#13293]
It is possible to run codeunit 80 with commits suppressed, so you can handle your own commit moments. However, there is no way to do this if you want to call codeunit 80 through codeunit 81 Sales-Post (Yes/No).

Therefore, I would request the following code:

```
local procedure RunSalesPost(var SalesHeader: Record "Sales Header")
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeRunSalesPost(SalesHeader, IsHandled);
    if IsHandled then
        exit;
     Codeunit.Run(Codeunit::"Sales-Post", SalesHeader);
end;
```

be updated to look something like
    
```
local procedure RunSalesPost(var SalesHeader: Record "Sales Header")
var
    SalesPost: Codeunit "Sales-Post";
    SuppressCommit: Boolean;
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeRunSalesPost(SalesHeader, SuppressCommit, IsHandled);
    if IsHandled then
        exit;

    SalesPost.SetSuppressCommit(SuppressCommit);
    SalesPost.Run(SalesHeader);
end;
```

And the event be changed to incorporate that.
    
```
[IntegrationEvent(false, false)]
local procedure OnBeforeRunSalesPost(var SalesHeader: Record "Sales Header"; var SuppressCommit: Boolean; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
