### ISSUE TITLE
[Event Request] table 5964 "Service Contract Line" - OnBeforeUpdateContractAnnualAmount()

### ISSUE THREAD

**Issue by PavlosPGP** [microsoft/ALAppExtensions#13291]
New Event OnBeforeUpdateContractAnnualAmount in function UpdateContractAnnualAmount as follows:

    procedure UpdateContractAnnualAmount(Deleting: Boolean)
    var
        OldServContractHeader: Record "Service Contract Header";
        ServContractLine2: Record "Service Contract Line";
        LineAmount: Decimal;
        IsHandled: Boolean;  //New Line
    begin
        GetServContractHeader;
        // New Event -> Start
        IsHandled := false;
        OnBeforeUpdateContractAnnualAmount(ServContractHeader, Rec, IsHandled);
        if IsHandled then
            exit;
        // New Event <- End
        if not ServContractHeader."Allow Unbalanced Amounts" then begin
            LineAmount := CalculateOtherLineAmounts(ServContractHeader);

            OldServContractHeader := ServContractHeader;
            if Deleting then
                ServContractHeader."Annual Amount" := LineAmount
            else begin
                ServContractHeader."Annual Amount" := LineAmount + "Line Amount";
                if not "New Line" then
                    ContractGainLossEntry.AddEntry(4, "Contract Type", "Contract No.", "Line Amount" - xRec."Line Amount", '')
                else
                    if ServContractHeader.Status = ServContractHeader.Status::Signed then begin
                        if ServContractLine2.Get("Contract Type", "Contract No.", "Line No.") then
                            ContractGainLossEntry.AddEntry(4, "Contract Type", "Contract No.", "Line Amount" - ServContractLine2."Line Amount", '')
                        else
                            ContractGainLossEntry.AddEntry(0, "Contract Type", "Contract No.", "Line Amount", '')
                    end;
            end;
            ServContractHeader.ValidateNextInvoicePeriod;
            ServContractHeader.SuspendStatusCheck(StatusCheckSuspended);
            ServContractHeader.Modify(true);
            if ServContractHeader."Contract Type" = ServContractHeader."Contract Type"::Contract then
                if ServMgtSetup."Register Contract Changes" then
                    ServContractHeader.UpdContractChangeLog(OldServContractHeader);
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateContractAnnualAmount(ServContractHeader: Record "Service Contract Header"; var ServContractLine: Record "Service Contract Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
