### ISSUE TITLE
request for protected variables - report 1316 "Standard Statement" - PrintAllHavingEntry, PrintAllHavingBal, PrintReversedEntries, PrintUnappliedEntries

### ISSUE THREAD

**Issue by db-bc** [microsoft/ALAppExtensions#13290]
Similarly to https://github.com/microsoft/ALAppExtensions/issues/13279

When implementing that scenario, we'll also want to set StartDate to an arbitarily early date, e.g. `19990101D`, and then set `PrintAllHavingEntry` to `true` and `PrintAllHavingBal` to `false`, so that we don't show any weird starting balances before open entries, or include any customers who only have same.

Thanks!

**Comment by db-bc** [comment]
To add: We'd also want to turn off Include Reversed/Unapplied Entries settings, since Open entries of Initial type won't be either of those. So can we get those at the same time please?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
