### ISSUE TITLE
[Event Request] codeunit 7304 "Whse. Jnl.-Register Batch" - OnBeforeItemJnlPostLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13305]
We would like to add a new event OnBeforeItemJnlPostLine in the following procedure:

    local procedure "Code"()
.
.
.

                    until TempWhseJnlLine2.Next() = 0;

                //A109F0003.Event.ns
                IsHandled := false;
                OnBeforeItemJnlPostLine(ItemJnlPostLine, WhseJnlLine, WhseJnlTemplate, IsHandled);
                if not IsHandled then
                    //A109F0003.Event.ne
                    if IsReclass("Journal Template Name") then
                        if CreateItemJnlLine(WhseJnlLine, ItemJnlLine) then
                            ItemJnlPostLine.RunWithCheck(ItemJnlLine);

                OnAfterItemJnlPostLine(WhseJnlLine);

                if IsPhysInvtCount(WhseJnlTemplate, "Phys Invt Counting Period Code", "Phys Invt Counting Period Type") then begin
                    if not PhysInvtCount then begin
                        PhysInvtCountMgt.InitTempItemSKUList;
                        PhysInvtCount := true;
                    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeItemJnlPostLine(var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line"; var WarehouseJournalLine: Record "Warehouse Journal Line"; WarehouseJournalTemplate: Record "Warehouse Journal Template"; var IsHandled: Boolean)
    begin
        //A109F0003.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
