### ISSUE TITLE
[Event Request] codeunit 5750 "Whse.-Create Source Document" - OnAfterCreateWhseItemTrackingLines

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13302]
We would like to add a new event OnAfterCreateWhseItemTrackingLines in the following procedure:

    local procedure CreateShptLine(var WhseShptLine: Record "Warehouse Shipment Line")
    var
        Item: Record Item;
    begin
        with WhseShptLine do begin
            Item."No." := "Item No.";
            Item.ItemSKUGet(Item, "Location Code", "Variant Code");
            "Shelf No." := Item."Shelf No.";
            OnBeforeWhseShptLineInsert(WhseShptLine);
            Insert;
            OnAfterWhseShptLineInsert(WhseShptLine);
            CreateWhseItemTrackingLines;
            OnAfterCreateWhseItemTrackingLines(WhseShptLine); //A109F0000.Event.n
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCreateWhseItemTrackingLines(var WarehouseShipmentLine: Record "Warehouse Shipment Line")
    begin
        //A109F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
