### ISSUE TITLE
[Event Request] codeunit 5750 "Whse.-Create Source Document" - OnBeforeCreateRcptLineFromPurchLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13301]
We would like to add a new event OnBeforeCreateRcptLineFromPurchLine in the following procedure:

    procedure PurchLine2ReceiptLine(WhseReceiptHeader: Record "Warehouse Receipt Header"; PurchLine: Record "Purchase Line"): Boolean
    var
        WhseReceiptLine: Record "Warehouse Receipt Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePurchLine2ReceiptLine(WhseReceiptHeader, PurchLine, IsHandled);
        if IsHandled then
            exit;

        with WhseReceiptLine do begin
            InitNewLine(WhseReceiptHeader."No.");
            SetSource(DATABASE::"Purchase Line", PurchLine."Document Type".AsInteger(), PurchLine."Document No.", PurchLine."Line No.");
            PurchLine.TestField("Unit of Measure Code");
            SetItemData(
              PurchLine."No.", PurchLine.Description, PurchLine."Description 2", PurchLine."Location Code",
              PurchLine."Variant Code", PurchLine."Unit of Measure Code", PurchLine."Qty. per Unit of Measure");
            OnPurchLine2ReceiptLineOnAfterInitNewLine(WhseReceiptLine, WhseReceiptHeader, PurchLine);
            case PurchLine."Document Type" of
                PurchLine."Document Type"::Order:
                    begin
                        Validate("Qty. Received", Abs(PurchLine."Quantity Received"));
                        "Due Date" := PurchLine."Expected Receipt Date";
                    end;
                PurchLine."Document Type"::"Return Order":
                    begin
                        Validate("Qty. Received", Abs(PurchLine."Return Qty. Shipped"));
                        "Due Date" := WorkDate;
                    end;
            end;
            SetQtysOnRcptLine(WhseReceiptLine, Abs(PurchLine.Quantity), Abs(PurchLine."Quantity (Base)"));
            OnPurchLine2ReceiptLineOnAfterSetQtysOnRcptLine(WhseReceiptLine, PurchLine);
            "Starting Date" := PurchLine."Planned Receipt Date";
            if "Location Code" = WhseReceiptHeader."Location Code" then
                "Bin Code" := WhseReceiptHeader."Bin Code";
            if "Bin Code" = '' then
                "Bin Code" := PurchLine."Bin Code";
            UpdateReceiptLine(WhseReceiptLine, WhseReceiptHeader);
            OnPurchLine2ReceiptLineOnAfterUpdateReceiptLine(WhseReceiptLine, WhseReceiptHeader);
            OnBeforeCreateRcptLineFromPurchLine(WhseReceiptLine, WhseReceiptHeader, PurchLine); //A109F0000.Event.n
            CreateReceiptLine(WhseReceiptLine);
            OnAfterCreateRcptLineFromPurchLine(WhseReceiptLine, WhseReceiptHeader, PurchLine);
            exit(not HasErrorOccured);
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateRcptLineFromPurchLine(var WarehouseReceiptLine: Record "Warehouse Receipt Line"; WarehouseReceiptHeader: Record "Warehouse Receipt Header"; PurchaseLine: Record "Purchase Line")
    begin
        //A109F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
