### ISSUE TITLE
[Event Request] codeunit 7304 "Whse. Jnl.-Register Batch" - OnInitItemJournalLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13306]
We would like to add a new event OnInitItemJournalLine in the following procedure:

    local procedure CreateItemJnlLine(WhseJnlLine2: Record "Warehouse Journal Line"; var ItemJnlLine: Record "Item Journal Line"): Boolean
.
.
.

                if QtyToHandleBase <> 0 then begin
                    OnInitItemJournalLine(ItemJnlLine, WhseJnlLine2, WhseJnlTemplate); //A200F0000.Event
                    ItemJnlLine."Document No." := "Whse. Document No.";
                    ItemJnlLine.Validate("Posting Date", "Registering Date");
                    ItemJnlLine.Validate("Item No.", "Item No.");
                    ItemJnlLine.Validate("Variant Code", "Variant Code");
                    ItemJnlLine.Validate("Location Code", "Location Code");
                    ItemJnlLine.Validate("Unit of Measure Code", "Unit of Measure Code");
                    ItemJnlLine.Validate(Quantity, Round(QtyToHandleBase / "Qty. per Unit of Measure", UOMMgt.QtyRndPrecision));
                    ItemJnlLine.Description := Description;
                    ItemJnlLine."Source Type" := ItemJnlLine."Source Type"::Item;
                    ItemJnlLine."Source No." := "Item No.";
                    ItemJnlLine."Source Code" := "Source Code";
                    ItemJnlLine."Reason Code" := "Reason Code";
                    ItemJnlLine."Warehouse Adjustment" := true;
                    ItemJnlLine."Line No." := "Line No.";
                    //OnAfterCreateItemJnlLine(ItemJnlLine, WhseItemTrkgLine, WhseJnlLine2); //A200F0000.Event.o
                    OnAfterCreateItemJnlLine(ItemJnlLine, WhseItemTrkgLine, WhseJnlLine2, QtyToHandleBase); //A200F0000.Event.n
                end;
            end;
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnInitItemJournalLine(var ItemJournalLine: Record "Item Journal Line"; WarehouseJournalLine: Record "Warehouse Journal Line"; WarehouseJournalTemplate: Record "Warehouse Journal Template")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
