### ISSUE TITLE
[Event Request] codeunit 7311 "Whse. Worksheet-Create" - OnAfterTransferFromAssemblyLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13315]
We would like to add a new event OnAfterTransferFromAssemblyLine in the following procedure:

    local procedure TransferAllButWhseDocDetailsFromAssemblyLine(var WhseWkshLine: Record "Whse. Worksheet Line"; AssemblyLine: Record "Assembly Line")
    var
        WhseWkshLine1: Record "Whse. Worksheet Line";
        Location: Record Location;
        Bin: Record Bin;
    begin
        with AssemblyLine do begin
            WhseWkshLine.SetHideValidationDialog(true);
            FindLastWhseWkshLine(WhseWkshLine1, WhseWkshLine."Worksheet Template Name", WhseWkshLine.Name, WhseWkshLine."Location Code");
            WhseWkshLine."Line No." := WhseWkshLine1."Line No." + 10000;
            WhseWkshLine."Source Type" := DATABASE::"Assembly Line";
            WhseWkshLine."Source Subtype" := "Document Type".AsInteger();
            WhseWkshLine."Source No." := "Document No.";
            WhseWkshLine."Source Line No." := "Line No.";
            WhseWkshLine."Source Subline No." := 0;
            WhseWkshLine."Source Document" := WhseMgt.GetWhseActivSourceDocument(WhseWkshLine."Source Type", WhseWkshLine."Source Subtype");
            WhseWkshLine."Location Code" := "Location Code";
            TestField(Type, Type::Item);
            WhseWkshLine."Item No." := "No.";
            WhseWkshLine."Variant Code" := "Variant Code";
            WhseWkshLine."Unit of Measure Code" := "Unit of Measure Code";
            WhseWkshLine."Qty. per Unit of Measure" := "Qty. per Unit of Measure";
            WhseWkshLine.Description := Description;
            WhseWkshLine."Description 2" := "Description 2";
            WhseWkshLine."Due Date" := "Due Date";
            CalcFields("Pick Qty.", "Pick Qty. (Base)");
            WhseWkshLine."Qty. Handled" := "Qty. Picked" + "Pick Qty.";
            WhseWkshLine."Qty. Handled (Base)" := "Qty. Picked (Base)" + "Pick Qty. (Base)";
            Location.Get("Location Code");
            if Location."Require Shipment" then
                WhseWkshLine.Validate(Quantity, Quantity)
            else
                WhseWkshLine.Validate(Quantity, "Quantity to Consume");
            WhseWkshLine."To Bin Code" := "Bin Code";
            if ("Location Code" <> '') and ("Bin Code" <> '') then begin
                Bin.Get("Location Code", "Bin Code");
                WhseWkshLine."To Zone Code" := Bin."Zone Code";
            end;
        end;
        OnAfterTransferFromAssemblyLine(WhseWkshLine, AssemblyLine); //A200F0000.Event
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterTransferFromAssemblyLine(var WhseWorksheetLine: Record "Whse. Worksheet Line"; AssemblyLine: Record "Assembly Line")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
