### ISSUE TITLE
[Event Request] codeunit 7311 "Whse. Worksheet-Create" - OnBeforeTransferFromWhseShptLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13316]
We would like to add a new event OnBeforeTransferFromWhseShptLine in the following procedure:

    local procedure TransferFromWhseShptLine(var WhseWkshLine: Record "Whse. Worksheet Line"; WhseWkshTemplateName: Code[10]; WhseWkshName: Code[10]; WhseShptLine: Record "Warehouse Shipment Line"): Boolean
    var
        WhseShptHeader: Record "Warehouse Shipment Header";
        IsHandled: Boolean;
    begin
        //A109F0004.Event.ns
        OnBeforeTransferFromWhseShptLine(WhseWkshLine, WhseShptLine, WhseWkshTemplateName, WhseWkshName, IsHandled);
        if IsHandled then
            exit(false);
        //A109F0004.Event.ne
        //A200F0000 Function parameter Boolean added
        with WhseShptLine do begin
            WhseWkshLine.SetCurrentKey(
              "Whse. Document Type", "Whse. Document No.", "Whse. Document Line No.");
            WhseWkshLine.SetRange("Whse. Document Type", WhseWkshLine."Whse. Document Type"::Shipment);
            WhseWkshLine.SetRange("Whse. Document No.", "No.");
            WhseWkshLine.SetRange("Whse. Document Line No.", "Line No.");
            if WhseWkshLine.Find('-') then
                exit;

            FindLastWhseWkshLine(WhseWkshLine, WhseWkshTemplateName, WhseWkshName, "Location Code");
            WhseShptHeader.Get("No.");

            WhseWkshLine.Init();
            WhseWkshLine.SetHideValidationDialog(true);
            WhseWkshLine."Line No." := WhseWkshLine."Line No." + 10000;
            WhseWkshLine."Source Type" := "Source Type";
            WhseWkshLine."Source Subtype" := "Source Subtype";
            WhseWkshLine."Source No." := "Source No.";
            WhseWkshLine."Source Line No." := "Source Line No.";
            WhseWkshLine."Source Document" := WhseMgt.GetWhseActivSourceDocument("Source Type", "Source Subtype");
            WhseWkshLine."Location Code" := "Location Code";
            WhseWkshLine."Item No." := "Item No.";
            WhseWkshLine."Variant Code" := "Variant Code";
            WhseWkshLine."Unit of Measure Code" := "Unit of Measure Code";
            WhseWkshLine."Qty. per Unit of Measure" := "Qty. per Unit of Measure";
            WhseWkshLine.Description := Description;
            WhseWkshLine."Description 2" := "Description 2";
            WhseWkshLine."Due Date" := "Due Date";
            WhseWkshLine."Qty. Handled" := "Qty. Picked" + "Pick Qty.";
            WhseWkshLine."Qty. Handled (Base)" := "Qty. Picked (Base)" + "Pick Qty. (Base)";
            WhseWkshLine.Validate(Quantity, Quantity);
            WhseWkshLine."To Zone Code" := "Zone Code";
            WhseWkshLine."To Bin Code" := "Bin Code";
            WhseWkshLine."Shelf No." := "Shelf No.";
            WhseWkshLine."Destination Type" := "Destination Type";
            WhseWkshLine."Destination No." := "Destination No.";
            if WhseShptHeader."Shipment Date" = 0D then
                WhseWkshLine."Shipment Date" := "Shipment Date"
            else
                WhseWkshLine."Shipment Date" := WhseShptHeader."Shipment Date";
            WhseWkshLine."Shipping Advice" := "Shipping Advice";
            WhseWkshLine."Shipping Agent Code" := WhseShptHeader."Shipping Agent Code";
            WhseWkshLine."Shipping Agent Service Code" := WhseShptHeader."Shipping Agent Service Code";
            WhseWkshLine."Shipment Method Code" := WhseShptHeader."Shipment Method Code";
            WhseWkshLine."Whse. Document Type" := WhseWkshLine."Whse. Document Type"::Shipment;
            WhseWkshLine."Whse. Document No." := "No.";
            WhseWkshLine."Whse. Document Line No." := "Line No.";
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferFromWhseShptLine(var WhseWkshLine: Record "Whse. Worksheet Line"; var WhseShptLine: Record "Warehouse Shipment Line"; WhseWkshTemplateName: Code[10]; WhseWkshName: Code[10]; var IsHandled: Boolean)
    begin
        //A109F0004.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
