### ISSUE TITLE
[Event Request] table 8613 "Config. Package Table" - OnBeforeModifyAllConfigLineWithEmptyPackageCode

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13318]
We would like to add a new event OnBeforeModifyAllConfigLineWithEmptyPackageCode in the following procedure:

    procedure DeleteRelatedTables(PackageCode: Code[20]; TableID: Integer)
    var
        ConfigLine: Record "Config. Line";
        ConfigPackageField: Record "Config. Package Field";
        ConfigFieldMapping: Record "Config. Field Mapping";
        ConfigPackageFilter: Record "Config. Package Filter";
        ConfigTableProcessingRule: Record "Config. Table Processing Rule";
    begin
        ConfigFieldMapping.SetRange("Package Code", PackageCode);
        if TableID <> 0 then
            ConfigFieldMapping.SetRange("Table ID", "Table ID");
        ConfigFieldMapping.DeleteAll();

        ConfigPackageField.SetRange("Package Code", PackageCode);
        if TableID <> 0 then
            ConfigPackageField.SetRange("Table ID", "Table ID");
        ConfigPackageField.DeleteAll();

        ConfigPackageFilter.SetRange("Package Code", PackageCode);
        if TableID <> 0 then
            ConfigPackageFilter.SetRange("Table ID", "Table ID");
        ConfigPackageFilter.DeleteAll();

        ConfigTableProcessingRule.SetRange("Package Code", PackageCode);
        if TableID <> 0 then
            ConfigTableProcessingRule.SetRange("Table ID", "Table ID");
        ConfigTableProcessingRule.DeleteAll();

        ConfigLine.SetRange("Package Code", PackageCode);
        if TableID <> 0 then
            ConfigLine.SetRange("Table ID", "Table ID");
        ConfigLine.SetRange("Dimensions as Columns", true);
        ConfigLine.ModifyAll("Dimensions as Columns", false);
        ConfigLine.SetRange("Dimensions as Columns");
        OnBeforeModifyAllConfigLineWithEmptyPackageCode(ConfigLine, PackageCode, TableID); //A100F0001.Event
        ConfigLine.ModifyAll("Package Code", '');
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyAllConfigLineWithEmptyPackageCode(var ConfigLine: Record "Config. Line"; PackageCode: Code[20]; TableID: Integer)
    begin
        //A100F0001.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
