### ISSUE TITLE
[Event Request] table 8613 "Config. Package Table" - OnBeforeInsertPackageField

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13319]
We would like to add a new event OnBeforeInsertPackageField in the following procedure:

    local procedure InitPackageFields(): Boolean
    var
        ConfigPackageField: Record "Config. Package Field";
        ConfigLine: Record "Config. Line";
        "Field": Record "Field";
        ProcessingOrder: Integer;
        FieldsAdded: Boolean;
        AddField: Boolean;
    begin
        FieldsAdded := false;
        ConfigPackageMgt.SetFieldFilter(Field, "Table ID", 0);
        if Field.FindSet then
            repeat
                //A100F0001.Event.ns
                AddField := true;
                OnBeforeInsertPackageField(Rec, Field, AddField);
                //A100F0001.Event.ne
                if not ConfigPackageField.Get("Package Code", "Table ID", Field."No.") and
                    AddField and //A200F0003.Event.n
                   not ConfigPackageMgt.IsDimSetIDField("Table ID", Field."No.")
                then begin
                    ConfigPackageMgt.InsertPackageField(
                      ConfigPackageField, "Package Code", "Table ID", Field."No.", Field.FieldName, Field."Field Caption",
                      true, true, false, false);
                    ConfigPackageField.SetRange("Package Code", "Package Code");
                    ConfigPackageField.SetRange("Table ID", "Table ID");
                    ConfigPackageField.SetRange("Field ID", Field."No.");
                    ConfigPackageMgt.SelectAllPackageFields(ConfigPackageField, true);
                    FieldsAdded := true;
                end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertPackageField(var ConfigPackageTable: Record "Config. Package Table"; "Field": Record "Field"; var AddField: Boolean)
    begin
        //A100F0001.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
