### ISSUE TITLE
[Event Request] codeunit 7311 "Whse. Worksheet-Create" - OnCreateWhseWkshLineOnAfterInsert

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13314]
We would like to add a new event OnCreateWhseWkshLineOnAfterInsert in the following procedure:

    local procedure CreateWhseWkshLine(var WhseWkshLine: Record "Whse. Worksheet Line") Created: Boolean
    var
        Item: Record Item;
        ItemTrackingMgt: Codeunit "Item Tracking Management";
    begin
        with WhseWkshLine do begin
            if "Shelf No." = '' then begin
                Item."No." := "Item No.";
                Item.ItemSKUGet(Item, "Location Code", "Variant Code");
                "Shelf No." := Item."Shelf No.";
            end;
            OnCreateWhseWkshLineOnBeforeInsert(WhseWkshLine);
            if Insert() then begin
                Created := true;
                if ItemTrackingMgt.GetWhseItemTrkgSetup("Item No.") then
                    ItemTrackingMgt.InitTrackingSpecification(WhseWkshLine);
                OnCreateWhseWkshLineOnAfterInsert(WhseWkshLine); //A200F0000.Event
            end;
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnCreateWhseWkshLineOnAfterInsert(var WhseWorksheetLine: Record "Whse. Worksheet Line")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
