### ISSUE TITLE
[Event Request] table 7347 "Internal Movement Line" - OnLookupBinContentFilters

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13326]
We would like to add a new event OnLookupBinContentFilters in the following procedure:

    local procedure LookUpBinContent()
    var
        BinContent: Record "Bin Content";
    begin
        BinContent.FilterGroup(2);
        BinContent.SetRange("Location Code", "Location Code");
        BinContent.FilterGroup(0);
        BinContent.SetFilter("Item No.", "Item No.");
        if "Variant Code" <> '' then begin
            TestField("Item No.");
            BinContent.SetRange("Variant Code", "Variant Code");
        end;
        if "Unit of Measure Code" <> '' then
            TestField("Item No.");
        OnLookupBinContentFilters(BinContent, Rec); //A200F0000.Event
        if PAGE.RunModal(0, BinContent) = ACTION::LookupOK then begin
            if BinContent."Block Movement" in [BinContent."Block Movement"::Outbound, BinContent."Block Movement"::All]
            then
                BinContent.FieldError("Block Movement");
            Validate("Location Code");
            Validate(Quantity, 0);
            Validate("From Bin Code", BinContent."Bin Code");
            Validate("Item No.", BinContent."Item No.");
            Validate("Variant Code", BinContent."Variant Code");
            Validate("Unit of Measure Code", BinContent."Unit of Measure Code");
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnLookupBinContentFilters(var BinContent: Record "Bin Content"; var InternalMovementLine: Record "Internal Movement Line")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
