### ISSUE TITLE
[Event Request] table 7347 "Internal Movement Line" - OnCheckBinContentQtySetInternalMovementLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13325]
We would like to add a new event OnCheckBinContentQtySetInternalMovementLine in the following procedure:

    procedure CheckBinContentQty()
    var
        BinContent: Record "Bin Content";
        InternalMovementLine: Record "Internal Movement Line";
        AvailQtyBase: Decimal;
    begin
        GetLocation("Location Code");

        if Location."Bin Mandatory" and
           ("Location Code" <> '') and ("From Bin Code" <> '') and
           ("Item No." <> '') and ("Unit of Measure Code" <> '')
        then begin
            BinContent."Location Code" := "Location Code";
            BinContent."Bin Code" := "From Bin Code";
            BinContent."Item No." := "Item No.";
            BinContent."Variant Code" := "Variant Code";
            BinContent."Unit of Measure Code" := "Unit of Measure Code";
            OnCheckBinContentQtySetBinContent(BinContent, Rec); //A200F0000.Event

            AvailQtyBase := BinContent.CalcQtyAvailToTake(0);
            InternalMovementLine.SetCurrentKey(
              "Item No.", "From Bin Code", "Location Code", "Unit of Measure Code", "Variant Code");
            InternalMovementLine.SetRange("Item No.", "Item No.");
            InternalMovementLine.SetRange("From Bin Code", "From Bin Code");
            InternalMovementLine.SetRange("Location Code", "Location Code");
            InternalMovementLine.SetRange("Unit of Measure Code", "Unit of Measure Code");
            InternalMovementLine.SetRange("Variant Code", "Variant Code");
            InternalMovementLine.SetFilter("Line No.", '<>%1', "Line No.");
            OnCheckBinContentQtySetInternalMovementLine(InternalMovementLine, Rec); //A200F0000.Event
            InternalMovementLine.CalcSums("Qty. (Base)");
            if AvailQtyBase - InternalMovementLine."Qty. (Base)" < "Qty. (Base)" then
                FieldError(
                  "Qty. (Base)",
                  StrSubstNo(
                    Text001, AvailQtyBase - InternalMovementLine."Qty. (Base)"));
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnCheckBinContentQtySetInternalMovementLine(var FilteredInternalMovementLine: Record "Internal Movement Line"; var InternalMovementLine: Record "Internal Movement Line")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
