### ISSUE TITLE
[Event Request] Codeunit 1535 "Approvals Mgmt." - OnBeforeShowPurchApprovalStatus

### ISSUE THREAD

**Issue by VPaas2** [microsoft/ALAppExtensions#13327]
Event request with IsHandled pattern in function ShowPurchApprovalStatus

    local procedure ShowPurchApprovalStatus(PurchaseHeader: Record "Purchase Header")
    **var**
        **IsHandled: Boolean;**
    begin
        PurchaseHeader.Find;

          **IsHandled := false;
         OnBeforeShowPurchApprovalStatus(PurchaseHeader)
            if IsHandled then
                exit;**

        case PurchaseHeader.Status of
            PurchaseHeader.Status::Released:
                Message(DocStatusChangedMsg, PurchaseHeader."Document Type", PurchaseHeader."No.", PurchaseHeader.Status);
            PurchaseHeader.Status::"Pending Approval":
                if HasOpenOrPendingApprovalEntries(PurchaseHeader.RecordId) then
                    Message(PendingApprovalMsg);
            PurchaseHeader.Status::"Pending Prepayment":
                Message(DocStatusChangedMsg, PurchaseHeader."Document Type", PurchaseHeader."No.", PurchaseHeader.Status);
        end;
    end;

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowPurchApprovalStatus(var PurchaseHeader, var IsHandled)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
