### ISSUE TITLE
[Event Request] table 6507 "Item Entry Relation" - OnAfterInitFromItemLedgerEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13328]
We would like to add a new event OnAfterInitFromItemLedgerEntry in the following procedure:

    procedure InitFromItemLedgerEntry(ItemLedgerEntry: Record "Item Ledger Entry")
    begin
        //A200F0000.Event.ns
        Init;
        "Item Entry No." := ItemLedgerEntry."Entry No.";
        "Serial No." := ItemLedgerEntry."Serial No.";
        "Lot No." := ItemLedgerEntry."Lot No.";

        OnAfterInitFromItemLedgerEntry(Rec, ItemLedgerEntry);
        //A200F0000.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterInitFromItemLedgerEntry(var ItemEntryRelation: Record "Item Entry Relation"; ItemLedgerEntry: Record "Item Ledger Entry")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
