### ISSUE TITLE
[Event Request] table 1003 "Job Planning Line" - OnAfterCopyFromGLAccount

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13337]
We would like to add a new event OnAfterCopyFromGLAccount in the following trigger:

    local procedure CopyFromGLAccount()
    begin
        GLAcc.Get("No.");
        GLAcc.CheckGLAcc;
        GLAcc.TestField("Direct Posting", true);
        GLAcc.TestField("Gen. Prod. Posting Group");
        Description := GLAcc.Name;
        "Gen. Bus. Posting Group" := GLAcc."Gen. Bus. Posting Group";
        "Gen. Prod. Posting Group" := GLAcc."Gen. Prod. Posting Group";
        "Unit of Measure Code" := '';
        "Direct Unit Cost (LCY)" := 0;
        "Unit Cost (LCY)" := 0;
        "Unit Price" := 0;
        OnAfterCopyFromGLAccount(Rec, Job, GLAcc); //A108F0025.Event
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyFromGLAccount(var JobPlanningLine: Record "Job Planning Line"; Job: Record Job; GLAccount: Record "G/L Account")
    begin
        //A108F0025.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
