### ISSUE TITLE
[Event Request] table 1001 "Job Task" - OnAfterOnInsert

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13339]
We would like to add a new event OnAfterOnInsert in the following trigger:

    trigger OnInsert()
    var
        Job: Record Job;
        Cust: Record Customer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeOnInsert(Rec, IsHandled);
        if IsHandled then
            exit;

        LockTable();
        Job.Get("Job No.");
        if Job.Blocked = Job.Blocked::All then
            Job.TestBlocked;
        Job.TestField("Bill-to Customer No.");
        Cust.Get(Job."Bill-to Customer No.");

        DimMgt.InsertJobTaskDim("Job No.", "Job Task No.", "Global Dimension 1 Code", "Global Dimension 2 Code");

        CalcFields("Schedule (Total Cost)", "Usage (Total Cost)");
        Job.UpdateOverBudgetValue("Job No.", true, "Usage (Total Cost)");
        Job.UpdateOverBudgetValue("Job No.", false, "Schedule (Total Cost)");

        OnAfterOnInsert(Rec, xRec); //A113F0000.Event
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterOnInsert(var JobTask: Record "Job Task"; var xJobTask: Record "Job Task")
    begin
        //A113F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
