### ISSUE TITLE
[Event Request] table 167 Job - OnAfterUpdateBillToCust

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13335]
We would like to add a new event OnAfterUpdateBillToCust in the following procedure:

    procedure UpdateCust()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateCust(Rec, xRec, IsHandled);
        If IsHandled then
            exit;

        if "Bill-to Customer No." <> '' then begin
            Cust.Get("Bill-to Customer No.");
            Cust.TestField("Customer Posting Group");
            IsHandled := false;
            OnUpdateCustOnBeforeTestBillToCustomerNo(Rec, Cust, IsHandled);
            if not IsHandled then
                Cust.TestField("Bill-to Customer No.", '');
            if Cust."Privacy Blocked" then
                Error(Cust.GetPrivacyBlockedGenericErrorText(Cust));
            if Cust.Blocked = Cust.Blocked::All then
                Error(
                  BlockedCustErr,
                  FieldCaption("Bill-to Customer No."),
                  "Bill-to Customer No.",
                  Cust.TableCaption,
                  FieldCaption(Blocked),
                  Cust.Blocked);
            "Bill-to Name" := Cust.Name;
            "Bill-to Name 2" := Cust."Name 2";
            "Bill-to Address" := Cust.Address;
            "Bill-to Address 2" := Cust."Address 2";
            "Bill-to City" := Cust.City;
            "Bill-to Post Code" := Cust."Post Code";
            "Bill-to Country/Region Code" := Cust."Country/Region Code";
            IsHandled := false;
            OnUpdateCustOnBeforeAssignIncoiceCurrencyCode(Rec, xRec, Cust, IsHandled);
            if not IsHandled then
                "Invoice Currency Code" := Cust."Currency Code";
            if "Invoice Currency Code" <> '' then
                Validate("Currency Code", '');
            "Customer Disc. Group" := Cust."Customer Disc. Group";
            "Customer Price Group" := Cust."Customer Price Group";
            "Language Code" := Cust."Language Code";
            "Bill-to County" := Cust.County;
            Reserve := Cust.Reserve;
            UpdateBillToContact("Bill-to Customer No.");
            CopyDefaultDimensionsFromCustomer();
        end else begin
            "Bill-to Name" := '';
            "Bill-to Name 2" := '';
            "Bill-to Address" := '';
            "Bill-to Address 2" := '';
            "Bill-to City" := '';
            "Bill-to Post Code" := '';
            "Bill-to Country/Region Code" := '';
            "Invoice Currency Code" := '';
            "Customer Disc. Group" := '';
            "Customer Price Group" := '';
            "Language Code" := '';
            "Bill-to County" := '';
            Validate("Bill-to Contact No.", '');
        end;

        //OnAfterUpdateBillToCust(Rec); A114F0000.Event.o
        OnAfterUpdateBillToCust(Rec, Cust); //A114F0000.Event.n
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateBillToCust(var Job: Record Job; Customer: Record Customer)
    begin
        //A114F0000.Event Parameter Customer
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
