### ISSUE TITLE
[Event Request] table 167 Job - OnAfterCalcAreJobTaskLinesEditable

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13333]
We would like to add a new event OnAfterCalcAreJobTaskLinesEditable in the following procedure:

    procedure CalcAreJobTaskLinesEditable() IsEditable: Boolean;
    begin
        //A113F0000.Event.ns
        IsEditable := "Bill-to Customer No." <> '';

        OnAfterCalcAreJobTaskLinesEditable(Rec, IsEditable);
        //A113F0000.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcAreJobTaskLinesEditable(var Job: Record Job; var IsEditable: Boolean)
    begin
        //A113F0000.Event
    end;

**Comment by Oleg-Romashkov** [comment]
Function CalcAreJobTaskLinesEditable does not exist. Please check the latest code base.

**Comment by Oleg-Romashkov** [comment]
We do not implement additional application code via event requests. Especially parts of you own solution. We need detailed explanation for such requests, better create them on IDEAS portal
