### ISSUE TITLE
[Event Request] table 83 "Item Journal Line" - OnAfterAssignProdOrderLineValues

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13332]
We would like to add a new event OnAfterAssignProdOrderLineValues in the following trigger:

            trigger OnValidate()
            var
                ProdOrderLine: Record "Prod. Order Line";
            begin
                TestField("Order No.");
                case "Order Type" of
                    "Order Type"::Production,
                    "Order Type"::Assembly:
                        begin
                            if "Order Type" = "Order Type"::Production then begin
                                ProdOrderLine.SetFilterByReleasedOrderNo("Order No.");
                                ProdOrderLine.SetRange("Line No.", "Order Line No.");
                                OnValidateOrderLineNoOnAfterProdOrderLineSetFilters(Rec, ProdOrderLine);
                                if ProdOrderLine.FindFirst then begin
                                    "Source Type" := "Source Type"::Item;
                                    "Source No." := ProdOrderLine."Item No.";
                                    "Order Line No." := ProdOrderLine."Line No.";
                                    "Routing No." := ProdOrderLine."Routing No.";
                                    "Routing Reference No." := ProdOrderLine."Routing Reference No.";
                                    if "Entry Type" = "Entry Type"::Output then begin
                                        "Location Code" := ProdOrderLine."Location Code";
                                        "Bin Code" := ProdOrderLine."Bin Code";
                                    end;
                                    OnAfterAssignProdOrderLineValues(Rec, ProdOrderLine); //A200F0000.Event
                                end;
                            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignProdOrderLineValues(var ItemJournalLine: Record "Item Journal Line"; ProdOrderLine: Record "Prod. Order Line")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
