### ISSUE TITLE
[Event Request] table 83 "Item Journal Line" - OnAfterSetTrackingFilterFromItemLedgerEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13331]
We would like to add a new event OnAfterSetTrackingFilterFromItemLedgerEntry in the following procedure:

    procedure SetTrackingFilterFromItemLedgerEntry(ItemLedgerEntry: Record "Item Ledger Entry")
    begin
        //A200F0000.ns
        SetRange("Serial No.", ItemLedgerEntry."Serial No.");
        SetRange("Lot No.", ItemLedgerEntry."Lot No.");

        OnAfterSetTrackingFilterFromItemLedgerEntry(Rec, ItemLedgerEntry);
        //A200F0000.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetTrackingFilterFromItemLedgerEntry(var ItemJournalLine: Record "Item Journal Line"; ItemLedgerEntry: Record "Item Ledger Entry")
    begin
        //A200F0000.Event
    end;

**Comment by Oleg-Romashkov** [comment]
This function does not exist. Please check the latest code base.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
