### ISSUE TITLE
[Event Request] table 1003 "Job Planning Line" - OnAfterClearItemTrackingValues

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13338]
We would like to add a new event OnAfterClearItemTrackingValues in the following trigger:

    procedure ClearItemTrackingValues()
    begin
        //A101F0000.Event.ns
        "Lot No." := '';
        "Serial No." := '';
        //A101F0000.Event.ne

        OnAfterClearItemTrackingValues(Rec); //A101F0000.Event
    end;

Event Signature:

   [IntegrationEvent(false, false)]
    local procedure OnAfterClearItemTrackingValues(var JobPlanningLine: Record "Job Planning Line")
    begin
        //A101F0000.Event.n
    end;

**Comment by Stepanenko-Vadim** [comment]
There is no **ClearItemTrackingValues** procedure in that table as far as I can see. Please double check your request, maybe if you specify which version/country you are using can help me find it...

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
