### ISSUE TITLE
[Event Request] table 1003 "Job Planning Line" - OnAfterAssignFieldsForNo

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13336]
We would like to add a new event OnAfterAssignFieldsForNo in the following trigger:

            trigger OnValidate()
            begin
                ValidateModification(xRec."No." <> "No.");

                CheckUsageLinkRelations;

                UpdateReservation(FieldNo("No."));

                UpdateDescription;

                if ("No." = '') or ("No." <> xRec."No.") then begin
                    "Unit of Measure Code" := '';
                    "Qty. per Unit of Measure" := 1;
                    "Variant Code" := '';
                    "Work Type Code" := '';
                    "Gen. Bus. Posting Group" := '';
                    "Gen. Prod. Posting Group" := '';
                    DeleteAmounts;
                    "Cost Factor" := 0;
                    if Type = Type::Item then begin
                        "Bin Code" := '';
                        if ("No." <> '') and ("Location Code" <> '') then begin
                            GetLocation("Location Code");
                            if IsDefaultBin() then
                                WMSManagement.GetDefaultBin("No.", "Variant Code", "Location Code", "Bin Code");
                        end;
                    end;
                    if "No." = '' then
                        exit;
                end;

                GetJob;
                "Customer Price Group" := Job."Customer Price Group";
                "Price Calculation Method" := Job.GetPriceCalculationMethod();
                "Cost Calculation Method" := Job.GetCostCalculationMethod();

                case Type of
                    Type::Resource:
                        CopyFromResource();
                    Type::Item:
                        CopyFromItem();
                    Type::"G/L Account":
                        CopyFromGLAccount();
                    Type::Text:
                        CopyFromStandardText();
                end;
                OnAfterAssignFieldsForNo(Rec, xRec, Job); //A101F0000.Event

                OnValidateNoOnAfterCopyFromAccount(Rec, xRec);

                if Type <> Type::Text then
                    Validate(Quantity);
            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignFieldsForNo(var JobPlanningLine: Record "Job Planning Line"; var xJobPlanningLine: Record "Job Planning Line"; Job: Record Job)
    begin
        //A101F0000.Event
    end;

**Comment by Stepanenko-Vadim** [comment]
Use **OnValidateNoOnAfterCopyFromAccount** instead, we will add the missing parameter there.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
