### ISSUE TITLE
[Event Request] table 99000829 "Planning Component" - OnAfterCopyFromItem

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13344]
We would like to add a new event OnAfterCopyFromItem in the following procedure:

            trigger OnValidate()
            begin
                ReservePlanningComponent.VerifyChange(Rec, xRec);
                CalcFields("Reserved Qty. (Base)");
                TestField("Reserved Qty. (Base)", 0);

                if "Item No." = '' then begin
                    "Dimension Set ID" := 0;
                    "Shortcut Dimension 1 Code" := '';
                    "Shortcut Dimension 2 Code" := '';
                    exit;
                end;

                GetItem;
                Description := Item.Description;
                OnAfterCopyFromItem(Rec, Item); //A200F0000.Event
                Validate("Unit of Measure Code", Item."Base Unit of Measure");
                GetUpdateFromSKU;
                CreateDim(DATABASE::Item, "Item No.");
            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyFromItem(var PlanningComponent: Record "Planning Component"; Item: Record Item)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
