### ISSUE TITLE
[Event Request] table 5876 "Phys. Invt. Order Line" - OnAfterHandleWarehouseEntryTracking

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13342]
We would like to add a new event OnAfterHandleWarehouseEntryTracking in the following procedure:

    procedure CalcQtyAndTrackLinesExpected()
.
.
.

                    if WhseEntry.FindSet then
                        repeat
                            if not
                               ExpPhysInvtTracking.Get(
                                 "Document No.", "Line No.", WhseEntry."Serial No.", WhseEntry."Lot No.")
                            then begin
                                ExpPhysInvtTracking.InsertLine(
                                  "Document No.", "Line No.", WhseEntry."Serial No.", WhseEntry."Lot No.", WhseEntry."Qty. (Base)");
                                OnCalcQtyAndTrackLinesExpectedOnAfterExpPhysInvtTrackingInsertLineFromWhseEntry(ExpPhysInvtTracking, WhseEntry);
                            end else begin
                                ExpPhysInvtTracking."Quantity (Base)" += WhseEntry."Qty. (Base)";
                                OnCalcQtyAndTrackLinesExpectedOnBeforeInsertFromWhseEntry(ExpPhysInvtTracking, WhseEntry);
                                ExpPhysInvtTracking.Modify();
                            end;
                            OnAfterHandleWarehouseEntryTracking(ExpPhysInvtTracking, WhseEntry); //A200F0000
                        until WhseEntry.Next() = 0;
                    ExpPhysInvtTracking.DeleteLine("Document No.", "Line No.", false);
                    TestQtyExpected();
                end else
                    OnCalcQtyAndTrackLinesExpectedOnPhysInvtTrackingNotGet(Rec);
                // In the case of
                // ItemTrkgMgtPhysInvtLine.LocationIsBinMandatory("Location Code") = Yes and
                // ItemTrkgMgtPhysInvtLine.GetTrackingNosFromWhse(Item) = No
                // Navision cannot create the records of table ExpPhysInvtTracking
                // In this case Navision must create the Reservation Entries by
                // analyzing the ItemLedgerEntries and WhseEntries during the function to Finish the Order.
                ;
            end;
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterHandleWarehouseEntryTracking(var ExpPhysInvtTracking: Record "Exp. Phys. Invt. Tracking"; WarehouseEntry: Record "Warehouse Entry")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
