### ISSUE TITLE
[Event Request] Table 81 SetUpNewLine

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/ALAppExtensions#1334]
I Would like to request an event as shown bellow so we can initialize a specific field:
Table 81 - SetupNewLine

![image](https://user-images.githubusercontent.com/13696679/53243675-9260de80-36a0-11e9-8d3a-29caa577a316.png)

**Comment by Hornsyld** [comment]
This would be nice. I will follow this one.
