### ISSUE TITLE
[Event Request] table 5876 "Phys. Invt. Order Line" - OnAfterHandleItemLedgerEntryTracking

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13341]
We would like to add a new event OnAfterHandleItemLedgerEntryTracking in the following procedure:

    procedure CalcQtyAndTrackLinesExpected()
.
.
.

                        end else begin
                            ExpPhysInvtTracking."Quantity (Base)" += ItemLedgEntry.Quantity;
                            OnCalcQtyAndTrackLinesExpectedOnBeforeModifyFromItemLedgEntry(ExpPhysInvtTracking, ItemLedgEntry);
                            ExpPhysInvtTracking.Modify();
                        end;

                        OnAfterHandleItemLedgerEntryTracking(ExpPhysInvtTracking, ItemLedgEntry); //A200F0000
                    until ItemLedgEntry.Next() = 0;
                ExpPhysInvtTracking.DeleteLine("Document No.", "Line No.", false);
                TestQtyExpected();
            end else begin
                if PhysInvtTrackingMgt.GetTrackingNosFromWhse(Item) then begin
                    WhseEntry.Reset();
                    WhseEntry.SetCurrentKey("Location Code", "Bin Code", "Item No.", "Variant Code");
                    WhseEntry.SetRange("Location Code", "Location Code");
                    WhseEntry.SetRange("Bin Code", "Bin Code");
                    WhseEntry.SetRange("Item No.", "Item No.");
                    WhseEntry.SetRange("Variant Code", "Variant Code");
                    WhseEntry.SetRange("Registering Date", 0D, PhysInvtOrderHeader."Posting Date");
                    OnCalcQtyAndTrackLinesExpectedOnAfterSetWhseEntryFilters(WhseEntry, Rec);
                    if WhseEntry.FindSet then
                        repeat
                            if not
                               ExpPhysInvtTracking.Get(
                                 "Document No.", "Line No.", WhseEntry."Serial No.", WhseEntry."Lot No.")
                            then begin
                                ExpPhysInvtTracking.InsertLine(
                                  "Document No.", "Line No.", WhseEntry."Serial No.", WhseEntry."Lot No.", WhseEntry."Qty. (Base)");
                                OnCalcQtyAndTrackLinesExpectedOnAfterExpPhysInvtTrackingInsertLineFromWhseEntry(ExpPhysInvtTracking, WhseEntry);
                            end else begin

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterHandleItemLedgerEntryTracking(var ExpPhysInvtTracking: Record "Exp. Phys. Invt. Tracking"; ItemLedgerEntry: Record "Item Ledger Entry")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
