### ISSUE TITLE
[Event Request] table 7003 "Price Asset" - OnElseUnitOfMeasureCode

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13348]
We would like to add a new event OnElseUnitOfMeasureCode in the following trigger:

            trigger OnValidate()
            var
                ItemUnitofMeasure: Record "Item Unit of Measure";
                ResourceUnitofMeasure: Record "Resource Unit of Measure";
                UnitofMeasure: Record "Unit of Measure";
            begin
                if "Unit of Measure Code" <> '' then
                    case "Asset Type" of
                        "Asset Type"::Item:
                            begin
                                TestField("Asset No.");
                                ItemUnitofMeasure.Get("Asset No.", "Unit of Measure Code");
                            end;
                        "Asset Type"::Resource:
                            begin
                                TestField("Asset No.");
                                ResourceUnitofMeasure.Get("Asset No.", "Unit of Measure Code");
                            end;
                        "Asset Type"::"Resource Group":
                            begin
                                TestField("Asset No.");
                                UnitofMeasure.Get("Unit of Measure Code");
                            end;
                        else
                            //Error(AssetTypeForUOMErr); //A101F0000.Event.o
                            OnElseUnitOfMeasureCode(Rec); //A101F0000.Event.n
                    end;
            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnElseUnitOfMeasureCode(var PriceAsset: Record "Price Asset")
    begin
        //A101F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
