### ISSUE TITLE
[Event Request] table 7001 "Price List Line" - OnAfterIsUOMSupported

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13349]
We would like to add a new event OnAfterIsUOMSupported in the following procedure:

    procedure IsUOMSupported() Result: Boolean;
    begin
        //exit(IsAssetItem() or IsAssetResource()); //A101F0000.Event.o
        //A101F0000.Event.ns
        Result := IsAssetItem() or IsAssetResource();
        OnAfterIsUOMSupported(Rec, Result);
        //A101F0000.Event.ne
    end;

Event Signature: 

  
   [IntegrationEvent(true, false)]
    procedure OnAfterIsUOMSupported(PriceListLine: Record "Price List Line"; var Result: Boolean)
    begin
        //A101F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
