### ISSUE TITLE
[Event Request] table 99000758 "Machine Center" - OnAfterCopyFromWorkCenter

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13340]
We would like to add a new event OnAfterCopyFromWorkCenter in the following trigger:

            trigger OnValidate()
            var
                WorkCenter: Record "Work Center";
                ProdOrderRtngLine: Record "Prod. Order Routing Line";
                ProdOrderCapNeed: Record "Prod. Order Capacity Need";
                PlanningRtngLine: Record "Planning Routing Line";
            begin
                if "Work Center No." = xRec."Work Center No." then
                    exit;

                if "Work Center No." <> '' then begin
                    WorkCenter.Get("Work Center No.");
                    WorkCenter.TestField("Unit of Measure Code");
                    "Queue Time Unit of Meas. Code" := WorkCenter."Queue Time Unit of Meas. Code";
                    "Setup Time Unit of Meas. Code" := WorkCenter."Unit of Measure Code";
                    "Wait Time Unit of Meas. Code" := WorkCenter."Unit of Measure Code";
                    "Move Time Unit of Meas. Code" := WorkCenter."Unit of Measure Code";
                    OnAfterCopyFromWorkCenter(Rec, WorkCenter); //A108F0054.Event
                end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyFromWorkCenter(var MachineCenter: Record "Machine Center"; WorkCenter: Record "Work Center")
    begin
        //A108F0054.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
