### ISSUE TITLE
[Event Request] table 7319 "Posted Whse. Receipt Line" - OnAfterSetTrackingFilterFromItemLedgerEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13347]
We would like to add a new event OnAfterSetTrackingFilterFromItemLedgerEntry in the following procedure:

    procedure SetTrackingFilterFromItemLedgerEntry(ItemLedgerEntry: Record "Item Ledger Entry")
    begin
        //A200F0000.Event.ns
        SetRange("Serial No.", ItemLedgerEntry."Serial No.");
        SetRange("Lot No.", ItemLedgerEntry."Lot No.");

        OnAfterSetTrackingFilterFromItemLedgerEntry(Rec, ItemLedgerEntry);
        //A200F0000.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetTrackingFilterFromItemLedgerEntry(var PostedWhseReceiptLine: Record "Posted Whse. Receipt Line"; ItemLedgerEntry: Record "Item Ledger Entry")
    begin
        //A200F0000.Event
    end;

**Comment by AlexanderYakunin** [comment]
We already have that:

    procedure SetTrackingFilterFromItemLedgEntry(ItemLedgEntry: Record "Item Ledger Entry")
    begin
        SetRange("Serial No.", ItemLedgEntry."Serial No.");
        SetRange("Lot No.", ItemLedgEntry."Lot No.");

        OnAfterSetTrackingFilterFromItemLedgEntry(rec, ItemLedgEntry);
    end;
