### ISSUE TITLE
[Event Request] table 225 "Post Code" - OnAfterValidatePostCode

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13346]
We would like to add a new event OnAfterValidatePostCode in the following procedure:

    procedure ValidatePostCode(var CityTxt: Text[30]; var PostCode: Code[20]; var CountyTxt: Text[30]; var CountryCode: Code[10]; UseDialog: Boolean)
    var
        PostCodeRec: Record "Post Code";
        PostCodeRec2: Record "Post Code";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeValidatePostCode(CityTxt, PostCode, CountyTxt, CountryCode, UseDialog, IsHandled);
        if IsHandled then
            exit;

        if PostCode <> '' then begin
            if StrPos(PostCode, '*') = StrLen(PostCode) then
                PostCodeRec.SetFilter(Code, PostCode)
            else
                PostCodeRec.SetRange(Code, PostCode);
            OnValidatePostCodeOnAfterSetFilters(PostCodeRec);
            if not PostCodeRec.FindFirst then
                exit;

            if CountryCode <> '' then begin
                PostCodeRec.SetRange("Country/Region Code", CountryCode);
                if not PostCodeRec.FindFirst then
                    PostCodeRec.SetRange("Country/Region Code");
            end;

            PostCodeRec2.Copy(PostCodeRec);
            if UseDialog and (PostCodeRec2.Next = 1) and GuiAllowed then
                if PAGE.RunModal(PAGE::"Post Codes", PostCodeRec, PostCodeRec.Code) <> ACTION::LookupOK then
                    exit;
            PostCode := PostCodeRec.Code;
            CityTxt := PostCodeRec.City;
            CountryCode := PostCodeRec."Country/Region Code";
            CountyTxt := PostCodeRec.County;
        end;

        OnAfterValidatePostCode(CityTxt, PostCode, CountyTxt, CountryCode, UseDialog); //A108F0029.Event
    end;

Event Signature:

    [IntegrationEvent(true, false)]
    local procedure OnAfterValidatePostCode(var CityTxt: Text[30]; var PostCode: Code[20]; var CountyTxt: Text[30]; var CountryCode: Code[10]; UseDialog: Boolean)
    begin
        //A108F0029.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
