### ISSUE TITLE
[Event Request] table 5409 "Prod. Order Routing Line" - OnBeforeInsertProdOrderRtngCommentLineFromStandardTask

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13354]
We would like to add a new event OnBeforeInsertProdOrderRtngCommentLineFromStandardTask in the following procedure:

            trigger OnValidate()
            var
                StandardTask: Record "Standard Task";
                StdTaskTool: Record "Standard Task Tool";
                StdTaskPersonnel: Record "Standard Task Personnel";
                StdTaskQltyMeasure: Record "Standard Task Quality Measure";
                StdTaskComment: Record "Standard Task Description";
                ProdOrderRoutingTool: Record "Prod. Order Routing Tool";
                ProdOrderRoutingPersonnel: Record "Prod. Order Routing Personnel";
                ProdOrderRtngQltyMeas: Record "Prod. Order Rtng Qlty Meas.";
                ProdOrderRtngCommentLine: Record "Prod. Order Rtng Comment Line";
            begin
                if "Standard Task Code" = '' then
                    exit;

                StandardTask.Get("Standard Task Code");
                Description := StandardTask.Description;

                DeleteRelations();

                StdTaskTool.SetRange("Standard Task Code", "Standard Task Code");
                if StdTaskTool.Find('-') then
                    repeat
                        ProdOrderRoutingTool.Status := Status;
                        ProdOrderRoutingTool."Prod. Order No." := "Prod. Order No.";
                        ProdOrderRoutingTool."Routing Reference No." := "Routing Reference No.";
                        ProdOrderRoutingTool."Routing No." := "Routing No.";
                        ProdOrderRoutingTool."Operation No." := "Operation No.";
                        ProdOrderRoutingTool."Line No." := StdTaskTool."Line No.";
                        ProdOrderRoutingTool."No." := StdTaskTool."No.";
                        ProdOrderRoutingTool.Description := StdTaskTool.Description;
                        ProdOrderRoutingTool.Insert();
                        OnAfterTransferFromStdTaskTool(ProdOrderRoutingTool, StdTaskTool);
                    until StdTaskTool.Next() = 0;

                StdTaskPersonnel.SetRange("Standard Task Code", "Standard Task Code");
                if StdTaskPersonnel.Find('-') then
                    repeat
                        ProdOrderRoutingPersonnel.Status := Status;
                        ProdOrderRoutingPersonnel."Prod. Order No." := "Prod. Order No.";
                        ProdOrderRoutingPersonnel."Routing Reference No." := "Routing Reference No.";
                        ProdOrderRoutingPersonnel."Routing No." := "Routing No.";
                        ProdOrderRoutingPersonnel."Operation No." := "Operation No.";
                        ProdOrderRoutingPersonnel."Line No." := StdTaskPersonnel."Line No.";
                        ProdOrderRoutingPersonnel."No." := StdTaskPersonnel."No.";
                        ProdOrderRoutingPersonnel.Description := StdTaskPersonnel.Description;
                        ProdOrderRoutingPersonnel.Insert();
                        OnAfterTransferFromStdTaskPersonnel(ProdOrderRoutingPersonnel, StdTaskPersonnel);
                    until StdTaskPersonnel.Next() = 0;

                StdTaskQltyMeasure.SetRange("Standard Task Code", "Standard Task Code");
                if StdTaskQltyMeasure.Find('-') then
                    repeat
                        ProdOrderRtngQltyMeas.Status := Status;
                        ProdOrderRtngQltyMeas."Prod. Order No." := "Prod. Order No.";
                        ProdOrderRtngQltyMeas."Routing Reference No." := "Routing Reference No.";
                        ProdOrderRtngQltyMeas."Routing No." := "Routing No.";
                        ProdOrderRtngQltyMeas."Operation No." := "Operation No.";
                        ProdOrderRtngQltyMeas."Line No." := StdTaskQltyMeasure."Line No.";
                        ProdOrderRtngQltyMeas."Qlty Measure Code" := StdTaskQltyMeasure."Qlty Measure Code";
                        ProdOrderRtngQltyMeas.Description := StdTaskQltyMeasure.Description;
                        ProdOrderRtngQltyMeas."Min. Value" := StdTaskQltyMeasure."Min. Value";
                        ProdOrderRtngQltyMeas."Max. Value" := StdTaskQltyMeasure."Max. Value";
                        ProdOrderRtngQltyMeas."Mean Tolerance" := StdTaskQltyMeasure."Mean Tolerance";
                        ProdOrderRtngQltyMeas.Insert();
                        OnAfterTransferFromStdTaskQltyMeasure(ProdOrderRtngQltyMeas, StdTaskQltyMeasure);
                    until StdTaskQltyMeasure.Next() = 0;

                StdTaskComment.SetRange("Standard Task Code", "Standard Task Code");
                if StdTaskComment.Find('-') then
                    repeat
                        ProdOrderRtngCommentLine.Status := Status;
                        ProdOrderRtngCommentLine."Prod. Order No." := "Prod. Order No.";
                        ProdOrderRtngCommentLine."Routing Reference No." := "Routing Reference No.";
                        ProdOrderRtngCommentLine."Routing No." := "Routing No.";
                        ProdOrderRtngCommentLine."Operation No." := "Operation No.";
                        ProdOrderRtngCommentLine."Line No." := StdTaskComment."Line No.";
                        ProdOrderRtngCommentLine.Comment := StdTaskComment.Text;
                        OnBeforeInsertProdOrderRtngCommentLineFromStandardTask(ProdOrderRtngCommentLine, StdTaskComment); //A108F0041.Event
                        ProdOrderRtngCommentLine.Insert();
                        OnAfterTransferFromStdTaskComment(ProdOrderRtngCommentLine, StdTaskComment);
                    until StdTaskComment.Next() = 0;
            end;

Event Signature: 

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertProdOrderRtngCommentLineFromStandardTask(var ProdOrderRtngCommentLine: Record "Prod. Order Rtng Comment Line"; StdTaskComment: Record "Standard Task Description")
    begin
        //A108F0041.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
