### ISSUE TITLE
[Event Request] table 38 "Purchase Header" - OnAfterCalcArePurchaseLinesEditable

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13358]
We would like to add a new event OnAfterCalcArePurchaseLinesEditable in the following procedure:

    procedure CalcArePurchaseLinesEditable() IsEditable: Boolean;
    begin
        //A113F0000.Event.ns
        IsEditable := "Buy-from Vendor No." <> '';

        OnAfterCalcArePurchaseLinesEditable(Rec, IsEditable);
        //A113F0000.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcArePurchaseLinesEditable(var PurchaseHeader: Record "Purchase Header"; var IsEditable: Boolean)
    begin
        //A113F0000.Event
    end;

**Comment by Oleg-Romashkov** [comment]
Function CalcArePurchaseLinesEditable does not exist. Please check the latest code base.

**Comment by AlexanderYakunin** [comment]
We do not implement additional application code via event requests. Especially parts of you own solution. We need detailed explanation for such requests, better create them on IDEAS portal
