### ISSUE TITLE
[Event Request] table 5406 "Prod. Order Line" - OnAfterAssignItemValues

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13353]
We would like to add a new event OnAfterAssignItemValues in the following trigger:

            trigger OnValidate()
            begin
                ProdOrderLineReserve.VerifyChange(Rec, xRec);
                TestField("Finished Quantity", 0);
                CalcFields("Reserved Quantity");
                TestField("Reserved Quantity", 0);
                WhseValidateSourceLine.ProdOrderLineVerifyChange(Rec, xRec);
                if ("Item No." <> xRec."Item No.") and ("Line No." <> 0) then begin
                    DeleteRelations;
                    "Variant Code" := '';
                end;
                if "Item No." = '' then
                    Init
                else begin
                    ProdOrder.Get(Status, "Prod. Order No.");
                    "Starting Date" := ProdOrder."Starting Date";
                    "Starting Time" := ProdOrder."Starting Time";
                    "Ending Date" := ProdOrder."Ending Date";
                    "Ending Time" := ProdOrder."Ending Time";
                    "Due Date" := ProdOrder."Due Date";
                    "Location Code" := ProdOrder."Location Code";
                    "Bin Code" := ProdOrder."Bin Code";

                    GetItem;
                    Item.TestField("Inventory Posting Group");
                    "Inventory Posting Group" := Item."Inventory Posting Group";

                    Description := Item.Description;
                    "Description 2" := Item."Description 2";
                    "Production BOM No." := Item."Production BOM No.";
                    "Routing No." := Item."Routing No.";

                    "Scrap %" := Item."Scrap %";
                    "Unit Cost" := Item."Unit Cost";
                    "Indirect Cost %" := Item."Indirect Cost %";
                    "Overhead Rate" := Item."Overhead Rate";
                    OnAfterAssignItemValues(Rec, Item); //A200F0000.Event
                    if "Item No." <> xRec."Item No." then begin
                        Validate("Production BOM No.", Item."Production BOM No.");
                        Validate("Routing No.", Item."Routing No.");
                        if "Production BOM No." = '' then //A108B0073.n
                            Validate("Unit of Measure Code", Item."Base Unit of Measure");
                    end;

Event Signature: 

    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignItemValues(var ProdOrderLine: Record "Prod. Order Line"; Item: Record Item)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
