### ISSUE TITLE
[Event Request] table 38 "Purchase Header" - OnBeforeUpdatePayToVendorNoFromContBusinessRelation

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13357]
We would like to add a new event OnBeforeUpdatePayToVendorNoFromContBusinessRelation in the following procedure:

    local procedure UpdatePayToVend(ContactNo: Code[20])
    var
        ContBusinessRelation: Record "Contact Business Relation";
        Vend: Record Vendor;
        Cont: Record Contact;
    begin
        if Cont.Get(ContactNo) then begin
            "Pay-to Contact No." := Cont."No.";
            if Cont.Type = Cont.Type::Person then
                "Pay-to Contact" := Cont.Name
            else
                if Vend.Get("Pay-to Vendor No.") then
                    "Pay-to Contact" := Vend.Contact
                else
                    "Pay-to Contact" := '';
        end else begin
            "Pay-to Contact" := '';
            exit;
        end;

        OnBeforeUpdatePayToVendorNoFromContBusinessRelation(Rec, Vend, Cont); //A108F0013.Event
        if ContBusinessRelation.FindByContact(ContBusinessRelation."Link to Table"::Vendor, Cont."Company No.") then begin
            if "Pay-to Vendor No." = '' then begin
                SkipPayToContact := true;
                Validate("Pay-to Vendor No.", ContBusinessRelation."No.");
                SkipPayToContact := false;
            end else
                if "Pay-to Vendor No." <> ContBusinessRelation."No." then
                    Error(Text037, Cont."No.", Cont.Name, "Pay-to Vendor No.");
        end else
            ContactIsNotRelatedToVendorError(Cont, ContactNo);
        OnAfterUpdatePayToVend(Rec, Cont);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdatePayToVendorNoFromContBusinessRelation(var PurchaseHeader: Record "Purchase Header"; Vendor: Record Vendor; Contact: Record Contact)
    begin
        //A108F0013.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
