### ISSUE TITLE
[Event Request] table 38 "Purchase Header" - OnAfterCopyShipToCustomerFields

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13356]
We would like to add a new event OnAfterCopyShipToCustomerFields in the following trigger:

            trigger OnValidate()
            var
                ShipToAddr: Record "Ship-to Address";
            begin
                CheckShipToCodeChange(Rec);

                if "Ship-to Code" <> '' then begin
                    ShipToAddr.Get("Sell-to Customer No.", "Ship-to Code");
                    SetShipToAddress(
                      ShipToAddr.Name, ShipToAddr."Name 2", ShipToAddr.Address, ShipToAddr."Address 2",
                      ShipToAddr.City, ShipToAddr."Post Code", ShipToAddr.County, ShipToAddr."Country/Region Code");
                    "Ship-to Contact" := ShipToAddr.Contact;
                    "Shipment Method Code" := ShipToAddr."Shipment Method Code";
                    if ShipToAddr."Location Code" <> '' then
                        Validate("Location Code", ShipToAddr."Location Code");
                    OnAfterCopyShipToAddressFields(Rec, ShipToAddr); //A108F0011.Event
                end else begin
                    TestField("Sell-to Customer No.");
                    Cust.Get("Sell-to Customer No.");
                    SetShipToAddress(
                      Cust.Name, Cust."Name 2", Cust.Address, Cust."Address 2",
                      Cust.City, Cust."Post Code", Cust.County, Cust."Country/Region Code");
                    "Ship-to Contact" := Cust.Contact;
                    "Shipment Method Code" := Cust."Shipment Method Code";
                    if Cust."Location Code" <> '' then
                        Validate("Location Code", Cust."Location Code");
                    OnAfterCopyShipToCustomerFields(Rec, Cust); //A108F0011.Event
                end;
            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyShipToCustomerFields(var PurchaseHeader: Record "Purchase Header"; Customer: Record "Customer");
    begin
        //A108F0011.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
