### ISSUE TITLE
[Event Request] table 337 "Reservation Entry" - OnAfterCopyTrackingFiltersToReservationEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13368]
We would like to add a new event OnAfterCopyTrackingFiltersToReservationEntry in the following procedure:

    procedure CopyTrackingFiltersToReservationEntry(var ReservationEntry: Record "Reservation Entry")
    begin
        //A200F0000.Event.ns
        CopyFilter("Serial No.", ReservationEntry."Serial No.");
        CopyFilter("Lot No.", ReservationEntry."Lot No.");

        OnAfterCopyTrackingFiltersToReservationEntry(Rec, ReservationEntry);
        //A200F0000.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyTrackingFiltersToReservationEntry(var FromReservationEntry: Record "Reservation Entry"; var ToReservationEntry: Record "Reservation Entry")
    begin
        //A200F0000.Event
    end;

**Comment by Oleg-Romashkov** [comment]
Function CopyTrackingFiltersToReservationEntry does not exist. Please check the latest code base.

**Comment by AlexanderYakunin** [comment]
We already have this

    procedure CopyTrackingFiltersToReservEntry(var FilterReservEntry: Record "Reservation Entry")
    begin
        CopyFilter("Serial No.", FilterReservEntry."Serial No.");
        CopyFilter("Lot No.", FilterReservEntry."Lot No.");

        OnAfterCopyTrackingFiltersToReservEntry(Rec, FilterReservEntry);
#if not CLEAN17
        OnAfterCopyTrackingFiltersToResernEntry(Rec, FilterReservEntry); // Obsoleted
#endif
    end;
