### ISSUE TITLE
[Event Request] table 295 "Reminder Header" - OnAfterSetReminderTextFilter

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13364]
We would like to add a new event OnAfterSetReminderTextFilter in the following 2 procedures:

Procedure 1:

    local procedure InsertBeginTexts(ReminderHeader: Record "Reminder Header")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeInsertBeginTexts(ReminderHeader, IsHandled);
        if IsHandled then
            exit;

        ReminderLevel.SetRange("Reminder Terms Code", ReminderHeader."Reminder Terms Code");
        ReminderLevel.SetRange("No.", 1, ReminderHeader."Reminder Level");
        if ReminderLevel.FindLast then begin
            ReminderText.Reset();
            ReminderText.SetRange("Reminder Terms Code", ReminderHeader."Reminder Terms Code");
            ReminderText.SetRange("Reminder Level", ReminderLevel."No.");
            ReminderText.SetRange(Position, ReminderText.Position::Beginning);
            OnAfterSetReminderTextFilter(ReminderText, ReminderHeader); //A108F0065.Event

            ReminderLine.Reset();
            ReminderLine.SetRange("Reminder No.", ReminderHeader."No.");
            ReminderLine."Reminder No." := ReminderHeader."No.";
            if ReminderLine.Find('-') then begin
                LineSpacing := ReminderLine."Line No." div (ReminderText.Count + 2);
                if LineSpacing = 0 then
                    Error(Text004);
            end else
                LineSpacing := 10000;
            NextLineNo := 0;
            InsertTextLines(ReminderHeader);
        end;
    end;

Procedure 2:

    local procedure InsertEndTexts(ReminderHeader: Record "Reminder Header")
    var
        ReminderLine2: Record "Reminder Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeInsertEndTexts(ReminderHeader, IsHandled);
        if IsHandled then
            exit;

        ReminderLevel.SetRange("Reminder Terms Code", ReminderHeader."Reminder Terms Code");
        ReminderLevel.SetRange("No.", 1, ReminderHeader."Reminder Level");
        if ReminderLevel.FindLast then begin
            ReminderText.SetRange(
              "Reminder Terms Code", ReminderHeader."Reminder Terms Code");
            ReminderText.SetRange("Reminder Level", ReminderLevel."No.");
            ReminderText.SetRange(Position, ReminderText.Position::Ending);
            OnAfterSetReminderTextFilter(ReminderText, ReminderHeader); //A108F0065.Event
            ReminderLine.Reset();
            ReminderLine.SetRange("Reminder No.", ReminderHeader."No.");
            ReminderLine.SetFilter(
              "Line Type", '%1|%2|%3',
              ReminderLine."Line Type"::"Reminder Line",
              ReminderLine."Line Type"::"Additional Fee",
              ReminderLine."Line Type"::Rounding);
            ReminderLine.SetRange("Line Type"); //A108F0065.n
            if ReminderLine.FindLast then
                NextLineNo := ReminderLine."Line No."
            else
                NextLineNo := 0;
            ReminderLine.SetRange("Line Type");
            ReminderLine2 := ReminderLine;
            ReminderLine2.CopyFilters(ReminderLine);
            ReminderLine2.SetFilter("Line Type", '<>%1', ReminderLine2."Line Type"::"Line Fee");
            ReminderLine2.SetRange("Line Type"); //A108F0065.n
            if ReminderLine2.Next <> 0 then begin
                LineSpacing :=
                  (ReminderLine2."Line No." - ReminderLine."Line No.") div
                  (ReminderText.Count + 2);
                if LineSpacing = 0 then
                    Error(Text004);
            end else
                LineSpacing := 10000;
            InsertTextLines(ReminderHeader);
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetReminderTextFilter(var ReminderText: Record "Reminder Text"; ReminderHeader: Record "Reminder Header")
    begin
        //A108F0065.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
