### ISSUE TITLE
[Event Request] table 39 "Purchase Line" - OnBeforeCalculateOrderDateBOC2OnValidateRequestedReceiptDate

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13360]
We would like to add a new event OnBeforeCalculateOrderDateBOC2OnValidateRequestedReceiptDate in the following trigger:

            trigger OnValidate()
            var
                CustomCalendarChange: Array[2] of Record "Customized Calendar Change";
                IsHandled: Boolean;
            begin
                IsHandled := false;
                OnBeforeValidateRequestedReceiptDate(Rec, xRec, CustomCalendarChange, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;

                if (CurrFieldNo <> 0) and
                   ("Promised Receipt Date" <> 0D)
                then
                    Error(
                      Text023,
                      FieldCaption("Requested Receipt Date"),
                      FieldCaption("Promised Receipt Date"));

                if "Requested Receipt Date" <> 0D then begin
                    CustomCalendarChange[1].SetSource(CalChange."Source Type"::Vendor, "Buy-from Vendor No.", '', '');
                    CustomCalendarChange[2].SetSource(CalChange."Source Type"::Location, "Location Code", '', '');
                    //A108F0071.Event.ns
                    IsHandled := false;
                    OnBeforeCalculateOrderDateBOC2OnValidateRequestedReceiptDate(Rec, CustomCalendarChange, IsHandled);
                    if not IsHandled then
                        //A108F0071.Event.ne
                        Validate("Order Date",
                            CalendarMgmt.CalcDateBOC2(AdjustDateFormula("Lead Time Calculation"), "Requested Receipt Date", CustomCalendarChange, true))
                end else
                    if "Requested Receipt Date" <> xRec."Requested Receipt Date" then
                        GetUpdateBasicDates;
            end;

Event Signature:

    [IntegrationEvent(true, false)]
    local procedure OnBeforeCalculateOrderDateBOC2OnValidateRequestedReceiptDate(var PurchaseLine: Record "Purchase Line"; CustomCalendarChange: Array[2] of Record "Customized Calendar Change"; var IsHandled: Boolean)
    begin
        //A108F0071.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
