### ISSUE TITLE
[Event Request] table 337 "Reservation Entry" - OnAfterHasSameItemTrackingValues

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13369]
We would like to add a new event OnAfterHasSameItemTrackingValues in the following procedure: 

    procedure HasSameItemTrackingValues(ReservationEntry: Record "Reservation Entry") SameItemTrackingValues: Boolean
    begin
        //A200F0000.Event.ns
        SameItemTrackingValues := ("Lot No." = ReservationEntry."Lot No.") and ("Serial No." = ReservationEntry."Serial No.");

        OnAfterHasSameItemTrackingValues(Rec, ReservationEntry, SameItemTrackingValues);
        //A200F0000.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterHasSameItemTrackingValues(ReservationEntry1: Record "Reservation Entry"; ReservationEntry2: Record "Reservation Entry"; var SameItemTrackingValues: Boolean)
    begin
        //A200F0000.Event        
    end;

**Comment by Oleg-Romashkov** [comment]
Function HasSameItemTrackingValues does not exist. Please check the latest code base.

**Comment by AlexanderYakunin** [comment]
Please use existing procedure

    procedure HasSameTracking(ReservEntry: Record "Reservation Entry") IsSameTracking: Boolean
    begin
        IsSameTracking := ("Serial No." = ReservEntry."Serial No.") and ("Lot No." = ReservEntry."Lot No.");

        OnAfterHasSameTracking(Rec, ReservEntry, IsSameTracking);
    end;
