### ISSUE TITLE
[Event Request] table 337 "Reservation Entry" - OnAfterSetNewTrackingFilterFromReservEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13367]
We would like to add a new event OnAfterSetNewTrackingFilterFromReservEntry in the following procedure:

    procedure SetNewTrackingFilterFromReservEntry(ReservationEntry: Record "Reservation Entry")
    begin
        //A200F0000.Event.ns
        SetRange("New Serial No.", ReservationEntry."New Serial No.");
        SetRange("New Lot No.", ReservationEntry."New Lot No.");

        OnAfterSetNewTrackingFilterFromReservEntry(Rec, ReservationEntry);
        //A200F0000.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetNewTrackingFilterFromReservEntry(var ReservationEntry: Record "Reservation Entry"; FromReservationEntry: Record "Reservation Entry")
    begin
        //A200F0000.Event        
    end;

**Comment by Oleg-Romashkov** [comment]
Function SetNewTrackingFilterFromReservEntry does not exist. Please check the latest code base.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
