### ISSUE TITLE
[Event Request] table 39 "Purchase Line" - OnBeforeCalculateOrderDateBOC2OnValidatePlannedReceiptDate

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13361]
We would like to add a new event OnBeforeCalculateOrderDateBOC2OnValidatePlannedReceiptDate in the following trigger:

            trigger OnValidate()
            var
                CustomCalendarChange: Array[2] of Record "Customized Calendar Change";
                IsHandled: Boolean;
            begin
                if "Promised Receipt Date" <> 0D then begin
                    if "Planned Receipt Date" <> 0D then begin
                        CustomCalendarChange[1].SetSource(CalChange."Source Type"::Location, "Location Code", '', '');
                        "Expected Receipt Date" :=
                          CalendarMgmt.CalcDateBOC(InternalLeadTimeDays("Planned Receipt Date"), "Planned Receipt Date", CustomCalendarChange, false)
                    end else
                        "Expected Receipt Date" := "Planned Receipt Date";
                end else
                    if "Planned Receipt Date" <> 0D then begin
                        CustomCalendarChange[1].SetSource(CalChange."Source Type"::Vendor, "Buy-from Vendor No.", '', '');
                        CustomCalendarChange[2].SetSource(CalChange."Source Type"::Location, "Location Code", '', '');
                        //A108F0071.Event.ns
                        IsHandled := false;
                        OnBeforeCalculateOrderDateBOC2OnValidatePlannedReceiptDate(Rec, CustomCalendarChange, IsHandled);
                        if not IsHandled then
                            //A108F0071.Event.ne
                            "Order Date" :=
                                CalendarMgmt.CalcDateBOC2(AdjustDateFormula("Lead Time Calculation"), "Planned Receipt Date", CustomCalendarChange, true);
                        CustomCalendarChange[1].SetSource(CalChange."Source Type"::Location, "Location Code", '', '');
                        if not ExpectedReceiptDateCalculated then //A108F0071.n
                            "Expected Receipt Date" :=
                              CalendarMgmt.CalcDateBOC(InternalLeadTimeDays("Planned Receipt Date"), "Planned Receipt Date", CustomCalendarChange, false)
                    end else
                        GetUpdateBasicDates;

                if not TrackingBlocked then
                    CheckDateConflict.PurchLineCheck(Rec, CurrFieldNo <> 0);
            end;

Event Signature:

    [IntegrationEvent(true, false)]
    local procedure OnBeforeCalculateOrderDateBOC2OnValidatePlannedReceiptDate(var PurchaseLine: Record "Purchase Line"; CustomCalendarChange: Array[2] of Record "Customized Calendar Change"; var IsHandled: Boolean)
    begin
        //A108F0071.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
