### ISSUE TITLE
Issue in an Event of the Table Assemble-to-Order Link 

### ISSUE THREAD

**Issue by FLX01** [microsoft/ALAppExtensions#13376]
In the Event OnMakeAsmOrderLinkedToSalesOrderLineOnBeforeCheckDocumentType the variables FromSalesLine and ToSalesOrderLine are passed reversed.

![EventPublish](https://user-images.githubusercontent.com/6044559/126285405-b1ac1a5e-3d73-4d24-bda3-7230acbaac73.png)
![EventRaise](https://user-images.githubusercontent.com/6044559/126285418-dbedf618-c99f-4f06-b1ee-800dc406e28e.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
