### ISSUE TITLE
[Event Request] table 99000764 "Routing Line" - OnBeforeInsertRoutingCommentLineFromStandardTask

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13370]
We would like to add a new event OnBeforeInsertRoutingCommentLineFromStandardTask in the following trigger:

            trigger OnValidate()
            var
                StandardTask: Record "Standard Task";
            begin
                if "Standard Task Code" = '' then
                    if "Standard Task Code" <> xRec."Standard Task Code" then begin
                        DeleteRelations;
                        exit;
                    end;

                StandardTask.Get("Standard Task Code");
                Description := StandardTask.Description;

                DeleteRelations;

                StdTaskTool.SetRange("Standard Task Code", "Standard Task Code");
                if StdTaskTool.Find('-') then
                    repeat
                        RtngTool."Routing No." := "Routing No.";
                        RtngTool."Version Code" := "Version Code";
                        RtngTool."Operation No." := "Operation No.";
                        RtngTool."Line No." := StdTaskTool."Line No.";
                        RtngTool."No." := StdTaskTool."No.";
                        RtngTool.Description := StdTaskTool.Description;
                        RtngTool.Insert();
                    until StdTaskTool.Next() = 0;

                StdTaskPersonnel.SetRange("Standard Task Code", "Standard Task Code");
                if StdTaskPersonnel.Find('-') then
                    repeat
                        RtngPersonnel."Routing No." := "Routing No.";
                        RtngPersonnel."Version Code" := "Version Code";
                        RtngPersonnel."Operation No." := "Operation No.";
                        RtngPersonnel."Line No." := StdTaskPersonnel."Line No.";
                        RtngPersonnel."No." := StdTaskPersonnel."No.";
                        RtngPersonnel.Description := StdTaskPersonnel.Description;
                        RtngPersonnel.Insert();
                    until StdTaskPersonnel.Next() = 0;

                StdTaskQltyMeasure.SetRange("Standard Task Code", "Standard Task Code");
                if StdTaskQltyMeasure.Find('-') then
                    repeat
                        RtngQltyMeasure."Routing No." := "Routing No.";
                        RtngQltyMeasure."Version Code" := "Version Code";
                        RtngQltyMeasure."Operation No." := "Operation No.";
                        RtngQltyMeasure."Line No." := StdTaskQltyMeasure."Line No.";
                        RtngQltyMeasure."Qlty Measure Code" := StdTaskQltyMeasure."Qlty Measure Code";
                        RtngQltyMeasure.Description := StdTaskQltyMeasure.Description;
                        RtngQltyMeasure."Min. Value" := StdTaskQltyMeasure."Min. Value";
                        RtngQltyMeasure."Max. Value" := StdTaskQltyMeasure."Max. Value";
                        RtngQltyMeasure."Mean Tolerance" := StdTaskQltyMeasure."Mean Tolerance";
                        RtngQltyMeasure.Insert();
                    until StdTaskQltyMeasure.Next() = 0;

                StdTaskComment.SetRange("Standard Task Code", "Standard Task Code");
                if StdTaskComment.Find('-') then
                    repeat
                        RtngComment."Routing No." := "Routing No.";
                        RtngComment."Version Code" := "Version Code";
                        RtngComment."Operation No." := "Operation No.";
                        RtngComment."Line No." := StdTaskComment."Line No.";
                        RtngComment.Comment := StdTaskComment.Text;
                        OnBeforeInsertRoutingCommentLineFromStandardTask(RtngComment, StdTaskComment); //A108F0041.Event
                        RtngComment.Insert();
                    until StdTaskComment.Next() = 0;
            end;

Event Signature: 

   [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertRoutingCommentLineFromStandardTask(var RoutingCommentLine: Record "Routing Comment Line"; StdTaskComment: Record "Standard Task Description")
    begin
        //A108F0041.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
