### ISSUE TITLE
[Enum Request] Table 1173 Document Attachment, Field 6 File Type

### ISSUE THREAD

**Issue by j2associates** [microsoft/ALAppExtensions#13379]
There is no easy way to extend Option fields, so making this an Enum instead would greatly simplify things.
1.  Change field 6 File Type from Option to Extensible Enum.
2. As first extensibilities, add Text, Csv and Custom which is a special case Other

Table 1173 is the Document Attachment table.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
