### ISSUE TITLE
[Event Request]  Modify(PayTo)VendorAddress Event

### ISSUE THREAD

**Issue by TBorgerink** [microsoft/ALAppExtensions#13378]
Is it possible to add an "OnBefore" event to the procedures ModifyPayToVendorAddress and ModifyVendorAddress or otherwise add the Procedure TestStatusOpen to the mentioned procedures in Table 38 Purchase Header. 

From:
LOCAL Modify(PayTo)VendorAddress()
GetPurchSetup;
... #line11

To:
LOCAL Modify(PayTo)VendorAddress()
OnBeforeModify(PayTo)VendorAddress(Rec,xRec,IsHandled);
if IsHandled then
  exit;
GetPurchSetup;
... #line11

Or to:
LOCAL Modify(PayTo)VendorAddress()
TestStatusOpen;
GetPurchSetup;
... #line11

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
