### ISSUE TITLE
[Event-Request] table 1670 "Option Lookup Buffer" - OnBeforeIncludeOption

### ISSUE THREAD

**Issue by Duffy77** [microsoft/ALAppExtensions#13377]
Hi,
is it possible, that the existing Publisher "OnBeforeIncludeOption" is extended with the Document Type?

At this Point it is only for Sales or Purchase in general, but it would be very nice if we can differ the options by document type.

Thanks in advice

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
