### ISSUE TITLE
[Event Request] table 36 "Sales Header" - OnAfterCalcAreSalesLinesEditable

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13373]
We would like to add a new event OnAfterCalcAreSalesLinesEditable in the following procedure:

    procedure CalcAreSalesLinesEditable() IsEditable: Boolean;
    begin
        //A113F0000.Event.ns
        if "Document Type" = "Document Type"::Quote then
            IsEditable := ("Sell-to Customer No." <> '') or ("Sell-to Customer Template Code" <> '') or ("Sell-to Contact No." <> '')
        else
            IsEditable := "Sell-to Customer No." <> '';

        OnAfterCalcAreSalesLinesEditable(Rec, IsEditable);
        //A113F0000.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcAreSalesLinesEditable(var SalesHeader: Record "Sales Header"; var IsEditable: Boolean)
    begin
        //A113F0000.Event
    end;

**Comment by Oleg-Romashkov** [comment]
Function CalcAreSalesLinesEditable does not exist. Please check the latest code base.

**Comment by AlexanderYakunin** [comment]
We do not implement additional application code via event requests. Especially parts of you own solution. We need detailed explanation for such requests, better create them on IDEAS portal
