### ISSUE TITLE
[Event Request] table 36 "Sales Header" - OnAfterCopyShipToCustomerAddressFieldsFromContact

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13372]
We would like to add a new event OnAfterCopyShipToCustomerAddressFieldsFromContact in the following procedure:

    local procedure UpdateSellToCust(ContactNo: Code[20])
.
.
.

                if not GetContactAsCompany(Cont, SearchContact) then
                    SearchContact := Cont;
                "Sell-to Customer Name" := SearchContact."Company Name";
                "Sell-to Customer Name 2" := SearchContact."Name 2";
                "Sell-to Phone No." := SearchContact."Phone No.";
                "Sell-to E-Mail" := SearchContact."E-Mail";
                SetShipToAddress(
                  SearchContact."Company Name", SearchContact."Name 2", SearchContact.Address, SearchContact."Address 2",
                  SearchContact.City, SearchContact."Post Code", SearchContact.County, SearchContact."Country/Region Code");
                OnAfterCopyShipToCustomerAddressFieldsFromContact(Rec, SearchContact); //A108F0011.Event
                #if not CLEAN18
                if not CustomerTemplMgt.IsEnabled() then begin
                    if ("Sell-to Customer Template Code" = '') and (not CustTemplate.IsEmpty) then
                        Validate("Sell-to Customer Template Code", Cont.FindCustomerTemplate());
                end else
              #endif

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyShipToCustomerAddressFieldsFromContact(var SalesHeader: Record "Sales Header"; SearchContact: Record Contact)
    begin
        //A108F0011.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
