### ISSUE TITLE
[Event Request] table 5900 "Service Header" - OnBeforeUpdateShipToAddress

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13389]
We would like to add a new event OnBeforeUpdateShipToAddress in the following procedure:

    local procedure UpdateShipToAddress()
    var
        Location: Record Location;
        CompanyInfo: Record "Company Information";
        IsHandled: Boolean;
    begin
        //A108F0023.Event.ns
        OnBeforeUpdateShipToAddress(Rec, IsHandled);
        if IsHandled then
            exit;
        //A108F0023.Event.ne
        if "Document Type" = "Document Type"::"Credit Memo" then begin
            if "Location Code" <> '' then begin
                Location.Get("Location Code");
                SetShipToAddress(
                  Location.Name, Location."Name 2", Location.Address, Location."Address 2",
                  Location.City, Location."Post Code", Location.County, Location."Country/Region Code");
                "Ship-to Contact" := Location.Contact;
            end else begin
                CompanyInfo.Get();
                "Ship-to Code" := '';
                SetShipToAddress(
                  CompanyInfo."Ship-to Name", CompanyInfo."Ship-to Name 2", CompanyInfo."Ship-to Address", CompanyInfo."Ship-to Address 2",
                  CompanyInfo."Ship-to City", CompanyInfo."Ship-to Post Code", CompanyInfo."Ship-to County",
                  CompanyInfo."Ship-to Country/Region Code");
                "Ship-to Contact" := CompanyInfo."Ship-to Contact";
            end;
            "VAT Country/Region Code" := "Country/Region Code";
        end;

        OnAfterUpdateShipToAddress(Rec);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateShipToAddress(var ServiceHeader: Record "Service Header"; var IsHandled: Boolean)
    begin
        //A108F0023.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
