### ISSUE TITLE
[Event Request] table 5965 "Service Contract Header" - OnBeforeUpdateBillToCustomerNoFromContBusinessRelation

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13385]
We would like to add a new event OnBeforeUpdateBillToCustomerNoFromContBusinessRelation in the following procedure:

    local procedure UpdateBillToCust(ContactNo: Code[20])
    var
        ContBusinessRelation: Record "Contact Business Relation";
        Cust: Record Customer;
        Cont: Record Contact;
    begin
        if Cont.Get(ContactNo) then begin
            "Bill-to Contact No." := Cont."No.";
            if Cont.Type = Cont.Type::Person then
                "Bill-to Contact" := Cont.Name
            else
                if Cust.Get("Bill-to Customer No.") then
                    "Bill-to Contact" := Cust.Contact
                else
                    "Bill-to Contact" := '';
        end else begin
            "Bill-to Contact" := '';
            exit;
        end;

        OnBeforeUpdateBillToCustomerNoFromContBusinessRelation(rec, Cust, Cont); //A108F0013.Event
        if ContBusinessRelation.FindByContact(ContBusinessRelation."Link to Table"::Customer, Cont."Company No.") then begin
            if "Bill-to Customer No." = '' then begin
                SkipBillToContact := true;
                Validate("Bill-to Customer No.", ContBusinessRelation."No.");
                SkipBillToContact := false;
            end else
                if "Bill-to Customer No." <> ContBusinessRelation."No." then
                    Error(Text044, Cont."No.", Cont.Name, "Bill-to Customer No.");
        end else
            Error(Text051, Cont."No.", Cont.Name);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateBillToCustomerNoFromContBusinessRelation(var ServiceContractHeader: Record "Service Contract Header"; Customer: Record Customer; Contact: Record Contact)
    begin
        //A108F0013.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
