### ISSUE TITLE
[Event Request] table 37 "Sales Line" - OnBeforeSumVATAmountLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13382]
We would like to add a new event OnBeforeSumVATAmountLine in the following procedure:

    procedure CalcVATAmountLines(QtyType: Option General,Invoicing,Shipping; var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; var VATAmountLine: Record "VAT Amount Line"; IncludePrepayments: Boolean)
    var
        TotalVATAmount: Decimal;
        QtyToHandle: Decimal;
        AmtToHandle: Decimal;
        RoundingLineInserted: Boolean;
    begin
        if IsCalcVATAmountLinesHandled(SalesHeader, SalesLine, VATAmountLine, QtyType) then
            exit;

        Currency.Initialize(SalesHeader."Currency Code");

        VATAmountLine.DeleteAll();

        with SalesLine do begin
            SetRange("Document Type", SalesHeader."Document Type");
            SetRange("Document No.", SalesHeader."No.");
            OnCalcVATAmountLinesOnAfterSetFilters(SalesLine, SalesHeader);
            if FindSet then
                repeat
                    if not ZeroAmountLine(QtyType) then begin
                        if (Type = Type::"G/L Account") and not "Prepayment Line" then
                            RoundingLineInserted := (("No." = GetCPGInvRoundAcc(SalesHeader)) and "System-Created Entry") or RoundingLineInserted;
                        if "VAT Calculation Type" in
                           ["VAT Calculation Type"::"Reverse Charge VAT", "VAT Calculation Type"::"Sales Tax"]
                        then
                            "VAT %" := 0;
                        if not VATAmountLine.Get(
                             "VAT Identifier", "VAT Calculation Type", "Tax Group Code", false, "Line Amount" >= 0)
                        then
                            VATAmountLine.InsertNewLine(
                              "VAT Identifier", "VAT Calculation Type", "Tax Group Code", false, "VAT %", "Line Amount" >= 0, false);

                        VATAmountLine."VAT Clause Code" := "VAT Clause Code"; //A108F0084.n
                        case QtyType of
                            QtyType::General:
                                begin
                                    VATAmountLine.Quantity += "Quantity (Base)";
                                    OnBeforeSumVATAmountLine(SalesHeader, SalesLine, VATAmountLine, IncludePrepayments, QtyType, QtyToHandle, AmtToHandle); //A108F0084.Event.n
                                    VATAmountLine.SumLine(
                                      "Line Amount", "Inv. Discount Amount", "VAT Difference", "Allow Invoice Disc.", "Prepayment Line");
                                end;
                            QtyType::Invoicing:
                                begin
                                    case true of
                                        ("Document Type" in ["Document Type"::Order, "Document Type"::Invoice]) and
                                      (not SalesHeader.Ship) and SalesHeader.Invoice and (not "Prepayment Line"):
                                            if "Shipment No." = '' then begin
                                                QtyToHandle := GetAbsMin("Qty. to Invoice", "Qty. Shipped Not Invoiced");
                                                VATAmountLine.Quantity += GetAbsMin("Qty. to Invoice (Base)", "Qty. Shipped Not Invd. (Base)");
                                            end else begin
                                                QtyToHandle := "Qty. to Invoice";
                                                VATAmountLine.Quantity += "Qty. to Invoice (Base)";
                                            end;
                                        IsCreditDocType() and (not SalesHeader.Receive) and SalesHeader.Invoice:
                                            if "Return Receipt No." = '' then begin
                                                QtyToHandle := GetAbsMin("Qty. to Invoice", "Return Qty. Rcd. Not Invd.");
                                                VATAmountLine.Quantity += GetAbsMin("Qty. to Invoice (Base)", "Ret. Qty. Rcd. Not Invd.(Base)");
                                            end else begin
                                                QtyToHandle := "Qty. to Invoice";
                                                VATAmountLine.Quantity += "Qty. to Invoice (Base)";
                                            end;
                                        else begin
                                                QtyToHandle := "Qty. to Invoice";
                                                VATAmountLine.Quantity += "Qty. to Invoice (Base)";
                                            end;
                                    end;

                                    OnBeforeSumVATAmountLine(SalesHeader, SalesLine, VATAmountLine, IncludePrepayments, QtyType, QtyToHandle, AmtToHandle); //A108F0084.Event.n                                    
                                    if IncludePrepayments then
                                        AmtToHandle := GetLineAmountToHandleInclPrepmt(QtyToHandle)
                                    else
                                        AmtToHandle := GetLineAmountToHandle(QtyToHandle);
                                    if SalesHeader."Invoice Discount Calculation" <> SalesHeader."Invoice Discount Calculation"::Amount then
                                        VATAmountLine.SumLine(
                                          AmtToHandle, Round("Inv. Discount Amount" * QtyToHandle / Quantity, Currency."Amount Rounding Precision"),
                                          "VAT Difference", "Allow Invoice Disc.", "Prepayment Line")
                                    else
                                        VATAmountLine.SumLine(
                                          AmtToHandle, "Inv. Disc. Amount to Invoice", "VAT Difference", "Allow Invoice Disc.", "Prepayment Line");
                                end;
                            QtyType::Shipping:
                                begin
                                    if "Document Type" in
                                       ["Document Type"::"Return Order", "Document Type"::"Credit Memo"]
                                    then begin
                                        QtyToHandle := "Return Qty. to Receive";
                                        VATAmountLine.Quantity += "Return Qty. to Receive (Base)";
                                    end else begin
                                        QtyToHandle := "Qty. to Ship";
                                        VATAmountLine.Quantity += "Qty. to Ship (Base)";
                                    end;
                                    OnBeforeSumVATAmountLine(SalesHeader, SalesLine, VATAmountLine, IncludePrepayments, QtyType, QtyToHandle, AmtToHandle); //A108F0084.Event.n                                    
                                    if IncludePrepayments then
                                        AmtToHandle := GetLineAmountToHandleInclPrepmt(QtyToHandle)
                                    else
                                        AmtToHandle := GetLineAmountToHandle(QtyToHandle);
                                    VATAmountLine.SumLine(
                                      AmtToHandle, Round("Inv. Discount Amount" * QtyToHandle / Quantity, Currency."Amount Rounding Precision"),
                                      "VAT Difference", "Allow Invoice Disc.", "Prepayment Line");
                                end;
                        end;
                        TotalVATAmount += "Amount Including VAT" - Amount;
                        OnCalcVATAmountLinesOnAfterCalcLineTotals(VATAmountLine, SalesHeader, SalesLine, Currency, QtyType, TotalVATAmount);
                    end;
                until Next() = 0;
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSumVATAmountLine(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; var VATAmountLine: Record "VAT Amount Line"; IncludePrepayments: Boolean; QtyType: Option General,Invoicing,Shipping; var QtyToHandle: Decimal; var AmtToHandle: Decimal)
    begin
        //A108F0084.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
