### ISSUE TITLE
[Event Request] table 5965 "Service Contract Header" - OnAfterSetFieldsBilltoCustomer

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13383]
We would like to add a new event OnAfterSetFieldsBilltoCustomer in the following trigger:

            trigger OnValidate()
            var
                CustCheckCrLimit: Codeunit "Cust-Check Cr. Limit";
                ConfirmManagement: Codeunit "Confirm Management";
            begin
                CheckChangeStatus;
                if xRec."Bill-to Customer No." <> "Bill-to Customer No." then
                    if xRec."Bill-to Customer No." <> '' then begin
                        if HideValidationDialog then
                            Confirmed := true
                        else
                            Confirmed :=
                              ConfirmManagement.GetResponseOrDefault(
                                StrSubstNo(Text014, FieldCaption("Bill-to Customer No.")), true);
                    end else
                        Confirmed := true;

                if Confirmed then begin
                    if "Bill-to Customer No." <> xRec."Bill-to Customer No." then
                        if "Bill-to Customer No." <> '' then begin
                            Cust.Get("Bill-to Customer No.");
                            if Cust."Privacy Blocked" then
                                Cust.CustPrivacyBlockedErrorMessage(Cust, false);
                            if Cust.Blocked = Cust.Blocked::All then
                                Cust.CustBlockedErrorMessage(Cust, false);
                        end;

                    if "Customer No." <> '' then begin
                        Cust.Get("Customer No.");
                        if Cust."Bill-to Customer No." <> '' then
                            if "Bill-to Customer No." = '' then
                                "Bill-to Customer No." := Cust."Bill-to Customer No.";
                    end;
                    if "Bill-to Customer No." = '' then
                        "Bill-to Customer No." := "Customer No.";
                    if Cust.Get("Bill-to Customer No.") then begin
                        "Currency Code" := Cust."Currency Code";
                        "Payment Terms Code" := Cust."Payment Terms Code";
                        Validate("Payment Method Code", Cust."Payment Method Code");
                        "Language Code" := Cust."Language Code";
                        SetSalespersonCode(Cust."Salesperson Code", "Salesperson Code");
                        if not SkipBillToContact then
                            "Bill-to Contact" := Cust.Contact;
                        OnAfterSetFieldsBilltoCustomer(Rec, Cust, SkipBillToContact); //A101F0000.Event
                    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetFieldsBilltoCustomer(var ServiceContractHeader: Record "Service Contract Header"; Customer: Record Customer; SkipBillToContact: Boolean)
    begin
        //A108F0013.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
