### ISSUE TITLE
[Event Request] table 5900 "Service Header" - OnInitInsertOnBeforeInitRecord

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13386]
We would like to add a new event OnInitInsertOnBeforeInitRecord in the following trigger:

    trigger OnInsert()
    begin
        GetServiceMgtSetup();
        if "No." = '' then begin
            TestNoSeries;
            NoSeriesMgt.InitSeries(GetNoSeriesCode, xRec."No. Series", 0D, "No.", "No. Series");
        end;

        CheckDocumentTypeAlreadyUsed();

        OnInitInsertOnBeforeInitRecord(Rec, xRec); //A113F0002.Event
        InitRecord;

        Clear(ServLogMgt);
        ServLogMgt.ServHeaderCreate(Rec);

        if "Salesperson Code" = '' then
            SetDefaultSalesperson;

        if GetFilter("Customer No.") <> '' then begin
            Clear(xRec."Ship-to Code");
            if GetRangeMin("Customer No.") = GetRangeMax("Customer No.") then
                Validate("Customer No.", GetRangeMin("Customer No."));
        end;

        if GetFilter("Contact No.") <> '' then
            if GetRangeMin("Contact No.") = GetRangeMax("Contact No.") then
                Validate("Contact No.", GetRangeMin("Contact No."));
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnInitInsertOnBeforeInitRecord(var ServiceHeader: Record "Service Header"; xServiceHeader: Record "Service Header")
    begin
        //A113F0004.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
