### ISSUE TITLE
[Event Request] table 5900 "Service Header" - OnAfterUpdateBillToContact

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13387]
We would like to add a new event OnAfterUpdateBillToContact in the following procedure:

    local procedure UpdateBillToCont(CustomerNo: Code[20])
    var
        ContBusRel: Record "Contact Business Relation";
        Cont: Record Contact;
        Cust: Record Customer;
    begin
        if Cust.Get(CustomerNo) then begin
            Clear(ServOrderMgt);
            ContactNo := ServOrderMgt.FindContactInformation("Bill-to Customer No.");
            if Cont.Get(ContactNo) then begin
                "Bill-to Contact No." := Cont."No.";
                "Bill-to Contact" := Cont.Name;
            end else begin
                if Cust."Primary Contact No." <> '' then
                    "Bill-to Contact No." := Cust."Primary Contact No."
                else
                    if ContBusRel.FindByRelation(ContBusRel."Link to Table"::Customer, "Bill-to Customer No.") then
                        "Bill-to Contact No." := ContBusRel."Contact No."
                    else
                        "Bill-to Contact No." := '';
                "Bill-to Contact" := Cust.Contact;
            end;
        end;
        OnAfterUpdateBillToContact(Rec, Cust, Cont); //A108F0013.Event
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateBillToContact(var ServiceHeader: Record "Service Header"; Customer: Record Customer; Contact: Record Contact)
    begin
        //A108F0013.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
