### ISSUE TITLE
[Event Request] table 5900 "Service Header" - OnAfterUpdateBillToCustomerContact

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13388]
We would like to add a new event OnAfterUpdateBillToCustomerContact in the following procedure:

    local procedure UpdateBillToCust(ContactNo: Code[20])
    var
        ContBusinessRelation: Record "Contact Business Relation";
        Cust: Record Customer;
        Cont: Record Contact;
    begin
        if Cont.Get(ContactNo) then begin
            "Bill-to Contact No." := Cont."No.";
            if Cont.Type = Cont.Type::Person then
                "Bill-to Contact" := Cont.Name
            else
                if Cust.Get("Bill-to Customer No.") then
                    "Bill-to Contact" := Cust.Contact
                else
                    "Bill-to Contact" := '';
            OnAfterUpdateBillToCustomerContact(Rec, Cust, Cont); //A113F0004.Event
        end else begin
            "Bill-to Contact" := '';
            exit;
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateBillToCustomerContact(var ServiceHeader: Record "Service Header"; Customer: Record Customer; Contact: Record Contact)
    begin
        //A108F0013.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
