### ISSUE TITLE
[Enum Request] Table 1173 Document Attachment, Field 13 Document Type

### ISSUE THREAD

**Issue by j2associates** [microsoft/ALAppExtensions#13380]
1.  Change field 13 Document Type from Option to Extensible Enum.
There is no easy way to extend Option fields, so making this an Enum instead would greatly simplify things, for example, adding support for Service Items.

Table 1173 is the Document Attachment table.

**Comment by AlexanderYakunin** [comment]
This is already implemented

        field(13; "Document Type"; Enum "Attachment Document Type")
        {
            Caption = 'Document Type';
        }
