### ISSUE TITLE
[Event Request] table 25 "Vendor Ledger Entry" - OnBeforeShowDoc

### ISSUE THREAD

**Issue by tvandruten** [microsoft/ALAppExtensions#13381]
[table 21 "Cust. Ledger Entry"] - [procedure ShowDoc()] contains an [OnBeforeShowDoc] event.

Please add the same [OnBeforeShowDoc] event to the [ShowDoc()] procedure on the [table 25 "Vendor Ledger Entry"]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
