### ISSUE TITLE
[Event Request] codeunit 7022 "Item Journal Line - Price" - AddSources()

### ISSUE THREAD

**Issue by skeck** [microsoft/ALAppExtensions#13395]
Could you please add a new event in codeunit 7022 "Item Journal Line - Price" - AddSources()

```
local procedure AddSources()
var
    SourceType: Enum "Price Source Type";
begin
    PriceSourceList.Init();
    case CurrPriceType of
        CurrPriceType::Sale:
            PriceSourceList.Add(SourceType::"All Customers");
        CurrPriceType::Purchase:
            PriceSourceList.Add(SourceType::"All Vendors");
    end;

// New Event ..
OnAfterAddSources(ItemJournalLine, CurrPriceType, PriceSourceList);
// .. New Event
end;

[IntegrationEvent(false, false)]
local procedure OnAfterAddSources(ItemJournalLine: Record "Item Journal Line"; PriceType: Enum "Price Type"; var PriceSourceList: Codeunit "Price Source List")
begin
end;
```

The same event type already exists in e.g. codeunit 7020 "Sales Line - Price". Since all codeunits that implement the interface "Line With Price" have a local procedure AddSources() , it might make sense to standardize the event publishers.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
