### ISSUE TITLE
[Event Request] table 5900 "Service Header" -  OnAfterGetNoSeriesCode

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13391]
We would like to add a new event OnAfterGetNoSeriesCode in the following procedure:

    local procedure GetNoSeriesCode(): Code[20]
    var
        NoSeriesCode: Code[20];
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetNoSeries(Rec, NoSeriesCode, IsHandled);
        if IsHandled then
            exit(NoSeriesCode);

        case "Document Type" of
            "Document Type"::Quote:
                exit(ServSetup."Service Quote Nos.");
            "Document Type"::Order:
                exit(ServSetup."Service Order Nos.");
            "Document Type"::Invoice:
                exit(ServSetup."Service Invoice Nos.");
            "Document Type"::"Credit Memo":
                exit(ServSetup."Service Credit Memo Nos.");
        end;
        //A108F0089.Event.ns
        OnAfterGetNoSeriesCode(Rec, ServSetup, NoSeriesCode);
        exit(NoSeriesMgt.GetNoSeriesWithCheck(NoSeriesCode, true, "No. Series"));
        //A108F0089.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetNoSeriesCode(var ServiceHeader: Record "Service Header"; ServiceMgtSetup: Record "Service Mgt. Setup"; var NoSeriesCode: Code[20])
    begin
        //A108F0089.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
