### ISSUE TITLE
[Event Request] table 5900 "Service Header" - OnAfterCalcAreServiceLinesEditable

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13392]
We would like to add a new event OnAfterCalcAreServiceLinesEditable and a new procedure:

    procedure CalcAreServiceLinesEditable() IsEditable: Boolean;
    begin
        //A113F0000.Event.ns
        IsEditable := "Customer No." <> '';

        OnAfterCalcAreServiceLinesEditable(Rec, IsEditable);
        //A113F0000.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcAreServiceLinesEditable(var ServiceHeader: Record "Service Header"; var IsEditable: Boolean)
    begin
        //A113F0000.Event
    end;

**Comment by Oleg-Romashkov** [comment]
We do not implement additional application code via event requests. Especially parts of you own solution. We need detailed explanation for such requests, better create them on IDEAS portal
