### ISSUE TITLE
[Event Request] table 336 "Tracking Specification" - OnBeforeCheckItemTrackingChange

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13399]
We would like to add a new event OnBeforeCheckItemTrackingChange in the following trigger:

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                if ("Quantity (Base)" * "Quantity Handled (Base)" < 0) or
                   (Abs("Quantity (Base)") < Abs("Quantity Handled (Base)"))
                then
                    FieldError("Quantity (Base)", StrSubstNo(Text002, FieldCaption("Quantity Handled (Base)")));

                //A200F0000.Event.ns
                OnBeforeCheckItemTrackingChange(Rec, CurrFieldNo, IsHandled);
                if not IsHandled then
                    //A200F0000.Event.ne
                    WMSManagement.CheckItemTrackingChange(Rec, xRec);
                InitQtyToShip();
                CheckSerialNoQty();

                ClearApplyToEntryIfQuantityToInvoiceIsNotSufficient();
            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckItemTrackingChange(var TrackingSpecification: Record "Tracking Specification"; CallingFieldNo: Integer; IsHandled: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by Stepanenko-Vadim** [comment]
When requesting an event in a trigger such as OnValidate in a table, please specify which field it refers to. There are usually several OnValidate triggers and sometimes code in them looks pretty familiar, so finding where the event is wanted can be difficult.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
