### ISSUE TITLE
COD1509 - Event Request to Allow Changing Workflow Approval Notification Email Subject

### ISSUE THREAD

**Issue by jeffgit** [Microsoft/ALAppExtensions#1339]
Can we add the event in COD1509 function CreateMailAndDispatch() to allow changing workflow approval notification email subject?

**Comment by JesperSchulz** [comment]
Please be more specific about the parameters you would like us to add and the position of the event. Please look at other event requests for inspiration. Thanks!

**Comment by jeffgit** [comment]
When I looked into it further, I found there is no way to inject an Event to change the subject text constant NotificationMailSubjectTxt with some context from Notification Entry as it's a Label per the code below.
![image](https://user-images.githubusercontent.com/2955741/53534561-389f5080-3ab4-11e9-9ea6-b38609d9ee41.png)

Can you refactor the code so that it allows to pass in something else from the Subscriber function instead of using the Label? It just needs to be right before the function call DocumentMailing.EmailFileWithSubject(), and need NotifcationEntry and SubjectLine as parameters. Or the alternative is to make the subject line configurable in the some Setup table.

**Comment by jeffgit** [comment]
Hello Jesper, can I get an update when this will be added? Thanks!
