### ISSUE TITLE
[Event Request] table 336 "Tracking Specification" - OnBeforeCheckItemTrackingQuantityByType

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13398]
We would like to add a new event OnBeforeCheckItemTrackingQuantityByType and a new procedure:

    procedure CheckItemTrackingQuantity(TableNo: Integer; DocumentType: Option; DocumentNo: Code[20]; LineNo: Integer; ProdOrderLineNo: Integer; QtyToHandleBase: Decimal; QtyToInvoiceBase: Decimal; Handle: Boolean; Invoice: Boolean)
    var
        ReservationEntry: Record "Reservation Entry";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckItemTrackingQuantity(
            Rec, TableNo, DocumentType, DocumentNo, LineNo, ProdOrderLineNo,
            QtyToHandleBase, QtyToInvoiceBase, Handle, Invoice, IsHandled);
        if IsHandled then
            exit;

        if QtyToHandleBase = 0 then
            Handle := false;
        if QtyToInvoiceBase = 0 then
            Invoice := false;
        if not (Handle or Invoice) then
            exit;
        ReservationEntry.SetSourceFilter(TableNo, DocumentType, DocumentNo, LineNo, true);
        if ProdOrderLineNo >= 0 then
            ReservationEntry.SetSourceFilter('', ProdOrderLineNo);
        ReservationEntry.SetFilter("Item Tracking", '%1|%2',
          ReservationEntry."Item Tracking"::"Lot and Serial No.",
          ReservationEntry."Item Tracking"::"Serial No.");
        OnBeforeCheckItemTrackingQuantityByType(ReservationEntry); //A109F0006.Event.n
        CheckItemTrackingByType(ReservationEntry, QtyToHandleBase, QtyToInvoiceBase, false, Handle, Invoice);
        ReservationEntry.SetRange("Item Tracking", ReservationEntry."Item Tracking"::"Lot No.");
        CheckItemTrackingByType(ReservationEntry, QtyToHandleBase, QtyToInvoiceBase, true, Handle, Invoice);

        OnAfterCheckItemTrackingQuantity(Rec, ReservationEntry, TableNo, DocumentType, DocumentNo, LineNo);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckItemTrackingQuantityByType(var ReservationEntry: Record "Reservation Entry")
    begin
        //A109F0006.Event
    end;

**Comment by Stepanenko-Vadim** [comment]
There is already a **OnBeforeCheckItemTrackingByType** in **CheckItemTrackingByType** procedure, you can use that.
