### ISSUE TITLE
[Event Request] table 5900 "Service Header" - OnBeforeUpdateShipToCodeAddressFields

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13390]
We would like to add a new event OnBeforeUpdateShipToCodeAddressFields in the following trigger:

            trigger OnValidate()
            var
                ShipToAddr: Record "Ship-to Address";
                ConfirmManagement: Codeunit "Confirm Management";
                IsHandled: Boolean;
                UpdateShipToAddressFields: Boolean;
            begin
                if ("Ship-to Code" <> xRec."Ship-to Code") and
                   ("Customer No." = xRec."Customer No.")
                then begin
                    if ("Contract No." <> '') and not HideValidationDialog then
                        Error(
                          Text003,
                          FieldCaption("Ship-to Code"),
                          "Document Type", FieldCaption("No."), "No.",
                          FieldCaption("Contract No."), "Contract No.");
                    if ServItemLineExists then begin
                        if not ConfirmManagement.GetResponseOrDefault(
                             StrSubstNo(Text004, FieldCaption("Ship-to Code")), true)
                        then begin
                            "Ship-to Code" := xRec."Ship-to Code";
                            exit;
                        end;
                    end else
                        if ServLineExists then
                            if not ConfirmManagement.GetResponseOrDefault(
                                 StrSubstNo(Text057, FieldCaption("Ship-to Code")), true)
                            then begin
                                "Ship-to Code" := xRec."Ship-to Code";
                                exit;
                            end;
                end;

                //if "Document Type" <> "Document Type"::"Credit Memo" then A108F0023.Event.o
                //A108F0023.Event.ns
                UpdateShipToAddressFields := "Document Type" <> "Document Type"::"Credit Memo";
                OnBeforeUpdateShipToCodeAddressFields(Rec, UpdateShipToAddressFields);
                if UpdateShipToAddressFields then
                    //A108F0023.Event.ne
                    if "Ship-to Code" <> '' then begin
                        if xRec."Ship-to Code" <> '' then begin
                            GetCust("Customer No.");
                            if Cust."Location Code" <> '' then
                                "Location Code" := Cust."Location Code";
                            "Tax Area Code" := Cust."Tax Area Code";
                        end;
                        ShipToAddr.Get("Customer No.", "Ship-to Code");
                        SetShipToCustomerAddressFieldsFromShipToAddr(ShipToAddr);
                    end else
                        if "Customer No." <> '' then begin
                            GetCust("Customer No.");
                            CopyShipToCustomerAddressFieldsFromCust(Cust);
                        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateShipToCodeAddressFields(var ServiceHeader: Record "Service Header"; var UpdateShipToAddressFields: Boolean)
    begin
        //A108F0023.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
