### ISSUE TITLE
[Event Request] table 5902 "Service Line" - OnAfterInitOutstandingQty

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13393]
We would like to add a new event OnAfterInitOutstandingQty in the following procedure:

    procedure InitOutstanding()
    begin
        if "Document Type" = "Document Type"::"Credit Memo" then begin
            "Outstanding Quantity" := Quantity;
            "Outstanding Qty. (Base)" := "Quantity (Base)";
        end else begin
            "Outstanding Quantity" := Quantity - "Quantity Shipped";
            "Outstanding Qty. (Base)" := "Quantity (Base)" - "Qty. Shipped (Base)";
            "Qty. Shipped Not Invoiced" := "Quantity Shipped" - "Quantity Invoiced" - "Quantity Consumed";
            "Qty. Shipped Not Invd. (Base)" := "Qty. Shipped (Base)" - "Qty. Invoiced (Base)" - "Qty. Consumed (Base)";
        end;
        CalcFields("Reserved Quantity");
        Planned := "Reserved Quantity" = "Outstanding Quantity";
        "Completely Shipped" := (Quantity <> 0) and ("Outstanding Quantity" = 0);
        OnAfterInitOutstandingQty(Rec); //A200F0000.Event
        InitOutstandingAmount;

        OnAfterInitOutstanding(Rec);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterInitOutstandingQty(var ServiceLine: Record "Service Line")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
