### ISSUE TITLE
[Event Request] table 5902 "Service Line" - OnAfterAssignFieldsForNo

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13394]
We would like to add a new event OnAfterAssignFieldsForNo in the following trigger:

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                CheckIfCanBeModified;

                TestField("Qty. Shipped Not Invoiced", 0);
                TestField("Quantity Shipped", 0);
                TestField("Shipment No.", '');
                CheckItemAvailable(FieldNo("No."));
                TestStatusOpen;

                ClearFields;

                UpdateReservation(FieldNo("No."));

                if "No." = '' then
                    exit;

                GetServHeader;

                if ServHeader."Document Type" = ServHeader."Document Type"::Quote then begin
                    if ServHeader."Customer No." = '' then
                        Error(
                          Text031,
                          ServHeader.FieldCaption("Customer No."));
                    if ServHeader."Bill-to Customer No." = '' then
                        Error(
                          Text031,
                          ServHeader.FieldCaption("Bill-to Customer No."));
                end else
                    ServHeader.TestField("Customer No.");

                InitHeaderDefaults(ServHeader);

                if "Service Item Line No." <> 0 then begin
                    ServItemLine.Get("Document Type", "Document No.", "Service Item Line No.");
                    Validate("Contract No.", ServItemLine."Contract No.")
                end else
                    Validate("Contract No.", ServHeader."Contract No.");

                case Type of
                    Type::" ":
                        CopyFromStdTxt;
                    Type::"G/L Account":
                        CopyFromGLAccount;
                    Type::Cost:
                        CopyFromCost;
                    Type::Item:
                        begin
                            CopyFromItem;
                            if ServItem.Get("Service Item No.") then
                                CopyFromServItem(ServItem);
                        end;
                    Type::Resource:
                        CopyFromResource;
                end;

                OnAfterAssignFieldsForNo(Rec, xRec, ServHeader); //A101F0000.Event
                if Type <> Type::" " then begin
                    PlanPriceCalcByField(FieldNo("No."));

                    IsHandled := false;
                    OnBeforeValidateVATProdPostingGroup(Rec, xRec, IsHandled);
                    if not IsHandled then
                        Validate("VAT Prod. Posting Group");
                    Validate("Unit of Measure Code");
                    if Quantity <> 0 then begin
                        InitOutstanding;
                        if "Document Type" = "Document Type"::"Credit Memo" then
                            InitQtyToInvoice
                        else
                            InitQtyToShip;
                        UpdateWithWarehouseShip;
                    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignFieldsForNo(var ServiceLine: Record "Service Line"; var xServiceLine: Record "Service Line"; ServiceHeader: Record "Service Header")
    begin
        //A101F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
