### ISSUE TITLE
[Event Request] table 5741 "Transfer Line" - OnAfterUpdateWithWarehouseShipReceive 

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13405]
We would like to add a new event OnAfterUpdateWithWarehouseShipReceive in the following procedure:

    procedure UpdateWithWarehouseShipReceive()
    var
        IsHandled: Boolean;
    begin
        //A200F0001.Event.ns
        GetTransHeader;
        OnBeforeUpdateWithWarehouseShipReceive(TransHeader, Rec, IsHandled);
        if IsHandled then
            exit;
        //A200F0001.Event.ne
        if Location.RequireShipment("Transfer-from Code") then
            Validate("Qty. to Ship", 0)
        else
            Validate("Qty. to Ship", "Outstanding Quantity");

        if Location.RequireReceive("Transfer-to Code") then
            Validate("Qty. to Receive", 0)
        else begin
            if "In-Transit Code" <> '' then
                Validate("Qty. to Receive", "Qty. in Transit");
            if ("In-Transit Code" = '') and ("Quantity Shipped" = "Quantity Received") then
                Validate("Qty. to Receive", "Qty. to Ship");
        end;

        //OnAfterUpdateWithWarehouseShipReceive(Rec, CurrFieldNo); A200F0001.Event.o
        OnAfterUpdateWithWarehouseShipReceive(TransHeader, Rec, CurrFieldNo); //A200F0001.Event.n
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateWithWarehouseShipReceive(TransferHeader: Record "Transfer Header"; var TransferLine: Record "Transfer Line"; CurrentFieldNo: Integer)
    begin
        //A200F0000.Event Parameter TransferHeader
    end;

**Comment by Oleg-Romashkov** [comment]
You can use existing function GetTransHeaderExternal
