### ISSUE TITLE
[Event Request] table 5767 "Warehouse Activity Line" - OnAfterSetConditionalTrackingFilters

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13408]
We would like to add a new event OnAfterSetConditionalTrackingFilters and a new procedure:

    procedure SetConditionalTrackingFilters()
    begin
        //A200F0000.Event.ns
        SetFilter("Serial No.", "Serial No.");
        SetFilter("Lot No.", "Lot No.");

        OnAfterSetConditionalTrackingFilters(Rec);
        //A200F0000.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetConditionalTrackingFilters(var WarehouseActivityLine: Record "Warehouse Activity Line")
    begin
        //A200F0000.Event
    end;

**Comment by Oleg-Romashkov** [comment]
This function does not exist.

**Comment by AlexanderYakunin** [comment]
We already have this procedure and event, but in more generic way:

    procedure SetTrackingFilterFromWhseActivityLine(WhseActivityLine: Record "Warehouse Activity Line")
    begin
        SetRange("Serial No.", WhseActivityLine."Serial No.");
        SetRange("Lot No.", WhseActivityLine."Lot No.");

        OnAfterSetTrackingFilterFromWhseActivityLine(Rec, WhseActivityLine);
    end;
