### ISSUE TITLE
[Event Request] table 5740 "Transfer Header" - OnAfterAddTransferLineFromReceiptLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13402]
We would like to add a new event OnAfterAddTransferLineFromReceiptLine in the following procedure:

    local procedure AddTransferLineFromReceiptLine(PurchRcptLine: Record "Purch. Rcpt. Line"; LineNo: Integer)
    var
        TransferLine: Record "Transfer Line";
        ItemLedgerEntry: Record "Item Ledger Entry";
        TempItemLedgerEntry: Record "Item Ledger Entry" temporary;
        ItemTrackingDocMgt: Codeunit "Item Tracking Doc. Management";
        ItemTrackingMgt: Codeunit "Item Tracking Management";
    begin
        TransferLine."Document No." := "No.";
        TransferLine."Line No." := LineNo;
        TransferLine.Validate("Item No.", PurchRcptLine."No.");
        TransferLine.Validate("Variant Code", PurchRcptLine."Variant Code");
        TransferLine.Validate(Quantity, PurchRcptLine.Quantity);
        TransferLine.Validate("Unit of Measure Code", PurchRcptLine."Unit of Measure Code");
        TransferLine."Shortcut Dimension 1 Code" := PurchRcptLine."Shortcut Dimension 1 Code";
        TransferLine."Shortcut Dimension 2 Code" := PurchRcptLine."Shortcut Dimension 2 Code";
        TransferLine."Dimension Set ID" := PurchRcptLine."Dimension Set ID";
        //OnAddTransferLineFromReceiptLineOnBeforeTransferLineInsert(TransferLine, PurchRcptLine); A200F0000.Event.o
        OnAddTransferLineFromReceiptLineOnBeforeTransferLineInsert(TransferLine, Rec, PurchRcptLine); //A200F0000.Event.n
        TransferLine.Insert(true);

        PurchRcptLine.FilterPstdDocLnItemLedgEntries(ItemLedgerEntry);
        ItemTrackingDocMgt.CopyItemLedgerEntriesToTemp(TempItemLedgerEntry, ItemLedgerEntry);
        ItemTrackingMgt.CopyItemLedgEntryTrkgToTransferLine(TempItemLedgerEntry, TransferLine);

        //OnAfterAddTransferLineFromReceiptLine(TransferLine, PurchRcptLine, TempItemLedgerEntry); A200F0000.Event.o
        OnAfterAddTransferLineFromReceiptLine(TransferLine, Rec, PurchRcptLine, TempItemLedgerEntry); //A200F0000.Event.n
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterAddTransferLineFromReceiptLine(var TransferLine: Record "Transfer Line"; TransferHeader: Record "Transfer Header"; var PurchRcptLine: Record "Purch. Rcpt. Line"; var TempItemLedgerEntry: Record "Item Ledger Entry")
    begin
        //A200F0000.Event Parameter TransferHeader
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
