### ISSUE TITLE
[Event Request] table 5740 "Transfer Header" - OnAfterInitFromTransferFromLocation

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13401]
We would like to add a new event OnAfterInitFromTransferFromLocation in the following trigger:

            trigger OnValidate()
            var
                Location: Record Location;
                Confirmed: Boolean;
                IsHandled: Boolean;
            begin
                TestStatusOpen;

                IsHandled := false;
                OnBeforeValidateTransferFromCode(Rec, xRec, IsHandled, HideValidationDialog);
                if IsHandled then
                    exit;

                if "Transfer-from Code" <> '' then
                    CheckTransferFromAndToCodesNotTheSame();

                if "Direct Transfer" then
                    VerifyNoOutboundWhseHandlingOnLocation("Transfer-from Code");

                if xRec."Transfer-from Code" <> "Transfer-from Code" then begin
                    if HideValidationDialog or
                       (xRec."Transfer-from Code" = '')
                    then
                        Confirmed := true
                    else
                        Confirmed := Confirm(Text002, false, FieldCaption("Transfer-from Code"));
                    if Confirmed then begin
                        if Location.Get("Transfer-from Code") then begin
                            "Transfer-from Name" := Location.Name;
                            "Transfer-from Name 2" := Location."Name 2";
                            "Transfer-from Address" := Location.Address;
                            "Transfer-from Address 2" := Location."Address 2";
                            "Transfer-from Post Code" := Location."Post Code";
                            "Transfer-from City" := Location.City;
                            "Transfer-from County" := Location.County;
                            "Trsf.-from Country/Region Code" := Location."Country/Region Code";
                            "Transfer-from Contact" := Location.Contact;
                            OnAfterInitFromTransferFromLocation(Rec, Location); //A108F0011.Event
                            if not "Direct Transfer" then begin
                                "Outbound Whse. Handling Time" := Location."Outbound Whse. Handling Time";
                                TransferRoute.GetTransferRoute(
                                  "Transfer-from Code", "Transfer-to Code", "In-Transit Code",
                                  "Shipping Agent Code", "Shipping Agent Service Code");
                                OnAfterGetTransferRoute(Rec, TransferRoute);
                                TransferRoute.GetShippingTime(
                                  "Transfer-from Code", "Transfer-to Code",
                                  "Shipping Agent Code", "Shipping Agent Service Code",
                                  "Shipping Time");
                                CalcReceiptDate();
                            end;
                            TransLine.LockTable();
                            TransLine.SetRange("Document No.", "No.");
                        end;
                        UpdateTransLines(Rec, FieldNo("Transfer-from Code"));
                    end else
                        "Transfer-from Code" := xRec."Transfer-from Code";
                end;
            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterInitFromTransferFromLocation(var TransferHeader: Record "Transfer Header"; Location: Record Location)
    begin
        //A108F0011.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
