### ISSUE TITLE
request for fieldgroup - table 5051 Contact Alt. Address - DropDown

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/ALAppExtensions#13409]
Please add the DropDown fieldgroup to this table so that we can add fields to it

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
