### ISSUE TITLE
[Event Request] table 23 Vendor - OnAfterOnInsert

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13407]
We would like to add a new event OnAfterOnInsert in the following trigger:

    trigger OnInsert()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeOnInsert(Rec, IsHandled);
        if IsHandled then
            exit;

        if "No." = '' then begin
            PurchSetup.Get();
            PurchSetup.TestField("Vendor Nos.");
            NoSeriesMgt.InitSeries(PurchSetup."Vendor Nos.", xRec."No. Series", 0D, "No.", "No. Series");
        end;

        if "Invoice Disc. Code" = '' then
            "Invoice Disc. Code" := "No.";

        if not (InsertFromContact or (InsertFromTemplate and (Contact <> ''))) then
            UpdateContFromVend.OnInsert(Rec);

        if "Purchaser Code" = '' then
            SetDefaultPurchaser;

        DimMgt.UpdateDefaultDim(
          DATABASE::Vendor, "No.",
          "Global Dimension 1 Code", "Global Dimension 2 Code");

        UpdateReferencedIds;
        SetLastModifiedDateTime;

        OnAfterOnInsert(Rec); //A108F0020.Event
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterOnInsert(var Vendor: Record Vendor)
    begin
        //A108F0020.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
