### ISSUE TITLE
[Event Request] table 5740 "Transfer Header" - OnAfterCalcAreTransferLinesEditable

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13400]
We would like to add a new event OnAfterCalcAreTransferLinesEditable and a new procedure:

    procedure CalcAreTransferLinesEditable() IsEditable: Boolean;
    begin
        //A113F0000.Event.ns
        IsEditable := ("Transfer-from Code" <> '') and ("Transfer-to Code" <> '') and ("In-Transit Code" <> '');

        OnAfterCalcAreTransferLinesEditable(Rec, IsEditable);
        //A113F0000.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcAreTransferLinesEditable(var TransferHeader: Record "Transfer Header"; var IsEditable: Boolean)
    begin
        //A113F0000.Event
    end;

**Comment by Oleg-Romashkov** [comment]
We do not implement additional application code via event requests. Especially parts of you own solution. We need detailed explanation for such requests, better create them on IDEAS portal
