### ISSUE TITLE
[Event Request] table 5802 "Value Entry" - OnAfterFilterSumCostsValueEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13406]
We would like to add a new event OnAfterFilterSumCostsValueEntry in the following procedure:

    procedure SumCostsTillValuationDate(var ValueEntry: Record "Value Entry")
    var
        AccountingPeriod: Record "Accounting Period";
        PrevValueEntrySum: Record "Value Entry";
        Item: Record Item;
        FromDate: Date;
        ToDate: Date;
        CostCalcIsChanged: Boolean;
        QtyFactor: Decimal;
    begin
        Item.Get(ValueEntry."Item No.");
        OnSumCostsTillValuationDateOnAfterGetItem(Item, ValueEntry);
        if Item."Costing Method" = Item."Costing Method"::Average then
            ToDate := GetAvgToDate(ValueEntry."Valuation Date")
        else
            ToDate := ValueEntry."Valuation Date";

        repeat
            if Item."Costing Method" = Item."Costing Method"::Average then
                FromDate := GetAvgFromDate(ToDate, AccountingPeriod, CostCalcIsChanged)
            else
                FromDate := 0D;

            QtyFactor := 1;
            Reset;
            SetCurrentKey("Item No.", "Valuation Date", "Location Code", "Variant Code");
            SetRange("Item No.", ValueEntry."Item No.");
            SetRange("Valuation Date", FromDate, ToDate);
            OnAfterFilterSumCostsValueEntry(Rec, ValueEntry, Item); //A200F0002.Event
            CheckApplyLocationVariantFilters(AccountingPeriod, ValueEntry, Item, CostCalcIsChanged, QtyFactor, FromDate, ToDate);

            CalcSums(
              "Item Ledger Entry Quantity", "Invoiced Quantity",
              "Cost Amount (Actual)", "Cost Amount (Actual) (ACY)",
              "Cost Amount (Expected)", "Cost Amount (Expected) (ACY)");
            OnSumCostsTillValuationDateOnAfterCalcSums(Rec);

            "Item Ledger Entry Quantity" :=
              Round("Item Ledger Entry Quantity" * QtyFactor, UOMMgt.QtyRndPrecision) + PrevValueEntrySum."Item Ledger Entry Quantity";
            "Invoiced Quantity" :=
              Round("Invoiced Quantity" * QtyFactor, UOMMgt.QtyRndPrecision) + PrevValueEntrySum."Invoiced Quantity";
            "Cost Amount (Actual)" :=
              "Cost Amount (Actual)" * QtyFactor + PrevValueEntrySum."Cost Amount (Actual)";
            "Cost Amount (Expected)" :=
              "Cost Amount (Expected)" * QtyFactor + PrevValueEntrySum."Cost Amount (Expected)";
            "Cost Amount (Expected) (ACY)" :=
              "Cost Amount (Expected) (ACY)" * QtyFactor + PrevValueEntrySum."Cost Amount (Expected) (ACY)";
            "Cost Amount (Actual) (ACY)" :=
              "Cost Amount (Actual) (ACY)" * QtyFactor + PrevValueEntrySum."Cost Amount (Actual) (ACY)";
            PrevValueEntrySum := Rec;

            if FromDate <> 0D then
                ToDate := CalcDate('<-1D>', FromDate);
        until FromDate = 0D;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterFilterSumCostsValueEntry(var ValueEntryToFilter: Record "Value Entry"; ValueEntry: Record "Value Entry"; Item: Record Item);
    begin
        //A200F0002.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
