### ISSUE TITLE
[Event Request] table 5741 "Transfer Line" - OnBeforeUpdateWithWarehouseShipReceive

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13404]
We would like to add a new event OnBeforeUpdateWithWarehouseShipReceive in the following procedure:

    procedure UpdateWithWarehouseShipReceive()
    var
        IsHandled: Boolean;
    begin
        //A200F0001.Event.ns
        GetTransHeader;
        OnBeforeUpdateWithWarehouseShipReceive(TransHeader, Rec, IsHandled);
        if IsHandled then
            exit;
        //A200F0001.Event.ne
        if Location.RequireShipment("Transfer-from Code") then
            Validate("Qty. to Ship", 0)
        else
            Validate("Qty. to Ship", "Outstanding Quantity");

        if Location.RequireReceive("Transfer-to Code") then
            Validate("Qty. to Receive", 0)
        else begin
            if "In-Transit Code" <> '' then
                Validate("Qty. to Receive", "Qty. in Transit");
            if ("In-Transit Code" = '') and ("Quantity Shipped" = "Quantity Received") then
                Validate("Qty. to Receive", "Qty. to Ship");
        end;

        //OnAfterUpdateWithWarehouseShipReceive(Rec, CurrFieldNo); A200F0001.Event.o
        OnAfterUpdateWithWarehouseShipReceive(TransHeader, Rec, CurrFieldNo); //A200F0001.Event.n
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateWithWarehouseShipReceive(TransferHeader: Record "Transfer Header"; var TransferLine: Record "Transfer Line"; var IsHandled: Boolean)
    begin
        //A200F0001.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
