### ISSUE TITLE
[Event Request] table 5767 "Warehouse Activity Line" - OnBeforeModifyBreakBulkWhseActivLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13410]
We would like to add a new event OnBeforeModifyBreakBulkWhseActivLine in the following procedure:

    procedure UpdateBreakbulkQtytoHandle()
    var
        WhseActivLine: Record "Warehouse Activity Line";
    begin
        WhseActivLine.SetCurrentKey(
          "Activity Type", "No.", "Whse. Document Type",
          "Whse. Document No.", "Whse. Document Line No.");
        WhseActivLine.SetRange("Activity Type", "Activity Type");
        WhseActivLine.SetRange("No.", "No.");
        WhseActivLine.SetRange("Whse. Document Type", "Whse. Document Type");
        WhseActivLine.SetRange("Whse. Document No.", "Whse. Document No.");
        WhseActivLine.SetRange("Whse. Document Line No.", "Whse. Document Line No.");
        WhseActivLine.SetTrackingFilterFromWhseActivityLine(Rec);
        if "Original Breakbulk" then
            WhseActivLine.SetRange("Original Breakbulk", true)
        else
            WhseActivLine.SetRange("Breakbulk No.", "Breakbulk No.");
        WhseActivLine.SetRange("Action Type", WhseActivLine."Action Type"::Place);
        if WhseActivLine.FindFirst then begin
            WhseActivLine."Qty. to Handle (Base)" := "Qty. to Handle (Base)";
            WhseActivLine."Qty. to Handle" := WhseActivLine.CalcQty("Qty. to Handle (Base)");
            WMSMgt.CalcCubageAndWeight(
              WhseActivLine."Item No.", WhseActivLine."Unit of Measure Code",
              WhseActivLine."Qty. to Handle", WhseActivLine.Cubage, WhseActivLine.Weight);
            OnBeforeModifyBreakBulkWhseActivLine(WhseActivLine); //A109F0000.Event
            WhseActivLine.Modify();

            WhseActivLine.SetRange("Action Type", WhseActivLine."Action Type"::Take);
            if "Original Breakbulk" then begin
                WhseActivLine.SetRange("Original Breakbulk");
                WhseActivLine.SetRange("Breakbulk No.", WhseActivLine."Breakbulk No.")
            end else begin
                WhseActivLine.SetRange("Breakbulk No.");
                WhseActivLine.SetRange("Original Breakbulk", true);
            end;
            if WhseActivLine.FindFirst then begin
                WhseActivLine."Qty. to Handle (Base)" := "Qty. to Handle (Base)";
                WhseActivLine."Qty. to Handle" := WhseActivLine.CalcQty("Qty. to Handle (Base)");
                WMSMgt.CalcCubageAndWeight(
                  WhseActivLine."Item No.", WhseActivLine."Unit of Measure Code",
                  WhseActivLine."Qty. to Handle", WhseActivLine.Cubage, WhseActivLine.Weight);
                OnBeforeModifyBreakBulkWhseActivLine(WhseActivLine); //A109F0000.Event
                WhseActivLine.Modify();
            end;
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyBreakBulkWhseActivLine(var WarehouseActivityLine: Record "Warehouse Activity Line")
    begin
        //A109F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
