### ISSUE TITLE
[Event Request] table 7316 "Warehouse Receipt Header" - OnAfterOnInsert

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13419]
We would like to add a new event OnAfterOnInsert in the following trigger:

    trigger OnInsert()
    begin
        WhseSetup.Get();
        if "No." = '' then begin
            WhseSetup.TestField("Whse. Receipt Nos.");
            NoSeriesMgt.InitSeries(WhseSetup."Whse. Receipt Nos.", xRec."No. Series", "Posting Date", "No.", "No. Series");
        end;

        NoSeriesMgt.SetDefaultSeries("Receiving No. Series", WhseSetup."Posted Whse. Receipt Nos.");

        GetLocation("Location Code");
        Validate("Bin Code", Location."Receipt Bin Code");
        Validate("Cross-Dock Bin Code", Location."Cross-Dock Bin Code");
        "Posting Date" := WorkDate;
        OnAfterOnInsert(Rec, xRec); //A113F0000.Event
    end;

 
Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterOnInsert(var WarehouseReceiptHeader: Record "Warehouse Receipt Header"; var xWarehouseReceiptHeader: Record "Warehouse Receipt Header")
    begin
        //A108F0020.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
