### ISSUE TITLE
[Event Request] table 7310 "Warehouse Journal Batch" - OnAfterSetupNewBatch

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13413]
We would like to add a new event OnAfterSetupNewBatch in the following procedure:

    procedure SetupNewBatch()
    begin
        WhseJnlTemplate.Get("Journal Template Name");
        "No. Series" := WhseJnlTemplate."No. Series";
        "Registering No. Series" := WhseJnlTemplate."Registering No. Series";
        "Reason Code" := WhseJnlTemplate."Reason Code";
        OnAfterSetupNewBatch(Rec, WhseJnlTemplate); //A108F0009.Event
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetupNewBatch(var WarehouseJournalBatch: Record "Warehouse Journal Batch"; WarehouseJournalTemplate: Record "Warehouse Journal Template")
    begin
        //A108F0009.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
