### ISSUE TITLE
Bug (or event request) - Unable to remove page action

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#1341]
Our add-on has enhanced/extended functionality for dimensions. For this to work, we need additional code to fire after ShowDimensions is called in all tables.  May approach here was to set the base product Dimensions page action to Visible = No, and then add our own DImensions page action that calls a new version of ShowDimensions with the additional logic.  I have tried this on the General Journal page but it doesn't work...the base product Dimensions link still shows.  Should we be able to hide that action?

An alternative (and cleaner) solution here would be if an integration event code be added at the end of every ShowDimensions function in the application for OnAfterShowDimensions.  At that point we need to update some other fields on the record based on the capabilities we add here.

**Comment by RHansenEpimatic** [comment]
Interesting...if i set Visible = FALSE on the page action, it doesn't work.  If i create a global boolean variable and use that for the property...it seems to work fine.

**Comment by JesperSchulz** [comment]
This sounds like a bug in our client. Would you mind logging it as such?
We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.
