### ISSUE TITLE
[Event Request] table 5767 "Warehouse Activity Line" - OnBeforeModifyChangeUoMBulkWhseActivLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13411]
We would like to add a new event OnBeforeModifyChangeUoMBulkWhseActivLine in the following procedure:

    procedure ChangeUOMCode(var WhseActivLine: Record "Warehouse Activity Line"; var WhseActivLine2: Record "Warehouse Activity Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeChangeUOMCode(WhseActivLine, WhseActivLine2, IsHandled);
        if IsHandled then
            exit;

        if "Breakbulk No." = 0 then
            if (Quantity <> "Qty. to Handle") or ("Qty. Handled" <> 0) then
                CreateNewUOMLine("Action Type", WhseActivLine, WhseActivLine2)
            else begin
                Rec := WhseActivLine2;
                GetLocation("Location Code");
                if Location."Directed Put-away and Pick" then
                    WMSMgt.CalcCubageAndWeight(
                      "Item No.", "Unit of Measure Code", "Qty. to Handle", Cubage, Weight);
                OnBeforeModifyChangeUoMBulkWhseActivLine(Rec); //A109F0000.Event
                Modify;
            end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyChangeUoMBulkWhseActivLine(var WarehouseActivityLine: Record "Warehouse Activity Line")
    begin
        //A109F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
