### ISSUE TITLE
[Event Request] table 5767 "Warehouse Activity Line" - OnAfterInitSplitWhseActivityLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13412]
We would like to add a new event OnAfterInitSplitWhseActivityLine in the following procedure:

    procedure SplitLine(var WhseActivLine: Record "Warehouse Activity Line")
    var
        NewWhseActivLine: Record "Warehouse Activity Line";
        LineSpacing: Integer;
        NewLineNo: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSplitLines(WhseActivLine, IsHandled);
        if IsHandled then
            exit;

        CheckSplitLine(WhseActivLine);

        NewWhseActivLine := WhseActivLine;
        NewWhseActivLine.SetRange("No.", WhseActivLine."No.");
        if NewWhseActivLine.Find('>') then
            LineSpacing :=
              (NewWhseActivLine."Line No." - WhseActivLine."Line No.") div 2
        else
            LineSpacing := 10000;

        OnSplitLineOnBeforeRenumberAllLines(WhseActivLine, LineSpacing);
        if LineSpacing = 0 then
            ReNumberWhseActivityLines(NewWhseActivLine, WhseActivLine, NewLineNo, LineSpacing);

        NewWhseActivLine.Reset();
        NewWhseActivLine.Init();
        NewWhseActivLine := WhseActivLine;
        NewWhseActivLine."Line No." := NewWhseActivLine."Line No." + LineSpacing;
        NewWhseActivLine.Quantity :=
          WhseActivLine."Qty. Outstanding" - WhseActivLine."Qty. to Handle";
        NewWhseActivLine."Qty. (Base)" :=
          WhseActivLine."Qty. Outstanding (Base)" - WhseActivLine."Qty. to Handle (Base)";
        NewWhseActivLine."Qty. Outstanding" := NewWhseActivLine.Quantity;
        NewWhseActivLine."Qty. Outstanding (Base)" := NewWhseActivLine."Qty. (Base)";
        NewWhseActivLine."Qty. to Handle" := NewWhseActivLine.Quantity;
        NewWhseActivLine."Qty. to Handle (Base)" := NewWhseActivLine."Qty. (Base)";
        NewWhseActivLine."Qty. Handled" := 0;
        NewWhseActivLine."Qty. Handled (Base)" := 0;
        OnAfterInitSplitWhseActivityLine(NewWhseActivLine); //A109F0001.Event
        GetLocation("Location Code");
        if Location."Directed Put-away and Pick" then begin
            WMSMgt.CalcCubageAndWeight(
              NewWhseActivLine."Item No.", NewWhseActivLine."Unit of Measure Code",
              NewWhseActivLine."Qty. to Handle", NewWhseActivLine.Cubage, NewWhseActivLine.Weight);
            if not
               (((NewWhseActivLine."Activity Type" = NewWhseActivLine."Activity Type"::"Put-away") and
                 (NewWhseActivLine."Action Type" = NewWhseActivLine."Action Type"::Take)) or
                ((NewWhseActivLine."Activity Type" = NewWhseActivLine."Activity Type"::Pick) and
                 (NewWhseActivLine."Action Type" = NewWhseActivLine."Action Type"::Place)) or
                ("Breakbulk No." <> 0))
            then begin
                NewWhseActivLine."Zone Code" := '';
                NewWhseActivLine."Bin Code" := '';
            end;
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterInitSplitWhseActivityLine(var WarehouseActivityLine: Record "Warehouse Activity Line")
    begin
        //A109F0001.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
