### ISSUE TITLE
[Event Request] table 7316 "Warehouse Receipt Header" - OnAfterCalcAreWarehouseReceiptLinesEditable

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13418]
We would like to add a new event OnAfterCalcAreWarehouseReceiptLinesEditable and a new procedure:

    procedure CalcAreWarehouseReceiptLinesEditable() IsEditable: Boolean;
    begin
        IsEditable := true;
        //A113F0000.Event.ns

        OnAfterCalcAreWarehouseReceiptLinesEditable(Rec, IsEditable);
        //A113F0000.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcAreWarehouseReceiptLinesEditable(var WarehouseReceiptHeader: Record "Warehouse Receipt Header"; var IsEditable: Boolean)
    begin
        //A113F0000.Event
    end;

**Comment by Oleg-Romashkov** [comment]
Function CalcAreWarehouseReceiptLinesEditable does not exist.

**Comment by AlexanderYakunin** [comment]
It is not clear what is the purpose of new procedure and new variable IsEditable which we don't have. If you have good justification, please create new request with additional information.
