### ISSUE TITLE
[Event Request] "OnAfterLookUp" for Requisition/Planning Worksheets Journal Names and the "Vendor No." on these Worksheets.

### ISSUE THREAD

**Issue by FavMY** [microsoft/ALAppExtensions#13417]
Could we get events called OnAfterLookUp of the journal names on both worksheets (they called "CurrentJnlBatchName" and "CurrentWkshBatchName")? We need that because the "OnAfterValidate" or the "OnAfterAfterLookup" Events are not triggered when using the Lookup of this Pagefields.

Requisition WorkSheet(CurrentJnlBatchName):

    trigger OnLookup(var Text: Text): Boolean
    begin
        CurrPage.SaveRecord;
        ReqJnlManagement.LookupName(CurrentJnlBatchName, Rec);
        CurrPage.Update(false);
        OnAfterLookUp(CurrentJnlBatchName, Rec);
    end;
  
    trigger OnValidate()
    begin
        ReqJnlManagement.CheckName(CurrentJnlBatchName, Rec);
        CurrentJnlBatchNameOnAfterVali;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterLookUp(var CurrentJnlBatchName: Code[10];var RequisitionLine: Record "Requisition Line")
    begin
    end;
    
Planning Worksheet (CurrentWkshBatchName):
    
    trigger OnLookup(var Text: Text): Boolean
    begin
        CurrPage.SaveRecord;
        ReqJnlManagement.LookupName(CurrentWkshBatchName, Rec);
        CurrPage.Update(false);
        OnAfterLookUp(CurrentWkshBatchName, Rec);
    end;
    
    trigger OnValidate()
    begin
        ReqJnlManagement.CheckName(CurrentWkshBatchName, Rec);
        CurrentWkshBatchNameOnAfterVal;
    end;
    
    [IntegrationEvent(false, false)]
    local procedure OnAfterLookUp(var CurrentWkshBatchName: Code[10];var RequisitionLine: Record "Requisition Line")
    begin
    end;

Similar to these we also need an OnAfterLookUp-Event for the "Vendor No." on the Pagefield. It only has an LookUp on table level.
It could look like this:

Requisition WorkSheet:

      field("Vendor No."; "Vendor No.")
      {
          ApplicationArea = Planning;
          ToolTip = 'Specifies the number of the vendor who will ship the items in the purchase order.';
          
          trigger OnLookup(var Text: Text): Boolean
          begin
              OnAfterLookUp(Rec);
          end;

          trigger OnValidate()
          begin
              ReqJnlManagement.GetDescriptionAndRcptName(Rec, Description2, BuyFromVendorName);
              ShowShortcutDimCode(ShortcutDimCode);
          end;
      }

    [IntegrationEvent(false, false)]
    local procedure OnAfterLookUp(var RequisitionLine: Record "Requisition Line")
    begin
    end;

Planning Worksheet:

      field("Vendor No."; "Vendor No.")
      {
          ApplicationArea = Planning;
          ToolTip = 'Specifies the number of the vendor who will ship the items in the purchase order.';
          Visible = false;

          trigger OnLookup(var Text: Text): Boolean
          begin
              OnAfterLookUp(Rec);
          end;
      }

    [IntegrationEvent(false, false)]
    local procedure OnAfterLookUp(var RequisitionLine: Record "Requisition Line")
    begin
    end;

**Comment by Oleg-Romashkov** [comment]
The batch lookup events will be done.

The approach you suggested for vendor lookup triggers does not work. Please use existing events on table level.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
