### ISSUE TITLE
[Event Request] table 7311 "Warehouse Journal Line" - OnBeforeLookupFromBinCode

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13414]
We would like to add a new event OnBeforeLookupFromBinCode in the following procedure:

    local procedure LookupFromBinCode()
    var
        WhseItemTrackingSetup: Record "Item Tracking Setup";
        BinCode: Code[20];
        IsHandled: Boolean;
    begin
        //A201F0000.Event.ns
        IsHandled := false;
        OnBeforeLookupFromBinCode(Rec, IsHandled);
        if IsHandled then
            exit;
        //A201F0000.Event.ne

        if ("Line No." <> 0) and IsReclass("Journal Template Name") then begin
            LookupItemTracking(WhseItemTrackingSetup);
            BinCode := WMSMgt.BinContentLookUp("Location Code", "Item No.", "Variant Code", "Zone Code", WhseItemTrackingSetup, "Bin Code");
        end else
            BinCode := WMSMgt.BinLookUp("Location Code", "Item No.", "Variant Code", "Zone Code");
        if BinCode <> '' then
            Validate("From Bin Code", BinCode);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeLookupFromBinCode(var WarehouseJournalLine: Record "Warehouse Journal Line"; var IsHandled: Boolean)
    begin
        //A201F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
