### ISSUE TITLE
[Extensibility Bug] 'Option Lookup Buffer' to manage other types

### ISSUE THREAD

**Issue by SBiernat** [microsoft/ALAppExtensions#13415]
Hi,
with case #8656 and BC18 the publisher 
<code>
OnFillBufferLookupTypeCase(LookupType, IsHandled);
</code>
was created to manage other types.

But how should this work without the record variable as parameter?

If you agree, that it doesn't work as expected, then i suggest the following solution:

The parameters of the publisher "OnFillBufferLookupTypeCase" are changed and after that the function FillBufferInternal is called.

```
procedure FillLookupBuffer(LookupType: Enum "Option Lookup Type")
var
  SalesLine: Record "Sales Line";
  PurchaseLine: Record "Purchase Line";
  Permission: Record Permission;
  IsHandled: Boolean;
begin
  case LookupType of
    "Lookup Type"::Sales:
	FillBufferInternal(DATABASE::"Sales Line", SalesLine.FieldNo(Type), SalesLine.FieldNo("No."), LookupType);
    "Lookup Type"::Purchases:
	FillBufferInternal(DATABASE::"Purchase Line", PurchaseLine.FieldNo(Type), PurchaseLine.FieldNo("No."), LookupType);
    "Lookup Type"::Permissions:
	FillBufferInternal(DATABASE::Permission, Permission.FieldNo("Read Permission"), 0, LookupType);
    else begin
	IsHandled := false;
	// >> Change
        // OnFillBufferLookupTypeCase(LookupType, IsHandled);
        OnFillBufferLookupTypeCase(LookupType, IsHandled, TableNo, FieldNo, RelationFieldNo);
        // << Change
        if not IsHandled then
	  Error(UnsupportedTypeErr);
	// >> Change
        FillBufferInternal(TableNo, FieldNo, RelationFieldNo, LookupType);
        // << Change
	end;
end;

[IntegrationEvent(true, false)]
// >> Change
// local procedure OnFillBufferLookupTypeCase(LookupType: Enum "Option Lookup Type"; var IsHandled: Boolean)
local procedure OnFillBufferLookupTypeCase(LookupType: Enum "Option Lookup Type"; var IsHandled: Boolean; var TableNo: Integer; var FieldNo: Integer; var RelationFieldNo: Integer;)
// << Change
begin
end;
```

So if someone wants to extend the LookUpType, he has to use the two publishers OnFillBufferLookupTypeCase and OnBeforeIncludeOption

Thanks in advice

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
