### ISSUE TITLE
[Event Request] table 6550 "Whse. Item Tracking Line" - OnAfterSetTrackingFilterFromItemLedgerEntry

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13424]
We would like to add a new event OnAfterSetTrackingFilterFromItemLedgerEntry and a new procedure:

    procedure SetTrackingFilterFromItemLedgerEntry(ItemLedgerEntry: Record "Item Ledger Entry")
    begin
        //A200F0000.Event.ns
        SetRange("Serial No.", ItemLedgerEntry."Serial No.");
        SetRange("Lot No.", ItemLedgerEntry."Lot No.");
        //A200F0000.Event.ne

        OnAfterSetTrackingFilterFromItemLedgerEntry(Rec, ItemLedgerEntry); //A200F0000.Event
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetTrackingFilterFromItemLedgerEntry(var WhseItemTrackingLine: Record "Whse. Item Tracking Line"; ItemLedgerEntry: Record "Item Ledger Entry")
    begin
        //A200F0000.Event
    end;

**Comment by Oleg-Romashkov** [comment]
Function SetTrackingFilterFromItemLedgerEntry does not exist

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
