### ISSUE TITLE
[Event Request] table 7326 "Whse. Worksheet Line" - OnBeforeOpenItemTrackingLines

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13425]
We would like to add a new event OnBeforeOpenItemTrackingLines in the following procedure:

    procedure OpenItemTrackingLines()
    var
        WhseItemTrackingForm: Page "Whse. Item Tracking Lines";
    begin
        OnBeforeOpenItemTrackingLines(Rec); //A200F0000.Event
        TestField("Item No.");
        TestField("Qty. (Base)");
        case "Whse. Document Type" of
            "Whse. Document Type"::Receipt:
                WhseItemTrackingForm.SetSource(Rec, DATABASE::"Posted Whse. Receipt Line");
            "Whse. Document Type"::Shipment:
                WhseItemTrackingForm.SetSource(Rec, DATABASE::"Warehouse Shipment Line");
            "Whse. Document Type"::"Internal Put-away":
                WhseItemTrackingForm.SetSource(Rec, DATABASE::"Whse. Internal Put-away Line");
            "Whse. Document Type"::"Internal Pick":
                WhseItemTrackingForm.SetSource(Rec, DATABASE::"Whse. Internal Pick Line");
            "Whse. Document Type"::Production:
                WhseItemTrackingForm.SetSource(Rec, DATABASE::"Prod. Order Component");
            "Whse. Document Type"::Assembly:
                WhseItemTrackingForm.SetSource(Rec, DATABASE::"Assembly Line");
            else
                WhseItemTrackingForm.SetSource(Rec, DATABASE::"Whse. Worksheet Line");
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeOpenItemTrackingLines(var WhseWorksheetLine: Record "Whse. Worksheet Line")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
