### ISSUE TITLE
[Event Request] table 7326 "Whse. Worksheet Line" - OnBeforeOpenItemTrackingLines 

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13426]
We would like to add a new event OnAssignedQtyOnReservedLinesSetWhseWkshLineFilters in the following procedure: 

    procedure AssignedQtyOnReservedLines(): Decimal
    var
        WhseWkshLine: Record "Whse. Worksheet Line";
        TempWhseActivLine: Record "Warehouse Activity Line" temporary;
        LineReservedQtyBase: Decimal;
        TotalReservedAndAssignedBase: Decimal;
        ReservedAndAssignedBase: Decimal;
    begin
        WhseWkshLine.SetCurrentKey(
          "Item No.", "Location Code", "Worksheet Template Name", "Variant Code");
        WhseWkshLine.SetRange("Item No.", "Item No.");
        WhseWkshLine.SetRange("Location Code", "Location Code");
        WhseWkshLine.SetRange("Worksheet Template Name", "Worksheet Template Name");
        WhseWkshLine.SetRange("Variant Code", "Variant Code");
        OnAssignedQtyOnReservedLinesSetWhseWkshLineFilters(WhseWkshLine, Rec); //A200F0000.Event
        if WhseWkshLine.Find('-') then
            repeat
                if RecordId <> WhseWkshLine.RecordId then begin
                    LineReservedQtyBase :=
                      Abs(
                        WhseAvailMgt.CalcLineReservedQtyOnInvt(
                          WhseWkshLine."Source Type", WhseWkshLine."Source Subtype",
                          WhseWkshLine."Source No.", WhseWkshLine."Source Line No.",
                          WhseWkshLine."Source Subline No.",
                          true, TempWhseActivLine));
                    if LineReservedQtyBase > 0 then begin
                        if LineReservedQtyBase <= WhseWkshLine."Qty. to Handle (Base)" then
                            ReservedAndAssignedBase := LineReservedQtyBase
                        else
                            ReservedAndAssignedBase := WhseWkshLine."Qty. to Handle (Base)";
                        TotalReservedAndAssignedBase := TotalReservedAndAssignedBase + ReservedAndAssignedBase;
                    end;
                end;
            until WhseWkshLine.Next() = 0;
        exit(TotalReservedAndAssignedBase);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAssignedQtyOnReservedLinesSetWhseWkshLineFilters(var FilteredWhseWorksheetLine: Record "Whse. Worksheet Line"; var WhseWorksheetLine: Record "Whse. Worksheet Line")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
