### ISSUE TITLE
[Event Request] page 9657 "Customer Report Selections" - OnElseSetUsageFilter

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13429]
We would like to add a new event OnElseSetUsageFilter in the following trigger:

                    trigger OnValidate()
                    begin
                        case Usage2 of
                            Usage2::Quote:
                                Usage := Usage::"S.Quote";
                            Usage2::"Confirmation Order":
                                Usage := Usage::"S.Order";
                            Usage2::Invoice:
                                Usage := Usage::"S.Invoice";
                            Usage2::"Credit Memo":
                                Usage := Usage::"S.Cr.Memo";
                            Usage2::"Customer Statement":
                                Usage := Usage::"C.Statement";
                            Usage2::"Job Quote":
                                Usage := Usage::JQ;
                            Usage2::Reminder:
                                Usage := Usage::Reminder;
                            Usage2::Shipment:
                                Usage := Usage::"S.Shipment";
                            else
                                OnElseSetUsageFilter(Rec, Usage2); //A108F0075.Event
                        end;
                    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnElseSetUsageFilter(var CustomReportSelection: Record "Custom Report Selection"; ReportUsage: Option)
    begin
        //A108F0075.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
