### ISSUE TITLE
[Event Request] table 7320 "Warehouse Shipment Header" - OnAfterOnInsert

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13421]
We would like to add a new event OnAfterOnInsert in the following trigger:

    trigger OnInsert()
    begin
        WhseSetup.Get();
        if "No." = '' then begin
            WhseSetup.TestField("Whse. Ship Nos.");
            NoSeriesMgt.InitSeries(WhseSetup."Whse. Ship Nos.", xRec."No. Series", "Posting Date", "No.", "No. Series");
        end;

        NoSeriesMgt.SetDefaultSeries("Shipping No. Series", WhseSetup."Posted Whse. Shipment Nos.");

        GetLocation("Location Code");
        Validate("Bin Code", Location."Shipment Bin Code");
        "Posting Date" := WorkDate;
        "Shipment Date" := WorkDate;

        OnAfterOnInsert(Rec, xRec); //A113F0000.Event
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterOnInsert(var WarehouseShipmentHeader: Record "Warehouse Shipment Header"; var xWarehouseShipmentHeader: Record "Warehouse Shipment Header")
    begin
        //A108F0020.Event
    end;

**Comment by pri-kise** [comment]
@Duizy05 may I ask why you aren't using the OnInsertTrigger of a TableExtension, that would be executed exactly on this position?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
