### ISSUE TITLE
[Event Request] table 7332 "Whse. Internal Put-away Line" - OnCheckBinContentQtySetWarehouseInternalPutAwayLineFilters

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13422]
We would like to add a new event OnCheckBinContentQtySetWarehouseInternalPutAwayLineFilters in the following procedure:

    procedure CheckBinContentQty()
    var
        BinContent: Record "Bin Content";
        WhseInternalPutAwayLine: Record "Whse. Internal Put-away Line";
        AvailQtyBase: Decimal;
    begin
        GetLocation("Location Code");

        if Location."Bin Mandatory" and
           ("Location Code" <> '') and ("From Bin Code" <> '') and
           ("Item No." <> '') and ("Unit of Measure Code" <> '')
        then begin
            if Location."Directed Put-away and Pick" then
                CheckBlocking(BinContent);
            AvailQtyBase := BinContent.CalcQtyAvailToTake(0);
            WhseInternalPutAwayLine.SetCurrentKey(
              "Item No.", "From Bin Code", "Location Code", "Unit of Measure Code", "Variant Code");
            WhseInternalPutAwayLine.SetRange("Item No.", "Item No.");
            WhseInternalPutAwayLine.SetRange("From Bin Code", "From Bin Code");
            WhseInternalPutAwayLine.SetRange("Location Code", "Location Code");
            WhseInternalPutAwayLine.SetRange("Unit of Measure Code", "Unit of Measure Code");
            WhseInternalPutAwayLine.SetRange("Variant Code", "Variant Code");
            WhseInternalPutAwayLine.SetFilter("Line No.", '<>%1', "Line No.");
            OnCheckBinContentQtySetWarehouseInternalPutAwayLineFilters(WhseInternalPutAwayLine, Rec); //A200F0000.Event
            WhseInternalPutAwayLine.CalcSums("Qty. (Base)");
            if AvailQtyBase - WhseInternalPutAwayLine."Qty. (Base)" < "Qty. (Base)" then
                FieldError(
                  "Qty. (Base)",
                  StrSubstNo(
                    Text002, AvailQtyBase - WhseInternalPutAwayLine."Qty. (Base)"));
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnCheckBinContentQtySetWarehouseInternalPutAwayLineFilters(var FilteredWhseInternalPutawayLine: Record "Whse. Internal Put-away Line"; var WhseInternalPutawayLine: Record "Whse. Internal Put-away Line")
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
