### ISSUE TITLE
[Event Request] table 7320 "Warehouse Shipment Header" - OnAfterCalcAreWarehouseShipmentLinesEditable

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13420]
We would like to add a new event OnAfterCalcAreWarehouseShipmentLinesEditable and a new procedure:

    procedure CalcAreWarehouseShipmentLinesEditable() IsEditable: Boolean;
    begin
        IsEditable := true;
        //A113F0000.Event.ns

        OnAfterCalcAreWarehouseShipmentLinesEditable(Rec, IsEditable);
        //A113F0000.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcAreWarehouseShipmentLinesEditable(var WarehouseShipmentHeader: Record "Warehouse Shipment Header"; var IsEditable: Boolean)
    begin
        //A113F0000.Event
    end;

**Comment by Oleg-Romashkov** [comment]
Function CalcAreWarehouseShipmentLinesEditable does not exist

**Comment by AlexanderYakunin** [comment]
It is not clear what is the purpose of new procedure and new variable IsEditable which we don't have. If you have good justification, please create new request with additional information.
