### ISSUE TITLE
page 8626 "Config. Package Records" - OnBeforeValidatePackageData 

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13428]
We would like to add a new event OnBeforeValidatePackageData in the following procedure:

    local procedure ValidatePackageData(ColumnID: Integer)
    var
        ConfigPackageField: Record "Config. Package Field";
        Dimension: Record Dimension;
        DimValue: Record "Dimension Value";
        ConfigValidateMgt: Codeunit "Config. Validate Management";
        ConfigPackageMgt: Codeunit "Config. Package Management";
        RecRef: RecordRef;
        FieldRef: FieldRef;
        ErrorText: Text[250];
        IsHandled: Boolean;
    begin
        MatrixCellData[ColumnID] := DelChr(MatrixCellData[ColumnID], '<>', ' ');
        //A100F0001.Event.ns A200F0003.Event.ns
        IsHandled := false;
        OnBeforeValidatePackageData(Rec, MatrixCellData, PackageColumnField, ColumnID, IsHandled);
        if IsHandled then begin
            CurrPage.update;
            exit;
        end;
        //A100F0001.ne A200F0003.ne
        if MatrixDimension[ColumnID] then begin
            if MatrixCellData[ColumnID] <> '' then
                if not DimValue.Get(MatrixColumnCaptions[ColumnID], MatrixCellData[ColumnID]) then
                    Error(Text001, Dimension.TableCaption, MatrixCellData[ColumnID]);
            ConfigPackageData.Get("Package Code", "Table ID", "No.", PackageColumnField[ColumnID]);
            ConfigPackageData.Validate(Value, MatrixCellData[ColumnID]);
            ConfigPackageData.Modify();
        end else begin
            RecRef.Open("Table ID", true);
            FieldRef := RecRef.Field(PackageColumnField[ColumnID]);
            ConfigPackageField.Get("Package Code", "Table ID", PackageColumnField[ColumnID]);
            ConfigPackageField.TestField(Dimension, false);

            ConfigPackageData.Get("Package Code", "Table ID", "No.", PackageColumnField[ColumnID]);
            ConfigPackageMgt.CleanFieldError(ConfigPackageData);
            ErrorText := ConfigValidateMgt.EvaluateValue(FieldRef, MatrixCellData[ColumnID], false);
            if ErrorText <> '' then
                Error(ErrorText);

            MatrixCellData[ColumnID] := Format(FieldRef.Value);

            ConfigPackageData.Validate(Value, MatrixCellData[ColumnID]);
            if ConfigPackageField."Validate Field" and not ConfigPackageMgt.ValidateSinglePackageDataRelation(ConfigPackageData) then
                Error(Text001, FieldRef.Caption, FieldRef.Value);

            ConfigPackageData.Modify();
        end;
        CurrPage.Update();
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidatePackageData(var ConfigPackageRecord: record "Config. Package Record"; var MatrixCellData: array[1000] of Text[250]; PackageColumnField: array[1000] of Integer; ColumnID: Integer; var IsHandled: Boolean)
    begin
        //A100F0001.Event A200F0003.Event 
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
