### ISSUE TITLE
[Event Request] table 7326 "Whse. Worksheet Line" - OnBeforeCalcAvailQtyToMove

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13427]
We would like to add a new event OnBeforeCalcAvailQtyToMove in the following procedure:

    local procedure CalcAvailQtyToMove(): Decimal
    var
        BinContent: Record "Bin Content";
        WhseWkshLine: Record "Whse. Worksheet Line";
        QtyAvailToMoveBase: Decimal;
        IsCalculated: Boolean;
    begin
        if ("Location Code" <> '') and ("From Bin Code" <> '') and
           ("Item No." <> '') and ("From Unit of Measure Code" <> '')
        then begin
            GetLocation("Location Code");
            if BinContent.Get(
                 "Location Code", "From Bin Code", "Item No.", "Variant Code", "From Unit of Measure Code")
            then begin
                //A200F0000.Event.ns
                OnBeforeCalcAvailQtyToMove(BinContent, Rec, QtyAvailToMoveBase, IsCalculated);
                if not IsCalculated then begin
                    //A200F0000.Event.ne
                    QtyAvailToMoveBase := BinContent.CalcQtyAvailToTake(0);
                    WhseWkshLine.SetCurrentKey(
                      "Item No.", "From Bin Code", "Location Code", "Variant Code", "From Unit of Measure Code");
                    WhseWkshLine.SetRange("Item No.", "Item No.");
                    WhseWkshLine.SetRange("From Bin Code", "From Bin Code");
                    WhseWkshLine.SetRange("Location Code", "Location Code");
                    WhseWkshLine.SetRange("Variant Code", "Variant Code");
                    WhseWkshLine.SetRange("From Unit of Measure Code", "From Unit of Measure Code");
                    OnCalcAvailQtyToMoveOnAfterSetFilters(WhseWkshLine, Rec);
                    WhseWkshLine.CalcSums("Qty. to Handle (Base)");
                    QtyAvailToMoveBase := QtyAvailToMoveBase - WhseWkshLine."Qty. to Handle (Base)";
                end; //A200F0000.Event.n
            end;
        end;
        exit(QtyAvailToMoveBase);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcAvailQtyToMove(var BinContent: Record "Bin Content"; var WhseWorksheetLine: Record "Whse. Worksheet Line"; var QtyAvailToMoveBase: Decimal; IsCalculated: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
