### ISSUE TITLE
[Event Request] page 9209 "Invt. Analys by Dim. Matrix" - OnBeforeDrillDownColumnDimension

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13433]
We would like to add a new event OnBeforeDrillDownColumnDimension in the following procedure:

    local procedure MATRIX_OnDrillDown(MATRIX_ColumnOrdinal: Integer)
    var
        IsHandled: Boolean;
    begin
        //A200F0010.Event.ns
        OnBeforeDrillDownColumnDimension(ItemAnalysisView, LineDimOption, Rec, ColumnDimOption, MatrixRecords[MATRIX_ColumnOrdinal], true, IsHandled);
        if IsHandled then
            exit;
        //A200F0010.Event.ne
        ItemAnalysisMgt.DrillDown(
          CurrentAnalysisArea.AsInteger(), ItemStatisticsBuffer, CurrentItemAnalysisViewCode,
          ItemFilter, LocationFilter, DateFilter,
          Dim1Filter, Dim2Filter, Dim3Filter, BudgetFilter,
          LineDimOption, Rec,
          ColumnDimOption, MatrixRecords[MATRIX_ColumnOrdinal],
          true, ValueType, ShowActualBudget);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDrillDownColumnDimension(var ItemAnalysisView: Record "Item Analysis View"; LineDimOption: Option; LineDimCodeBuf: Record "Dimension Code Buffer"; ColDimOption: Option; ColDimCodeBuf: Record "Dimension Code Buffer"; SetColumnFilter: Boolean; var IsHandled: Boolean)
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
