### ISSUE TITLE
[Event Request] page 7159 "Invt. Analysis by Dimensions" - OnAfterGenerateColumnCaptions

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13436]
We would like to add a new event OnAfterGenerateColumnCaptions in the following procedure:

    procedure MATRIX_GenerateColumnCaptions(MATRIX_SetWanted: Option Initial,Previous,Same,Next,PreviousColumn,NextColumn)
.
.
.

                begin
                    Clear(MATRIX_CaptionSet);
                    RecRef.GetTable(Vendor);
                    RecRef.SetTable(Vendor);
                    MatrixMgt.GenerateMatrixData(RecRef, MATRIX_SetWanted, ArrayLen(MATRIX_CaptionSet), 1,
                      MATRIX_PrimKeyFirstCaption, MATRIX_CaptionSet, MATRIX_CaptionRange, MATRIX_CurrentNoOfColumns);
                    for i := 1 to MATRIX_CurrentNoOfColumns do
                        MATRIX_MatrixRecords[i].Code := MATRIX_CaptionSet[i];
                    if ShowColumnName then
                        MatrixMgt.GenerateMatrixData(RecRef, MATRIX_SetWanted::Same, ArrayLen(MATRIX_CaptionSet), 2,
                          MATRIX_PrimKeyFirstCaption, MATRIX_CaptionSet, MATRIX_CaptionRange, MATRIX_CurrentNoOfColumns);
                end;
            ItemAnalysisView."Dimension 1 Code":
                MatrixMgt.GenerateDimColumnCaption(
                  ItemAnalysisView."Dimension 1 Code",
                  Dim1Filter, MATRIX_SetWanted, MATRIX_PrimKeyFirstCaption, FirstColumn, LastColumn,
                  MATRIX_CaptionSet, MATRIX_MatrixRecords, MATRIX_CurrentNoOfColumns, ShowColumnName, MATRIX_CaptionRange);
            ItemAnalysisView."Dimension 2 Code":
                MatrixMgt.GenerateDimColumnCaption(
                  ItemAnalysisView."Dimension 2 Code",
                  Dim2Filter, MATRIX_SetWanted, MATRIX_PrimKeyFirstCaption, FirstColumn, LastColumn,
                  MATRIX_CaptionSet, MATRIX_MatrixRecords, MATRIX_CurrentNoOfColumns, ShowColumnName, MATRIX_CaptionRange);
            ItemAnalysisView."Dimension 3 Code":
                MatrixMgt.GenerateDimColumnCaption(
                  ItemAnalysisView."Dimension 3 Code",
                  Dim3Filter, MATRIX_SetWanted, MATRIX_PrimKeyFirstCaption, FirstColumn, LastColumn,
                  MATRIX_CaptionSet, MATRIX_MatrixRecords, MATRIX_CurrentNoOfColumns, ShowColumnName, MATRIX_CaptionRange);
        end;
        //A200F0010.Event.ns
        OnAfterGenerateColumnCaptions(
            MatrixMgt, ItemAnalysisView, MATRIX_MatrixRecords, MATRIX_CaptionSet, MATRIX_PrimKeyFirstCaption, MATRIX_CaptionRange, MATRIX_CurrentNoOfColumns,
            ColumnDimCode, MATRIX_SetWanted, FirstColumn, LastColumn, ShowColumnName);
        //A200F0010.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterGenerateColumnCaptions(var MatrixMgt: Codeunit "Matrix Management"; var ItemAnalysisView: Record "Item Analysis View"; var MATRIX_MatrixRecords: array[32] of Record "Dimension Code Buffer"; var MATRIX_CaptionSet: array[32] of Text[1024]; var MATRIX_PrimKeyFirstCaption: Text[1024]; var MATRIX_CaptionRange: Text[1024]; MATRIX_CurrentNoOfColumns: Integer; ColumnDimCode: Text[30]; MATRIX_SetWanted: Option Initial,Previous,Same,Next,PreviousColumn,NextColumn; var FirstColumn: Text; var LastColumn: Text; ShowColumnName: Boolean)
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
