### ISSUE TITLE
[Event Request] page 9209 "Invt. Analys by Dim. Matrix" - OnBeforeAnalysisViewSelection

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13431]
We would like to add a new event OnBeforeAnalysisViewSelection in the following trigger:

    trigger OnOpenPage()
    var
        IsHandled: Boolean;
    begin
        CurrentAnalysisArea := CurrentAnalysisArea::Inventory;

        GLSetup.Get();
        //A200F0010.Event.ns
        OnBeforeAnalysisViewSelection(
            CurrentAnalysisArea, CurrentItemAnalysisViewCode, ItemAnalysisView, ItemStatisticsBuffer, Dim1Filter, Dim2Filter, Dim3Filter, IsHandled);
        if IsHandled then
            exit;
        //A200F0010.Event.ne
        ItemAnalysisMgt.AnalysisViewSelection(
          CurrentAnalysisArea.AsInteger(), CurrentItemAnalysisViewCode, ItemAnalysisView, ItemStatisticsBuffer,
          Dim1Filter, Dim2Filter, Dim3Filter);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAnalysisViewSelection(CurrentAnalysisArea: Option; var CurrentItemAnalysisViewCode: Code[10]; var ItemAnalysisView: Record "Item Analysis View"; var ItemStatisticsBuffer: Record "Item Statistics Buffer"; var Dim1Filter: Code[250]; var Dim2Filter: Code[250]; var Dim3Filter: Code[250]; var IsHandled: Boolean)
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
