### ISSUE TITLE
[Event Request] page 9657 "Customer Report Selections" - OnElseMapTableUsageValueToPageValue

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13430]
We would like to add a new event OnElseMapTableUsageValueToPageValue in the following procedure:

    local procedure MapTableUsageValueToPageValue()
    var
        CustomReportSelection: Record "Custom Report Selection";
    begin
        case Usage of
            CustomReportSelection.Usage::"S.Quote":
                Usage2 := Usage2::Quote;
            CustomReportSelection.Usage::"S.Order":
                Usage2 := Usage2::"Confirmation Order";
            CustomReportSelection.Usage::"S.Invoice":
                Usage2 := Usage2::Invoice;
            CustomReportSelection.Usage::"S.Cr.Memo":
                Usage2 := Usage2::"Credit Memo";
            CustomReportSelection.Usage::"C.Statement":
                Usage2 := Usage2::"Customer Statement";
            CustomReportSelection.Usage::JQ:
                Usage2 := Usage2::"Job Quote";
            CustomReportSelection.Usage::Reminder:
                Usage2 := Usage2::Reminder;
            CustomReportSelection.Usage::"S.Shipment":
                Usage2 := Usage2::Shipment;
            else
                OnElseMapTableUsageValueToPageValue(CustomReportSelection, Usage2);  //A108F0075.Event
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnElseMapTableUsageValueToPageValue(CustomReportSelection: Record "Custom Report Selection"; var ReportUsage: Option)
    begin
        //A108F0075.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
