### ISSUE TITLE
[Event Request] page 7159 "Invt. Analysis by Dimensions" - OnAfterSetItemAnalysisView

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13435]
We would like to add a new event OnAfterSetItemAnalysisView in the following trigger:

                    trigger OnValidate()
                    begin
                        ItemAnalysisMgt.CheckAnalysisView(CurrentAnalysisArea.AsInteger(), CurrentItemAnalysisViewCode, ItemAnalysisView);
                        ItemAnalysisMgt.SetItemAnalysisView(
                          CurrentAnalysisArea.AsInteger(), CurrentItemAnalysisViewCode, ItemAnalysisView, ItemStatisticsBuffer,
                          Dim1Filter, Dim2Filter, Dim3Filter);
                        OnAfterSetItemAnalysisView(ItemAnalysisView); //A200F0010.Event
                        ItemAnalysisMgt.SetLineAndColDim(
                          ItemAnalysisView, LineDimCode, LineDimOption, ColumnDimCode, ColumnDimOption);
                        UpdateFilterFields;
                        CurrPage.Update(false);
                    end;

Event Signature:

    [IntegrationEvent(true, false)]
    local procedure OnAfterSetItemAnalysisView(var ItemAnalysisView: Record "Item Analysis View")
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
