### ISSUE TITLE
[Event Request] page 7159 "Invt. Analysis by Dimensions" - OnBeforeItemLookup

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13437]
We would like to add a new event OnBeforeItemLookup in the following trigger:

                    trigger OnLookup(var Text: Text): Boolean
                    var
                        ItemList: Page "Item List";
                    begin
                        ItemList.LookupMode(true);
                        OnBeforeItemLookup(ItemList, ItemAnalysisView); //A200F0010.Event
                        if ItemList.RunModal = ACTION::LookupOK then begin
                            Text := ItemList.GetSelectionFilter;
                            exit(true);
                        end;
                    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeItemLookup(var ItemList: Page "Item List"; ItemAnalysisView: Record "Item Analysis View")
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
