### ISSUE TITLE
[Event Request] page 7159 "Invt. Analysis by Dimensions" - OnBeforeRunMatrixPage

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13438]
We would like to add a new event OnBeforeRunMatrixPage in the following trigger:

                trigger OnAction()
                var
                    MatrixForm: Page "Invt. Analys by Dim. Matrix";
                begin
                    Clear(MatrixForm);
                    MatrixForm.Load(MATRIX_CaptionSet, MATRIX_MatrixRecords, MATRIX_CurrentNoOfColumns,
                      LineDimOption, ColumnDimOption, RoundingFactor, DateFilter,
                      ValueType, ItemAnalysisView, CurrentItemAnalysisViewCode,
                      ItemFilter, LocationFilter, BudgetFilter, Dim1Filter, Dim2Filter, Dim3Filter, ShowOppositeSign);
                    OnBeforeRunMatrixPage(MatrixForm, ItemAnalysisView); //A200F0010.Event
                    MatrixForm.RunModal;
                end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeRunMatrixPage(var InvtAnalysByDimMatrix: Page "Invt. Analys by Dim. Matrix"; var ItemAnalysisView: Record "Item Analysis View")
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
