### ISSUE TITLE
[Event Request] page 9209 "Invt. Analys by Dim. Matrix" - OnBeforeCalcValue

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13432]
We would like to add a new event OnBeforeCalcValue in the following procedure:

    local procedure CalcAmt(ValueType: Integer; SetColFilter: Boolean): Decimal
    var
        Amt: Decimal;
        IsHandled: Boolean;
    begin
        //A200F0010.Event.ns
        OnBeforeCalcValue(ItemAnalysisView, Amt, LineDimOption, Rec, ColumnDimOption, MatrixRecord, SetColFilter, ItemFilter, LocationFilter, DateFilter, ValueType, SetColFilter, ShowOppositeSign, IsHandled);
        if IsHandled then
            exit(Amt);
        //A200F0010.Event.ne
        Amt := ItemAnalysisMgt.CalcAmount(
            ValueType, SetColFilter,
            CurrentAnalysisArea.AsInteger(), ItemStatisticsBuffer, CurrentItemAnalysisViewCode,
            ItemFilter, LocationFilter, DateFilter, BudgetFilter,
            Dim1Filter, Dim2Filter, Dim3Filter,
            LineDimOption, Rec,
            ColumnDimOption, MatrixRecord,
            ShowActualBudget);
        if ShowOppositeSign then
            Amt := -Amt;
        exit(Amt);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcValue(var ItemAnalysisView: Record "Item Analysis View"; var Value: Decimal; LineDimOption: Option; LineDimCodeBuf: Record "Dimension Code Buffer"; ColumnDimOption: Option; ColumnDimCodeBuf: Record "Dimension Code Buffer"; SetColumnFilter: Boolean; ItemFilter: Code[250]; LocationFilter: Code[250]; DateFilter: Text[30]; ValueType: Integer; SetColFilter: Boolean; ShowOppositeSign: Boolean; var IsHandled: Boolean)
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
