### ISSUE TITLE
Hide code in Czech legislation

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#13449]
I would like to ask if it is possible to allow showing code for Czech legislation extensions in NEXT versions. We can't suggest events and other changes for next version before release. 

If we download snadbox for BC18 we can't see code, but if we download onprem container we have there zip files with codes. Problem is that NextMajor and NextMinor version can be download as sandbox only and another problem is that Czech legislation extesions have hide code. It means that "Go to definition" does not work. We have to see the code otherwise it is not possible to develop our products that are dependent on Czech legislation.

**Comment by AlexanderYakunin** [comment]
This is already done for 19.0
