### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnBeforeAssignLotNo

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13444]
We would like to add a new event OnBeforeAssignLotNo in the following procedure:

    local procedure AssignLotNo()
    var
        QtyToCreate: Decimal;
        IsHandled: Boolean;
    begin
        //A200F0000.Event.ns
        OnBeforeAssignLotNo(Rec, TempItemTrackLineInsert, SourceQuantityArray, IsHandled);
        if IsHandled then begin
            CalculateSums();
            exit;
        end;
        //A200F0000.Event.ne            
        if ZeroLineExists then
            Rec.Delete();

        if (SourceQuantityArray[1] * UndefinedQtyArray[1] <= 0) or
           (Abs(SourceQuantityArray[1]) < Abs(UndefinedQtyArray[1]))
        then
            QtyToCreate := 0
        else
            QtyToCreate := UndefinedQtyArray[1];

        GetItem(Rec."Item No.");

        Rec.Validate("Quantity Handled (Base)", 0);
        Rec.Validate("Quantity Invoiced (Base)", 0);
        AssignNewLotNo();
        OnAfterAssignNewTrackingNo(Rec, xRec, FieldNo("Lot No."));
        Rec."Qty. per Unit of Measure" := QtyPerUOM;
        Validate("Quantity (Base)", QtyToCreate);
        Rec."Entry No." := NextEntryNo;
        TestTempSpecificationExists();
        Rec.Insert();

        OnAssignLotNoOnAfterInsert(Rec);

        TempItemTrackLineInsert.TransferFields(Rec);
        TempItemTrackLineInsert.Insert();
        ItemTrackingDataCollection.UpdateTrackingDataSetWithChange(
          TempItemTrackLineInsert, CurrentSignFactor * SourceQuantityArray[1] < 0, CurrentSignFactor, 0);
        CalculateSums();
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssignLotNo(var TrackingSpecification: Record "Tracking Specification"; var TempItemTrackLineInsert: Record "Tracking Specification" temporary; SourceQuantityArray: array[5] of Decimal; var IsHandled: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
