### ISSUE TITLE
[Event Request] Codeunit 1535 "Approvals Mgmt." - OnBeforeSetApproverType

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#13441]
Hello,

We would need a new event **OnBeforeSetApproverType** in function **SetApproverType**:

    local procedure SetApproverType(WorkflowStepArgument: Record "Workflow Step Argument"; var ApprovalEntry: Record "Approval Entry")
    var
        IsHandled: Boolean;
    begin
        // start new event
        IsHandled := false;
        OnBeforeSetApproverType(ApprovalEntry, IsHandled);
        if IsHandled then
            exit;
        // end new event
        case WorkflowStepArgument."Approver Type" of
            WorkflowStepArgument."Approver Type"::"Salesperson/Purchaser":
                ApprovalEntry."Approval Type" := ApprovalEntry."Approval Type"::"Sales Pers./Purchaser";
            WorkflowStepArgument."Approver Type"::Approver:
                ApprovalEntry."Approval Type" := ApprovalEntry."Approval Type"::Approver;
            WorkflowStepArgument."Approver Type"::"Workflow User Group":
                ApprovalEntry."Approval Type" := ApprovalEntry."Approval Type"::"Workflow User Group";
        end;

        OnAfterSetApproverType(WorkflowStepArgument, ApprovalEntry);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetApproverType(ApprovalEntry: Record "Approval Entry"; var IsHandled: Boolean)
    begin
    end;

**Comment by CameliaPopescu** [comment]
Version to implement >= 18.2.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
