### ISSUE TITLE
[Event Request] page 1872 "Item Availability Check" - OnAfterInitializeFromNotification

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13442]
We would like to add a new event OnAfterInitializeFromNotification in the following procedure:

    procedure InitializeFromNotification(AvailabilityCheckNotification: Notification)
    var
        GrossReq: Decimal;
        SchedRcpt: Decimal;
        ReservedReq: Decimal;
        ReservedRcpt: Decimal;
        CurrentQuantity: Decimal;
        CurrentReservedQty: Decimal;
        EarliestAvailDate: Date;
    begin
        Get(AvailabilityCheckNotification.GetData('ItemNo'));
        SetRange("No.", AvailabilityCheckNotification.GetData('ItemNo'));
        Evaluate(TotalQuantity, AvailabilityCheckNotification.GetData('TotalQuantity'));
        Evaluate(InventoryQty, AvailabilityCheckNotification.GetData('InventoryQty'));
        Evaluate(LocationCode, AvailabilityCheckNotification.GetData('LocationCode'));
        CurrPage.AvailabilityCheckDetails.PAGE.SetUnitOfMeasureCode(
          AvailabilityCheckNotification.GetData('UnitOfMeasureCode'));

        if AvailabilityCheckNotification.GetData('GrossReq') <> '' then begin
            Evaluate(GrossReq, AvailabilityCheckNotification.GetData('GrossReq'));
            CurrPage.AvailabilityCheckDetails.PAGE.SetGrossReq(GrossReq);
        end;
        if AvailabilityCheckNotification.GetData('ReservedReq') <> '' then begin
            Evaluate(ReservedReq, AvailabilityCheckNotification.GetData('ReservedReq'));
            CurrPage.AvailabilityCheckDetails.PAGE.SetReservedReq(ReservedReq);
        end;
        if AvailabilityCheckNotification.GetData('SchedRcpt') <> '' then begin
            Evaluate(SchedRcpt, AvailabilityCheckNotification.GetData('SchedRcpt'));
            CurrPage.AvailabilityCheckDetails.PAGE.SetSchedRcpt(SchedRcpt);
        end;
        if AvailabilityCheckNotification.GetData('ReservedRcpt') <> '' then begin
            Evaluate(ReservedRcpt, AvailabilityCheckNotification.GetData('ReservedRcpt'));
            CurrPage.AvailabilityCheckDetails.PAGE.SetReservedRcpt(ReservedRcpt);
        end;
        if AvailabilityCheckNotification.GetData('CurrentQuantity') <> '' then begin
            Evaluate(CurrentQuantity, AvailabilityCheckNotification.GetData('CurrentQuantity'));
            CurrPage.AvailabilityCheckDetails.PAGE.SetCurrentQuantity(CurrentQuantity);
        end;
        if AvailabilityCheckNotification.GetData('CurrentReservedQty') <> '' then begin
            Evaluate(CurrentReservedQty, AvailabilityCheckNotification.GetData('CurrentReservedQty'));
            CurrPage.AvailabilityCheckDetails.PAGE.SetCurrentReservedQty(CurrentReservedQty);
        end;
        if AvailabilityCheckNotification.GetData('EarliestAvailDate') <> '' then begin
            Evaluate(EarliestAvailDate, AvailabilityCheckNotification.GetData('EarliestAvailDate'));
            CurrPage.AvailabilityCheckDetails.PAGE.SetEarliestAvailDate(EarliestAvailDate);
        end;

        if LocationCode = '' then
            AvailableInventoryCaption := AvailableInventoryLbl
        else
            AvailableInventoryCaption := StrSubstNo('%1 (%2)', AvailableInventoryLbl, LocationCode);
        OnAfterInitializeFromNotification(Rec, AvailabilityCheckNotification); //A200F0000.Event
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterInitializeFromNotification(var Item: Record Item; AvailabilityCheckNotification: Notification)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
