### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnAfterShouldInsertItemTrackingLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13445]
We would like to add a new event OnAfterShouldInsertItemTrackingLine and a new procedure:

    local procedure ShouldInsertItemTrackingLine(ItemTrackingLine: Record "Tracking Specification"; xItemTrackingLine: Record "Tracking Specification") ShouldInsert: Boolean
    begin
        //A200F0000.Event.ns
        ShouldInsert :=
          (ItemTrackingLine."Serial No." <> xItemTrackingLine."Serial No.") or
          (ItemTrackingLine."Lot No." <> xItemTrackingLine."Lot No.") or
          (ItemTrackingLine."Appl.-from Item Entry" <> xItemTrackingLine."Appl.-from Item Entry") or
          (ItemTrackingLine."Appl.-to Item Entry" <> xItemTrackingLine."Appl.-to Item Entry");

        OnAfterShouldInsertItemTrackingLine(ItemTrackingLine, xItemTrackingLine, ShouldInsert);
        //A200F0000.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterShouldInsertItemTrackingLine(ItemTrackingLine: Record "Tracking Specification"; xItemTrackingLine: Record "Tracking Specification"; var ShouldInsert: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by AlexanderYakunin** [comment]
What is the purpose of adding new local procedure, if you will not be able to call it?

**Comment by AlexanderYakunin** [comment]
No reply
