### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnBeforeGetNextSerialNo

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13443]
We would like to add a new event OnBeforeGetNextSerialNo and a new procedure:

    local procedure GetNextSerialNo(Item: Record Item) SerialNo: Code[50]
    var
        IsHandled: Boolean;
    begin
        //A200F0000.Event.n
        OnBeforeGetNextSerialNo(SourceTrackingSpecification, SerialNo, IsHandled);
        if IsHandled then
            exit(SerialNo);

        SerialNo := NoSeriesMgt.GetNextNo(Item."Serial Nos.", WorkDate(), true);
        //A200F0000.Event.e
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetNextSerialNo(var SourceTrackingSpecification: Record "Tracking Specification"; var SerialNo: Code[50]; var IsHandled: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by AlexanderYakunin** [comment]
Please explain how new local procedure will be used?

**Comment by AlexanderYakunin** [comment]
No reply
