### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnBeforeTestTempSpecificationExists

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13446]
We would like to add a new event OnBeforeTestTempSpecificationExists in the following procedure:

    procedure TestTempSpecificationExists() Exists: Boolean
    var
        TrackingSpecification: Record "Tracking Specification";
    begin
        //A200F0000.Event.ns
        if not TrackingExists() then
            exit(false);
        //A200F0000.Event.ne
        TrackingSpecification.Copy(Rec);
        Rec.SetCurrentKey("Lot No.", "Serial No.");
        Rec.SetRange("Serial No.", Rec."Serial No.");
        if Rec."Serial No." = '' then
            Rec.SetNonSerialTrackingFilterFromSpec(Rec);
        OnBeforeTestTempSpecificationExists(Rec); //A200F0000.Event.n

        Rec.SetFilter("Entry No.", '<>%1', Rec."Entry No.");
        Rec.SetRange("Buffer Status", 0);

        OnTestTempSpecificationExistsOnAfterSetFilters(Rec);
        Exists := not Rec.IsEmpty();
        Rec.Copy(TrackingSpecification);
        if Exists and CurrentPageIsOpen then
            if Rec."Serial No." = '' then
                Message(Text011, Rec."Serial No.", Rec."Lot No.", Rec."Package No.")
            else
                Message(Text012, Rec."Serial No.");
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTestTempSpecificationExists(var TrackingSpecification: Record "Tracking Specification")
    begin
        //A200F0000.Event
    end;

**Comment by AlexanderYakunin** [comment]
We already have event OnTestTempSpecificationExistsOnAfterSetFilters(Rec), why you cannot use this one?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
