### ISSUE TITLE
[Event Request] page 7159 "Invt. Analysis by Dimensions" - OnBeforeUpdateLocationColumnCaptions

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13440]
We would like to add a new event OnBeforeUpdateLocationColumnCaptions in the following trigger: 

                    trigger OnValidate()
                    var
                        UpdateColumnCaptions: Boolean;
                    begin
                        ItemStatisticsBuffer.SetFilter("Location Filter", LocationFilter);
                        //if ColumnDimOption = ColumnDimOption::Location then A200F0010.o
                        //A200F0010.Event.ns
                        UpdateColumnCaptions := ColumnDimOption = ColumnDimOption::Location;
                        OnBeforeUpdateLocationColumnCaptions(ItemAnalysisView, ItemStatisticsBuffer, ColumnDimOption, UpdateColumnCaptions);
                        if UpdateColumnCaptions then
                            //A200F0010.Event.ne
                            MATRIX_GenerateColumnCaptions(MATRIX_Step::Initial);
                        CurrPage.Update(false);
                    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateLocationColumnCaptions(var ItemAnalysisView: Record "Item Analysis View"; var ItemStatisticsBuffer: Record "Item Statistics Buffer"; ColumnDimOption: Option Item,Period,Location,"Dimension 1","Dimension 2","Dimension 3"; var UpdateColumnCaptions: Boolean)
    begin
        //A200F0010.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
