### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnAfterQtyToHandleOrInvoiceDifferFromQuantity

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13452]
We would like to add a new event OnAfterQtyToHandleOrInvoiceDifferFromQuantity and a new procedure

    local procedure QtyToHandleOrInvoiceDifferFromQuantity(ItemTrackingLine: Record "Tracking Specification"; xItemTrackingLine: Record "Tracking Specification") HasChanged: Boolean
    begin
        //A109F0006.Event.ns
        HasChanged :=
            (ItemTrackingLine."Quantity (Base)" <> xItemTrackingLine."Qty. to Handle (Base)") or
            (ItemTrackingLine."Quantity (Base)" <> xItemTrackingLine."Qty. to Invoice (Base)");

        OnAfterQtyToHandleOrInvoiceDifferFromQuantity(ItemTrackingLine, xItemTrackingLine, HasChanged);
        //A109F0006.Event.ne
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterQtyToHandleOrInvoiceDifferFromQuantity(LeftItemTrackingLine: Record "Tracking Specification"; RightItemTrackingLine: Record "Tracking Specification"; var HasChanged: Boolean)
    begin
        //A109F0006.Event
    end;

**Comment by AlexanderYakunin** [comment]
Please explain why do you need new local procedure?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
