### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnBeforeInsertCopiedTrackingSpecification

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13454]
We would like to add a new event OnBeforeInsertCopiedTrackingSpecification in the following procedure:

    procedure RegisterItemTrackingLines(SourceSpecification: Record "Tracking Specification"; AvailabilityDate: Date; var TempTrackingSpecification: Record "Tracking Specification" temporary)
    begin
        SourceSpecification.TestField("Source Type"); // Check if source has been set.
        if not CalledFromSynchWhseItemTrkg then
            TempTrackingSpecification.Reset();
        if not TempTrackingSpecification.Find('-') then
            exit;

        IsCorrection := SourceSpecification.Correction;
        ExcludePostedEntries := true;
        SetSourceSpec(SourceSpecification, AvailabilityDate);
        Rec.Reset();
        Rec.SetCurrentKey("Lot No.", "Serial No.");

        repeat
            SetTrackingFilterFromSpec(TempTrackingSpecification);
            //A200F0000.Event.ns
            if CurrentRunMode = CurrentRunMode::Reclass then
                Rec.SetNewTrackingFilterFromNewTrackingSpec(TempTrackingSpecification);
            //A200F0000.Event.ne
            if Find('-') then begin
                OnAfterFindItemTrackingLineToRegister(Rec, TempTrackingSpecification); //A200F0000.Event
                if IsCorrection then begin
                    Rec."Quantity (Base)" += TempTrackingSpecification."Quantity (Base)";
                    Rec."Qty. to Handle (Base)" += TempTrackingSpecification."Qty. to Handle (Base)";
                    Rec."Qty. to Invoice (Base)" += TempTrackingSpecification."Qty. to Invoice (Base)";
                end else
                    if TempTrackingSpecification."Quantity (Base)" <> 0 then //A200F0001.Event
                        Rec.Validate("Quantity (Base)", "Quantity (Base)" + TempTrackingSpecification."Quantity (Base)");
                Rec.Modify();
            end else begin
                Rec.TransferFields(SourceSpecification);
                Rec.CopyTrackingFromTrackingSpec(TempTrackingSpecification);
                Rec."Warranty Date" := TempTrackingSpecification."Warranty Date";
                Rec."Expiration Date" := TempTrackingSpecification."Expiration Date";
                if CurrentRunMode = CurrentRunMode::Reclass then begin
                    Rec."New Serial No." := TempTrackingSpecification."New Serial No.";
                    Rec."New Lot No." := TempTrackingSpecification."New Lot No.";
                    Rec."New Expiration Date" := TempTrackingSpecification."New Expiration Date";
                    OnRegisterItemTrackingLinesOnAfterReclass(Rec, TempTrackingSpecification);
                end;
                OnAfterCopyTrackingSpec(TempTrackingSpecification, Rec);
                Rec.Validate("Quantity (Base)", TempTrackingSpecification."Quantity (Base)");
                Rec."Entry No." := NextEntryNo;
                OnBeforeInsertCopiedTrackingSpecification(Rec, TempTrackingSpecification, SourceTrackingSpecification); //A109F0006.Event.n
                Rec.Insert();
            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertCopiedTrackingSpecification(var TrackingSpecification: Record "Tracking Specification"; FromTrackingSpecification: Record "Tracking Specification"; SourceTrackingSpecification: Record "Tracking Specification")
    begin
        //A109F0006.Event        
    end;

**Comment by AlexanderYakunin** [comment]
Please explain why you would like to change our code? Is this a bug fix or what?

**Comment by AlexanderYakunin** [comment]
No reply
