### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnBeforeSetWarehouseControls

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13457]
We would like to add a new event OnBeforeSetWarehouseControls in the following procedure: 

    procedure SetSourceSpec(TrackingSpecification: Record "Tracking Specification"; AvailabilityDate: Date)
    var
        ReservEntry: Record "Reservation Entry";
        TempTrackingSpecification: Record "Tracking Specification" temporary;
        TempTrackingSpecification2: Record "Tracking Specification" temporary;
        CreateReservEntry: Codeunit "Create Reserv. Entry";
        Controls: Option Handle,Invoice,Quantity,Reclass,Tracking;
        CurrentEntryStatusOption: Option;
        IsHandled: Boolean;
    begin
        OnBeforeSetSourceSpec(TrackingSpecification, ReservEntry);

        SourceTrackingSpecification := TrackingSpecification; //A200F0000.Event
        GetItem(TrackingSpecification."Item No.");
        ForBinCode := TrackingSpecification."Bin Code";
        SetFilters(TrackingSpecification);
        TempTrackingSpecification.DeleteAll();
        TempItemTrackLineInsert.DeleteAll();
        TempItemTrackLineModify.DeleteAll();
        TempItemTrackLineDelete.DeleteAll();

        TempReservEntry.DeleteAll();
        LastEntryNo := 0;
        if ItemTrackingMgt.IsOrderNetworkEntity(TrackingSpecification."Source Type",
             TrackingSpecification."Source Subtype") and not (CurrentRunMode = CurrentRunMode::"Drop Shipment")
        then
            CurrentEntryStatus := CurrentEntryStatus::Surplus
        else
            CurrentEntryStatus := CurrentEntryStatus::Prospect;

        if (TrackingSpecification."Source Type" = DATABASE::"Transfer Line") and (CurrentRunMode = CurrentRunMode::Reclass) then
            CurrentEntryStatus := CurrentEntryStatus::Prospect;

        CurrentEntryStatusOption := CurrentEntryStatus.AsInteger();
        OnSetSourceSpecOnAfterAssignCurrentEntryStatus(TrackingSpecification, CurrentEntryStatusOption);
        CurrentEntryStatus := "Reservation Status".FromInteger(CurrentEntryStatusOption);

        // Set controls for Qty to handle:
        SetControls(Controls::Handle, GetHandleSource(TrackingSpecification));
        // Set controls for Qty to Invoice:
        SetControls(Controls::Invoice, GetInvoiceSource(TrackingSpecification));

        SetControls(Controls::Reclass, CurrentRunMode = CurrentRunMode::Reclass);

        if CurrentRunMode = CurrentRunMode::"Combined Ship/Rcpt" then
            SetControls(Controls::Tracking, false);
        //A200F0000.Event.ns
        IsHandled := false;
        OnBeforeSetWarehouseControls(Rec, IsHandled);
        if not IsHandled then
            //A200F0000.Event.ne
            if ItemTrackingMgt.ItemTrkgIsManagedByWhse(
                 TrackingSpecification."Source Type",
                 TrackingSpecification."Source Subtype",
                 TrackingSpecification."Source ID",
                 TrackingSpecification."Source Prod. Order Line",
                 TrackingSpecification."Source Ref. No.",
                 TrackingSpecification."Location Code",
                 TrackingSpecification."Item No.")
            then begin
                SetControls(Controls::Quantity, false);
                QtyToHandleBaseEditable := true;
                DeleteIsBlocked := true;
                ItemTrackingManagedByWhse := true;
            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetWarehouseControls(TrackingSpecification: Record "Tracking Specification"; var IsHandled: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
