### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnBeforeSynchronizeWarehouseItemTracking

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13456]
We would like to add a new event OnBeforeSynchronizeWarehouseItemTracking in the following procedure:

    protected procedure SynchronizeWarehouseItemTracking()
    var
        WarehouseShipmentLine: Record "Warehouse Shipment Line";
        Location: Record Location;
        WarehouseEntry: Record "Warehouse Entry";
        ItemTrackingMgt: Codeunit "Item Tracking Management";
        WhseManagement: Codeunit "Whse. Management";
        IsHandled: Boolean;
    begin
        //A200F0000.Event.ns
        OnBeforeSynchronizeWarehouseItemTracking(Rec, IsHandled);
        if IsHandled then
            exit;
        //A200F0000.Event.ne
        if ItemTrackingMgt.ItemTrkgIsManagedByWhse(
             Rec."Source Type", Rec."Source Subtype", Rec."Source ID",
             Rec."Source Prod. Order Line", Rec."Source Ref. No.", Rec."Location Code", Rec."Item No.")
        then
            exit;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSynchronizeWarehouseItemTracking(TrackingSpecification: Record "Tracking Specification"; var IsHandled: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
