### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnAfterCalculateSums

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13450]
We would like to add a new event OnAfterCalculateSums in the following procedure

    procedure CalculateSums()
    var
        xTrackingSpec: Record "Tracking Specification";
    begin
        xTrackingSpec.Copy(Rec);
        Rec.Reset();
        Rec.CalcSums("Quantity (Base)", "Qty. to Handle (Base)", "Qty. to Invoice (Base)");
        TotalItemTrackingLine := Rec;
        Rec.Copy(xTrackingSpec);

        OnAfterCalculateSums(Rec, SourceTrackingSpecification, TotalItemTrackingLine); //A109F0006.Event.n
        UpdateUndefinedQtyArray();
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalculateSums(var TrackingSpecification: Record "Tracking Specification"; SourceTrackingSpecification: Record "Tracking Specification"; var TotalItemTrackingLine: Record "Tracking Specification")
    begin
        //A109F0006.Event
    end;

**Comment by AlexanderYakunin** [comment]
We do not have global variable SourceTrackingSpecification in this page. Please clarify.

**Comment by AlexanderYakunin** [comment]
We already have this event OnCalculateSumsOnAfterCalcSums(Rec).
