### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnBeforeAddToGlobalRecordSet

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13458]
We would like to add a new event OnBeforeAddToGlobalRecordSet in the following procedure:

    local procedure AddToGlobalRecordSet(var TempTrackingSpecification: Record "Tracking Specification" temporary)
    var
        ExpDate: Date;
        EntriesExist: Boolean;
    begin
        TempTrackingSpecification.SetCurrentKey("Lot No.", "Serial No.");
        if TempTrackingSpecification.Find('-') then
            repeat
                TempTrackingSpecification.SetTrackingFilterFromSpec(TempTrackingSpecification);
                TempTrackingSpecification.CalcSums("Quantity (Base)", "Qty. to Handle (Base)",
                  "Qty. to Invoice (Base)", "Quantity Handled (Base)", "Quantity Invoiced (Base)");
                if TempTrackingSpecification."Quantity (Base)" <> 0 then begin
                    Rec := TempTrackingSpecification;
                    Rec."Quantity (Base)" *= CurrentSignFactor;
                    Rec."Qty. to Handle (Base)" *= CurrentSignFactor;
                    Rec."Qty. to Invoice (Base)" *= CurrentSignFactor;
                    Rec."Quantity Handled (Base)" *= CurrentSignFactor;
                    Rec."Quantity Invoiced (Base)" *= CurrentSignFactor;
                    Rec."Qty. to Handle" := Rec.CalcQty(Rec."Qty. to Handle (Base)");
                    Rec."Qty. to Invoice" := Rec.CalcQty(Rec."Qty. to Invoice (Base)");
                    Rec."Entry No." := NextEntryNo;

                    // skip expiration date check for performance
                    // item tracking code is cached at the beginning of the caller method
                    if not ItemTrackingCode."Use Expiration Dates" then
                        Rec."Buffer Status2" := Rec."Buffer Status2"::"ExpDate blocked"
                    else begin
                        ExpDate := ItemTrackingMgt.ExistingExpirationDate(Rec, false, EntriesExist);
                        if ExpDate <> 0D then begin
                            Rec."Expiration Date" := ExpDate;
                            Rec."Buffer Status2" := Rec."Buffer Status2"::"ExpDate blocked";
                        end;
                    end;

                    //OnBeforeAddToGlobalRecordSet(Rec, EntriesExist, CurrentSignFactor); A109F0006.Event.o
                    OnBeforeAddToGlobalRecordSet(Rec, TempTrackingSpecification, EntriesExist, CurrentSignFactor); //A109F0006.Event.n
                    Rec.Insert();

                    if Rec."Buffer Status" = 0 then begin
                        xTempItemTrackingLine := Rec;
                        xTempItemTrackingLine.Insert();
                    end;
                end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAddToGlobalRecordSet(var TrackingSpecification: Record "Tracking Specification"; var TempTrackingSpecification: Record "Tracking Specification" temporary; EntriesExist: Boolean; CurrentSignFactor: Integer)
    begin
        //A109F0006.Event Parameter TempTrackingSpecification
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
