### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnAfterQtyToHandleAndInvoiceChanged

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13451]
We would like to add a new event OnAfterQtyToHandleAndInvoiceChanged and a new procedure: 

    local procedure QtyToHandleAndInvoiceChanged(var ReservEntry1: Record "Reservation Entry"; var ReservEntry2: Record "Reservation Entry") HasChanged: Boolean
    begin
        HasChanged :=
          (ReservEntry1."Qty. to Handle (Base)" <> ReservEntry2."Qty. to Handle (Base)") or
          (ReservEntry1."Qty. to Invoice (Base)" <> ReservEntry2."Qty. to Invoice (Base)");

        OnAfterQtyToHandleAndInvoiceChanged(ReservEntry1, ReservEntry2, HasChanged); //A109F0006.Event.n
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterQtyToHandleAndInvoiceChanged(LeftReservationEntry: Record "Reservation Entry"; RightReservationEntry: Record "Reservation Entry"; var HasChanged: Boolean)
    begin
        //A109F0006.Event
    end;

**Comment by AlexanderYakunin** [comment]
Please explain how you are going to use this new procedure?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
