### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnBeforeCheckLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13455]
We would like to add a new event OnBeforeCheckLine and a new procedure:

    procedure CheckLine(TrackingLine: Record "Tracking Specification")
    var
        IsHandled: Boolean;
    begin
        //A200F0000.Event.ns
        OnBeforeCheckLine(TrackingLine, SourceQuantityArray, IsHandled);
        if IsHandled then
            exit;
        //A200F0000.Event.ne
        if TrackingLine."Quantity (Base)" * SourceQuantityArray[1] < 0 then
            if SourceQuantityArray[1] < 0 then
                Error(Text002, Text003)
            else
                Error(Text002, Text004);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckLine(TrackingLine: Record "Tracking Specification"; SourceQuantityArray: array[5] of Decimal; var IsHandled: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
