### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnBeforeAssignNewLotNo

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13459]
We would like to add a new event OnBeforeAssignNewLotNo in the following procedure:

    local procedure AssignNewLotNo()
    var
        IsHandled: Boolean;
    begin
        //OnBeforeAssignNewLotNo(Rec, IsHandled); //A200F0000.Event.o
        OnBeforeAssignNewLotNo(Rec, SourceTrackingSpecification, IsHandled); //A200F0000.Event.n
        if IsHandled then
            exit;

        Item.TestField("Lot Nos.");
        Rec.Validate("Lot No.", NoSeriesMgt.GetNextNo(Item."Lot Nos.", WorkDate, true));
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssignNewLotNo(var TrackingSpecification: Record "Tracking Specification"; var SourceTrackingSpecification: Record "Tracking Specification"; var IsHandled: Boolean)
    begin
        //A200F0000.Event Parameter SourceTrackingSpecification
    end;

**Comment by AlexanderYakunin** [comment]
What is SourceTrackingSpecification here? It des not exist in Item Tracking Lines page.
