### ISSUE TITLE
Table 130 Incoming Document VAR DocExist

### ISSUE THREAD

**Issue by clausmacali** [Microsoft/ALAppExtensions#1345]
Hi

Can we in 130, the VAR DocExist

Local [IntegrationEvent] OnAfterUpdateDocumentFields(VAR IncomingDocument : Record "Incoming Document; VAR DocExist : Bolean)

**Comment by JesperSchulz** [comment]
Not sure I understand what your request is. Could you elaborate? Both parameters are VAR.

**Comment by clausmacali** [comment]
Hi Jesper

We need 3 events

Today we have

[cid:image002.jpg@01D4CE14.BB20E530]

Required is this
[cid:image004.jpg@01D4CE14.BB20E530]

Med venlig hilsen
Best Regards

Claus Petersen
MACALI ApS
Hegnsgårdsvej 38
DK-7120 Vejle Ø
claus@macali.dk

Mobil + 45 52 23 70 70
_______________________________________________________________________________________________
[macali-03]    [navapp-05]
_______________________________________________________________________________________________




Fra: Jesper Schulz-Wedde <notifications@github.com>
Sendt: 26. februar 2019 10:43
Til: Microsoft/ALAppExtensions <ALAppExtensions@noreply.github.com>
Cc: Claus Petersen <claus@navapp.dk>; Author <author@noreply.github.com>
Emne: Re: [Microsoft/ALAppExtensions] Table 130 Incoming Document VAR DocExist (#1345)


Not sure I understand what your request is. Could you elaborate? Both parameters are VAR.

**Comment by JesperSchulz** [comment]
Sorry, I cannot see those pictures :-) Could you try once more?

**Comment by clausmacali** [comment]
Hi Jesper

In this doc

Med venlig hilsen
Best Regards

Claus Petersen
MACALI ApS
Hegnsgårdsvej 38
DK-7120 Vejle Ø
claus@macali.dk

Mobil + 45 52 23 70 70
_______________________________________________________________________________________________
[macali-03]    [navapp-05]
_______________________________________________________________________________________________




Fra: Jesper Schulz-Wedde <notifications@github.com>
Sendt: 27. februar 2019 11:18
Til: Microsoft/ALAppExtensions <ALAppExtensions@noreply.github.com>
Cc: Claus Petersen <claus@navapp.dk>; Author <author@noreply.github.com>
Emne: Re: [Microsoft/ALAppExtensions] Table 130 Incoming Document VAR DocExist (#1345)


Sorry, I cannot see those pictures :-) Could you try once more?

**Comment by JesperSchulz** [comment]
I'm sorry, but I cannot access that doc either. Attachment to GitHub Mail replies don't work. Could you post your request in a "traditional" way on GitHub please.

**Comment by clausmacali** [comment]
Hi Jesper
Is for use need so we can control what we we got in the incomming Document in 130
Thanks

Local [IntegrationEvent] OnAfterFindPostdRecord(VAR IncomingDocument : Record "Incoming Document; VAR RelatedRecord : Variant;VAR RecordFound : Bolean)

Local [IntegrationEvent] OnAfterFindUnpostedRecord(VAR IncomingDocument : Record "Incoming Document; VAR RelatedRecord : Variant;VAR RecordFound : Bolean)

Local [IntegrationEvent] OnAfterUpdateDocumentFields(VAR IncomingDocument : Record "Incoming Document; VAR DocExist : Bolean)

**Comment by JesperSchulz** [comment]
Ah, so you'd like us to add incoming document as parameter to those three event publishers? Got it! Creating work item for us.

**Comment by clausmacali** [comment]
Thanks :)
