### ISSUE TITLE
[Event Request] page 399 "Purchase Receipt Statistics" - OnCalculateTotalsOnAfterAddLineTotals

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13468]
We would like to add a new event OnCalculateTotalsOnAfterAddLineTotals in the following procedure:

    local procedure CalculateTotals()
    var
        PurchRcptLine: Record "Purch. Rcpt. Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalculateTotals(Rec, LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels, IsHandled);
        if IsHandled then
            exit;

        PurchRcptLine.SetRange("Document No.", "No.");
        if PurchRcptLine.Find('-') then
            repeat
                LineQty := LineQty + PurchRcptLine.Quantity;
                TotalNetWeight := TotalNetWeight + (PurchRcptLine.Quantity * PurchRcptLine."Net Weight");
                TotalGrossWeight := TotalGrossWeight + (PurchRcptLine.Quantity * PurchRcptLine."Gross Weight");
                TotalVolume := TotalVolume + (PurchRcptLine.Quantity * PurchRcptLine."Unit Volume");
                if PurchRcptLine."Units per Parcel" > 0 then
                    TotalParcels := TotalParcels + Round(PurchRcptLine.Quantity / PurchRcptLine."Units per Parcel", 1, '>');
                OnCalculateTotalsOnAfterAddLineTotals(
                    Rec, //A108F0039.Event
                    PurchRcptLine, LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels)
            until PurchRcptLine.Next() = 0;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnCalculateTotalsOnAfterAddLineTotals(PurchRcptHeader: Record "Purch. Rcpt. Header"; var PurchRcptLine: Record "Purch. Rcpt. Line"; var LineQty: Decimal; var TotalNetWeight: Decimal; var TotalGrossWeight: Decimal; var TotalVolume: Decimal; var TotalParcels: Decimal)
    begin
        //A108F0039.Event Parameter PurchRcptHeader
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
