### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnAfterSetQtyToHandleAndInvoiceOnBeforeReservEntryModify

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13465]
We would like to add  2 new events OnAfterSetQtyToHandleAndInvoiceOnBeforeReservEntryModify in the following procedure:

    local procedure SetQtyToHandleAndInvoice(TrackingSpecification: Record "Tracking Specification")
.
.
.

Event 1:

                        if (ReservEntry1."Qty. to Handle (Base)" <> QtyToHandleThisLine) or
                           (ReservEntry1."Qty. to Invoice (Base)" <> QtyToInvoiceThisLine) and not ReservEntry1.Correction
                        then begin
                            ReservEntry1."Qty. to Handle (Base)" := QtyToHandleThisLine;
                            ReservEntry1."Qty. to Invoice (Base)" := QtyToInvoiceThisLine;
                            OnSetQtyToHandleAndInvoiceOnBeforeReservEntryModify(ReservEntry1, TrackingSpecification);
                            //ReservEntry1.Modify(); //A109F0006.Event.o
                            ModifyLine := true; //A109F0006.Event.n
                        end;
                        TotalQtyToHandle -= QtyToHandleThisLine;
                        TotalQtyToInvoice -= QtyToInvoiceThisLine;
                        //A109F0006.Event.ns
                        OnAfterSetQtyToHandleAndInvoiceOnBeforeReservEntryModify(ReservEntry1, TrackingSpecification, TotalTrackingSpecification, ModifyLine);
                        if ModifyLine then
                            ReservEntry1.Modify();
                    //A109F0006.Event.ne
                    until (ReservEntry1.Next() = 0);
            end

Event 2:

                if (ReservEntry1."Qty. to Handle (Base)" <> TotalQtyToHandle) or
                   (ReservEntry1."Qty. to Invoice (Base)" <> TotalQtyToInvoice) and not ReservEntry1.Correction
                then begin
                    ReservEntry1."Qty. to Handle (Base)" := TotalQtyToHandle;
                    ReservEntry1."Qty. to Invoice (Base)" := TotalQtyToInvoice;
                    OnSetQtyToHandleAndInvoiceOnBeforeReservEntryModify(ReservEntry1, TrackingSpecification);
                    //ReservEntry1.Modify(); /A109F0006.Event.o
                    ModifyLine := true; //A109F0006.Event.n
                end;
                //A109F0006.Event.ns
                OnAfterSetQtyToHandleAndInvoiceOnBeforeReservEntryModify(ReservEntry1, TrackingSpecification, TotalTrackingSpecification, ModifyLine);
                if ModifyLine then
                    ReservEntry1.Modify();
            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetQtyToHandleAndInvoiceOnBeforeReservEntryModify(var ReservationEntry: Record "Reservation Entry"; TrackingSpecification: Record "Tracking Specification"; var TotalTrackingSpecification: Record "Tracking Specification"; var ModifyLine: Boolean)
    begin
        //A109F0006.Event.n
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
