### ISSUE TITLE
[Bug] Page 6510 TestTempSpecificationExists

### ISSUE THREAD

**Issue by Bleika** [microsoft/ALAppExtensions#1346]
This function is used to make sure that the user doesn't define a particular lot more than once.

However, it doesn't take the Reclassification(P393->P6510) scenario into consideration:
When a user wants to split an original lot in several smaller lots, he should be allowed to insert several lines with the same value in the "Lot No." field: what matters here is the "New Lot No." which will be the basis for new Item Tracking.

This is working fine in WMS Reclassification (P7365->P6550): users can introduce several lines with the same "Lot No." and different "New Lot No."

There are 2 options to solve this, no. 2 is of course a more thorough solution, but it will require a new key on T336 for "New Lot No.","New Serial No.":

1) Totally disable check within this function by using the FormRunMode variable
if FormRunMode <> FormRunMode::Reclass then begin
perform the existing checks

2) Split the check in two:
if FormRunMode <> FormRunMode::Reclass then begin
perform the existing checks
end else
perform identical checks against "New Lot No."/"New Serial No."

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
