### ISSUE TITLE
codeunit 8 AccSchedManagement

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#13469]
I would like to use the global prozedure "CalcColumnDates". But unfortunately this does not work, because some variables are defined globally. Can you pass these variables as parameters?

old:
`procedure CalcColumnDates(ColumnLayout: Record "Column Layout"; var FromDate: Date; var ToDate: Date; var FiscalStartDate2: Date)`

new:
`procedure CalcColumnDates(ColumnLayout: Record "Column Layout"; var FromDate: Date; var ToDate: Date; var FiscalStartDate2: Date; StartDate: Date; EndDate: Date; FiscalStartDate: Date)`

**Comment by AlexanderYakunin** [comment]
No, we cannot change signature of global procedure. You should copy this code to your extension or try to use this procedure together with 

    procedure SetStartDateEndDate(NewStartDate: Date; NewEndDate: Date)
    begin
        StartDate := NewStartDate;
        EndDate := NewEndDate;
    end;
