### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnRegisterChangeOnAfterModify

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13464]
We would like to add a new event OnRegisterChangeOnAfterModify in the following procedure: 

                        end;

                        OldTrackingSpecification."Quantity (Base)" := QtyToAdd;
                        OldTrackingSpecification."Warranty Date" := NewTrackingSpecification."Warranty Date";
                        OldTrackingSpecification."Expiration Date" := NewTrackingSpecification."Expiration Date";
                        OldTrackingSpecification.Description := NewTrackingSpecification.Description;
                        OnAfterCopyTrackingSpec(NewTrackingSpecification, OldTrackingSpecification);

                        RegisterChange(OldTrackingSpecification, OldTrackingSpecification,
                          ChangeType::Insert, not IdenticalArray[2]);
                    end else begin
                        TempReservEntry.SetTrackingFilterFromSpec(OldTrackingSpecification);
                        OldTrackingSpecification.ClearTracking;
                        OnAfterClearTrackingSpec(OldTrackingSpecification);
                        QtyToAdd :=
                          CurrentSignFactor *
                          ReservEngineMgt.AddItemTrackingToTempRecSet(
                            TempReservEntry, OldTrackingSpecification,
                            CurrentSignFactor * (OldTrackingSpecification."Quantity (Base)" -
                                                 NewTrackingSpecification."Quantity (Base)"), QtyToAddAsBlank,
                            ItemTrackingCode);
                        TempReservEntry.ClearTrackingFilter();
                        RegisterChange(NewTrackingSpecification, NewTrackingSpecification,
                          ChangeType::PartDelete, not IdenticalArray[2]);
                    end;
                    //OnRegisterChangeOnAfterModify(NewTrackingSpecification, OldTrackingSpecification); //A200F0000.Event.o
                    OnRegisterChangeOnAfterModify(NewTrackingSpecification, OldTrackingSpecification, OriginalOldTrackingSpecification, CurrentPageIsOpen); //A200F0000.Event.n
                    OK := true;
                end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnRegisterChangeOnAfterModify(var NewTrackingSpecification: Record "Tracking Specification"; var OldTrackingSpecification: Record "Tracking Specification"; var OriginalOldTrackingSpecification: Record "Tracking Specification"; CurrentPageIsOpen: Boolean)
    begin
        //A200F0000.Event parameter OriginalOldTrackingSpecification and CurrentPageIsOpen
    end;

**Comment by AlexanderYakunin** [comment]
We do not have OriginalOldTrackingSpecification in this page

**Comment by AlexanderYakunin** [comment]
Adding CurrentPageIsOpen only

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
