### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnRegisterChangeOnAfterFullDelete

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13462]
We would like to add a new event OnRegisterChangeOnAfterFullDelete in the following procedure:

    local procedure RegisterChange(var OldTrackingSpecification: Record "Tracking Specification"; var NewTrackingSpecification: Record "Tracking Specification"; ChangeType: Option Insert,Modify,FullDelete,PartDelete,ModifyAll; ModifySharedFields: Boolean) OK: Boolean
.
.
.

                    if ChangeType = ChangeType::FullDelete then begin
                        TempReservEntry.SetTrackingFilterFromSpec(OldTrackingSpecification);
                        OldTrackingSpecification.ClearTracking;
                        OnAfterClearTrackingSpec(OldTrackingSpecification);
                        QtyToAdd :=
                          CurrentSignFactor *
                          ReservEngineMgt.AddItemTrackingToTempRecSet(
                            TempReservEntry, OldTrackingSpecification,
                            CurrentSignFactor * OldTrackingSpecification."Quantity (Base)",
                            QtyToAddAsBlank, ItemTrackingCode);
                        TempReservEntry.ClearTrackingFilter();
                        ReservationMgt.DeleteReservEntries(true, 0, ReservEntry1);
                        //OnRegisterChangeOnAfterFullDelete(ReservEntry1); //A200F0000.Event.o
                        OnRegisterChangeOnAfterFullDelete(NewTrackingSpecification, OldTrackingSpecification, ReservEntry1, CurrentPageIsOpen); //A200F0000.Event.n
                    end else begin
                        ReservationMgt.DeleteReservEntries(false, ReservEntry1."Quantity (Base)" -
                          OldTrackingSpecification."Quantity Handled (Base)", ReservEntry1);
                        if ModifySharedFields then begin
                            ReservEntry1.SetRange("Reservation Status");
                            ModifyFieldsWithinFilter(ReservEntry1, OldTrackingSpecification);
                        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnRegisterChangeOnAfterFullDelete(var NewTrackingSpecification: Record "Tracking Specification"; var OldTrackingSpecification: Record "Tracking Specification"; var ReservEntry: Record "Reservation Entry"; CurrentPageIsOpen: Boolean)
    begin
        //A200F0000.Event parameter OldTrackingSpecification and CurrentPageIsOpen
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
