### ISSUE TITLE
[Event Request] page 400 "Purchase Invoice Statistics" - OnCalculateTotalsOnAfterAddLineTotals

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13467]
We would like to add a new event OnCalculateTotalsOnAfterAddLineTotals in the following procedure:

    local procedure CalculateTotals()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalculateTotals(
            Rec, VendAmount, AmountInclVAT, InvDiscAmount,
            LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels, IsHandled);
        if IsHandled then
            exit;

        PurchInvLine.SetRange("Document No.", "No.");
        if PurchInvLine.Find('-') then
            repeat
                VendAmount += PurchInvLine.Amount;
                AmountInclVAT += PurchInvLine."Amount Including VAT";
                if "Prices Including VAT" then
                    InvDiscAmount += PurchInvLine."Inv. Discount Amount" / (1 + PurchInvLine."VAT %" / 100)
                else
                    InvDiscAmount += PurchInvLine."Inv. Discount Amount";
                LineQty += PurchInvLine.Quantity;
                TotalNetWeight += PurchInvLine.Quantity * PurchInvLine."Net Weight";
                TotalGrossWeight += PurchInvLine.Quantity * PurchInvLine."Gross Weight";
                TotalVolume += PurchInvLine.Quantity * PurchInvLine."Unit Volume";
                if PurchInvLine."Units per Parcel" > 0 then
                    TotalParcels += Round(PurchInvLine.Quantity / PurchInvLine."Units per Parcel", 1, '>');
                if PurchInvLine."VAT %" <> VATPercentage then
                    if VATPercentage = 0 then
                        VATPercentage := PurchInvLine."VAT %"
                    else
                        VATPercentage := -1;

                OnCalculateTotalsOnAfterAddLineTotals(
                    Rec, //A108F0039.Event
                    PurchInvLine, VendAmount, AmountInclVAT, InvDiscAmount,
                    LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels, VATPercentage)
            until PurchInvLine.Next() = 0;

        OnAfterCalculateTotals(
            Rec, VendAmount, AmountInclVAT, InvDiscAmount,
            LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnCalculateTotalsOnAfterAddLineTotals(PurchInvHeader: Record "Purch. Inv. Header"; var PurchInvLine: Record "Purch. Inv. Line"; var VendAmount: Decimal; var AmountInclVAT: Decimal; var InvDiscAmount: Decimal; var LineQty: Decimal; var TotalNetWeight: Decimal; var TotalGrossWeight: Decimal; var TotalVolume: Decimal; var TotalParcels: Decimal; var VATPercentage: Decimal)
    begin
        //A108F0039.Event Parameter PurchInvHeader: Record "Purch. Inv. Header"; PurchInvHeader 
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
