### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnAfterSetQtyToHandleAndInvoiceOnBeforeTrackingSpecModify

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13466]
We would like to add a new event OnAfterSetQtyToHandleAndInvoiceOnBeforeTrackingSpecModify in the following procedure:

    local procedure SetQtyToHandleAndInvoice(TrackingSpecification: Record "Tracking Specification")
    var
        ReservEntry1: Record "Reservation Entry";
        TotalTrackingSpecification: Record "Tracking Specification";
        TotalQtyToHandle: Decimal;
        TotalQtyToInvoice: Decimal;
        QtyToHandleThisLine: Decimal;
        QtyToInvoiceThisLine: Decimal;
        ModifyLine: Boolean;
    begin
        if IsCorrection then
            exit;

        //A109F0006.Event.ns
        TotalTrackingSpecification := TrackingSpecification;
        OnBeforeSetQtyToHandleAndInvoice(TotalTrackingSpecification, CurrentSignFactor);
        //A109F0006.Event.ne
        TotalQtyToHandle := TrackingSpecification."Qty. to Handle (Base)" * CurrentSignFactor;
        TotalQtyToInvoice := TrackingSpecification."Qty. to Invoice (Base)" * CurrentSignFactor;

        ReservEntry1.TransferFields(TrackingSpecification);
        ReservEntry1.SetPointerFilter();
        ReservEntry1.SetTrackingFilterFromReservEntry(ReservEntry1);
        ReservEntry1.SetNewTrackingFilterFromReservEntry(ReservEntry1); //A200F0000.Event.n
        if TrackingSpecification.TrackingExists then begin
            ItemTrackingMgt.SetPointerFilter(TrackingSpecification);
            TrackingSpecification.SetTrackingFilterFromSpec(TrackingSpecification);
            TrackingSpecification.SetNewTrackingFilterFromNewTrackingSpec(TrackingSpecification); //A200F0000.Event.n
            if TrackingSpecification.Find('-') then
                repeat
                    if not TrackingSpecification.Correction then begin
                        ModifyLine := false; //A109F0006.Event.n
                        QtyToInvoiceThisLine :=
                          TrackingSpecification."Quantity Handled (Base)" - TrackingSpecification."Quantity Invoiced (Base)";
                        if Abs(QtyToInvoiceThisLine) > Abs(TotalQtyToInvoice) then
                            QtyToInvoiceThisLine := TotalQtyToInvoice;
                        if TrackingSpecification."Qty. to Invoice (Base)" <> QtyToInvoiceThisLine then begin
                            TrackingSpecification."Qty. to Invoice (Base)" := QtyToInvoiceThisLine;
                            OnSetQtyToHandleAndInvoiceOnBeforeTrackingSpecModify(TrackingSpecification);
                            //TrackingSpecification.Modify(); A109F0006.Event.o
                            ModifyLine := true; //A109F0006.Event.n
                        end;
                        //A109F0006.Event.ns
                        OnAfterSetQtyToHandleAndInvoiceOnBeforeTrackingSpecModify(TrackingSpecification, TotalTrackingSpecification, ModifyLine);
                        if ModifyLine then
                            TrackingSpecification.Modify();
                        //A109F0006.Event.ne
                        TotalQtyToInvoice -= QtyToInvoiceThisLine;
                    end;
                until (TrackingSpecification.Next() = 0);
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetQtyToHandleAndInvoiceOnBeforeTrackingSpecModify(var TrackingSpecification: Record "Tracking Specification"; var TotalTrackingSpecification: Record "Tracking Specification"; var ModifyLine: Boolean)
    begin
        //A109F0006.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
