### ISSUE TITLE
[Function Request] Page 6510 GetFormRunMode

### ISSUE THREAD

**Issue by Bleika** [Microsoft/ALAppExtensions#1347]
The variable FormRunMode is useful for controlling visibility/editability of fields in this page.
Please add an External function to give access to its value:

[External] GetFormRunMode(VAR Mode : ',Reclass,Combined Ship/Rcpt,Drop Shipment')
Mode := FormRunMode;

**Comment by IhorHandziuk** [comment]
Thank you for your request @Bleika , the same issue already exists (#1064)
