### ISSUE TITLE
Useless Code in "PostJobContractLine" in CU 80 "Sales-Post

### ISSUE THREAD

**Issue by DoLLoWFreaK** [microsoft/ALAppExtensions#13475]
I am not really sure, if this is the correct Spot for a suggestion like this. I stumbled upon this today and thought it might be considerable to change:
In the Microsoft_Base Application_18.1.24822.25874.app in the Sales-Post Codeunit (80), i found following Code in the local Procedure "PostJobContractLine"(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line")

        if SalesLine."Job Contract Entry No." = 0 then
            exit;
        if (SalesHeader."Document Type" <> SalesHeader."Document Type"::Invoice) and
           (SalesHeader."Document Type" <> SalesHeader."Document Type"::"Credit Memo")
        then
            SalesLine.TestField("Job Contract Entry No.", 0);

        SalesLine.TestField("Job No.");
        SalesLine.TestField("Job Task No.");

        if SalesHeader."Document Type" = SalesHeader."Document Type"::Invoice then
            SalesLine."Document No." := SalesInvHeader."No.";
        if SalesHeader."Document Type" = SalesHeader."Document Type"::"Credit Memo" then
            SalesLine."Document No." := SalesCrMemoHeader."No.";
        JobContractLine := true;
        JobPostLine.PostInvoiceContractLine(SalesHeader, SalesLine);
    end;

The Testfield on the "Job Contract Entry No." can´t be false, because the Condition directly before prevents SalesLine with "Job Contract Entry No." = 0 to enter this Conditional Statement.
So i would delete the second conditional Statement + useless Testfield on "Job Contract entry No." = 0

The other thing i found quite astonishing, was the assigning of the SalesCrMemoHeader."No."\SalesInvHeader."No." to the regular Sales Line."Document No." . I don´t know the whole process very well, but this is the first time i see something like this instead of just saving the Value in a variable/parameter or directly create a SalesCrMemoLine/SalesInvLine.

I´m looking forward to read your answer.

With kind regards,

Simon , MS-Partner

**Comment by AlexanderYakunin** [comment]
Does this code works incorrect? We are doing extensibility requests here, and technical support team working on bug fixes.

**Comment by DoLLoWFreaK** [comment]
No, as far as i know is this Code working just fine. I honestly just thought about the optimization of saving a line of Code and was curious about the process of saving a Posted Sales Header "No." in an unposted SalesLine. I am sorry for any inconvenience i created if this is the wrong section for suggestions and questions like mine.
