### ISSUE TITLE
[Event Request] Codeunit 392 "Reminder-Make" - function InsertReminderLine

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#13472]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 392 - function InsertReminderLine

    begin
        // DINNL <<
        IsHandled := false;
        OnBeforeInsertReminderLine(ReminderNo, LineType, Description, NextLineNo, IsHandled);
        if IsHandled then
            exit;
        // DINNL >>
        InitReminderLine(ReminderLine, ReminderNo, LineType, Description, NextLineNo);
        ReminderLine.Insert();
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertReminderLine(ReminderNo: Code[20]; LineType: Integer; Description: Text[100]; var NextLineNo: Integer; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
