### ISSUE TITLE
[Event Request] Codeunit 392 "Reminder-Make" - function AddRemiderLinesFromCustLedgEntryWithNoReminderLevelFilter

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#13471]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 392 - function AddRemiderLinesFromCustLedgEntryWithNoReminderLevelFilter

        if (not OverdueEntriesOnly) or
           (CustLedgEntry."Document Type" in [CustLedgEntry."Document Type"::Payment, CustLedgEntry."Document Type"::Refund])
        then begin
            SetReminderLine(LineLevel, ReminderDueDate);
            if (CalcDate(ReminderLevel."Grace Period", ReminderDueDate) >= ReminderHeaderReq."Document Date") and
               (LineLevel = 1)
            then begin
                // DINNL <<
                OnMakeReminderBeforeCheckAmountsNotDueLineInserted(AmountsNotDueLineInserted);
                // DINNL >>
                if not AmountsNotDueLineInserted then begin
                    InsertReminderLine(ReminderHeader."No.", ReminderLine."Line Type"::"Not Due", '', NextLineNo);
                    InsertReminderLine(
                      ReminderHeader."No.", ReminderLine."Line Type"::"Not Due", OpenEntriesNotDueTranslated, NextLineNo);
                    AmountsNotDueLineInserted := true;
                end;

    [IntegrationEvent(false, false)]
    local procedure OnMakeReminderBeforeCheckAmountsNotDueLineInserted(var AmountsNotDueLineInserted: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
