### ISSUE TITLE
[Event Request] Codeunit 392 "Reminder-Make" - function MakeReminder

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#13470]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 392 - function MakeReminder

                if IncludeEntriesOnHold then
                    if CustLedgEntryOnHoldTEMP.FindSet then begin
                        InsertReminderLine(
                          ReminderHeader."No.", ReminderLine."Line Type"::"On Hold", '', NextLineNo);
                        InsertReminderLine(
                          ReminderHeader."No.", ReminderLine."Line Type"::"On Hold", OpenEntriesOnHoldTranslated, NextLineNo);
                        repeat
                            InitReminderLine(
                              ReminderLine, ReminderHeader."No.", ReminderLine."Line Type"::"On Hold", '', NextLineNo);
                            ReminderLine.Type := ReminderLine.Type::"Customer Ledger Entry";
                            ReminderLine.Validate("Entry No.", CustLedgEntryOnHoldTEMP."Entry No.");
                            ReminderLine."No. of Reminders" := 0;
                            OnMakeReminderOnBeforeOnHoldReminderLineInsert(ReminderLine, ReminderHeader, ReminderLevel, CustLedgEntry, CustLedgEntryOnHoldTEMP);
                            ReminderLine.Insert();
                        until CustLedgEntryOnHoldTEMP.Next() = 0;
                    end;

                // DINNL <<
                OnMakeReminderOnBeforeReminderHeaderModify(ReminderHeader, ReminderLine, NextLineNo, MaxReminderLevel);
                // DINNL >>
                ReminderHeader.Modify();

    [IntegrationEvent(false, false)]
    local procedure OnMakeReminderOnBeforeReminderHeaderModify(var ReminderHeader: Record "Reminder Header"; var ReminderLine: Record "Reminder Line"; var NextLineNo: Integer; MaxReminderLevel: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
