### ISSUE TITLE
[Event Request] Codeunit 392 "Reminder-Make" - function InitReminderLine

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#13473]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 392 - function InitReminderLine

    local procedure InitReminderLine(var ReminderLine: Record "Reminder Line"; ReminderNo: Code[20]; LineType: Enum "Reminder Line Type"; Description: Text[100]; var NextLineNo: Integer)
    begin
        NextLineNo := GetLastLineNo(ReminderHeader."No.") + 10000;

        ReminderLine.Init();
        ReminderLine."Reminder No." := ReminderNo;
        ReminderLine."Line No." := NextLineNo;
        ReminderLine."Line Type" := LineType;
        ReminderLine.Description := Description;
        // DINNL <<
        OnAfterInitReminderLine(ReminderHeader, ReminderLine, LineType, Description);
        // DINNL >>
    end;

    [IntegrationEvent(false, false)]
    local procedure DINAfterInitReminderLine(var ReminderHeader: Record "Reminder Header"; var ReminderLine: Record "Reminder Line"; LineType: Integer; Description: Text)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
