### ISSUE TITLE
 [Event Request] table 122 "Purch. Inv. Header" - OnBeforeShowCanceledOrCorrCrMemo

### ISSUE THREAD

**Issue by tvandruten** [microsoft/ALAppExtensions#13480]
Please add "OnBeforeShowCanceledOrCorrCrMemo" to procedcure "ShowCanceledOrCorrCrMemo" in table 122 "Purch. Inv. Header" like:
`IsHandled := false;
        OnBeforeShowCanceledOrCorrCrMemo(Rec, IsHandled);
        if IsHandled then
            exit;`

This event has already been added to table 112 "Sales Invoice Header", please make this consistent

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
