### ISSUE TITLE
Local functions in Codeunit 31000 "Sales-Post Advances"

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#13499]
Plase change local functions to global.

local procedure CalcLinkedPmtAmountToApplyTmp(SalesAdvanceLetterLine: Record "Sales Advance Letter Line"; TotalAmountToApply: Decimal; var TempCustLedgEntry: Record "Cust. Ledger Entry" temporary; var TempCustLedgEntryLink: Record "Cust. Ledger Entry" temporary; var TempAdvanceLink: Record "Advance Link" temporary)
 
local procedure CalcVATToDeduct(SalesAdvanceLetterLine: Record "Sales Advance Letter Line"; var TotalBase: Decimal; var TotalAmount: Decimal; var TotalBaseLCY: Decimal; var TotalAmountLCY: Decimal; CustEntryNo: Integer)
 
local procedure PostPaymentCorrection(SalesInvHeader: Record "Sales Invoice Header"; var TempCustLedgEntry: Record "Cust. Ledger Entry" temporary)

**Comment by Jiribu73** [comment]
It is blocking our business and we need to resolve it as soon as possible.
Thanks
Jiří Bureš
CEO

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
