### ISSUE TITLE
[Event Request] codeunit 5940 ServContractManagement - OnCreateServiceLedgerEntryOnBeforeLoopPeriods

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#13493]
Can you change parameter InvFrom to referance in event OnCreateServiceLedgerEntryOnBeforeLoopPeriods?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
