### ISSUE TITLE
[Event Request] codeunit 5407 Prod. Order Status Management - Function FlushProdOrder

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#13500]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5407 function FlushProdOrder

                    if QtyToPost <> 0 then begin
                        InitItemJnlLineFromProdOrderComp(ItemJnlLine, ProdOrder, ProdOrderLine, ProdOrderComp, PostingDate, QtyToPost);
                        ItemJnlLine."Gen. Prod. Posting Group" := Item."Gen. Prod. Posting Group";
                        // DINNL <<
                        FlushProdOrderOnBeforeCopyItemTracking(ItemJnlLine, ProdOrderComp, Item);
                        // DINNL >>
                        if Item."Item Tracking Code" <> '' then
                            ItemTrackingMgt.CopyItemTracking(RowID1, ItemJnlLine.RowID1, false);
                        PostFlushItemJnlLine(ItemJnlLine);
                        OnFlushProdOrderOnAfterPostFlushItemJnlLine(ItemJnlLine);
                    end;

    
    [IntegrationEvent(false, false)]
    local procedure FlushProdOrderOnBeforeCopyItemTracking(ItemJournalLine: Record "Item Journal Line"; ProdOrderComponent: Record "Prod. Order Component"; Item: Record Item)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
