### ISSUE TITLE
[Event Request] codeunit 5940 ServContractManagement - OnAfterCreateAllServLines

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#13502]
Can you add event OnAfterCreateAllServLines in procedure CreateAllServLines?

```
            Validate("Last Invoice Date", "Next Invoice Date");
            "Print Increase Text" := false;
            Modify;
        end;

        OnAfterCreateAllServLines(ServContractToInvoice, ServContractLine);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCreateAllServLines(ServiceContractHeader: Record "Service Contract Header"; var ServContractLine: Record "Service Contract Line")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
