### ISSUE TITLE
[Event Request] codeunit 5407 Prod. Order Status Management - Function OnRun

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#13501]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5407 function OnRun

        ChangeStatusForm.Set(Rec);
        if ChangeStatusForm.RunModal = ACTION::Yes then begin
            OnRunOnAfterChangeStatusFormRun(Rec);
            ChangeStatusForm.ReturnPostingInfo(NewStatus, NewPostingDate, NewUpdateUnitCost);
            // DINNL <<
	        IsHandled := false;
            OnRunOnBeforeChangeStatusOnProdOrder(Rec, NewStatus, NewPostingDate, NewUpdateUnitCost, IsHandled);
            if IsHandled then
                exit;
            // DINNL >>
            ChangeProdOrderStatus(Rec, NewStatus, NewPostingDate, NewUpdateUnitCost);
            Commit();
            ShowStatusMessage(Rec);

    [IntegrationEvent(false, false)]
    local procedure OnRunOnBeforeChangeProdOrderStatus(ProductionOrder: Record "Production Order"; NewStatus: Enum "Production Order Status"; NewPostingDate: Date; NewUpdateUnitCost: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
