### ISSUE TITLE
[Event Request] codeunit 5407 Prod. Order Status Management - Add parameter to Function ChangeProdOrderStatus

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#13505]
Dear ALAppExtensions Team,

Is it possible to add parameter "BlockCommit" to function ChangeProdOrderStatus in codeunit 5407 ?

        end else begin
            TransProdOrder(ProdOrder);
            FlushProdOrder(ProdOrder, NewStatus, NewPostingDate);
            WhseProdRelease.Release(ProdOrder);
        end;
        OnAfterChangeStatusOnProdOrder(ProdOrder, ToProdOrder, NewStatus, NewPostingDate, NewUpdateUnitCost, BlockCommit);
        // DINNL <<
        if not BlockCommit then
        // DINNL >>
        Commit();

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
