### ISSUE TITLE
[Request for External] table 5902 "Service Line" - GetLineNo

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#13504]
Can you remove scrope OnPrem from procedure GetLineNo in service line table?

I want to set additional fields on service line in procedure InsertDescriptionServiceLine in codeunit 5940 ServContractManagement.

Another alternative is to add event OnInsertDescriptionServiceLineOnBeforeServiceLineInsert to be able to set the fields before the line is inserted.

**Comment by AlexanderYakunin** [comment]
Can you use procedure GetNextLineNo(ServiceLineSource: Record "Service Line"; BelowxRec: Boolean): Integer instead?

**Comment by auzhhv** [comment]
Hi Alexander,

It is certainly possible, but I think it is a bit risky considering future changes.
I want to run the same code, but add values to fields.
Can I rather get the OnInsertDescriptionServiceLineOnBeforeServiceLineInsert event with ServiceLine as reference?

```
    local procedure InsertDescriptionServiceLine(Description: Text[100])
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeInsertDescriptionServiceLine(ServLine, Description, IsHandled);
        if IsHandled then
            exit;

        ServLine.Init();
        ServLine."Line No." := ServLine.GetLineNo();
        ServLine.Description := Description;
        // >>>>>>>>
        OnInsertDescriptionServiceLineOnBeforeServiceLineInsert(ServiceLine);
        // <<<<<<<<
        ServLine.Insert();
    end;
```

**Comment by AlexanderYakunin** [comment]
Yes, we better add this event.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
