### ISSUE TITLE
Remove Scope from procedure Credit Limit in Bank Account table 

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13518]
Hello, 

Is it possible to remove the scope on the following function:    

    // [Scope('OnPrem')]  
    procedure "Credit limit"(): Decimal
    begin
        CalcFields(Balance, Proposal, "Payment History");
        exit(Balance - "Min. Balance" - Proposal - "Payment History");
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
