### ISSUE TITLE
[Event request] Codeunit 90 "Purch.-Post" - OnBeforeCheckPostRestrictions

### ISSUE THREAD

**Issue by VeronicaGoglia** [microsoft/ALAppExtensions#13519]
Hi AL-Team,
can you please add new events in the method CheckAndUpdate

if Invoice then
                if WithhSocSec.Get("Document Type", "No.") and
                   (WithhSocSec."Withholding Tax Code" <> '') and
                   (WithhSocSec."Total Amount" = 0) and
                   ("Document Type" = "Document Type"::Invoice)
                then
                    Error(Text1130006,
                      WithhSocSec.FieldCaption("Total Amount"), WithhSocSec.FieldCaption("Withholding Tax Code"));
//New Event
OnBeforeCheckPostRestrictions(WithhSocSec,Invoice,PurchHeader);
//New Event

CheckPostRestrictions(PurchHeader);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
