### ISSUE TITLE
[Event request] Table 11401 CBG Statement Line OnBeforeCreateGenJournalLine

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13521]
Hello, is it possible to add the following to the CBG statement line table (Dutch localisation)

    procedure CreateGenJournalLine(var GenJnlLine: Record "Gen. Journal Line")
    var
        CBGStatement: Record "CBG Statement";
        **SuspendTestAccountNo: Boolean;   // New Variable**
    begin
        **// DINNL <<
        OnBeforeCreateGenJournalLine(SuspendTestAccountNo);
        if not SuspendTestAccountNo then
            // DINNL >>**
        TestField("Account No.");
        GenJnlLine.Init();
        GenJnlLine."Journal Template Name" := "Journal Template Name";
        GenJnlLine."Journal Batch Name" := Text1000016;// STRSUBSTNO('%1',"No.");
        GenJnlLine."Line No." := 0;

        GenJnlLine.Validate("Posting Date", Date);
        case "Account Type" of
            "Account Type"::"G/L Account":

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
