### ISSUE TITLE
[Event Request] page 401 "Purch. Credit Memo Statistics" - OnCalculateTotalsOnAfterAddLineTotals

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13527]
We would like to add a parameter to the existing event OnCalculateTotalsOnAfterAddLineTotals in the following procedure:

    local procedure CalculateTotals()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalculateTotals(
            Rec, VendAmount, AmountInclVAT, InvDiscAmount,
            LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels, IsHandled);
        if IsHandled then
            exit;

        PurchCrMemoLine.SetRange("Document No.", "No.");
        if PurchCrMemoLine.Find('-') then
            repeat
                VendAmount += PurchCrMemoLine.Amount;
                AmountInclVAT += PurchCrMemoLine."Amount Including VAT";
                if "Prices Including VAT" then
                    InvDiscAmount += PurchCrMemoLine."Inv. Discount Amount" / (1 + PurchCrMemoLine."VAT %" / 100)
                else
                    InvDiscAmount += PurchCrMemoLine."Inv. Discount Amount";
                LineQty += PurchCrMemoLine.Quantity;
                TotalNetWeight += PurchCrMemoLine.Quantity * PurchCrMemoLine."Net Weight";
                TotalGrossWeight += PurchCrMemoLine.Quantity * PurchCrMemoLine."Gross Weight";
                TotalVolume += PurchCrMemoLine.Quantity * PurchCrMemoLine."Unit Volume";
                if PurchCrMemoLine."Units per Parcel" > 0 then
                    TotalParcels += Round(PurchCrMemoLine.Quantity / PurchCrMemoLine."Units per Parcel", 1, '>');
                if PurchCrMemoLine."VAT %" <> VATPercentage then
                    if VATPercentage = 0 then
                        VATPercentage := PurchCrMemoLine."VAT %"
                    else
                        VATPercentage := -1;

                OnCalculateTotalsOnAfterAddLineTotals(
                    Rec, //A108F0039.Event
                    PurchCrMemoLine, VendAmount, AmountInclVAT, InvDiscAmount,
                    LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels, VATPercentage)
            until PurchCrMemoLine.Next() = 0;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnCalculateTotalsOnAfterAddLineTotals(PurchCrMemoHeader: Record "Purch. Cr. Memo Hdr."; var PurchCrMemoLine: Record "Purch. Cr. Memo Line"; var VendAmount: Decimal; var AmountInclVAT: Decimal; var InvDiscAmount: Decimal; var LineQty: Decimal; var TotalNetWeight: Decimal; var TotalGrossWeight: Decimal; var TotalVolume: Decimal; var TotalParcels: Decimal; var VATPercentage: Decimal)
    begin
        //A108F0039.Event Parameter PurchCrMemoHeader
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
