### ISSUE TITLE
[Event request] Codeunit 12101 "Withholding - Contribution" - OnBeforeComputedWithholdingTaxModify

### ISSUE THREAD

**Issue by VeronicaGoglia** [microsoft/ALAppExtensions#13520]
Hi AL-Team,
can you please add new events in the method PostPayments

ComputedWithholdingTax."Related Date" := "Related Date";
ComputedWithholdingTax."Payment Date" := "Payment Date";

//New Event
OnBeforeComputedWithholdingTaxModify(TempWithholdingSocSec,ComputedWithholdingTax);
//New Event

ComputedWithholdingTax.Modify();

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.

**Comment by VeronicaGoglia** [comment]
The event to insert in method PostPayments is: 
OnBeforeComputedWithholdingTaxModify(var TempWithholdingSocSec: Record "Tmp Withholding Contribution",
var ComputedWithholdingTax: Record "Computed Withholding Tax";);


ComputedWithholdingTax."Withholding Tax Code" := "Withholding Tax Code";
ComputedWithholdingTax."Related Date" := "Related Date";
ComputedWithholdingTax."Payment Date" := "Payment Date";

//New Event to add here
OnBeforeComputedWithholdingTaxModify(var TempWithholdingSocSec: Record "Tmp Withholding Contribution",
var ComputedWithholdingTax: Record "Computed Withholding Tax";);
//New Event

ComputedWithholdingTax.Modify();

**Comment by Oleg-Romashkov** [comment]
I meant the signature like this:
```

    [IntegrationEvent(false, false)]
    local procedure OnPostPaymentsOnBeforeComputedWithholdingTaxModify(var TempWithholdingSocSec: Record "Tmp Withholding Contribution"; var ComputedWithholdingTax: Record "Computed Withholding Tax")
    begin
    end;

```
That helps us implementing the requests faster and avoiding possible issues with "var" parameters.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
