### ISSUE TITLE
[Event Request] Table 5965 Service Contract Heder event OnValidateNextInvoiceDateOnBeforeCheck

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#13522]
ServiceContractHeader variable should be passed as **VAR**

before    
[IntegrationEvent(false, false)]
    local procedure OnValidateNextInvoiceDateOnBeforeCheck(ServiceContractHeader: Record "Service Contract Header"; var IsHandled: Boolean)
    begin
    end;

after
[IntegrationEvent(false, false)]
    local procedure OnValidateNextInvoiceDateOnBeforeCheck(**var** ServiceContractHeader: Record "Service Contract Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
