### ISSUE TITLE
[Event Request] report 699 Calculate Plan - Req. Wksh.	OnAfterItemOnAfterGetRecord

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13534]
Hello, 

Is het possible to get the following event:

                  RespectPlanningParm);

                if PlanningAssignment.Find('-') then
                    repeat
                        if PlanningAssignment."Latest Date" <= ToDate then begin
                            PlanningAssignment.Inactive := true;
                            PlanningAssignment.Modify();
                        end;
                    until PlanningAssignment.Next() = 0;
                **// DINNL <<
                OnAfterItemOnAfterGetRecord(ReqLine, Item, CurrTemplateName, CurrWorksheetName, FromDate);
                // DINNL >>**

                Commit();

    **[IntegrationEvent(false, false)]
    local procedure OnAfterItemOnAfterGetRecord(var ReqLine: Record "Requisition Line"; Item: Record Item; CurrTemplateName: Code[10]; CurrWorksheetName: Code[10]; FromDate: Date)
    begin
    end;**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
