### ISSUE TITLE
[Event Request] page 396 "Sales Shipment Statistics" - OnCalculateTotalsOnAfterAddLineTotals

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13533]
We would like to add a parameter to the existing event OnCalculateTotalsOnAfterAddLineTotals in the following procedure:

    local procedure CalculateTotals()
    var
        SalesShptLine: Record "Sales Shipment Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalculateTotals(Rec, LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels, IsHandled);
        if IsHandled then
            exit;

        SalesShptLine.SetRange("Document No.", "No.");
        if SalesShptLine.Find('-') then
            repeat
                LineQty += SalesShptLine.Quantity;
                TotalNetWeight += SalesShptLine.Quantity * SalesShptLine."Net Weight";
                TotalGrossWeight += SalesShptLine.Quantity * SalesShptLine."Gross Weight";
                TotalVolume += SalesShptLine.Quantity * SalesShptLine."Unit Volume";
                if SalesShptLine."Units per Parcel" > 0 then
                    TotalParcels += Round(SalesShptLine.Quantity / SalesShptLine."Units per Parcel", 1, '>');
                OnCalculateTotalsOnAfterAddLineTotals(
                    Rec, //A108F0039.Event
                    SalesShptLine, LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels)
            until SalesShptLine.Next() = 0;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnCalculateTotalsOnAfterAddLineTotals(SalesShipmentHeader: Record "Sales Shipment Header"; var SalesShipmentLine: Record "Sales Shipment Line"; var LineQty: Decimal; var TotalNetWeight: Decimal; var TotalGrossWeight: Decimal; var TotalVolume: Decimal; var TotalParcels: Decimal)
    begin
        //A108F0039.Event Parameter SalesShipmentHeader
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
