### ISSUE TITLE
[Event Request] 5965 Table Service Contract Header new event OnBeforeValidateLastInvoiceDate with IsHandeld param

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#13535]
**BEFORE**
field(33; "Last Invoice Date"; Date)
        {
            Caption = 'Last Invoice Date';
            Editable = false;

            trigger OnValidate()
            begin
                TestField("Starting Date");
....

**AFTER**
field(33; "Last Invoice Date"; Date)
        {
            Caption = 'Last Invoice Date';
            Editable = false;

            trigger OnValidate()
            var
                  IsHandled: Boolean;
            begin
                  IsHandled := false;
                  OnBeforeValidateLastInvoiceDate(Rec, IsHandled);
                  if IsHandled then
                      exit;
                TestField("Starting Date");

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateLastInvoiceDate(var ServiceContractHeader: Record "Service Contract Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
