### ISSUE TITLE
[Event Request] page 42 "Sales Order" - OnBeforeShowReleaseNotification

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13532]
We would like to add a new event OnBeforeShowReleaseNotification in the following procedure:

    local procedure ShowReleaseNotification(): Boolean
    var
        LocationsQuery: Query "Locations from items Sales";
        IsHandled: Boolean;
        Result: Boolean;
    begin
        //A109F0006.Event.ns
        OnBeforeShowReleaseNotification(Rec, Result, IsHandled);
        if IsHandled then
            exit(Result);
        //A109F0006.Event.ne
        if TestStatusIsNotReleased then begin
            LocationsQuery.SetRange(Document_No, "No.");
            LocationsQuery.SetRange(Require_Pick, true);
            LocationsQuery.Open;
            if LocationsQuery.Read then
                exit(true);
            LocationsQuery.SetRange(Require_Pick);
            LocationsQuery.SetRange(Require_Shipment, true);
            LocationsQuery.Open;
            exit(LocationsQuery.Read);
        end;
        exit(false);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowReleaseNotification(SalesHeader: Record "Sales Header"; var Result: Boolean; var IsHandled: Boolean)
    begin
        //A109F0006.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
