### ISSUE TITLE
[Event Request] Please do not obsolete OnBeforeGetTrackingInternetAddr event on Sales Shipment Header

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#13547]
There is currently an OnBeforeGetTrackingInternetAddr event on the "Sales Shipment Header" table but this is being obsoleted with the following reason: Moved to table 291 Shipping Agent OnBeforeGetTrackingInternetAddr

However this will cause a problem in my current extension because I use this event to get a tracking address from another field that has been added to the "Sales Shipment Header" table.  Unfortunately there's no way for me to access this new field on the "Sales Shipment Header" from the new OnBeforeGetTrackingInternetAddr event on the "Shipping Agent" table.

Can you please not obsolete the OnBeforeGetTrackingInternetAddr event in table 110 "Sales Shipment Header"

**Comment by Oleg-Romashkov** [comment]
No, we cannot get it back. What about making OnBeforeStartTrackingSite handled?

Something like this:
```

    procedure StartTrackingSite()
    var
        IsHandled: Boolean;
    begin
        OnBeforeStartTrackingSite(Rec, IsHandled);
        if IsHandled then
            exit;

        HyperLink(GetTrackingInternetAddr());
    end;

```

**Comment by kmistrytnp** [comment]
Yes, that would also work.  Please could make the suggested change. Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
