### ISSUE TITLE
[Event Request] page 5757 "Transfer Receipt Statistics" - OnCalculateTotalsOnAfterAddLineTotals

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13545]
We would like to add a parameter to the existing event OnCalculateTotalsOnAfterAddLineTotals in the following procedure: 

    local procedure CalculateTotals()
    var
        TransRcptLine: Record "Transfer Receipt Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalculateTotals(Rec, LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels, IsHandled);
        if IsHandled then
            exit;

        TransRcptLine.SetRange("Document No.", "No.");
        if TransRcptLine.Find('-') then
            repeat
                LineQty += TransRcptLine.Quantity;
                TotalNetWeight += TransRcptLine.Quantity * TransRcptLine."Net Weight";
                TotalGrossWeight += TransRcptLine.Quantity * TransRcptLine."Gross Weight";
                TotalVolume += TransRcptLine.Quantity * TransRcptLine."Unit Volume";
                if TransRcptLine."Units per Parcel" > 0 then
                    TotalParcels += Round(TransRcptLine.Quantity / TransRcptLine."Units per Parcel", 1, '>');
                OnCalculateTotalsOnAfterAddLineTotals(
                    Rec, //A108F0039.Event
                    TransRcptLine, LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels)
            until TransRcptLine.Next() = 0;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnCalculateTotalsOnAfterAddLineTotals(TransferReceiptHeader: Record "Transfer Receipt Header"; var TransferReceiptLine: Record "Transfer Receipt Line"; var LineQty: Decimal; var TotalNetWeight: Decimal; var TotalGrossWeight: Decimal; var TotalVolume: Decimal; var TotalParcels: Decimal)
    begin
        //A108F0039.Event Parameter TransferReceiptHeader
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
