### ISSUE TITLE
[Event Request] page 6032 "Service Shipment Statistics" - OnBeforeCalculateTotals

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13543]
We would like to add a new event OnBeforeCalculateTotals in the following trigger:

    trigger OnAfterGetRecord()
    var
        IsHandled: Boolean;
    begin
        ClearAll;
        //A108F0080.Event.ns
        IsHandled := false;
        OnBeforeCalculateTotals(Rec, LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels, IsHandled);
        if IsHandled then
            exit;
        //A108F0080.Event.ne

        ServShptLine.SetRange("Document No.", "No.");

        if ServShptLine.Find('-') then
            repeat
                LineQty := LineQty + ServShptLine.Quantity;
                TotalNetWeight := TotalNetWeight + (ServShptLine.Quantity * ServShptLine."Net Weight");
                TotalGrossWeight := TotalGrossWeight + (ServShptLine.Quantity * ServShptLine."Gross Weight");
                TotalVolume := TotalVolume + (ServShptLine.Quantity * ServShptLine."Unit Volume");
                if ServShptLine."Units per Parcel" > 0 then
                    TotalParcels := TotalParcels + Round(ServShptLine.Quantity / ServShptLine."Units per Parcel", 1, '>');
                OnCalculateTotalsOnAfterAddLineTotals(Rec, ServShptLine, LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels); //A108F0080.Event
            until ServShptLine.Next() = 0;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculateTotals(ServiceShipmentHeader: Record "Service Shipment Header"; var LineQty: Decimal; var TotalNetWeight: Decimal; var TotalGrossWeight: Decimal; var TotalVolume: Decimal; var TotalParcels: Decimal; var IsHandled: Boolean)
    begin
        //A108F0080.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
