### ISSUE TITLE
[Event Request] page 5755 "Transfer Statistics" - OnCalculateTotalsOnAfterAddLineTotals 

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13548]
We would like to add a parameter to the existing event OnCalculateTotalsOnAfterAddLineTotals in the following procedure:

    local procedure CalculateTotals()
    var
        TransLine: Record "Transfer Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalculateTotals(Rec, LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels, IsHandled);
        if IsHandled then
            exit;

        TransLine.SetRange("Document No.", "No.");
        TransLine.SetRange("Derived From Line No.", 0);
        if TransLine.Find('-') then
            repeat
                LineQty += TransLine.Quantity;
                TotalNetWeight += TransLine.Quantity * TransLine."Net Weight";
                TotalGrossWeight += TransLine.Quantity * TransLine."Gross Weight";
                TotalVolume += TransLine.Quantity * TransLine."Unit Volume";
                if TransLine."Units per Parcel" > 0 then
                    TotalParcels += Round(TransLine.Quantity / TransLine."Units per Parcel", 1, '>');

                OnCalculateTotalsOnAfterAddLineTotals(
                    Rec, //A108F0039.Event
                    TransLine, LineQty, TotalNetWeight, TotalGrossWeight, TotalVolume, TotalParcels)
            until TransLine.Next() = 0;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnCalculateTotalsOnAfterAddLineTotals(TransferHeader: Record "Transfer Header"; var TransferLine: Record "Transfer Line"; var LineQty: Decimal; var TotalNetWeight: Decimal; var TotalGrossWeight: Decimal; var TotalVolume: Decimal; var TotalParcels: Decimal)
    begin
        //A108F0039.Event Parameter TransferHeader
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
