### ISSUE TITLE
[Event Request] Table 81 "Gen. Journal Line"- OnValidateAmountOnAfterValidateAmount

### ISSUE THREAD

**Issue by kwettermann** [microsoft/ALAppExtensions#13542]
Please add a new integration event **OnValidateAmountOnAfterValidateAmount** in **Table 81**.

```
local procedure ValidateAmount(ShouldCheckPaymentTolerance: Boolean)
begin
	[...]

	if JobTaskIsSet then begin
		CreateTempJobJnlLine();
		UpdatePricesFromJobJnlLine();
	end;
	
+	OnValidateAmountOnAfterValidateAmount(Rec);

end;
```

New integration event
```
[IntegrationEvent(false, false)]
local procedure OnValidateAmountOnAfterValidateAmount(var GenJournalLine: Record "Gen. Journal Line")
begin
end;
```

**Comment by kwettermann** [comment]
*bump*

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
