### ISSUE TITLE
[Event Request] page 6550 "Whse. Item Tracking Lines" - OnAfterUpdateUndefinedQty

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13549]
We would like to add a new event OnAfterUpdateUndefinedQty in the following procedure:

    local procedure UpdateUndefinedQty() QtyIsValid: Boolean
    begin
        QtyIsValid := ItemTrackingMgt.UpdateUndefinedQty(TotalWhseItemTrackingLine, SourceQuantityArray, UndefinedQtyArray);
        UpdateColorOfQty();
        OnAfterUpdateUndefinedQty(Rec, TotalWhseItemTrackingLine, QtyIsValid); //A200F000.Event
    end;

    local procedure UpdateColorOfQty()
    begin
        ColorOfQuantityArray[1] := GetQtyColor(SourceQuantityArray[1], TotalWhseItemTrackingLine."Quantity (Base)");
        ColorOfQuantityArray[2] := GetQtyColor(SourceQuantityArray[2], TotalWhseItemTrackingLine."Qty. to Handle (Base)");
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateUndefinedQty(var WhseItemTrackingLine: Record "Whse. Item Tracking Line"; var TotalWhseItemTrackingLine: Record "Whse. Item Tracking Line"; var QtyIsValid: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
