### ISSUE TITLE
[Event Request] Include sender in OnAfterCopyDimValueToBufPage on page 9223 "Item Statistics Matrix"

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13554]
Dear ALAppExtensions Team,

Is it possible to include the sender in OnAfterCopyDimValueToBufPage on page 9223 "Item Statistics Matrix"?

-[IntegrationEvent(false, false)]
    local procedure OnAfterCopyDimValueToBuf(var ItemBuffer: Record "Item Statistics Buffer"; var TheDimValue: Record "Integer"; 
          var TheDimCodeBuf: Record "Dimension Code Buffer");
     begin
     end;

+[IntegrationEvent(true, false)]
    local procedure OnAfterCopyDimValueToBuf(var ItemBuffer: Record "Item Statistics Buffer"; var TheDimValue: Record "Integer"; 
         var TheDimCodeBuf: Record "Dimension Code Buffer");
     begin
     end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
