### ISSUE TITLE
[Event Request] page 6550 "Whse. Item Tracking Lines" - OnAfterOnClosePage

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13550]
We would like to add a new event OnAfterOnClosePage in the following trigger:

    trigger OnAfterGetCurrRecord()
    begin
        UpdateExpDateEditable();
        CalculateSums();
    end;

    trigger OnAfterGetRecord()
    begin
        ExpirationDateOnFormat();
    end;

    trigger OnClosePage()
    begin
        if FormUpdated then
            if not UpdateUndefinedQty then
                RestoreInitialTrkgLine()
            else
                if not CopyToReservEntry then
                    RestoreInitialTrkgLine();
        OnAfterOnClosePage(Rec, WhseWorksheetLine, FormSourceType, FormUpdated); //A200F0000.Event
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterOnClosePage(var WhseItemTrackingLine: Record "Whse. Item Tracking Line"; var WhseWorksheetLine: Record "Whse. Worksheet Line"; FormSourceType: Integer; FormUpdated: Boolean)
    begin
        //A200F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
