### ISSUE TITLE
[Event Request] report 99001017 "Calculate Plan - Plan. Wksh." - OnBeforeItemOnPreDataItem

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13552]
We would like to add a new event OnBeforeItemOnPreDataItem in the following trigger:

            trigger OnPreDataItem()
            begin
                OnBeforeItemOnPreDataItem(Item); //A108F0061.Event

                OpenWindow;
                Clear(CalcItemPlan);
                CalcItemPlan.SetTemplAndWorksheet(CurrTemplateName, CurrWorksheetName, NetChange);
                CalcItemPlan.SetParm(UseForecast, ExcludeForecastBefore, Item);
                CalcItemPlan.Initialize(FromDate, ToDate, MPS, MRP, RespectPlanningParm);

                SetAtStartPosition := true;

                ReqLine.SetRange("Worksheet Template Name", CurrTemplateName);
                ReqLine.SetRange("Journal Batch Name", CurrWorksheetName);
                PlanningErrorLog.SetRange("Worksheet Template Name", CurrTemplateName);
                PlanningErrorLog.SetRange("Journal Batch Name", CurrWorksheetName);
                if PlanningErrorLog.FindFirst and ReqLine.FindFirst then
                    SetAtStartPosition := not Confirm(Text009);

                ClearPlanningErrorLog();
                ClearLastError;

                OnAfterItemOnPreDataItem(Item);
                Commit();
            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeItemOnPreDataItem(var Item: Record Item)
    begin
        //A108F0061.Event        
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
