### ISSUE TITLE
[Event Modification Request] Transfer Line table procedure FilterLinesWithItemToPlan

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#13555]
Please change from
OnAfterFilterLinesWithItemToPlan(Item, IsReceipt, IsSupplyForPlanning);

to 
OnAfterFilterLinesWithItemToPlan(Rec,  Item, IsReceipt, IsSupplyForPlanning);

where 
[IntegrationEvent(true, false)]
    local procedure OnAfterFilterLinesWithItemToPlan(var Item: Record Item; IsReceipt: Boolean; IsSupplyForPlanning: Boolean)
    begin
    end;

becomes

[IntegrationEvent(true, false)]
    local procedure OnAfterFilterLinesWithItemToPlan(var TransferLine: Record "Transfer Line"; var Item: Record Item; IsReceipt: Boolean; IsSupplyForPlanning: Boolean)
    begin
    end;

Thanks very much!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
