### ISSUE TITLE
[Event Request] report 99001017 "Calculate Plan - Plan. Wksh." - OnBeforeOnPreReport

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13553]
We would like to add a new event OnBeforeOnPreReport and a new trigger:

    trigger OnPreReport()
    var
        RunCalculation: Boolean;
    begin
        //A108F0061.Event.ns
        RunCalculation := true;
        OnBeforeOnPreReport(RunCalculation);
        if not RunCalculation then
            CurrReport.Quit();
        //A108F0061.Event.ne
    end;

Event Signature:

    [IntegrationEvent(true, false)]
    local procedure OnBeforeOnPreReport(var RunCalculation: Boolean)
    begin
        //A108F0061.Event
    end;

**Comment by Oleg-Romashkov** [comment]
Not clear how do you want to use this event: when to run it or not? 

Does it make sense to add handled OnBeforeAction events for "Planning Worksheet" page where this report is called by?

**Comment by AlexanderYakunin** [comment]
We cannot implement this.
