### ISSUE TITLE
[Event Request] report 5899 "Calculate Inventory Value" - OnAfterInitItemJnlLine

### ISSUE THREAD

**Issue by Duizy05** [microsoft/ALAppExtensions#13551]
We would like to add a new event OnAfterInitItemJnlLine in the following procedure:

    local procedure InitItemJnlLine(var ItemJnlLine: Record "Item Journal Line"; EntryType2: Enum "Item Ledger Entry Type"; ItemNo2: Code[20]; VariantCode2: Code[10]; LocationCode2: Code[10])
    begin
        with ItemJnlLine do begin
            if NextLineNo = 0 then begin
                LockTable();
                SetRange("Journal Template Name", "Journal Template Name");
                SetRange("Journal Batch Name", "Journal Batch Name");
                if FindLast then
                    NextLineNo := "Line No.";
            end;

            NextLineNo := NextLineNo + 10000;
            Init;
            "Line No." := NextLineNo;
            "Value Entry Type" := "Value Entry Type"::Revaluation;

            OnInitItemJnlLineOnBeforeValidateFields(ItemJnlLine);

            Validate("Posting Date", PostingDate);
            Validate("Entry Type", EntryType2);
            Validate("Document No.", NextDocNo);
            Validate("Item No.", ItemNo2);
            "Reason Code" := ItemJnlBatch."Reason Code";
            "Variant Code" := VariantCode2;
            "Location Code" := LocationCode2;
            "Source Code" := SourceCodeSetup."Revaluation Journal";
        end;

        //OnAfterInitItemJnlLine(ItemJnlLine); //A108F0009.o
        OnAfterInitItemJnlLine(ItemJnlLine, ItemJnlBatch); //A108F0009.Event.n
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterInitItemJnlLine(var ItemJournalLine: Record "Item Journal Line"; ItemJnlBatch: Record "Item Journal Batch")
    begin
        //A108F0009.Event Parameter ItemJnlBatch
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
