### ISSUE TITLE
[Event Request] Purchase Line table

### ISSUE THREAD

**Issue by TaaviSa** [microsoft/ALAppExtensions#13558]
Please add the ‘OnValidateQuantityOnAfterCalcBaseQty’ IntegrationEvent to Purchase Line table exactly the same way as it is currently in Sales Line table:
 
table 37 "Sales Line" 
        field(15; Quantity; Decimal)
                ..
                "Quantity (Base)" :=
                    UOMMgt.CalcBaseQty("No.", "Variant Code", "Unit of Measure Code", Quantity, "Qty. per Unit of Measure");
 
                OnValidateQuantityOnAfterCalcBaseQty(Rec, xRec);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
