### ISSUE TITLE
Effective Permissions not always affected by adding Permission Set to a User

### ISSUE THREAD

**Issue by marekjz** [microsoft/ALAppExtensions#13557]
This seems to be quite a "random" issue, but it has happened several times in our environment. Scenario: adding a new entry under User Permission Sets (for example: SUPER) on User Card, saving changes, click on "Effective Permissions" shows nothing (at least related to the just specified Permission Set). The issue stays permanent - after reopening User Card, even after a while... There is still no Effective Permissions there.

Bug observed in: Version: NO Business Central **18.0** (Platform 18.0.22893.23773 + Application 18.0.23013.23795)
Worked Ok in (as long as I tested): Version: NO Business Central **16.1** (Platform 16.0.12630.12758 + Application 16.1.12805.0)

**Comment by AlexanderYakunin** [comment]
Hello marekjz! Thank you for your information, but our team has no resources to repro or fix this kind of issues. We are working on adding integration events and doing other extensibility changes for our application. We have CSS team (=technical support) with resources to work with you on such requests, please create hotfix requests and it will be processed by CSS.
