### ISSUE TITLE
Permission Request on Codeunit 703 "Find Record Management"

### ISSUE THREAD

**Issue by rjoehl** [microsoft/ALAppExtensions#13561]
We would like to add indirect read permission for the Record 17 "G/L Entry" on the codeunit 703 "Find Record Management", thank you

**Comment by AlexanderYakunin** [comment]
Please explain why do you need this here?

**Comment by rjoehl** [comment]
We would like to limit User Permission for the "G/L Entries" to indirect read only while still being able to access other Process Features

**Comment by AlexanderYakunin** [comment]
How this is related to codeunit 703 Find Record Management? "G/L Entry" table is not used here at all.

**Comment by rjoehl** [comment]
You are correct. What I meant was indirect read permission for the tabledata of "G/L Entry", sorry for the confusion.

**Comment by AlexanderYakunin** [comment]
Indirect permission will not help you for that, it only allows access from code to particular table. So if we add indirect permissions for G/L Entry inside of G/L Entry table, it will only help code in this object read this table. If you want to limit access to G/L entry table for users, you need to change their permission sets.
