### ISSUE TITLE
[Event Request] OnRunPostGenJnlLineBufferBeforeLockTable Codeunit 5704 "TransferOrder-Post Shipment"

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13560]
Hello, 

Is it possible to add the following Event ?   

                 TransLine.UpdateWithWarehouseShipReceive;
                    TransLine.Modify();
                    OnAfterTransLineModify(TransLine);
                until TransLine.Next() = 0;
            end;

            **// DINNL <<
            OnRunPostGenJnlLineBufferBeforeLockTable (ItemJnlPostLine);
            // DINNL >>**
            if WhseShip then
                WhseShptLine.LockTable();
            LockTable();
            if WhseShip then begin
                WhsePostShpt.PostUpdateWhseDocuments(WhseShptHeader);
                TempWhseShptHeader.Delete();

    **[IntegrationEvent(false, false)]
    local procedure OnRunPostGenJnlLineBufferBeforeLockTable(var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line")
    begin
    end;**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
