### ISSUE TITLE
[Request for external] codeunit "Approvals Mgmt." - functions CreateApprovalRequestForChainOfApprovers and CreateApprovalRequestForApproverWithSufficientLimit

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#13564]
Please make these two functions available for external in codeunit "Approvals Mgmt.":

- CreateApprovalRequestForChainOfApprovers
- CreateApprovalRequestForApproverWithSufficientLimit

The reason is that we have several event subscribers to events in this codeunit and we need to to create new approval requests by calling standard methods.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
