### ISSUE TITLE
Codeunit 426 'Payment Tolerance Management' - suppress COMMIT 

### ISSUE THREAD

**Issue by rgrygoryshchak** [microsoft/ALAppExtensions#1356]
Suppress COMMIT functionality is needed in codeunit 426 'Payment Tolerance Management'.

Could be implemented similar to codeunit 80 :

[External] SetSuppressCommit(NewSuppressCommit : Boolean)
SuppressCommit := NewSuppressCommit;

Regards, Roman.

**Comment by AlexanderYakunin** [comment]
Already done:

SetSuppressCommit(NewSuppressCommit : Boolean)
SuppressCommit := NewSuppressCommit;

**Comment by rgrygoryshchak** [comment]
Sorry, what version this has been done?

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
