### ISSUE TITLE
[Event Request Modification] codeunit 7301 "Whse. Jnl.-Register Line" OnInitWhseEntryCopyFromWhseJnlLine

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13565]
Hello, 

Can you please do the following modification to an Existing Event. 

Please add the variables Location ,BinCode and Ishandled

            if (WhseJnlLine."New Expiration Date" <> WhseJnlLine."Expiration Date") and (WhseEntry."Entry Type" = WhseEntry."Entry Type"::Movement) then
                WhseEntry."Expiration Date" := WhseJnlLine."New Expiration Date";
        end;
        WhseEntry."Warranty Date" := WhseJnlLine."Warranty Date";
        WhseEntry."Phys Invt Counting Period Code" := WhseJnlLine."Phys Invt Counting Period Code";
        WhseEntry."Phys Invt Counting Period Type" := WhseJnlLine."Phys Invt Counting Period Type";

        // DINNL <<
        **OnInitWhseEntryCopyFromWhseJnlLine(WhseEntry, WhseJnlLine, OnMovement, Sign, Location, BinCode,IsHandled);
        If not IsHandled then** 
        // DINNL >>     

        if Sign > 0 then begin
            if BinCode <> Location."Adjustment Bin Code" then begin
                if not ToBinContent.Get(
                        WhseJnlLine."Location Code", BinCode, WhseJnlLine."Item No.", WhseJnlLine."Variant Code", WhseJnlLine."Unit of Measure Code")
                then
                    InsertToBinContent(WhseEntry)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
