### ISSUE TITLE
[Event Request] Include sender in OnItemValuePostingOnBeforeInsertOHValueEntry in Codeunit 22 - Item Jnl.-Post Line

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13562]
Dear ALAppExtensions Team,

Is it possible to include the sender in OnItemValuePostingOnBeforeInsertOHValueEntry in Codeunit 22 - Item Jnl.-Post Line?

-[IntegrationEvent(false, false)]
  local procedure OnItemValuePostingOnBeforeInsertOHValueEntry(var ItemJnlLine: Record "Item Journal Line"; var 
     GlobalValueEntry: Record "Value Entry"; var GlobalItemLedgEntry: Record "Item Ledger Entry"; var ValueEntryNo: Integer; var 
     IsHandled: Boolean)
    begin
    end;

+[IntegrationEvent(true, false)]
  local procedure OnItemValuePostingOnBeforeInsertOHValueEntry(var ItemJnlLine: Record "Item Journal Line"; var 
     GlobalValueEntry: Record "Value Entry"; var GlobalItemLedgEntry: Record "Item Ledger Entry"; var ValueEntryNo: Integer; var 
     IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
