### ISSUE TITLE
Table 5965 "Service Contract Header" - Field "Starting Date" - OnValidate

### ISSUE THREAD

**Issue by Ayman-AYDI** [microsoft/ALAppExtensions#13572]
Dear ALAppExtensions Team,

We would like to request the following event publisher in Table 5965 "Service Contract Header" - Field "Starting Date" - OnValidate
var ServContractLine: Record "Service Contract Line"

Best Regards,
![image](https://user-images.githubusercontent.com/64891337/127018804-944bffeb-fd44-4a09-9c18-38bfd8ee0c42.png)

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
