### ISSUE TITLE
[Event Request] Codeunit 5760 "Whse.-Post Receipt" function PostWhseJnlLine

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13571]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5760 "Whse.-Post Receipt" function PostWhseJnlLine

        OnBeforeRegisterWhseJnlLines(TempWhseJnlLine, PostedWhseRcptHeader, PostedWhseRcptLine);

        ItemTrackingMgt.SplitWhseJnlLine(TempWhseJnlLine, TempWhseJnlLine2, TempWhseSplitSpecification, false);
        if TempWhseJnlLine2.Find('-') then
            repeat
            // DINNL <<
           DINOnPostWhseJnlLineBeforePost(TempWhseJnlLine2, PostedWhseRcptHeader);
           // DINNL >>
           WhseJnlRegisterLine.Run(TempWhseJnlLine2);
        until TempWhseJnlLine2.Next() = 0;

     local procedure DINOnPostWhseJnlLineBeforePost(var WarehouseJournalLine: Record "Warehouse Journal Line"; PostedWhseReceiptHeader: Record "Posted Whse. Receipt Header")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
