### ISSUE TITLE
Table 5965 "Service Contract Header" - Field "Invoice Period" - OnValidate 

### ISSUE THREAD

**Issue by Ayman-AYDI** [microsoft/ALAppExtensions#13570]
Dear ALAppExtensions Team,

We would like to request the following event publisher in Table 5965 "Service Contract Header" - Field "Invoice Period" - OnValidate
Var Rec :  Service Contract Header and IsHandled : Boolean

Best  Regards,

![image](https://user-images.githubusercontent.com/64891337/127013805-1219fe44-81be-464a-842e-712141cb3835.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
