### ISSUE TITLE
[Request for external] function ClearUTF8BOMSymbols in Codeunit "XML DOM Management"

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#13580]
Please make function ClearUTF8BOMSymbols in Codeunit "XML DOM Management" a public function.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
