### ISSUE TITLE
[Event Request] Codeunit 5760 "Whse.-Post Receipt" function InsertWhseItemEntryRelation

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13589]
Dear ALAppExtensions Team,

We would like to request the following event publisher in codeunit 5760 "Whse.-Post Receipt" function InsertWhseItemEntryRelation
    
     if TempWhseSplitSpecification.Find('-') then
            repeat
                WhseItemEntryRelation.InitFromTrackingSpec(TempWhseSplitSpecification);
                WhseItemEntryRelation.SetSource(
                  DATABASE::"Posted Whse. Receipt Line", 0, PostedWhseRcptHeader."No.", PostedWhseRcptLine."Line No.");
                // DINNL <<
                DINOnBeforeWhseItemEntryRelationInsertFromTempWhseSplitSpecification(WhseItemEntryRelation, 
                         TempWhseSplitSpecification);
                // DINNL >>
                WhseItemEntryRelation.Insert();
            until TempWhseSplitSpecification.Next() = 0;

           local procedure DINOnBeforeWhseItemEntryRelationInsertFromTempWhseSplitSpecification(var WhseItemEntryRelation: Record "Whse. Item Entry Relation"; TempWhseSplitSpecification: Record "Tracking Specification" temporary)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
