### ISSUE TITLE
Replace options fields by enum in SII fields

### ISSUE THREAD

**Issue by operrui** [microsoft/ALAppExtensions#13596]
For the Canary Islands SII, we need new options in the "Invoice Type" and "Special Schema Code" fields in all involved tables. I suggest replacing the type "Option" with "enum".

**Comment by AlexanderYakunin** [comment]
Here is list of available SII related enums:
![image](https://user-images.githubusercontent.com/31849120/127474373-b92a71fa-c025-4999-b051-632566707403.png)

**Comment by AlexanderYakunin** [comment]
Which version do you use? Seems we have everything you may need for your purpose?

**Comment by operrui** [comment]
I am using the latest published Oncloud version 18.3.27240.28196.
What I'm seeing is that in tables 36, 38, 112, ... the fields are still in option. I need them to be defined with their corresponding enum

![image](https://user-images.githubusercontent.com/38982763/127511168-41e2574a-8328-4408-9f36-e5909e9b253f.png)

**Comment by AlexanderYakunin** [comment]
Please be aware what we do not implement new enums in production version. We only do it for next major release (=19.0)

**Comment by operrui** [comment]
I'll keep it in mind. Thanks for everything
