### ISSUE TITLE
Codeunit : Undo Sales Shipment Line (5815) - Procedure: UpdateOrderLine

### ISSUE THREAD

**Issue by alessandrowolf87** [microsoft/ALAppExtensions#13594]
Hi,
can you please add a new event in the procedure UpdateOrderLine of "Undo Sales Shipment Line" codeunit

//>New Event
OnBeforeUpdateSalesLine(var SalesShptLine: Record "Sales Shipment Line",var isHandled: boolean);
//<New Event

//>Old Procedure

procedure UpdateOrderLine(ReturnRcptLine: Record "Return Receipt Line")
    var
        SalesLine: Record "Sales Line";
    begin
        with SalesShptLine do begin
            SalesLine.Get(SalesLine."Document Type"::Order, "Order No.", "Order Line No.");
            UndoPostingMgt.UpdateSalesLine(SalesLine, Quantity - "Quantity Invoiced", "Quantity (Base)" - "Qty. Invoiced (Base)", 
            TempGlobalItemLedgEntry);
            OnAfterUpdateSalesLine(SalesLine, SalesShptLine);
        end;
    end;
//<Old Procedure

//>New Procedure

```
procedure UpdateOrderLine(SalesShptLine: Record "Sales Shipment Line")
    var
        IsHandled: Boolean;
        SalesLine: Record "Sales Line";
    begin
        with SalesShptLine do begin
            IsHandled := false;
           OnBeforeUpdateSalesLine(SalesShptLine,isHandled);
           if IsHandled then
               exit;
           SalesLine.Get(SalesLine."Document Type"::Order, "Order No.", "Order Line No.");
           UndoPostingMgt.UpdateSalesLine(SalesLine, Quantity - "Quantity Invoiced", "Quantity (Base)" - "Qty. Invoiced (Base)",  
            TempGlobalItemLedgEntry);
           OnAfterUpdateSalesLine(SalesLine, SalesShptLine);
        end;
    end;
```
//<New Procedure

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
