### ISSUE TITLE
Codeunit : Undo Purchase Receipt Line (5813) - Procedure: UpdateOrderLine

### ISSUE THREAD

**Issue by alessandrowolf87** [microsoft/ALAppExtensions#13592]
Hi,
can you please add a new event in the procedure UpdateOrderLine of "Undo Purchase Receipt Line" codeunit

//>New Event
OnBeforeUpdateOrderLine(var PurchRcptLine: Record "Purch. Rcpt. Line",var isHandled: boolean);
//<New Event

//>Old Procedure

procedure UpdateOrderLine(PurchRcptLine: Record "Purch. Rcpt. Line")
    var
        PurchLine: Record "Purchase Line";
    begin
        with PurchRcptLine do begin
            PurchLine.Get(PurchLine."Document Type"::Order, "Order No.", "Order Line No.");
            UndoPostingMgt.UpdatePurchLine(PurchLine, Quantity - "Quantity Invoiced", "Quantity (Base)" - "Qty. Invoiced (Base)", 
            TempGlobalItemLedgEntry);
            UndoPostingMgt.UpdatePurchaseLineOverRcptQty(PurchLine, "Over-Receipt Quantity");
            OnAfterUpdateOrderLine(PurchRcptLine, PurchLine);
        end;
    end;

//<Old Procedure

//>New Procedure

procedure UpdateOrderLine(PurchRcptLine: Record "Purch. Rcpt. Line")
    var
        IsHandled: Boolean;
        PurchLine: Record "Purchase Line";
    begin
        with PurchRcptLine do begin
            IsHandled := false;
           OnBeforeUpdateOrderLine(PurchRcptLine,isHandled);
           if IsHandled then
               exit;
           PurchLine.Get(PurchLine."Document Type"::Order, "Order No.", "Order Line No.");
           UndoPostingMgt.UpdatePurchLine(PurchLine, Quantity - "Quantity Invoiced", "Quantity (Base)" - "Qty. Invoiced (Base)", 
           TempGlobalItemLedgEntry);
           UndoPostingMgt.UpdatePurchaseLineOverRcptQty(PurchLine, "Over-Receipt Quantity");
           OnAfterUpdateOrderLine(PurchRcptLine, PurchLine);
        end;
    end;

//<New Procedure

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
