### ISSUE TITLE
Codeunit : Undo Return Shipment Line (5814) - Procedure: UpdateOrderLine

### ISSUE THREAD

**Issue by alessandrowolf87** [microsoft/ALAppExtensions#13593]
Hi,
can you please add a new event in the procedure UpdateOrderLine of "Undo Return Shipment Line" codeunit

//>New Event
OnBeforeUpdatePurchLine(var ReturnShptLine: Record "Return Shipment Line",var isHandled: boolean);
//<New Event

//>Old Procedure

procedure UpdateOrderLine(ReturnRcptLine: Record "Return Receipt Line")
    var
        PurchLine: Record "Purchase Line";
    begin
        with ReturnShptLine do begin
            PurchLine.Get(PurchLine."Document Type"::"Return Order", "Return Order No.", "Return Order Line No.");
            UndoPostingMgt.UpdatePurchLine(PurchLine, Quantity, "Quantity (Base)", TempGlobalItemLedgEntry);
            OnAfterUpdatePurchLine(PurchLine, ReturnShptLine);
        end;
    end;
//<Old Procedure

//>New Procedure

procedure UpdateOrderLine(ReturnShptLine: Record "Return Shipment Line")
    var
        IsHandled: Boolean;
        PurchLine: Record "Purchase Line";
    begin
        with ReturnShptLine do begin
            IsHandled := false;
           OnBeforeUpdatePurchLine(ReturnShptLine,isHandled);
           if IsHandled then
               exit;
           PurchLine.Get(PurchLine."Document Type"::"Return Order", "Return Order No.", "Return Order Line No.");
           UndoPostingMgt.UpdatePurchLine(PurchLine, Quantity, "Quantity (Base)", TempGlobalItemLedgEntry);
           OnAfterUpdatePurchLine(PurchLine, ReturnShptLine);
        end;
    end;

//<New Procedure

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
