### ISSUE TITLE
Codeunit 10752 "SII Doc. Upload Management"

### ISSUE THREAD

**Issue by operrui** [microsoft/ALAppExtensions#13597]
In codeunit 10752 InvokeBatchSoapRequest procedure, I need to add new parameters to  event OnInvokeBatchSoapRequestOnBeforeStoreRequestXML. It would be like this:

OnInvokeBatchSoapRequestOnBeforeStoreRequestXML(RequestText,  **RequestType**, **WebServiceUrl** );

[IntegrationEvent(false, false)]
local procedure OnInvokeBatchSoapRequestOnBeforeStoreRequestXML(var RequestText: Text, **RequestType**: Option InvoiceIssuedRegistration,InvoiceReceivedRegistration,PaymentSentRegistration,PaymentReceivedRegistration,CollectionInCashRegistration, var **WebServiceUrl**: Text;);
  begin
  end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
