### ISSUE TITLE
Codeunit : Undo Purchase Receipt Line (5816) - Procedure: UpdateOrderLine

### ISSUE THREAD

**Issue by alessandrowolf87** [microsoft/ALAppExtensions#13595]
Hi,
can you please add a new event in the procedure UpdateOrderLine of "Undo Purchase Receipt Line" codeunit

//>New Event
OnBeforeUpdateSalesLine(var ReturnRcptLine: Record "Return Receipt Line",var isHandled: boolean);
//<New Event

//>Old Procedure

procedure UpdateOrderLine(ReturnRcptLine: Record "Return Receipt Line")
    var
        SalesLine: Record "Sales Line";
    begin
        with ReturnRcptLine do begin
            SalesLine.Get(SalesLine."Document Type"::"Return Order", "Return Order No.", "Return Order Line No.");
            UndoPostingMgt.UpdateSalesLine(SalesLine, Quantity, "Quantity (Base)", TempGlobalItemLedgEntry);
            OnAfterUpdateSalesLine(ReturnRcptLine, SalesLine);
        end;
    end;
//<Old Procedure

//>New Procedure

```
procedure UpdateOrderLine(ReturnRcptLine: Record "Return Receipt Line")
    var
        IsHandled: Boolean;
        SalesLine: Record "Sales Line";
    begin
        with ReturnRcptLine do begin
            IsHandled := false;
           OnBeforeUpdateSalesLine(ReturnRcptLine,isHandled);
           if IsHandled then
               exit;
           SalesLine.Get(SalesLine."Document Type"::"Return Order", "Return Order No.", "Return Order Line No.");
           UndoPostingMgt.UpdateSalesLine(SalesLine, Quantity, "Quantity (Base)", TempGlobalItemLedgEntry);
           OnAfterUpdateSalesLine(ReturnRcptLine, SalesLine);
        end;
    end;
```
//<New Procedure

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
