### ISSUE TITLE
codeunit 8 AccSchedManagement

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#13590]
https://github.com/microsoft/ALAppExtensions/issues/13469#event-5075139552 

Would it then be possible to make a "Get" Pocedure?

```
procedure GetStartDateEndDate(OutputStartDate: Date; OutputEndDate: Date)
begin
    OutputStartDate := StartDate;
    OutputEndDate := EndDate;
end;
```

**Comment by db-bc** [comment]
The parameters will need to be declared `var` for changes in them to propagate to the caller

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
