### ISSUE TITLE
[Event Reuqest] Codeunit 80 Sales-Post - function ReverseAmount

### ISSUE THREAD

**Issue by Drakonian** [Microsoft/ALAppExtensions#136]
Hello,
We need below events to customize workflow for CU 80:

Add integration event in function **ReverseAmount**

```
WITH SalesLine DO BEGIN
  "Qty. to Ship" := -"Qty. to Ship";
  "Qty. to Ship (Base)" := -"Qty. to Ship (Base)";
  "Return Qty. to Receive" := -"Return Qty. to Receive";
  "Return Qty. to Receive (Base)" := -"Return Qty. to Receive (Base)";
  "Qty. to Invoice" := -"Qty. to Invoice";
  "Qty. to Invoice (Base)" := -"Qty. to Invoice (Base)";
  "Line Amount" := -"Line Amount";
  Amount := -Amount;
  "VAT Base Amount" := -"VAT Base Amount";
  "VAT Difference" := -"VAT Difference";
  "Amount Including VAT" := -"Amount Including VAT";
  "Line Discount Amount" := -"Line Discount Amount";
  "Inv. Discount Amount" := -"Inv. Discount Amount";
END;
// NEW CODE START
OnAfterReverseAmount(SalesLine);
// NEW CODE END
```

With new Publisher:

`OnAfterReverseAmount(VAR SalesLine : Record "Sales Line")`

- AL Extension Version: 0.12.28462
- Server Version: NA11.0 (24742)

**Comment by AlexanderYakunin** [comment]
Event already exist

**Comment by Drakonian** [comment]
> Event already exist

Did you mean it is will be exist in CU11?
![2](https://user-images.githubusercontent.com/16802407/47669023-98dbbf80-dbb2-11e8-912c-7f9ff0437a15.png)
![1](https://user-images.githubusercontent.com/16802407/47669024-98dbbf80-dbb2-11e8-972d-28134112f69a.png)

**Comment by frivadulla** [comment]
> 
> 
> > Event already exist
> 
> Did you mean it is will be exist in CU11?
> ![2](https://user-images.githubusercontent.com/16802407/47669023-98dbbf80-dbb2-11e8-912c-7f9ff0437a15.png)
> ![1](https://user-images.githubusercontent.com/16802407/47669024-98dbbf80-dbb2-11e8-972d-28134112f69a.png)

In the last BC sandbox, the event is created:

![evento_codeunit80](https://user-images.githubusercontent.com/7207127/47702661-f48f6280-dc1d-11e8-9264-b0938f412c66.JPG)

**Comment by AlexanderYakunin** [comment]
Correct, we do not create more events for NAV 2018, this is on prem version and you can do it yourself. We create new events for monthly updates on D365 BC and they are available in cloud tenants
