### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" OnInsertReservEntryFromTrackingSpecBeforeInsert

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13605]
Hello, 

Is it possible to add the following Event:  

          TransferFields(TrackingSpecification);
            "Source Subtype" := SourceSubtype;
            "Source ID" := SourceID;
            "Source Ref. No." := SourceRefNo;
            "Reservation Status" := "Reservation Status"::Prospect;
            "Quantity Invoiced (Base)" := 0;
            Validate("Quantity (Base)", QtyBase);
            Positive := ("Quantity (Base)" > 0);
            "Entry No." := 0;
            "Item Tracking" := GetItemTrackingEntryType();
            **// DINNL <<
            OnInsertReservEntryFromTrackingSpecBeforeInsert(ReservEntry, TrackingSpecification);
            // DINNL >>**
            Insert();
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnInsertReservEntryFromTrackingSpecBeforeInsert(var ReservationEntry: Record "Reservation Entry"; TrackingSpecification: Record "Tracking Specification")
    begin
    end;

**Comment by AlexanderYakunin** [comment]
We already have this event
