### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" OnWhseItemTrkgLineExists

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13602]
Hello, 

Is it possible to add the following event:

    procedure WhseItemTrkgLineExists(SourceId: Code[20]; SourceType: Integer; SourceSubtype: Integer; SourceBatchName: Code[10]; SourceProdOrderLine: Integer; SourceRefNo: Integer; LocationCode: Code[10]; ItemTrackingSetup: Record "Item Tracking Setup"): Boolean
    var
        WhseItemTrkgLine: Record "Whse. Item Tracking Line";
    begin
        with WhseItemTrkgLine do begin
            SetSourceFilter(SourceType, SourceSubtype, SourceId, SourceRefNo, true);
            SetSourceFilter(SourceBatchName, SourceProdOrderLine);
            SetRange("Location Code", LocationCode);
            SetTrackingFilterFromItemTrackingSetupIfNotBlank(ItemTrackingSetup);
            // DINNL <<
            OnWhseItemTrkgLineExists(WhseItemTrkgLine);
            // DINNL >>
            exit(not IsEmpty);
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnWhseItemTrkgLineExists(var WhseItemTrkgLine: Record "Whse. Item Tracking Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
