### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management"  OnBeforeTempHandlingSpecificationModify

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13601]
Hello, 

Hello, 

Is it possible to add the following event.

            TempHandlingSpecification."Qty. to Handle" :=
                          TempHandlingSpecification."Qty. to Handle (Base)" / ReservEntry."Qty. per Unit of Measure";
                        TempHandlingSpecification."Qty. to Invoice" :=
                          TempHandlingSpecification."Qty. to Invoice (Base)" / ReservEntry."Qty. per Unit of Measure";
                        if not ReservEntry.IsReservationOrTracking() then // Late Binding
                            TempHandlingSpecification."Buffer Value1" += TempHandlingSpecification."Qty. to Handle (Base)";
                        **// DINNL <<
                        OnBeforeTempHandlingSpecificationModify(TempHandlingSpecification, ReservEntry);
                        // DINNL >>**
                        TempHandlingSpecification.Modify();
                    end else begin
                        TempHandlingSpecification.Init();
                        TempHandlingSpecification.TransferFields(ReservEntry);
                        NextEntryNo += 1;
                        TempHandlingSpecification."Entry No." := NextEntryNo;
                        TempHandlingSpecification."Qty. to Handle" :=
                          TempHandlingSpecification."Qty. to Handle (Base)" / ReservEntry."Qty. per Unit of Measure";
                        TempHandlingSpecification."Qty. to Invoice" :=
         

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTempHandlingSpecificationModify(var TempTrackingSpecification: Record "Tracking Specification" temporary; ReservationEntry: Record "Reservation Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
