### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" OnItemTrackingExistsOnDocumentLineBeforeExit

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13606]
Hello, 

Is it possible to add the following Event:

    procedure ItemTrackingExistsOnDocumentLine(SourceType: Integer; SourceSubtype: Option; SourceID: Code[20]; SourceRefNo: Integer): Boolean
    var
        TrackingSpecification: Record "Tracking Specification";
        ReservEntry: Record "Reservation Entry";
    begin
        TrackingSpecification.SetSourceFilter(SourceType, SourceSubtype, SourceID, SourceRefNo, true);
        TrackingSpecification.SetSourceFilter('', 0);
        TrackingSpecification.SetRange(Correction, false);
        ReservEntry.SetSourceFilter(SourceType, SourceSubtype, SourceID, SourceRefNo, true);
        ReservEntry.SetSourceFilter('', 0);
        ReservEntry.SetFilter("Item Tracking", '<>%1', ReservEntry."Item Tracking"::None);

        // DINNL <<
        OnItemTrackingExistsOnDocumentLineBeforeExit(ReservEntry);
        // DINNL >>
        exit(not TrackingSpecification.IsEmpty or not ReservEntry.IsEmpty);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnItemTrackingExistsOnDocumentLineBeforeExit(var ReservEntry: Record "Reservation Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
