### ISSUE TITLE
[Event Modification]  codeunit 6500 "Item Tracking Management"  OnBeforeInsertReservEntryForSalesLine

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13603]
Hello, 

Is it possible to add an extra variable to an existing event:

OnBeforeInsertReservEntryForSalesLine(ReservEntry, SalesLine, ItemLedgEntryBuf);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
