### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" OnAfterTestExpDateOnTrackingSpecNew

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13609]
Hello, 

Is it possible to add the following Event:

    procedure TestExpDateOnTrackingSpecNew(var TempTrackingSpecification: Record "Tracking Specification" temporary)
    begin
        if TempTrackingSpecification."New Lot No." = '' then
            exit;
        TempTrackingSpecification.SetRange("New Lot No.", TempTrackingSpecification."New Lot No.");
        TempTrackingSpecification.SetFilter("New Expiration Date", '<>%1', TempTrackingSpecification."New Expiration Date");
        if not TempTrackingSpecification.IsEmpty() then
            Error(Text007, TempTrackingSpecification."New Lot No.");
        TempTrackingSpecification.SetRange("New Lot No.");
        TempTrackingSpecification.SetRange("New Expiration Date");
        // DINNL <<
        OnAfterTestExpDateOnTrackingSpecNew(TempTrackingSpecification);
        // DINNL >>
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterTestExpDateOnTrackingSpecNew(var TempTrackingSpecification: Record "Tracking Specification" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
