### ISSUE TITLE
[Event Request] codeunit 6501 "Item Tracking Data Collection" AssistEditTrackingNoOnBeforeItemTrackingSummaryFormRunmodal

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13619]
Hello, 

Is it possible to add the following Event:

        ItemTrackingSummaryForm.SetSources(TempGlobalReservEntry, TempGlobalEntrySummary);
        ItemTrackingSummaryForm.LookupMode(SearchForSupply);
        ItemTrackingSummaryForm.SetSelectionMode(false);

        // DINNL <<
        AssistEditTrackingNoOnBeforeItemTrackingSummaryFormRunmodal(TempTrackingSpecification);
        // DINNL >>
        Window.Close;
        if ItemTrackingSummaryForm.RunModal = ACTION::LookupOK then begin
            ItemTrackingSummaryForm.GetRecord(TempGlobalEntrySummary);

    [IntegrationEvent(false, false)]
    local procedure AssistEditTrackingNoOnBeforeItemTrackingSummaryFormRunmodal(TempTrackingSpecification: Record "Tracking Specification" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
