### ISSUE TITLE
[Event Request] codeunit 6501 "Item Tracking Data Collection" OnUpdateLotSNGlobalChangeRecCalcCurrentPendingQuantity

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13617]
Hello, 

Is it possible to add the following Event: (2 integration points)

            TempGlobalChangedEntrySummary."Entry No." := LastEntryNo + 1;
            TempGlobalChangedEntrySummary.CopyTrackingFromSpec(TempTrackingSpecificationChanged);
            TempGlobalChangedEntrySummary."Non Serial Tracking" := TempGlobalEntrySummary.HasNonSerialTracking();
            TempGlobalChangedEntrySummary."Current Pending Quantity" := NewQuantity;
            // DINNL <<
            OnUpdateLotSNGlobalChangeRecCalcCurrentPendingQuantity(
              TempGlobalChangedEntrySummary, TempTrackingSpecificationChanged, LineIsDemand, CurrentSignFactor, ChangeType);
            // DINNL >>
            if TempTrackingSpecificationChanged."Serial No." <> '' then
                TempGlobalChangedEntrySummary."Table ID" := DATABASE::"Tracking Specification"; // Not a summary line
            OnBeforeTempGlobalChangedEntrySummaryInsert(TempGlobalChangedEntrySummary, TempTrackingSpecificationChanged);
            TempGlobalChangedEntrySummary.Insert();
            PartialGlobalDataSetExists := false; // The partial data set does not cover the new line
        end else
            if LineIsDemand then begin
                TempGlobalChangedEntrySummary."Current Pending Quantity" := NewQuantity;
                // DINNL <<
                OnUpdateLotSNGlobalChangeRecCalcCurrentPendingQuantity(
                  TempGlobalChangedEntrySummary, TempTrackingSpecificationChanged, LineIsDemand, CurrentSignFactor, ChangeType);
                // DINNL >>
                TempGlobalChangedEntrySummary.Modify();
            end;
        exit(TempGlobalChangedEntrySummary."Entry No.");
    end;

    [IntegrationEvent(false, false)]
    local procedure OnUpdateLotSNGlobalChangeRecCalcCurrentPendingQuantity(var TempGlobalChangedEntrySummary: Record "Entry Summary" temporary; var TempItemTrackLineChanged: Record "Tracking Specification" temporary; LineIsDemand: Boolean; CurrentSignFactor: Integer; ChangeType: Option Insert,Modify,Delete)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
