### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" OnSynchronizeItemTrkgTransferSetFilterOnToReservEntry

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13610]
Hello, 

Is it possible to add the following Event:

        SumUpItemTracking(FromReservEntry, TempTrackingSpecification, false, true);
        TempTrackingSpecification.Reset();
        TempTrackingSpecification.SetFilter("Qty. to Handle (Base)", '<%1', 0);
        if TempTrackingSpecification.FindSet then
            repeat
                ToReservEntry.SetRange("Lot No.", TempTrackingSpecification."Lot No.");
                ToReservEntry.SetRange("Serial No.", TempTrackingSpecification."Serial No.");
                // DINNL <<
                OnSynchronizeItemTrkgTransferSetFilterOnToReservEntry(ToReservEntry, TempTrackingSpecification);
                // DINNL >>
                ToReservEntry.ModifyAll("Qty. to Handle (Base)", 0);
                ToReservEntry.ModifyAll("Qty. to Invoice (Base)", 0);

                TempTrackingSpecification."Qty. to Handle (Base)" *= -1;

    [IntegrationEvent(false, false)]
    local procedure OnSynchronizeItemTrkgTransferSetFilterOnToReservEntry(var ToReservEntry: Record "Reservation Entry"; TempTrackingSpecification: Record "Tracking Specification" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
