### ISSUE TITLE
[Event Modification] codeunit 6501 "Item Tracking Data Collection" OnAddSelectedTrackingToDataSetOnAfterCopyNewTrackingFromTrackingSpec

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13615]
hello,

Is is it possible to add some paramaters to an event:

OnAddSelectedTrackingToDataSetOnAfterCopyNewTrackingFromTrackingSpec(TempTrackingSpecification,TempEntrySummary, ChangeType::Insert);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
