### ISSUE TITLE
[Event Request] codeunit 6501 "Item Tracking Data Collection"  OnCreateEntrySummary2

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13614]
Hello, 

Is it possible to add the following Event:

            TempGlobalEntrySummary."Total Requested Quantity" -= TempReservEntry."Quantity (Base)";
            if TempReservEntry.HasSamePointerWithSpec(TrackingSpecification) then begin
                if TempReservEntry."Reservation Status" = TempReservEntry."Reservation Status"::Reservation then
                    TempGlobalEntrySummary."Current Reserved Quantity" -= TempReservEntry."Quantity (Base)";
                if TempReservEntry."Entry No." > 0 then // The record represents a reservation entry
                    TempGlobalEntrySummary."Current Requested Quantity" -= TempReservEntry."Quantity (Base)";
            end;
        end;

        // DINNL <<
        OnCreateEntrySummary2(TempGlobalEntrySummary, TempReservEntry, TrackingSpecification, TempReservEntry.HasSamePointerWithSpec(TrackingSpecification));
        // DINNL >>
        // Update available quantity on the record
        TempGlobalEntrySummary.UpdateAvailable();
        if DoInsert then
            TempGlobalEntrySummary.Insert()
        else
            TempGlobalEntrySummary.Modify();

    [IntegrationEvent(false, false)]
    local procedure OnCreateEntrySummary2(var TempGlobalEntrySummary: Record "Entry Summary" temporary; TempReservEntry: Record "Reservation Entry" temporary; TrackingSpecification: Record "Tracking Specification" temporary; HasSamePointer: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
