### ISSUE TITLE
[Event Request] codeunit 6501 "Item Tracking Data Collection" OnUpdateTempSummaryWithChangeCalcCurrentPendingQuantity

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13618]
Hello, 

Is it possible to add the following Event:

                if ChangedEntrySummary."Serial No." <> '' then begin
                    TempGlobalEntrySummary."Current Pending Quantity" := SumOfSNPendingQuantity;
                    TempGlobalEntrySummary."Current Requested Quantity" := SumOfSNRequestedQuantity;
                end else
                    TempGlobalEntrySummary."Current Pending Quantity" := ChangedEntrySummary."Current Pending Quantity" -
                      TempGlobalEntrySummary."Current Requested Quantity";

                // DINNL <<
                OnUpdateTempSummaryWithChangeCalcCurrentPendingQuantity(ChangedEntrySummary, TempGlobalEntrySummary);
                // DINNL >>
                TempGlobalEntrySummary.UpdateAvailable();
                TempGlobalEntrySummary.Modify();
            end else begin
                TempGlobalEntrySummary := ChangedEntrySummary;
                TempGlobalEntrySummary."Entry No." := LastEntryNo + 1;
                TempGlobalEntrySummary."Serial No." := '';

    [IntegrationEvent(false, false)]
    local procedure OnUpdateTempSummaryWithChangeCalcCurrentPendingQuantity(ChangedEntrySummary: Record "Entry Summary" temporary; var TempGlobalEntrySummary: Record "Entry Summary" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
