### ISSUE TITLE
extensibility-enhancement request / change needed ASAP (table 832 "Workflows Entries Buffer" RunWorkflowEntriesPage)

### ISSUE THREAD

**Issue by eque2al** [microsoft/ALAppExtensions#13612]
Hi,

The table  _Workflows Entries Buffer_ / procedure _RunWorkflowEntriesPage_ has it's 3rd parameter still as an Option.  Please can this be changed to an enum (to avoid passing in enum 'Sales Document Type' resulting in a warning ('AL0603')).?

Thanks!

**Comment by AlexanderYakunin** [comment]
Why you need this ASAP? It does not represent any problem, we have good time to resolve such warnings.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
