### ISSUE TITLE
[Event Request] codeunit 6501 "Item Tracking Data Collection"  OnAddSelectedLotSNToDatabeforeUpdateTrackingDataSetWithChange

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13616]
Hello, 

Is it possible to add the following Event:

OnAddSelectedTrackingToDataSetOnAfterInitTrackingSpecification2(TrackingSpecification2, TempTrackingSpecification);

        TempTrackingSpecification.Reset();
        LastEntryNo := TempTrackingSpecification.GetLastEntryNo();

        TempEntrySummary.FindFirst;
        repeat
            TempTrackingSpecification.SetTrackingFilterFromEntrySummary(TempEntrySummary);
            if TempTrackingSpecification.FindFirst() then begin
                // DINNL <<
                OnAddSelectedLotSNToDatabeforeUpdateTrackingDataSetWithChange(TempEntrySummary, TempTrackingSpecification, ChangeType::Modify);
                // DINNL >>
                TempTrackingSpecification.Validate("Quantity (Base)",
                  TempTrackingSpecification."Quantity (Base)" + TempEntrySummary."Selected Quantity");
                TempTrackingSpecification."Buffer Status" := TempTrackingSpecification."Buffer Status"::MODIFY;
                TransferExpDateFromSummary(TempTrackingSpecification, TempEntr

    [IntegrationEvent(false, false)]
    local procedure OnAddSelectedLotSNToDatabeforeUpdateTrackingDataSetWithChange(var TempEntrySummary: Record "Entry Summary" temporary; var TrackingSpecification: Record "Tracking Specification" temporary; ChangeType: Option Insert,Modify,Delete)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
