### ISSUE TITLE
[Event Request] codeunit 80 "Sales-Post"  OnBeforeDeleteAfterPosting

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13626]
Hello, 

Is it possible to add the following to an Event:

        OnBeforeDeleteAfterPosting(SalesHeader, SalesInvHeader, SalesCrMemoHeader, SkipDelete, SuppressCommit, EverythingInvoiced);

to 

        OnBeforeDeleteAfterPosting(SalesHeader, SalesInvHeader, SalesCrMemoHeader, SkipDelete, SuppressCommit, EverythingInvoiced,TempSalesLineGlobal);

TempSalesLineGlobal as var

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
