### ISSUE TITLE
[Event Modification] codeunit 80 "Sales-Post" OnPostItemJnlLineOnAfterPrepareItemJnlLine

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13624]
Hello, 

Is it possible to add the following to an Event:

OnPostItemJnlLineOnAfterPrepareItemJnlLine(ItemJnlLine, SalesLine, SalesHeader, WhseShip, ItemJnlPostLine);

to:

OnPostItemJnlLineOnAfterPrepareItemJnlLine(ItemJnlLine, SalesLine, SalesHeader, WhseShip, ItemJnlPostLine, QtyToBeShipped, TrackingSpecification);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
