### ISSUE TITLE
[Event Request] codeunit 80 "Sales-Post"  OnBeforeSaveInvoiceSpecification

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13627]
Hello, 

Is it possible to add the following Event:

    local procedure SaveInvoiceSpecification(var TempInvoicingSpecification: Record "Tracking Specification" temporary)
    begin
        TempInvoicingSpecification.Reset();
        if TempInvoicingSpecification.FindSet() then begin
            repeat
                TempInvoicingSpecification."Quantity Invoiced (Base)" += TempInvoicingSpecification."Quantity actual Handled (Base)";
                TempInvoicingSpecification."Quantity actual Handled (Base)" := 0;
                // DINNL <<
                OnBeforeSaveInvoiceSpecification(TempInvoicingSpecification);
                // DINNL >>
                TempTrackingSpecification := TempInvoicingSpecification;
                TempTrackingSpecification."Buffer Status" := TempTrackingSpecification."Buffer Status"::MODIFY;
                if not TempTrackingSpecification.Insert() then begin
                    TempTrackingSpecification.Get(TempInvoicingSpecification."Entry No.");
                    TempTrackingSpecification."Qty. to Invoice (Base)" += TempInvoicingSpecification."Qty. to Invoice (Base)";

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSaveInvoiceSpecification(var TempInvoicingSpecification: Record "Tracking Specification" temporary)
    begin
    end;

**Comment by db-bc** [comment]
Presumably you expect `TempInvoicingSpecification` to be passed to subscribers as `var`? You should show such details. Best is to just include how the publisher would be declared.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
