### ISSUE TITLE
[Event Request] codeunit 80 "Sales-Post" OnAfterRoundAmount

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13623]
Hello, 

Is it possible to add the following Event:

           CheckItemReservDisruption(SalesLine);
            RoundAmount(SalesHeader, SalesLine, "Qty. to Invoice");

            // DINNL <<
            OnAfterRoundAmount(SalesLine, SalesInvHeader, SalesCrMemoHeader, SalesHeader.Invoice);
            // DINNL >>
            if not IsCreditDocType then begin
                ReverseAmount(SalesLine);
                ReverseAmount(SalesLineACY);
            end;

            RemQtyToBeInvoiced := "Qty. to Invoice";
            RemQtyToBeInvoicedBase := "Qty. to Invoice (Base)";

    [IntegrationEvent(false, false)]
    local procedure OnHandleRentalPostFromSalesPost(SalesLine: Record "Sales Line"; SalesInvoiceHeader: Record "Sales Invoice Header"; SalesCrMemoHeader: Record "Sales Cr.Memo Header"; Invoice: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
