### ISSUE TITLE
[Event Request] codeunit 6501 "Item Tracking Data Collection" OnSelectMultipleTrackingNoOnBeforePageRunModal

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13622]
Hello, 

Is it possible to add the following Event:

       ItemTrackingSummaryForm.AutoSelectTrackingNo();

        Window.Close;

        // DINNL <<
        IsHandled := false;
        OnSelectMultipleTrackingNoOnBeforePageRunModal(DINIsHandled);
        if not IsHandled then
        // DINNL >>
        if not (ItemTrackingSummaryForm.RunModal = ACTION::LookupOK) then
            exit;
        ItemTrackingSummaryForm.GetSelected(TempEntrySummary);
        if TempEntrySummary.IsEmpty() then
            exit;

        // Swap sign on the selected entries if parent is a negative supply line
        if CurrentSignFactor > 0 then // Negative supply lines
            if TempEntrySummary.Find('-') then

    [IntegrationEvent(false, false)]
    local procedure OnSelectMultipleTrackingNoOnBeforePageRunModal(var IsHandled: Boolean)
    begin
    end;

**Comment by AlexanderYakunin** [comment]
Please explain how you are going to us this event without any parameters except IsHandled?

**Comment by leegeurts** [comment]
If we have a certain app installed we don't want that form to run. So we just check if our own app is active.

**Comment by AlexanderYakunin** [comment]
In this case why don't you use event OnBeforeSelectMultipleTrackingNo in beginning of this procedure? Do you need to run all code before run page, I assume this is not needed in your case?

**Comment by leegeurts** [comment]
We are going to check that. Please feel free to close this one in the meanwhile. 

Thank you Alexander.
