### ISSUE TITLE
[Event Request] codeunit 80 "Sales-Post" OnAfterCopyToTempLines

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13635]
procedure CopyToTempLines(SalesHeader: Record "Sales Header"; var TempSalesLine: Record "Sales Line" temporary)
    var
        SalesLine: Record "Sales Line";
    begin
        SalesLine.SetRange("Document Type", SalesHeader."Document Type");
        SalesLine.SetRange("Document No.", SalesHeader."No.");
        OnCopyToTempLinesOnAfterSetFilters(SalesLine, SalesHeader);
        if SalesLine.FindSet() then
            repeat
                TempSalesLine := SalesLine;
                TempSalesLine.Insert();
            until SalesLine.Next() = 0;
        // DINNL <<
        OnAfterCopyToTempLines(TempSalesLine);
        // DINNL >>
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyToTempLines(var TempSalesLine: Record "Sales Line" temporary)
    begin
    end;

**Comment by Oleg-Romashkov** [comment]
The parameter DINTempPackagingSalesLine does not exist. Could you please check base application code?

**Comment by leegeurts** [comment]
Sorry Oleg :) Forgot to remove it :) Updated the request

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
