### ISSUE TITLE
[Event Modification] codeunit 80 "Sales-Post"

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13633]
Hello, 

Is it possible to add the following to an Event:

        OnRunOnBeforeCheckTotalInvoiceAmount(SalesHeader);

to 

      TempServiceItem2.DeleteAll();
        TempServiceItemComp2.DeleteAll();

        // Check that the invoice amount is zero or greater
        // DINNL <<
        OnRunOnBeforeCheckTotalInvoiceAmount(SalesHeader,IsHandled );
        if not IsHandled then 
        // DINNL >>
        if SalesHeader.Invoice then
                CheckTotalInvoiceAmount(SalesHeader);

        OnRunOnBeforeCheckAndUpdate(SalesHeader);

**Comment by Oleg-Romashkov** [comment]
Is it ok for you to use existing event OnBeforeCheckTotalInvoiceAmount instead?

**Comment by leegeurts** [comment]
Yes, you are correct, we can do it there. Thank you :)

**Comment by Oleg-Romashkov** [comment]
Ok, then closing the request.
