### ISSUE TITLE
[Event Request] codeunit 80 "Sales-Post"  OnPostUpdateInvoiceLineOnBeforeCalcQuantityInvoiced

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13630]
Hello, 

Is it possible to add the following to an Event:

                    if Type = Type::"Charge (Item)" then
                        UpdateSalesOrderChargeAssgnt(TempSalesLine, SalesOrderLine);
                    // DINNL <<
                    IsHandled := false;
                    OnPostUpdateInvoiceLineOnBeforeCalcQuantityInvoiced(SalesOrderLine, TempSalesLine, IsHandled);
                    if not IsHandled then begin
                        // DINNL >>
                        SalesOrderLine."Quantity Invoiced" += "Qty. to Invoice";
                        SalesOrderLine."Qty. Invoiced (Base)" += "Qty. to Invoice (Base)";
                        CheckSalesLineInvoiceMoreThanShipped(SalesOrderLine, TempSalesLine, SalesShptLine);
                        OnPostUpdateInvoiceLineOnBeforeInitQtyToInvoice(SalesOrderLine, TempSalesLine);
                        SalesOrderLine.InitQtyToInvoice;
                        if SalesOrderLine."Prepayment %" <> 0 then begin
                            SalesOrderLine."Prepmt Amt Deducted" += "Prepmt Amt to Deduct";
                            SalesOrderLine."Prepmt VAT Diff. Deducted" += "Prepmt VAT Diff. to Deduct";
                            DecrementPrepmtAmtInvLCY(
                              TempSalesLine, SalesOrderLine."Prepmt. Amount Inv. (LCY)", SalesOrderLine."Prepmt. VAT Amount Inv. (LCY)");
                            SalesOrderLine."Prepmt Amt to Deduct" :=
                              SalesOrderLine."Prepmt. Amt. Inv." - SalesOrderLine."Prepmt Amt Deducted";
                            SalesOrderLine."Prepmt VAT Diff. to Deduct" := 0;
                        end;
                        SalesOrderLine.InitOutstanding();
                        SalesOrderLine.Modify();
                        OnPostUpdateInvoiceLineOnAfterModifySalesOrderLine(SalesOrderLine, TempSalesLine);

                        if not TempSalesOrderHeader.Get(SalesOrderLine."Document Type", SalesOrderLine."Document No.") then begin
                            TempSalesOrderHeader."Document Type" := SalesOrderLine."Document Type";
                            TempSalesOrderHeader."No." := SalesOrderLine."Document No.";
                            TempSalesOrderHeader.Insert();
                        end;
                        // DINNL <<
                    end;
                // DINNL >>

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
