### ISSUE TITLE
[Event Request] codeunit 80 "Sales-Post" OnAfterReturnRcptLineInsert

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13638]
Hello, 

Is it possible to add the following Event:

            ReturnRcptLine."Item Rcpt. Entry No." :=
              InsertReturnEntryRelation(ReturnRcptLine); // ItemLedgShptEntryNo;
            ReturnRcptLine."Item Charge Base Amount" :=
              Round(CostBaseAmount / SalesLine.Quantity * ReturnRcptLine.Quantity);
        end;
        // DINNL <<
        OnAfterReturnRcptLineInsert(xSalesLine, ReturnRcptLine);
        // DINNL >>
    end;

    local procedure CheckICPartnerBlocked(SalesHeader: Record "Sales Header")
    var
        ICPartner: Record "IC Partner";
    begin
        with SalesHeader do begin

    [IntegrationEvent(false, false)]
    local procedure OnAfterReturnRcptLineInsert(xSalesLine: Record "Sales Line"; var ReturnReceiptLine: Record "Return Receipt Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
