### ISSUE TITLE
[Request for external] codeunit 92 "Purch.-Post + Print" Print functions

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13647]
Please make the following functions available:

PrintReceive
PrintInvoice
PrintShip
PrintCrMemo

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
