### ISSUE TITLE
[Event Request]  codeunit 90 "Purch.-Post"

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13640]
Hello, 

Is it possible to add the following Event:

                 BlanketOrderPurchLine."Document Type"::"Blanket Order", PurchLine."Blanket Order No.",
                 PurchLine."Blanket Order Line No.")
            then begin
                BlanketOrderPurchLine.TestField(Type, PurchLine.Type);
                BlanketOrderPurchLine.TestField("No.", PurchLine."No.");
                BlanketOrderPurchLine.TestField("Buy-from Vendor No.", PurchLine."Buy-from Vendor No.");

                // DINNL <<
                OnBeforeUpdateBlanketOrderLine(BlanketOrderPurchLine, PurchLine);
                // DINNL >>
                ModifyLine := false;
                case PurchLine."Document Type" of
                    PurchLine."Document Type"::Order,
                  PurchLine."Document Type"::Invoice:
                        Sign := 1;
                    PurchLine."Document Type"::"Return Order",
                  PurchLine."Document Type"::"Credit Memo":
                        Sign := -1;
                end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateBlanketOrderLine(var BlanketOrderPurchaseLine: Record "Purchase Line"; PurchaseLine: Record "Purchase Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
