### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post"  OnInsertReturnShipmentLineBeforeCreate

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13643]
Hello, 

Is it possible to add the following Event:

    if (PurchLine.Type = PurchLine.Type::Item) and (PurchLine."Return Qty. to Ship" <> 0) then begin
            // DINNL <<
            IsHandled := false;
            OnInsertReturnShipmentLineBeforeCreate(PurchLine, IsHandled);
            if not IsHandled then
                // DINNL >>
            if WhseShip then
                    if WhseShptLine.GetWhseShptLine(
                         WhseShptHeader."No.", DATABASE::"Purchase Line", PurchLine."Document Type".AsInteger(), PurchLine."Document No.", PurchLine."Line No.")
                    then begin
                        OnInsertReturnShipmentLineOnAfterGetWhseShptLine(WhseShptLine, ReturnShptLine);
                        WhseShptLine.TestField("Qty. to Ship", ReturnShptLine.Quantity);
                        SaveTempWhseSplitSpec(PurchLine);
                        WhsePostShpt.CreatePostedShptLine(
                          WhseShptLine, PostedWhseShptHeader, PostedWhseShptLine, TempWhseSplitSpecification);
                    end;
            // DINNL <<
           IsHandled := false;
            OnInsertReturnShipmentLineBeforeCreate(PurchLine, IsHandled);
            if not IsHandled then
                // DINNL >>
            if WhseReceive then
                    if WhseRcptLine.GetWhseRcptLine(
                         WhseRcptHeader."No.", DATABASE::"Purchase Line", PurchLine."Document Type".AsInteger(), PurchLine."Document No.", PurchLine."Line No.")
                    then begin
                        WhseRcptLine.TestField("Qty. to Receive", -ReturnShptLine.Quantity);
                        SaveTempWhseSplitSpec(PurchLine);
                        WhsePostRcpt.CreatePostedRcptLine(
                          WhseRcptLine, PostedWhseRcptHeader, PostedWhseRcptLine, TempWhseSplitSpecification);
                    end;

    [IntegrationEvent(false, false)]
    local procedure DINOnInsertReturnShipmentLinePurchaseLineIsPackingLineOrSortCompLine(PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
