### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" OnSaveInvoiceSpecificationOnBeforeModify

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13642]
Hello, 

Is it possible to add the following Event:

    TempTrackingSpecification.Get(TempInvoicingSpecification."Entry No.");
                    TempTrackingSpecification."Qty. to Invoice (Base)" += TempInvoicingSpecification."Qty. to Invoice (Base)";
                    TempTrackingSpecification."Quantity Invoiced (Base)" += TempInvoicingSpecification."Qty. to Invoice (Base)";
                    TempTrackingSpecification."Qty. to Invoice" += TempInvoicingSpecification."Qty. to Invoice";
                    // DINNL <<
                    OnSaveInvoiceSpecificationOnBeforeModify(TempTrackingSpecification, TempInvoicingSpecification);
                    // DINNL >>
                    TempTrackingSpecification.Modify();
                end;
                OnSaveInvoiceSpecificationOnAfterUpdateTempTrackingSpecification(TempTrackingSpecification, TempInvoicingSpecification);
            until TempInvoicingSpecification.Next() = 0;
            TempInvoicingSpecification.DeleteAll();
        end;

    [IntegrationEvent(false, false)]
    local procedure OnSaveInvoiceSpecificationOnBeforeModify(var TempTrackingSpecification: Record "Tracking Specification" temporary; TempInvoicingSpecification: Record "Tracking Specification" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
