### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" OnbeforeSetTempTrackingSpecification

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13641]
Hello, 

Is it possible to add the following Event:

    local procedure SaveInvoiceSpecification(var TempInvoicingSpecification: Record "Tracking Specification" temporary)
    begin
        TempInvoicingSpecification.Reset();
        if TempInvoicingSpecification.FindSet() then begin
            repeat
                TempInvoicingSpecification."Quantity Invoiced (Base)" += TempInvoicingSpecification."Quantity actual Handled (Base)";
                TempInvoicingSpecification."Quantity actual Handled (Base)" := 0;
                // DINNL <<
                OnbeforeSetTempTrackingSpecification(TempInvoicingSpecification);
                // DINNL >>
                TempTrackingSpecification := TempInvoicingSpecification;
                TempTrackingSpecification."Buffer Status" := TempTrackingSpecification."Buffer Status"::MODIFY;
                if not TempTrackingSpecification.Insert() then begin

    [IntegrationEvent(false, false)]
    local procedure OnbeforeSetTempTrackingSpecification(var TempInvoicingSpecification: Record "Tracking Specification" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
