### ISSUE TITLE
[Event Modification] codeunit 90 "Purch.-Post"  OnBeforePostPurchaseDoc

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13645]
Hello, 

Is it possible to add the following to an Event:

        OnBeforePostPurchaseDoc(Rec, PreviewMode, SuppressCommit, HideProgressWindow);

to 

        OnBeforePostPurchaseDoc(Rec, PreviewMode, SuppressCommit, HideProgressWindow, ItemJnlPostLine);

ItemJnlPostLine as var

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
