### ISSUE TITLE
[Event Request] codeunit 7304 "Whse. Jnl.-Register Batch" OnBeforeCreateReservEntryFor

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13656]
Hello, 

Is it possible to add the following Event:

        if WhseItemTrkgLine.FindSet then begin
            ItemJnlLine.Init();
            ItemJnlLine."Line No." := 0;
            ItemJnlLine.Validate("Entry Type", ItemJnlLine."Entry Type"::Transfer);
            with WhseJnlLine2 do begin
                repeat
                    if not WhseItemTrkgLine.HasSameNewTracking() or
                        (WhseItemTrkgLine."New Expiration Date" <> WhseItemTrkgLine."Expiration Date")
                    then begin
                        ReservEntry.CopyTrackingFromWhseItemTrackingLine(WhseItemTrkgLine);
                        // DINNL <<
                        OnBeforeCreateReservEntryFor(WhseJnlLine2, WhseItemTrkgLine);
                        // DINNL >>
                        CreateReservEntry.CreateReservEntryFor(
                          DATABASE::"Item Journal Line", ItemJnlLine."Entry Type".AsInteger(), '', '', 0, "Line No.", WhseItemTrkgLine."Qty. per Unit of Measure",
                          Abs(WhseItemTrkgLine."Qty. to Handle"), Abs(WhseItemTrkgLine."Qty. to Handle (Base)"), ReservEntry);
                        CreateReservEntry.SetNewTrackingFromNewWhseItemTrackingLine(WhseItemTrkgLine);
                        CreateReservEntry.SetDates(WhseItemTrkgLine."Warranty Date", WhseItemTrkgLine."Expiration Date");
                        CreateReservEntry.SetNewExpirationDate(WhseItemTrkgLine."New Expiration Date");
                        OnBeforeCreateReservEntry(WhseJnlLine2, WhseItemTrkgLine);
                        CreateReservEntry.CreateEntry(

   [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateReservEntryFor(var WhseJnlLine2: record "Warehouse Journal Line"; WhseItemTrkgLine: Record "Whse. Item Tracking Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
