### ISSUE TITLE
  [Event Request] codeunit 7304 "Whse. Jnl.-Register Batch"  OnCheckLinesOnAfterGetWhseItemTrkgSetup

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13657]
Hello, 

Is it possible to add the following Event:

                    UpdateTempBinContentBuffer(WhseJnlLine, "To Bin Code", true);
                if "Entry Type" in ["Entry Type"::"Negative Adjmt.", "Entry Type"::Movement] then
                    UpdateTempBinContentBuffer(WhseJnlLine, "From Bin Code", false);

                ItemTrackingMgt.GetWhseItemTrkgSetup("Item No.", WhseItemTrackingSetup);
                // DINNL <<
                OnCheckLinesOnAfterGetWhseItemTrkgSetup(WhseJnlLine, WhseItemTrackingSetup);
                // DINNL >>
                if WhseItemTrackingSetup.TrackingRequired() then begin
                    if WhseItemTrackingSetup."Serial No. Required" then
                        TestField("Qty. per Unit of Measure", 1);
                    if WhseJnlTemplate.Type <> WhseJnlTemplate.Type::"Physical Inventory" then
                        CreateTrackingSpecification(WhseJnlLine, TempTrackingSpecification)

    [IntegrationEvent(false, false)]
    local procedure OnCheckLinesOnAfterGetWhseItemTrkgSetup(WhseJnlLine: record "Warehouse Journal Line"; var WhseItemTrackingSetup: record "item tracking setup")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
