### ISSUE TITLE
[Event Request] codeunit 7307 "Whse.-Activity-Register" OnBeforeAutoreserve

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13659]
Hello, 

Is it possible to add the following Event:

                    TempReservEntryAfter.CopyFilters(TempReservEntryBefore);
                    TempReservEntryAfter.CalcSums(Quantity, "Quantity (Base)");

                    QtyToReserve :=
                      "Qty. to Handle" + (TempReservEntryAfter.Quantity - TempReservEntryBefore.Quantity);
                    QtyToReserveBase :=
                      "Qty. to Handle (Base)" + (TempReservEntryAfter."Quantity (Base)" - TempReservEntryBefore."Quantity (Base)");

                    if not IsSalesLineCompletelyReserved(SalesLine) and (QtyToReserve > 0) then begin
                        ReservMgt.SetReservSource(SalesLine);
                        ReservMgt.SetTrackingFromWhseActivityLine(TempWhseActivLineToReserve);
                        // DINNL <<
                        OnBeforeAutoreserve(TempWhseActivLineToReserve);
                        // DINNL >>
                        ReservMgt.AutoReserve(FullAutoReservation, '', SalesLine."Shipment Date", QtyToReserve, QtyToReserveBase);
                    end;
                until Next() = 0;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAutoreserve(var TempWhseActivLineToReserve: Record "Warehouse Activity Line" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
