### ISSUE TITLE
[Event Request] codeunit 7304 "Whse. Jnl.-Register Batch" OnBeforeCreateTrackingSpecification

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13655]
Hello, 

Is it possible to add the following Event:

    local procedure CreateTrackingSpecification(WhseJnlLine: Record "Warehouse Journal Line"; var TempHandlingSpecification: Record "Tracking Specification" temporary)
    var
        WhseItemTrkgLine: Record "Whse. Item Tracking Line";
        WhseItemTrackingSetup: Record "Item Tracking Setup";
        BinContent: Record "Bin Content";
        Location: Record Location;
        DINIsHandled: Boolean;
    begin
        // DINNL <<
	IsHandled := false;
        OnBeforeCreateTrackingSpecification(WhseJnlLine, IsHandled);
        if not IsHandled then
        // DINNL >>
        if (WhseJnlLine."Entry Type" = WhseJnlLine."Entry Type"::Movement) or
           (WhseJnlLine.Quantity < 0)
        then
            BinContent.Get(WhseJnlLine."Location Code", WhseJnlLine."From Bin Code", WhseJnlLine."Item No.",
              WhseJnlLine."Variant Code", WhseJnlLine."Unit of Measure Code");

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
