### ISSUE TITLE
[Event Request] codeunit 7307 "Whse.-Activity-Register" OnAfterSetQtyInWhseBase

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13658]
Hello, 

Is it possible to add the following Event:

          LocationGet("Location Code");
            if Location."Directed Put-away and Pick" or
               ("Activity Type" = "Activity Type"::"Invt. Movement")
            then begin
                WhseEntry.SetCurrentKey("Item No.", "Location Code", "Variant Code", "Bin Type Code");
                WhseEntry.SetRange("Item No.", "Item No.");
                WhseEntry.SetRange("Location Code", "Location Code");
                WhseEntry.SetRange("Variant Code", "Variant Code");
                SetTrackingFilterToWhseEntryIfRequired(WhseEntry, WhseItemTrackingSetup);
                WhseEntry.CalcSums("Qty. (Base)");
                QtyInWhseBase := WhseEntry."Qty. (Base)";
                // DINNL <<
                OnAfterSetQtyInWhseBase(WhseEntry, QtyInWhseBase, "Location Code");
                // DINNL >>

                BinTypeFilter := CreatePick.GetBinTypeFilter(0);
                if BinTypeFilter <> '' then
                    WhseEntry.SetFilter("Bin Type Code", '<>%1', BinTypeFilter); // Pick from all but Receive area
                WhseEntry.CalcSums("Qty. (Base)");
                QtyOnPickBinsBase := WhseEntry."Qty. (Base)";

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetQtyInWhseBase(var WarehouseEntry: Record "Warehouse Entry"; var QtyInWhseBase: Decimal; LocationCode: Code[10])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
