### ISSUE TITLE
[Event Request] codeunit 7302 "WMS Management" OnSetZoneAndBinsForConsumptionBeforeCheckQtyPicked

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13653]
Hello, 

Is it possible to add the following Event:

  with ItemJnlLine do
            if GetProdOrderCompLine(
                 ProdOrderCompLine, ProdOrderCompLine.Status::Released, "Order No.", "Order Line No.", "Prod. Order Comp. Line No.")
            then
                if Quantity > 0 then begin
                    WhseJnlLine."Entry Type" := WhseJnlLine."Entry Type"::"Negative Adjmt.";
                    WhseJnlLine."From Bin Code" := "Bin Code";
                    if Location."Bin Mandatory" and Location."Require Pick" and Location."Require Shipment" then begin
                        // DINNL <<
                        DINOnSetZoneAndBinsForConsumptionBeforeCheckQtyPicked(ItemJnlLine, ProdOrderCompLine);
                        // DINNL >>
                        if (ProdOrderCompLine."Planning Level Code" = 0) and
                           ((ProdOrderCompLine."Flushing Method" = ProdOrderCompLine."Flushing Method"::Manual) or
                            (ProdOrderCompLine."Flushing Method" = ProdOrderCompLine."Flushing Method"::"Pick + Backward") or
                            ((ProdOrderCompLine."Flushing Method" = ProdOrderCompLine."Flushing Method"::"Pick + Forward") and
                             (ProdOrderCompLine."Routing Link Code" <> '')))
                        then
                            CheckProdOrderCompLineQtyPickedBase(ProdOrderCompLine, ItemJnlLine);
                        GetBin("Location Code", WhseJnlLine."From Bin Code");

    [IntegrationEvent(false, false)]
    local procedure OnSetZoneAndBinsForConsumptionBeforeCheckQtyPicked(ItemJournalLine: Record "Item Journal Line"; var ProdOrderComponent: Record "Prod. Order Component")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
