### ISSUE TITLE
[Event Request] codeunit 7302 "WMS Management" OnCheckWhseJnlLineBlockChecks

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13654]
Hello, 

Is it possible to add the following Event (3 integration points):

  procedure CheckWhseJnlLine(var WhseJnlLine: Record "Warehouse Journal Line"; SourceJnl: Option " ",ItemJnl,OutputJnl,ConsumpJnl,WhseJnl; DecreaseQtyBase: Decimal; ToTransfer: Boolean)
    var
        BinContent: Record "Bin Content";
        ItemTrackingCode: Record "Item Tracking Code";
        QtyAbsBase: Decimal;
        IsHandled: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckWhseJnlLine(WhseJnlLine, SourceJnl, DecreaseQtyBase, ToTransfer, IsHandled);
        if IsHandled then
            exit;

        GetItem(WhseJnlLine."Item No.");
        with WhseJnlLine do begin
            TestField("Location Code");
            GetLocation("Location Code");
            OnCheckWhseJnlLineOnAfterGetLocation(WhseJnlLine, Location, Item);

            if SourceJnl = SourceJnl::WhseJnl then
                CheckAdjBinCode(WhseJnlLine);

            // DINNL <<
	    IsHandled := false;
            OnCheckWhseJnlLineBlockChecks(WhseJnlLine , IsHandled);
            if not IsHandled then
            // DINNL >>
            if ItemTrackingCode.Get(Item."Item Tracking Code") then begin
                if ("Serial No." <> '') and
                   ("From Bin Code" <> '') and
                   ItemTrackingCode."SN Specific Tracking" and
                   ("From Bin Code" <> Location."Adjustment Bin Code") and
                   (((Location."Adjustment Bin Code" <> '') and
                     ("Entry Type" = "Entry Type"::Movement)) or
                    (("Entry Type" <> "Entry Type"::Movement) or
                     ("Source Document" = "Source Document"::"Reclass. Jnl.")))
                then
                    CheckSerialNo(
                      "Item No.", "Variant Code", "Location Code", "From Bin Code",
                      "Unit of Measure Code", "Serial No.", CalcReservEntryQuantity());

                if ("Lot No." <> '') and
                   ("From Bin Code" <> '') and
                   ItemTrackingCode."Lot Specific Tracking" and
                   ("From Bin Code" <> Location."Adjustment Bin Code") and
                   (((Location."Adjustment Bin Code" <> '') and
                     ("Entry Type" = "Entry Type"::Movement)) or
                    (("Entry Type" <> "Entry Type"::Movement) or
                     ("Source Document" = "Source Document"::"Reclass. Jnl.")))
                then
                    CheckLotNo(
                      "Item No.", "Variant Code", "Location Code", "From Bin Code",
                      "Unit of Measure Code", "Lot No.", CalcReservEntryQuantity());

                OnCheckWhseJnlLineOnAfterCheckTracking(WhseJnlLine, ItemTrackingCode, Location);
            end;

            if "Entry Type" in ["Entry Type"::"Positive Adjmt.", "Entry Type"::Movement] then
                if SourceJnl = SourceJnl::" " then begin
                    CheckWhseDocumentToZoneCode(WhseJnlLine);
                    if "To Bin Code" = '' then
                        Error(
                          Text006,
                          FieldCaption("Bin Code"), "Whse. Document Type",
                          FieldCaption("Whse. Document No."), "Whse. Document No.",
                          FieldCaption("Line No."), "Whse. Document Line No.");
                end else
                    if ("Entry Type" <> "Entry Type"::Movement) or ToTransfer then begin
                        CheckToZoneCode(WhseJnlLine);
                        TestField("To Bin Code");
                    end;
            if "Entry Type" in ["Entry Type"::"Negative Adjmt.", "Entry Type"::Movement] then
                if SourceJnl = SourceJnl::" " then begin
                    if Location."Directed Put-away and Pick" and ("From Zone Code" = '') then
                        Error(
                          Text006,
                          FieldCaption("Zone Code"), "Whse. Document Type",
                          FieldCaption("Whse. Document No."), "Whse. Document No.",
                          FieldCaption("Line No."), "Whse. Document Line No.");
                    if "From Bin Code" = '' then
                        Error(
                          Text006,
                          FieldCaption("Bin Code"), "Whse. Document Type",
                          FieldCaption("Whse. Document No."), "Whse. Document No.",
                          FieldCaption("Line No."), "Whse. Document Line No.");
                end else
                    if ("Entry Type" <> "Entry Type"::Movement) or not ToTransfer then begin
                        if Location."Directed Put-away and Pick" then
                            TestField("From Zone Code");
                        TestField("From Bin Code");
                    end;

            QtyAbsBase := "Qty. (Absolute, Base)";
            IsHandled := false;
            OnCheckWhseJnlLineOnBeforeCheckBySourceJnl(WhseJnlLine, Bin, SourceJnl, BinContent, Location, DecreaseQtyBase, IsHandled);
            if not IsHandled then
                case SourceJnl of
                    SourceJnl::" ", SourceJnl::ItemJnl:
                        begin
                            // DINNL <<
			    IsHandled := false;
                            OnCheckIsDirectPutAwayBin(WhseJnlLine , IsHandled);
                            if not IsHandled then
                            // DINNL >>
                            if ("From Bin Code" <> '') and
                               ("From Bin Code" <> Location."Adjustment Bin Code") and
                               Location."Directed Put-away and Pick"
                            then begin
                                BinContent.Get(
                                  "Location Code", "From Bin Code",
                                  "Item No.", "Variant Code", "Unit of Measure Code");
                                BinContent.CheckDecreaseBinContent("Qty. (Absolute)", "Qty. (Absolute, Base)", DecreaseQtyBase);
                            end;

                            if ("To Bin Code" <> '') and
                               ("To Bin Code" <> Location."Adjustment Bin Code") and
                               Location."Directed Put-away and Pick"
                            then
                                if BinContent.Get(
                                     "Location Code", "To Bin Code",
                                     "Item No.", "Variant Code", "Unit of Measure Code")
                                then begin
                                    if ("Reference Document" = "Reference Document"::"Posted Rcpt.") or
                                       ("Reference Document" = "Reference Document"::"Posted Rtrn. Rcpt.") or
                                       ("Reference Document" = "Reference Document"::"Posted T. Receipt")
                                    then
                                        BinContent.CheckIncreaseBinContent(
                                          "Qty. (Absolute, Base)", 0, Cubage, Weight, Cubage, Weight, true, false)
                                    else
                                        BinContent.CheckIncreaseBinContent(
                                          "Qty. (Absolute, Base)", "Qty. (Absolute, Base)", Cubage, Weight, Cubage, Weight, true, false)
                                end else begin
                                    GetBin("Location Code", "To Bin Code");
                                    Bin.CheckIncreaseBin(
                                      Bin.Code, "Item No.", "Qty. (Absolute)", Cubage, Weight, Cubage, Weight, true, false);
                                end;
                        end;
                    SourceJnl::OutputJnl, SourceJnl::ConsumpJnl:
                        begin
                            if ("From Bin Code" <> '') and
                               Location."Directed Put-away and Pick"
                            then begin
                                BinContent.Get(
                                  "Location Code", "From Bin Code",
                                  "Item No.", "Variant Code", "Unit of Measure Code");
                                BinContent.CheckDecreaseBinContent("Qty. (Absolute)", "Qty. (Absolute, Base)", DecreaseQtyBase);
                            end;

                            if ("To Bin Code" <> '') and
                               Location."Directed Put-away and Pick"
                            then
                                if BinContent.Get(
                                     "Location Code", "To Bin Code",
                                     "Item No.", "Variant Code", "Unit of Measure Code")
                                then
                                    BinContent.CheckIncreaseBinContent(
                                      "Qty. (Absolute)", "Qty. (Absolute)", Cubage, Weight, Cubage, Weight, true, false)
                                else begin
                                    GetBin("Location Code", "To Bin Code");
                                    Bin.CheckIncreaseBin(
                                      Bin.Code, "Item No.", "Qty. (Absolute)", Cubage, Weight, Cubage, Weight, true, false);
                                end;
                        end;
                    SourceJnl::WhseJnl:
                        begin
                            // DINNL <<
			    IsHandled := false;
                            OnCheckIsDirectPutAwayBin(WhseJnlLine , IsHandled);
                            if not IsHandled then
                            // DINNL >>
                            if ("From Bin Code" <> '') and
                               ("From Bin Code" <> Location."Adjustment Bin Code") and
                               Location."Directed Put-away and Pick"
                            then begin
                                if not ItemTrackingMgt.GetWhseItemTrkgSetup("Item No.") then begin
                                    BinContent.Get(
                                      "Location Code", "From Bin Code",
                                      "Item No.", "Variant Code", "Unit of Measure Code");
                                    BinContent.CheckDecreaseBinContent("Qty. (Absolute)", "Qty. (Absolute, Base)", DecreaseQtyBase);
                                end;
                            end;
                            if ("To Bin Code" <> '') and
                               ("To Bin Code" <> Location."Adjustment Bin Code") and
                               Location."Directed Put-away and Pick"
                            then begin
                                GetBin("Location Code", "To Bin Code");
                                Bin.CheckWhseClass("Item No.", false);
                            end;
                        end;
                end;
            if QtyAbsBase <> "Qty. (Absolute, Base)" then begin
                Validate("Qty. (Absolute, Base)");
                Modify;
            end;
        end;

    [IntegrationEvent(false, false)]
    local procedure OnCheckIsDirectPutAwayBin(WhseJnlLine : Record Warehouse Journal Line; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
