### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" OnSetGlobalToQtyToPick

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13666]
Hello, 

Is it possible to add the following Event:

                        CreateTempActivityLine(
                            LocationCode, FromBinContent."Bin Code", UnitofMeasureCode, FromBinContent."Qty. per Unit of Measure",
                            FromQtyToPick, FromQtyToPickBase, 1, 0);
                        CreateTempActivityLine(
                            LocationCode, ToBinCode, UnitofMeasureCode, FromBinContent."Qty. per Unit of Measure",
                            ToQtyToPick, ToQtyToPickBase, 2, 0);

                        TotalAvailQtyToPickBase := TotalAvailQtyToPickBase - ToQtyToPickBase;
                        // DINNL <<
                        OnSetGlobalToQtyToPick(ToQtyToPick, ToQtyToPickBase);
                        // DINNL >>
                    end;
                end else
                    EnqueueCannotBeHandledReason(
                        GetMessageForUnhandledQtyDueToBin(
                            BinIsForPick, BinIsForReplenishment, Wh

    [IntegrationEvent(false, false)]
    local procedure OnSetGlobalToQtyToPick(ToQtytoPick: Decimal; ToQtytoPickBase: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
