### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick"OnSetTempWhseItemTrkgLineBeforeInsert

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13669]
Hello, 

Is it possible to add the following Event:

    local procedure CopyToTempWhseItemTrkgLine(WhseItemTrackingLine: Record "Whse. Item Tracking Line")
    begin
        with TempWhseItemTrackingLine do begin
            TempWhseItemTrackingLine := WhseItemTrackingLine;
            "Entry No." := LastWhseItemTrkgLineNo + 1;
            // DINNL <<
            OnSetTempWhseItemTrkgLineBeforeInsert(TempWhseItemTrackingLine);
            // DINNL >>
            TempWhseItemTrackingLine.Insert();
            LastWhseItemTrkgLineNo := "Entry No.";
            WhseItemTrkgExists := true;
            WhseItemTrkgLineCount += 1;
        end;
    end;

   [IntegrationEvent(false, false)]
    local procedure OnSetTempWhseItemTrkgLineBeforeInsert(var TempWhseItemTrackingLine: Record "Whse. Item Tracking Line" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
