### ISSUE TITLE
[Event Request] codeunit 7322 "Create Inventory Pick/Movement" OnAfterCalcAvailQtyToPick

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13662]
Hello, 

Is it possible to add the following Event:

                    if not ((EntrySummary."Serial No." <> '') and (QtyTracked > 0)) then begin
                        if Location."Bin Mandatory" then
                            TotalAvailQtyToPickBase :=
                              CalcQtyAvailToPickOnBins(WhseActivLine, WhseItemTrackingSetup, RemQtyToPickBase)
                        else
                            TotalAvailQtyToPickBase := CalcInvtAvailability(WhseActivLine, WhseItemTrackingSetup);
                        // DINNL <<
                        OnAfterCalcAvailQtyToPick(WhseActivLine."Item No.", WhseActivLine."Variant Code", WhseActivLine."Bin Code", EntrySummary, TotalAvailQtyToPickBase);
                        // DINNL >>

                        TotalAvailQtyToPickBase := TotalAvailQtyToPickBase - QtyTracked;
                        QtyToPickBase := 0;

                        OnAfterCalcTotalAvailQtyToPickBase(

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcAvailQtyToPick(ItemNo: Code[20]; VariantCode: Code[10]; BinCode: Code[20]; EntrySummary: Record "Entry Summary"; var TotalAvailQtyToPickBase: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
