### ISSUE TITLE
[Event Request] codeunit 7307 "Whse.-Activity-Register" OnAfterRegisterWhseActivityLines

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13661]
Hello, 

Is it possible to add the following Event:

                    if "Qty. to Handle (Base)" > QtyBaseDiff then // round off error- qty same, not base qty
                        "Qty. to Handle (Base)" := QtyBaseDiff;
                    if HideDialog then
                        Validate("Qty. to Handle", 0);
                    Validate("Qty. Handled", Quantity - "Qty. Outstanding");
                    OnBeforeWhseActivLineModify(WarehouseActivityLine);
                    Modify;
                end;
            until Next() = 0;
        end;
        // DIN <<
        OnAfterRegisterWhseActivityLines(WarehouseActivityLine);
        // DIN >>
    end;

    local procedure UpdateWhseActivLineQtyOutstanding(var WarehouseActivityLine: Record "Warehouse Activity Line"; QtyDiff: Decimal; QtyBaseDiff: Decimal)
    var
        IsHandled: Boolean;
    begin

    [IntegrationEvent(false, false)]
    local procedure OnAfterRegisterWhseActivityLines(var WarehouseActivityLine: Record "Warehouse Activity Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
