### ISSUE TITLE
[Event Request] codeunit 7322 "Create Inventory Pick/Movement" OnAfterItemTrackedQuantity

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13663]
Hello, 

Is it possible to add the following Event:

            repeat
                WhseItemTrackingSetup.CopyTrackingFromEntrySummary(EntrySummary);
                if EntrySummary."Expiration Date" <> 0D then begin
                    QtyTracked := ItemTrackedQuantity(WhseItemTrackingSetup);
                    // DINNL <<
                    OnAfterItemTrackedQuantity(EntrySummary, QtyTracked, TempHandlingSpecification);
                    // DINNL >>
                    if not ((EntrySummary."Serial No." <> '') and (QtyTracked > 0)) then begin
                        if Location."Bin Mandatory" then
                            TotalAvailQtyToPickBase :=
                              CalcQtyAvailToPickOnBins(WhseActivLine, WhseItemTrackingSetup, RemQtyToPickBase)
                        else

    [IntegrationEvent(false, false)]
    local procedure OnAfterItemTrackedQuantity(EntrySummary: Record "Entry Summary"; var QuantityTracked: Decimal; var TempHandlingSpecification: Record "Tracking Specification" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
