### ISSUE TITLE
[Event Request] codeunit 7322 "Create Inventory Pick/Movement" OnAfterWhseItemTrackingFEFOSetSource

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13664]
Hello, 

Is it possible to add the following Event:

        if Location."Bin Mandatory" then
            if not IsItemOnBins(WhseActivLine) then
                exit;

        WhseItemTrackingFEFO.SetSource(
          WhseActivLine."Source Type", WhseActivLine."Source Subtype", WhseActivLine."Source No.",
          WhseActivLine."Source Line No.", WhseActivLine."Source Subline No.");
        // DINNL <<
        OnAfterWhseItemTrackingFEFOSetSource(WhseItemTrackingFEFO, WhseActivLine, WhseRequest, DINHURequired);
        // DINNL >>
        WhseItemTrackingFEFO.CreateEntrySummaryFEFO(Location, WhseActivLine."Item No.", WhseActivLine."Variant Code", true);
        if WhseItemTrackingFEFO.FindFirstEntrySummaryFEFO(EntrySummary) then begin
            InitTempHandlingSpec;
            RemQtyToPickBase := TotalQtyToPickBase;
            repeat

    [IntegrationEvent(false, false)]
    local procedure OnAfterWhseItemTrackingFEFOSetSource(var WhseItemTrackingFEFO: Codeunit "Whse. Item Tracking FEFO"; WarehouseActivityLine: Record "Warehouse Activity Line"; WarehouseRequest: Record "Warehouse Request"; HURequired: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
