### ISSUE TITLE
[Event Request] codeunit 7307 "Whse.-Activity-Register" OnBeforeRegisterWhseActivityLines

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13660]
Hello, 

Is it possible to add the following Event:

        OnAfterRegisterWhseActivity(WhseActivHeader);
    end;

    local procedure RegisterWhseActivityLines(var WarehouseActivityLine: Record "Warehouse Activity Line"; var TempWhseActivLineToReserve: Record "Warehouse Activity Line" temporary; var TempWhseActivityLineGrouped: Record "Warehouse Activity Line" temporary)
    var
        QtyDiff: Decimal;
        QtyBaseDiff: Decimal;
        SkipDelete: Boolean;
    begin
        // DIN <<
        OnBeforeRegisterWhseActivityLines(WarehouseActivityLine);
        // DIN >>
        with WarehouseActivityLine do begin
            if not FindSet then
                exit;

            repeat
                LineCount := LineCount + 1;
                UpdateWindow(3, '');
                UpdateWindow(4, '');
                if Location."Bin Mandatory" then
                    RegisterWhseJnlLine(WarehouseActivityLine);

    [IntegrationEvent(false, false)]
    local procedure OnBeforeRegisterWhseActivityLines(var WarehouseActivityLine: Record "Warehouse Activity Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
