### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" OnCreateTempItemTrkgLinesCalcQtyToPickBase

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13674]
[Event Request] codeunit 7312 "Create Pick"

Hello, 

Is it possible to add the following Event:

                        if TotalAvailQtyToPickBase > 0 then
                            if TotalAvailQtyToPickBase >= RemQtyToPickBase then begin
                                QtyToPickBase := RemQtyToPickBase;
                                RemQtyToPickBase := 0
                            end else begin
                                QtyToPickBase := TotalAvailQtyToPickBase;
                                RemQtyToPickBase := RemQtyToPickBase - QtyToPickBase;
                            end;

                        // DINNL <<
                        OnCreateTempItemTrkgLinesCalcQtyToPickBase(ItemNo, VariantCode, Location.Code, EntrySummary, TotalAvailQtyToPickBase, QtyToPickBase);
                        // DINNL >>
                        if QtyToPickBase > 0 then
                            InsertTempItemTrkgLine(Location.Code, ItemNo, VariantCode, EntrySummary, QtyToPickBase);

    [IntegrationEvent(false, false)]
    local procedure OnCreateTempItemTrkgLinesCalcQtyToPickBase(ItemNo: Code[20]; VariantCode: Code[10]; LocationCode: Code[10]; EntrySummary: Record "Entry Summary"; TotalAvailQtyToPickBase: Decimal; var QtytoPickBase: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
