### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" OnCalcPickQtyAssignedBeforeTempWhseActivLineCalcsums

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13677]
Hello, 

Is it possible to add the following Event:

            end;
            SetRange("Variant Code", VariantCode);
            if UOMCode <> '' then
                SetRange("Unit of Measure Code", UOMCode);
            SetRange("Activity Type", "Activity Type");
            SetRange("Breakbulk No.", 0);
            if WhseItemTrkgExists then begin // DINNL
                SetTrackingFilterFromWhseItemTrackingLineIfNotBlank(TempWhseItemTrackingLine);
                // DINNL <<
                OnCalcPickQtyAssignedBeforeTempWhseActivLineCalcsums(TempWhseActivLine, TempWhseItemTrackingLine);
                // DINNL >>
            end; // DINNL
            CalcSums("Qty. Outstanding (Base)");
            PickQtyAssigned := "Qty. Outstanding (Base)";
        end;
        TempWhseActivLine.Copy(WhseActivLine2);
        exit(PickQtyAssigned);
    end;

    local procedure CalcQtyAssignedToPick(ItemNo: Code[20]; LocationCode: Code[10]; VariantCode: Code[10]; BinCode: Code[20]; WhseItemTrackingSetup: Record "Item Tracking Setup"): Decimal
    var

    [IntegrationEvent(false, false)]
    local procedure DINOnCalcPickQtyAssignedBeforeTempWhseActivLineCalcsums(var TempWhseActivLine: Record "Warehouse Activity Line" temporary; TempWhseItemTrackingLine: Record "Whse. Item Tracking Line" temporary)
    begin
    end;

**Comment by Oleg-Romashkov** [comment]
Hi Lee,

Seems you can use existent event OnAfterSetTrackingFilterFromWhseItemTrackingLineIfNotBlank of the table 5767 "Warehouse Activity Line" with exactly the same signature.

Is it ok?

**Comment by leegeurts** [comment]
Hey Oleg, 

I believe you are right here as well :) 
Gonna try it there first 

Thank you
