### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" OnCreateTempItemTrkgLinesOnAfterQtyTracked

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13672]
Hello, 

Is it possible to add the following Event:

        RemQtyToPickBase := TotalQtyToPickBase;
        if HasExpiryDate then
            TransferRemQtyToPickBase := TotalQtyToPickBase;
        if WhseItemTrackingFEFO.FindFirstEntrySummaryFEFO(EntrySummary) then begin
            ReqFEFOPick := true;
            repeat
                if ((EntrySummary."Expiration Date" <> 0D) and HasExpiryDate) or
                   ((EntrySummary."Expiration Date" = 0D) and (not HasExpiryDate))
                then begin
                    WhseItemTrackingSetup.CopyTrackingFromEntrySummary(EntrySummary);
                    QtyTracked := ItemTrackedQuantity(WhseItemTrackingSetup);

                    // DINNL <<
                    OnCreateTempItemTrkgLinesOnAfterQtyTracked(EntrySummary, TempWhseItemTrackingLine, QtyTracked);
                    // DINNL >>
                    if not ((EntrySummary."Serial No." <> '') and (QtyTracked > 0)) then begin
                        WhseItemTrackingLine.CopyTrackingFromEntrySummary(EntrySummary);
                        TotalAvailQtyToPickBase :=
                            CalcTotalAvailQtyToPick(
                                Location.Code, ItemNo, VariantCode, WhseItemTrackingLine,
                                SourceType, SourceSubType, SourceNo, SourceLineNo, SourceSubLineNo, 0, HasExpiryDate);

    [IntegrationEvent(false, false)]
    local procedure OnCreateTempItemTrkgLinesOnAfterQtyTracked(EntrySummary: Record "Entry Summary"; var TempWhseItemTrackingLine: Record "Whse. Item Tracking Line" temporary; var QuantityTracked: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
