### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" OnCreateTempItemTrkgLinesOnAfterCalcTotalAvailQtyToPick

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13673]
Hello, 

Is it possible to add the following Event: 

if not ((EntrySummary."Serial No." <> '') and (QtyTracked > 0)) then begin
                        WhseItemTrackingLine.CopyTrackingFromEntrySummary(EntrySummary);
                        TotalAvailQtyToPickBase :=
                            CalcTotalAvailQtyToPick(
                                Location.Code, ItemNo, VariantCode, WhseItemTrackingLine,
                                SourceType, SourceSubType, SourceNo, SourceLineNo, SourceSubLineNo, 0, HasExpiryDate);

                        // DINNL <<
                        OnCreateTempItemTrkgLinesOnAfterCalcTotalAvailQtyToPick(EntrySummary, ItemNo, VariantCode, '', TotalAvailQtyToPickBase);
                        // DINNL >>
                        if CalledFromWksh and (WhseWkshLine."From Bin Code" <> '') then begin
                            FromBinContentQty :=
                                GetFromBinContentQty(
                                    WhseWkshLine."Location Code", WhseWkshLine."From Bin Code", WhseWkshLine."Item No.",
                                    WhseWkshLine."Variant Code", WhseWkshLine."From Unit of Measure Code", WhseItemTrackingLine);
                            if TotalAvailQtyToPickBase > FromBinContentQty then
                                TotalAvailQtyToPickBase := FromBinContentQty;
                        end;

    [IntegrationEvent(false, false)]
    local procedure OnCreateTempItemTrkgLinesOnAfterCalcTotalAvailQtyToPick(EntrySummary: Record "Entry Summary"; ItemNo: Code[20]; VariantCode: Code[10]; BinCode: Code[20]; var TotalAvailQtyToPickBase: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
