### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" OnCreateTempActivityLineAfterValidateQuantity

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13678]
Hello, 

Is it possible to add the following Event:

          Validate(Quantity, QtyToPick);
            if QtyToPickBase <> 0 then begin
                "Qty. (Base)" := QtyToPickBase;
                "Qty. to Handle (Base)" := QtyToPickBase;
                "Qty. Outstanding (Base)" := QtyToPickBase;
            end;

            // DINNL <<
            OnCreateTempActivityLineAfterValidateQuantity(TempWhseActivLine);
            // DINNL >>
            case WhseSource of
                WhseSource::Shipment:
                    begin
                        "Shipping Agent Code" := ShippingAgentCode;
                        "Shipping Agent Service Code" := ShippingAgentServiceCode;
                        "Shipment Method Code" := ShipmentMethodCode;
                        "Shipping Advice" := "Shipping Advice";
                    end;
                WhseSource::Production, WhseSource::Assembly:
                    if "Shelf No." = '' then begin
                        Item."No." := "Item No.";
                        Item.ItemSKUGet(Item, "Location Code", "Variant Code");
                        "Shelf No." := Item."Shelf No.";
                    end;
                WhseSource::"Movement Worksheet":

    [IntegrationEvent(false, false)]
    local procedure OnCreateTempActivityLineAfterValidateQuantity(var TempWhseActivLine: Record "Warehouse Activity Line" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
