### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" OnCreateTempActivityLineAfterAssignSpecEquipment

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13675]
Hello, 

Is it possible to add the following Event: 

           if (LocationCode <> '') and (BinCode <> '') then begin
                GetBin(LocationCode, BinCode);
                Dedicated := Bin.Dedicated;
            end;
            if Location."Directed Put-away and Pick" then begin
                "Zone Code" := Bin."Zone Code";
                "Bin Ranking" := Bin."Bin Ranking";
                "Bin Type Code" := Bin."Bin Type Code";
                if Location."Special Equipment" <> Location."Special Equipment"::" " then
                    "Special Equipment Code" :=
                      AssignSpecEquipment(LocationCode, BinCode, "Item No.", "Variant Code");
                // DINNL <<
                OnCreateTempActivityLineAfterAssignSpecEquipment(TempWhseActivLine, QtyToPick);
                // DINNL >>
            end;

            Validate(Quantity, QtyToPick);
            if QtyToPickBase <> 0 then begin
                "Qty. (Base)" := QtyToPickBase;
                "Qty. to Handle (Base)" := QtyToPickBase;
                "Qty. Outstanding (Base)" := QtyToPickBase;
            end;

    [IntegrationEvent(false, false)]
    local procedure OnCreateTempActivityLineAfterAssignSpecEquipment(var TempWhseActivLine: Record "Warehouse Activity Line" temporary; QtyToPick: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
