### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" OnAfterSetTempWhseItemTrkgLine

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13670]
Hello, 

Is it possible to add the following Event:

    local procedure SetSourceWhseItemTrkgLine(SourceID: Code[20]; SourceType: Integer; SourceBatchName: Code[10]; SourceProdOrderLine: Integer; SourceRefNo: Integer)
    begin
        SourceWhseItemTrackingLine.Init();
        SourceWhseItemTrackingLine."Source Type" := SourceType;
        SourceWhseItemTrackingLine."Source ID" := SourceID;
        SourceWhseItemTrackingLine."Source Batch Name" := SourceBatchName;
        SourceWhseItemTrackingLine."Source Prod. Order Line" := SourceProdOrderLine;
        SourceWhseItemTrackingLine."Source Ref. No." := SourceRefNo;
        // DINNL <<
        OnAfterSetTempWhseItemTrkgLine(TempWhseItemTrackingLine, LastWhseItemTrkgLineNo);
        // DINNL >>
    end;

    [IntegrationEvent(false, false)]
    local procedure DINOnAfterSetTempWhseItemTrkgLine(var TempWhseItemTrackingLine: Record "Whse. Item Tracking Line" temporary; var LastWhseItemTrkgLineNo: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
