### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" DINOnFindPickBinCheck

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13676]
Hello, 

Is it possible to add the following Event:

            TotalAvailQtyToPickBase :=
                CalcTotalAvailQtyToPick(
                    LocationCode, ItemNo, VariantCode, TempWhseItemTrackingLine,
                    SourceType, SourceSubType, SourceNo, SourceLineNo, SourceSubLineNo, TotalQtytoPickBase, false);
            if TotalAvailQtyToPickBase < 0 then
                TotalAvailQtyToPickBase := 0;

                // DINNL <<
                DINOnFindPickBinCheck(TempWhseItemTrackingLine, TotalAvailQtyToPickBase);
                // DINNL >>
            repeat
                BinIsForPick := UseForPick(FromBinContent) and (WhseSource <> WhseSource::"Movement Worksheet");
                BinIsForReplenishment := UseForReplenishment(FromBinContent) and (WhseSource = WhseSource::"Movement Worksheet");
                if FromBinContent."Bin Code" <> ToBinCode then

    [IntegrationEvent(false, false)]
    local procedure DINOnFindPickBinCheck(TempWhseItemTrackingLine: Record "Whse. Item Tracking Line" temporary; var TotalAvailQtyToPickBase: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
