### ISSUE TITLE
[Event Request] T352 "Default Dimension" - procedure UpdateGlobalDimCode()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#13680]
------- Change the procedure from local to global ---------
procedure UpdateGlobalDimCode(GlobalDimCodeNo: Integer; TableID: Integer; AccNo: Code[20]; NewDimValue: Code[20])

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
