### ISSUE TITLE
[Event Request/Change] Codeunit 7312 "Create Pick"

### ISSUE THREAD

**Issue by GaryFrostick2** [microsoft/ALAppExtensions#13686]
The current events around  Codeunit 7312 "Create Pick" are very limiting in terms of influencing the bin to pick from. This issue is caused by the call to a function within the Bin Content table with returns a filtered set of Bin Content records from which top pick from. This is called within procedures FindPickBin, FindBreakBulkBin and FIndSmallerUOMBin. This function is not called from any other codeunits.

Whilst there is currently an event in the GetBinContent, the approach here gives a number of issues:
1) The  QuantityToPickBase  is not passed to the function. It is impossible to decide the best bin without knowing the quantity.
2) there is no way in the current event of really knowing what bin we are trying to find (i.e. BreakBulk)
3) As we can't create a key across standard and bespoke fields it is not always possible to return the bin content records in the correct order. 

To handle points 1 and 2 I would like to request new events before the 3 calls to GetBinContent with a handled pattern. This would allow us to know why it was called and also include QuantityToPickBase.

procedure FindPickBin

OnBeforeFindPickBinGetBinContent(ItemNo, VariantCode, UnitofMeasureCode, LocationCode, ToBinCode, CrossDock,
            WhseSource, WhseItemTrkgExists, WhseItemTrackingSetup, TotalQtytoPickBase, IsHandled);
if not IsHandled then
  FromBinContent.GetBinContent(
            ItemNo, VariantCode, UnitofMeasureCode, LocationCode, ToBinCode, CrossDock,
            WhseSource = WhseSource::"Movement Worksheet", WhseItemTrkgExists, WhseItemTrackingSetup);
if Not FromBinContent.IsEmpty then....

with the equivalent in FindBreakBulkBin and FIndSmallerUOMBin.

Point 3 is harder to achieve without code refactoring. What I would ideally like to see is FromBinContent being changed to a temporary record which is populated in the GetBinContent fucntion.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
