### ISSUE TITLE
[Event Request] Codeunit 370 "Bank Acc. Reconciliation Post"

### ISSUE THREAD

**Issue by AlexxBenn** [microsoft/ALAppExtensions#13687]
Hi Team,

**BC version** - 18.3.27240.27381;
**codeunit** - 370 "Bank Acc. Reconciliation Post" ;
**procedure** - TransferToPostPmtAppln (the same event could be adde to the similar function TransferToBankStmt);

We would like to have an event (for example OnBeforePostedPmtReconLineInsert) before inserting "Posted Payment Recon. Line" from "Bank Acc. Reconciliation Line" while posting Payment Reconciliation Jnl. to have more control.
![image](https://user-images.githubusercontent.com/62009673/127635704-84fe8593-0bbf-486b-9b4e-575245337c5a.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostedPmtReconLineInsert(var PostedPmtReconLine: Record "Posted Payment Recon. Line"; BankAccReconLine: Record "Bank Acc. Reconciliation Line")
    begin
    end;

**Comment by Oleg-Romashkov** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by AlexxBenn** [comment]
> You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

Got it, will follow this rule in future requests.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
