### ISSUE TITLE
[Request for Protected Variable] Page 99000887 "Work Center Load"

### ISSUE THREAD

**Issue by GaryFrostick2** [microsoft/ALAppExtensions#13682]
Can the Variables PeriodType and AmountType be made protected on page 99000887 Work Center Load?

This variables are user set on the page as fields so it would be deniable to be able to see what the user has set for extensibility.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
