### ISSUE TITLE
[Event-Request] Codeunit 378 TransferExtendedText Function InsertSalesExtTextRetLast

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#13688]
Hi,

we would like the event OnBeforeToSalesLineInsert to be changed to Handler pattern, so we can skip the insert.
![image](https://user-images.githubusercontent.com/41729653/127637410-f5c2f69b-9f93-4dfe-8de9-5b466b0387d7.png)

Thanks in advance.

**Comment by Oleg-Romashkov** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
