### ISSUE TITLE
[Event Request] CodeUnit 1535 "Approvals Mgmt." - OnCheckPurchaseApprovalPossibleOnBeforeCheckPurchaseHeader

### ISSUE THREAD

**Issue by VPaas2** [microsoft/ALAppExtensions#13685]
```


    procedure CheckPurchaseApprovalPossible(var PurchaseHeader: Record "Purchase Header"): Boolean
    begin
        if not IsPurchaseApprovalsWorkflowEnabled(PurchaseHeader) then
            Error(NoWorkflowEnabledErr);

	IsHandled := false;
	OnCheckPurchaseApprovalPossibleOnBeforeCheckPurchaseHeader(PurchaseHeader);
        if IsHandled then
            exit(true);

        if not PurchaseHeader.PurchLinesExist then
            Error(NothingToApproveErr);

        OnAfterCheckPurchaseApprovalPossible(PurchaseHeader);

        exit(true);
    end;




    [IntegrationEvent(false, false)]
    local procedure OnCheckPurchaseApprovalPossibleOnBeforeCheckPurchaseHeader(PurchaseHeader: Record PurchaseHeader; var IsHandled: Boolean)
    end;

```

**Comment by db-bc** [comment]
Do you mean `exit();` to be `exit(false);`? or `true`? or perhaps should subscribers get passed the result as `var`, so they can set whether approval is possible or not?

**Comment by VPaas2** [comment]
> 
> 
> Do you mean `exit();` to be `exit(false);`? or `true`? or perhaps should subscribers get passed the result as `var`, so they can set whether approval is possible or not?

Thank you for the reply. I have updated the statement to exit(true)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
