### ISSUE TITLE
Preview posting happening with same Posted Document No.

### ISSUE THREAD

**Issue by paragpardhi123** [microsoft/ALAppExtensions#13696]
Hi,
In D365 Business Central 18.0 if we perform ‘Preview Posting” on a transaction, in our case a Sales Invoice, the posting window pops up and it shows that the posted transaction is getting posted with *** as document no.
 
![image](https://user-images.githubusercontent.com/33540581/127655087-cc378607-c7a9-44a0-95c4-1913ad7af9ce.png)

But if Invoice Nos. and Posted Invoice Nos. have the same No. Series in the Sales & Receivable Setup, then the document no. is taken from the No. Series instead of *** while performing Preview Posting.
 
![image](https://user-images.githubusercontent.com/33540581/127655106-b77ae7ff-d3f7-4730-bedf-0caa178c1942.png)

This difference in the behavior is causing extension workflow failure if the user performs Preview posting on an environment where our extension is installed.
So, is this behavior expected and being introduced by Microsoft on purpose?

If this is expected behavior then please add a parameter "PreviewMode" in Event OnFinalizeInvoicePostingSalesTax under Codeunit 80 Sales-Post.

Version: US Business Central 18.3 (Platform 18.0.27224.28087 + Application 18.3.27240.27381)

Regards,
Parag Pardhi

**Comment by db-bc** [comment]
I dunno but guess it's because if you are using a different No Series for the Posted docs, if you Preview and then wait a while before really Posting, you can get a different Doc No than was previewed, because others users took the earlier numbers in the same series

**Comment by chavansachin20** [comment]
Thanks @AlexanderYakunin for accepting this as extensibility-bug.

Now, can you please provide ETA and in which version we should expect fix for this bug. This will help us to relay information to our Customer / Partner.

@paragpardhi123 : cc

**Comment by AlexanderYakunin** [comment]
Labelling request does not mean this is accepted as a bug, this is just for classification purpose. This forum is not for reporting bugs, but for asking for extensibility improvements. 

If you need to report a bug and get hotfix, please create request via technical support, they will validate and repro your case and confirm acceptance. In this case you will have SLA and it will be fixed in supported versions.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Strictly speaking, this one shouldn't have gotten labeled as an extensibility-bug, as it wasn't one. Bugs are to be logged through our support channels, ideas are to be logged through aka.ms/bcideas, while GitHub is for extensibility requests/issues and open sourced code only. However, this one seems to have slipped through the process cracks and will now ship with BC 19 🥳
