### ISSUE TITLE
 [Event Request] Report 11000000 "Get Proposal Entries"

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13698]
Dear ALAppExtensions Team,

Is it possible to add an event in Report 11000000 "Get Proposal Entries" OnPreReport?

        if CopyStr(CompanyName, 1, 6) <> Text1000001 then
            if "Value Date" - Today > 14 then
                if not Confirm(
                     StrSubstNo(
                       Text1000002 +
                       Text1000003 +
                       Text1000004,
                       "Value Date" - Today), false)
                then
                    Error(Text1000005);
        // DINNL <<
        DINOnPreReportCheckAccountTypeFilterIsNotEmpty(TransactionmodeTable);
        // DINNL >>

        BatchStatus.Open(Text1000006 + Text1000007);

       local procedure DINOnPreReportCheckAccountTypeFilterIsNotEmpty(var TransactionMode: Record "Transaction Mode")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
