### ISSUE TITLE
[Event Request] codeunit 5760 "Whse.-Post Receipt". - Change parameter to var for event OnInitSourceDocumentLinesOnAfterSourceTransLineFound 

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13693]
Dear ALAppExtensions Team,

Is it possible to change the parameter ModifyLine of the event OnInitSourceDocumentLinesOnAfterSourceTransLineFound in  codeunit 5760 "Whse.-Post Receipt" to var?

 -local procedure OnInitSourceDocumentLinesOnAfterSourceTransLineFound(var TransferLine: Record "Transfer Line"; WhseRcptLine: Record "Warehouse Receipt Line"; ModifyLine: Boolean)
+local procedure OnInitSourceDocumentLinesOnAfterSourceTransLineFound(var TransferLine: Record "Transfer Line"; WhseRcptLine: Record "Warehouse Receipt Line"; var ModifyLine: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
