### ISSUE TITLE
[Function Request] Page 232 - Apply Customer Entries - GetApplnCurrencyCode

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#1369]
Dear ALAppExtensions,

Through this issue we would like to request the following procedure to be added in page 232 Apply Customer Entries:
```
[External] GetApplnCurrencyCode() : Code[10]
EXIT(ApplnCurrencyCode)
```
so that we have the `ApplnCurrencyCode` available for use in page-extensions.

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
