### ISSUE TITLE
codeunit "Reminder-Make" add new event OnAfterReminderLevelProcessed

### ISSUE THREAD

**Issue by tyurm** [microsoft/ALAppExtensions#13695]
Hello,

Could you please add new event to codeunit "Reminder-Make" , procedure MakeReminder:

![image](https://user-images.githubusercontent.com/45788765/127653772-a552ce4e-de92-43be-9d88-27010072db0e.png)

Event Call:

`OnAfterReminderLevelProcessed(ReminderLevel, NextLineNo, StartLineInserted);`

Event Declaration:
`    [IntegrationEvent(false, false)]
    local procedure OnAfterReminderLevelProcessed(var ReminderLevel: Record "Reminder Level"; var NextLineNo: Integer; StartLineInserted: Boolean)
    begin
    end;`

Thank you in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
