### ISSUE TITLE
codeunit "Reminder-Make" event OnCodeOnBeforeCurrencyLoop additional parameter request

### ISSUE THREAD

**Issue by tyurm** [microsoft/ALAppExtensions#13694]
Hello,

Is it possible to add "Currency" parameter to OnCodeOnBeforeCurrencyLoop ?

Event call:
`OnCodeOnBeforeCurrencyLoop(CustLedgEntry, ReminderHeaderReq, ReminderTerms, OverdueEntriesOnly, IncludeEntriesOnHold, HeaderExists, CustLedgEntryLastIssuedReminderLevelFilter, Currency);`
Event declaration:
`    [IntegrationEvent(false, false)]
    local procedure OnCodeOnBeforeCurrencyLoop(CustLedgEntry: Record "Cust. Ledger Entry"; ReminderHeaderReq: Record "Reminder Header"; ReminderTerms: Record "Reminder Terms"; OverdueEntriesOnly: Boolean; IncludeEntriesOnHold: Boolean; HeaderExists: Boolean; CustLedgEntryLastIssuedReminderLevelFilter: Text; var Currency: Record Currency temporary)
    begin
    end;`

Thank you in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
