### ISSUE TITLE
codeunit "Cancel Issued Reminder" add event OnAfterCheckIssuedReminder

### ISSUE THREAD

**Issue by tyurm** [microsoft/ALAppExtensions#13697]
Hello,

Please add event OnAfterCheckIssuedReminder to codeunit "Cancel Issued Reminder", procedure CheckIssuedReminder:
![image](https://user-images.githubusercontent.com/45788765/127656198-7df785a2-70fc-4ef5-abbb-de5722e032c5.png)

Event Call:
` 
OnAfterCheckIssuedReminder(IssuedReminderHeader, SkipShowNotification, TempErrorMessage, Result, IsHandled);
if IsHandled then
   exit(Result);
`

Event Declaration:
`[IntegrationEvent(false, false)]
local procedure OnAfterCheckIssuedReminder(IssuedReminderHeader: Record "Issued Reminder Header"; SkipShowNotification: boolean; var TempErrMessage: Record "Error Message" temporary; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;`

Thank you in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
