### ISSUE TITLE
[Event Request] report 7305 "Whse.-Source - Create Document" OnSetQuantity

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13708]
Hello, 

Is it possible to get the following event

if FindFirst then begin
                // DINNL <<
                OnSetQuantity(PostedWhseRcptLine, WhseItemTrackingLine);
                // DINNL >>
                if QtyToHandleBase < "Qty. to Handle (Base)" then
                    PostedWhseRcptLine."Qty. (Base)" := QtyToHandleBase
                else
                    PostedWhseRcptLine."Qty. (Base)" := "Qty. to Handle (Base)";
                QtyToHandleBase -= PostedWhseRcptLine."Qty. (Base)";
                PostedWhseRcptLine.Quantity :=
                  Round(PostedWhseRcptLine."Qty. (Base)" / PostedWhseRcptLine."Qty. per Unit of Measure", UOMMgt.QtyRndPrecision);
            end;
        end;

    [IntegrationEvent(false, false)]
    local procedure OnSetQuantity(var PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; var WhseItemTrackingLine: Record "Whse. Item Tracking Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
