### ISSUE TITLE
[Event Request] Report 7318 "Whse.-Shipment - Create Pick" - OnPreDataItem

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13707]
Dear ALAppExtensions Team,

Is it possible to add an event (with sender included) in Report 7318 "Whse.-Shipment - Create Pick" - OnPreDataItem

     trigger OnPreDataItem()
            var
                IsHandled: Boolean;
            begin
                // DINNL <<
		    IsHandled := false;
                OnBeforeCreatePickSetValues(AssignedID, 1, SortActivity, 1, 0, 0, false, DoNotFillQtytoHandle, BreakbulkFilter, false, CreatePick, IsHandled);
                if not IsHandled then
                // DINNL >>
                CreatePick.SetValues(
                  AssignedID, 1, SortActivity, 1, 0, 0, false, DoNotFillQtytoHandle, BreakbulkFilter, false);

                CopyFilters(WhseShptLine);
                SetFilter("Qty. (Base)", '>0');
            end;

     local procedure OnBeforeCreatePickSetValues(AssignedID2: Code[50]; WhseDocument2: Option "Pick 
       Worksheet",Shipment,"Movement Worksheet","Internal Pick",Production,Assembly; SortPick2: Enum "Whse. Activity Sorting 
       Method"; WhseDocType2: Option "Put-away",Pick,Movement; MaxNoOfSourceDoc2: Integer; MaxNoOfLines2: Integer; 
       PerZone2: Boolean; DoNotFillQtytoHandle2: Boolean; BreakbulkFilter2: Boolean; PerBin2: Boolean; var CreatePick: Codeunit 
       "Create Pick"; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
