### ISSUE TITLE
[Event Request] report 7305 "Whse.-Source - Create Document" OnSetQuantityOnBeforeWhseItemTrackingLineFindFirst

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13706]
Hello, 

Is it possible to get the following event

   procedure SetQuantity(var PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; SourceType: Integer; var QtyToHandleBase: Decimal)
    var
        WhseItemTrackingLine: Record "Whse. Item Tracking Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetQuantity(PostedWhseRcptLine, SourceType, QtyToHandleBase, IsHandled);
        if IsHandled then
            exit;

        with WhseItemTrackingLine do begin
            Reset;
            SetCurrentKey("Serial No.", "Lot No.");
            SetTrackingFilterFromPostedWhseReceiptLine(PostedWhseRcptLine);
            SetRange("Source Type", SourceType);
            SetRange("Source ID", PostedWhseRcptLine."No.");
            SetRange("Source Ref. No.", PostedWhseRcptLine."Line No.");
            // DINNL <<
            OnSetQuantityOnBeforeWhseItemTrackingLineFindFirst(WhseItemTrackingLine, PostedWhseRcptLine);
            // DINNL >>
            if FindFirst then begin

    
    [IntegrationEvent(false, false)]
    local procedure OnSetQuantityOnBeforeWhseItemTrackingLineFindFirst(var WhseItemTrackingLine: Record "Whse. Item Tracking Line"; var PostedWhseRcptLine: Record "Posted Whse. Receipt Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
