### ISSUE TITLE
[Event Request] report 5754 "Create Pick" DINOnWhseWorksheetCreatePickSetShipToFilter

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13702]
Hello, 

Is it possible to get the following event

                 end;
                        if PerDestination then begin
                            PickWhseWkshLine.SetRange("Destination Type", PickWhseWkshLine."Destination Type");
                            PickWhseWkshLine.SetRange("Destination No.", PickWhseWkshLine."Destination No.");
                            // DINNL <<
                            DINOnWhseWorksheetCreatePickSetShipToFilter(PickWhseWkshLine);
                            // DINNL >>
                            SetPickFilters;
                            PickWhseWkshLineFilter.CopyFilter("Destination Type", PickWhseWkshLine."Destination Type");
                            PickWhseWkshLineFilter.CopyFilter("Destination No.", PickWhseWkshLine."Destination No.");
                        end else begin
                            PickWhseWkshLineFilter.CopyFilter("Destination Type", PickWhseWkshLine."Destination Type");
                            PickWhseWkshLineFilter.CopyFilter("Destination No.", PickWhseWkshLine."Destination No.");
                            SetPickFilters;

    [IntegrationEvent(false, false)]
    local procedure DINOnWhseWorksheetCreatePickSetShipToFilter(var PickWkshLine: Record "Whse. Worksheet Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
