### ISSUE TITLE
[Event Request] Report 7323 "Create Invt Put-away/Pick/Mvmt" function InitWhseActivHeader

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13701]
Dear ALAppExtensions Team,

Is it possible to add an event in report 7323 "Create Invt Put-away/Pick/Mvmt" function InitWhseActivHeader?

    local procedure InitWhseActivHeader()
    begin
        with WhseActivHeader do begin
            Init;
            case "Warehouse Request".Type of
                "Warehouse Request".Type::Inbound:
                    Type := Type::"Invt. Put-away";
                "Warehouse Request".Type::Outbound:
                    if CreatePick then
                        Type := Type::"Invt. Pick"
                    else
                        Type := Type::"Invt. Movement";
            end;
            "No." := '';
            "Location Code" := "Warehouse Request"."Location Code";
            // DINNL <<
            OnAfterInitWhseActivHeader(WhseActivHeader, "Warehouse Request");
            // DINNL >>
        end;
    end;

     local procedure OnAfterInitWhseActivHeader(var WarehouseActivityHeader: Record "Warehouse Activity Header"; var 
          WarehouseRequest: Record "Warehouse Request")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
