### ISSUE TITLE
[Event Request] Report 11000012 "SEPA ISO20022 Pain 01.01.03" - function AddPaymentInformation

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13700]
Dear ALAppExtensions Team,

Is it possible to add an event in Report 11000000 "Get Proposal Entries" in function AddPaymentInformation? 

        AddElement(XMLNodeCurr, 'PmtMtd', 'TRF', '', XMLNewChild);
       
        OnAddPaymentInformationSetTransactionModeBatchBooking(PaymentHistoryLine, IsHandled);
        if IsHandled then
            AddElement(XMLNodeCurr, 'BtchBookg', 'true', '', XMLNewChild)
        else
           LocalFunctionalityMgt.GetPmtHistLineCountAndAmtPmtInf(TotalAmount, LineCount, "Payment History", PaymentHistoryLine);

        AddElement(XMLNodeCurr, 'NbOfTxs', LineCount, '', XMLNewChild);

    local procedure OnAddPaymentInformationSetTransactionModeBatchBooking(PaymentHistoryLine: Record "Payment History Line"; var IsHandled: Boolean)

**Comment by Oleg-Romashkov** [comment]
Provided code changes the standard logic anyways. 
Maybe you missed the proper "else" BtchBookg line:
```

    AddElement(XMLNodeCurr, 'PmtMtd', 'TRF', '', XMLNewChild);
   
    OnAddPaymentInformationSetTransactionModeBatchBooking(PaymentHistoryLine, IsHandled);
    if IsHandled then
        AddElement(XMLNodeCurr, 'BtchBookg', 'true', '', XMLNewChild)
    else
        AddElement(XMLNodeCurr, 'BtchBookg', BtchBookg, '', XMLNewChild);
    
    LocalFunctionalityMgt.GetPmtHistLineCountAndAmtPmtInf(TotalAmount, LineCount, "Payment History", PaymentHistoryLine);
    AddElement(XMLNodeCurr, 'NbOfTxs', LineCount, '', XMLNewChild);

```

**Comment by NeleBollen** [comment]
OK, we will take a closer look.
I'm closing this issue.
