### ISSUE TITLE
[Protected Request]  report 5754 "Create Pick" PickWhseWkshLine

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13705]
Hello, 

Is it possible to get the following variable as protected so we can use it in an extension.

PickWhseWkshLine

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
