### ISSUE TITLE
[Event Request] report 5754 "Create Pick" OnWhseWorksheetCreatePickClearShipToFilter

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13703]
Hello, 

Is it possible to get the following event

                            PickWhseWkshLineFilter.CopyFilter("Destination No.", PickWhseWkshLine."Destination No.");
                        end else begin
                            PickWhseWkshLineFilter.CopyFilter("Destination Type", PickWhseWkshLine."Destination Type");
                            PickWhseWkshLineFilter.CopyFilter("Destination No.", PickWhseWkshLine."Destination No.");
                            SetPickFilters;
                        end;
                        PickWhseWkshLineFilter.CopyFilter("Whse. Document Type", PickWhseWkshLine."Whse. Document Type");
                        PickWhseWkshLineFilter.CopyFilter("Whse. Document No.", PickWhseWkshLine."Whse. Document No.");
                        // DINNL <<
                        OnWhseWorksheetCreatePickClearShipToFilter(PickWhseWkshLineFilter, PickWhseWkshLine);
                        // DINNL >>
                    until not PickWhseWkshLine.Find('-');
                    CheckPickActivity;
                end else begin

OnWhseWorksheetCreatePickClearShipToFilter

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
