### ISSUE TITLE
[Event Request] Report 7318 "Whse.-Shipment - Create Pick" - OnPreReport

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13704]
Dear ALAppExtensions Team,

Is it possible to add an event (with sender included) in Report 7318 "Whse.-Shipment - Create Pick" - OnPreReport?

    trigger OnPreReport()
    begin
        // DINNL <<
        OnBeforeOnPreReport;
        // DINNL <<
        Clear(CreatePick);
        EverythingHandled := true;
    end;

    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeOnPreReport()
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
