### ISSUE TITLE
[Event Request] report 7390 "Whse. Calculate Inventory" OnInsertWhseJnlLineOnBeforeFindWhseEntry

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13719]
Hello, 

Is it possible to get the following event

            WhseEntry.SetCurrentKey(
              "Item No.", "Bin Code", "Location Code", "Variant Code",
              "Unit of Measure Code", "Lot No.", "Serial No.", "Entry Type");
            WhseEntry.SetRange("Item No.", BinContent."Item No.");
            WhseEntry.SetRange("Bin Code", BinContent."Bin Code");
            WhseEntry.SetRange("Location Code", BinContent."Location Code");
            WhseEntry.SetRange("Variant Code", BinContent."Variant Code");
            WhseEntry.SetRange("Unit of Measure Code", BinContent."Unit of Measure Code");
            // DINNL <<
            OnInsertWhseJnlLineOnBeforeFindWhseEntry(WhseEntry, "Bin Content");
            // DINNL >>
            if WhseEntry.Find('-') then
                repeat
                    WhseEntry.SetTrackingFilterFromWhseEntry(WhseEntry);
                    WhseEntry.CalcSums("Qty. (Base)");
                    if (WhseEntry."Qty. (Base)" <> 0) or ZeroQty then begin
                        ItemUOM.Get(BinContent."Item No.", BinContent."Unit of Measure Code");
                        NextLineNo := NextLineNo + 10000;
                        Init;
                        "Line No." := NextLineNo;

    [IntegrationEvent(false, false)]
    local procedure OnInsertWhseJnlLineOnBeforeFindWhseEntry(var WhseEntry: Record "Warehouse Entry"; var BinContent: Record "Bin Content")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
