### ISSUE TITLE
[Event Request] report 11404 "Create Elec. ICP Declaration" OnGetCountryCode

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13718]
Hello, 

Is it possible to get the following event

                        SetRange("Country/Region Code", "Country/Region Code");
                        SetRange("VAT Registration No.", "VAT Registration No.");
                        CalcSums(Base);

                        if Abs(Base) >= 1 then begin
                            "Elec. Tax Declaration Header".InsertLine(0, 1, CurrentType, '');
                            CountryRegionCode := GetCountryRegionCode("Country/Region Code");
                            // DINNL <<
                            OnGetCountryCode("VAT Entry");
                            // DINNL >>

                            InsertDataLine("Elec. Tax Declaration Header", 2, 'bd-i:CountryCodeISO-EC',
                              CopyStr(CountryRegionCode, 1, 2), '', 'Msg', '');

    [IntegrationEvent(false, false)]
    local procedure OnGetCountryCode(var VATEntry: Record "VAT Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
