### ISSUE TITLE
[Event Request] report 11000000 "Get Proposal Entries" OnBeforeProposalLineInsert

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13717]
Hello, 

Is it possible to get the following event 

                    ProposalLine.Init();
                    ProposalLine.Validate("Account Type", DetailLine."Account Type");
                    ProposalLine.Validate("Account No.", DetailLine."Account No.");
                    ProposalLine.Validate(Bank, DetailLine.Bank);
                    ProposalLine.Validate("Transaction Mode", DetailLine."Transaction Mode");
                    ProposalLine.Validate("Currency Code", DetailLine."Currency Code");
                    ProposalLine."Transaction Date" := DetailLine.Date;
                    ProposalLine.Validate("Identification No. Series", TrMode."Identification No. Series");
                    OnBeforeProposalLineInsert(ProposalLine, DetailLine);
                    // DINNL <<
                    OnBeforeProposalLineInsert(ProposalLine, DetailLine, DINTempProposalLines);
                    // DINNL >>
                    ProposalLine.Insert(true);
                end;

                DetailLine."Connect Lines" := ProposalLine."Line No.";
                DetailLine.UpdateConnection;
                DetailLine.Modify();

    [IntegrationEvent(false, false)]
    local procedure OnBeforeProposalLineInsert(var ProposalLine: Record "Proposal Line"; DetailLine: Record "Detail Line"; var TempProposalLines: Record "Proposal Line" temporary)
    begin
    end;

**Comment by db-bc** [comment]
What is `DINTempProposalLines`? Presumably not something MS have in the standard object, with that name.

**Comment by leegeurts** [comment]
Your correct, I can simply use OnBeforeProposalLineInsert sorry for that one,, totally missed it, you can close this one.
