### ISSUE TITLE
[Scope Change]  IT Localization - Codeunit 12152 SubcontractingManagement - procedure TransfSUBOrdCompToSUBTransfOrd

### ISSUE THREAD

**Issue by Delpixe** [microsoft/ALAppExtensions#13716]

**Comment by AlexanderYakunin** [comment]
Hello! You have created several [Scope change] requests for this codeunit. Please clarify which problem you need to address by this change?

**Comment by Delpixe** [comment]
Hello! 

I'm facing a porting of custom code from NAV2018 to BC18 SaaS.

I'm not sure if it can help, but, here is some example of my code:
```AL
[...]
TransferLine."Routing No." := PurchLine."Routing No.";
TransferLine."Routing Reference No." := PurchLine."Routing Reference No.";
TransferLine."Work Center No." := PurchLine."Work Center No.";
TransferLine."Operation No." := PurchLine."Operation No.";
TransferLine."LSA Sub. Order Item Demand" := ProdOrderItemDemand;
TransferLine.Insert();

SubcontractingMgt.TransfSUBOrdCompToSUBTransfOrd(TransferLine, ProdOrderComponent);
```

```AL
local procedure ProdOrderRoutingLineOnValidate(var ProdOrderRoutingLine: Record "Prod. Order Routing Line")
var
   SubcontractingManagement: Codeunit SubcontractingManagement;
begin
   SubcontractingManagement.UpdLinkedComponents(ProdOrderRoutingLine, false);
end;
```

```AL
//OnValidate of the "Prod Order Routing Line"."No."
if SubcontractingManagement.FindSubcOrder(Rec, PurchLine, PurchHeader) then
    Error(Text1130001, Status, TableCaption, "Operation No.", PurchLine."Document No.");
if (xRec."No." <> "LSA No." /*Custom Field*/) and ("Routing Link Code" <> '') then
    SubcontractingManagement.UpdLinkedComponents(Rec, not HideMessages);
```

Actually, after some careful analysis, I was able to overcome the problem with the other functions, instead, the 2 listed above are the only remaining.
I'm sorry for the inconvenience I may have created, let me know if I have to Delete/Close the other issues myself.

I hope I have answered your question, and I'm sorry for my bad English.

Thank you in advance,
  Mattia

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
