### ISSUE TITLE
[Scope Change]  IT Localization - Codeunit 12152 SubcontractingManagement - procedure UpdLinkedComponents

### ISSUE THREAD

**Issue by Delpixe** [microsoft/ALAppExtensions#13712]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
