### ISSUE TITLE
[Request] Codeunit 5633 FA Jnl.-Post Batch - Add GuiAllowed

### ISSUE THREAD

**Issue by tgdoat44** [microsoft/ALAppExtensions#13728]
In Codeunit 5633 FA Jnl.-Post Batch, we requiere a trigger after setting the filters, before the table is locked:
`local procedure OnCodeOnBeforeLockTableFAJnlLine(var FAJnlLine : Record "FA Journal Line")`
![image](https://user-images.githubusercontent.com/72976203/127881572-79071da0-d9f0-499c-b1ba-d4183069f2ab.png)

In order to use this codeunit in background processes, GuiAllowed is needed at the following locations throughout the code to prevent the progress dialog from opening and causing an error.

In procedure "Code"():
![image](https://user-images.githubusercontent.com/72976203/127881036-ce6812d3-08fc-483d-838e-9c6a0e4af0aa.png)
![image](https://user-images.githubusercontent.com/72976203/127881051-130ef8f4-cbc5-407c-b388-292cb893521a.png)

In procedure PostLines():
![image](https://user-images.githubusercontent.com/72976203/127880568-26ea5301-44bf-477b-885e-8b7319788b18.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
