### ISSUE TITLE
[Event Request] Codeunit 1510 Notification Management - OnBeforeInsertOverdueEntry

### ISSUE THREAD

**Issue by hgnamvn** [microsoft/ALAppExtensions#13729]
Please add OnBeforeInsertOverdueEntry event for "InsertOverdueEntry" method of Codeunit 1510 Notification Management

![image](https://user-images.githubusercontent.com/24407031/127980180-b664ff85-8cc6-477d-8f9d-4277e9cb0ca8.png)

procedure OnBeforeInsertOverdueEntry(var OverdueApprovalEntry: Record "Overdue Approval Entry"; ApprovalEntry: Record "Approval Entry")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
