### ISSUE TITLE
Extend IntegrationEvent in Table 60 "Document Sending Profile", function OnBeforeSendEmailToCust

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#13726]
Hello,

please extends IntegrationEvent in Table 60 "Document Sending Profile", function OnBeforeSendEmailToCust.
Existing Parameter "ShowDialog" should have the VAR Property.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
