### ISSUE TITLE
add paramteters to OnBeforeCheckApplyLocationVariantFilters event ("Value Entry" record)

### ISSUE THREAD

**Issue by tyurm** [microsoft/ALAppExtensions#13721]
Hello,

New "isHandled" event was added to CheckApplyLocationVariantFilters procedure, but not all parent procedure parameters were added to this event:
![image](https://user-images.githubusercontent.com/45788765/127836875-eed0bda8-6833-4ca2-a083-37d4ac4fb015.png)

is it possible to extend OnBeforeCheckApplyLocationVariantFilters with the same parameters?

Event Call:

```
IsHandled := false;
OnBeforeCheckApplyLocationVariantFilters(Rec, AccountingPeriod, ValueEntry, Item, CostCalcIsChanged, QtyFactor, FromDate, ToDate, IsHandled);
if IsHandled then
  exit;
```

Event Declaration:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckApplyLocationVariantFilters(var RecValueEntry: Record "Value Entry"; AccountingPeriod: Record "Accounting Period"; ValueEntry: Record "Value Entry"; Item: Record Item; CostCalcIsChanged: Boolean; var QtyFactor: Decimal; FromDate: Date; ToDate: Date; var IsHandled: Boolean)
begin
end;
```

Thank you in advance.

**Comment by db-bc** [comment]
It would help to specify which AL object type/ID/name this is in...

**Comment by tyurm** [comment]
@db-bc table 5802 "Value Entry"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
