### ISSUE TITLE
[Request] Codeunit 13 Gen. Jnl.-Post Batch Event and GuiAllowed

### ISSUE THREAD

**Issue by tgdoat44** [microsoft/ALAppExtensions#13724]
In Codeunit 13 Gen. Jnl.-Post Batch, we requiere a trigger before clearing the data exchange entries:
`local procedure OnBeforeClearDataExchEntries(var PassedGenJnlLine: Record "Gen. Journal Line"; var IsHandled: Boolean)`
![image](https://user-images.githubusercontent.com/72976203/127875190-4a8276d8-54d6-4c21-856a-a10e9c0ff48f.png)

In order to use this codeunit in background processes, GuiAllowed is needed at the following locations throughout the code to prevent the progress dialog from opening and causing an error. The record counts that are only used in the progress dialog can also be disabled when GuiAllowed is false.

In procedure ProcessLines():
The opening and updating of the progress dialog and the count of the number of records, which is only used in the progress dialog, should be proceeded by GuiAllowed:
![image](https://user-images.githubusercontent.com/72976203/127875204-81ff9562-a466-4ef3-bf13-16e7bb72eabe.png)

In procedure CheckAndCopyBalancingData();
The count of the number of entries is only used in the progress dialog and therefore should also be proceeded by GuiAllowed:
![image](https://user-images.githubusercontent.com/72976203/127875216-55952b50-e000-47c9-9b88-07b70a1d0d0e.png)

In the following three functions GuiAllowed should be added at the beginning:
* UpdateDialog():
* UpdateDialogUpdateBalLines():
* UpdatePostingState():

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
