### ISSUE TITLE
[Event Request] Page 232 Apply Customer Entries - Set ApplyingCustLedgEntry as Protected Var

### ISSUE THREAD

**Issue by Joneleth84** [microsoft/ALAppExtensions#13723]
In order to use temporary record ApplyingCustLedgEntry in a page extension (custom action) of page "Apply Customer Entries" we need the record to be a protected var.

Best regards,
Johannes Gritsch

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
