### ISSUE TITLE
[Event Request] codeunit 139173 CRMSynchHelperTest new Event OnBeforePostSalesInvoice

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#13737]
We have changed posting routine that we have to release document before posting. Therefor standard Unit Tests are failing, so we need new publisher where we would subscribe and Release Document before posting.

**BEFORE**
    local procedure CreateAndPostSalesInvoice(var SalesInvoiceHeader: Record "Sales Invoice Header")
    var
        SalesHeader: Record "Sales Header";
    begin
        LibrarySales.CreateSalesInvoice(SalesHeader);
        LibrarySales.PostSalesDocument(SalesHeader, false, true);
        SalesInvoiceHeader.SetRange("Bill-to Customer No.", SalesHeader."Bill-to Customer No.");
        SalesInvoiceHeader.FindLast;
        SalesInvoiceHeader.CalcFields("Amount Including VAT");
        SalesInvoiceHeader.CalcFields(Amount);
    end;

**AFTER**
    local procedure CreateAndPostSalesInvoice(var SalesInvoiceHeader: Record "Sales Invoice Header")
    var
        SalesHeader: Record "Sales Header";
    begin
        LibrarySales.CreateSalesInvoice(SalesHeader);
        **OnBeforePostSalesInvoice(SalesHeader)**
        LibrarySales.PostSalesDocument(SalesHeader, false, true);
        SalesInvoiceHeader.SetRange("Bill-to Customer No.", SalesHeader."Bill-to Customer No.");
        SalesInvoiceHeader.FindLast;
        SalesInvoiceHeader.CalcFields("Amount Including VAT");
        SalesInvoiceHeader.CalcFields(Amount);
    end;

[IntegrationEvent(false, false)]
local procedure OnBeforePostSalesInvoice(var SalesHeader: Record "Sales Header")
begin
end;

**Comment by AlexanderYakunin** [comment]
We are not going to implement such events in test codeunits, please use event in test libraries, like this one OnBeforePostSalesDocument(SalesHeader, NewShipReceive, NewInvoice, AfterPostSalesDocumentSendAsEmail);
