### ISSUE TITLE
[Event Request] Codeunit 5870 Calculate BOM Tree

### ISSUE THREAD

**Issue by hgnamvn** [microsoft/ALAppExtensions#13730]
Please:
1. Add procedure to set HideDialog to hide Dialog for this codeunit.
   
![image](https://user-images.githubusercontent.com/24407031/127982101-ad5d450b-f034-4d10-88c3-bd870cfca853.png)
![image](https://user-images.githubusercontent.com/24407031/127982210-cb56362b-016b-49bf-a929-fae750b3b76c.png)

2. Add OnBeforeCalculateTreeType event for GenerateTreeForItemLocal method
procedure  OnBeforeCalculateTreeType(ParentItem : Record Item; Var BOMBuffer : Record "BOM Buffer"; TreeType: Option " ",Availability,Cost; EntryNo: Integer)

![image](https://user-images.githubusercontent.com/24407031/127983296-8193754a-b2fc-49eb-a604-db4fe1203aca.png)

3. Add event for GenerateProdCompSubTree method to handle BOM buffer from "Routing Line" by extension.
procedure  OnBeforeGenerateProdCompSubTreeForRoutingLine(ParentItem : Record Item; Var BOMBuffer : Record "BOM Buffer"; TreeType: Option " ",Availability,Cost; EntryNo: Integer; IsHandled: Boolean)

![image](https://user-images.githubusercontent.com/24407031/127984372-7b19a776-7a59-478f-9175-80215378c2c2.png)

Thank!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
