### ISSUE TITLE
Domestic QR code treatment for CH is required in W1 database

### ISSUE THREAD

**Issue by Kowa63** [microsoft/ALAppExtensions#13733]
Due to the nature of German being an offical language in several neighbouring countries (DE, AT, CH, LI, LU ,BE ,partly IT)
https://en.wikipedia.org/wiki/List_of_countries_and_territories_where_German_is_an_official_language
we are currently running into SaaS limitations in respect of the CH payment module, as the special treatment of QR codes with a superimposed swiss flag is encased in codeunits with are only part of the CH database.
![grafik](https://user-images.githubusercontent.com/16236672/131851406-cb5a361a-8078-486c-bf07-51c78d2e5fb7.png)
Many customers in CH and LI are working with DE or AT databases, as these contain modules which were developed by ISVs in DE or AT. These systems are mostly serviced and maintained from DE or AT too. Since all customers in CH require their national payment module with its dedicated domestic requirements, it is presently not possible to offer a SaaS customer in CH a solution which is entirely satisfactory. OnPrem you could copy the functions of the CH modules to your own, for SaaS this option is not available due to the external components like dlls which are employed here. 

Would it be possible to offer the QR codes (or any other functionality which induces external components) with local quirks in objects which are part of the W1 database as external functions so that they can be used by all ISVs?

**Comment by Kowa63** [comment]
I presume this problem will cease to exist as soon as DE,AT and CH are provided as localisation apps like DK will be soon as announced here: https://twitter.com/JesperSchulz/status/1433102881465544705 ?

**Comment by dnpb** [comment]
For that to solve the problem, the QR functionality would have to be moved to W1, rather than an alternative such as copying and pasting it to each of the localisation apps. Putting it in W1 seems most sensible as it's useful functionality and shouldn't end up diverging as it would if copied-and-pasted around.

**Comment by Kowa63** [comment]
It has just been released, in BC 19.1 codeunit 4113 "Swiss QR Code Helper" was implemented.
In the OnPrem version, it's located in Dynamics.365.BC.32186.DE.DVD\Applications\BaseApp\Source\Base Application.Source\QR Code Helpers

**Comment by fmoric** [comment]
> It has just been released, in BC 19.1 codeunit 4113 "Swiss QR Code Helper" was implemented. In the OnPrem version, it's located in Dynamics.365.BC.32186.DE.DVD\Applications\BaseApp\Source\Base Application.Source\QR Code Helpers

I hope that it is just first version, because it is just copy paste of Swiss localization CU to W1. If you notice you cannot generate QR code without swiss logo overlay on it. I was hoping for more generic approach, and maybe to be able to setup QR settings. Some countries have QR code settings defined by law.

P.S. QR fonts are available now.

**Comment by Kowa63** [comment]
The normal 2D codes should be in BC 19.1 as well, the generic QR is just one of them, together with DataMatrix, Aztec and PDF417.
At least that is what was announced here:
https://www.yammer.com/dynamicsnavdev/threads/1288318994497536

**Comment by Kowa63** [comment]
The 2D codes were implemented in the System Application in BC 19.1, not in the Base Application as the new Swiss QR Code Helper above.
https://github.com/microsoft/ALAppExtensions/tree/main/Modules/System/Barcode/src/IDAutomation%202D%20Provider/Encoders

**Comment by JesperSchulz** [comment]
There is also a new PR to leverage the Microsoft.Dynamics.Nav.MX.dll to generate QR code images: #15306. It's needs a few adjustments, but if all goes well you will be able to create QR code images through the barcode module soon :-)
