### ISSUE TITLE
[Event Change] Codeunit 7312 "Create Pick" - Add "VAR" for parameters of event

### ISSUE THREAD

**Issue by hgnamvn** [microsoft/ALAppExtensions#13732]
Please Add VAR for parameters of OnCreateTempActivityLineOnAfterCalcQtyToPick event.
**Current:**
_[IntegrationEvent(false, false)]
    local procedure OnCreateTempActivityLineOnAfterCalcQtyToPick(var TempWhseActivLine: Record "Warehouse Activity Line" temporary; QtyToPick: Decimal; QtyToPickBase: Decimal; WhseSource: Option "Pick Worksheet",Shipment,"Movement Worksheet","Internal Pick",Production,Assembly; WhseSource2: Option)
    begin
    end;_

**After Change:**
_[IntegrationEvent(false, false)]
    local procedure OnCreateTempActivityLineOnAfterCalcQtyToPick(var TempWhseActivLine: Record "Warehouse Activity Line" temporary; **VAR** QtyToPick: Decimal; **VAR** QtyToPickBase: Decimal; WhseSource: Option "Pick Worksheet",Shipment,"Movement Worksheet","Internal Pick",Production,Assembly; WhseSource2: Option)
    begin
    end;_

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
