### ISSUE TITLE
[Request-for-external] table 37 "Sales Line" - GetSKU() 

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#13735]
GetSKU does not have a reference parameter for the SKU table. And the globale variabel is not protected var.
Can you change GetSKU as suggested in Ref #10827

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
