### ISSUE TITLE
[EventRequest] codeunit 139197 DocumentSendingPostTests new event OnBeforePostSalesHeaderAndLine

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#13738]
We have changed posting routine that we have to release document before posting. Therefor standard Unit Tests are failing, so we need new publisher where we would subscribe and Release Document before posting.

**BEFORE**
    local procedure CreateAndPostSalesHeaderAndLine(var PostedDocumentVariant: Variant; var Customer: Record Customer; DocumentType: Enum "Sales Document Type")
    var
        SalesHeader: Record "Sales Header";
        Item: Record Item;
        SalesLine: Record "Sales Line";
        SalesPost: Codeunit "Sales-Post";
    begin
        LibrarySales.CreateSalesHeader(SalesHeader, DocumentType, Customer."No.");
        UpdateYourReferenceSalesHeader(SalesHeader, LibraryUtility.GenerateGUID);
        LibraryInventory.CreateItem(Item);
        LibrarySales.CreateSalesLine(SalesLine, SalesHeader, SalesLine.Type::Item, Item."No.", 1);
        LibrarySales.PostSalesDocument(SalesHeader, false, true);
        SalesPost.GetPostedDocumentRecord(SalesHeader, PostedDocumentVariant);
    end;

**AFTER**
    local procedure CreateAndPostSalesHeaderAndLine(var PostedDocumentVariant: Variant; var Customer: Record Customer; DocumentType: Enum "Sales Document Type")
    var
        SalesHeader: Record "Sales Header";
        Item: Record Item;
        SalesLine: Record "Sales Line";
        SalesPost: Codeunit "Sales-Post";
    begin
        LibrarySales.CreateSalesHeader(SalesHeader, DocumentType, Customer."No.");
        UpdateYourReferenceSalesHeader(SalesHeader, LibraryUtility.GenerateGUID);
        LibraryInventory.CreateItem(Item);
        LibrarySales.CreateSalesLine(SalesLine, SalesHeader, SalesLine.Type::Item, Item."No.", 1);
        OnBeforePostSalesHeaderAndLine(SalesHeader);
        LibrarySales.PostSalesDocument(SalesHeader, false, true);
        SalesPost.GetPostedDocumentRecord(SalesHeader, PostedDocumentVariant);
    end;
[IntegrationEvent(false, false)]
local procedure OnBeforePostSalesHeaderAndLine(var SalesHeader: Record "Sales Header")
begin
end;

**Comment by AlexanderYakunin** [comment]
We are not going to implement such events in test codeunits, please use event in test libraries, like this one OnBeforePostSalesDocument(SalesHeader, NewShipReceive, NewInvoice, AfterPostSalesDocumentSendAsEmail);
