### ISSUE TITLE
[Event Request] - table 39 "Purchase Line" - OnGetDeferralPostDate

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#13736]
In the "Sales Line" I can change the DeferralPostDate but nut in the "Purchase Line". Can you do it in the same way?  
"Sales Line":  
![image](https://user-images.githubusercontent.com/45654195/128011225-79fed896-65e4-4142-8cbb-6dd1558ef55d.png)
  
"Purchase Line":  
![image](https://user-images.githubusercontent.com/45654195/128011255-c4e77a6a-59d2-4422-843d-f7a3aa974e87.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
