### ISSUE TITLE
[EventRequest] codeunit 142061 "ERM Batch Reports DACH" new Event OnBeforePostFixedAssetSalesInvoice

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#13734]
We have changed posting routine that we have to release document before posting. Therefor standard Unit Tests are failing, so we need new publisher where we would subscribe and Release Document before posting.

**BEFORE**
local procedure CreatePostFixedAssetSalesInvoice(PostingDate: Date; FANo: Code[20]; UnitPrice: Decimal): Code[20]
    var
        SalesHeader: Record "Sales Header";
        SalesLine: Record "Sales Line";
    begin
        LibrarySales.CreateSalesHeader(SalesHeader, SalesHeader."Document Type"::Invoice, LibrarySales.CreateCustomerNo);
        SalesHeader.Validate("Posting Date", PostingDate);
        SalesHeader.Modify(true);

        LibrarySales.CreateSalesLine(SalesLine, SalesHeader, SalesLine.Type::"Fixed Asset", FANo, 1);
        SalesLine.Validate("Depreciation Book Code", GetFADeprBookCode(FANo));
        SalesLine.Validate("Depr. until FA Posting Date", true);
        SalesLine.Validate("Unit Price", UnitPrice);
        SalesLine.Modify(true);

        exit(LibrarySales.PostSalesDocument(SalesHeader, true, true));
    end;

**AFTER**
local procedure CreatePostFixedAssetSalesInvoice(PostingDate: Date; FANo: Code[20]; UnitPrice: Decimal): Code[20]
    var
        SalesHeader: Record "Sales Header";
        SalesLine: Record "Sales Line";
    begin
        LibrarySales.CreateSalesHeader(SalesHeader, SalesHeader."Document Type"::Invoice, LibrarySales.CreateCustomerNo);
        SalesHeader.Validate("Posting Date", PostingDate);
        SalesHeader.Modify(true);

        LibrarySales.CreateSalesLine(SalesLine, SalesHeader, SalesLine.Type::"Fixed Asset", FANo, 1);
        SalesLine.Validate("Depreciation Book Code", GetFADeprBookCode(FANo));
        SalesLine.Validate("Depr. until FA Posting Date", true);
        SalesLine.Validate("Unit Price", UnitPrice);
        SalesLine.Modify(true);
        **OnBeforePostFixedAssetSalesInvoice(SalesHeader);**
        exit(LibrarySales.PostSalesDocument(SalesHeader, true, true));
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostFixedAssetSalesInvoice(var SalesHeader: Record "Sales Header")
    begin
    end;

**Comment by Stepanenko-Vadim** [comment]
There is already an event in LibrarySales.PostSalesDocument called **OnBeforePostSalesDocument**, is there a reason you cannot use that instead?

**Comment by Stepanenko-Vadim** [comment]
We are not going to implement such events in test codeunits, please use event in test libraries, like this one in LibrarySales PostSalesDocument procedure: **OnBeforePostSalesDocument**
