### ISSUE TITLE
[EventRequest] codeunit 134481 "ERM Dimension Archive Document" new Event OnBeforePostSalesArchiveOrder

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#13745]
We have changed posting routine that we have to release document before posting. Therefor standard Unit Tests are failing, so we need new publisher where we would subscribe and Release Document before posting.

**BEFORE**
    local procedure CreateAndPostSalesArchiveOrder(var SalesLine: Record "Sales Line")
    var
        Customer: Record Customer;
        SalesHeader: Record "Sales Header";
    begin
        LibrarySales.SetArchiveOrders(true);
        LibrarySales.CreateCustomer(Customer);
        LibrarySales.CreateSalesHeader(SalesHeader, SalesHeader."Document Type"::Order, Customer."No.");
        LibrarySales.CreateSalesLine(SalesLine, SalesHeader, SalesLine.Type::Item, CreateItem, LibraryRandom.RandDec(10, 2));  // Used Random value for Quantity.
        SalesLine.Validate("Qty. to Ship", SalesLine.Quantity / 2);  // Taken partial Qty. to Ship
        SalesLine.Modify(true);
        LibrarySales.PostSalesDocument(SalesHeader, true, true);
    end;

**AFTER**
    local procedure CreateAndPostSalesArchiveOrder(var SalesLine: Record "Sales Line")
    var
        Customer: Record Customer;
        SalesHeader: Record "Sales Header";
    begin
        LibrarySales.SetArchiveOrders(true);
        LibrarySales.CreateCustomer(Customer);
        LibrarySales.CreateSalesHeader(SalesHeader, SalesHeader."Document Type"::Order, Customer."No.");
        LibrarySales.CreateSalesLine(SalesLine, SalesHeader, SalesLine.Type::Item, CreateItem, LibraryRandom.RandDec(10, 2));  // Used Random value for Quantity.
        SalesLine.Validate("Qty. to Ship", SalesLine.Quantity / 2);  // Taken partial Qty. to Ship
        SalesLine.Modify(true);
        **OnBeforePostSalesArchiveOrder**(SalesHeader);
        LibrarySales.PostSalesDocument(SalesHeader, true, true);
    end;

[IntegrationEvent(false, false)]
local procedure **OnBeforePostSalesArchiveOrder**(var SalesHeader: Record "Sales Header")
begin
end;

**Comment by Stepanenko-Vadim** [comment]
We are not going to implement such events in test codeunits, please use event in test libraries, like this one in LibrarySales PostSalesDocument procedure: **OnBeforePostSalesDocument**
