### ISSUE TITLE
Webclient BUG Report filter with combined Optionfield

### ISSUE THREAD

**Issue by ThomasBrendel** [Microsoft/ALAppExtensions#1374]
If you run a Report with a combined Filter on an Optionfield like it is possible in RTC-Client, this is not possible. The Field gets greyed and it is not editable and the Options i get is 0|1 instead of the Strings. 

We use a Filter like this:

JobStructDispL.SETFILTER("Reordering Significant", '<%1', JobStructDispL."Reordering Significant"::Planning)

And the Optionfield has three options: "BLANK,Manual,Planning"

**Comment by JesperSchulz** [comment]
Could you try to repro in our latest cumulative update? We believe this has been fixed recently. If not, please report to support, as this has to be addressed the right way. Thanks a lot!

**Comment by ThomasBrendel** [comment]
Tried in CU2 AND CU3
