### ISSUE TITLE
[EventRequest] codeunit 134553 "ERM Cash Flow - Filling II" new Events before Post Sales Headers

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#13741]
We have changed posting routine that we have to release document before posting. Therefor standard Unit Tests are failing, so we need new publisher where we would subscribe and Release Document before posting.

**BEFORE**
local procedure CreateAndPostSalesOrderWithOneLine(var SalesHeader: Record "Sales Header"; CustomerNo: Code[20]): Code[20]
    begin
        CreateSalesOrderWithLineCount(SalesHeader, CustomerNo, 1);
        exit(LibrarySales.PostSalesDocument(SalesHeader, true, true));
    end;

    local procedure CreateAndPostSalesOrderWithDiscountPercentage(CustomerNo: Code[20]; PaymentTermsCode: Code[10]): Code[20]
    var
        SalesHeader: Record "Sales Header";
    begin
        CreateSalesOrderWithLineCount(SalesHeader, CustomerNo, 1);
        SalesHeader.Validate("Payment Terms Code", PaymentTermsCode);
        SalesHeader.Modify(true);
        exit(LibrarySales.PostSalesDocument(SalesHeader, true, true));
    end;

**AFTER**
    local procedure CreateAndPostSalesOrderWithOneLine(var SalesHeader: Record "Sales Header"; CustomerNo: Code[20]): Code[20]
    begin
        CreateSalesOrderWithLineCount(SalesHeader, CustomerNo, 1);
        **OnBeforePostSalesOrderWithOneLine(SalesHeader);**
        exit(LibrarySales.PostSalesDocument(SalesHeader, true, true));
    end;

    local procedure CreateAndPostSalesOrderWithDiscountPercentage(CustomerNo: Code[20]; PaymentTermsCode: Code[10]): Code[20]
    var
        SalesHeader: Record "Sales Header";
    begin
        CreateSalesOrderWithLineCount(SalesHeader, CustomerNo, 1);
        SalesHeader.Validate("Payment Terms Code", PaymentTermsCode);
        SalesHeader.Modify(true);
        **OnBeforePostSalesOrderWithDiscountPercentage(SalesHeader);**
        exit(LibrarySales.PostSalesDocument(SalesHeader, true, true));
    end;

[IntegrationEvent(false, false)]
local procedure OnBeforePostSalesOrderWithOneLine(var SalesHeader: Record "Sales Header")
begin
end;

[IntegrationEvent(false, false)]
local procedure OnBeforePostSalesOrderWithDiscountPercentage(var SalesHeader: Record "Sales Header")
begin
end;

**Comment by Stepanenko-Vadim** [comment]
We are not going to implement such events in test codeunits, please use event in test libraries, like this one in LibrarySales PostSalesDocument procedure: **OnBeforePostSalesDocument**
