### ISSUE TITLE
[EventRequest] codeunit 134820 "ERM Cost Accounting - Codeunit" new event OnBeforePostSalesInvoiceWithMultipleLinesAndDimensions

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#13743]
We have changed posting routine that we have to release document before posting. Therefor standard Unit Tests are failing, so we need new publisher where we would subscribe and Release Document before posting.

**BEFORE**
    local procedure CreateAndPostSalesInvoiceWithMultipleLinesAndDimension(DimensionValue: array[2] of Record "Dimension Value"; ItemNo: Code[20]; Qty: Decimal; LineCount: Integer)
    var
        Customer: Record Customer;
        SalesHeader: Record "Sales Header";
        SalesLine: Record "Sales Line";
        i: Integer;
    begin
        LibrarySales.CreateCustomer(Customer);
        LibrarySales.CreateSalesHeader(SalesHeader, SalesHeader."Document Type"::Invoice, Customer."No.");

        // Create Multiple Sales Lines with different dimensions.
        for i := 1 to LineCount do begin
            LibrarySales.CreateSalesLine(SalesLine, SalesHeader, SalesLine.Type::Item, ItemNo, Qty);
            SalesLine.Validate("Shortcut Dimension 1 Code", DimensionValue[i].Code);
            SalesLine.Modify(true);
        end;
        LibrarySales.PostSalesDocument(SalesHeader, true, true);
    end;

**AFTER**
local procedure CreateAndPostSalesInvoiceWithMultipleLinesAndDimension(DimensionValue: array[2] of Record "Dimension Value"; ItemNo: Code[20]; Qty: Decimal; LineCount: Integer)
    var
        Customer: Record Customer;
        SalesHeader: Record "Sales Header";
        SalesLine: Record "Sales Line";
        i: Integer;
    begin
        LibrarySales.CreateCustomer(Customer);
        LibrarySales.CreateSalesHeader(SalesHeader, SalesHeader."Document Type"::Invoice, Customer."No.");

        // Create Multiple Sales Lines with different dimensions.
        for i := 1 to LineCount do begin
            LibrarySales.CreateSalesLine(SalesLine, SalesHeader, SalesLine.Type::Item, ItemNo, Qty);
            SalesLine.Validate("Shortcut Dimension 1 Code", DimensionValue[i].Code);
            SalesLine.Modify(true);
        end;
        **OnBeforePostSalesInvoiceWithMultipleLinesAndDimensions**(SalesHeader);
        LibrarySales.PostSalesDocument(SalesHeader, true, true);
    end;

[IntegrationEvent(false, false)]
local procedure **OnBeforePostSalesInvoiceWithMultipleLinesAndDimensions**(var SalesHeader: Record "Sales Header")
begin
end;

**Comment by Stepanenko-Vadim** [comment]
We are not going to implement such events in test codeunits, please use event in test libraries, like this one in LibrarySales PostSalesDocument procedure: **OnBeforePostSalesDocument**
