### ISSUE TITLE
[Event Request] Codeunit 99000774 "Calculate Routing Line"

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#13742]
Please add new event (with new fuction - not to create similar event 4 times)

    local procedure CalcRoutingLineBack(CalculateEndDate: Boolean)
    ...
        if ProdOrderRoutingLine."Schedule Manually" then // Move and wait time has been calculated
            exit;

        repeat
            LotSize := SendAheadLotSize;
            RemainNeedQty := LotSize * ProdOrderRoutingLine.RunTimePer();
            OnCalculateRoutingLineBackOnAfterCalcRemainNeedQtyForLotSize(ProdOrderRoutingLine, RemainNeedQty);
            RemainNeedQty :=
              Round(
                RemainNeedQty *
                CalendarMgt.TimeFactor(ProdOrderRoutingLine."Run Time Unit of Meas. Code") /
                CalendarMgt.TimeFactor(Workcenter."Unit of Measure Code"),
                Workcenter."Calendar Rounding Precision");
    
            with ProdOrderRoutingLine do begin
                //----------------------------------------GetConstrainedSetup:BEGIN
                //ResourceIsConstrained := ConstrainedCapacity.Get(Type, "No.");
                //ParentIsConstrained := ParentWorkCenter.Get(Type::"Work Center", "Work Center No.");
                GetConstrainedSetup(ConstrainedCapacity,ResourceIsConstrained,ParentWorkCenter,ParentIsConstrained);                
                //----------------------------------------GetConstrainedSetup:END
                if not "Schedule Manually" and
                   (ResourceIsConstrained or ParentIsConstrained)
                then
                    FinitelyLoadCapBack(RoutingTimeType::"Run Time", ConstrainedCapacity, ResourceIsConstrained, ParentWorkCenter, ParentIsConstrained)
                else
                    LoadCapBack(Type, "No.", RoutingTimeType::"Run Time", true);
            end;
    
            ProdEndingDate := ProdOrderRoutingLine."Starting Date";
            ProdEndingTime := ProdOrderRoutingLine."Starting Time";
        until FindSendAheadStartingTime(TmpProdOrderRtngLine, SendAheadLotSize);
    
        ProdEndingDate := ProdOrderRoutingLine."Starting Date";
        ProdEndingTime := ProdOrderRoutingLine."Starting Time";
        RemainNeedQty :=
          Round(
            ProdOrderRoutingLine."Setup Time" *
            CalendarMgt.TimeFactor(ProdOrderRoutingLine."Setup Time Unit of Meas. Code") /
            CalendarMgt.TimeFactor(Workcenter."Unit of Measure Code"),
            Workcenter."Calendar Rounding Precision");
    
        with ProdOrderRoutingLine do begin
            //----------------------------------------GetConstrainedSetup:BEGIN
            //ResourceIsConstrained := ConstrainedCapacity.Get(Type, "No.");
            //ParentIsConstrained := ParentWorkCenter.Get(Type::"Work Center", "Work Center No.");
            GetConstrainedSetup(ConstrainedCapacity,ResourceIsConstrained,ParentWorkCenter,ParentIsConstrained);            
            //----------------------------------------GetConstrainedSetup:END
            if not "Schedule Manually" and
               (ResourceIsConstrained or ParentIsConstrained)
            then
                FinitelyLoadCapBack(RoutingTimeType::"Setup Time", ConstrainedCapacity, ResourceIsConstrained, ParentWorkCenter, ParentIsConstrained)
            else
                LoadCapBack(Type, "No.", RoutingTimeType::"Setup Time", true);
    
            "Starting Date" := ProdEndingDate;
            "Starting Time" := ProdEndingTime;
    
            if "Ending Date" = CalendarMgt.GetMaxDate then begin
                "Ending Date" := "Starting Date";
                "Ending Time" := "Starting Time";
            end;
    
            UpdateDatetime;
            Modify;
        end;
    ...
    end;
     
    local procedure CalcRoutingLineForward(CalculateStartDate: Boolean)
    ...
        with ProdOrderRoutingLine do begin
            //----------------------------------------GetConstrainedSetup:BEGIN
            //ResourceIsConstrained := ConstrainedCapacity.Get(Type, "No.");
            //ParentIsConstrained := ParentWorkCenter.Get(Type::"Work Center", "Work Center No.");
            GetConstrainedSetup(ConstrainedCapacity,ResourceIsConstrained,ParentWorkCenter,ParentIsConstrained);
            //----------------------------------------GetConstrainedSetup:END
            if not "Schedule Manually" and
               (RemainNeedQty > 0) and (ResourceIsConstrained or ParentIsConstrained)
            then
                FinitelyLoadCapForward(RoutingTimeType::"Setup Time", ConstrainedCapacity, ResourceIsConstrained, ParentWorkCenter, ParentIsConstrained)
            else
                LoadCapForward(Type, "No.", RoutingTimeType::"Setup Time", true);
        end;
    
        FirstInBatch := true;
        repeat
            if (InputQtyDiffTime > 0) and (TotalLotSize = MaxLotSize) then
                SetMaxDateTime(
                  ProdStartingDate, ProdStartingTime, ProdOrderRoutingLine2."Ending Date", ProdOrderRoutingLine2."Ending Time");
    
            LotSize := SendAheadLotSize;
            RemainNeedQty := LotSize * ProdOrderRoutingLine.RunTimePer();
            OnCalculateRoutingLineForwardOnAfterCalcRemainNeedQtyForLotSize(ProdOrderRoutingLine, RemainNeedQty);
            RemainNeedQty :=
              Round(
                RemainNeedQty *
                CalendarMgt.TimeFactor(ProdOrderRoutingLine."Run Time Unit of Meas. Code") /
                CalendarMgt.TimeFactor(Workcenter."Unit of Measure Code"),
                Workcenter."Calendar Rounding Precision");
    
            with ProdOrderRoutingLine do begin
                //----------------------------------------GetConstrainedSetup:BEGIN
                //ResourceIsConstrained := ConstrainedCapacity.Get(Type, "No.");
                //ParentIsConstrained := ParentWorkCenter.Get(Type::"Work Center", "Work Center No.");
                GetConstrainedSetup(ConstrainedCapacity,ResourceIsConstrained,ParentWorkCenter,ParentIsConstrained);
                //----------------------------------------GetConstrainedSetup:END                
                if not "Schedule Manually" and
                   (RemainNeedQty > 0) and (ResourceIsConstrained or ParentIsConstrained)
                then
                    FinitelyLoadCapForward(RoutingTimeType::"Run Time", ConstrainedCapacity, ResourceIsConstrained, ParentWorkCenter, ParentIsConstrained)
                else
                    LoadCapForward(Type, "No.", RoutingTimeType::"Run Time", true);
            end;
    
            ProdStartingDate := ProdOrderRoutingLine."Ending Date";
            ProdStartingTime := ProdOrderRoutingLine."Ending Time";
        until FindSendAheadEndingTime(TmpProdOrderRtngLine, SendAheadLotSize);
    ...
    end;
    
    //----------------------------------------GetConstrainedSetup:BEGIN
    local procedure GetConstrainedSetup(
        var ConstrainedCapacity: Record "Capacity Constrained Resource"; 
        var ResourceIsConstrained: Boolean; 
        var ParentWorkCenter: Record "Capacity Constrained Resource"; 
        var ParentIsConstrained: Boolean)
    var
        IsHandled: Boolean;
    begin
        OnBeforeGetConstrainedSetup(ProdOrderRoutingLine,ConstrainedCapacity,ResourceIsConstrained,ParentWorkCenter,ParentIsConstrained,IsHandled);
        if IsHandled then
            exit;
            
        ResourceIsConstrained := ConstrainedCapacity.Get(ProdOrderRoutingLine.Type, ProdOrderRoutingLine."No.");
        ParentIsConstrained := ParentWorkCenter.Get(ProdOrderRoutingLine.Type::"Work Center", ProdOrderRoutingLine."Work Center No.");
    end;
    
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetConstrainedSetup(
        ProdOrderRoutingLine: Record "Prod. Order Routing Line";
        var ConstrainedCapacity: Record "Capacity Constrained Resource"; 
        var ResourceIsConstrained: Boolean; 
        var ParentWorkCenter: Record "Capacity Constrained Resource"; 
        var ParentIsConstrained: Boolean;
        var IsHandled: Boolean)
    begin
    end;  
    //----------------------------------------GetConstrainedSetup:END

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
