### ISSUE TITLE
[Event Request] table 37 "Sales Line"/39 "Purchase Line" - OnInitTypeOnAfterSetType

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#13746]
I asked for OnInitTypeOnAfterSetType in february. Not sure it takes time or has been forgotten? 
I can see that SalesHeader has been added as parameter to event OnAfterInitType. I can use this, but then I have to duplicate the most of the code in the procedure.
See explanation in #10882

I also would like to have this event in table 39 "Purchase Line" if possible.
And it would be greate if PurchaseHeader is also added as parameter to OnAfterInitType in table 39 "Purchase Line".

**Comment by Stepanenko-Vadim** [comment]
The change for **OnAfterInitType** is what we've done in scope of that request and same will be done for purchase side in scope of this. While it's unfortunate that some code has to be duplicated in cases like this, some balance need to be struck, where we don't want a 5 line procedure to have multiple events after each call or assignment.

**Comment by auzhhv** [comment]
> The change for **OnAfterInitType** is what we've done in scope of that request and same will be done for purchase side in scope of this. While it's unfortunate that some code has to be duplicated in cases like this, some balance need to be struck, where we don't want a 5 line procedure to have multiple events after each call or assignment.

That's understandable.
Can you add PurchaseHeader as parameter to OnAfterInitType in table 39 "Purchase Line"?

**Comment by Stepanenko-Vadim** [comment]
Yes, we will do that.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
