### ISSUE TITLE
[EventRequest] codeunit 134480 "ERM Dimension General Part 2" New events OnBeforePostSalesDocument

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#13747]
We have changed posting routine that we have to release document before posting. Therefor standard Unit Tests are failing, so we need new publisher where we would subscribe and Release Document before posting.

**BEFORE**
    local procedure CreateAndPostSalesDocument(CustomerNo: Code[20]; ItemNo: Code[20]; SalespersonCode: Code[20]; var Quantity: Decimal; var Amount: Decimal)
    var
        SalesHeader: Record "Sales Header";
        SalesLine: Record "Sales Line";
    begin
        // Take Random Values for Quantity and Sales Price and Assign Values in Global Variables.
        LibrarySales.CreateSalesHeader(SalesHeader, SalesHeader."Document Type"::Order, CustomerNo);
        SalesHeader.Validate("Salesperson Code", SalespersonCode);
        SalesHeader.Modify(true);
        LibrarySales.CreateSalesLine(SalesLine, SalesHeader, SalesLine.Type::Item, ItemNo, LibraryRandom.RandDec(10, 2));

        // Amount and Quantity are getting accumulated when calling CreateAndPostSalesDocument multiple times.
        Quantity += SalesLine.Quantity;
        Amount += SalesLine."Line Amount";
        LibrarySales.PostSalesDocument(SalesHeader, true, true);
    end;

    local procedure CreateAndPostSalesDocumentAtDate(CustomerNo: Code[20]; ItemNo: Code[20]; DocDate: Date): Decimal
    var
        SalesHeader: Record "Sales Header";
        SalesLine: Record "Sales Line";
    begin
        // Take Random Values for Quantity and Sales Price and Assign Values in Global Variables.
        LibrarySales.CreateSalesHeader(SalesHeader, SalesHeader."Document Type"::Order, CustomerNo);
        with SalesHeader do begin
            Validate("Order Date", DocDate);
            Validate("Posting Date", DocDate);
            Validate("Shipment Date", DocDate);
            Modify(true);
        end;
        LibrarySales.CreateSalesLine(SalesLine, SalesHeader, SalesLine.Type::Item, ItemNo, LibraryRandom.RandDec(10, 2));
        LibrarySales.PostSalesDocument(SalesHeader, true, true);
        exit(SalesLine."Line Amount");
    end;
    local procedure CreateAndPostSalesInvoice(var SalesLine: Record "Sales Line"; DimensionValue: Code[20]; ItemNo: Code[20]): Date
    var
        SalesHeader: Record "Sales Header";
    begin
        // Take Random Quantity for Sales Line.
        LibrarySales.CreateSalesHeader(SalesHeader, SalesHeader."Document Type"::Invoice, CreateCustomerWithDimension(DimensionValue));
        LibrarySales.CreateSalesLine(SalesLine, SalesHeader, SalesLine.Type::Item, ItemNo, LibraryRandom.RandDec(10, 2));
        LibrarySales.PostSalesDocument(SalesHeader, true, true);
        exit(SalesHeader."Posting Date");
    end;

**AFTER**
    local procedure CreateAndPostSalesDocument(CustomerNo: Code[20]; ItemNo: Code[20]; SalespersonCode: Code[20]; var Quantity: Decimal; var Amount: Decimal)
    var
        SalesHeader: Record "Sales Header";
        SalesLine: Record "Sales Line";
    begin
        // Take Random Values for Quantity and Sales Price and Assign Values in Global Variables.
        LibrarySales.CreateSalesHeader(SalesHeader, SalesHeader."Document Type"::Order, CustomerNo);
        SalesHeader.Validate("Salesperson Code", SalespersonCode);
        SalesHeader.Modify(true);
        LibrarySales.CreateSalesLine(SalesLine, SalesHeader, SalesLine.Type::Item, ItemNo, LibraryRandom.RandDec(10, 2));

        // Amount and Quantity are getting accumulated when calling CreateAndPostSalesDocument multiple times.
        Quantity += SalesLine.Quantity;
        Amount += SalesLine."Line Amount";
        **OnBeforePostSalesDocument(SalesHeader);**
        LibrarySales.PostSalesDocument(SalesHeader, true, true);
    end;

    local procedure CreateAndPostSalesDocumentAtDate(CustomerNo: Code[20]; ItemNo: Code[20]; DocDate: Date): Decimal
    var
        SalesHeader: Record "Sales Header";
        SalesLine: Record "Sales Line";
    begin
        // Take Random Values for Quantity and Sales Price and Assign Values in Global Variables.
        LibrarySales.CreateSalesHeader(SalesHeader, SalesHeader."Document Type"::Order, CustomerNo);
        with SalesHeader do begin
            Validate("Order Date", DocDate);
            Validate("Posting Date", DocDate);
            Validate("Shipment Date", DocDate);
            Modify(true);
        end;
        LibrarySales.CreateSalesLine(SalesLine, SalesHeader, SalesLine.Type::Item, ItemNo, LibraryRandom.RandDec(10, 2));
        **OnBeforePostSalesDocumentAtDate(SalesHeader);**
        LibrarySales.PostSalesDocument(SalesHeader, true, true);
        exit(SalesLine."Line Amount");
    end;
    local procedure CreateAndPostSalesInvoice(var SalesLine: Record "Sales Line"; DimensionValue: Code[20]; ItemNo: Code[20]): Date
    var
        SalesHeader: Record "Sales Header";
    begin
        // Take Random Quantity for Sales Line.
        LibrarySales.CreateSalesHeader(SalesHeader, SalesHeader."Document Type"::Invoice, CreateCustomerWithDimension(DimensionValue));
        LibrarySales.CreateSalesLine(SalesLine, SalesHeader, SalesLine.Type::Item, ItemNo, LibraryRandom.RandDec(10, 2));
        **OnBeforePostSalesInvoice(SalesHeader);**
        LibrarySales.PostSalesDocument(SalesHeader, true, true);
        exit(SalesHeader."Posting Date");
    end;

[IntegrationEvent(false, false)]
local procedure **OnBeforePostSalesDocument**(var SalesHeader: Record "Sales Header")
begin
end;
[IntegrationEvent(false, false)]
local procedure **OnBeforePostSalesDocumentAtDate**(var SalesHeader: Record "Sales Header")
begin
end;
[IntegrationEvent(false, false)]
local procedure **OnBeforePostSalesInvoice**(var SalesHeader: Record "Sales Header")
begin
end;

**Comment by Stepanenko-Vadim** [comment]
We are not going to implement such events in test codeunits, please use event in test libraries, like this one in LibrarySales PostSalesDocument procedure: **OnBeforePostSalesDocument**
