### ISSUE TITLE
[Function Request] GetRecordOnce @ Setup-Tables

### ISSUE THREAD

**Issue by J-KVS** [microsoft/ALAppExtensions#13759]
I'd like to propose that you add the `GetRecordOnce()`-Function, that is present e.g. in `PurchasesPayablesSetup.Table.al` or
`SalesReceivablesSetup.Table.al` to the other Setup-Tables. Please let me know if you need additional information from me.

**Code to add:**
``` al
var
    RecordHasBeenRead: Boolean;

procedure GetRecordOnce()
begin
    if RecordHasBeenRead then
        exit;
    Get;
    RecordHasBeenRead := true;
end;
```

Those are the setup-tables missing the `GetRecordOnce()`-Function

- AccountEntitySetup.Table.al
- AccountSchedulesChartSetup.Table.al
- AccSchedKPIWebSrvSetup.Table.al
- AdditionalFeeSetup.Table.al
- AnalysisReportChartSetup.Table.al
- APIEntitiesSetup.Table.al
- ApplicationAreaSetup.Table.al
- AssemblySetup.Table.al
- AzureADAppSetup.Table.al
- AzureADMgtSetup.Table.al
- BankDataConvServiceSetup.Table.al
- BankExportImportSetup.Table.al
- BookingMgrSetup.Table.al
- BusinessChartUserSetup.Table.al
- BusinessUnitSetup.Table.al
- CashFlowChartSetup.Table.al
- CashFlowSetup.Table.al
- CDSConnectionSetup.Table.al
- ChangeLogSetup.Table.al
- ConfigSetup.Table.al
- CostAccountingSetup.Table.al
- CRMConnectionSetup.Table.al
- CurrExchRateUpdateSetup.Table.al
- DataClassNotifSetup.Table.al
- DataMigrationSetup.Table.al
- DocExchServiceSetup.Table.al
- DtldPriceCalculationSetup.Table.al
- DuplicateSearchStringSetup.Table.al
- ElectronicVATDeclSetup.Table.al
- ExchangeServiceSetup.Table.al
- ExperienceTierSetup.Table.al
- FAJournalSetup.Table.al
- FAPostingTypeSetup.Table.al
- FASetup.Table.al
- GeneralPostingSetup.Table.al
- GenericChartSetup.Table.al
- GraphMailSetup.Table.al
- HumanResourcesSetup.Table.al
- HybridDeploymentSetup.Table.al
- ImageAnalysisSetup.Table.al
- IncomingDocumentsSetup.Table.al
- IntegrationManagementSetup.Table.al
- InteractionTemplateSetup.Table.al
- InventoryPostingSetup.Table.al
- InventorySetup.Table.al
- ItemTrackingSetup.Table.al
- JobsSetup.Table.al
- JournalLinesEntitySetup.Table.al
- ManufacturingSetup.Table.al
- MarketingSetup.Table.al
- MSQBDSetup.Table.al
- MSQBOSetup.Table.al
- NativeAPITaxSetup.Table.al
- NonstockItemSetup.Table.al
- NotificationSetup.Table.al
- O365EmailSetup.Table.al
- O365SalesInitialSetup.Table.al
- OAuth20Setup.Table.al
- OCRServiceSetup.Table.al
- OfficeAddinSetup.Table.al
- OnlineMapParameterSetup.Table.al
- OnlineMapSetup.Table.al
- OrderPromisingSetup.Table.al
- OutlookSynchUserSetup.Table.al
- PaymentRegistrationSetup.Table.al
- PaymentServiceSetup.Table.al
- PayrollSetup.Table.al
- PriceCalculationSetup.Table.al
- ResourcesSetup.Table.al
- SalesbyCustGrpChartSetup.Table.al
- ServiceMgtSetup.Table.al
- ServiceStatusPrioritySetup.Table.al
- ServPriceGroupSetup.Table.al
- SMTPMailSetup.Table.al
- SocialListeningSetup.Table.al
- SourceCodeSetup.Table.al
- TaxSetup.Table.al
- TimeSheetChartSetup.Table.al
- TrailingSalesOrdersSetup.Table.al
- TrialBalanceSetup.Table.al
- TroubleshootingSetup.Table.al
- UserSetup.Table.al
- VATPostingSetup.Table.al
- VATRateChangeSetup.Table.al
- VATReportSetup.Table.al
- WarehouseSetup.Table.al

**Comment by db-bc** [comment]
I would mention that in some cases now, such patterns of 'global record + get once' are less useful, because `SetLoadFields()` exists. Thus, even if a call is frequent, if it only needs a small number of field(s), it can now load just those in a local instance and get each time. That avoids polluting with a global variable, having to write subscribers to refresh it if the table is modified, etc.

**Comment by AlexanderYakunin** [comment]
We have no plans to do this kind of changes in application, as this is platform duty to cache frequently used data. SQL server use advanced methods for getting data, and there are ongoing improvements for each release.
