### ISSUE TITLE
[EventRequest] Report Post Prepaid Contract Entries - New events in function PostGenJnlLine

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#13758]
To fill additional informations before posting General Journal Lines we need new events in this report in function PostGenJnlLine:

![image](https://user-images.githubusercontent.com/47414309/128204528-157a986e-6182-45cf-83da-a5d76c2e9349.png)

The new publisher should look like this (all parameter as var):

![image](https://user-images.githubusercontent.com/47414309/128204594-7a0b0cea-6b3a-4a3a-aa94-1a7b9fbe3750.png)

The existing events OnBeforePostPrepaidAccount and OnBeforePostNonPrepaidAccount cannot solve this requirement.

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
