### ISSUE TITLE
insider build 19.0.28666.0 - wrong parameter value passed in Approvals Mgmt: OpenApprovalsPurchase

### ISSUE THREAD

**Issue by MikeGlue** [microsoft/ALAppExtensions#13752]
In the Approvals Mgmt codeunit, the following function uses `DATABASE::"SalesHeader"` but it should be `DATABASE::"Purchase Header"`
```
procedure OpenApprovalsPurchase(PurchHeader: Record "Purchase Header")
begin
    RunWorkflowEntriesPage(
        PurchHeader.RecordId(), DATABASE::"Sales Header", PurchHeader."Document Type", PurchHeader."No.");
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
