### ISSUE TITLE
[EventRequest] Add Rec Paremter to OnValidateShipmentDateOnBeforeCalcReceiptDate and OnValidateReceiptDateOnBeforeCalcShipmentDate

### ISSUE THREAD

**Issue by AndreasGloeckner** [microsoft/ALAppExtensions#13756]
Hello,

please add the Rec as parameter to the publisher `OnValidateShipmentDateOnBeforeCalcReceiptDate` and `OnValidateReceiptDateOnBeforeCalcShipmentDate` on the "Transfer Header" table. Otherwise, you cannot do some checks if the handled needs to be set.

New publisher signature:
`local procedure OnValidateShipmentDateOnBeforeCalcReceiptDate(TransferHeader: Record "Transfer Header"; var IsHandled: Boolean)`

`OnValidateReceiptDateOnBeforeCalcShipmentDate(TransferHeader: Record "Transfer Header"; var IsHandled: Boolean)`

Alternatively, set "includeSender". I dont mind.

Best regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
