### ISSUE TITLE
[Event Request] - table 81 "Gen. Journal Line" - OnBeforeGetDeferralAmount

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#13754]
You forgot to make the DeferralAmount editable.  

**wrong: "DeferralAmount: Decimal"**
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetDeferralAmount(var GenJournalLine: Record "Gen. Journal Line"; DeferralAmount: Decimal; var IsHandled: Boolean)
    begin
    end;
```
**correct: "var DeferralAmount: Decimal"**
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetDeferralAmount(var GenJournalLine: Record "Gen. Journal Line"; var DeferralAmount: Decimal; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
