### ISSUE TITLE
CalculateCFAmountAndCFDate in Cash Flow Worksheet Line not available in italian saas

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#13757]
In the Italian localization the procedure `CalculateCFAmountAndCFDate` in `table 846 "Cash Flow Worksheet Line"` is marked with OnPrem Scope.
In any other localization and w1 this procedure can be used in cloud deployments.

i think this is an extensibility bug.
Tested with current Version (18.3) and BC 19 Preview (19.0.28507.0).

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
