### ISSUE TITLE
[Event Request] - Page 9192 "Company Creation Wizard" - OnBeforeValidateCompanyType

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#13755]
Please add an event before the ValidateCompanyType procedure with a handled variable.

```
    local procedure ValidateCompanyType()
    var
        ConfigurationPackageFile: Record "Configuration Package File";
        UserPersonalization: Record "User Personalization";
        Language: Codeunit Language;
+       Handled: Boolean;
    begin
+       OnBeforeValidateCompanyType(NewCompanyData, ConfigurationPackageExists, Handled)
+       if Handled then
+           exit;
```
`ConfigurationPackageExists` and `Handled` should be called by reference.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
