### ISSUE TITLE
[Cleanup Request] Codenit 80, Function PostSalesLine

### ISSUE THREAD

**Issue by miljance** [Microsoft/ALAppExtensions#1375]
In NAV2017 new Function "TestSalesLine" was introduced in CU80 which contains all needed tests and Publishers on a Sales Line. It seems however as residue of Code is still being called after the call of this new function "TestSalesLine":
IF NOT ("Document Type" IN ["Document Type"::Invoice,"Document Type"::"Credit Memo"]) THEN
  TESTFIELD("Job No.",'');

From My point of view this residue of Code should be deleted since it is already contained in function TestSalesLine.

**Comment by JesperSchulz** [comment]
Agree. That is duplicate code. As this code now is handled through an event with handled pattern, removing the code becomes a breaking change. The change can hence only be made for the next major release in the fall. But we'll get it done.
