### ISSUE TITLE
Approvals Mgmt: RunWorkflowEntriesPage - marked internal

### ISSUE THREAD

**Issue by MikeGlue** [microsoft/ALAppExtensions#13751]
Regarding issue #13612 that was recently resolved....

I noticed that when you updated the parameter to an enum you also moved the `RunWorkflowEntriesPage` function to the Approvals Mgmt codeunit.

the problem though is that when you moved it you marked the new function as internal so now I cannot use that function in my code. Can you remove the internal property please for this function?

We've extended approvals to handle our own documents and we need to access this function in order to pass our table information. The global functions inside the Approvals Mgmt codeunit only support sales and purchase header tables.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
