### ISSUE TITLE
[Event Request] Codeunit 80 Sales Post - OnBeforeSalesInvLineInsert

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#13763]
Hi, 
would it be possible to modify the event OnBeforeSalesInvLineInsert in order to add SalesLine as a parameter, like this : 

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesInvLineInsert(var SalesInvLine: Record "Sales Invoice Line"; SalesInvHeader: Record "Sales Invoice Header"; SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line";CommitIsSuppressed: Boolean; var IsHandled: Boolean)
    begin
    end;

```
?
Thanks

**Comment by db-bc** [comment]
Also currently only taking `xSalesLine` but missing `SalesLine` are:
* `OnAfterSalesInvLineInsert`
* `OnBeforeSalesCrMemoLineInsert`
* `OnAfterSalesCrMemoLineInsert`
* possibly others; I didn't check exhaustively
* possibly the equivalents in `Purch.-Post`

`xSalesLine` is a copy of the line before rounding, made by RoundAmount()`. So it stands to reason that such events should pass `SalesLine` to get the current, possibly rounded version.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
