### ISSUE TITLE
[Event Request] Codeunit 5807 "Item Charge Assgnt. (Sales)" – Event "OnAssignByAmountOnBeforeGetSalesLine"

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#13765]
Hi,

in #8201 the event OnAssignByAmountOnBeforeGetSalesLine in Codeunit 5807 Item Charge Assgnt. (sales) was requested.
I wanted to use this Event, unfortunatly the Handler pattern is not implemented. The handled variable is passed, but not checked.
Please check the variable

Current Code:
```
 begin
      OnAssignByAmountOnBeforeGetSalesLine(SalesLine, ItemChargeAssignmentSales, IsHandled);
      SalesLine.Get(
        ItemChargeAssignmentSales."Applies-to Doc. Type",
        ItemChargeAssignmentSales."Applies-to Doc. No.",
        ItemChargeAssignmentSales."Applies-to Doc. Line No.");
      TempItemChargeAssgntSales."Applies-to Doc. Line Amount" :=
        Abs(SalesLine."Line Amount");
  end;
```

needed Code:
```
begin
    isHandled := false;
    OnAssignByAmountOnBeforeGetSalesLine(SalesLine, ItemChargeAssignmentSales, IsHandled);
    if not isHandled then 
      SalesLine.Get(
        ItemChargeAssignmentSales."Applies-to Doc. Type",
        ItemChargeAssignmentSales."Applies-to Doc. No.",
        ItemChargeAssignmentSales."Applies-to Doc. Line No.");
    TempItemChargeAssgntSales."Applies-to Doc. Line Amount" :=
      Abs(SalesLine."Line Amount");
end;
```

Thanks in advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
