### ISSUE TITLE
[Access Request] protected var - report 7 "Trial Balance/Previous Year"

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#13761]
Can you change FiscalYearStartDate, FiscalYearEndDate, LastYearStartDate, LastYearEndDate, FiscalYearBalance, FiscalYearNetChange, LastYearBalance and LastYearNetChange to proteced var in report 7 "Trial Balance/Previous Year"?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
