### ISSUE TITLE
Table 15 "G/L Account" - Field  "Account Type" - Missing Option values for spanish localization

### ISSUE THREAD

**Issue by marcoleosbz** [microsoft/ALAppExtensions#13764]
Trying to build an app on spanish localization we got an option missing error.
Building the same app on all other available localizations (~ 45) no error is thrown.

We found that in spanish localization the specific field "Account Type" of Table 15 "G/L Account"  has only 2 options.

Other 4 tables (table 841 "Cash Flow Account"  -   table 376 "G/L Account (Analysis View)" -  table 410 "IC G/L Account" - table 5488 "Trial Balance Entity Buffer")  have the same field "Account Type" . And here all (5) options are present.

![image](https://user-images.githubusercontent.com/43878853/128495930-fedb8c35-cedc-4fc6-a1b7-eebec74393cd.png)

![image](https://user-images.githubusercontent.com/43878853/128495948-cef9e52f-273c-43b6-b7ae-dccb5aacf378.png)

Is this a bug?  
Have we to create a specific app version for ES?

Thank you

**Comment by db-bc** [comment]
I would think the fix is that the field should be an `Enum`, then if ES localisers want to prevent using certain values for whatever reason, they will now have the `ValuesAllowed` property.

**Comment by AlexanderYakunin** [comment]
This is legacy deviation which happened 10+ years ago, way before we even start thinking about apps and enums. We will try to align it with W1.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
