### ISSUE TITLE
Page 370 Bank Account Card - OnBeforOnOpenPage, OnAfterSetCountrySpecificControls, & OnAfterAfterGetCurrentRecord - Event Request

### ISSUE THREAD

**Issue by ZacRyon** [microsoft/ALAppExtensions#13778]
trigger OnOpenPage()
    var
        Contact: Record Contact;
    begin
        OnBeforOnOpenPage();                // New event
        ContactActionVisible := Contact.ReadPermission;
        SetNoFieldVisible;
    end;

    local procedure SetCountrySpecificControls()
    begin
        "Client No.Enable" := "Export Format" = "Export Format"::CA;
        "Client NameEnable" := "Export Format" = "Export Format"::CA;
        "Input QualifierEnable" := "Export Format" = "Export Format"::CA;
        OnAfterSetCountrySpecificControls();
    end;

    local procedure ExportFormatOnAfterValidate()
    begin
        SetCountrySpecificControls;
    end;

    local procedure AfterGetCurrentRecord()
    begin
        xRec := Rec;
        SetCountrySpecificControls;
        OnAfterAfterGetCurrentRecord();
    end;

=================
    [IntegrationEvent(true, false)]
    local procedure OnBeforOnOpenPage();
    begin
    end;

    [IntegrationEvent(true, false)]
    local procedure OnAfterSetCountrySpecificControls()
    begin
    end;

    [IntegrationEvent(true, false)]
    local procedure OnAfterAfterGetCurrentRecord()
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
