### ISSUE TITLE
[Event Request] Page 47 - "Sales Invoice Subform"

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13770]
Dear ALAppExtensions Team,

Is it possible to add an event in page 47 - procedure CalculateTotals

    procedure CalculateTotals()
    begin
        if SuppressTotals then
            exit;

        // DINNL <<
        SalesInvoiceSubformOnBeforeCalculateTotals(TotalSalesLine);
        // DINNL >>
        DocumentTotals.SalesCheckIfDocumentChanged(Rec, xRec);
        DocumentTotals.CalculateSalesSubPageTotals(TotalSalesHeader, TotalSalesLine, VATAmount, InvoiceDiscountAmount, InvoiceDiscountPct);
        DocumentTotals.RefreshSalesLine(Rec);
    end;

    local procedure SalesInvoiceSubformOnBeforeCalculateTotals(var TotalSalesLine: Record "Sales Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
