### ISSUE TITLE
[Event Change Request] Codeunit 90 »Purch.-Post« - OnBeforePostItemChargeLine

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#13775]
Could you please change parameters "PurchHeader" and "PurchLine" to "var" in event publisher OnBeforePostItemChargeLine?
Thank you

OLD CODE

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostItemChargeLine(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

NEW CODE

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostItemChargeLine(var PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
