### ISSUE TITLE
table 8619 "Config. Template Line" request ENUM for field(3; Type; Option)

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/ALAppExtensions#13774]
Hello,

we would need that field(3; Type; Option) from table 8619 "Config. Template Line" be converted to ENUM.
We need to extend this field.
![image](https://user-images.githubusercontent.com/53824412/128836648-c66db75a-1b76-4eec-9deb-e58cb3bb9d86.png)

Thank you in advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
