### ISSUE TITLE
codeunit 6620 "Copy Document Mgt." - OnAfterCopyPurchLine, OnEndOfCopyFieldsFromOldPurchHeader, & OnAfterUpdateVendLedgEntry - Event Request

### ISSUE THREAD

**Issue by ZacRyon** [microsoft/ALAppExtensions#13789]
codeunit 6620 "Copy Document Mgt."
{

...

    procedure CopyFieldsFromOldPurchHeader(var ToPurchHeader: Record "Purchase Header"; OldPurchHeader: Record "Purchase Header")
    begin
        OnBeforeCopyFieldsFromOldPurchHeader(ToPurchHeader, OldPurchHeader);

        with ToPurchHeader do begin
            "No. Series" := OldPurchHeader."No. Series";
            "Posting Description" := OldPurchHeader."Posting Description";
            "Posting No." := OldPurchHeader."Posting No.";
            "Posting No. Series" := OldPurchHeader."Posting No. Series";
            "Receiving No." := OldPurchHeader."Receiving No.";
            "Receiving No. Series" := OldPurchHeader."Receiving No. Series";
            "Return Shipment No." := OldPurchHeader."Return Shipment No.";
            "Return Shipment No. Series" := OldPurchHeader."Return Shipment No. Series";
            "Prepayment No. Series" := OldPurchHeader."Prepayment No. Series";
            "Prepayment No." := OldPurchHeader."Prepayment No.";
            "Prepmt. Posting Description" := OldPurchHeader."Prepmt. Posting Description";
            "Prepmt. Cr. Memo No. Series" := OldPurchHeader."Prepmt. Cr. Memo No. Series";
            "Prepmt. Cr. Memo No." := OldPurchHeader."Prepmt. Cr. Memo No.";
            "Prepmt. Posting Description" := OldPurchHeader."Prepmt. Posting Description";
            SetSalespersonPurchaserCode("Purchaser Code");
            OnEndOfCopyFieldsFromOldPurchHeader(ToPurchHeader, OldPurchHeader);
        end;
    end;

...

    procedure CopyFieldsFromOldPurchHeader(var ToPurchHeader: Record "Purchase Header"; OldPurchHeader: Record "Purchase Header")
    begin
        OnBeforeCopyFieldsFromOldPurchHeader(ToPurchHeader, OldPurchHeader);

        with ToPurchHeader do begin
            "No. Series" := OldPurchHeader."No. Series";
            "Posting Description" := OldPurchHeader."Posting Description";
            "Posting No." := OldPurchHeader."Posting No.";
            "Posting No. Series" := OldPurchHeader."Posting No. Series";
            "Receiving No." := OldPurchHeader."Receiving No.";
            "Receiving No. Series" := OldPurchHeader."Receiving No. Series";
            "Return Shipment No." := OldPurchHeader."Return Shipment No.";
            "Return Shipment No. Series" := OldPurchHeader."Return Shipment No. Series";
            "Prepayment No. Series" := OldPurchHeader."Prepayment No. Series";
            "Prepayment No." := OldPurchHeader."Prepayment No.";
            "Prepmt. Posting Description" := OldPurchHeader."Prepmt. Posting Description";
            "Prepmt. Cr. Memo No. Series" := OldPurchHeader."Prepmt. Cr. Memo No. Series";
            "Prepmt. Cr. Memo No." := OldPurchHeader."Prepmt. Cr. Memo No.";
            "Prepmt. Posting Description" := OldPurchHeader."Prepmt. Posting Description";
            SetSalespersonPurchaserCode("Purchaser Code");
            OnEndOfCopyFieldsFromOldPurchHeader(ToPurchHeader, OldPurchHeader);
        end;
    end;

...

    procedure UpdateVendLedgEntry(var ToPurchHeader: Record "Purchase Header"; FromDocType: Enum "Gen. Journal Document Type"; FromDocNo: Code[20])
    var
        VendLedgEntry: Record "Vendor Ledger Entry";
    begin
        OnBeforeUpdateVendLedgEntry(ToPurchHeader, VendLedgEntry);

        VendLedgEntry.SetCurrentKey("Document No.");
        if FromDocType = "Purchase Document Type From"::"Posted Invoice" then
            VendLedgEntry.SetRange("Document Type", VendLedgEntry."Document Type"::Invoice)
        else
            VendLedgEntry.SetRange("Document Type", VendLedgEntry."Document Type"::"Credit Memo");
        VendLedgEntry.SetRange("Document No.", FromDocNo);
        VendLedgEntry.SetRange("Vendor No.", ToPurchHeader."Pay-to Vendor No.");
        VendLedgEntry.SetRange(Open, true);
        if VendLedgEntry.FindFirst then begin
            if FromDocType = "Purchase Document Type From"::"Posted Invoice" then begin
                ToPurchHeader."Applies-to Doc. Type" := ToPurchHeader."Applies-to Doc. Type"::Invoice;
                ToPurchHeader."Applies-to Doc. No." := FromDocNo;
            end else begin
                ToPurchHeader."Applies-to Doc. Type" := ToPurchHeader."Applies-to Doc. Type"::"Credit Memo";
                ToPurchHeader."Applies-to Doc. No." := FromDocNo;
            end;
            VendLedgEntry.CalcFields("Remaining Amount");
            VendLedgEntry."Amount to Apply" := VendLedgEntry."Remaining Amount";
            VendLedgEntry."Accepted Payment Tolerance" := 0;
            VendLedgEntry."Accepted Pmt. Disc. Tolerance" := false;
            CODEUNIT.Run(CODEUNIT::"Vend. Entry-Edit", VendLedgEntry);
            OnAfterUpdateVendLedgEntry(ToPurchHeader, FromDocNo);
        end;
    end;

...

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyPurchLine(CopyThisLine: Boolean; var ToPurchLine: Record "Purchase Line")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnEndOfCopyFieldsFromOldPurchHeader(var ToPurchHeader: Record "Purchase Header"; var OldPurchHeader: Record "Purchase Header")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateVendLedgEntry(var ToPurchHeader: Record "Purchase Header"; var FromDocNo: Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
