### ISSUE TITLE
codeunit 10142 "Deposit-Post + Print" - OnAfterOnRun - Event Request

### ISSUE THREAD

**Issue by ZacRyon** [microsoft/ALAppExtensions#13797]
codeunit 10142 "Deposit-Post + Print"
{
    TableNo = "Deposit Header";

    trigger OnRun()
    begin
        DepositHeader.Copy(Rec);

        if not Confirm(Text000, false) then
            exit;

        DepositPost.Run(DepositHeader);
        Rec := DepositHeader;
        Commit();

        if PostedDepositHeader.Get("No.") then begin
            PostedDepositHeader.SetRecFilter;
            //NPO begin
            IsHandled := false;
            OnAfterOnRun(PostedDepositHeader, IsHandled);
            if IsHandled then 
                exit;
            //NPO end
            REPORT.Run(REPORT::Deposit, false, false, PostedDepositHeader);
        end;
    end;

    var
        DepositHeader: Record "Deposit Header";
        PostedDepositHeader: Record "Posted Deposit Header";
        DepositPost: Codeunit "Deposit-Post";
        Text000: Label 'Do you want to post and print the Deposit?';
        IsHandled: Boolean; //NPO

    //NPO begin
    [IntegrationEvent(false, false)]
    local procedure OnAfterOnRun(var PostedDepositHeader: Record "Posted Deposit Header"; var IsHandled: Boolean)
    begin
    end;
    //NPO end
}

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
