### ISSUE TITLE
Which environment to use for development as an ISV ?? bcsandbox or OnPrem sandbox ??

### ISSUE THREAD

**Issue by shashiBssi** [Microsoft/ALAppExtensions#138]

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!

**Comment by StanislawStempin** [comment]
To get help for general questions please use one of the following resources:
[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)
