### ISSUE TITLE
[Event Modification]  page 6510 "Item Tracking Lines" OnAfterSetSourceSpec

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13808]
Hello, 

Is it possible to add the following to an event 

        OnAfterSetSourceSpec(TrackingSpecification, Rec, AvailabilityDate, BlockCommit);

to 

        OnAfterSetSourceSpec(TrackingSpecification, Rec, AvailabilityDate, BlockCommit, FunctionsDemandVisible, FunctionsSupplyVisible, QtyToHandleBaseEditable, QuantityBaseEditable, InsertIsBlocked);

QtyToHandleBaseEditable, QuantityBaseEditable, InsertIsBlocked as var

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
