### ISSUE TITLE
table 5203 "Employee Qualification" - OnBeforeOnLookupOnEmployeeNoField - Event Request

### ISSUE THREAD

**Issue by ZacRyon** [microsoft/ALAppExtensions#13802]
table 5203 "Employee Qualification"
{
    Caption = 'Employee Qualification';
    DataCaptionFields = "Employee No.";
    DrillDownPageID = "Qualified Employees";
    LookupPageID = "Employee Qualifications";

    fields
    {
        field(1; "Employee No."; Code[20])
        {
            Caption = 'Employee No.';
            NotBlank = true;
            //NPO Begin
            //TableRelation = Employee;

            trigger OnLookup()
            begin
                OnBeforeOnLookupOnEmployeeNoField();
            end;
            //NPO End
        }
        field(2; "Line No."; Integer)
        {
            Caption = 'Line No.';
        }
        field(3; "Qualification Code"; Code[10])
        {
            Caption = 'Qualification Code';
            TableRelation = Qualification;

            trigger OnValidate()
            begin
                Qualification.Get("Qualification Code");
                Description := Qualification.Description;
            end;
        }
        field(4; "From Date"; Date)
        {
            Caption = 'From Date';
        }
        field(5; "To Date"; Date)
        {
            Caption = 'To Date';
        }
        field(6; Type; Option)
        {
            Caption = 'Type';
            OptionCaption = ' ,Internal,External,Previous Position';
            OptionMembers = " ",Internal,External,"Previous Position";
        }
        field(7; Description; Text[100])
        {
            Caption = 'Description';
        }
        field(8; "Institution/Company"; Text[100])
        {
            Caption = 'Institution/Company';
        }
        field(9; Cost; Decimal)
        {
            AutoFormatType = 1;
            Caption = 'Cost';
        }
        field(10; "Course Grade"; Text[50])
        {
            Caption = 'Course Grade';
        }
        field(11; "Employee Status"; Enum "Employee Status")
        {
            Caption = 'Employee Status';
            Editable = false;
        }
        field(12; Comment; Boolean)
        {
            CalcFormula = Exist("Human Resource Comment Line" WHERE("Table Name" = CONST("Employee Qualification"),
                                                                     "No." = FIELD("Employee No."),
                                                                     "Table Line No." = FIELD("Line No.")));
            Caption = 'Comment';
            Editable = false;
            FieldClass = FlowField;
        }
        field(13; "Expiration Date"; Date)
        {
            Caption = 'Expiration Date';
        }
    }

    keys
    {
        key(Key1; "Employee No.", "Line No.")
        {
            Clustered = true;
        }
        key(Key2; "Qualification Code")
        {
        }
        //K12 Begin
        key(Key3; "Employee No.", "Qualification Code", "From Date")
        {
        }
        //K12 End
    }

    fieldgroups
    {
    }

    trigger OnDelete()
    begin
        //NVPN Begin
        //if Comment then
        //    Error(Text000);
        //NVP End
    end;

    trigger OnInsert()
    begin
        //NVP Begin
        //Employee.Get("Employee No.");
        //"Employee Status" := Employee.Status;
        //NVP End
    end;

    var
        Text000: Label 'You cannot delete employee qualification information if there are comments associated with it.';
        Qualification: Record Qualification;
        Employee: Record Employee;

    //NVP Begin
    [IntegrationEvent(true, false)]
    local procedure OnBeforeOnLookupOnEmployeeNoField()
    begin
    end;
    //NVP End
}

**Comment by Stepanenko-Vadim** [comment]
We cannot add a new empty on lookup trigger as this will break lookup for all other clients/scenarios.
