### ISSUE TITLE
table 368 "Dimension Selection Buffer" - OnBeforeDimSelectionMultipleInsertDimSelBuf, OnBeforeDimSelectionChangeInsertDimSelBuf, OnBeforeAddDimCodeToText,  OnAfterSetDefaultRangeOnSelectedDimTable, & OnBeforeSelectedDimInsert - Event Request

### ISSUE THREAD

**Issue by ZacRyon** [microsoft/ALAppExtensions#13800]
table 368 "Dimension Selection Buffer"
{
    Caption = 'Dimension Selection Buffer';
    ReplicateData = false;

    fields
    {
        field(1; "Code"; Text[30])
        {
            Caption = 'Code';
            DataClassification = SystemMetadata;
        }
        field(2; Description; Text[30])
        {
            Caption = 'Description';
            DataClassification = SystemMetadata;
        }
        field(3; Selected; Boolean)
        {
            Caption = 'Selected';
            DataClassification = SystemMetadata;

            trigger OnValidate()
            begin
                "New Dimension Value Code" := '';
                "Dimension Value Filter" := '';
                Level := Level::" ";
            end;
        }
        field(4; "New Dimension Value Code"; Code[20])
        {
            Caption = 'New Dimension Value Code';
            DataClassification = SystemMetadata;
            TableRelation = IF (Code = CONST('G/L Account')) "G/L Account"."No."
            ELSE
            IF (Code = CONST('Business Unit')) "Business Unit".Code
            ELSE
            "Dimension Value".Code WHERE("Dimension Code" = FIELD(Code));

            trigger OnValidate()
            begin
                Selected := true;
            end;
        }
        field(5; "Dimension Value Filter"; Code[250])
        {
            Caption = 'Dimension Value Filter';
            DataClassification = SystemMetadata;
            TableRelation = IF ("Filter Lookup Table No." = CONST(15)) "G/L Account"."No."
            ELSE
            IF ("Filter Lookup Table No." = CONST(220)) "Business Unit".Code
            ELSE
            IF ("Filter Lookup Table No." = CONST(841)) "Cash Flow Account"."No."
            ELSE
            IF ("Filter Lookup Table No." = CONST(840)) "Cash Flow Forecast"."No."
            ELSE
            "Dimension Value".Code WHERE("Dimension Code" = FIELD(Code));
            ValidateTableRelation = false;

            trigger OnValidate()
            begin
                if (Level = Level::" ") and ("Dimension Value Filter" = '') then
                    Selected := false
                else
                    Selected := true;
            end;
        }
        field(6; Level; Option)
        {
            Caption = 'Level';
            DataClassification = SystemMetadata;
            OptionCaption = ' ,Level 1,Level 2,Level 3,Level 4';
            OptionMembers = " ","Level 1","Level 2","Level 3","Level 4";

            trigger OnValidate()
            begin
                if (Level = Level::" ") and ("Dimension Value Filter" = '') then
                    Selected := false
                else
                    Selected := true;
            end;
        }
        field(7; "Filter Lookup Table No."; Integer)
        {
            Caption = 'Filter Lookup Table No.';
            DataClassification = SystemMetadata;
            Editable = false;
            InitValue = 349;
        }
    }

    keys
    {
        key(Key1; "Code")
        {
            Clustered = true;
        }
        key(Key2; Level, "Code")
        {
        }
    }

    fieldgroups
    {
    }

    var
        Text000: Label 'Another user has modified the selected dimensions for the %1 field after you retrieved it from the database.\';
        Text002: Label 'Enter your changes again in the Dimension Selection window by clicking the AssistButton on the %1 field. ';

    procedure SetDimSelectionMultiple(ObjectType: Integer; ObjectID: Integer; var SelectedDimText: Text[250])
    var
        SelectedDim: Record "Selected Dimension";
        Dim: Record Dimension;
        TempDimSelectionBuf: Record "Dimension Selection Buffer" temporary;
        DimSelectionMultiple: Page "Dimension Selection-Multiple";
        IsHandled: Boolean;  //K12
    begin
        Clear(DimSelectionMultiple);
        if Dim.Find('-') then
            repeat
                //NPO Begin
                IsHandled := false;
                OnBeforeDimSelectionMultipleInsertDimSelBuf(DimSelectionMultiple, Dim, ObjectID, ObjectType, IsHandled);
                if not IsHandled then
                //NPO End
					DimSelectionMultiple.InsertDimSelBuf(
						SelectedDim.Get(UserId, ObjectType, ObjectID, '', Dim.Code),
						Dim.Code, Dim.GetMLName(GlobalLanguage));
            until Dim.Next() = 0;

        if DimSelectionMultiple.RunModal = ACTION::OK then begin
            DimSelectionMultiple.GetDimSelBuf(TempDimSelectionBuf);
            SetDimSelection(ObjectType, ObjectID, '', SelectedDimText, TempDimSelectionBuf);
        end;
    end;

    procedure SetDimSelectionChange(ObjectType: Integer; ObjectID: Integer; var SelectedDimText: Text[250])
    var
        SelectedDim: Record "Selected Dimension";
        Dim: Record Dimension;
        TempDimSelectionBuf: Record "Dimension Selection Buffer" temporary;
        DimSelectionChange: Page "Dimension Selection-Change";
        IsHandled: Boolean;  //NPO
    begin
        Clear(DimSelectionChange);
        if Dim.Find('-') then
            repeat
                //NPO Begin
                IsHandled := false;
                OnBeforeDimSelectionChangeInsertDimSelBuf(DimSelectionChange, Dim, ObjectID, ObjectType, IsHandled);
                if not IsHandled then
                //NPO End
                DimSelectionChange.InsertDimSelBuf(
                  SelectedDim.Get(UserId, ObjectType, ObjectID, '', Dim.Code),
                  Dim.Code, Dim.GetMLName(GlobalLanguage),
                  SelectedDim."New Dimension Value Code",
                  SelectedDim."Dimension Value Filter");
            until Dim.Next() = 0;

        if DimSelectionChange.RunModal = ACTION::OK then begin
            DimSelectionChange.GetDimSelBuf(TempDimSelectionBuf);
            SetDimSelection(ObjectType, ObjectID, '', SelectedDimText, TempDimSelectionBuf);
        end;

        OnAfterSetDimSelectionChange(Rec, TempDimSelectionBuf);
    end;

    procedure CompareDimText(ObjectType: Integer; ObjectID: Integer; AnalysisViewCode: Code[10]; SelectedDimText: Text[250]; DimTextFieldName: Text[100])
    var
        SelectedDim: Record "Selected Dimension";
        SelectedDimTextFromDb: Text[250];
    begin
        SelectedDimTextFromDb := '';
        SelectedDim.SetCurrentKey(
          "User ID", "Object Type", "Object ID", "Analysis View Code", Level, "Dimension Code");
        SetDefaultRangeOnSelectedDimTable(SelectedDim, ObjectType, ObjectID, AnalysisViewCode);
        //NPO Begin
        OnBeforeAddDimCodeToText(SelectedDim, ObjectID);
        //NPO End
        if SelectedDim.Find('-') then
            repeat
                AddDimCodeToText(SelectedDim."Dimension Code", SelectedDimTextFromDb);
            until SelectedDim.Next() = 0;
        if SelectedDimTextFromDb <> SelectedDimText then
            Error(
              Text000 +
              Text002,
              DimTextFieldName);
    end;

    local procedure AddDimCodeToText(DimCode: Code[30]; var Text: Text[250])
    begin
        if Text = '' then
            Text := DimCode
        else
            if (StrLen(Text) + StrLen(DimCode)) <= (MaxStrLen(Text) - 4) then
                Text := StrSubstNo('%1;%2', Text, DimCode)
            else
                if CopyStr(Text, StrLen(Text) - 2, 3) <> '...' then
                    Text := StrSubstNo('%1;...', Text)
    end;

    procedure SetDimSelection(ObjectType: Integer; ObjectID: Integer; AnalysisViewCode: Code[10]; var SelectedDimText: Text[250]; var DimSelectionBuf: Record "Dimension Selection Buffer")
    var
        SelectedDim: Record "Selected Dimension";
        IsHandled: Boolean;  //NPO
    begin
        SetDefaultRangeOnSelectedDimTable(SelectedDim, ObjectType, ObjectID, AnalysisViewCode);
        //NPO Begin
        OnAfterSetDefaultRangeOnSelectedDimTable(SelectedDim, ObjectID);
        //NPO End
        SelectedDim.DeleteAll();
        SelectedDimText := '';
        DimSelectionBuf.SetCurrentKey(Level, Code);
        DimSelectionBuf.SetRange(Selected, true);
        if DimSelectionBuf.Find('-') then begin
            repeat
                //NPO Begin
                IsHandled := false;
                OnBeforeSelectedDimInsert(ObjectID, IsHandled);
                if not IsHandled then
					SelectedDim."User ID" := UserId;
                //NPO End
                
                SelectedDim."Object Type" := ObjectType;
                SelectedDim."Object ID" := ObjectID;
                SelectedDim."Analysis View Code" := AnalysisViewCode;
                SelectedDim."Dimension Code" := DimSelectionBuf.Code;
                SelectedDim."New Dimension Value Code" := DimSelectionBuf."New Dimension Value Code";
                SelectedDim."Dimension Value Filter" := DimSelectionBuf."Dimension Value Filter";
                SelectedDim.Level := DimSelectionBuf.Level;
                SelectedDim.Insert();
            until DimSelectionBuf.Next() = 0;
            SelectedDimText := GetDimSelectionText(ObjectType, ObjectID, AnalysisViewCode);
        end;
    end;

    procedure SetDimSelectionLevelGLAcc(ObjectType: Integer; ObjectID: Integer; AnalysisViewCode: Code[10]; var SelectedDimText: Text[250])
    var
        GLAcc: Record "G/L Account";
    begin
        SetDimSelectionLevelWithAutoSet(ObjectType, ObjectID, AnalysisViewCode, SelectedDimText, GLAcc.TableCaption, false);
    end;

    procedure SetDimSelectionLevelGLAccAutoSet(ObjectType: Integer; ObjectID: Integer; AnalysisViewCode: Code[10]; var SelectedDimText: Text[250])
    var
        GLAcc: Record "G/L Account";
    begin
        SetDimSelectionLevelWithAutoSet(ObjectType, ObjectID, AnalysisViewCode, SelectedDimText, GLAcc.TableCaption, true);
    end;

    procedure SetDimSelectionLevelCFAcc(ObjectType: Integer; ObjectID: Integer; AnalysisViewCode: Code[10]; var SelectedDimText: Text[250])
    var
        CFAcc: Record "Cash Flow Account";
    begin
        SetDimSelectionLevelWithAutoSet(ObjectType, ObjectID, AnalysisViewCode, SelectedDimText, CFAcc.TableCaption, false);
    end;

    local procedure SetDimSelectionLevelWithAutoSet(ObjectType: Integer; ObjectID: Integer; AnalysisViewCode: Code[10]; var SelectedDimText: Text[250]; AccTableCaption: Text[30]; AutoSet: Boolean)
    var
        SelectedDim: Record "Selected Dimension";
        AnalysisView: Record "Analysis View";
        Dim: Record Dimension;
        TempDimSelectionBuf: Record "Dimension Selection Buffer" temporary;
        DimSelectionLevel: Page "Dimension Selection-Level";
        SelectedDimLevel: Option;
        GetSelectedDim: Boolean;
        Finished: Boolean;
    begin
        Clear(DimSelectionLevel);
        if AnalysisView.Get(AnalysisViewCode) then begin
            if Dim.Get(AnalysisView."Dimension 1 Code") then begin
                GetSelectedDim := SelectedDim.Get(UserId, ObjectType, ObjectID, AnalysisViewCode, Dim.Code);
                if AutoSet and not (SelectedDim.Level <> SelectedDim.Level::" ") then begin
                    SelectedDimLevel := SelectedDim.Level::"Level 2";
                    GetSelectedDim := true;
                end else
                    SelectedDimLevel := SelectedDim.Level;

                DimSelectionLevel.InsertDimSelBuf(
                  GetSelectedDim,
                  Dim.Code, Dim.GetMLName(GlobalLanguage),
                  SelectedDim."Dimension Value Filter", SelectedDimLevel);
            end;

            if Dim.Get(AnalysisView."Dimension 2 Code") then
                DimSelectionLevel.InsertDimSelBuf(
                  SelectedDim.Get(UserId, ObjectType, ObjectID, AnalysisViewCode, Dim.Code),
                  Dim.Code, Dim.GetMLName(GlobalLanguage),
                  SelectedDim."Dimension Value Filter", SelectedDim.Level);

            if Dim.Get(AnalysisView."Dimension 3 Code") then
                DimSelectionLevel.InsertDimSelBuf(
                  SelectedDim.Get(UserId, ObjectType, ObjectID, AnalysisViewCode, Dim.Code),
                  Dim.Code, Dim.GetMLName(GlobalLanguage),
                  SelectedDim."Dimension Value Filter", SelectedDim.Level);

            if Dim.Get(AnalysisView."Dimension 4 Code") then
                DimSelectionLevel.InsertDimSelBuf(
                  SelectedDim.Get(UserId, ObjectType, ObjectID, AnalysisViewCode, Dim.Code),
                  Dim.Code, Dim.GetMLName(GlobalLanguage),
                  SelectedDim."Dimension Value Filter", SelectedDim.Level);

            GetSelectedDim := SelectedDim.Get(UserId, ObjectType, ObjectID, AnalysisViewCode, AccTableCaption);
            if AutoSet and not (SelectedDim.Level <> SelectedDim.Level::" ") then
                SelectedDimLevel := SelectedDim.Level::"Level 1"
            else
                SelectedDimLevel := SelectedDim.Level;

            DimSelectionLevel.InsertDimSelBuf(
              GetSelectedDim,
              AccTableCaption, AccTableCaption,
              SelectedDim."Dimension Value Filter", SelectedDimLevel);
        end;

        if not AutoSet then
            Finished := DimSelectionLevel.RunModal = ACTION::OK
        else
            Finished := true;

        if Finished then begin
            DimSelectionLevel.GetDimSelBuf(TempDimSelectionBuf);
            SetDimSelection(ObjectType, ObjectID, AnalysisViewCode, SelectedDimText, TempDimSelectionBuf);
        end;
    end;

    procedure GetDimSelectionText(ObjectType: Integer; ObjectID: Integer; AnalysisViewCode: Code[10]): Text[250]
    var
        SelectedDim: Record "Selected Dimension";
        SelectedDimText: Text[250];
    begin
        SetDefaultRangeOnSelectedDimTable(SelectedDim, ObjectType, ObjectID, AnalysisViewCode);
        //NPO Begin
        OnAfterSetDefaultRangeOnSelectedDimTable(SelectedDim, ObjectID);
        //NPO End
        SelectedDim.SetCurrentKey("User ID", "Object Type", "Object ID", "Analysis View Code", Level, "Dimension Code");
        with SelectedDim do begin
            if Find('-') then
                repeat
                    AddDimCodeToText("Dimension Code", SelectedDimText);
                until Next() = 0;
        end;
        exit(SelectedDimText);
    end;

    local procedure SetDefaultRangeOnSelectedDimTable(var SelectedDim: Record "Selected Dimension"; ObjectType: Integer; ObjectID: Integer; AnalysisViewCode: Code[10])
    begin
        SelectedDim.SetRange("User ID", UserId);
        SelectedDim.SetRange("Object Type", ObjectType);
        SelectedDim.SetRange("Object ID", ObjectID);
        SelectedDim.SetRange("Analysis View Code", AnalysisViewCode);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetDimSelectionChange(var DimensionSelectionBuffer: Record "Dimension Selection Buffer"; var TheDimSelectionBuf: Record "Dimension Selection Buffer" temporary)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDimSelectionMultipleInsertDimSelBuf(var DimSelectionMultiple: Page "Dimension Selection-Multiple"; var Dim: Record Dimension; ObjectID: Integer; ObjectType: Integer; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDimSelectionChangeInsertDimSelBuf(var DimSelectionChange: Page "Dimension Selection-Change"; var Dim: Record Dimension; ObjectID: Integer; ObjectType: Integer; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAddDimCodeToText(var SelectedDim: Record "Selected Dimension"; ObjectID: Integer)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetDefaultRangeOnSelectedDimTable(var SelectedDim: Record "Selected Dimension"; ObjectID: Integer)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSelectedDimInsert(ObjectID: Integer; var IsHandled: Boolean)
    begin
    end;
}

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
