### ISSUE TITLE
[Event Request] page 95 "Sales Quote Subform"  SalesQuoteSubformOnCalculateTotals

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13805]
Hello,   Is it possible to get the following event: 

    procedure CalculateTotals()
    begin
        if SuppressTotals then
            exit;

        //DINNL <<
        SalesQuoteSubformOnCalculateTotals(TotalSalesLine);
        // DINNL >>
        DocumentTotals.SalesCheckIfDocumentChanged(Rec, xRec);
        DocumentTotals.CalculateSalesSubPageTotals(TotalSalesHeader, TotalSalesLine, VATAmount, InvoiceDiscountAmount, InvoiceDiscountPct);
        DocumentTotals.RefreshSalesLine(Rec);
    end;

    [IntegrationEvent(false, false)]
    local procedure SalesQuoteSubformOnCalculateTotals(var TotalSalesLine: Record "Sales Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
