### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" OnDeleteRecordAfterWMSCheckTrackingChange

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13807]
Hello, 

Is it possible to get the following event: 

trigger OnDeleteRecord(): Boolean
    var
        TrackingSpec: Record "Tracking Specification";
        WMSManagement: Codeunit "WMS Management";
        AlreadyDeleted: Boolean;
    begin
        OnBeforeDeleteRecord(Rec);

        TrackingSpec."Item No." := Rec."Item No.";
        TrackingSpec."Location Code" := Rec."Location Code";
        TrackingSpec."Source Type" := Rec."Source Type";
        TrackingSpec."Source Subtype" := Rec."Source Subtype";
        WMSManagement.CheckItemTrackingChange(TrackingSpec, Rec);

        // DINNL <<
        DINOnDeleteRecordAfterWMSCheckTrackingChange(TrackingSpec, Rec);
        // DINNL >>
        if not DeleteIsBlocked then begin
            AlreadyDeleted := TempItemTrackLineDelete.Get(Rec."Entry No.");
            TempItemTrackLineDelete.TransferFields(Rec);
            Rec.Delete(true);

            if not AlreadyDeleted then
                TempItemTrackLineDelete.Insert();
            ItemTrackingDataCollection.UpdateTrackingDataSetWithChange(
              TempItemTrackLineDelete, CurrentSignFactor * SourceQuantityArray[1] < 0, CurrentSignFactor, 2);
            if TempItemTrackLineInsert.Get(Rec."Entry No.") then
                TempItemTrackLineInsert.Delete();
            if TempItemTrackLineModify.Get(Rec."Entry No.") then

    [IntegrationEvent(false, false)]
    local procedure DINOnDeleteRecordAfterWMSCheckTrackingChange(TrackingSpecification: Record "Tracking Specification"; xTrackingSpecification: Record "Tracking Specification")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
