### ISSUE TITLE
[Event Request] page 6500 "Item Tracking Summary" SetSourcesOnAfterxEntrySummarySetview

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13806]
Hello, 

Is it possible to get the following event: 

    procedure SetSources(var ReservEntry: Record "Reservation Entry"; var EntrySummary: Record "Entry Summary")
    var
        xEntrySummary: Record "Entry Summary";
    begin
        TempReservEntry.Reset();
        TempReservEntry.DeleteAll();
        if ReservEntry.Find('-') then
            repeat
                TempReservEntry := ReservEntry;
                TempReservEntry.Insert();
            until ReservEntry.Next() = 0;

        xEntrySummary.SetView(Rec.GetView());
        // DINNL <<
        DINSetSourcesOnAfterxEntrySummarySetview(xEntrySummary);
        // DINNL >>
        Rec.Reset;
        Rec.DeleteAll();
        if EntrySummary.FindSet() then
            repeat
                if EntrySummary.HasQuantity then begin
                    Rec := EntrySummary;
                    Rec.Insert();
                end;
            until EntrySummary.Next() = 0;
        Rec.SetView(xEntrySummary.GetView());
        UpdateSelectedQuantity();
    end;

    [IntegrationEvent(false, false)]
    local procedure DINSetSourcesOnAfterxEntrySummarySetview(var xEntrySummary: Record "Entry Summary")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
