### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines"  OnAddToGlobalRecordSetAfterTrackingSpecificationCalcSums

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13813]
Hello, 

Is it possible to get the following event:

        if TempTrackingSpecification.Find('-') then
            repeat
                TempTrackingSpecification.SetTrackingFilterFromSpec(TempTrackingSpecification);
                TempTrackingSpecification.CalcSums("Quantity (Base)", "Qty. to Handle (Base)",
                  "Qty. to Invoice (Base)", "Quantity Handled (Base)", "Quantity Invoiced (Base)");
                // DINNL <<
                DINOnAddToGlobalRecordSetAfterTrackingSpecificationCalcSums(TempTrackingSpecification);
                // DINNL >>

                if TempTrackingSpecification."Quantity (Base)" <> 0 then begin
                    Rec := TempTrackingSpecification;
                    Rec."Quantity (Base)" *= CurrentSignFactor;
                    Rec."Qty. to Handle (Base)" *= CurrentSignFactor;
                    Rec."Qty. to Invoice (Base)" *= CurrentSignFactor;

    [IntegrationEvent(false, false)]
    local procedure DINOnAddToGlobalRecordSetAfterTrackingSpecificationCalcSums(var TempTrackingSpecification: record "Tracking Specification" temporary);
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
