### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" OnAddToGlobalRecordSetAfterTrackingSpecificationSetCurrentKey

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13811]
Hello, 

Is it possible to get the following event:    

 local procedure AddToGlobalRecordSet(var TempTrackingSpecification: Record "Tracking Specification" temporary)
    var
        ExpDate: Date;
        EntriesExist: Boolean;
    begin
        TempTrackingSpecification.SetCurrentKey("Lot No.", "Serial No.");
        // DINNL <<
        DINOnAddToGlobalRecordSetAfterTrackingSpecificationSetCurrentKey(TempTrackingSpecification);
        // DINNL >>

        if TempTrackingSpecification.Find('-') then
            repeat

    [IntegrationEvent(false, false)]
    local procedure DINOnAddToGlobalRecordSetAfterTrackingSpecificationSetCurrentKey(var TempTrackingSpecification: record "Tracking Specification" temporary);
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
