### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" OnCalculateSumsAfterCalcSums

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13815]
Hello, 

Is it possible to get the following event: 

    procedure CalculateSums()
    var
        xTrackingSpec: Record "Tracking Specification";
    begin
        xTrackingSpec.Copy(Rec);
        Rec.Reset();
        Rec.CalcSums("Quantity (Base)", "Qty. to Handle (Base)", "Qty. to Invoice (Base)");
        // DINNL <<
        DINOnCalculateSumsAfterCalcSums(Rec);
        // DINNL >>
        TotalItemTrackingLine := Rec;
        Rec.Copy(xTrackingSpec);

        UpdateUndefinedQtyArray();
    end;

    [IntegrationEvent(false, false)]
    local procedure DINOnCalculateSumsAfterCalcSums(var TrackingSpecification: Record "Tracking Specification");
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
