### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" OnWriteToDatabaseBeforeUpdateOrderTracking

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13817]
Hello, 

Is it possible to get the following event: 

                        xTempItemTrackingLine.Insert();
                    end else
                        Error(Text005);
                    SetQtyToHandleAndInvoice(Rec);
                    Rec.Delete();
                until Rec.Next() = 0;
        end;
        // DINNL <<
        DINOnWriteToDatabaseBeforeUpdateOrderTracking(TempReservEntry);
        // DINNL >>

        UpdateOrderTrackingAndReestablishReservation();

    [IntegrationEvent(false, false)]
    local procedure DINOnWriteToDatabaseBeforeUpdateOrderTracking(var TempReservEntry: Record "Reservation Entry" temporary);
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
