### ISSUE TITLE
[Extensibility Enhancement] Table 290 - VAT Amount Line - CopyFrom...Line - "VAT Clause Code" missing + Apply procedures in "Standard" reports

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#13826]
Dear ALAppExtensions team,

Through this issue we would like to report that copying the "VAT Clause Code" is missing in the `CopyFrom...Line` methods in the `VAT Amount Line` table.

Note that this exact same code is duplicated throughout the Microsoft "Standard" reports for inserting VAT Amount Line records rather than using these procedures.
It would be a major extensibility enhancement if you could have the reports use the `CalcVATAmountLines` procedures rather than duplicating the code, so that if we have subscribers on the corresponding events, they will also cover usage in reports, where this is currently not possible.

To summarize:
1. The `VATAmountLine` table has multiple `CopyFrom...Line` procedures (e.g., `CopyFromPurchInvLine`, `CopyFromPurchCrMemoLine`, `CopyFromSalesInvLine`, `CopyFromSalesCrMemoLine`, `CopyFromServInvLine`, `CopyFromServCrMemoLine`), but they are missing the "VAT Clause Code" from being copied from the record to the VAT Amount Line. Could you please add this to align this with how the Standard reports actually do this?

   There are no `CopyFromSalesLine`/`CopyFromPurchLine`/`CopyFromServLine` procedures. Instead for Sales Lines and Purchase Lines copying from the record to the VAT Amount Line is still being done in-line in the `CalcVATAmountLines` procedures. Could you please align this for these record types as well?

2. Could you please have the "Standard" reports leverage these procedures (e.g., `CalcVATAmountLines`) as well? This would improve extensibility for us, i.e., if we are to add an event subscriber, the code we add will also be applied for reports retrieving VAT Amount Lines.

Thank you in advance for your time and efforts!

**Comment by rvanbekkum** [comment]
Does not seem to apply for Purchase though, but it does for Sales and Service - the "Standard Sales Order Confirmation" report is actually going wrong with the VAT Clause dataitem due to the missing statement for copying the "VAT Clause Code".

**Comment by AndersLarsenMicrosoft** [comment]
Old issues without any fresh history. Closed for now

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.

**Comment by rvanbekkum** [comment]
> Old issues without any fresh history. Closed for now

@AndersLarsenMicrosoft Will this request be shipped in a future update? I am now wondering whether the automatically-generated reply from @JesperSchulz is correct or not. :)

**Comment by JesperSchulz** [comment]
> > Old issues without any fresh history. Closed for now
> 
> @AndersLarsenMicrosoft Will this request be shipped in a future update? I am now wondering whether the automatically-generated reply from @JesperSchulz is correct or not. :)

I'm afraid our internal work item wrongly was resolved as "Fixed", which triggers the automation to update this issue. As per Ander's comment, we won't address this issue through this work item.

The code you are referring to is in the BaseApp and you'd hence have to suggest and fix this code in the BaseApp contribution pilot: https://github.com/microsoft/businesscentralapps. For access to the pilot, please fill out the following form: https://forms.office.com/r/E9wyE5a58f.

This repository is only for extensibility requests or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

**IMPORTANT:** Microsoft is not going to address the reported issue for you. You will have to get the issue approved, and then push a pull request with the suggested changes yourself. If you would like Microsoft to address the issue, please create a support request.

If you want to log a support case, please visit:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

We haven't gotten around to cleaning up some of the older issues here on GitHub yet - I guess now it was the turn on this one 😉

**Comment by rvanbekkum** [comment]
Thank you for the explanation I think it is an extensibility request though (as it allows for event subscribers to also be triggered in reports where the VAT specs are retrieved), but I suspect it is considered debatable. 😉

**Comment by JesperSchulz** [comment]
> Thank you for the explanation I think it is an extensibility request though (as it allows for event subscribers to also be triggered in reports where the VAT specs are retrieved), but I suspect it is considered debatable. 😉

Maybe you want to take a stab at fixing this in the BaseApp contribution pilot? It's by far the fastest path to change!

**Comment by rvanbekkum** [comment]
Perhaps I will in the near future. Thanks again for getting back and explaining (and now updating the status appropriately 😉).
