### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines"  OnWriteToDatabaseBeforeCheckChangedTracking

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13828]
Hello, 

Is it possible to get the following event with IsHandled: 

                       if xTempItemTrackingLine.Get(TempItemTrackLineModify."Entry No.") then begin
                            // Process decreases before increases
                            OnWriteToDatabaseOnBeforeRegisterDecrease(TempItemTrackLineModify);
                            Decrease := (xTempItemTrackingLine."Quantity (Base)" > TempItemTrackLineModify."Quantity (Base)");
                            if ((ModifyLoop = 1) and Decrease) or ((ModifyLoop = 2) and not Decrease) then begin
                                i := i + 1;
                                // DINNL <<
                                DINOnWriteToDatabaseBeforeCheckChangedTracking(xTempItemTrackingLine, TempItemTrackLineModify, IsHandled);
                                // DINNL >>
                                if (not xTempItemTrackingLine.HasSameTracking(TempItemTrackLineModify)) or
                                   (xTempItemTrackingLine."Appl.-from Item Entry" <> TempItemTrackLineModify."Appl.-from Item Entry") or
                                   (xTempItemTrackingLine."Appl.-to Item Entry" <> TempItemTrackLineModify."Appl.-to Item Entry")
                                   // DINNL <<
                                   OR (IsHandled)
                                // DINNL >>
                                then begin
                                    RegisterChange(xTempItemTrackingLine, xTempItemTrackingLine, ChangeType::Delete, false);
                                    RegisterChange(TempItemTrackLineModify, TempItemTrackLineModify, ChangeType::Insert, false);
                                    if (TempItemTrackLineInsert."Quantity (Base)" <> TempItemTrackLineInsert."Qty. to Handle (Base)") or
                                       (TempItemTrackLineInsert."Quantity (Base)" <> TempItemTrackLineInsert."Qty. to Invoice (Base)")
                                    then

    [IntegrationEvent(false, false)]
    local procedure DINOnWriteToDatabaseBeforeCheckChangedTracking(xTempItemTrackingLine: Record "Tracking Specification" temporary; TempItemTrackLineModify: record "Tracking Specification" temporary; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
