### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" OnAfterUpdateUndefinedQtyArray

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13827]
Hello, 

Is it possible to get the following event:    

 local procedure UpdateUndefinedQtyArray()
    begin
        UndefinedQtyArray[1] := SourceQuantityArray[1] - TotalItemTrackingLine."Quantity (Base)";
        UndefinedQtyArray[2] := SourceQuantityArray[2] - TotalItemTrackingLine."Qty. to Handle (Base)";
        UndefinedQtyArray[3] := SourceQuantityArray[3] - TotalItemTrackingLine."Qty. to Invoice (Base)";
        // DINNL <<
        DINOnAfterUpdateUndefinedQtyArray(TotalItemTrackingLine)
        // DINNL >>
    end;

    [IntegrationEvent(false, false)]
    local procedure DINOnAfterUpdateUndefinedQtyArray(TotalItemTrackingLine: Record "Tracking Specification");
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
