### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" OnSelectEntriesBeforeSelectMultipleTrackingNo

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13831]
Hello, 

Is it possible to get the following event: 

    local procedure SelectEntries()
    var
        xTrackingSpec: Record "Tracking Specification";
        MaxQuantity: Decimal;
    begin
        xTrackingSpec.CopyFilters(Rec);
        MaxQuantity := UndefinedQtyArray[1];
        if MaxQuantity * CurrentSignFactor > 0 then
            MaxQuantity := 0;
        Rec."Bin Code" := ForBinCode;
        // DINNL <<
        DINOnSelectEntriesBeforeSelectMultipleTrackingNo(CurrentSignFactor, ItemTrackingDataCollection);
        // DINNL >>
        ItemTrackingDataCollection.SelectMultipleTrackingNo(Rec, MaxQuantity, CurrentSignFactor);
        Rec."Bin Code" := '';
        if Rec.FindSet() then
            repeat
                case Rec."Buffer Status" of
                    Rec."Buffer Status"::MODIFY:
                        begin

    [IntegrationEvent(false, false)]
    local procedure DINOnSelectEntriesBeforeSelectMultipleTrackingNo(D CurrentSignFactor: integer; ItemTrackingDataCollection: codeunit "Item Tracking Data Collection");
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
