### ISSUE TITLE
[Event Request] codeunit 5760 "Whse.-Post Receipt" PurchaseLineSkipModify

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13838]
if "Source Document" = "Source Document"::"Purchase Order" then begin
                                        ModifyLine := PurchLine."Qty. to Receive" <> 0;
                                        // DINNL <<
                                        DINIsHandled := false;
                                        DINPurchaseLineSkipModify(PurchLine, DINIsHandled);
                                        if not DINIsHandled then
                                            // DINNL >>
                                        if ModifyLine then
                                                PurchLine.Validate("Qty. to Receive", 0);
                                    end else begin
                                        ModifyLine := PurchLine."Return Qty. to Ship" <> 0;
                                        // DINNL <<
                                        DINIsHandled := false;
                                        DINPurchaseLineSkipModify(PurchLine, DINIsHandled);
                                        if not DINIsHandled then
                                            // DINNL >>
                                        if ModifyLine then
                                                PurchLine.Validate("Return Qty. to Ship", 0);
                                    end;

    [IntegrationEvent(false, false)]
    local procedure DINPurchaseLineSkipModify(PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
