### ISSUE TITLE
[Event Request] page 9126 "Lot Numbers by Bin FactBox"  FillTempTableOnBeforeInsertLotNosByBinBuffer

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13833]
Hello, 

Is it possible to get the following event: 

        DeleteAll();

        while LotNosByBinCode.Read do begin
            Init;
            "Item No." := LotNosByBinCode.Item_No;
            "Variant Code" := LotNosByBinCode.Variant_Code;
            "Zone Code" := LotNosByBinCode.Zone_Code;
            "Bin Code" := LotNosByBinCode.Bin_Code;
            "Location Code" := LotNosByBinCode.Location_Code;
            "Lot No." := LotNosByBinCode.Lot_No;
            // DINNL >>
            DINFillTempTableOnBeforeInsertLotNosByBinBuffer(Rec, LotNosByBinCode);
            // DINNL >>
            if Find then begin
                "Qty. (Base)" += LotNosByBinCode.Sum_Qty_Base;
                Modify;
            end else begin
                "Qty. (Base)" := LotNosByBinCode.Sum_Qty_Base;
                Insert;
            end;
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure DINFillTempTableOnBeforeInsertLotNosByBinBuffer(var LotBinBuffer: record "Lot Bin Buffer"; LotNosByBinCode: query "Lot Numbers by Bin")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
