### ISSUE TITLE
[Event Request] page 9126 "Lot Numbers by Bin FactBox" FillTempTableOnBeforeOpenLotNosByBinCode

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13832]
Hello, 

Is it possible to get the following event:    

 local procedure FillTempTable()
    var
        LotNosByBinCode: Query "Lot Numbers by Bin";
    begin
        LotNosByBinCode.SetRange(Item_No, GetRangeMin("Item No."));
        LotNosByBinCode.SetRange(Variant_Code, GetRangeMin("Variant Code"));
        LotNosByBinCode.SetRange(Location_Code, GetRangeMin("Location Code"));
        LotNosByBinCode.SetFilter(Lot_No, '<>%1', '');
        // DINNL <<
        DINFillTempTableOnBeforeOpenLotNosByBinCode(LotNosByBinCode);
        // DINNL >>

        LotNosByBinCode.Open;

        DeleteAll();

        while LotNosByBinCode.Read do begin

    [IntegrationEvent(false, false)]
    local procedure DINFillTempTableOnBeforeOpenLotNosByBinCode(var LotNosByBinCode: query "Lot Numbers by Bin")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
