### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" OnRegisterChangeBeforeCheckQuantityBase

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13830]
Hello, 

Is it possible to get the following event with is Handled: 

                    ReservEntry2.TransferFields(NewTrackingSpecification);

                    ReservEntry1."Entry No." := ReservEntry2."Entry No."; // If only entry no. has changed it should not trigger
                    OnRegisterChangeOnChangeTypeModifyOnBeforeCheckEntriesAreIdentical(ReservEntry1, ReservEntry2, OldTrackingSpecification, NewTrackingSpecification, IdenticalArray);
                    if EntriesAreIdentical(ReservEntry1, ReservEntry2, IdenticalArray) then
                        exit(QtyToHandleAndInvoiceChanged(ReservEntry1, ReservEntry2));

                    // DINNL <<
                    DINOnRegisterChangeBeforeCheckQuantityBase(OldTrackingSpecification, NewTrackingSpecification, IsHandled);
                    //if Abs(OldTrackingSpecification."Quantity (Base)") < Abs(NewTrackingSpecification."Quantity (Base)") then begin
                    IF (ABS(OldTrackingSpecification."Quantity (Base)") < ABS(NewTrackingSpecification."Quantity (Base)")) OR
                         (DINDualQuantityBaseIsSmaller) THEN BEGIN
                        // DINNL >>
                        // Item Tracking is added to any blank reservation entries:
                        TempReservEntry.SetTrackingFilterBlank();

    [IntegrationEvent(false, false)]
    local procedure DINOnRegisterChangeBeforeCheckQuantityBase(OldTrackingSpecification: Record "Tracking Specification"; NewTrackingSpecification: record "Tracking Specification"; var IsHandled: Boolean);
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
