### ISSUE TITLE
[Event Request] Table 5902 - Service Line - OnCalcVATAmountLinesOnAfterCalcLineTotals

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#13835]
Dear ALAppExtensions team,

Through this issue we would like to request event `OnCalcVATAmountLinesOnAfterCalcLineTotals` to be added to table `Service Line`, in line with the same events that exist for the `Purchase Line` and `Sales Line` tables.

Thank you in advance for your time and efforts!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
