### ISSUE TITLE
[Event Request] codeunit 80 "Sales-Post" OnPostUpdateOrderLine

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13836]
Hello is it possible to get the following event. Or a modification on OnBeforePostUpdateOrderLineModifyTempLine

                    SetDefaultQuantity;
                    OnBeforePostUpdateOrderLineModifyTempLine(TempSalesLine, WhseShip, WhseReceive, SuppressCommit);
                    // DINNL <<
                    DINIsHandled := false;
                    DINOnPostUpdateOrderLine(TempSalesLine, SalesHeader, WhseHandlingRequired(TempSalesLine), DINIsHandled);
                    if not DINIsHandled then
                        // DINNL >>
                    ModifyTempLine(TempSalesLine);
                    OnAfterPostUpdateOrderLineModifyTempLine(TempSalesLine, WhseShip, WhseReceive, SuppressCommit, SalesHeader);

    [IntegrationEvent(false, false)]
    local procedure DINOnPostUpdateOrderLine(var TempSalesLine: Record "Sales Line" temporary; SalesHeader: Record "Sales Header"; WhseHandlingRequired: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
