### ISSUE TITLE
[Event Request] table 81 "Gen. Journal Line" SetHideValidationOnAfterCustLedgEntrySetFilters

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13839]
if CustLedgEntry.Find('-') then;
                            CustLedgEntry.SetRange("Applies-to ID");
                        end else
                            if "Applies-to Doc. Type" <> "Applies-to Doc. Type"::" " then begin
                                CustLedgEntry.SetRange("Document Type", "Applies-to Doc. Type");
                                if CustLedgEntry.Find('-') then;
                                CustLedgEntry.SetRange("Document Type");
                            end else
                                if Amount <> 0 then begin
                                    CustLedgEntry.SetRange(Positive, Amount < 0);
                                    if CustLedgEntry.Find('-') then;
                                    CustLedgEntry.SetRange(Positive);
                                end;
                    // DINNL <<
                    DINSetHideValidationOnAfterCustLedgEntrySetFilters(CustLedgEntry, AccNo);
                    // DINNL >>
                    ApplyCustEntries.SetGenJnlLine(Rec, GenJnlLine.FieldNo("Applies-to Doc. No."));
                    ApplyCustEntries.SetTableView(CustLedgEntry);
                    ApplyCustEntries.SetRecord(CustLedgEntry);
                    ApplyCustEntries.LookupMode(true);

    [IntegrationEvent(false, false)]
    local procedure DINSetHideValidationOnAfterCustLedgEntrySetFilters(var CustLedgEntry: Record "Cust. Ledger Entry"; AccNo: Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
