### ISSUE TITLE
[Event Modification] page 9223 "Item Statistics Matrix" OnAfterCalculate

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13834]
hello 

Is it possible to get the following added to an event:  

      OnAfterCalculate(ItemBuffer, SetColumnFilter, Amount);

to 
        OnAfterCalculate(ItemBuffer, SetColumnFilter, Amount, Name, CalcSalesAmount(SetColumnFilter));

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
