### ISSUE TITLE
[Event request] codeunit 5760 "Whse.-Post Receipt" SalesLineSkipModify

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13837]
if "Source Document" = "Source Document"::"Sales Order" then begin
                                        ModifyLine := SalesLine."Qty. to Ship" <> 0;
                                        // DINNL <<
                                        DINIsHandled := false;
                                        DINSalesLineSkipModify(SalesLine, DINIsHandled);
                                        if not DINIsHandled then
                                            // DINNL >>
                                        if ModifyLine then
                                                SalesLine.Validate("Qty. to Ship", 0);
                                    end else begin
                                        ModifyLine := SalesLine."Return Qty. to Receive" <> 0;
                                        // DINNL <<
                                        DINIsHandled := false;
                                        DINSalesLineSkipModify(SalesLine, DINIsHandled);
                                        if not DINIsHandled then
                                            // DINNL >>
                                        if ModifyLine then
                                                SalesLine.Validate("Return Qty. to Receive", 0);
                                    end;

    [IntegrationEvent(false, false)]
    local procedure DINSalesLineSkipModify(SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
