### ISSUE TITLE
[Event Request] table 81 "Gen. Journal Line" SetHideValidationOnAfterLookupApplyCustEntries

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13841]
ApplyCustEntries.SetTableView(CustLedgEntry);
                    ApplyCustEntries.SetRecord(CustLedgEntry);
                    ApplyCustEntries.LookupMode(true);
                    if ApplyCustEntries.RunModal = ACTION::LookupOK then begin
                        ApplyCustEntries.GetRecord(CustLedgEntry);
                        // DINNL <<
                        DINSetHideValidationOnAfterLookupApplyCustEntries(Rec, CustLedgEntry);
                        // DINNL >>
                        CustLedgEntry.CalcFields("Remaining Amount");
                        Clear(ApplyCustEntries);
                        if "Currency Code" <> CustLedgEntry."Currency Code" then
                            if Amount = 0 then
                                Validate("Currency Code", CustLedgEntry."Currency Code")
                            else
                                GenJnlApply.CheckAgainstApplnCurrency("Currency Code", CustLedgEntry."Currency Code",
                                  GenJnlLine."Account Type"::Customer, true);
                        if Amount = 0 then begin
                            if ("Document Type" = "Document Type"::Payment) and

    [IntegrationEvent(false, false)]
    local procedure DINSetHideValidationOnAfterLookupApplyCustEntries(var GenJournalLine: Record "Gen. Journal Line"; CustLedgerEntry: Record "Cust. Ledger Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
