### ISSUE TITLE
[Event Modification] codeunit 90 "Purch.-Post" OnAfterReturnShptLineInsert

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13844]
OnAfterReturnShptLineInsert(
          ReturnShptLine, ReturnShptHeader, PurchLine, ItemLedgShptEntryNo, WhseShip, WhseReceive, SuppressCommit,
          TempWhseShptHeader, PurchCrMemoHeader);

to 
            OnAfterReturnShptLineInsert(
          ReturnShptLine, ReturnShptHeader, PurchLine, ItemLedgShptEntryNo, WhseShip, WhseReceive, SuppressCommit,
          TempWhseShptHeader, PurchCrMemoHeader, xPurchLine);

**Comment by Oleg-Romashkov** [comment]
CheckCertificateOfSupplyStatus is not an event. Which event you would like to update?

**Comment by leegeurts** [comment]
Hi Oleg, 
Should have been OnAfterReturnShptLineInsert
Sorry :)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
