### ISSUE TITLE
[Event modification] codeunit 90 "Purch.-Post"  PurchRcptLineInsert

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13843]
PurchRcptLineInsert(PurchRcptLine, PurchRcptHeader, PurchLine);
to 
        PurchRcptLineInsert(PurchRcptLine, PurchRcptHeader, PurchLine, xPurchLine);

**Comment by Oleg-Romashkov** [comment]
The function PurchRcptLineInsert is not an event. Which event you would like to update?

**Comment by leegeurts** [comment]
You are correct. we need the XPurchline on event OnAfterPurchRcptLineInsert

This means you need to pas it to the function. Is that possible ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
