### ISSUE TITLE
[Event Request] table 81 "Gen. Journal Line" SetHideValidationOnAfterVendLedgEntrySetFilters

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13840]
if VendLedgEntry.Find('-') then;
                            VendLedgEntry.SetRange("Applies-to ID");
                        end else
                            if "Applies-to Doc. Type" <> "Applies-to Doc. Type"::" " then begin
                                VendLedgEntry.SetRange("Document Type", "Applies-to Doc. Type");
                                if VendLedgEntry.Find('-') then;
                                VendLedgEntry.SetRange("Document Type");
                            end else
                                if Amount <> 0 then begin
                                    VendLedgEntry.SetRange(Positive, Amount < 0);
                                    if VendLedgEntry.Find('-') then;
                                    VendLedgEntry.SetRange(Positive);
                                end;
                    // DINNL <<
                    DINSetHideValidationOnAfterVendLedgEntrySetFilters(VendLedgEntry, AccNo);
                    // DINNL >>
                    ApplyVendEntries.SetGenJnlLine(Rec, GenJnlLine.FieldNo("Applies-to Doc. No."));
                    ApplyVendEntries.SetTableView(VendLedgEntry);
                    ApplyVendEntries.SetRecord(VendLedgEntry);
                    ApplyVendEntries.LookupMode(true);

    [IntegrationEvent(false, false)]
    local procedure DINSetHideValidationOnAfterVendLedgEntrySetFilters(var VendLedgEntry: Record "Vendor Ledger Entry"; AccNo: Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
