### ISSUE TITLE
Global event request

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#1385]
Greetings - For an add-on we're porting, we have some logic we'd like to run right before any transaction (anywhere in NAV) finishes (i.e. the point of a commit occurring, whether explicitly coded or just triggered by the end of a transaction).  Would it be possible to create a global OnBeforeCommit event we could subscribe to in order to implement our logic?

**Comment by JesperSchulz** [comment]
Interesting idea! However, this request goes beyond the scope of this repository. Please submit your idea to [Business Central - Ideas](http://aka.ms/bcideas), where it will end up as a feature request. Thanks!
