### ISSUE TITLE
codeunit 22 "Item Jnl.-Post Line" - OnBeforeInsertValueEntry - Event Request

### ISSUE THREAD

**Issue by ZacRyon** [microsoft/ALAppExtensions#13859]
codeunit 22 "Item Jnl.-Post Line"
{
    Permissions = TableData Item = imd,
                  TableData "Item Ledger Entry" = imd,
                  TableData "Item Register" = imd,
                  TableData "Phys. Inventory Ledger Entry" = imd,
                  TableData "Item Application Entry" = imd,
                  TableData "Prod. Order Capacity Need" = rimd,
                  TableData "Stockkeeping Unit" = imd,
                  TableData "Value Entry" = imd,
                  TableData "Avg. Cost Adjmt. Entry Point" = rim,
                  TableData "Post Value Entry to G/L" = ri,
                  TableData "Capacity Ledger Entry" = rimd,
                  TableData "Inventory Adjmt. Entry (Order)" = rim;
    TableNo = "Item Journal Line";

...
    procedure InsertValueEntry(var ValueEntry: Record "Value Entry"; var ItemLedgEntry: Record "Item Ledger Entry"; TransferItem: Boolean)
    var
        InvdValueEntry: Record "Value Entry";
        InvoicedQty: Decimal;
    begin
        OnBeforeInsertValueEntryProcedure(ItemLedgEntry, ItemJnlLine);
        with ItemJnlLine do begin
            if IsWarehouseReclassification(ItemJnlLine) then begin
                ValueEntry."Dimension Set ID" := OldItemLedgEntry."Dimension Set ID";
                ValueEntry."Global Dimension 1 Code" := OldItemLedgEntry."Global Dimension 1 Code";
                ValueEntry."Global Dimension 2 Code" := OldItemLedgEntry."Global Dimension 2 Code";
            end else
                if TransferItem then begin
                    ValueEntry."Global Dimension 1 Code" := "New Shortcut Dimension 1 Code";
                    ValueEntry."Global Dimension 2 Code" := "New Shortcut Dimension 2 Code";
                    ValueEntry."Dimension Set ID" := "New Dimension Set ID";
                end else
                    if (GlobalValueEntry."Entry Type" = GlobalValueEntry."Entry Type"::"Direct Cost") and
                       (GlobalValueEntry."Item Charge No." <> '') and
                       (ValueEntry."Entry Type" = ValueEntry."Entry Type"::Variance)
                    then begin
                        GetLastDirectCostValEntry(ValueEntry."Item Ledger Entry No.");
                        ValueEntry."Gen. Prod. Posting Group" := DirCostValueEntry."Gen. Prod. Posting Group";
                        MoveValEntryDimToValEntryDim(ValueEntry, DirCostValueEntry);
                    end else begin
                        ValueEntry."Global Dimension 1 Code" := "Shortcut Dimension 1 Code";
                        ValueEntry."Global Dimension 2 Code" := "Shortcut Dimension 2 Code";
                        ValueEntry."Dimension Set ID" := "Dimension Set ID";
                    end;
            RoundAmtValueEntry(ValueEntry);

            if ValueEntry."Entry Type" = ValueEntry."Entry Type"::Rounding then begin
                ValueEntry."Valued Quantity" := ItemLedgEntry.Quantity;
                ValueEntry."Invoiced Quantity" := 0;
                ValueEntry."Cost per Unit" := 0;
                ValueEntry."Sales Amount (Actual)" := 0;
                ValueEntry."Purchase Amount (Actual)" := 0;
                ValueEntry."Cost per Unit (ACY)" := 0;
                ValueEntry."Item Ledger Entry Quantity" := 0;
            end else begin
                if IsFirstValueEntry(ValueEntry."Item Ledger Entry No.") then
                    ValueEntry."Item Ledger Entry Quantity" := ValueEntry."Valued Quantity"
                else
                    ValueEntry."Item Ledger Entry Quantity" := 0;
                RecalculateCostPerUnit(ValueEntry, ItemLedgEntry);
                if UpdateItemLedgEntry(ValueEntry, ItemLedgEntry) then
                    ItemLedgEntry.Modify();
            end;

            OnInsertValueEntryOnBeforeCalcExpectedCost(ItemJnlLine, ItemLedgEntry, ValueEntry);
            if ((ValueEntry."Entry Type" = ValueEntry."Entry Type"::"Direct Cost") and
                (ValueEntry."Item Charge No." = '')) and
               (((Quantity = 0) and ("Invoiced Quantity" <> 0)) or
                (Adjustment and not ValueEntry."Expected Cost")) and
               not ExpectedCostPosted(ValueEntry)
            then begin
                if ValueEntry."Invoiced Quantity" = 0 then begin
                    if InvdValueEntry.Get(ValueEntry."Applies-to Entry") then
                        InvoicedQty := InvdValueEntry."Invoiced Quantity"
                    else
                        InvoicedQty := ValueEntry."Valued Quantity";
                end else
                    InvoicedQty := ValueEntry."Invoiced Quantity";
                CalcExpectedCost(
                  ValueEntry,
                  ItemLedgEntry."Entry No.",
                  InvoicedQty,
                  ItemLedgEntry.Quantity,
                  ValueEntry."Cost Amount (Expected)",
                  ValueEntry."Cost Amount (Expected) (ACY)",
                  ValueEntry."Sales Amount (Expected)",
                  ValueEntry."Purchase Amount (Expected)",
                  ItemLedgEntry.Quantity = ItemLedgEntry."Invoiced Quantity");
            end;

            OnBeforeInsertValueEntry(ValueEntry, ItemJnlLine, ItemLedgEntry, ValueEntryNo, InventoryPostingToGL, CalledFromAdjustment);
            //NPO begin
            OnBeforeInsertValueEntryNVG(ValueEntry, ItemJnlLine, ItemLedgEntry, ValueEntryNo, InventoryPostingToGL, CalledFromAdjustment, OldItemLedgEntry, Item, TransferItem, GlobalValueEntry);
            //NPO end

            if ValueEntry.Inventoriable and not Item."Inventory Value Zero" then
                PostInventoryToGL(ValueEntry);

            ValueEntry.Insert();

            OnAfterInsertValueEntry(ValueEntry, ItemJnlLine, ItemLedgEntry, ValueEntryNo);

            ItemApplnEntry.SetOutboundsNotUpdated(ItemLedgEntry);

            UpdateAdjmtProperties(ValueEntry, ItemLedgEntry."Posting Date");

            InsertItemReg(0, 0, ValueEntry."Entry No.", 0);
            InsertPostValueEntryToGL(ValueEntry);
            if Item."Item Tracking Code" <> '' then begin
                TempValueEntryRelation.Init();
                TempValueEntryRelation."Value Entry No." := ValueEntry."Entry No.";
                TempValueEntryRelation.Insert();
            end;
            OnInsertValueEntryOnAfterTempValueEntryRelationInsert(ValueEntry, ItemJnlLine, TempValueEntryRelation);
        end;
    end;
...

    //NPO begin
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertValueEntryNVG(var ValueEntry: Record "Value Entry"; ItemJournalLine: Record "Item Journal Line"; var ItemLedgerEntry: Record "Item Ledger Entry"; var ValueEntryNo: Integer; var InventoryPostingToGL: Codeunit "Inventory Posting To G/L"; CalledFromAdjustment: Boolean; var OldItemLedgEntry: Record "Item Ledger Entry"; var Item: Record Item; TransferItem: Boolean; var GlobalValueEntry: Record "Value Entry")
    begin
    end;
    //NPO end
}

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
