### ISSUE TITLE
[Event Modification] page 232 "Apply Customer Entries" OnSetCustApplIdAfterCheckAgainstApplnCurrency

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13864]
Hello

OnSetCustApplIdAfterCheckAgainstApplnCurrency

Can you please make GenJnlLine var

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
