### ISSUE TITLE
codeunit 10144 "Posted Deposit-Delete" - OnBeforeDelete - Event Request

### ISSUE THREAD

**Issue by ZacRyon** [microsoft/ALAppExtensions#13869]
codeunit 10144 "Posted Deposit-Delete"
{
    Permissions = TableData "Posted Deposit Header" = rd,
                  TableData "Posted Deposit Line" = rd;
    TableNo = "Posted Deposit Header";

    trigger OnRun()
    begin
        PostedDepositLine.SetRange("Deposit No.", "No.");
        PostedDepositLine.DeleteAll();

        //NPO begin
        OnBeforeDelete(Rec);
        //NPO end

        Delete;
    end;

    //NPO begin
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDelete(var Rec: Record "Posted Deposit Header")
    begin
    end;        
    //NPO end
    
    var
        PostedDepositLine: Record "Posted Deposit Line";
}

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
