### ISSUE TITLE
codeunit 10125 "Posted Bank Rec.-Delete" - OnBeforeDelete - Event Request

### ISSUE THREAD

**Issue by ZacRyon** [microsoft/ALAppExtensions#13866]
codeunit 10125 "Posted Bank Rec.-Delete"
{
    Permissions = TableData "Bank Comment Line" = rd,
                  TableData "Posted Bank Rec. Header" = rd,
                  TableData "Posted Bank Rec. Line" = rd;
    TableNo = "Posted Bank Rec. Header";

    trigger OnRun()
    begin
        PostedBankRecLines.SetRange("Bank Account No.", "Bank Account No.");
        PostedBankRecLines.SetRange("Statement No.", "Statement No.");
        PostedBankRecLines.DeleteAll();

        BankRecCommentLines.SetRange("Table Name", BankRecCommentLines."Table Name"::"Posted Bank Rec.");
        BankRecCommentLines.SetRange("Bank Account No.", "Bank Account No.");
        BankRecCommentLines.SetRange("No.", "Statement No.");
        BankRecCommentLines.DeleteAll();

        //NPO begin
        OnBeforeDelete(Rec);
        //NPO end

        Delete;
    end;

    //NPO begin
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDelete(var Rec: Record "Posted Bank Rec. Header")
    begin
    end;
    //NPO end

    var
        PostedBankRecLines: Record "Posted Bank Rec. Line";
        BankRecCommentLines: Record "Bank Comment Line";
}

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
