### ISSUE TITLE
table 39 "Purchase Line" - OnBeforeSelectItemEntryPageRun, OnBeforeUpdateVATAmountsUpdateAmounts, OnBeforeExitThenDepreciationBookCodeEmpty, OnBeforeValidateLineDiscountPercent, OnAfterCreateDimTableIDsOverload, OnAfterCreateDimOverload, OnConfirmCheckForTaxDifferences, & OnUpdateVATAmountsOnBeforeValidateLineDiscountPercentForLines

### ISSUE THREAD

**Issue by ZacRyon** [microsoft/ALAppExtensions#13874]
table 39 "Purchase Line"
{
    Caption = 'Purchase Line';
    DrillDownPageID = "Purchase Lines";
    LookupPageID = "Purchase Lines";

    fields
    {
...
    local procedure SelectItemEntry()
    var
        ItemLedgEntry: Record "Item Ledger Entry";
    begin
        TestField("Prod. Order No.", '');
        ItemLedgEntry.SetCurrentKey("Item No.", Open);
        ItemLedgEntry.SetRange("Item No.", "No.");
        ItemLedgEntry.SetRange(Open, true);
        ItemLedgEntry.SetRange(Positive, true);
        OnSelectItemEntryOnBeforeSetRangeLocationCode(Rec, ItemLedgEntry);
        if "Location Code" <> '' then
            ItemLedgEntry.SetRange("Location Code", "Location Code");
        ItemLedgEntry.SetRange("Variant Code", "Variant Code");

        //NPO Begin
        OnBeforeSelectItemEntryPageRun(Rec, ItemLedgEntry);
        //NPO End

        if PAGE.RunModal(PAGE::"Item Ledger Entries", ItemLedgEntry) = ACTION::LookupOK then
            Validate("Appl.-to Item Entry", ItemLedgEntry."Entry No.");
    end;
...
    procedure UpdateAmounts()
    var
        PurchCrMemoHeader: Record "Purch. Cr. Memo Hdr.";
        VATBaseAmount: Decimal;
        LineAmountChanged: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateAmounts(Rec, xRec, CurrFieldNo, IsHandled);
        if IsHandled then
            exit;

        if Type = Type::" " then
            exit;

        GetPurchHeader;

        VATBaseAmount := "Amount Including VAT";
        "Recalculate Invoice Disc." := true;

        UpdateLineAmount(LineAmountChanged);

        //NPO Begin
        IsHandled := false;
        OnBeforeUpdateVATAmountsUpdateAmounts(Rec, IsHandled);
        if not IsHandled then begin
        //NPO End
            if PurchHeader.Status = PurchHeader.Status::Released then
                if PurchHeader."Tax Area Code" = '' then
                    UpdateVATAmounts
                else
                    if (CurrFieldNo <> 0) and (("Over-Receipt Quantity" = 0) and (xRec."Over-Receipt Quantity" = 0)) then
                        Error(Text1020002);
        //NPO Begin
        end;
        //NPO End
        if (CurrFieldNo <> 0) and ("Tax Area Code" <> '') then
            CheckForTaxDifferences;

        if (("Tax Group Code" = '') and (xRec."Tax Group Code" <> ''))
           or (("Tax Area Code" = '') and (xRec."Tax Area Code" <> '')) then begin
            Amount := 0;
            "Amount Including VAT" := 0;
        end;

        if not "Prepayment Line" then
            UpdatePrepmtAmounts();

        OnAfterUpdateAmounts(Rec, xRec, CurrFieldNo);

        UpdateVATAmounts;
        if VATBaseAmount <> "Amount Including VAT" then
            LineAmountChanged := true;

        if LineAmountChanged then begin
            UpdateDeferralAmounts;
            LineAmountChanged := false;
        end;

        InitOutstandingAmount;

        if Type = Type::"Charge (Item)" then
            UpdateItemChargeAssgnt();

        if (Quantity < xRec.Quantity) and ("Prepmt. Amt. Inv." <> 0) then begin
            PurchCrMemoHeader.SetCurrentKey("Prepayment Order No.");
            PurchCrMemoHeader.SetRange("Prepayment Order No.", "Document No.");
            if PurchCrMemoHeader.FindFirst then begin
                PurchCrMemoHeader.CalcFields(Amount);
                if ("Prepmt. Amt. Inv." <> 0) and ("Prepayment %" <> 0) then
                    if "Line Amount" <> xRec."Line Amount" - PurchCrMemoHeader.Amount * 100 / "Prepayment %" then
                        FieldError("Line Amount", StrSubstNo(Text1020005, xRec."Line Amount"));
            end;
        end;
        CalcPrepaymentToDeduct;

        OnAfterUpdateAmountsDone(Rec, xRec, CurrFieldNo);
    end;
...
    procedure UpdateVATAmounts()
    var
        PurchLine2: Record "Purchase Line";
        TotalLineAmount: Decimal;
        TotalInvDiscAmount: Decimal;
        TotalAmount: Decimal;
        TotalAmountInclVAT: Decimal;
        TotalVATDifference: Decimal;
        TotalQuantityBase: Decimal;
        TotalExpenseTax: Decimal;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateVATAmounts(Rec, IsHandled);
        if IsHandled then
            exit;

        GetPurchHeader;
        PurchLine2.SetRange("Document Type", "Document Type");
        PurchLine2.SetRange("Document No.", "Document No.");
        PurchLine2.SetFilter("Line No.", '<>%1', "Line No.");
        PurchLine2.SetRange("VAT Identifier", "VAT Identifier");
        PurchLine2.SetRange("Tax Group Code", "Tax Group Code");
        PurchLine2.SetRange("Tax Area Code", "Tax Area Code");

        if ("Line Amount" = "Inv. Discount Amount") and not
            SalesTaxCalculate.HasExciseTax("Tax Area Code", "Tax Group Code", "Tax Liable", Quantity, PurchHeader."Document Date") then begin
            Amount := 0;
            "VAT Base Amount" := 0;
            "Amount Including VAT" := 0;
            OnUpdateVATAmountsOnBeforePurchLineModify(Rec, PurchLine2);
            if (Quantity = 0) and (xRec.Quantity <> 0) and (xRec.Amount <> 0) then begin
                if "Line No." <> 0 then
                    Modify;
                PurchLine2.SetFilter(Amount, '<>0');
                if PurchLine2.Find('<>') then begin
                    // NPO begin
                    //PurchLine2.ValidateLineDiscountPercent(false);
                    IsHandled := false;
                    OnUpdateVATAmountsOnBeforeValidateLineDiscountPercentForLines(PurchLine2, IsHandled);
                    if not(IsHandled) then
                    // NPO end
                      PurchLine2.ValidateLineDiscountPercent(false);
                    PurchLine2.Modify();
                end;
            end;
        end else begin
            TotalLineAmount := 0;
            TotalInvDiscAmount := 0;
            TotalAmount := 0;
            TotalAmountInclVAT := 0;
            TotalQuantityBase := 0;
            if ("VAT Calculation Type" = "VAT Calculation Type"::"Sales Tax") or
               (("VAT Calculation Type" in
                 ["VAT Calculation Type"::"Normal VAT", "VAT Calculation Type"::"Reverse Charge VAT"]) and ("VAT %" <> 0))
            then begin
                PurchLine2.SetFilter("VAT %", '<>0');
                if not PurchLine2.IsEmpty() then begin
                    PurchLine2.CalcSums(
                      "Line Amount", "Inv. Discount Amount", Amount, "Amount Including VAT", "Quantity (Base)", "VAT Difference", "Tax To Be Expensed");
                    TotalLineAmount := PurchLine2."Line Amount";
                    TotalInvDiscAmount := PurchLine2."Inv. Discount Amount";
                    TotalAmount := PurchLine2.Amount;
                    TotalAmountInclVAT := PurchLine2."Amount Including VAT";
                    TotalVATDifference := PurchLine2."VAT Difference";
                    TotalQuantityBase := PurchLine2."Quantity (Base)";
                    TotalExpenseTax := PurchLine2."Tax To Be Expensed";
                    OnAfterUpdateTotalAmounts(Rec, PurchLine2, TotalAmount, TotalAmountInclVAT, TotalLineAmount, TotalInvDiscAmount);
                end;
            end;

            if PurchHeader."Prices Including VAT" then
                case "VAT Calculation Type" of
                    "VAT Calculation Type"::"Normal VAT",
                    "VAT Calculation Type"::"Reverse Charge VAT":
                        begin
                            Amount :=
                              Round(
                                (TotalLineAmount - TotalInvDiscAmount + CalcLineAmount) / (1 + "VAT %" / 100),
                                Currency."Amount Rounding Precision") -
                              TotalAmount;
                            "VAT Base Amount" :=
                              Round(
                                Amount * (1 - PurchHeader."VAT Base Discount %" / 100),
                                Currency."Amount Rounding Precision");
                            "Amount Including VAT" :=
                              TotalLineAmount + "Line Amount" -
                              Round(
                                (TotalAmount + Amount) * (PurchHeader."VAT Base Discount %" / 100) * "VAT %" / 100,
                                Currency."Amount Rounding Precision", Currency.VATRoundingDirection) -
                              TotalAmountInclVAT - TotalInvDiscAmount - "Inv. Discount Amount";
                            OnUpdateVATAmountsOnAfterCalcNormalVATAmountsForPricesIncludingVAT(Rec, PurchHeader, Currency, TotalAmount, TotalAmountInclVAT);
                        end;
                    "VAT Calculation Type"::"Full VAT":
                        begin
                            Amount := 0;
                            "VAT Base Amount" := 0;
                            "Amount Including VAT" := ROUND(CalcLineAmount(), Currency."Amount Rounding Precision");
                        end;
                    "VAT Calculation Type"::"Sales Tax":
                        begin
                            PurchHeader.TestField("VAT Base Discount %", 0);
                            "Amount Including VAT" :=
                              Round(CalcLineAmount, Currency."Amount Rounding Precision");
                            if "Use Tax" then
                                Amount := "Amount Including VAT"
                            else
                                Amount :=
                                  Round(
                                    SalesTaxCalculate.ReverseCalculateTax(
                                      "Tax Area Code", "Tax Group Code", "Tax Liable", PurchHeader."Posting Date",
                                      TotalAmountInclVAT + "Amount Including VAT", TotalQuantityBase + "Quantity (Base)",
                                      PurchHeader."Currency Factor"),
                                    Currency."Amount Rounding Precision") -
                                  TotalAmount;
                            OnAfterSalesTaxCalculateReverse(Rec, PurchHeader, Currency);
                            "VAT Base Amount" := Amount;
                            if "VAT Base Amount" <> 0 then
                                "VAT %" :=
                                  Round(100 * ("Amount Including VAT" - "VAT Base Amount") / "VAT Base Amount", 0.00001)
                            else
                                "VAT %" := 0;
                        end;
                end
            else
                case "VAT Calculation Type" of
                    "VAT Calculation Type"::"Normal VAT",
                    "VAT Calculation Type"::"Reverse Charge VAT":
                        begin
                            Amount := Round(CalcLineAmount, Currency."Amount Rounding Precision");
                            "VAT Base Amount" :=
                              Round(Amount * (1 - PurchHeader."VAT Base Discount %" / 100), Currency."Amount Rounding Precision");
                            "Amount Including VAT" :=
                              TotalAmount + Amount +
                              Round(
                                (TotalAmount + Amount) * (1 - PurchHeader."VAT Base Discount %" / 100) * "VAT %" / 100,
                                Currency."Amount Rounding Precision", Currency.VATRoundingDirection) -
                              TotalAmountInclVAT + TotalVATDifference;
                        end;
                    "VAT Calculation Type"::"Full VAT":
                        begin
                            Amount := 0;
                            "VAT Base Amount" := 0;
                            "Amount Including VAT" := CalcLineAmount;
                        end;
                    "VAT Calculation Type"::"Sales Tax":
                        begin
                            Amount := Round(CalcLineAmount, Currency."Amount Rounding Precision");
                            "VAT Base Amount" := Amount;
                            if "Use Tax" then
                                "Amount Including VAT" := Amount
                            else
                                "Amount Including VAT" :=
                                  TotalAmount + Amount +
                                  Round(
                                    SalesTaxCalculate.CalculateTax(
                                      "Tax Area Code", "Tax Group Code", "Tax Liable", PurchHeader."Posting Date",
                                      TotalAmount + Amount, TotalQuantityBase + "Quantity (Base)",
                                      PurchHeader."Currency Factor"),
                                    Currency."Amount Rounding Precision") -
                                  TotalAmountInclVAT + TotalExpenseTax;
                            "Tax To Be Expensed" := SalesTaxCalculate.CalculateExpenseTax(
                                "Tax Area Code", "Tax Group Code", "Tax Liable", PurchHeader."Posting Date",
                                CalcLineAmount, "Quantity (Base)", PurchHeader."Currency Factor");
                            "Amount Including VAT" += "Tax To Be Expensed";
                            OnAfterSalesTaxCalculate(Rec, PurchHeader, Currency);
                            if "VAT Base Amount" <> 0 then
                                "VAT %" :=
                                  Round(100 * ("Amount Including VAT" - "VAT Base Amount") / "VAT Base Amount", 0.00001)
                            else
                                "VAT %" := 0;
                        end;
                end;
        end;

        OnAfterUpdateVATAmounts(Rec);
    end;
...
    local procedure GetFAPostingGroup()
    var
        LocalGLAcc: Record "G/L Account";
        FAPostingGr: Record "FA Posting Group";
        FADeprBook: Record "FA Depreciation Book";
        FASetup: Record "FA Setup";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetFAPostingGroup(Rec, IsHandled);
        if IsHandled then
            exit;

        if (Type <> Type::"Fixed Asset") or ("No." = '') then
            exit;
        if "Depreciation Book Code" = '' then begin
            FASetup.Get();
            "Depreciation Book Code" := FASetup."Default Depr. Book";
            if not FADeprBook.Get("No.", "Depreciation Book Code") then
                "Depreciation Book Code" := '';

            //NPO Begin
            OnBeforeExitThenDepreciationBookCodeEmpty(Rec);
            //NPO End

            if "Depreciation Book Code" = '' then
                exit;
        end;
        if "FA Posting Type" = "FA Posting Type"::" " then
            "FA Posting Type" := "FA Posting Type"::"Acquisition Cost";
        FADeprBook.Get("No.", "Depreciation Book Code");
        FADeprBook.TestField("FA Posting Group");
        FAPostingGr.GetPostingGroup(FADeprBook."FA Posting Group", FADeprBook."Depreciation Book Code");
        case "FA Posting Type" of
            "FA Posting Type"::"Acquisition Cost":
                LocalGLAcc.Get(FAPostingGr.GetAcquisitionCostAccount);
            "FA Posting Type"::Appreciation:
                LocalGLAcc.Get(FAPostingGr.GetAppreciationAccount);
            "FA Posting Type"::Maintenance:
                LocalGLAcc.Get(FAPostingGr.GetMaintenanceExpenseAccount);
        end;
        LocalGLAcc.CheckGLAcc;
        GLSetup.Get();
        if GLSetup."VAT in Use" then
            LocalGLAcc.TestField("Gen. Prod. Posting Group");
        "Posting Group" := FADeprBook."FA Posting Group";
        "Gen. Prod. Posting Group" := LocalGLAcc."Gen. Prod. Posting Group";
        "Tax Group Code" := LocalGLAcc."Tax Group Code";
        Validate("VAT Prod. Posting Group", LocalGLAcc."VAT Prod. Posting Group");

        OnAfterGetFAPostingGroup(Rec, LocalGLAcc);
    end;
...
    local procedure CheckForTaxDifferences()
    var
        SalesTaxDifference: Record "Sales Tax Amount Difference";
    begin
        if "Tax Area Code" = '' then
            exit;

        //NPO Begin
        // if SalesTaxDifference.AnyTaxDifferenceRecords(
        //      SalesTaxDifference."Document Product Area"::Purchase, "Document Type".AsInteger(), "Document No.")
        // then begin
        //     if Confirm(Text1020001, false) then
        //         SalesTaxDifference.ClearDocDifference(
        //           SalesTaxDifference."Document Product Area"::Purchase, "Document Type".AsInteger(), "Document No.")
        //     else
        //         Error(Text1020000);
        // end;
         if Confirm(Text1020001, false) then begin
            SalesTaxDifference.ClearDocDifference(
                SalesTaxDifference."Document Product Area"::Purchase, "Document Type".AsInteger(), "Document No.");
            OnConfirmCheckForTaxDifferences(Rec);
        end else
            Error(Text1020000);
       //NPO End
    end;
...
    [Scope('OnPrem')]
    procedure ValidateLineDiscountPercent(DropInvoiceDiscountAmount: Boolean)
    var
        IsHandled: Boolean;
    begin
        //NPO Start
        OnBeforeValidateLineDiscountPercent(Rec);
        //NPO End
        TestStatusOpen;
        IsHandled := false;
        OnValidateLineDiscountPercentOnAfterTestStatusOpen(Rec, xRec, CurrFieldNo, IsHandled);
        if IsHandled then
            exit;

        GetPurchHeader;
        "Line Discount Amount" :=
          Round(
            Round(Quantity * "Direct Unit Cost", Currency."Amount Rounding Precision") *
            "Line Discount %" / 100,
            Currency."Amount Rounding Precision");
        if DropInvoiceDiscountAmount then begin
            "Inv. Discount Amount" := 0;
            "Inv. Disc. Amount to Invoice" := 0;
        end;
        UpdateAmounts;
        UpdateUnitCost;
    end;
...
    //NPO Begin
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSelectItemEntryPageRun(var PurchaseLine: Record "Purchase Line"; var ItemLedgEntry: Record "Item Ledger Entry")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateVATAmountsUpdateAmounts(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeExitThenDepreciationBookCodeEmpty(var PurChaseLine: Record "Purchase Line")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateLineDiscountPercent(var PurchaseLine: Record "Purchase Line")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCreateDimTableIDsOverload(var PurchLine: Record "Purchase Line"; CallingFieldNo: Integer; var TableID: array[10] of Integer; var No: array[10] of Code[20]; Type5: Integer; No5: Code[20])
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCreateDimOverload(var PurchaseLine: Record "Purchase Line"; var CurrFieldNo: Integer; var TableID: array[10] of Integer; var No: array[10] of Code[20]; var PurchHeader: Record "Purchase Header")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnConfirmCheckForTaxDifferences(var PurchaseLine: Record "Purchase Line")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnUpdateVATAmountsOnBeforeValidateLineDiscountPercentForLines(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;
    //NPO End
}

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
