### ISSUE TITLE
DK: OIOUBL currencyID blank when currency is blank on the posted sales invoice

### ISSUE THREAD

**Issue by kimnoer** [microsoft/ALAppExtensions#1389]
https://github.com/Microsoft/ALAppExtensions/blob/1e16831b9507c55a42035dc791345880f4c6a49e/OIOUBL/src/SalesInvoice/COD13636.ExportSalesInvoice.al#L330

When the posted sales invoice does not have any currency (because the currency is the same as the LCY Code in tabel General Ledger Setup), the currencyId is blank multiple places in the generated OIOUBL document.

There are more places than the example line provided:

PaymentTerms->Amount
TaxTotal->TaxAmount
TaxTotal->TaxSubtotal->TaxableAmount
TaxTotal->TaxSubtotal->TaxAmount

and so on.

**Comment by StanPesotskiy** [comment]
Please report this issue via the standard support channel.
