### ISSUE TITLE
Event Request:  Table 5767

### ISSUE THREAD

**Issue by LucaMartinengo** [Microsoft/ALAppExtensions#139]
Hi,
Please, add a new event in CU5767 "Warehouse Activity Line" for customizing the split line function.

![image](https://user-images.githubusercontent.com/39652483/47549303-f2ff2b00-d8fb-11e8-8b66-ad0c5576d890.png)

Thank you,
Luca Martinengo

**Comment by JesperSchulz** [comment]
Event exists. Was resolved as part of another issue. Closing this issue. Thanks for reporting!
