### ISSUE TITLE
[Event Request] Codeunit 99000845 Reservation Management - OnDeleteReservEntriesOnAfterReservEntrySetFilters

### ISSUE THREAD

**Issue by TCutullic** [microsoft/ALAppExtensions#13915]
Hi, 
I need you to add a parameter in the trigger OnDeleteReservEntriesOnAfterReservEntrySetFilters in the procedure DeleteReservEntries, codeunit Reservation Management. If possible.
![image](https://user-images.githubusercontent.com/70213459/129168474-df70a85f-b94e-4df6-94a7-6a0a988e6a17.png)

Something like this should be useful :
OnDeleteReservEntriesOnAfterReservEntrySetFilters(ReservEntry, (var) ItemTrackingHandling);

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
