### ISSUE TITLE
[Event Modification] codeunit 5760 "Whse.-Post Receipt" OnInitSourceDocumentLinesOnAfterSourcePurchLineFound

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13914]
OnInitSourceDocumentLinesOnAfterSourcePurchLineFound(PurchLine, WhseRcptLine2, ModifyLine, WhseRcptHeader);

PLease make the following parameter var:

ModifyLine

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
