### ISSUE TITLE
Extension of Cash Flow

### ISSUE THREAD

**Issue by stephanweidmann** [microsoft/ALAppExtensions#1391]
Actually, the Cash Flow Forecast Statistics has a fixed array of 15 to display the differenct sources of cash expenses and revenues. With an extension, it is not possible to add new sources.

Would it be possible to redesign this module, so that it can be extended by an extension?

Ideas, that crossed my mind (unvalidated):
Using a Temporary Table instead of an Array?
Changing the source type of the Cash Flow Forecast Entry to an Enum or replace by Code[10], which can be extended?

**Comment by fvet** [comment]
Having the same need to add extra sources ...

**Comment by fvet** [comment]
@StanPesotskiy, any chance of having this issue included in the October / Fall '19 release? This blocks us from moving to extensions (without customizing the AL base app) ...

**Comment by StanPesotskiy** [comment]
@fvet I will look into this request.

**Comment by StanPesotskiy** [comment]
Hi @fvet 
Unfortunately this change will not make it to the major release scope. 
Still is in the backlog.

**Comment by fvet** [comment]
@StanPesotskiy, any official commitment of having this issue included in the Spring '20 wave 1 release (since tagged as 'Ships-in-future-update')? This is one of the blocking issues for us to move our solution to extensions (without customizing the AL base app) ... Can we get this higher on the prio list with MS somehow?

**Comment by StanPesotskiy** [comment]
It is tagged because the solution has been committed on September 12, so it will be shipped in wave 1.

**Comment by fvet** [comment]
@StanPesotskiy Would it be possible updating this issue or adding a Yammer post when the (pre) development is available on the insider previews so we can test if our changes are compatible with the newly designed cf objects?

**Comment by StanPesotskiy** [comment]
The fix has been shipped in scope of Update 15.1 for Dynamics 365 Business Central 2019.

**Comment by fvet** [comment]
I've seen it appearing in 15.1 but have no clue how to extend? 
I don't see how we can easily add new source types as requested by @stephanweidmann ...

**Table 847 "Cash Flow Forecast Entry"** 
- Field "Source Type": Seems not be converted to an extendable enum. I could use a blank option in combination with my custom field.
- If so, then 'DrillDownOnEntries' would need extra filters..
- Field "Source No.": 

**Table 840 "Cash Flow Forecast"**
- Field "Source Type Filter": Seems not be converted to an extendable enum. 
- Field "Amount (LCY)" : would need extra filters..
- Seems like we'll have to duplicate all CalcAmount related functions

**Report 840 "Suggest Worksheet Lines"**
- Extra RequestPage options, dataitems, ... seems like the standard report needs to be fully duplicated ...

**Comment by StanPesotskiy** [comment]
Please create another GitHub request (with the link to this one), where you put what you need (new events, enums, etc.) based on the latest version of objects.
