### ISSUE TITLE
[Event Modification] codeunit 5813 "Undo Purchase Receipt Line" OnAfterCopyItemJnlLineFromPurchRcpt

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13938]
Can you please add the following to an event

            OnAfterCopyItemJnlLineFromPurchRcpt(ItemJnlLine, PurchRcptHeader, PurchRcptLine);

to 
            OnAfterCopyItemJnlLineFromPurchRcpt(ItemJnlLine, PurchRcptHeader, PurchRcptLine, WhseUndoQty);

WhseUndoQty as var

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
