### ISSUE TITLE
codeunit 12 "Gen. Jnl.-Post Line" - 60 Event Requests

### ISSUE THREAD

**Issue by ZacRyon** [microsoft/ALAppExtensions#13933]
OnAdditionalCurrencyPostingNone
OnAfterApplyVendLedgEntryNPO
OnAfterCalcApplication
OnAfterCreateGLEntry
OnAfterCustPostApplyCustLedgEntry
OnAfterGetCurrencyExchRate
OnAfterInitCustLedgEntry_PostCust
OnAfterInitGLEntryNVG
OnAfterInitTempDtldCVLedgEntryBuf
OnAfterInitTempDtldCVLedgEntryBuf_PostVend
OnAfterInitVendLedgEntry_PostVend
OnAfterInsertDtldCustLedgEntryOnPostDtldCustLedgEntries
OnAfterInsertGLEntry_InsertSummarizedVAT
OnAfterResetDtldCVLedgEntryBuf
OnAfterSetDtldCustLedgEntryNoOffset
OnAfterSetGenJnlLineShortcutDimCodes
OnAfterSetGenJnlLineValues
OnAfterSetShorcutDimCode
OnAfterUpdateTotalAmounts
OnAfterVendLedgEntryInsertBeforePostDtldVendLedgEntries
OnAfterVendPostApplyVendLedgEntry
OnBefoResetGLEntry
OnBeforeCheckPurchaseExtDocNo
OnBeforeContinuePostingIncreaseNextTransactionNo
OnBeforeCreateGLEntriesForTotalAmountsUnapplyNVG
OnBeforeCreateGLEntriesForTotalAmountsUnapplyVendorNVG
OnBeforeCreateGLEntriesForTotalAmounts_PostDtldCustLedgEntries
OnBeforeCreateGLEntryBalAcc
OnBeforeCreateGLEntryBalAccPostICPartner
OnBeforeCustLedgEntryInsertNVG
OnBeforeGetDtldCustLedgEntryAccNoNVG
OnBeforeGetDtldVendLedgEntryAccNoNVG
OnBeforeInsertGLEntryBufferNVG
OnBeforeInsertGlEntry
OnBeforePostDtldCVLedgEntryOverload
OnBeforePostDtldVendLedgEntry
OnBeforeUpdateGLEntryNo
OnBeforeUpdateTotalAmountsPostDtldVendLedgEntries
OnCreateGLEntriesOverloadBeforeFindSet
OnCreateGLEntriesOverloadIsDistributed
OnGLCalcAddCurrencyPostingNone
OnGetCurrencyExchRateAfterNewCurrencyDateSet
OnHandleAddCurrResidualGLEntryOnBeforeInsertGLEntryNVG
OnPostBankAccOnBeforeBankAccLedgEntryInsertNVG
OnPostBankAccOnBeforeInitBankAccLedgEntryNVG
OnPostDtldAdjustmentBeforeCreateGLEntryBalAcc
OnPostFixedAssetOnBeforeInsertGLEntryNVG
OnPostGLAccOnBeforeInsertGLEntryNVG
OnPostTheApplication
OnProcessTempVATEntryCustBeforeProcessTempVATEntry
OnUnapplyBeforeInitRoundingPrecision
OnUnapplyBeforeSecondLook
OnUnapplyBeforeUpdateTotalAmounts
OnUnapplyCustLedgEntryOnAfterCreateGLEntriesForTotalAmountsNVG
OnUnapplyVendLedgEntryBeforeSecondLook
OnUnapplyVendLedgEntryBeforeSetAddCurrForUnapplication
OnUnapplyVendLedgEntryBeforeUpdateTotalAmounts
OnUnapplyVendLedgEntryOnAfterCreateGLEntriesForTotalAmountsNVG
OnVatCalculationTypeNormal
PostBankAccOnAfterInitCheckLedgEntry
[GenJnlPostLine.Codeunit.al.txt](https://github.com/microsoft/ALAppExtensions/files/6974591/GenJnlPostLine.Codeunit.al.txt)

**Comment by StanPesotskiy** [comment]
OnAdditionalCurrencyPostingNone - renamed OnInitAmountsOnAddCurrencyPostingNone
OnAfterApplyVendLedgEntryNPO - renamed OnVendPostApplyVendLedgEntryOnAfterApplyVendLedgEntry
OnAfterCalcApplication - OK
OnAfterCreateGLEntry - OK
OnAfterCustPostApplyCustLedgEntry - OK
OnAfterGetCurrencyExchRate - OK
OnAfterInitCustLedgEntry_PostCust - not found usage 
OnAfterInitGLEntryNVG -  added params to OnAfterInitGLEntry
OnAfterInitTempDtldCVLedgEntryBuf = OnPostCustOnAfterTempDtldCVLedgEntryBufCopyFromGenJnlLine
OnAfterInitTempDtldCVLedgEntryBuf_PostVend = OnPostVendAfterTempDtldCVLedgEntryBufInit
OnAfterInitVendLedgEntry_PostVend - renamed to OnPostVendOnAfterInitVendLedgEntry
OnAfterInsertDtldCustLedgEntryOnPostDtldCustLedgEntries - renamed OnPostDtldCustLedgEntriesOnAfterInsertDtldCustLedgEntry
OnAfterInsertGLEntry_InsertSummarizedVAT - renamed to OnInsertSummarizedVATOnAfterInsertGLEntry
OnAfterResetDtldCVLedgEntryBuf - renamed OnAfterSetDtldVendLedgEntryNoOffset
OnAfterSetDtldCustLedgEntryNoOffset - OK
OnAfterSetGenJnlLineShortcutDimCodes - renamed OnPostFixedAssetOnAfterSetGenJnlLineShortcutDimCodes
OnAfterSetGenJnlLineValues = OnPostFixedAssetOnBeforeInitGLEntryFromTempFAGLPostBuf
OnAfterSetShorcutDimCode =? OnPostFixedAssetOnAfterSaveGenJnlLineValues
OnAfterUpdateTotalAmounts - renamed OnPostDtldCustLedgEntriesOnAfterUpdateTotalAmounts
OnAfterVendLedgEntryInsertBeforePostDtldVendLedgEntries - renamed OnPostVendOnBeforePostDtldVendLedgEntries
OnAfterVendPostApplyVendLedgEntry - OK
OnBefoResetGLEntry - added params to OnBeforePostGLAcc
OnBeforeCheckPurchaseExtDocNo - not found usage
OnBeforeContinuePostingIncreaseNextTransactionNo - renamed OnContinuePostingOnIncreaseNextTransactionNo
OnBeforeCreateGLEntriesForTotalAmountsUnapplyNVG - added params to OnBeforeCreateGLEntriesForTotalAmountsUnapplyV19
OnBeforeCreateGLEntriesForTotalAmountsUnapplyVendorNVG - added params to OnBeforeCreateGLEntriesForTotalAmountsUnapplyVendorV19
OnBeforeCreateGLEntriesForTotalAmounts_PostDtldCustLedgEntries - added params to OnPostDtldCustLedgEntriesOnBeforeCreateGLEntriesForTotalAmounts
OnBeforeCreateGLEntryBalAcc - renamed OnPostBankAccOnBeforeCreateGLEntryBalAcc
OnBeforeCreateGLEntryBalAccPostICPartner - renamed OnPostICPartnerOnBeforeCreateGLEntryBalAcc
OnBeforeCustLedgEntryInsertNVG - added params to OnBeforeCustLedgEntryInsert
OnBeforeGetDtldCustLedgEntryAccNoNVG = OnBeforeGetDtldCustLedgEntryAccNo
OnBeforeGetDtldVendLedgEntryAccNoNVG = OnBeforeGetDtldVendLedgEntryAccNo
OnBeforeInsertGLEntryBufferNVG = added param to OnBeforeInsertGLEntryBuffer
OnBeforeInsertGlEntry - OK
OnBeforePostDtldCVLedgEntryOverload - skipped as part of customization
OnBeforePostDtldVendLedgEntry - OK
OnBeforeUpdateGLEntryNo - skipped as part of customization
OnBeforeUpdateTotalAmountsPostDtldVendLedgEntries - renamed OnPostDtldVendLedgEntriesOnBeforeUpdateTotalAmounts
OnCreateGLEntriesOverloadBeforeFindSet - skipped as part of customization
OnCreateGLEntriesOverloadIsDistributed - skipped as part of customization
OnGLCalcAddCurrencyPostingNone - OK
OnGetCurrencyExchRateAfterNewCurrencyDateSet - renamed OnGetCurrencyExchRateOnAfterSetNewCurrencyDate
OnHandleAddCurrResidualGLEntryOnBeforeInsertGLEntryNVG - added params to OnHandleAddCurrResidualGLEntryOnBeforeInsertGLEntry
OnPostBankAccOnBeforeBankAccLedgEntryInsertNVG - added params to OnPostBankAccOnBeforeBankAccLedgEntryInsert
OnPostBankAccOnBeforeInitBankAccLedgEntryNVG - added param to OnPostBankAccOnBeforeInitBankAccLedgEntry
OnPostDtldAdjustmentBeforeCreateGLEntryBalAcc - renamed OnPostDtldAdjustmentOnBeforeCreateGLEntryBalAcc
OnPostFixedAssetOnBeforeInsertGLEntryNVG -  added param to OnPostFixedAssetOnBeforeInsertGLEntry
OnPostGLAccOnBeforeInsertGLEntryNVG = OnPostGLAccOnBeforeInsertGLEntry
OnPostTheApplication - renamed OnCustPostApplyCustLedgEntryOnAfterApplyCustLedgEntry
OnProcessTempVATEntryCustBeforeProcessTempVATEntry - renamed OnProcessTempVATEntryCustOnAfterProcessTempVATEntry
OnUnapplyBeforeInitRoundingPrecision - renamed OnUnapplyCustLedgEntryOnAfterFillDtldCVLedgEntryBuf
OnUnapplyBeforeSecondLook - renamed OnOnUnapplyCustLedgEntryOnBeforeSecondLook
OnUnapplyBeforeUpdateTotalAmounts - renamed OnOnUnapplyCustLedgEntryOnBeforeUpdateTotalAmounts
OnUnapplyCustLedgEntryOnAfterCreateGLEntriesForTotalAmountsNVG - added param to OnUnapplyCustLedgEntryOnAfterCreateGLEntriesForTotalAmounts
OnUnapplyVendLedgEntryBeforeSecondLook - renamed OnUnapplyVendLedgEntryOnBeforeSecondLook
OnUnapplyVendLedgEntryBeforeSetAddCurrForUnapplication - renamed OnUnapplyVendLedgEntryOnAfterFillDtldCVLedgEntryBuf
OnUnapplyVendLedgEntryBeforeUpdateTotalAmounts - renamed OnUnapplyVendLedgEntryOnBeforeUpdateTotalAmounts
OnUnapplyVendLedgEntryOnAfterCreateGLEntriesForTotalAmountsNVG - added param to OnUnapplyVendLedgEntryOnAfterCreateGLEntriesForTotalAmounts
OnVatCalculationTypeNormal - renamed OnInitVATOnVATCalculationTypeNormal
PostBankAccOnAfterInitCheckLedgEntry = OnPostBankAccOnBeforeCheckLedgEntryInsert

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
