### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" OnAfterUpdateItemLedgEntry

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13944]
(ValueEntry."Entry Type" = ValueEntry."Entry Type"::Variance)
                    then begin
                        GetLastDirectCostValEntry(ValueEntry."Item Ledger Entry No.");
                        ValueEntry."Gen. Prod. Posting Group" := DirCostValueEntry."Gen. Prod. Posting Group";
                        MoveValEntryDimToValEntryDim(ValueEntry, DirCostValueEntry);
                    end else begin
                        ValueEntry."Global Dimension 1 Code" := "Shortcut Dimension 1 Code";
                        ValueEntry."Global Dimension 2 Code" := "Shortcut Dimension 2 Code";
                        ValueEntry."Dimension Set ID" := "Dimension Set ID";
                    end;
            RoundAmtValueEntry(ValueEntry);

            if ValueEntry."Entry Type" = ValueEntry."Entry Type"::Rounding then begin
                ValueEntry."Valued Quantity" := ItemLedgEntry.Quantity;
                ValueEntry."Invoiced Quantity" := 0;
                ValueEntry."Cost per Unit" := 0;
                ValueEntry."Sales Amount (Actual)" := 0;
                ValueEntry."Purchase Amount (Actual)" := 0;
                ValueEntry."Cost per Unit (ACY)" := 0;
                ValueEntry."Item Ledger Entry Quantity" := 0;
            end else begin
                if IsFirstValueEntry(ValueEntry."Item Ledger Entry No.") then
                    ValueEntry."Item Ledger Entry Quantity" := ValueEntry."Valued Quantity"
                else
                    ValueEntry."Item Ledger Entry Quantity" := 0;
                RecalculateCostPerUnit(ValueEntry, ItemLedgEntry);
                if UpdateItemLedgEntry(ValueEntry, ItemLedgEntry) then
                    ItemLedgEntry.Modify();
                // DINNL <<
                DINOnAfterUpdateItemLedgEntry(ValueEntry, ItemLedgEntry, ItemJnlLine, TransferItem,  InventoryPostingToGL);
                // DINNL >>
            end;

    [IntegrationEvent(false, false)]
    local procedure DINOnAfterUpdateItemLedgEntry(ValueEntry: Record "Value Entry"; ItemLedgEntry: Record "Item Ledger Entry"; ItemJnlLine: Record "Item Journal Line"; TransferItemPBln: Boolean; var InventoryPostingToGL: Codeunit "Inventory Posting To G/L")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
