### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" OnUndoQuantityPosting

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13948]
Hello, 

Is it possible to get the following event:

UpdateOldItemLedgEntry(OldItemLedgEntry, NewItemLedgEntry."Posting Date");
        UpdateItemApplnEntry(OldItemLedgEntry."Entry No.", NewItemLedgEntry."Posting Date");

        // DINNL <<
        DINOnUndoQuantityPosting(ItemJnlLine, OldItemLedgEntry, NewItemLedgEntry, NewValueEntry,  InventoryPostingToGL);
        // DINNL >>
        if GlobalItemLedgEntry.Quantity > 0 then
            IsReserved :=
              ItemJnlLineReserve.TransferItemJnlToItemLedgEntry(
                ItemJnlLine, GlobalItemLedgEntry, ItemJnlLine."Quantity (Base)", true);

        if not ItemJnlLine.IsATOCorrection then begin
            ApplyItemLedgEntry(NewItemLedgEntry, OldItemLedgEntry2, NewValueEntry, false);
            AutoTrack(NewItemLedgEntry, IsReserved);
        end;

        NewItemLedgEntry.Modify();

    [IntegrationEvent(false, false)]
    local procedure DINOnUndoQuantityPosting(var ItemJnlLine: Record "Item Journal Line"; OldItemLedgEntry: Record "Item Ledger Entry"; NewItemLedgEntry: Record "Item Ledger Entry"; NewValueEntry: Record "Value Entry";  InventoryPostingToGL: Codeunit "Inventory Posting To G/L")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
