### ISSUE TITLE
[Event Request] Table 77 OnBeforeSaveReportAsPDF new Param necessary

### ISSUE THREAD

**Issue by ChristianBouska** [Microsoft/ALAppExtensions#1394]
please see below

**Comment by ChristianBouska** [comment]
Dear,
can you please extend the Publisher by VAR FilePath, so that it is possible to handle the event and use the already instanced filepath (or one's own), which is later used as return value. This makes it possible to i.e. let pop up the UserReqPage for the Report and manipulate ReqPage Options for saving the XML-Doc.

![image](https://user-images.githubusercontent.com/46595080/53570134-1108c080-3b66-11e9-91b2-7e2d709b058e.png)

**Comment by AlexanderYakunin** [comment]
We cannot expose FilePath via events due to security reasons.

**Comment by mfalk118** [comment]
How should we then "Handle" the event? Alternatively you should provide a TempBLOB record parameter where we can return the generated file, and then you can say (Pseudo code)

IF Handled THEN
  TempBlob.BLOB.EXPORT(FilePath)
ELSE
  REPORT.SAVEAS....
