### ISSUE TITLE
[Event Modification] codeunit 5815 "Undo Sales Shipment Line" OnAfterCopyItemJnlLineFromSalesShpt

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13940]
Can you please add the following to an event:

            OnAfterCopyItemJnlLineFromSalesShpt(ItemJnlLine, SalesShptHeader, SalesShptLine, TempWhseJnlLine);

to 

            OnAfterCopyItemJnlLineFromSalesShpt(ItemJnlLine, SalesShptHeader, SalesShptLine, TempWhseJnlLine,WhseUndoQty);

WhseUndoQty as var

**Comment by db-bc** [comment]
Is it to be `var`, like your other requests submitted around the same time?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
