### ISSUE TITLE
[Event Modification] codeunit 22 "Item Jnl.-Post Line" OnAfterInsertItemLedgEntry

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13943]
OnAfterInsertItemLedgEntry(ItemLedgEntry, ItemJnlLine, ItemLedgEntryNo, ValueEntryNo, ItemApplnEntryNo);

To 

            OnAfterInsertItemLedgEntry(ItemLedgEntry, ItemJnlLine, ItemLedgEntryNo, ValueEntryNo, ItemApplnEntryNo; GlobalValueEntry, TransferItem, InventoryPostingToGL, OldItemLedgEntry);

GlobalValueEntry: Record "Value Entry"; 
TransferItem: Boolean;
var InventoryPostingToGL: Codeunit "Inventory Posting To G/L"; 
var OldItemLedgerEntry: Record "Item Ledger Entry"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
