### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" OnInsertValueEntriesFromUndo

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13947]
Hello, 

Is it possible to add the following event?

              OldValueEntry, NewValueEntry, NewItemLedgEntry, ItemJnlLine."Document Line No.", -1,
              0, NewItemLedgEntry.Quantity);
        end else
            InsertCorrValueEntry(
              OldValueEntry, NewValueEntry, NewItemLedgEntry, ItemJnlLine."Document Line No.", -1,
              NewItemLedgEntry.Quantity, NewItemLedgEntry.Quantity);

        // DINNL <<
        DINOnInsertValueEntriesFromUndo(OldValueEntry, NewItemLedgEntry, NewValueEntry, ItemJnlLine);
        // DINNL >>
        UpdateOldItemLedgEntry(OldItemLedgEntry, NewItemLedgEntry."Posting Date");
        UpdateItemApplnEntry(OldItemLedgEntry."Entry No.", NewItemLedgEntry."Posting Date");

    [IntegrationEvent(TRUE, TRUE)]
    local procedure DINOnInsertValueEntriesFromUndo(var OldValueEntry2: Record "Value Entry"; var NewItemLedgEntry: Record "Item Ledger Entry"; var NewValueEntry: Record "Value Entry"; var ItemJnlLine: Record "Item Journal Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
