### ISSUE TITLE
[Event Modification] codeunit 5814 "Undo Return Shipment Line" OnAfterCopyItemJnlLineFromReturnShpt

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13941]
Can you please add the following to an event:

            OnAfterCopyItemJnlLineFromReturnShpt(ItemJnlLine, ReturnShptHeader, ReturnShptLine);
 to 

            OnAfterCopyItemJnlLineFromReturnShpt(ItemJnlLine, ReturnShptHeader, ReturnShptLine,WhseUndoQty);

WhseUndoQty as var

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
