### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" OnAfterCalcQtyToHandleForTrackedQtyOnDocumentLine

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13942]
Is it possible to add the following event? we dont like subscribing to OnBeforeCalcQtyToHandleForTrackedQtyOnDocumentLine because we need to reqrite your code and if you change something in that code we will miss that.

procedure CalcQtyToHandleForTrackedQtyOnDocumentLine(SourceType: Integer; SourceSubtype: Option; SourceID: Code[20]; SourceRefNo: Integer): Decimal
    var
        ReservEntry: Record "Reservation Entry";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalcQtyToHandleForTrackedQtyOnDocumentLine(ReservEntry, IsHandled);
        If IsHandled then
            exit;

        ReservEntry.SetSourceFilter(SourceType, SourceSubtype, SourceID, SourceRefNo, true);
        ReservEntry.SetSourceFilter('', 0);
        ReservEntry.SetFilter("Item Tracking", '<>%1', ReservEntry."Item Tracking"::None);
        ReservEntry.CalcSums("Qty. to Handle (Base)");
        // DINNL <<
        DINOnAfterCalcQtyToHandleForTrackedQtyOnDocumentLine(ReservEntry);
        // DINNL >>
        exit(ReservEntry."Qty. to Handle (Base)");
    end;

    [IntegrationEvent(false, false)]
    local procedure DINOnAfterCalcQtyToHandleForTrackedQtyOnDocumentLine(var ReservEntry: Record "Reservation Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
