### ISSUE TITLE
Remove scope from procedure FindStreetNameFromAddress in codeunit 11401 "Post Code Management"

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13952]
Hello,

Is it possible to remove the scope from the following function:

    [Scope('OnPrem')]
    procedure FindStreetNameFromAddress(var Address: Text[100]; var Address2: Text[50]; var PostCode: Code[20]; var City: Text[50]; CountryCode: Code[10]; var PhoneNo: Text[30]; var FaxNo: Text[30])

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
