### ISSUE TITLE
[Procedure modification] codeunit 82 "Sales-Post + Print"

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13951]
Is it possible to make the following functions accessable for an extension:

PrintReceive
PrintInvoice
PrintShip
PrintCrMemo

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
