### ISSUE TITLE
[Protected Request] page 161 "Purchase Statistics" PurchPost

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13954]
Hello,

Is it possible to get the variable PurchPost in page 161 "Purchase Statistics" as protected var?

        PurchPost: Codeunit "Purch.-Post";

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
