### ISSUE TITLE
[Event Request] OnAfterValidateShortcutDimCode

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#1396]
Greetings - To port one of our NAV add-ons to BC, we need to run some additional logic every time the ValidateShortcutDimCode function finishes (in every table that has that function...basically every table that supports shortcut dimensions).  Can an OnAfterValidateShortcutDimCode integration event be added to every instance of that function?

**Comment by RHansenEpimatic** [comment]
Thanks Jesper.  I think this would work perfectly and is much better than my requested approach.

**Comment by RHansenEpimatic** [comment]
If you make this change, would it become active in BC SAAS as part of the April 2019 update?  Is the cloud/SAAS version updated more frequently than once every six months?

**Comment by AlexanderYakunin** [comment]
I'm not Jesper :-) but Alexander. Yes, we provide monthly updates for BC SAAS and it will be available in first monthly update after April 2019 release.

**Comment by RHansenEpimatic** [comment]
Sorry Alex!  I misread the history.  This sounds great - please proceed and let me know once it's done.  I assume i then just need to watch for the next package update on Collaborate to download it locally.

**Comment by RHansenEpimatic** [comment]
Sorry Alexander...i realized i need a bit more here.  On the various journal / document subform pages, if the page action is used to open Dimensions, i would also need logic added.  Right now the code behind the action is generally:

ShowDimensions;
CurrPage.SAVERECORD;

Would it be possible to get code added after that on all journals and document subforms for:

ShowShortcutDimCode(ShortcutDimCode);

?
