### ISSUE TITLE
[Protected Request] page 402 "Sales Order Statistics" SalesPost

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13962]
Hello,

Is it possible to get the variable SalesPost in page 402 "Sales Order Statistics" as protected var?

       SalesPost: Codeunit "Sales-Post";

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
