### ISSUE TITLE
Whse.-Activity-Register - UpdateTempBinContentBuffer invalide Key

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/ALAppExtensions#13964]
The key of table Bin Content Buffer has changed from 
"Location Code", "Bin Code", "Item No.", "Variant Code", "Unit of Measure Code", "Lot No.", "Serial No."
to
"Location Code", "Bin Code", "Item No.", "Variant Code", "Unit of Measure Code", "Lot No.", "Serial No.", "Package No."
But in Codeunit Whse.-Activity-Register in function UpdateTempBinContentBuffer is a get to the old key.
So it is not possible to create a Put-away to two Lots on one Bin

```
 local procedure UpdateTempBinContentBuffer(WhseActivLine: Record "Warehouse Activity Line")
    var
        WMSMgt: Codeunit "WMS Management";
        UOMCode: Code[10];
        Sign: Integer;
    begin
        with WhseActivLine do begin
            if Location."Directed Put-away and Pick" then
                UOMCode := "Unit of Measure Code"
            else
                UOMCode := WMSMgt.GetBaseUOM("Item No.");
-            if not TempBinContentBuffer.Get("Location Code", "Bin Code", "Item No.", "Variant Code", UOMCode, "Lot No.", "Serial No.")
+            if not TempBinContentBuffer.Get("Location Code", "Bin Code", "Item No.", "Variant Code", UOMCode, "Lot No.", "Serial No.", "Package No.")
            then begin
                TempBinContentBuffer.Init();
                TempBinContentBuffer."Location Code" := "Location Code";
                TempBinContentBuffer."Zone Code" := "Zone Code";
                TempBinContentBuffer."Bin Code" := "Bin Code";
                TempBinContentBuffer."Item No." := "Item No.";
                TempBinContentBuffer."Variant Code" := "Variant Code";
                TempBinContentBuffer."Unit of Measure Code" := UOMCode;
                TempBinContentBuffer.CopyTrackingFromWhseActivityLine(WhseActivLine);
                OnUpdateTempBinContentBufferOnBeforeInsert(TempBinContentBuffer, WhseActivLine);
                TempBinContentBuffer.Insert();
            end;
            Sign := 1;
            if "Action Type" = "Action Type"::Take then
                Sign := -1;

            TempBinContentBuffer."Base Unit of Measure" := WMSMgt.GetBaseUOM("Item No.");
            TempBinContentBuffer."Qty. to Handle (Base)" := TempBinContentBuffer."Qty. to Handle (Base)" + Sign * "Qty. to Handle (Base)";
            TempBinContentBuffer."Qty. Outstanding (Base)" :=
              TempBinContentBuffer."Qty. Outstanding (Base)" + Sign * "Qty. Outstanding (Base)";
            TempBinContentBuffer.Cubage := TempBinContentBuffer.Cubage + Sign * Cubage;
            TempBinContentBuffer.Weight := TempBinContentBuffer.Weight + Sign * Weight;
            TempBinContentBuffer.Modify();
        end;
    end;
```

Version: DE Business Central 18.3 (Plattform 18.0.27224.27469 + Anwendung 18.3.27240.27480)

**Comment by AlexanderYakunin** [comment]
Platform automatically detect right key, even if you only type few first fields for the key, so key 

"Location Code", "Bin Code", "Item No.", "Variant Code", "Unit of Measure Code", "Lot No.", "Serial No.", "Package No."

used here.

**Comment by FSchneiderYav** [comment]
My problem with this solution ist, that I have a Put-away with a splitted Place line, so I have two lines who the values of "Location Code", "Bin Code", "Item No.", "Variant Code", "Unit of Measure Code", "Lot No.", "Serial No." and "Package No." are the same. Now the get find no record, because the Get looks for a record witch Package No. '' and insert a new line with the already existing Key

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
