### ISSUE TITLE
[Event Request] Table 210 UpdateUnitCost, Change in Table 1003 UpdateUnitCost

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#13979]
1. Can you please provide the similiar publisher "OnBeforeUpdateUnitCost" in T210 JobJournalLine as already available in JobPlanningLine (T1003)
2.  Can you please extend the publisher in T1003 to var JobPlanningLine

1.-T210----------------------------------------
    local procedure UpdateUnitCost()
    var
        RetrievedCost: Decimal;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateUnitCost(Rec, IsHandled);
        if IsHandled then
            exit;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateUnitCost(var JobJounralLine: Record "Job Journal Line"; var IsHandled: Boolean)
    begin
    end;

2. -T1003----------------------------------------
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateUnitCost(var JobPlanningLine: Record "Job Planning Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
