### ISSUE TITLE
page 9095 "Vendor Hist. Buy-from FactBox" - OnFindRecordEvent - Event Request

### ISSUE THREAD

**Issue by ZacRyon** [microsoft/ALAppExtensions#13973]
page 9095 "Vendor Hist. Buy-from FactBox"
{
    Caption = 'Buy-from Vendor History';
    PageType = CardPart;
    SourceTable = Vendor;

    layout
    {
        area(content)
        {
            field("No."; "No.")
            {
                ApplicationArea = All;
                Caption = 'Vendor No.';
                ToolTip = 'Specifies the number of the vendor. The field is either filled automatically from a defined number series, or you enter the number manually because you have enabled manual number entry in the number-series setup.';

                trigger OnDrillDown()
                begin
                    ShowDetails;
                end;
            }
            group(Control23)
            {
                ShowCaption = false;
                Visible = false;
                field("No. of Quotes"; "No. of Quotes")
                {
                    ApplicationArea = Suite;
                    Caption = 'Quotes';
                    DrillDownPageID = "Purchase Quotes";
                    ToolTip = 'Specifies the number of purchase quotes that exist for the vendor.';
                }
                field("No. of Blanket Orders"; "No. of Blanket Orders")
                {
                    ApplicationArea = Suite;
                    Caption = 'Blanket Orders';
                    DrillDownPageID = "Blanket Purchase Orders";
                    ToolTip = 'Specifies the number of purchase blanket orders that exist for the vendor.';
                }
                field("No. of Orders"; "No. of Orders")
                {
                    ApplicationArea = Suite;
                    Caption = 'Orders';
                    DrillDownPageID = "Purchase Order List";
                    ToolTip = 'Specifies the number of purchase orders that exist for the vendor.';
                }
                field("No. of Invoices"; "No. of Invoices")
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Invoices';
                    DrillDownPageID = "Purchase Invoices";
                    ToolTip = 'Specifies the number of unposted purchase invoices that exist for the vendor.';
                }
                field("No. of Return Orders"; "No. of Return Orders")
                {
                    ApplicationArea = PurchReturnOrder;
                    Caption = 'Return Orders';
                    DrillDownPageID = "Purchase Return Order List";
                    ToolTip = 'Specifies the number of purchase return orders that exist for the vendor.';
                }
                field("No. of Credit Memos"; "No. of Credit Memos")
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Credit Memos';
                    DrillDownPageID = "Purchase Credit Memos";
                    ToolTip = 'Specifies the number of unposted purchase credit memos that exist for the vendor.';
                }
                field("No. of Pstd. Return Shipments"; "No. of Pstd. Return Shipments")
                {
                    ApplicationArea = PurchReturnOrder;
                    Caption = 'Pstd. Return Shipments';
                    ToolTip = 'Specifies the number of posted return shipments that exist for the vendor.';
                }
                field("No. of Pstd. Receipts"; "No. of Pstd. Receipts")
                {
                    ApplicationArea = Suite;
                    Caption = 'Pstd. Receipts';
                    ToolTip = 'Specifies the number of posted purchase receipts that exist for the vendor.';
                }
                field("No. of Pstd. Invoices"; "No. of Pstd. Invoices")
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Pstd. Invoices';
                    ToolTip = 'Specifies the number of posted purchase invoices that exist for the vendor.';
                }
                field("No. of Pstd. Credit Memos"; "No. of Pstd. Credit Memos")
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Pstd. Credit Memos';
                    ToolTip = 'Specifies the number of posted purchase credit memos that exist for the vendor.';
                }
                field(NoOfIncomingDocuments; "No. of Incoming Documents")
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Incoming Documents';
                    ToolTip = 'Specifies incoming documents, such as vendor invoices in PDF or as image files, that you can manually or automatically convert to document records, such as purchase invoices. The external files that represent incoming documents can be attached at any process stage, including to posted documents and to the resulting vendor, customer, and general ledger entries.';
                }
            }
            cuegroup(Control1)
            {
                ShowCaption = false;
                field(CueQuotes; "No. of Quotes")
                {
                    ApplicationArea = Suite;
                    Caption = 'Quotes';
                    DrillDownPageID = "Purchase Quotes";
                    ToolTip = 'Specifies the number of purchase quotes that exist for the vendor.';
                }
                field(CueBlanketOrders; "No. of Blanket Orders")
                {
                    ApplicationArea = Suite;
                    Caption = 'Blanket Orders';
                    DrillDownPageID = "Blanket Purchase Orders";
                    ToolTip = 'Specifies the number of purchase blanket orders that exist for the vendor.';
                }
                field(CueOrders; "No. of Orders")
                {
                    ApplicationArea = Suite;
                    Caption = 'Orders';
                    DrillDownPageID = "Purchase Order List";
                    ToolTip = 'Specifies the number of purchase orders that exist for the vendor.';
                }
                field(CueInvoices; "No. of Invoices")
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Invoices';
                    DrillDownPageID = "Purchase Invoices";
                    ToolTip = 'Specifies the number of unposted purchase invoices that exist for the vendor.';
                }
                field(CueReturnOrders; "No. of Return Orders")
                {
                    ApplicationArea = PurchReturnOrder;
                    Caption = 'Return Orders';
                    DrillDownPageID = "Purchase Return Order List";
                    ToolTip = 'Specifies the number of purchase return orders that exist for the vendor.';
                }
                field(CueCreditMemos; "No. of Credit Memos")
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Credit Memos';
                    DrillDownPageID = "Purchase Credit Memos";
                    ToolTip = 'Specifies the number of unposted purchase credit memos that exist for the vendor.';
                }
                field(CuePostedRetShip; "No. of Pstd. Return Shipments")
                {
                    ApplicationArea = PurchReturnOrder;
                    Caption = 'Pstd. Return Shipments';
                    ToolTip = 'Specifies the number of posted return shipments that exist for the vendor.';
                }
                field(CuePostedReceipts; "No. of Pstd. Receipts")
                {
                    ApplicationArea = Suite;
                    Caption = 'Pstd. Receipts';
                    ToolTip = 'Specifies the number of posted purchase receipts that exist for the vendor.';
                }
                field(CuePostedInvoices; "No. of Pstd. Invoices")
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Pstd. Invoices';
                    ToolTip = 'Specifies the number of posted purchase invoices that exist for the vendor.';
                }
                field(CuePostedCreditMemos; "No. of Pstd. Credit Memos")
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Pstd. Credit Memos';
                    ToolTip = 'Specifies the number of posted purchase credit memos that exist for the vendor.';
                }
                field(CueIncomingDocuments; "No. of Incoming Documents")
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Incoming Documents';
                    ToolTip = 'Specifies incoming documents, such as vendor invoices in PDF or as image files, that you can manually or automatically convert to document records, such as purchase invoices. The external files that represent incoming documents can be attached at any process stage, including to posted documents and to the resulting vendor, customer, and general ledger entries.';
                }
            }
        }
    }

    actions
    {
    }

    //SPLN 1.01 Start
    trigger OnFindRecord(Which: text): Boolean
    var
        ReturnValue: Boolean;
    begin
        OnFindRecordEvent(Which, ReturnValue);
        exit(ReturnValue)
    end;

    [IntegrationEvent(true, false)]
    local procedure OnFindRecordEvent(Which: text; var ReturnValue: Boolean)
    begin
    end;
    //SPLN 1.01 End

    var
        ShowVendorNo: Boolean;

    local procedure ShowDetails()
    begin
        PAGE.Run(PAGE::"Vendor Card", Rec);
    end;

    [Obsolete('Visibility of the Vendor No. can be controlled through personalizaition or PTE', '17.0')]
    procedure SetVendorNoVisibility(Visible: Boolean)
    begin
        ShowVendorNo := Visible;
    end;
}

**Comment by Stepanenko-Vadim** [comment]
We cannot add empty triggers, it will break default behavior.
