### ISSUE TITLE
[Event Request] codeunit 99000830 "Create Reserv. Entry" DINOnAfterTransferReservEntry

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13974]
if (NewReservEntry."Source Type" = DATABASE::"Sales Line") and
                       (OldReservEntry."Source Type" = DATABASE::"Item Journal Line") and
                       (OldReservEntry."Reservation Status" = OldReservEntry."Reservation Status"::Reservation)
                    then begin
                        if ItemTrkgMgt.GetWhseItemTrkgSetup(OldReservEntry."Item No.") and
                            Location.RequireShipment(OldReservEntry."Location Code")
                        then
                            CreateWhseItemTrkgLines(NewReservEntry);
                    end;
                end else
                    if CarriedItemTrackingSetup.TrackingExists() then
                        if NewReservEntry.Get(NewReservEntry."Entry No.", not NewReservEntry.Positive) then; // Get partner-record
            end;

        // DINNL <<
        DINOnAfterTransferReservEntry(NewReservEntry, OldReservEntry);
        // DINNL >>
        if CarriedItemTrackingSetup.TrackingExists() then begin
            if NewReservEntry."Qty. to Handle (Base)" = 0 then
                NewReservEntry.Validate("Quantity (Base)");
            NewReservEntry.CopyTrackingFromItemTrackingSetup(CarriedItemTrackingSetup);
            OnTransferReservEntryOnBeforeUpdateItemTracking(NewReservEntry);
            NewReservEntry.UpdateItemTracking;
            if NewReservEntry.Modify then;
        end;

    [IntegrationEvent(false, false)]
    local procedure DINOnAfterTransferReservEntry(var NewReservEntry: Record "Reservation Entry"; OldReservEntry: Record "Reservation Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
