### ISSUE TITLE
Business central on-prem croatian (hr-HR) another language bug (Date formula)

### ISSUE THREAD

**Issue by fmoric** [Microsoft/ALAppExtensions#1397]
Hello,

There is another bug in Croatian system language, in On-Prem release of Business Central, that comes with installation.

Date formula for Week cannot be entered it says that it is not a valid unit, but it shows it as a valid unit in error message.
English unit is **W**, Croatian is **T**.

![error](https://user-images.githubusercontent.com/18283753/53623167-9ccd2c00-3bfc-11e9-97e1-c40c11656faa.png)

**Comment by JesperSchulz** [comment]
Nice catch! Let's get the issue to a team who will fix and backport it, as this repo only is for extensibility related issues in the upcoming release. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.
