### ISSUE TITLE
[Protected Request] page 403 "Purchase Order Statistics"

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13976]
Hello,

Is it possible to get these variables as protected var in page 403 "Purchase Order Statistics"?

        TotalPurchLine: array[3] of Record "Purchase Line"; 
        TotalPurchLineLCY: array[3] of Record "Purchase Line"; 
        PurchPost: Codeunit "Purch.-Post";

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
