### ISSUE TITLE
[Event Request] page 5530 "Item Availability by Event" OnBeforeOnOpenPage

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13989]
trigger OnOpenPage()
    begin
        // DINNL <<
        DINOnBeforeOnOpenPage(IncludeBlanketOrders);
        // DINNL >>
        if ItemIsSet then
            InitAndCalculatePeriodEntries()
        else
            InitItemRequestFields();
    end;

    [IntegrationEvent(false, false)]
    local procedure DINOnBeforeOnOpenPage(var IncludeBlanketOrders: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
