### ISSUE TITLE
[Protected Request] page 6510 "Item Tracking Lines"

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#13983]
Hello,

Is it possible to get these variables as protected var in page 6510 "Item Tracking Lines"?

        TotalItemTrackingLine: Record "Tracking Specification"; 
        TempItemTrackLineInsert: Record "Tracking Specification" temporary; 
        ItemTrackingDataCollection: Codeunit "Item Tracking Data Collection"; 
        QtyPerUOM: Decimal; 
        CurrentSignFactor: Integer; 
        InsertIsBlocked: Boolean; 
        ForBinCode: Code[20];

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
