### ISSUE TITLE
Basic functionality: StrMenu not supporting '&' Shortcuts

### ISSUE THREAD

**Issue by SweconThomasH** [microsoft/ALAppExtensions#13993]
The call to StrMenu doesn't seem to support the '&' shortcuts like it used to.

Example in standard CodeUnit 81: `ShipInvoiceQst: Label '&Ship,&Invoice,Ship &and Invoice';` 

In the posting dialog, the user could select 'Invoice' by just pressing 'I'. This doesn't seem to work any more. I quote one of our key users: "Can we have this back, please?"

**Comment by db-bc** [comment]
I don't see how this is related to extensibility, nor would it relate to the other GitHub repo for the AL language/compiler. It's probably best reported via partner support and/or on BCIdeas

**Comment by AlexanderYakunin** [comment]
Yes, this forum is not intended for bug reporting or ideas. You can do this using aka.ms/bcideas or technical support.
