### ISSUE TITLE
[Event Request] codeunit 5530 "Calc. Item Availability" OnGetBlanketSalesOrdersSetQtyReleased

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13996]
InsertEntry(InvtEventBuf);
                            QtyReleased := 0;
                        end else
                            QtyReleased -= "Outstanding Qty. (Base)";
                        // DINNL <<
                        DINOnGetBlanketSalesOrdersSetQtyReleased(BlanketSalesLine, QtyReleased);
                        // DINNL >>
                    until Next() = 0;
                    SetRange("Document No.");
                    SetRange("Line No.");
                until Next() = 0;
        end;

        InvtEventBuf.Copy(CopyOfInvtEventBuf);
    end;

    local procedure GetPlanningLines(var InvtEventBuf: Record "Inventory Event Buffer"; var Item: Record Item)

    [IntegrationEvent(false, false)]
    local procedure DINOnGetBlanketSalesOrdersSetQtyReleased(BlanketSalesLine: Record "Sales Line"; QtyReleased: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
