### ISSUE TITLE
[Event Request] T1003 UpdateAllAmounts, OnAfterUpdateAllAmounts

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#13999]
Can you please extend publisher OnAfterUpdateAllAmounts with xRec parameter, as we want to react to the changes in amounts, for example make some own logging functionality, so that the user can trace how the values evolved.

    local procedure UpdateAllAmounts()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateAllAmounts(Rec, xRec, IsHandled);
        if IsHandled then
            exit;

        InitRoundingPrecisions();

        UpdateUnitCost;
        FindPriceAndDiscount(CurrFieldNo);
        UpdateTotalCost;
        HandleCostFactor;
        UpdateUnitPrice;
        UpdateTotalPrice;
        UpdateAmountsAndDiscounts;
        UpdateRemainingCostsAndAmounts("Currency Date", "Currency Factor");
        if Type = Type::Text then
            FieldError(Type);
        // -NEW001
        // OnAfterUpdateAllAmounts(Rec);
        OnAfterUpdateAllAmounts(Rec, xRec);
        // +NEW001
    end;

    // -NEW001
    [IntegrationEvent(false, false)]
    // local procedure OnAfterUpdateAllAmounts(var JobPlanningLine: Record "Job Planning Line")
    local procedure OnAfterUpdateAllAmounts(var JobPlanningLine: Record "Job Planning Line"; xJobPlanningLine: Record "Job Planning Line")
    // +NEW001
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
