### ISSUE TITLE
[Event Request] codeunit 5530 "Calc. Item Availability" OnGetBlanketSalesOrdersCalcQtyReleased

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13994]
with BlanketSalesLine do begin
            if FindLinesWithItemToPlan(Item, "Document Type"::"Blanket Order") then
                repeat
                    InvtEventBuf.SetRange(Type, InvtEventBuf.Type::Sale);
                    InvtEventBuf.SetRange("Derived from Blanket Order", true);
                    InvtEventBuf.SetRange("Ref. Order No.", "Document No.");
                    InvtEventBuf.SetRange("Ref. Order Line No.", "Line No.");
                    if InvtEventBuf.Find('-') then
                        repeat
                            QtyReleased -= InvtEventBuf."Remaining Quantity (Base)";
                            // DINNL <<
                            DINOnGetBlanketSalesOrdersCalcQtyReleased(InvtEventBuf);
                            // DINNL >>
                        until InvtEventBuf.Next() = 0;
                    SetRange("Document No.", "Document No.");
                    SetRange("Line No.", "Line No.");

    [IntegrationEvent(false, false)]
    local procedure DINOnGetBlanketSalesOrdersCalcQtyReleased(InventoryEventBuffer: Record "Inventory Event Buffer")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
