### ISSUE TITLE
[Event Request] codeunit 5530 "Calc. Item Availability" OnGetBlanketSalesOrdersCalculateQuantities

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13995]
until InvtEventBuf.Next() = 0;
                    SetRange("Document No.", "Document No.");
                    SetRange("Line No.", "Line No.");
                    repeat
                        if "Outstanding Qty. (Base)" > QtyReleased then begin
                            InvtEventBuf.TransferFromSalesBlanketOrder(
                              BlanketSalesLine, "Outstanding Qty. (Base)" - QtyReleased);
                            // DINNL <<
                            DINOnGetBlanketSalesOrdersCalculateQuantities(BlanketSalesLine, InvtEventBuff);
                            // DINNL >>
                            InsertEntry(InvtEventBuf);
                            QtyReleased := 0;
                        end else
                            QtyReleased -= "Outstanding Qty. (Base)";

    [IntegrationEvent(false, false)]
    local procedure DINOnGetBlanketSalesOrdersCalculateQuantities(BlanketSalesLine: Record "Sales Line"; var InventoryEventBuffer: Record "Inventory Event Buffer")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
