### ISSUE TITLE
[Code Defect] codeunit 22 "Item Jnl.-Post Line", procedure SetupSplitJnlLine

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#13990]
There is the code in codeunit 22 "Item Jnl.-Post Line", in procedure SetupSplitJnlLine. Shouldn't be there a reset of IsHandled variable before call of OnSetupSplitJnlLineOnBeforeReallocateTrkgSpecification event?

```
IsHandled := false;
OnBeforeCalcExpirationDate(ItemJnlLine2, CalcExpirationDate, IsHandled);
if not IsHandled then
    if Format(Item."Expiration Calculation") <> '' then
        CalcExpirationDate := CalcDate(Item."Expiration Calculation", ItemJnlLine2."Document Date");

IsHandled := false;  //************ missing??
OnSetupSplitJnlLineOnBeforeReallocateTrkgSpecification(GlobalItemTrackingCode, TempTrackingSpecification, ItemJnlLine2, SignFactor, IsHandled);
if not IsHandled then
    if SignFactor * ItemJnlLine2.Quantity < 0 then // Demand
        if GlobalItemTrackingCode."SN Specific Tracking" or GlobalItemTrackingCode."Lot Specific Tracking" then
            LateBindingMgt.ReallocateTrkgSpecification(TempTrackingSpecification);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
