### ISSUE TITLE
[Event Request] codeunit 5705 "TransferOrder-Post Receipt" OnRunPostGenJnlLineBuffer

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#13992]
TransLine.LockTable();
            if WhsePosting then
                WhseEntry.LockTable();

            TransLine.SetFilter(Quantity, '<>0');
            TransLine.SetFilter("Qty. to Receive", '<>0');
            if TransLine.Find('-') then
                repeat
                    TransLine.Validate("Quantity Received", TransLine."Quantity Received" + TransLine."Qty. to Receive");
                    TransLine.UpdateWithWarehouseShipReceive;
                    ReservMgt.SetReservSource(ItemJnlLine);
                    ReservMgt.SetItemTrackingHandling(1); // Allow deletion
                    ReservMgt.DeleteReservEntries(true, 0);
                    TransLine.Modify();
                    OnAfterTransLineUpdateQtyReceived(TransLine, SuppressCommit);
                until TransLine.Next() = 0;
            // DINNL <<
            DINOnRunPostGenJnlLineBuffer(ItemJnlPostLine);
            // DINNL >>

            if WhseReceive then
                WhseRcptLine.LockTable();
            LockTable();
            if WhseReceive then begin

    [IntegrationEvent(false, false)]
    local procedure DINOnRunPostGenJnlLineBuffer(var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
