### ISSUE TITLE
[EventRequest]Table 570 G/L Account Category - GetBalance - OnGetBalanceOnBeforeProcessChildren 

### ISSUE THREAD

**Issue by mikolajsledz** [microsoft/ALAppExtensions#13997]
Due to Polish Localization App building, we need publisher in T570. We need to override default calculation of category balance.

In Function: GetBalance the is function OnGetBalanceOnBeforeProcessChildren, but it isn't declared with IntegrationEvent Attribute
![image](https://user-images.githubusercontent.com/62235137/129363627-58d729a4-be17-4029-a318-3a65977802f9.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
