### ISSUE TITLE
Additional ISO Codes

### ISSUE THREAD

**Issue by JasnaPirnar** [Microsoft/ALAppExtensions#1399]
We have additional request since you added ISO Codes on tables Currency and Country/Regions.

Is there posibility to add on Country/Region also:
- ISO Code (three-letter) code. We use this field when preparing some reports for tax authorities.

We also have additional question. How do you set ISO Code and ISO Numeric Code for local currency? When exporting data for different currencies we need to export information for ISO Codes also for local currency, since we post local entries without entered currency on documents. Is there posibility to add on General Ledger Setup additional fields:
- Loc. Currency ISO Numeric Code 
- Loc. Currency ISO Code

Thank you
Jasna

**Comment by JasnaPirnar** [comment]
Ok, can you just send me new addres where will be transferred.

**Comment by JesperSchulz** [comment]
Thanks for sharing your idea with us. We're always looking for better ways to do things. However, this isn't the right place to share it either. You'll have better luck getting it implemented and noticed by other partners if you post it to the following resource:

- For functional improvements, go to [Business Central - Ideas](http://aka.ms/bcideas)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
