### ISSUE TITLE
Event Request: Table 81 - CheckDirectPosting

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/ALAppExtensions#14]
In reference to the issue I posted on the AL repository (https://github.com/Microsoft/AL/issues/3543) I would like to suggest a change on the events OnBefore/AfterCheckDirectPosting.

Could you please include the calling "GenJnlLine" in these two events? The new signature would be

**Table 81**
````
LOCAL [IntegrationEvent] OnAfterCheckDirectPosting(VAR GLAccount : Record "G/L Account";GenJnlLine : Record "Gen. Journal Line")

LOCAL [IntegrationEvent] OnBeforeCheckDirectPosting(VAR GLAccount : Record "G/L Account";GenJnlLine : Record "Gen. Journal Line";VAR IsHandled : Boolean)
````

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!
