### ISSUE TITLE
[Function Expose] PurchaseUpdateTotalsControls in "Document Totals" Codeunit

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/ALAppExtensions#140]
We need the function **PurchaseUpdateTotalsControls** to be external in codeunit 57 **Document Totals**

The reason we need this is to re-calculate the global variables "TotalPurchaseLine" and "TotalPurchaseHeader", which are inaccessible on a page extension of multiple pages (54, 55, 97, 98, 139, 141).  There is no way for us to access global variables, so we'll have to re-calculate our own to be able to do calculations on it and show it on the pages... .  Highly inefficient, but I don't see another solution.  If you have any, I'm all ears ;-).

**Comment by JesperSchulz** [comment]
We'll look into it :-)

**Comment by darjoo** [comment]
Hi, we have accepted your request. You'll see it in the next minor release. Congrat's on helping the extension development community!
