### ISSUE TITLE
[Event Modification] Codeunit 5704 and 5705: OnBeforeTransferOrderPostReceipt and OnBeforeTransferOrderPostShipment events

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#14008]
Hi Microsoft AL Team,

Could you please pass the **CommitIsSuppressed** parameter as _var_ for the following integration events? Thank you!

1. Codeunit 5705 "TransferOrder-Post Receipt"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferOrderPostReceipt(var TransferHeader: Record "Transfer Header"; CommitIsSuppressed: Boolean)
    begin
    end;
```

2. Codeunit 5704 "TransferOrder-Post Shipment"

```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeTransferOrderPostShipment(var TransferHeader: Record "Transfer Header"; CommitIsSuppressed: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
