### ISSUE TITLE
[Event Request] Table "Report Selections".OnAfterSetEmailBodyUsageFilters

### ISSUE THREAD

**Issue by LPhanMCS** [microsoft/ALAppExtensions#14005]
Table "Report Selections":

procedure SetEmailBodyUsageFilters(ReportUsage: Enum "Report Selection Usage")
begin
    Reset();
    SetRange(Usage, ReportUsage);
    SetRange("Use for Email Body", true);

    //>>>>
    OnAfterSetEmailBodyUsageFilters(Rec, ReportUsage);
    //<<<<
end;

//>>>>
[IntegrationEvent(false, false)]
local procedure OnAfterSetEmailBodyUsageFilters(var ReportSelections: Record "Report Selections"; ReportUsage: Enum "Report Selection Usage")
begin
end;
//<<<<

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
