### ISSUE TITLE
[Event Request] Table "Custom Report Selection".OnAfterFilterEmailBodyUsage

### ISSUE THREAD

**Issue by LPhanMCS** [microsoft/ALAppExtensions#14006]
Table "Custom Report Selection":

procedure FilterEmailBodyUsage(NewSourceType: Integer; NewSourceNo: Code[20]; NewUsage: Option)
begin
    FilterReportUsage(NewSourceType, NewSourceNo, NewUsage);
    SetRange("Use for Email Body", true);
    
    //>>>>
    OnAfterFilterEmailBodyUsage(Rec, NewSourceType, NewSourceNo, NewUsage);
    //<<<<
end;

//>>>>
[IntegrationEvent(false, false)]
local procedure OnAfterFilterEmailBodyUsage(var CustomReportSelection: Record "Custom Report Selection"; NewSourceType: Integer; NewSourceNo: Code[20]; NewUsage: Option)
begin
end;
//<<<<

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
