### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line", event OnAfterPostItemJnlLine

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#14003]
Could you please change the value of IncludeSender parameter in the event OnAfterPostItemJnlLine?
```
[IntegrationEvent(true, false)]  //********************
local procedure OnAfterPostItemJnlLine(var ItemJournalLine: Record "Item Journal Line"; ItemLedgerEntry: Record "Item Ledger Entry"; var ValueEntryNo: Integer; var InventoryPostingToGL: Codeunit "Inventory Posting To G/L"; CalledFromAdjustment: Boolean; CalledFromInvtPutawayPick: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
