### ISSUE TITLE
Report 840 - OnBeforeSetCashFlowDate - Event Request

### ISSUE THREAD

**Issue by Athon-dev** [microsoft/ALAppExtensions#14010]
**REQUEST**: Create Event on before Function SetCashFlowDate in procedure InsertCFLineForSalesLine() AND procedure InsertCFLineForPurchaseLine()
I would request the function with another date

**SUGGEST**:

    local procedure InsertCFLineForPurchaseLine()
    var
        PurchLine2: Record "Purchase Line";
    begin
        PurchLine2 := "Purchase Line";
        if Summarized and (PurchLine2.Next <> 0) and (PurchLine2."Buy-from Vendor No." <> '') and
           (PurchLine2."Document No." = "Purchase Line"."Document No.")
        then begin
            TotalAmt += CalculateLineAmountForPurchaseLine(PurchHeader, "Purchase Line");
            MultiSalesLines := true;
        end else
            with CFWorksheetLine2 do begin
                Init();
                "Source Type" := "Source Type"::"Purchase Orders";
                "Source No." := "Purchase Line"."Document No.";
                "Source Line No." := "Purchase Line"."Line No.";
                "Document Type" := "Document Type"::Invoice;
                "Document Date" := PurchHeader."Document Date";
                "Shortcut Dimension 1 Code" := PurchHeader."Shortcut Dimension 1 Code";
                "Shortcut Dimension 2 Code" := PurchHeader."Shortcut Dimension 2 Code";
                "Dimension Set ID" := PurchHeader."Dimension Set ID";
                "Cash Flow Account No." := CFSetup."Purch. Order CF Account No.";
                Description :=
                  CopyStr(
                    StrSubstNo(
                      PurchaseDocumentDescriptionTxt,
                      PurchHeader."Document Type",
                      Format(PurchHeader."Order Date"),
                      PurchHeader."Buy-from Vendor Name"),
                    1, MaxStrLen(Description));
		** //> START REQUEST**
		IsHandled := false;
		OnOnBeforeSetCashFlowDate(CFWorksheetLine2,IsHandled);
                if not IsHandled then
		** //< END REQUEST**
		  SetCashFlowDate(CFWorksheetLine2, PurchHeader."Due Date");
                "Document No." := "Purchase Line"."Document No.";

    local procedure InsertCFLineForSalesLine()
    var
        SalesLine2: Record "Sales Line";
    begin
        SalesLine2 := "Sales Line";
        if Summarized and (SalesLine2.Next <> 0) and (SalesLine2."Sell-to Customer No." <> '') and
           (SalesLine2."Document No." = "Sales Line"."Document No.")
        then begin
            TotalAmt += CalculateLineAmountForSalesLine(SalesHeader, "Sales Line");
            MultiSalesLines := true;
        end else
            with CFWorksheetLine2 do begin
                Init();
                "Document Type" := "Document Type"::Invoice;
                "Document Date" := SalesHeader."Document Date";
                "Source Type" := "Source Type"::"Sales Orders";
                "Source No." := "Sales Line"."Document No.";
                "Source Line No." := "Sales Line"."Line No.";
                "Shortcut Dimension 1 Code" := SalesHeader."Shortcut Dimension 1 Code";
                "Shortcut Dimension 2 Code" := SalesHeader."Shortcut Dimension 2 Code";
                "Dimension Set ID" := SalesHeader."Dimension Set ID";
                "Cash Flow Account No." := CFSetup."Sales Order CF Account No.";
                Description :=
                  CopyStr(
                    StrSubstNo(
                      SalesDocumentDescriptionTxt,
                      SalesHeader."Document Type",
                      Format(SalesHeader."Order Date"),
                      SalesHeader."Sell-to Customer Name"),
                    1, MaxStrLen(Description));
		** //> START REQUEST**
		IsHandled := false;
		OnOnBeforeSetCashFlowDate(CFWorksheetLine2,IsHandled);
                if not IsHandled then
		** //< END REQUEST**
                SetCashFlowDate(CFWorksheetLine2, SalesHeader."Due Date");
                "Document No." := "Sales Line"."Document No.";

**//> START REQUEST**
    [IntegrationEvent(true, false)]
    local procedure OnOnBeforeSetCashFlowDate(var CashFlowWorksheetLine: Record "Cash Flow Worksheet Line"; var IsHandled: Boolean)
    begin
    end;
**//< END REQUEST**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
