### ISSUE TITLE
Change VAT Report Type fields from Option to Enum

### ISSUE THREAD

**Issue by LubomirUrx** [microsoft/ALAppExtensions#14015]
Could you change following fields to Enum "VAT Report Configuration"?

```
"VAT Report Config. Code" in Table "VAT Statement Report Line",
"VAT Report Type" in Table "VAT Report Archive".
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
