### ISSUE TITLE
Page 5780 "Whse. Pick Subform" - RegisterActivityYesNo - event-request

### ISSUE THREAD

**Issue by HHynynen** [microsoft/ALAppExtensions#14011]
New Integration Event needed for page "Whse. Pick Subform" procedure RegisterActivityYesNo():

- OnBeforeRegisterActivityYesNo(var Rec: Record "Warehouse Activity Line"; var IsHandled: Boolean)
- OnAfterRegisterActivityYesNo(var Rec: Record "Warehouse Activity Line"; var IsHandled: Boolean)

#event-request

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
