### ISSUE TITLE
Remove scope from GetBatchFromSession in codeunit 1380 "Batch Processing Mgt."

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#14013]
Request change of scope on procedure GetBatchFromSession in codeunit 1380 "Batch Processing Mgt." to allow use for Cloud development:

```
    [Scope('OnPrem')]
    procedure GetBatchFromSession(SourceRecordID: RecordID; SourceSessionID: Integer)
    ...
    end;
```

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
