### ISSUE TITLE
[Event Request] Table "Prod. Order Routing Line"

### ISSUE THREAD

**Issue by Easystep2** [microsoft/ALAppExtensions#14017]
Would like to request additional events when updating the bins from a Prod Order Routing Line:

procedure UpdateComponentsBin(FromTrigger: Option Insert,Modify,Delete)
    var
        TempProdOrderRtngLine: Record "Prod. Order Routing Line" temporary;
    begin
        IF SkipUpdateOfCompBinCodes THEN
          EXIT;

        IF NOT UpdateOfComponentsBinRequired(FromTrigger) THEN
          EXIT;

        PopulateNewRoutingLineSet(TempProdOrderRtngLine,FromTrigger);
        ProdOrderRouteMgt.UpdateComponentsBin(TempProdOrderRtngLine,FALSE);

        // << EWMSW113.00.01 Set Replenishment Bin
        OnAfterUpdateComponentsBin(TempProdOrderRtngLine,FALSE);
        // >>
end;

Add event-> local procedure OnAfterUpdateComponentsBin(var ProdOrderRoutingLine: Record "Prod. Order Routing Line";FromTrigger: Option Insert,Modify,Delete; IgnoreErrors: Boolean)
    begin
    end;

local procedure UpdateOfComponentsBinRequired(FromTrigger: Option Insert,Modify,Delete): Result: Boolean
    begin
        if ("No." = '') and (xRec."No." = "No.") then begin// bin codes are and were empty
            result := false;
            exit();
       end;

        case FromTrigger of
            FromTrigger::Insert, FromTrigger::Delete:
                result := ("Previous Operation No." = '') or ("Routing Link Code" <> '');
            FromTrigger::Modify:
                result := 
                  ((xRec."Previous Operation No." = '') and ("Previous Operation No." <> '')) or
                  ((xRec."Previous Operation No." <> '') and ("Previous Operation No." = '')) or
                  (xRec."Routing Link Code" <> "Routing Link Code") or
                  ((("Previous Operation No." = '') or ("Routing Link Code" <> '')) and
                   ((xRec."To-Production Bin Code" <> "To-Production Bin Code") or
                    (xRec."Open Shop Floor Bin Code" <> "Open Shop Floor Bin Code")));
        end;

        // << EWMSW113.00.01 Set update Replenishment Bin required
        OnAfterUpdateOfComponentsBinRequired(Rec, FromTrigger, Result);
       // >>
end;
       

Add event ->
local OnAfterUpdateOfComponentsBinRequired(ProdOrderRoutingLine: record "Prod. Order Routing Line";FromTrigger: Option Insert,Modify,Delete; var Result);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
