### ISSUE TITLE
[Event Request] Report 98 - "Date Compress General Ledger" - OnSummarizeEntryOnBeforeDeleteGLEntry

### ISSUE THREAD

**Issue by chliebich** [microsoft/ALAppExtensions#14016]
Please add a new integration event OnSummarizeEntryOnBeforeDeleteGLEntry in Report 98.

    local procedure SummarizeEntry(var NewGLEntry: Record "G/L Entry"; GLEntry: Record "G/L Entry")
    var
        GLItemLedgRelation: Record "G/L - Item Ledger Relation";
        GLEntryVatEntrylink: Record "G/L Entry - VAT Entry Link";
        GLEntryVatEntrylink2: Record "G/L Entry - VAT Entry Link";
    begin
        with GLEntry do begin
            NewGLEntry.Amount := NewGLEntry.Amount + Amount;
            NewGLEntry."VAT Amount" := NewGLEntry."VAT Amount" + "VAT Amount";
            NewGLEntry."Debit Amount" := NewGLEntry."Debit Amount" + "Debit Amount";
            NewGLEntry."Credit Amount" := NewGLEntry."Credit Amount" + "Credit Amount";
            NewGLEntry."Additional-Currency Amount" :=
              NewGLEntry."Additional-Currency Amount" + "Additional-Currency Amount";
            NewGLEntry."Add.-Currency Debit Amount" :=
              NewGLEntry."Add.-Currency Debit Amount" + "Add.-Currency Debit Amount";
            NewGLEntry."Add.-Currency Credit Amount" :=
              NewGLEntry."Add.-Currency Credit Amount" + "Add.-Currency Credit Amount";
            if RetainNo(FieldNo(Quantity)) then
                NewGLEntry.Quantity := NewGLEntry.Quantity + Quantity;

    +       OnSummarizeEntryOnBeforeDeleteGLEntry(NewGLEntry, GLEntry);

            Delete;

            GLItemLedgRelation.SetRange("G/L Entry No.", "Entry No.");
            GLItemLedgRelation.DeleteAll();

            GLEntryVatEntrylink.SetRange("G/L Entry No.", "Entry No.");
            if GLEntryVatEntrylink.FindSet then
                repeat
                    GLEntryVatEntrylink2 := GLEntryVatEntrylink;
                    GLEntryVatEntrylink2.Delete();
                    GLEntryVatEntrylink2."G/L Entry No." := NewGLEntry."Entry No.";
                    if GLEntryVatEntrylink2.Insert() then;
                until GLEntryVatEntrylink.Next() = 0;
            DateComprReg."No. Records Deleted" := DateComprReg."No. Records Deleted" + 1;
            Window.Update(4, DateComprReg."No. Records Deleted");
        end;
    end;

New integration event:

    [IntegrationEvent(false, false)]
    local procedure OnSummarizeEntryOnBeforeDeleteGLEntry(var NewGLEntry: Record "G/L Entry"; GLEntry: Record "G/L Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
