### ISSUE TITLE
Report 840 - OnBeforeInsertCFLineForJobPlanningLine - Event Request

### ISSUE THREAD

**Issue by Athon-dev** [microsoft/ALAppExtensions#14024]
REQUEST: Create Event on before Function InsertCFLineForJobPlanningLine inside OnAfterGetRecord trigger of "Job Planning Line" dataitem.
I would to insert new conditions to skip some rows.

SUGGEST:
dataitem("Job Planning Line"; "Job Planning Line")
{
    DataItemTableView = SORTING("Job No.", "Planning Date", "Document No.");

    trigger OnAfterGetRecord()
    begin
        Window.Update(2, JobsMsg);
        Window.Update(3, "Job No.");

        if not ("Line Type" in ["Line Type"::Billable, "Line Type"::"Both Budget and Billable"]) then
            exit;

        ** //> START REQUEST**
        OnBeforeInsertCFLineForJobPlanningLine("Job Planning Line");
        ** //< END REQUEST**
        InsertCFLineForJobPlanningLine();
    end;

    trigger OnPreDataItem()
    begin
        .....
    end;
}

//> START REQUEST
[IntegrationEvent(flase, false)]
local procedure OnBeforeInsertCFLineForJobPlanningLine(JobPlanningLine: Record "Job Planning Line")
begin
end;
//< END REQUEST

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
