### ISSUE TITLE
Change scope procedure LookupAvailable page 6510 "Item Tracking Lines"

### ISSUE THREAD

**Issue by NeleBollen** [microsoft/ALAppExtensions#14027]
Hello,

is it possible to change the scope of procedure LookupAvailable page 6510 "Item Tracking Lines"?

    -     local procedure LookupAvailable(LookupMode: Enum "Item Tracking Type")
    +    procedure LookupAvailable(LookupMode: Enum "Item Tracking Type")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
