### ISSUE TITLE
[Event Request] codeunit 1339 Cancel Posted Sales Cr. Memo - CreateCopyDocument OnBeforeSalesHeaderInsert

### ISSUE THREAD

**Issue by marcbosgraaf** [microsoft/ALAppExtensions#14043]
Could we get an event in C1339 in function CreateCopyDocument to be able to set some additional fields before actually inserting the new sales header. This would help a lot.

Event Declaration:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesHeaderInsert(var SalesHeader: Record "Sales Header"; var SalesCrMemoHeader: Record "Sales Cr.Memo Header")
    begin
    end;

Event Call:

    local procedure CreateCopyDocument(var SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var SalesHeader: Record "Sales Header")
    var
        CopyDocMgt: Codeunit "Copy Document Mgt.";
    begin
        Clear(SalesHeader);
        SalesHeader."No." := '';
        SalesHeader."Document Type" := SalesHeader."Document Type"::Invoice;

        // new event >>
        OnBeforeSalesHeaderInsert(SalesHeader,SalesCrMemoHeader)
        // new event <<

        SalesHeader.Insert(true);
        CopyDocMgt.SetPropertiesForInvoiceCorrection(false);
        CopyDocMgt.CopySalesDocForCrMemoCancelling(SalesCrMemoHeader."No.", SalesHeader);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
