### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt".OnBeforeRecalculateAndApplySalesLine

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#14045]
Please set "var" before parameters "ExactCostRevMandatory", "RecalculateAmount" and "CreateToHeader"

Also set "var" before parameter "RecalculateAmount" in function "RecalculateAndApplySalesLine"
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeRecalculateAndApplySalesLine(var ToSalesHeader: Record "Sales Header"; var ToSalesLine: Record "Sales Line"; var FromSalesLine: Record "Sales Line"; Currency: Record Currency; var ExactCostRevMandatory: Boolean; var RecalculateAmount: Boolean; var CreateToHeader: Boolean; MoveNegLines: Boolean; var IsHandled: Boolean)
    begin
    end
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
