### ISSUE TITLE
Blob in Report Column

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#14054]
@JesperSchulz 
unfortunately we need to re-open this case. for any PerTenantExtensions we cannot use our own TempBlob-table, as intended because of the .NET streaming methods. the Microsoft Base App TempBlob-Table is working for now, but is marked as obsolete. 

please provide a solution to use Blob-content directly in a report column as soon as possible.

`
column(BlobImage; TempBlob.Blob)
            {
            }`
`column(ShowBlobImage; NOT TempBlob.Blob.HasValue())
            {
            }
`

_Originally posted by @JulianTillmann in https://github.com/microsoft/ALAppExtensions/issues/6812#issuecomment-860729700_

**Comment by GiorgosPa** [comment]
@JulianTillmann you should not require any .NET streaming methods, where exactly is using a different table lacking? What are you trying to achieve with the .NET methods?

**Comment by JulianTillmann** [comment]
This is regarding my case https://github.com/microsoft/ALAppExtensions/issues/6812 but there were no responses on that thread, so I reposted. 

We need to use a TempBlob directly in a Report column. This is not possible with the TempBlob Codeunit, only with the table. Since the table is marked as obsolete @JesperSchulz suggested to make a copy of the TempBlob table inside our own extension. 

This works OnPrem, but there are .NET and streaming methods for using importing and exporting the blob content, which don't work as a Cloud extension. 

So we are back to the original request: please make the SystemApplication TempBlob funcitonality usable for Reports.

**Comment by GiorgosPa** [comment]
@julianTilmann You should be able to to load any binary content to any Blob without using any .NET methods. I would need a concrete example of what it is blocking in order to help you. I am very confident you can import your data without using these methods. Here is an example of a Blob in a report

```
report 50100 MyReport
{
    UsageCategory = Administration;
    ApplicationArea = All;
    
    dataset
    {
        dataitem(DataItemName; Attachment)
        {
            column(Blobfield; "Attachment File")
            {
                
            }
        }
    }
}
```
With the proper layout this looks like this
![blob in report](https://user-images.githubusercontent.com/4313776/131316821-83ffb9d9-971b-4a91-9b40-b0717eb2e42d.PNG)

**Comment by JulianTillmann** [comment]
we don't have a blobfield in a fixed table but instead want to have IntegrationEvents were extensions can add their own blob content. so we need  to have a event parameter which we can fill, the easiest way would be the TempBlob table but it's marked as obsolete. 

Alternatively it would work if there was a way to use the TempBlob Codeunit content somehow in a report column

**Comment by GiorgosPa** [comment]
Two option here

1. Define your own table with a blob field and pass that on the event parameter
2. Pass Temp Blob Codeunit in the event fill it the way you need and afterwards extract the Blob Content on your own table, not the best option as you will end up copying the blob, but it will look like this

```
OnFillTheBlob(TempBlobCodeunit);
RecordRef.GetTable(TableWithBlobField);
TempBlob.ToRecordRef(RecordRef, TableWithBlobField.FieldNo(Blob));
RecordRef.SetTable(TableWithBlobField);
...

column(BlobImage; TableWithBlobField.Blob) { }
column(ShowBlobImage; NOT TableWithBlobField.Blob.HasValue()) { }
```

**Comment by GiorgosPa** [comment]
I hope the following example help you achieve the desired result. 
I have created a temporary table with a blob field. I populate the table with an event on the OnInitReport trigger.
The subscriber then downloads this [image](https://th.bing.com/th/id/OIP.g77_8CCvqg2ihD9gLEq8nAHaGj?w=211&h=187&c=7&r=0&o=5&pid=1.7) and saves it in the Blob field of the Record. 
With the appropriate layout the image is then displayed on the report.

![image](https://user-images.githubusercontent.com/4313776/131337869-2206dd94-50b6-49f7-8b8e-efc3945ae85f.png)

```
report 50100 MyReport
{
    UsageCategory = Administration;
    ApplicationArea = All;
    
    dataset
    {
        dataitem(Record; Customer)
        {
            column(Blobfield; MyTable.Blob) {}
        }
    }

    trigger OnInitReport()
    begin
        OnFillBlobField(MyTable);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnFillBlobField(var MyTable: Record MyTable)
    begin
    end;
        
    var
        MyTable: Record MyTable temporary;
}

table 50100 MyTable
{
    TableType = Temporary;

    fields
    {
        field(1; ID; Integer) {}
        field(2; Blob; Blob) {}
    }
}

codeunit 50100 MyCodeunit
{
    [EventSubscriber(ObjectType::Report, Report::MyReport, 'OnFillBlobField', '', true, true)]
    local procedure MyProcedure(var MyTable: Record MyTable)
    var
        Client: HttpClient;
        Response: HttpResponseMessage;
        Instream: Instream;
        OutStream: OutStream;
    begin
        Client.Get('https://th.bing.com/th/id/OIP.g77_8CCvqg2ihD9gLEq8nAHaGj?w=211&h=187&c=7&r=0&o=5&pid=1.7', Response);
        Response.Content.ReadAs(Instream);
        MyTable.Blob.CreateOutStream(OutStream);
        CopyStream(OutStream, Instream);
    end;
}
```

**Comment by JesperSchulz** [comment]
@JulianTillmann, if this doesn't work for you, please reopen with a mention of me, and we'll take another look. But this should do the trick! Best of luck :-)
