### ISSUE TITLE
[Event Request] codeunit 7307 "Whse.-Activity-Register" OnCodeOnBeforeReadActivityLineGrouped

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#14055]
.
            .
            .
            // breakbulk first to provide quantity for pick lines in smaller UoM
            WhseActivLine.SetFilter("Breakbulk No.", '<>0');
            RegisterWhseActivityLines(WhseActivLine, TempWhseActivLineToReserve, TempWhseActivityLineGrouped);

            WhseActivLine.SetRange("Breakbulk No.", 0);
            RegisterWhseActivityLines(WhseActivLine, TempWhseActivLineToReserve, TempWhseActivityLineGrouped);
            WhseActivLine.SetRange("Breakbulk No.");

>>>OnCodeOnBeforeReadActivityLineGrouped(WhseActivHeader,WhseActivLine,RegisteredWhseActivHeader)

            TempWhseActivityLineGrouped.Reset();
            if TempWhseActivityLineGrouped.FindSet then
                repeat
                    if Type <> Type::Movement then
                        UpdateWhseSourceDocLine(TempWhseActivityLineGrouped);
                    UpdateWhseDocHeader(TempWhseActivityLineGrouped);
                    TempWhseActivityLineGrouped.DeleteBinContent(TempWhseActivityLineGrouped."Action Type"::Take);
                until TempWhseActivityLineGrouped.Next() = 0;
            .
            .
            .

>>>[IntegrationEvent(false,false)]
>>>local procedure OnCodeOnBeforeReadActivityLineGrouped(var WhseActivHeader: Record "Warehouse Activity Header"; var WhseActivLine: Record "Warehouse Activity Line"; var RegisteredWhseActivityHdr: Record "Registered Whse. Activity Hdr.")
>>>begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
