### ISSUE TITLE
[Event Request] codeunit 1247 "Process Gen. Journal  Lines" - OnAfterImportBankStatement

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#14077]
New Event in the codeunit 1247 "Process Gen. Journal  Lines", Function ImportBankStatement:
OnAfterImportBankStatement(var GenJournalLine: Record "Gen. Journal Line";GenJournalLineTemplate: Record "Gen. Journal Line")

**Comment by Stepanenko-Vadim** [comment]
This has been implemented already, closing the issue. The tag 'ships-in-future-update' is for housekeeping.
