### ISSUE TITLE
Testpage ControlAddin

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#14072]
Hi guys, 

is there a way to use a usercontrol (control-addin) on a test page somehow? 

Are there any ideas on how to test those?

Thanks & Best Regards 
J

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas

**Comment by db-bc** [comment]
For questions not yet identified as being bugs, [Yammer](https://www.yammer.com/dynamicsnavdev) could be better.

**Comment by db-bc** [comment]
It;s now posted there: https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1357549857865728
