### ISSUE TITLE
[Event Paramete Request] codeunit 1247 "Process Gen. Journal Lines" - OnBeforeUpdateGenJnlLines

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#14078]
current:
OnBeforeUpdateGenJnlLines(var GenJournalLineTemplate: Record "Gen. Journal Line")
desired:
OnBeforeUpdateGenJnlLines(var GenJournalLineTemplate: Record "Gen. Journal Line"; var IsHandled: Boolean)
if IsHandled then
    exit;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
