### ISSUE TITLE
typo / non-`var` parameter `varTempExcelBuffer` of `OnAfterExportData()` in `codeunit 424 "Export Analysis View"`

### ISSUE THREAD

**Issue by db-bc** [microsoft/ALAppExtensions#14073]
from Yammer: https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1354729182109696

Instead of `var TempExcelBuffer`, you are passing a non-`var` instance named `varTempExcelBuffer`, and this seems to break subscribers' attempts to use the real Excel Buffer instance, e.g. to `SaveFromStream()` via the global variable `FileNameServer`.

> there is a typo here, so that instead of passing to subscribers a var TempExcelBuffer, MS are passing a non-var record named varTempExcelBuffer... And I think that maybe a non-var record will lose values of global variables, etc. - including the FileNameServer that I mentioned above.

The fix is to add `var` to the parameter. Hopefully that can be done without breaking any existing subscribers? I guess it has to keep the same, typo'd name though...

wrong:

    [IntegrationEvent(false, false)]
    local procedure OnAfterExportData(varTempExcelBuffer: Record "Excel Buffer" temporary; var AnalysisViewEntry: Record "Analysis View Entry")
    begin
    end;

right (I presume!):

    [IntegrationEvent(false, false)]
    local procedure OnAfterExportData(var varTempExcelBuffer: Record "Excel Buffer" temporary; var AnalysisViewEntry: Record "Analysis View Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Fixed. Made variable var. Kept the name though, to avoid introduction of breaking change. I guess we can live with that variable name...

**Comment by db-bc** [comment]
Thanks as always @JesperSchulz !

**Comment by JesperSchulz** [comment]
Will backport to 18.5 too.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
