### ISSUE TITLE
[Request For External] codeunit 22 "Item Jnl.-Post Line".PrepareItem

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#14085]
Please change the scope of PrepareItem function from local to public.
`procedure PrepareItem(...)`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
