### ISSUE TITLE
[Event Request] Codeunit 7041 (Price Asset - Item) - OnBeforeIsLookupOK

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#14092]
Dear Team,

we need a new publisher in codeunit 7041 (Price Asset - Item) "OnBeforeIsLookupOK" to add filters to the item Record.

    procedure IsLookupOK(var PriceAsset: Record "Price Asset"): Boolean
    var
        xPriceAsset: Record "Price Asset";
    begin
        OnBeforeIsLookupOK(PriceAsset,Item);  //NEW EVENT
        xPriceAsset := PriceAsset;
        if Item.Get(xPriceAsset."Asset No.") then;
        if Page.RunModal(Page::"Item List", Item) = ACTION::LookupOK then begin
            xPriceAsset.Validate("Asset No.", Item."No.");
            PriceAsset := xPriceAsset;
            exit(true);
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsLookupOK(priceAsset: Record "Price Asset"; var item: Record Item)
    begin
    end;

Thanks in advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
