### ISSUE TITLE
[Event Request] report 7317 - "Whse. - Shipment" - WarehouseShipmentHeaderOnAfterOnAfterGetRecord

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#14090]
Hi AL-Team,
can you please add the following Publisher in trigger OnAfterGetRecord with "includeSender"?

```
trigger OnAfterGetRecord()
            begin
                GetLocation("Location Code");
                // NEW >>>>
                WarehouseShipmentHeaderOnAfterOnAfterGetRecord("Warehouse Shipment Header");
                // NEW <<<<
            end;

[IntegrationEvent(true, false)]
    local procedure WarehouseShipmentHeaderOnAfterOnAfterGetRecord(var WarehouseShipmentHeader: Record "Warehouse Shipment Header");
    begin
    end;
```

**Comment by db-bc** [comment]
What is it for, and might that be doable/easier using the standard platform report-extension event `OnAfterAfterGetRecord()` instead?

**Comment by MattiLE** [comment]
How can I use the OnAfterGetRecord trigger in ReportExt?

**Comment by db-bc** [comment]
Make a new `reportextension` object: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-ext-object

and then inside the `dataset` element, `modify` the `dataitem` of interest, and add your `trigger`(s) there:

```al
modify(SomeDataItem)
{
    trigger OnAfterAfterGetRecord()
    begin
        DoSomethingWith(TheDataItemRecVar);
    end;
}
```

and so on for the other triggers documented here:

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/reportextensiondatasetmodify/devenv-onafteraftergetrecord-reportextensiondatasetmodify-trigger

**Comment by MattiLE** [comment]
Works well. Thank you :)

**Comment by db-bc** [comment]
I filed [a documentation bug](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/2010) because it is not mentioned anywhere obvious that you can do these things, so it waste's everyone's time:

https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/2010
