### ISSUE TITLE
[Function exposure] Table 37 Sales Line - Function InitHeaderDefaults

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#14091]
Pleas make the function InitHeaderDefaults in the Table 37 Sales Line externally available.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
