### ISSUE TITLE
Codeunit 12 Function FinishPosting

### ISSUE THREAD

**Issue by ThomasBrendel** [Microsoft/ALAppExtensions#141]
For extracting our own code out of this function, we need this function with parameter.

FinishPosting(GenJnlLine : Record "Gen. Journal Line") IsTransactionConsistent : Boolean

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!

**Comment by darjoo** [comment]
Hi, we've gone ahead with your request. We usually include these types of changes in the next minor release, so look for it there.
