### ISSUE TITLE
Table 36 Sales Header OnValidate Salesperson Code

### ISSUE THREAD

**Issue by ligoendeavor** [microsoft/ALAppExtensions#14104]
Event request in trigger OnValidate on field "Salesperson Code":
trigger OnValidate()
            var
                ApprovalEntry: Record "Approval Entry";
                EnumAssignmentMgt: Codeunit "Enum Assignment Management";
#if not CLEAN18
                CustomerTemplMgt: Codeunit "Customer Templ. Mgt.";
#endif
                IsHandled: Boolean;
            begin
                ValidateSalesPersonOnSalesHeader(Rec, false, false);

                ApprovalEntry.SetRange("Table ID", DATABASE::"Sales Header");
                ApprovalEntry.SetRange("Document Type", EnumAssignmentMgt.GetSalesApprovalDocumentType("Document Type"));
                ApprovalEntry.SetRange("Document No.", "No.");
                ApprovalEntry.SetFilter(Status, '%1|%2', ApprovalEntry.Status::Created, ApprovalEntry.Status::Open);
                if not ApprovalEntry.IsEmpty() then
                    Error(Text053, FieldCaption("Salesperson Code"));

                // New event
                IsHandled := false;
                OnBeforeCreateDimSalesperson(Rec, IsHandled);
                if IsHandled then
                    exit;
                // End new event
#if not CLEAN18
                if not CustomerTemplMgt.IsEnabled() then
                    CreateDim(
                      DATABASE::"Salesperson/Purchaser", "Salesperson Code",
                      DATABASE::Customer, "Bill-to Customer No.",
                      DATABASE::Campaign, "Campaign No.",
                      DATABASE::"Responsibility Center", "Responsibility Center",
                      DATABASE::"Customer Template", "Bill-to Customer Template Code")
                else
#endif
                    CreateDim(
                      DATABASE::"Salesperson/Purchaser", "Salesperson Code",
                      DATABASE::Customer, "Bill-to Customer No.",
                      DATABASE::Campaign, "Campaign No.",
                      DATABASE::"Responsibility Center", "Responsibility Center",
                      DATABASE::"Customer Templ.", "Bill-to Customer Templ. Code");
            end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
