### ISSUE TITLE
[Event Change] Codeunit 408 - DimensionManagement - OnBeforeCheckDimValueComb

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#14106]
Hi AL-Team,
can you please pass the parameter DimensionValueCombination by var?

```
    [IntegrationEvent(false, false)]
    // NEW >>>>
    // local procedure OnBeforeCheckDimValueComb(DimensionValueCombination: Record "Dimension Value Combination")
    local procedure OnBeforeCheckDimValueComb(var DimensionValueCombination: Record "Dimension Value Combination")
    // NEW <<<<    
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
