### ISSUE TITLE
[Event Change] Report 7310 - Calculate Bins - OnLevel2OnAfterGetRecordOnBeforeBinCreateWksh

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#14107]
Hi AL-Team,
can you please add set the IncludeSender parameter to Publisher OnLevel2OnAfterGetRecordOnBeforeBinCreateWksh?

```
// NEW >>>>
    // [IntegrationEvent(false, false)]
    [IntegrationEvent(true, false)]
    // NEW <<<<
    local procedure OnLevel2OnAfterGetRecordOnBeforeBinCreateWksh(var Level: Code[20])
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
