### ISSUE TITLE
[Event Change] Codeunit 408 - DimensionManagement - OnBeforeCheckDimComb

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#14105]
Hi AL-Team,
can you please pass the parameter DimensionCombination by var?

```
    [IntegrationEvent(false, false)]
// NEW >>>>
    // local procedure OnBeforeCheckDimComb(DimensionCombination: Record "Dimension Combination")
    local procedure OnBeforeCheckDimComb(var DimensionCombination: Record "Dimension Combination")
// New <<<<    
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
