### ISSUE TITLE
Table 372 "Payment Buffer" - Functions CopyFieldsFromVendorLedgerEntry and CopyFieldsToGenJournalLine

### ISSUE THREAD

**Issue by domingosbarreto** [microsoft/ALAppExtensions#14116]
Hi,

We are developing an extension and we need to call the functions CopyFieldsFromVendorLedgerEntry and CopyFieldsToGenJournalLine from table 372 "Payment Buffer".

At this moment, both functions have Scope OnPrem, so I'm getting the error that these functions cannot be used for 'Cloud' development.

Is it possible to expose these functions?

Thank you.
BR,
Domingos

**Comment by AlexanderYakunin** [comment]
Yes, this is already fixed for BC 19
