### ISSUE TITLE
IndentationControls property incorrect display for 2+ fields specified

### ISSUE THREAD

**Issue by PaulFurlet** [microsoft/ALAppExtensions#14117]
If you specify more than one field in IndentationControls property, they become concatenated into one semi-multilevel control with glitches
Example code:
```
table 50100 DemoIndentation
{
    fields
    {
        field(1; entryNo; Integer) { Caption = 'Entry No.'; }
        field(2; Level; Integer) { Caption = 'Level'; }
        field(3; Description; Text[100]) { Caption = 'Description'; }
        field(4; Text01; Text[30]) { Caption = 'Text01'; }
    }
    keys { key(PK; entryNo) { Clustered = true; } }
}

page 50100 DemoIndentation2
{
    UsageCategory = None;
    DelayedInsert = true;
    PageType = List;
    AutoSplitKey = true;
    SourceTable = DemoIndentation;
    layout
    {
        area(Content)
        {
            repeater(entries)
            {
                IndentationColumn = Rec.Level;
                IndentationControls = Description, Text01;
                field(Level; Rec.Level) { ApplicationArea = All; }
                field(Description; Rec.Description) { ApplicationArea = All; }
                field(Text01; Rec.Text01) { ApplicationArea = All; }
            }
        }
    }
}
```
Actual result:
![image](https://user-images.githubusercontent.com/17279234/131166855-8dd51e93-fdcc-4554-9ef5-a7f56c369df7.png)

Expected result (edited image!):
![image](https://user-images.githubusercontent.com/17279234/131167987-28291ac9-d46f-4305-a1c5-8067d906e2ba.png)

**Comment by db-bc** [comment]
documented:

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-indentationcontrols-property

> Web client supports indentation on one column only. You can specify more than one column, however, in the UI, the columns may not appear as expected.

Anyway, seems off-topic for extensibility.

**Comment by PaulFurlet** [comment]
Thanks.
Well, it is something that would be nice to see fixed, I suppose.
Where else to write about this?

**Comment by db-bc** [comment]
I'd guess that MS will say it is best submitted as an Idea: https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central I couldn't see any for this one already.

**Comment by AlexanderYakunin** [comment]
Please submit an idea. Closing this one.
