### ISSUE TITLE
Codeunit DimensionCaptionClassMgt

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#14113]
In codeunit dimensioncaptionclassmgt there is event subscriber "ResolveCaptionClass"
the code:
 if CaptionArea = '1' then begin
            Caption := DimCaptionClassTranslate(Language, CaptionExpr);
            Resolved := true;
        end;

in every case the resolved is set to true. that is not logic.
if i want to create for ex. a 9th dimension, then the DimCaptionClassTranslate function will return an empty string, because the captionclass i would use 1,1,9 wil not be resolved by that function.
so the caption wil be an empty string but still resolved is true.
since i have no impact on the order of firing event subscribers, my subscriber could be after the standard code and then i may not look at "resolved" because it is not correct.
that makes no sense. resolved should only be true if it is indeed resolved.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
