### ISSUE TITLE
[Event Request] 1250 "Match General Journal Lines" 

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#14118]
New Event desired in 1250 "Match General Journal Lines" jut before the function FindMatchingCustEntries

`OnBeforeFindMatchingCustEntries(var TempBankStatementMatchingBuffer: Record "Bank Statement Matching Buffer" temporary; var TempGenJournalLine: Record "Gen. Journal Line" temporary)`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
