### ISSUE TITLE
Codeunit 442 "Sales-Post Prepayments" wrong "Line No" on Sales Invoice Lines

### ISSUE THREAD

**Issue by Stef1974** [microsoft/ALAppExtensions#14112]
Line No. is being populated incorrectly growing exponentially when prepayments are not compressed:

//..
if TempPrepmtInvLineBuffer."Line No." <> 0 then
  LineNo := PrevLineNo + TempPrepmtInvLineBuffer."Line No."
else
  LineNo := PrevLineNo + 10000;
//...

It shouldn't add "PrevLineNo." to the existing Line No. on the first part of the condition.

This causes an order with 600 lines or more to crash when posting a prepayment Invoice:

![2021-08-27 11_05_00-Window](https://user-images.githubusercontent.com/50665405/131110705-2446892d-670b-4d05-b2c2-0dcb3dbb4c3a.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
