### ISSUE TITLE
[Request for Protected] Page 5805 "Item Charge Assignment (Purch)"

### ISSUE THREAD

**Issue by omerfaruknav** [microsoft/ALAppExtensions#14119]
Can the following variables become Protected:

PurchLine2
PurchRcptLine

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
