### ISSUE TITLE
[Scope] table 55 "Invoice Posting Buffer".PadField

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#14122]
Please change the scope of PadField procedure to public.
`procedure PadField(TextField: Text; MaxLength: Integer): Text`

**Comment by db-bc** [comment]
Why? `Invoice Post Buffer` is due to be replaced with interfaces, IIRC, Can't an existing function like `Text.Pad(Str|Left|Right)` or `StringConversionManagement.GetPaddedString` suffice?

I checked W1 source and no such table exists, so I guess this is some localisation, but same questions apply.

**Comment by RadoArvay** [comment]
> 
> 
> Why? `Invoice Post Buffer` is due to be replaced with interfaces, IIRC, Can't an existing function like `Text.Pad(Str|Left|Right)` or `StringConversionManagement.GetPaddedString` suffice?
> 
> I checked W1 source and no such table exists, so I guess this is some localisation, but same questions apply.

When I mention "scope change", probably that procedure/table should exist, don't you think? ;-)
And I am writing about `Invoice Posting Buffer`, not that old one. This new table is a part of replacement functionality with interfaces.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
