### ISSUE TITLE
[Enum Request] - WarehouseActivityLine.Table - field "Activity Type"

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#14121]
We would like to have the field "Activity Type" in table "Warehouse Activity Line" as Enum.

**Comment by AlexanderYakunin** [comment]
Already done in BC 19

        field(1; "Activity Type"; Enum "Warehouse Activity Type")
        {
            Caption = 'Activity Type';
            Editable = false;
        }
