### ISSUE TITLE
[Event Parameter Request] codeunit 90 "Purch.-Post".PostItemTrackingItemChargePerOrder - OnBeforePostItemTrackingItemChargePerOrder

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#14132]
Please add a new parameter `ItemJnlLine2` to the event `OnBeforePostItemTrackingItemChargePerOrder`.
And - I think it is a mistake - replace a variable `TempTrackingSpecificationInv` with `TempTrackingSpecificationChargeAssmt` in a call.
```
local procedure PostItemTrackingItemChargePerOrder(...)
...
begin
    IsHandled := false;
    OnBeforePostItemTrackingItemChargePerOrder(ItemJnlLine2, TempTrackingSpecificationChargeAssmt, IsHandled);
    if IsHandled then
        exit;

    with TempTrackingSpecificationChargeAssmt do begin
...
end;

[IntegrationEvent(false, false)]
local procedure OnBeforePostItemTrackingItemChargePerOrder(var ItemJnlLine2: Record "Item Journal Line"; var TempTrackingSpecificationChargeAssmt: Record "Tracking Specification" temporary; var IsHandled: Boolean)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
