### ISSUE TITLE
Change Request: "Source Type" and "Source No." on Page 20 "General Ledger Entries"

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#14133]
The fields "Source Type" and "Source No." should be added (maybe Visible = false) by default on page 20 "General Ledger Entries". This is a field that is commonly used for tracing and we would like to have it baseline, to avoid adding it by our apps and risk future collisions. Thanks.

**Comment by AlexanderYakunin** [comment]
These fields already available in page 20 General Ledger Entries, please recheck in 19.0
