### ISSUE TITLE
[Function-Expose] CU 2310 O365 Sales Invoice Mgmt - GetPaymentInstructionsFromPostedInvoice

### ISSUE THREAD

**Issue by plagijat** [Microsoft/ALAppExtensions#1414]
Can you please expose **GetPaymentInstructionsFromPostedInvoice** from CU 2310 **O365 Sales Invoice Mgmt**?
This function is used in standard Sales reports and we use similar customized reports that we want to use this function in.

Thanks,
Zoran

**Comment by IhorHandziuk** [comment]
Thank you for your request @plagijat 
Currently we don't want to expose more functions from "Invoicing" as there can be changes to them in the future.
As for the requested function: please, consider having this function in your own extension

**Comment by lvanvugt** [comment]
> Currently we don't want to expose more functions from "Invoicing" as there can be changes to them in the future.

Doesn't this apply to all functionality? And if that happens it's the responsibility of the one who's calling to function. IMHO it's worse to not allow us to use it (and let everybody do their replication).
