### ISSUE TITLE
page 11303 "Manual VAT Correction List" - function SetCorrStatementLineNo

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#14143]
in page 11303 "Manual VAT Correction List" there is a function "SetCorrStatementLineNo"
this has the scope "OnPrem"
why is this not available in saas?
can this be opened up for saas?

we are in the process of migrating out onprem solution to saas and would need this function.

is there somewhere documentation on why functions are in scope "onprem"? (as i will encounter othes)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
