### ISSUE TITLE
[Request-For-External] Page 5414 "Item Availability by Variant" - PeriodType

### ISSUE THREAD

**Issue by percova** [microsoft/ALAppExtensions#14140]
Hi, could you please change the global **PeriodType** variable's protection level on page 5414 (**Item Availability by Variant**) to a **protected**?

```AL
    protected var
        PeriodType: Option Day,Week,Month,Quarter,Year,"Accounting Period";
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
