### ISSUE TITLE
[Request for external] - PostSalesOrder - Sales Order

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#14141]
Hi,

The new PostSalesOrder procedure is still local in BC 18.3, when will it become protected?

Ref #12609

![image](https://user-images.githubusercontent.com/46031720/131350074-813fd2cb-da6c-4b8a-9e87-a419a43227c4.png)

**Comment by RadoArvay** [comment]
FYI: It is already `protected` in 19.0.
