### ISSUE TITLE
Report 2098156 "CFL File SEPA Payments"

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#14157]
we are in the process of migrating our onprem solution to saas.
we encouter following issue:
we have changes in the report 2098156 "CFL File SEPA Payments" . so we have created a copy of the standard report to do our changes in.
this worked fine onprem, but for saas we can not use the dotnet to create the xmldocument.
i do not understand why the base app can use the dotnets for xml creating and we can not.
why do i need to recode the entire report to create a xml document without the use of dotnet in my extension if the baseapp can use these dotnets?

**Comment by db-bc** [comment]
SaaS app devs can't run stuff on the server, including .Net functions, because that's Microsoft's server. The base app can because it runs on Microsoft's server and they trust their own app to run code thereon...

**Comment by db-bc** [comment]
> we have changes in the report 2098156 "CFL File SEPA Payments" . so we have created a copy of the standard report to do our changes in.

Can you use the new `reportextension` object now, instead? That way, you don't have the hassle or maintenance burden/risk of copying and pasting, and you can let the base app do .Net stuff

**Comment by bartpattijn** [comment]
no, report extension has not sufficient capabilities to make the necessary adjustments i need to do. so i am forced to recode the entire report.
it would be a lot easier if MS was to play by the same rules as we do. so then the standard report would have been altered to make use of the native xml elements in al.
now for some "simple" modifications i need a lot of time.

**Comment by db-bc** [comment]
Just to check, does that include the updated report extension capabilities from 18.1, where you can add `OnBefore/After` triggers in `dataitem`s, etc.? They are not documented well or at all, so you could easily have missed them: https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/2010

**Comment by bartpattijn** [comment]
yes, even with those i can not do the necessary changes. 
even asking for events is not an option because you are making the xml with donet and i can not use that.
there could be no events with these dotnet parameters.
that's why you should play by the same rules as we do. the application can never be easily extendable if you are using stuff we can not.

**Comment by db-bc** [comment]
There's no need for the blaming tone... I don't work for Microsoft.
