### ISSUE TITLE
[Event Request] Codeunit 5005353/5005357 OnBeforePhysInvtOrderLineModify

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#1415]
we Need the same Event trigger from Codeunit 5005351 in codeunits 5005353 and 5005357:

Codeunit 5005353:
Code()
...
        PhysInvtOrderLine."No. Finished Rec.-Lines" :=
          PhysInvtOrderLine."No. Finished Rec.-Lines" - 1;
        PhysInvtOrderLine."In Recording Lines" := PhysInvtOrderLine."No. Finished Rec.-Lines" <> 0;
        OnBeforePhysInvtOrderLineModify(VAR PhysInvtOrderLine,PhysInvtRecordingLine);  <-- New Event trigger
        PhysInvtOrderLine.MODIFY;

Codeunit 5005357:
[External] Code()
...
        PhysInvtOrderLine."Quantity (Base)" := 0;
        PhysInvtOrderLine."Entry Type" := PhysInvtOrderLine."Entry Type"::" ";
        OnBeforePhysInvtOrderLineModify(VAR PhysInvtOrderLine);  <-- New Event trigger
        PhysInvtOrderLine.MODIFY;

**Comment by AlexanderYakunin** [comment]
Is this for OnPrem customer?

**Comment by GuntherGebauer** [comment]
this is for our ISV solution necessary because we handle a second quantity type on all entries

**Comment by AlexanderYakunin** [comment]
You will need to update your solution as this DE module have been merged into W1 for Spring 2019 release  in the range 5875..5890. We can add new events here.

**Comment by GuntherGebauer** [comment]
yes, we will do that as soon as the spring release is officially released

**Comment by AlexanderYakunin** [comment]
No update, seems not needed anymore.
