### ISSUE TITLE
extending document sending profiles  issue

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#14151]
We are in the process of migrating our onprem solution to saas. we encounter an issue with extending the document sending profile.
we have a custom "electronic document format", for which we have created a codeunit to create the file.
in the standard table "electronic document format" there is this code in the function "sendelectronically":
 RecordExportBuffer.SetRange(ID, StartID, EndID);
        if RecordExportBuffer.FindSet then
            repeat
                ErrorMessage.SetContext(RecordExportBuffer);
                ErrorMessage.ClearLog;

                CODEUNIT.Run("Codeunit ID", RecordExportBuffer);

                TempErrorMessage.CopyFromContext(RecordExportBuffer);
                ErrorMessage.ClearLog; // Clean up

                if RecordExportBuffer.ServerFilePath = '' then
                    IsMissingServerFile := true;
            until RecordExportBuffer.Next() = 0;

this runs our codeunit. But we need to put the file (xml file in our case) on the server and fill the field "serverfilepath",otherwise this errors on missingserverfile.
but in saas we can not create a server temp file (filemgt.servertempfile not accessable)
is there a way to do this?
or should the standard code be refactored so that it works with a blob field for example instead of a server file?

**Comment by bartpattijn** [comment]
is there any update on when there would be a solution for this?

**Comment by StanPesotskiy** [comment]
The refactoring is done in the app build 20.0.35635.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
