### ISSUE TITLE
table 11303 VAT Summary Buffer

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#14156]
we are in the process of migrating our onprem solution to saas.
we encouter issues with all procedures in the table "VAT Summary Buffer" that are scope 'OnPrem' and therefor not accesable in saas.
why are these not available in saas?
i see noting special in these functions that would cause problems in saas in my opinion.
can these procedures be opened up for saas?

i have simular issues in following objects: 
codeunit 11300 VATLogicalTests
codeunit 11308 "INTERVAT Helper"
table 2000001 "Payment Journal Line"
codeunit 408 DimensionManagement
codeunit 2000001 CheckPaymJnlLine
page 371 "Bank Account List"
page 2000001 "EB Payment Journal"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by bartpattijn** [comment]
as extension to this, could the procedure UpdateStatementAmounts on page 11300 also be opened up for cloud?
it has been marked with scope on prem in bc20, but i do not see any reason why, instead of it being in the be localisation and as previous requested objects were also in the be localisation.
