### ISSUE TITLE
[Event Request] New event OnBeforeBankAccountModify in OnRun trigger of codeunit 10120 "Bank Rec.-Post"

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#14160]
Hello.
Need event OnBeforeBankAccountModify(var BankAccount: Record "Bank Account"; BankRecHeader: Record "Bank Rec. Header"; var PostedBankRecHeader: Record "Posted Bank Rec. Header") in OnRun trigger of codeunit 10120 "Bank Rec.-Post".

Version of AL Language 7.4.496506
US Business Central 18.3 (Platform 18.0.27224.27469 + Application 18.3.27240.27480)

Trigger:

  
    trigger OnRun()
        begin
            ClearAll;
    
            BankRecHeader := Rec;
            with BankRecHeader do begin
                TestField("Statement Date");
                TestField("Statement No.");
                TestField("Bank Account No.");
    
                CalculateBalance;
                if ("G/L Balance" +
                    ("Positive Adjustments" - "Negative Bal. Adjustments") +
                    ("Negative Adjustments" - "Positive Bal. Adjustments")) -
                   (("Statement Balance" + "Outstanding Deposits") - "Outstanding Checks") <> 0
                then
                    Error(Text007);
    
                CalcFields("Total Adjustments", "Total Balanced Adjustments");
                if ("Total Adjustments" - "Total Balanced Adjustments") <> 0 then
                    Error(Text008);
    
                Window.Open(Text001 +
                  Text002 +
                  Text003 +
                  Text004 +
                  Text005 +
                  Text006);
    
                Window.Update(1, "Bank Account No.");
                Window.Update(2, "Statement No.");
    
                GLSetup.Get();
    
                BankRecLine.LockTable();
                PostedBankRecLine.LockTable();
    
                SourceCodeSetup.Get();
    
                SetRange("Date Filter", "Statement Date");
                CalcFields("G/L Balance (LCY)");
                CalculateBalance;
    
                PostedBankRecHeader.Init();
                PostedBankRecHeader.TransferFields(BankRecHeader, true);
                PostedBankRecHeader."G/L Balance (LCY)" := "G/L Balance (LCY)";
                PostedBankRecHeader.Insert();
    
                BankRecCommentLine.SetCurrentKey("Table Name",
                  "Bank Account No.",
                  "No.");
                BankRecCommentLine.SetRange("Table Name", BankRecCommentLine."Table Name"::"Bank Rec.");
                BankRecCommentLine.SetRange("Bank Account No.", "Bank Account No.");
                BankRecCommentLine.SetRange("No.", "Statement No.");
                if BankRecCommentLine.Find('-') then
                    repeat
                        Window.Update(3, BankRecCommentLine."Line No.");
    
                        PostedBankRecCommentLine.Init();
                        PostedBankRecCommentLine.TransferFields(BankRecCommentLine, true);
                        PostedBankRecCommentLine."Table Name" := PostedBankRecCommentLine."Table Name"::"Posted Bank Rec.";
                        PostedBankRecCommentLine.Insert();
                    until BankRecCommentLine.Next() = 0;
                BankRecCommentLine.DeleteAll();
    
                BankRecLine.Reset();
                BankRecLine.SetCurrentKey("Bank Account No.",
                  "Statement No.");
                BankRecLine.SetRange("Bank Account No.", "Bank Account No.");
                BankRecLine.SetRange("Statement No.", "Statement No.");
                if BankRecLine.Find('-') then
                    repeat
                        Window.Update(BankRecLine."Record Type" + 4, BankRecLine."Line No.");
                        if BankRecLine."Record Type" = BankRecLine."Record Type"::Adjustment then
                            if (GLSetup."Bank Rec. Adj. Doc. Nos." <> '') and
                               (BankRecLine."Document No." <> NoSeriesMgt.GetNextNo(GLSetup."Bank Rec. Adj. Doc. Nos.",
                                  "Posting Date", false))
                            then
                                NoSeriesMgt.TestManual(GLSetup."Bank Rec. Adj. Doc. Nos.");
    
                        if BankRecLine."Record Type" = BankRecLine."Record Type"::Adjustment then
                            PostAdjustmentToGL(BankRecLine)
                        else
                            if BankRecLine.Cleared then
                                UpdateLedgers(BankRecLine, SetStatus::Posted)
                            else
                                UpdateLedgers(BankRecLine, SetStatus::Open);
    
                        PostedBankRecLine.Init();
                        PostedBankRecLine.TransferFields(BankRecLine, true);
                        PostedBankRecLine.Insert();
                    until BankRecLine.Next() = 0;
                BankRecLine.DeleteAll();
                BankRecSubLine.Reset();
                BankRecSubLine.SetRange("Bank Account No.", "Bank Account No.");
                BankRecSubLine.SetRange("Statement No.", "Statement No.");
                BankRecSubLine.DeleteAll();
    
                BankAccount.Get("Bank Account No.");
                BankAccount."Last Statement No." := "Statement No.";
                BankAccount."Balance Last Statement" := "Statement Balance";
                OnBeforeBankAccountModify(BankAccount, BankRecHeader, PostedBankRecHeader);
                BankAccount.Modify();
    
                Delete;
    
                Commit();
                Window.Close;
            end;
            if GLSetup."Bank Rec. Adj. Doc. Nos." <> '' then
                NoSeriesMgt.SaveNoSeries;
            Rec := BankRecHeader;
            UpdateAnalysisView.UpdateAll(0, true);
        end;

Signature:

    
    [IntegrationEvent(false, false)]
    
    local procedure OnBeforeBankAccountModify(var BankAccount: Record "Bank Account"; BankRecHeader: Record "Bank Rec. Header"; var PostedBankRecHeader: Record "Posted Bank Rec. Header");
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
