### ISSUE TITLE
CU 368 Format Document parameter/Return Value limitation in function SetText

### ISSUE THREAD

**Issue by plagijat** [Microsoft/ALAppExtensions#1416]
Hello,

In **Codeunit 368 Format Document** function **SetText** has limited input Text[80] parameter Caption and limited Text[80] Return Value.
This causes **Possible overflow assigning 'Text' to 'Text[80]'.AL(AA0139)** when AL Code Analysis is enabled - which is required for AppSource review of Extension.

I see no reason to limit input parameter and return value in this case since the return value is not limited to some (buffer) table  field which has limitation of 250 chars.

Best,
Zoran

**Comment by darjoo** [comment]
Hi @plagijat,
I have discussed with Jesper and this isn't a extensibility-bug sized issue but much larger. `SetText` is only used in reports, any changes to the limit may cause repercussions throughout the report layouts.
As such, we would like to recommend that if you would like to push this through, you may post your idea on the [Ideas](https://experience.dynamics.com/ideas/) page. Or if you need this functionality with the increased limit, to copy this function and make your own modifications at this time.
