### ISSUE TITLE
[Event Request] New parameter DtldCustLedgEntry2 in standard event OnBeforePostUnApplyCustomerCommit in standard function PostUnApplyCustomerCommit of codeunit 226 "CustEntry-Apply Posted Entries"

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/ALAppExtensions#14172]
Hello.
Need new parameter DtldCustLedgEntry2 (parameter in PostUnApplyCustomerCommit) in standard event OnBeforePostUnApplyCustomerCommit in standard function PostUnApplyCustomerCommit of codeunit 226 "CustEntry-Apply Posted Entries"

Version of AL Language 7.4.496506
US Business Central 18.3 (Platform 18.0.27224.27469 + Application 18.3.27240.27480)

Function:

     procedure PostUnApplyCustomerCommit(DtldCustLedgEntry2: Record "Detailed Cust. Ledg. Entry"; DocNo: Code[20]; 
        PostingDate: Date; CommitChanges: Boolean)
        var
            GLEntry: Record "G/L Entry";
            CustLedgEntry: Record "Cust. Ledger Entry";
            SourceCodeSetup: Record "Source Code Setup";
            GenJnlLine: Record "Gen. Journal Line";
            DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry";
            DateComprReg: Record "Date Compr. Register";
            TempCustLedgerEntry: Record "Cust. Ledger Entry" temporary;
            AdjustExchangeRates: Report "Adjust Exchange Rates";
            GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line";
            GenJnlPostPreview: Codeunit "Gen. Jnl.-Post Preview";
            Window: Dialog;
            AddCurrChecked: Boolean;
            MaxPostingDate: Date;
            HideProgressWindow: Boolean;
            IsHandled: Boolean;
        begin
            OnBeforePostUnApplyCustomerCommit(HideProgressWindow, DtldCustLedgEntry2);
    
            if isHandled then
                exit;
    
            MaxPostingDate := 0D;
            GLEntry.LockTable();
            DtldCustLedgEntry.LockTable();
            CustLedgEntry.LockTable();
            CustLedgEntry.Get(DtldCustLedgEntry2."Cust. Ledger Entry No.");
            OnPostUnApplyCustomerCommitOnAfterGetCustLedgEntry(CustLedgEntry);
            CheckPostingDate(PostingDate, MaxPostingDate);
            if PostingDate < DtldCustLedgEntry2."Posting Date" then
                Error(MustNotBeBeforeErr);
            if DtldCustLedgEntry2."Transaction No." = 0 then begin
                DtldCustLedgEntry.SetCurrentKey("Application No.", "Customer No.", "Entry Type");
                DtldCustLedgEntry.SetRange("Application No.", DtldCustLedgEntry2."Application No.");
            end else begin
                DtldCustLedgEntry.SetCurrentKey("Transaction No.", "Customer No.", "Entry Type");
                DtldCustLedgEntry.SetRange("Transaction No.", DtldCustLedgEntry2."Transaction No.");
            end;
            DtldCustLedgEntry.SetRange("Customer No.", DtldCustLedgEntry2."Customer No.");
            DtldCustLedgEntry.SetFilter("Entry Type", '<>%1', DtldCustLedgEntry."Entry Type"::"Initial Entry");
            DtldCustLedgEntry.SetRange(Unapplied, false);
            OnPostUnApplyCustomerCommitOnAfterSetFilters(DtldCustLedgEntry, DtldCustLedgEntry2);
            if DtldCustLedgEntry.Find('-') then
                repeat
                    if not AddCurrChecked then begin
                        CheckAdditionalCurrency(PostingDate, DtldCustLedgEntry."Posting Date");
                        AddCurrChecked := true;
                    end;
                    CheckReversal(DtldCustLedgEntry."Cust. Ledger Entry No.");
                    if DtldCustLedgEntry."Transaction No." <> 0 then
                        CheckUnappliedEntries(DtldCustLedgEntry);
                until DtldCustLedgEntry.Next() = 0;
    
            DateComprReg.CheckMaxDateCompressed(MaxPostingDate, 0);
    
            with DtldCustLedgEntry2 do begin
                SourceCodeSetup.Get();
                CustLedgEntry.Get("Cust. Ledger Entry No.");
                GenJnlLine."Document No." := DocNo;
                GenJnlLine."Posting Date" := PostingDate;
                GenJnlLine."Account Type" := GenJnlLine."Account Type"::Customer;
                GenJnlLine."Account No." := "Customer No.";
                GenJnlLine.Correction := true;
                GenJnlLine.CopyCustLedgEntry(CustLedgEntry);
                GenJnlLine."Source Code" := SourceCodeSetup."Unapplied Sales Entry Appln.";
                GenJnlLine."Source Currency Code" := "Currency Code";
                GenJnlLine."System-Created Entry" := true;
                if not HideProgressWindow then
                    Window.Open(UnapplyingMsg);
    
                OnBeforePostUnapplyCustLedgEntry(GenJnlLine, CustLedgEntry, DtldCustLedgEntry2, GenJnlPostLine);
                CollectAffectedLedgerEntries(TempCustLedgerEntry, DtldCustLedgEntry2);
                GenJnlPostLine.UnapplyCustLedgEntry(GenJnlLine, DtldCustLedgEntry2);
                AdjustExchangeRates.AdjustExchRateCust(GenJnlLine, TempCustLedgerEntry);
                OnAfterPostUnapplyCustLedgEntry(GenJnlLine, CustLedgEntry, DtldCustLedgEntry2, GenJnlPostLine, CommitChanges);
    
                if PreviewMode then
                    GenJnlPostPreview.ThrowError;
    
                if CommitChanges then
                    Commit();
                if not HideProgressWindow then
                    Window.Close;
            end;
        end;

Signature:

      [IntegrationEvent(false, false)]
      local procedure OnBeforePostUnApplyCustomerCommit(var HideProgressWindow: Boolean; DtldCustLedgEntry2: Record "Detailed Cust. Ledg. Entry");
      begin
      end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
