### ISSUE TITLE
[Event Request] FinancialVoidCheck function on CheckManagement codeunit 367

### ISSUE THREAD

**Issue by LoanVision** [microsoft/ALAppExtensions#14189]
Change event OnFinancialVoidCheckOnBeforePostVoidcheckLine to include BankAccLedgerEntry2
from
` OnFinancialVoidCheckOnBeforePostVoidCheckLine(GenJnlLine2);`

to
` OnFinancialVoidCheckOnBeforePostVoidCheckLine(GenJnlLine2,BankAccLedgEntry2);`

**Comment by dnpb** [comment]
as `var` or not? MS ask us to include full signatures and example calls when requesting events.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
