### ISSUE TITLE
[Event Request] Codeunit 90 Purch. Post - OnPostUpdateOrderLineOnAfterInitQtyToReceiveOrShip

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#14184]
Hi,
is it possible to add to Puch. Post codeunit the event in object, that already exists for codeunito Sales-Post?

Codeunit 90
![image](https://user-images.githubusercontent.com/49486284/131678601-b078fa05-cea1-471b-9799-edae69f12898.png)

Codeunit 80
![image](https://user-images.githubusercontent.com/49486284/131678560-a0c7e862-69a9-4f52-a9ef-2180bbf63301.png)

Thank you

**Comment by Oleg-Romashkov** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
