### ISSUE TITLE
[Event Request] Codeunit Available to Promise, Function CalcAllItemFields

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#14195]
Hi,
to manage calculation of additional (own, new) FlowFields (Item table) in this procedure it would be very helpful if you could insert the following event:
 
![image](https://user-images.githubusercontent.com/47414309/131820495-68bb1241-4222-417a-8889-a1d704191e5d.png)

Please define Item as var
![image](https://user-images.githubusercontent.com/47414309/131820758-5bc3350c-1a3f-4b1a-b1ac-0a7d72eb1efc.png)

Thanks!

**Comment by Oleg-Romashkov** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by AJasp** [comment]
Thanks for the suggestion, I will do that

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
