### ISSUE TITLE
[NA] Codeunit 367 CheckManagement FinancialVoidCheck has not Document Type

### ISSUE THREAD

**Issue by LoanVision** [microsoft/ALAppExtensions#14190]
Hello,
when financially voiding check - document type is not defined on reversal entries. Function already exists GetVoidingDocumentType - however it's used only in "PostRoundingAmount" function.

Thanks!

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility.  The suggested solution does break some old behavior that verified by AL tests. Prepare enough information about the business cases that fail dur to this issue.
Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
