### ISSUE TITLE
Bug in Calendar Management

### ISSUE THREAD

**Issue by Chielve** [microsoft/ALAppExtensions#14193]
Hello,

We have found a bug in the Calendar Management Codeunit.

In the CombineChanges function there are 2 functions that use the NewCustomizedCalendarChange Record and update the TempCustomizedCalendarChange Record.

After the 2 functions are executed the CurrCustomizedCalendarChange Record is set with the NewCustomizedCalendarChange Record, which does not contain the changes made in the previous functions.

![image](https://user-images.githubusercontent.com/13106808/131814234-543c3b44-295f-4253-91e1-fdec6f109ee0.png)

This line:
CurrCustomizedCalendarChange := NewCustomizedCalendarChange;
Should be:
CurrCustomizedCalendarChange := TempCustomizedCalendarChange;

**Comment by StanPesotskiy** [comment]
Hi @Chielve,
CurrCustomizedCalendarChange's role is to prevent unnecessary calculations. It is compared with NewCustomizedCalendarChange in the beginning :
```
    local procedure CombineChanges(NewCustomizedCalendarChange: Record "Customized Calendar Change"; var TempCustomizedCalendarChange: record "Customized Calendar Change" temporary)
    begin
        if CurrCustomizedCalendarChange.IsEqualSource(NewCustomizedCalendarChange) then
            exit;
```
and get assigned in the end with NewCustomizedCalendarChange :
`        CurrCustomizedCalendarChange := NewCustomizedCalendarChange;`
If you run this function again with the same NewCustomizedCalendarChange it will not do anything as the temp buffer TempCustChange is already filled according to parameters of NewCustomizedCalendarChange. When the CheckDateStatus() is called it looks through TempCustChange to find the day status and CurrCustomizedCalendarChange does not play any other role here.

So I don't see a bug here unless you can share a business scenario when this leads to a problem. 
Can you share a failing AL test proving me wrong?
