### ISSUE TITLE
[Function Expose] DetermineCountry in "Country/Region" Table [BE localization]

### ISSUE THREAD

**Issue by maksym-ch** [Microsoft/ALAppExtensions#142]
Hi,
We need to implement additional business logic and use built-in function DetermineCountry from Table 9 Country/Region to define if specific country is BE  or not.

Thus, the function DetermineCountry should be external in table 9 Country/Region

**Comment by darjoo** [comment]
Hi, we've gone ahead with your request. We usually include these types of changes in the next minor release, so look for it there.
