### ISSUE TITLE
[Event Request] Codeunit 2000042 Post Coded Bank Statement - OnTransferCodBankStmtLinesOnBeforeInitGenJnlLine

### ISSUE THREAD

**Issue by OlegKulyk86** [microsoft/ALAppExtensions#14209]
Hi, would it be possible to modify the **OnTransferCodBankStmtLinesOnBeforeInitGenJnlLine** event in codeunit 2000042 (**Post Coded Bank Statement**) by adding the **var** keyword to the **CODAStatementLine** parameter, like this:

```al
    [IntegrationEvent(false, false)]
    local procedure OnTransferCodBankStmtLinesOnBeforeInitGenJnlLine(var CODAStatementLine: Record "CODA Statement Line")
    begin
    end;
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
