### ISSUE TITLE
[Request-for-external] page 6510 "Item Tracking Lines"- SetControls/AddReservEntriesToTempRecSet

### ISSUE THREAD

**Issue by Herodoteux** [microsoft/ALAppExtensions#14218]
Hi, I was wondering if it would be possible to change the procedure SetControls and AddReservEntriesToTempRecSet in Page 6510 from local to external.
My team and I use this procedure a lot in our code, and changing it to external would be a huge help.
Thanks.

**Comment by AlexanderYakunin** [comment]
This is already done:

    protected procedure SetPageControls(Controls: Enum "Item Tracking Lines Controls"; SetAccess: Boolean)
    protected procedure AddReservEntriesToTempRecSet(var ReservEntry: Record "Reservation Entry"; var TempTrackingSpecification: Record "Tracking Specification" temporary; SwapSign: Boolean; Color: Integer)
