### ISSUE TITLE
[Event Request] codeunit 7307 "Whse.-Activity-Register" Function InitTempTrackingSpecification

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#14213]
begin
        // DIN <<
        DINOnBeforeInitTempTrackingSpecification(WhseActivLine2,QtyToRegisterBase,DINIsHandled);
        if DINIsHandled then
            exit;
        // DIN >>
        QtyToRegisterBase := WhseActivLine2."Qty. to Handle (Base)";
        SetPointerFilter(WhseActivLine2, WhseItemTrkgLine);

        with WhseItemTrkgLine do begin
            SetTrackingFilterFromWhseActivityLine(WhseActivLine2);
            if FindSet then

    [IntegrationEvent(false, false)]
    local procedure DINOnBeforeInitTempTrackingSpecification(WarehouseActivityLine: Record "Warehouse Activity Line"; var QtyToRegisterBase: Decimal; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
