### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnCustFindVATSetupOnBeforeErrrorMessage

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#14225]
We need a new event in codeunit 12 "Close Income Statement" named **OnCustFindVATSetupOnBeforeErrrorMessage**

[IntegrationEvent(false, false)]
local procedure **OnCustFindVATSetupOnBeforeErrrorMessage**(VAR ErrorMessage: Boolean; VAR ExistsVATNoReal: Boolean);
begin
end;

called from:

**procedure CustFindVATSetup**(var VATSetup: Record "VAT Posting Setup"; CustLedgEntry4: Record "Cust. Ledger Entry"; IsFromJournal: Boolean): Boolean
    var
        Customer: Record Customer;
        ProdPostingGroup: Code[20];
        SalesLine2: Record "Sales Invoice Line";
        ErrorMessage: Boolean;
        ExistsVATNoReal: Boolean;
        Text1100003: Label 'Unrealized VAT Type must be "Percentage" in VAT Posting Setup.';
        GLEntry: Record "G/L Entry";
        BusPostingGroup: Code[20];
    begin
        ErrorMessage := false;
        ExistsVATNoReal := false;
        Customer.Get(CustLedgEntry4."Customer No.");
        .....
	.....
	.....
                                    ExistsVATNoReal := true;
                        end;
                end;
            until SalesLine2.Next = 0;
        end;
        **//INIT INSERT
        OnCustFindVATSetupOnBeforeErrrorMessage(ErrorMessage, ExistsVATNoReal);
        //END INSERT**
        if ErrorMessage then
            Error(Text1100003);
        exit(ExistsVATNoReal);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
