### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnVendFindVATSetupOnBeforeErrrorMessage

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#14224]
We need a new event in codeunit 12 "Close Income Statement" named **OnVendFindVATSetupOnBeforeErrrorMessage**

[IntegrationEvent(false, false)]
**local procedure OnVendFindVATSetupOnBeforeErrrorMessage**(VAR ErrorMessage: Boolean; VAR ExistsVATNoReal: Boolean);
begin
end;

called from:

**procedure VendFindVATSetup**(var VATSetup: Record "VAT Posting Setup"; VendLedgEntry4: Record "Vendor Ledger Entry"; IsFromJournal: Boolean): Boolean
    var
        Vendor: Record Vendor;
        ProdPostingGroup: Code[20];
        PurchLine2: Record "Purch. Inv. Line";
        Text1100003: Label 'Unrealized VAT Type must be "Percentage" in VAT Posting Setup.';
        ErrorMessage: Boolean;
        ExistsVATNoReal: Boolean;
        GLEntry: Record "G/L Entry";
        BusPostingGroup: Code[20];
        IsHandled: Boolean;
    begin
        ErrorMessage := false;
        ExistsVATNoReal := false;
        Vendor.Get(VendLedgEntry4."Vendor No.");
	.....
	.....
	.....
ExistsVATNoReal := true;
                        end;
                end;
            until PurchLine2.Next = 0;
        end;
**//INIT INSERT
        OnVendFindVATSetupOnBeforeErrrorMessage(ErrorMessage, ExistsVATNoReal);
        //END INSERT**
if ErrorMessage then
            Error(Text1100003);
        exit(ExistsVATNoReal);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
