### ISSUE TITLE
Report 190 "Issue Reminders" - Add "InDataSet" on PostingDateReq variable

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#14228]
```
 NewDateTime: DateTime;
  OldDateTime: DateTime;
  [InDataSet]
  PostingDateReq: Date;
  ReplacePostingDate: Boolean;
  PrintDoc: Option " ",Print,Email;
```

**Comment by StanPesotskiy** [comment]
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/attributes/devenv-indataset-attribute
The InDataSet attribute is defined on variables of the type Boolean or Integer on pages.
