### ISSUE TITLE
Add RetrieveAsmItemTracking to OnRetrieveDocumentItemTracking Event

### ISSUE THREAD

**Issue by domingosbarreto** [microsoft/ALAppExtensions#14220]
Is it possible to add RetrieveAsmItemTracking variable as a parameter to event OnRetrieveDocumentItemTracking in codeunit 6503 "Item Tracking Doc. Management"?

Would be:

```
[IntegrationEvent(false, false)]
local procedure OnRetrieveDocumentItemTracking(var TempTrackingSpecBuffer: Record "Tracking Specification" temporary; SourceID: Code[20]; var Found: Boolean; SourceType: Integer; SourceSubType: Option; RetrieveAsmItemTracking: Boolean)
begin
end;
```

Instead of:
 
```
[IntegrationEvent(false, false)]
local procedure OnRetrieveDocumentItemTracking(var TempTrackingSpecBuffer: Record "Tracking Specification" temporary; SourceID: Code[20]; var Found: Boolean; SourceType: Integer; SourceSubType: Option)
begin
end;
```

Thank you,
Domingos Barreto

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
