### ISSUE TITLE
Price List Header & Line OnLookup triggers should validate field

### ISSUE THREAD

**Issue by BertDeTemmerman** [microsoft/ALAppExtensions#14229]
Could the OnLookup triggers in the Price List Header & Line please do a validate of the field?
It's very hard to add extra custom logic to the price lists to update other fields if you don't know the original fields are changed ...

example :
```
table 7001 "Price List Line"

field(15; "Unit of Measure Code"; Code[10])
{
 DataClassification = CustomerContent;

 trigger OnValidate()
 begin
                TestStatusDraft();
                CopyRecTo(PriceAsset);
                PriceAsset.Validate("Unit of Measure Code", "Unit of Measure Code");
                CopyFrom(PriceAsset);
 end;

 trigger OnLookup()
 begin
                CopyTo(PriceAsset);
                if PriceAsset.LookupUnitofMeasure() then begin
                    TestStatusDraft();
                    "Unit of Measure Code" := PriceAsset."Unit of Measure Code";
                end;
 end;
}
```

 
How can I subscribe on 
`[EventSubscriber(ObjectType::Table, Database::"Price List Line", 'OnAfterValidateEvent', 'Unit of Measure Code', true, true)]`
if it isn't called when using the OnLookup?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.

**Comment by JesperSchulz** [comment]
The changes went into the 19.x branch on the 13th of September and should have been released with 19.1. I see the following changes in our repo:
![image](https://user-images.githubusercontent.com/19796701/145064956-d8b7384d-dead-4558-8bf1-4ea8c4fdfc4e.png)

**Comment by BertDeTemmerman** [comment]
Yes, now I look in the base object itself, I see it too ...

Nevermind, sorry, stupid me!
I checked the Base application Version="19.0.29894.33342", thinking I copied 19.1.
In 19.1 it IS fixed. :)
Thank you and sorry for being stupid ... ><

**Comment by JesperSchulz** [comment]
No worries at all. I make those kind of mistakes all the time ;-)
