### ISSUE TITLE
[Application] Missing PageId's on "Data Exch. Def"

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#14230]
Table "Data Exch. Def" has no default DrillDownPageId / LookupPageId, making navigating more complex.

We can easily change this by introducing a table extension, although it would be better if the base app would contain below pages / properties as defaults.

```
tableextension 2002643 "NVT Data Exch. Def" extends "Data Exch. Def"
{
    DrillDownPageId = "Data Exch Def List";
    LookupPageId = "Data Exch Def List";
}
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
