### ISSUE TITLE
[Event Request] 1650 "Curr. Exch. Rate Update Setup"

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#14236]
Please make function CreateDataExchangeDefinition in the Codeunit 1650 "Curr. Exch. Rate Update Setup" externally available.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
