### ISSUE TITLE
[Event Request] Codeunit 368 Format Document OnAfterSetTotalLabels

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#14235]
Event 
`OnAfterSetTotalLabels(CurrencyCode: Code[10];VAR TotalInclVATText: Text[50];VAR TotalExclVATText: Text[50])`
at the end of the function SetTotalLabels.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
