### ISSUE TITLE
[Event Request] codeunit 7326 Whse. Item Tracking FEFO Function SummarizeInventoryFEFO

### ISSUE THREAD

**Issue by DirkGijsen** [microsoft/ALAppExtensions#14243]
with ItemLedgEntry do begin
            Reset;
            SetCurrentKey("Item No.", Open, "Variant Code", Positive, "Lot No.", "Serial No.");
            SetRange("Item No.", ItemNo);
            SetRange(Open, true);
            SetRange("Variant Code", VariantCode);
            SetRange(Positive, true);
            if HasExpirationDate then
                SetFilter("Expiration Date", '<>%1', 0D)
            else
                SetRange("Expiration Date", 0D);
            SetRange("Location Code", Location.Code);
            // DINNL <<
            DINOnSummarizeInventoryFEFOOnAfterSetILEFilters(ItemLedgEntry, ItemNo, HasExpirationDate);
            // DINNL >>
            if IsEmpty() then
                exit;

            FindSet();
            repeat

    [IntegrationEvent(false, false)]
    local procedure DINOnSummarizeInventoryFEFOOnAfterSetILEFilters(var ItemLedgerEntry: Record "Item Ledger Entry"; ItemNo: Code[20]; HasExpirationDate: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
