### ISSUE TITLE
Table 37 Sales Line GetSalesHeader, GetItem, GetResource

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#14256]
On table Sales Line

Function GetSalesHeader is only available with two var parameters: Sales Header and Currency.
In case we don't need Currency, we still need to create a dummy variable for it.
Would it be possible to let GetSalesHeader() return the Sales Header variable, similar to GetCust() on table Sales Header?

Same for GetItem and GetResource, please let these two functions have the global variables as return values.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
