### ISSUE TITLE
[Access Request] Table 39 "Purchase Line" - Global variables

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#14255]
This is the same request as https://github.com/microsoft/ALAppExtensions/issues/13172

The previous issue was closed without proper discussion. I would like to point out that the existing

`procedure GetPurchHeader(var OutPurchHeader: Record "Purchase Header"; var OutCurrency: Record Currency)
`
requires us to define a dummy record variable for Record Currency in case we only need Purchase Header. This will lead to a code analyzer message like 'variable is assigned but never used' or something like that.

I think that making these two variables protected is a good alternative so we can use them from the tableextension after calling GetPurchHeader()

Alternatively (maybe better) let procedure GetPurchHeader() return the Purchase Header, similar to GetCust() on Sales Header.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
