### ISSUE TITLE
[Request-For-External] Report 593 "Intrastat - Make Disk Tax Auth" - TempIntrastatJnlLine

### ISSUE THREAD

**Issue by petroLubchenko** [microsoft/ALAppExtensions#14262]
Hi, could you please change the global **TempIntrastatJnlLine** variable's protection level on report 593 (**Intrastat - Make Disk Tax Auth**) to a protected?
```AL
    protected var
        TempIntrastatJnlLine: Record "Intrastat Jnl. Line" temporary;
```
Thanks!

**Comment by AlexanderYakunin** [comment]
Please explain scenario to use this variable? Maybe you simply need single event instead?

**Comment by petroLubchenko** [comment]
We have the customization that rounds the **No. of Supplementary Units** field for the result xml file. Therefore, we would like to write the code to round the **No. of Supplementary Units** field in the **OnPostDataItem** trigger (of **IntrastatJnlLine** dataitem). We have the idea to reach this using the protected **TempIntrastatJnlLine** variable in the report extension. However, it will be also possible to implement this logic using the following **OnBeforeOnPostDataItemIntrastatJnlLine** event:
```AL
                trigger OnPostDataItem()
                var
                    ExportType: Option Receipt,Shipment;
                begin
                    OnBeforeOnPostDataItemIntrastatJnlLine(TempIntrastatJnlLine); // New event

                    TempIntrastatJnlLine.Reset();

                    // Reciepts
                    if StrPos(GetFilter(Type), Format(Type::Receipt)) <> 0 then begin
                        CreateReportNode(ExportType::Receipt);
                        IntrastatJnlBatch."System 19 reported" := true;
                    end;

                    // Shipments
                    if StrPos(GetFilter(Type), Format(Type::Shipment)) <> 0 then begin
                        CreateReportNode(ExportType::Shipment);
                        IntrastatJnlBatch."System 29 reported" := true;
                    end;

                    IntrastatJnlBatch.Modify();
                end;
```
```AL
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnPostDataItemIntrastatJnlLine(var TempIntrastatJnlLine: Record "Intrastat Jnl. Line" temporary)
    begin
    end;
```

In case such a way is better from the product point of view, could you please add the mentioned event?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
