### ISSUE TITLE
[Event Request] Table 179 "Reversal Entry"

### ISSUE THREAD

**Issue by mrabus** [microsoft/ALAppExtensions#14270]
New event requested to skip the posting date check. It would be great if you could use the handled pattern or something similar. 

local procedure CheckPostingDate(PostingDate: Date; Caption: Text[50]; EntryNo: Integer)
var
    Handled: Boolean; 
begin
    //EVENTREQUEST
    HandleCheckPostingDate(PostingDate, EntryNo, Handled);
    if Handled then 
        exit;
    //EVENTREQUEST

    if GenJnlCheckLine.DateNotAllowed(PostingDate) then
        Error(Text001, Caption, EntryNo);
    if PostingDate > MaxPostingDate then
        MaxPostingDate := PostingDate;
end;

//EVENTREQUEST
[IntegrationEvent(false, false)]
local procedure HandleCheckPostingDate(PostingDate: Date; Caption: Text[50]; EntryNo: Integer; var Handled: Boolean)
begin
end;
//EVENTREQUEST

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
