### ISSUE TITLE
purchaseInvoiceLines endpoint does not accept Resource Item type custom unit cost

### ISSUE THREAD

**Issue by Iamabdul** [microsoft/ALAppExtensions#14276]
When posting to the `api/v2.0/companies({{companyId}})/purchaseInvoiceLines` endpoint using this body:

```
{
    "documentId": "{docId}",
    "lineType": "Resource",
    "lineObjectNumber": "LINDA",
    "description": "bbb",
    "unitCost": 20,
    "quantity": 2
}
```

The unit cost of the post body is ignored and instead uses the default resource item unit cost, it returns with this body in the result.

{
    ...
    "id": {newId},
    "documentId": "{docId},
    "itemId": "00000000-0000-0000-0000-000000000000",
    "accountId": "00000000-0000-0000-0000-000000000000",
    "lineType": "Resource",
    "lineObjectNumber": "LINDA",
    "description": "bbb",
    "unitOfMeasureCode": "HOUR",
    "unitCost": 50,
    "quantity": 2,
    "taxCode": "REDUCED",
    "taxPercent": 5,
    "netAmount": 100,
    "netTaxAmount": 5,
    "netAmountIncludingTax": 105,
    ...
}

**Comment by RomanZanizdra** [comment]
Hi @Iamabdul . 
I suggest you yo change the order in statement, put "quantity" before "unitcost" that should solve the problem.

**Comment by RomanZanizdra** [comment]
@Iamabdul , I also see you use purchaseInvoiceLines for exposure that doesn't look like existing in BC page. So also please try your request on the purchaseDocumentLines and share the result.

**Comment by Iamabdul** [comment]
@RomanZanizdra Apologies for the late reply!

I've attempted to put "quantity" before "unitcost" and that didn't work unfortunately.

I'm also using [this page](https://github.com/microsoft/ALAppExtensions/blob/9e66810a78d25f430225871f5fa06a556089862e/Apps/W1/APIV2/app/src/pages/APIV2PurchaseInvoiceLines.Page.al), I'm assuming that this is what this endpoint hits?:
`api.businesscentral.dynamics.com/v2.0/sandbox/api/v2.0/companies({{companyId}})/purchaseInvoiceLines`
