### ISSUE TITLE
[Event Request] Codeunits 70 "Purch.-Calc.Discount and 5950 "Service-Calc. Discount"

### ISSUE THREAD

**Issue by Easystep2** [microsoft/ALAppExtensions#14272]
We would like to have a simular Event as defined in codeunit 60 "Sales-Calc. Discount" called  OnAfterValidateSalesLine2Quantity(SalesHeader, SalesLine2, CustInvDisc);

in **codeunit 70 this would be  in local procedure CalulateInvoiceDiscount::**

       if VendInvDisc."Service Charge" <> 0 then begin
                OnCalculateInvoiceDiscountOnBeforeCurrencyInitialize(VendPostingGr);
                Currency.Initialize(PurchHeader."Currency Code");
                if not UpdateHeader then
                    PurchLine2.SetPurchHeader(PurchHeader);
                if not TempServiceChargeLine.IsEmpty() then begin
                    TempServiceChargeLine.FindLast;
                    PurchLine2.Get("Document Type", "Document No.", TempServiceChargeLine."Line No.");
                    if PurchHeader."Prices Including VAT" then
                        PurchLine2.Validate(
                          "Direct Unit Cost",
                          Round(
                            (1 + PurchLine2."VAT %" / 100) * VendInvDisc."Service Charge",
                            Currency."Unit-Amount Rounding Precision"))
                    else
                        PurchLine2.Validate("Direct Unit Cost", VendInvDisc."Service Charge");
                    PurchLine2.Modify();
                end else begin
                    PurchLine2.Reset();
                    PurchLine2.SetRange("Document Type", "Document Type");
                    PurchLine2.SetRange("Document No.", "Document No.");
                    PurchLine2.Find('+');
                    PurchLine2.Init();
                    if not UpdateHeader then
                        PurchLine2.SetPurchHeader(PurchHeader);
                    PurchLine2."Line No." := PurchLine2."Line No." + 10000;
                    PurchLine2.Type := PurchLine2.Type::"G/L Account";
                    PurchLine2.Validate("No.", VendPostingGr.GetServiceChargeAccount);
                    PurchLine2.Description := Text000;
                    PurchLine2.Validate(Quantity, 1);

<<<<<
                       **OnAfterValidatePurchaseLine2Quantity(PurchHeader, PurchLine2, VendInvDisc);**
>>>>>

                    if PurchLine2."Document Type" in
                       [PurchLine2."Document Type"::"Return Order", PurchLine2."Document Type"::"Credit Memo"]
                    then
                        PurchLine2.Validate("Return Qty. to Ship", PurchLine2.Quantity)
                    else
                        PurchLine2.Validate("Qty. to Receive", PurchLine2.Quantity);
                    if PurchHeader."Prices Including VAT" then
                        PurchLine2.Validate(
                          "Direct Unit Cost",
                          Round(
                            (1 + PurchLine2."VAT %" / 100) * VendInvDisc."Service Charge",
                            Currency."Unit-Amount Rounding Precision"))
                    else
                        PurchLine2.Validate("Direct Unit Cost", VendInvDisc."Service Charge");
                    PurchLine2."System-Created Entry" := true;
                    PurchLine2.Insert();
                end;

in **Codeunit 5950 this would be in local procedure CalulateInvoiceDiscount::**

       if CustInvDisc."Service Charge" <> 0 then begin
                    Currency.Initialize(ServHeader."Currency Code");
                    if TemporaryHeader then
                        ServiceLine2.SetServHeader(ServHeader);
                    if ServiceChargeLineNo <> 0 then begin
                        ServiceLine2.Get("Document Type", "Document No.", ServiceChargeLineNo);
                        if ServHeader."Prices Including VAT" then
                            ServiceLine2.Validate(
                              "Unit Price",
                              Round(
                                (1 + ServiceLine2."VAT %" / 100) * CustInvDisc."Service Charge",
                                Currency."Unit-Amount Rounding Precision"))
                        else
                            ServiceLine2.Validate("Unit Price", CustInvDisc."Service Charge");
                        ServiceLine2.Modify();
                    end else begin
                        ServiceLine2.Reset();
                        ServiceLine2.SetRange("Document Type", "Document Type");
                        ServiceLine2.SetRange("Document No.", "Document No.");
                        ServiceLine2.Find('+');
                        ServiceLine2.Init();
                        if TemporaryHeader then
                            ServiceLine2.SetServHeader(ServHeader);
                        ServiceLine2."Line No." := ServiceLine2."Line No." + GetNewServiceLineNoBias(ServiceLine2);
                        ServiceLine2.Type := ServiceLine2.Type::"G/L Account";
                        ServiceLine2.Validate("No.", CustPostingGr.GetServiceChargeAccount);
                        ServiceLine2.Description := Text000;
                        ServiceLine2.Validate(Quantity, 1);

<<<<<
                       **OnAfterValidateServiceLine2Quantity(ServHeader, ServiceLine2, CustInvDisc);**
>>>>>

                        if ServHeader."Prices Including VAT" then
                            ServiceLine2.Validate(
                              "Unit Price",
                              Round(
                                (1 + ServiceLine2."VAT %" / 100) * CustInvDisc."Service Charge",
                                Currency."Unit-Amount Rounding Precision"))
                        else
                            ServiceLine2.Validate("Unit Price", CustInvDisc."Service Charge");
                        ServiceLine2."System-Created Entry" := true;
                        ServiceLine2.Insert();
                    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
