### ISSUE TITLE
[Event Request] Report 1003 - Existing Event "OnAfterOnPreDataItem"

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#14277]
Hi,
the Event Request [(#12089)](https://github.com/microsoft/ALAppExtensions/issues/12809) inserted the event "_OnAfterOnPreDataItem_". According to my analysis, this is not called in the code. I would expect this here (After code line 118):

  trigger OnPreDataItem()
  begin
      InvtPostToGL.SetRunOnlyCheck(false, true, true);
      TempCapValueEntry.DeleteAll();
      OnAfterPostValueEntryToGLOnPreDataItem(PostValueEntryToGL, CompanyName);
      // missing event #5510 - begins after line 118
      OnAfterOnPreDataItem(PostValueEntryToGL, CompanyName);
  end;

In line 118 the event _"OnAfterPostValueEntryToGLOnPreDataItem(PostValueEntryToGL, CompanyName);"_ is fired - the name ob this Event might be a little bit confusing though, so I think it would make more sense to fire the Event "OnAfterOnPreDataItem" there.

Thanks!

**Comment by Oleg-Romashkov** [comment]
Hi,
Is it ok for you to use existent event OnAfterPostValueEntryToGLOnPreDataItem instead of mentioned OnAfterOnPreDataItem?

**Comment by AJasp** [comment]
Hi,
this is exactly what i am currently doing. actually the report does not post anything (testreport) and therefore the name is a bit confusing. Was the event originally intended for report 1002?

**Comment by Oleg-Romashkov** [comment]
Ok then. Name OnAfterPostValueEntryToGLOnPreDataItem means event located in the end of OnPreDataItem of the PostValueEntryToGL dataitem. This is more meaningful in case of several dataitems and their OnPreDataItem triggers.
