### ISSUE TITLE
[Enum Request] Table 1001 "Job Task" Field 4 "Job Task Type"

### ISSUE THREAD

**Issue by tdkumar** [microsoft/ALAppExtensions#14273]
Please change field 4 "Job Task Type" in Table 1001 "Job Task" to Enum

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
