### ISSUE TITLE
ShowPostedConfirmationMessage should be able to open different pages

### ISSUE THREAD

**Issue by domingosbarreto** [microsoft/ALAppExtensions#14294]
Is it possible to add an event to all ShowPostedConfirmationMessage procedures across the application in all documents lists and card pages?

This is useful because different pages may be opened on certain conditions, and at this moment the application always opens the standard page.

My suggestion is to add an OnBeforeOpenPostedDocument event before running the page, like in the example below:

Before:
```
local procedure ShowPostedConfirmationMessage()
var
    OrderPurchaseHeader: Record "Purchase Header";
    PurchInvHeader: Record "Purch. Inv. Header";
    InstructionMgt: Codeunit "Instruction Mgt.";
begin
    if not OrderPurchaseHeader.Get("Document Type", "No.") then begin
        PurchInvHeader.SetRange("No.", "Last Posting No.");
        if PurchInvHeader.FindFirst then
            if InstructionMgt.ShowConfirm(StrSubstNo(OpenPostedPurchaseOrderQst, PurchInvHeader."No."),
                    InstructionMgt.ShowPostedConfirmationMessageCode)
            then
                PAGE.Run(PAGE::"Posted Purchase Invoice", PurchInvHeader);
    end;
end;
```

After the event added:
```
local procedure ShowPostedConfirmationMessage()
var
    OrderPurchaseHeader: Record "Purchase Header";
    PurchInvHeader: Record "Purch. Inv. Header";
    InstructionMgt: Codeunit "Instruction Mgt.";
    IsHandled: Boolean;
begin
    if not OrderPurchaseHeader.Get("Document Type", "No.") then begin
        PurchInvHeader.SetRange("No.", "Last Posting No.");
        if PurchInvHeader.FindFirst then
            if InstructionMgt.ShowConfirm(StrSubstNo(OpenPostedPurchaseOrderQst, PurchInvHeader."No."),
                    InstructionMgt.ShowPostedConfirmationMessageCode)
            then begin
                OnBeforeOpenPostedDocument(PurchInvHeader, IsHandled);
                if not IsHandled then
                    PAGE.Run(PAGE::"Posted Purchase Invoice", PurchInvHeader);
            end;
    end;
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeOpenPostedDocument(PurchInvHeader: Record "Purch. Inv. Header"; var IsHandled: Boolean)
begin
end;
```

Pages where I found this procedure:
- Page 42 "Sales Order"
- Page 43 "Sales Invoice"
- Page 44 "Sales Credit Memo"
- Page 50 "Purchase Order"
- Page 51 "Purchase Invoice"
- Page 52 "Purchase Credit Memo"
- Page 5900 "Service Order"
- Page 5933 "Service Invoice"
- Page 5935 "Service Credit Memo"
- Page 6630 "Sales Return Order"
- Page 6640 "Purchase Return Order"
- Page 9301 "Sales Invoice List"
- Page 9302 "Sales Credit Memos"
- Page 9308 "Purchase Invoices"
- Page 9309 "Purchase Credit Memos"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
