### ISSUE TITLE
[Event Request] New IntegrationEvent in Codeunit 905 "Assembly Line Management", function SetLinkToBOM

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#14295]
Hello,

please insert new IntegrationEvent in Codeunit 905 "Assembly Line Management", function SetLinkToBOM

The BOMComponent Parameter should get the VAR Property

    local procedure SetLinkToBOM(AsmHeader: Record "Assembly Header"; var BOMComponent: Record "BOM Component")
    begin
        BOMComponent.SetRange("Parent Item No.", AsmHeader."Item No.");
        // Start kvs.dde
        OnAfterSetLinkToBOM(BOMComponent,AsmHeader)
        // Stop kvs.dde
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
