### ISSUE TITLE
Add OnBeforeTestStatus(Rec,IsHandled) event to Production Bom Line Table (99000772) 

### ISSUE THREAD

**Issue by GregEnns** [microsoft/ALAppExtensions#14296]
The "Production BOM Line" table has a "TestStatus" procedure. Can we please add an event (and the related IsHandled code) at the beginning of this procedure to allow for escaping this procedure?

```
    procedure TestStatus()
    var
        ProdBOMVersion: Record "Production BOM Version";
    begin
        OnBeforeTestStatus(Rec, IsHandled);
        if IsHandled then
            exit;
        .........
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTestStatus(Rec: Record "Production BOM Line"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
