### ISSUE TITLE
Report 1009 "Job Actual To Budget" Label Text000 to support Enum "Job Journal Line Type" values

### ISSUE THREAD

**Issue by tdkumar** [microsoft/ALAppExtensions#14305]
In Report 1009,  Variable **Text000: Label 'Resource,Item,G/L Account'**  is not extendable to sync with **Enum "Job Journal Line Type"** values 

Variable Text000 is used in below code:
column(JobDiffBufferType1; SelectStr(JobDiffBuffer.Type.AsInteger() + 1, Text000))
column(JobDiffBuffer2Type1; SelectStr(JobDiffBuffer2.Type.AsInteger() + 1, Text000))

As we extended **Enum "Job Journal Line Type"** ,  getting below error while running the  "Job Actual To Budget" report:
"The SourceExpr for report control 'JobDiffBufferType1' is not valid. The following error occurred: The SELECTSTR comma-string Resource,Item,G/L Account does not contain a value for index 50001."

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
