### ISSUE TITLE
[Scope Change Request] Table "Prod. Order Component" - SetFilterFromProdBOMLine

### ISSUE THREAD

**Issue by Meximity** [microsoft/ALAppExtensions#14308]
Hi,

I'd like to request a Scope Change in table "Prod. Order Component" so that we can use this function for cloud development and don't need to copy the function in an table extension/codeunit.
I'm not sure why this is set to OnPrem, because all the function does is filter the current record.

```
    [Scope('OnPrem')]
    procedure SetFilterFromProdBOMLine(ProdBOMLine: Record "Production BOM Line")
    begin
        SetRange("Item No.", ProdBOMLine."No.");
        SetRange("Variant Code", ProdBOMLine."Variant Code");
        SetRange("Routing Link Code", ProdBOMLine."Routing Link Code");
        SetRange(Position, ProdBOMLine.Position);
        SetRange("Position 2", ProdBOMLine."Position 2");
        SetRange("Position 3", ProdBOMLine."Position 3");
        SetRange(Length, ProdBOMLine.Length);
        SetRange(Width, ProdBOMLine.Width);
        SetRange(Weight, ProdBOMLine.Weight);
        SetRange(Depth, ProdBOMLine.Depth);
        SetRange("Unit of Measure Code", ProdBOMLine."Unit of Measure Code");

        OnAfterSetFilterFromProdBOMLine(Rec, ProdBOMLine);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
