### ISSUE TITLE
[Event Request] new Parameter in Procedure UpdateWhseShptLine in Codeunit 7307 "Whse.-Activity-Register"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#14301]
We need a new parameter to transfer the local WhseActivityLine to the function UpdateWhseShptLine:
Old:
procedure UpdateWhseShptLine(WhseDocNo: Code[20]; WhseDocLineNo: Integer; QtyToHandle: Decimal; QtyToHandleBase: Decimal; QtyPerUOM: Decimal)
New:
procedure UpdateWhseShptLine(WhseDocNo: Code[20]; WhseDocLineNo: Integer; QtyToHandle: Decimal; QtyToHandleBase: Decimal; QtyPerUOM: Decimal; **WhseActivityLine : Record "Warehouse Activity Line"**

In Codeunit "Whse.-Activity-Register" in Procedure UpdateWhseSourceDocLine several update routines are called with the local parameter WhseActivLine.

E.G. UpdateProdCompLine(WhseActivLine), UpdateAssemblyLine(WhseActivLine), UpdatePostedWhseRcptLine(WhseActivLine)

Only UpdateWhseShptLine is not called with WhseActivLine.

Inside all Update Routines the parameter WhseActivLine is then transferred to the OnBeforeModify and OnAfterModify functions working here with the local variable.

E.G.

OnBeforeProdCompLineModify(ProdCompLine, WhseActivityLine);
            ProdCompLine.Modify();
            OnAfterProdCompLineModify(ProdCompLine);

Only because of the missing parameter UpdateWhseShptLine is working with the global WhseActivityLine, which contains the wrong values in case of partial shipments.

So those routines transfer the wrong variables and our extensions uses the wrong values.

 OnBeforeWhseShptLineModify(WhseShptLine, WhseActivLine);
        WhseShptLine.Modify();
        OnAfterWhseShptLineModify(WhseShptLine);

**Comment by Oleg-Romashkov** [comment]
We do not add parameters to functions which are used only by events. 
To handle this particular case you can use event OnBeforeUpdateWhseSourceDocLine to process "Whse. Document Type"::Shipment
