### ISSUE TITLE
[Scope Change] Page "Check Credit Limit" - "SalesLineShowWarning"

### ISSUE THREAD

**Issue by Meximity** [microsoft/ALAppExtensions#14306]
Hi, 

I'd like to request the Scope "OnPrem" to be removed so that we can use this for cloud management.
I haven't seen an obsolete tag or anything else, so I'm not entirely sure if this is intended or not.

```     
    [Scope('OnPrem')]
    procedure SalesLineShowWarning(SalesLine: Record "Sales Line") Result: Boolean
    var
        IsHandled: Boolean;
    begin
        // ...
    end
```

**Comment by AlexanderYakunin** [comment]
This is already removed
