### ISSUE TITLE
[Event modification] Event OnAfterQueryClosePage in page 9176 "My Settings"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#14300]
Dear ALAppExtensions Team:

Our solution extends the page 9176 "My Settings". We need to refresh the user session even if the standard values in the page have not changed. In order to achieve this, we need a new parameter in the event publisher OnAfterQueryClosePage.

The event publisher OnAfterQueryClosePage in Page 9176 "My Settings" would be modified as follows:

OLD CODE:

  [IntegrationEvent(false, false)]
    local procedure OnAfterQueryClosePage(NewLanguageID: Integer; NewLocaleID: Integer; NewTimeZoneID: Text[180]; NewCompany: Text; NewAllProfile: Record "All Profile")
    begin
    end;

NEW CODE:
 [IntegrationEvent(false, false)]
    local procedure OnAfterQueryClosePage(NewLanguageID: Integer; NewLocaleID: Integer; NewTimeZoneID: Text[180]; NewCompany: Text; NewAllProfile: Record "All Profile"**; var AnythingUpdated: Boolean**)  //parameter added
    begin
    end;

The code in the page would be modify as follows:

OLD CODE:
.
.
.
      if AllProfile.Get(ProfileScope, ProfileAppID, ProfileID) then;
            OnAfterQueryClosePage(LanguageID, LocaleID, TimeZoneID, VarCompany, AllProfile);

            if AnythingUpdated then
                sessionSetting.RequestSessionUpdate(true);
.
.
.

NEW CODE:

.
.
.
      if AllProfile.Get(ProfileScope, ProfileAppID, ProfileID) then;

            //start new code
            OnAfterQueryClosePage(LanguageID, LocaleID, TimeZoneID, VarCompany, AllProfile, AnythingUpdated;
           //end new code 

            if AnythingUpdated then
                sessionSetting.RequestSessionUpdate(true);
.
.
.

Thanks!

**Comment by Oleg-Romashkov** [comment]
Event OnAfterQueryClosePage cannot be extended by technical reasons.
My Settings is obsoleted page and well be removed soon. Use page "User Settings" instead.
