### ISSUE TITLE
[Event Request] Codeunit 80/90 OnBeforeCheckDim

### ISSUE THREAD

**Issue by GuntherGebauer** [Microsoft/ALAppExtensions#1430]
We Need a new Event trigger in codeunits 80 and 90 in CheckAndUpdate before Checkdim is called:

Codeunit 80:
PROCEDURE LOCAL CheckAndUpdate
...
  InvtPickPutaway := "Posting from Whse. Ref." <> 0;
  "Posting from Whse. Ref." := 0;
  
  OnBeforeCheckDim(VAR SalesHeader);  <-- new Event trigger
  CheckDim(SalesHeader);

Codeunit 90:
PROCEDURE LOCAL CheckAndUpdate
...

  InvtPickPutaway := "Posting from Whse. Ref." <> 0;
  "Posting from Whse. Ref." := 0;

  OnBeforeCheckDim(VAR PurchHeader);  <-- new Event trigger
  CheckDim(PurchHeader);

**Comment by AlexanderYakunin** [comment]
Another event already implemented here

COD481
[External] CheckSalesDim(SalesHeader : Record "Sales Header";VAR TempSalesLine : TEMPORARY Record "Sales Line")
IsHandled := FALSE;
OnBeforeCheckSalesDim(SalesHeader,TempSalesLine,IsHandled);
IF IsHandled THEN
  EXIT;

**Comment by AlexanderYakunin** [comment]
You seems to use old code base.
