### ISSUE TITLE
[Event Request] table 8613 "Config. Package Table"  OnBeforeShowFilteredPackageFields

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#14318]
procedure ShowFilteredPackageFields(FilterValue: Text)
    var
        ConfigPackageField: Record "Config. Package Field";
        ConfigPackageFields: Page "Config. Package Fields";
    begin
        if InitPackageFields then
            Commit();

        if "Dimensions as Columns" then
            if not DimensionPackageDataExist then begin
                if DimensionFieldsCount > 0 then
                    DeleteDimensionFields;
                InitDimensionFields;
                Commit();
            end;
        // DINNL <<
        DINOnBeforeShowFilteredPackageFields(Rec);
        // DINNL >>

    [IntegrationEvent(false, false)]
    local procedure DINOnBeforeShowFilteredPackageFields(var ConfigPackageTable: Record "Config. Package Table")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
