### ISSUE TITLE
[Request for Protected] page 8625 "Config. Package Subform" ConfigPackageTable

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#14317]
var
        MultipleTablesSelectedQst: Label '%1 tables have been selected. Do you want to continue?', Comment = '%1 = Number of selected tables';
        //ConfigPackageTable: Record "Config. Package Table"; // DINNL <<
        Show: Option Records,Errors,All;
        [InDataSet]
        NoOfErrorsStyleTxt: Text;
        SingleTableSelectedQst: Label 'One table has been selected. Do you want to continue?', Comment = '%1 = Table name';
        MultiRelationQst: Label 'Some fields have two or more related tables.\Do you want to check them?';
        AditionalOptionsEnabled: Boolean;

    protected var
        ConfigPackageTable: Record "Config. Package Table"; // DINNL <<

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
