### ISSUE TITLE
[Event Request] table 8616 "Config. Package Field" OnBeforeValidateFieldValidateField

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#14313]
field(6; "Validate Field"; Boolean)
        {
            Caption = 'Validate Field';

            trigger OnValidate()
            var 
                DINIsHandled: Boolean;
            begin
                // DINNL <<
                DINIsHandled := false;
                DINOnBeforeValidateFieldValidateField(Rec, DINIsHandled);
                if DINIsHandled then
                    exit;
                // DINNL >> 
                if not Dimension then begin
                    if xRec."Validate Field" and not "Validate Field" and "Primary Key" then
                        Error(Text000, "Field Caption");
                    if "Validate Field" then
                        ThrowErrorIfFieldRemoved;
                    UpdateFieldErrors;
                end;
            end;
        }

    [IntegrationEvent(false, false)]
    local procedure DINOnBeforeValidateFieldValidateField(var ConfigPackageField: Record "Config. Package Field"; var Ishandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
