### ISSUE TITLE
[Event request] codeunit 8618 "Config. Excel Exchange" OnBeforeCreateTableColumnNames

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#14312]
local procedure CreateTableColumnNames(var ConfigPackageField: Record "Config. Package Field"; var ConfigPackageTable: Record "Config. Package Table"; TableColumns: DotNet TableColumns)
    var
        "Field": Record "Field";
        Dimension: Record Dimension;
        XmlColumnProperties: DotNet XmlColumnProperties;
        TableColumn: DotNet TableColumn;
        WrkShtWriter2: DotNet WorksheetWriter;
        RecRef: RecordRef;
        FieldRef: FieldRef;
        TableColumnName: Text;
        ColumnID: Integer;
        DINIsHandled: Boolean;
    begin
        // DINNL <<
        DINIsHandled := false;
        DINOnBeforeCreateTableColumnNames(ConfigPackageField, ConfigPackageTable, TableColumns, DINIsHandled, TypeHelper, ConfigXMLExchange, WrkShtWriter, WrkShtHelper, OpenXMLManagement, StringBld);
        if DINIsHandled then
            exit;
        // DINNL >>
        RecRef.Open(ConfigPackageTable."Table ID");
        ConfigPackageField.SetCurrentKey("Package Code

    [IntegrationEvent(false, false)]
    local procedure DINOnBeforeCreateTableColumnNames(var ConfigPackageField: Record "Config. Package Field"; var ConfigPackageTable: Record "Config. Package Table"; TableColumns: DotNet TableColumns; var IsHandled: Boolean; var TypeHelper: Codeunit "Type Helper"; var ConfigXMLExchange: Codeunit "Config. XML Exchange"; var WrkShtWriter: DotNet WorksheetWriter; var WrkShtHelper: DotNet WorksheetHelper; var OpenXMLManagement: Codeunit "OpenXML Management"; var StringBld: DotNet StringBuilder)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
