### ISSUE TITLE
[Event Request] Codeunit 90 OnPostPurchLineOnAfterUpdatePurchLineBeforePost

### ISSUE THREAD

**Issue by GuntherGebauer** [Microsoft/ALAppExtensions#1431]
we Need a similar trigger as the trigger OnPostSalesLineOnAfterTestUpdatedSalesLine from codeunit 80 as well in codeunit 90:

PROCEDURE PostPurchLine
...
  TestPurchLine(PurchHeader,PurchLine);
  UpdatePurchLineBeforePost(PurchHeader,PurchLine);

  OnPostPurchLineOnAfterUpdatePurchLineBeforePost(VAR Purchline;VAR EverythingInvoiced);  <-- New Event trigger

  IF "Qty. to Invoice" + "Quantity Invoiced" <> Quantity THEN
    EverythingInvoiced := FALSE;

**Comment by AlexanderYakunin** [comment]
Another event already implemented for same purpose

  IF "Qty. to Invoice" + "Quantity Invoiced" <> Quantity THEN
    EverythingInvoiced := FALSE;

  OnPostPurchLineOnAfterSetEverythingInvoiced(PurchLine,EverythingInvoiced);
