### ISSUE TITLE
[Event Request] codeunit 8611 "Config. Package Management" OnBeforeApplyPackageRecords

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#14315]
local procedure ApplyPackageRecords(var ConfigPackageRecord: Record "Config. Package Record"; PackageCode: Code[20]; TableNo: Integer; ApplyMode: Option ,PrimaryKey,NonKeyFields)
    var
        ConfigPackageTable: Record "Config. Package Table";
        ConfigTableProcessingRule: Record "Config. Table Processing Rule";
        ConfigPackageMgt: Codeunit "Config. Package Management";
        ConfigProgressBarRecord: Codeunit "Config. Progress Bar";
        RecRef: RecordRef;
        RecordCount: Integer;
        StepCount: Integer;
        Counter: Integer;
        ProcessingRuleIsSet: Boolean;
        DINIsHandled: Boolean;
    begin
        // DINNL <<
        DINIsHandled := false;
        DINOnBeforeApplyPackageRecords(ConfigPackageRecord, PackageCode, TableNo, ApplyMode, ConfigPackageMgt, TempAppliedConfigPackageRecord, ProcessingRuleIsSet, TempConfigRecordForProcessing, ConfigTableProcessingRule, RecordsInsertedCount, RecordsModifiedCount, DINIsHandled, HideDialog);
        if DINIsHandled then
            exit;
        // DINNL >>       
        ConfigPackageTable.Get(PackageCode, TableNo);
        ProcessingRuleIsSet := ConfigTableProcessingRule.FindTableRules(ConfigPackageTable);

        ConfigPackageMgt.SetApplyMode(A

    [IntegrationEvent(false, false)]
    local procedure DINOnBeforeApplyPackageRecords(var ConfigPackageRecord: Record "Config. Package Record"; var PackageCode: Code[20]; var TableNo: Integer; var ApplyMode: Option ,PrimaryKey,NonKeyFields; var ConfigPackageMgt: Codeunit "Config. Package Management"; var TempAppliedConfigPackageRecord: Record "Config. Package Record" temporary; var ProcessingRuleIsSet: Boolean; var TempConfigRecordForProcessing: Record "Config. Record For Processing" temporary; var ConfigTableProcessingRule: Record "Config. Table Processing Rule"; var RecordsInsertedCount: Integer; var RecordsModifiedCount: Integer; var IsHandled: Boolean; var HideDialog: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
