### ISSUE TITLE
[Event Request] codeunit 8614 "Config. XML Exchange" OnBeforeCreateRecordNodes

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#14310]
local procedure CreateRecordNodes(var PackageXML: DotNet XmlDocument; ConfigPackageTable: Record "Config. Package Table")
    var
        "Field": Record "Field";
        ConfigPackageField: Record "Config. Package Field";
        ConfigPackage: Record "Config. Package";
        ConfigProgressBarRecord: Codeunit "Config. Progress Bar";
        DocumentElement: DotNet XmlNode;
        FieldNode: DotNet XmlNode;
        RecordNode: DotNet XmlNode;
        TableNode: DotNet XmlNode;
        TableIDNode: DotNet XmlNode;
        PackageCodeNode: DotNet XmlNode;
        RecRef: RecordRef;
        FieldRef: FieldRef;
        RecordCount: Integer;
        ProcessedRecordCount: Integer;
        StepCount: Integer;
        ExportMetadata: Boolean;
        ShowDialog: Boolean;
        DINIsHandled: Boolean;
    begin
        if ConfigMgt.IsSystemTable(ConfigPackageTable."Table ID") then
            exit;
        // DINNL <<
        DINIsHandled := false;
        DINOnBeforeCreateRecordNodes(ConfigPackageTable, ExcelMode, FieldNode, RecordNode, ConfigPackageField, PackageXML, DINIsHandled, HideDialog, TypeHelper, Advanced, XMLDOMMgt, WorkingFolder);
        if DINIsHandled then
            exit;
        // DINNL >>
        ConfigPackage

    [IntegrationEvent(false, false)]
    local procedure DINOnBeforeCreateRecordNodes(var ConfigPackageTable: Record "Config. Package Table"; var ExcelMode: Boolean; var FieldNode: DotNet XmlNode; var RecordNode: DotNet XmlNode; var ConfigPackageField: Record "Config. Package Field"; var PackageXML: DotNet XmlDocument; var Ishandled: Boolean; var HideDialog: Boolean; var TypeHelper: Codeunit "Type Helper"; var Advanced: Boolean; var XMLDOMMgt: Codeunit "XML DOM Management"; var WorkingFolder: Text)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
