### ISSUE TITLE
[Event Request]  codeunit 8614 "Config. XML Exchange" OnBeforeFillPackageDataFromXML

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#14311]
local procedure FillPackageDataFromXML(PackageCode: Code[20]; TableID: Integer; var TableNode: DotNet XmlNode)
    var
        ConfigPackageTable: Record "Config. Package Table";
        ConfigPackageData: Record "Config. Package Data";
        ConfigPackageRecord: Record "Config. Package Record";
        ConfigPackageField: Record "Config. Package Field";
        TempConfigPackageField: Record "Config. Package Field" temporary;
        ConfigProgressBarRecord: Codeunit "Config. Progress Bar";
        RecRef: RecordRef;
        FieldRef: FieldRef;
        RecordNodes: DotNet XmlNodeList;
        RecordNode: DotNet XmlNode;
        NodeCount: Integer;
        RecordCount: Integer;
        StepCount: Integer;
        ErrorText: Text[250];
        DINIsHandled: Boolean;
    begin
        if ConfigMgt.IsSystemTable(TableID) then
            exit;

        if ConfigPackageTable.Get(PackageCode, TableID) then begin
            ExcludeRemovedFields(ConfigPackageTable);
            if ExcelMode then begin
                ConfigPackageTable.CalcFields("No. of Package Records");
                if ConfigPackageTable."No. of Package Records" > 0 then
                    if Confirm(TableContainsRecordsQst, true, TableID, PackageCode, ConfigPackageTable."No. of Package Records") then
                        ConfigPackageTable.DeletePackageData
                    else
                        exit;
            end;
            ConfigPackageTable.CalcFields("Table Name");
            if not HideDialog then
                ConfigProgressBar.Update(ConfigPackageTable."Table Name");
            RecordNodes := TableNode.SelectNodes(GetElementName(ConfigPackageTable."Table Name"));
            RecordCount := RecordNodes.Count();

            if not HideDialog and (RecordCount > 1000) then begin
                StepCount := Round(RecordCount / 100, 1);
                ConfigProgressBarRecord.Init(RecordCount, StepCount,
                  StrSubstNo(RecordProgressTxt, ConfigPackageTable."Table Name"));
            end;

            ConfigPackageField.SetRange("Package Code", ConfigPackageTable."Package Code");
            ConfigPackageField.SetRange("Table ID", ConfigPackageTable."Table ID");
            ConfigPackageField.SetRange("Include Field", true);
            if ConfigPackageField.FindSet then
                repeat
                    TempConfigPackageField := ConfigPackageField;
                    TempConfigPackageField.Insert();
                until ConfigPackageField.Next() = 0;

            for NodeCount := 0 to RecordCount - 1 do begin
                RecordNode := RecordNodes.Item(NodeCount);
                if RecordNode.HasChildNodes then begin
                    ConfigPackageMgt.InitPackageRecord(ConfigPackageRecord, PackageCode, ConfigPackageTable."Table ID");

                    RecRef.Close;
                    RecRef.Open(ConfigPackageTable."Table ID");
                    if TempConfigPackageField.FindSet then
                        repeat
                            ConfigPackageData.Init();
                            ConfigPackageData."Package Code" := TempConfigPackageField."Package Code";
                            ConfigPackageData."Table ID" := TempConfigPackageField."Table ID";
                            ConfigPackageData."Field ID" := TempConfigPackageField."Field ID";
                            ConfigPackageData."No." := ConfigPackageRecord."No.";
                            if FieldNodeExists(RecordNode, TempConfigPackageField.GetElementName()) or
                               TempConfigPackageField.Dimension
                            then
                                GetConfigPackageDataValue(ConfigPackageData, RecordNode, TempConfigPackageField.GetElementName());
                            ConfigPackageData.Insert();

                            // DINNL <<
                            DINIsHandled := false;
                            DINOnBeforeFillPackageDataFromXML(ConfigPackageField, ConfigPackageData, ConfigPackageRecord, TempConfigPackageField, DINIsHandled);
                            if not DINIsHandled then
                                // DINNL >>
                                if not TempConfigPackageField.Dimension then begin
                                    FieldRef := RecRef.Field(ConfigPackageData."Field ID");
                                    if ConfigPackageData.Value <> '' then begin
                                        ErrorText := ConfigValidateMgt.EvaluateValue(FieldRef, ConfigPackageData.Value, not ExcelMode);
                                        if ErrorText <> '' then
                                            ConfigPackageMgt.FieldError(

    [IntegrationEvent(false, false)]
    local procedure DINOnBeforeFillPackageDataFromXML(var ConfigPackageField: Record "Config. Package Field"; var ConfigPackageData: Record "Config. Package Data"; var ConfigPackageRecord: Record "Config. Package Record"; var TempConfigPackageField: Record "Config. Package Field" temporary; var lIshandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
