### ISSUE TITLE
[Event Request] page 8626 "Config. Package Records"  OnAfterFindPackageFields

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#14316]
local procedure FindPackageFields(var ConfigPackageField: Record "Config. Package Field"): Boolean
    begin
        ConfigPackageField.SetRange("Package Code", PackageCode);
        ConfigPackageField.SetRange("Table ID", TableNo);
        if ErrorFieldNo = 0 then
            ConfigPackageField.SetRange("Include Field", true)
        else begin
            ConfigPackageField.FilterGroup(-1);
            ConfigPackageField.SetRange("Primary Key", true);
            ConfigPackageField.SetRange("Field ID", ErrorFieldNo);
            ConfigPackageField.FilterGroup(0);
        end;
        if not ShowDim then
            ConfigPackageField.SetRange(Dimension, false);
        // DINNL <<    
        DINOnAfterFindPackageFields(ConfigPackageField);
        // DINNL >>
        exit(ConfigPackageField.FindSet);
    end;

    [IntegrationEvent(false, false)]
    local procedure DINOnAfterFindPackageFields(var ConfigPackageField: Record "Config. Package Field")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
