### ISSUE TITLE
[Exposure request] codeunit 1262 "Pre & Post Process XML Import"

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#14328]
Please make the function SetValueFromDataExchField in the codeunit 1262 to be externally available.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
