### ISSUE TITLE
[Event modification] Event OnBeforeIssueReminder in codeunit 393 "Reminder-Issue"

### ISSUE THREAD

**Issue by AndreaRux** [microsoft/ALAppExtensions#14323]
Please add IssuedReminderHeader as var Parameter for Event OnBeforeIssueReminder 
Thanks in advance

codeunit 393 "Reminder-Issue"
{
    Permissions = TableData "Cust. Ledger Entry" = rm,
                  TableData "Issued Reminder Header" = rimd,
                  TableData "Issued Reminder Line" = rimd,
                  TableData "Reminder/Fin. Charge Entry" = rimd;
    trigger OnRun()
    var
        CustPostingGr: Record "Customer Posting Group";
        ReminderLine: Record "Reminder Line";
        ReminderFinChargeEntry: Record "Reminder/Fin. Charge Entry";
        ReminderCommentLine: Record "Reminder Comment Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeIssueReminder(ReminderHeader, ReplacePostingDate, PostingDate, IsHandled, **_IssuedReminderHeader_**);
        if IsHandled then
            exit;
.
    [IntegrationEvent(false, false)]
    local procedure OnBeforeIssueReminder(var ReminderHeader: Record "Reminder Header"; var ReplacePostingDate: Boolean; var PostingDate: Date; var IsHandled: Boolean; **_var  _IssuedReminderHeader_: Record "Issued Reminder Header"_**)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
