### ISSUE TITLE
[Request for External] Page 7139 "Sales Budget Overview" CurrentBudgetName and PeriodType

### ISSUE THREAD

**Issue by hemmsi** [microsoft/ALAppExtensions#14326]
Please make the global variables __CurrentBudgetName__ and __PeriodType__ protected. 

```
protected var
    CurrentBudgetName: Code[10];
    PeriodType: Option Day,Week,Month,Quarter,Year,"Accounting Period";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
