### ISSUE TITLE
[Event Request] Codeunit 7201 "CDS Integration Impl.": OnBeforeLCYMustMatchBaseCurrencyErr

### ISSUE THREAD

**Issue by deadmouse** [microsoft/ALAppExtensions#14331]
[Event Request] Codeunit 7201 "CDS Integration Impl.": OnBeforeLCYMustMatchBaseCurrencyErr

We would need to skip this verification, since we use Dataverse to extract Business Central data from companies with different currencies and currently we are unable to do this.

```
local procedure SyncCompany(var CDSConnectionSetup: Record "CDS Connection Setup"; AdminUserName: Text; AdminPassword: Text; AccessToken: Text; AdminADDomain: Text)
.
.
.
if DelChr(CRMTransactioncurrency.ISOCurrencyCode) <> DelChr(GeneralLedgerSetup."LCY Code") then begin
	Session.LogMessage('0000ASL', CurrencyMismatchTxt, Verbosity::Normal, DataClassification::SystemMetadata, TelemetryScope::ExtensionPublisher, 'Category', CategoryTok);
	///////// START
	IsHandled := false;
	OnBeforeLCYMustMatchBaseCurrencyErr(IsHandled);
	if not IsHandled then
	///////// END
		Error(LCYMustMatchBaseCurrencyErr, GeneralLedgerSetup."LCY Code", CRMTransactioncurrency.ISOCurrencyCode);	
end;
```

Signature:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeLCYMustMatchBaseCurrencyErr(var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
