### ISSUE TITLE
[Event Request] Table 77 "Report Selections" - OnBeforeBLOBImportFromServerFile

### ISSUE THREAD

**Issue by gtrennert** [microsoft/ALAppExtensions#14336]
Hi, would it be possible to get an OnBeforeBLOBImportFromServerFile event in table 77 (report Selections) ?
We need this to attach documents merged with spécific PDF documents

**Comment by AlexanderYakunin** [comment]
Please provide definition of required event and there it should be added in the code.

**Comment by gtrennert** [comment]
Could be like this : 
`procedure SaveAsDocumentAttachment(ReportUsage: Integer; RecordVariant: Variant; DocumentNo: Code[20]; AccountNo: Code[20]; ShowNotificationAction: Boolean)
    ...
    begin
    ...
        with TempAttachReportSelections do
            repeat
                if CanSaveReportAsPDF(TempAttachReportSelections."Report ID") then begin
                    IsHandled := false;
                    OnBeforeBLOBImportFromServerFile(RecordVariant: Variant; TempAttachReportSelections: Record "Report Selections"; var IsHandled: Boolean)

                    if not IsHandled then
                        FileManagement.BLOBImportFromServerFile(
                            TempBlob,
                            SaveReportAsPDF("Report ID", RecordVariant, "Custom Report Layout Code", "Report Selection Usage".FromInteger(ReportUsage)));

                    SaveDocumentAttachmentFromRecRef(RecRef, TempAttachReportSelections, DocumentNo, AccountNo, TempBlob, NumberOfReportsAttached);
                end;
            until Next() = 0;
`

**Comment by Oleg-Romashkov** [comment]
Is it ok for you to use existent event OnBeforeSaveDocumentAttachmentFromRecRef for SaveDocumentAttachmentFromRecRef function?

**Comment by DavidFeldhoff** [comment]
Just saw this issue. We asked in the linked issue to not use BLOBImportFromServerFile in this case and use the cloud compliant solution instead where we could completely swap the Blob content. Maybe that would work as well? 
https://github.com/microsoft/ALAppExtensions/issues/14356

**Comment by gtrennert** [comment]
@Oleg-Romashkov 
Maybe - I'm just trying to do this - Only there is one thing that is missing at this moment : 
The event 
`OnBeforeSaveDocumentAttachmentFromRecRef(RecRef, TempAttachReportSelections, DocumentNo, AccountNo, TempBlob, IsHandled);`
does not contain the variable NumberOfReportsAttached as a VAR Parameter - and so I get wrong notification
Is it possible to add this parameter ?
 
@DavidFeldhoff 
What do you mean by "use the cloud compliant solution" ?

**Comment by DavidFeldhoff** [comment]
Not relevant, I just re-read your case and had to notice that the idea I posted is not helpful here in your case, sorry :)

**Comment by gtrennert** [comment]
@Oleg-Romashkov
After testing i'm able to subscribe and do my merging job by using the event OnBeforeSaveDocumentAttachmentFromRecRef you proposed.
As I said the only thing missing is variable NumberOfReportsAttached as a VAR Parameter - Could this be done ?

**Comment by Oleg-Romashkov** [comment]
Yes, sure. I will do this then.

**Comment by gtrennert** [comment]
Thanks a lot ! 
What do you think in which version this will be available ?

**Comment by Oleg-Romashkov** [comment]
Usually we do not provide this information. Hopefully it will be in 18.6 and 19.1

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
