### ISSUE TITLE
[EventRequest] OnAfterInsertSalesCrMemoHeader in report 6653 "Combine Return Receipts"

### ISSUE THREAD

**Issue by TriangleSPV** [microsoft/ALAppExtensions#14335]
In the report 6653 "Combine Return Receipts" we need the event OnAfterInsertSalesCrMemoHeader similar than the
OnAfterInsertSalesInvHeader of the report 295 "Combine Shipments".

The only difference will be the 2nd parameter of new event, that must we related to the table "Return Receipt Header" instead of the "Sales Shipment Header".

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
