### ISSUE TITLE
[Event Request And Code] incomplete Implementation of request #13105 in Page "99000883 Sales Order Planning"

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#14337]
As requested in #13105 we needed a publisher to decide if we want to use the SetSelectionFilter of "CurrPage" to be able to create production orders only for some selected saleslines and not for all of them!

This was the original request:

local procedure CreateOrders() OrdersCreated: Boolean
var
 ....
begin
    xSalesPlanLine := Rec;

    // ###########  event request and code #############
    OnBeforeCurrPageSetSelectionFilter(ApplySetSelectionFilter);
    if ApplySetSelectionFilter then
        CurrPage.SetSelectionFilter(Rec);
    // ###########  event request and code #############

...
    Rec := xSalesPlanLine;
end;

You missed the **"if ApplySetSelectionFilter then CurrPage.SetSelectionFilter(Rec)"** in your implementation.
Unfortunately with your current implementation it is not possible to do the needed action.

Can you please review this and give me an info about this?

Thanks

**Comment by Oleg-Romashkov** [comment]
Event OnCreateOrdersOnBeforeFindSet is declared with IncludeSender= true
So, you can subscribe on it like this:
```

    [EventSubscriber(ObjectType::Page, 99000883, 'OnCreateOrdersOnBeforeFindSet', '', false, false)]
    local procedure OnCreateOrdersOnBeforeFindSet(var Sender: Page "Sales Order Planning"; var SalesPlanningLine: Record "Sales Planning Line")
    var
        SalesPlanningLine2: Record "Sales Planning Line";
    begin
        Sender.SetSelectionFilter(SalesPlanningLine2);
        // do some logic with SalesPlanningLine2
    end;

```
Does it solve your problem?

**Comment by AndreBreitenbach** [comment]
Perfect Tip with IncludeSender. I did not had this in mind!
Thanks a lot!
