### ISSUE TITLE
Expose Sent Email Message Id Through Function

### ISSUE THREAD

**Issue by Darren-OO** [microsoft/ALAppExtensions#14343]
Hi,

Would it be possible to expose the Sent Email Message Id using a Get function?

I want to copy email relations from Purchase Header to Purch. Rcpt. Header and Purch. Inv. Header on posting. The intention is to be able to navigate to a sent email from the Posted Purchase Invoice where the original email was sent from the Purchase Order.
Something like:

    local procedure PurchPost_OnAfterPurchRcptHeaderInsert(var PurchaseHeader: Record "Purchase Header"; var PurchRcptHeader: Record "Purch. Rcpt. Header")
    var
        TempSentEmail: Record "Sent Email" temporary;
        Email: Codeunit Email;
        EmailMessage: Codeunit "Email Message";
        EmailRelationType: Enum "Email Relation Type";
    begin
        TempSentEmail := Email.GetSentEmailsForRecord(Database::"Purchase Header", PurchaseHeader.SystemId);
        if TempSentEmail.FindSet() then
            repeat
                EmailMessage.Get(TempSentEmail.GetMessageId());
                Email.AddRelation(EmailMessage, Database::"Purch. Rcpt. Header", PurchRcptHeader.SystemId, EmailRelationType::"Related Entity");
            until TempSentEmail.Next() = 0;
    end;

**Comment by mazhelez** [comment]
Hey @Darren-OO 

Interesting idea you have there! How do you feel like contributing functionality that would help you implement your solution?

My understanding is that you just want to transfer sent emails from one record to another. So why not implement a `TransferRelatedEmails(SourceRecordVariant: Variant; DestinationRecordVariant: Variant;)` or just `CopyRelatedEmails`?

Let me know in case you have more questions :)
