### ISSUE TITLE
Codeunit 31000 "Sales-Post Advances".GetInvCurrFactor

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#14350]
Please remove local from function.
```
//local procedure GetInvCurrFactor(LetterNo: Code[20]): Decimal
procedure GetInvCurrFactor(LetterNo: Code[20]): Decimal
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
