### ISSUE TITLE
Report 190 "Issue Reminders" - Add "Protected var" on PostingDateReq variable

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#14357]
```
NewDateTime: DateTime;
  OldDateTime: DateTime;
  Protected var
  PostingDateReq: Date;
  ReplacePostingDate: Boolean;
  PrintDoc: Option " ",Print,Email;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
