### ISSUE TITLE
[Request for External] page 5415 "Item Avail. by Variant Lines" Global Var Item

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#14379]
var 
        // Item: Record Item; // DINNL
        ItemAvailFormsMgt: Codeunit "Item Availability Forms Mgt";
        ExpectedInventory: Decimal;
        QtyAvailable: Decimal;
        AmountType: Option "Net Change","Balance at Date";
        PlannedOrderReleases: Decimal;
        GrossRequirement: Decimal;
        PlannedOrderRcpt: Decimal;
        ScheduledRcpt: Decimal;
        ProjAvailableBalance: Decimal;
        PeriodStart: Date;
        PeriodEnd: Date;

    protected var 
        Item: Record Item; // DINNL

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
