### ISSUE TITLE
[Request for External] page 5540 "Item Availability by Timeline"

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#14378]
var 
        Item: Record Item;
        TempTimelineEvent: Record "Timeline Event" temporary;
        CalcItemAvailTimeline: Codeunit "Calc. Item Avail. Timeline";
        ItemNo: Code[20];
        LocationFilter: Text;
        VariantFilter: Text;
        [InDataSet]
        ForecastName: Code[10];
        TemplateNameNewSupply: Code[10];
        WorksheetNameNewSupply: Code[10];
        Description: Text[250];
        ActionMsg: Enum "Action Message Type";
        State: Option " ",Initialized,"Unsaved Changes";
        LastUpdateTime: DateTime;
        //[InDataSet] // DINNL 
        //IncludeBlanketOrders: Boolean; // DINNL
        Text001: Label 'The changes have been saved to the planning or requisition worksheet.';
        CurrReferenceNo: Text[200];
        BlockCurrRecNotifications: Boolean;
        Text002: Label 'The changes have been saved to the planning or requisition worksheet.\\New supply is saved to worksheet Template Name %1, Batch Name %2, Location Code %3, and Variant Code %4.';
        Text003: Label 'All unsaved changes will not be saved. Are you sure that you want to close the window?';
        Text004: Label 'Show Projected Available Balance';
        Text005: Label 'Include Planning Suggestions';
        Text006: Label 'Workdate';
        Text007: Label 'Today';
        IgnoreChanges: Boolean;
        [InDataSet]
        ItemSelected: Boolean;
        Text008: Label 'New Supply %1';
        Text009: Label 'Do you want to delete?';

    protected var
        [InDataSet] // DINNL 
        IncludeBlanketOrders: Boolean; // DINNL

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
