### ISSUE TITLE
SubPageLink Enums

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#14372]
**1. Describe the bug**
Using the SubPageLink on a Factbox with a field that has a filter from an enum to an option you get warning AL0603, and eventually become an error.  So for example mine is using Sales Header Document Type and going to Reservation Entry Source Subtype.  

![image](https://user-images.githubusercontent.com/32099690/133811883-f95286fc-de82-4bd1-90af-553d611d2ded.png)

**2. To Reproduce**
Use a Subpage Link that has a filter that goes from Enum to Option.

**3. Expected behavior**
Is this something we have to use Pragma for or is this something that will become an error? since this is a base application table, I cannot change the option to an enum.

**4. Actual behavior**
You get a warning

**5. Versions:**

- AL Language: 8.1.516714
- Visual Studio Code:1.60.1
- Business Central: BC18
- List of Visual Studio Code extensions that you have installed:

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
