### ISSUE TITLE
[Event Request] Add OnAfterUpdate in Codeunit 7021 "Purchase Line - Price"

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#14389]
Hello, please consider adding the following event to `codeunit 7021 "Purchase Line - Price"`:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdate(var PurchaseLine: Record "Purchase Line"; CurrPriceType: Enum "Price Type"; AmountType: Enum "Price Amount Type")
    begin
    end;
```

and raise it in the `Update` procedure:

```
    procedure Update(AmountType: enum "Price Amount Type")
    begin
        if not DiscountIsAllowed then
            PurchaseLine."Line Discount %" := 0;

        OnAfterUpdate(PurchaseLine, CurrPriceType, AmountType);
    end;
```

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
