### ISSUE TITLE
[Event Request] Reminder Header - procedure InsertLines - after calculating additional fee

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#14383]
We would like to have a new event OnInsertLinesOnAfterGetAdditionalFee in procedure InsertLines in table Reminder Header

```
    procedure InsertLines()
    ........
        if ReminderLevel.FindLast then begin
            CalcFields("Remaining Amount");
            AdditionalFee := ReminderLevel.GetAdditionalFee("Remaining Amount", "Currency Code", false, "Posting Date");
            OnInsertLinesOnAfterGetAdditionalFee(Rec, ReminderLevel, AdditionalFee); // <-- NEW EVENT

            if AdditionalFee > 0 then begin
                ReminderLine.Reset();
            ......

    [IntegrationEvent(false, false)]
    local procedure OnInsertLinesOnAfterGetAdditionalFee(var ReminderHeader: Record "Reminder Header"; ReminderLevel: Record "Reminder Level"; var AdditionalFee: Decimal)
    begin
    end;
```

With this event, we can calculate additional fees based on certain settings.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
