### ISSUE TITLE
[Event Request] Reminder Header - procedure InsertLines - before insert additional fee line

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#14382]
We would like to have a new event OnBeforeInsertReminderAdditionalFeeLine in procedure InsertLines in table Reminder Header.

The existing event OnBeforeInsertReminderLine does not work because this event is called in multiple places. We need an event specifically for additional fee, which includes the current Reminder Header record.

The event OnBeforeInsertReminderTextLine does not work either. This seems to be a bug, see also issue #14381 

```
    procedure InsertLines()
    ........
                ReminderLine.Validate(Amount, AdditionalFee);
                ReminderLine."Line Type" := ReminderLine."Line Type"::"Additional Fee";
                OnBeforeInsertReminderTextLine(ReminderLine, ReminderText, ReminderHeader); // <-- incorrect event? ReminderHeader parameter will be empty
                OnBeforeInsertReminderAdditionalFeeLine(ReminderLine, Rec); // <-- NEW EVENT
                OnBeforeInsertReminderLine(ReminderLine);
                ReminderLine.Insert();
                if TransferExtendedText.ReminderCheckIfAnyExtText(ReminderLine, false) then
                    TransferExtendedText.InsertReminderExtText(ReminderLine);
                ........

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertReminderAdditionalFeeLine(var ReminderLine: Record "Reminder Line"; var ReminderHeader: Record "Reminder Header")
    begin
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
