### ISSUE TITLE
[Event Request] Add OnAfterUpdate in Codeunit 7020 "Sales Line - Price"

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#14388]
Hello, please consider adding the following event to `codeunit 7020 "Sales Line - Price"`:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdate(var SalesLine: Record "Sales Line"; CurrPriceType: Enum "Price Type"; AmountType: Enum "Price Amount Type")
    begin
    end;
```

and raise it in the `Update` procedure:

```
    procedure Update(AmountType: enum "Price Amount Type")
    begin
        if not SalesLine."Allow Line Disc." then
            SalesLine."Line Discount %" := 0;

        OnAfterUpdate(SalesLine, CurrPriceType, AmountType);
    end;
```

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
