### ISSUE TITLE
[Scope Change Request] codeunit 2310 "O365 Sales Invoice Mgmt" - GetPaymentInstructionsFromPostedInvoice

### ISSUE THREAD

**Issue by Meximity** [microsoft/ALAppExtensions#14384]
Hi, 

We'd like to request the removal of the `[Scope('OnPrem')]` for the function GetPaymentInstructionsFromPostedInvoice in Codeunit "O365 Sales Invoice Mgmt".
I'm not sure if this is intended that the scope is set to onprem, but copying the function as an own we can publish it with target cloud just fine, so nothing that should break the cloud logic behind this. 

```al
    [Scope('OnPrem')]
    procedure GetPaymentInstructionsFromPostedInvoice(SalesInvoiceHeader: Record "Sales Invoice Header"): Text
    var
        TypeHelper: Codeunit "Type Helper";
        InStream: InStream;
    begin
        SalesInvoiceHeader.CalcFields("Payment Instructions");
        if not SalesInvoiceHeader."Payment Instructions".HasValue then
            exit('');

        SalesInvoiceHeader."Payment Instructions".CreateInStream(InStream, TEXTENCODING::Windows);
        exit(TypeHelper.ReadAsTextWithSeparator(InStream, TypeHelper.LFSeparator));
    end;
```

**Comment by AlexanderYakunin** [comment]
Please let us know which version to you have? This objects belongs to Invoicing, which is discontinued time ago.

**Comment by Meximity** [comment]
Hi,

Thanks for the response!

We're currently on 18.4 and trying to build our app against targeting cloud, this is why this came up. In the 18.4 base application it seems that this is still available and not tagged as obsolete as far as I've seen, this is why I haven't questioned it yet.

I had a talk with my team about this and decided to also remove it, so this change isn't necessary anymore.
