### ISSUE TITLE
[Extensibility-Bug] Interface "Line With Price" doesn't allow to work with temporary records

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#14380]
Hello, I think there may be an issue with the two `SetLine` overloads in the `interface "Line With Price"` (and in all standard codeunits which implement this interface).

```
    /// <summary>
    /// Setup the internal record line. Applicable for the journal lines that does not have a header record.
    /// The PriceType parameter defines what type of price is going to be calculated.
    /// </summary>
    /// <param name="PriceType">the price type for which the price or discount will be calculated.</param>
    /// <param name="Line">the source record line</param>
    procedure SetLine(PriceType: Enum "Price Type"; Line: Variant)

    /// <summary>
    /// Setup the internal records - line and header. Applicable for the document lines.
    /// The PriceType parameter defines what type of price is going to be calculated.
    /// </summary>
    /// <param name="PriceType">the price type for which the price or discount will be calculated.</param>
    /// <param name="Header">the source record header</param>
    /// <param name="Line">the source record line</param>
    procedure SetLine(PriceType: Enum "Price Type"; Header: Variant; Line: Variant)
```

I need to work with temporary variables. The `Header` and `Line` parameters are not passed by var, so when I call the other methods of the interface, they do not treat the variables as temporary, resulting in unexpected behavior.

Please fix these methods and all their implementations, or alternatively implement new ones that would allow us to pass temporary variables to be treated as such.

**Comment by StanPesotskiy** [comment]
The only way to extend an interface is to introduce another interface that will include all methods of the existing one.
I would need more information of what you are doing so you can't use the existing implementation, e.g. by using temp records in real tables.

**Comment by f0ffee** [comment]
I'll try to further describe our particular issue.

Our ISV solution currently works for both V.15 and V.16 implementations with two separate chunks of code.

In the code for V.15 we have this subscriber: `[EventSubscriber(ObjectType::Codeunit, Codeunit::"Purch. Price Calc. Mgt.", 'OnBeforeFindPurchLineLineDisc', '', false, false)],` where we check that the `Purchase Header` and `Purchase Line` records are not temporary before executing our code.

A delivery developer opened an issue with us because he called the `SetLine` procedure declared in the interface, and they saw that our ISV code still executed even though he called the procedure for a temporary document line. As I mentioned, the `Line` variant is not passed by var and so the information on it being temporary is lost.

As a temporary (no pun intended) workaround, since for their particular customer they are still using the V.15 implementation (actually, I believe they haven't yet turned on the new sales price feature at all), I recommended they call the old procedure from the old codeunit, which means they are still going to be in technical debt when they turn on the feature and switch to the V.16 implementation.

I believe there are many cases for having temporary document lines for which we still want to retrieve prices and discounts, but right now the interface doesn't seem to allow it. If I'm wrong, I will be very happy to stand corrected.

Please let me know if you need any more information

**Comment by StanPesotskiy** [comment]
@f0ffee I understand the issue, the solution is not clear yet.

**Comment by f0ffee** [comment]
To add to this: the problems increase when you take into consideration the fact that, by not passing the Sales Line (for example) as var, you lose all the information on any global variables for this record, namely `HideValidationDialog` and `StatusCheckSuspended`. This issue needs to be addressed as soon as possible.

**Comment by dnpb** [comment]
I don't think the lack of `var` is a problem, but rather that when a record is put through a `Variant`, it keeps its filters and such but evidently **not** its global variables.

Receiving as `var Variant` would not work as then the callers would have to really pass `Variant`s; they couldn't pass records in order to convert the records to variants.

**Comment by dnpb** [comment]
This code shows that the filter is preserved via `Variant` but the value of the global `HideValidationDialog: Boolean` is not:
```al
pageextension 50101 Test extends "Customer List"
{
    trigger OnOpenPage()
    var
        SalesLine: Record "Sales Line";
    begin
        SalesLine.SetRange(Type, SalesLine.Type::" ");
        SalesLine.SetHideValidationDialog(true);
        Foo(SalesLine);
    end;

    local procedure Foo(RecordVariant: Variant)
    var
        SalesLine: Record "Sales Line";
        RecordRef: RecordRef;
    begin
        RecordRef.GetTable(RecordVariant);
        RecordRef.SetTable(SalesLine);
        Message('%1, %2', RecordRef.GetFilters(), SalesLine.GetHideValidationDialog());
    end;
}
```

result:
![image](https://user-images.githubusercontent.com/63455896/146961687-4a37da28-ab15-454a-88db-e5c2573b8569.png)

If `Foo()` takes a `var` `Variant`, it won't compile:
![image](https://user-images.githubusercontent.com/63455896/146961794-9f32f9dd-cf31-496e-8a41-af0885a7a50d.png)

**Comment by dnpb** [comment]
I don't know what the fix would be, but it would evidently not be to just add `var`. It also will not suffice to get the records back out of the `Variant`s via `RecordRef` instead of by `:=` assigning, since apparently the mere act of putting them into the `Variant` in the first place clears the globals (yet **not** the filters... I thought it'd be all or nothing)

You might need to e.g. add 'dummy' fields or filters on the involved records, to mark them as being temporary or to otherwise store the other state you need, which the `Variant` loses. Then you can read those later and act accordingly, since the fields and filters are preserved OK.

It looks like MS didn't think about supporting this much state via the interface, so you might have to make it work for yourself.

**Comment by StanPesotskiy** [comment]
An assignment of a record variable to another record variable as well as assignment of a variant to a record and back do not copy internal global variables. Even if we could avoid conversion to and from a variant variable the internal state is not passed anyway. 
The only way to keep it is to work with the original variable passed by var. It is not possible with the new pricing engine (without a big redesign) as there are intermediate variables used to store line's content.

The approach to pass such data through is to extend "Sales Line" table with new fields, or add a special dedicated table, or a single instance codeunit.

You can create an idea on https://aka.ms/bcideas so we would see if this is not only your problem, but important for many.

**Comment by pri-kise** [comment]
Created Idea for future Reference: https://experience.dynamics.com/ideas/idea/?ideaid=d1beca69-d3f6-ec11-b5cf-0003ff45e64b
