### ISSUE TITLE
Missing event

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#14386]
Hello, 

In BC18.5 this event: https://github.com/microsoft/ALAppExtensions/issues/13941 is not available. 

The other ones are (same kind of request): 

https://github.com/microsoft/ALAppExtensions/issues/13938
https://github.com/microsoft/ALAppExtensions/issues/13939
https://github.com/microsoft/ALAppExtensions/issues/13940

**Comment by Oleg-Romashkov** [comment]
Codeunit 5814 "Undo Return Shipment Line" has been updated accordingly request #13941. Seems the problem is about codeunit 5816 "Undo Return Receipt Line" which actually was not mentioned.

**Comment by leegeurts** [comment]
Oleg, Seems you are right, I mixed up the Github ID's in my own spreadsheet. 


codeunit 5816 "Undo Return Receipt Line"

            ItemJnlLine."Bin Code" := "Bin Code";
            ItemJnlLine.Quantity := Quantity;
            ItemJnlLine."Quantity (Base)" := "Quantity (Base)";
            ItemJnlLine."Unit of Measure Code" := "Unit of Measure Code";
            ItemJnlLine."Qty. per Unit of Measure" := "Qty. per Unit of Measure";
            ItemJnlLine."Document Date" := ReturnRcptHeader."Document Date";

            OnAfterCopyItemJnlLineFromReturnRcpt(ItemJnlLine, ReturnRcptHeader, ReturnRcptLine);

            // DINNL <<
            DINOnBeforeWhseUndoQtyInsertTempWhseJnlLine(ReturnRcptLine, WhseUndoQty);
            // DINNL >>
            WhseUndoQty.InsertTempWhseJnlLine(
                ItemJnlLine,
                DATABASE::"Sales Line", SalesLine."Document Type"::"Return Order".AsInteger(), "Return Order No.", "Return Order Line No.",
                TempWhseJnlLine."Reference Document"::"Posted Rtrn. Rcpt.", TempWhseJnlLine, NextLineNo);

            if "Item Rcpt. Entry No." <> 0 then begin
                ItemJnlPostLine.Run(ItemJnlLine);
                exit(ItemJnlLine."Item Shpt. Entry No.");
            end;
            UndoPostingMgt.CollectItemLedgEntries(


    [IntegrationEvent(false, false)]
    local procedure DINOnBeforeWhseUndoQtyInsertTempWhseJnlLine(var ReturnRcptLine: Record "Return Receipt Line"; var WhseUndoQty: Codeunit "Whse. Undo Quantity")
    begin
    end;

So we do need those extra parameters on OnAfterCopyItemJnlLineFromReturnRcpt

Sorry for the confusion :) Thanks for your reply

**Comment by Oleg-Romashkov** [comment]
NP. 
It will be realized like similar events before:
OnAfterCopyItemJnlLineFromReturnRcpt(ItemJnlLine, ReturnRcptHeader, ReturnRcptLine, WhseUndoQty);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
