### ISSUE TITLE
[Bug] Event OnBeforeInsertReminderTextLine in Reminder Header procedure InsertLines

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#14381]
The call to event OnBeforeInsertReminderTextLine in procedure InsertLines in table "Reminder Header" seems to be a bug.

The event is not logical in the first place because there is no text line being inserted at that point. The code is inserting an additional fee line instead.
On top of that, the parameter ReminderHeader that is passed with the event will be empty in this case. It is not initialized in the function and it will not be initialized by earlier function calls either.

```
    procedure InsertLines()
    ........
                ReminderLine.Validate(Amount, AdditionalFee);
                ReminderLine."Line Type" := ReminderLine."Line Type"::"Additional Fee";
                OnBeforeInsertReminderTextLine(ReminderLine, ReminderText, ReminderHeader); // <-- incorrect event? ReminderHeader parameter will be empty
                OnBeforeInsertReminderLine(ReminderLine);
                ReminderLine.Insert();
    ........

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
