### ISSUE TITLE
[Event Request] - table 39 "Purchase Line" - OnGetDeferralPostDate

### ISSUE THREAD

**Issue by ddagkappeler** [microsoft/ALAppExtensions#14399]
You have made a mistake in the conversion (https://github.com/microsoft/ALAppExtensions/issues/13736). I can adjust the "DeferralPostDate" now, but after that it will be overwritten right away.  

![image](https://user-images.githubusercontent.com/45654195/134141966-bf539e2f-c325-4b61-89a5-872bf671e175.png)

    procedure UpdateDeferralAmounts()
    var
        DeferralPostDate: Date;
        AdjustStartDate: Boolean;
    begin
        GetPurchHeader;
        OnUpdateDeferralAmountsOnBeforeSetDeferralPostDate(PurchHeader, Rec, DeferralPostDate);
        >>>NEW CODE
       if DeferralPostDate = 0D then
       <<< NEW CODE
        DeferralPostDate := PurchHeader."Posting Date";
        AdjustStartDate := true;
        if "Document Type" = "Document Type"::"Return Order" then begin
            if "Returns Deferral Start Date" = 0D then
                "Returns Deferral Start Date" := PurchHeader."Posting Date";
            DeferralPostDate := "Returns Deferral Start Date";
            AdjustStartDate := false;
        end;

        DeferralUtilities.RemoveOrSetDeferralSchedule(
            "Deferral Code", "Deferral Document Type"::Purchase.AsInteger(), '', '',
            "Document Type".AsInteger(), "Document No.", "Line No.",
            GetDeferralAmount(), DeferralPostDate, Description, PurchHeader."Currency Code", AdjustStartDate);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
