### ISSUE TITLE
Events to handle the creation and open of Links from the Standard Links in the Web Client

### ISSUE THREAD

**Issue by BenjaminHochstetter** [microsoft/ALAppExtensions#14397]
Hello together,

Please add some Events to handle the creation and open of links from the Standard Links in the Web Client.

NAV 2018 / BC 14: 
We need an event to override the Validation of the "Link adress" during the creation of a link, this is not possible in the Web Client.

NAV 2018 .. BC 18:
We need an event to handle links which are located on the local file system for the creation and open of links.

[T200956666 - Test Web Client und Links.docx](https://github.com/microsoft/ALAppExtensions/files/7200826/T200956666.-.Test.Web.Client.und.Links.docx)

Thanks in advance,
Benjamin

**Comment by Stepanenko-Vadim** [comment]
This is not something AlAppExtensions team can help with.
You can try submitting this at BC Ideas at https://aka.ms/bcideas 
Or maybe you could submit this request at ALModernDev repo. But I would suggest that you log it at IDEAS site first.
