### ISSUE TITLE
[Bug] Total Var Mfg. Ovhd. Cost Amt. textbox in the RDLC layout references an incorrect field from the report

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#14396]
Hi Microsoft AL Development Team,

We found a bug while modifying the base application.

In the report 1002 "Post Inventory Cost to G/L", there is a field for **TotalVarMfgOvhdCostAmt**.
![image](https://user-images.githubusercontent.com/69611495/134105596-7b3d8f12-271a-4bf3-b5fd-4402ea8130fa.png)

The TextBox with the name = **textbox246** is used to display its value in the layout file "PostInventoryCosttoGL.rdlc" but the value is referencing the **TotalOvhdCostAmt** field instead of the **TotalVarMfgOvhdCostAmt** field.
![image](https://user-images.githubusercontent.com/69611495/134105648-32f8487f-e056-4e9b-a6e4-b3e2c5341f87.png)

This needs to be changed to **TotalVarMfgOvhdCostAmt**
![image](https://user-images.githubusercontent.com/69611495/134105899-35272429-8a0e-4f81-843d-f8df492088a7.png)

Kind regards,
Tuan Nguyen

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
