### ISSUE TITLE
[Event Request] codeunit 5817 "Undo Posting Management" - New event OnUpdatePurchLineOnBeforeInitOustanding

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#14391]
Hi,
we need an event OnUpdatePurchLineOnBeforeInitOustanding, similar to the one already present for Sales. It would be useful to add the source record (that means for example Purchase Receipt) in order to have all information related to any customization and let us to update PurchLine according to our customization.
Now I'm not able to retrieve information about the correction except UndoQty passed as parameter. Having Purchase Receipt Line record would help us to update other custom fields.

As suggestion:

UpdatePurchLine function call in "Undo Posting Management" codeunit: add SourcePostedDoc: variant (PurchRcptLine in my example) record as parameter
UndoPostingMgt.UpdatePurchLine call in "Undo Purchase Receipt Line" codeunit: pass PurchRcptLine record for SourcePostedDoc parameter
OnUpdatePurchLineOnBeforeInitOustanding event in "Undo Posting Management": pass new parameter SourcePostedDoc received

this issue is related to another opened by me for sales area: #14373

I hope that our need is clear.
Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
