### ISSUE TITLE
[Event Request] Codeunit "Requisition Line - Price" event for AddSources()

### ISSUE THREAD

**Issue by shuyusheng** [microsoft/ALAppExtensions#14408]
Could we please have an event at the end of AddSource() similar to codeunits such as "Purchase Line - Price".

```
local procedure AddSources()
var
    SourceType: Enum "Price Source Type";
begin
    PriceSourceList.Init();
    PriceSourceList.Add(SourceType::Vendor, RequisitionLine."Vendor No.");
    
    OnAfterAddSources(RequisitionLine, CurrPriceType, PriceSourceList);
end;

[IntegrationEvent(false, false)]
local procedure OnAfterAddSources(RequisitionLine: Record "Requisition Line"; PriceType: Enum "Price Type"; var PriceSourceList: Codeunit "Price Source List")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
