### ISSUE TITLE
[EventRequest] Codeunit 80 "Sales Post" - OnBeforeCheckMandatoryCustNoFields

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#14405]
Hello,

We created an event request OnBeforeCheckMandatoryCustNoFields for codeunit 80 "Sales Post" in https://github.com/microsoft/ALAppExtensions/issues/10847.
It was approved, but we don't find it in our current version 18.4, neither in version 19.

Can you please let us know if it will implemented?

Thank you!

**Comment by Stepanenko-Vadim** [comment]
This has been implemented as **OnBeforeCheckMandatoryHeaderFields** which is at the start of the procedure.
It doesn't wrap only the two testfields, but you can only test the fields you want in the subscriber and just handle to skip the rest.
