### ISSUE TITLE
[Parameter Request] codeunit 1371 "Sales Batch Post Mgt." - OnAfterPrepareSalesHeader

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#14401]
Could you please add the global `Codeunit  BatchProcessingMgt` as Parameter to thisevent?

```al
[IntegrationEvent(false, false)]
//local procedure OnAfterPrepareSalesHeader(var SalesHeader: Record "Sales Header") //OLD
local procedure OnAfterPrepareSalesHeader(var SalesHeader: Record "Sales Header"; var BatchProcessingMgt: Codeunit "Batch Processing Mgt.") //NEW
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
