### ISSUE TITLE
[Event Request] CU1510 OnBeforeGetDocumentTypeAndNumber

### ISSUE THREAD

**Issue by SteveyN** [Microsoft/ALAppExtensions#1440]
In CU 1510 Notification Management, function GetDocumentTypeAndNumber has an event OnGetDocumentTypeAndNumber to handle tables that aren't included in the function.

Does not however allow us to replace the DocumentType and DocumentNo in the instance that we want to show something different in these two parameters for an existing handled table.

OnBeforeGetDocumentTypeAndNumber(NotificationEntry,RecRef,DocumentType,DocumentNo,IsHandled);
at the beginning of the function would allow us to do this.

In context:
During approval workflow, we convert a purchase quote to order and send a notification to the requestee. This should say "Purchase Quote x was approved", but it displays the created Purchase Order instead.

I want to use a manual event binding to display the Quote No. instead when this specific workflow step is called.

At the moment I am having to create a copy of the Notification Email report just so I can handle this.

**Comment by AlexanderYakunin** [comment]
I cannot implement this as NotificationEntry is not available in this context
OnBeforeGetDocumentTypeAndNumber(**NotificationEntry**,RecRef,DocumentType,DocumentNo,IsHandled);

**Comment by SteveyN** [comment]
The function GetDocumentTypeAndNumber is only called in two places:
Codeunit 1509 Notification Entry Dispatcher - CreateNoteBody
Report 1320 Notification Email - SetDocumentTypeAndNumber

Notification Entry is used in both of these functions; could the NotificationEntry parameter be added to GetDocumentTypeAndNumber, and then passed through from these functions?
![image](https://user-images.githubusercontent.com/10519634/54135780-5e144e80-4412-11e9-986f-f4f408cd745c.png)

**Comment by AlexanderYakunin** [comment]
I cannot change signature of External function

[External] GetDocumentTypeAndNumber(VAR RecRef : RecordRef;VAR DocumentType : Text;VAR DocumentNo : Text)

**Comment by SteveyN** [comment]
I can understand the reasoning, since you don't want to break partners existing functionality, but if changes like that can't be made I don't see how this software can improve efficiently without hacky solutions.

Surely if the function signature is updated, partner development must be updated to match; as should be expected with evolving software like this.

Without changing this function, or adding a new function to supplant it, the only way I can see to do this is to set a global NotificationEntry variable in the NotificationManagement Codeunit, and then using this in the requested event. 

![image](https://user-images.githubusercontent.com/10519634/54603935-794c1300-4a3d-11e9-8127-2323477b32d1.png)

![image](https://user-images.githubusercontent.com/10519634/54603662-d09db380-4a3c-11e9-8dd8-d9cb114ab073.png)


This is far from the neatest solution, but you've stated you can't implement the neatest solution.

**Comment by SteveyN** [comment]
An alternative scenario that is specific to our use case is to add the following event to Report 1320 Notification Email

However this does not support instances where Notifications are sent as Notes rather than emails. So only Notification Emails can be customised.

![image](https://user-images.githubusercontent.com/10519634/54604250-33dc1580-4a3e-11e9-91e3-05b4ff74c658.png)
