### ISSUE TITLE
[Fieldgroup Request] Table 260 "Tariff Number"

### ISSUE THREAD

**Issue by HansvanderStaak** [microsoft/ALAppExtensions#14417]
Hi,

Is it possible to add a dropdown fieldgroup for table 260. 

`fieldgroups
{
    fieldgroup(Dropdown; "No.")
    {
    }
}`

**Comment by dnpb** [comment]
should add the Description in there too, since the default fieldgroup is the PK and a field named Description (or Name), whereas by adding the fieldgroup as you wrote it they would presumably lose the Description.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
