### ISSUE TITLE
[Event Request] report 790 "Calculate Inventory" - Enhance events in UpdateBuffer

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#14419]
Hi, for a customization, I need to extend "Inventory Buffer" table with a custom field "Quantity 2". 
After this, I need to handle my new field in Inventory calculation. To achieve this, I need that events
- OnUpdateBufferOnBeforeModify
- OnUpdateBufferOnBeforeInsert
would have source record from which quantity is taken. That means 
- WhseEntry for this call: UpdateBuffer(WhseEntry."Bin Code", WhseEntry."Qty. (Base)");
- Item Ledger Entry for this call: UpdateBuffer('', Quantity);

Function UpdateBuffer is local, so I guess that adding a parameter should not break anything.

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
