### ISSUE TITLE
[Extensibility Enhancements] Codeunit 1535 Approvals Mgmt, event OnBeforeIsSufficientPurchApprover

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#14418]
Hello,

In codeunit 1535 Approvals Mgmt, there is an event OnBeforeIsSufficientPurchApprover with the following parameters:

    local procedure OnBeforeIsSufficientPurchApprover(UserSetup: Record "User Setup"; DocumentType: Enum "Purchase Document Type"; ApprovalAmountLCY: Decimal; var IsSufficient: Boolean; var IsHandled: Boolean)

We have a scenario where we need to change the ApprovalAmountLCY and we would need to have this parameter ByRef (var):

    local procedure OnBeforeIsSufficientPurchApprover(UserSetup: Record "User Setup"; DocumentType: Enum "Purchase Document Type"; var ApprovalAmountLCY: Decimal; var IsSufficient: Boolean; var IsHandled: Boolean)

Thank you!

**Comment by dnpb** [comment]
So you want the decision on sufficiency to be based on an amount other than the one actually on the document? Seems confusing!

**Comment by CameliaPopescu** [comment]
We have a situation that in case the DocumentType is Order the ApprovalAmountLCY := Abs(ApprovalAmountLCY);
So we will need to change the ApprovalAmountLCY inside the event OnBeforeIsSufficientPurchApprover and then use it in determining the sufficiency.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
