### ISSUE TITLE
[Event Request] Report 20 "Calc. and Post VAT Settlement" - OnClosingGLAndVATEntryOnAfterSetVATEntryFilters same as issue #14226 but with the sender included

### ISSUE THREAD

**Issue by Sameer-Utekar** [microsoft/ALAppExtensions#14414]
Hi,

We need a similar solution mentioned in issue #14226 **but with the sender included**, so that we are able to retain the existing filters along with the new filters.
Which should change the first parameter for the IntegrationEvent() to "true"

So, the event signature changes to:
`
[IntegrationEvent(true, false)]
    local procedure OnClosingGLAndVATEntryOnAfterSetVATEntryFilters(VATPostingSetup: Record "VAT Posting Setup"; var VATEntry: Record "VAT Entry")
    begin
    end;
`

Thanks in advance :)!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
