### ISSUE TITLE
[Event Request] Codeunit 64 "Sales-Get Shipment" - OnAfterInsertLine

### ISSUE THREAD

**Issue by percova** [microsoft/ALAppExtensions#14420]
'Hi, would it be possible to modify the **OnAfterInsertLine** event in codeunit 64 (**Sales-Get Shipment**) by adding the **SalesHeader** parameter (with var keyword), like this:

```AL
    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertLine(var SalesShptLine: Record "Sales Shipment Line"; var SalesLine: Record "Sales Line"; SalesShptLine2: Record "Sales Shipment Line"; TransferLine: Boolean; var SalesHeader: Record "Sales Header")
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
