### ISSUE TITLE
[Fieldgroup Request] Table 7000 "Price List Header"

### ISSUE THREAD

**Issue by ZepposBE** [microsoft/ALAppExtensions#14423]
Hi,

Would it be possible to add a dropdown fieldgroup for table 7000, please?

`fieldgroups { fieldgroup(Dropdown; "Code", "Description") { } }`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
