### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" OnFindBWPickBinOnBeforeFindFromBinContent

### ISSUE THREAD

**Issue by hindsight2020** [microsoft/ALAppExtensions#14431]
Object codeunit 7312 "Create Pick"
Event Location FindBWPickBin

The name of the Parameter in the event signature seems wrong

TotalQty**ToPick**Base from the event publisher is TotalQty**Picked**Base. TotalQtyToPickBase2 is the actual value from TotalQtyToPickBase.

In function FindBWPickBin
`OnFindBWPickBinOnBeforeFindFromBinContent(FromBinContent, SourceType, TotalQtyPickedBase, IsHandled, TotalQtyToPickBase);`

Event Publisher:
`    [IntegrationEvent(false, false)]
    local procedure OnFindBWPickBinOnBeforeFindFromBinContent(var FromBinContent: Record "Bin Content"; SourceType: Integer; var TotalQtyToPickBase: Decimal; var IsHandled: Boolean; var TotalQtyToPickBase2: Decimal)`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
