### ISSUE TITLE
[Request-for-External] Codeunit 2310 "O365 Sales Invoice Mgmt" - GetPaymentInstructionsFromPostedInvoice - open for cloud

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#14441]
Can you please remove [Scope('OnPrem')] from procedure GetPaymentInstructionsFromPostedInvoice in codeunit 2310 "O365 Sales Invoice Mgmt"?

**Comment by AlexanderYakunin** [comment]
This procedure is part if old Invoicing solution, which was discontinued some time ago. We plan to finally obsolete all objects and elements of Invoicing in next release. Do you really need this object?

**Comment by andersws** [comment]
Hi and thanks for the feedback.

No, we dont need it if it's discontinued. We'll manage with a workaround until it's removed/replaced.

You can close this issue.
