### ISSUE TITLE
[Event request] table 290 "VAT Amount Line" - OnAfterCalcVATFields

### ISSUE THREAD

**Issue by iltererdogan** [microsoft/ALAppExtensions#14444]
Hi,

Is it possible to add Currency variable to publisher.

Original
```
OnAfterCalcVATFields(Rec, NewPricesIncludingVAT, NewVATBaseDiscPct);

[IntegrationEvent(false, false)]
local procedure OnAfterCalcVATFields(var VATAmountLine: Record "VAT Amount Line"; NewPricesIncludingVAT: Boolean; NewVATBaseDiscPct: Decimal)

```
Modified
```
OnAfterCalcVATFields(Rec, NewPricesIncludingVAT, NewVATBaseDiscPct, Currency);

[IntegrationEvent(false, false)]
local procedure OnAfterCalcVATFields(var VATAmountLine: Record "VAT Amount Line"; NewPricesIncludingVAT: Boolean; NewVATBaseDiscPct: Decimal; Currency: Record Currency)

```

**Comment by dnpb** [comment]
presumably not `var`? best to show full signatures of event publishers you want.

**Comment by iltererdogan** [comment]
> presumably not `var`? best to show full signatures of event publishers you want.

**Comment by iltererdogan** [comment]
thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
