### ISSUE TITLE
Codeunit 101 - Add parameter in the event OnBeforeUpdateCustLedgerEntry

### ISSUE THREAD

**Issue by rswaldia** [microsoft/ALAppExtensions#14446]
Request to add one parameter "CustEntryApplID" in the event "OnBeforeUpdateCustLedgerEntry" inside procedure "UpdateCustLedgerEntry".

// OLD
OnBeforeUpdateCustLedgerEntry(TempCustLedgerEntry, ApplyingCustLedgerEntry, AppliesToID, IsHandled);

// NEW
OnBeforeUpdateCustLedgerEntry(TempCustLedgerEntry, ApplyingCustLedgerEntry, AppliesToID, CustEntryApplID, IsHandled);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
