### ISSUE TITLE
[Event Request] - AddOnIntegrManagement.Codeunit.al - OnBeforeValidateProdOrderOnPurchLine

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#14440]
We like to request the following Event:
Object: AddOnIntegrManagement.Codeunit.al
Where is the event placed:
```al
procedure ValidateProdOrderOnPurchLine(var PurchLine: Record "Purchase Line")
var
    ...
    IsHandled: Boolean;
begin
    OnBeforeValidateProdOrderOnPurchLine(PurchLine, IsHandled);
    if IsHandled then
        exit;

    with PurchLine do begin
        TestField(Type, Type::Item);
        ...
end;
```
Event Code:
```al
[IntegrationEvent(false, false)]
local procedure OnBeforeValidateProdOrderOnPurchLine(var PurchLine: Record "Purchase Line"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
