### ISSUE TITLE
Codeunit 31020 "Purchase-Post Advances" local functions

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#14449]
Please change functions to glogal:
local procedure DeductRndLetterLines(OrderNo: Code[20])
local procedure FullyDeductedVendPrepmt(var PurchLine: Record "Purchase Line"): Boolean

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
