### ISSUE TITLE
Page 232 "Apply Customer Entries" - Add parameter in the event OnBeforeSetCustEntryApplID

### ISSUE THREAD

**Issue by rswaldia** [microsoft/ALAppExtensions#14447]
Request to add one parameter "GenJnlLine" as VAR in the event "OnBeforeSetCustEntryApplID" inside procedure "SetCustEntryApplID".

// OLD
OnBeforeSetCustEntryApplID(Rec, CurrentRec, ApplyingAmount, ApplyingCustLedgEntry, GetAppliesToID(), IsHandled);

// NEW
OnBeforeSetCustEntryApplID(Rec, CurrentRec, ApplyingAmount, ApplyingCustLedgEntry, GetAppliesToID(), GenJnlLine, IsHandled);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
