### ISSUE TITLE
Request to increase Dimension 1/2 filter field size on table 361 "Analysis by Dim. Parameters" 

### ISSUE THREAD

**Issue by davidatbinarystream** [microsoft/ALAppExtensions#14445]
This request is to increase the size of the dimension filter fields on table 361 "Analysis by Dim. Parameters".  

Specifically, this request it to remove (or at least increase) the size restriction on the dimension 1 and 2 filter fields, which our company (Binary Stream) uses in our Multi-Entity Management extension.  The current limit on these fields is 250 characters, but some of our customers have hundreds of entities that must be filtered when running the "G/L Balance by Dimension" and this limit results in the error shown below.  While our application relies heavily on these fields, it can also be reproduced in an unmodified instance of the application by creating and filtering on just over 25 dimensions.  (see the screenshots below)

This change would be greatly appreciated, best regards, David A.

Here is a snippet from the existing code...

table 361 "Analysis by Dim. Parameters"
...
field(10; "Dimension 1 Filter"; **Text[250]**)
{
    DataClassification = SystemMetadata;
}
field(11; "Dimension 2 Filter"; **Text[250]**)
{
    DataClassification = SystemMetadata;
}

![image](https://user-images.githubusercontent.com/71534583/134715132-471e1fe9-1beb-4a24-b3ac-af5420096a82.png)

![image](https://user-images.githubusercontent.com/71534583/134715157-008a8ee8-a826-4218-aef9-28677ad6ed1e.png)

**Comment by StanPesotskiy** [comment]
@davidatbinarystream Increasing a field length in general is a breaking change as it can lead to runtime errors. We allowed to create new fields with increased length instead. It means that all usage of this field should be rewritten to use the new field and all assignments of this field should be secured which can lead to more fields needing an increase. So we need very strong business case to make such a change in so widely used area. 
Also this increase is not a scalable solution, at some point you would exceed the new length as well. I would suggest considering some grouping of dim values so you can convert a group of almost any size to an unlimited Text to be applied as a filter. Though I am not sure about performance of this approach.
