### ISSUE TITLE
[Request for External] page 515 "Item Avail. by Location Lines" Global Var Item

### ISSUE THREAD

**Issue by moomencegekadsa** [microsoft/ALAppExtensions#14456]
Hello,

We hereby request that global variable Item in page 515 "Item Avail. by Location Lines" is changed to a protected variable.
![image](https://user-images.githubusercontent.com/85683700/134918548-362f1ad0-99c2-48b6-b351-1755f85a4736.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
