### ISSUE TITLE
[Event Request] table 900 "Assembly Header" - OnBeforeValidateQuantityToAssembleBase

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14459]
We would like to add a new event We would like to add a new event OnBeforeValidateQuantityToAssembleBase in the following trigger:

        field(47; "Quantity to Assemble (Base)"; Decimal)
        {
            Caption = 'Quantity to Assemble (Base)';
            DecimalPlaces = 0 : 5;

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                //A200F0000.Event18.03.ns
                IsHandled := false;
                OnBeforeValidateQuantityToAssembleBase(Rec, xRec, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;
                TestField("Qty. per Unit of Measure", 1);
                Validate("Quantity to Assemble", "Quantity to Assemble (Base)");
                //A200F0000.Event18.03.ne
            end;
        }

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateQuantityToAssembleBase(var AssemblyHeader: Record "Assembly Header"; xAssemblyHeader: Record "Assembly Header"; CallingFieldNo: Integer; var IsHandled: Boolean)
    begin
        //A200F0000.Event18.03
    end;

**Comment by Oleg-Romashkov** [comment]
Assembly Header table does not have validate trigger code for the field "Quantity to Assemble (Base)". You can use internal event OnAfterValidateEvent.
