### ISSUE TITLE
[Event Request] Codeunit 1535 "Approvals Mgmt." - DeleteApprovalEntries Function

### ISSUE THREAD

**Issue by Celicienta** [microsoft/ALAppExtensions#14457]
Dear ALAppExtensions Team,

I would like to request the following event publisher in codeunit "Approvals Mgmt." - DeletepprovalEntries function:
![image](https://user-images.githubusercontent.com/74307312/134926353-a4775cce-b1c1-489e-91ca-31a60d69c5ea.png)
New publisher event:
local procedure OnBeforeFilterApprovalEntriesToDelete(var ApprovalEntry: Record "Approval Entry");
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
