### ISSUE TITLE
[Extensibility-Enhancement] page 1354 "Pstd. Sales Cr. Memo - Update" - SetRec

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#14452]
Hello,
Is it possible to remove [Scope('OnPrem')] on this procedure ?

```
[Scope('OnPrem')]
    procedure SetRec(SalesCrMemoHeader: Record "Sales Cr.Memo Header")
    begin
        Rec := SalesCrMemoHeader;
        Insert();
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
