### ISSUE TITLE
[Event Request] table 900 "Assembly Header" - OnBeforeValidateQuantityBase

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14458]
We would like to add a new event OnBeforeValidateQuantityBase in the following trigger. We have many rounding issues when using item tracking lines with a different unit of measure then for instance the sales/purchase line. The statement TestField("Qty. per Unit of Measure", 1); is giving us al lot of grieve over the last twenty years.

field(41; "Quantity (Base)"; Decimal)
        {
            Caption = 'Quantity (Base)';
            DecimalPlaces = 0 : 5;

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                //A200F0000.Event18.03.ns
                IsHandled := false;
                OnBeforeValidateQuantityBase(Rec, xRec, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;
                //A200F0000.Event18.03.ne
                TestStatusOpen;
                TestField("Qty. per Unit of Measure", 1);
                Validate(Quantity, "Quantity (Base)");
            end;
        }

Event signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateQuantityBase(var AssemblyHeader: Record "Assembly Header"; xAssemblyHeader: Record "Assembly Header"; CallingFieldNo: Integer; var IsHandled: Boolean)
    begin
        //A200F0000.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
