### ISSUE TITLE
[Event Request] table 901 "Assembly Line" - OnBeforeValidateQuantityToAssembleBase

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14460]
We would like to add a new event OnBeforeValidateQuantityToAssembleBase in the following trigger:

        field(41; "Quantity (Base)"; Decimal)
        {
            Caption = 'Quantity (Base)';
            DecimalPlaces = 0 : 5;
            Editable = false;
            MinValue = 0;

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                //A200F0000.Event18.03.ns
                IsHandled := false;
                OnBeforeValidateQuantityBase(Rec, xRec, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;
                //A200F0000.Event18.03.ne
                TestField("Qty. per Unit of Measure", 1);
                Validate(Quantity, "Quantity (Base)");
            end;
        }

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateQuantityBase(var AssemblyLine: Record "Assembly Line"; xAssemblyLine: Record "Assembly Line"; CallingFieldNo: Integer; var IsHandled: Boolean)
    begin
        //A200F0000.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
