### ISSUE TITLE
[Request for External] table 901 "Assembly Line" - procedure CheckItemAvailable

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14462]
We would like to set the procedure CheckItemAvailable to global (The same as for instance Table 37 "Sales Line" so we can use this function in event OnBeforeValidateQuantityToAssembleBase which will hopefully be created in another git issue.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
