### ISSUE TITLE
[Request for External] page 510 "Blanket Purchase Order Subform" - DeltaUpdateTotals

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14465]
We would like to set procedure DeltaUpdateTotals() to global like it has been done in the other purchase subpages so we can use it in page extensions:

    procedure DeltaUpdateTotals()
    begin
        //A108F0000.Event18.03 local=false
        DocumentTotals.PurchaseDeltaUpdateTotals(Rec, xRec, TotalPurchaseLine, VATAmount, InvoiceDiscountAmount, InvoiceDiscountPct);
        CheckSendLineInvoiceDiscountResetNotification();
    end;

**Comment by AlexanderYakunin** [comment]
We have this instead

    procedure CallDeltaUpdateTotals()
    begin
        DeltaUpdateTotals();
    end;
