### ISSUE TITLE
[Request for Protected var] page 5870 "BOM Structure" - ShowBy

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14467]
protected var
        //A108F0000.Event18.03 protected var
        ShowBy: Option Item,Assembly,Production;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
