### ISSUE TITLE
[Request for External] page 508 "Blanket Sales Order Subform" - DeltaUpdateTotals

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14466]
We would like to set procedure DeltaUpdateTotals() to global like it has been done in the other sales subpages so we can use it in page extensions:

    procedure DeltaUpdateTotals()
    begin
        //A108F0000.Event18.03 local=false
        DocumentTotals.SalesDeltaUpdateTotals(Rec, xRec, TotalSalesLine, VATAmount, InvoiceDiscountAmount, InvoiceDiscountPct);
        if Rec."Line Amount" <> xRec."Line Amount" then
            Rec.SendLineInvoiceDiscountResetNotification();
    end;

**Comment by AlexanderYakunin** [comment]
We have this instead

    procedure CallDeltaUpdateTotals()
    begin
        DeltaUpdateTotals();
    end;
