### ISSUE TITLE
[Fieldgroups Request] table 7354 Bin

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14464]
We would like to add a fieldgroups property in table bin so we can extend this with our addon fields:

fieldgroups
    {
        fieldgroup(DropDown; "Code", "Zone Code", "Bin Type Code", Empty, Default)
        {
            //A108F0000.Event18.03
        }
    }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
