### ISSUE TITLE
[Event Request] report 6653 "Combine Return Receipts" - OnAfterFinalizeLastSalesCrMemoHeader

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14468]
We would like to add a new event OnAfterFinalizeLastSalesCrMemoHeader in the following trigger:

            trigger OnPostDataItem()
            begin
                CurrReport.Language := GlobalLanguage;
                Window.Close;
                OnBeforeShowResult(SalesHeader, NoOfSalesInvErrors, PostInv); //A108F0019.Event
                if SalesHeader."No." <> '' then begin // Not the first time
                    FinalizeSalesInvHeader;
                    OnAfterFinalizeLastSalesCrMemoHeader(SalesHeader, NoOfSalesInvErrors, PostInv); //A108F0019.Event18.03                    
                    if NoOfSalesInvErrors = 0 then
                        Message(Text010, NoOfSalesInv)
                    else
                        Message(Text007, NoOfSalesInvErrors)
                end else
                    Message(Text008);
            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterFinalizeLastSalesCrMemoHeader(var SalesCreditMemoHeader: Record "Sales Header"; var NoOfSalesCrMemoErrors: Integer; PostCreditMemo: Boolean)
    begin
        //A108F0019.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
