### ISSUE TITLE
[Event Request] codeunit 5058 "BankCont-Update" - OnInsertNewContactOnBeforeAssignNo

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14463]
We would like to add a new event OnInsertNewContactOnBeforeAssignNo in the following trigger. Maybe creating a new local procedure to handle the "No. Series" with be even nicer:

procedure InsertNewContact(var BankAcc: Record "Bank Account"; LocalCall: Boolean)
    var
        Cont: Record Contact;
        ContBusRel: Record "Contact Business Relation";
        NoSeriesMgt: Codeunit NoSeriesManagement;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeInsertNewContact(BankAcc, LocalCall, IsHandled);
        if IsHandled then
            exit;

        if not LocalCall then begin
            RMSetup.Get();
            RMSetup.TestField("Bus. Rel. Code for Bank Accs.");
        end;

        with Cont do begin
            Init;
            TransferFields(BankAcc);
            Validate(Name);
            Validate("E-Mail");
            //A108F0049.Event18.03.ns
            IsHandled := false;
            OnInsertNewContactOnBeforeAssignNo(Cont, BankAcc, RMSetup, IsHandled);
            if not IsHandled then begin
                //A108F0049.Event18.03.ne
                "No." := '';
                "No. Series" := '';
                RMSetup.TestField("Contact Nos.");
                NoSeriesMgt.InitSeries(RMSetup."Contact Nos.", '', 0D, "No.", "No. Series");
            end; //A108F0049.Event18.03
            Type := Type::Company;
            TypeChange;
            SetSkipDefault;
            OnBeforeContactInsert(Cont, BankAcc);
            Insert(true);
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnInsertNewContactOnBeforeAssignNo(var Contact: Record Contact; BankAccount: Record "Bank Account"; MarketingSetup: Record "Marketing Setup"; var IsHandled: Boolean)
    begin
        //A108F0049.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
