### ISSUE TITLE
[Request for Protected var] page 25 "Customer Ledger Entries" - StyleTxt

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14474]
We would like to request for a protected var StyleTxt.     

protected var
        Dim1Visible: Boolean;
        Dim2Visible: Boolean;
        Dim3Visible: Boolean;
        Dim4Visible: Boolean;
        Dim5Visible: Boolean;
        Dim6Visible: Boolean;
        Dim7Visible: Boolean;
        Dim8Visible: Boolean;
	//A108F0000.Event18.03 protected var
        StyleTxt: Text;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
