### ISSUE TITLE
[Event Request] table 9657 "Custom Report Selection" - OnCheckEmailBodyUsageOnBeforeEmailBodyIsAlreadyDefinedError

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14479]
We would like to add a new event OnCheckEmailBodyUsageOnBeforeEmailBodyIsAlreadyDefinedError in the following trigger. We have added a "Table-ID" and "Table Filter" to the "Report Selection" tables to allow an advanced selection of email bodies. For instance per "Responsibility Center" and/or "Language Code" and or "Prepayment Terms Code" etc. etc . etc.

    local procedure CheckEmailBodyUsage()
    var
        CustomReportSelection: Record "Custom Report Selection";
        ReportLayoutSelection: Record "Report Layout Selection";
    begin
        if "Use for Email Body" then begin
            CustomReportSelection.FilterEmailBodyUsage("Source Type", "Source No.", Usage.AsInteger());
            CustomReportSelection.SetFilter(Sequence, '<>%1', Sequence);
            OnCheckEmailBodyUsageOnBeforeEmailBodyIsAlreadyDefinedError(Rec, CustomReportSelection); //A108F0075.Event18.03
            if not CustomReportSelection.IsEmpty() then
                Error(EmailBodyIsAlreadyDefinedErr, Usage);

            if "Email Body Layout Code" = '' then
                if ReportLayoutSelection.GetDefaultType("Report ID") =
                   ReportLayoutSelection.Type::"RDLC (built-in)"
                then
                    Error(CannotBeUsedAsAnEmailBodyErr, "Report ID", ReportLayoutSelection.Type);
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnCheckEmailBodyUsageOnBeforeEmailBodyIsAlreadyDefinedError(var CustomReportSelection: Record "Custom Report Selection"; var SearchCustomReportSelection: Record "Custom Report Selection")
    begin
        //A108F0075.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
