### ISSUE TITLE
[Request for Protected var] page 21 "Customer Card" - ContactEditable

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14473]
We would like to request for a protected var ContactEditable. We have added a "Primary Bill-to Contact No." and are in need of this value:

    protected var
        [InDataSet]
	//A108F0000.Event18.03 protected var
        ContactEditable: Boolean;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
