### ISSUE TITLE
[Event Request] report 295 "Combine Shipments" - OnAfterFinalizeLastSalesInvoiceHeader

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14470]
We would like to add a new event OnAfterFinalizeLastSalesInvoiceHeader in the following trigger:

trigger OnPostDataItem()
            begin
                CurrReport.Language := GlobalLanguage;
                Window.Close;
                OnBeforeShowResult(SalesHeader, NoOfSalesInvErrors, PostInv); //A108F0019.Event
                if SalesHeader."No." <> '' then begin // Not the first time
                    FinalizeSalesInvHeader;
                    OnAfterFinalizeLastSalesInvoiceHeader(SalesHeader, NoOfSalesInvErrors, PostInv, HideDialog); //A108F0019.Event18.03
                    if (NoOfSalesInvErrors = 0) and not HideDialog then begin
                        if NoOfskippedShiment > 0 then begin
                            Message(
                              Text011,
                              NoOfSalesInv, NoOfskippedShiment)
                        end else
                            Message(
                              Text010,
                              NoOfSalesInv);
                    end else
                        if not HideDialog then
                            if PostInv then
                                Message(
                                  Text007,
                                  NoOfSalesInvErrors)
                            else
                                Message(
                                  NotAllInvoicesCreatedMsg,
                                  NoOfSalesInvErrors)
                end else
                    if not HideDialog then
                        Message(Text008);
            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterFinalizeLastSalesInvoiceHeader(var SalesInvoiceHeader: Record "Sales Header"; var NoOfSalesInvErrors: Integer; PostInvoice: Boolean; var HideDialog: Boolean)
    begin
        //A108F0019.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
