### ISSUE TITLE
[Event Request] codeunit 7322 "Create Inventory Pick/Movement" - OnAfterPrepareItemTrackingForInternalMovement

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14472]
We would like to add a new event OnAfterPrepareItemTrackingForInternalMovement in the following trigger:

    local procedure PrepareItemTrackingForInternalMovement(InternalMovementLine: Record "Internal Movement Line")
    begin
        // function recopies warehouse item tracking into temporary item tracking table
        // when Invt. Movement is created from Internal Movement
        TempReservEntry.Reset();
        TempReservEntry.DeleteAll();

        PrepareItemTrackingFromWhseIT(
          DATABASE::"Internal Movement Line", 0, InternalMovementLine."No.", InternalMovementLine."Line No.", -1);
        OnAfterPrepareItemTrackingForInternalMovement(InternalMovementLine, TempReservEntry); //A200F0000.Event18.03
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterPrepareItemTrackingForInternalMovement(InternalMovementLine: Record "Internal Movement Line"; var ReservationEntryBuffer: Record "Reservation Entry")
    begin
        //A200F0000.Event18.03
    end;

**Comment by Stepanenko-Vadim** [comment]
This has been implemented already several updates ago, closing the issue. The tag 'ships-in-future-update' is for housekeeping.
