### ISSUE TITLE
Remove scope OnPrem from procedures in Table 5065 and 5062

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [microsoft/ALAppExtensions#14476]
Remove scope OnPrem from procedure OpenAttachment in Table 5065 Interaction log Entry
Remove scope OnPrem from procedure DisplayInOutlook in Table 5062 Attachment

**Comment by AlexanderYakunin** [comment]
Hello! These procedures use DotNet components and cannot work in Cloud. This is the reason why they have scope On Prem.
