### ISSUE TITLE
[Event Request] report 295 "Combine Shipments" - OnFinalizeSalesInvoiceHeaderOnBeforePost

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14471]
We would like to add a new event OnFinalizeSalesInvoiceHeaderOnBeforePost in the following trigger. Maybe even creating a new local procedure handling the posting with an OnBeforePost event:

    local procedure FinalizeSalesInvHeader()
    var
        HasError: Boolean;
        IsHandled: Boolean;
    begin
        HasError := false;
        OnBeforeFinalizeSalesInvHeader(SalesHeader, HasAmount, HasError);
        if HasError then
            NoOfSalesInvErrors += 1;

        with SalesHeader do begin
            if (not HasAmount) or HasError then begin
                OnFinalizeSalesInvHeaderOnBeforeDelete(SalesHeader);
                Delete(true);
                OnFinalizeSalesInvHeaderOnAfterDelete(SalesHeader);
                exit;
            end;
            OnFinalizeSalesInvHeader(SalesHeader);
            if CalcInvDisc then
                SalesCalcDisc.Run(SalesLine);
            Find;
            Commit();
            Clear(SalesCalcDisc);
            Clear(SalesPost);
            NoOfSalesInv := NoOfSalesInv + 1;
            //if PostInv then begin A108F0019.Event18.03.o
            //A108F0019.Event18.03.ns
            IsHandled := false;
            OnFinalizeSalesInvoiceHeaderOnBeforePost(SalesHeader, PostInv, IsHandled); //A108F0019.Event18.03
            if PostInv and not IsHandled then begin
                //A108F0019.Event18.03.ne
                Clear(SalesPost);
                if not SalesPost.Run(SalesHeader) then
                    NoOfSalesInvErrors := NoOfSalesInvErrors + 1;
            end;
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnFinalizeSalesInvoiceHeaderOnBeforePost(var SalesInvoiceHeader: Record "Sales Header"; PostInvoice: Boolean; var IsHandled: Boolean)
    begin
        //A108F0019.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
