### ISSUE TITLE
Enum 5405 "Production Order Status" 

### ISSUE THREAD

**Issue by kw-AZ** [microsoft/ALAppExtensions#14475]
Good Morning,
Can you please change the "Production Order Status" enum to an extensible enum.
In the version 18.05 it is not extensible.
![image](https://user-images.githubusercontent.com/62378630/135052837-24179bad-4f8b-4171-bfcd-76ab9f062ee2.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
