### ISSUE TITLE
[Request for Protected vars] page 7159 "Invt. Analysis by Dimensions"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14485]
We would like to request for a few protected vars:

    protected var
        //A108F0000.Event18.03 protected var
        ItemAnalysisView: Record "Item Analysis View";
        MATRIX_Step: Option Initial,Previous,Same,Next,PreviousColumn,NextColumn;
        LineDimOption: Option Item,Period,Location,"Dimension 1","Dimension 2","Dimension 3";
        ColumnDimOption: Option Item,Period,Location,"Dimension 1","Dimension 2","Dimension 3";

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
