### ISSUE TITLE
[Request for Protected vars] page 99000919 "Demand Forecast"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14481]
We would like to request for a few protected vars:

    protected var
        //A108F0000.Event18.03 protected var
        PeriodType: Option Day,Week,Month,Quarter,Year,"Accounting Period";
        ForecastType: Option "Sales Item",Component,Both;
        ProductionForecastName: Text[30];
        LocationFilter: Text;
        DateFilter: Text[1024];
        ItemFilter: Text[1024];

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
