### ISSUE TITLE
[Request for External] table 7347 "Internal Movement Line" - CheckBinContentQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14482]
We would like to request for setting procedure CheckBinContentQty() to global to allow reuse in extensions.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
