### ISSUE TITLE
Event Request - Event available/updated in BC OnPrem CU3, but not updated on BC Cloud

### ISSUE THREAD

**Issue by anuj-inecta** [Microsoft/ALAppExtensions#1448]
Hi Team,

Given below events and parameters are present on BC On-Premise CU3, but are missing in BC Cloud. 
This is stopping us from creating package and deploying on BC Cloud.

1. **[EventSubscriber(ObjectType::Codeunit, 5760, 'OnBeforePostWhseJnlLine', '', false, false)]**
Issue:
procedure OnBeforePostWhseJnlLine_WhsePostRecCU(var PostedWhseReceiptHeader: Record "Posted Whse. Receipt Header"; var PostedWhseReceiptLine: Record "Posted Whse. Receipt Line"; var WhseReceiptLine: Record "Warehouse Receipt Line"; var TempTrackingSpecification: Record "Tracking Specification" temporary; var IsHandled: Boolean)

_var TempTrackingSpecification --> Parameter Missing_

2. **[EventSubscriber(ObjectType::Codeunit, 7307, 'OnAfterRegisteredWhseActivLineInsert', '', false, false)]**
Issue:
_OnAfterRegisteredWhseActivLineInsert --> Event Missing_

3. **[EventSubscriber(ObjectType::Codeunit, 7313, 'OnBeforeCreateNewWhseActivity', '', false, false)]**
Issue:
_OnBeforeCreateNewWhseActivity --> Event Missing_

Please update/add these events in BC Cloud as well.

Thanks!

**Comment by AlexanderYakunin** [comment]
We use same code base for OnPrem or Cloud, so you simply need t wait until next update will be deployed.

**Comment by anuj-inecta** [comment]
Got it.. Thanks!
