### ISSUE TITLE
[Event Request] table 77 "Report Selections" - OnCheckEmailBodyUsageOnBeforeEmailBodyIsAlreadyDefinedError

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14480]
We would like to add a new event OnCheckEmailBodyUsageOnBeforeEmailBodyIsAlreadyDefinedError in the following trigger. We have added a "Table-ID" and "Table Filter" to the "Report Selection" tables to allow an advanced selection of email bodies. For instance per "Responsibility Center" and/or "Language Code" and or "Prepayment Terms Code" etc. etc . etc.

    local procedure CheckEmailBodyUsage()
    var
        ReportSelections: Record "Report Selections";
        ReportLayoutSelection: Record "Report Layout Selection";
    begin
        if "Use for Email Body" then begin
            ReportSelections.SetEmailBodyUsageFilters(Usage);
            ReportSelections.SetFilter(Sequence, '<>%1', Sequence);
            OnCheckEmailBodyUsageOnBeforeEmailBodyIsAlreadyDefinedError(Rec, ReportSelections); //A108F0075.Event18.03
            if not ReportSelections.IsEmpty() then
                Error(EmailBodyIsAlreadyDefinedErr, Usage);

            if "Email Body Layout Code" = '' then
                if ReportLayoutSelection.GetDefaultType("Report ID") =
                   ReportLayoutSelection.Type::"RDLC (built-in)"
                then
                    Error(CannotBeUsedAsAnEmailBodyErr, "Report ID", ReportLayoutSelection.Type);
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnCheckEmailBodyUsageOnBeforeEmailBodyIsAlreadyDefinedError(var ReportSelection: Record "Report Selections"; var SearchReportSelection: Record "Report Selections")
    begin
        //A108F0075.Event18.03
    end;

**Comment by Stepanenko-Vadim** [comment]
This has been implemented already several updates ago, closing the issue. The tag 'ships-in-future-update' is for housekeeping.
