### ISSUE TITLE
[Request for fieldgroup] table 5800 "Item Charge" - DropDown

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14489]
We are missing a fieldgroup DropDown so we can extend it:

    fieldgroups
    {
        fieldgroup(DropDown; "No.", Description, "Search Description", "Gen. Prod. Posting Group", "VAT Prod. Posting Group")
        {
	    //A108F0000.Event18.03
        }
    }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
