### ISSUE TITLE
[Request for Protected var] page 9110 "Item Attributes Factbox" - TranslatedValuesVisible

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14487]
We would like to request for a protected var TranslatedValuesVisible. We have added a new field Description to allow for instance a color attribute '1010' a description 'Quality' and then with values for instance '01' a description 'Excellent' or '03' a description 'Questionable' which is not possible with standard BC18.

Signature:

    protected var
        //A108F0000.Event18.03 protected var
        TranslatedValuesVisible: Boolean;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
