### ISSUE TITLE
[Event Request] codeunit 99000854 "Inventory Profile Offsetting" - OnMaintainPlanningLineOnBeforeValidateUnitOfMeasureCode

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14483]
We would like to add a new event OnMaintainPlanningLineOnBeforeValidateUnitOfMeasureCode in the following trigger:

OnMaintainPlanningLineOnBeforeValidateNo(ReqLine, SupplyInvtProfile, TempSKU);
                        Validate("No.");
                        //A108F0000.Event18.03.ns
                        IsHandled := false;
                        OnMaintainPlanningLineOnBeforeValidateUnitOfMeasureCode(ReqLine, SupplyInvtProfile, TempSKU, IsHandled);
                        if not IsHandled then
                            //A108F0000.Event18.03.ne
                            Validate("Unit of Measure Code", SupplyInvtProfile."Unit of Measure Code");
                        "Starting Time" := ManufacturingSetup."Normal Starting Time";
                        "Ending Time" := ManufacturingSetup."Normal Ending Time";
                        OnMaintainPlanningLineOnAfterValidateFieldsForNewReqLine(ReqLine, SupplyInvtProfile, TempSKU);

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnMaintainPlanningLineOnBeforeValidateUnitOfMeasureCode(var RequisitionLine: Record "Requisition Line"; InventoryProfile: Record "Inventory Profile"; StockkeepingUnit: Record "Stockkeeping Unit"; var IsHandled: Boolean)
    begin
        //A108F0000.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
