### ISSUE TITLE
How to Identify a delegated admin?

### ISSUE THREAD

**Issue by pzentner** [microsoft/ALAppExtensions#1449]
We are charging customers by user for some of our apps and obviously want to determine the accurate amount of users we should charge for. Now, if we follow Microsoft's licensing model, delegated admins would not be counted into "billable users", however, they are also "full users". So, if I go through the user table, I cannot determine, if this user is a normal user or a delegated admin. I could determine that, if I would have read access to the Entitlement tables, but those tables are not accessible in app development.

Is there another way to determine this or would it be an option to make those tables accessible with read access? An alternative would be, if you would actually add a function (or let me know, if that exists already - I couldn't find one) that determines the number of users Microsoft would charge for based on the different user types.

**Comment by ikoletic** [comment]
This issue is a question. Please submit your questions on [business central community ](https://community.dynamics.com/business/f/758) or on [BC development yammer groups](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035).
