### ISSUE TITLE
[Event Request] table 83 "Item Journal Line" - OnValidateQuantityOnAfterCalcBaseQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14491]
We would like to add a new event OnValidateQuantityOnAfterCalcBaseQty in the following trigger:

        field(13; Quantity; Decimal)
        {
            Caption = 'Quantity';
            DecimalPlaces = 0 : 5;

            trigger OnValidate()
            var
                CallWhseCheck: Boolean;
            begin
                if ("Entry Type".AsInteger() <= "Entry Type"::Transfer.AsInteger()) and (Quantity <> 0) then
                    TestField("Item No.");

                if not PhysInvtEntered then
                    TestField("Phys. Inventory", false);

                CallWhseCheck :=
                  ("Entry Type" = "Entry Type"::"Assembly Consumption") or
                  ("Entry Type" = "Entry Type"::Consumption) or
                  ("Entry Type" = "Entry Type"::Output) and
                  LastOutputOperation(Rec);
                if CallWhseCheck then
                    WhseValidateSourceLine.ItemLineVerifyChange(Rec, xRec);

                if CurrFieldNo <> 0 then
                    WMSManagement.CheckItemJnlLineFieldChange(Rec, xRec, FieldCaption(Quantity));

                "Quantity (Base)" :=
                  UOMMgt.CalcBaseQty(
                    "Item No.", "Variant Code", "Unit of Measure Code", Quantity, "Qty. per Unit of Measure");
                OnValidateQuantityOnAfterCalcBaseQty(Rec, xRec); //A200F0000.Event18.03

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnValidateQuantityOnAfterCalcBaseQty(var ItemJournalLine: Record "Item Journal Line"; xItemJournalLine: Record "Item Journal Line")
    begin
        //A200F0000.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
