### ISSUE TITLE
[Event Request] table 83 "Item Journal Line" - OnValidateAppliesToEntryOnBeforeTrackingExistsError

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14492]
We would like to add a new event OnValidateAppliesToEntryOnBeforeTrackingExistsError in the following trigger:

        field(29; "Applies-to Entry"; Integer)
        {
            Caption = 'Applies-to Entry';

            trigger OnLookup()
            begin
                SelectItemEntry(FieldNo("Applies-to Entry"));
            end;

            trigger OnValidate()
            var
                ItemLedgEntry: Record "Item Ledger Entry";
                ItemTrackingLines: Page "Item Tracking Lines";
                IsHandled: Boolean;
            begin
                if "Applies-to Entry" <> 0 then begin
                    ItemLedgEntry.Get("Applies-to Entry");

                    if "Value Entry Type" = "Value Entry Type"::Revaluation then begin
                        if "Inventory Value Per" <> "Inventory Value Per"::" " then
                            Error(Text006, FieldCaption("Applies-to Entry"));

                        if "Inventory Value Per" = "Inventory Value Per"::" " then
                            if not RevaluationPerEntryAllowed("Item No.") then
                                Error(RevaluationPerEntryNotAllowedErr);

                        InitRevalJnlLine(ItemLedgEntry);
                        ItemLedgEntry.TestField(Positive, true);
                    end else begin
                        TestField(Quantity);
                        if Signed(Quantity) * ItemLedgEntry.Quantity > 0 then begin
                            if Quantity > 0 then
                                FieldError(Quantity, Text030);
                            if Quantity < 0 then
                                FieldError(Quantity, Text029);
                        end;
                        //A200F0000.Event18.03.ns
                        IsHandled := false;
                        OnValidateAppliesToEntryOnBeforeTrackingExistsError(Rec, xrec, IsHandled);
                        if not IsHandled then
                            //A200F0000.Event18.03.ne
                            if ItemLedgEntry.TrackingExists then
                                Error(Text033, FieldCaption("Applies-to Entry"), ItemTrackingLines.Caption);

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnValidateAppliesToEntryOnBeforeTrackingExistsError(var ItemJournalLine: Record "Item Journal Line"; xItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
        //A200F0000.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
