### ISSUE TITLE
[Request for External] codeunit 6501 "Item Tracking Data Collection" - SumUpTempTrkgSpec & RelateJnlLineToTempTrkgSpec

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14499]
We would like to set procedures SumUpTempTrkgSpec and RelateJnlLineToTempTrkgSpec. We are using it to check the item tracking lines correctly between Output Journal vs. "Prod. Order Line" and "Consumption Journal" vs. "Prod Order. Component".

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
