### ISSUE TITLE
[Event Request] table 83 "Item Journal Line" - OnValidateOutputQuantityOnAfterCalcBaseQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14494]
We would like to add a new event OnValidateOutputQuantityOnAfterCalcBaseQty in the following trigger:

        field(5846; "Output Quantity"; Decimal)
        {
            AccessByPermission = TableData "Machine Center" = R;
            Caption = 'Output Quantity';
            DecimalPlaces = 0 : 5;

            trigger OnValidate()
            begin
                TestField("Entry Type", "Entry Type"::Output);
                if SubcontractingWorkCenterUsed and ("Output Quantity" <> 0) then
                    Error(SubcontractedErr, FieldCaption("Output Quantity"), "Line No.");

                CheckConfirmOutputOnFinishedOperation;

                if LastOutputOperation(Rec) then
                    WhseValidateSourceLine.ItemLineVerifyChange(Rec, xRec);

                "Output Quantity (Base)" :=
                  UOMMgt.CalcBaseQty(
                    "Item No.", "Variant Code", "Unit of Measure Code", "Output Quantity", "Qty. per Unit of Measure");
                OnValidateOutputQuantityOnAfterCalcBaseQty(Rec, xRec); //A200F0000.Event18.03
                Validate(Quantity, "Output Quantity");
            end;
        }

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnValidateOutputQuantityOnAfterCalcBaseQty(var ItemJournalLine: Record "Item Journal Line"; xItemJournalLine: Record "Item Journal Line")
    begin
        //A200F0000.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
