### ISSUE TITLE
[Request for External] table 83 "Item Journal Line" - CheckItemAvailable

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14497]
We would like to set procedure CheckItemAvailable to global so we can reuse it in our item specification table and page extension:

Signature:

    procedure CheckItemAvailable(CalledByFieldNo: Integer)
    var
        IsHandled: Boolean;
    begin
        //A108F0000.Event18.03 local=false
        if (CurrFieldNo = 0) or (CurrFieldNo <> CalledByFieldNo) then // Prevent two checks on quantity
            exit;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
