### ISSUE TITLE
[Request for External] codeunit 22 "Item Jnl.-Post Line" - PostFlushedConsump

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14490]
We would like to set procedure PostFlushedConsump to global so we can use it in a subscriber to event OnBeforeFlushOperation. Out vertical provides some extra item tracking posting during some routing operations and we are in need of the code provided in PostFlushedConsump.

Signature:

procedure PostFlushedConsump(ProdOrder: Record "Production Order"; ProdOrderLine: Record "Prod. Order Line"; ProdOrderComp: Record "Prod. Order Component"; var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; OldItemJnlLine: Record "Item Journal Line")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
