### ISSUE TITLE
[Request editable item tracking fields] table 83 "Item Journal Line"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14498]
In our vertical we are heavily using the item tracking engine. In the journals: "Item Journal", "Phys. Inventory Journal", "Item Reclass. Journal", "Production Journal", "Output Journal" and "Consumption Journal" we found out that filling in "Item Tracking Lines" in T336 and T337 with page 6510 "Item Tracking Lines" is way to difficult and hard to use for many of our customers. Also the performance is an issue by using T337 heavily in the Base.
Therfore we have been reusing the fields "Serial No.", "Lot No.", "Warranty Date", "New Serial No.", "New Lot No.", "New Item Expiration Date", "Item Expiration Date", "Package No.", "New Package No." by setting the editable property to true in table 83 "Item Journal Line" and putting those fields on the previous mentioned pages. Those fields are only internally used in C22 and cannot be set to editable=true by using an extension table. It would be nice if this could be modified in the base.

![image_7](https://user-images.githubusercontent.com/30273162/135107370-26870881-af2e-451b-9d7b-6356dd8e1a1e.png)

**Comment by Duizy1971** [comment]
Hi Andrei,

That idea is not actually what I'm needing. I just need the T83 en T7311 item tracking fields to be made editable. Putting them on a page would be implemnted in our extension not in the Base.

**Comment by RomanZanizdra** [comment]
Hi @Duizy1971 , the mentioned idea is exactly about what you are asking for. Please read the comment where editable fields in T83 are requested.
