### ISSUE TITLE
[Request for External] table 1003 "Job Planning Line" - CheckItemAvailable & UpdateReservation

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14505]
We would like to set procedure CheckItemAvailable and UpdateReservation to global.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
