### ISSUE TITLE
[Request for External] page 1007 "Job Planning Lines" - PerformAutoReserve

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14506]
We would like to set procedure PerformAutoReserve() to global so when we put field "Quantity (Base)" on a page we can do the same as the base field Quantity.

**Comment by AlexanderYakunin** [comment]
We already have this for that purpose

    protected procedure ReserveOnAfterValidate()
    begin
        PerformAutoReserve();
    end;
