### ISSUE TITLE
[Event Request] codeunit 397 Mail - OnCreateAndSendMessageOnAfterAttachFile

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14509]
We would like to add a new event OnCreateAndSendMessageOnAfterAttachFile in the following trigger:    

local procedure CreateAndSendMessage(ToAddresses: Text; CcAddresses: Text; BccAddresses: Text; Subject: Text; Body: Text; AttachFilename: Text; ShowNewMailDialogOnSend: Boolean; RunModal: Boolean): Boolean
    var
        MailSent: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCreateAndSendMessage(
          ToAddresses, CcAddresses, BccAddresses, Subject, Body, AttachFilename, ShowNewMailDialogOnSend, MailSent, IsHandled);
        if IsHandled then
            exit(MailSent);

        Initialize;

        CreateMessage(ToAddresses, CcAddresses, BccAddresses, Subject, Body, ShowNewMailDialogOnSend, RunModal);
        AttachFile(AttachFilename);
        OnCreateAndSendMessageOnAfterAttachFile(); //A108F0075.Event18.03

        exit(Send);
    end;

Event Signature:

    [IntegrationEvent(true, false)]
    local procedure OnCreateAndSendMessageOnAfterAttachFile()
    begin
        //A108F0075.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
