### ISSUE TITLE
[Request variable] page 6510 "Item Tracking Lines" - SourceTrackingSpecification in SetSourceSpec

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14501]
We would like to have a new protected var SourceTrackingSpecification: Record "Tracking Specification" in page page 6510 "Item Tracking Lines" which is set in the beginning of the procedure SetSourceSpec. In our vertical we have the possibility to set a new output Lot and/or Serial No. not only from the setting on the Item Card but also derived from the Prod Order No. or our field "Batch No." or even a no. series setting on the machine or work center. The values needed to provide for this functionality are lost when using Rec and the filtering on T337 etc. 

    procedure SetSourceSpec(TrackingSpecification: Record "Tracking Specification"; AvailabilityDate: Date)
    var
        ReservEntry: Record "Reservation Entry";
        TempTrackingSpecification: Record "Tracking Specification" temporary;
        TempTrackingSpecification2: Record "Tracking Specification" temporary;
        CreateReservEntry: Codeunit "Create Reserv. Entry";
        CurrentEntryStatusOption: Option;
        IsHandled: Boolean;
    begin
        OnBeforeSetSourceSpec(TrackingSpecification, ReservEntry);

        SourceTrackingSpecification := TrackingSpecification; //A200F0000.Event18.03

which we then can use in two standard events OnBeforeAssignNewSerialNo and OnBeforeAssignNewLotNo

    local procedure AssignNewSerialNo()
    var
        IsHandled: Boolean;
    begin
        //OnBeforeAssignNewSerialNo(Rec, IsHandled); A200F0000.Event18.05.o
        OnBeforeAssignNewSerialNo(Rec, SourceTrackingSpecification, IsHandled); //A200F0000.Event18.05.o
        if IsHandled then
            exit;

        Item.TestField("Serial Nos.");
        Rec.Validate("Serial No.", NoSeriesMgt.GetNextNo(Item."Serial Nos.", WorkDate(), true));
    end;

    local procedure AssignNewLotNo()
    var
        IsHandled: Boolean;
    begin
        //OnBeforeAssignNewLotNo(Rec, IsHandled); //A200F0000.Event.o
        OnBeforeAssignNewLotNo(Rec, SourceTrackingSpecification, IsHandled); //A200F0000.Event.n
        if IsHandled then
            exit;

        Item.TestField("Lot Nos.");
        Rec.Validate("Lot No.", NoSeriesMgt.GetNextNo(Item."Lot Nos.", WorkDate, true));
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
