### ISSUE TITLE
[Existing Event Request] page 6510 "Item Tracking Lines" - OnQueryClosePageOnBeforeConfirmClosePage parameter CurrentRunMode

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14500]
We would like to extend event procedure OnQueryClosePageOnBeforeConfirmClosePage with a new parameter CurrentRunMode a.k.a. ItemTrackingRunMode:

    trigger OnQueryClosePage(CloseAction: Action): Boolean
    var
        IsHandled: Boolean;
    begin
        if not UpdateUndefinedQty then
            exit(Confirm(Text006));

        if not ItemTrackingDataCollection.RefreshTrackingAvailability(Rec, false) then begin
            CurrPage.Update();

            IsHandled := false;
            //OnQueryClosePageOnBeforeConfirmClosePage(Rec, IsHandled); A200F0000.Event18.03.o
            OnQueryClosePageOnBeforeConfirmClosePage(Rec, CurrentRunMode, IsHandled); //A200F0000.Event18.03.n
            if IsHandled then
                Exit(true);

            exit(Confirm(AvailabilityWarningsQst, true));
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnQueryClosePageOnBeforeConfirmClosePage(var TrackingSpecification: Record "Tracking Specification"; ItemTrackingRunMode: Enum "Item Tracking Run Mode"; var IsHandled: Boolean)
    begin
        //A108F0000.Event18.03 Parameter ItemTrackingRunMode
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
