### ISSUE TITLE
[Fieldgroup Request] table 14 Location - DropDown

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14507]
fieldgroups
    {
        fieldgroup(DropDown; "Code", Name, Address, "Post Code", City, "Country/Region Code")
        {
            //A108F0000.Event18.03
        }
    }

**Comment by AlexanderYakunin** [comment]
We already have DropDown field group for Location table, and you can extend it using this information:

In a table extension object, the fieldgroups control allows you to add more fields to a field group defined for the table object. This can be done by using the addlast(<name>; <field>) keyword.
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-field-groups
