### ISSUE TITLE
[Event Request] table table 5406 "Prod. Order Line" - OnValidateQuantityOnAfterCalcBaseQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14516]
We would like to add a new event OnValidateQuantityOnAfterCalcBaseQty in the following trigger:

        field(40; Quantity; Decimal)
        {
            Caption = 'Quantity';
            DecimalPlaces = 0 : 5;
            MinValue = 0;

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                IsHandled := false;
                OnBeforeValidateQuantity(Rec, xRec, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;

                "Quantity (Base)" := Quantity * "Qty. per Unit of Measure";

                OnValidateQuantityOnAfterCalcBaseQty(Rec, xRec); //A200F0000.Event18.03

                "Remaining Quantity" := Quantity - "Finished Quantity";
                if "Remaining Quantity" < 0 then
                    "Remaining Quantity" := 0;
                "Remaining Qty. (Base)" := "Remaining Quantity" * "Qty. per Unit of Measure";
                ProdOrderLineReserve.VerifyQuantity(Rec, xRec);
                WhseValidateSourceLine.ProdOrderLineVerifyChange(Rec, xRec);

                UpdateProdOrderComp(xRec."Qty. per Unit of Measure");

                if CurrFieldNo <> 0 then
                    Validate("Ending Time");
                "Cost Amount" := Round(Quantity * "Unit Cost");
            end;
        }

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnValidateQuantityOnAfterCalcBaseQty(var ProdOrderLine: Record "Prod. Order Line"; xProdOrderLine: Record "Prod. Order Line")
    begin
        //A200F0000.Event18.03
    end;

**Comment by Duizy1971** [comment]
I've been checking our customized BaseApp 20.05W1 and searched for my tag 'Event18.??' and found out that this request has not made it to 20.05 even after two major releases. When you search in ALAppExtensions on 'OnValidateQuantityOnAfterCalcBaseQty' you can see that I have requested the same event 10 more times or so for other tables and those events have made it on time. Can you tell me what happened to this particular one.
I would also like to know if this is the way to request for answers on this particular topic in this closed issue. I think I have a lot more of the same questions.

**Comment by JesperSchulz** [comment]
I too cannot see that this request was implemented - neither in the way you requested nor in another way. Let me see if I can either find some answers for you or if we can reopen your case and get that event added.

**Comment by Duizy1971** [comment]
Hi Jesper,

I was a bit hasty and already added a new issue:

https://github.com/microsoft/ALAppExtensions/issues/20295

to reask for this event.
