### ISSUE TITLE
[Event Request] Codeunit 90 - Purch.-Post - OnPostItemChargePerOrderOnAfterCopyToItemJnlLine add VAR parameter TempItemChargeAssgntPurch

### ISSUE THREAD

**Issue by rvanbekkum** [Microsoft/ALAppExtensions#1451]
Dear ALAppExtensions team,

Through this issue we would like to request the event publisher `OnPostItemChargePerOrderOnAfterCopyToItemJnlLine` to be extended with an additional **VAR** parameter `TempItemChargeAssgntPurch`, resulting in the following signature:
```
LOCAL [IntegrationEvent] OnPostItemChargePerOrderOnAfterCopyToItemJnlLine(VAR ItemJournalLine : Record "Item Journal Line";VAR PurchaseLine : Record "Purchase Line";GeneralLedgerSetup : Record "General Ledger Setup";QtyToInvoice : Decimal;VAR TempItemChargeAssignmentPurch : TEMPORARY Record "Item Charge Assignment (Purch)")
```

Then, this event publisher would be called in procedure `PostItemChargePerOrder` as follows:
```pascal
OnPostItemChargePerOrderOnAfterCopyToItemJnlLine(ItemJnlLine2,ItemChargePurchLine,GLSetup,QtyToInvoice,TempItemChargeAssgntPurch);
```

**Comment by AlexanderYakunin** [comment]
This change already implemented

**Comment by rvanbekkum** [comment]
@AlexanderYakunin I just pulled the latest version from bcinsider.azurecr.io/bcsandbox-master:latest.
I do not see the additional parameter `TempItemChargeAssignmentPurch` in that version yet.

Did I do something wrong? Or did you accidentally mistake this issue for being about adding the event?
