### ISSUE TITLE
[Event Request] table 39 "Purchase Line" - OnBeforeValidateQtyToReceiveBase

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14519]
We would like to add a new event OnBeforeValidateQtyToReceiveBase in the following trigger:

        field(5418; "Qty. to Receive (Base)"; Decimal)
        {
            Caption = 'Qty. to Receive (Base)';
            DecimalPlaces = 0 : 5;

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                //A200F0000.Event18.03.ns
                IsHandled := false;
                OnBeforeValidateQtyToReceiveBase(Rec, xRec, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;
                //A200F0000.Event18.03.ne
                TestField("Qty. per Unit of Measure", 1);
                Validate("Qty. to Receive", "Qty. to Receive (Base)");
            end;
        }

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateQtyToReceiveBase(var PurchaseLine: Record "Purchase Line"; xPurchaseLine: Record "Purchase Line"; CallingFieldNo: Integer; var IsHandled: Boolean)
    begin
        //A200F0000.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
