### ISSUE TITLE
[Event Request] table 7001 "Price List Line" - OnAfterVerify

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14512]
We would like to add a new event OnAfterVerify in the following trigger:

    procedure Verify()
    begin
        VerifySource();
        TestField("Asset Type");
        OnAfterVerify(Rec); //A101F0000.Event18.03
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterVerify(var PriceListLine: Record "Price List Line")
    begin
        //A101F0000.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
