### ISSUE TITLE
[Request for Protected vars] Sales document subpages - UnitofMeasureCodeIsChangeable

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14522]
We would like to request for protected var UnitofMeasureCodeIsChangeable in the following pages. We have introduced a "Price Unit of Measure Code" and would like to reuse this base value for our horizontal addon:

page 96 "Sales Cr. Memo Subform"
page 46 "Sales Order Subform"
page 6631 "Sales Return Order Subform"

Event Signature:

        [InDataSet]
        ItemReferenceVisible: Boolean;
        VATAmount: Decimal;
	//A108F0000.Event18.03 protected var
        UnitofMeasureCodeIsChangeable: Boolean;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
