### ISSUE TITLE
[Event Request] table 246 "Requisition Line" - OnBeforeValidateQuantityBase

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14524]
We would like to add a new event OnBeforeValidateQuantityBase in the following trigger:

        field(5408; "Quantity (Base)"; Decimal)
        {
            Caption = 'Quantity (Base)';
            DecimalPlaces = 0 : 5;

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                IsHandled := false;
                //OnBeforeValidateQuantityBase(Rec, IsHandled); A200F0000.Event18.03.o
                OnBeforeValidateQuantityBase(Rec, xRec, CurrFieldNo, CurrentFieldNo, IsHandled); //A200F0000.Event18.03.n
                if IsHandled then
                    exit;

                TestField("Prod. Order No.", '');
                TestField("Qty. per Unit of Measure", 1);
                Validate(Quantity, "Quantity (Base)");
            end;
        }

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateQuantityBase(var RequisitionLine: Record "Requisition Line"; xRequisitionLine: Record "Requisition Line"; CallingFieldNo: Integer; CurrentCallingFieldNo: Integer; var IsHandled: Boolean)
    begin
        //A200F0000.Event18.03 Parameter xRequisitionLine, CallingFieldNo, CurrentCallingFieldNo
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
