### ISSUE TITLE
[Enum Request] table 245 "Requisition Wksh. Name" & table 244 "Req. Wksh. Template"- "Template Type"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14529]
We would like to be able to add our own template type to the options. We have a different planning strategy for production which we'd like to separate from the three base types.

OptionMembers = "Req.","For. Labor",Planning

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
