### ISSUE TITLE
[Event Request] table 36 "Sales Header" - OnRecreateReservEntryOnBeforeValidateLocationCode

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14530]
We would like to add a new event OnRecreateReservEntryOnBeforeValidateLocationCode in the following trigger. We don't understand that when using item reservation, order tracking, order-to-order production planning, assemble to order or ,even worse, item tracking lines that you want to change the "Location Code" back to the header default. You get some not so pleasing results:

    local procedure RecreateReservEntryReqLine(var TempSalesLine: Record "Sales Line" temporary; var TempATOLink: Record "Assemble-to-Order Link" temporary; var ATOLink: Record "Assemble-to-Order Link")
    var
        IsHandled: Boolean;
    begin
        repeat
            TestSalesLineFieldsBeforeRecreate;
            //A108F0026.Event18.03.ns
            IsHandled := false;
            OnRecreateReservEntryOnBeforeValidateLocationCode(Rec, xRec, SalesLine, IsHandled);
            if not IsHandled then
                //A108F0026.Event18.03.ne
                if (SalesLine."Location Code" <> "Location Code") and (not SalesLine.IsNonInventoriableItem) then
                    SalesLine.Validate("Location Code", "Location Code");
            TempSalesLine := SalesLine;
            if SalesLine.Nonstock then begin
                SalesLine.Nonstock := false;
                SalesLine.Modify();
            end;

            if ATOLink.AsmExistsForSalesLine(TempSalesLine) then begin
                TempATOLink := ATOLink;
                TempATOLink.Insert();
                ATOLink.Delete();
            end;

            TempSalesLine.Insert();
            OnAfterInsertTempSalesLine(SalesLine, TempSalesLine);
            SalesLineReserve.CopyReservEntryToTemp(TempReservEntry, SalesLine);
            RecreateReqLine(SalesLine, 0, true);
            OnRecreateReservEntryReqLineOnAfterLoop(Rec, SalesLine);
        until SalesLine.Next() = 0;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnRecreateReservEntryOnBeforeValidateLocationCode(var SalesHeader: Record "Sales Header"; xSalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; IsHandled: Boolean)
    begin
        //A108F0026.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
