### ISSUE TITLE
[Event Request] table 753 "Standard Item Journal Line" - OnValidateItemNoOnAfterCopyItemValues

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14544]
We would like to add a new event OnValidateItemNoOnAfterCopyItemValues in the following trigger:

        field(3; "Item No."; Code[20])
        {
            Caption = 'Item No.';
            TableRelation = Item WHERE(Blocked = CONST(false));

            ...
            
            trigger OnValidate()
            var
                PriceType: Enum "Price Type";
            begin
                ...
                GetItem;
                Item.TestField(Blocked, false);
                Description := Item.Description;
                "Inventory Posting Group" := Item."Inventory Posting Group";
                "Item Category Code" := Item."Item Category Code";
                OnValidateItemNoOnAfterCopyItemValues(Rec, Item); //A200F0000.Event18.03
                ...
            end;
        }

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnValidateItemNoOnAfterCopyItemValues(var StandardItemJournalLine: Record "Standard Item Journal Line"; Item: Record Item)
    begin
        //A200F0000.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
