### ISSUE TITLE
[Event Request] table 5741 "Transfer Line" - OnValidateQuantityOnAfterCalcBaseQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14545]
We would like to add a new event OnValidateQuantityOnAfterCalcBaseQty in the following trigger:

        field(4; Quantity; Decimal)
        {
            Caption = 'Quantity';
            DecimalPlaces = 0 : 5;
            MinValue = 0;

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                if CurrFieldNo <> 0 then
                    TestStatusOpen;
                if Quantity <> 0 then
                    TestField("Item No.");
                "Quantity (Base)" :=
                    UOMMgt.CalcBaseQty("Item No.", "Variant Code", "Unit of Measure Code", Quantity, "Qty. per Unit of Measure");
                OnValidateQuantityOnAfterCalcBaseQty(Rec, xRec); //A200F0000.Event18.03

                if ((Quantity * "Quantity Shipped") < 0) or
                   (Abs(Quantity) < Abs("Quantity Shipped"))
                then
                    FieldError(Quantity, StrSubstNo(Text002, FieldCaption("Quantity Shipped")));
                ...
            end;
        }

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnValidateQuantityOnAfterCalcBaseQty(var TransferLine: Record "Transfer Line"; xTransferLine: Record "Transfer Line")
    begin
        //A200F0000.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
