### ISSUE TITLE
[Request for External] table 5902 "Service Line" - UpdateWithWarehouseShip

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14542]
We would like to set procedure UpdateWithWarehouseShip() to global like it has been done in the T37 "Sales Line" and T39 "Purchase Line" tables:

    procedure UpdateWithWarehouseShip()
    //A108F0000.Event18.03 local=false
    begin
        if Type <> Type::Item then
            exit;
        if "Document Type" in ["Document Type"::Quote, "Document Type"::Order] then
            if Location.RequireShipment("Location Code") then begin
                Validate("Qty. to Ship", 0);
                Validate("Qty. to Invoice", 0);
            end else
                Validate("Qty. to Ship", "Outstanding Quantity");
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
