### ISSUE TITLE
[Event Request] table 5741 "Transfer Line" - OnBeforeValidateQtyToReceiveBase

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14548]
We would like to add a new event OnBeforeValidateQtyToReceiveBase in the following trigger:

        field(20; "Qty. to Receive (Base)"; Decimal)
        {
            Caption = 'Qty. to Receive (Base)';
            DecimalPlaces = 0 : 5;
            MinValue = 0;

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                //A200F0000.Event18.03.ns
                IsHandled := false;
                OnBeforeValidateQtyToReceiveBase(Rec, xRec, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;
                //A200F0000.Event18.03.ne
                TestField("Qty. per Unit of Measure", 1);
                Validate("Qty. to Receive", "Qty. to Receive (Base)");
            end;
        }

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateQtyToReceiveBase(var TransferLine: Record "Transfer Line"; xTransferLine: Record "Transfer Line"; CallingFieldNo: Integer; var IsHandled: Boolean)
    begin
        //A200F0000.Event18.03
    end;

**Comment by Stepanenko-Vadim** [comment]
This has been implemented already several updates ago, closing the issue. The tag 'ships-in-future-update' is for housekeeping.
