### ISSUE TITLE
[Event Request] table 5902 "Service Line" - OnBeforeValidateQtyToShipBase

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14540]
We would like to add a new event OnBeforeValidateQtyToShipBase in the following trigger:

        field(5418; "Qty. to Ship (Base)"; Decimal)
        {
            Caption = 'Qty. to Ship (Base)';
            DecimalPlaces = 0 : 5;

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                //A200F0000.Event18.03.ns
                IsHandled := false;
                OnBeforeValidateQtyToShipBase(Rec, xRec, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;
                //A200F0000.Event18.03.ne
                if "Qty. to Ship (Base)" < 0 then
                    FieldError("Qty. to Ship (Base)", Text029);

                TestField("Qty. per Unit of Measure", 1);
                Validate("Qty. to Ship", "Qty. to Ship (Base)");
            end;
        }

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateQtyToShipBase(var ServiceLine: Record "Service Line"; xServiceLine: Record "Service Line"; CallingFieldNo: Integer; var IsHandled: Boolean)
    begin
        //A200F0000.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
