### ISSUE TITLE
[Request editable item tracking fields] table 7311 "Warehouse Journal Line"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14556]
In our vertical we are heavily using the item tracking engine. In the journals: "Whse. Item Journal", "Whse. Phys. Invt. Journal", "Whse. Reclassification Journal" we found out that filling in page 6550 "Whse. Item Tracking Lines" is way to difficult and hard to use for many of our customers. 
Therfore we have been reusing the fields "Warranty Date", "Expiration Date", "New Serial No.", "New Lot No.", "New Expiration Date", "New Package No." by setting the editable property to true in table 7311 "Warehouse Journal Line" and putting those fields on the previous mentioned pages. Those fields are only internally used in C7304 "Whse. Jnl.-Register Batch" and cannot be set to editable=true by using an extension table. Fields "Lot No.", "Serial No." and "Package No." are already editable so it would be nice if these fields could be modified to editable=true in the base.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
