### ISSUE TITLE
event parameter request - codeunit 427 ICInboxOutboxMgt - OnInsertICOutboxJnlLine() - add TempGenJnlLine

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#14555]
Please pass the source `TempGenJnlLine` to subscribers. We need to copy additional fields from the source document/lines to the IC Outbox Jnl Line (and from there, to the Inbox, etc.)

I'd prefer an `OnBeforeInsert` event to what is here, so we wouldn't have to wastefully do a Modify() after setting our fields - so it'd be nice to add that too, if you think it makes sense. However, our main requirement is having the source `TempGenJnlLine` alongside the destination `ICOutboxJnlLine`, so we'll be able to copy over more fields, and if we must `Modify()` then so be it.

publisher:

    [IntegrationEvent(false, false)]
    local procedure OnInsertICOutboxJnlLine(var ICOutboxJnlLine: Record "IC Outbox Jnl. Line";
        TempGenJnlLine: Record "Gen. Journal Line" temporary) // ADDED

call:

    local procedure InsertOutboxJnlLine(TempGenJnlLine: Record "Gen. Journal Line" temporary; TransactionNo: Integer; TransactionSource: Option "Rejected by Current Company"," Created by Current Company"; BalancingLine: Boolean)
    [...]
            ICOutboxJnlLine.Insert();

            OnInsertICOutboxJnlLine(ICOutboxJnlLine,
                TempGenJnlLine); // ADDED
        end;
    end;

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
