### ISSUE TITLE
[Event Request] table 7311 "Warehouse Journal Line" - OnValidateQuantityOnAfterCalcBaseQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14553]
We would like to add a new event OnValidateQuantityOnAfterCalcBaseQty in the following trigger:

        field(10; Quantity; Decimal)
        {
            Caption = 'Quantity';
            DecimalPlaces = 0 : 5;

            trigger OnValidate()
            var
                WhseItemTrackingSetup: Record "Item Tracking Setup";
            begin
                if not PhysInvtEntered then
                    TestField("Phys. Inventory", false);

                ...
                
                "Qty. (Base)" :=
                    UOMMgt.CalcBaseQty("Item No.", "Variant Code", "Unit of Measure Code", Quantity, "Qty. per Unit of Measure");
                OnValidateQuantityOnAfterCalcBaseQty(Rec, xRec); //A200F0000.Event18.03

                "Qty. (Absolute)" := Abs(Quantity);
                ...
            end;
        }

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnValidateQuantityOnAfterCalcBaseQty(var WarehouseJournalLine: Record "Warehouse Journal Line"; xWarehouseJournalLine: Record "Warehouse Journal Line")
    begin
        //A200F0000.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
