### ISSUE TITLE
[Request property change] table 7311 "Warehouse Journal Line" - "Qty. (Phys. Inventory) (Base)"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14557]
We would like the property editable = false removed from the field 69 "Qty. (Phys. Inventory) (Base)" so the customer is also able to enter values in the base unit of measure, but also to prevent rounding issues with warehouse item tracking lines sumup (Those are always applied on its base quantity). Some extra code tagged with 'A200F0000' is needed to make this work.

        field(69; "Qty. (Phys. Inventory) (Base)"; Decimal)
        {
            Caption = 'Qty. (Phys. Inventory) (Base)';
            DecimalPlaces = 0 : 5;
            Description = 'A200F0000.Event.18.03: Editable=true';
            Editable = true;

            trigger OnValidate()
            begin
                "Qty. (Base)" := "Qty. (Phys. Inventory) (Base)" - "Qty. (Calculated) (Base)";
                "Qty. (Absolute, Base)" := Abs("Qty. (Base)");
                //A200F0000.ns
                if not PhysInvtEntered then begin
                    TestField("Phys. Inventory", true);
                    Validate("Qty. (Phys. Inventory)", UOMMgt.CalcQtyFromBase("Qty. (Phys. Inventory) (Base)", "Qty. per Unit of Measure"));
                end;
                //A200F0000.ne
            end;
        }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
