### ISSUE TITLE
[Request for External] table 7332 "Whse. Internal Put-away Line" - CheckBinContentQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14561]
We would like to set procedure CheckBinContentQty to global (i.e. local = false)

    procedure CheckBinContentQty()
    var
        BinContent: Record "Bin Content";
        WhseInternalPutAwayLine: Record "Whse. Internal Put-away Line";
        AvailQtyBase: Decimal;
    begin
        //A200F0000.Event18.03 local=false
        GetLocation("Location Code");

        if Location."Bin Mandatory" and
           ("Location Code" <> '') and ("From Bin Code" <> '') and
           ("Item No." <> '') and ("Unit of Measure Code" <> '')
        then begin

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
