### ISSUE TITLE
[Event Request] table 7326 "Whse. Worksheet Line" - OnValidateQtyToHandleOnAfterCalcQtyAvailToMove

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14568]
We would like to add a new event OnValidateQtyToHandleOnAfterCalcQtyAvailToMove in the following trigger:

        field(21; "Qty. to Handle"; Decimal)
        {
            Caption = 'Qty. to Handle';
            DecimalPlaces = 0 : 5;
            MinValue = 0;

            trigger OnValidate()
            var
                WhseWkshTemplate: Record "Whse. Worksheet Template";
                Confirmed: Boolean;
                AvailableQty: Decimal;
            begin
                ...
                    end else
                        if WhseWkshTemplate.Type = WhseWkshTemplate.Type::Movement then
                            if CurrFieldNo <> FieldNo("Qty. to Handle") then begin
                                AvailableQty := CheckAvailQtytoMove;
                                OnValidateQtyToHandleOnAfterCalcQtyAvailToMove(Rec, xRec, AvailableQty); //A200F0000.Event18.03
                                if AvailableQty < 0 then
                                    "Qty. to Handle (Base)" := 0
                                else
                                    if "Qty. to Handle (Base)" > AvailableQty then
                                        "Qty. to Handle (Base)" := AvailableQty;
                            end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnValidateQtyToHandleOnAfterCalcQtyAvailToMove(var WhseWorksheetLine: Record "Whse. Worksheet Line"; xWhseWorksheetLine: Record "Whse. Worksheet Line"; var QtyAvailToMoveBase: Decimal)
    begin
        //A200F0000.Event18.03
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
