### ISSUE TITLE
[Event Request] table 8616 "Config. Package Field"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14570]
We have previously requested for events OnValidateFieldOnValidateOnAfterCalcShouldRunCheck and OnIncludeFieldOnValidateOnAfterCalcShouldRunCheck to allow the use of other 'fake' fields. In the base that would be the use of field(11; Dimension; Boolean), but in our case we have extented that functionality with "Item Attribute" and "Item Specifications"

This does not work well with field field(3; "Field ID"; Integer) which has a fixed TableRelation:
TableRelation = IF (Dimension = CONST(false)) Field."No." WHERE(TableNo = FIELD("Table ID"))
This is not extensible. We would like the TableRelation to be modified and add ValidateTableRelation = false together with OnValidate trigger:

        field(3; "Field ID"; Integer)
        {
            Caption = 'Field ID';
            NotBlank = true;
            //TableRelation = IF (Dimension = CONST(false)) Field."No." WHERE(TableNo = FIELD("Table ID")); A100F0001.Event18.05.o  
            TableRelation = Field."No." WHERE(TableNo = FIELD("Table ID")); //A100F0001.Event18.05.n
            ValidateTableRelation = false; //A100F0001.Event18.05.n

            trigger OnValidate()
            var
                Field: Record Field;
                ShouldRunCheck: Boolean;
            begin
                //A100F0001.Event18.05.ns A200F0003.Event18.05.ns
                ShouldRunCheck := not Dimension;
                OnFieldIDOnValidateOnAfterCalcShouldRunCheck(Rec, ShouldRunCheck);
                if ShouldRunCheck then
                    Field.get("Table ID", "Field ID");
                //A100F0001.Event18.05.ne A200F0003.Event18.05.ne
            end;
        }

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnFieldIDOnValidateOnAfterCalcShouldRunCheck(var ConfigPackageField: Record "Config. Package Field"; var ShouldRunCheck: Boolean)
    begin
        //A100F0001.Event18.05.ns A200F0003.Event18.05.ns
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
