### ISSUE TITLE
[Event Request change] table 37 "Sales Line" - OnCalcVATAmountLinesOnBeforeAssignAmtToHandle

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14577]
In a previous request we asked for event OnCalcVATAmountLinesOnBeforeAssignAmtToHandle in procedure CalcVATAmountLines but the call was not placed in the three places requested. We are missing it in the QtyType::General case statement. QtyType::Shipping and QtyType::Invoicing are perfect:

                        case QtyType of
                            QtyType::General:
                                begin
                                    VATAmountLine.Quantity += "Quantity (Base)";
                                    OnCalcVATAmountLinesOnBeforeAssignAmtToHandle(SalesHeader, SalesLine, VATAmountLine, IncludePrepayments, QtyType, QtyToHandle, AmtToHandle); //A108F0084.Event18.05.n
                                    VATAmountLine.SumLine(
                                      "Line Amount", "Inv. Discount Amount", "VAT Difference", "Allow Invoice Disc.", "Prepayment Line");
                                end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
