### ISSUE TITLE
[Event Request] codeunit 8614 "Config. XML Exchange" - OnCreateRecordNodesOnNotFoundOnAfterConfigPackageFieldSetFilters

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14572]
We would like to add a new event OnCreateRecordNodesOnNotFoundOnAfterConfigPackageFieldSetFilters in the following trigger:

    local procedure CreateRecordNodes(var PackageXML: DotNet XmlDocument; ConfigPackageTable: Record "Config. Package Table")
    var
        ...
        end else begin
            RecordNode := PackageXML.CreateElement(GetTableElementName(ConfigPackageTable."Table Name"));
            TableNode.AppendChild(RecordNode);

            ConfigPackageField.SetRange("Package Code", ConfigPackageTable."Package Code");
            ConfigPackageField.SetRange("Table ID", ConfigPackageTable."Table ID");
            ConfigPackageField.SetRange("Include Field", true);
            ConfigPackageField.SetRange(Dimension, false);
            OnCreateRecordNodesOnNotFoundOnAfterConfigPackageFieldSetFilters(ConfigPackageTable, ConfigPackageField); //A100F0001.Event18.05 A200F0003.Event18.05
            if ConfigPackageField.FindSet then
                repeat
                    FieldRef := RecRef.Field(ConfigPackageField."Field ID");
                    FieldNode :=
                      PackageXML.CreateElement(GetFieldElementName(ConfigPackageField.GetValidatedElementName()));
                    FieldNode.InnerText := '';
                    RecordNode.AppendChild(FieldNode);
                    if not ExcelMode then
                        AddFieldAttributes(ConfigPackageField, FieldNode);
                until ConfigPackageField.Next() = 0;

            if ConfigPackageTable."Dimensions as Columns" and ExcelMode then
                AddDimensionFields(ConfigPackageField, RecRef, PackageXML, RecordNode, FieldNode, false);
            OnCreateRecordNodesOnAfterNotFoundRecordProcessed(ConfigPackageTable, ConfigPackageField, RecRef, PackageXML, RecordNode, FieldNode, ExcelMode);
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnCreateRecordNodesOnNotFoundOnAfterConfigPackageFieldSetFilters(ConfigPackageTable: Record "Config. Package Table"; var ConfigPackageField: Record "Config. Package Field")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
