### ISSUE TITLE
[Event Parameter change] report 6653 "Combine Return Receipts" - OnAfterShouldFinalizeSalesInvHeader

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14578]
We would like to add parameter ReturnReceiptHeader: Record "Return Receipt Header" in event OnAfterShouldFinalizeSalesInvHeader

    local procedure ShouldFinalizeSalesInvHeader(SalesOrderHeader: Record "Sales Header"; SalesHeader: Record "Sales Header"; ReturnReceiptLine: Record "Return Receipt Line") Finalize: Boolean
    begin
        Finalize :=
          (SalesOrderHeader."Bill-to Customer No." <> SalesHeader."Bill-to Customer No.") or
          (SalesOrderHeader."Currency Code" <> SalesHeader."Currency Code") or
          (SalesOrderHeader."Dimension Set ID" <> SalesHeader."Dimension Set ID");

        //OnAfterShouldFinalizeSalesInvHeader(SalesOrderHeader, SalesHeader, Finalize, ReturnReceiptLine); A108F0019.Event.o
        OnAfterShouldFinalizeSalesInvHeader(SalesOrderHeader, SalesHeader, Finalize, "Return Receipt Header", ReturnReceiptLine); //A108F0019.Event.n
        exit(Finalize);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterShouldFinalizeSalesInvHeader(var SalesOrderHeader: Record "Sales Header"; SalesHeader: Record "Sales Header"; var Finalize: Boolean; ReturnReceiptHeader: Record "Return Receipt Header"; ReturnReceiptLine: Record "Return Receipt Line")
    begin
        //A108F0019.Event Parameter ReturnReceiptHeader
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
