### ISSUE TITLE
[Event Request Change] page 8626 "Config. Package Records" - OnBeforeValidatePackageData

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14571]
In a previous request we asked for an event OnBeforeValidatePackageData. A small detail was forgotten when implementing that event. A CurrPage.Update() statement was forgotten when before performing the exit: 

    local procedure ValidatePackageData(ColumnID: Integer)
    var
        ...
        IsHandled := false;
        OnBeforeValidatePackageData(Rec, MatrixCellData, PackageColumnField, ColumnID, IsHandled);
        //A100F0001.Event18.05.os A200F0003.Event18.05.os
        //if IsHandled then
        //    exit;
        //A100F0001.Event18.05.oe A200F0003.Event18.05.oe
        //A100F0001.Event18.05.ns A200F0003.Event18.05.ns
        if IsHandled then begin
            CurrPage.Update();
            exit;
        end;
        //A100F0001.Event18.05.ne A200F0003.Event18.05.ne

        MatrixCellData[ColumnID] := DelChr(MatrixCellData[ColumnID], '<>', ' ');

**Comment by Stepanenko-Vadim** [comment]
I will add IncludeSender in the publisher of this event, so you can call update from sender param if you need it.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
