### ISSUE TITLE
[Event Request change] codeunit 6500 "Item Tracking Management" - OnSynchronizeItemTracking2OnAfterSyncBothTrackingSpec

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14576]
We would like to add parameter TempTrkgSpec1 to event OnSynchronizeItemTracking2OnAfterSyncBothTrackingSpec:

    local procedure SynchronizeItemTracking2(var FromReservEntry: Record "Reservation Entry"; ToRowID: Text[250]; DialogText: Text[250])
            ...

            if TempTrkgSpec1.FindSet() then
                repeat
                    TempTrkgSpec2.SetTrackingFilterFromSpec(TempTrkgSpec1);
                    if TempTrkgSpec2.FindFirst() then begin
                        ShouldInsertTrkgSpec := TempTrkgSpec2."Quantity (Base)" * SignFactor2 <> TempTrkgSpec1."Quantity (Base)" * SignFactor1;
                        OnSynchronizeItemTracking2OnAfterCalcShouldInsertTrkgSpec(TempTrkgSpec1, TempTrkgSpec2, TempTrkgSpec3, SignFactor1, SignFactor2, ShouldInsertTrkgSpec);
                        if ShouldInsertTrkgSpec then begin
                            TempTrkgSpec3 := TempTrkgSpec2;
                            //OnSynchronizeItemTracking2OnAfterSyncBothTrackingSpec(TempTrkgSpec3, TempTrkgSpec2, TempSourceSpec); A200F0000.Event18.05.o
                            OnSynchronizeItemTracking2OnAfterSyncBothTrackingSpec(TempTrkgSpec3, TempTrkgSpec2, TempSourceSpec, TempTrkgSpec1); //A200F0000.Event18.05.n
                            TempTrkgSpec3.Validate("Quantity (Base)",
                              (TempTrkgSpec1."Quantity (Base)" * SignFactor1 - TempTrkgSpec2."Quantity (Base)" * SignFactor2));
                            TempTrkgSpec3."Entry No." := LastEntryNo + 1;
                            TempTrkgSpec3.Insert();
                        end;
                        OnSynchronizeItemTracking2OnBeforeDeleteSyncedTrackingSpec(
                            TempTrkgSpec3, TempTrkgSpec1, TempTrkgSpec2, SignFactor1, SignFactor2, LastEntryNo);
                        TempTrkgSpec2.Delete();

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnSynchronizeItemTracking2OnAfterSyncBothTrackingSpec(var TempTrkgSpec3: Record "Tracking Specification" temporary; TempTrkgSpec2: Record "Tracking Specification" temporary; TempSourceSpec: Record "Tracking Specification" temporary; TempTrkgSpec1: Record "Tracking Specification" temporary)
    begin
        //A200F0000.Event18.05 Parameter TempTrkgSpec1
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
