### ISSUE TITLE
[Request change] codeunit 7153 "Item Analysis Management" - FindRec & NextRec

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14573]
We would like to change the parameter of ItemAnalysisView: Record "Item Analysis View" in the procedures FindRec and NextRec from value to var. In our addon we pass other parameters by creating new fields and setting filters. Those values are needed in the events OnElseFindRec and OnElseNextRec we have requested in issues:

https://github.com/microsoft/ALAppExtensions/issues/13191
https://github.com/microsoft/ALAppExtensions/issues/13192

A suggestion for the future would be to pass on Dim1Filter, Dim2Filter and Dim3Filter also with a record filter instead of fixed parameter values which are not extensible.

procedure FindRec(var ItemAnalysisView: Record "Item Analysis View"; DimOption: Option Item,Period,Location,"Dimension 1","Dimension 2","Dimension 3"; var DimCodeBuf: Record "Dimension Code Buffer"; Which: Text[250]; ItemFilter: Code[250]; LocationFilter: Code[250]; PeriodType: Option Day,Week,Month,Quarter,Year,"Accounting Period"; var DateFilter: Text[30]; var PeriodInitialized: Boolean; InternalDateFilter: Text[30]; Dim1Filter: Code[250]; Dim2Filter: Code[250]; Dim3Filter: Code[250]): Boolean

procedure NextRec(var ItemAnalysisView: Record "Item Analysis View"; DimOption: Option Item,Period,Location,"Dimension 1","Dimension 2","Dimension 3"; var DimCodeBuf: Record "Dimension Code Buffer"; Steps: Integer; ItemFilter: Code[250]; LocationFilter: Code[250]; PeriodType: Option Day,Week,Month,Quarter,Year,"Accounting Period"; DateFilter: Text[30]; Dim1Filter: Code[250]; Dim2Filter: Code[250]; Dim3Filter: Code[250]): Integer

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
