### ISSUE TITLE
[Event Parameter change] codeunit 22 "Item Jnl.-Post Line" - OnBeforeFlushOperation and PostFlushedConsump

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14589]
In our addon we are in dire need of some extra critical component flushing with item tracking when flushing is manual and the first operation starts with a particular component "Lot No.".

The event OnBeforeFlushOperation needs the global variable LastOperation as a new parameter and more importantly the property IncludeSender = true set. We all know what happens if you are not in possession of the last item ledger entry no. or current item register etc. 

We would like to reuse procedure PostFlushedConsump in that case and for it to work it must be set to local = false. In a subscriber codeunit we can then us: 
sender.PostFlushedConsump(ProdOrder, ProdOrderLine, ProdOrderComponent, ProdOrderRoutingLine, ItemJnlLine);

    local procedure FlushOperation(ProdOrder: Record "Production Order"; ProdOrderLine: Record "Prod. Order Line")
    var
        ProdOrderRoutingLine: Record "Prod. Order Routing Line";
        ProdOrderComp: Record "Prod. Order Component";
        OldItemJnlLine: Record "Item Journal Line";
        OldTempSplitItemJnlLine: Record "Item Journal Line" temporary;
        OldItemTrackingCode: Record "Item Tracking Code";
        OldItemTrackingSetup: Record "Item Tracking Setup";
        xCalledFromInvtPutawayPick: Boolean;
    begin
        //OnBeforeFlushOperation(ProdOrder, ProdOrderLine, ItemJnlLine); A200F0000.Event.o
        OnBeforeFlushOperation(ProdOrder, ProdOrderLine, ItemJnlLine, LastOperation); //A200F0000.Event.n

Event Signature:

    [IntegrationEvent(true, false)]
    local procedure OnBeforeFlushOperation(var ProdOrder: Record "Production Order"; var ProdOrderLine: Record "Prod. Order Line"; var ItemJnlLine: Record "Item Journal Line"; LastOperation: Boolean);
    begin
        //A200F0000.Event Parameter LastOperation; IncludeSender = true
    end;

    procedure PostFlushedConsump(ProdOrder: Record "Production Order"; ProdOrderLine: Record "Prod. Order Line"; ProdOrderComp: Record "Prod. Order Component"; var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; OldItemJnlLine: Record "Item Journal Line")
    var
        ...
        IsHandled: Boolean;
    begin
        //A108F0000.Event18.03 local=false

**Comment by Oleg-Romashkov** [comment]
Please create a dedicated request for making PostFlushedConsump global
