### ISSUE TITLE
[Event Request] Codeunit 99000778 OrderTrackingManagement - OnAfterSetSoucreRecord 

### ISSUE THREAD

**Issue by petroLubchenko** [microsoft/ALAppExtensions#14581]
Hi, would it be possible to modify the **OnAfterSetSoucreRecord** event in codeunit 99000778 (**OrderTrackingManagement**) by adding  the **ItemLedgEntry2** parameter (with **var** keyword), like this:
```AL
    procedure SetSourceRecord(var SourceRecordVar: Variant)
    begin
        // Modified Event begin
        // OnAfterSetSoucreRecord(SourceRecordVar, ReservEntry, CaptionText);
        OnAfterSetSoucreRecord(SourceRecordVar, ReservEntry, ItemLedgEntry2, CaptionText);
        // Modified Event end
    end;
```
```AL
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetSoucreRecord(var SourceRecordVar: Variant; var ReservationEntry: Record "Reservation Entry"; var ItemLedgEntry2: Record "Item Ledger Entry"; var CaptionText: Text)
    begin
    end;
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
