### ISSUE TITLE
[Additional publisher] Codeunit 225, Gen. Jnl.-Apply, OnApplyVendorLedgerEntryOnBeforeModify

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#14582]
Hi Team,

In codeunit 225 - "Gen. Jnl.-Apply", we need possibility to process more on function "ApplyVendorLedgerEntry". Standard publisher OnApplyVendorLedgerEntryOnBeforeModify may help us:
![GenJnlApply-OnApplyVendorLedgerEntryOnBeforeModify](https://user-images.githubusercontent.com/91654106/135400646-1791d1fe-8a22-47ba-828a-1bc7edbfd51c.png)

[IntegrationEvent(false, false)]
local procedure OnApplyVendorLedgerEntryOnBeforeModify (var GenJnlLine: Record "Gen. Journal Line"; VendorLedgEntry: Record "Vendor Ledger Entry")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
