### ISSUE TITLE
[Event Parameter change] codeunit 22 "Item Jnl.-Post Line" - OnBeforeInsertPhysInvtLedgEntry

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14586]
We would like to add parameter ItemJnlLine to event OnBeforeInsertPhysInvtLedgEntry. We need the item tracking fields to add to the PhysInvtLedgEntry. Lot No., Serial No., Packing No. are not available at this point.

            //OnBeforeInsertPhysInvtLedgEntry(PhysInvtLedgEntry, ItemJnlLineOrigin); A200F0000.Event.o
            OnBeforeInsertPhysInvtLedgEntry(PhysInvtLedgEntry, ItemJnlLineOrigin, ItemJnlLine); //A200F0000.Event.n

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertPhysInvtLedgEntry(var PhysInventoryLedgerEntry: Record "Phys. Inventory Ledger Entry"; ItemJournalLine: Record "Item Journal Line"; LastSplitItemJournalLine: Record "Item Journal Line")
    begin
        //A200F0000.Event Parameter LastSplitItemJournalLine
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
