### ISSUE TITLE
[Event Request] CodeUnit 1535 "Approvals Mgmt." - OnCheckPurchaseApprovalPossibleOnBeforeCheckPurchaseHeader

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#14580]
Hello,

In the request https://github.com/microsoft/ALAppExtensions/issues/13685 we wanted an event with this structure:

    procedure CheckPurchaseApprovalPossible(var PurchaseHeader: Record "Purchase Header"): Boolean
    begin
        if not IsPurchaseApprovalsWorkflowEnabled(PurchaseHeader) then
            Error(NoWorkflowEnabledErr);

	IsHandled := false;
	OnCheckPurchaseApprovalPossibleOnBeforeCheckPurchaseHeader(PurchaseHeader,IsHandled);
        if IsHandled then
            exit(true);

        if not PurchaseHeader.PurchLinesExist then
            Error(NothingToApproveErr);

        OnAfterCheckPurchaseApprovalPossible(PurchaseHeader);

        exit(true);
    end;

In 18.5 version, the event **OnBeforeCheckPurchaseApprovalPossible** was implemented with this structure:

    procedure CheckPurchaseApprovalPossible(var PurchaseHeader: Record "Purchase Header") Result: Boolean
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckPurchaseApprovalPossible(PurchaseHeader, Result, IsHandled);
        if IsHandled then
            exit(Result);

        if not IsPurchaseApprovalsWorkflowEnabled(PurchaseHeader) then
            Error(NoWorkflowEnabledErr);

        if not PurchaseHeader.PurchLinesExist then
            Error(NothingToApproveErr);

        OnAfterCheckPurchaseApprovalPossible(PurchaseHeader);

        exit(true);
    end;

The issue we initially had was that we wanted to execute the code 
**if not PurchaseHeader.PurchLinesExist then
            Error(NothingToApproveErr);**
only in a certain condition and then exit with true.

Now, by using the event OnBeforeCheckPurchaseApprovalPossible and adding our condition there, in case the condition is true, the IsHandled will be true and the rest of the code will not be executed. This is not ok, because we want the check on IsPurchaseApprovalsWorkflowEnabled to be always executed.
Is it possible to provide us an event after the check on IsPurchaseApprovalsWorkflowEnabled, as it was in the initial request?

Thank you!

**Comment by Stepanenko-Vadim** [comment]
The **IsHandled** will be true only if you set it to **true**, if you leave it as **false** in your subscriber - the rest of the code will be executed...
Please clarify the scenario a bit more, because it seems like you can do everything with this subscriber, in the worst case you can copy the 1st check, the 2nd check or both into subscriber in different orders, whichever works for you. Adding a 3rd event in a two-liner procedure seems like an overkill :)

**Comment by CameliaPopescu** [comment]
We need to execute the check 
            **if not PurchaseHeader.PurchLinesExist then
                Error(NothingToApproveErr);**
only in a certain condition.
If we don't set the IsHandled to true, then we will execute the code above and get the error NothingToApproveErr even when we don't want it.
That's why we initially requested an event before this check, in order to skip it in a certain condition.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
