### ISSUE TITLE
[Event Parameter change] codeunit 99000830 "Create Reserv. Entry" - OnTransferReservEntryOnBeforeUpdateItemTracking

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14583]
We were having issues that with order-to-order salesline to prodorderline reservations with item tracking that it did not properly populate all item tracking values like "Expiration Date", "Warranty Date" and our addon fields from the supply to demand reservation entry. We are in need of a new variable CarriedReservationEntry and use it in event OnTransferReservEntryOnBeforeUpdateItemTracking:

    procedure TransferReservEntry(NewType: Option; NewSubtype: Integer; NewID: Code[20]; NewBatchName: Code[10]; NewProdOrderLine: Integer; NewRefNo: Integer; QtyPerUOM: Decimal; OldReservEntry: Record "Reservation Entry"; TransferQty: Decimal): Decimal
    var
        NewReservEntry: Record "Reservation Entry";
        ...
        CarriedReservationEntry: Record "Reservation Entry";
    begin
        if TransferQty = 0 then
            exit;
        ...
                        // If an order-to-order supply is being posted, item tracking must be carried to the related demand:
                if (TransferQty >= 0) and (NewReservEntry.Binding = NewReservEntry.Binding::"Order-to-Order") then begin
                    CarriedReservationEntry := InsertReservEntry; //A200F0000.Event.n
                    CarriedItemTrackingSetup.CopyTrackingFromReservEntry(NewReservEntry);
                    if not UseQtyToHandle then
                        // the IT is set only in Consumption/Output Journal and we need to update all fields properly
                        QtyToInvoiceThisLine := NewReservEntry."Quantity (Base)";
                end;
        ...
                if CarriedItemTrackingSetup.TrackingExists() then begin
            if NewReservEntry."Qty. to Handle (Base)" = 0 then
                NewReservEntry.Validate("Quantity (Base)");
            NewReservEntry.CopyTrackingFromItemTrackingSetup(CarriedItemTrackingSetup);
            //OnTransferReservEntryOnBeforeUpdateItemTracking(NewReservEntry); A200F0000.Event.o
            OnTransferReservEntryOnBeforeUpdateItemTracking(NewReservEntry, CarriedReservationEntry); //A200F0000.Event.n
            NewReservEntry.UpdateItemTracking;
            if NewReservEntry.Modify then;
        end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnTransferReservEntryOnBeforeUpdateItemTracking(var ReservationEntry: Record "Reservation Entry"; CarriedReservationEntry: Record "Reservation Entry")
    begin
        //A200F0000.Event Parameter CarriedReservationEntry
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
