### ISSUE TITLE
[Page Search Request] Make Purchase Lines/Sales Lines/Posted Purchase Receipt Lines Pages Searchable

### ISSUE THREAD

**Issue by RWeston6** [microsoft/ALAppExtensions#14597]
Could you please add ApplicationArea/UsageCategory to the Purchase Lines(518), Sales Lines(516) and Posted Purchase Receipt Lines(528) so they can be found from the Search

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45238.
