### ISSUE TITLE
[Event Parameter change] table 99000829 "Planning Component" - OnBeforeGetWMSDefaultBin

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14599]
1. Maybe change FALSE in false
2. Maybe set Location as a parameter of function GetWMSDefaultBin also.

local procedure GetWMSDefaultBin(): Code[20]
    var
        WMSManagement: Codeunit "WMS Management";
        BinCode: Code[20];
        IsHandled: Boolean;
    begin
        IsHandled := FALSE;
        //OnBeforeGetWMSDefaultBin(Rec, BinCode, IsHandled); A200F0000.Event.o
        OnBeforeGetWMSDefaultBin(Rec, Location, BinCode, IsHandled); //A200F0000.Event.n
        if not IsHandled then
            if Location."Bin Mandatory" and not Location."Directed Put-away and Pick" then
                WMSManagement.GetDefaultBin("Item No.", "Variant Code", "Location Code", BinCode);
        exit(BinCode);
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetWMSDefaultBin(var PlanningComponent: Record "Planning Component"; Location: Record Location; var BinCode: Code[20]; var IsHandled: Boolean)
    begin
        //A200F0000.Event Parameter Location
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
