### ISSUE TITLE
[Additional publisher] Codeunit 410, Update Analysis View, OnBeforeUpdateEntriesForGLAccount

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#14594]
Hi Team,

In codeunit 410 - "Update Analysis View", we need possibility to process more on function "UpdateEntriesForGLAccount". Standard publisher OnBeforeUpdateEntriesForGLAccount may help us:

![UpdateAnalysisView-OnBeforeUpDateEntriesForGLAccount](https://user-images.githubusercontent.com/91654106/135421595-95ef280a-02ca-4047-bd67-d0b7490fcbd0.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateEntriesForGLAccount(var TempAnalysisViewEntry: Record "Analysis View Entry" temporary; AnalysisView: Record "Analysis View"; LastGLEntryNo: Integer; var NoOfEntries: Integer; var IsHandled: Boolean)
begin
end;

**Comment by Oleg-Romashkov** [comment]
Please create dedicated request for making function global

**Comment by GiangLNT56** [comment]
Hi, 
I have created another request. 
Please help me to process.

Thank you.

**Comment by Stepanenko-Vadim** [comment]
This has been implemented already several updates ago, closing the issue. The tag 'ships-in-future-update' is for housekeeping.
