### ISSUE TITLE
[Event Parameter change] codeunit 22 "Item Jnl.-Post Line" - OnPostFlushedConsumpOnAfterCalcQtyToPost

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14590]
We would like to add parameter OldItemJnlLine in event OnPostFlushedConsumpOnAfterCalcQtyToPost:

        QtyToPost := UOMMgt.RoundToItemRndPrecision(QtyToPost, CompItem."Rounding Precision");
        //OnPostFlushedConsumpOnAfterCalcQtyToPost(ProdOrder, ProdOrderLine, ProdOrderComp, OutputQtyBase, QtyToPost); A200F0000.Event.o
        OnPostFlushedConsumpOnAfterCalcQtyToPost(ProdOrder, ProdOrderLine, ProdOrderComp, OldItemJnlLine, OutputQtyBase, QtyToPost); //A200F0000.Event.n
        if QtyToPost = 0 then
            exit;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnPostFlushedConsumpOnAfterCalcQtyToPost(ProductionOrder: Record "Production Order"; ProdOrderLine: Record "Prod. Order Line"; ProdOrderComponent: Record "Prod. Order Component"; var ItemJournalLine: Record "Item Journal Line"; ActOutputQtyBase: Decimal; var QtyToPost: Decimal)
    begin
        //A200F0000.Event Parameter ItemJournalLine
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
