### ISSUE TITLE
[Event Parameter change] table 233 "Item Journal Batch" - OnAfterSetupNewBatch

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14592]
//OnAfterSetupNewBatch(Rec); A108F0009.Event.o
	    OnAfterSetupNewBatch(Rec, ItemJnlTemplate); //A108F0009.Event.n

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetupNewBatch(var ItemJournalBatch: Record "Item Journal Batch"; ItemJnlTemplate: Record "Item Journal Template")
    begin
        //A108F0009.Event Parameter ItemJnlTemplate
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
