### ISSUE TITLE
[Event Parameter change] codeunit 6520 "Item Tracing Mgt." - OnAfterTransferData

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14598]
//OnAfterTransferData(ItemLedgEntry,TempTrackEntry); A200F0000.Event.o
        OnAfterTransferData(ItemLedgEntry, TempTrackEntry, ValueEntry); //A200F0000.Event.n

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterTransferData(var ItemLedgerEntry: Record "Item Ledger Entry"; var TempItemTracingBuffer: Record "Item Tracing Buffer" temporary; ValueEntry: Record "Value Entry")
    begin
        //A200F0000.Event Parameter ValueEntry
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
