### ISSUE TITLE
[Event Parameter change] codeunit 22 "Item Jnl.-Post Line" - OnPostConsumptionOnBeforeCalcRemainingQuantity

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14591]
We would like to add parameter RemQtyToPost in event OnPostConsumptionOnBeforeCalcRemainingQuantity

                    IsHandled := false;
                    //OnPostConsumptionOnBeforeCalcRemainingQuantity(ProdOrderComp, ItemJnlLine, NewRemainingQty, QtyToPost, IsHandled); //A200F0000.Event.o
                    OnPostConsumptionOnBeforeCalcRemainingQuantity(ProdOrderComp, ItemJnlLine, NewRemainingQty, QtyToPost, RemQtyToPost, IsHandled); //A200F0000.Event.n
                    if not IsHandled then
                        "Remaining Quantity" := Round("Remaining Qty. (Base)" / "Qty. per Unit of Measure", UOMMgt.QtyRndPrecision);

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnPostConsumptionOnBeforeCalcRemainingQuantity(var ProdOrderComp: Record "Prod. Order Component"; var ItemJnlLine: Record "Item Journal Line"; var NewRemainingQty: Decimal; var QtyToPost: Decimal; var RemQtyToPost: Decimal; var IsHandled: Boolean)
    begin
        //A200F0000.Event Parameter RemQtyToPost
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
