### ISSUE TITLE
[Event Parameter change] table 99000829 "Planning Component" - OnValidateRoutingLinkCodeOnBeforeValidateDueDate

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14600]
//OnValidateRoutingLinkCodeOnBeforeValidateDueDate(Rec, ReqLine); A108F0079.Event.o
OnValidateRoutingLinkCodeOnBeforeValidateDueDate(Rec, ReqLine, PlanningRtngLine); //A108F0079.Event.n

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnValidateRoutingLinkCodeOnBeforeValidateDueDate(var PlanningComponent: Record "Planning Component"; RequisitionLine: Record "Requisition Line"; var PlanningRoutingLine: Record "Planning Routing Line")
    begin
        //A108F0079.Event Parameter PlanningRoutingLine
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
