### ISSUE TITLE
[Event Parameter change] table 38 "Purchase Header" - OnAfterCopyAddressInfoFromOrderAddress

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14605]
//OnAfterCopyAddressInfoFromOrderAddress(OrderAddr); A108B0064.Event.o
        OnAfterCopyAddressInfoFromOrderAddress(Rec, OrderAddr); //A108B0064.Event.n

Event Signature:

    [IntegrationEvent(true, false)]
    local procedure OnAfterCopyAddressInfoFromOrderAddress(var PurchaseHeader: Record "Purchase Header"; var OrderAddress: Record "Order Address")
    begin
        //A108B0064.Event Parameter PurchaseHeader
    end;

**Comment by Oleg-Romashkov** [comment]
Parameter will be added. However, event has IncludeSender = true, so you can use it now

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
