### ISSUE TITLE
[Event Parameter change] table 38 "Purchase Header" - OnValidatePurchaseHeaderPayToVendorNoOnBeforeCheckDocType

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14608]
Event OnValidatePurchaseHeaderPayToVendorNo should be set to obsolete and OnValidatePurchaseHeaderPayToVendorNoOnBeforeCheckDocType should be modified with SkipPayToContact: Boolean

                Validate("Creditor No.", Vend."Creditor No.");
                OnValidatePurchaseHeaderPayToVendorNo(Vend, Rec);
                //OnValidatePurchaseHeaderPayToVendorNoOnBeforeCheckDocType(Vend, Rec, xRec); A108F0013.Event18.05.o
                OnValidatePurchaseHeaderPayToVendorNoOnBeforeCheckDocType(Vend, Rec, xRec, SkipPayToContact); //A108F0013.Event18.05.n

                if "Document Type" = "Document Type"::Order then

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnValidatePurchaseHeaderPayToVendorNoOnBeforeCheckDocType(Vendor: Record Vendor; var PurchaseHeader: Record "Purchase Header"; var xPurchaseHeader: Record "Purchase Header"; SkipPayToContact: Boolean)
    begin
        //A108F0013.Event Parameter SkipPayToContact
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
