### ISSUE TITLE
[Event Parameter change] codeunit 5407 "Prod. Order Status Management" - OnAfterSetTimeAndQuantityOmItemJnlLine

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14602]
//OnAfterSetTimeAndQuantityOmItemJnlLine(ItemJnlLine, ProdOrderRtngLine); A200F0000.Event.o
            OnAfterSetTimeAndQuantityOmItemJnlLine(ItemJnlLine, ProdOrderRtngLine, OutputQtyBase, OutputQty); //A200F0000.Event.n

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetTimeAndQuantityOmItemJnlLine(var ItemJournalLine: Record "Item Journal Line"; ProdOrderRoutingLine: Record "Prod. Order Routing Line"; OutputQtyBase: Decimal; OutputQty: Decimal)
    begin
        //A200F0000.Event Parameters OutputQtyBase, OutputQty
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
