### ISSUE TITLE
[Event Parameter change] codeunit 5510 "Production Journal Mgt" - OnInsertOutputItemJnlLineOnAfterItemJnlLineInit

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14604]
//OnInsertOutputItemJnlLineOnAfterItemJnlLineInit(ItemJnlLine, ProdOrderLine); 
            OnInsertOutputItemJnlLineOnAfterItemJnlLineInit(ItemJnlLine, ProdOrderLine, ItemJnlTemplate, ItemJnlBatch); //A200F0000.Event.n

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnInsertOutputItemJnlLineOnAfterItemJnlLineInit(var ItemJnlLine: Record "Item Journal Line"; ProdOrderLine: Record "Prod. Order Line"; ItemJournalTemplate: Record "Item Journal Template"; ItemJournalBatch: Record "Item Journal Batch")
    begin
    	//A200F0000.Event Parameters ItemJournalTemplate, ItemJournalBatch
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
