### ISSUE TITLE
[Event Parameter change] table 5407 "Prod. Order Component" - OnValidateRoutingLinkCodeBeforeValidateDueDate

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14601]
//OnValidateRoutingLinkCodeBeforeValidateDueDate(Rec, ProdOrderLine); A108F0079.Event.o
  OnValidateRoutingLinkCodeBeforeValidateDueDate(Rec, ProdOrderLine, ProdOrderRtngLine); //A108F0079.Event.n

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnValidateRoutingLinkCodeBeforeValidateDueDate(var ProdOrderComponent: Record "Prod. Order Component"; var ProdOrderLine: Record "Prod. Order Line"; var ProdOrderRoutingLine: Record "Prod. Order Routing Line")
    begin
        //A108F0079.Event Parameter ProdOrderRoutingLine
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
