### ISSUE TITLE
[Event Parameter change] table 38 "Purchase Header" - OnAfterSetShipToForSpecOrder

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14606]
//OnAfterSetShipToForSpecOrder(Rec); A108F0011.Event.o
        OnAfterSetShipToForSpecOrder(Rec, Location, CompanyInfo); //A108F0026.Event.n

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetShipToForSpecOrder(var PurchaseHeader: Record "Purchase Header"; Location: Record Location; CompanyInformation: Record "Company Information")
    begin
        //A108F0011.Event Parameters Location and CompanyInformation
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
