### ISSUE TITLE
[Event Parameter change] codeunit 90 "Purch.-Post" - OnBeforeReturnShptHeaderInsert

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14611]
//OnBeforeReturnShptHeaderInsert(ReturnShptHeader, PurchHeader, SuppressCommit); A109F0000.Event.o
                OnBeforeReturnShptHeaderInsert(ReturnShptHeader, PurchHeader, SuppressCommit, TempWhseRcptHeader, WhseReceive, TempWhseShptHeader, WhseShip); //A109F0000.Event.n

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeReturnShptHeaderInsert(var ReturnShptHeader: Record "Return Shipment Header"; var PurchHeader: Record "Purchase Header"; CommitIsSupressed: Boolean; WarehouseReceiptHeader: Record "Warehouse Receipt Header"; WhseReceive: Boolean; WarehouseShipmentHeader: Record "Warehouse Shipment Header"; WhseShip: Boolean)
    begin
        //A109F0000.Event Parameters
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
