### ISSUE TITLE
[Event Parameter change] table 36 "Sales Header" - OnBeforeSalesLineByChangedFieldNo

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14612]
//OnBeforeSalesLineByChangedFieldNo(Rec, SalesLine, ChangedFieldNo, IsHandled); A108F0071.Event.o
                OnBeforeSalesLineByChangedFieldNo(Rec, xRec, SalesLine, ChangedFieldNo, IsHandled); //A108F0071.Event.n

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesLineByChangedFieldNo(var SalesHeader: Record "Sales Header"; xSalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; ChangedFieldNo: Integer; var IsHandled: Boolean)
    begin
        //A108F0071.Event Parameter xSalesHeader
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
