### ISSUE TITLE
[Event Request] codeunit 80 "Sales-Post" - OnSumSalesLines2OnAfterDivideAmount

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14619]
We would like to add a new event OnSumSalesLines2OnAfterDivideAmount in the following trigger:

    local procedure SumSalesLines2(SalesHeader: Record "Sales Header"; var NewSalesLine: Record "Sales Line"; var OldSalesLine: Record "Sales Line"; QtyType: Option General,Invoicing,Shipping; InsertSalesLine: Boolean; CalcAdCostLCY: Boolean; var TotalAdjCostLCY: Decimal; IncludePrepayments: Boolean)
                    ...

                    IsHandled := false;
                    OnSumSalesLines2OnBeforeDivideAmount(OldSalesLine, IsHandled, SalesHeader, SalesLine, QtyType, SalesLineQty, TempVATAmountLine, TempVATAmountLineRemainder, IncludePrepayments);
                    if not IsHandled then
                        DivideAmount(SalesHeader, SalesLine, QtyType, SalesLineQty, TempVATAmountLine, TempVATAmountLineRemainder, IncludePrepayments);
                    OnSumSalesLines2OnAfterDivideAmount(OldSalesLine, SalesLineQty, QtyType); //A108F0084.Event
                    SalesLine.Quantity := SalesLineQty;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnSumSalesLines2OnAfterDivideAmount(var OldSalesLine: Record "Sales Line"; var SalesLineQty: Decimal; QtyType: Option General,Invoicing,Shipping)
    begin
        //A108F0084.Event
    end;

**Comment by Stepanenko-Vadim** [comment]
This has been implemented already several updates ago, closing the issue. The tag 'ships-in-future-update' is for housekeeping.
