### ISSUE TITLE
[Event Parameter change] table 5902 "Service Line" - OnAfterAssignGLAccountValues

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14621]
//OnAfterAssignGLAccountValues(Rec, GLAcc); A108F0025.Event.o
        OnAfterAssignGLAccountValues(Rec, ServHeader, GLAcc); //A108F0025.Event.n

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignGLAccountValues(var ServiceLine: Record "Service Line"; ServiceHeader: Record "Service Header"; GLAccount: Record "G/L Account")
    begin
        //A108F0025.Event Parameter ServiceHeader
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
