### ISSUE TITLE
[Event Parameter change] codeunit 7304 "Whse. Jnl.-Register Batch" - OnBeforeWhseJnlRegisterLineRun

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#14631]
//OnBeforeWhseJnlRegisterLineRun(TempWhseJnlLine2); A109F0003.Event.o
                        OnBeforeWhseJnlRegisterLineRun(TempWhseJnlLine2, WhseJnlTemplate); //A109F0003.Event.n

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeWhseJnlRegisterLineRun(var TempWarehouseJournalLine: Record "Warehouse Journal Line" temporary; WarehouseJournalTemplate: Record "Warehouse Journal Template")
    begin
        //A109F0003.Event Parameter WhseJnlTemplate
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
