### ISSUE TITLE
[Key Request] - ValueEntry.Table.al - Key7

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#14636]
We would like to request the following key change:
Object: ValueEntry.Table.al
Reason: There is one missing field for Key7, which will slow down the performance on large databases for the procedure SumCostsTillValuationDate on ValueEntry.Table.

Those fields are defined as SumIndexFields:
*"Cost Amount (Expected)", "Cost Amount (Actual)", "Cost Amount (Expected) (ACY)", "Cost Amount (Actual) (ACY)", "Item Ledger Entry Quantity"*

Those fields are used for the CalcSums:
*"Cost Amount (Expected)", "Cost Amount (Actual)", "Cost Amount (Expected) (ACY)", "Cost Amount (Actual) (ACY)", "Item Ledger Entry Quantity"*, **"Invoiced Quantity"**

```al
procedure SumCostsTillValuationDate(var ValueEntry: Record "Value Entry")
var
    ...
begin
    ...
        SetCurrentKey("Item No.", "Valuation Date", "Location Code", "Variant Code");
        ...
        CalcSums(
          "Item Ledger Entry Quantity", "Invoiced Quantity",
          "Cost Amount (Actual)", "Cost Amount (Actual) (ACY)",
          "Cost Amount (Expected)", "Cost Amount (Expected) (ACY)");
        OnSumCostsTillValuationDateOnAfterCalcSums(Rec);
        ...
end;
```

New Key configuration:
```al
key(Key7; "Item No.", "Valuation Date", "Location Code", "Variant Code")
{
    SumIndexFields = "Cost Amount (Expected)", "Cost Amount (Actual)", "Cost Amount (Expected) (ACY)", "Cost Amount (Actual) (ACY)", "Item Ledger Entry Quantity", "Invoiced Quantity";
}
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
