### ISSUE TITLE
[Event Request] codeunit 99000854 "Inventory Profile Offsetting"

### ISSUE THREAD

**Issue by ClaudioNuBe** [microsoft/ALAppExtensions#14632]
Is it possible to have a new event like this?

```
local procedure AllowLotAccumulation(SupplyInvtProfile: Record "Inventory Profile"; DemandDueDate: Date) AccumulationOK: Boolean
    var
        IsHandled: Boolean;
    begin
        //start New Event
        OnBeforeAllowLotAccumulation(IsHandled, AccumulationOK, SupplyInvtProfile, DemandDueDate, TempSKU);
        if IsHandled then
            exit(AccumulationOK);
        //end New Event
        AccumulationOK := CalcDate(TempSKU."Lot Accumulation Period", SupplyInvtProfile."Due Date") >= DemandDueDate;
    end;

    //New Event
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAllowLotAccumulation(var IsHandled: Boolean; var AccumulationOK: Boolean; SupplyInvtProfile: Record "Inventory Profile"; DemandDueDate: Date; var TempSku: Record "Stockkeeping Unit" temporary)
    begin
    end;
```

The aim of the request is to skip the accumulation of the need also in the same days for the companies that wants to manage safety stocks or order changers but wants to have a direct connection between the need and the supply proposal also if the needs are in the same day.
So the expected result will be to have X lines in the planning worksheet for the same date and item for X lines of need for that item in the same date
Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
