### ISSUE TITLE
[Protection Level] page 7003 "Duplicate Price Lines" - visible variables

### ISSUE THREAD

**Issue by BertDeTemmerman** [microsoft/ALAppExtensions#14650]
Similar to #14649 
Could it be possible on page 7003 "Duplicate Price Lines" to have the global variables, that are set in the procedure `Set` , be protected?
If we add fields to the page, we can check based on those global variables if they should be also visible.

```
procedure Set(PriceType: Enum "Price Type"; AmountType: Enum "Price Amount Type"; var DuplicatePriceLine: Record "Duplicate Price Line")
    begin
        Rec.Copy(DuplicatePriceLine, true);
        DiscountVisible := AmountType in ["Price Amount Type"::Any, "Price Amount Type"::Discount];
        PriceVisible := AmountType in ["Price Amount Type"::Any, "Price Amount Type"::Price];
        IsSalesPrice := PriceType = "Price Type"::Sale;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
