### ISSUE TITLE
[Request for Protected vars] Page 403 "Purchase Order Statistics"

### ISSUE THREAD

**Issue by SteinleMossGaewers** [microsoft/ALAppExtensions#14676]
Hello,

we need multiple vars in the Page 403 "Purchase Order Statistics" as protected vars in order to use them in our modfied calculation.

The vars we need are:
TotalAmount1: array[3] of Decimal;
TotalAmount2: array[3] of Decimal;
i: Integer;
VATAmount: array[3] of Decimal;

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
