### ISSUE TITLE
Temporary table (global variable) in report not saved in preview

### ISSUE THREAD

**Issue by louagej** [microsoft/ALAppExtensions#14682]
## Description

I have a report with two data items (main record and integer).
Before I run the report, I fill a temporary table in the report with the selected records in the list page.

In the Integer data item, then I loop over all temporary records to print certain values.

When I run the report, I can see in with the debugger that the temporary table is being filled with the selected records, so far so good...
But when I select the preview button no the request page, no temporary record get displayed on the report.

When I select the print button, all selected  records are displayed.

It seems that the preview somehow loses the global var with temporary records

## Expected behavior

The preview should show the same temporary record as the print.

## Visualization

![2021-10-05_21-47-43](https://user-images.githubusercontent.com/7229592/136092901-5bb9003c-185a-4ada-a897-c586022026c6.gif)

## Attachments

Attached, you can find the report (al and rdlc) and page extension.
[MyCustLedgerEntries.Report.zip](https://github.com/microsoft/ALAppExtensions/files/7288843/MyCustLedgerEntries.Report.zip)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
