### ISSUE TITLE
passing option variable using globalvaraccess

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#1468]
Hi,
we have a Codeunit in C/AL with a publisher, that we subscribe in an AL-Extension.
In the publisher we set "GlobalVarAccess" to yes, as we would have to pass about 50 parameters if we don't.
So when we subscribe to that publisher in C/AL it works fine and we can use the Global variables.
In AL we can subscribe and also use most of the global variables. The one we cant not use is of "Source Type" of type option. So when i select the option in the subscriber I get the error **The type of the parameter 'SourceType' on the event subscriber 'OnAllocativeFunctionUserFunctionsFaR' does not match the expected type 'Option'**.
I get the same error whether I define the optionvalues or not.
Am I doing something wrong or is is a bug?
Below you got the subscriber Codeunit. 

[SubscriberCU.zip](https://github.com/Microsoft/ALAppExtensions/files/2941350/SubscriberCU.zip)

Kind Regards

**Comment by ikoletic** [comment]
This issue is a question. Please submit your questions on [business central community ](https://community.dynamics.com/business/f/758) or on [BC development yammer groups](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035).
