### ISSUE TITLE
Table 36 "Sales Header" change assignment in validate on CopyShipToCustomerAddressFieldsFromCust and SetShipToCustomerAddressFieldsFromShipToAddr

### ISSUE THREAD

**Issue by Mfelice1975** [microsoft/ALAppExtensions#14688]
On table 37 "Sales Header"  in function "SetShipToCustomerAddressFieldsFromShipToAddr" and "CopyShipToCustomerAddressFieldsFromCust" the assignment of some fields should be replaced by the VALIDATE:

SetShipToCustomerAddressFieldsFromShipToAddr

OLD:
        "Shipping Agent Code" := ShipToAddr."Shipping Agent Code";
        "Shipping Agent Service Code" := ShipToAddr."Shipping Agent Service Code";
        if ShipToAddr."Tax Area Code" <> '' then
            "Tax Area Code" := ShipToAddr."Tax Area Code";
        "Tax Liable" := ShipToAddr."Tax Liable";

NEW:
        VALIDATE("Shipping Agent Code", ShipToAddr."Shipping Agent Code");
        VALIDATE("Shipping Agent Service Code", ShipToAddr."Shipping Agent Service Code");
        if ShipToAddr."Tax Area Code" <> '' then
            VALIDATE("Tax Area Code", ShipToAddr."Tax Area Code");
        VALIDATE("Tax Liable", ShipToAddr."Tax Liable");

CopyShipToCustomerAddressFieldsFromCust

OLD:
            if not CustomerTempl.Get("Sell-to Customer Templ. Code") then begin
                "Tax Area Code" := Cust."Tax Area Code";
                "Tax Liable" := Cust."Tax Liable";
            end;
        SetCustomerLocationCode();
        "Shipping Agent Code" := Cust."Shipping Agent Code";
        "Shipping Agent Service Code" := Cust."Shipping Agent Service Code";

NEW: 
            if not CustomerTempl.Get("Sell-to Customer Templ. Code") then begin
                VALIDATE("Tax Area Code", Cust."Tax Area Code");
                VALIDATE("Tax Liable", Cust."Tax Liable");
            end;
        SetCustomerLocationCode();
        VALIDATE("Shipping Agent Code", Cust."Shipping Agent Code");
        VALIDATE("Shipping Agent Service Code", Cust."Shipping Agent Service Code");

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 40751.
