### ISSUE TITLE
Problem in Word Template merge() with more than 1 related tables and SplitDocument true

### ISSUE THREAD

**Issue by msomp** [microsoft/ALAppExtensions#14698]
Dear AL Team,

there seems to be a bug in the "Word Template Impl." codeunit when processing merge with more than one related tables
and split documents.

I think the problem is located in the procedure:

`local procedure WriteDataDict(RecordRef: RecordRef; var Data: Dictionary of [Text, Text])`

where the RecordRef (variable RecordRefRelated) is opened but not closed.
If just one related table is in use, everything works fine of course.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
