### ISSUE TITLE
[Event Request] Table 1701 - Deferral Header - OnBeforeCalculateSchedule

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#14696]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeCalculateSchedule` to be added to Table 1701 Deferral Header with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculateSchedule(var DeferralHeader: Record "Deferral Header")
    begin
    end;

```

which would be called as follows from `CalculateSchedule`:
```al
    procedure CalculateSchedule(): Boolean
    var
        DeferralDescription: Text[100];
    begin
        OnBeforeCalculateSchedule(Rec); //NEW
        if "Deferral Code" = '' then begin
            Message(SelectionMsg);
            exit(false);
        end;
        DeferralDescription := "Schedule Description";

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
