### ISSUE TITLE
[Event Request] Codeunit  6500 "Item Tracking Management" - OnItemTrkgIsManagedByWhse

### ISSUE THREAD

**Issue by ghost** [microsoft/ALAppExtensions#14692]
In codeunit 6500 - procedure ItemTrkgIsManagedByWhse we would like to have control over the exit value
is it possible to add an event in the beginning of the procedure with following signature and code

```
OnItemTrkgIsManagedByWhse(Type: Integer; Subtype: Integer; ID: Code[20]; ProdOrderLine: Integer; RefNo: Integer; LocationCode: Code[10]; ItemNo: Code[20]); var IsHandled: Boolean; var Result: Boolean);
if IsHandled then
  exit(Result);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
