### ISSUE TITLE
[Event Request] Table "Reminder Header" event OnBeforeInsertReminderTextLine

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#14694]
I would like to request that the event OnBeforeInsertReminderTextLine on the "Reminder Header" table passes the Reminder header parameter by reference.

     [IntegrationEvent(false, false)]
     local procedure OnBeforeInsertReminderTextLine(var ReminderLine: Record "Reminder Line"; var ReminderText: Record Reminder Text"; **var** ReminderHeader: Record "Reminder Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
