### ISSUE TITLE
Business Central Reverse employee ledger entry

### ISSUE THREAD

**Issue by Rolahalabi** [Microsoft/ALAppExtensions#147]
You'll receive the following error message when trying to reverse an employee ledger entry transaction.
![image](https://user-images.githubusercontent.com/44561155/47627899-9750ce00-db97-11e8-983c-2d9bca575b84.png)

to reproduce:
post a general journal with account type as "employee" 
navigate to the employee ledger entry then click Actions > Functions > Reverse transaction.

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!

**Comment by JesperSchulz** [comment]
This GitHub repository is dedicated to handling issues with published apps and extensibility requests for the latest release of Business Central. If you run into an issue, please open a support case. You can open a Support Request to CSS through PartnerSource portal or by contacting your Service Account Manager (SAM) in the local subsidiary, to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.
Another option would be to file this bug in Collaborate and include details on your Business Central build number and country. Quick link: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.
