### ISSUE TITLE
[Event Request] Codeunit 1720 - Deferral Utilities - OnCalculateUserDefinedOnBeforeDeferralLineInsert

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#14706]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnCalculateUserDefinedOnBeforeDeferralLineInsert`to be added to Codeunit 1720 Deferral Utilities with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnCalculateUserDefinedOnBeforeDeferralLineInsert(DeferralHeader: Record "Deferral Header"; var DeferralLine: record "Deferral Line")
    begin
    end;

```

which would be called as follows from `CalculateUserDefined`:
```al
            CheckPostingDate(DeferralHeader, DeferralLine);

            // For User-Defined, user must enter in deferral amounts
            OnCalculateUserDefinedOnBeforeDeferralLineInsert(DeferralHeader, DeferralLine); //NEW
            DeferralLine.Insert();
        end;

        OnAfterCalculateUserDefined(DeferralHeader, DeferralLine, DeferralTemplate);
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
