### ISSUE TITLE
Still missing Events in "Generate EFT" Codeunit

### ISSUE THREAD

**Issue by twbook** [microsoft/ALAppExtensions#14703]
I'm trying to run "Generate EFT".ProcessAndGenerateEFTFile but can not because of access on it.  There are no other events in the conduit to help.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
