### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - new event in CalculateSums

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#14715]
Hi,
I ask if you can add an event in function CalculateSums in order to let us work on the record before it is copied .
I mean something like:

    procedure CalculateSums()
    var
        xTrackingSpec: Record "Tracking Specification";
    begin
        xTrackingSpec.Copy(Rec);
        Rec.Reset();
        Rec.CalcSums("Quantity (Base)", "Qty. to Handle (Base)", "Qty. to Invoice (Base)");
        // NEW >>
        OnBeforeCopyRecToTotalTrackingSpecification(Rec);
        // NEW <<
        TotalTrackingSpecification := Rec;
        Rec.Copy(xTrackingSpec);

        UpdateUndefinedQtyArray();
    end;

this is because I need to execute additional calcsums for that record.

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
