### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - new event in RegisterChange

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#14718]
Hi, I nedd a new event in the function in object to let me act when a TempItemTrackLineReserv is inserted.

Example:

                    if ReservEngineMgt.RetrieveLostReservQty(LostReservQty) then begin 
                        TempItemTrackLineReserv := NewTrackingSpecification;
                        TempItemTrackLineReserv."Quantity (Base)" := LostReservQty * CurrentSignFactor;
                        // NEW OnBeforeTempItemTrackLineReservInsert(TempItemTrackLineReserv,CurrentSignFactor);
                        TempItemTrackLineReserv.Insert();
                    end;

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
