### ISSUE TITLE
Can't use multiple tabs on business central

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#14711]
Hi, 
I'm having troubles opening a new tab in business central. When I click with the scroll wheel, a new tab is created but just keeps loading indefinitely. This happens on chrome, firefox and edge.
When i just click it opens fine, and the "open in a new window" feature works well.

Is this normal ? What could be causing this issue ? 

Thanks

**Comment by AlexanderYakunin** [comment]
This is not related to extensibility of application. Please report this as a bug if required.
