### ISSUE TITLE
extensibility bugs / event requests? - codeunit 80 "Sales Post" & codeunit 90 "Purch.-Post" - InsertICGenJnlLine uses default Gen./VAT Bus. Posting Groups from Vendor/Customer, not source Sales/Purchase Line

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#14729]
We already had to extend IC posting code to propagate VAT Bus./Prod. Posting Groups from source Sales/Purchase Line, to the IC Outbox, to the IC Inbox, to the resulting IC Gen. Journal.

That's because the standard code only passes a VAT Amount, and wrongly assumes that the destination journal should use either no VAT Posting Groups (if the destination GJ Batch has Copy VAT Setup off) or the defaults from the G/L Account (if Copy VAT Setup is on). These may be totally wrong, if the VAT Bus./Prod. Posting Groups were changed on the source invoice.

We need the VAT Posting Groups to be preserved as-is, all the way from source document to destination document/journal.

***

After adding fields to the IC Outbox/Inbox tables and events to (with serious acrobatics) handle propagating/retrieving the correct/original Groups to the destination journal, we are now facing this problem:

![image](https://user-images.githubusercontent.com/63455896/136773770-fe0ee5f9-183f-46cb-8cae-62ead5d3e98d.png)

That is, although the source Sales or Purchase Line **has** its own Gen./VAT Bus. Posting Group, you instead go out and get the defaults off the Customer or Vendor. That seems wrong! The Sales/Purchase document might have had a different-than-default Group selected, or even individual lines might have.

This means we cannot extend the IC functionality to fix this and propagate the *exact* Gen. and VAT Bus. Posting Groups to the IC journal lines...

...at least not without doing yet more horrible acrobatics, and possibly copying/pasting your other code (which validates Amounts, which depend on Posting Groups), etc. - none of which we should have to do, as this seems like a simple oversight.

***

Is it not objectively correct to just take the two Bus. Posting Group fields off the source Sales/Purchase Line, whatever they may be, instead of going and getting the defaults off the Customer/Vendor, which may not be applicable?

**edit:** I notice now that `Sales-Post` uses `Vend` and `Purch.-Post` uses `Cust`. So I guess this is at least somewhat intended. However, we could really use a way to opt out of this behaviour. Please see my next post for that!

Thanks in advance for your support here!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
