### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - new event in SetQtyToHandleAndInvoice

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#14721]
Hi, I need a new event in the function in object placed before the loop, when variables are initialized This is because I need to do a similar calculation with custom fields..

Example:

        if IsCorrection then
            exit;
        
        // NEW >>
        OnBeforeSetQtyToHandleAndInvoice(TrackingSpecification);
        // NEW <<
        TotalQtyToHandle := TrackingSpecification."Qty. to Handle (Base)" * CurrentSignFactor;
        TotalQtyToInvoice := TrackingSpecification."Qty. to Invoice (Base)" * CurrentSignFactor;

        ReservEntry1.TransferFields(TrackingSpecification);
        ReservEntry1.SetPointerFilter();
        ReservEntry1.SetTrackingFilterFromReservEntry(ReservEntry1);
        if TrackingSpecification.TrackingExists() then begin

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
