### ISSUE TITLE
Event Request Codeunit 427 - IC Inbox Outbox Mgt. OnCreateSalesLinesOnAfterValidateNo

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#14723]
Hello,
Requesting a new event publisher on codeunit 427 - IC Inbox Outbox Mgt.

I would like to request the publisher OnCreateSalesLinesOnAfterValidateNo in Function CreateSalesLines

    procedure CreateSalesLines(SalesHeader: Record "Sales Header"; ICInboxSalesLine: Record "IC Inbox Sales Line")
    var
        SalesLine: Record "Sales Line";
        ICDocDim: Record "IC Document Dimension";
        Currency: Record Currency;
        Precision: Decimal;
        DimensionSetIDArr: array[10] of Integer;
    begin
        with ICInboxSalesLine do begin
            SalesLine.Init();
            SalesLine.TransferFields(ICInboxSalesLine);
            SalesLine."Document Type" := SalesHeader."Document Type";
            SalesLine."Document No." := SalesHeader."No.";
            SalesLine."Line No." := "Line No.";

            OnCreateSalesLinesOnBeforefterAssignTypeAndNo(SalesLine, ICInboxSalesLine);
            case "IC Partner Ref. Type" of
                "IC Partner Ref. Type"::"Common Item No.":
                    begin
                        SalesLine.Type := SalesLine.Type::Item;
                        SalesLine."No." := GetItemFromCommonItem("IC Partner Reference");
                        if SalesLine."No." <> '' then
                            SalesLine.Validate("No.", SalesLine."No.")
                        else
                            SalesLine."No." := "IC Partner Reference";
                    end;
                "IC Partner Ref. Type"::"Cross reference":
                    begin
                        SalesLine.Validate(Type, SalesLine.Type::Item);
                        SalesLine.Validate("Item Reference No.", "IC Item Reference No.");
                    end;
                "IC Partner Ref. Type"::Item:
                    begin
                        SalesLine.Validate(Type, SalesLine.Type::Item);
                        SalesLine."No." :=
                            GetItemFromItemRef(
                                "IC Partner Reference", "Item Reference Type"::Customer, SalesHeader."Sell-to Customer No.");
                        if SalesLine."No." <> '' then
                            SalesLine.Validate("No.", SalesLine."No.")
                        else
                            SalesLine."No." := "IC Partner Reference";
                    end;
                "IC Partner Ref. Type"::"Vendor Item No.":
                    begin
                        SalesLine.Validate(Type, SalesLine.Type::Item);
                        SalesLine."No." :=
                            GetItemFromItemRef(
                                "IC Item Reference No.", "Item Reference Type"::Customer, SalesHeader."Sell-to Customer No.");
                        if SalesLine."No." <> '' then
                            SalesLine.Validate("No.", SalesLine."No.")
                        else
                            SalesLine."No." := CopyStr("IC Item Reference No.", 1, MaxStrLen(SalesLine."No."));
                    end;
                "IC Partner Ref. Type"::"G/L Account":
                    begin
                        SalesLine.Validate(Type, SalesLine.Type::"G/L Account");
                        SalesLine.Validate("No.", TranslateICGLAccount("IC Partner Reference"));
                    end;
                "IC Partner Ref. Type"::"Charge (Item)":
                    begin
                        SalesLine.Type := SalesLine.Type::"Charge (Item)";
                        SalesLine.Validate("No.", "IC Partner Reference");
                    end;
                else
                    OnCreateSalesLinesOnICPartnerRefTypeCaseElse(SalesLine, SalesHeader, ICInboxSalesLine);
            end;
            OnCreateSalesLinesOnAfterValidateNo(SalesLine, SalesHeader, ICInboxSalesLine);    // NEW
            SalesLine."Currency Code" := SalesHeader."Currency Code";
            SalesLine.Description := Description;

    // NEW +
    [IntegrationEvent(false, false)]
    local procedure OnCreateSalesLinesOnAfterValidateNo(var SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header"; ICInboxSalesLine: Record "IC Inbox Sales Line")
    begin
    end;
    // NEW -

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
