### ISSUE TITLE
[Event Request] Codeunit 1535 "Approvals Mgmt." - OnSendApprovalRequestFromRecordOnAfterApprovalEntrySetFilters 

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#14732]
Hello,

We would need an event OnSendApprovalRequestFromRecordOnAfterApprovalEntrySetFilters in the function SendApprovalRequestFromRecord.

    procedure SendApprovalRequestFromRecord(RecRef: RecordRef; WorkflowStepInstance: Record "Workflow Step Instance")
    var
        ApprovalEntry: Record "Approval Entry";
        ApprovalEntry2: Record "Approval Entry";
        IsHandled: Boolean;
    begin
        ApprovalEntry.SetCurrentKey("Table ID", "Record ID to Approve", Status, "Workflow Step Instance ID", "Sequence No.");
        ApprovalEntry.SetRange("Table ID", RecRef.Number);
        ApprovalEntry.SetRange("Record ID to Approve", RecRef.RecordId);
        ApprovalEntry.SetRange(Status, ApprovalEntry.Status::Created);
        ApprovalEntry.SetRange("Workflow Step Instance ID", WorkflowStepInstance.ID);
        // begin new event
        IsHandled := false;
        OnSendApprovalRequestFromRecordOnAfterApprovalEntrySetFilters(RecRef, ApprovalEntry, IsHandled);
        if IsHandled then
            exit;
        // end new event
        if ApprovalEntry.FindFirst then begin
            ApprovalEntry2.CopyFilters(ApprovalEntry);
            ApprovalEntry2.SetRange("Sequence No.", ApprovalEntry."Sequence No.");
            if ApprovalEntry2.FindSet(true) then
                repeat
                    ApprovalEntry2.Validate(Status, ApprovalEntry2.Status::Open);
                    ApprovalEntry2.Modify(true);
                    CreateApprovalEntryNotification(ApprovalEntry2, WorkflowStepInstance);
                until ApprovalEntry2.Next() = 0;
            if FindApprovedApprovalEntryForWorkflowUserGroup(ApprovalEntry, WorkflowStepInstance) then
                OnApproveApprovalRequest(ApprovalEntry);
            exit;
        end;

        ApprovalEntry.SetRange(Status, ApprovalEntry.Status::Approved);
        if ApprovalEntry.FindLast then
            OnApproveApprovalRequest(ApprovalEntry)
        else
            Error(NoApprovalRequestsFoundErr);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnSendApprovalRequestFromRecordOnAfterApprovalEntrySetFilters(RecRef: RecordRef; var ApprovalEntry: Record "Approval Entry"; var IsHandled: Boolean)
    begin
    end;

We need this event because we set extra filters on Approval Entry record and, in some situations, we also exit the function.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
