### ISSUE TITLE
[Event request] Codeunit 12151 "VAT Pmt. Comm. Data Lookup" - OnBeforeVATEntryVATPurchaseSetFilter

### ISSUE THREAD

**Issue by stebruni** [microsoft/ALAppExtensions#14737]
Hi AL-Team,
can you please add new events in the method GetVATPurchases

begin
   VATEntry.SetRange(Type, VATEntry.Type::Purchase);

  //New Event
  OnBeforeVATEntryVATPurchaseSetFilter(VatEntry);
  //New Event

    VATEntry.CalcSums(Amount);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
