### ISSUE TITLE
[Event Change] Codeunit 80 OnBeforeDivideAmount and OnAfterDivideAmount

### ISSUE THREAD

**Issue by BartPermentier** [microsoft/ALAppExtensions#14731]
Could you change both Publishers so that the Parameter SalesHeader is a var please?
![image](https://user-images.githubusercontent.com/24684493/136799519-86945fa3-f19c-4e49-9ae3-32642437fd53.png)
![image](https://user-images.githubusercontent.com/24684493/136799651-ce7f6547-4610-4a19-8c9a-157dce6d2ade.png)

Thanks a lot!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
