### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - modify event OnRegisterItemTrackingLinesOnAfterFind

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#14738]
Hi,
for event "OnRegisterItemTrackingLinesOnAfterFind" I need parameter "IsCorrection" to be added. That boolean is used immediately after the event and causaes a different behaviour.

  OnRegisterItemTrackingLinesOnAfterFind(Rec, TempTrackingSpecification); // Add IsCorrection 
  if IsCorrection then begin
    Rec."Quantity (Base)" += TempTrackingSpecification."Quantity (Base)";
    Rec."Qty. to Handle (Base)" += TempTrackingSpecification."Qty. to Handle (Base)";
    Rec."Qty. to Invoice (Base)" += TempTrackingSpecification."Qty. to Invoice (Base)";
  end else
    Rec.Validate("Quantity (Base)", "Quantity (Base)" + TempTrackingSpecification."Quantity (Base)");

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
