### ISSUE TITLE
ContextSensitiveHelpPage on pageextension is broken in BC19

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/ALAppExtensions#14749]
BC 19 (2021 wave2) contexthelp on default MS list or card that is modified through pageextension does not work anymore.

in BC18 and lower it will start the ContextSensitiveHelpPage from the pageextension with our own help URL. 

 in BC19 same code and same settings it starts the default MS url: https://docs.microsoft.com/nl-NL/dynamics365/business-central/L_77

 ContextSensitiveHelpPage property is set in the pageextension,
App with pageextension is published.

app.json has the contextSensitiveHelpUrl filled in: "contextSensitiveHelpUrl":  "https://help.dummy.nl/bc19/html/",

and the navsettings.json from the webclient (iss) has the BaseHelpURL filled in.

    "ApplicationIdSettings":  {
                                  "BaseHelpUrl":  "https://help.dummy.nl/bc19/html/"
                              }

and the HelpServer and HelpServerPort empty. (old help way)

the settings are the same for BC18 and BC19.

On our own pages and lists, the contextsensetivehelp is working, its only the pageextensions help that fails..

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
