### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - new event in CollectPostedOutputEntries

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#14741]
Hi, I need a new envent in procedure CollectPostedOutputEntries placed after all, like OnAfterCollectPostedOutputEntries

OnAfterCollectPostedOutputEntries(ItemLedgerEntry, TempTrackingSpecification);

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
