### ISSUE TITLE
[Event Request] Table 210 Job Journal Line - OnAfterShowDimensions

### ISSUE THREAD

**Issue by ddagklossner** [microsoft/ALAppExtensions#14752]
Please add a new event OnAfterShowDimensions in table 210 "Job Journal Line".

```
   procedure ShowDimensions()
    begin
        "Dimension Set ID" :=
          DimMgt.EditDimensionSet("Dimension Set ID", StrSubstNo('%1 %2 %3', "Journal Template Name", "Journal Batch Name", "Line No."));
        DimMgt.UpdateGlobalDimFromDimSetID("Dimension Set ID", "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");
       OnAfterShowDimensions(Rec,xRec)
    end;
```

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
