### ISSUE TITLE
[Event Request] Report 202 Sales Document - Test - OnBeforeCheckSalesLine

### ISSUE THREAD

**Issue by MOomenAL** [microsoft/ALAppExtensions#14754]
Hello team,

We request that you add an event publisher in the procedure _CheckSalesLine()_ from report _202 Sales Document - Test_ according to the suggestion in the screenshots below. This to facilitate checks on the Sales Line which do contain the standard _Type_, but have extra requirements on the line itself. Thank you in advance.
![image](https://user-images.githubusercontent.com/85683700/137141898-2c0772a8-34dd-48db-8aa3-b54bcf858d5e.png)

![image](https://user-images.githubusercontent.com/85683700/137142114-c11f1158-5365-4a1d-a499-f8ad908f2ebe.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
