### ISSUE TITLE
[Event Request] codeunit 99000830 "Create Reserv. Entry" - OnBeforeUpdateItemTrackingAfterPosting

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#14768]
Please add an event OnBeforeUpdateItemTrackingAfterPosting to procedure UpdateItemTrackingAfterPosting in codeunit 99000830 "Create Reserv. Entry"

```
    procedure UpdateItemTrackingAfterPosting(var ReservEntry: Record "Reservation Entry")
    var
        CurrSourceRefNo: Integer;
        ReachedEndOfResvEntries: Boolean;
    begin
        OnBeforeUpdateItemTrackingAfterPosting(ReservEntry); // <-- NEW EVENT

        if not ReservEntry.FindSet(true) then
            exit;
        ...

    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateItemTrackingAfterPosting(var ReservEntry: Record "Reservation Entry")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
