### ISSUE TITLE
[Event parameter request] codeunit 5431 "Calc. Item Plan - Plan Wksh." - OnCodeOnAfterSetReqLineFilters

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#14766]
Please add CurrTemplateName and CurrWorksheetName to event OnCodeOnAfterSetReqLineFilters in codeunit 5431 "Calc. Item Plan - Plan Wksh."

Original code:

```
OnCodeOnAfterSetReqLineFilters(ReqLineExtern);

[IntegrationEvent(false, false)]
local procedure OnCodeOnAfterSetReqLineFilters(var ReqLineExtern: Record "Requisition Line")
begin
end;
```

Modified code:

```
OnCodeOnAfterSetReqLineFilters(ReqLineExtern, CurrTemplateName, CurrWorksheetName);

[IntegrationEvent(false, false)]
local procedure OnCodeOnAfterSetReqLineFilters(var ReqLineExtern: Record "Requisition Line"; CurrTemplateName: Code[10]; CurrWorksheetName: Code[10])
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
