### ISSUE TITLE
Please convert field Type to enum in table 156 Resource.

### ISSUE THREAD

**Issue by arnasif** [microsoft/ALAppExtensions#1477]
Hi Team,
We need to add more options for field Type in table Resource.
Can you convert it to enum so we cant extend it and add more options.
Best regards,
Arna Sif

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
