### ISSUE TITLE
[Event Request] table 5407 "Prod. Order Component" - OnBeforeCalcBaseQty

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#14777]
Please add a new event OnBeforeCalcBaseQty to procedure CalcBaseQty in table "Prod. Order Component"

    local procedure CalcBaseQty(Qty: Decimal; FromFieldName: Text; ToFieldName: Text) BaseQty: Decimal
    var
        IsHandled: Boolean; // NEW LOCAL VARIABLE
    begin
        // NEW EVENT -->
        OnBeforeCalcBaseQty(Rec, CurrFieldNo, Qty, BaseQty, IsHandled);
        if IsHandled then
            exit;
        // NEW EVENT <--
        
        exit(UOMMgt.CalcBaseQty(
            "Item No.", "Variant Code", "Unit of Measure Code", Qty, "Qty. per Unit of Measure", "Qty. Rounding Precision (Base)", FieldCaption("Qty. Rounding Precision"), FromFieldName, ToFieldName));
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcBaseQty(ProdOrderComponent: Record "Prod. Order Component"; CurrFieldNo: integer; Qty: Decimal; var BaseQty: Decimal; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
