### ISSUE TITLE
[Event Request] codeunit 5760 "Whse.-Post Receipt" - OnAfterPostSourceDocument

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#14789]
Please add a new event OnAfterPostSourceDocument to procedure PostSourceDocument in codeunit 5760 "Whse.-Post Receipt"

```
    local procedure PostSourceDocument(WhseRcptLine: Record "Warehouse Receipt Line")
    var
        ...
    begin
        WhseSetup.Get();
        with WhseRcptLine do begin
            ...
        end;

        OnAfterPostSourceDocument(WhseRcptLine); // <-- NEW EVENT
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterPostSourceDocument(var WarehouseReceiptLine: Record "Warehouse Receipt Line")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
