### ISSUE TITLE
The type or Method 'file' can not be used for 'Extension' Development

### ISSUE THREAD

**Issue by SangitPPanchal** [Microsoft/ALAppExtensions#1479]
Here, I'm having a below error for record variable (File).

![the type or method file can not be used for extension development](https://user-images.githubusercontent.com/35402654/54028246-72fea100-41ca-11e9-8eb6-69fc2ad34780.png)

- In this case I want to get all the files name with full path from folder credential.
  **example** :  this is credential folder '**E:\Credentials\**' and i want to get all the files name with full 
  path like this '**E:\Credentials\techcronus.txt**', '**E:\Credentials\sangit.txt**'.

So, is there any other way to get all the files path? if any then please let me know.
Thanks !

- here is the example of code
           `action("Get Files Name")
            {
                Caption = 'Get Files Name';
                image = GetLines;
                trigger OnAction();
                var
                    fileRec: Record File;
                begin
                    fileRec.Reset;
                    fileRec.SetRange(Path, 'E:\Credentials\');
                    if fileRec.FindSet then begin
                        repeat
                            Message(fileRec.Name);
                        until fileRec.Next = 0;
                    end;
                end;
            }`

**Comment by JesperSchulz** [comment]
In extensions, you are not allowed to use files or access the file system. There is hence no way to achieve what you are requesting.
