### ISSUE TITLE
[Event request] Codeunit 90 OnAfterPostGLAndVendor

### ISSUE THREAD

**Issue by LdrAms** [Microsoft/ALAppExtensions#148]
Hi,
We need an OnAfterPostGLAndVendor event at function PostGLAndVendor on codeunit 90. The same requested event already exist at codeunit 80 PostGLAndCustomer function.
We need to post some additional transactions based on the original one. 

```
...
// Balancing account
  IF "Bal. Account No." <> '' THEN BEGIN
    IF GUIALLOWED THEN
      Window.UPDATE(5,1);
    PostBalancingEntry(
      PurchHeader,TotalPurchLine,TotalPurchLineLCY,GenJnlLineDocType,GenJnlLineDocNo,GenJnlLineExtDocNo,SrcCode);
  END;
END;

// New event request
OnAfterPostGLAndVendor(TempInvoicePostBuffer,GenJnlLineDocType,GenJnlLineDocNo);
//

```
Thank you.
Kind regards.
-- Alejandro --

**Comment by LdrAms** [comment]
Sorry,

Event already exists in Busines Central. 

Thanks.

**Comment by AlexanderYakunin** [comment]
Please do not use NAV 2018 code for reference when ordering events, use D365 Business Central builds.
