### ISSUE TITLE
[Event Request] Table 904 - new event on procedure RestoreItemTracking

### ISSUE THREAD

**Issue by calliopedavidroldan** [microsoft/ALAppExtensions#14801]
Hi,

We need a new event on table 904 procedure RestoreItemTracking :

```
... 
if TrackingSpecification.Find('-') then
  repeat
    > new event
    OnBeforeTrackingSpecificationLoopInRestoreItemTracking(TrackingSpecification);
    < new event
    CreateReservEntry.SetDates(TrackingSpecification."Warranty Date", TrackingSpecification."Expiration Date");
...
    
[IntegrationEvent(false, false)]
local procedure OnBeforeTrackingSpecificationLoopInRestoreItemTracking(var TrackingSpecification: Record "Tracking Specification");
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
