### ISSUE TITLE
The name 'AssignQuote' does not exist in the current context AL(AL0118)

### ISSUE THREAD

**Issue by SangitPPanchal** [microsoft/ALAppExtensions#1480]
Here I'm having issue while i try to call the function **AssignQuote** from Table **Opportunity** .

![Issue AL(AL0118)](https://user-images.githubusercontent.com/35402654/54066957-05e91b00-425f-11e9-8423-b65db31e8f26.PNG)

So, after that i opened NAV2018 and tried to find the function **AssignQuote**, I found this function in Opportunity table as below image.

![NAV 2018](https://user-images.githubusercontent.com/35402654/54066974-392baa00-425f-11e9-9400-10fabcc98e25.PNG)

but, after that i tried to find **AssignQuote** function in the D365 On-premise, but i was not able to find, So where can i find this function?

Thanks!

**Comment by StanPesotskiy** [comment]
It had been renamed to CreateQuote().
