### ISSUE TITLE
[Scope] codeunit 8 AccSchedManagement - DrillDownOnGLAccount, DrillDownOnCFAccount

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#14810]
Please could you change the scope to `public` for these methods?
- `DrillDownOnGLAccount`
- `DrillDownOnCFAccount`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
