### ISSUE TITLE
[Bug] Enum "Item Tracking Run Mode"

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#14817]
hey guys,

enum 6510 "Item Tracking Run Mode"
{
    Extensible = true;
    AssignmentCompatibility = true;

    value(0; "") { }
    value(1; "Reclass") { }
    value(2; "Combined Ship/Rcpt") { }
    value(3; "Drop Shipment") { }
    value(4; "Transfer") { }
}

The value 0 of the enum is not accessable.

![2021-10-15_14h14_49](https://user-images.githubusercontent.com/34685182/137485150-118e3b00-c5a9-40b8-bfaa-738c2927f62e.png)

**Comment by dnpb** [comment]
In the meantime you can do `SomeEnumVarOrField := Enum::"Item Tracking Run Mode".FromInteger(0)`

**Comment by AlexanderYakunin** [comment]
Originally, this Option variable had been defined as
         FormRunMode: Option ,Reclass,"Combined Ship/Rcpt","Drop Shipment",Transfer;

We never use value "" in the code, so this variable sued with values Reclass,"Combined Ship/Rcpt","Drop Shipment",Transfer only.

Please explain why do you need to set it to value 0?
