### ISSUE TITLE
Event requests (2) - InitServiceRegister function in codeunit 5912

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#1482]
To port a NAV add-on to BC, we need to to run code at the start of the InitServiceRegister function in codeunit 5912 and at the end of that function.  So, we need 2 new integration events here:

OnBeforeInitServiceRegister
OnAfterInitServiceRegister

**Comment by AlexanderYakunin** [comment]
Can you please specify parameters for requested events?

**Comment by RHansenEpimatic** [comment]
Sorry Alexander.  I actually don't think this is needed...I'm going to close it for now and will reopen it once i review if i do think i need it.  Sorry again.  :)
