### ISSUE TITLE
Event Requests - Codeunit 5632

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#1483]
Unlike other journal post line codeunits, codeunit 5632 does not have OnBeforeFAJnlPostLine and OnAfterFAJnlPostLine events.  We need this to migrate a NAV add-on to BC.

**Comment by RHansenEpimatic** [comment]
This was marked as "ships-in-future-update", but only the OnAfterFAJnlPostLine event was added...there is still no OnBeforeFAJnlPostLine.

Can you please reopen this?

**Comment by AlexanderYakunin** [comment]
This is not correct, you again look into old builds. Please wait until new build willbe available for you

![image](https://user-images.githubusercontent.com/31849120/55543364-95a0ae80-56d1-11e9-9633-68e2209f9341.png)

**Comment by RHansenEpimatic** [comment]
Thanks Jesper.  What's the best way for me to find out when a new build is posted so i can check it out?
