### ISSUE TITLE
[Event Request] Codeunit 6620 add parameter NextLineNo on event OnCopySalesDocLineOnBeforeCopyThisLine

### ISSUE THREAD

**Issue by calliopedavidroldan** [microsoft/ALAppExtensions#14835]
Hi,

We need to add the parameter NextLineNo on event OnCopySalesDocLineOnBeforeCopyThisLine call on procedure CopySalesDocLine :

```
    [IntegrationEvent(false, false)]
    local procedure OnCopySalesDocLineOnBeforeCopyThisLine(ToSalesHeader: Record "Sales Header"; var ToSalesLine: Record "Sales Line"; FromSalesLine: Record "Sales Line"; FromSalesDocType: Enum "Sales Document Type From"; var RecalculateLines: Boolean; var CopyThisLine: Boolean; var LinesNotCopied: Integer; var Result: Boolean; var IsHandled: Boolean ; var NextLineNo: Integer)
    begin
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
