### ISSUE TITLE
Transfer order locations cannot be empty

### ISSUE THREAD

**Issue by JohnFrostDP** [microsoft/ALAppExtensions#14847]
While coding I came across a odd feature. While playing with the Transfer order I noticed a soft lock scenario. If you fill in the transfer-from, transfer-to code and in-Transit code you can add an item. After you added the item as a subline and you delete the locations from and to you can't add them again because of this code in the Qty. to Receive Validation. If you fill the transfer-from, it checks the Transfer-to, which is empty. The other way around it checks the Transfer-from which ofcourse is also empty. 

The only way to work around this is by deleting the lines and start over. Please make it so that refilling the fields is possible, or prevent location deletion in the first place. 

Point in the code where it always validates Qty. to Recieve:
![image](https://user-images.githubusercontent.com/92578153/137473600-f23a90ce-7a97-4545-99ab-585e5a231208.png)

Code when you try to fill Transfer-from:
![image](https://user-images.githubusercontent.com/92578153/137473562-ac9b9aa7-5a2a-476f-9533-a47d4c079d31.png)

![image](https://user-images.githubusercontent.com/92578153/137473578-8317a0e6-a442-4256-a628-6bcb6dc213aa.png)

Code when you try to fill Transfer-to:
![image](https://user-images.githubusercontent.com/92578153/137473676-849f9018-dea2-4095-a9b3-364f0920c22a.png)

![image](https://user-images.githubusercontent.com/92578153/137473698-b07e5430-cc6e-4ab7-ace7-de4a9873420e.png)

**Comment by AlexanderYakunin** [comment]
Sorry, this is not related to extensibility and should be reported via technical support. We need repro steps and more details to fix this kind of issues.
