### ISSUE TITLE
[EventRequest] Codeunit 6620 "Copy Document Mgt.". Make it Job Que executeable

### ISSUE THREAD

**Issue by FavMY** [microsoft/ALAppExtensions#14854]
Hey all,

we need a possibility to skip the windows-dialog when copying a document, so we can use sme function in the job que.

For example the function "CopySalesShptLinesToDoc" has 5 places of windows.open ,windows.update or windows.close.

A possible solution can be events like OnBeforeOpenWindow or OnBeforeCloseWindow or something like that, where we can handle that dialog. There are also Windows.Update functions which should be avoided also. Just one example from first lines of "CopySalesShptLinesToDoc":

    begin
        MissingExCostRevLink := false;
        InitCurrency(ToSalesHeader."Currency Code");
        OnBeforeOpenWindow(IsHandled);
        if not IsHandled then
           OpenWindow;

        OnBeforeCopySalesShptLinesToDoc(TempDocSalesLine, ToSalesHeader, FromSalesShptLine);

        with FromSalesShptLine do
            if FindSet then
                .
                .
                .
        OnBeforeCloseWindow(IsHandled);
        if not IsHandled then
           Window.Close;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
