### ISSUE TITLE
[Event Request] Table 18 Customer Check Blocked

### ISSUE THREAD

**Issue by AJasp** [Microsoft/ALAppExtensions#1485]
To manage additional checks for blocked customers we need the following two events in table 18 (Customer):

Function: CheckBlockedCustOnDocs - new event OnBeforeCheckBlockedCustOnDocs:
![image](https://user-images.githubusercontent.com/47414309/54118091-8a1fd780-43f2-11e9-8fc0-9cb574ce85ba.png)

Function: CheckBlockedCustOnJnls - new event OnBeforeCheckBlockedCustOnJnls:
![image](https://user-images.githubusercontent.com/47414309/54118156-af144a80-43f2-11e9-8169-14215664b98b.png)

Thanks!

**Comment by AlexanderYakunin** [comment]
Well, this is not to manage additional checks but to skip our checks?

**Comment by AJasp** [comment]
The "IsHandled" parameter allows us to do both. Currently we use an additional field on the customer which can prevent the creation of an order.
