### ISSUE TITLE
'Codeunit "SignedXml Impl."' does not contain a definition for 'InitializeDataObject'

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#14909]
Trying to contribute to the System app by cloning the code, results in below errors when trying to packaging the System app. (@JesperSchulz )

![image](https://user-images.githubusercontent.com/25268332/138118609-cbd2eeeb-6578-46d1-94ae-f96ab1169811.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by IhorHandziuk** [comment]
@fvet , PR #15028 addressed the issue, thanks for reporting 😊
