### ISSUE TITLE
[Event Request] Table 37 - Sales Line - InitQtyToShip2OnBeforeCalcInvDiscToInvoice

### ISSUE THREAD

**Issue by cosmo-skol** [Microsoft/ALAppExtensions#1491]
Hello AL-Team,
I need the following publisher, to reset field values before invoice discount calculation, depending on custom setup:

Function [External] InitQtyToShip2

```
"Qty. to Ship" := "Outstanding Quantity";
"Qty. to Ship (Base)" := "Outstanding Qty. (Base)";

ATOLink.UpdateQtyToAsmFromSalesLine(Rec);

CheckServItemCreation;

"Qty. to Invoice" := MaxQtyToInvoice;
"Qty. to Invoice (Base)" := MaxQtyToInvoiceBase;
"VAT Difference" := 0;

// >> NEW
InitQtyToShip2OnBeforeCalcInvDiscToInvoice(Rec,xRec);
// << NEW

CalcInvDiscToInvoice;

CalcPrepaymentToDeduct;
```

Publisher definition currently used by us
IncludeSender: false
GlobaVarAccess: false
LOCAL [IntegrationEvent] InitQtyToShip2OnBeforeCalcInvDiscToInvoice(VAR Rec : Record "Sales Line";xRec : Record "Sales Line")

**Comment by NKarolak** [comment]
Note: created as
`OnInitQtyToShip2OnBeforeCalcInvDiscToInvoice(Rec,xRec);`
