### ISSUE TITLE
[Event Request] Codeunit 7304 - Whse. Jnl.-Register Batch - OnCheckWhseJnlLine

### ISSUE THREAD

**Issue by SchoKa** [Microsoft/ALAppExtensions#1494]
Hello AL-Team,
 we need an additional parameter in the following Publisher in function "Code":

…
    ItemTrackingMgt.CheckWhseItemTrkgSetup("Item No.",WhseSNRequired,WhseLNRequired,FALSE);
    IF WhseSNRequired OR WhseLNRequired THEN BEGIN
      IF WhseSNRequired THEN
        TESTFIELD("Qty. per Unit of Measure",1);
      IF WhseJnlTemplate.Type <> WhseJnlTemplate.Type::"Physical Inventory" THEN
        CreateTrackingSpecification(WhseJnlLine,TempHandlingSpecification)
      ELSE BEGIN
        // >> Update
        // OnCheckWhseJnlLine(WhseJnlLine);
        OnCheckWhseJnlLine(WhseJnlLine,WhseItemTrkgLine);
        // << Update

        IF WhseSNRequired THEN
          TESTFIELD("Serial No.");
        IF WhseLNRequired THEN
          TESTFIELD("Lot No.");
      END;
    END;
    ItemTrackingMgt.CollectItemTrkgInfWhseJnlLine(WhseJnlLine);
    OnAfterCollectTrackingInformation(WhseJnlLine);
...

Publisher definition currently used by us
 IncludeSender: false
 GlobaVarAccess: false
 LOCAL [IntegrationEvent] OnCheckWhseJnlLine(VAR WhseJnlLine : Record "Warehouse Journal Line";VAR WhseItemTrackingLine : Record "Whse. Item Tracking Line")

**Comment by AlexanderYakunin** [comment]
WhseItemTrkgLine is not available in this context

**Comment by SchoKa** [comment]
Please close this request. Thank you!
