### ISSUE TITLE
Add Permission in Permission List in Codeunit "Sales-Post" 

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#14949]
Please add "**`TableData = "Service Item" = rimd`**"
in Sales-Post to make it possible to work with indirect permissions.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
