### ISSUE TITLE
[Event request] - Table 81 OnAfterCreateDim

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#1495]
To replicate functionality for a NAV add-on in BC, we require the ability to add logic to the end of the CreateDim function in table 81.  Please add an event to the end of that function for OnAfterCreateDim so we can subscribe to it to add our logic.

**Comment by AlexanderYakunin** [comment]
We already have event inside of procedure

[External] GetRecDefaultDimID(RecVariant : Variant;CurrFieldNo : Integer;TableID : ARRAY [10] OF Integer;No : ARRAY [10] OF Code[20];SourceCode : Code[20];VAR GlobalDim1Code : Code[20];VAR GlobalDim2Code : Code[20];InheritFromDimSetID : Integer;Inheri
OnGetRecDefaultDimID(RecVariant,CurrFieldNo,TableID,No,SourceCode,InheritFromDimSetID,InheritFromTableNo);
EXIT(GetDefaultDimID(TableID,No,SourceCode,GlobalDim1Code,GlobalDim2Code,InheritFromDimSetID,InheritFromTableNo));

**Comment by RHansenEpimatic** [comment]
Thanks Alexander.  Where is that event?  I don't see it in my build, but i'm using one from early February.

**Comment by AlexanderYakunin** [comment]
In COD408

**Comment by RHansenEpimatic** [comment]
Sorry - i was in the wrong database.  I see it now - thanks!  I'll close this issue for now and will open a new one if it doesn't work for some reason.

**Comment by RHansenEpimatic** [comment]
Sorry Alexander - this doesn't quite give me what i need.  The GetDecDefaultDimID ends with the line:

EXIT(GetDefaultDimID(...));

I need the ability to manipulate the result that is returned.  In the GetDefaultDimID function there is an event at the start for OnBeforeGetDefaultDimID, but there is no integration event later in the function.  I need an event right before "TempDimBuf.RESET" near the end of the function that passes in the TempDimBuf variable and other function parameters so i can adjust the data to return the DimensionSetID to use.

**Comment by RHansenEpimatic** [comment]
This is marked as ships-in-future-update but i just downloaded the build from March 19th and i don't see the change.  Can you reopen this?
