### ISSUE TITLE
Workflow Handling Codeunits UpperCase Problem

### ISSUE THREAD

**Issue by muratkarabek** [microsoft/ALAppExtensions#14950]
There are lots of procedures returning workflow function names in Codeunit 1520 "Workflow Event Handling" and Codeunit 1521 "Workflow Response Handling" such as samples below:

```
procedure RunWorkflowOnAfterInsertIncomingDocumentCode(): Code[128]
begin
    exit(UpperCase('RunWorkflowOnAfterInsertIncomingDocument'));
end;

procedure RunWorkflowOnAfterReleaseIncomingDocCode(): Code[128]
begin
    exit(UpperCase('RunWorkflowOnAfterReleaseIncomingDoc'));
end;

```

Usage of UpperCase function in these procedures occurs the problem in Turkish. Uppercase of "i" character in Turkish is "İ" but in English it is "I". If i use Business Central in English and open the Workflows page, it tries to initialize workflows and with "I" character for workflow function names. But if i use BC in Turkish, it tries to initialize workflows with "İ" character. As a result, there happens two sets of workflows. My suggestion would be;

1) Remove UpperCase function and use directly uppercase letters for function name.

```
procedure RunWorkflowOnAfterInsertIncomingDocumentCode(): Code[128]
begin
    exit('RUNWORKFLOWONAFTERINSERTINCOMINGDOCUMENT');
end;
```
2) or create a special UpperCase function in these codeunits with a publisher such as:

```
procedure RunWorkflowOnAfterInsertIncomingDocumentCode(): Code[128]
begin
    exit(WFUpperCase('RunWorkflowOnAfterInsertIncomingDocument'));
end;

local procedure WFUpperCase(FunctionName: Text) : Code[128]
var
    IsHandled: Boolean;
    UpperCaseFunctionName: Code[128];
begin
    IsHandled := false;
    OnBeforeWSUpperCase(FunctionName, UpperCaseFunctionName, IsHandled);
    if IsHandled then
        exit(UpperCaseFunctionName);

    exit(UpperCase(FunctionName));
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeWSUpperCase(FunctionName: Text; var UpperCaseFunctionName: Code[128]; var IsHandled: Boolean)
begin
end;
```

3) or any other suggestion?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40890.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 40904.
