### ISSUE TITLE
[Event Request] Codeunit 13 Gen. Jnl.-Post Batch Event - Prevent Counts for GuiAllowed()

### ISSUE THREAD

**Issue by tgdoat44** [microsoft/ALAppExtensions#14977]
In #13724 my request to make codeunit 13 "Gen. Jnl.-Post Batch" usable in background processes was granted. However, not all necessary changes were made and the missing changes have a significant negative impact on the performance.

As I can see, the NumberOfRecords is now used in a telemetry function. Up until now the record counts were only used in the progress dialog and therefore it was not necessary to calculated these values if the progress dialog ist already disabled.

We therefore require the possibility to prevent these counts to avoid (in our case) unneccessary calculations with signficant performance impact. Therefore please add the following two integration events:

* `local procedure OnProcessLinesOnBeforeCountNoOfRecords(var GenJnlLine: Record "Gen. Journal Line"; var NoOfRecords: Integer; var IsHandled: Boolean)`
![image](https://user-images.githubusercontent.com/72976203/138710676-c38e64b7-29d6-48b9-b29b-24178ab63505.png)

* `local procedure OnCheckAndCopyBalancingDataOnBeforeCountGenJnlLine(var GenJnlLine4: Record "Gen. Journal Line"; var JnlLineTotalQty: Integer; var IsHandled: Boolean)`
![image](https://user-images.githubusercontent.com/72976203/138711235-c3532df4-dc76-4292-8350-ff153fe5e3a8.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
