### ISSUE TITLE
comment out TESTFIELD(Amount) in codeunit 13

### ISSUE THREAD

**Issue by nanla** [Microsoft/ALAppExtensions#15]
we need to comment out a line TESTFIELD(Amount) in codeunit 13(Gen. Jnl.-Post Batch) in procedure "CheckRecurringLine", so that the user is able to post a zero amount recurring line. 

Can you please tell us how we can modify a codeunit?
thanks

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!

**Comment by JesperSchulz** [comment]
The short answer is: you cannot. We need to adjust our base code to support your extensibility request. but for that, we need more context as to why this change is needed. Could you please provide that?

**Comment by nanla** [comment]
________________________________

**Comment by nanla** [comment]
Thank you for your response.

In table 81 field 109 is "Allow Zero-Amount Posting". when this flag is on, we want to be able to post recurring journal line with zero amount. In standard NAV, we commented out below lines in codeunit 13, so it will not give error message when a recurring journal line has zero amount.
We want to do the same thing in Business Central. How should we do it?
Thank you for helping.


CASE "Recurring Method" OF

//"Recurring Method"::"V Variable","Recurring Method"::"RV Reversing Variable",

//"Recurring Method"::"F Fixed","Recurring Method"::"RF Reversing Fixed":

// TESTFIELD(Amount);

"Recurring Method"::"B Balance","Recurring Method"::"RB Reversing Balance":

TESTFIELD(Amount,0);

END;

________________________________

**Comment by IhorHandziuk** [comment]
Thank you for clarification.
We added a check before testing the field:
```
IF NOT "Allow Zero-Amount Posting" THEN
  TESTFIELD(Amount);
```
This change will be available in the next update.

**Comment by nanla** [comment]
Thank you for the updates.

________________________________
