### ISSUE TITLE
[Request for External] Page "Items by Location" procedure SetColumns vs. SetMatrixType

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#15005]
hey guys,

you made the procedure "SetColumns" obsolet in page "Items by Location" but the replacement procedure "SetMatrixColumns" is set to local.

Please make this procedure global.

```
.....

#if not CLEAN19
    [Obsolete('Replaced by SetMatrixType().', '19.0')]
    procedure SetColumns(SetType: Option)
    begin
        SetMatrixColumns("Matrix Page Step Type".FromInteger(SetType));
    end;
#endif

    local procedure SetMatrixColumns(StepType: Enum "Matrix Page Step Type")

....
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
