### ISSUE TITLE
Typo on the ToolTip text of the Connector field on the Email Account Wizard page in System Application

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#15000]
It should be Specifies instead. Found in 18.0.22893.23773

![image](https://user-images.githubusercontent.com/69611495/139013975-541baaee-98cc-4740-9318-88b0d42ebed5.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
