### ISSUE TITLE
[Event Request] cu 80 - OnFinalizePostingOnBeforeCreateOutboxSalesTrans

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#15008]
Please change from:

            OnFinalizePostingOnBeforeCreateOutboxSalesTrans(SalesHeader, IsHandled, EverythingInvoiced)

to:

            OnFinalizePostingOnBeforeCreateOutboxSalesTrans(SalesHeader, SalesInvHeader, SalesCrMemoHeader, IsHandled, EverythingInvoiced)

[Integration Event] from:

    [IntegrationEvent(false, false)]
    local procedure OnFinalizePostingOnBeforeCreateOutboxSalesTrans(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean; EverythingInvoiced: Boolean)
    begin
    end;

to:

    [IntegrationEvent(false, false)]
    local procedure OnFinalizePostingOnBeforeCreateOutboxSalesTrans(var SalesHeader: Record "Sales Header"; var SalesInvoiceHeader: Record "Sales Invoice Header"; var SalesCrMemoHeader: Record "Sales Cr. Memo Header"; var IsHandled: Boolean; EverythingInvoiced: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
