### ISSUE TITLE
[EventRequest] codeunit 1012 "Job Jnl.-Post Line" - OnBeforeModifyValueEntry set VAR for parameter IsHandled 

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#15007]
Requesting a change on existing Publisher OnBeforeModifyValueEntry.
The existing parameter IsHandled is currently passed by value and we need to pass it by Reference (Var). In this case the Ishandled Pattern is not working for our Subscribers.

Event
```
[IntegrationEvent(false, false)]
local procedure OnBeforeModifyValueEntry(var ValueEntry: Record "Value Entry"; JobJournalLine: Record "Job Journal Line";   
IsHandled: Boolean)
   begin
   end;
```

In Issue https://github.com/microsoft/ALAppExtensions/issues/10397 I requested this publisher where parameter IsHandled is defined by Reference, Unfortunately this is not the case in BC19.

**Code**
## local procedure ModifyValueEntry(var ValueEntry: Record "Value Entry")
```
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeModifyValueEntry(ValueEntry, JobJnlLine2, IsHandled);
        if IsHandled then
            exit;

        ValueEntry.Modify(true);
    end;
```

The current Publisher has the following definition:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeModifyValueEntry(var ValueEntry: Record "Value Entry"; JobJournalLine: Record "Job Journal Line"; IsHandled: Boolean)
  begin
  end;
```

We need it to be like below:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeModifyValueEntry(var ValueEntry: Record "Value Entry"; JobJournalLine: Record "Job Journal Line"; VAR IsHandled: Boolean)
  begin
  end;
```

Can you please add this change because we need this parameter by reference to use in our extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
