### ISSUE TITLE
Table 39 Purchase Line - OnUpdateDirectUnitCostByFieldOnBeforeUpdateItemReference 

### ISSUE THREAD

**Issue by acicatech** [microsoft/ALAppExtensions#15016]
CalledByFieldNoParam would be great in var mode in order to allow devs modify the value on event subscriber and skip executing UpdateItemReference function. Another solution can be isHandled variable.

Event definition :

    [IntegrationEvent(false, false)]
    local procedure OnUpdateDirectUnitCostByFieldOnBeforeUpdateItemReference(var PurchaseLine: Record "Purchase Line"; CalledByFieldNo: Integer)
    begin
    end;

Source Code :

        OnUpdateDirectUnitCostByFieldOnBeforeUpdateItemReference(Rec, CalledByFieldNo);
        if Type = Type::Item then
            if CalledByFieldNo in [FieldNo("No."), FieldNo("Variant Code"), FieldNo("Location Code")] then
                UpdateItemReference;

Best Regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
