### ISSUE TITLE
CopyBlob operation not working on "ABS Blob Client" Business Central 19

### ISSUE THREAD

**Issue by MarijnRuttenGAC** [microsoft/ALAppExtensions#15011]
I have a simple CopyBlob operation which isn't working.

`Procedure CopyBlob(ContainerName: Text; Source: Text; Destination: Text)`
`    var`
        `BlobClient: Codeunit "ABS Blob Client";`
    `begin`
        `BlobClient := GetBlobClient(ContainerName);`
        `BlobClient.CopyBlob(Destination, Source);`

It returns the following error:
"Could not copy aaa.xml to bbb/aaa.xml..
Response Code: 400 The value for one of the HTTP headers is not in the correct format."

I can't seem to put in some HTTP Headers, and there is no AL documentation available regarding this "ABS Blob Client" Codeunit. Any help would be appreciated

Other operations like "PutBlobBlockBlobStream" and "DeleteBlob" are working fine.

**Comment by mazhelez** [comment]
Hey @MarijnRuttenGAC 

What does `GetBlobClient` do? 

The existing AL documentation for the `CopyBlob` functions points to [REST API CopyBlob](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob).

Here is the doc for the source BLOB:

> Required. Specifies the name of the source blob or file.

> Beginning with version 2012-02-12, this value may be a URL of up to 2 KiB in length that specifies a blob. The value should be URL-encoded as it would appear in a request URI. A source blob in the same storage account can be authorized via Shared Key. However, if the source is a blob in another account, the source blob must either be public or must be authorized via a shared access signature. If the source blob is public, no authorization is required to perform the copy operation.

> Beginning with version 2015-02-21, the source object may be a file in the Azure File service. If the source object is a file that is to be copied to a blob, then the source file must be authorized using a shared access signature, whether it resides in the same account or in a different account.

> Only storage accounts created on or after June 7th, 2012 allow the Copy Blob operation to copy from another storage account.

> Here are some examples of source object URLs:

> - https://myaccount.blob.core.windows.net/mycontainer/myblob
> - https://myaccount.blob.core.windows.net/mycontainer/myblob?snapshot=<DateTime>
> - https://myaccount.blob.core.windows.net/mycontainer/myblob?versionid=<DateTime>

> When the source object is a file in the Azure File service, the source URL uses the following format; note that the URL must include a valid SAS token for the file:

> - https://myaccount.file.core.windows.net/myshare/mydirectorypath/myfile?sastoken

> In versions before 2012-02-12, blobs can only be copied within the same account, and a source name can use these formats:

> - Blob in named container: /accountName/containerName/blobName
> - Snapshot in named container: /accountName/containerName/blobName?snapshot=<DateTime>
> - Blob in root container: /accountName/blobName
> - Snapshot in root container: /accountName/blobName?snapshot=<DateTime>

**The current version is _2020-10-02_**.

Do you call it with a file URL or just BLOB name?

**Comment by MarijnRuttenGAC** [comment]
Hello @mazhelez,

The documentation that you have provided only shows API documentation.
We are working with the integrated BLOB operations in the Business Central AL language therefor the above solutions aren't applicable.
Is it possible to schedule a Teams meeting so I can explain the issue we are encountering?

**Comment by mazhelez** [comment]
> The documentation that you have provided only shows API documentation. We are working with the integrated BLOB operations in the Business Central 19 AL language therefor the above solutions aren't applicable. 

The current solution only wraps the existing REST API. And the code is right here in the repo. See [here](https://github.com/microsoft/ALAppExtensions/blob/main/Modules/System/Azure%20Blob%20Services%20API/src/ABSBlobClient.Codeunit.al)

> Is it possible to schedule a Teams meeting so I can explain the issue we are encountering?

Let's keep a Teams meeting a last resort. 

From the description of the issue, it looks like one of the HTTP headers is not in the correct format. For `CopyBlob` the headers are:
- `Authorization`. I assume that's not it, as you mentioned other functions work as expected. Still, to my previous question: what does `GetBlobClient` do?
- `x-ms-date`. Same as above.
- `x-ms-version`. Same as above.
- `x-ms-copy-source`. That's the most probable culprit. So again, please read the documentation and see if you find your answer.

**Comment by MarijnRuttenGAC** [comment]
I'm sorry, the GetBlobClient authorizes with the Azure environment and gets our predefined settings from BC (Path to the file on Azure).
I also believe that one of the HTTP Headers is not in the correct format, however we can't seem to change those headers.
When we try to debug the issue, it shows us the ABS Blob Client codeunit empty.. It guess that we are not allowed to access it and see what's going on.
I will check the documentation more closely and will come back to you. Even when I manage to solve the issue.

**Comment by mazhelez** [comment]
Hey @MarijnRuttenGAC 

Did you manage to solve the issue?
Let me know if I can help with anything.

**Comment by mazhelez** [comment]
Hey @MarijnRuttenGAC 

Any development on the issue? Since you haven't updated it in more than 3 weeks, I'll consider it resolved. Ping me if it's not.

**Comment by jmpuigdollers** [comment]
Hi,
I've got the same error. Any idea about the solution?
Here, the piece of code


        ABSOperationResponse := ABSBlobClient.CopyBlob(DestinationUrl, SourceUrl);
        if ABSOperationResponse.IsSuccessful() then
            ABSBlobClient.DeleteBlob(SourceUrl)
        else
            Message(ABSOperationResponse.GetError())



Josep M
