### ISSUE TITLE
[VAR Request] OnRunOnBeforeCommit / CU "TransferOrder-Post Shipment"

### ISSUE THREAD

**Issue by sgiordy** [microsoft/ALAppExtensions#15019]
Hello,

similarly than in CU "Sales-Post" /  "Purch.-Post" please change the signature of OnRunOnBeforeCommit from:

`local procedure OnRunOnBeforeCommit(var TransferHeader: Record "Transfer Header"; TransferShipmentHeader: Record "Transfer Shipment Header"; PostedWhseShptHeader: Record "Posted Whse. Shipment Header")`

to

`local procedure OnRunOnBeforeCommit(var TransferHeader: Record "Transfer Header"; TransferShipmentHeader: Record "Transfer Shipment Header"; PostedWhseShptHeader: Record "Posted Whse. Shipment Header"; var SuppressCommit: Boolean)`

and pass it the global SuppressCommit variable.

Thank you
S.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
