### ISSUE TITLE
Codeunit 6620 Copy Document Mgt. CopyDocSalesLine DocLineNo in Events

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/ALAppExtensions#15017]
Hello,

Please extend the events

OnBeforeCopySalesLine

`IsHandled := false;
        OnBeforeCopySalesLine(ToSalesHeader, FromSalesHeader, FromSalesLine, RecalculateLines, CopyThisLine, MoveNegLines, Result, IsHandled);
        if IsHandled then
            exit(Result);`

and 

OnCopySalesDocLineOnBeforeCopyThisLine

`        IsHandled := false;
        OnCopySalesDocLineOnBeforeCopyThisLine(ToSalesHeader, ToSalesLine, FromSalesLine, FromSalesDocType, RecalculateLines, CopyThisLine, LinesNotCopied, Result, IsHandled);
        if IsHandled then
            exit(Result);`

with the parameter of the value DocLineNo.

`IsHandled := false;
        OnBeforeCopySalesLine(ToSalesHeader, FromSalesHeader, FromSalesLine, RecalculateLines, CopyThisLine, MoveNegLines, DocLineNo, Result, IsHandled);
        if IsHandled then
            exit(Result);`

`    [IntegrationEvent(false, false)]
    local procedure OnBeforeCopySalesLine(var ToSalesHeader: Record "Sales Header"; FromSalesHeader: Record "Sales Header"; FromSalesLine: Record "Sales Line"; RecalculateAmount: Boolean; var CopyThisLine: Boolean; MoveNegLines: Boolean; DocLineNo:Integer; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;`

`        IsHandled := false;
        OnCopySalesDocLineOnBeforeCopyThisLine(ToSalesHeader, ToSalesLine, FromSalesLine, FromSalesDocType, RecalculateLines, DocLineNo, CopyThisLine, LinesNotCopied, Result, IsHandled);
        if IsHandled then
            exit(Result);`

`    [IntegrationEvent(false, false)]
    local procedure OnCopySalesDocLineOnBeforeCopyThisLine(ToSalesHeader: Record "Sales Header"; var ToSalesLine: Record "Sales Line"; FromSalesLine: Record "Sales Line"; FromSalesDocType: Enum "Sales Document Type From"; var RecalculateLines: Boolean; DocLineNo:Integer; var CopyThisLine: Boolean; var LinesNotCopied: Integer; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;`

Thank you in advance.

Best Regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
