### ISSUE TITLE
[Event-Request] Table 7500 Item Attribute - Event: OnAfterHasBeenUsed

### ISSUE THREAD

**Issue by HHynynen** [microsoft/ALAppExtensions#15012]
In table 7501 Item Attribute Value there is this event:
LOCAL [IntegrationEvent] OnAfterHasBeenUsed(ItemAttributeValue : Record "Item Attribute Value";VAR AttributeHasBeenUsed : Boolean)
Same event is needed for the table Item Attribute also.

When using master data synchronization, it must be possible to avoid the confirmation about deleting Item Attribute.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
