### ISSUE TITLE
[Event request] Table 37 - OnAfterCreateDim

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#1501]
To port a NAV add-on to BC, we need to run some additional logic at the end of the CreateDim function in table 37.  Could you please add an event to the end of that function for OnAfterCreateDim?

**Comment by AlexanderYakunin** [comment]
Same as for TAB81

**Comment by RHansenEpimatic** [comment]
Thanks again!

**Comment by miljance** [comment]
Hi, what is the status of this requirement? It seems that pulisher never made it to the release. @AlexanderYakunin @jobulsin @JesperSchulz
