### ISSUE TITLE
Transfer "Email Related Records" to other (posted) source record > Email.RemoveRelation

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#15023]
If mails are sent for a **draft** sales invoice, the Sent Emails are stored, linked to table **Sales Header** and its systemid.
However, when the invoice is posted, the Sent Emails (in fact, the Email Related Record) still refers to table Sales Header.

This way, we loose track of the preceding communication on the posted sales invoice (in case we would add the 'Sent Emails' action here) + we loose navigation on the Sent Emails to the Source Document (action 'Show Source') since the record no longer exists.

We would like to - as part of the posting process - **move** the Sent Emails from the non posted to the posted document.
However, Email Related Record is set to internal. We were thinking of removing the Email Related Records for the sales header record and create new ones (via AddRelation) for the posted document record.

Does this suggestion seems valid for a PR? (@JesperSchulz )
If yes, we would create a `RemoveRelation` function, with similar signature as `AddRelation`.

```
///<summary>
    /// Adds a relation between an email message and a record.
    ///</summary>
    ///<param name="EmailMessage">The email message for which to create the relation.</param>
    ///<param name="TableId">The table ID of the record.</param>
    ///<param name="SystemId">The system ID of the record.</param>
    ///<param name="RelationType">The relation type to set.</param>
    procedure AddRelation(EmailMessage: Codeunit "Email Message"; TableId: Integer; SystemId: Guid; RelationType: Enum "Email Relation Type")
    begin
        EmailImpl.AddRelation(EmailMessage, TableId, SystemId, RelationType);
    end;
```

**Comment by JesperSchulz** [comment]
Sorry, it took a while before this issue landed on my desk :-( To me, it sounds like this should be the default behavior of the system, and not something partners should individually have to implement. While "RemoveRelation" absolutely would be a valid PR (other scenarios come to mind, where you would want to be able to control the relationship between emails and entities), I think we will look at this request from our end as well to see if we cannot make this work "out of the box". Given, that the required investment is small, we'll process this request as an enhancement. We'll do a quick investigation and return to you.

**Comment by fvet** [comment]
@JesperSchulz  It would be great if this can be added 'out of the box' for the standard BC processes that follow a Draft (non-posted) / Posted pattern. Native support for transferring sent emails from sales invoices to posted sales invoices would fix the above requirement.

Nevertheless, as an ISV, we have created additional entities in our add-on following the same draft / posted pattern and would like to include the transfer of sent email from one record (table / recordid) to another record (other table / recordid). So any set of functions that allows us to 'move' sent emails between records would be welcome ;)

**Comment by JesperSchulz** [comment]
I discussed this with the team this morning, and while this absolutely is a great and valid scenario which we'd love to support "out of the box", we won't be able to prioritize this right now. I will add a work item to my team's backlog to look at this, when time allows, but that will take a while. It's actually a great "intern project", as it's a rather confined task. Maybe my next intern gets to look into this ;-)
Until then, feel free to create PRs with the functions you need, to implement support for this scenario yourself! Your request makes sense and we'll happily process your PRs.
