### ISSUE TITLE
Codeunit 5763 new event on procedure  SetPrint

### ISSUE THREAD

**Issue by ASLANSABINEFR** [microsoft/ALAppExtensions#15027]
Hi,

We need a new event on codeunit 5763 procedure SetPrint :

```
.....
 procedure SetPrint(Print2: Boolean)
    begin
        Print := Print2;
        // > New Event
        OnSetPrint(Print);
        // < New Event
    end;
.....

[IntegrationEvent(false, false)]
    local procedure OnSetPrint(var Print: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
