### ISSUE TITLE
[Event Request] Codeunit 5763 new event on procedure  HandleSalesLine

### ISSUE THREAD

**Issue by ASLANSABINEFR** [microsoft/ALAppExtensions#15024]
Hi,

We need a new event on codeunit 5763 procedure HandleSalesLine :

```
.....
 OnBeforeSalesLineModify(SalesLine, WhseShptLine, ModifyLine, Invoice);
                    if ModifyLine then
                        SalesLine.Modify();
                    // > New Event
                    OnAfterSalesLineModify(SalesLine, ModifyLine)
                   // < New Event
......

 [IntegrationEvent(false, false)]
    local procedure OnAfterSalesLineModify(var SalesLine: Record "Sales Line"; ModifyLine: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
