### ISSUE TITLE
[Event Required]: "OIOUBL-Export Sales Invoice" Codeunit 

### ISSUE THREAD

**Issue by tayyabahmed-DI** [microsoft/ALAppExtensions#15022]
In OIOUBL Extension for Danish customers by Microsoft.
**Codeunit** = "OIOUBL-Export Sales Invoice" **Codeunit Object ID** = 13636

We need to Add "Work Description" field's data of "Sales Invoice Header" table as XML tag called <cbc:Note></cbc:Note>. And we need to add it right after <cbc:InvoiceTypeCode></cbc:InvoiceTypeCode> XML tag otherwise the document will not be considered valid.

We already have found an event in this codeunit called 'OnCreateXMLOnBeforeInsertAccountingSupplierParty' but it adds up just before <cac:AccountingSupplierParty> starting tag which makes the OIOUBL document invalid.

Can you please **raise an event** similar to 'OnCreateXMLOnBeforeInsertAccountingSupplierParty' event but very after <cbc:InvoiceTypeCode></cbc:InvoiceTypeCode> XML tag designing line of AL code, so we can subscribe to it and add "Work Description" field's data after it?

The event should be raised here:
![image](https://user-images.githubusercontent.com/84970349/139443338-c9499c0a-b72b-4bf5-ac82-27d4b2ba4e38.png)

The event definition should look like:

```
[IntegrationEvent(false, false)]
    local procedure OnCreateXMLOnAfterInsertInvoiceTypeCode(SalesInvoiceHeader: Record "Sales Invoice Header"; var XMLCurrNode: XmlElement)
    begin
    end;
```

The file that we want to export should look somewhat like this.
![image](https://user-images.githubusercontent.com/84970349/139439233-98d9c58f-aba2-4942-a706-e3b9074662c8.png)

Thanks,
Tayyab Ahmed

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
