### ISSUE TITLE
[VAR Request] OnRunOnBeforeCommit / CU "TransferOrder-Post Receipt"

### ISSUE THREAD

**Issue by sgiordy** [microsoft/ALAppExtensions#15020]
Hello,

similarly than in CU "Sales-Post" /  "Purch.-Post" please change the signature of OnRunOnBeforeCommit from:

`local procedure OnRunOnBeforeCommit(var TransHeader: Record "Transfer Header"; TransRcptHeader: Record "Transfer Receipt Header"; PostedWhseRcptHeader: Record "Posted Whse. Receipt Header")`

to

`local procedure OnRunOnBeforeCommit(var TransHeader: Record "Transfer Header"; TransRcptHeader: Record "Transfer Receipt Header"; PostedWhseRcptHeader: Record "Posted Whse. Receipt Header"; var SuppressCommit: Boolean)`

and pass it the global SuppressCommit variable.

Thank you
S.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
