### ISSUE TITLE
[Event Request] Codeunit 5069 "Word Template Interactions" - Access = Public

### ISSUE THREAD

**Issue by OlegKulyk86** [microsoft/ALAppExtensions#15021]
Hi, would it be possible to change an **Access** property in codeunit 5069 (**Word Template Interactions**) to **Public** to get aссess to event(s) that were added, for example to **OnAfterGetDataSource**?

#14339

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
