### ISSUE TITLE
[Event Request] Codeunit 5702 "Dist. Integration", Procedure ProcessSalesLine, Event OnAfterInsertPurchLine - additional parameter "NextLineNo" 

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#15039]
Hi, 
we would like to add additional text lines for special orders and therefore we need an additional parameter "NextLineNo" (with **var**) for the event "OnAfterInsertPurchLine", fired in procedure ProcessSalesLine):

`OnAfterInsertPurchLine(PurchLine, SalesLine,NextLineNo);`

The existing event with the new parameter looks like this:
`local procedure OnAfterInsertPurchLine(var PurchaseLine: Record "Purchase Line"; SalesLine: Record "Sales Line"; var NextLineNo: Integer)`

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
