### ISSUE TITLE
[Event Request (parameter)] Make SalesHeader a var in "Sales-Post and Send".OnCodeOnBeforePostSalesHeader

### ISSUE THREAD

**Issue by RWeston6** [microsoft/ALAppExtensions#15034]
Salesheader needs to be a var in the below event otherwise subsequent code such as SalesPost.SendPostedDocumentRecord(SalesHeader, TempDocumentSendingProfile) will not work.

codeunit 79 "Sales-Post and Send"
```
[IntegrationEvent(false, false)]
    local procedure OnCodeOnBeforePostSalesHeader(var SalesHeader: Record "Sales Header"; var TempDocumentSendingProfile: Record "Document Sending Profile" temporary; HideDialog: Boolean; var IsHandled: Boolean)
    begin
    end; 
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
