### ISSUE TITLE
[Event Request] Table 7500 "Item Attribute - OnAfterHasBeenUsed(Rec, AttributeHasBeenUsed);

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#15049]
In table 7501 "Item Attribute Value" we have an event OnAfterHasBeenUsed(Rec, AttributeHasBeenUsed);
Using this we can avoid user interference when deleting the "Item Attribute Value"

But we need a similar event in Table 7500 "Item Attribute" - it is exactly the same structure

 [IntegrationEvent(false, false)]
 local procedure OnAfterHasBeenUsed(ItemAttributeValue: Record "Item Attribute Value"; var AttributeHasBeenUsed: Boolean)
 begin
 end;

So the procedure HasBeenUseed must be expanded with the same type of event plus restructure.

Now:
![image](https://user-images.githubusercontent.com/28138717/139820902-4122f8ad-da24-4e7a-aa5b-57d10e86de6e.png)

 
Solution could be.
 
![image](https://user-images.githubusercontent.com/28138717/139820913-68f05cce-626a-4a16-8a62-93bbf7794aca.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
