### ISSUE TITLE
[Event Request] Table 18 "Customer", OnValidate Field "No.", OnBeforeNoSeriesTestManual

### ISSUE THREAD

**Issue by meilel** [microsoft/ALAppExtensions#15041]
Please add an event OnBeforeNoSeriesTestManual with an IsHandled Boolean.
We use multiple No. Series on Table 18. We need to be able, to test a diffrent no. series then the one in sales setup.
![image](https://user-images.githubusercontent.com/46705270/139689597-f30f38da-b883-4e2f-9737-c20205194b8c.png)

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
