### ISSUE TITLE
[EventRequest] Report 99001020 "Carry Out Action Msg. - Plan."

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#15044]
Please transfer global variables from option to extensible enum:
- ProdOrderChoice
- PurchOrderChoice
- TransOrderChoice

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
