### ISSUE TITLE
Email Outbox html text editor functionality

### ISSUE THREAD

**Issue by lars1407** [microsoft/ALAppExtensions#15040]
Hi,
we noticed the integrated html text editor feature in Microsoft Page 13 "Email Editor". We'd like to use this functionalty for our own extensions, but can't see in the Microsoft AL program code how this functionality is implemented/how it works. Additionaly the potential AL Code is implemented as internal and thus can't be used anyways.

Is there a way how to make use of the Microsoft standard version in AL code or do we have to use the CKEditor mentioned down below, which apparently is not free for commercial use.

Only hint I found: https://docs.microsoft.com/en-us/dynamics365-release-plan/2020wave2/finance-operations/finance-operations-crossapp-capabilities/new-html-editor-control
(the mentioned CKEditor in this Microsoft hint can't be used for free)

This was the last found request for an editor (html): https://experience.dynamics.com/ideas/idea/?ideaid=6497fbae-cc6b-e911-b047-0003ff688f46

Houggard has publish an WYSIWYG editor which seems to be based on CKEditor as well: https://github.com/hougaard/wysiwyg-al/

Thanks in advance for your feedback.

![image](https://user-images.githubusercontent.com/85485016/139667179-ecfb41c0-9b8c-4c3d-b518-f8b3c439e944.png)

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
Unfortunately, the Rich Text editor control is not available as a reusable control (yet). There is indeed plenty of support for the above mentioned idea to complete our work of making the control publicly available, but so far we haven't been able to get around to do so. For now, you will have to use alternatives, as the ones you describe. Sorry about that.

**Comment by dnpb** [comment]
see also https://experience.dynamics.com/ideas/idea/?ideaid=6497fbae-cc6b-e911-b047-0003ff688f46
