### ISSUE TITLE
[Event Request] Page 5050 - "Contact Card" - OnAfterEnableFields

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#15050]
Hi AL-Team,
can you please the following publisher in EnableFields?

local procedure EnableFields()
    begin
        CompanyGroupEnabled := Type = Type::Company;
        PersonGroupEnabled := Type = Type::Person;
        CurrencyCodeEnable := Type = Type::Company;
        VATRegistrationNoEnable := Type = Type::Company;
        CompanyNameEnable := Type = Type::Person;
        OrganizationalLevelCodeEnable := Type = Type::Person;
        // NEW >>>>
        OnAfterEnableFields(CompanyGroupEnabled, PersonGroupEnabled, CurrencyCodeEnable, VATRegistrationNoEnable, CompanyNameEnable, OrganizationalLevelCodeEnable);
        // NEW <<<<
    end;

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterEnableFields(var CompanyGroupEnabled: Boolean; var PersonGroupEnabled: Boolean; var CurrencyCodeEnable: Boolean; var VATRegistrationNoEnable: Boolean; var CompanyNameEnable: Boolean; var OrganizationalLevelCodeEnable: Boolean)
    begin
    end;
```

Alternatively, you could throw the event without parameters but with "IncludeSender" and set the individual variables to "protected".

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
