### ISSUE TITLE
Field not visible "Fik Import Format" on page General Ledger Setup(Payment and Reconciliation Formats (DK)

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#15051]
Unable to configure field  "FIK Import Format" as this is not visible on the Page 188 "Generel Ledger Setup" 

The FIK Import fails as it tries to get that field in Codeunit 13650 FIKManagement but if empty it breaks.

In procedure ImportFIKToBankAccRecLine

        GeneralLedgerSetup.Get();
        DataExchDef.Get(GeneralLedgerSetup."FIK Import Format");

 https://github.com/microsoft/ALAppExtensions/blob/7c34747bcf1e3de8abc4e87b0fcd3bb70c0910b0/Apps/DK/FIK/app/src/codeunits/Management.Codeunit.al

Please also update error message if this field is not set as the user has no idea what is missing.

**Comment by AlexanderYakunin** [comment]
Which version you are looking into?

**Comment by MortenRa** [comment]
I believe this is in every version.

But 
BC  Version: DK Business Central 19.0 (Platform 19.0.29884.31839 + Application 19.0.29894.30403)
Extension
Payment and Reconciliation Formats (DK) Payment and Reconciliation Formats (DK)

and looking into github repo for the extension Payment and Reconciliation Formats (DK) Payment and Reconciliation Formats (DK)
https://github.com/microsoft/ALAppExtensions/blob/7c34747bcf1e3de8abc4e87b0fcd3bb70c0910b0/Apps/DK/FIK/app/src/

I do not see a page extension on the Generel Ledger Setup

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
