### ISSUE TITLE
[Event Change] Add Parameters to OnOpenPage Event in Report 99001017

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#15059]
Can you extend this event in report 99001017 "Calculate Plan - Plan. Wksh." and its call by the `FromDate` and the `ToDate`?
```
trigger OnOpenPage()
begin
    InitializeFromMfgSetup();
    OnAfterOnOpenPage(FromDate, ToDate);
end;
```
with

```
[IntegrationEvent(false, false)]
local procedure OnAfterOnOpenPage(var FromDate: Date; var ToDate: Date)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
