### ISSUE TITLE
Media of type gif not shown anymore as image

### ISSUE THREAD

**Issue by pieter-kok** [microsoft/ALAppExtensions#15055]
Dear team,

In one of our products we use gif files that are supplied by an external service while creating items.
Since BC19, but also in NextMajor (tested in 20.0.31871), those gif files are not shown anymore in the FactBoxes on the Item Card. When the image is exported, the actual image is there and it can be saved. It's only not shown anymore:

![NextMajor](https://user-images.githubusercontent.com/34770900/139839146-412fa39a-f8f5-4b96-9a65-3364aad34d73.png)

This can be tested by manually importing the supplied gif file (the only file in the attached [Product.zip](https://github.com/microsoft/ALAppExtensions/files/7460041/Product.zip)) using the action on the FactBox of the Item in a standard database. In BC18, the same image (that I also added in the attached zip-file) is shown as expected:

![BC18](https://user-images.githubusercontent.com/34770900/139839414-7a4900ea-ce03-470e-a68b-2867113abd1b.png)

Is something changed intentionally regarding the gif-format or is this unexpected behaviour?

**Comment by AlexanderYakunin** [comment]
We can upload several gif files and they show up correctly. Your image seems to be corrupted gif file, please check with other images and confirm if you have same problem.

**Comment by pieter-kok** [comment]
I just checked your statement by creating a GIF file using Paint, just a file with a single column.

![1](https://user-images.githubusercontent.com/34770900/140070532-6192932f-19d4-4b8a-839a-e3910ab077b9.png)

I first uploaded it into Version: W1 20.0 (Platform 20.0.31831.0 + Application 20.0.31871.0), also BC19 the same behavior:

![2](https://user-images.githubusercontent.com/34770900/140071168-cdd38187-6fd7-4aa8-8380-1d117351bd54.png)

In BC18, in my specific situation it was NL Business Central 18.5 (Platform 18.0.29486.31726 + Application 18.5.29545.31822), this just works:

![3](https://user-images.githubusercontent.com/34770900/140073276-cd91f68b-3682-4481-902b-c13822c8c08a.png)

That makes me conclude that it is something in BC that is different, not the imported gif file.

Besides that, what made you think that the image was corrupt? When I open the gif from a downloaded copy of the attached zip-file, it just shows me the picture in my default app (Windows Photo-app).
Other thing. If it was corrupted, why is the exact same image correctly shown in BC18 and not in BC19 and upwards?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
