### ISSUE TITLE
Requested event not available

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#15064]
Recently I've requested a number of new events and to make procedures external or protected.

All event requests have been accepted and they are already available in 19.1 (apart from one). That's great!

Just one event seems to be missing. Please add this one as well: https://github.com/microsoft/ALAppExtensions/issues/14780

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
