### ISSUE TITLE
Problems with EnumExtensions and Evaluate

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#15067]
Is there a problem with EnumExtensions and EVALUATE-Function ?

I have a docker OnPrem version 19.0.29894.30693-de and the following problem:

I have extended the Enum 1670 "Option Lookup Type" with my own Enum-Type as follows:

enumextension 5505268 "M365 Option Lookup Type" extends "Option Lookup Type"
{
    value(30; M365)
    {
        Caption = 'M365';
    }
}

I want to use my option in order to server my own tables and their enum-fields for a Lookup on the Enum-Values.

So I coded in my own action the following code:

    var
        optionLookupBuffer: Record "Option Lookup Buffer";
    begin
        optionLookupBuffer.SetRange("Lookup Type", optionLookupBuffer."Lookup Type"::M365);
        optionLookupBuffer."Lookup Type" := optionLookupBuffer."Lookup Type"::M365;
        Evaluate(optionLookupBuffer."Lookup Type", optionLookupBuffer.GetFilter("Lookup Type"));

Up to this statement everything is okay and I can use my own Enum-Value and even evaluate the value into  the field optionLookupBuffer."Lookup Type".

Now I call the page 1670 "Option Lookup List". 

        if Page.RunModal(0, optionLookupBuffer) = Action::LookupOK then
            fieldValue := optionLookupBuffer."Option Caption";

This page 1670 calls on the trigger OnOpenPage() exactly those statements above:    trigger OnOpenPage()
    var
        OptionLookupBuffer: Record "Option Lookup Buffer";
    begin
        if Rec.GetFilter("Lookup Type") = '' then
            exit;

        Evaluate(OptionLookupBuffer."Lookup Type", Rec.GetFilter("Lookup Type"));

But this last statement Evaluate with my own Enum-Value now gives the error that the Enum-Value "M365" does not exist.

So the following the statements are not executed
        Rec.FillLookupBuffer(OptionLookupBuffer."Lookup Type");

and the event OnFillBufferLookupTypeCase on table 1670 "Option Lookup Buffer" is not executed and I cannot fill the LookupBuffer with my own values.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting an AL compiler bug, not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
