### ISSUE TITLE
Inventory Documents issues

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#15060]
Hi!

It would be good to bring the inventory documents to a perfect form, since now they do not work quite correctly and predictably.

1. In the document there is a field number taking into account a series of numbers. It would be nice to be able to redefine it for this you need the OnAfrerInitRecord event on table 5850 at the end of the InitRecord function.
2. When creating a posted document in codeunits 5850 and 5851, it is worth taking the posting number from document field Posting No. instead of generating a new number from a series, if it is empty, then take a number from a series of Posting No. Series field.
3. When posting a invt. shipment document with the correction attribute, an entry in item application entry is created between shipment and correction, however, shipment has already been applied to the first inbound and it is not possible to correct this through the application journal. I think that in this case the operation should not be created or the first application between shipment and first inbound should be canceled.
4. It would be nice to add a preview posting fuction for this documents.

Thank you!

**Comment by StanPesotskiy** [comment]
@vlkov
1 and 2 - can be done is scope of this request.
3 - seems to be a bug, please report it via a relevant support channel. It requires detailed repro steps for the further investigation.
4 - a request for a new functionality. Please submit a product suggestion on https://aka.ms/bcideas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
