### ISSUE TITLE
Request for external not in next minor

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#15063]
Recently I've requested a number of new events and to make procedures external or protected.

All event requests have been accepted and they are already available in 19.1 (apart from one).  That's great!
However, all requests for external are not available in 19.1. Not in 19.2 as well. But they are available in the current build of the next major, v20.

Is there a specific reason to make them only available in the net major release and not in the next minor?

All requests:
https://github.com/microsoft/ALAppExtensions/issues/14765
https://github.com/microsoft/ALAppExtensions/issues/14770
https://github.com/microsoft/ALAppExtensions/issues/14771
https://github.com/microsoft/ALAppExtensions/issues/14772
https://github.com/microsoft/ALAppExtensions/issues/14773
https://github.com/microsoft/ALAppExtensions/issues/14778
https://github.com/microsoft/ALAppExtensions/issues/14779
https://github.com/microsoft/ALAppExtensions/issues/14781
https://github.com/microsoft/ALAppExtensions/issues/14784
https://github.com/microsoft/ALAppExtensions/issues/14787
https://github.com/microsoft/ALAppExtensions/issues/14788

**Comment by AndriiSeverin** [comment]
@ajkauffmann, according to https://github.com/microsoft/ALAppExtensions/blob/main/FAQ.md#what-do-all-the-labels-assigned-to-issues-mean it is a usual flow for implementing the **Request-for-external**. However, it is a good question to understand the reason for such an approach.

**Comment by JesperSchulz** [comment]
As agreed, I'll backport these items for you, in time for the 19.2 release :-)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
