### ISSUE TITLE
Extensibility Request: Change UpdatePropagation to "Both" in the "Job Card" page

### ISSUE THREAD

**Issue by cbrandemann** [microsoft/ALAppExtensions#15065]
part(JobTaskLines; "Job Task Lines Subform")
{
    ApplicationArea = Jobs;
    Caption = 'Tasks';
    SubPageLink = "Job No." = FIELD("No.");
    SubPageView = SORTING("Job Task No.")
                  ORDER(Ascending);
    UpdatePropagation = Both;
}

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
