### ISSUE TITLE
[Application / Bug] FldRefHasValue return false for first option value

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#15085]
`FldRefHasValue` has been exposed by #12644, but does not give the desired result (when testing e.g for mandatory fields / fields having a value). It does not work properly for option fields.

If I would have an option with 2 values : `Import,Export` (0,1) the standard code (left side of screenshot) will return HasValue as false, in case the option is 'Import' (0), which seems wrong.

Shouldn't option values always return true instead?  (right side of screenshot = changed / copied function)

![image](https://user-images.githubusercontent.com/25268332/140314424-233b3a3f-4fe2-4d63-994b-d9e56e103073.png)

PS: Only other scenario could be if you would have blank values : E.g. `' ', Import, Export` (0,1,2) or` Import,Export,' '` (0,1,2)

**Comment by dnpb** [comment]
`TestField(OptionField)` errors if the value has integer representation of 0, doesn't it? So then the behaviour makes sense to me
