### ISSUE TITLE
[Expose Functions] 1218 "Map Incoming Doc to Purch Doc"

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#15086]
Following #12944, the requested function **ProcessField, GetValueFromIntermediate, IsFieldProcessed** have not been exposed.

Can you please make the functions global, so we can process our own fields (in OnAfterProcessLines).

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
