### ISSUE TITLE
Enum Request Table 97 Comment Line, field 1"Table Name"

### ISSUE THREAD

**Issue by arnasif** [microsoft/ALAppExtensions#1509]
Hi Team,
Please implement field 1 "Table Name" in Table 97 "Comment Line" as enum.
Best regards,
Arna Sif

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
