### ISSUE TITLE
[Additional publisher] Codeunit 410, Update Analysis View, OnBeforeUpdateEntriesForGLAccount

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#15093]
Hi Team,

In codeunit 410 - "Update Analysis View", we need possibility to process more on function "UpdateEntriesForGLAccount". Standard publisher OnBeforeUpdateEntriesForGLAccount may help us:

![image](https://user-images.githubusercontent.com/91654106/140472640-a5606029-127e-431a-9486-f44a8a102a5b.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateEntriesForGLAccount(var TempAnalysisViewEntry: Record "Analysis View Entry" temporary; AnalysisView: Record "Analysis View"; LastGLEntryNo: Integer; var NoOfEntries: Integer; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
