### ISSUE TITLE
[EventRequest] FA Depreciation Calculation

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#15091]
Hi,
It's will be better to add some new events to Fixed Assets functionality

codeunit 5616 Depreciation Calculation
add new paramentr for event OnAfterDeprDays Year365Days: Boolean

function GetFirstDeprDate
    event OnBeforeGetFirstDeprDate(FANo;DeprBookCode;Year365Days;var LocalDate;var IsHandled)
    event OnAfterSetAcquisitionFiltersLedgerEntryGetFirstDeprDate(var FALedgEntry;var LocalDate);

Make function DeprDays365 global

codeunit  5611 Calculate Normal Depreciation
  add parameter to event OnAfterCalcSL FirstDeprDate:Date
  function CalcSLAmount
     event OnCalcSLAmountOnRemainingLifeExpired(FA, FADeprBook,BookValue,var Result, var IsHandled) and raise it on 
          
      if RemainingLife < 1 then begin
         IsHandled := false;
         OnCalcSLAmountOnRemainingLifeExpired(FA, FADeprBook,BookValue,var Result, var IsHandled);
         if not IsHandled then
            exit(-BookValue)
         else
            exit(Result);
      end;
That's need because if Ending Book Value filled on FA Depreciation Book we need exit with -(BookValue-FADeprBook."Ending Book Value")

Thank you!

**Comment by Stepanenko-Vadim** [comment]
In the future please make 1 issue per 1 event/global request, don't mix different requests and different objects in one issue.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
