### ISSUE TITLE
[Enum Request] - Item Statistics Buffer -"Source Type Filter" 

### ISSUE THREAD

**Issue by stryzhak** [microsoft/ALAppExtensions#15095]
Hi, 

Could you please transform "Source Type Filter" into enum ?

![image](https://user-images.githubusercontent.com/29860849/140485998-94f6c6c1-2c10-4d67-9f31-cb5f572afd4f.png)

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
