### ISSUE TITLE
[Event Request] Table 5940 - onValidate "Serial No."

### ISSUE THREAD

**Issue by amploba** [microsoft/ALAppExtensions#15090]
Hello

We need to add a new Event to skip the validation of the "Serial No." field

        field(2; "Serial No."; Code[50])
        {
            Caption = 'Serial No.';

            trigger OnValidate()
            var
                isHandled: Boolean;
            begin
                isHandled := false;
                OnBeforeValidateNoSeries(Rec, xRec, isHandled);
                if not isHandled then begin

With the event

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateNoSeries(var ServiceItem: Record "Service Item"; var xServiceItem: Record "Service Item"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
