### ISSUE TITLE
[ Function Expose ] Pages 7000001 & 7000002

### ISSUE THREAD

**Issue by frivadulla** [Microsoft/ALAppExtensions#151]
It would be nice to have the method UpdateStatistics exposed. I need to override the OnAfterGetRecord trigger to apply some style at some fields in the page, so if i can recreate your function "AfterGetCurrRecord" or also that function could be exposed, that would be wonderful.

Thanks in advice.

**Comment by JesperSchulz** [comment]
I will expose all public functions in those pages :-)
