### ISSUE TITLE
Codeunit 6520 new event on procedure SetRecordID

### ISSUE THREAD

**Issue by ASLANSABINEFR** [microsoft/ALAppExtensions#15116]
Hi,

We need a new event on Codeunit 6520 procedure SetRecordID :

```
...
          // > New event
            IsHandled := false;
            OnBeforeSetRecordID(TrackingEntry, IsHandled);
            If not IsHandled then
            // < New event

....

 [IntegrationEvent(false, false)]
    local procedure OnBeforeSetRecordID(var TrackingEntry: Record "Item Tracing Buffer"; var IsHandled: Boolean);
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
