### ISSUE TITLE
Enum Request Table 7603 "Customaized Calendar Entry" field 1 "Source Type"

### ISSUE THREAD

**Issue by arnasif** [microsoft/ALAppExtensions#1511]
Hi Team,
Please implement field 1 "Source Type" in table 7603 "Customaized Calendar Entry" as enum.
Best regards,
Arna Sif

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
