### ISSUE TITLE
Codeunit 22 new event on procedure InsertOHValueEntry

### ISSUE THREAD

**Issue by ASLANSABINEFR** [microsoft/ALAppExtensions#15121]
Hi,

We need a new event on Codeunit 22 procedure InsertOHValueEntry :

```

     ```
 ValueEntry."Variance Type" := ValueEntry."Variance Type"::Purchase;

        // > New event
        OnSetECDValueInsertVarValueEntryPostItemJnl(ValueEntry);
        // < New event
        if GLSetup."Additional Reporting Currency" <> '' then begin
            if Round(VarianceAmount, GLSetup."Amount Rounding Precision") =
               Round(-GlobalValueEntry."Cost Amount (Actual)", GLSetup."Amount Rounding Precision")
            then
                ValueEntry."Cost Amount (Actual) (ACY)" := -GlobalValueEntry."Cost Amount (Actual) (ACY)"
            else
                ValueEntry."Cost Amount (Actual) (ACY)" :=
                  Round(VarianceAmountACY, Currency."Amount Rounding Precision");

...

    [IntegrationEvent(false, false)]
    local procedure OnSetECDValueInsertVarValueEntryPostItemJnl(var ValueEntry: record "Value Entry");
    begin
    end;
```
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
