### ISSUE TITLE
Codeunit 23 new event on procedure GetLocation

### ISSUE THREAD

**Issue by ASLANSABINEFR** [microsoft/ALAppExtensions#15125]
Hi,

We need a new event on Codeunit 23 procedure GetLocation :

```
....
   if LocationCode = '' then
            Clear(Location)
        else
            if Location.Code <> LocationCode then
                Location.Get(LocationCode);
        // > New event
        OnAfterGetLocationCode(Location, ItemJnlLine);
        // < New event
...
[IntegrationEvent(false, false)]
    local procedure OnAfterGetLocationCode(Var Location: Record location; Var ItemJnlLine: Record "Item Journal Line")
    begin

    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
