### ISSUE TITLE
Enum Request Table 7604 "Where Used Base Calendar" field 1 "Source Type"

### ISSUE THREAD

**Issue by arnasif** [microsoft/ALAppExtensions#1512]
Hi Team,
Please implement field 1 "Source Type" in table 7604 "Where Used Base Calendar" as enum.
Best regards,
Arna Sif

**Comment by SKeiler** [comment]
Hello,

we also would like to need a ENUM-transformation of the Source Type of the whole calendar functionality. We needs to add a calendar to items and stockkeeping unit.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
