### ISSUE TITLE
API V2 Items doesn`t apply API Template if baseUnitOfMeasureCode is set

### ISSUE THREAD

**Issue by pripravka** [microsoft/ALAppExtensions#15135]
Hi there!
In On-Prem BC v18 (tryed 18.3 and 18.6) problem occured when use standard API V2 Items. 
If do an post request trought the API and field baseUnitOfMeasureCode are setting - API templates doesn`t applies. Tryed with Cronos Demo DB and my own DB. 
In BC v17 all works fine.
How to  reproduce:
Send Post request api/v2.0/companies(companyID)/items
```
{
    "displayName": "testtest",
    "baseUnitOfMeasureCode": "KG"
}
```
If use "baseUnitOfMeasureId" templates are applied. But we can`t use BC IDs within third party sysytems which do exchange with BC.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
