### ISSUE TITLE
[Event Request] codeunit 99000854 "Inventory Profile Offsetting" - OnPlanItemOnBeforeSetPlanningStartDate

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#15139]
Hi,
we would like to change the `PlanningStartDate` for some SKUs dynamic via  code.
Would it be possible that you would add a event to change the `PlanningStartDate` within the `TempSKU` loop?

```al
local procedure PlanItem(var DemandInvtProfile: Record "Inventory Profile"; var SupplyInvtProfile: Record "Inventory Profile"; PlanningStartDate: Date; ToDate: Date; RespectPlanningParm: Boolean)
var
    ..
begin
    ...

    //+NEW
    OriginalPlanningStartDate := PlanningStartDate; 
    //-NEW

    TempSKU.SetCurrentKey("Item No.", "Transfer-Level Code");
    OnPlanItemOnBeforeTempSKUFind(TempSKU);
    if TempSKU.Find('-') then
        repeat
            IsReorderPointPlanning := IsSKUSetUpForReorderPointPlanning(TempSKU);
            OnPlanItemAfterCalcIsReorderPointPlanning(TempSKU, IsReorderPointPlanning, ReqLine, PlanningTransparency, PlanningResilicency, CurrTemplateName, CurrWorksheetName);
            //+NEW
            IsHandled := false;
            OnPlanItemOnBeforeSetPlanningStartDate(TempSKU, OriginalPlanningStartDate, PlanningStartDate, IsHandled); 
            if not IsHandled then
                PlanningStartDate := OriginalPlanningStartDate
            //-NEW

           
end;
```
```al
[IntegrationEvent(false, false)]
local procedure OnPlanItemOnBeforeSetPlanningStartDate(var TempSKU: Record "Stockkeeping Unit" temporary; OriginalPlanningStartDate: Date; var PlanningStartDate: Date; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by DanielGoehler** [comment]
Hi @JesperSchulz, we don't find this new event (Insider Preview 20.0.35117.0 W1). When will this be rolled out?

**Comment by JesperSchulz** [comment]
I would appear that this request was addressed by adding PlanningStartDate as a parameter to OnPlanItemAfterCalcIsReorderPointPlanning, rather than introducing a new event. Will that work for you?

**Comment by pri-kise** [comment]
@JesperSchulz we want to change the PlanningStartDate only for specific SKUs. That was the reason for our event request and the small refactoring where we temporary save the `OriginalPlanningStartDate`.
```al
          if not IsHandled then
                PlanningStartDate := OriginalPlanningStartDate
```

**Comment by JesperSchulz** [comment]
ok, just needed to make sure before I carry this forward to the owning team. I will forward your request right away.

**Comment by Stepanenko-Vadim** [comment]
@pri-kise can't you just do that in your own code in the event subscriber? Store the original date on a new loop-start and 'restore'/don't change it via subscriber for **OnPlanItemAfterCalcIsReorderPointPlanning** on each iteration when you need to do it. You can use **OnPlanItemOnBeforeTempSKUFind**, to determine if it's the start of a new loop, set a flag that next iteration of **OnPlanItemAfterCalcIsReorderPointPlanning** is first one and you need to store the date as original. (I guess it would be easier if PlanningStartDate was available as param on **OnPlanItemOnBeforeTempSKUFind**, if you request we add it - we will)

**Comment by pri-kise** [comment]
@Stepanenko-Vadim right now, it would be very complicated. Because of that I originally requested the event as above.
Personally I would prefer it, if the BaseApp code would be changed as request, but I can live with a solution where the `PlanningStartDate` would be made available in the event **OnPlanItemOnBeforeTempSKUFind**, then we could store the Original PlanningStartDate in a SingleInstance Codeunit.

I can understand that the event isn't added as requested above, but I would at least expect an answer to the issue, when an event is implemented in a differnt way. (I had this for other issues, too) I'm open for discussion, and mabye there are sometimes better solutions, than I originally had in mind, but please don't close issues in the future that aren't implemented as requested.

**Comment by Stepanenko-Vadim** [comment]
We generally do not add variables/code to baseapp just for events, unless it's absolutely necessary, that's why we prefer this solution.

I will add **PlanningStartDate** to **OnPlanItemOnBeforeTempSKUFind**, you don't have to open a new request for it.
