### ISSUE TITLE
[Event Request] Codeunit 11000002 CBG Journal Telebank Interface - OnBeforeInsertPaymentHistory

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#15141]
We would like to request a new event: OnBeforeInsertPaymentHistory.
With the event we would like to do additional checks on the CBG Statement before the user can import the payment history.

    procedure InsertPaymentHistory(CBGStatement: Record "CBG Statement")
    var
        PaymHistOverview: Page "Payment History List";
        PaymHist: Record "Payment History";
        PaymentHistLine: Record "Payment History Line";
        CBGStatementLine: Record "CBG Statement Line";
        LineAmount: Decimal;
        IsConfirmHandled: Boolean;
        UseAdjustedAmount: Boolean;
    begin
       >>OnBeforeInsertPaymentHistory(CBGStatement);<<
        with CBGStatement do begin
            TestField(Type, Type::"Bank/Giro");
            TestField("Account Type", "Account Type"::"Bank Account");

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertPaymentHistory(CBGStatement: Record "CBG Statement")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
