### ISSUE TITLE
Add permissions to codeunit 5055 "CustVendBank-Update"

### ISSUE THREAD

**Issue by WJMSmit** [microsoft/ALAppExtensions#15144]
In order to make it possible for users with indirect permissions to update the concerning tables, we need the following:
Permissions = TableData "Bank Account" = rm,
                        TableData Customer = rm,
                        TableData Employee = rm,
                        TableData Vendor = rm;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
