### ISSUE TITLE
"Item Availability by Lot No." page error with long LocationFilter

### ISSUE THREAD

**Issue by LucaDonatoSEDP** [microsoft/ALAppExtensions#15146]
Hi,

in BC19 I set in Item card page a long locationfilter "<>BTP-SCARTI&<>EUROFINS&<>GE-SCARTI&<>STERIL_RIC&<>STU_AMB&<>TUV" , when I run the page "Item Availability by Lot No." I get this error:
![image](https://user-images.githubusercontent.com/59683494/140889096-0f67cc4e-050f-4c1b-b206-6d5b5764bf99.png)

I assume the problem is in this part of the code

                field(LocationFilter; LocationFilter)
                {
                    ApplicationArea = Assembly;
                    Caption = 'Location Filter';
                    ToolTip = 'Specifies the location that availability is shown for.';
                    TableRelation = Location;

                    trigger OnValidate()
                    var
                        Location: Record Location;
                    begin
                        if LocationFilter <> '' then
                            Location.Get(LocationFilter);
                        RefreshPage();
                    end;
                }

In my opinion using instead of location.get the location.setfilter should solve it.

**Comment by dnpb** [comment]
This seems not about length, but about the fact that the page is designed to filter only to one location. Even if you just entered a filter of `LOCA|LOCB` it would still error... unless you happen to have a Location whose Code is literally that, but that wouldn't be the result you wanted either.

**Comment by qasimikram** [comment]
As explained above, supporting multiple location on the page would be a feature request and would require some changes. 

If this is something that needs to be added to the product, please propose it on idea site [here](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central). Closing this issue.
