### ISSUE TITLE
Codeunit 103 "Cust. Entry-Edit" - Always error on VALIDATE "Recipient Bank Account"

### ISSUE THREAD

**Issue by FabioC34** [microsoft/ALAppExtensions#15143]
Hi, in Italian Localization, if one field is modified and CU103 Triggered, if the entry is "Open" and the field "Bank Receipt Issued" is set to TRUE, the operation always gives an error even if "Recipient Bank Account" is not modified.
This occurs because in the codeunit the code:
`CustLedgEntry.Validate("Recipient Bank Account", "Recipient Bank Account");`
is always triggered, without checking if CustLedgEntry"Recipient Bank Account" is <> to Rec."Recipient Bank Account"

The error occurs because in T21, OnValidate "Recipient Bank Account" there is the following code:
`TestField("Bank Receipt Issued", false);`

Could you please check and fix the issue?
Thank you
Fabio

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
