### ISSUE TITLE
[Functionality Request] Conditional Custom Report Layout

### ISSUE THREAD

**Issue by SteveyN** [microsoft/ALAppExtensions#1515]
Unsure where best to put this.

Our customer has a requirement to use a different Word Layout for the Purchase Order if a condition is met; i.e the Purchase Order status is Pending Approval, use an Unapproved custom layout, otherwise use the standard layout.

We cannot achieve this at the moment, since Word Layouts cannot contain conditional fields or formatting. To achieve this we would have to make a carbon copy of R1322 "Standard Purchase - Order" in AL and manually construct an RDLC layout based on the built in word layout. RDLC allows conditional formatting, but we would have to constantly update the report copy to match Microsoft updates.

In Table 77 Report Selections, there is a function PrintDocumentsWithCheckGUIYesNoCommon, in which functionality could be added to replace the current Report Layout with a related Custom one based on a Condition.

Then we could call this event and say if Status = Pending Approval and the report selection is R1322 Standard PO, use our custom Unapproved layout for this report.
![image](https://user-images.githubusercontent.com/10519634/54194566-6fae3280-44b4-11e9-9970-96f512ccd56b.png)

In addition, we want to create the Custom Report Layout record when the app is installed, but to achieve this we have to use a dummy report, which changes the ID's inside our custom word layout to not match with Report 1322. Can anything be done with this, or do we simply need to inform the customer to manually setup?

**Comment by StanPesotskiy** [comment]
For the new features please submit a product suggestion on https://aka.ms/bcideas
