### ISSUE TITLE
Service Line Amount Including VAT calculation

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#15155]
Hi,

We find some mistakes in the calculation of field Amount Including VAT in the service line,
It should be like in the sales line.
In the Service Line table in function UpdateVATAmounts
In case when "Prices Including VAT" = false and "VAT Calculation Type"::"Normal VAT","VAT Calculation Type"::"Reverse Charge VAT" we need to remove validate(Amount) and code like in the same case in the Sales Line table.
![image](https://user-images.githubusercontent.com/43178739/140921913-25431f77-2035-4e23-a59c-8ea0053a2306.png)

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 40751.
