### ISSUE TITLE
Sales Price Synchronisation between Business Central and Sales

### ISSUE THREAD

**Issue by Gurnek848** [microsoft/ALAppExtensions#15159]
Business Central Version 19

We have enabled the following two features through Feature Management
New Sales Price experience
Multiple Units of Measure synchronisation with Dynamics 365.

We have created a Sales Price list for one product with multiple units of measure

![image](https://user-images.githubusercontent.com/75612353/141088189-f6ce0caa-ab20-4dd8-a1ad-545f42bcc383.png)

however we are getting the following error when trying synchronise a Sales Price list between BC and Sales

![image](https://user-images.githubusercontent.com/75612353/141088391-75d36fc2-77da-483a-b40c-76a6dd75b1dd.png)

We have debugged the process and teh error seems to be happening in the following procedure

![image](https://user-images.githubusercontent.com/75612353/141088542-1148fdc4-ea3f-4c52-84a5-4092662c25d9.png)

We also carried out a test where we left one unit of measure blank for the product

![image](https://user-images.githubusercontent.com/75612353/141088823-ceb81c57-c192-44ad-a48e-a5b00c98379d.png)

This time when running teh Job to synchronise we got teh following error

![image](https://user-images.githubusercontent.com/75612353/141088976-9c5f6c75-61b9-4f7f-a299-6e46aea16242.png)

Please could you advise how we can resolve this synchronisation problem.  

Regards
Gurnek.

**Comment by StanPesotskiy** [comment]
The fix seems to be in with the build 20.0.32936. Reference id 417979. If you need this fix in the older versions, you can ask for the downport via the support.

In the new code Item is always read even if UoMCode was blank:
```
local procedure FindCRMUoMIdForSalesPrice(...)
    begin
        case AssetType of
            AssetType::Item:
                begin
                    Item.Get(AssetNo);
                    if UoMCode = '' then
                        UoMCode := Item."Base Unit of Measure";
                end;
            AssetType::Resource:
                begin
                    Resource.Get(AssetNo);
                    if UoMCode = '' then
                        UoMCode := Resource."Base Unit of Measure";
                end;
            else
                if UoMCode = '' then
                    exit;
        end;
```
