### ISSUE TITLE
[EventRequest] table 12170 "Payment Lines"  - Function CreatePaymentLinesSales

### ISSUE THREAD

**Issue by Athon-dev** [microsoft/ALAppExtensions#15157]
Can we please get the following event?

STANDARD CODE:

`                until OldDate = PaymentLines."Due Date";

                PaymentLines."Pmt. Discount Date" := CalcDate(PaymentLinesTerms."Discount Date Calculation", SalesHeader."Document Date");

                if PaymentLines."Pmt. Discount Date" < SalesHeader."Document Date" then
                    PaymentLines."Pmt. Discount Date" := SalesHeader."Document Date";
                PaymentLines.Insert();
            until PaymentLinesTerms.Next() = 0;`
            
            

NEW CODE

`                  until OldDate = PaymentLines."Due Date";

                PaymentLines."Pmt. Discount Date" := CalcDate(PaymentLinesTerms."Discount Date Calculation", SalesHeader."Document Date");

                if PaymentLines."Pmt. Discount Date" < SalesHeader."Document Date" then
                    PaymentLines."Pmt. Discount Date" := SalesHeader."Document Date";
                OnBeforeInserPaymentLines(PaymentLines, SalesHeader);
                PaymentLines.Insert();
            until PaymentLinesTerms.Next() = 0;`
            
            
NEW EVENT
`    
    [IntegrationEvent(false, false)]     
    local procedure OnBeforeInserPaymentLines(var PaymentLines: Record "Payment Lines"; SalesHeader: Record "Sales Header")
    begin
    end;`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
