### ISSUE TITLE
Make functions SetAllEntries and SetApplId global from page 11310 "General Ledger Entries Apply"

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#15163]
Hello,

We would need to have the functions SetAllEntries and SetApplId global from page 11310 "General Ledger Entries Apply".
We have a development where we use these two functions.

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
