### ISSUE TITLE
[BUG] Sales Comment Lines are not deleted on Sales-Quote to Order

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#15161]
In NAV2009SP1 the sales comment lines of a quote were deleted after transfer to the sales order. In newer NAV/BC versions this is not happening.

Steps to reproduce in BC19:

- Create sales quote
- Add comment lines
- Create sales order from quote
- Comment lines are copied
- Quote is deleted
- Sales comment lines from the sales quote remain in the database.

Suggested fix:

```al
codeunit 85 "Sales-Quote to Order"
...
trigger OnRun()
var
...
IsHandled := false;
OnBeforeDeleteSalesQuote(Rec, SalesOrderHeader, IsHandled, SalesQuoteLine);
if not IsHandled then begin
// --- new
    SalesCommentLine.DeleteComments(Rec."Document Type", Rec."No.");
// +++ new
    ApprovalsMgmt.DeleteApprovalEntries(RecordId);
    DeleteLinks;
    Delete;
    SalesQuoteLine.DeleteAll();
end;
...
```

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
