### ISSUE TITLE
There is no overloaded function that allows to save an image in a specified format

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/ALAppExtensions#15162]
Hello,

The module Image does not allow to save an image in a new format .

https://github.com/microsoft/ALAppExtensions/blob/60b3c46df078f7f2414023c6ce75c900fc9a48c7/Modules/System/Image/src/Image.Codeunit.al#L104

What is the replacement for DotNet_Image.Save(OutStream, Codeunit "DotNet_ImageFormat") ?

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
It looks like none has been implemented. Probably no other developer had the need for this capability! Luckily, we've open sourced the module, which allows you to add exactly the overloads that you need. Could you create a PR? We'll process it swiftly!

**Comment by nicolassaleron** [comment]
Contributing to the System App: that's new for me  :)

I see many ways to achieve the same result. Have you any preference or is it up-to-me?

* I could propose an overload with ```Save(OutStream: OutStream, Format: Enum "Image Format")``` where the current image is just re-encoded to the specified format into the specified stream
* It could be a ```SetFormat(NewFormat: Enum "Image Format")``` where the format of the internal stream of Image is changed. Then the existing ```Save(OutStream: OutStream)``` would remain the same.

**Comment by JesperSchulz** [comment]
Happy to hear that you're considering to create a PR :-D

Generally, that would be up to you! As you are the developer, you are free to choose the option which best suits your needs. Both options seem viable to me!

Looking forward to receiving your pull request!

If you get stuck or need help, please don't hesitate to reach out! We're here to help :-)

**Comment by JesperSchulz** [comment]
Progress in PR instead 🥳
