### ISSUE TITLE
Inconsistent read of field in custom page

### ISSUE THREAD

**Issue by LucaDonatoSEDP** [microsoft/ALAppExtensions#15164]
Hi,

in a custom sales line page list, when I try to modify the field 'Planned Delivery Date' raise this error:

Validation Results
Inconsistent read of field(s): 'Planned Delivery Date', on table 'Sales Line', 
identification values: 'Document Type='Order',Document No.='20ORC2666',Line No.='10000''

"Sales Line-Reserve"(CodeUnit 99000832).TestSalesLineModification line 4 - Base Application by Microsoft
"Sales Line-Reserve"(CodeUnit 99000832).VerifyChange line 25 - Base Application by Microsoft
"Sales Line"(Table 37).VerifyChangeForSalesLineReserve line 9 - Base Application by Microsoft
"Sales Line"(Table 37).OnModify(Trigger) line 17 - Base Application by Microsoft

This issue did not occur until version 18.5 while it appeared after updating to version 19.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels and provide detailed repro steps:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
