### ISSUE TITLE
Subscriber Required to by pass validation incorporated in codeunit 1320 "Lines Instruction Mgt."

### ISSUE THREAD

**Issue by umang11** [microsoft/ALAppExtensions#15165]
Hi team, 

as per my customer requirement i need to bypass the validation from codeunit 1320 "Lines Instruction Mgt." function name
procedure SalesCheckAllLinesHaveQuantityAssigned(SalesHeader: Record "Sales Header")
    var
        SalesLine: Record "Sales Line";
    begin
        SalesLine.SetRange("Document No.", SalesHeader."No.");
        SalesLine.SetRange("Document Type", SalesHeader."Document Type");
        SalesLine.SetFilter(Type, '<>%1', SalesLine.Type::" ");
        SalesLine.SetFilter("No.", '<>%1', '');
        SalesLine.SetRange(Quantity, 0);
        OnAfterSetSalesLineFilters(SalesLine, SalesHeader);
**_OnBeforeFireError(Ishandled)_**
**_if Ishandled then
Exit;_**
        if not SalesLine.IsEmpty() then
            if (SalesHeader."Document Type" = SalesHeader."Document Type"::"Credit Memo") then
                if Confirm(LinesMissingQuantityConfirmQst, false) then
                    exit
                else
                    Error(LinesMissingQuantityErr)
            else
                Error(LinesMissingQuantityErr);

    end;

Subscriber signature

[IntegrationEvent(false, false)]
    local procedure OnBeforeFireError(Var Ishandled : Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
