### ISSUE TITLE
[Protected var Request] - Page 7352 PutawayWorksheet 

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#15178]
We would like to have the following variables as protected var, so we can use them in page extension.

Object: PutawayWorksheet.Page.al
Global Variables:

```
var
  CurrentWkshTemplateName: Code[10];
  CurrentWkshName: Code[10];
  CurrentLocationCode: Code[10];
```

Thanks in advance,
Christian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
