### ISSUE TITLE
New parameter in OnAfterSetGLIntegration

### ISSUE THREAD

**Issue by vianju** [microsoft/ALAppExtensions#15172]
Hi,

To suscribe to OnAfterSetGLIntegration in  Codeunit 5631 "FA Jnl.-Check Line", we need as paremeter the variable DeprBook, otherwise we can not use extended fields "G/L - Integration XXXX" in Depreciation Book to modify GLIntegration var.

Regards.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
