### ISSUE TITLE
[Deprecate Procedure] codeunit 5807 "Item Charge Assgnt. (Sales)" -  SuggestAssignment2 -> Use AssignItemCharges instead.

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#15189]
Hi could you please add the Obsolete Tag to the following procedure that results in error in non english environments?
You have already added an alternative, but the current procedure isn't obsoleted.
Additionally you could add something like
```al
case Selection of 
    Selection::Equally: 
    SelectionText := AssignEquallyMenuText();
    Selection::"By Amount": 
    SelectionText := AssignByAmountMenuText();

...

end;

    AssignItemCharges(SalesLine, TotalQtyToAssign, TotalAmtToAssign, SelectionText), //NEW
```

to the procedure `SuggestAssignment2`.

```al
procedure SuggestAssignment2(SalesLine: Record "Sales Line"; TotalQtyToAssign: Decimal; TotalAmtToAssign: Decimal; Selection: Option Equally,"By Amount","By Weight","By Volume")
begin
    // this function will be deprecated. Please use AssignItemCharges instead
    AssignItemCharges(SalesLine, TotalQtyToAssign, TotalAmtToAssign, Format(Selection))
end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
