### ISSUE TITLE
[Event Request] Table 1670 - Option Lookup Buffer - OnCreateNewOnBeforeInsert

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#15182]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnCreateNewOnBeforeInsert` to be added to Table 1670 Option Lookup Buffer with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnCreateNewOnBeforeInsert(var OptionLookupBuffer: Record "Option Lookup Buffer"; OptionID: Integer; OptionText: Text[30]; LookupType: Enum "Option Lookup Type")
    begin
    end;
```
with `OptionLookupBuffer` as `var` parameter.

which would be called as follows from `CreateNew`:
```al
    local procedure CreateNew(OptionID: Integer; OptionText: Text[30]; LookupType: Enum "Option Lookup Type")
    begin
        Init();
        ID := OptionID;
        "Option Caption" := OptionText;
        "Lookup Type" := LookupType;
        OnCreateNewOnBeforeInsert(Rec, OptionID, OptionText, LookupType); // << NEW EVENT
        Insert();
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
