### ISSUE TITLE
[Access Request] Page 5417 "Item Avail. by UOM Lines" - Item protected

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#15187]
Hi Al team,

I would like to access the following variable from an extension object:

`protected var 
  Item: Record Item;`

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
