### ISSUE TITLE
Make the variable DynamicCaption protected in page 11310 "General Ledger Entries Apply"

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#15197]
Hello,

We will need to have the variable DynamicCaption protected in page 11310 "General Ledger Entries Apply".
We have a function in the page extension for page 11310 "General Ledger Entries Apply" and there we change the DynamicCaption variable. We would need to have this variable protected, so we could access it through the page extension and then, this value is used when executing the code CurrPage.Caption := DynamicCaption; from OnOpenPage trigger.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
