### ISSUE TITLE
[Event Change Request] - WhseWorksheetLine.Table - OnAfterGetItem

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#15194]
We would like to request the following event change:
Object: WhseWorksheetLine.Table
ToDo: add var ItemDescription parameter
Where is the event placed:
```al
procedure GetItem(ItemNo: Code[20]; var ItemDescription: Text[100])
begin
    if ItemNo = '' then
        ItemDescription := ''
    else
        if ItemNo <> Item."No." then begin
            ItemDescription := '';
            if Item.Get(ItemNo) then
                ItemDescription := Item.Description;
        end else
            ItemDescription := Item.Description;

    OnAfterGetItem(Rec, Item, ItemDescription);
end;
```
Event Code:
```al
[IntegrationEvent(false, false)]
local procedure OnAfterGetItem(var WhseWorksheetLine: Record "Whse. Worksheet Line"; var Item: Record Item; var ItemDescription: Text[100])
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
