### ISSUE TITLE
Report "Depreciation Book" (12119) - Company Name in header

### ISSUE THREAD

**Issue by rdemasi987** [microsoft/ALAppExtensions#15198]
Hello,
I'm frequently asked to add the company name in the header of the report in question.
E.g.
![image](https://user-images.githubusercontent.com/75783517/141483970-44b03444-ed48-41e6-a8a8-958574fe1b4f.png)

I wonder if it's possible to add it in the standard report.

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
