### ISSUE TITLE
[Event Change Request] table 77 "Report Selections"

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#15199]
Begining of the function CanSaveReportAsPDF
`OnBeforeCanSaveReportAsPDF(ReportId, CanSaveAsPDF, IsHandled);
if IsHandled then
   exit(CanSaveAsPDF);
`

`    [IntegrationEvent(false, false)]
    local procedure OnBeforeCanSaveReportAsPDF(ReportId: Integer; var CanSaveAsPDF: boolean; var IsHandled: Boolean)
`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
