### ISSUE TITLE
AL0603 -  Implicit conversion from Enum to Integer

### ISSUE THREAD

**Issue by andreilungu** [microsoft/ALAppExtensions#15205]
**1. Describe the bug**
When use subpage part in a page and have Enum in the Subpage Link we receive error:

An implicit conversion is being performed from a value of type 'Integer' to a value of type 'Enum "Default Dimension Parent Type"'. This conversion can lead to unexpected runtime issues. This warning will become an error in a future release.AL(AL0603)

 part(defaultDimensions; "APIV1 - Default Dimensions")
                {
                    Caption = 'Default Dimensions';
                    EntityName = 'defaultDimension';
                    EntitySetName = 'defaultDimensions';
                    SubPageLink = ParentId = Field(SystemId), "Parent Type" = const(1);
                }

"Parent Type" = Enum "Default Dimension Parent Type"

How can we solve this issue considering we can not use "Parent Type".AsInteger() or use the Enum Value instead of const(1).

**Comment by AlexanderYakunin** [comment]
You can use #pragma statements for such cases

**Comment by andreilungu** [comment]
I used #pragma first but then I thought if it would be better to leave the warning and get it fix without #pragma when you fix it in the base app.

The question is if you have a timeline for fixing this? If it will not be in the next version, then I will use #pragma in our code..

**Comment by TriangleSPV** [comment]
We have a similar behaviour in the CalcFormula of some FlowFields.

Specefically we relate the sales/purchase "Document Type" (Enum) with the "Source Subtype" of the Warehouse Activity documents (Options). The option field must be changed to Enum, can you change it in a future release?

**Comment by AlexanderYakunin** [comment]
We have no plans to convert Source Type to Enum. This is field is Integer in many places (and this is correct design) and Option on some other places (and this is legacy issue we cannot fix in easy way). We will keep this as is until we have less breaking option to do this kind of changes.

**Comment by TriangleSPV** [comment]
Hi Alexander.
You didn't get it right. I mean to the field "Source Subtype", which is an option to relate to the different document types.
As you said, the "Source Type" is related to the table number and it is correct.

**Comment by AlexanderYakunin** [comment]
Of course, my comment was about Source Subtype. Corrected above.
