### ISSUE TITLE
[Request for External] report 5198 "Add Contacts" procedure + variables

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#15208]
hey,

please make following accessable, it is needed for a report extension.

procedure:
```
local procedure InsertContact(var CheckedCont: Record Contact)
```

variables:
```
TempCont: Record Contact temporary;
TempCont2: Record Contact temporary;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
