### ISSUE TITLE
event + parameter request - table 61 "Electronic Document Format" - GetAttachmentFileName() - OnBeforeGetAttachmentFileName(RecordVariant, ...)

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15200]
Please add this event so that we can customise filenames used when downloading PDFs or creating zips of multiple PDFs.

    procedure GetAttachmentFileName(DocumentNo: Code[20]; DocumentType: Text; Extension: Code[3]) Result: Text[250]
    var
        FileMgt: Codeunit "File Management";
        IsHandled: Boolean;
    begin
        OnBeforeGetAttachmentFileName(DocumentNo, DocumentType, Extension, IsHandled, Result);

        if IsHandled then
            exit;

        exit(
          CopyStr(
            StrSubstNo('%1 - %2 %3.%4', FileMgt.StripNotsupportChrInFileName(CompanyName), DocumentType, DocumentNo, Extension), 1, 250));
    end;

published as

    [IntegrationEvent(false, false)]
    local procedure GetAttachmentFileName(
        DocumentNo: Code[20]; DocumentType: Text; Extension: Code[3];
        var IsHandled: Boolean; var Result: Text[250])

Thanks!

**Comment by dnpb** [comment]
Actually, this will be of limited usefulness without knowing the record being printed. Can this function be updated to take a `RecordVariant: Variant`, and `table 77 "Report Selections"` be updated to pass that from its callers, so that we can then e.g. include the customer's name in the case of sales invoices, etc.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
