### ISSUE TITLE
[Event Request] Codeunit 5986 "Serv-Amounts Mgt.", Function UpdInvPostingBuffer: OnUpdateInvPostBuffer

### ISSUE THREAD

**Issue by SteinleMossWahlers** [microsoft/ALAppExtensions#15203]
Hello, would it be possible to get an event OnUpdateInvPostBuffer(InvPostingBuffer[1], InvPostingBuffer[2]) in Codeunit 5986, Function UpdInvPostingBuffer:

    local procedure UpdInvPostingBuffer(var InvPostingBuffer: array[2] of Record "Invoice Post. Buffer"; ServiceLine: Record "Service Line")
    begin
        InvPostingBuffer[1]."Dimension Set ID" := ServiceLine."Dimension Set ID";
        if InvPostingBuffer[1].Type = InvPostingBuffer[1].Type::"Fixed Asset" then begin
            FALineNo := FALineNo + 1;
            InvPostingBuffer[1]."Fixed Asset Line No." := FALineNo;
        end;

        OnBeforeUpdateInvPostBuffer(InvPostingBuffer[1]);

        InvPostingBuffer[2] := InvPostingBuffer[1];
        if InvPostingBuffer[2].Find then begin
            InvPostingBuffer[2].Amount := InvPostingBuffer[2].Amount + InvPostingBuffer[1].Amount;
            InvPostingBuffer[2]."VAT Amount" :=
              InvPostingBuffer[2]."VAT Amount" + InvPostingBuffer[1]."VAT Amount";
            InvPostingBuffer[2]."VAT Base Amount" :=
              InvPostingBuffer[2]."VAT Base Amount" + InvPostingBuffer[1]."VAT Base Amount";
            InvPostingBuffer[2]."Amount (ACY)" :=
              InvPostingBuffer[2]."Amount (ACY)" + InvPostingBuffer[1]."Amount (ACY)";
            InvPostingBuffer[2]."VAT Amount (ACY)" :=
              InvPostingBuffer[2]."VAT Amount (ACY)" + InvPostingBuffer[1]."VAT Amount (ACY)";
            InvPostingBuffer[2]."VAT Difference" :=
              InvPostingBuffer[2]."VAT Difference" + InvPostingBuffer[1]."VAT Difference";
            InvPostingBuffer[2]."VAT Base Amount (ACY)" :=
              InvPostingBuffer[2]."VAT Base Amount (ACY)" +
              InvPostingBuffer[1]."VAT Base Amount (ACY)";
            InvPostingBuffer[2].Quantity :=
              InvPostingBuffer[2].Quantity + InvPostingBuffer[1].Quantity;
            **OnUpdateInvPostBuffer(InvPostingBuffer[1], InvPostingBuffer[2]);**
            if not InvPostingBuffer[1]."System-Created Entry" then
                InvPostingBuffer[2]."System-Created Entry" := false;
            InvPostingBuffer[2].Modify();
        end else
            InvPostingBuffer[1].Insert();

        OnAfterUpdateInvPostBuffer(InvPostingBuffer[1]);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnUpdateInvPostBuffer(var InvoicePostBuffer1: Record "Invoice Post. Buffer"; var InvoicePostBuffer2: Record "Invoice Post. Buffer")
    begin
    end;

**Comment by AlexanderYakunin** [comment]
We already have different design in latest versions, please check this first
