### ISSUE TITLE
[Event Request] codeunit 5056 - CustCont-Update - InsertNewContactPerson

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#15202]
Hi AL team,

can you please add the parameter "ContComp" to the event publisher OnInsertNewContactPersonOnBeforeValidateType?

    procedure InsertNewContactPerson(var Cust: Record Customer; LocalCall: Boolean)
        var
            ContComp: Record Contact;
            ContBusRel: Record "Contact Business Relation";
            Cont: Record Contact;
        begin
            if not LocalCall then begin
                RMSetup.Get();
                RMSetup.TestField("Bus. Rel. Code for Customers");
            end;
    
            ContBusRel.SetCurrentKey("Link to Table", "No.");
            ContBusRel.SetRange("Link to Table", ContBusRel."Link to Table"::Customer);
            ContBusRel.SetRange("No.", Cust."No.");
            if ContBusRel.FindFirst then
                if ContComp.Get(ContBusRel."Contact No.") then
                    with Cont do begin
                        Init;
                        "No." := '';
                        // NEW >>>>
                        //OnInsertNewContactPersonOnBeforeValidateType(Cont, Cust);
                        OnInsertNewContactPersonOnBeforeValidateType(Cont, Cust, ContComp);
                        // NEW <<<<
                        Validate(Type, Type::Person);
                        Insert(true);
                        "Company No." := ContComp."No.";
                        Validate(Name, Cust.Contact);
                        InheritCompanyToPersonData(ContComp);
                        UpdateBusinessRelation();
                        OnInsertNewContactPersonOnBeforeContactModify(Cont, Cust);
                        Modify(true);
                        Cust."Primary Contact No." := "No.";
                    end
        end;

      // NEW (additional parameter ContComp) >>>>
      [IntegrationEvent(false, false)]
      local procedure OnInsertNewContactPersonOnBeforeValidateType(var Contact: Record Contact; Customer: Record Customer; ContComp: Record Contact)
      begin
      end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
