### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnInsertVATOnBeforeCreateGLEntryForReverseChargeVATToPurchAcc

### ISSUE THREAD

**Issue by skully1991** [microsoft/ALAppExtensions#15212]
Can you declared the `VATPostingSetup` parameter in the event `OnInsertVATOnBeforeCreateGLEntryForReverseChargeVATToPurchAcc` with `var`?

```
[IntegrationEvent(false, false)]
local procedure OnInsertVATOnBeforeCreateGLEntryForReverseChargeVATToPurchAcc(var GenJournalLine: Record "Gen. Journal Line"; var VATPostingSetup: Record "VAT Posting Setup"; UnrealizedVAT: Boolean; VATAmount: Decimal; VATAmountAddCurr: Decimal; UseAmountAddCurr: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
