### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeInsertVATForGLEntry

### ISSUE THREAD

**Issue by skully1991** [microsoft/ALAppExtensions#15213]
We need to change the `G/L Entry`. Would it be possible to set the `IncludeSender` boolean in the integration event `OnBeforeInsertVATForGLEntry` on true?

```
[IntegrationEvent(true, false)]
local procedure OnBeforeInsertVATForGLEntry(var GenJnlLine: Record "Gen. Journal Line"; VATPostingSetup: Record "VAT Posting Setup"; GLEntryVATAmount: Decimal; SrcCurrGLEntryVATAmt: Decimal; UnrealizedVAT: Boolean; var IsHandled: Boolean; var VATEntry: Record "VAT Entry")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
