### ISSUE TITLE
[Event Request] Table 5600 "Fixed Asset"- OnBeforeGetNoSeriesCode

### ISSUE THREAD

**Issue by KuljitSinghParmar** [microsoft/ALAppExtensions#15219]
Hi Team,

In table 5600 "Fixed Asset" , we need to have Integration event in the "AssistEdit" procedure. Adding an event with handling in this procedure will work great for us.
![image](https://user-images.githubusercontent.com/61985025/142057166-e7719c5e-877d-4b32-88e5-bedf6f19114a.png)

procedure AssistEdit(OldFA: Record "Fixed Asset"): Boolean
    begin
        with FA do begin
            FA := Rec;
            FASetup.Get();
            OnBeforeGetNoSeriesCode(FASetup, FA, Rec, IsHandled);
            if IsHandled then
                exit(true);
            FASetup.TestField("Fixed Asset Nos.");
            if NoSeriesMgt.SelectSeries(FASetup."Fixed Asset Nos.", OldFA."No. Series", "No. Series") then begin
                NoSeriesMgt.SetSeries("No.");
                Rec := FA;
                exit(true);
            end;
        end;
    end;

[IntegrationEvent(false, false)]
local procedure OnBeforeGetNoSeriesCode( FASetup: Record "FA Setup";  var FA: Record "Fixed Asset"; var Rec :Record "Fixed Asset";
var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
