### ISSUE TITLE
[Event Request] Table Lifo Band - Function UpdateIncrementValue - New Event OnAfterUpdateIncrementValue (Italian Localization)

### ISSUE THREAD

**Issue by FabioC34** [microsoft/ALAppExtensions#15211]
Hello, we need the possibility to extend the function UpdateIncrementValue on Lifo Band Table (T12130) as follows:

```
[Scope('OnPrem')]
procedure UpdateIncrementValue()
begin
    "Increment Value" := "Residual Quantity" * "Year Average Cost";
//new-s
    OnAfterUpdateIncrementValue(Rec);
//new-e
end;

```
```
[IntegrationEvent(false, false)]
local procedure OnAfterUpdateIncrementValue(var LifoBand: Record "Lifo Band")
begin
end;

```
Thank you
Fabio

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
