### ISSUE TITLE
[Scope Change] tables 6660 "Return Receipt Header" & 167 Job - EmailRecords

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#15218]
As mentioned in previous requests like:
https://github.com/microsoft/ALAppExtensions/issues/10340

we would like to remove the scope from both procedures like it has already been done in  tables 112&114 in previous request.
Little side note: I don't know why [Scope('Cloud')] is set in T36 on same procedure.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
