### ISSUE TITLE
[Event Request] CU1012 "Job Jnl.-Post Line" - procedure CreateJobLedgEntry()

### ISSUE THREAD

**Issue by tguyonnet** [microsoft/ALAppExtensions#15229]
------- ADD PARAMETER : GLEntryNo ---------

OnCreateJobLedgerEntryOnAfterAssignLedgerEntryTypeAndNo(JobLedgEntry, JobJnlLine2, GLEntryNo);

[IntegrationEvent(false, false)]
local procedure OnCreateJobLedgerEntryOnAfterAssignLedgerEntryTypeAndNo(var JobLedgEntry: Record "Job Ledger Entry"; JobJournalLine: Record "Job Journal Line"; GLEntryNo: Integer)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
