### ISSUE TITLE
parameter request - table 36 "Sales Header" - ConfirmDeletion() - OnBeforeConfirmDeletion() - add var Handled pattern

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15235]
https://github.com/microsoft/ALAppExtensions/issues/8481 added this event, but there is no way to skip the question.

We have a subscriber to `PostSales-Delete` - `OnBeforeDeleteHeader()` that skips the creation of the posted document in some cases. However, we still get the confirmation question, even though it's wrong/misleading. And I see no nice way to skip it.

Therefore, please can you add the `Handled` pattern to this event emission, to let us skip it under the same conditions.

    procedure ConfirmDeletion(): Boolean
    var
        SourceCode: Record "Source Code";
        SourceCodeSetup: Record "Source Code Setup";
        PostSalesDelete: Codeunit "PostSales-Delete";
        ConfirmManagement: Codeunit "Confirm Management";
        IsHandled: Boolean;
    begin
        OnBeforeConfirmDeletion(Rec, IsHandled);

        if IsHandled then
            exit;
    [...]

    [IntegrationEvent(false, false)]
    local procedure OnBeforeConfirmDeletion(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
