### ISSUE TITLE
event request - table 38 "Purchase Header" - ConfirmDeletion() - OnBeforeConfirmDeletion()

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15236]
`table 36 "Sales Header"` has this, implemented partially since https://github.com/microsoft/ALAppExtensions/issues/8481 and fully after https://github.com/microsoft/ALAppExtensions/issues/15235 - but `table 38 "Purchase Header"` lacks the expected symmetry.

Please thus add an event with the Handled pattern, like so:

    procedure ConfirmDeletion(): Boolean
    var
        SourceCode: Record "Source Code";
        SourceCodeSetup: Record "Source Code Setup";
        PostPurchDelete: Codeunit "PostPurch-Delete";
        ConfirmManagement: Codeunit "Confirm Management";
        IsHandled: Boolean;
    begin
        OnBeforeConfirmDeletion(Rec, IsHandled);

        if IsHandled then
            exit;
    [...]

    [IntegrationEvent(false, false)]
    local procedure OnBeforeConfirmDeletion(var PurchaseHeader: Record "Purchase Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
