### ISSUE TITLE
event request - codeunit 368 "Format Document" - SetSalesPerson() - OnBeforeSetSalesPerson()

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15242]
We'd like to make the absence of the related Salesperson/Purchaser record not a hard error. So can we get an OnBefore/Handled event please?

emitted as:

    procedure SetSalesPerson(var SalespersonPurchaser: Record "Salesperson/Purchaser"; "Code": Code[20]; var SalesPersonText: Text[50])
    var
        IsHandled: Boolean;
    begin
        OnBeforeSetSalesPerson(SalespersonPurchaser, "Code", SalesPersonText, IsHandled);

        if IsHandled then
            exit;

        if Code = '' then begin
            SalespersonPurchaser.Init();
            SalesPersonText := '';
        end else begin
            SalespersonPurchaser.Get(Code);
            SalesPersonText := SalespersonTxt;
        end;
    end;

published as:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetSalesPerson(var SalespersonPurchaser: Record "Salesperson/Purchaser"; "Code": Code[20]; var SalesPersonText: Text[50]; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
