### ISSUE TITLE
Event Request: Table 5902 Service Line

### ISSUE THREAD

**Issue by ACJStopka** [Microsoft/ALAppExtensions#1524]
Event declaration:
LOCAL [IntegrationEvent] OnAfterFilterLinesWithItemToPlan(VAR ServiceLine: Record "Service Line";VAR Item : Record Item)

A new code is required:
[External] FilterLinesWithItemToPlan(VAR Item : Record Item)
RESET;
SETCURRENTKEY(Type,"No.","Variant Code","Location Code","Needed by Date","Document Type");
SETRANGE("Document Type","Document Type"::Order);
SETRANGE(Type,Type::Item);
SETRANGE("No.",Item."No.");
SETFILTER("Variant Code",Item.GETFILTER("Variant Filter"));
SETFILTER("Location Code",Item.GETFILTER("Location Filter"));
SETFILTER("Needed by Date",Item.GETFILTER("Date Filter"));
SETFILTER("Shortcut Dimension 1 Code",Item.GETFILTER("Global Dimension 1 Filter"));
SETFILTER("Shortcut Dimension 2 Code",Item.GETFILTER("Global Dimension 2 Filter"));
SETFILTER("Outstanding Qty. (Base)",'<>0');
// *** new code *** >>
OnAfterFilterLinesWithItemToPlan(Rec,Item);
// *** new code *** <<

**Comment by AlexanderYakunin** [comment]
Event already exist
