### ISSUE TITLE
[Event Request] codeunit 5632 "FA Jnl.-Post Line" - OnBeforeFAJnlPostLine /  OnAfterFAJnlPostLine / OnBeforeGenJnlPostLine /  OnAfterGenJnlPostLine

### ISSUE THREAD

**Issue by Mike-1984** [microsoft/ALAppExtensions#15249]
Hello colleagues,

We would like to create additional postings in FA using the same instance of the  "FA Jnl.-Post Line"  codeunit.

Could you please change the signature of those events to include the sender.

New signatures:
```
    [IntegrationEvent(**true**, false)]
    local procedure OnBeforeFAJnlPostLine(var FAJournalLine: Record "FA Journal Line")

    [IntegrationEvent(**true**, false)]
    local procedure OnAfterFAJnlPostLine(var FAJournalLine: Record "FA Journal Line")

    [IntegrationEvent(**true**, false)]
    local procedure OnBeforeGenJnlPostLine(var GenJournalLine: Record "Gen. Journal Line")

    [IntegrationEvent(**true**, false)]
    local procedure OnAfterGenJnlPostLine(var GenJournalLine: Record "Gen. Journal Line")

```

Thank you, best regards.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
