### ISSUE TITLE
[Code Change] Codeunit 6224 - "XML DOM Management" - TryTransformXMLToOutStream

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#15246]
Hi al-team, 

i used XSL transformation to remove nodes without content from an xml file
In the Base app there is the function TryTransformXMLToOutStream in the Codeunit XML DOM Management for this task.

When using my own XSL, this function throws the following error. 
_White space cannot be stripped from input documents that have already been loaded. Provide the input document as an XmlReader instead._

This problem is also described here: 
https://stackoverflow.com/questions/15548147/white-space-cannot-be-stripped-from-input-documents-that-have-already-been-loade
https://social.msdn.microsoft.com/Forums/en-US/cfc903a8-5582-4d5e-b447-7dcfa1d4d81f/xsltransform-conversion-problem-quotwhite-space-cannot-be-stripped-from-input-documents-that-have?forum=xmlandnetfx

In the error message and also in the forums, it is described as solution that when using the XslCompiledTransform.Transform function, not an IXPathNavigable object should be passed but an XMLReader. 

However, I could not find out the cause of the problem.

Nevertheless, my suggestion is to rebuild or overload the function as follows. 
```
    [TryFunction]
    procedure TryTransformXMLToOutStream(var XmlInStream: InStream; var XslInStream: InStream; var XmlOutStream: OutStream)
    var
        XslCompiledTransform: DotNet XslCompiledTransform;
        XslReader: DotNet XmlReader;
        XmlWriter: DotNet XmlWriter;
        XmlReader: DotNet XmlReader;
        XmlIn: DotNet XmlDocument;
        // NEW >>>
        XMLTextReader: DotNet XmlTextReader;
        StringReader: DotNet StringReader;
    // NEW <<<
    begin
        XmlIn := XmlIn.XmlDocument;
        XmlIn.PreserveWhitespace(false);

        CreateXMLReaderFromInStream(XmlInStream, XmlReader);
        XmlIn.Load(XmlReader);

        CreateXMLReaderFromInStream(XslInStream, XslReader);
        XslCompiledTransform := XslCompiledTransform.XslCompiledTransform;
        XslCompiledTransform.Load(XslReader);

        XmlWriter := XmlWriter.Create(XmlOutStream);
        // NEW >>>
        // XslCompiledTransform.Transform(XmlIn.CreateNavigator, XmlWriter);
        XMLTextReader := XMLTextReader.XmlTextReader(StringReader.StringReader(XmlIn.DocumentElement.OuterXml));
        XslCompiledTransform.Transform(XMLTextReader, XmlWriter);
        // NEW <<<
        XmlWriter.Flush;

        XmlReader.Close;
        XslReader.Close;
        XmlWriter.Close;
    end;
```

In order to be able to reproduce the behavior here still the XSL:
```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>
    <xsl:strip-space elements="*"/>
    <xsl:template match="*[descendant::text() or descendant-or-self::*/@*[string()]]">
        <xsl:copy>
            <xsl:apply-templates select="node()|@*"/>
        </xsl:copy>
    </xsl:template>
    <xsl:template match="@*[string()]">
        <xsl:copy/>
    </xsl:template>
</xsl:stylesheet>
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
