### ISSUE TITLE
Codeunit 90 modify event on procedure  UpdateAssociatedSalesOrder

### ISSUE THREAD

**Issue by ASLANSABINEFR** [microsoft/ALAppExtensions#15254]
Hi,

We need a modify event on Codeunit 90 procedure UpdateAssociatedSalesOrder :

..
                     // > Modify event
                           OnUpdateAssocOrderOnAfterSalesOrderLineModify(SalesOrderLine, TempDropShptPostBuffer, SalesShptHeader);
                    // < Modify event
                until TempDropShptPostBuffer.Next() = 0;
                TempDropShptPostBuffer.SetRange("Order No.");
                OnUpdateAssocOrderOnAfterOrderNoClearFilter(TempDropShptPostBuffer);

....
[IntegrationEvent(false, false)]
    local procedure OnUpdateAssocOrderOnAfterSalesOrderLineModify(var SalesOrderLine: Record "Sales Line"; var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer" temporary; SalesShptHeader: Record "Sales Shipment Header")
    begin
    end;
```
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
