### ISSUE TITLE
[feature-request] Filtering "Cust. Ledger Entries" for "Due Date" should affect "Create Reminders"/"Suggest Reminder Lines".

### ISSUE THREAD

**Issue by GeWuNAV** [microsoft/ALAppExtensions#15259]
Currently only the "Document Date" of the "Reminder Header" or the "On Hold" within specific "Cust. Ledger Entries" have an affect on the creation or suggestion of reminder lines.
Intuitively some customers of ours filter the "Cust. Ledger Entry" on "Due Date" and wonder why this does not apply to the generated lines.

Is there a possibility to have this implemented in the base app?

Thank you in advance!

![image](https://user-images.githubusercontent.com/40358071/142637104-3910b534-33bf-46a0-b14d-f34f3f1a07f6.png)

**Comment by AlexanderYakunin** [comment]
Thanks you for your suggestion, but we cannot accept it this way. Please create idea on aka.ms/bcideas and let other partners to vote for. We prioritize feature work based on number of votes

**Comment by GeWuNAV** [comment]
@AlexanderYakunin 
Oh, sorry. The label "feature-request" was the reason of giving it a shot. 
Thank you for your fast response.
