### ISSUE TITLE
[Event Request] Table 83 Item No. - OnValidate: OnValidateItemNoFromProdOrderLine

### ISSUE THREAD

**Issue by NKarolak** [Microsoft/ALAppExtensions#1526]
In **table 83 Item Journal Line,** trigger **Item No. - OnValidate**, please add the following publisher **OnValidateItemNoFromProdOrderLine**:

```
[…]
      IF ProdOrderLine.COUNT = 1 THEN BEGIN
        VALIDATE("Order Line No.",ProdOrderLine."Line No.");
        "Unit of Measure Code" := ProdOrderLine."Unit of Measure Code";
        "Location Code" := ProdOrderLine."Location Code";
        VALIDATE("Variant Code",ProdOrderLine."Variant Code");
        VALIDATE("Bin Code",ProdOrderLine."Bin Code");

        // >> New
        OnValidateItemNoFromProdOrderLine(VAR Rec,ProdOrderLine);
        // << New
       
      END ELSE
        "Unit of Measure Code" := Item."Base Unit of Measure";
    END;
  "Entry Type"::Consumption:
[…]
```

**Comment by AlexanderYakunin** [comment]
We already have this in latest version, it solve you request:

LOCAL CopyFromProdOrderLine(ProdOrderLine : Record "Prod. Order Line")
VALIDATE("Order Line No.",ProdOrderLine."Line No.");
"Unit of Measure Code" := ProdOrderLine."Unit of Measure Code";
"Location Code" := ProdOrderLine."Location Code";
VALIDATE("Variant Code",ProdOrderLine."Variant Code");
VALIDATE("Bin Code",ProdOrderLine."Bin Code");

OnAfterCopyFromProdOrderLine(Rec,ProdOrderLine);
