### ISSUE TITLE
[Event Request] Report 5753 - OnBeforeUpdateReceiptHeaderStatus

### ISSUE THREAD

**Issue by RWeston6** [microsoft/ALAppExtensions#15267]
Please can you add event OnBeforeUpdateReceiptHeaderStatus to function UpdateReceiptHeaderStatus in Report 5753 Get Source Documents

```
    local procedure UpdateReceiptHeaderStatus()
    begin
        // <<New
        OnBeforeUpdateReceiptHeaderStatus(WhseReceiptHeader);
        // >> New
        with WhseReceiptHeader do begin
            if "No." = '' then
                exit;
            Validate("Document Status", GetHeaderStatus(0));
            Modify(true);
        end;
    end;
```

```
    // << New 
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateReceiptHeaderStatus(var WhseReceiptHeader: Record "Warehouse Receipt Header");
    begin
    end;
    // >> New
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
