### ISSUE TITLE
Page 1670 "Option Lookup List" - Evaluate for extended Enums leads to Error

### ISSUE THREAD

**Issue by SBiernat** [microsoft/ALAppExtensions#15269]
Evaluate command is not working correct for extended enums.

I have extended the Enum "Option Lookup Type" and used the EventPublisher "OnBeforeIncludeOption" and "OnFillBufferLookupTypeCase" in Table "Option Lookup Buffer" to fill the Buffer. 
But when i am calling the Page "Option Lookup List" the Evaluate Command leads to the following Error.

![image](https://user-images.githubusercontent.com/45194723/142707729-8ba17cda-e2c7-4c82-9d66-6aaa956fa32c.png)

I know the following Lines are dirty code, but hard coded it is working correct.
![image](https://user-images.githubusercontent.com/45194723/142707800-7bc49c6d-7501-4b16-a88d-ceab83af310f.png)

The following lines are also working, but are leading to an compiler warning.
![image](https://user-images.githubusercontent.com/45194723/142707888-55bfb1e4-c2a8-4ab2-a6c6-b6f7d814777f.png)

**Comment by AlexanderYakunin** [comment]
Are you sure that your extension was published?

**Comment by SBiernat** [comment]
Yes, I am . Because when I replace the code with the other ones, there is no problem

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SBiernat** [comment]
Don't know why, but now it works in my SaaS Sandbox

**Comment by SBiernat** [comment]
I have to open this case again.
Attached you find my TestApp, that leads to an error when using the Lookup.
Tested against a customer cloud sandbox - (https://businesscentral.dynamics.com/xxxxxx) - Doesn't work
[MyEventSub.Codeunit.al.txt](https://github.com/microsoft/ALAppExtensions/files/8030697/MyEventSub.Codeunit.al.txt)
[MyList.Page.al.txt](https://github.com/microsoft/ALAppExtensions/files/8030698/MyList.Page.al.txt)
[MyOptions.Enum.al.txt](https://github.com/microsoft/ALAppExtensions/files/8030699/MyOptions.Enum.al.txt)
[MyTable.Table.al.txt](https://github.com/microsoft/ALAppExtensions/files/8030700/MyTable.Table.al.txt)
[OptionLookupType.EnumExt.al.txt](https://github.com/microsoft/ALAppExtensions/files/8030701/OptionLookupType.EnumExt.al.txt)

**Comment by SBiernat** [comment]
It looks like, that the Evaluate Command does not work for extended values.
I published an APP1 with the Enum Field "Type" (Values A,B,C,D,E)
With APP2 i extended the enum for the values (F,G,H). 
As you can see, both apps are published
![image](https://user-images.githubusercontent.com/45194723/153193673-7502e744-bff3-4013-9158-5f947cfa26a2.png)


I created an Page-Action in Both apps, that evaluates the Value F.


![image](https://user-images.githubusercontent.com/45194723/153194212-36263ff1-02ed-46fd-9aa1-85d727c2d0d3.png)

![image](https://user-images.githubusercontent.com/45194723/153193712-f3a8633c-f0be-463a-82e1-f63438fa4527.png)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).

**Comment by SBiernat** [comment]
@fvet MS has reproduced this problem and hopefully we will get a fix with the next Update (20.1 and 19.6?)
