### ISSUE TITLE
Codeunit 64 "Sales-Get Shipment" new event on procedure "InsertInvoiceLineFromShipmentLine(var SalesShptLine2: Record "Sales Shipment Line"; TransferLine: Boolean; var PrepmtAmtToDeductRounding: Decimal)"

### ISSUE THREAD

**Issue by Hofschn8** [microsoft/ALAppExtensions#15274]
local procedure InsertInvoiceLineFromShipmentLine(var SalesShptLine2: Record "Sales Shipment Line"; TransferLine: Boolean; var PrepmtAmtToDeductRounding: Decimal)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeInsertInvoiceLineFromShipmentLine(SalesShptHeader, SalesShptLine2, SalesHeader, PrepmtAmtToDeductRounding, TransferLine, IsHandled);
        if IsHandled then
            exit;

        if TransferLine then begin
            SalesShptLine := SalesShptLine2;
************************
      +     OnBeforeInsertInvLineFromShptLine(SalesShptLine, SalesLine, IsHandled);
      +     if not IsHandled then
              SalesShptLine.InsertInvLineFromShptLine(SalesLine);
***********************
            CalcUpdatePrepmtAmtToDeductRounding(SalesShptLine, SalesLine, PrepmtAmtToDeductRounding);
        end;
    end;

************************
  +  [IntegrationEvent(false, false)]
  +  local procedure OnBeforeInsertInvLineFromShptLine(var SalesShptLine: Record "Sales Shipment Line"; var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
  +  begin
  +  end;
**********************
[InsertInvoiceLineFromShipmentLine.txt](https://github.com/microsoft/ALAppExtensions/files/7579304/InsertInvoiceLineFromShipmentLine.txt)
**

**Comment by Stepanenko-Vadim** [comment]
Is there a reason you cannot use OnBeforeInsertInvoiceLineFromShipmentLine from here and OnBeforeCodeInsertInvLineFromShptLine from SalesShipmentLine table instead of this? Seems a bit over the top adding another handled pattern in 3 lines of code...
