### ISSUE TITLE
[Event Update Request] CodeUnit 1535 "Approvals Mgmt." - OnBeforeMakeApprovalEntry

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#15276]
In the following event request: [ #14299] we request the event OnBeforeMakeApprovalEntry in the ApprovalsMgmt codeunit.
We see that Microsoft implemented this event, but without the var parameter on the Approval Entry Record. Due to this we are not allowed to make any changes on this record.
We would like to request Microsoft to change the event OnBeforeMakeApprovalEntry with a var parameter on the ApprovalEntry record.

    [IntegrationEvent(false, false)]
    local procedure OnBeforeMakeApprovalEntry(**var** ApprovalEntry: Record "Approval Entry"; ApprovalEntryArgument: Record "Approval Entry"; WorkflowStepArgument: Record "Workflow Step Argument"; ApproverId: Code[50]; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
