### ISSUE TITLE
[Event Request] Page Navigate procedure FindRecordsOnOpen()

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#15272]
Hi,

Please add event at procedure FindRecordsOnOpen()
OnBeforeFindRecordsOnAfterSetDocumentFiltersOnOpen(DocNoFilter,PostingDateFilter,ExtDocNo,NewSourceRecVar);
`  end else begin `
`                Rec.SetRange("Document No.", NewDocNo);`
`                Rec.SetRange("Posting Date", NewPostingDate);`
`                DocNoFilter := Rec.GetFilter("Document No.");`
`                PostingDateFilter := Rec.GetFilter("Posting Date");`
`                ContactType := ContactType::" ";`
`                ContactNo := '';`
`                ExtDocNo := '';`
`                ClearTrackingInfo();`
`                OnBeforeFindRecordsOnAfterSetDocumentFiltersOnOpen(DocNoFilter,PostingDateFilter,ExtDocNo,NewSourceRecVar);`
`                FindRecords();`
`            end;`

`[IntegrationEvent(false, false)]`
`    local procedure OnBeforeFindRecordsOnAfterSetDocumentFiltersOnOpen(var Rec: Record "Document Entry",var DocNoFilter:Text,var PostingDateFilter:Text, ExtDocNo: Code[250],NewSourceRecVar: Variant);`
`    begin`
`    end;`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
