### ISSUE TITLE
Table  111 "Sales Shipment Line"  add Parameter to existing Event "OnBeforeInsertInvLineFromShptLineBeforeInsertTextLine"

### ISSUE THREAD

**Issue by Hofschn8** [microsoft/ALAppExtensions#15275]
procedure InsertInvLineFromShptLine(var SalesLine: Record "Sales Line")
 ...

        SetRange("Document No.", "Document No.");

        TempSalesLine := SalesLine;
        if SalesLine.Find('+') then
            NextLineNo := SalesLine."Line No." + 10000
        else
            NextLineNo := 10000;

        if SalesInvHeader."No." <> TempSalesLine."Document No." then
            SalesInvHeader.Get(TempSalesLine."Document Type", TempSalesLine."Document No.");

        if SalesLine."Shipment No." <> "Document No." then begin

            OnInsertInvLineFromShptLineOnBeforeInsertDescriptionLine(
                Rec, SalesLine, TempSalesLine, SalesInvHeader, NextLineNo);

            SalesLine.Init();
            SalesLine."Line No." := NextLineNo;
            SalesLine."Document Type" := TempSalesLine."Document Type";
            SalesLine."Document No." := TempSalesLine."Document No.";
            TranslationHelper.SetGlobalLanguageByCode(SalesInvHeader."Language Code");
            SalesLine.Description := StrSubstNo(Text000, "Document No.");
            TranslationHelper.RestoreGlobalLanguage;
            IsHandled := false;
*****************************
       -    OnBeforeInsertInvLineFromShptLineBeforeInsertTextLine(Rec, SalesLine, NextLineNo, IsHandled);
       +    OnBeforeInsertInvLineFromShptLineBeforeInsertTextLine(Rec, SalesLine, TempSalesLine, SalesInvHeader, NextLineNo, IsHandled);
*****************************
            if not IsHandled then begin
                SalesLine.Insert();
                OnAfterDescriptionSalesLineInsert(SalesLine, Rec, NextLineNo);
                NextLineNo := NextLineNo + 10000;
            end;
        end;

...

	[IntegrationEvent(false, false)]
*****************************
 -  local procedure OnBeforeInsertInvLineFromShptLineBeforeInsertTextLine(var SalesShptLine: Record "Sales Shipment Line"; var SalesLine: Record "Sales Line"; var NextLineNo: Integer; var Handled: Boolean)
 +  local procedure OnBeforeInsertInvLineFromShptLineBeforeInsertTextLine(var SalesShptLine: Record "Sales Shipment Line"; var SalesLine: Record "Sales Line"; **TempSalesLine: Record "Sales Line" temporary**; **SalesInvHeader: Record "Sales Header"**; var NextLineNo: Integer; var Handled: Boolean)
*****************************
    begin
    en
[OnBeforeInsertInvLineFromShptLineBeforeInsertTextLine.txt](https://github.com/microsoft/ALAppExtensions/files/7579326/OnBeforeInsertInvLineFromShptLineBeforeInsertTextLine.txt)
d;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
