### ISSUE TITLE
Planning Direction table 5409 Prod. Order Routing Line

### ISSUE THREAD

**Issue by Bakmans** [microsoft/ALAppExtensions#15278]
The planning direction is always Forward when a time is entered manually in the prod. order routing line.
There is a subcription **OnbeforeCalcStartingEndingDates** in table 5409, but the direction parameter is not a VAR.
![image](https://user-images.githubusercontent.com/94836253/142846722-861d89f7-3e63-44d5-8996-c57986206df4.png)

So it is not possible to infleunce the planning direction.
Can this be changed, that the parameter Direction is a VAR.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
