### ISSUE TITLE
Custom Address Format has only 6 Lines instead of 8 possible

### ISSUE THREAD

**Issue by SBiernat** [microsoft/ALAppExtensions#15279]
In the Country Table you can select the address format "Custom Address".
This generates the Custom Address Format with 6 Lines. 
In this lines the Country is missing.

It is not possible to create more lines than 6, because the first lines are auto generated and the pageinsert is not enabled.

The FormatAddress Function can handle 8 Lines. So why is this function limited to 6 lines?

**Comment by dnpb** [comment]
You can use a page extension to add an action that will add up to 2 more additional lines than the defaults, and then they work OK.

I agree though that it's weird this doesn't support 8 lines as standard.

**Comment by SBiernat** [comment]
Ok, this should work. 
But perhaps you agree and it could be fixed in the future, that the country code in the standard format.
It doesn't make sense, that you have a differnt country and don't show it in the address.

**Comment by dnpb** [comment]
I already said I agree. I don't work for MS, so I can't do more than that.

**Comment by SBiernat** [comment]
Ok, thanks i don't look at your profile.

But why should i use a workaround to fix a standard bug? This should not be the way...

**Comment by dnpb** [comment]
I didn't say it should be the way; I said it is a workaround until MS hopefully fix this properly... use it or don't.

**Comment by AlexanderYakunin** [comment]
Can you provide more information where we have limitation of 6 lines? And if this is a bug, why you didn't report it via technical support? How this issue is related to extensibility?

**Comment by SBiernat** [comment]
Ok, you are right. This has nothing to do with extensibility.
