### ISSUE TITLE
[Event Request] - codeunit 7324 "Whse.-Activity-Post"  OnAfterSetInvoiceSourceDoc

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#15283]
Can we please get the following event?
```al
procedure SetInvoiceSourceDoc(Invoice: Boolean)
begin
    InvoiceSourceDoc := Invoice;
    OnAfterSetInvoiceSourceDoc(InvoiceSourceDoc); //NEW
end;
```
```al
[IntegrationEvent(false, false)]
local procedure OnAfterSetInvoiceSourceDoc(var InvoiceSourceDocument: Boolean )
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
