### ISSUE TITLE
[Parameter Request] report 5881 "Make Phys. Invt. Recording"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#15281]
Could you please give us access to the follwoing variables in report `report 5881 "Make Phys. Invt. Recording"`?
```al
protected var
    NextLineNo: Integer;
    HeaderCount: Integer;
    OnlyLinesNotInRecordings: Boolean;
    HeaderInserted: Boolean;
    AllowRecWithoutOrder: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
