### ISSUE TITLE
[Event Request] table 5900 "Service Header" - OnValidateCustomerNoAfterInit

### ISSUE THREAD

**Issue by iltererdogan** [microsoft/ALAppExtensions#15298]
Hi,

Is it possible to add OnValidateCustomerNoAfterInit publisher to Service Header table?

        field(2; "Customer No."; Code[20])
        {
            Caption = 'Customer No.';
            TableRelation = Customer;

            trigger OnValidate()
            var
                ConfirmManagement: Codeunit "Confirm Management";
                IsHandled: Boolean;
            begin
                if ("Customer No." <> xRec."Customer No.") and (xRec."Customer No." <> '') then begin
                    if "Contract No." <> '' then
                        Error(
                          Text003,
                          FieldCaption("Customer No."),
                          "Document Type", FieldCaption("No."), "No.",
                          FieldCaption("Contract No."), "Contract No.");
                    if HideValidationDialog or not GuiAllowed then
                        Confirmed := true
                    else
                        if ServItemLineExists then
                            Confirmed :=
                              ConfirmManagement.GetResponseOrDefault(
                                StrSubstNo(Text004, FieldCaption("Customer No.")), true)
                        else
                            if ServLineExists then
                                Confirmed :=
                                  ConfirmManagement.GetResponseOrDefault(
                                    StrSubstNo(Text057, FieldCaption("Customer No.")), true)
                            else
                                Confirmed :=
                                  ConfirmManagement.GetResponseOrDefault(
                                    StrSubstNo(Text005, FieldCaption("Customer No.")), true);
                    if Confirmed then begin
                        ServLine.SetRange("Document Type", "Document Type");
                        ServLine.SetRange("Document No.", "No.");
                        if "Document Type" = "Document Type"::Order then
                            ServLine.SetFilter("Quantity Shipped", '<>0')
                        else
                            if "Document Type" = "Document Type"::Invoice then begin
                                ServLine.SetRange("Customer No.", xRec."Customer No.");
                                ServLine.SetFilter("Shipment No.", '<>%1', '');
                            end;

                        if ServLine.FindFirst then begin
                            if "Document Type" = "Document Type"::Order then
                                ServLine.TestField("Quantity Shipped", 0)
                            else
                                ServLine.TestField("Shipment No.", '');
                        end;
                        OnValidateCustomerNoOnBeforeModify(Rec, CurrFieldNo);
                        Modify(true);

                        IsHandled := false;
                        OnValidateCustomerNoOnBeforeDeleteLines(Rec, IsHandled);
                        if not IsHandled then begin
                            ServLine.LockTable();
                            ServLine.Reset();
                            ServLine.SetRange("Document Type", "Document Type");
                            ServLine.SetRange("Document No.", "No.");
                            ServLine.DeleteAll(true);

                            ServItemLine.LockTable();
                            ServItemLine.Reset();
                            ServItemLine.SetRange("Document Type", "Document Type");
                            ServItemLine.SetRange("Document No.", "No.");
                            ServItemLine.DeleteAll(true);
                        end;

                        Get("Document Type", "No.");
                        if "Customer No." = '' then begin
                            Init;
                            // <<new
                            OnValidateCustomerNoAfterInit(Rec, xRec);
                            // >>new
                            GetServiceMgtSetup();
                            "No. Series" := xRec."No. Series";
                            InitRecord;
                            if xRec."Shipping No." <> '' then begin
                                "Shipping No. Series" := xRec."Shipping No. Series";
                                "Shipping No." := xRec."Shipping No.";
                            end;
                            if xRec."Posting No." <> '' then begin
                                "Posting No. Series" := xRec."Posting No. Series";
                                "Posting No." := xRec."Posting No.";
                            end;
                            exit;
                        end;
                    end else begin
                        Rec := xRec;
                        exit;
                    end;
                end;

                GetCust("Customer No.");
                if "Customer No." <> '' then begin
                    IsHandled := false;
                    OnBeforeCheckBlockedCustomer(Cust, IsHandled);
                    if not IsHandled then
                        Cust.CheckBlockedCustOnDocs(Cust, "Document Type", false, false);
                    Cust.TestField("Gen. Bus. Posting Group");
                    CopyCustomerFields(Cust);
                end;

                if "Customer No." = xRec."Customer No." then
                    if ShippedServLinesExist then
                        if not ApplicationAreaMgmt.IsSalesTaxEnabled then begin
                            TestField("VAT Bus. Posting Group", xRec."VAT Bus. Posting Group");
                            TestField("Gen. Bus. Posting Group", xRec."Gen. Bus. Posting Group");
                        end;

                Validate("Ship-to Code", Cust."Ship-to Code");
                if Cust."Bill-to Customer No." <> '' then
                    Validate("Bill-to Customer No.", Cust."Bill-to Customer No.")
                else begin
                    if "Bill-to Customer No." = "Customer No." then
                        SkipBillToContact := true;
                    Validate("Bill-to Customer No.", "Customer No.");
                    SkipBillToContact := false;
                end;

                Validate("Service Zone Code");

                if not SkipContact then
                    UpdateCont("Customer No.");
            end;
        }

    // <<new
    [IntegrationEvent(false, false)]
    local procedure OnValidateCustomerNoAfterInit(var ServiceHeader: Record "Service Header"; xServiceHeader: Record "Service Header")
    begin
    end;
    // >>new

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
