### ISSUE TITLE
[Question] For which Document Types is the Purchasing Code of the Item transfered to the Sales Line 

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#15293]
Hello,

I found several different Version how the purchasing code of the item is transfered to the sales line. 
In one version it is only validated if the document type is order, in another always and in another if the document type is quote or order. Can you help us and make clear, when the purchasing code is transfered?
Thank you.

**Comment by AlexanderYakunin** [comment]
@AndreiPanko - can you help?

**Comment by StanPesotskiy** [comment]
Your request is not related to the AL **application** extensibility. 
Please post it at https://www.yammer.com/dynamicsnavdev/ where the wider community may give you a valid answer.
