### ISSUE TITLE
Table 5902 Service Line updates Service Ledger Entry

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#15291]
There is a function that updates Service Ledger Entry (local procedure **UpdateServiceLedgerEntry**()) but it has no Permissions granted in code, despite we define them in User Permissions we need this in code as well

**BEFORE**
table 5902 "Service Line"
{
    Caption = 'Service Line';
    DrillDownPageID = "Service Line List";
    LookupPageID = "Service Line List";

**AFTER**
table 5902 "Service Line"
{
    **Permissions = tabledata "Service Ledger Entry" = rm;**
    Caption = 'Service Line';
    DrillDownPageID = "Service Line List";
    LookupPageID = "Service Line List";

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
