### ISSUE TITLE
[Translation] Contact Card German

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#15292]
There is no Translation in German for Prices on Contact Card

![image](https://user-images.githubusercontent.com/86241544/142906161-d9a500b5-8255-42a1-892d-c9367bc1da33.png)

page 5050 "Contact Card"
            group(**Prices**)
            {
                action(PriceLists)
                {

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
