### ISSUE TITLE
Adding GUIALLOWED condition to dialog window calls in Codeunit 5870 "Calculate BOM Tree" 

### ISSUE THREAD

**Issue by CarstenHeu** [microsoft/ALAppExtensions#15296]
We want to use the BOM Tree calculation to the BOM Buffer in a webservice background task. So it would be necessary to suppress the dialog window calls if no gui allowed.
So please add the guiallowed conditon to every dialog window command in the "Calculate BOM Tree" codeunit.

Kind regards,

Carsten Heu.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
