### ISSUE TITLE
[Event-Request] Codeunit 96 Purch.-Quote to Order OnAfterOnRun

### ISSUE THREAD

**Issue by OlivierHellmann** [Microsoft/ALAppExtensions#153]
Hi, 
we would like a new event in Codeunit 96 Purch.-Quote to Order, similar to the event in Codeunit 86:
OnAfterOnRun(Rec,PurchOrderHeader)

thanks in advance

**Comment by AlexanderYakunin** [comment]
This event already exist in BC

**Comment by JesperSchulz** [comment]
Closing as per @AlexanderYakunin's reply.
