### ISSUE TITLE
[Event Request] Add OnAfterPostTempWhseJnlLineCache in codeunit 7320 "Whse. Undo Quantity"

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#15301]
Hi, please consider adding the following event to `codeunit 7320 "Whse. Undo Quantity"`:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterPostTempWhseJnlLine(var TempWhseJnlLine: Record "Warehouse Journal Line" temporary)
    begin
    end;
```

and raise it as follows inside the `PostTempWhseJnlLineCache` procedure:

```
    procedure PostTempWhseJnlLineCache(var TempWhseJnlLine: Record "Warehouse Journal Line" temporary; var WhseJnlRegLine: Codeunit "Whse. Jnl.-Register Line")
    begin
        OnBeforePostTempWhseJnlLine(TempWhseJnlLine);
        if TempWhseJnlLine.Find('-') then
            repeat
                WhseJnlRegLine.RegisterWhseJnlLine(TempWhseJnlLine);
            until TempWhseJnlLine.Next() = 0;
        OnAfterPostTempWhseJnlLine(TempWhseJnlLine);
    end;
```

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
