### ISSUE TITLE
[Event-request] Sales/Purchase Invoice Header - OnBeforeCheckCorrectedDocumentExist

### ISSUE THREAD

**Issue by asaez85** [microsoft/ALAppExtensions#15307]
We need a new event with a "IsHandled" parameter:
![image](https://user-images.githubusercontent.com/2249576/143014802-2378bfd8-27cb-4b45-9107-f636c8aee5c8.png)

Same situation occurs in Purchase Invoice Header.

Thank you

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by asaez85** [comment]
**Table: 112 "Sales Invoice Header" - "CheckCorrectedDocumentExist" procedure:**
```
    procedure CheckCorrectedDocumentExist(CustNo: Code[20]; CorrInvNo: Code[20])
    //event-request
    var
        IsHandled: Boolean;
    begin
        OnBeforeCheckCorrectedDocumentExist(Custno,CorrInvNo,IsHandled);
        if IsHandled then
            exit;
    //event-request

        SetRange("Bill-to Customer No.", CustNo);
        SetRange("No.", CorrInvNo);
        if not FindFirst then
            Error(CorrInvDoesNotExistErr, CorrInvNo);
    end;
```
Integration event:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckCorrectedDocumentExist(CustNo: Code[20]; CorrInvNo: Code[20];var IsHandled: Boolean)
    begin
    end;
```

**Table: 122 "Purch. Inv. Header" - "CheckCorrectedDocumentExist" procedure:**
```
    procedure CheckCorrectedDocumentExist(VendNo: Code[20]; CorrInvNo: Code[20])
    //event-request
    var
        IsHandled: Boolean;
    begin
        OnBeforeCheckCorrectedDocumentExist(VendNo,CorrInvNo,IsHandled);
        if IsHandled then
            exit;
    //event-request

        SetRange("Pay-to Vendor No.", VendNo);
        SetRange("No.", CorrInvNo);
        if not FindFirst then
            Error(CorrInvDoesNotExistErr, CorrInvNo);
    end;
```
Integration event:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckCorrectedDocumentExist(VendNo: Code[20]; CorrInvNo: Code[20];var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
