### ISSUE TITLE
Working with parallel routings - Error during certification

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#15305]
If you create a parallel routing and choose ranges (200..220) instead of pipe separated operations (200|210|220) to avoid 30 character limitation of the fields "next and previous operation" there is some strange behaviour after certification.

Next operation stays as a "range", but previous operation is changed from range orientated string to pipe separated. 
Can you please check and confirm this? Working with ranges would be great to avoid the limitation of char30-fields.

Tested on Version: DE Business Central 19.0 (Platform 19.0.29884.30666 + Application 19.0.29894.30870)

Screenshot before certification:
![image](https://user-images.githubusercontent.com/40287548/143004236-1984f69f-9ff8-49c2-8a10-4266783ea54a.png)

Screenshot after certification:
![image](https://user-images.githubusercontent.com/40287548/143004314-074bf286-44ea-40a3-8251-74181a6ea4a1.png)

**Comment by AlexanderYakunin** [comment]
Hello! This is not an extensibility request or bug and our team is not working on application functionality fixes. Right way is to report this as hotfix request via technical support.

**Comment by AndreBreitenbach** [comment]
Ok, thanks. We will create an hotfix request.
