### ISSUE TITLE
Financial Journal [P11300] - Change variables to protected 

### ISSUE THREAD

**Issue by NicolasVanDerSpiegel** [microsoft/ALAppExtensions#15304]
Hello, 

<Page 11300 - Financial Journal> 

We are having the problem that we can't update the fields <Balance Last Statement> and <Statement Ending Balance>  on our Financial Journal Page. 
The function <UpdateStatementAmounts> is set Obsolete:
![image](https://user-images.githubusercontent.com/92102399/143003263-8541fc1a-c9b3-4c47-9fb3-c215a53d637b.png)

I would ask if it is possible to make the following Global Variables **Protected**: 

- BalanceLastStatement: Decimal;
- StatementEndingBalance: Decimal;
- TotalBalance: Decimal; 
- Balance: Decimal; 
![image](https://user-images.githubusercontent.com/92102399/143003577-117565f6-7f83-4a5e-bb9b-a8ddc06c6f06.png)

Kind regards,
Nicolas

**Comment by AlexanderYakunin** [comment]
You can use obsoleted function, in this case this is just information. Protected will be added.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
