### ISSUE TITLE
[Protected var Request]Report 15000001  "Suggest Remittance Payments" - VendLedgEntry Variable

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#15309]
Hello, Is it possible to make VendLedgEntry which is a global variable in this report to protected var?
```   
    Protected var
        VendLedgEntry: Record "Vendor Ledger Entry";

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
