### ISSUE TITLE
Report "Vendor - Balance to Date" (321) Vendor's Total Issue

### ISSUE THREAD

**Issue by glachana** [microsoft/ALAppExtensions#15310]
Hi, 

It seems that the rdl of this report cannot display the total by vendor and by currency. It does not loop through the temporary records CurrTotalBufferTotalAmt

![image](https://user-images.githubusercontent.com/55086553/143015201-a18bb740-a515-41d9-9186-1079bd074792.png)

Here a exemple on Business Central :
![image](https://user-images.githubusercontent.com/55086553/143016254-d466e850-704a-4757-af48-52a74b0963f8.png)

Here an exemple on Dynamics NAV 2016 :
![image](https://user-images.githubusercontent.com/55086553/143016401-1781fe6f-f5c1-4144-8424-c164823420f8.png)

**Comment by AlexanderYakunin** [comment]
Sorry, this is not extensibility request and we cannot fix this kind of issues here. Can you report hotfix requests via technical support?
