### ISSUE TITLE
[Event Request] Codeunit 8612- Config. Template Management - procedure ModifyRecordWithField

### ISSUE THREAD

**Issue by tepke22** [microsoft/ALAppExtensions#15318]
We would like to have in Codeunit **8612- Config. Template Management** in procedure **ModifyRecordWithField** 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/39384168/143054603-fd247e09-2fd1-4ce2-8cc3-865da15ae496.png)

**RecRef** and **FieldRef** as **Var** parameters.

**Comment by dnpb** [comment]
Do you intend to change the record/field to which they refer? They needn't be `var` if not, as `Ref`s innately have reference semantics.

**Comment by tepke22** [comment]
Yeah, we plan to reassign Refs, so we need var.

**Comment by Oleg-Romashkov** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
