### ISSUE TITLE
codeunit 2 "Company-Initialize" - Initializing "Source Code" Description field length

### ISSUE THREAD

**Issue by BertDeTemmerman** [microsoft/ALAppExtensions#15311]
The following functions should have an update of the length of the description variables.
The `Object Caption` from `AllObjWithCaption` (text249), passed through as a text250, then shrinked to a text30 in `PageName` & `ReportName`, but return as a text50, and stored in a text100 `Description` field.

Could the functions `InsertSourceCode, PageName and ReportName` be updated to store the first 100 characters of the related report and page caption?
(so there is some consistency?)

```
    local procedure InsertSourceCode(var SourceCodeDefCode: Code[10]; "Code": Code[10]; Description: Text[50])
    var
        SourceCode: Record "Source Code";
    begin
        SourceCodeDefCode := Code;
        SourceCode.Init();
        SourceCode.Code := Code;
        SourceCode.Description := Description;
        SourceCode.Insert();
    end;

    local procedure PageName(PageID: Integer): Text[50]
    var
        ObjectTranslation: Record "Object Translation";
    begin
        exit(CopyStr(ObjectTranslation.TranslateObject(ObjectTranslation."Object Type"::Page, PageID), 1, 30));
    end;

    local procedure ReportName(ReportID: Integer): Text[50]
    var
        ObjectTranslation: Record "Object Translation";
    begin
        exit(CopyStr(ObjectTranslation.TranslateObject(ObjectTranslation."Object Type"::Report, ReportID), 1, 30));
    end;
```

with
table 230 "Source Code"
`field(2; Description; Text[100])`

where
table 377 "Object Translation"
```
    procedure TranslateObject(ObjectType: Option " ","Table",Form,"Report",,"Codeunit","XMLPort",MenuSuite,"Page"; ObjectID: Integer): Text[250]
    var
        "Object": Record AllObjWithCaption;
    begin
        if Object.Get(ObjectType, ObjectID) then
            exit(Object."Object Caption");
    end;

    procedure TranslateTable(ObjectID: Integer): Text[250]
    begin
        exit(TranslateObject("Object Type"::Table, ObjectID));
    end;
```

with
table 2000000058 AllObjWithCaption
`field(20; "Object Caption"; Text[249])`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
