### ISSUE TITLE
Enum Request Table 60 "Document Sending Profile"

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [microsoft/ALAppExtensions#15327]
Can you change the type of the option fields "Electronic Document" and "Send To" to Enum.

 field(20; "Electronic Document"; Option)
        {
            Caption = 'Electronic Document';
            OptionCaption = 'No,Through Document Exchange Service';
            OptionMembers = No,"Through Document Exchange Service";
        }
field(50; "Send To"; Option)
        {
            Caption = 'Send To';
            OptionCaption = 'Disk,Email,Print,Electronic Document';
            OptionMembers = Disk,Email,Print,"Electronic Document";
        }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
