### ISSUE TITLE
[Event Request] Codeunit Intrastat Document Completion (331), Procedure "DefaultPurchaseDcouments"

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#15324]
Hi,
we need to transfer additional values from Intrastat Setup to the Purchase Header, so would like to suggest the event "OnAfterDefaultPurchaseDocuments" in procedure "DefaultPurchaseDocuments":

`OnAfterDefaultPurchaseDocuments(Rec,` IntrastatSetup);`

The signature of the event looks like this:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterDefaultPurchaseDocuments(var Rec: Record "Purchase Header"; IntrastatSetup: Record "Intrastat Setup")
    begin
    end;

```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
