### ISSUE TITLE
[Event Request] Codeunit Intrastat Document Completion (331), Procedure "DefaultSalesDocuments"

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#15323]
Hi,
we need to transfer additional values from Intrastat Setup to the Sales Header, so would like to suggest the event "OnAfterDefaultSalesDocuments" in procedure "DefaultSalesDocuments":

`OnAfterDefaultSalesDocuments(Rec, IntrastatSetup);`

The Event signature should look like this:

```
[IntegrationEvent(false, false)]
local procedure OnAfterDefaultSalesDocuments(var SalesHeader: Record "Sales Header"; IntrastatSetup: Record "Intrastat Setup")
begin
end;

```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
