### ISSUE TITLE
Inventory Pick with "Non-inventory" item gives incorrect message

### ISSUE THREAD

**Issue by renevanbeekum** [microsoft/ALAppExtensions#15320]
[Sales Order with non-inventory item and inventory-pick.docx](https://github.com/microsoft/ALAppExtensions/files/7593439/Sales.Order.with.non-inventory.item.and.inventory-pick.docx)

See attachment, also occurs in the latest BC19CU1 version

**Comment by dnpb** [comment]
This doesn't seem related to extensibility and so should probably be filed via Partner Centre or such instead.

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot analyze and fix such requests here, please report as hotfix request via technical support channels
