### ISSUE TITLE
[Event Request] Table 11400 - "CBG Statement" OnAfterInitRecord

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#15332]
We would like to request an event OnAfterInitRecord on the CBG Statement Header.
We would like to make some modification on the CBGStatement after the CBGStatement has been initialized with the InitRecord function.   
   
    procedure InitRecord(UseTemplate: Code[10])
    var
        CBGStatement: Record "CBG Statement";
        JournalTemplate: Record "Gen. Journal Template";
        BankAccount: Record "Bank Account";
        GLAccount: Record "G/L Account";
        NoSeriesMgt: Codeunit NoSeriesManagement;
    begin
        "Journal Template Name" := DelChr(UseTemplate, '<>', '''');
        JournalTemplate.Get("Journal Template Name");

        case JournalTemplate.Type of
            JournalTemplate.Type::Cash:
                Type := Type::Cash;
            JournalTemplate.Type::Bank:
                begin
                    Type := Type::"Bank/Giro";
                    if Date = 0D then
                        Date := WorkDate;
                end;
        end;

        case JournalTemplate."Bal. Account Type" of
            JournalTemplate."Bal. Account Type"::"G/L Account":
                "Account Type" := "Account Type"::"G/L Account";
            JournalTemplate."Bal. Account Type"::"Bank Account":
                "Account Type" := "Account Type"::"Bank Account"
            else
                Error(Text1000000,
                  JournalTemplate."Bal. Account Type",
                  JournalTemplate.FieldCaption("Bal. Account Type"));
        end;

        JournalTemplate.TestField("Bal. Account No.");
        "Account No." := JournalTemplate."Bal. Account No.";
        case "Account Type" of
            "Account Type"::"G/L Account":
                begin
                    GLAccount.Get("Account No.");
                    Currency := '';
                end;
            "Account Type"::"Bank Account":
                begin
                    BankAccount.Get("Account No.");
                    Currency := BankAccount."Currency Code";
                end;
        end;

        if "Opening Balance" = 0 then begin
            CBGStatement.SetRange("Journal Template Name", "Journal Template Name");
            CBGStatement.SetFilter("No.", '<>%1', "No.");
            if CBGStatement.FindLast then
                "Opening Balance" := CBGStatement."Closing Balance"
            else
                case "Account Type" of
                    "Account Type"::"G/L Account":
                        begin
                            GLAccount.Get("Account No.");
                            GLAccount.CalcFields(Balance);
                            "Opening Balance" := GLAccount.Balance;
                        end;
                    "Account Type"::"Bank Account":
                        begin
                            BankAccount.Get("Account No.");
                            BankAccount.CalcFields(Balance);
                            "Opening Balance" := BankAccount.Balance;
                        end;
                end;

            "Closing Balance" := 0;
        end;

        if (JournalTemplate.Type = JournalTemplate.Type::Bank) and ("Document No." = '') then begin
            JournalTemplate.TestField("No. Series");
            NoSeriesMgt.InitSeries(JournalTemplate."No. Series", xRec."No. Series", Date, "Document No.", "No. Series");
        end;

        if JournalTemplate.Type = JournalTemplate.Type::Bank then
            CreateDim(DATABASE::"Bank Account", "Account No.", 0, '', 0, '', 0, '', 0, '')// Use the Bank Account
        else
            CreateDim(DATABASE::"G/L Account", "Account No.", 0, '', 0, '', 0, '', 0, '');// Use the G/L Account

        >>>OnAfterInitRecord(CBGStatement);<<<
    end;
    
With Event

    [IntegrationEvent(false, false)]
    local procedure OnAfterInitRecord(var CBGStatement: Record "CBG Statement")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
