### ISSUE TITLE
[Event publisher] Modification in event publisher "OnUpdateAssemblyLinesOnAfterCopyAssemblyData" in codeunit 905 "Assembly Line Management"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#15333]
Dear ALAppExtensions Team:

We need a modification in  the event publisher OnUpdateAssemblyLinesOnAfterCopyAssemblyData in codeunit 905 "Assembly Line Management". We need the parameter ReplaceLinesFromBom to be declared by reference.
 

OLD CODE:

 [IntegrationEvent(false, false)]
    local procedure OnUpdateAssemblyLinesOnAfterCopyAssemblyData(var AssemblyLine: Record "Assembly Line"; ReplaceLinesFromBOM: Boolean)
    begin
    end;

NEW CODE:

 [IntegrationEvent(false, false)]
    local procedure OnUpdateAssemblyLinesOnAfterCopyAssemblyData(var AssemblyLine: Record "Assembly Line"; **var** ReplaceLinesFromBOM: Boolean)
    begin
    end;

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
