### ISSUE TITLE
[Event Request] Table 37 OnBeforeUpdateLocationCode - broken in 19.0

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#15330]
Hi:

in 18.5.29545.31455, the procedure InitHeaderLocactionCode (sic) looked as follows:

        IsHandled := false;
        OnBeforeUpdateLocationCode(Rec, IsHandled);
        if IsHandled then
            "Location Code" := SalesHeader."Location Code"
        else
            if not IsNonInventoriableItem then
                "Location Code" := SalesHeader."Location Code";

now in 19.0.29894.32762, it is as follows:

        IsHandled := false;
        OnBeforeUpdateLocationCode(Rec, IsHandled);
        "Location Code" := SalesHeader."Location Code";

why? The ability to handle NonInventoriable items has been removed. This seems like a step backward. (And my client wasn't even handling them; they were taking default functionality in 18.5, which was that NonInvenotoriable Items did *NOT* get a location code on insert).

When can the ability to handle NonInventoryItems be restored? Or hopefully it has already been restored in 19.1 or 19.2?

Here is the huge negative implication for my client:

Report 7323 (create inventory pick/putaway/movement) will not create an inventory pick when the following are true (as it is now in 19.0):
- "Sales Header"."Shipping Advice" = Complete
- All NonInventoriable Items *DO HAVE* a Location code
- All NonInventoriable Items have Qty to Ship > 0

So they have to relax one of the 3 above in order for Inventory Pick creation to complete successfully (Report 7323)

They process 3,000+ orders per day. :( Nearly all have at least one Service item on them, and they send the Inventory Pick to a 3PL.

**Comment by grantbrimhall** [comment]
of course after hitting send, I see there is an event just above (OnBeforeInitHeaderLocactionCode) <sic> that could possibly be used to handle the noninventoriable items. Still curious why the change was made. it seems to have made OnBeforeUpdateLocationCode an almost useless Event now.

**Comment by Oleg-Romashkov** [comment]
This update had been made in scope of ["Enable locations for Non-inventory items"](https://docs.microsoft.com/en-us/dynamics365-release-plan/2021wave2/smb/dynamics365-business-central/locations-non-inventory-items) feature.

**Comment by grantbrimhall** [comment]
Hi Oleg:

I understand that it was made in the scope of enable location for non-inventory items ... but the create inventory pick report is now broken when location exists (so whoever made that feature didn't do a good job of testing inventory picks).

Anyway, why not write the event with a typical if IsHandled then exit:

    IsHandled := false;
    OnBeforeUpdateLocationCode(Rec, IsHandled);
    if IsHandled then
        exit;
    "Location Code" := SalesHeader."Location Code"

thanks.

@Oleg-Romashkov

**Comment by Oleg-Romashkov** [comment]
Hi,

I agree, second call will be fixed.

**Comment by Oleg-Romashkov** [comment]
If you have problems with Report 7323 scenarios then you need to create a bug for partner support system.

**Comment by grantbrimhall** [comment]
thx Oleg. yes they were the first one I bugged. then I tried to fix using events, and saw this event had changed. and then I wrote this issue. thanks for your help.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
