### ISSUE TITLE
[Code Improvement] table 900 "Assembly Header" - procedure ShowDueDateBeforeWorkDateMsg

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#15331]
hey,

It's about the warning message in the function. This is also displayed although the remaining quantity is zero. It would be nice if you could include the code improvement mentioned below.

table 900 "Assembly Header"
procedure ShowDueDateBeforeWorkDateMsg

Before:
![image](https://user-images.githubusercontent.com/34685182/143397247-4261c359-eb90-4fd6-a7f6-b155f4a32456.png)

After:
![Unbenannt](https://user-images.githubusercontent.com/34685182/143397140-13527a47-98ea-4902-81fb-84626793a7be.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
