### ISSUE TITLE
In the Codeunit "Over-Receipt Mgt" all functions are only available on OnPrem

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#15348]
Hi al-team, 

is it intended that all functions in the code unit "Over-Receipt Mgt" are only available on OnPrem?

![image](https://user-images.githubusercontent.com/48024891/143545005-1581ef7c-cbd9-4b59-aaf1-68bd53eb1c0b.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
