### ISSUE TITLE
Bug? RSACryptoServiceProviderImpl.Codeunit.al - Is there an Exit(...) in VerifyData missing? 

### ISSUE THREAD

**Issue by sackpost** [microsoft/ALAppExtensions#15342]
https://github.com/microsoft/ALAppExtensions/blob/935155845bf45b631d1c34b6bcd5aec54308d50f/Modules/System/Cryptography%20Management/src/RSACryptoServiceProviderImpl.Codeunit.al#L60

I want to change the following code 
```
var RSAKey: DotNet RSACryptoServiceProvider;
 ... 

RSAKey := RSAKey.Create();
RSAKey.FromXmlString(GetPublicKey());
result := RSAKey.VerifyData(bLicFile, 'SHA1', bSignature);
```
to 
```
var  RSACryptoServiceProvider: Codeunit RSACryptoServiceProvider;
...
result := RSACryptoServiceProvider.VerifyData(GetPublicKey(), DataIStream, HashAlgo::SHA1, SignatureIStream);
```
And in the second section the result ist always false! And I think, that in line 60 of RSACryptoServiceProviderImpl.Codeunit.al an `Exit( )` fixes the problem.

**Comment by sackpost** [comment]
My  fix 

```
    #region VerifyData
    // [NonDebuggable]
    procedure VerifyData(XmlString: Text; DataInStream: InStream; HashAlgorithm: Enum "Hash Algorithm"; SignatureInStream: InStream): Boolean
    var
        Verified: Boolean;
    begin
        FromXmlString(XmlString);
        Verified := VerifyData(DataInStream, HashAlgorithm, SignatureInStream);
        exit(Verified);
    end;
```

works in my local environment. Suprisly an `Exit(VerifyData(DataInStream, HashAlgorithm, SignatureInStream))` does not work.

**Comment by sackpost** [comment]
My environment: 

- Application 18.7.31790.0
- System 18.0.31692.0

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.

**Comment by sackpost** [comment]
Is this bug also fixed in version 18.x?
