### ISSUE TITLE
[Request for external] - table 38 "Purchase Header" GetUserSetupPurchaserCode

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#15346]
Can you change procedure GetUserSetupPurchaserCode in purchase header to global?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
