### ISSUE TITLE
fieldgroup request: "Country/Region"

### ISSUE THREAD

**Issue by Katarina-BS** [microsoft/ALAppExtensions#15349]
Please add fieldgroup DropDown to table "Country/Region" so we can extend it.
Best regards,
Katarina

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
