### ISSUE TITLE
[Event Request] table 7001 "Price List Line" - OnBeforeVerify 

### ISSUE THREAD

**Issue by PatrickSchiefer** [microsoft/ALAppExtensions#15340]
In some cases it is necessary to change the standard behaviour of the Verify function

```
procedure Verify()
var
    isHandled : Boolean;
begin
    OnBeforeVerify(Rec, isHandled);
    if isHandled then
       exit;
    VerifySource();
    TestField("Asset Type");
end;
```

Event Signature:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeVerify(var PriceListLine: Record "Price List Line", var isHandled)
begin
end;
```

**Comment by PatrickSchiefer** [comment]
We would need the Event in BC18

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
