### ISSUE TITLE
[Code Defect] Empty Routing Line with Comment/Tool/Personnel/Quality Measure

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#15341]
hey,

It is currently possible to enter a new empty line for certified routing lines and to store tools, comments, personnel and test measures for this empty line. That should be prevented.

CRONUS database:
1. Open the first certified routing
2. Go to the last routing line and create a new line
3. click one of the buttons (ex. comments)
4. Add comments

The comments now refer to operation no. 0.

related tables:
Table	99000775	Routing Comment Line
Table	99000802	Routing Tool
Table	99000803	Routing Personnel
Table	99000805	Routing Quality Measure

The field "Operation No." in the tables is setted to NotBlank = true, but this property is ignored in integer values.

Please add a testfield for the opertaion no. in the insert triggers of the tables or switch the subform to editable no, in case the routing header is certified.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
