### ISSUE TITLE
[Event Request] Page 11310 "General Ledger Entries Apply" - OnAfterSetIncludeEntryFilter

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#15350]
Hello,

We would need a new event **OnAfterSetIncludeEntryFilter** on page 11310 "General Ledger Entries Apply":

    internal procedure SetIncludeEntryFilter()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetIncludeEntryFilter(Rec, IncludeEntryFilter, IsHandled);
        if IsHandled then
            exit;

        SetCurrentKey("G/L Account No.", "Posting Date", "Entry No.", Open);
        case IncludeEntryFilter of
            IncludeEntryFilter::All:
                SetRange(Open);
            IncludeEntryFilter::Open:
                SetRange(Open, true);
            IncludeEntryFilter::Closed:
                SetRange(Open, false);
        end;

        OnAfterSetIncludeEntryFilter(Rec, IncludeEntryFilter); // new event
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetIncludeEntryFilter(var GLEntryApplicationBuffer: Record "G/L Entry Application Buffer"; var IncludeEntryFilter: Option)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
