### ISSUE TITLE
[Event Request] Application “Tests-ERM” Codeunit 136101 "Service Orders"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#15356]
[Event Request]Application “Tests-ERM”, 136101 "Service Orders"

Could you please insert the Initialize procedure at the beginning of test procedure CorrectCalculationLineDiscountForServiceLineWithSalesPrice
![pic1](https://user-images.githubusercontent.com/45795262/143605205-b89204d3-b0f4-4df6-a304-097857ae2897.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
