### ISSUE TITLE
[Event Request] Application “Tests-Local” Codeunit 142078 "Test Vat VIES Declaration"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#15357]
[Event Request]Application “Tests-Local”, 142078 "Test Vat VIES Declaration"

Could you please insert the Event OnTestInitialize at the beginning of the procedure Initialize
![pic1](https://user-images.githubusercontent.com/45795262/143605422-85abdc28-ced7-4ff2-87b6-20d76d3a1c49.png)
?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
