### ISSUE TITLE
[Event Update Request] Table 295 "Reminder Header" - OnInsertLinesOnAfterCalcAdditionalFee

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#15353]
In the following event request: https://github.com/microsoft/ALAppExtensions/issues/14383, we requested the event OnInsertLinesOnAfterCalcAdditionalFee in the "Reminder Header" table.
We see that Microsoft implemented this event, but without the var parameter on the "Reminder Header" Record. 
We would like to request Microsoft to change the event OnInsertLinesOnAfterCalcAdditionalFee with a var parameter on the "Reminder Header" record.

    [IntegrationEvent(false, false)]
    local procedure OnInsertLinesOnAfterCalcAdditionalFee(var ReminderHeader: Record "Reminder Header"; ReminderLevel: Record "Reminder Level"; var AdditionalFee: Decimal)
    begin
    end;

**Comment by CameliaPopescu** [comment]
I checked in 19.1.31886.32889 version and the ReminderHeader parameter is with var. You can close the ticket.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
