### ISSUE TITLE
[Event Request] T5050 Contact - procedure UpdateQuotesFromTemplate()

### ISSUE THREAD

**Issue by tguyonnet** [microsoft/ALAppExtensions#15354]
```
------- ADD PARAMETER : Rec ---------

OnBeforeUpdateQuotesFromTemplate(Rec, Customer, CustomerTemplateCode, IsHandled);


    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateQuotesFromTemplate(var Contact: Record Contact; Customer: Record Customer; CustomerTemplateCode: Code[20]; var IsHandled: Boolean)
    begin
    end;


```

**Comment by dnpb** [comment]
you presumably mean

`OnBeforeUpdateQuotesFromTemplate(Rec, Customer, CustomerTemplateCode, IsHandled);`

i.e. to pass `Rec`, not a record variable `Contact`, which does not exist here.

**Comment by tguyonnet** [comment]
Yeah thx!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
