### ISSUE TITLE
[Event Request] Application “Tests-Marketing” Codeunit 134626 "Person and Company Contacts"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#15358]
[Event Request]Application “Tests-Marketing”, 134626 "Person and Company Contacts"

Could you please insert the Event OnTestInitialize at the beginning of the procedure Initialize
![pic1](https://user-images.githubusercontent.com/45795262/143605573-b0f7ea37-4214-4064-9563-93f64a6fbc3c.png)
?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
