### ISSUE TITLE
[Event Request] Application “Tests-VAT” Codeunit 134130 "ERM Reverse And VAT Settlement"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#15359]
[Event Request]Application “Tests-VAT”, 134130 "ERM Reverse And VAT Settlement"

Could you please insert the Event OnTestInitialize at the beginning of the procedure Initialize
![pic1](https://user-images.githubusercontent.com/45795262/143605823-de179b53-3540-435e-8a29-f8f11b85a877.png)
?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
