### ISSUE TITLE
[Request for access to Proteced vars] page 7138 "Purchase Budget Overview"

### ISSUE THREAD

**Issue by VNOVAL** [microsoft/ALAppExtensions#15360]
We would like to request for access a few protected vars:

protected var
    CurrentBudgetName: Code[10];
    LineDimCode: Text[30];
    ColumnDimCode: Text[30];
    ValueType: Option, "Cost Amount", Quantity;
    PeriodType: Option Day, Week, Month, Quarter, Year, "Accounting Period";
    RoundingFactor: Option None, "1", "1000", "1000000";
    ShowColumnName: Boolean;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
