### ISSUE TITLE
[Event Request] Employee Templ. Mgt.

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#15367]
Hello,

Please add new event to codeunit 1387 "Employee Templ. Mgt."
procedure ApplyTemplate
`OnAfterApplyTemplateBeforeModify(var Employee: Record Employee;EmployeeTempl: Record "Employee Templ.")`
procedure InsertTemplateFromEmployee
`OnAfterInsertTemplateFromEmployeeBeforeInsert(var EmployeeTempl: Record "Employee Templ."; Employee: Record Employee)`

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
