### ISSUE TITLE
[Event Request] 1250 "Match General Journal Lines"

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#15364]
OnAfterOnRun(Rec) at the end of the function OnRun

`OnAfterOnRun(var GenJnlLine: Record "Gen. Journal Line")`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
