### ISSUE TITLE
[Request-For-External] Table 5741 "Transfer Line" - Variable StatusCheckSuspended

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#15375]
Hi, could you please make the value of the global variable **StatusCheckSuspended** available with a getter in table 5741 (**Transfer Line**), like this:
```AL
    procedure GetStatusCheckSuspended() : Boolean
    begin
        exit(StatusCheckSuspended);
    end;
```
Also, maybe it makes sense to add the **protected** keyword to the **StatusCheckSuspended** variable.

_Note_: both of these changes are already added to table 36 (**Sales Header**), table 37 (**Sales Line**), table 38 (**Purchase Header**), table 39 (**Purchase Line**). Just a small difference is the procedure/variable name.
#6310 #11257

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
