### ISSUE TITLE
[Event Request]  codeunit 351 "Intrastat Document Completion"

### ISSUE THREAD

**Issue by jthoerner-tso** [microsoft/ALAppExtensions#15389]
Hi BC - Team

would it be possible to add new event publishers in codeunit 351 "Intrastat Document Completion"?
BC 19.0 German localisation

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterDefaultSalesDocuments(var SalesHeader: Record "Sales Header"; IntrastatSetup: Record "Intrastat Setup")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterDefaultPurchaseDcouments(var PurchaseHeader: Record "Purchase Header"; IntrastatSetup: Record "Intrastat Setup")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterDefaultServiceDocuments(var ServiceHeader: Record "Service Header"; IntrastatSetup: Record "Intrastat Setup")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
