### ISSUE TITLE
[Code Improvement] Dispatch Board - remove "Date Filter" to yesterday

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#15388]
hey,

Resources for future orders are to be planned via the dispatch board. 
Therefore it makes no sense to set a date filter to yesterday. 
If this filter is set, it causes an incorrect display of the assigned resources that are planned in the future.

The "problem" is in the table 5900 "Service Header".
```

    procedure SetSecurityFilterOnRespCenter()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetSecurityFilterOnRespCenter(Rec, IsHandled);
        if IsHandled then
            exit;

        if UserSetupMgt.GetServiceFilter() <> '' then begin
            FilterGroup(2);
            SetRange("Responsibility Center", UserSetupMgt.GetServiceFilter());
            FilterGroup(0);
        end;

        SetRange("Date Filter", 0D, WorkDate - 1);  <--- Please remove the line
    end;
```

I would be happy if you can change that.
Best regards!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
