### ISSUE TITLE
[Event Request] Report 5706 "Create Stockkeeping Unit" - OnBeforeStockkeepingUnitInsert

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#15387]
Hi, would it be possible to modify the **OnBeforeStockkeepingUnitInsert** event in report 5706 (**Create Stockkeeping Unit**) by adding the **IncludeSender**, like this:
```AL
    [IntegrationEvent(true, false)]
    local procedure OnBeforeStockkeepingUnitInsert(var StockkeepingUnit: Record "Stockkeeping Unit"; Item: Record Item)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
