### ISSUE TITLE
[Request-For-External] Report 594 "Get Item Ledger Entries" - RequestPage Variables

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#15396]
Hi, could you please change the protection level of the following variables on report 594 (**Get Item Ledger Entries**) to a **protected**: **StartDate**, **EndDate**, **IndirectCostPctReq**, **SkipRecalcZeroAmounts**, **SkipZeroAmounts**, **ShowItemCharges**?
```AL
    protected var
        StartDate: Date;
        EndDate: Date;
        IndirectCostPctReq: Decimal;
        SkipRecalcZeroAmounts: Boolean;
        SkipZeroAmounts: Boolean;
        ShowItemCharges: Boolean;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
