### ISSUE TITLE
[Event Request] Codeunit ServContractManagement Event  "OnBeforeUpdateServLedgEntryAmounts" Missing VAR

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#15397]
InvRoundedAmount doesn't have a "var" - therefore every calculation is effectless... Please add "var":

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateServLedgEntryAmounts(var ServiceContractLine: Record "Service Contract Line"; var ServLedgEntry: Record "Service Ledger Entry"; **var** InvRoundedAmount: array[4] of Decimal; LineInvoiceFrom: Date; InvoiceTo: Date; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
