### ISSUE TITLE
[Event Change] Table 5050 - Contact - OnAfterSetTypeForContact

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#15392]
Hi AL-Team,

can you please add the xRec as parameter in Event-Publisher **OnAfterSetTypeForContact** as shown below:

```
[IntegrationEvent(false, false)]
local procedure OnAfterSetTypeForContact(var Contact: Record Contact; xContact: Record Contact)
begin
end;
```

```
OnAfterSetTypeForContact(Rec); 
OnAfterSetTypeForContact(Rec,xRec); // New
```
Thank you in advance,
Christian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
