### ISSUE TITLE
[Event Change] Report 20 "Calc. and Post VAT Settlement" - OnCloseVATEntriesOnAfterPostGenJnlLineReverseChargeVATSales

### ISSUE THREAD

**Issue by peter555555546** [microsoft/ALAppExtensions#15395]
Hey
currently there is no way to reflect the changes from custom code on the report itself using the event `OnCloseVATEntriesOnAfterPostGenJnlLineReverseChargeVATSales`
can you please add GenJnlLine2 to the event `OnCloseVATEntriesOnAfterPostGenJnlLineReverseChargeVATSales`, also change GenJnlLine to be passed as reference?

Old:
```
[IntegrationEvent(false, false)]
    local procedure OnCloseVATEntriesOnAfterPostGenJnlLineReverseChargeVATSales(var VATEntry: Record "VAT Entry"; GenJnlLine: Record "Gen. Journal Line"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; VATPostingSetup: Record "VAT Posting Setup"; PostSettlement: Boolean; var ReversingEntry: Boolean; DocNo: Code[20]; PostingDate: Date)
    begin
    end;
```

New:
```
    [IntegrationEvent(false, false)]
    local procedure OnCloseVATEntriesOnAfterPostGenJnlLineReverseChargeVATSales(var VATEntry: Record "VAT Entry"; var GenJnlLine: Record "Gen. Journal Line"; var GenJnlLine2: Record "Gen. Journal Line"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; VATPostingSetup: Record "VAT Posting Setup"; PostSettlement: Boolean; var ReversingEntry: Boolean; DocNo: Code[20]; PostingDate: Date)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
