### ISSUE TITLE
9064 "Stor. Serv. Auth. Shared Key" generates invalid keys for IT databases

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#15409]
The codeunit 9064 "Stor. Serv. Auth. Shared Key" is responsible for generating the shared key used for storage service authentication. Specifically: the function `GetSharedKeySignature`. This function uses the label `SignaturePlaceHolderLbl` as a placeholder string where the two parts (account name & key) are then filled in via `StrSubstNo`. This label however does not have the `Locked` property set and is therefore translated in the various localizations.

In the IT version platform 19.0.29884.30666 + application 19.0.29894.30693 this label is translated wrong (a space is added before the colon). 

Therefore using an IT database in IT language causes the access key header to be wrong and essentially makes all storage operation calls fail.

![image](https://user-images.githubusercontent.com/8897936/144090335-ee693d14-0d18-4074-b378-b9cf2716abce.png)

This label should not be translated and therefore have the `Locked` property set.

**Comment by darjoo** [comment]
I'll close this bug as we will process the PR :)
