### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" OnBeforePostItemCharge - Missing var, procs global

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#15401]
To handle credit value memos and other specialities of sales post (like for service) we need to have the variable "TempItemChargeAssignmentSales" marked as var. It's important for value entries. 

Additionally the procedures "CopyItemChargeForSalesLine" and "CopyAndCheckItemCharge" to be global to reduce duplicate code and ensure correct postings. 

```
[IntegrationEvent(false, false)]
local procedure OnBeforePostItemCharge(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; **var** TempItemChargeAssignmentSales: Record "Item Charge Assignment (Sales)" temporary; ItemLedgEntryNo: Integer)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
