### ISSUE TITLE
[Event Request] Table 5405 "Production Order" - OnModifyOnBeforeStatusCheck

### ISSUE THREAD

**Issue by OlegKulyk86** [microsoft/ALAppExtensions#15415]
Hi, would it be possible to get an **OnModifyOnBeforeStatusCheck** event in table 5405 (**Production Order**), like this:

```al
    trigger OnModify()
    var
        IsHandled: Boolean;
    begin
        "Last Date Modified" := Today;
        // New Event begin
        IsHandled := false;
        OnModifyOnBeforeStatusCheck(Rec,xRec,IsHandled);
        if not IsHandled then
        // New Event end
        if Status = Status::Finished then
            Error(Text006);
    end;
```
```al
    [IntegrationEvent(false, false)]
    local procedure OnModifyOnBeforeStatusCheck(var ProductionOrder: Record "Production Order"; xProductionOrder: Record "Production Order"; var IsHandled: Boolean)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
