### ISSUE TITLE
[Event Request] codeunit 7002 "Price Calculation - V16" implements "Price Calculation"

### ISSUE THREAD

**Issue by InnoNavSupport** [microsoft/ALAppExtensions#15425]
Please enter the OnBeforePickBestLine-Event
![grafik](https://user-images.githubusercontent.com/62563638/144235850-98993803-d318-4e7e-bbe3-d006d0db67fb.png)

![grafik](https://user-images.githubusercontent.com/62563638/144236014-11fef4a2-1c36-458f-8603-a05e86df1bad.png)

**Comment by Stepanenko-Vadim** [comment]
Please use text instead of screenshots when requesting events in the future.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
