### ISSUE TITLE
Request for external/public procedures - page 6510 "Item Tracking Lines" -     local procedure LotNoInfoCardAction(LotNo: Code[50]) and local procedure SerialNoInfoCardAction(SerialNo: Code[50])

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15423]
These methods are called by various actions to open the relevant Serial/Lot No Info pages, while ensuring they are Init()d from the current Item Tracking Line (Rec).

We are adding new fields to the Lot No Information table. We want them to be editable via the Item Tracking Lines list. It would be good to add AssistEdit buttons to the fields so that the Lot No Info Card would be quickly available from the Item Tracking Lines page fields. We would of course want to open said Card by calling the same code that your standard actions do. The same might be for Serials later.

Therefore can you please make these functions publically callable, so that we don't have to copy/paste them? Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
