### ISSUE TITLE
[Extensibility enhancements] Validate complete Workflow Event Conditions on enabling Workflow

### ISSUE THREAD

**Issue by elweilando** [microsoft/ALAppExtensions#15421]
In the event conditions of a purchase approval workflow, I have the possibility to set a filter on the purchase header and on the purchase line.

The use case is that our customer will run separate approval workflows, they depend on information in the purchase header and in the purchase line. e.g. only open purchase order with specific items with a specific quantity. The default gives me the possibility to set this scenario.

This scenario based on the default approval workflow for purchase orders.

If I try to enable these workflows, I receive the error that "One or more entry-point steps exist that use the same event on table Purchase Header. You must specify unique event conditions on entry-point steps that use the same table."

There are no other workflows.
Workflow A: Purchase Header, Status: Open | Purchase Line, Quantity 8
Workflow B: Purchase Header, Status: Open | Purchase Line, Quantity <>8

For the Purchase header, it's true. I filter only on open Purchase Headers with Type Order. 

But for the condition for the workflow it's wrong because the condition for the workflow is the filter on the purchase header AND on the purchase line. And not only the first record in condition.

If Business Central gives us the possibility to define a "more than one record" workflow condition, it should also be possible to uses this.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
