### ISSUE TITLE
request for protected variables - page 167 "Item Ledger Entries Preview" - ItemTrackingVisible, PackageTrackingVisible: Boolean

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15427]
We are extending the Item Ledger Entry table with additional Lot/Tracking related fields. We would like to show these in the Preview. We want to use the same logic as the standard fields, which use this variable to show/hide the fields as relevant:

![image](https://user-images.githubusercontent.com/63455896/144237928-5f857dae-eb81-459b-992c-2a75ba807125.png)

We of course don't want to have to duplicate all your complex code that sets these. Thus can you please make them protected, so that our page extension adding the fields can use your exact logic to determine whether to show them?

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
