### ISSUE TITLE
Additional information 15332

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#15429]
In the issue #15332 We requested the event
    >>>OnAfterInitRecord(CBGStatement);<<<
    
 But since we want to modify the original CBG statement it should use of course the Rec paramter
     >>>OnAfterInitRecord(Rec);<<<

We do not want to modify the other CBG Statements

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
