### ISSUE TITLE
[Event Request] Events #10515, #10523, #10524 still not available

### ISSUE THREAD

**Issue by chliebich** [microsoft/ALAppExtensions#15433]
There are some event requests that have the tag _ships-infuture-update_ but have still not been delivered with bc19.1. When will these events be published? The following events are still not available with BC19.1:
#10515 [Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnApplyVendLedgEntryOnBeforeUnrealizedVAT
#10523 [Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnCustPostApplyCustLedgEntryOnAfterCustLedgEntryTransferFields
#10524 [Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnVendPostApplyVendLedgEntryOnAfterVendLedgEntryTransferFields

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
