### ISSUE TITLE
API fails when exposing Production orders

### ISSUE THREAD

**Issue by JanSkrubbeltrang** [microsoft/ALAppExtensions#15430]
When trying to make an extension including custom API it fails with "Sequence contains more than one matching element" when exposing Production Order (table 5405) 

Github project to reproduce error: https://github.com/JanSkrubbeltrang/AL-ProdOrderApiFail

**Comment by JanSkrubbeltrang** [comment]
Testet on 
18.3 DK
18.3 W1 
19.1 DK
19.1 W1

All show the same behavior, all endpoints in that API group fails with the "Sequence contains more than one matching element" error

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
