### ISSUE TITLE
[Extensibility Enhancement] Codeunit 365 - Format Address - Pass "Country/Region Code" in Company procedure

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#15432]
Dear ALAppExtensions team,

Through this issue we would like to request the `CompanyInfo."Country/Region Code"` to be passed to the `FormatAddr` procedure in the `Company` procedure so that we can get the Country/Region name for company address blocks.

We suggest the following change:
```al
    procedure Company(var AddrArray: array[8] of Text[100]; var CompanyInfo: Record "Company Information")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCompany(AddrArray, CompanyInfo, IsHandled);
        if IsHandled then
            exit;

        with CompanyInfo do
            FormatAddr(
              AddrArray, Name, "Name 2", '', Address, "Address 2",
              // City, "Post Code", County, '');                                       // OLD
              City, "Post Code", County, "Country/Region Code");                       // NEW
    end;
```

**Comment by dnpb** [comment]
Great point. We have noticed this in the past and also wondered if it could be changed/improved. It would definitely be far better for extensibility. Currently we have to copy and paste the code and handle it ourselves, which of course is never ideal.

**Comment by AlexanderYakunin** [comment]
I think this is done on purpose, cause procedure FormatAddress use settings from General Ledger Setup for local address format if CountryCode is blank. And this is exactly what we need for Company address. If we use non blank CountryCode, same settings will be taken from Country/Region record. 

So I would not go for this change without very strong reasons.

**Comment by dnpb** [comment]
Hm, that seems like a good point; I don't think I consciously knew of that G/L Setup field when I made our version of `FormatAddress.Company()` use the Company Info country/region code.
