### ISSUE TITLE
[EventRequest] Codeunit 99000813 "Carry Out Action" procedure "InsertAsmHeader"

### ISSUE THREAD

**Issue by tdkumar** [microsoft/ALAppExtensions#15435]
We have customization to get BOM Components of the Type::Resource from the custom table. Need an event in Codeunit 99000813 "Carry Out Action" procedure "InsertAsmHeader".

    procedure InsertAsmHeader(ReqLine: Record "Requisition Line"; var AsmHeader: Record "Assembly Header")
    var
        BOMComp: Record "BOM Component";
        Item: Record Item;
    begin
        Item.Get(ReqLine."No.");
        AsmHeader.Init();
        AsmHeader."Document Type" := AsmHeader."Document Type"::Order;
        OnInsertAsmHeaderOnBeforeAsmHeaderInsert(AsmHeader, ReqLine);
        AsmHeader.Insert(true);
        OnInsertAsmHeaderOnAfterAsmHeaderInsert(AsmHeader, ReqLine);
        AsmHeader.SetWarningsOff;
        AsmHeader.Validate("Item No.", ReqLine."No.");
        AsmHeader.Validate("Unit of Measure Code", ReqLine."Unit of Measure Code");
        AsmHeader.Description := ReqLine.Description;
        AsmHeader."Description 2" := ReqLine."Description 2";
        AsmHeader."Variant Code" := ReqLine."Variant Code";
        AsmHeader."Location Code" := ReqLine."Location Code";
        AsmHeader."Inventory Posting Group" := Item."Inventory Posting Group";
        AsmHeader.Validate("Unit Cost", ReqLine."Unit Cost");
        AsmHeader."Due Date" := ReqLine."Due Date";
        AsmHeader."Starting Date" := ReqLine."Starting Date";
        AsmHeader."Ending Date" := ReqLine."Ending Date";

        AsmHeader.Quantity := ReqLine.Quantity;
        AsmHeader."Quantity (Base)" := ReqLine."Quantity (Base)";
        AsmHeader.InitRemainingQty;
        AsmHeader.InitQtyToAssemble;
        if ReqLine."Bin Code" <> '' then
            AsmHeader."Bin Code" := ReqLine."Bin Code"
        else
            AsmHeader.GetDefaultBin;

        AsmHeader."Planning Flexibility" := ReqLine."Planning Flexibility";
        AsmHeader."Shortcut Dimension 1 Code" := ReqLine."Shortcut Dimension 1 Code";
        AsmHeader."Shortcut Dimension 2 Code" := ReqLine."Shortcut Dimension 2 Code";
        AsmHeader."Dimension Set ID" := ReqLine."Dimension Set ID";
        ReqLineReserve.TransferPlanningLineToAsmHdr(ReqLine, AsmHeader, ReqLine."Net Quantity (Base)", false);
        if ReqLine.Reserve then
            ReserveBindingOrderToAsm(AsmHeader, ReqLine);
        AsmHeader.Modify();

        TransferAsmPlanningComp(ReqLine, AsmHeader);

	**// > New event**
        OnBeforeAddResourceComponents(ReqLine, AsmHeader, IsHandled)
        if not IsHandled then begin
        **// < New event**
        BOMComp.SetRange("Parent Item No.", ReqLine."No.");
        BOMComp.SetRange(Type, BOMComp.Type::Resource);
        if BOMComp.Find('-') then
            repeat
                AsmHeader.AddBOMLine(BOMComp);
            until BOMComp.Next() = 0;
        end; **// New event**

        OnAfterInsertAsmHeader(ReqLine, AsmHeader);

        PrintAsmOrder(AsmHeader);
        TempDocumentEntry.Init();
        TempDocumentEntry."Table ID" := DATABASE::"Assembly Header";
        TempDocumentEntry."Document Type" := AsmHeader."Document Type"::Order;
        TempDocumentEntry."Document No." := AsmHeader."No.";
        TempDocumentEntry."Entry No." := TempDocumentEntry.Count + 1;
        TempDocumentEntry.Insert();
    end;

**// > New event**
[IntegrationEvent(false, false)]
        local procedure OnBeforeAddResourceComponents(ReqLine: Record "Requisition Line"; var AsmHeader: Record "Assembly Header"; var IsHandled: Boolean)
        begin
        end;
**// < New event**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
