### ISSUE TITLE
[Enum Request] - FA Posting Type Setup -"FA Posting Type" 

### ISSUE THREAD

**Issue by CPNCST** [microsoft/ALAppExtensions#15439]
Hello everyone, 

Could you please convert "FA Posting Type" into a enum? 

![image](https://user-images.githubusercontent.com/35273761/144567503-e57d0c78-6377-4e18-8a0e-6473b09342d7.png)

Thanks in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
