### ISSUE TITLE
[Event Request] table 225 "Post Code" - Change UseDialog to var

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#15446]
Could you please change the Parameter `UseDialog` in the following to `var`?

```al
[IntegrationEvent(true, false)]
local procedure OnBeforeValidatePostCode(var CityTxt: Text[30]; var PostCode: Code[20]; var CountyTxt: Text[30]; var CountryCode: Code[10]; var UseDialog: Boolean; var IsHandled: Boolean)
begin
end;
```

```al
[IntegrationEvent(true, false)]
local procedure OnBeforeValidateCity(var CityTxt: Text[30]; var PostCode: Code[20]; var CountyTxt: Text[30]; var CountryCode: Code[10]; var UseDialog: Boolean; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
