### ISSUE TITLE
OnAfterCopyItemJnlFromStdJnl wrong parameter

### ISSUE THREAD

**Issue by acicatech** [microsoft/ALAppExtensions#15444]
event "OnAfterCopyItemJnlFromStdJnl" in Table 752 "Standard Item Journal" is exposing "Standard Item Journal" table in order to pass custom fields to destination "Item Journal Line" table , but the correct param must be "Standard Item Journal Line" table not "Standard Item Journal"

Old Code : 

```
 [IntegrationEvent(false, false)]
    local procedure OnAfterCopyItemJnlFromStdJnl(var ItemJournalLine: Record "Item Journal Line"; var StandardItemJournal: Record "Standard Item Journal")
    begin
    end;
```

Sugested Code :

```
 [IntegrationEvent(false, false)]
    local procedure OnAfterCopyItemJnlFromStdJnl(var ItemJournalLine: Record "Item Journal Line"; var StandardItemJournalLine: Record "Standard Item Journal Line")
    begin
    end;
```

**Comment by dnpb** [comment]
Well, that is what [you asked for](https://github.com/microsoft/ALAppExtensions/issues/12646) ;-)

**Comment by acicatech** [comment]
Yes , sorry for mistake , the concept was well , but the name of the table not.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
