### ISSUE TITLE
[Enum Request] - Cost Allocation Target - "Data Filter Code"

### ISSUE THREAD

**Issue by CPNCST** [microsoft/ALAppExtensions#15441]
Hello everyone, 

Could you please convert "Date Filter Code" into a enum? 

![image](https://user-images.githubusercontent.com/35273761/144568064-d8ca85f4-f62c-4f04-868b-9932b2c43db2.png)

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
