### ISSUE TITLE
event parameter request - codeunit 99000834 "Purch. Line-Reserve" - OnCallItemTrackingOnBeforeItemTrackingFormRunModal() - var IsHandled: Boolean

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15445]
We have a need to use `CallItemTracking()` and from there `ItemTrackingLines.GetTracking(var TempTrackingSpecification)`, so that we can use the latter record to determine the tracking lines that would be shown on the page, to then update Lot Info records based on them.

Anyway, the point of all that is that we don't actually want to do the final `ItemTrackingLines.RunModal()` in this case. So we want a way to block it. That is: without having to e.g. set some Boolean in the page extension, make it `Error()` in `OnOpenPage()` and hope that still commits... etc.

Thus can you please add the `var IsHandled: Boolean` pattern to the event publisher, and `if IsHandled then` do **not** do the `RunModal()`? Thanks!

![image](https://user-images.githubusercontent.com/63455896/144601890-3b3da646-f1f9-4ee5-92dd-5bd403c4b813.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
