### ISSUE TITLE
[Event Request] report 5753 "Get Source Documents" update OnAfterProcessDocumentLine

### ISSUE THREAD

**Issue by vovazvv** [microsoft/ALAppExtensions#15448]
Please add the parameter **WhseReceiptHeader**: Record "Warehouse Receipt Header" to the event **OnAfterProcessDocumentLine**
Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
