### ISSUE TITLE
DK:OIOUBL Supported receiver countries missing: Greenland and The Faroe Islands

### ISSUE THREAD

**Issue by ERPgruppenMW** [microsoft/ALAppExtensions#15443]
Hi,
In procedure IsValidCountryCode, in CU DocumentEncode.Codeunit.al country must be equal to companysetup. This gives error when trying to invoice between Denmark, Greenland and The Faroe Islands.

**Comment by Oleg-Romashkov** [comment]
Hi,
Thank you for reaching out. Your request could be reporting as a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
