### ISSUE TITLE
Make variables in "Combine Shipments" protected

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#15451]
Hi, 
can you make these variables in report 295 "Combine Shipments" protected?

```
PostingDate
DocDateReq
CalcInvDisc
PostInv
OnlyStdPmtTerms
CopyTextLines
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
