### ISSUE TITLE
[Request-For-External] Report 594 "Get Item Ledger Entries" - Global Variables

### ISSUE THREAD

**Issue by OlegKulyk86** [microsoft/ALAppExtensions#15454]
Hi, could you please change the protection level of the **IntrastatJnlBatch** variable on report 594 (**Get Item Ledger Entries**) to a protected?

```al
    protected var
        IntrastatJnlBatch: Record "Intrastat Jnl. Batch";
```
https://github.com/microsoft/ALAppExtensions/issues/15396
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
