### ISSUE TITLE
Task Scheduler permissions for S2S Authentication (OAuth)

### ISSUE THREAD

**Issue by legrlion** [microsoft/ALAppExtensions#15458]
Hello,

Since basic authentication will be deprecated very soon, we try to implement **S2S authentication (OAuth)** for our Business Central API.

When creating a record in an entity of this API, our process needs to create a task in **Task Scheduler** to execute some code asynchronously.
Everything works fine with basic authentication (User Name and Web Access Key).

**When we try this with S2S, we got the following error:**
> “You do not have permission to create or run scheduled tasks.”

As mentioned in the [Task Scheduler help](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-task-scheduler#about-task-sessions-and-permissions), it seems that  users should have appropriated permissions to execute tasks.
> The session runs by using the same user/credentials that are used when calling AL code. The user must have appropriate permissions to the codeunit and any other objects that are associated with the operation of the codeunit.

We tried to set full permissions for the user (SUPER is not allowed, so we created a copy of SUPER, with the same rights, only for test purposes), but nothing changes.
![image](https://user-images.githubusercontent.com/51998770/144876369-f05f17da-ef43-47c9-bd1a-33626853113f.png)

![image](https://user-images.githubusercontent.com/51998770/144875599-f1c87c13-0996-4595-aa86-4f36169a41e8.png)

**Business Central version: 19.0.29894.30403
Business Central environment type: Sandbox (SaaS)**

Does-we missed something in the configuration ?
Is there any restrictions to use Task Scheduler from an API with S2S ?

Thanks in advance for your help.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz - can you help?

**Comment by henrikwh** [comment]
Hi @legrlion 
With S2S, you cannot run scheduled tasks. Scheduled tasks always need to run in the context of a licensed user (that is also way delagted admins and helpdesk users cant run scheduled tasks). For security reasons, its not allowed for an app to schedule tasks.
You would need and api, which you could call to trigger the same logic as you currently want to trigger from the scheduled task.

**Comment by JesperSchulz** [comment]
Thanks for picking this one up, @henrikwh.
