### ISSUE TITLE
[Event Request] table 38 "Purchase Header" OnAfterSetBuyFromVendorFromFilter

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#15459]
Can you add event OnAfterSetBuyFromVendorFromFilter in table 38 "Purchase Header"?

Rec as reference
```
    procedure SetBuyFromVendorFromFilter()
    var
        BuyFromVendorNo: Code[20];
    begin
        BuyFromVendorNo := GetFilterVendNo;
        if BuyFromVendorNo = '' then begin
            FilterGroup(2);
            BuyFromVendorNo := GetFilterVendNo;
            FilterGroup(0);
        end;
        if BuyFromVendorNo <> '' then
            Validate("Buy-from Vendor No.", BuyFromVendorNo);

        // >>>>>>>>>>>>>>>>
        OnAfterSetBuyFromVendorFromFilter(Rec);
        // <<<<<<<<<<<<<<<<
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
