### ISSUE TITLE
[Event Parameter Request] Table 39 - "Purchase Line"- OnBeforeCheckPrepmtAmtInvEmpty

### ISSUE THREAD

**Issue by chliebich** [microsoft/ALAppExtensions#15453]
Please add the following parameter for the event OnBeforeCheckPrepmtAmtInvEmpty in Table 39:

xPurchaseLine: Record "Purchase Line"

```
local procedure CheckPrepmtAmtInvEmpty()
var
    IsHandled: Boolean;
begin
    IsHandled := false;
+   OnBeforeCheckPrepmtAmtInvEmpty(Rec, IsHandled, xRec);
    if IsHandled then
        exit;

    if "Prepmt. Amt. Inv." <> 0 then
        Error(CannotChangeVATGroupWithPrepmInvErr);
end;
```

New event signature:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckPrepmtAmtInvEmpty(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean; xPurchaseLine: Record "Purchase Line")
begin
end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
