### ISSUE TITLE
[Event Request] Report 1320 "Notification Email" - OnSetReportFieldPlaceholdersOnBeforeGetWebUrl

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#15450]
Hi Microsoft AL Development Team,

Could you please pass the variable **SourceRecRef: RecordRef** as a new parameter to this integration event **OnSetReportFieldPlaceholdersOnBeforeGetWebUrl** in **Report 1320 "Notification Email"**?

![image](https://user-images.githubusercontent.com/69611495/144794868-b6b378d5-5e84-44bf-955c-d1a114beb493.png)

Thank you.

Regards,
Tuan

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
