### ISSUE TITLE
Table "Gen. Journal Line" - wrong parameter passed into OnAfterCopyGenJnlLineFromCustLedgEntry() event

### ISSUE THREAD

**Issue by VMasalkov** [microsoft/ALAppExtensions#15467]
In BC19, table "Gen. Journal Line" procedure CopyCustLedgEntry() is called with variable CustLedgerEntry as parameter, but the call to OnAfterCopyGenJnlLineFromCustLedgEntry() event takes global variable CustLedgEntry instead of the one passed into procedure. That makes event subscription unusable for any kind of integration enhancements.

**Comment by dnpb** [comment]
Good find! The potential for easy confusion like this this is one of the main (many) reasons why global variables are horrible, and MS should invest time in eliminating them... ;-) especially as it shows they have fallen victim to the danger, just as other devs will.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
