### ISSUE TITLE
[Event Request] Page 232 Apply Customer Entries - OnBeforePostDirectApplication2

### ISSUE THREAD

**Issue by adejsy** [microsoft/ALAppExtensions#15462]
In BC19 CU1 this integration event was added as per the below link.

#14956 

This is great but we need this integration event to be changed from the below.

[IntegrationEvent(false, false)]
local procedure OnBeforePostDirectApplication2(ApplyingCustLedgEntry: Record "Cust. Ledger Entry")
begin
end; 

We need the sender but the parameter is set to false at present. Ideally we need this to be the following.

[IntegrationEvent(**true**, false)]
local procedure OnBeforePostDirectApplication2(ApplyingCustLedgEntry: Record "Cust. Ledger Entry")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
