### ISSUE TITLE
[Event-Request] table 1670 "Option Lookup Buffer" - OnBeforeIncludeOption

### ISSUE THREAD

**Issue by SBiernat** [microsoft/ALAppExtensions#15465]
Regarding to case #14712 i requested the publisher OnBeforeIncludeOption to be extended for the Document Type.

In 19.1 the publisher was extended by the RecRef parameter.
But how should this work?

The Parameter RecRef is only the Table without any Fieldvalues.
Except the Field Type, which was filled before.

**Comment by AlexanderYakunin** [comment]
No, RecRef gives you full table record with values, if you use RecRef.SetTable(SalesLine), for example. So you have all needed information.

**Comment by SBiernat** [comment]
Sorry, but have you tried your own publisher ? 
I know how i can work with RecRef. But when the Publisher doesn't pass the necessary information to the RecRef Variable, then the Variable can't be used and it's a BUG.

Here is my code:
codeunit 50000 "MY Event Subscriber"
{
    [EventSubscriber(ObjectType::Table, Database::"Option Lookup Buffer", 'OnBeforeIncludeOption', '', false, false)]
    local procedure OptionLookupBuffer_OnBeforeIncludeOption(OptionLookupBuffer: Record "Option Lookup Buffer"; LookupType: Option; Option: Integer; var Handled: Boolean; var Result: Boolean; RecRef: RecordRef)
    begin
        message(Format(RecRef));
    end;
}

And these are the messages when i open a SalesOrderCard.
![image](https://user-images.githubusercontent.com/45194723/150630936-838d979f-2630-469e-8580-c5496f5e717e.png)
![image](https://user-images.githubusercontent.com/45194723/150630944-0c49fb4c-5a70-4f56-af8b-8f784ac77288.png)
![image](https://user-images.githubusercontent.com/45194723/150630955-0a33cc2c-65b2-43dc-97c6-a6583d5118a3.png)
![image](https://user-images.githubusercontent.com/45194723/150630961-11889a8c-5e68-4b3d-b9e3-ca8c8f38bae4.png)

Perhaps you can see, that there is only the one Field changing and the EventPublisher has a BUG.
