### ISSUE TITLE
event parameter request - codeunit 7324 "Whse.-Activity-Post" - OnBeforeCheckItemTracking() - WhseActivHeader

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15463]
`CheckItemTracking()` checks the `Expiration Date` of the `WhseActivLine2` against the `WhseActivHeader."Posting Date"`. We want to add another check against another date, which should also be done against the `WhseActivHeader."Posting Date"`. But the event publisher does not pass the `WhseActivHeader`. For now, we can manually duplicate the work of `Get()`ting it and check that. But it would make sense if you could please add that to the publisher:

    local procedure CheckItemTracking(WhseActivLine2: Record "Warehouse Activity Line"): Boolean
    var
        WhseItemTrackingSetup: Record "Item Tracking Setup";
        Result: Boolean;
        IsHandled: Boolean;
    begin
        OnBeforeCheckItemTracking(WhseActivLine2, WhseActivHeader, Result, IsHandled);
        if IsHandled then
            exit(Result);
    [...]
    
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckItemTracking(var WarehouseActivityLine: Record "Warehouse Activity Line"; WarehouseActivityHeader: Record "WarehouseActivity Header"; var Result: Boolean; var IsHandled: Boolean)

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
