### ISSUE TITLE
[Event Request] Table 5900 "Service Header" - OnBeforeOnModify

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#15461]
Hi, would it be possible to get an **OnBeforeOnModify** event in table 5900 (**Service Header**), like this:
```AL
    trigger OnModify()
    var
        IsHandled: Boolean;
    begin
        // New Event begin
        IsHandled := false;
        OnBeforeOnModify(Rec, xRec, IsHandled);
        if IsHandled then
            exit;
        // New Event end

        UpdateServiceOrderChangeLog(xRec);
    end;
```
```AL
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnModify(var ServiceHeader: Record "Service Header"; xServiceHeader: Record "Service Header"; var IsHandled: Boolean)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
