### ISSUE TITLE
[Event Request] Codeunit 5815 "Undo Sales Shipment Line" - OnPostItemJnlLineOnAfterRunItemJnlPostLine

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#15476]
We need the event OnPostItemJnlLineOnAfterRunItemJnlPostLine just after the line ItemJnlPostLine.Run(ItemJnlLine) in the function PostItemJnlLine

`    [IntegrationEvent(false, false)]
    local procedure OnPostItemJnlLineOnAfterRunItemJnlPostLine(var ItemJnlLine: Record "Item Journal Line")
`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
