### ISSUE TITLE
[Bug] Page 6510 - Item Tracking Lines Register Item Tracking Lines

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#15483]
On Page 6510 Item Tracking Lines in the function RegisterItemTrackingLines the code change about a month ago for  reclass.  The code was originally setting the New Serial No. and New Lot No. from the New Serial No. and New Lot No.  If you go look at the function CopyNewTrackingFromTrackingSpec, it is now not getting it from the New Serial and New Lot No., but instead from the normal Serial No. and Lot No.  There might need to be a new function called CopyNewTrackingFromNewTrackingSpec and it should be calling that from the Item Tracking Lines.  

**Current**
![image](https://user-images.githubusercontent.com/32099690/145285358-936300b7-c5e6-40fb-88c3-30e281b609bf.png)
![image](https://user-images.githubusercontent.com/32099690/145285495-452f889a-95cc-4489-ae64-0735f3738e0a.png)

**New**
    procedure CopyNewTrackingFromNewTrackingSpec(TrackingSpecification: Record "Tracking Specification")
    begin
        "New Serial No." := TrackingSpecification."New Serial No.";
        "New Lot No." := TrackingSpecification."New Lot No.";

        OnAfterCopyNewTrackingFromNewTrackingSpec(Rec, TrackingSpecification);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
