### ISSUE TITLE
[Extensibility Request] Create Enum for Option "Returns-Related Document".Document Type"

### ISSUE THREAD

**Issue by ThomasKlockenbusch** [microsoft/ALAppExtensions#15486]
![image](https://user-images.githubusercontent.com/95849274/145362896-2b5a90aa-59fe-4ab2-8e87-14f9e06947c5.png)

Please create an extensible enum for the option field.

Thx

**Comment by ThomasKlockenbusch** [comment]
And please make the Action "Card" on the page "Returns-Related Documents" accessible as well.

![image](https://user-images.githubusercontent.com/95849274/145391168-f24c1e28-2aab-471e-8cca-0d734f27b94a.png)

Action:
![image](https://user-images.githubusercontent.com/95849274/145391233-63f746e2-05af-4c33-bc61-195ab17e9cef.png)

Thank you :)

**Comment by dnpb** [comment]
It's best to make a new issue for the 2nd request. I suspect comments after the 1st post don't always make it to MS's internal system, so they might get lost, and only the 1st post actioned.

**Comment by ThomasKlockenbusch** [comment]
Thx for the information. No problem

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
