### ISSUE TITLE
[Extensibility Request] Table 1003 "Job Planning Line" - function GetNextJobLineNo

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#15487]
Please make function GetNextJobLineNo externally available - Set to Global

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
