### ISSUE TITLE
Russian language (Russia) LCY translation

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#15499]
Hello,
In the application Russian language (Russia) we have a critical issue in translation.
In all cases for fields ex. Amount (LCY) translated Сумма (руб.), but "руб." is the Russian national currency. It's not correct when clients use business central in other countries with Russian UI translation or for in companies where local currency is not RUB.

I suggest make a replacement in file Base Application.ru-RU.xlf for w1 objects.
(руб.) -> (ЛОК)
(руб) - > (ЛОК)
руб. -> ЛОК
в рублях -> в локальной валюте
рублями -> локальной валютой
в рубли -> в локальную валюту
рубли) -> ЛОК)

**Comment by dnpb** [comment]
This concept generally was discussed on Yammer:
https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1461995408523264

excerpts for those who aren't registered:

***

> Eva Dupont – November 5 at 01:07 PM
>Hm. The way I remember this from old times, LCY would only be LCY in the W1 builds and always be replaced by the country's currency code in the various languages for each country we shipped.
>That appears to still work for the Norwegian translations of the docs for BC, but not for en-gb, where LCY is still LCY. At a guess, it's because our British translators decided to interpret our terminology very literally. And to their point, the source of our docs is now a true en-US language and not the mid-Atlantic "en-W1" anymore...

***

> [me]
>It seems wrong to assume that in every company the LCY is the 'default' currency for the region of the current language. Otherwise, why even have the ability to choose LCY in the G/L Setup? 
>It's not outlandish that e.g. a business could be based in Norway and use that localisation but be accounting for companies whose LCY is GBP, etc.
>I have mostly used en-GB, but the way it does things makes sense to me. LCY should either be translated literally, or be CaptionClass-ed to substitute the actual G/L Setup's LCY Code, but it doesn't seem right to 'hard-code' it in translations to assume it's a specific currency.

***
>I've talked to a few people here, and we need a bit more time to determine if we want to make the currency story more transparent in code. Until we have that decision ready, I can't ask the translators to translate LCY to "LCY" instead of "NOK" in this case. 
>And yes, BVA and RV are translations of LCY in Swedish and Danish, respectively. RV means "accounting currency", loosely translated. I think this is going to be the preferred solution going forward, so that it's transparent which currencies amounts on a document are in: LCY, NOK, or GBP, for example.

**Comment by dnpb** [comment]
update from Yammer:
> Eva Dupont – 17 minutes ago
>Hello everyone,
>We're working on getting this issue resolved in the languages that we translate into. The decision is that "LCY" means "LCY" in all our languages and should not be translated into that country's local currency.
>To Ivar Løvlie's example above, that would mean that it would be correct to use  "Fordelingsbalanse (RV)" going forward. In the setup for those Norwegian customers, LCY would of course (nearly) always be set to NOK. 
>Oh, and to the non-Danish speakers out there, "RV" means "regnskabsvaluta", literally "accounting currency", which is technically more appropriate than LCY :-)

**Comment by vlkov** [comment]
Awesome!
Thanks)

**Comment by edupont04** [comment]
Hi @vlkov 
The Russian translation is not delivered by Microsoft. I can't guarantee that the Russian translation will be updated at the same time as the Microsoft-provided translations.
