### ISSUE TITLE
[Event Request] table 36 "Sales Header" - OnBeforeValidateRequestedDeliveryDate

### ISSUE THREAD

**Issue by mrabus** [microsoft/ALAppExtensions#15495]
Would you please be so kind to add a new event publisher like that: 

    //Added
    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateRequestedDeliveryDate(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;
    //Added    
    
in the field "Requested Delivery Date"?

        field(5790; "Requested Delivery Date"; Date)
        {
            Caption = 'Requested Delivery Date';

            trigger OnValidate()
            var
                Handled: Boolean;            
            begin
                //Added
                Handled := false;
                OnBeforeValidateRequestedDeliveryDate(Rec, Handled);
                if Handled then
                    exit;
                //Added 
                TestStatusOpen;
                CheckPromisedDeliveryDate();

                if "Requested Delivery Date" <> xRec."Requested Delivery Date" then
                    UpdateSalesLinesByFieldNo(FieldNo("Requested Delivery Date"), CurrFieldNo <> 0);
            end;
        }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
