### ISSUE TITLE
[Event Request] Table 2158 "O365 Document Sent History" - Event OnBeforeNewInProgressFromRecRef

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#15491]
Hello,

Can we please get "O365 Document Sent History" as reference in this event "OnBeforeNewInProgressFromRecRef"?

   procedure NewInProgressFromRecRef(RecRef: RecordRef) Result: Boolean
    var
        SalesHeader: Record "Sales Header";
        SalesInvoiceHeader: Record "Sales Invoice Header";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeNewInProgressFromRecRef(**Rec**, RecRef, Result, IsHandled);
        if IsHandled then
            exit(Result);
        case RecRef.Number of
            DATABASE::"Sales Header":
                begin
                    RecRef.SetTable(SalesHeader);
                    exit(NewInProgressFromSalesHeader(SalesHeader));
                end;
            DATABASE::"Sales Invoice Header":
                begin
                    RecRef.SetTable(SalesInvoiceHeader);
                    exit(NewInProgressFromSalesInvoiceHeader(SalesInvoiceHeader));
                end;
            else begin
                    Session.LogMessage('000028D', StrSubstNo(UnrecognizedParentRecordErr, RecRef.Number), Verbosity::Error, DataClassification::SystemMetadata, TelemetryScope::ExtensionPublisher, 'Category', DocSentHistoryCategoryTxt);
                    exit(false);
                end;
        end;
    end;

 [IntegrationEvent(false, false)]
    local procedure OnBeforeNewInProgressFromRecRef(**var O365DocumentSentHistory: Record "O365 Document Sent History"**;  RecRef: RecordRef; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
