### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" - PostItemChargeLine & OnAfterPostItemChargeLine

### ISSUE THREAD

**Issue by ccatt000** [microsoft/ALAppExtensions#15500]
Hello Team,

In Codeunit 80, please provide the possibility of passing SalesLine by reference to **PostItemChargeLine** as well as the Publisher **OnAfterPostItemChargeLine** (existing) event. 

1. **PostItemChargeLine**
![image](https://user-images.githubusercontent.com/81978737/145433652-00c2c4ef-760d-4673-a63e-95b26ba6fa91.png)

2. **OnAfterPostItemChargeLine**
![image](https://user-images.githubusercontent.com/81978737/145433883-e318dd58-9315-45c9-bf57-988e4bfde2f6.png)

This would allow users to edit values of SalesLine without a MODIFY in the subscriber, as this causes an error:
![image](https://user-images.githubusercontent.com/81978737/145434482-3da6bd16-c19f-4d0c-879f-2628433d62c1.png)

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
