### ISSUE TITLE
Error when creating warehouse worksheet lines from pick worksheet

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#15503]
Hello,
we found a bug when createin warehouse worksheet lines:
When creating a "Whse. Worksheet Line" (Table 7326) via the "Pick Worksheet" (Page 7345) with the action "Get Warehouse Documents" the created lines have the description of the item and not the warehouse shipment line.
I analyzed that the GetItem-Funktion overwrites the description with the item description Can you fix this?
![image](https://user-images.githubusercontent.com/56454149/145559626-f3c95987-3c3e-43cb-ba92-f5d823a74e02.png)

Alexander

**Comment by AlexanderYakunin** [comment]
Sorry, this is not an extensibility issue, please create hotfix request using regular partner support channels.
