### ISSUE TITLE
[Event Request] table 36 "Sales Header" - OnBeforeSetShippingAgenFromShipToAddr

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#15502]
Can we please get the following event?
```al
procedure SetShipToCustomerAddressFieldsFromShipToAddr(ShipToAddr: Record "Ship-to Address")
var
    IsHandled: Boolean;
begin

    ...

    //+EVENT
    NEW:= false;
    OnBeforeSetShippingAgenFromShipToAddr(Rec, ShipToAddr, IsHandled);
    if not IsHandled then begin
    //-NEW
        "Shipping Agent Code" := ShipToAddr."Shipping Agent Code";
        "Shipping Agent Service Code" := ShipToAddr."Shipping Agent Service Code";
    end; //NEW
    if ShipToAddr."Tax Area Code" <> '' then
        "Tax Area Code" := ShipToAddr."Tax Area Code";
    "Tax Liable" := ShipToAddr."Tax Liable";

    OnAfterCopyShipToCustomerAddressFieldsFromShipToAddr(Rec, ShipToAddr);
end;
```
```al
[IntegrationEvent(false, false)]
local procedure OnBeforeSetShippingAgenFromShipToAddr(var SalesHeader: Record "Sales Header"; ShipToAddr: Record "Ship-to Address"; var IsHandled: Boolean)
begin
end;
```

**Comment by Oleg-Romashkov** [comment]
Hi,

Please use existing events OnBeforeCopyShipToCustomerAddressFieldsFromShipToAddr or OnAfterCopyShipToCustomerAddressFieldsFromShipToAddr

**Comment by pri-kise** [comment]
Hi @Oleg-Romashkov could you then please add the xRec to the event `OnAfterCopyShipToCustomerAddressFieldsFromShipToAddr` that we optionally can reset the values to the previous values.

**Comment by Oleg-Romashkov** [comment]
Ok

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
