### ISSUE TITLE
[Event Request] Codeunit "Calculate Prod. Order" - Procedure "CopyRoutingTools"

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#15506]
We need a possibility to filter RoutingTools before they are transferred to ProdOrderRoutingTools in procedure "CopyRoutingTools".
Parameter RoutingTool should be var.

    local procedure CopyRoutingTools(ProdOrderRoutingLine: Record "Prod. Order Routing Line"; VersionCode: Code[20])
    var
        RoutingTool: Record "Routing Tool";
        ProdOrderRoutingTool: Record "Prod. Order Routing Tool";
    begin
        RoutingTool.SetRange("Routing No.", ProdOrderRoutingLine."Routing No.");
        RoutingTool.SetRange("Operation No.", ProdOrderRoutingLine."Operation No.");
        RoutingTool.SetRange("Version Code", VersionCode);
        >>>>>>>>NEW<<<<<<<<<<<
        OnFilterRoutingTools(RoutingTool, ProdOrderRoutingLine, VersionCode);
        >>>>>>>>NEW<<<<<<<<<<<
        if RoutingTool.Find('-') then
            repeat
                ProdOrderRoutingTool.TransferFields(RoutingTool);
                ProdOrderRoutingTool.Status := ProdOrderRoutingLine.Status;
                ProdOrderRoutingTool."Prod. Order No." := ProdOrderRoutingLine."Prod. Order No.";
                ProdOrderRoutingTool."Routing Reference No." := ProdOrderRoutingLine."Routing Reference No.";
                ProdOrderRoutingTool.Insert();
            until RoutingTool.Next() = 0;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
