### ISSUE TITLE
[Request publisher change] Codeunit 1012 "Job Jnl.-Post Line", OnAfterRunCode() IncludeSender

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#15507]
Currently it's not possible to call the global procedure CreateJobLedgEntry() because it relies on global variables (e.g. NextEntryNo and JobReg).

We need to call this procedure from subscribers for two reasons:
a) We extended the Type Enum of Job Journal Lines and need to post job ledger entries accordingly
b) We need to replace PostItem() functionality and call CreateJobLedgEntry() 

Please change the publisher like this:
```
[IntegrationEvent(true, false)]
local procedure OnAfterRunCode(var JobJournalLine: Record "Job Journal Line"; var JobLedgEntryNo: Integer; var JobRegister: Record "Job Register"; var NextEntryNo: Integer)
begin
end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
