### ISSUE TITLE
event parameter request - codeunit 414 "Release Sales Document" - PerformManualRelease() - OnPerformManualReleaseOnBeforeTestSalesPrepayment() - IsHandled pattern

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15508]
We have a need to in some cases skip the standard code and do our own stuff instead. Currently a previous developer had to do our stuff via `OnBeforeManualReleaseSalesDoc`, then `Commit()` and `Error('')` to suppress the standard code. That is, of course, horrible (including to debug other, downstream code...) and brittle (it will not let subsequent code run if fired non-interactively).

Thus can you please add the Handled pattern? I would suggest adding to both `OnBefore` events here, as I imagine someone else might want to skip checking prepayments too.

    procedure PerformManualRelease(var SalesHeader: Record "Sales Header")
    var
        PrepaymentMgt: Codeunit "Prepayment Mgt.";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnPerformManualReleaseOnBeforeTestSalesPrepayment(SalesHeader, PreviewMode, IsHandled);
        if IsHandled then
            exit;

        if PrepaymentMgt.TestSalesPrepayment(SalesHeader) then
            Error(UnpostedPrepaymentAmountsErr, SalesHeader."Document Type", SalesHeader."No.");

        IsHandled := false;
        OnBeforeManualReleaseSalesDoc(SalesHeader, PreviewMode, IsHandled);
        if IsHandled then
            exit;

        PerformManualCheckAndRelease(SalesHeader);
        OnAfterManualReleaseSalesDoc(SalesHeader, PreviewMode);
    end;

publishers:

    [IntegrationEvent(false, false)]
    local procedure OnPerformManualReleaseOnBeforeTestSalesPrepayment(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeManualReleaseSalesDoc(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean; var IsHandled: Boolean)
    begin
    end;

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
