### ISSUE TITLE
[Event Request] Purchase Header - New Event OnBeforeCreateDimensionsFromValidatePayToVendor(Rec, IsHandled)

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#15509]
Congruent Event exists on Sales Header (but with BillToCustomer). Would like similar on Purchase Header.

would suggest the following fix (to be congruent with Sales Header):

Exiting 19.1.31886.33484: "Purchase Header"."Pay-To Vendor No." On Validate:

Line 219:

>                if "Pay-to Vendor No." = xRec."Pay-to Vendor No." then begin
>                    if ReceivedPurchLinesExist then
>                        TestField("Currency Code", xRec."Currency Code");
>                end;
>
>                CreateDim(
>                  DATABASE::Vendor, "Pay-to Vendor No.",
>                  DATABASE::"Salesperson/Purchaser", "Purchaser Code",
>                  DATABASE::Campaign, "Campaign No.",
>                  DATABASE::"Responsibility Center", "Responsibility Center");
>
>                OnValidatePaytoVendorNoBeforeRecreateLines(Rec, CurrFieldNo);

Proposed change:

1. Remove CreateDim( ... ) procedure.
2. replace with:

>            CreateDimensionsFromValidatePayToVendorNo();

And then add the following procedure and Integration Event

>            local procedure CreateDimensionsFromValidatePayToVendorNo()
>            var
>                IsHandled: Boolean;
>            begin
>                IsHandled := false;
>                OnBeforeCreateDimensionsFromValidatePayToVendorNo(Rec, IsHandled);
>                if IsHandled then
>                    exit;
>
>                CreateDim(
>                  DATABASE::Vendor, "Pay-to Vendor No.",
>                  DATABASE::"Salesperson/Purchaser", "Purchaser Code",
>                  DATABASE::Campaign, "Campaign No.",
>                  DATABASE::"Responsibility Center", "Responsibility Center");
>            end;
>
>            [IntegrationEvent(false, false)]
>            local procedure OnBeforeCreateDimensionsFromValidatePayToVendorNo(var PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
>            begin
>            end;
>

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
