### ISSUE TITLE
[Event Request] Application “Tests-SCM”, Codeunit 137831 "SCM - Warehouse UT"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#15515]
[Event Request]Application “Tests-SCM”, 137831 "SCM - Warehouse UT"

Could you please insert the Event OnTestInitialize at the beginning of the Initialize procedure
![pic1](https://user-images.githubusercontent.com/45795262/145808778-f65e1cef-264e-4641-8fc5-855cade13612.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
