### ISSUE TITLE
[Event Request] Application “Tests-SCM”, Codeunit 137621 "SCM Costing Bugs II"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#15516]
[Event Request]Application “Tests-SCM”, 137621 "SCM Costing Bugs II"

Could you please insert the Event OnTestInitialize at the beginning of the test procedures:
•	TFS355737_AdjmtRoundingAfterReturn
•	TFS356239_ShipAndReturnOnNegativeInventory
![pic1](https://user-images.githubusercontent.com/45795262/145808988-c2ee094c-8534-4c98-a275-8f36c442215d.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
