### ISSUE TITLE
[Extensibility Request] Codeunit VAT Registration Log Mgt. (249), Procedure CheckVIESForVATNo

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#15519]
Hi AL-Team,
we would like to check "VAT Registration No." for a new field in a table extension, the new fieldname includes a Suffix. Unfortunately, we cannot use the procedure "CheckVIESForVATNo" (Codeunit VAT Registration Log Mgt.) because the following line (336) does not support pre-/suffixed fields.

```
if not DataTypeManagement.FindFieldByName(RecordRef, VatRegNoFieldRef, Customer.FieldName("VAT Registration No.")) then
   exit;

```
The problem is the usage of the static "Customer.FieldName("VAT Registration No.")" parameter - we need something more flexible to maintain additional field names and we suggest a new parameter "VATRegistrationNoFieldName" in the procedure "CheckVIESForVATNo".

```
procedure CheckVIESForVATNo(var RecordRef: RecordRef; VATRegistrationNoFieldName: Text ;var VATRegistrationLog: Record "VAT 
   Registration Log"; RecordVariant: Variant; EntryNo: Code[20]; CountryCode: Code[10]; AccountType: Option)
```

The Customer.FieldName("VAT Registration No.") is replaced by VATRegistrationNoFieldName:
```
if not DataTypeManagement.FindFieldByName(RecordRef, VatRegNoFieldRef, VATRegistrationNoFieldName) then
    exit;

```

This is surely only one possibility, feel free to suggest another solution how to use the standard functions with the suffixed fieldnames.

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
