### ISSUE TITLE
event parameter request - page 6510 "Item Tracking Lines" - AssignSerialNoBatch() - OnAssignSerialNoBatchOnAfterInsert() - CreateLotNo

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15529]
Please can you pass the `CreateLotNo` parameter to event subscribers? Not `var`, just by copy/value.

    local procedure AssignSerialNoBatch(QtyToCreate: Integer; CreateLotNo: Boolean; CreateSNInfo: Boolean)
    [...]
        for i := 1 to QtyToCreate do begin
            [....]
            Rec.Insert();

            OnAssignSerialNoBatchOnAfterInsert(Rec, Create LotNo);
    [....]

Please see also https://github.com/microsoft/ALAppExtensions/issues/15528 to include the sending page from the same publisher.

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
