### ISSUE TITLE
event parameter request - page 6510 "Item Tracking Lines" - AssignSerialNoBatch() - OnAssignSerialNoBatchOnAfterInsert() - Sender

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15528]
We have a page extension for this that needs to perform some actions/updates whenever a Lot No is validated. It does this in a function on the page extension, as it uses values of said page extension's controls/variables. We need this to include creation of a Lot by the Assign Serial No actions.

Thus can you please make OnAssignSerialNoBatchOnAfterInsert() include the sending page, so we can call our function on our page extension? I guess change it to `IntegrationEvent(true, false)`.

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
