### ISSUE TITLE
[Event Request] Codeunit 920 "Period Form Lines Mgt." - OnBeforeInsertLine

### ISSUE THREAD

**Issue by Athon-dev** [microsoft/ALAppExtensions#15523]
Please add a new integration event OnBeforeInsertLine in Codeunit 920 .

procedure NextDate(var BufferRecord: Variant; var DateRec: Record Date; Steps: Integer; PeriodType: Option): Integer
    var
        RecRef: RecordRef;
        ResultSteps: Integer;
    begin
        RecRef.GetTable(BufferRecord);
        CopyPeriodStartFilter(RecRef, DateRec);
        ResultSteps := PeriodPageMgt.NextDate(Steps, DateRec, "Analysis Period Type".FromInteger(PeriodType));
        if ResultSteps = 0 then
            exit(0);

	+ OnBeforeInsertLine(BufferRecord, DateRec, IsHandled);
	+ if IsHandled then
	+	exit(0);

        if not FindLine(RecRef, DateRec) then
            if not InsertLine(RecRef, DateRec) then
                exit(0);

        RecRef.SetTable(BufferRecord);

        exit(ResultSteps);
    end;

New integration event:

    [IntegrationEvent(false, false)]
     local procedure OnBeforeInsertLine(var BufferRecord: Variant; var DateRec: Record Date; var IsHandled: Boolean)
    begin
    end;

**Comment by Athon-dev** [comment]
Hi Alexander can you tell me when you can handle this request?

thank's

**Comment by Athon-dev** [comment]
News? 

thank's

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
