### ISSUE TITLE
[Event Request] Page 232 "Apply Customer Entries" - procedure CheckCustLedgEntry(var CustLedgerEntry: Record "Cust. Ledger Entry")

### ISSUE THREAD

**Issue by Connie94** [microsoft/ALAppExtensions#15525]
trigger CheckCustLedgEntry(var CustLedgerEntry: Record "Cust. Ledger Entry")
var
        RaiseError: Boolean;
    begin
        if CustLedgerEntry.FindSet() then
            repeat
                if CalcType = CalcType::"Gen. Jnl. Line" then begin
                    RaiseError := ApplyingCustLedgEntry."Posting Date" < CustLedgerEntry."Posting Date";
                    OnBeforeEarlierPostingDateError(ApplyingCustLedgEntry, CustLedgerEntry, RaiseError, CalcType.AsInteger());
                    if RaiseError then
                        Error(
                            EarlierPostingDateErr, ApplyingCustLedgEntry."Document Type", ApplyingCustLedgEntry."Document No.",
                            CustLedgerEntry."Document Type", CustLedgerEntry."Document No.");
                end;

               OnBeforeCheckAgainstApplnCurrency(CustledgerEntry);

                if ApplyingCustLedgEntry."Entry No." <> 0 then
                    GenJnlApply.CheckAgainstApplnCurrency(
                        ApplnCurrencyCode, CustLedgerEntry."Currency Code", GenJnlLine."Account Type"::Customer, true);
            until CustLedgerEntry.Next() = 0;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
