### ISSUE TITLE
[Event Request] Codeunit 104000 "Upgrade - BaseApp" - OnBeforeUpdateItems

### ISSUE THREAD

**Issue by chliebich** [microsoft/ALAppExtensions#15522]
Please add a new integration event OnBeforeUpdateItems in Codeunit 104000.

```
local procedure UpdateItems()
var
    ItemCategory: Record "Item Category";
    Item: Record "Item";
    UpgradeTag: Codeunit "Upgrade Tag";
    UpgradeTagDefinitions: Codeunit "Upgrade Tag Definitions";
+   IsHandled: Boolean;
begin
+   IsHandled := false;
+   OnBeforeUpdateItems(IsHandled);
+   If IsHandled then
+       exit();

    IF UpgradeTag.HasUpgradeTag(UpgradeTagDefinitions.GetItemCategoryOnItemAPIUpgradeTag()) THEN
        EXIT;

    IF NOT ItemCategory.ISEMPTY THEN BEGIN
        Item.SETFILTER("Item Category Code", '<>''''');
        IF Item.FINDSET(TRUE, FALSE) THEN
            REPEAT
                Item.UpdateItemCategoryId;
                IF Item.MODIFY THEN;
            UNTIL Item.Next() = 0;
    END;

    UpgradeTag.SetUpgradeTag(UpgradeTagDefinitions.GetItemCategoryOnItemAPIUpgradeTag());
end;
```

New integration event:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateItems(var IsHandled: Boolean)
begin
end;

```

**Comment by Stepanenko-Vadim** [comment]
We will not add events into upgrade codeunits.
If you wish to run your code before or instead an upgrade routine you should subscribe to **OnCheckPreconditionsPerCompany** , insert the tag that is being inserted here (so this upgrade routine is naturally skipped), then do any of your own upgrade routines when you deem necessary, with your own flags etc.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by Stepanenko-Vadim** [comment]
You should disregard the message from Jesper, it's a bot malfunction :)
