### ISSUE TITLE
Extensibility Request: Change UpdatePropagation to "Both" for "Incoming Document"

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#15533]
On page 189 "Incoming Document"
Please change UpdatePropagation to "Both" for "Incoming Document Attachments" pagepart on the Incoming Document. After making changes to the incoming document attachments (shuffeling Supporting to main attachments) we would like to update the concerning incoming document page. This property cannot be modified in an extension.
 
            part(SupportingAttachments; "Incoming Document Attachments")
            {
                ApplicationArea = All;
                Caption = 'Supporting Attachments';
                ShowFilter = false;
                UpdatePropagation = Both;
                Visible = AdditionalAttachmentsPresent;
            }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
