### ISSUE TITLE
[EventRequest] C11, procedure LogTestField

### ISSUE THREAD

**Issue by LucVanDyck** [microsoft/ALAppExtensions#15545]
Similar to https://github.com/microsoft/ALAppExtensions/issues/12088, we have code that makes it possible to apply G/L Entries. 

Can a OnBeforeLogTestField event be introduced in Codeunit 11, in the LogTestField procedure? This way, we could skip the TestField-statement for a specific Field No., making it more generic then the proposed solution in the referred issue.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
