### ISSUE TITLE
event request - page 256 "Payment Journal" - action("Print Remi&ttance Advice") - OnAction() - OnPrintRemittanceAdviceOnAfterSetFilters(var GenJournalLine: Record "Gen. Journal Line")

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15549]
We want the Print Remittance Advice button to automatically filter the report to the selected payment(s) only. Right now it shows all payments for all vendors in the batch.

Therefore, please can you add an event as below?

* The argument should be `var GenJournalLine: Record "Gen. Journal Line"` so that we can add our filters before calling Report Selections.
* The `IncludeSender` should be `true` so that we can do `Sender.SetSelectionFilter(GenJournalLine)` from said page to the argument.

Thanks!

                action("Print Remi&ttance Advice")
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Print Remi&ttance Advice';
                    Image = PrintAttachment;
                    ToolTip = 'Print the remittance advice before posting a payment journal and after posting a payment. This advice displays vendor invoice numbers, which helps vendors to perform reconciliations.';

                    trigger OnAction()
                    var
                        ReportSelections: Record "Report Selections";
                    begin
                        GenJnlLine.Reset();
                        GenJnlLine.SetRange("Journal Template Name", "Journal Template Name");
                        GenJnlLine.SetRange("Journal Batch Name", "Journal Batch Name");
                        OnPrintRemittanceAdviceOnAfterSetFilters(GenJnlLine);
                        ReportSelections.PrintWithDialogForVend(
                            ReportSelections.Usage::"V.Remittance", GenJnlLine, true, FieldNo("Account No."));
                    end;
                }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
