### ISSUE TITLE
[Scope Change Request] - DocExchServiceAuth.Page - GetAuthCode

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#15552]
We would like to have the scope changed for the following procedure:
Object: DocExchServiceAuth.Page
Procedure: GetAuthCode

Reason: In extensions that uses the universal code, it should be possible to use the default OAuth logic. For that, the "OnPrem" flag must  be removed from the following procedure.
```al
[Scope('OnPrem')]
[NonDebuggable]
procedure GetAuthCode(): Text
begin
    exit(AuthCode);
end;
```

**Comment by AndersLarsenMicrosoft** [comment]
Sorry in understand your argument, but for security issues this is both marked as [Scope('OnPrem')] and
[NonDebuggable]
