### ISSUE TITLE
[Event Request] Table 5767 - Warehouse Activity Line - OnAfterAssistEditTrackingNo

### ISSUE THREAD

**Issue by SchoKa** [Microsoft/ALAppExtensions#1555]
Hello AL-Team,
 we need the following publisher to add some extra decisions if a Lot is selected:

[External] LookUpTrackingSummary(VAR WhseActivLine : Record "Warehouse Activity Line";SearchForSupply : Boolean;SignFactor : Integer;TrackingType : 'SerialNo,LotNo')

[...]
   ItemTrackingDataCollection.SetCurrentBinAndItemTrkgCode("Bin Code",ItemTrackingCode);

 ItemTrackingDataCollection.AssistEditTrackingNo(
    TempTrackingSpecification,SearchForSupply,SignFactor,TrackingType,"Qty. Outstanding");

  // >> New
  OnAfterAssistEditTrackingNo(WhseActivLine,TempTrackingSpecification,TrackingType);
  // << New

  CASE TrackingType OF
    TrackingType::SerialNo:
      IF TempTrackingSpecification."Serial No." <> '' THEN BEGIN
        VALIDATE("Serial No.",TempTrackingSpecification."Serial No.");
[…]

Publisher definition currently used by us
 IncludeSender: false
 GlobaVarAccess: false
LOCAL [IntegrationEvent] OnAfterAssistEditTrackingNo(VAR WhseActivLine : Record "Warehouse Activity Line";VAR TrackingSpecification : Record "Tracking Specification";VAR TrackingType : Option)

**Comment by NKarolak** [comment]
Note: added as OnLookUpTrackingSummaryOnAfterAssistEditTrackingNo
