### ISSUE TITLE
[Event Request] Page 232 Apply Customer Entries - Set PostingDone as Protected Var

### ISSUE THREAD

**Issue by tgdoat44** [microsoft/ALAppExtensions#15555]
In order to use the global variable PostingDone in a custom action in page 232 "Apply Customer Entries", we need the variable to be in the protected var section.

Perhaps it would be easier to set all global variables of this page to protected var.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
