### ISSUE TITLE
[Access Request]  page 41 "Sales Quote" EnableBillToCustomerNo

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#15564]
Could you please change the variable `EnableBillToCustomerNo` on the page  "Sales Quote" to `protected` that we can use this value for our own fields as property value?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
