### ISSUE TITLE
[Event Request] Codeunit 22 - "Item Jnl.-Post Line"

### ISSUE THREAD

**Issue by mrabus** [microsoft/ALAppExtensions#15562]
Hello Microsoft Team,

please consider adding the following event to the "Item Jnl.-Post Line" codeunit. 

    local procedure GetSourceNo(ItemJnlLine: Record "Item Journal Line"): Code[20]
    var
        Handled: Boolean; 
        SourceNo: Code[20];
    begin
        //XX B
        OnBeforeGetSourceNo(ItemJnlLine, Handled, SourceNo);
        if Handled then
            exit(SourceNo)
        //XX E
        if ItemJnlLine."Invoice-to Source No." <> '' then
            exit(ItemJnlLine."Invoice-to Source No.");
        exit(ItemJnlLine."Source No.");
    end;
    
   Subscriber: 
   
    //XX B
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetSourceNo(ItemJnlLine: Record "Item Journal Line"; Handled: Boolean; SourceNo: Code[20];)
    begin
    end;
    //XX E
    
    
Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
