### ISSUE TITLE
[Event / Change Request] table 37 "Sales Line" - OnCheckWarehouseOnBeforeShowDialog

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#15560]
Could you please change the parameter `ShowDialog` to **var** in the event OnCheckWarehouseOnBeforeShowDialog?
```al
[IntegrationEvent(false, false)]
//- local procedure OnCheckWarehouseOnBeforeShowDialog(var SalesLine: Record "Sales Line"; Location: Record Location; ShowDialog: Option " ",Message,Error; var DialogText: Text[50])
local procedure OnCheckWarehouseOnBeforeShowDialog(var SalesLine: Record "Sales Line"; Location: Record Location; var ShowDialog: Option " ",Message,Error; var DialogText: Text[50])
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
