### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post", Function GetCurrency: OnAfterGetCurrency

### ISSUE THREAD

**Issue by jm-nd** [microsoft/ALAppExtensions#15569]
Hello, we need a way to influence global "Currency" in Codeunit 80, thanks in advance

```al
    local procedure GetCurrency(CurrencyCode: Code[10])
    begin
        Currency.Initialize(CurrencyCode, true);
        // - new
        OnAfterGetCurrency(CurrencyCode, Currency);
        // + new
    end;
```

```al
    [IntegrationEvent(false, false)]
       local procedure OnAfterGetCurrency(CurrencyCode: Code[10]; var Currency: Record Currency)
       begin
       end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
