### ISSUE TITLE
[Event request] Codeunit 5870 "Calculate BOM Tree" in function GenerateTreeForItemLocal

### ISSUE THREAD

**Issue by CarstenHeu** [microsoft/ALAppExtensions#15563]
We would need a second event publisher in the function GenerateTreeForItemLocal in the Calculate BOM Tree codeunit. It should be directly before the line "if HasBOM() or ("Routing No." <> '') then begin" with the same parameter like the OnBeforeFilterBOMBuffer publisher or can you move the existing OnBeforeFilterBOMBuffer publisher before the if condition including the isHandled functionality? 

We would like to go around the if condition to build up the BOMBuffer without having a real BOM...

**Comment by RomanZanizdra** [comment]
Hi @CarstenHeu .
OnBeforeFilterBOMBuffer() event cannot be run before condition, this will change system's behavior. Also I think that's not a good idea to have one more "IsHandled" event  before condition. Why can't you use the existing one, what's the purpose of a new one?

**Comment by CarstenHeu** [comment]
Hi @RomanZanizdra ,
our customer wants to use this structure BOM view for all items including purchase items having no real BOM. In this view we did already some extensions they want to have for all items too. So we would add a temp. BOM line for the calculation and show it instead of real BOM lines. It would work so far if we could come around this one check if the item has a BOM.  
A second event publisher for this task we already got with the thread 15572 (https://github.com/microsoft/ALAppExtensions/issues/15572). So only this one would be needed...
Kind regards,
Carsten Heu.

**Comment by RomanZanizdra** [comment]
@CarstenHeu let's do it in a little bit other way. I'll extend existing OnBeforeGenerateTreeForItemLocal event with required parameters including IsHandled.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
