### ISSUE TITLE
[Event Request] Reports 99001020, 99001025, 99001026 - OnAfterInitReport

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#15566]
Using a report extension, I'd like to extend the following reports by adding a new field on the request page:
- 99001020 "Carry Out Action Msg. - Plan."
- 99001025 "Refresh Production Order"
- 99001026 "Replan Production Order"

I need to preset its value in the OnInitReport trigger.
_RequestPage.OnInit would not be suitable, since the value needs to be also set if the report is run without request page._

Therefore, could you please add the following event in all three reports?

```
    trigger OnInitReport()
    begin
        [...]
        OnAfterInitReport(); // <--- NEW LINE
    end;
```

```
    [IntegrationEvent(true, false)]
    local procedure OnAfterInitReport()
    begin
    end;
```
The **IncludeSender** (or GlobalVarAccess!) parameter set to true is important, in order to modify our own global variable used in the report extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
