### ISSUE TITLE
[event request] Table 18 OnModify

### ISSUE THREAD

**Issue by Nischmiddi** [microsoft/ALAppExtensions#15574]
Hello, 

I need a publisher Event in the modify trigger of the customer table to hadle code If IsContactUpdateNeeded then ...

trigger OnModify()
    begin
        [...]
        If IsContactUpdateNeeded then begin
        [...]
            UpdateContFromCust.OnModify(Rec);
            OnAfterModifyUpdateContFromCust   <-- new Publisher event
         [...]

**Comment by dnpb** [comment]
You should show the actual call including parameters passed, and the declaration of the event procedure showing how they get passed.

**Comment by RomanZanizdra** [comment]
Hi @Nischmiddi . Please add parameters required for event. Or is it possible that you can use existing standard event OnAfterModify()?

**Comment by Nischmiddi** [comment]
Hi @RomanZanizdra sry I didn't get a notification. Yes you can close the request, I got a way to use the OnAfterModifyTrigger. Thank you for your support.
