### ISSUE TITLE
[Event Request] Report 12 "VAT Statement" - Events for CalcLineTotal2C function

### ISSUE THREAD

**Issue by TriangleSPV** [microsoft/ALAppExtensions#15579]
In the report Report 12 "VAT Statement" there are 3 events in the function CalcLineTotal.

In the Spanish Localization it exists a feature that allow to print the report in 2 colums. In this case it uses the function CalcLineTotal2C.

So we need some events in the function CalcLineTotal2C, or equal than the existing in the CalcLineTotal, or as least, an event before the CalculateTotalAmount call.

**Comment by dnpb** [comment]
What events do you need? You should show their procedure declarations and where/how they are called.

**Comment by TriangleSPV** [comment]
We need an event similar than the OnCalcLineTotalOnBeforeCalcTotalAmountVATEntryTotaling before the CalculateTotalAmount call.
The parameters are the same, just adding the decimal Base as we have for the Amount.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
