### ISSUE TITLE
[Request for external] Codeunit 740 VAT Report Mediator 

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#15578]
Please make function GetVATReportConfiguration in the Codeunit 740 in the W1 Version externally available.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
