### ISSUE TITLE
Codeunit 99000810 "Calculate Planning Route Line" New Publisher Events and Adjustments to Publisher Events

### ISSUE THREAD

**Issue by TroelsMuffThygesen** [microsoft/ALAppExtensions#15575]
Hello,
We would like to be able to adjust have Load calculations are done in codeunit 99000810 "Calculate Planning Route Line" and therefore we would like you to adjust one Publisher Event function and add a few new ones.

First of all please make the ProdStartingTime variable passed by reference as it is in the equivalent function in the codeunit 99000774 "Calculate Routing Line".
Current version of the publisher function:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeLoadCapForward(var PlanningRoutingLine: Record "Planning Routing Line"; TimeType: Enum "Routing Time Type"; var ProdStartingDate: Date; ProdStartingTime: Time; var IsHandled: Boolean)
    begin
    end;
```
Adjusted version of the publisher function:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeLoadCapForward(var PlanningRoutingLine: Record "Planning Routing Line"; TimeType: Enum "Routing Time Type"; var ProdStartingDate: Date; var ProdStartingTime: Time; var IsHandled: Boolean)
    begin
    end;
```

Please use the GetConstrainedCapacity function for retreiving the ConstraingedCapacity and ParentWorkCenter in the CalcRoutingLineForward function, so that we will be able to control this by subscribing to the OnBeforeGetConstrainedCapacity publisher. This will make it work the same way as in the CalcRoutingLineBack function.
Current version of the code in CalcRoutingLineForward function:
```
            ResourceIsConstrained := ConstrainedCapacity.Get(Type, "No.");
            ParentIsConstrained := ParentWorkCenter.Get(Type::"Work Center", "Work Center No.");
```
Adjusted version of the code in CalcRoutingLineForward function:
```
            ResourceIsConstrained := GetConstrainedCapacity(Type, "No.", ConstrainedCapacity);
            ParentIsConstrained := GetConstrainedCapacity(Type::"Work Center", "Work Center No.", ParentWorkCenter);
```
The above code sections exist twice in the function and both places should be updated. 

Please create a new publisher event function OnBeforeFinitelyLoadCapForward and call it as the first thing in the FinitelyLoadCapForward function with the IsHandled pattern.
New Publisher Event Function:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeFinitelyLoadCapForward (var PlanningRoutingLine: Record "Planning Routing Line"; TimeType: Enum "Routing Time Type"; var ProdStartingDate: Date; var ProdStartingTime: Time; var IsHandled: Boolean)
    begin
    end;
```
New function call in the FinitelyLoadCapForward function:
```
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeLoadCapForward(PlanningRoutingLine, TimeType, ProdStartingDate, ProdStartingTime, IsHandled);
        if IsHandled then
            exit;
```

In order to align how things are working when calculating forward and backward, it would be nice if the same subscriber functions with calls and IsHandled pattern are availlable in both set up functions. At the moment there is no OnBeforeLoadCapBack function call in the LoadCapBack function event though there is one in the LoadCapForward function. And if you introduce the OnBeforeFinitelyLoadCapForward in the FinitelyLoadCapForward function then you should also consider adding such a publisher call in the FinitelyLoadCapBack function.

Hope to hear from you soon.
Kind Regards 
Troels Muff Thygesen

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
