### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post OnBeforeCreatePrepmtLines

### ISSUE THREAD

**Issue by LukaszJessa** [microsoft/ALAppExtensions#15584]
Hi AL-Team,

Due to customer customization in prepayments, we need one extra parameter in publisher in CU 90 (TempPurchLineGlobal).
In CU 80 for same functionality on sales side there is such parameter. 

Function: CreatePrepmtLines

Current code:
OnBeforeCreatePrepmtLines(PurchHeader, TempPrepmtPurchLine, CompleteFunctionality, IsHandled);

Requested code:
OnBeforeCreatePrepmtLines(PurchHeader, TempPrepmtPurchLine, CompleteFunctionality, IsHandled, TempPurchLineGlobal);

Current Publisher signature:     [IntegrationEvent(false, false)] local procedure OnBeforeCreatePrepmtLines(PurchaseHeader: Record "Purchase Header"; var TempPrepmtPurchaseLine: Record "Purchase Line" temporary; CompleteFunctionality: Boolean; var IsHandled: Boolean)

Requested Publisher signature:     [IntegrationEvent(false, false)] local procedure OnBeforeCreatePrepmtLines(PurchaseHeader: Record "Purchase Header"; var TempPrepmtPurchaseLine: Record "Purchase Line" temporary; CompleteFunctionality: Boolean; var IsHandled: Boolean; TempPurchLineGlobal: Record "Purchase Line" temporary)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
