### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post OnCreatePrepmtLinesOnAfterTempPrepmtPurchLineSetFilters

### ISSUE THREAD

**Issue by LukaszJessa** [microsoft/ALAppExtensions#15583]
Hi AL-Team,

Due to customer customization in prepayments, we need one extra parameter in publisher in CU 90 (TempPurchLine).

Function: CreatePrepmtLines

Current code:
OnCreatePrepmtLinesOnAfterTempPrepmtPurchLineSetFilters(TempPrepmtPurchLine);

Requested code:
OnCreatePrepmtLinesOnAfterTempPrepmtPurchLineSetFilters(TempPrepmtPurchLine,TempPurchLine);

Current Publisher signature: [IntegrationEvent(false, false)] local procedure OnCreatePrepmtLinesOnAfterTempPrepmtPurchLineSetFilters(var TempPrepmtPurchLine: Record "Purchase Line" temporary)

Requested Publisher signature: [IntegrationEvent(false, false)] local procedure OnCreatePrepmtLinesOnAfterTempPrepmtPurchLineSetFilters(var TempPrepmtPurchLine: Record "Purchase Line" temporary; TempPurchLine: Record "Purchase Line" temporary)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
