### ISSUE TITLE
[Event-Request] Codeunit 21 "Item Jnl.-Check Line" OnCheckDimensionsOnAfterAssignDimTableIDs

### ISSUE THREAD

**Issue by DanielBalanCgk** [microsoft/ALAppExtensions#15581]
We would like to request an event in procedure CheckDimensions() from codeunit 21 "Item Jnl.-Check Line"

    local procedure CheckDimensions(ItemJnlLine: Record "Item Journal Line")
    var
        TableID: array[10] of Integer;
        No: array[10] of Code[20];
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckDimensions(ItemJnlLine, CalledFromAdjustment, IsHandled);
        if IsHandled then
            exit;

        with ItemJnlLine do
            if not IsValueEntryForDeletedItem and not Correction and not CalledFromAdjustment then begin
                if not DimMgt.CheckDimIDComb("Dimension Set ID") then
                    Error(DimCombBlockedErr, "Journal Template Name", "Journal Batch Name", "Line No.", DimMgt.GetDimCombErr);
                if "Item Charge No." = '' then begin
                    TableID[1] := DATABASE::Item;
                    No[1] := "Item No.";
                end else begin
                    TableID[1] := DATABASE::"Item Charge";
                    No[1] := "Item Charge No.";
                end;
                TableID[2] := DATABASE::"Salesperson/Purchaser";
                No[2] := "Salespers./Purch. Code";
                TableID[3] := DATABASE::"Work Center";
                No[3] := "Work Center No.";

                OnCheckDimensionsOnAfterAssignDimTableIDs(ItemJnlLine, TableID, No);

                if not DimMgt.CheckDimValuePosting(TableID, No, "Dimension Set ID") then begin
                    if "Line No." <> 0 then
                        Error(DimCausedErr, "Journal Template Name", "Journal Batch Name", "Line No.", DimMgt.GetDimValuePostingErr);
                    Error(DimMgt.GetDimValuePostingErr);
                end;
                if ("Entry Type" = "Entry Type"::Transfer) and
                   ("Value Entry Type" <> "Value Entry Type"::Revaluation)
                then
                    if not DimMgt.CheckDimIDComb("Dimension Set ID") then begin
                        if "Line No." <> 0 then
                            Error(DimCausedErr, "Journal Template Name", "Journal Batch Name", "Line No.", DimMgt.GetDimValuePostingErr);
                        Error(DimMgt.GetDimValuePostingErr);
                    end;
            end;
    end;

    [IntegrationEvent(true, false)]
    local procedure OnCheckDimensionsOnAfterAssignDimTableIDs(var ItemJnlLine: Record "Item Journal Line"; var TableID: array[10] of Integer; var No: array[10] of Code[20])
    begin
    end;

**This is similar with what we have already on codeunit 11 "Gen. Jnl.-Check Line"**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
