### ISSUE TITLE
[Event-Request] Codeunit 211 "Res. Jnl.-Check Line" OnCheckDimensionsOnAfterAssignDimTableIDs

### ISSUE THREAD

**Issue by DanielBalanCgk** [microsoft/ALAppExtensions#15580]
We would like to request an event in procedure CheckDimensions() from codeunit 211 "Res. Jnl.-Check Line"

    local procedure CheckDimensions(ResJnlLine: Record "Res. Journal Line")
    var
        TableID: array[10] of Integer;
        No: array[10] of Code[20];
        IsHandled: Boolean;

    begin
        IsHandled := false;
        OnBeforeCheckDimensions(ResJnlLine, IsHandled);
        if IsHandled then
            exit;

        with ResJnlLine do begin
            if not DimMgt.CheckDimIDComb("Dimension Set ID") then
                Error(
                  Text002,
                  TableCaption, "Journal Template Name", "Journal Batch Name", "Line No.",
                  DimMgt.GetDimCombErr);

            TableID[1] := DATABASE::Resource;
            No[1] := "Resource No.";
            TableID[2] := DATABASE::"Resource Group";
            No[2] := "Resource Group No.";
            TableID[3] := DATABASE::Job;
            No[3] := "Job No.";

            OnCheckDimensionsOnAfterAssignDimTableIDs(ResJnlLine, TableID, No);
            
            if not DimMgt.CheckDimValuePosting(TableID, No, "Dimension Set ID") then
                if "Line No." <> 0 then
                    Error(
                      Text003,
                      TableCaption, "Journal Template Name", "Journal Batch Name", "Line No.",
                      DimMgt.GetDimValuePostingErr)
                else
                    Error(DimMgt.GetDimValuePostingErr);
        end;
    end;

    [IntegrationEvent(true, false)]
    local procedure OnCheckDimensionsOnAfterAssignDimTableIDs(var ResJournalLine: Record "Res. Journal Line"; var TableID: array[10] of Integer; var No: array[10] of Code[20])
    begin
    end;

**This is similar with what we have already on codeunit 11 "Gen. Jnl.-Check Line"**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
