### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post OnCreatePrepaymentLinesOnAfterTempPrepmtSalesLineSetFilters

### ISSUE THREAD

**Issue by LukaszJessa** [microsoft/ALAppExtensions#15582]
Hi AL-Team,

Due to customer customization in prepayments, we need one extra parameter in publisher in CU 80 (TempSalesLine).

Function: CreatePrepaymentLines

Current code:
OnCreatePrepaymentLinesOnAfterTempPrepmtSalesLineSetFilters(TempPrepmtSalesLine);

Requested code:
OnCreatePrepaymentLinesOnAfterTempPrepmtSalesLineSetFilters(TempPrepmtSalesLine,TempSalesLine);

Current Publisher signature: [IntegrationEvent(false, false)] local procedure OnCreatePrepaymentLinesOnAfterTempPrepmtSalesLineSetFilters(var TempPrepmtSalesLine: Record "Sales Line" temporary)

Requested Publisher signature: [IntegrationEvent(false, false)] local procedure OnCreatePrepaymentLinesOnAfterTempPrepmtSalesLineSetFilters(var TempPrepmtSalesLine: Record "Sales Line" temporary; TempSalesLine: Record "Sales Line" temporary;)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
