### ISSUE TITLE
[Event Request] page 408 "G/L Balance by Dimension" - OnOpenPageOnBeforeFindPeriod

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#15599]
Can you add event OnOpenPageOnBeforeFindPeriod in trigger OnOpenPage before FindPeriod with IncludeSender = true, so I can set my own global variables?

```
        LineDimOption := DimCodeToOption(LineDimCode);
        ColumnDimOption := DimCodeToOption(ColumnDimCode);

        //AZ99999+
        OnOpenPageOnBeforeFindPeriod(GLSetup, GLAcc);
        //AZ99999-
        FindPeriod('');

        MATRIX_NoOfColumns := 32;
        SetDateFilter("Date Filter");
```

```
    [IntegrationEvent(true, false)]
    local procedure OnOpenPageOnBeforeFindPeriod(GLSetup: Record "General Ledger Setup"; var GLAccount: Record "G/L Account")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
