### ISSUE TITLE
codeunit 378 "Transfer Extended Text" Method OnInsertServExtTextOnBeforeToServiceLineInsert. Tag: 20.0.

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#15594]
Method '**OnBeforeToServiceLineInsert**' is marked for removal. 
Reason: Replaced with **OnInsertServExtTextOnBeforeToServiceLineInsert**. Tag: 20.0.
New Method has paramether ToSrevLine NOT as VAR, and it should have

**OLD**
    [IntegrationEvent(false, false)]
    [Obsolete('Replaced with OnInsertServExtTextOnBeforeToServiceLineInsert', '20.0')]
    local procedure OnBeforeToServiceLineInsert**(var ToServLine: Record "Service Line"; ServLine: Record "Service Line";** TempExtTextLine: Record "Extended Text Line" temporary; var NextLineNo: Integer; LineSpacing: Integer)
    begin
    end;
**NEW**
    [IntegrationEvent(false, false)]
    local procedure OnInsertServExtTextOnBeforeToServiceLineInsert(**var ServLine: Record "Service Line"; ToServLine: Record "Service Line"**; TempExtTextLine: Record "Extended Text Line" temporary; var NextLineNo: Integer; LineSpacing: Integer)
    begin
    end;
**NEW CORRECTED**
    [IntegrationEvent(false, false)]
    local procedure OnInsertServExtTextOnBeforeToServiceLineInsert(**var ServLine: Record "Service Line"; var ToServLine: Record "Service Line"**; TempExtTextLine: Record "Extended Text Line" temporary; var NextLineNo: Integer; LineSpacing: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
