### ISSUE TITLE
[Event Request] page 408 "G/L Balance by Dimension" - OnAfterOnInit

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#15598]
Can you add event OnAfterOnInit with IncludeSender = true to be able to set new global variabel in event.
Like "Dim1FilterEnable := true;" i want to set my own variabel to true.

```
    trigger OnInit()
    var
        "Field": Record "Field";
    begin
        Dim2FilterEnable := true;
        Dim1FilterEnable := true;
        Field.Get(DATABASE::"G/L Account", 42);
        BusUnitFilterCaption := Field."Field Caption";
        //AZ99999+
        OnAfterOnInit();
        //AZ99999-
    end;
```

```
    [IntegrationEvent(true, false)]
    local procedure OnAfterOnInit()
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
