### ISSUE TITLE
[Enum Request] - codeunit "Available to promise" - CalculateLookahead

### ISSUE THREAD

**Issue by tguyonnet** [microsoft/ALAppExtensions#15619]
procedure CalculateLookahead(var Item: Record Item; PeriodType: Option Day,Week,Month,Quarter,Year; StartDate: Date; EndDate: Date)

Replace parameter PeriodType: Option 
by PeriodType: Enum "Analysis Period Type"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
