### ISSUE TITLE
[Enum Request] - Codeunit DimensionManagement - TypeToTableID3

### ISSUE THREAD

**Issue by tguyonnet** [microsoft/ALAppExtensions#15618]
procedure TypeToTableID3(Type: Option " ","G/L Account",Item,Resource,"Fixed Asset","Charge (Item)")

Replace option parameter Type
with enum "Sales Line Type"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
