### ISSUE TITLE
[Enum Request] - codeunit "Available to Promise" - QtyAvailabletoPromise

### ISSUE THREAD

**Issue by tguyonnet** [microsoft/ALAppExtensions#15616]
Replace parameter PeriodType: Option
By Enum "Analysis Period Type"

**Comment by AlexanderYakunin** [comment]
Please explain why do you need this? It can be large refactoring, what is the purpose of this?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
