### ISSUE TITLE
[Event Request] Codeunit 10753 "SII Job Upload Pending Docs.": Include IsHandled into OnBeforeOnAfterPostServiceDoc

### ISSUE THREAD

**Issue by deadmouse** [microsoft/ALAppExtensions#15621]
[Event Request] Codeunit 10753 "SII Job Upload Pending Docs.": Include _IsHandled_ into OnBeforeOnAfterPostServiceDoc

```
procedure OnAfterPostServiceDoc(var ServiceHeader: Record "Service Header")
var
    SIISetup: Record "SII Setup";
begin
///////// START
IsHandled := false;
OnBeforeOnAfterPostServiceDoc(ServiceHeader, IsHandled);
if not IsHandled then
    exit;
.
.
.
///////// END
```

Signature:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeOnAfterPostServiceDoc(var ServiceHeader: Record "Service Header"; var IsHandled: Boolean)
begin
end;
```

**Comment by deadmouse** [comment]
Not needed anymore.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
