### ISSUE TITLE
CRM integration doesn't calculate CDS flowfields anymore

### ISSUE THREAD

**Issue by JohnFrostDP** [microsoft/ALAppExtensions#15633]
Hi all,

While working on our CRM integration we noticed that some of our integration didn't work anymore. After some research we found that the calculation of the field ref isn't executed in more recent code of BC, which always results in a null guid. This means that the sync doesn't have the necessary information to fill certain fields. 

We also saw that this is because of the following code in the CRM integration(codeunit 5336). Below a piece of code in version 18.5.29545.31110 (although not exactly sure this is the version where it changed). Notice that there is only a check for a class, which means that the flowfield is always calculated. Even on CDS pages.
![image](https://user-images.githubusercontent.com/92578153/147230994-fcd48973-4f69-44db-a8c7-622a9ef67064.png)

in a later version there is a check that prevents using flowfields on CRM CDS pages.  the code is now:
![image](https://user-images.githubusercontent.com/92578153/147235154-4fb49dde-325c-487d-8404-be232ee7ffa5.png)

They build a solution for blob fields, but by doing that they exclude the use of flowfields on CRM CDS. Because that is not a real table and is an external table. This is a major issue in my opinion because integration with CRM can break from one version to another. We had to fix it by calculating the field on the event OnFindNewValueForCoupledRecordPK. It works again, but still it should just work in the standard code. 

Please fix this in upcoming releases.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.

**Comment by JohnFrostDP** [comment]
I can see that it is changed. Thank You!
![image](https://user-images.githubusercontent.com/92578153/161935148-04ea7357-9ae0-4543-97c4-b2714325c86d.png)
