### ISSUE TITLE
Codeunit 426 - Suppress Payment Tolerance Warning

### ISSUE THREAD

**Issue by obychyk** [microsoft/ALAppExtensions#15637]
Hello,

We have a case when we reconcile a large number of **Table 11401 "CBG Statement Line"** records. After the import of the bank statement, the reconciliation is called. We are using **Codeunit 426 "Payment Tolerance Management"** -> `procedure PmtTolGenJnl(var NewGenJnlLine: Record "Gen. Journal Line"): Boolean`, which, eventually, triggers page 591 "Payment Tolerance Warning" if the setup in table 98 "General Ledger Setup", field 101 "Payment Tolerance Warning" is enabled (CU 426 -> `local procedure CallPmtTolWarning`). 
Our case requires that only during a custom reconciliation we don't want to show the page with Payment Tolerance Warning, as, due to the size of the import, it's unrealistic to work with such functionality (pressing "Put Amount as Payment Tolerance" action many times), but in all other cases, we would like to show the pop-up. The available event `OnBeforeRunModalPmtTolWarningCallPmtTolWarning` can't be used as if we are going to set `IsHandled := true` then this is going to influence all other reconciliations (e.g. Cash Receipt Journal) and other parameters, which are available in the mentioned event, do not provide enough distinguishability for the custom flow.
At the moment, we've overcome the restriction by copying Codeunit 426 "Payment Tolerance Management" into the custom range and by removing the pop-up from the functionality, but, as you can imagine, this approach is far from being at least good, as we are going to lose the bug fixes with Cumulative Updates and it's going to be hard to upgrade to the new versions of BC.
Can you please add a `SetHidePaymentToleranceWarning` function into Codeunit 426 "Payment Tolerance Management" -> `CallPmtDiscTolWarning` and `CallPmtTolWarning` in order to be able to suppress the warning and `exit(true);` from the functions if the function is called (similar to `procedure SetHideValidationDialog(NewHideValidationDialog: Boolean)` in table 36 "Sales Header")? That way we would be able to use the standard CU and suppress the warning only for a single reconciliation flow.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
