### ISSUE TITLE
Table 7001 "Price List Line" new Subscriber OnAfterLookupAssetNo

### ISSUE THREAD

**Issue by OlgicaA** [microsoft/ALAppExtensions#15636]
**We dont have subscriber On After Lookup to which we can subscribe**

        field(8; "Asset No."; Code[20])
        {
            Caption = 'Product No.';
            DataClassification = CustomerContent;
            NotBlank = true;

            trigger OnValidate()
            begin
                TestStatusDraft();
                if not FieldLookedUp then begin
                    CopyRecTo(PriceAsset);
                    PriceAsset.Validate("Asset No.", "Asset No.");
                end;
                CopyFrom(PriceAsset);
            end;

            trigger OnLookup()
            begin
                CopyTo(PriceAsset);
                if PriceAsset.LookupNo() then begin
                    FieldLookedUp := true;
                    Validate("Asset No.", PriceAsset."Asset No.");
                    FieldLookedUp := false;
                end;
            end;
        }

**Comment by dnpb** [comment]
Can you use OnLookup() or OnAfterLookup() on the page extension instead?

If you need a new event, you'll need to show its publisher signature and how it should be called.

**Comment by StanPesotskiy** [comment]
@OlgicaA 
Please always put the full detailed signature of the requested events and the parameters passed in the call.
Please put the code surrounding the place, where you expect a new event call, as a text not as a screenshot. 
It helps us finding the right place quickly if you put enough code to identify the unique place.
