### ISSUE TITLE
[Access Request] table 5767 "Warehouse Activity Line" - FindBinCode

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#15645]
Could you please make the procedure `` of the `table 5767 "Warehouse Activity Line"` accessible from external and remove the local scope?
```al
//-local procedure FindBinCode() BinCode: Code[20] //OLD
procedure FindBinCode() BinCode: Code[20] //NEW
var
    WhseItemTrackingSetup: Record "Item Tracking Setup";
    IsHandled: Boolean;
begin

    ...

end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
