### ISSUE TITLE
[Field Group] Table 308 "No. Series"

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#15640]
Hi,

please add field group to Table 308 "No. Series" so DropDown can be extended with more fields from extensions.

Code to be added after Keys section:

```
    fieldgroups
    {
        fieldgroup(DropDown; Code, Description) { }
        fieldgroup(Brick; Code, Description) { }
    }
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
