### ISSUE TITLE
[extensibility-enhancement] Page 1117 "Cost Budget per Period" Please add SetCostObjectCodeFilter

### ISSUE THREAD

**Issue by elweilando** [microsoft/ALAppExtensions#15641]
Please add in Page 1117 "Cost Budget per Period" the possibility to set the filter for Cost Object from external.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
