### ISSUE TITLE
[Scope Change] table 263 "Intrastat Jnl. Line", procedure IsVendorPrivatePerson

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#15653]
Please change the scope of `procedure IsVendorPrivatePerson` to `public`.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
