### ISSUE TITLE
[Event Request] table 263 "Intrastat Jnl. Line", OnBeforeGetPartnerID

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#15654]
Please add a new event `OnBeforeGetPartnerID`:
```al
  procedure GetPartnerID()
+ var
+     IsHandled: Boolean;
  begin
+     IsHandled := false;
+     OnBeforeGetPartnerID(Rec, IsHandled);
+     if IsHandled then
+         exit;

      case "Source Type" of
      ...
      end;
  end;

+ [IntegrationEvent(false, false)]
+ local procedure OnBeforeGetPartnerID(var IntrastatJnlLine: Record "Intrastat Jnl. Line"; var IsHandled: Boolean)
+ begin
+ end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
