### ISSUE TITLE
[Change Request] Codeunit 7324 "Whse.-Activity-Post" – Procedure “CreateWhseJnlLine” local to global

### ISSUE THREAD

**Issue by eknraw** [microsoft/ALAppExtensions#15656]
Could we please have the existing procedure “CreateWhseJnlLine”,  Codeunit 7324 "Whse.-Activity-Post be set to global or have a new function expose it?

OLD:
```
    local procedure CreateWhseJnlLine(var WhseJnlLine: Record "Warehouse Journal Line"; WhseActivLine: Record "Warehouse Activity Line")
    var
        WMSMgt: Codeunit "WMS Management";
    begin
        with WhseActivLine do begin
            WhseJnlLine.Init();
```

NEW
```
 procedure CreateWhseJnlLine(var WhseJnlLine: Record "Warehouse Journal Line"; WhseActivLine: Record "Warehouse Activity Line")
    var
        WMSMgt: Codeunit "WMS Management";
    begin
        with WhseActivLine do begin
            WhseJnlLine.Init();
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
