### ISSUE TITLE
[Event Request] table 263 "Intrastat Jnl. Line", OnBeforeGetCountryOfOriginCode

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#15655]
Please add a new event OnBeforeGetCountryOfOriginCode:
```al
  procedure GetCountryOfOriginCode()
+ var
+     IsHandled: Boolean;
  begin
+     IsHandled := false;
+     OnBeforeGetCountryOfOriginCode(Rec, IsHandled);
+     if IsHandled then
+         exit;
      ...
  end;

+ [IntegrationEvent(false, false)]
+ local procedure OnBeforeGetCountryOfOriginCode(var IntrastatJnlLine: Record "Intrastat Jnl. Line"; var IsHandled: Boolean)
+ begin
+ end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
