### ISSUE TITLE
[Event Request] Codeunit 260 Document-Mailing

### ISSUE THREAD

**Issue by MisterTrojan** [Microsoft/ALAppExtensions#1566]
Heyy,

I Need a possibility to init the Page 9700 based on the related document. (not only posted).

Atm there is an Event OnBeforeSendEmail.
Can you add a Parameter to get the current document (eg. RecRef, Variant,...)?

If this is not possible it would also help to get an event to init TempEmailItem on a place where we have access to the current record (eg. T77 ReportSelection.SendEmailDirectly and also add the parameter EmailItem to DocumentMailing.EmailFile).

If you already have a external function or anything else to send a document and be able to init Mail addresses, names and file names please tell me :)

**Comment by AlexanderYakunin** [comment]
In event OnBeforeSendEmail(TempEmailItem,IsFromPostedDoc,PostedDocNo,HideDialog,ReportUsage) you have PostedDocNo and ReportUsage, and can identify document.

**Comment by BeefHigi** [comment]
> In event OnBeforeSendEmail(TempEmailItem,IsFromPostedDoc,PostedDocNo,HideDialog,ReportUsage) you have PostedDocNo and ReportUsage, and can identify document.

Thanks for the Reply.
Isn´t the PostedDocNo only filled if it´s a posted document?

If not is there a available (external) function to get the unposted document type by ReportUsage?

**Comment by AlexanderYakunin** [comment]
Look into TAB77, same used for sending unposted documents
