### ISSUE TITLE
[Extensibility enhancement] report 8 Budget - Getters needed

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15667]
Hello,

We need these getters:

![image](https://user-images.githubusercontent.com/33875371/147738309-b745a11b-df8b-468a-9a9e-80ea7a5c53ef.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
