### ISSUE TITLE
[Event request] codeunit 80 "Sales-Post" - TestSalesLine

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15660]
Hello,

Could you add this Handled event, please?

![image](https://user-images.githubusercontent.com/33875371/147666116-941bd134-3738-4875-9a0e-6d9934b9a941.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
