### ISSUE TITLE
[Event Request] report 1401 Check - VendUpdateAmounts

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15669]
Hello,

We need this publisher:

![image](https://user-images.githubusercontent.com/33875371/147741208-52302100-dbeb-4cc3-a159-bba71aa956fc.png)
![image](https://user-images.githubusercontent.com/33875371/147741262-d343d66b-6545-4ef9-a715-0f0cae011514.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
