### ISSUE TITLE
[Event Request] report 1401 Check - OnAfterGetRecord

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15668]
Hello,

Publisher is needed:

![image](https://user-images.githubusercontent.com/33875371/147741023-9eefcff4-5adb-459b-8b2c-49385933a642.png)
![image](https://user-images.githubusercontent.com/33875371/147741085-8328711c-505d-4d19-bc38-586871e85694.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
