### ISSUE TITLE
[Extensibility Enhancement] codeunit 6620 "Copy Document Mgt." - CheckCreditLimit

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15673]
Hello,

Please add IncludeHeader and HideDialog arguments of OnBeforeCheckCreditLimit publisher:

![image](https://user-images.githubusercontent.com/33875371/147743503-95815dbd-8248-48a5-90e6-4492eea353a7.png)
![image](https://user-images.githubusercontent.com/33875371/147743530-3c88da4c-2b97-4c39-9108-bfb8912ae42e.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
