### ISSUE TITLE
[Extensibility Enhancement] codeunit 365 "Format Address" - GeneratePostCodeCity

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15679]
Hello,

Please change the scope of GeneratePostCodeCity() to global.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
