### ISSUE TITLE
[Event Request] codeunit 365 "Format Address" - SetLineNos

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15678]
Hello,

Please add this handled event:

![image](https://user-images.githubusercontent.com/33875371/147745629-4250210c-4e4d-430a-9288-8a4c4db998b7.png)
![image](https://user-images.githubusercontent.com/33875371/147745708-95839a9b-25f2-47d5-b8b9-a359dacbfd39.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
