### ISSUE TITLE
[Extensibility Enhancement] page 343 "Check Credit Limit" - ShowWarning

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15670]
Hello,

Please add OrderAmountThisOrderLCY to arguments of OnBeforeShowWarning publisher.

Publisher Old:
OnBeforeShowWarning(Rec, NewOrderAmountLCY, OldOrderAmountLCY, OrderAmountTotalLCY, ShippedRetRcdNotIndLCY, CustCreditAmountLCY, DeltaAmount, CheckOverDueBalance, Heading, Result, IsHandled, NotificationId, NewCustNo, NewOrderAmountLCY2, OldOrderAmountLCY2);

Publisher New:
OnBeforeShowWarning(Rec, NewOrderAmountLCY, OldOrderAmountLCY, OrderAmountTotalLCY, ShippedRetRcdNotIndLCY, CustCreditAmountLCY, DeltaAmount, CheckOverDueBalance, Heading, Result, IsHandled, NotificationId, NewCustNo, NewOrderAmountLCY2, OldOrderAmountLCY2, OrderAmountThisOrderLCY);

![image](https://user-images.githubusercontent.com/33875371/147741807-2c46e2c2-5f14-424e-814b-be7fa98fe1a3.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
