### ISSUE TITLE
Table "Warehouse Shipment Header" (7320) Local Procedure DeleteWarehouseShipmentLines to public procedure

### ISSUE THREAD

**Issue by Mfelice1975** [microsoft/ALAppExtensions#15676]
Please, could we have this change on Table 7320 ("Warehouse Shipment Header") :

OLD
    local procedure DeleteWarehouseShipmentLines()

NEW
    procedure DeleteWarehouseShipmentLines()

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
