### ISSUE TITLE
[Extensibility Enhancement] table 370 "Excel Buffer" - ParseCellValue

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15677]
Hello,

Could you please change the scope of the ParseCellValue() procedure to global?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
