### ISSUE TITLE
[Event Request] codeunit 5701 "Item Subst." - ItemServiceSubstGet

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15687]
Hello,

Please add these handled events to ItemServiceSubstGet()

![image](https://user-images.githubusercontent.com/33875371/147748222-956bd410-ee28-4318-b219-31510e0d81dd.png)
![image](https://user-images.githubusercontent.com/33875371/147748247-046de5fa-bf26-4835-824d-b75151c945af.png)

![image](https://user-images.githubusercontent.com/33875371/147748298-fc5bc889-8d93-4553-8312-61a4cd6f9e88.png)
![image](https://user-images.githubusercontent.com/33875371/147748271-7205263d-0a0b-484f-9296-37024fc685b9.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
