### ISSUE TITLE
[Event Request] codeunit 5701 "Item Subst." - CalcCustPrice

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15686]
Hello,

Please add this handled event:

![image](https://user-images.githubusercontent.com/33875371/147747956-38de354f-817d-4bab-a322-c6e9cc731169.png)
![image](https://user-images.githubusercontent.com/33875371/147747984-b2ce01cf-ae00-4731-9dc3-b893d0ec4d5b.png)

**Comment by Stepanenko-Vadim** [comment]
You can clear any fields or assign any other values you want before inserting in **OnCalcCustPriceOnBeforeTempItemSubstitutionInsert** event instead.
