### ISSUE TITLE
[Extensibility Enhancement] page 5857 "Get Post.Doc - P.InvLn Subform" - DocumentNoHideValue

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15680]
Hello,

Please make DocumentNoHideValue variable protected:

![image](https://user-images.githubusercontent.com/33875371/147746799-48f55d96-d272-4416-a02a-b62e8c9aa34f.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
