### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - PostItemLine

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15698]
Hello,

Please add this handled event:

![image](https://user-images.githubusercontent.com/33875371/147750324-25dd47c3-ac59-464d-b23e-9f64c3af90ca.png)
![image](https://user-images.githubusercontent.com/33875371/147750340-c76f7409-fe37-439a-afdd-c7c69ab9770c.png)

**Comment by StanPesotskiy** [comment]
@NiroWolfee You help us implementing the requests faster when your request contains AL code copied from VSCode as a text instead of screenshots.

**Comment by StanPesotskiy** [comment]
Please use the existing event OnBeforePostItemLine()
