### ISSUE TITLE
[Event Request] codeunit 99000834 "Purch. Line-Reserve" - VerifyQuantity

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15694]
Hello,

Please add this handled event:

![image](https://user-images.githubusercontent.com/33875371/147749929-29adca96-4f66-4a8a-a954-1d75e8539a7d.png)
![image](https://user-images.githubusercontent.com/33875371/147749943-d2ae0e1c-90e3-459b-911a-ffd540f03676.png)

**Comment by StanPesotskiy** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode as a text instead of screenshots.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
