### ISSUE TITLE
[Event Request] codeunit 99000834 "Purch. Line-Reserve" - RetrieveInvoiceSpecification2

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15697]
Hello,

Please add this handled event:

![image](https://user-images.githubusercontent.com/33875371/147750160-7333c9ca-e908-42bf-8ab1-8fbf4e8190b6.png)
![image](https://user-images.githubusercontent.com/33875371/147750169-677cab08-fb90-48d5-b275-d0a8de726cb7.png)

**Comment by StanPesotskiy** [comment]
@NiroWolfee You help us implementing the requests faster when your request contains AL code copied from VSCode as a text instead of screenshots.
