### ISSUE TITLE
[Event Request] codeunit 99000834 "Purch. Line-Reserve" - AssignForPlanning

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15695]
Hello,

Please add this handled event:

![image](https://user-images.githubusercontent.com/33875371/147750009-ea4b4590-83aa-4c75-9773-1808db84be18.png)
![image](https://user-images.githubusercontent.com/33875371/147750026-c5b4271e-d328-42af-ae54-d51b727f1c4a.png)

**Comment by StanPesotskiy** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode as a text instead of screenshots.
