### ISSUE TITLE
[Event Request] table 39 "Purchase Line" - "Unit Cost (LCY)" -> OnValidate

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15692]
Hello,

Please add the following handled events:

![image](https://user-images.githubusercontent.com/33875371/147749629-d58f5768-bb0e-4002-9141-a9621304bd85.png)
![image](https://user-images.githubusercontent.com/33875371/147749656-7e37d7e1-3d46-44de-b731-4afeea370263.png)

![image](https://user-images.githubusercontent.com/33875371/147749690-faf3e9fa-aa35-43b1-9475-64f646c42987.png)
![image](https://user-images.githubusercontent.com/33875371/147749715-73a4fda0-4387-49c0-a43e-71695b1e972b.png)

**Comment by StanPesotskiy** [comment]
@NiroWolfee You help us implementing the requests faster when your request contains AL code copied from VSCode as a text instead of screenshots.

**Comment by NiroWolfee** [comment]
field(23; "Unit Cost (LCY)"; Decimal)
        {
            AutoFormatType = 2;
            Caption = 'Unit Cost (LCY)';

            trigger OnValidate()
            var
                Item: Record Item;
                IndirectCostPercent: Decimal;
                //Request
                IsHandled: Boolean;
                //Request
            begin
                TestStatusOpen();
                TestField("No.");
                //Request
                IsHandled := false;
                OnValidateUnitCostLCYOnBeforeTestQuantity(Rec, IsHandled); //CustPub
                if not IsHandled then
                    TestField(Quantity);
                //Request

                if "Prod. Order No." <> '' then
                    Error(
                      Text99000000,
                      FieldCaption("Unit Cost (LCY)"));

                if CurrFieldNo = FieldNo("Unit Cost (LCY)") then
                    if Type = Type::Item then begin
                        GetItem(Item);
                        if Item."Costing Method" = Item."Costing Method"::Standard then
                            Error(
                              Text010,
                              FieldCaption("Unit Cost (LCY)"), Item.FieldCaption("Costing Method"), Item."Costing Method");
                    end;

                UnitCostCurrency := "Unit Cost (LCY)";
                GetPurchHeader();
                if PurchHeader."Currency Code" <> '' then begin
                    PurchHeader.TestField("Currency Factor");
                    GetGLSetup();
                    UnitCostCurrency :=
                      Round(
                        CurrExchRate.ExchangeAmtLCYToFCY(
                          GetDate, "Currency Code",
                          "Unit Cost (LCY)", PurchHeader."Currency Factor"),
                        GLSetup."Unit-Amount Rounding Precision");
                end;

                OnValidateUnitCostLCYOnAfterUpdateUnitCostCurrency(Rec, UnitCostCurrency);

                "Indirect Cost %" := 0;
                //Request
                IsHandled := false;
                OnValidateUnitCostLCYOnBeforeAssignIndirectCost(Rec, UnitCostCurrency, IsHandled); //CustPub
                if not IsHandled then
                    if ("Direct Unit Cost" <> 0) and
                    ("Direct Unit Cost" <> ("Line Discount Amount" / Quantity))
                    then begin
                        IndirectCostPercent :=
                        Round(
                            (UnitCostCurrency - "Direct Unit Cost" + "Line Discount Amount" / Quantity) /
                            ("Direct Unit Cost" - "Line Discount Amount" / Quantity) * 100, 0.00001);
                        if IndirectCostPercent >= 0 then begin
                            "Indirect Cost %" := IndirectCostPercent;
                            CheckLineTypeOnIndirectCostPercentUpdate();
                        end;
                    end;
                //Request

                UpdateSalesCostFromUnitCostLCY();

                if JobTaskIsSet then begin
                    CreateTempJobJnlLine(false);
                    TempJobJnlLine.Validate("Unit Cost (LCY)", "Unit Cost (LCY)");
                    UpdateJobPrices();
                end
            end;
        }

**Comment by StanPesotskiy** [comment]
Please always put the full detailed signature of the requested events and the parameters passed in the call.

**Comment by StanPesotskiy** [comment]
It will be very appreciated if you went through all your requests and replaced all screenshots with plain text. 
Thank you!

**Comment by NiroWolfee** [comment]
[IntegrationEvent(false, false)]
    local procedure OnBeforeCopyBuyFromVendorAddressFieldsFromVendor(var PurchaseHeader: Record "Purchase Header"; Vendor: Record "Vendor"; var IsHandled: Boolean) //CustPub
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
