### ISSUE TITLE
[Event Request] table 38 "Purchase Header" - "Order Address Code" -> OnValidate

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15691]
Hello,

Please add this handled event:

![image](https://user-images.githubusercontent.com/33875371/147749114-ed5f0397-56c8-4e8f-9c54-0591e0e4ce31.png)
![image](https://user-images.githubusercontent.com/33875371/147749134-31314a8d-9ca7-4b59-8aec-038ed9a96534.png)

**Comment by StanPesotskiy** [comment]
@NiroWolfee 
You help us implementing the requests faster when your request contains AL code copied from VSCode as a text instead of screenshots.

**Comment by NiroWolfee** [comment]
field(95; "Order Address Code"; Code[10])
        {
            Caption = 'Order Address Code';
            TableRelation = "Order Address".Code WHERE("Vendor No." = FIELD("Buy-from Vendor No."));

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                if "Order Address Code" <> '' then
                    CopyAddressInfoFromOrderAddress()
                else begin
                    GetVend("Buy-from Vendor No.");
                    //Request
                    IsHandled := false;
                    OnBeforeCopyBuyFromVendorAddressFieldsFromVendor(Rec, Vend, IsHandled); //CustPub
                    if not IsHandled then begin
                        "Buy-from Vendor Name" := Vend.Name;
                        "Buy-from Vendor Name 2" := Vend."Name 2";
                        CopyBuyFromVendorAddressFieldsFromVendor(Vend, true);
                    end;
                    //Request

                    OnValidateOrderAddressCodeOnAfterCopyBuyFromVendorAddressFieldsFromVendor(Rec, Vend);

                    PostCodeCheck.CopyAddressID(
                      DATABASE::Vendor, Vend.GetPosition, 0, DATABASE::"Purchase Header", GetPosition, 5);

                    if IsCreditDocType() then begin
                        "Ship-to Name" := Vend.Name;
                        "Ship-to Name 2" := Vend."Name 2";
                        CopyShipToVendorAddressFieldsFromVendor(Vend, true);
                        "Ship-to Contact" := Vend.Contact;
                        "Shipment Method Code" := Vend."Shipment Method Code";
                        IsHandled := false;
                        OnValidateOrderAddressCodeOnBeforeUpdateLocationCode(Rec, xRec, CurrFieldNo, IsHandled);
                        if not IsHandled then
                            if Vend."Location Code" <> '' then
                                Validate("Location Code", Vend."Location Code");
                    end
                end;
            end;
        }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
