### ISSUE TITLE
Why not set GlobalVarAccess = Yes

### ISSUE THREAD

**Issue by j-wilder** [Microsoft/ALAppExtensions#157]
There are a few places I have come across where I wish GlobalVarAccess was Set to yes.  Is there a reason why Microsoft doesn't default this to Yes for all Publisher Events?  Is there a performance impact?

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!

**Comment by JesperSchulz** [comment]
This discussion came up again, and I'm now ready to close this request with our conclusion. The problem with GlobalVarAccess is that every change to a global variable would become a breaking change going forward, if we would set GlobalVarAccess to yes everywhere. We're hence hesitant to go there, as we are working on reducing the amount breaking changes in the upcoming releases. This would hence be a step in the wrong direction. But please do open issues for the individual cases, where you need access to globals, and we will deal with it one by one. Thanks for your suggestion!
