### ISSUE TITLE
[Extensibility Enhancement] codeunit 90 "Purch.-Post" - GetPrepmtDiffToLineAmount

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15701]
Hello,

Please change the scope of GetPrepmtDiffToLineAmount() to global.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
