### ISSUE TITLE
[Event Request] table 37 "Sales Line" - OnDelete

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15702]
Hello,

Please add the following events:

![image](https://user-images.githubusercontent.com/33875371/147751210-7e39ec83-893d-42fa-a3a9-853c937e8587.png)
![image](https://user-images.githubusercontent.com/33875371/147751227-f323089e-20ab-4ac3-a596-ea7f7dbbe009.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
