### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - PostResourceLine

### ISSUE THREAD

**Issue by NiroWolfee** [microsoft/ALAppExtensions#15700]
Hello,

Please add SrcCode, GenJnlLineExtDocNo, GenJnlLineDocNo, PurchInvHeader, PurchCrMemoHeader, JobPurchLine to arguments of OnBeforePostResourceLine publisher:

![image](https://user-images.githubusercontent.com/33875371/147750688-5c732497-14fa-43fd-8ee3-de190f00a3bd.png)
![image](https://user-images.githubusercontent.com/33875371/147750725-7fc87125-bba1-4c31-b927-271f98a8de39.png)

**Comment by StanPesotskiy** [comment]
@NiroWolfee You help us implementing the requests faster when your request contains AL code copied from VSCode as a text instead of screenshots.
