### ISSUE TITLE
[Event Request] table 273 "Bank Acc. Reconciliation"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#15718]
Please add new event  **OnBeforeMatchSingle** on Table **Bank Acc. Reconciliation** in function **MatchSingle**.

```
procedure MatchSingle(DateRange: Integer)
var
    MatchBankRecLines: Codeunit "Match Bank Rec. Lines";
    IsHandled: Boolean;
begin

    OnBeforeMatchSingle(Rec, DateRange, IsHandled);  
    if not IsHandled then


    MatchBankRecLines.MatchSingle(Rec, DateRange);
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeMatchSingle(var Rec: Record "Bank Acc. Reconciliation"; DateRange: Integer; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
