### ISSUE TITLE
[Event Request] table 179 "Reversal Entry" - events in OnAssignSerialNoBatchOnAfterInsert

### ISSUE THREAD

**Issue by alessandrovecchio** [microsoft/ALAppExtensions#15711]
Hi,
in table  "Reversal Entry" I suggest 2 enhancements:

1. event **OnBeforeReverseEntries**: add HideDialog as param
2. new event **OnAfterReverseEntries** placed at the end of the procedure. Suggested params:

- Number: Integer; 
- RevType: Option Transaction,Register
- HideDialog:m boolean

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
