### ISSUE TITLE
[Event Request] Codeunit 13 - OnAfterProcessLine

### ISSUE THREAD

**Issue by JuditNavarro** [microsoft/ALAppExtensions#1571]
Hello AL-team,

In codeunit 13 ("Gen. Jnl.-Post Batch") , we need to use function ProcessLines, but we need to do some code when it finalizes to use the table 81 ("Gen. Journal Line"), could it be possible to add an "onAfterProcessLine" to make it possible to work with it? 

Thank you!

**Comment by AlexanderYakunin** [comment]
Please provide exact place and definition of event.

**Comment by AlexanderYakunin** [comment]
Last chance to reply. If no reply I will close this request.

**Comment by JuditNavarro** [comment]
Hello, sorry for the late reply, my mistake. 

We need in codeunit 13 ("Gen. Jnl.-Post Batch") an event at the end of the local method called "Process Line". We think that the event could be something like "OnAfterProcessLine(VAR TempGenJnlLine : TEMPORARY Record "Gen. Journal Line")", and it allow us to execute it just when it finishes its internal code.
