### ISSUE TITLE
[Event Request] codeunit 1278 "Exp. User Feedback Gen. Jnl."

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#15726]
Please add new event **OnAfterSetExportFlagOnAppliedCustVendLedgerEntry** in codeunit **"Exp. User Feedback Gen. Jnl."** function
**SetExportFlagOnAppliedCustVendLedgerEntry**

```
procedure SetExportFlagOnAppliedCustVendLedgerEntry(var GenJnlLine: Record "Gen. Journal Line"; Flag: Boolean)
    begin
        case GenJnlLine."Account Type" of
            GenJnlLine."Account Type"::Vendor:
                SetExportFlagOnAppliedVendorLedgerEntry(GenJnlLine, Flag);
            GenJnlLine."Account Type"::Customer:
                SetExportFlagOnAppliedCustLedgerEntry(GenJnlLine, Flag);
        end;

        OnAfterSetExportFlagOnAppliedCustVendLedgerEntry(GenJnlLine, Flag);

    end;
```
```
[IntegrationEvent(false, false)]
    local procedure OnAfterSetExportFlagOnAppliedCustVendLedgerEntry(var GenJnlLine: Record "Gen. Journal Line"; Flag: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
