### ISSUE TITLE
[Enum Request] table 405 "Change Log Entry"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#15722]
Please replace Option with enum in Table **Change Log Entry** field **Type of Change**

```
field(9; "Type of Change"; enum "Type of Change")
        {
            Caption = 'Type of Change';

        }
```

```
enum 1234 "Type of Change"
{
    Extensible = true;
    value(0; Insertion) { Caption = 'Insertion'; }
    value(1; Modification) { Caption = 'Modification'; }
    value(2; Deletion) { Caption = 'Deletion'; }

}
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
