### ISSUE TITLE
[Enum Request] table 86 "Exch. Rate Adjmt. Reg."

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#15725]
Please replace Option with existing enum ("Gen. Journal Account Type") in Table **"Exch. Rate Adjmt. Reg."** field **"Account Type"**

```
field(3; "Account Type"; enum "Gen. Journal Account Type")
        {
            Caption = 'Account Type';
        }
```

**Comment by AlexanderYakunin** [comment]
We already have enum "Exch. Rate Adjmt. Account Type" here.
