### ISSUE TITLE
[Enum Request] table 1206 "Credit Transfer Entry"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#15723]
Please replace Option with enum in Table **Credit Transfer Entry** field **Account Type**

```
 field(3; "Account Type"; Enum "Cr. Transfer Entry Acc. Type")
        {
            Caption = 'Account Type';
        }
```

```

enum 1234 "Cr. Transfer Entry Acc. Type"
{
    Extensible = true;
    value(0; Customer) { Caption = 'Customer'; }
    value(1; Vendor) { Caption = 'Vendor'; }
    value(2; Employee) { Caption = 'Employee'; }

}

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
