### ISSUE TITLE
[Feature request] Allow users to add filter fields on report

### ISSUE THREAD

**Issue by alopezolivia** [Microsoft/ALAppExtensions#1573]
When running a report, the user can choose a filter for the pre-defined fields or replace an existing filter field with a new one, but he can't add additional filter fields to the request page if he requires more fields to filter on.

**Comment by JesperSchulz** [comment]
Thanks for sharing your idea with us. We're always looking for better ways to do things. However, this isn't the right place to share it. You'll have better luck getting it implemented and noticed by other partners if you post it to the following resources:

- For functional improvements, go to [Business Central - Ideas](http://aka.ms/bcideas)
- For feature suggestions for the AL compiler and developer tools, visit [Github.com/Microsoft/AL](https://github.com/Microsoft/AL/issues)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.

**Comment by JesperSchulz** [comment]
This might fall into "feature suggestions for the AL compiler! Maybe try there first.
