### ISSUE TITLE
[Extensibility Enhancement] Table 485 "Business Chart Buffer"

### ISSUE THREAD

**Issue by akontos** [microsoft/ALAppExtensions#15739]
Hello. Please change the scope from local to global for the following functions

AddDataColumn
AddColumnWithCaption

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
