### ISSUE TITLE
[Request-for-external] Report 296 "Batch Post Sales Orders": Make global vars available in report extension

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/ALAppExtensions#15738]
Hi, we would like to use most of the global variables of the "batch post sales orders" report in a report extension to modify and use them.
I think it's a similar request then in #11185 which was closed because it was bc14. But we want to have it for the newest version to use it in report extensions.
So could you please make the following variables protected?
```al
        ShipReq: Boolean;
        InvReq: Boolean;
        PostingDateReq: Date;
        ReplacePostingDate: Boolean;
        ReplaceDocumentDate: Boolean;
        CalcInvDisc: Boolean;
        PrintDoc: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
