### ISSUE TITLE
[Enum Request] table 5065 "Interaction Log Entry"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#15730]
Please replace Option with enum in table 5065 **"Interaction Log Entry"** field **"Delivery Status"**

```
field(25; "Delivery Status"; enum "Delivery Status")
        {
            Caption = 'Delivery Status';

        }
```
```
enum 1234 "Delivery Status"
{
    Extensible = true;
    value(0; " ") { Caption = ' '; }
    value(1; "In Progress") { Caption = 'In Progress'; }
    value(2; Error) { Caption = 'Error'; }

}
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
