### ISSUE TITLE
SuppressCommit in codeunit 227 "VendEntry-Apply Posted Entries"

### ISSUE THREAD

**Issue by tyurm** [microsoft/ALAppExtensions#15737]
Is it possible to add "SuppressCommit" logic to codeunit 227 "VendEntry-Apply Posted Entries", "VendPostApplyVendLedgEntry" procedure (same as in codeunit 226 "CustEntry-Apply Posted Entries"):

add local variable to VendPostApplyVendLedgEntry procedure:
`        SuppressCommit: Boolean;`

add code to VendPostApplyVendLedgEntry procedure:
```
            if PreviewMode then
                GenJnlPostPreview.ThrowError;

            //to add >>
            SuppressCommit := false;
            OnVendPostApplyVendLedgEntryOnBeforeCommit(VendLedgEntry, SuppressCommit);
            if not SuppressCommit then
            //to add <<
                Commit();
            Window.Close;
            RunUpdateAnalysisView();
```

Event Declaration:

```
    [IntegrationEvent(false, false)]
    local procedure OnVendPostApplyVendLedgEntryOnBeforeCommit(var VendLedgerEntry: Record "Vendor Ledger Entry"; var SuppressCommit: Boolean);
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
