### ISSUE TITLE
[ShowAsTree] ShowAsTree property causes error

### ISSUE THREAD

**Issue by petroLubchenko** [microsoft/ALAppExtensions#15748]
Hi,
We faced an issue with the **ShowAsTree** property on the page we created to implement requirements. When the source table of this page contains more than 100000 records, the last record cannot be selected using the FindLast function or using UI. The following error is shown:
![image](https://user-images.githubusercontent.com/22105115/148085669-3a65e8cf-7c43-44e7-bc7b-bc6048a5d50e.png)

This error was reproduced on different web browsers and does not depend on their settings.

We managed to reproduce this error on the demo database (D365BC 18.0 BE and D365BC 19.2 BE) on page 9900 (**Code Coverage**). When several objects are loaded (for instance, by pressing the **Load country objects** action), the same error is displayed when the last record is selected using the **Ctrl+End** shortcut.

Is it possible to fix this issue? Or, probably, there are some ways to overcome this issue?

**Comment by AlexanderYakunin** [comment]
Do you consider to request hotfix via technical support? This is not an extensibility question.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
