### ISSUE TITLE
[Extensibility Enhancement] Table 5093 Opportunity Entry Protected Variables

### ISSUE THREAD

**Issue by akontos** [microsoft/ALAppExtensions#15753]
Hello. Please make the following variables protected:

````
TempSalesCycleStageFirst: Record "Sales Cycle Stage" temporary;
TempSalesCycleStageNext: Record "Sales Cycle Stage" temporary;
TempSalesCycleStagePrevious: Record "Sales Cycle Stage" temporary;
TempSalesCycleStageSkip: Record "Sales Cycle Stage" temporary;
TempSalesCycleStageUpdate: Record "Sales Cycle Stage" temporary;
TempSalesCycleStageJump: Record "Sales Cycle Stage" temporary;

````

Many thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
