### ISSUE TITLE
[Event Request] codeunit 130618 "Library - Graph Mgt"

### ISSUE THREAD

**Issue by Arthurvdv** [microsoft/ALAppExtensions#15756]
When creating Test Automation for API's an BC-environment with Windows authentication is required. The goal here is to use a username and password for running the AL Test Suite using NavUserPassword in stead of Windows.

In the "Http Web Request Mgt." (codeunit 1297) there's a function;

```
procedure AddBasicAuthentication(BasicUserId: Text; BasicUserPassword: Text)
var
    Credential: DotNet NetworkCredential;
begin
    HttpWebRequest.UseDefaultCredentials(false);
    Credential := Credential.NetworkCredential;
    Credential.UserName := BasicUserId;
    Credential.Password := BasicUserPassword;
    HttpWebRequest.Credentials := Credential;
end;
```

So I would like a OnBefore-event on the ExecuteWebRequestAndReadResponse in the "Library - Graph Mgt" (codeunit 130618) I could pass a User and Password to the http-call;

```
local procedure ExecuteWebRequestAndReadResponse(var HttpWebRequestMgt: Codeunit "Http Web Request Mgt."; var TempBlob: Codeunit "Temp Blob"; var ResponseError: Text; var HttpStatusCode: DotNet HttpStatusCode; var ResponseHeaders: DotNet NameValueCollection): Boolean
var
    WebRequestHelper: Codeunit "Web Request Helper";
    WebException: DotNet WebException;
    WebExceptionResponse: DotNet HttpWebResponse;
    ResponseInStream: InStream;
    WebExceptionResponseText: Text;
    TextLine: Text;
    ServiceUrl: Text;
    LastError: Text;
    ErrorCode: Text;
    ErrorMessage: Text;
begin
    Clear(TempBlob);
    TempBlob.CreateInStream(ResponseInStream);

    ClearLastError;
    OnBeforeGetResponse(HttpWebRequestMgt); <<-- NEW EVENT
    if HttpWebRequestMgt.GetResponse(ResponseInStream, HttpStatusCode, ResponseHeaders) then
        exit(true);

    LastError := GetLastErrorText;

    ....
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeGetResponse(var HttpWebRequestMgt: Codeunit "Http Web Request Mgt.")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by lvanvugt** [comment]
Thanx for this. It made testing APIs in pipelines much easier than I had learned from how MS did (and described it in my book). Thanx @Arthurvdv for raising this and sharing your solution here: https://github.com/PacktPublishing/Automated-Testing-in-Microsoft-Dynamics-365-Business-Central-Second-Edition/issues/16

**Comment by rumon10** [comment]
Hello,
@Arthurvdv, If we run the APIs test automation program inside the docker container by following the above strategy (basic authentication use docker user name and password) the test automation program will run or fail?  If failed please let me know how we run test automation inside the docker container.
