### ISSUE TITLE
[Event Request] Table 37 Sales Line OnBeforeSetDefaultQuantity

### ISSUE THREAD

**Issue by pererikandersen** [microsoft/ALAppExtensions#15757]
Please add an Event OnBeforeSetDefaultQuantity to procedure SetDefaultQuantity in table 37 Sales Line.

    procedure SetDefaultQuantity()
    var
        IsHandled: Boolean;
    Begin
        OnBeforeSetDefaultQuantity(Rec, IsHandled);   <--- NEW EVENT
        if IsHandled then
            exit;

        GetSalesSetup();
        if SalesSetup."Default Quantity to Ship" = SalesSetup."Default Quantity to Ship"::Blank then begin
            if ("Document Type" = "Document Type"::Order) or ("Document Type" = "Document Type"::Quote) then begin
                "Qty. to Ship" := 0;
                "Qty. to Ship (Base)" := 0;
                "Qty. to Invoice" := 0;
                "Qty. to Invoice (Base)" := 0;
            end;
            if "Document Type" = "Document Type"::"Return Order" then begin
                "Return Qty. to Receive" := 0;
                "Return Qty. to Receive (Base)" := 0;
                "Qty. to Invoice" := 0;
                "Qty. to Invoice (Base)" := 0;
            end;
        end;

        OnAfterSetDefaultQuantity(Rec, xRec);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetDefaultQuantity(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
