### ISSUE TITLE
Procedure PurchseReferenceNoLookup() in Codeunit 5720 "Item Reference Management" overrides selected Item Reference

### ISSUE THREAD

**Issue by VMasalkov** [microsoft/ALAppExtensions#15754]
Here is a given scenario, which is allowed per std. Business Central rules:
 - there are several identical generic Reference No. set for the same Item No. but Variant Code
![image](https://user-images.githubusercontent.com/95699224/148131960-fcde6a7e-02ae-4e33-aa6b-0722e12acec7.png)
 - the item reference lookup capability on the purchase documents always results in selection of first item reference from the list
![image](https://user-images.githubusercontent.com/95699224/148132650-13fe8ab2-5198-4a38-9afb-4d8bdf4a4ea7.png)
 - same lookup functionality correctly applies selected reference back to sales line
![image](https://user-images.githubusercontent.com/95699224/148132675-9a9a8b0b-8c53-455f-aade-0b0d4d346839.png)

The core issue is within PurchseReferenceNoLookup() procedure where extra call to PurchaseLine.Validate("Item Reference No.", XYZ) resets all the previously values set per selection and that results in selection of 1st reference from the list. Please follow the same design logic as per sales line and related SalesReferenceNoLookup() procedure.

Software should behave identically on both, sales and purchase, sides with the same dataset.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
