### ISSUE TITLE
[Event Request] codeunit 80 "Sales-Post"

### ISSUE THREAD

**Issue by tendreffy** [microsoft/ALAppExtensions#15758]
Please add an event OnBeforeTestUpdatedSalesLine to procedure TestUpdatedSalesLine

    local procedure TestUpdatedSalesLine(SalesLine: Record "Sales Line")
    var
        ForwardLinkMgt: Codeunit "Forward Link Mgt.";
    begin
        OnBeforeTestUpdatedSalesLine(SalesLine, IsHandled);// <-- NEW EVENT
        if IsHandled then
            exit();

        with SalesLine do begin
            if "Drop Shipment" then begin
                if Type <> Type::Item then
                    TestField("Drop Shipment", false);
                if ("Qty. to Ship" <> 0) and ("Purch. Order Line No." = 0) then
                    ErrorMessageMgt.LogErrorMessage(FieldNo("Purchasing Code"), StrSubstNo(DropShipmentErr, "Line No."),
                        0, 0, ForwardLinkMgt.GetHelpCodeForSalesLineDropShipmentErr());
            end;

            if Quantity = 0 then
                TestField(Amount, 0)
            else begin
                TestField("No.");
                TestField(Type);
                if not ApplicationAreaMgmt.IsSalesTaxEnabled then begin
                    TestField("Gen. Bus. Posting Group");
                    TestField("Gen. Prod. Posting Group");
                end;
            end;
        end;
    end;

new event:      

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTestUpdatedSalesLine(SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
