### ISSUE TITLE
[Extensibility Enhancement] Table 5080 To-Do Change Event OnBeforeRunCreateTaskPage

### ISSUE THREAD

**Issue by akontos** [microsoft/ALAppExtensions#15761]
Hello. It would be great if you could consider changing the existing event to include an IsHandled Variable, since the existing implementation does not provide this option.

````
local procedure RunCreateTaskPage()
#if EXT
    var
        IsHandled: Boolean;
#endif
    begin
#if EXT
        OnBeforeRunCreateTaskPage(Rec, IsHandled);
        if IsHandled then
            exit;
#else
        OnBeforeRunCreateTaskPage(Rec);
#endif

        if PAGE.RunModal(PAGE::"Create Task", Rec) = ACTION::OK then;
    end;
````
````
#if EXT 
    [IntegrationEvent(false, false)]
    local procedure OnBeforeRunCreateTaskPage(var Task: Record "To-do"; var IsHandled: Boolean)
    begin
    end;
#else
    [IntegrationEvent(false, false)]
    local procedure OnBeforeRunCreateTaskPage(var Task: Record "To-do")
    begin
    end;
#endif
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
