### ISSUE TITLE
[Event Change] PriceListHeader parameter for OnBeforeHasDraftLines event

### ISSUE THREAD

**Issue by shuyusheng** [microsoft/ALAppExtensions#15765]
Hi, we'd like the PriceListHeader record available as a parameter for the event requested in #13183
This allows us to conditionally alter the behavior based on the header record calling the event, thanks.

```
[IntegrationEvent(false, false)]
local procedure OnBeforeHasDraftLines(PriceListHeader: Record "Price List Header"; var PriceListLine: Record "Price List Line"; var Result: Boolean; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
