### ISSUE TITLE
[Event Parameter Enhancement] - (ObjectType::Table, Database::Customer, 'OnBeforeGetCustNoOpenCard')

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#15763]
Could you make ShowCreateCustomerOption var?

local procedure OnBeforeGetCustNoOpenCard(CustomerText: Text; ShowCustomerCard: Boolean; ShowCreateCustomerOption: Boolean; var CustomerNo: Code[20]; var IsHandled: Boolean);

thx.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by grantbrimhall** [comment]
Hi @JesperSchulz, would it be helpful to include a pull request along with these issues? I find one every other month or so that would be helpful for what I'm doing for a client. Thanks.

**Comment by JesperSchulz** [comment]
I am not 100% I understand your last comment. Unfortunately, the Base Application is not open sourced (yet), and you hence won't be able to submit a PR for the requested changes - else a great suggestion! What are you suggesting us to do?
