### ISSUE TITLE
[Event Change][Bug?] Overriding Sales-Post.PostItemJnlLine with OnBeforePostItemJnlLine will always return a blank value

### ISSUE THREAD

**Issue by shuyusheng** [microsoft/ALAppExtensions#15774]
The event `OnBeforePostItemJnlLine` allows us to completely override the function `PostItemJnlLine` by setting the parameter IsHandled to true. However, `PostItemJnlLine` is expected to return an integer value, namely `ItemJnlLine."Item Shpt. Entry No."`, but there isn't a parameter in `OnBeforePostItemJnlLine` that allows us to provide this value, nor does the code to skip the standard behavior return any value. Below is a snippet of the existing code, as well as the request change, it also seems there is a similar issue with the same function in `Purch-Post`.

Thanks

### Existing
```
procedure PostItemJnlLine(...): Integer // <-- Return value
var
    ...
begin
    IsHandled := false;
    OnBeforePostItemJnlLine(
      SalesHeader, SalesLine, QtyToBeShipped, QtyToBeShippedBase, QtyToBeInvoiced, QtyToBeInvoicedBase,
      ItemLedgShptEntryNo, ItemChargeNo, TrackingSpecification, IsATO, SuppressCommit, IsHandled); // <-- No option to provide a return value
    if IsHandled then
        exit; // <-- No return value

    with ItemJnlLine do begin
        ...

        exit("Item Shpt. Entry No."); // <-- Standard code returns a value
    end;
```

### Requested
```
procedure PostItemJnlLine(...): Integer
var
    ...
   ItemShptEntryNo: Decimal;
begin
    IsHandled := false;
    OnBeforePostItemJnlLine(
      SalesHeader, SalesLine, QtyToBeShipped, QtyToBeShippedBase, QtyToBeInvoiced, QtyToBeInvoicedBase,
      ItemLedgShptEntryNo, ItemChargeNo, TrackingSpecification, IsATO, SuppressCommit, ItemShptEntryNo; IsHandled); // <-- New parameter
    if IsHandled then
        exit(ItemShptEntryNo); // <-- Returns the value

    with ItemJnlLine do begin
        ...

        exit("Item Shpt. Entry No.");
    end;

    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforePostItemJnlLine(... var ItemShptEntryNo: Decimal; ...) // <-- New parameter
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
