### ISSUE TITLE
[Request for external] report 304 "Vendor - Detail Trial Balance"

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#15779]
Can you change the following globale variables to protected var?

VendCurrencyCode: Code[10];
PrintAmountsInLCY: Boolean;
Correction: Decimal;
VendBalanceLCY: Decimal;
BalanceLCYCaptionLbl: Label 'Balance (LCY)';
AmountCaption: Text[30];
StartBalAdjLCY: Decimal;
VendDateFilter: Text;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
