### ISSUE TITLE
[Event Request] Add Event OnAfterSetItemData Table 7317 Warehouse Receipt Line

### ISSUE THREAD

**Issue by anbi-pri** [microsoft/ALAppExtensions#15777]
Could you please add a new Event OnAfterSetItemData in Table 7317?

    procedure SetItemData(ItemNo: Code[20]; ItemDescription: Text[100]; ItemDescription2: Text[50]; LocationCode: Code[10]; VariantCode: Code[10]; UoMCode: Code[10]; QtyPerUoM: Decimal)
    begin
        "Item No." := ItemNo;
        Description := ItemDescription;
        "Description 2" := ItemDescription2;
        "Location Code" := LocationCode;
        "Variant Code" := VariantCode;
        "Unit of Measure Code" := UoMCode;
        "Qty. per Unit of Measure" := QtyPerUoM;
        OnAfterSetItemData(Rec);   <-- NEW EVENT
    end;

```al

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetItemData(var WarehouseReceiptLine: Record "Warehouse Receipt Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
