### ISSUE TITLE
[Event Request] Report 950 "Create Time Sheets" - Add StartingDate and EndingDate to existing event OnBeforeResourceOnAfterGerRecord

### ISSUE THREAD

**Issue by rwe12345** [microsoft/ALAppExtensions#15783]
Please add the parameters StartingDate and EndingDate to the eventOnBeforeResourceOnAfterGerRecord so we can check on these dates.

![image](https://user-images.githubusercontent.com/44321194/148794688-7a9d17ce-91b3-45c3-8d8f-933e3dc5e813.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
