### ISSUE TITLE
event request - report 1306 "Standard Sales - Invoice" - FillRightHeader() - OnAfterFillRightHeader() - as in FillLeftHeader()

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15782]
`FillLeftHeader()` has an `OnAfter` event that we could use to add/change the contents of the `LeftHeader` `Name/Value Buffer`. But there is no corresponding event in `FillRightHeader()`!

![image](https://user-images.githubusercontent.com/63455896/148793724-bfe8d301-483c-449c-92be-7a573c9b428b.png)

Please add one, just the same but with `Left` substituted by `Right`, so:

```al
        OnAfterFillRightHeader(RightHeader, Header);
```

published as:

```al
    [IntegrationEvent(false, false)]
    local procedure OnAfterFillRightHeader(var RightHeader: Record "Name/Value Buffer"; SalesInvoiceHeader: Record "Sales Invoice Header")
    begin
    end;
```

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
