### ISSUE TITLE
[Extensibility Request] table 86 "Exch. Rate Adjmt. Reg."

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#15788]
Please replace Option with existing enum ("Gen. Journal Account Type") in Table "Exch. Rate Adjmt. Reg." field "Account Type"

Old Code
```
field(3; "Account Type"; Option)
        {
            Caption = 'Account Type';
            OptionCaption = 'G/L Account,Customer,Vendor,Bank Account';
            OptionMembers = "G/L Account",Customer,Vendor,"Bank Account";
        }
```

New Code
```
field(3; "Account Type"; enum "Gen. Journal Account Type")
        {
            Caption = 'Account Type';
        }
```

I ve already opened issue
[https://github.com/microsoft/ALAppExtensions/issues/15725](url)
just checked latest version and in Account Type the field type is option

**Comment by panas78** [comment]
i also checked for enum "Exch. Rate Adjmt. Account Type" mentioned on issue 15725 but did not find it

**Comment by AlexanderYakunin** [comment]
You should not expect new enums in PROD versions, we only implement it in next major, currently 20.0. And you suggestion is breaking change, we cannot alter order of options this way.

**Comment by panas78** [comment]
I am not asking for a new enum but rather use an existing one (enum "Gen. Journal Account Type").
You have the same approach in G/L entry also.

**Comment by panas78** [comment]
Fair enough, but using the enum "Gen. Journal Account Type" is not a breaking change since the order of options is not altered.
Its all the same minus the : Fixed Asset,IC Partner,Employee
