### ISSUE TITLE
[Event Request] Report 297 "Batch Post Sales Invoices" - OnBeforeSalesBatchPostMgt

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#15786]
Hi Microsoft AL Development Team,

Could you please add an integration event for **OnBeforeSalesBatchPostMgt** to the OnPreDataItem trigger of report 297 "Batch Post Sales Invoices"?

![image](https://user-images.githubusercontent.com/69611495/148851023-31bbe5aa-9423-4fd5-8227-14504b2367cf.png)

![image](https://user-images.githubusercontent.com/69611495/148851036-dfef637e-f549-4508-abbd-c4b0c75c253d.png)

Thank you!

Kind regards,
Tuan Nguyen

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
