### ISSUE TITLE
Codeunit 730 "Copy Item" - Cannot access parameters

### ISSUE THREAD

**Issue by DennyHW** [microsoft/ALAppExtensions#15789]
I've extended the table "Copy Item Buffer" adding additional item copy options.

The only place where I' can read the CopyItemBuffer record is on event OnRunOnAfterItemCopied(...), but it's too late.

I need to process some options inside the copy loop, for each item copy.
The copy process can create more than an item.
I need to acces that variable in events like OnBeforeCopyItem() , OnCopyItemOnBeforeTargetItemInsert() and OnAfterCopyItem().

Thanks.

![immagine](https://user-images.githubusercontent.com/53569676/148929563-eca11d4c-508d-4243-ac7a-10dc4e08fc85.png)
![immagine](https://user-images.githubusercontent.com/53569676/148930145-071f3884-4111-4594-8a6f-34edf15b14d7.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
