### ISSUE TITLE
Table 1003 "Job Planning Line" - "Directed Put-away and Pick" Testfield

### ISSUE THREAD

**Issue by gpintaudi** [microsoft/ALAppExtensions#15785]
Is there a reason why field "Directed Put-away and Pick" is tested false on validate of  Location Code field in table Job Planning Line?

```
        field(20; "Location Code"; Code[10])
        {
            Caption = 'Location Code';
            TableRelation = Location WHERE("Use As In-Transit" = CONST(false));

            trigger OnValidate()
            begin
                ValidateModification(xRec."Location Code" <> "Location Code");

                "Bin Code" := '';
                if Type = Type::Item then begin
                    GetLocation("Location Code");
                    **Location.TestField("Directed Put-away and Pick", false);**
                    CheckItemAvailable(FieldNo("Location Code"));
                    UpdateReservation(FieldNo("Location Code"));
                    Validate(Quantity);
                    if ("Location Code" <> '') and ("No." <> '') then begin
                        GetItem();
                        if IsDefaultBin() and Item.IsInventoriableType() then
                            WMSManagement.GetDefaultBin("No.", "Variant Code", "Location Code", "Bin Code");
                    end;
                end;
            end;
        }
```

It seems that without this check Directed Put-aways and Picks work fine anyway.
Could it be removed? or if removing this is not an option, at least give us a way to handle it via events or similar.

Thanks

**Comment by SKnoppers** [comment]
Hi, 
I'm not sure if i should add it to this issue or open a new issue but it is related to the same field Directed Put-away and Pick.

This is also a problem on the Purchase line (table 39) in the function CheckWMS. but here it does not even check if it is line of type Item. Could this be changed so a check for Type::Item is included or else an event with IsHandeld, so we can skip this check. 

![image](https://user-images.githubusercontent.com/97528114/148950584-90b4d49c-0ef0-42fc-834a-5658797f3b88.png)

**Comment by Stepanenko-Vadim** [comment]
I have processed both of the requests but in the future it is preferable that you open a new issue for a separate (even if similar request).

**Comment by SKnoppers** [comment]
Thank you!
In the future I will make a new issues!
