### ISSUE TITLE
[Event Request] Codeunit 7000 Sales Price Calc. Mgt. – FindJobJnlLinePrice

### ISSUE THREAD

**Issue by ttaeufer** [Microsoft/ALAppExtensions#1579]
Could we please have a Supplement in publisher OnBeforeFindJobJnlLinePrice in function FindJobJnlLinePrice Codeunit 7000 Sales Price Calc. Mgt.?

```
[External] FindJobJnlLinePrice(VAR JobJnlLine : Record "Job Journal Line";CalledByFieldNo : Integer)

// >>>>>>>>
OnBeforeFindJobJnlLinePrice( Var JobJnlLine, CalledByFieldNo, Var Handled);
IF Handled THEN
  EXIT;
// <<<<<<<<  

WITH JobJnlLine DO BEGIN

```

**Comment by JesperSchulz** [comment]
We are currently looking into a larger refactoring effort of the Sales Price module and hence cannot accept event requests for this module right now. We will keep you posted.

**Comment by cosmo-skol** [comment]
> We are currently looking into a larger refactoring effort of the Sales Price module and hence cannot accept event requests for this module right now. We will keep you posted.

Hello Mr. Schulz,
is your team also planning on refactoring the codeunit 7010 for the purchase price calculation?

Best regards

**Comment by cosmo-skol** [comment]
Hello @JesperSchulz,

any new information to this issue?

Best regards

**Comment by JesperSchulz** [comment]
I wonder why I wasn't informed about your comments through the notification system! That's strange. Anyway, sorry for the late reply!
Actually, it is a little uncertain when we get to do what. I will hence move forward with your requests. Then you can always decide to pick up the refactored version, when that will be made available.
