### ISSUE TITLE
Table 172 - Standard Customer Sales Code - CreateSalesInvoice

### ISSUE THREAD

**Issue by superjma** [microsoft/ALAppExtensions#15797]
I would like to request a new puiblisher in function CreateSalesInvoice of table 172 standard customer sales code:

procedure CreateSalesInvoice(OrderDate: Date; PostingDate: Date)
    var
        SalesHeader: Record "Sales Header";
        Handled : Boolean; //Also new
    begin
        //>> START
        OnBeforeCreateSalesInvoice(Rec, OrderDate, PostingDate, Handled)
        if Handled then exit;
        //<< END
        TestField(Blocked, false);
        SalesHeader.Init();
        SalesHeader."No." := '';
        SalesHeader."Document Type" := SalesHeader."Document Type"::Invoice;
        OnCreateSalesInvoiceOnBeforeSalesHeaderInsert(SalesHeader, Rec);
        ....

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
