### ISSUE TITLE
[Extensibility Request] codeunit 1252 "Match Bank Rec. Lines"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#15790]
In codeunit 1252 "Match Bank Rec. Lines" please make the following functions global 

**RemoveMatchesFromRecLines**
```
local procedure RemoveMatchesFromRecLines(var SelectedBankAccReconciliationLine: Record "Bank Acc. Reconciliation Line")
```

**ListOfMatchedFields**
```
local procedure ListOfMatchedFields(AmountMatched: Boolean; DocumentNoMatched: Boolean; ExternalDocumentNoMatched: Boolean; TransactionDateMatched: Boolean; RelatedPartyMatched: Boolean; DescriptionMatched: Boolean): Text
```

**SaveOneToOneMatching**
```
local procedure SaveOneToOneMatching(var TempBankStatementMatchingBuffer: Record "Bank Statement Matching Buffer" temporary; BankAccountNo: Code[20]; StatementNo: Code[20])
```

**ShowMatchSummary**
```
local procedure ShowMatchSummary(BankAccReconciliation: Record "Bank Acc. Reconciliation")
```

**GetDescriptionMatchScore**
```
local procedure GetDescriptionMatchScore(BankRecDescription: Text; BankEntryDescription: Text; DocumentNo: Code[20]; ExternalDocumentNo: Code[35]): Integer
```

**GetMatchLengthTreshold**
```
local procedure GetMatchLengthTreshold(): Integer
```

**GetNormalizingFactor**
```
local procedure GetNormalizingFactor(): Integer
```

,that way one can implement his own MatchSingle logic using the above functions

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
