### ISSUE TITLE
[Application Bug] ConvertAndAddPrinterPaperDimensions

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#15804]
Haven't tested in detail, but both the Email Printer / Universal Printer extension have a function ConvertAndAddPrinterPaperDimensions that might have possible switched **width** and **height** parameters?

![image](https://user-images.githubusercontent.com/25268332/149133861-56c42196-d135-4497-869d-e042dad82ad8.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
