### ISSUE TITLE
BC19.2 - County field caption displayed as '5,1,' on all pages if Country/Region Code is not assigned

### ISSUE THREAD

**Issue by VMasalkov** [microsoft/ALAppExtensions#15802]
On all pages County field caption is not properly displayed properly if Country/Region Code is left blank. While it seems to be minor, it's very critical for reporting which may no longer function. For ex. JetReports are based on fields caption, not names, and with BC19.2 upgrade all of the JetReports are no longer working.

![image](https://user-images.githubusercontent.com/95699224/149020606-562a9aac-144b-4bcb-9c65-adb3d240a504.png)
![image](https://user-images.githubusercontent.com/95699224/149020644-8bf403e7-b24a-44f4-99a4-2dd1e9972285.png)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
