### ISSUE TITLE
OnMapTableUsageValueToPageValueOnCaseElse in Page Customer Report Selections

### ISSUE THREAD

**Issue by marpacca** [microsoft/ALAppExtensions#15803]
In the page "Customer Report Selections", the event "OnMapTableUsageValueToPageValueOnCaseElse" has as first parameter "CustomReportSelection" and it should be "rec", because "CustomReportSelection" is a local variable that is not initialised.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
