### ISSUE TITLE
[Event Request] Codeunit 7000 Sales Price Calc. Mgt. – JobPlanningLineFindJTPrice

### ISSUE THREAD

**Issue by ttaeufer** [Microsoft/ALAppExtensions#1580]
Could we please have a publisher OnBeforeFindJobPlanningLinePrice in function JobPlanningLineFindJTPrice Codeunit 7000 Sales Price Calc. Mgt.?

```
[External] JobPlanningLineFindJTPrice(VAR JobPlanningLine : Record "Job Planning Line") 

// >>>>>>>>
OnBeforeJobPlanningLineFindJTPrice (Var JobPlanningLine, Var Handled);
IF Handled THEN
  EXIT;
// <<<<<<<<  

WITH JobPlanningLine DO
  CASE Type OF
    Type::Item:

```

**Comment by JesperSchulz** [comment]
We are currently looking into a larger refactoring effort of the Sales Price module and hence cannot accept event requests for this module right now. We will keep you posted.
