### ISSUE TITLE
[Request For External] page 1340 Config Templates

### ISSUE THREAD

**Issue by akontos** [microsoft/ALAppExtensions#15819]
Hello. Please make the following variable protected

NewMode: Boolean;

Thank You

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
