### ISSUE TITLE
[Extensibility Request] Page 504 "Available - Item Ledg. Entries" - Protected variables

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#15810]
For our page extension, we need the following global variables defined as protected. Thank you!
```
protected var
    ReservEntry: Record "Reservation Entry";
    SourceRecRef: RecordRef;
    QtyToReserve: Decimal;
    QtyReserved: Decimal;
    TotalAvailQty: Decimal;
    MaxQtyToReserve: Decimal;
    MaxQtyDefined: Boolean;

var
    ReservEntry2: Record "Reservation Entry";
    [...]
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
