### ISSUE TITLE
[Event Request] Codeunit 7000 Sales Price Calc. Mgt. – FindJobPlanningLinePrice

### ISSUE THREAD

**Issue by ttaeufer** [Microsoft/ALAppExtensions#1581]
Could we please have a Supplement in publisher OnBeforeFindJobPlanningLinePrice in function FindJobPlanningLinePrice Codeunit 7000 Sales Price Calc. Mgt.?

```
[External] FindJobPlanningLinePrice(VAR JobPlanningLine : Record "Job Planning Line";CalledByFieldNo : Integer)

// >>>>>>>>
OnBeforeFindJobPlanningLinePrice(Var JobPlanningLine, CalledByFieldNo, Var Handled);
IF Handled THEN
  EXIT;
// <<<<<<<<  

WITH JobPlanningLine DO BEGIN

```

**Comment by JesperSchulz** [comment]
We are currently looking into a larger refactoring effort of the Sales Price module and hence cannot accept event requests for this module right now. We will keep you posted.
