### ISSUE TITLE
[Request For External] codeunit 1402 Cancel Posted Purch. Cr. Memo

### ISSUE THREAD

**Issue by akontos** [microsoft/ALAppExtensions#15816]
Hello. Please make the following function protected:

````
procedure TestGLAccount(AccountNo: Code[20]; PurchCrMemoLine: Record "Purch. Cr. Memo Line")
begin
...
end
````

Thank You!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
