### ISSUE TITLE
[Request For External] codeunit 1313 Correct Posted Purch. Invoice 

### ISSUE THREAD

**Issue by akontos** [microsoft/ALAppExtensions#15813]
Hello. Please make the following function protected:

procedure ErrorHelperHeader(ErrorOption: Option; PurchInvHeader: Record "Purch. Inv. Header")
begin
...
end

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
