### ISSUE TITLE
[Event Request] Codeunit 11000010 "Check SEPA ISO20022" - OnAfterCheckSWIFTCodeOnVendCustBankAccount

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#15823]
Hello,

We would like an event publisher in codeunit 11000010 "Check SEPA ISO20022" - OnBeforeCheckSWIFTCode in trigger OnRun:        

        if StrLen("SWIFT Code") > 11 then begin
            "Error Message" := StrSubstNo(Text002, FieldCaption("SWIFT Code"), TableCaption);
            exit;
        end;

        IsHandled := false;
        OnAfterCheckSWIFTCodeOnVendCustBankAccount(Rec, IsHandled);
        if IsHandled then
            exit;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckSWIFTCodeOnVendCustBankAccount(var ProposalLine: Record "Proposal Line"; var IsHandled: Boolean)
    begin
    end;

After checking if the "SWIFT Code" exceeds 11 characters, there are additional checks that we need to perform.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
