### ISSUE TITLE
[Request For External] Report 5084 Email Merge

### ISSUE THREAD

**Issue by akontos** [microsoft/ALAppExtensions#15827]
Please make the following variables protected in Report 5084 Email Merge

 ```
SegmentLine: Record "Segment Line";
      CompanyInformation: Record "Company Information";
        Contact: Record Contact;
        SalespersonPurchaser: Record "Salesperson/Purchaser";
        Content: Text;
        Contact_Mail_Address: Text;
        Formal_Salutation: Text;
        Informal_Salutation: Text;
        Document_Date: Text;
```

Thank  You

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
