### ISSUE TITLE
[Event Request] Codeunit 7000 Sales Price Calc. Mgt. – FindAnalysisReportPrice

### ISSUE THREAD

**Issue by ttaeufer** [Microsoft/ALAppExtensions#1582]
Could we please have a Supplement in publisher OnBeforeFindAnalysisReportPrice in function FindAnalysisReportPrice Codeunit 7000 Sales Price Calc. Mgt.?

```
[External] FindAnalysisReportPrice(ItemNo : Code[20];Date : Date) : Decimal

// >>>>>>>>
OnBeforeFindAnalysisReportPrice(ItemNo,Date,Var ReturnValue, Var Handled);
IF Handled THEN
  EXIT(ReturnValue);
// <<<<<<<<  

WITH ItemJnlLine DO BEGIN
  SetCurrency('',0,0D);
  SetVAT(FALSE,0,0,'');
  SetUoM(ABS(Quantity),"Qty. per Unit of Measure");

```

**Comment by JesperSchulz** [comment]
We are currently looking into a larger refactoring effort of the Sales Price module and hence cannot accept event requests for this module right now. We will keep you posted.
