### ISSUE TITLE
[Event Request] Codeunit 7000 Sales Price Calc. Mgt. – FindItemJnlLinePrice

### ISSUE THREAD

**Issue by ttaeufer** [Microsoft/ALAppExtensions#1583]
Could we please have a Supplement in publisher OnBeforeFindItemJnlLinePrice in function FindItemJnlLinePrice  Codeunit 7000 Sales Price Calc. Mgt.?

```
[External] FindItemJnlLinePrice(VAR ItemJnlLine : Record "Item Journal Line";CalledByFieldNo : Integer)

// >>>>>>>>
OnBeforeFindItemJnlLinePrice(ItemJnlLine, CalledByFieldNo,Var Handled);
IF Handled THEN
  EXIT;
// <<<<<<<<  

WITH ItemJnlLine DO BEGIN
  SetCurrency('',0,0D);
  SetVAT(FALSE,0,0,'');
  SetUoM(ABS(Quantity),"Qty. per Unit of Measure");

```

**Comment by JesperSchulz** [comment]
We are currently looking into a larger refactoring effort of the Sales Price module and hence cannot accept event requests for this module right now. We will keep you posted.
