### ISSUE TITLE
[Extensibility Request] table 81 "Gen. Journal Line"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#15831]
In table 81 "Gen. Journal Line" please make the following functions **Protected**

SetCurrencyCode

CheckICPartner

UpdateCurrencyCode

CheckPaymentTolerance

UpdateDescription

ClearPostingGroups

ClearBalancePostingGroups

SetAmountWithRemaining

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
