### ISSUE TITLE
[Extensibility Request] Table 5901 "Service Item Line" Validation of field "Contract No." 

### ISSUE THREAD

**Issue by MilosPetrovic1** [microsoft/ALAppExtensions#15848]
Hello guys!

Can you please add this check here:
![image](https://user-images.githubusercontent.com/64962632/149527978-ef5aebdb-e0b5-4e0d-aba1-c41782fc6677.png)

```
if xRec."Contract No." <> '' then
```

Best regards!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
