### ISSUE TITLE
[Event Request] CodeUnit 10821 - "Export DEB DTI" - OnRepeatOnBeforeInsertInsertTempJnlLines

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#15846]
Hi, would it be possible do get an event OnRepeatOnBeforeInsertInsertTempJnlLines in the procedure InsertTempJnlLines, codeunit 10821, like this : 

`    local procedure InsertTempJnlLines(var IntrastatJnlLine: Record "Intrastat Jnl. Line")
    var
        Type: Integer;
        FlowCode: Text[1];
        IsHandled : Boolean;
    begin
        Type := -1;
        IntrastatJnlLine.SetCurrentKey(Type);
        if IntrastatJnlLine.FindSet then
            repeat
                OnRepeatOnBeforeInsertInsertTempJnlLines(IntrastatJnlLine,IsHandled);
                if not ishandled then begin
                    if Type <> IntrastatJnlLine.Type then begin
                        FlowCode := GetFlowCode(IntrastatJnlLine.Type);
                        InsertTempJnlBatch(IntrastatJnlLine, FlowCode);
                        Type := IntrastatJnlLine.Type;
                    end;
                    InsertTempJnlLine(IntrastatJnlLine, FlowCode);
                end;
            until IntrastatJnlLine.Next() = 0;
    end;  `

`    [IntegrationEvent(false, false)]
    local procedure OnRepeatOnBeforeInsertInsertTempJnlLines(IntrastatJnlLine: Record "Intrastat Jnl. Line"; var IsHandled: Boolean)
    begin
    end;`

thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
