### ISSUE TITLE
[Event Request] Codeunit 7000 Sales Price Calc. Mgt. – FindStdItemJnlLinePrice

### ISSUE THREAD

**Issue by ttaeufer** [Microsoft/ALAppExtensions#1584]
Could we please have a Supplement in publisher OnBeforeFindStdItemJnlLinePrice in function FindStdItemJnlLinePrice  Codeunit 7000 Sales Price Calc. Mgt.?

```
[External] FindStdItemJnlLinePrice(VAR StdItemJnlLine : Record "Standard Item Journal Line";CalledByFieldNo : Integer)

// >>>>>>>>
OnBeforeFindStdItemJnlLinePrice(var StdItemJnlLine, CalledByFieldNo , Var Handled);
IF Handled THEN
  EXIT;
// <<<<<<<<  

WITH StdItemJnlLine DO BEGIN
  SetCurrency('',0,0D);
  

```

**Comment by JesperSchulz** [comment]
We are currently looking into a larger refactoring effort of the Sales Price module and hence cannot accept event requests for this module right now. We will keep you posted.
