### ISSUE TITLE
[Event Request] Codeunit 7000 Sales Price Calc. Mgt. – FindServLineDisc

### ISSUE THREAD

**Issue by ttaeufer** [Microsoft/ALAppExtensions#1585]
Could we please have a Supplement in publisher OnBeforeFindServLineDisc in function FindServLineDisc Codeunit 7000 Sales Price Calc. Mgt.?

```
[External] FindServLineDisc(var ServHeader : Record "Service Header";VAR ServLine : Record "Service Line")

// >>>>>>>>
OnBeforeFindServLineDisc(var ServHeader,var ServLine,var Handled);
IF Handled THEN 
    EXIT;
// <<<<<<<<  

WITH ServLine DO BEGIN


```

**Comment by JesperSchulz** [comment]
We are currently looking into a larger refactoring effort of the Sales Price module and hence cannot accept event requests for this module right now. We will keep you posted.
