### ISSUE TITLE
[Scope Change Request] - "Local Functionality Mgt." - CheckBankAccNo

### ISSUE THREAD

**Issue by rwe12345** [microsoft/ALAppExtensions#15869]
Please delete the scope 'OnPrem' on procedure CheckBankAccNo so we can use this function in our cloud solution.

codeunit 11400 "Local Functionality Mgt."

    [Scope('OnPrem')]
    procedure CheckBankAccNo(Acc: Text[30]; CountryCode: Code[10]; var AccountNo: Text[30]) Result: Boolean
    var
        Len: Integer;
        BaseLen: Integer;
        FirstCharacter: Char;
        IsHandled: Boolean;
    begin

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
