### ISSUE TITLE
[Event request]Codeunit 8510 "Over-Receipt Mgt." - VerifyOverReceiptQuantity --> OnBeforeVerifyOverReceiptQuantity

### ISSUE THREAD

**Issue by Mfelice1975** [microsoft/ALAppExtensions#15866]
Please, could we have a publisher event "OnBeforeVerifyOverReceiptQuantity" in "VerifyOverReceiptQuantity" - 8510 "Over-Receipt Mgt."?
Thanks

` procedure VerifyOverReceiptQuantity(PurchaseLine: Record "Purchase Line"; xPurchaseLine: Record "Purchase Line")
    var
        OverReceiptCode: Record "Over-Receipt Code";
        UoMMgt: Codeunit "Unit of Measure Management";
        OverReceiptQtyBase: Decimal;
        LineBaseQty: Decimal;
        MaxOverReceiptQtyAllowed: Decimal;
        // >> NEW VAR
        IsHandled: Boolean;
       // <<  NEW VAR
    begin
        if not IsOverReceiptAllowed() then
            exit;

        // >> NEW EVENT
        OnBeforeVerifyOverReceiptQuantity(PurchaseLine, xPurchaseLine, IsHandled);
        if IsHandled then
             Exit;
        // <<  NEW EVENT

        OverReceiptCode.Get(PurchaseLine."Over-Receipt Code");
        OverReceiptQtyBase := UOMMgt.CalcBaseQty(PurchaseLine."Over-Receipt Quantity", PurchaseLine."Qty. per Unit of Measure");
        LineBaseQty := UoMMgt.CalcBaseQty(xPurchaseLine.Quantity - xPurchaseLine."Over-Receipt Quantity", xPurchaseLine."Qty. per Unit of Measure");
        MaxOverReceiptQtyAllowed := UOMMgt.RoundQty(LineBaseQty / 100 * OverReceiptCode."Over-Receipt Tolerance %");
        if OverReceiptQtyBase > MaxOverReceiptQtyAllowed then
            Error(StrSubstNo(OverReceiptQuantityErr, MaxOverReceiptQtyAllowed));
    end;
`

EVENT PUBLISHER
`[IntegrationEvent(false, false)]
local procedure OnBeforeVerifyOverReceiptQuantity(PurchaseLine: Record "Purchase Line"; xPurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
begin
end;`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
