### ISSUE TITLE
Increase the length of field 5062 Job Title from table 13 Salesperson/Purchaser

### ISSUE THREAD

**Issue by MirabelaRobu** [microsoft/ALAppExtensions#15865]
We would like to request to increase the length of field 5062 "Job Title", table 13 Salesperson/Purchaser from Text[30] to Text[100].

![image](https://user-images.githubusercontent.com/97884885/149758470-3f5e0b5d-3295-4bc4-b4cd-5248684ba7fd.png)

The field is used only in a few places in standard objects, so the modification would have low impact.

**Comment by MirabelaRobu** [comment]
Thank you, we will consider using our own field.

**Comment by AlexanderYakunin** [comment]
Thank you!
