### ISSUE TITLE
[Event Request] Codeunit 7000 Sales Price Calc. Mgt. – FindServLinePrice

### ISSUE THREAD

**Issue by ttaeufer** [Microsoft/ALAppExtensions#1586]
Could we please have a Supplement in publisher OnBeforeFindServLinePrice in function FindServLinePrice Codeunit 7000 Sales Price Calc. Mgt.?

```
[External] FindServLinePrice(ServHeader : Record "Service Header";VAR ServLine : Record "Service Line";CalledByFieldNo : Integer)

// >>>>>>>>
OnBeforeFindServLinePrice(Var ServLine,ServHeader,CalledByFieldNo,var Handled);
IF Handled THEN 
    EXIT;
// <<<<<<<<  

WITH ServLine DO BEGIN


```

**Comment by JesperSchulz** [comment]
We are currently looking into a larger refactoring effort of the Sales Price module and hence cannot accept event requests for this module right now. We will keep you posted.
