### ISSUE TITLE
[Scope Change Request] - "Post Code Lookup - Table" - FindStreetNameFromAddress

### ISSUE THREAD

**Issue by rwe12345** [microsoft/ALAppExtensions#15870]
Please delete the scope 'OnPrem' on procedure FindStreetNameFromAddress so we can use this function in our cloud solution.

codeunit 11402 "Post Code Lookup - Table"

    [Scope('OnPrem')]
    procedure FindStreetNameFromAddress(var StreetName: Text[50]; HouseNo: Text[50]; var PostCode: Code[20]; var City: Text[50]; var PhoneNo: Text[30]; var FaxNo: Text[30]): Boolean
    var
        ForcePopup: Boolean;
    begin

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
