### ISSUE TITLE
[Event Request] Page 232 Apply Customer Entries OnApplyCustomerEntriesOnNextRecord

### ISSUE THREAD

**Issue by akontos** [microsoft/ALAppExtensions#15880]
Please Add an Event OnApplyCustomerEntriesOnNextRecord in Page 232 Apply Customer Entries

```
trigger OnNextRecord(Steps: Integer): Integer
    var
        NextStep: Integer;
        IsHandled: Boolean;
    begin
        OnApplyCustomerEntriesOnNextRecord(Rec, Steps, NextStep, IsHandled);
        if IsHandled then
            exit(NextStep);
        exit(Steps);
    end;
```

```
[IntegrationEvent(true, false)]
    local procedure OnApplyCustomerEntriesOnNextRecord(CustLedgerEntry: Record "Cust. Ledger Entry"; Steps: Integer; var NextStep: Integer; var IsHandled: Boolean)
    begin
    end;
```

Thank You!

**Comment by Stepanenko-Vadim** [comment]
We cannot add an empty trigger, since in will break default behavior of this page, so we cannot add such event

**Comment by akontos** [comment]
Please Check the Code. It won't break anything. You already did that in page 554 "Analysis by Dimensions"

**Comment by Stepanenko-Vadim** [comment]
Ok I will check these 4 again

**Comment by akontos** [comment]
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
