### ISSUE TITLE
request for protected variable - report 399 "Remittance Advice - Journal" - TempAppliedVendLedgEntry

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15890]
The `dataitem` uses the old `Integer` pattern, rather than a real table with `UseTemporary`, so we can't get at the fields from the temp table unless you make it `protected`. Please do so :-)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
