### ISSUE TITLE
[Event Request] Page 233 Apply Vendor Entries OnApplyVendorEntriesOnNextRecord

### ISSUE THREAD

**Issue by akontos** [microsoft/ALAppExtensions#15892]
Please Add an Event OnApplyVendorEntriesOnNextRecord in Page 233 Apply Vendor Entries

```
trigger OnNextRecord(Steps: Integer): Integer
    var
        NextStep: Integer;
        IsHandled: Boolean;
    begin
        OnApplyVendorEntriesOnNextRecord(Rec, Steps, NextStep, IsHandled);
        if IsHandled then
            exit(NextStep);
        exit(Steps);
    end;
```

```
[IntegrationEvent(true, false)]
    local procedure OnApplyVendorEntriesOnNextRecord(VendorLedgerEntry: Record "Vendor Ledger Entry"; Steps: Integer; var NextStep: Integer; var IsHandled: Boolean)
    begin
    end;
```

Thank You!

**Comment by Stepanenko-Vadim** [comment]
We cannot add an empty trigger, since in will break default behavior of this page, so we cannot add such event

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by Stepanenko-Vadim** [comment]
My message is the one to believe :)

**Comment by panas78** [comment]
Actually it does not break anything since it will exit the default steps as it would if no code was present

**Comment by akontos** [comment]
Ι don't agree that the event will break anything. If not handled will exit the parameter steps. In any case we have already did that in a different object. Please check page 554 "Analysis by Dimensions".

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
