### ISSUE TITLE
[Event Request] Page 233 Apply Vendor Entries OnApplyVendorEntriesOnFindRecord

### ISSUE THREAD

**Issue by akontos** [microsoft/ALAppExtensions#15891]
Please Add an Event OnApplyVendorEntriesOnFindRecord in Page 233 Apply Vendor Entries

```
trigger OnFindRecord(Which: Text): Boolean
    var
        Found: Boolean;
        IsHandled: Boolean;
    begin
        OnApplyVendorEntriesOnFindRecord(Rec, Which, Found, IsHandled);
        if IsHandled then
            exit(Found);
        exit(true);
    end;
```

```
[IntegrationEvent(true, false)]
    local procedure OnApplyVendorEntriesOnFindRecord(VendorLedgerEntry: Record "Vendor Ledger Entry"; Which: Text; var Found: Boolean; var IsHandled: Boolean)
    begin
    end;
```

Thank You!

**Comment by Stepanenko-Vadim** [comment]
We cannot add an empty trigger, since in will break default behavior of this page, so we cannot add such event

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
