### ISSUE TITLE
[Request For External] Page 233 Apply Vendor Entries Global Variables

### ISSUE THREAD

**Issue by akontos** [microsoft/ALAppExtensions#15899]
Please make the following variables Protected

Currency: Record Currency;
CurrExchRate: Record "Currency Exchange Rate";

Thank You!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
