### ISSUE TITLE
[Event Request] Codeunit 6500 Item Tracking Management - OnBeforeCopyItemLedgEntryTrkgToSalesLine

### ISSUE THREAD

**Issue by maksym-ch** [Microsoft/ALAppExtensions#159]
Hi, we need to implement additional business logic after retrieving expiration date. 
The following publisher is needed to be added (before inserting temp reservation entry):
Codeunit 6500 Item Tracking Management  - Function CopyItemLedgEntryTrkgToSalesLn -
**[IntegrationEvent] OnBeforeCopyItemLedgEntryTrkgToSalesLine(VAR ItemLedgEntryBuf : TEMPORARY Record "Item Ledger Entry";ReservEntry : Record "Reservation Entry")**
![c 6500 p2](https://user-images.githubusercontent.com/44081671/47698887-b6903f80-dc19-11e8-86f7-2ec9e527a57a.png)

**Comment by maksym-ch** [comment]
> 
> 
> You already have event OnBeforeInsertReservEntryForSalesLine(ReservEntry,SalesLine) for same purpose.

Hi Alexender, which build contains the mentioned event publisher? How could I check?

**Comment by AlexanderYakunin** [comment]
You need to look into D365 BC builds using Docker. Please do not use NAV 2018 for reference.

**Comment by maksym-ch** [comment]
The mentioned OnBeforeInsertReservEntryForSalesLine(ReservEntry,SalesLine) event publisher does not meet our requirements (parameters mismatch)
The OnCopyItemLedgEntryTrkgToDocLine(ItemLedgEntryBuf,ReservEntry)  could be used instead.

This issue can be closed.
