### ISSUE TITLE
[Protection Level] Table 36 "Sales Header" - Protected vars needed

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/ALAppExtensions#15906]
Hi, 

can you please change the variables `SkipSellToContact` and `SkipBillToContact` to **protected vars**, so we can change this variable from a page extension. (Custom Search with setting Contact when validating the **Sell to Customer No.** etc.)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
