### ISSUE TITLE
[Event Request] OnBeforeValidateQuantityIsBalanced in table 5741 "Transfer Line"

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#15908]
Hello, with reference to issue #15903, please consider adding the following procedure and event to table 5741 "Transfer Line"

```
    local procedure ValidateQuantityIsBalanced(TotalQty: Decimal; TotalQtyBase: Decimal; QtyToHandle: Decimal; QtyToHandleBase: Decimal; QtyHandled: Decimal; QtyHandledBase: Decimal)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeValidateQuantityIsBalanced(Rec, xRec, CurrFieldNo, IsHandled);
        if IsHandled then
            exit;

        UOMMgt.ValidateQtyIsBalanced(TotalQty, TotalQtyBase, QtyToHandle, QtyToHandleBase, QtyHandled, QtyHandledBase);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateQuantityIsBalanced(var TransferLine: Record "Transfer Line"; xTransferLine: Record "Transfer Line"; CurrentFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;
```

and replacing `UOMMgt.ValidateQtyIsBalanced(...);` with `ValidateQuantityIsBalanced(...);`

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
