### ISSUE TITLE
[Extensibility Enhancement] Uniform ValidateQuantityIsBalanced events across tables

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#15903]
Hello, you recently introduced a new check on balanced quantities with the new `ValidateQtyIsBalanced` in codeunit 5402 "Unit of Measure Management".

Since you decided to only pass decimal values as parameters, it's clear that if we want to do any customization on this check, we need to do it before the procedure is called, when we actually know the record for which we are checking the quantities.

This is what happened with issues #15501 and #15773. This issues were resolved just a few days one from another, and yet the implementation on the two tables is very different:

table 7317 "Warehouse Receipt Line":
```
IsHandled := false;
OnValidateQtyToReceiveOnBeforeUOMMgtValidateQtyIsBalanced(Rec, xRec, IsHandled);
if not IsHandled then
    UOMMgt.ValidateQtyIsBalanced(Quantity, "Qty. (Base)", "Qty. to Receive", "Qty. to Receive (Base)", "Qty. Received", "Qty. Received (Base)");
```

table 7321 "Warehouse Shipment Line":
```
ValidateQuantityIsBalanced();
```
where
```
    local procedure ValidateQuantityIsBalanced()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeValidateQuantityIsBalanced(Rec, IsHandled);
        if IsHandled then
            exit;

        UOMMgt.ValidateQtyIsBalanced(Quantity, "Qty. (Base)", "Qty. to Ship", "Qty. to Ship (Base)", "Qty. Shipped", "Qty. Shipped (Base)");
    end;
```

Since none of these procedures have been released yet, I request that you uniform them: I find what you did in table 7321 "Warehouse Shipment Line" to be cleaner and easier to read, and if you add the xRec parameter like you did in table 7317 "Warehouse Receipt Line" it would be just perfect. This way, the _same_ OnBefore event for the _same_ procedure call in these twin tables will be the same.

OnBefore events for this procedure are missing all over the place, and I hope you will consider uniforming them to what this issue is proposing.

Thank you

**Comment by f0ffee** [comment]
Now this is where it becomes trickier, I guess: in tables Purchase Line, Transfer Line and Service Line, the procedure is called multiple times with different quantities. So for the sake of uniformity, please consider ALL of the issues linked to this one to figure out what's the best way to do it.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
