### ISSUE TITLE
[Event Request] codeunit 5940 ServContractManagement - function CheckContractGroupAccounts

### ISSUE THREAD

**Issue by PavlosPGP** [microsoft/ALAppExtensions#15902]
New event publisher in function CheckContractGroupAccounts as follows:

    procedure CheckContractGroupAccounts(ServContractHeader: Record "Service Contract Header")
    var
        GLAcc: Record "G/L Account";
        ServContractAccGr: Record "Service Contract Account Group";
        IsHandled: Boolean;
    begin
        // New Event -> Start
        IsHandled := false;
        OnBeforeCheckContractGroupAccounts(ServContractHeader,IsHandled);
        if IsHandled then
            exit;
        // New Event <- End

        ServContractHeader.TestField("Serv. Contract Acc. Gr. Code");
        ServContractAccGr.Get(ServContractHeader."Serv. Contract Acc. Gr. Code");
        ServContractAccGr.TestField("Non-Prepaid Contract Acc.");
        GLAcc.Get(ServContractAccGr."Non-Prepaid Contract Acc.");
        GLAcc.TestField("Direct Posting");
        if ServContractHeader.Prepaid then begin
            ServContractAccGr.TestField("Prepaid Contract Acc.");
            GLAcc.Get(ServContractAccGr."Prepaid Contract Acc.");
            GLAcc.TestField("Direct Posting");
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckContractGroupAccounts(ServiceContractHeader: Record "Service Contract Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
