### ISSUE TITLE
request for protected variable - report 1316 "Standard Statement" - IncludeAgingBand

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15912]
Further to https://github.com/microsoft/ALAppExtensions/issues/13290
I've noticed that this option (caption 'Include Aging Band') is not available to report extensions.
We would like to set it to default to Yes in OnOpenPage() of the request options page.
Thus can you please make it protected? Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
