### ISSUE TITLE
[Event Request] OnBeforeCheckAutosearchForDuplicates in Codeunit 5060 DuplicateManagement

### ISSUE THREAD

**Issue by HaukeSchuldt** [microsoft/ALAppExtensions#15918]
Hello,

please add an Event OnBeforeCheckAutosearchForDuplicates in Codeunit 5060 DuplicateManagement. It will allow to call the duplicate check procedure independently of the AutoSearch setting from Marketing Setup. 

    procedure DuplicateExist(Cont: Record Contact): Boolean
    var
        DuplCont: Record "Contact Duplicate";
        IsHandled: Boolean;
    begin        
        IsHandled := false;
        OnBeforeCheckAutosearchForDuplicates(Cont, IsHandled);
        if not IsHandled then begin
            RMSetup.Get();
            if not RMSetup."Autosearch for Duplicates" then
                exit(false);
        end;
        DuplCont.FilterGroup(-1);
        DuplCont.SetRange("Contact No.", Cont."No.");
        DuplCont.SetRange("Duplicate Contact No.", Cont."No.");
        DuplCont.FilterGroup(0);
        DuplCont.SetRange("Separate Contacts", false);
        exit(DuplCont.Find('=<>'));
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckAutosearchForDuplicates(Contact: Record Contact; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
