### ISSUE TITLE
request for protected variable - report 1316 "Standard Statement" - RemainingAmount

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15911]
Further to https://github.com/microsoft/AlAppExtensions/issues/13126 what we basically want to do is

```al
                    CustBalance -= DtldCustLedgEntries.Amount;
                    CustBalance += RemainingAmount;
```

so that if showing only Open CLEs, we accumulate the Remaining Amount instead of the Amount.

We can do this by recalculating the Remaining Amount of the DCLE's parent CLE, but of course we'd prefer not to have to write that code or (possibly?) redo that calculation.

Thus making `RemainingAmount` `protected` would make this a lot nicer. Please can you do so? Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
