### ISSUE TITLE
[Request For External] Report 840 Suggest Worksheet Line

### ISSUE THREAD

**Issue by akontos** [microsoft/ALAppExtensions#15914]
Please make the following variables protected in Report 840 Suggest Worksheet Line to allow Extensibility

```
protected var
        Window: Dialog;
        ConsiderSource: array[50] of Boolean;
        SourceType: Enum "Cash Flow Source Type";
        CFWorksheetLine2: Record "Cash Flow Worksheet Line";
        Customer: Record Customer;
        Vendor: Record Vendor;
        CFSetup: Record "Cash Flow Setup";
        SelectionCashFlowForecast: Record "Cash Flow Forecast";
        Currency: Record Currency;
        CurrExchRate: Record "Currency Exchange Rate";
        TotalAmt: Decimal;
```

Thank You!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
