### ISSUE TITLE
[Event Request] OnAfterCollectData in Table 64 "Merge Duplicates Buffer"

### ISSUE THREAD

**Issue by HaukeSchuldt** [microsoft/ALAppExtensions#15922]
Dear Business Central team,

the following event in Table 64 "Merge Duplicates Buffer" would be really great as it would allow to show related data on Merge Duplicates this is not implemented using a table relation but a different data identification approach.  

    local procedure CollectData()
    begin
        ClearData;
        CollectFieldData;
        if not IsConflict then
            CollectRelatedTables;
        OnAfterCollectData(Rec, TempMergeDuplicatesLineBuffer);
    end;
    
    [IntegrationEvent(false, false)]
    local procedure OnAfterCollectData(MergeDuplicatesBuffer: Record "Merge Duplicates Buffer"; var TempMergeDuplicatesLineBuffer: Record "Merge Duplicates Line Buffer" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
