### ISSUE TITLE
[Event Request] Codeunit 5763 "Whse.-Post Shipment": Handled Pattern in TryPostSource<Type>Document Functions

### ISSUE THREAD

**Issue by NilsGruettner** [microsoft/ALAppExtensions#15926]
Hi,

please add handled patterns to

- `OnBeforeTryPostSourcePurchDocument ` in `TryPostSourcePurchDocument()`
- `OnBeforeTryPostSourceTransferDocument ` in `TryPostSourceTransferDocument()`

In `TryPostSourceSalesDocument()`, there is already a handled pattern with the event publisher `OnPostSourceDocumentOnBeforeSalesPost` so it would make sense to equalize all these publishers.

In my specific use case, I need to run the whole posting process in a single transaction (using CommitBehavior::Ignore), so the `if Codeunit.Run()` statements in the TryPostSource<Type>Document functions will raise a runtime error and I need a way to skip them/replace them with `Codeunit.Run()` calls. For sales this already works, so it would be great if this would work for the other document types aswell.

Alternatively you could provide a way to change the `WhseSetup."Shipment Posting Policy"` in `PostSourceDocument`, but I think the first approach is more sensible.

Thanks and kind regards!

<br>
Version: DE Business Central 19.2 (Platform 19.0.32956.34411 + Application 19.2.32968.34456)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
