### ISSUE TITLE
Azure blob services api

### ISSUE THREAD

**Issue by ohlfsen** [microsoft/ALAppExtensions#15929]
In the codeunit 9044 "ABS Format Helper" we have a Label used for URI generation

> AppendType1Lbl: Label '%1%2=%3', Comment = '%1 = Concatenation character, %2 = Parameter Identifer, %3 = Parameter Value';

This URI generation will result in an unusable URI when the code is run by a user with language

> target-language="da-DK 

because of a danish translation of the label with blanks in it.

> %1%2 = %3

![image](https://user-images.githubusercontent.com/45096635/150010342-bc3b86b8-84fc-4b1f-aca2-0cb7407e56a9.png)

Did a random check of some other translations which did not appear to have this issue.

B.R. Allan

**Comment by mazhelez** [comment]
Nice catch, @ohlfsen 

In this particular case, the string should just be locked (`Locked = true`) as the translation team should bother "translating" it.

We'd gladly have it fixed. However, I bet it'll be faster if you provide a fix yourself as a PR to this repo. It's a half-liner ;)

**Comment by JesperSchulz** [comment]
We've fixed the issue. And we'll be backporting the fix to be released with 19.4. Thanks for reporting.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
