### ISSUE TITLE
[Protected Request] Report 492 Copy Purchase Document - make multiple variables protected

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#15924]
Please make the following variables from the Report 492 "Copy Purchase Document" protected. 

```al
    protected var
        PurchHeader: Record "Purchase Header";
        FromPurchHeader: Record "Purchase Header";
        FromDocType: Enum "Purchase Document Type From";
        FromDocNo: Code[20];
        FromDocNoOccurrence: Integer;
        FromDocVersionNo: Integer;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
