### ISSUE TITLE
Codeunit 1535 "Approvals Mgmt. - Event Requests OnCreateApprovalRequestOnBeforeSetApproverType and OnCreateApprovalRequestForApproverChainOnBeforeCheckApproverId

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#15931]
Hello,

The following two event requests were approved in July and August, but they have not yet been implemented in 19.5 version:
https://github.com/microsoft/ALAppExtensions/issues/13311
https://github.com/microsoft/ALAppExtensions/issues/13684

Can you please let us know what is the status for them? Will they be delivered in 19.5? 

Thank you

**Comment by Oleg-Romashkov** [comment]
In scope of your requests following events were added/updated:

- OnBeforeCreateApprovalRequests
- OnCreateApprovalRequestForApproverChainOnAfterCheckApprovalEntrySenderID
