### ISSUE TITLE
request for public/external procedure - table 36 "Sales Header" - local procedure LookupContact(CustomerNo: Code[20]; ContactNo: Code[20]; var Contact: Record Contact)

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15938]
We are adding a "Requestor" field to Sales Credit Memos and want it to lookup Contacts relevant to either the Sell-to or Bill-to Customer No.

As of now, we'll have to copy and paste your `LookupContact()` procedure as used on the standard Bill-to/Sell-to Contact fields. But we would prefer to reuse/share your implementation.

Thus can you please make this function public so that we can call it? Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
