### ISSUE TITLE
[Event Change Request] - SalesPost.Codeunit - OnSumSalesLines2OnBeforeDivideAmount

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#15946]
We would like to request the following event change:
Object: SalesPost.Codeunit
ToDo: add var to SalesLineQty

Event Code:
```al
[IntegrationEvent(false, false)]
local procedure OnSumSalesLines2OnBeforeDivideAmount(var OldSalesLine: Record "Sales Line"; var IsHandled: Boolean; SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; QtyType: Option; var SalesLineQty: Decimal; var TempVATAmountLine: Record "VAT Amount Line" temporary; var TempVATAmountLineRemainder: Record "VAT Amount Line" temporary; IncludePrepayments: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
