### ISSUE TITLE
[Event Change Request] - SalesPost.Codeunit - OnBeforePostItemTracking

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#15945]
We would like to request the following event change:
Object: SalesPost.Codeunit
ToDo: add var to TrackingSpecificationExists
Event Code:
```al
[IntegrationEvent(false, false)]
local procedure OnBeforePostItemTracking(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; var TrackingSpecificationExists: Boolean; var TempTrackingSpecification: Record "Tracking Specification" temporary; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
