### ISSUE TITLE
[Protected var Request] - ItemAvailbyLocationLines.Page

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#15940]
We would like to have the following variables as protected var, so we can use them.

Object: ItemAvailbyLocationLines.Page
Variables:
```al
protected var
    ExpectedInventory: Decimal;
    QtyAvailable: Decimal;
    PlannedOrderReleases: Decimal;
    GrossRequirement: Decimal;
    PlannedOrderRcpt: Decimal;
    ScheduledRcpt: Decimal;
    ProjAvailableBalance: Decimal;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
