### ISSUE TITLE
[Extensibility Request] Codeunit 99000845 Reservation Management - Change UpdateReservation() to global

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#15949]
In order to make reservation management usable with extension tables, as suggested in #15801 by @Stepanenko-Vadim, please change UpdateReservation() function to global
```
procedure UpdateReservation(EntryIsPositive: Boolean)
[...]
```
and enable IncludeSender in the OnSetReservSource() event:
```
[IntegrationEvent(true, false)]
local procedure OnSetReservSource(SourceRecRef: RecordRef; var ReservEntry: Record "Reservation Entry"; Direction: Enum "Transfer Direction")
begin
end;
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
