### ISSUE TITLE
[Event Change Request] - SalesLine.Table - OnBeforeInitQty

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#15948]
We would like to request the following event change:
Object: SalesLine.Table
ToDo: We need a way to init outstanding qty with other conditions.
Alternative: It would also work if the procedure InitQtyToAsm() is set to global like all the other used procedures.

Where is the event placed:
```al
local procedure InitQty()
var
    IsHandled: Boolean;
    DoInitOutstanding: Boolean;
begin
    IsHandled := false;
    DoInitOutstanding := (xRec.Quantity <> Quantity) or (xRec."Quantity (Base)" <> "Quantity (Base)");
    OnBeforeInitQty(Rec, xRec, IsAsmToOrderAllowed(), IsAsmToOrderRequired(), DoInitOutstanding, IsHandled);
    if IsHandled then
        exit;

    if DoInitOutstanding then begin
        InitOutstanding();
        if IsCreditDocType() then
            InitQtyToReceive()
        else
            InitQtyToShip();
        InitQtyToAsm();
        SetDefaultQuantity();
    end;
end;
```
Event Code:
```al
[IntegrationEvent(false, false)]
local procedure OnBeforeInitQty(var SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line"; IsAsmToOrderAlwd: Boolean; IsAsmToOrderRqd: Boolean; var DoInitOutstanding: Boolean; var IsHandled: Boolean)
begin
end;
```

**Comment by pri-kise** [comment]
The procedure `InitQtyToAsm` is set to protected which means that you can call the procedure from a tableextension.
Therefore you could simple add wrapper function as tableextensions that will call the procedure `InitQtyToAsm`

**Comment by acadonAG-dev** [comment]
Sorry I did not know the access modifier was already changed.
Thank you for this information.
