### ISSUE TITLE
Jobs in the warehousing module

### ISSUE THREAD

**Issue by cbrandemann** [microsoft/ALAppExtensions#15956]
Projects may require a lot of material arriving over a longer period. When a company runs multiple projects at the same time it is important to keep track of where what material for which Job is stored. Business Central’s warehousing module provides the tools to organize this. With these tools, material can be retrieved easily with a lower chance to become obsolete or damaged. This enables the planner to become more efficient as there will be less exceptions. Unfortunately Business Central has a limited integration with Jobs.

To-Increase Jobs Management Suite fully integrates with Business Central’s warehousing module by adding a Consume Job Bin Code to a Location as well as Transport and Deliveries functionality. Material to be used in a Job can now follow the complete, directed, warehousing process from receiving and put-away to picking for consumption in the Job or delivery to a Job Site.

In the Base App it was possible to create this functionality and customers are using this. At this moment we are running a project to move this functionality to an extension.

To achieve this we need a new source (Job Planning Line) in the warehouse functionality.  We have prototyped this extension now by copying the standard code. We would like to consult with you on how we can best deliver all the required extension points, global functions and protected variables.

**Comment by StanPesotskiy** [comment]
If you think that part of this solution could be a standard functionality you can describe it and submit a product suggestion on https://aka.ms/bcideas
We cannot suggest you good extensions points as we are not allowed to read your code and can only ask questions when you request a certain event or other change in here and it is unusual. If a request is typical and easy to do we just implement it and you get it in the next update for the last shipped version. 

Please always put the full detailed signature of the requested events and the parameters passed in the call.
Please put the code surrounding the place, where you expect a new event call, as a text (copied form VSCode) not as a screenshot. It helps us finding the right place quickly if you put enough code to identify the unique place. 

One request should be about one object, please don't mix multiple objects in one request. If you ask for multiple events called from one method you can put them all into one request, same for requests for protected vars/functions.
