### ISSUE TITLE
[Request for Protected vars] Purchase document subpages - ItemReferenceVisible

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#15957]
Please set variable ItemReferenceVisible: Boolean as protected in the five below mentioned subpages.

All six sales subpages and page 510 "Blanket Purchase Order Subform" were already done correctly but allas the other five purchase pages were pasted in the wrong section:

page 54 "Purchase Order Subform"
page 97 "Purchase Quote Subform"
page 6641 "Purchase Return Order Subform"
page 98 "Purch. Cr. Memo Subform"
page 55 "Purch. Invoice Subform"

**Comment by AlexanderYakunin** [comment]
We do not use ItemReferenceVisible anymore, fields Item Reference No. are visible by default.
