### ISSUE TITLE
[Event Request] table 23 Vendor: Add parameter VendBankAccount to event OnBeforeUpdateVendorBankAccounts

### ISSUE THREAD

**Issue by MarcoHeijden** [microsoft/ALAppExtensions#15953]
Please add the parameter VendBankAcc to the event OnBeforeUpdateVendorBankAccounts

    procedure UpdateVendorBankAccounts(UseFieldCaption: Text[250])
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateVendorBankAccounts(VendBankAcc, IsHandled); <-- Add parameter VendBankAcc
        if not GuiAllowed or IsHandled then
            exit;

        VendBankAcc.SetRange("Vendor No.", "No.");

        if VendBankAcc.Find('-') then begin
            IsHandled := false;
            OnUpdateVendorBankAccountsOnBeforeConfirm(Rec, IsHandled);
            if not IsHandled then
                if not Confirm(StrSubstNo(Text11000000, UseFieldCaption)) then
                    exit;
            repeat
                VendBankAcc."Account Holder Name" := Name;
                VendBankAcc."Account Holder Address" := Address;
                VendBankAcc."Account Holder Post Code" := "Post Code";
                VendBankAcc."Account Holder City" := City;
                VendBankAcc."Acc. Hold. Country/Region Code" := "Country/Region Code";
                VendBankAcc.Modify();
            until VendBankAcc.Next() = 0;
            Modify();
        end;
    end;

    [IntegrationEvent(true, false)]
    local procedure OnBeforeUpdateVendorBankAccounts(var VendBankAccount: Record "Vendor Bank Account"; var IsHandled: Boolean)
    begin
    end;

**Comment by Stepanenko-Vadim** [comment]
Will it work for you if we add **VendBankAcc** to **OnBeforeUpdateVendorBankAccounts** instead pf creating a new event?

**Comment by MarcoHeijden** [comment]
Yes, that will work as well. I updated the GitHub request accordingly.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
