### ISSUE TITLE
[Event-Request] Codeunit 392 "Reminder-Make" - OnBeforeInsertReminderLine

### ISSUE THREAD

**Issue by sandort012** [microsoft/ALAppExtensions#15954]
We would like to request the addition of an event in procedure AddLineFeeForCustLedgEntry() from table 392 "Reminder-Make".
```
procedure AddLineFeeForCustLedgEntry(var CustLedgEntry: Record "Cust. Ledger Entry";var ReminderLevel: Record "Reminder Level";NextLineNo: Integer)
[...]
  OnBeforeInsertReminderLine(ReminderLine);
  ReminderLine.Insert(true);
end;
```
```
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertReminderLine(var ReminderLine: Record "Reminder Line")
begin
end;
```

Thanks in advance,
Thomas Sandor
COSMO Consult Ltd.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
