### ISSUE TITLE
extensibility-bug - table 1670 "Option Lookup Buffer" - OnBeforeIncludeOption

### ISSUE THREAD

**Issue by SBiernat** [microsoft/ALAppExtensions#15960]
Regarding to case #14712 i requested the publisher OnBeforeIncludeOption to be extended for the Document Type

In 19.1 the publisher was extended by the RecRef parameter with a Bug.
I reported this Bug with case #15465 which was closed because you don't think there is a problem.

But perhaps you can try yourself this publisher.
Here is my Code:
codeunit 50000 "MY Event Subscriber"
{
    [EventSubscriber(ObjectType::Table, Database::"Option Lookup Buffer", 'OnBeforeIncludeOption', '', false, false)]
    local procedure OptionLookupBuffer_OnBeforeIncludeOption(OptionLookupBuffer: Record "Option Lookup Buffer"; LookupType: Option; Option: Integer; var Handled: Boolean; var Result: Boolean; RecRef: RecordRef)
    begin
        message(Format(RecRef));
    end;
}

And these are the messages, when i open a Sales Order Card.
![image](https://user-images.githubusercontent.com/45194723/150630936-838d979f-2630-469e-8580-c5496f5e717e.png)
![image](https://user-images.githubusercontent.com/45194723/150630944-0c49fb4c-5a70-4f56-af8b-8f784ac77288.png)
![image](https://user-images.githubusercontent.com/45194723/150630955-0a33cc2c-65b2-43dc-97c6-a6583d5118a3.png)
![image](https://user-images.githubusercontent.com/45194723/150630961-11889a8c-5e68-4b3d-b9e3-ca8c8f38bae4.png)
 
As you can see, there is only one Field changing and the extensibility that was made brings no improvement.

**Comment by dannoe** [comment]
This is not possibile because the code is called in the OnInit trigger of the Pages. At this time of calling the trigger, there is no record given in the subform.

**Comment by Oleg-Romashkov** [comment]
Hi,

One more issue with document type parameter - the FillLookupBuffer is called also from pages which do not have document type:

- page 171 "Standard Sales Code Subform"
- page 176 "Standard Purchase Code Subform"

However, there is a workaround which could help you to identify the source page called the event OnBeforeIncludeOption with callstack. This is a bit tricky, but it works and do not cause any "stop transaction" issues:
```

codeunit 50000 "MY Event Subscriber"
{
    [EventSubscriber(ObjectType::Table, Database::"Option Lookup Buffer", 'OnBeforeIncludeOption', '', false, false)]
    local procedure OptionLookupBuffer_OnBeforeIncludeOption(OptionLookupBuffer: Record "Option Lookup Buffer"; LookupType: Option; Option: Integer; var Handled: Boolean; var Result: Boolean; RecRef: RecordRef)
    var
        CallStack: Text;
    begin
        if ThrowError() then;
        CallStack := GetLastErrorCallStack();

        if StrPos(CallStack, 'Sales Order Subform') <> 0 then
            Message('Sales Order');
    end;

    [TryFunction]
    local procedure ThrowError()
    begin
        // Throw an error to get the call stack by GetLastErrorCallstack
        Error('');
    end;
}

```
![image](https://user-images.githubusercontent.com/82887855/154070952-5ff1b7a1-b46d-4ad4-9c09-34a808c6513d.png)
