### ISSUE TITLE
[Event Request] Table 9650 - Custom Report Layout - OnBeforeExportReportLayout

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#15978]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeExportReportLayout` to be added to Table 9650 Custom Report Layout with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeExportReportLayout(CustomReportLayout: Record "Custom Report Layout"; var DefaultFileName: Text; ShowFileDialog: Boolean)
    begin
    end;
```
with **var** parameter `DefaultFileName`.

which would be called as follows from `ExportReportLayout`:
```al
    procedure ExportReportLayout(DefaultFileName: Text; ShowFileDialog: Boolean): Text
    var
        TempBlob: Codeunit "Temp Blob";
        FileMgt: Codeunit "File Management";
    begin
        OnBeforeExportReportLayout(Rec, DefaultFileName, ShowFileDialog);

        ...
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
