### ISSUE TITLE
[Event Request] Table 11400 - CBG Statement - OnBeforeMakeGenJournalLine (NL Localization)

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#15974]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeMakeGenJournalLine` to be added to Table 11400 CBG Statement with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeMakeGenJournalLine(var GenJnlLine: Record "Gen. Journal Line"; ForEachDocumentNo: Code[20]; ForEachDate: Date; TotAmountVV: Decimal; TotAmountLV: Decimal)
    begin
    end;
```
with **var** parameter: `GenJnlLine`

which would be called as follows from `MakeGenJournalLine`:
```al
    [Scope('OnPrem')]
    procedure MakeGenJournalLine(var GenJnlLine: Record "Gen. Journal Line"; ForEachDocumentNo: Code[20]; ForEachDate: Date; TotAmountVV: Decimal; TotAmountLV: Decimal)
    var
        DocumentType: Enum "Gen. Journal Document Type";
    begin
        OnBeforeMakeGenJournalLine(GenJnlLine, ForEachDocumentNo, ForEachDate, TotAmountVV, TotAmountLV);
        ...
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
