### ISSUE TITLE
[Event Request] Table 39 - Purchase Line - Add parameter Page ItemChargeAssgnts to OnAfterShowItemChargeAssgnt

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#15973]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnAfterShowItemChargeAssgnt` in Table 39 Purchase Line to be extended resulting in the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnAfterShowItemChargeAssgnt(var PurchaseLine: Record "Purchase Line"; var ItemChargeAssgnmtPurch: Record "Item Charge Assignment (Purch)"; var ItemChargeAssgnmtPurch: Page "Item Charge Assignment (Purch)")
    begin
    end;
```

which would be called as follows from `ShowItemChargeAssgnt`:
```al
OnAfterShowItemChargeAssgnt(Rec, ItemChargeAssgntPurch, ItemChargeAssgnts);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
