### ISSUE TITLE
"PostingDescription" in "Calculate Depreciation" not available in italian localization

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#15975]
In the Italian localization the control _PostingDescription_ in _report 5692 "Calculate Depreciation"_ does not exists.
In any other (tested) localization and w1 this field exist.

i think this is an extensibility bug.
Tested with current Version (19.3.34541.35210) and next Minor Preview (19.4.35230.0).

**Comment by AlexanderYakunin** [comment]
Report Calculate Depreciation in Italian version use 3 posting description and document numbers per Normal/Anticipated/Acc./Red. Depreciation. Looks like this change is forced by local regulation.

**Comment by ChrisBlankDe** [comment]
Localization should never have a smaller public interface than w1!
You have fixed issues like this in #13757, #13103 and #14678.

Please add the control and set it to visible false.
else anybody who uses this control is not able to publish his app in Italia.

**Comment by AlexanderYakunin** [comment]
Of course I agree, but this is legacy customization created like 15 years ago. We are working on such issues and cleaning it up. OK, we will add this back, while it will require some redesign of report for IT.

**Comment by AlexanderYakunin** [comment]
Fixed for next major

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14056.
