### ISSUE TITLE
event parameter request - codeunit 5200 "Employee/Resource Update" - ResUpdate() - OnAfterResUpdate() - Employee

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15989]
The `Employee` record from which the `var Resource` is being updated is not passed... thus how can we include more fields in the update?? Please add and pass like so:

```al
    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateResource(var Resource: Record Resource; Employee: Record Employee)
    begin
    end;
```

```al
        OnAfterUpdateResource(Res, Employee);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
