### ISSUE TITLE
extensibility bug - page 256 "Payment Journal" - Apply Entries action not enabled for Account Types = Employee (but page 39 "General Journal" does enable it!)

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#15981]
We cannot view Apply Entries for Employee payments. I thought maybe that functionality was not implemented, but the General Journal page *does* allow it! Shouldn't these pages both agree, especially the Payment Journal since that's most relevant to paying employees..?

![image](https://user-images.githubusercontent.com/63455896/150796285-d156b59e-b662-4b3f-bbb2-7c74e8953206.png)

Please can the action in page 256 be updated to match page 39?

I would hugely appreciate if, as it's relatively simple / no-brainer, this can be dealt with here... I used to have the ability to submit application bugs via Partner Centre, but this has mysteriously vanished, and our partner-partner who apparently should report these things for us is not replying to my attempts to get a login set up :-(

It kind of *is* an extensibility bug, in that now we have to make an extension just to fix the action, update the boolean whenever a relevant field changes or record is loaded, etc....

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
