### ISSUE TITLE
[Event Request] Add. Events Parameters - codeunit 99000773 "Calculate Prod. Order" - OnBeforeUpdateProdOrderDates

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#15986]
Could you please add the following Parameter to Event OnBeforeUpdateProdOrderDates in codeunit 99000773 "Calculate Prod. Order"

Adjust Publisher Call in Fct. CalculateProdOrderDates:

````
-   OnBeforeUpdateProdOrderDates(ProdOrder, ProdOrderLine);
+   OnBeforeUpdateProdOrderDates(ProdOrder, ProdOrderLine, ProdOrderModify);
````

Adjusted Publisher:

Add Param (with var): ProdOrderModify

````
    [IntegrationEvent(false, false)]
-   local procedure OnBeforeUpdateProdOrderDates(var ProductionOrder: Record "Production Order"; var ProdOrderLine: Record "Prod. Order Line")
+   local procedure OnBeforeUpdateProdOrderDates(var ProductionOrder: Record "Production Order"; var ProdOrderLine: Record "Prod. Order Line"; var ProdOrderModify: Boolean)
    begin
    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
