### ISSUE TITLE
[Extensibility Bug/Breaking Change] Codeunit 44 - ReportManagement - ReportGetCustomWord also reached for new members of enum "Custom Report Layout Type" (<>Word)

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#15984]
Dear ALAppExtensions team,

Through this issue we would like to report an extensibility bug in Codeunit 2000000005 Reporting Triggers, event `ReportGetCustomWord` (/Codeunit 44 ReportManagement, procedure `ReportGetCustomWord`), which is incorrectly being triggered when a report is being run with a Custom Report Layout of Type <> Word, e.g., a type that is being added to the `Custom Report Layout Type` enum via an enumextension object (Base Application, build 20.0.35273.0)
```
    [BusinessEvent(false)]
    procedure ReportGetCustomWord(ReportId: Integer; var LayoutStream: OutStream; var Success: Boolean)
    begin
    end;
```
This is a breaking change and extensibility bug for new enum members of the `"Custom Report Layout Type"` enum.

That is, `ReportManagement.ReportGetCustomWord` will invoke the `"Document Report Mgt.".GetWordLayoutStream` procedure, which in turn invokes the `"Document Report Mgt.".ValidateAndUpdateWordLayoutOnRecord` procedure that runs a `TestField` for `Type::Word`, but the report could also be run with other custom report layout types.

So, this could either be resolved in `ReportManagement.ReportGetCustomWord`, or `"Document Report Mgt.".GetWordLayoutStream` or `"Reporting Triggers".ReportGetCustomWord`.

**Comment by StanPesotskiy** [comment]
@rvanbekkum the events you mentioned in the call stack are marked as obsolete so we don't want to do much about them as they are gone soon. 
Would it be helpful for you if we add an event that would allow you to skip the failing testfield()?

**Comment by rvanbekkum** [comment]
Hi @StanPesotskiy,
Thank you for your message. We see there are several new events in place since this issue has been reported. Please let us have a look as soon as there is a build where the `OnCustomDocumentMerger` event works so we can provide feedback on all of that. Do you happen to know when that will be ready for testing? 😊

**Comment by StanPesotskiy** [comment]
@rvanbekkum the mentioned events are marked as obsolete with the message: 'This procedure will be replaced with platform functionality. Subscribe to the event FetchReportLayoutByCode instead to retrieve a layout.' This change was done by the platform team. I assume that you can try to work with FetchReportLayoutByCode event and if it is still not triggered as it supposed to please reach out to the relevant support channels:
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
