### ISSUE TITLE
[Extensibility Bug/Breaking Change] Codeunit 44 - ReportManagement - OnCustomDocumentMerger (not a working replacement yet for MergeDocument events)

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#15983]
Dear ALAppExtensions team,

Through this issue we would like to report that the replacement for `ReportManagement.OnMergeDocumentReport` and `"Document Report Mgt.".OnBeforeMergeDocument` which is the new `ReportManagement.OnCustomDocumentMerger` event does not get triggered in the Base Application build 20.0.35273.0.
It concerns the following event that does not get triggered:
```al
    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Reporting Triggers", 'CustomDocumentMerger', '', false, false)]
    local procedure CustomDocumentMerger(ObjectID: Integer; ReportAction: Option SaveAsPdf,SaveAsWord,SaveAsExcel,Preview,Print,SaveAsHtml; XmlData: InStream; LayoutData: InStream; var DocumentStream: OutStream)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnCustomDocumentMerger(ObjectID, ReportAction, XmlData, LayoutData, DocumentStream, IsHandled);
        if (IsHandled) then
            exit;
    end;
```
There is no indication on why the code is not being reached or when it should be reached (but considering it is a replacement for the `MergeDocument` events, it should be triggered when a report is run with a layout of type <> Word.

**Actual Behaviour:**
The event `OnCustomDocumentMerger` is not triggered when:
* Running a report with Custom Report Layout of Type=Word
* Running a report with Custom Report Layout with a custom "Custom Report Layout Type" (= extensible enum).

**Expected Behaviour (non-breaking, allowing for extensibility)**
The event `OnCustomDocumentMerger` is triggered when:
* Running a report with Custom Report Layout of Type=Word
* Running a report with Custom Report Layout with a custom "Custom Report Layout Type" (= extensible enum).

Could you please look into this issue? Could you also supply any documentation for using the event for Custom Report Layouts (for Type = "Word", or Type = "<Custom>" (where <Custom> is a member of the "Custom Report Layout Type" enum added by an enumextension object)?

P.S.
The old events do not get triggered either, although that is explained by the comment in the `ReportManagement.MergeDocument` procedure, i.e., that it is being due to (new) EnableReportLegacyWordRender being disabled by default:
```al
    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Reporting Triggers", 'MergeDocument', '', false, false)]
    [Obsolete('Replaced by CustomDocumentMerger for support of AL driver report renders.', '20.0')]
    local procedure MergeDocument(ObjectType: Option "Report","Page"; ObjectID: Integer; ReportAction: Option SaveAsPdf,SaveAsWord,SaveAsExcel,Preview,Print,SaveAsHtml; XmlData: InStream; FileName: Text; var DocumentStream: OutStream)
    var
        DocumentReportMgt: Codeunit "Document Report Mgt.";
        IsHandled: Boolean;
    begin
// IMPORTANT: This codepath is only reachable if the platform feature switch EnableReportLegacyWordRender is active. The default is to render Word driven reports in the platform.
```

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a platform bug (the related work item id **416624**) not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
