### ISSUE TITLE
[Event Request] Codeunit 9651 - Document Report Mgt. - OnGetWordLayoutStreamOnAfterGetCustomLayoutCode

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#15985]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnGetWordLayoutStreamOnAfterGetCustomLayoutCode` to be added to Codeunit 9651 Document Report Mgt. with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnGetWordLayoutStreamOnAfterGetCustomLayoutCode(ReportID: Integer; var CustomLayoutCode: Code[20])
    begin
    end;
```
with *var* parameter `CustomLayoutCode`.

which would be called as follows from `GetWordLayoutStream` (Base Application, build 20.0.35273.0):
```al
    [Scope('OnPrem')]
    procedure GetWordLayoutStream(ReportID: Integer; var LayoutStream: OutStream; var Success: Boolean)
    var
        ReportLayoutSelection: Record "Report Layout Selection";
        CustomReportLayout: Record "Custom Report Layout";
        TempBlobIn: Codeunit "Temp Blob";
        CustomLayoutCode: Code[20];
        InStrWordDoc: InStream;
    begin
        Success := false;
        // Temporarily selected layout for Design-time report execution?
        if ReportLayoutSelection.GetTempLayoutSelected() <> '' then
            CustomLayoutCode := ReportLayoutSelection.GetTempLayoutSelected()
        else  // Normal selection
            if ReportLayoutSelection.Get(ReportID, CompanyName) and
               (ReportLayoutSelection.Type = ReportLayoutSelection.Type::"Custom Layout")
            then
                CustomLayoutCode := ReportLayoutSelection."Custom Report Layout Code";

        OnGetWordLayoutStreamOnAfterGetCustomLayoutCode(ReportID, CustomLayoutCode);

        if CustomLayoutCode <> '' then
            if not CustomReportLayout.Get(CustomLayoutCode) then
                CustomLayoutCode := '';

        if CustomLayoutCode <> '' then begin
            ValidateAndUpdateWordLayoutOnRecord(CustomReportLayout);
            CustomReportLayout.GetLayoutBlob(TempBlobIn);
            TempBlobIn.CreateInStream(InStrWordDoc);
            ValidateWordLayoutCheckOnly(ReportID, InStrWordDoc);
            CopyStream(LayoutStream, InStrWordDoc);
            Success := true;
        end;
    end;
```

Alternatively, we would like to request the `OnAfterGetCustomLayoutCode` **NOT** to be removed as the code of the `GetWordLayoutStream` procedure (where the event is _also_ used(!)) is still being reached and not being replaced by the platform.

**Comment by Stepanenko-Vadim** [comment]
The current state of this procedure and whole codeunit is that it is being absorbed by the platform, current obsolete state is:
[Obsolete('This procedure will be eventually replaced by platform functionality. Subscribe to the event FetchReportLayoutByCode instead.', '20.0')]
So we cannot implement a new app event here, since this whole codeunit and functionality is being depreciated. You can use this one meanwhile, until it's removed/fully switched to platform
