### ISSUE TITLE
[EventRequest] Additional Parameters - report 20 "Calc. and Post VAT Settlement" OnBeforePreReport

### ISSUE THREAD

**Issue by redIT-LoPf** [microsoft/ALAppExtensions#15987]
Please add two additional parameters 

![image](https://user-images.githubusercontent.com/37530329/150959820-1c3b4a8c-e266-4a35-9a24-ad92398b5602.png)

![image](https://user-images.githubusercontent.com/37530329/150959767-73b05b2d-ef7f-477b-9508-1c956d386453.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
