### ISSUE TITLE
[Event Request] Report 2000005 / 2000006 OnBeforePreReport or protected vars

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#15982]
#3772 and #342 have been closed without resolution...

---

Hello,
We are working on a solution that requires running REP2000005 (File SEPA Payments) & REP2000006 (File Non Euro SEPA Payments) with no Request Page.

The required changes have already been described in this issue:
#342
However not all the necessary events have been implemented yet.

TAB2000005 has already received the OnBeforeExportPaymentLinesOnRunReport event.

There is still no way to **alter the Global variables** set in the Request page of Reports **2000005/2000006**.
Is this still planned for future update?

Ideal would be an OnBeforePreReport trigger

- `OnBeforePreReport(VAR PaymentJournalLine, VAR GenJnlLine, VAR AutomaticPosting, VAR IncludeDimText, VAR ExecutionDate, VAR FileName)`
- Or make following global variables available by putting them in a **protected** var section:
`GenJnlLine, AutomaticPosting, IncludeDimText, ExecutionDate, FileName`

Remark: GenJnlLine is required to get the 2 options JournalTemplateName & JournalBatch.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
