### ISSUE TITLE
[Event Request] Application “Tests-General Journal”, Codeunit 134930 "ERM Applies-To Doc. No."

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#15991]
[Event Request]Application “Tests-General Journal”, 134930 "ERM Applies-To Doc. No."

Could you please insert the Event OnTestInitialize at the beginning of the Initialize procedure
![pic1](https://user-images.githubusercontent.com/45795262/150982669-8c7d16ea-4d23-4a69-9d43-7b2747e9806c.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
