### ISSUE TITLE
Make Codeunit "Assembly Line Management" global in "Assembly Header" ShowDueDateBeforeWorkDateMsg  or add new event

### ISSUE THREAD

**Issue by Frmog** [microsoft/ALAppExtensions#15997]

**Comment by Frmog** [comment]
Hi
I have been asked to disable the "Assembly due date before work date" warning message, but I dont think this is doable at the moment.
![image](https://user-images.githubusercontent.com/84179334/151162546-8c75be2c-9eb9-4c81-8976-b7fcc314e0e5.png)

Explanantion:
The only way  to disable this warning at the moment, is to use the WarninModeOff = true in the "Assembly Line Management" function
![image](https://user-images.githubusercontent.com/84179334/151162897-fced31fa-eae8-4b58-991e-bf624b01ce54.png)
![image](https://user-images.githubusercontent.com/84179334/151162916-459b133b-0863-49ed-b095-2538f1370508.png)

this flag is triggered from the "Assembly Header", with the use of a **global** variable.
![image](https://user-images.githubusercontent.com/84179334/151163067-0fcf158c-0c00-4349-8436-c8a6e1100b68.png)
![image](https://user-images.githubusercontent.com/84179334/151163114-72dac9b2-d388-45c9-94b1-d653a28ef086.png)

The problem her is that the Assembly Header function ShowDueDateBeforeWorkDateMsg uses a **local** AsmLineMgt variable, and thus, does not benefit from the WarninModeOff flag set previously
![image](https://user-images.githubusercontent.com/84179334/151163429-5e7de952-1448-469f-af8e-9c654dca7384.png)
The result of course, is that the WarningModeOff value is always false and the warning message is shown.

Thus I think that the "Assembly Header" function should use the Global asmLineMgt instead the local var, or at least, I would like to request an event in the Assembly Line Management" ShowDueDateBeforeWorkDateMsg function before the message is called.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40755.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 40841.
