### ISSUE TITLE
Qty. Rounding Precision error introduced in BC19.2

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#15994]
Qty. Rounding Precision – error when creating production order in BC19.2
Issue: 
If a component line in a production BOM is set up with a “Quantity per” significantly smaller than 1, you can get a rounding error during planning and when doing manual refresh of production orders.   

Repro:
Create Items and Production BOM
Create two items with Base Unit of Measure as below
![image](https://user-images.githubusercontent.com/28138717/151144307-86c4c3dd-8d6a-49aa-bb05-883c46106516.png)

 
70061 is a purchased item, Base UOM RULLER
70062 is a produced item, Base UOM STK with a production Bom set up as below:
![image](https://user-images.githubusercontent.com/28138717/151144325-bc2c9f5b-ec08-4279-a186-b12d2f382590.png)

 
The production bom points to item 70061 with Quantity per STK = 0,00081.

Scenario 1
Create a released production order for item 70062 with quantity 275400:
 
![image](https://user-images.githubusercontent.com/28138717/151144339-bc40a9f6-f883-4f14-8b22-e33290d6e2f9.png)

Activate Refresh Production Order, and use default settings. 
You will get this error:
![image](https://user-images.githubusercontent.com/28138717/151144393-af9220a5-82e3-4802-949b-b1bd274c8230.png)

 
The error text is:
“Qty. Rounding Precision on Item-70061 causes the Quantity and Quantity (Base) to be out of balance. Rounding of the field Quantity (Base) results to 0.”

Scenario 2
Create a sales order and add one line for item 70062, Quantity = 275400 STK
Activate Actions, Plan, Planning. This will give this Sales Order Planning suggestion:
![image](https://user-images.githubusercontent.com/28138717/151144413-ff69082c-0101-4d57-8ec8-05ddbc9b2276.png)

 
Activate Create Prod. Order and try to create a Released production order
 
![image](https://user-images.githubusercontent.com/28138717/151144424-d4120058-4486-4957-9ee6-2ec69c87b7f0.png)

When clicking Yes, you will get the same error:
 
![image](https://user-images.githubusercontent.com/28138717/151144432-5741960a-c575-4f84-8fd5-77f3dd6926ed.png)

Code Analysis
The issue is triggered because QtyRndingPrecision ends up being zero:
![image](https://user-images.githubusercontent.com/28138717/151144444-08b1d991-c2e4-4de5-96ff-b9ba7a66fba1.png)

 
This value is taken from the Prod. Order Component field “Qty. Rounding Precision (Base)”:
![image](https://user-images.githubusercontent.com/28138717/151144458-5b98ee3e-3036-46c8-98c2-d87f316bf9db.png)

 
However, the real issue is that rounding occurs at all at this point in the calculation where he fractions are very small. And thus, if we did not get a run-time error, we would be likely to end up with incorrect results.
In NAV2019 there was no rounding in this calculation; it was just a simple multiplication:
![image](https://user-images.githubusercontent.com/28138717/151144516-85e21a20-03bf-4231-82c2-61a164d80797.png)

 
The exact same code exists in Planning Component table.

In BC19 it looks like this:
 
![image](https://user-images.githubusercontent.com/28138717/151144544-077e24ee-07de-47b0-ab26-76842311e3a7.png)

As can be seen, the hardcoded rounding precisions of 0.00001 have been replaced by a call of UOMMgt.QtyRndPrecision. This procedure on the other hand is only there to enable triggering an integration event that can potentially change the precision, but in normal cases it will return the same 0.00001 value as before.
![image](https://user-images.githubusercontent.com/28138717/151144559-d528b1d2-7f10-496e-9adb-c76cf534f7f6.png)

 
Hence, the only real change of this section since NAV2019 is that the calculation of Quantity (Base) now is run through CalcBaseQty where it is rounded. This is logically wrong and is what is causing the described error.

Changes made in BC 19.2
In BC 19.2 we find some new concerning changes related to rounding in Validation trigger for Field 25 “Expected Quantity” on ProdOrderComponent table; a line has been added that will apply rounding to the calculation of “Remaining Quantity” before calculating “Remaining Quantity (Base)” 
![image](https://user-images.githubusercontent.com/28138717/151144609-15f48be4-7dd8-4bf5-b02a-e93479434f90.png)

 
What seems to happen here again is that rounding is applied to a sub result of a calculation, potentially causing the end result to be off.
It is somewhat odd this should suddenly be needed as this calculation logic has been more or less unchanged for many years. 

This is from NAV2019
![image](https://user-images.githubusercontent.com/28138717/151144624-b4b19bfc-d321-4f05-90e5-16893e45d8c0.png)

 

We strongly recommend that the original logic is reestablished.

**Comment by MortenRa** [comment]
@JesperSchulz FYI

**Comment by JesperSchulz** [comment]
Hi @MortenRa,

first of all thank you for this very detailed bug report. However, I'm afraid this is not the right place to log product defects.

This repo is only for extensibility related issues in the upcoming release. I would suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible and within our SLAs.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks again for reporting the issue and sorry for not being able to take it from here, but it's important that real product defects go through the right channels to get the right treatment.

**Comment by AlexanderLundq** [comment]
Did this ever get solved? And what was the solution to this? Having the same issue but in BC23.2.

**Comment by JesperSchulz** [comment]
If the issue persists, it was probably never reported to support. Please open a support case, following the instructions above.

**Comment by MortenRa** [comment]
It was reported through collaborate but closed with reason it was by design!!!!. I have never been a fan of collaborate the feedback is never more than a status and with the detailed information I reported I would expect them to fix the error or maybe just interact with the partner reporting the issues.

Link to support issue 
https://partner.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/607935

**Comment by AlexanderLundq** [comment]
Ok - just wanted to know if there was ever found any solution to this. But after looking at the code I can see that it never was resolved.

I think this needs to be resolved by Microsoft. But my case is exactly the same as yours, Morten. So will most likely get the same answer as you.

**Comment by AlexanderLundq** [comment]
And thanks a lot for the quick answers from both of you.
