### ISSUE TITLE
[Request for External] report 708 "Inventory Order Details" - SalesHeader

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#15993]
Can you change SalesHeader to protected var in report 708 "Inventory Order Details"?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
