### ISSUE TITLE
[Event Request] Application “Tests-Graph”, Codeunit 138921 "O365 Test Quotes"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#15990]
[Event Request]Application “Tests-Graph”, 138921 "O365 Test Quotes"

Could you please insert the Event OnTestInitialize at the beginning of the Initialize procedure
![pic1](https://user-images.githubusercontent.com/45795262/150977525-57cc90e5-3db9-4ed0-9a23-4d882355eac8.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
