### ISSUE TITLE
[Event Request] Table 5600 "Fixed Asset"- OnBeforeGetNoSeriesCode

### ISSUE THREAD

**Issue by KuljitSinghParmar** [microsoft/ALAppExtensions#15992]
Hi Team,

In table 5600 "Fixed Asset" , we need to have Integration event in  OnInsert procedure . Adding an event with handling in this procedure will solve our problem.

![image](https://user-images.githubusercontent.com/61985025/151073094-1e07751d-2c50-4e52-9d09-419f4a1acc05.png)

 trigger OnInsert()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnInsertOnBeforeInitSeries(Rec, xRec, IsHandled);
        if not IsHandled then
            if "No." = '' then begin
                FASetup.Get();
                FASetup.TestField("Fixed Asset Nos.");
                NoSeriesMgt.InitSeries(FASetup."Fixed Asset Nos.", xRec."No. Series", 0D, "No.", "No. Series");
            end;

        "Main Asset/Component" := "Main Asset/Component"::" ";
        "Component of Main Asset" := '';

        DimMgt.UpdateDefaultDim(
          DATABASE::"Fixed Asset", "No.",
          "Global Dimension 1 Code", "Global Dimension 2 Code");
    end;

  [IntegrationEvent(false, false)]
    local procedure OnInsertOnBeforeInitSeries(var FixedAsset: Record "Fixed Asset"; xFixedAsset: Record "Fixed Asset"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
