### ISSUE TITLE
[Event Request] Codeunit 22 "Item Jnl.-Post Line" - OnBeforeModifyItemOnSetItemAdjmtProperties

### ISSUE THREAD

**Issue by ZtefanBildalZ** [microsoft/ALAppExtensions#15995]
Hi,
Requesting new event in function SetItemAdjmtProperties in codeunit 22 "Item Jnl.-Post Line" before modifying an item, that is an event like OnBeforeModifyItemOnSetItemAdjmtProperties that would be placed like this:
if ModifyItem then begin
    OnBeforeModifyItemOnSetItemAdjmtProperties(Item2);
    Modify();
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
