### ISSUE TITLE
Refactor COMMIT handling CU80/90/5763/5760

### ISSUE THREAD

**Issue by sgiordy** [Microsoft/ALAppExtensions#16]
Hi,

CU 5760 and 5763 are missing of suppression of COMMIT.

In CU 80 and 90 appears "SuppressCommit" but is unusable because you need to call explicit the "SetSuppressCommit" but there are a lot of standard entry point in these CUs.

Better to set in VAR the "CommitIsSuppressed" variable on "OnBeforePostSalesDoc" / "OnBeforePostPurchaseDoc" events, so the developer can disable COMMIT for all the applications area.

I suggest to replace all COMMITs with a similar method:

![docommit](https://user-images.githubusercontent.com/17341714/46919212-4d36ec80-cfdc-11e8-9e42-9b7f3ecbf3a3.PNG)

Thank you
S.

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!

**Comment by JesperSchulz** [comment]
Thanks for the suggestion. SuppressCommit should only be used in very specific circumstances and with great care. It is meant for cases where an extension/customization is using the posting codeunits and has a specific scenario that requires multiple types of documents to be posted in a single transaction. We do not intend to make it generally available everywhere.

**Comment by JesperSchulz** [comment]
Do you have any specific commits you'd like us to suppress?

**Comment by sgiordy** [comment]
Hi @JesperSchulz 
COMMITs are intended to release database lock during posting. OK
But in a context with extensions, customization or fiscal regulatory, leaving the DB in an inconsistent state after an ERROR is a big issue.
Suppression of COMMITs should be generally available :) if not via an event, at least through a flag in General Posting Setup.
Thank you
S.

**Comment by JesperSchulz** [comment]
With the chance of earning another "dislike" :-) Here we go:

The commits are placed in the code in places where the state is known to be consistent and to roll back to that place in case of an error. Yes, commits also release db lock, but that alone is not a sufficient reason to place a commit. You wouldn’t want to commit to release lock at a point in the code where the state is not consistent.

Removing commits is not a trivial thing, it needs to be done with care. When you suppress the commit in posting you do not choose to suppress a single commit, you should suppress all or none. When you do suppress them, you take responsibility for what happens next. Depending on your scenario, you might not be able to suppress the commits, posting might simply fail without commits in certain scenarios. 
We do not want to provide a general mechanism to suppress commits. This is a topic we have debated internally many times and we have concluded that we would support this only for specific scenarios. You’ll notice the base code does not suppress commits. We provide this option only for very specific partner scenarios.

If you have such a scenario, we’d happy to discuss it with you and see if we can provide support for it in the base application, but a general, app wide or platform supported solution is not an option we are willing to consider at this time.

**Comment by sgiordy** [comment]
Hi @JesperSchulz 
I imagined that COMMITs has been placed to release database locks because, from my point of view, there is no any good reason to put a COMMIT inside a posting CU.

The issue is exactly the database consistency!

What about this piece of code:

![cu80](https://user-images.githubusercontent.com/17341714/48305617-501af380-e52e-11e8-8c24-f2a9f265665e.png)

COMMIT is between two events. How do you be sure that the database is consistent? How do you know what is attached to that events?

You have filled up CU80/90 with a lot of useless "SuppressCommit" ... it would have been enough a single event or flag in General Posting Setup. 

User and developer cannot know what other extentions can do and we need that the database remain consistent. With "SuppressCommit" I have to redefine all CU entry points all over the database, but if the user call the standard posting ... BOOM ... no suppression = inconsistent database.

Moreover in some country (such as Italy from I'm writing) there are fiscal regulatory about no. series sequence. COMMIT after take a new no. in case of an error, generates a gap in the sequence. The only way that user has to fix the issue is asking to the partner... it's a nonsense. 10 of 10 partners in Italy had always commented the COMMIT in CU80/90/5760/5763/7324... in the C/SIDE era of development.

Please consider to talk again about this issue.
Thank you.
S.

**Comment by JesperSchulz** [comment]
After further discussions I am sorry to disappoint you, but currently we do not intend to make suppressing of commits **generally** available. We would still like to handle your specific issues though. Please just create a new issue for the individual requests.
