### ISSUE TITLE
[EventRequest] Report 81 "Import Budget from Excel".OnPreReport

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16000]
Please add new event

```
trigger OnPreReport()
var
    BusUnit: Record "Business Unit";
begin
    if ToGLBudgetName = '' then
        Error(Text000);

    if SheetName = '' then
        SheetName := ExcelBuf.SelectSheetsName(ServerFileName);

    //-------------------------------OnPreReportOnBeforeSetTempDim:BEGIN
    OnPreReportOnBeforeSetTempDim(TempDim);
    //-------------------------------OnPreReportOnBeforeSetTempDim:END
    BusUnitDimCode := 'BUSINESSUNIT_TAB220';
    TempDim.Init();
    TempDim.Code := BusUnitDimCode;
    TempDim."Code Caption" := BusUnit.TableCaption;
    TempDim.Insert();
    ...
end;

[IntegrationEvent(false, false)]
local procedure OnPreReportOnBeforeSetTempDim(var TempDim: Record Dimension temporary)
begin
end
```

**Comment by Stepanenko-Vadim** [comment]
What are you trying to achieve with this event? The only thing you are changing will be overwritten by Init() call 2 lines after the event it seems.

**Comment by Jiribu73** [comment]
Our solution works with Job table in the Budgets so we need to insert this non dimensional table to the TempDim record - similar to Business Unit table.
The Init is only for the Business Unit table, we need to insert our own record.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
