### ISSUE TITLE
[Enum Request] Enum 114 "G/L Budget Matrix Dimensions"

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16010]
Please allow this enum extensible.

**Comment by AlexanderYakunin** [comment]
Which one? Where?

**Comment by Jiribu73** [comment]
"G/L Budget Matrix Dimensions" is enum object and recently is not Extensible. The issue requests to enable it.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.
