### ISSUE TITLE
Add permission to codeunit 415 "Release Purchase Document"

### ISSUE THREAD

**Issue by RaimondStokkel** [microsoft/ALAppExtensions#16012]
While the permissions for the Purchase header are present for the line this is not. Only read is needed:
Now:
Permissions = TableData "Purchase Header" = rm;

Request:
Permissions = TableData "Purchase Header" = rm,
                  TableData "Purchase Line" = r,

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
