### ISSUE TITLE
[VariableFunction] Page 113 Budget.

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16021]
Please change variable GLAccBudgetBuf as Protected
Please change local procedure GenerateColumnCaptions as Protected

**Comment by Jiribu73** [comment]
@AlexanderYakunin - can you tell when this request will be finished? All other issues regarding the budget area from my side were accepted and without this I cannot finish my modifications.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
