### ISSUE TITLE
[Extensibility bug] Customer List

### ISSUE THREAD

**Issue by Gandalf88bis** [microsoft/ALAppExtensions#16035]
Hi,

i added "County" field on my "Customer List" (page 22) page extension with visibility = false. "County" field on table 18 "Customer" has 2 different properties:

CaptionClass = '5,1,' + "Country/Region Code";
Caption = 'County';

when i try to add "County" field on "Customer List" with "personalize" feature, the field in "Add Field to Page" list has "5,1," name instead "County".

**Comment by AlexanderYakunin** [comment]
This logic defined in codeunit 344 "County CaptionClass Mgmt", please check if you country/region setup is correct.

**Comment by Gandalf88bis** [comment]
![immagine](https://user-images.githubusercontent.com/98513883/152390208-b73a4464-4f6f-4bea-bdd0-396f9050be75.png)
![immagine](https://user-images.githubusercontent.com/98513883/152390243-a18912c8-9175-424a-9092-a9ea6de5d56b.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
