### ISSUE TITLE
[Extensibility Request] Method 'GetPaymentInstructionsFromPostedInvoice' has scope 'OnPrem' and cannot be used for 'Extension' development

### ISSUE THREAD

**Issue by srenders** [microsoft/ALAppExtensions#16036]
When you clone report 1306, there's an error in its code:

 _The application object or method 'GetPaymentInstructionsFromPostedInvoice' has scope 'OnPrem' and cannot be used for 'Extension' development. For more information, see: https://docs.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-compilation-scope-overview.ALAL0296_ 

 
It could be interesting if standard reports, especially document reports don't use any OnPrem scoped procedures/objects, since those reports are cloned a lot, or at least provide a non-onprem overload?

Or does Microsoft wants us to start using scope OnPrem too? ;-)

![1306](https://user-images.githubusercontent.com/17511254/151324310-6d7b1c74-c280-411b-8c91-8a34252887c1.png)

**Comment by pri-kise** [comment]
I guess the main reason, why this procedure is OnPrem, is that this procedure shouldn't be used anymore since it is using an obsoletete field `"Payment Instructions"` of the SalesHeader.

The use of this procedure is probably mainly legacy code, that should be cleaned up.

```al
#if not CLEAN19
    [Scope('OnPrem')]
    procedure GetPaymentInstructionsFromPostedInvoice(SalesInvoiceHeader: Record "Sales Invoice Header"): Text
    var
        TypeHelper: Codeunit "Type Helper";
        InStream: InStream;
    begin
        if not SalesInvoiceHeader."Payment Instructions".HasValue then
            exit('');

        SalesInvoiceHeader."Payment Instructions".CreateInStream(InStream, TEXTENCODING::Windows);
        exit(TypeHelper.ReadAsTextWithSeparator(InStream, TypeHelper.LFSeparator));
    end;
#endif
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
