### ISSUE TITLE
[Request for External] CodeUnit 5601 "FA Insert G/L Account" - Event OnGetBalAccAfterSaveGenJnlLineFields and function InsertBufferBalAcc

### ISSUE THREAD

**Issue by VPaas2** [microsoft/ALAppExtensions#16051]
Set IncludeSender to true on event OnGetBalAccAfterSaveGenJnlLineFields:

```
  [IntegrationEvent(true, false)]     
    local procedure OnGetBalAccAfterSaveGenJnlLineFields(var ToGenJnlLine: Record "Gen. Journal Line"; FromGenJnlLine: Record "Gen. Journal Line"; var SkipInsert: Boolean)
    begin
    end;

```
and make function Global InsertBufferBalAcc so it can be accessed in event subscriber:

`procedure InsertBufferBalAcc(FAPostingType: Enum "FA Posting Group Account Type"; AllocAmount: Decimal; DeprBookCode: Code[10]; PostingGrCode: Code[20]; GlobalDim1Code: Code[20]; GlobalDim2Code: Code[20]; DimSetID: Integer; AutomaticEntry: Boolean; Correction: Boolean) `

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
