### ISSUE TITLE
SumLine in VAT Amount Line in spanish localization

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#16067]
The signature of procedure `SumLine` in `table 290 "VAT Amount Line"` differs in spanish localization from in w1.

### w1:
`procedure SumLine(LineAmount: Decimal; InvDiscAmount: Decimal; VATDifference: Decimal; AllowInvDisc: Boolean; Prepayment: Boolean)`
[source @ MSDyn365BC.Code.History ](https://github.com/StefanMaron/MSDyn365BC.Code.History/blob/26c59d60ff118e2b18e68afaf8933fc8a382d5a2/BaseApp/Source/Base%20Application/VATAmountLine.Table.al#L529)
### es:
`procedure SumLine(LineAmount: Decimal; InvDiscAmount: Decimal; PmtDiscAmount: Decimal; VATDifference: Decimal; ECDifference: Decimal; AllowInvDisc: Boolean; Prepayment: Boolean)`
[source @ MSDyn365BC.Code.History ](https://github.com/StefanMaron/MSDyn365BC.Code.History/blob/b81ed884783c09e9e7009cd806a5c47d03611971/BaseApp/Source/Base%20Application/VATAmountLine.Table.al#L685)

Localization should never have a smaller public interface than w1!
Please use overload instead of replacement.
Else anybody who uses this procedure is not able to publish his app in spain.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
