### ISSUE TITLE
[Extensibility Enhancement] Codeunit "Item Reference Management" - make FindOrSelectFromItemReferenceList global

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#16079]
Please make the ``FindOrSelectFromItemReferenceList`` function in the "Item Reference Management" codeunit global:

~~local~~ procedure FindOrSelectFromItemReferenceList(var ItemReferenceToReturn: Record "Item Reference"; ShowDialog: Boolean; ItemNo: Code[20]; ItemRefNo: Code[50]; ItemRefTypeNo: Code[30]; ItemRefType: Enum "Item Reference Type")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
