### ISSUE TITLE
[Bug] Media type field's function ExportStream() does not take into account Record.CurrentCompany() if Record.ChangeCompany() was applied

### ISSUE THREAD

**Issue by PaulFurlet** [microsoft/ALAppExtensions#16081]
**1. Describe the bug**
Field type Media does not export with ExportStream() from the record from other company if ChangeCompany was applied despite HasValue() is working correctly.

**2. To Reproduce**
1. Have at least 2 companies created
2. Have at least 1 Bank Account in each company created with Image uploaded.
3. Run code from the snippet1.

Snippet1:
```
    local procedure test()
    var
        BankAcc: Record "Bank Account";
        Comp: Record Company;
        Base64: Codeunit "Base64 Convert";
        TempBlob: Codeunit "Temp Blob";
        InS: InStream;
        OutS: OutStream;
    begin
        if Comp.FindSet() then
            repeat
                BankAcc.ChangeCompany(Comp.Name);
                if BankAcc.FindSet() then
                    repeat
                        if BankAcc.Image.HasValue() then begin //Bank Account's field Image has type Media
                            TempBlob.CreateOutStream(OutS);
                            if BankAcc.Image.ExportStream(OutS) then begin
                                TempBlob.CreateInStream(InS);
                                //this message will never be shown for non-current company
                                Message('Company %1\Bank Account %2\Image in Base64:\%3',
                                        Comp.Name,
                                        BankAcc."No.",
                                        Base64.ToBase64(InS));
                            end;
                        end;
                    until BankAcc.Next() = 0;
            until Comp.Next() = 0;
    end;
```

**3. Expected behavior**
Messages shown for every company and every bank account where Image has value.

**4. Actual behavior**
Messages shown only for current company.

**5. Versions:**

- AL Language: v8.1.540594
- Business Central: 19.2.32968.33504

P.S.
currently, there is workaround with the usage of Tenant Media table:
```
    local procedure test()
    var
        BankAcc: Record "Bank Account";
        Comp: Record Company;
        TenantMedia: Record "Tenant Media";
        Base64: Codeunit "Base64 Convert";
        InS: InStream;
    begin
        if Comp.FindSet() then
            repeat
                BankAcc.ChangeCompany(Comp.Name);
                if BankAcc.FindSet() then
                    repeat
                        if BankAcc.Image.HasValue() then begin
                            TenantMedia.Get(BankAcc.Image.MediaId);
                            TenantMedia.CalcFields(Content);
                            TenantMedia.Content.CreateInStream(InS);
                            //now message is shown for every company and every bank account within that companies
                            Message('Company %1\Bank Account %2\Image in Base64:\%3',
                                    Comp.Name,
                                    BankAcc."No.",
                                    Base64.ToBase64(InS));
                        end;
                    until BankAcc.Next() = 0;
            until Comp.Next() = 0;
    end;
```

I do not have solution for fixing this that initial code will work.

**Comment by PaulFurlet** [comment]
resubmitted to https://github.com/microsoft/AL/issues/6903

**Comment by PaulFurlet** [comment]
Sorry, jsut noticed that AL repository only handles issues to do with the compiler or VSCode development experience for AL, when current issue is about System App.
Reopening.

**Comment by dnpb** [comment]
My guess is this is more like a runtime issue than either AL or extensibility.

**Comment by PaulFurlet** [comment]
@dnpb Does not depend on runtime - tested on BC18.1 and BC19.2 - same behavior.

**Comment by JesperSchulz** [comment]
Nice catch! Let's get the issue to a team who will fix and backport it, as this repo only is for extensibility related issues in the upcoming release. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.
