### ISSUE TITLE
[Extensibility Enhancement] Table "Transaction Mode", field Code - add TableRelation + ValidateTableRelation

### ISSUE THREAD

**Issue by WJMSmit** [microsoft/ALAppExtensions#16087]
Our customers requested a Lookup on field Code of DataItem "Transaction Mode" in report "Get Proposal Entries".
We provided this by adding the following to field Code:
        field(2; "Code"; Code[20])
        {
            Caption = 'Code';
            NotBlank = true;
            **TableRelation = "Transaction Mode".Code where("Account Type" = field("Account Type"));
            ValidateTableRelation = false;**
        }

Trying to extend this, we ran into the issue that it's not possible to use property ValidateTableRelation on the TableExtension.
Besides that, it's not possible to add a coded Lookup to the TableExt.

Our request is if Microsoft could add these properties.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a suggestion for the AL compiler not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
