### ISSUE TITLE
[Extensibility-Enhancement] codeunit 90 "Purch.-Post"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#16088]
Please make function IncrAmount  global

```
procedure IncrAmount(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; var TotalPurchLine: Record "Purchase Line")
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
