### ISSUE TITLE
[EnumRequest] Table 361 "Analysis by Dim. Parameters"

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16091]
Please change "Line Dim Option" and "Column Dim Option" fields to Enum - with all related funcionalities

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
