### ISSUE TITLE
[VariableFunction] Page 554 "Analysis by Dimensions".OnBeforeDimCodeToOption

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16093]
Please change parameter Result to var

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
