### ISSUE TITLE
[Enum Request] Table 299 "Reminder Comment Line" - Field "Type"

### ISSUE THREAD

**Issue by merfai1** [microsoft/ALAppExtensions#16097]
Hi,
Could you please change field 1 (**Type**) of table 299 (**Reminder Comment Line**) from option to enum?

```AL
        field(1; Type; Option)
        {
            Caption = 'Type';
            OptionCaption = 'Reminder,Issued Reminder';
            OptionMembers = Reminder,"Issued Reminder";
        }
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
