### ISSUE TITLE
 [Event Request] Codeunit 90  -  Purch.-Post

### ISSUE THREAD

**Issue by InnovaACAdmin** [Microsoft/ALAppExtensions#161]
Hello we need some modifications on C90
1.- In standard publisher OnBeforeFinalizePosting we need to have access to global variables GenJnlLineDocNo,GenJnlLineExtDocNo,GenJnlLineDocType,SrcCode
Is possible to add all of those variablees to this standard publisher or better modify property, GlobalVarAccess to yes?

We need the same in with standard pusblisher OnAfterFinalizePostingOnBeforeCommit

2.- We need new publisher on funcion PostAssocItemJnlLine. 

OnAfterCopyFromSalesHeader(ItemJnlLine,PurchHeader);

`LOCAL [IntegrationEvent]OnAfterCopyFromSalesHeader(VAR PRecItemJournalLine : Record "Item Journal Line";PRecPurchaseHeader : Record "Purchase Header")`

**Comment by AlexanderYakunin** [comment]
#1 - ok, #2 - you already have this event in Table 83 OnAfterCopyItemJnlLineFromSalesHeader(Rec,SalesHeader);

**Comment by InnovaACAdmin** [comment]
Hello again, For my second request I can´t  use the event that you told me because I need "Purchase Header" not "Sales Header". 

I see in C80 at the end of InitAssocItemJnlLine there is this publisher
`OnAfterInitAssocItemJnlLine(ItemJnlLine,PurchOrderHeader,PurchOrderLine,SalesHeader);`

We need the same but in C90.
Could you add the same publisher (but the variables specified down) at the end of InitAssocItemJnlLine function on C90?
`OnAfterInitAssocItemJnlLine(ItemJnlLine,SalesOrderHeader,SalesOrderLine,PurchHeader);`

Thanks.

**Comment by AlexanderYakunin** [comment]
In this case name of this event is really confusing OnAfterCopyFromSalesHeader(ItemJnlLine,PurchHeader)? It should be OnAfterCopyFromPurchHeader, isn't it?
