### ISSUE TITLE
[Bug fix] codeunit 10098 - "Generate EFT" - does not support customer refunds

### ISSUE THREAD

**Issue by dkatson** [microsoft/ALAppExtensions#16106]
Hi team, 
in the codeunit 10098 - "Generate EFT" there is a code
`        if TempEFTExportWorkset.FindFirst then begin
            repeat
                LocalBankAccount.Get(TempEFTExportWorkset."Bank Account No.");
                CheckDigitCheck := not (LocalBankAccount."Export Format" in [LocalBankAccount."Export Format"::CA, LocalBankAccount."Export Format"::MX]);
                ExportPaymentsACH.CheckVendorTransitNum(TempEFTExportWorkset, TempEFTExportWorkset."Account No.", DummyVendor, VendorBankAccount, CheckDigitCheck);
                VendorBankAccount.TestField("Bank Account No.");
            until TempEFTExportWorkset.Next() = 0;
        end;
`

The problem here, it does not support customer refunds. However, the functionality further (codeunit 10094 "Export EFT (ACH)") supports customers refunds
`
    procedure ExportElectronicPayment(var TempEFTExportWorkset: Record "EFT Export Workset" temporary; PaymentAmount: Decimal; DataExchEntryNo: Integer; DataExchLineDefCode: Code[20]): Code[30]
...
            end else
                if AcctType = 'C' then begin
                    Customer.Get(AcctNo);
`

So i propose to refactor the code in the codeunit 10098 - "Generate EFT" to the next one
`
...
        if TempEFTExportWorkset.FindFirst then begin
            repeat
                LocalBankAccount.Get(TempEFTExportWorkset."Bank Account No.");
                CheckDigitCheck := not (LocalBankAccount."Export Format" in [LocalBankAccount."Export Format"::CA, LocalBankAccount."Export Format"::MX]);
                ExportPaymentsACH.CheckVendorTransitNum(TempEFTExportWorkset, TempEFTExportWorkset."Account No.", DummyVendor, VendorBankAccount, CheckDigitCheck);
                ExportPaymentsACH.CheckCustomerTransitNum(TempEFTExportWorkset, TempEFTExportWorkset."Account No.", DummyCustomer, CustomerBankAccount, CheckDigitCheck);

                CheckBankAccountNo(TempEFTExportWorkset, VendorBankAccount);
                CheckBankAccountNo(TempEFTExportWorkset, CustomerBankAccount);

            until TempEFTExportWorkset.Next() = 0;
        end;
...

    local procedure CheckBankAccountNo(var TempEFTExportWorkset: Record "EFT Export Workset" temporary; VendorBankAccount: Record "Vendor Bank Account")
    begin
        if TempEFTExportWorkset."Account Type" <> TempEFTExportWorkset."Account Type"::Vendor then
            exit;
        VendorBankAccount.TestField("Bank Account No.");
    end;

    local procedure CheckBankAccountNo(var TempEFTExportWorkset: Record "EFT Export Workset" temporary; CustomerBankAccount: Record "Customer Bank Account")
    begin
        if TempEFTExportWorkset."Account Type" <> TempEFTExportWorkset."Account Type"::Customer then
            exit;
        CustomerBankAccount.TestField("Bank Account No.");
    end;
...

codeunit 10090 "Export Payments (ACH)"
var
...
        CustomerTransitNumNotValidErr: Label 'The specified transit number %1 for customer %2  is not valid.', Comment = '%1 the transit number, %2 The Customer No.';

...
    procedure CheckVendorTransitNum(var TempEFTExportWorkset: Record "EFT Export Workset" temporary; AccountNo: Code[20]; var Vendor: Record Vendor; var VendorBankAccount: Record "Vendor Bank Account"; CheckTheCheckDigit: Boolean)
    var
        EFTRecipientBankAccountMgt: Codeunit "EFT Recipient Bank Account Mgt";
    begin
        if TempEFTExportWorkset."Account Type" <> TempEFTExportWorkset."Account Type"::Vendor then
            exit;

        CheckVendor(Vendor, AccountNo);

        EFTRecipientBankAccountMgt.GetRecipientVendorBankAccount(VendorBankAccount, TempEFTExportWorkset, AccountNo);

        CheckDigit(VendorBankAccount, CheckTheCheckDigit, Vendor."No.");
    end;

    procedure CheckCustomerTransitNum(var TempEFTExportWorkset: Record "EFT Export Workset" temporary; AccountNo: Code[20]; var Customer: Record Customer; var CustomerBankAccount: Record "Customer Bank Account"; CheckTheCheckDigit: Boolean)
    var
        EFTRecipientBankAccountMgt: Codeunit "EFT Recipient Bank Account Mgt";
    begin
        if TempEFTExportWorkset."Account Type" <> TempEFTExportWorkset."Account Type"::Customer then
            exit;

        CheckCustomer(Customer, AccountNo);

        EFTRecipientBankAccountMgt.GetRecipientCustomerBankAccount(CustomerBankAccount, TempEFTExportWorkset, AccountNo);

        CheckDigit(CustomerBankAccount, CheckTheCheckDigit, Customer."No.");
    end;

    local procedure CheckVendor(var Vendor: Record Vendor; AccountNo: Code[20])
    begin
        Vendor.Get(AccountNo);
        Vendor.TestField(Blocked, Vendor.Blocked::" ");
        Vendor.TestField("Privacy Blocked", false);
    end;

    local procedure CheckCustomer(var Customer: Record Customer; AccountNo: Code[20])
    begin
        Customer.Get(AccountNo);
        Customer.TestField(Blocked, Customer.Blocked::" ");
        Customer.TestField("Privacy Blocked", false);
    end;

    local procedure CheckDigit(var VendorBankAccount: Record "Vendor Bank Account"; CheckTheCheckDigit: Boolean; VendorNo: Code[20])
    var
        ExportPaymentsACH: Codeunit "Export Payments (ACH)";
    begin
        if CheckTheCheckDigit and (VendorBankAccount."Country/Region Code" = 'US') then
            if not ExportPaymentsACH.CheckDigit(VendorBankAccount."Transit No.") then
                Error(StrSubstNo(VendorTransitNumNotValidErr, VendorBankAccount."Transit No.", VendorNo));
    end;

    local procedure CheckDigit(var CustomerBankAccount: Record "Customer Bank Account"; CheckTheCheckDigit: Boolean; CustomerNo: Code[20])
    var
        ExportPaymentsACH: Codeunit "Export Payments (ACH)";
    begin
        if CheckTheCheckDigit and (CustomerBankAccount."Country/Region Code" = 'US') then
            if not ExportPaymentsACH.CheckDigit(CustomerBankAccount."Transit No.") then
                Error(StrSubstNo(CustomerTransitNumNotValidErr, CustomerBankAccount."Transit No.", CustomerNo));
    end;
...
`

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels and provide valid repro steps describing the business case:
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
