### ISSUE TITLE
[Event Request] Codeunit 6620 - "Copy Document Mgt." - OnBeforeCopyAsmOrderToAsmOrder

### ISSUE THREAD

**Issue by MatthiasHierteis** [microsoft/ALAppExtensions#16102]
When codeunit "Copy Document Mgt." copies Assembly Orders to the target document there is no possibility to influence or filter the assembly order lines that get copied. For a customer project we need to avoid that certain lines get copied and therefor we need a new integration event in this codeunit:

![image](https://user-images.githubusercontent.com/61226453/151563862-12a1e8b6-3c56-47f2-98b4-0153de883f37.png)

![image](https://user-images.githubusercontent.com/61226453/151563704-d9ef0efc-9aa5-4bc4-9600-d007c4046d58.png)

We would need the event from BC18 onwards.

Thanks a lot for helping us further in our project

Here is the code to copy:

Event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCopyAsmOrderToAsmOrder(var TempFromAsmHeader: Record "Assembly Header" temporary; var TempFromAsmLine: Record "Assembly Line" temporary;
       ToSalesLine: Record "Sales Line"; ToAsmHeaderDocType: Option; ToAsmHeaderDocNo: Code[20]; InclAsmHeader: Boolean)
    begin
    end;

Caller of the event in ct. CopyAsmOrderToAsmOrder:

local procedure CopyAsmOrderToAsmOrder(var TempFromAsmHeader: Record "Assembly Header" temporary; var TempFromAsmLine: Record "Assembly Line" temporary; ToSalesLine: Record "Sales Line"; ToAsmHeaderDocType: Option; ToAsmHeaderDocNo: Code[20]; InclAsmHeader: Boolean)
    var
        FromAsmHeader: Record "Assembly Header";
        ToAsmHeader: Record "Assembly Header";
        TempToAsmHeader: Record "Assembly Header" temporary;
        AssembleToOrderLink: Record "Assemble-to-Order Link";
        ToAsmLine: Record "Assembly Line";
        BasicAsmOrderCopy: Boolean;
    begin
        ***********************************        
        OnBeforeCopyAsmOrderToAsmOrder(TempFromAsmHeader, TempFromAsmLine, ToSalesLine, ToAsmHeaderDocType, ToAsmHeaderDocNo, InclAsmHeader);
        ***********************************
        if ToAsmHeaderDocType = -1 then
            exit;
        BasicAsmOrderCopy := ToAsmHeaderDocNo <> '';

**Comment by Oleg-Romashkov** [comment]
Hi,
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by MatthiasHierteis** [comment]
Code is now added to the ticket. Please appologize, as it my first even request I was not aware of that.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
