### ISSUE TITLE
[Event Request] Codeunit 5895 - Inventory Adjustment - OnBeforePostItemJnlLine

### ISSUE THREAD

**Issue by Gitulf** [microsoft/ALAppExtensions#16114]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher PostItemJnlLineto be added to Codeunit 5895 Inventory Adjustment with the following signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostItemJnlLine(var ItemJnlLine: Record "Item Journal Line"; OrigValueEntry: Record "Value Entry";NewAdjustedCost : Decimal;NewAdjustedCostACY : Decimal; SkipUpdateJobItemCost : Bool; var IsHandled: Boolean)
    begin
    end;
    
with VAR parameter ItemJnlLine.
which would be called as follows from PostItemJnlLine:

    local procedure PostItemJnlLine(ItemJnlLine: Record "Item Journal Line"; OrigValueEntry: Record "Value Entry"; NewAdjustedCost: Decimal; NewAdjustedCostACY: Decimal)
    var
        InvtPeriod: Record "Inventory Period";
        IsHandled: Boolean;        
    begin
        IsHandled := false;
        OnBeforePostItemJnlLine(ItemJnlLine, OrigValueEntry, NewAdjustedCost, NewAdjustedCostACY, SkipUpdateJobItemCost, IsHandled);
        if IsHandled then
            exit;

        with OrigValueEntry do begin
            ItemJnlLine."Item No." := "Item No.";
            ItemJnlLine."Location Code" := "Location Code";
            ItemJnlLine."Variant Code" := "Variant Code";

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
