### ISSUE TITLE
codeunit 5632 FA Jnl.-Post Line - procedures scope 

### ISSUE THREAD

**Issue by LubomirUrx** [microsoft/ALAppExtensions#16119]
Please, could you change the scope to public for these methods?

- PostReverseType
- SetResultOnDisposal
- PostGLBalAcc

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
