### ISSUE TITLE
Codeunit 5601 FA Insert G/L Account - new event 

### ISSUE THREAD

**Issue by LubomirUrx** [microsoft/ALAppExtensions#16118]
Please, add event OnAfterSetFilterOnAllocationBuffer to InsertBufferBalAcc.```

    local procedure InsertBufferBalAcc(FAPostingType: Enum "FA Posting Group Account Type"; AllocAmount: Decimal; DeprBookCode: Code[10]; PostingGrCode: Code[20]; GlobalDim1Code: Code[20]; GlobalDim2Code: Code[20]; DimSetID: Integer; AutomaticEntry: Boolean; Correction: Boolean)
    var
        SourceCodeSetup: Record "Source Code Setup";
        DimMgt: Codeunit DimensionManagement;
        GLAccNo: Code[20];
        DimensionSetIDArr: array[10] of Integer;
        IsHandled: Boolean;
        DefaultDimSource: Dictionary of [Integer, Code[20]];
    begin
        NumberOfEntries := 0;
        TotalAllocAmount := 0;
        NewAmount := 0;
        TotalPercent := 0;
        FAPostingGr.Reset();
        FAPostingGr.GetPostingGroup(PostingGrCode, DeprBookCode);
        GLAccNo := GetGLAccNoFromFAPostingGroup(FAPostingGr, FAPostingType);

        DimensionSetIDArr[1] := DimSetID;

        OnBeforeFillAllocationBuffer(
            TempFAGLPostBuf, NextEntryNo, GLEntryNo, NumberOfEntries, OrgGenJnlLine, NetDisp, GLAccNo,
            FAPostingType.AsInteger(), AllocAmount, DeprBookCode, PostingGrCode, GlobalDim1Code, GlobalDim2Code,
            DimSetID, AutomaticEntry, Correction, IsHandled);
        if IsHandled then
            exit;

        with FAAlloc do begin
            Reset();
            SetRange(Code, PostingGrCode);
            SetRange("Allocation Type", FAPostingType);
            //Start
            OnAfterSetFilterOnAllocationBuffer(var FAAlloc: Record "FA Allocation");
            // End
            if Find('-') then
                repeat
            ...
```
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetFilterOnAllocationBuffer(var FAAlloc: Record "FA Allocation")
    begin
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
