### ISSUE TITLE
[Event-Request] Table 39 "Purchase Line" - OnGetFAPostingGroupOnBeforeValidateVATProdPostingGroup

### ISSUE THREAD

**Issue by JerryTyssen** [microsoft/ALAppExtensions#16111]
Hello,

We would like to request the addition of the event OnGetFAPostingGroupOnBeforeValidateVATProdPostingGroup(Rec, IsHandled) in procedure GetFAPostingGroup() in table 39 "Purchase Line":

`local procedure GetFAPostingGroup()`
[...]
```
LocalGLAcc.CheckGLAcc;
if not ApplicationAreaMgmt.IsSalesTaxEnabled then
  LocalGLAcc.TestField("Gen. Prod. Posting Group");
"Posting Group" := FADeprBook."FA Posting Group";
"Gen. Prod. Posting Group" := LocalGLAcc."Gen. Prod. Posting Group";
"Tax Group Code" := LocalGLAcc."Tax Group Code";
        
++IsHandled := false;
++OnGetFAPostingGroupOnBeforeValidateVATProdPostingGroup(Rec, IsHandled);             
++if not IsHandled then 
  ++Validate("VAT Prod. Posting Group", LocalGLAcc."VAT Prod. Posting Group");
OnAfterGetFAPostingGroup(Rec, LocalGLAcc);
```
```
[IntegrationEvent(false, false)]
local procedure OnGetFAPostingGroupOnBeforeValidateVATProdPostingGroup(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
begin
end;
```

Background: we need to validate a different value of the field "VAT Prod. Posting Group" based on a custom setup table.

Thanks in advance,
Jerry Tyssen
Cegeka

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
