### ISSUE TITLE
[Access Request] report 790 "Calculate Inventory" - Change scope to protected 

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#16128]
Could you please move the following variables to the `var portected`?
```al
protected var
//+NEW
    SKU: Record "Stockkeeping Unit";
    QuantityOnHandBuffer: Record "Inventory Buffer" temporary;
    PostingDate: Date;
    NextDocNo: Code[20];
    ZeroQty: Boolean;
    IncludeItemWithNoTransaction: Boolean;
    ColumnDim: Text[250];
//-NEW
    HideValidationDialog: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
