### ISSUE TITLE
[Access Request] report 699 "Calculate Plan - Req. Wksh." - Change scope to protected

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#16127]
Could you please change the scope of following variables to **protected**?
```al
var protected
        SKU: Record "Stockkeeping Unit";
        ExtendedPriceEnabled: Boolean;
        PriceCalculationMethod: Enum "Price Calculation Method";
        CurrTemplateName: Code[10];
        CurrWorksheetName: Code[10];
        FromDate: Date;
        ToDate: Date;
        UseForecast: Code[10];
        ExcludeForecastBefore: Date;
        RespectPlanningParm: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
