### ISSUE TITLE
[Request for External] Table 11400 "CBG Statement" - request-for-external 

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#16126]
In table 11400 there are a lot of functions scoped as OnPrem while they are in my opinion not OnPrem specific. 
We would like to request for external for at least the following 2 functions:
CLAccountNo()
GetName()

    [Scope('OnPrem')]
    procedure CLAccountNo() CLAccNo: Text[80]
    var
        GLAccount: Record "G/L Account";
        BankAccount: Record "Bank Account";
        BankAccPostingGrp: Record "Bank Account Posting Group";
    begin
        case "Account Type" of
            "Account Type"::"G/L Account":
                CLAccNo := "Account No.";
            "Account Type"::"Bank Account":
                case false of
                    BankAccount.Get("Account No."):
                        CLAccNo := Text1000001;
                    BankAccPostingGrp.Get(BankAccount."Bank Acc. Posting Group"):
                        CLAccNo := Text1000002;
                    GLAccount.Get(BankAccPostingGrp."G/L Account No."):
                        CLAccNo := Text1000003
                    else
                        CLAccNo := GLAccount."No.";
                end;
        end;
    end;

    [Scope('OnPrem')]
    procedure GetName() Name: Text[100]
    var
        GLAccount: Record "G/L Account";
        BankAccount: Record "Bank Account";
    begin
        case "Account Type" of
            "Account Type"::"G/L Account":
                case false of
                    GLAccount.Get("Account No."):
                        Name := Text1000004;
                    else
                        Name := GLAccount.Name;
                end;
            "Account Type"::"Bank Account":
                case false of
                    BankAccount.Get("Account No."):
                        Name := Text1000004;
                    else
                        Name := BankAccount.Name;
                end;
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
