### ISSUE TITLE
New event (parameter) request

### ISSUE THREAD

**Issue by ksplinter** [Microsoft/ALAppExtensions#1612]
Hi,

In the current event

 [EventSubscriber(ObjectType::Codeunit, Codeunit::"TransferOrder-Post Shipment", 'OnAfterTransferOrderPostShipment', '', true, false)]

I need an additional parameter TransferShipmentHeader, in order to identify the record created by the posting of transfer header. Currently, I only get the unposted document, which is not enough.

**Comment by AlexanderYakunin** [comment]
This is already implemented
