### ISSUE TITLE
[Event Request] Page  9231 "Items by Location Matrix" OnAfterMATRIX_OnAfterGetRecord

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#16138]
We need a new Event Trigger in  Page 9231 "Items by Location Matrix":

    local procedure MATRIX_OnAfterGetRecord(ColumnID: Integer)
    var
        TempItem: Record Item temporary;
    begin
        TempItem.Copy(Rec);
        TempItem.SetRange("Location Filter", MatrixRecords[ColumnID].Code);
        TempItem.CalcFields(Inventory);
        MATRIX_CellData[ColumnID] := TempItem.Inventory;
        SetVisible;
        OnAfterMATRIX_OnAfterGetRecord(MATRIX_CellData[ColumnID], TempItem.Inventory,MatrixRecords[ColumnID]);
    end;

    [IntegrationEvent(true, false)]
    local procedure OnAfterMATRIX_OnAfterGetRecord(var MATRIX_CellData[ColumnID]: Decimal ;var TempItem: Record Item temporary;Location: Record Location))
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
