### ISSUE TITLE
[Event-Request] Table 39 "Purchase Line" - OnCalcVATAmountLinesOnAfterVATAmountLineInsertNewLine

### ISSUE THREAD

**Issue by JerryTyssen** [microsoft/ALAppExtensions#16135]
Hello,

We would like to request the addition of the event OnCalcVATAmountLinesOnAfterVATAmountLineInsertNewLine(PurchLine, VATAmountLine) in procedure CalcVATAmountLines()) in table 39 "Purchase Line":

`procedure CalcVATAmountLines(QtyType: Option General,Invoicing,Shipping; var PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; var VATAmountLine: Record "VAT Amount Line")`
[...]

```
if not VATAmountLine.Get(
    "VAT Identifier", "VAT Calculation Type", "Tax Group Code", "Use Tax", "Line Amount" >= 0)
++then begin
    VATAmountLine.InsertNewLine(
        "VAT Identifier", "VAT Calculation Type", "Tax Group Code", "Use Tax", "VAT %", "Line Amount" >= 0, false);
            ++OnCalcVATAmountLinesOnAfterVATAmountLineInsertNewLine(PurchLine, VATAmountLine);
++end;
```

```
[IntegrationEvent(false, false)]
local procedure OnCalcVATAmountLinesOnAfterVATAmountLineInsertNewLine(var PurchLine: Record "Purchase Line"; var VATAmountLine: Record "VAT Amount Line")
begin
end;

```

Background: we have a custom field in the "VAT Amount Line" table which also needs to be filled. The procedure InsertNewLine is called more than once, so a new event in this procedure is not sufficient for us.

Thanks in advance,
Jerry Tyssen
Cegeka

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
