### ISSUE TITLE
[Event Request] codeunit 396 NoSeriesManagement

### ISSUE THREAD

**Issue by tendreffy** [microsoft/ALAppExtensions#16134]
Hi,
Please add an event OnAfterTestManual to procedure TestManual.

    procedure TestManual(DefaultNoSeriesCode: Code[20])
    begin

        if DefaultNoSeriesCode <> '' then begin
            NoSeries.Get(DefaultNoSeriesCode);
            if not NoSeries."Manual Nos." then
                Error(
                  Text000 +
                  Text001,
                  NoSeries.FieldCaption("Manual Nos."), NoSeries.TableCaption, NoSeries.Code);
        end;
        //New Event begin
        OnAfterTestManual(DefaultNoSeriesCode);
        //New Event end
    end;

new event:

    [IntegrationEvent(false, false)]
    local procedure OnAfterTestManual(DefaultNoSeriesCode: Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
