### ISSUE TITLE
[Event Request] Table 112 "Sales Invoice Header"

### ISSUE THREAD

**Issue by OlWaechter** [microsoft/ALAppExtensions#16143]
Please add  "OnBeforeDoPrintDocumentToAttachment" Event in the following procedure

```
    local procedure DoPrintToDocumentAttachment(SalesInvoiceHeader: Record "Sales Invoice Header"; ShowNotificationAction: Boolean)
    var
        ReportSelections: Record "Report Selections";
    begin
        SalesInvoiceHeader.SetRecFilter();
        ReportSelections.SaveAsDocumentAttachment(
            ReportSelections.Usage::"S.Invoice".AsInteger(), SalesInvoiceHeader, SalesInvoiceHeader."No.", SalesInvoiceHeader."Bill-to Customer No.", ShowNotificationAction);
    end;
```
We need to change the used Report. Just like in functions "PrintRecords" and "SendProfile"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
