### ISSUE TITLE
[request-for-external] Make EmailMessageImpl.UpdateMessage available through EmailMessage

### ISSUE THREAD

**Issue by michvllni** [microsoft/ALAppExtensions#16149]
codeunit 8905 "Email Message Impl." already has a procedure
```
procedure UpdateMessage(ToRecipients: List of [Text]; Subject: Text; Body: Text; HtmlFormatted: Boolean; CCRecipients: List of [Text]; BCCRecipients: List of [Text])
    begin
        SetBody(Body);
        SetSubject(Subject);
        SetBodyHTMLFormatted(HtmlFormatted);
        Modify();

        SetRecipients(Enum::"Email Recipient Type"::"To", ToRecipients);
        SetRecipients(Enum::"Email Recipient Type"::Cc, CCRecipients);
        SetRecipients(Enum::"Email Recipient Type"::Bcc, BCCRecipients);
    end;
```

This procedure is currently not passed on to codeunit 8904 "Email Message"

Would it be possible to pass this procedure to codeunit 8904 "Email Message" to make it available for extensions?

Ideally, also create overloads to match the current overloads of the Create function:
```
procedure UpdateMessage(EmailMessage: Codeunit "Email Message Impl.")
procedure UpdateMessage(ToRecipients: Text; Subject: Text; Body: Text; HtmlFormatted: Boolean)
procedure UpdateMessage(Recipients: List of [Text]; Subject: Text; Body: Text; HtmlFormatted: Boolean)
procedure UpdateMessage(Recipients: List of [Text]; Subject: Text; Body: Text; HtmlFormatted: Boolean; CCRecipients: List of [Text]; BCCRecipients: List of [Text])
```

Thank you!

**Comment by mazhelez** [comment]
Hey @michvllni 

_Email Message_ was left ummutable after creation for a reason. That reason is to avoid meddling with before sending.

What is the scenario you are after?

**Comment by michvllni** [comment]
The way it was back with SMTP Mail was a little more convenient.

When I dynamically generate an email now i can't simultaniously append to the body and add attachments for example.

Instead I have to do two loops: One to create the body and another one to add the attachments.

It would be nice if it was possible to update the parameters of the mail as described

**Comment by michvllni** [comment]
Loop 1: Build the body
Loop 2: Append the attachments

Might be a bit specific but in that case a note for each attachment would be added to the body

Setters would work for me as well

**Comment by mazhelez** [comment]
I think I understand now, thanks for clarifying.

If setters would suffice, how do you feel about contributing a PR to the repo?
