### ISSUE TITLE
[request-for-external] table 179 "Reversal Entry"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#16146]
Please make the following functions protected : 

InsertFromCustLedgEntry
InsertFromVendLedgEntry
InsertFromEmplLedgerEntry
InsertFromBankAccLedgEntry
InsertFromFALedgEntry
InsertFromMaintenanceLedgEntry
InsertFromVATEntry
InsertFromGLEntry

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
