### ISSUE TITLE
[Event Request] Codeunit 7000003 "BG/PO-Post and Print"

### ISSUE THREAD

**Issue by KingDiamondXT** [microsoft/ALAppExtensions#16153]
Please add these events:

    procedure PayablePostAndPrint(PmtOrd: Record "Payment Order")
    var
        PostedPmtOrd: Record "Posted Payment Order";
    begin
        //NEW CODE
        OnBeforePayablePostAndPrint(PmtOrd, IsHandled);
        if IsHandled then
            exit; 
        //NEW CODE

        PmtOrd.SetRecFilter();
        REPORT.RunModal(REPORT::"Post Payment Order", false, false, PmtOrd);

        Commit();

        if PostedPmtOrd.Get(PmtOrd."No.") then begin
            PostedPmtOrd.SetRecFilter();
            CarteraReportSelection.Reset();
            CarteraReportSelection.SetRange(Usage, CarteraReportSelection.Usage::"Posted Payment Order");
            CarteraReportSelection.Find('-');
            repeat
                CarteraReportSelection.TestField("Report ID");
                REPORT.Run(CarteraReportSelection."Report ID", false, false, PostedPmtOrd);
            until CarteraReportSelection.Next() = 0;
        end;

        //NEW CODE
        OnAfterPayablePostAndPrint(PmtOrd);
        //NEW CODE
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforePayablePostAndPrint(var PaymentOrder: Record "Payment Order"; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterPayablePostAndPrint(var PaymentOrder: Record "Payment Order")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
