### ISSUE TITLE
Possibility to start Manager Time Sheet by Job with a specified starting date/skip completely approved weeks

### ISSUE THREAD

**Issue by pieter-kok** [microsoft/ALAppExtensions#16155]
We are currently in the process of changing our extension that uses the Time Sheets module to also support the new time sheet experience, that we now can enable through feature management. A lot of our customizations seem to be not necessary anymore, so that is a good thing. I'm talking mainly about functionality we created for supporting time sheets on mobile devices and approvers per line.

In our process we had a page which contained all Time Sheet Lines that had to be approved per approver, without a filter on the week. Approvers were already determined per line in our solution, which was the reason we created the page in the first place. We are thinking about obsoleting this custom page and replacing it by the Manager Time Sheet by Job page. We already removed the filter on Type = Job and use the events regarding filtering to use all types when approving, rejecting, etc. 

The only difference between our page and page Page 954 "Manager Time Sheet by Job" is the fact that it's scope is per week.
In our own solution we showed the lines of all weeks. We think we can overcome this by creating a page which sums all lines that need to be approved per week for an approver. This way the approver doesn't have to search for a week with something to approve. From this page we want to start the Manager Time Sheet by Job page on the selected week. 

So: what we are currently missing is a way to edit the Starting Date that is used when the Manager Time Sheet by Job page is initially opened. Also we would like to skip weeks that have nothing left to approve when changing the period. Therefore I think that we need some kind of modification in the base app to be able to extend the functionality of the page as described. I'm hoping on your cooperation to give us some more control in this page through extensibility.

The following is my suggestion for changes on Page 954 "Manager Time Sheet by Job", but I'm open to other solutions that enable us to do as described.

```
//NEW >>
var
    InitialStartingDateBase: Date;
//NEW <<

local procedure FindPeriod(Which: Option Initial,Previous,Next)
//NEW >>
var
        IsHandled: Boolean;
//NEW <<
begin
    //NEW >>
    OnBeforeFindPeriod(Rec,Which,InitialStartingDateBase,StartingDate,IsHandled);

    if not IsHandled then begin
        if InitialStartingDateBase = 0D then
            InitialStartingDateBase := Workdate();                
    //NEW <<
        ResourcesSetup.Get();
        case Which of
            Which::Initial:
                //CHANGED >>
                //if Date2DWY(WorkDate, 1) = ResourcesSetup."Time Sheet First Weekday" + 1 then
                //    StartingDate := WorkDate
                //else
                //    StartingDate := CalcDate(StrSubstNo('<WD%1-7D>', ResourcesSetup."Time Sheet First Weekday" + 1), WorkDate);
                if Date2DWY(InitialStartingDateBase, 1) = ResourcesSetup."Time Sheet First Weekday" + 1 then
                    StartingDate := InitialStartingDateBase
                else
                    StartingDate := CalcDate(StrSubstNo('<WD%1-7D>', ResourcesSetup."Time Sheet First Weekday" + 1), InitialStartingDateBase);
                //CHANGED <<
            Which::Previous:
                StartingDate := CalcDate('<-1W>', StartingDate);
            Which::Next:
                StartingDate := CalcDate('<1W>', StartingDate);
        end;
    //NEW >>
    end;
    //NEW <<
    EndingDate := CalcDate('<1W>', StartingDate) - 1;
    FilterGroup(2);
    SetRange("Time Sheet Starting Date", StartingDate, EndingDate);
    SetRange("Approver ID", UserId);
    FilterGroup(0);
    SetColumns;
    CurrPage.Update(false);
end;

//NEW >>
procedure SetInitialStartingDateBase(StartingDateBase: Date)
begin
    InitialStartingDateBase := StartingDateBase;
end;

[IntegrationEvent(false,false)]
local procedure OnBeforeFindPeriod(var TimeSheetLine: Record "Time Sheet Line"; Which: Option Initial,Previous,Next;InitialStartingDateBase: Date; var ResultStartingDate: Date; var IsHandled: Boolean)
begin
end;
//NEW <<
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
