### ISSUE TITLE
[Event Request] codeunit 5870 "Calculate BOM Tree" -  OnBeforeGenerateTreeForItemLocal

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#16159]
Please could we have OnBeforeGenerateTreeForItemLocal event added to allow the updating of Prod. Bom No. and Routing No. on the ParentItem before any calculations begin.

the existing OnBeforeFilterBOMBuffer event is too late as it is after the if HasBOM or ("Routing No." <> '') then begin statement

    local procedure GenerateTreeForItemLocal
    begin
        OnBeforeGenerateTreeForItemLocal(ParentItem, DemandDate, TreeType);

        with ParentItem do begin
            InitVars;
        ......

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGenerateTreeForItemLocal(var ParentItem: Record Item; DemandDate: Date; TreeType: Option);
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
