### ISSUE TITLE
[Event Request] Codeunit 7000000 CarteraManagement

### ISSUE THREAD

**Issue by KingDiamondXT** [microsoft/ALAppExtensions#16151]
Please add these two events:

    procedure RemoveReceivableDocs(var CarteraDoc2: Record "Cartera Doc.")
    var
        BillGr: Record "Bill Group";
        CustLedgEntry: Record "Cust. Ledger Entry";
    begin
        with CarteraDoc2 do
            if Find('-') then begin
                BillGr.Get("Bill Gr./Pmt. Order No.");
                //NEW CODE
                OnBeforeCheckNoPrintedRemoveReceivableDocs(BillGr,IsHandled);
                if not IsHandled then
                //NEW CODE
                    if BillGr."No. Printed" <> 0 then
                         if not Confirm(Text1100001, false) then
                             exit;
                BillGr."No. Printed" := 0;
                repeat
                    RemoveReceivableError(CarteraDoc2);
                    "Bill Gr./Pmt. Order No." := '';
                    Modify;
                    if CustLedgEntry.Get("Entry No.") then begin
                        CustLedgEntry."Document Situation" := CustLedgEntry."Document Situation"::Cartera;
                        CustLedgEntry.Modify();
                    end;
                    OnAfterRemoveReceivableDocs(CarteraDoc2, BillGr);
                until Next() = 0;
                BillGr.Modify();
            end;
    end;

    procedure RemovePayableDocs(var CarteraDoc2: Record "Cartera Doc.")
    var
        PaymentOrder: Record "Payment Order";
        VendLedgEntry: Record "Vendor Ledger Entry";
    begin
        with CarteraDoc2 do
            if Find('-') then begin
                PaymentOrder.Get("Bill Gr./Pmt. Order No.");
                //NEW CODE
                OnBeforeCheckNoPrintedRemovePayableDocs(PaymentOrder,IsHandled);
                if not IsHandled then
                //NEW CODE
                    if PaymentOrder."No. Printed" <> 0 then
                        if not Confirm(Text1100004, false) then
                            exit;
                PaymentOrder."No. Printed" := 0;
                repeat
                    RemovePayableError(CarteraDoc2);
                    "Bill Gr./Pmt. Order No." := '';
                    Modify;
                    if VendLedgEntry.Get("Entry No.") then begin
                        VendLedgEntry."Document Situation" := VendLedgEntry."Document Situation"::Cartera;
                        VendLedgEntry.Modify();
                    end;
                    OnAfterRemovePayableDocs(CarteraDoc2, PaymentOrder);
                until Next() = 0;
                PaymentOrder.Modify();
            end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckNoPrintedRemoveReceivableDocs(var BillGroup: Record "Bill Group"; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckNoPrintedRemovePayableDocs(var PaymentOrder: Record "Payment Order"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
