### ISSUE TITLE
[Request-For-External] Page 515 "Item Avail. by Location Lines" - SetItemFilter

### ISSUE THREAD

**Issue by percova** [microsoft/ALAppExtensions#16166]
Hi, could you please change the local **SetItemFilter** procedure of page 515 (**Item Avail. by Location Lines**) to a **global** one?

```AL
    procedure SetItemFilter()
    begin
        if AmountType = AmountType::"Net Change" then
            Item.SetRange("Date Filter", PeriodStart, PeriodEnd)
        else
            Item.SetRange("Date Filter", 0D, PeriodEnd);
        LocationCode := Code;
        Item.SetRange("Location Filter", Code);

        OnAfterSetItemFilter(Item, PeriodStart, PeriodEnd);
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
