### ISSUE TITLE
[Request-For-External] Page 515 "Item Avail. by Location Lines" - AmountType, PeriodStart, PeriodEnd

### ISSUE THREAD

**Issue by percova** [microsoft/ALAppExtensions#16168]
Hi, could you please change the global **AmountType**, **PeriodStart**, **PeriodEnd** variable's protection level on page 515 (**Item Avail. by Location Lines**) to a **protected**?
```AL
    protected var
        AmountType: Enum "Analysis Amount Type";
        PeriodStart: Date;
        PeriodEnd: Date;
```
Thanks!
#16166

**Comment by AlexanderYakunin** [comment]
Already done
