### ISSUE TITLE
Wrong value in [Last Login] when using "User Settings".GetUserSettings()

### ISSUE THREAD

**Issue by RodrigoPuelma** [microsoft/ALAppExtensions#16167]
**1. Describe the bug**
The field "Last Login" on the record "User Settings" contains the current user's value and not the requested user's value. This is because the field is set in the procedure GetUserSettings in the codeunit "User Settings Impl." by using the procedure GetPenultimateLoginDateTime in the codeunit "User Login Time Tracker". Codeunit "User Login Time Tracker" only works with the current "User Login" record.

**2. To Reproduce**
    local procedure GetUserSetting()
    var
        UserSetting: Record "User Settings";
        UserSettings: Codeunit "User Settings";
        AnUserSecurityIdOtherThanTheCurrentUser: Guid;
    begin
            UserSettings.GetUserSettings(AnUserSecurityIdOtherThanTheCurrentUser, UserSetting);
            Message(Format(UserSetting."Last Login"));
        end;
    end;

**3. Expected behavior**
I would expect the field value of "Last Login" in the "User Settings" record to be the log in datetime of the user of the record and not the last log in date of the current user logged in.

**4. Actual behavior**

**5. Versions:**

- AL Language: 8.3.570094
- Visual Studio Code: 1.63.2
- Business Central: 19.3
- List of Visual Studio Code extensions that you have installed:

**Comment by JesperSchulz** [comment]
Thank you for reporting a bug! Strictly speaking, this issue does not qualify to be logged as an issue here on GitHub though, as GitHub is for extensibility issues only. But as this isn't a time critical issue, we'll make an exception and accept this bug report here :-) The reason for why we normally don't accept product defect reports here on GitHub, is that we don't have the right support channel attached. There are no SLAs and issue won't get addressed in all supported versions of Business Central. If you find product defects which affect customers and/or persist data, please log the bug through our support channels. Thanks you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
