### ISSUE TITLE
[Event Request] codeunit 5870 "Calculate BOM Tree" - OnGenerateItemSubTreeAfterGetParentItem

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#16160]
Please could you add OnGenerateItemSubTreeAfterGetParentItem event to allow the Parent Item Prod. BOM No. and Routing to be changed before the calculations begin.

    local procedure GenerateItemSubTree(ItemNo: Code[20]; var BOMBuffer: Record "BOM Buffer"): Boolean
    begin
        with BOMBuffer do begin
            ParentItem.Get(ItemNo);
            OnGenerateItemSubTreeAfterGetParentItem(ParentItem);

            if TempItem.Get(ItemNo) then begin
                "Is Leaf" := false;
                Modify(true);
                exit(false);
            end;
            .......

    [IntegrationEvent(false, false)]
    local procedure OnGenerateItemSubTreeAfterGetParentItem(var ParentItem: Record Item);
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
