### ISSUE TITLE
[request-for-external] codeunit 17 "Gen. Jnl.-Post Reverse"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#16179]
Please make function CheckDimComb global

```
procedure CheckDimComb(EntryNo: Integer; DimSetID: Integer; TableID1: Integer; AccNo1: Code[20]; TableID2: Integer; AccNo2: Code[20])
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
