### ISSUE TITLE
[Event Request] Codeunit 5856 "TransferOrder-Post Transfer" - all event triggers missing

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#16171]
In case of InvtSetup."Direct Transfer Posting"::"Receipt and Shipment" the codeunits TransferPostShipment and TransferPostReceipt are executed with all necessary event triggers.

In case of InvtSetup."Direct Transfer Posting"::"Direct Transfer" the codeunit  5856 "TransferOrder-Post Transfer" is executed, creates records in table 5856 "Direct Trans. Header" and 5857 "Direct Trans. Line" and posts ItemJnlLine similar to the codeunits TransferPostShipment and TransferPostReceipt.

In this codeunit  5856 "TransferOrder-Post Transfer" all event triggers are missing.

OnAfterCreateItemJnlLine
OnBeforePostItemJournalLine
OnAfterInsertDirectTransHeader
OnAfterInsertDirectTransLine
OnAfterInsertShptEntryRelation
OnBeforeTransferTracking
OnPostWhseJnlLineOnBeforeSplitWhseJnlLine
OnBeforeDeleteOneTransferHeader

Please add all necessary triggers to codeunit 5856, so in case of  InvtSetup."Direct Transfer Posting"::"Direct Transfer" we can use the tables and routines according to our processes.

**Comment by Stepanenko-Vadim** [comment]
I've tried to accommodate this request and 'guess' from names/context and the other code units where most of these events should be and which parameters you want in those, but in the future please create 1 request per event and specify where exactly you need it and which parameters you expect.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
