### ISSUE TITLE
[Event Change] Page 343 CheckCreditLimit.Page.al OnShowWarningOnBeforeExitValue

### ISSUE THREAD

**Issue by nickgoddard777** [microsoft/ALAppExtensions#16178]
Can the fields Heading, SecondHeading, and NotificationID be passed through on Event OnShowWarningOnBeforeExitValue.  These would need to be Passed By Value.

The reason for this change is to allow the headings and notificationid to be overridden in custom code.

There are 2 alternatives to this, either have Setter Procedures which are available globally for the three variables.  Or allow the three variables to be accessible in a page extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
