### ISSUE TITLE
[Request-For-External] Table 210 "Job Journal Line" - JobJnlTemplate, DimMgt

### ISSUE THREAD

**Issue by tjbakker** [microsoft/ALAppExtensions#16189]
Hi, could you please change the following global variables in table 210 to protected: 
```
 protected var
        JobJnlTemplate: Record "Job Journal Template";
        DimMgt: Codeunit DimensionManagement;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
