### ISSUE TITLE
[Event Request] codeunit 1381 "Customer Templ. Mgt." - OnAfterUpdateFromTemplate and OnAfterUpdateMultipleFromTemplate

### ISSUE THREAD

**Issue by gtrennert** [microsoft/ALAppExtensions#16181]
Hi, would it be possible to get 
- an OnAfterUpdateFromTemplate event and 
- an and OnAfterUpdateMultipleFromTemplate event 
in codeunit 1381 ("Customer Templ. Mgt.") ?

We need this to Show a message tu the user after the template has been applied to one or more Customers.

Here are draft from what we like to obtain :
    local procedure UpdateFromTemplate(var Customer: Record Customer; var IsHandled: Boolean)
    var
        CustomerTempl: Record "Customer Templ.";
    begin
        IsHandled := false;
        OnBeforeUpdateFromTemplate(Customer, IsHandled);
        if IsHandled then
            exit;

        if not CanBeUpdatedFromTemplate(CustomerTempl, IsHandled) then
            exit;

        ApplyCustomerTemplate(Customer, CustomerTempl);
        OnAfterUpdateFromTemplate(Customer, CustomerTempl);
    end;

    local procedure UpdateMultipleFromTemplate(var Customer: Record Customer; var IsHandled: Boolean)
    var
        CustomerTempl: Record "Customer Templ.";
    begin
        IsHandled := false;
        OnBeforeUpdateMultipleFromTemplate(Customer, IsHandled);
        if IsHandled then
            exit;

        if not CanBeUpdatedFromTemplate(CustomerTempl, IsHandled) then
            exit;

        if Customer.FindSet() then
            repeat
                ApplyCustomerTemplate(Customer, CustomerTempl);
            until Customer.Next() = 0;
        OnAfterUpdateMultipleFromTemplate(Customer, CustomerTempl);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
