### ISSUE TITLE
API for Purchase Credit Memos

### ISSUE THREAD

**Issue by Delpixe** [microsoft/ALAppExtensions#16180]
Hello,

I am working for a customer API, and they need an API for the Purchase Credit Memos:
Right now the only invoice/cr.memo API's I have found are those:

Sales:
salesInvoices | Sales Invoice Entity Aggregate
salesInvoiceLines | Sales Invoice Line Aggregate
salesCreditMemos | Sales Cr. Memo Entity Buffer
salesCreditMemoLines | Sales Invoice Line Aggregate

Purchase:
purchaseInvoices | Purch. Inv. Entity Aggregate
purchaseInvoiceLines | Purch. Inv. Line Aggregate

I couldn't find the PurchaseCrMemos API.
am I missing something?

Thanks in advance,
  Mattia

**Comment by onbuyuka** [comment]
We currently do not have Purchase Credit Memo API endpoint. This is in our backlog, however to get more attention to it please log an idea at [Microsoft Idea](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central) or vote on existing an idea if there's any.

In the meantime you can always develop your custom APIs: [Developing a Custom API](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-custom-api)
