### ISSUE TITLE
Document Attachment Details list page - should not drilldown when in lookup mode

### ISSUE THREAD

**Issue by quadfin** [microsoft/ALAppExtensions#16203]
If the Document Attachment Details page (a list page) is opened in Lookup mode and the Attachment column (a drilldown field) is clicked then the dialog either exports the attachment (if it exists) or prompts for file selection then imports.

In Lookup mode it should not take action - it should select the record then dismiss the dialog with result Action::LookupOK.

**Comment by Oleg-Romashkov** [comment]
Hi,
In current state we cannot update OnLookup trigger as you requested - there is no way to close page with Action::LookupOK.

You can make a new page for lookup purpose or, if you need the existing one then you can make a simple extension:

```
pageextension 50199 MyExtension extends "Document Attachment Details"
{
    layout
    {
        addbefore(Name)
        {
            field(ID_ext; ID)
            {
                Visible = LookupModeActive;
                ToolTip = 'Specifies the ID of the attachment.';
            }
        }
    }

    trigger OnOpenPage()
    begin
        LookupModeActive := CurrPage.LookupMode();
    end;

    var
        LookupModeActive: Boolean;
}
```
Having field "ID" on the first place allows to use it for selecting records in the lookup mode:
![image](https://user-images.githubusercontent.com/82887855/154192563-f8d58cd8-5253-4abc-8ec8-503a8eaa5cf8.png)
