### ISSUE TITLE
[request-for-external] table 9650 "Custom Report Layout"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#16208]
Please make function CanModify external

```
procedure CanModify(): Boolean
 var
        User: Record User;
    begin
        if CurrentTransactionType() = TransactionType::Report then
            exit(false);
        if not WritePermission then
            exit(false);
        if not User.Get(UserSecurityId) then
            exit(true);
        exit(User."License Type" <> User."License Type"::"Limited User");
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
