### ISSUE TITLE
Add permissions to Table 5051 "Contact Alt. Address"

### ISSUE THREAD

**Issue by EvaCegeka** [microsoft/ALAppExtensions#16218]
Hello,

We would like to request for the following Permissions to be added to table 5051 "Contact Alt. Address" for better protection of the data that is altered via several triggers in tables 5050 Contact and 5052 "Contact Alt. Addr. Date Range".

 Permissions = TableData Contact = rm,
                        TableData "Contact Alt. Addr. Date Range" = rd;

Thank you in advance for your consideration.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
