### ISSUE TITLE
[Event Request] Table 77 "Report Selections" - OnAfterSaveReportAsPDF

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#16214]
We need a new event in table 77 "Report Selections", named

**OnAfterSaveReportAsPDF**

[IntegrationEvent(false, false)]
**local procedure OnAfterSaveReportAsPDF(ReportID: Integer; RecordVariant: Variant; LayoutCode: Code[20]; var IsHandled: Boolean; FilePath: Text[250])**
begin
end;

called from:
**local procedure SaveReportAsPDF(ReportID: Integer; RecordVariant: Variant; LayoutCode: Code[20]; ReportUsage: Integer) FilePath: Text[250]**
    var
        ReportLayoutSelection: Record "Report Layout Selection";
        FileMgt: Codeunit "File Management";
        IsHandled: Boolean;
    begin
        OnBeforeSetReportLayout(RecordVariant, ReportUsage);
        FilePath := CopyStr(FileMgt.ServerTempFileName('pdf'), 1, 250);

ReportLayoutSelection.SetTempLayoutSelected(LayoutCode);
        OnBeforeSaveReportAsPDF(ReportID, RecordVariant, LayoutCode, IsHandled, FilePath);
        if not IsHandled then
            REPORT.SaveAsPdf(ReportID, FilePath, RecordVariant);
        **//INIT INSERT
        OnAfterSaveReportAsPDF(ReportID, RecordVariant, LayoutCode, IsHandled, FilePath);
	//END INSERT**
        ReportLayoutSelection.SetTempLayoutSelected('');

Commit();
    end;

**Comment by Stepanenko-Vadim** [comment]
There already is such an event for at least last couple of majors, the code you've pasted seems like a pretty old version of those procedures (they've been refactored since), please check if you are using latest-ish codebase for event requests.
