### ISSUE TITLE
event parameter request - codeunit 368 "Format Document" - SetSalesPurchaseLine() - OnAfterSetSalesPurchaseLine() - CommentLine: Boolean

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#16215]
Please add `CommentLine` as an argument to subscribers of `OnAfterSetSalesPurchaseLine()`. We can instead check `if FormattedWhatever = ''` and avoid applying our own formatting if so, but it would be cleaner and more self-explanatory to just get the `CommentLine` as already determined by yourselves ;-)

![image](https://user-images.githubusercontent.com/63455896/152963882-933eac84-4479-4744-b734-384d0280f502.png)

So:
```al
        OnAfterSetSalesPurchaseLine(
          CommentLine, Quantity, UnitPrice, VATPercentage, LineAmount, CurrencyCode,
          FormattedQuantity, FormattedUnitPrice, FormattedVATPercentage, FormattedLineAmount);
```
and
```al
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetSalesPurchaseLine(CommentLine: Boolean; Quantity: Decimal; UnitPrice: Decimal; VATPercentage: Decimal; LineAmount: Decimal; CurrencyCode: Code[10]; var FormattedQuantity: Text; var FormattedUnitPrice: Text; var FormattedVATPercentage: Text; var FormattedLineAmount: Text)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
