### ISSUE TITLE
[Event Request] table 39 "Purchase Line" - OnValidateDescriptionOnBeforeCannotFindDescrError

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#16224]
Can you add event OnValidateDescriptionOnBeforeCannotFindDescrError to purchase line table in the OnValidate trigger for description?
The same way it is done in sales line table.

```
                //>>>>>>>>>>>>>>>>>>
                IsHandled := false;
                OnValidateDescriptionOnBeforeCannotFindDescrError(Rec, xRec, IsHandled);
                if not IsHandled then
                //<<<<<<<<<<<<<<<<<<
                    if ("No." = '') and GuiAllowed then
                        if ApplicationAreaMgmtFacade.IsFoundationEnabled then
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
