### ISSUE TITLE
add new event OnRunOnAfterUpdatePurchaseOrderLinesFromCancelledInvoice to "Correct Posted Purch. Invoice" codeunit

### ISSUE THREAD

**Issue by tyurm** [microsoft/ALAppExtensions#16223]
Hello,

Could you please add new event OnRunOnAfterUpdatePurchaseOrderLinesFromCancelledInvoice to codeunit 1313 "Correct Posted Purch. Invoice" OnRun:

```
CODEUNIT.Run(CODEUNIT::"Purch.-Post", PurchaseHeader);
SetTrackInfoForCancellation(Rec);
if RedoApplications then
    ItemJnlPostLine.RedoApplications;
UpdatePurchaseOrderLinesFromCancelledInvoice("No.");
//New Event >>
OnRunOnAfterUpdatePurchaseOrderLinesFromCancelledInvoice(Rec, PurchaseHeader);
//New Event <<
Commit();
```

Event Declaration:
```
[IntegrationEvent(false, false)]
local procedure OnRunOnAfterUpdatePurchaseOrderLinesFromCancelledInvoice(var Rec: Record "Purch. Inv. Header"; var PurchaseHeader: Record "Purchase Header")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
