### ISSUE TITLE
[Event Request] Table 111 "Sales Shipment Line" - OnAfterInsertInvLineFromShptLine

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#16222]
Hello
Can I get NextLineNo as VAR parameter in  OnAfterInsertInvLineFromShptLine ?
```
 [IntegrationEvent(false, false)]
    local procedure OnAfterInsertInvLineFromShptLine(var SalesLine: Record "Sales Line"; SalesOrderLine: Record "Sales Line";VAR NextLineNo: Integer; SalesShipmentLine: Record "Sales Shipment Line")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
