### ISSUE TITLE
[EventRequest] Report 82 "Export Budget to Excel".OnBeforeEnterRangeForDimension

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16233]
Regarding issue #16009 add parameter i to the event (as it has been requested):

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeEnterRangeForDimension(i: Integer; var DimensionRange: array[2, 8] of Integer; var BusUnit: Record "Business Unit"; var DimValue: Record "Dimension Value"; var RowNo: Integer; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
