### ISSUE TITLE
[Event Request] Page 9203 "Budget Matrix".OnAfterSetDimFilters

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16237]
Related to the issue #16029 please add parameter DimType to the event

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetDimFilters(var TheGLAccBudgetBuffer: Record "G/L Acc. Budget Buffer"; DimType: Enum "G/L Budget Matrix Dimensions")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
