### ISSUE TITLE
[request-for-external] table 5606 "FA Posting Group"

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#16230]
We would like to request for external for function CheckGLAcc on the FA Posting Group table.
We would like to also use the function in a table extension to check the GLAccount in case additional Accounts are created inside a tableextension for the FA Posting Group. 
When validating these additional GLAccounts we would like to also check them based on the standard function.

From:
`    local procedure CheckGLAcc(AccNo: Code[20]; DirectPosting: Boolean)`
To:
`    protected procedure CheckGLAcc(AccNo: Code[20]; DirectPosting: Boolean)`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
