### ISSUE TITLE
[EventRequest] Page 113 Budget.OnAfterGenerateColumnCaptions

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16236]
Regarding issue #16014 please add parameter ShowColumnName to the event

    [IntegrationEvent(false, false)]
    local procedure OnAfterGenerateColumnCaptions(ColumnDimCode: Text[30]; StepType: Enum "Matrix Page Step Type"; var PrimKeyFirstCaptionInCu: Text; var CaptionSet: array[32] of Text[80]; var CaptionRange: Text; var CurrentNoOfColumns: Integer; MatrixRecords: array[32] of Record "Dimension Code Buffer"; ShowColumnName: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
