### ISSUE TITLE
[EventRequest] Report 82 "Export Budget to Excel".OnBeforeGetDimValueCode

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16232]
Regarding issue #16007 I need to add parameter "GLBudgetEntry" to the event OnBeforeGetDimValueCode

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetDimValueCode(GLBudgetEntry: Record "G/L Budget Entry"; DimCode: Code[20]; var Result: Code[20]; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
