### ISSUE TITLE
[Event Request] Page 9203 "Budget Matrix".OnBudgetDrillDownOnBeforePageRun

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16238]
Related to the issue #16030 please change parameter GLAccBudgetBuffer to var

    [IntegrationEvent(false, false)]
    local procedure OnBudgetDrillDownOnBeforePageRun(var GLAccBudgetBuffer: Record "G/L Acc. Budget Buffer"; var GLBudgetEntry: Record "G/L Budget Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
