### ISSUE TITLE
[EventRequest] Report 81 "Import Budget from Excel".OnAfterSetBudgetDimFilter

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16235]
Regarding issue #16004 please add parameter DimCode2 to the event

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetBudgetDimFilter(var GLBudgetEntry: Record "G/L Budget Entry"; DimValCode2: Code[20]; DimCode2: Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
