### ISSUE TITLE
[VariableFunction] Page 554 "Analysis by Dimensions"

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16239]
Related to the issue #16095 please change local procedure Create CaptionSet to protect - other demands from the issue were fulfilled and do not know if this was forgotten.

**Comment by AlexanderYakunin** [comment]
Protected procedures implemented for v.20, we do not downgrade this kind of changes without CSS request

**Comment by Jiribu73** [comment]
I have downloaded latest version 20.0.35986.0 and procedure CreateCaptionSet is still local and not protected

**Comment by Jiribu73** [comment]
Same situation for the version 20.0.36262.0. @AlexanderYakunin - why is this issue still labeled as missing-info?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
