### ISSUE TITLE
Codeunit "Item Jnl.-Explode BOM", a way to influence or control the LineSpacing variable

### ISSUE THREAD

**Issue by stephanpl** [microsoft/ALAppExtensions#16247]
In our add-on, we use consecutive line numbers, raised by one, assigned to lines within a certain group.
In this situation, the action Explode BOM on the Item Journal fails because there is no line spacing between the item journal lines in such a group. 

What we could use for Codeunit 246 “Item Jnl.-Explode BOM” is a similar solution as was suggested in issue #12036

A procedure call is used to assign the value to the LineSpacing variable:
![image](https://user-images.githubusercontent.com/48206764/153379675-30813b29-072b-4e63-b684-bf6323d72614.png)

The line spacing is calculated in the procedure:
![image](https://user-images.githubusercontent.com/48206764/153379325-d48db5a4-1cde-472b-bb69-ce09fa779d73.png)

At the beginning of the procedure there is a publisher event added:
![image](https://user-images.githubusercontent.com/48206764/153379507-44d86400-bc00-4756-8045-b00c9134afd4.png)

**Comment by Oleg-Romashkov** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
