### ISSUE TITLE
[Event Request] table 37 "Sales Line" - OnBeforeInitType

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#16245]
Can you add SalesHeader as reference to OnBeforeInitType in the sales line table?
Just like in the purchase line table.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
