### ISSUE TITLE
Page 9249 "Analysis by Dimensions Matrix".OnAfterSetDimBudgetFilters

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16244]
Please change the parameter DimOption from Option to Enum "Analysis Dimension Option"

**Comment by Jiribu73** [comment]
Sorry wrong object, I have changed the title

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
