### ISSUE TITLE
Add PeriodType on Item Availability by Event to protected vars

### ISSUE THREAD

**Issue by spankau537826** [microsoft/ALAppExtensions#16248]
Hello,

I would like to request the PeriodType variable to be added to the protected variables on the Item Availability by Event Page (5530), so it can be accessed in a page extension.
The use case would be to have the PeriodType set to a customizable default value, instead of it always opening as day.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
