### ISSUE TITLE
using collectable errors funtionality for cloud

### ISSUE THREAD

**Issue by RasmusTorpeRIT** [microsoft/ALAppExtensions#16240]
We would like to able to use the new collectable errors funtionality ([link](https://docs.microsoft.com/en-us/dynamics365-release-plan/2021wave2/smb/dynamics365-business-central/collectable-errors-al)) when creating AL apps conforming with the "universal code initiative" (basically when target = cloud in app.json)

Please can we have the following changes made: 

Codeunit 28 "Error Message Management" 
- remove [Scope('OnPrem')] from procedure ShowErrors(Notification: Notification)
- remove [Scope('OnPrem')] from procedure ShowErrors(RegisterID: Guid)

Codeunit 28 "Error Message Management" 
- remove [Scope('OnPrem')] from procedure RegisterErrorMessages() RegisterID: Guid
- remove [Scope('OnPrem')] from procedure RegisterErrorMessages(ClearError: Boolean) RegisterID: Guid
- remove [Scope('OnPrem')] from procedure HasErrors(): Boolean

Thank you and regards, 

Rasmus

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.

**Comment by miljance** [comment]
Sounds great, we need it also.
