### ISSUE TITLE
[Expose procedures] Codeunit 2501 "Extension Marketplace" - Install* procedures

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#16241]
Following this idea https://experience.dynamics.com/ideas/idea/?ideaid=ad74b94f-0c6f-ec11-b820-0003ff459206 and this thread https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1523107125002240, we'd like to be able to auto-install AppSource apps from within the BC client, using the available functions from codeunit 2501 "Extension Marketplace".

Codeunit is currently set to 'Internal', blocking us from using several usefull functions.

Can you please expose following functions?

- IsMarketplaceEnabled
- InstallMarketplaceExtension
- InstallAppsourceExtension

**Comment by JesperSchulz** [comment]
I'll investigate if this is a safe thing to expose.

**Comment by JesperSchulz** [comment]
I did some digging and I'm no longer sure we can just expose the functions requested in this issue. There are concerns around changing the flow, needed when installing certain apps; some need you to contact a partner, some need you to accept EULAs, etc. By allowing to install apps through an API, we would go around these flows and would break the mechanisms we need to have in place. Bottom line, this is more complex than to just expose 3 functions. The suggested path forward is to go with the [BCIdea](https://experience.dynamics.com/ideas/idea/?ideaid=ad74b94f-0c6f-ec11-b820-0003ff459206), but we all know that things will take a while then. I'm afraid I won't be able to support this request at this point in time through this issue.
Sorry about that.
