### ISSUE TITLE
[Access Request] report 99003802 "Copy Production Order Document"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#16249]
Could you please change the Access of the following variables to `protected`, that we can access them from report extensions?
```al
protected var
        ToProdOrder: Record "Production Order";
        StatusType: Enum "Production Order Status";
        DocNo: Code[20];
        IncludeHeader: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
