### ISSUE TITLE
[Event Request] Table 7022 "Price Worksheet Line" –  OnAfterCopyExistingPrices

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#16256]
[Event Request] Table 7022 "Price Worksheet Line" –  OnAfterCopyExistingPrices

Could we please have a publisher OnAfterCopyExistingPrices in function CopyExistingPrices Table 7022 "Price Worksheet Line"?

```
    procedure CopyExistingPrices(PriceListLine: Record "Price List Line")
    begin
        "Existing Unit Price" := PriceListLine."Unit Price";
        "Existing Direct Unit Cost" := PriceListLine."Direct Unit Cost";
        "Existing Unit Cost" := PriceListLine."Unit Cost";

// >>>>>>>>
        OnAfterCopyExistingPrices(PriceListLine);
// <<<<<<<< 

    end;

// >>>>>>>>
    [IntegrationEvent(true, false)]
    local procedure OnAfterCopyExistingPrices(PriceListLine: Record "Price List Line")
    begin
    end;
// <<<<<<<<   

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
