### ISSUE TITLE
[Event Request] Table 7001 "Price List Line" –  OnAfterCopyPriceFrom

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#16254]
[Event Request] Codeunit Table 7001 "Price List Line" –  OnAfterCopyPriceFrom

Could we please have a publisher OnAfterCopyPriceFrom in function CopyPriceFrom Table 7001 "Price List Line"?

```
    procedure CopyPriceFrom(PriceAsset: Record "Price Asset")
    begin
        case PriceAsset."Price Type" of
            PriceAsset."Price Type"::Sale:
                "Unit Price" := PriceAsset."Unit Price";
            PriceAsset."Price Type"::Purchase:
                begin
                    "Direct Unit Cost" := PriceAsset."Unit Price";
                    "Unit Cost" := PriceAsset."Unit Price 2";
                end;
        end;

// >>>>>>>>
        OnAfterCopyPriceFrom(PriceAsset);
// <<<<<<<< 

end;
  
// >>>>>>>>
    [IntegrationEvent(true, false)]
    local procedure OnAfterCopyPriceFrom(PriceAsset: Record "Price Asset")
    begin
    end;
// <<<<<<<<   

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
