### ISSUE TITLE
event request - codeunit 6620 "Copy Document Mgt." - TransferFieldsFromCrMemoToInv() - OnBeforeCopySellToAddressToShipToAddressAndValidateShipToCode(...var IsHandled)

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#16251]
Please add an event to let us opt out of the lines

        ToSalesHeader.CopySellToAddressToShipToAddress;
        ToSalesHeader.Validate("Ship-to Code", FromSalesCrMemoHeader."Ship-to Code");

Like so:

    local procedure TransferFieldsFromCrMemoToInv(var ToSalesHeader: Record "Sales Header"; FromSalesCrMemoHeader: Record "Sales Cr.Memo Header")
    begin
        ToSalesHeader.Validate("Sell-to Customer No.", FromSalesCrMemoHeader."Sell-to Customer No.");
        ToSalesHeader.TransferFields(FromSalesCrMemoHeader, false);

        if (ToSalesHeader."Document Type" = ToSalesHeader."Document Type"::Invoice) and IncludeHeader then
            CopySellToAddressToShipToAddressAndValidateShipToCode(ToSalesHeader, FromSalesCrMemoHeader);

        OnAfterTransferFieldsFromCrMemoToInv(ToSalesHeader, FromSalesCrMemoHeader, CopyJobData);
    end;

    local procedure CopySellToAddressToShipToAddressAndValidateShipToCode(var ToSalesHeader: Record "Sales Header"; FromSalesCrMemoHeader: Record "Sales Cr.Memo Header")
    var
        IsHandled: Boolean;
    begin
        OnBeforeCopySellToAddressToShipToAddressAndValidateShipToCode(ToSalesHeader, FromSalesCrMemoHeader, IsHandled);
        if IsHandled then exit;

        ToSalesHeader.CopySellToAddressToShipToAddress;
        ToSalesHeader.Validate("Ship-to Code", FromSalesCrMemoHeader."Ship-to Code");
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCopySellToAddressToShipToAddressAndValidateShipToCode(var ToSalesHeader: Record "Sales Header"; FromSalesCrMemoHeader: Record "Sales Cr.Memo Header"; var IsHandled: Boolean)
    begin
    end;

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
