### ISSUE TITLE
[Event Request] Table 18 Customer - OnBeforeLookupContactList

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#16255]
Similar to the other OnBeforeLookup* events, we also need the following event in LookupContactList(), please:

```
local procedure LookupContactList()
var
    [...]
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeLookupContactList(Rec, IsHandled);
    if IsHandled then
        exit;

    [...]
```
The new publisher:
```
local procedure OnBeforeLookupContactList(var Customer: Record Customer; var IsHandled: Boolean)
begin
end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
