### ISSUE TITLE
Codeunit "Item Jnl.-Explode BOM", a way to influence or control the NextLineNo variable

### ISSUE THREAD

**Issue by stephanpl** [microsoft/ALAppExtensions#16250]
When Explode BOM is selected on the Item Journal line we want to be able to explode the BOM for multiple item journal lines.

To be able to do this, we would like to have access to the assignment of the NextLineNo in codeunit “Item Jnl.-Explode BOM”

That could be an extension of the available publisher OnBeforeToItemJnlLineInsert

![image](https://user-images.githubusercontent.com/48206764/153394638-edf64d0f-4ea0-4796-9484-e46fe76fed0a.png)

![image](https://user-images.githubusercontent.com/48206764/153393162-e5bef2a2-e819-4833-9c13-ff67e9927109.png)

Or alternatively, a separate event publisher that includes the NextLineNo variable by reference. Something like this:
![image](https://user-images.githubusercontent.com/48206764/153394351-cb826ffa-5c51-4593-bed1-27eb62fe95c8.png)

![image](https://user-images.githubusercontent.com/48206764/153394426-39612bb3-b56e-41b8-84c1-7e337948a553.png)

**Comment by Oleg-Romashkov** [comment]
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
