### ISSUE TITLE
[Event Request] Codeunit 5056 "CustCont-Update" - OnBeforeOnModify

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#16252]
Similar to OnDelete, we also need the following publisher in OnModify please:

```
procedure OnModify(var Cust: Record Customer)
var
    [...]    
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeOnModify(Cust, ContBusRel, IsHandled);
    if IsHandled then
        exit;

    [...]
```
The new publisher:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeOnModify(Customer: Record Customer; var ContactBusinessRelation: Record "Contact Business Relation"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
