### ISSUE TITLE
[Request for External] table 39 "Purchase Line" - InitNewLine

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#16260]
Can you change InitNewLine to global in purchase line?
It's already global in the sales line table.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
