### ISSUE TITLE
Record already exists error when selecting a default profile for a new user group

### ISSUE THREAD

**Issue by RodrigoPuelma** [microsoft/ALAppExtensions#16262]
**Problem**
When creating a new user group in User Groups (9830, List) and selecting a default profile from the lookup. The error occurs even when changing line before selecting the default profile (and triggering the delayed insert). The only way to avoid this error is by creating the new user group, close the user groups page and then assign a default profile.

![image](https://user-images.githubusercontent.com/35121934/153514619-43baccf0-bea5-439d-b411-d282969b8437.png)

When pressing OK, the new user group ends up with no profile. Sometimes the page even shows a duplicate record below/above the new user group.

**Expected behavior**
Users should be able to select a default profile when creating a new user group and should not have to first close the list page and then open the list page again to then be able to assign the default profile.

The image above is a screenshot of the error from a sandbox without any extensions beside the ones installed by Microsoft.
Version: AU Business Central 19.3 (Platform 19.0.34506.35781 + Application 19.3.34541.34662)

**Comment by pri-kise** [comment]
This repository is mostly for creating event requests.
If you have access you should create a support request on the partner portal 
https://partner.microsoft.com/en-US/dashboard/support/servicerequests/create?stage=1

**Comment by AlexanderYakunin** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL application extensibility. Please reach out to the relevant support channels:

For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
