### ISSUE TITLE
Missing Publisher in codeunit 5856 "TransferOrder-Post Transfer"

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#16265]
Currently there is not a single one there and it is very complicated to implement your extensions there. Please use the codeunit 5704 "TransferOrder-Post Shipment" or codeunit 5705 "TransferOrder-Post Receipt" as a template and insert a certain "standard".

**Comment by Stepanenko-Vadim** [comment]
Already addressed in part in issue #16171 
Will add 3 more events as part of this issue to a total of 10.
After that if you are missing particular events please specify where exactly and which params you need, also keep it at one per issue, thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
