### ISSUE TITLE
[Extensibility Request] Filter on "Message ID" in table "Sent Mail" and "Email Outbox"

### ISSUE THREAD

**Issue by NilsGruettner** [microsoft/ALAppExtensions#16269]
Hi,

it would be great if you could provide a way to filter on the field `Message ID` in the tables `Sent Mail` and `Email Outbox`.

I need a way to find the `Sent Mail` only by its `Message ID`, for example when the event `Codeunit::Email (8901), 'OnAfterSendEmail'` is raised. This event only provides the `Message ID`. Currently the field has the property `Access = Internal`, so I cannot filter on it to find the `Sent Mail`.
The same problem may occur with the `Email Outbox` table.

Proposals for solution:

- Make access modifier external or
- Add a `FilterMessageID(Guid)` method to the mentioned tables or
- Add a `GetByMessageID(Guid)` method to the mentioned tables

Version: DE Business Central 19.3 (Platform 19.0.34506.35491 + Application 19.3.34541.35597)

Edit: The `Email Outbox` table also lacks a `GetMessageId()` method. The table `Sent Mail` has such a method, so it would make sense to make this available for `Email Outbox` aswell.

**Comment by dannoe** [comment]
@NilsGruettner If you need a temporary solution:

```al
    local procedure TestMailFilter()
    var
        EmailOutbox: Record "Email Outbox";
        MailRecordRef: RecordRef;
        MessageIdFieldRef: FieldRef;
    begin
        MailRecordRef.GetTable(EmailOutbox);
        MessageIdFieldRef := MailRecordRef.Field(2); // Message ID
        MessageIdFieldRef.SetFilter('41a3c20d-923a-4b88-acd2-e791c02a97ef');

        if MailRecordRef.FindFirst() then begin
            Message('ok' + Format(MailRecordRef.Field(2).Value));
        end else
            Message('not ok');
    end;
```

**Comment by NilsGruettner** [comment]
@dannoe Thanks for the suggestion, I will give this a try!

**Comment by mazhelez** [comment]
@NilsGruettner Thanks for getting in touch.

What exactly is the scenario you are trying to cover? Why do you need to get the `Sent Email` by `Message ID`? A bit of a context would be great!

**Comment by NilsGruettner** [comment]
@mazhelez Thanks for your reply. 

I want to write a log entry with information from the `Sent Email` record. Right now the only possibility to get the sent email after sending, is to subscribe `EventSubscriber(ObjectType::Table, Database::"Sent Email", 'OnAfterInsertEvent'`, which is bad, because an error in this subscriber will break the email sending transaction and lead to data inconsistencies.

The better approach would be to subscribe to `EventSubscriber(ObjectType::Codeunit, Codeunit::Email, 'OnAfterSendEmail'` and `EventSubscriber(ObjectType::Codeunit, Codeunit::"Mail Management", 'OnSendViaEmailModuleOnAfterEmailSend'`.
Alas, the `OnAfterSendEmail` Publisher only provides a `MessageID`, thus I would need to utilize the workaround mentioned above to get the `Sent Email` record.
The workaround, though, should be considered as a bug that should lead to a runtime error at some point in the future.

**Comment by mazhelez** [comment]
@NilsGruettner thank you for clarifying!

In the upcoming release, the plan is to ship the so-called [isolated events](https://docs.microsoft.com/en-us/dynamics365-release-plan/2022wave1/smb/dynamics365-business-central/isolated-events).

I think an event of this type after an email has been sent would be ideal to address your scenario.

**Comment by NilsGruettner** [comment]
@mazhelez Oh, that is an awesome feature and that would definitely be the best solution.

In this case I would propose that the `OnAfterSendEmail` event should be transformed into an isolated event and then raised every time a mail is sent. Currently the event is only raised if the mail is sent in a background session.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
