### ISSUE TITLE
Codeunit "Purch. Doc. From Sales Doc.", assign additional fields before validating quantity in procedure CopySalesLinesToPurchaseLines

### ISSUE THREAD

**Issue by stephanpl** [microsoft/ALAppExtensions#16264]
In our add-on in most situations, it is crucial to have a variant code assigned before quantity is validated.
Therefore, I would request to have an event publisher after the No. field of the purchase line is validated in local procedure  CopySalesLinesToPurchaseLines in codeunit "Purch. Doc. From Sales Doc.", where the purchase line is passed as a parameter by reference so that we can assign some additional fields which are needed before the Quantity field is validated. This could be something like this:

![image](https://user-images.githubusercontent.com/48206764/153569705-1481cf4c-32b0-437f-85dc-946c0c5c0688.png)

![image](https://user-images.githubusercontent.com/48206764/153569728-97fa7a99-8012-48cb-9b73-f201606f9a0d.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
