### ISSUE TITLE
Change Event OnRunOnBeforeItemCheckAvailSalesLineCheck Codeunit 63 Sales-Explode BOM

### ISSUE THREAD

**Issue by anbi-pri** [microsoft/ALAppExtensions#16263]
Please add the IsHandled Boolean to the event in the OnRun Trigger

OLD:
IsHandled := false;
OnRunOnBeforeItemCheckAvailSalesLineCheck(ToSalesLine, FromBOMComp, Rec);
if not IsHandled then

NEW:
IsHandled := false;
OnRunOnBeforeItemCheckAvailSalesLineCheck(ToSalesLine, FromBOMComp, Rec, IsHandled);
if not IsHandled then

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
