### ISSUE TITLE
[EventRequest] Add xRec to OnBeforeValidateTimeSheetApproverUserID in table Resource

### ISSUE THREAD

**Issue by pieter-kok** [microsoft/ALAppExtensions#16278]
To be able to respond on a changed Time Sheet Approver User ID during the event OnBeforeValidateTimeSheetApproverUserID, I would like to suggest to add the xRec to the event definition. Just like the standard code does before raising an error on existing unprocessed time sheets.

    trigger OnValidate()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        //CHANGED >>
        //OnBeforeValidateTimeSheetApproverUserID(Rec, IsHandled);
        OnBeforeValidateTimeSheetApproverUserID(Rec, xRec, IsHandled);
        //CHANGED <<
        if IsHandled then
            exit;

        if "Time Sheet Approver User ID" <> xRec."Time Sheet Approver User ID" then
            if ExistUnprocessedTimeSheets then
                Error(Text005, FieldCaption("Time Sheet Approver User ID"));
    end;

```
[IntegrationEvent(false, false)]
//CHANGED >>
//local procedure OnBeforeValidateTimeSheetApproverUserID(var Resource: Record Resource; var IsHandled: Boolean)
local procedure OnBeforeValidateTimeSheetApproverUserID(var Resource: Record Resource; xResource: Record Resource; var IsHandled: Boolean)
//CHANGED <<
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
