### ISSUE TITLE
Event in Purchase Line - OnAfterCreateTempJobJnlLineEvent

### ISSUE THREAD

**Issue by Nischmiddi** [microsoft/ALAppExtensions#16272]
Hi,
I need an event in table 39 in the No.-OnValidate() after CreateTempJobJnlLine(true) (Line 252) to validate values of record TempJobJnlLine before update job prices.
Thank you very much. Have a good day.
Kind regards
Nico

**Comment by Stepanenko-Vadim** [comment]
There is already an **OnAfterCreateTempJobJnlLine** in **CreateTempJobJnlLine**, can you use that instead?

**Comment by Stepanenko-Vadim** [comment]
Please use that event. If it's not possible - feel free to open a new issue with the scenario, thanks.
