### ISSUE TITLE
[EventRequest] Report 82 "Export Budget to Excel".OnBeforeEnterRangeForDimension

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16273]
Related to the issues #16009 and #16233 please add two additional parameters to the event:

- var GLBudgetEntry: Record "G/L Budget Entry"
- var ExcelBuffer: Record "Excel Buffer"

    [IntegrationEvent(false, false)]
    local procedure OnBeforeEnterRangeForDimension(var DimensionRange: array[2, 8] of Integer; var BusUnit: Record "Business Unit"; var DimValue: Record "Dimension Value"; var RowNo: Integer; var IsHandled: Boolean; i: Integer; var GLBudgetEntry: Record "G/L Budget Entry";  var ExcelBuffer: Record "Excel Buffer")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
