### ISSUE TITLE
[Event Request] table Reminder Header - event OnInsertTextLinesOnBeforeReminderLineInsert pass parameter by var

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#16279]
In table Reminder Header, the event OnBeforeInsertReminderTextLine is replaced by OnInsertTextLinesOnBeforeReminderLineInsert

However, the parameters are not equal. Parameter ReminderHeader should be passed by var in the new event OnInsertTextLinesOnBeforeReminderLineInsert just like it was in the obsoleted event.

Current code
```
    [Obsolete('Replaced with OnInsertTextLinesOnBeforeReminderLineInsert', '20.0')]
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertReminderTextLine(var ReminderLine: Record "Reminder Line"; var ReminderText: Record "Reminder Text"; var ReminderHeader: Record "Reminder Header")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnInsertTextLinesOnBeforeReminderLineInsert(var ReminderLine: Record "Reminder Line"; var ReminderText: Record "Reminder Text"; ReminderHeader: Record "Reminder Header")
    begin
    end;
```

Code after correction

```
    [IntegrationEvent(false, false)]
    local procedure OnInsertTextLinesOnBeforeReminderLineInsert(var ReminderLine: Record "Reminder Line"; var ReminderText: Record "Reminder Text"; var ReminderHeader: Record "Reminder Header")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
