### ISSUE TITLE
[EventRequest] Page 7001 "Price List Lines", New Event OnUpdateSourceType

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#16275]
The local procedure UpdateSourceType sets values depending on the "Source Group" of the related header record. The "Source Group" is an extensible Enum, but the procedure gives us no possibility to react to an extended enum value. We would need a new event OnUpdateSourceType and a new publisher within the procedure to allow for extending the case-operation:

    local procedure UpdateSourceType()
    var
        PriceSource: Record "Price Source";
    begin
        case PriceListHeader."Source Group" of
            "Price Source Group"::Customer:
                begin
                    IsJobGroup := false;
                    SourceType := "Sales Price Source Type".FromInteger(Rec."Source Type".AsInteger());
                end;
            "Price Source Group"::Job:
                begin
                    IsJobGroup := true;
                    JobSourceType := "Job Price Source Type".FromInteger(Rec."Source Type".AsInteger());
                end;
            // New Publisher
            else
                OnUpdateSourceType(PriceListHeader, SourceType, IsJobGroup)
        end;
        PriceSource."Source Type" := Rec."Source Type";
        IsParentAllowed := PriceSource.IsParentSourceAllowed();
    end;

    // New Integration Event
    [IntegrationEvent(false, false)]
    local procedure OnUpdateSourceType(PriceListHdr: Record "Price List Header" ; var SourceType: Enum "Sales Price Source Type"; var IsJobGroup: Boolean)
    begin
    end;

**Integration Event:** OnUpdateSourceType
Parameters:
PriceListHdr: Record "Price List Header" (by value)
var SourceType: Enum "Sales Price Source Type" (by reference)
var IsJobGroup: Boolean (by reference)

**Publisher:** OnUpdateSourceType
To be added as new else-statement at the end of the case-operation in local procedure UpdateSourceType.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
