### ISSUE TITLE
[EventRequest] Page 7016 "Sales Price List", New Event OnUpdateSourceType

### ISSUE THREAD

**Issue by GaryWinter** [microsoft/ALAppExtensions#16274]
The local procedure UpdateSourceType sets values depending on the "Source Group" of the record. The "Source Group" is an extensible Enum, but the procedure gives us no possibility to react to an extended enum value. We would need a new event OnUpdateSourceType and a new publisher within the procedure to allow for extending the case-operation:

    local procedure UpdateSourceType()
    begin
        case Rec."Source Group" of
            Rec."Source Group"::Customer:
                begin
                    IsJobGroup := false;
                    SourceType := "Sales Price Source Type".FromInteger(Rec."Source Type".AsInteger());
                    DefaultSourceType := Rec."Source Type"::"All Customers";
                end;
            Rec."Source Group"::Job:
                begin
                    IsJobGroup := true;
                    JobSourceType := "Job Price Source Type".FromInteger(Rec."Source Type".AsInteger());
                    DefaultSourceType := Rec."Source Type"::"All Jobs";
                end;
            // New Publisher
            else
                OnUpdateSourceType(Rec, SourceType, DefaultSourceType, IsJobGroup);
        end;
    end;

    // New Integration Event
    [IntegrationEvent(false, false)]
    local procedure OnUpdateSourceType(PriceListHdr: Record "Price List Header" ; var SourceType: Enum "Sales Price Source Type"; var DefaultSourceType: Enum "Price Source Type"; var IsJobGroup: Boolean)
    begin
    end;

**IntegrationEvent:** OnUpdateSourceType
Parameters:
PriceListHdr: Record "Price List Header" (by value)
SourceType: Enum: "Sales Price Source Type" (by reference)
DefaultSourceType: Enum "Price Source Type" (by reference)
IsJobGroup: Boolean (by reference)

**Publisher:** Place as new else-statement at the end of he case-operation in local procedure OnUpdateSourceType

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
