### ISSUE TITLE
[Protection Level] Page 7022 "Price Worksheet" protected vars needed

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#16271]
Hello,
please make:

        CustomerSourceType: Enum "Sales Price Source Type";
        VendorSourceType: Enum "Purchase Price Source Type";
        JobSourceType: Enum "Job Price Source Type";
        PriceType: Enum "Price Type";
        SourceGroup: Enum "Price Source Group";
        AllowEditingActivePrice: Boolean;
        AllowUpdatingDefaults: Boolean;
        AmountTypeIsEditable: Boolean;
        AmountTypeIsVisible: Boolean;
        AssetTypeEditable: Boolean;
        DiscountEditable: Boolean;
        DiscountVisible: Boolean;
        ItemAsset: Boolean;
        ItemAssetVisible: Boolean;
        LineExists: Boolean;
        ModifiedLine: Boolean;
        ModifiedUnitPrice: Boolean;
        ModifiedUnitCost: Boolean;
        ModifiedDirectUnitCost: Boolean;
        ParentSourceNoEditable: Boolean;
        PriceEditable: Boolean;
        PriceLineEditable: Boolean;
        PriceVisible: Boolean;
        PurchPriceLine: Boolean;
        PurchVisible: Boolean;
        ResourceAsset: Boolean;
        ResourceAssetVisible: Boolean;
        SalesPriceLine: Boolean;
        SalesVisible: Boolean;
        SourceNoEditable: Boolean;
        SourceTypeEditable: Boolean;

to protected vars.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
