### ISSUE TITLE
[Extensibility Request]: Contact, Procedure GetSalutation, Error Message

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#16281]
Hi AL Team,
we would like to suggest the following extensibility enhancement:

 Table Contact, Procedure GetSalutation, Error Message
```
        if not SalutationFormula.Get("Salutation Code", LanguageCode, SalutationType) then
            Error(Text021, LanguageCode, "No.");
```
We suggest the following enhancement:

```
        if not SalutationFormula.Get("Salutation Code", LanguageCode, SalutationType) then
            Error(Format(SalutationType), Text021, LanguageCode, "No.");
```
The passed Enum "Salutation Formula Salutation Type" is extensible, so the Enum value should be considered in the error message.

Thanks!

**Comment by dnpb** [comment]
Error(Format(SalutationType), Text021, LanguageCode, "No.");

This is wrong, as the 1st argument must be the text string into which the remaining arguments are substituted.

You should show what you want as the new value of `Text021`, and where in that the `SalutationType` should go (i.e. which numbered argument it is). It shouldn't need `Format()`ted either as the platform does that implicitly with arguments to `Error()`, `Message()`, etc.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
