### ISSUE TITLE
[Request for External] Page 43 Sales Invoice - UpdatePaymentService

### ISSUE THREAD

**Issue by shuyusheng** [microsoft/ALAppExtensions#16286]
Could we change UpdatePaymentService from local to protected, similar to #7592, thanks.

```
protected procedure UpdatePaymentService()
var
    PaymentServiceSetup: Record "Payment Service Setup";
begin
    PaymentServiceEnabled := PaymentServiceSetup.CanChangePaymentService(Rec);
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
