### ISSUE TITLE
[Protection Level] page 5114 "Contact Profile Answers"

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#16280]
Please make following global variables in the page 5114 protected so that they can be used by page extension:
Cont: Record Contact;
ContProfileAnswer: Record "Contact Profile Answer";

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
