### ISSUE TITLE
[Request for global] Codeunit 5600 "FA Insert Ledger Entry" - InsertRegister

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#16294]
Hello,

We would need to have the function InsertRegister global, to be able to call it from other places that need this function.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
