### ISSUE TITLE
[Request for External] Table 5612 "FA Depreciation Book" - LinearMethod(): 

### ISSUE THREAD

**Issue by VPaas2** [microsoft/ALAppExtensions#16298]
Make LinearMethod a global method:

```
procedure LinearMethod(): Boolean 
    begin
        exit(
          "Depreciation Method" in
          ["Depreciation Method"::"Straight-Line",
          "Depreciation Method"::"DB1/SL",
          "Depreciation Method"::"DB2/SL"]);
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
