### ISSUE TITLE
[Modify parameter to be by reference ] Codeunit 5600 "FA Insert Ledger Entry" - OnInsertFAOnBeforeCheckFALedgEntry

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#16292]
Hello,

We would need to have the parameter FALedgEntry by reference in the event OnInsertFAOnBeforeCheckFALedgEntry from Codeunit 5600 "FA Insert Ledger Entry".

So instead of this:

    [IntegrationEvent(false, false)]
    local procedure OnInsertFAOnBeforeCheckFALedgEntry(FALedgEntry: Record "FA Ledger Entry"; FALedgEntry2: Record "FA Ledger Entry"; var IsHandled: Boolean)
    begin
    end;

to be declared like this:

    [IntegrationEvent(false, false)]
    local procedure OnInsertFAOnBeforeCheckFALedgEntry(**var** FALedgEntry: Record "FA Ledger Entry"; FALedgEntry2: Record "FA Ledger Entry"; var IsHandled: Boolean)
    begin
    end;

We would need to have this parameter as by reference, because we want to use this event to update some fields on FALedgEntry from  FALedgEntry2. Later in the function InsertFA, a Modify is done on FALedgEntry, so the changes done on this record on event OnInsertFAOnBeforeCheckFALedgEntry will be saved.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
