### ISSUE TITLE
[Add extra parameter] Codeunit 5600 "FA Insert Ledger Entry" - OnBeforeInsertRegister

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#16293]
Hello,

We would need a new parameter NextEntryNo to the event OnBeforeInsertRegister from codeunit 5600 "FA Insert Ledger Entry".

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertRegister(var FALedgerEntry: Record "FA Ledger Entry"; var FALedgerEntry2: Record "FA Ledger Entry"; **var NextEntryNo: Integer**)
    begin
    end;

We would need this new parameter in the event OnBeforeInsertRegister, because in some cases, new FA Ledger Entries are created and the NextEntryNo should be correctly updated, when calling function InsertRegister.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
