### ISSUE TITLE
[Request for External] Table 5612 "FA Depreciation Book" - var FA and DeprBook

### ISSUE THREAD

**Issue by VPaas2** [microsoft/ALAppExtensions#16299]
Request to make Variables FA And DeprBook in FADepreciationBook protected:

```
    protected var
        FA: Record "Fixed Asset";
        DeprBook: Record "Depreciation Book";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
