### ISSUE TITLE
[Enum Request] Table "Reminder Text" 294 - Position

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#16290]
Can you please change the field "Position" into an extensible enum.
Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
