### ISSUE TITLE
[bug] Table: Purchase Header (38) - Field: Ship-to Country (92) translating error

### ISSUE THREAD

**Issue by tvandruten** [microsoft/ALAppExtensions#16300]
The translation of the field Ship-to Country(92) in Purchase Header (38) is not working until you fill Ship-to Country/Region Code (93)

see 5,1,
![afbeelding](https://user-images.githubusercontent.com/85502495/154070587-449303ba-7335-4de9-acbf-c7e4615549c8.png)

Now it says State
![afbeelding](https://user-images.githubusercontent.com/85502495/154070709-c13b59d8-d5f4-4780-a170-ac81f6891926.png)

**Comment by AlexanderYakunin** [comment]
This is already fixed

**Comment by tvandruten** [comment]
Thanks for your answer. is it fixed in BC19 CU3? We're running CU2 and the issue exists.
