### ISSUE TITLE
[bug] Table: Sales Header (36) - Field: Ship-to Country (92) translating error

### ISSUE THREAD

**Issue by tvandruten** [microsoft/ALAppExtensions#16301]
The translation of the field Ship-to Country(92) in Sales Header (36) is not working until you fill Ship-to Country/Region Code (93)

See 5,1,
![afbeelding](https://user-images.githubusercontent.com/85502495/154071127-9bd47774-e561-45d5-a00e-360f7274d0ef.png)

See State
![afbeelding](https://user-images.githubusercontent.com/85502495/154071318-88865fd6-d77a-434b-9dec-8936eb37fd9a.png)

**Comment by AlexanderYakunin** [comment]
This is already fixed
