### ISSUE TITLE
[Protected var] Page 5404 "Item Units of Measure"

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#16302]
We'd like to apply the same styling for additional fields added to the "Item Units of Measure" page.
Therefore, please add the `StyleName` variable to the protected var section.

In addition, it would be beneficial to also have the `ItemBaseUOM` variable included in the protected var section. This would eliminate some code to refetch the Item's Base UOM.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
