### ISSUE TITLE
[Event Request] New Event Parameters - codeunit 63 "Sales-Explode BOM" - OnRunOnBeforeItemCheckAvailSalesLineCheck

### ISSUE THREAD

**Issue by GregorGrabner** [microsoft/ALAppExtensions#16304]
Hi Microsoft AL Dev Team,

Please Chage Event: OnRunOnBeforeItemCheckAvailSalesLineCheck
Please do this also for the next CU of BC18

OLD
===================
local procedure OnRunOnBeforeItemCheckAvailSalesLineCheck(var ToSalesLine: Record "Sales Line"; FromBOMComp: Record "BOM Component"; SalesLine: Record "Sales Line")

NEW
===================
local procedure OnRunOnBeforeItemCheckAvailSalesLineCheck(var ToSalesLine: Record "Sales Line"; FromBOMComp: Record "BOM Component"; SalesLine: Record "Sales Line"; var IsHandled: Boolean; HideDialog: Boolean)

BACKGROUND
===================
HideDialog Paramerter: is needed to Capture the Event and avoid Item Availibility Check if HideDialog is set

var IsHandled Parameter: IsHandled is just missing in Parameter.  Code Lines before and after EventCall are already coded for IsHandled

Best Regards
Gregor Grabner

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
