### ISSUE TITLE
Missing Publisher in page 5814 "Item Charge Assignment (Sales)"

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#16318]
I miss a publisher in local procedure UpdateQty called OnAfterUpdateQty

=================== OLD CODE============
    local procedure UpdateQty()
    begin
        case "Applies-to Doc. Type" of
            "Applies-to Doc. Type"::Order, "Applies-to Doc. Type"::Invoice:
                begin
                    SalesLine.Get("Applies-to Doc. Type", "Applies-to Doc. No.", "Applies-to Doc. Line No.");
                    QtyToShipBase := SalesLine."Qty. to Ship (Base)";
                    QtyShippedBase := SalesLine."Qty. Shipped (Base)";
......
......
......
                    QtyShippedBase := SalesShptLine."Quantity (Base)";
                    GrossWeight := SalesLine."Gross Weight";
                    UnitVolume := SalesLine."Unit Volume";
                end;
        end;
    end;
    
 =================== NEW CODE REQUEST============
 
     local procedure UpdateQty()
    begin
        case "Applies-to Doc. Type" of
            "Applies-to Doc. Type"::Order, "Applies-to Doc. Type"::Invoice:
                begin
                    SalesLine.Get("Applies-to Doc. Type", "Applies-to Doc. No.", "Applies-to Doc. Line No.");
                    QtyToShipBase := SalesLine."Qty. to Ship (Base)";
                    QtyShippedBase := SalesLine."Qty. Shipped (Base)";
......
......
......
                    GrossWeight := SalesLine."Gross Weight";
                    UnitVolume := SalesLine."Unit Volume";
                end;
        end;
        **OnAfterUpdateQty(Rec, QtyToShipBase , QtyShippedBase , QtyToRetReceiveBase, QtyRetReceivedBase, GrossWeight, UnitVolume);**
    end;
 
     **[IntegrationEvent(false, false)]
    local procedure OnAfterUpdateQty(var ItemChargeAssignmentSales: Record "Item Charge Assignment (Sales)"; var QtyToShipBase: Decimal; var QtyShippedBase: Decimal; var QtyToReceiveBase: Decimal; var QtyReceivedBase: Decimal; var GrossWeight: Decimal; var UnitVolume: Decimal)
    begin
    end;**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
