### ISSUE TITLE
[Extensibility-Bug] Config. Package.  Setup Processing Order For Tables

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#16314]
Hello,

In codeunit "Config. Package Management" we have a function ApplyPackage, maybe in all function calls of this function in the base application, for example at  Config. Package page we set the parameter SetupProcessingOrderForTables = true.
when SetupProcessingOrderForTables is the true system will remove Processing Order of package tables field that was defined before and create that for some base application tables. 
I think it's a mistake because when we change the processing order for tables in the package it was deleted at apply package stage.

Please analyze this issue, maybe the great solution will be to separate SetupProcessingOrder into different actions and change the call ApplyPackage with SetupProcessingOrderForTables = false.
Also, we need to change or override this parameter in procedure ApplyPackages table 8627 "Config. Setup"

Thank  you!

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. As a quick solution we provide a new event in codeunit 8611 "Config. Package Management":
   ` local procedure OnBeforeSetupProcessingOrder(var ConfigPackageTable: Record "Config. Package Table"; var IsHandled: Boolean)`
For a long term solution we created a work item 437534.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40908.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 40994.
