### ISSUE TITLE
[Protected var Request] - Report 7391 "Whse. Get Bin Content"

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#16312]
We would like to have the following variables as protected var, so we can use them in report extension.

Object: WhseGetBinContent.Report.al
Global Variable: DestinationType2, QtyToEmptyBase, ReportInitialized

from:
```
var
  DestinationType2: Option MovementWorksheet,WhseInternalPutawayHeader,ItemJournalLine,TransferHeader,InternalMovementHeader;
  QtyToEmptyBase: Decimal;
  ReportInitialized: Boolean;
```

to:
```
protected var
  DestinationType2: Option MovementWorksheet,WhseInternalPutawayHeader,ItemJournalLine,TransferHeader,InternalMovementHeader;
  QtyToEmptyBase: Decimal;
  ReportInitialized: Boolean;
```

Thanks in advance,
Christian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
