### ISSUE TITLE
[Event Request] [Application “Tests-ERM”]()Codeunit 134804 "RED Test Unit for Purch Doc"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#16315]
[Event Request]Application “Tests-ERM”, 134804 "RED Test Unit for Purch Doc"

Could you please insert the OnTestInitialize Event at the beginning of the following test procedures:
-	TestOpenPurchaseInvoiceDeferralScheduleNeg
-	TestOpenPurchaseCreditMemoDeferralScheduleNeg
-	TestOpenPurchaseReturnOrderDeferralScheduleNeg
-	TestOpenPurchaseOrderDeferralScheduleNeg
![pic1](https://user-images.githubusercontent.com/45795262/154293223-43b6afef-ecc2-4d22-8e5e-4ca24c5bb0d3.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
