### ISSUE TITLE
Table 36 "Sales Header" - Change GetUserSetupSalespersonCode() to protected

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16325]
Could we change GetUserSetupSalespersonCode from local to protected?

![image](https://user-images.githubusercontent.com/99872396/154469633-95ea0d5c-c564-4c20-9003-fb6ce7b358c4.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
