### ISSUE TITLE
[Request for External] codeunit 1173 "Document Attachment Mgmt" - local procedure "CopyAttachmentsForPostedDocs"

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#16336]
hey,

please make the procedure external.

codeunit 1173 "Document Attachment Mgmt"
local procedure CopyAttachmentsForPostedDocs(var FromRecRef: RecordRef; var ToRecRef: RecordRef)

thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
