### ISSUE TITLE
[BUG] [Event Request] Codeunit 333 "Req. Wksh.-Make Order" - InitPurchOrderLine Function

### ISSUE THREAD

**Issue by Celicienta** [microsoft/ALAppExtensions#16353]
Dear ALAppExtensions Team,

I would like to request the following event publisher in Codeunit 333 "Req. Wksh.-Make Order" - InitPurchOrderLine Function.
![image](https://user-images.githubusercontent.com/74307312/154649331-e8eb3552-d274-46cc-84a9-8f6c2442fec1.png)

New publisher Event:
[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateOrderDateInRequisitionLine(var RequisitionLine : Record "Requisition Line";var PurchOrderHeader: Record "Purchase Header";var PurchOrderLine: Record "Purchase Line";var IsHandled: Boolean)
    begin
    end;
I request this event because I need to be able to not recalculate the direct unit cost in the requisition line.
Thank you.

**Comment by Celicienta** [comment]
Hi,
This line is new in a version 19.3 and **I think this is a bug** because it should not be possible to fill direct unit cost in a requisition line if this cost is going to recalculate it when the purchase is created.
Why did you add that line in the 19.3 update?

  Validate("Order Date", PurchOrderHeader."Order Date");

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
