### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134805 "RED Test Unit for Sales Doc"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#16354]
[Event Request]Application “Tests-ERM”, 134805 "RED Test Unit for Sales Doc"

Could you please insert the OnTestInitialize Event at the beginning the following test procedures:
-	TestOpenSalesOrderDeferralScheduleNeg
-	TestOpenSalesCreditMemoDeferralScheduleNeg
-	TestOpenSalesReturnOrderDeferralScheduleNeg
-	TestOpenSalesInvoiceDeferralScheduleNeg

![pic1](https://user-images.githubusercontent.com/45795262/154682172-36f8954d-8322-4d19-ab31-e2b28debd2ba.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
