### ISSUE TITLE
Improvement Codeunit 5988 "Serv-Documents Mgt." / Function FinalizeInvoiceDocument 

### ISSUE THREAD

**Issue by RaKuNbg** [microsoft/ALAppExtensions#16356]
Background for the request:
We added a BLOB-Field to table "Service Header" and "Service Invoice Header" and added code to transfer the value in the publisher OnBeforeServInvHeaderInsert but it never appeared in the "Service Invoice Header" at the end of the posting.
After long time of searching we found the function FinalizeInvoiceDocument that copies from the temporary "Service Invoice Header" record to the real record but doesn't respect that BLOB fields have to be calculated :-(

Request:
1. Publisher OnBeforeFinalizeInvoiceDocument should be extended with Parameter "ServHeader" and and handled flag:

local procedure OnBeforeFinalizeInvoiceDocument(var ServiceInvoiceHeader: Record "Service Invoice Header"; ServiceHeader: record "Service Header"; Handlel: Boolean)

2. Publisher OnAfterFinalizeInvoiceDocument(ServInvHeader, ServHeader) should have variable PServInvHeader (instead of ServInvHeader) as parameter.

3. Function FinalizeInvoiceDocument should be checked in general if there is a better way to move the data from the temporary record to the real record considering BLOB fields.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
