### ISSUE TITLE
[Event Request] Table 18 Customer - CheckPrepaymentDocNo Function

### ISSUE THREAD

**Issue by plinto97** [microsoft/ALAppExtensions#16363]
Hello,  I would like to ask you to add new event OnBeforeCheckPrepaymentDocNo in table 18 "Customer" in procedure CheckPrepaymentDocNo. Thank you.
![1](https://user-images.githubusercontent.com/98730800/154900735-c8623889-af27-4052-88aa-013854296fc4.png)
![2](https://user-images.githubusercontent.com/98730800/154900737-4086f1ca-7258-495c-9075-03901b50b60e.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
