### ISSUE TITLE
[Event Request] Request for new event publisher OnBeforeOpenJnlBatch in codeunit 230 GenJnlManagement

### ISSUE THREAD

**Issue by mie-swp-group** [microsoft/ALAppExtensions#16369]
procedure OpenJnlBatch(var GenJnlBatch: Record "Gen. Journal Batch")
    var
        [SecurityFiltering(SecurityFilter::Filtered)]
        GenJnlTemplate: Record "Gen. Journal Template";
        [SecurityFiltering(SecurityFilter::Filtered)]
        GenJnlLine: Record "Gen. Journal Line";
        JnlSelected: Boolean;
    begin
        OnBeforeOpenJnlBatch(GenJnlBatch, isHandled);
        if isHandled then
            exit;
        if GenJnlBatch.GetFilter("Journal Template Name") <> '' then
            exit;
        GenJnlBatch.FilterGroup(2);
        if GenJnlBatch.GetFilter("Journal Template Name") <> '' then begin
            GenJnlBatch.FilterGroup(0);
            exit;
        end;
        GenJnlBatch.FilterGroup(0);

        if not GenJnlBatch.Find('-') then
            for GenJnlTemplate.Type := GenJnlTemplate.Type::General to GenJnlTemplate.Type::Jobs do begin
                GenJnlTemplate.SetRange(Type, GenJnlTemplate.Type);
                if not GenJnlTemplate.FindFirst then
                    TemplateSelection(0, GenJnlTemplate.Type, false, GenJnlLine, JnlSelected);
                if GenJnlTemplate.FindFirst then
                    CheckTemplateName(GenJnlTemplate.Name, GenJnlBatch.Name);
                if GenJnlTemplate.Type = GenJnlTemplate.Type::General then begin
                    GenJnlTemplate.SetRange(Recurring, true);
                    if not GenJnlTemplate.FindFirst then
                        TemplateSelection(0, GenJnlTemplate.Type, true, GenJnlLine, JnlSelected);
                    if GenJnlTemplate.FindFirst then
                        CheckTemplateName(GenJnlTemplate.Name, GenJnlBatch.Name);
                    GenJnlTemplate.SetRange(Recurring);
                end;
            end;

        GenJnlBatch.Find('-');
        JnlSelected := true;
        GenJnlBatch.CalcFields("Template Type", Recurring);
        GenJnlTemplate.SetRange(Recurring, GenJnlBatch.Recurring);
        if not GenJnlBatch.Recurring then
            GenJnlTemplate.SetRange(Type, GenJnlBatch."Template Type");
        if GenJnlBatch.GetFilter("Journal Template Name") <> '' then
            GenJnlTemplate.SetRange(Name, GenJnlBatch.GetFilter("Journal Template Name"));
        case GenJnlTemplate.Count of
            1:
                GenJnlTemplate.FindFirst;
            else
                JnlSelected := PAGE.RunModal(0, GenJnlTemplate) = ACTION::LookupOK;
        end;
        if not JnlSelected then
            Error('');

        GenJnlBatch.FilterGroup(0);
        GenJnlBatch.SetRange("Journal Template Name", GenJnlTemplate.Name);
        GenJnlBatch.FilterGroup(2);

        OnAfterOpenJournalBatch(GenJnlBatch, GenJnlTemplate);
    end;

        [IntegrationEvent(false, false)]
        local procedure OnBeforeOpenJnlBatch(var GenJnlBatch: Record "Gen. Journal Batch"; var isHandled: boolean);
        begin
        end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
