### ISSUE TITLE
[EventRequest] Page 554 "Analysis by Dimensions".OnBeforeDimCodeToDimOption

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16360]
Please ad var to the parameter Result

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDimCodeToDimOption(DimCode: Text[30]; var AnalysisView: Record "Analysis View"; var Result: Enum "Analysis Dimension Option"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
