### ISSUE TITLE
Codeunit 12 - "Gen. Jnl.-Post Line" - Change CalcLCYToAddCurr() to global

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16370]
Could we change CalcLCYToAddCurr from local to global?

![image](https://user-images.githubusercontent.com/99872396/154954998-81b84340-ce30-4c76-8279-e69d03a59cda.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
