### ISSUE TITLE
Codeunit 22 - ""Item Jnl.-Post Line"" - Change PostInventoryToGL() to global

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16379]
Could you change PostInventoryToGL() from local to global?

![image](https://user-images.githubusercontent.com/99872396/154957099-ced0150d-c5b6-4c9a-bd19-f31146da03a3.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
