### ISSUE TITLE
Codeunit 5895 "Inventory Adjustment" - Change ExpCostIsCompletelyInvoiced() to global

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16377]
Could you change ExpCostIsCompletelyInvoiced() from local to global?

```
    procedure ExpCostIsCompletelyInvoiced(ItemLedgEntry: Record "Item Ledger Entry"; ValueEntry: Record "Value Entry"): Boolean
    begin
        with ItemLedgEntry do
            exit(ValueEntry."Expected Cost" and (Quantity = "Invoiced Quantity"));
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
