### ISSUE TITLE
[Event Request] Codeunit 12 - "Gen. Jnl.-Post Line" -Add new parameters in OnBeforeInsertVATEntry()

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16374]
Hello,
We would need a new parameters in the event OnBeforeInsertVATEntry().

New parameters: 

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertVATEntry(var VATEntry: Record "VAT Entry"; GenJournalLine: Record "Gen. Journal Line"; var NextVATEntryNo: Integer; var GLEntryVATEntryLink: Record "G/L Entry - VAT Entry Link"; var TempGLEntryBuf: Record "G/L Entry" temporary)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
