### ISSUE TITLE
[Event Change Request] Codeunit 8612 - Procedure InsertTemplate / Event OnInsertTemplateCaseElse

### ISSUE THREAD

**Issue by NemanjaKutlesic** [microsoft/ALAppExtensions#16373]
Hi,

Object: codeunit 8612 "Config. Template Management"
Event: OnInsertTemplateCaseElse

It would be nice to extend event **OnInsertTemplateCaseElse** in procedure InsertTemplate to be aware from which Record we are inserting related template. With this change, we would be able to define and insert data for different tables in which PK is dependent on source Config. Template Table.

For example, we can create one template for Fixed Asset and define a related template for Depreciation Book, and if we try that, currently it won't be possible since Depreciation Book PK contains Fixed Asset No., but if we extend the event with RecRef, we would have Fixed Asset No. and we will be able to create Depreciation Book together with Fixed Asset

For that case, I would suggest the following structure

Event call (**new parameter added RecRef at the end**):

`OnInsertTemplateCaseElse(ConfigTemplateLine, ConfigTemplateHeader2, FieldRef, RecRef2, SkipFields, TempSkipField, RecRef);`

Event declaration:

```
    [IntegrationEvent(false, false)]
    local procedure OnInsertTemplateCaseElse(var ConfigTemplateLine: Record "Config. Template Line"; var ConfigTemplateHeader: Record "Config. Template Header"; FldRef: FieldRef; var RecRef: RecordRef; SkipFields: Boolean; var TempSkipField: record Field; OldRecRef: RecordRef)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
