### ISSUE TITLE
[Event Change Request] Report 952 "Suggest Job Jnl. Lines" - OnAfterTransferTimeSheetDetailToJobJnlLine

### ISSUE THREAD

**Issue by nicmartino** [microsoft/ALAppExtensions#16371]
[Event Change Request]
Object: Report 952 "Suggest Job Jnl. Lines"
Event: OnAfterTransferTimeSheetDetailToJobJnlLine ;
Could you please add the requested parameter to the event  **OnAfterTransferTimeSheetDetailToJobJnlLine**

```
// OnAfterTransferTimeSheetDetailToJobJnlLine(JobJnlLine, JobJnlTemplate, TempTimeSheetLine, TimeSheetDetail, JobJnlBatch) //OLD
OnAfterTransferTimeSheetDetailToJobJnlLine(JobJnlLine, JobJnlTemplate, TempTimeSheetLine, TimeSheetDetail, JobJnlBatch, LineNo) //NEW
```
```
[IntegrationEvent(false, false)]
local procedure OnAfterTransferTimeSheetDetailToJobJnlLine(var JobJournalLine: Record "Job Journal Line"; JobJournalTemplate: Record "Job Journal Template"; var TempTimeSheetLine: Record "Time Sheet Line" temporary; TimeSheetDetail: Record "Time Sheet Detail"; JobJournalBatch: Record "Job Journal Batch"; var LineNo: Integer)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
