### ISSUE TITLE
[External Request] CheckItemAvailable

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#16376]
Please make all local occurrences of procedure CheckItemAvailable externally available.
This affects the following tables:

- table 901 "Assembly Line"
- codeunit 5857 "Copy Invt. Document Mgt."
- table 5851 "Invt. Document Line"
- table 83 "Item Journal Line" (duplicate of #14497)
- table 210 "Job Journal Line"
- table 1003 "Job Planning Line"
- table 5741 "Transfer Line"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
