### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" -Add new parameters in OnBeforeCalcLineAmountAndLineDiscountAmount()

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16387]
Hello,
We would need a new parameters in the event OnBeforeCalcLineAmountAndLineDiscountAmount().

Resulting event:

```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeCalcLineAmountAndLineDiscountAmount(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; PurchLineQty: Decimal; var IsHandled: Boolean; Currency: Record Currency)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
