### ISSUE TITLE
Codeunit 90 "Purch.-Post" - Change GetPrepmtDiffToLineAmount() to global

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16382]
Could you change GetPrepmtDiffToLineAmount() from local to global?

![image](https://user-images.githubusercontent.com/99872396/154958185-e5c1c809-e835-40f0-ada7-c3fe8bd9e0b5.png)

**Comment by AlexanderYakunin** [comment]
This is already a global procedure

**Comment by XeMaTT** [comment]
I have reviewed version 19.3 and that procedure is still local. Could you tell me in which version approximately it will be global? Attached definition of it in version 19.3

![image](https://user-images.githubusercontent.com/99872396/155551020-b3dca491-16d0-47c9-be4b-1c253b61c626.png)

**Comment by AlexanderYakunin** [comment]
We do not implement such changes into PROD versions, only to vNext. It is implemented in 20.0
