### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - Add new parameters in OnPostItemJnlLineOnAfterCopyDocumentFields()

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16389]
Hello,
We would need a new parameters in the event OnPostItemJnlLineOnAfterCopyDocumentFields().

Resulting event:

```
    [IntegrationEvent(false, false)]
    local procedure OnPostItemJnlLineOnAfterCopyDocumentFields(var ItemJournalLine: Record "Item Journal Line"; PurchaseLine: Record "Purchase Line"; WarehouseReceiptHeader: Record "Warehouse Receipt Header"; WarehouseShipmentHeader: Record "Warehouse Shipment Header"; PurchRcptHeader: Record "Purch. Rcpt. Header")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
