### ISSUE TITLE
[External Request] UpdateReservation / VerifyChangeForSalesLineReserve

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#16386]
Please make the local procedure UpdateReservation externally available in the following tables:
- table 1003 "Job Planning Line".UpdateReservation
- table 5902 "Service Line".UpdateReservation
- table 37 "Sales Line".VerifyChangeForSalesLineReserve

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
