### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" -Add new parameters in OnPostItemChargeOnBeforePostItemJnlLine()

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16388]
Hello,
We would need a new parameters in the event OnPostItemChargeOnBeforePostItemJnlLine().

Resulting event:

```
    [IntegrationEvent(false, false)]
    local procedure OnPostItemChargeOnBeforePostItemJnlLine(var PurchaseLineToPost: Record "Purchase Line"; var PurchaseLine: Record "Purchase Line"; QtyToAssign: Decimal; var TempItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)" temporary; PurchInvHeader: Record "Purch. Inv. Header")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
