### ISSUE TITLE
codeunit 1201 "Process Data Exch.", function ProcessColumnMapping

### ISSUE THREAD

**Issue by JulianSchmidtkeGWS** [microsoft/ALAppExtensions#16394]
Please make the function ProcessColumnMapping in the codeunit 1201 "Process Data Exch." externally available.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
