### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" -Add new parameters in OnRunOnBeforeMakeInventoryAdjustment()

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16390]
Hello,
We would need a new parameters in the event OnRunOnBeforeMakeInventoryAdjustment().

Resulting event:

```
    [IntegrationEvent(false, false)]
    local procedure OnRunOnBeforeMakeInventoryAdjustment(var PurchaseHeader: Record "Purchase Header"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line"; PreviewMode: Boolean; PurchRcptHeader: Record "Purch. Rcpt. Header"; PurchInvHeader: Record "Purch. Inv. Header")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
