### ISSUE TITLE
Codeunit  10750 "SII XML Creator" - procedure CalculateTotalVatAndBaseAmounts() - OnCalculateTotalVatAndBaseAmountsOnBeforeCalculateTotals

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#16397]
Could You please, add the following event to the Codeunit  10750 "SII XML Creator"

Object: Codeunit  10750 "SII XML Creator"
procedure CalculateTotalVatAndBaseAmounts()

Publisher Event: OnCalculateTotalVatAndBaseAmountsOnBeforeCalculateTotals

Reason: To implement custom business logic and modify the Vat amounts fields in some scenarios
Where is the event placed (see image attached)?:

![Event sii 1](https://user-images.githubusercontent.com/73465025/155008949-8358a2b5-b416-4268-bd09-b45d6ed7176e.jpg)

just after the repeat loop for VATEntry table, between lines 1693 and 1694
Insert the next line:

OnCalculateTotalVatAndBaseAmountsOnBeforeCalculateTotals(LedgerEntryRecRef, VATEntry);  (see image)

![Event sii 1 1](https://user-images.githubusercontent.com/73465025/155009122-a4f3d164-0950-4c55-9ed1-df1188aa1785.jpg)

Event Code:
[IntegrationEvent(false, false)]
    local procedure OnCalculateTotalVatAndBaseAmountsOnBeforeCalculateTotals(LedgerEntryRecRef: RecordRef; var VATEntry: Record "VAT Entry")
    begin
    end;

Thanks in Advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
