### ISSUE TITLE
[Event Request] Report 357 - "Copy Company" - Add new parameter in OnAfterCreatedNewCompanyByCopyCompany()

### ISSUE THREAD

**Issue by RobertoVP** [microsoft/ALAppExtensions#16400]
Hello, we would need a new parameter (SourceCompanyName) in the event OnAfterCreatedNewCompanyByCopyCompany() - Report 357 - "Copy Company":

```
trigger OnPostDataItem()
var
    JobQueueManagement: Codeunit "Job Queue Management";
begin
    ProgressWindow.Close;
    SetNewNameToNewCompanyInfo;
    JobQueueManagement.SetRecurringJobsOnHold(NewCompanyName);
    OnAfterCreatedNewCompanyByCopyCompany(SourceCompanyName, NewCompanyName);
    RegisterUpgradeTags(NewCompanyName);
    Message(CopySuccessMsg, Name);
end;
```

Resulting event:

```
[IntegrationEvent(false, false)]
local procedure OnAfterCreatedNewCompanyByCopyCompany(SourceCompanyName: Text[30]; NewCompanyName: Text[30])  
begin
end;
```
Thank you.

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
