### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post - OnBeforeFillTempLine

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#16404]
Hi, would it be possible to get an event OnBeforeFillTempline in codeunit 80, trigger OnRun, like this :

```
...
        GetGLSetup();
        GetSalesSetup();
        GetInvoicePostingSetup();
        GetCurrency(Rec."Currency Code");

        SalesHeader := Rec;
        OnBeforeFillTempline (SalesHeader);
        FillTempLines(SalesHeader, TempSalesLineGlobal);
        TempServiceItem2.DeleteAll();
        TempServiceItemComp2.DeleteAll();
...

```
```

    [IntegrationEvent(false, false)]
    local procedure OnBeforeFillTempline (var SalesHeader: Record "Sales Header")
    begin
    end;
```
?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
