### ISSUE TITLE
[Protected var] Page 5905 "Service Lines"

### ISSUE THREAD

**Issue by savithasGit** [microsoft/ALAppExtensions#16406]
We'd like to apply different filters to Service Line page during the page load.
Therefore, please add the SelectionFilter variable to the protected var section.

Microsoft standard page global variable section for reference :
![image](https://user-images.githubusercontent.com/75597068/155137145-e526c802-d8a4-46f2-be44-c406d272ca9f.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
