### ISSUE TITLE
Integration events in Report 10743 "Make 340 Declaration"

### ISSUE THREAD

**Issue by camadorsummar** [microsoft/ALAppExtensions#16405]
Hi,

Would it be possible to include two integration events in the following functions?

![image](https://user-images.githubusercontent.com/67145347/155154518-b8c5e68c-a102-40be-86f1-8cfc8c64cf27.png)

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
