### ISSUE TITLE
Table 290 "VAT Amount Line" - Event OnAfterCheckVATDifference

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#16403]
Hi,

There is a bug in the event **OnAfterCheckVATDifference** of table 290 "VAT Amount Line", the first parameter must be declared by  reference.

see the image:
![VatAmount line 3](https://user-images.githubusercontent.com/73465025/155099042-4c161342-6224-4a27-b5f2-d48c4cb71e52.jpg)

Cloul you please, fix it and add the var word to it?

![vat amount line 4](https://user-images.githubusercontent.com/73465025/155099566-1d632952-71d0-4b2a-ad1d-49e3bf7411f9.jpg)

Thanks in advance

**Comment by dnpb** [comment]
Why should it be `var`? The purpose is to check the line, not change it.

**Comment by IgnacioPeq** [comment]
Hi, 
is due to change some custom fields added to manage the deductible vat.

But sorry, you have reason, I can deal with it by adding modify OnAfterValidate triggers for standard fields in a table extension.

Thanks, I close this request.
