### ISSUE TITLE
[Extensibility Request] Page 5600 "Fixed Asset Card" - Protected variables & Protected procedures

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16417]
Hello, we need the following currently global variables defined as protected for our page extension. Can you please check that?

    protected var
        FADepreciationBookOld: Record "FA Depreciation Book";
        Simple: Boolean;

We also need the following currently Local procedures to be set as protected, for the same purpose. Can you please check this one too? Thank you!

    protected procedure ShowAcquisitionNotification()
    protected procedure SetDefaultDepreciationBook()
    protected procedure SetDefaultPostingGroup()

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
