### ISSUE TITLE
[Event Request] Modify OnBeforeVendorInsert on Procedure CreateVendorFromTemplate

### ISSUE THREAD

**Issue by TBorgerink** [microsoft/ALAppExtensions#16410]
Hi,

Is it possible to modify OnBeforeVendorInsert(Vend, Rec) from procedure CreateVendorFromTemplate from the Contact table. And make it the same as event published in the procedure CreateCustomerFromTemplate event OnCreateCustomerFromTemplateOnBeforeCustomerInsert, so the VendorTemplateCode is given to the event as well.

from: 
        Clear(Vend);
        Vend.SetInsertFromContact(true);
        OnBeforeVendorInsert(Vend, Rec);
        Vend.Insert(true);
...#line 1566

to:
        Clear(Vend);
        Vend.SetInsertFromContact(true);
        OnCreateVendorFromTemplateOnBeforeVendorInsert(Vend, Rec, VendorTemplateCode);
        Vend.Insert(true);
...#line 1566

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
