### ISSUE TITLE
[Extensibility Request] Page 5076 "Interaction Log Entries" - Protected variable

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16420]
Hello, we need the following currently global variable defined as protected for our page extension. Can you please check that? Thank you!

    protected var
        ShowEnable: Boolean;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
