### ISSUE TITLE
Page 9658 "Vendor Report Selections" - Make Usage2 Protected Var

### ISSUE THREAD

**Issue by adueker** [microsoft/ALAppExtensions#16439]
Greetings and Salutations!

Can we get Usage2 to be a protected var so we can extend this page and functionality like we can on the customer side? It would be super appreciated by us and @MattiLE who submitted a similar request twice in May (#12141) and October (#14671) of last year.

Props to you and your team, All the love!

**Comment by MattiLE** [comment]
Hi @adueker, 

i looked in the pre-release version of BC20 and there Usage2 is protected. I hope that at the latest in the first real BC20 version the variable is protected.
Maybe the info will help you :)

**Comment by adueker** [comment]
@MattiLE,

Thank you for your response! Just so I'm aware in the future where could I go to see this?

**Comment by MattiLE** [comment]
@adueker 
Do you know the BCArtifacts? With the BCInsider account you can download pre-release versions.
Check out this blog post for more information.
https://freddysblog.com/2020/06/25/working-with-artifacts/
