### ISSUE TITLE
[Event Request] codeunit 99000854 "Inventory Profile Offsetting" - OnAfterMaintainPlanningLine

### ISSUE THREAD

**Issue by MarcoHeijden** [microsoft/ALAppExtensions#16435]
Could you please set "var" before the parameter ReqLine

    [IntegrationEvent(false, false)]
    local procedure OnAfterMaintainPlanningLine(var ReqLine: Record "Requisition Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by MarcoHeijden** [comment]
Hi Anca,

Microsoft just responded to the second event and agreed. I already updated the WIKI page<https://cegekadsa.visualstudio.com/DynamicsEmpire/_wiki/wikis/DynamicsEmpire.wiki/6784/-0FP-Pending-GitHub-Requests>.

Met vriendelijke groet,
Marco van der Heijden
Software Engineer
