### ISSUE TITLE
[Event Request] Page 1350 "Posted Sales Shipment - Update" - New publisher

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16433]
Hello, we need a new Event publisher in procedure RecordChanged(). Can you please check that? Thank you!

    local procedure RecordChanged() IsChanged : Boolean
    begin
        IsChanged := false;
        OnBeforeCheckRecordChanged(Rec, xSalesShipmentHeader, IsChanged);
        if IsChanged then
            exit(true);

        IsChanged :=
          ("Shipping Agent Code" <> xSalesShipmentHeader."Shipping Agent Code") or
          ("Package Tracking No." <> xSalesShipmentHeader."Package Tracking No.") or
          ("Shipping Agent Service Code" <> xSalesShipmentHeader."Shipping Agent Service Code");

        OnAfterRecordChanged(Rec, xSalesShipmentHeader, IsChanged);
    end;

New Event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckRecordChanged(SalesShipmentHeader: Record "Sales Shipment Header"; xSalesShipmentHeader: Record "Sales Shipment Header"; var Changed: Boolean)
    begin
    end;

**Comment by Oleg-Romashkov** [comment]
Hi,
Please use existing event OnAfterRecordChanged which has same signature and allows to set IsChanged return value.

**Comment by MarkoMilosavljevic** [comment]
Hi Oleg, 
thank you for your reply, we will use the Event you suggest.
