### ISSUE TITLE
[Event Request] Page 499 "Available - Sales Lines" - New publisher

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16431]
Hello, we need a new Event publisher in procedure CreateReservation(). Can you please check that? Thank you!

    local procedure CreateReservation(ReserveQuantity: Decimal; ReserveQuantityBase: Decimal)
    var
        TrackingSpecification: Record "Tracking Specification";
        IsHandled: Boolean;
    begin
        if Abs("Outstanding Qty. (Base)") + "Reserved Qty. (Base)" < ReserveQuantityBase then
            Error(Text003, Abs("Outstanding Qty. (Base)") + "Reserved Qty. (Base)");

        IsHandled := false;
        OnCreateReservationOnBeforeTestFields(Rec, ReservEntry, IsHandled);
        if not IsHandled then begin
            TestField("Job No.", '');
            TestField("Drop Shipment", false);
            TestField("No.", ReservEntry."Item No.");
            TestField("Variant Code", ReservEntry."Variant Code");
            TestField("Location Code", ReservEntry."Location Code");
        end;
        TrackingSpecification.InitTrackingSpecification(
            DATABASE::"Sales Line", "Document Type".AsInteger(), "Document No.", '', 0, "Line No.",
            "Variant Code", "Location Code", "Qty. per Unit of Measure");
        ReservMgt.CreateReservation(
          ReservEntry.Description, "Shipment Date", ReserveQuantity, ReserveQuantityBase, TrackingSpecification);
        UpdateReservFrom;
    end;

New Event:

    [IntegrationEvent(false, false)]
    local procedure OnCreateReservationOnBeforeTestFields(SalesLine: Record "Sales Line"; ReservationEntry: Record "Reservation Entry"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
