### ISSUE TITLE
[Protection Level] page 7005 "Price List Line Review" - visible & editable variables

### ISSUE THREAD

**Issue by BertDeTemmerman** [microsoft/ALAppExtensions#16445]
Could the same as for #14649 & #14650 be done for page 7005 "Price List Line Review" please?
including, but not limited to, LineToVerify & HideProductControls
So we don't need to duplicate these variables and functions in order to have the same control/UI for our added fields on a pageextension.

**Comment by AlexanderYakunin** [comment]
Please be more specific which variables should be protected.

**Comment by BertDeTemmerman** [comment]
These would be, like in the made changes for those other 2 issues,:
- AmountEditable: Boolean;
- UOMEditable: Boolean;
- ItemAsset: Boolean;
- ResourceAsset: Boolean;
- DiscountMandatory: Boolean;
- DiscountStyle: Text;
- DiscountVisible: Boolean;
- PriceMandatory: Boolean;
- PriceStyle: Text;
- PriceVisible: Boolean;
- IsSalesPrice: Boolean;
- PriceEditable: Boolean;
- AmountTypeIsVisible: Boolean;
- AmountTypeIsEditable: Boolean;
- LineExists: Boolean;
- LineToVerify: Boolean;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
