### ISSUE TITLE
[Event Request] Page 343 "Check Credit Limit" - Add new parameter in OnShowWarningOnBeforeExitValue()

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16448]
Hello,
We would need a new parameters in the event OnShowWarningOnBeforeExitValue().

Resulting event:

```
    [IntegrationEvent(false, false)]
    local procedure OnShowWarningOnBeforeExitValue(var Customer: Record Customer; ExitValue: Integer; var Result: Boolean; var IsHandled: Boolean; var Heading: Text[250])
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
