### ISSUE TITLE
Codeunit 7600 "Calendar Management", Function: CheckDateStatus, Add new event

### ISSUE THREAD

**Issue by nicdiblasiFS** [microsoft/ALAppExtensions#16442]
Hi, 
Can the follow event please be added in, 
Codeunit 7600 "Calendar Management", 
Inside Function: CheckDateStatus
Where: 
![image](https://user-images.githubusercontent.com/87403142/155465132-0c70d722-d03e-4d79-bc97-7b16aeeeb6ae.png)

The new event: 
[IntegrationEvent(false, false)]
local procedure OnCheckDateStatusAfterDateCustomized(var TargetCustomizedCalendarChange: Record "Customized Calendar Change"; TempCustChange: Record "Customized Calendar Change")

As I wish to pass the Temporary Customer Calendar change as a parameter.

Kind Regards Nic

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
