### ISSUE TITLE
[Request for permissions] codeunit 70 "Purch.-Calc.Discount"

### ISSUE THREAD

**Issue by MarcoHeijden** [microsoft/ALAppExtensions#16446]
Please add indirect permissions to codeunit 70 "Purch.-Calc.Discount" so the purchase process can be handled by indirect permissions

    codeunit 70 "Purch.-Calc.Discount"
    {
    ++  Permissions = TableData "Purchase Header" = rm,
    ++                TableData "Purchase Line" = rm;
        TableNo = "Purchase Line";

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
