### ISSUE TITLE
Page: 7604 "Base Calendar Entries Subform", Event: OnUpdateBaseCalendarChanges

### ISSUE THREAD

**Issue by nicdiblasiFS** [microsoft/ALAppExtensions#16443]
Hi, 
Can the following event please be modified. 

Page: 7604 "Base Calendar Entries Subform"
Event: OnUpdateBaseCalendarChanges

Change to: 
 [IntegrationEvent(false, false)]
    local procedure OnUpdateBaseCalendarChanges(var BaseCalendarChange: Record "Base Calendar Change";CustCalendarChange: Record "Customized Calendar Change")
    
We wish to modify the current record of the page. 
    
Kind Regards Nic

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
