### ISSUE TITLE
[Event Request] codeunit 5944 "SignServContractDoc"

### ISSUE THREAD

**Issue by pfortunyak** [microsoft/ALAppExtensions#16440]
Please add OnAddendumToContractOnAfterServContractLineLoop publisher into the position below.

procedure AddendumToContract(ServContractHeader: Record "Service Contract Header")
...       
        ServContractLine.Reset();
        ServContractLine.SetCurrentKey("Contract Type", "Contract No.", Credited, "New Line");
        ServContractLine.SetRange("Contract Type", FromServContractHeader."Contract Type");
        ServContractLine.SetRange("Contract No.", FromServContractHeader."Contract No.");
        ServContractLine.SetRange("New Line", true);
        StartingDate := WorkDate;
        OnAddendumToContractOnAfterSetStartingDate(FromServContractHeader, StartingDate);
        if ServContractLine.FindSet then
            repeat
                OnAddendumToContractOnBeforeServContractLineLoop(ServContractLine, StartingDate);
                if ServMgtSetup."Contract Rsp. Time Mandatory" then
                    ServContractLine.TestField("Response Time (Hours)");
                ServContractLine."Starting Date" := StartingDate;
                if (ServContractLine."Next Planned Service Date" <> 0D) and
                   (ServContractLine."Next Planned Service Date" < StartingDate)
                then
                    ServContractLine."Next Planned Service Date" := StartingDate;
                ServContractLine.Modify();
               OnAddendumToContractOnAfterServContractLineLoop(ServContractLine, StartingDate); //New Event!
            until ServContractLine.Next() = 0;
...

[IntegrationEvent(false, false)]
    local procedure OnAddendumToContractOnAfterServContractLineLoop(var ServContractLine: Record "Service Contract Line"; var StartingDate: Date)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
