### ISSUE TITLE
[Event Request] Page 5708 "Get Shipment Lines" - New event OnCreateLinesEvent()

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16453]
Hello,
We would need a new event OnCreateLinesEvent() in procedure CreateLines() in page "Get Shipment Lines".

New event:

```
    [IntegrationEvent(true, false)]
    local procedure OnCreateLinesEvent(var pSalesHeader: Record "Sales Header"; var pSalesShipmentLine: Record "Sales Shipment Line")
    begin
    end;
```

Here:

```
    procedure CreateLines()
    begin
        CurrPage.SetSelectionFilter(Rec);
        SalesGetShpt.SetSalesHeader(SalesHeader);

        //++ New event
        OnCreateLinesEvent(SalesHeader, Rec);
        SalesGetShpt.CreateInvLines(Rec);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
