### ISSUE TITLE
[Event Request] Table 1003 "Job Planning Line" . Use

### ISSUE THREAD

**Issue by navaddict** [microsoft/ALAppExtensions#16459]
Please add an event 'OnBeforeUpdateRemainingQuantity' as shown the the code sample below.

This is required so that the paragraph of code that starts with the check '**if (PostedQty >= 0) = ("Remaining Qty." >= 0) then**' can be skipped in particular instances (but only to skip that paragraph & not a complete exit of the whole procedure).

Many thanks!!

procedure Use(PostedQty : Decimal; PostedTotalCost : Decimal; PostedLineAmount; Decimal)
begin
IF "Usage Link" THEN BEGIN
  InitRoundingPrecisions;
  // Update Quantity Posted
  VALIDATE("Qty. Posted","Qty. Posted" + PostedQty);

  // Update Posted Costs and Amounts.
  "Posted Total Cost" += ROUND(PostedTotalCost,AmountRoundingPrecisionFCY);
  "Posted Total Cost (LCY)" := ROUND(
      CurrExchRate.ExchangeAmtFCYToLCY(
        "Currency Date","Currency Code",
        "Posted Total Cost","Currency Factor"),
      AmountRoundingPrecision);

  "Posted Line Amount" += ROUND(PostedLineAmount,AmountRoundingPrecisionFCY);
  "Posted Line Amount (LCY)" := ROUND(
      CurrExchRate.ExchangeAmtFCYToLCY(
        "Currency Date","Currency Code",
        "Posted Line Amount","Currency Factor"),
      AmountRoundingPrecision);

        //----------------------------------------OnBeforeUpdateRemainingQuantity:BEGIN
        IsHandled := false;        
        OnBeforeUpdateRemainingQuantity();
        if not IsHandled then
        //----------------------------------------OnBeforeUpdateRemainingQuantity:END

        IF (PostedQty >= 0) = ("Remaining Qty." >= 0) THEN
    IF ABS(PostedQty) <= ABS("Remaining Qty.") THEN
      VALIDATE("Remaining Qty.","Remaining Qty." - PostedQty)
    ELSE BEGIN
      VALIDATE(Quantity,Quantity + PostedQty - "Remaining Qty.");
      VALIDATE("Remaining Qty.",0);
    END
  ELSE
    VALIDATE("Remaining Qty.","Remaining Qty." - PostedQty);

  // Update Remaining Costs and Amounts
  UpdateRemainingCostsAndAmounts;

...

//----------------------------------------OnBeforeUpdateRemainingQuantity:START
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateRemainingQuantity(var JobPlanningLine: Record "Job Planning Line"; var IsHandled: Boolean)
begin
end;
//----------------------------------------OnBeforeUpdateRemainingQuantity:END

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
