### ISSUE TITLE
Broken Event in Codeunit "Item Jnl.-Post Line" OnAfterApplyItemLedgEntry

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/ALAppExtensions#16457]
The event publisher OnAfterApplyItemLedgEntry in the codeunit "Item Jnl.-Post Line" will never be called:
```
    local procedure ApplyItemLedgEntry(var ItemLedgEntry: Record "Item Ledger Entry"; var OldItemLedgEntry: Record "Item Ledger Entry"; var ValueEntry: Record "Value Entry"; CausedByTransfer: Boolean)
............
            end;
            OnApplyItemLedgEntryOnApplicationLoop(ItemLedgEntry);
        until false;

        OnAfterApplyItemLedgEntry(GlobalItemLedgEntry, OldItemLedgEntry, ItemJnlLine);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
