### ISSUE TITLE
[Event Request] codeunit 99000854 "Inventory Profile Offsetting" - OnMaintainPlanningLineOnBeforeReqLineInsert

### ISSUE THREAD

**Issue by MarcoHeijden** [microsoft/ALAppExtensions#16450]
Please add an IsHandled pattern to the event OnMaintainPlanningLineOnBeforeReqLineInsert. We cannot use the event OnBeforeMaintainPlanningLine since our conditions are dependent on values of the requisition line like the quantities.

                    OnMaintainPlanningLineOnBeforeAdjustPlanLine(ReqLine, SupplyInvtProfile, TempSKU);
                    AdjustPlanLine(SupplyInvtProfile);
                    "Accept Action Message" := true;
                    "Routing Reference No." := "Line No.";
                    UpdateDatetime;
                    "MPS Order" := SupplyInvtProfile."MPS Order";
                    OnMaintainPlanningLineOnBeforeReqLineInsert(
                      ReqLine, SupplyInvtProfile, PlanToDate, CurrForecast, NewPhase, Direction, DemandInvtProfile, ExcludeForecastBefore, **IsHandled**);
                    if IsHandled then
                        exit;
                    Insert;
 
    [IntegrationEvent(false, false)]
    local procedure OnMaintainPlanningLineOnBeforeReqLineInsert(var RequisitionLine: Record "Requisition Line"; var SupplyInvtProfile: Record "Inventory Profile"; PlanToDate: Date; CurrentForecast: Code[10]; NewPhase: Option " ","Line Created","Routing Created",Exploded,Obsolete; Direction: Option Forward,Backward; DemandInvtProfile: Record "Inventory Profile"; ExcludeForecastBefore: Date; **var IsHandled: Boolean**)
    begin
    end;

**Comment by Oleg-Romashkov** [comment]
Hi,
This approach could cause potential issues for couple of events which go after. Please use existing event OnBeforeMaintainPlanningLine or find another way of you logic realization.
