### ISSUE TITLE
[Event Request] Codeunit "Item Jnl.-Post Line" OnAfterApplyItemLedgEntryOnBeforeCalcAppliedQty

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/ALAppExtensions#16461]
The Event OnAfterApplyItemLedgEntryOnBeforeCalcAppliedQty in the Codeunit "Item Jnl.-Post Line" has these 2 Parameter:
`OldItemLedgerEntry: Record "Item Ledger Entry"`
`ItemLedgerEntry: Record "Item Ledger Entry"`

Is it possible to add the `var` option to `OldItemLedgerEntry`?

from 
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterApplyItemLedgEntryOnBeforeCalcAppliedQty(OldItemLedgerEntry: Record "Item Ledger Entry"; ItemLedgerEntry: Record "Item Ledger Entry")
    begin
    end;
```

to
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterApplyItemLedgEntryOnBeforeCalcAppliedQty(var OldItemLedgerEntry: Record "Item Ledger Entry"; ItemLedgerEntry: Record "Item Ledger Entry")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
