### ISSUE TITLE
[Protection Level] page 7001 "Price List Lines" 

### ISSUE THREAD

**Issue by BertDeTemmerman** [microsoft/ALAppExtensions#16463]
Could these variables also be set to protected please?

- DiscountStyle: Text;
- PriceStyle: Text;
- LineToVerify: Boolean;

Like for #14649 ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
