### ISSUE TITLE
[Protection Level] page  - visible & editable variables

### ISSUE THREAD

**Issue by BertDeTemmerman** [microsoft/ALAppExtensions#16464]
Similar to #14649 & #14650 & #16445 & #16463
Could the following variables be set protected?
- DiscountStyle: Text;
- PriceStyle: Text;
- LineToVerify: Boolean;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
