### ISSUE TITLE
[Event Request] codeunit 5944 "SignServContractDoc"

### ISSUE THREAD

**Issue by djuras1** [microsoft/ALAppExtensions#16466]
Please add 'OnAddendumToContractOnAfterServHeaderNoValidate' publisher into the position below.

procedure AddendumToContract(ServContractHeader: Record "Service Contract Header")
...
if InvoicePrepaid and FromServContractHeader.Prepaid then begin
            ServContractMgt.InitCodeUnit;
            if ServHeaderNo = '' then
                ServHeaderNo :=
                  ServContractMgt.CreateServHeader(FromServContractHeader, PostingDate, false);
            OnAddendumToContractOnAfterServHeaderNoValidate(ServHeaderNo, ServContractMgt, FromServContractHeader); // --> NEW EVENT

            RemainingAmt := 0;
            ServContractLine.Reset();
            ServContractLine.SetCurrentKey("Contract Type", "Contract No.", Credited, "New Line");
            ServContractLine.SetRange("Contract Type", FromServContractHeader."Contract Type");
            ServContractLine.SetRange("Contract No.", FromServContractHeader."Contract No.");
            ServContractLine.SetRange("New Line", true);

...

[IntegrationEvent(false, false)]
local procedure OnAddendumToContractOnAfterServHeaderNoValidate(var ServHeaderNo: Code[20], var ServContractMgt: Codeunit ServContractManagement, FromServContractHeader: Record "Service Contract Header")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
