### ISSUE TITLE
Expose ParseParametersAndFlags from UriBuilderImpl. or UriBuilder.GetQueryParameter

### ISSUE THREAD

**Issue by bjarkihall** [microsoft/ALAppExtensions#16460]
Hi,

I just noticed:
**UriBuilderImpl.ParseParametersAndFlags**, which can convert `Text -> Dictionary of [Text, list of [Text]]`

Currently it's only possible to **Add** a query parameter to a URL but there's no way to **Get** a query parameter.

The method uses `NameValueCollection: DotNet NameValueCollection;` and `HttpUtility: DotNet HttpUtility;` so we're not able to use a similar approach in our own solution.

So I was thinking if it was possible to make this procedure public?
Or maybe:

```al
// UriBuilder.Codeunit.al:
procedure GetQueryParameter(ParameterKey: Text) Values: List of [Text]
begin
    Values := UriBuilderImpl.GetQueryParameter(ParameterKey);
end;

// UriBuilderImpl.Codeunit.al:
procedure GetQueryParameter(ParameterKey: Text) Values: List of [Text]
var
    KeysWithValueList: Dictionary of [Text, List of [Text]];
    Flags: List of [Text];
    QueryString: Text;
begin
    if ParameterKey = '' then
        Error(QueryParameterKeyCannotBeEmptyErr);

    QueryString := GetQuery();
    ParseParametersAndFlags(QueryString, KeysWithValueList, Flags);
    
    if not KeysWithValueList.ContainsKey(ParameterKey) then begin
        if Flags.Contains(ParameterKey) then
            Values.Add('');
        exit;
    end;

    KeysWithValueList.Get(ParameterKey, Values);
end;
```

Ideas for test cases:
UriBuilder.Init and set QueryParam as = '?a=1,2&b=3&c'
GetQueryParameter(''); -> Error // empty key
GetQueryParameter('a') -> ['1', '2'] // multiple values
GetQueryParameter('b') -> ['3'] // single value
GetQueryParameter('c') -> [''] // flag (key but no values)
GetQueryParameter('d') -> [] // query parameter not present

What do you think?

**Comment by JesperSchulz** [comment]
Unless there would be a security issue in doing so, I don't see why not! The System Application's URI module is open sourced. Please create PR, if you'd like to get the code above code reviewed and ultimately added :-)
