### ISSUE TITLE
[Event Request] codeunit 5944 "SignServContractDoc"

### ISSUE THREAD

**Issue by djuras1** [microsoft/ALAppExtensions#16465]
Please add 'OnAddendumToContractOnAfterPostingDateValidate' publisher into the position below.

procedure AddendumToContract(ServContractHeader: Record "Service Contract Header")
...
if InvoiceNow then begin
            PostingDate := InvoiceFrom;
            OnAddendumToContractOnAfterPostingDateValidate(PostingDate, InvoiceFrom); // --> NEW EVENT
            ServContractLine.Reset();
            ServContractLine.SetCurrentKey("Contract Type", "Contract No.", Credited, "New Line");
            ServContractLine.SetRange("Contract Type", FromServContractHeader."Contract Type");
            ServContractLine.SetRange("Contract No.", FromServContractHeader."Contract No.");
            ServContractLine.SetRange("New Line", true);
            if ServContractLine.FindSet then
                repeat
                    if (ServContractLine."Contract Expiration Date" <> 0D) and
                       (ServContractLine."Contract Expiration Date" < InvoiceTo)
                    then
                        NoOfMonthsAndMParts := ServContractMgt.NoOfMonthsAndMPartsInPeriod(
                            InvoiceFrom, ServContractLine."Contract Expiration Date")
                    else
                        if (FromServContractHeader."Expiration Date" <> 0D) and
                           (FromServContractHeader."Expiration Date" < InvoiceTo)
                        then
                            NoOfMonthsAndMParts := ServContractMgt.NoOfMonthsAndMPartsInPeriod(
                                InvoiceFrom, FromServContractHeader."Expiration Date")
                        else
                            NoOfMonthsAndMParts :=
                              ServContractMgt.NoOfMonthsAndMPartsInPeriod(InvoiceFrom, InvoiceTo);
                    RemainingAmt :=
                      RemainingAmt +
                      Round(
                        ServContractLine."Line Amount" / 12 * NoOfMonthsAndMParts, Currency."Amount Rounding Precision");
                until ServContractLine.Next() = 0;
        end;
...

[IntegrationEvent(false, false)]
local procedure OnAddendumToContractOnAfterPostingDateValidate(var PostingDate: Date, var InvoiceForm: Date)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
