### ISSUE TITLE
[Event Request] Codeunit "Job Create-Invoice"

### ISSUE THREAD

**Issue by ElmarFV** [microsoft/ALAppExtensions#16462]
Our client, Converge, has a mod in NAV8.0 that needs to be replicated in BC19 Cloud (their now current environment). This mod populates a new field in the "Job Planning Line Invoice" table with the value in the PostingDate variable in the CreateSalesInvoiceLines function in codeunit 1002 "Job Create-Invoice".
This is how it looks in NAV8.0

      JobPlanningLineInvoice."Document No." := SalesHeader."No.";
      JobPlanningLineInvoice."Line No." := SalesLine."Line No.";
      JobPlanningLineInvoice."Quantity Transferred" := JobPlanningLine."Qty. to Transfer to Invoice";
      //>>
      JobPlanningLineInvoice."Invoice Date" := PostingDate;
      //<<
      IF NewInvoice THEN
        JobPlanningLineInvoice."Transferred Date" := PostingDate
      ELSE
        JobPlanningLineInvoice."Transferred Date" := SalesHeader."Posting Date";
      JobPlanningLineInvoice.INSERT;

But there is no way for me to tap into this code in BC19 as this is how it looks today...

                    JobPlanningLineInvoice."Document No." := SalesHeader."No.";
                    JobPlanningLineInvoice."Line No." := SalesLine."Line No.";
                    JobPlanningLineInvoice."Quantity Transferred" := JobPlanningLine."Qty. to Transfer to Invoice";
                    JobPlanningLineInvoice."Transferred Date" := PostingDate;
                    JobPlanningLineInvoice.Insert();

I need a new IntegrationEvent created and called just before the JobPlanningLineInvoice.Insert(); is called... it will need to have the JobPlanningLineInvoice as a var and also contain the PostingDate variable if possible.
Something like this...

    [IntegrationEvent(false, false)]
    local procedure OnBeforeJobPlanningLineInvoiceInsert(var JobPlanningLineInvoice: Record "Job Planning Line Invoice"; PostingDate: Date)
    begin
    end;

Thank you,
Elmar Vidisson

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
