### ISSUE TITLE
[Event Request] Codeunit 5895 - Inventory Adjustment - OnAfterItemJnlPostLineRunWithCheck

### ISSUE THREAD

**Issue by Gitulf** [microsoft/ALAppExtensions#16475]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher PostItemJnlLineto be added to Codeunit 5895 - Inventory Adjustment Reverse with the following signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterItemJnlPostLineRunWithCheck(var ItemJournalLine: Record "Item Journal Line"; ValueEntry: Record "Value Entry")
    begin
    end;

with VAR parameter ItemJournalLine.
which would be called as follows from PostItemJnlLine

    local procedure PostItemJnlLine(ItemJnlLine: Record "Item Journal Line"; OrigValueEntry: Record "Value Entry"; NewAdjustedCost: Decimal; NewAdjustedCostACY: Decimal)
    var
        InvtPeriod: Record "Inventory Period";
        l_UserSetup: Record "User Setup";
        l_PostingAllowed: Boolean;
    begin
        with OrigValueEntry do begin

            if not SkipUpdateJobItemCost and ("Job No." <> '') then
                CopyJobToAdjustmentBuf("Job No.");

            OnPostItemJnlLineCopyFromValueEntry(ItemJnlLine, OrigValueEntry);
            ItemJnlPostLine.RunWithCheck(ItemJnlLine);
            OnAfterItemJnlPostLineRunWithCheck(ItemJnlLine, OrigValueEntry);
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
