### ISSUE TITLE
[Event Request] Codeunit 17 - Gen. Jnl.-Post Reverse - OnReverseGLEntryOnAfterInsertGLEntry

### ISSUE THREAD

**Issue by Gitulf** [microsoft/ALAppExtensions#16473]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher PostItemJnlLineto be added to Codeunit 17 - Gen. Jnl.-Post Reverse with the following signature:

    [IntegrationEvent(false, false)] 
    local procedure OnReverseGLEntryOnAfterInsertGLEntry(VAR GLEntry : Record "G/L Entry";GenJournalLine : Record "Gen. Journal Line",GLEntry2: Record "G/L Entry")
    begin
    end;

with VAR parameter GLEntry.
which would be called as follows from ReverseGLEntry:

    local procedure ReverseGLEntry(var GLEntry2: Record "G/L Entry"; var GenJnlLine: Record "Gen. Journal Line"; var TempCustLedgEntry: Record "Cust. Ledger Entry" temporary; var TempVendLedgEntry: Record "Vendor Ledger Entry" temporary; var TempEmployeeLedgerEntry: Record "Employee Ledger Entry" temporary; var TempBankAccLedgEntry: Record "Bank Account Ledger Entry" temporary; var NextDtldCustLedgEntryEntryNo: Integer; var NextDtldVendLedgEntryEntryNo: Integer; var NextDtldEmplLedgEntryNo: Integer; FAInsertLedgerEntry: Codeunit "FA Insert Ledger Entry")
    var
        GLEntry: Record "G/L Entry";
        ReversedGLEntry: Record "G/L Entry";
        l_DialogManagement: Codeunit "MSU DialogManagement";
    begin
        with GLEntry2 do
            if Find('+') then
                repeat
                
                
                    OnReverseGLEntryOnBeforeInsertGLEntry(GLEntry, GenJnlLine, GLEntry2);
                    GenJnlPostLine.InsertGLEntry(GenJnlLine, GLEntry, false);
                    OnReverseGLEntryOnAfterInsertGLEntry(GLEntry, GenJnlLine, GLEntry2);

                    case true of
                        TempCustLedgEntry.Get("Entry No."):

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
