### ISSUE TITLE
[Event Request] Codeunit 7000005 "Invoice-Split Payment"- Add new parameter in OnAfterSplitSalesInvCalculateAmounts()

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16479]
Hello,
We would need a new parameters in the event OnAfterSplitSalesInvCalculateAmounts().

Resulting event:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSplitSalesInvCalculateAmounts(var GenJournalLine: Record "Gen. Journal Line"; var SalesHeader: Record "Sales Header"; var RemainingAmount: Decimal; var RemainingAmountLCY: Decimal; Installment: Record Installment; CurrDocNo: Integer; PaymentTerms: Record "Payment Terms");
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
