### ISSUE TITLE
[Event Request] Table 6660 "Return Receipt Header" - SetSecurityFilterOnRespCenter Function

### ISSUE THREAD

**Issue by plinto97** [microsoft/ALAppExtensions#16472]
Hello, I would like to ask you to add new event OnBeforeSetSecurityFilterOnRespCenter in table 6660 "Return Receipt Header" in procedure SetSecurityFilterOnRespCenter. Thank you
![1](https://user-images.githubusercontent.com/98730800/155674702-d49915c0-8a4f-47ca-9a3a-a9efe37f7937.PNG)
![2](https://user-images.githubusercontent.com/98730800/155674705-acfaf0f7-bea2-4249-ac8e-3c3be3eb9bd9.PNG)
.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
