### ISSUE TITLE
[Event Request] Table 23 Vendor - Add new parameter in OnBeforeVATRegistrationValidation()

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16477]
Hello,
We would need a new parameters in the event OnBeforeVATRegistrationValidation().

Resulting event:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeVATRegistrationValidation(var Vendor: Record Vendor; var IsHandled: Boolean; CurrFieldNo: Integer)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
