### ISSUE TITLE
[EventRequest] Codeunit 410 "Update Analysis View"

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16486]
Please add IncludeSender to the event OnBeforeUpdateEntriesForGLAccount

```
[IntegrationEvent(true, false)]
local procedure OnBeforeUpdateEntriesForGLAccount(var TempAnalysisViewEntry: Record "Analysis View Entry" temporary; AnalysisView: Record "Analysis View"; LastGLEntryNo: Integer; var NoOfEntries: Integer; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
