### ISSUE TITLE
[VariableFunction] Codeunit 410 "Update Analysis View"

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16487]
Please change local procedures to global:
- UpdateAnalysisViewEntry
- UpdateWindowCounter

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
