### ISSUE TITLE
[Event Request] codeunit 6620 "Copy Document Mtg."

### ISSUE THREAD

**Issue by djuras1** [microsoft/ALAppExtensions#16485]
Please add 'OnCopySalesDocOnAfterCopySalesDocUpdateHeader' publisher into the position below.

procedure CopySalesDoc(FromDocType: Enum "Sales Document Type From"; FromDocNo: Code[20]; var ToSalesHeader: Record "Sales Header")
...
if IncludeHeader then
                CopySalesDocUpdateHeader(
                    FromDocType, FromDocNo, ToSalesHeader, FromSalesHeader,
                    FromSalesShptHeader, FromSalesInvHeader, FromReturnRcptHeader, FromSalesCrMemoHeader, 
                    FromSalesHeaderArchive, ReleaseDocument)
                    OnCopySalesDocOnAfterCopySalesDocUpdateHeader(ToSalesHeader, FromSalesInvHeader, FromDocType); // --> NEW EVENT
            else
                OnCopySalesDocWithoutHeader(ToSalesHeader, FromDocType.AsInteger(), FromDocNo, FromDocOccurrenceNo, FromDocVersionNo);

            LinesNotCopied := 0;
            ErrorMessageMgt.Activate(ErrorMessageHandler);
            ErrorMessageMgt.PushContext(ErrorContextElement, RecordId, 0, StrSubstNo(SalesErrorContextMsg, FromDocNo));
...

[IntegrationEvent(false, false)]
local procedure OnCopySalesDocOnAfterCopySalesDocUpdateHeader(FromDocType: Enum; var ToSalesHeader: Record "Sales Header"; var FromSalesInvHeader: Record "Sales Invoice Header" )
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
