### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" - Add new parameter in OnAfterSalesInvHeaderInsert()

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16482]
Hello,
We would need a new parameters in the event OnAfterSalesInvHeaderInsert().

Resulting event:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSalesInvHeaderInsert(var SalesInvHeader: Record "Sales Invoice Header"; SalesHeader: Record "Sales Header"; CommitIsSuppressed: Boolean; WhseShip: Boolean; WhseReceive: Boolean; var TempWhseShptHeader: Record "Warehouse Shipment Header"; var TempWhseRcptHeader: Record "Warehouse Receipt Header"; PreviewMode: Boolean);
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
