### ISSUE TITLE
[Event Request] Codeunit 5807 "Item Charge Assgnt. (Sales)" - Add new parameter in OnBeforeAssignItemCharges()

### ISSUE THREAD

**Issue by XeMaTT** [microsoft/ALAppExtensions#16481]
Hello,
We would need a new parameters in the event OnBeforeAssignItemCharges().

Resulting event:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssignItemCharges(var SalesLine: Record "Sales Line"; TotalQtyToAssign: Decimal; TotalAmtToAssign: Decimal; var IsHandled: Boolean; SelectionTxt: Text)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
