### ISSUE TITLE
[Event Request] Codeunit 8 AccSchedManagement.OnDrillDownOnGLAccountOnBeforeCopyFiltersEmptyAnalysisViewName

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16491]
Please add parametr var GLAcc: Record "G/L Account" to the event

[IntegrationEvent(false, false)]
local procedure OnDrillDownOnGLAccountOnBeforeCopyFiltersEmptyAnalysisViewName(var AccScheduleLine: Record "Acc. Schedule Line"; var TempColumnLayout: Record "Column Layout"; var GLAcc: Record "G/L Account")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
