### ISSUE TITLE
[EventRequest] Codeunit 8 AccSchedManagement.DrillDownOnGLAccCatFilter

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#16492]
Please add event

    local procedure DrillDownOnGLAccCatFilter(TempColumnLayout: Record "Column Layout" temporary; var AccScheduleLine: Record "Acc. Schedule Line"; SubcategoryEntryFilter: Text)
    var
        GLAcc: Record "G/L Account";
        GLAccAnalysisView: Record "G/L Account (Analysis View)";
        CostType: Record "Cost Type";
        ChartOfAccsAnalysisView: Page "Chart of Accs. (Analysis View)";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeDrillDownOnGLAccount(TempColumnLayout, AccScheduleLine, IsHandled);
        if IsHandled then
            exit;

        with AccScheduleLine do
            if "Totaling Type" in ["Totaling Type"::"Cost Type", "Totaling Type"::"Cost Type Total"] then begin
                SetCostTypeRowFilters(CostType, AccScheduleLine, TempColumnLayout);
                SetCostTypeColumnFilters(CostType, AccScheduleLine, TempColumnLayout);
                CopyFilter("Cost Center Filter", CostType."Cost Center Filter");
                CopyFilter("Cost Object Filter", CostType."Cost Object Filter");
                CopyFilter("Cost Budget Filter", CostType."Budget Filter");
                CostType.FilterGroup(2);
                CostType.SetFilter("Cost Center Filter", GetDimTotalingFilter(1, "Cost Center Totaling"));
                CostType.SetFilter("Cost Object Filter", GetDimTotalingFilter(1, "Cost Object Totaling"));
                CostType.FilterGroup(8);
                CostType.SetFilter("Cost Center Filter", GetDimTotalingFilter(1, TempColumnLayout."Cost Center Totaling"));
                CostType.SetFilter("Cost Object Filter", GetDimTotalingFilter(1, TempColumnLayout."Cost Object Totaling"));
                CostType.FilterGroup(0);
                PAGE.Run(PAGE::"Chart of Cost Types", CostType);
            end else begin
                CopyFilter("Business Unit Filter", GLAcc."Business Unit Filter");
                CopyFilter("G/L Budget Filter", GLAcc."Budget Filter");
                SetGLAccRowFilters(GLAcc, AccScheduleLine);
                SetGLAccColumnFilters(GLAcc, AccScheduleLine, TempColumnLayout);
                AccSchedName.Get("Schedule Name");
                if AccSchedName."Analysis View Name" = '' then begin
                    OnDrillDownOnGLAccountOnBeforeCopyFiltersEmptyAnalysisViewName(AccScheduleLine, TempColumnLayout);
                    CopyFilter("Dimension 1 Filter", GLAcc."Global Dimension 1 Filter");
                    CopyFilter("Dimension 2 Filter", GLAcc."Global Dimension 2 Filter");
                    CopyFilter("Business Unit Filter", GLAcc."Business Unit Filter");
                    GLAcc.FilterGroup(2);
                    GLAcc.SetFilter("Global Dimension 1 Filter", GetDimTotalingFilter(1, "Dimension 1 Totaling"));
                    GLAcc.SetFilter("Global Dimension 2 Filter", GetDimTotalingFilter(2, "Dimension 2 Totaling"));
                    GLAcc.FilterGroup(8);
                    GLAcc.SetFilter("Business Unit Filter", TempColumnLayout."Business Unit Totaling");
                    GLAcc.SetFilter("Global Dimension 1 Filter", GetDimTotalingFilter(1, TempColumnLayout."Dimension 1 Totaling"));
                    GLAcc.SetFilter("Global Dimension 2 Filter", GetDimTotalingFilter(2, TempColumnLayout."Dimension 2 Totaling"));
                    if SubcategoryEntryFilter <> '' then begin
                        GlAcc.SetRange("Account Type", GlAcc."Account Type"::Posting);
                        GLAcc.SetFilter("Account Subcategory Entry No.", SubcategoryEntryFilter);
                    end;
                    GLAcc.FilterGroup(0);
                    PAGE.Run(PAGE::"Chart of Accounts (G/L)", GLAcc)
                end else begin
                    //-------------------------------OnDrillDownOnGLAccountOnBeforeCopyFiltersWithAnalysisView:BEGIN
                    OnDrillDownOnGLAccountOnBeforeCopyFiltersWithAnalysisView(AccScheduleLine, TempColumnLayout, GLAcc);
                    //-------------------------------OnDrillDownOnGLAccountOnBeforeCopyFiltersWithAnalysisView:END
                    GLAcc.CopyFilter("Date Filter", GLAccAnalysisView."Date Filter");
                    GLAcc.CopyFilter("Budget Filter", GLAccAnalysisView."Budget Filter");
                    GLAcc.CopyFilter("Business Unit Filter", GLAccAnalysisView."Business Unit Filter");
                    GLAccAnalysisView.SetRange("Analysis View Filter", AccSchedName."Analysis View Name");
                    GLAccAnalysisView.CopyDimFilters(AccScheduleLine);
                    GLAccAnalysisView.FilterGroup(2);
                    GLAccAnalysisView.SetDimFilters(
                      GetDimTotalingFilter(1, "Dimension 1 Totaling"), GetDimTotalingFilter(2, "Dimension 2 Totaling"),
                      GetDimTotalingFilter(3, "Dimension 3 Totaling"), GetDimTotalingFilter(4, "Dimension 4 Totaling"));
                    GLAccAnalysisView.FilterGroup(8);
                    GLAccAnalysisView.SetDimFilters(
                      GetDimTotalingFilter(1, TempColumnLayout."Dimension 1 Totaling"),
                      GetDimTotalingFilter(2, TempColumnLayout."Dimension 2 Totaling"),
                      GetDimTotalingFilter(3, TempColumnLayout."Dimension 3 Totaling"),
                      GetDimTotalingFilter(4, TempColumnLayout."Dimension 4 Totaling"));
                    GLAccAnalysisView.SetFilter("Business Unit Filter", TempColumnLayout."Business Unit Totaling");
                    GLAccAnalysisView.FilterGroup(0);
                    Clear(ChartOfAccsAnalysisView);
                    ChartOfAccsAnalysisView.InsertTempGLAccAnalysisViews(GLAcc);
                    ChartOfAccsAnalysisView.SetTableView(GLAccAnalysisView);
                    ChartOfAccsAnalysisView.Run();
                end;
            end;
    end;
    
    [IntegrationEvent(false, false)]
    local procedure OnDrillDownOnGLAccountOnBeforeCopyFiltersWithAnalysisView(var AccScheduleLine: Record "Acc. Schedule Line"; var TempColumnLayout: Record "Column Layout"; var GLAcc: Record "G/L Account")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
