### ISSUE TITLE
[EventRequest] codeunit 1011 "Job Jnl.-Check Line".RunCheck - OnBeforeCheckJobJnlLine 

### ISSUE THREAD

**Issue by navaddict** [microsoft/ALAppExtensions#16494]
Code snippet:

procedure RunCheck(var JobJnlLine: Record "Job Journal Line")
    begin
        OnBeforeRunCheck(JobJnlLine);

        with JobJnlLine do begin
            if EmptyLine then
                exit;

            TestJobJnlLine(JobJnlLine);
            TestJobStatusOpen(JobJnlLine);
            CheckPostingDate(JobJnlLine);
            CheckDocumentDate(JobJnlLine);

**//BEGIN-ADDCODE +
            IsHandled := false;
            OnBeforeCheckJobJnlLine(JobJnlLine, IsHandled);
            if not IsHandled then
//END-ADDCODE -**
            if "Time Sheet No." <> '' then
                TimeSheetMgt.CheckJobJnlLine(JobJnlLine);

//START ADD-NEW-INTEGRATIONEVENT +

[IntegrationEvent(false, false)]
local procedure OnBeforeCheckJobJnlLine( var JobJnlLine: Record "Job Journal Line"; var IsHandled: Boolean)
begin
end;
//END ADD-NEW-INTEGRATIONEVENT -

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
