### ISSUE TITLE
[EventRequest] Codeunit 212 ResJnlPostLine.Code() - OnBeforePostTimeSheetDetail

### ISSUE THREAD

**Issue by navaddict** [microsoft/ALAppExtensions#16493]
Code snippet showing where to add the new event:

            ...
            ResLedgEntry."User ID" := UserId;
            ResLedgEntry."Entry No." := NextEntryNo;
            ResUOM.Get(ResLedgEntry."Resource No.", ResLedgEntry."Unit of Measure Code");
            if ResUOM."Related to Base Unit of Meas." then
                ResLedgEntry."Quantity (Base)" := ResLedgEntry.Quantity * ResLedgEntry."Qty. per Unit of Measure";

            if ResLedgEntry."Entry Type" = ResLedgEntry."Entry Type"::Usage then begin

                **//START ADD-NEW-CODE +**
                IsHandled := false;
                OnBeforePostTimeSheetDetail(ResJnlLine, IsHandled);
                if not IsHandled then
                **//END ADD-NEW-CODE -**

                PostTimeSheetDetail(ResJnlLine, ResLedgEntry."Quantity (Base)");
                ResLedgEntry.Chargeable := IsChargable(ResJnlLine, ResLedgEntry.Chargeable);
            end;

  **//START ADD-NEW-INTEGRATIONEVENT +**

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostTimeSheetDetail( var ResJournalLine: Record "Res. Journal Line"; var IsHandled: Boolean)
    begin
    end;

  **//END ADD-NEW-INTEGRATIONEVENT -**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
