### ISSUE TITLE
[Event Request] Table 167 - Job - OnBeforeDeleteJobTasks

### ISSUE THREAD

**Issue by programmierenlol** [microsoft/ALAppExtensions#16504]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher OnBeforeDeleteJobTasks be added to Table 167 - Job with the following signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteJobTasks(var Job: Record Job; var xJob: Record Job; var IsHandled: Boolean)
    begin
    end;

with VAR parameter Job.
which would be called as follows from OnDelete in Table 167 - Job:

    trigger OnDelete()
    var
        JobTask: Record "Job Task";
        IsHandled: Boolean;
    begin
        MoveEntries.MoveJobEntries(Rec);

        OnBeforeDeleteJobTasks(Rec, xRec, IsHandled);
        if Not IsHandled then begin
           JobTask.SetCurrentKey("Job No.");
           JobTask.SetRange("Job No.", "No.");
           JobTask.DeleteAll(true);
        end;

        CommentLine.SetRange("Table Name", CommentLine."Table Name"::Job);
        CommentLine.SetRange("No.", "No.");
        CommentLine.DeleteAll();

        DimMgt.DeleteDefaultDim(DATABASE::Job, "No.");

        if "Project Manager" <> '' then
            RemoveFromMyJobs();
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
