### ISSUE TITLE
[Event request] table 36 "Sales Header" - OnBeforeValidateSellToEmail

### ISSUE THREAD

**Issue by DavidRoys** [microsoft/ALAppExtensions#16507]
Hi there,

Please add this IsHandled Event to the "Sales Header" table.

![image](https://user-images.githubusercontent.com/6288989/156110579-894b84bc-854b-4d18-bc39-2ade280dc51d.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
