### ISSUE TITLE
[Event Change] Codeunit 99000832 "Sales Line-Reserve", OnBeforeVerifyQuantity

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#16519]
Hi Team,

could you please add parameter **OldSalesLine** to publisher **OnBeforeVerifyQuantity** in codeunit **Sales Line-Reserve**

Current definition:
``` AL
[IntegrationEvent(false, false)]
local procedure OnBeforeVerifyQuantity(var NewSalesLine: Record "Sales Line"; var IsHandled: Boolean)
begin
end;
```

Requested definition:
``` AL
[IntegrationEvent(false, false)]
local procedure OnBeforeVerifyQuantity(var NewSalesLine: Record "Sales Line"; var OldSalesLine: Record "Sales Line"; var IsHandled: Boolean)
begin
end;
```

Publisher is triggered in procedure **VerifyQuantity**
``` AL
procedure VerifyQuantity(var NewSalesLine: Record "Sales Line"; var OldSalesLine: Record "Sales Line")
    var
        SalesLine: Record "Sales Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeVerifyQuantity(NewSalesLine, IsHandled);
        // OnBeforeVerifyQuantity(NewSalesLine, OldSalesLine, IsHandled); // Requested definition
        if IsHandled then
            exit;
...
```

Thanks in advance,
Christian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
