### ISSUE TITLE
[Event Request] Table 5065 "Interaction Log Entry" - OnAfterLookupToDoNo

### ISSUE THREAD

**Issue by monicasuica** [microsoft/ALAppExtensions#16518]
Hello,

We would like to request the following event in the OnLookup trigger of the To-Do No. field on table Table 5065 "Interaction Log Entry".

```
 trigger OnLookup()
 begin
      OnAfterLookupToDoNo(Rec); 
  end;
```

```    
local procedure OnAfterLookupToDoNo(InteractionLogEntry: Record "Interaction Log Entry")
begin
end;
```

In our solution there are some situations in which the another page should open.
Thank you in advance for your consideration.

**Comment by Oleg-Romashkov** [comment]
We cannot realize empty Lookup trigger because it breaks internal lookup based on TableRelation property.
