### ISSUE TITLE
CU 1520 Workflow Event Handling and the Uppercase function in Turkish Language

### ISSUE THREAD

**Issue by daryobahar** [microsoft/ALAppExtensions#16529]
Dear Team Members,

The issue I will try to describe is related to the Turkish Language, and the letters i, I, and I.

As you know, in English, the upper case for the letter "i" is "I". On the other hand in Turkish Language, the uppercase for "i" is not "I" but "İ" with a dot on top.

The function uppercase works perfect in this sence.

But when it comes to the usage codeunit 1520 "Workflow Event Handling", this brings about a problem.

Consider the following function.

  _procedure RunWorkflowOnAfterInsertGeneralJournalLineCode(): Code[128]
    begin
        exit(UpperCase('RunWorkflowOnAfterInsertGeneralJournalLine'));
    end;_

In the function below, if BC is run in English language, the return value is "RUNWORKFLOWONAFTERINSERTGENERALJOURNALLINE" and and the program works perfect.

But if it is run in Turkish language, the return value is "RUNWORKFLOWONAFTERINSERTGENERALJOURNALLİNE" (note the dot on "İ" in the word "LİNE" at the end), the program fails and interrupts with an error message saying that **"RUNWORKFLOWONAFTERINSERTGENERALJOURNALLİNE" is not found.**

Our suggested solution is changing the **exit** line as exit(RUNWORKFLOWONAFTERINSERTGENERALJOURNALLINE) instead of using the uppercase for a hard coded text string. (not only in this function but for all similar functions)

But if there is something we are missing and if our suggestion doesn't work, then our suggestion will be adding event publishers before the exit. Such as:

  _procedure RunWorkflowOnAfterInsertGeneralJournalLineCode(): Code[128]
    var
        FunctionName: Code[128]
    begin
        FunctionName := UpperCase('RunWorkflowOnAfterInsertGeneralJournalLine')
        OnAfterUpperCaseRunWorkflowOnAfterInsertGeneralJournalLine(FunctionName) ---> event where the FunctionName variable can be modified
        exit(FunctionName );
    end;_

Or maybe an easier solution is modifying the event publisher in codeunit 1501 "Workflow Management" as follows

 _[IntegrationEvent(false, false)]
    local procedure OnBeforeHandleEventWithxRec(**var** FunctionName: Code[128]; Variant: Variant; xVariant: Variant; var IsHandled: Boolean)
    begin
    end;_

Thank you for your support in solving such issues.

Kindest regards

Daryo Bahar
Infotek Yazilim ve Donanim Hizmetleri A.S.
Istanbul - Turkey

**Comment by StanPesotskiy** [comment]
Duplicate to #14950
