### ISSUE TITLE
DotNet string normalization

### ISSUE THREAD

**Issue by makovickanavisys** [microsoft/ALAppExtensions#16521]
- AL Extension Version: v8.4.586670
- Server Version: W1 19.3 (Platform 19.0.34506.35154 + Application 19.3.34541.35210)

We have a function, that should strip diacritics from a string (e.g. convert "Kód příčiny" to "Kodpriciny"), but it does not work (and returns "Kódpříčiny" instead). See the sample below - the "Normalize" part is not working as intended and changing NormalizationForm to another does not help either.

    procedure GetSPName(_InputName: Text): Text
    var
        NormalizationForm: Codeunit DotNet_NormalizationForm;
        TextToChange: Codeunit DotNet_String;
    begin
        NormalizationForm.FormD();
        TextToChange.Set(_InputName);
        _InputName := TextToChange.Normalize(NormalizationForm);
        exit(DelChr(DelChr(_InputName), '=', '.@$#%^&*()! -'));
    end;

Can you please explain where the issue might be or propose another way how to strip diacritics from a string?

**Comment by makovickanavisys** [comment]
Hello, any news about the issue?

**Comment by darjoo** [comment]
Hi @makovickanavisys, does this actually work in a C# project? Normalize does not seem to work as you suggest.
Normalization FormC gets close but not all the way and FormD is even further.

I had found something that does work but we don't expose the CharUnicodeInfo dotnet class unfortunately.
http://archives.miloush.net/michkap/archive/2007/05/14/2629747.html

**Comment by darjoo** [comment]
Closing this issue for now. 
Feel free to reopen the issue when you have more information :)
