### ISSUE TITLE
[Event Request] Codeunit 1001 - JobPostLine - OnBeforePostJobOnPurchaseLine

### ISSUE THREAD

**Issue by Gitulf** [microsoft/ALAppExtensions#16527]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher OnBeforePostGenJournalLine be added to Codeunit 1001 JobPostLine with the following signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostGenJournalLine(var JobJournalLine: Record "Job Journal Line"; GenJnlLine: Record "Gen. Journal Line"; GLEntry : Record "G/L Entry"; var IsHandled: Boolean)
    begin
    end;

with VAR parameter JobJournalLine and IsHandled.
which would be called as follows from PostGenJnlLine:

    procedure PostGenJnlLine(GenJnlLine: Record "Gen. Journal Line"; GLEntry: Record "G/L Entry")
    var
        JobJnlLine: Record "Job Journal Line";
        Job: Record Job;
        JobTask: Record "Job Task";
        SourceCodeSetup: Record "Source Code Setup";
        JobTransferLine: Codeunit "Job Transfer Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePostGenJournalLine(JobJnlLine, GenJnlLine, GLEntry, IsHandled);
        if IsHandled then
            exit;        
        if GenJnlLine."System-Created Entry" then
            exit;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
