### ISSUE TITLE
Table 81 OnBeforeGetAppliesToDocCustLedgEntry

### ISSUE THREAD

**Issue by Athon-dev** [microsoft/ALAppExtensions#16528]
We need to add a new filter after Document Number filter: "CustLedgEntry.SETRANGE("Document Occurrence","Applies-to Occurrence No.");"
    
local procedure GetAppliesToDocCustLedgEntry(var CustLedgEntry: Record "Cust. Ledger Entry"; AccNo: Code[20])

    begin

        OnBeforeGetAppliesToDocCustLedgEntry()

        if handle then

            exit;

           

        CustLedgEntry.SetRange("Customer No.", AccNo);

        CustLedgEntry.SetRange(Open, true);

        if "Applies-to Doc. No." <> '' then begin

            CustLedgEntry.SetRange("Document Type", "Applies-to Doc. Type");

            CustLedgEntry.SetRange("Document No.", "Applies-to Doc. No.");

            if CustLedgEntry.FindFirst then;

        end else

            if "Applies-to ID" <> '' then begin

                CustLedgEntry.SetRange("Applies-to ID", "Applies-to ID");

                if CustLedgEntry.FindFirst then;

            end;

    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
