### ISSUE TITLE
New integration Event in Codeunit 228 "Test Report-Print"

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#16523]
Hello 
we need an event for an extension in procedure PrintGenJnlLine
bevore REPORT.RUN

procedure PrintGenJnlLine(var NewGenJnlLine: Record "Gen. Journal Line")
    var
        IsHandled: Boolean;
    begin
        GenJnlLine.Copy(NewGenJnlLine);
        OnPrintGenJnlLineOnAfterGenJnlLineCopy(GenJnlLine);
        GenJnlLine.SetRange("Journal Template Name", GenJnlLine."Journal Template Name");
        GenJnlLine.SetRange("Journal Batch Name", GenJnlLine."Journal Batch Name");
        GenJnlTemplate.Get(GenJnlLine."Journal Template Name");

        IsHandled := false;
        OnBeforeReportRun(GenJnlLine, IsHandled);
        if IsHandled then
            exit;

        GenJnlTemplate.TestField("Test Report ID");
        REPORT.Run(GenJnlTemplate."Test Report ID", true, false, GenJnlLine);
    end;

And the IntegrationEvent

[IntegrationEvent(false, false)]
    local procedure OnBeforeReportRun(var GenJnlLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
