### ISSUE TITLE
[Event Request] Codeunit 8907 "Email Viewer", OnBeforeCheckPermission

### ISSUE THREAD

**Issue by es-mh** [microsoft/ALAppExtensions#16524]
Hello,

We would like to request the following event in the procedure CheckPermission in Codeunit 8907 "Email Viewer"

procedure CheckPermissions(SentEmail: Record "Sent Email")
    begin
        **IsHandled := false;
        OnBeforeCheckPermission(SentEmail, IsHandled);
        if IsHandled then
            exit;**

        if IsNullGuid(SentEmail."User Security Id") then
            exit;

        if SentEmail."User Security Id" = UserSecurityId() then
            exit;

        Error(EmailMessageOpenPermissionErr);
    end;

We would like to add the possibility to view all Emails for some users, regardless the UserSecurityId of the Sent Email

Many thanks and best Regards,
Michael

**Comment by JesperSchulz** [comment]
You won't need this event for that. With version 20, we are introducing Email View Policies, where you can configure that certain users can read all emails.
