### ISSUE TITLE
Table 349 - OnBeforeCostAccSetup - Event Request

### ISSUE THREAD

**Issue by Athon-dev** [microsoft/ALAppExtensions#16525]
Create an event OnBeforeCostAccSetup in procedure trigger OnInsert(). I need to skip both functions UpdateCostCenterFromDim and UpdateCostObjectFromDim.

    trigger OnInsert()
    begin
        TestField("Dimension Code");
        TestField(Code);
        "Global Dimension No." := GetGlobalDimensionNo;

       OnBeforeCostAccSetup(Rec,Handle)
        if Handle then
            if CostAccSetup.Get then begin
                CostAccMgt.UpdateCostCenterFromDim(Rec, Rec, 0);
                CostAccMgt.UpdateCostObjectFromDim(Rec, Rec, 0);
            end;

        DimMgt.AddDefaultDimensionAllowedDimensionValue(Rec);
        SetLastModifiedDateTime;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
