### ISSUE TITLE
New IntegrationEvent and adjustments in codeunit 6620 "Copy Document Mgt."

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#16522]
Hello for an extension of codeunit 6620 "Copy Document Mgt." we need the following adjustments.

add another Record Variable FromSalesInvHeader: Record "Sales Invoice Header"  in procedure OnAfterCopySalesLineFromSalesLineBuffer
[IntegrationEvent(false, false)]
    local procedure OnAfterCopySalesLineFromSalesLineBuffer(var ToSalesLine: Record "Sales Line"; FromSalesInvLine: Record "Sales Invoice Line"; IncludeHeader: Boolean; RecalculateLines: Boolean; var TempDocSalesLine: Record "Sales Line" temporary; ToSalesHeader: Record "Sales Header"; FromSalesLineBuf: Record "Sales Line"; var FromSalesLine2: Record "Sales Line"; FromSalesLine: Record "Sales Line"; ExactCostRevMandatory: Boolean; FromSalesInvHeader: Record "Sales Invoice Header")

add another Record Variable  FromSalesLine: Record "Sales Line"  in procedure  OnAfterCopySalesLineFromSalesCrMemoLineBuffer
[IntegrationEvent(false, false)]
    local procedure OnAfterCopySalesLineFromSalesCrMemoLineBuffer(var ToSalesLine: Record "Sales Line"; FromSalesCrMemoLine: Record "Sales Cr.Memo Line"; IncludeHeader: Boolean; RecalculateLines: Boolean; var TempDocSalesLine: Record "Sales Line" temporary; ToSalesHeader: Record "Sales Header"; FromSalesLineBuf: Record "Sales Line"; FromSalesLine: Record "Sales Line")

add the following Record Variable 
ToPurchHeader: Record "Purchase Header"; FromPurchInvLine: Record "Purch. Inv. Line"; FromPurchCrMemoLine: Record "Purch. Cr. Memo Line"   in
[IntegrationEvent(false, false)]
    local procedure OnAfterCopyPurchLinesToBufferFields(var TempPurchaseLine: Record "Purchase Line" temporary; FromPurchaseLine: Record "Purchase Line"; FromPurchLine: Record "Purchase Line"; ToPurchHeader: Record "Purchase Header"; FromPurchInvLine: Record "Purch. Inv. Line"; FromPurchCrMemoLine: Record "Purch. Cr. Memo Line")

add another Record Variable  var FromPurchCrMemoLine: Record "Purch. Cr. Memo Line"  in procedure 
 OnCopyPurchCrMemoLinesToDocOnAfterTransferFields
[IntegrationEvent(false, false)]
    local procedure OnCopyPurchCrMemoLinesToDocOnAfterTransferFields(var FromPurchaseLine: Record "Purchase Line"; var FromPurchaseHeader: Record "Purchase Header"; var ToPurchaseHeader: Record "Purchase Header"; var FromPurchCrMemoHdr: Record "Purch. Cr. Memo Hdr."; var FromPurchCrMemoLine: Record "Purch. Cr. Memo Line")

add another Variable  RecalculateLines: Boolean  in procedure OnAfterSetDefaultValuesToSalesLine
[IntegrationEvent(false, false)]
    local procedure OnAfterSetDefaultValuesToSalesLine(var ToSalesLine: Record "Sales Line"; ToSalesHeader: Record "Sales Header"; CreateToHeader: Boolean)

New IntegrationEvent
OnAfterCopyPurchCrMemoLines(TempDocPurchaseLine, ToPurchHeader, FromPurchLineBuf, FromPurchCrMemoLine);
after CopyPurchLinesToBuffer in Procedure CopyPurchCrMemoLinesToDoc
-
[IntegrationEvent(false, false)]
    local procedure OnAfterCopyPurchCrMemoLines(var TempDocPurchaseLine: Record "Purchase Line" temporary; var ToPurchHeader: Record "Purchase Header"; var FromPurchLineBuf: Record "Purchase Line"; var FromPurchCrMemoLine: Record "Purch. Cr. Memo Line")
    begin
    end;

New IntegrationEvent
OnCopySalesReturnRcptLinesToDocOnBeforeCheckInsertDocNoLine(ToSalesHeader, FromReturnRcptLine, FromSalesHeader, NextLineNo, InsertDocNoLine);
After NextLineNo := GetLastToSalesLineNo(ToSalesHeader);  in  Procedure  CopySalesReturnRcptLinesToDoc
-
[IntegrationEvent(false, false)]
    local procedure OnCopySalesReturnRcptLinesToDocOnBeforeCheckInsertDocNoLine(var ToSalesHeader: Record "Sales Header"; FromReturnRcptLine: Record "Return Receipt Line"; FromSalesHeader: Record "Sales Header", var NextLineNo: Integer, var InsertDocNoLine: Boolean)
    begin
    end;

New IntegrationEvent
OnCopySalesShptLinesToDocOnBeforeCheckInsertDocNoLine(ToSalesHeader, FromSalesShptLine, FromSalesHeader, NextLineNo, InsertDocNoLine);
After NextLineNo := GetLastToSalesLineNo(ToSalesHeader);  in  procedure  CopySalesShptLinesToDoc
-
[IntegrationEvent(false, false)]
    local procedure OnCopySalesShptLinesToDocOnBeforeCheckInsertDocNoLine(var ToSalesHeader: Record "Sales Header"; FromSalesShptLine: Record "Sales Shipment Line"; FromSalesHeader: Record "Sales Header"; var NextLineNo: Integer; var InsertDocNoLine: Boolean);
    begin
    end;

New IntegrationEvent
OnCopyPurchReturnShptLinesToDocOnBeforeCheckInsertDocNoLine(ToPurchHeader, FromReturnShptLine, FromPurchHeader, NextLineNo, InsertDocNoLine);
After NextLineNo := GetLastToPurchLineNo(ToPurchHeader); in procedure CopyPurchReturnShptLinesToDoc
[IntegrationEvent(false, false)]
    local procedure OnCopyPurchReturnShptLinesToDocOnBeforeCheckInsertDocNoLine(var ToPurchaseHeader: Record "Purchase Header"; FromReturnShptLine: Record "Return Shipment Line"; FromPurchHeader: Record "Purchase Header"; var NextLineNo: Integer; var InsertDocNoLine: Boolean);
    begin
    end;

**Comment by Oleg-Romashkov** [comment]
Hi,
Please, next time create one request per event.
Put the code surrounding the place, where you expect a new event call, as a text not as a screenshot (not just mentioned single code line as a reference).

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
