### ISSUE TITLE
Tab 349 - OnBeforCostAccSetup - Event Request

### ISSUE THREAD

**Issue by Athon-dev** [microsoft/ALAppExtensions#16530]
We need to skip both functions UpdateCostCenterFromDim and UpdateCostObjectFromDim

    trigger OnRename()
    begin
        RenameBudgEntryDim;
        RenameAnalysisViewEntryDim;
        RenameItemBudgEntryDim;
        RenameItemAnalysisViewEntryDim;

       OnBeforCostAccSetup()
       if handle then
           if CostAccSetup.Get then begin
               CostAccMgt.UpdateCostCenterFromDim(Rec, xRec, 3);
               CostAccMgt.UpdateCostObjectFromDim(Rec, xRec, 3);
           end;

        SetLastModifiedDateTime;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
