### ISSUE TITLE
Extract Code from function SetSellToCustomerFromFilter in Table 36

### ISSUE THREAD

**Issue by RaKuNbg** [microsoft/ALAppExtensions#16533]
Could you please extract the marked piece of code
![image](https://user-images.githubusercontent.com/46022628/156381167-b9d2e49a-9cd9-4398-accb-234e7d95e2a4.png)
to an separate global function with "SellToCustomerNo" as return value so that it can be used to check if there is an single filter on SellToCustomerNo and to do some work with the SellToCustomerNo.

    procedure GetSellToCustomerFromFilter() SellToCustomerNo: Code[20]
    begin
        SellToCustomerNo := GetFilterCustNoKTG;
        if SellToCustomerNo = '' then begin
            FilterGroup(2);
            SellToCustomerNo := GetFilterCustNoKTG;
            if SellToCustomerNo = '' then
                SellToCustomerNo := GetFilterCustNoByApplyingFilterKTG;
            FilterGroup(0);
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
