### ISSUE TITLE
[Event Request] Codeunit 900 Assembly-Post - OnAfterPost

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#16537]
Current Event:

>> OnAfterPost(AssemblyHeader) -- at end of local procedure Post(...)
>> local procedure OnAfterPost(var AssemblyHeader: Record "Assembly Header")

Desired Event:

>> OnAfterPost(AssemblyHeader, AssemblyLine, PostedAssemblyHeader, ItemJnlPostLine, ResJnlPostLine, WhseJnlRegisterLine)
>> local procedure OnAfterPost(var AssemblyHeader: Record "Assembly Header"; var AssemblyLine: Record "Assembly Line"; PostedAssemblyHeader: Record "Posted Assembly Header"; var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line"; var ResJnlPostLine: Codeunit "Res. Jnl.-Post Line"; var WhseJnlRegisterLine: Codeunit "Whse. Jnl.-Register Line")

Thx.

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
