### ISSUE TITLE
[Event Request] table 5965 "Service Contract Header"

### ISSUE THREAD

**Issue by djuras2** [microsoft/ALAppExtensions#16535]
Please add OnServiceContractHeaderOnBeforePrepaidValidate publisher into the position below.

field(45; Prepaid; Boolean)
        {
            Caption = 'Prepaid';

            trigger OnValidate()
            var
                ServLedgEntry: Record "Service Ledger Entry";
            begin
                OnServiceContractHeaderOnBeforePrepaidValidate(Rec, xRec, ServLedgEnrty IsInvoicePeriodInTimeSegment, isHandled) --> NEW EVENT
                if isHandled then // --> NEW ISHANDLED
                       exit;
                if Prepaid <> xRec.Prepaid then begin
                    if "Contract Type" = "Contract Type"::Contract then begin
                        ServLedgEntry.SetCurrentKey("Service Contract No.");
                        ServLedgEntry.SetRange("Service Contract No.", "Contract No.");
                        if not ServLedgEntry.IsEmpty() then
                            Error(
                              Text032,
                              FieldCaption(Prepaid), TableCaption, "Contract No.");
                    end;
                    TestField("Starting Date");
                    if Prepaid then begin
                        if "Invoice after Service" then
                            Error(
                              Text057,
                              FieldCaption("Invoice after Service"),
                              FieldCaption(Prepaid));
                        if "Invoice Period" = "Invoice Period"::None then
                            Validate("Next Invoice Date", 0D)
                        else
                            if IsInvoicePeriodInTimeSegment then
                                if "Starting Date" = CalcDate('<-CM>', "Starting Date") then
                                    Validate("Next Invoice Date", "Starting Date")
                                else
                                    Validate("Next Invoice Date", CalcDate('<-CM+1M>', "Starting Date"));
                    end else
                        Validate("Last Invoice Date");
                end;
            end;

[IntegrationEvent(false, false)]
local procedure OnServiceContractHeaderOnBeforePrepaidValidate (var Rec: Record "Service Contract Header", var xRec: Record "Service Contract Header",var ServLedgEnrty: "Service Ledger Entry", var IsInvoicePeriodInTimeSegment: Boolean, var isHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
