### ISSUE TITLE
Codeunit 90 "Purch.-Post" - OnBeforeDivideAmount

### ISSUE THREAD

**Issue by GijsFranssens** [microsoft/ALAppExtensions#16539]
Event OnBeforeDivideAmount in Codeunit 90 should use the same parameters as 'var' as in Codeunit 80.

Codeunit 90:
`    
[IntegrationEvent(false, false)]
    local procedure OnBeforeDivideAmount(**PurchHeader: Record "Purchase Header"**; var PurchLine: Record "Purchase Line"; QtyType: Option General,Invoicing,Shipping; var PurchLineQty: Decimal; var TempVATAmountLine: Record "VAT Amount Line" temporary; var TempVATAmountLineRemainder: Record "VAT Amount Line" temporary)
    begin
    end;
`
Codeunit 80:
` [IntegrationEvent(false, false)]
    local procedure OnBeforeDivideAmount(**var** SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; QtyType: Option General,Invoicing,Shipping; var SalesLineQty: Decimal; var TempVATAmountLine: Record "VAT Amount Line" temporary; var TempVATAmountLineRemainder: Record "VAT Amount Line" temporary; var IsHandled: Boolean)`

Please also check other integration events..

_Originally posted by @GijsFranssens in https://github.com/microsoft/ALAppExtensions/issues/7219#issuecomment-1054410021_

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
