### ISSUE TITLE
[Event Request] OnAfterValidateGLAccountNo in table 171 "Standard Sales Line"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#16531]
Please add OnAfterValidateGLAccountNo from table table 174 "Standard Purchase Line" also to table 171 "Standard Sales Line":

field(4; "No."; Code[20])
trigger OnValidate()
                case Type of
                    Type::"G/L Account":
                        begin
                            GLAcc.Get("No.");
                            GLAcc.CheckGLAcc;
                            GLAcc.TestField("Direct Posting", true);
                            Description := GLAcc.Name;
OnAfterValidateGLAccountNo(Rec, GLAcc);  <-- new event
                        end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterValidateGLAccountNo(var StandardSalesLine: Record "Standard SalesLine"; GLAccount: Record "G/L Account")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
