### ISSUE TITLE
Error trying to send approval requests in payment journal

### ISSUE THREAD

**Issue by Celicienta** [microsoft/ALAppExtensions#16546]
Dear ALAppExtensions Team,
In Payment Journal, we cannot send approval requests because BC give us an error that page cannot be updated and the transaction cannot found.
The error occurs because an attempt was made to modify the general journal line::

![image](https://user-images.githubusercontent.com/74307312/156752770-9654b896-f8f4-4453-b2e2-defe1cc610f8.png)

In the previous version these lines does not appear.
Are these lines necessary?
Can you create an event before these lines to skip them please?
Thanks.

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix in an update for the current version.
