### ISSUE TITLE
[Event Request] 5705 "TransferOrder-Post Receipt" - OnInsertDirectTransLine_OnBeforePost

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#16540]
We would like to be able to assign extra fields from TransLine to DirectTransLine before the DirectTransLine is inserted/ before the posting is done.

Therefore, can you please add following event publisher

```
OnInsertDirectTransLine_OnBeforePost(DirectTransLine, DirectTransHeader, TransLine)

[IntegrationEvent(false, false)]
    local procedure OnInsertDirectTransLine_OnBeforePost(var DirectTransLine: Record "Direct Trans. Line"; DirectTransHeader: Record "Direct Trans. Header"; TransLine: Record "Transfer Line")
    begin
    end;
```

at this location?

![image](https://user-images.githubusercontent.com/25268332/156529622-3b3c0634-8c4a-4c07-89ef-a6d8dffc4e13.png)

or refactor the fields assignment to a separate function 'CopyFromTransferLine' on the Direct Trans. Line table and foresee a publisher `OnAfterCopyFromTransferLine`...

**Comment by Oleg-Romashkov** [comment]
Hi,
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.
Please, do it next time

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
