### ISSUE TITLE
Page 5522 "Order Planning" - SetDemandOrderFilter

### ISSUE THREAD

**Issue by jaromirchaloupka** [microsoft/ALAppExtensions#16547]
Hello, would that be possible to add new procedure called **SetDemandOrderFilter** into Page 5522 "Order Planning" in order to handle and set _DemandOrderFilter_ variable which is used in this page as source for "Show Demand As" field?

Something like mentioned below which could help us to set the value for DemandOrderFilter from our own extensions:

```
procedure SetDemandOrderFilter(NewDemandOrderFilter: Option "All Demands","Production Demand","Sales Demand","Service Demand","Job Demand","Assembly Demand")
begin
DemandOrderFilter := NewDemandOrderFilter;
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
