### ISSUE TITLE
Request-> New Protected Variables in report 208 "Sales - Shipment"

### ISSUE THREAD

**Issue by Bw-Foodcloud** [microsoft/ALAppExtensions#16544]
Hello,

Is it possible to make _TrackingSpecBuffer_  variable protected in report 208 "Sales - Shipment" please? 

Our business users would like to communicate expiration dates to customers on this report for food safety reasons. 

Many thanks in advance,
Brendan

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
