### ISSUE TITLE
[Request for External] page 408 "G/L Balance by Dimension" - GenerateColumnCaptions

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#16557]
Can you change procedure GenerateColumnCaptions to protected?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
