### ISSUE TITLE
Cannot Rename Price List Line - Line No. is set to AutoIncrement = true

### ISSUE THREAD

**Issue by markborges** [microsoft/ALAppExtensions#16556]
Is there a specific reason why AutoIncrement is set to true on field "Line No." on the Price List Line table?

I'm creating a custom routine that will move price list lines from one header to another (by renaming them), and as I move them to a new header, I would like to have a fresh clean start with the Line Nos. (meaning, starting at 10000, and so on).

However, during renaming, if I try to change the Line No., BC throws an error that Line No. is set to Auto Increment. 

Workaround: Instead of renaming, I need to insert a new line, and delete the old line.

Tks.

**Comment by AlexanderYakunin** [comment]
@StanPesotskiy - please reply

**Comment by RadoArvay** [comment]
> Workaround: Instead of renaming, I need to insert a new line, and delete the old line.
If I understand well, you are moving lines from one header to another one. So, it is not the renaming operation from the view of data and that workaround is a correct way to process data.

**Comment by markborges** [comment]
> > Workaround: Instead of renaming, I need to insert a new line, and delete the old line.
> 
> If I understand well, you are moving lines from one header to another one. So, it is not the renaming operation from the view of data and that workaround is a correct way to process data.

Semantics apart, there's another use case: When you create lines on the Sales Price Lists, Line Nos. are automatically assigned in the 10000s, because the Page is set to AutoSplitKey = true.

As you might know, there's a flaw with the Split Key that it cannot add more than approx 13 lines between 2 lines, because eventually BC runs out of Line Nos. to split.

So, if we want to write a function that will automatically renumber the Line Nos. (by the use of Rename), this is also not possible because of the same issue posed on my first message.

**Comment by StanPesotskiy** [comment]
@markborges the property does put some value if the "Line No." is 0 on insert, but if you put any other value it should be accepted as is and the record will be inserted with this value. There is SetNextLineNo() method (see its usage) that adds 10000 to the last line of the price list. This is used when one price list is copied to another one. 
What error do you see when you try to insert a record with a non-zero "Line No."? I wouldn't expect any.

**Comment by markborges** [comment]
@StanPesotskiy I don't get an error when I try to **INSERT**. I'm getting an error when I try to **RENAME** a record.

For example, I have the first 6 records (out of a bunch), that were created like this because I kept creating new lines between lines 10,000 and 20,000:
```
Price List Code | Line No.
----------------------------
PL0001          | 10000
PL0001          | 10001
PL0001          | 10002
PL0001          | 10004
PL0001          | 10009
PL0001          | 10019
...
```

I would like to now rename these lines, so that I can have room between lines again, in case the user wants to add New lines in the future between 10000 and 10001, or between 10001 and 10002, and so on and so forth. I would like to RENAME my lines to the following sequence:
```
Price List Code | Line No.
----------------------------
PL0001          | 10000
PL0001          | 20000
PL0001          | 30000
PL0001          | 40000
PL0001          | 50000
PL0001          | 60000
```

Right now, because Line No. is set to AutoIncrement = True, if my extension tries to **RENAME** the Price List Line record, I will get the following error message:

```
You cannot change the value of an AutoIncrement field.

Field: Line No.
Table: Price List Line

Identification fields and values:
Price List Code='PL0001',Line No.='60000'
```

**Comment by StanPesotskiy** [comment]
Rename operation makes sense when the renamed record is widely referenced, e.g. table Customer. When you rename customer's "No." it is changed everywhere, where is the table relation to the customer table. If there are no additional tables related to the target table then Delete-Insert is a better approach.

**Comment by markborges** [comment]
I respectfully disagree from this suggestion since a Rename, without any related tables, produces 1 SQL transaction (UPDATE), where Deleting and Inserting produces 2 SQL transactions (DELETE, INSERT).

If I try to run this operation (Delete-Insert) on a Price List with 100 lines, I will get at least 200 SQL transactions. This is really not an optimized operation.

Also, I don't understand why a Line No. field would have the property AutoIncrement set to True, specially when the field is being used on a form with AutoSplitKey, so AutoIncrement definitely adds some unnecessary complexity for extensions being written over the new pricing feature.

With all that said, I mentioned I already have a workaround for this, so, I'll just move on with what I have. I know you guys have bigger fishes to fry with this whole Pricing module that still needs a loooooooot of work.

Tks, I'm closing this issue.
