### ISSUE TITLE
[Event Request] Wrap calls to Dimension Management's EditDimensionSet (with dim fields overload) with event and IsHandled pattern

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#16551]
We have in out solution the need to pass additional information into the Dimension Management's overloaded EditDimensionSet procedure that passes in the two dimension fields.  I have looked at this procedure to possibly add events in it, but it is not possible based on our needs.  There are also other events in some of the procedures that call EditDimensionSet, but we can't use them as we need to;, procedure overriding events (inaccessible local procedures) and events after the procedure call (unable to override the procedure call).

My request is to have the places where the specific overloaded EditDimensionSet call is made to add an event and IsHandled pattern wrapping only the call to this procedure.  Here is an example of the change:

```
table 900 "Assembly Header"
...
    procedure ShowDimensions()
    var
        DimMgt: Codeunit DimensionManagement;
        OldDimSetId: Integer;
        IsHandled: boolean;  // NEW VAR
    begin
        OldDimSetId := "Dimension Set ID";

        // NEW CODE - event and IsHandled check wrapping the call
        OnShowDimensionOnBeforeEditDimensionSet(Rec, IsHandled);
        if not IsHandled then
        // END NEW CODE, next statement indented
            "Dimension Set ID" :=
            DimMgt.EditDimensionSet(
                "Dimension Set ID", StrSubstNo('%1 %2', "Document Type", "No."),
                "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");

        if OldDimSetId <> "Dimension Set ID" then begin
            SetCurrentFieldNum(FieldNo("Dimension Set ID"));
            AssemblyLineMgt.UpdateAssemblyLines(Rec, xRec, FieldNo("Dimension Set ID"), false, CurrFieldNo, CurrentFieldNum);
            ClearCurrentFieldNum(FieldNo("Dimension Set ID"));
            Modify(true);
        end;
    end;

    // NEW EVENT DEFINITION
    [IntegrationEvent(false, false)]
    local procedure OnShowDimensionOnBeforeEditDimensionSet(var AssemblyHeader: Record "Assembly Header"; var IsHandled: Boolean)
    begin
    end;


```
I would prefer that only the procedure be wrapped, as some of the places that it is called from has other code in the procedure that either does not need modification or is local in scope and can't be called from my event handlers without further modifications.

Here is a list of the places (object and procedure name) that the EditDimensionSet procedure with the two dimensions passed in is being called, which I am requesting the change for.  The code changes in each is very similar to the above example in all cases, and these are all the cases I found which I suggest should all be changed for consistency:

table 901 "Assembly Line"
    procedure ShowDimensions()

table 273 "Bank Acc. Reconciliation"
    procedure ShowDocDim()

table 10121 "Bank Rec. Line"
    procedure ShowDimensions()

table 846 "Cash Flow Worksheet Line"
    procedure ShowDimensions()

table 10140 "Deposit Header"
    procedure ShowDocDim()

table 5615 "FA Allocation"
    procedure ShowDimensions()

table 5621 "FA Journal Line"
    procedure ShowDimensions()

table 302 "Finance Charge Memo Header"
    procedure ShowDocDim()

table 221 "Gen. Jnl. Allocation"
    procedure ShowDimensions()

table 5635 "Insurance Journal Line"
    procedure ShowDimensions()

table 5850 "Invt. Document Header"
    procedure ShowDocDim()

table 5851 "Invt. Document Line"
    procedure ShowDimensions()

table 83 "Item Journal Line"
    procedure ShowDimensions()

table 5875 "Phys. Invt. Order Header"
    procedure ShowDocDim()

table 5876 "Phys. Invt. Order Line"
    procedure ShowDimensions()

table 99000829 "Planning Component"
    procedure ShowDimensions()

table 10124 "Posted Bank Rec. Line"
    procedure ShowDimensions()

table 5407 "Prod. Order Component"
    procedure ShowDimensions()

table 5406 "Prod. Order Line"
    procedure ShowDimensions()

table 5405 "Production Order"
    procedure ShowDocDim()

table 295 "Reminder Header"
    procedure ShowDocDim()

table 246 "Requisition Line"
    procedure ShowDimensions()

table 207 "Res. Journal Line"
    procedure ShowDimensions()

table 5965 "Service Contract Header"
    procedure ShowDocDim()

table 5900 "Service Header"
    procedure ShowDocDim()

table 5901 "Service Item Line"
    procedure ShowDimensions()

table 751 "Standard General Journal Line"
    procedure ShowDimensions()

table 753 "Standard Item Journal Line"
    procedure ShowDimensions()

table 5997 "Standard Service Line"
    procedure ShowDimensions()
extra code

table 5740 "Transfer Header"
    procedure ShowDocDim()

This list is like above, but currently (19.4) also has an event/IsHandled pattern that covers the entire procedure, but because of additional code in the calling procedure that is not accessible from an extension's event handler, I am also requesting that the EditDimensionSet call be wrapped here as well:

table 81 "Gen. Journal Line"
    procedure ShowDimensions()

table 38 "Purchase Header"
    procedure ShowDocDim()

table 39 "Purchase Line"
    procedure ShowDimensions()

table 36 "Sales Header"
    procedure ShowDocDim()

table 37 "Sales Line"
    procedure ShowDimensions()

table 5902 "Service Line"
    procedure ShowDimensions()

Thank you,

Denis

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by AlexanderYakunin** [comment]
Hello! 

We have received feedback that this requests is not yet implemented and therefore reactivate it. I can see that we have event OnBeforeEditDimensionSet(DimSetID, NewCaption, NewDimSetID, IsHandled) in codeunit DimensionManagement as generic possibility to alter standard processing, but this procedure does not provide Rec as parameter.

We can either implement suggested event in 41 tables, or add parameter Rec (as Variant) into new implementation of procedure EditDimensionSet in codeunit DimensionManagement. Please provide your thoughts on this suggestion.

**Comment by AlexanderYakunin** [comment]
After recheck. We have addressed this ask but in more generic way. New version of procedure EditDimensionSet have been added, with parameter RecVariant, and handled event. You can use this event to address any table:

    procedure EditDimensionSet(RecVariant: Variant; DimSetID: Integer; NewCaption: Text[250]; var GlobalDimVal1: Code[20]; var GlobalDimVal2: Code[20]): Integer
    var
        DimSetEntry: Record "Dimension Set Entry";
        EditDimSetEntries: Page "Edit Dimension Set Entries";
        NewDimSetID: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeEditDimensionSet2(DimSetID, NewCaption, GlobalDimVal1, GlobalDimVal2, NewDimSetID, IsHandled, RecVariant);
        if IsHandled then
            exit(NewDimSetID);

**Comment by SER-denisg** [comment]
Hello Alexander,
Thank you for reviewing this.  The variant parameter we should be able to use to access our extra extension fields for our processing, so I believe this change will work for our needs.  Thank you for finding a more appropriate change!

Denis
