### ISSUE TITLE
[EventRequest] Codeunit::Price List Management, OnAfterActivateDraftLines

### ISSUE THREAD

**Issue by markborges** [microsoft/ALAppExtensions#16555]
Hi,

Is it possible to add an event after prices are "verified"? From what I read in the base code, it seems the "Verify Lines" function ends up calling a function named "ActivateDraftLines" on Codeunit 7017 "Price List Management".

Having this event OnAfterActivateDraftLines (or OnAfterVerifyLines) would be helpful to make additional checks, or maybe, even renumbering the Sales Price Lines that eventually get clogged up if users split lines multiple times.

Thanks in advance.

**Comment by Oleg-Romashkov** [comment]
Hi,
Please always put the full detailed signature of the requested events and the parameters passed in the call.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by markborges** [comment]
> Hi, Please always put the full detailed signature of the requested events and the parameters passed in the call. You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

Noted! Thanks for the info. Please see the details below:

```
codeunit 7017 "Price List Management"
```
```
procedure ActivateDraftLines(PriceListHeader: Record "Price List Header"): Boolean;
    var
        PriceListLine: Record "Price List Line";
    begin
        if not PriceListHeader.HasDraftLines(PriceListLine) then
            exit;

        VerifyLines(PriceListLine);
        if not ResolveDuplicatePrices(PriceListHeader) then
            exit(false);

        PriceListLine.ModifyAll(Status, "Price Status"::Active);

        OnAfterActivateDraftLines();  //<---------- NEW
        Message(AllLinesVerifiedMsg);
        exit(true);
    end;
```

```
    // NEW
    [IntegrationEvent(false, false)]
    local procedure OnAfterActivateDraftLines(var PriceListHeader: Record "Price List Header")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
