### ISSUE TITLE
Cannot set balancingAccountNumber for journalLines API

### ISSUE THREAD

**Issue by tomwells2** [microsoft/ALAppExtensions#16550]
API when issuing a post request -
api/v2.0/companies(guid)/journals(guid)/journalLines

Example - 
```
 {    
            "accountNumber": "25402",
            "postingDate": "2022-02-28",            
            "amount": 10,            
            "comment": "test journal",
            "taxCode": "",            
            "balancingAccountNumber": "57004"
 }

```
Result - 
```
{
    ... 
    "balanceAccountType": "G_x002F_L_x0020_Account",
    "balancingAccountId": "00000000-0000-0000-0000-000000000000",
    "balancingAccountNumber": "",
}
```

Same result when setting the balancingAccountId guid directly.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
