### ISSUE TITLE
New Subscription - Codeunit 5940 ServContractManagement -  CountLineInvFrom

### ISSUE THREAD

**Issue by pfortunyak** [microsoft/ALAppExtensions#16554]
Please create a new subcription to method  local procedure CountLineInvFrom(SigningContract: Boolean;ServContractLine: Record "Service Contract Line";InvFrom: Date) LineInvFrom: Date

local procedure CountLineInvFrom(SigningContract: Boolean;ServContractLine: Record "Service Contract Line";InvFrom: Date) LineInvFrom: Date
    begin
        if ServContractLine."Invoiced to Date" = 0D then
          LineInvFrom := ServContractLine."Starting Date"
        else
          if SigningContract then begin
            // >> CC14
            //IF ServContractLine."Invoiced to Date" <> CALCDATE('<CM>',ServContractLine."Invoiced to Date") THEN
            if ServContractLine."Invoiced to Date" <> 0D then
            // << CC14
              LineInvFrom := ServContractLine."Invoiced to Date" + 1
          end else
            LineInvFrom := InvFrom;
      OnAfterCountLineInvFrom(SigningContract,ServContractLine,InvFrom,LineInvFrom )
    end;

[IntegrationEvent(false, false)]
local procedure OnCalcServLedgEntryDiscountPct(SigningContract: Boolean;ServContractLine: Record "Service Contract Line";InvFrom: Date;var LineInvFrom: Date)
begin
end;

**Comment by AlexanderYakunin** [comment]
Please verify you request. Do you need new event? Or something else?
