### ISSUE TITLE
Codeunit 415 Release Purchase Document

### ISSUE THREAD

**Issue by RaimondStokkel** [microsoft/ALAppExtensions#16559]
Request to move the check on the Purchase Lines in the procedure Code() to a separate function (TestLines) with a handled pattern. 

..........................
local procedure "Code"() LinesWereModified: Boolean
        with PurchaseHeader do begin
            if Status = Status::Released THEN
                exit;
            OnBeforeReleasePurchaseDoc(PurchaseHeader, PreviewMode);
            if not (PreviewMode or SkipCheckReleaseRestrictions) then
                CheckPurchaseReleaseRestrictions;

            IsHandled := false;
            OnCodeOnAfterCheckPurchaseReleaseRestrictions(PurchaseHeader, IsHandled);
            if IsHandled then
                exit;

            **///////////<<Code from here in separate function with handled pattern**
            PurchLine.SetRange("Document Type", "Document Type");
            PurchLine.SetRange("Document No.", "No.");
            PurchLine.SetFilter(Type, '>0');
            PurchLine.SetFilter(Quantity, '<>0');
            OnCodeOnAfterPurchLineSetFilters(PurchaseHeader, PurchLine);
            if not PurchLine.Find('-') then
                Error(Text001, "Document Type", "No.");
            **///////////>>End**

            InvtSetup.Get();
            if InvtSetup."Location Mandatory" then begin
                PurchLine.SetRange(Type, PurchLine.Type::Item);
                if PurchLine.Find('-') then
                    repeat
                        if PurchLine.IsInventoriableItem then
                            PurchLine.TestField("Location Code");
                    until PurchLine.Next() = 0;
                PurchLine.SetFilter(Type, '>0');
            end;
..........................

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
