### ISSUE TITLE
[Event Request] codeunit 99000854 "Inventory Profile Offsetting" - OnMaintainPlanningLineOnBeforeReqLineInsert

### ISSUE THREAD

**Issue by MarcoHeijden** [microsoft/ALAppExtensions#16560]
Please add the parameter SkipInsert the event OnMaintainPlanningLineOnBeforeReqLineInsert. We want to skip the insert of the Requisition Line based on the actual values of the fields which are hard to predict upfront, for example the Quantity and Original Quantity. These fields are determined differently in various scenario's and can also be changed by existing events.  That is why it is not possible to use the existing event OnBeforeMaintainPlanningLine.
If the parameter SkipInsert is true then we want to exit the procedure, because in that case the code behind the insert does not make sense.

                OnMaintainPlanningLineOnBeforeAdjustPlanLine(ReqLine, SupplyInvtProfile, TempSKU);
                AdjustPlanLine(SupplyInvtProfile);
                "Accept Action Message" := true;
                "Routing Reference No." := "Line No.";
                UpdateDatetime;
                "MPS Order" := SupplyInvtProfile."MPS Order";
                OnMaintainPlanningLineOnBeforeReqLineInsert(
                  ReqLine, SupplyInvtProfile, PlanToDate, CurrForecast, NewPhase, Direction, DemandInvtProfile, ExcludeForecastBefore, **SkipInsert**);
                if SkipInsert then
                    exit;
                Insert;

    [IntegrationEvent(false, false)]
    local procedure OnMaintainPlanningLineOnBeforeReqLineInsert(var RequisitionLine: Record "Requisition Line"; var SupplyInvtProfile: Record "Inventory Profile"; PlanToDate: Date; CurrentForecast: Code[10]; NewPhase: Option " ","Line Created","Routing Created",Exploded,Obsolete; Direction: Option Forward,Backward; DemandInvtProfile: Record "Inventory Profile"; ExcludeForecastBefore: Date; **var SkipInsert: Boolean**)
    begin
    end;

**Comment by Oleg-Romashkov** [comment]
Hi,
We cannot make exit here because there could be problems with next events in this functions. 

Is it ok for you to make handled wrapping for line:
`Insert;`
instead of exiting?
If no, then please find another way for needed logic.

**Comment by MarcoHeijden** [comment]
Thanks for the answer, but we want to stop the code of this function. Not only prevent the insert. We will look to another solution.

**Comment by Oleg-Romashkov** [comment]
Ok. Please create a new request if needed.
