### ISSUE TITLE
Email Outbox how get the record?

### ISSUE THREAD

**Issue by twbook** [microsoft/ALAppExtensions#16566]
I've made simple change to the the "Email Outbox", however all the fields are Access Internal.  With this I then can not filter the table by the Message ID that I have to set the value?

tableextension 60019 "EmailOutboxBST" extends "Email Outbox"
{
    fields
    {
        field(60001; "Customer No.BST"; Code[20])
        {
            DataClassification = CustomerContent;
            Caption = 'Customer No.';
            TableRelation = "Customer"."No.";
        }
    }
}

**Comment by darjoo** [comment]
Hi @twbook
Below is an example of how to do so. It isn't the cleanest way of doing it, but it is the only way to access the internal fields right now.
```
local procedure FilterOutbox()
var
    EmailOutbox: Record "Email Outbox";
    MailRecordRef: RecordRef;
    MessageIdFieldRef: FieldRef;
begin
    MailRecordRef.GetTable(EmailOutbox);
    MessageIdFieldRef := MailRecordRef.Field(2); // Message ID field
    MessageIdFieldRef.SetFilter(<MessageId Guid>);

    if MailRecordRef.FindFirst() then begin
        Message('Found');
    end else
        Message('Not Found');
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
