### ISSUE TITLE
[Event Request] Codeunit 1173 - Document Attachment Mgmt - procedure DeleteAttachedDocumentsWithConfirm

### ISSUE THREAD

**Issue by jasontalssi** [microsoft/ALAppExtensions#16563]
It would be nice to have an IsHandled that would allow the confirmation message and delete from happening.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
