### ISSUE TITLE
Add new Event for Codeunit: Calendar Management, Function CheckDateStatus

### ISSUE THREAD

**Issue by nicdiblasiFS** [microsoft/ALAppExtensions#16568]
Hi,
Can the following event please be added to:

Codeunit 7600 "Calendar Management"
Function: CheckDateStatus

New Event: 
OnCheckDateStatusAfterCombineChanges(var TargetCustomizedCalendarChange: Record "Customized Calendar Change"; TempCustChange: Record "Customized Calendar Change")

![image](https://user-images.githubusercontent.com/87403142/157369120-8adc5d03-f661-4566-8222-ec93b4c1451a.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
