### ISSUE TITLE
[EventRequest] Codeunit 5600 "FA Insert Ledger Entry" - OnInsertFAOnAfterSetFALedgEntryFANo

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#16561]
Hello,

We would need to have IncludeSender attribute to true on the event OnInsertFAOnAfterSetFALedgEntryFANo:

    [IntegrationEvent(**true**, false)]
    local procedure OnInsertFAOnAfterSetFALedgEntryFANo(FALedgEntry3: Record "FA Ledger Entry"; FALedgEntry2: Record "FA Ledger Entry"; FALedgEntry: Record "FA Ledger Entry"; var NextEntryNo: Integer)
    begin
    end;

We need this change because, when subscribing to this event, we need to use global functions from the codeunit FA Insert Ledger Entry.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
