### ISSUE TITLE
[Event Change] Codeunit 80 "Sales-Post", OnBeforePostLines

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#16578]
Hi Team,

could you please add parameter **TempWhseShptHeader** to publisher **OnBeforePostLines** in codeunit **Sales-Post**

Current definition:

``` AL
[IntegrationEvent(false, false)]
local procedure OnBeforePostLines(var SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header"; CommitIsSuppressed: Boolean; PreviewMode: Boolean)
begin
end;
```

Requested definition:

``` AL
[IntegrationEvent(false, false)]
local procedure OnBeforePostLines(var SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header"; TempWhseShptHeader: Record "Warehouse Shipment Header" temporary; CommitIsSuppressed: Boolean; PreviewMode: Boolean)
begin
end;
```

Thanks in advance,
Christian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
