### ISSUE TITLE
[Event Request] CU 452 "Report Distribution Management" - OnBeforeGetReportCaption

### ISSUE THREAD

**Issue by Easystep2** [microsoft/ALAppExtensions#16572]
Can we please add the following event:

procedure GetReportCaption(ReportID: Integer; LanguageCode: Code[10]) ReportCaption: Text[250]
    var
        AllObjWithCaption: Record AllObjWithCaption;
        TranslationHelper: Codeunit "Translation Helper";
---- start
         IsHandled : Boolean;
---- stop
    begin

---- start
       IsHandeld := false;
       OnBeforeGetReportCaption(ReportID, LanguageCode, ReportCaption, IsHandled);
       if IsHandled then 
             exit;
---- end

        TranslationHelper.SetGlobalLanguageByCode(LanguageCode);

        if AllObjWithCaption.Get(AllObjWithCaption."Object Type"::Report, ReportID) then
            ReportCaption := AllObjWithCaption."Object Caption";

        TranslationHelper.RestoreGlobalLanguage();
    end;

---- start
local procedure OnBeforeGetReportCaption(ReportID: Integer; LanguageCode: Code[10];var ReportCaption: Text[250]; var IsHandled : boolean)
---- end

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
