### ISSUE TITLE
[Event Request] table 901 "Assembly Line" - OnValidateApplToItemEntryOnBeforeShowNotOpenItemLedgerEntryMessage

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16576]
I would like to request the following event. I would not need it if I was able to get connected to Partnersource or Collaborate because it is actually needed to fix a bug:
"Location Code" := ItemLedgEntry."Location Code";
should actually be
Validate("Location Code", ItemLedgEntry."Location Code");
But because it is easier to get an event than a bug fixed, I'm requesting this event.

        field(38; "Appl.-to Item Entry"; Integer)
        {
            ...

            trigger OnValidate()
            var
                ItemLedgEntry: Record "Item Ledger Entry";
            begin
                ...
                    "Location Code" := ItemLedgEntry."Location Code";
                    OnValidateApplToItemEntryOnBeforeShowNotOpenItemLedgerEntryMessage(Rec, xRec, ItemLedgEntry, CurrFieldNo); //A108B0068.Event.19.05
                    if not ItemLedgEntry.Open then
                        Message(Text042, "Appl.-to Item Entry");
                end;
            end;
        }

    [IntegrationEvent(false, false)]
    local procedure OnValidateApplToItemEntryOnBeforeShowNotOpenItemLedgerEntryMessage(var AssemblyLine: Record "Assembly Line"; xAssemblyLine: Record "Assembly Line"; var ItemLedgerEntry: Record "Item Ledger Entry"; CurrFieldNo: Integer)
    begin
        //A108B0068.Event.19.05
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
