### ISSUE TITLE
Possible bug on Customer Card CZ extension

### ISSUE THREAD

**Issue by MKadlecNav** [microsoft/ALAppExtensions#16575]
Hello,
for CZ localization on Customer Card there is a field Balance(LCY) as Vendor
![image](https://user-images.githubusercontent.com/100062613/157616602-1afa84c0-ed94-4e3e-b365-0eef3385ac08.png)
this field is not calculated, it should be calculated in trigger OnAfterGetRecord the same way as it is calculated field BalanceAsCust on Vendor Card:
![image](https://user-images.githubusercontent.com/100062613/157618048-d59a5601-6070-4c6a-8266-d1afaafeaf41.png)
but on Customer Card it is not calculated.

it is BC version:
![image](https://user-images.githubusercontent.com/100062613/157619655-016d130c-ec4d-4c8e-bfa9-b03f841f8361.png)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 18.
