### ISSUE TITLE
[Code Improvement] Codeunit 12 - Procedure IsOriginalEntryExist

### ISSUE THREAD

**Issue by jazadv** [microsoft/ALAppExtensions#16573]
Hello,

I propose to replace all findfirst() by isempty() in procedure IsOriginalEntryExist of codeunit 12.

This change provides a significant speed improvement when posting a journal with many lines applying.

Greetings

J

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
