### ISSUE TITLE
[Fieldgroups ReRequest] table 7354 Bin

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16577]
I'm currently on 19.05 and since 18.03 this issue has not been resolved:

https://github.com/microsoft/ALAppExtensions/issues/14464

With the Universal Code Initiative on our doorstep this must be resolved a lot faster please.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
