### ISSUE TITLE
Table 5406 Prod. Order Line, OnValidateItemNoOnAfterAssignItemValues

### ISSUE THREAD

**Issue by SoniaIbermatica** [microsoft/ALAppExtensions#16579]
We need a modification in Table 5406 "Prod. Order Line". The change will be in the function "OnValidateItemNoOnAfterAssingItemValues".

Now we have this code in the OnValidate of the field "Item No.":

OnAfterAssignItemValues(Rec, Item);
IF "Item No." <> xRec."Item No." THEN BEGIN
    VALIDATE("Production BOM No.",Item."Production BOM No.");
    VALIDATE("Routing No.",Item."Routing No.");
    VALIDATE("Unit of Measure Code",Item."Base Unit of Measure");
END;

It would be possible to include a parameter in the function "OnAfterAssignItemValues"?

// MODIFY EVENT
The event will be:
LOCAL [IntegrationEvent] OnAfterAssignItemValues(VAR ProdOrderLine : Record "Prod. Order Line";Item : Record Item;VAR IsHandled: Boolean)

// MODIFY CODE
OnAfterAssignItemValues(Rec, Item,IsHandled);
IF NOT IsHandled THEN BEGIN
  IF "Item No." <> xRec."Item No." THEN BEGIN
      VALIDATE("Production BOM No.",Item."Production BOM No.");
      VALIDATE("Routing No.",Item."Routing No.");
      VALIDATE("Unit of Measure Code",Item."Base Unit of Measure");
  END;
END;

Thank you.
Sonia Roca.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
