### ISSUE TITLE
[ReRequest for External] table 7347 "Internal Movement Line" - CheckBinContentQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16582]
https://github.com/microsoft/ALAppExtensions/issues/14482

Asking politely again to implement the request from issue 14482
I'm using 19.5 and five months later not seeing it.

**Comment by AlexanderYakunin** [comment]
Please read Wiki, we do not implement such requests into PROD versions (19.x for now), so all external request implemented in 20.0. This one already implemented.
