### ISSUE TITLE
[Event Request] table 83 "Item Journal Line" - OnValidateItemNoOnAfterSetProdOrderLineItemNoFilter

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16587]
field(3; "Item No."; Code[20])
        {
            Caption = 'Item No.';
            TableRelation = Item;

            trigger OnValidate()
            var
                ProdOrderLine: Record "Prod. Order Line";
                ProdOrderComp: Record "Prod. Order Component";
                PriceType: Enum "Price Type";
            begin
                ...
                    "Entry Type"::Output:
                        begin
                            Item.TestField("Inventory Value Zero", false);
                            ProdOrderLine.SetFilterByReleasedOrderNo("Order No.");
                            ProdOrderLine.SetRange("Item No.", "Item No.");
                            OnValidateItemNoOnAfterSetProdOrderLineItemNoFilter(Rec, xRec, ProdOrderLine); //A108B0087.Event19.05
                            if ProdOrderLine.FindFirst then begin

    [IntegrationEvent(false, false)]
    local procedure OnValidateItemNoOnAfterSetProdOrderLineItemNoFilter(var ItemJournalLine: Record "Item Journal Line"; xItemJournalLine: Record "Item Journal Line"; var ProdOrderLine: Record "Prod. Order Line")
    begin
        //A108B0087.Event19.05
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
