### ISSUE TITLE
[Event Request] table 83 "Item Journal Line" - OnValidateItemNoOnShouldCopyFromProdOrderLine

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16588]
We have trouble using the Output Journal with a production order who uses the same item no. in multiple prod. order lines
We would like to request this change. 

        field(3; "Item No."; Code[20])
        {
            Caption = 'Item No.';
            TableRelation = Item;

            trigger OnValidate()
            var
                ProdOrderLine: Record "Prod. Order Line";
                ProdOrderComp: Record "Prod. Order Component";
                PriceType: Enum "Price Type";
                ShouldCopyFromProdOrderLine: Boolean; //A108B0087
            begin
                ...
                    "Entry Type"::Output:
                        begin
                            Item.TestField("Inventory Value Zero", false);
                            ...
                            //if ProdOrderLine.Count = 1 then A108B0087.o
                            //A108B0087.Event19.05.ns
                            ShouldCopyFromProdOrderLine := ProdOrderLine.Count = 1;
                            OnValidateItemNoOnShouldCopyFromProdOrderLine(Rec, xRec, ProdOrderLine, ShouldCopyFromProdOrderLine);
                            if ShouldCopyFromProdOrderLine then
                                //A108B0087.Event19.05.ne
                                CopyFromProdOrderLine(ProdOrderLine)
                            else
                                if "Order Line No." <> 0 then begin
                                    ProdOrderLine.SetRange("Line No.", "Order Line No.");
                                    if ProdOrderLine.FindFirst() then
                                        CopyFromProdOrderLine(ProdOrderLine)

    [IntegrationEvent(false, false)]
    local procedure OnValidateItemNoOnShouldCopyFromProdOrderLine(var ItemJournalLine: Record "Item Journal Line"; xItemJournalLine: Record "Item Journal Line"; var ProdOrderLine: Record "Prod. Order Line"; var ShouldCopyFromProdOrderLine: Boolean)
    begin
        //A108B0087.Event19.05
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
