### ISSUE TITLE
[Event Request] table 27 Item - OnAfterOnInsert

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16583]
trigger OnInsert()
    var
        IsHandled: Boolean;
    begin
        ...
        UpdateItemUnitGroup();

        OnAfterOnInsert(Rec, xRec); //A113F0000.Event
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterOnInsert(var Item: Record Item; var xItem: Record Item)
    begin
        //A113F0000.Event
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
