### ISSUE TITLE
[Event Change] Codeunit 80 "Sales-Post", OnBeforeSalesInvHeaderInsert

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#16581]
Hi Team,

could you please add following parameter to publisher **OnBeforeSalesInvHeaderInsert** in codeunit **Sales-Post**
- WhseShip: Boolean;
-  WhseShptHeader: Record "Warehouse Shipment Header"

Current definition:

``` AL
[IntegrationEvent(false, false)]
local procedure OnBeforeSalesInvHeaderInsert(var SalesInvHeader: Record "Sales Invoice Header"; var SalesHeader: Record "Sales Header"; CommitIsSuppressed: Boolean; var IsHandled: Boolean)
begin
end;
```

Requested definition:

``` AL
[IntegrationEvent(false, false)]
local procedure OnBeforeSalesInvHeaderInsert(var SalesInvHeader: Record "Sales Invoice Header"; SalesHeader: Record "Sales Header"; CommitIsSuppressed: Boolean; WhseShip: Boolean; WhseShptHeader: Record "Warehouse Shipment Header"; var IsHandled: Boolean)
begin
end;
```

Thanks in advance,
Christian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
