### ISSUE TITLE
[Event ReRequest] table 83 "Item Journal Line" - OnValidateOutputQuantityOnAfterCalcBaseQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16585]
https://github.com/microsoft/ALAppExtensions/issues/14494

I would like to ask politely to apply this request as you seem to have agreed, but after 5,5 months no change in 19.05

**Comment by Oleg-Romashkov** [comment]
Hi,
Sometimes we do not create events exactly as you requested but do it in a bit different way.
By your request the event OnAfterCalcBaseQty has been created (for the function CalcBaseQty

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
