### ISSUE TITLE
event request - report 1305 "Standard Sales - Order Conf." - DocumentCaption() - OnBeforeGetDocumentCaption - as with Sales Invoice

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#16589]
We want to override the caption conditionally, as we already do in `report 1306 "Standard Sales - Invoice"`.

Thus please add this event to `report 1305 "Standard Sales - Order Conf."`, to be called how `report 1306` already does it:

```al
    local procedure DocumentCaption(): Text[250]
    var
        DocCaption: Text;
    begin
        OnBeforeGetDocumentCaption(Header, DocCaption);
        if DocCaption <> '' then
            exit(DocCaption);
        exit(SalesConfirmationLbl);
    end;
```

```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetDocumentCaption(SalesHeader: Record "Sales Header"; var DocCaption: Text)
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
