### ISSUE TITLE
Unable to open tenant permission from permission set when  length => 20

### ISSUE THREAD

**Issue by DivyaManjunath25** [microsoft/ALAppExtensions#16593]
Hello,
we are facing the below error when trying to open permission from permission set.
The CurrentRoleId accepts text as value which appends single quotes hence the total length will be 22. But the function GetSourceForLinkedPermissionSet which accepts role id as a parameter has been set to type code[20] hence causing the issue.

**Note: This only happens when a special character like (,),* etc is added in the RoleID** 

![image](https://user-images.githubusercontent.com/100192237/157824843-b4dda265-a66e-422c-97de-c2e652b4b6dc.png)

![image](https://user-images.githubusercontent.com/100192237/157825308-bfc65d4f-fcad-4b6d-b3ca-992439ff5e09.png)

![image](https://user-images.githubusercontent.com/100192237/157825210-c26c720c-1e4f-49a8-8fb9-ff585ac1a30a.png)

**Comment by RomanZanizdra** [comment]
Hi @DivyaManjunath25.
Starting from 19.x version user is not able to create permission set with special symbols (I suppose yours were created earlier).
I suggest you to rename permission sets by removing brackets from the name or make the name shorter. This is the way out.
