### ISSUE TITLE
[ReRequest Scope Change] tables 6660 "Return Receipt Header" & 167 Job - EmailRecords

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16590]
https://github.com/microsoft/ALAppExtensions/issues/15218

Issue 15218 is agreed upon in nov. 2021 in 18.05. When can we expect to see the requested scope change?

**Comment by Duizy1971** [comment]
@dnpb I think I know what you mean. Issue 15218 was requested by me on nov. 2021 when 19.x was already released but my code was still on 18.05. So you say I can expect it in 20.x? Funny thing is that many of my other requests from sept/okt/nov 2021 have been implemented in releases 19.1 and 19.5 so I am afraid issues are just being forgotten/misplaced. Many requests from July 2021 have been acknowledged also but still I do not see those changes reflected in either 18.x or 19.x Should I be more patient then?

**Comment by AlexanderYakunin** [comment]
Implemented for 20.0
