### ISSUE TITLE
[Event Request] table 167 Job - OnAfterCalcAreJobTaskLinesEditable

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16594]
In our app we are using a lifecycle/workflow code on the Job table which has the ability to tell and show the user if the Job Card and its subpage "JobTaskLines" is editable or not. When you scroll through the job records we are able to set the editable property of the Job card itself but not of the task lines subpage. I hope this is the right place to ask for such a code/event change and not go through the Ideas or Collaborate site because that will take ages to conform to the Universal Code Initiative on time.

To use our app and delete Base app changes we need the following:
1.
A procedure + event in table 167 Job:
    procedure CalcAreJobTaskLinesEditable() IsEditable: Boolean;
    begin
        //A113F0000.Event.ns
        IsEditable := "Bill-to Customer No." <> '';

        OnAfterCalcAreJobTaskLinesEditable(Rec, IsEditable);
        //A113F0000.Event.ne
    end;
    
        [IntegrationEvent(false, false)]
    local procedure OnAfterCalcAreJobTaskLinesEditable(var Job: Record Job; var IsEditable: Boolean)
    begin
        //A113F0000.Event
    end;

2.
a global var on page 88 "Job Card"
AreJobTaskLinesEditable: Boolean;

3.
a call in trigger OnAfterGetCurrRecord() on page 88 "Job Card"
        AreJobTaskLinesEditable := Rec.CalcAreJobTaskLinesEditable(); //A113F0000.Event

4.
setting the properties Editable and Enabled of part(JobTaskLines; "Job Task Lines Subform")
                Editable = AreJobTaskLinesEditable;
                Enabled = AreJobTaskLinesEditable;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
