### ISSUE TITLE
Need Event in Price List Line to transfer customer fields from PriceAsset

### ISSUE THREAD

**Issue by michuanni** [microsoft/ALAppExtensions#16595]
It is not possible to transfer customer field values from Price Asset to Price List Line. Please create a subscription event in the function CopyFrom with parameters "Price List Line" and " Price Asset.

    procedure CopyFrom(PriceAsset: Record "Price Asset")
    begin
        "Price Type" := PriceAsset."Price Type";
        "Asset Type" := PriceAsset."Asset Type";
        "Asset No." := PriceAsset."Asset No.";
        "Asset ID" := PriceAsset."Asset ID";
        Description := PriceAsset.Description;
        "Unit of Measure Code" := PriceAsset."Unit of Measure Code";
        "Variant Code" := PriceAsset."Variant Code";
        "Work Type Code" := PriceAsset."Work Type Code";

        "Allow Invoice Disc." := PriceAsset."Allow Invoice Disc.";
        if not GetHeader() or PriceListHeader."Allow Updating Defaults" then
            if "VAT Bus. Posting Gr. (Price)" = '' then begin
                "Price Includes VAT" := PriceAsset."Price Includes VAT";
                "VAT Bus. Posting Gr. (Price)" := PriceAsset."VAT Bus. Posting Gr. (Price)";
            end;
        
        OnAfterCopyFromPriceAsset(PriceAsset);
        OnAfterCopyFromPriceAsset(Rec,PriceAsset);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyFromPriceAsset(var PriceListLine: Record "Price List Line";PriceAsset: Record "Price Asset")
    begin
    end;

So I can transfer the Values from Price Asset to Price List Line like this:

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Price Asset - Item", 'OnAfterFillAdditionalFields', '', false, false)]
    local procedure OnAfterFillAdditionalFieldsPriceAssetItem(var PriceAsset: Record "Price Asset"; Item: Record Item; ItemVariant: Record "Item Variant")
    begin
        PriceAsset.KVSItemDesc2 := Item."Description 2";
    end;

    [EventSubscriber(ObjectType::Table, Database::"Price List Line", 'OnAfterCopyFromPriceAsset', '', false, false)]
    local procedure OnAfterCopyFromPriceAssetPriceListLine(var PriceListLine: Record "Price List Line"; PriceAsset: Record "Price Asset")
    begin
        PriceListLine.KVSItemDesc2 := PriceAsset.KVSItemDesc2;        
    end;

**Comment by Oleg-Romashkov** [comment]
Hi,
Exiting event OnAfterCopyFromPriceAsset has IncludeSender=true, so you already can use parameter var Sender: Record "Price List Line"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
