### ISSUE TITLE
[EventRequest]Codeunit 90 Purch.-Post

### ISSUE THREAD

**Issue by wokw** [Microsoft/ALAppExtensions#166]
Due to Polish Localization App building, we need one extra parameter in publisher in CU 90 (GenJnlLineDocNo) . Before finalize posting we need to post Reverse Charge Differences.

Function: FinalizePosting

Current code:
OnBeforeFinalizePosting(PurchHeader,TempPurchLineGlobal,EverythingInvoiced,SuppressCommit);

Requested code:
OnBeforeFinalizePosting(PurchHeader,TempPurchLineGlobal,EverythingInvoiced,SuppressCommit,GenJnlLineDocNo);

Current Publisher signature: LOCAL [IntegrationEvent] OnBeforeFinalizePosting(VAR PurchaseHeader : Record "Purchase Header";VAR TempPurchLineGlobal : TEMPORARY Record "Purchase Line";VAR EverythingInvoiced : Boolean;CommitIsSupressed : Boolean)

Requested Publisher signature: LOCAL [IntegrationEvent] OnBeforeFinalizePosting(VAR PurchaseHeader : Record "Purchase Header";VAR TempPurchLineGlobal : TEMPORARY Record "Purchase Line";VAR EverythingInvoiced : Boolean;CommitIsSupressed : Boolean;GenJnlLineDocNo : Code[20])

**Comment by AlexanderYakunin** [comment]
We plan to add GlobalVar access to this event
