### ISSUE TITLE
[Event Request] Page 5708 "Get Shipment Lines" - New publisher

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16605]
Hello, we need a new Event publisher in OnQueryClosePage trigger. Can you please check that? Thank you!

    trigger OnQueryClosePage(CloseAction: Action): Boolean
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeOnQueryClosePage(CloseAction, IsHandled);
        if IsHandled then
            exit;

        if CloseAction in [ACTION::OK, ACTION::LookupOK] then
            CreateLines;
    end;

New Event:

    [IntegrationEvent(true, false)]
    local procedure OnBeforeOnQueryClosePage(CloseAction: Action; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
