### ISSUE TITLE
[Event Request] Table 167 - Job - OnBeforeAssistEdit

### ISSUE THREAD

**Issue by programmierenlol** [microsoft/ALAppExtensions#16601]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher OnBeforeAssistEdit be added to Table 167 - Job with the following signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssistEdit(var Job: Record Job; var OldJob: Record Job; var IsHandled: Boolean)
    begin
    end;

with VAR parameter Job.
which would be called as follows from AssistEdit in Table 167 - Job:

    procedure AssistEdit(OldJob: Record Job): Boolean
    var
        IsHandled: Boolean;
    begin
        OnBeforeAssistEdit(Rec, OldJob, IsHandled);
        if IsHandled then
            EXIT;

        with Job do begin
            Job := Rec;
            JobsSetup.Get();
            JobsSetup.TestField("Job Nos.");
            if NoSeriesMgt.SelectSeries(JobsSetup."Job Nos.", OldJob."No. Series", "No. Series") then begin
                NoSeriesMgt.SetSeries("No.");
                Rec := Job;
                exit(true);
            end;
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
