### ISSUE TITLE
[Extensibility Request] Page 223 "Resource Statistics" - Protected variables

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16608]
Hello, we need the following currently global variables defined as protected for our page extension. Can you please check that? Thank you!

    protected var
        ResCapacity: array[4] of Decimal;
        UnusedCapacity: array[4] of Decimal;
        ResDateFilter: array[4] of Text[30];

**Comment by AlexanderYakunin** [comment]
Already implemented
