### ISSUE TITLE
PurchPost.Codeunit.al - PostItemChargePerITTransfer

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#16602]
I would like to request the following event:
Object: PurchPost.Codeunit
Procedure: PostItemChargePerITTransfer

![image](https://user-images.githubusercontent.com/68000891/157869419-98ab39b1-6930-4200-a3b7-7e9ef461fce6.png)

Event Code: 
```al
    [IntegrationEvent(false, false)]
    local procedure OnPostItemChargePerITTransferOnAfterCollectItemEntryRelation(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; TransRcptLine: Record "Transfer Receipt Line"; var TempItemLedgEntry: Record "Item Ledger Entry" temporary)
    begin
    end;
```

**Comment by Oleg-Romashkov** [comment]
Hi,
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
