### ISSUE TITLE
[Event Request] table 210 "Job Journal Line" - OnValidateBinCodeOnBeforeFindBinContent

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16618]
field(5403; "Bin Code"; Code[20])
        {
            AccessByPermission = TableData "Warehouse Source Filter" = R;
            ...

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                TestField("Location Code");
                if "Bin Code" <> '' then begin
                    GetLocation("Location Code");
                    Location.TestField("Bin Mandatory");
                end;
                TestField(Type, Type::Item);
                GetItem();
                Item.TestField(Type, Item.Type::Inventory);
                CheckItemAvailable;
                //A108B0094.ns
                OnValidateBinCodeOnBeforeFindBinContent(Rec, xRec, IsHandled);
                if not IsHandled then
                    //A108B0094.ne
                    WMSManagement.FindBinContent("Location Code", "Bin Code", "No.", "Variant Code", '')
            end;
        }

    [IntegrationEvent(false, false)]
    local procedure OnValidateBinCodeOnBeforeFindBinContent(var JobJournalLine: Record "Job Journal Line"; xJobJournalLine: Record "Job Journal Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
