### ISSUE TITLE
[Extensibility Request] Codeunit 402 "Sales Order Statistics" - Procedure from Local to Global & Protected procedures

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16617]
Hello, we need the following currently Local procedure to be set as Global. Can you please check this? Thank you!

    procedure UpdateHeaderInfo(IndexNo: Integer; var VATAmountLine: Record "VAT Amount Line")

We also need the following currently Local procedure to be set as protected, for the same purpose. Can you please check this one too? Thank you!

    protected procedure GetCaptionClass(FieldCaption: Text[100]; ReverseCaption: Boolean): Text[80]

    protected procedure VATLinesDrillDown(var VATLinesToDrillDown: Record "VAT Amount Line"; ThisTabAllowsVATEditing: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
