### ISSUE TITLE
[Event Parameter Request] table 39 "Purchase Line" - OnAfterAssignItemValues

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16625]
//OnAfterAssignItemValues(Rec, Item, CurrFieldNo); A108F0025.Event.o
        OnAfterAssignItemValues(Rec, PurchHeader, Item, CurrFieldNo); //A108F0025.Event.n

    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignItemValues(var PurchLine: Record "Purchase Line"; PurchHeader: Record "Purchase Header"; Item: Record Item; CurrentFieldNo: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
