### ISSUE TITLE
[Event Parameter change] table 39 "Purchase Line" - OnAfterAssignGLAccountValues

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16624]
We would like to add parameter PurchHeader:

        //OnAfterAssignGLAccountValues(Rec,GLAcc); A108F0025.Event.o
        OnAfterAssignGLAccountValues(Rec, GLAcc, PurchHeader); //A108F0025.Event.n

    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignGLAccountValues(var PurchLine: Record "Purchase Line";  GLAccount: Record "G/L Account"; PurchHeader: Record "Purchase Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
