### ISSUE TITLE
[Event Request] table 39 "Purchase Line" - OnBeforeCheckApplToItemLedgEntry

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16628]
local procedure CheckApplToItemLedgEntry(): Code[10]
    var
        ItemLedgEntry: Record "Item Ledger Entry";
        ApplyRec: Record "Item Application Entry";
        ReturnedQty: Decimal;
        RemainingtobeReturnedQty: Decimal;
        IsHandled: Boolean;
    begin
        //A108B0024.19.05.ns
        OnBeforeCheckApplToItemLedgEntry(Rec, xRec, IsHandled);
        if IsHandled then
            exit;
        //A108B0024.19.05.ne
        if "Appl.-to Item Entry" = 0 then
            exit;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckApplToItemLedgEntry(var PurchaseLine: Record "Purchase Line"; xPurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
