### ISSUE TITLE
Smtp Mail -> Email+EmailMesage, Missing Functionality?

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/ALAppExtensions#16634]
Hi,

I'm migrating code using the smtp mail setup and codeunit. Previously we were able to set the sender name and sender email address in a call to CreateMessage:

`"SMTP Mail".CreateMessage(sender name, sender email, recipients, subject, body`

We used this to allow users to manage what templates came from where, e.g. shipping template, receipts, orders, etc. They could swap details in those fields to quickly achieve this.

I don't see a procedure that reproduces this functionality in [Email.Codeunit.al](https://github.com/microsoft/ALAppExtensions/blob/main/Modules/System/Email/src/Email/Email.Codeunit.al) or [EmailMessage.Codeunit.al](https://github.com/microsoft/ALAppExtensions/blob/main/Modules/System/Email/src/Message/EmailMessage.Codeunit.al).

Should we instead "hotswap" the sender name and email address in the "SMTP Account" table? Rely on the user to configure multiple email account for this purpose? The first approach is imo a bad idea, the second puts the onus on the user to configure a bunch of stuff. We can tie that together with the email scenario enum?

I'm just looking for guidance as to what the team at MS would consider "correct" as we want to avoid having to alter it again in the future.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz - please help

**Comment by pri-kise** [comment]
There is an open Pull Request, Does this covers parts of your issues?
https://github.com/microsoft/ALAppExtensions/pull/15762

**Comment by mjmatthiesen** [comment]
> There is an open Pull Request, Does this covers parts of your issues?
> #15762

This appears to address most of my use case by adding the SetFrom to the Email Message codeunit.

Thanks for the link!

**Comment by JesperSchulz** [comment]
We'll work on that PR next week and will consider your input @mjmatthiesen! I will close this issue and we can continue discussions in the PR :-)
