### ISSUE TITLE
[Event Request] Wrap calls to DimMgmt's GetDefaultDimID procedure to allow replacing the call to it

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#16635]
Similar to my last two requests, this request is to wrap the calls to GetDefaultDimID with an IsHandled pattern so that the procedure call be replaced.  I am dealing with the same issues of having extra code after that can contain local scope items like event calls, which I cannot replicate in extension code.

Here is an example replacement (that uses a local var to return into, not a table field):

```
report 595 "Adjust Exchange Rates"
...
    local procedure GetJnlLineDefDim(var GenJnlLine: Record "Gen. Journal Line"; var DimSetEntry: Record "Dimension Set Entry")
    var
        DimSetID: Integer;
        TableID: array[10] of Integer;
        No: array[10] of Code[20];
        IsHandled: Boolean;  // NEW VAR
    begin
        case GenJnlLine."Account Type" of
            GenJnlLine."Account Type"::"G/L Account":
                TableID[1] := DATABASE::"G/L Account";
            GenJnlLine."Account Type"::"Bank Account":
                TableID[1] := DATABASE::"Bank Account";
        end;
        No[1] := GenJnlLine."Account No.";
        // NEW CODE BEGIN
        OnGetJnlLineDefDimOnBeforeGetDefaultDimID(TableID, No, GenJnlLine."Source Code", GenJnlLine."Dimension Set ID", 0, IsHandled, DimSetID);
        if not IsHandled then
        // END NEW CODE, indent next statement
        DimSetID :=
            DimMgt.GetDefaultDimID(
                TableID, No, GenJnlLine."Source Code",
                GenJnlLine."Shortcut Dimension 1 Code", GenJnlLine."Shortcut Dimension 2 Code",
                GenJnlLine."Dimension Set ID", 0);
        DimMgt.GetDimensionSet(DimSetEntry, DimSetID);
    end;
...
    [IntegrationEvent(false, false)]
    local procedure OnGetJnlLineDefDimOnBeforeGetDefaultDimID(TableID: array[10] of Integer; No: array[10] of Code[20]; SourceCode: Code[20]; var GlobalDim1Code: Code[20]; var GlobalDim2Code: Code[20]; InheritFromDimSetID: Integer; InheritFromTableNo: Integer; var IsHandled: Boolean; var DimSetID: integer)
    begin
    end;

```

Here is the list of calls to the GetDefaultDimID procedure:

report 595 "Adjust Exchange Rates"
local procedure GetJnlLineDefDim(var GenJnlLine: Record "Gen. Journal Line"; var DimSetEntry: Record "Dimension Set Entry")
- places DimSetID into a local var, not a table field

table 10121 "Bank Rec. Line"
local procedure ClearAndAssignDefaultDimSetID(var TableID: array[10] of Integer; var No: array[10] of Code[20])

table 10140 "Deposit Header"
local procedure CreateDim(Type1: Integer; No1: Code[20])

codeunit 5601 "FA Insert G/L Account"
procedure InsertBufferBalAcc(FAPostingType: Enum "FA Posting Group Account Type"; AllocAmount: Decimal; DeprBookCode: Code[10]; PostingGrCode: Code[20]; GlobalDim1Code: Code[20]; GlobalDim2Code: Code[20]; DimSetID: Integer; AutomaticEntry: Boolean; Correction: Boolean)

codeunit 395 "FinChrgMemo-Issue"
local procedure SetDimensions(var GenJnlLine: Record "Gen. Journal Line"; FinanceChargeMemoHeader: Record "Finance Charge Memo Header")

table 5850 "Invt. Document Header"
procedure DocLinesExist(): Boolean
- two calls, different passed paramters

table 5851 "Invt. Document Line"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20])

table 5876 "Phys. Invt. Order Line"
procedure CreateDim(Type1: Integer; No1: Code[20])

table 10124 "Posted Bank Rec. Line"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20]; Type4: Integer; No4: Code[20]; Type5: Integer; No5: Code[20])

report 402 "Purchase Document - Test"
procedure AddDimToTempLine(PurchLine: Record "Purchase Line"; var TempDimSetEntry: Record "Dimension Set Entry")

report 202 "Sales Document - Test"
procedure AddDimToTempLine(SalesLine: Record "Sales Line"; var TempDimSetEntry: Record "Dimension Set Entry")

Thanks

Denis

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
