### ISSUE TITLE
job integration sales/purchase

### ISSUE THREAD

**Issue by stephanweidmann** [microsoft/ALAppExtensions#1663]
the standard purchase documents only supports direct purchase invoices. if you only ship an item, there is no job ledger entry, and no usage on the job, the job ledger entry will be created after invoicing the document.

If I want to be able to change this, so that the shipping already creates an item ledger entry and a job ledger entry, this is not possible with events right now. So, I thought about copying codeunit 90. But, to support at least other extensions, it would be cool to call the publishers from codeunit 90 from the copy.

This would work for all publishers except one: in OnBeforeItemJnlPostLine, the globalvar Access is activated.

This could even be used for posting prepayments (as an example where a codeunit has been duplicated for a special requirement...).

For CU 80, making the publishers global would also support new business cases.

**Comment by StanPesotskiy** [comment]
All events are going to be local functions and global var access may be discontinued in future versions. 
You may suggest a refactoring of CU80/90 so you would have entry points that enable your customisation.
