### ISSUE TITLE
[Event Parameter change] table 246 "Requisition Line" - OnBeforeSetReplenishmentSystemFromProdOrder

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16632]
There is an issue between different replenishment methods on Item and Stockkeeping Unit cards in a certain data setup. We would like this fixed in our vertical. Below mentioned changes are needed:

    local procedure SetReplenishmentSystemFromProdOrder(StockkeepingUnit: Record "Stockkeeping Unit")
    var
        NoSeriesMgt: Codeunit NoSeriesManagement;
        IsHandled: Boolean;
        ProductionBOMNo: Code[20];
        RoutingNo: Code[20];
        ShouldShowReplenishmentError: Boolean;
    begin
        //A108B0055.Event.19.05.os
        //OnBeforeSetReplenishmentSystemFromProdOrder(Rec);
        //
        //if ReqWkshTmpl.Get("Worksheet Template Name") and
        //   (ReqWkshTmpl.Type = ReqWkshTmpl.Type::"Req.") and (ReqWkshTmpl.Name <> '') and not "Drop Shipment"
        //then
        //A108B0055.Event.19.05.oe
        //A108B0055.Event.19.05.ns
        ShouldShowReplenishmentError := ReqWkshTmpl.Get("Worksheet Template Name") and (ReqWkshTmpl.Type = ReqWkshTmpl.Type::"Req.") and (ReqWkshTmpl.Name <> '') and not "Drop Shipment";
        OnBeforeSetReplenishmentSystemFromProdOrder(Rec, Item, ShouldShowReplenishmentError);
        if ShouldShowReplenishmentError then
            //A108B0055.Event.19.05.ne
            Error(ReplenishmentErr);

        if PlanningResiliency and (Item."Base Unit of Measure" = '') then
            TempPlanningErrorLog.SetError(
              StrSubstNo(Text032, Item.TableCaption, Item."No.", Item.FieldCaption("Base Unit of Measure")),
              DATABASE::Item, Item.GetPosition);

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetReplenishmentSystemFromProdOrder(var RequisitionLine: Record "Requisition Line"; Item: Record Item; var ShouldShowReplenishmentError: Boolean)
    begin
        //A108B0055.Event.19.05 Parameter Item, ShouldShowReplenishmentError
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
