### ISSUE TITLE
[Event Request] Codeunit 10750 "SII XML Creator" - OnInitPurchXMLBodyOnBeforeFillThirdPartyID

### ISSUE THREAD

**Issue by LdrAms** [microsoft/ALAppExtensions#16638]
Hi,

We need a new event in codeunit 10750 "SII XML Creator" at "InitializePurchXmlBody" procedure. It should be `OnInitPurchXMLBodyOnBeforeFillThirdPartyID()`, so we can take the vendor info from the purchase document insteed of from the Vendor card (generic vendors).

The "InitializePurchXmlBody" should be extended with a new paramenter VendLedgEntry.

New Event: `OnInitPurchXMLBodyOnBeforeFillThirdPartyID(var VendLedgEntry, var AlXmlNode, IDType, var isHandled);`

```
local procedure InitializePurchXmlBody(var XMLNode: DotNet XmlNode; VendorNo: Code[20]; PostingDate: Date; IDType: Enum "SII ID Type")
    var
        Vendor: Record Vendor;
        TempXMLNode: DotNet XmlNode;
    begin
        XMLDOMManagement.AddElementWithPrefix(XMLNode, 'RegistroLRFacturasRecibidas', '', 'siiLR', SiiLRTxt, XMLNode);
        XMLDOMManagement.AddElementWithPrefix(XMLNode, FillDocHeaderNode, '', 'sii', SiiTxt, XMLNode);
        XMLDOMManagement.AddElementWithPrefix(
          XMLNode, 'Ejercicio', GetYear(PostingDate), 'sii', SiiTxt, TempXMLNode);
        XMLDOMManagement.AddElementWithPrefix(
          XMLNode, 'Periodo', Format(PostingDate, 0, '<Month,2>'), 'sii', SiiTxt, TempXMLNode);
        XMLDOMManagement.FindNode(XMLNode, '..', XMLNode);
        XMLDOMManagement.AddElementWithPrefix(XMLNode, 'IDFactura', '', 'siiLR', SiiLRTxt, XMLNode);
        XMLDOMManagement.AddElementWithPrefix(XMLNode, 'IDEmisorFactura', '', 'sii', SiiTxt, XMLNode);
        Vendor.Get(VendorNo);
	//NEW Event
	//From DotNet XMLNode to Al XmlNode
	OnInitPurchXMLBodyOnBeforeFillThirdPartyID(var VendLedgEntry, var AlXmlNode, IDType, var isHandled);
	if isHandled then
		begin
			//From Al XmlNode to DotNet XMLNode
				
		end
	else
        //END New Event		
		FillThirdPartyId(...
end;
```
		
Thanks,
Alejandro

**Comment by LdrAms** [comment]
Hi, I know it, this is why I'm requesting an event with an **XMLNode **AL**** type NOT DotNet type. You should then convert it back again as you did in this same coudeunit at procedure `GenerateXml `in the event `OnBeforeGenerateXmlDocument`
Please reconsider it.
Thanks

**Comment by Oleg-Romashkov** [comment]
Parameters VendLedgEntry and AlXmlNode do not exist. Please provide full needed AL code, which could be compiled

**Comment by LdrAms** [comment]
Yes, this is why I'm also need that "The "InitializePurchXmlBody" be extended with a new paramenter VendLedgEntry". And procedure should be modifed as it was the function GenerateXml (in this same codeunit) in order to convert the DotNET XmlNode to AL XmlNode

**Comment by Oleg-Romashkov** [comment]
You will help implement this event faster if you provide full required AL code update for this.

**Comment by LdrAms** [comment]
Hi,

It could be something like that (note that function InitializePurchXmlBody should be modified to receive VendLedgEntry). The objective is to change the info relative to the ThirdParty with data from the Purchase Invoice insted from the Vendor
New Event: OnInitializePurchXmlBodyOnAfterFillThirdParty(var innerXML : Text; VendorLedgerEntry: Record "Vendor Ledger Entry")

```
local procedure InitializePurchXmlBody(var XMLNode: DotNet XmlNode; VendorNo: Code[20]; PostingDate: Date; IDType: Enum "SII ID Type"; VendorLedgerEntry: Record "Vendor Ledger Entry")
    var
        Vendor: Record Vendor;
        TempXMLNode: DotNet XmlNode;
    begin
        XMLDOMManagement.AddElementWithPrefix(XMLNode, 'RegistroLRFacturasRecibidas', '', 'siiLR', SiiLRTxt, XMLNode);
        XMLDOMManagement.AddElementWithPrefix(XMLNode, FillDocHeaderNode, '', 'sii', SiiTxt, XMLNode);
        XMLDOMManagement.AddElementWithPrefix(
          XMLNode, 'Ejercicio', GetYear(PostingDate), 'sii', SiiTxt, TempXMLNode);
        XMLDOMManagement.AddElementWithPrefix(
          XMLNode, 'Periodo', Format(PostingDate, 0, '<Month,2>'), 'sii', SiiTxt, TempXMLNode);
        XMLDOMManagement.FindNode(XMLNode, '..', XMLNode);
        XMLDOMManagement.AddElementWithPrefix(XMLNode, 'IDFactura', '', 'siiLR', SiiLRTxt, XMLNode);
        XMLDOMManagement.AddElementWithPrefix(XMLNode, 'IDEmisorFactura', '', 'sii', SiiTxt, XMLNode);
        Vendor.Get(VendorNo);
		FillThirdPartyId(
          XMLNode, Vendor."Country/Region Code", Vendor.Name, Vendor."VAT Registration No.", Vendor."No.", false,
          SIIManagement.VendorIsIntraCommunity(Vendor."No."), false, IDType);
	 //NEW Event
	 OnInitializePurchXmlBodyOnAfterFillThirdParty(var XMLNode.InnerXML, VendLedgEntry)		
end;
```
Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
