### ISSUE TITLE
[Request Enum] table 246 "Requisition Line" - "Planning Line Origin"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16630]
In out vertical we have an item layout specification planning worksheet and added an option. Please make it extensible.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
