### ISSUE TITLE
[Event Request] Wrap calls to DimMgmt's GetRecDefaultDimID procedure to allow replacing the call to it

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#16633]
Thank you for getting #16651 into a future update.

As I continue to review our needs regarding dimensions, unfortunately I have quite a few more event requests.  

The root of it all is that for a number of the calls into DimensionManagement we need to process more information than just two dimension codes, so calls that have only the two dimensions we are needing to handle with a change somehow.

I've been trying to see for each procedure that I review if there is a way change the DimMgmt procedure itself, without upending the code too much, but not being successful.  The event wrapper around the procedure calls seems to be the most practical and flexible route that I can think of so far.  Some of the requested procedures to change below have an OnAfterCreateDimTableIDs event just before the place I am requesting to add the event, with a IsHandled/exit pattern to end the procedure, but because of the additional code and some events and calls that are defined local, and not all the parameters needed passed into it, still need to request the new event.

My request is to wrap the GetRecDefaultDimID() procedure calls with an even that can replace the original call, and allow the rest of the procedure to run.  Here is an example of the requested event added to wrap a GetRecDefaultDimID call:

```
table 900 "Assembly Header"
...
    procedure CreateDim(Type1: Integer; No1: Code[20])
    var
        SourceCodeSetup: Record "Source Code Setup";
        DimMgt: Codeunit DimensionManagement;
        TableID: array[10] of Integer;
        No: array[10] of Code[20];
        IsHandled: Boolean;  // NEW VAR
    begin
        SourceCodeSetup.Get();
        TableID[1] := Type1;
        No[1] := No1;
        OnAfterCreateDimTableIDs(Rec, CurrFieldNo, TableID, No);
        "Shortcut Dimension 1 Code" := '';
        "Shortcut Dimension 2 Code" := '';
        // NEW CODE begin
        IsHandled := false;
        OnCreateDimOnBeforeGetRecDefaultDimID(Rec, CurrFieldNo, TableID, No, SourceCodeSetup.Assembly, 0, 0, IsHandled, "Dimension Set ID");
        if not IsHandled then
        // NEW CODE end, following statement can be indented
        "Dimension Set ID" :=
          DimMgt.GetRecDefaultDimID(
            Rec, CurrFieldNo, TableID, No, SourceCodeSetup.Assembly,
            "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code", 0, 0);
        if "No." <> '' then
            DimMgt.UpdateGlobalDimFromDimSetID(
              "Dimension Set ID",
              "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");
    end;
...
    [IntegrationEvent(false, false)]
    local procedure OnCreateDimOnBeforeGetRecDefaultDimID(RecVariant: Variant; CurrFieldNo: Integer; TableID: array[10] of Integer; No: array[10] of Code[20]; SourceCode: Code[20]; InheritFromDimSetID: Integer; InheritFromTableNo: Integer; var IsHandled: Boolean; var ResultDimSetID: Integer)
    begin

    end;

```

For the event definition, it is the same parameters as the GetRecDefaultDimID, less the two dimension parameters.  I then add the IsHandled, and the variable that the return dimension set ID variable that the value will go into.  I needed to do that because I found a few calls that were returning into a local variable rather than a field in the passed record variable.  This is a bit different than the event definition I requested in 16551.

Here is a list of all the places I have found with the call to GetRecDefaultDimID to be wrapped.  Most are in CreateDim procedures from tables (or in routines called from it), but there are a few at the bottom in other objects:

table 900 "Assembly Header"
procedure CreateDim(Type1: Integer; No1: Code[20])

table 901 "Assembly Line"
procedure CreateDim(Type1: Integer; No1: Code[20]; HeaderDimensionSetID: Integer)
- 2 calls, same code, but setting different variable

table 273 "Bank Acc. Reconciliation"
procedure CreateDim(Type1: Integer; No1: Code[20])

table 274 "Bank Acc. Reconciliation Line"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20])

table 5621 "FA Journal Line"
procedure CreateDim(Type1: Integer; No1: Code[20])

table 302 "Finance Charge Memo Header"
procedure CreateDim(Type1: Integer; No1: Code[20])

table 221 "Gen. Jnl. Allocation"
procedure CreateDim(Type1: Integer; No1: Code[20])

table 81 "Gen. Journal Line"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20]; Type4: Integer; No4: Code[20]; Type5: Integer; No5: Code[20])

table 5635 "Insurance Journal Line"
procedure CreateDim(Type1: Integer; No1: Code[20])

table 83 "Item Journal Line"
local procedure PickDimension(TableArray: array[10] of Integer; CodeArray: array[10] of Code[20]; InheritFromDimSetID: Integer; InheritFromTableNo: Integer)

table 210 "Job Journal Line"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20])

table 99000829 "Planning Component"
procedure CreateDim(Type1: Integer; No1: Code[20])

table 5407 "Prod. Order Component"
procedure CreateDim(Type1: Integer; No1: Code[20])

table 5406 "Prod. Order Line"
procedure CreateDim(Type1: Integer; No1: Code[20])

table 5405 "Production Order"
procedure CreateDim(Type1: Integer; No1: Code[20])

table 38 "Purchase Header"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20]; Type4: Integer; No4: Code[20])

table 39 "Purchase Line"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20]; Type4: Integer; No4: Code[20])

table 295 "Reminder Header"
procedure CreateDim(Type1: Integer; No1: Code[20])

table 246 "Requisition Line"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20])

table 207 "Res. Journal Line"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20])

table 36 "Sales Header"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20]; Type4: Integer; No4: Code[20]; Type5: Integer; No5: Code[20])

table 37 "Sales Line"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20])

table 5965 "Service Contract Header"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20]; Type4: Integer; No4: Code[20]; Type5: Integer; No5: Code[20])

table 5900 "Service Header"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20]; Type4: Integer; No4: Code[20]; Type5: Integer; No5: Code[20])

table 5901 "Service Item Line"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20])

table 5902 "Service Line"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20])

table 751 "Standard General Journal Line"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20]; Type4: Integer; No4: Code[20]; Type5: Integer; No5: Code[20])

table 753 "Standard Item Journal Line"
procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20])

table 5997 "Standard Service Line"
procedure CreateDim(Type1: Integer; No1: Code[20])

table 5741 "Transfer Line"
procedure CreateDim(Type1: Integer; No1: Code[20])

report 20 "Calc. and Post VAT Settlement"
local procedure PostGenJnlLine(var GenJnlLine: Record "Gen. Journal Line")

table 846 "Cash Flow Worksheet Line"
procedure MoveDefualtDimToJnlLineDim(TableID: Integer; No: Code[20]; var DimensionSetID: Integer)
- This code does not pass in table fields for the dim parameters

codeunit 444 "Purchase-Post Prepayments"
local procedure CreateDimensions(var PurchLine: Record "Purchase Line")
	
codeunit 442 "Sales-Post Prepayments"
local procedure CreateDimensions(var SalesLine: Record "Sales Line")

Thank you,

Denis

**Comment by Oleg-Romashkov** [comment]
Hi Denis,

I would try to find a solution based on existing function DimMgt.GetRecDefaultDimID. Could you please provide more detailed scenario for requested event? Maybe we can find another way to resolve it.

Rgds,
Oleg.

**Comment by SER-denisg** [comment]
Hi Oleg,

Thank you for your response.  I know these requests that I have made are a fair number of areas to change, I hope we can find some way to minimize it.

What is causing this request on our end is that we extend the dimensions to have 8 global dimensions (and potentially some other fields as well).  When I run across calls that pass in Dimensions 1&2, and not a record variable or some other structure, I don't have a way to be able to update our fields as I don't have anything coming into the function that I can use to identify the specific record, or to have that instance of that record.  The TableID and No arrays being passed in are usually other codes on the record, not the record itself.

That is where the thought of putting an event with an IsHandled code pattern in place seemed to be the most practical, and smallest code impact.

I have thought about a single point of change in the GetRecDefaultDimID procedure, putting in an event in there, but the locating the correct record instance issue is still present.  There is not enough information going into the call to locate the record, but the issue also becomes that the current record variable is not saved yet, so I would not be able to get the correct values from the database.  I would imagine passing in a record variable as a variant is not something you want to entertain, that would affect every call in the system too.

We have used a persistent codeunit to pass in data in an event before another event call that needs it, but for record variables it appears to be a static copy which won't work well with code like my example, as the record variable changes with the calls and is not saved, so I can't retrieve updated values.

The last thing that I thought of is to just create a procedure level event at the start that can bypass the entire procedure with and IsHandled code pattern.  Issues I can see with this is mostly the result of other code being accessed in these procedures being local in scope, which would cause my event subscriber code to not be able to access them unless they change too. For example, I would not be able to fire the OnAfterCreateDimTableIDs event as it is local in scope.  This one I can see as doable, by making a number of events and procedures not local in scope, but there are a few more complex procedures that this is called from (processing loops mainly) that would still lend itself better for another way.

Unfortunately I have not been able to come up with any better solutions for this and a few other DImMgt calls, mostly the ones that pass in the two dimensions and return a DimSetID, they are just updating a lot of information.  There was one that was able to find other ways (other events present to use mainly).  In my code example above, calls to UpdateGlobalDimFromDimSetID I was able to use other events, as internally this procedure is more passive and direct (although I needed some more generic events added in some places where there was nothing existing I could use, #16803),

This has been an interesting challenge to find something that will work the best, I hope this sheds some light on the nature of our request and the issues I have with the other methods I have considered.  I look forward to your input!  

Thanks,

Denis

**Comment by Oleg-Romashkov** [comment]
Hi Denis,

Thank you for detailed explanation. Taking into account your other requests in this area I'm going to create handled events OnBeforeCreateDim as we already have for major document and journal tables.

Rgds,
Oleg.

**Comment by Oleg-Romashkov** [comment]
Hi Denis,

One more point. The majority of CreateDim functions have OnAfterCreateDim(Rec, xRec) event. Is it ok for you to update record fields based on dimension set id?

Oleg.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
