### ISSUE TITLE
[Event Request] table 37 "Sales Line" - OnBeforeCalcPlannedDeliveryDate

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16646]
We would like the use of existing event OnBeforeCalcPlannedDeliveryDate in the validate trigger of field "Requested Delivery Date" by applying and enhancing the existing function CalcPlannedDeliveryDate. The code changes can be found with tag 'A108B0037'

        field(5790; "Requested Delivery Date"; Date)
        {
            Caption = 'Requested Delivery Date';

            trigger OnValidate()
            begin
                TestStatusOpen();
                CheckPromisedDeliveryDate();

                if "Requested Delivery Date" <> 0D then
                    //Validate("Planned Delivery Date", "Requested Delivery Date") A108B0037.Event.19.05.o
                    Validate("Planned Delivery Date", CalcPlannedDeliveryDate(FieldNo("Requested Delivery Date"))) //A108B0037.Event.19.05.n
                else begin
                    GetSalesHeader();
                    Validate("Shipment Date", SalesHeader."Shipment Date");
                end;
            end;
        }

    procedure CalcPlannedDeliveryDate(CurrFieldNo: Integer) PlannedDeliveryDate: Date
    var
        CustomCalendarChange: Array[2] of Record "Customized Calendar Change";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        PlannedDeliveryDate := "Planned Delivery Date";
        OnBeforeCalcPlannedDeliveryDate(Rec, PlannedDeliveryDate, CurrFieldNo, IsHandled);
        if IsHandled then
            exit(PlannedDeliveryDate);

        //A108B0037.Event.19.05.ns
        if CurrFieldNo = FieldNo("Requested Delivery Date") then
            exit("Requested Delivery Date");
        //A108B0037.Event.19.05.ne
        if "Shipment Date" = 0D then
            exit("Planned Delivery Date");

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
