### ISSUE TITLE
[Event Request] Table 1001 - Job Task - ValidateShortcutDimCode

### ISSUE THREAD

**Issue by programmierenlol** [microsoft/ALAppExtensions#16640]
Dear ALAppExtensions team,

Through this issue we would like to request changes to event publisher OnBeforeValidateShortcutDimCode in Table 1001 - Job Task in procedure ValidateShortcutDimCode to get access to JobTask2:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateShortcutDimCode(var JobTask: Record "Job Task"; var xJobTask: Record "Job Task"; var JobTask2: Record "Job Task"; FieldNumber: Integer; var ShortcutDimCode: Code[20])
    begin
    end;

This would result in the following change in procedure ValidateShortcutDimCode

    procedure ValidateShortcutDimCode(FieldNumber: Integer; var ShortcutDimCode: Code[20])
    var
        JobTask2: Record "Job Task";
    begin
        OnBeforeValidateShortcutDimCode(Rec, xRec, JobTask2, FieldNumber, ShortcutDimCode);

        DimMgt.ValidateDimValueCode(FieldNumber, ShortcutDimCode);
        if JobTask2.Get("Job No.", "Job Task No.") then begin
            DimMgt.SaveJobTaskDim("Job No.", "Job Task No.", FieldNumber, ShortcutDimCode);
            Modify;
        end else
            DimMgt.SaveJobTaskTempDim(FieldNumber, ShortcutDimCode);

        OnAfterValidateShortcutDimCode(Rec, xRec, FieldNumber, ShortcutDimCode);
    end;

**Comment by Oleg-Romashkov** [comment]
Hi,
Why do you need this local variable which used only for condition if JobTask2.Get?

**Comment by programmierenlol** [comment]
To be able to do a Changecompany on the JobTask2.
