### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - Function CreateGLEntryBalAcc

### ISSUE THREAD

**Issue by swecompany** [microsoft/ALAppExtensions#16645]
Hello,
would it be possible to get an event OnBeforeCreateGLEntryBalAcc at the beginning of the Function CreateGLEntryBalAcc like this:

[IntegrationEvent(false, false)]
local procedure OnBeforeCreateGLEntryBalAcc(var GenJournalLine: Record "Gen. Journal Line"; var AccNo: Code[20]; Amount: Decimal; AmountAddCurr: Decimal; var BalAccType: Enum "Gen. Journal Account Type"; var BalAccNo: Code[20])
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
