### ISSUE TITLE
[Global request] - Make all integration events external

### ISSUE THREAD

**Issue by RHansenEpimatic** [microsoft/ALAppExtensions#1664]
We are migrating a NAV add-on to BC.  Our add-on makes some changes to posting routines (eg. CDU 12, CDU 80, CDU 90) that cannot be implemented currently using existing integration events.  I will be submitting requests for new events, but in the meantime our approach here is to duplicate the base posting codeunits to our own versions, and then modify them.  We will then use provided events (such as OnBeforeCode in codeunit 12) to divert the logic to our versions and (in the case of codeunit 12) set the "IsPosted" flag to True to abort the base process.  This is just a short-term measure.

Our concern here is if the customer has multiple add-ons, other add-ons might subscribe to the integration events in codeunit 12.  In our product copy of codeunit 12, we would like to set the various integration events to call the events over in the base codeunit 12 (rather than in our custom codeunit) so that other ISV add-ons still pick up the events and work correctly.  Currently, we are unable to do this because the integration events in codeunit 12 (and the other codeunits) are all local so our codeunit cannot see/call them.

Would it be possible to make all integration events external so that the scenario above is possible?

**Comment by AlexanderYakunin** [comment]
No, all events needs to stay as LOCAL. Only procedures can be made global and external.
