### ISSUE TITLE
[Event Request] codeunit "Calculate Normal Depreciation" - OnBeforeNumberofDayCalculateNumberofDays

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#16654]
Please modify event `OnBeforeNumberofDayCalculateNumberofDays` in procedure CalculateDeprAmount in codeunit "Calculate Normal Depreciation"

The reason is that we need to set UntilDate to FADepreciationBook."Depreciation Ending Date" of that is earlier. There is currently no way to overwrite UntilDate.

Original event:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeNumberofDayCalculateNumberofDays(
        FixedAsset: Record "Fixed Asset";
        DeprBook: Record "Depreciation Book";
        var NumberofDays: Integer;
        FirstDeprDate: date;
        UntilDate: Date;
        Year365Days: Boolean;
        var IsHandled: Boolean)
    begin
    end;
```

Modified event:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeNumberofDayCalculateNumberofDays(
        FixedAsset: Record "Fixed Asset";
        DeprBook: Record "Depreciation Book";
        FADepreciationBook: Record "FA Depreciation Book"; // <-- NEW PARAMETER
        var NumberofDays: Integer;
        FirstDeprDate: date;
        var UntilDate: Date;  // <-- ADDED var
        Year365Days: Boolean;
        var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
