### ISSUE TITLE
C7000.OnBeforeSalesLinePriceExistsProcedure() param must be VAR

### ISSUE THREAD

**Issue by ariweinda** [microsoft/ALAppExtensions#16656]
C7000
local procedure OnBeforeSalesLinePriceExistsProcedure(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; ShowAll: Boolean; TempSalesPrice: Record "Sales Price" temporary; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;

TempSalesPrice must obviously be VAR

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
