### ISSUE TITLE
[Event Request] table 5902 "Service Line" - OnValidateApplToItemEntryOnBeforeShowNotOpenItemLedgerEntryMessage

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16669]
field(38; "Appl.-to Item Entry"; Integer)
        {
            AccessByPermission = TableData Item = R;
            Caption = 'Appl.-to Item Entry';

            trigger OnLookup()
            begin
                SelectItemEntry(FieldNo("Appl.-to Item Entry"));
            end;

            trigger OnValidate()
            var
                ItemLedgEntry: Record "Item Ledger Entry";
            begin
                if "Appl.-to Item Entry" <> 0 then begin
                    TestField(Type, Type::Item);
                    TestField(Quantity);

                    ItemLedgEntry.Get("Appl.-to Item Entry");
                    ItemLedgEntry.TestField(Positive, true);
                    Validate("Unit Cost (LCY)", CalcUnitCost(ItemLedgEntry));
                    "Location Code" := ItemLedgEntry."Location Code";
                    OnValidateApplToItemEntryOnBeforeShowNotOpenItemLedgerEntryMessage(Rec, xRec, ItemLedgEntry, CurrFieldNo); //A108B0068.Event.19.05
                    if not ItemLedgEntry.Open then
                        Message(Text042, "Appl.-to Item Entry");
                end;
            end;
        }

    [IntegrationEvent(false, false)]
    local procedure OnValidateApplToItemEntryOnBeforeShowNotOpenItemLedgerEntryMessage(var ServiceLine: Record "Service Line"; xServiceLine: Record "Service Line"; var ItemLedgerEntry: Record "Item Ledger Entry"; CurrFieldNo: Integer)
    begin
        //A108B0068.Event.19.05
    end;

**Comment by AlexanderYakunin** [comment]
Can you explain the purpose of this event? You want to skip message?

**Comment by Duizy1971** [comment]
Hi Alexander,

The problem is that code:
"Location Code" := ItemLedgEntry."Location Code"
has a bug because it does not perform a validation and therefor the Bin Code handling is completely off. 
In Cronus W1 you can fill in an item ledger entry no. which has LocationCode=BLUE while the line itself has LocationCode=SILVER with a BinCode. Then all of a sudden the Line has LocationCode=Blue with still a BinCode of LocationCode=SILVER.

I should use the ServicesHub to enter an issue there but it took us till earlier this week to get access to that. So I've been fixing things with events for the last couple of years.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
