### ISSUE TITLE
Codeunits 313, 314, 315, 316, 318, 319, 320, 6651, 6661 - OnBeforePrinted event

### ISSUE THREAD

**Issue by rgrygoryshchak** [Microsoft/ALAppExtensions#1666]
Hi,

   We need new event to suppress "No. Printed" field increment in codeunits 313, 314, 315, 316, 318, 319, 320, 6651, 6661:

`LOCAL [IntegrationEvent] OnBeforePrinted(VAR SalesInvoiceHeader : Record "Sales Invoice Header";VAR IsHandled : Boolean)
` 

   Usage for codeunit 315:

**OnRun(VAR Rec : Record "Sales Invoice Header")**
```
//New Code >>
OnBeforePrinted(Rec,Handled);
IF Handled THEN
  EXIT;
//New Code <<

FIND;
"No. Printed" := "No. Printed" + 1;
OnBeforeModify(Rec);
MODIFY;
COMMIT;

```

Regards, Roman.

**Comment by AlexanderYakunin** [comment]
All these events already implemented

**Comment by rgrygoryshchak** [comment]
In what version events are implemented?

**Comment by AlexanderYakunin** [comment]
Implemented August 2, 2018, available in cloud and onPrem. Are you looking into NAV 2018 code?

**Comment by rgrygoryshchak** [comment]
Business Central build 13.0.27390

Codeunit 315

**OnRun(VAR Rec : Record "Sales Invoice Header")**
```
FIND;
"No. Printed" := "No. Printed" + 1;
OnBeforeModify(Rec);
MODIFY;
COMMIT;
``` 

You have OnBeforeModify event, but it does not allow to suppress update!
