### ISSUE TITLE
[Event ReRequest] table 5902 "Service Line" - OnAfterInitOutstandingQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16674]
https://github.com/microsoft/ALAppExtensions/issues/13393

I'm looking in 20.0.37145.0 and this issue has not been dealt with yet as it seems.

**Comment by AlexanderYakunin** [comment]
You should be aware that code freeze for release happens several weeks before release date, and request event few months earlier. This event is implemented in 20.x and will be available in 20.1
