### ISSUE TITLE
[Event Request] codeunit 99000854 "Inventory Profile Offsetting", OnAfterAdjustPlanLineOnBeforeModify

### ISSUE THREAD

**Issue by GiulioBeckmann** [microsoft/ALAppExtensions#16673]
local procedure MaintainPlanningLine(var SupplyInvtProfile: Record "Inventory Profile"; DemandInvtProfile: Record "Inventory Profile"; NewPhase: Option " ","Line Created","Routing Created",Exploded,Obsolete; Direction: Option Forward,Backward)
    var
        PurchaseLine: Record "Purchase Line";
        ProdOrderLine: Record "Prod. Order Line";
        AsmHeader: Record "Assembly Header";
        TransLine: Record "Transfer Line";
        CurrentSupplyInvtProfile: Record "Inventory Profile";
        PlanLineNo: Integer;
        RecalculationRequired: Boolean;
    begin
        if (NewPhase = NewPhase::"Line Created") or
           (SupplyInvtProfile."Planning Line Phase" < SupplyInvtProfile."Planning Line Phase"::"Line Created")
        then
            if SupplyInvtProfile."Planning Line No." = 0 then
                with ReqLine do begin
                    BlockDynamicTracking(true);
                    if FindLast then
                        PlanLineNo := "Line No." + 10000
                    else
                        PlanLineNo := 10000;

                    Init();
                    "Worksheet Template Name" := CurrTemplateName;
                    "Journal Batch Name" := CurrWorksheetName;
                    "Line No." := PlanLineNo;
                    Type := Type::Item;
                    "No." := SupplyInvtProfile."Item No.";
                    "Variant Code" := SupplyInvtProfile."Variant Code";
                    "Location Code" := SupplyInvtProfile."Location Code";
                    "Bin Code" := SupplyInvtProfile."Bin Code";
                    "Planning Line Origin" := "Planning Line Origin"::Planning;
                    OnMaintainPlanningLineOnAfterPopulateReqLineFields(ReqLine, SupplyInvtProfile, DemandInvtProfile, NewPhase, Direction, TempSKU);
                    if SupplyInvtProfile."Action Message" = SupplyInvtProfile."Action Message"::New then begin
                        "Order Date" := SupplyInvtProfile."Due Date";
                        "Planning Level" := SupplyInvtProfile."Planning Level Code";
                        case TempSKU."Replenishment System" of
                            TempSKU."Replenishment System"::Purchase:
                                "Ref. Order Type" := "Ref. Order Type"::Purchase;
                            TempSKU."Replenishment System"::"Prod. Order":
                                begin
                                    "Ref. Order Type" := "Ref. Order Type"::"Prod. Order";
                                    if "Planning Level" > 0 then begin
                                        "Ref. Order Status" := SupplyInvtProfile."Primary Order Status";
                                        "Ref. Order No." := SupplyInvtProfile."Primary Order No.";
                                    end;
                                end;
                            TempSKU."Replenishment System"::Assembly:
                                "Ref. Order Type" := "Ref. Order Type"::Assembly;
                            TempSKU."Replenishment System"::Transfer:
                                "Ref. Order Type" := "Ref. Order Type"::Transfer;
                        end;
                        OnMaintainPlanningLineOnBeforeValidateNo(ReqLine, SupplyInvtProfile, TempSKU);
                        Validate("No.");
                        Validate("Unit of Measure Code", SupplyInvtProfile."Unit of Measure Code");
                        "Starting Time" := ManufacturingSetup."Normal Starting Time";
                        "Ending Time" := ManufacturingSetup."Normal Ending Time";
                    end else
                        case SupplyInvtProfile."Source Type" of
                            DATABASE::"Purchase Line":
                                SetPurchase(PurchaseLine, SupplyInvtProfile);
                            DATABASE::"Prod. Order Line":
                                SetProdOrder(ProdOrderLine, SupplyInvtProfile);
                            DATABASE::"Assembly Header":
                                SetAssembly(AsmHeader, SupplyInvtProfile);
                            DATABASE::"Transfer Line":
                                SetTransfer(TransLine, SupplyInvtProfile);
                        end;

                    OnMaintainPlanningLineOnBeforeAdjustPlanLine(ReqLine, SupplyInvtProfile, TempSKU);
                    AdjustPlanLine(SupplyInvtProfile);
                    "Accept Action Message" := true;
                    "Routing Reference No." := "Line No.";
                    UpdateDatetime;
                    "MPS Order" := SupplyInvtProfile."MPS Order";
                    OnMaintainPlanningLineOnBeforeReqLineInsert(
                      ReqLine, SupplyInvtProfile, PlanToDate, CurrForecast, NewPhase, Direction, DemandInvtProfile, ExcludeForecastBefore);
                    Insert;
                    OnMaintainPlanningLineOnAfterReqLineInsert(ReqLine);
                    SupplyInvtProfile."Planning Line No." := "Line No.";
                    if NewPhase = NewPhase::"Line Created" then
                        SupplyInvtProfile."Planning Line Phase" := SupplyInvtProfile."Planning Line Phase"::"Line Created";
                end else begin
                if SupplyInvtProfile."Planning Line No." <> ReqLine."Line No." then
                    ReqLine.Get(CurrTemplateName, CurrWorksheetName, SupplyInvtProfile."Planning Line No.");
                ReqLine.BlockDynamicTracking(true);
                AdjustPlanLine(SupplyInvtProfile);

    OnAfterAdjustPlanLineOnBeforeModify(TempSKU,ReqLine,SupplyInvtProfile,PlanToDate,CurrForecast,NewPhase,Direction,DemandInvtProfile)

                if NewPhase = NewPhase::"Line Created" then
                    ReqLine.Modify();
            end;

[IntegrationEvent(false, false)]
local procedure OnAfterAdjustPlanLineOnBeforeModify(var TempSKU: Record "Stockkeeping Unit" temporary; var RequisitionLine: Record "Requisition Line"; var SupplyInvtProfile: Record "Inventory Profile"; PlanToDate: Date; CurrentForecast: Code[10]; NewPhase: Option " ","Line Created","Routing Created",Exploded,Obsolete; Direction: Option Forward,Backward; DemandInvtProfile: Record "Inventory Profile")
begin

end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
