### ISSUE TITLE
[Bugfix] CH-Localization "Sales Shipment Line".HasTypeToFillMandatoryFields()

### ISSUE THREAD

**Issue by CptBlaubart** [microsoft/ALAppExtensions#16702]
Request:
Please adjust the "Sales Shipment Line".HasTypeToFillMandatoryFields() procedure to behave as the other counterparts in the "Sales Invoice Line" and "Sales Cr. Memo Lines" do.

Background: The CH-Localization has an alteration to W1 on the "Sales Line Type"-Enum there are 4 more values:
```
[...]
    value(6; "Title") { Caption = 'Title'; }
    value(7; "Begin-Total") { Caption = 'Begin-Total'; }
    value(8; "End-Total") { Caption = 'End-Total'; }
    value(9; "New Page") { Caption = 'New Page'; }
```
Those Values are mostly there to improve the design of report outputs and have no effect on Ledger Entries etc.
In the current situation, when posting a Sales Order, the Type-Value of the posted Shipments get reset to " " instead of left alone, like it is the case on the invoices and Cr. Memo.

As an alternative: You could consider scratching the whole feature (or adapting it to W1) at the current state, those Types are poorly supported. You can't select them unless you enable ApplicationArea = advanced, you can't even enter a Title unless you supply your own events. - I haven't even checked the default Reports. 
However a lot of our swiss customers don't want to let go of those features as they allow a lot more freedom in the designing the documents going to their customers with very little effort.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
