### ISSUE TITLE
[Event Request] - Table 39 "Purchase Line" - OnValidateLineAmountOnAfterCalcMaxLineAmount

### ISSUE THREAD

**Issue by RobertJohnstoneEque2** [microsoft/ALAppExtensions#16706]
Hi,

In a recent version of BC, there has been code added to Table 39, Field 103 "Line Amount" OnValidate() trigger that calculates a local variable called MaxLineAmount.

Could you add an Event after MaxLineAmount is calculated, so that we can override the value of MaxLineAmount, perhaps called OnValidateLineAmountOnAfterCalcMaxLineAmount?

<img width="598" alt="EventRequest" src="https://user-images.githubusercontent.com/57365946/158823614-a3b15287-d9d0-4946-9ce8-8efa53d1ab20.PNG">

Thanks.
Robert

**Comment by Oleg-Romashkov** [comment]
Hi,
Please always put the full detailed signature of the requested events and the parameters passed in the call.
You help us implementing the requests faster when your request contains AL code copied from VSCode instead of screenshots.

**Comment by RobertJohnstoneEque2** [comment]
**[IntegrationEvent(false, false)]
local procedure OnValidateLineAmountOnAfterCalcMaxLineAmount(var MaxLineAmt: Decimal)
begin
end;**

field(103; "Line Amount"; Decimal)
        {
            AutoFormatExpression = "Currency Code";
            AutoFormatType = 1;
            CaptionClass = GetCaptionClass(FieldNo("Line Amount"));
            Caption = 'Line Amount';

            trigger OnValidate()
            var
                MaxLineAmount: Decimal;
            begin
                TestField(Type);
                TestField(Quantity);
                CheckDirectUnitCost();

                GetPurchHeader();
                "Line Amount" := Round("Line Amount", Currency."Amount Rounding Precision");
                MaxLineAmount := Round(Quantity * "Direct Unit Cost", Currency."Amount Rounding Precision");

               **OnValidateLineAmountOnAfterCalcMaxLineAmount(MaxLineAmount);**

                if "Line Amount" < 0 then
                    if "Line Amount" < MaxLineAmount then
                        Error(LineAmountInvalidErr);

                if "Line Amount" > 0 then
                    if "Line Amount" > MaxLineAmount then
                        Error(LineAmountInvalidErr);

                Validate("Line Discount Amount", MaxLineAmount - "Line Amount");
            end;
        }

**Comment by RobertJohnstoneEque2** [comment]
I have noticed that MS have now added a function called CheckLineAmount(). Is this the intended fix to this request?

If so, it won't work for what we need as MaxLineAmount is not being passed into CheckLineAmount() by variance, preventing me from amending the value of MaxLineAmount.

**Comment by RobertJohnstoneEque2** [comment]
My apologies, yes this will address my request.

Thanks for adding the new Event for us.
