### ISSUE TITLE
[Request Extensible Procedure] page 99000892 "Work Center Group Load Lines" - CalculateCapacity

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16716]
We would like to change the hard structure of procedure CalculateCapacity.
Currently the interface is

local procedure CalculateCapacity(var CapacityEffective: Decimal; var ProdOrderNeed: Decimal)

with both parameters from protected var WorkCenterGroup
but that provides poor extensibility. We like to propose a change to the following code and provide it with three events (which after all these years might not have the correct names)

    local procedure CalculateCapacity(var WorkCenterGroup: Record "Work Center Group")
    var
        WorkCenter: Record "Work Center";
        CalendarMgt: Codeunit "Shop Calendar Management";
    begin
        if CapacityUoM = '' then
            CapacityUoM := MfgSetup."Show Capacity In";
        WorkCenterGroup."Capacity (Effective)" := 0;
        WorkCenterGroup."Prod. Order Need (Qty.)" := 0;

        OnBeforeCalculateCapacity(WorkCenterGroup, CapacityUoM);

        WorkCenter.SetCurrentKey("Work Center Group Code");
        WorkCenter.SetRange("Work Center Group Code", WorkCenterGroup.Code);
        if WorkCenter.FindSet then
            repeat
                WorkCenterGroup.CopyFilter("Date Filter", WorkCenter."Date Filter");
                WorkCenter.CalcFields("Capacity (Effective)", "Prod. Order Need (Qty.)");
                WorkCenterGroup."Capacity (Effective)" += 
                  WorkCenter."Capacity (Effective)" *
                  CalendarMgt.TimeFactor(WorkCenter."Unit of Measure Code") /
                  CalendarMgt.TimeFactor(CapacityUoM);

                WorkCenterGroup."Prod. Order Need (Qty.)" +=
                  WorkCenter."Prod. Order Need (Qty.)" *
                  CalendarMgt.TimeFactor(WorkCenter."Unit of Measure Code") /
                  CalendarMgt.TimeFactor(CapacityUoM);

                OnAfterCalculateWorkCenterCapacity(WorkCenter, WorkCenterGroup, CapacityUoM);
            until WorkCenter.Next() = 0;

        OnAfterCalculateCapacity(WorkCenterGroup, CapacityUoM);
    end;

New events:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculateCapacity(var WorkCenterGroup: Record "Work Center Group"; CapacityUoM: Code[10])
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalculateCapacity(var WorkCenterGroup: Record "Work Center Group"; CapacityUoM: Code[10])
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalculateWorkCenterCapacity(var WorkCenter: Record "Work Center"; var WorkCenterGroup: Record "Work Center Group"; CapacityUoM: Code[10])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
