### ISSUE TITLE
[Event Request] Wrap calls to DimMgmt's GetCombinedDimensionSetID procedure to allow replacing the call to it

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#16713]
I am requesting some more calls into Dimension Management procedures that pass in global dimensions, this one is to wrap the calls to GetCombinedDimensionSetID with an IsHandled pattern so that the procedure call be replaced.  As with my other requests, I would like just the call wrapped rather than the calling's procedure to be completely covered with an IF IsHandled THEN exit; code pattern. 
In most cases, there is other code we need to have run that we cannot process in an event trigger, mostly because of local references, but for consistency, I would request that they all be patterned the same.

Here is an example of the code using the Assembly Line table:

```
table 901 "Assembly Line"
...
    procedure CreateDim(Type1: Integer; No1: Code[20]; HeaderDimensionSetID: Integer)
    var
        SourceCodeSetup: Record "Source Code Setup";
        AssemblySetup: Record "Assembly Setup";
        DimMgt: Codeunit DimensionManagement;
        TableID: array[10] of Integer;
        No: array[10] of Code[20];
        DimensionSetIDArr: array[10] of Integer;
        IsHandled: Boolean;  // NEW VAR (although requested in another event request)
    begin
        if SkipVerificationsThatChangeDatabase then
            exit;

        SourceCodeSetup.Get();
        TableID[1] := Type1;
        No[1] := No1;
        OnAfterCreateDimTableIDs(Rec, CurrFieldNo, TableID, No);

        "Shortcut Dimension 1 Code" := '';
        "Shortcut Dimension 2 Code" := '';
        AssemblySetup.Get();
        case AssemblySetup."Copy Component Dimensions from" of
            AssemblySetup."Copy Component Dimensions from"::"Order Header":
                begin
                    DimensionSetIDArr[1] :=
                      DimMgt.GetRecDefaultDimID(
                        Rec, CurrFieldNo, TableID, No, SourceCodeSetup.Assembly,
                        "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code",
                        0, 0);
                    DimensionSetIDArr[2] := HeaderDimensionSetID;
                end;
            AssemblySetup."Copy Component Dimensions from"::"Item/Resource Card":
                begin
                    DimensionSetIDArr[2] :=
                      DimMgt.GetRecDefaultDimID(
                        Rec, CurrFieldNo, TableID, No, SourceCodeSetup.Assembly,
                        "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code",
                        0, 0);
                    DimensionSetIDArr[1] := HeaderDimensionSetID;
                end;
        end;

        // NEW CODE begin
        IsHandled := false;  // added here as other calls above I also am requesting this code pattern using this var
        OnCreateDimOnBeforeGetCombinedDimensionSetID(Rec, DimensionSetIDArr, IsHandled, "Dimension Set ID");
        if not IsHandled then
        // NEW CODE end - next statement indented
        "Dimension Set ID" :=
          DimMgt.GetCombinedDimensionSetID(DimensionSetIDArr, "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");
    end;
...
    [IntegrationEvent(false, false)]
    local procedure OnCreateDimOnBeforeGetCombinedDimensionSetID(var AssemblyLine: Record "Assembly Line"; DimensionSetIDArr: array[10] of Integer; var IsHandled: Boolean; var DimSetID: Integer)
    begin
    end;

```

This trigger is a bit different, I am passing in a record variable to be able to access the two global dims and our additional information.  This may be different for each object event request below:

table 901 "Assembly Line"
    procedure CreateDim(Type1: Integer; No1: Code[20]; HeaderDimensionSetID: Integer)

codeunit 6620 "Copy Document Mgt."
    procedure TransfldsFromSalesToPurchLine(var FromSalesLine: Record "Sales Line"; var ToPurchLine: Record "Purchase Line")

page 1191 "Create Employee Payment"
    local procedure AssignCombinedDimensionSetID(var GenJournalLine: Record "Gen. Journal Line"; var DimSetIDArr: array[10] of Integer; NewDimensionID: Integer)

page 1190 "Create Payment"
    local procedure AssignCombinedDimensionSetID(var GenJournalLine: Record "Gen. Journal Line"; var DimSetIDArr: array[10] of Integer; NewDimensionID: Integer)

codeunit 5601 "FA Insert G/L Account"
    procedure InsertBufferBalAcc(FAPostingType: Enum "FA Posting Group Account Type"; AllocAmount: Decimal; DeprBookCode: Code[10]; PostingGrCode: Code[20]; GlobalDim1Code: Code[20]; GlobalDim2Code: Code[20]; DimSetID: Integer; AutomaticEntry: Boolean; Correction: Boolean)

codeunit 427 ICInboxOutboxMgt
    procedure CreateSalesDocument(ICInboxSalesHeader: Record "IC Inbox Sales Header"; ReplacePostingDate: Boolean; PostingDate: Date)
    procedure CreateSalesLines(SalesHeader: Record "Sales Header"; ICInboxSalesLine: Record "IC Inbox Sales Line")
    procedure CreatePurchDocument(ICInboxPurchHeader: Record "IC Inbox Purchase Header"; ReplacePostingDate: Boolean; PostingDate: Date)
    procedure CreatePurchLines(PurchHeader: Record "Purchase Header"; ICInboxPurchLine: Record "IC Inbox Purchase Line")

codeunit 22 "Item Jnl.-Post Line"
    local procedure GetCombinedDimSetID(DimSetID1: Integer; DimSetID2: Integer): Integer

table 83 "Item Journal Line"
    procedure CreateProdDim()
    local procedure CreateAssemblyDim()

codeunit 1002 "Job Create-Invoice"
    local procedure UpdateSalesLineDimension(var SalesLine: Record "Sales Line"; JobPlanningLine: Record "Job Planning Line")

table 210 "Job Journal Line"
    procedure UpdateDimensions()

table 99000829 "Planning Component"
    procedure CreateDim(Type1: Integer; No1: Code[20])

report 1201 "Post Direct Debit Collection"
    local procedure CreateJnlLine(var DirectDebitCollectionEntry: Record "Direct Debit Collection Entry"): Boolean

table 39 "Purchase Line"
    local procedure UpdateDimensionsFromJobTask()

codeunit 90 "Purch.-Post"
    local procedure UpdatePurchLineDimSetIDFromAppliedEntry(var PurchLineToPost: Record "Purchase Line"; PurchLine: Record "Purchase Line")

codeunit 393 "Reminder-Issue"
    trigger OnRun()

table 246 "Requisition Line"
    procedure UpdateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20])
    procedure GetDimFromRefOrderLine(AddToExisting: Boolean)

codeunit 333 "Req. Wksh.-Make Order"
    procedure InsertPurchOrderLine(var ReqLine2: Record "Requisition Line"; var PurchOrderHeader: Record "Purchase Header")

codeunit 80 "Sales-Post"
    local procedure UpdateSalesLineDimSetIDFromAppliedEntry(var SalesLineToPost: Record "Sales Line"; SalesLine: Record "Sales Line")

table 172 "Standard Customer Sales Code"
    local procedure CombineDimensions(var SalesLine: Record "Sales Line"; StdSalesLine: Record "Standard Sales Line")

table 5998 "Standard Service Item Gr. Code"
    local procedure CombineDimensions(var ServLine: Record "Service Line"; StdServLine: Record "Standard Service Line")

table 175 "Standard Vendor Purchase Code"
    local procedure CombineDimensions(var PurchaseLine: Record "Purchase Line"; StdPurchaseLine: Record "Standard Purchase Line")

report 394 "Suggest Employee Payments"
    local procedure UpdateDimensions(var GenJnlLine: Record "Gen. Journal Line")

report 393 "Suggest Vendor Payments"
    local procedure UpdateDimensions(var GenJnlLine: Record "Gen. Journal Line")

Thanks,

Denis

**Comment by SER-denisg** [comment]
UPDATE:  After some further review, the change for:

codeunit 22 "Item Jnl.-Post Line"
local procedure GetCombinedDimSetID(DimSetID1: Integer; DimSetID2: Integer): Integer

does not need to be done, I have figured out another way.

Denis

**Comment by SER-denisg** [comment]
I have created another request (#16860) for an event that ends up covering this object, so it can be removed from this request:

table 210 "Job Journal Line"
procedure UpdateDimensions()

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
