### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" - OnCalcMaxQtyOnBeforeFindTempWhseActivLine

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16726]
local procedure CalcMaxQty(var QtytoHandle: Decimal; QtyOutstanding: Decimal; var QtytoHandleBase: Decimal; QtyOutstandingBase: Decimal; ActionType: Enum "Warehouse Action Type")
    var
        WhseActivLine2: Record "Warehouse Activity Line";
    begin
        WhseActivLine2.Copy(TempWhseActivLine);
        with TempWhseActivLine do begin
            SetCurrentKey(
              "Whse. Document No.", "Whse. Document Type", "Activity Type", "Whse. Document Line No.");
            SetRange("Whse. Document Type", "Whse. Document Type");
            SetRange("Whse. Document No.", "Whse. Document No.");
            SetRange("Activity Type", "Activity Type");
            SetRange("Whse. Document Line No.", "Whse. Document Line No.");
            SetRange("Source Type", "Source Type");
            SetRange("Source Subtype", "Source Subtype");
            SetRange("Source No.", "Source No.");
            SetRange("Source Line No.", "Source Line No.");
            SetRange("Source Subline No.", "Source Subline No.");
            SetRange("Action Type", ActionType);
            SetRange("Breakbulk No.", 0);
            OnCalcMaxQtyOnBeforeFindTempWhseActivLine(TempWhseActivLine); //A200F0000.Event19.05
            if Find('-') then

    [IntegrationEvent(false, false)]
    local procedure OnCalcMaxQtyOnBeforeFindTempWhseActivLine(var TempWhseActivLine: Record "Warehouse Activity Line" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
