### ISSUE TITLE
[Event Request] codeunit 12179 "Export FatturaPA Document"

### ISSUE THREAD

**Issue by mcalzolari** [microsoft/ALAppExtensions#16723]
In Local procedure PopulateOrderData I need the event 'OnBeforePopulateOrderData'

```
local procedure PopulateOrderData(var TempFatturaLine: Record "Fattura Line" temporary; TempFatturaHeader: Record "Fattura Header" temporary)

Begin

//--Code to add
    IsHandled := false;
    OnBeforePopulateOrderData(TempFatturaLine, TempFatturaHeader, TempXMLBuffer, IsHandled);
    if IsHandled then
        exit;
//-- End Code to Add
...
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
