### ISSUE TITLE
Request for determining default value in function ShowDialog (page 954 "Manager Time Sheet by Job")

### ISSUE THREAD

**Issue by pieter-kok** [microsoft/ALAppExtensions#16730]
The functionality on page Manager Time Sheet by Job (page 954) to approve, reject and reopen lines requests the user whether only the selected lines or all lines in the current filter must be processed. The dialog that is used for this purpose is created by the procedure ShowDialog. 

In our solution, we would like to be able to change the default value per ActionType. The following is our suggestion to solve this, that we hope you will consider as enhancement.

```
local procedure ShowDialog(ActionType: Option Approve,Reopen,Reject): Integer
var
    //New >>
    DefaultValue: Integer;
    //New <<
begin
    //Current Version >>
    //exit(StrMenu(GetDialogText(ActionType), 1, TimeSheetApprovalMgt.GetManagerTimeSheetDialogInstruction(ActionType)));
    //Current Version <<

    //New >>
    DefaultValue := 1;
    OnBeforeShowDialogForAction(ActionType, DefaultValue);

    exit(StrMenu(GetDialogText(ActionType), DefaultValue, TimeSheetApprovalMgt.GetManagerTimeSheetDialogInstruction(ActionType)));
    //New <<
end;

//New >>
[IntegrationEvent(false, false)]
local procedure OnBeforeShowDialogForAction(ActionType: Option; var DefaultValue: Integer)
begin
end;
//New <<

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
