### ISSUE TITLE
[Event Request] codeunit 5752 "Get Source Doc. Outbound"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#16732]
Please add the same logic in codeunit 5752 "Get Source Doc. Outbound" as in codeunit 5751 "Get Source Doc. Inbound" and call  GetSourceDocuments.GetLastShptHeader that the created Record "Warehouse Shipment Header" can be modified, and add var WhseShptHeader to the existing OnAfterCreateWhseShipmentHeaderFromWhseRequest

old:
    local procedure CreateWhseShipmentHeaderFromWhseRequest(var WarehouseRequest: Record "Warehouse Request") Result: Boolean
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCreateWhseShipmentHeaderFromWhseRequest(WarehouseRequest, Result, IsHandled);
        if IsHandled then
            exit(Result);

        if WarehouseRequest.IsEmpty() then
            exit(false);

        Clear(GetSourceDocuments);
        GetSourceDocuments.UseRequestPage(false);
        GetSourceDocuments.SetTableView(WarehouseRequest);
        GetSourceDocuments.SetHideDialog(true);
        GetSourceDocuments.RunModal();

        OnAfterCreateWhseShipmentHeaderFromWhseRequest(WarehouseRequest);

        exit(true);
    end;

new:
    local procedure CreateWhseShipmentHeaderFromWhseRequest(var WarehouseRequest: Record "Warehouse Request") Result: Boolean
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCreateWhseShipmentHeaderFromWhseRequest(WarehouseRequest, Result, IsHandled);
        if IsHandled then
            exit(Result);

        if WarehouseRequest.IsEmpty() then
            exit(false);

        Clear(GetSourceDocuments);
        GetSourceDocuments.UseRequestPage(false);
        GetSourceDocuments.SetTableView(WarehouseRequest);
        GetSourceDocuments.SetHideDialog(true);
        GetSourceDocuments.RunModal();

//++changed/added lines
       GetSourceDocuments.GetLastShptHeader(var WhseShptHeader);
        OnAfterCreateWhseShipmentHeaderFromWhseRequest(WarehouseRequest; var WhseShptHeader);
//--changed/added lines

        exit(true);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
