### ISSUE TITLE
[Event Request] codeunit 5751 "Get Source Doc. Inbound" OnAfterCreateWhseReceiptHeaderFromWhseRequest

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#16731]
Please add WarehouseRequest as additional parameter to OnAfterCreateWhseReceiptHeaderFromWhseRequest in codeunit 5751 "Get Source Doc. Inbound":

old:
    [IntegrationEvent(false, false)]
    local procedure OnAfterCreateWhseReceiptHeaderFromWhseRequest(var WhseReceiptHeader: Record "Warehouse Receipt Header");
    begin
    end;

new:
 [IntegrationEvent(false, false)]
    local procedure OnAfterCreateWhseReceiptHeaderFromWhseRequest(var WhseReceiptHeader: Record "Warehouse Receipt Header",WarehouseRequest: Record "Warehouse Request");
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
