### ISSUE TITLE
[Event Request] Codeunit 99000770 OnBeforeInsertWhereUsedList

### ISSUE THREAD

**Issue by GuntherGebauer** [Microsoft/ALAppExtensions#1673]
we Need a new eventtrigger in codeunit 99000770 before the record is inserted:

codeunit 99000770:
LOCAL BuildWhereUsedList(Type : ' ,Item,Production BOM';No : Code[20];CalcDate : Date;Level : Integer;Quantity : Decimal)

...
      WhereUsedList."Version Code" := VersionMgt.GetBOMVersion(No,CalcDate,TRUE);
      OnBeforeInsertWhereUsedList(VAR WhereUsedList;ItemAssembly;CalcDate;Quantity);  <-- New Eventttrigger
      WhereUsedList.INSERT;
      NextWhereUsedEntryNo := NextWhereUsedEntryNo + 1;

**Comment by NKarolak** [comment]
Great, I need that event too. Though I would propose the following publisher name: OnBuildWhereUsedListOnBeforeInsert
