### ISSUE TITLE
[Apply Enum Request} = enum 5874 "BOM Structure Show By"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16736]
The enum has only been applied in page 5870 "BOM Structure" and set as protected (I think I asked for that in previous issue)
Could you please apply the enum in the following objects and set it as Protected in the pages if not already done so?

page 5871 "Item Availability by BOM Level"
page 5872 "BOM Cost Shares"
report 5871 "Item - Able to Make (Timeline)"
page 5871 "Item Availability by BOM Level"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
