### ISSUE TITLE
[Permission Request] Purchase Line table 39

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#16738]
We would like to request indrect modify permission for Purchase Line on the Table 39 Purchase line.
We would need this permission to make sure that the (Rec.)modify that is called in the function UpdateVATOnLines on the Purchase line can be executed when a user has indirect permissions.

    table 39 "Purchase Line"
    {
        Caption = 'Purchase Line';
        DrillDownPageID = "Purchase Lines";
        LookupPageID = "Purchase Lines";
        //<<New 
        Permissions = TableData "Purchase Line" = m;
        //>>Endnew

Our scenario that is causing issue is when users are approving an Purchase Order. During the approval and release of the purchase order the following functions are called:
"Purchase Line"(Table 39).UpdateVATOnLines
"Release Purchase Document"(CodeUnit 415).CalcAndUpdateVATOnLines

If the user that is approving the order has indirect permissions to modify the purchase line, it should be able to approve the order. Currently the user get stuck in permission error.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
