### ISSUE TITLE
[Event Request] Page 6510 "Item Tracking Lines" - New publisher OnQueryClosePageOnBeforeCurrPageUpdate

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16746]
Hello, we need a new Event publisher in trigger OnQueryClosePage(). Can you please check that? Thank you!

    trigger OnQueryClosePage(CloseAction: Action): Boolean
    var
        IsHandled: Boolean;
    begin
        if not UpdateUndefinedQty then
            exit(Confirm(Text006));

        if not ItemTrackingDataCollection.RefreshTrackingAvailability(Rec, false) then begin
            IsHandled := false;
            OnQueryClosePageOnBeforeCurrPageUpdate(IsHandled);    <===========================
            if IsHandled then
              CurrPage.Update();

            IsHandled := false;
            OnQueryClosePageOnBeforeConfirmClosePage(Rec, IsHandled);
            if IsHandled then
                Exit(true);

            exit(Confirm(AvailabilityWarningsQst, true));
        end;
    end;

    [IntegrationEvent(true, false)]
    local procedure OnQueryClosePageOnBeforeCurrPageUpdate(var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Looks fine in the current code base. Probably was addressed already:
![image](https://user-images.githubusercontent.com/19796701/175263834-5f6e8315-b93d-423a-9019-f5e32826b759.png)
