### ISSUE TITLE
[Event Parameter Change] Page 6510 "Item Tracking Lines" - New parameters in OnBeforeSerialNoOnAfterValidate

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16743]
Hello, we would need the following Event publisher to be extended with the additional parameters. Can you please check this? Thank you!

    Original(Current) - OnBeforeSerialNoOnAfterValidate:

      OnBeforeSerialNoOnAfterValidate(Rec);

      [IntegrationEvent(false, false)]
      local procedure OnBeforeSerialNoOnAfterValidate(var TempTrackingSpecification: Record "Tracking Specification" temporary)
      begin
      end;

    New -  OnBeforeSerialNoOnAfterValidate, with additional parameters:
     
        OnBeforeSerialNoOnAfterValidate(Rec, SourceQuantityArray);
      
        [IntegrationEvent(false, false)]
        local procedure OnBeforeSerialNoOnAfterValidate(var TempTrackingSpecification: Record "Tracking Specification" temporary; 
        SourceQuantityArray: array[5] of Decimal)
        begin
        end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
