### ISSUE TITLE
[Event Parameter Change] Page 6510 "Item Tracking Lines" - New parameters & IncludeSender in OnSetSourceSpecOnAfterAssignCurrentEntryStatus

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16741]
Hello, we would need the following Event publisher to be extended with the additional parameters. Can you please check this? Thank you!

    Original(Current) - OnSetSourceSpecOnAfterAssignCurrentEntryStatus:

        OnSetSourceSpecOnAfterAssignCurrentEntryStatus(TrackingSpecification, CurrentEntryStatusOption);

        [IntegrationEvent(false, false)]
        local procedure OnSetSourceSpecOnAfterAssignCurrentEntryStatus(var TrackingSpecification: Record "Tracking Specification"; var 
        CurrentEntryStatus: Option)
        begin
        end;

     New -  OnSetSourceSpecOnAfterAssignCurrentEntryStatus, with additional parameters & IncludeSender=true:
     
        OnSetSourceSpecOnAfterAssignCurrentEntryStatus(TrackingSpecification, CurrentEntryStatusOption, ItemTrackingCode, InsertIsBlocked);

        [IntegrationEvent(true, false)]
        local procedure OnSetSourceSpecOnAfterAssignCurrentEntryStatus(var TrackingSpecification: Record "Tracking Specification"; var 
        CurrentEntryStatus: Option; ItemTrackingCode: Record "Item Tracking Code"; var InsertIsBlocked: Boolean)
        begin
        end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
