### ISSUE TITLE
[Event Request] Codeunit 99000773 OnBeforeTransferBOMNextLevel

### ISSUE THREAD

**Issue by GuntherGebauer** [Microsoft/ALAppExtensions#1674]
we Need new Eventtrigger in codeunit 99000773 before ReqQty is used for the next level. We cannot use the existing trigger OnBeforeTransferBOMComponent because this trigger Needs to handle all Levels if ishandled=true should be returned and reqqty is used later inside of the Routine for one level:

LOCAL TransferBOM(ProdBOMNo : Code[20];Level : Integer;LineQtyPerUOM : Decimal;ItemQtyPerUOM : Decimal) : Boolean
...
      END ELSE
        ReqQty :=
          ProdBOMLine[Level].Quantity * (1 + ProdBOMLine[Level]."Scrap %" / 100) * LineQtyPerUOM / ItemQtyPerUOM;

      OnBeforeTransferBOMNextLevel( ProdBOMLine[Level];ProdOrderLine;LineQtyPerUOM ;ItemQtyPerUOM;VAR ReqQty);   <-- New Eventtrigger
      CASE ProdBOMLine[Level].Type OF

**Comment by GuntherGebauer** [comment]
In Procedure TransferBOMProcessItem we Need zwo addtional Parameter in the existing eventtrigger:

old:
  OnAfterTransferBOMComponent(VAR ProdOrderLine,VAR ProdBOMLine[Level],VAR ProdOrderComp);
new:
  OnAfterTransferBOMComponent(VAR ProdOrderLine,VAR ProdBOMLine[Level],VAR ProdOrderComp,LineQtyPerUOM,ItemQtyPerUOM);

old:
OnBeforeProdOrderCompModify(VAR ProdOrderComp,VAR ProdBOMLine[Level]);
new:
OnBeforeProdOrderCompModify(VAR ProdOrderComp,VAR ProdBOMLine[Level],LineQtyPerUOM,ItemQtyPerUOM);

**Comment by NKarolak** [comment]
Note: implemented in BC 14 CU02  as
- OnBeforeTransferBOMNextLevel --> OnTransferBOMOnAfterCalcReqQty
With ProdOrderRoutingLine2 instead of ProdOrderLine
