### ISSUE TITLE
[Event Request] Page 6510 "Item Tracking Lines" - New publisher OnBeforeOnInsertRecord

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16745]
Hello, we need a new Event publisher in trigger OnInsertRecord(). Can you please check that? Thank you!

    trigger OnInsertRecord(BelowxRec: Boolean): Boolean
    begin
        OnBeforeOnInsertRecord(Rec, SourceQuantityArray);    <=======================
        if Rec."Entry No." <> 0 then
            exit(false);

        InsertRecord(Rec);
        CalculateSums();

        exit(false);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnInsertRecord(var TrackingSpecification: Record "Tracking Specification"; SourceQuantityArray: array[5] of Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
