### ISSUE TITLE
[Event Request] Table 5093 "Opportunity Entry" - New publisher OnBeforeModifyUpdateEstimates

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16749]
Hello, we need a new Event publisher in procedure UpdateEstimates(). Can you please check that? Thank you!

    procedure UpdateEstimates()
    var
        SalesCycle: Record "Sales Cycle";
        SalesCycleStage: Record "Sales Cycle Stage";
        Opp: Record Opportunity;
        SalesHeader: Record "Sales Header";
    begin
        if SalesCycleStage.Get("Sales Cycle Code", "Sales Cycle Stage") then begin
            SalesCycle.Get("Sales Cycle Code");
            if ("Chances of Success %" = 0) and (SalesCycleStage."Chances of Success %" <> 0) then
                "Chances of Success %" := SalesCycleStage."Chances of Success %";
            "Completed %" := SalesCycleStage."Completed %";
            case SalesCycle."Probability Calculation" of
                SalesCycle."Probability Calculation"::Multiply:
                    "Probability %" := "Chances of Success %" * "Completed %" / 100;
                SalesCycle."Probability Calculation"::Add:
                    "Probability %" := ("Chances of Success %" + "Completed %") / 2;
                SalesCycle."Probability Calculation"::"Chances of Success %":
                    "Probability %" := "Chances of Success %";
                SalesCycle."Probability Calculation"::"Completed %":
                    "Probability %" := "Completed %";
            end;
            "Calcd. Current Value (LCY)" := "Estimated Value (LCY)" * "Probability %" / 100;
            if ("Estimated Close Date" = "Date of Change") or ("Estimated Close Date" = 0D) then
                "Estimated Close Date" := CalcDate(SalesCycleStage."Date Formula", "Date of Change");
        end;

        case "Action Taken" of
            "Action Taken"::Won:
                begin
                    Opp.Get("Opportunity No.");
                    if SalesHeader.Get(SalesHeader."Document Type"::Quote, Opp."Sales Document No.") then
                        "Calcd. Current Value (LCY)" := GetSalesDocValue(SalesHeader);

                    "Completed %" := 100;
                    "Chances of Success %" := 100;
                    "Probability %" := 100;
                end;
            "Action Taken"::Lost:
                begin
                    "Calcd. Current Value (LCY)" := 0;
                    "Completed %" := 100;
                    "Chances of Success %" := 0;
                    "Probability %" := 0;
                end;
        end;

        OnBeforeModifyUpdateEstimates(Rec, SalesHeader);     <=============================
        Modify;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyUpdateEstimates(var Rec: Record "Opportunity Entry"; SalesHeader: Record "Sales Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
