### ISSUE TITLE
[Event Parameter Change] Page 6510 "Item Tracking Lines" - New parameters in OnBeforeClosePage

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16740]
Hello, we would need the following Event publisher to be extended with the additional parameters. Can you please check this? Thank you!

    Original(Current) - OnBeforeClosePage:

        OnBeforeClosePage(Rec, SkipWriteToDatabase);

        [IntegrationEvent(false, false)]
        local procedure OnBeforeClosePage(var TrackingSpecification: Record "Tracking Specification"; var SkipWriteToDatabase:  
        Boolean)
        begin
        end;

     New -  OnBeforeClosePage, with additional parameters:
     
         OnBeforeClosePage(Rec, SkipWriteToDatabase, CurrentRunMode, CurrentSourceType);
         
         [IntegrationEvent(false, false)]
         local procedure OnBeforeClosePage(var TrackingSpecification: Record "Tracking Specification"; var SkipWriteToDatabase: 
         Boolean; CurrentRunMode: Enum "Item Tracking Run Mode"; CurrentSourceType: Integer)
         begin
         end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
