### ISSUE TITLE
[Extensibility Request] Page 498 Reservation - Procedure from Local to Global

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16751]
Hello, we need the following currently Local procedure to be set as Global. Can you please check this? Thank you!

    procedure UpdateReservFrom()

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
