### ISSUE TITLE
[Event Request] Page 9237 "Resource Capacity Matrix" - New publisher OnAfterValidateCapacity

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16757]
Hello, we need a new Event publisher in procedure ValidateCapacity(). Can you please check that? Thank you!

    local procedure ValidateCapacity(MATRIX_ColumnOrdinal: Integer)
    begin
        SetDateFilter(MATRIX_ColumnOrdinal);
        CalcFields(Capacity);
        Validate(Capacity, MATRIX_CellData[MATRIX_ColumnOrdinal]);

        OnAfterValidateCapacity(Rec, MATRIX_CellData, MATRIX_ColumnOrdinal);           <===================
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterValidateCapacity(var Resource: Record Resource; var MATRIXCellData: array[32] of Decimal; MATRIXColumnOrdinal: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
