### ISSUE TITLE
[Event Request] Page 95 "Sales Quote Subform" - New publisher OnBeforeDeltaUpdateTotalsQuantityOnAfterValidate

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16767]
Hello, we need a new Event publisher in procedure QuantityOnAfterValidate(). Can you please check that? Thank you!

    protected procedure QuantityOnAfterValidate()
    begin
        if Reserve = Reserve::Always then begin
            CurrPage.SaveRecord();
            AutoReserve();
        end;

        OnBeforeDeltaUpdateTotalsQuantityOnAfterValidate(Rec, xRec);            <=========================

        DeltaUpdateTotals();

        OnAfterQuantityOnAfterValidate(Rec, xRec);
    end;

    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeDeltaUpdateTotalsQuantityOnAfterValidate(var SalesLine: Record "Sales Line"; var xSalesLine: Record "Sales Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
