### ISSUE TITLE
[Event Parameter Change] Page 47 "Sales Invoice Subform" - New parameter in OnAfterValidateAutoReserve

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16762]
Hello, we would need the following Event publisher to be extended with the additional parameter. Can you please check this? Thank you!

    Original(Current) - OnAfterValidateAutoReserve:

    OnAfterValidateAutoReserve(Rec);

    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterValidateAutoReserve(var SalesLine: Record "Sales Line")
    begin
    end;

    New -  OnAfterValidateAutoReserve, with additional parameter:
 
    OnAfterValidateAutoReserve(Rec, xRec);
  
    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterValidateAutoReserve(var SalesLine: Record "Sales Line"; var xSalesLine: Record "Sales Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
