### ISSUE TITLE
[Event Request] Page 95 "Sales Quote Subform" - New publisher OnAfterShowNonstockItems

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16765]
Hello, we need a new Event publisher in procedure ShowNonstockItems(). Can you please check that? Thank you!

    local procedure ShowNonstockItems()
    begin
        ShowNonstock;

        OnAfterShowNonstockItems(Rec);     <=================
    end;

    [IntegrationEvent(true, false)]
    local procedure OnAfterShowNonstockItems(var SalesLine: Record "Sales Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
