### ISSUE TITLE
[Event Request] codeunit 8618 "Config. Excel Exchange" - OnBeforeGetFieldOnAfterCalcShouldRunCheck

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16772]
local procedure CreateTableColumnNames(var ConfigPackageField: Record "Config. Package Field"; var ConfigPackageTable: Record "Config. Package Table"; TableColumns: DotNet TableColumns)
    var
        ...
        IsHandled: Boolean;
        ShouldRunCheck: Boolean; //A115F0000.Event19.05
    begin
        IsHandled := false;
        ...

        RecRef.Open(ConfigPackageTable."Table ID");
        ConfigPackageField.SetCurrentKey("Package Code", "Table ID", "Processing Order");
        if ConfigPackageField.FindSet then begin
            ColumnID := 1;
            repeat
                //A115F0000.Event19.05.ns
                ShouldRunCheck := ConfigPackageField.Dimension;
                OnBeforeGetFieldOnAfterCalcShouldRunCheck(ConfigPackageField, ShouldRunCheck);
                //A115F0000.Event19.05.ne
                if TypeHelper.GetField(ConfigPackageField."Table ID", ConfigPackageField."Field ID", Field) or
                    ShouldRunCheck //A115F0000.Event19.05.n
                   //ConfigPackageField.Dimension A115F0000.Event19.05.o
                then begin

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetFieldOnAfterCalcShouldRunCheck(var ConfigPackageField: Record "Config. Package Field"; var ShouldRunCheck: Boolean)
    begin
        //A115F0000.Event19.05
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
