### ISSUE TITLE
[Event Request] Page 5098 "Task Card" - New publisher OnAfterSwitchCardControls

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16775]
Hello, we need a new Event publisher in procedure SwitchCardControls(). Can you please check that? Thank you!

    local procedure SwitchCardControls()
    begin
        if Type = Type::Meeting then begin
            ContactNoEditable := false;

            NoOfAttendeesEnable := true;
            AttendeesAcceptedNoEnable := true;
        end else begin
            ContactNoEditable := true;

            NoOfAttendeesEnable := false;
            AttendeesAcceptedNoEnable := false;
        end;
        if "Team Code" = '' then
            CompletedByEnable := false
        else begin
            CompletedByEnable := true;
            CompletedByEditable := not Closed
        end;

        OnAfterSwitchCardControls(ContactNoEditable, NoOfAttendeesEnable, AttendeesAcceptedNoEnable);   <==========
    end;

    [IntegrationEvent(true, false)]
    local procedure OnAfterSwitchCardControls(ContactNoEditable: Boolean; NoOfAttendeesEnable: Boolean; AttendeesAcceptedNoEnable: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
