### ISSUE TITLE
[EventRequest] Codeunit 782 "Opportunity Chart Mgt."

### ISSUE THREAD

**Issue by rvicenteADV** [microsoft/ALAppExtensions#16778]
Please new events

procedure DrillDown(var BusinessChartBuffer: Record "Business Chart Buffer"; Period: Record Date; OpportunityStatus: Option)
begin
      #15..28
      // BEGIN
      OnBeforeDrillDown(Opportunity);
     // END
      PAGE.Run(PAGE::"Opportunity List", Opportunity);
end;

local procedure GetOppCount(Period: Record Date; SalesPersonCode: Code[20]; OpportunityStatus: Option): Integer
begin
    #36..46
      // BEGIN
      OnGetOppCountOnBeforeCount(Opportunity);
     // END
    exit(Opportunity.Count);
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeDrillDown(var Opportunity: Record "Opportunity")
begin
end;

[IntegrationEvent(false, false)]
local procedure OnGetOppCountOnBeforeCount(var Opportunity: Record "Opportunity")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
