### ISSUE TITLE
[Code Change] Codeunit 7380 Phys. Invt. Count.-Management

### ISSUE THREAD

**Issue by ZtefanBildalZ** [Microsoft/ALAppExtensions#1678]
Missing the ability to limit (filter) items down to a specified Counting Period Code ("Phys Invt Counting Period Code"). Should be part of “[External] InitFrom**” functions. Something like:
WITH Item DO BEGIN
  //LS-3723-
  IF CountingPeriodCode <> '' THEN
    SETFILTER("Phys Invt Counting Period Code",CountingPeriodCode)
  ELSE
  //LS-3723+
  SETFILTER("Phys Invt Counting Period Code",'<>''''');

Missing the ability to control more dynamically into which worksheet (journal) the lines are processed. As it is today only source journals are “ItemJnl” and “WhseJnl”.  This must be made more general with ability to handle process of extra journals through events. This could be achieved by more general “[External] InitFrom**” function that then would accept more dynamic journal reference and the fixed “Counting Period Code” described here above. The process of the “TempPhysInvtItemSelection“ table would then be handled by typical event with IsHandled flag.

**Comment by AlexanderYakunin** [comment]
Can you please be more specific to speed up processing of your request?

**Comment by AlexanderYakunin** [comment]
[COD7380.txt](https://github.com/Microsoft/ALAppExtensions/files/2982449/COD7380.txt)

Please verify that this change solve you problem.

**Comment by ZtefanBildalZ** [comment]
This would work for me there is though one thing you could add and that is to pass the SourceJnl option field to the OnRunOnAfterSetItemFilters and OnRunOnAfterSetSKUFilters function because they could be used in connection with other types then Custom. No need for that into the Custom function because it is what it is!
