### ISSUE TITLE
[Event Request] codeunit 8618 "Config. Excel Exchange" - OnCreateTableColumnNamesOnBeforeSetCellComment

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16788]
local procedure CreateTableColumnNames(var ConfigPackageField: Record "Config. Package Field"; var ConfigPackageTable: Record "Config. Package Table"; TableColumns: DotNet TableColumns)
    var
        "Field": Record "Field";
        ...
        ShouldSetCellComment: Boolean;
    begin
        IsHandled := false;
        ...
                    WrkShtWriter.SetCellValueText(
                      3, OpenXMLManagement.GetXLColumnID(ColumnID), TableColumnName, WrkShtWriter.DefaultCellDecorator);
                    //if not ConfigPackageField.Dimension then begin A115F0000.Event19.05
                    //A115F0000.Event19.05.ns
                    ShouldSetCellComment := not ConfigPackageField.Dimension;
                    OnCreateTableColumnNamesOnBeforeSetCellComment(ConfigPackageField, ConfigPackageTable, ShouldSetCellComment);
                    if ShouldSetCellComment then begin
                        //A115F0000.Event19.05.ne
                        FieldRef := RecRef.Field(ConfigPackageField."Field ID");
                        OpenXMLManagement.SetCellComment(
                          WrkShtWriter, OpenXMLManagement.GetXLColumnID(ColumnID) + '3', ConfigValidateMgt.AddComment(FieldRef));
                        StringBld.Append(OpenXMLManagement.CreateCommentVmlShapeXml(ColumnID, 3));
                    end;
                end;

    [IntegrationEvent(false, false)]
    local procedure OnCreateTableColumnNamesOnBeforeSetCellComment(var ConfigPackageField: Record "Config. Package Field"; var ConfigPackageTable: Record "Config. Package Table"; var ShouldAddCellComment: Boolean)
    begin
        //A115F0000.Event19.05
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
