### ISSUE TITLE
[Event Parameter Change] Page 344 Navigate - New parameters in OnBeforeUpdateFormAfterFindRecords

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16783]
Hello, we would need the following Event publisher to be extended with the additional parameters. Can you please check this? Thank you!

    Original(Current) - OnBeforeUpdateFormAfterFindRecords:

    OnBeforeUpdateFormAfterFindRecords();

    [IntegrationEvent(true, false)]
    local procedure OnBeforeUpdateFormAfterFindRecords()
    begin
    end;

    New -  OnBeforeUpdateFormAfterFindRecords, with additional parameters:
 
    OnBeforeUpdateFormAfterFindRecords(PostingDateFilter);
  
    [IntegrationEvent(true, false)]
    local procedure OnBeforeUpdateFormAfterFindRecords(var PostingDateFilter: Text)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
