### ISSUE TITLE
[Event Request] Page 9255 "Tasks Matrix" - New publisher OnAfterSetFilters

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16780]
Hello, we need a new Event publisher in procedure SetFilters(). Can you please check that? Thank you!

    local procedure SetFilters()
    begin
        if StatusFilter <> StatusFilter::" " then begin
            SetRange("Task Status Filter", StatusFilter - 1);
            Task.SetRange(Status, StatusFilter - 1);
        end else begin
            SetRange("Task Status Filter");
            Task.SetRange(Status);
        end;

        Task.SetFilter("System To-do Type", '%1|%2', "System Task Type Filter"::Organizer,
          "System Task Type Filter"::"Salesperson Attendee");

        if IncludeClosed then
            Task.SetRange(Closed)
        else
            Task.SetRange(Closed, false);

        if PriorityFilter <> PriorityFilter::" " then begin
            SetRange("Priority Filter", PriorityFilter - 1);
            Task.SetRange(Priority, PriorityFilter - 1);
        end else begin
            SetRange("Priority Filter");
            Task.SetRange(Priority);
        end;

        case TableOption of
            TableOption::Salesperson:
                begin
                    SetRange("Salesperson Filter", "No.");
                    SetFilter(
                      "System Task Type Filter", '%1|%2',
                      "System Task Type Filter"::Organizer,
                      "System Task Type Filter"::"Salesperson Attendee");
                end;
            TableOption::Team:
                begin
                    SetRange("Team Filter", "No.");
                    SetRange("System Task Type Filter", "System Task Type Filter"::Team);
                end;
            TableOption::Campaign:
                begin
                    SetRange("Campaign Filter", "No.");
                    SetRange("System Task Type Filter", "System Task Type Filter"::Organizer);
                end;
            TableOption::Contact:
                if Type = Type::Company then begin
                    SetRange("Contact Filter");
                    SetRange("Contact Company Filter", "Company No.");
                    SetRange(
                      "System Task Type Filter", "System Task Type Filter"::"Contact Attendee");
                end else begin
                    SetRange("Contact Filter", "No.");
                    SetRange("Contact Company Filter");
                    SetRange(
                      "System Task Type Filter", "System Task Type Filter"::"Contact Attendee");
                end;
        end;

        OnAfterSetFilters(Rec, Task, TableOption);                         <===========================
    end;

    [IntegrationEvent(true, false)]
    local procedure OnAfterSetFilters(var RMMatrixManagement: Record "RM Matrix Management"; var Task: Record "To-do"; TableOption: Option Salesperson,Team,Campaign,Contact)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
