### ISSUE TITLE
[Event Request] Page page 5129 "Update Opportunity" - New publisher OnBeforeModifyUpdateEstimatedValues

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#16782]
Hello, we need a new Event publisher in procedure UpdateEstimatedValues(). Can you please check that? Thank you!

    local procedure UpdateEstimatedValues()
    var
        SalesCycleStage: Record "Sales Cycle Stage";
        SalesHeader: Record "Sales Header";
    begin
        if SalesCycleStage.Get("Sales Cycle Code", "Sales Cycle Stage") then begin
            "Estimated Close Date" := CalcDate(SalesCycleStage."Date Formula", "Date of Change");
            "Chances of Success %" := SalesCycleStage."Chances of Success %";
        end;
        if SalesHeader.Get(SalesHeader."Document Type"::Quote, Opp."Sales Document No.") then
            "Estimated Value (LCY)" := GetSalesDocValue(SalesHeader);

        OnBeforeModifyUpdateEstimatedValues(Rec, SalesHeader);          <==============
        Modify;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyUpdateEstimatedValues(var Rec: Record "Opportunity Entry"; SalesHeader: Record "Sales Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
