### ISSUE TITLE
[Extensibility Bug] codeunit 6620 "Copy Document Mgt." - Get Posted Document Lines to Reverse

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#16789]
There is an issue in Copy Document Management when the lines are copied from multiply documents by usage of Get Posted Document Lines to Reverse action and it ends up in methods `CopySalesInvLinesToDoc` or `CopySalesCrMemoLinesToDoc` and their **equivalents** on **purchase** side.
There is `FromSalesHeader` variable in those methods and this variable is used in the **events** and other **methods**.
There are 2 loops - for example in `CopySalesInvLinesToDoc`:
```al
with FromSalesInvLine do
	if FindSet() then
		repeat
			...
			FromSalesHeader.TransferFields(FromSalesInvHeader);
			...
		until Next() = 0;
```
This first one is OK, `FromSalesHeader` is processing and is filled in. But this loop prepares a buffer that is used in the 2nd loop:
```al
with TempSalesLineBuf do begin
	if FindSet() then begin
		repeat
			...
		until Next() = 0;
```
There is `FromSalesHeader` variable used as a parameter of methods (and inside them in events).
`FromSalesHeader` is not prepared anywhere and uses last values from the previous loop for all lines. In a general case (copying one document), it is ok but for Get Posted Document Lines to Reverse it is the problem.

**Comment by AlexanderYakunin** [comment]
This variable is prepared in this statement: FromSalesHeader.TransferFields(FromSalesInvHeader);

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related directly to the AL **application** extensibility. Please reach out to the relevant support channels:
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
