### ISSUE TITLE
[Event Request] codeunit 8611 "Config. Package Management" - OnModifyRecordDataFieldsOnBeforeHandleRecRef

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16790]
This is a reminder and update of issue (placed by my son in july 2021)
https://github.com/microsoft/ALAppExtensions/issues/13135

    local procedure ModifyRecordDataFields(var RecRef: RecordRef; ConfigPackageRecord: Record "Config. Package Record"; DoModify: Boolean; DelayedInsert: Boolean)
        ...
        if not DoModify then
            exit;
        if not RecRef.IsDirty() then
            exit;
        
        OnModifyRecordDataFieldsOnBeforeHandleRecRef(RecRef, ConfigPackageRecord, ConfigPackageTable, DoModify, DelayedInsert); //A115F0000.Event19.05

        if DelayedInsert then begin
            IsHandled := false;
            OnModifyRecordDataFieldsOnBeforeRecRefInsert(RecRef, ConfigPackageTable, IsHandled);
            if not IsHandled then
                RecRef.Insert(true);
        end else begin
            IsHandled := false;
            OnModifyRecordDataFieldsOnBeforeRecRefModify(RecRef, ConfigPackageTable, RecordsModifiedCount, IsHandled);
            if not IsHandled then
                RecRef.Modify(not ConfigPackageTable."Skip Table Triggers");
            OnModifyRecordDataFieldsOnAfterRecRefModify(RecRef);
            RecordsModifiedCount += 1;
        end;

    [IntegrationEvent(false, false)]
    local procedure OnModifyRecordDataFieldsOnBeforeHandleRecRef(var RecRef: RecordRef; ConfigPackageRecord: Record "Config. Package Record"; ConfigPackageTable: Record "Config. Package Table"; DoModify: Boolean; DelayedInsert: Boolean)
    begin
        //A115F0000.Event19.05
    end;

**Comment by Stepanenko-Vadim** [comment]
You already have full control of the flow with **OnModifyRecordDataFieldsOnBeforeRecRefInsert**, **OnModifyRecordDataFieldsOnBeforeRecRefModify** and **OnModifyRecordDataFieldsOnAfterRecRefModify** don't you? What is the purpose of this event that can't already be done with those 3? If you need a param to any of these 3, that's preferable way of handling this.

**Comment by Duizy1971** [comment]
I checked my code made 5 years ago and I'm missing the ConfigPackageRecord parameter in the first two Base Events. If you could add ConfigPackageRecord to both events I'm fine with that solution too.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by Duizy1971** [comment]
Sorry, I thought after a couple of days nobody was monitoring closed issues (I think I read that somewhere). In my haste I already entered a new issue https://github.com/microsoft/ALAppExtensions/issues/20295. Sorry about that.
