### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" - OnCreateWhseDocTakeLineOnBeforeWhseActivLineInsert

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16795]
Standard event OnCreateWhseDocTakeLineOnBeforeWhseActivLineInsert should be put at the place activity line also. The same as event OnAfterWhseActivLineInsert which also is used twice.    

local procedure CreateWhseDocTakeLine(var WhseActivLine: Record "Warehouse Activity Line"; var LineNo: Integer)
        ...
                    WhseActivLine2."Original Breakbulk" :=
                      WhseActivLine."Qty. (Base)" = WhseActivLine2."Qty. (Base)";
                    if CreatePickParameters."Breakbulk Filter" then
                        WhseActivLine2.Breakbulk := WhseActivLine2."Original Breakbulk";
                    OnCreateWhseDocTakeLineOnBeforeWhseActivLineInsert(WhseActivLine2, WhseActivHeader, TempWhseActivLine); //A109F0000.Event19.05
                    WhseActivLine2.Insert();
                    OnAfterWhseActivLineInsert(WhseActivLine2);

                    TempWhseActivLine.Delete();
                    LineNo := LineNo + 10000;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
