### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" - OnCreateWhseDocPlaceLineOnBeforeWhseActivLineInsert

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16796]
If there is time left, maybe you can refactor the 'if CreatePickParameters."Do Not Fill Qty. to Handle"' and the lines below and put it in a separate local procedure and an OnAfter event. That piece of code exists four times in this codeunit. If that is not possible make it work with a new event OnCreateWhseDocPlaceLineOnBeforeWhseActivLineInsert.

local procedure CreateWhseDocPlaceLine(PickQty: Decimal; PickQtyBase: Decimal; var LineNo: Integer)
        ...
                if WhseActivLine.Quantity > 0 then begin
                    TempWhseActivLine3 := WhseActivLine;
                    ValidateWhseActivLineQtyFIeldsFromCreateWhseDocPlaceLine(WhseActivLine, TempWhseActivLine3);
                    if CreatePickParameters."Do Not Fill Qty. to Handle" then begin
                        WhseActivLine."Qty. to Handle" := 0;
                        WhseActivLine."Qty. to Handle (Base)" := 0;
                        WhseActivLine.Cubage := 0;
                        WhseActivLine.Weight := 0;
                    end;
                    OnCreateWhseDocPlaceLineOnBeforeWhseActivLineInsert(WhseActivLine, WhseActivHeader, TempWhseActivLine3); //A109F0000.Event19.05
                    WhseActivLine.Insert();
                    OnAfterWhseActivLineInsert(WhseActivLine);
                end;
    
[IntegrationEvent(false, false)]
    local procedure OnCreateWhseDocPlaceLineOnBeforeWhseActivLineInsert(var WarehouseActivityLine: Record "Warehouse Activity Line"; WarehouseActivityHeader: Record "Warehouse Activity Header"; TempWarehouseActivityLine: Record "Warehouse Activity Line" temporary)
    begin
        //A109F0000.Event19.05
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
