### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" - OnFindPickBinOnBeforeCreateTempActivityLine

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16794]
local procedure FindPickBin(
        LocationCode: Code[10]; ItemNo: Code[20]; VariantCode: Code[10]; UnitofMeasureCode: Code[10]; ToBinCode: Code[20];
        QtyRndPrec: Decimal; QtyRndPrecBase: Decimal; var TempWhseActivLine2: Record "Warehouse Activity Line" temporary; var TotalQtytoPick: Decimal; var TempWhseItemTrackingLine: Record "Whse. Item Tracking Line" temporary;
        CrossDock: Boolean; var TotalQtytoPickBase: Decimal; WhseItemTrackingSetup: Record "Item Tracking Setup")
    var
        ...
        IsHandled: Boolean;
    begin
        // Directed put-away and pick
       ...
                    if AvailableQtyBase > 0 then begin
                        ToQtyToPickBase := CalcQtyToPickBase(FromBinContent, TempWhseActivLine);
                        if AvailableQtyBase > ToQtyToPickBase then
                            AvailableQtyBase := ToQtyToPickBase;

                        //A108B0052.Event19.05.ns
                        IsHandled := false;
                        OnFindPickBinOnBeforeCreateTempActivityLine(FromBinContent, TempWhseActivLine, ToQtyToPick, ToQtyToPickBase, AvailableQtyBase, IsHandled);
                        if not IsHandled then begin
                        //A108B0052.Event19.05.ne
                            UpdateQuantitiesToPick(
                                AvailableQtyBase,
                                FromBinContent."Qty. per Unit of Measure", FromQtyToPick, FromQtyToPickBase,
                                FromBinContent."Qty. per Unit of Measure", ToQtyToPick, ToQtyToPickBase,
                                TotalQtytoPick, TotalQtytoPickBase);

                            CreateTempActivityLine(
                                LocationCode, FromBinContent."Bin Code", UnitofMeasureCode, FromBinContent."Qty. per Unit of Measure",
                                FromQtyToPick, FromQtyToPickBase, 1, 0, QtyRndPrec, QtyRndPrecBase);
                            CreateTempActivityLine(
                                LocationCode, ToBinCode, UnitofMeasureCode, FromBinContent."Qty. per Unit of Measure",
                                ToQtyToPick, ToQtyToPickBase, 2, 0, QtyRndPrec, QtyRndPrecBase);
                        end; //A108B0052.Event19.05

                        TotalAvailQtyToPickBase := TotalAvailQtyToPickBase - ToQtyToPickBase;

    [IntegrationEvent(false, false)]
    local procedure OnFindPickBinOnBeforeCreateTempActivityLine(var FromBinContent: Record "Bin Content"; var TempWhseActivLine: Record "Warehouse Activity Line" temporary; var ToQtyToPick: Decimal; var ToQtyToPickBase: Decimal; var AvailableQtyBase: Decimal; var IsHandled: Boolean)
    begin
        //A108B0052.Event19.05
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
