### ISSUE TITLE
Enum Request Table 5054 "Contact Business Relation", field 3 "Link to Table"

### ISSUE THREAD

**Issue by TarasTarasiuk** [microsoft/ALAppExtensions#1680]
Hi Team,

Please implement field 3 "Link to Table" in table 5054 "Contact Business Relation" as an enum.

Best regards,
Taras

**Comment by peterz84** [comment]
Yes, would love to see that happening! Now we have two tables, one BC table, one extension table.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
