### ISSUE TITLE
[Event Request] Calls to DimMgmt's UpdateGlobalDimFromDimSetID procedure requesting an event after it

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#16803]
I have some event requests to handle calls to DimensionManagement's UpdateGlobalDimFromDimSetID procedure.  We have additional dimension information that needs to be updated at the same time this is procedure is called.  Although this has the largest number of calls to this procedure, fortunately, I am not needing to request events be added for all of the instances.  Because this procedure is much simpler, and more passive, I can run the original procedure and then run my version without worrying too much about performance by running some Dimension code twice.
For the areas I am requesting an event, it is because there is not an existing event I can hook into in the appropriate place, or can I modify DimensionManagement's procedure directly.  So for about 30 out of about 120 instances of the procedure call I am requesting a simple OnAfterUpdateGlobalDimFromDimSetID event be added after, with the record variable being changed passed in.

In some instances, there may need to be two record vars passed in because the Dim Set ID field comes from one table, and the dimension fields to update are in another.  I have tried to note that and other exceptions below.

Here is an example from one of the objects:

```
table 273 "Bank Acc. Reconciliation"
...
    local procedure UpdateAllLineDim(NewParentDimSetID: Integer; OldParentDimSetID: Integer)
    var
        BankAccReconciliationLine: Record "Bank Acc. Reconciliation Line";
        NewDimSetID: Integer;
    begin
        // Update all lines with changed dimensions.
        if NewParentDimSetID = OldParentDimSetID then
            exit;

        BankAccReconciliationLine.LockTable();
        if BankAccReconciliationLine.LinesExist(Rec) then begin
            if not Confirm(YouChangedDimQst) then
                exit;

            repeat
                NewDimSetID :=
                  DimMgt.GetDeltaDimSetID(BankAccReconciliationLine."Dimension Set ID", NewParentDimSetID, OldParentDimSetID);
                if BankAccReconciliationLine."Dimension Set ID" <> NewDimSetID then begin
                    BankAccReconciliationLine."Dimension Set ID" := NewDimSetID;
                    DimMgt.UpdateGlobalDimFromDimSetID(
                      BankAccReconciliationLine."Dimension Set ID",
                      BankAccReconciliationLine."Shortcut Dimension 1 Code",
                      BankAccReconciliationLine."Shortcut Dimension 2 Code");
                    OnUpdateAllLineDimOnAfterUpdateGlobalDimFromDimSetID(BankAccReconciliationLine);  // NEW EVENT CALL
                    BankAccReconciliationLine.Modify();
                end;
            until BankAccReconciliationLine.Next() = 0;
        end;
    end;
...
    // NEW EVENT DEFINITION
    [IntegrationEvent(false, false)]
    local procedure OnUpdateAllLineDimOnAfterUpdateGlobalDimFromDimSetID(var BankAccReconciliation: Record "Bank Acc. Reconciliation")
    begin
    end;

```

Sorry, my search is only referencing the .al filename that the object is located in, but I do have the procedure names that you will find the call in.

AssemblyHeader.Table.al:
- one of the two 2 instances in the object requesting an event for
    procedure CreateDim(Type1: Integer; No1: Code[20])

BankAccReconciliation.Table.al:
- one of the two 2 instances requesting an event for
    local procedure UpdateAllLineDim(NewParentDimSetID: Integer; OldParentDimSetID: Integer)

BankAccReconciliationLine.Table.al:
- one of three instances requesting an event
    procedure ShowDimensions()

CalculateInventory.Report.al:
    procedure InsertItemJnlLine(ItemNo: Code[20]; VariantCode2: Code[10]; DimEntryNo2: Integer; BinCode2: Code[20]; Quantity2: Decimal; PhysInvQuantity: Decimal)

CloseIncomeStatement.Report.al:
- 1 instance, no available event, uses lots of locals, REVIEW
        dataitem("G/L Account"; "G/L Account")
                trigger OnPostDataItem()

Consolidate.Codeunit.al:
- one of the two instances in the object requesting an event for
    local procedure CreateAndPostGenJnlLine(GenJnlLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; var DimBuf: Record "Dimension Buffer")

CustomerPaymentsEntity.Page.al:
    local procedure UpdateDimensions(LineExists: Boolean)

DimCorrectionRun.Codeunit.al:
    local procedure UpdateGLEntry(var GLEntry: Record "G/L Entry"; DimensionCorrectionEntryNo: Integer; var TempDimCorrectionSetBuffer: Record "Dim Correction Set Buffer" temporary; var TempInvalidatedDimCorrection: Record "Invalidated Dim Correction" temporary) Result: Boolean

DimensionCorrectionUndo.Codeunit.al:
    local procedure UndoGLEntry(var GLEntry: Record "G/L Entry"; var TempDimCorrectionSetBuffer: Record "Dim Correction Set Buffer" temporary; var TempInvalidatedDimCorrection: Record "Invalidated Dim Correction" temporary): Boolean

DimensionLinesEntity.Page.al:
    local procedure SaveDimensions()

ICInboxOutboxMgt.Codeunit.al:
- one of five instances could use and event
    procedure CreateJournalLines(InboxTransaction: Record "IC Inbox Transaction"; InboxJnlLine: Record "IC Inbox Jnl. Line"; var TempGenJnlLine: Record "Gen. Journal Line" temporary; GenJnlTemplate: Record "Gen. Journal Template")

InvtDocumentHeader.Table.al:
- one of the two instances in the object requesting an event for
    local procedure UpdateAllLineDim(NewParentDimSetID: Integer; OldParentDimSetID: Integer)

InvtDocumentLine.Table.al:
- two of the three instances in the object requesting an event for
    procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20])
    procedure ShowDimensions()

ItemJournalLine.Table.al:
- one of the two instances in the object requesting an event for
    local procedure PickDimension(TableArray: array[10] of Integer; CodeArray: array[10] of Code[20]; InheritFromDimSetID: Integer; InheritFromTableNo: Integer)

JobCalculateWIP.Codeunit.al:
- one of the two instances in the object requesting an event for
    local procedure CreateWIPEntries(JobNo: Code[20])

PhysInvtOrderHeader.Table.al:
- one of the two instances in the object requesting an event for
    local procedure UpdateAllLineDim(NewParentDimSetID: Integer; OldParentDimSetID: Integer)

PhysInvtOrderLine.Table.al:
- one of the two instances in the object requesting an event for
    procedure CreateDim(Type1: Integer; No1: Code[20])

ProdOrderLine.Table.al:
- one of the two instances in the object requesting an event for
    procedure UpdateProdOrderCompDim(NewDimSetID: Integer; OldDimSetID: Integer)

ProductionOrder.Table.al:
- one of the two instances in the object requesting an event for
    local procedure UpdateAllLineDim(NewParentDimSetID: Integer; OldParentDimSetID: Integer)

SaveasStandardGenJournal.Report.al:
- one reference, needs event with Rec and DimSetID as params
        DimMgt.UpdateGlobalDimFromDimSetID(GenJnlLine."Dimension Set ID", StdGenJnlLine."Shortcut Dimension 1 Code",

ServiceHeader.Table.al:
- Three of four instances requesting an event for
    procedure UpdateAllLineDim(NewParentDimSetID: Integer; OldParentDimSetID: Integer)
- two of the instances in this next procedure to add an event
    procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20]; Type4: Integer; No4: Code[20]; Type5: Integer; No5: Code[20])

ServiceItemLine.Table.al:
- two of the three instances in the object requesting an event for
    procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20])
    procedure UpdateAllLineDim(NewParentDimSetID: Integer; OldParentDimSetID: Integer)

SuggestEmployeePayments.Report.al:
    local procedure UpdateDimensions(var GenJnlLine: Record "Gen. Journal Line")

SuggestVendorPayments.Report.al:
    local procedure UpdateDimensions(var GenJnlLine: Record "Gen. Journal Line")

Thank you.

Denis

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
