### ISSUE TITLE
Report 12471 "Shipment Request M-11" skips records

### ISSUE THREAD

**Issue by ABaludin** [microsoft/ALAppExtensions#16815]
Issue confirmed in BC19 (including the latest 19.5), BC18, BC17, NAV2016
Excel Report skips the reсords in the page breaks. Usually it's the line number 18 or 19.

How to reproduce:
Create Posted Transfer Receipt with line number more than 20. Print report 12471 from it. Compare lines in the Transfer receipt with printed report in Excel. Each page break it will skip 1 line.

**Comment by AlexanderYakunin** [comment]
Please report bugs via technical support (CSS). This forum is for extensibility request and issues.
