### ISSUE TITLE
[Event Modify Request] codeunit 6500 "Item Tracking Management" - OnRetrieveSubcontrItemTrackingOnAfterDeleteReservEntries

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16814]
Enhance existing event OnRetrieveSubcontrItemTrackingOnAfterDeleteReservEntries with parameter ReservEntry

local procedure RetrieveSubcontrItemTracking(ItemJnlLine: Record "Item Journal Line"; var TempHandlingSpecification: Record "Tracking Specification" temporary) Result: Boolean
        ...
        if SumUpItemTracking(ReservEntry, TempHandlingSpecification, false, true) then begin
            ReservEntry.SetRange("Reservation Status", ReservEntry."Reservation Status"::Prospect);
            ReservEntry.SetRange("Qty. to Handle (Base)"); //A108B0012.n
            if not ReservEntry.IsEmpty() then
                ReservEntry.DeleteAll();
            //OnRetrieveSubcontrItemTrackingOnAfterDeleteReservEntries(TempHandlingSpecification); A108B0012.Event20.00.o
            OnRetrieveSubcontrItemTrackingOnAfterDeleteReservEntries(TempHandlingSpecification, ReservEntry); //A108B0012.Event20.00.n
            exit(true);
        end;

    [IntegrationEvent(false, false)]
    local procedure OnRetrieveSubcontrItemTrackingOnAfterDeleteReservEntries(var TempHandlingSpecification: Record "Tracking Specification" temporary; var ReservationEntry: Record "Reservation Entry")
    begin
        //A108B0012.Event20.00 Parameter ReservationEntry
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
