### ISSUE TITLE
[Access Request] report 188 "Create Reminders"  - Request Page parameters

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#16811]
Can you please change to scope of the following variables to `protected`?

```al
protected var
        OverdueEntriesOnly: Boolean;
        UseHeaderLevel: Boolean;
        IncludeEntriesOnHold: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
