### ISSUE TITLE
[Event Request] codeunit 1004 "Job Transfer Line" - OnFromPlanningLineToJnlLineOnBeforeCopyItemTracking

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16824]
procedure FromPlanningLineToJnlLine(JobPlanningLine: Record "Job Planning Line"; PostingDate: Date; JobJournalTemplateName: Code[10]; JobJournalBatchName: Code[10]; var JobJnlLine: Record "Job Journal Line")
        ...
        JobJnlLine.UpdateDimensions;
        //A200F0000.Event19.05.ns
        IsHandled := false;
        OnFromPlanningLineToJnlLineOnBeforeCopyItemTracking(JobJnlLine, JobPlanningLine, IsHandled);
        if not IsHandled then
            //A200F0000.Event19.05.ne
            ItemTrackingMgt.CopyItemTracking(JobPlanningLine.RowID1, JobJnlLine.RowID1, false);

        JobJnlLine.Insert(true);

    [IntegrationEvent(false, false)]
    local procedure OnFromPlanningLineToJnlLineOnBeforeCopyItemTracking(var JobJournalLine: Record "Job Journal Line"; var JobPlanningLine: Record "Job Planning Line"; var IsHandled: Boolean)
    begin
        //A200F0000.Event19.05
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
