### ISSUE TITLE
[Extensibility Request] Codeunit 550 VAT Rate Change Conversion - UpdateRec

### ISSUE THREAD

**Issue by JerryTyssen** [microsoft/ALAppExtensions#16820]
Hello,

In response to https://github.com/microsoft/ALAppExtensions/issues/16631 (See comments section), we would like the following procedure to be made global in Codeunit 550 - VAT Rate Change Conversion:

`local procedure UpdateRec(var RecRef: RecordRef; ConvertVATProdPostingGroup: Boolean; ConvertGenProdPostingGroup: Boolean)`

Note: as mentioned in https://github.com/microsoft/ALAppExtensions/issues/16631, the global variable "VATRateChangeSetup" in this procedure cannot be fully used outside this codeunit. Can we make this "VATRateChangeSetup" local instead so this procedure can be made global?

Thanks in advance,
Jerry Tyssen
Cegeka

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
