### ISSUE TITLE
Event Request Codeunit 99000831 "Reservation Engine Mgt." OnAfterCloseReservEntry

### ISSUE THREAD

**Issue by AndriiBodashevskyi** [microsoft/ALAppExtensions#16825]
Hello, could you please add OnAfterCloseReservEntry event at the very end of the CloseReservEntry procedure in the codeunit 99000831 like this?

    if ReTrack then begin
        TotalQty := ReservMgt.SourceQuantity(ReservEntry, true);
        ReservMgt.AutoTrack(TotalQty);
    OnAfterCloseReservEntry(ReservEntry);

    [IntegrationEvent(false, false)]
    local procedure  OnAfterCloseReservEntry(var ReservEntry: Record "Reservation Entry")
    begin
   
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
