### ISSUE TITLE
Event Request Codeunit 99000836 "Transfer Line-Reserve" OnCreateReservationOnBeforeCreateReservEntry

### ISSUE THREAD

**Issue by AndriiBodashevskyi** [microsoft/ALAppExtensions#16834]
Hello, could you please change the part of the code of the CreateReservation procedure in the codeunit 99000836 like this?

    IsHandled := false;
    OnCreateReservationOnBeforeCreateReservEntry(TransLine, Quantity, QuantityBase, ForReservEntry, Direction, IsHandled);
    if not IsHandled then 
          CreateReservEntry.CreateReservEntryFor(
          DATABASE::"Transfer Line", Direction.AsInteger(), TransLine."Document No.", '',
          TransLine."Derived From Line No.", TransLine."Line No.", TransLine."Qty. per Unit of Measure",
          Quantity, QuantityBase, ForReservEntry);
    if not IsHnadled then
        CreateReservEntry.CreateReservEntryFrom(FromTrackingSpecification);
    IsHandled := false;

    [IntegrationEvent(false, false)]
    local procedure OnCreateReservationOnBeforeCreateReservEntry(var TransLine: Record "Transfer Line"; var Quantity: Decimal; var QuantityBase: Decimal; var ForReservEntry: Record "Reservation Entry"; var Direction: Enum "Transfer Direction"; var IsHandled: Boolean)
    begin

    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
