### ISSUE TITLE
[Apply Event Request] codeunit 99000838 "Prod. Order Comp.-Reserve" - OnAfterClearTrackingFilter

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16836]
Could you remove to two Setranges on Serial and Lot No. and replace it with the standard procedure ClearTrackingFilter so we and the Base can use the event OnAfterClearTrackingFilter in that procedure in T337?

    procedure TransferPOCompToItemJnlLineCheckILE(var OldProdOrderComp: Record "Prod. Order Component"; var NewItemJnlLine: Record "Item Journal Line"; TransferQty: Decimal; CheckApplFromItemEntry: Boolean)
        ...
                EndLoop := TransferQty = 0;
                if not EndLoop then
                    if ReservEngineMgt.NEXTRecord(OldReservEntry) = 0 then
                        if ItemTrackingFilterIsSet then begin
                            //A200F0000.Event19.05.os
                            //OldReservEntry.SetRange("Serial No.");
                            //OldReservEntry.SetRange("Lot No.");
                            //A200F0000.Event19.05.oe
                            OldReservEntry.ClearTrackingFilter; //A200F0000.Event19.05
                            ItemTrackingFilterIsSet := false;
                            EndLoop := not ReservEngineMgt.InitRecordSet(OldReservEntry);
                        end else
                            EndLoop := true;
            until EndLoop;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
