### ISSUE TITLE
[Request] codeunit 5407 "Prod. Order Status Management" - ChangeProdOrderStatus

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16847]
After using the procedure ChangeProdOrderStatus there is no way to get to the variable ToProdOrder and know what the production order no. is tranferred to. Without compromising the Base I would suggest to add a new procedure:

    procedure ChangeProdOrderStatus(ProdOrder: Record "Production Order"; var NewProdOrder: Record "Production Order"; NewStatus: Enum "Production Order Status"; NewPostingDate: Date; NewUpdateUnitCost: Boolean)
    begin
        ChangeProdOrderStatus(ProdOrder, NewStatus, NewPostingDate, NewUpdateUnitCost);
        NewProdOrder := ToProdOrder;
    end;

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
