### ISSUE TITLE
[Event Request] Codeunit 99000774 OnBeforeCalcExpectedCost

### ISSUE THREAD

**Issue by GuntherGebauer** [Microsoft/ALAppExtensions#1685]
We Need a new Eventtrigger in Codeunit 99000773 before the expected Costs are calculated.

PROCEDURE [External] CalculateRoutingLine
...

ProdOrderRoutingLine."Input Quantity" := MaxLotSize;

IF ActualOperOutput > 0 THEN BEGIN
  TotalQtyPerOperation :=
    ExpectedOperOutput *
    (1 + ProdOrderRoutingLine."Scrap Factor % (Accumulated)") *
    (1 + TotalScrap / 100) +
    ProdOrderRoutingLine."Fixed Scrap Qty. (Accum.)";
END ELSE
  TotalQtyPerOperation := MaxLotSize;

OnBeforeCalcExpectedCost(VAR ProdOrderRoutingLine;VAR MaxLotSize;VAR TotalCapacityPerOperation;ActualOperOutput);  <-- New Eventtrigger
TotalCapacityPerOperation :=

**Comment by GuntherGebauer** [comment]
I am sorry, the new trigger it should be in codeunit 99000774 - not CU99000773

**Comment by AlexanderYakunin** [comment]
Please update you ask for current code structure. I need to know exact position for new event.

**Comment by GuntherGebauer** [comment]
The exact Position of the new Event trigger should be:

Codeunit 99000774
in
[External] CalculateRoutingLine(VAR ProdOrderRoutingLine2 : Record "Prod. Order Routing Line";Direction : 'Forward,Backward';CalcStartEndDate : Boolean)

...



MaxLotSize :=
  ProdOrderQty *
  (1 + ProdOrderRoutingLine."Scrap Factor % (Accumulated)") *
  (1 + TotalScrap / 100) +
  ProdOrderRoutingLine."Fixed Scrap Qty. (Accum.)";

ProdOrderRoutingLine."Input Quantity" := MaxLotSize;

IF ActualOperOutput > 0 THEN BEGIN
  TotalQtyPerOperation :=
    ExpectedOperOutput *
    (1 + ProdOrderRoutingLine."Scrap Factor % (Accumulated)") *
    (1 + TotalScrap / 100) +
    ProdOrderRoutingLine."Fixed Scrap Qty. (Accum.)";
END ELSE
  TotalQtyPerOperation := MaxLotSize;

//M365+++++++++++++++++++++++
OnBeforeCalcExpectedCost(VAR ProdOrderRoutingLine;VAR MaxLotSize:Decimal;VAR TotalQtyPerOperation:Decimal;ActualOperOutput:Decimal); <-- New Eventtrigger
//M265-----------------------
TotalCapacityPerOperation :=
  ROUND(
    TotalQtyPerOperation *
    ProdOrderRoutingLine.RunTimePer *
    CalendarMgt.QtyperTimeUnitofMeasure(
      ProdOrderRoutingLine."Work Center No.",ProdOrderRoutingLine."Run Time Unit of Meas. Code"),
    0.00001);
IF MfgSetup."Cost Incl. Setup" THEN BEGIN
  ConCurrCapacity := ProdOrderRoutingLine."Concurrent Capacities";
  IF ConCurrCapacity = 0 THEN
    ConCurrCapacity := 1;
  TotalCapacityPerOperation :=
    TotalCapacityPerOperation +
    ROUND(
      ConCurrCapacity * ProdOrderRoutingLine."Setup Time" *
      CalendarMgt.QtyperTimeUnitofMeasure(
        ProdOrderRoutingLine."Work Center No.",ProdOrderRoutingLine."Setup Time Unit of Meas. Code"),
      0.00001);
END;
CalcExpectedCost(ProdOrderRoutingLine,TotalQtyPerOperation,TotalCapacityPerOperation);

OnBeforeScheduleRoutingLine(ProdOrderRoutingLine);

IF ProdOrderRoutingLine."Schedule Manually" THEN

**Comment by AlexanderYakunin** [comment]
What is ActualOperOutput? Seems like your own variable?

**Comment by GuntherGebauer** [comment]
Hi Alexander,
have a look in the actual OnPrem Codeunit 99000774 ReleaseVersion 'NAVW113.04'  DateTime 12th February 2019 - ActualOperOutput is and was ever an official local variable from NAV/BC365 in Procedure CalculateRoutingLine - where I need the Event trigger.

**Comment by AlexanderYakunin** [comment]
We accept event request based on latest preview builds. And 13.X was replaced by 14.X since April 1st.

**Comment by GuntherGebauer** [comment]
and variable ActualOperOutput  is deleted in 14.X without any substitution ??

I will check that - and I had entered this request at a time where 14.x was not yet released

**Comment by GuntherGebauer** [comment]
Hi Alexander,
I have checked Version 14.X and ActualOperOutput  is located at the exactly same place as before - so please accept the request for a new Publisher in codeunit 990007774 as described:

OnBeforeCalcExpectedCost

**Comment by AlexanderYakunin** [comment]
You have wrong title for COD99000773 and I cannot read all comments all the time, so I missed this is now for COD99000774.
