### ISSUE TITLE
[Event Parameter Request] codeunit 90 "Purch.-Post" - OnPostItemChargePerSalesShptOnBeforeTestJobNo

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16852]
We would like Base event OnPostItemChargePerSalesShptOnBeforeTestJobNo to be enhanced with parameter PurchLine

    local procedure PostItemChargePerSalesShpt(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line")
        ...
        IsHandled := false;
        //OnPostItemChargePerSalesShptOnBeforeTestJobNo(SalesShptLine, IsHandled); A108F0086.Event19.05.o
        OnPostItemChargePerSalesShptOnBeforeTestJobNo(SalesShptLine, PurchLine, IsHandled); //A108F0086.Event19.05.n
        if not IsHandled then
            SalesShptLine.TestField("Job No.", '');

    [IntegrationEvent(false, false)]
    local procedure OnPostItemChargePerSalesShptOnBeforeTestJobNo(SalesShipmentLine: Record "Sales Shipment Line"; var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
        //A108F0086.Event19.05 Parameter PurchaseLine
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
