### ISSUE TITLE
[Event Request] codeunit 70 "Purch.-Calc.Discount" - OnCalculateInvoiceDiscountOnBeforeSetPurchaseLineDescription

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16850]
PurchLine2.Validate("No.", VendPostingGr.GetServiceChargeAccount);
                    //A108F0006.Event19.05.ns
                    IsHandled := false;
                    OnCalculateInvoiceDiscountOnBeforeSetPurchaseLineDescription(PurchLine2, PurchHeader, IsHandled);
                    if not IsHandled then
                        //A108F0006.Event19.05.ne
                        PurchLine2.Description := Text000;
                    PurchLine2.Validate(Quantity, 1);

    [IntegrationEvent(false, false)]
    local procedure OnCalculateInvoiceDiscountOnBeforeSetPurchaseLineDescription(var PurchaseLine: Record "Purchase Line"; var PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
    begin
        //A108F0006.Event19.05
    end;

**Comment by AlexanderYakunin** [comment]
No need for hahdled events here, simply OnBeforeInsert event will allow you to set Description you need.

**Comment by Duizy1971** [comment]
Hi Alexander,

Both T39 Descripion and "Description 2" are already set when validating "No.". we have een "G/L Account" and "Item Charge" translation table and together with the T38."Language Code" we do the translation already in T39. Exactly the same as it does with "Item Translation". It would be very expensive and ugly to fetch the header and perform the same code again in an OnBeforeInsert trigger. In previous issues I have already requested the passing of the PurchaseHeader with events like OnAfterAssignGLAccountValues and OnAfterAssignItemChargeValues in T39/T37/T5902 to make the same time of code working. Moreover it is not necessary to have the code 'PurchLine2.Description' at all because it is a fixed translation Text000 and the customer cannot change that at all. So please add the requested event.
