### ISSUE TITLE
[Event Parameter Request] codeunit 90 "Purch.-Post" - OnPostItemChargePerRetShptOnBeforeTestJobNo

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16851]
We would like Base event OnPostItemChargePerRetShptOnBeforeTestJobNo to be enhanced with parameter PurchLine

    local procedure PostItemChargePerRetShpt(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line")
    var
        ReturnShptLine: Record "Return Shipment Line";
        TempItemLedgEntry: Record "Item Ledger Entry" temporary;
        Sign: Decimal;
        DistributeCharge: Boolean;
        IsHandled: Boolean;
    begin
        ReturnShptLine.Get(
          TempItemChargeAssgntPurch."Applies-to Doc. No.", TempItemChargeAssgntPurch."Applies-to Doc. Line No.");

        IsHandled := false;
        //OnPostItemChargePerRetShptOnBeforeTestJobNo(ReturnShptLine, IsHandled); A108F0086.Event.o
        OnPostItemChargePerRetShptOnBeforeTestJobNo(ReturnShptLine, PurchLine, IsHandled); //A108F0086.Event.n
        if not IsHandled then
            ReturnShptLine.TestField("Job No.", '');

    [IntegrationEvent(false, false)]
    local procedure OnPostItemChargePerRetShptOnBeforeTestJobNo(ReturnShipmentLine: Record "Return Shipment Line"; var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
        //A108F0086 Parameters PurchaseLine
    end;

**Comment by Stepanenko-Vadim** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
