### ISSUE TITLE
[Event request] codeunit 99000831 "Reservation Engine Mgt." - OnSetItemTracking2OnBeforeShouldShowCannotStateItemTrackingError

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16858]
local procedure SetItemTracking2(TempReservEntry2: Record "Reservation Entry"; var TrackingSpecification2: Record "Tracking Specification")
    var
        ShouldShowError: Boolean;
    begin
        if TempReservEntry2.Binding = TempReservEntry2.Binding::"Order-to-Order" then begin
            // only supply can change IT and demand must respect it
            //A108B0035.Event19.05.os
            //if TempReservEntry2.Positive and
            //   not TempReservEntry2.HasSameTrackingWithSpec(TrackingSpecification2)
            //then
            //A108B0035.Event19.05.oe
            //A108B0035.Event19.05.ns
            ShouldShowError := TempReservEntry2.Positive and not TempReservEntry2.HasSameTrackingWithSpec(TrackingSpecification2);
            OnSetItemTracking2OnBeforeShouldShowCannotStateItemTrackingError(TempReservEntry2, TrackingSpecification2, ShouldShowError);
            if ShouldShowError then
                //A108B0035.Event19.05.ne
                Error(CannotStateItemTrackingErr, TempReservEntry2.FieldCaption(Binding), TempReservEntry2.Binding);
        end else
            // each record brings/holds own IT
            TrackingSpecification2.CopyTrackingFromReservEntry(TempReservEntry2);

        OnAfterSetItemTracking2(TrackingSpecification2, TempReservEntry2);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnSetItemTracking2OnBeforeShouldShowCannotStateItemTrackingError(TempReservEntry2: Record "Reservation Entry"; var TrackingSpecification2: Record "Tracking Specification"; var ShouldShowError: Boolean)
    begin
        //A108B0035.Event19.05
    end;

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
