### ISSUE TITLE
page 30066 "APIV2 - Purchase Orders" - ReceiveAndInvoice bug

### ISSUE THREAD

**Issue by bfranzwipfli** [microsoft/ALAppExtensions#16868]
API returns 400 Bad Request message when receiveAndInvoice action is invoked where invoiceQuantity for po lines = 0 but receipt of the lines does in fact complete in the application.

Reproduction steps:
![image](https://user-images.githubusercontent.com/57499608/160014520-19f0b478-7169-4995-9a09-7c8a75596f23.png)

POST request to: /purchaseOrders({id})/Microsoft.NAV.receiveAndInvoice results in:
{
    "error": {
        "code": "Internal_DataNotFoundFilter",
        "message": "There is no Purch. Inv. Header within the filter.\r\n\r\nFilters: Order No.: 106024, Order No. Series: P-ORD, Pre-Assigned No.: ''  CorrelationId:  e7b4742f-fac6-427c-8ffc-68339c16c34c."
    }
}

![image](https://user-images.githubusercontent.com/57499608/160014546-c5cbeae6-a68d-4d4b-92ec-75f6b032cd39.png)

I believe the issue is the result of the following code in the PostInvoice procedure: https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/APIV2/app/src/pages/APIV2PurchaseOrders.Page.al#:~:text=PurchInvHeader.FindFirst()%3B

Given Qty. to Invoice on the line(s) was 0 when posting was invoked, BC never created a Purch. Inv. Header record to be found at the conclusion of the PostInvoice procdure.

I expect the salesOrders endpoint would have a similar issue based on the the following code but have not literally tested to confirm: https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/APIV2/app/src/pages/APIV2SalesOrders.Page.al#:~:text=SalesInvoiceHeader.FindFirst()

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
