### ISSUE TITLE
[Event Change] codeunit 7312 "Create Pick", OnCreateWhseDocumentOnAfterSaveOldValues

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#16867]
Hi Team,

could you please change signature of publisher OnCreateWhseDocumentOnAfterSaveOldValues in codeunit "Create Pick" as shown below:

``` AL
[IntegrationEvent(false, false)]
local procedure OnCreateWhseDocumentOnAfterSaveOldValues(var TempWarehouseActivityLine: Record "Warehouse Activity Line" temporary; var WhseActivHeader: Record "Warehouse Activity Header"; LastWhseDocNo: Code[20])
begin
end;
```

Change adds WhseActivHeader Record Variable and LastWhseDocNo variable to event signature.

``` AL
// Requested Change
//OnCreateWhseDocumentOnAfterSaveOldValues(TempWhseActivLine);
OnCreateWhseDocumentOnAfterSaveOldValues(TempWhseActivLine,WhseActivHeader,LastWhseDocNo);
// --
```

Thanks in advance,
Christian

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
