### ISSUE TITLE
Preassegnazione numero di serie definito in Fatture

### ISSUE THREAD

**Issue by ErikaC82** [microsoft/ALAppExtensions#16862]
Durante la compilazione della Fatture provvisorie ( acquisto /vendita ) il sistema assegna il numero di serie definitivo, e non permette di cancellare il documento o di variare il Vendere/Acquistare A.

Questo crea buchi di numerazione.

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot address your request, this is not related to extensibility. If you have a bug, you can create hotfix request using technical support.
