### ISSUE TITLE
[Extensibility Request] Table VAT Clause (560)

### ISSUE THREAD

**Issue by operrui** [microsoft/ALAppExtensions#16865]
Hi team,
We need to include new values ​​for the 10700 field.
Could you substitute the type option to enum?

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
