### ISSUE TITLE
[Extensibility Request] codeunit 7312 "Create Pick", EnqueueCannotBeHandledReason

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#16863]
Hi Team,

is it possible to change procedure **EnqueueCannotBeHandledReason** in "Create Pick" Codeunit from local to global?

we would like to call this procedure from a publisher which includes the sender, so that we can add a reason to CannotBeHandledReasons-Array.

```
// Requested change
//local procedure EnqueueCannotBeHandledReason(CannotBeHandledReason: Text)
procedure EnqueueCannotBeHandledReason(CannotBeHandledReason: Text)
//--
var
    NewReasonAdded: Boolean;
    i: Integer;
begin
    if CannotBeHandledReason = '' then
        exit;

    repeat
        i += 1;
        if CannotBeHandledReasons[i] = '' then begin
            CannotBeHandledReasons[i] := CannotBeHandledReason;
            NewReasonAdded := true;
        end;
    until NewReasonAdded or (i = ArrayLen(CannotBeHandledReasons));
end;
```

Thanks,
Christian

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
