### ISSUE TITLE
[Event Request] Wrap three back to back DimMgt calls with a single event to allow override

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#16860]
We would like to request a new event to cover calls to Dimension Management routines.  I have additional dimension data to process and these calls are three in a row that can be wrapped by and event and IsHandled code pattern.  The three objects alll have a similar structure, but the middle procedure (...NextHigherPriority call) is just different for each one.  That will result in the specific parameters needed to pass to the event, becomes a combination of the parameters to the individual calls into DimMgt, with a final IsHandled and a return DimSetID parameters added.

I have created an example call:

```
table 210 "Job Journal Line"

    procedure ShowDimensions()
    begin
        "Dimension Set ID" :=
          DimMgt.EditDimensionSet("Dimension Set ID", StrSubstNo('%1 %2 %3', "Journal Template Name", "Journal Batch Name", "Line No."));
        DimMgt.UpdateGlobalDimFromDimSetID("Dimension Set ID", "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");

        OnAfterShowDimensions(Rec, xRec);
    end;

    procedure UpdateDimensions()
    var
        DimensionSetIDArr: array[10] of Integer;
        IsHandled: Boolean;  // NEW VAR
    begin
        CreateDim(
          DimMgt.TypeToTableID2(Type.AsInteger()), "No.",
          DATABASE::Job, "Job No.",
          DATABASE::"Resource Group", "Resource Group No.");
        if "Job Task No." <> '' then begin
            DimensionSetIDArr[1] := "Dimension Set ID";
            // NEW CODE begin
            IsHandled := false;
            OnUpdateDimensionsOnBeforeMakeDimSet(Rec, CurrFieldNo, DimensionSetIDArr, "Job No.", "Job Task No.", "Source Code", DATABASE::Job, IsHandled, "Dimension Set ID");
            if not IsHandled then begin
            // NEW CODE end, indent next three statements
            DimensionSetIDArr[2] :=
              DimMgt.CreateDimSetFromJobTaskDim("Job No.",
                "Job Task No.", "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");
            DimMgt.CreateDimForJobJournalLineWithHigherPriorities(
              Rec, CurrFieldNo, DimensionSetIDArr[3], "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code", "Source Code", DATABASE::Job);
            "Dimension Set ID" :=
              DimMgt.GetCombinedDimensionSetID(
                DimensionSetIDArr, "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");
            // NEW CODE begin, terminiation of IsHandled check
            end;
            // NEW CODE end
        end;

        OnAfterUpdateDimensions(Rec, DimensionSetIDArr);
    end;
...
    [IntegrationEvent(false, false)]
    local procedure OnUpdateDimensionsOnBeforeMakDimSet(var JobJournalLine: Record "Job Journal Line"; CurrFieldNo: Integer; (DimensionSetIDArr: array[10] of Integer; JobNo: Code[20]; JobTaskNo: Code[20]; SourceCode: Code[10]; PriorityTableID: Integer; var IsHandled: Boolean; var ResultDimSetID: Integer);
    begin
    end;

```

There are only three instances for this one:

codeunit 1002 "Job Create-Invoice"
    local procedure UpdateSalesLineDimension(var SalesLine: Record "Sales Line"; JobPlanningLine: Record "Job Planning Line")

table 210 "Job Journal Line"
    procedure UpdateDimensions()

table 39 "Purchase Line"
    local procedure UpdateDimensionsFromJobTask()

**Comment by AlexanderYakunin** [comment]
We don't like to insert handled events in the middle of code, instead we'd better add OnBefore handled event to let you do what you need for your business logic.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
