### ISSUE TITLE
[Event Request] codeunit 7324 "Whse.-Activity-Post" - OnPostOutputLineOnAfterInitItemJournalLine

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16878]
local procedure PostOutputLine(ProdOrder: Record "Production Order"; ProdOrderLine: Record "Prod. Order Line")
    var
        ItemJnlLine: Record "Item Journal Line";
        ItemJnlPostLine: Codeunit "Item Jnl.-Post Line";
        ReservProdOrderLine: Codeunit "Prod. Order Line-Reserve";
    begin
        with TempWhseActivLine do begin
            ItemJnlLine.Init();
            OnPostOutputLineOnAfterInitItemJournalLine(ItemJnlLine, SourceCodeSetup); //A108B0045.Event19.05
            ItemJnlLine.Validate("Entry Type", ItemJnlLine."Entry Type"::Output);

    [IntegrationEvent(false, false)]
    local procedure OnPostOutputLineOnAfterInitItemJournalLine(var ItemJournalLine: Record "Item Journal Line"; SourceCodeSetup: Record "Source Code Setup")
    begin
        //A108B0045.Event19.05
    end;

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
