### ISSUE TITLE
[Event Request] codeunit 5817 "Undo Posting Management" - OnBeforeUpdatePurchLine

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16876]
procedure UpdatePurchLine(PurchLine: Record "Purchase Line"; UndoQty: Decimal; UndoQtyBase: Decimal; var TempUndoneItemLedgEntry: Record "Item Ledger Entry" temporary)
    var
        xPurchLine: Record "Purchase Line";
        PurchSetup: Record "Purchases & Payables Setup";
        IsHandled: Boolean;
    begin
        //A108B0020.Event19.05.ns
        OnBeforeUpdatePurchLine(PurchLine, UndoQty, UndoQtyBase, TempUndoneItemLedgEntry, IsHandled);
        if IsHandled then
            exit;
        //A108B0020.Event19.05.ne
        PurchSetup.Get();
        with PurchLine do begin

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdatePurchLine(PurchLine: Record "Purchase Line"; var UndoQty: Decimal; var UndoQtyBase: Decimal; var TempUndoneItemLedgEntry: Record "Item Ledger Entry" temporary; var IsHandled: Boolean)
    begin
        //A108B0020.Event19.05
    end;

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
