### ISSUE TITLE
[Event Request] codeunit 7324 "Whse.-Activity-Post" - OnPostConsumptionLineOnAfterInitItemJournalLine

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16879]
local procedure PostConsumptionLine(ProdOrder: Record "Production Order"; ProdOrderComp: Record "Prod. Order Component")
    var
        ItemJnlLine: Record "Item Journal Line";
        ProdOrderLine: Record "Prod. Order Line";
        ItemJnlPostLine: Codeunit "Item Jnl.-Post Line";
        ProdOrderCompReserve: Codeunit "Prod. Order Comp.-Reserve";
    begin
        with TempWhseActivLine do begin
            ProdOrderLine.Get("Source Subtype", "Source No.", "Source Line No.");
            ItemJnlLine.Init();
            OnPostConsumptionLineOnAfterInitItemJournalLine(ItemJnlLine, SourceCodeSetup); //A108B0045.Event19.05
            ItemJnlLine.Validate("Entry Type", ItemJnlLine."Entry Type"::Consumption);

    [IntegrationEvent(false, false)]
    local procedure OnPostConsumptionLineOnAfterInitItemJournalLine(var ItemJournalLine: Record "Item Journal Line"; SourceCodeSetup: Record "Source Code Setup")
    begin
        //A108B0045.Event19.05
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
