### ISSUE TITLE
[Event Request] codeunit 99000836 "Transfer Line-Reserve" - OnTransferWhseShipmentToItemJnlLineOnAfterCalcWarehouseQtyBase

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16873]
procedure TransferWhseShipmentToItemJnlLine(var TransLine: Record "Transfer Line"; var ItemJnlLine: Record "Item Journal Line"; var WhseShptHeader: Record "Warehouse Shipment Header"; TransferQty: Decimal)
        ...

                WarehouseEntry.CalcSums("Qty. (Base)");
                QtyToHandleBase := -WarehouseEntry."Qty. (Base)";
                OnTransferWhseShipmentToItemJnlLineOnAfterCalcWarehouseQtyBase(WhseShptHeader, WhseShptLine, OldReservEntry, WhseItemTrackingSetup, QtyToHandleBase); //A108B0100.Event19.05
                if Abs(QtyToHandleBase) > Abs(OldReservEntry."Qty. to Handle (Base)") then
                    QtyToHandleBase := OldReservEntry."Qty. to Handle (Base)";

    [IntegrationEvent(false, false)]
    local procedure OnTransferWhseShipmentToItemJnlLineOnAfterCalcWarehouseQtyBase(var WhseShptHeader: Record "Warehouse Shipment Header"; var WhseShptLine: Record "Warehouse Shipment Line"; var OldReservEntry: Record "Reservation Entry"; var WhseItemTrackingSetup: Record "Item Tracking Setup"; var QtyToHandleBase: Decimal);
    begin
        //A108B0100.Event19.05
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
