### ISSUE TITLE
Event Request Table 39 "Purchase Line" OnFilterLinesForReservationBeforeExpectedReceiptDateSetFilter

### ISSUE THREAD

**Issue by AndriiBodashevskyi** [microsoft/ALAppExtensions#16886]
Hello, could you please change the code of the FilterLinesForReservation procedure in the table 39 like this?

    procedure FilterLinesForReservation(ReservationEntry: Record "Reservation Entry"; DocumentType: Enum "Purchase Document Type"; AvailabilityFilter: Text; Positive: Boolean)
    var
        IsHandled: Boolean;
    begin
        Reset;
        SetCurrentKey(
          "Document Type", Type, "No.", "Variant Code", "Drop Shipment", "Location Code", "Expected Receipt Date");
        SetRange("Document Type", DocumentType);
        SetRange(Type, Type::Item);
        SetRange("No.", ReservationEntry."Item No.");
        IsHandled := false;
        OnFilterLinesForReservationOnBeforeSetFilterVariantCode(Rec, ReservationEntry, Positive, IsHandled);
        if not IsHandled then
            SetRange("Variant Code", ReservationEntry."Variant Code");
        SetRange("Drop Shipment", false);
        SetRange("Location Code", ReservationEntry."Location Code");
        IsHandled := false; //new change
        OnFilterLinesForReservationBeforeExpectedReceiptDateSetFilter(IsHandled); //new change
        if not IsHandled then //new change
            SetFilter("Expected Receipt Date", AvailabilityFilter);
        IsHandled := false; //new change
        if Positive and (DocumentType <> "Document Type"::"Return Order") then
            SetFilter("Quantity (Base)", '>0')
        else
            SetFilter("Quantity (Base)", '<0');
        SetRange("Job No.", ' ');

        OnAfterFilterLinesForReservation(Rec, ReservationEntry, DocumentType, AvailabilityFilter, Positive);
    end;

     //newchange
    [IntegrationEvent(false, false)]
    local procedure OnFilterLinesForReservationBeforeExpectedReceiptDateSetFilter(var IsHandled: Boolean)
    begin

    end;

**Comment by AlexanderYakunin** [comment]
You should use existing event OnAfterFilterLinesForReservation ro set/reset any filters
