### ISSUE TITLE
Posting Rutine- Create additional GLEntries

### ISSUE THREAD

**Issue by NedimYami** [microsoft/ALAppExtensions#16883]
Hi All,

I am trying to create extra GLEntry on posting rutine.

OnPostInvoicePostBufferOnAfterPostSalesGLAccounts procedure have GLEntryNo parameter. I need to set it as var. 

Who should I request this from? 

I know posting rutine will change. And also I convert my solution for the new posting rutine(Using interface).

But it is not support on Production now.

 

 Does anybody have any alternative solution suggestions? 

 

 
If it's not in the right forum, please let me know. 

Thank you.
![image](https://user-images.githubusercontent.com/42783080/160132461-df1b11a2-f4b8-4ab5-b46d-aa0ae4b91cf3.png)

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
