### ISSUE TITLE
Event Request Table 37 "Sales Line" OnFilterLinesForReservationAfterSalesLineSetRanges

### ISSUE THREAD

**Issue by AndriiBodashevskyi** [microsoft/ALAppExtensions#16887]
Hello, could you please change the code of the FilterLinesForReservation procedure in the table 37 like this?

    procedure FilterLinesForReservation(ReservationEntry: Record "Reservation Entry"; DocumentType: Enum "Sales Document Type"; AvailabilityFilter: Text; Positive: Boolean)
    begin
        Reset;
        SetCurrentKey(
          "Document Type", Type, "No.", "Variant Code", "Drop Shipment", "Location Code", "Shipment Date");
        SetRange("Document Type", DocumentType);
        SetRange(Type, Type::Item);
        SetRange("No.", ReservationEntry."Item No.");
        SetRange("Variant Code", ReservationEntry."Variant Code");
        SetRange("Drop Shipment", false);
        SetRange("Location Code", ReservationEntry."Location Code");
        OnFilterLinesForReservationAfterSalesLineSetRanges(Rec, ReservationEntry); //new change
        SetFilter("Shipment Date", AvailabilityFilter);
        if DocumentType = "Document Type"::"Return Order" then
            if Positive then
                SetFilter("Quantity (Base)", '>0')
            else
                SetFilter("Quantity (Base)", '<0')
        else
            if Positive then
                SetFilter("Quantity (Base)", '<0')
            else
                SetFilter("Quantity (Base)", '>0');
        SetRange("Job No.", ' ');

        OnAfterFilterLinesForReservation(Rec, ReservationEntry, DocumentType, AvailabilityFilter, Positive);
    end;

    //new change
    [IntegrationEvent(false, false)]
    local procedure OnFilterLinesForReservationAfterSalesLineSetRanges(var SalesLine: Record "Sales Line"; var ReservationEntry: Record "Reservation Entry")
    begin

    end;

**Comment by AlexanderYakunin** [comment]
Please use this event OnAfterFilterLinesForReservation(Rec, ReservationEntry, DocumentType, AvailabilityFilter, Positive); to change filters
