### ISSUE TITLE
[Event Parameter Request] codeunit 7324 "Whse.-Activity-Post" - OnInitSourceDocumentOnAfterTransferLineLoopIteration

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#16880]
local procedure InitSourceDocument()
        ...
                            until TransLine.Next() = 0;

                        //OnInitSourceDocumentOnAfterTransferLineLoopIteration(TransLine, TransHeader, WhseActivHeader); A108F0000.Event19.03.o
                        OnInitSourceDocumentOnAfterTransferLineLoopIteration(TransLine, TransHeader, WhseActivHeader, ModifyHeader); //A108F0000.Event19.03.n

                        if (TransHeader."Posting Date" <> "Posting Date") and ("Posting Date" <> 0D) then begin

    [IntegrationEvent(false, false)]
    local procedure OnInitSourceDocumentOnAfterTransferLineLoopIteration(var TransLine: Record "Transfer Line"; TransHeader: Record "Transfer Header"; WhseActivHeader: Record "Warehouse Activity Header"; var ModifyHeader: Boolean)
    begin
        //A108F0000.Event19.03 Parameter ModifyHeader
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
