### ISSUE TITLE
Event Request Table 39 "Purchase Line" OnBeforeFilterLinesForReservation

### ISSUE THREAD

**Issue by AndriiBodashevskyi** [microsoft/ALAppExtensions#16885]
Hello, could you please change the code of the FilterLinesForReservation procedure in the table 39 like this?

    procedure FilterLinesForReservation(ReservationEntry: Record "Reservation Entry"; DocumentType: Enum "Purchase Document Type"; AvailabilityFilter: Text; Positive: Boolean)
    var
        IsHandled: Boolean;
    begin
        Reset;
        OnBeforeFilterLinesForReservation(Rec); // new change
        SetCurrentKey(
          "Document Type", Type, "No.", "Variant Code", "Drop Shipment", "Location Code", "Expected Receipt Date");
        SetRange("Document Type", DocumentType);
        SetRange(Type, Type::Item);
        SetRange("No.", ReservationEntry."Item No.");
        IsHandled := false;
        OnFilterLinesForReservationOnBeforeSetFilterVariantCode(Rec, ReservationEntry, Positive, IsHandled);
        if not IsHandled then
            SetRange("Variant Code", ReservationEntry."Variant Code");
        SetRange("Drop Shipment", false);
        SetRange("Location Code", ReservationEntry."Location Code");
        SetFilter("Expected Receipt Date", AvailabilityFilter);
        if Positive and (DocumentType <> "Document Type"::"Return Order") then
            SetFilter("Quantity (Base)", '>0')
        else
            SetFilter("Quantity (Base)", '<0');
        SetRange("Job No.", ' ');

        OnAfterFilterLinesForReservation(Rec, ReservationEntry, DocumentType, AvailabilityFilter, Positive);
    end;

    //newchange
    [IntegrationEvent(false, false)]
    local procedure OnBeforeFilterLinesForReservation(var PurchaseLine: Record "Purchase Line")
    begin

    end;

**Comment by AlexanderYakunin** [comment]
Please use this event OnAfterFilterLinesForReservation(Rec, ReservationEntry, DocumentType, AvailabilityFilter, Positive); to update filters
