### ISSUE TITLE
Event Request Codeunit 99000845 "Reservation Management" OnBeforeReservedQuantityAssign

### ISSUE THREAD

**Issue by AndriiBodashevskyi** [microsoft/ALAppExtensions#16881]
Hello, could you please change the code of the MarkReservConnection procedure in the codeunit 99000845 like this?

    procedure MarkReservConnection(var ReservEntry: Record "Reservation Entry"; TargetReservEntry: Record "Reservation Entry") ReservedQuantity: Decimal
    var
        ReservEntry2: Record "Reservation Entry";
        SignFactor: Integer;
        IsHandled: Boolean; //new change
    begin
        if not ReservEntry.FindSet then
            exit;
        SignFactor := CreateReservEntry.SignFactor(ReservEntry);

        repeat
            if ReservEntry2.Get(ReservEntry."Entry No.", not ReservEntry.Positive) then
                if ReservEntry2.HasSamePointer(TargetReservEntry) then begin
                    ReservEntry.Mark(true);
                    OnBeforeReservedQuantityAssign(IsHandled, ReservedQuantity, ReservEntry, SignFactor); //new change
                    if not IsHandled then //new change
                        ReservedQuantity += ReservEntry."Quantity (Base)" * SignFactor;
                end;
        until ReservEntry.Next() = 0;
        ReservEntry.MarkedOnly(true);
    end;

    //newchange
    [IntegrationEvent(false, false)]
    local procedure OnBeforeReservedQuantityAssign(var IsHandled: Boolean; var ReservedQuantity: Decimal; var ReservEntry: Record "Reservation Entry"; var SignFactor: Integer)
    begin
   
    end;

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
