### ISSUE TITLE
[Event Change] codeunit 7312 "Create Pick", OnAfterCreateWhseDocument

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#16884]
Hi Team,

could you please change signature of publisher OnAfterCreateWhseDocument in codeunit "Create Pick" as shown below:

``` AL
[IntegrationEvent(false, false)]
local procedure OnAfterCreateWhseDocument(var FirstWhseDocNo: Code[20]; var LastWhseDocNo: Code[20]; CreatePickParameters: Record "Create Pick Parameters")
begin
end;
```

Change adds CreatePickParameters Record Variable to event signature.

``` AL
// Requested Change
//OnAfterCreateWhseDocument(FirstWhseDocNo, LastWhseDocNo);
OnAfterCreateWhseDocument(FirstWhseDocNo, LastWhseDocNo,CreatePickParameters);
// --
```

Thanks in advance,
Christian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
