### ISSUE TITLE
Report 10072 - Make variables protected

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#16889]
Can you please make the following variable protected, so additional columns can be exposed in a report extension? Thanks.

TempCustLedgEntry (resides in the OpenItem dataitem)

**Comment by AlexanderYakunin** [comment]
Can you provide report name and country version code?

**Comment by grantbrimhall** [comment]
10072. Customer Statements. US. Thx.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
