### ISSUE TITLE
[Request for External] Report 11000003 "Paymt. History - Change Status"

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#16894]
We would like global variable `NewStatus` to be moved to protected var so we can access it from a report extension.

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
