### ISSUE TITLE
New event request xmlport 9174 "Import Tenant Permission Sets"

### ISSUE THREAD

**Issue by iaxmartinwagner** [microsoft/ALAppExtensions#16896]
Hello,

I need a new event "OnAfterOnPreXmlPort" in xmlport 9174 "Import Tenant Permission Sets".

```
    trigger OnPreXmlPort()
    var
        PermissionPagesMgt: Codeunit "Permission Pages Mgt.";
    begin
        PermissionPagesMgt.DisallowEditingPermissionSetsForNonAdminUsers;
        OnAfterOnPreXmlPort(UpdatePermissions);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterOnPreXmlPort(var UpdatePermissions: boolean)
    begin
    end;
```

Kind regards
Martin

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by iaxmartinwagner** [comment]
Hi Jesper, perfect - thank´s a lot...
