### ISSUE TITLE
bug in event call OnBeforeAutoReservePurchLine in codeunit 99000845 "Reservation Management"

### ISSUE THREAD

**Issue by tyurm** [microsoft/ALAppExtensions#16899]
Hello,

I have found bug in OnBeforeAutoReservePurchLine event in codeunit 99000845 "Reservation Management" call - same variable was used twice:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/45788765/160420709-982137ac-8672-4c01-8f0a-3b4b8db7d409.png">

as you can see on the screenshot "RemainingQtyToReserveBase" variable does exist in the AutoReservePurchLine procedure scope, and can be used in event call.

this is the event declaration:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeAutoReservePurchLine(ReservSummEntryNo: Integer; var RemainingQtyToReserve: Decimal; var RemainingQtyToReserveBase: Decimal; Description: Text[100]; AvailabilityDate: Date; var IsReserved: Boolean; var Search: Text[1]; var NextStep: Integer; CalcReservEntry: Record "Reservation Entry")
begin
end;
```

As far as both variables are declared "by var" it is impossible to change RemainingQtyToReserveBase variable due to this bug.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
