### ISSUE TITLE
codeunit 1234 "Json Text Reader/Writer" - Make JsonTextWriter.WriteNull public

### ISSUE THREAD

**Issue by mart1n89** [microsoft/ALAppExtensions#16890]
It's possible to use "procedure WriteNullProperty(VariableName: Text)" with a given VariableName:

![image](https://user-images.githubusercontent.com/19255022/160344174-22ffb66f-1f3e-4115-8699-126e29701a46.png)

We need the possibility to use this procedure without a given VariableName:

![image](https://user-images.githubusercontent.com/19255022/160344940-bd500657-2fd1-4455-8efb-80b0a7ff4091.png)

Or maybe better just:

![image](https://user-images.githubusercontent.com/19255022/160344992-f0786c14-acf2-4f27-8a98-727210337524.png)

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
