### ISSUE TITLE
Event Request Table 39 "Purchase Line" OnBeforeGetReservationQty

### ISSUE THREAD

**Issue by AndriiBodashevskyi** [microsoft/ALAppExtensions#16905]
Hello, could you please change the code of the GetReservationQty procedure in the table 39 like this?

    procedure GetReservationQty(var QtyReserved: Decimal; var QtyReservedBase: Decimal; var QtyToReserve: Decimal; var QtyToReserveBase: Decimal) Result: Decimal
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetReservationQty(IsHandled, Rec, QtyReserved, QtyReservedBase, QtyToReserve, QtyToReserveBase);
        if not IsHandled then begin
            CalcFields("Reserved Quantity", "Reserved Qty. (Base)");
            if "Document Type" = "Document Type"::"Return Order" then begin
                "Reserved Quantity" := -"Reserved Quantity";
                "Reserved Qty. (Base)" := -"Reserved Qty. (Base)";
            end;
            QtyReserved := "Reserved Quantity";
            QtyReservedBase := "Reserved Qty. (Base)";
            QtyToReserve := "Outstanding Quantity";
            QtyToReserveBase := "Outstanding Qty. (Base)";
            Result := "Qty. per Unit of Measure";
            OnAfterGetReservationQty(Rec, QtyReserved, QtyReservedBase, QtyToReserve, QtyToReserveBase, Result);
        end else begin
            Result := "Qty. per Unit of Measure";
            OnAfterGetReservationQty(Rec, QtyReserved, QtyReservedBase, QtyToReserve, QtyToReserveBase, Result);
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure  OnBeforeGetReservationQty(var IsHandled: Boolean; var PurchaseLine: Record "Purchase Line"; var QtyReserved: Decimal; var QtyReservedBase: Decimal; var QtyToReserve: Decimal; var QtyToReserveBase: Decimal)
    begin

    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
