### ISSUE TITLE
Event Request Table 32 "Item Ledger Entry" OnBeforeGetReservationQty

### ISSUE THREAD

**Issue by AndriiBodashevskyi** [microsoft/ALAppExtensions#16906]
Hello, could you please change the code of the GetReservationQty procedure in the table 32 like this?

    procedure GetReservationQty(var QtyReserved: Decimal; var QtyToReserve: Decimal)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetReservationQty(IsHandled, Rec, QtyReserved, QtyToReserve);
        if not IsHandled then begin
            CalcFields("Reserved Quantity");
            QtyReserved := "Reserved Quantity";
            QtyToReserve := "Remaining Quantity" - "Reserved Quantity";
    end;

    [IntegrationEvent(false, false)]
    local procedure  OnBeforeGetReservationQty(var IsHandled: Boolean; var ItemLedgerEntry: Record "Item Ledger Entry"; var QtyReserved: Decimal; var QtyToReserve: Decimal)
    begin

    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
