### ISSUE TITLE
Event Request Table 5741 "Transfer Line" OnBeforeGetReservationQty

### ISSUE THREAD

**Issue by AndriiBodashevskyi** [microsoft/ALAppExtensions#16907]
Hello, could you please change the code of the GetReservationQty procedure in the table 5741 like this?

    procedure GetReservationQty(var QtyReserved: Decimal; var QtyReservedBase: Decimal; var QtyToReserve: Decimal; var QtyToReserveBase: Decimal; Direction: Integer): Decimal
    var
    IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetReservationQty(IsHandled, Rec, QtyReserved, QtyReservedBase, QtyToReserve, QtyToReserveBase, Direction);
        if not IsHandled then
            if Direction = 0 then begin // Outbound
                CalcFields("Reserved Quantity Outbnd.", "Reserved Qty. Outbnd. (Base)");
                QtyReserved := "Reserved Quantity Outbnd.";
                QtyReservedBase := "Reserved Qty. Outbnd. (Base)";
                QtyToReserve := "Outstanding Quantity";
                QtyToReserveBase := "Outstanding Qty. (Base)";
            end else begin // Inbound
                CalcFields("Reserved Quantity Inbnd.", "Reserved Qty. Inbnd. (Base)");
                QtyReserved := "Reserved Quantity Inbnd.";
                QtyReservedBase := "Reserved Qty. Inbnd. (Base)";
                QtyToReserve := "Outstanding Quantity";
                QtyToReserveBase := "Outstanding Qty. (Base)";
            end;
            exit("Qty. per Unit of Measure");
        end else
            exit("Qty. per Unit of Measure");
    end;

    [IntegrationEvent(false, false)]
    local procedure  OnBeforeGetReservationQty(var IsHandled: Boolean; var TransferLine: Record "Transfer Line"; var QtyReserved: Decimal; var QtyReservedBase: Decimal; var QtyToReserve: Decimal; var QtyToReserveBase: Decimal; var Direction: Integer)
    begin

    end

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
