### ISSUE TITLE
Event Request Table 37 "Sales Line" OnBeforeGetReservationQty

### ISSUE THREAD

**Issue by AndriiBodashevskyi** [microsoft/ALAppExtensions#16903]
Hello, could you please change the code of the GetReservationQty procedure in the table 37 like this?

    procedure GetReservationQty(var QtyReserved: Decimal; var QtyReservedBase: Decimal; var QtyToReserve: Decimal; var QtyToReserveBase: Decimal): Decimal
    var
    IsHandled: Boolean; 
    begin
        IsHandled := false; 
        OnBeforeGetReservationQty(IsHandled, Rec, QtyReserved, QtyReservedBase, QtyToReserve, QtyToReserveBase);
        if not IsHandled then begin
            CalcFields("Reserved Quantity", "Reserved Qty. (Base)");
            if "Document Type" = "Document Type"::"Return Order" then begin
                "Reserved Quantity" := -"Reserved Quantity";
                "Reserved Qty. (Base)" := -"Reserved Qty. (Base)";
            end;
            QtyReserved := "Reserved Quantity";
            QtyReservedBase := "Reserved Qty. (Base)";
            QtyToReserve := "Outstanding Quantity";
            QtyToReserveBase := "Outstanding Qty. (Base)";
            exit("Qty. per Unit of Measure");
       end else
          exit("Qty. per Unit of Measure");
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetReservationQty(var IsHandled: Boolean; var SalesLine: Record "Sales Line"; var QtyReserved: Decimal; var QtyReservedBase: Decimal; var QtyToReserve: Decimal; var QtyToReserveBase: Decimal)
    begin

    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
