### ISSUE TITLE
Event Request Table 246 "Requisition Line" OnAfterFilterLinesForReservation

### ISSUE THREAD

**Issue by AndriiBodashevskyi** [microsoft/ALAppExtensions#16910]
Hello, could you please add this event at the very end of the FilterLinesForReservation procedure in the table 246?

    OnAfterFilterLinesForReservation(Rec, ReservationEntry);

    [IntegrationEvent(false, false)]
    local procedure OnAfterFilterLinesForReservation(var RequisitionLine: Record "Requisition Line"; var ReservationEntry: Record "Reservation Entry")    
    begin

    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
