### ISSUE TITLE
fieldgroups request for table 99000754 "Work Center"

### ISSUE THREAD

**Issue by RED-Lin** [microsoft/ALAppExtensions#16913]
We would like to add a fieldgroups property in table Work Center so we can extend this with our addon fields:

fieldgroups
{
fieldgroup(DropDown; "No.", Name)
{
}
}

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
