### ISSUE TITLE
Change Scope[Omprem] to Scope[Cloud] and add events for codeunit 8510 "Over-Receipt Mgt."

### ISSUE THREAD

**Issue by Easystep2** [microsoft/ALAppExtensions#16917]
I would like to allow the scope of this codeunit to be changed to Cloud, to be able to extend this functionality

Second I would like to add an event in the Onvalidate Trigger "Over-Receipt Quantity" at the Purchase Line"

if "Over-Receipt Quantity" <> 0 then
                    CheckLocationRequireReceive();

                if ("Over-Receipt Code" <> '') then begin
                    OverReceiptMgt.VerifyOverReceiptQuantity(Rec, xRec);
                    OverReceiptCode.Get("Over-Receipt Code");
                    if OverReceiptCode."Required Approval" then
                        "Over-Receipt Approval Status" := "Over-Receipt Approval Status"::Pending;
                end;

<<<<<<<----- 

              OnBeforeValidateOverReceiptQuantity(Rec, xRec, OverReceiptCode, CurrFieldNo, Handled) 

               If Not Handled then begin
                          SuspendStatusCheck(true);
                          Validate(Quantity, Quantity - xRec."Over-Receipt Quantity" + "Over-Receipt Quantity");
                          Validate("Direct Unit Cost");
               end;
-------->>>>>>>>>>>

                if "Over-Receipt Quantity" = 0 then begin
                    "Over-Receipt Approval Status" := "Over-Receipt Approval Status"::" ";
                    OverReceiptMgt.RecallOverReceiptNotification(PurchaseHeader.RecordId());
                end else
                    OverReceiptMgt.ShowOverReceiptNotificationFromLine(PurchaseHeader."No.");

[IntegrationEvent(false, false)]
local procedure  OnBeforeValidateOverReceiptQuantity(var PurchaseLine: "Purchase Line"; xPurchaseLine: "Purchase Line";OverReceiptCode : Record "Over-Receipt Code";, CurrFieldNo ; Integer; Handled : boolean) 
begin
end

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
