### ISSUE TITLE
[Fieldgroup Request] Table 5718 "Nonstock Item"

### ISSUE THREAD

**Issue by alexlang24** [microsoft/ALAppExtensions#16914]
Hi,
please add a **dropdown fieldgroup** to the **table 5718 "Nonstock Item"** that users can search directly by "Vendor Item No." and we are able to enhance it.

fieldgroups
    {
        fieldgroup(Dropdown; "Vendor Item No.", "Manufacturer Code", Description)
        {}
    }

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
