### ISSUE TITLE
[Protected var] Report 33 "Reconcile Cust. and Vend. Accs"

### ISSUE THREAD

**Issue by ampasc** [microsoft/ALAppExtensions#16926]
Could you please expose the variables "ReconCustVendBuffer", "Amount" and "AccountType" of Report 33 "Reconcile Cust. and Vend. Accs" as protected variables? This would enable us to reconcile additional G/L Accounts with this report.

```
    protected var
        ReconCustVendBuffer: Record "Reconcile CV Acc Buffer" temporary;
        Amount: Decimal;
        AccountType: Text[1024];
```

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. 
We will update this issue with information about availability. Please do not reply to this, as we do not monitor closed issues. 
If you have follow-up questions or requests, please create a new issue where you reference this one.
