### ISSUE TITLE
[Event Request] Table 137 "Inc. Doc. Attachment Overview"

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/ALAppExtensions#16927]
Please add event OnBeforeNameDrillDown(var IncDocAttachmentOverview: Record "Inc. Doc. Attachment Overview";var IsHandled: Boolean) and call from top of the function NameDrillDown(),

**Comment by gunnargestsson** [comment]
Please also increase field length

field(5; Name; Text[250])

to 

field(5; Name; Text[2048])

As we may need to handle long Urls.

**Comment by Stepanenko-Vadim** [comment]
In scope of this issue we will handle the event request, for field change please create a separate issue, those are for a separate team and they are handled separately from event requests.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
