### ISSUE TITLE
[Event Request] Table 7302 - Bin Content - OnCheckDecreaseBinContentOnAfterCalcTotalQtyAvailToTake

### ISSUE THREAD

**Issue by Jattzia1978** [microsoft/ALAppExtensions#16928]
Hi,

If possible, In Codeunit 7304 "Whse. Jnl-Register Batch", we would need this line of code BinContent.CheckDecreaseBinContent to include the WhseJnlLine variable and also be added to the OnCheckDecreaseBinContentOnAfterCalcTotalQtyAvailToTake

It is required as we are in need of changing the error message to add more information related to the warehouse journal line

Thank you

**Comment by Oleg-Romashkov** [comment]
Hi,

Function BinContent.CheckDecreaseBinContent is used by several objects including codeunit "Whse.-Activity-Register" which does not have related WhseJnlLine. 
For the Codeunit 7304 "Whse. Jnl-Register Batch" you can try to use existing event OnBeforeCreateTrackingSpecification.
