### ISSUE TITLE
Forced SourceTableView has significant performance implications

### ISSUE THREAD

**Issue by tgdoat44** [microsoft/ALAppExtensions#16936]
In many ledger entry pages, the forced setting of a key in the SourceTableView property is causing significant performance decreases. Opening a page with the wrong key takes more than a minute instead of less than one second, if the correct key is being used.

For example: in the page 29 "Vendor Ledger Entries", the sorting key is set to "Entry No.". If this page is opened from the vendor card, then the filter is applied to the vender no. and better keys are available. However, the SourceTableView property takes precedence and sorts the filtered results without considering the better secondary key, causing the significant performance impact. 

This applies to all ledger entry pages, where a SourceTableView was set, including (but not limited to): 
- page 20 "General Ledger Entries" (SORTING("G/L Account No.", "Posting Date"))
- page 25 "Customer Ledger Entries" SORTING("Entry No.")
- page 29 "Vendor Ledger Entries" SORTING("Entry No.")
- page 5604 "FA Ledger Entries" SORTING("Entry No.")

Creating a separate page without the key in the SourceTableView is not an option, because hardly any code lines that call the standard page offer an option to overwrite this behaviour. This is also not a feasible approach for such a fundamental problem in so many different pages. One "acceptable" alternative could be the possibility to overwrite the SourceTableView property in a pageextension, but even this does not seem feasibly in this case.

Please remove the unnecessary SourceTableView from these pages.

**Comment by Joneleth84** [comment]
I wholeheartedly agree - Microsoft should not "force" a key on its customers / partners. In terms of encapsulation the SourceTableView property should be made available for read/write access.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43051.
