### ISSUE TITLE
[Event Parameter Request] table 38 "Purchase Header"  - OnValidateBuyFromVendorNoOnAfterUpdateBuyFromCont

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#16948]
Could you please add the parameters `CallingFieldNo: Integer;` & `var SkipBuyFromContact: Boolean` to the event `OnValidateBuyFromVendorNoOnAfterUpdateBuyFromCont`?
```al
//OLD Signature
//-[IntegrationEvent(false, false)]
//-local procedure OnValidateBuyFromVendorNoOnAfterUpdateBuyFromCont(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader: Record "Purchase Header")
//-begin
//-end;

//NEW Signature
[IntegrationEvent(false, false)]
local procedure OnValidateBuyFromVendorNoOnAfterUpdateBuyFromCont(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader: Record "Purchase Header"; CallingFieldNo: Integer; var SkipBuyFromContact: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
