### ISSUE TITLE
[Event Request] Table 38 Purchase Header / procedure AddSpecialOrderToAddress

### ISSUE THREAD

**Issue by VolkerBoehm** [microsoft/ALAppExtensions#16946]
It would be great to have an event like: AddSpecialOrderToAddress(SalesHeader: Record "Sales Header"; ShowError: Boolean), similar to the requested event in procedure AddShipToAddress. This event would be useful for all developers that need to add new fields to the shipment address in the purchase header.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
