### ISSUE TITLE
[Parameter Request] report 1092 "Job Transfer to Credit Memo"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#16944]
Could you please change the scope to **protected** of the following variables?
```al
    var
        Job: Record Job;
        SalesHeader: Record "Sales Header";
        PostingDate: Date;
        CrMemoPostingDate: Date;
        Done: Boolean;
  protected var
        CreditMemoNo: Code[20];
        NewCreditMemo: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
