### ISSUE TITLE
Event Request Page 232 "Apply Customer Entries" OnAfterSetFilterOnBeforeSetCustEntryApplID

### ISSUE THREAD

**Issue by NadiaMelnyk** [microsoft/ALAppExtensions#16956]
Hello, could you please add event to page 232?

    local procedure SetCustEntryApplID(CurrentRec: Boolean)
        var
            IsHandled: Boolean;
        begin
            IsHandled := false;
            OnBeforeSetCustEntryApplID(Rec, CurrentRec, ApplyingAmount, ApplyingCustLedgEntry, GetAppliesToID(), IsHandled, GenJnlLine);
            if IsHandled then
                exit;

            CustLedgEntry.Copy(Rec);
            if CurrentRec then begin
                CustLedgEntry.SetRecFilter();
	            OnAfterSetFilterOnBeforeSetCustEntryApplID(CustLedgEntry, ApplyingCustLedgEntry, "Applies-to ID");
                CustEntrySetApplID.SetApplId(CustLedgEntry, ApplyingCustLedgEntry, "Applies-to ID")
            end else begin
                CurrPage.SetSelectionFilter(CustLedgEntry);
	            OnAfterSetFilterOnBeforeSetCustEntryApplID(CustLedgEntry, ApplyingCustLedgEntry, "Applies-to ID");
                CustEntrySetApplID.SetApplId(CustLedgEntry, ApplyingCustLedgEntry, GetAppliesToID)
            end;
        end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetFilterOnBeforeSetCustEntryApplID(var CustLedgEntry: Record "Cust. Ledger Entry"; ApplyingCustLedgEntry: Record "Cust. Ledger Entry"; AppliesToID: Code[50])
    begin
    end;

**Comment by Oleg-Romashkov** [comment]
Hi,

Please use existing event OnBeforeSetCustEntryApplID
