### ISSUE TITLE
Concerning #12464 - From which version is this provided? 

### ISSUE THREAD

**Issue by PFoncke** [microsoft/ALAppExtensions#16953]

**Comment by AlexanderYakunin** [comment]
This is implemented June 3, 2021; in version 19.0 and up.

trigger OnOpenPage()
    begin
        InitButtons();
        **if not FiltersInitialized then begin**
            TraceMethod := TraceMethod::"Usage->Origin";
            ShowComponents := ShowComponents::"Item-tracked Only";
        end;

        SetPackageTrackingVisibility();
    end;
