### ISSUE TITLE
[Parameter Request] page 9657 "Customer Report Selections" - OnMapTableUsageValueToPageValueOnCaseElse

### ISSUE THREAD

**Issue by SteveyN** [microsoft/ALAppExtensions#16954]
Please change the ReportUsage parameter from an Option, to Enum "Custom Report Selection Sales" on the event OnMapTableUsageValueToPageValueOnCaseElse on Page 9657 "Customer Report Selections"

```
    [IntegrationEvent(false, false)]
    // OLD
    local procedure OnMapTableUsageValueToPageValueOnCaseElse(CustomReportSelection: Record "Custom Report Selection"; var ReportUsage: Option)
    // NEW
    local procedure OnMapTableUsageValueToPageValueOnCaseElse(CustomReportSelection: Record "Custom Report Selection"; var CustomReportSelectionSales: Enum "Custom Report Selection Sales")
    begin
    end;
```

This issue is true as of 19.5

This should fix a bug where, on opening the page, the Report Usage shows as the last standard Usage Type (like Quote or Invoice), instead of being set to the custom one via this event (i.e Custom Invoice)
![image](https://user-images.githubusercontent.com/10519634/161036381-3d3a559a-dcfe-4a6c-9e35-d971b30744f4.png)
![image](https://user-images.githubusercontent.com/10519634/161036716-fa6aa782-2123-4504-bbac-3e9b5ec5205a.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
