### ISSUE TITLE
[Extensiblity / Performance Request] table 370 "Excel Buffer" ReadSheet for specific Columns

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#16964]
We are using the Excel Buffer to import large files, but often we only want to import specific columns.
We had our own solution where we skipped columns that weren't provived. 
Since performance gains more priority we could need an overload of the `ReadSheet` /`ReadSheetContinous` functions that allow us to specify a List of Column Ids (`ImportColums: List of [Integer]`) to skip not needed columns.

We would add this to our app, but DotNet isn't allowed with target=Cloud. Therefore this can only be added in the Base Application.
```al
procedure ReadSheetContinous(SheetName: Text; CloseBookOnCompletion: Boolean; ImportColums: List of [Integer])
var
    ExcelBufferDialogMgt: Codeunit "Excel Buffer Dialog Management";
    CellData: DotNet CellData;
    Enumerator: DotNet IEnumerator;
    RowCount: Integer;
    LastUpdate: DateTime;
begin
    // Allows reading Excel files with more than one sheet without closing and reopening file
    if SheetName <> '' then
        SetActiveReaderSheet(SheetName);
    LastUpdate := CurrentDateTime;
    ExcelBufferDialogMgt.Open(Text007);
    DeleteAll();

    Enumerator := XlWrkShtReader.GetEnumerator;
    RowCount := XlWrkShtReader.RowCount;
    while Enumerator.MoveNext do begin
        CellData := Enumerator.Current;
        if CellData.HasValue and ImportColums.Contains(CellData.ColumnNumber) then begin //Check for ColumNumber
            Validate("Row No.", CellData.RowNumber);
            Validate("Column No.", CellData.ColumnNumber);
            ParseCellValue(CellData.Value, CellData.Format);
            Insert;

            if not UpdateProgressDialog(ExcelBufferDialogMgt, LastUpdate, CellData.RowNumber, RowCount) then begin
                CloseBook;
                Error(Text035)
            end;
        end;
    end;

    if CloseBookOnCompletion then
        CloseBook;
    ExcelBufferDialogMgt.Close;
end;
```

Additonal we sometimes only want to read the header line of Excel Sheet.
It would improve our performance if we get a function to only read a specific line.

procedure ReadSheetLineContinous(SheetName: Text; CloseBookOnCompletion: Boolean; RowNo: Integer)
var
    ExcelBufferDialogMgt: Codeunit "Excel Buffer Dialog Management";
    CellData: DotNet CellData;
    Enumerator: DotNet IEnumerator;
    RowCount: Integer;
    LastUpdate: DateTime;
    ImportColumIds: List of [Integer];
begin
    
    // Allows reading Excel files with more than one sheet without closing and reopening file
    if SheetName <> '' then
        SetActiveReaderSheet(SheetName);
    LastUpdate := CurrentDateTime;
    ExcelBufferDialogMgt.Open(Text007);
    DeleteAll();

    Enumerator := XlWrkShtReader.GetEnumerator;
    RowCount := XlWrkShtReader.RowCount;
    while Enumerator.MoveNext do begin
        CellData := Enumerator.Current;
        if CellData.HasValue and (CellData.RowNumber = RowNo) then begin //NEW
            Validate("Row No.", CellData.RowNumber);
            Validate("Column No.", CellData.ColumnNumber);
            ParseCellValue(CellData.Value, CellData.Format);
            Insert;

            if not UpdateProgressDialog(ExcelBufferDialogMgt, LastUpdate, CellData.RowNumber, RowCount) then begin
                CloseBook;
                Error(Text035)
            end;
        end;
        //+NEW
       if CellData.RowNumber = RowNo then
          break;
       //-NEW
    end;

    if CloseBookOnCompletion then
        CloseBook;
    ExcelBufferDialogMgt.Close;
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
