### ISSUE TITLE
Event Request Page 10009 "Customer Order Header Status" OnBeforeOnAfterGetRecord

### ISSUE THREAD

**Issue by NadiaMelnyk** [microsoft/ALAppExtensions#16961]
Hello, could you please add the event to page 10009?

    trigger OnAfterGetRecord()
    begin
	    OnBeforeOnAfterGetRecord(Rec)

        GetLastShipmentInvoice;
        AfterGetCurrentRecord;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnAfterGetRecord(var SalesHeader: Record "Sales Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
