### ISSUE TITLE
[Event Request] codeunit 1261 "Imp. SEPA CAMT Bank Rec. Lines" - OnRunOnBeforeRunPostProcess or OnAfterOnRun

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#16966]
I need to access RecRef and skip RunPostProcess procedure.
But later run the RunPostProcess procedure.
There is an event in RunPostProcess with IsHandled, but as I'm going to run this procedure later I would like to skip the procedure in OnRun.
Can I get one of the following events (All parameters as reference)? The first event is preferred, but I will manage with the last one.

```
    trigger OnRun()
    var
        DataExch: Record "Data Exch.";
        ProcessDataExch: Codeunit "Process Data Exch.";
        RecRef: RecordRef;
    begin
        DataExch.Get("Data Exch. Entry No.");
        RecRef.GetTable(Rec);
        RunPreProcess(Rec);
        ProcessDataExch.ProcessAllLinesColumnMapping(DataExch, RecRef);
        // >>>>>>>>>>>>>>>>
        OnRunOnBeforeRunPostProcess(Rec, RecRef, IsHandled);
        if not IsHandled then
        // <<<<<<<<<<<<<<<<
        RunPostProcess(Rec);
        // >>>>>>>>>>>>>>>>
        OnAfterOnRun(Rec, RecRef);
        // <<<<<<<<<<<<<<<<
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
