### ISSUE TITLE
[Event Request] Codeunit "Job Calculate WIP"

### ISSUE THREAD

**Issue by ElmarFV** [microsoft/ALAppExtensions#16979]
Our client, Converge, has a mod in NAV8.0 that needs to be replicated in BC19 Cloud (their now current environment). This mod uses the Job's default dimensions and adds them to the WIP Postings. In order to be able to get this done I would need a new Integration event in the following places.

local procedure InitWIPBufferEntryFromTask(var JobTask: Record "Job Task"; var JobWIPTotal: Record "Job WIP Total"; BufferType: Enum "Job WIP Buffer Type"; WIPEntryAmount: Decimal)

before line 540
TempJobWIPBuffer[1]."Dim Combination ID" := DimMgt.CreateDimSetIDFromDimBuf(TempDimensionBuffer);

because I would need to create a new record in the TempDimensionBuffer variable and I need to know the Job No. so something like 
[IntegrationEvent(false, false)]
local procedure OnBeforeCreateDimSetIDFromDimBuf(var TempDimensionBuffer: Record "Dimension Buffer"; JobTask: Record "Job Task")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
