### ISSUE TITLE
Additional Overrides For Field of Type Media's Import Function

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/ALAppExtensions#16985]
Good overrides to have:

Import(base64: Text, description, mime)
Justification: Many APIs return data in a base64 string.
Current solution: use base 64 convert FromBase64 to outstream. Copy to instream. Call ImportStream.

Import(url: Text, description, mime)
Justification: You may have a url to the resource.
Current solution: use http client et all to download image. Get instream. Call ImportStream.

This could all be a bit simpler, would be great.
I'd write my own PR, but I don't think this is exposed, at least I didn't find it.

**Comment by JesperSchulz** [comment]
Thanks for your suggestion. The import function for fields of type Media is a platform implementation. I've forwarded your request, but normally issues in this repo are either for open source or extensibility requests. As this is platform, it doesn't fall into any of these categories. But let's see :-)

**Comment by jensmpmsft** [comment]
We will add the request to our backlog, but since workarounds do exist and we are very busy with other features, then I would not expect this to happen in the next release.
