### ISSUE TITLE
[Request for External] table 11000003 "Detail Line" - vars CustLedgEntry and VendLedgEntry 

### ISSUE THREAD

**Issue by VPaas2** [microsoft/ALAppExtensions#16983]
Request to make vars  CustLedgEntry and VendLedgEntry protected in table "Detail Line":
```
    protected var
        CustLedgEntry: Record "Cust. Ledger Entry";
        VendLedgEntry: Record "Vendor Ledger Entry";

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
