### ISSUE TITLE
[Request for External] table 11000003 "Detail Line" - GetVendorEntries

### ISSUE THREAD

**Issue by VPaas2** [microsoft/ALAppExtensions#16982]
Function from local to protected:
```
    protected procedure GetVendorEntries() OK: Boolean       
    begin
        if "Serial No. (Entry)" <> VendLedgEntry."Entry No." then begin
            OK := VendLedgEntry.Get("Serial No. (Entry)");
            VendLedgEntry.CalcFields("Remaining Amount");
        end else
            OK := true;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
