### ISSUE TITLE
[Extensibility Request] table 11307 G/L Entry Application Buffer - procedure Apply

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#16989]
Please remove scope OnPrem from procedure Apply in table 11307 "G/L Entry Application Buffer" (NL localization)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
