### ISSUE TITLE
[Request for External] table 11000003 "Detail Line" - IsDifferentSign

### ISSUE THREAD

**Issue by VPaas2** [microsoft/ALAppExtensions#16981]
Function from local to global:
```
    procedure IsDifferentSign(FirstAmount: Decimal; SecondAmount: Decimal): Boolean 
    begin
        exit(((FirstAmount < 0) and (SecondAmount > 0)) or ((FirstAmount > 0) and (SecondAmount < 0)));
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
