### ISSUE TITLE
[Event Request] report 298 "Batch Post Sales Credit Memos": Request to provide new Event OnAfterOnOpenPage

### ISSUE THREAD

**Issue by IndubhusanGiri** [microsoft/ALAppExtensions#16997]
![image](https://user-images.githubusercontent.com/85640621/161253546-d6050b4f-547d-47c4-8dd1-d97b3c194482.png)

we can have an OnAfterOnOpenPage event for the Report as below

![image](https://user-images.githubusercontent.com/85640621/161254120-e722bd6d-d508-49be-97d2-fec9a0077ee3.png)

**Comment by IndubhusanGiri** [comment]
solve the issue with the help of Codeunit "Sales Batch Post Mgt."

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
