### ISSUE TITLE
[Extensibility Request] report 1093 "Job Create Sales Invoice"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#16999]
Could you please change the variables `JobChoice` and `PostingDate` to **protected**?

```al
    var
        JobCreateInvoice: Codeunit "Job Create-Invoice";
        JobCalcBatches: Codeunit "Job Calculate Batches";
        NoOfInvoices: Integer;
        InvoicePerTask: Boolean;
        JobChoice: Option Job,"Job Task";
        OldJobNo: Code[20];
        OldJTNo: Code[20];
        Text000: Label 'A', Comment = 'A';
//+NEW
    protected var
        JobChoice: Option Job,"Job Task";
        PostingDate: Date;
//-NEW
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
