### ISSUE TITLE
Codeunit 1279 GenerateHashBytes returns an empty string for an empty InputString

### ISSUE THREAD

**Issue by BjEic** [microsoft/ALAppExtensions#16998]
Codeunit 1279 GenerateHashBytes returns an empty string for an empty InputString but muste be SHA256("") =
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.
