### ISSUE TITLE
[Event Request] report 297 "Batch Post Sales Invoices":  Add Extra parameter to existing OnAfterOnOpenPage Event

### ISSUE THREAD

**Issue by IndubhusanGiri** [microsoft/ALAppExtensions#16996]
![image](https://user-images.githubusercontent.com/85640621/161252853-12e7df0b-5b07-4b06-8aa1-bdd3ec2a03bd.png)
 
 In some scenario like to post the Sales and Credit statement we need to set the PostingDateReq as 0D. thats why it will be good if we can have that added to the parameter of OnAfterOnOpenPage event.

**Comment by IndubhusanGiri** [comment]
solved the issue with Codeunit "Sales Batch Post Mgt."

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
