### ISSUE TITLE
[EventRequest]Table 39 Purchase Line

### ISSUE THREAD

**Issue by wokw** [Microsoft/ALAppExtensions#170]
Due to Polish Localization App building, we need two publishers in Table 39. Before and after VAT amounts updating we need to handle VAT Base Amount.

Function: UpdateVATAmounts

// START
OnBeforeUpdateVATAmounts(Rec);
// STOP
GetPurchHeader;
PurchLine2.SETRANGE("Document Type","Document Type");
PurchLine2.SETRANGE("Document No.","Document No.");
PurchLine2.SETFILTER("Line No.",'<>%1',"Line No.");
...
          IF "VAT Base Amount" <> 0 THEN
            "VAT %" :=
              ROUND(100 * ("Amount Including VAT" - "VAT Base Amount") / "VAT Base Amount",0.00001)
          ELSE
            "VAT %" := 0;
        END;
    END;
END;
// START
OnAfterUpdateVATAmounts(Rec);
// STOP

Publishers signatures: LOCAL [IntegrationEvent] OnBeforeUpdateVATAmounts(VAR PurchaseLine: Record "Purchase Line")
					   LOCAL [IntegrationEvent] OnAfterUpdateVATAmounts(VAR PurchaseLine: Record "Purchase Line")

**Comment by wokw** [comment]
Hi,
thanks a lot for all publishers added for us. Could you give me some ETA for this one? It's the last one missing for our big app and we are waiting for your feedback. Is there any related issue with this request?
Thanks in advance
Wojciech

**Comment by wokw** [comment]
Hi,
it looks that this publisher is already available. Issue can be just closed.
Regards
Wojciech

**Comment by JesperSchulz** [comment]
Sorry for not replying. But glad that you got your event publishers :-) I will close this issue.
