### ISSUE TITLE
[Data Archive] Audit Fields do not get archived

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/ALAppExtensions#17009]
I tried do manually archive records before modifying them.

For Example:

```AL
local procedure UpdateItemLedgerEntries()
    var
        ItemLedgerEntry: Record "Item Ledger Entry";
        DataArchive: Codeunit "Data Archive";
    begin
        DataArchive.Create('ItemLedgerEntryMoveTables');

        ItemLedgerEntry.FilterGroup(-1);
        ItemLedgerEntry.SetFilter("TPT COGS", '<>%1', 0);
        ItemLedgerEntry.SetFilter("TPT Revenue", '<>%1', 0);
        if ItemLedgerEntry.FindSet(true, false) then
            repeat
                DataArchive.SaveRecord(ItemLedgerEntry);
                ItemLedgerEntry."COGS AHALR" := ItemLedgerEntry."TPT COGS";
                ItemLedgerEntry."Revenue AHALR" := ItemLedgerEntry."TPT Revenue";
                ItemLedgerEntry.Modify(false);
            until ItemLedgerEntry.Next() = 0;
        DataArchive.Save();
    end;
```

It seems like the audit fields `$systemId,SystemCreatedAt,SystemCreatedBy,SystemModifiedAtSystemModifiedBy` do not get included.
I checked the code which selects the fields to be included in the archive, and I do not find any hint why they should not be included.

Version: 
US Business Central 19.5 (Platform 19.0.36528.38326 + Application 19.5.36567.36634)
Data Archive | Microsoft | v. 19.5.36567.36841

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
