### ISSUE TITLE
[Event Request] codeunit 5005273 "Iss. Delivery Remind. printed" - OnRunOnBeforeModify

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17002]
CAn we please get the following event?
```al
codeunit 5005273 "Iss. Delivery Remind. printed"
{
    Permissions = TableData "Issued Deliv. Reminder Header" = rimd;
    TableNo = "Issued Deliv. Reminder Header";

    trigger OnRun()
    begin
        Find;
        "No. Printed" := "No. Printed" + 1;
        OnRunOnBeforeModify(Rec); //NEW
        Modify;
        Commit();
    end;
}
```
[IntegrationEvent(false, false)]
local procedure OnRunOnBeforeModify(var IssuedDelivReminderHeader: Record "Issued Deliv. Reminder Header")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
