### ISSUE TITLE
[EVENT REQUEST] Skip incrementing no. printed for reminder issue

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#17000]
Hello, 

we need a possibility to skip the incrementation of the field "No. Printed" in codeunit 393 "Reminder-Issue". Can we get this event?

```
    procedure IncrNoPrinted(var IssuedReminderHeader: Record "Issued Reminder Header")
    var
        IsHandled: Boolean;
    begin
        OnBeforeIncrNoPrinted(IsHandled);
        if IsHandled then
            exit;
        with IssuedReminderHeader do begin
            Find;
            "No. Printed" := "No. Printed" + 1;
            Modify;
            Commit();
        end;
    end;
```
With
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeIncrNoPrinted(var IsHandled: Boolean)
    begin
    end;
```

It would be acutally pretty helpful to have this event in all codeunits which increment the "No. Printed", but first the above mentioned event would actually be enough for us.
- "PurchCrMemo-Printed"
- "Purch.HeaderArch-Printed"
- "Purch.Header-Printed"
- "Purch. Inv.-Printed"
- "Purch.Rcpt.-Printed"
- "Return Receipt - Printed"
- "Return Shipment - Printed"
- "SalesCount-PrintedArch"
- "Sales Cr. Memo-Printed"
- "Sales Inv.-Printed"
- "Sales-Printed"
- "Sales Shpt.-Printed"
- "Service Cr. Memo-Printed"
- "Service Inv.-Printed"
- "Service-Printed"
- "Service Shpt.-Printed"
- "Whse.-Printed"

**Comment by Oleg-Romashkov** [comment]
Hi,
The majority of places where "No. Printed" are incrementing have "...OnBeforeModify" events which let you update this field if needed. The rest of objects will be updated the same way.

Rgds,
Oleg

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
