### ISSUE TITLE
[Ebent Request] OnBeforeUpdateBlanketOrder in Codeunit 5813 "Undo Purchase Receipt Line" and 5815 "Undo Sales Shipment Line"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#17003]
We need a new event trigger OnBeforeUpdateBlanketOrder  in codeunit 5813 "Undo Purchase Receipt Line" and 5815 "Undo Sales Shipment Line" (see similar Eventtriggers in codeunit 80 and 90 OnBeforeUpdateBlanketOrderLine):

codeunit 5813 "Undo Purchase Receipt Line" 
    procedure UpdateBlanketOrder(PurchRcptLine: Record "Purch. Rcpt. Line")
    var
        BlanketOrderPurchaseLine: Record "Purchase Line";
        IsHandled: Boolean;  <-- new variable
    begin
//++++++++++++++++
        IsHandled := false;
        OnBeforeUpdateBlanketOrder(var PurchRcptLine: Record "Purch. Rcpt. Line", var IsHandled);
        if IsHandled then
            exit;
//-----------------------

        with PurchRcptLine do
            if BlanketOrderPurchaseLine.Get(
                 BlanketOrderPurchaseLine."Document Type"::"Blanket Order", "Blanket Order No.", "Blanket Order Line No.")
            then begin
...
    end;

Codeunit 5815 "Undo Sales Shipment Line":
    procedure UpdateBlanketOrder(SalesShptLine: Record "Sales Shipment Line")
    var
        BlanketOrderSalesLine: Record "Sales Line";
        xBlanketOrderSalesLine: Record "Sales Line";
        IsHandled: Boolean;  <-- new variable
    begin
//++++++++++++++++
        IsHandled := false;
        OnBeforeUpdateBlanketOrder(var SalesShptLine: Record "Sales Shipment Line", var IsHandled);
        if IsHandled then
            exit;
//-----------------------

        with SalesShptLine do
            if BlanketOrderSalesLine.Get(
                 BlanketOrderSalesLine."Document Type"::"Blanket Order", "Blanket Order No.", "Blanket Order Line No.")
            then begin
...
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
