### ISSUE TITLE
[Access Request] page 599 "Payment Disc Tolerance Warning" - proteced vars for PageExtension

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17016]
Could you please change the scope fof the following variables to protected?
```al
    var
        Amount: Decimal;
        AppliedAmount: Decimal;
        BalanceAmount: Decimal;
        Posting: Option " ","Payment Tolerance Accounts","Remaining Amount";
        NewPostingAction: Integer;
        AccountName: Text;
//+Change
    protected var
        PostingDate: Date;
        CustVendNo: Code[20];
        DocNo: Code[20];
        CurrencyCode: Code[10];
//-Change
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
