### ISSUE TITLE
Faults, Resolutions etc. getting deleted, when Bill-to Customer No. is changed in Service Order

### ISSUE THREAD

**Issue by ISliceUrPanties** [microsoft/ALAppExtensions#17010]
Hello,
when changing Bill-to Customer No. in a Service Order and underlying Service Lines don't start with Line No. 10000, all Faults, Resolutions, Comments, etc. are getting lost.
Version: DE Business Central 19.5 (Platform 19.0.36528.36625 + Application 19.5.36567.36700)

Steps to reproduce the problem:
1.	Search for Services Orders
2.	Click on New
3.	Enter 30000 in Field Customer No.
4.	Under „Lines“ enter 10 in Service Item No.
5.	Click on Line -> Comments -> Faults
<img width="769" alt="image" src="https://user-images.githubusercontent.com/25838698/161507955-fdd60136-bd36-4a37-bd76-af510333e73b.png">

6.	Enter some Text in Faults. One line is enough fort he test.
7.	Close Fault Service Comment Sheet
8.	Click on Line -> Service Item Worksheet
<img width="304" alt="image" src="https://user-images.githubusercontent.com/25838698/161508116-0425faf4-4e49-4711-8205-cb5b7585865d.png">

9.	Under Lines create an new Line: Type Item, No. 80203
10.	In the upcoming Message choose „Ignore“ and accept with OK.
11.	Create a second Line: Type Item, No. 80204
12.	In the upcoming Message choose „Ignore“ and accept with OK.
13.	Delete the first Line with type Item and No. 80203
14.	Close Service Item Worksheet
15.	Under „Invoicing“ enter 40000 in Field „Bill-to Customer No.“
a.	„Do you want to change the Bill-to Customer No.?“ -> Click yes
b.	„Do you want to update the lines?“ -> Click yes
c.	„If you change Bill-to Customer No., the existing service lines will be deleted and the program will create new service lines based on the new information on the header.
Do you want to change the Bill-to Customer No.?“ -> Click yes
16.	Click on Line -> Comments -> Faults
17.	The comments created in Step 6 are deleted.

The Problem lies in procedure `RecreateServLines(ChangedFieldName: Text[100])` of Table Sales Header. All Service Comments getting transfered to a temporary table and deleted afterwards.
<img width="959" alt="image" src="https://user-images.githubusercontent.com/25838698/161508719-6f61d37f-b63f-4dee-8c6c-cfe5887de38d.png">
In procedure `CreateServiceLines(var TempServLine: Record "Service Line" temporary; var ExtendedTextAdded: Boolean; var TempServiceCommentLine: Record "Service Comment Line" temporary)` these comments should get recreated but won't when no Service Line with Line No. 10000 ist existent.
<img width="680" alt="image" src="https://user-images.githubusercontent.com/25838698/161510003-0ee3f3b5-fe8b-4081-9c65-e16fc5f84082.png">

Service comments are tied to a Service Item Line and not Service Line, so saving and recreating comments in RecreateServLines is not necessary at all.

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
