### ISSUE TITLE
[Event Request] Page 5708 "Get Shipment Lines" - New publisher

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#17019]
Hello, we need a new Event publisher in procedure SetSalesHeader. Can you please check that? Thank you!

    procedure SetSalesHeader(var SalesHeader2: Record "Sales Header")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetSalesHeader(SalesHeader2, IsHandled);
        if IsHandled then
            exit;

        SalesHeader.Get(SalesHeader2."Document Type", SalesHeader2."No.");
        SalesHeader.TestField("Document Type", SalesHeader."Document Type"::Invoice);
    end;

New Event:

    [IntegrationEvent(true, false)]
    local procedure OnBeforeSetSalesHeader(SalesHeader2: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
