### ISSUE TITLE
[Event Request] for GetAvailableScenariosForAccount function in codeunit 8892 "Email Scenario Impl." in System Application

### ISSUE THREAD

**Issue by ivandjordjevic** [microsoft/ALAppExtensions#17029]
Hi all,

We recently obsoleted some of the enum options for Email Scenarios (enum 8890 "Email Scenario") we initially added through our new Enum Extentation.

What happens now is that those options are still available to users, and the problems is that we can't hide those through extension since both table and page object used are in system app and are marked as internal.

![image](https://user-images.githubusercontent.com/20359384/161563799-bed11da1-4ec3-49be-b112-ddcd71934ed0.png)

What we probably need is a publisher in..:

codeunit 8892 "Email Scenario Impl.".GetAvailableScenariosForAccount(EmailAccount: Record "Email Account Scenario"; var EmailScenarios: Record "Email Account Scenario")

...to be able to skip some of the options from the loop and not insert them into EmailScenarios record.

![image](https://user-images.githubusercontent.com/20359384/161564872-b0ec0d4c-67d9-4c54-be8f-4f759419dc2c.png)

**Comment by Oleg-Romashkov** [comment]
Hi,

Please provide the required event signature.

Rgds,
Oleg.

**Comment by ivandjordjevic** [comment]
@Oleg-Romashkov I think this would work for us:

Publisher call:
![image](https://user-images.githubusercontent.com/20359384/162421642-0b05bae1-726b-467b-94f5-1e2d49f8e4bf.png)

Publisher signature:

````
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertAvailableScenario(CurrentScenario: Integer; var IsAvailable: Boolean);
begin
end;
````

**Comment by ivandjordjevic** [comment]
Hey @Oleg-Romashkov, can you update the label here now that the missing information is provided?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41665.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 41831.
