### ISSUE TITLE
[Event Request] Change argument GlobalVarAccess to true in standard event OnBeforeSetFilterOnItem in standard codeunit 311 "Item-Check Avail."

### ISSUE THREAD

**Issue by margolui** [microsoft/ALAppExtensions#17028]
Hello.
Need change argument GlobalVarAccess to true in standard event OnBeforeSetFilterOnItem in standard codeunit 311 "Item-Check Avail."

Version of AL Language v9.0.605172
US Business Central 19.5 (Platform 19.0.36528.37760 + Application 19.5.36567.37808)

Function:

`

      local procedure SetFilterOnItem(var Item: Record Item; ItemNo: Code[20]; ItemVariantCode: Code[10]; ItemLocationCode: Code[10]; ShipmentDate: Date)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetFilterOnItem(Item, ItemNo, ItemVariantCode, ItemLocationCode, ShipmentDate, UseOrderPromise, IsHandled);
        if IsHandled then
            exit;

        Item.Get(ItemNo);
        Item.SetRange("No.", ItemNo);
        Item.SetRange("Variant Filter", ItemVariantCode);
        Item.SetRange("Location Filter", ItemLocationCode);
        Item.SetRange("Drop Shipment Filter", false);
        if UseOrderPromise then
            Item.SetRange("Date Filter", 0D, ShipmentDate)
        else
            Item.SetRange("Date Filter", 0D, WorkDate);
    end;

`

`

    [IntegrationEvent(false, false)]
        local procedure OnBeforeSetFilterOnItem(var Item: Record Item; ItemNo: Code[20]; ItemVariantCode: Code[10]; ItemLocationCode: Code[10]; ShipmentDate: Date; UseOrderPromise: Boolean; var IsHandled: Boolean)
        begin
        end;

`

**Comment by Oleg-Romashkov** [comment]
Hi Margo,

We do not make update for events GlobalVarAccess parameter. The alternative could be moving some of global variables to protected and using them from event with IncludeSender.
If it is ok for you then please create a new request describing protected variables you need.

Rgds,
Oleg.
