### ISSUE TITLE
[Event Request] Table 288 - Vendor Bank Account - OnBeforeCheckIBAN

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#17021]
Dear ALAppExtensions team,

Through this issue we would like to request adding event publisher `OnBeforeCheckIBAN` in Table 288 `Vendor Bank Account` with the following signature:

```AL
[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckIBAN(var Rec: Record "Vendor Bank Account"; xRec: Record "Vendor Bank Account"; var v_IsHandled: Boolean)
    begin
    end;
```

which would be called as follows in `IBAN: - OnValidate`:

```AL
field(24; IBAN; Code[50])
        {
            Caption = 'IBAN';

            trigger OnValidate()
            var
                CompanyInfo: Record "Company Information";
                l_IsHandled: boolean;
            begin
                l_IsHandled := false;
                OnBeforeCheckIBAN(Rec, xRec, l_IsHandled);
                if not l_IsHandled then
                    CompanyInfo.CheckIBAN(IBAN);
            end;
        }
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
