### ISSUE TITLE
[Event Request] OnAfterCheckBeforePost in Codeunit 5856 "TransferOrder-Post Transfer"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#17036]
We need a new Event OnAfterCheckBeforePost  in Codeunit 5856 "TransferOrder-Post Transfer". Either implement TransHeader.CheckBeforePost as in codeunit 5705 "TransferOrder-Post Receipt" and 5704 "TransferOrder-Post Shipment" or new Event Trigger:

codeunit 5856 "TransferOrder-Post Transfer"
trigger OnRun()
...
OnRunOnAfterTransHeaderSetHideValidationDialog(TransHeader, Rec, HideValidationDialog);

        with TransHeader do begin
            TestField("Transfer-from Code");
            TestField("Transfer-to Code");
            TestField("Direct Transfer");
            if ("Transfer-from Code" <> '') and
               ("Transfer-from Code" = "Transfer-to Code")
            then
                Error(
                  SameLocationErr,
                  "No.", FieldCaption("Transfer-from Code"), FieldCaption("Transfer-to Code"));
            TestField("In-Transit Code", '');
            TestField(Status, Status::Released);
            TestField("Posting Date");

//++++++++++++++++++++++++++++++++
OnAfterCheckBeforePost(var TransHeader);
//-----------------------------------

            CheckDim();
...

Better as in CU5704/5705;
codeunit 5856 "TransferOrder-Post Transfer"
trigger OnRun()
        ReleaseDocument(Rec);
        TransHeader := Rec;
        TransHeader.SetHideValidationDialog(HideValidationDialog);

        OnRunOnAfterTransHeaderSetHideValidationDialog(TransHeader, Rec, HideValidationDialog);

        with TransHeader do begin
            CheckBeforePost;

            CheckDim;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
