### ISSUE TITLE
[Event Request] OnBeforeInsertDirectTransHeader in codeunit 5856 "TransferOrder-Post Transfer"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#17039]
Please add a new event trigger OnBeforeInsertDirectTransHeader in codeunit 5856 "TransferOrder-Post Transfer"

codeunit 5856 "TransferOrder-Post Transfer"
    local procedure InsertDirectTransHeader(TransferHeader: Record "Transfer Header"; var DirectTransHeader: Record "Direct Trans. Header")
    begin
...
        DirectTransHeader."No." :=
            NoSeriesMgt.GetNextNo(InvtSetup."Posted Direct Trans. Nos.", TransferHeader."Posting Date", true);
//+++++++++++++++++++++++
 OnBeforeInsertDirectTransHeader(var DirectTransHeader, TransferHeader);
//---------------------------------
        DirectTransHeader.Insert();

        OnAfterInsertDirectTransHeader(DirectTransHeader, TransferHeader);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
