### ISSUE TITLE
[Request for External] Page 7119 "Inventory Analysis Report"

### ISSUE THREAD

**Issue by nvleeuwen** [microsoft/ALAppExtensions#17031]
Dear ALAppExtensions team,

On behalve of 4PS I would like to request to make variable CurrentLineTemplate protected on page 7119 "Inventory Analysis Report"

````
protected var
    CurrentLineTemplate: Code[10];
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
