### ISSUE TITLE
[Change Request] Report 99001017 IF GUIALLOWED

### ISSUE THREAD

**Issue by LidaLidaLidaLidaLida** [microsoft/ALAppExtensions#17048]
Hello,

In the Report 99001017 there are the functions "OpenWindow", "UpdateWindow" and "CloseWindow". Please could you add:
      IF NOT GUIALLOWED THEN
          EXIT;
so that the report can be called by an individually programmed codeunit from job queue. I noticed that it is already the case in Report 699.

Thank you in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
