### ISSUE TITLE
[Event Request] OnBeforeInsertDirectTransLine in codeunit 5856 "TransferOrder-Post Transfer"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#17040]
Please add a new event trigger OnBeforeInsertDirectTransLine  in codeunit 5856 "TransferOrder-Post Transfer":

codeunit 5856 "TransferOrder-Post Transfer"
local procedure InsertDirectTransLine(DirectTransHeader: Record "Direct Trans. Header"; TransLine: Record "Transfer Line")
    begin
...
end;
//++++++++++++++++++++
 OnBeforeInsertDirectTransLine(var DirectTransLine, DirectTransHeader, TransLine);
//--------------------------
        DirectTransLine.Insert();

        OnAfterInsertDirectTransLine(DirectTransLine, DirectTransHeader, TransLine)
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
