### ISSUE TITLE
Inventory Valuation, report 1001 - request to move code from OnAfterGetRecord trigger to a procedure

### ISSUE THREAD

**Issue by stephanpl** [microsoft/ALAppExtensions#17049]
We would like to specify the Inventory Valuation report (1001) per item variant as well. In order to prevent code duplication, it would be nice to have the code that is momentarily in the OnAfterGetRecord trigger of the data-item "Item" in a separate function that could be called from a report extension. Then this procedure could be called from for the item as well for the item variants with an appropriate filter set for the "Variant Filter" field of the item record.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
