### ISSUE TITLE
Event Request Page 232 "Apply Customer Entries"  OnQueryClosePageOnEarlierPostingDateError

### ISSUE THREAD

**Issue by NadiaMelnyk** [microsoft/ALAppExtensions#17043]
Hello, could you please add event OnQueryClosePageOnEarlierPostingDateError to page 232?

    trigger OnQueryClosePage(CloseAction: Action): Boolean
        var
            RaiseError: Boolean;
        begin
            if CloseAction = ACTION::LookupOK then
                LookupOKOnPush();
            if ApplnType = ApplnType::"Applies-to Doc. No." then begin
                if OK then begin
                    RaiseError := ApplyingCustLedgEntry."Posting Date" < "Posting Date";
                    OnBeforeEarlierPostingDateError(ApplyingCustLedgEntry, Rec, RaiseError, CalcType.AsInteger());
                    OnQueryClosePageOnEarlierPostingDateError(ApplyingCustLedgEntry, Rec, RaiseError, OK);      <--------------------------
                    if RaiseError then begin
                        OK := false;
                        Error(
                          EarlierPostingDateErr, ApplyingCustLedgEntry."Document Type", ApplyingCustLedgEntry."Document No.",
                          Rec."Document Type", Rec."Document No.");
                    end;
                end;
                if OK then begin
                    if Rec."Amount to Apply" = 0 then
                        Rec."Amount to Apply" := Rec."Remaining Amount";
                    CODEUNIT.Run(CODEUNIT::"Cust. Entry-Edit", Rec);
                end;
            end;
            if (CalcType = CalcType::Direct) and not OK and not PostingDone then begin
                Rec := ApplyingCustLedgEntry;
                Rec."Applying Entry" := false;
                Rec."Applies-to ID" := '';
                Rec."Amount to Apply" := 0;
    
                OnOnQueryClosePageOnBeforeRunCustEntryEdit(Rec);
                CODEUNIT.Run(CODEUNIT::"Cust. Entry-Edit", Rec);
            end;
        end;

        [IntegrationEvent(false, false)]
        local procedure OnQueryClosePageOnEarlierPostingDateError(ApplyingCustLedgerEntry: Record "Cust. Ledger Entry"; CustLedgerEntry: Record "Cust. Ledger Entry"; var RaiseError: Boolean; var OK: Boolean)
        begin
        end;

**Comment by dnpb** [comment]
Why pass `OK`? The call is only made when it's `false`, and you pass it as non-`var`. Did you mean for it to be `var` and changeable by subscribers?

**Comment by NadiaMelnyk** [comment]
> Why pass `OK`? The call is only made when it's `false`, and you pass it as non-`var`. Did you mean for it to be `var` and changeable by subscribers?

Yes
My bad
`OK` should be `var` for changing by subscribers

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
