### ISSUE TITLE
[Event parameter request] In CU 7312 the event OnBeforeGetBinTypeFilter needs the "Type" parameter

### ISSUE THREAD

**Issue by SweconThomasH** [microsoft/ALAppExtensions#17050]
In CodeUnit 7312 "Create Pick", the event OnBeforeGetBinTypeFilter should inherit the "Type" parameter from the parent procedure GetBinTypeFilter(), without that it's almost useless.

```
procedure GetBinTypeFilter(Type: Option Receive,Ship,"Put Away",Pick,"Put Away only") BinTypeFilter: Text[1024]
var
    BinType: Record "Bin Type";
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeGetBinTypeFilter(BinTypeFilter, IsHandled);

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
