### ISSUE TITLE
[Event Request] Table 5612 - FA Depreciation Book - OnBeforeAdjustLinearMethod

### ISSUE THREAD

**Issue by Codey42** [microsoft/ALAppExtensions#17060]
Dear ALAppExtensions team,

Through this issue we would like to request adding event publisher `OnBeforeAdjustLinearMethod` in Table 5612 FA Depreciation Book with the following signature:

```AL
[IntegrationEvent(true, false)]
local procedure OnBeforeAdjustLinearMethod(var Amount1: Decimal;
                                           var Amount2: Decimal;
                                           var IsHandled: Boolean)
begin
end;
```

with `IncludeSender` set to `true`.
which would be called as follows in `AdjustLinearMethod`:

```AL
local procedure AdjustLinearMethod(var Amount1: Decimal; var Amount2: Decimal)
var
    IsHandled: Boolean;
begin
    // >>>> New >>>>>>>>>>>>>>>>
    IsHandled := false;
    OnBeforeAdjustLinearMethod(Amount1, Amount2, IsHandled);
    if IsHandled then
        exit;
    // <<<< New <<<<<<<<<<<<<<<<

    Amount1 := 0;
    Amount2 := 0;
    if "No. of Depreciation Years" = 0 then begin
        "No. of Depreciation Months" := 0;
        "Depreciation Ending Date" := 0D;
    end;
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
