### ISSUE TITLE
[Enum Request] report 7391 "Whse. Get Bin Content" DestinationType2

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17063]
Could you please change the Option DestinationType2 in report 7391 "Whse. Get Bin Content" to an enum?
```al
        DestinationType2: Option MovementWorksheet,WhseInternalPutawayHeader,ItemJournalLine,TransferHeader,InternalMovementHeader;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
