### ISSUE TITLE
[Extensibility Enhancement] table 246 "Requisition Line" Getter for global var CurrentFieldNo

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17066]
To be able to use the default OnValidateTrigger of `table 246 "Requisition Line"` we could need an getter function for the global varialbe `CurrentFieldNo`? Then we could avoid addtional events.
```al
procedure GetGlobalCurrFieldNo() : Integer
begin
    exit(CurrentFieldNo);
end;
```

Update:
Other accepted solution: Move the variable `CurrentFieldNo` to the scope **protected**.
```al
protected var
        CurrentFieldNo: Integer;
```

**Comment by AlexanderYakunin** [comment]
Can we simply move this variable to protected?

**Comment by pri-kise** [comment]
Would be okay for me, too. Didn't know what you prefer on such issues.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
