### ISSUE TITLE
[Protected var] Page 490 AccScheduleOverview

### ISSUE THREAD

**Issue by Vittorio-Panigoni** [microsoft/ALAppExtensions#17065]
In page 490 AccScheduleOverview could you change the scope of the following variables to protected?
    protected var
        AccSchedManagement: Codeunit AccSchedManagement;
        UseAmtsInAddCurr: Boolean;

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
