### ISSUE TITLE
Bug/Event Call Request - Missing Publisher Call codeunit 815 "Sales Post Invoice" - procedure PostLedgerEntry

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#17062]
With BC20 the Publisher procedure OnPostLedgerEntryOnBeforeGenJnlPostLine was set to obsolete.

The Call of this Publisher was removed in procedure PostItemLedgerEntry with BC20.

Can you please call this obsolete Publisher until the Publisher is removed in a future Version (Add the Call again in the Source Code) like you did e.g. in the Reminder Header.

Example from Reminder Header:
![image](https://user-images.githubusercontent.com/46991052/161951804-3ac9469e-fb83-484f-924f-652f5abc4e37.png)

procedure PostLedgerEntry in Codeunit 815:

Old Code before BC20:

![image](https://user-images.githubusercontent.com/46991052/161950379-a1f04fae-7532-4013-a7fd-672dce1afecd.png)

New Code in BC20:

![image](https://user-images.githubusercontent.com/46991052/161950445-425cf282-0217-4fdc-9968-806a89f546ae.png)

**Comment by AlexanderYakunin** [comment]
This approach does not work here for all events, please be VERY CAREFUL if you want to use new implementation BEFORE ver. 23. We will make new implementation standard from this point.

**Comment by AlexanderYakunin** [comment]
Here we have full replacement of old engine by new one, which will happen in v23. There are no plans to use new engine in PROD BEFORE this version. We investigated possibility to provide event mapping like in other simple places, but finally decided not doing that due to very high risks of issues in this design.

We already implemented event bridge for furure implementations, like this:

            SalesPostInvoiceEvents.RunOnPostLedgerEntryOnBeforeGenJnlPostLine(
                GenJnlLine, SalesHeader, TotalSalesLine, TotalSalesLineLCY, PreviewMode, SuppressCommit, GenJnlPostLine);
            GenJnlPostLine.RunWithCheck(GenJnlLine);
            SalesPostInvoiceEvents.RunOnPostLedgerEntryOnAfterGenJnlPostLine(
                GenJnlLine, SalesHeader, TotalSalesLine, TotalSalesLineLCY, PreviewMode, SuppressCommit, GenJnlPostLine);
