### ISSUE TITLE
[Event Request] codeunit 432 Consolidate - OnBeforeRun

### ISSUE THREAD

**Issue by Vittorio-Panigoni** [microsoft/ALAppExtensions#17074]
In codeunit 432 Consolidate please add the following event:

```al
    trigger OnRun()
    var
        PreviousDate: Date;
        i: Integer;
    begin
        // New event
        OnBeforeRun(Rec);
        // New event
        BusUnit := Rec;
        if NormalDate(EndingDate) - NormalDate(StartingDate) + 1 > ArrayLen(RoundingResiduals) then
```

```al
    [IntegrationEvent(true, false)]
    local procedure OnBeforeRun(var BusUnit: Record "Business Unit")
    begin
    end;
```

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
