### ISSUE TITLE
[Enum Request] table 12174 "Customer Bill Header" - field Type

### ISSUE THREAD

**Issue by Vittorio-Panigoni** [microsoft/ALAppExtensions#17078]
In table 12174 "Customer Bill Header" please transform field 15 - Type in an enum.

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
