### ISSUE TITLE
[Bug] codeunit 6620 "Copy Document Mgt." - CopyDocLines

### ISSUE THREAD

**Issue by Vittorio-Panigoni** [microsoft/ALAppExtensions#17076]
For me the signature of the procedure CopyDocLines is wrong because procedure changes ToPurchLine, not FromPurchLine, and you can have problems after the procedure call because the record could be different.

actual:
```al
local procedure CopyDocLines(RecalculateAmount: Boolean; ToPurchLine: Record "Purchase Line"; var FromPurchLine: Record "Purchase Line")
```
correct
```al
local procedure CopyDocLines(RecalculateAmount: Boolean; var ToPurchLine: Record "Purchase Line"; FromPurchLine: Record "Purchase Line")
```

Thank you

**Comment by dnpb** [comment]
I believe now they won't be able to remove `var` from the parameter that shouldn't have it, in case someone already receives it by `var` (even if they don't intend to modify it, e.g. via the event finder). However, it should be OK to _add_ `var` to the one missing it.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
