### ISSUE TITLE
[Event Request] Table 5645 - FA Date Type - OnAfterCreateTypes

### ISSUE THREAD

**Issue by Codey42** [microsoft/ALAppExtensions#17071]
Dear ALAppExtensions team,

Through this issue we would like to request adding event publisher `OnAfterCreateTypes` in Table 5645 FA Date Type with the following signature:

```AL
[IntegrationEvent(true, false)]
local procedure OnAfterCreateTypes()
begin
end;
```

with `IncludeSender` set to `true`.
which would be called as follows in `CreateTypes`:

```AL
procedure CreateTypes()
var
    FADeprBook: Record "FA Depreciation Book";
begin
    ...

    // >>>> New >>>>>>>>>>>>>>>>
    OnAfterCreateTypes();
    // <<<< New <<<<<<<<<<<<<<<<
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
