### ISSUE TITLE
[Event Request] Codeunit 99000854 - Inventory Profile Offsetting -OnBeforeSumSupplyInventory

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#1708]
Hello AL-Team,
 please add the following Publisher in function "PlanItem":

LOCAL PlanItem(VAR DemandInvtProfile : Record "Inventory Profile";VAR SupplyInvtProfile : Record "Inventory Profile";PlanningStartDate : Date;ToDate : Date;RespectPlanningParm : Boolean)

[ … ]
      // Calculate initial inventory
      PlanItemCalcInitialInventory(
        DemandInvtProfile,SupplyInvtProfile,PlanningStartDate,DemandExists,SupplyExists,LastProjectedInventory);

      OnBeforePrePlanDateDemandProc(SupplyInvtProfile,DemandInvtProfile,SupplyExists,DemandExists);
      WHILE DemandExists DO BEGIN
        LastProjectedInventory -= DemandInvtProfile."Remaining Quantity (Base)";
        LastAvailableInventory -= DemandInvtProfile."Untracked Quantity";
        DemandInvtProfile."Untracked Quantity" := 0;
        DemandInvtProfile.MODIFY;
        DemandExists := DemandInvtProfile.NEXT <> 0;
      END;

      OnBeforePrePlanDateSupplyProc(SupplyInvtProfile,DemandInvtProfile,SupplyExists,DemandExists);
      WHILE SupplyExists DO BEGIN

        // >> New
        ISHandled := FALE;
        OnBeforeSumSupplyInventory(SupplyInvtProfile,IsHandled);
        IF NOT IsHandled THEN BEGIN
        // << New

          LastProjectedInventory += SupplyInvtProfile."Remaining Quantity (Base)";
          LastAvailableInventory += SupplyInvtProfile."Untracked Quantity";

        // >> New
        END;
        // << New

        SupplyInvtProfile."Planning Flexibility" := SupplyInvtProfile."Planning Flexibility"::None;
        SupplyInvtProfile.MODIFY;
        SupplyExists := SupplyInvtProfile.NEXT <> 0;
      END;
      OnAfterPrePlanDateSupplyProc(SupplyInvtProfile,DemandInvtProfile,SupplyExists,DemandExists);
[ … ]

Publisher definition currently used by us
 IncludeSender: false
 GlobaVarAccess: false
LOCAL [IntegrationEvent] OnBeforeSumSupplyInventory(SupplyInvtProfile : Record "Inventory Profile";VAR IsHandled : Boolean)

**Comment by NKarolak** [comment]
Note: Already added in BC Insider as OnPlanItemOnBeforeSumSupplyInvtProfile
