### ISSUE TITLE
[Function Expose] codeunit 22 "Item Jnl.-Post Line" - TouchEntry

### ISSUE THREAD

**Issue by Vittorio-Panigoni** [microsoft/ALAppExtensions#17088]
In codeunit 22 "Item Jnl.-Post Line" please change the visibility of the procedure TouchEntry to global.

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
