### ISSUE TITLE
[Function Expose] codeunit 6529 "Item Tracking Navigate Mgt." - SearchValueEntries

### ISSUE THREAD

**Issue by Vittorio-Panigoni** [microsoft/ALAppExtensions#17090]
In codeunit 6529 "Item Tracking Navigate Mgt." please change the visibility of the procedure SearchValueEntries to global.

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
