### ISSUE TITLE
[FunctionVisibilityRequest]Page 403 Purchase Order Statistics

### ISSUE THREAD

**Issue by wokw** [Microsoft/ALAppExtensions#171]
Due to Polish Localization App building, we need one function in Page 403 to be external. OnAssistEdit for the new field requires to call UpdateVATOnPurchLines function.

Function: UpdateVATOnPurchLines

Current function signature: LOCAL UpdateVATOnPurchLines()

Requested function signature: [External] UpdateVATOnPurchLines()

**Comment by darjoo** [comment]
Hi, we have accepted your request. Thanks! You'll see it in the next minor release. Congrat's on helping the extension development community!
