### ISSUE TITLE
[Enum Request] Table 5615 FA Allocation: Allocation Type Option to Enum

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/ALAppExtensions#17109]
Can you please convert the Field 8 "Allocation Type" from a Option to an extensible Enum?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
