### ISSUE TITLE
[Event Request] Page 5097("Create Task") - OnAfterFinishPage

### ISSUE THREAD

**Issue by AnkithShah** [microsoft/ALAppExtensions#17105]
Hi,

Can you please provide an event in page 5097 - "Create Task" as below.

```
local procedure FinishPage()
    begin
        CurrPage.AttendeeSubform.PAGE.GetAttendee(AttendeeTemp);
        SetAttendee(AttendeeTemp);

        CheckStatus;
        FinishWizard(false);
        OnAfterFinishPage(Rec); //NewEvent
    end;
```

New Event:

```
[IntegrationEvent(true, false)]
    local procedure OnAfterFinishPage(var Task: Record "To-do")
    begin
    end;
```

In our solution we have some customization to add notes on closing the page. Please request you to provide Event subscriber.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
