### ISSUE TITLE
Leverage the base bc wysiwyg html editor?

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/ALAppExtensions#17102]
The newer email functionality has an html wysiwyg editor. I would like to re-use that on another page without needing to reinvent this wheel. There are plenty of examples out there, but in my opinion it's better to use the base when possible.

I'm referring to this page: https://github.com/microsoft/ALAppExtensions/blob/2cf3c3f8395aa2cda684513b738f69fedca3fe91/Modules/System/Email/src/Email/Outbox/EmailEditor.Page.al

The magic isn't in that file, so I suspect there's a page extension or some other magic inserting a control addin? It would be great if there was some way for me to leverage that.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by mjmatthiesen** [comment]
> seems like a dupe of #15040
> 
> see also [experience.dynamics.com/ideas/idea/?ideaid=6497fbae-cc6b-e911-b047-0003ff688f46](https://experience.dynamics.com/ideas/idea/?ideaid=6497fbae-cc6b-e911-b047-0003ff688f46)

Same question yes. Didn't find that issue when searching. It's been about six months, so maybe the status has changed though.

**Comment by JesperSchulz** [comment]
I'm afraid we're still not able to release the rich-text editor as a standalone control :-( Please use one of the many alternatives out there. I cannot give an ETA when we'll be able to release it (if ever), or if we'll be forced to use a different editor internally and externally, to make it happen.
