### ISSUE TITLE
Increase length of "Description 2" on Table "Fixed Asset" from 50 to 100

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/ALAppExtensions#17114]
The length of the fields "Description" and "Search Description" on the Table 5600 "Fixed Asset" was increased from 50 to 100. Can you make the same change to the field "Description 2"?
Thank you.

**Comment by RadoArvay** [comment]
It is out-of-structure proposal, I think. Why? Description/Name/Address was increased in order to not use Description/xx/yy 2 in a whole system.

**Comment by AlexanderYakunin** [comment]
We cannot change field length; this is breaking change.
