### ISSUE TITLE
[Bug] table 39 "Purchase Line" - CheckApplToItemLedgEntry

### ISSUE THREAD

**Issue by Vittorio-Panigoni** [microsoft/ALAppExtensions#17116]
I think that in table 39 "Purchase Line" procedure CheckApplToItemLedgEntry there's a missing check:

```al
    local procedure CheckApplToItemLedgEntry(): Code[10]
    var
        ItemLedgEntry: Record "Item Ledger Entry";
        ApplyRec: Record "Item Application Entry";
        ReturnedQty: Decimal;
        RemainingtobeReturnedQty: Decimal;
    begin
        if "Appl.-to Item Entry" = 0 then
            exit;

        if "Receipt No." <> '' then
            exit;
        // Missing check
        if "Return Shipment No." <> '' then
            exit;
        // Missing check

        TestField(Type, Type::Item);
        TestField(Quantity);
        if Signed(Quantity) > 0 then
            TestField("Prod. Order No.", '');
        if IsCreditDocType() then begin
```

Thank you

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
