### ISSUE TITLE
[Enum Request] 5637 "FA G/L Posting Buffer" Field "FA Allocation Type" from Option to Enum

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/ALAppExtensions#17120]
Enum Request #17109 would cause overflow if it isn't implemented in Table 5637 "FA G/L Posting Buffer". The overflow would occur in Codeunit `5601 "FA Insert G/L Account"` on line `FAGLPostBuf."FA Allocation Type" := "Allocation Type";`.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
