### ISSUE TITLE
[EventRequest] Codeunit 5056 CustCont-Update - OnBeforeInsertContBusRel

### ISSUE THREAD

**Issue by EmmyCegeka** [microsoft/ALAppExtensions#17125]
Hello,

In procedure InsertNewContact in codeunit 5056 CustCont-Update there is already an event OnBeforeContactInsert in the with do block where the contact record is inserted.
We would like to request a similar event (OnBeforeContBusRelInsert) inside the with do block where Contact Business Relation is inserted inside the same procedure so we can also update the information on this record before the insert when necessary.

How it would look in procedure InsertNewContact (inserted on line 131 in the codeunit):

```
with ContBusRel do begin
     Init;
     "Contact No." := Cont."No.";
     "Business Relation Code" := RMSetup."Bus. Rel. Code for Customers";
     "Link to Table" := "Link to Table"::Customer;
     "No." := Cust."No.";
     OnBeforeContBusRelInsert(ContBusRel, Cont, Cust); 
     Insert(true);
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeContBusRelInsert(var ContactBusinessRelation: Record "Contact Business Relation"; Contact: Record Contact; Customer: Record Customer)
begin
end;
```

Thank you in advance for your consideration.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
