### ISSUE TITLE
[Bug] table 23 Vendor - GetTDDAddr

### ISSUE THREAD

**Issue by Vittorio-Panigoni** [microsoft/ALAppExtensions#17133]
Please in table 23 Vendor procedure GetTDDAddr add this check:

```al
    procedure GetTDDAddr(VendorNo: Code[20]; var AddrArray: array[8] of Text[100])
    var
        FormatAddr: Codeunit "Format Address";
    begin
        if Get(VendorNo) then begin
            FormatAddr.FormatAddr(
              AddrArray, Name, '', '', Address, '',
              City, "Post Code", '', "Country/Region Code");
            // New check
            if Rec."VAT Registration No." <> '' then
            // New check
                AddrArray[8] := FieldCaption("VAT Registration No.") + ':' + "VAT Registration No.";
        end;
        CompressArray(AddrArray);
    end;
```

Thank you

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
