### ISSUE TITLE
[Request for external] Codeunit 1201 - ProcessDataExch.Codeunit.al - SetDateDecimalField - Make global

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#17146]
Hi

Can you please make procedure SetDateDecimalField in Codeunit 1201 - ProcessDataExch.Codeunit.al global?

```
// >>>>>>>>>>
//local procedure SetDateDecimalField(ValueText: Text; var DataExchField: Record "Data Exch. Field"; var FieldRef: FieldRef; var DataExchColumnDef: Record "Data Exch. Column Def")
procedure SetDateDecimalField(ValueText: Text; var DataExchField: Record "Data Exch. Field"; var FieldRef: FieldRef; var DataExchColumnDef: Record "Data Exch. Column Def")
// <<<<<<<<<<
```

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
