### ISSUE TITLE
[Accessibility Request] Table 36 Sales Header HideCreditCheckDialogue

### ISSUE THREAD

**Issue by JerryTyssen** [microsoft/ALAppExtensions#17143]
Hello,

Currently, the global variable "HideCreditCheckDialogue" in Table 36 Sales Header is inaccessible due to its protection level.

I need the following 2 functions added to be able to access it: (just like the functions for "HideValidationDialog")

```
procedure SetHideCreditCheckDialogue(NewHideCreditCheckDialogue: Boolean)
begin
    HideCreditCheckDialogue := NewHideCreditCheckDialogue;
end;

procedure GetHideCreditCheckDialogue(): Boolean
begin
    exit(HideCreditCheckDialogue);
end;
```

Thanks in advance,
Jerry Tyssen
Cegeka

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
