### ISSUE TITLE
[Access Request] page 5709 "Get Receipt Lines" - DocumentNoHideValue

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17144]
Could you please change the access scope of the varialbe `DocumentNoHideValue` and `PurchHeader` to **protected** ?

```al
var    PurchRcptHeader: Record "Purch. Rcpt. Header";
    TempPurchRcptLine: Record "Purch. Rcpt. Line" temporary;
    GetReceipts: Codeunit "Purch.-Get Receipt";
    VendorOrderNo: Code[35];
    VendorShptNo: Code[35];
    OrderNo: Code[20];
    ItemReferenceNo: Code[50];
//+Change
protected var
    PurchHeader: Record "Purchase Header";
    [InDataSet]
    DocumentNoHideValue: Boolean;
//-Change
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
