### ISSUE TITLE
[Request for External] codeunit 7301 "Whse. Jnl.-Register Line" - InsertToBinContent

### ISSUE THREAD

**Issue by Vittorio-Panigoni** [microsoft/ALAppExtensions#17142]
Please in codeunit 7301 "Whse. Jnl.-Register Line" change the procedure InsertToBinContent from local to global, because is always possible to duplicate code to insert a record in the bin content, but you can't call the standard events that are in it.

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
