### ISSUE TITLE
[Event Request] Depreciation Book: Convert IndexGLIntegration to a more extensible procedure

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/ALAppExtensions#17150]
This Event Request is going to be a more complex one.
On the Table Depreciation Book, there is a Procedure "IndexGLIntegration".
This Procedure accepts a Boolean Array with the length of 9. We have extended the enum, and would like to add custom options here.
By implementing this, we don't have to request and implement a event for each reference, plus if two different Apps would implement this via IsHandled, they would likely conflict.
Can you refactor the Code so only one Event is required? See my Example below:
On the table i'd suggest something like this:

```diff --git a/src/DepreciationBook.Table.al b/src/DepreciationBook.Table.al
index 7336d8e..24b2a49 100644
--- a/src/DepreciationBook.Table.al
+++ b/src/DepreciationBook.Table.al
@@ -348,5 +348,23 @@ table 5611 "Depreciation Book"
         GLIntegration[8] := "G/L Integration - Maintenance";
         GLIntegration[9] := false; // Salvage Value
     end;
+
+    procedure GetGLIntegrationIndex(PostingTypeIndex: Integer): Boolean
+    var
+        GLIntegration: array[9] of Boolean;
+        CustomIsTrue: Boolean;
+    begin
+        If PostingTypeIndex <= 9 then begin
+            IndexGLIntegration(GLIntegration);
+            exit(GLIntegration[PostingTypeIndex + 1]);
+        end else
+            GLEntriesIndexOutOfBounds(PostingTypeIndex, CustomIsTrue);
+        exit(CustomIsTrue);
+    end;
+
+    [IntegrationEvent(false, false)]
+    local procedure GLEntriesIndexOutOfBounds(PostingTypeIndex: Integer, var CustomIsTrue: Boolean)
+    begin
+    end;
 }
```
then for each implementation something like this:
```diff --git a/src/CancelFALedgerEntries.Codeunit.al b/src/CancelFALedgerEntries.Codeunit.al
index f121848..594e219 100644
--- a/src/CancelFALedgerEntries.Codeunit.al
+++ b/src/CancelFALedgerEntries.Codeunit.al
@@ -50,7 +50,7 @@ codeunit 5624 "Cancel FA Ledger Entries"
                     IsHandled := false;
                     OnTransferLineOnBeforeInsertJnlLine(FALedgEntry, BalAccount, FA."Budgeted Asset", IsHandled);
                     if not IsHandled then
-                        if GLIntegration[ConvertPostingType + 1] and not FA."Budgeted Asset" then
+                        if DeprBook.GetGLIntegrationIndex(ConvertPostingType()) and not FA."Budgeted Asset" then
                             InsertGenJnlLine(FALedgEntry, BalAccount)
                         else
                             InsertFAJnlLine(FALedgEntry);```

**Comment by matthias-planzer** [comment]
Can you please tell me when this will be implemented as this request is rather central for our project.

**Comment by matthias-planzer** [comment]
I don't intend to push you but we would be very thankful for a update. 
If this won't be implemented in the next few months, we will have to find another solution.
@Oleg-Romashkov

**Comment by Oleg-Romashkov** [comment]
Hi matthias-planzer,

This request is in our queue. However, extensibility enhancements are published with major updates. So, this one should be available on October 2022 release.

Rgds,
Oleg.

**Comment by matthias-planzer** [comment]
I'm tagging @AlexanderYakunin now, because I'm not sure if Oleg is working for Microsoft anymore.
Unfortunately, it seems like this didn't make it into the BC21 release.

**Comment by AndersLarsenMicrosoft** [comment]
old request closed for now
