### ISSUE TITLE
[Scope Change] Codeunit 12184 "Fattura Doc. Helper" Procedure CheckMandatoryFields

### ISSUE THREAD

**Issue by clembo67** [microsoft/ALAppExtensions#17157]
Please remove the scope OnPrem for procedure **CheckMandatoryFields** in **Codeunit 12184**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
