### ISSUE TITLE
[Event Request] table 99000829 "Planning Component" - OnBeforeShowReservation

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17152]
procedure ShowReservation()
    var
        IsHandled: Boolean;
    begin
        //A200F0008.Event19.05.ns
        IsHandled := false;
        OnBeforeShowReservation(Rec, IsHandled);
        if IsHandled then
            exit;
        //A200F0008.Event19.05.ne

        TestField("Item No.");

    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowReservation(var PlanningComponent: Record "Planning Component"; var IsHandled: Boolean)
    begin
        //A200F0008.Event19.05
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by Duizy1971** [comment]
Thanks for the implementation of this issue in 21.00. One question though:
The local variable IsHandled is not tagged with 'var'. It does compile but is that the way we all want or is it a compiler issue?

    procedure ShowReservation()
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeShowReservation(Rec, IsHandled);
        if IsHandled then
            exit;

        TestField("Item No.");
        Clear(Reservation);
        Reservation.SetReservSource(Rec);
        Reservation.RunModal();
    end;

**Comment by JesperSchulz** [comment]
We usually don't follow up on closed issues. If further changes are required, please create a new issue going forward.
@AlexanderYakunin, could you look into this case?
