### ISSUE TITLE
Barcode is not available on the report lay-out

### ISSUE THREAD

**Issue by rwe12345** [microsoft/ALAppExtensions#17158]
I want to add a barcode to a report. This barcode will only be shown when I send the report to Word. When I try to send the report to pdf (or preview), the barcode is not available.

I created a new report, based on the example of Microsoft (https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-add-barcodes?tabs=1d). The report is added, see below.

For this report I created a rdlc lay-out and a Word lay-out.

The created RDLC lay-out:
![image](https://user-images.githubusercontent.com/44321194/162222794-d6ed8275-7c19-4173-952a-312124fa6ee7.png)

If I run the report and select the preview of the report, the barcode wasn’t printed:
![image](https://user-images.githubusercontent.com/44321194/162222917-8be916c9-4b9c-46a7-8a6d-2b2696f1b5a1.png)
I’ve got the same result when I try to send the result of this report to pdf.

If I run the report and select send the to Word, the barcode was correct printed:
![image](https://user-images.githubusercontent.com/44321194/162222980-0e6759e1-fdd1-4706-aa4c-9fc771c261a9.png)

I’ve got the same result when I use the Word lay-out.

Report code:
[Rep.ItemBarcodeReport1D.zip](https://github.com/microsoft/ALAppExtensions/files/8443807/Rep.ItemBarcodeReport1D.zip)

Report lay-outs:
[ItemBarcodes.zip](https://github.com/microsoft/ALAppExtensions/files/8443723/ItemBarcodes.zip)

**Comment by StanPesotskiy** [comment]
Thank you for reaching out. Your request could be reporting a product bug not related to the AL **application** extensibility. Please reach out to the relevant support channels:
- For collaboration in preview or beta versions of AL Language in Visual Studio Code (aka ModernDev), use GitHub (https://github.com/microsoft/al).
- For Microsoft partners, for versions already in general availability and supported, file requests through Microsoft Partnersource (https://mbs.microsoft.com/partnersource/).
- For ISVs/VARs who have discovered a bug in a in preview or beta version, use MS Collaborate (https://docs.microsoft.com/en-us/collaborate/).
- For Business Central customers who have issues or found bugs, please contact your Microsoft partner.
- For the new features please submit a product suggestion on https://aka.ms/bcideas
