### ISSUE TITLE
[Event Request] table 246 "Requisition Line" - OnBeforeShowReservation

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17151]
procedure ShowReservation()
    var
        ReservationPage: Page Reservation;
        IsHandled: Boolean;
    begin
        //A200F0008.Event19.05.ns
        IsHandled := false;
        OnBeforeShowReservation(Rec, IsHandled);
        if IsHandled then
            exit;
        //A200F0008.Event19.05.ne

        TestField(Type, Type::Item);

    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowReservation(var RequisitionLine: Record "Requisition Line"; var IsHandled: Boolean)
    begin
        //A200F0008.Event19.05
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
