### ISSUE TITLE
[Event Request] Service Line table procedure CopyFromCost

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#17175]
Existing code:

local procedure CopyFromCost()
    var
        ServCost: Record "Service Cost";
        GLAcc: Record "G/L Account";
        ConfirmManagement: Codeunit "Confirm Management";
    begin
        ServCost.Get("No.");
        if ServCost."Cost Type" = ServCost."Cost Type"::Travel then
            if ServHeader."Service Zone Code" <> ServCost."Service Zone Code" then
                if not HideCostWarning then
                    if not ConfirmManagement.GetResponseOrDefault(
                         StrSubstNo(
                           Text004, ServCost.TableCaption, "No.",
                           ServCost.FieldCaption("Service Zone Code"),
                           ServHeader.FieldCaption("Service Zone Code"),
                           ServHeader.TableCaption, ServHeader."No."), true)
                    then
                        Error(Text005);
        Description := ServCost.Description;
        Validate("Unit Cost (LCY)", ServCost."Default Unit Cost");
...
...
...

Please add an event

local procedure CopyFromCost()
    var
        ServCost: Record "Service Cost";
        GLAcc: Record "G/L Account";
        ConfirmManagement: Codeunit "Confirm Management";
    begin
        ServCost.Get("No."); 
****  OnBeforeAssignServCostValues(Rec,ServCost,HideCostWarning,IsHandled);
        if (Not IsHandled) and (ServCost."Cost Type" = ServCost."Cost Type"::Travel) then
            if ServHeader."Service Zone Code" <> ServCost."Service Zone Code" then
                if not HideCostWarning then
                    if not ConfirmManagement.GetResponseOrDefault(
                         StrSubstNo(
                           Text004, ServCost.TableCaption, "No.",
                           ServCost.FieldCaption("Service Zone Code"),
                           ServHeader.FieldCaption("Service Zone Code"),
                           ServHeader.TableCaption, ServHeader."No."), true)
                    then
                        Error(Text005);
        Description := ServCost.Description;
        Validate("Unit Cost (LCY)", ServCost."Default Unit Cost");

where
[IntegrationEvent(true, false)]
local procedure OnBeforeAssignServCostValues(var ServiceLine: Record "Service Line"; ServiceCost : Record "Service Cost"; HideCostWarning: Boolean; var IsHandled: Boolean) 
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
