### ISSUE TITLE
[Event Request] [Application “Tests-Bank”](), [Codeunit ]()132561 "Test Bank Account Tables"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#17183]
[Event Request]Application “Tests-Bank”, Codeunit 132561 "Test Bank Account Tables"

Could you please insert the OnTestInitialize Event at the beginning of each Test procedure:
![pic1](https://user-images.githubusercontent.com/45795262/162700378-e09d403c-7008-498a-998e-2159a15e19b1.png)

**Comment by Stepanenko-Vadim** [comment]
From the code I assume that you ask for missing oninitialize events in "ERM Bank Reconciliation" codeunit, not "Test Bank Account Tables" (which you already have requested in other work item...

**Comment by ttaeufer** [comment]
Yes that was my mistake.
Should I create a new work item or is this also possible?


Freundliche Grüße / Best regards


i.A. Thomas Täufer
Produktmanager

KUMAVISION AG
Oberfischbach 3, 88677 Markdorf, Germany
Tel:      +49 7544 966-223
Fax:     +49 7544 966-101
Mobil:  +49 171 7668287
E-Mail  ***@***.******@***.***>
http://www.kumavision.com

Von: Vadim Stepanenko ***@***.***>
Gesendet: Donnerstag, 14. April 2022 11:52
An: microsoft/ALAppExtensions ***@***.***>
Cc: Täufer, Thomas ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/ALAppExtensions] [Event Request] [Application “Tests-Bank”](), [Codeunit ]()132561 "Test Bank Account Tables" (Issue #17183)


From the code I assume that you ask for missing oninitialize events in "ERM Bank Reconciliation" codeunit, not "Test Bank Account Tables" (which you already have requested in other work item...

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FALAppExtensions%2Fissues%2F17183%23issuecomment-1098955056&data=04%7C01%7C%7Cf8d520786f95461688d308da1dfc75d2%7Cb2abceea6c5b40ddbf270288f8f30f2c%7C0%7C0%7C637855267391387114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tAD6VBm9TVE1ljrTxT9R2rLmQ1CBLM5gK3rtPkMskWk%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAK5MPPULRWAOC5W5U26YZFTVE7TE7ANCNFSM5TCOUCQA&data=04%7C01%7C%7Cf8d520786f95461688d308da1dfc75d2%7Cb2abceea6c5b40ddbf270288f8f30f2c%7C0%7C0%7C637855267391387114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=44XDNr%2FXTa8z%2FPza3OS3IBHbsUPDVoejb7pdC5Hz5h0%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>





Hauptsitz: KUMAVISION AG • Oberfischbach 3 • 88677 Markdorf • www.kumavision.com<https://kumavision.com/>

Amtsgericht Freiburg • HRB 581134 • Vorstand: Kay von Wilcken (Vorsitzender), Helmut Rabanser • AR-Vorsitzender: Dr.-Ing. Roy Walter

Wir nehmen den Schutz Ihrer persönlichen Daten sehr ernst. Erfahren Sie mehr darüber, wie wir mit Ihren personenbezogenen Daten umgehen: Informationspflichten<https://kumavision.com/informationspflichten> | We do take the protection of your personal data very seriously. Read more here: Information Obligation<https://kumavision.com/processing-of-customer-prospects-supplier-data>

Bitte beachten Sie auch unsere Allgemeinen Geschäftsbedingungen: AGB<https://kumavision.com/images/kumavision/impressum/agb-kumavision-ag-de.pdf> | Please also note our general terms and conditions: GTC<https://kumavision.com/images/kumavision/impressum/agb-kumavision-ag-en.pdf>

**Comment by Stepanenko-Vadim** [comment]
No need for new item, I will handle this in scope of this one :)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
