### ISSUE TITLE
[Extensibility Enhancement] Page 343 - Check Credit Limit - SetDeltaAmount

### ISSUE THREAD

**Issue by MCHammerTNP** [microsoft/ALAppExtensions#17185]
At present although the user can write code against the many OnBeforeXXXShowWarning events, none of these expose the global variable DeltaAmount.  The net result is that it is not possible to set this value externally before calling the procedure ShowWarning.

Can we therefore add a new function to Set the value of the variable from external code

```
procedure SetDeltaAmount(DeltaAmt: decimal)
begin
     DeltaAmount := DeltaAmt;
end;

```
Alternatively could we add a DeltaAmount parameter to the ShowWarning Function;

```
ShowWarning(NewCustNo: Code[20]; NewOrderAmountLCY2: Decimal; OldOrderAmountLCY2: Decimal; CheckOverDueBalance: Boolean; NewDeltaAmount2: Decimal) Result: Boolean
    var
        CustCheckCrLimit: Codeunit "Cust-Check Cr. Limit";
        ExitValue: Integer;
        IsHandled: Boolean;
    begin
        DeltaAmount := NewDeltaAmount2;  //NEW CODE
        IsHandled := false;
        OnBeforeShowWarning(Rec, NewOrderAmountLCY, OldOrderAmountLCY, OrderAmountTotalLCY, ShippedRetRcdNotIndLCY, CustCreditAmountLCY, DeltaAmount, CheckOverDueBalance, Heading, Result, IsHandled, NotificationId);
        if IsHandled then
            exit(Result);

```

**Comment by AlexanderYakunin** [comment]
Please use protected variable, it is available

**Comment by MCHammerTNP** [comment]
Hi Dannoe

Many thanks for the prompt response.  This has worked a treat.  Thank you.

Rgds
 ​​
Michael Clarendon
Senior Consultant
***@***.***
+442083289818
***@***.***
07436 144708

[Facebook]<https://www.facebook.com/thenavpeople>
[LinkedIn]<https://www.linkedin.com/company/the-nav-365-people>
[Twitter]<https://www.twitter.com/TheNAVPeople>
[YouTube]<https://www.youtube.com/channel/UC4D1Fxl_SwyFX7abeIjaI-A>
Disclaimer: www.the365people.com/disclaimer<https://the365people.com/disclaimer>
***@***.***
Cyber Essentials Plus<https://www.cyberessentials.ncsc.gov.uk/about>
