### ISSUE TITLE
[Event Request] [Application “Tests-Cash Flow”](), [Codeunit ]()139315 "CF Forecast Wizard Tests"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#17182]
[Event Request]Application “Tests-Cash Flow”, Codeunit 139315 "CF Forecast Wizard Tests"

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/162700110-29392764-d004-4900-adde-828b2a5153ff.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
