### ISSUE TITLE
[Event Request] [Application “Tests-Bank”](), [Codeunit ]()132561 "Test Bank Account Tables"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#17184]
[Event Request]Application “Tests-Bank”, Codeunit 132561 "Test Bank Account Tables"

Could you please insert the OnTestInitialize Event at the beginning of each Test procedure:
![pic1](https://user-images.githubusercontent.com/45795262/162700827-bbbbe5b2-5e17-403f-934e-97ff3238fc24.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
