### ISSUE TITLE
[Event Request] Codeunit 99000854 - Inventory Profile Offsetting - OnBeforePlanStepSettingOnStartOver

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#1719]
Hello AL-Team,
 please update the Publisher OnBeforePlanStepSettingOnStartOver in function "PlanItem" with the 2 parameters "NextState" and "IsHandled":

LOCAL PlanItem(VAR DemandInvtProfile : Record "Inventory Profile";VAR SupplyInvtProfile : Record "Inventory Profile";PlanningStartDate : Date;ToDate : Date;RespectPlanningParm : Boolean)

[ … ]
      WHILE PlanThisSKU DO
        CASE NextState OF
          NextState::StartOver:
            BEGIN
              IF DemandExists AND (DemandInvtProfile."Source Type" = DATABASE::"Transfer Line") THEN
                WHILE CancelTransfer(SupplyInvtProfile,DemandInvtProfile,DemandExists) DO
                  DemandExists := DemandInvtProfile.NEXT <> 0;

              // >> Update
              // OnBeforePlanStepSettingOnStartOver(SupplyInvtProfile,DemandInvtProfile,SupplyExists,DemandExists);
              IsHandled := FALSE;
              OnBeforePlanStepSettingOnStartOver(SupplyInvtProfile,DemandInvtProfile,SupplyExists,DemandExists,NextState,IsHandled);
              IF NOT IsHandled THEN BEGIN
              // << Update

                IF DemandExists THEN
                  IF DemandInvtProfile."Untracked Quantity" = 0 THEN
                    NextState := NextState::CloseDemand
                  ELSE
                     IF SupplyExists THEN
                       NextState := NextState::MatchDates
                     ELSE
                        NextState := NextState::CreateSupply
                ELSE
                  IF SupplyExists THEN
                    NextState := NextState::ReduceSupply
                  ELSE
                    NextState := NextState::CloseLoop;
              // >> New
              END;
              // << New
            END;
          NextState::MatchDates:

[ … ]

Publisher definition currently used by us
 IncludeSender: false
 GlobaVarAccess: false
LOCAL [IntegrationEvent] OnBeforePlanStepSettingOnStartOver(VAR SupplyInventoryProfile : Record "Inventory Profile";VAR DemandInventoryProfile : Record "Inventory Profile";VAR SupplyExists : Boolean;VAR DemandExists : Boolean;VAR NextState : 'StartOver,MatchDates,MatchQty,CreateSupply,ReduceSupply,CloseDemand,CloseSupply,CloseLoop';VAR IsHandled : Boolean)

**Comment by NKarolak** [comment]
Note: added as
`LOCAL PROCEDURE OnBeforePlanStepSettingOnStartOver@146(VAR SupplyInventoryProfile@1002 : Record 99000853;VAR DemandInventoryProfile@1001 : Record 99000853;VAR SupplyExists@1000 : Boolean;VAR DemandExists@1003 : Boolean;VAR NextState@1004 : Option;VAR IsHandled@1005 : Boolean);`

Hence the NextState option values have been skipped.
