### ISSUE TITLE
[Extensibility Enhancement] Report 1302 - "Standard Sales - Pro Forma Inv"

### ISSUE THREAD

**Issue by rkirsten** [microsoft/ALAppExtensions#17194]
In the OnPreDataItem trigger, a filter sets the line type to "Item". Therefore, printing a proforma invoice including lines with comments, item charges or G/L accounts neglected.

 Could you please alter subsequent code in the OnAfterGetRecord trigger in a way, that at least comments (line.type::" ") could be printed, too?

```
trigger OnAfterGetRecord()
var
  Location: Record Location;
  AutoFormatType: Enum "Auto Format";
begin
  Item.Get("No.");
  OnBeforeLineOnAfterGetRecord(Header, Line);

  ...
end;
```
to

```
trigger OnAfterGetRecord()
var
  Location: Record Location;
  AutoFormatType: Enum "Auto Format";
begin
  if not Item.Get("No.") then
    exit;
  OnBeforeLineOnAfterGetRecord(Header, Line);

  ...
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
