### ISSUE TITLE
[Event Request] table 7321 "Warehouse Shipment Line" - OnAfterSetSourceFilterForWhseShptLine

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17205]
Could you please add the following event in the `table 7321 "Warehouse Shipment Line" `?

```al
procedure SetSourceFilter(SourceType: Integer; SourceSubType: Option; SourceNo: Code[20]; SourceLineNo: Integer; SetKey: Boolean)
begin
    if SetKey then
        SetCurrentKey("Source Type", "Source Subtype", "Source No.", "Source Line No.");
    SetRange("Source Type", SourceType);
    if SourceSubType >= 0 then
        SetRange("Source Subtype", SourceSubType);
    SetRange("Source No.", SourceNo);
    if SourceLineNo >= 0 then
        SetRange("Source Line No.", SourceLineNo);
end;
OnAfterSetSourceFilter(Rec, SourceType, SourceSubType, SourceNo, SourceLineNo, SetKey); //NEW
```
```al
[IntegrationEvent(false, false)]
local procedure OnAfterSetSourceFilter(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; SourceType: Integer; SourceSubType: Option; SourceNo: Code[20]; SourceLineNo: Integer; SetKey: Boolean)
begin
end;
```

Alternativly you coud call the procedure `SetSourceFilterForWhseShptLine` in the `codeunit 5775 "Whse. Management"`. There would be already an event.

**Comment by Stepanenko-Vadim** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
