### ISSUE TITLE
EventRequests Job Table for Obsoleted functions

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#17208]
Hey, 

you obsoleted the procedure UpdateCust() and it's events in table 167 Job and "replaced [it] with BillToCustomerNoUpdated and SellToCustomerNoUpdated". 

But the new functionality doesn't have events we could subscribe to. Please fix as soon as possible, this is a breaking change! 

Thanks in advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.
