### ISSUE TITLE
[EnumRequest] Report 99001020 "Carry Out Action Msg. - Plan."

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#17201]
W asked for change option to extensible enums. It was in https://github.com/microsoft/ALAppExtensions/issues/15044. Problem is that enums are not extensible as we asked. Please change it.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.
