### ISSUE TITLE
event request - report 120 "Aged Accounts Receivable" - TempCustLedgEntryLoop - OnTempCustLedgEntryOnAfterSetDetailedEntryFilters()

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#17207]
We have a client who needs to exclude Detailed Entries whose Posting Date is after the EndingDate option, even in Aging By Due or Document Date modes. The simplest way to achieve this without having to copy and paste the report, would appear to be to filter the `DetailedCustomerLedgerEntry` set to exclude entries with such `Posting Date`s and bypass the subsequent normal checks.

Thus please can you add an event, wherein we can add a filter on the `Posting Date`?

Thanks!

So it would be declared as
```al
[IntegrationEvent(false, false)]
local procedure OnTempCustLedgEntryOnAfterSetDetailedEntryFilters(var DetailedCustLedgEntry: Record "Detailed Cust. Ledg. Entry")
```

and called as
```al
                        trigger OnAfterGetRecord()
                        [...]
                            CustLedgEntryEndingDate := TempCustLedgEntry;

                            DetailedCustomerLedgerEntry.SetRange("Cust. Ledger Entry No.", CustLedgEntryEndingDate."Entry No.");
			    OnTempCustLedgEntryOnAfterSetDetailedEntryFilters(DetailedCustomerLedgerEntry); // NEW

                            if DetailedCustomerLedgerEntry.FindSet(false, false) then
                            [...]
```

**Comment by Stepanenko-Vadim** [comment]
The name will be **OnTempCustLedgEntryGetRecordOnAfterSetDetailedEntryFilters**

**Comment by dnpb** [comment]
Sure, is better than mine as it's more specific, thanks for considering it!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
