### ISSUE TITLE
Extend NL report 11405 "Submit Elec. Tax Declaration"

### ISSUE THREAD

**Issue by Wildrik** [microsoft/ALAppExtensions#17202]
Please remove OnPrem-scope from SetGenerateSubmissionMessageOnly() in report 11405 of the NL localization. We would like to able to generate the message without submitting it in our cloud solution.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
