### ISSUE TITLE
 table 5945 "Troubleshooting Setup" - Field 1 "Type" to Enum 

### ISSUE THREAD

**Issue by wgross92** [microsoft/ALAppExtensions#17215]
In table 5945 "Troubleshooting Setup" please transform field 1 "Type" in an enum.

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
