### ISSUE TITLE
[Event Request] Add property UnitOfMeasureCode in event OnBeforeSetFilterOnItem in standard codeunit 311 "Item-Check Avail."

### ISSUE THREAD

**Issue by margolui** [microsoft/ALAppExtensions#17219]
Hello.
Need to add property UnitOfMeasureCode in event OnBeforeSetFilterOnItem in standard codeunit 311 "Item-Check Avail."

The version of AL Language v9.0.605172
US Business Central 19.5 (Platform 19.0.36528.37760 + Application 19.5.36567.37808)

Function:
first time
`
        
        local procedure SetFilterOnItem(var Item: Record Item; ItemNo: Code[20]; ItemVariantCode: Code[10]; ItemLocationCode:                         Code[10]; ShipmentDate: Date; ])
        var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetFilterOnItem(Item, ItemNo, ItemVariantCode, ItemLocationCode, ShipmentDate, UseOrderPromise, IsHandled, UnitOfMeasureCode);
        if IsHandled then
            exit;
        Item.Get(ItemNo);
        Item.SetRange("No.", ItemNo);
        Item.SetRange("Variant Filter", ItemVariantCode);
        Item.SetRange("Location Filter", ItemLocationCode);
        Item.SetRange("Drop Shipment Filter", false);
        if UseOrderPromise then
            Item.SetRange("Date Filter", 0D, ShipmentDate)
        else
            Item.SetRange("Date Filter", 0D, WorkDate);
    end;
`
second time
`
[IntegrationEvent(false, false)]
    local procedure OnBeforeSetFilterOnItem(var Item: Record Item; ItemNo: Code[20]; ItemVariantCode: Code[10]; ItemLocationCode: Code[10]; ShipmentDate: Date; UseOrderPromise: Boolean; var IsHandled: Boolean; UnitOfMeasureCode: Code[10])
    begin
    end;
`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
