### ISSUE TITLE
[Request for External] Report 211 "Customer - Payment Receipt"

### ISSUE THREAD

**Issue by alinat2022** [microsoft/ALAppExtensions#17210]
Hello,

We are creating a report extension for report 211 "Customer - Payment Receipt". In our version of the report, we need to also display another field from CompanyInfo - CompanyInfo.IBAN. At this moment, the variable CompanyInfo is not reachable from the report extension. Can you please make it protected?
Thank you.

```
    protected var
        CompanyInfo: Record "Company Information";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
