### ISSUE TITLE
[al-language]: use of InDataset-attribute on pages variables

### ISSUE THREAD

**Issue by wtouw** [microsoft/ALAppExtensions#17213]
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/attributes/devenv-indataset-attribute

It is not clear to us if InDataset-attribute should be used on pages. If we do not use it, we do not see any different behavior? Can someone explain why it should be used and what can go wrong if you do not used it?

**Comment by dnpb** [comment]
This repo is for issues relating to extensibility, not the core language or compiler itself. There is a repo for the latter, but it's not for general support questions either. Yammer is probably more on-topic.

But still! What have you tried? Was it this?
> You must define this attribute on a variable if it is used as the value of the [Editable Property](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-editable-property), [Enabled Property](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-enabled-property), [Visible Property](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-visible-property) and [StyleExpr Property](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/properties/devenv-styleexpr-property).

Does this documentation disagree with what you've observed? If so, use the button shown below on the documentation page, to file a bug at the correct repo.

Make sure to identify which versions of BC you've tested it against and include the code you used. I believe the above used to be the case, but it might refer to older versions of BC or NAV. If so, MS can update the docs to reflect that, but they need to be informed of what they've missed.

![image](https://user-images.githubusercontent.com/63455896/163128745-01a9be22-f6d5-4692-a18b-112da8861605.png)

**Comment by wtouw** [comment]
Hi dnpb,

thank you for you reaction.

I also posted this on Yammer: https://www.yammer.com/dynamicsnavdev/threads/1692379172651008
