### ISSUE TITLE
[Event Request] Page 9658 "Vendor Report Selections" same as in 9657 "Customer Report Selections"

### ISSUE THREAD

**Issue by dNsl9r** [microsoft/ALAppExtensions#17228]
In Page 9657 "Customer Report Selections" three Events for custom Usage Types where added longer ago:

- OnMapTableUsageToPageValueOnCaseElse
- OnValidateUsage2OnCaseElse
- OnAfterFilterCustomerUsageReportSelections

These events are a good way for us to enhance the Usage Types with our own values.
In the page 9658 "Vendor Report Selections" these events are not available, so we can not add our own values "the easy way".

Please add the events, as existing for customers, for vendors too. If there is any possible context in other pages I'm pretty sure you know better than I do and should be able to add these events, if missing, as well 👍

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
