### ISSUE TITLE
[Event Change Request] Codeunit 12 Gen. Jnl.-Post Line

### ISSUE THREAD

**Issue by nixpt82** [microsoft/ALAppExtensions#17224]
Hi like to request the same logic applied to the "PostVend" function be replicated in the "PostCust" function

PostVend Function: 

![image](https://user-images.githubusercontent.com/35833855/163158232-c8345d59-5238-4228-89b6-90e4aa61856a.png)

![image](https://user-images.githubusercontent.com/35833855/163158354-f701cfcc-e10e-408c-9348-cac05fac853a.png)

PostCust Function:

![image](https://user-images.githubusercontent.com/35833855/163158434-50a6c406-75b0-4cec-9d17-5f93f150331d.png)

Reason is not possible to user the next event since the receible accounts is missing creates a error. 
The event similar to the OnAfterGetVendorPostingGroup isnt missing for the customer function.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
