### ISSUE TITLE
[Request for External] table 37 "Sales Line" - InitQtyToAsm

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#17221]
Can you remove protected from procedure InitQtyToAsm?

I need to run all procedures that is ran in procedure InitQty.
Because of a customizations to override quantity this will not cause this statement to be true
`
if (xRec.Quantity <> Quantity) or (xRec."Quantity (Base)" <> "Quantity (Base)") then begin
`
So i need to run the procedures by using event OnBeforeInitQty 

An alternative is to move this code to its own procedure.
```
            InitOutstanding();
            if IsCreditDocType() then
                InitQtyToReceive()
            else
                InitQtyToShip();
            InitQtyToAsm();
            SetDefaultQuantity();
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
