### ISSUE TITLE
[Event Request] report 722 "Phys. Inventory List"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17227]
Can we please get the following event?
```al
procedure Initialize(ShowQtyCalculated2: Boolean)
begin
    ShowQtyCalculated := ShowQtyCalculated2;
    OnAfterInitialize(ShowQtyCalculated); //NEW
end;
```

```al
[IntegrationEvent(true, false)]
local procedure OnAfterInitialize(ShowQtyCalculated: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
