### ISSUE TITLE
[Event Request] Codeunit 99000854 - Inventory Profile Offsetting - OnBeforeMaintainProjectedInv

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#1722]
Hello AL-Team,
 please add the following Publisher in function "MaintainProjectedInv":

LOCAL MaintainProjectedInv(VAR InvChangeReminder : Record "Inventory Profile";AtDate : Date;VAR LastProjectedInventory : Decimal;VAR LatestBucketStartDate : Date;VAR ROPHasBeenCrossed : Boolean)
// Updates information about projected inventory up until AtDate or until reorder point is crossed.
// The check is performed within time buckets.
// >> New
IsHandled := FALSE;
OnBeforeMaintainProjectedInv(InvChangeReminder,AtDate,LastProjectedInventory,LatestBucketStartDate,ROPHasBeenCrossed,IsHandled);
IF IsHandled THEN 
  EXIT;
// << New

ROPHasBeenCrossed := FALSE;
LatestBucketStartDate := FindNextBucketStartDate(InvChangeReminder,AtDate,LatestBucketStartDate);
NextBucketEndDate := LatestBucketStartDate + BucketSizeInDays - 1;
[ … ]

Publisher definition currently used by us
 IncludeSender: false
 GlobaVarAccess: false
LOCAL [IntegrationEvent] OnBeforeMaintainProjectedInv(VAR InvChangeReminder : Record "Inventory Profile";AtDate : Date;VAR LastProjectedInventory : Decimal;VAR LatestBucketStartDate : Date;VAR ROPHasBeenCrossed : Boolean;VAR IsHandled : Boolean)

**Comment by NKarolak** [comment]
Note: added in BC Insider as 
```
OnBeforeMaintainProjectedInventory(
  TempReminderInvtProfile,AtDate,LastProjectedInventory,LatestBucketStartDate,ROPHasBeenCrossed,IsHandled);
```
