### ISSUE TITLE
Set FieldGroups on base tables

### ISSUE THREAD

**Issue by dzakojc** [microsoft/ALAppExtensions#17235]
Hi,
Please add FieldGroups to standard tables Archive tables
T5107 - Sales Header Archive, T5109 - Purchase Header Archive and all related tables - T5108 - Sales Line Archive, T5110 - Purchase Line Archive 

We need to add fieldgroups and brick on all Documents Archived tables, so that users will be able to clearly identify the document displayed on the tiles of the page lists. This is needed so that users can use the BC inside Outlook and on the go, using BC application on Android and iOS. 

And, it must be supported that fieldgroups, and bricks can be added to the base tables via the tableextension objects. My customers do not understand when I say to them, that sorry, it's not possible.

Thank you
BR Damjan

**Comment by AlexanderYakunin** [comment]
Please specify which fields do you need per each table

**Comment by dzakojc** [comment]
Hi 

> Please specify which fields do you need per each table

Please see below:
T5107 - Sales Header Archive -> "No.","Version No.","Sell-to Customer Name"
T5108 - Sales Line Archive -> "Document No.","Line No.","Version No.","Sell-to Customer No."
T5109 - Purchase Header Archive -> "No.","Buy From Vendor Name","Version No."
T5110 - Purchase Line Archive -> "Document No.","Line No.","Version No.","Buy From Vendor No."

Thank you
BR Damjan

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
