### ISSUE TITLE
Tables 110, 114 - new event OnBeforeSendProfile

### ISSUE THREAD

**Issue by rgrygoryshchak** [Microsoft/ALAppExtensions#1723]
Hi,

   Could you please add new event OnBeforeSendProfile to tables:
        110 'Sales Shipment Header',
        114 'Sales Cr.Memo Header'
   similar to table 112 'Sales Invoice Header' to make code consistent?

`LOCAL [IntegrationEvent] OnBeforeSendProfile(ReportSelections : Record "Report Selections";SalesInvoiceHeader : Record "Sales Invoice Header";DocTxt : Text;VAR IsHandled : Boolean)
`

   **'Sales Invoice Header' code:**

```
[External] SendProfile(VAR DocumentSendingProfile : Record "Document Sending Profile")
IsHandled := FALSE;
OnBeforeSendProfile(DummyReportSelections,Rec,DocTxt,IsHandled);
IF NOT IsHandled THEN
  DocumentSendingProfile.Send(
    DummyReportSelections.Usage::"S.Invoice",Rec,"No.","Bill-to Customer No.",
    DocTxt,FIELDNO("Bill-to Customer No."),FIELDNO("No."));

```

**'Sales Shipment Header' code:**

```
[External] SendProfile(VAR DocumentSendingProfile : Record "Document Sending Profile")
DocumentSendingProfile.Send(
  DummyReportSelections.Usage::"S.Shipment",Rec,"No.","Sell-to Customer No.",
  DocTxt,FIELDNO("Sell-to Customer No."),FIELDNO("No."));

```
Regards, Roman.

**Comment by AlexanderYakunin** [comment]
Already implemented
