### ISSUE TITLE
[Event Request] New events for batch posting processing

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#17237]
Hi Microsoft AL Development Team,

The current batch posting implementation in the Base Application enforces users to batch post without letting them choose the posting options like the normal posting process.

For extensibility, could you please add the following integration events to allow override Receive/Ship and Invoice parameters for batch posting on sales & purchase documents?

## Pages

This integration event should be added to following pages.

![image](https://user-images.githubusercontent.com/69611495/163339907-7eed4f21-e6bf-4c1d-991f-3dce4e90c7c7.png)

### Page 9307 "Purchase Order List"

![image](https://user-images.githubusercontent.com/69611495/163339475-ffab3540-1c4a-425a-82eb-af74bd64eee7.png)

### Page 9311 "Purchase Return Order List"

![image](https://user-images.githubusercontent.com/69611495/163339570-cf443a7f-eeb2-46e3-b51f-27f740d2cda7.png)

### Page 9305 "Sales Order List"

![image](https://user-images.githubusercontent.com/69611495/163339624-c13ebf1d-7718-47a9-999e-8657132b84c1.png)

### Page 9304 "Sales Return Order List"

![image](https://user-images.githubusercontent.com/69611495/163339693-a5143fbf-636e-4677-afd5-06cb66e3367e.png)

### Report 496 "Batch Post Purchase Orders"

**New event**
![image](https://user-images.githubusercontent.com/69611495/163340985-16a9e972-5832-4e5d-98cf-e51a530fa190.png)

**Placement in the report**
![image](https://user-images.githubusercontent.com/69611495/163340905-58373269-6541-424a-bc9b-448ff6768eab.png)

### Report 6655 "Batch Post Sales Return Orders"

**New event**
![image](https://user-images.githubusercontent.com/69611495/163340985-16a9e972-5832-4e5d-98cf-e51a530fa190.png)

**Placement in the report**
![image](https://user-images.githubusercontent.com/69611495/163341032-758ab4ae-0313-413f-949c-2ac8bb0e56e6.png)

### Report 6665 "Batch Post Purch. Ret. Orders"

**These events should be added onto this report**
![image](https://user-images.githubusercontent.com/69611495/163341204-1d9e84e1-5e85-4b79-87f0-64ba558593c1.png)

**Event 1 placement in the report** 
![image](https://user-images.githubusercontent.com/69611495/163341164-1588bfc1-bf72-4469-a7d3-826d7fc6a8df.png)

**Event 2 placement in the report**
![image](https://user-images.githubusercontent.com/69611495/163341127-a089e9ef-e03d-46e4-8c9a-3b64332d372c.png)

Kind regards,
Tuan Nguyen

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
