### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnCopyPurchInvHeaderToDocOnBeforeCheckInsertDocNoLine

### ISSUE THREAD

**Issue by merfai1** [microsoft/ALAppExtensions#17234]
Hi.
Recently we have requested event request #16938.
Unfortunately, the suggested **OnBeforeInsertOldPurchDocNoLine**  event cannot be used in our case, because we need the **FromPurchInvHeader** parameter to cover our logic.
As far, as we see similar event **OnCopyPurchRcptLinesToDocOnBeforeCheckInsertDocNoLine** was already added for the **CopyPurchRcptLinesToDoc** procedure.
Therefore, would it be possible to add the requested event for **CopyPurchInvLinesToDoc** procedure as well (the signature of the requested event can be found in the related event request)?

Many thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
