### ISSUE TITLE
[EventRequest] Add parameter Invoice to OnAfterHandlePurchaseLine in codeunit 5763 "Whse.-Post Shipment"

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#17241]
Hello, please add the parameter Invoice to the following event in the "Whse.-Post Shipment" codeunit, 

Current signature:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterHandlePurchaseLine(var WhseShipmentLine: Record "Warehouse Shipment Line"; PurchHeader: Record "Purchase Header")
    begin
    end;
```

Proposed signature:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterHandlePurchaseLine(var WhseShipmentLine: Record "Warehouse Shipment Line"; PurchHeader: Record "Purchase Header"; var Invoice: Boolean)
    begin
    end;
```

The `var` is probably not necessary, but you added it in the twin event for the Sales Line that was requested in #14943.

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
