### ISSUE TITLE
[EventRequest] Codeunit 11000001 "Financial Interface Telebank" - OnBeforeInitializeGJLine

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#17243]
Hello,

We would need an event OnBeforeInitializeGJLine in the function "Initialize GJLine":

    [Scope('OnPrem')]
    procedure "Initialize GJLine"(var GenJnlLine: Record "Gen. Journal Line")
    begin
        OnBeforeInitializeGJLine(GenJnlLine, "Journal template"); // <<NEW EVENT>>
        if GenJnlLine.Find('+') then
            GenJnlLine."Line No." := GenJnlLine."Line No." + 1
        else
            GenJnlLine."Line No." := 1;
        GenJnlLine.Init();
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitializeGJLine(var GenJnlLine: Record "Gen. Journal Line"; JournalTemplate: Record "Gen. Journal Template")
    begin
    end;

We need this event, because we need to apply a certain filter on the GenJnlLine variable before doing the GenJnlLine.Find('+').

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
