### ISSUE TITLE
[EventRequest] Table 81 "Gen. Journal Line".SetUpNewLine

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#17242]
Please change parameter when you call event OnSetUpNewLineOnBeforeSetDocumentNo, OnSetUpNewLineOnBeforeIncrDocNo, OnSetUpNewLineOnBeforeSetBalAccount and OnBeforeSetUpNewLine.

You send there "GenJnlLine", but we need "Rec". Because when we change something in events nothing happens in new created record.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
