### ISSUE TITLE
[EventRequest] Codeunit 11000001 "Financial Interface Telebank" - OnProcessGLJLOnBeforeGenJnlLineInsert

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#17244]
Hello,

We would need an event OnProcessGLJLOnBeforeGenJnlLineInsert in the function ProcessGLJL:

```
    [Scope('OnPrem')]
    procedure ProcessGLJL(var GenJnlLine: Record "Gen. Journal Line")
    var
        IsHandled: Boolean;
    begin
// <<START NEW EVENT
        IsHandled := false;
        OnProcessGLJLOnBeforeGenJnlLineInsert(GenJnlPostLine, GenJnlLine, IsHandled);
        if IsHandled then
            exit;
// >> END NEW EVENT
        GenJnlLine.Insert();
        // GenJnlPostLineCu.RUN(FDBR);
    end;
```

    [IntegrationEvent(false, false)]
    local procedure OnProcessGLJLOnBeforeGenJnlLineInsert(var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; var GenJnlLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
    begin
    end;

We have a certain development that needs to be executed when this function ProcessGLJL is called. That's why we need this event with IsHandled pattern.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
