### ISSUE TITLE
[EventRequest] Codeunit 11000001 "Financial Interface Telebank" - OnPostPaymReceivedOnBeforeProcessGLJL

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#17245]
Hello,

We would need an event OnPostPaymReceivedOnBeforeProcessGLJL in the function PostPaymReceived:

    [Scope('OnPrem')]
    procedure PostPaymReceived(var GenJnlLine: Record "Gen. Journal Line"; var PaymentHistLine: Record "Payment History Line"; var PaymentHist: Record "Payment History")
    begin
        PaymentHistLine.TestField(Status, PaymentHistLine.Status::New);
        BankAcc.Get(PaymentHistLine."Our Bank");
        BankAccPostingGrp.Get(BankAcc."Bank Acc. Posting Group");
        BankAccPostingGrp.TestField("Acc.No. Pmt./Rcpt. in Process");
        TrMode.Get(PaymentHistLine."Account Type", PaymentHistLine."Transaction Mode");

        TrMode.TestField("Acc. No. Pmt./Rcpt. in Process");
        TrMode.TestField("Posting No. Series");
        TrMode.TestField("Source Code");

        "New Document No." := '';
        NewPostingDate := Today;
        NoSeriesManagement.InitSeries(TrMode."Posting No. Series",
          '',
          NewPostingDate,
          "New Document No.",
          NewSeriesCode);

        "Initialize GJLine"(GenJnlLine);
        GenJnlLine.Validate("System-Created Entry", true);
        GenJnlLine.Validate("Document No.", "New Document No.");
        GenJnlLine.Validate("Posting Date", NewPostingDate);
        GenJnlLine.Validate("Account Type", GenJnlLine."Account Type"::"G/L Account");
        GenJnlLine.Validate("Account No.", TrMode."Acc. No. Pmt./Rcpt. in Process");
        PaymentHistLine."Amount Paymt. in Process (LCY)" := Round(CurrencyExchangeRate.ExchangeAmtFCYToFCY(
              NewPostingDate,
              PaymentHistLine."Currency Code",
              '',
              PaymentHistLine.Amount));
        GenJnlLine.Validate(Amount, PaymentHistLine."Amount Paymt. in Process (LCY)");
        if PaymentHistLine."Description 1" <> '' then
            GenJnlLine.Validate(Description, PaymentHistLine."Description 1");
        GenJnlLine.Validate("Source Code", TrMode."Source Code");

        GenJnlLine."Shortcut Dimension 1 Code" := PaymentHistLine."Global Dimension 1 Code";
        GenJnlLine."Shortcut Dimension 2 Code" := PaymentHistLine."Global Dimension 2 Code";
        GenJnlLine."Dimension Set ID" := PaymentHistLine."Dimension Set ID";
        ProcessGLJL(GenJnlLine);

        "Initialize GJLine"(GenJnlLine);
        GenJnlLine.Validate("System-Created Entry", true);
        GenJnlLine.Validate("Document No.", "New Document No.");
        GenJnlLine.Validate("Posting Date", NewPostingDate);
        GenJnlLine.Validate("Account Type", GenJnlLine."Bal. Account Type"::"G/L Account");
        GenJnlLine.Validate("Account No.", BankAccPostingGrp."Acc.No. Pmt./Rcpt. in Process");
        GenJnlLine.Validate(Amount, -PaymentHistLine."Amount Paymt. in Process (LCY)");
        if PaymentHistLine."Description 1" <> '' then
            GenJnlLine.Validate(Description, PaymentHistLine."Description 1");
        GenJnlLine.Validate("Source Code", TrMode."Source Code");
        GenJnlLine."Shortcut Dimension 1 Code" := PaymentHistLine."Global Dimension 1 Code";
        GenJnlLine."Shortcut Dimension 2 Code" := PaymentHistLine."Global Dimension 2 Code";
        GenJnlLine."Dimension Set ID" := PaymentHist."Dimension Set ID";
        OnPostPaymReceivedOnBeforeProcessGLJL(GenJnlLine, PaymentHistLine); **// <<NEW EVENT>>**
        ProcessGLJL(GenJnlLine);

        PaymentHistLine."Document No." := "New Document No.";
        PaymentHistLine."Posting Date" := NewPostingDate;
        PaymentHistLine.Modify();
    end; 

    [IntegrationEvent(false, false)]
    local procedure OnPostPaymReceivedOnBeforeProcessGLJL(var GenJnlLine: Record "Gen. Journal Line"; PaymentHistLine: Record "Payment History Line")
    begin
    end;

We need this event, so we could update some fields on GenJnlLine from PaymentHistLine.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
