### ISSUE TITLE
Table 137 "Inc. Doc. Attachment Overview", Increase field length

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/ALAppExtensions#17258]
field(5; Name; Text[250])

to

field(5; Name; Text[2048])

As we may need to handle long Urls.

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot extend existing field. We can replace old field with new longer one.

**Comment by AlexanderYakunin** [comment]
If we need URL field in this table, please create new request.
