### ISSUE TITLE
Table 114 - Sales Cr.Memo Header - new events OnBeforeSendRecords, OnBeforePrintRecords, OnBeforeEmailRecords

### ISSUE THREAD

**Issue by rgrygoryshchak** [Microsoft/ALAppExtensions#1725]
Hi,

   Could you please add next events to table 114 'Sales Cr.Memo Header' in order to match table 112 'Sales Invoice Header':

`LOCAL [IntegrationEvent] OnBeforeEmailRecords(ReportSelections : Record "Report Selections";SalesCrMemoHeader : Record "Sales Cr.Memo Header";DocTxt : Text;ShowDialog : Boolean;VAR IsHandled : Boolean)
`

`LOCAL [IntegrationEvent] OnBeforePrintRecords(ReportSelections : Record "Report Selections";SalesCrMemoHeader : Record "Sales Cr.Memo Header";ShowRequestPage : Boolean;VAR IsHandled : Boolean)
`

`LOCAL [IntegrationEvent] OnBeforeSendRecords(ReportSelections : Record "Report Selections";SalesCrMemoHeader : Record "Sales Cr.Memo Header";DocTxt : Text;VAR IsHandled : Boolean)
`

`LOCAL [IntegrationEvent] OnBeforeSendProfile(ReportSelections : Record "Report Selections";SalesCrMemoHeader : Record "Sales Cr.Memo Header";DocTxt : Text;VAR IsHandled : Boolean)
`

Regards, Roman.

**Comment by AlexanderYakunin** [comment]
We already have all that
