### ISSUE TITLE
[Extensibility Request] report 99001017 "Calculate Plan - Plan. Wksh." - InitializeRequest

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17265]
Most of our customers are running this plan during the night hours using the job queue and task scheduler. We are not able to set all the parameters available in the request page. Could you provide below mentioned new procedure to accommodate that:

    procedure InitializeRequest(NewMPS: Boolean; NewMRP: Boolean; NewUseForecast: Code[10]; NewExcludeForecastBefore: Date; NewNoPlanningResiliency: Boolean)
    begin
        //A108F0061.Event20.00.ns
        MPS := NewMPS;
        MRP := NewMRP;
        UseForecast := NewUseForecast;
        ExcludeForecastBefore := NewExcludeForecastBefore;
        NoPlanningResiliency := NewNoPlanningResiliency;
        //A108F0061.Event20.00.ne
    end;

**Comment by AlexanderYakunin** [comment]
Suggested procedure does not have parameters for FromDate, ToDate and RespectPlanningParm. Should we add all parameters to new procedure?

**Comment by Duizy1971** [comment]
That is also fine by me, but would that not result into a 'breaking' change? That is why I added a new procedure with the same name; 

procedure InitializeRequest(NewFromDate: Date; NewToDate: Date; NewRespectPlanningParm: Boolean)

does not work because MPS and MRP are from a manufacturing setup instead of another setup we have per day in our addon.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
