### ISSUE TITLE
request for external - table 36 "Sales Header" - procedure InitPostingDescription()

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#17261]
We have some cases where e.g. when fields are validated, and we have a certain combo of values, we want to change the Posting Description to something other than the BC default.

However, if our values don't support that (e.g. a related record is missing/blank) then we want to revert to the standard Posting Description.

Thus can you please make `InitPostingDescription()` public so we can call it in cases where we can't use our 'custom' description and want to restore yours?

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
