### ISSUE TITLE
[Event Request] - report 7315 "Calculate Whse. Adjustment" - OnAfterSetItemJournalLineFilters

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17266]
ItemJnlLine.SetRange("Unit of Measure Code", "Unit of Measure Code");
                                ItemJnlLine.SetRange("Warehouse Adjustment", true);
                                OnAfterSetItemJournalLineFilters(ItemJnlLine, TempAdjmtBinContentBuffer); //A200F0000.Event
                                if ItemJnlLine.FindSet() then
                                    repeat
                                        ReservationEntry.SetRange("Source Type", DATABASE::"Item Journal Line");

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetItemJournalLineFilters(var ItemJournalLine: Record "Item Journal Line"; BinContentBuffer: Record "Bin Content Buffer")
    begin
        //A200F0000.Event20.00
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
