### ISSUE TITLE
Table 60 - Document Sending Profile - new events OnBeforeSend, OnBeforeSendVendor, OnBeforeTrySendToPrinterVendor

### ISSUE THREAD

**Issue by rgrygoryshchak** [Microsoft/ALAppExtensions#1726]
Hi,

   Could you please add new events to table 60 'Document Sending Profile'?

`LOCAL [IntegrationEvent] OnBeforeSend(ReportUsage : Integer;RecordVariant : Variant;DocNo : Code[20];ToCust : Code[20];DocName : Text[150];CustomerFieldNo : Integer;DocumentNoFieldNo : Integer;VAR Handled : Boolean)
`

`LOCAL [IntegrationEvent] OnBeforeSendVendor(ReportUsage : Integer;RecordVariant : Variant;DocNo : Code[20];ToVendor : Code[20];DocName : Text[150];VendorNoFieldNo : Integer;DocumentNoFieldNo : Integer;VAR Handled : Boolean)
`

`LOCAL [IntegrationEvent] OnBeforeTrySendToPrinterVendor(ReportUsage : Integer;RecordVariant : Variant;VendorFieldNo : Integer;ShowDialog : Boolean;VAR Handled : Boolean)
`

   **Usage:**

```
Send(ReportUsage : Integer;RecordVariant : Variant;DocNo : Code[20];ToCust : Code[20];DocName : Text[150];CustomerFieldNo : Integer;DocumentNoFieldNo : Integer)
// New Code >>
OnBeforeSend(ReportUsage,RecordVariant,DocNo,ToCust,DocName,CustomerFieldNo,DocumentNoFieldNo,Handled);
IF Handled THEN
  EXIT;
// New Code <<

SendVendor(ReportUsage : Integer;RecordVariant : Variant;DocNo : Code[20];ToVendor : Code[20];DocName : Text[150];VendorNoFieldNo : Integer;DocumentNoFieldNo : Integer)
// New Code >>
OnBeforeSendVendor(ReportUsage,RecordVariant,DocNo,ToVendor,DocName,VendorNoFieldNo,DocumentNoFieldNo,Handled);
IF Handled THEN
  EXIT;
// New Code <<

[External] TrySendToPrinterVendor(ReportUsage : Integer;RecordVariant : Variant;VendorNoFieldNo : Integer;ShowDialog : Boolean)
// New Code >>
OnBeforeTrySendToPrinterVendor(ReportUsage,RecordVariant,VendorFieldNo,ShowDialog,Handled);
IF Handled THEN
  EXIT;
// New Code <<

```
Regards, Roman.

**Comment by AlexanderYakunin** [comment]
We already have all these events available. Please use latest preview builds from Collaborate for next asks.
