### ISSUE TITLE
[Event Request] codeunit 7304 "Whse. Jnl.-Register Batch" - OnInitItemJournalLine

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17262]
Maybe put the ItemJournal Line code in a separate procedure and make it an OnBeforeCreateItemJournalLine event...

    local procedure CreateItemJnlLine(WhseJnlLine2: Record "Warehouse Journal Line"; var ItemJnlLine: Record "Item Journal Line"): Boolean
        ...
                if QtyToHandleBase <> 0 then begin
                    OnInitItemJournalLine(ItemJnlLine, WhseJnlLine2, WhseJnlTemplate); //A200F0000.Event
                    ItemJnlLine."Document No." := "Whse. Document No.";

    [IntegrationEvent(false, false)]
    local procedure OnInitItemJournalLine(var ItemJournalLine: Record "Item Journal Line"; WarehouseJournalLine: Record "Warehouse Journal Line"; WarehouseJournalTemplate: Record "Warehouse Journal Template")
    begin
        //A200F0000.Event20.00
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
