### ISSUE TITLE
[Protected Var Request] - report 6653 "Combine Return Receipts"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17276]
We would like to be able to use them in an OnOpenPage trigger extension

    protected var
        PostingDateReq: Date;
        DocDateReq: Date;
        CalcInvDisc: Boolean;
        PostInv: Boolean;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
