### ISSUE TITLE
[Event Request] - report 7304 "Get Outbound Source Documents" - OnBeforeCreateWarehousePickLineFromShipmentLine

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17288]
if not "Assemble to Order" then begin
                            CalcFields("Pick Qty.", "Pick Qty. (Base)");
                            //A109F0004.Event20.00.ns
                            OnBeforeCreateWarehousePickLineFromShipmentLine("Whse. Pick Request", "Warehouse Shipment Header", "Warehouse Shipment Line", IsHandled);
                            if not IsHandled then
                                CurrReport.Skip();
                            //A109F0004.Event20.00.ne
                            if "Qty. (Base)" > "Qty. Picked (Base)" + "Pick Qty. (Base)" then begin
                                if "Destination Type" = "Destination Type"::Customer then begin
                                    TestField("Destination No.");
                                    Cust.Get("Destination No.");
                                    Cust.CheckBlockedCustOnDocs(Cust, "Source Document", false, false);
                                end;

                                if WhsePickWkshCreate.FromWhseShptLine(PickWkshTemplate, PickWkshName, "Warehouse Shipment Line") then
                                    LineCreated := true;
                            end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateWarehousePickLineFromShipmentLine(var WhsePickRequest: Record "Whse. Pick Request"; var WarehouseShipmentHeader: Record "Warehouse Shipment Header"; var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var IsHandled: Boolean)
    begin
        //A109F0004.Event20.00
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
