### ISSUE TITLE
[Protected Var Request] - report 7391 "Whse. Get Bin Content"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17295]
We need to be able to explode the item tracking with a report extension in the "Bin Content" OnAfterGetRecord trigger. We are in dire need of the created destination records:

    protected var
        //A200F0000.Event20.00
        WhseWorksheetLine: Record "Whse. Worksheet Line";
        WhseInternalPutawayLine: Record "Whse. Internal Put-away Line";
        ItemJournalLine: Record "Item Journal Line";
        TransferLine: Record "Transfer Line";
        InternalMovementLine: Record "Internal Movement Line";

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
