### ISSUE TITLE
[Protected Var Request] - report 5855 "Implement Standard Cost Change"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17291]
protected var
        //A108F0062.Event20.00
        PostingDate: Date;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
