### ISSUE TITLE
[Bug] Events in Codeunit "Purch.-Post" use the wrong variable as parameter

### ISSUE THREAD

**Issue by kaspermoerch** [microsoft/ALAppExtensions#17298]
In Codeunit 90 Purch.-Post some of the calls to Event Publishers are using the wrong TempPurchLine variable.

This results in an empty temporary table when subscribing to these events.

So far I have identified the problem on the following calls to Event Publishers:

**FinalizePosting**
`OnFinalizePostingOnAfterUpdateItemChargeAssgnt(PurchHeader, TempDropShptPostBuffer, EverythingInvoiced, TempPurchLine);`
should be
`OnFinalizePostingOnAfterUpdateItemChargeAssgnt(PurchHeader, TempDropShptPostBuffer, EverythingInvoiced, TempPurchLineGlobal);`

`OnFinalizePostingOnBeforeUpdateAfterPosting(PurchHeader, TempDropShptPostBuffer, EverythingInvoiced, IsHandled, TempPurchLine);`
should be
`OnFinalizePostingOnBeforeUpdateAfterPosting(PurchHeader, TempDropShptPostBuffer, EverythingInvoiced, IsHandled, TempPurchLineGlobal);`

**DeleteAfterPosting**
`OnBeforeDeleteAfterPosting(PurchHeader, PurchInvHeader, PurchCrMemoHeader, SkipDelete, SuppressCommit, TempPurchLine);`
should be
`OnBeforeDeleteAfterPosting(PurchHeader, PurchInvHeader, PurchCrMemoHeader, SkipDelete, SuppressCommit, TempPurchLineGlobal);`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
