### ISSUE TITLE
[Event Change Request] codeunit 80 "Sales-Post"- OnBeforePostItemLine

### ISSUE THREAD

**Issue by Vittorio-Panigoni** [microsoft/ALAppExtensions#17299]
In codeunit 80 "Sales-Post" event OnBeforePostItemLine please change the signature in the same way as codeunit 90 "Purch.-Post".
From 
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostItemLine(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

```
to
```al
   [IntegrationEvent(false, false)]
    local procedure OnBeforePostItemLine(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; var RemQtyToBeInvoiced: Decimal; var TempSalesLineGlobal: Record "Sales Line" temporary; var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer" temporary; var RemQtyToBeInvoicedBase: Decimal; var IsHandled:Boolean)
    begin
    end;
```

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
