### ISSUE TITLE
[Event Request] Table 5080 "To-do" - OnBeforeStartWizard

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#17296]
Similar to the StartWizard() function in Table 5077 "Segment Line", please add a OnBeforeStartWizard() event in Table 5080 "To-do":

```
procedure StartWizard()
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeStartWizard(Rec, IsHandled);
    if IsHandled then
        exit;

    "Wizard Step" := "Wizard Step"::"1";
    [...]
```
The new event:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeStartWizard(var Task: Record "To-do"; var IsHandled: Boolean)
begin
end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
