### ISSUE TITLE
[Event Request] Table 4 - OnAfterInitRoundingPrecision(xRec, GLSetup)

### ISSUE THREAD

**Issue by tomasevicstefan** [Microsoft/ALAppExtensions#1729]
Hi,

Could you please add new Integration Publisher **OnAfterInitRoundingPrecision(VAR xRec : Record Currency; GeneralLedgerSetup: Record "General Ledger Setup")** in table 4 Currency.

![1](https://user-images.githubusercontent.com/31925856/54682961-aae1de80-4b10-11e9-98f5-6e3129e9d906.png)

Regards,
Stefan

**Comment by hvandenborn** [comment]
We also need this one!
