### ISSUE TITLE
[Event Request] - report 7391 "Whse. Get Bin Content" - OnAfterInitItemJournalLine

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17292]
And please move up the template and Batch fetch code. It would even be better, certainly performance wise, to put both Template and Batch Gets in the procedure InitializeItemJournalLine and set as global.

    local procedure InsertItemJournalLine(BinContent: Record "Bin Content")
    var
        ItemJournalTempl: Record "Item Journal Template";
        ItemJournalBatch: Record "Item Journal Batch";
    begin
        with ItemJournalLine do begin
            //A108F0000.Event20.00.ns
            ItemJournalTempl.Get("Journal Template Name");
            ItemJournalBatch.Get("Journal Template Name", "Journal Batch Name");
            //A108F0000.Event20.00.ne
            Init();
            "Line No." := "Line No." + 10000;
            OnAfterInitItemJournalLine(ItemJournalLine, ItemJournalTempl, ItemJournalBatch); //A108B0045.Event20.00
            Validate("Entry Type", "Entry Type"::Transfer);

    [IntegrationEvent(false, false)]
    local procedure OnAfterInitItemJournalLine(var ItemJournalLine: Record "Item Journal Line"; ItemJournalTemplate: Record "Item Journal Template"; ItemJournalBatch: Record "Item Journal Batch")
    begin
        //A108B0045.Event20.00
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
