### ISSUE TITLE
[Event Request] - report 7391 "Whse. Get Bin Content" - OnAfterSetWarehouseEntryFilters

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17293]
local procedure GetItemTracking(BinContent: Record "Bin Content")
        ...
            SetRange("Variant Code", BinContent."Variant Code");
            SetRange("Unit of Measure Code", BinContent."Unit of Measure Code");
            OnAfterSetWarehouseEntryFilters(WarehouseEntry, "Bin Content"); //A200F0000.Event20.00
            if FindSet() then
                repeat
                    if TrackingExists() then begin

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetWarehouseEntryFilters(var WarehouseEntry: Record "Warehouse Entry"; var BinContent: Record "Bin Content")
    begin
        //A200F0000.Event20.00
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
