### ISSUE TITLE
event request - codeunit 427 ICInboxOutboxMgt - CreateJournalLines() - OnBeforeCreateJournalLines()

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#17308]
We have a requirement to suppress some validation logic while creating GJLs from the IC Inbox. Thus we need an event before the GJLs have their fields validated.

Thus please add an event:

```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateJournalLines(InboxTransaction: Record "IC Inbox Transaction"; InboxJnlLine: Record "IC Inbox Jnl. Line"; var TempGenJnlLine: Record "Gen. Journal Line" temporary; GenJnlTemplate: Record "Gen. Journal Template"; var IsHandled: Boolean)
```

called like so

```al
    procedure CreateJournalLines(InboxTransaction: Record "IC Inbox Transaction"; InboxJnlLine: Record "IC Inbox Jnl. Line"; var TempGenJnlLine: Record "Gen. Journal Line" temporary; GenJnlTemplate: Record "Gen. Journal Template")
    var
    [...]
        IsHandled: Boolean;
    begin
        OnBeforeCreateJournalLines(InboxTransaction, InboxJnlLine, TempGenJnlLine, GenJnlTemplate, IsHandled);
        if IsHandled then exit;
        [...]
```

We do not require the `Handled` pattern at the moment but think that it can't hurt to have, and we think including all procedure parameters to subscribers is nice and future-proof. :-)

There is already an `OnAfterCreateJournalLines()`, although it lacks most parameters, but we shouldn't need them added right now (hopefully!)

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
