### ISSUE TITLE
[Event Request] Table 81 "Gen. Journal Line" - function FindFirstVendLedgEntryWithAppliesToDocNo - event

### ISSUE THREAD

**Issue by agicdai** [microsoft/ALAppExtensions#17302]
Could you please add integration event 
OnFindFirstVendLedgEntryWithAppliesToDocNoOnAfterSetFilters(var GenJournalLine: Record "Gen. Journal Line"; AccNo: Code[20]; var VendLedgEntry: Record "Vendor Ledger Entry")  
right before exit(VendLedgEntry.FindFirst) in function FindFirstVendLedgEntryWithAppliesToDocNo()?

![image](https://user-images.githubusercontent.com/90642246/164273890-9cbe5dcd-29ab-4c04-8ff9-21b6e9588b13.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
