### ISSUE TITLE
[Event Extension Request] Report 699 "Calculate Plan - Req. Wksh." - New parameters in Publishers

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#17317]
Hello, we need a new parameter in Publisher OnBeforeDeleteReqLines. Can you please check that? Thank you!

            trigger OnAfterGetRecord()
            var
                IsHandled: Boolean;
            begin
                if Counter mod 5 = 0 then
                    Window.Update(1, "No.");
                Counter := Counter + 1;

                if SkipPlanningForItemOnReqWksh(Item) then
                    CurrReport.Skip();

                PlanningAssignment.SetRange("Item No.", "No.");

                ReqLine.LockTable();
                ActionMessageEntry.LockTable();

                IsHandled := false;
                OnBeforeDeleteReqLines(Item, PurchReqLine, ReqLineExtern, InvtProfileOffsetting, IsHandled);      <====NewPar-InvtProfileOffsetting====
                if not IsHandled then begin
                    PurchReqLine.SetRange("No.", "No.");
                    PurchReqLine.ModifyAll("Accept Action Message", false);
                    PurchReqLine.DeleteAll(true);

                    ReqLineExtern.SetRange(Type, ReqLine.Type::Item);
                    ReqLineExtern.SetRange("No.", "No.");
                    if ReqLineExtern.Find('-') then
                        repeat
                            ReqLineExtern.Delete(true);
                        until ReqLineExtern.Next() = 0;
                end;

Event signature with new parameter:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteReqLines(Item: Record Item; var PurchReqLine: Record "Requisition Line"; var ReqLineExtern: Record "Requisition Line"; InvtProfileOffsetting: Codeunit "Inventory Profile Offsetting"; var IsHandled: Boolean)
    begin
    end;

We also need new parameters in Publisher OnBeforeSkipPlanningForItemOnReqWksh. Can you please check that? Thank you!

    local procedure SkipPlanningForItemOnReqWksh(Item: Record Item): Boolean
    var
        SkipPlanning: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        SkipPlanning := false;
        OnBeforeSkipPlanningForItemOnReqWksh(Item, SkipPlanning, IsHandled, SKU, CurrWorksheetType);     <===NewPar-SKU,CurrWorksheetType====
        if IsHandled then
            exit(SkipPlanning);

        with Item do
            if (CurrWorksheetType = CurrWorksheetType::Requisition) and
               ("Replenishment System" = "Replenishment System"::Purchase) and
               ("Reordering Policy" <> "Reordering Policy"::" ")
            then
                exit(false);

        with SKU do begin
            SetRange("Item No.", Item."No.");
            if Find('-') then
                repeat
                    if (CurrWorksheetType = CurrWorksheetType::Requisition) and
                       ("Replenishment System" in ["Replenishment System"::Purchase,
                                                   "Replenishment System"::Transfer]) and
                       ("Reordering Policy" <> "Reordering Policy"::" ")
                    then
                        exit(false);
                until Next() = 0;
        end;

        SkipPlanning := true;
        OnAfterSkipPlanningForItemOnReqWksh(Item, SkipPlanning);
        exit(SkipPlanning);
    end;

Event signature with new parameter:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSkipPlanningForItemOnReqWksh(Item: Record Item; var SkipPlanning: Boolean; var IsHandled: Boolean; SKU: Record "Stockkeeping Unit"; CurrWorksheetType: Option Requisition,Planning)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
