### ISSUE TITLE
[Request for Protected var] page 5870 "BOM Structure" - ItemFilter

### ISSUE THREAD

**Issue by aobsgit** [microsoft/ALAppExtensions#17311]
Hi

Could you please expose "ItemFilter" variable as protected?
We are extending this page and that information is needed.

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
