### ISSUE TITLE
[Event Request] Report 5198 "Add Contacts" - New publisher

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#17313]
Hello, we need a new Event publisher with a Handling pattern in procedure AddPeople(). Can you please check that? Thank you!

    local procedure AddPeople()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;                                                                                                         
        OnBeforeAddPeople(TempCont, TempCont2, Cont, "Contact Mailing Group", IsHandled);          <<=====New Event======
        if IsHandled then                                                                                                           
            exit;   
                                                                                                                         
        TempCont.Reset();
        if TempCont.Find('-') then
            repeat
                if TempCont."Company No." <> '' then begin
                    Cont.SetCurrentKey("Company No.");
                    Cont.SetRange("Company No.", TempCont."Company No.");
                    if Cont.Find('-') then
                        repeat
                            TempCont2 := Cont;
                            if TempCont2.Insert() then;
                        until Cont.Next() = 0
                end else begin
                    TempCont2 := TempCont;
                    TempCont2.Insert();
                end;
            until TempCont.Next() = 0;

        TempCont.DeleteAll();
        if TempCont2.Find('-') then
            repeat
                TempCont := TempCont2;
                TempCont.Insert();
            until TempCont2.Next() = 0;
        TempCont2.DeleteAll();
    end;

New Event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAddPeople(var TempCont: Record Contact temporary; var TempCont2: Record Contact temporary; Cont: Record Contact; DataItemContactMailingGroup: Record "Contact Mailing Group"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
