### ISSUE TITLE
[Extensibility Request] Report 699 "Calculate Plan - Req. Wksh." - Protected variables

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#17314]
Hello, we need the following currently global variables defined as protected for our Report extension. Can you please check that? Thank you!

    protected var
        InvtProfileOffsetting: Codeunit "Inventory Profile Offsetting";
        MfgSetup: Record "Manufacturing Setup";
        CurrTemplateName: Code[10];
        CurrWorksheetName: Code[10];
        FromDate: Date;
        ToDate: Date;
        RespectPlanningParm: Boolean;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
