### ISSUE TITLE
[Event Extension Request] Report 492 "Copy Purchase Document"- New parameters in Publisher 

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#17326]
Hello, we need a new parameters  in Publisher OnPreReportOnBeforeCopyPurchaseDoc. Can you please check that? Thank you!

    trigger OnPreReport()
    begin
        OnBeforePreReport();

        PurchSetup.Get();
        CopyDocMgt.SetProperties(
          IncludeHeader, RecalculateLines, false, false, false, PurchSetup."Exact Cost Reversing Mandatory", false);
        CopyDocMgt.SetArchDocVal(FromDocNoOccurrence, FromDocVersionNo);
       
        OnPreReportOnBeforeCopyPurchaseDoc(CopyDocMgt, IncludeHeader, RecalculateLines);    <====newPar-IncludeHeader, RecalculateLines====

        CopyDocMgt.CopyPurchDoc(FromDocType, FromDocNo, PurchHeader);
    end;

Event signature with new parameters:

    [IntegrationEvent(false, false)]
    local procedure OnPreReportOnBeforeCopyPurchaseDoc(var CopyDocumentMgt: Codeunit "Copy Document Mgt."; IncludeHeader: Boolean; RecalculateLines: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
