### ISSUE TITLE
[Event Request] Report 492 "Copy Purchase Document" - New publisher

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#17327]
Hello, we need a new Event publisher in the procedure ValidateIncludeHeader. Can you please check that? Thank you!

    procedure ValidateIncludeHeader()
    begin
        RecalculateLines :=
          (FromDocType in [FromDocType::"Posted Receipt", FromDocType::"Posted Return Shipment"]) or not IncludeHeader;

        OnAfterProcedureValidateIncludeHeader(RecalculateLines, IncludeHeader);       <====NewEvent====
    end;

New Event:

    [IntegrationEvent(false, false)]
    local procedure OnAfterProcedureValidateIncludeHeader(var RecalculateLines: Boolean; IncludeHeader: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
