### ISSUE TITLE
[Event Request] Report 292 "Copy Sales Document" - New publisher

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#17329]
Hello, we need a new Event publisher in the procedure ValidateIncludeHeader. Can you please check that? Thank you!

    local procedure ValidateIncludeHeader()
    begin
        RecalculateLines :=
          (FromDocType in [FromDocType::"Posted Shipment", FromDocType::"Posted Return Receipt"]) or not IncludeHeader;

        OnAfterProcedureValidateIncludeHeader(RecalculateLines);               <=====NewEvent====
    end;

New Event:

    [IntegrationEvent(false, false)]
    local procedure OnAfterProcedureValidateIncludeHeader(var RecalculateLines: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
