### ISSUE TITLE
[Event Request] Table 81 "Gen. Journal Line", function GetVendLedgerEntry: OnBeforeGetVendLedgEntry

### ISSUE THREAD

**Issue by nd2403** [microsoft/ALAppExtensions#17339]
Hello,
we need a way to insert our code in GetVendLedgerEntry function. Please add following publisher. Thank you in advance!
```al
procedure GetVendLedgerEntry()
// - new
    var
        IsHandled: Boolean;
// + new
    begin
// - new
        IsHandled := false;
        OnBeforeGetVendLedgEntry(Rec, IsHandled);
        if IsHandled then
            exit;
// + new
       [...]
```
```al
// - new
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetVendLedgEntry(var GenJnlLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
    begin
    end;
// + new
```

**Comment by Stepanenko-Vadim** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
