### ISSUE TITLE
[Event Extension Request] Report 2 "General Journal - Test"  - new Handling pattern in Publisher OnAfterAssignDimTableID

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#17335]
Hello, we need a new Handling pattern in the Publisher OnAfterAssignDimTableID. Can you please check that? Thank you!

    local procedure CheckDimensions(GenJournalLine: Record "Gen. Journal Line")
    var
        DimMgt: Codeunit DimensionManagement;
        TableID: array[10] of Integer;
        No: array[10] of Code[20];
        IsHandled: Boolean;
    begin
        with GenJournalLine do begin
            if not DimMgt.CheckDimIDComb("Dimension Set ID") then
                AddError(DimMgt.GetDimCombErr);

            TableID[1] := DimMgt.TypeToTableID1("Account Type".AsInteger());
            No[1] := "Account No.";
            TableID[2] := DimMgt.TypeToTableID1("Bal. Account Type".AsInteger());
            No[2] := "Bal. Account No.";
            TableID[3] := DATABASE::Job;
            No[3] := "Job No.";
            TableID[4] := DATABASE::"Salesperson/Purchaser";
            No[4] := "Salespers./Purch. Code";
            TableID[5] := DATABASE::Campaign;
            No[5] := "Campaign No.";

            IsHandled := false;
            OnAfterAssignDimTableID(GenJournalLine, TableID, No, IsHandled);                      <====NewPar-IsHandled====
            if IsHandled then
                if not DimMgt.CheckDimValuePosting(TableID, No, "Dimension Set ID") then
                        AddError(DimMgt.GetDimValuePostingErr);
        end;
    end;

Event signature with new parameter:

    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignDimTableID(GenJournalLine: Record "Gen. Journal Line"; var TableID: array[10] of Integer; var No: array[10] of Code[20]; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
