### ISSUE TITLE
event request - table 5964 "Service Contract Line" - LogContractLineChanges() - OnAfterLogContractLineChanges

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#17336]
We have a need to change some other fields and log those.

We can use `OnModify()` but since `LogContractLineChanges()` is public, we want an event so that we definitely catch all calls to it.

Thus can you please add an event like so?

```al
[IntegrationEvent(false, false)]
local procedure OnAfterLogContractLineChanges(xServiceContractLine: Record "Service Contract Line"; var ServiceContractLine: Record "Service Contract Line")
```

called at the end of `LogContractLineChanges()` like

```al
OnAfterLogContractLineChanges(ServContractLine2, Rec);
```

`ServContractLine2` is the unfortunate name for the `xRec` passed from `OnModify()`.

`var ServiceContractLine` should be `var` so that subscribers can check if it `.IsTemporary` and not modify the database if it is.

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
