### ISSUE TITLE
Add FieldNo to OnAfterInitDefaultDimensionSources

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#17341]
Getting default dimensions has been redesigned in v20. A new event has been added everywhere: OnAfterInitDefaultDimensionSources.

However, in many cases the function InitDefaultDimensionSources that raises the event has a parameter FieldNo that is missing in the events.

Please review all occurrences of event OnAfterInitDefaultDimensionSources and add FieldNo as an extra parameter if available.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
