### ISSUE TITLE
[Event Request] Codeunit 5940

### ISSUE THREAD

**Issue by aismel87** [microsoft/ALAppExtensions#17343]
Hello,

We need a new event in the codeunit 5940, "LookupServItemNo" procedure, "OnLookupServItemOnBeforeFilterByShipToCode(ServItem, ServiceContractLine, IsHandled)", after the "ServItem.FilterGroup(0)" line. It should work in a similar way to the OnLookupServItemNoOnBeforeFilterByCustomerNo event

![imagen](https://user-images.githubusercontent.com/93609371/164699990-6f2c9fb0-bb19-4a3f-bc84-5101dce337d2.png)

Regards,

Ismael

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40825.
