### ISSUE TITLE
"Persistent Blob" extensibility request 

### ISSUE THREAD

**Issue by gntpet** [microsoft/ALAppExtensions#17349]
Dear AL Gurus, 

We do have scenario where we use "Persistent Blob" table across multiple companies. We are downloading PDFs from another company by using CHANGECOMPANY on NAV2018.

Now, when moving to extensions, we have an issue since this table is marked as Internal and we cannot access it. Existing functions in codeunit 4101 does not support this scenario either. 

I see few options available:

- remove internal property from table 4151 "Persistent Blob"
- add new parameter "CompanyName" to function CopyToOutStream on codeunit 4101 "Persistent Blob"

Could you please implement one of it?

Best Regards, 
Gintautas

**Comment by mazhelez** [comment]
Hey @gntpet 

The scenario you described is definitely a valid one and it was not considered in the current design.

We have logged an issue on our side, but talking from experience, it might be faster if you decide to contribute a solution to [Persistent Blob](https://github.com/microsoft/ALAppExtensions/blob/main/Modules/System/BLOB%20Storage/src/PersistentBlob.Codeunit.al) and related object.

**Comment by mazhelez** [comment]
Hi again @gntpet 

Unfortunately, the request didn't make the cut as the scenario isn't broadly used. However, we would still gladly accept your contribution, should you decide to make it.
