### ISSUE TITLE
[Extensibility Request] Email - SMTP API, enable read receipts and/or additional message headers

### ISSUE THREAD

**Issue by quadfin** [microsoft/ALAppExtensions#17340]
Is it possible to expose an interface on the SmtpMessage codeunit to allow setting additional message headers?
In particular, "Disposition-Notification-To", but in general any valid message header
https://www.iana.org/assignments/message-headers/message-headers.xhtml

**Comment by darjoo** [comment]
Hi @quadfin, absolutely. We think that it shouldn't just be possible for SMTP API but the whole Email module and downstream connectors. Would you be willing to open on PR on this?

**Comment by darjoo** [comment]
I'll be closing this for the timebeing and if you're willing, feel free to open a PR or reach out to us here again open the issue to discuss further on the design etc.

**Comment by acjdekorte** [comment]
We also needing something simular, because the dutch Auction requires that the message has headers namely
'21', '7bit'
'22', 'application/edifact'
