### ISSUE TITLE
"Rec." missing from page objects

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#17342]
When can someone update all the base microsoft page objects with "Rec."? it makes diffs very tedious when PTE require it in Visual Studio but somehow the base objects get away with not having it?

Example: APIV2SalesInvoices.Page.al (v20.0):

without Rec:

                field(shortcutDimension1Code; "Shortcut Dimension 1 Code")
                {
                    Caption = 'Shortcut Dimension 1 Code';

                    trigger OnValidate()
                    begin
                        RegisterFieldSet(FieldNo("Shortcut Dimension 1 Code"));
                    end;
                }

needs Rec:

                field(shortcutDimension1Code; Rec."Shortcut Dimension 1 Code")
                {
                    Caption = 'Shortcut Dimension 1 Code';

                    trigger OnValidate()
                    begin
                        RegisterFieldSet(Rec.FieldNo("Shortcut Dimension 1 Code"));
                    end;
                }

**Comment by dnpb** [comment]
How does the style of base code affect extensibility?

**Comment by grantbrimhall** [comment]
two reasons ... (1) API pages are not extensible. so if I want to extend an API page for a client, I have to copy the base code into a PTE page. Visual Studio will not compile without Rec. everywhere. So I have to tediously add it. and (2) when base pages get updates, and I want to compare my PTE page with the base page, as explained above I get sometimes 100's of diffs solely because base page doesn't have Rec. but the PTE page does.

But larger question is this: if visual studio is demanding all page variables have Rec., how is base code able to compile without this? Shouldn't base code have to adhere to all development standards too?

Thanks.

**Comment by AlexanderYakunin** [comment]
We are improving base app code too. Rec will be added for vNext
