### ISSUE TITLE
[Event Request] Table 81 "Gen. Journal Line" - OnExportPaymentFileOnBeforeCheckDocNoOnLines - AGAIN

### ISSUE THREAD

**Issue by MatjazSega** [microsoft/ALAppExtensions#17345]
Hello,

Two weeks ago, I issued an event request for OnExportPaymentFileOnBeforeCheckDocNoOnLines in Table 81 "Gen. Journal Line" (#17045).
@Stepanenko-Vadim replied "This will be OnBeforeCheckDocNoOnLines inside CheckDocNoOnLines instead".
Unfortunately, I did not notice the reply before the issue got closed, so I need to make a new Issue with "complaint" on the proposed solution. 

The thing is, we would only like to skip Document No. check when exporting payments, but keep it in place when posting. When you are inside the CheckDocNoOnLines() procedure, you have no way of knowing whether the procedure was called from posting or from payment export.
This is why I suggested OnExportPaymentFileOnBeforeCheckDocNoOnLines event in ExportPaymentFile() procedure. The alternative solution would be to add CalledFromPosting (Boolean) parameter to CheckDocNoOnLines() procedure. I'm OK with either solution.

I hope I have sufficiently explained my issue with proposed solution.

Best regards,
Matjaž

**Comment by Stepanenko-Vadim** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
