### ISSUE TITLE
[Event Request] page 5703 "Location Card" - OnAfterUpdateEnabled

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17355]
Could you please add the following event?
```al
procedure UpdateEnabled()
begin

  ...

    UseADCSEnable := not Rec."Use As In-Transit" and Rec."Directed Put-away and Pick";
    PickAccordingToFEFOEnable := Rec."Require Pick" and Rec."Bin Mandatory";
    OnAfterUpdateEnabled(Rec); //NEW
end;
```
```al
[IntegrationEvent(true, false)]
local procedure OnAfterUpdateEnabled(Location: Record Location)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
