### ISSUE TITLE
Codeunit 1279 GenerateHash() Hex InputString 

### ISSUE THREAD

**Issue by BjEic** [microsoft/ALAppExtensions#17359]
Codeunit 1279 GenerateHash() hast an InputString and returns a hexadecimal string.
If the input string is a "normal" string hashes are calculated correctly.
If the input string is a hexadecimal value stored in a string variable hashes are not calculated correctly.

Example: see https://github.com/microsoft/ALAppExtensions/issues/17137

**Comment by Groenbech96** [comment]
Hi @BjEic 
I have investigated your problem with this, and you need to use the Base64 versions of the module. 
Take a look at how the test is written, as it follows the same example as you are referring to. 
https://github.com/microsoft/ALAppExtensions/blob/main/Modules/System%20Tests/Cryptography%20Management/src/GenerateBase64KeyedHashTest.Codeunit.al

If you try and run this test, and convert the base64 back to the hex format used in your example, you will see that the values from each call is correct.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
