### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnBeforeSalesLinesExist

### ISSUE THREAD

**Issue by moomencegekadsa** [microsoft/ALAppExtensions#17365]
Hello,

We request that the _OnBeforeSalesLinesExist()_ event is added to the _SalesLinesExist()_ procedure in table 36 _Sales Header_ as below.
```
    procedure SalesLinesExist(): Boolean
+   var
+      IsHandled: Boolean;
    begin
+       IsHandled := false;
+       OnBeforeSalesLinesExist(Rec, xRec, IsHandled);
+       if IsHandled then
+           exit;

        SalesLine.Reset();
        SalesLine.SetRange("Document Type", "Document Type");
        SalesLine.SetRange("Document No.", "No.");
        exit(not SalesLine.IsEmpty);
    end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesLinesExist(var SalesHeader: Record "Sales Header"; xSalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;
```
Thanks!

**Comment by dnpb** [comment]
I'm curious what the use-case for this is? And must it always return `false`, as your added code implicitly will?

**Comment by moomencegekadsa** [comment]
Well, it will not always return false, right? Only if _IsHandled_ is set to true. As for the use case; There are situations in which certain (non standard) fields on the Sales Header determine the fact that the Sales Lines should to be changed, for example in _RecreateSalesLines()_ defined in object _Sales Header_.

**Comment by dannoe** [comment]
For your mentioned use case you should subscribe to the ``OnBeforeRecreateSalesLinesHandler`` event in the ``Sales Header`` and set the IsHandled to true. I would consider this a code smell if I call ``SalesHeader.SalesLinesExist()`` and it would return false even though there are sales lines.

**Comment by Stepanenko-Vadim** [comment]
We agree with the above comment.
This is a very straightforward and atomic procedure, that is probably used by many and over-riding it is not a good idea.
Please consider using events that exist in places where this is called but produces the undesirable (for you) result instead of this event.
