### ISSUE TITLE
[Event Change] Table To-Do Event OnCreateTaskFromSalesHeaderoOnBeforeStartWizard

### ISSUE THREAD

**Issue by AJasp** [Microsoft/ALAppExtensions#1736]
This event is called in the function CreateTaskFromSalesHeader. I assume a small error in the naming of the event and please rename it from OnCreateTaskFromSalesHeaderoOnBeforeStartWizard in 
OnCreateTaskFromSalesHeaderOnBeforeStartWizard

Thanks

**Comment by AlexanderYakunin** [comment]
We cannot change name of event, but only implement new one and make old obsolete

**Comment by AJasp** [comment]
> We cannot change name of event, but only implement new one and make old obsolete

That would be fine too.
