### ISSUE TITLE
Missing Extension Menu /  Search Abilities

### ISSUE THREAD

**Issue by markjinx** [Microsoft/ALAppExtensions#1737]
We have created extensions for both BC and NAV2018 that are having the same issue. After we install the application, the Menu Suite will arbitrarily disappear and the search function will not find our objects. Restarting services will sometimes bring back this functionality but then at some point it will again disappear. This is getting to be a real problem for our users who cannot keep restarting services throughout the day to maybe get it back. We seem to have the UsageCategory and ApplicationArea properties correct as the menu suite /  search ability will be there, but then go away.

I know there have been issues with the menu suite not appearing when there are over 20 pages, but we only have 8 pages and 2 reports.

We have also had this happen with third party extension applications that have been installed.

**Comment by JesperSchulz** [comment]
Nice catch! Let's get the issue to a team who will fix and backport it, as this repo only is for extensibility related issues in the upcoming release. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.
