### ISSUE TITLE
Set init value from Install Codeunit

### ISSUE THREAD

**Issue by tomasevicstefan** [Microsoft/ALAppExtensions#1738]
Does anyone know how to set init values to custom fields on standard table (existing records) throw install codeunit?

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
