### ISSUE TITLE
TempGLEntryPreview initialize problem at ContinuePosting on Gen. Jnl.-Post Line

### ISSUE THREAD

**Issue by rameijeirasfe** [microsoft/ALAppExtensions#17387]
Hello,

I have detected an initialization problem in the TempGLEntryPreview variable when call a function ContinuePosting on codeunit 12 "Gen. Jnl.-Post Line".

In the StartPosting function the DeleteAll() is done correctly, both of the TempGLEntryBuf and TempGLEntryPreview variables.

![2022-04-26_12h56_18](https://user-images.githubusercontent.com/34210912/165286285-5e2d9b13-0524-44d7-8146-9ab410363745.png)

However, in the ContinuePosting only the TempGLEntryBuf  have a DeleteAll();

![2022-04-26_12h58_40](https://user-images.githubusercontent.com/34210912/165286305-2569f44d-86e7-4916-9a4c-a88a5fce2000.png)

I consider that in the ContinuePosting the DeleteAll() should be performed so that there is no insertion error if you modify the TempGLEntryBuf  

![2022-04-26_13h00_31](https://user-images.githubusercontent.com/34210912/165286327-b0fb1886-73d2-4b16-8533-83d6de75b29a.png)

Thanks.

**Comment by rameijeirasfe** [comment]
News?

**Comment by AlexanderYakunin** [comment]
Hello! We cannot take this change, as we should not clean TempGLEntryPreview buffer at this point to support preview of multiple postings coming in one transaction. For example, during Exchange rate adjustment. Do you have repro steps when you have error message during preview, in this case we will try to fix this problem without breaking existing functionality?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42550.
