### ISSUE TITLE
[Event Request] Codeunit 826 - Purch. Post Invoice Events - OnBeforeTempDeferralHeaderInsert

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#17392]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeTempDeferralHeaderInsert` to be added to Codeunit 826 Purch. Post Invoice Events with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTempDeferralHeaderInsert(var TempDeferralHeader: Record "Deferral Header" temporary; DeferralHeader: Record "Deferral Header"; PurchLine: Record "Purchase Line") //New
    begin
    end;
```

which would be called as follows from `RunOnBeforeTempDeferralHeaderInsert`:
```al
    procedure RunOnBeforeTempDeferralHeaderInsert(var TempDeferralHeader: Record "Deferral Header" temporary; DeferralHeader: Record "Deferral Header"; PurchLine: Record "Purchase Line") //New
    begin
        OnBeforeTempDeferralHeaderInsert(TempDeferralHeader, DeferralHeader, PurchLine);
    end;
```

which would be called as follows from Codeunit 816 - Purch. Post Invoice `CalcDeferralAmounts`:
```al
                  TempDeferralHeader."Amount to Defer", PurchHeader."Currency Factor"));
            PurchPostInvoiceEvents.RunOnBeforeTempDeferralHeaderInsert(TempDeferralHeader, DeferralHeader, PurchLine); //New
            TempDeferralHeader.Insert();
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
