### ISSUE TITLE
[Event Request] Codeunit 825 - Sales Post Invoice Events - OnBeforeTempDeferralHeaderInsert

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#17395]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeTempDeferralHeaderInsert` to be added to Codeunit 825 Sales Post Invoice Events with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTempDeferralHeaderInsert(var TempDeferralHeader: Record "Deferral Header" temporary; DeferralHeader: Record "Deferral Header"; SalesLine: Record "Sales Line") //New
    begin
    end;
```

which would be called as follows from `RunOnBeforeTempDeferralHeaderInsert`:
```al
    procedure RunOnBeforeTempDeferralHeaderInsert(var TempDeferralHeader: Record "Deferral Header" temporary; DeferralHeader: Record "Deferral Header"; SalesLine: Record "Sales Line") //New
    begin
        OnBeforeTempDeferralHeaderInsert(TempDeferralHeader, DeferralHeader, SalesLine);
    end;
```

which would be called as follows from Codeunit 815 - Sales Post Invoice `CalcDeferralAmounts`:
```al
            TempDeferralHeader."Amount to Defer (LCY)" :=
              Round(
                CurrExchRate.ExchangeAmtFCYToLCY(
                  SalesHeader.GetUseDate(), SalesHeader."Currency Code",
                  TempDeferralHeader."Amount to Defer", SalesHeader."Currency Factor"));
            SalesPostInvoiceEvents.RunOnBeforeTempDeferralHeaderInsert(TempDeferralHeader, DeferralHeader, SalesLine); //New
            TempDeferralHeader.Insert();
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
