### ISSUE TITLE
[Event Request] Report 12152 "Create Subcontr.Transf. Order" -  CheckPurchLine(PurchLine: Record "Purchase Line"; InsertLine: Boolean; var QtyToPost: Decimal): Boolean

### ISSUE THREAD

**Issue by Simolabo** [microsoft/ALAppExtensions#17399]
(For Italian Localization).
Please, can you add the event suggested below in order to add information to the transfer lines taken from the purchase lines? Thank you in advance.

procedure  CheckPurchLine(PurchLine: Record "Purchase Line"; InsertLine: Boolean; var QtyToPost: Decimal): Boolean

 begin
        if not ProdOrderLine.Get(ProdOrderLine.Status::Released, PurchLine."Prod. Order No.", PurchLine."Prod. Order Line No.") then
            exit(false);
        if not ProdOrderRoutingLine.Get(ProdOrderRoutingLine.Status::Released, PurchLine."Prod. Order No.",
             PurchLine."Routing Reference No.", PurchLine."Routing No.", PurchLine."Operation No.")
        then
            Error(Text1130002, PurchOrderNo, PurchLine."Routing No.", PurchLine."Prod. Order No.", PurchLine."Operation No.");

        Item.Get(PurchLine."No.");
        QtyPerUom := UOMMgt.GetQtyPerUnitOfMeasure(Item, PurchLine."Unit of Measure Code");

        if ProdOrderRoutingLine."WIP Item" then begin
            ProdOrderRoutingLine.SetRange("Purchase Order Filter", PurchLine."Document No.");
            ProdOrderRoutingLine.CalcFields("Qty. WIP on Subcontractors", "Qty. WIP on Transfer Order");
            QtyToPost := Round(PurchLine.Quantity * QtyPerUom, UOMMgt.QtyRndPrecision) -
              (ProdOrderRoutingLine."Qty. WIP on Subcontractors" + ProdOrderRoutingLine."Qty. WIP on Transfer Order");
            QtyToPost := Round(QtyToPost / QtyPerUom, UOMMgt.QtyRndPrecision);
            exit(QtyToPost > 0);
        end;

        ProdOrderComponent.SetCurrentKey(Status, "Prod. Order No.", "Routing Link Code");
        ProdOrderComponent.SetRange(Status, ProdOrderComponent.Status::Released);
        ProdOrderComponent.SetRange("Prod. Order No.", PurchLine."Prod. Order No.");
        ProdOrderComponent.SetRange("Prod. Order Line No.", PurchLine."Prod. Order Line No.");
        ProdOrderComponent.SetRange("Routing Link Code", ProdOrderRoutingLine."Routing Link Code");
        ProdOrderComponent.SetRange("Purchase Order Filter", PurchLine."Document No.");
        if ProdOrderComponent.FindSet then
            repeat
                Item.Get(ProdOrderComponent."Item No.");
                QtyToPost := CostCalcMgt.CalcActNeededQtyBase(ProdOrderLine, ProdOrderComponent,
                    Round(PurchLine.Quantity * QtyPerUom, 0.00001));
                ProdOrderComponent.CalcFields("Qty. on Transfer Order (Base)", "Qty. in Transit (Base)",
                  "Qty. transf. to Subcontractor");
                if QtyToPost > (ProdOrderComponent."Qty. on Transfer Order (Base)" + ProdOrderComponent."Qty. in Transit (Base)" +
                                ProdOrderComponent."Qty. transf. to Subcontractor")
                then
                    if InsertLine then begin
                        if Vendor."Subcontractor Procurement" then
                            InsertTransferHeader(PurchLine."Location Code")
                        else
                            if ProdOrderComponent."Original Location" <> '' then
                                InsertTransferHeader(ProdOrderComponent."Original Location")
                            else
                                InsertTransferHeader(ProdOrderComponent."Location Code");
                        LineNum := LineNum + 10000;
                        TransferLine.Init();
                        TransferLine."Document No." := TransferHeader."No.";
                        TransferLine."Line No." := LineNum;
                        TransferLine.Validate("Item No.", ProdOrderComponent."Item No.");
                        TransferLine.Validate("Variant Code", ProdOrderComponent."Variant Code");
                        TransferLine."Unit of Measure Code" := ProdOrderComponent."Unit of Measure Code";
                        TransferLine."Qty. per Unit of Measure" := ProdOrderComponent."Qty. per Unit of Measure";
                        QtyToPost := QtyToPost - (ProdOrderComponent."Qty. on Transfer Order (Base)" +
                                                  ProdOrderComponent."Qty. in Transit (Base)" +
                                                  ProdOrderComponent."Qty. transf. to Subcontractor");
                        TransferLine.Validate(Quantity,
                          Round(QtyToPost / ProdOrderComponent."Qty. per Unit of Measure", Item."Rounding Precision", '>'));
                        TransferLine."Subcontr. Purch. Order No." := PurchLine."Document No.";
                        TransferLine."Subcontr. Purch. Order Line" := PurchLine."Line No.";
                        TransferLine."Prod. Order No." := PurchLine."Prod. Order No.";
                        TransferLine."Prod. Order Line No." := PurchLine."Prod. Order Line No.";
                        TransferLine."Prod. Order Comp. Line No." := ProdOrderComponent."Line No.";
                        TransferLine."Routing No." := PurchLine."Routing No.";
                        TransferLine."Routing Reference No." := PurchLine."Routing Reference No.";
                        TransferLine."Work Center No." := PurchLine."Work Center No.";
                        TransferLine."Operation No." := PurchLine."Operation No.";
                        TransferLine.Insert();

                         //New Event Code - Begin
                        OnAfterInsertTransferLineCheckPurchaseLine(TransferHeader, TransferLine,PurchLine);
                       //New Event Code - End

                        if ProdOrderComponent."Original Location" = '' then
                            ProdOrderComponent."Original Location" := ProdOrderComponent."Location Code";
                        ProdOrderComponent."Location Code" := TransferHeader."Transfer-to Code";
                        ProdOrderComponent.GetDefaultBin;
                        ProdOrderComponent.Modify();
                        SubcontractingMgt.TransfSUBOrdCompToSUBTransfOrd(TransferLine, ProdOrderComponent);
                    end else
                        exit(true);
            until ProdOrderComponent.Next() = 0;

        exit(false);
end;

[IntegrationEvent(TRUE, false)]
procedure OnAfterInsertTransferLineCheckPurchaseLine(var TransferHeader: Record "Transfer Header"; var TransferLine: Record "Transfer Line"; PurchaseLine: record "Purchase Line"): Boolean)
begin
end;

**Comment by AI-91** [comment]
This is necessary also for us!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
