### ISSUE TITLE
[Extensibility Bug] table 49 "Invoice Post. Buffer" -  Invoice Posting Interface - Set Events to obsolete (e.g. OnAfterInvPostBufferPrepareSales)

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17397]
Today I checked our events after an update and it looks like some events are missing an obsolete state.
Shouldn't the events in table `table 49 "Invoice Post. Buffer"` being set to obsolete and instead point to the new posting interface events in `table 55 "Invoice Posting Buffer"`?

e.g. the following event:
```al
[Obsolete('Moved to Sales Invoice Posting implementation. Use Event OnAfterPrepareSales in table 55 "Invoice Posting Buffer" instead.', '19.0')] //NEW
[IntegrationEvent(false, false)]
local procedure OnAfterInvPostBufferPrepareSales(var SalesLine: Record "Sales Line"; var InvoicePostBuffer: Record "Invoice Post. Buffer")
begin
end;
```

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 47298.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 47376.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47651.
