### ISSUE TITLE
[Event Request] - Table Vendor Ledger Entry/Customer Ledger Entry - OnBeforeValidateMessageToRecipient

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#17398]
Could this be added? Or maybe the same functionality that is in sales header for status check. 
Both for vendor ledger entry and customer ledger entry.

```
field(289; "Message to Recipient"; Text[140])
        {
            Caption = 'Message to Recipient';

            trigger OnValidate()
            var
                IsHandled:Boolean;
            begin
                OnBeforeValidateMessageToRecipient(Rec,IsHandled);
                if not StatusCheckSuspended then
                    TestField(Open, true);
            end;
        }

 [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateMessageToRecipient(var VendorLedgerEntry:Record "Vendor Ledger Entry"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
