### ISSUE TITLE
[Event Request] Report 12152 "Create Subcontr.Transf. Order" - OnAfterGetRecord

### ISSUE THREAD

**Issue by Simolabo** [microsoft/ALAppExtensions#17401]
(For Italian Localization).
Please, can you add the event suggested below in order to add information to the transfer lines taken from the purchase lines? Thank you in advance.

  trigger OnAfterGetRecord()
                var
                    QtyToPost: Decimal;
                begin
                    if not "WIP Item" then
                        CheckPurchLine("Purchase Line", true, QtyToPost)
                    else begin
                        CheckPurchLine("Purchase Line", false, QtyToPost);
                        if QtyToPost > 0 then begin
                            TestField("Location Code");
                            InsertTransferHeader("Location Code");
                            TransferLine.Init();
                            TransferLine."Document No." := TransferHeader."No.";
                            LineNum := LineNum + 10000;
                            TransferLine."Line No." := LineNum;
                            TransferLine.Validate("Item No.", "No.");
                            TransferLine.Validate("Variant Code", "Variant Code");
                            TransferLine.Validate("Unit of Measure Code", "Unit of Measure Code");
                            TransferLine.Validate("WIP Quantity", QtyToPost);
                            TransferLine."Subcontr. Purch. Order No." := "Document No.";
                            TransferLine."Subcontr. Purch. Order Line" := "Line No.";
                            TransferLine."Prod. Order No." := "Prod. Order No.";
                            TransferLine."Prod. Order Line No." := "Prod. Order Line No.";
                            TransferLine."WIP Item" := true;
                            TransferLine."Routing No." := "Routing No.";
                            TransferLine."Routing Reference No." := "Routing Reference No.";
                            TransferLine."Work Center No." := "Work Center No.";
                            TransferLine."Operation No." := "Operation No.";
                            TransferLine.Insert();
                    
                           //New Event Code - Begin
                           OnAfterInsertTransferLine(TransferHeader, TransferLine, "Purchase Line");
                          //New Event Code - End

                        end;
                    end;
                end;

[IntegrationEvent(TRUE, false)]
procedure OnAfterInsertTransferLine(var TransferHeader: Record "Transfer Header"; var TransferLine: Record "Transfer Line"; PurchaseLine: record "Purchase Line"): Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
