### ISSUE TITLE
[Request] table 5741 "Transfer Line" - Validate "Item No." calculates weights, volume and parcels twice

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17425]
I thought I was at the correct place to ask for this particular issue on serviceshub (2204260050001625) but they send me back here:

This is not a request that is describing that the BC application is malfunctioning or setting up data incorrectly. There will certainly not be a repo. It is a request to make the AL code a bit cleaner and clearer 

In table 5741 "Transfer Line" there is the following code in the Validate trigger of "Item No.":

1- Validate(Quantity, xRec.Quantity); 
2- Validate("Unit of Measure Code", Item."Base Unit of Measure"); 
3- Validate("Gross Weight", Item."Gross Weight"); 
4- Validate("Net Weight", Item."Net Weight"); 
5- Validate("Unit Volume", Item."Unit Volume"); 
6- Validate("Units per Parcel", Item."Units per Parcel"); 
7- Item Category Code" := Item."Item Category Code"; 

The lines 3,4,5 and 6 can be deleted because they have already been calculated with the validation of "Unit of Measure Code" in line 2: 

Validate("Qty. per Unit of Measure", UOMMgt.GetQtyPerUnitOfMeasure(Item, "Unit of Measure Code")); 
"Gross Weight" := Item."Gross Weight" * "Qty. per Unit of Measure"; 
"Net Weight" := Item."Net Weight" * "Qty. per Unit of Measure"; 
"Unit Volume" := Item."Unit Volume" * "Qty. per Unit of Measure"; 
"Units per Parcel" := Round(Item."Units per Parcel" / "Qty. per Unit of Measure", UOMMgt.QtyRndPrecision);

I wanted to do something with the rounding of the Weight values with an OnAfterValidate "Unit of Measure Code" subscriber but it was not working the same way as it does in for instance T37 and T39. The mentioned lines of code is probably a leftover from NAV1.x when we did not have Item Units of Measure.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46699.
