### ISSUE TITLE
[Access Request]  table 1007 "Job WIP Warning"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17448]
Could you please remove to local scope of the procedure `InsertWarning` in `table 1007 "Job WIP Warning"`?
```al
//local procedure InsertWarning(JobWIPTotal: Record "Job WIP Total"; Message: Text[250]) //OLD
procedure InsertWarning(JobWIPTotal: Record "Job WIP Total"; Message: Text[250]) //NEW
begin
    Reset;
    if FindLast() then
        "Entry No." += 1
    else
        "Entry No." := 1;
    "Job WIP Total Entry No." := JobWIPTotal."Entry No.";
    "Job No." := JobWIPTotal."Job No.";
    "Job Task No." := JobWIPTotal."Job Task No.";
    "Warning Message" := Message;
    Insert;
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
