### ISSUE TITLE
[Request for External] report 104 "Customer - Detail Trial Bal."

### ISSUE THREAD

**Issue by nvleeuwen** [microsoft/ALAppExtensions#17441]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request to make variable 'AppliedDocuments' protected on report 104 "Customer - Detail Trial Bal.".

````
protected var
    AppliedDocuments: Text[30];
````

**Comment by AlexanderYakunin** [comment]
This variable is not found in BaseApp, please recheck and create new request if needed
