### ISSUE TITLE
[Request for External] report 104 "Customer - Detail Trial Bal."

### ISSUE THREAD

**Issue by nvleeuwen** [microsoft/ALAppExtensions#17442]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request to make variable 'CustFilter' protected on report 104 "Customer - Detail Trial Bal.".

````
protected var
    CustFilter: Text;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
