### ISSUE TITLE
[Request for External] report 27 "Dimensions - Total"

### ISSUE THREAD

**Issue by nvleeuwen** [microsoft/ALAppExtensions#17446]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request to make variable 'GLAcc' protected on report 27 "Dimensions - Total".

````
protected var
    GLAcc: Record "G/L Account"; 
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
