### ISSUE TITLE
[Request for External] report 4 "Detail Trial Balance"

### ISSUE THREAD

**Issue by nvleeuwen** [microsoft/ALAppExtensions#17444]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request to make variable 'GLFilter' protected on report 4 "Detail Trial Balance".

````
protected var
    GLFilter: Text;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
