### ISSUE TITLE
[Request for external] page 2901 "Demand Forecast Card" - SetMatrix and SetMatrixColumns

### ISSUE THREAD

**Issue by Vittorio-Panigoni** [microsoft/ALAppExtensions#17455]
In page 2901 "Demand Forecast Card" please change the visibility of the procedures SetMatrix and SetMatrixColumns to global or protected, as they were in old page page 99000919 "Demand Forecast".

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
