### ISSUE TITLE
[Fix Event Request] codeunit 6529 "Item Tracking Navigate Mgt.": Add VAR to EventPublisher

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#17479]
see #16622

The ItemFilters parameter of the event publisher has to be defined as VAR parameter or the filters get lost.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
