### ISSUE TITLE
Table 130 Local [IntegrationEvent] OnAfterFindPostdRecord(

### ISSUE THREAD

**Issue by clausmacali** [Microsoft/ALAppExtensions#1747]
Thanks for this on table 130                    
Thanks for this, could I request for the last 2 Events

Local [IntegrationEvent] OnAfterUpdateDocumentFields(VAR IncomingDocument : Record "Incoming Document; VAR DocExist : Bolean)

Missing
Local [IntegrationEvent] OnAfterFindPostdRecord(VAR IncomingDocument : Record "Incoming Document; VAR RelatedRecord : Variant;VAR RecordFound : Bolean)

Local [IntegrationEvent] OnAfterFindUnpostedRecord(VAR IncomingDocument : Record "Incoming Document; VAR RelatedRecord : Variant;VAR RecordFound : Bolean)

**Comment by AlexanderYakunin** [comment]
All this already implemented
