### ISSUE TITLE
[Request for external] Page 344 Navigate - Request to make different variables protected

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#17477]
Please make these variables protected so we can extend the tracking search of the Navigate page:

```al
SerialNoFilter: Text;
LotNoFilter: Text;
PackageNoFilter: Text;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
