### ISSUE TITLE
Bug Table 1223 "Data Exch. Column Def" - Overflow

### ISSUE THREAD

**Issue by b1m1** [microsoft/ALAppExtensions#17481]
The length of the string is 56, but it must be less than or equal to 50 characters. Value: Nett_weight_per_unit_measure_unit_specifier_in_kilograms

**Internal session id:** 
f79ec577-f475-4d07-92de-89b08598814a

**Application Insights session id:** 
ff25740e-5569-46f2-84e3-e1fb7aee535f

**Client activity id:** 
ab9c493f-eb70-934f-adea-36cb4fc41bc4

**Timestamp:** 
2022-04-29T09:36:42.9261749Z

**AL call stack:** 
"XSD Parser"(CodeUnit 9610).**CreateDataExchColumnDefinitions** line 34 - Base Application by Microsoft
"XSD Parser"(CodeUnit 9610).CreateDataExchDefForCAMT line 19 - Base Application by Microsoft
"XML Schema Viewer"(Page 9610)."GenerateDataExchSetup - OnAction"(Trigger) line 4 - Base Application by Microsoft

In procedure **CreateDataExchColumnDefinitions** procedure **InsertRecForImport** will be called. 
DataExchColumnDef.Description = Text[100]. Procedure InsertRecForImport allows a value of Text[50].
```
 DataExchColumnDef.InsertRecForImport(DataExchDef.Code, DataExchLineDef.Code,
                      ColumnNo, CopyStr(ElementName, 1, MaxStrLen(DataExchColumnDef.Name)),
                      CopyStr("Node Name", 1, MaxStrLen(DataExchColumnDef.Description)), true,
```
        field(8; Description; Text[100])
        {
            Caption = 'Description';
        }

**Solution**:
table 1223 "Data Exch. Column Def"
NewDescription has to be Text[100] instead of NewDescription: Text[50];

```
//Start
//procedure InsertRecForImport(DataExchDefCode: Code[20]; DataExchLineDefCode: Code[20]; ColumnNo: Integer; NewName: Text[250]; NewDescription: Text[50]; NewShow: Boolean; DataType: Option; DataFormat: Text[100]; DataFormattingCulture: Text[10])
procedure InsertRecForImport(DataExchDefCode: Code[20]; DataExchLineDefCode: Code[20]; ColumnNo: Integer; NewName: Text[250]; NewDescription: Text[100]; NewShow: Boolean; DataType: Option; DataFormat: Text[100]; DataFormattingCulture: Text[10])
//Stop
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42835.
