### ISSUE TITLE
Missing PriceType in PriceAsset on ShowPriceListLines() in item table

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#17487]
Hi, 
we want to add filters to the price list lines depends on the current price type (sale or purchase). Unfortunately, the pricetype isn't set in every case.
In my case it is the "Show Prices" (Sales & Pruchase) action in item card and list. I have enough publisher to change the result but not have the value of pricetype in my assets. This is because the procedure AsPriceAsset() does not add the pricetype.
To fix this i would suggest such change:

current:
```
    local procedure AsPriceAsset(var PriceAsset: Record "Price Asset")
    begin
        PriceAsset.Init();
        PriceAsset."Asset Type" := PriceAsset."Asset Type"::Item;
        PriceAsset."Asset No." := "No.";
    end;
```
suggested change:
```
    local procedure AsPriceAsset(var PriceAsset: Record "Price Asset"; PriceType: Enum "Price Type")
    begin
        PriceAsset.Init();
        PriceAsset."Asset Type" := PriceAsset."Asset Type"::Item;
        PriceAsset."Asset No." := "No.";
        PriceAsset."Price Type" := PriceType;
    end;
```
And of course, fill the parameters in ShowPriceListLines():

```
    procedure ShowPriceListLines(PriceType: Enum "Price Type"; AmountType: Enum "Price Amount Type")
    var
        PriceAsset: Record "Price Asset";
        PriceUXManagement: Codeunit "Price UX Management";
    begin
        AsPriceAsset(PriceAsset, PriceType);
        PriceUXManagement.ShowPriceListLines(PriceAsset, PriceType, AmountType);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
