### ISSUE TITLE
[Extensibility BUG]  codeunit 487 "Job Queue Start Report" - OnRunReportOnAfterCalcShouldModifyNotifyOnSuccess

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17494]
I requested an event for `OnRunReportOnAfterCalcShouldModifyNotifyOnSuccess` and specified that the event sould be added to a public (Access = External) Codeunit that we can subscribe to it. See Issue https://github.com/microsoft/ALAppExtensions/issues/16505
Could you please fix this?

```al
codeunit 487 "Job Queue Start Report"
{
    Access = Internal; // this is the problem
    TableNo = "Job Queue Entry";

    ....

/// THIS EVENT has to be in a PUBLIC accesible Codeunit
    [IntegrationEvent(false, false)]
    local procedure OnRunReportOnAfterCalcShouldModifyNotifyOnSuccess(ReportID: Integer; var JobQueueEntry: Record "Job Queue Entry"; var ShouldModifyNotifyOnSuccess: Boolean)
    begin
    end;
}
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
