### ISSUE TITLE
[Request for External] page 2901 "Demand Forecast Card" 

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#17491]
hi,

please switch the procedure to global
`    local procedure SetMatrix()`

please switch the variables to protected
```
    var
        MatrixRecords: array[32] of Record Date;
        VariantFilterIsEnabled: Boolean;
        LocationFilterIsEnabled: Boolean;
        IsEditable: Boolean;
        ItemFilter: Text;
        LocationFilter: Text;
        VariantFilter: Text;
        MatrixColumnCaptions: array[32] of Text[1024];
        ColumnSet: Text;
        PKFirstRecInCurrSet: Text;
        CurrentSetLength: Integer;
```

It would be really great if this requirement will be shipped with BC20. (Next minor)
I can not wait to the next major. :(

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
