### ISSUE TITLE
[Event Change Request]  page 345 Reconciliation - OnSaveNetChangeOnBeforeModify

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17497]
Could you please change the event `OnSaveNetChangeOnBeforeModify` to include the sender?
```al
//-[IntegrationEvent(false, false)] //OLD
[IntegrationEvent(true, false)] //NEW
local procedure OnSaveNetChangeOnBeforeModify(var GLAccountNetChange: Record "G/L Account Net Change"; GenJnlLine: Record "Gen. Journal Line"; AccType: Enum "Gen. Journal Account Type"; AccNo: Code[20]; NetChange: Decimal)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
