### ISSUE TITLE
[Access Request] page 189 "Incoming Document" AskUserPermission

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17498]
Could you please change the Access Scope of the procedure `AskUserPermission` to at least **protected**?
```al
//+Change
//-local procedure AskUserPermission(): Boolean
protected procedure AskUserPermission(): Boolean
//+Change
begin
    if "Data Exchange Type" = '' then
        exit(true);

    if Status <> Status::New then
        exit(true);

    exit(Confirm(AutomaticProcessingQst));
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
