### ISSUE TITLE
Codeunit "Format Address"

### ISSUE THREAD

**Issue by VolkerBoehm** [microsoft/ALAppExtensions#17492]
It would be great to have the following events in this Codeunit:

OnBeforeAltAddr

OnBeforeEmployee

OnBeforeTransferShptTransferFrom

OnBeforeTransferShptTransferTo

OnBeforeTransferRcptTransferFrom

OnBeforeTransferRcptTransferTo

OnBeforeTransferHeaderTransferFrom

OnBeforeTransferHeaderTransferTo

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
