### ISSUE TITLE
[Event Change Request] codeunit 550 "VAT Rate Change Conversion"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17507]
Could you please change the event `OnAfterUpdateTables`  to include the sender?

```al
//-[IntegrationEvent(false, false)] //OLD
[IntegrationEvent(true, false)] //NEW
local procedure OnAfterUpdateTables(var VATRateChangeSetup: Record "VAT Rate Change Setup")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
