### ISSUE TITLE
[Event Request] page 343 "Check Credit Limit" - OnAfterCalcOverdueBalanceLCY

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17506]
Can we please get the following event?
```al
local procedure CalcOverdueBalanceLCY()
begin
    if GetFilter("Date Filter") = '' then
        SetFilter("Date Filter", '..%1', WorkDate);
    OnCalcOverdueBalanceLCYAfterSetFilter(Rec);
    CalcFields("Balance Due (LCY)");
    OnAfterCalcOverdueBalanceLCY(Rec); // New Event
end;
```
```al
[IntegrationEvent(true, false)]
local procedure OnAfterCalcOverdueBalanceLCY(var Customer: Record Customer);
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
