### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - Function InsertVATForGLEntry()

### ISSUE THREAD

**Issue by boych83** [microsoft/ALAppExtensions#17515]
Hello ALAppExtensions team,

for every occurrence of CreateGLEntry() function inside function InsertVATForGLEntry ( inside case statement from line 728 - 768 ) we would like to have ability to change G/L Account No.

New events would be similar to existing event OnInsertVATOnBeforeCreateGLEntryForReverseChargeVATToPurchAcc() or  OnInsertVATOnBeforeCreateGLEntryForReverseChargeVATToRevChargeAcc() but with "if IsHandled then" pattern.

e.g. changed code between lines 730 - 734:
<pre><code>
....
 case VATPostingSetup."VAT Calculation Type" of
                            VATPostingSetup."VAT Calculation Type"::"Normal VAT",
                            VATPostingSetup."VAT Calculation Type"::"Full VAT":
                                
                                IsHandled := false;
                                OnInsertVATOnBeforeCreateGLEntryForNormalAndFullVATToPurchAcc(GenJnlLine, VATPostingSetup, UnrealizedVAT, GLEntryVATAmount, SrcCurrGLEntryVATAmt, true, IsHandled)
                             if not IsHandled then
                                CreateGLEntry(GenJnlLine, VATPostingSetup.GetPurchAccount(UnrealizedVAT),
                                  GLEntryVATAmount, SrcCurrGLEntryVATAmt, true);
...
</code></pre>

When we'll subscribing to event we'll then using CreateGLEntry() with our extension function from VATPostingSetup table, e.g. "VATPostingSetup.GetNewAccount()" 

BR,
Bojan

**Comment by Oleg-Romashkov** [comment]
Hi Bojan,

You can realize described logic with existing event OnBeforeInsertVATForGLEntry.

Rgds,
Oleg.

**Comment by boych83** [comment]
Hi @Oleg-Romashkov 

Yes, this is one option I have thought about, but we do not won't to "copy / paste" to much of the standard code to our event subs.
If standard code changes in the future, then we need to tarack and implement that in our event. We tried to avoid that in the past. For that reason we would like to have additional event publishers.

BR, 
Bojan
