### ISSUE TITLE
Azure blob list not returning Content Length in ABS Container Content table

### ISSUE THREAD

**Issue by PunkyGP** [microsoft/ALAppExtensions#17520]
Hello,

currently I'm using the "ABS Blob Client" codeunit to get a list of all blobs.
Everything works except that I don't receive the Content-Length and Content-Type of a file.

<img width="443" alt="Screen Shot 2022-05-03 at 15 45 01" src="https://user-images.githubusercontent.com/16012756/166465634-5e6b58f9-478c-494f-8e42-8cb02412247e.png">

Can it be a problem in the codeunit 9054 "ABS Container Content Helper". Where the field is searched by returned properties.
<img width="941" alt="Screen Shot 2022-05-03 at 15 51 13" src="https://user-images.githubusercontent.com/16012756/166465858-f4555c96-e67e-479c-9efd-dec23ea87641.png">

And if I'm reading correctly here https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs. The return property is Content-Type and the field name is Content Type. So without he -.

Thanks in advance,
Gunter

**Comment by mazhelez** [comment]
@PunkyGP Nice catch!

The MS team is quite busy at the moment, so feel free to open a PR with a solution and we'll try to uptake it as soon as possible :)
