### ISSUE TITLE
[Event Request] Codeunit 8 "AccSchedManagement"   OnAfterGetAccSchedName 

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#17527]
Hello,
Can we please get an event OnAfterGetAccSchedName in the function CheckName:

````
procedure CheckName(CurrentSchedName: Code[10])
    var
        AccSchedName: Record "Acc. Schedule Name";
    begin
        AccSchedName.Get(CurrentSchedName);
        OnAfterGetAccSchedName(CurrentSchedName);
    end;





[IntegrationEvent(false, false)]
    local procedure OnAfterGetAccSchedName(var CurrentSchedName: Code[10])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
