### ISSUE TITLE
[Event Request] Codeunit 8 "AccSchedManagement"   OnAfterGetColumnLayoutName 

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#17529]
Hello,
Can we please get an event OnAfterGetColumnLayoutName in the function CheckColumnName:

````
procedure CheckColumnName(CurrentColumnName: Code[10])
    var
        ColumnLayoutName: Record "Column Layout Name";
    begin
        ColumnLayoutName.Get(CurrentColumnName);
        OnAfterGetColumnLayoutName(CurrentColumnName);
    end;


[IntegrationEvent(false, false)]
    local procedure OnAfterGetColumnLayoutName(var CurrentColumnName: Code[10])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
