### ISSUE TITLE
[Request-For-External]  Codeunit 8 "AccSchedManagement"   EvaluateExpression

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#17534]
Can you please set the funktion EvaluateExpression  from local to global?

````
 procedure EvaluateExpression(IsAccSchedLineExpression: Boolean; Expression: Text; AccSchedLine: Record "Acc. Schedule Line"; ColumnLayout: Record "Column Layout"; CalcAddCurr: Boolean): Decimal
    var

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
