### ISSUE TITLE
[Event Request] OnBeforeSet in "Price Calculation Buffer Mgt."

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#17542]
Hi,
currently if you want to fill additional fields in "Price Calculation Buffer" Record you need to edit every "Line with Price" implementation. Thats not good in every case because we have additional fields that are not dependent on line with price implementations and should work with every implementation.
So, we need a more central publisher in codeunit "Price Calculation Buffer Mgt.":

New Publisher:
```
procedure Set(NewPriceCalculationBuffer: Record "Price Calculation Buffer"; var PriceSourceList: Codeunit "Price Source List")
begin
    OnBeforeSet(NewPriceCalculationBuffer); //New Publisher    
    PriceCalculationBuffer := NewPriceCalculationBuffer;

    CalcUnitAmountRoundingPrecision();

    PriceAssetList.Init();
    PriceAssetList.Add(PriceCalculationBuffer);

    SetSources(PriceSourceList);
end;
```
Signature:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeSet(var NewPriceCalculationBuffer: Record "Price Calculation Buffer")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
