### ISSUE TITLE
[Extensibility Request] Table 36 "Sales Header" - Protected variables

### ISSUE THREAD

**Issue by moomencegekadsa** [microsoft/ALAppExtensions#17550]
Hello,

We request that the following two globals in table 36 "Sales Header" are moved to the protected variables for use in our table extension of this object. 
```
    protected var
     +  Cust: Record Customer;
     +  SalesSetup: Record "Sales & Receivables Setup";
        HideCreditCheckDialogue: Boolean;
        HideValidationDialog: Boolean;
```
Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
