### ISSUE TITLE
[Event Request] Codeunit 99000813 Carry Out Action "OnCarryOutactionPrintTransferOrder"

### ISSUE THREAD

**Issue by SWGaupadhyay1** [microsoft/ALAppExtensions#17558]
Can we please get the following event?
```
procedure PrintTransferOrder(TransHeader: Record "Transfer Header")
    var
        ReportSelections: Record "Report Selections";
        TransHeader2: Record "Transfer Header";
    begin
        if PrintOrder then begin
            TransHeader2 := TransHeader;
            TransHeader2.SetRecFilter();
            ```
            //Event Request Begin
            OnCarryOutactionPrintTransferOrder(ReportSelections); 
            //Event Request End
```
            ReportSelections.PrintWithDialogWithCheckForCust("Report Selection Usage"::Inv1, TransHeader2, false, 0);
        end;
    end;

```
```
    [IntegrationEvent(false, false)]
    local procedure OnCarryOutactionPrintTransferOrder(var ReportSelections: Record "Report Selections");
    begin
        
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
