### ISSUE TITLE
[Event Request] Codeunit 99000845 - Reservation Management - OnUpdItemTrkgLineStatsOnBeforeReservEntrySummaryInsert

### ISSUE THREAD

**Issue by SchoKa** [Microsoft/ALAppExtensions#1756]
Hello AL-Team,
 please add the following Publisher in function "UpdateItemTrackingLineStats":

LOCAL UpdateItemTrackingLineStats(VAR ReservEntrySummary : Record "Entry Summary";AvailabilityDate : Date)
[ … ]
    IF ReservEntry.FINDSET THEN
      REPEAT
        ReservEntrySummary."Total Quantity" += ReservEntry."Quantity (Base)";
        IF ReservEntry."Reservation Status" = ReservEntry."Reservation Status"::Reservation THEN
          ReservEntrySummary."Total Reserved Quantity" += ReservEntry."Quantity (Base)";
        IF CalcReservEntry.HasSamePointer(ReservEntry) THEN
          ReservEntrySummary."Current Reserved Quantity" += ReservEntry."Quantity (Base)";
      UNTIL ReservEntry.NEXT = 0;

    ReservEntrySummary."Total Available Quantity" :=
      ReservEntrySummary."Total Quantity" - ReservEntrySummary."Total Reserved Quantity";

    // >> New
    OnUpdItemTrkgLineStatsOnBeforeReservEntrySummaryInsert(ReservEntrySummary,ReservEntry);
    // << New
    ReservEntrySummary.INSERT;
[ … ]

Publisher definition currently used by us
 IncludeSender: false
 GlobaVarAccess: false
LOCAL [IntegrationEvent] OnUpdItemTrkgLineStatsOnBeforeReservEntrySummaryInsert(VAR EntrySummary : Record "Entry Summary";VAR ReservationEntry : Record "Reservation Entry")

**Comment by NKarolak** [comment]
Note: added in BC Insider as OnUpdateItemTrackingLineStatsOnBeforeReservEntrySummaryInsert
