### ISSUE TITLE
[Event Request] Codeunit 9520 - CheckValidEmailAddress

### ISSUE THREAD

**Issue by hvandenborn** [Microsoft/ALAppExtensions#1758]
Please provide us with an, IsHandled Event so we can also do our own check or extend. 

why onbefore? we have some cases with multiple addresses within the incomming text variable, we have a check function that can handle that. this normal checkfunction cannot handle that.

![image](https://user-images.githubusercontent.com/48794854/54752906-f1ead500-4bdf-11e9-95e2-b92b8d9164b7.png)

**Comment by AlexanderYakunin** [comment]
We already have that, seems you are using old version:

[External] CheckValidEmailAddresses(Recipients : Text)
IsHandled := FALSE;
OnBeforeCheckValidEmailAddress(Recipients,IsHandled);
IF IsHandled THEN
  EXIT;
