### ISSUE TITLE
[Event Request] Codeunit 1026 "Job Link Usage" - OnBeforeFindMatchingJobPlanningLine

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#17581]
Please add the event OnBeforeFindMatchingJobPlanningLine() in Codeunit 1026 "Job Link Usage" like this:

```
procedure FindMatchingJobPlanningLine(var JobPlanningLine: Record "Job Planning Line"; JobLedgerEntry: Record "Job Ledger Entry"): Boolean
var
    [...]
begin
    [...]
    OnBeforeFindMatchingJobPlanningLine(JobPlanningLine, JobLedgerEntry);

    // Match most specific Job Planning Line.
    if JobPlanningLine.FindFirst then
        exit(true);
    [...]
end;
```
The new event:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeFindMatchingJobPlanningLine(var JobPlanningLine: Record "Job Planning Line"; JobLedgerEntry: Record "Job Ledger Entry")
begin
end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
