### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" - Events of Issue #16163 Missing

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17584]
Could you please add the events requested on the following issue?

codeunit 22 "Item Jnl.-Post Line" - OnSetItemAdjmtPropertiesOnBeforeModifyItem / OnSetItemAdjmtPropertiesOnAfterModifyItem
https://github.com/microsoft/ALAppExtensions/issues/16163
I can't see them on any new preview version...

**Comment by Stepanenko-Vadim** [comment]
Those were skipped because we've already implemented **OnSetItemAdjmtPropertiesOnBeforeCheckModifyItem(Item2, ModifyItem);** before it for another request and it seems that with this one you can do anything you can do with those two, so adding two more seemed redundant. If you have a scenario where you can't implement what you want with this one, please let us know

**Comment by Stepanenko-Vadim** [comment]
Why though? 
You can do whatever you want to do with 1st event, then do modify and do whatever you want to do with 2nd event.
Then just set the modifyitem to false so that baseapp code doesn't run the modify.

**Comment by pri-kise** [comment]
You are right we could solve it by using the first event and setting `ModifyItem` to false.

What I had in mind that someone requested the event `OnSetItemAdjmtPropertiesOnBeforeCheckModifyItem` to disable the Modify.
If another app subscribes to the event and want to set boolean  `ModifyItem` to false, but our event subscriber is called before the other subsriber we would still modify the Item, although the other app might have a good reason to disable the modify.

Therefore, yes we can use the already existing event, but we still would prefer an event before and after the current modify.

**Comment by Stepanenko-Vadim** [comment]
While we understand the concern, we still think that we have to draw the line somewhere in regards of implementing events that are not explicitly needed and can be substitute by others so that we do not overload code too much. Since this works for you will leave as is for now.
