### ISSUE TITLE
Table Relation Recipient Bank Account

### ISSUE THREAD

**Issue by martinhocosta88** [microsoft/ALAppExtensions#1759]
I've tried for the first time to modify a table relation so I've been testing the following in new development:

On Payment Journal the "recipient bank account" should not load the bank accounts from the "vendor no." but the bank accounts from the "Factoring vendor no." if its filled which is a specific field related with vendor table.

So I've changed the default table relation from the field "recipient bank account" to this:

![image](https://user-images.githubusercontent.com/13696679/54752372-be0ab200-4bd5-11e9-9065-50aa77a6f89a.png)
In Yellow are my changes to the standard relation.

Since the behaviour is the same as the standard, my question is: Do the standard relations overwrite changes on already existing relations?

**Comment by ikoletic** [comment]
This issue is a question. Please submit your questions on [business central community ](https://community.dynamics.com/business/f/758) or on [BC development yammer groups](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035).
