### ISSUE TITLE
[Scope Change] Table 370 "Excel Buffer" Procedure EnterCellByCellName

### ISSUE THREAD

**Issue by clembo67** [microsoft/ALAppExtensions#17593]
Please remove the scope OnPrem for procedure **EnterCellByCellName** in **Table 370**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
