### ISSUE TITLE
[Event Request] Table 38 Purchase Header OnAfterValidateDocumentDateWithPostingDate

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#17599]
Is it possible to add an event in the OnValidate-Trigger of field 20 "Document Date"?

<pre>
        field(20; "Posting Date"; Date)
        {
            Caption = 'Posting Date';

            trigger OnValidate()
            var
                SkipJobCurrFactorUpdate: Boolean;
            begin
                TestField("Posting Date");
                TestNoSeriesDate(
                  "Posting No.", "Posting No. Series",
                  FieldCaption("Posting No."), FieldCaption("Posting No. Series"));
                TestNoSeriesDate(
                  "Prepayment No.", "Prepayment No. Series",
                  FieldCaption("Prepayment No."), FieldCaption("Prepayment No. Series"));
                TestNoSeriesDate(
                  "Prepmt. Cr. Memo No.", "Prepmt. Cr. Memo No. Series",
                  FieldCaption("Prepmt. Cr. Memo No."), FieldCaption("Prepmt. Cr. Memo No. Series"));

                if "Incoming Document Entry No." = 0 then
                    ValidateDocumentDateWithPostingDate();

                // Event request
                OnAfterValidateDocumentDateWithPostingDate(Rec, xRec, CurrFieldNo);
                // Event request

                if ("Document Type" in ["Document Type"::Invoice, "Document Type"::"Credit Memo"]) and
                   not ("Posting Date" = xRec."Posting Date")
                then
                    PriceMessageIfPurchLinesExist(FieldCaption("Posting Date"));

    [IntegrationEvent(false, false)]
    local procedure OnAfterValidateDocumentDateWithPostingDate(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader: Record "Purchase Header"; CallingFieldNo: Integer) // RELC Requested with
    begin
    end;
</pre>

**Comment by Oleg-Romashkov** [comment]
Hi,

Is it ok for you if we update existing event OnValidatePostingDateOnBeforeResetInvoiceDiscountValue(Rec, xRec); by adding parameter CurrFieldNo?

Rgds,
Oleg.

**Comment by oni1300** [comment]
Hello Oleg,

in which version has this event been implemented? In version 20.0.37253.40434 this event does not exist.

Regards
Dietmar

Von: Oleg-Romashkov ***@***.***>
Gesendet: Mittwoch, 11. Mai 2022 08:23
An: microsoft/ALAppExtensions ***@***.***>
Cc: Schulz, Dietmar ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/ALAppExtensions] [Event Request] Table 38 Purchase Header OnAfterValidateDocumentDateWithPostingDate (Issue #17599)


Hi,

Is it ok for you if we update existing event OnValidatePostingDateOnBeforeResetInvoiceDiscountValue(Rec, xRec); by adding parameter CurrFieldNo?

Rgds,
Oleg.

**Comment by Oleg-Romashkov** [comment]
This is a fresh one. It will be available for 20.1

**Comment by oni1300** [comment]
Can you please send me a screenshot to see where the event is implemented in the trigger?

Von: Oleg-Romashkov ***@***.***>
Gesendet: Mittwoch, 11. Mai 2022 10:42
An: microsoft/ALAppExtensions ***@***.***>
Cc: Schulz, Dietmar ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/ALAppExtensions] [Event Request] Table 38 Purchase Header OnAfterValidateDocumentDateWithPostingDate (Issue #17599)


This is a fresh one. It will be available for 20.1

**Comment by Oleg-Romashkov** [comment]
```
        field(20; "Posting Date"; Date)
        {
            Caption = 'Posting Date';

            trigger OnValidate()
            var
                SkipJobCurrFactorUpdate: Boolean;
            begin
                TestField("Posting Date");
                TestNoSeriesDate(
                  "Posting No.", "Posting No. Series",
                  FieldCaption("Posting No."), FieldCaption("Posting No. Series"));
                TestNoSeriesDate(
                  "Prepayment No.", "Prepayment No. Series",
                  FieldCaption("Prepayment No."), FieldCaption("Prepayment No. Series"));
                TestNoSeriesDate(
                  "Prepmt. Cr. Memo No.", "Prepmt. Cr. Memo No. Series",
                  FieldCaption("Prepmt. Cr. Memo No."), FieldCaption("Prepmt. Cr. Memo No. Series"));

                if "Incoming Document Entry No." = 0 then
                    ValidateDocumentDateWithPostingDate();

                if ("Document Type" in ["Document Type"::Invoice, "Document Type"::"Credit Memo"]) and
                   not ("Posting Date" = xRec."Posting Date")
                then
                    PriceMessageIfPurchLinesExist(FieldCaption("Posting Date"));

                OnValidatePostingDateOnBeforeResetInvoiceDiscountValue(Rec, xRec);
                ResetInvoiceDiscountValue();

                if "Currency Code" <> '' then begin
                    UpdateCurrencyFactor();
                    if ("Currency Factor" <> xRec."Currency Factor") and not CalledFromWhseDoc then
                        SkipJobCurrFactorUpdate := not ConfirmCurrencyFactorUpdate();
                end;

                if "Posting Date" <> xRec."Posting Date" then
                    if DeferralHeadersExist() then
                        ConfirmUpdateDeferralDate();

                if PurchLinesExist() then
                    JobUpdatePurchLines(SkipJobCurrFactorUpdate);
            end;
        }

    [IntegrationEvent(false, false)]
    local procedure OnValidatePostingDateOnBeforeResetInvoiceDiscountValue(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader: Record "Purchase Header")
    begin
    end;

```

**Comment by oni1300** [comment]
I checked it out and I agree to your proposal to add CurrFieldNo to the parameter list of OnValidatePostingDateOnBeforeResetInvoiceDiscountValue.

Thank you and best regards
Dietmar

Von: Oleg-Romashkov ***@***.***>
Gesendet: Mittwoch, 11. Mai 2022 11:28
An: microsoft/ALAppExtensions ***@***.***>
Cc: Schulz, Dietmar ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/ALAppExtensions] [Event Request] Table 38 Purchase Header OnAfterValidateDocumentDateWithPostingDate (Issue #17599)


        field(20; "Posting Date"; Date)

        {

            Caption = 'Posting Date';



            trigger OnValidate()

            var

                SkipJobCurrFactorUpdate: Boolean;

            begin

                TestField("Posting Date");

                TestNoSeriesDate(

                  "Posting No.", "Posting No. Series",

                  FieldCaption("Posting No."), FieldCaption("Posting No. Series"));

                TestNoSeriesDate(

                  "Prepayment No.", "Prepayment No. Series",

                  FieldCaption("Prepayment No."), FieldCaption("Prepayment No. Series"));

                TestNoSeriesDate(

                  "Prepmt. Cr. Memo No.", "Prepmt. Cr. Memo No. Series",

                  FieldCaption("Prepmt. Cr. Memo No."), FieldCaption("Prepmt. Cr. Memo No. Series"));



                if "Incoming Document Entry No." = 0 then

                    ValidateDocumentDateWithPostingDate();



                if ("Document Type" in ["Document Type"::Invoice, "Document Type"::"Credit Memo"]) and

                   not ("Posting Date" = xRec."Posting Date")

                then

                    PriceMessageIfPurchLinesExist(FieldCaption("Posting Date"));



                OnValidatePostingDateOnBeforeResetInvoiceDiscountValue(Rec, xRec);

                ResetInvoiceDiscountValue();



                if "Currency Code" <> '' then begin

                    UpdateCurrencyFactor();

                    if ("Currency Factor" <> xRec."Currency Factor") and not CalledFromWhseDoc then

                        SkipJobCurrFactorUpdate := not ConfirmCurrencyFactorUpdate();

                end;



                if "Posting Date" <> xRec."Posting Date" then

                    if DeferralHeadersExist() then

                        ConfirmUpdateDeferralDate();



                if PurchLinesExist() then

                    JobUpdatePurchLines(SkipJobCurrFactorUpdate);

            end;

        }



    [IntegrationEvent(false, false)]

    local procedure OnValidatePostingDateOnBeforeResetInvoiceDiscountValue(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader: Record "Purchase Header")

    begin

    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
