### ISSUE TITLE
[Request for External] codeunit 22 "Item Jnl.-Post Line" - Procedure InsertPhysInventoryEntry

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#17607]
Please make procedure InsertPhysInventoryEntry in codeunit 22 "Item Jnl.-Post Line" generally available.

Ideal solution would be a new global function as overloaded function with a new parameter forItemJnlLine to create the physical ledger entry. 
Original idea is: we would like to create a physical ledger entry per TempSplitItemJnlLine per lot/serial/package no., but that is actually not possible.

procedure InsertPhysInventoryEntry(forItemJnlLine: Record "Item Journal Line")
var
  saveItemJnlLine: Record "Item Journal Line"
begin
  saveItemJnlLine := ItemJnlLineOrigin;
  ItemJnlLineOrigin := forItemJnlLine;
  InsertPhysInventoryEntry();
  ItemJnlLineOrigin := saveItemJnlLine;
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
