### ISSUE TITLE
Table 36 [Event Request] Global Currency, to use Amount Rounding Precision

### ISSUE THREAD

**Issue by mboon75** [Microsoft/ALAppExtensions#1761]
In table 36 and table 37 the currency records is supposed to be initialized and globally available, mainly to have the field Amount Rounding Precision available.

We want to use the field Amount Rounding Precision as well in a Extension Table on Table 37. There for i have added the following function to table 36 Sales Header (together with a EventPublisher to be able to influence the amount rounding precision by our own logic.

[External] GetCurrencyAmountRoundingPrecision() : Decimal
CLEAR(Currency);
IF NOT Currency.GET("Currency Code") THEN
  Currency.InitRoundingPrecision();
OnGetCurrencyAmountRoundingPrecision(Currency);
EXIT(Currency."Amount Rounding Precision");

LOCAL [IntegrationEvent] OnGetCurrencyAmountRoundingPrecision(VAR Currency : Record Currency)

The code in our Table Extension looks like this:

LOCAL CalcMargin(VAR Rec : Record "Sales Line")
GetSalesHeader(Rec, SH);
Rec.Margin :=  (Rec.Quantity * (Rec."Unit Price" - Rec."Unit Cost (LCY)"));
Rec.Margin := ROUND(Rec.Margin,SH.GetCurrencyAmountRoundingPrecision());

**Comment by mboon75** [comment]
This might be related to this request:
[Event Request] Table 37 - OnAfterGetSalesHeader #1610

**Comment by mboon75** [comment]
Same issue applies for Table 38, Purchase Header

**Comment by AlexanderYakunin** [comment]
You can easliy get this value using your code from table Currency, no need to add anything here.

**Comment by mboon75** [comment]
Hi Alexander, 
Not sure what you mean, but point is that Currency is a global in Sales Header and we want to use that currency value, without having to reinitialize it each and every time. 
When having to read this from Currency, we have to first read the Sales Header. It would be more clean coding if there is a function in the Sales Header which gives the used amountRoundingPrecision for the Sales Header. This function can then be used outside the Sales HEader as well.
