### ISSUE TITLE
[Event Request] Codeunit 99000838 - Prod. Order Comp.-Reserve - OnAfterDeleteReservEntries

### ISSUE THREAD

**Issue by SchoKa** [Microsoft/ALAppExtensions#1764]
Hello AL-Team,
please add the following Publisher in function "DeleteLine":

External] DeleteLine(VAR ProdOrderComp : Record "Prod. Order Component")
[ … ] 
 IF DeleteItemTracking THEN
    ReservMgt.SetItemTrackingHandling(1); // Allow Deletion
  ReservMgt.DeleteReservEntries(TRUE,0);
  // >> New
  OnAfterDeleteReservEntries(ProdOrderComp);
  // << New
  CALCFIELDS("Reserved Qty. (Base)");
[ … ]

Publisher definition currently used by us
 IncludeSender: false
 GlobaVarAccess: false
LOCAL [IntegrationEvent] OnAfterDeleteReservEntries(VAR ProdOrderComp : Record "Prod. Order Component")

**Comment by NKarolak** [comment]
Note: add as OnDeleteLineOnAfterDeleteReservEntries
