### ISSUE TITLE
[Event Request] Table 36  - Function RecreateSalesLines

### ISSUE THREAD

**Issue by mboon75** [microsoft/ALAppExtensions#1765]
We Like to have a OnBeforeRecreateSalesLines to be able to decided whether the RecreationProcess applies.

![image](https://user-images.githubusercontent.com/32514251/54756245-1d71bd80-4be8-11e9-8654-b22a0759a628.png)

**Comment by AlexanderYakunin** [comment]
We already have this event
LOCAL RecreateSalesLines(ChangedFieldName : Text[100])
IF NOT SalesLinesExist THEN
  EXIT;

OnRecreateSalesLinesOnBeforeConfirm(Rec,xRec,ChangedFieldName,HideValidationDialog,Confirmed,IsHandled);
IF NOT IsHandled THEN
