### ISSUE TITLE
[Event-request] Create Pick - OnAfterOpenPage

### ISSUE THREAD

**Issue by nanoono** [microsoft/ALAppExtensions#17655]
Hi, 

We request for a new Event Publisher on:

**Report: 5754 "Create Pick"**

    //...
        trigger OnOpenPage()
        begin
            if LocationCode <> '' then begin
                Location.Get(LocationCode);
                if Location."Use ADCS" then
                    DoNotFillQtytoHandle := true;
            end;
            //>event-request
            OnAfterOpenPage(DoNotFillQtytoHandle);
            //<event-request
        end;
    //...

**Integration event**

    //>event-request
    [IntegrationEvent(false, false)]
    local procedure OnAfterOpenPage(var DoNotFillQtytoHandle: Boolean)
    begin
    end;
    //<event-request

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
