### ISSUE TITLE
[Extensibility Request] local to global Codeunit 423 Change Log Management - IsLogActive and InsertLogEntry

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#17652]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

[Extensibility Request] Codeunit 423 "Change Log Management" - Procedure from Internal to Global

procedure IsLogActive(TableNumber: Integer; FieldNumber: Integer; TypeOfChange: Option Insertion,Modification,Deletion): Boolean

procedure InsertLogEntry(var FldRef: FieldRef; var xFldRef: FieldRef; var RecRef: RecordRef; TypeOfChange: Option Insertion,Modification,Deletion; IsReadable: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
