### ISSUE TITLE
[Event Request] Codeunit 408 DimensionManagement " OnDimensionManagementOnBeforeIsDefaultDimTable"  

### ISSUE THREAD

**Issue by SWGaswar** [microsoft/ALAppExtensions#17661]
Can we please get the following event?
  ```
  local procedure IsDefaultDimTable(TableID: Integer): Boolean
    var
        IsHandled: Boolean;
    begin
        // Local versions should add exceptions here
```
//Event Request Begin
        IsHandled := false;
        OnDimensionManagementOnBeforeIsDefaultDimTable(TableID, IsHandled);
//Event Request End
```
        if not IsHandled then
        exit(TableID = 0);
    end;

```
 ```
 [IntegrationEvent(false, false)]
    local procedure OnDimensionManagementOnBeforeIsDefaultDimTable(var TableID: Integer; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
