### ISSUE TITLE
[Event Request] Table 37 Sales Line OnBeforeUpdateGlobalDimFromDimSetID

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#17665]
Please add an event in procedure CreateDim:

<pre>
        ...
        "Shortcut Dimension 1 Code" := '';
        "Shortcut Dimension 2 Code" := '';
        GetSalesHeader();
        "Dimension Set ID" :=
          DimMgt.GetRecDefaultDimID(
            Rec, CurrFieldNo, TableID, No, SourceCodeSetup.Sales,
            "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code", SalesHeader."Dimension Set ID", DATABASE::Customer);

        // Event request
        OnBeforeUpdateGlobalDimFromDimSetID(Rec);
        // Event request

        DimMgt.UpdateGlobalDimFromDimSetID("Dimension Set ID", "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");
        ATOLink.UpdateAsmDimFromSalesLine(Rec);

        OnAfterCreateDim(Rec, CurrFieldNo);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateGlobalDimFromDimSetID(var SalesLine: Record "Sales Line")
    begin
    end;
</pre>

**Comment by Oleg-Romashkov** [comment]
Hi,

Is it ok for you to use event OnAfterCreateDim instead of new one?

Rgds,
Oleg.

**Comment by oni1300** [comment]
Hello,

the existing event can not be used due to our business logic, so the requested event is necessary.

Regards
Dietmar

Von: Oleg-Romashkov ***@***.***>
Gesendet: Mittwoch, 11. Mai 2022 15:56
An: microsoft/ALAppExtensions ***@***.***>
Cc: Schulz, Dietmar ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/ALAppExtensions] [Event Request] Table 37 Sales Line OnBeforeUpdateGlobalDimFromDimSetID (Issue #17665)


Hi,

Is it ok for you to use event OnAfterCreateDim instead of new one?

Rgds,
Oleg.
