### ISSUE TITLE
[Event Request] Table 37 Sales Line OnValidateVATProdPostingGroupOnBeforeSetPostingGroup(Rec, IsHandled);

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#17664]
Please add an event in the OnValidate-Trigger of field 90 "VAT Prod. Posting Group" using IsHandled pattern:

<pre>
        field(90; "VAT Prod. Posting Group"; Code[20])
        {
            Caption = 'VAT Prod. Posting Group';
            TableRelation = "VAT Product Posting Group";

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                TestStatusOpen();

                // Event request
                IsHandled := false;
                OnValidateVATProdPostingGroupOnBeforeSetPostingGroup(Rec, IsHandled);
                If IsHandled then
                    exit;
                // Event request

    [IntegrationEvent(false, false)]
    local procedure OnValidateVATProdPostingGroupOnBeforeSetPostingGroup(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;
</pre>

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
