### ISSUE TITLE
Event Request: Codeunit 80 / 90: RunGenJnlPostLine

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/ALAppExtensions#1767]
The methods `RunGenJnlPostLine` in Codeunit 80 / 90 should have a OnBefore and OnAfter event. Just like so:

````
    LOCAL PROCEDURE RunGenJnlPostLine@23(VAR GenJnlLine@1000 : Record 81;SalesHeader@1021100000 : Record 36) : Integer;
    VAR
      Result: Integer;
    BEGIN
      OnBeforePostGenJnlLine(SalesHeader, GenJnlLine);
      Result := GenJnlPostLine.RunWithCheck(GenJnlLine);
      OnAfterPostGenJnlLine(SalesHeader, GenJnlLine, Result);
      EXIT(Result);
    END;

````

Note that the OnAfter-Event also includes the created entry no. and `RunGenJnlPostLine` also gets a reference to `SalesHeader` that is forwarded to both events.

The same pattern should also be applied to Codeunit 90.

**Comment by AlexanderYakunin** [comment]
We alerady have this construction
  OnBeforePostInvPostBuffer(GenJnlLine,InvoicePostBuffer,SalesHeader,SuppressCommit,GenJnlPostLine,PreviewMode);
  GLEntryNo := RunGenJnlPostLine(GenJnlLine,SalesHeader);
  OnAfterPostInvPostBuffer(GenJnlLine,InvoicePostBuffer,SalesHeader,GLEntryNo,SuppressCommit,GenJnlPostLine);

**Comment by AlexanderYakunin** [comment]
Please close if this is ok for you

**Comment by hemisphera** [comment]
OK, didn't check them, my bad. In my case they work, but there are a few other places where the posting of `GenJnlLine` is invoked, and there are no events. Namely:
- `PostICGenJnl` (not needed in my opinion)
- `PostPayment` (might turn out handy)
