### ISSUE TITLE
[Event Request] Codeunit 5632 FA Jnl . -Post Line "OnFAJnlPostLinePostReverseTypes" &OnFAJnlPostLinePostReverseType

### ISSUE THREAD

**Issue by SWGaswar** [microsoft/ALAppExtensions#17672]
Can we please get the following event?
```
procedure PostReverseType(FALedgEntry: Record "FA Ledger Entry")
    var
        EntryAmounts: array[4] of Decimal;
        i: Integer;
    begin
     ```
     //Event Request Begin
        OnFAJnlPostLinePostReverseType();
     //Event Request End

```
        CalculateDisposal.CalcReverseAmounts(FANo, DeprBookCode, EntryAmounts);
        FALedgEntry."FA Posting Category" := FALedgEntry."FA Posting Category"::" ";
        FALedgEntry."Automatic Entry" := true;
     ```
    // Event Request Begin
        OnFAJnlPostLinePostReverseTypes();
    // Event Request Begin
```
        for i := 1 to 4 do
            if EntryAmounts[i] <> 0 then begin
                FALedgEntry.Amount := EntryAmounts[i];
                FALedgEntry."FA Posting Type" := "FA Ledger Entry FA Posting Type".FromInteger(CalculateDisposal.SetReverseType(i));
                FAInsertLedgEntry.InsertFA(FALedgEntry);
                if FALedgEntry."G/L Entry No." > 0 then
                    FAInsertLedgEntry.InsertBalAcc(FALedgEntry);
            end;
    end;
```
```
 [IntegrationEvent(false, false)]
    local procedure OnFAJnlPostLinePostReverseType()
    begin
    end;
```

  ```
  [IntegrationEvent(false, false)]
    local procedure OnFAJnlPostLinePostReverseTypes()
    begin
    end;
```

**Comment by Oleg-Romashkov** [comment]
Hi,

Requested events do not have parameters. Could you please clarify what is the scenario of using those events?

Rgds,
Oleg.

**Comment by SWGaswar** [comment]
Hi Oleg,

As per the below comment, I want to confirm you that we don't required any parameters in the publisher. We are using this publisher to call our customized global procedure.

Thanks,
SWGswar.

**Comment by Oleg-Romashkov** [comment]
Hi SWGswar,

Could you please describe the scenario of using those events?

Is it enough to have only first event to call your global procedures?

Rgds,
Oleg.

**Comment by SWGaswar** [comment]
Hi Oleg,

It's enough to have only the first event to call our global procedure, Could you please proceed further.

Thanks,
SWGswar.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
