### ISSUE TITLE
CU1380 OnVerifyRecord Event

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/ALAppExtensions#1768]
I have a business case where some customers only want to be invoiced for Sales Orders at month end.  This prevents them from receiving an invoice for each partial shipment during the month.  

Batch Post Sales Orders (R296) passes the RequestPage parameters to CU1371 Sales Batch Post Mgt. RunBatch function which sets the parameters for Batch Processing Mgt. CU1380.  As this is on premise I can deal with adding field on the RequestPage.  These parameters are used in various places but there is no means to access them from the OnVerifyRecord function which is where I would determine whether the current Sales Order should be invoiced.

1) It would be great if we could extend a RequestPage in a report.
2) It would nice to be able to set additional parameters in some sort of event with the RunBatch function is run.
3) Can the OnVerifyRecord event signature be changed so that I can access the Parameter set for the BatchID/RecordID?  Or can another event be added to the CanProcess function with the required information?
4) Is there another event driven solution to this issue?  Have I missed something?

**Comment by StanPesotskiy** [comment]
1. Request Pages are not extendable yet. As a workaround, you can copy the existing report, rename it and customise, then extend pages or other code that calls the original report to replace it with yours.
3. We can add new parameters to the end of the existing event; we can add VAR to event parameters.
The best way to get something from us is to implement your customisation on events, verify that these events work for you and then request them here by including pieces of code that would not cause us guessing.
