### ISSUE TITLE
[Event Request] Codeunit 99000837 - Prod. Order Line-Reserve - OnAfterDeleteReservEntries

### ISSUE THREAD

**Issue by SchoKa** [Microsoft/ALAppExtensions#1769]
Hello AL-Team,
 please add the following Publisher in function "DeleteLine":

[External] DeleteLine(VAR ProdOrderLine : Record "Prod. Order Line")
[ … ]
  ReservMgt.DeleteReservEntries(TRUE,0);
  // >> New
  OnAfterDeleteReservEntries(ProdOrderLine);
  // << New
  ReservMgt.ClearActionMessageReferences;
[ … ]
Publisher definition currently used by us
 IncludeSender: false
 GlobaVarAccess: false
LOCAL [IntegrationEvent] OnAfterDeleteReservEntries(VAR ProdOrderLine : Record "Prod. Order Line")

**Comment by NKarolak** [comment]
Note: created as OnDeleteLineOnAfterDeleteReservEntries
