### ISSUE TITLE
[Event Request] Codeunit 5900 ServOrderManagement "OnServOrderMgtOnBeforeCalcServItemDates"

### ISSUE THREAD

**Issue by SWGaswar** [microsoft/ALAppExtensions#17737]
Can we please get the following event?
```
    procedure CalcServItemDates(var ServHeader: Record "Service Header"; ServItemNo: Code[20])
    var
        ServItem: Record "Service Item";
        IsHandled: Boolean;
    begin
        if ServItem.Get(ServItemNo) then begin
```
    //Event Request Begin
            IsHandled := false;
            OnServOrderMgtOnBeforeCalcServItemDates(ServHeader, ServItem, IsHandled);
            if not IsHandled then begin
     //Event Request End
```
            if ServHeader."Finishing Date" <> 0D then
                ServItem."Last Service Date" := ServHeader."Finishing Date"
            else
                ServItem."Last Service Date" := ServHeader."Posting Date";
            ServItem.Modify();
        end;
```
      //Event Request Begin
    end;
    //Event Request End
```
    end;
```
```
   [IntegrationEvent(false, false)]
    local procedure OnServOrderMgtOnBeforeCalcServItemDates(var ServHeader: Record "Service Header"; var ServItem: Record "Service Item"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
