### ISSUE TITLE
[Event Request] Codeunit 5922 Serv-Quote to Order (Yes/No) "OnSerViceQuoteToOrderOnRunYesNo"&"OnServQuoteToOrderYesorNoOnBeforeOnRun"

### ISSUE THREAD

**Issue by SWGaswar** [microsoft/ALAppExtensions#17732]
Can we please get the following event?
```
 trigger OnRun()
    var
        ConfirmManagement: Codeunit "Confirm Management";
        HideMessage: Boolean;
        IsHandled: Boolean;
    begin
        Rec.TestField("Document Type", Rec."Document Type"::Quote);
```
      //Event Request Begin
        IsHandled := false;
        OnSerViceQuoteToOrderOnRunYesNo(IsHandled);
        if not IsHandled then begin
     //Event Request End
```
        Rec.TestField("Customer No.");
        Rec.TestField("Bill-to Customer No.");
        if not ConfirmManagement.GetResponseOrDefault(Text000, true) then
            exit;
```
      //Event Request Begin
        end;
    //Event Request End
```

```
    //Event Request Begin
        IsHandled := false;
        OnServQuoteToOrderYesorNoOnBeforeOnRun(IsHandled);
        if not IsHandled then begin
    //Event Request End
```
        ServQuoteToOrder.Run(Rec);

        OnBeforeShowMessage(Rec, ServQuoteToOrder.ReturnOrderNo(), HideMessage);
        if not HideMessage then
            Message(Text001, Rec."No.", ServQuoteToOrder.ReturnOrderNo());
```
    //Event Request Begin
    end;
    //Event Request End
```
```
```
 [IntegrationEvent(false, false)]
    local procedure OnSerViceQuoteToOrderOnRunYesNo(var IsHandled: Boolean)
    begin
    end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnServQuoteToOrderYesorNoOnBeforeOnRun(var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
