### ISSUE TITLE
[Event Request] Codeunit 416 Release Service Document "OnReleaseServiceDocumentPerformManualReopen"

### ISSUE THREAD

**Issue by SWGaswar** [microsoft/ALAppExtensions#17743]
Can we please get the following event?
```
 procedure PerformManualReopen(var ServHeader: Record "Service Header")
    begin
      //Event Request Begin
        OnReleaseServiceDocumentPerformManualReopen(ServiceHeader);
     //Event request End

        Reopen(ServHeader);
    end;
```
```
 local procedure OnReleaseServiceDocumentPerformManualReopen(var ServiceHeader: Record "Service Header")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
