### ISSUE TITLE
[Event Request] Codeunit 99000830 - Create Reserv. Entry - OnAfterSplitReservEntry

### ISSUE THREAD

**Issue by SchoKa** [Microsoft/ALAppExtensions#1774]
Hello AL-Team,
 please add the following Publisher in function "CreateEntry":

[External] CreateEntry(ItemNo : Code[20];VariantCode : Code[10];LocationCode : Code[10];Description : Text[50];ExpectedReceiptDate : Date;ShipmentDate : Date;TransferredFromEntryNo : Integer;Status : 'Reservation,Tracking,Surplus,Prospect')
[ … ]
    OnBeforeReservEntryInsertNonSurplus(ReservEntry2);
    ReservEntry2.INSERT;
    // >> New
    OnAfterSplitReservEntry(ReservEntry, ReservEntry2);
    // << New
  END;
END;

LastReservEntry := ReservEntry;
[ … ]
Publisher definition currently used by us
 IncludeSender: false
 GlobaVarAccess: false
LOCAL [IntegrationEvent] OnAfterSplitReservEntry(ReservEntry : Record "Reservation Entry";ReservEntry2 : Record "Reservation Entry")

**Comment by NKarolak** [comment]
Note: created as 
`OnAfterReservEntryInsertNonSurplus(ReservEntry2,ReservEntry);`
