### ISSUE TITLE
[Event Request] Table 5901 Service Item Line "OnServiceItemLineSetHideDialogBox"  

### ISSUE THREAD

**Issue by dgoyalaptean** [microsoft/ALAppExtensions#17761]
Can we please get the following event?
```
 procedure SetHideDialogBox(DialogBoxVar: Boolean)
    begin
        HideDialogBox := DialogBoxVar;

      //Event request begin
        OnServiceItemLineSetHideDialogBox(HideDialogBox);  
        //Event request end
    end;
```

   ```
 [IntegrationEvent(false, false)]
    local procedure OnServiceItemLineSetHideDialogBox(var HideDialogBox: Boolean)
    begin
   
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
