### ISSUE TITLE
[Event Request] Codeunit 904 - Whse.-Assembly Release - OnBeforeCreateWhseRqst

### ISSUE THREAD

**Issue by cosmo-skol** [Microsoft/ALAppExtensions#1777]
Hello AL-Team,
we need a new publisher to set custom fields:

Function LOCAL CreateWhseRqst(VAR AssemblyHeader : Record "Assembly Header";VAR AssemblyLine : Record "Assembly Line")

```
GetLocation(Location,AssemblyLine."Location Code");
// >> #AMPW111.00.01:T101
OnBeforeCreateWhseRqst(AssemblyHeader, AssemblyLine, Location);
// << #AMPW111.00.01:T101
IF NOT Location."Require Pick" THEN
  EXIT;

[...]
```

Publisher definition:
LOCAL [IntegrationEvent] OnBeforeCreateWhseRqst(VAR AssemblyHeader : Record "Assembly Header";VAR AssemblyLine : Record "Assembly Line";VAR Location : Record Location)

Publisher properties:
IncludeSender: FALSE
GlobaVarAccess: FALSE

**Comment by NKarolak** [comment]
Note: implemented in BC15 as
`local procedure OnBeforeCreateWhseRqst(AssemblyHeader: Record "Assembly Header"; AssemblyLine: Record "Assembly Line"; var Location: Record Location)`
