### ISSUE TITLE
[Event Request] Codeunit 904 - Whse.-Assembly Release - OnBeforeDeleteWhseRqst

### ISSUE THREAD

**Issue by cosmo-skol** [Microsoft/ALAppExtensions#1778]
Hello AL-Team,
we need a new publisher to set custom fields:

Function [External] DeleteLine(AssemblyLine : Record "Assembly Line")

```
[...]
    REPEAT
      IF (NOT AssemblyLine2.CompletelyPicked) OR
         (NOT (Location."Require Pick" AND Location."Require Shipment"))
      THEN
        KeepWhseRqst := TRUE; // if lines are incompletely picked.
    UNTIL (AssemblyLine2.NEXT = 0) OR KeepWhseRqst;

  // >> NEW
  OnBeforeDeleteWhseRqst(AssemblyLine2, KeepWhseRqst);
  // << NEW

  IF NOT KeepWhseRqst THEN BEGIN
    IF Location."Require Shipment" THEN
      DeleteWhsePickRqst(AssemblyLine,FALSE)
    ELSE
      DeleteWhseRqst(AssemblyLine,FALSE);
[...]
```

Publisher definition:
LOCAL [IntegrationEvent] OnBeforeDeleteWhseRqst(VAR AssemblyLine : Record "Assembly Line";VAR KeepWhseRqst : Boolean)

Publisher properties:
IncludeSender: FALSE
GlobaVarAccess: FALSE

**Comment by NKarolak** [comment]
Note: implemented as
- **OnDeleteLine**OnBeforeDeleteWhseRqst in BC 14.4
- OnBeforeDeleteWhseRqst in BC 15
