### ISSUE TITLE
[Event Expansion Request] Codeunit 5704 - TransferOrder-Post Shipment - OnCheckTransLine

### ISSUE THREAD

**Issue by cosmo-skol** [Microsoft/ALAppExtensions#1779]
Hello AL-Team,
we need the publisher expanded to perform additional tests:

Function OnRun(VAR Rec : Record "Transfer Header")

```
[...]
      IF TransLine."Item No." <> '' THEN BEGIN
        Item.GET(TransLine."Item No.");
        Item.TESTFIELD(Blocked,FALSE);
      END;
      // >> NEW
      // OnCheckTransLine(TransLine);
      OnCheckTransLine(TransLine, WhseShip);
      // << NEW

      InsertTransShptLine(TransShptHeader);

[...]
```

Publisher definition:
Current	: LOCAL [IntegrationEvent] OnCheckTransLine(TransferLine : Record "Transfer Line")
New		: LOCAL [IntegrationEvent] OnCheckTransLine(VAR TransLine : Record "Transfer Line";WhseShip : Boolean)

Publisher properties:
IncludeSender: FALSE
GlobaVarAccess: FALSE

**Comment by NKarolak** [comment]
Note: implemented as
`local procedure OnCheckTransLine(TransferLine: Record "Transfer Line"; WhseShip: Boolean)`
