### ISSUE TITLE
External Function required in CodeUnit 231 

### ISSUE THREAD

**Issue by AmolSalvi** [Microsoft/ALAppExtensions#178]
Hi,

We need to have external function (or maybe event) for setting preview mode. This will be useful when you can call your own report by using posting preview.

Or for using this functionality you need to copy this code unit for simple Boolean variable.

Regards
Amol

**Comment by DuttaSoumya** [comment]
Let me confirm that this will be part of the next release.

**Comment by AmolSalvi** [comment]
Whether this will be part of CU or Major release ?

**Comment by JesperSchulz** [comment]
Both minor and major. We are backporting the fix pack.

**Comment by AmolSalvi** [comment]
I was expecting this function in CU02 of business central .but it is still not there.
