### ISSUE TITLE
[Event Request] Codeunit 5704 - TransferOrder-Post Shipment - OnAfterModifyTransLine

### ISSUE THREAD

**Issue by cosmo-skol** [Microsoft/ALAppExtensions#1780]
Hello AL-Team,
we need a new publisher to perform additional actions:

Function OnRun(VAR Rec : Record "Transfer Header")

```
[...]
      TransLine.UpdateWithWarehouseShipReceive;
      TransLine.MODIFY;
      // >> NEW
      OnAfterModifyTransLine(TransLine);
      // << NEW
    UNTIL TransLine.NEXT = 0;
[...]
```

Publisher definition:
LOCAL [IntegrationEvent] OnAfterModifyTransLine(VAR TransLine : Record "Transfer Line")

Publisher properties:
IncludeSender: FALSE
GlobaVarAccess: FALSE

**Comment by NKarolak** [comment]
Note: added as OnAfterTransLineModify
