### ISSUE TITLE
[Event Request] Codeunit 5770 - Whse.-Service Release - OnAfterCreateWhseRqst

### ISSUE THREAD

**Issue by cosmo-skol** [Microsoft/ALAppExtensions#1782]
Hello AL-Team,
we need a new publisher to create additional records:

Function [External] Release(ServiceHeader : Record "Service Header")

```
[...]
    REPEAT
      IF ("Document Type" = "Document Type"::Order) AND (ServiceLine.Quantity >= 0) THEN
        WhseType := WhseType::Outbound
      ELSE
        WhseType := WhseType::Inbound;

      IF First OR (ServiceLine."Location Code" <> OldLocationCode) OR (WhseType <> OldWhseType) THEN
        CreateWhseRqst(ServiceHeader,ServiceLine,WhseType);

      // >> NEW
      OnAfterCreateWhseRqst(ServiceLine,ServiceHeader,WhseType);
      // << NEW

      First := FALSE;
      OldLocationCode := ServiceLine."Location Code";
      OldWhseType := WhseType;
    UNTIL ServiceLine.NEXT = 0;
[...]
```

Publisher definition:
LOCAL [IntegrationEvent] OnAfterCreateWhseRqst(VAR ServiceLine : Record "Service Line";VAR ServiceHeader : Record "Service Header";WhseType : 'Inbound,Outbound')

Publisher properties:
IncludeSender: FALSE
GlobaVarAccess: FALSE

**Comment by NKarolak** [comment]
Note: added as
`LOCAL [IntegrationEvent] OnAfterCreateWhseRqst(VAR ServiceHeader : Record "Service Header";VAR ServiceLine : Record "Service Line";WhseType : Option)`
