### ISSUE TITLE
[Event Request] Table 5900 Service Header "OnAfterServiceHeaderSetValidatingFromLines"

### ISSUE THREAD

**Issue by SWGaswar** [microsoft/ALAppExtensions#17824]
Can we please get the following event?
```
   procedure SetValidatingFromLines(NewValidatingFromLines: Boolean)
    begin
        ValidatingFromLines := NewValidatingFromLines;
```
      //Event Request Begin
        OnAfterServiceHeaderSetValidatingFromLines(Rec, ValidatingFromLines) 
     //Event Request End
```
    end;
```
```
   [IntegrationEvent(false, false)]
    local procedure OnAfterServiceHeaderSetValidatingFromLines(var Rec: Record "Service Header"; var ValidatingFromLines: Boolean) 
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
