### ISSUE TITLE
[Event Request] CodeUnit 5988 Serv-Documents Mgt. "OnMakeInvtAdjustmentOnServDocCodeunit"

### ISSUE THREAD

**Issue by SWGaswar** [microsoft/ALAppExtensions#17835]
Can we please get the following event?
```
    local procedure MakeInvtAdjustment()
    var
        InvtSetup: Record "Inventory Setup";
        InvtAdjmtHandler: Codeunit "Inventory Adjustment Handler";
    begin
        InvtSetup.Get();
        if InvtSetup.AutomaticCostAdjmtRequired() then begin
            InvtAdjmtHandler.MakeInventoryAdjustment(true, InvtSetup."Automatic Cost Posting");
```
      //Event Request Begin
            OnMakeInvtAdjustmentOnServDocCodeunit(InvtSetup, ServHeader);  
     //Event Request End
```
        end;
    end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnMakeInvtAdjustmentOnServDocCodeunit(var InvtSetup: Record "Inventory Setup"; var ServHeader: Record "Service Header")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
