### ISSUE TITLE
[Event Request] Codeunit 99000787 - Create Prod. Order Lines - OnBeforeCopyFromSalesOrder

### ISSUE THREAD

**Issue by SchoKa** [Microsoft/ALAppExtensions#1783]
Hello AL-Team,
we need a new publisher in function CopyFromSalesOrder:

```
LOCAL CopyFromSalesOrder(SalesHeader : Record "Sales Header";CurrLineNo : Integer) : Boolean
// >> New
OnBeforeCopyFromSalesOrder(SalesLine,CurrLineNo);
// << New

SalesLine.SETRANGE("Document Type",SalesHeader."Document Type");
SalesLine.SETRANGE("Document No.",SalesHeader."No.");
IF SalesLine.FINDSET THEN
  REPEAT
```
Publisher definition:
LOCAL [IntegrationEvent] OnBeforeCopyFromSalesOrder(VAR SalesLine : Record "Sales Line";VAR CurrLineNo : Integer)

Publisher properties:
IncludeSender: FALSE
GlobaVarAccess: FALSE

**Comment by AlexanderYakunin** [comment]
We do not have parameter CurrLineNo in CopyFromSalesOrder in our code. Please update you ask.
