### ISSUE TITLE
[Event Request] Add new Event in local procedure FindPurchRcptHeader in standard page 344 "Navigate"

### ISSUE THREAD

**Issue by margolui** [microsoft/ALAppExtensions#17849]
Hello.
Need new Event in local procedure FindPurchRcptHeader in standard page 344 "Navigate"

The version of AL Language v9.0.605172
US Business Central 19.5 (Platform 19.0.36528.37760 + Application 19.5.36567.37808)

Function:

`

	   local procedure FindPurchRcptHeader()
    begin
        if PurchRcptHeader.ReadPermission() then begin
            PurchRcptHeader.Reset();
            PurchRcptHeader.SetFilter("No.", DocNoFilter);
            PurchRcptHeader.SetFilter("Posting Date", PostingDateFilter);
            InsertIntoDocEntry(Rec, DATABASE::"Purch. Rcpt. Header", PostedPurchaseReceiptTxt, PurchRcptHeader.Count);
		OnAfterInsertIntoPurchRcptDocEntry(Rec, PurchRcptHeader, DocNoFilter, PostingDateFilter);
        end;
    end;

`
signature

`

    [IntegrationEvent(false, false)]
    OnAfterInsertIntoPurchRcptDocEntry(var DocEntry: Record "Document Entry";
var PurchRcptHeader: Record ''Purch. Rcpt. Header", DocNoFilter: Text, PostingDateFilter: Text; )
    begin
    end;
`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
