### ISSUE TITLE
[Event Request] C90 OnBeforeUpdPostingDescriptionOnInvoice

### ISSUE THREAD

**Issue by SandroKiedis** [Microsoft/ALAppExtensions#1784]
Hi

We need the possibility to post our own Posting Descriptions, so we would be happy about the following change:
![image](https://user-images.githubusercontent.com/47424839/54812855-6e3af200-4c8c-11e9-8876-c1fb8b8907ce.png)

The same event should be in the same function in CU80 as well.

**Comment by AlexanderYakunin** [comment]
We don't have this code in latest version, please check you request
