### ISSUE TITLE
[Event Change Request] codeunit 7322 "Create Inventory Pick/Movement" - OnCreatePickOrMoveLineOnAfterFindTakeQtyForBinCodeOfSourceLine

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17851]
Could you please fix the event signature of the event `OnCreatePickOrMoveLineOnAfterFindTakeQtyForBinCodeOfSourceLine`? That it is implement as requested (https://github.com/microsoft/ALAppExtensions/issues/17198)?
We need the parameter `RemQtyToPickBase` and 
you are calling the event with this parameter,
 >  OnCreatePickOrMoveLineOnAfterFindTakeQtyForBinCodeOfSourceLine(NewWhseActivLine, WhseItemTrackingSetup, RemQtyToPickBase);

 but the event parameters' name is `ITQtyToPickBase`.
> local procedure OnCreatePickOrMoveLineOnAfterFindTakeQtyForBinCodeOfSourceLine(var NewWarehouseActivityLine: Record "Warehouse Activity Line"; WhseItemTrackingSetup: Record "Item Tracking Setup"; **var ITQtyToPickBase: Decimal**)

Therefore I'm asking for fixing this "Typo" that you could lead to misunderstandings.

And could could you please add the `WarehouseActivityHeader: Record "Warehouse Activity Header";` to the event OnCreatePickOrMoveLineOnAfterFindTakeQtyForBinCodeOfSourceLine?

```al
local procedure CreatePickOrMoveLine(NewWhseActivLine: Record "Warehouse Activity Line"; var RemQtyToPickBase: Decimal; OutstandingQtyBase: Decimal; ReservationExists: Boolean)
...
if Location."Bin Mandatory" then begin
    // find Take qty. for bin code of source line
    if (RemQtyToPickBase > 0) and
        (NewWhseActivLine."Bin Code" <> '') and
        (not IsInvtMovement or IsBlankInvtMovement) and
        (not HasExpiredItems)
    then
        InsertPickOrMoveBinWhseActLine(
            NewWhseActivLine, NewWhseActivLine."Bin Code", false, RemQtyToPickBase, WhseItemTrackingSetup);

//+Change
//-    OnCreatePickOrMoveLineOnAfterFindTakeQtyForBinCodeOfSourceLine(NewWhseActivLine, WhseItemTrackingSetup, RemQtyToPickBase);
OnCreatePickOrMoveLineOnAfterFindTakeQtyForBinCodeOfSourceLine(NewWhseActivLine, WhseItemTrackingSetup, RemQtyToPickBase, RemQtyToPickBase, WhseActivHeader);
//-Change

    // Invt. movement without document has to be created
    if IsBlankInvtMovement then
        RemQtyToPickBase := 0;

    // find Take qty. for default bin
    if (RemQtyToPickBase > 0) and (not HasExpiredItems) then
        InsertPickOrMoveBinWhseActLine(NewWhseActivLine, '', true, RemQtyToPickBase, WhseItemTrackingSetup);

    // find Take qty. for other bins
    if (RemQtyToPickBase > 0) and (not HasExpiredItems) then
        InsertPickOrMoveBinWhseActLine(NewWhseActivLine, '', false, RemQtyToPickBase, WhseItemTrackingSetup)
end else
    if (RemQtyToPickBase > 0) and (not HasExpiredItems) then
        InsertShelfWhseActivLine(NewWhseActivLine, RemQtyToPickBase, WhseItemTrackingSetup);
....

```
//NEW EVENT Signature
```al
[IntegrationEvent(false, false)]
local procedure OnCreatePickOrMoveLineOnAfterFindTakeQtyForBinCodeOfSourceLine(vvar NewWarehouseActivityLine: Record "Warehouse Activity Line"; WhseItemTrackingSetup: Record "Item Tracking Setup"; var ITQtyToPickBase: Decimal; var RemQtyToPickBase: Decimal; WarehouseActivityHeader: Record "Warehouse Activity Header")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40825.
