### ISSUE TITLE
[Event Request] Codeunit 1008 "Job Calculate Statistics" - Extend OnAfterJTCalculateCommonFilters

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#17868]
To allow for modification of filters on global variables **JobLedgEntry** and **JobPlanningLine**, please add them to the event OnAfterJTCalculateCommonFilters() in Codeunit 1008 "Job Calculate Statistics":

```
procedure JTCalculateCommonFilters(var JT2: Record "Job Task"; var Job2: Record Job; UseJobFilter: Boolean)
var
    JT: Record "Job Task";
begin
    [...]

    OnAfterJTCalculateCommonFilters(JT, JT2, Job2, UseJobFilter, JobLedgEntry, JobPlanningLine);
end;
```
The extended event:
```
[IntegrationEvent(false, false)]
local procedure OnAfterJTCalculateCommonFilters(JobTask: Record "Job Task"; var JobTask2: Record "Job Task"; var Job2: Record Job; UseJobFilter: Boolean; var JobLedgEntry: Record "Job Ledger Entry"; var JobPlanningLine: Record "Job Planning Line")
begin
end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
