### ISSUE TITLE
[Event Request] Codeunit 1008 "Job Calculate Statistics" - Extend OnAfterJobCalculateCommonFilters

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#17867]
To allow for modification of filters on global variables **JobLedgEntry** and **JobPlanningLine**, please add them to the event OnAfterJobCalculateCommonFilters() in Codeunit 1008 "Job Calculate Statistics":

```
procedure JobCalculateCommonFilters(var Job: Record Job)
begin
    [...]

    OnAfterJobCalculateCommonFilters(Job, JobLedgEntry, JobPlanningLine);
end;
```
The extended event:
```
[IntegrationEvent(false, false)]
local procedure OnAfterJobCalculateCommonFilters(var Job: Record Job; var JobLedgEntry: Record "Job Ledger Entry"; var JobPlanningLine: Record "Job Planning Line")
begin
end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
