### ISSUE TITLE
[Event Request] table 81 "Gen. Journal Line" - OnAfterCleanLine

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#17873]
We would like to request and event on the function Cleanline from the the table  "Gen. Journal Line". We would like to clean up custom fields after cleaning up the standard BC fields.

    local procedure CleanLine()
    begin
        UpdateLineBalance;
        UpdateSource;
        CreateDimFromDefaultDim(0);
        if not ("Bal. Account Type" in ["Bal. Account Type"::Customer, "Bal. Account Type"::Vendor]) then
            "Recipient Bank Account" := '';
        if xRec."Account No." <> '' then begin
            ClearPostingGroups;
            "Tax Area Code" := '';
            "Tax Liable" := false;
            "Tax Group Code" := '';
            "Bill-to/Pay-to No." := '';
            "Ship-to/Order Address Code" := '';
            "Sell-to/Buy-from No." := '';
            UpdateCountryCodeAndVATRegNo('');
        end;

        case "Account Type" of
            "Account Type"::"G/L Account":
                UpdateAccountID;
            "Account Type"::Customer:
                UpdateCustomerID;
            "Account Type"::"Bank Account":
                UpdateBankAccountID;
        end;

        OnAfterCleanLine(Rec, xRec); // New Event
    end;
    
    
    
    
        [IntegrationEvent(false, false)]
    local procedure OnAfterCleanLine(var Rec: Record "Gen. Journal Line"; var xRec: Record "Gen. Journal Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
