### ISSUE TITLE
[Event-Request] Table 36 "Sales Header" - OnBeforeLookupSellToCity

### ISSUE THREAD

**Issue by JerryTyssen** [microsoft/ALAppExtensions#17876]
Hello,

We would like to request the addition of the event OnBeforeLookupSellToCity(Rec, PostCode) in procedure OnLookup() of field(83; "Sell-to City"; Text[30]) in Table 36 "Sales Header":

trigger OnLookup()
begin
++  OnBeforeLookupSellToCity(Rec, PostCode);
  PostCode.LookupPostCode("Sell-to City", "Sell-to Post Code", "Sell-to County", "Sell-to Country/Region Code");
end;
            
```
[IntegrationEvent(false, false)]
local procedure OnBeforeLookupSellToCity(var SalesHeader: Record "Sales Header"; var PostCodeRec: Record "Post Code")
begin
end;
```
    
Note: some other fields already have this event, like "Ship-to City" and also have the "OnAfterLookupShipToCity" event present. Maybe this event can be added as well?

Note 2: Similar request for another field requested in https://github.com/microsoft/ALAppExtensions/issues/17875

Thanks in advance,
Jerry Tyssen
Cegeka

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
