### ISSUE TITLE
[Feature Request] Add table "Activity Log" to retention policy allowed tables

### ISSUE THREAD

**Issue by JPicard90** [microsoft/ALAppExtensions#17874]
hi
could be userful to add "Activity Log" (710)  to table 3903 "Retention Policy Allowed Table"
i suggest to add this lines in codeunit 3999 inside funcion "AddAllowedTables"

```
        if not UpgradeTag.HasUpgradeTag(GetRetenActLogTableUpgradeTag()) then begin
            RetenPolAllowedTables.AddAllowedTable(Database::"Activity Log");
            CreateRetentionPolicySetup(Database::"Activity Log", CreateOneMonthRetentionPeriod());
            UpgradeTag.SetUpgradeTag(GetRetenActLogTableUpgradeTag());
        end;
```

and this inside codeunit 3999

```
    local procedure GetRetenActLogTableUpgradeTag(): Code[250]
    begin
        exit('MS-378964-RetenActLogTable-20220509'); // TAG TBD
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41407.
