### ISSUE TITLE
[Event Request] table 11000003 "Detail Line" - OnBeforeFillVendorDescription

### ISSUE THREAD

**Issue by alinat2022** [microsoft/ALAppExtensions#17887]
Hello,

In table "Detail Line", procedure FillVendorDescription, there is an event we would like to use. But it is missing the IsHandled parameter. Can you please correct it?

    local procedure FillVendorDescription(var CompanyInformation: Record "Company Information"; var Vendor: Record Vendor)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeFillVendorDescription(Rec, Vendor, VendLedgEntry, IsHandled); //<<IsHandled parameter>>
        if IsHandled then
            exit;

Thank you,

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
