### ISSUE TITLE
[Request for External] table 11000003 "Detail Line" - vars CustLedgEntry and VendLedgEntry

### ISSUE THREAD

**Issue by alinat2022** [microsoft/ALAppExtensions#17886]
Hello,

In the GitHub issue  #16983, two variables were requested to be made protected:
```
    protected var
        CustLedgEntry: Record "Cust. Ledger Entry";
        VendLedgEntry: Record "Vendor Ledger Entry";
```

In BC version 20.1.39959.0, we see this request has not yet been solved.

Can you please take a look at it?

Thank you.

**Comment by AlexanderYakunin** [comment]
We do not make external requests for minor versions, we only do it for major one. If you need this for minor, please request this via technical support ticket.
