### ISSUE TITLE
Table 458 "Overdue Approval Entry" - Function ShowRecord - missing line 

### ISSUE THREAD

**Issue by DanielBalanCgk** [microsoft/ALAppExtensions#17880]
It seems that in the following ticket [https://github.com/microsoft/ALAppExtensions/issues/12774](url), an event was requested but also a line of code before opening the page (RecRef.SetRecFilter;).

The fix was announced to be implemented in the next major release, but it was only implemented partially, line for RecRef.SetRecFilter was omitted.

    procedure ShowRecord()
    var
        RecRef: RecordRef;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeShowRecord(Rec, IsHandled);
        if IsHandled then
            exit;

        if not RecRef.Get("Record ID to Approve") then
            exit;
        RecRef.SetRecFilter;    <-------
        PageManagement.PageRun(RecRef);
    end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 40826.
