### ISSUE TITLE
[Event Request] Codeunit 5700 User Setup Management

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#17881]
Please extend the Event OnAfterGetServiceFilter with parameter UserLocation:
```OnAfterGetServiceFilter(UserSetup, UserLocation, ServUserRespCenter);```
```
[IntegrationEvent(false, false)]
local procedure OnAfterGetServiceFilter(var UserSetup: Record "User Setup"; var UserLocation: Code[10]; var UserRespCenter: Code[10])
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
