### ISSUE TITLE
[Scope Change] codeunit 12 "Gen. Jnl.-Post Line", procedures IsGLEntryInconsistent, ShowInconsistentEntries

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#17883]
Could you please make the mentioned two methods "visible"?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
