### ISSUE TITLE
[Event Request] Codeunit 5705 add parameters on event OnBeforeCreatePostedRcptLineFromWhseRcptLine

### ISSUE THREAD

**Issue by calliopedavidroldan** [microsoft/ALAppExtensions#17898]
Hi,

We need to add the parameters  WhsePostRcpt and TempItemEntryRelation2 on event OnBeforeCreatePostedRcptLineFromWhseRcptLine called on procedure  CreatePostedRcptLineFromWhseRcptLine :

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreatePostedRcptLineFromWhseRcptLine(var TransRcptLine: Record "Transfer Receipt Line"; var WhseRcptLine: Record "Warehouse Receipt Line"; var PostedWhseRcptHeader: Record "Posted Whse. Receipt Header"; var PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; var TempWhseSplitSpecification: Record "Tracking Specification" temporary; var IsHandled: Boolean; var WhsePostRcpt: Codeunit "Whse.-Post Receipt"; var TempItemEntryRelation2: Record "Item Entry Relation" temporary)
    begin
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
