### ISSUE TITLE
[Extensibility enhancements] Codeunit 5348 "CRM Quote to Sales Quote"

### ISSUE THREAD

**Issue by left-code** [microsoft/ALAppExtensions#17896]
In function **CreateOrUpdateSalesQuoteLines** Sales Line should be inserted with OnInsert trigger:

 ```
        if CRMQuotedetail.FindSet() then begin
            repeat
                InitializeSalesQuoteLine(CRMQuotedetail, SalesHeader, SalesLine);
                SalesLine.Insert(TRUE); // here should be added insert with OnInsert trigger
                if SalesLine."Qty. to Assemble to Order" <> 0 then
                    SalesLine.Validate("Qty. to Assemble to Order");
            until CRMQuotedetail.Next() = 0;
        end else begin
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41235.
