### ISSUE TITLE
[Event Request] Codeunit 80 add parameter SalesHeader on event OnBeforePostUpdateOrderLineModifyTempLine

### ISSUE THREAD

**Issue by calliopedavidroldan** [microsoft/ALAppExtensions#17897]
Hi,

We need to add the parameter SalesHeader on event OnBeforePostUpdateOrderLineModifyTempLine called on procedure PostUpdateOrderLine :

  ```
  [IntegrationEvent(false, false)]
    local procedure OnBeforePostUpdateOrderLineModifyTempLine(var TempSalesLine: Record "Sales Line" temporary; WhseShip: Boolean; WhseReceive: Boolean; CommitIsSuppressed: Boolean; var IsHandled: Boolean; SalesHeader: Record "Sales Header")
    begin
```
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
