### ISSUE TITLE
Controls and Action with missing names in the Base Application

### ISSUE THREAD

**Issue by pzentner** [Microsoft/ALAppExtensions#179]
Currently, a lot of the stock objects have control and action names that are default (ControlXXX and ActionXXX). This is extremely difficult to extend those when you have to have the old dev environment open to find the name of the proper action or control that you want to define in "addafter()". I know, this is a big task, but it would be great, if those could be renamed with meaningful names.

Granted, those layout changes could be done via the InClient designer, but it is really easy to make "mass changes" by copying and pasting text blocks in the different files, but you don't know, if - for whatever reason - the Control ID is different in a particular object.

**Comment by JesperSchulz** [comment]
We are aware and actively working on generic soltutions for this. If you need immediate fixes for smaller issues, please log them in this repo and we will turn them around instantly. Closing this issue, as we won't report progress back on the generic solution here.
