### ISSUE TITLE
[Event Request] - table 167 Job - OnAfterUpdateBillToContact

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17908]
procedure UpdateBillToContact(CustomerNo: Code[20])
    begin
        GetCustomerContact(CustomerNo, Rec."Bill-to Contact No.", Rec."Bill-to Contact");

        OnAfterUpdateBillToContact(Rec, xRec); //A108F0013.Event20.00
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateBillToContact(var Job: Record Job; xJob: Record Job)
    begin
        //A108F0013.Event20.00
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
