### ISSUE TITLE
Report 402: Purchase Document - Test ~ direct posting check for system created entry

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#17905]
There is a difference in the check on direct posting between the validation of the No. field on the purchase line and the function "CheckPurchLine" in the report 402 Purchase Document - Test.

**For the purchase line:**
In case the document type = "G/L Account" and when i validate the No. field on the purchase line with a GL Account. The direct posting is only checked in case the Purchase lines is not a System-Created Entry. 

    local procedure CopyFromGLAccount()
    begin
        GLAcc.Get("No.");
        GLAcc.CheckGLAcc;
        if not "System-Created Entry" then
            GLAcc.TestField("Direct Posting", true);

However in the report Purchase Document - Test in the function "CheckPurchLine" the direct posting is always checked no matter if it is a system-created entry or not.

        with PurchaseLine do
            case Type of
                Type::"G/L Account":
                    begin
                        if ("No." = '') and (Amount = 0) then
                            exit;

                        if "No." <> '' then
                            if GLAcc.Get("No.") then begin
                                if GLAcc.Blocked then
                                    AddError(xxx)										
                            ****if not GLAcc."Direct Posting" and ("Line No." <= OrigMaxLineNo) then****
                                      AddError(
                                      StrSubstNo(
                                        MustBeForErr,
                                        GLAcc.FieldCaption("Direct Posting"), true, GLAcc.TableCaption, "No."));

It would make sense that during the checking of the purchase line, direct posting is only checked if the entry is not a "System created Entry". We would like to request to change the check in the report 402 to:

       if not GLAcc."Direct Posting" and (not "System-Created Entry") and ("Line No." <= OrigMaxLineNo) then

**Comment by neverbeam** [comment]
Do you want use to make an event request instead on this check?

**Comment by alinat2022** [comment]
Hello. Is there any update on this issue?

**Comment by neverbeam** [comment]
@AlexanderYakunin Can we get a reply on this issue? it is alreayd open from may.

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by alinat2022** [comment]
Thank you for the information provided, Alexander. We have already contacted support for this issue. You can close this ticket.
