### ISSUE TITLE
Field "Package No." in Page 7326 "Whse. Phys. Invt. Journal"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#17902]
Please add the field "Package No." to Page 7326 "Whse. Phys. Invt. Journal" and visible, when the feature "Package No. Tracking" is enabled.
The underlying table 7311 "Warehouse Journal Line" includes this field already and if you work with "Package Warehouse Tracking" you can easily add package nos. to postings in warehouse.
The functionality "Calculate Inventory" on Page 7326 already includes the "Package No." and calculates new line for each "Package No." for the item including "Lot No." if both are set.

It would be better to have the page field in standard instead of creating a page extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40744.
