### ISSUE TITLE
Codeunit 5051 SegManagement - access to local procedure TestFields

### ISSUE THREAD

**Issue by monicasuica** [microsoft/ALAppExtensions#17903]
Hi, 

Is it possible to change the procedure TestFields from local to global? 
In our solution is it used a lot from external object.

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
