### ISSUE TITLE
[Access Request]  codeunit 7313 "Create Put-away" CalcQtyToPutAway

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17900]
Could you please remove the local scope form the procedure `CalcQtyToPutAway` in the codeunit `"Create Put-away"`?

```al
//+Change
//-local procedure CalcQtyToPutAway(EmptyZoneBin: Boolean; NewBinContent: Boolean)
procedure CalcQtyToPutAway(EmptyZoneBin: Boolean; NewBinContent: Boolean)
//-Change
var
    ActionType: Enum "Warehouse Action Type";
begin
    if Location."Bin Mandatory" then begin
        ActionType := ActionType::Place;
        if not EmptyZoneBin and Location."Directed Put-away and Pick" then
            CalcAvailCubageAndWeight;
        AssignQtyToPutAwayForBinMandatory();
    end else
        QtyToPutAwayBase := PostedWhseRcptLine."Qty. (Base)";

    OnCalcQtyToPutAwayOnAfterSetQtyToPutAwayBase(
        PostedWhseRcptLine, Location, Bin, CrossDockInfo, EmptyZoneBin, QtyToPutAwayBase, EverythingHandled, RemQtyToPutAwayBase);
    QtyToPickBase := QtyToPickBase + QtyToPutAwayBase;
    if QtyToPutAwayBase > 0 then begin
        LineNo := LineNo + 10000;
        if NewBinContent and Location."Directed Put-away and Pick" then
            CreateBinContent(PostedWhseRcptLine);
        CreateNewWhseActivity(
            PostedWhseRcptLine, WhseActivLine, ActionType, LineNo,
            0, QtyToPutAwayBase, true, false, EmptyZoneBin, false)
    end
end;
```

**Comment by AlexanderYakunin** [comment]
This procedure depends on multiple global variables, so if it will be public, call to this procedure will return wrong result if previous context is not respected. How are you going to use it? Maybe you'd better write you own procedure for this calculation without risks of wrong result?

**Comment by pri-kise** [comment]
@AlexanderYakunin This request is related to the following request https://github.com/microsoft/ALAppExtensions/issues/17899 .
We have situations where we want to handle the other procedure, but we would still like this procedure in this context, to execute other events.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
