### ISSUE TITLE
Allow extension of standard report field values

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/ALAppExtensions#17929]
Hi,

could we please allow modification of (standard) report field values in report extension?

If I need to change the value of CompanyInfo."Phone No." on runtime, I cannot find a way to do this without having to modify the layout, create a new column etc.

One partial way would be to make all global variables accessible to the report extension. Then I could change the value of the CompanyInfo."Phone No." fields momentarily.

A better way would be a trigger "OnAfterSetValue" for every column in every report. Then the reportextension could simply overwrite the value of this field, without having to modify the layout(s).

**Comment by dnpb** [comment]
> One partial way would be to make all global variables accessible to the report extension.

Please, no! We don't need to encourage global variables. We are still dealing every day with the fallout of their tremendous overuse in the past.

> A better way would be a trigger "OnAfterSetValue" for every column in every report.

Better, but a current solution for things like `CompanyInfo`s would be to mark them as `protected` so report extensions can access them.

**Comment by AlexanderYakunin** [comment]
We cannot process this kind of requests here. If you want extra platform capabilities, please use another report AL. 

You can also ask to make some variables protected; this is easy way to make them available in report.
