### ISSUE TITLE
[Extensibility Request] Codeunit 80 "Sales-Post" - OnPostSalesLineOnAfterTestUpdatedSalesLine

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#17922]
Please Set globalVarAccess to true for function OnPostSalesLineOnAfterTestUpdatedSalesLine

```
[IntegrationEvent(false, true)]
local procedure OnPostSalesLineOnAfterTestUpdatedSalesLine(var SalesLine: Record "Sales Line"; var EverythingInvoiced: Boolean; SalesHeader: Record "Sales Header")
begin
end;
```

**Comment by AlexanderYakunin** [comment]
Sorry, we discontinued use of this parameters several years ago, and cannot set it anymore. See note in this article

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/attributes/devenv-integrationevent-attribute

**Comment by miljance** [comment]
OK, good to know. Thank you.
