### ISSUE TITLE
Event in Codeunit 8614 "Config. XML Exchange"

### ISSUE THREAD

**Issue by wgross92** [microsoft/ALAppExtensions#17927]
Can we have an Event in
"Config. XML Exchange":

```
local procedure CreateRecordNodes(var PackageXML: DotNet XmlDocument; ConfigPackageTable: Record "Config. Package Table")
    ...
    RecRef.Open(ConfigPackageTable."Table ID");
    OnCreateRecordNodesOnBeforeApplyPackageFilter(RecRef);
    ApplyPackageFilter(ConfigPackageTable, RecRef);
    if RecRef.FindSet() then begin
    ...
```

```
    [IntegrationEvent(false, false)]
    local procedure OnCreateRecordNodesOnBeforeApplyPackageFilter(var RecRef: RecordRef)
    begin
    end;
```

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
