### ISSUE TITLE
[Extensibility Request] Codeunit 80 "Sales-Post" - CreatePrepaymentLines

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#17921]
Please make the function CreatePrepaymentLines externally available (from local to external)

`local procedure CreatePrepaymentLines(SalesHeader: Record "Sales Header"; CompleteFunctionality: Boolean)`

desired:

`procedure CreatePrepaymentLines(SalesHeader: Record "Sales Header"; CompleteFunctionality: Boolean)`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
