### ISSUE TITLE
Codeunit 5051 SegManagement - new event request OnBeforeLogDocument

### ISSUE THREAD

**Issue by monicasuica** [microsoft/ALAppExtensions#17928]
Hello,

Please add a new event publisher in the function LogDocument:
```
  begin
        InteractTmplCode := FindInteractTmplCode(DocumentType);
	OnBeforeLogDocument(InteractTmplCode,Attachment); // ++
        if InteractTmplCode = '' then
            exit;

        InteractTmpl.Get(InteractTmplCode);
.....
```
```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeLogDocument(var InteractTmplCode: Code[10]; var Attachment: Record Attachment)
    begin
    end; 
```

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
