### ISSUE TITLE
[Event Request] Service item Line table Field 31 Fault Reason Code 

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#17925]
field(31; "Fault Reason Code"; Code[10])
        {
            Caption = 'Fault Reason Code';
            TableRelation = "Fault Reason Code";

            trigger OnValidate()
            var
                FaultReasonCode: Record "Fault Reason Code";
                ConfirmManagement: Codeunit "Confirm Management";
            begin
                ServLine.Reset();
                ServLine.SetCurrentKey("Document Type", "Document No.", "Service Item Line No.");
                ServLine.SetRange("Document Type", "Document Type");
                ServLine.SetRange("Document No.", "Document No.");
*******Please Add
                OnFaultReasonCodeValidateSetServiceLineFilters(Rec, ServLine, IsHandled);
                If Not IsHandled then begin
*******
                  ServLine.SetRange("Service Item Line No.", "Line No.");
                  if FaultReasonCode.Get("Fault Reason Code") then
                      if FaultReasonCode."Exclude Warranty Discount" then begin
                          ServLine.SetFilter(Type, '%1|%2', ServLine.Type::Cost, ServLine.Type::"G/L Account");
                          if ServLine.Find('-') then
                              if not ConfirmManagement.GetResponseOrDefault(
                                   StrSubstNo(
                                     Text056,
                                     TableCaption,
                                     FieldCaption("Document No."), "Document No.",
                                     FieldCaption("Line No."), "Line No.",
                                     ServLine.FieldCaption(Type),
                                     ServLine.Type::"G/L Account",
                                     ServLine.Type::Cost,
                                     FaultReasonCode.FieldCaption("Exclude Warranty Discount"),
                                     FaultReasonCode.TableCaption, FaultReasonCode.Code),
                                   true)
                              then
                                  Error('');
                          ServLine.SetRange(Type, ServLine.Type::Item, ServLine.Type::Resource);
                      end else
                          ServLine.SetRange(Type, ServLine.Type::Item, ServLine.Type::"G/L Account");
*******Please Add                
                End;
*******
                if ServLine.Find('-') then
                    repeat
                        ServLine.Validate("Fault Reason Code", "Fault Reason Code");
                        ServLine.Modify();
                    until ServLine.Next() = 0;
            end;
        }

where
On FaultReasonCodeValidateSetServiceLineFilters(var ServiceItemLine: Record "Service Item Line"; var ServLine:Record "Service Line"; IsHandled: Boolean);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
