### ISSUE TITLE
Business central 365 - Purchase credit memo

### ISSUE THREAD

**Issue by r-cornelia** [microsoft/ALAppExtensions#17939]
We developed an adapter able to export purchase accounting entries from our service to Business central 365.
The API we are using are the Business central public API: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v2.0/

This documentation doesn’t tell us how to create a purchase credit memo. 
(The sales credit memo are well described instead).

As the purchase credit memo document is as important as the purchase invoice our implementation is blocked. 
Can you please provide us with some documentation about it?

**Comment by onbuyuka** [comment]
There is no available purchase credit memo API as of now. We have it in our backlog but it is not planned for this release. If this is urgent for you, you can always create your own custom API for purchase credit memo. 
Please check out [Developing a Custom API
](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-custom-api) for the general custom API walkthrough and [APIV2SalesCreditMemos](https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/APIV2/app/src/pages/APIV2SalesCreditMemos.Page.al) for inspiration.

**Comment by r-cornelia** [comment]
Hello Onat,

Thank you for you feedback.
Do you have any release date for this feature? I understand it is not planned for the next one, but an estimation date will help us a lot.

Regards,


Cornelia Rusu
Project Manager

Tél. :+33 4 66 35 77 64
Mobile :+33 6 25 89 38 68
***@***.***




De : Onat Buyukakkus ***@***.***>
Envoyé : mardi 17 mai 2022 08:20
À : microsoft/ALAppExtensions ***@***.***>
Cc : Cornelia Rusu ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/ALAppExtensions] Business central 365 - Purchase credit memo (Issue #17939)


There is no available purchase credit memo API as of now. We have it in our backlog but it is not planned for this release. If this is urgent for you, you can always create your own custom API for purchase credit memo.
Please check out Developing a Custom API
<https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-custom-api>for the general custom API walkthrough and APIV2SalesCreditMemos<https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/APIV2/app/src/pages/APIV2SalesCreditMemos.Page.al> for inspiration.

**Comment by onbuyuka** [comment]
Hi, unfortunately not. It is going to be part of API version 3.0 however we do not see it coming out until v23 at least.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.

**Comment by JesperSchulz** [comment]
I apologize for the wrong update. Our internal work item was wrongfully closed as "Fixed", which triggered our automation to post the message that a fix is being released. It is not. @onbuyuka's comment is the conclusion on this issue.
