### ISSUE TITLE
[Event Request] codeunit 80 "Sales-Post" PostItemJnlLineBeforePost

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#17931]
Please make function PostItemJnlLineBeforePost externally available. Also please add the parameter TrackingSpecification as the parameter. Parameter neede for following Event:
OnPostItemJnlLineOnBeforeTransferReservToItemJnlLine
https://github.com/microsoft/ALAppExtensions/issues/17937

current:
`local procedure PostItemJnlLineBeforePost(var ItemJnlLine: Record "Item Journal Line"; SalesLine: Record "Sales Line"; var TempWhseJnlLine: Record "Warehouse Journal Line" temporary; var PostWhseJnlLine: Boolean; QtyToBeShippedBase: Decimal)`

desired:
`procedure PostItemJnlLineBeforePost(var ItemJnlLine: Record "Item Journal Line"; SalesLine: Record "Sales Line"; var TempWhseJnlLine: Record "Warehouse Journal Line" temporary; var PostWhseJnlLine: Boolean; QtyToBeShippedBase: Decimal; TrackingSpecification: Record "Tracking Specification")`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40900.
