### ISSUE TITLE
[Event Request] codeunit 80 "Sales-Post" PostItemJnlLineWhseLine

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#17934]
Please make function PostItemJnlLineWhseLine externally available:

current:
`local procedure PostItemJnlLineWhseLine(var TempWhseJnlLine: Record "Warehouse Journal Line" temporary; var TempWhseTrackingSpecification: Record "Tracking Specification" temporary)`

desired:
`procedure PostItemJnlLineWhseLine(var TempWhseJnlLine: Record "Warehouse Journal Line" temporary; var TempWhseTrackingSpecification: Record "Tracking Specification" temporary)`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
