### ISSUE TITLE
[Scope Request] Codeunit 10801 Modify Scope Onprem -> Cloud on procedure Check

### ISSUE THREAD

**Issue by calliopedavidroldan** [microsoft/ALAppExtensions#17938]
Hi,

We need to use the procedure Check from codeunit RIB key on cloud target. It is possible to change the scope ?
Moreover, we do not understand why some MS procedures have an Onprem scope.
For example :
- DimensionSetup from table Payment Line
- TestSourceCode from Payment Management
- GetCustLedgEntries or CheckAmounts from table Cust. Ledger Entry

**Comment by dnpb** [comment]
It seems some objects just got all their methods marked as for OnPrem only, until users request them to be available in Cloud too.

I know one big partner developer who deliberately made all procedures internal and require tickets for each procedure to be made public. Perhaps MS used similar logic in some places.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
