### ISSUE TITLE
[Event Request] codeunit 80 "Sales-Post" IsItemJnlPostLineHandled

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#17932]
Please make function IsItemJnlPostLineHandled externally available:

current:
`local procedure IsItemJnlPostLineHandled(var ItemJnlLine: Record "Item Journal Line"; var SalesLine: Record "Sales Line"; var SalesHeader: Record "Sales Header") IsHandled: Boolean
`
desired:
`procedure IsItemJnlPostLineHandled(var ItemJnlLine: Record "Item Journal Line"; var SalesLine: Record "Sales Line"; var SalesHeader: Record "Sales Header") IsHandled: Boolean`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
