### ISSUE TITLE
[Event Request] OnCreateRecurrenceOnBeforeInsertUserTask in Table 1170 "User Task"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#17942]
Please create a new event in table 1170 "User Task" in procedure CreateRecurrence:

procedure CreateRecurrence(RecurringStartDate: Date; Recurrence: DateFormula; Occurrences: Integer)
    var
        UserTaskTemp: Record "User Task";
        "Count": Integer;
        TempDueDate: Date;
    begin
        Validate("Parent ID", ID);
        Validate("Due DateTime", CreateDateTime(RecurringStartDate, 000000T));
        Modify(true);

        TempDueDate := RecurringStartDate;
        while Count < Occurrences - 1 do begin
            Clear(UserTaskTemp);
            UserTaskTemp.Validate(Title, Title);
            UserTaskTemp.SetDescription(GetDescription);
            UserTaskTemp."Created By" := UserSecurityId;
            UserTaskTemp.Validate("Created DateTime", CurrentDateTime);
            UserTaskTemp.Validate("Assigned To", "Assigned To");
            UserTaskTemp.Validate("User Task Group Assigned To", "User Task Group Assigned To");
            UserTaskTemp.Validate(Priority, Priority);
            UserTaskTemp.Validate("Object Type", "Object Type");
            UserTaskTemp.Validate("Object ID", "Object ID");
            UserTaskTemp.Validate("Parent ID", ID);
            TempDueDate := CalcDate(Recurrence, TempDueDate);
            UserTaskTemp.Validate("Due DateTime", CreateDateTime(TempDueDate, 000000T));
            //++++++++++++++++++++++++++++
            OnBeforeInsertRecurringUserTask(var UserTaskTemp: Record "User Task";fromUserTask:Record "User Task";"Count": Integer;RecurringStartDate: Date; Recurrence: DateFormula);
            //-------------------------------------------
            UserTaskTemp.Insert(true);
            Count := Count + 1;
        end
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
