### ISSUE TITLE
[Event Request] table 7316 "Warehouse Receipt Header" - OnAfterCalcAreWarehouseReceiptLinesEditable

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17958]
I'm referring to issue https://github.com/microsoft/ALAppExtensions/issues/16594 for this issue.

In our app we are using a lifecycle/workflow code which has the ability to tell and show the user if a page and/or its subpage(s) is/are editable or not. When you scroll through the records we are able to set the editable property dynamically of the page itself but not of the subpage(s). 

To use our app and delete Base app changes we need the following:
1. A procedure + event in table 7316 "Warehouse Receipt Header":
    
    procedure CalcAreWarehouseReceiptLinesEditable() IsEditable: Boolean;
    begin
        //A113F0000.Event20.00.ns
        IsEditable := true;

        OnAfterCalcAreWarehouseReceiptLinesEditable(Rec, IsEditable);
        //A113F0000.Event20.00.ne
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcAreWarehouseReceiptLinesEditable(var WarehouseReceiptHeader: Record "Warehouse Receipt Header"; var IsEditable: Boolean)
    begin
        //A113F0000.Event20.00
    end;

2. A global protected var:
    
    AreWarehouseReceiptLinesEditable: Boolean;

    on page 5768 "Warehouse Receipt"
   
3. A call in trigger OnAfterGetCurrRecord() in page 5768 "Warehouse Receipt"

    AreWarehouseReceiptLinesEditable := Rec.CalcAreWarehouseReceiptLinesEditable(); //A113F0000.Event20.00

4. Setting the properties Editable and Enabled of part(WhseReceiptLines) in page 5768 "Warehouse Receipt"

    Editable = AreWarehouseReceiptLinesEditable;
    Enabled = AreWarehouseReceiptLinesEditable;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43058.
