### ISSUE TITLE
[Event Request] table 5900 "Service Header" - OnAfterCalcAreServiceLinesEditable

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17957]
I'm referring to issue https://github.com/microsoft/ALAppExtensions/issues/16594 for this issue.

In our app we are using a lifecycle/workflow code which has the ability to tell and show the user if a page and/or its subpage(s) is/are editable or not. When you scroll through the records we are able to set the editable property dynamically of the page itself but not of the subpage(s). 

To use our app and delete Base app changes we need the following:
1. A procedure + event in table 5900 "Service Header":
    
    procedure CalcAreServiceLinesEditable() IsEditable: Boolean;
    begin
        //A113F0000.Event20.00.ns
        IsEditable := "Customer No." <> '';

        OnAfterCalcAreServiceLinesEditable(Rec, IsEditable);
        //A113F0000.Event20.00.ne
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcAreServiceLinesEditable(var ServiceHeader: Record "Service Header"; var IsEditable: Boolean)
    begin
        //A113F0000.Event20.00
    end;

2. A global protected var:
    
    AreServiceLinesEditable: Boolean;

    on pages:
    
    page 5900 "Service Order"
    page 5964 "Service Quote"
    page 5933 "Service Invoice"
    page 5935 "Service Credit Memo"
    
3. A call in trigger OnAfterGetCurrRecord() in each mentioned page

    AreServiceLinesEditable := Rec.CalcAreServiceLinesEditable(); //A113F0000.Event20.00

4. Setting the properties Editable and Enabled of part(ServLines) in each mentioned page

    Editable = AreServiceLinesEditable;
    Enabled = AreServiceLinesEditable;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43058.
