### ISSUE TITLE
[Event Request] - table 167 Job - OnAfterShipToCodeValidate

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17953]
This piece of code was completely missing in 20.00. Still it is not quite finished. Please add an event when copying one record to another. 

P.S. When you remove the "Ship-to Code" value, the address info from the Sell-To Customer is not copied to the Ship-to fields like it is being done in T36, T38 and T5900. You might add that same functionality at the Job area as well. 

    local procedure ShipToCodeValidate()
    var
        ShipToAddress: Record "Ship-to Address";
    begin
        if (xRec."Ship-to Code" <> Rec."Ship-to Code") and (Rec."Ship-to Code" <> '') then
            if ShipToAddress.Get(Rec."Sell-to Customer No.", Rec."Ship-to Code") then begin
                Rec."Ship-to Name" := ShipToAddress.Name;
                Rec."Ship-to Name 2" := ShipToAddress."Name 2";
                Rec."Ship-to Address" := ShipToAddress.Address;
                Rec."Ship-to Address 2" := ShipToAddress."Address 2";
                Rec."Ship-to City" := ShipToAddress.City;
                Rec."Ship-to County" := ShipToAddress.County;
                Rec."Ship-to Post Code" := ShipToAddress."Post Code";
                Rec."Ship-to Country/Region Code" := ShipToAddress."Country/Region Code";
                Rec."Ship-to Contact" := ShipToAddress.Contact;

                OnAfterShipToCodeValidate(Rec, ShipToAddress);
            end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterShipToCodeValidate(var Job: Record Job; ShipToAddress: Record "Ship-to Address")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
