### ISSUE TITLE
[Event Request] table 36 "Sales Header" - OnAfterCalcAreSalesLinesEditable

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17954]
I'm referring to issue https://github.com/microsoft/ALAppExtensions/issues/16594 for this issue.

In our app we are using a lifecycle/workflow code which has the ability to tell and show the user if a page and/or its subpage(s) is/are editable or not. When you scroll through the records we are able to set the editable property dynamically of the page itself but not of the subpage(s). 

To use our app and delete Base app changes we need the following:
1. A procedure + event in table 36 "Sales Header":
    
    procedure CalcAreSalesLinesEditable() IsEditable: Boolean;
    begin
        //A113F0000.Event20.00.ns
        if "Document Type" = "Document Type"::Quote then
            IsEditable := ("Sell-to Customer No." <> '') or ("Sell-to Customer Templ. Code" <> '') or ("Sell-to Contact No." <> '')
        else
            IsEditable := "Sell-to Customer No." <> '';

        OnAfterCalcAreSalesLinesEditable(Rec, IsEditable);
        //A113F0000.Event20.00.ne
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcAreSalesLinesEditable(var SalesHeader: Record "Sales Header"; var IsEditable: Boolean)
    begin
        //A113F000020.00.Event
    end;

2. A global protected var:
    
    AreSalesLinesEditable: Boolean;

    on pages:
    
    page 507 "Blanket Sales Order"
    page 44 "Sales Credit Memo"
    page 43 "Sales Invoice"
    page 42 "Sales Order"
    page 41 "Sales Quote"
    page 6630 "Sales Return Order"

3. A call in trigger OnAfterGetCurrRecord() in each mentioned page

    AreSalesLinesEditable := Rec.CalcAreSalesLinesEditable(); //A113F0000.Event20.00

4. Setting the properties Editable and Enabled of part(SalesLines) in each mentioned page

    Editable = AreSalesLinesEditable;
    Enabled = AreSalesLinesEditable;

For some of the pages Quote and Order it means a bit of recoding with booleans DynamicEditable and SalesLinesAvailable and procedure SetSalesLinesAvailability already being used doing something similar.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43058.
