### ISSUE TITLE
[Event Request] table 38 "Purchase Header" - OnAfterCalcArePurchaseLinesEditable

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17955]
I'm referring to issue https://github.com/microsoft/ALAppExtensions/issues/16594 for this issue.

In our app we are using a lifecycle/workflow code which has the ability to tell and show the user if a page and/or its subpage(s) is/are editable or not. When you scroll through the records we are able to set the editable property dynamically of the page itself but not of the subpage(s). 

To use our app and delete Base app changes we need the following:
1. A procedure + event in table 38 "Purchase Header":
    
    procedure CalcArePurchaseLinesEditable() IsEditable: Boolean;
    begin
        //A113F0000.Event20.00.ns
        IsEditable := "Buy-from Vendor No." <> '';

        OnAfterCalcArePurchaseLinesEditable(Rec, IsEditable);
        //A113F0000.Event20.00.ne
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcArePurchaseLinesEditable(var PurchaseHeader: Record "Purchase Header"; var IsEditable: Boolean)
    begin
        //A113F0000.Event20.00
    end;

2. A global protected var:
    
    ArePurchaseLinesEditable: Boolean;

    on pages:
    
    page 509 "Blanket Purchase Order"
    page 52 "Purchase Credit Memo"
    page 51 "Purchase Invoice"
    page 50 "Purchase Order"
    page 49 "Purchase Quote"
    page 6640 "Purchase Return Order"

3. A call in trigger OnAfterGetCurrRecord() in each mentioned page

    ArePurchaseLinesEditable := Rec.CalcArePurchaseLinesEditable(); //A113F0000.Event20.00

4. Setting the properties Editable and Enabled of part(PurchLines) in each mentioned page

    Editable = ArePurchaseLinesEditable;
    Enabled = ArePurchaseLinesEditable;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43058.
