### ISSUE TITLE
[Event Request] Codeunit 99000787 - Create Prod. Order Lines - CopyFromFamilyOnAfterInsertProdOrderLine

### ISSUE THREAD

**Issue by SchoKa** [Microsoft/ALAppExtensions#1795]
Hello AL-Team,
please add the following Publisher in function "CopyFromFamily":

```
LOCAL CopyFromFamily() : Boolean
[ ... ]
      InsertProdOrderLine;
      IF ProdOrderLine.HasErrorOccured THEN
        ErrorOccured := TRUE;

      // >> New
      CopyFromFamilyOnAfterInsertProdOrderLine(ProdOrderLine);
      // << New

    END;
  UNTIL FamilyLine.NEXT = 0;
EXIT(NOT ErrorOccured);

```
Publisher definition currently used by us
IncludeSender: false
GlobaVarAccess: false
LOCAL [IntegrationEvent] CopyFromFamilyOnAfterInsertProdOrderLine(VAR ProdOrderLine : Record "Prod. Order Line")

**Comment by NKarolak** [comment]
Note: added as OnCopyFromFamilyOnAfterInsertProdOrderLine
