### ISSUE TITLE
[Event Request] table 5740 "Transfer Header" - OnAfterCalcAreTransferLinesEditable

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17956]
I'm referring to issue https://github.com/microsoft/ALAppExtensions/issues/16594 for this issue.

In our app we are using a lifecycle/workflow code which has the ability to tell and show the user if a page and/or its subpage(s) is/are editable or not. When you scroll through the records we are able to set the editable property dynamically of the page itself but not of the subpage(s). 

To use our app and delete Base app changes we need the following:
1. A procedure + event in table table 5740 "Transfer Header":
    
    procedure CalcAreTransferLinesEditable() IsEditable: Boolean;
    begin
        //A113F0000.Event20.00.ns
        IsEditable := ("Transfer-from Code" <> '') and ("Transfer-to Code" <> '') and ("In-Transit Code" <> '');

        OnAfterCalcAreTransferLinesEditable(Rec, IsEditable);
        //A113F0000.Event20.00.ne
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcAreTransferLinesEditable(var TransferHeader: Record "Transfer Header"; var IsEditable: Boolean)
    begin
        //A113F0000.Event20.00
    end;

2. A global protected var:
    
    AreTransferLinesEditable: Boolean;

    on page 5740 "Transfer Order"
    
3. A call in trigger OnAfterGetCurrRecord() in page 5740 "Transfer Order"

    AreTransferLinesEditable := Rec.CalcAreTransferLinesEditable(); //A113F0000.Event20.00

4. Setting the properties Editable and Enabled of part(TransferLines) in page 5740 "Transfer Order"

    Editable = AreTransferLinesEditable;
    Enabled = AreTransferLinesEditable;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43058.

**Comment by Duizy1971** [comment]
Hi Jesper,

I checked this issue and so far, it all works well (also in all the other entities sales/purchase etc.
Only point 4 has not been implemented. The properties Editable and Enabled on page 5740 "Transfer Order" have not been changed in BC21.00

            part(TransferLines; "Transfer Order Subform")
            {
                ApplicationArea = Location;
                Editable = IsTransferLinesEditable;
                Enabled = IsTransferLinesEditable;
                SubPageLink = "Document No." = FIELD("No."),
                              "Derived From Line No." = CONST(0);
                UpdatePropagation = Both;
            }

**Comment by JesperSchulz** [comment]
We usually don't follow up on closed issues. If further changes are required, please create a new issue going forward.
@AlexanderYakunin, could you look into this case?

**Comment by Duizy1971** [comment]
This one is fixed as well with new issue 21129.
