### ISSUE TITLE
[Event Request] table 5405 "Production Order": CreateDim

### ISSUE THREAD

**Issue by TimCsr** [microsoft/ALAppExtensions#17963]
Object: table 5405 "Production Order"

Function: CreateDim

Integration Event:
OnBeforeCreateDim(Rec, IsHandled);

local procedure OnBeforeCreateDim(var ProductionOrder: Record "Production Order"; var IsHandled: Boolean)

![image](https://user-images.githubusercontent.com/50943286/168064327-4ed3f037-41af-4a44-b65e-bc6a2b94f3bd.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
