### ISSUE TITLE
[Event Request] report 99001015 "Calculate Subcontracts" - OnDeleteRepeatedReqLinesOnAfterSetRequisitionLineFilters

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#17964]
local procedure DeleteRepeatedReqLines()
    var
        RequisitionLine: Record "Requisition Line";
    begin
        with RequisitionLine do begin
            SetRange(Type, Type::Item);
            SetRange("No.", ProdOrderLine."Item No.");
            SetRange("Prod. Order No.", ProdOrderLine."Prod. Order No.");
            SetRange("Prod. Order Line No.", ProdOrderLine."Line No.");
            SetRange("Routing No.", "Prod. Order Routing Line"."Routing No."); //A108B0077.n
            SetRange("Operation No.", "Prod. Order Routing Line"."Operation No.");
            OnDeleteRepeatedReqLinesOnAfterSetRequisitionLineFilters(RequisitionLine, ProdOrderLine, "Prod. Order Routing Line"); //A111F0000.Event20.01
            DeleteAll(true);
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnDeleteRepeatedReqLinesOnAfterSetRequisitionLineFilters(var RequisitionLine: Record "Requisition Line"; ProdOrderLine: Record "Prod. Order Line"; ProdOrderRoutingLine: Record "Prod. Order Routing Line")
    begin
        //A111F0000.Event20.01
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
