### ISSUE TITLE
[BUG] [Event Request] Codeunit 22 procedure InsertVarValueEntry

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#17961]
Hello, 

For one of our customizations we need to update the Variance amount in function InsertVarValueEntry in codeunit 22. 

    local procedure InsertVarValueEntry(ValueEntry: Record "Value Entry"; VarianceAmount: Decimal; VarianceAmountACY: Decimal)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeInsertVarValueEntry(ValueEntry, Item, VarianceAmount, VarianceAmountACY, IsHandled);
        if IsHandled then
            exit;

        if (not ValueEntry.Inventoriable) or Item."Inventory Value Zero" then
            exit;
        if (VarianceAmount = 0) and (VarianceAmountACY = 0) then
            exit;

We are using Event OnBeforeInsertVarValueEntry for this. 
Note: if the Variance amount is 0 the function will exit.

We noticed this code is not always executed, this is because the if before the function Call:

                if ((GlobalValueEntry."Valued Quantity" > 0) or ("Applies-to Entry" <> 0)) and
                   ("Entry Type" = "Entry Type"::Purchase) and
                   (Item."Costing Method" = Item."Costing Method"::Standard) and
                   **(Round(VarianceAmount, GLSetup."Amount Rounding Precision") <> 0)** or
                   VarianceRequired
                then
                    InsertVarValueEntry(GlobalValueEntry, VarianceAmount, VarianceAmountACY);

As you can see the function is skipped if VarianceAmount is 0. I think this line should be removed.

if that is not possible, I would like to add the VarianceAmount and the VarianceAmountACY to procedure as var:       

OnItemValuePostingOnBeforeInsertOHValueEntry(ItemJnlLine, GlobalValueEntry, GlobalItemLedgEntry, ValueEntryNo, IsHandled);

Can you inform me about the delivery time of this bug ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
