### ISSUE TITLE
[Event Change Request] report 7391 "Whse. Get Bin Content" - OnBinContenOnAfterGetRecordOnAfterCalcShouldSkipReportForQty

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#17978]
Could you please include the sender on the event `OnBinContenOnAfterGetRecordOnAfterCalcShouldSkipReportForQty`?
```al
//+Change
//-[IntegrationEvent(false, false)]
[IntegrationEvent(true, false)]
//-Change
local procedure OnBinContenOnAfterGetRecordOnAfterCalcShouldSkipReportForQty(var BinContent: Record "Bin Content"; var ShouldSkipReportForQty: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
