### ISSUE TITLE
[Extensibility Request] Page 47 "Sales Invoice Subform" / Page 96 "Sales Cr. Memo Subform" / Page 6631 "Sales Return Order Subform"

### ISSUE THREAD

**Issue by chrischbo** [microsoft/ALAppExtensions#17972]
Hi,

to handle the new price calculation we work with the SystemId of the actual record. This is possible in Sales Quote and Sales Order without any issues but with the listed objects above we're in trouble. 
The misbehavior is caused by a missing CurrPage.Update(); on the OnValidate trigger of the "No." field. Because of this the record doesn't "exists" when the price calculation is called and so our function won't work.

Good :)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/15926999/168083750-cdc0bd1b-007b-4afb-8a28-97a2bc64883d.png)

Not so good ;) 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/15926999/168083865-ba1d4510-9815-4442-8c5a-603ba497ecbe.png)

Is it possible to align the logic for all document types?

Kind regards
Christian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47752.
