### ISSUE TITLE
Codeunit 12 - Change for OnNextTransactionNoNeeded

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#1797]
In the NextTransactionNoNeeded function, we need the OnNextTransactionNoNeeded event to be called regardless of the "NewTransaction" variable value.

**Comment by AlexanderYakunin** [comment]
We alerady have that?

LOCAL NextTransactionNoNeeded(GenJnlLine : Record "Gen. Journal Line") : Boolean
WITH GenJnlLine DO BEGIN
  NewTransaction :=
    (LastDocType <> "Document Type") OR (LastDocNo <> "Document No.") OR
    (LastDate <> "Posting Date") OR ((CurrentBalance = 0) AND (TotalAddCurrAmount = 0)) AND NOT "System-Created Entry";
  OnNextTransactionNoNeeded(GenJnlLine,LastDocType,LastDocNo,LastDate,CurrentBalance,TotalAddCurrAmount,NewTransaction);
  EXIT(NewTransaction);
END;

**Comment by AlexanderYakunin** [comment]
Please close if it is ok for you

**Comment by RHansenEpimatic** [comment]
Thanks Alexander.  When i downloaded the latest build, i saw this change.  Looks good.
