### ISSUE TITLE
[Extensibility Request] Report 11301 "Purchase Ledger" - Protected variables

### ISSUE THREAD

**Issue by TimXams** [microsoft/ALAppExtensions#17970]
Hi,

For a report extension I need the following global variables to protected so that I can use them:

    protected var
        PeriodStartDate: Date;
        PeriodEndDate: Date;

Is this possible?

Kind regards!
Tim

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
