### ISSUE TITLE
[Extensibility Request] local to global Page 510 "Blanket Purchase Order Subform" - DeltaUpdateTotals

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#17984]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!
[Extensibility Request] page 510 "Blanket Purchase Order Subform" - Procedure from Internal to Global

```
local procedure DeltaUpdateTotals()
```

**Comment by AlexanderYakunin** [comment]
You can call it using

    procedure CallDeltaUpdateTotals()
    begin
        DeltaUpdateTotals();
    end;
