### ISSUE TITLE
[Event Request] Codeunit 5987 "Serv-Posting Journals Mgt." - OnBeforeCreateCarteraBills (Spanish localization)

### ISSUE THREAD

**Issue by juacefer** [microsoft/ALAppExtensions#17982]
Please, add a new event in procedure CreateBills

procedure CreateBills(var TotalServiceLine: Record "Service Line"; var Window: Dialog; GenJnlLineDocNo: Code[20]; GenJnlLineExtDocNo: Code[35])
var
	CustLedgEntry: Record "Cust. Ledger Entry";
	PaymentMethod: Record "Payment Method";
	CarteraSetup: Record "Cartera Setup";
	SplitPayment: Codeunit "Invoice-Split Payment";
begin
	CustLedgEntry.Find('+');
	with ServiceHeader do begin
		if PaymentMethod.Get("Payment Method Code") then
			if (PaymentMethod."Create Bills" or PaymentMethod."Invoices to Cartera") and
			   (not CarteraSetup.ReadPermission) and Invoice
			then
				Error(CannotCreateCarteraDocErr);

		if ("Bal. Account No." = '') and ("Document Type" <> "Document Type"::"Credit Memo") and CarteraSetup.ReadPermission then **begin**
			**OnBeforeCreateCarteraBills(ServiceHeader,CustLedgEntry,TotalServiceLine);**
			SplitPayment.SplitServiceInv(
			  ServiceHeader, CustLedgEntry, Window, SrcCode, GenJnlLineExtDocNo, GenJnlLineDocNo,
			  -(TotalServiceLine."Amount Including VAT" - TotalServiceLine.Amount));
		**end**;

The new event:

[IntegrationEvent(false, false)]
local procedure OnBeforeCreateCarteraBills(ServiceHeader : Record "Service Header";CustLedgerEntry : Record "Cust. Ledger Entry";VAR TotalServiceLine : Record "Service Line")
begin
end;

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by juacefer** [comment]
We need a new modification in the event OnBeforeCreateCarteraBills

[IntegrationEvent(false, false)]
local procedure OnBeforeCreateCarteraBills(ServiceHeader : Record "Service Header";**VAR** CustLedgerEntry : Record "Cust. Ledger Entry";VAR TotalServiceLine : Record "Service Line")
begin
end;

We have a problem locating our customer entry. In the procedure CreateBills(var TotalServiceLine: Record "Service Line"; var Window: Dialog; GenJnlLineDocNo: Code[20]; the variable is initialized with CustLedgEntry.Find('+'). This returns ALL customer entries.

We need to be able to apply some filters in the CustLedgEntry variable in the OnBeforeCreateCarteraBills event in order to locate the correct customer entry corresponding to the invoice that we are posting.

**Comment by JesperSchulz** [comment]
> We need a new modification in the event OnBeforeCreateCarteraBills
> 
> [IntegrationEvent(false, false)] local procedure OnBeforeCreateCarteraBills(ServiceHeader : Record "Service Header";**VAR** CustLedgerEntry : Record "Cust. Ledger Entry";VAR TotalServiceLine : Record "Service Line") begin end;
> 
> We have a problem locating our customer entry. In the procedure CreateBills(var TotalServiceLine: Record "Service Line"; var Window: Dialog; GenJnlLineDocNo: Code[20]; the variable is initialized with CustLedgEntry.Find('+'). This returns ALL customer entries.
> 
> We need to be able to apply some filters in the CustLedgEntry variable in the OnBeforeCreateCarteraBills event in order to locate the correct customer entry corresponding to the invoice that we are posting.

Please create a new issue, if you need further changes.
