### ISSUE TITLE
[Extensibility Request] local to global Table 5876 "Phys. Invt. Order Line" - GetPhysInvtOrderHeader

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#17987]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

[Extensibility Request] table 5876 "Phys. Invt. Order Line" - Procedure from Internal to Global

```
local procedure GetPhysInvtOrderHeader()
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
