### ISSUE TITLE
[Extensibility Request] local to global Page 161 "Purchase Statistics" - GetVATSpecification

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#17986]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

[Extensibility Request] page 161 "Purchase Statistics" - Procedure from Local to Global

```
local procedure GetVATSpecification()
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
