### ISSUE TITLE
[Extensibility Request] local to global Page 5850 "Posted Sales Document Lines" - ChangeSubMenu

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#17985]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

[Extensibility Request] page 5850 "Posted Sales Document Lines" - Procedure from Local to Global

```
local procedure ChangeSubMenu(NewMenuType: Integer)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
