### ISSUE TITLE
[Event Request] table 337 "Reservation Entry" - OnAfterTransferReservations

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#17995]
Event need on the end of the function TransferReservations

```
[IntegrationEvent(false, false)]
local procedure OnAfterTransferReservations(var OldReservEntry: Record "Reservation Entry"; var NewReservEntry: Record "Reservation Entry")
begin
end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
