### ISSUE TITLE
[Extensibility Enhancement] Add `InitUsageFilter` to OnOpenPage of all "Report Selection" pages

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#17993]
Dear ALAppExtensions team,

Through this issue we would like to request an extensibility enhancement for report selections. We would like the following change to be applied:

Currently, there are _Report Selection_ pages, like "Report Selection - Sales" and "Report Selection - Reminder", which have a call to a `InitUsageFilter` procedure in the `OnOpenPage` trigger.
This allows one to have the page open with one of the usages already selected.

Could you please also add this procedure `InitUsageFilter` and call it in the `OnOpenPage` trigger in all Report Selection pages where it is currently not implemented?

This concerns the following pages:
* `Page "Report Selection - Bank Acc."`
* `Page "Report Selection - Inventory"`
* `Page "Report Selection - Prod. Order"`
* `Page "Report Selection - Purchase"`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43116.
