### ISSUE TITLE
[Request for External] page 6640 "Purchase Return Order" - Protected variables

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#17990]
Hello, we need the following currently global variable/-s to be set as protected. Can you please check this? Thank you!

```
protected var 
   DocPrint: Codeunit "Document-Print";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
