### ISSUE TITLE
Event Parameter Issue

### ISSUE THREAD

**Issue by RavinderKumarGitHub** [microsoft/ALAppExtensions#18001]
Dear Team

We are facing a lot of challenges in posting sales return and sales credit memo due to "IsHandled" is not declared with reference in the events. Please declare "IsHandled" variable under references in **_codeunit 18435 "Reference Invoice No. Mgt."_**.

For your References only.

**_Orignal code in BC365:_**
[IntegrationEvent(false, false)]

local procedure OnBeforeCheckRefInvNoPurchHeader(var PurchaseHeader: Record "Purchase Header"; **_IsHandled: Boolean_**)

**_Please correct the the code like in events._**
[IntegrationEvent(false, false)]

local procedure OnBeforeCheckRefInvNoPurchHeader(var PurchaseHeader: Record "Purchase Header"; **_var IsHandled: Boolean_**)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41146.
