### ISSUE TITLE
[Access Request] page 1171 "User Task Card"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#18007]
Could you please change the access scope of the following two variables to **protected**?
```al
    var
        MultiLineTextControl: Text;
        InvalidPageTypeErr: Label 'You must specify a list page.';
        PageTok: Label 'Page';
        ReportTok: Label 'Report';
    //+Change
    protected var
        MultiLineTextControl: Text;
        IsMarkCompleteEnabled: Boolean;
    //-Change
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40912.
