### ISSUE TITLE
Events and Application Enhancement.

### ISSUE THREAD

**Issue by RavinderKumarGitHub** [microsoft/ALAppExtensions#18000]
Dear Team,

Please do the needful.

**Change Dimension Action short key from _CTRL+SHIFT+D_ to _ALT+D_ in Page 18322 "Pay GST".
Change Option fields _"Status", "Change Status", "Quote Type"_ to Enum in Service Contract Header Table with extensible true.
Change Option fields _"Contract Status"_ to Enum in Service Contract Line Table with extensible true.
Provide fields _"OnValidate"_ trigger handling events in Service Contract Header Table.
Make Enum _"GST Reason Type"_ extensible true.**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40732.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 41457.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.

Build ID to track: 41456.
