### ISSUE TITLE
Codeunit 5988 Serv-Documents Mgt. - SetNoSeries

### ISSUE THREAD

**Issue by Lukoey** [microsoft/ALAppExtensions#18013]
Dear Team,

the modify in SetNoSeries is causing a problem when we try to post a serviceorder. When the shipping and posting no. were set previously this problem doesn't appear.
![Modify](https://user-images.githubusercontent.com/50693559/168531320-e51cbd31-8013-4c7f-8948-36454ade01c5.png)
![Error_Message](https://user-images.githubusercontent.com/50693559/168532736-d7f4088e-2c18-491d-9608-90ef292b8474.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42366.
