### ISSUE TITLE
[Request for external]  Codeunit 80 UpdateInvoicePostBuffer

### ISSUE THREAD

**Issue by RHansenEpimatic** [microsoft/ALAppExtensions#1802]
To migrate a NAV ISV add-on to BC:

We need the “UpdateInvoicePostBuffer” function to be available as an external function we can call.

**Comment by StanPesotskiy** [comment]
External usage of this function for purchasing fixed assets will not correct. If you are not going to use it for fixed assets posting then you better use InvoicePostBuffer.Update() which is already global.
