### ISSUE TITLE
Remove internal access property from procedures in Table 167 Job

### ISSUE THREAD

**Issue by SlawekDXC** [microsoft/ALAppExtensions#18027]
We noticed that in BC20 CU1 table 167 Job was modified and confirmation dialogs was added on multiple fields validation, for ex. on "Sell-to Customer No." and "Bill-to Customer No.".
![image](https://user-images.githubusercontent.com/105501469/168611107-d24ba88c-55ba-4201-bb33-51eff00f5ed3.png)

There are procedures added to hide those validation dialogs (SetHideValidationDialog and GetHideValidationDialog), but they have "internal" scope. Therefore we cannot skip this confirmation in our extensions.
![image](https://user-images.githubusercontent.com/105501469/168611184-a7c7c67c-4132-42f9-b8de-c25791396010.png)

Please remove "internal" access property from SetHideValidationDialog and GetHideValidationDialog to allow partners hide those confirmations in their extensions (similar as for ex. in Sales Header table).
Before change:

```
internal procedure SetHideValidationDialog(NewHideValidationDialog: Boolean)
begin
    HideValidationDialog := NewHideValidationDialog;
end;
```

```
internal procedure GetHideValidationDialog(): Boolean
begin
    exit(HideValidationDialog);
end;
```

After change:
```
procedure SetHideValidationDialog(NewHideValidationDialog: Boolean)
begin
    HideValidationDialog := NewHideValidationDialog;
end;
```

```
procedure GetHideValidationDialog(): Boolean
begin
    exit(HideValidationDialog);
end;
```

PS. If in BC20.1 such changes was introduced also on other tables, they could be also non-internal.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40912.
