### ISSUE TITLE
[Event Request] Application “Tests-SCM”, Codeunit 137140 "SCM Inventory Documents"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#18031]
[Event Request]Application “Tests-SCM”, Codeunit 137140 "SCM Inventory Documents"

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure:
![pic1](https://user-images.githubusercontent.com/45795262/168623419-c454f487-f17b-4a84-bc43-bd5accb7b387.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40749.
