### ISSUE TITLE
[Event Request] Table 5092 Opportunity - OnBeforeFinishWizard

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#18034]
Please add the event OnBeforeFinishWizard() in Table 5092 Opportunity like this:

```
procedure FinishWizard()
var
    ActivateFirstStage: Boolean;
begin
    OnBeforeFinishWizard(Rec, OppEntry); // <-- new event
    [...]
end;
```
The new event:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeFinishWizard(var Opportunity: Record Opportunity; var OppEntry: Record "Opportunity Entry")
begin
end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40744.
