### ISSUE TITLE
[Event request] Codeunit 80 to disable COMMITs

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#1804]
To migrate a NAV ISV add-on to BC:

We need a way to disable COMMITs under certain scenarios when in non-preview mode.  Could we get an event right before each COMMIT call that passes a variable we can set to bypass the commit if needed?  For example:    

IF NOT PreviewMode THEN BEGIN
  MODIFY;     
  ProceedWithCommit := TRUE;             //NEW     
  OnBeforeCommit(ProceedWithCommit);     //NEW     
  IF ProceedWithCommit THEN              //NEW       
    COMMIT;   
END;

**Comment by RHansenEpimatic** [comment]
I realized we can accomplish this with no additional events.

**Comment by gregoral** [comment]
Hi, this might be ok if your extension is the only one on the system.
But other extensions might execute a COMMIT just about anywhere.

Currently any extension can subscribe to any event and add a COMMIT,
just because they have a reason to do it.

br

**Comment by RHansenEpimatic** [comment]
Understood.  In the event our product conflicts with another product, we will reach out to the other ISV vendor to work toward  resolution.

**Comment by RHansenEpimatic** [comment]
100% agree on all your points.
