### ISSUE TITLE
[Function Expose] Codeunit 8906 - Email Editor - GetRelatedAttachments

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#18049]
Dear ALAppExtensions team,

Through this issue we would like to request procedure `GetRelatedAttachments(EmailMessageId: Guid; var EmailRelatedAttachmentOut: Record "Email Related Attachment")` to be exposed.
We would like to retrieve the attachments for when we are sending e-mails with attachments via code. It is now not possible to retrieve the related attachments.
Could you please expose this procedure or add a wrapper procedure in another public codeunit that exposes this?

As another alternative, perhaps you could expose the following event publishers which allow for retrieving the attachments?
```
    /// <summary>
    /// Integration event to get the names and IDs of attachments related to a source record. 
    /// </summary>
    /// <param name="SourceTableId">The table number of the source record.</param>
    /// <param name="SourceSystemID">The system ID of the source record.</param>
    /// <param name="EmailRelatedAttachments">Out parameter to return attachments related to the source record.</param>
    [IntegrationEvent(false, false)]
    internal procedure OnFindRelatedAttachments(SourceTableId: Integer; SourceSystemID: Guid; var EmailRelatedAttachments: Record "Email Related Attachment")
    begin
    end;

    /// <summary>
    /// Integration event that requests an attachment to be added to an email.
    /// </summary>
    /// <param name="AttachmentTableID">The table number of the attachment.</param>
    /// <param name="AttachmentSystemID">The system ID of the attachment.</param>
    /// <param name="MessageID">The ID of the email to add an attachment to.</param>
    [IntegrationEvent(false, false)]
    internal procedure OnGetAttachment(AttachmentTableID: Integer; AttachmentSystemID: Guid; MessageID: Guid)
    begin
    end;
 ```
 
 Thank you in advance. This would be very useful for extensibility with regards to e-mailing from BC.

**Comment by darjoo** [comment]
Hi @rvabbekkum, we're currently in the process of adding events like the following `OnBeforeOpenEmailEditor` and `OnBeforeSendEmail` (Happens before the email is sent). Is it at either points where you want to retrieve the related attachments? I'm considering whether a codeunit used within one of those events would suffice for your case. I'd like to avoid sprinkling events for everything :)
