### ISSUE TITLE
[Event Request] codeunit 99000832 "Sales Line-Reserve" - TransferSalesLineToItemJnlLineOnBeforeInitRecordSet

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18059]
Please add new event in Codeunit 99000832 in function TransferSalesLineToItemJnlLine

```
[IntegrationEvent(false, false)]
local procedure TransferSalesLineToItemJnlLineOnBeforeInitRecordSet(var OldReservEntry: Record "Reservation Entry")
begin
end;

```

```
if ItemJnlLine."Invoiced Quantity" <> 0 then
	CreateReservEntry.SetUseQtyToInvoice(true);

TransferSalesLineToItemJnlLineOnBeforeInitRecordSet(OldReservEntry);
if ReservEngineMgt.InitRecordSet(OldReservEntry) then begin
	repeat
		IsHandled := false;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40804.
