### ISSUE TITLE
[Request-For-External] Report 93 "Create Fiscal Year" - Variable FiscalYearStartDate

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#18062]
Hi, could you please change the protection level of the **FiscalYearStartDate** variable on report 93 (**Create Fiscal Year**) to a **protected** one?
```AL
    protected var
        FiscalYearStartDate: Date;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40912.
