### ISSUE TITLE
[Event Request] Codeunit 5940 ServContractManagement - OnLookupServItemOnBeforeFilterByShipToCode

### ISSUE THREAD

**Issue by juacefer** [microsoft/ALAppExtensions#18068]
Please, add a new event in procedure LookupServItemNo

procedure LookupServItemNo(var ServiceContractLine: Record "Service Contract Line")
var
	ServContractHeader: Record "Service Contract Header";
	ServItem: Record "Service Item";
	ServItemList: Page "Service Item List";
	IsHandled: Boolean;
begin
	Clear(ServItemList);
	if ServItem.Get(ServiceContractLine."Service Item No.") then
		ServItemList.SetRecord(ServItem);
	ServItem.Reset();
	ServItem.SetCurrentKey("Customer No.", "Ship-to Code");
	ServItem.FilterGroup(2);
	IsHandled := false;
	OnLookupServItemNoOnBeforeFilterByCustomerNo(ServItem, ServiceContractLine, IsHandled);
	if not IsHandled then
		if ServiceContractLine."Customer No." <> '' then
			ServItem.SetRange("Customer No.", ServiceContractLine."Customer No.");

	ServItem.FilterGroup(0);
	**IsHandled := false;
	OnLookupServItemOnBeforeFilterByShipToCode(ServItem, ServiceContractLine, IsHandled);
	if not IsHandled then**
		if ServContractHeader.Get(ServiceContractLine."Contract Type", ServiceContractLine."Contract No.") and
		   (ServiceContractLine."Ship-to Code" = ServContractHeader."Ship-to Code")
		then
			ServItem.SetRange("Ship-to Code", ServiceContractLine."Ship-to Code");
	ServItemList.SetTableView(ServItem);
	ServItemList.LookupMode(true);
	if ServItemList.RunModal = ACTION::LookupOK then begin
		ServItemList.GetRecord(ServItem);
		ServiceContractLine.Validate("Service Item No.", ServItem."No.");
	end;
end;

The new event:

[IntegrationEvent(false, false)]
local procedure OnLookupServItemOnBeforeFilterByShipToCode(var ServItem: Record "Service Item"; var ServiceContractLine: Record "Service Contract Line"; var IsHandled: Boolean)
begin
end;

Best regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40900.
