### ISSUE TITLE
[Event Request] Table 5050 Contact - OnCreateVendorLinkOnAfterCreateLink

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#18078]
Hi, would it be possible to get an **OnCreateVendorLinkOnAfterCreateLink** event in table 5050 (**Contact**), like this:
```AL
    procedure CreateVendorLink()
    var
        ContBusRel: Record "Contact Business Relation";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCreateVendorLink(Rec, IsHandled);
        if not IsHandled then begin
            CheckForExistingRelationships(ContBusRel."Link to Table"::Vendor);
            CheckIfPrivacyBlockedGeneric;
            TestField("Company No.");
            RMSetup.Get();
            RMSetup.TestField("Bus. Rel. Code for Vendors");
            CreateLink(
              PAGE::"Vendor Link",
              RMSetup."Bus. Rel. Code for Vendors",
              ContBusRel."Link to Table"::Vendor);

            OnCreateVendorLinkOnAfterCreateLink(Rec, xRec); // New Event
        end;
    end;
```
```AL
    [IntegrationEvent(false, false)]
    local procedure OnCreateVendorLinkOnAfterCreateLink(var Contact: Record Contact; xContact: Record Contact)
    begin
    end;
```
#18077 
Thanks!

**Comment by dannoe** [comment]
``ContBusRel`` is only used to reference the "Link to Table" enum in this code. This doesn't make sense as an event parameter.

**Comment by AndriiSeverin** [comment]
@dannoe 
Thanks!
I completely agree, it makes no sense to add this parameter. Also, it is not used in our customization. We just want to make the event more generic and similar to the requested event in the **CreateCustomerLink** procedure where this parameter can be used for some reason (for example, to apply some extra filters).
The signature of the requested event has been updated.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40859.
