### ISSUE TITLE
local procedure CopyAttachments - codeunit 1173 Document Attachment Management

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#18079]
Hopefully this is the right forum ...

is there a reason this procedure is local? I have copied it line-for-line into a PTE codeunit and it works without any adjustment. (in same codeunit there is procedure CopyAttachments**ForPostedDocuments** and it is global.)

maybe you could leave it as local, but then add a global procedure that calls the local? all the global procedure would need would be parameters for From/ToRecRef:

procedure CopyAttachmentsGlobal(var FromRecRef: RecordRef; var ToRecRef: RecordRef) -- you can probably think of a better name
begin
    CopyAttachments(FromRecRef, ToRecRef);
end;

Thx.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40912.
