### ISSUE TITLE
event request - codeunit 130411 "Sys. Warmup Scenarios" - WarmupInvoicePosting() - OnBefore and OnAfter events

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#18071]
This keeps causing us to get confused when subscribing to `Sales-Post` events. It runs `OnAfterCompanyOpen` if SaaS. It has no way to stop it firing junk events that we have no easy way to ignore. There are no fields on the resulting `Sales Header`/`Line` saying 'this is a test document; you can ignore it'...

It also only runs `if not CompanyInformationMgt.IsDemoCompany`, buuut we often develop in CRONUS, and might want to demonstrate new functionality there too - and so want to be able to ignore the warm-up invoices during this, without having to create a new company or whatever.

Thus can we please get `OnBefore` and `OnAfter` events, that we can use to suppress our subscribers during this 'warm-up'?

```al
    [Test]
    procedure WarmupInvoicePosting()
    var
        Customer: Record Customer;
        Item: Record Item;
        SalesHeader: Record "Sales Header";
    begin
        if not Customer.FindFirst then
            exit;

        Item.SetFilter(Inventory, '<>%1', 0);
        if not Item.FindFirst then
            exit;

        OnWarmupInvoicePostingBeforeCreateSalesInvoice(); // NEW

        CreateSalesInvoice(SalesHeader, Customer, Item);
        PostSalesInvoice(SalesHeader);

        OnWarmupInvoicePostingAfterPostSalesInvoice(); // NEW
    end;

    // NEW:

    [IntegrationEvent(false, false)]
    local procedure OnWarmupInvoicePostingBeforeCreateSalesInvoice();

    [IntegrationEvent(false, false)]
    local procedure OnWarmupInvoicePostingAfterPostSalesInvoice();
```

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41238.
