### ISSUE TITLE
[Exposure Request] codeunit 99000834 "Purch. Line-Reserve" - RetrieveInvoiceSpecification2

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18098]
Please make function RetrieveInvoiceSpecification2 externally available.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40912.
