### ISSUE TITLE
[request-for-external] page 232 "Apply Customer Entries"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#18099]
Please make the following functions protected
```
protected procedure CalcApplnRemainingAmount(Amount: Decimal): Decimal
protected procedure FindAmountRounding()
protected procedure HandleChosenEntries(Type: Enum "Customer Apply Calculation Type"; CurrentAmount: Decimal; CurrencyCode: Code[10]; PostingDate: Date)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40912.
