### ISSUE TITLE
[Event Request] codeunit 99000832 "Sales Line-Reserve" - OnBeforeDeleteInvoiceSpecFromLine

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18094]
Please add new event at the start of the function DeleteInvoiceSpecFromLine

```
local procedure DeleteInvoiceSpecFromLine(SalesLine: Record "Sales Line")
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeDeleteInvoiceSpecFromLine(SalesLine, IsHandled);
    if IsHandled then
        exit;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeDeleteInvoiceSpecFromLine(SalesLine: Record "Sales Line"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40859.
