### ISSUE TITLE
[Event Request] codeunit 99000832 "Sales Line-Reserve" - OnBeforeRetrieveInvoiceSpecification 

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18095]
Please extend the event OnBeforeRetrieveInvoiceSpecification with parameter TempInvoicingSpecification. Also please include sender in the event.

```
[IntegrationEvent(true, false)]
local procedure OnBeforeRetrieveInvoiceSpecification(var SalesLine: Record "Sales Line"; var TempInvoicingSpecification: Record "Tracking Specification" temporary; var OK: Boolean; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40859.
