### ISSUE TITLE
[Event Request] codeunit 99000832 "Sales Line-Reserve" - OnBeforeDeleteInvoiceSpecFromHeader

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18091]
Please add new event at the start of the function DeleteInvoiceSpecFromHeader

```
procedure DeleteInvoiceSpecFromHeader(var SalesHeader: Record "Sales Header")
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeDeleteInvoiceSpecFromHeader(SalesHeader, IsHandled);
    if IsHandled then
        exit;

```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeDeleteInvoiceSpecFromHeader(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
begin
end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40859.
