### ISSUE TITLE
[request-for-external] report 5084 "Email Merge"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#18109]
Please make variable SegmentLine protected

```
protected var
        CompanyInformation: Record "Company Information";
        Contact: Record Contact;
        SalespersonPurchaser: Record "Salesperson/Purchaser";
        Content: Text;
        Contact_Mail_Address: Text;
        Formal_Salutation: Text;
        Informal_Salutation: Text;
        Document_Date: Text;
        SegmentLine: Record "Segment Line";   //NEW VARIABLE
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
