### ISSUE TITLE
[request-for-external] codeunit 1313 "Correct Posted Purch. Invoice"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#18107]
Please make function ErrorHelperHeader Global

```
procedure ErrorHelperHeader(HeaderErrorType: Enum "Correct Purch. Inv. Error Type"; PurchInvHeader: Record "Purch. Inv. Header")
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40912.
