### ISSUE TITLE
[Event Request] codeunit 99000815 "Reservation-Check Date Confl." - OnPurchLineCheckOnBeforeUpdateDate

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18101]
Please Include sender in the Event OnPurchLineCheckOnBeforeUpdateDate
```
[IntegrationEvent(true, false)]
local procedure OnPurchLineCheckOnBeforeUpdateDate(var ReservationEntry: Record "Reservation Entry"; PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40908.
