### ISSUE TITLE
[event-request] Codeunit 70 "Purch.-Calc.Discount": OnCalculateInvoiceDiscountOnBeforeCheckVendInvDiscServiceCharge 

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#18117]
Similar to the publisher OnCalculateInvoiceDiscountOnBeforeCheckCustInvDiscServiceCharge in sales codeunit "Sales-Calc.Discount" wie need a publisher after getting the vendor invoice disc.

In procedure CalculateInvoiceDiscount:
![image](https://user-images.githubusercontent.com/34675109/169065865-44d8ffa6-10b5-4b8f-abf8-c1bec17d1d5a.png)

Call:
`OnCalculateInvoiceDiscountOnBeforeCheckVendInvDiscServiceCharge(VendInvDisc, PurchHeader, CurrencyDate, ChargeBase);`

Signature:
```
    [IntegrationEvent(false, false)]
    local procedure OnCalculateInvoiceDiscountOnBeforeCheckVendInvDiscServiceCharge(var VendInvDisc: Record "Vendor Invoice Disc."; var PurchHeader: Record "Purchase Header"; CurrencyDate: Date; ChargeBase: Decimal)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40908.
