### ISSUE TITLE
[Event request] Codeunit 90 to disable COMMITs

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#1811]
To migrate a NAV ISV add-on to BC:

We need a way to disable COMMITs under certain scenarios when in non-preview mode.  Could we get an event right before each COMMIT call that passes a variable we can set to bypass the commit if needed?  For example:    

.IF NOT PreviewMode THEN BEGIN
.  MODIFY;     
.  ProceedWithCommit := TRUE;             //NEW     
.  OnBeforeCommit(ProceedWithCommit);     //NEW     
.  IF ProceedWithCommit THEN              //NEW       
.    COMMIT;   
.END;

**Comment by AlexanderYakunin** [comment]
May I ask you a question which version you are looking into? You should use latest code base for BC Preview drops to make your requests. If you do so, you will see that many of you akss already addressed.

**Comment by RHansenEpimatic** [comment]
﻿Thanks Alexander.  Do I just grab the package with the most recent “Content Modified Date” in Collaborate?  Or am I not in the right place?

[cid:image001.png@01D4E530.9C25F070]

Regards,

Rob Hansen, CPA, CMA
epimatic

PH: 519.594.0133 | FAX: 519.489.2712
rhansen@epimatic.com<mailto:rhansen@epimatic.com> | http://www.epimatic.com<http://www.epimatic.com/> | Skype: rhansen74

**Comment by AlexanderYakunin** [comment]
http://aka.ms/collaborate and use bcsandbox-master

**Comment by RHansenEpimatic** [comment]
Thanks Alexander…I don’t see a package for that though?  Here is what I see:

[cid:image001.png@01D4E531.6AFDC080]

Regards,

Rob Hansen, CPA, CMA
epimatic

PH: 519.594.0133 | FAX: 519.489.2712
rhansen@epimatic.com<mailto:rhansen@epimatic.com> | http://www.epimatic.com<http://www.epimatic.com/> | Skype: rhansen74

**Comment by AlexanderYakunin** [comment]
Take the latest for Spring 2019

**Comment by RHansenEpimatic** [comment]
﻿Hi Alexander –

I didn’t want to impact my current environment, so I ran the demo installation option in the latest package.  Do you know what the sa password in SQL gets set to when that option is run?

Regards,

Rob Hansen, CPA, CMA
epimatic

PH: 519.594.0133 | FAX: 519.489.2712
rhansen@epimatic.com<mailto:rhansen@epimatic.com> | http://www.epimatic.com<http://www.epimatic.com/> | Skype: rhansen74

**Comment by RHansenEpimatic** [comment]
I realized I can accomplish this with no additional events.  I am currently reviewing the latest release and so far i've only found one of my logged issues has been addressed...i have a bunch more to check though.

**Comment by RHansenEpimatic** [comment]
Hi Alexander –

I reviewed all of my requests (around 34 or so) against the build from March 19th, and I only see two of my requests addressed.  Am I looking at the right build?  You said “many” are addressed?

Also, note that issues 1483 and 1495 were marked as closed (ships in future update) but they have not been addressed in the build I have.  Again, let me know if I’m working with the incorrect build.

Regards,

Rob Hansen, CPA, CMA
epimatic

PH: 519.594.0133 | FAX: 519.489.2712
rhansen@epimatic.com<mailto:rhansen@epimatic.com> | http://www.epimatic.com<http://www.epimatic.com/> | Skype: rhansen74
