### ISSUE TITLE
[Event Request] Table 5093 "Opportunity Entry" - OnBeforeStartWizard

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#18112]
Please add the event OnBeforeStartWizard() in Table 5093 "Opportunity Entry" like this:

```
local procedure StartWizard()
var
    CloseOpportunityPageId: Integer;
begin
    CloseOpportunityPageId := PAGE::"Close Opportunity";
    OnBeforeStartWizard(Rec, CloseOpportunityPageId); // <- new event
    if CloseOpportunityPageId <> 0 then begin
        Insert;
        if Page.RunModal(CloseOpportunityPageId, Rec) = Action::OK then;
    end;
end;
```
The new event:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeStartWizard(var OpportunityEntry: Record "Opportunity Entry"; var CloseOpportunityPageId: Integer)
begin
end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40859.
