### ISSUE TITLE
[request-for-external] table 81 "Gen. Journal Line"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#18115]
Please make function UpdateDescription protected

```
protected procedure UpdateDescription(Name: Text[100])
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40912.
