### ISSUE TITLE
[event-request] Table 36 "Sales Header": OnBeforeCheckPrepmtInfo

### ISSUE THREAD

**Issue by AMJSMEDDAH** [microsoft/ALAppExtensions#18119]
Similar to OnBeforeCheckShipmentInfo in "Sales Header" table, we need a publisher before checking the prepmt info.

In Procedure "CheckPremptInfo"

Call:
![image](https://user-images.githubusercontent.com/105815056/169116590-e9e30335-1b6f-4c1d-b2a9-e71774c80ba8.png)

Signature
![image](https://user-images.githubusercontent.com/105815056/169116716-60466caa-f9b5-4120-9124-e721798ef511.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40862.
