### ISSUE TITLE
[Extensibility Request] local to global codeunit 80 "Sales-Post" - RoundAmount

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18121]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!
[Extensibility Request] Codeunit 80 "Sales-Post" - Procedure from Internal to Global

```
local procedure RoundAmount(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; SalesLineQty: Decimal)
```

**Comment by AlexanderYakunin** [comment]
Hello! Can you provide justification with code sample why do you need this local procedure as global?

**Comment by MH1612** [comment]
We analyze again and try to find another solution.
