### ISSUE TITLE
[Extensibility Request] local to global Codeunit 5407 "Prod. Order Status Management" - OutputExists

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18128]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

[Extensibility Request] Codeunit 5407 "Prod. Order Status Management" - Procedure from Internal to Global
```
local procedure OutputExists(ProdOrderLine: Record "Prod. Order Line"): Boolean
    var
        ItemLedgEntry: Record "Item Ledger Entry";
    begin
        ItemLedgEntry.SetCurrentKey("Order Type", "Order No.", "Order Line No.");
        ItemLedgEntry.SetRange("Order Type", ItemLedgEntry."Order Type"::Production);
        ItemLedgEntry.SetRange("Order No.", ProdOrderLine."Prod. Order No.");
        ItemLedgEntry.SetRange("Order Line No.", ProdOrderLine."Line No.");
        ItemLedgEntry.SetRange("Entry Type", ItemLedgEntry."Entry Type"::Output);
        if ItemLedgEntry.FindFirst() then begin
            ItemLedgEntry.CalcSums(Quantity);
            if ItemLedgEntry.Quantity <> 0 then
                exit(true)
        end;
        exit(false);
    end;
```

**Comment by MH1612** [comment]
@JesperSchulz Can you please check this? Thank you!

**Comment by AlexanderYakunin** [comment]
This is done but request was not closed due to sync issue.

**Comment by JesperSchulz** [comment]
We had some issues with our automation which reports back progress from our internal systems to these GitHub issues. Some issues may not have been updated, such as this one - even though they were successfully processed! We will look at getting that fixed in the next weeks. Sorry about the inconvenience!
