### ISSUE TITLE
[Extensibility Request] local to global page 99000914 "Change Production Order Status" - BuildForm

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18136]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

[Extensibility Request] page 99000914 "Change Production Order Status" - Procedure from Internal to Global

```
local procedure BuildForm()
    begin
        FilterGroup(2);
        SetRange(Status, ProdOrderStatus);
        FilterGroup(0);

        if StartingDate <> 0D then
            SetFilter("Starting Date", '..%1', StartingDate)
        else
            SetRange("Starting Date");

        if EndingDate <> 0D then
            SetFilter("Ending Date", '..%1', EndingDate)
        else
            SetRange("Ending Date");

        CurrPage.Update(false);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40912.
