### ISSUE TITLE
[Extensibility Request] local to global codeunit 333 "Req. Wksh.-Make Order" - PrintPurchOrder

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18131]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

[Extensibility Request] codeunit 333 "Req. Wksh.-Make Order" - Procedure from Internal to Global

```
local procedure PrintPurchOrder(PurchHeader: Record "Purchase Header")
    var
        CarryOutAction: Codeunit "Carry Out Action";
    begin
        if PurchHeader."No." <> '' then begin
            CarryOutAction.SetPrintOrder(PrintPurchOrders);
            CarryOutAction.PrintPurchaseOrder(PurchHeader);
        end;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40912.
