### ISSUE TITLE
[Event Request] Update OnBeforeSetGLAccGLEntryFilters in codeunit 8 AccSchedManagement

### ISSUE THREAD

**Issue by ivandjordjevic** [microsoft/ALAppExtensions#18146]
Hey all,

I am missing GLEntry parameter for OnBeforeSetGLAccGLEntryFilters publisher in AccSchedManagement, currently it is:
````
[IntegrationEvent(false, false)]
local procedure OnBeforeSetGLAccGLEntryFilters(var GLAcc: Record "G/L Account"; var AccSchedLine: Record "Acc. Schedule Line"; var ColumnLayout: Record "Column Layout"; UseBusUnitFilter: Boolean; UseDimFilter: Boolean; var IsHandled: Boolean)
begin
end;
````
and it should be:
````
[IntegrationEvent(true, false)]
local procedure OnBeforeSetGLAccGLEntryFilters(var GLAccount: Record "G/L Account"; var GLEntry: Record "G/L Entry"; var AccSchedLine: Record "Acc. Schedule Line"; var ColumnLayout: Record "Column Layout"; UseBusUnitFilter: Boolean; UseDimFilter: Boolean; var IsHandled: Boolean; var AccountScheduleLine: Record "Acc. Schedule Line")
begin
end;
````
Also it is missing IncludeSender which is needed here since most of the local functions inside this codeunit are using global variables.

I am looking at the insider build: Platform 21.0.40380.0 + Application 21.0.40423.0

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40908.
