### ISSUE TITLE
[Event Request] table 1235 "XML Buffer" - OnBeforeDownload

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18149]
New Event in function Download:

```
procedure Download() Success: Boolean
var
    FileManagement: Codeunit "File Management";
    ServerTempFileName: Text;
    IsHandled: Boolean;
begin
    IsHandled := true;
    OnBeforeDownload(Success, IsHandled, Rec);
    if IsHandled then
        exit;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeDownload(var Success: Boolean; var IsHandled: Boolean; var XMLBuffer: Record "XML Buffer")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47942.
