### ISSUE TITLE
[Event Request] Table 5092 Opportunity - OnBeforeCheckCampaign

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#18155]
Please add the event OnBeforeCheckCampaign() in Table 5092 Opportunity like this:

```
local procedure CheckCampaign()
var
    Campaign: Record Campaign;
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeCheckCampaign(Rec, IsHandled);
    if IsHandled then
        exit;
    [...]
end;
```
The new event:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckCampaign(var Opportunity: Record Opportunity; var IsHandled: Boolean)
begin
end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 40900.
