### ISSUE TITLE
[Event change request] Codeunit 225 OnBeforeSelectCustLedgEntry

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#1815]
To migrate a NAV ISV add-on to BC:

We need the OnBeforeSelectCustLedgEntry event updated to pass in the CustLedgEntry variable.

**Comment by AlexanderYakunin** [comment]
It does not make sense as CustledgEntry is not initialized at this stage.

**Comment by RHansenEpimatic** [comment]
This is a valid request.  There is no "RESET" before the CustLedgEntry.SETCURRENTKEY, so if you pass the CustLedgEntry variable into OnBeforeSelectCustLedgEntry, i can add my additional filter which will be persisted through the function.

Can you please reopen this?

**Comment by RHansenEpimatic** [comment]
Hi Alexander –

I posted the reply below on issue 1815.  I don’t think I have the ability to reopen it though…can you?  Another option would be to add a new event right after the “CustLedgEntry.SETRANGE(Open,TRUE)” line.

This is a valid request. There is no "RESET" before the CustLedgEntry.SETCURRENTKEY, so if you pass the CustLedgEntry variable into OnBeforeSelectCustLedgEntry, i can add my additional filter which will be persisted through the function.
Can you please reopen this?


Regards,

Rob Hansen, CPA, CMA
epimatic

PH: 519.594.0133 | FAX: 519.489.2712
rhansen@epimatic.com<mailto:rhansen@epimatic.com> | http://www.epimatic.com<http://www.epimatic.com/> | Skype: rhansen74

**Comment by AlexanderYakunin** [comment]
You mwill not get OnBeforeSelectCustLedgEntry , this is against of our best practices. Instead you will get OnAfterSetFilters event to add you filters. You will see it in next builds I suppose.

**Comment by RHansenEpimatic** [comment]
That's perfect - thanks Alexander.
