### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" OnCreateDimOnBeforeUpdateGlobalDimFromDimSetID

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#18169]
Hello,
would it be possible to get an event OnCreateDimOnBeforeUpdateGlobalDimFromDimSetID(Rec) like this:
<pre>
    procedure CreateDim(Type1: Integer; No1: Code[20]; Type2: Integer; No2: Code[20]; Type3: Integer; No3: Code[20]; Type4: Integer; No4: Code[20])
    var
        SourceCodeSetup: Record "Source Code Setup";
        TableID: array[10] of Integer;
        No: array[10] of Code[20];
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCreateDim(Rec, IsHandled, CurrFieldNo);
        if IsHandled then
            exit;

        SourceCodeSetup.Get();
        TableID[1] := Type1;
        No[1] := No1;
        TableID[2] := Type2;
        No[2] := No2;
        TableID[3] := Type3;
        No[3] := No3;
        TableID[4] := Type4;
        No[4] := No4;
        OnAfterCreateDimTableIDs(Rec, CurrFieldNo, TableID, No);

        "Shortcut Dimension 1 Code" := '';
        "Shortcut Dimension 2 Code" := '';
        GetPurchHeader;
        "Dimension Set ID" :=
          DimMgt.GetRecDefaultDimID(
            Rec, CurrFieldNo, TableID, No, SourceCodeSetup.Purchases,
            "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code", PurchHeader."Dimension Set ID", DATABASE::Vendor);
        // Event request
        OnCreateDimOnBeforeUpdateGlobalDimFromDimSetID(Rec);
        // Event request
        DimMgt.UpdateGlobalDimFromDimSetID("Dimension Set ID", "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");

        OnAfterCreateDim(Rec, CurrFieldNo, xRec);
    end;

    // Event request
    [IntegrationEvent(false, false)]
    local procedure OnCreateDimOnBeforeUpdateGlobalDimFromDimSetID(var PurchaseLine: Record "Purchase Line")
    begin
    end;
    // Event request
</pre>

**Comment by AlexanderYakunin** [comment]
This procedure is obsoleted in 20.0 and replaced by new implementation

procedure CreateDim(DefaultDimSource: List of [Dictionary of [Integer, Code[20]]])
