### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" OnInitHeaderDefaultsOnBeforeSetVATBusPostingGroup

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#18166]
Hello,
would it be possible to get an event OnInitHeaderDefaultsOnBeforeSetVATBusPostingGroup(Rec, IsHandled) like this:
<pre>
    local procedure InitHeaderDefaults(PurchHeader: Record "Purchase Header"; var TempPurchLine: Record "Purchase Line" temporary)
    var
        IsHandled: Boolean;
    begin
        CheckBuyFromVendorNo(PurchHeader);

        "Buy-from Vendor No." := PurchHeader."Buy-from Vendor No.";
        "Currency Code" := PurchHeader."Currency Code";
        "Expected Receipt Date" := PurchHeader."Expected Receipt Date";
        "Shortcut Dimension 1 Code" := PurchHeader."Shortcut Dimension 1 Code";
        "Shortcut Dimension 2 Code" := PurchHeader."Shortcut Dimension 2 Code";
        IsHandled := false;
        OnBeforeUpdateLocationCode(Rec, IsHandled);
        if IsHandled then
            "Location Code" := PurchHeader."Location Code"
        else
            if not IsNonInventoriableItem then
                "Location Code" := PurchHeader."Location Code";
        "Transaction Type" := PurchHeader."Transaction Type";
        "Transport Method" := PurchHeader."Transport Method";
        "Pay-to Vendor No." := PurchHeader."Pay-to Vendor No.";
        "Price Calculation Method" := PurchHeader."Price Calculation Method";
        "Gen. Bus. Posting Group" := PurchHeader."Gen. Bus. Posting Group";
        // Event request
        IsHandled := false;
        OnInitHeaderDefaultsOnBeforeSetVATBusPostingGroup(Rec, IsHandled);
        if not IsHandled then
            "VAT Bus. Posting Group" := PurchHeader."VAT Bus. Posting Group";
        // Event request
        ...

    // Event request
    [IntegrationEvent(false, false)]
    local procedure OnInitHeaderDefaultsOnBeforeSetVATBusPostingGroup(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;
    // Event request
</pre>

**Comment by AlexanderYakunin** [comment]
Already implemented
