### ISSUE TITLE
[Request for external] Table Payment Line Modify Scope OnPrem -> Cloud on procedure SetUpNewLine

### ISSUE THREAD

**Issue by calliopedavidroldan** [microsoft/ALAppExtensions#18162]
Hi,

We need to use the procedure SetUpNewLine from table Payment Line on cloud target.

Please change the scope.

**Comment by calliopedavidroldan** [comment]
Hello,

Do you know if this request will be taken into account and in which BC version ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45464.
