### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" OnValidateVATProdPostingGroupOnAfterTestStatusOpen

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#18164]
Hello,
would it be possible to get an event OnVATProdPostingGroupOnAfterTestStatusOpen(Rec, IsHandled) like this:

<pre>
        field(90; "VAT Prod. Posting Group"; Code[20])
        {
            Caption = 'VAT Prod. Posting Group';
            TableRelation = "VAT Product Posting Group";

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                TestStatusOpen;
                // Event request
                IsHandled := false;
                OnValidateVATProdPostingGroupOnAfterTestStatusOpen(Rec, IsHandled);
                if not IsHandled then begin
                // Event request

                    CheckPrepmtAmtInvEmpty();
                    VATPostingSetup.Get("VAT Bus. Posting Group", "VAT Prod. Posting Group");
                    OnValidateVATProdPostingGroupOnAfterVATPostingSetupGet(VATPostingSetup);
                    "VAT Difference" := 0;
                    GetPurchHeader;
                    "VAT %" := VATPostingSetup."VAT %";
                    "VAT Calculation Type" := VATPostingSetup."VAT Calculation Type";
                    if "VAT Calculation Type" = "VAT Calculation Type"::"Full VAT" then
                        Validate("Allow Invoice Disc.", false);
                    "VAT Identifier" := VATPostingSetup."VAT Identifier";

                    IsHandled := false;
                    OnValidateVATProdPostingGroupOnBeforeCheckVATCalcType(Rec, VATPostingSetup, IsHandled);
                    if not IsHandled then
                        case "VAT Calculation Type" of
                            "VAT Calculation Type"::"Reverse Charge VAT",
                            "VAT Calculation Type"::"Sales Tax":
                                "VAT %" := 0;
                            "VAT Calculation Type"::"Full VAT":
                                begin
                                    TestField(Type, Type::"G/L Account");
                                    TestField("No.", VATPostingSetup.GetPurchAccount(false));
                                end;
                        end;

                    if PurchHeader."Prices Including VAT" and (Type in [Type::Item, Type::Resource]) then
                        Validate("Direct Unit Cost",
                          Round(
                            "Direct Unit Cost" * (100 + "VAT %") / (100 + xRec."VAT %"),
                            Currency."Unit-Amount Rounding Precision"));
                    UpdateAmounts;
                // Event request
                end;
                // Event request
            end;
        }

    // Event request
    [IntegrationEvent(false, false)]
    local procedure OnValidateVATProdPostingGroupOnAfterTestStatusOpen(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;
    // Event request

</pre>

**Comment by AlexanderYakunin** [comment]
Already implemented
