### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" OnAddItemOnBeforeInsert

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#18168]
Hello,
would it be possible to get an event OnAddItemOnBeforeInsert(PurchLine) like this:
<pre>
    procedure AddItem(var PurchLine: Record "Purchase Line"; ItemNo: Code[20])
    var
        LastPurchLine: Record "Purchase Line";
        TransferExtendedText: Codeunit "Transfer Extended Text";
    begin
        PurchLine.Init();
        PurchLine."Line No." += 10000;
        PurchLine.Validate(Type, Type::Item);
        PurchLine.Validate("No.", ItemNo);
        // Event request
        OnAddItemOnBeforeInsert(PurchLine);
        // Event request
        PurchLine.Insert(true);
        if TransferExtendedText.PurchCheckIfAnyExtText(PurchLine, false) then begin
            TransferExtendedText.InsertPurchExtTextRetLast(PurchLine, LastPurchLine);
            PurchLine."Line No." := LastPurchLine."Line No."
        end;
        OnAfterAddItem(PurchLine, LastPurchLine);
    end;

    // Event request
    [IntegrationEvent(false, false)]
    local procedure OnAddItemOnBeforeInsert(var PurchaseLine: Record "Purchase Line")
    begin
    end;
    // Event request
</pre>

**Comment by AlexanderYakunin** [comment]
This is already implemented
