### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" OnValidateNoOnBeforeAssignQtyFromXRec

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#18163]
Hello,
in field(6; "No.") - Trigger OnValidate would it be possible to get an event OnValidateNoOnBeforeAssignQtyFromXRec(Rec, xRec, IsHandled); with the IsHandled-pattern like this:
<pre>
        field(6; "No."; Code[20])
            trigger OnValidate()
                ...
                if HasTypeToFillMandatoryFields then begin
                    PlanPriceCalcByField(FieldNo("No."));
                    // Event request
                    IsHandled := false;
                    OnValidateNoOnBeforeAssignQtyFromXRec(Rec, xRec, IsHandled);
                    if not IsHandled then
                        Quantity := xRec.Quantity;
                    // Event request
                    OnValidateNoOnAfterAssignQtyFromXRec(Rec, TempPurchLine);
                    Validate("Unit of Measure Code");
                    InitOutstandingAndQtyToShipReceive(TempPurchLine);
                    UpdateWithWarehouseReceive;
                    UpdateJobFields();
                end;
                ...

    [IntegrationEvent(false, false)]
    local procedure OnValidateNoOnBeforeAssignQtyFromXRec(var PurchaseLine: Record "Purchase Line"; var xPurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

</pre>

**Comment by swecompany** [comment]
Hello,
is there any news on this request?

**Comment by AlexanderYakunin** [comment]
This is already implemented
