### ISSUE TITLE
[Request for external] Codeunit Sales Line-Reserve Modify Scope OnPrem -> Cloud on procedure CopyReservEntryToTemp and CopyReservEntryFromTemp

### ISSUE THREAD

**Issue by calliopedavidroldan** [microsoft/ALAppExtensions#18161]
Hi,

We need to use the procedures CopyReservEntryToTemp and CopyReservEntryFromTemp from codeunit Sales Line-Reserve on cloud target.

Please change the scope.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45057.
