### ISSUE TITLE
[Request for External] report 99000758 "Compare List" - Protected variables

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18178]
Hello, we need the following currently global variable/-s to be set as protected. Can you please check this? Thank you!

```
protected var
   Item: array[2] of Record Item;
```

**Comment by MH1612** [comment]
@JesperSchulz Can you please check this? Thank you!

**Comment by JesperSchulz** [comment]
GitHub issue wasn't updated due to issues with automation. A fix for your request will release with 21.0.
