### ISSUE TITLE
Table 5405 - Production Order - Variant Code Table Relation

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#18174]
HI,

On Table 5405 Production Order, can we change the TableRelation for Variant Code to Filter on Item?  This is Preventing us from adding another table relation for Source Type <> Item. 

**Current**

        field(12; "Variant Code"; Code[10])
        {
            Caption = 'Variant Code';
            TableRelation = "Item Variant".Code WHERE("Item No." = FIELD("Source No."),
                                                       Code = FIELD("Variant Code"));

**New**
        field(12; "Variant Code"; Code[10])
        {
            Caption = 'Variant Code';
            TableRelation = IF ("Source Type" = CONST(Item)) "Item Variant".Code WHERE("Item No." = FIELD("Source No."),
                                                       Code = FIELD("Variant Code"));

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41041.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 41088.
