### ISSUE TITLE
[Event Request] CU1390 - Document Notifications - OnCopyBillToCustomerAddressFieldsFromSalesDocumentOnBeforeModify

### ISSUE THREAD

**Issue by SamBfr** [microsoft/ALAppExtensions#18172]
Hi,
Would it be possible to get an OnCopyBillToCustomerAddressFieldsFromSalesDocumentOnBeforeModify event in codeunit 1390 (Document Notification), like this:

procedure CopyBillToCustomerAddressFieldsFromSalesDocument(ModifyCustomerAddressNotification: Notification)
    var
        Customer: Record Customer;
        SalesHeader: Record "Sales Header";
        UpdateAddress: Page "Update Address";
    begin
        if not ModifyCustomerAddressNotification.HasData(SalesHeader.FieldName("Bill-to Customer No.")) then
            exit;

        OnBeforeCopyBillToCustomerAddressFieldsFromSalesDocument(ModifyCustomerAddressNotification, SalesHeader);

        // Document Type
        Evaluate(SalesHeader."Document Type", ModifyCustomerAddressNotification.GetData(SalesHeader.FieldName("Document Type")));
        SalesHeader.Get(SalesHeader."Document Type", ModifyCustomerAddressNotification.GetData(SalesHeader.FieldName("No.")));
        if Customer.Get(ModifyCustomerAddressNotification.GetData(SalesHeader.FieldName("Bill-to Customer No."))) then begin
            UpdateAddress.SetExistingAddress(GetCustomerFullAddress(Customer));
            UpdateAddress.SetName(Customer.Name);
            UpdateAddress.SetUpdatedAddress(GetSalesHeaderFullBillToAddress(SalesHeader));

            if UpdateAddress.RunModal in [ACTION::OK, ACTION::LookupOK] then begin
                Customer.SetAddress(SalesHeader."Bill-to Address", SalesHeader."Bill-to Address 2",
                  SalesHeader."Bill-to Post Code", SalesHeader."Bill-to City", SalesHeader."Bill-to County",
                  SalesHeader."Bill-to Country/Region Code", SalesHeader."Bill-to Contact");

                //*****START
                OnCopyBillToCustomerAddressFieldsFromSalesDocumentOnBeforeModify(Customer, SalesHeader); 
                //*****END
                Customer.Modify(true);
            end;
        end;
    end;

```
[IntegrationEvent(false, false)]
    local procedure OnCopyBillToCustomerAddressFieldsFromSalesDocumentOnBeforeModify(var Customer: Record Customer; SalesHeader: Record "Sales Header") 
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41121.
