### ISSUE TITLE
[Event Request] Table 5077 "Segment Line" - OnBeforeRunWizard

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#18173]
Please add the event OnBeforeRunWizard() in Table 5077 "Segment Line" like this:

```
procedure StartWizard()
var
    Opp: Record Opportunity;
    IsHandled: Boolean;
    WizardPageId: Integer;
begin
    [...]
    WizardPageId := PAGE::"Create Interaction";
    OnBeforeRunWizard(Rec, WizardPageId); // <-- new event
    if WizardPageId <> 0 then
        if Page.RunModal(WizardPageId, Rec, "Interaction Template Code") = ACTION::OK then;
    if "Wizard Step" = "Wizard Step"::"6" then
        SendCreateOpportunityNotification();
end;
```
The new event:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeRunWizard(var SegmentLine: Record "Segment Line"; var WizardPageId: Integer)
begin
end;
```
Thanks!

**Comment by AlexanderYakunin** [comment]
Hello! We cannot implement this code as it completely overrides our code and does not relate to base app. You can easily use this code for your extension if needed, using handled event OnBeforeStartWizard. Let me know if I misunderstood your request.

**Comment by papillon** [comment]
Hi, all this code change does is to allow an extension to optionally run a different wizard page (or none at all). If no subscriber changes the WizardPageId, your base app code will continue to call the PAGE::"Create Interaction" just as before. I think this is a rather uncritical change which adds flexibility without breaking anything.

**Comment by papillon** [comment]
After checking the most current base app code, I found that you refactored the code around calling the wizard page in the meantime. I am happy with the change and therefore agree to close this issue.
