### ISSUE TITLE
[Event request] Codeunit 367 after post line

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#1818]
To migrate a NAV ISV add-on to BC:

After each line for:  GenJnlPostLine.RunWithCheck(GenJnlLine2);  I need a new event (OnAfterPostGenJnlLine?) that passes in the following variables:  
-	GenJnlLine2 
-	GenJnlPostLine   

For example:      

GenJnlPostLine.RunWithCheck(GenJnlLine2);   
OnAfterPostGenJnlLine(GenJnlLine2,GenJnlPostLine);

**Comment by AlexanderYakunin** [comment]
Please provide event names and exact location. What you would like to do in this event?

**Comment by RHansenEpimatic** [comment]
Hi Alexander -
Our add-on provides complex functionality to enable multiple operating companies to be set up in a single NAV company.  We enforce G/L balancing by global dimension 1 (which represents each company).  When certain transactions cross global dim. 1 values, we automatically post balancing due-to / due-from entries to the G/L.  That is what we need to do here, and we need the GenJnlPostLine variable passed out so we can post through the same instance of it.

I don't care what the event names are - but we need one after EACH "GenJnlPostLine.RunWithCheck" call.  They may need to just be numbered for each instance here...i.e.:

GenJnlPostLine.RunWithCheck(GenJnlLine2);  //Base app code
OnAfterPostGenJnlLine1(GenJnlLine2,GenJnlPostLine);  //New event

**Comment by RHansenEpimatic** [comment]
Thanks for addressing this!  Can you confirm a new event has been added after EVERY GenJnlPostLine.RunWithCheck call in the codeunit?

**Comment by AlexanderYakunin** [comment]
No, this is closed by mistake. Stil work in progress. I have to reopen it again.

**Comment by RHansenEpimatic** [comment]
Thanks very much Alexander!
