### ISSUE TITLE
[Request for External] codeunit 70 "Purch.-Calc.Discount" - Protected variables

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18189]
Hello, we need the following currently global variable/-s to be set as protected. Can you please check this? Thank you!

```
protected var
   PurchLine: Record "Purchase Line"
```

**Comment by AlexanderYakunin** [comment]
Protected variables cannot be used in codeunits, see [AS0676](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al676)
