### ISSUE TITLE
[Request for External] Table 36 "Sales Header" - Protected variables

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18180]
Hello, we need the following currently global variable/-s to be set as protected. Can you please check this? Thank you!

```
protected var
   SalesHeader: Record "Sales Header";
   SalesLine: Record "Sales Line";
```

**Comment by MH1612** [comment]
@JesperSchulz Can you please check this? Thank you!

**Comment by JesperSchulz** [comment]
It appears that this issue wasn't created in our internal system due to an issue with the automation, syncing GitHub issues and our internal systems. We will get that addressed as soon as possible and will then pick up this work. I apologize for the inconvenience!

**Comment by AlexanderYakunin** [comment]
Same question as for purchase header. I can see the purpose for SalesHeader, although still concerned about SalesLine as protected.
