### ISSUE TITLE
[Request for External] table 38 "Purchase Header" - Protected variables

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18182]
Hello, we need the following currently global variable/-s to be set as protected. Can you please check this? Thank you!

```
protected var
   PurchLine: Record "Purchase Line";
```

**Comment by MH1612** [comment]
@JesperSchulz Can you please check this? Thank you!

**Comment by JesperSchulz** [comment]
It appears that this issue wasn't created in our internal system due to an issue with the automation, syncing GitHub issues and our internal systems. We will get that addressed as soon as possible and will then pick up this work. I apologize for the inconvenience!

**Comment by AlexanderYakunin** [comment]
I think this is too generic request. Although there is global variable PurchLine in this table, it is used in several places independently. Why do you need global access to this variable? Maybe you simply need PurchLine2 variable in your code?
