### ISSUE TITLE
[Request for External] table 246 "Requisition Line" - Protected variables

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18181]
Hello, we need the following currently global variable/-s to be set as protected. Can you please check this? Thank you!

```
protected var
   PlanningResiliency: Boolean;
   TempPlanningErrorLog: Record "Planning Error Log" temporary;
   Subcontracting: Boolean;
```

**Comment by MH1612** [comment]
@JesperSchulz Can you please check this? Thank you!

**Comment by JesperSchulz** [comment]
It appears that this issue wasn't created in our internal system due to an issue with the automation, syncing GitHub issues and our internal systems. We will get that addressed as soon as possible and will then pick up this work. I apologize for the inconvenience!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47754.
