### ISSUE TITLE
[Event Request] CU7321 "Create Inventory Put-away" procedure "CreatePutAwayLinesFromSales"

### ISSUE THREAD

**Issue by ThomasKlockenbusch** [microsoft/ALAppExtensions#18199]
Hi :) 

In the procedure "CreatePutAwayLinesFromPurchase" there is an event after creating the put-away lines (OnAfterCreatePutAwayLinesFromPurchase).

I need a similar event raised from the procedure "CreatePutAwayLinesFromSales" after creating the put-away lines as well.

[IntegrationEvent(false, false)]
local procedure OnAfterCreatePutAwayLinesFromSales(SalesHeader: Record "SalesHeader"; WarehouseActivityHeader: Record "Warehouse Activity Header")
begin
 end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41121.
