### ISSUE TITLE
[Request for External] codeunit 333 "Req. Wksh.-Make Order" - Protected variables

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18198]
Hello, we need the following currently global variable/-s to be set as protected. Can you please check this? Thank you!

```
protected var
   NextLineNo: Integer;
```

**Comment by AlexanderYakunin** [comment]
Protected variables cannot be used in codeunits, see [AS0676](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/diagnostics/diagnostic-al676)
