### ISSUE TITLE
[Request for External] report 99001020 "Carry Out Action Msg. - Plan." - Protected variables

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18192]
Hello, we need the following currently global variable/-s to be set as protected. Can you please check this? Thank you!

```
protected var
   PurchOrderChoice: Enum "Planning Create Purchase Order";
```

**Comment by MH1612** [comment]
@JesperSchulz Can you please check this? Thank you!

**Comment by JesperSchulz** [comment]
It appears that this issue wasn't created in our internal system due to an issue with the automation, syncing GitHub issues and our internal systems. We will get that addressed as soon as possible and will then pick up this work. I apologize for the inconvenience!

**Comment by AlexanderYakunin** [comment]
These variables already made protected

    protected var
        ProdOrderChoice: Enum "Planning Create Prod. Order";
        PurchOrderChoice: Enum "Planning Create Purchase Order";
        TransOrderChoice: Enum "Planning Create Transfer Order";
        AsmOrderChoice: Enum "Planning Create Assembly Order";
