### ISSUE TITLE
Add parameters in Event SaveReportAsHTML

### ISSUE THREAD

**Issue by KliziaM** [microsoft/ALAppExtensions#18195]
Hi, 

I need to customize code in function "SaveReportAsHTML" in Table 77 "Report Selections";

Is it possible to add two parameters "var FilePath: Text[250]", and "var IsHandled: Boolean" in the event "OnSaveReportAsHTMLOnBeforeSetTempLayoutSelected"?

Something like this:

Before
![image](https://user-images.githubusercontent.com/105913292/169497788-a58ea554-0316-4b8e-8d3b-64af3211ddbe.png)

After
![image](https://user-images.githubusercontent.com/105913292/169499406-bb56c7af-7e4c-4ba8-a65f-1f4a933c36b8.png)

likewise function "SaveReportAsPDF" in the same table
![image](https://user-images.githubusercontent.com/105913292/169499223-c3da1284-0209-4082-9b56-36e12337d1c7.png)

Thank You

**Comment by AlexanderYakunin** [comment]
Exposing file path is security issue. Why you ask for this change? Which scenario you need to support?

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot add file path here.
