### ISSUE TITLE
Multiple SMTP Setups

### ISSUE THREAD

**Issue by ThomasBrodkorb** [microsoft/ALAppExtensions#182]
Suggestion:
Please allow several SMTP setups to be used per company.
This can be achieved by assigning a SMTP Setup record to SMTPMailSetup variable in CU 400 with an external procedure.

Reason:
Several different smtp servers might be required to allow for handling mails "in the name of" another company (warehouse handling).

**Comment by ikoletic** [comment]
This is a product suggestion already recorded here: https://experience.dynamics.com/ideas/idea/?ideaid=5f574a76-47c1-e811-b96f-0003ff68dcaf 
Please make sure to cast your vote on that idea.
