### ISSUE TITLE
[Event change request] Codeunit 415 OnAfterReopenPurchDoc

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#1820]
To migrate a NAV ISV add-on to BC:

We need the OnAfterReopenPurchDoc event updated to pass in the GenJnlPostLine variable

**Comment by AlexanderYakunin** [comment]
????? We already have this event OnAfterReopenPurchaseDoc(PurchHeader,PreviewMode) and we do not have GenJnlPostLine in this codeunit at all.

**Comment by RHansenEpimatic** [comment]
My apologies Alexander.  I was migrating the code for our add-on and saw the GenJnlPostLine variable being passed...i overlooked the fact that we added that variable...it's not base NAV.  Thank you for closing this one.
