### ISSUE TITLE
Codeunit 12151 "VAT Pmt. Comm. Data Lookup"

### ISSUE THREAD

**Issue by fulviabo** [microsoft/ALAppExtensions#18211]
Please add a new event in Codeunit 12151 "VAT Pmt. Comm. Data Lookup". The attached file indicates the position of the new event in the function and how the event should be. Many thanks in advance. Kind regards
 
[procedure GetVATPurchases.docx](https://github.com/microsoft/ALAppExtensions/files/8742222/procedure.GetVATPurchases.docx)

**Comment by Stepanenko-Vadim** [comment]
Please use the github issue to specify text in proper format, not attach some word document, we cannot process a request like this. You can see other requests to see how to specify locations, signatures etc.

**Comment by fulviabo** [comment]
Hi Vadim,
Sorry, for the inconvenience, it is the first time that I do it.

Codeunit 12151 "VAT Pmt. Comm. Data Lookup"

procedure GetVATPurchases(): Decimal
    begin
        VATEntry.SetRange(Type, VATEntry.Type::Purchase);
        OnGetVATPurchasesOnAfterVATEntrySetFilters(VATEntry);
        VATEntry.CalcSums(Amount);
        VATPurchases := VATEntry.Amount;
        VATEntry.SetRange(Type);s
       OnBeforeExitGetVATPurchases(VATPurchasesAmt,PeriodicSettlementVATEntryFound,LastPeriodicSettlementVATEntry,IsHandled);
        exit(VATPurchases);
    end;

[IntegrationEvent(false, false)]
local procedure OnBeforeExitGetVATPurchases(var VATPurchasesAmt: decimal; PeriodicSettlementVATEntryFound: Boolean; LastPeriodicSettlementVATEntry: Record "Periodic Settlement VAT Entry";var IsHandled: Boolean)
begin
end;


Fulvia Bondioli
Consultant
ERP-Dynamics NAV/365 BC

E  ***@***.******@***.***>
T +39 02 254427554
M +39 335 5838030

***@***.***
CEGEKA Via A. Volta 16
20093 Cologno Monzese MI, Italy
T +39 02 254 427 1
WWW.CEGEKA.IT<http://www.cegeka.it/>
***@***.***<https://www.linkedin.com/company/cegeka_italia>
***@***.***<https://twitter.com/Cegeka_IT>
***@***.***<https://www.facebook.com/Cegeka.Italia>
***@***.***<https://www.youtube.com/channel/UCyK4GfmaAT3MEJttkpfWoyQ>
[Immagine che contiene screenshot, tenendo, persone  Descrizione generata automaticamente]
