### ISSUE TITLE
[Event Request] Table 81 "Gen. Journal Line" OnValidateAccountTypeOnBeforeValidateDescription

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#18219]
Hello,
would it be possible to get an event OnValidateAccountTypeOnBeforeValidateDescription(Rec, IsHandled) like this:

<pre>
        field(3; "Account Type"; Enum "Gen. Journal Account Type")
        {
            Caption = 'Account Type';

            trigger OnValidate()
            var
                // Event request
                IsHandled: Boolean;
                // Event request
            begin
                if ("Account Type" in ["Account Type"::Customer, "Account Type"::Vendor, "Account Type"::"Fixed Asset",
                                       "Account Type"::"IC Partner", "Account Type"::Employee]) and
                   ("Bal. Account Type" in ["Bal. Account Type"::Customer, "Bal. Account Type"::Vendor, "Bal. Account Type"::"Fixed Asset",
                                            "Bal. Account Type"::"IC Partner", "Bal. Account Type"::Employee])
                then
                    Error(
                      Text000,
                      FieldCaption("Account Type"), FieldCaption("Bal. Account Type"));

                if ("Account Type" = "Account Type"::Employee) and ("Currency Code" <> '') then
                    Error(OnlyLocalCurrencyForEmployeeErr);

                Validate("Account No.", '');
                // Event request
                IsHandled := false;
                OnValidateAccountTypeOnBeforeValidateDescription(Rec, IsHandled);
                if not IsHandled then
                    Validate(Description, '');
                // Event request
                Validate("IC Partner G/L Acc. No.", '');

    [IntegrationEvent(false, false)]
    local procedure OnValidateAccountTypeOnBeforeValidateDescription(var GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
    begin
    end;

</pre>

**Comment by Oleg-Romashkov** [comment]
Hi, 

You can use existing field "Keep Description" and event OnValidateAccountTypeOnBeforeCheckKeepDescription:

```
                if ("Account Type" = "Account Type"::Employee) and ("Currency Code" <> '') then
                    Error(OnlyLocalCurrencyForEmployeeErr);

                Validate("Account No.", '');
                OnValidateAccountTypeOnBeforeCheckKeepDescription(Rec, xRec, CurrFieldNo);
                if not "Keep Description" then
                    Validate(Description, '');
                Validate("IC Partner G/L Acc. No.", '');
```

Rgds,
Oleg.
