### ISSUE TITLE
MS D365 Email not working in docker containers

### ISSUE THREAD

**Issue by RonKoppelaar** [microsoft/ALAppExtensions#18217]
When setting up email D365 Email connector in Docker the connector will throw following error on sending test mail:
The following AL methods are limited during write transactions because one or more tables will be locked: Form.RunModal is not allowed in write transactions. Codeunit.Run is allowed in write transactions only if the return value is not used. For example, 'OK := Codeunit.Run()' is not allowed. Report.RunModal is allowed in write transactions only if 'RequestForm = false'. For example, 'Report.RunModal(...,false)' is allowed. XmlPort.RunModal is allowed in write transactions only if 'RequestForm = false'. For example, 'XmlPort.RunModal(...,false)' is allowed. Use the commit method to save the changes before this call, or structure the code differently. Contact your application developer for further assistance.

**Callstack**
OAuth2Impl(CodeUnit 502).SetPropertiesBasedOnAuthRequestUrlAndRunOAuth2ControlAddIn - System Application by Microsoft
OAuth2Impl(CodeUnit 502).AcquireTokenByAuthorizationCode - System Application by Microsoft
OAuth2(CodeUnit 501).AcquireTokenByAuthorizationCode - System Application by Microsoft
"Email - OAuth Client"(CodeUnit 4507).TryGetAccessTokenInternal - Email - Outlook REST API by Microsoft
"Email - OAuth Client"(CodeUnit 4507).GetAccessToken - Email - Outlook REST API by Microsoft
"Email - Outlook API Helper"(CodeUnit 4509).Send line 13 - Email - Outlook REST API by Microsoft
"Microsoft 365 Connector"(CodeUnit 4503).Send line 4 - Email - Microsoft 365 Connector by Microsoft
"Send Email"(CodeUnit 8890).OnRun(Trigger) line 8 - System Application by Microsoft
"Email Dispatcher"(CodeUnit 8888).OnRun(Trigger) line 30 - System Application by Microsoft
"Email Impl"(CodeUnit 8900).Send line 40 - System Application by Microsoft
"Email Impl"(CodeUnit 8900).Send line 4 - System Application by Microsoft
Email(CodeUnit 8901).Send line 2 - System Application by Microsoft
"Email Test Mail"(CodeUnit 8887).OnRun(Trigger) line 35 - System Application by Microsoft

**Steps to repro**
- Create container with AAD auth
- Create App Registration using Create-AadAppsForBC (from bccontainerhelper)
- Setup email by providing the correct ClientID, Secret and redirect URI
- Send testmail, error as mentioned above is presented in outbox

**Workaround**
- Add event subscriber to: OnAfterInitializeClients from src\EmailOutlookAPIHelper.Codeunit.al
- Put commit() inside
- Build and publish the work around

**Retest**
- Go to email accounts
- Send email
- AAD login page is shown
- Re-enter credentials
- Email is send.

**Comment by mazhelez** [comment]
@RonKoppelaar I could not repro the issue. Are you using clean (no PTEs installed) container?

Generally, there cannot be `Page.RunModal` within a write transaction. The last transaction, updating the outbox status, was committed [here](https://github.com/microsoft/ALAppExtensions/blob/3f2f1d6e5337188b1af9c0275420f1c1de036a7f/Modules/System/Email/src/Email/EmailDispatcher.Codeunit.al#L102) and I cannot find any new one in the callstack. Any idea what might be starting a new write transaction?

**Comment by RonKoppelaar** [comment]
Not sure, which transaction is causing a new write action... I do have a script to create my local Docker container which I can share with you. 
``` powershell
$Office365UserName = 'YOUR ADMIN ACCOUNT' ## Emailadress
$credential = New-Object System.Management.Automation.PSCredential ($Office365UserName, (ConvertTo-SecureString '<YOUR PASSWORD>' -AsPlainText -Force))
$AadTenantId = "<YOUR TENANT ID>"
$LicenseFile = "<YOUR LICENSE FILE>"

$ContainerName = "demo20x"
$ArtifactURL = "https://bcartifacts.azureedge.net/sandbox/20.0.37253.38958/nl"
$DockerImageName = "local"

$AdditionalParameters = @()
$AdditionalParameters += ("--env locale=nl-NL")
$AdditionalParameters += ("--env ACCEPT_OUTDATED=Y")
$AdditionalParameters += ("--env locale=nl-NL")

$AdProperties = Create-AadAppsForBC -AadAdminCredential $credential -appIdUri "https://$containername.cdsa.nl/BC" -publicWebBaseUrl "https://$containername/BC" -IncludeEmailAadApp -IncludeApiAccess -IncludeExcelAadApp

Remove-NavContainer -containerName $ContainerName
$devcredentials = New-Object System.Management.Automation.PSCredential ('devadmin', (ConvertTo-SecureString 'Welkom01!' -AsPlainText -Force))
New-NavContainer -accept_eula `
    -containerName $ContainerName `
    -auth AAD `
    -Credential $devcredentials `
    -updateHosts `
    -isolation hyperv `
    -memoryLimit 20G `
    -additionalParameters $AdditionalParameters `
    -artifactUrl $ArtifactURL `
    -imageName $DockerImageName `
    -installCertificateOnHost `
    -authenticationEMail $Office365UserName -useSSL -AadTenant $AadTenantId  -AadAppIdUri "https://$containername.cdsa.nl/BC" -AadAppId $AdProperties.SsoAdAppId -licenseFile $LicenseFile

$Username = "<YOUR O365 Account>" 
Invoke-ScriptInNavContainer -containerName $ContainerName -scriptblock {
    param($Username)
    
    $UserId = $Username.Split("@")[0]
    New-NAVServerUser -serverinstance BC -tenant default -AuthenticationEmail $Username -UserName $UserId
    New-NAVServerUserPermissionSet -serverinstance BC -tenant default -PermissionSetId "SUPER" -UserName $UserId
} -argumentList $Username

```

After creating container:
- Logon with your O365 account
- Go to Email setup
- Walk through the wizard using the Email AppId and Email Secret from $AdProperties, make sure you set the correct redirect
- Go Email accounts page
- Try Process / Send test email

**Comment by RonKoppelaar** [comment]
When running, the compose email scenario, I got the same error message…
BTW... Im testing with BC 20.0
See error below:

The email was not sent because of the following error: "The following AL methods are limited during write transactions because one or more tables will be locked:

Form.RunModal is not allowed in write transactions.

Codeunit.Run is allowed in write transactions only if the return value is not used. For example, 'OK := Codeunit.Run()' is not allowed.

Report.RunModal is allowed in write transactions only if 'RequestForm = false'. For example, 'Report.RunModal(...,false)' is allowed.

XmlPort.RunModal is allowed in write transactions only if 'RequestForm = false'. For example, 'XmlPort.RunModal(...,false)' is allowed.

Use the commit method to save the changes before this call, or structure the code differently.

Contact your application developer for further assistance." 

Depending on the error, you might need to contact your administrator.

Internal session id: 
64c6c8a6-76d6-4d53-be1e-3e2f8b7ddbd9

Application Insights session id: 
8cb1944f-f85d-45c8-b0a8-3dff3af49662

Client activity id: 
dacca53a-c3c6-d906-fb3a-e8ff43700951

Timestamp: 
2022-05-25T08:42:59.3248888Z

AL call stack: 
"Email Editor"(CodeUnit 8906).SendOutbox line 8 - System Application by Microsoft
"Email Editor"(Page 13)."Send - OnAction"(Trigger) line 8 - System Application by Microsoft

**Comment by mazhelez** [comment]
> Any update on the repro scenario for this?

Yes, today I finally managed to reproduce using the exact image so I'll investigate further.

**Comment by RonKoppelaar** [comment]
Does it mean it had to do whith this particular version (image) of BC. e.g. doesn't it occur in 20.1 or 20.2?

**Comment by RonKoppelaar** [comment]
When running, the compose email scenario, I got the same error message…
See error below:

The email was not sent because of the following error: "The following AL methods are limited during write transactions because one or more tables will be locked:

Form.RunModal is not allowed in write transactions.

Codeunit.Run is allowed in write transactions only if the return value is not used. For example, 'OK := Codeunit.Run()' is not allowed.

Report.RunModal is allowed in write transactions only if 'RequestForm = false'. For example, 'Report.RunModal(...,false)' is allowed.

XmlPort.RunModal is allowed in write transactions only if 'RequestForm = false'. For example, 'XmlPort.RunModal(...,false)' is allowed.

Use the commit method to save the changes before this call, or structure the code differently.

Contact your application developer for further assistance."

Depending on the error, you might need to contact your administrator.

Internal session id:
64c6c8a6-76d6-4d53-be1e-3e2f8b7ddbd9

Application Insights session id:
8cb1944f-f85d-45c8-b0a8-3dff3af49662

Client activity id:
dacca53a-c3c6-d906-fb3a-e8ff43700951

Timestamp:
2022-05-25T08:42:59.3248888Z

AL call stack:
"Email Editor"(CodeUnit 8906).SendOutbox line 8 - System Application by Microsoft
"Email Editor"(Page 13)."Send - OnAction"(Trigger) line 8 - System Application by Microsoft

Met vriendelijke groet,
Ron Koppelaar
Architect
