### ISSUE TITLE
[Parameter Request] Page 99000902 Item Availability Line List "OnLookupExtensionTable"

### ISSUE THREAD

**Issue by dgoyalaptean** [microsoft/ALAppExtensions#18225]
Can we please get the below additional parameters under base event "OnLookupExtensionTable"?

New Parameters : [QuerySource(QuerySource: Integer) & SalesLine(SalesLine: Record "Sales Line")]

 OnLookupExtensionTable(Item, "Table No.", SalesLine, QuerySource);

```
    [IntegrationEvent(false, false)]
    local procedure OnLookupExtensionTable(var Item: Record Item; TableID: Integer; SalesLine: Record "Sales Line"; QuerySource: Integer)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41118.
