### ISSUE TITLE
[Event Request] Table 81 "Gen. Journal Line" OnDeleteOnBeforeClearCustVendApplnEntry

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#18221]
Hello,
would it be possible to get an event OnDeleteOnBeforeClearCustVendApplnEntry(GenJournalLine, GenJournalBatch, GenJnlAlloc, IsHandled) like this:

<pre>
    trigger OnDelete()
    var
        GenJournalBatch: Record "Gen. Journal Batch";
        GenJournalLine: Record "Gen. Journal Line";
        // Event request
        IsHandled: Boolean;
        // Event request
    begin
        CheckJobQueueStatus(Rec);
        ApprovalsMgmt.OnCancelGeneralJournalLineApprovalRequest(Rec);

        // Lines are deleted 1 by 1, this actually check if this is the last line in the General journal Bach
        GenJournalLine.SetRange("Journal Template Name", "Journal Template Name");
        GenJournalLine.SetRange("Journal Batch Name", "Journal Batch Name");
        if GenJournalLine.Count = 1 then
            if GenJournalBatch.Get("Journal Template Name", "Journal Batch Name") then
                ApprovalsMgmt.OnCancelGeneralJournalBatchApprovalRequest(GenJournalBatch);

        TestField("Check Printed", false);

        // Event request
        IsHandled := false;
        OnDeleteOnBeforeClearCustVendApplnEntry(GenJournalLine, GenJournalBatch, GenJnlAlloc, IsHandled);
        if not IsHandled then begin
        // Event request
            ClearCustVendApplnEntry;
            ClearAppliedGenJnlLine;
            DeletePaymentFileErrors;
            ClearDataExchangeEntries(false);

            GenJnlAlloc.SetRange("Journal Template Name", "Journal Template Name");
            GenJnlAlloc.SetRange("Journal Batch Name", "Journal Batch Name");
            GenJnlAlloc.SetRange("Journal Line No.", "Line No.");
            if not GenJnlAlloc.IsEmpty() then
                GenJnlAlloc.DeleteAll();
        // Event request
        end;
        // Event request

    [IntegrationEvent(false, false)]
    local procedure OnValidateVATProdPostingGroupOnBeforeCheckAccountType(var GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
    begin
    end;
</pre>

**Comment by swecompany** [comment]
**Attention**: In the call of the EventPublisher in the OnDelete trigger of Table 81 "Gen. Journal Line" there is an error: Instead of the variable GenJournalLine the Rec must be passed.

The call would then be: OnDeleteOnBeforeClearCustVendApplnEntry(**Rec**, GenJournalBatch, GenJnlAlloc, IsHandled);
