### ISSUE TITLE
[Event Request] Table 81 "Gen. Journal Line" OnGetBankBalAccountOnBeforeSetDescription

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#18224]
Hello,
would it be possible to get an event OnGetBankBalAccountOnBeforeSetDescription(Rec, IsHandled) like this:

<pre>
    local procedure GetBankBalAccount()
    var
        BankAcc: Record "Bank Account";
        // Event request
        IsHandled: Boolean;
        // Event request
    begin
        BankAcc.Get("Bal. Account No.");
        BankAcc.TestField(Blocked, false);
        if "Account No." = '' then begin
            // Event request
            IsHandled := false;
            OnGetBankBalAccountOnBeforeSetDescription(Rec, IsHandled);
            if not IsHandled then
            // Event request
                Description := BankAcc.Name;
        end;

        if ("Account No." = '') or

    [IntegrationEvent(false, false)]
    local procedure OnGetBankBalAccountOnBeforeSetDescription(var GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
    begin
    end;
</pre>

**Comment by Oleg-Romashkov** [comment]
Hi,

Please use existing event OnBeforeIsAdHocDescription

Rgds,
Oleg.
