### ISSUE TITLE
[Event Request]  Page 2900 "Demand Forecast Variant Matrix"

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#18229]
Hello,
Page 9245 "Demand Forecast Matrix"  is now set to be replaced by page 2900 "Demand Forecast Variant Matrix", but a lot of the events that was on demand forecast matrix has not been created in demand forecast variant matrix. Can you guys add the following events from demand forecast matrix to demand forecast variant matrix?

Events in procedure EnterBaseQty:
        OnBeforeEnterBaseQty(Rec, ColumnID, IsHandled, MatrixRecords, QtyType);
        OnEnterBaseQtyOnBeforeValidateProdForecastQty(Rec, ColumnID, MatrixRecords);
        OnEnterBaseQtyOnAfterValidateProdForecastQty(Rec, ColumnID, MatrixRecords, QtyType);

Events in procedure ProdForecastQtyBase_OnValidate:
            OnProdForecastQtyBase_OnValidateOnAfterCalcShouldConfirmMovingForecasts(ProdForecastEntry, ColumnID, MatrixRecords, ShouldConfirmMovingForecasts);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41118.
