### ISSUE TITLE
[Event Request] Table 81 "Gen. Journal Line" OnValidatePostingDateOnBeforeValidateDocumentDate(Rec, xRec, IsHandled)

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#18220]
Hello,
would it be possible to get an event OnValidatePostingDateOnBeforeValidateDocumentDate(Rec, xRec, IsHandled) like this:

<pre>
        field(5; "Posting Date"; Date)
        {
            Caption = 'Posting Date';
            ClosingDates = true;

            trigger OnValidate()
            var
                // Event request
                IsHandled: Boolean;
                // Event request
            begin
                TestField("Posting Date");
                // Event request
                IsHandled := false;
                OnValidatePostingDateOnBeforeValidateDocumentDate(Rec, xRec, IsHandled);
                if not IsHandled then
                    Validate("Document Date", "Posting Date");
                // Event request
                ValidateCurrencyCode();

    [IntegrationEvent(false, false)]
    local procedure OnValidatePostingDateOnBeforeValidateDocumentDate(var GenJournalLine: Record "Gen. Journal Line"; var xGenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
    begin
    end;
</pre>

**Comment by Oleg-Romashkov** [comment]
Hi,

Please use existing event OnBeforeValidateDocumentDateFromPostingDate

Rgds,
Oleg.

**Comment by oni1300** [comment]
Hello,

sorry, but I can’t find the event you proposed even in the latest available repo of BC 20.1.

Regards
Dietmar

Von: Oleg-Romashkov ***@***.***>
Gesendet: Dienstag, 24. Mai 2022 06:12
An: microsoft/ALAppExtensions ***@***.***>
Cc: Schulz, Dietmar ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/ALAppExtensions] [Event Request] Table 81 "Gen. Journal Line" OnValidatePostingDateOnBeforeValidateDocumentDate(Rec, xRec, IsHandled) (Issue #18220)


Hi,

Please use existing event OnBeforeValidateDocumentDateFromPostingDate

Rgds,
Oleg.

**Comment by oni1300** [comment]
Thx

Von: Oleg-Romashkov ***@***.***>
Gesendet: Dienstag, 24. Mai 2022 11:15
An: microsoft/ALAppExtensions ***@***.***>
Cc: Schulz, Dietmar ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/ALAppExtensions] [Event Request] Table 81 "Gen. Journal Line" OnValidatePostingDateOnBeforeValidateDocumentDate(Rec, xRec, IsHandled) (Issue #18220)


Hi Dietmar,

It is a fresh one. It will be available on 20.2

    local procedure ValidateDocumentDateFromPostingDate()

    var

        IsHandled: Boolean;

    begin

        IsHandled := false;

        OnBeforeValidateDocumentDateFromPostingDate(Rec, xRec, IsHandled);

        if IsHandled then

            exit;



        Validate("Document Date", "Posting Date");

    end;
