### ISSUE TITLE
Event Request] Codeunit 8613 "Config. Package Table" OnShowPackageRecordsOnBeforeProcessMatrixColumnCaptions

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#18238]
Body:
Hello,
would it be possible to get an event OnShowPackageRecordsOnBeforeProcessMatrixColumnCaptions(ConfigPackageField, MatrixColumnCaptions, IsHandled) like this:

<pre>
    procedure ShowPackageRecords(Show: Option Records,Errors,All; ShowDim: Boolean)
    var
        ConfigPackageField: Record "Config. Package Field";
        ConfigPackageRecord: Record "Config. Package Record";
        ConfigPackageRecords: Page "Config. Package Records";
        MatrixColumnCaptions: array[1000] of Text[100];
        // Event request
        IsHandled: Boolean;
        // Event request
    begin
        ConfigPackageField.SetRange("Package Code", "Package Code");
        ConfigPackageField.SetRange("Table ID", "Table ID");
        ConfigPackageField.SetRange("Include Field", true);
        if not ShowDim then
            ConfigPackageField.SetRange(Dimension, false);
        // Event request
        IsHandled := true;
        OnShowPackageRecordsOnBeforeProcessMatrixColumnCaptions(ConfigPackageField, MatrixColumnCaptions, IsHandled);
        if not IsHandled then begin
        // Event request
            i := 1;
            Clear(MatrixColumnCaptions);
            if ConfigPackageField.FindSet then
                repeat
                    MatrixColumnCaptions[i] := ConfigPackageField."Field Name";
                    i := i + 1;
                until ConfigPackageField.Next() = 0;
        // Event request
        end;
        // Event request

    [IntegrationEvent(false, false)]
    local procedure OnShowPackageRecordsOnBeforeProcessMatrixColumnCaptions(var ConfigPackageField: Record "Config. Package Field"; var MatrixColumnCaptions: array[1000] of Text[100]; var IsHandled: Boolean)
    begin
    end;
</pre>

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41118.
