### ISSUE TITLE
[Event Request] Table 249 "VAT Registration Log" - OnBeforeValidateField

### ISSUE THREAD

**Issue by SergiiSidlyar** [microsoft/ALAppExtensions#18257]
Hi, 
Would it be possible to pass **"Value"** parameter **by reference (by var)** in the **OnBeforeValidateField** publisher in table 249 **"VAT Registration Log"**?
Like this:

```al
// Old publisher begin
    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateField(var RecordRef: RecordRef; FieldName: Text; Value: Text; var IsHandled: Boolean)
    begin
    end;
// Old publisher end

// New publisher begin
    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateField(var RecordRef: RecordRef; FieldName: Text; var Value: Text; var IsHandled: Boolean)
    begin
    end;
// New publisher end
```

Thanks in advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41159.
