### ISSUE TITLE
"Format" fields are no longer included into Excel when printing with "Microsoft Excel Document (Data only)" option

### ISSUE THREAD

**Issue by Eduard-Gayvoronskiy** [microsoft/ALAppExtensions#18259]
I use printing with "Microsoft Excel Document (Data only)" option to export test cases into Excel. Then I use that Excel as a data source to develop RDL reports in the Report Builder. Format columns are a must because their values are used to format other columns' values. Could you please add the "Format" fields back to that export option? That was a great help for me as a reports developer. Thanks!

**Comment by JesperSchulz** [comment]
Unfortunately, this repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

For suggestions to the Business Central product group, please create a [BC Idea](https://aka.ms/bcideas).

If you want to log a support case, please visit:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
