### ISSUE TITLE
[Event Request ] "Payment History Line"

### ISSUE THREAD

**Issue by RonaldVeenman** [microsoft/ALAppExtensions#18265]
Please **modify** the Event Publisher OnAfterGetUnstrRemitInfo in table 11000002 "Payment History Line". 

Change: the variable UnstrRemitInfo to a VAR (call by reference), see example below.

**Current:**
    `local procedure OnAfterGetUnstrRemitInfo(var PaymentHistoryLine: Record "Payment History Line"; var DetailLine: Record "Detail Line"; UnstrRemitInfo: Text[140])
    begin
    end;`

**New:**
    `local procedure OnAfterGetUnstrRemitInfo(var PaymentHistoryLine: Record "Payment History Line"; var DetailLine: Record "Detail Line"; var UnstrRemitInfo: Text[140])
    begin
    end;`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41134.
