### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" - OnRoundAmountOnBeforeIncrAmount

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18263]
Please extend the OnRoundAmountOnAfterAssignSalesLines event with handled pattern.

```
[IntegrationEvent(false, false)]
local procedure OnRoundAmountOnAfterAssignSalesLines(var xSalesLine: Record "Sales Line"; var SalesLineACY: Record "Sales Line"; SalesHeader: Record "Sales Header"; var IsHandled: Boolean);
begin
end;
```
```
IsHandled := false;
OnRoundAmountOnAfterAssignSalesLines(xSalesLine, SalesLineACY, SalesHeader, IsHandled);
if not IsHandled then
    if SalesHeader."Currency Code" <> '' then begin
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41235.
