### ISSUE TITLE
[Event Request] Table 37 - Sales Line - OnAfterShowItemChargeAssgnt

### ISSUE THREAD

**Issue by jmezquita2** [microsoft/ALAppExtensions#18267]
Hi,

Related to the request #9993.
Could be posible to add the same event OnAfterShowItemChargeAssgnt on his twin function from Table 37 - Sales Line (ShowItemChargeAssgnt function)?

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41238.
