### ISSUE TITLE
[Event Request] Table 900 "Assembly Header" OnValidateLocationCodeOnBeforeUpdateAssemblyLines

### ISSUE THREAD

**Issue by BCI-AL** [microsoft/ALAppExtensions#18271]
Please add a new event publisher:

[IntegrationEvent(false, false)]
local procedure OnValidateLocationCodeOnBeforeUpdateAssemblyLines(var AssemblyHeader: Record "Assembly Header"; var OldAssemblyHeader: Record "Assembly Header"; var IsHandled: Boolean)
begin
end;

And please add code into the "Location Code" OnValidate trigger as indicated below (between the //BEGIN and //END):

Location Code - OnValidate()
                CheckIsNotAsmToOrder();
                TestStatusOpen();
                SetCurrentFieldNum(FieldNo("Location Code"));
                IsHandled := false;
                OnValidateLocationCodeOnBeforeValidateDates(Rec, xRec, IsHandled);
                if not IsHandled then
                    ValidateDates(FieldNo("Due Date"), true);

    //BEGIN NEW CODE >>
    IsHandled := false;
    OnValidateLocationCodeOnBeforeUpdateAssemblyLines(Rec, xRec, IsHandled);
    if not IsHandled then
    //END NEW CODE <<

                AssemblyLineMgt.UpdateAssemblyLines(Rec, xRec, FieldNo("Location Code"), false, CurrFieldNo, CurrentFieldNum);

So that the line of code 'AssemblyLineMgt.UpdateAssemblyLines' is only executed if IsHandled is false.

Needed for a Customer urgently.

Many thanks as always!

**Comment by Stepanenko-Vadim** [comment]
This will instead be extended in OnBeforeUpdateAssemblyLines of codeunit 905 "Assembly Line Management" with IsHandled pattern. It already has all the fieldno's as params so you can check whether you need to disable it or not
