### ISSUE TITLE
[event-request] "Purch.-Disc. (Yes/No)" & "Sales-Disc. (Yes/No)" OnBeforeRunCalcDiscount

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#18270]
Hi, we need a publisher "OnBeforeRunCalcDiscount" in codeunit "Purch.-Disc. (Yes/No)" & "Sales-Disc. (Yes/No)":

codeunit "Purch.-Disc. (Yes/No)":

```
    trigger OnRun()
    var
        ConfirmManagement: Codeunit "Confirm Management";
    begin
        if ConfirmManagement.GetResponseOrDefault(Text000, true) then begin
             OnBeforeRunCalcDiscount(Rec); // New Event
             CODEUNIT.Run(CODEUNIT::"Purch.-Calc.Discount", Rec);
        end;
    end;
    
    [InternalEvent(false)]
    local procedure OnBeforeRunCalcDiscount(PurchaseHeader: Record "Purchase Header")
    begin
    end;    

```

codeunit "Sales-Disc. (Yes/No)":

```
    trigger OnRun()
    var
        ConfirmManagement: Codeunit "Confirm Management";
    begin
        SalesLine.Copy(Rec);
        with SalesLine do begin
            if ConfirmManagement.GetResponseOrDefault(Text000, true) then begin
                OnBeforeRunCalcDiscount(Rec); // New Event
                CODEUNIT.Run(CODEUNIT::"Sales-Calc. Discount", SalesLine);
            end; 
        end;
        Rec := SalesLine;
    end;

    [InternalEvent(false)]
    local procedure OnBeforeRunCalcDiscount(SalesHeader: Record "Sales Header")
    begin
    end; 
```

**Comment by Stepanenko-Vadim** [comment]
Will it work for you if it will be an **OnBeforeOnRun** in "Purch.-Calc.Discount" and "Sales-Calc. Discount" instead?. Considering that in "Sales-Disc. (Yes/No)" changing rec will actually do nothing, since copy is used before and codeunit is ran on another var this just seems weird.

**Comment by pschwambornMC** [comment]
Unfortunately, this does not work for me. I do not want to change the rec, i want to send another confirm (and maybe modify tables assigned to rec) to the user only if the action "CalculateInvoiceDiscount" is pressed **specifically** in page "Sales Order", "Purchase Order" etc.
The **OnBeforeOnRun** you suggest would also run on post, on release, on changing lines etc. There i have no chance to check if the action was used.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41235.
