### ISSUE TITLE
[Scope] License Information table - request for alternative for accessing License details

### ISSUE THREAD

**Issue by paulojcdev** [microsoft/ALAppExtensions#18285]
Hi,

The goal is to be able to access the license information details and have the App scope = cloud.

We are trying to make our App comply with universal code, and change the scope to Cloud.
One problem is that we need to use the "License Information" table to gather/check some information, for OnPrem databases.

I understand this table does not exist/not used on SaaS. 

It would be very helpful to have some kind of Interface codeunit that could give us the same info we get from this table and that we could use when scope = cloud.

something like:
```
    procedure GetLicenseInformation(): JsonObject
    var
        EnvironmentInformation: Codeunit "Environment Information";
    begin
        if EnvironmentInformation.IsOnPrem() then
            exit(LicenseInformationImpl.GetLicenseInformation());
    end;
```

This is just random example, the return type for example could also be Text.

**Comment by KimKobberoe** [comment]
Hi, what kind of license information are you looking for? The license information is link between the license the user has assigned in AAD and the entitlements defined in the extensions installed.

**Comment by paulojcdev** [comment]
Hi @KimKobberoe 
the information we would like to have access to is:

- VOICE Account Number
- Amount of Business Central Device
- Amount of Business Central Team Members
- Is Dual Right license

Thanks,

**Comment by AlexanderYakunin** [comment]
We cannot help with this ask here, probably you can create an idea on aka.bs/bcideas?
