### ISSUE TITLE
[Event Request/Update] table 60 "Document Sending Profile" - OnCheckElectronicSendingEnabled

### ISSUE THREAD

**Issue by boych83** [microsoft/ALAppExtensions#18286]
Hello ALAppExtensions team,

I finally see some progress regarding Electronic formats and procedure "SendElectronically" with limitation in the past for SaaS w1 base app development 👏🏼

We need to solve another issue when our appsource application is installed and disables standard verification of "Document Sending Profile" - OnCheckElectronicSendingEnabled() in combination with 3rd party application which also disables same standard verification.

Both apps using codeunit with automatically bound subscribers. We would need to have information about "Document Sending Profile" on existing event publisher  OnCheckElectronicSendingEnabled() with enabled "IncludeSender" parameter.
With that information we could determine, if our or 3rd party or standard profile is used and which check for setup of the eDocument service provider need to be done: our or 3rd party or standard.

` [IntegrationEvent(true, false)]
    local procedure OnCheckElectronicSendingEnabled(var ExchServiceEnabled: Boolean)
    begin
    end;
`

BR,
Bojan

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41235.
