### ISSUE TITLE
[Event Request] Codeunit 11110 "Update VAT-AT" OnUpdateVATStatementTemplateOnBeforeUpdate

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#18288]
Hello,
would it be possible to get an event OnUpdateVATStatementTemplateOnBeforeUpdate(TemplateName, IsHandled) like this:

<pre>
    procedure UpdateVATStatementTemplate(TemplateName: Code[10]; TemplateDescription: Text[80]; AgricultureVATProdPostingGroups: Text)
    var
        // Event request
        IsHandled: Boolean;
        // Event request
    begin
        if VATStatementTemplate.Get(TemplateName) then begin
            if not Confirm(DeleteVATStatementQst, true, TemplateName) then
                Error(NoTemplateUpdatedErr)
        end else
            if not Confirm(CreateVATStatementQst, true, TemplateName) then
                Error(NoTemplateUpdatedErr);

        // Event request
        IsHandled := false;
        OnUpdateVATStatementTemplateOnBeforeUpdate(TemplateName, IsHandled);
        if IsHandled then
            exit;
        // Event request

        Update(TemplateName, TemplateDescription, AgricultureVATProdPostingGroups);

        Message(TemplateUpdatedMsg, VATStatementTemplate.Name);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnUpdateVATStatementTemplateOnBeforeUpdate(var TemplateName: Code[10]; var IsHandled: Boolean)
    begin
    end;
</pre>

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41235.
