### ISSUE TITLE
[Extensibility Enhancement] Codeunit 2846 "Post Inventory Cost to G/L" - Add TableNo property and expose in event

### ISSUE THREAD

**Issue by jmezquita2** [microsoft/ALAppExtensions#18281]
Hi,

This is a very simple codeunit that standard uses to schedule when the "Automatic cost posting" is not active.

Would be posible to add the TableNo and an event?

```
codeunit 2846 "Post Inventory Cost to G/L"
{
// ---> New property
    TableNo = "Job Queue Entry";
// ---> New property

    trigger OnRun()
    begin
        PostInvToGL.InitializeRequest(PostMethod::"per Entry", '', true);
        PostInvToGL.UseRequestPage(false);
// ---> New event with Rec and PostInvToGL
        PostInvToGL.Run();
    end;

    var
        PostInvToGL: Report "Post Inventory Cost to G/L";
        PostMethod: Option "per Posting Group","per Entry";
}
```

Thanks

**Comment by AlexanderYakunin** [comment]
Please explain why do you need TableNo and what is event defenition?

**Comment by jmezquita2** [comment]
> Please explain why do you need TableNo and what is event definition?

Hi. Since the codeunit is intended to use as queue, we thought it was great to be able to access to the queue record and get the parameter string to make personalizations. The event was to be able to make that personalizations.

However, this ticket  has 1 year. We already created a custom codeunit to solve that.

Thanks.
