### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnBeforeUpdateAssocOrder

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18289]
Please extend event OnBeforeUpdateAssocOrder with parameters PurchHeader and SuppressCommit. Also please include sender in this event.

```
[IntegrationEvent(true, false)]
local procedure OnBeforeUpdateAssocOrder(PurchHeader: Record "Purchase Header";var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer" temporary; SuppressCommit: Boolean; var IsHandled: Boolean)
begin
end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41235.
