### ISSUE TITLE
[Event Request] codeunit 1412 "Service Inv. Header - Edit"

### ISSUE THREAD

**Issue by boych83** [microsoft/ALAppExtensions#18280]
Hello ALAppExtensions team,

We need an additional event publisher to be able to block changes to the value of the 'Payment Method Code' field in some cases, e.g. for our "Fiscal verification of invoices" module, we need to block changes from/to the cash payment methode code.
I think the most appropriate way is with an additional event publisher, like in the code below:

```
codeunit 1412 "Service Inv. Header - Edit"
{
    Permissions = TableData "Service Invoice Header" = rm;
    TableNo = "Service Invoice Header";

    trigger OnRun()
    var
        ServiceInvoiceHeader: Record "Service Invoice Header";
    begin
        ServiceInvoiceHeader := Rec;
        ServiceInvoiceHeader.LockTable();
        ServiceInvoiceHeader.Find();
        
 // ---> New event publisher
        
        ServiceInvoiceHeader."Payment Method Code" := "Payment Method Code";
        ServiceInvoiceHeader."Payment Reference" := "Payment Reference";
        ServiceInvoiceHeader."Company Bank Account Code" := "Company Bank Account Code";
        ServiceInvoiceHeader.TestField("No.", "No.");
        ServiceInvoiceHeader.Modify();
        Rec := ServiceInvoiceHeader;
    end;
}
```
BR,
Bojan

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41238.
