### ISSUE TITLE
[Event Request] Codeunit 90 Purch.-Post

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#18297]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnAfterModifyTempLine' to be added to procedure 'ModifyTempLine' in codeunit 90 Purch.-Post.

````
    local procedure ModifyTempLine(var TempPurchLineLocal: Record "Purchase Line" temporary)
    var
        PurchLine: Record "Purchase Line";
    begin
        TempPurchLineLocal.Modify();
        PurchLine.Get(TempPurchLineLocal.RecordId);
        PurchLine.TransferFields(TempPurchLineLocal, false);
        PurchLine.Modify();
        OnAfterModifyTempLine(PurchLine); //new
    end;
````
````
    [IntegrationEvent(false, false)]
    local procedure OnAfterModifyTempLine(var PurchLine: Record "Purchase Line");
    begin
    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41235.
