### ISSUE TITLE
[Event Request] Codeunit 1313 "Correct Posted Purch. Invoice" OnTestPurchaseLinesOnBeforeWrongItemTypeError

### ISSUE THREAD

**Issue by oni1300** [microsoft/ALAppExtensions#18298]
Hello,
would it be possible to get an event OnTestPurchaseLinesOnBeforeWrongItemTypeError(PurchInvHeader, PurchInvLine, IsHandled) like this:

<pre>
    local procedure TestPurchaseLines(PurchInvHeader: Record "Purch. Inv. Header")
    var
        PurchInvLine: Record "Purch. Inv. Line";
        Item: Record Item;
        DimensionManagement: Codeunit DimensionManagement;
        ReceivedQtyNoReturned: Decimal;
        RevUnitCostLCY: Decimal;
        TableID: array[10] of Integer;
        No: array[10] of Code[20];
        // Event request
        IsHandled: Boolean;
        // Event request
    begin
        PurchInvLine.SetRange("Document No.", PurchInvHeader."No.");
        if PurchInvLine.Find('-') then
            repeat
                if not IsCommentLine(PurchInvLine) then begin
                    // Event request
                    IsHandled := false;
                    OnTestPurchaseLinesOnBeforeWrongItemTypeError(PurchInvHeader, PurchInvLine, IsHandled);
                    if not IsHandled then
                        if (not PurchInvLine.IsCancellationSupported) and NotInvRndAccount(PurchInvHeader."Vendor Posting Group", PurchInvLine) then
                            ErrorHelperLine(ErrorType::WrongItemType, PurchInvLine);
                    // Event request

                    if PurchInvLine.Type = PurchInvLine.Type::Item then begin
                        Item.Get(PurchInvLine."No.");

    [IntegrationEvent(false, false)]
    local procedure OnTestPurchaseLinesOnBeforeWrongItemTypeError(var PurchInvHeader: Record "Purch. Inv. Header"; var PurchInvLine: Record "Purch. Inv. Line"; var IsHandled: Boolean)
    begin
    end;
</pre>

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41238.
