### ISSUE TITLE
[Event Request] Codeunit 11000000 "Process Proposal Lines" - OnBeforeCheckProposalLines

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#18290]
Hello,

We would need to have the parameter ProposalLine by reference instead as by value in the event OnBeforeCheckProposalLines from codeunit 11000000 "Process Proposal Lines":

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckProposalLines(**var** ProposalLine: Record "Proposal Line"; var IsHandled: Boolean)
    begin
    end;

We need this change, because we need to keep any filter that was applied to the ProposalLine variable when the OnRun trigger was called before calling the function CheckProposalLines.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41235.
