### ISSUE TITLE
[Event Request] Report 2 - Function TestFixedAsset

### ISSUE THREAD

**Issue by bogdangarkusha** [microsoft/ALAppExtensions#18299]
Could you please create an Integration event in Report 2 "General Journal - Test", in Function "TestFixedAsset"?

**local procedure TestFixedAsset(var GenJnlLine: Record "Gen. Journal Line")**
    ....
    // >>>
    IsHandled := false;
    OnBeforeCheckFAPostingDate(GenJnlLine,ErrorText,ErrorCounter);
    if not IsHandled then
    // <<<
    if "FA Posting Date" <> 0D then begin
        if "FA Posting Date" <> NormalDate("FA Posting Date") then
    ....
end;

**Event signature:**
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckFAPostingDate(var GenJnlLine: Record "Gen. Journal Line";var ErrorText: array[50] of Text[250]; var ErrorCounter: Integer)
begin
end;

In our extension, we need it because we've extended checks for allowed posting ranges.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41235.
