### ISSUE TITLE
Request C_229 DoPrintSalesHeader

### ISSUE THREAD

**Issue by GlicPi** [Microsoft/ALAppExtensions#183]
Could you please add this Code: 

"SalesHeader.Setrange(Document Type, Salesheader."Document Type")" 

at the "DoPrintSalesHeader" function in Codeunit 229 ? 

![c_229](https://user-images.githubusercontent.com/34307263/33872055-8b52193a-df15-11e7-824d-2f2ea784cf26.PNG)

**Comment by JesperSchulz** [comment]
This issue somehow fell between the cracks. Sorry about that. This is normally not the right repo to log issues which aren't extenisbility related, but in this case I'll add the bug to my own backlog and get it resolved ;-) Sorry for keeping you waiting so long. I will close this issue and process the bug for the next major release right away.
