### ISSUE TITLE
Table 38 - Purchase Header - OnBeforeCreateDim add DefaultDimSource as a variable

### ISSUE THREAD

**Issue by DParkerRSM** [microsoft/ALAppExtensions#18308]
When creating dimensions I have clients that want to use the Buy-From Vendor dimensions instead of the pay-to vendor dimensions. I was originally using the OnAfterCreateDimTableIDs event on the purchase header table to do so but it is being removed.

    procedure CreateDim(DefaultDimSource: List of [Dictionary of [Integer, Code[20]]])
    var
        SourceCodeSetup: Record "Source Code Setup";
        OldDimSetID: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        //Remove >>
        //OnBeforeCreateDim(Rec, IsHandled);
        //Remove <<
        //Add >>
        OnBeforeCreateDim(Rec, DefaultDimSource, IsHandled);
        //Add<<
        if IsHandled then
            exit;

        SourceCodeSetup.Get();

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41235.
