### ISSUE TITLE
[Event Request] Report 5602 "Fixed Asset Journal - Test"

### ISSUE THREAD

**Issue by bogdangarkusha** [microsoft/ALAppExtensions#18303]
Could you please create an Integration event in Report 5602 "Fixed Asset Journal - Test", in dataitem "FA Journal Line", trigger OnAfterGetRecord?

**trigger OnAfterGetRecord()**
    begin
    if "FA No." <> '' then begin
    // >>>
    IsHandled := false;
    OnBeforeCheckFAPostingDate("FA Journal Line",ErrorText,ErrorCounter);
    if not IsHandled then
    // <<<
    if "FA Posting Date" = 0D then
....
end;

**Event signature:**
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckFAPostingDate(var FAJnlLine: Record "FA Journal Line"; var ErrorText: array[50] of Text[250]; var ErrorCounter: Integer)
begin
end;

In our extension, we need it because we would like to extend checks for allowed posting ranges.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41251.
