### ISSUE TITLE
[Extensibility request] enum 136 "Dimension Set Entry Buffer Parent Type"

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/ALAppExtensions#18309]
Please make enum 136 "Dimension Set Entry Buffer Parent Type" extensible.
We want to use it in custom APIs to load dimension sets for other tables.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41302.
