### ISSUE TITLE
[Event-Request] Table 36 "Sales Header" - OnBeforeLookupSellToContact

### ISSUE THREAD

**Issue by JerryTyssen** [microsoft/ALAppExtensions#18301]
Hello,

We would like to request the addition of the event OnBeforeLookupSellToContact(Rec, xRec, IsHandled) in procedure OnLookup() of field(84; "Sell-to Contact"; Text[100]) in Table 36 "Sales Header":

```
trigger OnLookup()
var
    Contact: Record Contact;
    ++ IsHandled: Boolean;
begin                
    ++ IsHandled := false;
    ++ OnBeforeLookupSellToContact(Rec, xRec, IsHandled);
    ++ if IsHandled then
    ++ exit;

    if "Document Type" <> "Document Type"::Quote then
        if "Sell-to Customer No." = '' then
            exit;
```
```
[IntegrationEvent(false, false)]
local procedure OnBeforeLookupSellToContact(var SalesHeader: Record "Sales Header"; xSalesHeader: Record "Sales Header"; var IsHandled: Boolean)
begin
end;
```

Background: same event as OnBeforeLookupSellToContactNo(Rec, xRec, IsHandled), so including the IsHandled so we can skip the rest of the code in the OnLookup() procedure.

Thanks in advance,
Jerry Tyssen
Cegeka

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41235.
