### ISSUE TITLE
[Event Request] Report 6250 - Function OnAfterGetGenJnlLinePostingDate

### ISSUE THREAD

**Issue by bogdangarkusha** [microsoft/ALAppExtensions#18300]
Could you please create an Integration event in Report 6250 "Auto Posting Errors", in Function "OnAfterGetGenJnlLinePostingDate"?

**local procedure OnAfterGetGenJnlLinePostingDate(var GenJnlLine: Record "Gen. Journal Line")**
    begin
    // >>>
    IsHandled := false;
    OnBeforeCheckPostingDate(GenJnlLine,ErrorText,ErrorCounter);
    if IsHandled then
        exit;
    // <<<
        with GenJnlLine do
            if "Posting Date" = 0D then
                AddError(StrSubstNo(Text002Txt, FieldCaption("Posting Date")))    ....
end;

**Event signature:**
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckPostingDate(var GenJnlLine: Record "Gen. Journal Line";var ErrorText: array[50] of Text[250]; var ErrorCounter: Integer)
begin
end;

In our extension, we need it because we would like to extend checks for allowed posting ranges.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41251.
