### ISSUE TITLE
[Event Request] Table 5740 Transfer Header - OnBeforeVerifyNoOutboundWhseHandlingOnLocation (2)

### ISSUE THREAD

**Issue by dario-zaniboni** [microsoft/ALAppExtensions#18306]
As mentioned in the issue #15312, I also kindly request a new publisher within table 5740, in order to allow direct transfers even in the case of whse. mgt. on the outbound location (InvtSetup."Direct Transfer Posting"::"Direct Transfer" is not a valid option for process reasons).

```
	procedure VerifyNoOutboundWhseHandlingOnLocation(LocationCode: Code[10])
	var
		Location: Record Location;
		//>> NEW
		IsHandled: Boolean;
		//<< NEW
	begin
		//>> NEW
		OnBeforeVerifyNoOutboundWhseHandlingOnLocation(LocationCode, IsHandled);
		if IsHandled then
			exit;
		//<< NEW
		
		GetInventorySetup();
		if InvtSetup."Direct Transfer Posting" = InvtSetup."Direct Transfer Posting"::"Direct Transfer" then
			exit;

		if not Location.Get(LocationCode) then
			exit;

		Location.TestField("Require Pick", false);
		Location.TestField("Require Shipment", false);
	end;
```

```
	//>> NEW
	[IntegrationEvent(false, false)]
	local procedure OnBeforeVerifyNoOutboundWhseHandlingOnLocation(LocationCode: Code[10]; var IsHandled: Boolean)
	begin
	end;
	//<< NEW
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41251.
