### ISSUE TITLE
[EventRequest] Page 5052 "Contact List".UpdateContactBusinessRelationOnContacts 

### ISSUE THREAD

**Issue by Jiribu73** [microsoft/ALAppExtensions#18311]
Please add event

    local procedure UpdateContactBusinessRelationOnContacts()
    var
        ContactToUpdate: Record Contact;
        ContactRec: Record Contact;
        ContactBusinessRelation: Enum "Contact Business Relation";
        //-------------------------------OnBeforeUpdateContactBusinessRelationOnContacts:BEGIN
        IsHandled: Boolean;
        //-------------------------------OnBeforeUpdateContactBusinessRelationOnContacts:END
    begin
        //-------------------------------OnBeforeUpdateContactBusinessRelationOnContacts:BEGIN
        OnBeforeUpdateContactBusinessRelationOnContacts(IsHandled);
        if IsHandled then
            exit;
        //-------------------------------OnBeforeUpdateContactBusinessRelationOnContacts:END

        ContactRec.SetRange("Contact Business Relation", ContactBusinessRelation::" ");
        if ContactRec.IsEmpty() then
            exit;

        ContactRec.FindSet();
        repeat
            ContactToUpdate.Get(ContactRec."No.");
            if (ContactToUpdate.UpdateBusinessRelation()) then
                ContactToUpdate.Modify();
        until ContactRec.Next() = 0;
    end;

    [IntegrationEvent(false,false)]
    local procedure OnBeforeUpdateContactBusinessRelationOnContacts(var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41251.
