### ISSUE TITLE
[Event Request] Codeunit 1535 "Approvals Mgmt." - OnHasOpenApprovalEntriesOnBeforeInitialCheck

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#18313]
Hi, some time ago we requested an **OnHasOpenApprovalEntriesOnAfterFilterApprovalEntry** event in codeunit 1535 (**Approvals Mgmt.**) (#11467). It was added. However, the new check (_Initial check before performing an expensive query due to the "Related to Change" flow field_) was added before the event, so this event is not suitable for us anymore since the customization changes one of the standard filters.
Therefore, would it be possible to get one more event - an **OnHasOpenApprovalEntriesOnBeforeInitialCheck** event in codeunit 1535 (**Approvals Mgmt.**), like this:
```AL
    procedure HasOpenApprovalEntries(RecordID: RecordID): Boolean
    var
        ApprovalEntry: Record "Approval Entry";
    begin
        ApprovalEntry.SetRange("Table ID", RecordID.TableNo);
        ApprovalEntry.SetRange("Record ID to Approve", RecordID);
        ApprovalEntry.SetRange(Status, ApprovalEntry.Status::Open);
        OnHasOpenApprovalEntriesOnBeforeInitialCheck(ApprovalEntry); // New Event
        // Initial check before performing an expensive query due to the "Related to Change" flow field.
        if ApprovalEntry.IsEmpty() then
            exit(false);
        ApprovalEntry.SetRange("Related to Change", false);
        OnHasOpenApprovalEntriesOnAfterApprovalEntrySetFilters(ApprovalEntry);
        exit(not ApprovalEntry.IsEmpty);
    end;
```
```AL
    [IntegrationEvent(false, false)]
    local procedure OnHasOpenApprovalEntriesOnBeforeInitialCheck(var ApprovalEntry: Record "Approval Entry")
    begin
    end;
```
#11467
Thanks!

**Comment by Stepanenko-Vadim** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
