### ISSUE TITLE
[Event Request] Codeunit 1535 "Approvals Mgmt." - OnBeforeDelegateSelectedApprovalRequest

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#18312]
Hi, would it be possible to modify the **OnBeforeDelegateSelectedApprovalRequest** event in codeunit 1535 (**Approvals Mgmt.**) by adding the **var** keyword to the **CheckCurrentUser** parameter, like this:
```AL
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDelegateSelectedApprovalRequest(var ApprovalEntry: Record "Approval Entry"; var CheckCurrentUser: Boolean; var IsHandled: Boolean)
    begin
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41325.
