### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" - OnSumSalesLines2SetFilter

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18317]
Please extend event OnSumSalesLines2SetFilter with new parameter:

```
OnSumSalesLines2SetFilter(OldSalesLine, SalesHeader, InsertSalesLine, QtyType);
```

```
[IntegrationEvent(false, false)]
local procedure OnSumSalesLines2SetFilter(var SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header"; InsertSalesLine: Boolean; QtyType: Option General,Invoicing,Shipping)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41325.
