### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" - OnPostUpdateOrderLineOnAfterUpdateInvoicedValues

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18318]
Please extend event OnPostUpdateOrderLineOnAfterUpdateInvoicedValues with new parameter:

```
OnPostUpdateOrderLineOnAfterUpdateInvoicedValues(SalesHeader, TempSalesLine);
```

```
[IntegrationEvent(false, false)]
local procedure OnPostUpdateOrderLineOnAfterUpdateInvoicedValues(var SalesHeader: Record "Sales Header"; var TempSalesLine: Record "Sales Line" temporary)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41325.
