### ISSUE TITLE
[Event Request] Codeunit 1032 "Job Planning Line-Reserve" - OnVerifyChangeOnBeforeHasError

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#18323]
Can you please provide a publisher in function VerifyChange (Similiar to VerifyChange in 99000835 "Item Jnl. Line-Reserve")

procedure VerifyChange(var NewJobPlanningLine: Record "Job Planning Line"; var OldJobPlanningLine: Record "Job Planning Line")
...

        if NewJobPlanningLine.Type <> OldJobPlanningLine.Type then begin
            if ShowError then
                NewJobPlanningLine.FieldError(Type, Text004);
            HasError := true;
        end;

        VerifyBinInJobPlanningLine(NewJobPlanningLine, OldJobPlanningLine, HasError);
        // -NewEvent
          OnVerifyChangeOnBeforeHasError(NewJobPlanningLine, OldJobPlanningLine, HasError, ShowError);
        // +NewEvent

        if HasError then
...

//Signature

    // -NewEvent
    [IntegrationEvent(false, false)]
    local procedure OnVerifyChangeOnBeforeHasError(NewJobPlanningLine: Record "Job Planning Line"; OldJobPlanningLine: Record "Job Planning Line"; var HasError: Boolean; var ShowError: Boolean)
    begin
    end;
    // +NewEvent

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41325.
