### ISSUE TITLE
CheckGLAcc in the "General Posting Setup" table

### ISSUE THREAD

**Issue by TheDenSter** [Microsoft/ALAppExtensions#1832]
We added a new G/L Account to the General Posting Setup table, and so we wanted to utilize the CheckGLAcc function. Since it is a local function I had to clone the CheckGLAcc function in my tableextension object.

Please make this function global

**Comment by JesperSchulz** [comment]
Hi Daniel! Your very first issue in this repo?! Welcome :-)
We'll look into it! I can see that we've already exposed the function in TAB15 - G/L Account and TAB325 - VAT Posting Setup. Maybe we should just expose that function everywhere? The logic is rather simple though... We'll get back to you!

**Comment by TheDenSter** [comment]
I know right, my thoughts exactly, that shows you how much actual development I've been doing. I'm using the function in the G/L Account table in my cloned function, it would just be nice to use the one in the General Posting Setup table and call that from the OnValidate trigger directly. 
![image](https://user-images.githubusercontent.com/23434319/55019140-8fb01c80-4fb1-11e9-92ae-796af9e7470f.png)

**Comment by fvet** [comment]
Requested this sometime ago and it got rejected ... #900 
Hopefully you'll get it through :)

**Comment by TheDenSter** [comment]
Ha! I totally missed that, and I even looked if this was already requested :) 

At this point if they reject it, it will make no difference at all because the cloned function is already there and working in my extension. 

So @fvet, do you mark these cloned functions for future removal if they ever do change them?

**Comment by fvet** [comment]
> So @fvet, do you mark these cloned functions for future removal if they ever do change them?

In general, we just copy the standard functions and move forward, possibly giving the function our own twist over time and no longer profit from possible BC improvements ... 

For example, in the past we've duplicated the 'Item Attributes' concept, since standard behavior was not 'extensible' enough, BC made some changes in the later versions to it, but we never succeeded (read : found the time) to backport the latest BC changes to our own version of the 'attributes' framework ...

**Comment by JesperSchulz** [comment]
It does seem inconsistent to me that we expose a few CheckGLAcc, and reject exposing the others. I'll move forward with the request. Seems reasonable and valid to me!
In general, however, we do try to avoid exposing local functions - for a good reason: The parameters of every global function will soon not be allowed to be changed, as a change results in a breaking change. That means that with every local function we expose, we tie ourselves further down. So unless there is a compelling argument, we try to push back.
