### ISSUE TITLE
[Request for External] Codeunit 80 "Sales-Post" - PostItemTrackingCheckReturnReceipt

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18330]
Please make function PostItemTrackingCheckReturnReceipt externally available.

```
procedure PostItemTrackingCheckReturnReceipt(SalesLine: Record "Sales Line"; RemQtyToBeInvoiced: Decimal)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41603.
