### ISSUE TITLE
[Change Logic] Page 1 "Company Information", UpdateSystemIndicator function

### ISSUE THREAD

**Issue by maksym-ch** [microsoft/ALAppExtensions#18335]
Hi, according to Customer's request, we would like to change the following functionality - remove limit of 4 characters for SystemIndicatorText  field, called from Page 1 "Company Information": 
  _local procedure UpdateSystemIndicator()
    var
        CustomSystemIndicatorText: Text[250];
        IndicatorStyle: Option;
    begin
        GetSystemIndicator(CustomSystemIndicatorText, IndicatorStyle); // IndicatorStyle is not used
        **SystemIndicatorText := CopyStr(CustomSystemIndicatorText, 1, 4);**
        SystemIndicatorTextEditable := CurrPage.Editable and ("System Indicator" = "System Indicator"::"Custom");
    end;_

replace with:
**SystemIndicatorText := CopyStr(CustomSystemIndicatorText, 1, maxstrlen(Rec."Custom System Indicator Text");**

This code (Page 1 "Company Information"): 
 _trigger OnValidate()
                    begin
                        "Custom System Indicator Text" := SystemIndicatorText;
                        SystemIndicatorOnAfterValidate;
                    end;_
updates the following field in the Company Information table
        _field(47; "Custom System Indicator Text"; Text[250])
        {
            Caption = 'Custom System Indicator Text';
        }_

Thank you.

**Comment by martijn1980-tech** [comment]
yes, this is what we need!

**Comment by maksym-ch** [comment]
@AlexanderYakunin, any news here? Thanks!

**Comment by AlexanderYakunin** [comment]
Hi! Due to design of application bar, there are max. 6 chars to display in this place. We recently extended system indicator from 4 to 6 chars. Cannot extend more without redesign on UI here.

**Comment by JesperSchulz** [comment]
Internally closed as "Won't Fix" by @AlexanderYakunin. Syncing state to GitHub.
