### ISSUE TITLE
[Request for External] report 5690 "Index Fixed Assets": InsertFAJnlLine public

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/ALAppExtensions#18344]
Could you please remove the "local" statement from the procedure InsertFAJnlLine in the report report 5690?

**Comment by matthias-planzer** [comment]
Good Morning, we would require this in combination with #18344, so protected would not be enough unfortunately.
Another option would be to add the "Sender" to the event #18344, then we could make a global procedure in a ReportExtension which would call this protected procedure.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41864.
