### ISSUE TITLE
[Event Request] - report "Job Create Sales Invoice" - OnBeforeOnInit

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#18350]
```
        trigger OnInit()
        begin
            OnBeforeOnInit(JobChoice);
        end;
```

```
 [IntegrationEvent(false, false)]
    local procedure OnBeforeOnInit(var JobChoice: Option Job,"Job Task")
    begin
    end;
```

**Comment by Stepanenko-Vadim** [comment]
JobChoice is already exposed as an external var, can't you just set it to whatever you want before running report? What's the purpose of adding a trigger just for this?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42200.
