### ISSUE TITLE
AccessByPermission for Unit Cost

### ISSUE THREAD

**Issue by ThomasBrodkorb** [Microsoft/ALAppExtensions#1835]
Please consider to add AccessByPermission for Unit Cost, Cost Amount and all related Profit fields.

Quite some customers do not want to show this information to all users, even though they have access to the Items and Item Ledger Entries.

If this is not an option, please consider to allow AccessByPermission to be altered using table extensions.

**Comment by JesperSchulz** [comment]
Thanks for sharing your idea with us. We're always looking for better ways to do things. However, this isn't the right place to share it. You'll have better luck getting it implemented and noticed by other partners if you post it to the following resources:

- For functional improvements, go to [Business Central - Ideas](http://aka.ms/bcideas)
- For feature suggestions for the AL compiler and developer tools, visit [Github.com/Microsoft/AL](https://github.com/Microsoft/AL/issues)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.

**Comment by ThomasBrodkorb** [comment]
Thank you very much for this suggestion, but that site does not work.
It lets me vote, but does no increase the counter.
