### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" - OnBeforeCreatePrepaymentLines

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18358]
Please add parameter TempSalesLineGlobal to the Event OnBeforeCreatePrepaymentLines and include sender in the event.

```
IsHandled := false;
OnBeforeCreatePrepaymentLines(SalesHeader, TempSalesLineGlobal, TempPrepmtSalesLine, CompleteFunctionality, IsHandled);
if IsHandled then
    exit;

```

```
[IntegrationEvent(true, false)]
local procedure OnBeforeCreatePrepaymentLines(SalesHeader: Record "Sales Header"; var TempSalesLineGlobal: Record "Sales Line"; var TempPrepmtSalesLine: Record "Sales Line" temporary; CompleteFunctionality: Boolean; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41440.
