### ISSUE TITLE
Purchase Invoice Error

### ISSUE THREAD

**Issue by darench** [Microsoft/ALAppExtensions#1836]
Trying to open or create a new purchase invoice leads to this error:
![image](https://user-images.githubusercontent.com/33038024/55012163-9ab47e00-4fac-11e9-9a6d-066d04ef272b.png)

Same result from:
Purchasing > Purchase Invoices > New or Open
Actions > + Purchase Invoice
Ongoing Purchase Invoices Cue > New or Open

-imageName bcinsider.azurecr.io/bcsandbox:us
Version: 14.0.29551.0-US

**Comment by JesperSchulz** [comment]
Nice catch! Let's get the issue to a team who will fix and backport it, as this repo only is for extensibility related issues in the upcoming release. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.
