### ISSUE TITLE
Add permission to codeunit 11402 'Post Code Lookup - Table'

### ISSUE THREAD

**Issue by alinat2022** [microsoft/ALAppExtensions#18365]
Hello,
Can you please add read permission on Record "Post Code Range" in codeunit 11402 "Post Code Lookup - Table"?

Desired solution:
`Permissions = tabledata "Post Code Range" = r;`

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47752.
