### ISSUE TITLE
[Request for External] Page 502 OAuth2ControlAddin

### ISSUE THREAD

**Issue by SteveyN** [microsoft/ALAppExtensions#18362]
There are 4 functions on page 502 OAuth2ControlAddIn that have scope [OnPrem].
Can we have the [OnPrem] removed, so that we can utilise this page for our cloud solution?

- SetOAuth2Properties
- GetAuthCode
- GetAuthError
- GetGrantConsentSuccess

Doesn't appear to be any reason to keep these OnPrem, and the result is we must duplicate the page entirely to use it.
The OAuth2ControlAddIn add-in it references is pure javascript.

This is the case as of 20.1

**Comment by AlexanderYakunin** [comment]
We cannot expose this due to security reasons.
