### ISSUE TITLE
[extensibility-bug] OnAfterGetDatabaseTableTriggerSetup

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#18361]
Hello!
In codeunit 49 GlobalTriggerManagement we have a event OnAfterGetDatabaseTableTriggerSetup  where we can enable global triggers for table, but when change log is activated in codeunit 423 "Change Log Management" this variables are overrided.
I suggest change this lines of code in codeunit 423 "Change Log Management" function GetDatabaseTableTriggerSetup
`with TempChangeLogSetupTable do begin`
    `LogInsert := "Log Insertion" <> "Log Insertion"::" ";`
   `LogModify := "Log Modification" <> "Log Modification"::" ";`
    `LogRename := "Log Modification" <> "Log Modification"::" ";`
    `LogDelete := "Log Deletion" <> "Log Deletion"::" ";`
`end;`

to

`with TempChangeLogSetupTable do begin`
    `LogInsert := LogInsert  or "Log Insertion" <> "Log Insertion"::" ";`
   `LogModify := LogModify  or "Log Modification" <> "Log Modification"::" ";`
    `LogRename := LogRename  or "Log Modification" <> "Log Modification"::" ";`
    `LogDelete := LogDelete  or "Log Deletion" <> "Log Deletion"::" ";`
`end;`

**Comment by Joerio** [comment]
I have the same issue. My code worked fine before, but it seems the event order was changed since the last update. 
Now this event (codeunit 423) is after mine, and it overwrites the 'true' value of LogModify to 'false'.

**Comment by Oleg-Romashkov** [comment]
Hi,

This problem has been fixed. Deploy to 20.0 - 20.2 is in progress now.

Rgds,
Oleg.
