### ISSUE TITLE
[Event Parameter Request] #16672: Add Parameter CurrFieldNo

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/ALAppExtensions#18383]
Could you please add the CurrFieldNo parameter to the Event requested in #16672? Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41534.
