### ISSUE TITLE
Handling DocumentIsPosted variable in document pages

### ISSUE THREAD

**Issue by pmohanakrishna** [Microsoft/ALAppExtensions#184]
due to some limitations, we are using our own POST action in all sale and purchase documents pages
example : page 42
code under standard post action is 

![image](https://user-images.githubusercontent.com/23735402/34093791-478734f8-e3f0-11e7-9703-46ce972402cc.png)

We cant access DocumentIsPosted variable in event subscribed to NEW Post action and we are getting document not posted confirmation event after posting documents.

Please provide a way to handle DocumentIsPosted .. may be by adding this to table etc.

**Comment by JesperSchulz** [comment]
A fix for the issue will ship in an upcoming update!
