### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - OnBeforeGetPurchLines

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#18401]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnBeforeGetPurchLines' to be added to procedure 'GetPurchLines' in codeunit 90 "Purch.-Post";

````
    procedure GetPurchLines(var PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; QtyType: Option General,Invoicing,Shipping)
    begin
        OnBeforeGetPurchLines(); //new
        FillTempLines(PurchHeader, TempPurchLineGlobal);
        if QtyType = QtyType::Invoicing then
            CreatePrepmtLines(PurchHeader, false);
        SumPurchLines2(PurchHeader, PurchLine, TempPurchLineGlobal, QtyType, true);
    end;
````
````
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetPurchLines()
    begin
    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41631.
