### ISSUE TITLE
[Event Request] Codeunit 23  Item Jnl.-Post Batch OnAfterCode

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#18415]
Can you please provide a publisher in Codeunit 23 OnAfterCode (similiar to CU 7304 "Whse. Jnl.-Register Batch")

    local procedure "Code"()
    var
        UpdateAnalysisView: Codeunit "Update Analysis View";
        UpdateItemAnalysisView: Codeunit "Update Item Analysis View";
        PhysInvtCountMgt: Codeunit "Phys. Invt. Count.-Management";
        OldEntryType: Enum "Item Ledger Entry Type";
        RaiseError: Boolean;
    begin
        OnBeforeCode(ItemJnlLine);
        ....
        if not SuppressCommit then
            Commit();

        // -New
        OnAfterCode(ItemJnlLine, ItemJnlBatch, ItemRegNo, WhseRegNo);
        //  +New
    end;

// Signature

    // -New
    [IntegrationEvent(false, false)]
    local procedure OnAfterCode(var ItemJournalLine: Record "Item Journal Line"; ItemJournalBatch: Record "Item Journal Batch"; ItemRegNo: Integer; WhseRegNo: Integer)
    begin
    end;
    // +New

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41782.
