### ISSUE TITLE
[Scope Change] Table - 1518 Integration Event OnAfterIsNotificationEnabled

### ISSUE THREAD

**Issue by Kskaar18** [microsoft/ALAppExtensions#18416]
Please remove the scope OnPrem for Integration Event OnAfterIsNotificationEnabled in My Notifications table.

Wouldn't mind if OnPrem scope was removed on the procedures OpenFilterSettings and GetFiltersAsDisplayText in same table as well.

**Comment by AlexanderYakunin** [comment]
No, we cannot remove this scope for event. The reason for this scope is that this event had been made global procedure by mistake (as all events must be defined as local procedure). We could not change signature of procedure and therefore added scope OnPrem. If you need to raise this event from your code, we should consider adding global procedure which will run this event. Two other procedures can be made global, this is ok.

**Comment by Kskaar18** [comment]
Hi, thanks for the reply.

My intention is to make an eventsubscriber not raising the publisher.
Is this still possible when the eventpublisher is OnPrem scope?
Otherwise is it possible to add a new event like the existing one but defined as local that is not OnPrem Scope.

Removing the OnPrem scope on the procedures would still be appreciated.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41864.
