### ISSUE TITLE
Table 5965 "Service Contract Header": Existing "Service Contract Nos." event OnBeforeGetServiceContractNos issue

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#18414]
With request https://github.com/microsoft/ALAppExtensions/issues/9569 changes were made only in the AssistEdit function but not in all the other relevant places. I tried serviceshub (Request ID: 2204250010000840) but they concluded it was the responsibility of ALAppExtensions to fix this:

Somewhere between BC17.00 and BC17.03 a change was made in table 5965 "Service Contract Header" to use eventing in the popular no. series area.
In the OnValidate of field "Contract No." and the OnInsert trigger the function GetServiceContractNos() is missing:
You can check the same behaviour in T36, T38 and T5900

        field(1; "Contract No."; Code[20])
        {
            Caption = 'Contract No.';

            trigger OnValidate()
            begin
                if "Contract No." <> xRec."Contract No." then begin
                    ServMgtSetup.Get();
                    //NoSeriesMgt.TestManual(ServMgtSetup."Service Contract Nos."); A108B0000.o
                    NoSeriesMgt.TestManual(GetServiceContractNos()); //A108B0000.n
                    "No. Series" := '';
                end;
            end;
        }

    trigger OnInsert()
    var
        ServiceContractTemplate: Record "Service Contract Template";
        ServContractQuoteTmplUpd: Codeunit "ServContractQuote-Tmpl. Upd.";
        ConfirmManagement: Codeunit "Confirm Management";
        IsHandled: Boolean;
    begin
        ServMgtSetup.Get();
        if "Contract No." = '' then begin
            //A108B0000.Event.os
            //ServMgtSetup.TestField("Service Contract Nos.");
            //NoSeriesMgt.InitSeries(ServMgtSetup."Service Contract Nos.",xRec."No. Series",0D,
            //A108B0000.Event.oe            
            NoSeriesMgt.InitSeries(GetServiceContractNos(), xRec."No. Series", 0D, //A108B0000.Event.n
              "Contract No.", "No. Series");
        end;
        "Starting Date" := WorkDate;
        "First Service Date" := WorkDate;

        IsHandled := false;
        OnBeforeApplyServiceContractQuoteTemplate(Rec, IsHandled);
        if not IsHandled then begin
            ServiceContractTemplate.Reset();
            if ServiceContractTemplate.FindFirst() then
                if ConfirmManagement.GetResponseOrDefault(Text000, false) then begin
                    Commit();
                    Clear(ServContractQuoteTmplUpd);
                    ServContractQuoteTmplUpd.Run(Rec);
                end;
        end;

        Validate("Starting Date");
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42200.
