### ISSUE TITLE
[Event Request] Add event OnBeforeInsertColumn to Codeunit 1203 - "Import XML File to Data Exch." in procedure ParseParentChildLine.

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#18412]
Hi

We need to be able to parse multiple XML-nodes in the same data exchange definition mapping, and wonder if you can add the event OnBeforeInsertColumn to Codeunit 1203 - "Import XML File to Data Exch." in procedure ParseParentChildLine?

If you have an suggestion on how to achieve this another way, we would appreciate that as an alternative.

Is there any plans for converting Codeunit 1203 to AL Code-only without DotNet references in the futere?

**Regarding the code below:**
If it's possible to send an AL Code XMLNode instead of "XMLNodeList.ItemOf(I - 1).InnerXML", it would be better to go that way.

```
var
    ...
    // >>>>>>>>>>
    Value: Text;
    // <<<<<<<<<<
```

```
for I := 1 to NodeCount do begin
    CurrentNodeID := IncreaseNodeID(NodeID, CurrentIndex);
    CurrentIndex += 1;
    // <<<<<<<<<<
    Value := XmlNodeList.ItemOf(I - 1).InnerText;
    // InsertColumn(
    //   DataExchColumnDef."Column No.", CurrentLineNo, CurrentNodeID, ParentNodeID, XmlNodeList.ItemOf(I - 1).Name,
    //   XmlNodeList.ItemOf(I - 1).InnerText, CurrentDataExchLineDef, EntryNo);
    OnBeforeInsertColumn(Value, XMLNodeList.ItemOf(I - 1).InnerXML);
    InsertColumn(
      DataExchColumnDef."Column No.", CurrentLineNo, CurrentNodeID, ParentNodeID, XmlNodeList.ItemOf(I - 1).Name,
      Value, CurrentDataExchLineDef, EntryNo);
    // <<<<<<<<<<
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertColumn(var Value: Text; InnerXML: Text)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42200.
