### ISSUE TITLE
[Request for external] Page 11000001 "Telebank Proposal" (NL Localization)

### ISSUE THREAD

**Issue by gntpet** [microsoft/ALAppExtensions#18431]
hey AL gurus, 

Could you please make variable **BankAccFilter** as protected within page 11000001  (NL localization), so we could access it's value?

Best Regards, 
Gintautas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41864.
