### ISSUE TITLE
[Event Request] Codeunit 402 "Purchase Header Apply"

### ISSUE THREAD

**Issue by bogdangarkusha** [microsoft/ALAppExtensions#18439]
I would like to ask you to create an Integration event in codeunit 401 "Purchase Header Apply", in trigger "OnRun".

trigger OnRun()
begin
	PurchHeader.Copy(Rec);
	with PurchHeader do begin
		PayToVendorNo := "Pay-to Vendor No.";
		VendLedgEntry.SetCurrentKey("Vendor No.", Open);
		// >>>
		OnRunOnBeforeFilterVendLedgEntry(CustLedgEntry, PurchHeader);	
		// <<<		
		VendLedgEntry.SetRange("Vendor No.", PayToVendorNo);
		VendLedgEntry.SetRange(Open, true);
		OnRunOnAfterFilterVendLedgEntry(VendLedgEntry);
		if "Applies-to ID" = '' then
		...
end;

Event signature:
[IntegrationEvent(false, false)]
local procedure OnRunOnBeforeFilterVendLedgEntry(var VendorLedgerEntry: Record "Vendor Ledger Entry"; PurchHeader: Record "Purchase Header")
begin
end;

In our extension, we need it because we would like to filter Vendor Ledger Entry on extra data from Purchase Header.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41782.
