### ISSUE TITLE
[Event Request] table 81 "Gen. Journal Line"

### ISSUE THREAD

**Issue by bogdangarkusha** [microsoft/ALAppExtensions#18436]
I would like to ask you to create an Integration event in table 81 "Gen. Journal Line", in procedure "CopyCustLedgEntry"?

procedure CopyCustLedgEntry(CustLedgerEntry: Record "Cust. Ledger Entry")
begin
	"Document Type" := CustLedgerEntry."Document Type";
	Description := CustLedgerEntry.Description;
	...

	OnAfterCopyGenJnlLineFromCustLedgEntry(CustLedgEntry, Rec);
	// >>>
	OnAfterCopyGenJnlLineFromCustLedgerEntry(CustLedgerEntry, Rec);	
	// <<<	
end;

Event signature:
[IntegrationEvent(false, false)]
local procedure OnAfterCopyGenJnlLineFromCustLedgerEntry(CustLedgerEntry: Record "Cust. Ledger Entry"; var GenJournalLine: Record "Gen. Journal Line")
begin
end;

There is already an event here, but it sets a wrong variable (global variable instead of local).

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41782.
