### ISSUE TITLE
[ExtensibilityEnhancement] Page "BC O365 Sales Invoice": CurrencyFormat protected

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/ALAppExtensions#18437]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41864.
