### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt."

### ISSUE THREAD

**Issue by bogdangarkusha** [microsoft/ALAppExtensions#18434]
I would like kindly ask you to create an Integration event in Codeunit 6620 "Copy Document Mgt.", in procedure "CopySalesDocUpdateHeader".

local procedure CopySalesDocUpdateHeader(FromDocType: Enum "Sales Document Type From"; FromDocNo: Code[20]; var ToSalesHeader: Record "Sales Header"; FromSalesHeader: Record "Sales Header"; FromSalesShptHeader: Record "Sales Shipment Header"; FromSalesInvHeader: Record "Sales Invoice Header"; FromReturnRcptHeader: Record "Return Receipt Header"; FromSalesCrMemoHeader: Record "Sales Cr.Memo Header"; FromSalesHeaderArchive: Record "Sales Header Archive"; var ReleaseDocument: Boolean);
var
	OldSalesHeader: Record "Sales Header";
begin
	with ToSalesHeader do begin
		CheckCustomer(FromSalesHeader, ToSalesHeader);
		OldSalesHeader := ToSalesHeader;
		OnBeforeCopySalesHeaderDone(ToSalesHeader, FromSalesHeader);
		// >>>
		OnBeforeCopySalesHeader(FromDocType, ToSalesHeader, OldSalesHeader, FromSalesHeader, FromSalesShipmentHeader, FromSalesInvoiceHeader, FromReturnReceiptHeader, FromSalesCrMemoHeader, FromSalesHeaderArchive)
		// <<<		
		case FromDocType of
....
end;

Event signature:
[IntegrationEvent(false, false)]
local procedure OnBeforeCopySalesHeader(FromDocType: Enum "Sales Document Type From"; var ToSalesHeader: Record "Sales Header"; OldSalesHeader: Record "Sales Header"; FromSalesHeader: Record "Sales Header"; FromSalesShipmentHeader: Record "Sales Shipment Header"; FromSalesInvoiceHeader: Record "Sales Invoice Header"; FromReturnReceiptHeader: Record "Return Receipt Header"; FromSalesCrMemoHeader: Record "Sales Cr.Memo Header"; FromSalesHeaderArchive: Record "Sales Header Archive")
begin
end;

In our extension, we need it because we would like to get set extra data "from documents" to a ToSalesHeader, which has to be set before "Sell-to Customer No." validation.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41650.
