### ISSUE TITLE
Can not find Event Request #16816 in BC 20.1

### ISSUE THREAD

**Issue by AndriiBodashevskyi** [microsoft/ALAppExtensions#18441]
Hello, could you please clarify when Event Request Codeunit 99000815 "Reservation-Check Date Confl." OnSalesLineCheckOnBeforeIssueError #16816 will be added to the BC? Thank you in advance.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 41672.
