### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnAfterPostPurchLine

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18457]
Please extend Event OnAfterPostPurchLine with two additional parameters:

```
[IntegrationEvent(false, false)]
local procedure OnAfterPostPurchLine(var PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line"; PurchInvLine: Record "Purch. Inv. Line"; PurchCrMemoLine: Record "Purch. Cr. Memo Line"; CommitIsSupressed: Boolean)
begin
end;
```

```
OnAfterPostPurchLine(PurchHeader, PurchLine, PurchInvLine, PurchCrMemoLine, SuppressCommit);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41782.
