### ISSUE TITLE
Codeunit 5980 Service-Post - LockTables 

### ISSUE THREAD

**Issue by marcbosgraaf** [microsoft/ALAppExtensions#18451]
We would like to request a publisher "OnLockTablesOnBeforeGLEntryFindLast" in function LockTables so we can do a SetLoadFields.
Thank you.

Event Declaration:

    [IntegrationEvent(false, false)]
    local procedure OnLockTablesOnBeforeGLEntryFindLast(var GLEntry: Record "G/L Entry")
    begin
    end;

Event Call:

    local procedure LockTables(var ServiceLine: Record "Service Line"; var GLEntry: Record "G/L Entry")
    var
        InvSetup: Record "Inventory Setup";
    begin
        ServiceLine.LockTable();

        if not InvSetup.OptimGLEntLockForMultiuserEnv() then begin
            GLEntry.LockTable();

            // ----> new publisher
            OnLockTablesOnBeforeGLEntryFindLast(GLEntry)
            // <---- end new publisher

            if GLEntry.FindLast() then;
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42366.
