### ISSUE TITLE
[Request-For-External] Codeunit 8800 "Custom Layout Reporting" - Procedure SaveReportRequestPageParameters 

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18450]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

[Request-For-External] Codeunit 8800 "Custom Layout Reporting" - Procedure from Internal to Global

```
procedure SaveReportRequestPageParameters(ReportID: Integer; XMLText: Text)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41864.
