### ISSUE TITLE
[Event Request] table 5407 "Prod. Order Component": CreateDim

### ISSUE THREAD

**Issue by TimCsr** [microsoft/ALAppExtensions#18453]
Object: table 5407 "Prod. Order Component"

Function: CreateDim

Integration Event:
OnBeforeCreateDim(Rec, IsHandled);

local procedure OnBeforeCreateDim(var  ProdOrderComponent: Record "Prod. Order Component"; var IsHandled: Boolean)
![image](https://user-images.githubusercontent.com/50943286/171843169-9888dfe8-ef3d-4aa4-931d-694a18eed48c.png)

**Comment by Stepanenko-Vadim** [comment]
There is already an `OnAfterCreateDim(Rec, DefaultDimSource);` at the end that has been implemented for another request, I assume that it will work in your case too, since you can replace all the dimension fields with whatever you want in that event?
