### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnRunOnBeforePostPurchLine

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18455]
Please extend Event OnRunOnBeforePostPurchLine with additional parameter - PurchaseHeader:

```
[IntegrationEvent(false, false)]
local procedure OnRunOnBeforePostPurchLine(var PurchaseHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line")
begin
end;
```

```
PurchaseLinesProcessed := false;
if TempPurchLineGlobal.FindSet() then
    repeat
        OnRunOnBeforePostPurchLine(PurchHeader, TempPurchLineGlobal);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42366.
