### ISSUE TITLE
[Parameter Update] Codeunit 1605 "PEPPOL Management" Procedure GetAdditionalDocRefInfo

### ISSUE THREAD

**Issue by markusfjolnisson** [microsoft/ALAppExtensions#18454]
The procedure GetAdditionalDocRefInfo defined in the PEPPOL Managment codeunit needs to include a parameter for DocumentType.

The procedure is run in the PEPPOL XMLPorts (1600, 1601, 1602, 1603, 1610, 1611). 

In the procedure you expose the OnAfterGetAdditionalDocRefInfo Integration Event which we can use to add a Base64 encoded pdf to the XML file.

However, you have made the XMLPorts work for both sales and service. You are simply transferring the fields from Sales Invoice Header or Service Invoice Header (Cr. Memo tables for the Cr. Memo XMLPort) to a temporary version of the Sales Header table, and using that Sales Header as a source for the XMLPort. This is an issue when i try to generate a report in the GetAdditionalDocRefInfo procedure, since i need to know if i am generating a service or sales report.

I suggest you simply add the "ProcessedDocType" to the GetAdditionalDocRefInfo and OnAfterGetAdditionalDocRefInfo procedures. The "ProcessedDocType" is a global option variable in all the PEPPOL XMLPorts, which the XMLPort uses to know if it is running on a Sales or Service Table.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10730.
