### ISSUE TITLE
[Extensibility Request] Report 5186 "Remove Contacts" - Protected variable

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#18465]
For our extension, we need the **SegCriteriaManagement** and **ContactOK** global variables defined as protected, please.

```
protected var
    SegCriteriaManagement: Codeunit SegCriteriaManagement;
    ContactOK: Boolean;
```
Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41864.
