### ISSUE TITLE
[Exposure Request] codeunit 90 "Purch.-Post" - ResetTempLines

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18461]
Please make function ResetTempLines in Codeuniot 90 externally available.

```
procedure ResetTempLines(var TempPurchLineLocal: Record "Purchase Line" temporary)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41864.
