### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnAfterCheckTrackingSpecification

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18476]
New Event at the end of the function CheckTrackingSpecification:

```
local procedure CheckTrackingSpecification(PurchHeader: Record "Purchase Header"; var TempItemPurchLine: Record "Purchase Line" temporary)
var
...
begin
...
...
...
    OnAfterCheckTrackingSpecification(PurchHeader, TempItemPurchLine);
end;
```

```
[IntegrationEvent(true, false)]
local procedure OnAfterCheckTrackingSpecification(PurchHeader: Record "Purchase Header"; var TempItemPurchLine: Record "Purchase Line" temporary);
begin
end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41884.
