### ISSUE TITLE
License error when modifying Posted documents - BC20.1

### ISSUE THREAD

**Issue by quadfin** [microsoft/ALAppExtensions#18470]
An error occurs when attempting to Modify a posted sales document table record even though the user has effective permission Modify for the table data.
Example:
    User is SUPER
    Attempting to modify a Posted Sales Credit Memo header in AL code (decrement the 'No. Printed' field) results in
        Error
        Your licence does not grant you the following permissions on TableData Sales Cr.Memo Header: Modify.
        To view details about your permissions, see the Effective Permissions page.

This was not a problem in previous releases.

**Comment by AlexanderYakunin** [comment]
Please report bugs using technical support. This way it will be fixed within short period of time.
