### ISSUE TITLE
[Event Request] codeunit 61 "Sales-Disc. (Yes/No)" - OnBeforeOnRun

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18483]
New Event on the beginning of the Function OnRun:

```
trigger OnRun()
var
    ConfirmManagement: Codeunit "Confirm Management";
begin
    OnBeforeOnRun(Rec);
```

```
[IntegrationEvent(false, false)]
procedure OnBeforeOnRun(var SalesLine: Record "Sales Line")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 41884.
