### ISSUE TITLE
BC19.0 On prem- Error when sending email using Enhanced Email feature.

### ISSUE THREAD

**Issue by JayDashti** [microsoft/ALAppExtensions#18486]
Hello,

Is this a known issue for BC19.0 on-prem, Enhanced Email, using oauth2.0? Do I need to upgrade to the latest CU or it is because of a bad setup somewhere?

**Access is denied. Check credentials and try again.**

![image](https://user-images.githubusercontent.com/43972342/172312247-2512f3ad-2f82-4da2-b1e9-7f6ce9aa31f1.png)

![image](https://user-images.githubusercontent.com/43972342/172311819-9fce232a-d030-4764-bfba-7dcef6680b73.png)

Thanks,
Jay

**Comment by JesperSchulz** [comment]
It would appear as if the user logged into BC doesn't have permissions to send emails from the address specified in the Microsoft 365 account. This doesn't look related to BC at first glimpse.

Please notice, that GitHub issues isn't the right place for you to log on-prem product defects - if this would qualify as being one. GitHub is for extensibility issues only. If you find a product defect, I'd suggest that you open a support case:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.
