### ISSUE TITLE
Error Posted Invt. Shipments No. Series - IT Business Central 20.1

### ISSUE THREAD

**Issue by VeronicaGoglia** [microsoft/ALAppExtensions#18489]
Hi AL-Team,
we found an error with Posted Invt. Shipments. The posted document took temp no series (Invt. Shipment Nos) instead of (Posted Invt. Shipment Nos.)

Below the screen 
![2022-06-07_093721](https://user-images.githubusercontent.com/57795392/172323182-c3cab1c0-0f1c-4bcf-81ba-444ebcf5cf40.png)

![2022-06-07_093848](https://user-images.githubusercontent.com/57795392/172323514-0c7fd58e-0b0a-44df-9732-cf6e4c99f298.png)

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
