### ISSUE TITLE
[Event Request] Codeunit 5404 "Lead-Time Management" - procedure ManufacturingLeadTime - OnManufacturingLeadTimeOnBeforeExitLeadTimeCalculation

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18502]
Please add an Event OnManufacturingLeadTimeOnBeforeExitLeadTimeCalculation in ManufacturingLeadTime in Codeunit 5404 "Lead-Time Management"

```
procedure ManufacturingLeadTime(ItemNo: Code[20]; LocationCode: Code[10]; VariantCode: Code[10]): Code[20]
    begin
        // Returns the leadtime in a date formula

        GetPlanningParameters.AtSKU(SKU, ItemNo, VariantCode, LocationCode);
        OnManufacturingLeadTimeOnBeforeExitLeadTimeCalculation(SKU); <-- NEW EVENT
        exit(Format(SKU."Lead Time Calculation"));
    end;
```

```
    [IntegrationEvent(false,false)]
    local procedure OnManufacturingLeadTimeOnBeforeExitLeadTimeCalculation(SKU: Record "Stockkeeping Unit" temporary)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42323.
