### ISSUE TITLE
[Event Request] Codeunit 5404 "Lead-Time Management" - procedure SafetyLeadTime - OnSafetyLeadTimeOnBeforeExitSafetyLeadTime

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18503]
Please add an Event OnSafetyLeadTimeOnBeforeExitSafetyLeadTime in SafetyLeadTime in Codeunit 5404 "Lead-Time Management"

```
procedure SafetyLeadTime(ItemNo: Code[20]; LocationCode: Code[10]; VariantCode: Code[10]): Code[20]
    begin
        // Returns the safety lead time in a date formula

        GetPlanningParameters.AtSKU(SKU, ItemNo, VariantCode, LocationCode);
        OnSafetyLeadTimeOnBeforeExitSafetyLeadTime(SKU); <-- NEW EVENT
        exit(Format(SKU."Safety Lead Time"));
    end;   
```

```
    [IntegrationEvent(false, false)]
    local procedure OnSafetyLeadTimeOnBeforeExitSafetyLeadTime(SKU: Record "Stockkeeping Unit" temporary)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42323.
