### ISSUE TITLE
[Event Request] table 37 "Sales Line" - OnBeforeCheckPrepmtAmounts

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18519]
Please add new Event OnBeforeCheckPrepmtAmounts in function CheckPrepmtAmounts

```
local procedure CheckPrepmtAmounts()
var
    RemLineAmountToInvoice: Decimal;
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeCheckPrepmtAmounts(Rec, IsHandled);
    if IsHandled then
        exit;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckPrepmtAmounts(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42366.
