### ISSUE TITLE
[Event Request] table 37 "Sales Line" - OnBeforeValidatePrepmtLineAmount

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18518]
Please extend the Event OnBeforeValidatePrepmtLineAmount with parameter CurrFieldNo:

```
IsHandled := false;
OnBeforeValidatePrepmtLineAmount(Rec, PrePaymentLineAmountEntered, IsHandled, CurrFieldNo);
if IsHandled then
    exit;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeValidatePrepmtLineAmount(var SalesLine: Record "Sales Line"; PrePaymentLineAmountEntered: Boolean; var IsHandled: Boolean; CurrentFieldNo: Integer)
begin
end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
