### ISSUE TITLE
table 17 "G/L Entry" extend SumIndexFields for Key2; "G/L Account No.", "Posting Date"

### ISSUE THREAD

**Issue by GregorJacobsen** [microsoft/ALAppExtensions#18511]
In our product we execute several calculations based on the Quantity in Table G/L Entry. To improve the performance of the calculations we would like to have an additional SumIndexField like shown below (shortened for better reading)

```
table 17 "G/L Entry"
{
[...]
        key(Key2; "G/L Account No.", "Posting Date")
        {
            // Original: SumIndexFields = Amount, "Debit Amount", "Credit Amount", "Additional-Currency Amount", "Add.-Currency Debit Amount", "Add.-Currency Credit Amount", "VAT Amount";
            SumIndexFields = Amount, "Debit Amount", "Credit Amount", "Additional-Currency Amount", "Add.-Currency Debit Amount", "Add.-Currency Credit Amount", "VAT Amount", Quantity;
        }
[...]
}
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42366.
