### ISSUE TITLE
[Event Request] Table 81 - Gen. Journal Line - OnBeforeGetFADeprBook

### ISSUE THREAD

**Issue by Codey42** [microsoft/ALAppExtensions#18513]
Dear ALAppExtensions team,

Through this issue we would like to request adding event publisher `OnBeforeGetFADeprBook` in Table 81 Gen. Journal Line with the following signature (similar to `OnAfterGetFADeprBook`):

```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeGetFADeprBook(var GenJournalLine: Record "Gen. Journal Line";
                                      FANo: Code[20])
begin
end;
```

with VAR parameter `GenJournalLine`.
which would be called as follows in `GetFADeprBook`:

```AL
local procedure GetFADeprBook(FANo: Code[20])
var
    FASetup: Record "FA Setup";
    FADeprBook: Record "FA Depreciation Book";
    DefaultFADeprBook: Record "FA Depreciation Book";
begin
    // >>>> New >>>>>>>>>>>>>>>>
    OnBeforeGetFADeprBook(Rec, FANo);
    // <<<< New <<<<<<<<<<<<<<<<

    ...
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42323.
