### ISSUE TITLE
[Event Request] codeunit 6620 "Copy Document Mgt.": Event before checking Credit Limit of FromSalesHeader

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/ALAppExtensions#18528]
Could you please implement the following Event?
```diff --git a/src/CopyDocumentMgt.Codeunit.al b/src/CopyDocumentMgt.Codeunit.al
index 98dbbfb..b719cf0 100644
--- a/src/CopyDocumentMgt.Codeunit.al
+++ b/src/CopyDocumentMgt.Codeunit.al
@@ -7095,6 +7095,7 @@ codeunit 6620 "Copy Document Mgt."
                         if "Document Type".AsInteger() <= "Document Type"::Invoice.AsInteger() then begin
                             FromSalesHeader.CalcFields("Amount Including VAT");
                             "Amount Including VAT" := FromSalesHeader."Amount Including VAT";
+                            OnTransferSalesHeaderOnBeforeCheckCreditLimit(FromSalesHeader, ToSalesHeader);
                             CheckCreditLimit(FromSalesHeader, ToSalesHeader);
                         end;
                         CheckCopyFromSalesHeaderAvail(FromSalesHeader, ToSalesHeader);
@@ -9478,5 +9479,10 @@ codeunit 6620 "Copy Document Mgt."
     local procedure OnAfterCopyPurchLinesToBuffer(var TempPurchaseLine: Record "Purchase Line"; FromPurchaseLine2: Record "Purchase Line"; FromPurchaseLine: Record "Purchase Line")
     begin
     end;
+
+    [IntegrationEvent(false, false)]
+    local procedure OnTransferSalesHeaderOnBeforeCheckCreditLimit(var FromSalesHeader: Record "Sales Header"; var ToSalesHeader: Record "Sales Header")
+    begin
+    end;
 }
 
```

**Comment by Stepanenko-Vadim** [comment]
Can't you use already existing **OnBeforeCheckCreditLimit** inside **CheckCreditLimit** procedure?

**Comment by matthias-planzer** [comment]
@Stepanenko-Vadim After investigating the use of the named event, I found out there are two reasons why this won't work the same way:
1) CheckCreditLimit is called twice. The other call to this procedure comes from a Sales Invoice Header (with TransferFields). I don't think there is a way to tell those two calls apart. I only need to change call shown in the code I included into this Issue.
2) The prcoedure CheckCreditLimit doesn't pass FromSalesHeader and ToSalesHeader by reference, plus the Event OnBeforeCheckCreditLimit doesn't pass FromSalesHeader and ToSalesHeader by reference. 
The CheckCreditLimit Pass By Reference is not required, but nice to have, while the OnBeforeCheckCreditLimit Pass By Reference is required.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42571.
