### ISSUE TITLE
[Event Request] Codeunit 7600 "Calendar Management" - procedure IsNonworkingDay - OnIsNonworkingDayBeforeCheckDateStatus

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18536]
Please add an Event OnIsNonworkingDayBeforeCheckDateStatus in IsNonworkingDay in Codeunit 7600 "Calendar Management"

```
procedure IsNonworkingDay(TargetDate: Date; var CustomizedCalendarChange: Record "Customized Calendar Change"): Boolean
begin
    CustomizedCalendarChange.Date := TargetDate;
    OnIsNonworkingDayBeforeCheckDateStatus(CustomizedCalendarChange); <- NEW EVENT
    CheckDateStatus(CustomizedCalendarChange);
    exit(CustomizedCalendarChange.Nonworking);
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnIsNonworkingDayBeforeCheckDateStatus(var CustomizedCalendarChange: Record "Customized Calendar Change")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42495.
