### ISSUE TITLE
[Event Request] Codeunit 90 new event on procedure InsertReceiptLine

### ISSUE THREAD

**Issue by calliopedavidroldan** [microsoft/ALAppExtensions#18546]
Hi,

I requested the adding of a publisher in the InsertReceiptLine function (issue 17885).
The publisher has been added in the BaseApp version **20.1.39764.41543** but the parameter _PurchRcptLine_ is missing  :

```
        IsHandled := false;
        OnInsertReceiptLineOnBeforeProcessWhseShptRcpt(PurchLine, IsHandled, CostBaseAmount, PurchRcptLine);
        if not IsHandled then
            if (PurchLine.Type = PurchLine.Type::Item) and (PurchLine."Qty. to Receive" <> 0) then begin
                ShouldGetWhseRcptLine := WhseReceive and PurchLine.IsInventoriableItem();
                > 
                OnInsertReceiptLineOnAfterCalcShouldGetWhseRcptLine(PurchRcptHeader, PurchLine, PostedWhseRcptHeader, WhseRcptHeader, CostBaseAmount, WhseReceive, WhseShip, ShouldGetWhseRcptLine);
                <
                if ShouldGetWhseRcptLine then

```

Could you add this parameter ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42200.
