### ISSUE TITLE
[Exposure Request] codeunit 442 "Sales-Post Prepayments" - BuildInvLineBuffer

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18542]
Please make function BuildInvLineBuffer externally available.

```
procedure BuildInvLineBuffer(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; DocumentType: Option; var TempPrepmtInvLineBuf: Record "Prepayment Inv. Line Buffer" temporary; UpdateLines: Boolean)
var

```

**Comment by AlexanderYakunin** [comment]
Hello! I would like to understand how you are going to use this procedure, if we make it external. We would prefer to keep it as internal implementation, to be able to change it in the future without affection partner extensions.

**Comment by miljance** [comment]
Hi,

Thank you for clarification. I understand. We are migrating legacy solution to extension. In this case I stumbled upon the code calling this function. In this solution the Prepayment Invoices are not automatically posted as in standard BC but can be viewed prior to posting instead. If you would prefer this function to stay internal because of change in near/distant future I can understand that. I will duplicate the logic.

**Comment by AlexanderYakunin** [comment]
Thank you for understanding, closing.
