### ISSUE TITLE
[Event Request] Codeunit 80 add sender and new parameters on event OnBeforePostItemTrackingLine

### ISSUE THREAD

**Issue by calliopedavidroldan** [microsoft/ALAppExtensions#18556]
Hi,

We need to add the sender and new parameters on event OnBeforePostItemTrackingLine to be able to change the way to posting specific sales invoice line :

  ```
  [IntegrationEvent(true, false)]
    local procedure OnBeforePostItemTrackingLine(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; var TempItemLedgEntryNotInvoiced: Record "Item Ledger Entry" temporary; HasATOShippedNotInvoiced: Boolean; var IsHandled: Boolean; var ItemLedgShptEntryNo: integer; var RemQtyToBeInvoiced: decimal; var RemQtyToBeInvoicedBase: decimal; SalesInvHeader: record "Sales Invoice Header"; SalesCrMemoHeader: record "Sales Cr.Memo Header")
    begin
    end;
```

Could you change the property and add new parameters to this event ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42200.
