### ISSUE TITLE
[Event Request] Codeunit 90 add sender on event OnPostItemChargeOnAfterPostItemJnlLine

### ISSUE THREAD

**Issue by calliopedavidroldan** [microsoft/ALAppExtensions#18559]
Hi,

We need to add the sender on event OnPostItemChargeOnAfterPostItemJnlLine to be able to change the way to posting specific purchase invoice item charge line :

```
    [IntegrationEvent(true, false)]
    local procedure OnPostItemChargeOnAfterPostItemJnlLine(PurchaseHeader: Record "Purchase Header"; PurchaseLine: Record "Purchase Line"; ItemChargeAssignmentPurch: Record "Item Charge Assignment (Purch)")
    begin
    end;
```

Could you change the property to this event ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42200.
