### ISSUE TITLE
[Extensibility Bug] report 1322 "Standard Purchase - Order" TotalSubTotal not reset

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#18557]
We are using the `report 1322 "Standard Purchase - Order"` with an rdlc layout and we would like to use the global variables `TotalSubTotal` & `TotalInvoiceDiscountAmount` in the layout.

As soon as multiple Purch. Orders are selected for printing these totals are incorrect from the second report onwards, since they aren't reset when the document is changed.

Right now we have the following options:
 1. We copy those two variables and fix it with a report extension
 2. You fix the code and reset these global variables. **(Preferred Solution)**
 ```al
trigger OnAfterGetRecord()
begin
    TotalAmount := 0;
    //+Change
    TotalSubTotal := 0;
    TotalInvoiceDiscountAmount := 0;
    //-Change
    CurrReport.Language := Language.GetLanguageIdOrDefault("Language Code");

    FormatAddressFields("Purchase Header");
    FormatDocumentFields("Purchase Header");
    if BuyFromContact.Get("Buy-from Contact No.") then;
    if PayToContact.Get("Pay-to Contact No.") then;

    if not IsReportInPreviewMode then begin
        CODEUNIT.Run(CODEUNIT::"Purch.Header-Printed", "Purchase Header");
        if ArchiveDocument then
            ArchiveManagement.StorePurchDocument("Purchase Header", LogInteraction);
    end;
end;
 ```
 3. You make these two global variables **protected**, that we can solve it on our own.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45051.
