### ISSUE TITLE
[Event Request] Page 5905 "Service Lines" - OnOpenPageOnBeforeSetSelectionFilter

### ISSUE THREAD

**Issue by juacefer** [microsoft/ALAppExtensions#18568]
Please, add a new event in page 5905 "Service Lines"

trigger OnOpenPage()
var
	PriceCalculationMgt: Codeunit "Price Calculation Mgt.";
begin
	ExtendedPriceEnabled := PriceCalculationMgt.IsExtendedPriceCalculationEnabled();
	Clear(SelectionFilter);
	SelectionFilter := SelectionFilter::"Lines per Selected Service Item";
	**OnOpenPageOnBeforeSetSelectionFilter(SelectionFilter);**
	SetSelectionFilter();

The new event:

[IntegrationEvent(false, false)]
local procedure OnOpenPageOnBeforeSetSelectionFilter(var SelectionFilter: Option "All Service Lines","Lines per Selected Service Item","Lines Not Item Related")
begin
end;

Best regards

**Comment by Stepanenko-Vadim** [comment]
There is already **OnBeforeSetSelectionFilter(SelectionFilter);** inside **SetSelectionFilter**, can you use that instead?

**Comment by juacefer** [comment]
Hi Stepanenko-Vadim

This event does not meet my client's requirements.
My client needs that, when entering the service lines page, by default, the "All Service Lines" option appears, as it happens in the service lines page from offers. 

I have subscribed to the OnBeforeSetSelectionFilter event and I have added the following code

    [EventSubscriber(ObjectType::Page, Page:: "Service Lines", 'OnBeforeSetSelectionFilter', '', false, false)]
    local procedure OnBeforeSetSelectionFilterServLinesEvent(var SelectionFilter: Option)
    begin
        SelectionFilter := 0;
    end;

When you enter the service lines page, the lines are filtered with the "All Service Lines" option, that's perfect, but if you change the filter to other option, for example to "Lines per Selected Service Item", the following code is triggered

            field(SelectionFilter; SelectionFilter)
            {
                ApplicationArea = Service;
                Caption = 'Service Lines Filter';
                OptionCaption = 'All,Per Selected Service Item Line,Service Item Line Non-Related';
                ToolTip = 'Specifies a service line filter.';

                trigger OnValidate()
                begin
                    **SelectionFilterOnAfterValidate**;
                end;

In the SelectionFilterOnAfterValidate function the SetSelectionFilter function is called

    local procedure SelectionFilterOnAfterValidate()
    begin
        CurrPage.Update();
        **SetSelectionFilter**();
    end;
 
and in the SetSelectionFilter function the OnBeforeSetSelectionFilter event is called again
    procedure SetSelectionFilter()
    begin
        **OnBeforeSetSelectionFilter**(SelectionFilter);
        case SelectionFilter of
            SelectionFilter:: "All Service Lines":
                SetRange("Service Item Line No.");
            SelectionFilter:: "Lines per Selected Service Item":
                SetRange("Service Item Line No.", ServItemLineNo);
            SelectionFilter:: "Lines Not Item Related":
                SetRange("Service Item Line No.", 0);
        end;
        CurrPage.Update(false);
    end;

So it goes back into my event again and the value of the SelectionFilter variable is changed back to option 0 ("All Service Lines")

That is why we need the requested event or the current event to be changed.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42575.
