### ISSUE TITLE
[Enum Request] Transformation Rule - "Transformation Type"

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#18563]
Can you please change the "Transformation Type" option in the 'Transformation Rule' table to an extensible enum?
This way, we can get rid of the 'custom' type and create real / new transformation types.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42168.
