### ISSUE TITLE
[Event Request] Table 99000829 "Planning Component" - OnAfterGetItem

### ISSUE THREAD

**Issue by KVSDKA** [microsoft/ALAppExtensions#18566]
Please add one new Publisher in Table 99000829 "Planning Component":
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterGetItem(var Item: Record Item; var Rec: Record "Planning Component")
    begin
    end;
```
Change Function "GetItem":
```
    local procedure GetItem()
    begin
*       if "Item No." <> Item."No." then begin       //add "begin"
            Item.Get("Item No.");
*           OnAfterGetItem(Item, Rec);               //new
*       end;                                         //new
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42495.
