### ISSUE TITLE
[Event Request] Table 5896 "Inventory Adjmt. Entry (Order)" - OnGetUnroundedCostsFromItemOnAfterGetItem

### ISSUE THREAD

**Issue by KVSDKA** [microsoft/ALAppExtensions#18562]
Please add one new Publisher in Table 5896 "Inventory Adjmt. Entry (Order)":
```
    [IntegrationEvent(false, false)]
    local procedure OnGetUnroundedCostsFromItemOnAfterGetItem(var Item: Record Item; var Rec: Record "Inventory Adjmt. Entry (Order)")
    begin
    end;
```

Change Function "GetUnroundedCostsFromItem"
```
    local procedure GetUnroundedCostsFromItem()
    var
        Item: Record Item;
    begin
        Item.Get("Item No.");

*       OnGetUnroundedCostsFromItemOnAfterGetItem(Item, Rec);                 //new

        "Indirect Cost %" := Item."Indirect Cost %";
        "Overhead Rate" := Item."Overhead Rate";

        GetSingleLevelCosts;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42495.
