### ISSUE TITLE
[Application Update / Bug] DrillDownPageId / LookupPageId missing on 'Item Templ.' table

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#18577]
We're building generic framework and want to show data for any sourcetable dynamically. This is fully driven by the default lookuppage that is linked to a table.

For the standard 'Item Templ.' table, however, no default lookuppageid has been added.

![image](https://user-images.githubusercontent.com/25268332/173041575-6be957e0-7a1b-4c19-a74c-45be3ff5e6d4.png)

Please add following code to the 'Item Templ.' table

```
table 1382 "Item Templ."
{
    Caption = 'Item Template';
    LookupPageID = "Item Templ. List"; // Add
    DrillDownPageID = "Item Templ. List"; // Add
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42366.
