### ISSUE TITLE
[Extensibility Bug] codeunit 1687 "Email Logging Message" - procedure GetTextProperty returns error when JsonValue contains null value

### ISSUE THREAD

**Issue by g-franck** [microsoft/ALAppExtensions#18578]
Hi,

Although an email should always contain a subject,
When this is not the case,
The GetTextProperty procedure returns an error when the JsonValue variable contains the value "null"

```
local procedure GetTextProperty(var JsonObject: JsonObject; PropertyName: Text): Text
var
    JsonValue: JsonValue;
begin
    if GetProperty(JsonObject, PropertyName, JsonValue) then
        exit(JsonValue.AsText());
    exit('');
end;
```

>exit(JsonValue.AsText());
>Unable to convert from Microsoft.Dynamics.Nav.Runtime.NavJsonValue to Microsoft.Dynamics.Nav.Runtime.NavText..

In accordance with the documentation [JsonValue.AsText() Method](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/jsonvalue/jsonvalue-astext-method#remarks).

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 43662.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43634.
