### ISSUE TITLE
[Parameter update] Change TransformationRule.TransformText() in procedure SetField in Codeunit 1201 "Process Data Exch."

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#18574]
Can you please change the code TranformationRule.TransformText() in procedure SetField in Codeunit 1201 "Process Data Exch.".
There is logic in place to support more than 250 characters, but not when the value is passed to a transformation rule.

```
DataExchColumnDef.Get(
  DataExchFieldMapping."Data Exch. Def Code",
  DataExchFieldMapping."Data Exch. Line Def Code",
  DataExchField."Column No.");
FieldRef := RecRef.Field(DataExchFieldMapping."Field ID");
TransformedValue := DelChr(DataExchField.GetValue, '>'); // We shoud use the trim transformation rule instead of this
if TransformationRule.Get(DataExchFieldMapping."Transformation Rule") then
    //>>>>>>>>>>
    //TransformedValue := TransformationRule.TransformText(DataExchField.Value);
    TransformedValue := TransformationRule.TransformText(TransformedValue);
    //<<<<<<<<<<
IsHandled := false;
OnBeforeFormatFieldValue(TransformedValue, DataExchField, DataExchFieldMapping, FieldRef, DataExchColumnDef, IsHandled);
```

**Comment by dcenic** [comment]
This will be fixed in one of the upcoming minor relesaes for Business Central 22 (most likely 22.2), by this line
TransformedValue := TransformationRule.TransformText(DataExchField.GetValue());

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56426.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10746.
