### ISSUE TITLE
Table "Segment Line"  - add permissions

### ISSUE THREAD

**Issue by monicasuica** [microsoft/ALAppExtensions#18572]
Hello,
Can you please add the following permissions on in table "Segment Line? 

Desired solution:
table 5077 "Segment Line"
{
    Caption = 'Segment Line';
    Permissions = TableData Attachment = rd,
                  TableData "Segment Line" = rim,
                  TableData "Segment History" = rd,
                  TableData "Segment Criteria Line" = rd,
                  TableData "Segment Interaction Language" = rid;
....
}

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42366.
