### ISSUE TITLE
[EventRequest] Page 344 "Navigate" - OnBeforeNoOfRecords

### ISSUE THREAD

**Issue by jmanuelmartinez** [microsoft/ALAppExtensions#18584]
Hi, please add this event in Page 344 "Navigate" into protected procedure NoOfRecords:

```
protected procedure NoOfRecords(TableID: Integer): Integer
    begin
        Rec.SetRange("Table ID", TableID);
        OnBeforeNoOfRecords(Rec, TableID)
        if not Rec.FindFirst() then
            Rec.Init();
        Rec.SetRange("Table ID");
        exit(Rec."No. of Records");
    end;
```

Requested event:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeNoOfRecords(var Rec: Record; var TableID: Integer)
begin
end;
```

Thanks in advance, best regards.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42366.
