### ISSUE TITLE
[Extensibility] Include sender in event OnUpdateQtyToHandleOnBeforeWhseActivLineModify in table Warehouse Activity Line

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#18581]
Hello, please consider changing the value of IncludeSender to true in the following event in table 5767 "Warehouse Activity Line"

```
    [IntegrationEvent(true, false)]
    local procedure OnUpdateQtyToHandleOnBeforeWhseActivLineModify(var WarehouseActivityLine: Record "Warehouse Activity Line")
    begin
    end;
```

or, alternatively, adding a "Rec" parameter to it and raising it accordingly

```
    [IntegrationEvent(false, false)]
    local procedure OnUpdateQtyToHandleOnBeforeWhseActivLineModify(var WarehouseActivityLine: Record "Warehouse Activity Line"; Rec: Record "Warehouse Activity Line")
    begin
    end;

    local procedure UpdateQtyToHandle(var WhseActivLine: Record "Warehouse Activity Line")
    begin
        [...]
        OnUpdateQtyToHandleOnBeforeWhseActivLineModify(WhseActivLine, Rec);
        WhseActivLine.Modify();
    end;
```

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42200.
