### ISSUE TITLE
Request more workflow template for Item Journal and FA Journal

### ISSUE THREAD

**Issue by hgnamvn** [microsoft/ALAppExtensions#186]
The system already have workflow template for **general journal** (MS-GJBAPW and MS-GJLAPW).
So, please also do:
 - Implement more workflow template for Item journal (maybe: MS-IJBAPW and MS-IJLAPW) for **"Item journal"** page.
 - Implement more workflow template for Fixed Asset (maybe: MS-FAJBAPW and MS-FAJLAPW) for **"FA journal"** page.

**Comment by ikoletic** [comment]
We currently don't have plans to extend this. If you feel strongly about this make sure to add this as product suggestion on https://aka.ms/bcideas.
