### ISSUE TITLE
[Request for External] ValidateFieldRelationAgainstPackageData in Codeunit 8611 "Config. Package Management"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#18600]
We would like to use ValidateFieldRelationAgainstPackageData in Codeunit 8611 "Config. Package Management" for our own check on the existing event trigger OnAfterValidatePackageDataRelation.
Could you please make the procedure ValidateFieldRelationAgainstPackageData public and external ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42225.
