### ISSUE TITLE
Codeunit 1535 "Approvals Mgmt. - Event Request for OnCreateApprovalRequestOnBeforeSetApproverType

### ISSUE THREAD

**Issue by WJMSmit** [microsoft/ALAppExtensions#18603]
Good afternoon,

The following event request has been approved in July 2021, but is not yet implemented: https://github.com/microsoft/ALAppExtensions/issues/13311.

Can you please let us know what is the status of this requested event?

Kind regards,

Helmut Smit

**Comment by Stepanenko-Vadim** [comment]
It has been implemented as **OnBeforeCreateApprovalRequests** with same signature, but instead being called 1 line higher.

**Comment by WJMSmit** [comment]
Thank you for your answer.

We will investigate if we can also use this event or that it really needs to be after 'PopulateApprovalEntryArgument'.

Kind regards,

Helmut Smit

**Comment by Stepanenko-Vadim** [comment]
Please open a new issue if you find that you need it after PopulateApprovalEntryArgument with scenario why so we can look into it.
I will close this one for now.
