### ISSUE TITLE
[Question] No BuildNo in #17109. When will this be implemented?

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/ALAppExtensions#18613]
Hi

I don't know if a Issue is the right place for this, but I would like to know when the Issue #17109 will be implemented.
When a Issue is closed, there is usually a build no. At the mentioned Issue, there isn't one.
Also, it would be nice to know if the Build No. is the last or the second last number in the version of a Build.
For example 20.2.41144.42126 => Is the Build No. 41144 or 42126?

Thanks for your help and regards
Matthias

**Comment by AlexanderYakunin** [comment]
We implement enums in master only (or in 21.0)
