### ISSUE TITLE
Need a way to add options to an Option field

### ISSUE THREAD

**Issue by JimAIT** [microsoft/ALAppExtensions#1861]
Because the OptionString property can't be extended, is there no way to do this now.  Use to add a bunch of commas at the end of the OptionString (just in case Nav added more in later versions) and then add additional options.  

The specific field I'm looking at now is the Document Type in the Sales Comment Line table.

**Comment by SirBETE** [comment]
There is:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums

and see #643

**Comment by JimAIT** [comment]
Ok, so if every option field that I need to extended is turned into an enum in the spring release I should be ok.

Thanks,

Jim Welch | Solution Architect
p. 631.756.2700 x718
accessIT | contractERP

**Comment by JesperSchulz** [comment]
I am sorry to disappoint you, but no options are going to be converted to extensible enums in the spring release of Business Central. We have run into problems when converting options to enums, requiring us to do some refactoring on the base application before we can proceed with the conversion. I'm afraid you will have to wait a little longer, before any progress can be made. I will tag your request as an enum request and add it to our long backlog of enum requests.

**Comment by JimAIT** [comment]
Ok, thanks for the update.  Hopefully they will be in the fall release.  Thanks.

**Comment by frivadulla** [comment]
> 
> 
> I am sorry to disappoint you, but no options are going to be converted to extensible enums in the spring release of Business Central. We have run into problems when converting options to enums, requiring us to do some refactoring on the base application before we can proceed with the conversion. I'm afraid you will have to wait a little longer, before any progress can be made. I will tag your request as an enum request and add it to our long backlog of enum requests.

When we can expect this to be done?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
