### ISSUE TITLE
[Accessibility Request] codeunit 9702 "Cues And KPIs Impl." - GetCustomizedCueStyleOption

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#18619]
In procedure GetCustomizedCueStyleOption in codeunit 9702 "Cues And KPIs Impl." we have the event OnBeforeGetCustomizedCueStyleOption.
This works well to override the cue style.
But I only want to override the cue style if the use hasn't personalized the setup.
Cue Setup is internal, so I cannot check that myself.
Can you add a event in the end if the procedure that only runs when a personalized setup is missing.
Or add a procedure to CuesAndKPIs to be able to check if a personalized setup exists?

**Comment by JesperSchulz** [comment]
What would such a procedure look like? Something along the lines of this?
`procedure PersonalizedCueSetupExists(TableID: Integer; FieldID: Integer): Boolean`

**Comment by auzhhv** [comment]
> What would such a procedure look like? Something along the lines of this? `procedure PersonalizedCueSetupExists(TableID: Integer; FieldID: Integer): Boolean`

It will solve the problem, yes :)
I assume that the procedure will check based on the current user?

**Comment by auzhhv** [comment]
> That was the idea, yes. It could also check if any personalizations exist. That call is up to you.

I agree with your suggestion :)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43366.
