### ISSUE TITLE
[Event request] report 11000012 "SEPA ISO20022 Pain 01.01.03" OnBeforeDownloadHandler

### ISSUE THREAD

**Issue by Wildrik** [microsoft/ALAppExtensions#18616]
Report 11000012 "SEPA ISO20022 Pain 01.01.03" creates a SEPA file and downloads it immediately. Some of our customers do not want the generated file to be downloaded immediately. Instead they want the file to be saved somewhere in order for someone else to submit it to the bank. We would like an event to be added just before the line below that contains a stream of the output file. This would allow us to save the file. The line below should not be executed if the event handles the output file.

FileMgt.DownloadHandler(ServerTempFileName, '', '', '', ExportFileName);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42232.
