### ISSUE TITLE
[Issue with existing Event] "Create Pick" OnBeforeFindBWPickBin

### ISSUE THREAD

**Issue by GaryFrostick2** [microsoft/ALAppExtensions#18614]
The event OnBeforeSetBinCodeFilter in codeunit "Create Pick" is pretty useless in its current form. AN event is needed here to influence Bin Selection and whilst the intention of the event  is exactl;y what is required there is a flaw in the implementation. The event should allow the BinCodeFilterText to be amended but the end of the IsHandled Condition is in the incorrect place. See below:

IsHandled := false;
            OnBeforeSetBinCodeFilter(BinCodeFilterText, LocationCode, ItemNo, VariantCode, ToBinCode, IsHandled);
            if not IsHandled then begin
                if Location."Require Pick" and (Location."Shipment Bin Code" <> '') then
                    AddToFilterText(BinCodeFilterText, '&', '<>', Location."Shipment Bin Code");
                if Location."Require Put-away" and (Location."Receipt Bin Code" <> '') then
                    AddToFilterText(BinCodeFilterText, '&', '<>', Location."Receipt Bin Code");
                if ToBinCode <> '' then
                    AddToFilterText(BinCodeFilterText, '&', '<>', ToBinCode);
                **End of ISHandled Condition Should be here**
                if BinCodeFilterText <> '' then
                    SetFilter("Bin Code", BinCodeFilterText);
                if WhseItemTrkgExists then begin
                    WhseItemTrackingSetup.CopyTrackingFromWhseItemTrackingLine(TempWhseItemTrackingLine);
                    SetTrackingFilterFromItemTrackingSetupIfRequiredWithBlank(WhseItemTrackingSetup);
                end; **Not here**
            end;

**Comment by Stepanenko-Vadim** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
