### ISSUE TITLE
[Extensibility Bug] table 560 "VAT Clause" Mixed Language for VAT Clause Descripton

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#18617]
The procedure `FillDescriptions` of `table 560 "VAT Clause"` only update the `"Description 2"`, if it isn't empty.
The problem is, that our customers uses the the Description 2 for the base language, but not for the foreign language.
Therefore the Description 2 is still in the Base langeuage instead of being cleared.
This results in mixed language for the descriptions

We have to use the event `OnAfterGetDescription` to clear  "Description 2", but shouldn't the description 2 being set empty if the Description has an translation?
```al
    local procedure FillDescriptions(NewDescription: Text[250]; NewDescription2: Text[250])
    begin
        if NewDescription <> '' then
            Description := NewDescription;
        if NewDescription2 <> '' then
            "Description 2" := NewDescription2;
    end;
```

**Comment by AlexanderYakunin** [comment]
Here you have special case, please manage it using event.
