### ISSUE TITLE
[GlobalFunctionRequest] Table 31004 "Sales Adv. Letter Header CZZ".CreateDim

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#18625]
Please change CreateDim function to global procedure.
from
```
local procedure CreateDim
```
to
```
procedure CreateDim
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42762.
