### ISSUE TITLE
Table 5900 "Service Header" - "OnAfterConfirmServicePrice event to "Prices Including VAT" field's validate trigger

### ISSUE THREAD

**Issue by yildiz-ozdemir** [microsoft/ALAppExtensions#18637]
Could you add "OnAfterConfirmServicePrice" event to "Prices Including VAT" - OnValidate trigger in "Service Header" table. Same structure available on "Sales Header" and "Purchase Header" tables. 

![image](https://user-images.githubusercontent.com/49477543/173785312-e305353c-632f-48af-9a91-a74f40ec8d5d.png)

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42323.
