### ISSUE TITLE
[issue with BC20 update] Global Dim be cleared when location code inserts in component line

### ISSUE THREAD

**Issue by Recafu** [microsoft/ALAppExtensions#18636]
Hi teams,

With the update of BC20, there is a new feature released regrading default dimension in Locations.
However, even users doesn't setup any dimensions in Location, 
when users insert a new line in Production order component line,
system will first bring Global dim 1 and dim 2 from Prod order lines to Prod order component line,
BUT clear out dimension values for Global dim 1 and dim 2 when users enter Location code in component line.

System should keep orignal dimension values, instead of clearring them out, since there is no dimensions in Location.
Overwrite the values to blank is not reasonable.
We consider this is a defect for this new feature.
And hope you can help to fix it.

Thanks,

![image](https://user-images.githubusercontent.com/84486467/173770151-abe04c16-a450-4215-80a1-ab0480c05471.png)

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
