### ISSUE TITLE
[Bug] Unable to add a hidden field to cuegroup on the Role Center page

### ISSUE THREAD

**Issue by PiotrBC** [microsoft/ALAppExtensions#18640]
After hidding a cue on the Role Center:
![rc_hide_cue](https://user-images.githubusercontent.com/107547632/173800872-846cae45-1417-43ad-a104-e6d5c0fea3ad.png)

there is not possibility to restore it through personalisation by drag and drop:
![rc_add_field_to_page](https://user-images.githubusercontent.com/107547632/173801226-27df5369-ba70-465d-bccd-1996b4cf895b.png)

**Comment by AlexanderYakunin** [comment]
We cannot process bugs here. This forum is for extensibility issues. Please create hotfix request via technical support
