### ISSUE TITLE
[Permission Request] Table Contact ID 5050

### ISSUE THREAD

**Issue by cosminah** [microsoft/ALAppExtensions#18643]
Hello,
Can you please add the following permissions on in table Contact ? Necessary when the data is created from template.

Desired solution:
table 5050 Contact
{
 Caption = 'Contact';
    DataCaptionFields = "No.", Name;
    DataPerCompany = false;
    DrillDownPageID = "Contact List";
    LookupPageID = "Contact List";
...
                 TableData "Contact Business Relation" = rd**i**,
                  TableData Customer = rim;
                  TableData Vendor= ri;
                  TableData Bank Account= ri;
....
}

Thank you.

**Comment by cosminah** [comment]
Hi, 

Any news about this request ?

Thanks,
Cosmina

**Comment by AlexanderYakunin** [comment]
Hello, I don't think it is good idea to assign Insert permissions for Customer, Vendor and Bank Account to Contact table. This way anyone will be able to create such entities. It is much better to control this by using regular permission setup.
