### ISSUE TITLE
[Event Extension Request] Codeunit 6620 "Copy Document Mgt." - new parameters in Publisher OnCopySalesDocWithoutHeader

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#18641]
Hello, we need new parameters in the Publisher OnCopySalesDocWithoutHeader. Can you please check that? Thank you!

    procedure CopySalesDoc(FromDocType: Option; FromDocNo: Code[20]; var ToSalesHeader: Record "Sales Header")
    var
        ToSalesLine: Record "Sales Line";
        OldSalesHeader: Record "Sales Header";
        FromSalesHeader: Record "Sales Header";
        FromSalesShptHeader: Record "Sales Shipment Header";
        FromSalesInvHeader: Record "Sales Invoice Header";
        FromReturnRcptHeader: Record "Return Receipt Header";
        FromSalesCrMemoHeader: Record "Sales Cr.Memo Header";
        FromSalesHeaderArchive: Record "Sales Header Archive";
        ReleaseSalesDocument: Codeunit "Release Sales Document";
        ConfirmManagement: Codeunit "Confirm Management";
        ErrorContextElement: Codeunit "Error Context Element";
        ErrorMessageHandler: Codeunit "Error Message Handler";
        NextLineNo: Integer;
        LinesNotCopied: Integer;
        MissingExCostRevLink: Boolean;
        ReleaseDocument: Boolean;
        IsHandled: Boolean;
    begin
        with ToSalesHeader do begin
            if not CreateToHeader then begin
                TestField(Status, Status::Open);
                if FromDocNo = '' then
                    Error(Text000);
                Find;
            end;

            OnBeforeCopySalesDocument(FromDocType, FromDocNo, ToSalesHeader);

            TransferOldExtLines.ClearLineNumbers;

            if not InitAndCheckSalesDocuments(
                 FromDocType, FromDocNo, FromSalesHeader, ToSalesHeader, ToSalesLine,
                 FromSalesShptHeader, FromSalesInvHeader, FromReturnRcptHeader, FromSalesCrMemoHeader,
                 FromSalesHeaderArchive)
            then
                exit;

            ToSalesLine.LockTable();

            ToSalesLine.SetRange("Document Type", "Document Type");
            if CreateToHeader then begin
                OnCopySalesDocOnBeforeToSalesHeaderInsert(ToSalesHeader, FromSalesHeader, MoveNegLines);
                Insert(true);
                ToSalesLine.SetRange("Document No.", "No.");
            end else begin
                ToSalesLine.SetRange("Document No.", "No.");
                if IncludeHeader then
                    if not ToSalesLine.IsEmpty then begin
                        Commit();
                        if not ConfirmManagement.GetResponseOrDefault(
                             StrSubstNo(DeleteLinesQst, "Document Type", "No."), true)
                        then
                            exit;
                        ToSalesLine.DeleteAll(true);
                    end;
            end;

            if ToSalesLine.FindLast then
                NextLineNo := ToSalesLine."Line No."
            else
                NextLineNo := 0;

            if IncludeHeader then
                CopySalesDocUpdateHeader(
                    FromDocType, FromDocNo, ToSalesHeader, FromSalesHeader,
                    FromSalesShptHeader, FromSalesInvHeader, FromReturnRcptHeader, FromSalesCrMemoHeader, FromSalesHeaderArchive, ReleaseDocument)
            else
     ===>     OnCopySalesDocWithoutHeader(ToSalesHeader, FromDocType, FromDocNo, FromDocOccurrenceNo, FromDocVersionNo, FromSalesInvHeader, FromSalesCrMemoHeader);    <===========

            LinesNotCopied := 0;
            ErrorMessageMgt.Activate(ErrorMessageHandler);
            ErrorMessageMgt.PushContext(ErrorContextElement, RecordId, 0, StrSubstNo(SalesErrorContextMsg, FromDocNo));
      ****

Event signature with new parameters:

    [IntegrationEvent(false, false)]
    local procedure OnCopySalesDocWithoutHeader(var ToSalesHeader: Record "Sales Header"; FromDocType: Option; FromDocNo: Code[20]; FromOccurenceNo: Integer; FromVersionNo: Integer; FromSalesInvHeader: Record "Sales Invoice Header"; FromSalesCrMemoHeader: Record "Sales Cr.Memo Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42316.
