### ISSUE TITLE
[Event Extension Request] Codeunit 6620 "Copy Document Mgt." - new parameters in Publisher OnAfterCopyFieldsFromOldSalesHeader

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#18653]
Hello, we need new parameters in the Publisher OnAfterCopyFieldsFromOldSalesHeader. Can you please check that? Thank you!

    local procedure CopySalesDocUpdateHeader(FromDocType: Enum "Sales Document Type From"; FromDocNo: Code[20]; var SalesHeader: Record "Sales Header"; FromSalesHeader: Record "Sales Header"; FromSalesShptHeader: Record "Sales Shipment Header"; FromSalesInvHeader: Record "Sales Invoice Header"; FromReturnRcptHeader: Record "Return Receipt Header"; FromSalesCrMemoHeader: Record "Sales Cr.Memo Header"; FromSalesHeaderArchive: Record "Sales Header Archive"; var ReleaseDocument: Boolean);
        var
            OldSalesHeader: Record "Sales Header";
            CustomerTemplMgt: Codeunit "Customer Templ. Mgt.";
        begin
            with ToSalesHeader do begin
                CheckCustomer(FromSalesHeader, ToSalesHeader);
                OldSalesHeader := ToSalesHeader;
                OnBeforeCopySalesHeaderDone(ToSalesHeader, FromSalesHeader);
                case FromDocType of
                    "Sales Document Type From"::Quote,
                    "Sales Document Type From"::"Blanket Order",
                    "Sales Document Type From"::Order,
                    "Sales Document Type From"::Invoice,
                    "Sales Document Type From"::"Return Order",
                    "Sales Document Type From"::"Credit Memo":
                        CopySalesHeaderFromSalesHeader(FromDocType, FromSalesHeader, OldSalesHeader, ToSalesHeader);
                    "Sales Document Type From"::"Posted Shipment":
                        CopySalesHeaderFromPostedShipment(FromSalesShptHeader, ToSalesHeader, OldSalesHeader);
                    "Sales Document Type From"::"Posted Invoice":
                        CopySalesHeaderFromPostedInvoice(FromSalesInvHeader, ToSalesHeader, OldSalesHeader);
                    "Sales Document Type From"::"Posted Return Receipt":
                        CopySalesHeaderFromPostedReturnReceipt(FromReturnRcptHeader, ToSalesHeader, OldSalesHeader);
                    "Sales Document Type From"::"Posted Credit Memo":
                        TransferFieldsFromCrMemoToInv(ToSalesHeader, FromSalesCrMemoHeader);
                    "Sales Document Type From"::"Arch. Quote",
                    "Sales Document Type From"::"Arch. Order",
                    "Sales Document Type From"::"Arch. Blanket Order",
                    "Sales Document Type From"::"Arch. Return Order":
                        CopySalesHeaderFromSalesHeaderArchive(FromSalesHeaderArchive, ToSalesHeader, OldSalesHeader);
                end;
                OnAfterCopySalesHeaderDone(
                    ToSalesHeader, OldSalesHeader, FromSalesHeader, FromSalesShptHeader, FromSalesInvHeader,
                    FromReturnRcptHeader, FromSalesCrMemoHeader, FromSalesHeaderArchive);

                ClearInvoiceAndShip(ToSalesHeader);
 
                if Status = Status::Released then begin
                    Status := Status::Open;
                    ReleaseDocument := true;
                end;
                if MoveNegLines or IncludeHeader then
                    Validate("Location Code");
                CopyShiptoCodeFromInvToCrMemo(ToSalesHeader, FromSalesInvHeader, FromDocType);
                CopyFieldsFromOldSalesHeader(ToSalesHeader, OldSalesHeader);
       ===>     OnAfterCopyFieldsFromOldSalesHeader(ToSalesHeader, OldSalesHeader, MoveNegLines, IncludeHeader, FromDocType);
                if RecalculateLines then
                   ***

Event signature with new parameters:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyFieldsFromOldSalesHeader(var ToSalesHeader: Record "Sales Header"; OldSalesHeader: Record "Sales Header"; MoveNegLines: Boolean; IncludeHeader: Boolean; FromDocType: Enum "Sales Document Type From")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42316.
