### ISSUE TITLE
[Event Extension Request] Codeunit 6620 "Copy Document Mgt." - new parameters in Publisher OnCopyPurchDocWithoutHeader

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#18656]
Hello, we need new parameters in the Publisher OnCopyPurchDocWithoutHeader. Can you please check that? Thank you!

    procedure CopyPurchDoc(FromDocType: Enum "Purchase Document Type From"; FromDocNo: Code[20]; var ToPurchHeader: Record "Purchase Header")
    var
        ToPurchLine: Record "Purchase Line";
        FromPurchHeader: Record "Purchase Header";
        FromPurchRcptHeader: Record "Purch. Rcpt. Header";
        FromPurchInvHeader: Record "Purch. Inv. Header";
        FromReturnShptHeader: Record "Return Shipment Header";
        FromPurchCrMemoHeader: Record "Purch. Cr. Memo Hdr.";
        FromPurchHeaderArchive: Record "Purchase Header Archive";
        ReleasePurchaseDocument: Codeunit "Release Purchase Document";
        ConfirmManagement: Codeunit "Confirm Management";
        ErrorContextElement: Codeunit "Error Context Element";
        ErrorMessageHandler: Codeunit "Error Message Handler";
        NextLineNo: Integer;
        LinesNotCopied: Integer;
        MissingExCostRevLink: Boolean;
        ReleaseDocument: Boolean;
    begin
        with ToPurchHeader do begin
            if not CreateToHeader then begin
                TestField(Status, Status::Open);
                if FromDocNo = '' then
                    Error(Text000);
                Find;
            end;

            OnBeforeCopyPurchaseDocument(FromDocType.AsInteger(), FromDocNo, ToPurchHeader);

            TransferOldExtLines.ClearLineNumbers;

            if not InitAndCheckPurchaseDocuments(
                 FromDocType.AsInteger(), FromDocNo, FromPurchHeader, ToPurchHeader,
                 FromPurchRcptHeader, FromPurchInvHeader, FromReturnShptHeader, FromPurchCrMemoHeader,
                 FromPurchHeaderArchive)
            then
                exit;

            ToPurchLine.LockTable();

            if CreateToHeader then begin
                OnCopyPurchDocOnBeforeToPurchHeaderInsert(ToPurchHeader, FromPurchHeader, MoveNegLines);
                Insert(true);
                ToPurchLine.SetRange("Document Type", "Document Type");
                ToPurchLine.SetRange("Document No.", "No.");
            end else begin
                ToPurchLine.SetRange("Document Type", "Document Type");
                ToPurchLine.SetRange("Document No.", "No.");
                if IncludeHeader then
                    if ToPurchLine.FindFirst then begin
                        Commit();
                        if not ConfirmManagement.GetResponseOrDefault(
                             StrSubstNo(DeleteLinesQst, "Document Type", "No."), true)
                        then
                            exit;
                        ToPurchLine.DeleteAll(true);
                    end;
            end;

            if ToPurchLine.FindLast then
                NextLineNo := ToPurchLine."Line No."
            else
                NextLineNo := 0;

            if IncludeHeader then begin
                CopyPurchDocUpdateHeader(
                    FromDocType, FromDocNo, ToPurchHeader, FromPurchHeader,
                    FromPurchRcptHeader, FromPurchInvHeader, FromReturnShptHeader, FromPurchCrMemoHeader, FromPurchHeaderArchive, ReleaseDocument)
            end else
    ===>      OnCopyPurchDocWithoutHeader(ToPurchHeader, FromDocType.AsInteger(), FromDocNo, FromDocOccurrenceNo, FromDocVersionNo, FromPurchInvHeader, FromPurchCrMemoHeader);

            LinesNotCopied := 0;
            ErrorMessageMgt.Activate(ErrorMessageHandler);
            ErrorMessageMgt.PushContext(ErrorContextElement, RecordId, 0, StrSubstNo(PurchErrorContextMsg, FromDocNo));
           ***

Event signature with new parameters:

    [IntegrationEvent(false, false)]
    local procedure OnCopyPurchDocWithoutHeader(var ToPurchaseHeader: Record "Purchase Header"; FromDocType: Option; FromDocNo: Code[20]; FromOccurenceNo: Integer; FromVersionNo: Integer; FromPurchInvHeader: Record "Purch. Inv. Header"; FromPurchCrMemoHeader: Record "Purch. Cr. Memo Hdr.")
    begin
    end;

Event signature with new parameters:

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42316.
