### ISSUE TITLE
BC19.2 On Prem - codeunit 8905 "Email Message Impl." Copying Attachment values in procedure Create(EmailMessage: Codeunit "Email Message Impl.")

### ISSUE THREAD

**Issue by pseyechlo** [microsoft/ALAppExtensions#18669]
Hi,

We have an extension that sends emails with inline attachments. (It sets the  Inline & "Content Id" values. on the "Email Message Attachment" record.)
However when we Resend or "Edit and Send" the email from the Sent Emails page, these values are not copied accross to the new attachment records.
When an e-mail is copied by the Create(EmailMessage: Codeunit "Email Message Impl.") procedure, can these two values be copied to the new attachment record as well.

Regards,
Andy Wojcik

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49407.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 49535.
