### ISSUE TITLE
[Bug] Codeunit 22 - Item Jnl.-Post Line

### ISSUE THREAD

**Issue by agnieszkaszuflak** [microsoft/ALAppExtensions#18666]
Hi AL-Team,

There is an issue, that could be fixed in Business Central.

When overconsumption is posted and then negative consumption is being posted, it generates strange errors with a minus value.

We would suggest adding condition.
Please find suggested solution below. 

![image](https://user-images.githubusercontent.com/57363333/173815703-2b812e7d-19c3-4f0f-a7c1-ecbaf5b078a1.png)

After line 414.
      if ("Remaining Qty. (Base)" * "Expected Qty. (Base)") >= 0 then begin
              if ("Remaining Qty. (Base)" = 0)  and ( "Expected Qty. (Base)" < ProdOrderComp."Act. Consumption (Qty)") then
                      QtyToPost := NewRemainingQty
               else
                     QtyToPost := "Remaining Qty. (Base)" - NewRemainingQty;
end else 
 QtyToPost := NewRemainingQty;

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
