### ISSUE TITLE
[Exposure Request] Table 36 "Sales Header" - TestNoSeriesDate

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18676]
Please make function TestNoSeriesDate in table 36 "Sales Header" externally available.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
