### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnBeforeLookupBillToContactNo

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18675]
Please extend the Event OnBeforeLookupBillToContactNo with parameter xRec:

```
[IntegrationEvent(true, false)]
local procedure OnBeforeLookupBillToContactNo(var IsHandled: Boolean; var SalesHeader: Record "Sales Header"; var xSalesHeader: Record "Sales Header")
begin
end;
```

```
IsHandled := false;
OnBeforeLookupBillToContactNo(IsHandled, Rec, xRec);
if IsHandled then
    exit;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42571.
