### ISSUE TITLE
Could you add ServiceHeader parameter on "OnAfterSetServiceShptLineFilters" event in "Service-Get Shipment" Codeunit.

### ISSUE THREAD

**Issue by yildiz-ozdemir** [microsoft/ALAppExtensions#18670]
Could you add ServiceHeader parameter on "OnAfterSetServiceShptLineFilters" event in "Service-Get Shipment" Codeunit. I cannot reach ServiceHeader record but i need this one. 

![image](https://user-images.githubusercontent.com/49477543/174056795-2bae2731-a7da-4f26-89e2-134123f334db.png)

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42571.
