### ISSUE TITLE
[HideValidationDialog Request][Event Request] Table 5050 Contact 

### ISSUE THREAD

**Issue by cosminah** [microsoft/ALAppExtensions#18674]
Hi,

We would like to use the variable HideValidationDialog from Table 5050 Contact in function ChooseNewCustomerTemplate as fallow:

procedure ChooseNewCustomerTemplate(): Code[20]
...
**Actual Code**

```
 if Confirm(CreateCustomerFromContactQst, true) then begin
            CustTemplate.SetRange("Contact Type", Type);
            if CustomerTemplMgt.SelectCustomerTemplate(CustTemplate) then
                exit(CustTemplate.Code);

            Error(Text022);
        end;
```

**Desired code:**

```
        if Not HideValidationDialog then
            if Not Confirm(CreateCustomerFromContactQst, true) then
                exit('');

        CustTemplate.SetRange("Contact Type", Type);
        if CustomerTemplMgt.SelectCustomerTemplate(CustTemplate) then
            exit(CustTemplate.Code)
        else
            Error(Text022);
```

And also we need a new Event in this function (ChooseNewCustomerTemplate) :
...
```
if ContBusRel.FindFirst() then
	Error(
		Text019,
		TableCaption, "No.", ContBusRel.TableCaption, ContBusRel."Link to Table", ContBusRel."No.");
**OnBeforeSelectCustomerTemplate(Rec, CustTemplate);** -->> new Event 
```
...

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSelectCustomerTemplate(var Contact: Record Contact; var CustTemplate: Record "Customer Templ.")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42495.
