### ISSUE TITLE
[Event Request] Page 522 "View Applied Entries" - OnBeforeBlockItem

### ISSUE THREAD

**Issue by juacefer** [microsoft/ALAppExtensions#18684]
Please, add a new event in page 522 "View Applied Entries"

local procedure BlockItem(ItemNo: Code[20])
var
	Item: Record Item;
	**IsHandled: Boolean;**
begin
	Item.Get(ItemNo);
	**IsHandled := false;
	OnBeforeBlockItem(Item, IsHandled);
	if IsHandled then
		exit;**

	if Item."Application Wksh. User ID" <> UpperCase(UserId) then
		Item.CheckBlockedByApplWorksheet;

	Item."Application Wksh. User ID" := UserId;
	Item.Modify(true);
end;

The new event:

**[IntegrationEvent(false, false)]
local procedure OnBeforeBlockItem(Item: Record Item; var IsHandled: Boolean)
begin
end;**

Best regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42575.
