### ISSUE TITLE
[Extensibility Request] CompanyInformation.Table.al - Table 79 "Company Information" - Add Procedure GetRecordOnce

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#18683]
Hi

Can you please add procedure GetRecordOnce to Table 79 "Company Information?

```
// >>>>>>>>>
procedure GetRecordOnce()
begin
    if RecordHasBeenRead then
        exit;
    Get();
    RecordHasBeenRead := true;
end;
// <<<<<<<<<<

// >>>>>>>>>>
var
    RecordHasBeenRead: Boolean;
// <<<<<<<<<<

```

**Comment by andersws** [comment]
Hi.

Any updates on this issue?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46699.
