### ISSUE TITLE
Create a Test Runner with TestIsolation = Function

### ISSUE THREAD

**Issue by josalm** [microsoft/ALAppExtensions#18693]
I think that the AL Testing tool should have a test Runner with the property TestIsolation = Function. 

All of given Test Runners have TestIsolation = Codeunit
![imagem](https://user-images.githubusercontent.com/14805835/174331545-7b3596a9-45ec-4bd7-b7af-e696f24cddfb.png)

**Comment by AlexanderYakunin** [comment]
We have no plans for this work, please do it yourself if you need it
