### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line": OnFlushOperationOnBeforePostFlushedConsumption

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#18690]
I've requested event OnBeforeFlushOperation before I believe. Especially with the request to IncludeSender.
Allas this event does not work for us because during an output posting with one instance of codeunit 22 you also post consumption which might upset the global variables needed for the original posting. Therefor I need an event that is a lot lower in the procedure FlushOperation:

    local procedure FlushOperation(ProdOrder: Record "Production Order"; ProdOrderLine: Record "Prod. Order Line")
        ...
        CalledFromInvtPutawayPick := false;

        GetProdOrderRoutingLine(ProdOrderRoutingLine, OldItemJnlLine);
        OnFlushOperationOnBeforePostFlushedConsumption(ProdOrder, ProdOrderLine, ProdOrderRoutingLine, ItemJnlLine, LastOperation); //A200F0000.Event20.00
        if ProdOrderRoutingLine."Routing Link Code" <> '' then
            with ProdOrderComp do begin
                SetCurrentKey(Status, "Prod. Order No.", "Routing Link Code", "Flushing Method");

    [IntegrationEvent(true, false)]
    local procedure OnFlushOperationOnBeforePostFlushedConsumption(var ProdOrder: Record "Production Order"; var ProdOrderLine: Record "Prod. Order Line"; var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var ItemJnlLine: Record "Item Journal Line"; LastOperation: Boolean);
    begin
        //A200F0000.Event20.00 IncludeSender = true
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42575.

**Comment by Duizy1971** [comment]
I received the requested change in BC21.00 and the name was changed from
OnFlushOperationOnBeforePostFlushedConsumption
to
OnFlushOperationOnBeforeCheckRoutingLinkCode
which is all fine and dandy but please do not forget such a detail like

IncludeSender = true

Can you please fix this in 21.02?

**Comment by JesperSchulz** [comment]
We usually don't follow up on closed issues. If further changes are required, please create a new issue going forward.
@AlexanderYakunin, could you look into this case?

**Comment by Duizy1971** [comment]
This one is fixed Jesper. Probably with new issue 21120.
