### ISSUE TITLE
[Event Request] codeunit 76 "Purch.-Get Drop Shpt." - OnCodeOnAfterSalesLineSetFilters

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#18708]
Can you change parameter PurchHeader to reference in event OnCodeOnAfterSalesLineSetFilters in codeunit 76 "Purch.-Get Drop Shpt."?
I already use a similar event when getting special order lines in codeunit "Dist. Integration".
I need this to pass a variable into purchase header before calling the run trigger, then use purchase header as parameter.
Then later get the value in the OnCodeOnAfterSalesLineSetFilters event from purchase header.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42636.
