### ISSUE TITLE
Please add an Event "OnBeforeOnDeleteSalesOrderLine" in Table 18 Customer.

### ISSUE THREAD

**Issue by AshuBansal01** [microsoft/ALAppExtensions#18701]
**Please Add an Event in between the Standard code.**
OnBeforeOnDeleteSalesOrderLine(Rec, IsHandled);
  if IsHandled then
    exit;
**Standard Code:** --> Trigger OnDelete()
SalesOrderLine.SetCurrentKey("Document Type", "Bill-to Customer No.");
        SalesOrderLine.SetRange("Bill-to Customer No.", "No.");
        if SalesOrderLine.FindFirst() then
            Error(
              Text000,
              TableCaption, "No.", SalesOrderLine."Document Type");

**Expected Code After raising an Event:**
        SalesOrderLine.SetCurrentKey("Document Type", "Bill-to Customer No.");
        SalesOrderLine.SetRange("Bill-to Customer No.", "No.");
#### Required Changes <<
       OnBeforeOnDeleteSalesOrderLine(Rec, IsHandled);     
       if IsHandled then
       exit;
#### Required Changes >>
       if SalesOrderLine.FindFirst() then
            Error(
              Text000,
              TableCaption, "No.", SalesOrderLine."Document Type");

[IntegrationEvent(false, false)]
    local procedure OnBeforeOnDeleteSalesOrderLine(var Customer: Record Customer; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42575.
