### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnBeforeCopySellToAddressToBillToAddress

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18705]
Please add new Event OnBeforeCopySellToAddressToBillToAddress in the table 36:

```
procedure CopySellToAddressToBillToAddress()
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeCopySellToAddressToBillToAddress(Rec, IsHandled);
    if IsHandled then
        exit;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCopySellToAddressToBillToAddress(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
begin
end;
```

**Comment by Stepanenko-Vadim** [comment]
Handled pattern here would break calling onaftercopy, so instead there will be a regular OnBefore, you can use that to store the values and restore in onafter if you so wish.

**Comment by miljance** [comment]
Not sure that I understand. There are a lot of instances in the base app that have both OnBefore and OnAfter in the same function and the OnBefore is handled. 

Restoring it in OnAfter would be a bit hacky  but doable.

**Comment by Stepanenko-Vadim** [comment]
Here it is hidden under the condition, so it's not called all the time, but some of the times, when we implement ishandled we still want to call the onafter and it is possible if it is called unconditionally as the last line. Technically it is possible to obsolete current onafter, create a new one one line lower, but not doing that for such a small function is a preferrable alternative.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42636.
