### ISSUE TITLE
[Fix Event Request] Table 39 - Purchase Line - OnCopyFromItemOnAfterCheck

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#18703]
The 'OnCopyFromItemOnAfterCheck' event in the Purchase Line table passes the current rec but not by var. This needs to be passed by var so it can be updated. (copied from https://github.com/microsoft/ALAppExtensions/issues/2841)

```diff
[IntegrationEvent(false, false)]
-    local procedure OnCopyFromItemOnAfterCheck(PurchaseLine: Record "Purchase Line"; Item: Record Item; CallingFieldNo: Integer)
+    local procedure OnCopyFromItemOnAfterCheck(var PurchaseLine: Record "Purchase Line"; Item: Record Item; CallingFieldNo: Integer)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42575.
