### ISSUE TITLE
[Event Request] codeunit 76 "Purch.-Get Drop Shpt." - OnRunOnBeforeCode

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#18717]
Can you add event OnRunOnBeforeCode with Rec and PurchHeader as reference.
I want to be able to copy globale variables with Get and Set between the records.

```
    trigger OnRun()
    begin
        PurchHeader.Copy(Rec);
        // >>>>>>>>>>>>
        OnRunOnBeforeCode(PurchHeader, Rec);
        // <<<<<<<<<<<<
        Code;
        Rec := PurchHeader;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42636.
