### ISSUE TITLE
[Request-For-External] codeunit 99000769 "Production BOM-Check" - CheckBOMStructure

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18739]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

[Request-For-External] codeunit 99000769 "Production BOM-Check" - Procedure from Internal to Global

```
procedure CheckBOMStructure(BOMHeaderNo: Code[20]; VersionCode: Code[20]; Level: Integer)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42678.
