### ISSUE TITLE
[Request-For-External] Codeunit 99000810 Calculate Planning Route Line - LoadCapForward

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18737]
Hello, we need the following currently local procedure to be set to global. Can you please check this? Thank you!

[Request-For-External] Codeunit 99000810 Calculate Planning Route Line - Procedure from local to global

```
procedure LoadCapForward(CapType: Enum "Capacity Type"; CapNo: Code[20]; TimeType: Enum "Routing Time Type"; Write: Boolean)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42678.
