### ISSUE TITLE
[Function Request] Table 901 - Assembly Line - GetSkipVerificationsThatChangeDatabase

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#1875]
Dear ALAppExtensions team,

Through this issue we would like to request a new external function that serves as a 'getter' for global variable `SkipVerificationsThatChangeDatabase`, i.e.:
```pascal
[External] GetSkipVerificationsThatChangeDatabase() : Boolean
EXIT(SkipVerificationsThatChangeDatabase);
```

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
