### ISSUE TITLE
[Event Request] Codeunit 9988 "Word Template Impl." - Procedure GenerateSpreadsheetDataSource - OnBeforeGenerateSpreadsheetDataSource

### ISSUE THREAD

**Issue by cscheidsteff** [microsoft/ALAppExtensions#18778]
Please add an Event OnBeforeGenerateSpreadsheetDataSource in Procedure GenerateSpreadsheetDataSource in Codeunit 9988 "Word Template Impl."

    local procedure GenerateSpreadsheetDataSource(var DataCompression: Codeunit "Data Compression")
    var
        TempBlob: Codeunit "Temp Blob";
        Decorator: DotNet CellDecorator;
        XlWrkBkWriter: DotNet WorkbookWriter;
        XlWrkShtWriter: DotNet WorksheetWriter;
        ColNo: Integer;
        MailMergeField: Text;
        MailMergeFields: List of [Text];
        InStream: InStream;
        OutStream: OutStream;
    begin
        MailMergeFields := MergeFields;
        OnBeforeGenerateSpreadsheetDataSource(MailMergeFields);

        if MailMergeFields.Count() = 0 then
            exit;

        TempBlob.CreateOutStream(OutStream);
        XlWrkBkWriter := XlWrkBkWriter.Create(OutStream);
        XlWrkShtWriter := XlWrkBkWriter.FirstWorksheet();
        XlWrkShtWriter.Name := DataSourceSheetNameTxt;

        Decorator := XlWrkShtWriter.DefaultCellDecorator();

        foreach MailMergeField in MailMergeFields do begin
            ColNo += 1;
            XlWrkShtWriter.SetCellValueText(1, ConvertColNoToColName(ColNo), MailMergeField, Decorator);
        end;
        XlWrkBkWriter.Close();

        TempBlob.CreateInStream(InStream);
        DataCompression.AddEntry(InStream, DataSourceFileTxt);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGenerateSpreadsheetDataSource(var MergeFields: List of [Text])
    begin
    end;

**Comment by darjoo** [comment]
@cscheidsteff What is the use case scenario for this? To add/remove additional mergefields into the doc before the zip is generated?

**Comment by darjoo** [comment]
Closing for now, please reopen once you have more information :)

**Comment by cscheidsteff** [comment]
@darjoo I was on vacation the last two weeks, so sorry for the late reply. I would kindly ask you to reopen this ticket. I will then post the requested information as soon as possible. thx, Carsten

**Comment by darjoo** [comment]
@cscheidsteff No worries, reopened.

**Comment by cscheidsteff** [comment]
@darjoo Below as announced, some information about this request. As we found out, the number of fields offered in the mail merge field Menu of Microsoft Word is limited to max. 255 items. This limit is reached very fast with somewhat extensive tables with many fields. In addition, the handling, i.e. the creation of a mail merge template using such a long menu is extremely tedious. Therefore, it would be helpful to be able to control and thus limit the fields that are passed to the datasource file. The requested integration event would provide this possibility.

**Comment by cscheidsteff** [comment]
Hi @darjoo,
you're right, in the end both events technically do the same job. I think that the event as suggested in #18777 is the more appropriate place then. If that one will be available in the future, I think this ticket here (#18778) could be dropped. 

One more thing. While checking #18777  again, I just noticed that I accidentally seem to have passed the wrong variable when invoking the new event. 

![grafik](https://user-images.githubusercontent.com/105804990/200797981-747f9ab2-77b1-4c8e-bd58-25b9d41bd88c.png)

But you probably already noticed that too.
