### ISSUE TITLE
[Event Request] Table 5050 Contact - function TypeChange 

### ISSUE THREAD

**Issue by cosminah** [microsoft/ALAppExtensions#18774]
Hi,

We need a new event in function **TypeChange** from table Contact.

```
...
if Cont.Get("No.") then begin
            if Type = Type::Company then
                CheckDuplicates
            else
                DuplMgt.RemoveContIndex(Rec, false);
        end;

        OnAfterTypeChangeOnContact(Rec); -- >> New Event Place
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterTypeChangeOnContact(var Contact: Record Contact)
    begin
    end;

Thanks,
Cosmina

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42636.
