### ISSUE TITLE
[Event Request] Codeunit 9988 "Word Template Impl." - Procedure GetMergeFieldsForRecord - OnBeforeAddFieldToMergeFields

### ISSUE THREAD

**Issue by cscheidsteff** [microsoft/ALAppExtensions#18777]
Please add an Event OnBeforeAddFieldToMergeFields in Procedure GetMergeFieldsForRecord in Codeunit 9988 "Word Template Impl."

    local procedure GetMergeFieldsForRecord(TableId: Integer; var MailMergeFields: List of [Text]; PrependValue: Text)
    var
        FieldRec: Record Field;
        MailMergeFieldsCount: Dictionary of [Text, Integer];
        Counter: Integer;
        AppendValue: Text;
        IsHandled: Boolean;
    begin
        FieldRec.SetRange(TableNo, TableId);
        FieldRec.SetFilter(Class, '<>%1', FieldRec.Class::FlowFilter);
        FieldRec.SetFilter(Type, '<>%1&<>%2&<>%3&<>%4&<>%5', FieldRec.Type::BLOB,
                                                             FieldRec.Type::Media,
                                                             FieldRec.Type::MediaSet,
                                                             FieldRec.Type::RecordID,
                                                             FieldRec.Type::TableFilter);
        if FieldRec.FindSet() then
            repeat
                AppendValue := GetAppendValue(FieldRec."Field Caption", Counter, MailMergeFieldsCount);
                IsHandled := false;
                OnBeforeAddFieldToMergeFields(MergeFields, FieldRec, PrependValue, AppendValue, IsHandled);
                if not IsHandled then
                    MailMergeFields.Add(StrSubstNo(MergeFieldTok, PrependValue, FieldRec."Field Caption", AppendValue));
            until FieldRec.Next() = 0;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAddFieldToMergeFields(var MergeFields: List of [Text]; FieldRec: Record Field; PrependValue: Text; AppendValue: Text; var IsHandled: Boolean)
    begin
    end;

**Comment by mazhelez** [comment]
@cscheidsteff we apologize for the late response. When requesting events in _System Application_, please mention a proper justification. Why is the event needed there? What is the exact scenario you try to cover?

Very often there are cleaner way of achieving the same outcome without using an event.

Looking forward to hearing from you!

**Comment by cscheidsteff** [comment]
In the current implementation of the function GetMergeFieldsForRecord() all fields of a table are passed to the Word template or the DataSource.xlsx file. Since we often need fields from up to 10 tables in our templates, the assignment of the fields in Word - both via the menu and the list - quickly becomes very inconvenient. Also, there is a limit of 255 items in the mail merge field menu in Microsoft Word, which is also quickly reached. On the other hand, we actually only ever need a certain selection of fields from a respective table. The event we requested would give us the possibility to control which fields are actually passed to the template. I hope I could explain our request. If there is a better alternative from your point of view, please let us know.

Looking forward to hearing from you!

**Comment by darjoo** [comment]
@cscheidsteff I was informed by the team that we have bigger work planned for this in the upcoming release. For selecting the specific fields for mailmerge, via UI and through an API/Event. I'll be linking this to that work-item internally and closing this.

**Comment by cscheidsteff** [comment]
> @cscheidsteff I was informed by the team that we have bigger work planned for this in the upcoming release. For selecting the specific fields for mailmerge, via UI and through an API/Event. I'll be linking this to that work-item internally and closing this.

ok - thx

**Comment by cscheidsteff** [comment]
@darjoo ok - thx
