### ISSUE TITLE
[Event-Request] Table 5050 Contact function ActiveAltAddress

### ISSUE THREAD

**Issue by cosminah** [microsoft/ALAppExtensions#18787]
Hi,

We need a new event and cod implementation in function **ActiveAltAddress** from table Contact.

```
 // Start
        IsHandled := false;
        OnBeforeContAltAddrDateRange(Rec, ContactAltAddressCode, IsHandled);
        if IsHandled then
            exit(ContactAltAddressCode);
//Stop

ContAltAddrDateRange.SetCurrentKey("Contact No.", "Starting Date");
        ContAltAddrDateRange.SetRange("Contact No.", "No.");
        ContAltAddrDateRange.SetRange("Starting Date", 0D, ActiveDate);
...
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeContAltAddrDateRange(var Contact: Record Contact; var ContactAltAddressCode: Code[10]; var IsHandled: Boolean)
    begin
    end;
```

Thanks,
Cosmina

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42636.
