### ISSUE TITLE
[Access Request] report 297 "Batch Post Sales Invoices"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#18785]
Could you please change the access scope to protected for the following variables?
```al
var
    Text003: Label 'The exchange rate associated with the new posting date on the sales header will not apply to the sales lines.';
//+Change
protected var
    PostingDateReq: Date;
    ReplacePostingDate: Boolean;
    ReplaceDocumentDate: Boolean;
    CalcInvDisc: Boolean;
    PrintDoc: Boolean;
    [InDataSet]
    PrintDocVisible: Boolean;
//-Change
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42678.
