### ISSUE TITLE
[Bug] DE Translation error in Page 7011 Direct Unit Cost

### ISSUE THREAD

**Issue by LidaLidaLidaLidaLida** [microsoft/ALAppExtensions#18795]
![correct](https://user-images.githubusercontent.com/103051698/174828092-721c4d8e-8cd8-4d08-83c0-34df1d95a727.PNG)
![wrong](https://user-images.githubusercontent.com/103051698/174828119-a04bf7eb-406e-4710-a9bf-e007c3254720.PNG)

The German translation of the field "Direct Unit Cost" ist wrong in page 7011. It should be "EK-Preis" instead of "Einstandspreis". It is correct in page 7005.

**Comment by AlexanderYakunin** [comment]
Sorry, we are not able to fix translation bugs here, please report any issues you have via technical support.
