### ISSUE TITLE
Unable to request MS for Prepaid Support

### ISSUE THREAD

**Issue by anuj-inecta** [Microsoft/ALAppExtensions#1879]
Hi Team,

We are not able to add any prepaid ticket for support to MS from BC Admin Center.
As we have few issues related to OnPremise that we need to report to MS, how can we add request to MS for that. Do we need to purchase some service plan or is there any other way we can use for reporting OnPremise tickets to MS.

_(Ref. Case https://github.com/Microsoft/AL/issues/4780)_

Please Suggest.
Best Regards.

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/business/f/758)
[mibuso forum](https://forum.mibuso.com/categories/nav-three-tier)
[Dynamics User Group](https://dynamicsuser.net/nav/f/developers)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.

**Comment by anuj-inecta** [comment]
Thanks @JesperSchulz
