### ISSUE TITLE
[Event Request] Codeunit 6501 add parameter ItemTrackingSummaryForm on event OnAssistEditTrackingNoOnBeforeLookupMode

### ISSUE THREAD

**Issue by calliopedavidroldan** [microsoft/ALAppExtensions#18793]
Hi,

We need to add the parameter ItemTrackingSummaryForm on event OnAssistEditTrackingNoOnBeforeLookupMode on procedure AssistEditTrackingNo :

```
    [IntegrationEvent(false, false)]
    local procedure OnAssistEditTrackingNoOnBeforeLookupMode(var TempGlobalEntrySummary: Record "Entry Summary"; var TempTrackingSpecification: Record "Tracking Specification"; var ItemTrackingSummaryPage: Page "Item Tracking Summary")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42636.
