### ISSUE TITLE
Report Fixed Asset - Projected Value (5607) - sum is not correct

### ISSUE THREAD

**Issue by AndrejaBS** [microsoft/ALAppExtensions#18798]
Hello!

If I use report **Fixed Asset - Projected Value (5607)** as you can see on first image, is the sum correct? Always is shown the last amount from 12/31/2023.

![image](https://user-images.githubusercontent.com/107405911/174973463-829d7177-194a-4b95-8e40-2a0626c3df92.png)

![image](https://user-images.githubusercontent.com/107405911/174973093-42eea668-15d1-4607-961d-13abc9439809.png)

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot investigate or fix bugs reported in this forum. You should report hotfix requests via technical support, this way they will be fixed for reported version.
