### ISSUE TITLE
T39 - OnValidate Description: Add "if GUIALLOWED then" 

### ISSUE THREAD

**Issue by DennisReinecke** [microsoft/ALAppExtensions#188]
Please add a 
`if guiallowed then`
before
`IF CONFIRM(AnotherItemWithSameDescrQst,FALSE,Item."No.",Item.Description) THEN`
and
`IF CONFIRM(AnotherChargeItemWithSameDescQst,FALSE,ItemCharge."No.",ItemCharge.Description) THEN`
is called.

This is currently causing problems when trying to insert new purchase lines via webservice.

**Comment by ikoletic** [comment]
This has been resolved in April 2019 release of Business Central through implementation of Confirm Management Codeunit (Codeunit 27).

**Comment by kvmAlio** [comment]
This validation makes no sense at all any way, Is there any way to remoev it?

If I input an Item No, wy would the system suggest a different Item? This is just confusing users. It would make more sense if the validation was 

if (StrLen(Description) <= MaxStrLen(Item."No.")) and **("Item No." = '**') then // IF THE ITEM NO. IS EMPTY
