### ISSUE TITLE
[GlobalRequest] Table167 "Job".SetHideValidationDialog

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#18804]
//------------------------------------------------------------RemoveInternal:BEGIN
internal procedure SetHideValidationDialog(NewHideValidationDialog: Boolean)
procedure SetHideValidationDialog(NewHideValidationDialog: Boolean)
//------------------------------------------------------------RemoveInternal:END
begin
    HideValidationDialog := NewHideValidationDialog;
end;

**Comment by pri-kise** [comment]
Duplicate of https://github.com/microsoft/ALAppExtensions/issues/18367

**Comment by AlexanderYakunin** [comment]
Already done
