### ISSUE TITLE
[Event Request] Codeunit 90 - Purchase-Post - OnBeforeCheckPrepaymentAmount

### ISSUE THREAD

**Issue by epernst** [microsoft/ALAppExtensions#18802]
We need a new subscriber OnBeforeCheckPrepmtAmtToDeduct in function CreatePrepmtLines in Codeunit 90:
```
                repeat
                    if CompleteFunctionality then
                        if PurchHeader."Document Type" <> PurchHeader."Document Type"::Invoice then begin
                            if not PurchHeader.Receive and ("Qty. to Invoice" = Quantity - "Quantity Invoiced") then
                                if "Qty. Rcd. Not Invoiced" < "Qty. to Invoice" then
                                    Validate("Qty. to Invoice", "Qty. Rcd. Not Invoiced");
                            Fraction := ("Qty. to Invoice" + "Quantity Invoiced") / Quantity;

                            **OnBeforeCheckPrepaymentAmount(SalesHeader, TempPrepmtSalesLine, SkipPrepaymentAmountCheck);
                            if not SkipPrepaymentAmountCheck then**
                              if "Prepayment %" <> 100 then

```
New event:
```
    [Integration]
    LOCAL PROCEDURE OnBeforeCheckPrepaymentAmount@72000(SalesHeader@72000 : Record 36;VAR TempPrepmtSalesLine@72001 : TEMPORARY Record 37;VAR SkipPrepaymentAmountCheck@72002 : Boolean);
    BEGIN
    END;

```

This solution would solve our requirement, but a better solution might be to do it the way it is done in codeunit 80 (Sales-Post). Here the code starting with "if "Prepayment %" <> 100 then" has been refactored into a new function CheckPrepmtAmtToDeduct, which has an handle event, which also would solve our issue.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42698.
