### ISSUE TITLE
[Event Request] Table 77 "Report Selections" - OnBeforeCanSaveReportAsPDF

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#18814]
Please add the event OnBeforeCanSaveReportAsPDF() in Table 77 "Report Selections" like this:

```
local procedure CanSaveReportAsPDF(ReportId: Integer): Boolean
var
    DummyInStream: InStream;
    CanSaveAsPDF: Boolean;
    IsHandled: Boolean;
begin
    OnBeforeCanSaveReportAsPDF(ReportId, CanSaveAsPDF, IsHandled); // <-- new event
    if IsHandled then
        exit(CanSaveAsPDF);
    exit(Report.RdlcLayout(ReportId, DummyInStream) or Report.WordLayout(ReportId, DummyInStream));
end;
```
The new event:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeCanSaveReportAsPDF(ReportId: Integer; var CanSaveAsPDF: boolean; var IsHandled: Boolean);
begin
end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42716.
