### ISSUE TITLE
Bug regarding reservations and orderplanning

### ISSUE THREAD

**Issue by JohnFrostDP** [microsoft/ALAppExtensions#18815]
Hi guys,

I found out that the Order Planning was not showing some Sales Orders in the demand overview. These should be shown seeing that the need an purchase to meet demand. I am missing order SO177761, SO177763 and SO177764 in this example.

![image](https://user-images.githubusercontent.com/92578153/175261136-51750358-3da3-4a54-97bf-46572d1b557c.png)

I found out that during the calculation, it checks on the field "Planned" in the Sales Lines. A boolean field used to indicate is the outstanding quantity is met with reservation quantities. it uses a function in the Sales Line table to determine if it is planned, as seen below.

![image](https://user-images.githubusercontent.com/92578153/175261215-86d83621-b17e-49a8-9aee-ef70beb42e8e.png)

During the calculation of the "Order Planning" it passes codeunit 5520 "Get Unplanned Demand". This will only check Sales lines that are not planned. As seen in the screenshot below.

![image](https://user-images.githubusercontent.com/92578153/175261308-f70406ae-4f66-46e8-9404-0b898bf4444b.png)

The bug:
The field "Planned" is only changed in certain situations. The only times it executes the proces is when:

the salesline is initiated
the quantity field is validated
when the reservation screen is opened(page 498)
But oddly enough not when a reservation is canceled on page 497 "Reservation Entries". The field planned is unchanged because nothing triggers the function "UpdatePlanned" or initiates a Sales line modification in this case. But after using the action "reserve" on the sales lines (which starts procedure ShowReservation on the sales line table and opens page 498) . It suddenly updates again. The "planned" field is now correct again.

You can understand the impact of this bug. Orders are overseen, and this could lead to supply shortages/delays. The order planning overview is incompleet and incorrect. Please fix this in the base application. I can probably work around it by forcing the function after each reservation deletion, but it would be better if you make a fix in future versions seeming your order planning is untrustworthy at the moment.

**Comment by JohnFrostDP** [comment]
i moved this bug to this location form https://github.com/microsoft/AL/issues/7089

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42833.
