### ISSUE TITLE
Codeunit 7302 - WMS Management - OnBeforeCheckBlockedBin new event

### ISSUE THREAD

**Issue by DParkerRSM** [microsoft/ALAppExtensions#18813]
I am working on a project where I want to dynamically set if a bin in the warehouse is blocked based user defined rules. I would like an event added to the CheckBlockedBin function in the WMS Management codeunit 7302.

    local procedure CheckBlockedBin(LocationCode: Code[10]; BinCode: Code[20]; ItemNo: Code[20]; VariantCode: Code[10]; UnitOfMeasureCode: Code[10]; CheckInbound: Boolean)
    var
        BinContent: Record "Bin Content";
    //Add >>
        IsHandled: Boolean;
    //Add <<
    begin
    //Add >>
        OnBeforeCheckBlockedBin(LocationCode, BinCode, ItemNo, VariantCode, UnitOfMeasureCode, CheckInbound, IsHandled);
        If IsHandled then
            exit;
    //Add <<
        GetLocation(LocationCode);
        if Location."Directed Put-away and Pick" then
            if BinContent.Get(LocationCode, BinCode, ItemNo, VariantCode, UnitOfMeasureCode) then begin
                if (CheckInbound and
                    (BinContent."Block Movement" in [BinContent."Block Movement"::Inbound, BinContent."Block Movement"::All])) or
                   (not CheckInbound and
                    (BinContent."Block Movement" in [BinContent."Block Movement"::Outbound, BinContent."Block Movement"::All]))
                then
                    BinContent.FieldError("Block Movement");
            end else
                if Location."Bin Mandatory" then begin
                    GetBin(LocationCode, BinCode);
                    if (CheckInbound and (Bin."Block Movement" in [Bin."Block Movement"::Inbound, Bin."Block Movement"::All])) or
                       (not CheckInbound and (Bin."Block Movement" in [Bin."Block Movement"::Outbound, Bin."Block Movement"::All]))
                    then
                        Bin.FieldError("Block Movement");
                end;
    //Add >>
        OnAfterCheckBlockedBin(LocationCode, BinCode, ItemNo, VariantCode, UnitOfMeasureCode, CheckInbound);
    //Add <<
    end;

    //Add >>
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckBlockedBin(LocationCode: Code[10]; BinCode: Code[20]; ItemNo: Code[20]; VariantCode: Code[10]; UnitOfMeasureCode: Code[10]; CheckInbound: Boolean; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckBlockedBin(LocationCode: Code[10]; BinCode: Code[20]; ItemNo: Code[20]; VariantCode: Code[10]; UnitOfMeasureCode: Code[10]; CheckInbound: Boolean)
    begin
    end;
    //Add <<

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42716.
