### ISSUE TITLE
[Function request] 2502 "Extension Marketplace" - AddSearchText

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#18817]
To improve the onboarding experience and provide better tools to our marketing department, we would like to provide an 'in-app' experience to showcase our available apps from within BC. Recommended apps is too limited, but the 'Extension Marketplace' page seems to provide the needed experience.

Request is to be able to call the page with a predefined filter.

![image](https://user-images.githubusercontent.com/25268332/175277814-8599a0f6-26db-46c0-ad43-b1b26c0f3a26.png)

We think this can be easily achieved by changing the `MarketplaceUrl` from a local to global variable.

And provide an extra function to add a 'SearchText' when constructing the URL

```
procedure AddSearchText(SearchText: text)
    var
        SearchLbl: Label '&search=%1&page=1', locked = true
    begin        
        // Example
        // https://appsource.microsoft.com/embed/en-us/marketplace/apps?product=dynamics-365-business-central   &search=dynavision&page=1

        MarketplaceUrl := ExtensionMarketplace.GetMarketplaceEmbeddedUrl();
        If SearchText <> '' then 
            // possible URLEncode 'SearchText' ...
            MarketplaceUrl += strsubstno(SearchLbl, SearchText)        
    end;
```

Related #16241

---

- [ ] Reviewed / Found in latest BC version

**Comment by stkillen** [comment]
We'll ship a procedure:

`procedure SetSearchText(Text: Text)`

In a future minor.
