### ISSUE TITLE
[Access Request] page 190 "Incoming Documents" - RunIncomingDocumentMultiSelectAction

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#18825]
Could you please change the Access Scope of the procedure `RunIncomingDocumentMultiSelectAction` to **protected**?
```al
//-Change
//-local procedure RunIncomingDocumentMultiSelectAction(ActionName: Enum "Incoming Doc. Selection Action")
protected procedure RunIncomingDocumentMultiSelectAction(ActionName: Enum "Incoming Doc. Selection Action")
//-Change
var
    IncomingDocument: Record "Incoming Document";
    ReleaseIncomingDocument: Codeunit "Release Incoming Document";
begin
    if not AskUserPermission(ActionName) then
        exit;

    ...
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42916.
