### ISSUE TITLE
[Extensibilty Request] CheckList Assigment

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#18829]
Hi,

I have a task to add some standard checklist items to our Role Center.
For this task, the most suitable event was in the "Checklist Events" at call InitializeGuidedExperienceItems code, but it is not suitable, because it further processes the code that inserts checklist items for the "Business Manager Role Center" and thereby overrides the setting for my roles.
I need an event that will work after the creation of checklist items.
It would also be cool if there was a function in the Codeunit Checklist that allowed you to add Roles for existing checklist items.

**Comment by AlexanderYakunin** [comment]
Hello! Can you add more details about placement and definition of needed events?

**Comment by AlexanderYakunin** [comment]
Closing, no information provided
