### ISSUE TITLE
[Request For External] Page 6505 "Lot No. Information Card" - Protected variable 

### ISSUE THREAD

**Issue by nickgoddard777** [microsoft/ALAppExtensions#18828]
Can the TrackingSpec Global variable be converted into a protected variable?

```
protected var
    TrackingSpec: Record "Tracking Specification";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42916.
