### ISSUE TITLE
[Function-Request] Codeunit 10 Type Helper

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/ALAppExtensions#18839]
Please add overload for FormatDate procedure that accepts Format and CultureName similar to what FormatDateTime and FormatDecimal does.

**Comment by JesperSchulz** [comment]
Done. Will release with 22.3.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10890.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 57225.
