### ISSUE TITLE
[Request for External] Table 23 Function LookupFromLocation

### ISSUE THREAD

**Issue by jagbarcelo** [microsoft/ALAppExtensions#18833]
Please make Function LookupFromLocation in Table 23 "Requisition Line", externally available.

Related to https://github.com/microsoft/ALAppExtensions/issues/6247 with simmilar use cases.

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42916.
