### ISSUE TITLE
[Event-Request] Codeunit 1210 Payment Export Mgt

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/ALAppExtensions#18838]
Please add OnBefore events with IsHandled pattern to procedures FormatToText, CheckLength and ExportToFile

**Comment by gunnargestsson** [comment]
procedure ProcessColumnMapping(DataExch: Record "Data Exch."; RecRef: RecordRef; LineNo: Integer; DataExchLineDefCode: Code[20]; TableID: Integer)
    var
        DataExchDef: Record "Data Exch. Def";
        DataExchColumnDef: Record "Data Exch. Column Def";
        DataExchField: Record "Data Exch. Field";
        DataExchFieldMapping: Record "Data Exch. Field Mapping";
        StringConversionManagement: Codeunit StringConversionManagement;
        ValueAsDestType: Variant;
        FieldRef: FieldRef;
        ValueAsString: Text[250];
    begin
        if not DataExchDef.Get(DataExch."Data Exch. Def Code") then
            Error(FormatNotDefinedErr, DataExch."Data Exch. Def Code");

        PrepopulateColumns(DataExchDef, DataExchLineDefCode, DataExch."Entry No.", LineNo);

        DataExchFieldMapping.SetRange("Data Exch. Def Code", DataExchDef.Code);
        DataExchFieldMapping.SetRange("Data Exch. Line Def Code", DataExchLineDefCode);
        DataExchFieldMapping.SetRange("Table ID", TableID);
        DataExchFieldMapping.FindSet();

        repeat
            DataExchColumnDef.Get(DataExchDef.Code, DataExchLineDefCode, DataExchFieldMapping."Column No.");

            if DataExchFieldMapping."Use Default Value" then
                ValueAsString := DataExchFieldMapping."Default Value"
            else begin
                FieldRef := RecRef.Field(DataExchFieldMapping."Field ID");
                CheckOptional(DataExchFieldMapping.Optional, FieldRef);
                CastToDestinationType(ValueAsDestType, FieldRef.Value, DataExchColumnDef, DataExchFieldMapping.Multiplier);
                **IsHandled := false;
                OnBeforeFormatToText(ValueAsDestType, DataExchDef, DataExchColumnDef, IsHandled);
                if not IsHandled then
                    ValueAsString := FormatToText(ValueAsDestType, DataExchDef, DataExchColumnDef);**
                if DataExchColumnDef."Text Padding Required" and (DataExchColumnDef."Pad Character" <> '') then

**Comment by AlexanderYakunin** [comment]
Please provide event's definition for ExportToFile. Going forward we will not accept requests without events definitions.

**Comment by gunnargestsson** [comment]
` procedure ExportToFile(EntryNo: Integer)
    var
        DataExch: Record "Data Exch.";
        DataExchDef: Record "Data Exch. Def";
        DataExchField: Record "Data Exch. Field";
        IsHandled: Boolean;   // Added
    begin
        DataExch.Get(EntryNo);
        DataExchDef.Get(DataExch."Data Exch. Def Code");
        DataExchField.SetRange("Data Exch. No.", DataExch."Entry No.");

        OnBeforeExportToFile(DataExch, DataExchDef, DataExchField, IsHandled); // Added
        if IsHandled then exit;                                                // Added

        DataExchDef.TestField("Reading/Writing XMLport");
        if not SilentServerMode then
            XMLPORT.Run(DataExchDef."Reading/Writing XMLport", false, false, DataExchField)
        else
            ExportToServerTempFile(DataExchDef."Reading/Writing XMLport", DataExchField);

        DataExchField.DeleteAll();
        DataExch.Delete
    end;


    // Added -->

    [IntegrationEvent(false, false)]
    local procedure OnBeforeExportToFile(DataExch: Record "Data Exch."; DataExchDef: Record "Data Exch. Def"; DataExchField: Record "Data Exch. Field"; var IsHandled: Boolean)
    begin
    end;

// Added <--`
