### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnBeforeLookupPayToContactNo

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#18846]
Please add event OnBeforeLookupPayToContactNo in the table 38:

```
[IntegrationEvent(true, false)]
local procedure OnBeforeLookupPayToContactNo(var PurchaseHeader: Record "Purchase Header"; var xPurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
begin
end;
```

```
trigger OnLookup()
var
    Cont: Record Contact;
    ContBusinessRelation: Record "Contact Business Relation";
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeLookupPayToContactNo(Rec, xRec, IsHandled);
    if IsHandled then
        exit;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43300.
