### ISSUE TITLE
[Event Request] codeunit 5814 "Undo Return Shipment Line" -  OnBeforeCode

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#18845]
Could you please add the following event?
```al

local procedure "Code"()
var
    PostedWhseShptLine: Record "Posted Whse. Shipment Line";
    SalesLine: Record "Sales Line";
    Window: Dialog;
    ItemShptEntryNo: Integer;
    DocLineNo: Integer;
    PostedWhseShptLineFound: Boolean;
begin
    OnBeforeCode(ReturnShptLine, UndoPostingMgt); //NEW EVENT
    with ReturnShptLine do begin
        ...
end;
```
[IntegrationEvent(false, false)]
local procedure OnBeforeCode(var ReturnShipmentLine: Record "Return Shipment Line"; var UndoPostingMgt: Codeunit "Undo Posting Management")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42846.
