### ISSUE TITLE
[GlobalRequest] Table 31008 "Purch. Adv. Letter Header CZZ".CreateDim

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#18869]
Please change CreateDim function from local procedure to global.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 19.

Build ID to track: 44198.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 44197.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44181.
