### ISSUE TITLE
[Request-For-External] codeunit 99000854 "Inventory Profile Offsetting" - TransferReqLineToInvProfiles

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18880]
Hello, we need the following currently internal procedure to be set to external. Can you please check this? Thank you!

[Request-For-External] Codeunit 99000854 "Inventory Profile Offsetting" - procedure from local to global

```
procedure TransferReqLineToInvProfiles(var InventoryProfile: Record "Inventory Profile"; var TransferReqLine: Record "Requisition Line")
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42916.
