### ISSUE TITLE
[Event Parameter] table 1003 "Job Planning Line" - OnBeforeUpdateReservation

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#18897]
I don't know how this could have happened, but I forgot a parameter in issue https://github.com/microsoft/ALAppExtensions/issues/16623

    procedure UpdateReservation(CalledByFieldNo: Integer)
    var
        ReservationCheckDateConfl: Codeunit "Reservation-Check Date Confl.";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        //OnBeforeUpdateReservation(Rec, xRec, CalledByFieldNo, IsHandled); A108F0000.Event20.02.o
        OnBeforeUpdateReservation(Rec, xRec, CalledByFieldNo, IsHandled, CurrFieldNo); //A108F0000.Event20.02.n
        if IsHandled then
            exit;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateReservation(var JobPlanningLine: Record "Job Planning Line"; var xJobPlanningLine: Record "Job Planning Line"; CalledByFieldNo: Integer; var IsHandled: Boolean; CurrentFieldNo: Integer)
    begin
        //A108F0000.Event20.02 Parameter CurrentFieldNo
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
