### ISSUE TITLE
[Event Parameter Change] Codeunit 99000854 - Inventory Profile Offsetting - procedure AllowScheduleOut - event OnAfterAllowScheduleOut

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18892]
We would like the parameter TempSKU added to the following event.

Codeunit 99000854 - Inventory Profile Offsetting - procedure AllowScheduleOut - event OnAfterAllowScheduleOut

Original:
```
OnAfterAllowScheduleOut(SupplyInvtProfile, TargetDate, CanReschedule);

[IntegrationEvent(false, false)]
local procedure OnAfterAllowScheduleOut(SupplyInvtProfile: Record "Inventory Profile"; TargetDate: Date; var CanReschedule: Boolean)
begin
end;
```

Change:
```
OnAfterAllowScheduleOut(SupplyInvtProfile, TargetDate, CanReschedule, TempSKU);

[IntegrationEvent(false, false)]
local procedure OnAfterAllowScheduleOut(SupplyInvtProfile: Record "Inventory Profile"; TargetDate: Date; var CanReschedule: Boolean; TempSKU: Record "Stockkeeping Unit") // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43085.
