### ISSUE TITLE
[Event Parameter Change] Codeunit 6620 - Copy Document Mgt. - procedure CopyArchSalesLine - Event OnCopyArchSalesLineOnAfterIncrementNextLineNo

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18890]
We would like the parameter ToSalesHeader added to the following event.

Codeunit 6620 - Copy Document Mgt. - procedure CopyArchSalesLine - Event OnCopyArchSalesLineOnAfterIncrementNextLineNo

Original:
```
OnCopyArchSalesLineOnAfterIncrementNextLineNo(ToSalesLine, FromSalesLineArchive, NextLineNo);

[IntegrationEvent(false, false)]
local procedure OnCopyArchSalesLineOnAfterIncrementNextLineNo(var ToSalesLine: Record "Sales Line"; var FromSalesLineArchive: Record "Sales Line Archive"; var NextLineNo: Integer)
begin
end;
```

Change:
```
OnCopyArchSalesLineOnAfterIncrementNextLineNo(ToSalesLine, FromSalesLineArchive, NextLineNo, ToSalesHeader);

[IntegrationEvent(false, false)]
local procedure OnCopyArchSalesLineOnAfterIncrementNextLineNo(var ToSalesLine: Record "Sales Line"; var FromSalesLineArchive: Record "Sales Line Archive"; var NextLineNo: Integer; ToSalesHeader: Record "Sales Header") // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 42843.
