### ISSUE TITLE
[Event Request] Table Segment Line function CreateSegLineInteractionFromContact

### ISSUE THREAD

**Issue by monicasuica** [microsoft/ALAppExtensions#18908]
Hello,

Is it possible to add a new event publisher in the function CreateSegLineInteractionFromContact?

```
 procedure CreateSegLineInteractionFromContact(var Contact: Record Contact)
    var
        IsHandled: Boolean;
    begin      
        IsHandled := false;
        OnBeforeCreateSegLineInteractionFromContact(Rec, Contact, IsHandled);
        if IsHandled then
            exit;        
	
	DeleteAll();
        Init();
     ....

  [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateSegLineInteractionFromContact(var SegmentLine: Record "Segment Line"; var Contact: Record Contact; var IsHandled: Boolean)
    begin
    end;
```
Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43300.
