### ISSUE TITLE
[Replace Option with Enum] page 42 "Sales Order" - BillToOptions

### ISSUE THREAD

**Issue by JulevG** [microsoft/ALAppExtensions#18903]
Could you please replace the Option BillToOptions with an enum

![Screenshot (50)](https://user-images.githubusercontent.com/108284620/175966860-c5a52c4a-c8b8-4337-86f1-c1ceabd090c5.png)
![Screenshot (51)](https://user-images.githubusercontent.com/108284620/175966877-b3b30f28-9abd-4894-862f-b9ce53cfbc5d.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43150.
