### ISSUE TITLE
[Event Request] Table 302 Finance Charge Memo Header

### ISSUE THREAD

**Issue by Zaynil** [microsoft/ALAppExtensions#18904]
In the OnDelete trigger of table 302 Finance Charge Memo Header, can we get a publisher to bypass the confirmation of printing the report. 

trigger OnDelete()
    var
        ConfirmManagement: Codeunit "Confirm Management";
    begin
        FinChrgMemoIssue.DeleteHeader(Rec, IssuedFinChrgMemoHdr);

        FinChrgMemoLine.SetRange("Finance Charge Memo No.", "No.");
        FinChrgMemoLine.DeleteAll();

        FinChrgMemoCommentLine.SetRange(Type, FinChrgMemoCommentLine.Type::"Finance Charge Memo");
        FinChrgMemoCommentLine.SetRange("No.", "No.");
        FinChrgMemoCommentLine.DeleteAll();

        if IssuedFinChrgMemoHdr."No." <> '' then begin
            Commit();
            //<<NEW PUBLISHER CODE
            OnDeleteBeforePrintReportConfirmation(Rec, IssuedFinChrgMemoHdr, IsHandled);
            if not IsHandled then
            //>>NEW PUBLISHER CODE
            if ConfirmManagement.GetResponse(
                 StrSubstNo(Text001, IssuedFinChrgMemoHdr."No."), true)
            then begin
                IssuedFinChrgMemoHdr.SetRecFilter;
                IssuedFinChrgMemoHdr.PrintRecords(true, false, false)
            end;
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43300.
