### ISSUE TITLE
[Event Request] Codeunit 7020 (Sales Line - Price) - OnAfterIsPriceUpdateNeeded

### ISSUE THREAD

**Issue by PunkyGP** [microsoft/ALAppExtensions#18916]
Dear Team,

can you please add a new Event to codeunit 7020 Sales Line - Price please?
We are currently working on making our product compatible with the new price feature.

But we are struggling with one issue.
In function 'IsPriceUpdateNeeded' there is a fixed check if the CalledByFieldNo isn't Quantity or Variant Code.
We would like to decide ourselves when the update needs to be done and then we like to have the following event.

    procedure IsPriceUpdateNeeded(AmountType: enum "Price Amount Type"; FoundPrice: Boolean; CalledByFieldNo: Integer) Result: Boolean;
    begin
        if FoundPrice then
            Result := true
        else
            Result :=
                Result or
                not (CalledByFieldNo in [SalesLine.FieldNo(Quantity), SalesLine.FieldNo("Variant Code")]);
        OnAfterIsPriceUpdateNeeded(AmountType, FoundPrice, CalledByFieldNo, Result);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterIsPriceUpdateNeeded(AmountType: Enum "Price Amount Type"; FoundPrice: Boolean; CalledByFieldNo: Integer; var Result: Boolean)
    begin
    end;

Thanks in advance,
Gunter

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43560.
