### ISSUE TITLE
[EVENT Change Request] report 5880 "Calc. Phys. Invt. Order Lines" -  OnCreateNewPhysInvtOrderLineOnAfterCalcQtyAndLastItemLedgExpected

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#18912]
Could you please include the sender on the event `OnCreateNewPhysInvtOrderLineOnAfterCalcQtyAndLastItemLedgExpected`
```al
//+Change
//-[IntegrationEvent(false, false)]
[IntegrationEvent(true , false)]
//-Change
local procedure OnCreateNewPhysInvtOrderLineOnAfterCalcQtyAndLastItemLedgExpected(QtyExpected: Decimal; LastItemLedgEntryNo: Integer; ItemLedgerEntry: Record "Item Ledger Entry"; PhysInvtOrderLine: Record "Phys. Invt. Order Line"; var InsertLine: Boolean; WarehouseEntry: Record "Warehouse Entry")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43300.
