### ISSUE TITLE
[Event Request] Reservation order depending on Availability Date

### ISSUE THREAD

**Issue by YannRobertCargo** [microsoft/ALAppExtensions#18918]
Hello,
We need to be able to change the reservation order depending on how close the Availability Date is.
To do so we would need the following :

The parameter AvailabilityDate to be passed into event OnAutoReserveOnBeforeSetValueArray so we could set a custom "ValueArrayNo" depending on the value of AvailabilityDate

Like so :

OnAutoReserveOnBeforeSetValueArray(ValueArrayNo,**AvailabilityDate**);

[IntegrationEvent(false, false)]
local procedure OnAutoReserveOnBeforeSetValueArray(var ValueArrayNo: Integer,**AvailabilityDate : Date**)
begin
end;

**Comment by tfbtrading** [comment]
So critical - we were trying to mimic Netsuite reservation / allocation strategy functionality (which is excellent) but ran into this issue with our own PTE. Prefer it is just implemented, but support this as a fix for customisations.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43428.
