### ISSUE TITLE
Visibility price type purchase fields on Price List Line Review page

### ISSUE THREAD

**Issue by RobertatK3** [microsoft/ALAppExtensions#18919]
I have extended the price type enum and run into al lot of fields which visibility are depending on a negative price type = sales condition causing me to modify the visibility for each of these fields.
For example field Direct Unit Cost which has the property Visible = PriceVisible and not IsSalesPrice;
Also for my new price type this condition is true, but of course I do not want to show the price type fields for purchase.
I would like to request a code change were the fields depending on price type = purchase are conditioned with IsPurchasePrice where IsPurchasePrice :=  PriceType = PriceType::Purchase;

**Comment by RobertatK3** [comment]
Any news on this request?

**Comment by AlexanderYakunin** [comment]
Sorry, we currently have no capacity for processing non-support related requests. If this is critical please create support ticket.

**Comment by RobertatK3** [comment]
> Sorry, we currently have no capacity for processing non-support related requests. If this is critical please create support ticket.

It is not critical, but this request is more then a year old!
You allow us to extend the price type enum, but everywhere Microsoft code is handling the price type as if there could only be two options. To overcome this we need to duplicate a lot of code and modify a lot of fields in extensions. I have asked for a small change. Other requests like event publishers I have asked for where added very quickly. What is the difference?

**Comment by RobertatK3** [comment]
@AlexanderYakunin Any news on this topic?

**Comment by AlexanderYakunin** [comment]
Please check the code, this is already fixed in May 2023, but due to issues with sync to GitHub this request is not closed yet. Closing now. Sorry for inconvenience.
