### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post subsitute GLAccount in CreatePrepaymentLines

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#18927]
Can you please provide a publisher that we can change the GL Account for the sales prepayment account. In our solution we have to get the GL Account base upon the VAT Posting Groups of the SalesLine.

    local procedure CreatePrepaymentLines(SalesHeader: Record "Sales Header"; CompleteFunctionality: Boolean)
    var
      ...
    begin
           ...
                    if "Prepmt Amt to Deduct" <> 0 then begin
                        if ("Gen. Bus. Posting Group" <> GenPostingSetup."Gen. Bus. Posting Group") or
                           ("Gen. Prod. Posting Group" <> GenPostingSetup."Gen. Prod. Posting Group")
                        then
                            GenPostingSetup.Get("Gen. Bus. Posting Group", "Gen. Prod. Posting Group");
                        GLAcc.Get(GenPostingSetup.GetSalesPrepmtAccount());
                        // -NewEvent
                        OnAfterGetSalesPrepmtAccount(GLAcc, TempSalesLine);
                        // +NewEvent
                        TempLineFound := false;
                        if SalesHeader."Compress Prepayment" then begin
                            TempPrepmtSalesLine.SetRange("No.", GLAcc."No.");
                            TempPrepmtSalesLine.SetRange("Dimension Set ID", "Dimension Set ID");
                            OnCreatePrepaymentLinesOnAfterTempPrepmtSalesLineSetFilters(TempPrepmtSalesLine, TempSalesLine);
                            TempLineFound := TempPrepmtSalesLine.FindFirst();
                        end;
                        if TempLineFound then begin

-----
Publisher signature

    // -NewEvent
    [IntegrationEvent(false, false)]
    local procedure OnAfterGetSalesPrepmtAccount(var GLAccount: Record "G/L Account"; TempSalesLine: Record "Sales Line" temporary)
    begin

    end;
    // +NewEvent

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43560.
