### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post in PostJobContractLine

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#18926]
In our solution we want to invoice from a sales order to a job (as we use the prepayment functionality, it is necessary to have document type order). 
Unfortunately, it is not possible for me to "navigate" around the Testfields in function PostJobContractLine as I want to use the default posting routine(s)
I have two alternative solutions, where you can help. Thanks a lot.
a) If you change the signature of this publisher ( SalesHeader to var)

    // -NewCode
    // [IntegrationEvent(false, false)]
    // local procedure OnBeforePostJobContractLine(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; var IsHandled: Boolean; var JobContractLine: Boolean)
    // begin
    // end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostJobContractLine(var SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; var IsHandled: Boolean; var JobContractLine: Boolean)
    begin
    end;
    // +NewCode

b) if you implement the following IsHandled pattern. I think it would be good if one can skip all testfields. I particulary have an issue with  Testfield("Job Contract Entry No",0)

    local procedure PostJobContractLine(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePostJobContractLine(SalesHeader, SalesLine, IsHandled, JobContractLine);

        if IsHandled then
            exit;

        if SalesLine."Job Contract Entry No." = 0 then
            exit;

        //-NewCode
        IsHandled := false;
        OnPostJobContractLineBeforeTestFields(SalesHeader, SalesLine,IsHandled);
        if not IsHandled then begin
            // +NewCode

            if (SalesHeader."Document Type" <> SalesHeader."Document Type"::Invoice) and (SalesHeader."Document Type" <> SalesHeader."Document Type"::"Credit Memo") then
                SalesLine.TestField("Job Contract Entry No.", 0);

            SalesLine.TestField("Job No.");
            SalesLine.TestField("Job Task No.");

            // -NewCode
        end;
        //+NewCode

        if SalesHeader."Document Type" = SalesHeader."Document Type"::Invoice then
            SalesLine."Document No." := SalesInvHeader."No.";
        if SalesHeader."Document Type" = SalesHeader."Document Type"::"Credit Memo" then
            SalesLine."Document No." := SalesCrMemoHeader."No.";
        JobContractLine := true;
        #if not CLEAN20
        if UseLegacyInvoicePosting() then
            JobPostLine.PostInvoiceContractLine(SalesHeader, SalesLine)
        else
        #endif
        InvoicePostingInterface.PrepareJobLine(SalesHeader, SalesLine, SalesLineACY);
    end;

-----
Publisher

    // -NewEvent
    [IntegrationEvent(false, false)]
    local procedure OnPostJobContractLineBeforeTestFields(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line",var IsHandled: Boolean)
    begin

    end;
    // +NewEvent

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43560.
