### ISSUE TITLE
[Event Change Request] Codeunit 5987 "Serv-Posting Journals Mgt." - OnBeforeCreateCarteraBills (Spanish localization)

### ISSUE THREAD

**Issue by juacefer** [microsoft/ALAppExtensions#18928]
We need a new modification in the event OnBeforeCreateCarteraBills

[IntegrationEvent(false, false)]
local procedure OnBeforeCreateCarteraBills(ServiceHeader : Record "Service Header";**VAR** CustLedgerEntry : Record "Cust. Ledger Entry";VAR TotalServiceLine : Record "Service Line")
begin
end;

We have a problem locating our customer entry. In the procedure CreateBills(var TotalServiceLine: Record "Service Line"; var Window: Dialog; GenJnlLineDocNo: Code[20]; the variable is initialized with CustLedgEntry.Find('+'). This returns ALL customer entries.

We need to be able to apply some filters in the CustLedgEntry variable in the OnBeforeCreateCarteraBills event in order to locate the correct customer entry corresponding to the invoice that we are posting.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44246.
