### ISSUE TITLE
[Function request] Page 7022 "Price Worksheet" - SetDefaults

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#18932]
Situation: I have a purchase price list X for '**vendor V00040**'.
With 'copy lines' on the price worksheet, I want to copy all price list lines from this purchase price list X into the price list worksheet. (ok)

However, when I manually add new lines to the price worksheet, the system takes the default values from the price worksheet, so new lines are inserted with **'All Vendors**'

![image](https://user-images.githubusercontent.com/25268332/176459670-466cb98b-ea6a-4289-87c3-7c173a642cf1.png)

Requested behavior:  I'd like to be able to **set the defaults via code**, so if the worksheet is called in the context of 'price list header X', that we can also change the worksheet defaults to those of **price list header X**.

Not really sure on how to achieve this or how it's designed to work, but my guess would be to be able to access `TempWorksheetPriceListHeader` by code.

Something similar to SetDefaults (from page 7021 "Suggest Price Lines") would probably provide a solution.

```
procedure SetDefaults(PriceListHeader: Record "Price List Header")
    begin
        TempWorksheetPriceListHeader := PriceListHeader;
        Defaults := GetDefaults();
    end;
```

TempWorksheetPriceListHeader

---

- [ ] Reviewed / Found in latest BC version

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43341.
