### ISSUE TITLE
[Event Request] - Codeunit 5750 Whse.-Create Source Document: OnBeforeCheckIfFromSalesLine2ShptLine

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#1893]
We need the following event with handled pattern to be able to do additional checks:
![image](https://user-images.githubusercontent.com/47382840/55310017-bcf04500-545f-11e9-8541-8a9ec6878c05.png)

**Comment by AlexanderYakunin** [comment]
No, this change limit use of event. You can use existing event if needed.

**Comment by JamesCarrSaunders** [comment]
this event would be helpful for us too. I need a way to interfere with creation of warehouse shipments.
