### ISSUE TITLE
Make local procedure AdjustAmount in Codeunit Price List Management global

### ISSUE THREAD

**Issue by RobertatK3** [microsoft/ALAppExtensions#18934]
I have extended the price list line with a new price field and want to include this field in the Copy Lines action from a price list. 
In the codeunit Price List Management there is an event publisher OnCopyLineOnAfterAdjustAmounts and I want to subscribe to this event and then for my new price field also call the AdjustAmount function to automatically convert the price to the currency from the price list.
Could you please make this a global function so I can call this?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43341.
