### ISSUE TITLE
Table 5077 Segment Line function ProcessPostponedAttachment

### ISSUE THREAD

**Issue by monicasuica** [microsoft/ALAppExtensions#18945]
Hi, 

Is it possible to make the function ProcessPostponedAttachment available for other objects?

Thank you?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43341.
