### ISSUE TITLE
[Enum Request] Report 5899 "Calculate Inventory Value Global Variable CalcBase  to Enum (Extensible)

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#18946]
Please change the Variable CalcBase to enum + change event(s):

Example:
procedure InsertItemJnlLine

```
"Applied Amount" := AppliedAmount;
 Insert;
// Start New Code
// OnAfterInsertItemJnlLine(ItemJnlLine, EntryType2, ItemNo2, VariantCode2, LocationCode2, Quantity2, Amount2, ApplyToEntry2, AppliedAmount);
OnAfterInsertItemJnlLine(ItemJnlLine, EntryType2, ItemNo2, VariantCode2, LocationCode2, Quantity2, Amount2, ApplyToEntry2, AppliedAmount,CalcBase: Enum CalcBase);
// Stop New Code
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43282.
