### ISSUE TITLE
[Bug] Sales and Purchase Orders - Comments line

### ISSUE THREAD

**Issue by agnieszkaszuflak** [microsoft/ALAppExtensions#18948]
Hi AL-Team,

There is an issue, that could be fixed in Business Central.

When user add new line on Purchase/Sales Order, with Type empty (Comment), when you  choose No. from the list, Location and Dates are automatically filled in, which is incorrect.
If user doesn't fill in No. from the list, Location and Dates are empty.

**Comment by AlexanderYakunin** [comment]
First of all, I'm not sure this is incorrect, we have this logic for long time. Anyway, please do not report functional bugs here, we have no possibility to address it here. We need technical support to analyze repro steps and create hotfix requests using right channel, to make sure this is fixed.
