### ISSUE TITLE
[Event Request] Page 96 "Sales Cr. Memo Subform" 

### ISSUE THREAD

**Issue by ValentinoEnz** [microsoft/ALAppExtensions#18942]
Hi there,

would it be possible to provide a new IntegrationEvent in Page 96 "Sales Cr. Memo Subform", upon invoking the method "QuantityOnAfterValidate", to then be able to subscribe to it and call page updates etc.
On other Subforms this is already implemented but it's missing on the Sales Credit Memo one.

**Event-Invokation:**
```al
protected procedure QuantityOnAfterValidate()
begin
    if Reserve = Reserve::Always then begin
        CurrPage.SaveRecord();
        AutoReserve();
    end;
    DeltaUpdateTotals();

    // -New Event
    OnAfterQuantityOnAfterValidate(Rec, xRec);
    // +New Event
end;
```

**Publisher Signature:**

```al
[IntegrationEvent(true, false)]
local procedure OnAfterQuantityOnAfterValidate(var SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line")
begin
end;
```

**Comment by AlexanderYakunin** [comment]
This is already done
