### ISSUE TITLE
[Event Request] Report 1002 Post Inventory Cost to G/L

### ISSUE THREAD

**Issue by DBiernat** [microsoft/ALAppExtensions#18944]
We need to prevent the output of skipped Value Entries under specific circumstances, because they are posted by our extension.
Therefore, I would like to request an event to be able to do this.

Data Item SkippedValueEntry

    trigger OnAfterGetRecord()
    TempValueEntry
        PreventOutput: Boolean;
    begin
        if TempValueEntry.Next() = 0 then
            Clear(TempValueEntry);

        // ++ New Code
        PreventOutput := false;
        OnPreventOutputOfSkippedValueEntry(TempValueEntry, PreventOutput);
        if (PreventOutput) then
            CurrReport.Skip();
        // -- New Code

        SetRange("Item No.", TempValueEntry."Item No.");
        SetRange("Entry No.", TempValueEntry."Entry No.");

        if Item.Get("Item No.") then;
        if "Expected Cost" then
            CostAmt := "Cost Amount (Expected)"
        else
            CostAmt := "Cost Amount (Actual)";
    end;

Event Definition

    [IntegrationEvent(false, false)]
    local procedure OnPreventOutputOfSkippedValueEntry(TempValueEntry: Record "Value Entry" temporary; var PreventOutput: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43560.
