### ISSUE TITLE
[Event Request] - Codeunit 5750 Whse.-Create Source Document: OnBeforeCheckIfSalesLine2ReceiptLine

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#1894]
We need the following event with handled pattern to be able to do additional checks:

![image](https://user-images.githubusercontent.com/47382840/55310089-e90bc600-545f-11e9-9447-6a9a5224e883.png)

**Comment by AlexanderYakunin** [comment]
No, this change limit use of event. You can use existing event if needed.

**Comment by AlexanderYakunin** [comment]
[External] CheckIfSalesLine2ReceiptLine(SalesLine : Record "Sales Line") : Boolean
IsHandled := FALSE;
ReturnValue := FALSE;
OnBeforeCheckIfSalesLine2ReceiptLine(SalesLine,ReturnValue,IsHandled);
IF IsHandled THEN
  EXIT(ReturnValue);
