### ISSUE TITLE
[Application] Avoid BlankDefaults on Price List pages?

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#18956]
In our scenario, users are creating / maintaining purchase price lists **per vendor**. 

When opening the purchase price lists page however, the assign-to type / assign-to fields are **blank** and do not contain the vendor info ... (??? confusing for the end user)

![image](https://user-images.githubusercontent.com/25268332/176669932-bf58238b-bac5-4402-85fa-cde090343ee2.png)

... although on the card page, the (_default_) fields are filled / available. 

![image](https://user-images.githubusercontent.com/25268332/176670061-0431afb2-8e85-4ed4-90ed-26cbfb5257dd.png)

This is confusing for the user.

Apparently, the fields shown in the purchase price lists page are not the actual / default fields, but calculated values. The reason why the fields are not shown are clear to us. It's due to the "Allow Update Defaults" setting on the price list. 

![image](https://user-images.githubusercontent.com/25268332/176670149-82f77af0-319f-42c3-b9e5-aa74c67b965f.png)

![image](https://user-images.githubusercontent.com/25268332/176670215-737209c2-4dac-4de6-b7df-1ca5174ae666.png)

We've enabled this setting to allow changes fields like "Price Including Tax", VAT Bus PG, ... but - in our case - not the vendor. 

What would be the best approach to still see the **actual** fields (instead of the CurrRec values) in the price list page? (**without** setting all standard CurrRec values to non-visible and introduce new page fields on the rec.values)

Suggestion: Add OnBeforeBlankDefaults with Handled pattern?

```
procedure BlankDefaults()
    var
        IsHandled: Boolean;
    begin
        OnBeforeBlankDefaults(Rec, IsHandled);
        if IsHandled then
            exit;
        
        if Rec."Allow Updating Defaults" then begin
            Rec."Source Type" := Rec."Source Type"::All;
            SetSourceNo('', '');
            Rec."Currency Code" := '';
            Rec."Starting Date" := 0D;
            Rec."Ending Date" := 0D;
        end;
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeBlankDefaults(var Rec: "Price List Header"; var IsHandled: Boolean)
    begin
    end;
```

---

- [ ] Reviewed / Found in latest BC version

**Comment by fvet** [comment]
Having an option that does not require custom coding / events would be even better. It's contra-intuitive to explain to a user that (seemingly the same) info on a list page does not match info from the underlying card page. This does not match the general list/card concept that is applied across all other entities in BC ...

**Comment by JakovljevicDusan** [comment]
Hi @fvet,

This behavior is going to be changed in the upcoming v22 and v23 minor releases, so values are no longer blanked: The same values set in card are shown in the list even when "Allow Update Defaults" = true.

Logic in previous behavior (that you reported) is that it shows default/blank values in the list of headers for the fields that might not have the same values in all lines. But, you are right, it was contra-intuitive to the user experience in other parts of the application and now it is "standardized".

Also, new events are introduced in places where BlankDefaults() was executed in Sales and Purchase price lists. So, in case someone needs it, it is possible to revert to previous logic via extensions.
