### ISSUE TITLE
[Code Change] - Codeunit 5750 Whse.-Create Source Document: CheckIfPurchLine2ReceiptLine

### ISSUE THREAD

**Issue by bcmako** [Microsoft/ALAppExtensions#1895]
Code change: the event should be called after InventoriableItem has been checked. Initialization of the local variables is needless.
![image](https://user-images.githubusercontent.com/47382840/55310225-37b96000-5460-11e9-9c7d-bd8e19a56b6b.png)

**Comment by AlexanderYakunin** [comment]
No, this change limit use of event. You can use existing event if needed.
