### ISSUE TITLE
Enum Request: Field(3; "Account Source"; Option) Table 363 "Analysis View"

### ISSUE THREAD

**Issue by Roberto-cyber** [microsoft/ALAppExtensions#18958]
We need the possibility to extend the option Field "Account Source" in Table 363 "Analysys View".

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43126.
