### ISSUE TITLE
[Event Request] page 26 "Vendor Card" - OnCreateVendorFromTemplateOnBeforeCurrPageUpdate

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#18965]
Can you add event OnCreateVendorFromTemplateOnBeforeCurrPageUpdatewith Rec as reference?
I have code that checks fields when the page is saved.
I don't want this check to run when using templates.
I have a Set-procedure in the vendor table to be able to prevent this code from running.
But the only events in this procedure (and other procedures called from this procedure before CurrPage.Update()) has Vendor as parameter.
When Copy(Vendor) is ran, the global variable is not transferred from Vendor to Rec.
Note: I have made three similar event requests. For Item, Customer and Vendor.

```
        if VendorTemplMgt.InsertVendorFromTemplate(Vendor) then begin
            VerifyVatRegNo(Vendor);
            Copy(Vendor);
            // >>>>>>>>>>>>>
            OnCreateVendorFromTemplateOnBeforeCurrPageUpdate(Rec);
            // <<<<<<<<<<<<<            
            CurrPage.Update();
        end else
            if VendorTemplMgt.TemplatesAreNotEmpty() then
                if not VendorTemplMgt.IsOpenBlankCardConfirmed() then
                    CurrPage.Close;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43428.
