### ISSUE TITLE
[Function Request] Page 511 Change Exchange Rate

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#18967]
Dear ALAppExtensions Team,
We would like to request the following global new procedure

    procedure GetCurrencyCode(): Code[10]
    begin
      exit(CurrencyCode);    
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43341.
