### ISSUE TITLE
[Event Request], [Code Change] - Codeunit 5750 Whse.-Create Source Document: CheckIfFromTransLine2ShptLine

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#1896]
Code Change: Calcfields should be done as late as possible.
New event to do additonal checks

![image](https://user-images.githubusercontent.com/47382840/55310300-67686800-5460-11e9-9bce-7c9263357e4c.png)

**Comment by AlexanderYakunin** [comment]
No, this change limit use of event. You can use existing event if needed.
