### ISSUE TITLE
[Event Request] codeunit 1336 "Item Templ. Mgt." - OnAfterCreateItemFromTemplate

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#18963]
Can you add event OnAfterCreateItemFromTemplate the same way it's done for customer and vendor..

```
        OnCreateItemFromTemplateOnBeforeSelectItemTemplate(Item, ItemTempl);
        if not SelectItemTemplate(ItemTempl) then
            exit(false);

        Item.Init();
        InitItemNo(Item, ItemTempl);
        Item.Insert(true);

        ApplyItemTemplate(Item, ItemTempl, true);

        // >>>>>>>>>>>>
        OnAfterCreateItemFromTemplate(Item, ItemTempl);
        // <<<<<<<<<<<<
        exit(true);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43428.
