### ISSUE TITLE
Codeunit 99000773 - Calculate Prod. Order - OnBeforeCalculate

### ISSUE THREAD

**Issue by DanielSmutek** [microsoft/ALAppExtensions#1897]
Hello,
please, we need to add a new Event or add SETRANGE to standard code:

Thank You!

1)
![1](https://user-images.githubusercontent.com/49072005/55310912-f2962d80-5461-11e9-8bda-2c0ec7c52442.png)

2)
![2](https://user-images.githubusercontent.com/49072005/55310989-325d1500-5462-11e9-9e11-d5f9e8c67cd1.jpg)

**Comment by JesperSchulz** [comment]
Is that an "either or"? Or "as well as"? Just to be sure.

**Comment by DanielSmutek** [comment]
"either or". The second one will be better.

**Comment by DanielSmutek** [comment]
Will this request be included in next release of Business Central? Thanks for answering! :-)

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
