### ISSUE TITLE
Type helper time zone conversion does not take daylight saving into account

### ISSUE THREAD

**Issue by PeterConijn** [microsoft/ALAppExtensions#18995]
The procedures GetTimeZoneOffset and GetTimeZoneUserOffset offsets do not allow for daylight saving time. 

![image](https://user-images.githubusercontent.com/47315514/176905185-49c4d390-7895-4ea4-8be1-6523b42da632.png)

This is because the conversion uses .BaseUtcOffset instead of .GetUtcOffset. 
![image](https://user-images.githubusercontent.com/47315514/176905337-3db27b44-12e9-475c-8f90-247a6019920b.png)

We need a procedure that calculates the correct offset based on a datetime argument like the example below:

![image](https://user-images.githubusercontent.com/47315514/176905886-548b6985-48ee-4820-aaca-b6831abc9ad9.png)

**Comment by JesperSchulz** [comment]
Looks like you're taking care of that issue by yourself now in PR #21246? 🥳 Should we close this issue then?

**Comment by PeterConijn** [comment]
We should. I have good hope the PR might be accepted.
