### ISSUE TITLE
[Event Parameter Change] Codeunit 76 "Purch.-Get Drop Shpt." - procedure Code - Event OnBeforeSalesLineModify

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#18990]
We would like the parameter SalesHeader added to the following events.

Codeunit 76 Purch.-Get Drop Shpt. - procedure Code - Event OnBeforeSalesLineModify

Original:

```
Codeunit 76 Purch.-Get Drop Shpt. - Procedure Code - Event OnBeforeSalesLineModify

[IntegrationEvent(false, false)]
    local procedure OnBeforeSalesLineModify(var SalesLine: Record "Sales Line"; PurchaseLine: Record "Purchase Line")
    begin
    end;
```

Change:

```
New Parameter SalesHeader

[IntegrationEvent(false, false)]
    local procedure OnBeforeSalesLineModify(var SalesLine: Record "Sales Line"; PurchaseLine: Record "Purchase Line"; SalesHeader: Record "Sales Header")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43428.
