### ISSUE TITLE
Table 36 and Codeunit 80 for our ISV solution

### ISSUE THREAD

**Issue by iuridavid** [Microsoft/ALAppExtensions#19]
We need one event on Table 36 and one event on Codeunit 80 for our ISV solution (in NAV 2018 that we will later move to BC)

Table 36:
[External] InitInsert()
We need an event OnBeforeInitRecord(Rec,xRec);
Just before InitRecord;
Print Below
![req](https://user-images.githubusercontent.com/32514408/46948828-3f827500-d077-11e8-902f-f8e69dbfff5c.png)

Codeunit 80:
We need an event on before FinalizePosting on Codeunit 80 Sales-Post

OnBeforeFinalizePosting(SalesHeader,SalesShptHeader,SalesInvHeader,SalesCrMemoHeader,ReturnRcptHeader,GenJnlPostLine);

We need to get some data before finalize posting in our solution.
Please check example of what we need to change bellow:

![codeunit 80 event request](https://user-images.githubusercontent.com/32514408/46948772-13ff8a80-d077-11e8-8ff6-0560e4568fd5.png)

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!

**Comment by iuridavid** [comment]
Thank you!
