### ISSUE TITLE
Change from html tables to csv in codeunit 5054

### ISSUE THREAD

**Issue by peterz84** [Microsoft/ALAppExtensions#190]
As suggested in issue #1057 switching from html tables to csv tables would take away the problem with the limitation of the number of fields (limitation of excel with html tables). 

This solution is described here: https://blogs.msdn.microsoft.com/freddyk/2009/09/20/word-management/

please implement this, because it is now possible to add fields with an extension because of the new codeevents in codeunit 5054.

**Comment by JesperSchulz** [comment]
After another round of triage, we'd like you to add this as an idea to our official ideas page for proper prioritization. Please log at http://aka.ms/bcideas.
