### ISSUE TITLE
[Event Parameter Change] Codeunit 99000809 "Planning Line Management" - procedure IsPlannedCompFound - Event OnAfterIsPlannedCompFound

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19000]
We would like the parameter SKU added to the following events.

Codeunit 99000809 Planning Line Management - procedure IsPlannedCompFound - Event OnAfterIsPlannedCompFound

Original:

```
Codeunit 99000809 - Planning Line Management - procedure IsPlannedCompFound - event OnAfterIsPlannedCompFound

OnAfterIsPlannedCompFound(PlanningComp, ProdBOMLine, IsFound);

[IntegrationEvent(false, false)]
local procedure OnAfterIsPlannedCompFound(PlanningComp: Record "Planning Component"; ProdBOMLine: Record "Production BOM Line"; var IsFound: Boolean)
begin
end;
```

Change:

```
OnAfterIsPlannedCompFound(PlanningComp, ProdBOMLine, IsFound, SKU);

[IntegrationEvent(false, false)]
local procedure OnAfterIsPlannedCompFound(PlanningComp: Record "Planning Component"; ProdBOMLine: Record "Production BOM Line"; var IsFound: Boolean; SKU: Record "Stockkeeping Unit") //<-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43428.
