### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - event OnBeforeCheckItemQuantityPurchCredit

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#19008]
Hello,

We would need an extra event in codeunit 90 "Purch.-Post" - OnBeforeCheckItemQuantityPurchCredit.
Before:
```
    local procedure CheckJobCreditPurchLine(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line")
    begin
        if PurchLine.IsCreditDocType then
            if (PurchLine."Job No." <> '') and (PurchLine.Type = PurchLine.Type::Item) and (PurchLine."Qty. to Invoice" <> 0) then 
                JobPostLine.CheckItemQuantityPurchCredit(PurchHeader, PurchLine);
    end;
```

Now, we would need an extra function and extra event to handle our code, as following:
New function CheckItemQuantityPurchCredit:

    local procedure CheckItemQuantityPurchCredit(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckItemQuantityPurchCredit(PurchHeader, PurchLine, IsHandled);
        if IsHandled then
            exit;

        if (PurchLine."Job No." <> '') and (PurchLine.Type = PurchLine.Type::Item) and (PurchLine."Qty. to Invoice" <> 0) then
            JobPostLine.CheckItemQuantityPurchCredit(PurchHeader, PurchLine);
    end;

Changes in the existing CheckJobCreditPurchLine function, to use the new function CheckItemQuantityPurchCredit:

    local procedure CheckJobCreditPurchLine(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line")
    begin
        if PurchLine.IsCreditDocType then
            CheckItemQuantityPurchCredit(PurchHeader, PurchLine);
    end;

New event:
This event needs to have the IncludeSender to true.
```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeCheckItemQuantityPurchCredit(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;
```

We would need these changes, as we have different condition to execute the line of code: JobPostLine.CheckItemQuantityPurchCredit(PurchHeader, PurchLine);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43560.
