### ISSUE TITLE
[Event Request] codeunit 4470 "Record Link Impl." - OnBeforeResetNotifyOnLinks

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#19009]
Can you add the following event to ResetNotifyOnLinks to be able to skip the reset.
I can see that there is already an event after the reset procedure is ran, but then I have to delete and copy them again, and I don't want to do that as the PK uses AutoIncrement.

```
    local procedure ResetNotifyOnLinks(RecVariant: Variant)
    var
        RecordLink: Record "Record Link";
        RecordRef: RecordRef;
        // >>>>>>>>>>>>
        IsHandled: Boolean;
        // <<<<<<<<<<<<
    begin
        // >>>>>>>>>>>>
        RecordLinkManagement.OnBeforeResetNotifyOnLinks(RecVariant, IsHandled);
        if IsHandled then
            exit;
        // <<<<<<<<<<<<
        RecordRef.GetTable(RecVariant);
        RecordLink.SetRange("Record ID", RecordRef.RecordId());
        RecordLink.SetRange(Notify, true);
        if not RecordLink.IsEmpty() then
            RecordLink.ModifyAll(Notify, false);
    end;
```

**Comment by mazhelez** [comment]
@auzhhv Since `ResetNotifyOnLinks` is referenced only in `CopyLinks` how about a symmetrical event `OnBeforeCopyLinks(..., SkipReset)`?

Moreover, since the code is out here in the repo, how do you feel about implementing it yourself? Should be easy and definitely faster, and I will be here to help if needed!

**Comment by mazhelez** [comment]
> > @auzhhv Since `ResetNotifyOnLinks` is referenced only in `CopyLinks` how about a symmetrical event `OnBeforeCopyLinks(..., SkipReset)`?
> > Moreover, since the code is out here in the repo, how do you feel about implementing it yourself? Should be easy and definitely faster, and I will be here to help if needed!
> 
> That would work. How do I do that? Just make a pull request with the changes?

Yep, a PR in this repo would be great! Looking forward!

**Comment by JesperSchulz** [comment]
This one was actually processed 13-10-2022. Closing issue.
