### ISSUE TITLE
Protected var - Request table 11406 "Post Code Range"

### ISSUE THREAD

**Issue by DanielBalanCgk** [microsoft/ALAppExtensions#19006]
Hello,

We would like to request making the global variable "PostCode" protected from table 11406 "Post Code Range", so we can access it from a table extension, in order to set additional custom fields from "Post Code" table before inserting in it. (OnBeforeInsert)

![image](https://user-images.githubusercontent.com/40453475/176912248-db519f69-8d55-41fb-bf1e-4cb918b4e784.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43341.
