### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - event OnAfterPostPurchLine

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#19004]
Hello,

We would need some extra parameters on the existing event OnAfterPostPurchLine:

Current event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterPostPurchLine(var PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line"; CommitIsSupressed: Boolean)
    begin
    end;

New parameters on the event:
    [IntegrationEvent(false, false)]
    local procedure OnAfterPostPurchLine(var PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line"; CommitIsSupressed: Boolean; **TempInvoicePostBuffer: Record "Invoice Post. Buffer" temporary; GenJnlLineDocNo: Code[20]; GenJnlLineExtDocNo: Code[35]; SrcCode: Code[10]; PurchInvLine: Record "Purch. Inv. Line"; PurchInvHeader: Record "Purch. Inv. Header"; PurchCrMemoLine: Record "Purch. Cr. Memo Line"; PurchLineACY: Record "Purchase Line")**
    begin
    end;

We need these extra parameters as we need to perform extra checks and based on them, extra records are created in our specific tables containing information from these parameters.

**Comment by AlexanderYakunin** [comment]
Please explain why do you need this? Table Invoice Post. Buffer is already obsoleted, adding this table to event is just co create large issue for the next version.

**Comment by CameliaPopescu** [comment]
Hello,

From table "Invoice Post. Buffer" we need the field "G/L Account No." to fill it in in additional tables. Because TempInvoicePostBuffer is declared global and it is filled from different places, it is hard to identify which value is set on "G/L Account", at this moment before calling event OnAfterPostPurchLine. In our case, it would be enough only to have the field "G/L Account No." sent as parameter.

**Comment by CameliaPopescu** [comment]
We did find an alternative for using "G/L Account No." from TempInvoicePostBuffer, so we don't need anymore TempInvoicePostBuffer to be sent as parameter.
The new structure of the event should be:

```
[IntegrationEvent(false, false)]
local procedure OnAfterPostPurchLine(var PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line"; CommitIsSupressed: Boolean; GenJnlLineDocNo: Code[20]; GenJnlLineExtDocNo: Code[35]; SrcCode: Code[10]; PurchInvLine: Record "Purch. Inv. Line"; PurchInvHeader: Record "Purch. Inv. Header"; PurchCrMemoLine: Record "Purch. Cr. Memo Line"; PurchLineACY: Record "Purchase Line")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45169.
