### ISSUE TITLE
[Scope Change] codeunit 13 "Gen. Jnl.-Post Batch" - InsertPostedGenJnlLine

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#19014]
Please change the scope of `InsertPostedGenJnlLine` method to public in addition to #19013.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43341.
