### ISSUE TITLE
[Request-For-External] Codeunit 5407 "Prod. Order Status Management" - SetTimeAndQuantityOmItemJnlLine

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19019]
Hello, we need the following currently local procedure to be set as global. Can you please check this? Thank you!

[Request-For-External] Codeunit 5407 "Prod. Order Status Management" - procedure from local to global

```
procedure SetTimeAndQuantityOmItemJnlLine(var ItemJnlLine: Record "Item Journal Line"; ProdOrderRtngLine: Record "Prod. Order Routing Line"; OutputQtyBase: Decimal; OutputQty: Decimal; PutawayQtyBaseToCalc: Decimal)
```

**Comment by AlexanderYakunin** [comment]
This procedure is already global

**Comment by MH1612** [comment]
In BC20 CU02 it is Local:
local procedure SetTimeAndQuantityOmItemJnlLine(var ItemJnlLine: Record "Item Journal Line"; ProdOrderRtngLine: Record "Prod. Order Routing Line"; OutputQtyBase: Decimal; OutputQty: Decimal; PutawayQtyBaseToCalc: Decimal)

**Comment by AlexanderYakunin** [comment]
We only expose new external elements for Master, if you need this for PROD versions, it requires special effort

**Comment by MH1612** [comment]
That's ok for us for a future version.

**Comment by MH1612** [comment]
@AlexanderYakunin 
Can you open the ticket again or do I have to submit a new issue?

**Comment by AlexanderYakunin** [comment]
This is already global in master; this is future version v. 21. What else for this ticket?

**Comment by MH1612** [comment]
Ok Thanks
