### ISSUE TITLE
Please remove onPrem scope from ExcelBuffer procedure CreateValidationRule.

### ISSUE THREAD

**Issue by HendraSikmawan82** [microsoft/ALAppExtensions#19020]
Dear Developer.

Until Microsoft_Base Application_20.2.41144.43129 the  [Scope('OnPrem')] on ExcelBuffer table, procedure CreateValidationRule.
Is still there, can you please remove it?
I see on CreateRange is already removed.
I need it to export excel and make a drill down option.

Thank You.

**Comment by AlexanderYakunin** [comment]
Already done
