### ISSUE TITLE
[Request-For-External] Codeunit 90 "Purch.-Post" - DivideAmount

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19057]
Hello, we need the following currently local procedure to be set als global. Can you please check this? Thank you!

[Request-For-External] Codeunit 90 "Purch.-Post" - procedure DivideAmount from local to global

```
procedure DivideAmount(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; QtyType: Option General,Invoicing,Shipping; PurchLineQty: Decimal; var TempVATAmountLine: Record "VAT Amount Line" temporary; var TempVATAmountLineRemainder: Record "VAT Amount Line" temporary)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43341.
