### ISSUE TITLE
[Event Parameter Change] Codeunit 90 Purch.-Post - procedure PostItemTrackingForShipment - Event OnPostItemTrackingForShipmentOnAfterReturnShptLineReset

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19065]
We would like the parameters PurchLine, IsHandled added to the following events.

Codeunit 90 Purch.-Post - procedure PostItemTrackingForShipment - Event OnPostItemTrackingForShipmentOnAfterReturnShptLineReset

Original:

```
Codeunit 90 - Purch.-Post - procedure PostItemTrackingForShipment - event OnPostItemTrackingForShipmentOnAfterReturnShptLineReset

OnPostItemTrackingForShipmentOnAfterReturnShptLineReset(ReturnShptLine, PurchHeader);

[IntegrationEvent(false, false)]
local procedure OnPostItemTrackingForShipmentOnAfterReturnShptLineReset(var ReturnShptLine: Record "Return Shipment Line"; PurchHeader: Record "Purchase Header")
begin
end;
```

Change:

```
IsHandled := false; // <-- ADDED
OnPostItemTrackingForShipmentOnAfterReturnShptLineReset(ReturnShptLine, PurchHeader, PurchLine, IsHandled); // <-- ADDED
if IsHandled then // <-- ADDED
    exit; // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnPostItemTrackingForShipmentOnAfterReturnShptLineReset(var ReturnShptLine: Record "Return Shipment Line"; PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; var IsHandled: Boolean) // <-- ADDED
begin
end;
```

**Comment by AlexanderYakunin** [comment]
Please explain why do you need this? Do you need to replace this code by your own, skip it for some cases or change the condition then tracking should be posted? Depending on this we may have different implementation.

**Comment by MH1612** [comment]
We need to skip it. We transfer negative EK receipt lines to the credit memo. We only go through the functionality if Receipt No. Is blank and return shipment no. unequal blank

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44246.
