### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnAfterQtyToHandleOrInvoiceDifferFromQuantity

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#19078]
Apart from the standard fields "Qty. to Handle (Base)" and "Qty. to Invoice (Base)" we have added a field "Whse. Qty. to Handle (Base)" in our addon which needs to be treated the same way. We would like two new procedures added

QtyToHandleOrInvoiceDifferFromQuantity and 
OnAfterQtyToHandleOrInvoiceDifferFromQuantity

to accomodate our feature. 

Could you also fix a rather obvious bug in which somebody many many years ago copy pasted the TempItemTrackLineInsert code for the TempItemTrackLineModify loop but forgot to replace the variable name? That woul be very much appreciated as well.

    procedure WriteToDatabase()
        ...
            for ModifyLoop := 1 to 2 do begin
                if TempItemTrackLineModify.Find('-') then
                    repeat
                        if xTempTrackingSpecification.Get(TempItemTrackLineModify."Entry No.") then begin
                            // Process decreases before increases
                            OnWriteToDatabaseOnBeforeRegisterDecrease(TempItemTrackLineModify);
                            Decrease := (xTempTrackingSpecification."Quantity (Base)" > TempItemTrackLineModify."Quantity (Base)");
                            if ((ModifyLoop = 1) and Decrease) or ((ModifyLoop = 2) and not Decrease) then begin
                                i := i + 1;
                                if ShouldModifyTrackingSpecification(xTempTrackingSpecification, TempItemTrackLineModify) then begin
                                    RegisterChange(xTempTrackingSpecification, xTempTrackingSpecification, ChangeType::Delete, false);
                                    RegisterChange(TempItemTrackLineModify, TempItemTrackLineModify, ChangeType::Insert, false);
                                    //A109F0006.Event20.02.os
                                    //A108B0004 Wrong variable in the standard
                                    //if (TempItemTrackLineInsert."Quantity (Base)" <> TempItemTrackLineInsert."Qty. to Handle (Base)") or
                                    //   (TempItemTrackLineInsert."Quantity (Base)" <> TempItemTrackLineInsert."Qty. to Invoice (Base)")
                                    //then
                                    //  SetQtyToHandleAndInvoice(TempItemTrackLineInsert);
                                    //A109F0006.Event20.02.oe
                                    //A109F0006.Event20.02.ns
                                    if QtyToHandleOrInvoiceDifferFromQuantity(TempItemTrackLineModify) then
                                        SetQtyToHandleAndInvoice(TempItemTrackLineModify);
                                    //A109F0006.Event20.02.ne
                                end else begin
                                    RegisterChange(xTempTrackingSpecification, TempItemTrackLineModify, ChangeType::Modify, false);
                                    SetQtyToHandleAndInvoice(TempItemTrackLineModify);
                                end;
                                TempItemTrackLineModify.Delete();
        ...
            if TempItemTrackLineInsert.Find('-') then begin
                repeat
                    i := i + 1;
                    if i mod 100 = 0 then
                        Window.Update(2, Round(i / NoOfLines * 10000, 1));
                    if TempItemTrackLineModify.Get(TempItemTrackLineInsert."Entry No.") then
                        TempItemTrackLineInsert.TransferFields(TempItemTrackLineModify);
                    OnWriteToDatabaseOnBeforeRegisterInsert(TempItemTrackLineInsert);
                    if not RegisterChange(TempItemTrackLineInsert, TempItemTrackLineInsert, ChangeType::Insert, false) then
                        Error(Text005);
                    //A109F0006.Event20.02.os
                    //if (TempItemTrackLineInsert."Quantity (Base)" <> TempItemTrackLineInsert."Qty. to Handle (Base)") or
                    //   (TempItemTrackLineInsert."Quantity (Base)" <> TempItemTrackLineInsert."Qty. to Invoice (Base)")
                    //then
                    //A109F0006.Event20.02.oe
                    if QtyToHandleOrInvoiceDifferFromQuantity(TempItemTrackLineInsert) then //A109F0006.Event20.02.n
                        SetQtyToHandleAndInvoice(TempItemTrackLineInsert);
                until TempItemTrackLineInsert.Next() = 0;
                TempItemTrackLineInsert.DeleteAll();

    local procedure QtyToHandleOrInvoiceDifferFromQuantity(ItemTrackingLine: Record "Tracking Specification") HasChanged: Boolean
    begin
        //A109F0006.Event20.02.ns
        HasChanged :=
            (ItemTrackingLine."Quantity (Base)" <> ItemTrackingLine."Qty. to Handle (Base)") or
            (ItemTrackingLine."Quantity (Base)" <> ItemTrackingLine."Qty. to Invoice (Base)");

        OnAfterQtyToHandleOrInvoiceDifferFromQuantity(ItemTrackingLine, HasChanged);
        //A109F0006.Event20.02.ne
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterQtyToHandleOrInvoiceDifferFromQuantity(ItemTrackingLine: Record "Tracking Specification";  var HasChanged: Boolean)
    begin
        //A109F0006.Event20.02
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43611.
