### ISSUE TITLE
[Event Parameter Request] page 6510 "Item Tracking Lines" - OnCalculateSumsOnAfterCalcSums

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#19076]
procedure CalculateSums()
    var
        xTrackingSpec: Record "Tracking Specification";
    begin
        xTrackingSpec.Copy(Rec);
        Rec.Reset();
        Rec.CalcSums("Quantity (Base)", "Qty. to Handle (Base)", "Qty. to Invoice (Base)");
        //OnCalculateSumsOnAfterCalcSums(Rec); A200F0000.Event20.02.o
        OnCalculateSumsOnAfterCalcSums(Rec, SourceTrackingSpecification); //A200F0000.Event20.02.n
        TotalTrackingSpecification := Rec;
        Rec.Copy(xTrackingSpec);

        UpdateUndefinedQtyArray();
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCalculateSumsOnAfterCalcSums(var TrackingSpecification: Record "Tracking Specification"; SourceTrackingSpecification: Record "Tracking Specification")
    begin
        //A200F0000.Event20.02 Parameter SourceTrackingSpecification
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43611.
