### ISSUE TITLE
[Event Parameter Request] codeunit 900 "Assembly-Post" - OnBeforeInitPost

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#19072]
We had submitted a bug request through serviceshub (2204280010002036) because during the shipment posting of a sales order with assembly-to-order sales line(s) the "Posting Date" of the SalesHeader is not being respected: Looking at the code in C80:

            AsmPost.SetSuppressCommit(SuppressCommit);
            AsmPost.SetPostingDate(true, SalesHeader."Posting Date");
            AsmPost.InitPostATO(AsmHeader);

C900 should set the sales posting date but is not doing anything at all. The Microsoft Product manager said this is how the functionality is intended to work but was unable or unwilling to explain the SetPostingDate code. Our customers do not want the the warehouse shipment posting to fail because current AssemblyHeader "Posting Dates" are out of the inventory or accounting periodes or not in the posting range of the warehouse employees. So we are turning our attention to the willing ALAppExtenions people. Thanks in advance for your hard work.

    local procedure InitPost(var AssemblyHeader: Record "Assembly Header")
    var
        GenJnlCheckLine: Codeunit "Gen. Jnl.-Check Line";
        NoSeriesMgt: Codeunit NoSeriesManagement;
        GenJnlPostPreview: Codeunit "Gen. Jnl.-Post Preview";
    begin
        //OnBeforeInitPost(AssemblyHeader, SuppressCommit); A108B0099.Event20.02.o
        OnBeforeInitPost(AssemblyHeader, SuppressCommit, GenJnlPostPreview, PostingDate, PostingDateExists, ReplacePostingDate); //A108B0099.Event20.02.n

        with AssemblyHeader do begin

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitPost(var AssemblyHeader: Record "Assembly Header"; SuppressCommit: Boolean; var GenJnlPostPreview: Codeunit "Gen. Jnl.-Post Preview"; var PostingDate: Date; PostingDateExists: Boolean; ReplacePostingDate: Boolean)
    begin
        //A108B0099.Event20.02 Parameters
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44246.
