### ISSUE TITLE
Fallow-up #18674

### ISSUE THREAD

**Issue by cosminah** [microsoft/ALAppExtensions#19077]
Hi,

I understood that the code Delivered for https://github.com/microsoft/ALAppExtensions/issues/18674 will be :
 
procedure ChooseNewCustomerTemplate(): Code[20]
var
    CustTemplate: Record "Customer Templ.";
    ContBusRel: Record "Contact Business Relation";
    CustomerTemplMgt: Codeunit "Customer Templ. Mgt.";
    CustTemplateCode: Code[20];
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeChooseNewCustomerTemplate(Rec, CustTemplateCode, IsHandled);
    if IsHandled then
        exit(CustTemplateCode);

    CheckForExistingRelationships(ContBusRel."Link to Table"::Customer);
    ContBusRel.Reset();
    ContBusRel.SetRange("Contact No.", "No.");
    ContBusRel.SetRange("Link to Table", ContBusRel."Link to Table"::Customer);
    if ContBusRel.FindFirst() then
        Error(
          Text019,
          TableCaption, "No.", ContBusRel.TableCaption(), ContBusRel."Link to Table", ContBusRel."No.");

    OnChooseNewCustomerTemplateOnBeforeSelectWithConfirm(Rec, CustTemplate);

    if not HideValidationDialog then
        if Confirm(CreateCustomerFromContactQst, true) then begin
            CustTemplate.SetRange("Contact Type", Type);
            if CustomerTemplMgt.SelectCustomerTemplate(CustTemplate) then
                exit(CustTemplate.Code);

            Error(Text022);
        end;
end;

But for us the next lines are not enought :(

```
 if not HideValidationDialog then
        if Confirm(CreateCustomerFromContactQst, true) then begin
            CustTemplate.SetRange("Contact Type", Type);
            if CustomerTemplMgt.SelectCustomerTemplate(CustTemplate) then
                exit(CustTemplate.Code);

            Error(Text022);
        end;
```

we need :

```
 if Not HideValidationDialog then
            **if Not Confirm(CreateCustomerFromContactQst, true) then
                exit('');**

        CustTemplate.SetRange("Contact Type", Type);
        if CustomerTemplMgt.SelectCustomerTemplate(CustTemplate) then
            exit(CustTemplate.Code)
        else
            Error(Text022);
```

If the implementation cannot be as we request the code can be changed as fallow?

       ```
 // +
        OnChooseNewCustomerTemplateOnBeforeSelectWithConfirm(Rec, CustTemplate,**IsHandled**);
          **if IsHandled then // new code 
              exit(CustTemplate.Code);** // new code 

        if not HideValidationDialog then
            if Confirm(CreateCustomerFromContactQst, true) then begin
                CustTemplate.SetRange("Contact Type", Type);
                if CustomerTemplMgt.SelectCustomerTemplate(CustTemplate) then
                    exit(CustTemplate.Code);

                Error(Text022);
            end ;
        // -




```

**Comment by AlexanderYakunin** [comment]
Please explain the difference

**Comment by cosminah** [comment]
![image](https://user-images.githubusercontent.com/28861979/177481906-6e6bb5d1-e356-46ae-9e28-7e70260742a4.png)

**Comment by cosminah** [comment]
Is not the same:

We want next : 
If  HideValidationDialog then to open directly the Templates (no matter the Confirm)

In your code the Templates are open only if **not** HideValidationDialog.

**Comment by cosminah** [comment]
In your code the Templates are opened if **not** HideValidationDialog and if Confirm is Yes

We want to open them even **if HideValidationDialog**

**Comment by AlexanderYakunin** [comment]
Well, whatever you want, we are not doing this kind of changes via GitHub. It is either accepted as a bug which should be fixed for all, or this is breaking change in business logic, as you want to change the behavior and potentially break extensions and test automation. We already have OnBefore event here, use it to write your own business logic than.

**Comment by cosminah** [comment]
Ok thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43761.
