### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnSetQtyToHandleAndInvoiceOnAfterSetTrackingSpecificationFilters

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#19084]
local procedure SetQtyToHandleAndInvoice(TrackingSpecification: Record "Tracking Specification")
        ...
        if TrackingSpecification.TrackingExists() then begin
            ItemTrackingMgt.SetPointerFilter(TrackingSpecification);
            TrackingSpecification.SetTrackingFilterFromSpec(TrackingSpecification);
            OnSetQtyToHandleAndInvoiceOnAfterSetTrackingSpecificationFilters(TrackingSpecification, SourceTrackingSpecification); //A200F0000.Event20.02
            if TrackingSpecification.Find('-') then

    [IntegrationEvent(false, false)]
    local procedure OnSetQtyToHandleAndInvoiceOnAfterSetTrackingSpecificationFilters(var TrackingSpecification: Record "Tracking Specification"; SourceTrackingSpecification: Record "Tracking Specification")
    begin
        //A200F0000.Event20.02
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43611.
