### ISSUE TITLE
Follow-up for [Event Request] Sales Post - New event OnFillInvoicePostingBufferOnBeforeGetSalesAccount

### ISSUE THREAD

**Issue by alinat2022** [microsoft/ALAppExtensions#19086]
Hello,

Can you please let us know when [this event](https://github.com/microsoft/ALAppExtensions/issues/17286) will be introduced?

Thank you.

**Comment by alinat2022** [comment]
Kind reminder. Thank you.

**Comment by alinat2022** [comment]
Kind reminder. Thank you.

**Comment by AlexanderYakunin** [comment]
Hello! We cannot add this event, use this one from procedure GetSalesAccount instead

        IsHandled := false;
        OnBeforeGetSalesAccount(SalesLine, GenPostingSetup, SalesAccountNo, IsHandled);
        if not IsHandled then
