### ISSUE TITLE
[Event Parameter Request] page 6510 "Item Tracking Lines" - OnBeforeSetQtyToHandleAndInvoice

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#19088]
I am sorry I did not respond to request https://github.com/microsoft/ALAppExtensions/issues/13453 in a timely fashion. It took place during my holiday at the time.

I would like global variable TotalTrackingSpecification added to event OnBeforeSetQtyToHandleAndInvoice:

    local procedure SetQtyToHandleAndInvoice(TrackingSpecification: Record "Tracking Specification")
    var
        ReservEntry1: Record "Reservation Entry";
        TotalQtyToHandle: Decimal;
        TotalQtyToInvoice: Decimal;
        QtyToHandleThisLine: Decimal;
        QtyToInvoiceThisLine: Decimal;
        ModifyLine: Boolean;
    begin
        //OnBeforeSetQtyToHandleAndInvoice(TrackingSpecification, IsCorrection, CurrentSignFactor); A200F0000.Event20.02.o
        OnBeforeSetQtyToHandleAndInvoice(TrackingSpecification, IsCorrection, CurrentSignFactor, TotalTrackingSpecification); //A200F0000.Event20.02
        if IsCorrection then
            exit;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetQtyToHandleAndInvoice(var TrackingSpecification: record "Tracking Specification"; IsCorrection: Boolean; CurrentSignFactor: Integer; var TotalTrackingSpecification: record "Tracking Specification")
    begin
        //A200F0000.Event20.02 Parameter TotalTrackingSpecification
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43611.
