### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnRegisterItemTrackingLinesOnBeforeValidateExistingQuantityBase

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#19099]
To clarify this request: When an item tracking line already exists i.e. T337 record(s) exist then afterwards you might want to update certain secondary fields (Identified by procedure EntriesAreIdentical and parameter IdenticalArray[2]). We do not want to validate the Rec."Quantity (Base)" again when TempTrackingSpecification."Quantity (Base)" is zero in that case.

procedure RegisterItemTrackingLines(SourceTrackingSpecification: Record "Tracking Specification"; AvailabilityDate: Date; var TempTrackingSpecification: Record "Tracking Specification" temporary)
        ...
                if IsCorrection then begin
                    Rec."Quantity (Base)" += TempTrackingSpecification."Quantity (Base)";
                    Rec."Qty. to Handle (Base)" += TempTrackingSpecification."Qty. to Handle (Base)";
                    Rec."Qty. to Invoice (Base)" += TempTrackingSpecification."Qty. to Invoice (Base)";
                    //A200F0000.Event20.02.os
                    //end else
                    //    Rec.Validate("Quantity (Base)", "Quantity (Base)" + TempTrackingSpecification."Quantity (Base)");
                    //A200F0000.Event20.02.oe
                    //A200F0000.Event20.02.ns
                end else begin
                    IsHandled := false;
                    OnRegisterItemTrackingLinesOnBeforeValidateExistingQuantityBase(Rec, TempTrackingSpecification, CurrentRunMode, IsHandled);
                    if not IsHandled then
                        Rec.Validate("Quantity (Base)", "Quantity (Base)" + TempTrackingSpecification."Quantity (Base)");
                end;
                //A200F0000.Event20.02.ne

    [IntegrationEvent(false, false)]
    local procedure OnRegisterItemTrackingLinesOnBeforeValidateExistingQuantityBase(var TrackingSpecification: Record "Tracking Specification"; var TempTrackingSpecification: Record "Tracking Specification" temporary; CurrentRunMode: Enum "Item Tracking Run Mode"; var IsHandled: Boolean)
    begin
        //A200F0000.Event20.02
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43761.
