### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnRegisterItemTrackingLinesOnBeforeFind

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#19098]
procedure RegisterItemTrackingLines(SourceTrackingSpecification: Record "Tracking Specification"; AvailabilityDate: Date; var TempTrackingSpecification: Record "Tracking Specification" temporary)
        ...
        repeat
            SetTrackingFilterFromSpec(TempTrackingSpecification);
            OnRegisterItemTrackingLinesOnBeforeFind(Rec, TempTrackingSpecification, CurrentRunMode); //A200F0000.Event20.02
            if Find('-') then begin

    [IntegrationEvent(false, false)]
    local procedure OnRegisterItemTrackingLinesOnBeforeFind(var TrackingSpecification: Record "Tracking Specification"; var TempTrackingSpecification: Record "Tracking Specification" temporary; CurrentRunMode: Enum "Item Tracking Run Mode")
    begin
        //A200F0000.Event20.02
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43761.
