### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnAfterSetQtyToHandleAndInvoiceOnBeforeReservEntryModify

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#19091]
Request https://github.com/microsoft/ALAppExtensions/issues/13465 was not issued correctly to ALAppExtensions and a vital part is still missing because of that:

The newly created event OnAfterSetQtyToHandleAndInvoiceOnBeforeReservEntryModify from #13465 should also be added at another place as has already be correctly done with procedure OnSetQtyToHandleAndInvoiceOnBeforeReservEntryModify. It does require a bit of code change however:

New Code:

    local procedure SetQtyToHandleAndInvoice(TrackingSpecification: Record "Tracking Specification")
        ...
            //if ReservEntry1.Find('-') then A109F0006.Event20.02.o
            //A109F0006.Event20.02.ns
            if ReservEntry1.FindFirst() then begin
                ModifyLine := false;
                //A109F0006.Event20.02.ne
                if (ReservEntry1."Qty. to Handle (Base)" <> TotalQtyToHandle) or
                   (ReservEntry1."Qty. to Invoice (Base)" <> TotalQtyToInvoice) and not ReservEntry1.Correction
                then begin
                    ReservEntry1."Qty. to Handle (Base)" := TotalQtyToHandle;
                    ReservEntry1."Qty. to Invoice (Base)" := TotalQtyToInvoice;
                    OnSetQtyToHandleAndInvoiceOnBeforeReservEntryModify(ReservEntry1, TrackingSpecification);
                    //ReservEntry1.Modify(); A109F0006.Event20.02.o
                    ModifyLine := true;
                end;
                //A200F0000.Event20.02.ns
                OnAfterSetQtyToHandleAndInvoiceOnBeforeReservEntryModify(ReservEntry1, TrackingSpecification, TotalTrackingSpecification, ModifyLine);
                if ModifyLine then
                    ReservEntry1.Modify();
            end;
        //A200F0000.Event20.02.ne

Old Code:

    local procedure SetQtyToHandleAndInvoice(TrackingSpecification: Record "Tracking Specification")
        ...
            if ReservEntry1.Find('-') then
                if (ReservEntry1."Qty. to Handle (Base)" <> TotalQtyToHandle) or
                   (ReservEntry1."Qty. to Invoice (Base)" <> TotalQtyToInvoice) and not ReservEntry1.Correction
                then begin
                    ReservEntry1."Qty. to Handle (Base)" := TotalQtyToHandle;
                    ReservEntry1."Qty. to Invoice (Base)" := TotalQtyToInvoice;
                    OnSetQtyToHandleAndInvoiceOnBeforeReservEntryModify(ReservEntry1, TrackingSpecification);
                    ReservEntry1.Modify();
                end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43611.
