### ISSUE TITLE
[Event Request] Table 5050 Contact - trigger OnValidate Address

### ISSUE THREAD

**Issue by cosminah** [microsoft/ALAppExtensions#19093]
Hi,

We need the next code and event in table 5050 Contact, OnValidate of Address:

```
trigger OnValidate()
            begin
               OnBefoureFindStreetNameFromAddress(Rec, CurrFieldNo, IsHandled);// New code
                if IsHandled then;// New code
                    Exit; ;// New code

              PostCodeMgt.FindStreetNameFromAddress(Address, "Address 2", "Post Code", City, "Country/Region Code", "Phone No.", "Fax No.");
            end;
```

Thanks,
Cosmina

**Comment by cosminah** [comment]
Hi, 

Any news about this request ?

Thanks,
Cosmina

**Comment by AlexanderYakunin** [comment]
Please help us understand the purpose of this event? And we have different code in latest version, please check if you really need this event at all.

**Comment by cosminah** [comment]
Hi,

1. At validation of **Address** we have some custom code, for example to fill in a certain field.
2. We have for example a functionality to **SyncAddressWhenModifyContact**, this functionality should not trigger the code from OnValidate related to FindStreetNameFromAddress. (we want to copy the information) but we want to trigger the rest of the code from OnValidate.
3. We need that the code related to FindStreetNameFromAddress to be triggered just when is from user interface because from code we have other functionalities related to **Address**.

Thanks,
Cosmina

**Comment by AlexanderYakunin** [comment]
You can do all this by using embedded events available for any field validation - OnBeforeValidateEvent and OnAftervalidateEvent. Please also consider subscribers in PostCodeManagement codeunit in NL version.
