### ISSUE TITLE
[Event Request] Table 5050 Contact - trigger OnValidate "Post Code"

### ISSUE THREAD

**Issue by cosminah** [microsoft/ALAppExtensions#19095]
Hi,

Is possible to extend the existing event OnBeforeValidatePostCode from OnValidate of field "Post Code" with IsHandled parameter? 

```
                IsHandled := false; // New Code
                OnBeforeValidatePostCode(Rec, PostCode, IsHandled); // Extend Code
                if IsHandled then  // New Code
                    exit;  // New Code

                PostCode.ValidatePostCode(City, "Post Code", County, "Country/Region Code", (CurrFieldNo <> 0) and GuiAllowed);
                OnAfterValidatePostCode(Rec, xRec);
```

Thanks,
Cosmina

**Comment by cosminah** [comment]
Hi, 

Any news about this request ?

Thanks,
Cosmina

**Comment by AlexanderYakunin** [comment]
Please help us understand the purpose of this event? And we have different code in latest version, please check if you really need this event at all.

**Comment by cosminah** [comment]
Hi,

We need the functionality from **PostCode.ValidatePostCode** only when 
IF ("Country/Region Code" = '') OR ("Country/Region Code" = GLSetup."Landcode Nederland") 
else
we don't want the functionality from **ValidatePostCode**  to be applied.


Thanks,
Cosmina

**Comment by AlexanderYakunin** [comment]
You can do all this by using embedded events available for any field validation - OnBeforeValidateEvent and OnAftervalidateEvent. Please also consider subscribers in PostCodeManagement codeunit in NL version.
