### ISSUE TITLE
[Parameter Request] Codeunit 6500 "Item Tracking Management" OnAfterCreateLotInformation

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#19102]
Can we add Tracking Specification to OnAfterCreateLotInformation.  I asked for this in #12482 and says it was completed but it is still not there.  

procedure CreateLotNoInformation(TrackingSpecification: Record "Tracking Specification")
var
    LotNoInfo: Record "Lot No. Information";
    LotNumbers: List of [Code[50]];
    LotNumber: Code[50];
begin
    if TrackingSpecification."Lot No." <> '' then
        LotNumbers.Add(TrackingSpecification."Lot No.");

    if TrackingSpecification."New Lot No." <> '' then
        LotNumbers.Add(TrackingSpecification."New Lot No.");

    foreach LotNumber in LotNumbers do begin
        if not LotNoInfo.Get(TrackingSpecification."Item No.", TrackingSpecification."Variant Code", LotNumber) then begin
            LotNoInfo.Init();
            LotNoInfo.Validate("Item No.", TrackingSpecification."Item No.");
            LotNoInfo.Validate("Variant Code", TrackingSpecification."Variant Code");
            LotNoInfo.Validate("Lot No.", LotNumber);
            LotNoInfo.Insert(true);
            OnAfterCreateLotInformation(LotNoInfo, TrackingSpecification);   // New Parameter
        end;
    end;
end;

[IntegrationEvent(false, false)]
local procedure OnAfterCreateLotInformation(var LotNoInfo: Record "Lot No. Information"; TrackingSpecification: Record "Tracking Specification")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43611.
