### ISSUE TITLE
[Event Request] codeunit 444 "Purchase-Post Prepayments" OnBeforeFillInvLineBuffer

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#19108]
Can you please provide the same publisher as in in C442 Sales-Post Prepayment in FillInvLineBuffer.

    procedure FillInvLineBuffer(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; var PrepmtInvLineBuf: Record "Prepayment Inv. Line Buffer")
    begin
        with PrepmtInvLineBuf do begin
            Init;
            // -NewEvent
            OnBeforeFillInvLineBuffer(PrepmtInvLineBuf, PurchHeader, PurchLine);
            // +NewEvent        
            "G/L Account No." := GetPrepmtAccNo(PurchLine."Gen. Bus. Posting Group", PurchLine."Gen. Prod. Posting Group");

            if not PurchHeader."Compress Prepayment" then begin
                "Line No." := PurchLine."Line No.";
                Description := PurchLine.Description;
            end;

----
SIgnature

    //-NewEvent
    [IntegrationEvent(false, false)]
    local procedure OnBeforeFillInvLineBuffer(var PrepaymentInvLineBuffer: Record "Prepayment Inv. Line Buffer"; PurchaseHeader: Record "Purchase Header"; PurchaseLine: Record "Purchase Line")
    begin
    end;
    // +NewEvent

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43974.
