### ISSUE TITLE
[Extensibility Enhancement] Add Parameters QtyToBeInvoiced, var PurchInvHeader, var PurchCrMemoHeader, SrcCode to OnPostItemJnlLineJobConsumption

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/ALAppExtensions#19111]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44168.
