### ISSUE TITLE
[Event Request]  codeunit 444 "Purchase-Post Prepayments" include sender in OnBeforeInvoice,OnBeforeCreditMemo

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#19110]
Can you please include the sender in the following two events. I.E. we want to use the procedure SetSuppressCommit, which is currently only possible by exchanging the whole action in the document. I think those two publishers would be a greate place.

    // [IntegrationEvent(false, false)]
    [IntegrationEvent(true, false)]
    local procedure OnBeforeInvoice(var PurchaseHeader: Record "Purchase Header"; var Handled: Boolean)
    begin
    end;

    // [IntegrationEvent(false, false)]
    [IntegrationEvent(true, false)]
    local procedure OnBeforeCreditMemo(var PurchaseHeader: Record "Purchase Header"; var Handled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43974.
