### ISSUE TITLE
[Event Request] Table 27 "Item" - OnBeforeUpdateReplenishmentSystem

### ISSUE THREAD

**Issue by kwettermann** [microsoft/ALAppExtensions#19119]
Please add a new integration event **OnBeforeUpdateReplenishmentSystem** in **Table 27 "Item"**.

```
procedure UpdateReplenishmentSystem(): Boolean
var
+    IsHandled: Boolean;
begin
+    IsHandled := false;
+    OnBeforeUpdateReplenishmentSystem(Rec, IsHandled);
+    if IsHandled then
+        exit;
    
     CalcFields("Assembly BOM");

     [...]
end;
```

New integration event
```
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateReplenishmentSystem(var Item: Record Item; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43611.
