### ISSUE TITLE
[Event Request] Codeunit 22 add parameter AverageTransfer on event OnPostItemOnBeforeTransferReservFromJobPlanningLine

### ISSUE THREAD

**Issue by calliopedavidroldan** [microsoft/ALAppExtensions#19115]
Hi,

We need to add the parameter AverageTransfer  on event OnPostItemOnBeforeTransferReservFromJobPlanningLine on procedure PostItem :

   ```
 [IntegrationEvent(false, false)]
    local procedure OnPostItemOnBeforeTransferReservFromJobPlanningLine(var ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean; var AverageTransfer)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43974.
