### ISSUE TITLE
[Event Change Request] - ReservationManagement.Codeunit - OnBeforeDeleteReservEntries

### ISSUE THREAD

**Issue by acadonAG-dev** [microsoft/ALAppExtensions#19124]
We would like to request the following event change:
Object: ReservationManagement.Codeunit

Issue: The IsHandled variable is never used and it is not possible to handle the procedure.
Where is the event placed:
```al
procedure DeleteReservEntries(DeleteAll: Boolean; DownToQuantity: Decimal; var ReservEntry: Record "Reservation Entry")
var
    ...
    IsHandled: Boolean;
begin
    OnBeforeDeleteReservEntries(ReservEntry, DownToQuantity, CalcReservEntry, CalcReservEntry2, IsHandled);

    ReservEntry.SetRange("Reservation Status");
    if ReservEntry.IsEmpty() then
        exit;
    ...
end;
```
Event Code:
```al
[IntegrationEvent(false, false)]
local procedure OnBeforeDeleteReservEntries(var ReservationEntry: Record "Reservation Entry"; var DownToQuantity: Decimal; CalcReservEntry: Record "Reservation Entry"; var CalcReservEntry2: Record "Reservation Entry"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43611.
