### ISSUE TITLE
[Event Change Request] Table 5902 "Service Line" - procedure CheckIfCanBeModified() - OnBeforeCheckIfCanBeModified

### ISSUE THREAD

**Issue by juacefer** [microsoft/ALAppExtensions#19128]
We need the xRec variable to control some fields changes.

The new procedure

local procedure CheckIfCanBeModified()
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeCheckIfCanBeModified(Rec, **xRec**, IsHandled);
    if IsHandled then
        exit;

    if ("Appl.-to Service Entry" > 0) and ("Contract No." <> '') then
        Error(Text053);
end;

And the new event changed:

[IntegrationEvent(false, false)]
local procedure OnBeforeCheckIfCanBeModified(ServiceLine: Record "Service Line"; **var xServiceLine: Record "Service Line"**; var IsHandled: Boolean)
begin
end;

Best regards.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43974.
