### ISSUE TITLE
[Event Parameter Request] Codeunit 12 - Gen. Jnl.-Post Line - OnCodeOnBeforeFinishPosting

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#19120]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnCodeOnBeforeFinishPosting` in Codeunit 12 Gen. Jnl.-Post Line to be extended with parameter FirstEntryNo resulting in the following signature:
```al
    [IntegrationEvent(true, false)]
    // local procedure OnCodeOnBeforeFinishPosting(var GenJournalLine: Record "Gen. Journal Line"; Balancing: Boolean) //Old
    local procedure OnCodeOnBeforeFinishPosting(var GenJournalLine: Record "Gen. Journal Line"; Balancing: Boolean; FirstEntryNo: Integer) //New
    begin
    end;
```

which would be called as follows from `Code`:
```al
            CreateDeferralScheduleFromGL(GenJnlLine, Balancing);

            // OnCodeOnBeforeFinishPosting(GenJnlLine, Balancing); //Old
            OnCodeOnBeforeFinishPosting(GenJnlLine, Balancing, FirstEntryNo); //New

            IsTransactionConsistent := FinishPosting(GenJnlLine);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43974.
