### ISSUE TITLE
who wins when two extensions change the DrillDownPageId property of a table?

### ISSUE THREAD

**Issue by wgross92** [microsoft/ALAppExtensions#19132]
I have two extensions. Both change the DrillDownPageId property of the same table?
Who wins?

**Comment by Mike-1984** [comment]
The latter published extension wins

**Comment by JesperSchulz** [comment]
This repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps). For general questions, please use Viva Engage.
