### ISSUE TITLE
Question: If Basic Auth Will be deprecated, any way to connect ADCS with oAuth2.0 on SaaS Business Central?

### ISSUE THREAD

**Issue by diegomurillopkfattest** [microsoft/ALAppExtensions#19135]
We have a client that migrated from OnPremise to SaaS.
They use ADCS in their warehouses. For example, through Telnet the connection is made through the NAV Automate Data Capture System installation configuration file.
Currently this file is configured with basic authentication (user + apikey) pointing to the SaaS environment, and we would like to configure it through oAuth2.0

At the moment with basic authentication it works, but we would like to modify it to oAuth2.0 with connection token

![image](https://user-images.githubusercontent.com/108922163/177939164-25351278-8400-434d-a453-17368806cf1c.png)
![imagen](https://user-images.githubusercontent.com/108922163/177939463-47a2acf9-dbed-4dcb-b56a-96c207a6166d.png)
![image](https://user-images.githubusercontent.com/108922163/177939489-128ebcf3-4708-44f7-93e8-cbc03301f9f9.png)
![image](https://user-images.githubusercontent.com/108922163/177939515-4a5d73dd-f645-485c-b455-22a7cb467340.png)
![image](https://user-images.githubusercontent.com/108922163/177939555-11b77c23-24d7-4ed8-8452-40cf5c931935.png)
![image](https://user-images.githubusercontent.com/108922163/177939654-478429d7-4461-4604-8a43-f433e57ce910.png)

**Comment by JesperSchulz** [comment]
Issue probably outdated. If the issue persists, please use Viva Engage to ask such questions. 
This repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).
