### ISSUE TITLE
table 5401 "Item Variant" extend field Code from Code 10 to Code 20

### ISSUE THREAD

**Issue by GregorJacobsen** [microsoft/ALAppExtensions#19138]
In our product knkPublishing, we use the article variants to map various publisher-specific product variants and print runs. These are based on publisher-specific master data (and also on Business Central master data) whose code fields are 20 characters long and are filled via the number series, which returns codes up to 20 characters.
In the past we were able to customize the field in the Base App or in the C/AL objects, this possibility will disapear in the near future (and that is good per se), so it would be great if the code could be extended to 20 characters.

**Comment by AlexanderYakunin** [comment]
Hello! We are not allowed to change field length anymore; this is breaking change. We can only obsolete old field and replace it by new one. This is not an option for Variant Code, as this field is part of primary key in many tables, in this case we cannot make this change at all.
