### ISSUE TITLE
Problem in Profile/User Personalization  after changing page number in AL

### ISSUE THREAD

**Issue by rvveldhuyzen** [Microsoft/ALAppExtensions#1914]
In short: Profile record disappears from the list and user personalization after a Role Center page was renumbered.

I renumbered a Role Center page in AL that was already linked to a Profile(ECOM_ADMIN) and User personalization in BC from number X to Y.  For Business Central this will be seen as a delete?

After I published the app again the Web Client opens with an error: 
 
![image](https://user-images.githubusercontent.com/25078664/55404115-88f84b00-5557-11e9-87a8-51d439ae4191.png)

The second time it opens with the default Role Center

When I look in the profiles the ECOM_ADMIN profile is not present:
 
![image](https://user-images.githubusercontent.com/25078664/55404140-93b2e000-5557-11e9-9438-f90236e3e945.png)

But when I try to recreate the profile I get the following message(There is already a profile named ECOM_ADMIN):
 
![image](https://user-images.githubusercontent.com/25078664/55404157-9c0b1b00-5557-11e9-840e-933cd934afae.png)

Strange thing is that from the user personalization the Profile is visible and can also be selected without an error:
 
![image](https://user-images.githubusercontent.com/25078664/55404175-a1686580-5557-11e9-84a7-280c10efdf36.png)

![image](https://user-images.githubusercontent.com/25078664/55404194-a9c0a080-5557-11e9-8c25-e826694b72fb.png)
 
The biggest problem is I can’t delete or edit the profile.

BC Version:
![image](https://user-images.githubusercontent.com/25078664/55404208-b218db80-5557-11e9-9470-c8a421f3d8a9.png)

**Comment by JesperSchulz** [comment]
Nice catch! Let's get the issue to a team who will fix and backport it, as this repo only is for extensibility related issues in the upcoming release. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.
