### ISSUE TITLE
[Request for External] Report 5186 "Remove Contacts": Need to set ContactOK as protected var

### ISSUE THREAD

**Issue by Mahibabu1993** [microsoft/ALAppExtensions#19143]
Hi,

Is it possible to set the global variable ContactOK as protected var. We have codes that uses this variable and needs to be moved to report extension. It is already set to protected var for the report 5198 "Add Contacts". We need similar changes in Report 5186 "Remove Contacts"

```
protected var
        ContactOK: Boolean;
```

**Comment by AlexanderYakunin** [comment]
Already done
