### ISSUE TITLE
[Request for External] Table 81 Gen. Journal Line

### ISSUE THREAD

**Issue by WJMSmit** [microsoft/ALAppExtensions#19142]
In table 81 there are some procedures scoped as OnPrem, while they are, to my opinion, not OnPrem-specific.
We would like to request for external for at least the following procedure: "Lookup Applies-to Doc. No."

Thanks in advance!

**Comment by AlexanderYakunin** [comment]
Already done

**Comment by WJMSmit** [comment]
Good evening Alexander,

Is it possible to mention on which version this is implemented or mention where I can find such information?

Thanks in advance.

Kind regards,

Helmut Smit
________________________________
Van: Alexander Yakunin ***@***.***>
Verzonden: woensdag 13 juli 2022 12:25
Aan: microsoft/ALAppExtensions ***@***.***>
CC: ***@***.*** ***@***.***>; Author ***@***.***>
Onderwerp: Re: [microsoft/ALAppExtensions] [Request for External] Table 81 Gen. Journal Line (Issue #19142)


Already done
