### ISSUE TITLE
Event Request: Codeunit 1239, "XML Buffer Reader"

### ISSUE THREAD

**Issue by Roberto-cyber** [microsoft/ALAppExtensions#19157]
Hi,

We need the Event "OnBeforeAppendChild(var ChildElement, TempElementXMLBuffer)" in Codeunit 1239, local function "SaveChildElements"

if TempParentElementXMLBuffer.FindChildElements(TempElementXMLBuffer) then
            repeat
                if TempElementXMLBuffer.Namespace = '' then
                    NamespaceURI := DefaultNamespace
                else
                    NamespaceURI := TempParentElementXMLBuffer.GetNamespaceUriByPrefix(TempElementXMLBuffer.Namespace);
                ChildElement := XmlDocument.CreateElement(TempElementXMLBuffer.GetElementName, NamespaceURI);
                ElementValue := TempElementXMLBuffer.GetValue;
                if ElementValue <> '' then
                    ChildElement.InnerText := ElementValue;
                **OnBeforeAppendChild(var ChildElement, TempElementXMLBuffer)**
                XMLCurrElement.AppendChild(ChildElement);
                SaveProcessingInstructions(TempElementXMLBuffer, ChildElement, XmlDocument);
                SaveAttributes(TempElementXMLBuffer, ChildElement, XmlDocument);
                SaveChildElements(TempElementXMLBuffer, ChildElement, XmlDocument);
            until TempElementXMLBuffer.Next() = 0;

Thank you

**Comment by Vadim-Stepanenko** [comment]
We are not able to provide events with dotnet parameters, sorry. If you find a way for achieve the effect you want withour the dotnet params, feel free to create a new issue.
