### ISSUE TITLE
Enum Request: SalesDocumentNoIsVisible(DocType: Option Quote,"Order",Invoice,"Credit Memo","Blanket Order","Return Order",Reminder,FinChMemo) Codeunit 1400 "DocumentNoVisibility"

### ISSUE THREAD

**Issue by Roberto-cyber** [microsoft/ALAppExtensions#19156]
Hi,

We need the possibility to extend the parameter "DocType" in the "SalesDocumentNoIsVisible" function of the Codeunit 1400 "DocumentNoVisibility".

Thank you.

**Comment by AlexanderYakunin** [comment]
Hello! Do you plan to implement additional sales document type? Should we consider using enum "Sales Document Type" here in this case?

**Comment by Roberto-cyber** [comment]
Hi, 

We would like that the parameter "DocType" in the "SalesDocumentNoIsVisible" function to be an Enum and not an option, to avoid compatibility errors, passing a wrong enum, since option is marked as deprecated

thank you

**Comment by AlexanderYakunin** [comment]
No, this is not the case. Option data type is not deprecated. Both option and enum will continue. If this is the only purpose, no need to make this change
