### ISSUE TITLE
[Event Request] report 393 "Suggest Vendor Payments" - MakeGenJnlLine 

### ISSUE THREAD

**Issue by boych83** [microsoft/ALAppExtensions#19151]
Hello,

we need an additional event publisher so that we can update the SetOff amount (our field) in the "TempPaymentBuffer" record from the SetOff amount** (our field) in the "VendLedgEntry" record and update the amount in procedure InsertGenJournalLine()

**SetOff amout is FlowField which shows sum of all the issued SetOff document lines related to VendLedgEntry Entry No.

Currently we are using event sub.: 
- procedure OnUpdateTempBufferFromVendorLedgerEntry(var TempPaymentBuffer: Record "Payment Buffer" temporary; VendorLedgerEntry: Record "Vendor Ledger Entry")
- local procedure OnBeforeUpdateGnlJnlLineDimensionsFromTempBuffer(var GenJournalLine: Record "Gen. Journal Line"; TempPaymentBuffer: Record "Payment Buffer" temporary; SummarizePerVend: Boolean)

This two events are not sufficient, if report is using 'Summarize per Vendor' option from request page.

We would need additional event publisher inside procedure MakeGenJnlLine() (after line764)

```
  if SummarizePerVend then begin
      TempPaymentBuffer."Vendor Ledg. Entry No." := 0;
      TempPaymentBuffer."Applies-to Ext. Doc. No." := '';
      if TempPaymentBuffer.Find then begin
          TempPaymentBuffer.Amount := TempPaymentBuffer.Amount + PayableVendLedgEntry.Amount;
          
    --->  OnBeforeTempPaymentBufferModify(TempPaymentBuffer,VendLedgEntry)
         
          TempPaymentBuffer.Modify();
      end else begin
          TempPaymentBuffer."Document No." := NextDocNo;
          RunIncrementDocumentNo(true);
          TempPaymentBuffer.Amount := PayableVendLedgEntry.Amount;
          Window2.Update(1, VendLedgEntry."Vendor No.");
          
   --->   OnBeforeTempPaymentBufferInsert(TempPaymentBuffer,VendLedgEntry)

          TempPaymentBuffer.Insert();
      end;
      VendLedgEntry."Applies-to ID" := TempPaymentBuffer."Document No.";
  end else begin
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43974.
