### ISSUE TITLE
Enum Request: Field(1; "Type"; Option) Table 12170 "Payment Lines"

### ISSUE THREAD

**Issue by Roberto-cyber** [microsoft/ALAppExtensions#19155]
Hi,

We need the possibility to extend the option Field "Type" in Table 12170 "Payment Lines".

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
