### ISSUE TITLE
[Enum Request] Codeunit 99000813 "Carry Out Action" procedure CarryOutProdOrder - Option to Enum

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19168]
Can you please convert parameter ProdOrderChoice to enum? (enum 5526 "Planning Create Prod. Order")

```
procedure CarryOutProdOrder(ReqLine: Record "Requisition Line"; ProdOrderChoice: Option " ",Planned,"Firm Planned","Firm Planned & Print","Copy to Req. Wksh"; ProdWkshTempl: Code[10]; ProdWkshName: Code[10]): Boolean
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43878.
