### ISSUE TITLE
[Enum Request] Codeunit 5775 Whse. Management - Event OnAfterGetSourceDocument - Option to Enum

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19166]
Can you please convert the Parameter SourceDocument in the Event OnAfterGetSourceDocument from a Option to an extensible Enum? Or can you add a new Parameter with the Enum "Warehouse Journal Source Document"?

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterGetSourceDocument(SourceType: Integer; SourceSubtype: Integer; var SourceDocument: Option; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43878.
