### ISSUE TITLE
Job Queue rescheduling

### ISSUE THREAD

**Issue by JamesCarrSaunders** [Microsoft/ALAppExtensions#1916]
Hi 

The rescheduling time of a job queue entry is based upon CURRENTDATETIME. 

![image](https://user-images.githubusercontent.com/39410695/55414574-4a688d80-5563-11e9-96a8-00a5a0dcf7b0.png)

This means that if a job has a variable run time then it is not possible to reliably schedule a job to run - for example - every hour on the hour. 

We would like an option to reschedule based upon "Earliest Start Date/Time" instead. We understand that there is a danger of a job run duration being longer than the re-schedule time but we would consider this more akin to a setup error than a code fault. 

If it is not possible to provide this option then could we have an event publisher to allow us to have regularly recurring jobs?

thanks

**Comment by JesperSchulz** [comment]
Thanks for sharing your idea with us. We're always looking for better ways to do things. However, this isn't the right place to share it. You'll have better luck getting it implemented and noticed by other partners if you post it to the following resources:

- For functional improvements, go to [Business Central - Ideas](http://aka.ms/bcideas)
- For feature suggestions for the AL compiler and developer tools, visit [Github.com/Microsoft/AL](https://github.com/Microsoft/AL/issues)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
