### ISSUE TITLE
[Enum Request] Table 99000754 Work Center Option to Enum - procedure GetBinCode - Parameter Option to Enum

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19164]
Can you please convert the Parameter  FlushingMethod in the Function GetBinCode  from a Option to an extensible Enum?

```
    procedure GetBinCode(UseFlushingMethod: Boolean; FlushingMethod: Option Manual,Forward,Backward,"Pick + Forward","Pick + Backward"): Code[20]
```

```
    procedure GetBinCode(UseFlushingMethod: Boolean; FlushingMethod: Enum "Flushing Method"): Code[20]
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43878.
