### ISSUE TITLE
[Request-For-External] Codeunit 5830 "Calc. Availability Overview" - procedure InsertEntry

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19170]
Hello, we need the following currently local procedure to be set as global. Can you please check this? Thank you!

[Request-For-External] Codeunit 5830 "Calc. Availability Overview" - procedure from local to global
```
procedure InsertEntry(var AvailabilityCalcOverview: Record "Availability Calc. Overview"; NewType: Integer; NewDate: Date; NewLocation: Code[10]; NewVariantCode: Code[10]; NewQuantityBase: Decimal; NewReservQtyBase: Decimal; NewSourceType: Integer; NewSourceOrderStatus: Integer; NewSourceID: Code[20]; NewDescription: Text[100]; NewDemandType: Option)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43953.
