### ISSUE TITLE
[Event Request] report 12177 "Suggest Vendor Bills" - OnBeforeVendorBillLineInsert

### ISSUE THREAD

**Issue by matteodelgatto** [microsoft/ALAppExtensions#19175]
Hi,
we need a new event on report 12177 "Suggest Vendor Bills", procedure CreateLine()
We suggest to add the event OnBeforeVendorBillLineInsert as shown in the example 

procedure CreateLine()
    var
        DimMgt: Codeunit DimensionManagement;
        Dimension: Code[20];
        No: array[10] of Code[20];
        TableID: array[10] of Integer;
    begin
        VendBillLine2.Reset();
        VendBillLine2.SetRange("Vendor Entry No.", "Vendor Ledger Entry"."Entry No.");

        if not VendBillLine2.FindFirst() then begin
            VendBillLine2.Reset();
            VendBillLine2.SetRange("Vendor No.", "Vendor Ledger Entry"."Vendor No.");
            VendBillLine2.SetRange("Document No.", "Vendor Ledger Entry"."Document No.");
            VendBillLine2.SetRange("Document Occurrence", "Vendor Ledger Entry"."Document Occurrence");
            VendBillLine2.SetRange("Document Date", "Vendor Ledger Entry"."Document Date");
            if not VendBillLine2.FindFirst() then begin
                VendorBillLine.Init();
                VendorBillLine."Vendor Bill List No." := VendorBillHeader."No.";
                VendorBillLine."Line No." := NextLineNo;
                VendorBillLine."Vendor No." := "Vendor Ledger Entry"."Vendor No.";
                VendorBillLine."Vendor Bank Acc. No." := "Vendor Ledger Entry"."Recipient Bank Account";
                VendorBillLine."Document Type" := "Vendor Ledger Entry"."Document Type";
                VendorBillLine."Document No." := "Vendor Ledger Entry"."Document No.";
                VendorBillLine."Document Occurrence" := "Vendor Ledger Entry"."Document Occurrence";
                VendorBillLine."Document Date" := "Vendor Ledger Entry"."Document Date";
                VendorBillLine."External Document No." := "Vendor Ledger Entry"."External Document No.";
                VendorBillLine."Instalment Amount" := Abs("Vendor Ledger Entry".Amount);
                VendorBillLine."Remaining Amount" := Abs("Vendor Ledger Entry"."Remaining Amount");
                TableID[1] := DATABASE::Vendor;
                No[1] := "Vendor Ledger Entry"."Vendor No.";
                Dimension := '';
                VendorBillLine."Dimension Set ID" :=
                  DimMgt.GetDefaultDimID(
                    TableID, No, '', Dimension, Dimension, 0, 0);
                VendorBillLine."Gross Amount to Pay" := VendorBillLine."Remaining Amount";
                if VendorBillHeader."Posting Date" <= "Vendor Ledger Entry"."Pmt. Disc. Tolerance Date" then
                    VendorBillLine."Amount to Pay" :=
                      VendorBillLine."Remaining Amount" - Abs("Vendor Ledger Entry"."Remaining Pmt. Disc. Possible")
                else
                    VendorBillLine."Amount to Pay" := VendorBillLine."Remaining Amount";
                VendorBillLine."Due Date" := "Vendor Ledger Entry"."Due Date";
                VendorBillLine."Beneficiary Value Date" := VendorBillHeader."Beneficiary Value Date";
                VendorBillLine."Cumulative Transfers" := true;
                VendorBillLine."Vendor Entry No." := "Vendor Ledger Entry"."Entry No.";
                VendorBillLine."Reason Code" := VendorBillHeader."Reason Code";
                NextLineNo := NextLineNo + 10000;

                OnBeforeVendorBillLineInsert(VendorBillLine, VendorBillHeader, "Vendor Ledger Entry")

                VendorBillLine.Insert(true);
            end;
        end;
    end;

[IntegrationEvent(false,false)]
local procedure OnBeforeVendorBillLineInsert(var pVendorBillLine: Record "Vendor Bill Line"; pVendorBillHeader: Record "Vendor Bill Header"; pVendorLedgerEntry: Record "Vendor Ledger Entry")
begin
end;

Thank You

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44168.
