### ISSUE TITLE
[Extensibility Enhancements] Assembly Order part UpdatePropagation to Both

### ISSUE THREAD

**Issue by HansDutting** [microsoft/ALAppExtensions#19182]
Please add UpdatePropagation property = Both to Assembly Order in Part Lines

```al
            part(Lines; "Assembly Order Subform")
            {
                ApplicationArea = Assembly;
                Caption = 'Lines';
                SubPageLink = "Document Type" = FIELD("Document Type"),
                              "Document No." = FIELD("No.");
            }
```

This property is added to Sales Order, Service Order, Production Order, Transfer Order, etc..
Example from Sales Order:

```al
            part(SalesLines; "Sales Order Subform")
            {
                ApplicationArea = Basic, Suite;
                Editable = DynamicEditable;
                Enabled = "Sell-to Customer No." <> '';
                SubPageLink = "Document No." = FIELD("No.");
                UpdatePropagation = Both;
            }
```

While doing that set FIELD to field :) according to guidelines.

Greetings,
Hans Dütting

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46699.
