### ISSUE TITLE
[Event Change Request] Codeunit 12 "Gen. Jnl. Post Line" - Include Sender in OnBeforeCreateGLEntriesForTotalAmountsUnapplyVendorV19

### ISSUE THREAD

**Issue by andreilungu** [microsoft/ALAppExtensions#19184]
Please add IncludeSender = true for event:
`[IntegrationEvent(false, false)]
    local procedure OnBeforeCreateGLEntriesForTotalAmountsUnapplyVendorV19(DetailedVendorLedgEntry: Record "Detailed Vendor Ledg. Entry"; var VendorPostingGroup: Record "Vendor Posting Group"; GenJournalLine: Record "Gen. Journal Line"; var TempDimPostingBuffer: Record "Dimension Posting Buffer" temporary; var IsHandled: Boolean)
    begin
    end;`

the one for Customer has it already, not sure why is different for Vendor..:
`[IntegrationEvent(true, false)]
    local procedure OnBeforeCreateGLEntriesForTotalAmountsUnapplyV19(DetailedCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; var CustomerPostingGroup: Record "Customer Posting Group"; GenJournalLine: Record "Gen. Journal Line"; var TempIDimPostingBuffer: Record "Dimension Posting Buffer" temporary; var IsHandled: Boolean)
    begin
    end;`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44163.
