### ISSUE TITLE
[Exposure Request] Table 37 "Sales Line" - DeleteChargeChargeAssgnt

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19183]
Please change function DeleteChargeChargeAssgnt to protected function.

```
local procedure DeleteChargeChargeAssgnt
```

```
protected procedure DeleteChargeChargeAssgnt
```

**Comment by AlexanderYakunin** [comment]
Not found in Sales Header

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43953.
