### ISSUE TITLE
[Application Bug] table 5901 "Service Item Line" - OnBeforeEnsureCorrectStartingFinishingTimes

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#19189]
I guess the `IsHandled `parameter needs to be set by `var`?

**Bad code**

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeEnsureCorrectStartingFinishingTimes(var ServiceItemLine: Record "Service Item Line"; ServiceHeader: Record "Service Header"; Ishandled: Boolean)
    begin
    end;
```

**Good code**

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeEnsureCorrectStartingFinishingTimes(var ServiceItemLine: Record "Service Item Line"; ServiceHeader: Record "Service Header"; var Ishandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43872.
