### ISSUE TITLE
[DotNet extensibility] CellData.HyperLink

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#19198]
We've built an extension that is able to read / process complex Excel files, fully driven by **Excel buffer** only. 
The Excel files are received from external large international suppliers and are / can / should **not** be manipulated by any tools (Azure Functions / Power Automate / ...) before importing. Adding extra layers to the import stage to 'transform' Excel files adds extra costs (Azure) / complexity to deploy / maintenance / delay / ...

Goal is to be able to import excel **data** in BC without using external tools / extra archictecture. This works fine, except for cells containing a **hyperlink** (link to product catalog, manuals, images, ...). 

Our request is to be able to extract the **hyperlink** from a cell.

![image](https://user-images.githubusercontent.com/25268332/179218876-e0f05576-5406-46cb-89eb-510d309457eb.png)

We're not able to add this ourselves, since the dotnet CellData object is maintained by MS.

`"Microsoft.Dynamics.Nav.OpenXml.Spreadsheet.CellData"; "CellData"`

---

Idea would be to :

- Add new field to Excel Buffer table

```
field(x; "Hyperlink"; Text[1024])
        {
            Caption = 'Hyperlink';
            DataClassification = SystemMetadata;
        }

```

- Add new `Hyperlink` property to CellData

Value can be calculated probably using code below

```
If Cell.Hyperlinks.count Then
'Return the address if there is at least one cell selected
Hyperlink = Cell.Hyperlinks(1).Address
```

- Fill the Hyperlink value upon reading the Excel sheet (`ReadSheetContinous`)

```
if CellData.HasValue then begin
    Validate("Row No.", CellData.RowNumber);
    Validate("Column No.", CellData.ColumnNumber);
    ParseHyperLink(CellData.HyperLink); // <<<<
    ParseCellValue(CellData.Value, CellData.Format);
    Insert;
```

**Comment by JesperSchulz** [comment]
Would you want to do contribute this in the BaseApp contribution pilot?

**Comment by JesperSchulz** [comment]
Turns out, we cannot build this in the application alone :-( Unfortunately, we hence cannot process this as an extensibility request, as it requires changes to the platform too. Please create a BCIdea instead.
