### ISSUE TITLE
[Event Request] codeunit 130512 "Library - Purchase" - OnBeforeCreatePurchaseHeader

### ISSUE THREAD

**Issue by epernst** [microsoft/ALAppExtensions#19195]
We need a new event in codeunit 130512 "Library - Purchase" in the function **CreatePurchaseHeader**. 
The event should be called after Clear(PurchaseHeader) and have the same parameters as the existing OnAfterCreatePurchaseHeader.

```
   Clear(PurchaseHeader);
   OnBeforeCreatePurchaseHeader(PurchaseHeader, DocumentType.AsInteger(), BuyformVendorNo);
   PurchaseHeader.Validate("Document Type", DocumentType);
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreatePurchaseHeader(var PurchaseHeader: Record "Purchase Header"; DocumentType: Option; BuyfromPurchaseNo: Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44163.
