### ISSUE TITLE
[Event Request] Table 37 "Sales Line" - OnValidateLineAmountOnbeforeTestUnitPrice

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19197]
Please extend the Event OnValidateLineAmountOnbeforeTestUnitPrice with Parameter CurrentFieldNo.

```
[IntegrationEvent(false, false)]
local procedure OnValidateLineAmountOnbeforeTestUnitPrice(var SalesLine: Record "Sales Line"; CurrentFieldNo: Integer; var IsHandled: Boolean)
begin
end;
```

```
IsHandled := false;
OnValidateLineAmountOnbeforeTestUnitPrice(Rec, CurrFieldNo, IsHandled);
if not IsHandled then
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44163.
