### ISSUE TITLE
[Event Request] codeunit 130509 "Library - Sales" - OnBeforeCreateSalesHeader

### ISSUE THREAD

**Issue by epernst** [microsoft/ALAppExtensions#19194]
We need a new event in codeunit 130509 "Library - Sales" in the function **CreateSalesHeader**. 
The event should be called after Clear(SalesHeader) and have the same parameters as the existing OnAfterCreateSalesHeader.

```
   Clear(SalesHeader);
   OnBeforeCreateSalesHeader(SalesHeader, DocumentType.AsInteger(), SellToCustomerNo);
   SalesHeader.Validate("Document Type", DocumentType);
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateSalesHeader(var SalesHeader: Record "Sales Header"; DocumentType: Option; SellToCustomerNo: Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44163.
