### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnAfterRecreatePurchLines

### ISSUE THREAD

**Issue by epernst** [microsoft/ALAppExtensions#19196]
Please add a new event "OnAfterRecreatePurchLines" as the last line in function RecreatePurchLines in table 38. Event already exists for table 36.

    [IntegrationEvent(false, false)]
    local procedure OnAfterRecreatePurchaseLines(var PurchaseHeader: Record "Purchase Header"; ChangedFieldName: Text[100])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44163.
