### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnBeforePurchAndRCVATEntryInsert

### ISSUE THREAD

**Issue by matteodelgatto** [microsoft/ALAppExtensions#19193]
Hi,
we need a new event on codeunit 12 "Gen. Jnl.-Post Line", procedure InsertVAT()
We suggest to add the event OnBeforePurchAndRCVATEntryInsert as shown in the example

procedure InsertVAT(GenJnlLine: Record "Gen. Journal Line"; VATPostingSetup: Record "VAT Posting Setup"; GLEntryAmount: Decimal; GLEntryVATAmount: Decimal; GLEntryBaseAmount: Decimal; SrcCurrCode: Code[10]; SrcCurrGLEntryAmt: Decimal; SrcCurrGLEntryVATAmt: Decimal; SrcCurrGLEntryBaseAmt: Decimal)

...

                if (VATEntry.Type = VATEntry.Type::Purchase) and
                   (VATEntry."VAT Calculation Type" = VATEntry."VAT Calculation Type"::"Reverse Charge VAT")
                then begin
                    if UnrealizedVAT then
                        Error(
                          Text1130021,
                          VATPostingSetup.FieldCaption("VAT Calculation Type"), VATPostingSetup."VAT Calculation Type",
                          VATEntry.FieldCaption(Type), VATEntry.Type);
                    VATEntry2 := VATEntry;
                    VATEntry."Entry No." := NextVATEntryNo;
                    VATEntry.Type := VATEntry.Type::Sale;
                    VATEntry."Reverse Sales VAT" := true;
                    VATEntry.Base := -(VATEntry.Base + VATEntry."Nondeductible Base");
                    VATEntry."Nondeductible Base" := 0;
                    VATEntry.Amount := -(VATEntry.Amount + VATEntry."Nondeductible Amount");
                    VATEntry."Nondeductible Amount" := 0;
                    VATEntry."Deductible %" := 100;
                    VATEntry."Additional-Currency Base" :=
                      -(VATEntry."Additional-Currency Base" + VATEntry."Add. Curr. Nondeductible Base");
                    VATEntry."Add. Curr. Nondeductible Base" := 0;
                    VATEntry."Additional-Currency Amount" :=
                      -(VATEntry."Additional-Currency Amount" + VATEntry."Add. Curr. Nondeductible Amt.");
                    VATEntry."Add. Curr. Nondeductible Amt." := 0;
                    if "VAT Calculation Type" = "VAT Calculation Type"::"Reverse Charge VAT" then
                        if ("Document Type" = "Document Type"::Invoice) and ("Reverse Sales VAT No." = '') then
                            if "Reverse Sales VAT No. Series" <> '' then begin
                                NoSeriesMgt.TestDateOrder("Reverse Sales VAT No. Series");
                                "Reverse Sales VAT No." := NoSeriesMgt.GetNextNo("Reverse Sales VAT No. Series", "Posting Date", true);
                            end;
                    if "Reverse Sales VAT No." <> '' then begin
                        VATEntry."Document No." := "Reverse Sales VAT No.";
                        VATEntry."No. Series" := "Reverse Sales VAT No. Series";
                    end;
                    CheckVATPlafond(VATEntry, true);
                    
                    **OnBeforePurchAndRCVATEntryInsert(VATEntry, GenJnlLine)**

                    VATEntry.Insert(true);
                    VATEntry."Tax Liable" := true;
                    NextVATEntryNo := NextVATEntryNo + 1;
                    InsertVATBookEntry(VATEntry);
                    VATEntry := VATEntry2;
                end;
            end;

...

end;
[IntegrationEvent(false,false)]
local procedure OnBeforePurchAndRCVATEntryInsert(var pVATEntry: Record "VAT Entry"; pGenJnlLine: Record "Gen. Journal Line")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.
