### ISSUE TITLE
[Extensibility Bug] table 37 "Sales Line" ShowItemSub

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#19203]
Right now the procedure `SalesCheckIfAnyExtText` is always called if a user opens the Item Substitutions.
Even if the Item isn't changed the Attached Text Lines, are regnerated. 
For our customers this is an error, since the don't select any substition, and the Text lines are newly created anyways.

```al
procedure ShowItemSub()
var
    IsHandled: Boolean;
    //+Change
    SaveSalesLine: Record "Sales Line";
    //-Change
begin
    IsHandled := false;
    OnBeforeShowItemSub(Rec, IsHandled);
    if IsHandled then
        exit;

    Clear(SalesHeader);
    TestStatusOpen();
    //+Change
    SaveSalesLine := Rec;
    //-Change
    ItemSubstitutionMgt.ItemSubstGet(Rec);
    //+Change
    if (SalesLine."No." <> SaveSalesLine."No.") or (SalesLine."Variant Code" <> SaveSalesLine."Variant Code") then            
    //-Change
        if TransferExtendedText.SalesCheckIfAnyExtText(Rec, false) then
            TransferExtendedText.InsertSalesExtText(Rec);

    OnAfterShowItemSub(Rec);
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46699.
