### ISSUE TITLE
[Request-For-External] Codeunit 442 "Sales-Post Prepayments" - procedure ApplyFilter

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#19211]
Hello, we need the following currently local procedure to be set to global. Can you please check this? Thank you!

[Request-For-External] Codeunit 442 "Sales-Post Prepayments" - procedure from local to global

```
procedure ApplyFilter(SalesHeader: Record "Sales Header"; DocumentType: Option Invoice,"Credit Memo",Statistic; var SalesLine: Record "Sales Line")
```

**Comment by AlexanderYakunin** [comment]
Already done
