### ISSUE TITLE
[Request for External] Page 344 "Navigate" - Protected variables

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#19215]
Hello, we need the following currently global variable/-s to be set as protected. Can you please check this? Thank you!

```
protected var
        SalesShptHeader: Record "Sales Shipment Header";
        SalesInvHeader: Record "Sales Invoice Header";
        ReturnRcptHeader: Record "Return Receipt Header";
        SalesCrMemoHeader: Record "Sales Cr.Memo Header";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44906.
