### ISSUE TITLE
[Request-For-External] page 99000811 "Prod. BOM Where-Used" - BuildForm

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#19220]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

[Request-For-External] page 99000811 "Prod. BOM Where-Used" - Procedure from Internal to Global

```
local procedure BuildForm()
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43953.
