### ISSUE TITLE
[Request-For-External] Codeunit 22 "Item Jnl.-Post Line" - Procedure InitItemLedgEntry

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#19223]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

[Request-For-External] Codeunit 22 "Item Jnl.-Post Line" - Procedure from Internal to Global

```
procedure InitItemLedgEntry(var ItemLedgEntry: Record "Item Ledger Entry")
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 43953.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
