### ISSUE TITLE
[Event-Request] Table 37 "Sales Line" - OnBeforeAssignGLAccountValues

### ISSUE THREAD

**Issue by JerryTyssen** [microsoft/ALAppExtensions#19237]
Hello,

We would like to request the addition of the event OnCopyFromGLAccountOnBeforeTestDirectPosting(SalesLine, GLAccount, SalesHeader, IsHandled) in procedure CopyFromGLAccount() in Table 37 "Sales Line": (Just like is present in CopyFromResource())

```
local procedure CopyFromGLAccount()
++ var
        ++ IsHandled: Boolean;
    begin
        GLAcc.Get("No.");
        GLAcc.CheckGLAcc;
        ++ IsHandled := false;
        ++ OnCopyFromGLAccountOnBeforeTestDirectPosting(Rec, GLAcc, SalesHeader, IsHandled);
        ++ if not "System-Created Entry" and not IsHandled then
            GLAcc.TestField("Direct Posting", true);
        Description := GLAcc.Name;
        "Gen. Prod. Posting Group" := GLAcc."Gen. Prod. Posting Group";
        "VAT Prod. Posting Group" := GLAcc."VAT Prod. Posting Group";
        "Tax Group Code" := GLAcc."Tax Group Code";
        "Allow Invoice Disc." := false;
        "Allow Item Charge Assignment" := false;
        InitDeferralCode();
        OnAfterAssignGLAccountValues(Rec, GLAcc, SalesHeader);
    end;
```

```
[IntegrationEvent(false, false)]
    local procedure OnCopyFromGLAccountOnBeforeTestDirectPosting(var SalesLine: Record "Sales Line"; GLAccount: Record "G/L Account"; SalesHeader: Record "Sales Header", var IsHandled: Boolean)
    begin
    end;
```

Background: we have a custom field on the Sales Line that we use as an additional check before the TestField on GLAcc."Direct Posting".

Thanks in advance,
Jerry Tyssen
Cegeka

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44163.
