### ISSUE TITLE
[EventRequest] Codeunit 90 - OnBeforeRun

### ISSUE THREAD

**Issue by horstoeko** [microsoft/ALAppExtensions#19231]
Hi, We need a new event in code unit 90 with which we can implement additional checks and, if necessary, prevent further execution of the code:

```al
trigger OnRun()
var
    ....
    ShouldNotRun: Boolean;
begin
    OnBeforeRun(Rec, SuppressCommit, PreviewMode, HideProgressWindow, ShouldNotRun);
    if ShouldNotRun then
        exit;
    OnBeforePostPurchaseDoc(Rec, SuppressCommit, PreviewMode, HideProgressWindow);
    ....
end;
```

The new event should look like this:

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeRun(var PurchaseHeader: Record "Purchase Header"; var PreviewMode: Boolean; var CommitIsSupressed: Boolean; var HideProgressWindow: Boolean; var ShouldNotRun: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44168.
