### ISSUE TITLE
[EventRequest] Codeunit 80 - OnBeforeRun

### ISSUE THREAD

**Issue by horstoeko** [microsoft/ALAppExtensions#19232]
Hi, We need a new event in codeunit 80 with which we can implement additional checks and, if necessary, prevent further execution of the code:

```al
trigger OnRun()
var
    ....
    ShouldNotRun: Boolean;
begin
    OnBeforeRun(Rec, SuppressCommit, PreviewMode, HideProgressWindow, ShouldNotRun);
    if ShouldNotRun then
        exit;
    OnBeforePostSalesDoc(Rec, SuppressCommit, PreviewMode, HideProgressWindow);
    ....
end;
```

The new event should look like this:

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeRun(var SalesHeader: Record "Sales Header"; var PreviewMode: Boolean; var CommitIsSupressed: Boolean; var HideProgressWindow: Boolean; var ShouldNotRun: Boolean)
begin
end;
```

**Comment by AlexanderYakunin** [comment]
We already have this event

        IsHandled := false;
        OnBeforePostSalesDoc(Rec, SuppressCommit, PreviewMode, HideProgressWindow, IsHandled);
        if IsHandled then
            exit;

**Comment by horstoeko** [comment]
Hi @AlexanderYakunin,

Thank you very much for your answer. I have taken a look at the codebase of NAV19 CU8 and higher versions. Unfortunately, I can't find the customisation you describe. In which cumulative update will this adaptation be delivered?

**Comment by AlexanderYakunin** [comment]
You should use preview build for v.21 or August CU for v.20. We do not implement events in v.19 since April release.
