### ISSUE TITLE
[Event Request] pageextension 3997 "Reten. Pol. Setup Lines Ext." - OnSetIsDocumentArchiveTable

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#19238]
Please add new event (somewhere - not final solution):
```al
  internal procedure SetIsDocumentArchiveTable(TableId: Integer)
  begin
     IsDocumentArchiveTable := TableId in [Database::"Sales Header Archive", Database::"Purchase Header Archive"];
+    OnSetIsDocumentArchiveTable(TableId, IsDocumentArchiveTable);
   end;

+ [IntegrationEvent(false,false)]
+ local procedure OnSetIsDocumentArchiveTable(TableId: Integer; var IsArchiveTable:Boolean)
+ begin
+ end;
```

**Comment by grobyns** [comment]
@RadoArvay can you explain why you want to control the boolean?
This is only used to control whether "Keep last version" is enabled and that field is only used for the tables listed in SetIsDocumentArchiveTable.

**Comment by RadoArvay** [comment]
We have implemented a new functionality with an archive part so I want to use standard archive retention policy for our archive as well.

**Comment by grobyns** [comment]
The only thing this controls is the enabled property of the control. You can already access the "Keep Last Version" field and re-use the codeunit 3994 "Reten. Pol. Doc. Arch. Fltrng.".

I can make the variable IsDocumentArchiveTable protected so you can change its value in a page extension. You should of course take care not to explicitly set it to false in case someone else has already set it to true.

**Comment by RadoArvay** [comment]
Ok, but: `IsDocumentArchiveTable` is placed in MSFT pageextension, not page object. So, is it possible to make it `protected`? And access it in another pageextension?

**Comment by RadoArvay** [comment]
That is the reason I requested `event` instead of `protected var`. I was convinced it is impossible. But I do not remeber I have tested a situation.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46770.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 46777.
