### ISSUE TITLE
Follow up issue 16724

### ISSUE THREAD

**Issue by MirabelaRobu** [microsoft/ALAppExtensions#19235]
Hi, 

I created this issue several months ago and I see it is not implemented yet [https://github.com/microsoft/ALAppExtensions/issues/16724](https://github.com/microsoft/ALAppExtensions/issues/16724)
Can you please tell me when it will be implemented?

**Comment by pri-kise** [comment]
@MirabelaRobu this is already added in the latest BC 21 preview.
Maybe you can check the BC 20 CU preview version.
