### ISSUE TITLE
[Event Request] Codeunit 1535 "Approvals Mgmt." –  OnBeforeCheckSalesApprovalPossible

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#19233]
[Event Request] Codeunit 1535 "Approvals Mgmt." –  OnBeforeCheckSalesApprovalPossible

Could we please have a publisher OnBeforeCheckSalesApprovalPossible
in function CheckSalesApprovalPossible Codeunit 1535 "Approvals Mgmt."?

```
    procedure CheckSalesApprovalPossible(var SalesHeader: Record "Sales Header"): Boolean
// >>>>>>>>
    var 
        IsHandled := Boolean;
        Result := Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckSalesApprovalPossible(SalesHeader, Result, IsHandled);
        if IsHandled then
            exit(Result);
// <<<<<<<<   
        
        if not IsSalesApprovalsWorkflowEnabled(SalesHeader) then
            Error(NoWorkflowEnabledErr);

// >>>>>>>>
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckSalesApprovalPossible(var SalesHeader: Record "Sales Header"; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;
// <<<<<<<<   
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44163.
