### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt" - OnBeforeValidatePurchLineDiscountFields

### ISSUE THREAD

**Issue by AnkithShah** [microsoft/ALAppExtensions#19265]
Hi,

As part of our customization we need access to Variable RecalculateLines in a Event Subscriber.

Can you please add this extra parameter for Event "OnBeforeValidatePurchLineDiscountFields" in codeunit 6620 "Copy Document Mgt" as below.

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeValidatePurchLineDiscountFields(FromPurchHeader: Record "Purchase Header"; ToPurchHeader: Record "Purchase Header"; var ToPurchLine: Record "Purchase Line"; var InvDiscountAmount: Decimal; var IsHandled: Boolean; RecalculateLines: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44168.
