### ISSUE TITLE
[Event Extension Request] Table 39 "Purchase Line" - adding var to Parameter in Publisher OnCopyFromItemOnAfterCheck

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#19262]
Hello, we need Parameter PurchaseLine in the Publisher OnCopyFromItemOnAfterCheck to be defined as a var. Can you please check that? Thank you!

    [IntegrationEvent(false, false)]
    local procedure OnCopyFromItemOnAfterCheck(var PurchaseLine: Record "Purchase Line"; Item: Record Item; CallingFieldNo: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44163.
