### ISSUE TITLE
[Extensibility Request] Codeunit 550 "VAT Rate Change Conversion" - Procedure from Local to Global

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#19264]
Hello, we need the following currently Local procedure to be set as Global. Can you please check this? Thank you!

     procedure UpdateRec(var RecRef: RecordRef; ConvertVATProdPostingGroup: Boolean; ConvertGenProdPostingGroup: Boolean)

**Comment by AlexanderYakunin** [comment]
Already done, please look into v21 preview code
