### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt" - OnAfterSetDefaultValuesToPurchLine

### ISSUE THREAD

**Issue by AnkithShah** [microsoft/ALAppExtensions#19266]
Hi,

Can you please add extra parameter "Recalculatelines" for the Event "OnAfterSetDefaultValuesToPurchLine" as below. We notice the same parameter is available for "OnAfterSetDefaultValuesToSalesLine"

```
[IntegrationEvent(false, false)]
    local procedure OnAfterSetDefaultValuesToPurchLine(var ToPurchaseLine: Record "Purchase Line"; ToPurchHeader: Record "Purchase Header"; CreateToHeader: Boolean; Recalcularelines:Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44246.
