### ISSUE TITLE
[feature-request] tables 5877 "Phys. Invt. Record Header" / 5878 "Phys. Invt. Record Line" Field "Person Recorded" is Code[20]

### ISSUE THREAD

**Issue by BjEic** [microsoft/ALAppExtensions#19269]
In the tables 5877 "Phys. Invt. Record Header" and 5878 "Phys. Invt. Record Line" Field 102 "Person Recorded" is Code[20]  with table relation. Ist must be Code[50] with table relation to the user table.

**Comment by AlexanderYakunin** [comment]
These fields contains Employee No., not User ID. We can add field "Recorded by User ID" if needed?

**Comment by BjEic** [comment]
Yes, please integrate "Recorded by User ID"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10731.
