### ISSUE TITLE
Table 110 Sales Shipment Header - Field 106 Package Tracking No. - Increase size

### ISSUE THREAD

**Issue by g-franck** [microsoft/ALAppExtensions#19271]
Hi,

Some Shipping Agents have Tracking No. longer than 30 characters.
Ex: DB Schenker : 32 (*xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx).

Is it possible to increase the size of the field "Package Tracking No." ?

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14034.
