### ISSUE TITLE
[extensibility Bug] table 5741 "Transfer Line" - OnAfterCreateDimTableIDs ->OnAfterInitDefaultDimensionSources

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#19277]
Could you please fix the obsolete description of the event to mention the new event `OnAfterInitDefaultDimensionSources`.
And could you please add the callingfieldno to the event `OnAfterInitDefaultDimensionSources` as you did on for the `Sales Header`?
```al
#if not CLEAN20
    [Obsolete('Temporary event for compatibility', '20.0')]
    [IntegrationEvent(false, false)]
    local procedure OnAfterCreateDimTableIDs(var TransferLine: Record "Transfer Line"; FieldNo: Integer; var TableID: array[10] of Integer; var No: array[10] of Code[20])
    begin
    end;
#endif
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46699.
