### ISSUE TITLE
[Function-Request] Codeunit 311 "Item-Check Avail."

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#19274]
Hello, we need an overload function for ShowWarning with the new parameter UseOrderPromiseArg. Can you please check this? Thank you! 

    procedure ShowWarning(ItemNoArg: Code[20]; ItemVariantCodeArg: Code[10]; ItemLocationCodeArg: Code[10]; UnitOfMeasureCodeArg: Code[10]; QtyPerUnitOfMeasureArg: Decimal; NewItemNetChangeArg: Decimal; OldItemNetChangeArg: Decimal; ShipmentDateArg: Date; OldShipmentDateArg: Date; UseOrderPromiseArg: Boolean): Boolean
    begin
        UseOrderPromise := UseOrderPromiseArg;
        exit(ShowWarning(ItemNoArg, ItemVariantCodeArg, ItemLocationCodeArg, UnitOfMeasureCodeArg, QtyPerUnitOfMeasureArg, NewItemNetChangeArg, OldItemNetChangeArg, ShipmentDateArg, OldShipmentDateArg));
    end;

**Comment by AlexanderYakunin** [comment]
Can you use this procedure before calling Show Warning externally?

    procedure SetUseOrderPromise(NewUseOrderPromise: Boolean)
    begin
        UseOrderPromise := NewUseOrderPromise;
    end;
