### ISSUE TITLE
[Event Request] New event OnCreatePickOrMoveFromTransferOnAfterCreatePickOrMoveLine in codeunit 7322 "Create Inventory Pick/Movement"

### ISSUE THREAD

**Issue by TriangleSPV** [microsoft/ALAppExtensions#19272]
In the function CreatePickOrMoveFromSales it exists the event OnCreatePickOrMoveFromSalesOnAfterCreatePickOrMoveLine.
We need a similar event in function CreatePickOrMoveFromTransfer.

local procedure CreatePickOrMoveFromTransfer(TransferHeader: Record "Transfer Header")
...
                OnBeforeNewWhseActivLineInsertFromTransfer(NewWhseActivLine, TransferLine, WhseActivHeader, RemQtyToPickBase);RemQtyToPickBase);
                CalcFields("Reserved Quantity Outbnd.");
                CreatePickOrMoveLine(NewWhseActivLine, RemQtyToPickBase, "Outstanding Qty. (Base)", "Reserved Quantity Outbnd." <> 0);

                OnCreatePickOrMoveFromTransferOnAfterCreatePickOrMoveLine(NewWhseActivLine, TransferLine, WhseActivHeader, ShowError, AutoCreation, LineCreated);  // NEW EVENT

                if TransferHeader."Shipping Advice" = TransferHeader."Shipping Advice"::Complete then begin
                    if RemQtyToPickBase > 0 then begin

NEW INTEGRATION EVENT
[IntegrationEvent(false, false)]
local procedure OnCreatePickOrMoveFromTransferOnAfterCreatePickOrMoveLine(var WarehouseActivityLine: Record "Warehouse Activity Line"; var TransferLine: Record "Transfer Line"; var WarehouseActivityHeader: Record "Warehouse Activity Header"; ShowError: Boolean; AutoCreation: Boolean; var LineCreated: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
