### ISSUE TITLE
New event in Codeunit 74 "Purch.-Get Receipt"

### ISSUE THREAD

**Issue by sarachalaca** [microsoft/ALAppExtensions#19275]
In order to be able to not run testfield in Codeunit 74, we would like to ask a new event if possible.

Current Code:

    trigger OnRun()
    begin
        PurchHeader.Get("Document Type", "Document No.");
        PurchHeader.TestField("Document Type", PurchHeader."Document Type"::Invoice);
        PurchHeader.TestStatusOpen();

        PurchRcptLine.SetCurrentKey("Pay-to Vendor No.");
        PurchRcptLine.SetRange("Pay-to Vendor No.", PurchHeader."Pay-to Vendor No.");
        PurchRcptLine.SetRange("Buy-from Vendor No.", PurchHeader."Buy-from Vendor No.");
        PurchRcptLine.SetFilter("Qty. Rcd. Not Invoiced", '<>0');
        PurchRcptLine.SetRange("Currency Code", PurchHeader."Currency Code");

        OnAfterPurchRcptLineSetFilters(PurchRcptLine, PurchHeader);

        GetReceipts.SetTableView(PurchRcptLine);
        GetReceipts.LookupMode := true;
        GetReceipts.SetPurchHeader(PurchHeader);
        GetReceipts.RunModal();
    end;
	
	
Suggested code:

    trigger OnRun()
    var
	IsHandled: Boolean;
    begin
        PurchHeader.Get("Document Type", "Document No.");
	OnRunBeforePurchaseHeaderTestField(Rec,IsHandled);
	if not IsHandled then
		PurchHeader.TestField("Document Type", PurchHeader."Document Type"::Invoice);
        PurchHeader.TestStatusOpen();

        PurchRcptLine.SetCurrentKey("Pay-to Vendor No.");
        PurchRcptLine.SetRange("Pay-to Vendor No.", PurchHeader."Pay-to Vendor No.");
        PurchRcptLine.SetRange("Buy-from Vendor No.", PurchHeader."Buy-from Vendor No.");
        PurchRcptLine.SetFilter("Qty. Rcd. Not Invoiced", '<>0');
        PurchRcptLine.SetRange("Currency Code", PurchHeader."Currency Code");

        OnAfterPurchRcptLineSetFilters(PurchRcptLine, PurchHeader);

        GetReceipts.SetTableView(PurchRcptLine);
        GetReceipts.LookupMode := true;
        GetReceipts.SetPurchHeader(PurchHeader);
        GetReceipts.RunModal();
    end;

Event Definition:
	[IntegrationEvent(false, false)]
        local procedure OnRunBeforePurchaseHeaderTestField(PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
        begin
        end;

**Comment by AlexanderYakunin** [comment]
We already have solution implemented

    local procedure CheckHeader(PurchaseLine: Record "Purchase Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckHeader(PurchHeader, PurchaseLine, IsHandled);
        if IsHandled then
            exit;

        PurchHeader.Get(PurchaseLine."Document Type", PurchaseLine."Document No.");
        PurchHeader.TestField("Document Type", PurchHeader."Document Type"::Invoice);
        PurchHeader.TestStatusOpen();
    end;

**Comment by sarachalaca** [comment]
Hi Alexander,

Do you know where I can find that "CheckHeader" function? Codeunit 74? In which build?

Thanks in advance.

**Comment by AlexanderYakunin** [comment]
You can find it in 20.x and in v.21 preview builds
