### ISSUE TITLE
Add permission to codeunit 347 "Amount Auto Format"

### ISSUE THREAD

**Issue by DonHendriksen** [microsoft/ALAppExtensions#19278]
Hello,
Can you please add read permission on Record "General Ledger Setup" in codeunit 347 "Amount Auto Format"?

Desired solution:
Permissions = tabledata "General Ledger Setup" = r;

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47752.
