### ISSUE TITLE
[Event Request] Codeunit 73 "Purch.-Explode BOM" - OnAfterEvents

### ISSUE THREAD

**Issue by FlowStad** [microsoft/ALAppExtensions#19279]
Hello,
could you please integrate two events in the 73 "Purch.-Explode BOM" codeunit. There is no OnAfterRun and OnAfterInsert Event in the codeunit as in Sales-Explode BOM and we would need those for customer requests.
Many thanks.

                    OnBeforeInsertExplodedPurchLine(ToPurchLine, PurchLine, FromBOMComp);
                    ToPurchLine.Insert();
                //New Event
                    OnAfterInsertExplodedPurchLine(ToPurchLine, PurchLine, FromBOMComp);

                    if Selection = 1 then begin
                         ToPurchLine."Shortcut Dimension 1 Code" := "Shortcut Dimension 1 Code";
                    ...

    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertExplodedPurchLine(var ToPurchLine: Record "Purchase Line"; PurchLine: Record "Purchase Line"; FromBOMComp: Record "BOM Component")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterOnRun(ToPurchLine: Record "Purchase Line"; PurchLine: Record "Purchase Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44168.
