### ISSUE TITLE
[Event Request] Table 37 "Sales Line" - OnBeforeCheckShipmentRelation

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19281]
Please extend Event OnBeforeCheckShipmentRelation with additional parameter

```
[IntegrationEvent(true, false)]
local procedure OnBeforeCheckShipmentRelation(var IsHandled: Boolean; var SalesLine: Record "Sales Line"; CallingFieldNo: Integer)
begin
end;
```

```
local procedure CheckShipmentRelation()
var
    SalesShptLine: Record "Sales Shipment Line";
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeCheckShipmentRelation(IsHandled, Rec, CurrFieldNo);
    if IsHandled then
        exit;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44163.
