### ISSUE TITLE
[Event Request] Codeunit 550 "VAT Rate Change Conversion" –  OnUpdateSalesOnAfterUpdateSalesLines

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#19289]
[Event Request] Codeunit 550 "VAT Rate Change Conversion" –  OnUpdateSalesOnAfterUpdateSalesLines

Can we please get a var before the Sales Header variable at the event OnUpdateSalesOnAfterUpdateSalesLines (Codeunit 550 "VAT Rate Change Conversion")

```
    // >>>>>>>>
    [IntegrationEvent(true, false)]
    local procedure OnUpdateSalesOnAfterUpdateSalesLines(VATRateChangeSetup: Record "VAT Rate Change Setup";  var SalesHeader: Record "Sales Header"; ConvertVATProdPostingGroup: Boolean; ConvertGenProdPostingGroup: Boolean)
    begin
    end;
    // <<<<<<<< 
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44168.
