### ISSUE TITLE
[Extensibility Enhancement] Add Obsolete properties to "Custom Report Layout" related objects

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#19283]
As stated in the Microsoft Docs (https://docs.microsoft.com/en-us/dynamics365/business-central/ui-manage-report-layouts#layout-sources), custom report layouts are being phased out and are considered _legacy_.
Also, with BC 20.0 the custom report layout had a (runtime) breaking change for extensions, i.e., it could not be used for custom types anymore (previously, you could extend enum "Custom Report Layout Type", but starting from BC 20.0 this will throw an error at runtime, when you run a report).
We resolved that with some upgrade code, but I am adding this comment more so, to say, that also in this regard, it can be considered deprecated (or even more than that; considering the report rendering refactoring changes were directly blocking it off for extensions, rather than having a transition period 😅).

Here is also the excerpt from the Docs stating it is being phased out:

> Custom layouts
> 
> Custom layouts are also layouts that are created by users. The difference is that these layouts are created from the legacy Custom Report Layouts page, and they can only be Word and RDLC type. Although you can still create custom layouts, they're being phased out in favor of user-defined layouts.
> 
> For more information, see [(Legacy) Create and Modify Custom Report Layouts](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-create-custom-report-layout).

Would it be an idea to add the `ObsoleteState = Pending;` and other Obsolete-properties to mark the custom report layout feature as obsolete in favor of the new report rendering implementation using the new system tables? Or is there a reason why this is currently not done?
My reasoning for filing this GitHub issue is that awareness should be raised that this is being phased out and that you should from now on develop extensions based on the new report rendering implementation (based on the new system tables/pages), so a deprecation warning would help developers in recognizing this.

This among others concerns the following objects:
- Table "Custom Report Layout"
- Fields, actions and procedures on the "Report Selections" and "Custom Report Selection" table and related objects
- Page "Custom Report Layouts"
- Fields, actions, and procedures on the "Report Layout Selection" page (type 'Custom')
- Page "Report Layout Lookup"

**Comment by AlexanderYakunin** [comment]
Found this active item. We are not going to obsolete Custom Report Layout objects yet, there are too many dependencies and many solutions still use it.
