### ISSUE TITLE
[Extensiblity Bug]  table 83 "Item Journal Line" - OnAfterCreateDimTableIDs - OnAfterInitDefaultDimensionSources

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#19285]
Could you please update the obsolete signature of the event `OnAfterCreateDimTableIDs` to use the event `OnAfterInitDefaultDimensionSources` instead - similiar how you did it on the `Sales Header`.
It is really annoying to guess how the code was refactored.
```al
#if not CLEAN20
//+Change
//-    [Obsolete('Temporary event for compatibility', '20.0')]
    [Obsolete('Replaced by OnAfterInitDefaultDimensionSources() event', '20.0')]
//-Change
    [IntegrationEvent(false, false)]
    local procedure OnAfterCreateDimTableIDs(var ItemJournalLine: Record "Item Journal Line"; CallingFieldNo: Integer; var TableID: array[10] of Integer; var No: array[10] of Code[20])
    begin
    end;
#endif
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46699.
