### ISSUE TITLE
[Extensibility Enhancement] Table 167 Job - Make the function "SetHideValidationDialog" external

### ISSUE THREAD

**Issue by redIT-LoPf** [microsoft/ALAppExtensions#19286]
![Screenshot](https://user-images.githubusercontent.com/37530329/179953129-2bfa25b7-818c-4a85-b0c0-8c21627cb8ce.png)

**Comment by pri-kise** [comment]
You should check the latest insider preview versions, or at least check the issues of this repository. This was already requested and changed in the main branch.

**Comment by AlexanderYakunin** [comment]
Already done

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
