### ISSUE TITLE
[Event Request] Table 37 "Sales Line" - OnBeforeValidateUnitCostLCY

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19284]
Please add new event in the table 37: OnBeforeValidateUnitCostLCY

```
field(23; "Unit Cost (LCY)"; Decimal)
{
    AutoFormatType = 2;
    Caption = 'Unit Cost (LCY)';

    trigger OnValidate()
    var
        Item: Record Item;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeValidateUnitCostLCY(xRec, CurrFieldNo, IsHandled);
        if IsHandled then
            exit;
```

```
[IntegrationEvent(true, false)]
local procedure OnBeforeValidateUnitCostLCY(var xRec: Record "Sales Line"; CurrFieldNo: Integer; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44163.
