### ISSUE TITLE
[Event Request] Codeunit 550 "VAT Rate Change Conversion" –  OnUpdatePurchaseOnAfterResetPurchaseHeaderStatus

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#19297]
[Event Request] Codeunit 550 "VAT Rate Change Conversion" –  OnUpdatePurchaseOnAfterResetPurchaseHeaderStatus

Could we please have a publisher OnUpdatePurchaseOnAfterResetPurchaseHeaderStatus
in function UpdatePurchase Codeunit 550 "VAT Rate Change Conversion"?

```
                    end;
                    if StatusChanged then begin
                        PurchaseHeader.Status := PurchaseHeader2.Status;
                        PurchaseHeader.Modify();
                        
                        // >>>>>>>>
                        OnUpdatePurchaseOnAfterResetPurchaseHeaderStatus(PurchaseHeader);
                        // <<<<<<<< 

                    end;
                end;
            until PurchaseHeader.Next() = 0;
    end;

    // >>>>>>>>
    [IntegrationEvent(false, false)]
    local procedure OnUpdatePurchaseOnAfterResetPurchaseHeaderStatus(var PurchaseHeader: Record "Purchase Header")
    begin
    end;
    // <<<<<<<< 

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44168.
