### ISSUE TITLE
Table 5080 "To-do" - var

### ISSUE THREAD

**Issue by MrinalSingha** [microsoft/ALAppExtensions#19305]
Hi microsoft/ALAppExtensions

can you please define following variable as protected:

`TempEndDateTime: DateTime;`

as 

```
protected var
TempEndDateTime: DateTime;

```
We need to access this variable in our table extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
