### ISSUE TITLE
Set CarryOutActions  procedure as Global in Report report 99001020 "Carry Out Action Msg. - Plan."

### ISSUE THREAD

**Issue by a-augros** [microsoft/ALAppExtensions#19303]
Please can you set CarryOutActions as global instead of local in Report report 99001020 "Carry Out Action Msg. - Plan." to be able to call this function from an Event Subscriber

```
procedure CarryOutActions(SourceType: Option Purchase,Transfer,Production,Assembly; Choice: Option; WkshTempl: Code[10]; WkshName: Code[10])
    begin
        if NoPlanningResiliency then begin
            CarryOutAction.SetTryParameters(SourceType, Choice, WkshTempl, WkshName);
            CarryOutAction.Run("Requisition Line");
        end else
            if not CarryOutAction.TryCarryOutAction(SourceType, "Requisition Line", Choice, WkshTempl, WkshName) then
                CounterFailed := CounterFailed + 1;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44906.
