### ISSUE TITLE
[Extensibility Request] Page 344 Navigate - Procedures from local to global

### ISSUE THREAD

**Issue by horstoeko** [microsoft/ALAppExtensions#19314]
Hello, we need the following currently Local procedures to be set as Global. Can you please check this? Thank you!

```al
ItemTrackingSearch
FindTrackingRecords
FindRecords
FindPush
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44906.
