### ISSUE TITLE
Table 5097 Segment Criteria Line - Increase field length field 7 (View)

### ISSUE THREAD

**Issue by knkcgv** [microsoft/ALAppExtensions#19316]
please extend the field length for field 7 from 250 to 2048

field(7; View; Text[250])
to
field(7; View; Text[2048])

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47647.
