### ISSUE TITLE
[Event Request] Table 110 Sales Shipment Header - procedure Navigate - OnBeforeNavigate

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#19337]
Please add an Event OnBeforeNavigate in procedure Navigate in Table 110 Sales Shipment Header

```
Navigate()
    var
        NavigatePage: Page Navigate;
        IsHandled: Boolean; <-- NEW VAR
    begin
        IsHandled := false;
        OnBeforeNavigate(Rec,IsHandled); <-- NEW EVENT
        If IsHandled then
           exit;

        NavigatePage.SetDoc("Posting Date", "No.");
        NavigatePage.SetRec(Rec);
        NavigatePage.Run();
    end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeNavigate(Rec: Record "Sales Shipment Header"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44246.
