### ISSUE TITLE
[Event Parameter Change] Table 37 Sales Line - Trigger OnValidate Line Amount - Event OnBeforeValidateLineAmount

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#19330]
We would like the parameter Currency added to the following events.

Table 37 Sales Line - Trigger OnValidate Line Amount - Event OnBeforeValidateLineAmount

Original:

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeValidateLineAmount(var SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line"; CurrentFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;
```

Change

```
OnBeforeValidateLineAmount(Rec, xRec, CurrFieldNo, IsHandled, Currency);

[IntegrationEvent(false, false)]
    local procedure OnBeforeValidateLineAmount(var SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line"; CurrentFieldNo: Integer; var IsHandled: Boolean; Currency: Record Currency)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44163.
