### ISSUE TITLE
[Event Parameter Change] Codeunit 6620 - Copy Document Mgt. - procedure CopySalesCrMemoLinesToDoc - event OnCopySalesCrMemoLinesToDocOnAfterCalcShouldCopyItemTracking

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#19333]
We would like the parameter ToSalesLine added to the following events.

Codeunit 6620 - Copy Document Mgt. - procedure CopySalesCrMemoLinesToDoc - event OnCopySalesCrMemoLinesToDocOnAfterCalcShouldCopyItemTracking

Original:

```
OnCopySalesCrMemoLinesToDocOnAfterCalcShouldCopyItemTracking(ToSalesHeader, ShouldCopyItemTracking);

[IntegrationEvent(false, false)]
local procedure OnCopySalesCrMemoLinesToDocOnAfterCalcShouldCopyItemTracking(ToSalesHeader: Record "Sales Header"; var ShouldCopyItemTracking: Boolean)
begin
end;
```

Change

```
OnCopySalesCrMemoLinesToDocOnAfterCalcShouldCopyItemTracking(ToSalesHeader, ShouldCopyItemTracking, ToSalesLine); // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnCopySalesCrMemoLinesToDocOnAfterCalcShouldCopyItemTracking(ToSalesHeader: Record "Sales Header"; var ShouldCopyItemTracking: Boolean; ToSalesLine: Record "Sales Line") // <-- ADDED
begin
end;		
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44168.
