### ISSUE TITLE
[Event Request] Report 99001043 Exchange Production BOM Item - Trigger OnInit  - OnAfterOnInitReport

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#19346]
Please add an Event OnAfterOnInitReport in Trigger OnInit in Report 99001043 Exchange Production BOM Item

```
        trigger OnInit()
        begin
            DeleteExchangedComponentEditab := true;
            CreateNewVersionEditable := true;
            CreateNewVersion := true;
            QtyMultiply := 1;
            StartingDate := WorkDate;
            OnAfterOnInitReport(CreateNewVersion,StartingDate,DeleteExcComp); <-- NEW EVENT
        end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterOnInitReport(var CreateNewVersion: Boolean; var StartingDate: Date; var DeleteExcComp: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44246.
