### ISSUE TITLE
[Event Request] Table 37 Sales Line - Procedure UpdateICPartner  - OnBeforeUpdateICPartner

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#19341]
Please add an Event OnBeforeUpdateICPartner in Procedure UpdateICPartner in Table 37 Sales Line 

```
UpdateICPartner()
    var
        ICPartner: Record "IC Partner";
        IsHandled: Boolean; <-- NEW VAR
    begin
        IsHandled: false;
        OnBeforeUpdateICPartner(Rec,GLAcc,PurchHeader,IsHandled); <-- NEW EVENT
        If IsHandled then
           exit;

        ...
    end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateICPartner(var PurchLine: Record "Purchase Line"; GLAcc: Record "G/L Account"; PurchHeader: Record "Purchase Header"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44163.
