### ISSUE TITLE
[Event Request] codeunit 1545 "Workflow Webhook Notification" - event PostHttpRequest

### ISSUE THREAD

**Issue by JAng13sea** [microsoft/ALAppExtensions#19358]
Existing code is like below:
`[TryFunction]
    local procedure PostHttpRequest(DataID: Guid; WorkflowStepInstanceID: Guid; NotificationUrl: Text; RequestedByUserEmail: Text)
    var
        TypeHelper: Codeunit "Type Helper";
        HttpWebRequest: DotNet HttpWebRequest;
        HttpWebResponse: DotNet HttpWebResponse;
        RequestStr: DotNet Stream;
        StreamWriter: DotNet StreamWriter;
        Encoding: DotNet Encoding;
    begin
        HttpWebRequest := HttpWebRequest.Create(NotificationUrl);
        HttpWebRequest.Method := 'POST';
        HttpWebRequest.ContentType('application/json');

        RequestStr := HttpWebRequest.GetRequestStream;
        StreamWriter := StreamWriter.StreamWriter(RequestStr, Encoding.ASCII);
        StreamWriter.Write('{"Row Id":"' + TypeHelper.GetGuidAsString(DataID) +
          '","Workflow Step Id":"' + TypeHelper.GetGuidAsString(WorkflowStepInstanceID) +
          '","Requested By User Email":"' + RequestedByUserEmail + '"}');
        StreamWriter.Flush;
        StreamWriter.Close;
        StreamWriter.Dispose;

        HttpWebResponse := HttpWebRequest.GetResponse;
        HttpWebResponse.Close; // close connection
        HttpWebResponse.Dispose; // cleanup of IDisposable
    end;`

Justification for the request is that sending more information in the webhook response will enable a Power Automate or Azure Logic Apps user to use conditional triggers. At present the current payload requires users of the mentioned platforms to check the data behind the request every time a flow is executed. Other Microsoft products allow for conditional triggering because the payload of the webhook response includes all the data. The event would need to be before the streamwriter is closed and disposed so that additions could be added to the string.

**Comment by AlexanderYakunin** [comment]
Hello, can you provide event definition and placement in this code?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44362.
