### ISSUE TITLE
[Event Request] Table 5080 "To-do" - OnAfterStartWizard2

### ISSUE THREAD

**Issue by MrinalSingha** [microsoft/ALAppExtensions#19359]
Can you please add a new event 

```
        "Wizard Step" := "Wizard Step"::"1";
        Duration := 1440 * 1000 * 60;

        OnBeforeInsertStartWizard2(Rec); // New Event
        Insert;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertStartWizard2(var Task: Record "To-do")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44246.
