### ISSUE TITLE
[Event Parameter Change] Codeunit 414 "Release Sales Document" - Procedure Code - Event OnBeforeCalcInvDiscount

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19367]
We would like the parameter LinesWereModified added to the following event.

Codeunit 414 "Release Sales Document" - Procedure Code - Event OnBeforeCalcInvDiscount

Original:

```
OnBeforeCalcInvDiscount(SalesHeader, PreviewMode);

[IntegrationEvent(false, false)]
local procedure OnBeforeCalcInvDiscount(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean)
begin
end;
```

Change:

```
OnBeforeCalcInvDiscount(SalesHeader, PreviewMode, SalesLine, LinesWereModified); // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnBeforeCalcInvDiscount(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean; var SalesLine: Record "Sales Line"; var LinesWereModified: Boolean) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44246.
