### ISSUE TITLE
[Event Parameter Change] Codeunit 414 "Release Sales Document" - Procedure Code - Event OnCodeOnAfterCheckCustomerCreated

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19365]
We would like the parameter LinesWereModified added to the following events.

Codeunit 414 "Release Sales Document" - Procedure Code - Event OnCodeOnAfterCheckCustomerCreated

Original:

```
OnCodeOnAfterCheckCustomerCreated(SalesHeader, PreviewMode, IsHandled);

[IntegrationEvent(false, false)]
local procedure OnCodeOnAfterCheckCustomerCreated(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean; var IsHandled: Boolean)
begin
end;
```

Change:

```
OnCodeOnAfterCheckCustomerCreated(SalesHeader, PreviewMode, IsHandled, LinesWereModified); // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnCodeOnAfterCheckCustomerCreated(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean; var IsHandled: Boolean; var LinesWereModified: Boolean) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44246.
