### ISSUE TITLE
Table 5080 "To-do" - InsertActivityTask

### ISSUE THREAD

**Issue by MrinalSingha** [microsoft/ALAppExtensions#19360]
Can you please make this procedure global, we need to access this functionality in another object.

Old Code
`
local procedure InsertActivityTask(Task2: Record "To-do"; ActivityCode: Code[10]; var Attendee: Record Attendee)
`

New Code
`procedure InsertActivityTask(Task2: Record "To-do"; ActivityCode: Code[10]; var Attendee: Record Attendee)`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
