### ISSUE TITLE
[Event Extension Request] Codeunit 63 "Sales-Explode BOM" - new Parameter in Publisher OnExplodeBOMCompLinesOnAfterFromBOMCompSetFilters

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#19378]
Hello, we need a new Parameter in the Publisher OnExplodeBOMCompLinesOnAfterFromBOMCompSetFilters. Can you please check that? Thank you!

    local procedure ExplodeBOMCompLines(SalesLine: Record "Sales Line")
    var
        PreviousSalesLine: Record "Sales Line";
        InsertLinesBetween: Boolean;
    begin
        with SalesLine do begin
            ToSalesLine.Reset();
            ToSalesLine.SetRange("Document Type", "Document Type");
            ToSalesLine.SetRange("Document No.", "Document No.");
            ToSalesLine := SalesLine;
            NextLineNo := "Line No.";
            InsertLinesBetween := false;
            if ToSalesLine.Find('>') then
                if ToSalesLine."Attached to Line No." = "Line No." then begin
                    ToSalesLine.SetRange("Attached to Line No.", "Line No.");
                    ToSalesLine.FindLast;
                    ToSalesLine.SetRange("Attached to Line No.");
                    NextLineNo := ToSalesLine."Line No.";
                    InsertLinesBetween := ToSalesLine.Find('>');
                end else
                    InsertLinesBetween := true;
            if InsertLinesBetween then
                LineSpacing := (ToSalesLine."Line No." - NextLineNo) div (1 + NoOfBOMComp)
            else
                LineSpacing := 10000;
            if LineSpacing = 0 then
                Error(Text003);

            FromBOMComp.Reset();
            FromBOMComp.SetRange("Parent Item No.", "No.");
            OnExplodeBOMCompLinesOnAfterFromBOMCompSetFilters(FromBOMComp, SalesLine, LineSpacing);        <=======
            FromBOMComp.FindSet();
            repeat
                ToSalesLine.Init();
                NextLineNo := NextLineNo + LineSpacing;
                ToSalesLine."Line No." := NextLineNo;

                case FromBOMComp.Type of
                    FromBOMComp.Type::" ": ..................................

New Event signature:

    [IntegrationEvent(false, false)]
    local procedure OnExplodeBOMCompLinesOnAfterFromBOMCompSetFilters(var BOMComponent: Record "BOM Component"; SalesLine: Record "Sales Line"; var LineSpacing: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44285.
