### ISSUE TITLE
[Event Extension Request] Codeunit 63 "Sales-Explode BOM" - new Parameter in Publisher OnAfterExplodeBOMCompLines

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#19380]
Hello, we need a new Parameter in the Publisher OnAfterExplodeBOMCompLines. Can you please check that? Thank you!

    local procedure ExplodeBOMCompLines(SalesLine: Record "Sales Line")
    var
        PreviousSalesLine: Record "Sales Line";
        InsertLinesBetween: Boolean;
    begin
        with SalesLine do begin
            ToSalesLine.Reset();
            ToSalesLine.SetRange("Document Type", "Document Type");
            ToSalesLine.SetRange("Document No.", "Document No.");
            ToSalesLine := SalesLine;
            NextLineNo := "Line No.";
            InsertLinesBetween := false;
            if ToSalesLine.Find('>') then
                if ToSalesLine."Attached to Line No." = "Line No." then begin
                    ToSalesLine.SetRange("Attached to Line No.", "Line No.");
                    ToSalesLine.FindLast;
                    ToSalesLine.SetRange("Attached to Line No.");
                    NextLineNo := ToSalesLine."Line No.";
                    InsertLinesBetween := ToSalesLine.Find('>');
                end else
                    InsertLinesBetween := true;
            if InsertLinesBetween then
                LineSpacing := (ToSalesLine."Line No." - NextLineNo) div (1 + NoOfBOMComp)
            else
                LineSpacing := 10000;
            if LineSpacing = 0 then
                Error(Text003);

            FromBOMComp.Reset();
            FromBOMComp.SetRange("Parent Item No.", "No.");
            OnExplodeBOMCompLinesOnAfterFromBOMCompSetFilters(FromBOMComp, SalesLine);
            FromBOMComp.FindSet();
            repeat
                ToSalesLine.Init();
                NextLineNo := NextLineNo + LineSpacing;
                ToSalesLine."Line No." := NextLineNo;

                case FromBOMComp.Type of
                    FromBOMComp.Type::" ":
                        ToSalesLine.Type := ToSalesLine.Type::" ";
                    FromBOMComp.Type::Item:
                        ToSalesLine.Type := ToSalesLine.Type::Item;
                    FromBOMComp.Type::Resource:
                        ToSalesLine.Type := ToSalesLine.Type::Resource;
                end;
                if ToSalesLine.Type <> ToSalesLine.Type::" " then begin
                    FromBOMComp.TestField("No.");
                    ToSalesLine.Validate("No.", FromBOMComp."No.");
                    if SalesHeader."Location Code" <> "Location Code" then
                        ToSalesLine.Validate("Location Code", "Location Code");
                    if FromBOMComp."Variant Code" <> '' then
                        ToSalesLine.Validate("Variant Code", FromBOMComp."Variant Code");
                    if ToSalesLine.Type = ToSalesLine.Type::Item then begin
                        ToSalesLine."Drop Shipment" := "Drop Shipment";
                        Item.Get(FromBOMComp."No.");
                        ToSalesLine.Validate("Unit of Measure Code", FromBOMComp."Unit of Measure Code");
                        ToSalesLine."Qty. per Unit of Measure" := UOMMgt.GetQtyPerUnitOfMeasure(Item, ToSalesLine."Unit of Measure Code");
                        ToSalesLine.Validate(Quantity,
                          Round(
                            "Quantity (Base)" * FromBOMComp."Quantity per" *
                            UOMMgt.GetQtyPerUnitOfMeasure(
                              Item, ToSalesLine."Unit of Measure Code") / ToSalesLine."Qty. per Unit of Measure",
                            UOMMgt.QtyRndPrecision));
                    end else
                        if ToSalesLine.Type = ToSalesLine.Type::Resource then begin
                            Resource.Get(FromBOMComp."No.");
                            ToSalesLine.Validate("Unit of Measure Code", FromBOMComp."Unit of Measure Code");
                            ToSalesLine."Qty. per Unit of Measure" :=
                              UOMMgt.GetResQtyPerUnitOfMeasure(Resource, ToSalesLine."Unit of Measure Code");
                            ToSalesLine.Validate(Quantity,
                              Round(
                                "Quantity (Base)" * FromBOMComp."Quantity per" *
                                UOMMgt.GetResQtyPerUnitOfMeasure(
                                  Resource, ToSalesLine."Unit of Measure Code") / ToSalesLine."Qty. per Unit of Measure",
                                UOMMgt.QtyRndPrecision));
                        end else
                            ToSalesLine.Validate(Quantity, "Quantity (Base)" * FromBOMComp."Quantity per");

                    if SalesHeader."Shipment Date" <> "Shipment Date" then
                        ToSalesLine.Validate("Shipment Date", "Shipment Date");
                end;
                if SalesHeader."Language Code" = '' then
                    ToSalesLine.Description := FromBOMComp.Description
                else
                    if not ItemTranslation.Get(FromBOMComp."No.", FromBOMComp."Variant Code", SalesHeader."Language Code") then
                        ToSalesLine.Description := FromBOMComp.Description;

                ToSalesLine."BOM Item No." := BOMItemNo;
                OnInsertOfExplodedBOMLineToSalesLine(ToSalesLine, SalesLine, FromBOMComp, SalesHeader);

                ToSalesLine.Insert();
                OnExplodeBOMCompLinesOnAfterToSalesLineInsert(ToSalesLine, SalesLine, FromBOMComp);

                ToSalesLine.Validate("Qty. to Assemble to Order");

                if (ToSalesLine.Type = ToSalesLine.Type::Item) and (ToSalesLine.Reserve = ToSalesLine.Reserve::Always) then
                    ToSalesLine.AutoReserve();

                if Selection = 1 then begin
                    ToSalesLine."Shortcut Dimension 1 Code" := "Shortcut Dimension 1 Code";
                    ToSalesLine."Shortcut Dimension 2 Code" := "Shortcut Dimension 2 Code";
                    ToSalesLine."Dimension Set ID" := "Dimension Set ID";
                    ToSalesLine.Modify();
                end;

                if PreviousSalesLine."Document No." <> '' then
                    if TransferExtendedText.SalesCheckIfAnyExtText(PreviousSalesLine, false) then
                        TransferExtendedText.InsertSalesExtText(PreviousSalesLine);

                PreviousSalesLine := ToSalesLine;
            until FromBOMComp.Next() = 0;

            if TransferExtendedText.SalesCheckIfAnyExtText(ToSalesLine, false) then
                TransferExtendedText.InsertSalesExtText(ToSalesLine);
        end;

        OnAfterExplodeBOMCompLines(SalesLine, Selection, LineSpacing);          <=============
    end;

New Event signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterExplodeBOMCompLines(var SalesLine: Record "Sales Line"; Selection: Integer; LineSpacing: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44285.
