### ISSUE TITLE
[Event Request] codeunit 7032 "Price Source - Customer" - OnAfterFillAdditionalFields

### ISSUE THREAD

**Issue by ahenkel** [microsoft/ALAppExtensions#19381]
To extended "Price List Line" with additional fields from item table we need an event that is called right after "FillAdditionalFields"
```
local procedure FillAdditionalFields(var PriceSource: Record "Price Source")
    begin
        PriceSource.Description := Customer.Name;
        PriceSource."Currency Code" := Customer."Currency Code";
        PriceSource."Allow Line Disc." := Customer."Allow Line Disc.";
        PriceSource."Price Includes VAT" := Customer."Prices Including VAT";
        PriceSource."VAT Bus. Posting Gr. (Price)" := Customer."VAT Bus. Posting Group";
+       OnAfterFillAdditionalFields(Customer,PriceSource);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44285.
