### ISSUE TITLE
[Event Request] table 7005 "Price Source" - OnAfterInitSource()

### ISSUE THREAD

**Issue by ahenkel** [microsoft/ALAppExtensions#19382]
To extended "Price List Line" with additional fields from item table we need an event that is called right after "InitSource"

```
procedure InitSource()
    begin
        Clear("Source ID");
        "Parent Source No." := '';
        "Source No." := '';
        Description := '';
        "Filter Source No." := '';
        "Currency Code" := '';
        GetPriceType();
+       OnAfterInitSource(Rec);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44285.
