### ISSUE TITLE
[Event Request] table 5005270

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/ALAppExtensions#1939]
Hi, in https://github.com/Microsoft/ALAppExtensions/issues/898 i requested a few events.
Event 1 (OnInsert) is missing the handler pattern. Please add

**Comment by AlexanderYakunin** [comment]
Hi, we already have what you need, look here
![image](https://user-images.githubusercontent.com/31849120/56187317-e21daf80-602a-11e9-9c86-dfcf401203ef.png)
