### ISSUE TITLE
[Event Request] Codeunit 18466 "Subcontracting Post" - procedure PostSubconCompCE() - OnBeforePostSubconCompCE

### ISSUE THREAD

**Issue by Hemali80** [microsoft/ALAppExtensions#19399]
procedure PostSubconCompCE(ProdOrder: Record "Production Order";ProdOrderLine: Record "Prod. Order Line";ProdOrderComp:      Record "Prod. Order Component";Purchline: Record "Purchase Line")
      var
          IsHandled : Boolean;  <-- NEW VAR 
      begin 
           IsHandled := false;  <-- NEW CODE
           OnBeforePostSubconCompCE(ProdOrder: Record "Production Order";ProdOrderLine: Record "Prod. Order Line";ProdOrderComp: Record "Prod. Order Component";Purchline: Record "Purchase Line"; var IsHandled : Boolean); <-- NEW EVENT        
           If IsHandled then   <-- NEW CODE
             exit;
      end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44660.
