### ISSUE TITLE
Table 5401 - Item Variant -> Length of Code Field

### ISSUE THREAD

**Issue by rovelgoenne** [microsoft/ALAppExtensions#194]
Hi,

we are trying to transfer ower solution into an extension. 
We uses the item variant to differ between master data. The master data Table use the No,.Series and as we know the No. Series Lines are Code20. 
So we extend the variant code field from Code10 to Code20. As far as I know In an extension this  is not possible. 
Is it possible that the base application will extend the variant code from code10 to code20? 

Kind regards,
Reiner Ovelgoenne

**Comment by kevindstanley1988** [comment]
Is there a reason this was moved into the ALAppExtensions repo? As far as I am aware this functionality could not be made into an extension. Extensions do not allow you to change the length of a field on a table, so it is technically impossible to do this as an extension. Is there any planned(future) AL functionality to change the length of a text or code field from an AL Extension?

**Comment by ikoletic** [comment]
We moved all the issues from old repo to new ALAppExtensions repo so old one can be used for pure developer and no application issues. 
Above sounds like product suggestion which is already recorded so please cast your votes on those:
- Item Variant code extension: https://experience.dynamics.com/ideas/idea/?ideaid=e6ad237e-5c88-e911-80e7-0003ff68d30d 
- Expand Item Cross Reference field: https://experience.dynamics.com/ideas/idea/?ideaid=ed1ed8f8-bf23-e911-9461-0003ff68d30d
-
