### ISSUE TITLE
[Event Request] Codeunit 18466 "Subcontracting Post" - procedure PostScrapAtVE() - OnBeforePostScrapAtVE 

### ISSUE THREAD

**Issue by Hemali80** [microsoft/ALAppExtensions#19400]
procedure PostScrapAtVE(ProdOrder: Record "Production Order";ProdOrderLine: Record "Prod. Order Line";ProdOrderComp: Record "Prod. Order Component";PurchaseLine: Record "Purchase Line")
      var
         IsHandled : Boolean;  <-- NEW VAR 
      begin 
         IsHandled := false;  <-- NEW CODE
         OnBeforePostScrapAtVE(ProdOrder: Record "Production Order";ProdOrderLine: Record "Prod. Order Line";ProdOrderComp: Record "Prod. Order Component";PurchaseLine: Record "Purchase Line"; var IsHandled : Boolean); <-- NEW EVENT        
         If IsHandled then   <-- NEW CODE
             exit;
      End;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47716.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 47773.
