### ISSUE TITLE
[Event Request] Codeunit 18466 "Subcontracting Post" - procedure PostSubconCompCE() - OnAfterAppliedDeliveryChallan

### ISSUE THREAD

**Issue by Hemali80** [microsoft/ALAppExtensions#19406]
Procedure PostSubconCompCE(ProdOrder: Record "Production Order";ProdOrderLine: Record "Prod. Order Line";ProdOrderComp: Record "Prod. Order Component";Purchline: Record "Purchase Line")
    var
        CompItem: Record "Item";
        ItemLedgerEntry: Record "Item Ledger Entry";
        SubOrderCompVend: Record "Sub Order Comp. List Vend";
        AppliedDeliveryChallan: Record "Applied Delivery Challan";
        Item: Record Item;
        ItemTrackingCode: Record "Item Tracking Code";
        OldReservEntry: Record "Reservation Entry";
        ItemTrackingSetup: Record "Item Tracking Setup";
        ItemTrackingManagement: Codeunit "Item Tracking Management";
        ItemJnlPostLine: Codeunit "Item Jnl.-Post Line";
        RemQtytoPost: Decimal;
        TotalQtyToPost: Decimal;
        Completed: Boolean;
        Inbound: Boolean;
        SNRequired: Boolean;
        LotRequired: Boolean;
        SNInfoRequired: Boolean;
        LotInfoRequired: Boolean;
        CheckTrackingLine: Boolean;
        TrackingQtyHandled: Decimal;
        TrackingQtyToHandle: Decimal;
        QuantitySent: Decimal;
    begin
        SubOrderCompVend.SetRange("Document No.", Purchline."Document No.");
        SubOrderCompVend.SetRange("Production Order No.", ProdOrderComp."Prod. Order No.");
        SubOrderCompVend.SetRange("Production Order Line No.", ProdOrderComp."Prod. Order Line No.");
        SubOrderCompVend.SetRange("Line No.", ProdOrderComp."Line No.");
        if SubOrderCompVend.FindFirst() then begin
            SourceCodeSetup.Get();
            CheckIfAppDelChallan(SubOrderCompVend);
            CheckAppDelChallan(SubOrderCompVend);
        end;

        CompItem.Get(ProdOrderComp."Item No.");
        CompItem.TestField("Rounding Precision");
        AppliedDeliveryChallan.Reset();
        AppliedDeliveryChallan.SetRange("Document No.", SubOrderCompVend."Document No.");
        AppliedDeliveryChallan.SetRange("Document Line No.", SubOrderCompVend."Document Line No.");
        AppliedDeliveryChallan.SetRange("Parent Item No.", SubOrderCompVend."Parent Item No.");
        AppliedDeliveryChallan.SetRange("Line No.", SubOrderCompVend."Line No.");
        AppliedDeliveryChallan.SetRange("Item No.", SubOrderCompVend."Item No.");
        if AppliedDeliveryChallan.FindSet() then
            repeat
                Completed := false;
                TotalQtyToPost := AppliedDeliveryChallan."Qty. to Return (C.E.)";
                TotalQtyToPost := Round(TotalQtyToPost, CompItem."Rounding Precision", '>');
                RemQtytoPost := TotalQtyToPost;

                CheckItemTracking(AppliedDeliveryChallan, TypeQty::RejectCE);
                GetApplicationLines(ProdOrderComp, SubOrderCompVend, ItemLedgerEntry, TotalQtyToPost, AppliedDeliveryChallan);
                if ItemLedgerEntry.FindSet() then
                    if RemQtytoPost <> 0 then
                        repeat
                            OldReservEntry.Reset();
                            if FindReservEntryVendBef(AppliedDeliveryChallan, OldReservEntry, 0, ItemLedgerEntry, TypeQty::RejectCE) then begin
                                ItemJnlLine.Init();
                                ItemJnlLine."Entry Type" := ItemJnlLine."Entry Type"::Consumption;
                                ItemJnlLine.Validate("Posting Date", SubOrderCompVend."Posting Date");
                                ItemJnlLine."Document No." := ProdOrderLine."Prod. Order No.";
                                ItemJnlLine."Source Type" := ItemJnlLine."Source Type"::Item;
                                ItemJnlLine."Source No." := ProdOrderLine."Item No.";
                                ItemJnlLine."Order Type" := ItemJnlLine."Order Type"::Production;
                                ItemJnlLine."Order No." := ProdOrderLine."Prod. Order No.";
                                ItemJnlLine."Order Line No." := ProdOrderLine."Line No.";
                                ItemJnlLine."Subcon Order No." := ProdOrderLine."Subcontracting Order No.";
                                ItemJnlLine.Validate("Prod. Order Comp. Line No.", ProdOrderComp."Line No.");
                                ItemJnlLine.Validate("Item No.", ProdOrderComp."Item No.");
                                ItemJnlLine.Validate("Unit of Measure Code", ProdOrderComp."Unit of Measure Code");
                                ItemJnlLine.Description := ProdOrderComp.Description;
                                GetDimensionsFromAppliedDeliveryChallan(ItemJnlLine, AppliedDeliveryChallan);
                                if ItemJnlLine."Posting Date" < ItemLedgerEntry."Posting Date" then
                                    Error(ReceiptDateErr, ItemJnlLine."Posting Date", ItemLedgerEntry."Posting Date");

                                Item.Get(ItemJnlLine."Item No.");
                                OldReservEntry.CalcSums("Qty. to Invoice (Base)");

                                if ItemLedgerEntry."Remaining Quantity" <> 0 then
                                    if (Abs(OldReservEntry."Qty. to Invoice (Base)") <> Abs(ItemLedgerEntry."Remaining Quantity")) and
                                       (Item."Item Tracking Code" <> '')
                                    then
                                        if RemQtytoPost > Abs(OldReservEntry."Qty. to Invoice (Base)") then begin
                                            RemQtytoPost -= Abs(OldReservEntry."Qty. to Invoice (Base)");
                                            ItemJnlLine.Validate(Quantity, Abs(OldReservEntry."Qty. to Invoice (Base)"));
                                        end else begin
                                            ItemJnlLine.Validate(Quantity, RemQtytoPost);
                                            Completed := true;
                                        end
                                    else
                                        if RemQtytoPost > ItemLedgerEntry."Remaining Quantity" then begin
                                            RemQtytoPost -= ItemLedgerEntry."Remaining Quantity";
                                            ItemJnlLine.Validate(Quantity, ItemLedgerEntry."Remaining Quantity");
                                        end else begin
                                            ItemJnlLine.Validate(Quantity, RemQtytoPost);
                                            Completed := true;
                                        end;

                                if (ItemLedgerEntry."Lot No." = '') and (ItemLedgerEntry."Serial No." = '') then
                                    ItemJnlLine.Validate("Applies-to Entry", ItemLedgerEntry."Entry No.");

                                ItemJnlLine.Validate("Unit Cost", ProdOrderComp."Unit Cost");
                                ItemJnlLine."External Document No." := Purchline."Vendor Shipment No.";
                                ItemJnlLine."Location Code" := SubOrderCompVend."Vendor Location";
                                ItemJnlLine."Source Code" := SourceCodeSetup."Consumption Journal";
                                ItemJnlLine."Gen. Bus. Posting Group" := ProdOrder."Gen. Bus. Posting Group";
                                ItemJnlLine."Gen. Prod. Posting Group" := CompItem."Gen. Prod. Posting Group";

                                if Item."Item Tracking Code" <> '' then begin
                                    Inbound := true;
                                    ItemTrackingCode.Code := Item."Item Tracking Code";
                                    ItemTrackingManagement.GetItemTrackingSetup(
                                        ItemTrackingCode,
                                        ItemJnlLine."Entry Type",
                                        Inbound,
                                        ItemTrackingSetup);
                                    SNRequired := ItemTrackingSetup."Serial No. Required";
                                    LotRequired := ItemTrackingSetup."Lot No. Required";
                                    SNInfoRequired := ItemTrackingSetup."Serial No. Info Required";
                                    LotInfoRequired := ItemTrackingSetup."Lot No. Info Required";

                                    CheckTrackingLine := (SNRequired = false) and (LotRequired = false);
                                    QuantitySent := 0;

                                    if CheckTrackingLine then
                                        CheckTrackingLine := GetTrackingQuantitiesVend(
                                            AppliedDeliveryChallan,
                                            0,
                                            ItemJnlLine.Quantity,
                                            QuantitySent,
                                            TypeQty::RejectCE);
                                end else
                                    CheckTrackingLine := false;

                                TrackingQtyToHandle := 0;
                                TrackingQtyHandled := 0;

                                if CheckTrackingLine then begin
                                    GetTrackingQuantitiesVend(
                                        AppliedDeliveryChallan,
                                        1,
                                        TrackingQtyToHandle,
                                        TrackingQtyHandled,
                                        TypeQty::RejectCE);
                                    if ((TrackingQtyHandled + TrackingQtyToHandle) <> ItemJnlLine.Quantity) or
                                       (TrackingQtyToHandle <> ItemJnlLine.Quantity)
                                    then
                                        Error(TrackingQtyMatchErr, ItemJnlLine.FieldCaption(Quantity));
                                end;

                                if Item."Item Tracking Code" <> '' then
                                    TransferTrackingToItemJnlLineV(
                                        AppliedDeliveryChallan,
                                        ItemJnlLine,
                                        ItemJnlLine.Quantity,
                                        0,
                                        ItemLedgerEntry,
                                        TypeQty::RejectCE);

                                ItemJnlPostLine.Run(ItemJnlLine);
                            end;
                        until (ItemLedgerEntry.Next() = 0) or Completed;
                AppliedDeliveryChallan."Qty. to Return (C.E.)" := 0;
                AppliedDeliveryChallan.Modify();          
            until AppliedDeliveryChallan.Next() = 0;  <-- ADD Event after this Line

           //AddNewEvent 
          OnAfterAppliedDeliveryChallan(Completed,RemQtytoPost,TotalQtyToPost,ProdOrderComp) - <-- ADD NEW EVENT

        SubOrderCompVend."Qty. to Return (C.E.)" := 0;
        SubOrderCompVend.Modify();
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44660.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 44657.
