### ISSUE TITLE
[Event Parameter Change] Codeunit 80 "Sales-Post" - procedure UpdateShippingNo - Event OnAfterUpdateShippingNo

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19428]
We would like the parameter-/s PreviewMode, ModifyHeader added to the following event.

Codeunit 80 "Sales-Post" - procedure UpdateShippingNo - Event OnAfterUpdateShippingNo

Original:

```
OnAfterUpdateShippingNo(SalesHeader);

[IntegrationEvent(false, false)]
    local procedure OnAfterUpdateShippingNo(var SalesHeader: Record "Sales Header")
    begin
    end;
```

Change:

```
OnAfterUpdateShippingNo(SalesHeader, PreviewMode, ModifyHeader);

[IntegrationEvent(false, false)]
    local procedure OnAfterUpdateShippingNo(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean; var ModifyHeader: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44362.
