### ISSUE TITLE
[Event Request] - Codeunit 6648 CopyItemChargeAssgnt

### ISSUE THREAD

**Issue by sarachalaca** [microsoft/ALAppExtensions#19430]
In order to be able to change some filters on PurchLine2 we ask for the following event:

Event Definition:

[IntegrationEvent(false, false)] 
OnCopyItemChargeAssgntOnBeforeFindPurchLine2(var PurchLine2: Record "Purchase Line"; var ItemChargeAssgntPurch2: Record "Item Charge Assignment (Purch)");
begin
end;

Current Code:

local procedure CopyItemChargeAssgnt(PurchOrderLine: Record "Purchase Line"; ReturnShptLine: Record "Return Shipment Line"; QtyToAssign: Decimal; QtyFactor: Decimal)
    var
        ReturnShptLine2: Record "Return Shipment Line";
        PurchLine2: Record "Purchase Line";
        ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)";
        ItemChargeAssgntPurch2: Record "Item Charge Assignment (Purch)";
        InsertChargeAssgnt: Boolean;
    begin
        with PurchOrderLine do begin
            ItemChargeAssgntPurch.SetRange("Document Type", "Document Type");
            (...)
	    if ItemChargeAssgntPurch2."Applies-to Doc. Type" = "Document Type" then begin
                ItemChargeAssgntPurch2."Applies-to Doc. Type" := PurchLine2."Document Type";
                ItemChargeAssgntPurch2."Applies-to Doc. No." := PurchLine2."Document No.";
                ReturnShptLine2.SetCurrentKey("Return Order No.", "Return Order Line No.");
                ReturnShptLine2.SetRange("Return Order No.", ItemChargeAssgntPurch."Applies-to Doc. No.");
                ReturnShptLine2.SetRange("Return Order Line No.", ItemChargeAssgntPurch."Applies-to Doc. Line No.");
                ReturnShptLine2.SetFilter(Quantity, '<>0');
                if ReturnShptLine2.FindFirst() then begin
                    PurchLine2.SetCurrentKey("Document Type", "Receipt No.", "Receipt Line No.");
                    PurchLine2.SetRange("Document Type", PurchLine2."Document Type"::"Credit Memo");
                    PurchLine2.SetRange("Return Shipment No.", ReturnShptLine2."Document No.");
                    PurchLine2.SetRange("Return Shipment Line No.", ReturnShptLine2."Line No.");
                    if PurchLine2.Find('-') and (PurchLine2.Quantity <> 0) then
                    (...)

Sugested Code:

local procedure CopyItemChargeAssgnt(PurchOrderLine: Record "Purchase Line"; ReturnShptLine: Record "Return Shipment Line"; QtyToAssign: Decimal; QtyFactor: Decimal)
    var
        ReturnShptLine2: Record "Return Shipment Line";
        PurchLine2: Record "Purchase Line";
        ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)";
        ItemChargeAssgntPurch2: Record "Item Charge Assignment (Purch)";
        InsertChargeAssgnt: Boolean;
		IsHandled: Boolean;
    begin
        with PurchOrderLine do begin
            ItemChargeAssgntPurch.SetRange("Document Type", "Document Type");
            (...)
	    if ItemChargeAssgntPurch2."Applies-to Doc. Type" = "Document Type" then begin
                ItemChargeAssgntPurch2."Applies-to Doc. Type" := PurchLine2."Document Type";
                ItemChargeAssgntPurch2."Applies-to Doc. No." := PurchLine2."Document No.";
                ReturnShptLine2.SetCurrentKey("Return Order No.", "Return Order Line No.");
                ReturnShptLine2.SetRange("Return Order No.", ItemChargeAssgntPurch."Applies-to Doc. No.");
                ReturnShptLine2.SetRange("Return Order Line No.", ItemChargeAssgntPurch."Applies-to Doc. Line No.");
                ReturnShptLine2.SetFilter(Quantity, '<>0');
                if ReturnShptLine2.FindFirst() then begin
                    PurchLine2.SetCurrentKey("Document Type", "Receipt No.", "Receipt Line No.");
                    PurchLine2.SetRange("Document Type", PurchLine2."Document Type"::"Credit Memo");
                    PurchLine2.SetRange("Return Shipment No.", ReturnShptLine2."Document No.");
                    PurchLine2.SetRange("Return Shipment Line No.", ReturnShptLine2."Line No.");
                    **OnCopyItemChargeAssgntOnBeforeFindPurchLine2(PurchLine2,ItemChargeAssgntPurch2);**
                    if PurchLine2.Find('-') and (PurchLine2.Quantity <> 0) then
                        (...)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44362.
