### ISSUE TITLE
[Event Request] - Codeunit 6648 in CopyItemChargeAssgnt (2)

### ISSUE THREAD

**Issue by sarachalaca** [microsoft/ALAppExtensions#19432]
We need to fill some more fields in ItemChargeAssgntPurch2 var:

Event Definition:
[IntegrationEvent(false, false)] 
OnCopyItemChargeAssgntOnAfterFind(var PurchLine2: Record "Purchase Line"; var ItemChargeAssgntPurch2: Record "Item Charge Assignment (Purch)");
begin
end;

Current Code:

local procedure CopyItemChargeAssgnt(PurchOrderLine: Record "Purchase Line"; ReturnShptLine: Record "Return Shipment Line"; QtyToAssign: Decimal; QtyFactor: Decimal)
    var
        ReturnShptLine2: Record "Return Shipment Line";
        PurchLine2: Record "Purchase Line";
        ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)";
        ItemChargeAssgntPurch2: Record "Item Charge Assignment (Purch)";
        InsertChargeAssgnt: Boolean;
    begin
        with PurchOrderLine do begin
            ItemChargeAssgntPurch.SetRange("Document Type", "Document Type");
            ItemChargeAssgntPurch.SetRange("Document No.", "Document No.");
            ItemChargeAssgntPurch.SetRange("Document Line No.", "Line No.");
            if ItemChargeAssgntPurch.Find('-') then
            (...)
            
                    if PurchLine2.Find('-') and (PurchLine2.Quantity <> 0) then
                        ItemChargeAssgntPurch2."Applies-to Doc. Line No." := PurchLine2."Line No."
                    else
                        InsertChargeAssgnt := false;
                end else
                    InsertChargeAssgnt := false;
            end;
        end;
    (...)

Sugested code:

    local procedure CopyItemChargeAssgnt(PurchOrderLine: Record "Purchase Line"; ReturnShptLine: Record "Return Shipment Line"; QtyToAssign: Decimal; QtyFactor: Decimal)
    var
        ReturnShptLine2: Record "Return Shipment Line";
        PurchLine2: Record "Purchase Line";
        ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)";
        ItemChargeAssgntPurch2: Record "Item Charge Assignment (Purch)";
        InsertChargeAssgnt: Boolean;
    begin
        with PurchOrderLine do begin
            ItemChargeAssgntPurch.SetRange("Document Type", "Document Type");
            ItemChargeAssgntPurch.SetRange("Document No.", "Document No.");
            ItemChargeAssgntPurch.SetRange("Document Line No.", "Line No.");
            if ItemChargeAssgntPurch.Find('-') then
            (...)

                    if PurchLine2.Find('-') and (PurchLine2.Quantity <> 0) then **begin**
                        **OnCopyItemChargeAssgntOnAfterFind(PurchLine2: Record "Purchase Line"; ItemChargeAssgntPurch2: Record "Item Charge Assignment (Purch)");**
                        ItemChargeAssgntPurch2."Applies-to Doc. Line No." := PurchLine2."Line No.";
                    **end** else
                        InsertChargeAssgnt := false;
                end else
                    InsertChargeAssgnt := false;
            end;
        end;
    (...)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44362.
