### ISSUE TITLE
[Event Request] - Codeunit 74 CopyItemChargeAssgnt (2)

### ISSUE THREAD

**Issue by sarachalaca** [microsoft/ALAppExtensions#19438]
Event Definition:
[IntegrationEvent(false, false)] 
OnCopyItemChargeAssgntOnAfterFind(var PurchLine2: Record "Purchase Line"; var ItemChargeAssgntPurch2: Record "Item Charge Assignment (Purch)");
begin
end;

Current Code:

    local procedure CopyItemChargeAssgnt(PurchOrderLine: Record "Purchase Line"; ReturnShptLine: Record "Return Shipment Line"; QtyToAssign: Decimal; QtyFactor: Decimal)
    var
    (...)
    begin
        with PurchOrderLine do begin
            ItemChargeAssgntPurch.SetRange("Document Type", "Document Type");
            ItemChargeAssgntPurch.SetRange("Document No.", "Document No.");
            ItemChargeAssgntPurch.SetRange("Document Line No.", "Line No.");
            if ItemChargeAssgntPurch.Find('-') then
            (...)
            
 		if ItemChargeAssgntPurch2."Applies-to Doc. Type" = "Document Type" then begin
                	ItemChargeAssgntPurch2."Applies-to Doc. Type" := PurchLine2."Document Type";
                        ItemChargeAssgntPurch2."Applies-to Doc. No." := PurchLine2."Document No.";
                        PurchRcptLine2.SetCurrentKey("Order No.", "Order Line No.");
                        PurchRcptLine2.SetRange("Order No.", ItemChargeAssgntPurch."Applies-to Doc. No.");
                        PurchRcptLine2.SetRange("Order Line No.", ItemChargeAssgntPurch."Applies-to Doc. Line No.");
                        PurchRcptLine2.SetRange(Correction, false);
                        PurchRcptLine2.SetFilter(Quantity, '<>0');
                        if PurchRcptLine2.FindFirst() then begin
                        	PurchLine2.SetCurrentKey("Document Type", "Receipt No.", "Receipt Line No.");
                                PurchLine2.SetRange("Document Type", PurchLine2."Document Type"::Invoice);
                                PurchLine2.SetRange("Receipt No.", PurchRcptLine2."Document No.");
                                PurchLine2.SetRange("Receipt Line No.", PurchRcptLine2."Line No.");
                                if PurchLine2.Find('-') and (PurchLine2.Quantity <> 0) then
                                	ItemChargeAssgntPurch2."Applies-to Doc. Line No." := PurchLine2."Line No."
                                else
                                	InsertChargeAssgnt := false;
                                    end else
                                        InsertChargeAssgnt := false;
                                end;
							
Suggested code:

    
    local procedure CopyItemChargeAssgnt(PurchOrderLine: Record "Purchase Line"; PurchRcptLine: Record "Purch. Rcpt. Line"; QtyToAssign: Decimal; QtyFactor: Decimal)
    var
    (...)
    begin
        with PurchOrderLine do begin
            ItemChargeAssgntPurch.SetRange("Document Type", "Document Type");
            ItemChargeAssgntPurch.SetRange("Document No.", "Document No.");
            ItemChargeAssgntPurch.SetRange("Document Line No.", "Line No.");
            if ItemChargeAssgntPurch.Find('-') then
            (...)
 		if ItemChargeAssgntPurch2."Applies-to Doc. Type" = "Document Type" then begin
                	ItemChargeAssgntPurch2."Applies-to Doc. Type" := PurchLine2."Document Type";
                        ItemChargeAssgntPurch2."Applies-to Doc. No." := PurchLine2."Document No.";
                        PurchRcptLine2.SetCurrentKey("Order No.", "Order Line No.");
                        PurchRcptLine2.SetRange("Order No.", ItemChargeAssgntPurch."Applies-to Doc. No.");
                        PurchRcptLine2.SetRange("Order Line No.", ItemChargeAssgntPurch."Applies-to Doc. Line No.");
                        PurchRcptLine2.SetRange(Correction, false);
                        PurchRcptLine2.SetFilter(Quantity, '<>0');
                        if PurchRcptLine2.FindFirst() then begin
                        	PurchLine2.SetCurrentKey("Document Type", "Receipt No.", "Receipt Line No.");
                                PurchLine2.SetRange("Document Type", PurchLine2."Document Type"::Invoice);
                                PurchLine2.SetRange("Receipt No.", PurchRcptLine2."Document No.");
                                PurchLine2.SetRange("Receipt Line No.", PurchRcptLine2."Line No.");
                                if PurchLine2.Find('-') and (PurchLine2.Quantity <> 0) then begin
 				        **OnCopyItemChargeAssgntOnAfterFind(PurchLine2, ItemChargeAssgntPurch2);**
                                	ItemChargeAssgntPurch2."Applies-to Doc. Line No." := PurchLine2."Line No."
                                end else
                                	InsertChargeAssgnt := false;
                                    end else
                                        InsertChargeAssgnt := false;
                                end;
    (...)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44362.
