### ISSUE TITLE
[Event Request ] Codeunit 1535 Approvals Mgt. - PrePostApprovalCheckSales procedure, change event subscriber behaviour

### ISSUE THREAD

**Issue by maksym-ch** [microsoft/ALAppExtensions#19433]
Hi guys, according to our business needs we are going to override logic in PrePostApprovalCheckSales function by using event subscriber for OnBeforePrePostApprovalCheckSales event.

```
procedure PrePostApprovalCheckSales(var SalesHeader: Record "Sales Header"): Boolean
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePrePostApprovalCheckSales(SalesHeader, IsHandled);
        if IsHandled then
            exit;

        if IsSalesHeaderPendingApproval(SalesHeader) then
            Error(SalesPrePostCheckErr, SalesHeader."Document Type", SalesHeader."No.");

        exit(true);
    end;
```

We have figured out the following if use the mentioned subscriber and put IsHandled = true, Business Central stops positng process as this function returns false. To resume posting function should return true.
We noticed that same issue with the same request was raised some time ago https://github.com/microsoft/ALAppExtensions/issues/12250.

Thus, we suggest to this function in the following way:
```
procedure PrePostApprovalCheckSales(var SalesHeader: Record "Sales Header"): Boolean
    var
        Result: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePrePostApprovalCheckSales(SalesHeader, Result, IsHandled);
        if IsHandled then
            exit(Result);

        if IsSalesHeaderPendingApproval(SalesHeader) then
            Error(SalesPrePostCheckErr, SalesHeader."Document Type", SalesHeader."No.");

        exit(true);
    end;
```
For Purchase, we already have the similar functionality:

```
    procedure PrePostApprovalCheckPurch(var PurchaseHeader: Record "Purchase Header") Result: Boolean
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePrePostApprovalCheckPurch(PurchaseHeader, Result, IsHandled);
        if IsHandled then
            exit(Result);

        if IsPurchaseHeaderPendingApproval(PurchaseHeader) then
            Error(PurchPrePostCheckErr, PurchaseHeader."Document Type", PurchaseHeader."No.");

        exit(true);
    end;
```
this modification will allow use customized check and post sales document

Thank you in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44362.
