### ISSUE TITLE
[Event Parameter Change] Codeunit 333 "Req. Wksh.-Make Order" - procedure InsertHeader - Event OnBeforePurchOrderHeaderInsert

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19449]
We would like the parameter-/s ReceiveDateReq added to the following event.

Codeunit 333 "Req. Wksh.-Make Order" - procedure InsertHeader - Event OnBeforePurchOrderHeaderInsert

Original:

```
OnBeforePurchOrderHeaderInsert(PurchOrderHeader, ReqLine2);

[IntegrationEvent(false, false)]
local procedure OnBeforePurchOrderHeaderInsert(var PurchaseHeader: Record "Purchase Header"; RequisitionLine: Record "Requisition Line")
begin
end;
```

Change:

```
OnBeforePurchOrderHeaderInsert(PurchOrderHeader, ReqLine2, ReceiveDateReq); // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnBeforePurchOrderHeaderInsert(var PurchaseHeader: Record "Purchase Header"; RequisitionLine: Record "Requisition Line"; var ReceiveDateReq: Date) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44362.
