### ISSUE TITLE
Bug in Contoso Coffee Demo

### ISSUE THREAD

**Issue by stephanweidmann** [microsoft/ALAppExtensions#19448]
In Table    https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/ContosoCoffeeDemoDataset/app/Tables/ManufacturingDemoDataSetup.Table.al,  
several field length are to short, 

        field(31; "Retail Code"; code[10])
        {
            DataClassification = CustomerContent;
            Caption = 'Retail - Gen. Prod. Posting Group';
            TableRelation = "Gen. Product Posting Group";
        }
-> should be length 20, for example.

Problem arises, if a customer has created a record with length 15, and renames it, there will be an error.

(
There hopefully will be some kind of automatic check after so many years to prevent this errors.
https://github.com/microsoft/AL/issues/4493
)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46387.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 46565.
