### ISSUE TITLE
[Event Parameter Change] Codeunit 333 "Req. Wksh.-Make Order" - procedure Code - Event OnAfterCode

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19450]
We would like the parameter-/s PrintPurchOrders added to the following event.

Codeunit 333 "Req. Wksh.-Make Order" - procedure Code - Event OnAfterCode

Original:

```
OnAfterCode(ReqLine, OrderLineCounter, OrderCounter);

[IntegrationEvent(false, false)]
local procedure OnAfterCode(var RequisitionLine: Record "Requisition Line"; OrderLineCounter: Integer; OrderCounter: Integer)
begin
end;
```

Change:

```
OnAfterCode(ReqLine, OrderLineCounter, OrderCounter, PrintPurchOrders); // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnAfterCode(var RequisitionLine: Record "Requisition Line"; OrderLineCounter: Integer; OrderCounter: Integer; PrintPurchOrders: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44362.
