### ISSUE TITLE
[Extensibility Enhancement] "Home Page" Field in "Base Application"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#19466]
There has been an issue regarding the different length of the the HomePage Field in the Base Application.
https://github.com/microsoft/ALAppExtensions/issues/4753

Maybe you could add new Field for the Domain, that has the same length everywhere and that also supports the maximum length of domains (255 octets/characters)
See [RFC2181: Clarifications to the DNS Specification](https://www.rfc-editor.org/rfc/rfc2181)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14079.
