### ISSUE TITLE
[Event Parameter Change] Table 246 "Requisition Line" - Trigger OnValidate Location Code - Event OnValidateLocationCodeOnBeforeGetDefaultBin

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19473]
We would like the parameter-/s CurrFieldNo added to the following event.

Table 246 "Requisition Line" - Trigger OnValidate Location Code - Event OnValidateLocationCodeOnBeforeGetDefaultBin

Original:

```
OnValidateLocationCodeOnBeforeGetDefaultBin(Rec, ShouldGetDefaultBin, Location);

[IntegrationEvent(false, false)]
    local procedure OnValidateLocationCodeOnBeforeGetDefaultBin(RequisitionLine: Record "Requisition Line"; var ShouldGetDefaultBin: Boolean; Location: Record Location)
    begin
    end;
```

Change:

```
OnValidateLocationCodeOnBeforeGetDefaultBin(Rec, ShouldGetDefaultBin, Location, CurrFieldNo);

[IntegrationEvent(false, false)]
    local procedure OnValidateLocationCodeOnBeforeGetDefaultBin(RequisitionLine: Record "Requisition Line"; var ShouldGetDefaultBin: Boolean; Location: Record Location; CurrFieldNo: Integer)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44362.
