### ISSUE TITLE
 [Scope Change] table 55 "Invoice Posting Buffer".PadField #14122 

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#19478]
#14122 was marked as [ships-in-future-update] but meanwhile 2 major version were released and the method `PadField` is still `local`. Will it be changed?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
