### ISSUE TITLE
[Event Parameter Change] Codeunit 99000813 "Carry Out Action" - Procedure PrintPurchaseOrder - Event OnBeforePrintPurchaseOrder

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19487]
We would like the parameter-/s PrintOrder added to the following event.

Codeunit 99000813 "Carry Out Action" - Procedure PrintPurchaseOrder - Event OnBeforePrintPurchaseOrder

Original:

```
Codeunit 99000813 - Carry Out Action - procedure PrintPurchaseOrder - event OnBeforePrintPurchaseOrder

OnBeforePrintPurchaseOrder(PurchHeader2, IsHandled);

[IntegrationEvent(false, false)]
local procedure OnBeforePrintPurchaseOrder(var PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
begin
end;
```

Change:

```
OnBeforePrintPurchaseOrder(PurchHeader2, IsHandled, PrintOrder); // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnBeforePrintPurchaseOrder(var PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean; PrintOrder: Boolean) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44362.
