### ISSUE TITLE
[Access Request] codeunit 419 "File Management" - CombinePath

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#19488]
Could please remove the scope `OnPrem` of the procedure `CombinePath`?
Or is there any other DotNet Wrapper Codeunit to combine a path?
```al
[Scope('OnPrem')]
    procedure CombinePath(BasePath: Text; Suffix: Text): Text
    begin
        exit(PathHelper.Combine(BasePath, Suffix));
    end;
```

**Comment by darjoo** [comment]
@pri-kise what is the use-case for this? On SaaS at least, there shouldn't be a reason for working with paths.

**Comment by pri-kise** [comment]
@darjoo we want provide specific solutions to our customers with the concept of a "local BC Agent" (https://github.com/microsoft/BCTech/tree/master/samples/BCAgent), where we wanna provide the ability to store some files on specific network paths.
And to avoid simple string concatenation we would like to use CombinePath to prepare the path on the BC (AL) side and keeping the agent very ligthweight.
And to avoid a target OnPrem on the app.json, we would like to use this procedure with an app with target Cloud.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44655.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 45270.
