### ISSUE TITLE
[Event Request] Codeunit 5812 "Calculate Standard Cost"

### ISSUE THREAD

**Issue by fekramer** [microsoft/ALAppExtensions#19496]
In Order to Calculate Production Standard Cost I need to overrule Parameters on Items before further calculating.
I would like suggest following new Event Subscriber:
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/24778982/181430824-9961cfcb-29a3-45e0-91be-511c43697c57.png">

Beside this Request it could be a question how the existing Event "OnAfterSetProperties" should work with the Parameters.
All internal Parameters in the CU were already set and the New... Parameters will be respected only partially.
For Example to change the Parameter NewStdCostWkshName will have no effect while changing Parameter NewUseAssemblyList will confuse on further processing because it is maybe changed in procedure "CalcItem" but not respected in procedure in "CalcItem**s**"
If you like to change the Parameters in the existing OnAfterSetproperties Event to the internal variables, this request would be obsolete. (but I think you have also to change the Code in procedure "CalcItem")

Best regards

New Code Sequence:

OnBeforeSetProperties(NewCalculationDate, NewCalcMultiLevel, NewUseAssemblyList, NewLogErrors, NewStdCostWkshName, NewShowDialog);

[IntegrationEvent(false, false)]
    local procedure OnBeforeSetProperties(var NewCalculationDate: Date; var NewCalcMultiLevel: Boolean; var NewUseAssemblyList: Boolean; var NewLogErrors: Boolean; var NewStdCostWkshName: Text[50]; var NewShowDialog: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44362.
