### ISSUE TITLE
[Exposure Request] codeunit 550 "VAT Rate Change Conversion" - WriteLogEntry

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19491]
Please make function WriteLogEntry in codeunit 550 "VAT Rate Change Conversion" externally available.

```
procedure WriteLogEntry(VATRateChangeLogEntry: Record "VAT Rate Change Log Entry")
begin
    with VATRateChangeLogEntry do begin
        if Converted then
            "Converted Date" := WorkDate
        else
            if Description = '' then
                Description := StrSubstNo(Text0009, VATRateChangeSetup.FieldCaption("Perform Conversion"));
        Insert;
    end;
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.

**Comment by AlexanderYakunin** [comment]
Already implemented
