### ISSUE TITLE
[Exposure Request] codeunit 550 "VAT Rate Change Conversion" - InitVATRateChangeLogEntry

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19492]
Please make function InitVATRateChangeLogEntry in codeunit 550 "VAT Rate Change Conversion" externally available.

```
procedure InitVATRateChangeLogEntryFromConfigTemplateLine(var VATRateChangeLogEntry: Record "VAT Rate Change Log Entry"; ConfigTemplateLine: Record "Config. Template Line")
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
