### ISSUE TITLE
Length of field City - Text30 is to short

### ISSUE THREAD

**Issue by rovelgoenne** [microsoft/ALAppExtensions#195]
Hi,

we want to transfer our solution into an extension. The field City (for example in Table 5050) is to short. German city names can be longer than 30 digit. We extend this field from Text30 to Text50. 

As far as I know a length change of a base application field is not possible. 

Is it possible to change the field length vom text30 to text50 in the base application?

Kind regards,
Reiner Ovelgoenne

**Comment by ikoletic** [comment]
We do not have plans to extend City text. If you feel strongly about this please make sure to add this as product suggestion on https://aka.ms/bcideas
