### ISSUE TITLE
Page 344 Navigate - New parameter to the Event OnAfterNavigateFindRecords

### ISSUE THREAD

**Issue by LubomirUrx** [microsoft/ALAppExtensions#19500]
Could you add the new parameter ExtDocNo to the Event OnAfterNavigateFindRecords?

New definition
```
[IntegrationEvent(true, false)]
local procedure OnAfterNavigateFindRecords(var DocumentEntry: Record "Document Entry"; DocNoFilter: Text; PostingDateFilter: Text; var 	NewSourceRecVar: Variant; ExtDocNo: Code[250])
begin
end;

```
Use
```
local procedure FindRecords()
...
OnAfterNavigateFindRecords(Rec, DocNoFilter, PostingDateFilter, NewSourceRecVar, ExtDocNo);
```
Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.
