### ISSUE TITLE
[Event Request] Codeunit 6620 Copy Document Mgt. CopySalesDocSalesLine OnBeforeFromSalesLineFind

### ISSUE THREAD

**Issue by sboeve** [Microsoft/ALAppExtensions#1950]
Hi,

We perform additional filtering of FromSalesLIne in the CopySalesDocSalesLine function within CopyDocument Mgt.  We would request that an event be added to allow for additional filtering of the record before the FromSalesLine records are found.

We would require a single parameter passed in by VAR - FromSalesLine

Example:
ItemChargeAssgntNextLineNo := 0;

With ToSalesHeader Do Begin
    FromSalesLine.RESET;
    …..
**** new event handler **** OnBeforeFromSalesLineFind(FromSalesLine);
   If FromSalesLine.FIND('-') THEN

Thank you!

**Comment by AlexanderYakunin** [comment]
We already have this event
OnCopySalesDocSalesLineOnAfterSetFilters(FromSalesHeader,FromSalesLine,ToSalesHeader);

Please use latest code base from Collaborate for your requests, seems you have old code.

**Comment by sboeve** [comment]
Hi,

Can you tell me where to get the Collaborate code?

Thanks!


Susan Boeve | Developer
p. 631.756.2700 x716
accessIT | contractERP

**Comment by AlexanderYakunin** [comment]
http://aka.ms/collaborate
