### ISSUE TITLE
Move (or Replicate) GetRfc1123DateTime() function to TypeHelper Codeunit

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#19503]
There is a function called GetRfc1123DateTime() in the following 2 codeunits, but neither function is accessible as both codeunits are marked as Internal...

     codeunit 9060 "Auth. Format Helper"
     codeunit 9044 "ABS Format Helper"

I need this functionality but as it uses is calls another function (FormatDateTime) which has a DotNet variable, I can not replicate these functions myself for an extension targeted for the "Cloud".

Can you move (or copy) the GetRfc1123DateTime() function to the TypeHelper codeunit so that we can use it too as it's needed for a the authorisation of a web service that I need to call.

**Comment by pri-kise** [comment]
@kmistrytnp you can solve this by using the following:

```al
    procedure GetRfc1123DateTime(MyDateTime: DateTime): Text
    begin
        exit(FormatDateTime(MyDateTime, 'R')); // https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings
    end;

    local procedure FormatDateTime(MyDateTime: DateTime; FormatSpecifier: Text): Text
    var
        TypeHelper: Codeunit "Type Helper";
    begin
        exit(TypeHelper.FormatDateTime(MyDateTime, FormatSpecifier, ''));
    end;
```
