### ISSUE TITLE
[Request-For-External] Report 94 "Close Income Statement" - CheckDimPostingRulesfrom

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19506]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

[Request-For-External] Report 94 Close Income Statement - Procedure CheckDimPostingRulesfrom Internal to Global
```
procedure CheckDimPostingRules(var SelectedDim: Record "Selected Dimension"): Text[1024]
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44906.
