### ISSUE TITLE
One time per second this exception raises. 

### ISSUE THREAD

**Issue by OlegLobakov** [microsoft/ALAppExtensions#19504]
![image](https://user-images.githubusercontent.com/34211051/181584632-ad4901d1-c1ff-4ed7-b786-ce06a690fb49.png)

**Comment by OlegLobakov** [comment]
Very hard to debug something.

**Comment by OlegLobakov** [comment]
Permissions is SUPER

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
