### ISSUE TITLE
[Exposure Request] codeunit 550 "VAT Rate Change Conversion" - IncludeLine

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19513]
Please make function IncludeLine externally available.

```
procedure IncludeLine(Type: Option " ","G/L Account",Item,Resource; No: Code[20]): Boolean
begin
    case Type of
        Type::"G/L Account":
            exit(IncludeGLAccount(No));
        Type::Item:
            exit(IncludeItem(No));
        Type::Resource:
            exit(IncludeRes(No));
    end;
    exit(true);
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
