### ISSUE TITLE
[Exposure Request] codeunit 550 "VAT Rate Change Conversion" - GetRoundingPrecision

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19511]
Please make function GetRoundingPrecision extenrally available.

```
procedure GetRoundingPrecision(CurrencyCode: Code[10]): Decimal
var
    Currency: Record Currency;
begin
    if CurrencyCode = '' then
        Currency.InitRoundingPrecision
    else
        Currency.Get(CurrencyCode);
    exit(Currency."Unit-Amount Rounding Precision");
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
