### ISSUE TITLE
Storage Service Authorization CreateAccountSAS() Error 403

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#19518]
Hello, 

I'm trying to use the ABS SAS Authorization from Codeunit "Storage Service Authorization" 

```
`SASServiceTypes.Add(Enum::"SAS Service Type"::Blob);
SASServiceTypes.Add(Enum::"SAS Service Type"::File);
SASServiceTypes.Add(Enum::"SAS Service Type"::Queue);
SASServiceTypes.Add(Enum::"SAS Service Type"::Table);

SASResourceTypes.Add(Enum::"SAS Resource Type"::Container);
SASResourceTypes.Add(Enum::"SAS Resource Type"::Object);
SASResourceTypes.Add(Enum::"SAS Resource Type"::Service);

SASPermissions.Add(Enum::"SAS Permission"::Read);
SASPermissions.Add(Enum::"SAS Permission"::Add);
SASPermissions.Add(Enum::"SAS Permission"::List);
SASPermissions.Add(Enum::"SAS Permission"::Create);
SASPermissions.Add(Enum::"SAS Permission"::Delete);
SASPermissions.Add(Enum::"SAS Permission"::Process);
SASPermissions.Add(Enum::"SAS Permission"::Update);
SASPermissions.Add(Enum::"SAS Permission"::Write);
 Authorization := StorageServiceAuthorization.CreateAccountSAS(<Access Key>, Enum::"Storage Service API Version"::"2020-10-02", SASServiceTypes, SASResourceTypes, SASPermissions, CreateDateTime(20220801D, 0T));`
```

But I get the error:
403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

Do I need to do something with the <Access Key>, like Base64 encode it or construct the signature like explained here https://docs.microsoft.com/en-us/rest/api/storageservices/create-account-sas#construct-the-signature-string ?

**Comment by Jupentti1** [comment]
Is there any update to this? We are also trying to get this working with no success. How about documentation for this feature? I think it was released already in [BC 19](https://docs.microsoft.com/en-us/dynamics365-release-plan/2021wave2/smb/dynamics365-business-central/module-integrate-azure-blob-service-rest-api).

**Comment by JulianTillmann** [comment]
any news?

**Comment by gntpet** [comment]
having the same issue as well

**Comment by mazhelez** [comment]
Hey @JulianTillmann

This issue somehow slipped under our radar, and we apologize for the delay.
We'll take a look and get back to you soon.

**Comment by JulianTillmann** [comment]
@mazhelez 
I no longer get the 403 error, but the CreateAccountSAS() function doesn't work. 

What would be the "signing key" here? 

![image](https://user-images.githubusercontent.com/35929603/204794458-1d9d4271-7062-4bda-a6e6-1e46d4b71180.png)

It sounds like you should use the signing key 1 or key 2, that would be the shared access key.

![image](https://user-images.githubusercontent.com/35929603/204794583-5ab3eb5a-4f40-4a26-a278-474188faa196.png)

But I don't understand what the advantage would be from using the shared access key authorization instead? 

and if it's the SASToken, why would I need to set the SASPermissions, SASResourceType, SASServiceTypes, etc. those are already declared in the SASToken itself

**Comment by JulianTillmann** [comment]
> Ideally, we might want to expose an authorization method that takes the whole SAS token (as generated in the azure portal, for instance) and not generate it ourselves.
> 
> Actually, the suggestion in my previous comment might not work as I just noticed the version used in the azure portal is always the latest (see versions [here](https://learn.microsoft.com/en-us/rest/api/storageservices/previous-azure-storage-service-versions)).

that would be the third option, that the "signing key"-parameter is not the "signing key" but instead the signature. But as you said, the azure portal is using the latest version, but BC only gives us one version option:
![image](https://user-images.githubusercontent.com/35929603/204795571-f0e88c39-1017-4212-9ea7-e8388896a683.png)

**Comment by mazhelez** [comment]
> What would be the "signing key" here?

The signing key is the storage access key (should be securely saved in a key vault, for instance).

> But I don't understand what the advantage would be from using the shared access key authorization instead?
These are different authorization methods. It's probably best explained [here](https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-requests-to-azure-storage).

> that would be the third option, that the "signing key"-parameter is not the "signing key" but instead the signature. But as you said, the azure portal is using the latest version, but BC only gives us one version option:

I meant something more like the following:
In _Storage Service Authorization_ we add:
```
procedure CreateAccountSAS(<SAS token as generated in azure portal and securely saved in a KV>)
...
```
As you said, everything (the version, the permissions, etc.) will be included in the SAS token itself.

**Comment by JulianTillmann** [comment]
@mazhelez 
The shared access key as "signing key" definately doesn't work, I already tested that with your colleagues Islam Bakr and Mohamad Vajid from support. They told me it should be the signature as far as they understand it. 

A solution using a pre-generated SAS-Token would be great, that's what I expected. I create a SAS token with an expiry date for exclusively the permissions needed and use it in BC.

**Comment by gntpet** [comment]
> If you can debug, can you verify the signature part is the same? Just make sure you use arguments (signing key, start and expiry datetime, etc).

It's not possible to debug it, since it's not allowed. 

![image](https://user-images.githubusercontent.com/16342128/204807604-0f23229f-391d-43f1-a2b1-62eaf9215c11.png)

**Comment by JesperSchulz** [comment]
We're seeing a rather large inflow of issues related to the Azure Blob Storage module of rather different nature. As this is a partner contributed module, which we haven't uptaken ourselves yet, this is a new situation for us and it requires a little more time than usual to give the needed support. We're currently working on improving our processes and at the same time we're evaluating, how we can make the current open-source model, where the support burden of partner-developed modules 100% falls on Microsoft, scalable.
I just wanted to reassure you, that we are still actively working on this support case and that we will provide a solution. Realistically though, we will not be able to deliver on this particular issue before January. My apologies for that.

I am in discussions about the debugging challenges too. We know what is needed to allow debugging of (most of) the system application, but like everything else, this needs to get prioritized against other work. However, I understand that this is a necessary capability, if we want partners to be able to support and help themselves. I'm very well aware of the importance here and will try to push for progress. An ETA however, cannot be given on this.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52444.

**Comment by darjoo** [comment]
Issue has now been fixed and planned for 21.4 release. The CreateAccountSAS will generate a usable signature for usage.

Side note: The signing key is the access key.

**Comment by JulianTillmann** [comment]
@darjoo 
sounds great, thank you very much :-)

but for me there's still a question and I don't know where I would need to ask it, so I'm doing it here: 
why I would use the SAS if I still need my access key?  

The shared access key is the master key for accessing the storage. If I only want to give the BC client limited access to my storage the process I would design would be:

1. create a SAS token (incl. permissions, start- /end date, IP-ranges etc.) in Azure Portal 

2. share the SAS Token with the BC client

**Comment by darjoo** [comment]
@JulianTillmann Yes, you can do that as well. The main reasons I'd think you'd use this is for generating short-lived and limited access tokens and avoid the situation where it expires and you have to manually update it. So it doesn't live for a long period of time, possibly minutes, just to run your action(s).

**Comment by JulianTillmann** [comment]
@darjoo 
How would I do that? There are only two options available on the Azure Storage SErvices Authorization right now: 
https://github.com/microsoft/ALAppExtensions/tree/main/Modules/System/Azure%20Storage%20Services%20Authorization

**Comment by darjoo** [comment]
@JulianTillmann 
Here is an example, it will create the Account SAS for authorization and list the blobs. The authorization will only last 5 minutes.
The AccessKey should stored in KeyVault and any procedures that get it through parameters should be set to NonDebuggable.

```
[NonDebuggable]
    procedure CreateAccountSASAndListBlob(AccessKey: Text)
    var
        TempABSContainerContent: Record "ABS Container Content" temporary;
        StorageServiceAuthorization: Codeunit "Storage Service Authorization";
        ABSBlobClient: Codeunit "ABS Blob Client";
        SASServiceTypes: List of [Enum "SAS Service Type"];
        SASResourceTypes: List of [Enum "SAS Resource Type"];
        SASPermissions: List of [Enum "SAS Permission"];
        Authorization: Interface "Storage Service Authorization";
        Expiry: DateTime;
    begin
        SASServiceTypes.Add(Enum::"SAS Service Type"::Blob);

        SASResourceTypes.Add(Enum::"SAS Resource Type"::Container);

        SASPermissions.Add(Enum::"SAS Permission"::Read);
        SASPermissions.Add(Enum::"SAS Permission"::List);

        Expiry := CurrentDateTime() + ((1000 * 60) * 5); // Expire in 5 minutes

        Authorization := StorageServiceAuthorization.CreateAccountSAS(AccessKey,
            Enum::"Storage Service API Version"::"2020-10-02",
            SASServiceTypes,
            SASResourceTypes,
            SASPermissions,
            Expiry);

        ABSBlobClient.Initialize(StorageAccountName, AzureBlobContainerName, Authorization, Enum::"Storage Service API Version"::"2020-10-02");
        ABSBlobClient.ListBlobs(TempABSContainerContent);
    end;
```

**Comment by darjoo** [comment]
You can chain one authorization to multiple actions with more permissions/resource types/service types and increasing expiry as needed.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 52442.

**Comment by JulianTillmann** [comment]
@darjoo 
but I would still need to create the SAS-token from inside BC and thus would need to store the access key there somewhere. 

What I'm talking about is just giving out the sas token when needed, that's much more secure.
