### ISSUE TITLE
[Extensibility Request] Table 156 "Resource" - Procedure from Local to Protected

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#19529]
Hello, we need the following currently Local procedure to be set as Protected for our Table extension. Can you please check this? Thank you!

    protected procedure TestNoEntriesExist(CurrentFieldName: Text[100])

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45057.
