### ISSUE TITLE
[Event Parameter Change] Codeunit 5815 Undo Sales Shipment Line - Procedure UpdateOrderLine - Event OnBeforeUpdateOrderLine

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19524]
We would like the parameter-/s TempGlobalItemLedgEntry added to the following event.

Codeunit 6638 "Sales-Get Return Receipts" - Procedure UpdateOrderLine - Event OnBeforeUpdateOrderLine

Original:

```
OnBeforeUpdateOrderLine(SalesShptLine, IsHandled);

[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateOrderLine(var SalesShptLine: Record "Sales Shipment Line"; var IsHandled: Boolean)
    begin
    end;
```

Change:

```
OnBeforeUpdateOrderLine(SalesShptLine, IsHandled, TempGlobalItemLedgEntry);

[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateOrderLine(var SalesShptLine: Record "Sales Shipment Line"; var IsHandled: Boolean; var TempGlobalItemLedgEntry: Record "Item Ledger Entry" temporary)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45914.
