### ISSUE TITLE
[Request for Protected]  Page 521 - Application Worksheet 

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#19522]
Dear ALAppExtensions team,

Through this issue we would like to request defining the following variables as protected:

```AL
var
    TempUnapplyItem: Record Item temporary;
    Apply: Codeunit "Item Jnl.-Post Line";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45057.
