### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - event OnBeforePostVendorEntry

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#19527]
Hello,

In https://github.com/microsoft/ALAppExtensions/issues/19354, we requested a new parameter IsHandled in event OnBeforePostVendorEntry.

```

OnBeforePostVendorEntry(GenJnlLine, PurchHeader, TotalPurchLine2, TotalPurchLineLCY2, PreviewMode, SuppressCommit, GenJnlPostLine, **IsHandled**); // <<NEW PARAMETER>>
        if IsHandled then // <<NEW PARAMETER>>
            GenJnlPostLine.RunWithCheck(GenJnlLine);
```
In this situation, the IsHandled variable is false at the beginning of the function PostVendorEntry. Now, the line  GenJnlPostLine.RunWithCheck(GenJnlLine); will be executed only if IsHandled is true. In case an event does not subscribe to OnBeforePostVendorEntry, IsHandled will remain false.

We would like to ask you to replace the parameter IsHandled with SkipPosting:

            OnBeforePostVendorEntry(GenJnlLine, PurchHeader, TotalPurchLine2, TotalPurchLineLCY2, PreviewMode, SuppressCommit, GenJnlPostLine, **SkipPosting**); // <<NEW PARAMETER>>
            if not SkipPosting then // <<NEW PARAMETER>>
                GenJnlPostLine.RunWithCheck(GenJnlLine);

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostVendorEntry(var GenJnlLine: Record "Gen. Journal Line"; var PurchHeader: Record "Purchase Header"; var TotalPurchLine: Record "Purchase Line"; var TotalPurchLineLCY: Record "Purchase Line"; PreviewMode: Boolean; CommitIsSupressed: Boolean; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; **var SkipPosting: Boolean**)
    begin
    end;

**Comment by AlexanderYakunin** [comment]
it is implemented this way, no need to change.

            IsHandled := false;
            OnBeforePostVendorEntry(GenJnlLine, PurchHeader, TotalPurchLine2, TotalPurchLineLCY2, PreviewMode, SuppressCommit, GenJnlPostLine, IsHandled);
            if not IsHandled then
                GenJnlPostLine.RunWithCheck(GenJnlLine);
