### ISSUE TITLE
[Event Request] codeunit 550 "VAT Rate Change Conversion" - OnBeforeUpdatePurchase

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19530]
Please add additional parameter to the event OnBeforeUpdatePurchase:

```
IsHandled := false;
OnBeforeUpdatePurchase(PurchaseHeader, VATRateChangeSetup, IsHandled);
if IsHandled then
    exit;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdatePurchase(var PurchaseHeader: Record "Purchase Header"; var VATRateChangeSetup: Record "VAT Rate Change Setup"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47182.
