### ISSUE TITLE
Add Parameter to the event OnAfterInvoicePostingBufferSetAmounts in CU80 Sales-Post

### ISSUE THREAD

**Issue by daryobahar** [microsoft/ALAppExtensions#19548]
In the paragraph below the line 
OnAfterInvoicePostingBufferSetAmounts(InvoicePostBuffer, SalesLine); 

needs to be modified as 
OnAfterInvoicePostingBufferSetAmounts(InvoicePostBuffer, SalesLine, SalesLineACY); 

Thank you for your close support.

Daryo Bahar
Infotek A.S.
=======================================================================

 OnBeforeInvoicePostingBufferSetAmounts(
          SalesLine, TempInvoicePostBuffer, InvoicePostBuffer,
          TotalVAT, TotalVATACY, TotalAmount, TotalAmountACY, TotalVATBase, TotalVATBaseACY);

        InvoicePostBuffer.SetAmounts(
          TotalVAT, TotalVATACY, TotalAmount, TotalAmountACY, SalesLine."VAT Difference", TotalVATBase, TotalVATBaseACY);

        **- OnAfterInvoicePostingBufferSetAmounts(InvoicePostBuffer, SalesLine);**
        **+ OnAfterInvoicePostingBufferSetAmounts(InvoicePostBuffer, SalesLine, SalesLineACY);**, 

        SalesAccount := GetSalesAccount(SalesLine, GenPostingSetup);

        OnFillInvoicePostingBufferOnBeforeSetAccount(SalesHeader, SalesLine, SalesAccount);

        InvoicePostBuffer.SetAccount(SalesAccount, TotalVAT, TotalVATACY, TotalAmount, TotalAmountACY);
        InvoicePostBuffer.UpdateVATBase(TotalVATBase, TotalVATBaseACY);
        InvoicePostBuffer."Deferral Code" := SalesLine."Deferral Code";
        OnAfterFillInvoicePostBuffer(InvoicePostBuffer, SalesLine, TempInvoicePostBuffer, SuppressCommit);
        UpdateInvoicePostBuffer(InvoicePostBuffer, false);

**Comment by RadoArvay** [comment]
I wanted to request/use it in the past as well. But if I may warn you there is a new posting functionality and the method `FillInvoicePostingBuffer` that contains this code you want to change is mark as `Obsolete`.

**Comment by daryobahar** [comment]
> I wanted to request/use it in the past as well. But if I may warn you there is a new posting functionality and the method `FillInvoicePostingBuffer` that contains this code you want to change is mark as `Obsolete`.

Thank you for the information. We are also in preparation to use the new posting routine, but until then if this event modification takes place our app will be functioning better with its current situation.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49880.
