### ISSUE TITLE
[EventRequests] Page "Workflow Response Options"

### ISSUE THREAD

**Issue by dennisroczek** [microsoft/ALAppExtensions#19554]
I do try to migrate old NAV2017 Code to BC20. We have expanded the "Approval Type" resp. "Approver Type" for a new system (based on the NAV2017 code).

My problem is: I do not get the old code using a page extension nicely in the page as some options are shown, although shouldn't have been shown or vise versa. :-(
I found a workaround, although this is quirks and unnecessary complex.

* Please provide an event in the end of the procedure SetVisibilityOptions() for hiding fields.
* Please mark the page as protected --> global var access!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48467.
