### ISSUE TITLE
[Event Request] table 36 "Sales Header" - OnCollectParamsInBufferForCreateDimSetOnBeforeInsertTempSalesLineInBuffer

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19555]
Please include sender in the Event OnCollectParamsInBufferForCreateDimSetOnBeforeInsertTempSalesLineInBuffer in table 36
```
[IntegrationEvent(true, false)]
local procedure OnCollectParamsInBufferForCreateDimSetOnBeforeInsertTempSalesLineInBuffer(var GenPostingSetup: Record "General Posting Setup"; var DefaultDimension: Record "Default Dimension")
begin
end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45720.
