### ISSUE TITLE
[Bug] CaptionClass doesn't work together with "ShowAsTree = true"

### ISSUE THREAD

**Issue by Mike-1984** [microsoft/ALAppExtensions#19557]
Hello colleagues,

When CaptionClass property is specified together with ShowAsTree = true, the very first column does not change the caption.
In the attached example you will find a simple application to reproduce the problem.

The page contains a repeater with "ShowAsTree = true" and 2 fields with CaptionClass peroperty defined.
The 2nd field works correctly, changing the caption of the field dynamically.
The 1st field has original caption. CaptionClass property had no effect on it

![image](https://user-images.githubusercontent.com/47153584/182140232-d3f0d00b-463b-442d-8e55-0eb2f8cb0bcf.png)

[CaptionClassBug.zip](https://github.com/microsoft/ALAppExtensions/files/9233544/CaptionClassBug.zip)

P.S. Tested on BC20 CU3

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22.0.47787.0.
