### ISSUE TITLE
[Event Parameter Change] Codeunit 80 Sales-Post - Event OnBeforeReturnRcptLineInsert

### ISSUE THREAD

**Issue by TriangleSPV** [microsoft/ALAppExtensions#19579]
We need that the event OnBeforeReturnRcptLineInsert of the codeunit 80 Sales-Post works equal than the OnBeforeSalesShptLineInsert, with the possibility to manipulate the Insert with a IsHandled variable.

    local procedure InsertReturnReceiptLine(ReturnRcptHeader: Record "Return Receipt Header"; SalesLine: Record "Sales Line"; CostBaseAmount: Decimal)
    var
        ReturnRcptLine: Record "Return Receipt Line";
        IsHandled: Boolean;  //NEW CODE
    begin
        IsHandled := false;  //NEW CODE
...............
        //OnBeforeReturnRcptLineInsert(ReturnRcptLine, ReturnRcptHeader, SalesLine, SuppressCommit, xSalesLine, TempSalesLineGlobal);      OLD CODE
        OnBeforeReturnRcptLineInsert(ReturnRcptLine, ReturnRcptHeader, SalesLine, SuppressCommit, xSalesLine, TempSalesLineGlobal, IsHandled);    //NEW CODE
        if IsHandled then    //NEW CODE
            exit;    //NEW CODE
        ReturnRcptLine.Insert(true);
        OnAfterReturnRcptLineInsert(
          ReturnRcptLine, ReturnRcptHeader, SalesLine, ItemLedgShptEntryNo, WhseShip, WhseReceive, SuppressCommit, SalesCrMemoHeader, TempWhseShptHeader, TempWhseRcptHeader);
    end;

OLD INTEGRATION EVENT:
    local procedure OnBeforeReturnRcptLineInsert(var ReturnRcptLine: Record "Return Receipt Line"; ReturnRcptHeader: Record "Return Receipt Header"; SalesLine: Record "Sales Line"; CommitIsSuppressed: Boolean; xSalesLine: record "Sales Line"; var TempSalesLineGlobal: record "Sales Line" temporary)

NEW INTEGRATION EVENT:
    local procedure OnBeforeReturnRcptLineInsert(var ReturnRcptLine: Record "Return Receipt Line"; ReturnRcptHeader: Record "Return Receipt Header"; SalesLine: Record "Sales Line"; CommitIsSuppressed: Boolean; xSalesLine: record "Sales Line"; var TempSalesLineGlobal: record "Sales Line" temporary; var IsHandled: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45169.
