### ISSUE TITLE
[Bug] "Service Line" - "LineRequiresShipmentOrReceipt" - "Qty. to Ship" on Type "Resource"

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#19570]
Hi,

we found a small bug in the service line.
In the case of type = Resource, the "Qty. to Ship" is not set correctly.

The problem can be solved as follows:

```
    local procedure LineRequiresShipmentOrReceipt(): Boolean
    var
        Location: Record Location;
    begin
        // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        if Type <> Type::Item then
            exit(false);
        // <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        if ("Document Type" <> "Document Type"::Order) or IsNonInventoriableItem() then
            exit(false);
        exit(Location.RequireReceive("Location Code") or Location.RequireShipment("Location Code"));
    end;
```

Only Items can be send to "Warehouse Shipment" / "Warehouse Receipt".

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
