### ISSUE TITLE
Table 5080 "To-do" - InsertTaskAndRelatedData

### ISSUE THREAD

**Issue by MrinalSingha** [microsoft/ALAppExtensions#19573]
Hi microsoft/ALAppExtensions

as follow-up of following request,
https://github.com/microsoft/ALAppExtensions/issues/19324

can you please add an additional parameter in the following procedure,

```
        OnAfterInsertTaskAndRelatedData(Task); //old
        OnAfterInsertTaskAndRelatedData(Rec, TaskNo); //new

```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertTaskAndRelatedData(var Task: Record "To-do"; TaskNo: Code[20])
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46955.
