### ISSUE TITLE
[Event Request] Table 81 Gen. Journal Line - Field Currency Code

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#19572]
Dear ALAppExtensions Team,

We would like to request the following change

    field(12; "Currency Code"; Code[10])
    {
        Caption = 'Currency Code';
        TableRelation = Currency;
  
        trigger OnValidate()
        var
            BankAcc: Record "Bank Account";
        begin
            if "Bal. Account Type" = "Bal. Account Type"::"Bank Account" then begin
                if BankAcc.Get("Bal. Account No.") and (BankAcc."Currency Code" <> '') then
                    BankAcc.TestField("Currency Code", "Currency Code");
            end;
            if "Account Type" = "Account Type"::"Bank Account" then begin
                if BankAcc.Get("Account No.") and (BankAcc."Currency Code" <> '') then
                    BankAcc.TestField("Currency Code", "Currency Code");
            end;
            if ("Recurring Method" in
                ["Recurring Method"::"B  Balance", "Recurring Method"::"RB Reversing Balance"]) and
               ("Currency Code" <> '')
            then
                Error(
                  Text001,
                  FieldCaption("Currency Code"), FieldCaption("Recurring Method"), "Recurring Method");
  
            if "Currency Code" <> '' then begin
                if ("Bal. Account Type" = "Bal. Account Type"::Employee) or ("Account Type" = "Account Type"::Employee) then
                    Error(OnlyLocalCurrencyForEmployeeErr);
                GetCurrency;
                if ("Currency Code" <> xRec."Currency Code") or
                   ("Posting Date" <> xRec."Posting Date") or
                   (CurrFieldNo = FieldNo("Currency Code")) or
                   ("Currency Factor" = 0)
                then
                    **//--> change request                    
                    OnUpdateCurrencyFactorOnBeforeGetExchangeRate(Rec, CurrExchRate);        
                    //<-- change request**            
                    "Currency Factor" :=
                      CurrExchRate.ExchangeRate("Posting Date", "Currency Code");
            end else
                "Currency Factor" := 0;
            Validate("Currency Factor");
  
            if not CustVendAccountNosModified then
                if ("Currency Code" <> xRec."Currency Code") and (Amount <> 0) then
                    PaymentToleranceMgt.PmtTolGenJnl(Rec);
        end;
    }

    [IntegrationEvent(false, false)]
    local procedure OnUpdateCurrencyFactorOnBeforeGetExchangeRate(GenJournalLine: Record "Gen. Journal Line"; var CurrExchRate: Record "Currency Exchange Rate")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45914.
