### ISSUE TITLE
Setting "resourceExposurePolicy" in "Email - SMTP API" app.json

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#19575]
To upgrade an Onprem customer from say 17.x to 20.x we need to have all the new 20.x apps available in a folder to publish/install them. Picking those new apps from downloads/DVD's and ZIPS from many publishers like Microsoft/Continia/To-Increase/Sana/TINX etc. is a tedious task prone to errors while we already have a complete 20.x.bacpac created with a devops pipeline which contains all the correct apps and versions needed for the 20.x upgraded customer database. With a https call we can download all the apps from a NST. Alas only one app is not so cooperative and that is "Email - SMTP API" 

Please add the following property:

    "resourceExposurePolicy":  {
                                   "allowDebugging":  true,
                                   "allowDownloadingSource":  true,
                                   "includeSourceInSymbolFile":  true
    }

**Comment by darjoo** [comment]
Looks like I missed adding that. Will do that. Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 44548.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 45119.
