### ISSUE TITLE
[Event Request] Table 246 Requisition Line - Field Currency Code

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#19576]
Dear ALAppExtensions Team,

We would like to request the following change

    field(29; "Currency Code"; Code[10])
    {
      Caption = 'Currency Code';
      TableRelation = Currency;
  
      trigger OnValidate()
      var
          Currency: Record Currency;
          CurrExchRate: Record "Currency Exchange Rate";
      begin
          Currency.Initialize("Currency Code");
          if "Currency Code" <> '' then begin
              TestField("Order Date");
              if PlanningResiliency then
                  CheckExchRate(Currency);
              **//--> change request                    
              OnUpdateCurrencyFactorOnBeforeGetExchangeRate(Rec, CurrExchRate);        
              //<-- change request**   
              Validate(
                "Currency Factor", CurrExchRate.ExchangeRate("Order Date", "Currency Code"));
          end else
              Validate("Currency Factor", 0);
  
          GetDirectCost(FieldNo("Currency Code"));
      end;
    }

    [IntegrationEvent(false, false)]
    local procedure OnUpdateCurrencyFactorOnBeforeGetExchangeRate(RequisitionLine: Record "Requisition Line"; var CurrExchRate: 
    Record "Currency Exchange Rate")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45914.
