### ISSUE TITLE
[CalcFormula Change request] Table 210 - "Job Journal Line" - Field 5468 "Reserved Qty. (Base)" 

### ISSUE THREAD

**Issue by cosmo-skol** [microsoft/ALAppExtensions#1957]
Hello AL-Team,

the property "CalcFormula" points to "Source Type" = 1011, but this table does not exist anymore (hasn't for a long time) and a quick search through all objects resulted in zero places, where a reservation entry with "Source Type" =  1011 is created.

On the other hand, code exists for a possible source from table 210 (Codeunit 99000830 - function "SignFactor").

Shouldn't the calcformula be 

-Sum("Reservation Entry"."Quantity (Base)" WHERE (Source ID=FIELD(Journal Template Name),Source Ref. No.=FIELD(Line No.),Source Type=CONST(**210**),Source Subtype=FIELD(Entry Type),Source Batch Name=FIELD(Journal Batch Name),Source Prod. Order Line=CONST(0),Reservation Status=CONST(Reservation)))

instead of

-Sum("Reservation Entry"."Quantity (Base)" WHERE (Source ID=FIELD(Journal Template Name),Source Ref. No.=FIELD(Line No.),Source Type=CONST(**1011**),Source Subtype=FIELD(Entry Type),Source Batch Name=FIELD(Journal Batch Name),Source Prod. Order Line=CONST(0),Reservation Status=CONST(Reservation)))

**Comment by AlexanderYakunin** [comment]
I agree, it will be fixed next week for 15.1 update

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
