### ISSUE TITLE
[Event Parameter Change] Table 330 Currency Exchange Rate - procedure FindCurrency

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#19578]
Dear ALAppExtensions Team,

We would like to request the following change

    procedure FindCurrency(Date: Date; CurrencyCode: Code[10]; CacheNo: Integer)
        var
            ShouldUseCache: Boolean;
        begin
            ShouldUseCache := (CurrencyCode2[CacheNo] = CurrencyCode) and (Date2[CacheNo] = Date);
            OnFindCurrencyOnAfterCalcShouldUseCache(Rec, CacheNo, ShouldUseCache);
            if ShouldUseCache then
                Rec := CurrencyExchRate2[CacheNo]
            else begin
                if Date = 0D then
                    Date := WorkDate;
                CurrencyExchRate2[CacheNo].SetRange("Currency Code", CurrencyCode);
                CurrencyExchRate2[CacheNo].SetRange("Starting Date", 0D, Date);
                **//--> change request
                OnFindCurrencyOnAfterCurrencyExchRate2SetFilters(Rec,CurrencyExchRate2[CacheNo], CurrencyCode, Date);
                //<-- change request**
                CurrencyExchRate2[CacheNo].FindLast();
                Rec := CurrencyExchRate2[CacheNo];
                CurrencyCode2[CacheNo] := CurrencyCode;
                Date2[CacheNo] := Date;
            end;
            OnAfterFindCurrency(Rec, CurrencyExchRate2, Date, CurrencyCode, CacheNo);
        end;

        [IntegrationEvent(false, false)]
        local procedure OnFindCurrencyOnAfterCurrencyExchRate2SetFilters(var CurrencyExchangeRate: Record "Currency Exchange Rate"; var CurrencyExchRate2: Record "Currency Exchange Rate"; 
        CurrencyCode: Code[10]; Date: Date)
        begin
        end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45914.
