### ISSUE TITLE
Table – 130 – Incoming Document

### ISSUE THREAD

**Issue by clausmacali** [microsoft/ALAppExtensions#1958]
[External] CreateGeneralJournalLineWithDataExchange() 
CreateGeneralJournalLineWithDataExchange is exposed as External and was available until the below version of Business Central. 
bcinsider.azurecr.io/bcsandbox:dk-ltsc2016 
Version: 13.4.27730.0-DK 
Platform: 13.0.27722.0 
Generic Tag: 0.0.9.1 
 
But in the Latest version of Business Central this function CreateGeneralJournalLineWithDataExchange is no longer available to be invoked externally from AL. 
bcinsider.azurecr.io/bcsandbox:dk-ltsc2019  
Version: 14.0.29523.0-DK 
Platform: 14.0.29501.0 
Generic Tag: 0.0.9.2  
Can you please check and make this function as external? Or Is there any alternative to this function? 
Thanks

**Comment by RomanZanizdra** [comment]
Hi clausmacali.
Unfortunately I'm going to return back to internal requested by you function. Looks like you should find another way of usage your functionality.
