### ISSUE TITLE
[Request-For-External] codeunit 5815 "Undo Sales Shipment Line" - GetCorrectionLineNov

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19586]
Hello, we need the following currently local procedure to be set to global. Can you please check this? Thank you!

[Request-For-External] codeunit 5815 "Undo Sales Shipment Line" - procedure from local to global
```
procedure GetCorrectionLineNo(SalesShptLine: Record "Sales Shipment Line") Result: Integer;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
