### ISSUE TITLE
codeunit 90 - procedure UpdatePurchOrderChargeAssgnt to Global

### ISSUE THREAD

**Issue by sarachalaca** [microsoft/ALAppExtensions#19582]
It is possible to change the local procedure UpdatePurchOrderChargeAssgnt from Codeunit 90 to global?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
