### ISSUE TITLE
[Extensibility Request] Page 397 "Sales Invoice Statistics" and Page 400 "Purchase Invoice Statistics" - Protected variable

### ISSUE THREAD

**Issue by deadmouse** [microsoft/ALAppExtensions#19583]
[Extensibility Request] **Page 397** "Sales Invoice Statistics" and **Page 400** "Purchase Invoice Statistics" for variable "AmountInclVAT"

```
protected var
    AmountInclVAT: Decimal;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45057.
