### ISSUE TITLE
[Event Parameter Change] Page 682 Schedule a Report - Procedure SetParameters - Event OnGetReportDescription

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19598]
We would like the parameter/-s JobQueueEntry and Sender added to the following event.

Page 682 Schedule a Report - Procedure SetParameters - Event OnGetReportDescription

Original:

```
OnGetReportDescription(ReportDescription, RequestPageXml, ReportId, IsHandled)

[IntegrationEvent(false, false)]
    local procedure OnGetReportDescription(var ReportDescription: Text[250]; RequestPageXml: Text; ReportId: Integer; var IsHandled: Boolean)
    begin
    end;
```

Change:

```
Added sender and Parameter JobQueueEntry (Rec)
OnGetReportDescription(ReportDescription, RequestPageXml, ReportId, IsHandled, Rec);

[IntegrationEvent(true, false)]
    local procedure OnGetReportDescription(var ReportDescription: Text[250]; RequestPageXml: Text; ReportId: Integer; var IsHandled: Boolean; var JobQueueEntry: Record "Job Queue Entry")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
