### ISSUE TITLE
[Event Parameter Change] Report 94 Close Income Statement - Trigger OnPreReport - Event OnPreReportOnBeforeCheckDimPostingRules

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19594]
We would like the parameter/-s GenJnlLine added to the following event.

Report 94 Close Income Statement - Trigger OnPreReport - Event OnPreReportOnBeforeCheckDimPostingRules

Original:

```
OnPreReportOnBeforeCheckDimPostingRules(IsHandled, TempSelectedDim);

[IntegrationEvent(false, false)]
    local procedure OnPreReportOnBeforeCheckDimPostingRules(var IsHandled: Boolean; var TempSelectedDim: Record "Selected Dimension" temporary)
    begin
    end;
```

Change:

```
OnPreReportOnBeforeCheckDimPostingRules(IsHandled, TempSelectedDim, GenJnlLine);

[IntegrationEvent(false, false)]
    local procedure OnPreReportOnBeforeCheckDimPostingRules(var IsHandled: Boolean; var TempSelectedDim: Record "Selected Dimension" temporary; GenJnlLine: Record "Gen. Journal Line")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
