### ISSUE TITLE
OnCustomProcessing in CU1380, Batch Processing Mgt.

### ISSUE THREAD

**Issue by renebrummel** [Microsoft/ALAppExtensions#196]
In CU1380, Batch Processing Mgt. MS has created a great new event called OnCustomProcessing with a handled parameter.

My issue is that MS has used this event themselves in CU1371, Sales Batch Post Mgt. Rendering the event nearly completely useless since we cannot predict which subscription will be executed first and all events might set or reset the handled parameter in a different way.

I would like to propose MS either moves their code in function HandleOnCustomProcessing to a hook instead of an event subscriber or create a new event before the OnCustomProcessing event in CU1380.

Similar issues exist with the events OnVerifyRecord and OnBeforeBatchProcessing in CU1380.

**Comment by JesperSchulz** [comment]
This issue seems to have been resolved. Closing issue.
