### ISSUE TITLE
[Event Parameter Change] Codeunit 5763 Whse.-Post Shipment - procedure Code - event OnAfterPostWhseShipment

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19608]
We would like the parameter/-s SuppressCommit, IsHandled added to the following event.

Codeunit 5763 Whse.-Post Shipment - procedure Code - event OnAfterPostWhseShipment

Original:

```
Codeunit 5763 - Whse.-Post Shipment - procedure Code - event OnAfterPostWhseShipment

OnAfterPostWhseShipment(WhseShptHeader);

[IntegrationEvent(false, false)]
local procedure OnAfterPostWhseShipment(var WarehouseShipmentHeader: Record "Warehouse Shipment Header")
begin
end;
```

Change:

```
IsHandled := false; // <-- ADDED
OnAfterPostWhseShipment(WhseShptHeader, SuppressCommit, IsHandled); // <-- ADDED
if not IsHandled then begin // <-- ADDED
    Commit();
    PrintDocuments();
end; // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnAfterPostWhseShipment(var WarehouseShipmentHeader: Record "Warehouse Shipment Header"; SuppressCommit: Boolean; var IsHandled: Boolean) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
