### ISSUE TITLE
[Event Request] Codeunit 5812 Calculate Standard Cost - OnBeforeSetProperties

### ISSUE THREAD

**Issue by developerchristiaens** [microsoft/ALAppExtensions#19609]
In the codeunit 5812 Calculate Standard Cost, I need an event OnBeforeSetProperties at the beginning of the procedure SetProperties, and pass the same var parameters as in the OnAfterSetProperties. Then someone can change the parameters passed in the SetProperties procedure before continuing.
Thus, like following:

OnBeforeSetProperties(NewCalculationDate, NewCalcMultiLevel, NewUseAssemblyList, NewLogErrors, NewStdCostWkshName, NewShowDialog);

**Comment by AlexanderYakunin** [comment]
This event already exists

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetProperties(var NewCalculationDate: Date; var NewCalcMultiLevel: Boolean; var NewUseAssemblyList: Boolean; var NewLogErrors: Boolean; var NewStdCostWkshName: Text[50]; var NewShowDialog: Boolean)
    begin
    end;
