### ISSUE TITLE
[Event Request] Page 1132 - Cost Bdgt. per Center Matrix - OnBeforeMATRIX_OnDrillDown

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#19628]
Dear ALAppExtensions team,

Through this issue we would like to request adding event publisher `OnBeforeMATRIX_OnDrillDown` in Page 1132 `Cost Bdgt. per Center Matrix` with the following signature:

```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeMATRIX_OnDrillDown(var CostBudgetEntry: Record "Cost Budget Entry")
begin
end;
```
which would be called as follows in `MATRIX_OnDrillDown`:

```AL
local procedure MATRIX_OnDrillDown(ColumnID: Integer)
begin
    OnBeforeMATRIX_OnDrillDown(CostBudgetEntry);

    CostBudgetEntry.SetCurrentKey("Budget Name", "Cost Type No.", "Cost Center Code", "Cost Object Code", Date);
    if Type in [Type::Total, Type::"End-Total"] then
        CostBudgetEntry.SetFilter("Cost Type No.", Totaling)
    else
        CostBudgetEntry.SetRange("Cost Type No.", "No.");
    CostBudgetEntry.SetFilter("Cost Center Code", CostCenterMatrixRecords[ColumnID].Code);
    CostBudgetEntry.SetFilter("Budget Name", BudgetFilter);
    CostBudgetEntry.SetFilter(Date, GetFilter("Date Filter"));
    PAGE.Run(0, CostBudgetEntry);
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
