### ISSUE TITLE
[Event Parameter Change] Codeunit 5817 Undo Posting Management - procedure CheckItemLedgEntries - event OnCheckItemLedgEntriesOnBeforeCheckTempItemLedgEntry

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19620]
We would like the parameter/-s IsHandled added to the following event.

Codeunit 5817 Undo Posting Management - procedure CheckItemLedgEntries - event OnCheckItemLedgEntriesOnBeforeCheckTempItemLedgEntry

Original:

```
OnCheckItemLedgEntriesOnBeforeCheckTempItemLedgEntry(TempItemLedgEntry);

[IntegrationEvent(false, false)]
local procedure OnCheckItemLedgEntriesOnBeforeCheckTempItemLedgEntry(var TempItemLedgEntry: Record "Item Ledger Entry" temporary)
begin
end;
```

Change:

```
IsHandled := false; // <-- ADDED
OnCheckItemLedgEntriesOnBeforeCheckTempItemLedgEntry(TempItemLedgEntry, IsHandled); // <-- ADDED
if not IsHandled then // <-- ADDED

    if Positive then begin
    ...

[IntegrationEvent(false, false)]
local procedure OnCheckItemLedgEntriesOnBeforeCheckTempItemLedgEntry(var TempItemLedgEntry: Record "Item Ledger Entry" temporary; var IsHandled: Boolean) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
