### ISSUE TITLE
[Event Request] Page 1132 - Cost Bdgt. per Center Matrix - OnAfterSetFilters

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#19627]
Dear ALAppExtensions team,

Through this issue we would like to request adding event publisher `OnAfterSetFilters` in Page 1132 `Cost Bdgt. per Center Matrix` with the following signature:

```AL
[IntegrationEvent(false, false)]
local procedure OnAfterSetFilters(var Rec: Record "Cost Type")
begin
end;
```

which would be called as follows in `SetFilters`:
```AL
local procedure SetFilters(ColumnID: Integer)
begin
    SetFilter("Date Filter", DateFilter);
    SetFilter("Cost Center Filter", CostCenterMatrixRecords[ColumnID].Code);
    SetFilter("Budget Filter", BudgetFilter);

    OnAfterSetFilters(Rec);
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
