### ISSUE TITLE
[Event Parameter Request] Table 37 Sales Line - procedure UpdateVATAmounts

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#19629]
Dear ALAppExtensions Team,

We would like to request the following change

    procedure UpdateVATAmounts()
    begin
      ...............
    
      **//--> change request
      OnAfterUpdateVATAmounts(Rec,Currency);
      //<-- change request**
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateVATAmounts(var SalesLine: Record "Sales Line"; Currency: Record Currency)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46663.
