### ISSUE TITLE
[Event Parameter Change] Table 36 Sales Header - Procedure CreateSalesLine - Event OnBeforeCreateSalesLine

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19623]
We would like the Sender added to the following event.

Table 36 Sales Header - Procedure CreateSalesLine - Event OnBeforeCreateSalesLine

Original:

```
Table 36 Sales Header - Procedure CreateSalesLine - Event OnBeforeCreateSalesLine

[IntegrationEvent(false, false)]
    local procedure OnBeforeCreateSalesLine(var TempSalesLine: Record "Sales Line" temporary; var IsHandled: Boolean; var SalesHeader: record "Sales Header"; var SalesLine: record "Sales Line")
    begin
    end;
```

Change:

```
Added sender

[IntegrationEvent(true, false)]
    local procedure OnBeforeCreateSalesLine(var TempSalesLine: Record "Sales Line" temporary; var IsHandled: Boolean; var SalesHeader: record "Sales Header"; var SalesLine: record "Sales Line")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
