### ISSUE TITLE
[Event Request] OnBeforeLookupDocNo in Report 292 "Copy Sales Document" and 492 "Copy Purchase Document"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#19626]
We need the FromDocType in the existing event trigger OnBeforeLookupDocNo to handle our own extended FromDocType and set the selected FromDocNo:

Report 292:
old:
    local procedure OnBeforeLookupDocNo(var SalesHeader: Record "Sales Header")
new:
    local procedure OnBeforeLookupDocNo(var SalesHeader: Record "Sales Header";FromDocType: Enum "Sales Document Type From"; var FromDocNo: Code[20])

Report 492:
old:
    local procedure OnBeforeLookupDocNo(var PurchaseHeader: Record "Purchase Header")
new:
    local procedure OnBeforeLookupDocNo(var PurchaseHeader: Record "Purchase Header";FromDocType: Enum "Purchase Document Type From"; var FromDocNo: Code[20])

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
