### ISSUE TITLE
[Event Request] Codeunit 6620 Copy Document Mgmt CopySalesLinesToDoc functions

### ISSUE THREAD

**Issue by sboeve** [Microsoft/ALAppExtensions#1963]
Hi,
In CopySalesDocSalesLine, CopySalesInvLinesToDoc, and CopySalesCrMemoLinesToDoc functions we update ancillary tables after the original document line is updated.  We require the variable for the original document to perform this functionality.  For example in CopySalesInvLinesToDoc we need not only the ToSalesLine but the FromSalesInvLine record.

We are requesting that you add an event in each of the above functions which will take the ToSalesLine and the respective FromSalesLine as parameters.  They do not need to be passed as VAR for us, but perhaps others would need them that way.

Examples below.

[External] CopySalesShptLinesToDoc(ToSalesHeader : Record "Sales Header";VAR FromSalesShptLine : Record "Sales Shipment Line";VAR LinesNotCopied : Integer;VAR MissingExCostRevLink : Boolean)
MissingExCostRevLink := FALSE;
InitCurrency(ToSalesHeader."Currency Code");
OpenWindow;

WITH FromSalesShptLine DO
    ...
    IF CopySalesLine(
               ToSalesHeader,ToSalesLine,FromSalesHeader,FromSalesLineBuf,NextLineNo,LinesNotCopied,
               FALSE,DeferralTypeForSalesDoc(SalesDocType::"Posted Shipment"),CopyPostedDeferral,
               FromSalesLineBuf."Line No.")
        THEN BEGIN  (believe this needs to include BEGIN now in order to get the handler and CopyItemTrkg in same block)
            IF CopyItemTrkg THEN BEGIN
                ...
            END;
New Handler**** OnAfterCopySalesShptLines(ToSalesLine, FromSalesShptLine);
        END;

LOCAL CopySalesDocSalesLine(FromSalesHeader : Record "Sales Header";VAR ToSalesHeader : Record "Sales Header";VAR LinesNotCopied : Integer;NextLineNo : Integer)
ItemChargeAssgntNextLineNo := 0;

WITH ToSalesHeader DO BEGIN
  FromSalesLine.RESET;
  ...
  IF CopySalesLine(
              ToSalesHeader,ToSalesLine,FromSalesHeader,FromSalesLine,
              NextLineNo,LinesNotCopied,FALSE,DeferralTypeForSalesDoc(FromSalesHeader."Document Type"),CopyPostedDeferral,
              FromSalesLine."Line No.")
        THEN BEGIN
          IF FromSalesLine.Type = FromSalesLine.Type::"Charge (Item)" THEN
            CopyFromSalesDocAssgntToLine(
              ToSalesLine,FromSalesLine."Document Type",FromSalesLine."Document No.",FromSalesLine."Line No.",
              ItemChargeAssgntNextLineNo);
New Handler**** OnAfterCopySalesDocSalesLines(ToSalesLine, FromSalesShptLine);             
        END; 

[External] CopySalesCrMemoLinesToDoc(ToSalesHeader : Record "Sales Header";VAR FromSalesCrMemoLine : Record "Sales Cr.Memo Line";VAR LinesNotCopied : Integer;VAR MissingExCostRevLink : Boolean)
MissingExCostRevLink := FALSE;
InitCurrency(ToSalesHeader."Currency Code");
FromSalesLineBuf.RESET;
FromSalesLineBuf.DELETEALL;
...
    IF CopySalesLine(ToSalesHeader,ToSalesLine,FromSalesHeader,FromSalesLine2,NextLineNo,LinesNotCopied,
           "Return Receipt No." = '',DeferralTypeForSalesDoc(SalesDocType::"Posted Invoice"),CopyPostedDeferral,
           GetSalesLineNo(TempDocSalesLine,FromSalesLine2."Line No."))
      THEN BEGIN
          IF CopyPostedDeferral THEN
            ...
            IF CopySalesLine(
                ToSalesHeader,ToSalesLine,FromSalesHeader,
                FromSalesLine2,NextLineNo,LinesNotCopied,"Return Receipt No." = '',
                DeferralTypeForSalesDoc(SalesDocType::"Posted Credit Memo"),CopyPostedDeferral,
                GetSalesLineNo(TempDocSalesLine,FromSalesLine2."Line No."))
            THEN BEGIN
                IF CopyPostedDeferral THEN
                ...
New Handler**** OnAfterCopySalesCrMemoLines(ToSalesLine, FromSalesCrMemoLine);

**Comment by sboeve** [comment]
Would also need same type of event in CopySalesReturnRcptLinesToDoc.  OnAfterCopySalesReturnRcptines(ToSalesLine, FromReturnRcptLine);

**Comment by AlexanderYakunin** [comment]
This is already done earlier
