### ISSUE TITLE
[Event Request] Table 37 Sales Line - Field Amount Including VAT

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#19634]
Dear ALAppExtensions Team,

We would like to request the following change

    field(30; "Amount Including VAT"; Decimal)
    {
        AutoFormatExpression = "Currency Code";
        AutoFormatType = 1;
        Caption = 'Amount Including VAT';
        Editable = false;

        trigger OnValidate()
        begin
            "Amount Including VAT" := Round("Amount Including VAT", Currency."Amount Rounding Precision");
            case "VAT Calculation Type" of
                "VAT Calculation Type"::"Normal VAT",
                "VAT Calculation Type"::"Reverse Charge VAT":
                    begin
                        Amount :=
                          Round(
                            "Amount Including VAT" /
                            (1 + (1 - SalesHeader."VAT Base Discount %" / 100) * "VAT %" / 100),
                            Currency."Amount Rounding Precision");
                        "VAT Base Amount" :=
                          Round(Amount * (1 - SalesHeader."VAT Base Discount %" / 100), Currency."Amount Rounding Precision");
                        **//--> change request
                        OnAfterSalesTaxCalculate(Rec, SalesHeader, Currency);
                        //<-- change request**
                    end;
                "VAT Calculation Type"::"Full VAT":
                    begin
                        Amount := 0;
                        "VAT Base Amount" := 0;
                    end;
                "VAT Calculation Type"::"Sales Tax":
                    begin
                        SalesHeader.TestField("VAT Base Discount %", 0);
                        Amount :=
                          SalesTaxCalculate.ReverseCalculateTax(
                            "Tax Area Code", "Tax Group Code", "Tax Liable", SalesHeader."Posting Date",
                            "Amount Including VAT", "Quantity (Base)", SalesHeader."Currency Factor");
                        OnAfterSalesTaxCalculateReverse(Rec, SalesHeader, Currency);
                        UpdateVATPercent(Amount, "Amount Including VAT" - Amount);
                        Amount := Round(Amount, Currency."Amount Rounding Precision");
                        "VAT Base Amount" := Amount;
                    end;
            end;
            OnValidateAmountIncludingVATOnAfterAssignAmounts(Rec, Currency);

            InitOutstandingAmount();
        end;
    }
    
    [IntegrationEvent(false, false)]
    local procedure OnAfterSalesTaxCalculate(var SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header"; Currency: Record Currency)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45914.
