### ISSUE TITLE
GetWhseRqstSourceDocument returns wrong value for Service Line

### ISSUE THREAD

**Issue by achim-t** [microsoft/ALAppExtensions#19631]
The procedure GetWhseRqstSourceDocument is in codeunit 5775 "Whse. Management".

`GetWhseRqstSourceDocument(Database::"Service Line", 0)` should return `"Warehouse Request Source Document"::"Service Order"` but it returns `18` instead. That enum doesn't have a value 18.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46699.
