### ISSUE TITLE
[Event Parameter Request] Table 37 Sales Line - procedure CalcVATAmountLines

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#19633]
Dear ALAppExtensions Team,

We would like to request the following change

    procedure CalcVATAmountLines(QtyType: Option General,Invoicing,Shipping; var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; var VATAmountLine: Record "VAT Amount Line"; IncludePrepayments: Boolean)
    var
        TotalVATAmount: Decimal;
        QtyToHandle: Decimal;
        AmtToHandle: Decimal;
        RoundingLineInserted: Boolean;
        ShouldProcessRounding: Boolean;
        IsHandled: Boolean;
    begin
        **//--> change request "IncludePrepayments" parameter
        if IsCalcVATAmountLinesHandled(SalesHeader, SalesLine, VATAmountLine, QtyType,IncludePrepayments) then
        //<-- change request**
            exit;

        Currency.Initialize(SalesHeader."Currency Code");
        OnCalcVATAmountLinesOnAfterCurrencyInitialize(Rec, SalesHeader, Currency);

        VATAmountLine.DeleteAll();

        ...........

    end;

    **//--> change request "IncludePrepayments" parameter
    local procedure IsCalcVATAmountLinesHandled(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; var VATAmountLine: Record "VAT Amount Line"; QtyType: Option General,Invoicing,Shipping;IncludePrepayments: Boolean) IsHandled: Boolean
    //<-- change request**
    begin
        IsHandled := false;
        **//--> change request "IncludePrepayments" parameter
        OnBeforeCalcVATAmountLines(SalesHeader, SalesLine, VATAmountLine, IsHandled, QtyType,IncludePrepayments);
        //<-- change request**
        exit(IsHandled);
    end;

    [IntegrationEvent(false, false)]
    **//--> change request "IncludePrepayments" parameter
    local procedure OnBeforeCalcVATAmountLines(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; var VATAmountLine: Record "VAT Amount Line"; var IsHandled: Boolean; QtyType: Option General,Invoicing,Shipping;IncludePrepayments: Boolean)
    //<-- change request**
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45720.
