### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - event OnBeforeCheckQtyToReceive

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#19630]
Hello,

We would need an extra event in codeunit 90 "Purch.-Post" - **OnBeforeCheckQtyToReceive**

    procedure TestPurchLine(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line")
    var
        DummyTrackingSpecification: Record "Tracking Specification";
        SkipTestFieldQtyToReceive: Boolean; // <<NEW VARIABLE>>
    begin
        OnBeforeTestPurchLine(PurchLine, PurchHeader, SuppressCommit);

        with PurchLine do begin
            case Type of
                Type::Item:
                    DummyTrackingSpecification.CheckItemTrackingQuantity(
                      DATABASE::"Purchase Line", "Document Type".AsInteger(), "Document No.", "Line No.",
                      "Qty. to Receive (Base)", "Qty. to Invoice (Base)", PurchHeader.Receive, PurchHeader.Invoice);
                Type::"Charge (Item)":
                    TestPurchLineItemCharge(PurchLine);
                Type::"Fixed Asset":
                    TestPurchLineFixedAsset(PurchLine);
                else
                    TestPurchLineOthers(PurchLine);
            end;

            TestPurchLineJob(PurchLine);

            case "Document Type" of
                "Document Type"::Order:
                    TestField("Return Qty. to Ship", 0, ErrorInfo.Create());
                "Document Type"::Invoice:
                    begin
                        if "Receipt No." = '' then
                            TestField("Qty. to Receive", Quantity, ErrorInfo.Create());
                        TestField("Return Qty. to Ship", 0, ErrorInfo.Create());
                        TestField("Qty. to Invoice", Quantity, ErrorInfo.Create());
                    end;
                "Document Type"::"Return Order":
                    TestField("Qty. to Receive", 0, ErrorInfo.Create());
                "Document Type"::"Credit Memo":
                    begin
                        if "Return Shipment No." = '' then
                            TestField("Return Qty. to Ship", Quantity, ErrorInfo.Create());
                        OnBeforeCheckQtyToReceive(PurchLine, SkipTestFieldQtyToReceive); // <<NEW EVENT>>
                        if not SkipTestFieldQtyToReceive then // <<NEW EVENT>>
                            TestField("Qty. to Receive", 0, ErrorInfo.Create());
                        TestField("Qty. to Invoice", Quantity, ErrorInfo.Create());
                    end;
            end;

            if "Blanket Order No." <> '' then
                TestField("Blanket Order Line No.", ErrorInfo.Create());
        end;
        CheckBlockedPostingGroups(PurchLine);

        OnAfterTestPurchLine(PurchHeader, PurchLine, WhseReceive, WhseShip);
    end;

We need this event, as we check the "Qty. to Receive" in specific situations. That's why we want to skip the TestField in certain conditions inside the event OnBeforeCheckQtyToReceive.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47148.
