### ISSUE TITLE
[BUG] codeunit 699 "Exch. Rate Adjmt. Process" - AdjustCurrency

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#19650]
I am not sure where to report this. I think the following ist a bug, because if you iterate over more than one currency the TempCurrencyToAdjust (Buffer) is only filled with the first currency.
I suggest to move the repeat some lines upwords. 

    local procedure AdjustCurrency(var ExchRateAdjmtParameters: Record "Exch. Rate Adjmt. Parameters" temporary)
    var
        BankAccount: Record "Bank Account";
    begin
        BankAccount.SetFilter("No.", ExchRateAdjmtParameters.GetFilter("Bank Account Filter"));
        BankAccount.FilterGroup(2);
        BankAccount.SetFilter("Currency Code", '<>%1', '');
        BankAccount.FilterGroup(0);
        BankAccNoTotal := BankAccount.Count();
        BankAccount.Reset();

        Currency.SetView(ExchRateAdjmtParameters."Currency Filter");
        if Currency.FindSet() then begin
            //-BUGFIX
            repeat
                // +BUGFIX
                Currency."Last Date Adjusted" := ExchRateAdjmtParameters."Posting Date";
                Currency.Modify();

                Currency."Currency Factor" := CurrExchRate.ExchangeRateAdjmt(ExchRateAdjmtParameters."Posting Date", Currency.Code);

                TempCurrencyToAdjust := Currency;
                TempCurrencyToAdjust.Insert();

                // -BUGFIX
                //repeat
                // +BUGFIX
                BankAccount.SetCurrentKey("Bank Acc. Posting Group");
                BankAccount.SetRange("Currency Code", Currency.Code);
                BankAccount.SetRange("Date Filter", ExchRateAdjmtParameters."Start Date", ExchRateAdjmtParameters."End Date");
                if BankAccount.FindSet() then
                    repeat
                        BankAccNo := BankAccNo + 1;
                        Window.Update(1, Round(BankAccNo / BankAccNoTotal * 10000, 1));
                        ProcessBankAccount(BankAccount, Currency);
                    until BankAccount.Next() = 0;
            until Currency.Next() = 0;
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45051.
