### ISSUE TITLE
[Request-For-External] codeunit 1290 "SOAP Web Service Request Mgt." - SendRequestToWebService

### ISSUE THREAD

**Issue by JPicard90** [microsoft/ALAppExtensions#19665]
please just remove the attribute "[Scope('OnPrem')]" above the function "SendRequestToWebService" from codeunit 1290, or update the whole codeunit to the new https variables

thanks

**Comment by AlexanderYakunin** [comment]
CU 1290 is intended for internal usage only, external code can use [HttpClient Data Type - Business Central | Microsoft Docs](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/httpclient/httpclient-data-type) to make SOAP requests
