### ISSUE TITLE
[Event Request] codeunit 5971 "Service Header Apply" OnRunOnAfterFilterCustLedgEntry

### ISSUE THREAD

**Issue by iltererdogan** [microsoft/ALAppExtensions#19664]
Hi,
Is it possible to add OnRunOnAfterFilterCustLedgEntry event "Service Header Apply" codeunit.

    trigger OnRun()
    begin
        ServHeader.Copy(Rec);
        with ServHeader do begin
            BilToCustNo := "Bill-to Customer No.";
            CustLedgEntry.SetCurrentKey("Customer No.", Open);
            CustLedgEntry.SetRange("Customer No.", BilToCustNo);
            CustLedgEntry.SetRange(Open, true);
            <<NEW
            OnRunOnAfterFilterCustLedgEntry(CustLedgEntry, ServHeader);
            >>NEW
            if "Applies-to ID" = '' then
                "Applies-to ID" := "No.";
            if "Applies-to ID" = '' then
                Error(
                  Text000,
                  FieldCaption("No."), FieldCaption("Applies-to ID"));

    <<NEW
    [IntegrationEvent(false, false)]
    local procedure OnRunOnAfterFilterCustLedgEntry(var CustLedgerEntry: Record "Cust. Ledger Entry"; var ServHeader: Record "Service Header")
    begin
    end;
    >>NEW

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45720.
