### ISSUE TITLE
[Event Request] Table 5902 Service Line - field Amount Including VAT

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#19673]
Dear ALAppExtensions Team,

We would like to request the following change

    field(30; "Amount Including VAT"; Decimal)
    {
        AutoFormatExpression = "Currency Code";
        AutoFormatType = 1;
        Caption = 'Amount Including VAT';
        Editable = false;

        trigger OnValidate()
        begin
            GetServHeader;
            "Amount Including VAT" := Round("Amount Including VAT", Currency."Amount Rounding Precision");
            case "VAT Calculation Type" of
                "VAT Calculation Type"::"Normal VAT",
                "VAT Calculation Type"::"Reverse Charge VAT":
                    begin
                        Amount :=
                          Round(
                            "Amount Including VAT" /
                            (1 + (1 - ServHeader."VAT Base Discount %" / 100) * "VAT %" / 100),
                            Currency."Amount Rounding Precision");
                        "VAT Base Amount" :=
                          Round(Amount * (1 - ServHeader."VAT Base Discount %" / 100), Currency."Amount Rounding Precision");
                        **//--> change request
                        OnAfterNormalVATCalculate(Rec, ServHeader, Currency);
                        //<-- change request**
                    end;
                "VAT Calculation Type"::"Full VAT":
                    begin
                        Amount := 0;
                        "VAT Base Amount" := 0;
                    end;
                "VAT Calculation Type"::"Sales Tax":
                    begin
                        ServHeader.TestField("VAT Base Discount %", 0);
                        Amount :=
                          SalesTaxCalculate.ReverseCalculateTax(
                            "Tax Area Code", "Tax Group Code", "Tax Liable", ServHeader."Posting Date",
                            "Amount Including VAT", "Quantity (Base)", ServHeader."Currency Factor");
                        OnAfterSalesTaxCalculateReverse(Rec, ServHeader, Currency);
                        UpdateVATPercent(Amount, "Amount Including VAT" - Amount);
                        Amount := Round(Amount, Currency."Amount Rounding Precision");
                        "VAT Base Amount" := Amount;
                    end;
            end;

            InitOutstandingAmount;
        end;
    }

    [IntegrationEvent(false, false)]
    local procedure OnAfterNormalVATCalculate(var ServiceLine: Record "Service Line"; ServiceHeader: Record "Service Header"; Currency: Record Currency)
   begin
   end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45914.
