### ISSUE TITLE
[Event Request] Table 39 Purchase Line - field Amount

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#19670]
Dear ALAppExtensions Team,

We would like to request the following change

    field(29; Amount; Decimal)
    {
        AutoFormatExpression = "Currency Code";
        AutoFormatType = 1;
        Caption = 'Amount';
        Editable = false;

        trigger OnValidate()
        begin
            GetPurchHeader();
            Amount := Round(Amount, Currency."Amount Rounding Precision");
            case "VAT Calculation Type" of
                "VAT Calculation Type"::"Normal VAT",
                "VAT Calculation Type"::"Reverse Charge VAT":
                    begin
                        "VAT Base Amount" :=
                          Round(Amount * (1 - PurchHeader."VAT Base Discount %" / 100), Currency."Amount Rounding Precision");
                        "Amount Including VAT" :=
                          Round(Amount + "VAT Base Amount" * "VAT %" / 100, Currency."Amount Rounding Precision");
                        **//--> change request
                        OnAfterNormalVATCalculate(Rec, PurchHeader, Currency);
                        //<-- change request**
                    end;
                "VAT Calculation Type"::"Full VAT":
                    if Amount <> 0 then
                        FieldError(Amount,
                          StrSubstNo(
                            Text011, FieldCaption("VAT Calculation Type"),
                            "VAT Calculation Type"));
                "VAT Calculation Type"::"Sales Tax":
                    begin
                        PurchHeader.TestField("VAT Base Discount %", 0);
                        "VAT Base Amount" := Amount;
                        if "Use Tax" then
                            "Amount Including VAT" := "VAT Base Amount"
                        else begin
                            "Amount Including VAT" :=
                              Amount +
                              Round(
                                SalesTaxCalculate.CalculateTax(
                                  "Tax Area Code", "Tax Group Code", "Tax Liable", PurchHeader."Posting Date",
                                  "VAT Base Amount", "Quantity (Base)", PurchHeader."Currency Factor"),
                                Currency."Amount Rounding Precision");
                            OnAfterSalesTaxCalculate(Rec, PurchHeader, Currency);
                            if "VAT Base Amount" <> 0 then
                                "VAT %" :=
                                  Round(100 * ("Amount Including VAT" - "VAT Base Amount") / "VAT Base Amount", 0.00001)
                            else
                                "VAT %" := 0;
                        end;
                    end;
            end;

            InitOutstandingAmount();
            UpdateUnitCost();
        end;
    }

    [IntegrationEvent(false, false)]
    local procedure OnAfterNormalVATCalculate(var PurchaseLine: Record "Purchase Line"; PurchaseHeader: Record "Purchase Header"; Currency: Record Currency)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45914.
