### ISSUE TITLE
[Event Request] Table 5902 Service Line - procedure UpdateVATAmounts

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#19681]
Dear ALAppExtensions Team,

We would like to request the following change

    procedure UpdateVATAmounts()
    var
        ServiceLine2: Record "Service Line";
        TotalLineAmount: Decimal;
        TotalInvDiscAmount: Decimal;
        TotalAmount: Decimal;
        TotalAmountInclVAT: Decimal;
        TotalVATDifference: Decimal;
        TotalQuantityBase: Decimal;
    begin
        OnBeforeUpdateVATAmounts(Rec);

        GetServHeader;
        ServiceLine2.SetRange("Document Type", "Document Type");
        ServiceLine2.SetRange("Document No.", "Document No.");
        ServiceLine2.SetFilter("Line No.", '<>%1', "Line No.");
        if "Line Amount" = 0 then
            if xRec."Line Amount" >= 0 then
                ServiceLine2.SetFilter(Amount, '>%1', 0)
            else
                ServiceLine2.SetFilter(Amount, '<%1', 0)
        else
            if "Line Amount" > 0 then
                ServiceLine2.SetFilter(Amount, '>%1', 0)
            else
                ServiceLine2.SetFilter(Amount, '<%1', 0);
        ServiceLine2.SetRange("VAT Identifier", "VAT Identifier");
        ServiceLine2.SetRange("Tax Group Code", "Tax Group Code");

        if "Line Amount" = "Inv. Discount Amount" then begin
            Amount := 0;
            "VAT Base Amount" := 0;
            "Amount Including VAT" := 0;
            **//--> change request
            OnUpdateVATAmountsOnBeforeServiceLineModify(Rec);
            //<-- change request**
        end else begin
            TotalLineAmount := 0;
            TotalInvDiscAmount := 0;
            TotalAmount := 0;
            TotalAmountInclVAT := 0;
            TotalQuantityBase := 0;
            if ("VAT Calculation Type" = "VAT Calculation Type"::"Sales Tax") or
               (("VAT Calculation Type" in
                 ["VAT Calculation Type"::"Normal VAT",
                  "VAT Calculation Type"::"Reverse Charge VAT"]) and
                ("VAT %" <> 0))
            then
                if not ServiceLine2.IsEmpty() then begin
                    ServiceLine2.CalcSums("Line Amount", "Inv. Discount Amount", Amount, "Amount Including VAT", "Quantity (Base)");
                    TotalLineAmount := ServiceLine2."Line Amount";
                    TotalInvDiscAmount := ServiceLine2."Inv. Discount Amount";
                    TotalAmount := ServiceLine2.Amount;
                    TotalAmountInclVAT := ServiceLine2."Amount Including VAT";
                    TotalVATDifference := ServiceLine2."VAT Difference";
                    TotalQuantityBase := ServiceLine2."Quantity (Base)";
                end;

            if ServHeader."Prices Including VAT" then
                case "VAT Calculation Type" of
                    "VAT Calculation Type"::"Normal VAT",
                    "VAT Calculation Type"::"Reverse Charge VAT":
                        begin
                            Amount :=
                              (TotalLineAmount - TotalInvDiscAmount + CalcLineAmount) / (1 + "VAT %" / 100) -
                              TotalAmount;
                            "VAT Base Amount" :=
                              Round(
                                Amount * (1 - ServHeader."VAT Base Discount %" / 100), Currency."Amount Rounding Precision");
                            "Amount Including VAT" :=
                              Round(TotalAmount + Amount +
                                (TotalAmount + Amount) * (1 - ServHeader."VAT Base Discount %" / 100) * "VAT %" / 100 -
                                TotalAmountInclVAT, Currency."Amount Rounding Precision", Currency.VATRoundingDirection);
                            Amount := Round(Amount, Currency."Amount Rounding Precision");
                          **//--> change request  
                          OnAfterNormalVATCalculateReverse(Rec, ServHeader, Currency);  
                          //<-- change request**
                        end;
                    "VAT Calculation Type"::"Full VAT":
                        begin
                            Amount := 0;
                            "VAT Base Amount" := 0;
                        end;
                    "VAT Calculation Type"::"Sales Tax":
                        begin
                            ServHeader.TestField("VAT Base Discount %", 0);
                            Amount :=
                              SalesTaxCalculate.ReverseCalculateTax(
                                "Tax Area Code", "Tax Group Code", "Tax Liable", ServHeader."Posting Date",
                                TotalAmountInclVAT + "Amount Including VAT", TotalQuantityBase + "Quantity (Base)",
                                ServHeader."Currency Factor") -
                              TotalAmount;
                            OnAfterSalesTaxCalculateReverse(Rec, ServHeader, Currency);
                            UpdateVATPercent(Amount, "Amount Including VAT" - Amount);
                            Amount := Round(Amount, Currency."Amount Rounding Precision");
                            "VAT Base Amount" := Amount;
                        end;
                end
            else
                case "VAT Calculation Type" of
                    "VAT Calculation Type"::"Normal VAT",
                  "VAT Calculation Type"::"Reverse Charge VAT":
                        begin
                            Amount := Round(CalcLineAmount(), Currency."Amount Rounding Precision");
                            "VAT Base Amount" :=
                              Round(Amount * (1 - ServHeader."VAT Base Discount %" / 100), Currency."Amount Rounding Precision");
                            "Amount Including VAT" :=
                              TotalAmount + Amount +
                              Round(
                                (TotalAmount + Amount) * (1 - ServHeader."VAT Base Discount %" / 100) * "VAT %" / 100,
                                Currency."Amount Rounding Precision", Currency.VATRoundingDirection()) -
                              TotalAmountInclVAT + TotalVATDifference;
                            **//--> change request  
                            OnAfterNormalVATCalculate(Rec, ServHeader, Currency);  
                            //<-- change request** 
                        end;
                    "VAT Calculation Type"::"Full VAT":
                        begin
                            Amount := 0;
                            "VAT Base Amount" := 0;
                            "Amount Including VAT" := CalcLineAmount;
                        end;
                    "VAT Calculation Type"::"Sales Tax":
                        begin
                            Amount := Round(CalcLineAmount, Currency."Amount Rounding Precision");
                            "VAT Base Amount" := Amount;
                            "Amount Including VAT" :=
                              TotalAmount + Amount +
                              Round(
                                SalesTaxCalculate.CalculateTax(
                                  "Tax Area Code", "Tax Group Code", "Tax Liable", ServHeader."Posting Date",
                                  TotalAmount + Amount, TotalQuantityBase + "Quantity (Base)",
                                  ServHeader."Currency Factor"), Currency."Amount Rounding Precision") -
                              TotalAmountInclVAT;
                            OnAfterSalesTaxCalculate(Rec, ServHeader, Currency);
                            UpdateVATPercent("VAT Base Amount", "Amount Including VAT" - "VAT Base Amount");
                        end;
                end;
        end;

        OnAfterUpdateVATAmounts(Rec);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnUpdateVATAmountsOnBeforeServiceLineModify(var ServiceLine: Record "Service Line")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterNormalVATCalculateReverse(var ServiceLine: Record "Service Line"; ServiceHeader: Record "ServiceHeader"; Currency: Record Currency)
    begin
    end;
    
    [IntegrationEvent(false, false)]
    local procedure OnAfterNormalVATCalculate(var ServiceLine: Record "Service Line"; ServiceHeader: Record "Service Header"; Currency: Record Currency)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49880.
