### ISSUE TITLE
[Event Request] table 5409 "Prod. Order Routing Line" - OnCalculateRoutingForwardOnAfterCalculateProdOrderDates

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#19682]
local procedure CalculateRoutingForward()
    var
        ProdOrderLine: Record "Prod. Order Line";
        ProdOrderRoutingLine: Record "Prod. Order Routing Line";
    begin
        ...
                CalcProdOrder.CalculateProdOrderDates(ProdOrderLine, true);
                OnCalculateRoutingForwardOnAfterCalculateProdOrderDates(Rec, ProdOrderLine);  //A111F000.Event20.02
                AdjustComponents(ProdOrderLine);
        ...
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCalculateRoutingForwardOnAfterCalculateProdOrderDates(var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var ProdOrderLine: Record "Prod. Order Line")
    begin
        //A111F000.Event20.02
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46829.

**Comment by AlexanderYakunin** [comment]
Missing implementation, reactivated

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49745.
