### ISSUE TITLE
[Event Change Request] report 7323 "Create Invt Put-away/Pick/Mvmt" - OnBeforeCheckWhseRequest

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#19697]
Could you please include the sender in the event `report 7323 "Create Invt Put-away/Pick/Mvmt"`?
```al
//+Change
//-[IntegrationEvent(false, false)]
[IntegrationEvent(true, false)]
//-Change
local procedure OnBeforeCheckWhseRequest(var WarehouseRequest: Record "Warehouse Request"; ShowError: Boolean; var SkipRecord: Boolean; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47191.
