### ISSUE TITLE
[Event Request] Table 5902 Service Line - procedure UpdateVATOnLines

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#19702]
Dear ALAppExtensions Team,

We would like to request the following change

    procedure UpdateVATOnLines(QtyType: Option General,Invoicing,Shipping; var ServHeader: Record "Service Header"; var ServiceLine: Record "Service Line"; var VATAmountLine: Record "VAT Amount Line")
    var
        TempVATAmountLineRemainder: Record "VAT Amount Line" temporary;
        Currency: Record Currency;
        NewAmount: Decimal;
        NewAmountIncludingVAT: Decimal;
        NewVATBaseAmount: Decimal;
        VATAmount: Decimal;
        VATDifference: Decimal;
        InvDiscAmount: Decimal;
        LineAmountToInvoice: Decimal;
    begin
        **//--> change request
         IsHandled := false;
         OnUpdateVATOnLinesOnBeforeProcessServiceLines(Rec, xRec, ServiceHeader, VATAmountLine, IsHandled, QtyType);
         if IsHandled then
            exit
        //<-- change request**
        if QtyType = QtyType::Shipping then
            exit;

        Currency.Initialize(ServHeader."Currency Code");

        TempVATAmountLineRemainder.DeleteAll();

      .........................
   
    end;

    [IntegrationEvent(false, false)]
    local procedure OnUpdateVATOnLinesOnBeforeProcessServiceLines(var ServiceLine: Record "Service Line"; xServiceLine: Record "Service Line"; var ServiceHeader: Record "Service Header"; var VATAmountLine: Record "VAT Amount Line"; var IsHandled: Boolean; QtyType: Option General,Invoicing,Shipping)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46829.
