### ISSUE TITLE
[Event Request] Table 290 VAT Amount Line - procedure DeductVATAmountLine

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#19706]
Dear ALAppExtensions Team,

We would like to request the following change

    procedure DeductVATAmountLine(var VATAmountLineDeduct: Record "VAT Amount Line")
    begin
        if FindSet() then
            repeat
                VATAmountLineDeduct := Rec;
                if VATAmountLineDeduct.Find then begin
                    "VAT Base" -= VATAmountLineDeduct."VAT Base";
                    "VAT Amount" -= VATAmountLineDeduct."VAT Amount";
                    "Amount Including VAT" -= VATAmountLineDeduct."Amount Including VAT";
                    "Line Amount" -= VATAmountLineDeduct."Line Amount";
                    "Inv. Disc. Base Amount" -= VATAmountLineDeduct."Inv. Disc. Base Amount";
                    "Invoice Discount Amount" -= VATAmountLineDeduct."Invoice Discount Amount";
                    "Calculated VAT Amount" -= VATAmountLineDeduct."Calculated VAT Amount";
                    "VAT Difference" -= VATAmountLineDeduct."VAT Difference";
                    **//--> change request
                    OnBeforeModifyDeductVATAmountLine(Rec,VATAmountLineDeduct)
                    //<-- change request** 
                    Modify;
                end;
            until Next() = 0;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyDeductVATAmountLine(var VATAmountLine: Record "VAT Amount Line"; VATAmountLineDeduct: Record "VAT Amount Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45720.
