### ISSUE TITLE
Bug in Correct Posted Document Codeunits

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/ALAppExtensions#19714]
The procedure ErrorHelperAccount in Codeunit is not called consistently in the code.  The variable order in the usage is incorrect in most cases.

Codeunit 1313:
- procedure TestVendorDimension
- procedure TestPurchaseLines
- procedure TestGLAccount

Codeunit 1303:
- procedure TestCustomerDimension
- procedure TestSalesLines
- procedure TestGLAccount

**Comment by AlexanderYakunin** [comment]
Hello! Can you be more specific? And how this is related to extensibility issues?

**Comment by gunnargestsson** [comment]
Hi!

This is not an extensibility issue, just a base app bug.  Should I be reporting this somewhere else?

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
