### ISSUE TITLE
[Event Request] Codeunit 5704 TransferOrder-Post Shipment  – OnRun

### ISSUE THREAD

**Issue by ttaeufer** [Microsoft/ALAppExtensions#1971]
Could we please have a Supplement in publisher OnBeforeTransferOrderPostShipment in function OnRun
5704 TransferOrder-Post Shipment ? 

```
OnRun(VAR Rec : Record "Transfer Header")
ReleaseDocument(Rec);
TransHeader := Rec;
TransHeader.SetHideValidationDialog(HideValidationDialog);
// >>>>>>>>
OnBeforeTransferOrderPostShipment(TransHeader,var SuppressCommit);
// <<<<<<<<  

WITH TransHeader DO BEGIN

```

**Comment by AlexanderYakunin** [comment]
We already have that:

OnRun(VAR Rec : Record "Transfer Header")
ReleaseDocument(Rec);
TransHeader := Rec;
TransHeader.SetHideValidationDialog(HideValidationDialog);

OnBeforeTransferOrderPostShipment(TransHeader,SuppressCommit);

WITH TransHeader DO BEGIN
  CheckBeforePost;
