### ISSUE TITLE
[Event Request] Report 1307 "Standard Sales - Credit Memo" VATAmountLine.InsertLine();

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#19728]
Hello,

can you please add publisher before line 579 to handle the insert: 
```
OnBeforeVATAmountLineInsertLine(IsHandled);
if not IsHandled then
VATAmountLine.InsertLine();
```

Definition: 
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeVATAmountLineInsertLine(var IsHandled: Boolean)
    begin
    end;
```

**Comment by Vadim-Stepanenko** [comment]
There is already a **OnInsertLine** in the **VATAmountLine.InsertLine();**, can you use that instead?

**Comment by Vadim-Stepanenko** [comment]
Ok, so I assume you can, please do that. If not please open a new issue and provide the scenario where it's not possible.
