### ISSUE TITLE
[Object Name exceeds 30 chars] enum 4700 "VAT Group Authentication Type OnPrem" and enum 4702 "VAT Group Authentication Type Saas"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#19720]
We are getting at least 20 warnings in the Windows Event Viewer during an update of at least 10 of our apps.
It looks like Enums:
enum 4700 "VAT Group Authentication Type OnPrem"
enum 4702 "VAT Group Authentication Type Saas"
exceed the 30 character limit

Message The object name 'VAT Group Authentication Type ' can only appear once for the type 'Enum'. The same object exists in both extension (
'c50a4bf0-db51-4ad2-88d5-fe2287da0eb8' 'VAT Group Management', Publisher: Microsoft, Package ID: 70a34fe7-b11d-48e5-b9de-44936dcb9019, Runtime Package ID: dcbec3da-2499-4947-b795-99eaa2bec490, Scope: Global, Version: 20.2.41144.41423) and in extension (
'c50a4bf0-db51-4ad2-88d5-fe2287da0eb8' 'VAT Group Management', Publisher: Microsoft, Package ID: 70a34fe7-b11d-48e5-b9de-44936dcb9019, Runtime Package ID: dcbec3da-2499-4947-b795-99eaa2bec490, Scope: Global, Version: 20.2.41144.41423).

**Comment by pri-kise** [comment]
Related Issue: https://github.com/microsoft/AL/issues/6740
(Comment that explains the 30 character limits in details: https://github.com/microsoft/AL/issues/6740#issuecomment-911443709)

**Comment by haoranpb** [comment]
Thanks for pointing out the issue. In 21.1, the Enums will be marked as obsoleted, and shorter names will be in place.

```
enum 4704 "VAT Group Auth Type OnPrem"
enum 4705 "VAT Group Auth Type Saas"
```

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 47728.
