### ISSUE TITLE
Report 1307 "Standard Sales - Credit Memo" protected variables

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#19725]
Hi,

can you please mark the following variables to be protected in Report 1307 "Standard Sales - Credit Memo"?

- FormattedQuantity
- FormattedUnitPrice
- FormattedVATPct
- FormattedLineAmount
- LineDiscountPctText
- FirstLineHasBeenOutput
- TotalAmountInclVAT
- TotalAmountVAT
- TotalAmount
- TotalInvDiscAmount
- TotalSubTotal
- VATAmtLbl
- SalespersonPurchaser
- PaymentTerms
- ShipmentMethod
- DiscountPercentLblText
- SalesPersonText
- TotalText
- TotalInclVATText
- TotalExclVATText

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45464.
