### ISSUE TITLE
Report 1305 "Standard Sales - Order Conf." protected variables

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#19724]
Hi,

can you please mark following variables to protected in Report 1305 Sales - Confirmation?

- TotalSubTotal
- TotalInvDiscAmount
- TotalAmount
- TotalAmountVAT
- TotalAmountInclVAT
- SalesConfirmationLbl
- DiscountPercentLblText
- PaymentTermsDescLbl
- PaymentTerms
- ShipmentMethod
- ShptMethodDescLbl
- SalespersonPurchaser
- SalesPersonText

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45464.
