### ISSUE TITLE
Report 1307 "Standard Sales - Credit Memo" SalesPersonText: Text[50]

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#19726]
In Report 1307 "Standard Sales - Credit Memo" global variable length is set to 30 characters. If you take a look at the procedure that is called from the report length of the variable is 50:

procedure SetSalesPerson(var SalespersonPurchaser: Record "Salesperson/Purchaser"; "Code": Code[20]; var SalesPersonText: Text[50])
begin
...
end;

Please set the length of the variable to 50 in the report.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45051.
