### ISSUE TITLE
[request-for-external] page 233 "Apply Vendor Entries"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#19731]
Please make the following functions protected

```
protected procedure CalcApplnRemainingAmount(Amount: Decimal): Decimal
protected procedure FindAmountRounding()
protected procedure HandleChosenEntries(Type: Enum "Vendor Apply Calculation Type"; CurrentAmount: Decimal; CurrencyCode: Code[10]; PostingDate: Date)
```

Has already been asked again in
https://github.com/microsoft/ALAppExtensions/issues/18103
but it is not included in latest w1 onprem 20.3.42673.43026

**Comment by AlexanderYakunin** [comment]
We do not expose new procedures in PROD versions, it will be available in version 21 only.
