### ISSUE TITLE
[Event Request] Report 1306 "Standard Sales - Invoice" FillRightHeader()

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#19739]
Please add an publisher to the procedure FillRightHeader in Report 1306 "Standard Sales - Invoice":
```
        OnBeforeFillRightHeader(Header, SalespersonPurchaser, SalesPersonText, RightHeader, IsHandled);
        if IsHandled then
            exit;
```
Definition:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeFillRightHeader(Header: Record "Sales Invoice Header"; var SalesPersonPurchaser: Record "Salesperson/Purchaser"; var SalesPersonText: Text[50]; var RightHeader: Record "Name/Value Buffer"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46955.
