### ISSUE TITLE
[Event Request] Report 1306 "Standard Sales - Invoice" GetUOMText

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#19736]
Please change following procedure in the way that we can manipulate/translate the description based on Language code: 
```
    local procedure GetUOMText(UOMCode: Code[10])**UOMDescription**: Text[50]
    var
        UnitOfMeasure: Record "Unit of Measure";
    begin
        if not UnitOfMeasure.Get(UOMCode) then
            exit(UOMCode);
        **UOMDescription := UnitOfMeasure.Description**
        **OnAfterGetUOMText(UOMCode,UOMDescription);**
        **exit(UOMDescription);**
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46955.
