### ISSUE TITLE
[Event Request] Codeunit 7326 Whse. Item Tracking FEFO  – SummarizeAdjustmentBinFEFO

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#1973]
Could we please have a publisher OnBeforeInsertEntrySummaryFEFOSummarizeAdjustmentBinFEFO in function SummarizeAdjustmentBinFEFO Codeunit 7326 Whse. Item Tracking FEFO? 

```
LOCAL SummarizeAdjustmentBinFEFO(Location : Record Location;ItemNo : Code[20];VariantCode : Code[10])
IF Location."Adjustment Bin Code" = '' THEN
  EXIT;

WITH WhseEntry DO BEGIN
..
            ExpirationDate :=
              ItemTrackingMgt.WhseExistingExpirationDate(
               "Item No.","Variant Code",Location,"Lot No.","Serial No.",EntriesExist);

            IF NOT EntriesExist THEN
              ExpirationDate := 0D;
            
       // >>>>>>>>
            OnBeforeInsertEntrySummaryFEFOSummarizeAdjustmentBinFEFO (var TempGlobalEntrySummary);
		  // <<<<<<<<  	

            InsertEntrySummaryFEFO("Lot No.","Serial No.",ExpirationDate);
      END;


```

**Comment by AlexanderYakunin** [comment]
We already have similar event here

LOCAL InsertEntrySummaryFEFO(LotNo : Code[50];SerialNo : Code[50];ExpirationDate : Date)
WITH TempGlobalEntrySummary DO
  IF (NOT StrictExpirationPosting) OR (ExpirationDate >= WORKDATE) THEN BEGIN
    INIT;
    "Entry No." := LastSummaryEntryNo + 1;
    "Serial No." := SerialNo;
    "Lot No." := LotNo;
    "Expiration Date" := ExpirationDate;
    **OnBeforeInsertEntrySummaryFEFO(TempGlobalEntrySummary);**
    INSERT;
    LastSummaryEntryNo := "Entry No.";
  END ELSE
    HasExpiredItems := TRUE;

**Comment by ttaeufer** [comment]
SummarizeInventoryFEFO (new Parameter ItemLedgEntry)

We looked at the publishers again.
The publisher in the function SummarizeAdjustmentBinFEFO is required, but unfortunately a parameter (ItemLedgEntry) was missing in the event request.
We have two more fields that we need to write in the Entry Summary table. This is not so easy, the idea is to hang two variables on the Entry Summary table (Table Extension) and fill them with Get (InsertEntrySummaryFEFO) and Set (SummarizeAdjustmentBinFEFO) functions.

OnBeforeInsertEntrySummaryFEFOSummarizeInventoryFEFO (var TempGlobalEntrySummary, ItemLedgEntry);




SummarizeAdjustmentBinFEFO (new Parameter: WhseEntry)

As with the event request for the function SummarizeInventoryFEFO, another parameter is required for this request (WhseEntry)

OnBeforeInsertEntrySummaryFEFOSummarizeAdjustmentBinFEFO (var TempGlobalEntrySummary, WhseEntry);
