### ISSUE TITLE
[request-for-external] codeunit 1313 "Correct Posted Purch. Invoice"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#19732]
Please make function ErrorHelperHeader Global

```
procedure ErrorHelperHeader(HeaderErrorType: Enum "Correct Purch. Inv. Error Type"; PurchInvHeader: Record "Purch. Inv. Header")
```

Has already been asked again in
https://github.com/microsoft/ALAppExtensions/issues/18107
but it is not included in latest w1 onprem 20.3.42673.43026

**Comment by AlexanderYakunin** [comment]
We do not expose new procedures in PROD versions, it will be available in version 21 only.
