### ISSUE TITLE
[request-for-external] table 81 "Gen. Journal Line"

### ISSUE THREAD

**Issue by panas78** [microsoft/ALAppExtensions#19735]
Please make function UpdateDescription protected

```
protected procedure UpdateDescription(Name: Text[100])
```

Has already been asked again in
https://github.com/microsoft/ALAppExtensions/issues/18115
https://github.com/microsoft/ALAppExtensions/issues/15831
but it is not included in latest w1 onprem 20.3.42673.43026

**Comment by AlexanderYakunin** [comment]
We do not expose new procedures in PROD versions, it will be available in version 21 only.
