### ISSUE TITLE
"Shipping Agent" table: remove [Scope('OnPrem')] from procedure ShippingAgentVendorOrContact

### ISSUE THREAD

**Issue by AngeloCopelli** [microsoft/ALAppExtensions#19745]
ShippingAgentVendorOrContact

![image](https://user-images.githubusercontent.com/51199875/183087721-aaff1aef-a540-4f51-ab80-aeb35a9d91b6.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45057.
