### ISSUE TITLE
"Shipment Method" table: remove [Scope('OnPrem')] from procedure ThirdPartyLoader and CheckShipMethod3rdPartyLoader

### ISSUE THREAD

**Issue by AngeloCopelli** [microsoft/ALAppExtensions#19744]
ThirdPartyLoader
CheckShipMethod3rdPartyLoader

![image](https://user-images.githubusercontent.com/51199875/183079208-deb056de-4e9f-4a9d-aa48-e9749ec04f8f.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45057.
