### ISSUE TITLE
"Vendor Bill Line" table: remove [Scope('OnPrem')] from procedure GetVendBillWithhTax

### ISSUE THREAD

**Issue by AngeloCopelli** [microsoft/ALAppExtensions#19747]
GetVendBillWithhTax

There ara also other procedures with the same issue

![image](https://user-images.githubusercontent.com/51199875/183089069-8d720873-c4b1-4645-9004-985d8eef5a66.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45057.
