### ISSUE TITLE
"Sales Line" table: remove [Scope('OnPrem')] from procedure ValidateLineDiscountPercent

### ISSUE THREAD

**Issue by AngeloCopelli** [microsoft/ALAppExtensions#19746]
ValidateLineDiscountPercent

![image](https://user-images.githubusercontent.com/51199875/183088652-c7bcb4ca-3d50-4a1f-88df-4072f5e7121d.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45057.
