### ISSUE TITLE
[Event Request] Table 49 Invoice Post. Buffer - procedure ApplyRoundingForFinalPosting

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#19750]
Dear ALAppExtensions Team,

We would like to request the following change

    internal procedure ApplyRoundingForFinalPosting()
    begin
        ApplyRoundingValueForFinalPosting(TempInvoicePostBufferRounding.Amount, Amount);
        ApplyRoundingValueForFinalPosting(TempInvoicePostBufferRounding."VAT Amount", "VAT Amount");
        ApplyRoundingValueForFinalPosting(TempInvoicePostBufferRounding."VAT Base Amount", "VAT Base Amount");
        **//--> change request
        OnAfterApplyRoundingForFinalPosting(Rec,TempInvoicePostBufferRounding)
        //<-- change request**
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterApplyRoundingForFinalPosting(var InvoicePostBuffer: Record "Invoice Post. Buffer"; TempInvoicePostBufferRounding: Record "Invoice Post. Buffer" temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51300.
