### ISSUE TITLE
[Event Parameter Change] Codeunit 5761 Whse.-Post Receipt (Yes/No) - procedure Code - event OnAfterConfirmPost

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19754]
We would like the parameter/-s IsHandled added to the following event.

Codeunit 5761 Whse.-Post Receipt (Yes/No) - procedure Code - event OnAfterConfirmPost

Original:

```
OnAfterConfirmPost(WhseReceiptLine);

[IntegrationEvent(false, false)]
local procedure OnAfterConfirmPost(WhseReceiptLine: Record "Warehouse Receipt Line")
begin
end;
```

Change:

```
IsHandled := false; // <-- ADDED
OnAfterConfirmPost(WhseReceiptLine, IsHandled); // <-- ADDED
if IsHandled then // <-- ADDED
    exit; // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnAfterConfirmPost(WhseReceiptLine: Record "Warehouse Receipt Line"; var IsHandled: Boolean) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46829.
