### ISSUE TITLE
ABS Container Content - Folder Display

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/ALAppExtensions#19756]
There is something wonky with table 9043 "ABS Container Content" and from the Azure Blob Storage API. 

I've created a few test folders and files
![image](https://user-images.githubusercontent.com/35929603/183361277-b300f4d3-c59f-4e64-9ea0-56801bb58211.png)

and created subfolders 
![image](https://user-images.githubusercontent.com/35929603/183361327-b68b4988-3f9a-4b25-97e2-d66b49f0b069.png)

and subsubfolders
![image](https://user-images.githubusercontent.com/35929603/183361411-73a3d606-3822-4d39-ab95-fce2b98a51b2.png)
![image](https://user-images.githubusercontent.com/35929603/183361432-9c491969-7c31-44d0-b397-e9004be6dbf2.png)

then I created a Page on the ABS Container Content table with a filter to the content Type "Directory" and ShowAsTree with IndenationColumn "Level"
![image](https://user-images.githubusercontent.com/35929603/183361631-f16138f2-ef18-4714-aab9-0db96a706b4f.png)

unfortunately it seems like the first folder name is repeated for the following folders:
![image](https://user-images.githubusercontent.com/35929603/183361953-0d80ff6a-eb4d-4fda-97b2-66036000ec41.png)

could you please check if that's a bug or I'm doing something wrong?

**Comment by JulianTillmann** [comment]
Additionally it would be great if Directories got a value for "Full Name" as well. Right now it would be difficult to know which folder is selected if the name is used elsewhere as well

**Comment by AlexanderYakunin** [comment]
@JesperSchulz

**Comment by JesperSchulz** [comment]
We'll look into it. It might take us a little while, though...

**Comment by JulianTillmann** [comment]
That's too bad, we wanted to use this for creating an app :-/

**Comment by mazhelez** [comment]
Hey @JulianTillmann nice catch!

The code for Azure Blob Storage API is all in this repo and, to be perfectly honest, the fastest way to get this issue fixed is... well, to do it yourself⭐ 
Just create a pull request with a fix and we'll gladly uptake it!

**Comment by JulianTillmann** [comment]
I created PR #19976 that should hopefully fix it.

**Comment by JesperSchulz** [comment]
That is awesome! Progress will be tracked in the new PR. Closing issue 🥳
