### ISSUE TITLE
[Extensibility Request] Page 9850 - Tenant Permissions

### ISSUE THREAD

**Issue by Codey42** [microsoft/ALAppExtensions#19759]
Dear ALAppExtensions team,

Through this issue we would like to request setting the following variables as protected in Page 9850 Tenant Permissions:

```AL
protected var
    CurrentAppID: Text;
    CurrentRoleID: Text;
    Show: Option "Only In Permission Set",All;
    IsNewRecord: Boolean;
    AllowChangePrimaryKey: Boolean;
    AddPermissionsQst: Label 'Do you want to add the recorded permissions?';
    StartRecordingQst: Label 'Do you want to start the recording now?';
    SingleFilterSelected: Boolean;
```

Furthermore, we would like to have the method `AddLoggedPermissions` public (no `local` at the beginning of the signature) so it is usable by an extension:

```AL
procedure AddLoggedPermissions(var TablePermissionBuffer: Record "Table Permission Buffer")

```

**Comment by mazhelez** [comment]
@Codey42 The page is about to be obsolete in version 21.0 in favor for another page.

We will not invest in altering obsolete objects. If still needed, please create a new issue (targeting version 21.0)

**Comment by Codey42** [comment]
@mazhelez We have analyzed until version 21.0 and discovered that there are no "obsolete"-properties set in this Page.

Therefore it is / was unknown to extension developers, that this page is about to be obsolete.

Furthermore we would like to know what will be the replacement page for this page in version 21.0 so that we are able to plan for future versions.

Thanks in advance.

**Comment by stkillen** [comment]
Page 9850 "Tenant Permissions" is obsoleted in v. 21.0, which I've just verified. The obsolete reason is _'Replaced by the Permission Set page.'_. You can find the new page in the System Application module "Permission Sets" (page 9855 "Permission Set"). 

If you do create a new issue targeting the new page, please provide a justification for why you need these variables protected. What's the scenario where you need these protected?
