### ISSUE TITLE
Report 1308 "Standard Sales - Shipment" FillLeftHeader()

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#19764]
Please add an publisher to the procedure FillLefHeader in Report 1308 "Standard Sales - Shipment":

```
        OnBeforeFillLeftHeader(IsHandled);
        if IsHandled then
            exit;
```
Definition:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeFillLeftHeader(var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46955.
