### ISSUE TITLE
[Event Request] Report 1304 "Standard Sales - Quote" OnAfterGetRecord 

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#19769]
Please add an publisher to the procedure OnAfterGetRecord in Report 1304 "Standard Sales - Quote":
```
                SalesPost.GetSalesLines(Header, Line, 0);
                Line.CalcVATAmountLines(0, Header, Line, VATAmountLine);
                Line.UpdateVATOnLines(0, Header, Line, VATAmountLine);
                **OnAfterUpdateVATOnLines(Header, Line);**
```
Definition: 
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateVATOnLines(Header: Record "Sales Header"; var Line: Record "Sales Line")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47995.
