### ISSUE TITLE
Report 1308 "Standard Sales - Shipment" Protected variables

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#19767]
Hi,

can you please mark following variables to protected in Report 1308 "Standard Sales - Shipment":
FirstLineHasBeenOutput
SalespersonPurchaser

**Comment by AlexanderYakunin** [comment]
PaymentTerms does not exist in this report. ItemTotalQty is local variable, cannot be made protected

**Comment by samra-singhammer** [comment]
Thank you for the feedback. The request is updated.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45464.
