### ISSUE TITLE
Generating xml file without <?xml> tag [Extensibility Request] 

### ISSUE THREAD

**Issue by Vinayak-Bhosale** [microsoft/ALAppExtensions#19776]
I am using Codeunit 1239 “XML Buffer Reader” to generate xml file. File generated with first line as ‘<?xml version="1.0" encoding="UTF-8"?>’. Customer don’t want this line to be generated.

Can you kindly provide event @ line 50 with Header in Codeunit 1239 “XML Buffer Reader” to resolve the issue.

![image](https://user-images.githubusercontent.com/88087159/183457198-89f76919-cdbd-4441-b7be-3e72a095fe6a.png)

**Comment by AlexanderYakunin** [comment]
Please provide event definition and placement in the code

**Comment by Vinayak-Bhosale** [comment]
**Event Definition:**
[IntegrationEvent(false, false)]
local procedure OnAfterHeaderInitialized(var Header: Text; var IsHandled: Boolean)
begin
end;

**Code to be added @ line no 50:** --> (Local Variable need to define --> IsHandled: Boolean;)
IsHandled := false;                 
OnAfterHeaderInitialized(Header, IsHandled);
if IsHandled then
    exit;
![image](https://user-images.githubusercontent.com/88087159/183843315-a96a0df1-fdb7-4841-a24b-d8766e819b3b.png)

**Comment by Vinayak-Bhosale** [comment]
@AlexanderYakunin 

Kindly update

**Comment by Vinayak-Bhosale** [comment]
Need to Update the Codeunit on below Environments:

https://lscentral.bc.dynamics.com/61e1bedc-6d60-4bd4-8b3a-a8c747843794/production
https://lscentral.bc.dynamics.com/61e1bedc-6d60-4bd4-8b3a-a8c747843794/LSSandbox

@AlexanderYakunin

**Comment by Vinayak-Bhosale** [comment]
@AlexanderYakunin : Kindly update

**Comment by AlexanderYakunin** [comment]
Hello! We cannot update environments with event, we simply implement events into our code base. If you have questions, please ask specifically.

**Comment by Vinayak-Bhosale** [comment]
Can you kindly provide us the 'Hotfix' for the above issue specified. So that we can plan our customization accordingly.

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by JesperSchulz** [comment]
Closing as per comment above.
