### ISSUE TITLE
Report 1304 "Standard Sales - Quote" SetLanguage()

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#19770]
Please add an publisher to the procedure SetLanguage in Report 1304 "Standard Sales - Quote":

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetLanguage()
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46955.
