### ISSUE TITLE
Report 1304 "Standard Sales - Quote" Protected variables

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#19773]
In the report Report 1304 "Standard Sales - Quote" please set following variables as protected: 

- FirstLineHasBeenOutput
- ShptMethodDescLbl
- PaymentTermsDescLbl
- ShipmentMethod
- PaymentTerms
- BillToCustomerNoLbl
- SalespersonPurchaser

**Comment by AlexanderYakunin** [comment]
VATAmountLine is data item and cannot be made protected. DiscountPercentLblText is not found in our app.

**Comment by AlexanderYakunin** [comment]
Please recheck you request; you use non-existing references. If this is not for W1, please always specify country code.

**Comment by samra-singhammer** [comment]
Thank you for your feedback. I have updated the request.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45464.
