### ISSUE TITLE
[Event Request] Codeunit 12 Gen. Jnl.-Post Line - OnPostDtldCustLedgEntriesOnAfterAssignCustAccNo, OnUnapplyCustLedgEntryOnAfterAssignCustGLAccountNo, OnUnapplyVendLedgEntryOnAfterAssignVendGLAccountNo

### ISSUE THREAD

**Issue by vperezLaberit** [microsoft/ALAppExtensions#19786]
Hello, we would like to change the AccNo assigned in order to set other Account No. 

The events requested are: 
OnPostDtldCustLedgEntriesOnAfterAssignCustAccNo(GenJnlLine, CustPostingGr, AccNo);
OnUnapplyCustLedgEntryOnAfterAssignCustGLAccountNo(GenJnlLine, CustPostingGr, GLAccountNo); 
OnUnapplyVendLedgEntryOnAfterAssignVendGLAccountNo(GenJnlLine, VendPostingGr, GLAccountNo); 

You can find the code  added searching the tag **New Event**
Thank you!

        Procedure PostDtldCustLedgEntries(GenJnlLine: Record "Gen. Journal Line"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; CustPostingGr: Record "Customer Posting Group"; LedgEntryInserted: Boolean) DtldLedgEntryInserted: Boolean
    var
        TempDimPostingBuffer: Record "Dimension Posting Buffer" temporary;
        DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry";
        Currency: Record Currency;
        GLEntry: Record "G/L Entry";
        DtldCustLedgEntry2: Record "Detailed Cust. Ledg. Entry";
        AdjAmount: array[4] of Decimal;
        DtldCustLedgEntryNoOffset: Integer;
        SaveEntryNo: Integer;
        ReceivableAccAmtLCY: Decimal;
        ReceivableAccAmtAddCurr: Decimal;
        ExistDtldCVLedgEntryBuf: Boolean;
        FindBill: Boolean;
        IsHandled: Boolean;
    begin
        if GenJnlLine."Account Type" <> GenJnlLine."Account Type"::Customer then
            exit;
  if DtldCustLedgEntry.FindLast() then
            DtldCustLedgEntryNoOffset := DtldCustLedgEntry."Entry No."
        else
            DtldCustLedgEntryNoOffset := 0; 

        DtldCVLedgEntryBuf.Reset();
        OnAfterSetDtldCustLedgEntryNoOffset(DtldCVLedgEntryBuf);
        DtldCVLedgEntryBuf.SetRange("Initial Document Type", DtldCVLedgEntryBuf."Initial Document Type"::Bill);
        if DtldCVLedgEntryBuf.FindFirst() then
            FindBill := true;
        DtldCVLedgEntryBuf.Reset();
        if DtldCVLedgEntryBuf.FindSet() then begin
            if LedgEntryInserted or FindBill then begin
                SaveEntryNo := NextEntryNo;
                IncrNextEntryNo();
                NextEntryNo2 := NextEntryNo;
            end;
            repeat
                InsertDtldCustLedgEntry(GenJnlLine, DtldCVLedgEntryBuf, DtldCustLedgEntry, DtldCustLedgEntryNoOffset);
                UpdateCustLedgEntryStats(DtldCustLedgEntry."Cust. Ledger Entry No.");
                IsHandled := false;
                OnPostDtldCustLedgEntriesOnBeforeUpdateTotalAmounts(GenJnlLine, DtldCustLedgEntry, IsHandled, DtldCVLedgEntryBuf);
                if not IsHandled then
                    UpdateTotalAmounts(TempDimPostingBuffer, GenJnlLine."Dimension Set ID", DtldCVLedgEntryBuf);
                IsHandled := false;
                OnPostDtldCustLedgEntriesOnBeforePostDtldCustLedgEntry(DtldCVLedgEntryBuf, AddCurrencyCode, GenJnlLine, CustPostingGr, AdjAmount, IsHandled);
                if not IsHandled then
                    if ((DtldCVLedgEntryBuf."Amount (LCY)" <> 0) or
                        (DtldCVLedgEntryBuf."VAT Amount (LCY)" <> 0)) or
                       ((AddCurrencyCode <> '') and (DtldCVLedgEntryBuf."Additional-Currency Amount" <> 0))
                    then
                        case DtldCVLedgEntryBuf."Entry Type" of
                            DtldCVLedgEntryBuf."Entry Type"::"Initial Entry":
                                if CheckCarteraPostDtldCustLE(
                                     GenJnlLine, DtldCustLedgEntry, ReceivableAccAmtLCY, ReceivableAccAmtAddCurr, false)
                                then
                                    DocAmountLCY := DtldCVLedgEntryBuf."Amount (LCY)";
                            DtldCVLedgEntryBuf."Entry Type"::Application:
                                if CheckCarteraPostDtldCustLE(
                                     GenJnlLine, DtldCustLedgEntry, ReceivableAccAmtLCY, ReceivableAccAmtAddCurr, false)
                                then begin
                                    GetCurrency(Currency, DtldCVLedgEntryBuf."Currency Code");
                                    CheckNonAddCurrCodeOccurred(Currency.Code);
                                    CreateGLEntry(
                                      GenJnlLine, CustPostingGr.GetReceivablesAccount, -DtldCVLedgEntryBuf."Amount (LCY)", 0,
                                      DtldCVLedgEntryBuf."Currency Code" = AddCurrencyCode);
                                end;
                            DtldCVLedgEntryBuf."Entry Type"::Redrawal:
                                ;
                            DtldCVLedgEntryBuf."Entry Type"::Rejection:
                                ;
                            else
                                PostDtldCustLedgEntry(GenJnlLine, DtldCVLedgEntryBuf, CustPostingGr, AdjAmount);
                        end;
            until DtldCVLedgEntryBuf.Next() = 0;

            ExistDtldCVLedgEntryBuf := not DtldCVLedgEntryBuf.IsEmpty;
            DtldLedgEntryInserted := not DtldCVLedgEntryBuf.IsEmpty;
            DtldCVLedgEntryBuf.DeleteAll();

            if UseGLBillsAccount(GenJnlLine) then
                AccNo := CustPostingGr.GetBillsAccount(false)
            else
                AccNo := CustPostingGr.GetReceivablesAccount();

         **New Event**
         **OnPostDtldCustLedgEntriesOnAfterAssignCustAccNo(GenJnlLine, CustPostingGr, AccNo); **

            CalcPostingBufferTotals(TempDimPostingBuffer);
            ReceivableAccAmtLCY :=
              TempDimPostingBuffer.Amount -
              (DocAmountLCY + DiscDocAmountLCY +
               CollDocAmountLCY + RejDocAmountLCY + DiscRiskFactAmountLCY +
               DiscUnriskFactAmountLCY + CollFactAmountLCY);
            ReceivableAccAmtAddCurr :=
              TempDimPostingBuffer."Amount (ACY)" -
              (DocAmtCalcAddCurrency(GenJnlLine, DocAmountLCY) + DocAmtCalcAddCurrency(GenJnlLine, DiscDocAmountLCY) +
               DocAmtCalcAddCurrency(GenJnlLine, CollDocAmountLCY) + DocAmtCalcAddCurrency(GenJnlLine, RejDocAmountLCY) +
               DocAmtCalcAddCurrency(GenJnlLine, DiscRiskFactAmountLCY) + DocAmtCalcAddCurrency(GenJnlLine, DiscUnriskFactAmountLCY) +
               DocAmtCalcAddCurrency(GenJnlLine, CollFactAmountLCY));

            CustLedgEntryInserted2 := LedgEntryInserted;
...
....
...

 **New Event**
    [IntegrationEvent(false, false)]
    local procedure OnPostDtldCustLedgEntriesOnAfterAssignCustAccNo(GenJournalLine: Record "Gen. Journal Line"; CustPostingGroup: Record "Customer Posting Group"; var AccountNo: Code[20])
    begin
    end;

procedure UnapplyCustLedgEntry(GenJnlLine2: Record "Gen. Journal Line"; DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry")
    var
        Cust: Record Customer;
        CustPostingGr: Record "Customer Posting Group";
        GenJnlLine: Record "Gen. Journal Line";
        DtldCustLedgEntry2: Record "Detailed Cust. Ledg. Entry";
        NewDtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry";
        CustLedgEntry: Record "Cust. Ledger Entry";
        DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer";
        VATEntry: Record "VAT Entry";
        TempVATEntry2: Record "VAT Entry" temporary;
        CurrencyLCY: Record Currency;
        GLEntry: Record "G/L Entry";
        TempDimPostingBuffer: Record "Dimension Posting Buffer" temporary;
#if not CLEAN19
        TempInvoicePostBuffer: Record "Invoice Post. Buffer" temporary;
#endif
        AdjAmount: array[4] of Decimal;
        NextDtldLedgEntryNo: Integer;
        UnapplyVATEntries: Boolean;
        PmtDiscTolExists: Boolean;
        PositiveLCYAppAmt: Decimal;
        NegativeLCYAppAmt: Decimal;
        PositiveACYAppAmt: Decimal;
        NegativeACYAppAmt: Decimal;
        GLAccountNo: Code[20];
        IsHandled: Boolean;
    begin
        GenJnlLine.TransferFields(GenJnlLine2);
        if GenJnlLine."Document Date" = 0D then
            GenJnlLine."Document Date" := GenJnlLine."Posting Date";

        if NextEntryNo = 0 then
            StartPosting(GenJnlLine)
        else
            ContinuePosting(GenJnlLine);

        ReadGLSetup(GLSetup);

        Cust.Get(DtldCustLedgEntry."Customer No.");
        Cust.CheckBlockedCustOnJnls(Cust, GenJnlLine2."Document Type"::Payment, true);

        OnUnapplyCustLedgEntryOnBeforeCheckPostingGroup(GenJnlLine, Cust);
        CustPostingGr.Get(GenJnlLine."Posting Group");
        CustPostingGr.GetReceivablesAccount();

        VATEntry.LockTable();
        DtldCustLedgEntry.LockTable();
        CustLedgEntry.LockTable();

        DtldCustLedgEntry.TestField("Entry Type", DtldCustLedgEntry."Entry Type"::Application);

        DtldCustLedgEntry2.Reset();
        DtldCustLedgEntry2.FindLast();
        NextDtldLedgEntryNo := DtldCustLedgEntry2."Entry No." + 1;
        if DtldCustLedgEntry."Transaction No." = 0 then begin
            DtldCustLedgEntry2.SetCurrentKey("Application No.", "Customer No.", "Entry Type");
            DtldCustLedgEntry2.SetRange("Application No.", DtldCustLedgEntry."Application No.");
        end else begin
            DtldCustLedgEntry2.SetCurrentKey("Transaction No.", "Customer No.", "Entry Type");
            DtldCustLedgEntry2.SetRange("Transaction No.", DtldCustLedgEntry."Transaction No.");
        end;
        DtldCustLedgEntry2.SetRange("Customer No.", DtldCustLedgEntry."Customer No.");
        DtldCustLedgEntry2.SetFilter("Entry Type", '>%1', DtldCustLedgEntry."Entry Type"::"Initial Entry");
        OnUnapplyCustLedgEntryOnAfterDtldCustLedgEntrySetFilters(DtldCustLedgEntry2, DtldCustLedgEntry);
        if DtldCustLedgEntry."Transaction No." <> 0 then begin
            UnapplyVATEntries := false;
            DtldCustLedgEntry2.FindSet();
            repeat
                CheckCarteraAccessPermissions(DtldCustLedgEntry2."Document Situation");
                DtldCustLedgEntry2.TestField(Unapplied, false);
                if IsVATAdjustment(DtldCustLedgEntry2."Entry Type") then
                    UnapplyVATEntries := true;
                if not GLSetup."Pmt. Disc. Excl. VAT" and GLSetup."Adjust for Payment Disc." then
                    if IsVATExcluded(DtldCustLedgEntry2."Entry Type") then
                        UnapplyVATEntries := true;
                if DtldCustLedgEntry2."Entry Type" = DtldCustLedgEntry2."Entry Type"::"Payment Discount Tolerance (VAT Excl.)" then
                    PmtDiscTolExists := true;
            until DtldCustLedgEntry2.Next() = 0;

            OnUnapplyCustLedgEntryOnBeforePostUnapply(DtldCustLedgEntry, DtldCustLedgEntry2);

            PostUnapply(
              GenJnlLine, VATEntry, VATEntry.Type::Sale,
              DtldCustLedgEntry."Customer No.", DtldCustLedgEntry."Transaction No.", UnapplyVATEntries, TempVATEntry);

            OnUnapplyCustLedgEntryOnAfterPostUnapply(GenJnlLine, DtldCustLedgEntry, DtldCustLedgEntry2);

            if PmtDiscTolExists then
                ProcessTempVATEntryCust(DtldCustLedgEntry2, TempVATEntry)
            else begin
                DtldCustLedgEntry2.SetRange("Entry Type", DtldCustLedgEntry2."Entry Type"::"Payment Tolerance (VAT Excl.)");
                ProcessTempVATEntryCust(DtldCustLedgEntry2, TempVATEntry);
                DtldCustLedgEntry2.SetRange("Entry Type", DtldCustLedgEntry2."Entry Type"::"Payment Discount (VAT Excl.)");
                ProcessTempVATEntryCust(DtldCustLedgEntry2, TempVATEntry);
                DtldCustLedgEntry2.SetFilter("Entry Type", '>%1', DtldCustLedgEntry."Entry Type"::"Initial Entry");
            end;
        end;

        // Look one more time
        OnOnUnapplyCustLedgEntryOnBeforeSecondLook(DtldCustLedgEntry2, NextDtldLedgEntryNo);
        DtldCustLedgEntry2.FindSet();
        TempDimPostingBuffer.DeleteAll();
        repeat
            DtldCustLedgEntry2.TestField(Unapplied, false);
            InsertDtldCustLedgEntryUnapply(GenJnlLine, NewDtldCustLedgEntry, DtldCustLedgEntry2, NextDtldLedgEntryNo, CustPostingGr);

            DtldCVLedgEntryBuf.Init();
            DtldCVLedgEntryBuf.TransferFields(NewDtldCustLedgEntry);
            OnUnapplyCustLedgEntryOnAfterFillDtldCVLedgEntryBuf(GenJnlLine, DtldCVLedgEntryBuf);
            SetAddCurrForUnapplication(DtldCVLedgEntryBuf);
            CurrencyLCY.InitRoundingPrecision();

            if (DtldCustLedgEntry2."Transaction No." <> 0) and IsVATExcluded(DtldCustLedgEntry2."Entry Type") then begin
                UnapplyExcludedVAT(
                  TempVATEntry2, DtldCustLedgEntry2."Transaction No.", DtldCustLedgEntry2."VAT Bus. Posting Group",
                  DtldCustLedgEntry2."VAT Prod. Posting Group", DtldCustLedgEntry2."Gen. Prod. Posting Group");
                DtldCVLedgEntryBuf."VAT Amount (LCY)" :=
                  CalcVATAmountFromVATEntry(DtldCVLedgEntryBuf."Amount (LCY)", TempVATEntry2, CurrencyLCY);
            end;
            IsHandled := false;
            OnOnUnapplyCustLedgEntryOnBeforeUpdateTotalAmounts(IsHandled, GenJnlLine, DtldCVLedgEntryBuf);
            if not IsHandled then begin
                UpdateTotalAmounts(TempDimPostingBuffer, GenJnlLine."Dimension Set ID", DtldCVLedgEntryBuf);
                OnUnapplyCustLedgEntryOnAfterUpdateTotals(GenJnlLine, DtldCVLedgEntryBuf);

                if DtldCVLedgEntryBuf."Entry Type" = DtldCVLedgEntryBuf."Entry Type"::Application then
                    if DtldCVLedgEntryBuf."Amount (LCY)" >= 0 then begin
                        PositiveLCYAppAmt := PositiveLCYAppAmt + DtldCVLedgEntryBuf."Amount (LCY)";
                        PositiveACYAppAmt :=
                          PositiveACYAppAmt + DtldCVLedgEntryBuf."Additional-Currency Amount";
                    end else begin
                        NegativeLCYAppAmt := NegativeLCYAppAmt + DtldCVLedgEntryBuf."Amount (LCY)";
                        NegativeACYAppAmt :=
                          NegativeACYAppAmt + DtldCVLedgEntryBuf."Additional-Currency Amount";
                    end;

                if not (DtldCVLedgEntryBuf."Entry Type" in [
                                                            DtldCVLedgEntryBuf."Entry Type"::"Initial Entry",
                                                            DtldCVLedgEntryBuf."Entry Type"::Application])
                then
                    CollectAdjustment(AdjAmount,
                      -DtldCVLedgEntryBuf."Amount (LCY)", -DtldCVLedgEntryBuf."Additional-Currency Amount");
            end;

            PostDtldCustLedgEntryUnapply(
              GenJnlLine, DtldCVLedgEntryBuf, CustPostingGr, DtldCustLedgEntry2."Transaction No.");

            DtldCustLedgEntry2.Unapplied := true;
            DtldCustLedgEntry2."Unapplied by Entry No." := NewDtldCustLedgEntry."Entry No.";
            DtldCustLedgEntry2.Modify();

            OnUnapplyCustLedgEntryOnBeforeUpdateCustLedgEntry(DtldCustLedgEntry2, DtldCVLedgEntryBuf);
            UpdateCustLedgEntry(DtldCustLedgEntry2, GenJnlLine);
        until DtldCustLedgEntry2.Next() = 0;

        IsHandled := false;
#if not CLEAN19
        CopyDimPostBufToInvPostBuf(TempDimPostingBuffer, TempInvoicePostBuffer);
        OnBeforeCreateGLEntriesForTotalAmountsUnapply(DtldCustLedgEntry, CustPostingGr, GenJnlLine, TempInvoicePostBuffer, IsHandled);
        CopyInvPostBufToDimPostBuf(TempInvoicePostBuffer, TempDimPostingBuffer);
#endif
        OnBeforeCreateGLEntriesForTotalAmountsUnapplyV19(DtldCustLedgEntry, CustPostingGr, GenJnlLine, TempDimPostingBuffer, IsHandled);
        if not IsHandled then
            CreateGLEntriesForTotalAmountsUnapply(GenJnlLine, TempDimPostingBuffer, GetCustomerReceivablesAccount(GenJnlLine, CustPostingGr));

        OnUnapplyCustLedgEntryOnAfterCreateGLEntriesForTotalAmounts(GenJnlLine2, DtldCustLedgEntry, GLReg);

        if IsTempGLEntryBufEmpty then begin
            if GenJnlLine."Financial Void" then
                GLAccountNo := CustPostingGr.GetReceivablesAccount
            else
                if CheckDtldCustLegderEntryCreateBills(DtldCustLedgEntry) then
                    GLAccountNo := CustPostingGr.GetBillsAccount(false)
                else
                    GLAccountNo := CustPostingGr.GetReceivablesAccount;

 **New Event**
         **OnUnapplyCustLedgEntryOnAfterAssignCustGLAccountNo (GenJnlLine, CustPostingGr, GLAccountNo ); **

            InitGLEntry(
              GenJnlLine, GLEntry, GLAccountNo, PositiveLCYAppAmt,
              PositiveACYAppAmt, false, true);
            InsertGLEntry(GenJnlLine, GLEntry, false);
            InitGLEntry(
              GenJnlLine, GLEntry, CustPostingGr."Receivables Account", NegativeLCYAppAmt,
              NegativeACYAppAmt, false, true);
            InsertGLEntry(GenJnlLine, GLEntry, false);
        end;

        CheckPostUnrealizedVAT(GenJnlLine, true);

        FinishPosting(GenJnlLine);
    end;

 **New Event**
    [IntegrationEvent(false, false)]
    local procedure OnUnapplyCustLedgEntryOnAfterAssignCustGLAccountNo (GenJournalLine: Record "Gen. Journal Line"; CustPostingGroup: Record "Customer Posting Group"; var GLAccountNo : Code[20])
    begin
    end;

  procedure UnapplyVendLedgEntry(GenJnlLine2: Record "Gen. Journal Line"; DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry")
    var
        Vend: Record Vendor;
        VendPostingGr: Record "Vendor Posting Group";
        GenJnlLine: Record "Gen. Journal Line";
        DtldVendLedgEntry2: Record "Detailed Vendor Ledg. Entry";
        NewDtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry";
        VendLedgEntry: Record "Vendor Ledger Entry";
        DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer";
        VATEntry: Record "VAT Entry";
        TempVATEntry2: Record "VAT Entry" temporary;
        CurrencyLCY: Record Currency;
        GLEntry: Record "G/L Entry";
        TempDimPostingBuffer: Record "Dimension Posting Buffer" temporary;
#if not CLEAN19
        TempInvPostBuffer: Record "Invoice Post. Buffer" temporary;
#endif
        AdjAmount: array[4] of Decimal;
        NextDtldLedgEntryNo: Integer;
        UnapplyVATEntries: Boolean;
        PmtDiscTolExists: Boolean;
        PositiveLCYAppAmt: Decimal;
        NegativeLCYAppAmt: Decimal;
        PositiveACYAppAmt: Decimal;
        NegativeACYAppAmt: Decimal;
        GLAccountNo: Code[20];
        IsHandled: Boolean;
    begin
        GenJnlLine.TransferFields(GenJnlLine2);
        if GenJnlLine."Document Date" = 0D then
            GenJnlLine."Document Date" := GenJnlLine."Posting Date";

        if NextEntryNo = 0 then
            StartPosting(GenJnlLine)
        else
            ContinuePosting(GenJnlLine);

        ReadGLSetup(GLSetup);

        Vend.Get(DtldVendLedgEntry."Vendor No.");
        Vend.CheckBlockedVendOnJnls(Vend, GenJnlLine2."Document Type"::Payment, true);

        OnUnapplyVendLedgEntryOnBeforeCheckPostingGroup(GenJnlLine, Vend);
        GetVendorPostingGroup(GenJnlLine, VendPostingGr);
        VendPostingGr.GetPayablesAccount();

        VATEntry.LockTable();
        DtldVendLedgEntry.LockTable();
        VendLedgEntry.LockTable();

        DtldVendLedgEntry.TestField("Entry Type", DtldVendLedgEntry."Entry Type"::Application);

        DtldVendLedgEntry2.Reset();
        DtldVendLedgEntry2.FindLast();
        NextDtldLedgEntryNo := DtldVendLedgEntry2."Entry No." + 1;
        if DtldVendLedgEntry."Transaction No." = 0 then begin
            DtldVendLedgEntry2.SetCurrentKey("Application No.", "Vendor No.", "Entry Type");
            DtldVendLedgEntry2.SetRange("Application No.", DtldVendLedgEntry."Application No.");
        end else begin
            DtldVendLedgEntry2.SetCurrentKey("Transaction No.", "Vendor No.", "Entry Type");
            DtldVendLedgEntry2.SetRange("Transaction No.", DtldVendLedgEntry."Transaction No.");
        end;
        DtldVendLedgEntry2.SetRange("Vendor No.", DtldVendLedgEntry."Vendor No.");
        DtldVendLedgEntry2.SetFilter("Entry Type", '>%1', DtldVendLedgEntry."Entry Type"::"Initial Entry");
        OnUnapplyVendLedgEntryOnAfterFilterSourceEntries(DtldVendLedgEntry, DtldVendLedgEntry2);
        if DtldVendLedgEntry."Transaction No." <> 0 then begin
            UnapplyVATEntries := false;
            DtldVendLedgEntry2.FindSet();
            repeat
                CheckCarteraAccessPermissions(DtldVendLedgEntry2."Document Situation");
                DtldVendLedgEntry2.TestField(Unapplied, false);
                if IsVATAdjustment(DtldVendLedgEntry2."Entry Type") then
                    UnapplyVATEntries := true;
                if not GLSetup."Pmt. Disc. Excl. VAT" and GLSetup."Adjust for Payment Disc." then
                    if IsVATExcluded(DtldVendLedgEntry2."Entry Type") then
                        UnapplyVATEntries := true;
                if DtldVendLedgEntry2."Entry Type" = DtldVendLedgEntry2."Entry Type"::"Payment Discount Tolerance (VAT Excl.)" then
                    PmtDiscTolExists := true;
            until DtldVendLedgEntry2.Next() = 0;

            OnUnapplyVendLedgEntryOnBeforePostUnapply(DtldVendLedgEntry, DtldVendLedgEntry2);

            PostUnapply(
              GenJnlLine, VATEntry, VATEntry.Type::Purchase,
              DtldVendLedgEntry."Vendor No.", DtldVendLedgEntry."Transaction No.", UnapplyVATEntries, TempVATEntry);

            OnUnapplyVendLedgEntryOnAfterPostUnapply(GenJnlLine, DtldVendLedgEntry, DtldVendLedgEntry2);

            if PmtDiscTolExists then
                ProcessTempVATEntryVend(DtldVendLedgEntry2, TempVATEntry)
            else begin
                DtldVendLedgEntry2.SetRange("Entry Type", DtldVendLedgEntry2."Entry Type"::"Payment Tolerance (VAT Excl.)");
                ProcessTempVATEntryVend(DtldVendLedgEntry2, TempVATEntry);
                DtldVendLedgEntry2.SetRange("Entry Type", DtldVendLedgEntry2."Entry Type"::"Payment Discount (VAT Excl.)");
                ProcessTempVATEntryVend(DtldVendLedgEntry2, TempVATEntry);
                DtldVendLedgEntry2.SetFilter("Entry Type", '>%1', DtldVendLedgEntry2."Entry Type"::"Initial Entry");
            end;
        end;

        // Look one more time
        OnUnapplyVendLedgEntryOnBeforeSecondLook(DtldVendLedgEntry2, NextDtldLedgEntryNo);
        DtldVendLedgEntry2.FindSet();
        TempDimPostingBuffer.DeleteAll();
        repeat
            DtldVendLedgEntry2.TestField(Unapplied, false);
            InsertDtldVendLedgEntryUnapply(GenJnlLine, NewDtldVendLedgEntry, DtldVendLedgEntry2, NextDtldLedgEntryNo);

            DtldCVLedgEntryBuf.Init();
            DtldCVLedgEntryBuf.TransferFields(NewDtldVendLedgEntry);
            OnUnapplyVendLedgEntryOnAfterFillDtldCVLedgEntryBuf(GenJnlLine, DtldCVLedgEntryBuf);
            SetAddCurrForUnapplication(DtldCVLedgEntryBuf);
            CurrencyLCY.InitRoundingPrecision();

            if (DtldVendLedgEntry2."Transaction No." <> 0) and IsVATExcluded(DtldVendLedgEntry2."Entry Type") then begin
                UnapplyExcludedVAT(
                  TempVATEntry2, DtldVendLedgEntry2."Transaction No.", DtldVendLedgEntry2."VAT Bus. Posting Group",
                  DtldVendLedgEntry2."VAT Prod. Posting Group", DtldVendLedgEntry2."Gen. Prod. Posting Group");
                DtldCVLedgEntryBuf."VAT Amount (LCY)" :=
                  CalcVATAmountFromVATEntry(DtldCVLedgEntryBuf."Amount (LCY)", TempVATEntry2, CurrencyLCY);
            end;
            IsHandled := false;
            OnUnapplyVendLedgEntryOnBeforeUpdateTotalAmounts(IsHandled, GenJnlLine, DtldCVLedgEntryBuf);
            if not IsHandled then begin
                UpdateTotalAmounts(TempDimPostingBuffer, GenJnlLine."Dimension Set ID", DtldCVLedgEntryBuf);

                if DtldCVLedgEntryBuf."Entry Type" = DtldCVLedgEntryBuf."Entry Type"::Application then
                    if DtldCVLedgEntryBuf."Amount (LCY)" >= 0 then begin
                        PositiveLCYAppAmt := PositiveLCYAppAmt + DtldCVLedgEntryBuf."Amount (LCY)";
                        PositiveACYAppAmt :=
                          PositiveACYAppAmt + DtldCVLedgEntryBuf."Additional-Currency Amount";
                    end else begin
                        NegativeLCYAppAmt := NegativeLCYAppAmt + DtldCVLedgEntryBuf."Amount (LCY)";
                        NegativeACYAppAmt :=
                          NegativeACYAppAmt + DtldCVLedgEntryBuf."Additional-Currency Amount";
                    end;

                if not (DtldCVLedgEntryBuf."Entry Type" in [
                                                            DtldCVLedgEntryBuf."Entry Type"::"Initial Entry",
                                                            DtldCVLedgEntryBuf."Entry Type"::Application])
                then
                    CollectAdjustment(AdjAmount,
                      -DtldCVLedgEntryBuf."Amount (LCY)", -DtldCVLedgEntryBuf."Additional-Currency Amount");
            end;

            PostDtldVendLedgEntryUnapply(
              GenJnlLine, DtldCVLedgEntryBuf, VendPostingGr, DtldVendLedgEntry2."Transaction No.");

            DtldVendLedgEntry2.Unapplied := true;
            DtldVendLedgEntry2."Unapplied by Entry No." := NewDtldVendLedgEntry."Entry No.";
            DtldVendLedgEntry2.Modify();

            OnUnapplyVendLedgEntryOnBeforeUpdateVendLedgEntry(DtldVendLedgEntry2, DtldCVLedgEntryBuf);
            UpdateVendLedgEntry(DtldVendLedgEntry2, GenJnlLine);
        until DtldVendLedgEntry2.Next() = 0;

        IsHandled := false;
#if not CLEAN19
        CopyDimPostBufToInvPostBuf(TempDimPostingBuffer, TempInvPostBuffer);
        OnBeforeCreateGLEntriesForTotalAmountsUnapplyVendor(DtldVendLedgEntry, VendPostingGr, GenJnlLine, TempInvPostBuffer, IsHandled);
        CopyInvPostBufToDimPostBuf(TempInvPostBuffer, TempDimPostingBuffer);
#endif
        OnBeforeCreateGLEntriesForTotalAmountsUnapplyVendorV19(DtldVendLedgEntry, VendPostingGr, GenJnlLine, TempDimPostingBuffer, IsHandled);
        if not IsHandled then
            CreateGLEntriesForTotalAmountsUnapply(GenJnlLine, TempDimPostingBuffer, GetVendorPayablesAccount(GenJnlLine, VendPostingGr));

        OnUnapplyVendLedgEntryOnAfterCreateGLEntriesForTotalAmounts(GenJnlLine2, DtldVendLedgEntry, GLReg);

        if IsTempGLEntryBufEmpty then begin
            if FinancialVoidWithMethodCreateBills(GenJnlLine) then
                GLAccountNo := VendPostingGr.GetBillsAccount
            else
                if GenJnlLine."Financial Void" then
                    GLAccountNo := VendPostingGr.GetPayablesAccount
                else
                    if CheckDtldVendLegderEntryCreateBills(DtldVendLedgEntry) then
                        GLAccountNo := VendPostingGr.GetBillsAccount
                    else
                        GLAccountNo := VendPostingGr.GetPayablesAccount;
 **New Event**
         **OnUnapplyVendLedgEntryOnAfterAssignVendGLAccountNo(GenJnlLine, VendPostingGr, GLAccountNo); **

            InitGLEntry(
              GenJnlLine, GLEntry, VendPostingGr.GetPayablesAccount,
              PositiveLCYAppAmt, PositiveACYAppAmt, false, true);
            InsertGLEntry(GenJnlLine, GLEntry, false);
            InitGLEntry(
              GenJnlLine, GLEntry, GLAccountNo,
              NegativeLCYAppAmt, NegativeACYAppAmt, false, true);
            InsertGLEntry(GenJnlLine, GLEntry, false);
        end;

        CheckPostUnrealizedVAT(GenJnlLine, true);

        FinishPosting(GenJnlLine);
    end;

 **New Event**
    [IntegrationEvent(false, false)]
    local procedure OnUnapplyVendLedgEntryOnAfterAssignVendGLAccountNo(GenJournalLine: Record "Gen. Journal Line"; CustPostingGroup: Record "Customer Posting Group"; var GLAccountNo : Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51294.
