### ISSUE TITLE
When Refunding a check from Check Ledger Entry "Document Type" is blank instead of Refund

### ISSUE THREAD

**Issue by LoanVision** [microsoft/ALAppExtensions#19792]
Hello,
when voiding a check from Check Ledger Entries area Document Type should be filled with Refund (for proper 1099 processing going forward). Currently it's blank and when generating 1099 at the end of the year this is causing wrong amounts.

To reproduce:
1 - Create an AP Invoice
2 - Issue Computer Check/Manual Check to pay this invoice via Payment Journal and post it
3 - From check ledger entries select "Void Check"
4 - After check is voided you you can look at created entries - document type will be blank, should be opposite to initial Document Type

Thank You!

Igor Pcelnikov

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
