### ISSUE TITLE
Request for generic OnReportPrintOutput event

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/ALAppExtensions#198]
There are scenario's where you want to print a report from code directly to a printer, without user interaction. However, with Business Central that's not possible because the server doesn't have access to local printers from code.

I have a working solution using PrintNode. That is based on Report.Save method, get the PDF output in a stream and then send it via a web service to the local printer. But then you need to hard code it for every single report and it doesn't really integrate with report selections.

It would be of great help if it would be possible to get the output of a print job before it actually prints. The current event OnAfterFindPrinter in Codeunit 1 doesn't work for that.

So I was thinking of a generic event OnReportPrintOutput in Codeunit 1 which passes the output as a PDF in a stream. It should also pass the ShowRequestPage parameter (so the code knows that the report was displayed on the screen and then could choose to behave differently). And it should accept a return parameter that indicates that the output is handled so Business Central knows that it doesn't need to print the output.

**Comment by JesperSchulz** [comment]
Closing this issue, as we'll track this under the aforementioned work item internally. Thanks for sharing your idea!
