### ISSUE TITLE
Guided Experience and Checklist Items of type Video

### ISSUE THREAD

**Issue by adejsy** [microsoft/ALAppExtensions#19806]
Previously when a user clicked on "Play Video" on the Checklist the item would be marked as completed.

The behaviour appears to have now changed so that the item on the checklist never gets marked as completed when it is a Video.

As a result you can end up with a checklist with some ticks in it depending on the checklist item type. This does not make for a great user experience when users are tracking which items they have completed and which they haven't.

In my example below, the first two are video's that I have clicked "Play Video" on. The rest are of type "Learn" and those are marked as completed fine.

![image](https://user-images.githubusercontent.com/63508365/183953418-a52a8ea6-bb69-4f7f-b1aa-81c7d8d245e1.png)

**Comment by sorenfriisalexandersen** [comment]
Thank you for the feedback. Can you provide the version of the application and platform from the Help & Support page?
We have not been able to reproduce it.
Also, can you show how you insert these Guided Experience Items , so we can investigate?

Thanks.

**Comment by adejsy** [comment]
Here is an example of the code inserting the Guided Experience Item. They all appear to have been inserted ok.

![image](https://user-images.githubusercontent.com/63508365/184708772-c4af514c-08c6-4a43-be48-978075214a07.png)

Here is the version. This is on Business Central Online. 

![image](https://user-images.githubusercontent.com/63508365/184709412-06a79638-1425-45de-9140-7eea8aa07070.png)

Guided experience items are created in our Extensions install Codeunit.

**Comment by adejsy** [comment]
In addition this might be useful information. The checklist could be a mix of its own "unique" guided experience items and items that are common to multiple roles. Here is an example whereby the checklist items are all linked to multiple roles. Just to mention, our setup has not changed for some time but the behaviour of the checklist appears to - I believe between BC19 and BC20.

Perhaps that is the scenario to test?

![image](https://user-images.githubusercontent.com/63508365/184712176-284e7865-0320-48b2-8e74-accb91cddc5b.png)



![image](https://user-images.githubusercontent.com/63508365/184710077-8893924e-c195-473c-a58d-be6b7189e577.png)

**Comment by sorenfriisalexandersen** [comment]
@adejsy thank you for providing the extra information.

Can you recreate the behavior in a new environment, or is this "only" for upgraded environments?

**Comment by adejsy** [comment]
I managed to finally get round to checking the behaviour in a new environment. This issue does not occur in new environments but seems to occur in existing environments.

**Comment by adejsy** [comment]
Ok actually on saying this is fixed, I have another new 20.5 environment where the issue still seems to exist. Maybve I wait for 21.1 to see if the issue is still there?

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 47790.
