### ISSUE TITLE
Report 5186 Remove Contacts [InDataSet] variable request

### ISSUE THREAD

**Issue by LewisHyettTES** [microsoft/ALAppExtensions#19804]
Please can the variable ReduceRefineSegment: Report "Remove Contacts" in object report 5186 "Remove Contacts" be changed to InDataSet true. 

This would allow us to create a report extension and include additional datasets.

**Comment by AlexanderYakunin** [comment]
This is not a boolean variable, but codeunit. See https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/attributes/devenv-indataset-attribute
