### ISSUE TITLE
[Event Request] - Codeunit 703 OnBeforeFindRecordWithSimilarName

### ISSUE THREAD

**Issue by LewisHyettTES** [microsoft/ALAppExtensions#19807]
Within the codeunit 703 Find Record Management, function "FindRecordByDescriptionAndView" I would like an event before the following code:

Current:
 // Try FINDLAST record with similar "Description"
        if FindRecordWithSimilarName(RecRef, SearchText, SearchFieldNo[2]) then begin
            Result := SearchFieldRef[1].Value;
            exit(1);
        end;

Proposed:
 // Try FINDLAST record with similar "Description"
OnBeforeFindRecordWithSimilarName(RecRef, SearchText, SearchFieldNo, IsHandled);
if not IsHandled then 
if FindRecordWithSimilarName(RecRef, SearchText, SearchFieldNo[2]) then begin
	Result := SearchFieldRef[1].Value;
	exit(1);
end;

We do not want to find requires which are similar, we would like an exact match.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47288.
