### ISSUE TITLE
Report 1322 "Standard Purchase - Order" PurchaserText

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#19813]
In report 1322 "Standard Purchase - Order" global variable PurchaserText length is set to 30 characters. If you take a look at the procedure that is called from the report length of the variable is 50:

```
procedure SetPurchaser(var SalespersonPurchaser: Record "Salesperson/Purchaser"; "Code": Code[20]; var PurchaserText: Text[50])
begin
...
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45051.
