### ISSUE TITLE
[Event Change Request] Codeunit 7010 "Purch. Price Calc. Mgt." - Event OnAfterFindJobJnlLinePriceResource

### ISSUE THREAD

**Issue by horstoeko** [microsoft/ALAppExtensions#19810]
Hi,

we would like to request the following change on the event __OnAfterFindJobJnlLinePriceResource__

__Original__
```al
[IntegrationEvent(false, false)]
local procedure OnAfterFindJobJnlLinePriceResource(var JobJournalLine: Record "Job Journal Line")
begin
end;
```
__Change to__ (Add __var ResCost: Record "Resource Cost"__)
```al
[IntegrationEvent(false, false)]
local procedure OnAfterFindJobJnlLinePriceResource(var JobJournalLine: Record "Job Journal Line"; var ResCost: Record "Resource Cost")
begin
end;
```

Many thanks in advance.

**Comment by Vadim-Stepanenko** [comment]
Please note that this is obsolete for a long time and will probably be removed soon, you should move to newer implementations of prices
