### ISSUE TITLE
[Event request] codeunit 99000773 "Calculate Prod. Order" CopyRoutingComments

### ISSUE THREAD

**Issue by GaryFrostick2** [microsoft/ALAppExtensions#19819]
Is it possible to have a new event in codeunit 99000773 "Calculate Prod. Order", procedure CopyRoutingComments?

local procedure CopyRoutingComments(ProdOrderRoutingLine: Record "Prod. Order Routing Line"; VersionCode: Code[20])
    var
        RoutingCommentLine: Record "Routing Comment Line";
        ProdOrderRtngCommentLine: Record "Prod. Order Rtng Comment Line";
        IsHandled: Boolean;
    begin
        //New Event
        IsHandled := false;
        OnBeforeCopyRoutingComments(RoutingCommentLine, ProdOrderRoutingLine, VersionCode, IsHandled);
        if IsHandled then
            exit;

        RoutingCommentLine.SetRange("Routing No.", ProdOrderRoutingLine."Routing No.");
        RoutingCommentLine.SetRange("Operation No.", ProdOrderRoutingLine."Operation No.");

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47288.
