### ISSUE TITLE
[Event Parameter Request] Codeunit 5940 "ServContractManagement - Need to add a parameter ServContract to OnCreateOrGetCreditHeaderOnBeforeInitSeries() event

### ISSUE THREAD

**Issue by josalm** [microsoft/ALAppExtensions#19818]
Hello,

Is it possible to add a parameter ServContract to the event `OnCreateOrGetCreditHeaderOnBeforeInitSeries()`.

`OnCreateOrGetCreditHeaderOnBeforeInitSeries(ServHeader2, ServMgtSetup, ServContract ,IsHandled);`

To match the event `OnCreateServHeaderOnBeforeInitSeries()` in the same codeunit.

Best regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47288.
