### ISSUE TITLE
[Event Request] table 363 "Analysis View" - OnBeforeCheckIfLastEntryOrDateIsSet

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19828]
Please add new event in the table 363 "Analysis View" - OnBeforeCheckIfLastEntryOrDateIsSet

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckIfLastEntryOrDateIsSet(Rec: Record "Analysis View"; var Result: Boolean; var IsHandled: Boolean)
begin
end;
```

```
local procedure CheckIfLastEntryOrDateIsSet(): Boolean
var
    Result: Boolean;
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeCheckIfLastEntryOrDateIsSet(Rec, Result, IsHandled);
    if IsHandled then
        exit(Result);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47054.
