### ISSUE TITLE
[Event Request] table 363 "Analysis View" - OnBeforeSetUpdateOnPosting

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19829]
Please add new event in the table 363 "Analysis View" - OnBeforeSetUpdateOnPosting
```
[IntegrationEvent(false, false)]
local procedure OnBeforeSetUpdateOnPosting(Rec: Record "Analysis View"; NewUpdateOnPosting: Boolean)
begin
end;
```

```
procedure SetUpdateOnPosting(NewUpdateOnPosting: Boolean)
begin
    OnBeforeSetUpdateOnPosting(Rec, NewUpdateOnPosting);
    if "Update on Posting" = NewUpdateOnPosting then
        exit;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47054.
