### ISSUE TITLE
[Event Request] Page 9905 "Vendor Hist. Buy-from FactBox" - ShowDetails

### ISSUE THREAD

**Issue by LewisHyettTES** [microsoft/ALAppExtensions#19826]
Within the object page 9095 "Vendor Hist. Buy-from FactBox" please add an event to the procedure "ShowDetails".

Existing
```
local procedure ShowDetails()
begin
	PAGE.Run(PAGE::"Vendor Card", Rec);
end;
```
Suggested
```
local procedure ShowDetails()
var
	IsHandled: Boolean;
begin
	OnBeforeShowDetails(IsHandled);
	if IsHandled then
		exit;
		
	PAGE.Run(PAGE::"Vendor Card", Rec);
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47288.
