### ISSUE TITLE
Extensability request for NL Payment History export functionality

### ISSUE THREAD

**Issue by gntpet** [microsoft/ALAppExtensions#19824]
In NL localization we have multiple, reports that perform Payment History export and update Status from New to Transmitted. 

`Status := Status::Transmitted;`

we would like to catch a moment, when Status changes from New to Trasmitted.
would it be possible for you to change the existing code to the code bellow, so we could catch this action using **OnAfterValidateEvent** or **OnBeforeValidateEvent** events?

`VALIDATE(Status, Status::Transmitted);`

![image](https://user-images.githubusercontent.com/16342128/184138736-74dd8033-125e-418a-b081-1685e3f18910.png)

Best Regards, 
Gintautas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46699.
