### ISSUE TITLE
[Event Request] Page 9084 Customer Details Factbox - OnBeforeShowDetails

### ISSUE THREAD

**Issue by LewisHyettTES** [microsoft/ALAppExtensions#19825]
Within the procedure "ShowDetails" can we have an event where we can override the page which runs? 

Existing:
```
local procedure ShowDetails()
begin
	PAGE.Run(PAGE::"Customer Card", Rec);
end;
```
Suggested

```
local procedure ShowDetails()
var
	IsHandled: Boolean;
begin
	OnBeforeShowDetails(IsHandled);
	if IsHandled then
		exit;		
	PAGE.Run(PAGE::"Customer Card", Rec);
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47288.
