### ISSUE TITLE
[Event Change Request] codeunit 7150 "Update Item Analysis View" - OnAfterInitializeTempItemAnalysisViewEntry

### ISSUE THREAD

**Issue by horstoeko** [microsoft/ALAppExtensions#19832]
Hi,

Could you please add the "Value Entry" to the Event __OnAfterInitializeTempItemAnalysisViewEntry__ in Codeunit 7150?

__Old Signature__

```al
[IntegrationEvent(false, false)]
local procedure OnAfterInitializeTempItemAnalysisViewEntry(var TempItemAnalysisViewEntry: Record "Item Analysis View Entry" temporary; ItemAnalysisView: Record "Item Analysis View"; var ItemAnalysisViewSource: Query "Item Analysis View Source")
begin
end;
```

__New Signature__

```al
[IntegrationEvent(false, false)]
local procedure OnAfterInitializeTempItemAnalysisViewEntry(var TempItemAnalysisViewEntry: Record "Item Analysis View Entry" temporary; ItemAnalysisView: Record "Item Analysis View"; var ItemAnalysisViewSource: Query "Item Analysis View Source"; var ValueEntry: Record "Value Entry")
begin
end;
```

Thank you in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47288.
