### ISSUE TITLE
[Request for Codechange] Table 36 - Sales Header - CreateDim

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#19837]
Dear ALAppExtensions team,

Through this issue we would like to request to change the function call from `SalesLine.CreateDim(DefaultDimSource)` to `TempSalesLine.CreateDim(DefaultDimSource)` in Table 36 `Sales Header` - Function `CreateDimSetForPrepmtAccDefaultDim`.

```AL
procedure CreateDimSetForPrepmtAccDefaultDim()
    var
        SalesLine: Record "Sales Line";
        TempSalesLine: Record "Sales Line" temporary;
        DefaultDimSource: List of [Dictionary of [Integer, Code[20]]];
    begin
        SalesLine.SetRange("Document Type", "Document Type");
        SalesLine.SetRange("Document No.", "No.");
        SalesLine.SetFilter("Prepmt. Amt. Inv.", '<>%1', 0);
        if SalesLine.FindSet() then
            repeat
                CollectParamsInBufferForCreateDimSet(TempSalesLine, SalesLine);
            until SalesLine.Next() = 0;
        TempSalesLine.Reset();
        TempSalesLine.MarkedOnly(false);
        if TempSalesLine.FindSet() then
            repeat
                InitSalesLineDefaultDimSource(DefaultDimSource, TempSalesLine);
             => TempSalesLine.CreateDim(DefaultDimSource);
            until TempSalesLine.Next() = 0;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45088.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 45149.
