### ISSUE TITLE
[Extensibility Bug] Codeunit "Catalog Item Management" Event OnAfterCreateNewItem

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#19834]
The record item is passed by var in the event OnAfterCreateNewItem, but is not current. There is a risk of data loss.
The transfer of the dimensions changes the record item in the background. An Item.Get or similar is necessary.

```
        Item."Manufacturer Code" := NonstockItem."Manufacturer Code";
        Item."Created From Nonstock Item" := true;
        OnCreateNewItemOnBeforeItemInsert(Item, NonstockItem);
        Item.Insert();
        ItemTemplMgt.InsertDimensions(Item."No.", NonstockItem."Item Templ. Code", Database::Item, Database::"Item Templ.");

       // >>>>>>>> 
       Item.Get(Item."No.");
       // <<<<<<<< 
        
        OnAfterCreateNewItem(Item, NonstockItem);
    end;
```

**Comment by AlexanderYakunin** [comment]
No, how this code can change Item?

    procedure InsertDimensions(DestNo: Code[20]; SourceNo: Code[20]; DestTableId: Integer; SourceTableId: Integer)
    var
        SourceDefaultDimension: Record "Default Dimension";
        DestDefaultDimension: Record "Default Dimension";
    begin
        SourceDefaultDimension.SetRange("Table ID", SourceTableId);
        SourceDefaultDimension.SetRange("No.", SourceNo);
        if SourceDefaultDimension.FindSet() then
            repeat
                DestDefaultDimension.Init();
                DestDefaultDimension.Validate("Table ID", DestTableId);
                DestDefaultDimension.Validate("No.", DestNo);
                DestDefaultDimension.Validate("Dimension Code", SourceDefaultDimension."Dimension Code");
                DestDefaultDimension.Validate("Dimension Value Code", SourceDefaultDimension."Dimension Value Code");
                DestDefaultDimension.Validate("Value Posting", SourceDefaultDimension."Value Posting");
                if not DestDefaultDimension.Get(DestDefaultDimension."Table ID", DestDefaultDimension."No.", DestDefaultDimension."Dimension Code") then
                    DestDefaultDimension.Insert(true);
            until SourceDefaultDimension.Next() = 0;
    end;
