### ISSUE TITLE
Codeunit 5063 ArchiveManagement - Permissions

### ISSUE THREAD

**Issue by MrinalSingha** [microsoft/ALAppExtensions#19836]
Hi,

Can you please add following permissions on codeunit 5063 ArchiveManagement

```
    Permissions = TableData "Purch. Comment Line" = r,
                  TableData "Purchase Header Archive" = ri,
                  TableData "Purchase Line Archive" = ri,
                  TableData "Purch. Comment Line Archive" = ri;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47148.
