### ISSUE TITLE
[Extensiblity Bug] User groups Profile Lookup

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#19848]
Hello,

We found some bug at page 9830 "User Groups". If we create a new group and select the default profile in one step. The system asks to start a rename process. This happened because in function UpdateProfile calls CurrPage.Update(); 

I  suggest to remove CurrPage.Update(); line from code.

Thank you!

**Comment by AlexanderYakunin** [comment]
This page is already replaced by the Security Groups page in the security groups system.
