### ISSUE TITLE
[Event Request] T5093 Opportunity Entry - OnBeforeTestQuote

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#19850]
Can you please provide the following publisher. Our solution has an integration between jobs and opportunities and therefore we do not have a related SalesHeader which is tested here. Many thanks.

    local procedure TestQuote()
    var
        Opp: Record Opportunity;
        SalesHeader: Record "Sales Header";
        // -NewEvent
        IsHandled: Boolean;
    // +NewEvent
    begin
        // -NewEvent
        OnBeforeTestQuote(Rec, IsHandled);
        if IsHandled then
            exit;
        // +NewEvent
        Opp.Get("Opportunity No.");
        if not SalesHeader.Get(SalesHeader."Document Type"::Quote, Opp."Sales Document No.") then
            Error(Text005);
    end;

----Signature-----

    // -NewEvent 
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTestQuote(OpportunityEntry: Record "Opportunity Entry"; var IsHandled: Boolean)
    begin
    end;
    // +NewEvent

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47288.
