### ISSUE TITLE
[Enum Request] T780 Certificate of Supply - Document Type

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#19851]
Can you please change the document type into an extensible enum

        field(1; "Document Type"; Option)
        {
            Caption = 'Document Type';
            OptionCaption = 'Sales Shipment,Service Shipment,Return Shipment';
            OptionMembers = "Sales Shipment","Service Shipment","Return Shipment";
        }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46015.
