### ISSUE TITLE
[Event Request] - Report 595 "Adjust Exchange Rates" 

### ISSUE THREAD

**Issue by CristhianMH** [microsoft/ALAppExtensions#19862]
Hello,

Could you please add this event  OnAfterAdjExchRateBufferUpdate("Bank Account") In the  dataitem BankAccountGroupTotal in the OnAfterGetRecord() trigger.

 dataitem(BankAccountGroupTotal; "Integer")
                {
                    DataItemTableView = SORTING(Number);
                    MaxIteration = 1;

                    trigger OnAfterGetRecord()
                    var
                        BankAccount: Record "Bank Account";
                        GroupTotal: Boolean;
                    begin
                        BankAccount.Copy("Bank Account");
                        if BankAccount.Next = 1 then begin
                            if BankAccount."Bank Acc. Posting Group" <> "Bank Account"."Bank Acc. Posting Group" then
                                GroupTotal := true;
                        end else
                            GroupTotal := true;

                        if GroupTotal then
                            if TotalAdjAmount <> 0 then begin
                                AdjExchRateBufferUpdate(
                                  "Bank Account"."Currency Code", "Bank Account"."Bank Acc. Posting Group",
                                  TotalAdjBase, TotalAdjBaseLCY, TotalAdjAmount, 0, 0, 0, PostingDate, '', "Bank Account"."VAT Registration No.");
                                OnAfterAdjExchRateBufferUpdate("Bank Account");
                                InsertExchRateAdjmtReg(3, "Bank Account"."Bank Acc. Posting Group", "Bank Account"."Currency Code");
                                TotalBankAccountsAdjusted += 1;
                                ResetTempAdjmtBuffer();
                                TotalAdjBase := 0;
                                TotalAdjBaseLCY := 0;
                                TotalAdjAmount := 0;
                            end;
                    end;
                }

Please also add this other event   OnAfterPostAdjmt(GenJnlLine)  in the feature PostAdjmt

local procedure PostAdjmt(GLAccNo: Code[20]; PostingAmount: Decimal; AdjBase2: Decimal; CurrencyCode2: Code[10]; var DimSetEntry: Record "Dimension Set Entry"; PostingDate2: Date; ICCode: Code[20]; "VATRegistrationNo.": Text[20]) TransactionNo: Integer
    var
        GenJnlLine: Record "Gen. Journal Line";
    begin
        if PostingAmount = 0 then
            exit;

        GenJnlLine.Init();
        GenJnlLine.Validate("Posting Date", PostingDate2);
        GenJnlLine."Document No." := PostingDocNo;
        GenJnlLine."Account Type" := GenJnlLine."Account Type"::"G/L Account";
        GenJnlLine.Validate("Account No.", GLAccNo);
        GenJnlLine.Description :=
            PadStr(StrSubstNo(PostingDescription, CurrencyCode2, AdjBase2), MaxStrLen(GenJnlLine.Description));
        GenJnlLine.Validate(Amount, PostingAmount);
        GenJnlLine."Source Currency Code" := CurrencyCode2;
        GenJnlLine."IC Partner Code" := ICCode;
        GenJnlLine."VAT Registration No." := "VATRegistrationNo.";
        if CurrencyCode2 = GLSetup."Additional Reporting Currency" then
            GenJnlLine."Source Currency Amount" := 0;
        GenJnlLine."Source Code" := SourceCodeSetup."Exchange Rate Adjmt.";
        GenJnlLine."System-Created Entry" := true;

        TransactionNo := PostGenJnlLine(GenJnlLine, DimSetEntry);
        OnAfterPostAdjmt(GenJnlLine);
    end;

Please also add this other event  OnAfterPostCustAdjmt(AdjExchRateBuffer);  in the feature PostCustAdjmt

    local procedure PostCustAdjmt(AdjExchRateBuffer: Record "Adjust Exchange Rate Buffer"; var TempDtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer" temporary; var TempDimSetEntry: Record "Dimension Set Entry" temporary)
    var
        CustPostingGr: Record "Customer Posting Group";
    begin
        CustPostingGr.Get(TempAdjExchRateBuffer."Posting Group");
        TempDtldCVLedgEntryBuf."Transaction No." :=
            PostAdjmt(
                CustPostingGr.GetReceivablesAccount(), AdjExchRateBuffer.AdjAmount,
                AdjExchRateBuffer.AdjBase, AdjExchRateBuffer."Currency Code", TempDimSetEntry,
                AdjExchRateBuffer."Posting Date", AdjExchRateBuffer."IC Partner Code", AdjExchRateBuffer."VAT Registration No.");
        OnAfterPostCustAdjmt(AdjExchRateBuffer);
        if TempDtldCVLedgEntryBuf.Insert() then;
        InsertExchRateAdjmtReg(1, AdjExchRateBuffer."Posting Group", AdjExchRateBuffer."Currency Code");
        TotalCustomersAdjusted += 1;
    end;

[IntegrationEvent(false, false)]
local procedure OnAfterPostCustAdjmt(AdjExchRateBuffer)
begin
end;

[IntegrationEvent(false, false)]
local procedure OnAfterPostAdjmt(GenJnlLine)
begin
end;

[IntegrationEvent(false, false)]
OnAfterAdjExchRateBufferUpdate("Bank Account")
begin
end;

Alfapeople Colombia, partner of Microsoft, has developed the financial localization to cover what is required by Colombian legislation. For this, it has been necessary to generate the regularization entry so that the income accounts close or their balance is canceled with the identification number of the third party they represent. that balance. It is necessary to clarify to Microsoft is the "VAT Registration No" field, from the standard as an alternative solution I copy the year-end codeunit to be able to adapt it to the year-end, this was done because there was no event.
For this reason we ask for your help adding these two events.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51064.
