### ISSUE TITLE
[Event Request] Report 5812 "Revaluation Posting - Test" OnAfterGetItemJournalLineOnAfterCreateDimTableIDs

### ISSUE THREAD

**Issue by SvenSakulowski** [microsoft/ALAppExtensions#19869]
Please add an Event OnAfterGetItemJournalLineOnAfterCreateDimTableIDs in Report 5812 "Revaluation Posting - Test"

Event Definition:

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetItemJournalLineOnAfterCreateDimTableIDs(var TableID: array[10] of Integer; var No: array[10] of Code[20]; ItemJournalLine: record "Item Journal Line")
    begin
    end;

Current Code:

	dataitem("Item Journal Line"; "Item Journal Line")
	{
		[...]
		trigger OnAfterGetRecord()
		var
			[...]
		begin
			[...]
			TableID[1] := DATABASE::Item;
			No[1] := "Item No.";
			TableID[2] := DATABASE::"Salesperson/Purchaser";
			No[2] := "Salespers./Purch. Code";
			if not DimMgt.CheckDimValuePosting(TableID, No, "Dimension Set ID") then
				AddError(DimMgt.GetDimValuePostingErr);

			OnAfterItemJournalLineOnAfterGetRecord("Item Journal Line", ErrorCounter, ErrorText);
		end;

Suggested Code:

	dataitem("Item Journal Line"; "Item Journal Line")
	{
		[...]
		trigger OnAfterGetRecord()
		var
			[...]
		begin
			[...]
			TableID[1] := DATABASE::Item;
			No[1] := "Item No.";
			TableID[2] := DATABASE::"Salesperson/Purchaser";
			No[2] := "Salespers./Purch. Code";
			OnAfterGetItemJournalLineOnAfterCreateDimTableIDs(TableID, No, "Item Journal Line");
			if not DimMgt.CheckDimValuePosting(TableID, No, "Dimension Set ID") then
				AddError(DimMgt.GetDimValuePostingErr);

			OnAfterItemJournalLineOnAfterGetRecord("Item Journal Line", ErrorCounter, ErrorText);
		end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47981.
