### ISSUE TITLE
[Request for External] report 5690 "Index Fixed Assets": InsertGenJnlLine public

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/ALAppExtensions#19866]
Could you please remove the "local" statement from the procedure InsertGenJnlLine in the report 5690?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45464.
