### ISSUE TITLE
[Request] - Table 17 "GL Entry" 

### ISSUE THREAD

**Issue by CristhianMH** [microsoft/ALAppExtensions#19863]
Hello ,

I have a field called "Vat Registration No" in the table "GL Entry" Type "Code[20]" , because I need to use the Flow Field "Balance at Date , Debit amount , credit amount "from the chart of accounts adding to the primary key of the GL Entry the field "Vat Registration No".

key(Key5; "G/L Account No.", "Business Unit Code", "Global Dimension 1 Code", "Global Dimension 2 Code", "Posting Date","Vat Registration No")
        {
            Enabled = false;
            SumIndexFields = Amount, "Debit Amount", "Credit Amount", "Additional-Currency Amount", "Add.-Currency Debit Amount", "Add.-Currency Credit Amount";
        }

**Comment by dnpb** [comment]
What is your question? Is `Vat Registration No` your own extension's field? MS obviously cannot add that to their table or any key therein.

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot process this request. You can extend existing key in your extension if needed.
