### ISSUE TITLE
[Event Request] Add and modify paramters in event OnParseParentChildLineOnBeforeInsertColumn in codeunit 1203, "Import XML File to Data Exch."

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#19870]
Hi

A couple of months ago we asked for a the following event.
https://github.com/microsoft/ALAppExtensions/issues/18412

However, this was not enough for us to achive what we wanted. Can you please do the following changes to the OnParseParentChildLineOnBeforeInsertColumn in procedure ParseParentChildLine in codeunit 1203 "Import XML File to Data Exch."?

```
// >>>>>>>>>>
InnerText := XmlNodeList.ItemOf(I - 1).InnerText;
//OnParseParentChildLineOnBeforeInsertColumn(InnerText, XmlNodeList.ItemOf(I - 1).InnerXml);
OnParseParentChildLineOnBeforeInsertColumn(InnerText, XmlNodeList.ItemOf(I - 1).InnerXml, XmlNodeList.ItemOf(I - 1).OuterXML, DataExchColumnDef);
// <<<<<<<<<
```

```
// >>>>>>>>>
[IntegrationEvent(false, false)]
//local procedure OnParseParentChildLineOnBeforeInsertColumn(var InnerText: Text; InnerXML: Text)
local procedure OnParseParentChildLineOnBeforeInsertColumn(var InnerText: Text; InnerXML: Text; OuterXML: Text; DataExchColumnDef: Record "Data Exch. Column Def")
// <<<<<<<<<<<
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47656.
