### ISSUE TITLE
[Extensibility-Enhancement] Create Custom Report Layout with Type = Excel

### ISSUE THREAD

**Issue by OleksiiAndoran** [microsoft/ALAppExtensions#19879]
We need to define different custom excel layouts for different customers. 
There is a need to define a specific "Document Layout" for specific customer
![image](https://user-images.githubusercontent.com/64095744/185334514-4c643761-1a4f-452a-b322-9dbf6e8ab2e9.png)
(Open Customer Card -> Related action category -> Customer group -> Document Layouts action)

We want to define a specific excel layout for the specific customer.
Click on the Custom Layout Description field and define which layout to use
![image](https://user-images.githubusercontent.com/64095744/185338222-9a95e6b8-43ce-49f1-9f36-95dff4595ba1.png)

We tried to create Custom Report Layout but Custom Report Layout supports only Word and RDLC layouts.
![image](https://user-images.githubusercontent.com/64095744/185340887-6f27984d-ac94-492e-9694-295f92e2122d.png)
(Open Custom Report Layouts -> New action)
Please extend Custom Report Layouts to support Excel layouts or provide a workaround for how we can provide different Excel layouts for different customers.

**Comment by pri-kise** [comment]
There is the same scenario for Vendors, too.

 But with extending the custom Report Layouts this should work for vendors, too.

**Comment by cb2bc** [comment]
@AlexanderYakunin any idea if this feature request is planned for this fall release? :)

**Comment by AlexanderYakunin** [comment]
No, we cannot make changes this way. This is serious change, and we need an Idea and votes first.

**Comment by JesperSchulz** [comment]
Closing as per comment above. For suggestions to the Business Central product group, please create a [BC Idea](https://aka.ms/bcideas).
