### ISSUE TITLE
[Request-For-External] Page 9305 Sales Order List procedure PostDocument

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#19882]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

[Request-For-External] Page 9305 Sales Order List - Procedure from Internal to Global

procedure PostDocument(PostingCodeunitID: Integer)

**Comment by AlexanderYakunin** [comment]
Hello! Any reason why you need this exposed? We usually do not expose page methods.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.
