### ISSUE TITLE
[Request For External] Report 5405 "Calc. Consumption". LocationCode

### ISSUE THREAD

**Issue by adamlrobinson** [microsoft/ALAppExtensions#19888]
Hi,

Could we please allow the LocationCode field to be set externally on Report 5405 "Calc. Consumption".

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45464.
