### ISSUE TITLE
[event request] in procedure IsCommentLine in codeunit 1303 "Correct Posted Sales Invoice"

### ISSUE THREAD

**Issue by RobertatK3** [microsoft/ALAppExtensions#19891]
I have extended the Sales Line Type enum with a value Matrix. A line with this type is an overview line for document lines with the same item no (but different variants) It is much the same as a comment line, but we need to have values in a lot of fields which are not allowed for a comment line and thus added a new sales line type. 
The line however does not need to post anything, but should only be copied just like a comment line.
And there is the challenge... :) 
In a lot of posting routines I have managed to skip test etc. for this line type using available events, but in codeunit 1303 "Correct Posted Sales Invoice" there is no event available.
Could you please add an event publisher in procedure IsCommentLine where I can set the return value of this procedure to true causing the line to be skipped in procedure TestSalesLines?

In general I would also want to say that the use of sales line type is quite rigid. Introducing a new type requires a lot of coding to bypass standard code when it should only be adding functionality.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47981.
