### ISSUE TITLE
[Extensibility Request] codeunit 6500 "Item Tracking Management" - InsertReservEntryFromTrackingSpec

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19899]
Please make function InsertReservEntryFromTrackingSpec externally available.
```
procedure InsertReservEntryFromTrackingSpec(TrackingSpecification: Record "Tracking Specification"; SourceSubtype: Option; SourceID: Code[20]; SourceRefNo: Integer; QtyBase: Decimal)
var
    ReservEntry: Record "Reservation Entry";
begin
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45464.
