### ISSUE TITLE
[Event Request] codeunit 6500 "Item Tracking Management" - OnBeforeCopyHandledItemTrkgToInvLine

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19896]
Please include sender in the Event OnBeforeCopyHandledItemTrkgToInvLine in the codeunit 6500:

```
[IntegrationEvent(true, false)]
local procedure OnBeforeCopyHandledItemTrkgToInvLine(FromSalesLine: Record "Sales Line"; var ToSalesInvLine: Record "Sales Line"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48444.
