### ISSUE TITLE
Maximum of 2100 parameters in dimension set filter

### ISSUE THREAD

**Issue by sgiordy** [Microsoft/ALAppExtensions#199]
Hi

due to lack of possibility to change behaviour of standard flowfield and keys, I'm doing some stress test with standard code.

In a medium-complex database with:
- 400 stores
- 80 item categories
- 20 customer types

it's easy to have thousands of dimension set IDs till to maxium of 400 x 80 x 20 = 640.000 combinations.

With a simple stress-test codeunit I have generated only 10.000 randomic G/L entries but sufficients to crash dimension set filter due to maximum number of parameters (2100) supported by SQL Server:

![dimensionifiltro](https://user-images.githubusercontent.com/17341714/39271496-863dc4fc-48d9-11e8-960c-7d3dc73a4fb0.PNG)

![dimensioni](https://user-images.githubusercontent.com/17341714/39271372-25c7fdf4-48d9-11e8-925e-4d3d740b6e7c.PNG)

In the past we could extend "G/L Entry" table with ""Global Dimension Code 3", 4 and so on; create the missing keys and alter the "Amount" flowfield of "G/L Account". But now?

I think this issue is partially related to #730 but anyway, in this scenario, Dimension Set Filter will never work. Maybe a new type of field such as "Filter on Related Table" can resolve the issue applying the WHERE clause in "Dimension Set Entry" table instead of passing thousand of parameters for "Dimension Set ID" in "G/L Entry".

S.

**Comment by JesperSchulz** [comment]
Update: This issue is being worked on.

**Comment by JesperSchulz** [comment]
Fixing this turned out to require a larger effort. We have various efforts in motion, but it will take us some time to get to the bottom of this. I will close this issue, as we will not report back progress on the larger efforts here in this repo, which is about extensibility issues. Thank you for reporting this issue.
