### ISSUE TITLE
[Event Request] codeunit 6529 "Item Tracking Navigate Mgt." - OnBeforeFindJobLedgEntry

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19905]
Please add new Event in Codeunit 6529

```
local procedure FindJobLedgEntry(var ItemFilters: Record Item)
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeFindJobLedgEntry(TempJobLedgEntry, ItemFilters, IsHandled);
    if IsHandled then
        exit;
```

```
[IntegrationEvent(true, false)]
local procedure OnBeforeFindJobLedgEntry(var TempJobLedgEntry: Record "Job Ledger Entry" temporary; var ItemFilters: Record Item; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47981.
