### ISSUE TITLE
[Extensibility Request] codeunit 6500 "Item Tracking Management" - SynchronizeItemTracking2

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19900]
Please make function SynchronizeItemTracking2 externally available.
```
procedure SynchronizeItemTracking2(var FromReservEntry: Record "Reservation Entry"; ToRowID: Text[250]; DialogText: Text[250])
var
    ReservEntry2: Record "Reservation Entry";
    TempTrkgSpec1: Record "Tracking Specification" temporary;
    TempTrkgSpec2: Record "Tracking Specification" temporary;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45464.
