### ISSUE TITLE
[Event Request] Net Cust/Vend Balances Mgt. 

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#19902]
Hello,

Please add new events in codeunit 108 "Net Cust/Vend Balances Mgt."

procedure InitGenJnlLine 
OnAfterInitGenJnlLine(var GenJnlLine,VendLedgEntry);
procedure FillGenJnlLineFrom
OnAfterFillGenJnlLineFromCustLedgEntry(var GenJnlLine,CustLedgEntry)
OnAfterFillGenJnlLineFromVendLedgEntry(var GenJnlLine,VendLedgEntry)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47288.
