### ISSUE TITLE
[Event Request]   OnBeforeSetKeyAndFilters in "Reservation Engine Mgt."

### ISSUE THREAD

**Issue by Easystep2** [microsoft/ALAppExtensions#19912]
Scenario, full tracking with full warehousing (Directed Put-away) when I pick 2 lotnumbers on a Prod. Component Line and pick+backflush on partial of the first lotnumer (its put into the machine), the second time I post output it takes the second lotnumber for consumption whilethat one is still besides the machine and not in the machine. So it keeps swapping the lotnumbers, while it should first consume the first lotnumber and then the second lotnumber when there is not sufficient inventory of the first lotnumber.

Where:
In codeunit "Reservation Engine Mgt."

local procedure SetKeyAndFilters(var ReservEntry: Record "Reservation Entry")
var
      IsHandled : boolean;
    begin

<< Start
       OnbeforeSetKeyAndFilters(ReservEntry, IsHandled);

       if IsHandled then 
          exit;
<< End

        if ReservEntry.IsEmpty() then
            exit;

        ReservEntry.SetCurrentKey(
          "Source ID", "Source Ref. No.", "Source Type", "Source Subtype",
          "Source Batch Name", "Source Prod. Order Line", "Reservation Status",
          "Shipment Date", "Expected Receipt Date");

        if ReservEntry.FindFirst() then
            ReservEntry.SetPointerFilter;
    end;

New Event:
[IntegrationEvent(false, false)]
    local procedure OnbeforeSetKeyAndFilters(var ReservationEntry: Record "Reservation Entry", var IsHandled: boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45720.
