### ISSUE TITLE
[Extensibility Request] report 699 "Calculate Plan - Req. Wksh."

### ISSUE THREAD

**Issue by BHoepfner** [microsoft/ALAppExtensions#19911]
As our customer has a large number of vendors and items, the requisition via the requisition worksheet takes a very long time. 

Therefore we have created a job which runs at night and starts the two actions "Calculate Plan" and "Carry Out Action Message" from the Requisition Worksheet automatically.

The action "Calculate Plan" is performed via report 699 "Calculate Plan - Req. Wksh.". While most of the parameters in this report can be set from outside using the functions "SetTemplAndWorksheet" and "InitializeRequest", there are unfortunately some parameters which can exclusively be set via the request page. 

This concerns the two functions "InitializeFromMfgSetup" and "ValidatePriceCalcMethod". Unfortunately these two function are local and there is no event publisher which could be subscribed in order to set the required values from outside the report.

Therefore we would ask if it would be possible to set the two functions "InitializeFromMfgSetup" and "ValidatePriceCalcMethod" to global, just like the already existing functions "SetTemplAndWorksheet" and "InitializeRequest", so that all required parameters can be set from outside the report.

Thank you very much in advance!

![image](https://user-images.githubusercontent.com/111738633/185885647-14ac9063-62b3-4157-aa20-07da11273c61.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45464.
