### ISSUE TITLE
[Event Change Request] Codeunit 5987 "Serv-Posting Journals Mgt." - OnCreateBillsOnBeforeSplitServiceInv (Spanish localization)

### ISSUE THREAD

**Issue by juacefer** [microsoft/ALAppExtensions#19921]
Last June 29th I published a post requesting a change of event.

https://github.com/microsoft/ALAppExtensions/issues/18928

The answer was that it was accepted and it was identified with the build id. 44246.
In the last "Update 20.4 for Microsoft Dynamics 365 Business Central (on-premises) 2022 Release Wave 1 (Application Build 20.4.44365, Platform Build 20.0.44359)" the requested changes were not merged.

We need a modification in the event OnCreateBillsOnBeforeSplitServiceInv

Actual event:
[IntegrationEvent(false, false)]
local procedure OnCreateBillsOnBeforeSplitServiceInv(ServiceHeader : Record "Service Header";CustLedgerEntry : Record "Cust. Ledger Entry";VAR TotalServiceLine : Record "Service Line")
begin
end;

New event:
[IntegrationEvent(false, false)]
local procedure OnCreateBillsOnBeforeSplitServiceInv(ServiceHeader : Record "Service Header";**_VAR_** CustLedgerEntry : Record "Cust. Ledger Entry";VAR TotalServiceLine : Record "Service Line")
begin
end;

Are you planning to make these changes in future updates?

Best regards.

**Comment by juacefer** [comment]
Please, our client requires a response to this request dated August 23rd and which referred to a previous request dated June 29th.
We need an urgent solution.

Best regards.

**Comment by Vadim-Stepanenko** [comment]
I have looked at the Serv-posting journals Mgt codeunit in ES localization and there is no OnBeforeCreateCarteraBills event there. The only event with this name is in SalesPost and PurchPost codeunits, but the signature is not the same.
From the request I gather that it's supposed to be at the start of CreateBills procedure? I can add it, but I am confused as to why the request is to modify and there is no such event, please clarify which version you are looking at.

**Comment by juacefer** [comment]
Hi Vadim.

As I indicate in this issue, the event is called **OnCreateBillsOnBeforeSplitServiceInv**. In the event before, I requested that the new event was called as OnBeforeCreateCarteraBills but your collegues named it as OnCreateBillsOnBeforeSplitServiceInv.

The new event is created in CreateBills procedure.

I copy here the procedure

    procedure CreateBills(var TotalServiceLine: Record "Service Line"; var Window: Dialog; GenJnlLineDocNo: Code[20]; GenJnlLineExtDocNo: Code[35])
    var
        CustLedgEntry: Record "Cust. Ledger Entry";
        PaymentMethod: Record "Payment Method";
        CarteraSetup: Record "Cartera Setup";
        SplitPayment: Codeunit "Invoice-Split Payment";
    begin
        CustLedgEntry.Find('+');
        with ServiceHeader do begin
            if PaymentMethod.Get("Payment Method Code") then
                if (PaymentMethod."Create Bills" or PaymentMethod."Invoices to Cartera") and
                   (not CarteraSetup.ReadPermission) and Invoice
                then
                    Error(CannotCreateCarteraDocErr);
            **OnCreateBillsOnBeforeSplitServiceInv(ServiceHeader, CustLedgEntry, TotalServiceLine);**
            if ("Bal. Account No." = '') and ("Document Type" <> "Document Type"::"Credit Memo") and CarteraSetup.ReadPermission then
                SplitPayment.SplitServiceInv(
                  ServiceHeader, CustLedgEntry, Window, SrcCode, GenJnlLineExtDocNo, GenJnlLineDocNo,
                  -(TotalServiceLine."Amount Including VAT" - TotalServiceLine.Amount));
        end;
    end;

New change event:
[IntegrationEvent(false, false)]
local procedure OnCreateBillsOnBeforeSplitServiceInv(ServiceHeader : Record "Service Header";**VAR** CustLedgerEntry : Record "Cust. Ledger Entry";VAR TotalServiceLine : Record "Service Line")
begin
end;
