### ISSUE TITLE
Change scope for InitializeFromData() in page Item Availability Check

### ISSUE THREAD

**Issue by sadjad1** [microsoft/ALAppExtensions#19930]
Hi!
I have come across clients who **explicitly** wants to be able to trigger _page 1872 "Item Availability Check"_ manually for specifick Sales Order Lines. There of course other ways around to show the same data as the in this page _1872 "Item Availability Check"_ does but they explicitly asks for this page.

So I was checking this page out and see what's possible and not. What I could find was a function in this page called InitializeFromData. This function could be useful in order to manually trigger this page but is that has the scope [Scope('OnPrem')]. Is it possible to remove this scope for Bussiness Central that is **not** on premesis so we can use this function?

Original reference/request: https://github.com/microsoft/ALAppExtensions/discussions/19847

![184585378-23afc1ab-a524-44b9-8eb5-c3d451ce526c](https://user-images.githubusercontent.com/15630953/186178165-e32ad227-b22e-483d-ab5c-8e3c2d6d6f52.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.
