### ISSUE TITLE
[Event Parameter Change] Table 36 Sales Header - procedure InitRecord - Event OnAfterInitRecord

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19950]
We would like the sender added to the following event.

Table 36 Sales Header - procedure InitRecord - Event OnAfterInitRecord

Original:

```
Table 36 Sales Header - procedure InitRecord - Event OnAfterInitRecord

[IntegrationEvent(false, false)]
    local procedure OnAfterInitRecord(var SalesHeader: Record "Sales Header")
    begin
    end;
```

Change:

```
Added sender Parameter
[IntegrationEvent(true, false)]
    local procedure OnAfterInitRecord(var SalesHeader: Record "Sales Header")
    begin
    en

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47054.
