### ISSUE TITLE
[Extensiblity Bug] Module Azure Blob Services API Caption Problem

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#19953]
Hi al-team, 

in the module Azure Blob Service Api it is possible to set HTTP Header via the predefined codeunit "ABS Optional Parameters".
When using the "Range" function, a label is used that does not have locked = true. This means that the translation is always used when setting the HTTP header. 
The problem is that in some XLF files the translation is different from the caption, so the HTTP request runs into an error. (e.g. in the German translation)

![image](https://user-images.githubusercontent.com/48024891/186410550-567394a6-1e3f-4bed-bd30-0e386793b079.png)
![image](https://user-images.githubusercontent.com/48024891/186410658-98061a39-4bf4-410d-bc2f-0da89ab8663f.png)
Can you please fix this? 

In this context, I have a further question. The module deals with downloading and uploading files to Azure Blob Storage. 
Since the HTTPClient data type is used in the module, the server configurations NavHttpClientMaxResponseContentSize is relevant. 
Is there any way to query this value via al at runtime? 

Thank you!

**Comment by MattiLE** [comment]
Hi al-team, 

can you please fix this? In BC 21 the problem still exists.

**Comment by MattiLE** [comment]
@JesperSchulz  @AlexanderYakunin I have additionally created this pull request.
#20592

**Comment by JesperSchulz** [comment]
Taking matters into your own hands is the way to go 🥳 We'll process your PR. Closing this issue, as I believe it isn't needed anymore.
