### ISSUE TITLE
[Event Parameter Change] Table 246 Requisition Line - Procedure CopyFromItem - Event OnAfterCopyFromItem

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#19951]
We would like the parameter/-s sender and CurrFieldNo added to the following event.

Table 246 Requisition Line - Procedure CopyFromItem - Event OnAfterCopyFromItem

Original:

```
OnAfterCopyFromItem(Rec, Item);

[IntegrationEvent(false, false)]
    local procedure OnAfterCopyFromItem(var RequisitionLine: Record "Requisition Line"; Item: Record Item)
    begin
    end;
```

Change:

```
Added: sender and CurrFieldNo

OnAfterCopyFromItem(Rec, Item, CurrFieldNo);

[IntegrationEvent(true, false)]
    local procedure OnAfterCopyFromItem(var RequisitionLine: Record "Requisition Line"; Item: Record Item; CurrFieldNo: Integer)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45914.
