### ISSUE TITLE
Event Request : - Required Event in Page “Applied Delivery Challan” and Codeunit “Subcontracting Post” in BC365

### ISSUE THREAD

**Issue by tsharma1161** [microsoft/ALAppExtensions#19978]
[Required Event in Apply Delivery Challan and Receive Subcon order.docx](https://github.com/microsoft/ALAppExtensions/files/9422402/Required.Event.in.Apply.Delivery.Challan.and.Receive.Subcon.order.docx)

**Comment by tsharma1161** [comment]
Please add the event as per attached document.

Thanks

**Comment by Vadim-Stepanenko** [comment]
We cannot process requests like this in a separate document.
Please open a new issue with proper formatting and all the info in the issue itself, not external files, try to follow other issues around here with tag: event-request.
