### ISSUE TITLE
[BREAKING CHANGE] report 699 "Calculate Plan - Req. Wksh." Rename of Protected Variables

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#19977]
Our NextMajor Pipeline is failing, since the name of the **protected** variable `SKU: Record "Stockkeeping Unit";` was changed to `StockkeepingUnit: Record "Stockkeeping Unit";` in report `report 699 "Calculate Plan - Req. Wksh."`.

This is in my opinion a breacking change, that should be avoided in any case.

Current Protected Variable Names:
```al
protected var
        MfgSetup: Record "Manufacturing Setup";
        SKU: Record "Stockkeeping Unit";
```

Renamed Variable Names
```al
    protected var
        ManufacturingSetup: Record "Manufacturing Setup";
        StockkeepingUnit: Record "Stockkeeping Unit";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45592.
