### ISSUE TITLE
[Event Issue] Codeunit ReportManagement - OnAfterDocumentReady DocumentStream: InStream can only be read by a single extension

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#19971]
Dear ALAppExtensions team,

I was asked to file an issue here on GitHub for tracking by @nhsejth. Problem is that the InStream parameter from the `OnAfterDocumentReady` event can only be read by the first subscriber. Subsequent event subscriber will be left with the parameter being set to the end of the stream (EOS = true).
It would be good if multiple subscribers (multiple apps, from multiple ISVs) can _read_ the document contents.

[Originally discussed on Yammer:](https://www.yammer.com/dynamicsnavdev/threads/1573605060698112)
> I found what the problem is. Multiple apps can subscribe OnAfterDocumentReady event and read the InStream. If one of the apps has read the InStream, then none of the other apps can read the PDF contained in the InStream anymore.
> 
> This already appears to form a problem for our own apps, but more so, if you combine apps from multiple ISVs that all try to use the OnAfterDocumentReady event.
> 
> Do you know if there is a way to avoid this problem (is there an option to sort of 'reset' an InStream that I am completely missing) or can this be considered a problem that might need to be resolved in BC itself? 😅
> 
> I think changing the InStream to a "Temp Blob" would also resolve the issue, as that would allow  ISVs to create an InStream themselves so there are no conflicts.

Reply:
> I will have to think about the best solution here. In principle, we should have an automatic reset of the stream when the NST iterates over all subscribers, but I don't know how easy that would be, it could be better to add a Reset method on the stream object that would reset the pointer to the beginning.
> 
> Notice that TempBlob is deprecated and replaced by another app codeunit, but it could be an option to feed the data into a blob in the report management codeunit, but I would prefer not to copy data around for performance reasons.
> 
> Would it be possible to you to log an issue on GitHub that I can use for tracking?

(Also discussed in the following public thread: https://www.yammer.com/dynamicsnavdev/threads/1885281555636224)

Maybe one possible approach might be to replace the `DocumentStream: InStream` parameter with a `DocumentTempBlob: Codeunit "Temp Blob` parameter, although the other suggested approaches ((1) InStream.Reset, or (2) Automatic Reset by NST of InStream event parameter) work as well and preferred if one of them can be realized.

**Comment by JesperSchulz** [comment]
I'm afraid I cannot provide an update on this issue. @nhsejth will give a reply, when he finds a minute to do so.

**Comment by JulianSchmidtke** [comment]
Hi, do you have any updates on this?

**Comment by nhsejth** [comment]
I have a potential workaround (but lack full validation) that can be tested.

In the subscriber procedure, you can create a local instream variable that gets initialized from the parameter stream. That will give two stream variables pointing to the same data, but with different pointers internally (shared stream). By using the local variable instead of the parameter, you should leave the parameter unmodified.

**Comment by pri-kise** [comment]
@nhsejth thanks for your feedback. Maybe you can give then some small example code, how we can patch our solution as temporary workaround.
I'm not quite sure how I can initiliaze my local InStream from the parameter stream. Are stream assignable and does this lead to a copy of the original stream?

**Comment by JulianSchmidtke** [comment]
This works for us

```
  begin        
      TempBlob.CreateOutStream(outs);
      CopyStream(outs, DocumentStream);

      // Refill the InStream
      TempBlob.CreateInStream(DocumentStream);
  end;
```

**Comment by JesperSchulz** [comment]
We're looking into finding a solution for this problem for 2023 Wave 1. Fingers crossed.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.

**Comment by pri-kise** [comment]
Referencing @nhsejth solution coming with next major:
https://github.com/microsoft/ALAppExtensions/issues/11846#issuecomment-1401960427

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22.0.52767.0.
