### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#19983]
Hello,
We are having memory issues with the client browser and Business Central 2022 Wave 1. For example, when scrolling the list of articles, the memory on the client station up, up to 4Go!!! then crashes the browser displaying ouch, ouch. 

What should I do to purge the memory ?

Cordially.

![image](https://user-images.githubusercontent.com/29279866/186638757-5c14f978-065b-4c06-bb08-33e9ce4a35c9.png)

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
