### ISSUE TITLE
[BUG] Codeunit 444 "Purchase-Post Prepayments"

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#19981]
Can you please fix the following scenario. if PurchSetup."Ext. Doc. No. Mandatory" is checked, then the code always wants you to have a Vendor Invoice No., even when posting a Credit Memo. I suggest to move the code inside the case statement.

    local procedure "Code"(var PurchHeader2: Record "Purchase Header"; DocumentType: Option Invoice,"Credit Memo")
    var
            ...
            // Create posted header
            // -BUGFIX
            // if PurchSetup."Ext. Doc. No. Mandatory" then
            //     TestField("Vendor Invoice No.");
            // +BUGFIX
            case DocumentType of
                DocumentType::Invoice:
                    begin
                        // -BUGFIX
                        if PurchSetup."Ext. Doc. No. Mandatory" then
                            TestField("Vendor Invoice No.");
                        // +BUGFIX
                        InsertPurchInvHeader(PurchInvHeader, PurchHeader, PostingDescription, GenJnlLineDocNo, SrcCode, PostingNoSeriesCode);
                        GenJnlLineDocType := GenJnlLine."Document Type"::Invoice;
                        PostedDocTabNo := DATABASE::"Purch. Inv. Header";
                        GenJnlLineExtDocNo := PurchInvHeader."Vendor Invoice No.";
                        Window.Update(1, StrSubstNo(Text003, "Document Type", "No.", PurchInvHeader."No."));
                    end;
                DocumentType::"Credit Memo":
                    begin
                        // -BUGFIX
                        if PurchSetup."Ext. Doc. No. Mandatory" then
                            TestField("Vendor Cr. Memo No.");
                        // +BUGFIX
                        if PurchSetup."Ext. Doc. No. Mandatory" then
                            TestField("Vendor Cr. Memo No.");
                        CalcPmtDiscOnCrMemos := GetCalcPmtDiscOnCrMemos("Prepmt. Payment Terms Code");
                        InsertPurchCrMemoHeader(
                          PurchCrMemoHeader, PurchHeader, PostingDescription, GenJnlLineDocNo, SrcCode, PostingNoSeriesCode,
                          CalcPmtDiscOnCrMemos);
                        GenJnlLineDocType := GenJnlLine."Document Type"::"Credit Memo";
                        PostedDocTabNo := DATABASE::"Purch. Cr. Memo Hdr.";
                        GenJnlLineExtDocNo := PurchCrMemoHeader."Vendor Cr. Memo No.";
                        Window.Update(1, StrSubstNo(Text011, "Document Type", "No.", PurchCrMemoHeader."No."));
                    end;
            end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47647.
