### ISSUE TITLE
Expose (local/ onprem) standard BC function (CheckBalance and CalcJournalTotal) from Financial Journal - 11300 Page

### ISSUE THREAD

**Issue by NicolasVanDerSpiegel** [microsoft/ALAppExtensions#19982]
Hello, 

We needed to copy the following local functions from the Financial Journal Page [11300]:

- CheckBalance 
- CalcJournalTotal 

![image](https://user-images.githubusercontent.com/92102399/186630837-b3a6d437-46c9-4ce6-b584-bb072a6d7914.png)
![image](https://user-images.githubusercontent.com/92102399/186630989-e2974f45-5e6a-42dc-8162-6e98178c65a6.png)

Would it be possible to make this functions available/accessible for the Cloud Version (Business Central) ?

Thanks in advance. 

Kind regards,
Nicolas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.
