### ISSUE TITLE
[Extensibility Enhancement] page 99000959 "Order Promising Lines - SetSourceType for Enum

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#19985]
Could you please provide an overload of the procedure `` on Page `page 99000959 "Order Promising Lines"`, that supports the new Enum?
```al
procedure SetSourceType(SourceType: Option)
    begin
        CrntSourceType := "Order Promising Line Source Type".FromInteger(SourceType);
    end;
```

NEW Procedure:
```al
procedure SetOrderPromisingLineSourceType(SourceType: Enum "Order Promising Line Source Type")
    begin
        CrntSourceType := SourceType;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46015.
