### ISSUE TITLE
[Event Change Request] Table 9651 "Report Layout Selection" - OnBeforeHasNormalCustomLayoutSelection

### ISSUE THREAD

**Issue by MMueller1974** [microsoft/ALAppExtensions#19989]
Dear ALAppExtensions team,

could you please add the "Rec" th the Event OnBeforeHasNormalCustomLayoutSelection in the Table 9651?

Old signature
```AL
    [IntegrationEvent(false, false)]
    local procedure OnBeforeHasNormalCustomLayoutSelection(ReportID: Integer; var Result: Integer; var Handled: Boolean)
    begin
    end;
```

New signature
```AL
    [IntegrationEvent(false, false)]
    local procedure OnBeforeHasNormalCustomLayoutSelection(var Rec: Record "Report Layout Selection"; ReportID: Integer; var Result: Integer; var Handled: Boolean)
    begin
    end;
```

Thank you in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47704.
