### ISSUE TITLE
[Exposure Request] codeunit 64 "Sales-Get Shipment" - AdjustPrepmtAmtToDeductRounding

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19995]
Please make function AdjustPrepmtAmtToDeductRounding externally available:

```
procedure AdjustPrepmtAmtToDeductRounding(var SalesLine: Record "Sales Line"; RoundingAmount: Decimal)
begin
    if Round(RoundingAmount) <> 0 then begin
        SalesLine."Prepmt Amt to Deduct" -= Round(RoundingAmount);
        SalesLine.Modify();
    end;
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.
