### ISSUE TITLE
[BUG] - Warehouse Shipment Card (80103) - "P&ost Shipment" - OnAfterAction

### ISSUE THREAD

**Issue by Bw-Foodcloud** [microsoft/ALAppExtensions#19996]
Summary: Rec.Modify returns error in OnAfterAction trigger. 

Steps to reproduce error:

1. Reduce the qty. to ship on a Warehouse Shipment to create a partial shipment. 
2. Click Post Shipment action. 
3. Set up a minimal extension with below code (same issue experienced in codeunit event subscriber):

> pageextension 80103 WarehouseShipmentCard extends "Warehouse Shipment"
> {
>     actions
>     {
>         modify("P&ost Shipment")
>         {
>             trigger OnAfterAction()
>             begin
>>                 CurrPage.Update(false);
>                 Rec.Modify();
>             end;
>         }
>     }
> }

**Outcome:**  Error Message: The changes to the Warehouse Shipment Header record cannot be saved because some information on the page is not up-to-date. Close the page, reopen it, and try again. Identification fields and values: No.='WHS-SHIP-0003217'

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
