### ISSUE TITLE
[Event Request] Table 133 "Incoming Document Attachment" - New publisher

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#19999]
Hello, we need a new Event publisher in the procedure "Export". Can you please check that? Thank you!

    procedure Export(DefaultFileName: Text; ShowFileDialog: Boolean): Text
    var
        TempBlob: Codeunit "Temp Blob";
        FileMgt: Codeunit "File Management";
    begin
        OnBeforeExport;                        <=====================

        if "Incoming Document Entry No." = 0 then
            exit;
        CalcFields(Content);
        if not Content.HasValue then
            exit;

        if DefaultFileName = '' then
            DefaultFileName := Name + '.' + "File Extension";

        OnGetBinaryContent(TempBlob, "Incoming Document Entry No.");
        if not TempBlob.HasValue then
            TempBlob.FromRecord(Rec, FieldNo(Content));
        exit(FileMgt.BLOBExport(TempBlob, DefaultFileName, ShowFileDialog));
    end;

New Event:

    [IntegrationEvent(true, false)]
    procedure OnBeforeExport()
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47656.
