### ISSUE TITLE
[Event Request] codeunit 64 "Sales-Get Shipment" - OnBeforeSetSalesHeader

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19997]
Please add new event in codeunit 64:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeSetSalesHeader(var SalesHeader: Record "Sales Header"; var SalesHeader2: Record "Sales Header"; var IsHandled: Boolean)
begin
end;
```

```
procedure SetSalesHeader(var SalesHeader2: Record "Sales Header")
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeSetSalesHeader(SalesHeader, SalesHeader2, IsHandled);
    if IsHandled then
        exit;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47990.
