### ISSUE TITLE
[Exposure Request] codeunit 64 "Sales-Get Shipment" - CalcInvoiceDiscount

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#19994]
Please make function CalcInvoiceDiscount externally available:

```
procedure CalcInvoiceDiscount(var SalesLine: Record "Sales Line")
var
    SalesReceivablesSetup: Record "Sales & Receivables Setup";
    SalesCalcDiscount: Codeunit "Sales-Calc. Discount";
begin
    SalesReceivablesSetup.Get();
    if SalesReceivablesSetup."Calc. Inv. Discount" then begin
        SalesCalcDiscount.CalculateInvoiceDiscountOnLine(SalesLine);
        OnAfterCalcInvoiceDiscount(SalesLine);
    end;
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.
