### ISSUE TITLE
[Event Request] Table 461 "Prepayment Inv. Line Buffer" - New publisher

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#19998]
Hello, we need a new Event publisher in the procedure "FillAdjInvLineBuffer". Can you please check that? Thank you!

    procedure FillAdjInvLineBuffer(PrepmtInvLineBuf: Record "Prepayment Inv. Line Buffer"; GLAccountNo: Code[20]; CorrAmount: Decimal; CorrAmountACY: Decimal)
    begin
        Init;
        Adjustment := true;
        "G/L Account No." := GLAccountNo;
        Amount := CorrAmount;
        "Amount Incl. VAT" := CorrAmount;
        "Amount (ACY)" := CorrAmountACY;
        "Line No." := PrepmtInvLineBuf."Line No.";
        "Global Dimension 1 Code" := PrepmtInvLineBuf."Global Dimension 1 Code";
        "Global Dimension 2 Code" := PrepmtInvLineBuf."Global Dimension 2 Code";
        "Dimension Set ID" := PrepmtInvLineBuf."Dimension Set ID";
        Description := PrepmtInvLineBuf.Description;
	
        OnAfterFillAdjInvLineBuffer(PrepmtInvLineBuf, Rec);       <=============
    end;

New Event:

    [IntegrationEvent(false, false)]
    local procedure OnAfterFillAdjInvLineBuffer(var PrepaymentInvLineBuffer: Record "Prepayment Inv. Line Buffer"; var Rec: Record "Prepayment Inv. Line Buffer")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47995.
