### ISSUE TITLE
Business central on-prem croatian (hr-HR) language bug

### ISSUE THREAD

**Issue by fmoric** [Microsoft/ALAppExtensions#20]
Hello,

There is a bug in Croatian system language, in On-Prem release of Business Central, that comes with installation.

When you change to Croatian language, you get an error when you try to launch any report.

There is a space in boolean translation in ,Yes,No (", Da,Ne"). So when on Croatian you cannot open any report.
![image](https://user-images.githubusercontent.com/18283753/46951689-0521d380-d089-11e8-86db-c5e6cf37fe56.png)

Translated:

Filer " Yes" is not valid for field Public visible on table object options. Value "Yes" cannot be evaluated to boolean type.

BR

**Comment by JesperSchulz** [comment]
We're investigating. Thanks for reporting.

**Comment by JesperSchulz** [comment]
I have provided the translation feedback to our translation supplier. We will fix the issue and make sure that it is included in the next OnPrem update (CU update 2). Thank you for reporting!
