### ISSUE TITLE
Add warehouse documents to Report Selections table

### ISSUE THREAD

**Issue by makuhn** [microsoft/ALAppExtensions#200]
The reports that are used in warehouse module are hard coded (REPORT.RUN(REPORT::xxx). Therefore it is not possible to replace these reports by own reports shipped with an ISV solution.

All warehouse documents should be added to **Report Selections** table. A new page **Report Selection - Warehouse** New field **Show Request Window** (Boolean) should be additionally added to this table. This field should be used as parameter for REPORT.RUN statement.

**Comment by AlexanderYakunin** [comment]
This is already implemented so I'm closing this old request
