### ISSUE TITLE
[Extensibility Bug] T1003 Job Planning Line - UpdatePlannedDueDate

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#20006]
Can you please remove [OnPrem] - Scope of this function. I do not understand, why we should not use it in cloud-scope.

    [Scope('OnPrem')]
    procedure UpdatePlanned(): Boolean
    begin
        CalcFields("Reserved Quantity");
        if Planned = ("Reserved Quantity" = "Remaining Qty.") then
            exit(false);
        Planned := not Planned;
        exit(true);
    end;

    procedure UpdatePlannedDueDate() Changed: Boolean;
    var
        Customer: Record Customer;
        PaymentTerms: Record "Payment Terms";
        DueDateCalculation: DateFormula;
        xPlanningDueDate: Date;
    begin
        xPlanningDueDate := "Planning Due Date";
        if "Planning Date" = 0D then
            exit(false);
        "Planning Due Date" := "Planning Date";
        GetJob();
        if Job."No." = '' then
            exit(false);
        Customer.SetLoadFields("Payment Terms Code");
        if not Customer.Get(Job."Bill-to Customer No.") then
            exit(false);
        PaymentTerms.SetLoadFields("Due Date Calculation");
        if PaymentTerms.Get(Customer."Payment Terms Code") then begin
            PaymentTerms.GetDueDateCalculation(DueDateCalculation);
            "Planning Due Date" := CalcDate(DueDateCalculation, "Planning Date");
        end;
        exit("Planning Due Date" <> xPlanningDueDate);
    end;

The Function is calling PaymentTerms.GetDueDateCalculation, which is marked as On Prem, too:
Please remove there, too. 

table 3 "Payment Terms"

    [Scope('OnPrem')]
    procedure GetDueDateCalculation(var DueDateCalculation: DateFormula)
    begin
        DueDateCalculation := "Due Date Calculation";
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.

**Comment by sergeyol** [comment]
Seems like you have removed [OnPrem] for UpdatePlanned procedure, but not for UpdatePlannedDueDate. @JesperSchulz we also need this, should we create a new issue?

**Comment by JesperSchulz** [comment]
That's be great. Sometimes things are forgotten :-( It's by far the easiest to create a new issue and have the team processing those requests take a 2nd look. Sorry about that!
