### ISSUE TITLE
Please Unabandon BREAKINGCHANGES.md

### ISSUE THREAD

**Issue by JeremyVyska** [microsoft/ALAppExtensions#20003]
There has been a wide variety of Breaking Changes in the past 5 versions, but the BREAKINGCHANGES.md, which the Microsoft Docs site refers you to for reference on how to upgrade code, has not been updated since March 2020.

**Comment by JeremyVyska** [comment]
This was referenced by @JesperSchulz in #11583 as a Retired document, but nothing in the breaking changes page either here or on the Docs site confirms or clarifies that.

Additionally, some breaking changes have not been documented in the code, as is the goal.  For example, the SMTP retirement was a very big breaking change, and there is no official source I could locate that aligns with the BREAKINGCHANGES.md style of "before/after", only community resources.

**Comment by pri-kise** [comment]
Personally i would prefer, if the BreakingChanges.md would keep up to date.

**Comment by JeremyVyska** [comment]
Same.   "In place guidance" is a laudable goal, but for customers jumping from NAV5, NAV2015, or even BC14, having one mega-doc with everything helps create a clear roadmap, as well as gives a very clear understanding to Customers (and non-Dev Managers) why the work effort is as many hours as it can take sometimes.

**Comment by SHermann73** [comment]
I would prefer to have this document updated as well.
I just stumbled accross an issue/breaking change in BCv21 and looking for an offical source of information.

**Comment by AlexanderYakunin** [comment]
@JesperSchulz - can you answer questions above?

**Comment by JesperSchulz** [comment]
It's good to hear, that many of you miss the BreakingChanges.md document - it means we did the right thing back then. However, as stated before, it was never meant to be a permanent solution. It was a temporary solution, where we documented all the breaking changes we made, when we introduced the System Application (before we had the deprecation concept).
I've noted the wish for better documentation of breaking changes, and we'll see what we can do. I doubt we'll keep official documentation in an md file on the ALAppExtensions GitHub repo, but maybe we can find a new home; and possibly even a better format! I will keep this issue open for now as a reminder, that there is a wish for better breaking change documentation in the community :-)

**Comment by JesperSchulz** [comment]
We're working on documenting breaking changes in a different way (from version 23.0, see "User Groups" as an example: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/deprecated-features-user-groups). If this new way proves successful, we will start documenting all larger breaking changes like that.
