### ISSUE TITLE
[Event Request] page 5709 "Get Receipt Lines" - OnBeforeSetPurchHeader

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#20002]
Please extend event OnBeforeSetPurchHeader in page 5709 "Get Receipt Lines":

```
[IntegrationEvent(false, false)]
local procedure OnBeforeSetPurchHeader(var PurchHeader: Record "Purchase Header"; var PurchHeader2: Record "Purchase Header"; var IsHandled: Boolean)
begin
end;
```

```
IsHandled := false;
OnBeforeSetPurchHeader(PurchHeader, PurchHeader2, IsHandled);
if IsHandled then
    exit;
```

**Comment by Vadim-Stepanenko** [comment]
Please clarify this request, there is no **OnBeforeSetPurchHeader** in either page 5708 (from title) nor Codeunit 64 (from text)

**Comment by miljance** [comment]
Thank you for the info. I have updated the title and the text also.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47702.
