### ISSUE TITLE
[Event Change Request] report 790 "Calculate Inventory" - OnRetrieveBufferOnBeforeFind

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#20011]
Could you please include the sender on the event `OnRetrieveBufferOnBeforeFind`?
```al
//+Change
//-[IntegrationEvent(false, false)]
[IntegrationEvent(true, false)]
//-Change
local procedure OnRetrieveBufferOnBeforeFind(var InventoryBuffer: Record "Inventory Buffer"; ItemLedgerEntry: Record "Item Ledger Entry")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47404.
