### ISSUE TITLE
[Access Request] report 790 "Calculate Inventory" AddZeroQtySKU

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#20015]
Could you please remove the `Scope('OnPrem')` of the procedure `AddZeroQtySKU` and make it accesible for Report Extensions by keeping at least the procedure _protected_?
```al
    //+Change
    //-[Scope('OnPrem')]
    //-procedure AddZeroQtySKU()
    protected procedure AddZeroQtySKU()
    //-Change
    var
        SKU: Record "Stockkeeping Unit";
        ShouldAddZeroQty: Boolean;
        IsHandled: Boolean;
    begin
        ...
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.

**Comment by AlexanderYakunin** [comment]
As you have requested this change AFTER code freeze for 21.0, this change is available in 22.x only.
