### ISSUE TITLE
[Event Request] Codeunit 1371 Sales Batch Post Mgt - OnBeforeRunBatch ==> Change Parameters

### ISSUE THREAD

**Issue by RaKuNbg** [microsoft/ALAppExtensions#20017]
With [(https://github.com/microsoft/ALAppExtensions/issues/10960)] the publisher "OnBeforeRunBatch" had been introduced.

In the moment, this publisher  has only two parameters that ar defined as VAR
    local procedure OnBeforeRunBatch(var SalesHeader: Record "Sales Header"; var ReplacePostingDate: Boolean; PostingDate: Date; ReplaceDocumentDate: Boolean; Ship: Boolean; Invoice: Boolean)
    begin
    end;
       
Please change this publisher so that all parameters are defined as VAR and so that they can be changed in a subscriber

local procedure OnBeforeRunBatch(var SalesHeader: Record "Sales Header"; var ReplacePostingDate: Boolean; var PostingDate: Date; var ReplaceDocumentDate: Boolean; var Ship: Boolean; var Invoice: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47656.
