### ISSUE TITLE
[Event Request] Codeunit 6620 Copy Document Mgt CopyPurchLinesToDoc Functions

### ISSUE THREAD

**Issue by sboeve** [Microsoft/ALAppExtensions#2001]
Hi,
In CopyPurchRcptLinesToDoc, CopyPurchCrMemoLinesToDoc and CopyPurchReturnShptLinesToDoc functions within Copy Document Mgt we update ancillary tables after the original document line is updated.  We requite the variable for the original document to perform this functionality.

We are requesting that you add an event in each of the above functions after the line is copied which will take the ToSalesLine and FromSalesLine as parameters.  They can be passed in as VAR.

Examples below:
[External] CopyPurchRcptLinesToDoc(ToPurchHeader : Record "Purchase Header";VAR FromPurchRcptLine : Record "Purch. Rcpt. Line";VAR LinesNotCopied : Integer;VAR MissingExCostRevLink : Boolean)
MissingExCostRevLink := FALSE;
InitCurrency(ToPurchHeader."Currency Code");
OpenWindow;

WITH FromPurchRcptLine DO
    ...
    IF CopyPurchLine(ToPurchHeader,ToPurchLine,FromPurchHeader,FromPurchLineBuf,NextLineNo,LinesNotCopied,
               FALSE,DeferralTypeForPurchDoc(PurchDocType::"Posted Receipt"),CopyPostedDeferral,FromPurchLineBuf."Line No.")
          THEN
            IF CopyItemTrkg THEN BEGIN
                ...
            END;
*** New Handler ***  OnAfterCopyPurchRcptLines(ToPurchLine, FromPurchRcptLine);

[External] CopyPurchCrMemoLinesToDoc(ToPurchHeader : Record "Purchase Header";VAR FromPurchCrMemoLine : Record "Purch. Cr. Memo Line";VAR LinesNotCopied : Integer;VAR MissingExCostRevLink : Boolean)
MissingExCostRevLink := FALSE;
InitCurrency(ToPurchHeader."Currency Code");
...
OpenWindow;

WITH FromPurchCrMemoLine DO
    ...
    IF CopyPurchLine(ToPurchHeader,ToPurchLine,FromPurchHeader,FromPurchLine2,NextLineNo,LinesNotCopied,
           "Return Shipment No." = '',DeferralTypeForPurchDoc(PurchDocType::"Posted Credit Memo"),CopyPostedDeferral,
           GetPurchLineNo(TempDocPurchaseLine,FromPurchLine2."Line No."))
      THEN BEGIN
            IF CopyPostedDeferral THEN
                ...

*** New Handler ***  OnAfterCopyPurchCrMemoLines(ToPurchLine, FromPurchCrMEmoLine);

[External] CopyPurchReturnShptLinesToDoc(ToPurchHeader : Record "Purchase Header";VAR FromReturnShptLine : Record "Return Shipment Line";VAR LinesNotCopied : Integer;VAR MissingExCostRevLink : Boolean)
MissingExCostRevLink := FALSE;
InitCurrency(ToPurchHeader."Currency Code");
OpenWindow;

WITH FromReturnShptLine DO
    ...
    IF CopyPurchLine(ToPurchHeader,ToPurchLine,FromPurchHeader,FromPurchLineBuf,NextLineNo,LinesNotCopied,
               FALSE,DeferralTypeForPurchDoc(PurchDocType::"Posted Return Shipment"),CopyPostedDeferral,
               FromPurchLineBuf."Line No.")
          THEN BEGIN(will need to be added)
            IF CopyItemTrkg THEN BEGIN
              IF SplitLine THEN
                ...
            END;
*** New Handler ***  OnAfterCopyPurchReturnShptLines(ToPurchLine, FromReturnShptLine);
           
          END;

**Comment by AlexanderYakunin** [comment]
This is already done earlier
