### ISSUE TITLE
[Request-For-External] Report 117 Reminder - Global variables

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#20026]
Hi, could you please change the protection level of the following variables on report 117 (**Reminder**) to a **protected**: **ReferenceText**, **VATNoText**, **NNC_TotalInclVAT**, **ShowNotDueAmounts**, **EndLineNo**?
```AL
    protected var
        ReferenceText: Text[35];
        VATNoText: Text[30];
        NNC_TotalInclVAT: Decimal;
        ShowNotDueAmounts: Boolean;
        EndLineNo: Integer;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.
