### ISSUE TITLE
[Event Request] codeunit 99000809 "Planning Line Management" - OnAfterShouldCheckMultiLevelStructure

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#20021]
procedure CheckMultiLevelStructure(ReqLine2: Record "Requisition Line"; CalcRouting: Boolean; CalcComponents: Boolean; PlanningLevel: Integer)
        ...
        if not Item3.Get(ReqLine2."No.") then
            exit;
        //if Item3."Manufacturing Policy" <> Item3."Manufacturing Policy"::"Make-to-Order" then A200F0008.Event20.04.o
        if not ShouldCheckMultiLevelStructure(ReqLine2, Item3) then //A200F0008.Event20.04.n
            exit;

        PlanningLineNo := ReqLine2."Line No.";

    local procedure ShouldCheckMultiLevelStructure(var RequisitionLine: Record "Requisition Line"; var Item: Record Item) Result: Boolean
    begin
        //A200F0008.Event20.04.ns
        Result := Item."Manufacturing Policy" = Item."Manufacturing Policy"::"Make-to-Order";

        OnAfterShouldCheckMultiLevelStructure(RequisitionLine, Item, Result);
        //A200F0008.Event20.04.ne
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterShouldCheckMultiLevelStructure(var RequisitionLine: Record "Requisition Line"; var Item: Record Item; var Result: Boolean)
    begin
        //A200F0008.Event20.04
    end;

**Comment by AlexanderYakunin** [comment]
Already implemented
