### ISSUE TITLE
[Event Request] codeunit 99000787 "Create Prod. Order Lines" - OnAfterSetPlanningLevelCode

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#20020]
var
        ...
        PlanningGetParameters: Codeunit "Planning-Get Parameters";
        ...
    local procedure CheckMultiLevelStructure(Direction: Option Forward,Backward; MultiLevel: Boolean; LetDueDateDecrease: Boolean)
    var
        //Item: Record Item; A200F0008.Event20.04
        //SKU: Record "Stockkeeping Unit"; A200F0008.Event20.04
        MultiLevelStructureCreated: Boolean;
        //IncreasePlanningLevel: Boolean; A200F0008.Event20.04
        IsHandled: Boolean;
    begin
        ...
        if ProdOrderComp.FindSet(true) then
            repeat
                if ProdOrderComp."Planning Level Code" = 0 then begin
                    //A200F0008.Event20.04.os
                    //IncreasePlanningLevel := false;
                    //if SKU.Get(ProdOrderComp."Location Code", ProdOrderComp."Item No.", ProdOrderComp."Variant Code") then
                    //    IncreasePlanningLevel :=
                    //      (SKU."Manufacturing Policy" = SKU."Manufacturing Policy"::"Make-to-Order") and
                    //      (SKU."Replenishment System" = SKU."Replenishment System"::"Prod. Order")
                    //else begin
                    //    Item.Get(ProdOrderComp."Item No.");
                    //    IncreasePlanningLevel :=
                    //      (Item."Manufacturing Policy" = Item."Manufacturing Policy"::"Make-to-Order") and Item.IsMfgItem;
                    //end;
                    //if IncreasePlanningLevel then begin
                    //A200F0008.Event20.04.oe
                    if SetPlanningLevelCode(ProdOrderComp) then begin //A200F0008.Event20.04
                        ProdOrderComp."Planning Level Code" := 1;
                        ProdOrderComp.Modify(true);
                    end;
                end;
                if ProdOrderComp."Planning Level Code" > 0 then
                    MultiLevelStructureCreated :=
                      MultiLevelStructureCreated or
                      CheckMakeOrderLine(ProdOrderComp, ProdOrderLine, Direction, MultiLevel, LetDueDateDecrease);
            until ProdOrderComp.Next() = 0;

    local procedure SetPlanningLevelCode(var ProdOrderComponent: Record "Prod. Order Component") IncreasePlanningLevel: Boolean
    var
        StockkeepingUnit: Record "Stockkeeping Unit";
    begin
        //A200F0008.Event20.04.ns
        PlanningGetParameters.AtSKU(StockkeepingUnit, ProdOrderComponent."Item No.", ProdOrderComponent."Variant Code", ProdOrderComponent."Location Code");
        IncreasePlanningLevel :=
            (StockkeepingUnit."Manufacturing Policy" = StockkeepingUnit."Manufacturing Policy"::"Make-to-Order") AND
            (StockkeepingUnit."Replenishment System" = StockkeepingUnit."Replenishment System"::"Prod. Order");

        OnAfterSetPlanningLevelCode(ProdOrderComponent, StockkeepingUnit, IncreasePlanningLevel);
        //A200F0008.Event20.04.ne
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetPlanningLevelCode(var ProdOrderComponent: Record "Prod. Order Component"; var StockkeepingUnit: Record "Stockkeeping Unit"; var IncreasePlanningLevel: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48086.
