### ISSUE TITLE
[Enum Request] Table 334 "Column Layout" - Field Show

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#20027]
Can you please change the type of field (11; Show; Option) into an extensible enum?

        field(11; Show; Option)
        {
            Caption = 'Show';
            InitValue = Always;
            OptionCaption = 'Always,Never,When Positive,When Negative';
            OptionMembers = Always,Never,"When Positive","When Negative";
        }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46015.
