### ISSUE TITLE
[Event Request] codeunit 99000809 "Planning Line Management" - OnAfterSetPlanningLevelCode

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#20023]
local procedure CreatePlanningComponentFromProdBOM(var PlanningComponent: Record "Planning Component"; ReqLine: Record "Requisition Line"; ProdBOMLine: Record "Production BOM Line"; CompSKU: Record "Stockkeeping Unit"; LineQtyPerUOM: Decimal; ItemQtyPerUOM: Decimal)
        ...
            "Flushing Method" := CompSKU."Flushing Method";
            //A200F0008.Event20.04.os
            //if (SKU."Manufacturing Policy" = SKU."Manufacturing Policy"::"Make-to-Order") and
            //   (CompSKU."Manufacturing Policy" = CompSKU."Manufacturing Policy"::"Make-to-Order") and
            //   (CompSKU."Replenishment System" = CompSKU."Replenishment System"::"Prod. Order")
            //then
            //A200F0008.Event20.04.oe
            if SetPlanningLevelCode(PlanningComponent, ProdBOMLine, SKU, CompSKU) then
                "Planning Level Code" := ReqLine."Planning Level" + 1;

    local procedure SetPlanningLevelCode(var PlanningComponent: Record "Planning Component"; var ProdBOMLine: Record "Production BOM Line"; var SKU: Record "Stockkeeping Unit"; var ComponentSKU: Record "Stockkeeping Unit") Result: Boolean
    begin
        //A200F0008.Event20.04.ns
        Result :=
            (SKU."Manufacturing Policy" = SKU."Manufacturing Policy"::"Make-to-Order") and
            (ComponentSKU."Manufacturing Policy" = ComponentSKU."Manufacturing Policy"::"Make-to-Order") and
            (ComponentSKU."Replenishment System" = ComponentSKU."Replenishment System"::"Prod. Order");

        OnAfterSetPlanningLevelCode(PlanningComponent, ProdBOMLine, SKU, ComponentSKU, Result);
        //A200F0008.Event20.04.ne
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetPlanningLevelCode(var PlanningComponent: Record "Planning Component"; var ProdBOMLine: Record "Production BOM Line"; var SKU: Record "Stockkeeping Unit"; var ComponentSKU: Record "Stockkeeping Unit"; var Result: Boolean)
    begin
        //A200F0008.Event20.04
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45914.
