### ISSUE TITLE
[Request-For-External] Page 39 "General Journal" - UpdateBalance

### ISSUE THREAD

**Issue by AndriiSeverin** [microsoft/ALAppExtensions#20025]
Hi, could you please change the local **UpdateBalance** procedure of page 39 (**General Journal**) to a global one?
```AL
    procedure UpdateBalance()
    begin
        GenJnlManagement.CalcBalance(Rec, xRec, Balance, TotalBalance, ShowBalance, ShowTotalBalance);
        BalanceVisible := ShowBalance;
        TotalBalanceVisible := ShowTotalBalance;
        if ShowTotalBalance then
            NumberOfRecords := Count();
    end;
```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.
