### ISSUE TITLE
Copy Document Mgt Codeunit 6620 need functions set to external

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#2002]
Hi,

We utilize the below functions to copy additional documents in the same method that NAV does so.  Previously we had our functions within the Copy Document Mgt codeunit so this was not an issue.  However as we move to having our solution live in an extension, we now require the below functions to have external visibility.

CopyFieldsFromOldServHeader  
CheckDateOrder
CheckFromServHeader  
  

Thank you!

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
