### ISSUE TITLE
[Event Extension Request] Table 221 "Gen. Jnl. Allocation" - new Parameter in Publisher OnAfterShowDimensions

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#20031]
Hello, we need a new Parameter in the Publisher OnAfterShowDimensions. Can you please check that? Thank you!

    procedure ShowDimensions()
    begin
        "Dimension Set ID" :=
          DimMgt.EditDimensionSet("Dimension Set ID",
            StrSubstNo('%1 %2 %3', "Journal Template Name", "Journal Batch Name", "Journal Line No."),
            "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");
        
        OnAfterShowDimensions(Rec, xRec);            <===============
    end;

New Event signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterShowDimensions(var GenJnlAllocation: Record "Gen. Jnl. Allocation"; var xGenJnlAllocation: Record "Gen. Jnl. Allocation")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47702.
