### ISSUE TITLE
[Event Request] Table 5809 "Item Charge Assignment (Sales)" - New publisher

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#20038]
Hello, we need a new Event publisher in the procedure SalesLineInvoiced. Can you please check that? Thank you!

    procedure SalesLineInvoiced(): Boolean
    begin
        if "Applies-to Doc. Type" <> "Document Type" then
            exit(false);
        SalesLine.Get("Applies-to Doc. Type", "Applies-to Doc. No.", "Applies-to Doc. Line No.");
        OnSalesLineInvoicedOnAfterSalesLineGet(Rec, SalesLine);                           <=====================
        exit(SalesLine.Quantity = SalesLine."Quantity Invoiced");
    end;

New Event:

    [IntegrationEvent(false, false)]
    local procedure OnSalesLineInvoicedOnAfterSalesLineGet(ItemChargeAssignmentSales: Record "Item Charge Assignment (Sales)"; SalesLine: Record "Sales Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47704.
