### ISSUE TITLE
[Event Request] Table 5103 "Interaction Tmpl. Language" - New publisher

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#20030]
Hello, we need a new Event publisher in the procedure ImportAttachment. Can you please check that? Thank you!

    procedure ImportAttachment()
    var
        Attachment: Record Attachment;
    begin
        if "Attachment No." <> 0 then begin
            if Attachment.Get("Attachment No.") then
                Attachment.TestField("Read Only", false);
            if not Confirm(Text001, false) then
                exit;
        end;

        if Attachment.ImportAttachmentFromClientFile('', false, false) then begin
            "Attachment No." := Attachment."No.";
	    
            OnImportAttachmentOnBeforeModify(Attcahment);                  <====================

            Modify;
        end else
            Error(Text002);
    end;

New Event:

    [IntegrationEvent(false, false)]
    local procedure OnImportAttachmentOnBeforeModify(Attachment: Record Attachment)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47191.
