### ISSUE TITLE
[Enum Request] Table 7000013 Cartera Report Selections - Field Usage

### ISSUE THREAD

**Issue by antoniomirandalopez** [microsoft/ALAppExtensions#20045]
Can you please change the type of field: 

```
field(1; Usage; Option)
{
     Caption = 'Usage';`
     OptionCaption = 'Bill Group,Posted Bill Group,Closed Bill Group,Bill,Bill Group - Test,Payment Order,Posted Payment Order,Payment Order - Test,Closed Payment Order';
     OptionMembers = "Bill Group","Posted Bill Group","Closed Bill Group",Bill,"Bill Group - Test","Payment Order","Posted Payment Order","Payment Order - Test","Closed Payment Order";
}
```
to a extensible Enum?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46678.
