### ISSUE TITLE
[Event Request] Table 167 "Job" add event in JobLedgEntryExist procedure

### ISSUE THREAD

**Issue by antoniomirandalopez** [microsoft/ALAppExtensions#20047]
Hi ALAppExtensions team.

We need a new event to add filters in JobLedgEntryExist procedure.

New Code:
```
procedure JobLedgEntryExist(): Boolean
var
    JobLedgEntry: Record "Job Ledger Entry";
begin
    Clear(JobLedgEntry);
    JobLedgEntry.SetCurrentKey("Job No.");
    JobLedgEntry.SetRange("Job No.", "No.");
    // >>>> New >>>>>>>>>>>>>>>>
    OnAfterFilterJobLedgEntryExists(JobLedgEntry);
    // <<<< New <<<<<<<<<<<<<<<<
    exit(not JobLedgEntry.IsEmpty());
end;

[IntegrationEvent(false, false)]
local procedure OnAfterFilterJobLedgEntryExists(var JobLedgerEntry: Record "Job Ledger Entry")
begin
end;
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47656.
