### ISSUE TITLE
[Event Request] Table 246 "Requisition Line" - New publisher

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#20043]
Hello, we need a new Event publisher in the procedure SetReservationEntry. Can you please check that? Thank you!

    procedure SetReservationEntry(var ReservEntry: Record "Reservation Entry")
    begin
        ReservEntry.SetSource(DATABASE::"Requisition Line", 0, "Worksheet Template Name", "Line No.", "Journal Batch Name", 0);
        ReservEntry.SetItemData("No.", Description, "Location Code", "Variant Code", "Qty. per Unit of Measure");
        if Type <> Type::Item then
            ReservEntry."Item No." := '';
        ReservEntry."Expected Receipt Date" := "Due Date";
        ReservEntry."Shipment Date" := "Due Date";
        ReservEntry."Planning Flexibility" := "Planning Flexibility";
	
        OnAfterSetReservationEntry(Rec, ReservEntry);                      <==================
    end;

New Event:

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetReservationEntry(RequisitionLine: Record "Requisition Line"; var ReservEntry: Record "Reservation Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47191.
