### ISSUE TITLE
[Event Change] Codeunit 7304 Whse. Jnl.-Register Batch Event -OnAfterPostJnlLines

### ISSUE THREAD

**Issue by picazin** [Microsoft/ALAppExtensions#2004]
Hi

I'm trying to make and extension using this event. 

When trying to show a message, it fails due to Window var is still open so it fails. I also think event should be after commit in order to allow create other actions and post is completely done

![image](https://user-images.githubusercontent.com/24437960/55625297-9d7f5200-57a8-11e9-89f5-6399870feb1c.png)

**Comment by AlexanderYakunin** [comment]
Another event OnAfterCode(WhseJnlLine,WhseJnlBatch,WhseRegNo); added in the end of procedure
