### ISSUE TITLE
[Event Change Request] Codeunit 12, Gen. Jnl.-Post Line - OnBeforeRunWithCheck, OnBeforeRunWithoutCheck

### ISSUE THREAD

**Issue by FrankDickschat** [microsoft/ALAppExtensions#20044]
Dear ALAppExtensions team,

could you please change the following 2 Events in CU12 to include the sender:

- OnBeforeRunWithCheck
- OnBeforeRunWithoutCheck

OnAfterRunWithCheck, OnAfterRunWithoutCheck already include the sender but the Before Events do not yet include them.

Original:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeRunWithCheck(var GenJournalLine: Record "Gen. Journal Line"; var GenJournalLine2: Record "Gen. Journal Line");
    begin
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeRunWithoutCheck(var GenJournalLine: Record "Gen. Journal Line"; var GenJournalLine2: Record "Gen. Journal Line");
    begin
    end;
```

Requested Change:

```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeRunWithCheck(var GenJournalLine: Record "Gen. Journal Line"; var GenJournalLine2: Record "Gen. Journal Line");
    begin
    end;
```
```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeRunWithoutCheck(var GenJournalLine: Record "Gen. Journal Line"; var GenJournalLine2: Record "Gen. Journal Line");
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47404.
