### ISSUE TITLE
[Event Request] Add Contacts/Reduce Contacts/Refine Contacts in Segments

### ISSUE THREAD

**Issue by KaiSwitalla** [microsoft/ALAppExtensions#20059]
Hello,

In the segments, currently the job "Add contacts" is already developed so that you can customize it. However not the two functionalities
- Reduce contacts
- Refine contacts.

The two reports do not yet have events, nor are elementary global variables usable.

Minimum requirement:
the reports must be able to be extended by dataitems and the extension must be integrable into the other business logic in these objects.  
![Segments](https://user-images.githubusercontent.com/26924867/187228650-88bebf03-642f-46bc-88dc-745465bbd9b6.png)

Translated with www.DeepL.com/Translator (free version)

**Comment by AlexanderYakunin** [comment]
Excuse me, we cannot process this request. We can implement needed events or make global variables protected, if you create requests with event specifications and placement in the code. Or with definition which variables in which report should become protected. Please create new requests if you still need something in this area.
