### ISSUE TITLE
[Event Request] Table 23 "Vendor" add event in trigger OnLookup(), field(7; City; Text[30]) and  field(91; "Post Code"; Code[20])

### ISSUE THREAD

**Issue by MeFrancois** [microsoft/ALAppExtensions#20051]
Hi ALAppExtensions team.

Could you add those events in Table 23 "Vendor"

New Code:

        field(7; City; Text[30])
        {
            Caption = 'City';
            TableRelation = IF ("Country/Region Code" = CONST('')) "Post Code".City
            ELSE
            IF ("Country/Region Code" = FILTER(<> '')) "Post Code".City WHERE("Country/Region Code" = FIELD("Country/Region Code"));
            //This property is currently not supported
            //TestTableRelation = false;
            ValidateTableRelation = false;

            trigger OnLookup()
            begin
                OnBeforeLookupCity(Rec, PostCode);

                PostCode.LookupPostCode(City, "Post Code", County, "Country/Region Code");

                //>>>> NEW >>>>>>>>>>>>>>>>>
                OnAfterLookupCity(Rec, PostCode);
                // <<<<NEW<<<<<<<<<<<<<<<<<
            end;

            trigger OnValidate()
            begin
                OnBeforeValidateCity(Rec, PostCode);

                PostCode.ValidateCity(City, "Post Code", County, "Country/Region Code", (CurrFieldNo <> 0) and GuiAllowed);

                OnAfterValidateCity(Rec, xRec);
            end;
        }
        ...
        field(91; "Post Code"; Code[20])
        {
            Caption = 'Post Code';
            TableRelation = IF ("Country/Region Code" = CONST('')) "Post Code"
            ELSE
            IF ("Country/Region Code" = FILTER(<> '')) "Post Code" WHERE("Country/Region Code" = FIELD("Country/Region Code"));
            //This property is currently not supported
            //TestTableRelation = false;
            ValidateTableRelation = false;

            trigger OnLookup()
            begin
                OnBeforeLookupPostCode(Rec, PostCode);

                PostCode.LookupPostCode(City, "Post Code", County, "Country/Region Code");

                 // >>>> NEW >>>>>>>>>>>>>>>>>
                OnAfterLookupPostCode(Rec, PostCode);
                // <<<<NEW<<<<<<<<<<<<<<<<<
            end;

            trigger OnValidate()
            begin
                OnBeforeValidatePostCode(Rec, PostCode);

                PostCode.ValidatePostCode(City, "Post Code", County, "Country/Region Code", (CurrFieldNo <> 0) and GuiAllowed);

                OnAfterValidatePostCode(Rec, xRec);
            end;
        }

             // >>>> NEW >>>>>>>>>>>>>>>>>
            [IntegrationEvent(false, false)]
            local procedure OnAfterLookupCity(var Vendor: Record Vendor; var PostCodeRec: Record "Post Code")
            begin
            end;

            [IntegrationEvent(false, false)]
            local procedure OnAfterLookupPostCode(var Vendor: Record Vendor; var PostCodeRec: Record "Post Code")
            begin
            end;
            // <<<<NEW<<<<<<<<<<<<<<<<<

Thanks,
François

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48091.
