### ISSUE TITLE
[Code Refactoring] Report 1401 - FormatNoText > AmountToText (without decimals)

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#2005]
I'd like to get a function that prints an amount as text. In report 1401, the FormatNoText is suited for this, although it add too many clutter to the result.

For value 1423, I'd like to get 'THOUSAND FOUR HUNDRED TWENTY THREE' as a result.

Can you please split up the FormatNoText and provide a function that does not add the prefix / suffix / AND / decimal part?

```
Check.InitTextVariable;
Check.FormatNoText(text, 1423,'');

```

Current result:
**** ONE THOUSAND FOUR HUNDRED TWENTY THREE AND 0/100 - 

Required result:
THOUSAND FOUR HUNDRED TWENTY THREE

**Comment by fvet** [comment]
We've added a custom function to the Check report with following structure

```
[External] FormatNoTextNoDecimals(VAR NoText : ARRAY [2] OF Text[80];No : Decimal)
CLEAR(NoText);
NoTextIndex := 1;
GLSetup.GET;

IF No < 1 THEN
  AddToNoText(NoText,NoTextIndex,PrintExponent,Text026)
ELSE
  FOR Exponent := 4 DOWNTO 1 DO BEGIN
    PrintExponent := FALSE;
    Ones := No DIV POWER(1000,Exponent - 1);
    Hundreds := Ones DIV 100;
    Tens := (Ones MOD 100) DIV 10;
    Ones := Ones MOD 10;
    IF Hundreds > 0 THEN BEGIN
      AddToNoText(NoText,NoTextIndex,PrintExponent,OnesText[Hundreds]);
      AddToNoText(NoText,NoTextIndex,PrintExponent,Text027);
    END;
    IF Tens >= 2 THEN BEGIN
      AddToNoText(NoText,NoTextIndex,PrintExponent,TensText[Tens]);
      IF Ones > 0 THEN
        AddToNoText(NoText,NoTextIndex,PrintExponent,OnesText[Ones]);
    END ELSE
      IF (Tens * 10 + Ones) > 0 THEN
        AddToNoText(NoText,NoTextIndex,PrintExponent,OnesText[Tens * 10 + Ones]);
    IF PrintExponent AND (Exponent > 1) THEN
      AddToNoText(NoText,NoTextIndex,PrintExponent,ExponentText[Exponent]);
    No := No - (Hundreds * 100 + Tens * 10 + Ones) * POWER(1000,Exponent - 1);
  END;

// NVT Added
IF DecimalPosition <> 0 THEN BEGIN
  AddToNoText(NoText,NoTextIndex,PrintExponent,Text028);
  DecimalPosition := GetAmtDecimalPosition;
  AddToNoText(NoText,NoTextIndex,PrintExponent,(FORMAT(No * DecimalPosition) + '/' + FORMAT(DecimalPosition)));
END;
```

It would be appreciated if the original 'FormatNoText' function could be stripped to subfunctions, so we can call these to compose our own function (not adding ***, skipping decimals / currency)

**Comment by RomanZanizdra** [comment]
Hi @fvet . 
There will be event publisher OnAfterFormatTextNo in the end of the function with var NoText.

**Comment by fvet** [comment]
@RomanZanizdra 

Why make things that difficult? This way we'll have to 'clean up' the string, by removing '****' (what if in the future this gets refactored?), removing the 'AND' text, the decimals part and the '-' :(

My request is to slightly redesign the content of the 'FormatNoText' function simply by separating the part to display the 'whole numbers' results to a new function. This should not be a breaking change and does not need subscribers.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by fvet** [comment]
@RomanZanizdra Issue just got closed, but did you take into account my latest remarks? If not, can you please reopen?

**Comment by RomanZanizdra** [comment]
Hi @fvet . I took your comments into account but also want to clarify some points from my side. 
It's not difficult to implement what you are asking for particular version and country (w1). But there are other localisations with significantly different formatting amounts into the text. Adjusting of requirements, code and tests for such localisations will take time and bring extra risks which are not mandatory for this case and should be avoided. As i mentioned before there is the event which allows you to do any required formatting and unblock you for further development. 
About your requirements, i suggest you to put them on the ideas site and let people to vote for them, may be somebody brings other valuable extra ideas for it. 
Ping me if we still have things to discuss.
