### ISSUE TITLE
[Access Request] page 6510 "Item Tracking Lines" make RegisterChange global

### ISSUE THREAD

**Issue by SBiernat** [microsoft/ALAppExtensions#20050]
In Page 6510 "Item Tracking Lines":
Would it be possible to set the protected procedure RegisterChange to global, so that is accessible from outside without extending the page itself?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.
