### ISSUE TITLE
[Event Request] Table 981 "Payment Registration Buffer"

### ISSUE THREAD

**Issue by bogdangarkusha** [microsoft/ALAppExtensions#20056]
I would like to ask you to create an Integration event in Table 981 "Payment Registration Buffer", in procedure "PopulateTable()".

    procedure PopulateTable()
    var
        CustLedgerEntry: Record "Cust. Ledger Entry";
        [SecurityFiltering(SecurityFilter::Filtered)]
        Customer: Record Customer;
        PaymentRegistrationSetup: Record "Payment Registration Setup";
    begin
        PaymentRegistrationSetup.Get(UserId);
        PaymentRegistrationSetup.TestField("Bal. Account No.");

        Reset;
        DeleteAll();

        CustLedgerEntry.SetFilter("Document Type", '<>%1', CustLedgerEntry."Document Type"::Payment);
        CustLedgerEntry.SetRange(Open, true);
        // >>
        OnAfterCustLedgerEntrySetFilters(CustLedgerEntry,Rec);
        // <<
        if CustLedgerEntry.FindSet() then begin
            repeat

Event signature:

    [IntegrationEvent(false, false)]
    local procedure OnAfterCustLedgerEntrySetFilters(var CustLedgerEntry: Record "Cust. Ledger Entry"; var PaymentRegistrationBuffer: Record "Payment Registration Buffer")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48091.
