### ISSUE TITLE
Table 1236 JSON Buffer ReadFromText issue

### ISSUE THREAD

**Issue by yrest** [microsoft/ALAppExtensions#2006]
**Describe the bug**
ReadFromText function in Table 1236 formats System.DateTime 

**To Reproduce**
Using above function import any JSON with DateTime 

**Expected behavior**
Expected to see a value like following
_2019-04-05T15:48:17.1319021+01:00_
Instead it brings formatted value of 
_05/04/19 15:48_

**Versions:**
 - Business Central: Spring 2019

**Comment by ikoletic** [comment]
Your issues seems to be a product bug. Please reach out to the relevant support channels as specified in Product Support for [On premises](https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f) or [On line](https://partner.microsoft.com/en-us/pcv/dashboard/overview)
