### ISSUE TITLE
[Event Change Request] Table 36 Sales Header - Procedure UpdateShipToAddressFromSellToAddress

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#20061]
Dear ALAppExtensions Team,

We would like to request the following change

    local procedure UpdateShipToAddressFromSellToAddress(FieldNumber: Integer)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateShipToAddressFromSellToAddress(Rec, FieldNumber, IsHandled);
        if IsHandled then
            exit;
    
        if ("Ship-to Code" = '') and ShipToAddressEqualsOldSellToAddress then begin
            case FieldNumber of
                FieldNo("Ship-to Address"):
                    "Ship-to Address" := "Sell-to Address";
                FieldNo("Ship-to Address 2"):
                    "Ship-to Address 2" := "Sell-to Address 2";
                FieldNo("Ship-to City"), FieldNo("Ship-to Post Code"):
                    begin
                        "Ship-to City" := "Sell-to City";
                        "Ship-to Post Code" := "Sell-to Post Code";
                        "Ship-to County" := "Sell-to County";
                        "Ship-to Country/Region Code" := "Sell-to Country/Region Code";
                    end;
                FieldNo("Ship-to County"):
                    "Ship-to County" := "Sell-to County";
                FieldNo("Ship-to Country/Region Code"):
                    "Ship-to Country/Region Code" := "Sell-to Country/Region Code";
            end;
            **//--> change request
            OnAfterUpdateShipToAddressFromSellToAddress(Rec, xRec, FieldNumber);
            //<-- change request**
        end;
        **//--> change request cancel old
        //OnAfterUpdateShipToAddressFromSellToAddress(Rec, xRec, FieldNumber);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47054.
