### ISSUE TITLE
[Event Change Request] Table 36 Sales Header - Field "Bill-to Post Code"

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#20075]
Dear ALAppExtensions Team,

We would like to request the following change

    field(85; "Bill-to Post Code"; Code[20])
    {
        Caption = 'Bill-to Post Code';
        TableRelation = "Post Code";
        //This property is currently not supported
        //TestTableRelation = false;
        ValidateTableRelation = false;
    
        trigger OnLookup()
        begin
            OnBeforeLookupBillToPostCode(Rec, PostCode);
    
            PostCode.LookupPostCode("Bill-to City", "Bill-to Post Code", "Bill-to County", "Bill-to Country/Region Code");
    
            **//--> change request new "xRec" parameter
            OnAfterLookupBillToPostCode(Rec, xRec, PostCode);
            //<-- change request**
        end;
    
        trigger OnValidate()
        begin
            OnBeforeValidateBillToPostCode(Rec, PostCode);
    
            PostCode.ValidatePostCode(
              "Bill-to City", "Bill-to Post Code", "Bill-to County", "Bill-to Country/Region Code", (CurrFieldNo <> 0) and GuiAllowed);
            **//--> change request
            OnAfterValidateBillToPostCode(Rec, xRec);
            //<-- change request**
            ModifyBillToCustomerAddress;
        end;
    }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.
