### ISSUE TITLE
 [Event Change Request] Table 222 Ship-to Address - Field City

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#20077]
Dear ALAppExtensions Team,

We would like to request the following change

    field(7; City; Text[30])
    {
        Caption = 'City';
        TableRelation = IF ("Country/Region Code" = CONST('')) "Post Code".City
        ELSE
        IF ("Country/Region Code" = FILTER(<> '')) "Post Code".City WHERE("Country/Region Code" = FIELD("Country/Region Code"));
        //This property is currently not supported
        //TestTableRelation = false;
        ValidateTableRelation = false;
    
        trigger OnLookup()
        begin
            OnBeforeLookupCity(Rec, PostCode);
    
            PostCode.LookupPostCode(City, "Post Code", County, "Country/Region Code");
    
            **//--> change request new "xRec" parameter
            OnAfterLookupCity(Rec, xRec, PostCode);
            //<-- change request**
        end;
    
        trigger OnValidate()
        begin
            OnBeforeValidateCity(Rec, PostCode);
    
            PostCode.ValidateCity(City, "Post Code", County, "Country/Region Code", (CurrFieldNo <> 0) and GuiAllowed);
        end;
    }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.
