### ISSUE TITLE
[Event Change Request] Table 36 Sales Header - Field "Sell-to Post Code"

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#20071]
Dear ALAppExtensions Team,

We would like to request the following change

    field(88; "Sell-to Post Code"; Code[20])
    {
        Caption = 'Sell-to Post Code';
        TableRelation = IF ("Sell-to Country/Region Code" = CONST('')) "Post Code"
        ELSE
        IF ("Sell-to Country/Region Code" = FILTER(<> '')) "Post Code" WHERE("Country/Region Code" = FIELD("Sell-to Country/Region Code"));
        //This property is currently not supported
        //TestTableRelation = false;
        ValidateTableRelation = false;
    
        trigger OnLookup()
        begin
            OnBeforeLookupSellToPostCode(Rec, PostCode);
    
            PostCode.LookupPostCode("Sell-to City", "Sell-to Post Code", "Sell-to County", "Sell-to Country/Region Code");
    
            **//--> change request new "xRec" parameter
            OnAfterLookupSellToPostCode(Rec, xRec, PostCode);
            //<-- change request**
        end;
    
        trigger OnValidate()
        begin
            OnBeforeValidateSellToPostCode(Rec, PostCode);
    
            PostCode.ValidatePostCode(
              "Sell-to City", "Sell-to Post Code", "Sell-to County", "Sell-to Country/Region Code", (CurrFieldNo <> 0) and GuiAllowed);
            **//--> change request
            OnAfterValidateSellToPostCode(Rec, xRec);
            //<-- change request**
            UpdateShipToAddressFromSellToAddress(FieldNo("Ship-to Post Code"));
            ModifyCustomerAddress;
        end;
    }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.
