### ISSUE TITLE
[Enum Request] Table 99000770 "Manufacturing Comment Line" - "Table Name"

### ISSUE THREAD

**Issue by ZsomborCsaszi** [microsoft/ALAppExtensions#20087]
Hello,
Could you please change the type of this field to a extensible Enum in "Manufacturing Comment Line" table?

```
field(1; "Table Name"; Option)
{
   Caption = 'Table Name';
   OptionCaption = 'Work Center,Machine Center,Routing Header,Production BOM Header';
   OptionMembers = "Work Center","Machine Center","Routing Header","Production BOM Header";
}
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46015.

**Comment by jerryfic** [comment]
Hello @JesperSchulz ,
We didn't found yet in any versions of BC.
Could You tell when will arrive?
Thx for in advance.
BR,
Laszlo
