### ISSUE TITLE
How to migrate Page Modifications to AL

### ISSUE THREAD

**Issue by caprigo** [microsoft/ALAppExtensions#2008]
Hi,

Like a lot of people I am trying to migrate bespoke C/AL code to AL and (in general) can find ways to do most things. However, I am having difficulty with Page modifications and (in particular) being able to access global variables form page event triggers.

Case in question is the Pick Worksheet - page 7345

In this page there are some global variables:
CurrentWkshName
CurrentLocationCode
CurrentSortingMethod

My modification involves adding another variable to set a default zone.

The OnOpenPage trigger is one trigger I want to use but the global variables are not visible.

The only solution I can come up with is to make a separate copy of page 7345 - apply the modifications that I would like and then modify the (4) places that the page is run from through Actions in role centres to call my modified page.

Seems a bit of a sledgehammer way of achieving this but am I missing something? Is this how we are expected to migrate solutions?

Any help appreciated - including MS making the global variables accessible ..

Thanks

**Comment by ikoletic** [comment]
This issue is a question. Please submit your questions on [business central community ](https://community.dynamics.com/business/f/758) or on [BC development yammer groups](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035).
