### ISSUE TITLE
[Event Request] Page 20 "General Ledger Entries"- GetCaption

### ISSUE THREAD

**Issue by ZsomborCsaszi** [microsoft/ALAppExtensions#20084]
Hello,
Can you please add an event as following into GetCaption procedure:

```
local procedure GetCaption(): Text[250]
var
        RetCaption: Text[250];
        IsHandled: Boolean;
begin
        //>>New Event
        IsHandled := false;
        OnBeforeGetCaption(Rec, GLAcc, RetCaption, IsHandled);
        if IsHandled then
            exit(RetCaption);
        //<<New Event

        if GLAcc."No." <> "G/L Account No." then
            if not GLAcc.Get("G/L Account No.") then
                if GetFilter("G/L Account No.") <> '' then
                    if GLAcc.Get(GetRangeMin("G/L Account No.")) then;
        exit(StrSubstNo('%1 %2', GLAcc."No.", GLAcc.Name))
end;
```

Event:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeGetCaption(GLEntry: Record "G/L Entry"; GLAcc: Record "G/L Account"; var RetCaption: Text[250]; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.

**Comment by jerryfic** [comment]
Hello @JesperSchulz ,
We didn't found yet in any versions of BC.
Could You tell when will arrive?
Thx for in advance.
BR,
Laszlo

**Comment by JesperSchulz** [comment]
This event should get added with 21.1, if the backport made it in time. If not, it will be 21.2.
