### ISSUE TITLE
table 114 "Sales Cr.Memo Header" -  new integration event in procedure DoPrintToDocumentAttachment

### ISSUE THREAD

**Issue by GregorJacobsen** [microsoft/ALAppExtensions#20094]
Similar to the event "OnBeforeDoPrintToDocumentAttachment" in the "Sales Invoice Header", we would like to have an event in the "Sales Cr.Memo Header". We subscribe to this in our product knkPublishing to call the function SaveAsDocumentAttachment with a different "ReportSelections.Usage" based on the value of product relevant fields in the Sales Cr.Memo Header.

Changes in **DoPrintToDocumentAttachment**
```
    local procedure DoPrintToDocumentAttachment(SalesCrMemoHeader: Record "Sales Cr.Memo Header"; ShowNotificationAction: Boolean)
    var
        ReportSelections: Record "Report Selections";
        //added IsHandled Flag
        IsHandled: Boolean;
    begin
        // Call new event start
        IsHandled := false;
        OnBeforeDoPrintToDocumentAttachment(SalesCrMemoHeader, ShowNotificationAction, IsHandled);
        if IsHandled then
            exit;
        // Call new event stop
        SalesCrMemoHeader.SetRecFilter();
        ReportSelections.SaveAsDocumentAttachment(
            ReportSelections.Usage::"S.Cr.Memo".AsInteger(), SalesCrMemoHeader, SalesCrMemoHeader."No.", SalesCrMemoHeader."Bill-to Customer No.", ShowNotificationAction);
    end;
   
```

new Integration Event **OnBeforeDoPrintToDocumentAttachment**
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDoPrintToDocumentAttachment(var SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var ShowNotificationAction: Boolean; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.
