### ISSUE TITLE
table 6660 "Return Receipt Header" - new integration event in procedure EmailRecords

### ISSUE THREAD

**Issue by GregorJacobsen** [microsoft/ALAppExtensions#20097]
Similar to the event "OnBeforePrintRecords" in the "Return Receipt Header", we would like to have an event in the procedure "EmailRecords". We subscribe to this in our product knkPublishing to call the function TrySendToEMail with a different "ReportSelections.Usage" based on the values of product relevant fields in Return Receipt Header.

Changes in **EmailRecords**

```
    procedure EmailRecords(ShowDialog: Boolean)
    var
        DocumentSendingProfile: Record "Document Sending Profile";
        DummyReportSelections: Record "Report Selections";
        ReportDistributionMgt: Codeunit "Report Distribution Management";
        //added IsHandled Flag
        IsHandled: Boolean;
    begin
        // Call new event start
        IsHandled := false;
        OnBeforeEmailRecords(Rec, ShowDialog, IsHandled);
        if IsHandled then
            exit;
        // Call new event stop
        DocumentSendingProfile.TrySendToEMail(
          DummyReportSelections.Usage::"S.Ret.Rcpt.".AsInteger(), Rec, FieldNo("No."),
          ReportDistributionMgt.GetFullDocumentTypeText(Rec), FieldNo("Bill-to Customer No."), ShowDialog);
    end;
```
new Integration Event **OnBeforeEmailRecords**

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeEmailRecords(var ReturnRcptHeader: Record "Return Receipt Header"; ShowDialog: Boolean; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.
