### ISSUE TITLE
[Event Request] codeunit 5807 "Item Charge Assgnt. (Sales)" - OnAssignByAmountOnAfterAssignAppliesToDocLineAmount

### ISSUE THREAD

**Issue by SteveKrisjanovsD365** [microsoft/ALAppExtensions#20092]
For item charge assignments, the event **OnAssignByAmountOnAfterAssignAppliesToDocLineAmount** is available in codeunit 5805 "Item Charge Assgnt. (Purch.)". That same event should be found also in codeunit 5807 "Item Charge Assgnt. (Sales)", but there is no such event.

Please add this event publisher to codeunit 5807 and raise it the same relative spot. 

A comparison of the two codeuits in BC20.4 is as follows:

**codeunit 5805 "Item Charge Assgnt. (Purch.)":**
```
OnAssignByAmountOnAfterAssignAppliesToDocLineAmount(ItemChargeAssgntPurch, TempItemChargeAssgntPurch, PurchHeader, TotalQtyToAssign, TotalAmtToAssign);
if TempItemChargeAssgntPurch."Applies-to Doc. Line Amount" <> 0 then
    TempItemChargeAssgntPurch.Insert
else begin
    ItemChargeAssgntPurch."Amount to Assign" := 0;
    ItemChargeAssgntPurch."Qty. to Assign" := 0;
    ItemChargeAssgntPurch.Modify();
end;
TotalAppliesToDocLineAmount += TempItemChargeAssgntPurch."Applies-to Doc. Line Amount";
```

**codeunit 5807 "Item Charge Assgnt. (Sales)"** (event missing)

```
if TempItemChargeAssgntSales."Applies-to Doc. Line Amount" <> 0 then
    TempItemChargeAssgntSales.Insert
else begin
    ItemChargeAssignmentSales."Amount to Assign" := 0;
    ItemChargeAssignmentSales."Qty. to Assign" := 0;
    ItemChargeAssignmentSales.Modify();
end;
TotalAppliesToDocLineAmount += TempItemChargeAssgntSales."Applies-to Doc. Line Amount";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48091.
