### ISSUE TITLE
Protected variable in report 193 "Issue Finance Charge Memos"

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#20090]
Hi,

Could you please set the variable PostingDateReq to be Protected, report 193 "Issue Finance Charge Memos"?
All variables used on the report's request page should be protected or accessible via some publisher. Otherwise, reportextensions are useless in many cases.

Thanks,
Radovan

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.
