### ISSUE TITLE
T5767 Warehouse Activity Line CheckReservedItemTrkg from local to global

### ISSUE THREAD

**Issue by KReinmann** [microsoft/ALAppExtensions#2009]
Hello,

for our application, we use the function CheckReservedItemTrkg in Table 5767. 
Is it possible to set the function from local to global? 

Thanks in advance,

Best regards, 
Kathrin

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
