### ISSUE TITLE
T36, T37, T38, T81 - Request to change reference-type of parameters in OnAfterCreateDimTableIDs

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/ALAppExtensions#201]
could you change reference-type of parameters TableId and No 

now:
LOCAL [IntegrationEvent] OnAfterCreateDimTableIDs(VAR SalesHeader : Record "Sales Header";FieldNo : Integer;TableID : ARRAY [10] OF Integer;No : ARRAY [10] OF Code[20])

ask for:
LOCAL [IntegrationEvent] OnAfterCreateDimTableIDs(VAR SalesHeader : Record "Sales Header";FieldNo : Integer;# VAR TableID : ARRAY [10] OF Integer;# VAR No : ARRAY [10] OF Code[20])

**Comment by JesperSchulz** [comment]
Closing issue as per @AlexanderYakunin's reply.
