### ISSUE TITLE
[Event Parameter Change] Table 36 Sales Header - procedure SetBillToCustomerAddressFieldsFromCustomer - event OnAfterSetFieldsBilltoCustomer

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#20101]
We would like the parameter/-s CurrFieldNo added to the following event.

Table 36 Sales Header - procedure SetBillToCustomerAddressFieldsFromCustomer - event OnAfterSetFieldsBilltoCustomer

Original:

```
OnAfterSetFieldsBilltoCustomer(Rec, BillToCustomer, xRec, SkipBillToContact);

[IntegrationEvent(false, false)]
local procedure OnAfterSetFieldsBilltoCustomer(var SalesHeader: Record "Sales Header"; Customer: Record Customer; xSalesHeader: Record "Sales Header"; SkipBillToContact: Boolean)
begin
end;
```

Change:

```
OnAfterSetFieldsBilltoCustomer(Rec, BillToCustomer, xRec, SkipBillToContact, CurrFieldNo); // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnAfterSetFieldsBilltoCustomer(var SalesHeader: Record "Sales Header"; Customer: Record Customer; xSalesHeader: Record "Sales Header"; SkipBillToContact: Boolean; CurrFieldNo: Integer) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.
