### ISSUE TITLE
[Event Parameter Change] Table 36 Sales Header - procedure SetBillToCustomerNo - event OnBeforeSetBillToCustomerNo

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#20100]
We would like the parameter/-s xRec, CurrFieldNo added to the following event.

Table 36 Sales Header - procedure SetBillToCustomerNo - event OnBeforeSetBillToCustomerNo

Original:

```
OnBeforeSetBillToCustomerNo(Rec, Cust, IsHandled);

[IntegrationEvent(false, false)]
local procedure OnBeforeSetBillToCustomerNo(var SalesHeader: Record "Sales Header"; var Cust: Record Customer; var IsHandled: Boolean)
begin
end;
```

Change:

```
OnBeforeSetBillToCustomerNo(Rec, Cust, IsHandled, xRec, CurrFieldNo); // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnBeforeSetBillToCustomerNo(var SalesHeader: Record "Sales Header"; var Cust: Record Customer; var IsHandled: Boolean; xSalesHeader: Record "Sales Header"; var CurrFieldNo: Integer) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.
