### ISSUE TITLE
Table 7005 "Price Source" - Protected variable

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#20118]
Hello, I need the following global variable to be set as protected, Can you please make it? Thanks!

```
var
        PriceSourceInterface: Interface "Price Source";
        
        
Protected var
        PriceSourceInterface: Interface "Price Source";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.
