### ISSUE TITLE
Local to Global procedure PopulateApprovalEntryArgument - request codeunit 1535 "Approvals Mgmt."

### ISSUE THREAD

**Issue by DanielBalanCgk** [microsoft/ALAppExtensions#20116]
Hello,

We would like to request changing the _**local procedure PopulateApprovalEntryArgument**_  into a _**global procedure**_ , so we can access it from other codeunits, in order to call it before creating custom approval entries.

codeunit 1535 "Approvals Mgmt."
![image](https://user-images.githubusercontent.com/40453475/187660192-d615d3ff-076f-4c3d-b5ff-62c09c486432.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.
