### ISSUE TITLE
[Enum Request] Table 77 Usage field

### ISSUE THREAD

**Issue by svwfr** [microsoft/ALAppExtensions#2011]
Please convert Usage of Report Selections to an enum.

**Comment by Pieterheinevdm** [comment]
please add this enum type also to the same usage field in table:9657:"Custom Report Selection"

**Comment by rvanbekkum** [comment]
This seems like a duplicate of issue #260, which is marked as "ships-in-future-update".
Probably this one was created because #260 was closed at that time though.

Also, it seems this issue was mistakenly flagged as "event-request" ;).

**Comment by SteveKrisjanovsD365** [comment]
Can we get an update on this enum request?

According to this closed issue https://github.com/microsoft/ALAppExtensions/issues/4901 the enum has been implemented, but I just downloaded 15.2 onprem and the Usage field is still an option.

**Comment by AlexanderYakunin** [comment]
We do not implement enums to 15.X versions, this is breaking change. All enums available in new version.
