### ISSUE TITLE
[Event Request] Page Resource Capacity Settings

### ISSUE THREAD

**Issue by BITSchmitt** [microsoft/ALAppExtensions#20111]
I need an event in the action UpdateCapacity to use another calendar. So the publisher event should be here:
<img width="388" alt="ResCapaSettings" src="https://user-images.githubusercontent.com/112541396/187631796-dda8f57e-b6ae-4ab7-b426-21f18f3038c7.png">

Thank you very much

**Comment by BITSchmitt** [comment]
@AlexanderYakunin Can you estimate when the event will be implemented?

**Comment by AlexanderYakunin** [comment]
We implement 100's events monthly based on their order of creation and our capacity, so I'd expect within a month with current number of active requests. Anyway, you request is missing event specification with needed parameters and therefore will not go to processing before you add this.

**Comment by Vadim-Stepanenko** [comment]
@BITSchmitt when requesting an event please use text instead of pictures and provide desired call of event and its signature so we do not have to guess then parameters you need.
Do you need something like this to change the CustomCalendarChange record or?

OnUpdateCapacityOnBeforeSetCalendar(Rec, CustomizedCalendarChange); with CustomizedCalendarChange being var

**Comment by BITSchmitt** [comment]
@Vadim-Stepanenko Thank you for your hint, I will keep ist in mind.
Yes, I want to change the CustomeCalendarChange but with another var parameter isHandled:
if not Confirm(Text004, false, TableCaption, "No.") then
                        exit;

OnUpdateCapacityOnBeforeSetCalendar(Rec, CustomizedCalendarChange, isHandled); 

if not isHandled then begin
  if CompanyInformation.Get then begin
      CompanyInformation.TestField("Base Calendar Code");
      CalendarMgmt.SetSource(CompanyInformation, CustomizedCalendarChange);
  end;
end;
