### ISSUE TITLE
[Event Change Request] page 343 "Check Credit Limit" - OnAfterCalcCreditLimitLCYProcedure (See Issue: #19497)

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#20133]
I requested the sender on Issue #19497 for the event `OnAfterCalcCreditLimitLCYProcedure `?

```al
//+Change
//-[IntegrationEvent(false, false)]
[IntegrationEvent(true, false)]
//-Change
local procedure OnAfterCalcCreditLimitLCYProcedure(var Customer: Record Customer; var CustCreditAmountLCY: Decimal; var ExtensionAmountsDic: Dictionary of [Guid, Decimal])
begin
end;
```

But the sender is still missing in the latest preview version.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.
