### ISSUE TITLE
[Event Request] Codeunit 6620 - Copy Document Mgt. - OnAfterCopyPostedDeferrals

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#20149]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnAfterCopyPostedDeferrals` to be added to Codeunit 6620 Copy Document Mgt. with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyPostedDeferrals(DeferralDocType: Enum "Deferral Document Type"; FromDocType: Integer; FromDocNo: Code[20]; FromLineNo: Integer; ToDocType: Integer; ToDocNo: Code[20]; ToLineNo: Integer; var StartDate: Date)
    begin
    end;
```

which would be called as follows from `CopyPostedDeferrals`:
```al

            if DeferralHeader.Get(DeferralDocType, '', '', ToDocType, ToDocNo, ToLineNo) then begin
                DeferralHeader."Initial Amount to Defer" := InitialAmountToDefer;
                OnCopyPostedDeferralsOnBeforeDeferralHeaderModify(DeferralHeader);
                DeferralHeader.Modify();
            end;
        end;
        OnAfterCopyPostedDeferrals(DeferralDocType, FromDocType, FromDocNo, FromLineNo, ToDocType, ToDocNo, ToLineNo, StartDate); //New
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.
