### ISSUE TITLE
[Change access scope] table 133 "Incoming Document Attachment" HyperlinkToDocument

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#20147]
Is there a reason, why the procedure `HyperlinkToDocument `OnPrem`?
This procedure doesn't use any procedure that aren't available on the Cloud environment...
Correct me if I'm wrong.
```al
[Scope('OnPrem')]
procedure HyperlinkToDocument(DocumentNo: Code[20]; PostingDate: Date)
var
    IncomingDocumentAttachment: Record "Incoming Document Attachment";
begin
    if ForwardToExistingLink(DocumentNo, PostingDate) then
        exit;
    IncomingDocumentAttachment.SetRange("Incoming Document Entry No.", "Entry No.");
    IncomingDocumentAttachment.SetFilter(Type, '<>%1', IncomingDocumentAttachment.Type::XML);
    if IncomingDocumentAttachment.FindFirst() then
        IncomingDocumentAttachment.Export('', true);
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.
