### ISSUE TITLE
[Event Request] Codeunit 99000773 Calculate Prod. Order - OnBeforeAssignProdOrderLineBinCodeFromProdRtngLineMachineCenter

### ISSUE THREAD

**Issue by juacefer** [microsoft/ALAppExtensions#20140]
Please, add a new event in procedure AssignProdOrderLineBinCodeFromProdRtngLineMachineCenter

procedure AssignProdOrderLineBinCodeFromProdRtngLineMachineCenter(var ProdOrderRoutingLine: Record "Prod. Order Routing Line")
var
	MachineCenter: Record "Machine Center";
	**_IsHandled: Boolean;_**
begin
	MachineCenter.SetRange("Work Center No.", ProdOrderRoutingLine."Work Center No.");
	
	**_IsHandled := false;_**
	**_OnBeforeAssignProdOrderLineBinCodeFromProdRtngLineMachineCenter(ProdOrderRoutingLine, MachineCenter, IsHandled);_**
	**_if IsHandled then_**
		**_exit;_**

	if PAGE.RunModal(PAGE::"Machine Center List", MachineCenter) = ACTION::LookupOK then
		if (ProdOrderRoutingLine."No." <> MachineCenter."No.") or
		   (ProdOrderRoutingLine.Type = ProdOrderRoutingLine.Type::"Work Center")
		then begin
			ProdOrderRoutingLine.Type := ProdOrderRoutingLine.Type::"Machine Center";
			ProdOrderRoutingLine.Validate("No.", MachineCenter."No.");
			FindAndSetProdOrderLineBinCodeFromProdRoutingLines(
			  ProdOrderRoutingLine.Status, ProdOrderRoutingLine."Prod. Order No.", ProdOrderRoutingLine."Routing Reference No.");
		end;
end;

The new event:

[IntegrationEvent(false, false)]
local procedure OnBeforeAssignProdOrderLineBinCodeFromProdRtngLineMachineCenter(var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var MachineCenter: Record "Machine Center"; var IsHandled: Boolean)
begin
end;

Best regards.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48086.
