### ISSUE TITLE
table 38 "Purchase Header" - add parameter to integration event in procedure PrintRecords

### ISSUE THREAD

**Issue by GregorJacobsen** [microsoft/ALAppExtensions#20142]
Similar to the event "OnBeforePrintRecords" in the "Purch. Inv. Header", we would like to have the parameter ShowRequestForm in the event "OnPrintRecordsOnBeforeTrySendToPrinterVendor". We subscribe to this in our product knkPublishing to call the function "TrySendToPrinterVendor" with a different "ReportSelections.Usage" based on the values of product relevant fields in "Purchase Header".

Changed procedure **PrintRecords**

```
    procedure PrintRecords(ShowRequestForm: Boolean)
    var
        DocumentSendingProfile: Record "Document Sending Profile";
        DummyReportSelections: Record "Report Selections";
        IsHandled: Boolean;
    begin
        CheckMixedDropShipment;
        OnPrintRecordsOnAfterCheckMixedDropShipment(Rec);

        IsHandled := false;
        OnPrintRecordsOnBeforeTrySendToPrinterVendor(Rec, ShowRequestForm, IsHandled);  // added ShowRequestForm
        if not IsHandled then
            DocumentSendingProfile.TrySendToPrinterVendor(
                DummyReportSelections.Usage::"P.Order".AsInteger(), Rec, FieldNo("Buy-from Vendor No."), ShowRequestForm);
    end;
```

Changed event **OnPrintRecordsOnBeforeTrySendToPrinterVendor**

```
    [IntegrationEvent(false, false)]
    local procedure OnPrintRecordsOnBeforeTrySendToPrinterVendor(var PurchaseHeader: Record "Purchase Header"; ShowRequestForm: Boolean; var IsHandled: Boolean) // added ShowRequestForm
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.
