### ISSUE TITLE
[Procedure Request] codeunit 8612 "Config. Template Management" - ModifyRecordWithField

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#20145]
In codeunit 8612 "Config. Template Management", there's a call to ModifyRecordWithField

`ModifyRecordWithField(RecRef, FieldRef, ConfigTemplateLine."Default Value", ConfigTemplateLine."Language ID");`

We would like to have full access to the ConfigTemplateLine variable inside the ModifyRecordWithField function.

So above call should be changed by 

`ModifyRecordWithField(RecRef, FieldRef, ConfigTemplateLine);`

This new wrapper function ModifyRecordWithField should be added with **ConfigTemplateLine** as parameter and a similar OnBeforeModifyRecordWithField publisher. The function simply gates all calls to the existing ModifyRecordWithField function with the Value / LanguageID parameters.

```
local procedure ModifyRecordWithField(var RecRef: RecordRef; FieldRef: FieldRef; ConfigTemplateLine: Record "Config. Template Line")
    var
        ConfigValidateMgt: Codeunit "Config. Validate Management";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeModifyRecordWithField(RecRef, FieldRef, ConfigTemplateLine, IsHandled);
        if IsHandled then
            exit;

        ModifyRecordWithField(RecRef, FieldRef, ConfigTemplateLine."Default Value", ConfigTemplateLine."Language ID");
    end;
```

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeModifyRecordWithField(var RecRef: RecordRef; FieldRef: FieldRef; var ConfigTemplateLine: Record "Config. Template Line"; var IsHandled: Boolean)
    begin
    end;
```

Reason why we would need access to ConfigTemplateLine is because we would like to add a custom '**DateFormula**' field on the ConfigTemplateLine, allowing to use config. templates with either default values or with a default **dateformula** (for date fields).

The new function would allow us to replace the **ConfigTemplateLine."Default Value"** with the calculated dateformula result. (via the new OnBeforeModifyRecordWithField publisher)

**Comment by JesperSchulz** [comment]
This issue is going to be taken care of through the BaseApp contribution pilot. Closing this issue, as it won't need to get picked up by the product group.
