### ISSUE TITLE
[Extensibility Request] table 5409 "Prod. Order Routing Line"

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#20141]
Can you please remove Scope OnPrem for this 2 functions.

    // -BUGFIX
    //[Scope('OnPrem')]
    // +BUGFIX
    procedure IsSerial(): Boolean
    begin
        GetProdOrderLine();
        exit(ProdOrderLine."Routing Type" = ProdOrderLine."Routing Type"::Serial)
    end;

    // -BUGFIX
    //[Scope('OnPrem')]
    // +BUGFIX
    procedure GetStartingEndingDateAndTime(var StartingTime: Time; var StartingDate: Date; var EndingTime: Time; var EndingDate: Date)
    begin
        StartingTime := DT2Time("Starting Date-Time");
        StartingDate := DT2Date("Starting Date-Time");
        EndingTime := DT2Time("Ending Date-Time");
        EndingDate := DT2Date("Ending Date-Time");
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 45938.
