### ISSUE TITLE
[Event Parameter Change] Table 39 Purchase Line - OnAfterInternalLeadTimeDays

### ISSUE THREAD

**Issue by NPTihomir** [microsoft/ALAppExtensions#20158]
In table 39 Purchase Line, function InternalLeadTimeDays, there's a publisher invoked called OnAfterInternalLeadTimeDays
None of the parameters in this publisher are sent by VAR.
Shouldn't parameter TotalDays be returned by VAR, so it has an effect in the function InternalLeadTimeDays from where it is invoked?

Original:
> [IntegrationEvent(false, false)]
local procedure OnAfterInternalLeadTimeDays(PurchaseLine: Record "Purchase Line"; PurchDate: Date; TotalDays: DateFormula);
begin
end;

Suggestion:
> [IntegrationEvent(false, false)]
local procedure OnAfterInternalLeadTimeDays(PurchaseLine: Record "Purchase Line"; PurchDate: Date; var TotalDays: DateFormula);
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.
