### ISSUE TITLE
Bug in ROUNDDATETIME

### ISSUE THREAD

**Issue by jcoe-nvt** [microsoft/ALAppExtensions#2015]
During the weekend of 31-03-2019 (switch to summertime: 2:00 to 3:00) I experienced a fault in ROUNDDATETIME.

Rounding a datetime like 015959T up to the nearest minute or hour results in following message:
_'The time '3/31/2019 2:00:00 AM' is not valid in the current time zone. For example, when the clock is adjusted forward, any time in the period that is skipped is invalid.'_

However, a function like ROUNDDATETIME shouldn't give such a message, instead it should round the datetime to 3:00:00 AM...

**Comment by ikoletic** [comment]
Your issues seems to be a product bug. Please reach out to the relevant support channels as specified in Product Support for [On premises](https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f) or [On line](https://partner.microsoft.com/en-us/pcv/dashboard/overview  )
