### ISSUE TITLE
[Event Request] Table 125 - Purch. Cr. Memo Line - OnBeforeShowDeferrals

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#20165]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeShowDeferrals` to be added to Table 125 Purch. Cr. Memo Line with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowDeferrals(PurchCrMemoLine: Record "Purch. Cr. Memo Line"; var IsHandled: Boolean)
    begin
    end;
```

which would be called as follows from `ShowDeferrals`:
```al
    procedure ShowDeferrals()
    var
        IsHandled: Boolean; //New
    begin
        //New start
        IsHandled := false;
        OnBeforeShowDeferrals(Rec, IsHandled);
        if IsHandled then
            exit;
        //New end
        DeferralUtilities.OpenLineScheduleView(
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47990.
