### ISSUE TITLE
[Extensibility Request] Table 5077 "Segment Line" - Change SendCreateOpportunityNotification() to global

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#20160]
We would like to call SendCreateOpportunityNotification() from our event handler in order to stay compatible with other extensions subscribing there, so please change the function to global:
```
procedure SendCreateOpportunityNotification()
[...]
```

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46680.
