### ISSUE TITLE
[Event-Change Request] Table 81 - Gen. Journal Line - OnBeforeBlankJobNo

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20163]
Dear ALAppExtensions team,

through this issue we would like to request a change of event publisher `OnBeforeBlankJobNo` in Table 81 Gen. Journal Line from:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeBlankJobNo(GenJournalLine: Record "Gen. Journal Line"; CurrentFieldNo: Integer; var IsHandled: Boolean)
begin
end;
```
to:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeBlankJobNo(var GenJournalLine: Record "Gen. Journal Line"; CurrentFieldNo: Integer; var IsHandled: Boolean)
begin
end;
```
making the parameter `GenJournalLine` a var parameter.

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46009.
