### ISSUE TITLE
[Event Parameter Change] Table 37 Sales Line - OnValidate Quantity - event OnValidateQuantityOnBeforeCheckQuantityChangeForPriceCalc

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#20175]
We would like the parameter/-s CurrFieldNo added to the following event.

Table 37 Sales Line - OnValidate Quantity - event OnValidateQuantityOnBeforeCheckQuantityChangeForPriceCalc

Original:

```
OnValidateQuantityOnBeforeCheckQuantityChangeForPriceCalc(Rec, xRec);

[IntegrationEvent(false, false)]
local procedure OnValidateQuantityOnBeforeCheckQuantityChangeForPriceCalc(var SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line")
begin
end;
```

Change:

```
OnValidateQuantityOnBeforeCheckQuantityChangeForPriceCalc(Rec, xRec, CurrFieldNo); // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnValidateQuantityOnBeforeCheckQuantityChangeForPriceCalc(var SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line"; CurrFieldNo: Integer) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47021.
