### ISSUE TITLE
table 38 "Purchase Header" - new integration event in procedure SendRecords

### ISSUE THREAD

**Issue by GregorJacobsen** [microsoft/ALAppExtensions#20171]
Similar to the event "OnPrintRecordsOnBeforeTrySendToPrinterVendor" in the procedure "PrintRecords", we would like to have an event in the procedure "SendRecords". We subscribe to this in our product knkPublishing to call the procedure DocumentSendingProfile.SendVendorRecords with a different "ReportSelections.Usage" based on the values of product relevant fields in the Purchase Header.

changes in procedure **SendRecords**

```
    procedure SendRecords()
    var
        DocumentSendingProfile: Record "Document Sending Profile";
        ReportSelections: Record "Report Selections";
        DocTxt: Text[150];
        //added handled flag
        IsHandled: Boolean;
    begin
        CheckMixedDropShipment;
        OnSendRecordsOnAfterCheckMixedDropShipment(Rec);

        GetReportSelectionsUsageFromDocumentType(ReportSelections.Usage, DocTxt);
        //added event call
        IsHandled := false;
        OnSendRecordsOnBeforeSendVendorRecords(ReportSelections.Usage.AsInteger(), Rec, DocTxt, IsHandled);
        if not IsHandled then
            DocumentSendingProfile.SendVendorRecords(
              ReportSelections.Usage.AsInteger(), Rec, DocTxt, "Buy-from Vendor No.", "No.",
              FieldNo("Buy-from Vendor No."), FieldNo("No."));
    end;
```

new integration event **OnSendRecordsOnBeforeSendVendorRecords**

```
    [IntegrationEvent(false, false)]
    local procedure OnSendRecordsOnBeforeSendVendorRecords(ReportUsage: Integer; var PurchaseHeader: Record "Purchase Header"; DocTxt: Text[150]; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47054.
