### ISSUE TITLE
[Request for external] CheckAssociatedSalesOrderLine, UpdatePurchOrderChargeAssgnt

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#20197]
We would like to request the function CheckAssociatedSalesOrderLine and UpdatePurchOrderChargeAssgnt to become global so it can be used in extension development. 
We use the IsHandled pattern in PostUpdateInvoiceLine -> OnBeforePostUpdateInvoiceLine but we required these functions.

    procedure CheckAssociatedSalesOrderLine(PurchaseLine: Record "Purchase Line")
    var
        SalesLine: Record "Sales Line";
        IsHandled: Boolean;
    begin

    procedure UpdatePurchOrderChargeAssgnt(PurchOrderInvLine: Record "Purchase Line"; PurchOrderLine: Record "Purchase Line")
    var
        PurchOrderLine2: Record "Purchase Line";

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46680.
