### ISSUE TITLE
[Event Request] Table 81 - Gen. Journal Line - OnJobTaskNoOnValidateOnBeforeJobTaskIsSet

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20196]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnJobTaskNoOnValidateOnBeforeJobTaskIsSet` in Table 81 Gen. Journal Line with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnJobTaskNoOnValidateOnBeforeJobTaskIsSet(var GenJournalLine: Record "Gen. Journal Line")
begin
end;
```
which would be called as follows in the OnValidate trigger of field `1001 - Job Task No.`:
```AL
trigger OnValidate()
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeValidateJobTaskNo(xRec, IsHandled);
    if IsHandled then
        exit;

    if "Job Task No." <> xRec."Job Task No." then
       Validate("Job Planning Line No.", 0);
    if "Job Task No." = '' then begin
        ClearJobRelatedAmounts();
        exit;
    end;

    // >>>> New >>>>>>>>>>>>>>>>
    OnJobTaskNoOnValidateOnBeforeJobTaskIsSet(Rec);
    // >>>> New >>>>>>>>>>>>>>>>
    if JobTaskIsSet then begin
        CreateTempJobJnlLine();
        CopyDimensionsFromJobTaskLine();
        UpdatePricesFromJobJnlLine();
    end;
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47191.
