### ISSUE TITLE
change code C1005 Function PostDiffBuffer

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/ALAppExtensions#202]
PostDiffBuffer(DocNo   : Code[20];PostingDate : Date;TemplateName : Code[10];BatchName : Code[10])
--
IF JobDiffBuffer[1].FIND('-')   THEN
….
REPEAT
**// begin
//IF JobDiffBuffer[1].Quantity > 0   THEN BEGIN
IF JobDiffBuffer[1].Quantity <> 0   THEN BEGIN
// end**

**Comment by JesperSchulz** [comment]
Could you give me more context about the requested enhancement? Is this a bug in our product? If so, please be aware that this GitHub repository is dedicated to handling issues with published apps and extensibility requests for the latest release of Business Central. If you run into an issue, open a support case. You can open a Support Request to CSS through PartnerSource portal or by contacting your Service Account Manager (SAM) in the local subsidiary, to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company.
Another option would be to file this bug in Collaborate and include details on your Business Central build number and country. Quick link: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

**Comment by JesperSchulz** [comment]
Assuming this isn't needed any more due to missing response and age of issue. Closing issue. If still needed, please open a new issue for us to process! Thanks!
