### ISSUE TITLE
page 1500 Workflows

### ISSUE THREAD

**Issue by MrinalSingha** [microsoft/ALAppExtensions#20208]
Hi,

Can you please make these small following changes in page 1500 Workflows, we need to access these variables and procedures in page extension.

Before
```
    var
        ExportEnabled: Boolean;
```

After
```
    protected var
        ExportEnabled: Boolean;
```

Before
```
local procedure RefreshTempWorkflowBuffer()
```

After 

```
procedure RefreshTempWorkflowBuffer()
```

Before
```
local procedure GetFilterFromSelection() "Filter": Text
```
After
```
procedure GetFilterFromSelection() "Filter": Text
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46680.
