### ISSUE TITLE
[Extend length of field] Page 7002-Sales Prices, Starting Date Filter

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#20209]
On Page 7002 - "Sales Price", we need to extend length of Starting Date Filter from 30 to 50. Please see below picture for your reference

![Page Sales Prices](https://user-images.githubusercontent.com/91654106/188576457-322c46e4-1780-4327-b858-283d8dbeaa0f.png)

Confirm me if it is possible.
Thank you in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47647.
