### ISSUE TITLE
codeunit 1560 "Workflow Imp. / Exp. Mgt"

### ISSUE THREAD

**Issue by MrinalSingha** [microsoft/ALAppExtensions#20212]
Can you please make following procedures global

Before
```
local procedure GetWorkflowCodeListFromXml(TempBlob: Codeunit "Temp Blob") WorkflowCodes: Text
```
After
```
procedure GetWorkflowCodeListFromXml(TempBlob: Codeunit "Temp Blob") WorkflowCodes: Text
```

Before
```
    [TryFunction]
    local procedure TrySelectStr(Index: Integer; InputString: Text; var SelectedString: Text[20])
```

After
```
    [TryFunction]
    procedure TrySelectStr(Index: Integer; InputString: Text; var SelectedString: Text[20])
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46680.
