### ISSUE TITLE
[Event-Change Request] Table 81 - Gen. Journal Line - OnBeforeSetUpNewLine

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20214]
Dear ALAppExtensions team,

through this issue we would like to request a change of event publisher `OnBeforeSetUpNewLine` in Table 81 Gen. Journal Line from:
```AL
local procedure OnBeforeSetUpNewLine(var GenJournalTemplate: Record "Gen. Journal Template"; var GenJournalBatch: Record "Gen. Journal Batch"; var GenJournalLine: Record "Gen. Journal Line"; LastGenJournalLine: Record "Gen. Journal Line"; var GLSetupRead: Boolean; Balance: Decimal; BottomLine: Boolean; var IsHandled: Boolean)
begin
end;
```
to:
```AL
local procedure OnBeforeSetUpNewLine(var RecGenJournalLine: Record "Gen. Journal Line"; var GenJournalTemplate: Record "Gen. Journal Template"; var GenJournalBatch: Record "Gen. Journal Batch"; var GenJournalLine: Record "Gen. Journal Line"; LastGenJournalLine: Record "Gen. Journal Line"; var GLSetupRead: Boolean; Balance: Decimal; BottomLine: Boolean; var IsHandled: Boolean)
begin
end;
```
adding the current Rec of Gen. Journal Line as var parameter to the event publisher.
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47191.
