### ISSUE TITLE
[Exposure Request] Table 27 "Item" - variables ItemTrackingCode and ItemTrackingCode2

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#20228]
Please mark variables ItemTrackingCode and ItemTrackingCode2 as protected variables so that those can be used on table extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46680.
