### ISSUE TITLE
Follow-up for Report 12 "VAT Statement" - protected var HeaderText and PeriodSelection

### ISSUE THREAD

**Issue by alinat2022** [microsoft/ALAppExtensions#20222]
Hello,

Can you please let us know when will this request https://github.com/microsoft/ALAppExtensions/issues/16644 be implemented?

Thank you.

**Comment by AlexanderYakunin** [comment]
It is implemented in version 21.

    protected var
        EndDate: Date;
        StartDate: Date;
        EndDateReq: Date;
        HeaderText: Text[50];
        PrintInIntegers: Boolean;
        PeriodSelection: Enum "VAT Statement Report Period Selection";
        Selection: Enum "VAT Statement Report Selection";
        TotalAmount: Decimal;
        UseAmtsInAddCurr: Boolean;
