### ISSUE TITLE
[Event Request] Report 596 "Exch. Rate Adjustment"

### ISSUE THREAD

**Issue by hgnamvn** [microsoft/ALAppExtensions#20226]
Please help me add new event for Report 596 "Exch. Rate Adjustment":

![image](https://user-images.githubusercontent.com/24407031/188838146-63159696-001f-4e4a-bab4-a2f0db22ca85.png)

![image](https://user-images.githubusercontent.com/24407031/188838030-ff0fbff1-659e-4a42-932b-5f5cdc0538e4.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47832.
