### ISSUE TITLE
page 10038 "Sales Order Stats."  missing ApplicationArea

### ISSUE THREAD

**Issue by ara3n** [microsoft/ALAppExtensions#20234]
The Gross Weight is missing ApplicationArea.  So it's hidden on all the tabs.  

```
field("TotalSalesLine[3].""Gross Weight"""; TotalSalesLine[3]."Gross Weight")

{

//Missing ApplicationArea = Basic, Suite;

Caption = 'Gross Weight';

DecimalPlaces = 0 : 5;

Editable = false;

Importance = Additional;

ToolTip = 'Specifies the gross weight of items on the document.';

}
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
