### ISSUE TITLE
[Extensibility Bug] Missing Action from W1 in BE

### ISSUE THREAD

**Issue by svenbaer** [microsoft/ALAppExtensions#20235]
In the belgium localization we are missing the "Payment Registration" Action on the "Bookkeeper Role Center" 

It exist in W1 but where removed in localization which blocks our app from installation.
I think the external signature of an localization should be additive only.
please add the action and set them to visible=false if not needed.

Tested with these Artifacts:
https://bcartifacts.azureedge.net/sandbox/20.5.45456.46090/w1
https://bcartifacts.azureedge.net/sandbox/20.5.45456.46090/be

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
