### ISSUE TITLE
[Event Request] codeunit 550 "VAT Rate Change Conversion" - OnUpdateRecOnBeforeValidateGenProdPostingGroup

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#20232]
The parameter IsHandled in the Event should be declared as var:
[IntegrationEvent(true, false)]
local procedure OnUpdateRecOnBeforeValidateGenProdPostingGroup(var RecRef: RecordRef; FldRef: FieldRef; VatRateChangeConversion: Record "VAT Rate Change Conversion"; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47182.
