### ISSUE TITLE
[Event Parameter Change] Table 6661 Return Receipt Line - procedure InsertInvLineFromRetRcptLine - event OnInsertInvLineFromRetRcptLineOnAfterInsertAllLines

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#20242]
We would like the parameter/-s IsHandled added to the following event.

Table 6661 Return Receipt Line - procedure InsertInvLineFromRetRcptLine - event OnInsertInvLineFromRetRcptLineOnAfterInsertAllLines

Original:

```
OnInsertInvLineFromRetRcptLineOnAfterInsertAllLines(Rec, SalesLine);

[IntegrationEvent(false, false)]
local procedure OnInsertInvLineFromRetRcptLineOnAfterInsertAllLines(ReturnReceiptLine: Record "Return Receipt Line"; var SalesLine: Record "Sales Line")
begin
end;
```

Change:

```
IsHandled := false; // <-- ADDED
OnInsertInvLineFromRetRcptLineOnAfterInsertAllLines(Rec, SalesLine, IsHandled); // <-- ADDED
if IsHandled then // <-- ADDED
    exit; // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnInsertInvLineFromRetRcptLineOnAfterInsertAllLines(ReturnReceiptLine: Record "Return Receipt Line"; var SalesLine: Record "Sales Line"; var IsHandled: Boolean) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47191.
