### ISSUE TITLE
[Event Request] codeunit 6529 "Item Tracking Navigate Mgt." - OnAfterFindTrackingRecords

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#20249]
Please include sender in the event OnAfterFindTrackingRecords in Codeunit 6529

```
[IntegrationEvent(true, false)]
local procedure OnAfterFindTrackingRecords(var TempRecordBuffer: Record "Record Buffer" temporary; var ItemFilters: Record Item)
begin
end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47651.
