### ISSUE TITLE
[Event Request] report 295 "Combine Shipments" - OnSalesShipmentLineOnAfterGetRecordOnBeforeInsertInvLineFromShptLine

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#20248]
Please extend the event OnSalesShipmentLineOnAfterGetRecordOnBeforeInsertInvLineFromShptLine in report 295:

```
[IntegrationEvent(false, false)]
local procedure OnSalesShipmentLineOnAfterGetRecordOnBeforeInsertInvLineFromShptLine(var SalesLine: Record "Sales Line"; var SalesShipmentLine: Record "Sales Shipment Line")
begin
end;
```

```
SalesShptLine := "Sales Shipment Line";
HasAmount := HasAmount or ("Qty. Shipped Not Invoiced" <> 0);
OnSalesShipmentLineOnAfterGetRecordOnBeforeInsertInvLineFromShptLine(SalesLine, SalesShptLine);
SalesShptLine.InsertInvLineFromShptLine(SalesLine);

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47702.
