### ISSUE TITLE
[Event Request] Table 37 - Sales Line - OnGenProdPostingGroupOnBeforeValidate

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20253]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher OnGenProdPostingGroupOnBeforeValidate in Table 37 Sales Line with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnGenProdPostingGroupOnBeforeValidate(var SalesLine: Record "Sales Line"; var xSalesLine: Record "Sales Line"; var GenProdPostingGrp: Record "Gen. Product Posting Group"; var IsHandled: Boolean);
begin
end;
```
which would be called as follows in the OnValidate trigger of field `75 - Gen. Prod. Posting Group`:
```AL
trigger OnValidate()
var
    // >>>> New >>>>>>>>>>>>>>>>
    IsHandled: Boolean;
    // <<<< New <<<<<<<<<<<<<<<<
begin
    // >>>> New >>>>>>>>>>>>>>>>
    OnGenProdPostingGroupOnBeforeValidate(Rec, xRec, GenProdPostingGrp, IsHandled);
    if IsHandled then
        exit;
    // <<<< New <<<<<<<<<<<<<<<<
    TestJobPlanningLine;
    TestStatusOpen();
    if xRec."Gen. Prod. Posting Group" <> "Gen. Prod. Posting Group" then
        if GenProdPostingGrp.ValidateVatProdPostingGroup(GenProdPostingGrp, "Gen. Prod. Posting Group") then
            Validate("VAT Prod. Posting Group", GenProdPostingGrp."Def. VAT Prod. Posting Group");
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47021.

**Comment by tkr95** [comment]
Hello,

we just checked and noticed that the requested parameter IsHandled is not a var parameter. Can you fix this please?

**Comment by JesperSchulz** [comment]
That I can. Sorry about that! It'll be with 24.0 in April, as this actually is considered a breaking change :-S
