### ISSUE TITLE
[Extensibility Bug] Missing actions from W1 in US

### ISSUE THREAD

**Issue by svenbaer** [microsoft/ALAppExtensions#20258]
In the us localization we are missing actions in 3 pages:

Missing Actions in Project Manager Role Center:

- "Job Sug. Billing"

Missing Actions in Job List:
- "Job Actual to Budget"
- "Job - Suggested Billing"
- "Jobs per Customer"
- "Jobs - Transaction Detail"

Missing Actions in Job Card:
- "Job Actual to Budget"
- "Job - Suggested Billing"

It exist in W1 but where removed in localization which blocks our app from installation.
I think the external signature of an localization should be additive only.
please add the action and set them to visible=false if not needed.

Tested with these Artifacts:
https://bcartifacts.azureedge.net/sandbox/20.5.45456.46090/w1
https://bcartifacts.azureedge.net/sandbox/20.5.45456.46090/us

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
