### ISSUE TITLE
[Extensibility Request] page 5098 "Task Card" - EnableFields

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#20252]
Please expose method EnableFields in page 5098 as global procedures as the function may be used when sender from the Events is being used.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46680.
