### ISSUE TITLE
[Extensibility Request] Page 498 Reservation - Expose Methods

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#20251]
Please expose following methods in page 498 as global procedures as the functions may be used when sender from the Events is being used. Currently those are set to protected:
FilterReservEntry
UpdateReservFrom

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 46680.
