### ISSUE TITLE
[Event Request] Codeunit 6620 Copy Document Mgt. - procedure SplitPstdSalesLinesPerILE

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#20278]
Dear ALAppExtensions Team,

We would like to request the following change

    local procedure SplitPstdSalesLinesPerILE(ToSalesHeader: Record "Sales Header"; FromSalesHeader: Record "Sales Header"; var ItemLedgEntry: Record "Item Ledger Entry"; var TempSalesLineBuf: Record "Sales Line" temporary; FromSalesLine: Record "Sales Line"; var TempDocSalesLine: Record "Sales Line" temporary; var NextLineNo: Integer; var CopyItemTrkg: Boolean; var MissingExCostRevLink: Boolean; FillExactCostRevLink: Boolean; FromShptOrRcpt: Boolean): Boolean
    var
        OrgQtyBase: Decimal;
        OneRecord: Boolean;
    begin
        if FromShptOrRcpt then begin
            TempSalesLineBuf.Reset();
            TempSalesLineBuf.DeleteAll();
        end else
            TempSalesLineBuf.Init();
    
        CopyItemTrkg := false;
    
        if (FromSalesLine.Type <> FromSalesLine.Type::Item) or (FromSalesLine.Quantity = 0) then
            exit(false);
        if IsCopyItemTrkg(ItemLedgEntry, CopyItemTrkg, FillExactCostRevLink) or
           not FillExactCostRevLink or MoveNegLines or
           not ExactCostRevMandatory
        then
            exit(false);
    
        with ItemLedgEntry do begin
            OneRecord := Count() = 1;
            FindSet();
            if Quantity >= 0 then begin
                TempSalesLineBuf."Document No." := "Document No.";
                if GetSalesDocTypeForItemLedgEntry(ItemLedgEntry) in
                   [TempSalesLineBuf."Document Type"::Order, TempSalesLineBuf."Document Type"::"Return Order"]
                then
                    TempSalesLineBuf."Shipment Line No." := 1;
                OnSplitPstdSalesLinesPerILEOnAfterAssignShipmentLineNo(ItemLedgEntry, TempSalesLineBuf);
                exit(false);
            end;
            OrgQtyBase := FromSalesLine."Quantity (Base)";
            repeat
                
            .................................................................
              
            until (Next() = 0) or (FromSalesLine."Quantity (Base)" = 0);
    
            if (FromSalesLine."Quantity (Base)" <> 0) and FillExactCostRevLink then
                MissingExCostRevLink := true;
            **//--> change request
            OnBeforeSplitPstdSalesLinesPerILECheckUnappliedLines(ToSalesHeader,SkippedLine, MissingExCostRevLink)
            //<-- change request**
            CheckUnappliedLines(SkippedLine, MissingExCostRevLink);
        end;
        exit(true);
    end;

    **//--> change request
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSplitPstdSalesLinesPerILECheckUnappliedLines(SalesHeader: Recored "Sales Header"; SkippedLine: Boolean; MissingExCostRevLink: Boolean)
    begin
    end;
    //<-- change request**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48091.
