### ISSUE TITLE
[Event Parameter Change] Codeunit 427 ICInboxOutboxMgt - procedure CreateSalesDocument - event OnCreateSalesDocumentOnAfterSalesHeaderFirstModify

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#20275]
We would like the parameter IsHandled added to the following event.

Codeunit 427 ICInboxOutboxMgt - procedure CreateSalesDocument - event OnCreateSalesDocumentOnAfterSalesHeaderFirstModify

Original:

```
OnCreateSalesDocumentOnAfterSalesHeaderFirstModify(SalesHeader);

[IntegrationEvent(false, false)]
local procedure OnCreateSalesDocumentOnAfterSalesHeaderFirstModify(var SalesHeader: Record "Sales Header")
begin
end;
```

Change:

```
IsHandled := false; // <-- ADDED
OnCreateSalesDocumentOnAfterSalesHeaderFirstModify(SalesHeader, IsHandled); // <-- ADDED
if not IsHandled then // <-- ADDED

    SalesHeader.Validate("Due Date", "Due Date");


[IntegrationEvent(false, false)]
local procedure OnCreateSalesDocumentOnAfterSalesHeaderFirstModify(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47021.
