### ISSUE TITLE
[Event Request] codeunit 5341 - OnBeforeGetSourceDestCodeOnAfterTransferRecordFields

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#20277]
20.4.44313.45921 - line 312 >>>>

    procedure OnAfterTransferRecordFields(SourceRecordRef: RecordRef; var DestinationRecordRef: RecordRef; var AdditionalFieldsWereModified: Boolean; DestinationIsInserted: Boolean)
    // >> Begin new code
    var
        IsHandled: Boolean;
    // << End new code
    begin
        // >> Begin new code
        IsHandled := false;
        OnBeforeGetSourceDestCodeOnAfterTransferRecordFields(SourceRecordRef, DestinationRecordRef, AdditionalFieldsWereModified, IsHandled);    <----- new Event
        If IsHandled then
            exit;
        // << End new code
        case GetSourceDestCode(SourceRecordRef, DestinationRecordRef) of
            'CRM Account-Customer':
                if UpdateCustomerBlocked(SourceRecordRef, DestinationRecordRef) then

    ....

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetSourceDestCodeOnAfterTransferRecordFields(SourceRecordRef: RecordRef; DestinationRecordRef: RecordRef; var AdditionalFieldsWereModified: Boolean; var IsHandled: Boolean)
    begin
    end;

why? this is desperately needed to stop unwanted CRMProduct updates relating to UOM and Pricing in cases where the CRM Instance was created first and Products were transacted upon, then BC instance came along later.

**Comment by grantbrimhall** [comment]
Hi: We have a client who cannot sync ITEM-PRODUCT without this event. Is this something you can fast track? :) (TrackingID#2208100010003430)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47981.
