### ISSUE TITLE
CHECK - [Event Request] Codeunit 1222 "SEPA CT-Prepare Source" - Function InsertTempGenJnlLine - New Event OnBeforeInsertTempGenJnlLine

### ISSUE THREAD

**Issue by FabioC34** [microsoft/ALAppExtensions#20289]
Ref. #18009
Hi, regarding this issue I saw that it's not implemented yet (I just checked last minor release 20.5).
Will be implemented in next Major Release or next Minor?

Thank you
Fabio

**Comment by Vadim-Stepanenko** [comment]
It didn't make it to 20.5 but it does exist in 21.0 and all the versions going forward
