### ISSUE TITLE
[Event Parameter Change] report 1002 "Post Inventory Cost to G/L" - trigger OnPreReport  - event OnBeforePreReport

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#20286]
We would like the parameter Post added to the following event.

report 1002 "Post Inventory Cost to G/L" - trigger OnPreReport -  Event OnBeforePreReport

Original:

```
OnBeforePreReport(Item, ItemValueEntry, PostValueEntryToGL);

    [IntegrationEvent(true, false)]
    local procedure OnBeforePreReport(var Item: Record Item; var ItemValueEntry: Record "Value Entry"; var PostValueEntryToGL: Record "Post Value Entry to G/L")
    begin
    end;
```	

Change:

```	
OnBeforePreReport(Item, ItemValueEntry, PostValueEntryToGL, Post);

    [IntegrationEvent(true, false)]
    local procedure OnBeforePreReport(var Item: Record Item; var ItemValueEntry: Record "Value Entry"; var PostValueEntryToGL: Record "Post Value Entry to G/L"; Post: Boolean) // <-- ADDED
    begin
    end;	
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47704.
