### ISSUE TITLE
[Event Parameter Request] Codeunit 17 Gen. Jnl.-Post Reverse - procedure ReverseBankAccLedgEntry

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#20297]
Dear ALAppExtensions Team,

We would like to request the following change

    local procedure ReverseBankAccLedgEntry(BankAccLedgEntry: Record "Bank Account Ledger Entry"; NewEntryNo: Integer; SourceCode: Code[10])
    var
        NewBankAccLedgEntry: Record "Bank Account Ledger Entry";
        ReversedBankAccLedgEntry: Record "Bank Account Ledger Entry";
    begin
        with NewBankAccLedgEntry do begin
            NewBankAccLedgEntry := BankAccLedgEntry;
            Amount := -Amount;
            "Remaining Amount" := -"Remaining Amount";
            "Amount (LCY)" := -"Amount (LCY)";
            "Debit Amount" := -"Debit Amount";
            "Credit Amount" := -"Credit Amount";
            "Debit Amount (LCY)" := -"Debit Amount (LCY)";
            "Credit Amount (LCY)" := -"Credit Amount (LCY)";
            Positive := not Positive;
            "User ID" := UserId;
            "Entry No." := NewEntryNo;
            "Transaction No." := GenJnlPostLine.GetNextTransactionNo;
            "Journal Batch Name" := '';
            "Source Code" := SourceCode;
            SetReversalDescription(BankAccLedgEntry, Description);
            "Reversed Entry No." := BankAccLedgEntry."Entry No.";
            Reversed := true;
            // Reversal of Reversal
            if BankAccLedgEntry."Reversed Entry No." <> 0 then begin
                ReversedBankAccLedgEntry.Get(BankAccLedgEntry."Reversed Entry No.");
                ReversedBankAccLedgEntry."Reversed by Entry No." := 0;
                ReversedBankAccLedgEntry.Reversed := false;
                ReversedBankAccLedgEntry.Modify();
                BankAccLedgEntry."Reversed Entry No." := "Entry No.";
                "Reversed by Entry No." := BankAccLedgEntry."Entry No.";
            end;
            BankAccLedgEntry."Reversed by Entry No." := "Entry No.";
            BankAccLedgEntry.Reversed := true;
            BankAccLedgEntry.Modify();
            **//--> change request GenJnlPostLine parameter
            //OnReverseBankAccLedgEntryOnBeforeInsert(NewBankAccLedgEntry, BankAccLedgEntry);
            OnReverseBankAccLedgEntryOnBeforeInsert(NewBankAccLedgEntry, BankAccLedgEntry, GenJnlPostLine);
            //<-- change request**
            Insert;
        end;
    end;

    **//--> change request GenJnlPostLine parameter
    [IntegrationEvent(false, false)]
    local procedure OnReverseBankAccLedgEntryOnBeforeInsert(var NewBankAccLedgEntry: Record "Bank Account Ledger Entry"; BankAccLedgEntry: Record "Bank Account Ledger Entry"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line")
    begin
    end;
    //<-- change request**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47517.
