### ISSUE TITLE
[Event Request] table table 5406 "Prod. Order Line" - OnValidateQuantityOnAfterCalcBaseQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#20295]
My company is getting a bit anxious because it is taking longer than expected to get all the requested events in the BaseApp:
This request is from a year ago and has not made it (Original request #14516) to at least 20.05

We would like to add a new event OnValidateQuantityOnAfterCalcBaseQty in the following trigger:

    field(40; Quantity; Decimal)
    {
        Caption = 'Quantity';
        DecimalPlaces = 0 : 5;
        MinValue = 0;

        trigger OnValidate()
        var
            IsHandled: Boolean;
        begin
            IsHandled := false;
            OnBeforeValidateQuantity(Rec, xRec, CurrFieldNo, IsHandled);
            if IsHandled then
                exit;

            "Quantity (Base)" := Quantity * "Qty. per Unit of Measure";

            OnValidateQuantityOnAfterCalcBaseQty(Rec, xRec); //A200F0000.Event18.03

            "Remaining Quantity" := Quantity - "Finished Quantity";
            if "Remaining Quantity" < 0 then
                "Remaining Quantity" := 0;
            "Remaining Qty. (Base)" := "Remaining Quantity" * "Qty. per Unit of Measure";
            ProdOrderLineReserve.VerifyQuantity(Rec, xRec);
            WhseValidateSourceLine.ProdOrderLineVerifyChange(Rec, xRec);

            UpdateProdOrderComp(xRec."Qty. per Unit of Measure");

            if CurrFieldNo <> 0 then
                Validate("Ending Time");
            "Cost Amount" := Round(Quantity * "Unit Cost");
        end;
    }
Event Signature:

[IntegrationEvent(false, false)]
local procedure OnValidateQuantityOnAfterCalcBaseQty(var ProdOrderLine: Record "Prod. Order Line"; xProdOrderLine: Record "Prod. Order Line")
begin
    //A200F0000.Event18.03
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47191.

**Comment by Duizy1971** [comment]
Hi Jesper and Co.,

As with issue https://github.com/microsoft/ALAppExtensions/issues/13350
I did not quite get what I requested with

    local procedure CalcBaseQty(Qty: Decimal; FromFieldName: Text; ToFieldName: Text) Result: Decimal
    begin
        Result := UOMMgt.CalcBaseQty("Item No.", "Variant Code", "Unit of Measure Code", Qty, "Qty. per Unit of Measure", "Qty. Rounding Precision (Base)", FieldCaption("Qty. Rounding Precision"), FromFieldName, ToFieldName);
        OnAfterCalcBaseQty(Rec, xRec, Result);
    end;

local procedure OnAfterCalcBaseQty(var ProdOrderLine: Record "Prod. Order Line"; var xProdOrderLine: Record "Prod. Order Line"; var Result: Decimal)

Allas as mentioned in issue 13350 it has a different signature (OnAfter instead of OnBefore event) while it should be quite the same.
I'm missing the FromFieldName and ToFieldName parameters (which should actually not be 'Name' but 'Caption'.

**Comment by JesperSchulz** [comment]
We usually don't follow up on closed issues. If further changes are required, please create a new issue going forward.
@AlexanderYakunin, could you look into this case?
