### ISSUE TITLE
[Event Request] codeunit 5058 "BankCont-Update" - OnInsertNewContactOnBeforeAssignNo

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#20296]
We would like to add a new event OnInsertNewContactOnBeforeAssignNo in the following trigger. 
I have requested this a year ago #14463 and did receive the event in its customer and vendor counter parts 
codeunit 5056 "CustCont-Update"
codeunit 5057 "VendCont-Update"
but still not in codeunit 5058 "BankCont-Update".

    local procedure InitContactFromBankAccount(var Contact: Record Contact; BankAcc: Record "Bank Account")
        ...
            Validate("E-Mail");
            //A108F0049.Event18.03.ns
            IsHandled := false;
            OnInsertNewContactOnBeforeAssignNo(Contact, BankAcc, RMSetup, IsHandled);
            if not IsHandled then begin
                //A108F0049.Event18.03.ne
                "No." := '';
                "No. Series" := '';
                RMSetup.TestField("Contact Nos.");
                NoSeriesMgt.InitSeries(RMSetup."Contact Nos.", '', 0D, "No.", "No. Series");
            end; //A108F0049.Event18.03
            Type := Type::Company;

[IntegrationEvent(false, false)]
local procedure OnInsertNewContactOnBeforeAssignNo(var Contact: Record Contact; BankAccount: Record "Bank Account"; MarketingSetup: Record "Marketing Setup"; var IsHandled: Boolean)
begin
    //A108F0049.Event18.03
end;

**Comment by Vadim-Stepanenko** [comment]
It was implemented as **OnBeforeInitContactFromBankAccount** for **InitContactFromBankAccount**, why can't you use that?

**Comment by Duizy1971** [comment]
As I said in the Customer and Vendor codeunits it is implemented as
OnBeforeInsertNewContact
AND as well as
OnInsertNewContactOnBeforeAssignNo

Suddenly its counterpart Bank does it differently with only an OnBeforeInitContactFromBankAccount event.

It would be nice if it behaves and feels the same in all three quite similar functions and codeunits.
