### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" procedure CreateDim()

### ISSUE THREAD

**Issue by SvenSakulowski** [microsoft/ALAppExtensions#20309]
To enable partners to effectively implement a variation of the "Purchase Line".CreateDim procedure, please add "DefaultDimSource" as a parameter to the "OnBeforeCreateDim" event or add a new extensibility event that allows for creation of dimensions based on DefaultDimSource.

Suggested modified Event Definition:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateDim(var PurchaseLine: Record "Purchase Line"; DefaultDimSource: List of [Dictionary of [Integer, Code[20]]]; var IsHandled: Boolean; CurrentFieldNo: Integer)  //added DefaultDimSource
    begin
    end;

Suggested modified Code:

	procedure CreateDim(DefaultDimSource: List of [Dictionary of [Integer, Code[20]]])
    var
        SourceCodeSetup: Record "Source Code Setup";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCreateDim(Rec, DefaultDimSource, IsHandled, CurrFieldNo); //added DefaultDimSource
        if IsHandled then
            exit;
    [...]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49874.
