### ISSUE TITLE
[Extensibility Bug] "ReadSoft OCR Master Data Sync" encoding

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#20304]
Hello,

We use a business central online tenant in Ireland country and we have vendors with cyrillic names. The name of such vendors is passed to the service with an encoding error. Let's use UTF-8 encoding when creating a request body.

Thank you!

**Comment by AlexanderYakunin** [comment]
Hello, we cannot help you based on the story. You should report such issues using support channel and provide more details about your scenario and repro steps. Our team is focused on extensibility requests and cannot investigate this cases.
