### ISSUE TITLE
[Event Request] Codeunit 1104 "Cost Account Allocation"

### ISSUE THREAD

**Issue by Daniamstutz** [microsoft/ALAppExtensions#20312]
Codeunit 1104 "Cost Account Allocation"
    local procedure OnBeforeCalcLineShare(CostAllocationTarget: Record "Cost Allocation Target"; var IsHandled: Boolean)

Should be
    local procedure OnBeforeCalcLineShare(**var** CostAllocationTarget: Record "Cost Allocation Target"; var IsHandled: Boolean)

We would like to calculate the Share field outside of the default.
Therefore we needed the record CostAllocationTarget as reference otherwise we get the error message:
The changes to the Cost Allocation Target record cannot be saved because some information on the page is not up-to-date. Close the page, reopen it, and try again.

**Comment by matthias-planzer** [comment]
Done #20444

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47832.
