### ISSUE TITLE
[Event-Change Request] Table 38 - Purchase Header - OnBeforeValidatePromisedReceiptDate

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20316]
Dear ALAppExtensions team,

through this issue we would like to request a change of event publisher `OnBeforeValidatePromisedReceiptDate` in Table 38 Purchase Header from:
```AL
local procedure OnBeforeValidatePromisedReceiptDate(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader: Record "Purchase Header";  var IsHandled: Boolean)
begin
end;
```
to: 
```AL
local procedure OnBeforeValidatePromisedReceiptDate(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader: Record "Purchase Header"; CurrFieldNo: Integer; var IsHandled: Boolean)
begin
end;
```
adding the CurrFieldNo as a parameter to the event publisher.

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47054.
