### ISSUE TITLE
Can not find Event Request #17043 in BC 20.5

### ISSUE THREAD

**Issue by NadiaMelnyk** [microsoft/ALAppExtensions#20313]
Hello, could you please clarify when Event Request Page 232 "Apply Customer Entries" OnQueryClosePageOnEarlierPostingDateError  https://github.com/microsoft/ALAppExtensions/issues/17043 will be added to the BC? Thank you in advance.

**Comment by Vadim-Stepanenko** [comment]
It has been implemented as adding **OK** to **OnBeforeEarlierPostingDateError**, use that event.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
