### ISSUE TITLE
[Event Request] Table 38 - Purchase Header - OnBeforeValidatePaymentDiscountPercent

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20326]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnBeforeValidatePaymentDiscountPercent` in Table 38 Purchase Header with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeValidatePaymentDiscountPercent(var PurchaseHeader: Record "Purchase Header"; CurrFieldNo: Integer; var IsHandled: Boolean)
begin
end;
```
which would be called as follows in the OnValidate trigger of field `25 - Payment Discount %`:
```AL
trigger OnValidate()
// >>>> New >>>>>>>>>>>>>>>>
var
    IsHandled: Boolean;
// <<<< New <<<<<<<<<<<<<<<<
begin
    // >>>> New >>>>>>>>>>>>>>>>
    IsHandled := false;
    OnBeforeValidatePaymentDiscountPercent(Rec, CurrFieldNo, IsHandled);
    if IsHandled then
        exit;
    // <<<< New <<<<<<<<<<<<<<<<
    if not (CurrFieldNo in [0, FieldNo("Posting Date"), FieldNo("Document Date")]) then
        TestStatusOpen();
    GLSetup.Get();
    if "Payment Discount %" < GLSetup."VAT Tolerance %" then
        "VAT Base Discount %" := "Payment Discount %"
    else
        "VAT Base Discount %" := GLSetup."VAT Tolerance %";
    Validate("VAT Base Discount %");
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47054.
