### ISSUE TITLE
[Event Request] Table 5076 "Segment Header" 

### ISSUE THREAD

**Issue by SvenSakulowski** [microsoft/ALAppExtensions#20329]
For extensibility reasons, please add an event OnBeforeSaveCriteria in Table 5076 "Segment Header".

Suggested Event Definition:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSaveCriteria(var SegmentHeader: Record "Segment Header"; var IsHandled: Boolean)
    begin
    end;

Suggested Code:

	procedure SaveCriteria()
    var
        [...]
        IsHandled: Boolean; //added variable
    begin
        //added event code start
        IsHandled := false;
        OnBeforeSaveCriteria(Rec, IsHandled);
        if IsHandled then
            exit;
        //added event code stop
        
        [...]
        
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47148.
