### ISSUE TITLE
Set permission group to a specific user with PowerShell

### ISSUE THREAD

**Issue by michuanni** [microsoft/ALAppExtensions#20327]
Hi,

we are looking for a possibility to set the permission groups to a specific user through PowerShell. 

This is a goog way to handle permissions but it is not possible to do it through PowerShell.

Can you create a cmdlet to handle this?

**Comment by AlexanderYakunin** [comment]
@JesperSchulz - please review this request

**Comment by JesperSchulz** [comment]
Thanks for sharing your idea with us. We're always looking for better ways to do things. However, this isn't the right place to share it. You'll have better luck getting it implemented and noticed by other partners if you post it to the following resources:

- For functional improvements, go to [Business Central - Ideas](http://aka.ms/bcideas)
- For feature suggestions for the AL compiler and developer tools, visit [Github.com/Microsoft/AL](https://github.com/Microsoft/AL/issues)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
