### ISSUE TITLE
Guided Experience Item entry still exist after unpublishing our app

### ISSUE THREAD

**Issue by HegedusZsolt** [microsoft/ALAppExtensions#20322]
We have an assisted setup page, which is works fine, but when we have uninstall and unpublish our app, a guided experience item is still exist.

Should I remove this entry somehow? How can I do this? Is there an event for this somewhere?

It's a bit annoying, because when we have reinstall our app, the assisted setup seems to be completed.

**Comment by HegedusZsolt** [comment]
There is no best practice to remove this entry or I'm asking on a wrong place?

**Comment by HegedusZsolt** [comment]
As I see, there is no option to subscribe on uninstalling apps. Please vote on this if you also need this option. 

https://experience.dynamics.com/ideas/idea/?ideaid=2ee9e0ed-6cc5-e911-b083-0003ff68ac6b

**Comment by sorenfriisalexandersen** [comment]
Hi @HegedusZsolt 
As you say, there is no OnUninstall trigger where you could place such code.
Your only option for now is to handle potentially existing Guided Experience Items at install, removing the old ones before adding new.

Thanks.
