### ISSUE TITLE
[Event Parameter Change] Table 5777 Item Reference - procedur CreateItemVendor - Event OnBeforeCreateItemVendor

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#20320]
We would like the parameter ItemVendor with var added to the following event.

Table 5777 Item Reference - procedur CreateItemVendor - Event OnBeforeCreateItemVendor

Original:

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeCreateItemVendor(var ItemReference: Record "Item Reference"; ItemVendor: Record "Item Vendor")
    begin
    end;
```

Change: Added var Parameter ItemVendor

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeCreateItemVendor(var ItemReference: Record "Item Reference"; var ItemVendor: Record "Item Vendor")
    begin
    end;		
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47651.
