### ISSUE TITLE
[Event Change Request] Codeunit 90 "Purch.-Post" OnPostItemChargeLineOnAfterPostItemCharge

### ISSUE THREAD

**Issue by SteveKrisjanovsD365** [microsoft/ALAppExtensions#20336]
Please change the IncludeSender integration event attribute in this event from false to true. There are codeunit procedures we need to fire off from this event subscriber but cannot because the sender codeunit is inaccessible.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47651.
