### ISSUE TITLE
[Extensibility Request] emun 362 "Analysis Period Type" reuqest to make extensible

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#20335]
We would like to request making this enum Extensible = true; so that we can add our own custom elements to it to support our processing of an Accounting Year type.  Thank you.

**Comment by AlexanderYakunin** [comment]
Hello! This enum is extensible:

enum 362 "Analysis Period Type"
{
    Extensible = true;
    AssignmentCompatibility = true;

    value(0; "Day") { Caption = 'Day'; }
    value(1; "Week") { Caption = 'Week'; }
    value(2; "Month") { Caption = 'Month'; }
    value(3; "Quarter") { Caption = 'Quarter'; }
    value(4; "Year") { Caption = 'Year'; }
    value(5; "Accounting Period") { Caption = 'Accounting Period'; }
}
