### ISSUE TITLE
Get draft email subject on change

### ISSUE THREAD

**Issue by cb2bc** [microsoft/ALAppExtensions#20338]
we would need to be able to get draft email subject after a user updates it.

https://github.com/microsoft/ALAppExtensions/blob/main/Modules/System/Email/src/Email/Outbox/EmailOutbox.Table.al

usecase:

User runs a function in bc 20 on prem and is presented a pre populated email draft, with a pre populated subject & then closes draft. 

![image](https://user-images.githubusercontent.com/113637576/190594230-4e9c8862-ff2c-4a29-99de-e6fccc35b2b6.png)

In the background we store a link to this email draft in a link table which links (1 to 1) to this email message via message id, with as filename the pre populated email subject.( link table also contains other links to fe pdf & word)

From this link table user can then navigate again to the draft email, change the subject & close it again.

Because we cannot get the updated subject by the user(marked  as internal in bc), we cannot update the filename in the link record and, as a result, the user now cannot find his draft email back in our link table

pls make it possible to get the updated subject on the email draft so we can leverage this cool feature :)

**Comment by AlexanderYakunin** [comment]
@JesperSchulz - please review this request

**Comment by stkillen** [comment]
If you have the email message id, you should be able to use codeunit 8904 "Email Message" to get the subject.

```
EmailMessage.Get(MessageId);
Subject := EmailMessage.GetSubject();
```

If this does somehow not work for your scenario, please explain why.

**Comment by stkillen** [comment]
@cb2bc does the above recommendation solve your issue?

**Comment by cb2bc** [comment]
@stkillen yes it did, tks 👍

**Comment by stkillen** [comment]
Perfect, closing this issue.
