### ISSUE TITLE
[Event change Request] Codeunit 248 "Vat Lookup Ext. Data Handl" OnRunOnAfterLookupVatRegistrationFromWebService

### ISSUE THREAD

**Issue by CarstenHeu** [microsoft/ALAppExtensions#20331]
Hello,

we would like to have the first parameter set as per reference in the event trigger OnRunOnAfterLookupVatRegistrationFromWebService in the codeunit "Vat Lookup Ext. Data Handl".
This would be the only way to change values in the Vat Registration Log record, because after the event publisher call this VatRegistrationLog parameter overwrites the Rec variable that is already given by reference, so that changes on this 2nd. parameter will be overwritten!
![Eventpublisher-OnRunOnAfterLookupVatRegistrationFromWebService](https://user-images.githubusercontent.com/48825129/190397373-8c3a6efa-5b8b-4afd-a5cd-e23fd99ae8cc.png)
![Eventpublisher call](https://user-images.githubusercontent.com/48825129/190397389-a042cc39-8d5e-4f3f-9227-05f9ae69d3fd.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47702.
