### ISSUE TITLE
[Event extend request] OnApplyCustLedgerEntryOnBeforeSetCompleted

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#20333]
We would like to request to extend the event publisher OnApplyCustLedgerEntryOnBeforeSetCompleted with the variable AppliedAmount

   OnApplyCustLedgerEntryOnBeforeSetCompleted(GenJnlLine, OldCustLedgEntry, NewCVLedgEntryBuf, AppliedAmount);

    [IntegrationEvent(false, false)]
    local procedure OnApplyCustLedgerEntryOnBeforeSetCompleted(var GenJournalLine: Record "Gen. Journal Line"; var OldCustLedgEntry: Record "Cust. Ledger Entry"; var NewCVLedgerEntryBuffer: Record "CV Ledger Entry Buffer"; **AppliedAmount**: **Decimal**)
    begin
    end;

**Comment by Vadim-Stepanenko** [comment]
Which object is this?

**Comment by Vadim-Stepanenko** [comment]
Please don't forget to tell us all relevant info so we can provide events. If you still need this, open a new issue with the object number + name included.
