### ISSUE TITLE
Internal Attribute on procedures in Codeunit 109 Lookup State Manager

### ISSUE THREAD

**Issue by LubomirUrx** [microsoft/ALAppExtensions#20332]
I follow up on the request #19204. Could you remove scope attribute Internal from all procedures in Codeunit 109 Lookup State Manager?
Thank you
Lubomír Urx

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47754.
