### ISSUE TITLE
Adding permissions to multiple objects

### ISSUE THREAD

**Issue by DonHendriksen** [microsoft/ALAppExtensions#20341]
Hi,
Hereafter an overview of objects for which we request to assign additional permissions. We created only one request, instead of splitting them in for instance function area, as we discussed it with Alexander Yakunin.

codeunit 5330 "CRM Integration Management"
- tabledata "CDS Connection Setup" = R
- tabledata "CRM Connection Setup" = R

table 5330 "CRM Connection Setup"
- tabledata "CRM Connection Setup" = R

codeunit 396 NoSeriesManagement
- tabledata "No. Series" = R
- tabledata "No. Series Line" = RM

codeunit 5508 "Graph Mgt - Sal. Cr. Memo Buf."
- tabledata "Sales Cr. Memo Entity Buffer" = R

codeunit 5477 "Sales Invoice Aggregator"
- tabledata "Sales Invoice Entity Aggregate" = R

codeunit 7600 "Calendar Management"
- tabledata "Base Calendar Change" = R

table 5077 "Segment Line"
- tabledata Contact = R
- tabledata Customer = R

codeunit 5051 SegManagement
- tabledata "Interaction Template" = R

table 5050 Contact
- tabledata "Contact Alt. Addr. Date Range" = R
- tabledata Contact = RM
- tabledata "Marketing Setup" = R
- tabledata "Salutation Formula" = R

codeunit 5055 "CustVendBank-Update"
- tabledata "Contact Business Relation" = R

table 250 "Gen. Business Posting Group"
- tabledata "Gen. Business Posting Group" = R

table 4 Currency
- tabledata "General Ledger Setup" = R

table 18 Customer
- tabledata "General Ledger Setup" = R
- tabledata "Marketing Setup" = R
- tabledata "Sales & Receivables Setup" = R

codeunit 347 "Amount Auto Format"
- tabledata "General Ledger Setup" = R

codeunit 5060 DuplicateManagement
- tabledata "Marketing Setup" = R

table 11406 "Post Code Range"
- tabledata "Post Code Range" = R

codeunit 1501 "Workflow Management"
- tabledata "Workflow Event" = R
- tabledata "Workflow Step Argument" = R
- tabledata "Workflow - Table Relation" = R
- tabledata "Workflow Event Queue" = R

table 1502 "Workflow Step"
- tabledata "Workflow Step" = R

table 1504 "Workflow Step Instance"
- tabledata Workflow = R
- tabledata "Workflow Event" = R

table 1506 "Workflow Table Relation Value" 
- tabledata "Workflow Table Relation Value" = RI

codeunit 1521 "Workflow Response Handling"
- tabledata "Workflow Response" = R

codeunit 365 "Format Address"
- tabledata "Country/Region" = R

Thanks in advance. Regards, Don

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47752.
