### ISSUE TITLE
[Event Parameter Change] Page 55 Purch. Invoice Subform - procedure UpdateEditableOnRow - event OnAfterUpdateEditableOnRow

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#20349]
We would like the parameter/-s InvDiscAmountEditable, CurrPageIsEditable, TotalPurchaseHeader added to the following event.

Page 55 Purch. Invoice Subform - procedure UpdateEditableOnRow - event OnAfterUpdateEditableOnRow

Original:

```
OnAfterUpdateEditableOnRow(Rec, IsCommentLine, IsBlankNumber);

[IntegrationEvent(false, false)]
local procedure OnAfterUpdateEditableOnRow(PurchaseLine: Record "Purchase Line"; var IsCommentLine: Boolean; var IsBlankNumber: Boolean);
begin
end;
```

Change:

```
OnAfterUpdateEditableOnRow(Rec, IsCommentLine, IsBlankNumber, InvDiscAmountEditable, CurrPageIsEditable, TotalPurchaseHeader); // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnAfterUpdateEditableOnRow(PurchaseLine: Record "Purchase Line"; var IsCommentLine: Boolean; var IsBlankNumber: Boolean; var InvDiscAmountEditable: Boolean; CurrPageIsEditable: Boolean; TotalPurchaseHeader: Record "Purchase Header"); // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47656.
