### ISSUE TITLE
[Event Parameter Change] Report 393 - "Suggest Vendor Payments" - Procedure "MakeGenJnlLines" - Event OnMakeGenJnlLinesOnBeforeTempPaymentBufferInsert

### ISSUE THREAD

**Issue by IHHNASmart** [microsoft/ALAppExtensions#20357]
Dear ALAppExtensions team,
we would like the parameter `PayableVendLedgEntry` added to the following event.

Report 393 - "Suggest Vendor Payments" - Procedure "MakeGenJnlLines" - Event OnMakeGenJnlLinesOnBeforeTempPaymentBufferInsert

Original:
> [IntegrationEvent(false, false)]
    local procedure OnMakeGenJnlLinesOnBeforeTempPaymentBufferInsert(var TempPaymentBuffer: Record "Payment Buffer" temporary; VendorLederEntry: Record "Vendor Ledger Entry")
    begin
    end;

Change: Added Parameter `PayableVendLedgEntry`
> [IntegrationEvent(false, false)]
    local procedure OnMakeGenJnlLinesOnBeforeTempPaymentBufferInsert(var TempPaymentBuffer: Record "Payment Buffer" temporary; VendorLederEntry: Record "Vendor Ledger Entry"; PayableVendLedgEntry : TEMPORARY Record "Payable Vendor Ledger Entry")
    begin
    end;

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47656.
