### ISSUE TITLE
[Event Request] Report 393 - "Suggest Vendor Payments" - OnBeforeClearNegative

### ISSUE THREAD

**Issue by IHHNASmart** [microsoft/ALAppExtensions#20355]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher OnBeforeClearNegative in report 393 - "Suggest Vendor Payments" with the following signature:

>[IntegrationEvent(false, false)]
>local procedure OnBeforeClearNegative(var PayableVendLedgEntry : Record "Payable Vendor Ledger Entry"; var AmountAvailable : Decimal; Vendor : Record Vendor; var IsHandled : Boolean)`

which could be used in the function ClearNegative()

> local procedure ClearNegative()
    var
        TempCurrency: Record Currency temporary;
        PayableVendLedgEntry2: Record "Payable Vendor Ledger Entry" temporary;
        CurrencyBalance: Decimal;
		// >>>> New >>>>>>>>>>>>>>>>
		IsHandled: Boolean;
		// <<<< New <<<<<<<<<<<<<<<<
    begin
         // >>>> New >>>>>>>>>>>>>>>>
		IsHandled := false;
		OnBeforeClearNegative(PayableVendLedgEntry, AmountAvailable, Vendor, IsHandled);
		if IsHandled then
			exit;
		// <<<< New <<<<<<<<<<<<<<<<
		Clear(PayableVendLedgEntry);
        PayableVendLedgEntry.SetRange("Vendor No.", Vendor."No.");
        ...
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48444.
