### ISSUE TITLE
[Event Request] Report 393 - "Suggest Vendor Payments" - OnAfterSaveAmoun 

### ISSUE THREAD

**Issue by IHHNASmart** [microsoft/ALAppExtensions#20356]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnAfterSaveAmoun` in report 393 - "Suggest Vendor Payments" with the following signature:
`[IntegrationEvent(false, false)]`
`OnAfterSaveAmoun(var GenJnlLine : Record "Gen. Journal Line"; var PayableVendLedgEntry : TEMPORARY Record "Payable Vendor Ledger Entry"; VendLedgEntry : Record "Vendor Ledger Entry";)`

which could be used in the function `SaveAmount()`
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48444.
