### ISSUE TITLE
Make SendPrintJob() externally accessible

### ISSUE THREAD

**Issue by bctstkla** [microsoft/ALAppExtensions#20379]
Hi,

why was the already accepted single-word-modification/PR #17952 (merged by @darjoo ) reverted in commit 44afd41 (20.4) ?

Our customers would really really have needed this and we've been waiting since May!

**Comment by darjoo** [comment]
Hi @bctstkla,
I just looked into this and it looks like it wasn't ported from major v21 (our master at that time) the minor of v20. The team that owns this feature only put it into the major and not minors. So, no it has not just disappeared.
It does look like it was reverted but that's only on GitHub at this moment as we take what we have for the version (20.4) and update this repo.

**Comment by bctstkla** [comment]
Thanks @darjoo , looking forward for this. :)
