### ISSUE TITLE
[Request for External] procedure Suffix in table 477 - "Report Inbox"

### ISSUE THREAD

**Issue by MMueller1974** [microsoft/ALAppExtensions#20374]
Dear ALAppExtensions team,

can you please remove local prefix from procedure Suffix in table 477 "Report Inbox"?
This issue is related to issue #20373.
Old signature
```AL
local procedure Suffix(): Text
```
New signature
```AL
procedure Suffix(): Text
```
Thank you in advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47754.
