### ISSUE TITLE
Event Request codeunit 7322 "Create Inventory Pick/Movement" - OnBeforeFindJobPlanningLines

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#20372]
Please can we have the following event in codeunit 7322 "Create Inventory Pick/Movement":

    local procedure SetFilterJobPlanningLine(var JobPlanningLine: Record "Job Planning Line"; Job: Record Job): Boolean
    begin
        JobPlanningLine.SetLoadFields(
            "Job No.",
            "Job Contract Entry No.",
            "Line No.",
            "Document No.",
            "Location Code",
            "Bin Code",
            "No.",
            "Variant Code",
            "Unit of Measure Code",
            "Qty. per Unit of Measure",
            "Qty. Rounding Precision",
            "Qty. Rounding Precision (Base)",
            Description,
            "Planning Due Date",
            "Job Task No.",
            "Reserved Quantity",
            "Remaining Qty. (Base)",
            "Reserved Quantity"
        );
        JobPlanningLine.SetRange("Job No.", Job."No.");
        JobPlanningLine.SetRange(Type, JobPlanningLine.Type::Item);

        if not CheckLineExist then
            JobPlanningLine.SetRange("Location Code", WhseActivHeader."Location Code");
        if IsInvtMovement then
            JobPlanningLine.SetFilter("Bin Code", '<>%1', '');
        JobPlanningLine.SetFilter("Remaining Qty.", '>0');
        OnBeforeFindJobPlanningLines(JobPlanningLine,Job,WhseActivHeader);
        exit(JobPlanningLine.Find('-'));
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindJobPlanningLines(var JobPlanningLine: Record "Job Planning Line";Job: Record Job;WarehouseActivityHeader: Record "Warehouse Activity Header")
    begin
    end;

**Comment by JeremyOrgan-DC** [comment]
Hi, will this event ship in the future?

**Comment by Vadim-Stepanenko** [comment]
It will most likely be in the nearest minor

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48444.
