### ISSUE TITLE
Event Request codeunit 980 "Payment Registration Mgt." - OnAfterFindRecords

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#20378]
Please can you add the following eventin codeunit 980 "Payment Registration Mgt.":

[IntegrationEvent(false, false)]
local procedure OnAfterFindRecords(var TempDocumentSearchResult: Record "Document Search Result" temporary; DocNoFilter: Code[20]; AmountFilter: Decimal; AmountTolerancePerc: Decimal)

procedure FindRecords(var TempDocumentSearchResult: Record "Document Search Result" temporary; DocNoFilter: Code[20]; AmountFilter: Decimal; AmountTolerancePerc: Decimal)
begin
    if not TempDocumentSearchResult.IsTemporary then
        Error(TempTableErr);

    TempDocumentSearchResult.Reset();
    TempDocumentSearchResult.DeleteAll();
    DocNoFilter := StrSubstNo('*%1*', DocNoFilter);

    FindSalesHeaderRecords(TempDocumentSearchResult, DocNoFilter, AmountFilter, AmountTolerancePerc);
    FindServiceHeaderRecords(TempDocumentSearchResult, DocNoFilter, AmountFilter, AmountTolerancePerc);
    FindReminderHeaderRecords(TempDocumentSearchResult, DocNoFilter, AmountFilter, AmountTolerancePerc);
    FindFinChargeMemoHeaderRecords(TempDocumentSearchResult, DocNoFilter, AmountFilter, AmountTolerancePerc);

    OnAfterFindRecords(TempDocumentSearchResult, DocNoFilter, AmountFilter, AmountTolerancePerc);
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47704.
