### ISSUE TITLE
[Extensibility Enhancement] Expose InLine Parameter in Codeunit 8904 "Email Message" - AddAttachment()

### ISSUE THREAD

**Issue by papillon** [microsoft/ALAppExtensions#20370]
We need to be able to specify the Content-Disposition property of email attachments. I suppose the **InLine** Property does just that, but is not exposed.

So the proposal is to add this procedure in EmailMessage.Codeunit.al
```
procedure AddAttachment(AttachmentName: Text[250]; ContentType: Text[250]; InLine: Boolean; AttachmentInStream: InStream)
begin
    EmailMessageImpl.AddAttachment(AttachmentName, ContentType, InLine, AttachmentInStream);
end;
```
and the implementation in EmailMessageImpl.Codeunit.al like this:
```
procedure AddAttachment(AttachmentName: Text[250]; ContentType: Text[250]; InLine: Boolean; AttachmentInStream: InStream)
begin
    AddAttachmentInternal(AttachmentName, ContentType, InLine, AttachmentInStream);
end;

procedure AddAttachmentInternal(AttachmentName: Text[250]; ContentType: Text[250]; InLine: Boolean; AttachmentInStream: InStream) Size: Integer
var
    EmailMessageAttachment: Record "Email Message Attachment";
    NullGuid: Guid;
begin
    AddAttachment(AttachmentName, ContentType, InLine, NullGuid, EmailMessageAttachment);
    InsertAttachment(EmailMessageAttachment, AttachmentInStream, '');
    exit(EmailMessageAttachment.Length);
end;
```
(or refactor the implementation and avoid code duplication just because of the InLine Parameter).

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10591.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56284.
