### ISSUE TITLE
Key request for "SII Doc. Upload State" table (id 10752) (ES localization)

### ISSUE THREAD

**Issue by pjllaneras** [microsoft/ALAppExtensions#20385]
In some databases, we have seen some performance issues when opening and scrolling through posted documents list pages (sales/purchase invoices/credit memos). 

After analizing these pages, we found that the "SII Status" field was the problem. This is a FlowField, for example, in table 112 "Sales Invoice Header":

```
        field(10706; "SII Status"; Enum "SII Document Status")
        {
            CalcFormula = Lookup("SII Doc. Upload State".Status WHERE("Document Source" = CONST("Customer Ledger"),
                                                                       "Document Type" = CONST(Invoice),
                                                                       "Document No." = FIELD("No.")));
            Caption = 'SII Status';
            FieldClass = FlowField;
            ...
        }
```

The problem is that there is no key for the filtered fields in the "SII Doc. Upload State" table, and this causes a performance issue when these pages are opened, and when the user scrolls. The problem remains hidden unless the company has a lot of records in this table (in SaaS, with few hundreds thousands records).

The solution is to create a key in "SII Doc. Upload State" to cover the fields used in the flowfield. We recomend this key:

"Document No.", "Document Source", "Document Type"

The the order of last two fields are less important than the first one.

We have created this key in a table extension and the performance issue is gone, but this is a problem with the base code for ES localization. As a point of reference, in a customer (this table have almost 500 thousand records), before creating the key, the page "Posted Sales Invoices" takes almost a minute to open, after the creation of the new key, it opens instantly.

**Comment by AlexanderYakunin** [comment]
Thank you! We will fix it asap.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: <None>.
