### ISSUE TITLE
[Event Request] Codeunit 99000770 Where-Used Management - OnBeforeBuildWhereUsedList

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#20384]
Hello Team,

In Codeunit 99000770 we need possibility to have our additional checks and/or avoid using standard code. Having event in procedure WhereUsedFromItem would be a perfect solution:

![image](https://user-images.githubusercontent.com/70525691/191508953-f23f25c0-e348-48c8-b5c1-36eb3c5bb1d6.png)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeBuildWhereUsedList(var MultiLevel: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48086.
