### ISSUE TITLE
[Event Request page 5850 Posted Sales/Purchase Document Lines - OnFindRecordOnBeforeFind

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#20397]
When you use the action 'Get Posted Doc&ument Lines' on for instance the sales credit memo page, you are presented with the page page 5850 "Posted Sales Document Lines" which has four subpages pointing to the four historic sales document tables.
The problem I'm facing is that the record pointer is always set to the first record. For some of our customers that might be invoices or shipments from the year 2014 which makes no sense. They always have to scroll to the far end or use the keyboard shortcut <CTRL+END>. It would be nice to manipulate the OnFindRecord trigger in the following eight pages to get the pointer to the last record with a subscriber that does something like. You might even think this is something that would be a nice feature for the BaseApp itself so everybody in the world can benefit immediately from it.

    [EventSubscriber(ObjectType::Page, Page::"Get Post.Doc - S.InvLn Subform", 'OnFindRecordOnBeforeFind', '', false, false)]
    local procedure OnFindRecordOnBeforeFind(var SalesInvoiceLine: Record "Sales Invoice Line"; var Which: Text)
    begin
        if Which = '=><' then
            Which := '+';
    end;

"Get Post.Doc - S.InvLn Subform"
"Get Post.Doc - S.ShptLn Sbfrm"
"Get Post.Doc-S.Cr.MemoLn Sbfrm"
"Get Pst.Doc-RtrnRcptLn Subform"
"Get Post.Doc - P.InvLn Subform"
"Get Post.Doc - P.RcptLn Sbfrm"
"Get Post.Doc-P.Cr.MemoLn Sbfrm"
"Get Pst.Doc-RtrnShptLn Subform"

    trigger OnFindRecord(Which: Text): Boolean
    begin
        if not Visible then
            exit(false);

        OnFindRecordOnBeforeFind(Rec, Which);
        if Find(Which) then begin

    [IntegrationEvent(false, false)]
    local procedure OnFindRecordOnBeforeFind(var SalesInvoiceLine: Record "Sales Invoice Line"; var Which: Text)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49745.
