### ISSUE TITLE
[Exposure Request] codeunit 7002 "Price Calculation - V16" - IsImprovedLine

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#20390]
Please make function IsImprovedLine externally available.

```
procedure IsImprovedLine(PriceListLine: Record "Price List Line"; BestPriceListLine: Record "Price List Line") Result: Boolean
begin
    Result :=
        IsSetValue(PriceListLine."Currency Code", BestPriceListLine."Currency Code") or
        IsSetValue(PriceListLine."Variant Code", BestPriceListLine."Variant Code");

    OnAfterIsImprovedLine(PriceListLine, BestPriceListLine, Result);
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47754.
