### ISSUE TITLE
Include Sender = True for several Integration Events.

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#20405]
We are working on functionality expanding the scope of Item Charge in Business Central.
The core logic was developed for NAV and includes some additions to central posting functions. In NAV the additional logic would be implemented directly into the core code and thus be processed within the same instance of the object as the core code itself. This ensured that we would plug directly into all the existing state variables in that object, e.g. posting buffers and NextEntryNo.

In Business Central we must instead do the integration using the provided integration events. However, a major issue has proven to be that the majority of the integration events offered in BC are set up with the parameter Include Sender = False. 

This implies that we cannot interact with the actual instance of the object triggering the event. This is a big problem when the triggering object makes use of global state variables and buffer data, which the majority of the objects in do.

In order to integrate seamlessly into the current standard logic, we need at least the following integration events to be changed to Include Sender = True: 

Codeunit 90, "Purch.-Post" 
OnPostItemChargeLineOnAfterPostItemCharge
OnPostItemJnlLineOnAfterCopyItemCharge
OnPostPurchLineOnBeforePostByType

Codeunit 22, "Item Jnl.-Post Line"
OnBeforeInitValueEntry

Codeunit 12, "Gen. Jnl.-Post Line"
OnBeforeStartOrContinuePosting

Codeunit 5802, "Inventory Posting To G/L"
OnBeforeBufferOutputPosting

Codeunit 5896, "Calc. Inventory Adjmt. - Order"
OnCalcActualMaterialCostsOnAfterSetFilters

Page 5805, "Item Charge Assignment (Purch)"
OnAfterUpdateQty

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
