### ISSUE TITLE
[Bug / Missing Caption] Table 7001 - Price List Line

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#20404]
Can you please add a `Caption` property for below fields, so they can get translated?

```
table 7001 "Price List Line"
{
    fields
    {
        field(1; "Price List Code"; Code[20])
        {
            DataClassification = CustomerContent;
            TableRelation = "Price List Header";
        }
        field(2; "Line No."; Integer)
        {
            DataClassification = CustomerContent;
            AutoIncrement = true;
        }
```

Seems like there's a lot more fields in the table with no caption.
Can you please review the "Price List *" objects with missing captions?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51565.
