### ISSUE TITLE
RefreshOnActivate in "Assembly Order Subform" page (901)

### ISSUE THREAD

**Issue by TriangleSPV** [microsoft/ALAppExtensions#20409]
Some days ago I created the following issue to add the RefreshOnActivate in a list page:
https://github.com/microsoft/ALAppExtensions/issues/17516

Now we have a similar problem in the subform page. Do you think if it is possible to add this property in the new requested page?

**Comment by TriangleSPV** [comment]
A customer reported us a comment that the field "Avail. Warning" of the lines was not updated correctly after changing the quantity in the header. If they change the focus ftom the header to the lines, it is refreshed correctly, so we thought that it could be solved with the RefreshOnActivate property, but if you think that it is not the correct behaviour in subforms, cancel this issue.

**Comment by AlexanderYakunin** [comment]
We already have property UpdatePropagation for subform, which is responsible for update behavior

            part(Lines; "Assembly Order Subform")
            {
                ApplicationArea = Assembly;
                Caption = 'Lines';
                SubPageLink = "Document Type" = FIELD("Document Type"),
                              "Document No." = FIELD("No.");
                UpdatePropagation = Both;
            }
