### ISSUE TITLE
[Bug] Report 11510 "Swiss QR-Bill Print"

### ISSUE THREAD

**Issue by JPicard90** [microsoft/ALAppExtensions#20403]
we noticed that every time that we print the report (even in preview mode) a record in table Tenant media and tenant media thumbnail is stored with QR image of the invoice: 
![image](https://user-images.githubusercontent.com/20781085/191687896-bae35fd9-0eae-44b4-8646-9f910fc0614d.png)

after 2 years of continuos using our DB is Expanded by 20 GB just for those image.. 
could you please fix this issue?

i think that you should use Blob for store QRcode image instread of media type or use TempBlob directly in the report and empty the useless space occupied by the images of previous executions

thanks

**Comment by AleksanderGladkov** [comment]
@JPicard90 
The problem was fixed, the fix will get to the next minor release.
