### ISSUE TITLE
Additional parameter to event OnAfterProcessShiptoCodeChange in codeunit 5940 ServContractManagement

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [microsoft/ALAppExtensions#20400]
Would it be possible to have parameter NewShipToCode added to event publisher OnAfterProcessShiptoCodeChange?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47656.
