### ISSUE TITLE
[Event Request] Codeunit1002 "Job Create-Invoice, OnCreateSalesInvoiceLinesOnBeforeLoopJobPlanningLines

### ISSUE THREAD

**Issue by kristerwiklund** [microsoft/ALAppExtensions#20413]
We would like to request an event in codeunit 1002 "Job Create-Invoice, procedure CreateSalesInvoiceLines(). The event could be called OnCreateSalesInvoiceLinesOnBeforeLoopJobPlanningLines. We need it to be able to set the order of Job Planning Lines (SetCurrentKey).

        OnCreateSalesInvoiceLinesOnBeforeJobPlanningLineCopy(Job, JobPlanningLineSource, PostingDate);
        JobPlanningLine.Copy(JobPlanningLineSource);
        JobPlanningLine.SetCurrentKey("Job No.", "Job Task No.", "Line No.");

        OnCreateSalesInvoiceLinesOnBeforeLoopJobPlanningLines(JobPlanningLine);

        if JobPlanningLine.FindSet() then
            repeat
                if TransferLine(JobPlanningLine) then begin

   [IntegrationEvent(false, false)]
    local procedure OnCreateSalesInvoiceLinesOnBeforeLoopJobPlanningLines(var JobPlanningLine: Record "Job Planning Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48467.
