### ISSUE TITLE
[Event Request] Codeunit 5407 function TransProdOrderLine

### ISSUE THREAD

**Issue by agnieszkaszuflak** [microsoft/ALAppExtensions#20419]
Hi AL-Team,
Due to customer customization, we need new publisher in CU 5407 (Prod. Order Status Management).

Function: TransProdOrderLine

Current code:

![image](https://user-images.githubusercontent.com/57363333/191925191-2b52d17d-7eb2-4037-90a7-d8b51edd3f5c.png)

Requested code:
From Line 213
                        end else begin
                            if Item.Get("Item No.") then begin
                                if (Item."Costing Method" <> Item."Costing Method"::Standard) and NewUpdateUnitCost then
                                    UpdateProdOrderCost.UpdateUnitCostOnProdOrder(FromProdOrderLine, false, true);
                            end;
                            ToProdOrderLine.BlockDynamicTracking(true);
                            ToProdOrderLine.Validate(Quantity);
                             OnBeforeTransferPOLineToPoLine(FromProdOrderLine, ToProdOrderLine, NewStatus);
                            ProdOrderLineReserve.TransferPOLineToPOLine(FromProdOrderLine, ToProdOrderLine, 0, true);
                        end;
                        ToProdOrderLine.Validate("Unit Cost", "Unit Cost");

Requested Publisher signature:
 [IntegrationEvent(false, false)] local procedure OnBeforeTransferPOLineToPoLine(FromProdOrderLine: Record "Prod. Order Line"; var ToProdOrderLine: Record "Prod. Order Line"; NewStatus: Enum "Production Order Status")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48467.
