### ISSUE TITLE
[Event Request] Table 39 - Purchase Line - OnBeforeValidateJobLineType

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20418]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnBeforeValidateJobLineType` in Table 39 Purchase Line with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeValidateJobLineType(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
begin
end;
```
which would be called as follows in the OnValidate trigger of field `1002- Job Line Type`:
```AL
trigger OnValidate()
// >>>> New >>>>>>>>>>>>>>>>
var
    IsHandled: Boolean;
// <<<< New <<<<<<<<<<<<<<<<
begin
    // >>>> New >>>>>>>>>>>>>>>>
    OnBeforeValidateJobLineType(Rec, IsHandled);
    if IsHandled then
        exit;
    // <<<< New <<<<<<<<<<<<<<<<

    TestField("Receipt No.", '');
    if "Document Type" = "Document Type"::Order then
        TestField("Quantity Received", 0);
    if "Job Planning Line No." <> 0 then
        Error(Text048, FieldCaption("Job Line Type"), FieldCaption("Job Planning Line No."));
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47054.
