### ISSUE TITLE
CRM synchronisation for customers with config template is broken

### ISSUE THREAD

**Issue by JohnFrostDP** [microsoft/ALAppExtensions#20410]
Dear Microsoft,

In version 20.5 there is a bug within the CRM integration sync. Or at least in one of the events that are being called within the BC code. It is now impossible to sync Customers with a standard integration mapping setup. It is also not possible to manually fill the customer number with a value from crm. The main reason for this is that when you use a Config. template header (table 8618) in your integration mapping, the field "Instance No. Series" (field 8) becomes mandatory. Not only that, the no series can not be set by hand as there is no field for it to fill it. I did find a code that does it, but that is beside my point. 

I know where it goes wrong and i think you should fix this fast, even as a hotfix. Because now, with a standard mapping, you cannot use a customer sync.

The code below comes from an subscribed event in codeunit 7205 "CDS Int. Table. Subscriber". when syncing a crm account to a customer it will directly call FillCustomerKeyFromInitSeries. Which is in some scenarios not preferable. Especially when you dont want to use "Instance No. Series" because you already have a number from CRM.
![Code_WlGDbTeVjj](https://user-images.githubusercontent.com/92578153/191756455-64f0797e-2f06-49bb-ba39-013061b118ae.png)

I think it used to work like the event above FillCustomerKeyFromInitSeries seen in the screenshot below. It skips the code when no "Instance No. Series" is filled. But I think somebody changed that and forgot to build an exit. 
![Code_R9xaQDP8aQ](https://user-images.githubusercontent.com/92578153/191758107-4dacff18-c345-4e9d-a214-2e4cf546491e.png)

Why is this exit so important? Because in the initseries function is does a hard get without a try to get the number series. Resulting in a failed sync from crm. 
![Code_qoQD8Y8Aul](https://user-images.githubusercontent.com/92578153/191758457-44d72de5-1d53-4740-b02f-cad570966ee4.png)

**Please fix this! The CRM sync for Customers is practically broken right now and is a real showstopper!** 

_As a side note i would advise that Microsoft never makes use of its own events. You have your own code, and don't  need events for doing stuff like this. It is faster, and more clear on which code comes first if you dont use them. If you use events, you are forced to make new events in events, because sometimes the partner needs to execute the code before your event. Which in this situation (onbeforeinser in crm sync) is impossible.  We, the partners, must use events and are depended on your events. It doesnt help if you don't give us the chance to execute when we need it. Now i am forced to seek an event even before this event to potentially make a workaround. Not that it helped in this case, but still. Please don't subscribe to your own code. It makes the code slow, unreadable and not partner friendly._

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
