### ISSUE TITLE
[Event request] Page 6510 and Codeunit 99000830 - PassTrackingSpecification

### ISSUE THREAD

**Issue by RHansenEpimatic** [microsoft/ALAppExtensions#2042]
On page 6510, in the RegisterChange function, we require the ability to pass additional new fields through from the OldTrackingSpecification / NewTrackingSpecification record variables.  Additional parameters added to the CreateEntry function in codeunit 99000830 would facilitate this, but that probably won’t be an option as that function is called from many places.  So, I’d like to request the following changes:   

- In codeunit 99000830, add a new global function for PassTrackingSpecification that receives in OldTrackingSpecification and NewTrackingSpecification variables (type = Record 336) 
- Have this new function call a new event publisher function: 
       - OnAfterPassTrackingSpecification(OldTrackingSpecification,NewTrackingSpecification, InsertReservEntry2,ReservEntry2) 
- In the RegisterChange function in Page 6510, right before the call to CreateReservEntry.CreateEntry to pass in the OldTrackingSpecification and NewTrackingSpecification variables:  (pasting a code snapshot below)            

![image](https://user-images.githubusercontent.com/44678594/55804051-96f32200-5aa9-11e9-828d-8c385ba1054a.png)

**Comment by AlexanderYakunin** [comment]
This solution cannot be implemented as events

**Comment by RHansenEpimatic** [comment]
Hi Alexander - I don't see why my suggestion isn't possible/acceptable.  Really all we're trying to do here is add one custom field to the reservation entry table and tracking specification table and to then have that custom field flow back and forth.  If my approach isn't acceptable, what is the recommended way to do what we need?

**Comment by AlexanderYakunin** [comment]
You simply need to use this from my point of view:

      CreateReservEntry.GetLastEntry(ReservEntry1);
      **OnRegisterChangeOnAfterCreateReservEntry(ReservEntry1,NewTrackingSpecification);**

If needed we can add OldTrackingSpecification to this event.

**Comment by RHansenEpimatic** [comment]
Thanks - my build doesn't have that event.  Is it already added or are you proposing it?

If you could add OldTrackingSpecification to it, I think this will work great.

**Comment by AlexanderYakunin** [comment]
Already added to master branch, we can use it and it will be present in next 14.x update

**Comment by RHansenEpimatic** [comment]
Super - thanks!  So can you add OldTrackingSpecification as a parameter?

**Comment by AlexanderYakunin** [comment]
Yes

**Comment by RHansenEpimatic** [comment]
Just one last question Alexander.  Assuming this change happens this week, what would the expected timing be for a new build to be publicly available with this and other recent updates?  I'm not sure how frequently those are released.

**Comment by RHansenEpimatic** [comment]
Question Alexander (wasn’t sure how to ask one not related to an issue, so I’m just replying to this)…

Are the daily builds only released as Docker images?  It’s a pain to have to download a full docker image every time I’d like the latest objects…is there any other way they are posted?

Regards,

Rob Hansen, CPA, CMA
epimatic

PH: 519.594.0133 | FAX: 519.489.2712
rhansen@epimatic.com<mailto:rhansen@epimatic.com> | http://www.epimatic.com<http://www.epimatic.com/> | Skype: rhansen74
