### ISSUE TITLE
[Permission Request] Codeunit 1013 Job Jnl.-Post Batch

### ISSUE THREAD

**Issue by moomencegekadsa** [microsoft/ALAppExtensions#20425]
Hello,

We request that you add the following permission to codeunit 1013 _Job Jnl.-Post Batch_.
```
codeunit 1013 "Job Jnl.-Post Batch"
{
    Permissions = TableData "Job Journal Batch" = imd,
               ++ TableData "Job Journal Line" = rimd;
    TableNo = "Job Journal Line";
```
A user may not have the permission to manually add/modify/delete records in _Job Journal Line_, but they can (indirectly) trigger this codeunit. And in this codeunit _Job Journal Lines_ may be inserted/modified and deleted through the execution of the (standard) code.

Thank you in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47752.
