### ISSUE TITLE
[Event Request] Table 39 - Purchase Line - OnBeforeValidateJobLineAmountLCY

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20427]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnBeforeValidateJobLineAmountLCY` in Table 39 Purchase Line with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeValidateJobLineAmountLCY(var PurchaseLine: Record "Purchase Line"; var TempJobJournalLine: Record "Job Journal Line" temporary; var IsHandled: Boolean)
begin
end;
```
which would be called as follows in the OnValidate trigger of field `1010 - Job Line Amount (LCY)`:
```AL
trigger OnValidate()
// >>>> New >>>>>>>>>>>>>>>>
var
    IsHandled: Boolean;
// <<<< New <<<<<<<<<<<<<<<<
begin
    // >>>> New >>>>>>>>>>>>>>>>
    OnBeforeValidateJobLineAmountLCY(Rec, TempJobJnlLine, IsHandled);
    if IsHandled then
        exit;
    // <<<< New <<<<<<<<<<<<<<<<

    TestField("Receipt No.", '');
    if "Document Type" = "Document Type"::Order then
        TestField("Quantity Received", 0);
    if JobTaskIsSet then begin
        CreateTempJobJnlLine(false);
        TempJobJnlLine.Validate("Line Amount (LCY)", "Job Line Amount (LCY)");
        UpdateJobPrices();
    end;
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47054.
