### ISSUE TITLE
[Event-Change Request] Table 39 - Purchase Line - OnAfterAssignGLAccountValues

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20431]
Dear ALAppExtensions team,

through this issue we would like to request a change of event publisher `OnAfterAssignGLAccountValues` in Table 39 Purchase Line from:
```AL
[IntegrationEvent(false, false)]
local procedure OnAfterAssignGLAccountValues(var PurchLine: Record "Purchase Line"; GLAccount: Record "G/L Account")
begin
end;
```
to:
```AL
[IntegrationEvent(false, false)]
local procedure OnAfterAssignGLAccountValues(var PurchLine: Record "Purchase Line"; var xPurchLine: Record "Purchase Line"; GLAccount: Record "G/L Account")
begin
end;
```
adding the xRec as a parameter to the event publisher.

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47054.
