### ISSUE TITLE
[Event Request] Table 39 - Purchase Line - OnValidateNoOnBeforeCheckReceiptNo

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20437]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnValidateNoOnBeforeCheckReceiptNo` in Table 39 Purchase Line with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnValidateNoOnBeforeCheckReceiptNo(var PurchaseLine: Record "Purchase Line"; var xPurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
begin
end;
```
which would be called as follows in the OnValidate trigger of field `6 - No.`:
```AL
trigger OnValidate()
var
    TempPurchLine: Record "Purchase Line" temporary;
    IsHandled: Boolean;
    l_ReceiptGLAccount: Boolean;
begin
    IsHandled := false;
    OnBeforeValidateNo(Rec, xRec, CurrFieldNo, IsHandled);
    if IsHandled then
        exit;
    GetPurchSetup();
    "No." := FindOrCreateRecordByNo("No.");
    TestStatusOpen();
    TestField("Qty. Rcd. Not Invoiced", 0);
    TestField("Quantity Received", 0);
    // >>>> New >>>>>>>>>>>>>>>>
    IsHandled := false;
    OnValidateNoOnBeforeCheckReceiptNo(Rec, xRec, IsHandled);
    if not IsHandled then
        TestField("Receipt No.", '');
    // <<<< New <<<<<<<<<<<<<<<<
    ...
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47054.
