### ISSUE TITLE
[EventRequest] OnRefreshOnAfterGetRecordOnAfterGetPurchLines in Purchase Order Statistics

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#20455]
Hello, please consider adding this event to the Purchase Order Statistics page

```
    [IntegrationEvent(false, false)]
    local procedure OnRefreshOnAfterGetRecordOnAfterGetPurchLines(PurchaseHeader: Record "PurchaseHeader"; var TempPurchLine: Record "Purchase Line" temporary)
    begin
    end;
```

and raise it after `PurchPost.GetPurchLines(Rec, TempPurchLine, i - 1);` in the `RefreshOnAfterGetRecord` procedure, similarly to how it's done in the Sales Order Statistics page.

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48467.
