### ISSUE TITLE
Date is Invalid Error when the Tests are run & cancelled manually from the AL Test Tool Page.

### ISSUE THREAD

**Issue by diveshbora** [microsoft/ALAppExtensions#20454]
https://github.com/microsoft/ALAppExtensions/blob/605555d636eb4463458bba728f7acfaa1421dcd1/Modules/DevTools/TestFramework/TestRunner/src/ALTestTool.Page.al#L452

RunDuration := Rec."Finish Time" - Rec."Start Time";

We sometimes get a Date is an Invalid error when the Tests are run & canceled manually from the AL Test Tool Page and the user is trying to open the page again. This is because the "Finish Time" is not updated for the test.

Can you please fix the code? Thanks

**Comment by JesperSchulz** [comment]
That might just be a product defect! Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps). We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
