### ISSUE TITLE
codeunit 5870 "Calculate BOM Tree" procedure GenerateProdCompSubTree - make it possbile to load data from SKU

### ISSUE THREAD

**Issue by extranrollo** [microsoft/ALAppExtensions#20457]
### 
codeunit 5870 "Calculate BOM Tree" 
procedure GenerateProdCompSubTree

In this procedure you search the ProdBOMLines depending on the Item.

![grafik](https://user-images.githubusercontent.com/36401349/192549203-910960c0-c420-4b81-aab0-12175eb859a7.png)

The problem is, that we define Prod Boms and Routings on the SKU and want to display the  Page "Item Availability by BOM Level" depending on the ProdBom and Routing from the SKU.

When you init the BOMLine, you  already have this event, where i can change the filters/Values from the BOMBuffer, but this is reset due to the logic above.

![grafik](https://user-images.githubusercontent.com/36401349/192548758-a0fd9203-65df-4e29-8e2c-418bae3ea45c.png)

So please change the part above from
with ProdBOMLine do begin
            SetRange("Production BOM No.", ParentItem."Production BOM No.");
            SetRange("Version Code", VersionMgt.GetBOMVersion(ParentItem."Production BOM No.", WorkDate, true));

to
with ProdBOMLine do begin
            SetRange("Production BOM No.", **_BOMBuffer_.**"Production BOM No.");
            SetRange("Version Code", VersionMgt.GetBOMVersion(**_BOMBuffer_**."Production BOM No.", WorkDate, true));

**Comment by JesperSchulz** [comment]
Internally closed as "Won't Fix" by @alexei-dobriansky with reason "This is not a safe change. In the code below, ParentItem and BOMBuffer have different Production BOM No. and Routing No. values, therefore we can't make suggested changes in GenerateProdCompSubTree.". Syncing state to GitHub.
