### ISSUE TITLE
[Event Request] Table 39 - Purchase Line - OnAfterDelete*** in local procedure DeleteChargeChargeAssgnt

### ISSUE THREAD

**Issue by InaBosseBiTeam** [microsoft/ALAppExtensions#20465]
Related to issue #20342 

Dear ALAppExtensions team,

we would like to request adding event publisher OnAfterDelete*** in Table 39 Purchase Line. 
I checked again: In 20.5.45456.45889 is no publisher OnAfterDelete with parameter: 
var PurchaseLine: Record "Purchase Line"; var xPurchaseLine: Record "Purchase Line"; CurrentFieldNo: Integer; DocType: Enum "Purchase Document Type"; DocNo: Code[20]; DocLineNo: Integer

```
local procedure DeleteChargeChargeAssgnt(DocType: Enum "Purchase Document Type"; DocNo: Code[20]; DocLineNo: Integer)
    var
        ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)";
    begin
        if DocType <> "Document Type"::"Blanket Order" then
            if "Quantity Invoiced" <> 0 then begin
                CalcFields("Qty. Assigned");
                TestField("Qty. Assigned", "Quantity Invoiced");
            end;

        ItemChargeAssgntPurch.Reset();
        ItemChargeAssgntPurch.SetRange("Document Type", DocType);
        ItemChargeAssgntPurch.SetRange("Document No.", DocNo);
        ItemChargeAssgntPurch.SetRange("Document Line No.", DocLineNo);
        if not ItemChargeAssgntPurch.IsEmpty() then
            ItemChargeAssgntPurch.DeleteAll();

--> ***
    end;
```

P.S. 
In procedure DeleteItemChargeAssignment is the publisher 
`OnAfterDeleteChargeChargeAssgnt(Rec, xRec, CurrFieldNo)`
The name is misleading in this case.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48444.
