### ISSUE TITLE
[Event Request] table 5895 "Inventory Adjustment Buffer" OnAddActualCostBufOnBeforeInsert

### ISSUE THREAD

**Issue by j4ck4l** [microsoft/ALAppExtensions#20461]
![image](https://user-images.githubusercontent.com/4457057/192611568-2a910985-0488-4690-ab2c-0231230ce5cd.png)

Intergation Event:
    local procedure OnAddActualCostBufOnBeforeInsert(var InventoryAdjustmentBuffer: Record "Inventory Adjustment Buffer"; ValueEntry: Record "Value Entry")

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48467.
