### ISSUE TITLE
New Event in codeunit 13636 "OIOUBL-Export Sales Invoice"

### ISSUE THREAD

**Issue by Midtfact** [microsoft/ALAppExtensions#20475]
We need to add a segment "PayeeParty" to the OIOUBL and according to http://oioubl.info/Classes/da/Invoice.html this segment must be placed after AccountingCustomerParty.

Please make a new Event here

        // Invoice->AccountingCustomerParty
        BillToAddress.Address := SalesInvoiceHeader."Bill-to Address";
        BillToAddress."Address 2" := SalesInvoiceHeader."Bill-to Address 2";
        BillToAddress.City := SalesInvoiceHeader."Bill-to City";
        BillToAddress."Post Code" := SalesInvoiceHeader."Bill-to Post Code";
        BillToAddress."Country/Region Code" := SalesInvoiceHeader."Bill-to Country/Region Code";
        SellToContact.Name := SalesInvoiceHeader."Sell-to Contact";
        SellToContact."Phone No." := SalesInvoiceHeader."OIOUBL-Sell-to Contact Phone No.";
        SellToContact."Fax No." := SalesInvoiceHeader."OIOUBL-Sell-to Contact Fax No.";
        SellToContact."E-Mail" := SalesInvoiceHeader."OIOUBL-Sell-to Contact E-Mail";
        OIOUBLXMLGenerator.InsertAccountingCustomerParty(XMLCurrNode,
          SalesInvoiceHeader."OIOUBL-GLN",
          SalesInvoiceHeader."VAT Registration No.",
          SalesInvoiceHeader."Bill-to Name",
          BillToAddress,
          SellToContact);

//New event+
// Invoice->PayeeParty
IsHandled := False
OnCreateXMLOnbeforeInsertPayeeParty(XMLCurrNode, SalesInvoiceHeader, IsHandled);
//New event-

        // Invoice->Delivery

And add this

    [IntegrationEvent(false, false)]
    local procedure OnCreateXMLOnbeforeInsertPayeeParty(var XMLCurrNode: XmlElement; SalesInvoiceHeader: Record "Sales Invoice Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by Vadim-Stepanenko** [comment]
We cannot provide events with dotnet parameters in them, if you find a way to implement this without requesting a dotnet param event feel free to do so in a new issue.
