### ISSUE TITLE
[Event Request] Table 11401 "CBG Statement Line" - OnBeforeValidateVATAmount

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#20483]
Hello,

We would need a new event **OnBeforeValidateVATAmount** in table 11401 "CBG Statement Line" in function **CreateGenJournalLine**:

    procedure CreateGenJournalLine(var GenJnlLine: Record "Gen. Journal Line")
    var
        CBGStatement: Record "CBG Statement";
        IsHandled: Boolean; // <<NEW EVENT>>
    begin
        CheckAccountNo();
        GenJnlLine.Init();
        GenJnlLine."Journal Template Name" := "Journal Template Name";
        GenJnlLine."Journal Batch Name" := Text1000016;// STRSUBSTNO('%1',"No.");
        GenJnlLine."Line No." := 0;

        GenJnlLine.Validate("Posting Date", Date);
        case "Account Type" of
            "Account Type"::"G/L Account":
                begin
                    GenJnlLine."Account Type" := GenJnlLine."Account Type"::"G/L Account";
                    case "VAT Type" of
                        "VAT Type"::Purchase:
                            if Credit = 0 then
                                GenJnlLine."Document Type" := GenJnlLine."Document Type"::Payment
                            else
                                GenJnlLine."Document Type" := GenJnlLine."Document Type"::" ";
                        "VAT Type"::Sale:
                            if Debit = 0 then
                                GenJnlLine."Document Type" := GenJnlLine."Document Type"::Payment
                            else
                                GenJnlLine."Document Type" := GenJnlLine."Document Type"::" ";
                    end;
                end;
            "Account Type"::Customer:
                begin
                    GenJnlLine."Account Type" := GenJnlLine."Account Type"::Customer;
                    if Debit = 0 then
                        GenJnlLine."Document Type" := GenJnlLine."Document Type"::Payment
                    else
                        GenJnlLine."Document Type" := GenJnlLine."Document Type"::Refund;
                end;
            "Account Type"::Vendor:
                begin
                    GenJnlLine."Account Type" := GenJnlLine."Account Type"::Vendor;
                    if Credit = 0 then
                        GenJnlLine."Document Type" := GenJnlLine."Document Type"::Payment
                    else
                        GenJnlLine."Document Type" := GenJnlLine."Document Type"::Refund;
                end;
            "Account Type"::Employee:
                begin
                    GenJnlLine."Account Type" := GenJnlLine."Account Type"::Employee;
                    GenJnlLine."Document Type" := GenJnlLine."Document Type"::Payment;
                end;
            "Account Type"::"Bank Account":
                begin
                    GenJnlLine."Account Type" := GenJnlLine."Account Type"::"Bank Account";
                    GenJnlLine."Document Type" := GenJnlLine."Document Type"::" ";
                end;
        end;
        GenJnlLine.Validate("Account No.", "Account No.");

        CBGStatement.Get("Journal Template Name", "No.");
        case CBGStatement.Type of
            CBGStatement.Type::"Bank/Giro":
                begin
                    if Date = 0D then
                        Error(Text1000017 +
                          '%3 %4 %5', "No.", "Line No.", GenJnlLine."Account Type", GenJnlLine."Account No.", GenJnlLine.Description);
                    GenJnlLine.Validate("Posting Date", Date);
                    GenJnlLine.Validate("Document Date", CBGStatement.Date);
                    GenJnlLine.Validate("Document No.", CBGStatement."Document No.");
                end;
            CBGStatement.Type::Cash:
                begin
                    if Date = 0D then
                        Error(Text1000018 +
                          '%3 %4 %5', "No.", "Line No.", GenJnlLine."Account Type", GenJnlLine."Account No.", GenJnlLine.Description);
                    GenJnlLine.Validate("Posting Date", Date);
                    GenJnlLine.Validate("Document Date", Date);
                    GenJnlLine.Validate("Document No.", "Document No.");
                end;
        end;

        if "Shortcut Dimension 1 Code" <> '' then
            GenJnlLine.Validate("Shortcut Dimension 1 Code", "Shortcut Dimension 1 Code");
        if "Shortcut Dimension 2 Code" <> '' then
            GenJnlLine.Validate("Shortcut Dimension 2 Code", "Shortcut Dimension 2 Code");
        if "Dimension Set ID" <> 0 then
            GenJnlLine.Validate("Dimension Set ID", "Dimension Set ID");

        GenJnlLine.Validate("Currency Code", CBGStatement.Currency);
        case "VAT Type" of
            "VAT Type"::" ":
                GenJnlLine."Gen. Posting Type" := GenJnlLine."Gen. Posting Type"::" ";
            "VAT Type"::Purchase:
                begin
                    GenJnlLine."Gen. Posting Type" := GenJnlLine."Gen. Posting Type"::Purchase;
                    GenJnlLine."Document Type" := GenJnlLine."Document Type"::Invoice;
                end;
            "VAT Type"::Sale:
                begin
                    GenJnlLine."Gen. Posting Type" := GenJnlLine."Gen. Posting Type"::Sale;
                    GenJnlLine."Document Type" := GenJnlLine."Document Type"::Invoice;
                end;
        end;

        GenJnlLine."VAT Bus. Posting Group" := "VAT Bus. Posting Group";
        GenJnlLine.Validate("VAT Prod. Posting Group", "VAT Prod. Posting Group");

        if Correction then
            GenJnlLine."Document Type" := GenJnlLine."Document Type"::" ";
        GenJnlLine.Description := Description;
        if "Applies-to Doc. No." <> '' then begin
            GenJnlLine.Validate("Applies-to Doc. Type", "Applies-to Doc. Type");
            GenJnlLine.Validate("Applies-to Doc. No.", "Applies-to Doc. No.");
        end else
            if "Applies-to ID" <> '' then
                GenJnlLine.Validate("Applies-to ID", "Applies-to ID");

        if "Debit Incl. VAT" <> 0 then begin
            GenJnlLine.Amount := "Debit Incl. VAT";
            GenJnlLine.Validate("Debit Amount", "Debit Incl. VAT")
        end else begin
            GenJnlLine.Amount := -"Credit Incl. VAT";
            GenJnlLine.Validate("Credit Amount", "Credit Incl. VAT");
        end;

        if GenJnlLine."VAT Calculation Type" <> GenJnlLine."VAT Calculation Type"::"Full VAT" then begin // <<NEW EVENT
            // <<NEW EVENT
            IsHandled := false;
            OnBeforeValidateVATAmount(Rec, IsHandled);
            if not IsHandled then
            // >>NEW EVENT
                if ("Debit VAT" <> 0) and ("Debit VAT" <> GenJnlLine."VAT Amount") then
                    GenJnlLine.Validate("VAT Amount", "Debit VAT")
                else
                   if ("Credit VAT" <> 0) and (-"Credit VAT" <> GenJnlLine."VAT Amount") then
                       GenJnlLine.Validate("VAT Amount", -"Credit VAT");
        end; // >>NEW EVENT
        OnAfterCreateGenJournalLine(GenJnlLine, Rec);
    end;

Event publisher:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateVATAmount(CBGStatementLine: Record "CBG Statement Line"; var IsHandled: Boolean)
    begin
    end;

We would need this event with IsHandled pattern because we need to execute in certain conditions the piece of code below:
 if ("Debit VAT" <> 0) and ("Debit VAT" <> GenJnlLine."VAT Amount") then
                GenJnlLine.Validate("VAT Amount", "Debit VAT")
            else
                if ("Credit VAT" <> 0) and (-"Credit VAT" <> GenJnlLine."VAT Amount") then
                    GenJnlLine.Validate("VAT Amount", -"Credit VAT");

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48444.
