### ISSUE TITLE
[Request for external] page 12156 "Subcontracting Prices"

### ISSUE THREAD

**Issue by Vittorio-Panigoni** [microsoft/ALAppExtensions#20496]
In page 12156 "Subcontracting Prices" (italian localization) could you change the scope of the following variables to protected?
protected var
        VendNoFilter: Code[30];
        ItemNoFilter: Code[30];
        WorkCenterFilter: Code[30];
        TaskCodeFilter: Code[30];
        StartingDateFilter: Text[30];

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47754.
