### ISSUE TITLE
Follow-up: Request to make global variable ManagerRole in the Time Sheet Detail pages accessible from page extensions

### ISSUE THREAD

**Issue by pieter-kok** [microsoft/ALAppExtensions#20494]
The following issue has been closed with the tag [ships-in-future-update] on June 3.
When can we expect this modification, as I don't see it in the current version and not in the BC21 NextMajor/Preview.

https://github.com/microsoft/ALAppExtensions/issues/18385

**Comment by AlexanderYakunin** [comment]
All this already done in version 21. We always do external access changes in new major release only.
