### ISSUE TITLE
[Event Request] Codeunit 12 - Gen. Jnl.-Post Line

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#20497]
Dear ALAppExtensions team,

Through this issue we would like to request the inclusion of the sender in Codeunit 12 `Gen. Jnl.-Post Line` Eventpublisher `OnBeforePostUnapply`.

```AL
[IntegrationEvent(true, false)]    <<<<<<<
local procedure OnBeforePostUnapply(GenJnlLine: Record "Gen. Journal Line"; var VATEntry: Record "VAT Entry";
    VATEntryType: Enum "General Posting Type"; BilltoPaytoNo: Code[20];
                      TransactionNo: Integer;
                      UnapplyVATEntries: Boolean;
    var TempVATEntry: Record "VAT Entry" temporary; var IsHandled: Boolean; var NextVATEntryNo: Integer)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47832.
