### ISSUE TITLE
Reread modified global Item var on Sales Line

### ISSUE THREAD

**Issue by SirBETE** [Microsoft/ALAppExtensions#205]
In OnValidate of No on Sales Line we used to change something on the entered Item No and reread the global variable Item.
If we didn't do this `Item.GET("No.")`, we would get the error 'Another use has modified the record ...'.

So in events:
```
LOCAL [EventSubscriber] OnBeforeValidate_Quantity_SalesLine(VAR Rec : Record "Sales Line";VAR xRec : Record "Sales Line";CurrFieldNo : Integer)
WITH Rec DO BEGIN
      lrecItem.GET("No.");
      DoSomething()
      lrecItem.MODIFY;
      Item.GET("No."); // reread global var
```
However `Item.GET("No.");` isn't possible cause we have no access to the global var Item.
There is however the local function GetItem, but this only performs the actual get when the No has changed.
```
LOCAL GetItem()
TESTFIELD("No.");
IF "No." <> Item."No." THEN
  Item.GET("No.");
```
We want to always reread the global var Item.
Any ideas on how to solve this?

For now we have solved it by putting the `IF "No." <> Item."No." THEN` in comment in GetItem.

Using NAV2018CU3

**Comment by JesperSchulz** [comment]
Hi @SirBETE,

are you still looking for help on this one, or did you find an answer in the meantime? :-)

**Comment by SirBETE** [comment]
Hello @JesperSchulz , 

If it's possible yes.
At the moment it hasn't a high priority.
We are preparing a customer's db with the upgrade to extensions.
Although the upgrade itself won't be requested for a while, we would still need a solution for this.
So that when we upgrade, we don't have to request enhancements/events anymore.

**Comment by JesperSchulz** [comment]
A solution to your problem has been implemented (and even back ported to our current release). You can find the code in the latest preview or in the upcoming update. Closing issue. If you have further requests, please open a new issue, as closed issues often drown in an ocean of issues :-)
