### ISSUE TITLE
[Event Request] New IntegrationEvent in Codeunit 7017 "Price List Management", function IsAllowedEditingActivePrice

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/ALAppExtensions#20500]
`
// Add name to return variable
procedure IsAllowedEditingActivePrice(PriceType: Enum "Price Type") **EditingAllowed** : Boolean;
    var
        PurchasesPayablesSetup: Record "Purchases & Payables Setup";
        SalesReceivablesSetup: Record "Sales & Receivables Setup";
    begin
        case PriceType of
            "Price Type"::Sale:
                if SalesReceivablesSetup.Get() then
                    exit(SalesReceivablesSetup."Allow Editing Active Price");
            "Price Type"::Purchase:
                if PurchasesPayablesSetup.Get() then
                    exit(PurchasesPayablesSetup."Allow Editing Active Price");
        end;
// Call New Event
**OnAfterIsAllowedEditingActivePrice(PriceType, EditingAllowed);** 
// Call New Event
    end;

// New Event
**local procedure OnAfterIsAllowedEditingActivePrice(PriceType: Enum "Price Type"; var EditingAllowed : Boolean)
begin 
end;**
// New Event

`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47832.
