### ISSUE TITLE
[Event Request] Table 113 - Procedure CalcQty

### ISSUE THREAD

**Issue by rvillanueva360** [microsoft/ALAppExtensions#20506]
Reason:
Need the event to support extensibility of CalcQty function for the Sales Invoice Line Table an upgrade project in BC Cloud Tenant.

Sample Code:
```
local procedure CalcQty(QtyBase: Decimal): Decimal
begin
//REQUEST BEGIN
OnBeforeCalcQty(Rec, QtyBase, IsHandled);
if IsHandled then
exit(QtyBase);
//REQUEST END

if "Qty. per Unit of Measure" = 0 then
    exit(QtyBase);
  exit(Round(QtyBase / "Qty. per Unit of Measure", UOMMgt.QtyRndPrecision));
end;


[IntegrationEvent(false, false)]
local procedure OnBeforeCalcQty(var SalesInvoiceLine: Record "Sales Invoice Line"; var QtyBase: Decimal; var IsHandled: Boolean)
begin
end;
```

**Comment by rvillanueva360** [comment]
Do we have an idea about timelines and how to expedite this request because it is holding up a client upgrade, we need to inform the stake holders.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47832.
