### ISSUE TITLE
[Event Request] Codeunit 311 - Procedure ConvertQty

### ISSUE THREAD

**Issue by rvillanueva360** [microsoft/ALAppExtensions#20508]
Reason:
Need the event to support extensibility of ConvertQty function for the CodeUnit 311: Item Check Availability on upgrade project in BC Cloud Tenant.

Source Code:
```
local procedure ConvertQty(Qty: Decimal): Decimal
begin
//REQUEST BEGIN
OnBeforeConvertQty(ItemNo, Qty, QtyPerUnitOfMeasure, IsHandled); 
if IsHandled then
  exit(Qty);
//REQUEST END

  if QtyPerUnitOfMeasure = 0 then
    QtyPerUnitOfMeasure := 1;
  exit(Round(Qty / QtyPerUnitOfMeasure, UOMMgt.QtyRndPrecision));
end; 

[IntegrationEvent(false, false)]
local procedure OnBeforeConvertQty(ItemNo: Code[20]; var Qty: Decimal; var QtyPerUnitOfMeasure: Decimal; var IsHandled: Boolean)
begin
end;
```

**Comment by rvillanueva360** [comment]
Do we have an idea about timelines and how to expedite this request because it is holding up a client upgrade, we need to inform the stake holders.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47832.
