### ISSUE TITLE
[Event Request] Codeunit 99000831 - Procedure ModifyReservEntry

### ISSUE THREAD

**Issue by rvillanueva360** [microsoft/ALAppExtensions#20512]
Reason:
Need the event to support extensibility of ModifyReservEntry function for the Reservation Engine Mgt. codeunit an upgrade project in BC Cloud Tenant.

Sample Code:
```
procedure ModifyReservEntry(ReservEntry: Record "Reservation Entry"; NewQuantity: Decimal; NewDescription: Text[100]; ModifyReserved: Boolean)
var
    TotalQty: Decimal;
    IsHandled: Boolean;
begin
    OnBeforeModifyReservEntry(ReservEntry, NewQuantity, NewDescription, ModifyReserved);

    //EVENT REQUEST
    IsHandled := false;
    OnBeforeModifyReservEntryOnCheckNewQuantity(ReservEntry, NewQuantity, NewDescription, ModifyReserved, IsHandled);
    if not IsHandled then begin
    //EVENT REQUEST
        ReservEntry.TestField("Reservation Status", ReservEntry."Reservation Status"::Reservation);
        if NewQuantity * ReservEntry."Quantity (Base)" < 0 then
            if NewQuantity < 0 then
                Error(Text000, ReservEntry.FieldCaption("Quantity (Base)"))
            else
                Error(Text001, ReservEntry.FieldCaption("Quantity (Base)"));
        if NewQuantity = 0 then
            Error(Text002);
        if Abs(NewQuantity) > Abs(ReservEntry."Quantity (Base)") then
            Error(Text003, ReservEntry.FieldCaption("Quantity (Base)"));
    //EVENT REQUEST
    end;
    //EVENT REQUEST

    if ModifyReserved then begin
        if ReservEntry."Item No." <> Item."No." then
            GetItem(ReservEntry."Item No.");

        ReservEntry.Get(ReservEntry."Entry No.", ReservEntry.Positive); // Get existing entry
        ReservEntry.Validate("Quantity (Base)", NewQuantity);
        ReservEntry.Description := NewDescription;
        ReservEntry."Changed By" := UserId;
        OnModifyReservEntryOnBeforeExistingReservEntryModify(ReservEntry);
        ReservEntry.Modify();
        OnModifyReservEntryOnAfterExistingReservEntryModify(ReservEntry);
        if Item."Order Tracking Policy" <> Item."Order Tracking Policy"::None then begin
            TotalQty := ReservMgt.SourceQuantity(ReservEntry, true);
            ReservMgt.AutoTrack(TotalQty);
        end;

        if ReservEntry.Get(ReservEntry."Entry No.", not ReservEntry.Positive) then begin // Get related entry
            ReservEntry.Validate("Quantity (Base)", -NewQuantity);
            ReservEntry.Description := NewDescription;
            ReservEntry."Changed By" := UserId;
            ReservEntry.Modify();
            if Item."Order Tracking Policy" <> Item."Order Tracking Policy"::None then begin
                TotalQty := ReservMgt.SourceQuantity(ReservEntry, true);
                ReservMgt.AutoTrack(TotalQty);
            end;
        end;
    end;

    OnAfterModifyReservEntry(ReservEntry);
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeModifyReservEntryOnCheckNewQuantity(var ReservEntry: Record "Reservation Entry"; var NewQuantity: Decimal; NewDescription: Text[100]; var ModifyReserved: Boolean; var IsHandled: Boolean)
begin
end;
```

**Comment by rvillanueva360** [comment]
Do we have an idea about timelines and how to expedite this request because it is holding up a client upgrade, we need to inform the stake holders.

**Comment by rvillanueva360** [comment]
May I follow up on timelines to expedite this request because it is holding up client upgrade, we need to report update the stake holders.

**Comment by rvillanueva360** [comment]
May I follow up again about timelines and how to expedite this request because it is holding up a client upgrade, we need to inform the stake holders.

**Comment by AlexanderYakunin** [comment]
Again, question about your expectations, this event will be done in few days for Master and 21.x (and therefore for 21.1). Is this what you expect?

**Comment by rvillanueva360** [comment]
Hi Alexander,

We need these events requested here in BC21 or earlier so long at it is when we create a new Sandbox: https://github.com/microsoft/ALAppExtensions/issues/created_by/rvillanueva360

  *   To support extensibility of ModifyReservEntry function for the Reservation Engine Mgt. codeunit an upgrade project in BC Cloud Tenant.
     *   Also need IsHandled variable to prevent execution of a part of the standard code
  *   To support extensibility of RetrieveInvoiceSpecification function for the codeunit 6500: Item Tracking Management on upgrade project in BC Cloud Tenant.
     *   Also need IsHandled variable to prevent execution of a part of the standard code

We also need to know if the requested list noted below is already available in the latest version of BC21 in the cloud:
https://github.com/microsoft/ALAppExtensions/issues?q=is%3Aissue+author%3Arvillanueva360+is%3Aclosed

Cheers,
[360 Visibility]<https://www.360visibility.com/?utm_source=email-signature>
Randy Villanueva
Sr. Dynamics Consultant
***@***.******@***.***> | (905) 907-3610<tel:(905)%20907-3610>
926 Nashville Rd., Vaughan ON L0J 1C0
[Twitter]<https://twitter.com/360visibility>[LinkedIn]<https://www.linkedin.com/company/360-visibility>[YouTube]<https://www.youtube.com/user/360visibilityinc>[Facebook]<https://www.facebook.com/360Vis/>[Instagram]<https://www.instagram.com/360_visibility/>
www.360visibility.com<https://www.360visibility.com/?utm_source=email-signature>
My working hours may not be your working hours. Please do not feel obligated to reply outside of your normal work schedule.
[https://360emailsignatures.blob.core.windows.net/pictures/email-signature-banner.jpg]<https://www.360visibility.com/email-signature-banner/?utm_source=email-signature>

**Comment by rvillanueva360** [comment]
Yes, please confirm if this events can be available in the latest release of BC this week?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48444.

**Comment by rvillanueva360** [comment]
It is still not in 21.1, please let us know which build will have this event update.
