### ISSUE TITLE
[Request for external] Table 81 Gen. Journal Line

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#20515]
In github request #19142 we requested to remove the OnPrem Scope from especially the dutch localization procedure "Lookup Applies-to Doc. No.". It is said that the scope is already removed. 
When looking in the R21 preview the onprem scope is still on the function and therefore cannot be used in extension development.

**Comment by neverbeam** [comment]
We are now stuck with removing our footprint because this function has the OnPrem scope while it is not specifically OnPrem. The tag can be removed in the meantime while an approach is set out how to deal with this localization.

**Comment by AlexanderYakunin** [comment]
This change is in progress and this code will be moved to table CBG Statement Line. Can you explain why do you need to call this procedure? Looks like this make sense in scope of CBG Statement Line only and should be local.

**Comment by neverbeam** [comment]
We have a PageExtension on the CBG statement functionality (specifically a page extension on Bank/giro journal and Cash journal subform pages). From this page extension we modify the standard BC lookup for applies to Doc-No. This function is specifically used for that purpose. For this we need this function that is specifically for dutch localization. 
I also found it very strange that the function was part of the Gen Journal Line table.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47843.
