### ISSUE TITLE
[Event Request] Codeunit 6500 - Procedure RetrieveInvoiceSpecification

### ISSUE THREAD

**Issue by rvillanueva360** [microsoft/ALAppExtensions#20511]
Reason:
Need the event to support extensibility of RetrieveInvoiceSpecification function for the codeunit 6500: Item Tracking Management on upgrade project in BC Cloud Tenant.

Sample code:
```
procedure RetrieveInvoiceSpecification(SourceSpecification: Record "Tracking Specification"; var TempInvoicingSpecification: Record "Tracking Specification" temporary) OK: Boolean
var
    TrackingSpecification: Record "Tracking Specification";
    ReservEntry: Record "Reservation Entry";
    TempTrackingSpecSummedUp: Record "Tracking Specification" temporary;
    IsHandled: Boolean;
begin
    OK := false;
    TempInvoicingSpecification.Reset();
    TempInvoicingSpecification.DeleteAll();
    ReservEntry.SetSourceFilter(
      SourceSpecification."Source Type", SourceSpecification."Source Subtype", SourceSpecification."Source ID",
      SourceSpecification."Source Ref. No.", true);
    ReservEntry.SetSourceFilter(SourceSpecification."Source Batch Name", SourceSpecification."Source Prod. Order Line");
    ReservEntry.SetFilter("Reservation Status", '<>%1', ReservEntry."Reservation Status"::Prospect);
    ReservEntry.SetFilter("Item Tracking", '<>%1', ReservEntry."Item Tracking"::None);
    SumUpItemTracking(ReservEntry, TempTrackingSpecSummedUp, false, true);
    // TrackingSpecification contains information about lines that should be invoiced:
    TrackingSpecification.SetSourceFilter(
      SourceSpecification."Source Type", SourceSpecification."Source Subtype", SourceSpecification."Source ID",
      SourceSpecification."Source Ref. No.", true);
    TrackingSpecification.SetSourceFilter(
      SourceSpecification."Source Batch Name", SourceSpecification."Source Prod. Order Line");
    
    //EVENT REQUEST 
    IsHandled := false; 
    OnBeforeFindTrackingSpecification(TempInvoicingSpecification, TempTrackingSpecSummedUp, TrackingSpecification, SourceSpecification, OK, IsHandled); 
    if not IsHandled then
    //EVENT REQUEST
        if TrackingSpecification.FindSet() then
            repeat
                TrackingSpecification.TestField("Qty. to Handle (Base)", 0);
                TrackingSpecification.TestField("Qty. to Handle", 0);
                if not TrackingSpecification.Correction then begin
                    TempInvoicingSpecification := TrackingSpecification;
                    TempInvoicingSpecification."Qty. to Invoice" :=
                    Round(TempInvoicingSpecification."Qty. to Invoice (Base)" /
                        SourceSpecification."Qty. per Unit of Measure", UOMMgt.QtyRndPrecision);
                    TempInvoicingSpecification.Insert();
                    OK := true;
                    TempTrackingSpecSummedUp.SetTrackingFilterFromSpec(TempInvoicingSpecification);
                    if TempTrackingSpecSummedUp.FindFirst() then begin
                        TempTrackingSpecSummedUp."Qty. to Invoice (Base)" += TempInvoicingSpecification."Qty. to Invoice (Base)";
                        OnBeforeTempTrackingSpecSummedUpModify(TempTrackingSpecSummedUp, TempInvoicingSpecification);
                        TempTrackingSpecSummedUp.Modify();
                    end else begin
                        TempTrackingSpecSummedUp := TempInvoicingSpecification;
                        TempTrackingSpecSummedUp.Insert();
                    end;
                end;
            until TrackingSpecification.Next() = 0;

    if not IsConsume and (SourceSpecification."Qty. to Invoice (Base)" <> 0) then
        CheckQtyToInvoiceMatchItemTracking(
          TempTrackingSpecSummedUp, TempInvoicingSpecification,
          SourceSpecification."Qty. to Invoice (Base)", SourceSpecification."Qty. per Unit of Measure");
    TempInvoicingSpecification.SetFilter("Qty. to Invoice (Base)", '<>0');
    if not TempInvoicingSpecification.FindFirst() then
        TempInvoicingSpecification.Init();
end;


    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindTrackingSpecification(var TempInvoicingSpecification: Record "Tracking Specification"; var TempTrackingSpecSummedUp: Record "Tracking Specification" temporary; TrackingSpecification: Record "Tracking Specification"; SourceSpecification: Record "Tracking Specification"; var OK: Boolean; var IsHandled: Boolean)
    begin
    end;
```

**Comment by rvillanueva360** [comment]
Do we have an idea about timelines and how to expedite this request because it is holding up a client upgrade, we need to inform the stake holders.

**Comment by rvillanueva360** [comment]
May I follow up on timelines to expedite this request because it is holding up client upgrade, we need to report update the stake holders.

**Comment by rvillanueva360** [comment]
May I follow up again about timelines and how to expedite this request because it is holding up a client upgrade, we need to inform the stake holders.

**Comment by AlexanderYakunin** [comment]
Please explain why do you need this for upgrade project? In which version you expect us to implement this event?

**Comment by rvillanueva360** [comment]
Thanks. Please let us know when we can test.

**Comment by rvillanueva360** [comment]
Still not found in BC 21.1. Please let us know which build will have this event.

**Comment by JesperSchulz** [comment]
I can see the changes in the 22 release:
![image](https://user-images.githubusercontent.com/19796701/207339939-b9d052e5-ff1a-47ae-b4ea-00d9066d7ed7.png)

I cannot find them in 21.x yet. @AlexanderYakunin, do you have an update on when this event is going to get backported?

**Comment by rvillanueva360** [comment]
Hi

Our client has been delayed in upgrading from NAV to BC due to these missing events.  Waiting until version 22 will mean they will not upgrade as their timeframe to complete the production upgrade is February.  If that date is missed they will need to delay for close a year, incurring both BC costs as well as the cost to host their NAV environment.

Can these be expedited in any way?

Thanks
Barb

[360 Visibility]<https://www.360visibility.com/?utm_source=email-signature>
Barbara Allen
Vice President, Client Solutions
***@***.******@***.***> | (905) 907-3604<tel:(905)%20907-3604>
926 Nashville Rd., Vaughan ON L0J 1C0
[Twitter]<https://twitter.com/360visibility>[LinkedIn]<https://www.linkedin.com/company/360-visibility>[YouTube]<https://www.youtube.com/user/360visibilityinc>[Facebook]<https://www.facebook.com/360Vis/>[Instagram]<https://www.instagram.com/360_visibility/>
www.360visibility.com<https://www.360visibility.com/?utm_source=email-signature>
My working hours may not be your working hours. Please do not feel obligated to reply outside of your normal work schedule.
[https://360emailsignatures.blob.core.windows.net/pictures/email-signature-banner.jpg]<https://www.360visibility.com/email-signature-banner/?utm_source=email-signature>


From: Randy Villanueva ***@***.***>
Sent: December 14, 2022 9:11 AM
To: microsoft/ALAppExtensions ***@***.***>; microsoft/ALAppExtensions ***@***.***>
Cc: Author ***@***.***>; Barbara Allen ***@***.***>
Subject: RE: [microsoft/ALAppExtensions] [Event Request] Codeunit 6500 - Procedure RetrieveInvoiceSpecification (Issue #20511)

Hi Jesper,

Is there a way to expedite these event requests on BC21.x?
https://github.com/microsoft/ALAppExtensions/issues/20511<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FALAppExtensions%2Fissues%2F20511&data=05%7C01%7Cballen%40360visibility.com%7C508e25c1889d4f6cf6e008dadddcf62b%7C0815a0a621fd4467a0ad296bc115d5f2%7C0%7C0%7C638066238375320482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=Ju8xI3kJXqAHgfihb%2FY%2BErRUQpThc579PKE5hMvEM0I%3D&reserved=0>
https://github.com/microsoft/ALAppExtensions/issues/20512<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FALAppExtensions%2Fissues%2F20512&data=05%7C01%7Cballen%40360visibility.com%7C508e25c1889d4f6cf6e008dadddcf62b%7C0815a0a621fd4467a0ad296bc115d5f2%7C0%7C0%7C638066238375320482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=Cd2rQvuSC2prGIXuaF7bIbtmF7Cj9Nh8AnuBdtPohGo%3D&reserved=0>

It is holding up our upgrade project.

Cheers,


[360 Visibility]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.360visibility.com%2F%3Futm_source%3Demail-signature&data=05%7C01%7Cballen%40360visibility.com%7C508e25c1889d4f6cf6e008dadddcf62b%7C0815a0a621fd4467a0ad296bc115d5f2%7C0%7C0%7C638066238375320482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=6SPsdFU3Qtv6zJW0F%2BJPAwQiJ%2BNoEetiinj73FDyhA8%3D&reserved=0>
Randy Villanueva
Sr. Dynamics Consultant
***@***.******@***.***> | (905) 907-3610<tel:(905)%20907-3610>
926 Nashville Rd., Vaughan ON L0J 1C0
[Twitter]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2F360visibility&data=05%7C01%7Cballen%40360visibility.com%7C508e25c1889d4f6cf6e008dadddcf62b%7C0815a0a621fd4467a0ad296bc115d5f2%7C0%7C0%7C638066238375320482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=1cMMvZl8dQl1Ep%2Bb%2FxPSgggT1q5kFF%2FCk1b2xyQQXoY%3D&reserved=0>[LinkedIn]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2F360-visibility&data=05%7C01%7Cballen%40360visibility.com%7C508e25c1889d4f6cf6e008dadddcf62b%7C0815a0a621fd4467a0ad296bc115d5f2%7C0%7C0%7C638066238375320482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=MLAXZ4VmmKK3aT3yhGrz7tGHcc4m%2BAP2JYSUwBqRMQg%3D&reserved=0>[YouTube]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2F360visibilityinc&data=05%7C01%7Cballen%40360visibility.com%7C508e25c1889d4f6cf6e008dadddcf62b%7C0815a0a621fd4467a0ad296bc115d5f2%7C0%7C0%7C638066238375320482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=F7ub0nWaCn3pzYvjgkkXBRq6Ng9b455fcCt6cpeYakY%3D&reserved=0>[Facebook]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2F360Vis%2F&data=05%7C01%7Cballen%40360visibility.com%7C508e25c1889d4f6cf6e008dadddcf62b%7C0815a0a621fd4467a0ad296bc115d5f2%7C0%7C0%7C638066238375320482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=v%2BWnX3NVcJihSrqT3vJHBzY8RakVghb%2F6ZEj4Rd3l3I%3D&reserved=0>[Instagram]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.instagram.com%2F360_visibility%2F&data=05%7C01%7Cballen%40360visibility.com%7C508e25c1889d4f6cf6e008dadddcf62b%7C0815a0a621fd4467a0ad296bc115d5f2%7C0%7C0%7C638066238375320482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=1BznTd4wIeOiI5s4peICEYASIQP%2Fo0eOAY3SRYry1wQ%3D&reserved=0>
www.360visibility.com<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.360visibility.com%2F%3Futm_source%3Demail-signature&data=05%7C01%7Cballen%40360visibility.com%7C508e25c1889d4f6cf6e008dadddcf62b%7C0815a0a621fd4467a0ad296bc115d5f2%7C0%7C0%7C638066238375320482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=6SPsdFU3Qtv6zJW0F%2BJPAwQiJ%2BNoEetiinj73FDyhA8%3D&reserved=0>
My working hours may not be your working hours. Please do not feel obligated to reply outside of your normal work schedule.
[https://360emailsignatures.blob.core.windows.net/pictures/email-signature-banner.jpg]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.360visibility.com%2Femail-signature-banner%2F%3Futm_source%3Demail-signature&data=05%7C01%7Cballen%40360visibility.com%7C508e25c1889d4f6cf6e008dadddcf62b%7C0815a0a621fd4467a0ad296bc115d5f2%7C0%7C0%7C638066238375320482%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=VnJ%2F6DjV40%2BLuZYi63xeMYJEAzswWtRzWV4SVRhMFIU%3D&reserved=0>

**Comment by JesperSchulz** [comment]
The merge to 21.x was completed 2 hours ago 🥳 The changes will release with 21.3.

**Comment by rvillanueva360** [comment]
Thanks Jesper.

Were you able to cover this as well?
https://github.com/microsoft/ALAppExtensions/issues/20512

Cheers,

[360 Visibility]<https://www.360visibility.com/?utm_source=email-signature>
Randy Villanueva
Sr. Dynamics Consultant
***@***.******@***.***> | (905) 907-3610<tel:(905)%20907-3610>
926 Nashville Rd., Vaughan ON L0J 1C0
[Twitter]<https://twitter.com/360visibility>[LinkedIn]<https://www.linkedin.com/company/360-visibility>[YouTube]<https://www.youtube.com/user/360visibilityinc>[Facebook]<https://www.facebook.com/360Vis/>[Instagram]<https://www.instagram.com/360_visibility/>
www.360visibility.com<https://www.360visibility.com/?utm_source=email-signature>
My working hours may not be your working hours. Please do not feel obligated to reply outside of your normal work schedule.
[https://360emailsignatures.blob.core.windows.net/pictures/email-signature-banner.jpg]<https://www.360visibility.com/email-signature-banner/?utm_source=email-signature>

**Comment by JesperSchulz** [comment]
That one will ship with 21.3 as well, yes.
