### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - UpdateBuyFromCont

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#20521]
Please make function UpdateBuyFromCont externally available.

```
procedure UpdateBuyFromCont(VendorNo: Code[20])
var
    ContBusRel: Record "Contact Business Relation";
    Vend: Record Vendor;
    OfficeContact: Record Contact;
    OfficeMgt: Codeunit "Office Management";
begin
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47832.
