### ISSUE TITLE
[Event Request] Codeunit 1100 - Cost Account Mgt - OnGetCostTypesFromChartOfAccountsOnBeforeConfirm

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20528]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnGetCostTypesFromChartOfAccountsOnBeforeConfirm` in Codeunit 1100 Cost Account Mgt with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnGetCostTypesFromChartOfAccountsOnBeforeConfirm(var IsHandled: Boolean)
begin
end;
```
which would be called as follows in `GetCostTypesFromChartOfAccount`:
```AL
procedure GetCostTypesFromChartOfAccount()
// >>>> New >>>>>>>>>>>>>>>>
var
    IsHandled: Boolean;
// <<<< New <<<<<<<<<<<<<<<<
begin
    // >>>> New >>>>>>>>>>>>>>>>
    IsHandled := false;
    OnGetCostTypesFromChartOfAccountsOnBeforeConfirm(IsHandled);
    if not IsHandled then
    // <<<< New <<<<<<<<<<<<<<<<
        if not Confirm(Text000, true) then
            Error('');
    GetCostTypesFromChartDirect;
    IndentCostTypes(true);
    Message(Text003, NoOfGLAcc, RecsCreated)
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47832.
