### ISSUE TITLE
[Event Request]Table 167 Job - OnBeforeSellToCustomerNoUpdated

### ISSUE THREAD

**Issue by frivadulla** [microsoft/ALAppExtensions#20523]
Hello everyone,

it could be possible to change the parameter xJob to a reference one?. It has been changed on the same event at "Bill-to Customer No" #19282

Actual implementation

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeSellToCustomerNoUpdated(var Job: Record Job; xJob: Record Job; CallingFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;
```

Desired one:

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeSellToCustomerNoUpdated(var Job: Record Job; var xJob: Record Job; CallingFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;
```

Kind regards.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47832.
