### ISSUE TITLE
[Event Request] table 167 Job - OnAfterBillToCustomerNoUpdated

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#20527]
Could you please extend the event OnAfterBillToCustomerNoUpdated with additional parameter:

```
[IntegrationEvent(false, false)]
local procedure OnAfterBillToCustomerNoUpdated(var Job: Record Job; xJob: Record Job; CallingFieldNo: Integer; BillToCustomer: Record Customer)
begin
end;
```

```
            Job."Bill-to Contact No." := '';
            Job."Payment Method Code" := '';
            Job."Payment Terms Code" := '';
        end;

#if not CLEAN20
        OnAfterUpdateBillToCust(Job, BillToCustomer);
#endif
        OnAfterBillToCustomerNoUpdated(Job, xJob, CurrFieldNo, BillToCustomer);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47832.
