### ISSUE TITLE
[Event Request] Table Sales Header - OnCreateDimOnBeforeUpdateLines

### ISSUE THREAD

**Issue by MarekBusseDXC** [microsoft/ALAppExtensions#20526]
Please add a new event or add var IsHandled to OnCreateDimOnBeforeUpdateLines event to skip the confirmation (in BC20 we don't have that confirmation):
<img width="571" alt="image" src="https://user-images.githubusercontent.com/115068851/194009531-a78dc4b8-f708-4c1a-8ddc-9ad5f2783837.png">

**Comment by SlawekDXC** [comment]
Hi, I have additional comment to consider:
Is it OK to put a Confirm inside such low-level function? 
This can be executed during some business processes (posting?). Then it pauses execution with several tables locked. If user go for coffee at that time, system is stuck until he returns. Or maybe something changed in confirm behaviour compared to older versions?
