### ISSUE TITLE
Wrong Parameter in OnBeforeCheckPromisedDeliveryDate()

### ISSUE THREAD

**Issue by msomp** [microsoft/ALAppExtensions#20540]
The Event Publisher OnBeforeCheckPromisedDeliveryDate() in Table 37 "Sales Line"
should have the Sales Line as parameter, not the Sales Header.

```
local procedure CheckPromisedDeliveryDate()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckPromisedDeliveryDate(SalesHeader, IsHandled);
        if IsHandled then
            exit;

        if ("Requested Delivery Date" <> xRec."Requested Delivery Date") and ("Promised Delivery Date" <> 0D) then
            Error(Text028, FieldCaption("Requested Delivery Date"), FieldCaption("Promised Delivery Date"));
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47832.
