### ISSUE TITLE
[Event Request] - Report 393 Suggest Vendor Payments - OnBeforeIncludeVendor()

### ISSUE THREAD

**Issue by pseyechlo** [microsoft/ALAppExtensions#20550]
Hello, please can you add an OnBeforeIncludeVendor event to the IncludeVendor procedure.
A previous customisation we have done allows us to exclude transactions from the report, but we also want to exclude them from the VendorBalance value when deciding if a vendor should be included..
This will allow us to recalculate the VendorBalance and optionally change the test that that IncludeVendor does.
The new event would be needed from BC19.2 onwards.

```
local procedure IncludeVendor(Vendor: Record Vendor; VendorBalance: Decimal) Result: Boolean
// >>>> New >>>>>>>>>>>>>>>>
var
    IsHandled: Boolean;
// <<<< New <<<<<<<<<<<<<<<<
begin
    // >>>> New >>>>>>>>>>>>>>>>
    OnBeforeIncludeVendor(Vendor, VendorBalance, Result, IsHandled);
    if IsHandled then
        exit;
    // <<<< New <<<<<<<<<<<<<<<<

    Result := VendorBalance > 0;

    OnAfterIncludeVendor(Vendor, VendorBalance, Result);
end;

// >>>> New >>>>>>>>>>>>>>>>
[IntegrationEvent(false, false)]
local procedure OnBeforeIncludeVendor(Vendor: Record Vendor; var VendorBalance: Decimal; var Result: Boolean; var IsHandled: Boolean)
begin
end;
// <<<< New <<<<<<<<<<<<<<<<
```

Thank you,
Andy

**Comment by Vadim-Stepanenko** [comment]
What can you do with this that you cannot do with **OnAfterIncludeVendor** already? Seems redundant.

**Comment by pseyechlo** [comment]
Hi,

The VendorBalance parameter for OnAfterIncludeVendor is not a var, so you can’t change it, which is what we want to do.
You could just change the parameter to be a var which would be fine for us, but that might break other peoples code.

Regards,
Andy

**Comment by AlexanderYakunin** [comment]
I see not reason to change VendorBalance variable for our code, as it is internal variable used in the cycle. This value will be lost anyway. If you need to adjust Vendor Balance to decide if you need include vendor or not, you should do this in your extension code and simply assign Result value. Closing this request.
