### ISSUE TITLE
Enum Value Caption Displayed Wrong When Containing Comma

### ISSUE THREAD

**Issue by juliebuusj** [microsoft/ALAppExtensions#20567]
If you have an enum value caption translation with a comma, the value is displayed wrong in the web client.

We have observed the following:

We have an enum that is extended by two different apps.

One app extends the enum with this value:
value(50017; "Volume Threshold")
{
    Caption = 'Volume Threshold';
}

The translation for this value contains a comma "Volume, trappetrin".

Another app extends the enum with e.g. this value:
value(60000; "Change Approval Status")
{
    Caption = 'Change Approval Status';
}

The translation for this value is "Skift godkendelsesstatus".

When a record is created with the value "Change Approval Status", it is displayed with the value " trappetrin".
This indicates that the value is correct in the database, but is displayed in a wrong manner when the caption is retrieved.
It also indicates it is caused by the comma in the caption.
When removing the comma from the translation, the issue no longer occurs.

This has been observed in the following version of Business Central:
DK Business Central 20.3 (platform 20.0.42653.43007 + program 20.3.42673.43026)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
