### ISSUE TITLE
[Event request] Event OnBeforeTestNoOpenEntriesExist in OnValidateTrigger in Field 8, "Base unit of measure" in Table 27 Item

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#20562]
Hi

Can you please add the event OnBeforeTestNoOpenEntriesExist in OnValidateTrigger in Field 8, "Base Unit of Measure" in Table 27, Item.

```
var
    TempItem: Record Item temporary;
    UnitOfMeasure: Record "Unit of Measure";
    IsHandled: Boolean;
    // >>>>>>>>>>
    SkipTest: Boolean;
    // <<<<<<<<<<
begin
    // >>>>>>>>>>
    SkipTest := false;
    // <<<<<<<<<<
    IsHandled := false;
....
// >>>>>>>>>>
OnBeforeTestNoOpenEntriesExist(Rec, SkipTest);
if not SkipTest then
    // <<<<<<<<<<
    TestNoOpenEntriesExist(FieldCaption("Base Unit of Measure"));
```
```
[IntegrationEvent(false, false)]
local procedure OnBeforeTestNoOpenEntriesExist(var Item: Record Item; var SkipTest: Boolean)
begin
end;
```

**Comment by Vadim-Stepanenko** [comment]
This will be inside TestNoOpenEntriesExist instead

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48699.
