### ISSUE TITLE
[Event Request] Table 1107 - Cost Allocation Target - OnCalcPercentOnAfterSetFilters

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20563]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnCalcPercentOnAfterSetFilters` in Table 1107  Cost Allocation Target with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnCalcPercentOnAfterSetFilters(var CostAllocationTarget: Record "Cost Allocation Target"; var Rec: Record "Cost Allocation Target")
begin
end;
```
which would be called as follows in `CalcPercent`:
```AL
local procedure CalcPercent()
var
    CostAllocationTarget: Record "Cost Allocation Target";
    PctTotal: Decimal;
    TotalShare: Decimal;
begin
    with CostAllocationTarget do begin
        SetRange(ID, Rec.ID);
        SetFilter("Line No.", '<>%1', Rec."Line No.");
        // >>>> New >>>>>>>>>>>>>>>>
        OnCalcPercentOnAfterSetFilters(CostAllocationTarget, Rec);
        // <<<< New <<<<<<<<<<<<<<<<
        CalcSums(Share);
        TotalShare := Share + Rec.Share;
...
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48068.
