### ISSUE TITLE
[Event Change Request] table 77 "Report Selections"

### ISSUE THREAD

**Issue by chrischbo** [microsoft/ALAppExtensions#20565]
Hi,

is it possible to get access to the passed Record Variant? We would like to add/modify filters to the passed variable.

Old:
`[IntegrationEvent(false, false)]
    local procedure OnBeforePrintDocument(TempReportSelections: Record "Report Selections" temporary; IsGUI: Boolean; RecVarToPrint: Variant; var IsHandled: Boolean)`

New:
`[IntegrationEvent(false, false)]
    local procedure OnBeforePrintDocument(TempReportSelections: Record "Report Selections" temporary; IsGUI: Boolean; **var** RecVarToPrint: Variant; var IsHandled: Boolean)`

Thanks in advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47832.
