### ISSUE TITLE
[Event Request] Table 1106 - Cost Allocation Source - OnBeforeValidateCostObjectCode

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20560]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnBeforeValidateCostObjectCode` in Table 1106 Cost Allocation Source with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeValidateCostObjectCode(var CostAllocationSource: Record "Cost Allocation Source"; var IsHandled: Boolean)
begin
end;
```
which would be called as follows in the OnValidate trigger of field `7 - Cost Object Code`:
```AL
trigger OnValidate()
// >>>> New >>>>>>>>>>>>>>>>
var
    IsHandled: Boolean;
// <<<< New <<<<<<<<<<<<<<<<
begin
    // >>>> New >>>>>>>>>>>>>>>>
    OnBeforeValidateCostObjectCode(Rec, IsHandled);
    if IsHandled then
        exit;
    // <<<< New <<<<<<<<<<<<<<<<

    if ("Cost Center Code" <> '') and ("Cost Object Code" <> '') then
        Error(Text003);
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48068.
