### ISSUE TITLE
[Event Request] Table 5612 "FA Depreciation Book" - OnValidateNoofDepreciationMonthsOnAfterCalcShowDeprMethodError

### ISSUE THREAD

**Issue by kratibaiwal** [microsoft/ALAppExtensions#20570]
Hi, Can you please add an event OnValidateNoofDepreciationMonthsOnAfterCalcShowDeprMethodError in the OnValidate trigger of field "No. of Depreciation Months". A similar event is already present in the OnValidate trigger of "No. of Depreciation Months" and "Depreciation Ending Date".

        field(7; "No. of Depreciation Months"; Decimal)
        {
            BlankZero = true;
            Caption = 'No. of Depreciation Months';
            DecimalPlaces = 2 : 8;
            MinValue = 0;

            trigger OnValidate()
            var
                DeprBook2: Record "Depreciation Book";
                IsHandled: Boolean;
                //>>>>>>> New
                ShowDeprMethodError: Boolean;
                //<<<<<<< New
            begin
                DeprBook2.Get("Depreciation Book Code");
                OnBeforeValidateNoOfDeprMonths("FA No.", DeprBook2, IsHandled);
                if not IsHandled then
                    if DeprBook2."Fiscal Year 365 Days" then
                        Error(FiscalYear365Err);

                TestField("Depreciation Starting Date");
                ModifyDeprFields;

                //>>>>>>> New event
                ShowDeprMethodError := ("No. of Depreciation Years" <> 0) and not LinearMethod();
                OnValidateNoofDepreciationMonthsOnAfterCalcShowDeprMethodError(Rec, ShowDeprMethodError);
                if ShowDeprMethodError then
                    DeprMethodError;
                //<<<<<<< New event

                "No. of Depreciation Years" := Round("No. of Depreciation Months" / 12, 0.00000001);
                AdjustLinearMethod("Straight-Line %", "Fixed Depr. Amount");
                "Depreciation Ending Date" := CalcEndingDate;
            end;
        }

    [IntegrationEvent(false, false)]
    local procedure OnValidateNoofDepreciationMonthsOnAfterCalcShowDeprMethodError(var FADepreciationBook: Record "FA 
    Depreciation Book"; var ShowDeprMethodError: Boolean)
    begin
    end;

**Comment by AleksandricMarko** [comment]
Already implemented.
