### ISSUE TITLE
[Event Request] OnBeforeShowDimension

### ISSUE THREAD

**Issue by AMJSMEDDAH** [microsoft/ALAppExtensions#20571]
Hi,

On Table 36 - Sales Header & 37 - Sales Line, we have the possibility to extends the ShowDimension function with the "OnBeforeShowDimensions" event.

Exemple "Table Sales Header"
![image](https://user-images.githubusercontent.com/105815056/194765938-9e765dad-1674-413f-b172-95ed59e1828a.png)

Could you please add the same event in other table where the ShowDimension function exist ? Like on "Assembly Header", "Assembly Line", "Sales Header Archive" ...

Exemple "Table Sales Header Archive"
![image](https://user-images.githubusercontent.com/105815056/194766184-307aa7dd-f618-4a6e-b96f-7a7b8ca16971.png)

For now we have to extend all related page with hiding the button "Dimensions" and implementing the same one with our customization.

Best Rergards,

**Comment by AlexanderYakunin** [comment]
Please explain why do you need this? What is wrong with our Dimension implementation?

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot process such requests which affect so many application objects. We need detailed justification to confirm why this is needed.
