### ISSUE TITLE
[Event Request] Table 7001 "Price List Line" - OnBeforeIsAllowedEditingActivePrice

### ISSUE THREAD

**Issue by jthoerner-tso** [microsoft/ALAppExtensions#20575]
Hello BC Team,

we would like to have an event to allow editing on selected price lists in certain situation.

```
    local procedure IsAllowedEditingActivePrice() EditingAllowed: Boolean;
    var
        PriceListManagement: Codeunit "Price List Management";
        IsHandled: Boolean;
    begin
     >>>>>>>>>>>NEW>>>>>>>>>   
     OnBeforeIsAllowedEditingActivePrice(IsHandled, EditingAllowed);
        if IsHandled then
            exit(EditingAllowed);
     <<<<<<<<<<<NEW<<<<<
        exit(PriceListManagement.IsAllowedEditingActivePrice("Price Type"));
    end;
```

```
    [BusinessEvent(true)]
    local procedure OnBeforeIsAllowedEditingActivePrice(var IsHandled: Boolean; var EditingAllowed: Boolean)
    begin
    end;
```

**Comment by Vadim-Stepanenko** [comment]
There is already **OnAfterIsAllowedEditingActivePrice** in **PriceListManagement.IsAllowedEditingActivePrice**, please use that instead.

**Comment by jthoerner-tso** [comment]
Hello,

not quite. I agree, this post looks at first glance like a duplicate to  #20500 and probably in most cases it is. 

The use case of both events are similar but not the same.

My event additionally contains with "[BusinessEvent(true)]" the original price list line as sender, and does not refer to the PriceType alone.
