### ISSUE TITLE
Request to add DocumentNo as a parameter to procedure IsOnBeforeCheckBlockedCustHandled in the Customer table

### ISSUE THREAD

**Issue by stephanpl** [microsoft/ALAppExtensions#20573]
In order to allow some exceptions to the Customer Blocked field, based on a field in the sales header we would like to have the document number of the sales header added to procedure IsOnBeforeCheckBlockedCustHandled. And also, to the event publisher OnBeforeCheckBlockedCust that is raised in this procedure. Something like this:

    local procedure IsOnBeforeCheckBlockedCustHandled(Customer: Record Customer; Source: Option Journal,Document; DocType: Enum "Gen. Journal Document Type"; DocumentNo: Code[20]; Shipment: Boolean; Transaction: Boolean) IsHandled: Boolean
    begin
        OnBeforeCheckBlockedCust(Customer, Source, DocType.AsInteger(), DocumentNo, Shipment, Transaction, IsHandled)
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckBlockedCust(Customer: Record Customer; Source: Option Journal,Document; DocType: Option; DocumentNo: Code[20]; Shipment: Boolean; Transaction: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by stephanpl** [comment]
If possible, we would like to know if this will be resolved and in what timeframe this could be realized

**Comment by Vadim-Stepanenko** [comment]
This will either get to the next minor or to the next after it.

**Comment by Vadim-Stepanenko** [comment]
@stephanpl we are not able to proceed with this request until you provide the info.

**Comment by stephanpl** [comment]
@Vadim-Stepanenko, in order to allow exceptions for the Customer Blocked field on sales document level we want to add a Blocked field on the Sales Header. This field will overrule the Blocked field on the Customer level. In order not to duplicate all the code where the functions CheckBlockedCustOnDocs  and CheckBlockedCustOnJnls are called, we will need these code changes

**Comment by stephanpl** [comment]
@Vadim-Stepanenko Thank you for clarifying this. Yes, that is the desired call for **IsOnBeforeCheckBlockedCustHandled**
Current code:
        if IsOnBeforeCheckBlockedCustHandled(Cust2, Source::Document, DocType, Shipment, Transaction) then
            exit;
 Proposed change:
         if IsOnBeforeCheckBlockedCustHandled(Cust2, Source::Document, DocType, DocumentNo, Shipment, Transaction) then
            exit;

And for **CheckBlockedCustOnDocs**
Current Code:
Cust.CheckBlockedCustOnDocs(Cust, "Document Type", true, true);
Proposed change:
Cust.CheckBlockedCustOnDocs(Cust, "Document Type", "No.", true, true);


And for **CheckBlockedCustOnJnls**
Current Code:
Cust.CheckBlockedCustOnJnls(Cust, "Document Type", true);

Proposed change:
Cust.CheckBlockedCustOnJnls(Cust, "Document Type", "Document No.", true);
