### ISSUE TITLE
Indirect permission on codeunit 703 "Find Record Management"

### ISSUE THREAD

**Issue by tinkun1** [microsoft/ALAppExtensions#20587]
Permissions = Tabledata "G/L Entry" = r;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51686.
