### ISSUE TITLE
[Event-Change Request] codeunit 12 "Gen. Jnl.-Post Line" - OnAfterInsertVATEntry

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#20583]
Dear ALAppExtensions team,

Through this issue we would like to request the inclusion of the sender in Codeunit 12 `Gen. Jnl.-Post Line` Eventpublisher `OnAfterInsertVATEntry`.

```AL
[IntegrationEvent(true, false)]    <<<<<<<
local procedure OnAfterInsertVATEntry(GenJnlLine: Record "Gen. Journal Line"; VATEntry: Record "VAT Entry"; GLEntryNo: Integer; var NextEntryNo: Integer; var TempGLEntryVATEntryLink: Record "G/L Entry - VAT Entry Link" temporary)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47942.
