### ISSUE TITLE
Indirect permission on table 93 "Vendor Posting Group"

### ISSUE THREAD

**Issue by tinkun1** [microsoft/ALAppExtensions#20586]
Permissions = Tabledata "G/L Account" = r;

**Comment by AlexanderYakunin** [comment]
Why do you need indirect permissions here? You should simply add permissions for table G/L Account to users who can define accounts for posting group.

**Comment by tinkun** [comment]
Because in the posting process the function GetInvRoundingAccount is executed. And the User should not have the permission to read GL Accounts..
