### ISSUE TITLE
[Event-Change Request] codeunit 12 "Gen. Jnl.-Post Line" - OnAfterCalcPmtTolerance

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#20585]
Dear ALAppExtensions team,

through this issue we would like to request a change of event publisher `OnAfterCalcPmtTolerance` in codeunit 12 `Gen. Jnl.-Post Line` from:

```AL
[IntegrationEvent(false, false)]
local procedure OnAfterCalcPmtTolerance(DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; OldCVLedgEntryBuf2: Record "CV Ledger Entry Buffer"; var PmtTol: Decimal; var PmtTolLCY: Decimal)
begin
end;
```

to:

```AL
[IntegrationEvent(false, false)]
local procedure OnAfterCalcPmtTolerance(var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; OldCVLedgEntryBuf2: Record "CV Ledger Entry Buffer"; var PmtTol: Decimal; var PmtTolLCY: Decimal)
begin
end;
```

adding the `var` tag to the `DtldCVLedgEntryBuf` parameter.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47942.
