### ISSUE TITLE
[Event Request] table "Time Sheet Line" OnAfterShowLineDetails

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#20599]
Hello,

Please add a new event in table 951 "Time Sheet Line" function ShowLineDetails
OnAfterShowLineDetails(var TimeSheetLine: Record "Time Sheet Line";var IsHandled: Boolean)

Raise after check types before error with if not Handled then error

Thank you

**Comment by AleksandricMarko** [comment]
Implemented as OnBeforeShowLineDetails(Rec, IsHandled, ManagerRole);
