### ISSUE TITLE
Report 6520 "Item Tracing Specification"

### ISSUE THREAD

**Issue by RSenaMarti** [microsoft/ALAppExtensions#20595]
Hello, a customer has asked us to extend the number of available fields that can be viewed in the 6520 report. Currently only 8 fields are available and he needs some more. I think it would be interesting for everyone to extend up to the dimension of the arrays and make them available up to 11.
I am thinking of making an extension report and would appreciate if the following variables could be declared as protected. 

var
        TempTrackEntry: Record "Item Tracing Buffer" temporary;
        NoOfRecords: Integer;
        HeaderText: array[11] of Text[50];
        BodyText: array[11] of Text[50];
        FieldCaption: array[11] of Text[50];
        FldNo: array[11] of Integer;

**change to**

**protected var**
        TempTrackEntry: Record "Item Tracing Buffer" temporary;
        NoOfRecords: Integer;
        HeaderText: array[11] of Text[50];
        BodyText: array[11] of Text[50];
        FieldCaption: array[11] of Text[50];
        FldNo: array[11] of Integer;

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47978.
