### ISSUE TITLE
Report 5600 - Request for Protected Var - Variable HeadLineText

### ISSUE THREAD

**Issue by josalm** [microsoft/ALAppExtensions#20600]
Hello,

In report 5600 "Fixed Asset - Analysis"could you change the scope of the following variable to protected?

protected var
   HeadLineText: array[5] of Text[50];
   
Best Regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47978.
