### ISSUE TITLE
Table 37- Sales Line - local procedures TestJobPlanningLine / UpdateUnitPriceByField - change to global / protected

### ISSUE THREAD

**Issue by Nethernexus** [microsoft/ALAppExtensions#20609]
Hi ALAppExtensions Team,
in the OnValidate Trigger of Quantity (Base) you can exit by isHandled. But you cannot call procedures that are called afterwards by yourself, because they are local. 
Is it possible to change them to protected / global?

Thanks and bye,
Karsten

Code:

            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                IsHandled := false;
                OnBeforeValidateQuantityBase(Rec, xRec, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;

                TestJobPlanningLine();
                TestField("Qty. per Unit of Measure", 1);

                if "Quantity (Base)" <> xRec."Quantity (Base)" then
                    PlanPriceCalcByField(FieldNo("Quantity (Base)"));

                Validate(Quantity, "Quantity (Base)");
       
                UpdateUnitPriceByField(FieldNo("Quantity (Base)"));
            end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47978.
