### ISSUE TITLE
[EventRequest] codeunit 5870 "Calculate BOM Tree" in procedure TraverseTree

### ISSUE THREAD

**Issue by extranrollo** [microsoft/ALAppExtensions#20616]
I need an event to Skip those lines

 ParentBOMBuffer."Able to Make Parent" :=
                      CalcMinAbleToMake(IsFirst, ParentBOMBuffer."Able to Make Parent", "Able to Make Parent");
ParentBOMBuffer."Able to Make Top Item" :=
                      CalcMinAbleToMake(IsFirst, ParentBOMBuffer."Able to Make Top Item", "Able to Make Top Item");

The Event should be like this 

![grafik](https://user-images.githubusercontent.com/36401349/195675575-0e6bc945-e0af-4e8d-bc51-40cccfbee5e7.png)

![grafik](https://user-images.githubusercontent.com/36401349/195675957-40416690-19cb-4290-807b-d6d2360954f4.png)

**Comment by AlexanderYakunin** [comment]
Can you provide full change? Including code for additional procedures you've added?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53591.
