### ISSUE TITLE
[Protected var Request] - report 7306 "Get Inbound Source Documents"

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#20614]
Hi Team,

we need to access following global variables in a report extending "Get Inbound Source Documents". Could they be declared as protected vars?

- WhseWkshTemplateName: Code[10];
- WhseWkshName: Code[10];
- LocationCode: Code[10];
- LineCreated: Boolean;
- HideDialog: Boolean;

``` AL
report 7306 "Get Inbound Source Documents"
{
 [...]
    trigger OnPreReport()
    begin
        LineCreated := false;
    end;

    var
       Text000: Label 'There are no Warehouse Worksheet Lines created.';
       WhseWkshCreate: Codeunit "Whse. Worksheet-Create";
    // Change var declaration  --
    //   WhseWkshTemplateName: Code[10];
    //   WhseWkshName: Code[10];
    //   LocationCode: Code[10];
    //   LineCreated: Boolean;
    //   HideDialog: Boolean;

    protected var
        WhseWkshTemplateName: Code[10];
        WhseWkshName: Code[10];
        LocationCode: Code[10];
        LineCreated: Boolean;
        HideDialog: Boolean;
    // --

    procedure SetHideDialog(NewHideDialog: Boolean)
    begin
        HideDialog := NewHideDialog;
    end;
   [...]
}
```

Thanks in advance,
Christian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47978.
