### ISSUE TITLE
"Link Advance Letter" action not working

### ISSUE THREAD

**Issue by Michal-z-Moravy** [microsoft/ALAppExtensions#20611]
The action "Link Advance Letter" seems to always results in 
![image](https://user-images.githubusercontent.com/115717166/195613208-7bdee78d-e16c-41cf-bb46-4cc936734f8a.png)

That is because in https://github.com/microsoft/ALAppExtensions/blob/6228f5f16ca84173df68f969410263095feffeca/Apps/CZ/AdvancePaymentsLocalization/app/Src/Codeunits/SalesAdvLetterManagement.Codeunit.al#L234 the return value of the inner procedure is not returned by the outer procedure, so in https://github.com/microsoft/ALAppExtensions/blob/6228f5f16ca84173df68f969410263095feffeca/Apps/CZ/AdvancePaymentsLocalization/app/Src/Codeunits/SalesAdvLetterManagement.Codeunit.al#L213 the InsertedEntryNo is always 0.

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
