### ISSUE TITLE
[Event Request] Page 1132 - Cost Bdgt. per Center Matrix - OnAfterUpdateAmount

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20618]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnAfterUpdateAmount` in Page 1132 Cost Bdgt. per Center Matrix with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnAfterUpdateAmount(var CostType: Record "Cost Type"; var MATRIX_CellData: array[12] of Decimal; ColumnID: Integer)
begin
end;
```
which would be called as follows in `UpdateAmount`:
```AL
local procedure UpdateAmount(ColumnID: Integer)
begin
    SetFilters(ColumnID);
    if GetRangeMin("Date Filter") = 0D then
        Error(Text000);
    CalcFields("Budget Amount");
    Validate("Budget Amount", MATRIX_CellData[ColumnID]);
    // >>>> New >>>>>>>>>>>>>>>>
    OnAfterUpdateAmount(Rec, MATRIX_CellData, ColumnID);
    // <<<< New <<<<<<<<<<<<<<<<
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48068.
