### ISSUE TITLE
[Request for external] SII module objects for Spanish localization

### ISSUE THREAD

**Issue by deadmouse** [microsoft/ALAppExtensions#20615]
I would like these procedures not having OnPrem scope in the Spanish localization:

- codeunit 10756 "SII Management"
    * GetSIIStyle
    * GetNoTaxablePurchAmount
    * GetNoTaxableSalesAmount
    * SIIStateDrilldown
    * IsVATEntryCashFlowBased
    * IsDetailedLedgerCashFlowBased
    * IsLedgerCashFlowBased
    * IsIntracommunity
    * FindVatEntriesFromLedger
    * FindOriginalLedgerFromDetailedPaymentLedger
    * FindOriginalLedgerFromPaymentLedger
    * FindVatEntriesReferringToDocLedger
    * FindDetailedPaymentApplicationLedgerFromLedger
    * FindDetailedLedgerFromVatEntry
    * FindLedgerFromVatEntry
    * FindPaymentDetailedCustomerLedgerEntries
    * FindPaymentDetailedVendorLedgerEntries
    * NoTaxableEntriesExistPurchase
    * NoTaxableEntriesExistSales
    * DoesPaymentDetailedLedgerCloseInvoice
    * DoesPaymentLedgerCloseInvoice
    * CountryIsLocal
    * CountryAndVATRegNoAreLocal
    * IsDomesticCustomer
    * CustomerIsIntraCommunity
    * VendorIsIntraCommunity
    * CombineOperationDescription
    * SplitOperationDescription
    * CharIsCapitalLetter
    * IsAllowedSalesInvType
    * IsAllowedServInvType
    * Run347DeclarationToGenerateCollectionsInCash
- table 10740 "No Taxable Entry"
    * FilterNoTaxableEntry
    * FilterNoTaxableEntriesForSource
    * InitFromGenJnlLine
    * InitFromServiceDocument
    * InitFromVendorEntry
    * InitFromCustomerEntry
    * Reverse
    * Update
- codeunit 10750 "SII XML Creator"
    * FormatDate
    * FormatNumber
- codeunit 10753 "SII Job Upload Pending Docs."
    * GenJnlLineHasSIIDocType
    * HandlePendingEntries

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51281.
