### ISSUE TITLE
[Exposure Request] [DE] report 11004 "Vendor Total-Balance" - protected variables

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#20629]
Please set varibles PeriodEndBalance and EndBalanceType to protected in report 11004 "Vendor Total-Balance" - german localization.

```
protected var
    PeriodEndBalance: Decimal;
    EndBalanceType: Option " ",Debit,Credit;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47978.
