### ISSUE TITLE
[Event Request] Codeunit 1990 "Guided Experience" - OnBeforeInsertAssistedSetup

### ISSUE THREAD

**Issue by Sameer-Utekar** [microsoft/ALAppExtensions#20631]
Hello colleagues,

We would like to request an event in Codeunit 1990 "Guided Experience".
We want the ability to check/change some parameters of the assisted setups before inserting
For example, We want to change the group for the assisted setups

We believe this requirement can be achieved by implementing the following event:

Event signature:

```
   [IntegrationEvent(false, false)]
    internal procedure OnBeforeInsertAssistedSetup()
    begin
    end;
```

**Comment by AlexanderYakunin** [comment]
Hello!

Not sure I understand how you are going to change any parameters in event without any parameters? And event cannot be internal, it must be local.

**Comment by Sameer-Utekar** [comment]
Yes, I will need the parameter as assisted setup object itself.

Regards,
Sameer Suresh Utekar
[cid:c1dfe6f7-d414-49b0-97bf-355f0bf03d3b]
________________________________

**Comment by Mike-1984** [comment]
Hello @AlexanderYakunin, we have created new request regarding this issue.
Please consider closing this issue and check the new request:

#https://github.com/microsoft/ALAppExtensions/issues/20870
