### ISSUE TITLE
[Event Request] report 780 "Certificate of Supply" - protected variables

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#20634]
Please set varibles TempServiceShipmentHeader and TempServiceShipmentLine to protected in report 780 "Certificate of Supply"
```
protected var
    TempServiceShipmentHeader: Record "Service Shipment Header" temporary;
    TempServiceShipmentLine: Record "Service Shipment Line" temporary;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 47978.
