### ISSUE TITLE
[Protected var request] Report 6 "Trial Balance" Spanish Version

### ISSUE THREAD

**Issue by aablasco** [microsoft/ALAppExtensions#20642]
Some of our customers requested us to change format or add more data to the Report 6 "Trial Balance" (Spanish Version).
In order to do it using Report Extensions instead of replacing the report, we need to access the global variables used on the Request Page.

Please, change the following variables to protected:

```al
    protected var
        PrintAllHavingBal: Boolean;
        PrintAmountsInAddCurrency: Boolean;
        AcumBalance: Boolean;
        CloseEntries: Boolean;
        OpenEntries: Boolean;
```

**Comment by JesperSchulz** [comment]
Was fixed in version 22.
