### ISSUE TITLE
[Event Parameter Change] Codeunit 80 Sales Post - procedure PostItemJnlLinePrepareJournalLine - event OnPostItemJnlLineOnAfterCopyTrackingFromSpec

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#20645]
We would like the parameter/-s IsATO added to the following event.

Codeunit 80 Sales Post - procedure PostItemJnlLinePrepareJournalLine - event OnPostItemJnlLineOnAfterCopyTrackingFromSpec

Original:

```
OnPostItemJnlLineOnAfterCopyTrackingFromSpec(ItemJnlLine, SalesLine, QtyToBeShipped);

[IntegrationEvent(false, false)]
local procedure OnPostItemJnlLineOnAfterCopyTrackingFromSpec(var ItemJnlLine: Record "Item Journal Line"; SalesLine: Record "Sales Line"; QtyToBeShipped: Decimal)
begin
end;
```

Change:

```
OnPostItemJnlLineOnAfterCopyTrackingFromSpec(ItemJnlLine, SalesLine, QtyToBeShipped, IsATO); // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnPostItemJnlLineOnAfterCopyTrackingFromSpec(var ItemJnlLine: Record "Item Journal Line"; SalesLine: Record "Sales Line"; QtyToBeShipped: Decimal; IsATO: Boolean) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48091.
