### ISSUE TITLE
New event request for table 472 "Job Queue Entry"

### ISSUE THREAD

**Issue by iaxmartinwagner** [microsoft/ALAppExtensions#20643]
In table 472 "Job Queue Entry" we will need the event

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetUserIDForScheduledTask(var JobQueueEntry: Record "Job Queue Entry"; var IsHandled: Boolean)
    begin
    end;

to omit changing the existing UserID when activating a job queue entry

    procedure ScheduleTask(): Guid
    var
        TaskGUID: Guid;
        IsHandled: Boolean;
        JobTimeout: Duration;
    begin
        CheckRequiredPermissions();
        //>>>>> new code - BEGIN >>>>>
        IsHandled := false;
        OnBeforeSetUserIDForScheduledTask(Rec, IsHandled);
        if not IsHandled then
            //<<<<< new code - END <<<<<
            if "User ID" <> UserId() then begin
                "User ID" := UserId();
                Modify(true);
            end;
        IsHandled := false;
        OnBeforeScheduleTask(Rec, TaskGUID, IsHandled);

Can you add this event, please?

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
