### ISSUE TITLE
[Event Request] Table 1109 - Cost Budget Entry - OnBeforeHandleCostBudgetRegister

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20640]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnBeforeHandleCostBudgetRegister` in Table 1109 Cost Budget Entry with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeHandleCostBudgetRegister(var CostBudgetEntry: Record "Cost Budget Entry"; var CurrRegNo: Integer; var IsHandled: Boolean)
begin
end;
```
which would be called as follows in `HandleCostBudgetRegister`:
```AL
local procedure HandleCostBudgetRegister()
var
    CostBudgetReg: Record "Cost Budget Register";
    // >>>> New >>>>>>>>>>>>>>>>
    IsHandled: Boolean;
    // <<<< New <<<<<<<<<<<<<<<<
begin
    // >>>> New >>>>>>>>>>>>>>>>
    OnBeforeHandleCostBudgetRegister(Rec, CurrRegNo, IsHandled);
    if IsHandled then
        exit;
    // <<<< New <<<<<<<<<<<<<<<<
    if CostBudgetReg.Get(CurrRegNo) then;
    if (CurrRegNo = 0) or (CostBudgetReg."To Cost Budget Entry No." <> "Entry No." - 1) then
        CurrRegNo := CostAccMgt.InsertCostBudgetRegister("Entry No.", "Budget Name", Amount)
    else
        CostAccMgt.UpdateCostBudgetRegister(CurrRegNo, "Entry No.", Amount);
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48068.
