### ISSUE TITLE
[Access Request] page 973 "Time Sheet Card" - Process

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#20646]
Could you please update the scope of the procedure `Process` to at least protected?
```al
//+Change
//-local procedure Process(ActionType: Option Submit,ReopenSubmitted,Approve,ReopenApproved,Reject)
protected procedure Process(ActionType: Option Submit,ReopenSubmitted,Approve,ReopenApproved,Reject)
//-Change
var
    TimeSheetLine: Record "Time Sheet Line";
begin
    FilterAllLines(TimeSheetLine, ActionType);
    OnProcessOnAfterTimeSheetLinesFiltered(TimeSheetLine, ActionType);

    if TimeSheetLine.FindSet() then
        repeat
            TimeSheetApprovalMgt.ProcessAction(TimeSheetLine, ActionType);
        until TimeSheetLine.Next() = 0;
    CurrPage.Update(true);

    OnAfterProcess(Rec, ActionType);
end;
```

**Comment by pri-kise** [comment]
@AlexanderYakunin can you provide any status information on this request?

**Comment by AlexanderYakunin** [comment]
Done 11/08/2022 11:32:15 AM, not sure why it is not closed at this time. 

    protected procedure Process(ActionType: Option Submit,ReopenSubmitted,Approve,ReopenApproved,Reject)
    var
        TimeSheetLine: Record "Time Sheet Line";
    begin
        FilterAllLines(TimeSheetLine, ActionType);
        OnProcessOnAfterTimeSheetLinesFiltered(TimeSheetLine, ActionType);

        if TimeSheetLine.FindSet() then
            repeat
                TimeSheetApprovalMgt.ProcessAction(TimeSheetLine, ActionType);
            until TimeSheetLine.Next() = 0;
        CurrPage.Update(true);

        OnAfterProcess(Rec, ActionType);
    end;
