### ISSUE TITLE
External Table on Onprem BC

### ISSUE THREAD

**Issue by dmendola** [microsoft/ALAppExtensions#20657]
Hi,
i need help about this topic: External Tables are under "Universal Code" Microsoft's rules?

Exatly, if i use an external table for developing on my OnPrem customer, MS sign it as "OUT-Universal Code"?

i need this answer to bring decision about an project.

Thank you for your support!

Have a nice day.

**Comment by dmendola** [comment]
Linked discussion: https://github.com/microsoft/ALAppExtensions/discussions/20622

**Comment by AlexanderYakunin** [comment]
We cannot help you with such questions here, please ask using Yammer for partners
