### ISSUE TITLE
[Event Request] codeunit 9520 "Mail Management" - OnSendMailOrDownloadAfterSending

### ISSUE THREAD

**Issue by gretanorv** [microsoft/ALAppExtensions#20669]
Hello, would it be possible to add OnSendMailOrDownloadAfterSending event to codeunit 9520 "Mail Management", like this: 
 ```al 
     procedure SendMailOrDownload(var TempEmailItem: Record "Email Item" temporary; HideMailDialog: Boolean; EmailScenario: Enum "Email Scenario") 
 ... 
                   exit;
              end;
  
          IsHandled := false;
>         OnSendMailOrDownloadAfterSending(IsHandled); //New Event
          if IsHandled then
              exit;
  
          if IsBackground() then 
 ``` 
 ```al 
 local procedure OnSendMailOrDownloadAfterSending(var IsHandled: Boolean)  
 ```

**Comment by Vadim-Stepanenko** [comment]
This will be **OnAfterIsBackground** instead.

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
