### ISSUE TITLE
Codeunit 80 Sales-Post - Hide Dialog

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#2066]
Hi,
many thanks for implementing HideProgressWindow for suppressing dialogs!
In the code unit 80 there are some Window.Close statements which are not prefixed with "IF NOT HideProcessWindow". According to the help a dialog.lose without dialog.open leads to an error. Has the behavior of the dialog.close changed here?

Here is the link to the corresponding help: 
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/dialog/dialog-close-method

_Originally posted by @AJasp in https://github.com/Microsoft/ALAppExtensions/issues/963#issuecomment-479523538_

**Comment by AlexanderYakunin** [comment]
As I can see this is fixed long time ago but request is still open. Closing.
