### ISSUE TITLE
Table 7302 function CalcQtyAvailToPutAway

### ISSUE THREAD

**Issue by KReinmann** [microsoft/ALAppExtensions#2067]
Hello,

for our application we are using fct. CalcQtyAvailToPutAway in Table 7302. Please set local function from local to global. 

thanks in advance,
Best regards
Kathrin

**Comment by KReinmann** [comment]
Hi,
Are there new insights here?
Thanks in advance,
best regards,
Kathrin

**Comment by KReinmann** [comment]
@AlexanderYakunin

**Comment by AlexanderYakunin** [comment]
This is done for master in June, not sure why this request is not closed.
