### ISSUE TITLE
[Event Request] table 112 "Sales Invoice Header" - OnDeleteOnBeforeLoctable

### ISSUE THREAD

**Issue by gretanorv** [microsoft/ALAppExtensions#20678]
Hello, would it be possible to add OnDeleteOnBeforeLoctable event to table 112 "Sales Invoice Header", like this: 
 ```al 
 trigger OnDelete() 
 ... 
       begin
          PostSalesDelete.IsDocumentDeletionAllowed("Posting Date");
  
          IsHandled := false;
>         OnDeleteOnBeforeLoctable(IsHandled); //New Event
          if not IsHandled then
              TestField("No. Printed");
          LockTable();
          PostSalesDelete.DeleteSalesInvLines(Rec); 
 ``` 
 ```al 
 local procedure OnDeleteOnBeforeLoctable(var IsHandled: Boolean)  
 ```

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
