### ISSUE TITLE
[Event Request] table 9650 "Custom Report Layout" - OnImportReportLayoutBeforeCheckType

### ISSUE THREAD

**Issue by gretanorv** [microsoft/ALAppExtensions#20689]
Hello, would it be possible to add OnImportReportLayoutBeforeCheckType event to table 9650 "Custom Report Layout", like this: 
 ```al 
 procedure ImportReportLayout(DefaultFileName: Text) 
 ... 
           if IsEmpty() then
              Error(NoRecordsErr);
  
          IsHandled := false;
>         OnImportReportLayoutBeforeCheckType(IsHandled); //New Event
  
          if not IsHandled then
              if not CanBeModified then
                  exit; 
 ``` 
 ```al 
 local procedure OnImportReportLayoutBeforeCheckType(var IsHandled: Boolean)  
 ```

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
