### ISSUE TITLE
[Event Request] page 20 "General Ledger Entries" - OnBeforeModifyRecord

### ISSUE THREAD

**Issue by gretanorv** [microsoft/ALAppExtensions#20696]
Hello, would it be possible to add OnBeforeModifyRecord event to page 20 "General Ledger Entries", like this: 
 ```al 
 trigger OnModifyRecord(): Boolean 
 ... 
           IsHandled: Boolean;
          DarfSachpostenAendern: Boolean;
      begin
          IsHandled := false;
>         OnBeforeModifyRecord(DarfSachpostenAendern, IsHandled); //New Event
          if IsHandled then
              exit(DarfSachpostenAendern);
  
          CODEUNIT.Run(CODEUNIT::"G/L Entry-Edit", Rec); 
 ``` 
 ```al 
 local procedure OnBeforeModifyRecord(var DarfSachpostenAendern: Boolean; var IsHandled: Boolean)  
 ```

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
