### ISSUE TITLE
[Event Request] table 352 "Default Dimension" - OnRenameBeforeCheckingPossibilityToRename

### ISSUE THREAD

**Issue by gretanorv** [microsoft/ALAppExtensions#20690]
Hello, would it be possible to add OnRenameBeforeCheckingPossibilityToRename event to table 352 "Default Dimension", like this: 
 ```al 
 trigger OnRename() 
 ... 
           DimValuePerAccount: Record "Dim. Value per Account";
          IsHandled: Boolean;
      begin
          IsHandled := false;
>         OnRenameBeforeCheckingPossibilityToRename(IsHandled); //New Event
  
          if not IsHandled then
              if ("Table ID" <> xRec."Table ID") or ("Dimension Code" <> xRec."Dimension Code") then
                  Error(Text000, TableCaption); 
 ``` 
 ```al 
 local procedure OnRenameBeforeCheckingPossibilityToRename(var IsHandled: Boolean)  
 ```

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
