### ISSUE TITLE
Edit in Excel - Resource not found for the segment when publishing changes.

### ISSUE THREAD

**Issue by MatDDev** [microsoft/ALAppExtensions#20708]
Hello,

When trying to publish new changes from Excel, using Edit in Excel I am getting the following error:

![image](https://user-images.githubusercontent.com/13900033/196789044-27e0a4e5-2394-41b0-8b98-7e122ae92f10.png)

It's a simple list with just 3 columns. Is there a property that I am missing, or what might be the reason for the error?

**Comment by AlexanderYakunin** [comment]
Sorry, this is not related to the purpose of this forum. Cannot answer tour question.
