### ISSUE TITLE
[Event Request] codeunit 1000 "Job Calculate WIP" - OnBeforeCreateJobWIPTotal

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#20705]
New Event in codeunit 1001:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCreateJobWIPTotal(var JobTask: Record "Job Task")
begin
end;
```

```
local procedure CreateJobWIPTotal(var JobTask: Record "Job Task"; var JobWIPTotal: Record "Job WIP Total")
begin
    OnBeforeCreateJobWIPTotal(JobTask);
    JobWIPTotalChanged := true;
    WIPAmount := 0;
    RecognizedAllocationPercentage := 0;

    JobWIPTotal.Init();
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48316.
