### ISSUE TITLE
extensibility bug - `report 2 "General Journal - Test"` - `"Gen. Journal Batch"` - `OnPreDataItem()` - `CopyFilter` statements from `Line` destroy `Batch` data item's own filters

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#20706]
This report does the following:

![image](https://user-images.githubusercontent.com/63455896/196716548-9b5fb1a7-b614-4cbd-8ec0-11c712f857fb.png)

That makes sense, to a point :-)

But we have a product that mediates approval of General Journal Batches, and does so by filtering to a single batch and then running this report. However, that filter gets lost as the above lines trample the Template/Batch Names on the Batch record with the Lines' filters, which in our case (because we pass only a Batch record to the report, not a Line one)... are empty, so the filters get cleared.

So the report that is produced shows all batches, not only the one that was filtered and passed in as the `"Gen. Journal Batch"` data item. And we can't (nicely, generically) work around this by filtering the `Line` data item instead, as our code only handles the `Batch`.

In the short term it looks like we'll have to work around this by checking if the Lines' filters are empty, and if so copying the Batch's filters to the Line... so that your later code will copy them back. *edit: This can't work for runtimes that don't have report extensions. What we have done is to special-case this Report ID and do our `SetRecFilter()` in another group, then restore the default filter group.*

But ideally we wouldn't have to do that. So is it possible, please, that your report could only copy those filters when the destination fields in the Batch are both blank? e.g.

```al
            if (GetFilter(Name) = '') and (GetFilter("Journal Template Name") = '') then begin // NEW
                "Gen. Journal Line".CopyFilter("Journal Batch Name", Name);
                "Gen. Journal Line".CopyFilter("Journal Template Name", "Journal Template Name");
            end; // NEW
```

Ditto for any other Journal/Batch type reports with the same pattern, please :-) *edit: I didn't find any obvious ones, yet*

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51299.
