### ISSUE TITLE
[Event Request] codeunit 444 "Purchase-Post Prepayments" - OnBeforePostVendorEntry

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#20709]
Please extend the event OnBeforePostVendorEntry with additional parameter:

```
        if GLSetup."Journal Templ. Name Mandatory" then
            "Journal Template Name" := GenJournalTemplate.Name;

        OnBeforePostVendorEntry(GenJnlLine, TotalPrepmtInvLineBuffer, TotalPrepmtInvLineBufferLCY, SuppressCommit, PurchHeader);
        GenJnlPostLine.RunWithCheck(GenJnlLine);
        OnAfterPostVendorEntry(GenJnlLine, TotalPrepmtInvLineBuffer, TotalPrepmtInvLineBufferLCY, SuppressCommit);
    end;
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforePostVendorEntry(var GenJnlLine: Record "Gen. Journal Line"; TotalPrepmtInvLineBuffer: Record "Prepayment Inv. Line Buffer"; TotalPrepmtInvLineBufferLCY: Record "Prepayment Inv. Line Buffer"; CommitIsSupressed: Boolean; PurchaseHeader: Record "Purchase Header")
begin
end;
```

**Comment by Vadim-Stepanenko** [comment]
Can't find any of this code in PurchaseHeader, please double check which version/country you are using.

**Comment by miljance** [comment]
Sorry, wrong title. I have corrected the title. The change should happen in the codeunit 444 "Purchase-Post Prepayments" analog to the event OnBeforePostCustomerEntry in codeunit 442 "Sales-Post Prepayments"

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
