### ISSUE TITLE
[Request for External] Codeunit 12 "Gen. Jnl.-Post Line", function PostGenJnlLine

### ISSUE THREAD

**Issue by ChristianFeitl** [microsoft/ALAppExtensions#20707]
Hello, 
we need to post additional G/L entries within a RunWithCheck call.
Therefore, please change function PostGenJnlLine to global.
```al
local procedure PostGenJnlLine(var GenJnlLine: Record "Gen. Journal Line"; Balancing: Boolean)
```
Thank you!

**Comment by AlexanderYakunin** [comment]
You already have this

procedure RunWithCheck(var GenJnlLine2: Record "Gen. Journal Line"): Integer

**Comment by ChristianFeitl** [comment]
We tried that function, it does not work, it seems to reset internal values.
THe requirement is to post additional G/L entries within an existing RunWithCheck call.
