### ISSUE TITLE
[Request procedure] Page 490 "Acc. Schedule Overview" - procedure GetUseAmtsInAddCurr()

### ISSUE THREAD

**Issue by nd2403** [microsoft/ALAppExtensions#20712]
Hello,

We would like to replace the action "Create New Document" in page 490 "Acc. Schedule Overview", so we can use our report instead of "Export Acc. Sched. to Excel", however we need access to global variable UseAmtsInAddCurr. 
Can you please added procedure that returns global variable UseAmtsInAddCurr (GetUseAmtsInAddCurr) to page 490? 

Thank you in advance.

**Comment by AlexanderYakunin** [comment]
We usually make such variable protected, no need to add procedure

**Comment by AlexanderYakunin** [comment]
This variable already made protected
