### ISSUE TITLE
Assisted Setup shows Entries multiple Entries (old Versions)

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#20711]
In the Codeunit 1991 "Guided Experience Impl.", Procedure InsertGuidedExperienceItemsInTempVar the Variable InsertItem is not reset (ItemItem := false;) at the Begin of the Repeat-Until-Loop which leads to the insertion of all following items once InsertItem is set to True the first time.

![image](https://user-images.githubusercontent.com/46991052/196923875-97b84c7a-0bd5-4842-9874-14a2cd871577.png)

**Comment by meilel** [comment]
i can recreate the same behavior in BC 21.2. All my Manual Setups are displayed multiple times for every version existing in the table. Have you found a workaround yet?

**Comment by meilel** [comment]
thank you for your quick feedback. We also hope to see a solution soon, because this must be a problem that affects everyone

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10164.
