### ISSUE TITLE
[Event Request] page 379 "Bank Acc. Reconciliation"

### ISSUE THREAD

**Issue by KuljitSinghParmar** [microsoft/ALAppExtensions#20719]
Hi Team,

In page 379 "Bank Acc. Reconciliation", we need to have Integration event in the "local procedure UpdateBankAccountLedgerEntrySubpage(StatementDate: Date; ExcludeReversedEntries: Boolean) ". Adding an event where we can add "Global Dimension 1/2 Filter" filter to the record will work great for us.

We need to add global dimension 1/2 filter to the vendor/customer table before it is populating the data into the ApplyBankLedgerEntries page. 

![image](https://user-images.githubusercontent.com/61985025/197010097-b4b9a220-356b-45ac-b654-5332b15b9a05.png)

local procedure UpdateBankAccountLedgerEntrySubpage(StatementDate: Date; ExcludeReversedEntries: Boolean)
    var
        BankAccountLedgerEntry: Record "Bank Account Ledger Entry";
        FilterDate: Date;
    begin
        BankAccountLedgerEntry.SetRange("Bank Account No.", "Bank Account No.");
        BankAccountLedgerEntry.SetRange(Open, true);
        BankAccountLedgerEntry.SetFilter("Statement Status", Format(BankAccountLedgerEntry."Statement Status"::Open) + '|' + 
                                                               Format(BankAccountLedgerEntry."Statement Status"::"Bank Acc. Entry Applied") + '|' + 
                                                               Format(BankAccountLedgerEntry."Statement Status"::"Check Entry Applied"));

       OnAfterAddFilter(BankAccountLedgerEntry);

        FilterDate := MatchCandidateFilterDate();
        if StatementDate > FilterDate then
            FilterDate := StatementDate;
        if FilterDate <> 0D then
            BankAccountLedgerEntry.SetFilter("Posting Date", '<=' + Format(FilterDate));
        if BankAccountLedgerEntry.FindSet() then
            if ExcludeReversedEntries then begin
                repeat
                    if (BankAccountLedgerEntry."Statement Status" = BankAccountLedgerEntry."Statement Status"::Open) and 
                       (BankAccountLedgerEntry.Reversed = true) then
                         BankAccountLedgerEntry.Mark(false)
                    else
                        BankAccountLedgerEntry.Mark(true);
                until BankAccountLedgerEntry.Next() = 0;
                BankAccountLedgerEntry.MarkedOnly(true);
            end;
        CurrPage.ApplyBankLedgerEntries.Page.SetTableView(BankAccountLedgerEntry);
        CurrPage.ApplyBankLedgerEntries.Page.Update();
    end;

[IntegrationEvent(false, false)]
local procedure OnAfterAddFilter(var BankAccountLedgerEntry: Record  "Bank Account Ledger Entry")
begin
end;

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
