### ISSUE TITLE
[Request for External] Codeunit 12 "Gen. Jnl.-Post Line", function PostGenJnlLine

### ISSUE THREAD

**Issue by ChristianFeitl** [microsoft/ALAppExtensions#20714]
Hello, we cannot use RunWithCheck.

We tried that function, it results in a "G/L entry already exists error", as it seems to reset internal values of the codeunit.
The requirement is to post additional G/L entries within an existing RunWithCheck call.
Therefore, please change function PostGenJnlLine to global.

_Originally posted by @ChristianFeitl in https://github.com/microsoft/ALAppExtensions/issues/20707#issuecomment-1285536743_

**Comment by AlexanderYakunin** [comment]
No, this is wrong way, you cannot use this method globally, please read this first 

https://learn.microsoft.com/en-us/dynamics365/business-central/design-details-posting-engine-structure

**Comment by ChristianFeitl** [comment]
Ok, thanks for the info but all the functions mentioned in the article are local too (looked into BC20 CU05).
So I cannot use them either in our extension.

**Comment by ChristianFeitl** [comment]
I don't know if you receive notifications, therefore I do it this way, @AlexanderYakunin

**Comment by AlexanderYakunin** [comment]
You should not expect any external functions for 20.x, we do not make such changes to PROD versions. Try to use existing events and add what you need in subscribers.

We only provide it for Master (currently it is 22.x).

**Comment by ChristianFeitl** [comment]
@AlexanderYakunin , to my understanding subscribers cannot help me with the task of adding G/L entries.
On the other hand if we do not get the possibilty to use the mentioned functions we have to use a changed BaseApp which is not an option.

**Comment by AlexanderYakunin** [comment]
Please explain in more details what you are doing and maybe I will guide you to right direction.

**Comment by ChristianFeitl** [comment]
While reviewing our code to answer your request I maybe found a way to solve this issue. I will look more into that and will open a new request if necessary. Thank you for guiding me!
