### ISSUE TITLE
[Event Parameter Change] Table 39 Purchase Line - procedure UpdateICPartner - event OnBeforeUpdateICPartner

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#20721]
We would like the parameter/-s ishandled added to the following event.

Table 39 Purchase Line - procedure UpdateICPartner - event OnBeforeUpdateICPartner

Original:

```
Table 39 Purchase Line - procedure UpdateICPartner - event OnBeforeUpdateICPartner

IsHandled := false;
OnBeforeUpdateICPartner(Rec, GLAcc, PurchHeader, IsHandled);

if PurchHeader."Send IC Document" and
   (PurchHeader."IC Direction" = PurchHeader."IC Direction"::Outgoing)
then
...

```

Change:

```
IsHandled := false;
OnBeforeUpdateICPartner(Rec, GLAcc, PurchHeader, IsHandled);
if IsHandled then // <-- ADDED
    exit; // <-- ADDED

if PurchHeader."Send IC Document" and
   (PurchHeader."IC Direction" = PurchHeader."IC Direction"::Outgoing)
then
...
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48444.
