### ISSUE TITLE
[Event Request] Table 210- Job Journal Line - OnBeforeGetLocation

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#20728]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnBeforeGetLocation` in Table 210 `Job Journal Line` with the following signature:

```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeGetLocation(var JobJournalLine: Record "Job Journal Line"; var Location: Record Location; LocationCode: Code[10]; var IsHandled: Boolean)
begin
end;
```

which would be called as follows in the `GetLocation` function:

```AL
local procedure GetLocation(LocationCode: Code[10])
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeGetLocation(Rec, Location, LocationCode, IsHandled);
    if IsHandled then
        exit;

    if LocationCode = '' then
        Clear(Location)
    else
        if Location.Code <> LocationCode then
            Location.Get(LocationCode);
end;
```

Thanks in advance!

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
