### ISSUE TITLE
[Event Request] Report 704 - Add Event before Line CalcFields("Net Change"); with parameter var Item

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/ALAppExtensions#20738]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49870.
