### ISSUE TITLE
[Event Request] Report 492 Copy Purchase Document change OnBeforeLookupDocNo event

### ISSUE THREAD

**Issue by bachii1010** [microsoft/ALAppExtensions#20739]
Hi,

Please change the below event:
[IntegrationEvent(false, false)]
    local procedure OnBeforeLookupDocNo(var PurchaseHeader: Record "Purchase Header")
    begin
    end;

to 
[IntegrationEvent(false, false)]
    local procedure OnBeforeLookupDocNo(var PurchaseHeader: Record "Purchase Header"; var FromDocNo: Code[20]; var FromDocType: Enum "Purchase Document Type From")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48695.
