### ISSUE TITLE
[Event Request] Extend OnBeforePostSourceDocument

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#20733]
Hello,

please extend the Eventpublisher OnBeforePostSourceDocument in codeunit 5763 "Whse.-Post Shipment" function "Code()" with SuppressCommit . At the moment there is no way for us to know whether or not we can commit in the Subscriber.

repeat
          SetSourceFilter("Source Type", "Source Subtype", "Source No.", -1, false);
          OnAfterSetSourceFilterForWhseShptLine(WhseShptLine);
          GetSourceDocument();
          MakePreliminaryChecks();
          InitSourceDocumentLines(WhseShptLine);
          InitSourceDocumentHeader();
          if not SuppressCommit then
              Commit();
          CounterSourceDocTotal := CounterSourceDocTotal + 1;
          **OnBeforePostSourceDocument(WhseShptLine, PurchHeader, SalesHeader, TransHeader, ServiceHeader, SuppressCommit);**
          PostSourceDocument(WhseShptLine);
          WhseJnlRegisterLine.LockTables();
          if FindLast() then;
          SetRange("Source Type");
          SetRange("Source Subtype");
          SetRange("Source No.");
          OnAfterReleaseSourceForFilterWhseShptLine(WhseShptLine);
until Next() = 0;

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
