### ISSUE TITLE
[Parameter Update] Event OnAfterGetRecordItemOnBeforeSkipEmptyLine in Report 1001 - Inventory Valuation

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#20732]
Hi

Can you please prefix the Qty-parameters in the OnAfterGetRecordItemOnBeforeSkipEmptyLine event in report 1001 - Inventory Valution with var and pass by reference instead of value?

```
[IntegrationEvent(false, false)]
// >>>>>>>>>>
//local procedure OnAfterGetRecordItemOnBeforeSkipEmptyLine(var Item: Record Item; StartingInvoicedQty: Decimal; IncreaseInvoicedQty: Decimal; DecreaseInvoicedQty: Decimal; var IsHandled: Boolean; var IsEmptyLine: Boolean)
local procedure OnAfterGetRecordItemOnBeforeSkipEmptyLine(var Item: Record Item; var StartingInvoicedQty: Decimal; var IncreaseInvoicedQty: Decimal; var DecreaseInvoicedQty: Decimal; var IsHandled: Boolean; var IsEmptyLine: Boolean)
// <<<<<<<<<<
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48699.
