### ISSUE TITLE
New Event in Table 36 Location Code

### ISSUE THREAD

**Issue by Nethernexus** [microsoft/ALAppExtensions#20730]
Hi ALAppExtensions Team,
in Table 38 in Location Code there is an event in OnValidate-Trigger OnBeforeValidateLocationCode. 

It would be really cool to have the same event in table 36 Sales Header.

Code in T 38:
            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                OnBeforeValidateLocationCode(Rec, IsHandled);
                if IsHandled then
                    exit;
...

Greetings and kind regards
Karsten

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
