### ISSUE TITLE
Wrong Translations for "Warehouse Receipt"

### ISSUE THREAD

**Issue by vdevmt** [microsoft/ALAppExtensions#20731]
In ITA version all translations for Warehouse Receipt Tables, Fields, Actions and more are wrong.
Actual Translation: Receipt = Ricevuta
Correct Translation: Receipt = Carico

Actual Translation: Receipts = Ricevute
Correct Translation: Receipts = Carichi

**Comment by AlexanderYakunin** [comment]
Sorry, we do not process translation related requests here
