### ISSUE TITLE
[Event Change Request] page 973 "Time Sheet Card" - OnAfterProcess

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#20744]
Could you please include the sender in the event `OnAfterProcess`?
```al
//+Change
//-[IntegrationEvent(false, false)]
[IntegrationEvent(true, false)]
//-Change
local procedure OnAfterProcess(var TimeSheetHeader: Record "Time Sheet Header"; ActionType: Option Submit,ReopenSubmitted,Approve,ReopenApproved,Reject)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48695.
