### ISSUE TITLE
[Enum Request] Table 472 "Job Queue Entry" - Field "Report Output Type"

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#20755]
Dear ALAppExtensions team,

could you please change the field type of the field ``Report Output Type` in the table 472 `Job Queue Entry` to an Enum.

Old signature

```AL
 field(10; "Report Output Type"; Option)
 {
     Caption = 'Report Output Type';
     OptionCaption = 'PDF,Word,Excel,Print,None (Processing only)';
     OptionMembers = PDF,Word,Excel,Print,"None (Processing only)";
```

New Signature

```AL
field(10;"Report Output Type"; Enum "Report Output Type")
{
    Caption = 'Report Output Type';
```

New Enum Type

```AL
enum [Object ID] "Report Output Type"
{
    Extensible = true;

    value(0; PDF)
    {
        Caption = 'PDF';
    }
    value(1; Word)
    {
        Caption = 'Word';
    }
    value(2; Excel)
    {
        Caption = 'Excel';
    }
    value(3; Print)
    {
        Caption = 'Print';
    }
    value(4; "None (Processing only)")
    {
        Caption = 'None (Processing only)';
    }
}
```

Thank you in advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
