### ISSUE TITLE
BC21: Feature "Allow using of multiple posting groups for customer or vendor" not usable

### ISSUE THREAD

**Issue by lbagage-pdw** [microsoft/ALAppExtensions#20753]
Hello,
After having enabled the feature "Allow using of multiple posting groups for customer or vendor" (plus signed out/sign in), I wish to set "Allow Multiple Posting Groups" to Yes in page 459 "Sales & Receivables Setup" but I can't: the control is not displayed.
The reason is the following: in page 459, the control is defined with ApplicationArea = Advanced.

Nota: same behavior and same reason for "Allow Multiple Posting Groups" in page 460 "Purchases & Payables Setup".

**Comment by RadoArvay** [comment]
The feature is not fully implemented yet. We are waiting for it as well but it was postponed multiply times.

**Comment by laurbag** [comment]
I understand, but then wouldn't it be useful to remove this feature until it is usable?
My second question is: when do you think it will be safely available?

**Comment by oyam63** [comment]
Hi. I enabled the feature in a sandbox. I tested with a simple purchase order and seemed to work fine. What is not working?

**Comment by laurbag** [comment]
Hello,
In a sandbox (version 21.3.51409.52527), even if the feature is enabled, it is impossible to display the field "Allow Multiple Posting Groups" in the "Sales & Receivables Setup" page. So, we cannot enable it.
The result is that we are not allowed to modify the "Customer Posting Group" in a Sales document.
Same thing happens on the Purchase side.

**Comment by RadoArvay** [comment]
Mine and Alexander's comments are still valid - it is not fully implemented yet. There should be a public availability again in BC22 release as mentioned in a pre-release note. But new insider artifacts are not available for about two weeks (I do not know why) so I cannot check if there is something new in the code.

**Comment by AlexanderYakunin** [comment]
We understand importance of this change and working to make this capability fully available for Preview in v.22 and GA in v.23 together with extendable Exchange Rate Adjustment feature. There are some dependencies between new features and legacy code to consider. This requests about Advanced app area is already considered.

**Comment by oyam63** [comment]
I enabled the "Allow Multiple Posting Groups" field on Purchases & Payables Setup using a configuration package. I tested a couple of documents and worked well. Not sure what is missing.

**Comment by RadoArvay** [comment]
Next steps are unprepared. It means when you try to apply two entries with different posting groups (with different payables accounts), your result will be unballanced. Example:

- entry 1 - the invoice with posting group 1 posted to account 1: -100
- entry 2 - the payment with posting group 2 posted to account 2: +100

After applying these etries there should be a zero ballance on both accounts = a system should post +100 to Acc1 and -100 to Acc2 - and this part is missing.

Before this feature it is like:

- entry 1 - the invoice with posting group 1 posted to account 1: -100
- entry 2 - the payment with posting group 1 posted to account 1: +100

...and the balance of Acc1 is zero

It should work similarly to applying two entries with different sets of dimensions.

**Comment by marcellusnav** [comment]
Hi All,

I see that this thread is closed but I wanted to add that the Vendor Trial Balance report does not show correctly the different Vendor Posting Groups.  It will show all entries under the Vendor Posting Group set on the Vendor Card.

I believe if we want to enable this feature this report needs to show the vendor and the corresponding balance under each Vendor Posting Group.
So the report will need to group by vendor posting group and flow fields like Balance on the vendor record should include a flow filter for Vendor Posting Group.

I hope this makes sense and thank you for all the efforts regarding this feature, we are looking forward it being released.

Regards,
Marcell
