### ISSUE TITLE
[Enum Request] IC Source Type enum

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#20756]
We would like to extend the IC transactions with a new source type (`requisition lines`)
Therefore, it would be required to have the 'Source Type' field in below tables available as enum instead of option.

**table 420 "Handled IC Inbox Trans."
table 416 "Handled IC Outbox Trans."
table 418 "IC Inbox Transaction"**

`OptionMembers = Journal,"Sales Document","Purchase Document";`

**table 414 "IC Outbox Transaction"**

`OptionMembers = "Journal Line","Sales Document","Purchase Document";`

Not sure if you would be able to create just **one** enum, or have to create (as a dirty workaround) a second enum for the differently named (Journal Line vs Journal) optionmembers in table 414 vs 416...

**Comment by AndersLarsenMicrosoft** [comment]
Closed as this is rather old request - and yes i know that we have done anything from our side, but we haven't seen any traction on this either
