### ISSUE TITLE
[Event Parameter Change] Codeunit 80 Sales Post - OnAfterPostItemJnlLine

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#20750]
We are working on an addon extension which has a new value "Inventory Quantity Zero A108" in table "Return Reason" to enable Directly undo the positive inventory posting of the sales return item. Goods are physically not being returned, but our customer has to pay a fee and does not want to use a fake resource or worse an item charge. Especially when you are dealing with EDI communication which does not know those last two entities. We would like the extra four variables in event OnAfterPostItemJnlLine to enable the request.

procedure PostItemJnlLine(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; QtyToBeShipped: Decimal; QtyToBeShippedBase: Decimal; QtyToBeInvoiced: Decimal; QtyToBeInvoicedBase: Decimal; ItemLedgShptEntryNo: Integer; ItemChargeNo: Code[20]; TrackingSpecification: Record "Tracking Specification"; IsATO: Boolean) Result: Integer
        ...
            ItemShptEntryNo := "Item Shpt. Entry No.";
            //OnAfterPostItemJnlLine(ItemJnlLine, SalesLine, SalesHeader, ItemJnlPostLine, WhseJnlPostLine, OriginalItemJnlLine, ItemShptEntryNo);  A108F0101.Event21.00.o
            OnAfterPostItemJnlLine(ItemJnlLine, SalesLine, SalesHeader, ItemJnlPostLine, WhseJnlPostLine, OriginalItemJnlLine, ItemShptEntryNo, TempHandlingSpecification, TempATOTrackingSpecification, TempWhseJnlLine, ShouldPostItemJnlLine); //A108F0101.Event21.00.n

            exit(ItemShptEntryNo);
        end;
    end;

    [IntegrationEvent(TRUE, false)]
    local procedure OnAfterPostItemJnlLine(var ItemJournalLine: Record "Item Journal Line"; SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header"; var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line"; var WhseJnlPostLine: Codeunit "Whse. Jnl.-Register Line"; OriginalItemJnlLine: Record "Item Journal Line"; var ItemShptEntryNo: Integer; var TempHandlingSpecification: Record "Tracking Specification"; var TempATOTrackingSpecification: Record "Tracking Specification"; TempWhseJnlLine: Record "Warehouse Journal Line" temporary; ShouldPostItemJnlLine: Boolean)
    begin
        //A108F0101.Event21.00 parameters TempHandlingSpecification, TempATOTrackingSpecification, TempWhseJnlLine, ShouldPostItemJnlLine
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48695.
