### ISSUE TITLE
[Parameter Change] - Codeunit 1001 - Make Parameters a VAR

### ISSUE THREAD

**Issue by horstoeko** [microsoft/ALAppExtensions#20757]
Hi 

Please declare the parameters of the following functions in _Codeunit 1001_ as VAR:

* InsertPlLineFromLedgEntry
* PostPlanningLine

__InsertPlLineFromLedgEntry__

_Old Signature_

````al
InsertPlLineFromLedgEntry(JobLedgEntry: Record "Job Ledger Entry")
````
_New Signature_

````al
InsertPlLineFromLedgEntry(var JobLedgEntry: Record "Job Ledger Entry")
````

__PostPlanningLine__

_Old Signature_

````al
PostPlanningLine(JobPlanningLine: Record "Job Planning Line")
````
_New Signature_

````al
PostPlanningLine(var JobPlanningLine: Record "Job Planning Line")
````
Thank you in advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51299.
