### ISSUE TITLE
Reintroduce CurrPage.Update() on Page 95 Sales Quote Subform OnValidate "No."

### ISSUE THREAD

**Issue by pererikandersen** [microsoft/ALAppExtensions#20754]
Please reintroduce CurrPage.Update() in OnValidate trigger for "No." in page 95 Sales Quote Subform. Codeline CurrPage.Update() in OnValidate trigger for "No." in page 95 Sales Quote Subform is removed with 21.0.46256.48144. 
Often additional lines is added automatically when entering a No. (special fee lines, bundle lines etc.) by use of an extension (subscriber on page event OnAfterValidateEvent) where Line No. is a prerequisite. 

_20.5.45456.47775 (CurrPage.Update() exist)_
                field("No."; "No.")
                {
                    ApplicationArea = Basic, Suite;
                    ShowMandatory = Type <> Type::" ";
                    ToolTip = 'Specifies the number of a general ledger account, item, resource, additional cost, or fixed asset, depending on the contents of the Type field.';

                    trigger OnValidate()
                    begin
                        ShowShortcutDimCode(ShortcutDimCode);
                        NoOnAfterValidate();
                        UpdateEditableOnRow();
                        UpdateTypeText();
                        DeltaUpdateTotals();

                        CurrPage.Update();
                    end;
                }

_21.0.46256.48144 (CurrPage.Update() is deleted)_
                field("No."; Rec."No.")
                {
                    ApplicationArea = Basic, Suite;
                    ShowMandatory = Type <> Type::" ";
                    ToolTip = 'Specifies the number of a general ledger account, item, resource, additional cost, or fixed asset, depending on the contents of the Type field.';

                    trigger OnValidate()
                    var
                        Item: Record "Item";
                    begin
                        ShowShortcutDimCode(ShortcutDimCode);
                        NoOnAfterValidate();
                        UpdateEditableOnRow();
                        UpdateTypeText();
                        DeltaUpdateTotals();

                        if "Variant Code" = '' then
                            VariantCodeMandatory := Item.IsVariantMandatory(Type = Type::Item, "No.");
                    end;
                }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51299.
