### ISSUE TITLE
Issue with GetBlobAsFile from blob-service-rest-api

### ISSUE THREAD

**Issue by gntpet** [microsoft/ALAppExtensions#20764]
Hey BC gurus, 

while testing blob-service-rest-api, we discovered that GetBlobAsFile is not working well in 'negative' scenarios, when trying to get non-existing blob. Now, if you run the function it will 'download' empty file, since there's no response check there.

See the function code

![image](https://user-images.githubusercontent.com/16342128/198215157-2ffdc45a-8b18-4a5f-a400-59d4a733a14f.png)

The code should something like this:

```
    procedure GetBlobAsFile(BlobName: Text; ABSOptionalParameters: Codeunit "ABS Optional Parameters"): Codeunit "ABS Operation Response"
    var
        ABSOperationResponse: Codeunit "ABS Operation Response";
        TargetInStream: InStream;
    begin
        ABSOperationResponse := GetBlobAsStream(BlobName, TargetInStream, ABSOptionalParameters);

        if ABSOperationResponse.IsSuccessful() then begin
          BlobName := ABSOperationPayload.GetBlobName();
          DownloadFromStream(TargetInStream, '', '', '', BlobName);
        end;
        exit(ABSOperationResponse);
    end;
```

Best Regards, 
Gintautas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 52498.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 52498.
