### ISSUE TITLE
[Protected var] page 296 "Recurring Req. Worksheet" - CurrentJnlBatchName

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#20766]
Can we please have (protected var) access to the global variable "CurrentJnlBatchName" in page 296 "Recurring Req. Worksheet"?

Cfr. #15181

**Comment by fvet** [comment]
@AlexanderYakunin Any chance in having this on prioritized for the nextMajor?

**Comment by AlexanderYakunin** [comment]
Did you check the code for 22.x? This was fixed long time ago. Not sure why this request is not closed on GitHub.

Here is what we have in this object:

    protected var
        ShortcutDimCode: array[8] of Code[20];
        Description2: Text[100];
        BuyFromVendorName: Text[100];
        CurrentJnlBatchName: Code[10];
        OpenedFromBatch: Boolean;
