### ISSUE TITLE
[Event Request] Table 1001- Job Task - OnBeforeOnModify

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#20768]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnBeforeOnModify` Table 1001 `Job Task` with the following signature:

```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeOnModify(var JobTask: Record "Job Task"; var IsHandled: Boolean)
begin
end;
```

which would be called as follows in the `OnModify` trigger:

```AL
trigger OnModify()
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeOnModify(Rec, IsHandled);
    if IsHandled then
        exit;

    CalcFields("Schedule (Total Cost)", "Usage (Total Cost)");
    Job.UpdateOverBudgetValue("Job No.", true, "Usage (Total Cost)");
    Job.UpdateOverBudgetValue("Job No.", false, "Schedule (Total Cost)");
end;
```

Thanks in advance!

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
