### ISSUE TITLE
[EventRequest] Add parameter to OnAfterIsPriceUpdateNeeded in codeunit 7020 "Sales Line - Price"

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#20769]
Hello, please consider adding the SalesLine parameter to the following event to `codeunit 7020 "Sales Line - Price"`

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterIsPriceUpdateNeeded(AmountType: Enum "Price Amount Type"; FoundPrice: Boolean; CalledByFieldNo: Integer; SalesLine: Record "Sales Line"; var Result: Boolean)
    begin
    end;
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48695.
