### ISSUE TITLE
[Event Parameter Change Request] Codeunit 6500 - OnSplitWhseJnlLineOnAfterCheckWhseItemTrkgSetup

### ISSUE THREAD

**Issue by fekramer** [microsoft/ALAppExtensions#20762]
Current Parameter on Event OnSplitWhseJnlLineOnAfterCheckWhseItemTrkgSetup is

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/24778982/198069058-60ec93cd-742d-4a36-a6ac-179b2621a781.png">

Same Event in BC14

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/24778982/198069267-9da47ed4-52cf-4185-bc79-2417c4715aa6.png">

I think Parameter WhseItemTrackingSetup."Lot No. _Info_ Required" must be WhseItemTrackingSetup."Lot No. Required" 

Best regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51150.
