### ISSUE TITLE
[Event Request] Table 1003- Job Planning Line - OnAfterGetJob

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#20776]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnAfterGetJob` Table 1003 `Job Planning Line` with the following signature:

```AL
[IntegrationEvent(false, false)]
local procedure OnAfterGetJob(var JobPlanningLine: Record "Job Planning Line")
begin
end;
```

which would be called as follows in the the `GetJob` procedure:

```AL
local procedure GetJob()
begin
    if ("Job No." <> Job."No.") and ("Job No." <> '') then
        Job.Get("Job No.");

    OnAfterGetJob(Rec);
end;
```

Thanks in advance!

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
