### ISSUE TITLE
Adding permissions to multiple objects

### ISSUE THREAD

**Issue by DonHendriksen** [microsoft/ALAppExtensions#20772]
Hi,
Hereafter an overview of objects for which we request to assign additional permissions.

codeunit 360 "Accounting Period Mgt."
- tabledata "Accounting Period" = R

codeunit 1535 "Approvals Mgmt."
- tabledata "Approval Entry" = R

codeunit 11 "Gen. Jnl.-Check Line"
- tabledata "Cost Accounting Setup" = R
- tabledata "Payment Terms" = R

table 81 "Gen. Journal Line"
- tabledata Customer = R
- tabledata "Cust. Ledger Entry" = R
- tabledata "G/L Account" = R
- tabledata "VAT Posting Setup" = R

codeunit 12 "Gen. Jnl.-Post Line"
- tabledata "Customer Posting Group" = R
- tabledata "Cust. Ledger Entry" = I
- tabledata "Detailed Cust. Ledg. Entry" = R
- tabledata "G/L Register" = R
- tabledata "Sales & Receivables Setup" = R
- tabledata "Source Code Setup" = R
- tabledata "VAT Entry" = R

codeunit 408 DimensionManagement
- tabledata "Default Dimension" = R
- tabledata "Dimension Set Entry" = R

table 221 "Gen. Jnl. Allocation"
- tabledata "Gen. Jnl. Allocation" = R

codeunit 703 "Find Record Management"
- tabledata "G/L Entry" = R

table 21 "Cust. Ledger Entry"
- tabledata "Reminder/Fin. Charge Entry" = R

table 1053 "Line Fee Note on Report Hist."
- tabledata "Reminder Terms" = R

codeunit 5477 "Sales Invoice Aggregator"
- tabledata "Sales Invoice Entity Aggregate" = RM

table 5475 "Sales Invoice Entity Aggregate"
- tabledata "VAT Business Posting Group" = R

codeunit 1501 "Workflow Management"
- tabledata Workflow = R
- tabledata "Workflow Step" = R
- tabledata "Workflow Step Instance" = R

table 18 Customer
- tabledata "VAT Business Posting Group" = R
- tabledata "Payment Terms" = R

Thanks. Regards,
Don

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51686.
