### ISSUE TITLE
[EventRequest] Add event to FindParentCRMAccountForContact in codeunit 7205 "CDS Int. Table. Subscriber"

### ISSUE THREAD

**Issue by CarloAxians** [microsoft/ALAppExtensions#20773]
We want to synchronize only Vendors and Contacts to dataverse. 
But the contact is coupled to both a Customer record and a Vendor record.
In that case the account id in dataverse will be filled with the CRM id of the customer.

We would like have an event in the FindParentCRMAccountForContact to deal with this:

```
    local procedure FindParentCRMAccountForContact(SourceRecordRef: RecordRef; Silent: Boolean; var AccountId: Guid): Boolean
    var
        ContactBusinessRelation: Record "Contact Business Relation";
        Contact: Record Contact;
        Customer: Record Customer;
        Vendor: Record Vendor;
        CRMIntegrationRecord: Record "CRM Integration Record";
        isHandled: Boolean;
        RecordFound: Boolean;
    begin
        // Event>>
        OnBeforeFindParentCRMAccountForContact(SourceRecordRef, Silent, AccountId, RecordFound, isHandled);
        if IsHandled then
            exit(RecordFound);
        // Event<<

````

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindParentCRMAccountForContact(SourceRecordRef: RecordRef; Silent: Boolean; var AccountId: Guid; var RecordFound: Boolean; var isHandled: Boolean)
    begin
    end;

```

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
