### ISSUE TITLE
Table 77: bug with reports selections

### ISSUE THREAD

**Issue by LucaMartinengo** [microsoft/ALAppExtensions#2077]
Hi,

Applying on the report 202 (launched from page 9301) a filter on the invoices like: 

![image](https://user-images.githubusercontent.com/39652483/56038086-57d70200-5d31-11e9-89bc-1282de257af0.png)

The report should select for printing all the report rows since from 18TC000005 to 18TC000007, as these invoices are handled on the page

![image](https://user-images.githubusercontent.com/39652483/56038570-9b7e3b80-5d32-11e9-8e0f-71fe8c3cc55c.png)

Instead, the report places a default filter on the customer for the current row, and selects only the rows for the current customer "Cliente retail", so the Invoice 18TC000007 could not be printed.

We noticed the error updating a NAV version from CU6 to CU15, actually, because the bug on the CU6 was not present.
  
Below, there is a comparison on the report selection from CU6 and CU15.

CU6:
![image](https://user-images.githubusercontent.com/39652483/56038973-835aec00-5d33-11e9-9cd3-636b4a2ad9ab.png)

CU15:
![image](https://user-images.githubusercontent.com/39652483/56038987-8bb32700-5d33-11e9-9dc0-0dc126bbce74.png)

Best regards,
Luca Martinengo

**Comment by StanPesotskiy** [comment]
Please report this issue via the standard support channel. This is not related to extensibility.
