### ISSUE TITLE
[Event Parameter Request] codeunit 80 "Sales-Post" - OnAfterReturnRcptLineInsert

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#20771]
Please add variable SalesHeader to event OnAfterReturnRcptLineInsert. Procedure InsertReturnReceiptLine needs to pass this variable as well. And when you are already working in that area: Maybe do the same for the ReturnReceiptLine as has been done with the SalesShipmentLine in procedure SalesShptLineInsert. The code does not behave and look the same for both records

    //local procedure InsertReturnReceiptLine(SalesHeader: Record "Sales Header"ReturnRcptHeader: Record "Return Receipt Header"; SalesLine: Record "Sales Line"; CostBaseAmount: Decimal) A109F0000.Event21.00.o
    local procedure InsertReturnReceiptLine(SalesHeader: Record "Sales Header"; ReturnRcptHeader: Record "Return Receipt Header"; SalesLine: Record "Sales Line"; CostBaseAmount: Decimal) //A109F0000.Event21.00.n
    ...
        OnBeforeReturnRcptLineInsert(ReturnRcptLine, ReturnRcptHeader, SalesLine, SuppressCommit, xSalesLine, TempSalesLineGlobal);
        ReturnRcptLine.Insert(true);
        OnAfterReturnRcptLineInsert(
          //ReturnRcptLine, ReturnRcptHeader, SalesLine, ItemLedgShptEntryNo, WhseShip, WhseReceive, SuppressCommit, SalesCrMemoHeader, TempWhseShptHeader, TempWhseRcptHeader); A109F0000.Event21.00.o
          ReturnRcptLine, ReturnRcptHeader, SalesLine, ItemLedgShptEntryNo, WhseShip, WhseReceive, SuppressCommit, SalesCrMemoHeader, TempWhseShptHeader, TempWhseRcptHeader, SalesHeader); //A109F0000.Event21.00.n
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterReturnRcptLineInsert(var ReturnRcptLine: Record "Return Receipt Line"; ReturnRcptHeader: Record "Return Receipt Header"; SalesLine: Record "Sales Line"; ItemShptLedEntryNo: Integer; WhseShip: Boolean; WhseReceive: Boolean; CommitIsSuppressed: Boolean; SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var TempWhseShptHeader: Record "Warehouse Shipment Header" temporary; var TempWhseRcptHeader: Record "Warehouse Receipt Header" temporary; SalesHeader: Record "Sales Header")
    begin
        //A109F0000.Event21.00 Parameter SalesHeader
    end;

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
