### ISSUE TITLE
[Event Change Request] codeunit 408 DimensionManagement - OnBeforeCheckDimComb

### ISSUE THREAD

**Issue by jorland1** [microsoft/ALAppExtensions#20781]
Hi,
could you please add the parameter `TempDimBuf` from procedure `CheckDimComb` as a parameter to the event `OnBeforeCheckDimComb`?
The resulting signature would be: 
``` al
local procedure OnBeforeCheckDimComb(
    var DimensionCombination: Record "Dimension Combination";
    var TempDimBuf: Record "Dimension Buffer" temporary)
```

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48695.
