### ISSUE TITLE
[Event]  in CreateFAAcquisitionLines

### ISSUE THREAD

**Issue by DoniaMTAT** [microsoft/ALAppExtensions#20785]
Hi ALAppExtensions Team,

in Table 81 in Location Code  there is an event in CreateFAAcquisitionLines OnAfterCreateFAAcquisitionLines(FAGenJournalLine, Rec). 
It would be really cool to have BalancingGenJnlLine in variable.

Cordially

MTAT Donia

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
