### ISSUE TITLE
[Event Request] OnAfterOnInitReport in (Standard Sales/ Purch Document) Reports

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#20783]
I need to access the OnInitReport trigger as part of a customization in ReportExtension.
Unfortunately, this is not available in the report extension object.

Would it be possible to implement a publisher for this in all Sales and Purchase Document Reports (i.e. 305 Standard Sales - Order Conf.)?
It would be good if there was a possibility in the Report Extension itself.

**Comment by AlexanderYakunin** [comment]
No, we cannot implement events in all reports, we need list of reports to implement.
