### ISSUE TITLE
[Extensibility Request Protected vars] Document Reports

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#20782]
We use in our business solution reportextension on the microsoft standard document reports.
For example 1305 Standard Sales - Order Conf.

Now we want to access the variables used in the standard request page to make visibility operations.
Would be nice if all variables used on request pages were also protected vars (for all Standard sales and Purchase document reports)

in general I'd wish if all variables were protected ;-)

**Comment by dnpb** [comment]
> in general I'd wish if all variables were protected ;-)

Please, no! Then the authors of the base objects could never confidently reason about how their own stuff works, as any random extension could mangle all their variables. There's a reason that `GlobalVarAccess` was deprecated/removed. ;-)

**Comment by Busslar** [comment]
well, the ones from the request page would be enough for me 👍

**Comment by JesperSchulz** [comment]
Was fixed in version 22.
