### ISSUE TITLE
[Event Change Request] table 36 "Sales Header" - OnBeforeUpdateSalesLineAmounts 

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#20794]
Could you please change the event signature of the event `OnBeforeUpdateSalesLineAmounts` to include the parameter `SalesHeader` by reference?
```al
[IntegrationEvent(false, false)]
//+Change
//-local procedure OnBeforeUpdateSalesLineAmounts(SalesHeader: Record "Sales Header"; xSalesHeader: Record "Sales Header"; CurrentFieldNo: Integer; var IsHandled: Boolean)
local procedure OnBeforeUpdateSalesLineAmounts(var SalesHeader: Record "Sales Header"; xSalesHeader: Record "Sales Header"; CurrentFieldNo: Integer; var IsHandled: Boolean)
//+Change
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 48695.
