### ISSUE TITLE
[Request for external] codeunit 9176 "User Settings" with new GetAllowedCompaniesForCurrentUser

### ISSUE THREAD

**Issue by deadmouse** [microsoft/ALAppExtensions#20795]
I would like the procedure _GetAllowedCompaniesForCurrentUser_ from **_codeunit 9175 "User Settings Impl."_** to be accesible from **_codeunit 9176 "User Settings"_**, so I expect something like this:

```
codeunit 9176 "User Settings"
{
    procedure GetAllowedCompaniesForCurrentUser(var TempComany: Record Company)
    var
        UserSettingsImpl: Codeunit "User Settings Impl.";
    begin
        UserSettingsImpl.GetAllowedCompaniesForCurrentUser(TempCompany);
    end;
}
```

**Comment by darjoo** [comment]
Hi @deadmouse, what do you need this for?

**Comment by deadmouse** [comment]
Because if I do:

```
Company.FindSet();
repeat
...
```

And a user doesn't have rights to read X company, an error is thrown saying you don't have access. I want to avoid that error.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: <None>.
