### ISSUE TITLE
[EventRequest] OnAfterGetBBAN in Table 270 "Bank Account"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20793]
Hello, please consider adding the following event to Table 270 "Bank Account":

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetBBAN(var Rec: Record "Bank Account")
    begin
    end;

and raise it accordingly:

    procedure GetBBAN()
    begin
        if (ABI <> '') and (CAB <> '') and ("Bank Account No." <> '') then
            BBAN := AbiCabCodes.CalcBBAN(ABI, CAB, "Bank Account No.")
        else
            BBAN := '';
        IBAN := '';

        OnAfterGetBBAN(Rec);
    end;

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49479.
