### ISSUE TITLE
[Event Request] Codeunit 6529 "Item Tracking Navigate Mgt." OnFindTrackingRecordsItemLedgEntry

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [microsoft/ALAppExtensions#2080]
We need the the following event in codeunit 6529 "Item Tracking Navigate Mgt." in function FindTrackingRecords (logic similar to page 344 Navigate)
![image](https://user-images.githubusercontent.com/30231314/56046357-bb6e2900-5d4b-11e9-9416-62a861b465ac.png)

Also function InsertBufferRec should be external.

**Comment by AlexanderYakunin** [comment]
This event cannot be added inside of CASE statement, it can be added AFTER end of CASE statement and before UNTIL. Does it make sense?

**Comment by AndriusAndrulevicius** [comment]
yes, that would be suitable.
