### ISSUE TITLE
[Event-Change Request] codeunit 13 "Gen. Jnl.-Post Batch" - OnBeforeUpdateRecurringAmt

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20807]
Dear ALAppExtensions team,

through this issue we would like to request a change of event publisher `OnBeforeUpdateRecurringAmt` in Codeunit 13 `Gen. Jnl.-Post Batch` from:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateRecurringAmt(var GenJnlLine2: Record "Gen. Journal Line"; var Updated: Boolean; var IsHandled: Boolean)
begin
end;
```
to:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateRecurringAmt(var GenJnlLine2: Record "Gen. Journal Line"; var Updated: Boolean; var GLEntry: Record "G/L Entry"; var GLAcc: Record "G/L Account" ;var GenJnlAlloc: Record "Gen. Jnl. Allocation";  var IsHandled: Boolean);
begin
end;
```
adding the var parameters GLEntry, GLAcc and GenJnlAlloc to the Event publisher.
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49203.
