### ISSUE TITLE
[Extensibility Request] All Sales / Purchase Document Subform Pages

### ISSUE THREAD

**Issue by chrischbo** [microsoft/ALAppExtensions#20801]
Hi,

due to the same issue as explained here (https://github.com/microsoft/ALAppExtensions/issues/17972), we would kindly request to add an CurrPage.Update() to the "Item Reference No." field on all sales and purchase document subforms. We need this to have an existing record to run our code for the new price calculation.

f.e.:
![image](https://user-images.githubusercontent.com/15926999/199246878-d5ee0cf5-47d8-46a6-8ea8-2122ce7b8030.png)

Min. requested pages:

- page 46 "Sales Order Subform"
- page 47 "Sales Invoice Subform"
- page 54 "Purchase Order Subform"
- page 55 "Purch. Invoice Subform"
- page 95 "Sales Quote Subform"
- page 96 "Sales Cr. Memo Subform"
- page 97 "Purchase Quote Subform"
- page 98 "Purch. Cr. Memo Subform"
- page 6631 "Sales Return Order Subform"
- page 6641 "Purchase Return Order Subform"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53019.
