### ISSUE TITLE
[Event Request] Codeunit 5488 - Graph Mgt - Reports - OnBeforeSetUpTrialBalanceAPIData

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20802]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnBeforeSetUpTrialBalanceAPIData` to Codeunit 5488 `Graph Mgt - Reports` with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeSetUpTrialBalanceAPIData(var TrialBalanceEntityBuffer: Record "Trial Balance Entity Buffer"; var IsHandled: Boolean)
begin
end;
```
which would be called as follows in `SetUpTrialBalanceAPIData`:
```AL
procedure SetUpTrialBalanceAPIData(var TrialBalanceEntityBuffer: Record "Trial Balance Entity Buffer")
var
    GLAccount: Record "G/L Account";
    NewTrialBalanceEntityBuffer: Record "Trial Balance Entity Buffer";
    DateFilter: Text;
    // >>>> New >>>>>>>>>>>>>>>>
    IsHandled: Boolean;
    // <<<< New <<<<<<<<<<<<<<<<
begin
    // >>>> New >>>>>>>>>>>>>>>>
    OnBeforeSetUpTrialBalanceAPIData(TrialBalanceEntityBuffer, IsHandled);
    if IsHandled then
        exit;
    // <<<< New <<<<<<<<<<<<<<<<
    DateFilter := StrSubstNo('%1', DelChr(TrialBalanceEntityBuffer.GetFilter("Date Filter"), '<>', ''''));
    if DateFilter = '' then
        DateFilter := Format(Today);
...
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49203.
