### ISSUE TITLE
[EventRequest] OnAfterLookupPostCode in Table 5050 "Contact"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20818]
Hello, please consider adding the following event to Table 5050 "Contact":

    [IntegrationEvent(false, false)]
    local procedure OnAfterLookupPostCode(var City: Text; var PostCode: Code[20]; var TerritoryCode: Code[10])
    begin
    end;

and raise it accordingly on field 91 "Post Code":

            trigger OnLookup()
            begin
                OnBeforeLookupPostCode(Rec, PostCode);

                PostCode.LookupPostCode(City, "Post Code", County, "Country/Region Code");

                OnAfterLookupPostCode(City, "Post Code", "Territory Code");       
            end;

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49203.
