### ISSUE TITLE
[Event Request] OnJobCalcWIPOnBeforeModifyJob in codeunit 1000 "Job Calculate WIP"

### ISSUE THREAD

**Issue by sannar** [microsoft/ALAppExtensions#20812]
Hi

We have a case where when calculating WIP for a job, we would need to be able to change the value of the variable JobComplete before moving further on with the WIP entry calculation and creation in codeunit 1000 "Job Calculate WIP".

Please consider adding the following event publisher in codeunit 1000 "Job Calculate WIP"

```
[IntegrationEvent(false, false)]
local procedure OnJobCalcWIPOnBeforeModifyJob(var Job: Record Job; var JobComplete: Boolean)
begin
end;
```

To be raised in procedure JobCalcWIP accordingly

```
Job.TestBlocked;
Job.TestField("WIP Method");
Job."WIP Posting Date" := WIPPostingDate;
if (Job."Ending Date" = 0D) and Job.Complete then
    Job.Validate("Ending Date", WIPPostingDate);
JobComplete := Job.Complete and (WIPPostingDate >= Job."Ending Date");
OnJobCalcWIPOnBeforeModifyJob(Job, JobComplete) // <-- NEW EVENT
Job.Modify();
```

Thank you in advance!

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
