### ISSUE TITLE
[Enum Request] - Table 12174 "Customer Bill Header" - Field 15 "Type"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20817]
Hello,

we ask you to transform the Option field 

> 15 "Type" 

on table 

> 12174 "Customer Bill Header" 

to Enum, in order to allow us to extend it with custom values.

Thank you !

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
