### ISSUE TITLE
[EventRequest] OnBeforeIsLowLevelOk in Table 5870 "BOM Buffer"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20821]
Hello, please consider adding the following event to Table 5870 "BOM Buffer":

> [IntegrationEvent(false, false)]
> local procedure OnBeforeIsLowLevelOk(VAR BomBuffer: Record "BOM Buffer"; var IsHandled: Boolean)
> begin
> end;

and raise it accordingly:

>     local procedure IsLowLevelOk(LogWarning: Boolean; var BOMWarningLog: Record "BOM Warning Log"): Boolean
>     var
>         Item: Record Item;
>         IsHandled: Boolean;
>     begin
>         OnBeforeIsLowLevelOk(Rec, IsHandled);
>         if IsHandled then
>             exit(true);
> 
>         if Type <> Type::Item then
>             exit(true);
>         if "No." = '' then
>             exit(true);
> 
>         Item.Get("No.");
> 
>         if TraverseIsLowLevelOk(Item) then
>             exit(true);
> 
>         if LogWarning then
>             BOMWarningLog.SetWarning(StrSubstNo(Text001, Item."No."), DATABASE::Item, Item.GetPosition);
>     end;

Thank you!

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
