### ISSUE TITLE
[Enum Request] Table 7000003 - Field 24 "Status"

### ISSUE THREAD

**Issue by DaRuizf** [microsoft/ALAppExtensions#20826]
Hello,
we need to be able to extend the options of field 24 - "Status" in table 7000003 - "Posted Cartera Doc.".
Could you please change it into an enum?

(The same field is in table 7000004 - "Closed Cartera Doc.")

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
