### ISSUE TITLE
[EventRequest] OnBeforeCalcUnitCost in Table 5870 "BOM Buffer"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20820]
Hello, please consider adding the following event to Table 5870 "BOM Buffer":

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcUnitCost(VAR BomBuffer: Record "BOM Buffer"; UsePurchPrice: Boolean; var IsHandled: Boolean)
    begin
    end;

and raise it accordingly:

    procedure CalcUnitCost()
        var isHandled: Boolean;
    begin
        OnBeforeCalcUnitCost(Rec, UsePurchPrice, IsHandled);
        if IsHandled then
             exit;

        "Total Cost" := CalcDirectCost + CalcIndirectCost;
        "Unit Cost" := 0;
        if "Qty. per Top Item" <> 0 then
            "Unit Cost" := Round("Total Cost" / "Qty. per Top Item", 0.00001);
    end;

Thank you!

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
