### ISSUE TITLE
[Enum Request] Table 21 "Cust. Ledger Entry" - Field 7000001 "Document Situation"

### ISSUE THREAD

**Issue by DaRuizf** [microsoft/ALAppExtensions#20828]
Hello,
we need to be able to extend the options of field 7000001 - "Document Situation" in table 21 - "Cust. Ledger Entry".
Could you please change it into an enum?

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
