### ISSUE TITLE
[Enum Request] Table 7000005 - Field 6 "Dealing Type"

### ISSUE THREAD

**Issue by DaRuizf** [microsoft/ALAppExtensions#20827]
Hello,
we need to be able to extend the options of field 6 - "Dealing type" in table 7000005 - "Bill Group".
Could you please change it into an enum?

(The same field is in table 7000006 - "Posted Bill Group" and table 7000007 - "Closed Bill Group")

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
