### ISSUE TITLE
[EnumRequest] Table 7000002 - Field 40 - "Document type"

### ISSUE THREAD

**Issue by DaRuizf** [microsoft/ALAppExtensions#20823]
Hello,
we need to be able to extend the  options of field 40 - "Document type" in table 7000002 - "Cartera Doc.". 
Could you please change it into an enum?

(It also'll affect to the same field in tables 7000003 - "Posted Cartera Doc." and 7000004 - "Closed Cartera Doc.")

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
