### ISSUE TITLE
[Enum Request] Page 6057 "Contract Line Selection" - Variable "SelectionFilter" Option

### ISSUE THREAD

**Issue by ZsomborCsaszi** [microsoft/ALAppExtensions#20824]
Dear ALAppExtensions team,

Could you please change the "SelectionFilter" global Option type variable to an Extensible Enum?

```
  SelectionFilter: Option "All Service Items","Service Items without Contract";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
