### ISSUE TITLE
[Event Request] Page 6057 - Contract Line Selection - OnAfterSetSelectionFilter

### ISSUE THREAD

**Issue by ZsomborCsaszi** [microsoft/ALAppExtensions#20822]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher OnAfterSetSelectionFilter in Page 6057 Contract Line Selection with the following signature:

```
    procedure SetSelectionFilter()
    begin
        case SelectionFilter of
            SelectionFilter::"All Service Items":
                SetRange("No. of Active Contracts");
            SelectionFilter::"Service Items without Contract":
                SetRange("No. of Active Contracts", 0);
        end;
        //>>New Event
        OnAfterSetSelectionFilter(Rec, SelectionFilter);
        //<<New Event
        CurrPage.Update(false);
    end;
```

Event: 

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetSelectionFilter(var ServiceItem: Record "Service Item"; SelectionFilter: Option "All Service Items","Service Items without Contract")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49170.
