### ISSUE TITLE
[EventRequest] OnBeforeIsReplenishmentOk in Table 5870 "BOM Buffer"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20834]
Hello, please consider adding the following event to Table 5870 "BOM Buffer":

> [IntegrationEvent(false, false)]
> local procedure OnBeforeIsReplenishmentOk(VAR BomBuffer: Record "BOM Buffer"; var IsHandled: Boolean)
> begin
> end;

and raise it accordingly:

>     local procedure IsReplenishmentOk(LogWarning: Boolean; var BOMWarningLog: Record "BOM Warning Log"): Boolean
>     var
>         Item: Record Item;
>         IsHandled: Boolean;
>     begin
>         OnBeforeIsReplenishmentOk(Rec, IsHandled);
>         if IsHandled then
>             exit(true);
> 
>         if Type <> Type::Item then
>             exit(true);
>         if "No." = '' then
>             exit(true);
> 
>         Item.Get("No.");
> 
>         if "Is Leaf" then begin
>             if Item."Replenishment System" in ["Replenishment System"::Purchase, "Replenishment System"::Transfer] then
>                 exit(true);
>             if LogWarning then
>                 BOMWarningLog.SetWarning(StrSubstNo(Text005, Item."No."), DATABASE::Item, Item.GetPosition);
>         end else begin
>             if Item."Replenishment System" in ["Replenishment System"::"Prod. Order", "Replenishment System"::Assembly] then
>                 exit(IsBOMOk(LogWarning, BOMWarningLog));
>             if LogWarning then
>                 BOMWarningLog.SetWarning(StrSubstNo(Text008, Item."No."), DATABASE::Item, Item.GetPosition);
>         end;
>     end;

Thank you!

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
