### ISSUE TITLE
[Event Request] table 246 "Requisition Line" - OnValidateReplenishmentSystemOnAfterSetStockkeepingUnit

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#20835]
field(99000903; "Replenishment System"; Enum "Replenishment System")
        {
            Caption = 'Replenishment System';

            trigger OnValidate()
            var
                StockkeepingUnit: Record "Stockkeeping Unit";
            begin
                ...
                StockkeepingUnit := Item.GetSKU("Location Code", "Variant Code");
                if Subcontracting then
                    StockkeepingUnit."Replenishment System" := StockkeepingUnit."Replenishment System"::"Prod. Order";
                OnValidateReplenishmentSystemOnAfterSetStockkeepingUnit(Rec, StockkeepingUnit, Subcontracting); //A108B0055.Event.21.00

                "Supply From" := '';

                case "Replenishment System" of
                ...
            end;
        }

    [IntegrationEvent(false, false)]
    local procedure OnValidateReplenishmentSystemOnAfterSetStockkeepingUnit(var RequisitionLine: Record "Requisition Line"; var StockkeepingUnit: Record "Stockkeeping Unit"; Subcontracting: Boolean)
    begin
        //A108B0055.Event.21.00
    end;

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
