### ISSUE TITLE
[Event Request] Codeunit 5845 - Get Inventory Report - OnBeforeCalcGLAccount

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#20830]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnBeforeCalcGLAccount` to Codeunit 5845 `Get Inventory Report` with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeCalcGLAccount(var GLAcc: Record "G/L Account"; var ReturnValue: Decimal; var IsHandled: Boolean)
begin
end;
```
which would be called as follows in `CalcGLAccount`:
```AL
local procedure CalcGLAccount(var GLAcc: Record "G/L Account"): Decimal
// >>>> New >>>>>>>>>>>>>>>>
var
    IsHandled: Boolean;
    ReturnValue: Decimal;
// <<<< New <<<<<<<<<<<<<<<<
begin
    with GLAcc do begin
        UpDateWindow(TableCaption, "No.", WindowPostingType);
        // >>>> New >>>>>>>>>>>>>>>>
        OnBeforeCalcGLAccount(GLAcc, ReturnValue, IsHandled);
        if IsHandled then
            exit(ReturnValue);
        // <<<< New <<<<<<<<<<<<<<<<

        CalcFields("Net Change");
        exit("Net Change");
    end;
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49170.
