### ISSUE TITLE
[Event Request] Codeunit 9802 : procedure Start() - OnBeforeStart(SessionIdVar); 

### ISSUE THREAD

**Issue by EHeirbaut** [microsoft/ALAppExtensions#20832]
Dear ALAppExtensions team,

We would like to request adding an event publisher OnBeforeStart in Codeunit 9802 "Log Activity Permissions" with the following signature:

  procedure Start()
    begin
        //>>New Event
        SessionIdVar := sessionid()
        OnBeforeStart(sessionidvar)
        //<<New Event
        TempTablePermissionBuffer.DeleteAll();
        if IsNull(EventReceiver) then
            EventReceiver := EventReceiver.NavPermissionEventReceiver(SessionIdVar); // change parameter to the variable
        EventReceiver.RegisterForEvents()
    end;

Event:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeStart(VAR SessionID: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Since this event request is for the System Application, we would need a justification for why this event is needed. Which scenario are you trying to support?

**Comment by EHeirbaut** [comment]
We provide functionality in our apps with which you can record a user session from another session and with which we can optimize the recorded data. This is used very much in permission setup projects where you have a consultant / application manager who is recording and an end user who is being recorded We need this event to be able to keep offering this functionality to our customers.

**Comment by JesperSchulz** [comment]
I think we can move forward with this request for the 22.1 release in May. I'll do one final internal code review and in it goes!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53793.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 54542.

**Comment by EHeirbaut** [comment]
Hi Jesper or colleague,

Thank you for adding the event. But alas, we can not use it yet because the eventually modified SessionId is not passed to the EventReceiver :

_codeunit 9802 "Log Activity Permissions"
    procedure Start()
    var
        SessionIdVar: Integer;
    begin
        SessionIdVar := SessionId();
        OnBeforeStart(SessionIdVar);
        TempTablePermissionBuffer.DeleteAll();
        if IsNull(EventReceiver) then
            EventReceiver := EventReceiver.NavPermissionEventReceiver(SessionId());  **--> instead of SessionId(), SessionIdVar has to be used here as parameter**

        EventReceiver.RegisterForEvents();
    end;_

Can that be fixed as soon as possible in a next update? 

Thnak you very much!

**Comment by JesperSchulz** [comment]
We'll look into it!

**Comment by EHeirbaut** [comment]
Hi Jesper,

Can you give an indication when this issue might be fixed?
I downloaded a new source last week and the code was unchanged.

To recall, it was about this error:

-------------------


Thank you for adding the event. But alas, we can not use it yet because the eventually modified SessionId is not passed to the EventReceiver :

_codeunit 9802 "Log Activity Permissions"
procedure Start()
var
SessionIdVar: Integer;
begin
SessionIdVar := SessionId();
OnBeforeStart(SessionIdVar);
TempTablePermissionBuffer.DeleteAll();
if IsNull(EventReceiver) then
EventReceiver := EventReceiver.NavPermissionEventReceiver(SessionId()); --> instead of SessionId(), SessionIdVar has to be used here as parameter

---------------------

Thank you very much!

Met vriendelijke groet / With kind regards,
Erik Heirbaut
____________________________________________________

Haagsemarkt 1
4813 BA Breda

M: +31(0)627 05 05 27
T:  +31(0)76 50 194 70

www.2-control.nl<http://www.2-control.nl/>

[Handtekening 201610]
    [cid:417141ef-cf1c-40f4-a011-84f6120c9167] <https://twitter.com/2Controlsocial>    [cid:9b35ad46-aafa-4974-af38-8e378f06799f] <https://www.linkedin.com/company/351586?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A351586%2Cidx%3A1-1-1%2CtarId%3A1461931314718%2Ctas%3A2-control>    [cid:ef9b302d-1a52-452c-bda3-29364f908ae7] <https://www.facebook.com/2control.authorizationbox/>

[cid:03620023-ce41-4e8e-be1a-026008436ff1]<https://2-control.nl/nl/werken-bij/vacatures/?utm_source=emailhandtekening/>








________________________________
Van: Jesper Schulz-Wedde ***@***.***>
Verzonden: donderdag 1 juni 2023 14:24
Aan: microsoft/ALAppExtensions ***@***.***>
CC: Erik Heirbaut ***@***.***>; Author ***@***.***>
Onderwerp: Re: [microsoft/ALAppExtensions] [Event Request] Codeunit 9802 : procedure Start() - OnBeforeStart(SessionIdVar); (Issue #20832)


We'll look into it!

**Comment by JesperSchulz** [comment]
The bug I created for you is still active. I will ping the responsible team.

**Comment by JesperSchulz** [comment]
Fixed. Will release with 22.4 in August.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11365.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 58495.
