### ISSUE TITLE
[EventRequest] OnBeforeIsBOMOk in Table 5870 "BOM Buffer"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20838]
Hello, please consider adding the following event to Table 5870 "BOM Buffer":

> [IntegrationEvent(false, false)]
> local procedure OnBeforeIsBOMOk(VAR BomBuffer: Record "BOM Buffer"; var IsHandled: Boolean)
> begin
> end;

and raise it accordingly:

>     local procedure IsBOMOk(LogWarning: Boolean; var BOMWarningLog: Record "BOM Warning Log"): Boolean
>     var
>         Item: Record Item;
>         IsHandled: Boolean;
>     begin
>         OnBeforeIsBOMOk(Rec, IsHandled);
>         if IsHandled then
>             exit(true);
> 
>         if Type <> Type::Item then
>             exit(true);
>         if "No." = '' then
>             exit(true);
> 
>         Item.Get("No.");
> 
>         case Item."Replenishment System" of
>             Item."Replenishment System"::Assembly:
>                 begin
>                     Item.CalcFields("Assembly BOM");
>                     if Item."Assembly BOM" then
>                         exit(true);
>                     if LogWarning then
>                         BOMWarningLog.SetWarning(StrSubstNo(Text006, Item."No."), DATABASE::Item, Item.GetPosition);
>                 end;
>             Item."Replenishment System"::"Prod. Order":
>                 begin
>                     if Item."Production BOM No." <> '' then
>                         exit(true);
>                     if LogWarning then
>                         BOMWarningLog.SetWarning(StrSubstNo(Text007, Item."No."), DATABASE::Item, Item.GetPosition);
>                 end;
>             else
>                 exit(true);
>         end;
>     end;

Thank you!

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
