### ISSUE TITLE
Required SaveValues  property on base report - Whse.-Shipment - Create Pick (7318, Report Request)

### ISSUE THREAD

**Issue by agirdhar007** [microsoft/ALAppExtensions#20848]
Dear Team,

In Base report "Whse.-Shipment - Create Pick (7318)", we require a SaveValues= TRUE property on request page.

For one of our customizations, we require to save the filters used by client last time.
We have added PerSource, PerZone, PerDestination, PerItem, PerLine and PerBin option on report (7318) and we want it to get saved on request page as per the SaveValues property.

Can you please let me know when we can expect the changes, please?

Thanks

**Comment by JakovljevicDusan** [comment]
Hi @agirdhar007, this can be significant change for some clients. Is it still active request or you've managed to find a workaround?

**Comment by alexei-dobriansky** [comment]
No response
