### ISSUE TITLE
[EventRequest] OnBeforeIsPublicCompany in Table 18 "Customer"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20843]
Hello, please consider adding the following event to Table 18 "Customer":

> [IntegrationEvent(false, false)]
> local procedure OnBeforeIsPublicCompany (var Customer: Record "Customer"; var Result: Boolean; var IsHandled: Boolean)
> begin
> end;

and raise it accordingly:

>     local procedure IsPublicCompany(): Boolean
>     var IsHandled: Boolean;
>           Result: Boolean;
>     begin
>         OnBeforeIsPublicCompany(Rec, Result, IsHandled);
>         if IsHandled then
>             EXIT(Result)
> 
>         EXIT(STRLEN("PA Code") = 6);
>     end;

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49479.
