### ISSUE TITLE
[EventRequest] OnBeforeLookupGLAccountFilter in Table 841 "Cash Flow Account"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20840]
Hello, please consider adding the following event to Table 841 "Cash Flow Account":

>     [IntegrationEvent(false, false)]
>     procedure OnBeforeLookUpGLAccountFilter(var Rec: record "Cash Flow Account"; var IsHandled: Boolean)
>     begin
>     end;

and raise it accordingly on field 37 "G/L Account Filter" :

>             trigger OnLookup()
>             var
>                 GLAccList: Page "G/L Account List";
>                 IsHandled: Boolean;
> 
>             begin
>                 IsHandled := false;
>                 OnBeforeLookUpGLAccountFilter(Rec, IsHandled);
>                 if IsHandled then
>                     exit;
> 
>                 GLAccList.LookupMode(true);
>                 if GLAccList.RunModal = ACTION::LookupOK then
>                     "G/L Account Filter" := CopyStr(GLAccList.GetSelectionFilter, 1, MaxStrLen("G/L Account Filter"));
>             end;

Thank you!

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
