### ISSUE TITLE
[Event Parameter Request] table 37 "Sales Line" - OnAfterAssignItemValues

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#20842]
//OnAfterAssignItemValues(Rec,Item); A108F0025.Event.21.00.o
        OnAfterAssignItemValues(Rec, Item, SalesHeader); //A108F0025.Event.21.00.n

    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignItemValues(var SalesLine: Record "Sales Line"; Item: Record Item; SalesHeader: Record "Sales Header")
    begin
        //A108F0025.Event21.00 SalesHeader parameter
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49170.
