### ISSUE TITLE
[EventRequest] OnBeforeInsertNewLine in Table 846 "Cash Flow Worksheet Line", inside "InsertNewLinesForUnpostedDocuments" procedure

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20852]
Hello, please consider adding the following event to Table 846 "Cash Flow Worksheet Line", inside "InsertNewLinesForUnpostedDocuments" procedure:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeInsertNewLine(var CFWrkstLine: Record "Cash Flow Worksheet Line"; PaymentLines: Record "Payment Lines")
begin
end;
```

and raise it accordingly:

>     procedure InsertNewLinesForUnpostedDocuments(CashFlowForecast: Record "Cash Flow Forecast"; var MaxPmtTolerance: Decimal)
>     var
>         GeneralLedgerSetup: Record "General Ledger Setup";
>     ...
>     ...
>     ...
>                             "Payment Discount" := 0;
>                         end;
>                 end else
>                     "Cash Flow Date" := CalcDate(PaymentLines."Due Date Calculation", "Document Date");
> 
>             **OnBeforeInsertNewLine(Rec,PaymentLines);**
> 
>             if "Amount (LCY)" <> 0 then
>                 Insert(true);
> 
>         until PaymentLines.Next() = 0;
> 
>         MaxPmtTolerance := 0;
>     end;

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49479.
