### ISSUE TITLE
Automatic updates of Business Central online

### ISSUE THREAD

**Issue by GoomVDS** [microsoft/ALAppExtensions#2085]
Good morning, 

I have some doubts about the automatic updates of BC online: In BC online can we do 
backups?, when will Microsoft update BC online, notify the partner in some way?, and if any extension itself makes the Microsoft update fail, what happens ?, does not update BC online to the latest version?

Thanks´

Greetings.

**Comment by ikoletic** [comment]
You can read about BC online backups [here](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/faq#how-often-are-production-databases-backed-up) and access them by contacting support. [Admin center](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center) (released in April 2019) offers capabilities you're inquiring about. 
Please submit your other questions on [business central community ](https://community.dynamics.com/business/f/758) or on [BC development yammer groups](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035).
