### ISSUE TITLE
[Event-Change Request] Codeunit 1006 "Copy Job" - OnBeforeCopyJobTasks

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#20851]
Dear ALAppExtensions team,

through this issue we would like to request a change of event publisher `OnBeforeCopyJobTasks` in Codeunit 1006 `Copy Job` from:

```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeCopyJobTasks(var SourceJob: Record Job; var TargetJob: Record Job; var IsHandled: Boolean)
begin
end;
```

to:

```AL
[IntegrationEvent(true, false)]
local procedure OnBeforeCopyJobTasks(var SourceJob: Record Job; var TargetJob: Record Job; CopyDimensions: Boolean; CopyQuantity: Boolean; CopyPrices: Boolean; JobTaskRangeFrom: Code[20]; JobTaskRangeTo: Code[20]; JobPlanningLineSource: Option "Job Planning Lines","Job Ledger Entries"; JobLedgerEntryType: Option " ",Usage,Sale; var IsHandled: Boolean)
begin
end;
```

adding the paramters CopyDimensions, CopyQuantity, CopyPrices, JobTaskRangeFrom, JobTaskRangeTo, JobPlanningLineSource and JobLedgerEntryType as well as adding the Sender to the EventPublisher. 

Thanks in advance!

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
