### ISSUE TITLE
[Enum Request] - Table 12203 "Fattura Header" - Field 7 "Entry Type"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20863]
Hello,

we ask you to transform the Option field

7 "Entry Type"

on Table 12203 "Fattura Header" to "Enum", in order to allow us to extend it with custom values.

Thank you !

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51600.
