### ISSUE TITLE
[Enum Request] - Table 12198 "Fattura Code" - Field 2 "Type"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20862]
Hello,

we ask you to transform the Option field

2 "Type"

on Table 12198 "Fattura Code" to "Enum", in order to allow us to extend it with custom values.

Thank you !

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
