### ISSUE TITLE
[Event Change Request] table 167 Job - OnBeforeAssistEdit

### ISSUE THREAD

**Issue by jorland1** [microsoft/ALAppExtensions#20874]
Hi,
could you please add the global variable `NoSeriesMgt` as a var parameter to the event `OnBeforeAssistEdit`?

The resulting signature would be:
``` al
local procedure OnBeforeAssistEdit(
    var Job: Record Job; var OldJob: Record Job; var Result: Boolean;
    // >>> NEW
    var NoSeriesMgt: Codeunit NoSeriesManagement;
    // <<< NEW
    var IsHandled: Boolean)
```

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49203.
