### ISSUE TITLE
Teaching Tips on RequestPages

### ISSUE THREAD

**Issue by adejsy** [microsoft/ALAppExtensions#20876]
Teaching Tips are an extremely useful feature within Business Central.

They can be added to the requestpage control on reports. However, they are not shown automatically when the user lands on the requestpage for the first time, as is the case for regular page objects.

This means the user is likely missing that there are teaching tips on the request page unless they click on the caption to force it to become visible as per "replaying" Teaching Tips on page objects.

This behaviour can be replicated in BC21.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
