### ISSUE TITLE
APIv2 Unit of Measure Code for Purchase Lines with G/L Account

### ISSUE THREAD

**Issue by Grueslayer** [microsoft/ALAppExtensions#20879]
In `APIV2 - Purch. Inv. Lines` for `unitOfMeasureCode` (and `unitOfMeasureId`) `Purch. Inv. Aggregator.VerifyCanUpdateUOM` is called. This prevents changing / setting the UOM for lines with G/L Account. 
We need to remove this code to be able to create an invoice with correct UOM like given on the real invoice document. We are able to do this in the page, why should this be prohibited by API?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49407.
