### ISSUE TITLE
[Enum Request] - 12177 "Issued Customer Bill Header" - Field 15 "Type"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20873]
Hello,

we ask you to transform the Option field

15 "Type"

on Table 12177 "Issued Customer Bill Header" to "Enum", in order to allow us to extend it with custom values.

Thank you !

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
