### ISSUE TITLE
[Event Request] OnBeforeUpdateCurrencyFactor - Job Planning Line

### ISSUE THREAD

**Issue by LewisHyettTES** [microsoft/ALAppExtensions#20877]
Please could you add an event to the procedure "UpdateCurrencyFactor" on the Job Planning Line table?

We have a customer who wishes to use a secondary table to record a fixed exchange rate for a Job. 

This would be as follows:
```
procedure UpdateCurrencyFactor()
    var
        IsHandled: Boolean;
    begin
        OnBeforeUpdateCurrencyfactor(Rec, IsHandled);
        if IsHandled then
            exit;

        if "Currency Code" <> '' then begin
            if "Currency Date" = 0D then
                CurrencyDate := WorkDate()
            else
                CurrencyDate := "Currency Date";
            OnUpdateCurrencyFactorOnBeforeGetExchangeRate(Rec, CurrExchRate);
            "Currency Factor" := CurrExchRate.ExchangeRate(CurrencyDate, "Currency Code");
        end else
            "Currency Factor" := 0;
    end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateCurrencyfactor(var JobPlanningLine: Record "Job Planning Line"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49203.
