### ISSUE TITLE
[Event Request] table 167 Job - OnValidateNoOnBeforeTestManualNoSeries

### ISSUE THREAD

**Issue by jorland1** [microsoft/ALAppExtensions#20875]
Hi,
could you please add an event publisher `OnValidateNoOnBeforeTestManualNoSeries` to the `OnValidate` trigger of the `"No."` field?

The call would be:
``` al
field(1; "No."; Code[20])
{
    Caption = 'No.';

    trigger OnValidate()
    var
        // >>> NEW
        IsHandled: Boolean;
        // <<< NEW
    begin
        if "No." <> xRec."No." then begin
            JobsSetup.Get();
            // >>> NEW
            IsHandled := false;
            OnValidateNoOnBeforeTestManualNoSeries(Rec, IsHandled);
            if not IsHandled then
            // <<< NEW
                NoSeriesMgt.TestManual(JobsSetup."Job Nos.");
            "No. Series" := '';
        end;
    end;
}
```

The signature would be:
``` al
[IntegrationEvent(false, false)]
local procedure OnValidateNoOnBeforeTestManualNoSeries(var Job: Record Job; var IsHandled: Boolean)
```

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49203.
