### ISSUE TITLE
APIv2 Purchase Credit Memos missing

### ISSUE THREAD

**Issue by Grueslayer** [microsoft/ALAppExtensions#20878]
There is no implementation for the Purchase Credit Memos in APIv2 (other purchase documents are implemented)

**Comment by onbuyuka** [comment]
There is no available purchase credit memo API as of now. We have it in our backlog but it is not planned for this release. If this is urgent for you, you can always create your own custom API for purchase credit memo.
Please check out [Developing a Custom API](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-custom-api)
for the general custom API walkthrough and [APIV2SalesCreditMemos](https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/APIV2/app/src/pages/APIV2SalesCreditMemos.Page.al) for inspiration.

**Comment by Grueslayer** [comment]
It's not only the API, you need to

- create the aggregator table
- the aggregator codeunit
- duplicate complete dimensionlines api, because it relates on an non extensible enum
- duplicate the attached document files api (like document lines)

**Comment by onbuyuka** [comment]
I agree, that's why it is in our backlog and it is not something we can provide in short term.
