### ISSUE TITLE
[Event Request] codeunit 99000774 "Calculate Routing Line" - OnCreateLoadForwardOnBeforeWriteCreateCapNeed

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#20883]
Same problem as issue #20882

    local procedure CreateLoadForward(TimeType: Enum "Routing Time Type"; Write: Boolean; LoadFactor: Decimal)
        ...
                if AvQtyBase * LoadFactor >= 0 then
                    RemainNeedQtyBase := RemainNeedQtyBase - AvQtyBase * LoadFactor;
                OnCreateLoadForwardOnBeforeWriteCreateCapNeed(ProdOrderRoutingLine, TimeType, RelevantEfficiency, RemainNeedQtyBase, RemainNeedQty, CurrentRounding, Write); //A108B0093.Event21.00.n
                if Write then begin
                    RemainNeedQty := Round(RemainNeedQtyBase / CurrentTimeFactor, CurrentRounding);
                    CreateCapNeed(
                      CalendarEntry.Date, CalendarEntry."Starting Time", EndingTime,
                      Round(AvQtyBase * LoadFactor / CurrentTimeFactor, CurrentRounding), TimeType, 0);
        ...
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCreateLoadForwardOnBeforeWriteCreateCapNeed(ProdOrderRoutingLine: Record "Prod. Order Routing Line"; TimeType: Enum "Routing Time Type"; var RelevantEfficiency: Decimal; var RemainNeedQtyBase: Decimal; var RemainNeedQty: Decimal; CurrentRounding: Decimal; Write: Boolean)
    begin
        //A108B0093.Event21.00
    end;

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
