### ISSUE TITLE
[Event change] include PreviewMode in the Codeunit 80 Sales-Post OnAfterPostSalesDoc publisher

### ISSUE THREAD

**Issue by OlekIvanov** [microsoft/ALAppExtensions#20889]
The PreviewMode is included in OnBeforePostSalesDoc and OnBeforePostLines publishers, but not in OnAfterPostSalesDoc

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49203.
