### ISSUE TITLE
IncludeEnder in OnPostUpdateOrderLineOnSetDefaultQtyBlank

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#20886]
Please include Sender in OnPostUpdateOrderLineOnSetDefaultQtyBlank in Codeunits 80 and 90.

We would like to call WhseHandlingRequiredExternal in this trigger.

Codeunit 90 "Purch.-Post"
old:
    [IntegrationEvent(false, false)]
    local procedure OnPostUpdateOrderLineOnSetDefaultQtyBlank(var PurchaseHeader: Record "Purchase Header"; var TempPurchaseLine: Record "Purchase Line" temporary; PurchPost: Record "Purchases & Payables Setup"; var SetDefaultQtyBlank: Boolean)
    begin
    end;

new:
    [IntegrationEvent(**true**, false)]
    local procedure OnPostUpdateOrderLineOnSetDefaultQtyBlank(var PurchaseHeader: Record "Purchase Header"; var TempPurchaseLine: Record "Purchase Line" temporary; **PurchSetup**: Record "Purchases & Payables Setup"; var SetDefaultQtyBlank: Boolean)
    begin
    end;

codeunit 80 "Sales-Post"
old:
    [IntegrationEvent(false, false)]
    local procedure OnPostUpdateOrderLineOnSetDefaultQtyBlank(var SalesHeader: Record "Sales Header"; var TempSalesLine: Record "Sales Line" temporary; SalesSetup: Record "Sales & Receivables Setup"; var SetDefaultQtyBlank: Boolean)
    begin
    end;

new:
    [IntegrationEvent(**true**, false)]
    local procedure OnPostUpdateOrderLineOnSetDefaultQtyBlank(var SalesHeader: Record "Sales Header"; var TempSalesLine: Record "Sales Line" temporary; SalesSetup: Record "Sales & Receivables Setup"; var SetDefaultQtyBlank: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49203.
