### ISSUE TITLE
[Event change] codeunit 99000837 "Prod. Order Line-Reserve" - OnBeforeTransferPOLineToItemJnlLineReservEntry

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#20885]
This is actually more of a code change request.
In codeunits
codeunit 99000837 "Prod. Order Line-Reserve" - TransferPOLineToItemJnlLine
and
codeunit 1032 "Job Planning Line-Reserve" - TransferJobLineToItemJnlLine

variable TransferQty can reach value zero but still the loop
until EndLoop or (TransferQty = 0);
goes on looping.

                if TransferQty <> 0 then //A108P0011.n
                    if ReservEngineMgt.NEXTRecord(OldReservEntry) = 0 then

The same kind of code in
codeunit 99000838 "Prod. Order Comp.-Reserve" - TransferPOCompToItemJnlLineCheckILE
is correct were a code change between NAV2017 and BC13 has fixed this particular issue:

                    EndLoop := TransferQty = 0;
                    if not EndLoop then
                        if ReservEngineMgt.NEXTRecord(OldReservEntry) = 0 then

Can you please fix it.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10414.
