### ISSUE TITLE
ModifyLine is not set in OnBeforeClearSalesLineQtyToShipReceive and OnBeforeClearPurchLineQtyToShipReceive

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#20881]
In codeunit 5760 "Whse.-Post Receipt" on the triggers  OnBeforeClearSalesLineQtyToShipReceive and OnBeforeClearPurchLineQtyToShipReceive the variable ModifyLine should declare, that the line should be modified.

Becasuse ModifyLine is only set later, this trigger cannot be handled correctly.

We need a new trigger OnAfterClearSalesLineQtyToShipReceive and OnAfterClearPurchLineQtyToShipReceive

    local procedure ClearSalesLineQtyToShipReceive(var SalesLine: Record "Sales Line"; WhseRcptLine2: Record "Warehouse Receipt Line"; var ModifyLine: Boolean)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeClearSalesLineQtyToShipReceive(SalesLine, WhseRcptLine2, ModifyLine, IsHandled);
        if IsHandled then
            exit;

        with WhseRcptLine2 do
            if "Source Document" = "Source Document"::"Sales Order" then begin
                ModifyLine := SalesLine."Qty. to Ship" <> 0;
                if ModifyLine then
                    SalesLine.Validate("Qty. to Ship", 0);
            end else begin
                ModifyLine := SalesLine."Return Qty. to Receive" <> 0;
                if ModifyLine then
                    SalesLine.Validate("Return Qty. to Receive", 0);
            end;

      --> OnAfterClearSalesLineQtyToShipReceive(SalesLine, WhseRcptLine2, ModifyLine);
    end;

    local procedure ClearPurchLineQtyToShipReceive(var PurchLine: Record "Purchase Line"; WhseRcptLine2: Record "Warehouse Receipt Line"; var ModifyLine: Boolean)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeClearPurchLineQtyToShipReceive(var PurchLine, WhseRcptLine2, ModifyLine, IsHandled);
        if IsHandled then
            exit;

        with WhseRcptLine2 do
            if "Source Document" = "Source Document"::"Purchase Order" then begin
                ModifyLine := PurchLine."Qty. to Receive" <> 0;
                if ModifyLine then
                    PurchLine.Validate("Qty. to Receive", 0);
            end else begin
                ModifyLine := PurchLine."Return Qty. to Ship" <> 0;
                if ModifyLine then
                    PurchLine.Validate("Return Qty. to Ship", 0);
            end;

      --> OnAfterClearPurchLineQtyToShipReceive(var PurchLine, WhseRcptLine2, ModifyLine);
    end;

in codeunit 5763 "Whse.-Post Shipment" the whole ClearSalesLine and ClearPurchLine routines are missing and we need new triggers there as well with OnBeforeClear with isHandled and OnAfterCkear as described above.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49473.
