### ISSUE TITLE
[Event Request] codeunit 99000774 "Calculate Routing Line" - OnCreateLoadBackOnBeforeWriteCreateCapNeed

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#20882]
We need this event to actually fix a base app bug in possible rounding issues between seconds, minutes and hours at two of our customers. We can see in TFS that we created this bugfix in March 2018, but we are sorry to say that we are having a hard time to reproduce this in BC21.00. Removing the specific fix in BC14 at one of our customers immediately raises the endless looping again in a customer ACC environment.

Standard line of code:
RemainNeedQtyBase := RemainNeedQtyBase - AvQtyBase;
should actually be
RemainNeedQtyBase := Round(RemainNeedQtyBase, CurrentRounding); //A108B0093.n
to make sure that StopLoop becomes true.
But as we all know if you can't reproduce it, you cannot just implement a change in code. Therefore, we request an event to only fix it at our own end.

    local procedure CreateLoadBack(TimeType: Enum "Routing Time Type"; Write: Boolean)
        ...
                StartingTime :=
                  CalendarMgt.CalcTimeSubtract(
                    CalendarEntry."Ending Time",
                    Round(AvQtyBase * 100 / RelevantEfficiency / ConCurrCap, 1, '>'));
                RemainNeedQtyBase := RemainNeedQtyBase - AvQtyBase;
                OnCreateLoadBackOnBeforeWriteCreateCapNeed(ProdOrderRoutingLine, TimeType, RelevantEfficiency, RemainNeedQtyBase, RemainNeedQty, CurrentRounding, Write); //A108B0093.Event21.00.n
                if Write then begin
                    RemainNeedQty := Round(RemainNeedQtyBase / CurrentTimeFactor, CurrentRounding);
                    CreateCapNeed(
                      CalendarEntry.Date, StartingTime, CalendarEntry."Ending Time",
                      Round(AvQtyBase / CurrentTimeFactor, CurrentRounding), TimeType, 1);
        ...
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCreateLoadBackOnBeforeWriteCreateCapNeed(ProdOrderRoutingLine: Record "Prod. Order Routing Line"; TimeType: Enum "Routing Time Type"; var RelevantEfficiency: Decimal; var RemainNeedQtyBase: Decimal; var RemainNeedQty: Decimal; CurrentRounding: Decimal; Write: Boolean)
    begin
        //A108B0093.Event21.00
    end;

**Comment by AlexanderYakunin** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.
