### ISSUE TITLE
Include xRec in existing Events [Job Journal Line]

### ISSUE THREAD

**Issue by LewisHyettTES** [microsoft/ALAppExtensions#20891]
The Job Journal Line table has events such as "OnBeforeUpdateUnitCost" which have Rec and IsHandled as a parameter. We don't however provide xRec while xRec is used in much of the logic within the standard "UpdateUnitCost" function. 

Please can xRec be added to these events?

 OnBeforeUpdateUnitCost

**Current**
 ```
  [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateUnitCost(var JobJounralLine: Record "Job Journal Line"; var IsHandled: Boolean)
    begin
    end;
```
**Proposed**
```
   [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateUnitCost(var JobJounralLine: Record "Job Journal Line"; xJobJournalLine: record "Job Journal Line"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49473.
