### ISSUE TITLE
[Access Change Request] table 36 "Sales Header" - global variable "NoSeriesMgt"

### ISSUE THREAD

**Issue by jorland1** [microsoft/ALAppExtensions#20890]
Hi,
could you please mark the global variables `NoSeriesMgt` as protected?
Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49473.
