### ISSUE TITLE
[Extensibility Request Protected vars] Report 1085 Post WIP to G/L  OR [Event Request] Codeunit 1000 - Job Calculate WIP

### ISSUE THREAD

**Issue by Imbapriest** [microsoft/ALAppExtensions#20899]
Hi,

Example Use-Case:

The Report is the entry to post and reverse the WIP Entries to/from the General Ledger. Our requierement is to prevent posting to General Ledger in some cases according to customers requierements. There we need an If-Clause where we can check the "JustReverse" - Bool is set to true or to false . We want to prevent only the posting from WIP G/L entries and allow anytime the reversal of WIP G/L entries.

**First Solution** can be to change the Report Request PageValues to protectet var:
If we couldn't check the report global variables we could only create a new report . Or we can only create an report extension that overlays all values and all actions from the original one.

Could we  have access to the request page variables of the Report 1085 "Post WIP to G/L"? 

OLD:
```
    var
        JobsSetup: Record "Jobs Setup";
        JobCalculateWIP: Codeunit "Job Calculate WIP";
        JobCalculateBatches: Codeunit "Job Calculate Batches";
        NoSeriesMgt: Codeunit NoSeriesManagement;
        PostingDate: Date;
        DocNo: Code[20];
        JustReverse: Boolean;
        WIPSuccessfullyPostedMsg: Label 'WIP was successfully posted to G/L.';
        ReplacePostDate: Boolean;
```

new:

```
var
        JobsSetup: Record "Jobs Setup";
        JobCalculateWIP: Codeunit "Job Calculate WIP";
        JobCalculateBatches: Codeunit "Job Calculate Batches";
        NoSeriesMgt: Codeunit NoSeriesManagement;
        WIPSuccessfullyPostedMsg: Label 'WIP was successfully posted to G/L.';

protected var
        PostingDate: Date;
        DocNo: Code[20];
        JustReverse: Boolean;
        ReplacePostDate: Boolean;
```

**Another solution** can be an EVENT on the Codeunit 1000 - Job Calculate WIP 

Could we have the following Event  `OnBeforeCalcGLWIP(JobNo,JustReverse,DocNo,PostingDate,NewPostDate);` on `CalcGLWIP`  like:

```
    procedure CalcGLWIP(JobNo: Code[20]; JustReverse: Boolean; DocNo: Code[20]; PostingDate: Date; NewPostDate: Boolean)
    var
        SourceCodeSetup: Record "Source Code Setup";
        GLEntry: Record "G/L Entry";
        Job: Record Job;
        JobWIPEntry: Record "Job WIP Entry";
        JobWIPGLEntry: Record "Job WIP G/L Entry";
        JobWIPTotal: Record "Job WIP Total";
        JobLedgerEntry: Record "Job Ledger Entry";
        JobTask: Record "Job Task";
        NextEntryNo: Integer;
        NextTransactionNo: Integer;
    begin
       // New Event
        OnBeforeCalcGLWIP(JobNo,JustReverse,DocNo,PostingDate,NewPostDate);
       //End Event
        JobWIPGLEntry.LockTable();
        JobWIPEntry.LockTable();
        Job.LockTable();

        JobWIPGLEntry.SetCurrentKey("Job No.", Reversed, "Job Complete");
        JobWIPGLEntry.SetRange("Job No.", JobNo);
        JobWIPGLEntry.SetRange("Job Complete", true);
        if not JobWIPGLEntry.IsEmpty() then
            exit;
        JobWIPGLEntry.Reset();
```
plus Event:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcGLWIP(var JobNo: Code[20]; var JustReverse: Boolean; var DocNo: Code[20]; var PostingDate: Date; var NewPostDate: Boolean)
    begin
    end;
```

Please choose a solution on your preferances.

Thanks in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49473.
