### ISSUE TITLE
[Event Request] page 6655 "Return Shipment Statistics" - OnCalculateTotalsOnAfterAddLineTotals

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#20895]
After asking and receiving for https://github.com/microsoft/ALAppExtensions/issues/13529 somebody at Micrsoft decided to remove all other code in page 6655 because it was not used. Instead of checking other similar statistic pages one could have seen that it was a bug in this particular page and that the solution was not to remove code but add CalculateTotals() to a trigger. I have managed to get that fixed through serviceshub. 
https://serviceshub.microsoft.com/support/case/2204200060002257

What I would like now is to get the events OnBeforeCalculateTotals and OnCalculateTotalsOnAfterAddLineTotals back because they have been set to Obsolete. Could you please fix this in the next release:

#if not CLEAN20
    [Obsolete('Event is never raised', '20.0')]
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculateTotals(ReturnReceiptHeader: Record "Return Receipt Header"; var LineQty: Decimal; var TotalNetWeight: Decimal; var TotalGrossWeight: Decimal; var TotalVolume: Decimal; var TotalParcels: Decimal; var IsHandled: Boolean)
    begin
    end;

    [Obsolete('Event is never raised', '20.0')]
    [IntegrationEvent(false, false)]
    local procedure OnCalculateTotalsOnAfterAddLineTotals(var ReturnReceiptLine: Record "Return Receipt Line"; var LineQty: Decimal; var TotalNetWeight: Decimal; var TotalGrossWeight: Decimal; var TotalVolume: Decimal; var TotalParcels: Decimal; ReturnReceiptHeader: Record "Return Receipt Header")
    begin
    end;
#endif

**Comment by AlexanderYakunin** [comment]
Page 6655 Return Shipment Statistics does not have any obsolete marks in v.21 or Master, nothing to do.

    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculateTotals(ReturnShipmentHeader: Record "Return Shipment Header"; var LineQty: Decimal; var TotalNetWeight: Decimal; var TotalGrossWeight: Decimal; var TotalVolume: Decimal; var TotalParcels: Decimal; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCalculateTotalsOnAfterAddLineTotals(var ReturnShipmentLine: Record "Return Shipment Line"; var LineQty: Decimal; var TotalNetWeight: Decimal; var TotalGrossWeight: Decimal; var TotalVolume: Decimal; var TotalParcels: Decimal; ReturnShipmentHeader: Record "Return Shipment Header")
    begin
    end;
