### ISSUE TITLE
[Extensibility Enhancement] Retrieve Vendor details in Approval Entry's GetCustVendorDetails procedure

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#20894]
Hi Microsoft AL Development Team,

I would like to suggest a simple enhancement to **GetCustVendorDetails** procedure in **table 454 "Approval Entry"**. 

Currently, the procedure doesn't handle Vendor scenario while the parameters suggest that the Customer/Vendor No. or Name are retrieved. Here is the change:

![image](https://user-images.githubusercontent.com/69611495/200471500-55e4e7be-7d6e-4788-b974-d0bdf0a53fd6.png)

Kind regards,
Tuan Nguyen

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51686.
