### ISSUE TITLE
It is no longer possible to use a custom text on a sales line if another account exist with same name

### ISSUE THREAD

**Issue by peikba** [microsoft/ALAppExtensions#209]
I have two accounts for invoicing transport:

Sales Freight
Purchase Transport

If I want to use the Purchase Transport account for invoicing freight and change the description to Freight:
 
![image](https://user-images.githubusercontent.com/33752561/41507015-7877d51e-7229-11e8-92ee-c93e5dc5e7c6.png)

Then it automatically changes the Account No to the Sales Freight account
![image](https://user-images.githubusercontent.com/33752561/41507020-994cc8f8-7229-11e8-8abd-9a8f078424b5.png)

It must be possible to change the description without changing the account number.
This happened after upgrading to NAV 2018 CU6.

Can this please be removed?

**Comment by ikoletic** [comment]
Solved in April 19 Business Central release: https://docs.microsoft.com/en-us/business-applications-release-notes/April19/dynamics365-business-central/application-enhancements#control-item-creation-from-lookups-on-documents
