### ISSUE TITLE
[Request-for-external] Report 1131 "Cost Allocation": Set CostRegister and CostBudgetRegister to protected

### ISSUE THREAD

**Issue by matthias-planzer** [microsoft/ALAppExtensions#20902]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49473.
