### ISSUE TITLE
[Event Request Table 77 - OnBeforePrintReport

### ISSUE THREAD

**Issue by peterelmqvist** [microsoft/ALAppExtensions#2090]
We would like to handle the print out from Business Central, in this case to save it as PDF. In order to do that we would like to avoid  REPORT.RUNMODAL so we need a Handled-pattern around this.

![image](https://user-images.githubusercontent.com/32321733/56139898-14cb9780-5f9a-11e9-9443-bfab30ef3355.png)

**Comment by Phfo** [comment]
We would use is to stream it and post it through an api request.
