### ISSUE TITLE
[Event Change] Extending Service Contract Header Invoice Period not possible

### ISSUE THREAD

**Issue by Grueslayer** [microsoft/ALAppExtensions#20913]
Calculated output variable `InvPeriodDuration` in Event `OnCalcInvPeriodDurationCaseElse(var ServiceContractHeader: Record "Service Contract Header"; InvPeriodDuration: DateFormula)` of  `Service Contract Header` not declared as `var` therefore not given by Reference and the needed date formula will not be returned to the caller.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49264.
