### ISSUE TITLE
protected variables Tabel 1003 "Job Planning Line"

### ISSUE THREAD

**Issue by Gitulf** [microsoft/ALAppExtensions#20911]
Dear ALAppExtensions team,

can you please mark the following variables to be protected in Tabel 1003 "Job Planning Line"?

```AL
    protected var
        UnitAmountRoundingPrecision: Decimal;
        AmountRoundingPrecision: Decimal;
        UnitAmountRoundingPrecisionFCY: Decimal;
        AmountRoundingPrecisionFCY: Decimal;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49473.
