### ISSUE TITLE
[Event Request] - OnAfterSetLastDateTimeModified in Table 27 "Item"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20918]
Hello, please consider adding the following event to Table 27 "Item":

    [IntegrationEvent(false, false)]
    local procedure OnAfterSetLastDateTimeModified((var Item: Record Item))
    begin        
    end;

and raise it accordingly inside the "SetLastDateTimeModified" procedure:

    procedure SetLastDateTimeModified()
    begin
        "Last DateTime Modified" := CurrentDateTime;
        "Last Date Modified" := DT2Date("Last DateTime Modified");
        "Last Time Modified" := DT2Time("Last DateTime Modified");

        OnAfterSetLastDateTimeModified(Rec);
    end;

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49479.
