### ISSUE TITLE
[EventRequest] Codeunit 10202 GetAppliedCustEntries

### ISSUE THREAD

**Issue by pzentner** [microsoft/ALAppExtensions#2092]
Add an event 

`
OnAfterPmtDtldCustLedgEntryFiltered(DtldCustLedgEntry, PmtDtldCustLedgEntry);
`
Right after line

`
PmtDtldCustLedgEntry.SETRANGE("Customer No.",DtldCustLedgEntry."Customer No.");
`

Purpose of this event is that we can adjust the entries that are part of the applied customer ledger entries

**Comment by pzentner** [comment]
I would like to reopen this one, since I cannot find the event added, but it says "ships in future update". Was this - by any chance - removed again, if it actually was added? If this was removed, I would appreciate, if this can be added again. If it was never added, I would still like to add it.

**Comment by JesperSchulz** [comment]
@AlexanderYakunin, could you check up on this one?

**Comment by AlexanderYakunin** [comment]
This event have been implemented in 14.X on July 1, 2019, but is not present in converted AL code. Please create new request with reference to this one and we will quickly implement it for 16.x.
