### ISSUE TITLE
[Event Request] - OnBeforeAppliesToEntryEntryTypeTest in Table 83 "Item Journal Line"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20920]
Hello, please consider adding the following event to Table 83 "Item Journal Line":

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcRoutingCostPerUnit(var ItemJnlLine: Record "Item Journal Line"; var ProdOrderRtngLine: Record "Prod. Order Routing Line"; var IsHandled: Boolean)
    begin        
    end;

and raise it accordingly inside the "OnValidate" trigger of "Cap. Unit of Measure Code" field:

            trigger OnValidate()
            var
                ProdOrderRtngLine: Record "Prod. Order Routing Line";

                **IsHandled: Boolean;**

            begin
                if Type <> Type::Resource then begin
                    "Qty. per Cap. Unit of Measure" :=
                      Round(
                        CalendarMgt.QtyperTimeUnitofMeasure(
                          "Work Center No.", "Cap. Unit of Measure Code"),
                        UOMMgt.QtyRndPrecision);

                    Validate("Setup Time");
                    Validate("Run Time");
                    Validate("Stop Time");
                end;

                if "Order No." <> '' then
                    case "Order Type" of
                        "Order Type"::Production:
                            begin
                                GetProdOrderRtngLine(ProdOrderRtngLine);
                                "Unit Cost" := ProdOrderRtngLine."Unit Cost per";

                                **OnBeforeCalcRoutingCostPerUnit(Rec, ProdOrderRtngLine, IsHandled);
                                IF NOT Handled THEN** 

                                    CostCalcMgt.RoutingCostPerUnit(
                                      Type, "No.", "Unit Amount", "Indirect Cost %", "Overhead Rate", "Unit Cost", "Unit Cost Calculation");
                            end;
                        "Order Type"::Assembly:
                            CostCalcMgt.ResourceCostPerUnit("No.", "Unit Amount", "Indirect Cost %", "Overhead Rate", "Unit Cost");
                        else
                            OnValidateCapUnitOfMeasureCodeOnCaseOrderTypeElse(Rec);
                    end;

                ReadGLSetup;
                "Unit Cost" :=
                  Round("Unit Cost" * "Qty. per Cap. Unit of Measure", GLSetup."Unit-Amount Rounding Precision");
                "Unit Amount" :=
                  Round("Unit Amount" * "Qty. per Cap. Unit of Measure", GLSetup."Unit-Amount Rounding Precision");
                Validate("Unit Amount");
            end;

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49264.
