### ISSUE TITLE
[Extensibility Request] Sharepoint Access by User

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#20930]
Right now I can only try to get access to the sharepoint with client Id and client secret.

Would it be an option to add an additional Sharepoint Autorization similiar to the Outlook OAuth Autorization (https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/Email%20-%20Outlook%20REST%20API/app/src/EmailOAuthClient.Codeunit.al) to retrieve an AccessToken, since UserCredentials aren't an option anymore for security reason. (https://github.com/microsoft/ALAppExtensions/pull/18635/commits/59877ee2f086f6b28116240e5bd49a998496167d)

**Comment by AlexanderYakunin** [comment]
Here is the reply from our team responsible for Client experience:

The current behavior to make it difficult is "by design" so we can control who consumes the token. Imo it would be preferable to expose an interface to perform specific SharePoint operations, rather than allow anyone to request a token but the issue doesn't really specify any scenario.

I would suggest you adding the idea for that and let them decide on proper implementation.

**Comment by pri-kise** [comment]
@AlexanderYakunin I would prefer being able to answer before the issue is getting closed.

I thought aboud adding a factbox or something similar for users to retrieve the sharepoint documents where they have access too.

The current implementation only provides access via client id and client secret.
Therefore we could use an app registration and use these secrets for any user.
Then we don't know who access the sharepoint. Maybe I don't understand your response, but I think we both want to ensure that the access to sharepoint make uses of the user context.

@JesperSchulz maybe you can help to avoid some misunderstandings.

Now I created an idea for the same extensibility: https://experience.dynamics.com/ideas/idea/?ideaid=15430f25-7f70-ed11-a76e-0003ff45ac6d

**Comment by AlexanderYakunin** [comment]
You can always continue discussion in closed requests, but we have a problem in processing of too many open requests. We can only process application extensibility requests here, keeping this kind of requests open may create wrong expectations for you.

**Comment by jwikman** [comment]
@pri-kise I don't know if I am missing something here, but... 
I think that the current implementation is exactly what you are requesting.
https://github.com/microsoft/ALAppExtensions/blob/9151fa39d6f6d548de0acdcf67512a30baf297ba/Modules/System/SharePoint%20Authorization/src/AuthorizationCode/SharePointAuthorizationCode.Codeunit.al#L64 are using the `Authorization Code Flow` for fetching the token, which is the authorization flow for delegated tokens.

Yes, you need to supply Client Id and Client Secret - but that is only to be used for fetching a token for the currently logged on user (for delegated access). So if you add a setup for Client Id and Client Secret, you could fetch a token for the currently logged on user. The user will be prompted for login the first time, but then the refresh token will be used. And I believe that the refresh token can be used for up to 90 days, so every third month the user will be prompted for login again.

Test it out! 🙂

**Comment by pri-kise** [comment]
@jwikman you are probable correct, but to be honest I don't quite understand why we still need clientid and client secret.
Shouldn't it be enough the use the current user scope to access the sharepoint?
Or is it similiar to other .net app services, where we have to provide a app registration with specific access scopes to trigger the authentication flow.

I've seen your request to enable S2S for the sharepoint module (https://github.com/microsoft/ALAppExtensions/issues/22261).

I think you're right and I will close this issue and keept track on your extensibility request.

**Comment by jwikman** [comment]
@pri-kise, yeah I know, it feels a bit cumbersome for us to create App Registration and use client id and client secret, when the user is already logged on... 
We used to have access to the `AcquireOnBehalfOfToken()` function, that did what you want to use. But that is now OnPrem (and I'm probably guilty for that... 😉), you can find a bit of background info on that in #12960.

But bottom line is, if we (ISV or VAR) want to obtain a token from AAD - we need use our own App Registrations (not MS App Registration that was the case in `AcquireOnBehalfOfToken()`). And to use our own App Registrations we need to provide the Client Id and a Client Secret or a Certificate. And Client Secret is much less of a hassle than certificate, IMO.
