### ISSUE TITLE
[Event Parameter Change] Table 37 - Sales Line - OnValidate "Purchasing Code" - event OnValidatePurchasingCodeOnAfterSetReserveWithoutPurchasingCode

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#20941]
We would like the parameter xRec added to the following event.

Table 37 - Sales Line - OnValidate "Purchasing Code" - event OnValidatePurchasingCodeOnAfterSetReserveWithoutPurchasingCode

OnValidatePurchasingCodeOnAfterSetReserveWithoutPurchasingCode(Rec, CurrFieldNo);

Original:
```
[IntegrationEvent(false, false)]
local procedure OnValidatePurchasingCodeOnAfterSetReserveWithoutPurchasingCode(var SalesLine: Record "Sales Line"; CurrentFieldNo: Integer)
begin
end;
```

Change: xRec
```
OnValidatePurchasingCodeOnAfterSetReserveWithoutPurchasingCode(Rec, CurrFieldNo, xRec); // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnValidatePurchasingCodeOnAfterSetReserveWithoutPurchasingCode(var SalesLine: Record "Sales Line"; CurrentFieldNo: Integer; xSalesLine: Record "Sales Line") // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49390.
