### ISSUE TITLE
[Event Parameter Change] Table 5876 - Phys. Invt. Order Line" - procedure - event OnAfterCalcQtyAndLastItemLedgExpected

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#20942]
We would like the parameter IncludeSender added to the following event.

Table 5876 - Phys. Invt. Order Line" - procedure - event OnAfterCalcQtyAndLastItemLedgExpected

Original:
```
[IntegrationEvent(false, false)]
local procedure OnAfterCalcQtyAndLastItemLedgExpected(var QtyExpected: Decimal; var LastItemLedgEntryNo: Integer)
begin
end;
```

Change: IncludeSender
```
[IntegrationEvent(true, false)] // <-- IncludeSender true
local procedure OnAfterCalcQtyAndLastItemLedgExpected(var QtyExpected: Decimal; var LastItemLedgEntryNo: Integer)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52178.
