### ISSUE TITLE
[Event Parameter Change] Report 698 - Get Sales Orders - procedure InsertReqWkshLine - event OnInsertReqWkshLineOnBeforeCode

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#20953]
We would like the parameter IncludeSender added to the following event.

Report 698 - Get Sales Orders - procedure InsertReqWkshLine - event OnInsertReqWkshLineOnBeforeCode

Original:
```
[IntegrationEvent(false, false)]
local procedure OnInsertReqWkshLineOnBeforeCode(var ReqLine: Record "Requisition Line"; SalesLine: Record "Sales Line"; SpecOrder: Integer; LineNo: Integer; ReqWkshName: Record "Requisition Wksh. Name"; GetDim: Option Item,"Sales Line"; var IsHandled: Boolean)
begin
end;
```

Change: IncludeSender = true
```
[IntegrationEvent(true, false)] // <-- we need IncludeSender true
local procedure OnInsertReqWkshLineOnBeforeCode(var ReqLine: Record "Requisition Line"; SalesLine: Record "Sales Line"; SpecOrder: Integer; var LineNo: Integer; ReqWkshName: Record "Requisition Wksh. Name"; GetDim: Option Item,"Sales Line"; var IsHandled: Boolean) <-- we need LineNo var
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49416.
