### ISSUE TITLE
[Event Parameter Change] Page 5530 - Item Availability by Event - procedure Initialize - event OnBeforeInitialize

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#20955]
We would like the parameter IncludeSender added to the following event.

Page 5530 - Item Availability by Event - procedure Initialize - event OnBeforeInitialize

Original:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeInitialize(var Item: Record Item; var ForecastName: Code[10]; var IncludeBlanketOrders: Boolean; var IncludePlanningSuggestions: Boolean; var IsHandled: Boolean)
begin
end;
```

Change: IncludeSender = true
```
[IntegrationEvent(true, false)] // <-- we need IncludeSender true
local procedure OnBeforeInitialize(var Item: Record Item; var ForecastName: Code[10]; var IncludeBlanketOrders: Boolean; var IncludePlanningSuggestions: Boolean; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49416.
