### ISSUE TITLE
[Event Request] table 5875 Phys. Invt. Order Header - OnShowDocDimOnBeforeModify

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#20962]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnShowDocDimOnBeforeModify` Table 5875 `Phys. Invt. Order Header` with the following signature:

```AL
[IntegrationEvent(false, false)]
local procedure OnShowDocDimOnBeforeModify(var Rec: Record "Phys. Invt. Order Header"; var xRec: Record "Phys. Invt. Order Header")
begin
end;
```

which would be called as follows in `ShowDocDim`:

```AL
procedure ShowDocDim()
var
	OldDimSetID: Integer;
begin
	OldDimSetID := "Dimension Set ID";
	"Dimension Set ID" :=
	  DimManagement.EditDimensionSet(
		"Dimension Set ID", StrSubstNo('%1 %2', TableCaption, "No."),
		"Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");
	// >>>> New >>>>>>>>>>>>>>>>
	OnShowDocDimOnBeforeModify(Rec, xRec);
	// <<<< New <<<<<<<<<<<<<<<<
	if OldDimSetID <> "Dimension Set ID" then begin
		Modify;
		if PhysInvtOrderLinesExist then
			UpdateAllLineDim("Dimension Set ID", OldDimSetID);
	end;
end;
```

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49559.
