### ISSUE TITLE
No-sense code in Codeunit 99000809 "Planning Line Management"

### ISSUE THREAD

**Issue by JalmarazMartn** [microsoft/ALAppExtensions#20965]
Good morning:
In the local procedure "TransferBOM '' there is a set of code that converts the output of the function to a mess if you are using a multi-level production BOM.
In the process of a production BOM component we found this Code:

`                        

                        ProdBOMLine[Level].Type::"Production BOM":
                            begin
                                OnTransferBOMOnBeforeTransferProductionBOM(ReqQty, ProdBOMLine[Level], LineQtyPerUOM, ItemQtyPerUOM);
                                TransferBOM(ProdBOMLine[Level]."No.", Level + 1, ReqQty, 1);
                                ProdBOMLine[Level].SetRange("Production BOM No.", ProdBOMNo);
                                ProdBOMLine[Level].SetRange(
                                  "Version Code", VersionMgt.GetBOMVersion(ProdBOMNo, ReqLine."Starting Date", true));
                                ProdBOMLine[Level].SetFilter("Starting Date", '%1|..%2', 0D, ReqLine."Starting Date");
                                ProdBOMLine[Level].SetFilter("Ending Date", '%1|%2..', 0D, ReqLine."Starting Date");
                            end;

`

All the filters settings in this piece must be removed because that doesn't make any sense, because at this moment you miss all references to previous right filters. 
The fix is only remove the filters setting lines and substitute this piece of code to:

`

                        ProdBOMLine[Level].Type::"Production BOM":
                            begin
                                OnTransferBOMOnBeforeTransferProductionBOM(ReqQty, ProdBOMLine[Level], LineQtyPerUOM, ItemQtyPerUOM);
                                TransferBOM(ProdBOMLine[Level]."No.", Level + 1, ReqQty, 1);
                            end;

`
Thank you very much in advance.

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot process bug reports here, if you think it is a bug, please report it via technical support and responsible team will get it assigned for correction. Our team is dedicated to extensibility issues.

**Comment by JalmarazMartn** [comment]
You are right. Thank you very much.
