### ISSUE TITLE
[Event Request] table 83 Item Journal Line - OnBeforeRevaluationPerEntryAllowed

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#20960]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnBeforeRevaluationPerEntryAllowed` to Table 83 `Item Journal Line` with the following signature:

```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeRevaluationPerEntryAllowed(var Rec: Record "Item Journal Line"; var ValueEntry: Record "Value Entry"; var IsHandled: Boolean)
begin
end;
```

which would be called as follows in `RevaluationPerEntryAllowed`:

```AL
local procedure RevaluationPerEntryAllowed(ItemNo: Code[20]): Boolean
var
	ValueEntry: Record "Value Entry";
	// >>>> New >>>>>>>>>>>>>>>>
	IsHandled: Boolean;
	// <<<< New <<<<<<<<<<<<<<<<
begin
	// >>>> New >>>>>>>>>>>>>>>>
	IsHandled := false;
	OnBeforeRevaluationPerEntryAllowed(Rec, ValueEntry, IsHandled);
	if IsHandled then
		exit(true);
	// <<<< New <<<<<<<<<<<<<<<<
	GetItem;
	if Item."Costing Method" <> Item."Costing Method"::Average then
		exit(true);

	ValueEntry.SetRange("Item No.", ItemNo);
	ValueEntry.SetRange("Entry Type", ValueEntry."Entry Type"::Revaluation);
	ValueEntry.SetRange("Partial Revaluation", true);
	exit(ValueEntry.IsEmpty);
end;
```

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49559.
