### ISSUE TITLE
[Event Request] - OnBeforeUpdUnPrice in Table 1003 "Job Planning Line"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20967]
Hello, please consider adding the following event to Table 1003 "Job Planning Line"

```
    [IntegrationEvent(false, false)]
    local procedure OnInsertOnAfterGetJob(var Rec: Record "Job Planning Line"; var Job: Record Job);
    begin
    end;

```
and raise it accordingly inside "OnInsert" table trigger:

```
    trigger OnInsert()
    begin
        LockTable();
        GetJob;

        **OnInsertOnAfterGetJob(Rec, Job);**

        IF Job.Blocked = Job.Blocked::All THEN
            Job.TestBlocked; //LYC-d
        JobTask.Get("Job No.", "Job Task No.");
        JobTask.TestField("Job Task Type", JobTask."Job Task Type"::Posting);
        InitJobPlanningLine;
        if Quantity <> 0 then
            UpdateReservation(0);

        if "Schedule Line" then
            Job.UpdateOverBudgetValue("Job No.", false, "Total Cost (LCY)");

#if not CLEAN20
        if FeatureManagement.IsEnabled(PicksForJobsFeatureIdLbl) then
#endif
        CreateWarehouseRequest();
    end;

```

Thank you!

**Comment by Vadim-Stepanenko** [comment]
There is already an OnAfterGetJob inside GetJob() procedure, will it work for you? If not please let me know what you are trying to achieve with this one.

**Comment by oldmat** [comment]
I'm very sorry: i did a lot of confusion about this request.
Let me write it again correctly:

Hello, please consider adding the following event to Table 1003 "Job Planning Line"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsert(var Rec: Record "Job Planning Line"; var IsHandled: Boolean);
    begin
    end;
```

and raise it accordingly inside "OnInsert" table trigger:

```
...
...
    trigger OnInsert()
    var
        **IsHandled: Boolean;**
    begin

        **OnBeforeInsert(Rec, IsHandled);
        if isHandled then
            exit;**

        LockTable();
        GetJob;

        IF Job.Blocked = Job.Blocked::All THEN
            Job.TestBlocked;
...
...
```

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49622.
