### ISSUE TITLE
[Event Request] Page 344 Navigate SetSource

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [microsoft/ALAppExtensions#2096]
We need additional event to be able to change source information (Document Type, Source Type, Source No., and Source Name).
Suggested solution:
![image](https://user-images.githubusercontent.com/30231314/56197598-d984a380-6041-11e9-8ab4-0103e9ad3e71.png)
![image](https://user-images.githubusercontent.com/30231314/56197654-f02afa80-6041-11e9-9d98-1073e35b6678.png)

**Comment by AlexanderYakunin** [comment]
We already have that:
    IsSourceUpdated := FALSE;
    OnFindRecordsOnAfterSetSource(
      Rec,PostingDate,DocType2,DocNo2,SourceType2,SourceNo2,DocNoFilter,PostingDateFilter,IsSourceUpdated);
    IF IsSourceUpdated THEN
      SetSource(PostingDate,DocType2,DocNo2,SourceType2,SourceNo2);
