### ISSUE TITLE
[Event Request] - OnCreatePaymentLinesServicesOnBeforePaymentLinesInsert event in table 12170 "Payment Lines"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20974]
Please, consider changing the signature of the following event in table 12170 "Payment Lines":

From:

  [IntegrationEvent(false, false)]
    local procedure OnCreatePaymentLinesServicesOnBeforePaymentLinesInsert(var PaymentLines: Record "Payment Lines"; ServiceHeader: Record "Service Header")
    begin
    end;

To:

  [IntegrationEvent(false, false)]
    local procedure OnCreatePaymentLinesServicesOnBeforePaymentLinesInsert(var PaymentLines: Record "Payment Lines";  ServiceHeader: Record "Service Header"; PaymentLinesTerms: Record "Payment Lines")
    begin
    end;

and calling it accordingly in procedure "CreatePaymentLinesServices":

```
...
...
                PaymentLines."Pmt. Discount Date" := CalcDate(PaymentLinesTerms."Discount Date Calculation", ServiceHeader."Document Date");

                if PaymentLines."Pmt. Discount Date" < ServiceHeader."Document Date" then
                    PaymentLines."Pmt. Discount Date" := ServiceHeader."Document Date";

                **OnCreatePaymentLinesServicesOnBeforePaymentLinesInsert(PaymentLines, ServiceHeader, PaymentLinesTerms);**

                PaymentLines.Insert();
            until PaymentLinesTerms.Next() = 0;
        end;
    end;
```

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49502.
