### ISSUE TITLE
[Improvement] Make "Object Caption" field visible by default in "All Objects with Caption" page

### ISSUE THREAD

**Issue by deadmouse** [microsoft/ALAppExtensions#20984]
**🕮 Describe the improvement**

Make "Object Caption" field visible by default in "All Objects with Caption" page 9174. It makes no sense to hide it when the page is called "All Objects with Caption".

**📣 Expected behavior**

I expect this field to be visible without needing to make it visible with Personalize option.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51299.
