### ISSUE TITLE
Question about procedure scope "OnPrem"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20981]
Hello,

i can not understand why a lot of procedures inside BC base app are scoped "OnPrem". In particular inside the italian localization objects (12.000).
Those procedure don't use .NET variables or local resource, and don't conflict with any technical "Cloud" rule.
This situation raises lot of problems in order to create "Cloud" targeted extensions.

**Comment by AlexanderYakunin** [comment]
There are many reasons:
- A lot of legacy code procedures have been made global in country customization with unclear purpose. Such procedures have been marked as Scope OnPrem during conversion from C/AL to AL. 
- Many procedures have been using dotnet and could not be made Cloud at time of conversion
- Some other issues also affected this

We are gradually enabling the code for Cloud based on partner requests. Just ask specifically what you need.
