### ISSUE TITLE
[Event Request] - OnAfterLookupBuyFromCity in Table 38 "Purchase Header"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20993]
Hello, please consider adding the following event to Table 38 "Purchase Header"

```
[IntegrationEvent(false, false)]
local procedure OnAfterLookupBuyFromCity(var PurchaseHeader: Record "Purchase Header")
begin
end;

```
and raise it accordingly inside "OnLookup" trigger of field 83"Buy-from City":

```
        trigger OnLookup()
        begin
            LookupPostCode("Pay-to City", "Pay-to Post Code", "Pay-to County", "Pay-to Country/Region Code", CurrFieldNo);

            **OnAfterLookupBuyFromCity(Rec);**
        end;
```

Thank you!

**Comment by adejsy** [comment]
Inside the procedure LookupPostCode it raises an integration event called OnLookupPostCode - does that not achieve the same as what you are asking for above?

![image](https://user-images.githubusercontent.com/63508365/201694575-574b0c2d-333f-41be-aefd-241c9c8f9509.png)

**Comment by oldmat** [comment]
Unfortunately no. I need to know what is the calling procedure (if lookup of Buy-from, Pay-to pr Ship-to), and inside the LookupPostCode procedure there is not that info.

The whole problem starts from the relation between "Territory Code" and "PostCode" + City: in BC this relation is not managed, while here in Italy is widely used.

**Comment by adejsy** [comment]
In the procedure and the integration event that is raised it passes you the CalledFromFieldNo so you can then see where it was called from...

**Comment by oldmat** [comment]
I see, you're right.
In general i don't feel very comfortable trusting the CurrFieldNo variable, since its value depends on the beginning of the execution flow. In this case, since the flow starts with a lookup action, i will follow your suggestion.

Thank you !

**Comment by adejsy** [comment]
No worries - just thought it might help you in progressing rather than having to wait for a minor release with these in (if they were included).

Do you think you could follow the same pattern for the other Event Requests that you raised that seem similar?

**Comment by oldmat** [comment]
Absolutely!
