### ISSUE TITLE
[Event Request] - OnAfterLookupShipToCity in Table 38 "Purchase Header"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#20991]
Hello, please consider adding the following event to Table 38 "Purchase Header"

    [IntegrationEvent(false, false)]
    local procedure OnAfterLookupShipToCity(var PurchaseHeader: Record "Purchase Header")
    begin
    end;

and raise it accordingly inside "OnLookup" trigger of field 17 "Ship-to City":

            trigger OnLookup()
            begin
                LookupPostCode("Pay-to City", "Pay-to Post Code", "Pay-to County", "Pay-to Country/Region Code", CurrFieldNo);

                **OnAfterLookupShipToCity(Rec);**
            end;

Thank you!

**Comment by Vadim-Stepanenko** [comment]
Closing as no longer needed after the discussion in your other issue.
