### ISSUE TITLE
Edit in Excel change in behaviour

### ISSUE THREAD

**Issue by adejsy** [microsoft/ALAppExtensions#20999]
There appears to have been some changes somewhere in the "Edit in Excel" feature whereby filters no longer seem to be respected.

Previously Edit in Excel opened Excel with only the records shown that are on the page where this is triggered from. 

Now it seems to ignore the filters and displays all records in the table regardless. This behaviour is not as it was before.

You can actually go to a list, which is showing no records, click Edit in Excel, and you will get all records in the table populated in the Excel. It never used to work like that.

Open in Excel works fine and only shows what is on the page at the time.

Version: GB Business Central 21.0 (Platform 21.0.46384.49089 + Application 21.0.46256.46853)

**Comment by AlexanderYakunin** [comment]
This is beyond responsibility of our team, but I checked with other teams. We are aware about this issue and working on the fix. Next time, please report issues using technical support, when it will be assigned properly.
