### ISSUE TITLE
Question/Suggestion: Global event OnBeforeCommit for later Commit

### ISSUE THREAD

**Issue by megel** [Microsoft/ALAppExtensions#210]
Hi @esbenk,
last week we have discussed - how to avoid a commit, if I try to run a "Post-Something-Operation" including a `Commit` as a Batch-Operation.

In my opinion it could be help, to include e.g. a `OnBeforeCommitEvent(…)` Event in the **COMMIT** command e.g.:

```JavaScript
    [BusinessEvent(true)]
    procedure OnBeforeCommit(var suspendCommit:Boolean)
    begin
    end;
```

When I use a codeunit with `dynamics` subscriber than I could set `suspendCommit = true` and avoid the Commit until the end of my Batch-Operation.

And now the tricky part :) how can I secure, that I only suspend the Commit of my Current Session which invoked the Batch-Operation? Would this be possible? If yes than pleas include the Event!
BR / Michael

**Comment by pborring** [comment]
Discussed more internally, and concluded that there will not be a generic, platform solution. We take requests for suppressing commits on a case by case basis instead. Hence closing this request, feel free to open specific requests instead.
