### ISSUE TITLE
[Application Bug] codeunit 20351 - TryGetCurrentCountry

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#21008]
Whenever I want to debug something, the debugger now ALWAYS stops on TryGetCurrentCountry in codeunit 20351 "Connectivity Apps Impl.", which is a little annoying :(

Reason why is US (my environment's country) is not a supported Conn. apps country (see https://github.com/microsoft/ALAppExtensions/blob/3f7fb5c34c6b6951e7687a9e9efc6a388e3cfc43/Apps/W1/ConnectivityApps/app/src/Enums/ConnAppsSupportedCountry.Enum.al), so the index (0) raises an error when getting the Conn. apps ordinal.

![image](https://user-images.githubusercontent.com/25268332/201879682-f3f1826a-4aac-47e5-9da2-46ee452e4041.png)

Can't this code be refactored to introduce an enum value with value 0, country " ", and instead of using a Try function, perform an If Get then, and return enum " " if nothing found?

**Comment by JesperSchulz** [comment]
Indeed sounds annoying. We'll take a look.

**Comment by JesperSchulz** [comment]
You can actually now control whether the debugger should stop on failing try-functions: https://learn.microsoft.com/en-us/dynamics365-release-plan/2022wave2/smb/dynamics365-business-central/exclude-try-functions-when-debugging-errors

Does that not solve your problem?

**Comment by fvet** [comment]
@JesperSchulz Thanks for the hint, I've changed my launch configs to avoid the debugger breaking on this line.
