### ISSUE TITLE
CU1280 GetAndAssignValue function

### ISSUE THREAD

**Issue by yildiz-ozdemir** [microsoft/ALAppExtensions#21021]
DearTeam Member,
Could you change the GetAndAssignValue procedure from local to global?

![image](https://user-images.githubusercontent.com/49477543/202135473-003bf785-3c14-403a-b307-f9eebed7a204.png)

**Comment by AlexanderYakunin** [comment]
This procedure already made global in v.22

    procedure GetAndAssignValue(var CurrencyExchangeRecordRef: RecordRef; FieldNo: Integer; DefinitionDataExchField: Record "Data Exch. Field"; DefaultValue: Variant): Boolean
    var
        DataExchField: Record "Data Exch. Field";
        DataExchFieldMapping: Record "Data Exch. Field Mapping";
        UseDefaultValue: Boolean;
    begin
        UseDefaultValue := not GetFieldValue(CurrencyExchangeRecordRef, DataExchField, DefinitionDataExchField, DataExchFieldMapping, FieldNo);
        exit(AssignValue(CurrencyExchangeRecordRef, DataExchField, DataExchFieldMapping, UseDefaultValue, DefaultValue, FieldNo));
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
