### ISSUE TITLE
Request for the parameters "CurrencyBalance" and "LastCurrencyCode" in the event OnBeforeUpdateCurrencyBalanceForRecurringLine  to be variable in Codeunit 13 "Gen. Journal Line"

### ISSUE THREAD

**Issue by daryobahar** [microsoft/ALAppExtensions#21020]
Dear Team Members

The parameters **CurrencyBalance** and **LastCurrencyCode** of the event **OnBeforeUpdateCurrencyBalanceForRecurringLine**  in the Codeunit 13 **Gen. Journal Line** need to be variable so that when we apply the IsHandled rule and change the calculation to fit our functionality, the calculated CurrencyBalance is conveyed to Codeunit 13 and the rest of the function after that point executes without giving false error messages.

Thus the event publisher 
   [**IntegrationEven**t(false, false)]
    local procedure **OnBeforeUpdateCurrencyBalanceForRecurringLine**(var GenJnlLine: Record "Gen. Journal Line"; CurrencyBalance: Decimal; LastCurrencyCode: Code[10]; var IsHandled: Boolean)
   
needs to become
   [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateCurrencyBalanceForRecurringLine(var GenJnlLine: Record "Gen. Journal Line"; **var** CurrencyBalance: Decimal; **var** LastCurrencyCode: Code[10]; var IsHandled: Boolean)

Thank you for your support.

Daryo Bahar
Infotek A.S.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49622.
