### ISSUE TITLE
[Event Request] Extend Swiss QR App with different payment reference generation

### ISSUE THREAD

**Issue by DominicSaladin** [microsoft/ALAppExtensions#21024]
At the moment, the Swiss QR Management codeunit generates the payment reference with an incremental number. Problem is, many customers would like to use the the customer no. and the invoice no. in the payment reference, but with the current implementation of the app, it is not possible to change the logic.

So It would be nice if either you guys implement this in the standard app or give us developers the possibility to change the behaviour with a event publisher.

I found the requirements here:
https://www.banana.ch/apps/en/node/9387
![image](https://user-images.githubusercontent.com/43037258/202154954-27dea60d-1be3-43c5-9c00-abe18e681731.png)

**Comment by AlexanderYakunin** [comment]
Can you suggest where you need this event and provide required parameters?

**Comment by DominicSaladin** [comment]
Yes, sure. Maybe something like this?

File ".\Apps\CH\SwissQRBill\app\src\core\Mgt.Codeunit.al"
Procedure is being used 3 times in this table ".\Apps\CH\SwissQRBill\app\src\core\Buffer.Table.al"
```
internal procedure GetNextReferenceNo(Buffer: Record "Swiss QR-Bill Buffer"; ReferenceType: Enum "Swiss QR-Bill Payment Reference Type"; UpdateLastUsed: Boolean) Result: Code[50]
var
    SwissQRBillSetup: Record "Swiss QR-Bill Setup";
    TempReferenceNo: Text;
    IsHandled: Boolean;
begin
    OnBeforeGetNextReferenceNo(Buffer, ReferenceType, UpdateLastUsed, Result, IsHandled);

    if (IsHandled) then
        exit;

    with SwissQRBillSetup do begin
        Get();
        "Last Used Reference No." += 1;
        if UpdateLastUsed then
            Modify();
    end;

    case ReferenceType of
        ReferenceType::"Creditor Reference (ISO 11649)":
            begin
                TempReferenceNo := Format(SwissQRBillSetup."Last Used Reference No.");
                exit(CopyStr('RF' + CalcCheckDigitForCreditorReference(TempReferenceNo) + TempReferenceNo, 1, 25));
            end;
        ReferenceType::"QR Reference":
            begin
                TempReferenceNo := Format(SwissQRBillSetup."Last Used Reference No.", 0, '<Integer,26><Filler Character,0>');
                exit(CopyStr(TempReferenceNo + CalcCheckDigitForQRReference(TempReferenceNo), 1, 27));
            end;
    end;
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeGetNextReferenceNo(Buffer: Record "Swiss QR-Bill Buffer"; ReferenceType: Enum "Swiss QR-Bill Payment Reference Type"; UpdateLastUsed: Boolean; var Result: Code[50]; var IsHandled: Boolean)
begin
end;
```

I also added the variable "Buffer: Record "Swiss QR-Bill Buffer"" to GetNextReferenceNo, because the buffer is necessary to generate the payment reference.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49950.
