### ISSUE TITLE
[Event-Request] cdu 10752 - SII Doc. Upload Management - OnBeforeStoreRequestXML

### ISSUE THREAD

**Issue by AlcobaG** [microsoft/ALAppExtensions#2102]
Dear Microsoft ALAppExtensions team,

We would like to request the following event-publisher to be added in Codeunit 10752 - SII Doc. Upload Management. This event will allow us to personalize SII functionality in Spain for customers submited to the legal requirement of "Not Deductible VAT". 
The best place to call the new event would be function or procedure InvokeBatchSoapRequest because the file could be modified before send it to the Spain Tax Agency. The event must pass the requesttext var by reference. Below we have attached an image with an arrow pointing the right place for the event.

[Event Request.docx](https://github.com/Microsoft/ALAppExtensions/files/3127734/Event.Request.docx)

Thank you so much

**Comment by AlexanderYakunin** [comment]
I need to inform you about following:

1. SII feature already have support for Non-Deductible VAT, so you don't need to customize export for this. You simply need it calculated in the document to be exported
2. Place you have selected for event does not look good, as here you already have RequestText as stream for sending. If you want to update this stream, you need to do it during creation of this request from document.

Therefore this request will not be implemented.

For the next time please specify event with parameters and exact location. Also add VAR for parameters where needed.

**Comment by AlcobaG** [comment]
To reply for the first question:
We inform you that the "Non-Deductible VAT" is not the same of "Unrealiced VAT" or "VAT Cash Regime". I send you an link of Spanish Tax Authorities (AEAT) that explain the ""Non Deductible VAT", or "Prorrata" in Spanish language (page from 106 to 112):
https://www.agenciatributaria.es/static_files/AEAT/Contenidos_Comunes/La_Agencia_Tributaria/Segmentos_Usuarios/Empresas_y_profesionales/Empresario_individuales_y_profesionales/I.V.A./Manual_IVA_2015.pdf
We have cases that in the same movement we have to operate with Unrealiced VAT and "Non-deductible VAT" or "Prorrata". The diference is that in Unrealiced VAT we realiced the VAT Amount in the Payment moment, but in the "Non Deductible VAT", a percentage of this VAT Amount is never deductible.

To reply for the second question:
The requested event for the codeunit SII Doc. Upload Management is due to modify the Text variable before being sent to Spanish Tax Authorities. We thought this solution was the easier to develop. If it’s not possible, we need 2 places in order to modify the value sent to the node:
[Image SII Non deductible VAT.docx](https://github.com/microsoft/ALAppExtensions/files/3198410/Image.SII.Non.deductible.VAT.docx)

For invoices: Codeunit 10750 SII XML Creator – procedure FillDetalleIVANode()
**See the Image 1**

-	The value to modify is the field Amount because we want to work with other field/value. 
-	If we have a previous event, we need to overwrite Amount value, also passing TempVATEntry record to identify the right value to substitute.


For corrective invoices: there are 2 possibilities:

Alternative 1: Codeunit 10750 SII XML Creator - procedure HandleReplacementPurchCorrectiveInvoice ()
**See the Image 2**

-	The value to modify is the variable VATAmountDiff because we want to work with other field/value. 
-	If we have a previous eve[n](url)t, we need to overwrite VATAmountDiff value, also passing TempVATEntryPerPercent record and VendorLedgerEntry record to identify the right value to substitute.

Alternative 2: Codeunit 10750 SII XML Creator - procedure CalcDiffAmounts()
**See the Image 3**
 
-	The value to modify is the variable VATAmountDiff because we want to work with other field/value. 
-	If we have an after event, we need to overwrite VATAmountDiff value, also passing TempVATEntryPerPercent record and VendorLedgerEntry record to identify the right value to substitute.

**Comment by AlexanderYakunin** [comment]
Thank you for your reply. I'm trying to understand your needs but you didn't provide sufficient information for this. Can you please for each event provide 1) name of event and list of required parameters 2) event call in existing code. I don't know your requirement and cannot decide myself which way is better for you. Please pay attention that VendorLedgerEntry is only available in HandleReplacementPurchCorrectiveInvoice procedure but not available in CalcDiffAmounts, so alternative 2 is not possible. Having this information I can implement events in 1 day.

**Comment by AlcobaG** [comment]
If you need more functional information, please contact with +34658031551 ana.alcoba@prodware.es
If you need more technical information, please contact with +34696505414 ja.munoz@prodware.es

Event 1 Name: OnBeforeFillCuotaIVA
Codeunit 10750 SII XML Creator – procedure FillDetalleIVANode()
[Events XML SII.docx](https://github.com/microsoft/ALAppExtensions/files/3203315/Events.XML.SII.docx)

See Image 1
Parameters (all by reference):
-	TempVATEntry
-	AmountNodeName
-	Amount
Subscriber Event: LOCAL [IntegrationEvent] OnBeforeFillCuotaIVA(VAR TempVATEntry : TEMPORARY Record "VAT Entry";VAR AmountNodeName : Text;VAR Amount : Decimal)

Event 2: Name: OnBeforeFillCorrectiveCuotaIVA
Codeunit 10750 SII XML Creator – procedure HandleReplacementPurchCorrectiveInvoice()

See Image 2
Parameters (all by reference except AmountNodeName):
-	TempVATEntryPerPercent
-	AmountNodeName
-	VATAmountDiff

Subscriber Event: LOCAL [IntegrationEvent] OnBeforeFillCorrectiveCuotaIVA (VAR TempVATEntryPerPercent : TEMPORARY Record "VAT Entry"; AmountNodeName : Text;VAR VATAmountDiff : Decimal)

Thank you,

**Comment by MikelIG11** [comment]
I have seen a new event which gives acces to variable CuotaDeducibleValue has been created.

[EventSubscriber(ObjectType::Codeunit, Codeunit::"SII XML Creator", 'OnAfterCalculateCuotaDeducibleValue', '', false, false)]
 
However, to Spanish Tax Agency requeriments we still need to have access to change CuotaSoportada value, which shows VATAmountDiff value.

Thank  you.

Something like this:

Codeunit 10750 SII XML Creator – procedure HandleReplacementPurchCorrectiveInvoice()

 

Name: OnBeforeFillCorrectiveCuotaIVA

Parameters (all by reference except AmountNodeName):
-	TempVATEntryPerPercent
-	AmountNodeName
-	VATAmountDiff

LOCAL [IntegrationEvent] OnBeforeFillCorrectiveCuotaIVA (VAR TempVATEntryPerPercent : TEMPORARY Record "VAT Entry"; AmountNodeName : Text;VAR VATAmountDiff : Decimal)
![event](https://user-images.githubusercontent.com/53006842/61379762-71479700-a8a8-11e9-84c4-377d5b085d7f.jpg)
