### ISSUE TITLE
[Event Request] codeunit 7312 "Create Pick" OnBeforeTempActivLineInsert

### ISSUE THREAD

**Issue by agirdhar007** [microsoft/ALAppExtensions#21031]
procedure CreateTempActivityLine(
        LocationCode: Code[10]; BinCode: Code[20]; UOMCode: Code[10]; QtyPerUOM: Decimal; QtyToPick: Decimal; QtyToPickBase: Decimal; ActionType: Integer; BreakBulkNo: Integer; QtyRndPrec: Decimal; QtyRndPrecBase: Decimal)
    var
        WhseSource2: Option;
        ShouldCalcMaxQty: Boolean;
    begin
        // ALANSH <<
        OnBeforeTempActivLineInsert(BinCode, QtyToPick, QtyToPickBase, ActionType);
        // ALANSH >>
        if Location."Directed Put-away and Pick" then
            GetBin(LocationCode, BinCode);

        TempLineNo := TempLineNo + 10000;
        with TempWhseActivLine do begin
            Reset();
            Init();

            "No." := Format(TempNo);
            "Location Code" := LocationCode;
            "Unit of Measure Code" := UOMCode;
            "Qty. per Unit of Measure" := QtyPerUOM;
            "Qty. Rounding Precision" := QtyRndPrec;
            "Qty. Rounding Precision (Base)" := QtyRndPrecBase;
            "Starting Date" := WorkDate;
            "Bin Code" := BinCode;
            "Action Type" := "Warehouse Action Type".FromInteger(ActionType);
            "Breakbulk No." := BreakBulkNo;
            "Line No." := TempLineNo;

            case CreatePickParameters."Whse. Document" of

[IntegrationEvent(false, false)] 
    local procedure OnBeforeTempActivLineInsert(var BinCode: Code[10]; var QtyToPick: Decimal; var QtyToPickBase: Decimal; ActionType: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49622.
