### ISSUE TITLE
Add HideValidationDialog to UpdatePurchLinesByFieldNo on Purchase Header

### ISSUE THREAD

**Issue by SandroKiedis** [microsoft/ALAppExtensions#21037]
Hello everyone

Please add the GetHideValidationDialog to the UpdatePurchLinesByFieldNo procedure (same as on Sales Header).

Sales Header
![image](https://user-images.githubusercontent.com/47424839/202403068-6bfcb4af-87bd-406b-a0b8-28f08a6d2a14.png)

Purchase Header
![image](https://user-images.githubusercontent.com/47424839/202403369-75ec6f25-b3be-4c83-ac69-6c12fc913944.png)

It would be nice to use one solution for either Sales and Purchase. 
Thank you for taking it into consideration :)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51299.
