### ISSUE TITLE
[Extensibility Request] Page 5600 "Fixed Asset Card" - Protected variable

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21035]
It seems one thins is still missing from previous request
https://github.com/microsoft/ALAppExtensions/issues/16417
Please set the variable FADepreciationBookOld to protected.

```
protected var
    FADepreciationBook: Record "FA Depreciation Book";
    FADepreciationBookOld: Record "FA Depreciation Book";
    Simple: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49742.
