### ISSUE TITLE
[Event Request] Page 5708 "Get Shipment Lines" - Fix wrong publisher

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21036]
It seems that the previous request introduced a problem:
https://github.com/microsoft/ALAppExtensions/issues/16605
Handled pattern should return a Result.

Current state:
```
trigger OnQueryClosePage(CloseAction: Action) Result: Boolean
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeOnQueryClosePage(CloseAction, Result, IsHandled, Rec);
    if IsHandled then
        exit;

    if CloseAction in [ACTION::OK, ACTION::LookupOK] then
        CreateLines();
end;
```

Desired state:
```
trigger OnQueryClosePage(CloseAction: Action) Result: Boolean
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeOnQueryClosePage(CloseAction, Result, IsHandled, Rec);
    if IsHandled then
        exit(Result);

    if CloseAction in [ACTION::OK, ACTION::LookupOK] then
        CreateLines();
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49620.
