### ISSUE TITLE
10302 - ACH US Footer Table - Add New Field

### ISSUE THREAD

**Issue by blakesmith4128** [microsoft/ALAppExtensions#21034]
I'm needing to add custom field to standard 10302 ACH US Footer table for data exchange mapping. We've created a new table/page for client to enter data and have successfully added this field to 10300 – ACH US Header but also need it in the footer. Our developer cant subscribe to the event to add code. Does anyone know if this is possible?

**Comment by AlexanderYakunin** [comment]
Please provide more information - which version you have, are you doing extension, which event you are trying to subscriber or what should be added to solve your issue?

**Comment by AlexanderYakunin** [comment]
Closing, as no information about event have been provided
