### ISSUE TITLE
[Exposure Request] Table 36 "Sales Header" - TransferItemChargeAssgntSalesToTemp

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21045]
Reference to the old issue marked as complete:
https://github.com/microsoft/ALAppExtensions/issues/18788
Not included in the Build ID 48357 (Update 1 for BC 2022 Wave 2
Could you please make function TransferItemChargeAssgntSalesToTemp in table 36 "Sales Header" externally available?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49742.
