### ISSUE TITLE
[Extensibility Request] Page 397 "Sales Invoice Statistics" - Protected variable

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21048]
Reference to the old issue marked as complete:
https://github.com/microsoft/ALAppExtensions/issues/16612
Not included in the Build ID 48357 (Update 1 for BC 2022 Wave 2
Could you please set the variable SalesInvLine in Page 397 to protected?

```
protected var
    SalesInvLine: Record "Sales Invoice Line";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49742.
