### ISSUE TITLE
[Event Request] codeunit 550 "VAT Rate Change Conversion" - OnBeforeUpdateItem

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21057]
Reference to the old issue marked as complete:
https://github.com/microsoft/ALAppExtensions/issues/19538
Not included in the Build ID 48357 (Update 1 for BC 2022 Wave 2)
Please include sender in the Event OnBeforeUpdateItem

```
[IntegrationEvent(true, false)]
local procedure OnBeforeUpdateItem(var Item: Record Item; var VATRateChangeSetup: Record "VAT Rate Change Setup"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49620.
