### ISSUE TITLE
[Exposure Request] codeunit 550 "VAT Rate Change Conversion" - OnAfterLineInScope

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21055]
Reference to the old issue marked as complete:
https://github.com/microsoft/ALAppExtensions/issues/19512
Not included in the Build ID 48357 (Update 1 for BC 2022 Wave 2)
Please make function LineInScope externally available and please add Event OnAfterLineInScope

```
[IntegrationEvent(true, false)]
local procedure OnAfterLineInScope(var Result: Boolean)
begin
end;
```

```
procedure LineInScope(GenProdPostingGroup: Code[20]; VATProdPostingGroup: Code[20]; ConvertGenProdPostingGroup: Boolean; ConvertVATProdPostingGroup: Boolean) Result: Boolean
begin
    if ConvertGenProdPostingGroup then
        if VATRateChangeConversion.Get(VATRateChangeConversion.Type::"Gen. Prod. Posting Group", GenProdPostingGroup) then
            exit(true);
    if ConvertVATProdPostingGroup then
        if VATRateChangeConversion.Get(VATRateChangeConversion.Type::"VAT Prod. Posting Group", VATProdPostingGroup) then
            exit(true);
    Result := false;
    OnAfterLineInScope(Result);
    exit(Result);
end;
```

**Comment by AlexanderYakunin** [comment]
Please consider if you request event and make procedure global in the same request when it will be done in Master only.

**Comment by AlexanderYakunin** [comment]
Procedure LineInScope is global in both 21.x and master. Please recheck. Convert this request to event request

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49745.
