### ISSUE TITLE
new fieldgroup in Table "Order Address"

### ISSUE THREAD

**Issue by pbemilyneufeld** [microsoft/ALAppExtensions#21061]
Hello,

could you provide a new DropDown-Fieldgroup in the table 224 "Order Address"?

Kind regards,
Emily Neufeld

**Comment by AlexanderYakunin** [comment]
This field group already exist

    fieldgroups
    {
        fieldgroup(DropDown; "Code", Name, Address, City, "Post Code")
        {
        }
    }
