### ISSUE TITLE
[Event Request] OnBeforeWhseActivLineDelete in Codeunit 7324 "Whse.-Activity-Post"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#21062]
In codeunit 7324 "Whse.-Activity-Post" in the existing event trigger OnBeforeWhseActivLineDelete we need the WarehouseActivityLine as var-parameter cause in case forcedelete=false the WarehouseActivityLine is modified, and we need to add field values before modify.
Additional the parameter HideDialog is useful because of the code after the eventtrigger checks:

                        if HideDialog then
                            WhseActivLine.Validate("Qty. to Handle", 0);

old:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeWhseActivLineDelete(WarehouseActivityLine: Record "Warehouse Activity Line"; var ForceDelete: Boolean)
    begin
    end;

new:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeWhseActivLineDelete(var WarehouseActivityLine: Record "Warehouse Activity Line"; var ForceDelete: Boolean;HideDialog: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49622.
