### ISSUE TITLE
[Code Change Request] Request to change CodeUnit 12 / Scope('OnPrem') Tag

### ISSUE THREAD

**Issue by MSIngest** [microsoft/ALAppExtensions#21064]
Hello
 could you remove Scope('OnPrem') on these  3 functions

   **[Scope('OnPrem')]**
    procedure ApplyBill(var NewCustLedgEntry: Record "Cust. Ledger Entry")
    var
        OldCustLedgEntry: Record "Cust. Ledger Entry";
    begin
        if NewCustLedgEntry."Document Type" = NewCustLedgEntry."Document Type"::Dishonored then begin
            OldCustLedgEntry.Reset();
            OldCustLedgEntry.SetCurrentKey("Closed by Entry No.");
            OldCustLedgEntry.SetRange("Closed by Entry No.", NewCustLedgEntry."Entry No.");
            if OldCustLedgEntry.FindSet() then
                repeat
                    HandleBill(OldCustLedgEntry, false);
                until OldCustLedgEntry.Next() = 0;
        end else
            if not NewCustLedgEntry.Open then
                HandleBill(NewCustLedgEntry, false);
    end;

    **[Scope('OnPrem')]**
    procedure UnapplyBill(var NewCustLedgEntry: Record "Cust. Ledger Entry")
    var
        OldCustLedgEntry: Record "Cust. Ledger Entry";
    begin
        if NewCustLedgEntry."Document Type" = NewCustLedgEntry."Document Type"::Dishonored then begin
            OldCustLedgEntry.Reset();
            OldCustLedgEntry.SetCurrentKey("Closed by Entry No.");
            OldCustLedgEntry.SetRange("Closed by Entry No.", NewCustLedgEntry."Entry No.");
            if OldCustLedgEntry.FindSet() then
                repeat
                    if OldCustLedgEntry."Bank Receipt Issued" then
                        HandleBill(OldCustLedgEntry, true);
                until OldCustLedgEntry.Next() = 0;
        end else
            if NewCustLedgEntry."Bank Receipt Issued" then
                HandleBill(NewCustLedgEntry, true);
    end;

    **[Scope('OnPrem')]**
    procedure HandleBill(var CustLedgEntry: Record "Cust. Ledger Entry"; IsUnApply: Boolean)
    var
        OldCustLedgEntry2: Record "Cust. Ledger Entry";
        DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeHandleBill(CustLedgEntry, IsUnApply, IsHandled);
        if IsHandled then
            exit;

        OldCustLedgEntry2.Reset();
        OldCustLedgEntry2.SetCurrentKey("Document Type", "Document No.", "Document Occurrence", "Customer No.", Open);
        OldCustLedgEntry2.SetRange("Document Type", CustLedgEntry."Document Type to Close");
        OldCustLedgEntry2.SetRange("Document No.", CustLedgEntry."Document No. to Close");
        OldCustLedgEntry2.SetRange("Document Occurrence", CustLedgEntry."Document Occurrence to Close");
        OldCustLedgEntry2.SetRange("Customer No.", CustLedgEntry."Customer No.");
        OldCustLedgEntry2.SetRange(Open, true);
        if OldCustLedgEntry2.FindFirst() then begin
            if IsUnApply then begin
                if CustLedgEntry."Bank Receipt Issued" then begin
                    OnHandleBillOnBeforeUpdateCustLedgEntryBankRcpt(OldCustLedgEntry2, CustLedgEntry, IsUnApply);
                    UpdateCustLedgEntryBankRcpt(OldCustLedgEntry2, CustLedgEntry);
                    OnHandleBillOnAfterUpdateCustLedgEntryBankRcpt(OldCustLedgEntry2, CustLedgEntry, IsUnApply);
                    OldCustLedgEntry2."Allow Issue" := true;
                    OldCustLedgEntry2.Modify();
                    ClearCustLedgEntryBankRcpt(CustLedgEntry);
                    CustLedgEntry.Modify();
                    UpdDtldCustLedgEntryBankRcpt(OldCustLedgEntry2."Entry No.", true);
                end;
            end else begin
                OnHandleBillOnBeforeUpdateCustLedgEntryBankRcpt(OldCustLedgEntry2, CustLedgEntry, IsUnApply);
                UpdateCustLedgEntryBankRcpt(CustLedgEntry, OldCustLedgEntry2);
                OnHandleBillOnAfterUpdateCustLedgEntryBankRcpt(OldCustLedgEntry2, CustLedgEntry, IsUnApply);
                CustLedgEntry.Modify();
                ClearCustLedgEntryBankRcpt(OldCustLedgEntry2);
                OldCustLedgEntry2."Allow Issue" := false;
                OldCustLedgEntry2.Modify();
                UpdDtldCustLedgEntryBankRcpt(OldCustLedgEntry2."Entry No.", false);
            end;
        end;

        OnAfterHandleBill(CustLedgEntry, IsUnApply);
    end;

Thank you for you interest.

Best regards
Monica S.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49742.
