### ISSUE TITLE
[Event Change Request] codeunit 8 AccSchedManagement - OnBeforeCalcCellValueInEvaluateExpression 

### ISSUE THREAD

**Issue by LucasOrGa** [microsoft/ALAppExtensions#21060]
Hi,

We have an issue with the Integration Event OnBeforeCalcCellValueInEvaluateExpression  on Codeunit 8 AccSchedManagement:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcCellValueInEvaluateExpression(IsAccSchedLineExpression: Boolean; AccSchedLine: Record "Acc. Schedule Line"; ColumnLayout: Record "Column Layout"; Expression: Text; CalcAddCurr: Boolean; IsFilter: Boolean; var Result: Decimal; var IsHandled: Boolean)
    begin
    end;
```

Could you change the parameter "include the sender" to true?

```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeCalcCellValueInEvaluateExpression(IsAccSchedLineExpression: Boolean; AccSchedLine: Record "Acc. Schedule Line"; ColumnLayout: Record "Column Layout"; Expression: Text; CalcAddCurr: Boolean; IsFilter: Boolean; var Result: Decimal; var IsHandled: Boolean)
    begin
    end;
```

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49622.
