### ISSUE TITLE
[Event Request] - OnBeforeLookupOperationType in Table 36 "Sales Header"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21073]
Hello, please consider adding the following event to Table 36 "Sales Header"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeLookupOperationType(var NoSeries: Record "No. Series"; var SalesHeader: record "Sales Header"; var xSalesHeader: record "Sales Header")
    begin
    end;
```

and call it accordingly inside "OnLookup" trigger of field 12100 "Operation Type":

```
            trigger OnLookup()
            begin
                **OnBeforeLookupOperationType(NoSeries, Rec, xRec);**

                if PAGE.RunModal(PAGE::"Operation Types", NoSeries) = ACTION::LookupOK then
                    Validate("Operation Type", NoSeries.Code);
            end;
```

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49950.
