### ISSUE TITLE
[Event Request] - Change the signature of OnBeforeValidateWorkTypeCode in Table 37 "Sales Line"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21075]
Please, consider modifying the signature of the "OnBeforeValidateWorkTypeCode" event in Table 37 "Sales Line",
from:

```
[IntegrationEvent(true, false)]
    local procedure OnBeforeValidateWorkTypeCode(xSalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;
```

to:

```
[IntegrationEvent(true, false)]
    local procedure OnBeforeValidateWorkTypeCode(**var SalesLine: Record "Sales Line"; var** xSalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;
```

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49745.
