### ISSUE TITLE
[Event Request] - OnAfterLookupBillToCity in Table 36 "Sales Header"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21071]
Hello, please consider adding the following event to Table 36 "Sales Header"

```
   [IntegrationEvent(false, false)]
    local procedure OnAfterLookupBillToCity(var Rec: Record "Sales Header"; var PostCode: Record "Post Code")
    begin
    end;
```

and call it accordingly inside "OnLookup" trigger of field 9 "Bill-to City":

```
            trigger OnLookup()
            begin
                PostCode.LookupPostCode("Bill-to City", "Bill-to Post Code", "Bill-to County", "Bill-to Country/Region Code");

                **OnAfterLookupBillToCity(Rec, PostCode);**
            end;
```

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49745.
