### ISSUE TITLE
[Event Request] - Change the signature of OnBeforeCheckReturnInfo in Table 36 "Sales Header"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21070]
Please, consider modifying the signature of the "OnBeforeCheckReturnInfo" event  in Table 36 "Sales Header", from:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckReturnInfo(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;
```

to:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckReturnInfo(var SalesHeader: Record "Sales Header"; **var xSalesHeader: Record "Sales Header"; BillTo: Boolean;**; var IsHandled: Boolean)
    begin
    end;
```

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49745.
