### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" OnBeforePrepareCheckDocument

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#21084]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnBeforePrepareCheckDocument' to be added to procedure 'PrepareCheckDocument' in codeunit 80 "Sales-Post".

````
    procedure PrepareCheckDocument(var SalesHeader: Record "Sales Header")
    begin
        OnBeforePrepareCheckDocument(SalesHeader); //new
        GetGLSetup();
        GetSalesSetup();
        GetInvoicePostingSetup();
        GetCurrency(SalesHeader."Currency Code");
        FillTempLines(SalesHeader, TempSalesLineGlobal);
        LogErrorMode := true;
    end;
````
````
    [IntegrationEvent(false, false)]
    local procedure OnBeforePrepareCheckDocument(var SalesHeader: Record "Sales Header");
    begin
    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49820.
