### ISSUE TITLE
[Event Request]  Table 83 "Item Journal Line" procedure SubcontractingWorkCenterUsed() 

### ISSUE THREAD

**Issue by lukone** [microsoft/ALAppExtensions#21089]
Hi,

Could you please add the following event?

    procedure SubcontractingWorkCenterUsed(): Boolean
    var
        WorkCenter: Record "Work Center";
        IsHandled: Boolean;
    begin
       //New Event start
        OnBeforeSubcontractingWorkCenterUsed(Rec,WorkCenter,IsHandled);
        if IsHandled then
           Exit();
       //New Event end
        if Type = Type::"Work Center" then
            if WorkCenter.Get("Work Center No.") then
                exit(WorkCenter."Subcontractor No." <> '');

        exit(false);
    end;

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49820.

**Comment by rstefanetti** [comment]
Thank Jesper!
Roberto
