### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" OnBeforeTestUpdatedSalesLine

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#21088]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnBeforeTestUpdatedSalesLine' to be changed in procedure 'TestUpdatedSalesLine' in codeunit 80 "Sales-Post".

````
    local procedure TestUpdatedSalesLine(SalesLine: Record "Sales Line")
    var
        ForwardLinkMgt: Codeunit "Forward Link Mgt.";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        //OnBeforeTestUpdatedSalesLine(SalesLine, IsHandled); //old
        OnBeforeTestUpdatedSalesLine(SalesLine, IsHandled, ErrorMessageMgt); //new
        if IsHandled then
            exit;
````
````
    [IntegrationEvent(false, false)]
    //local procedure OnBeforeTestUpdatedSalesLine(SalesLine: Record "Sales Line"; var IsHandled: Boolean) //old
    local procedure OnBeforeTestUpdatedSalesLine(SalesLine: Record "Sales Line"; var IsHandled: Boolean; var ErrorMessageMgt: codeunit "Error Message Management") //new
    begin
    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49820.
