### ISSUE TITLE
Item Copy Report

### ISSUE THREAD

**Issue by Hornsyld** [microsoft/ALAppExtensions#2108]
Can you make Item Copy Report shipped gloabally? Right now its only shipped in the German Version - I don't see why not to ship in to the other countries now that you already have made the report.

https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh931748(v=nav.90)

Thanks in advance.

**Comment by AlexanderYakunin** [comment]
Already done for W1

**Comment by Hornsyld** [comment]
Installed the Danish Version - but cant find it the Item Copy.
