### ISSUE TITLE
[Code Change Request] Table 64 "Merge Duplicates Buffer" - Merge() Scope OnPrem Tag

### ISSUE THREAD

**Issue by ChrisChristophers** [microsoft/ALAppExtensions#21095]
We are currently using the standard function merge()  to merge via OData Unbound Action. Can you please remove the OnPrem tag? 
![image](https://user-images.githubusercontent.com/118542597/202721882-28cf6850-cda1-4442-8f3a-3013cc78e222.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51059.
