### ISSUE TITLE
Event Request: Table 77 Report Selections

### ISSUE THREAD

**Issue by deanaxon44** [microsoft/ALAppExtensions#21096]
in _**_procedure SetEmailBodyUsageFilters()_**_there is an event **_OnAfterSetEmailBodyUsageFilters(Rec, ReportUsage);_**

Can this be duplicated in **_procedure SetEmailUsageFilters_** and **_SetEmailAttachmentUsageFilters_**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49832.
