### ISSUE TITLE
Design issue? Accounting schedules & SetGLAccColumnFilters

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/ALAppExtensions#211]
There is an issue with Codeunit 8 `AccSchedManagement`. It provides us the two methods `SetGLAccRowFilters` and `SetGLAccColumnFilters`. They are both public and marked as external, so my guess is that they are to be used "from outside". The problem is, that the latter (`SetGLAccColumnFilters`) uses two global variables `FromDate` and `ToDate` to apply the `Date Filter` on the acc. schedule line. Having this Codeunit in my event-handlers (I subscribe to `OnBeforeCalcCellExit` of the same Codeunit) obviously creates a new instance and therefore I lose the contents of these two variables and therefore an empty date filter gets applied to my acc. schedule line.

**Comment by JesperSchulz** [comment]
This issue has been fixed. Thanks for reporting!
