### ISSUE TITLE
[Enum Request] - Table 740 "VAT Report Header" - Field 2 "VAT Report Config. Code"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21107]
Hello,

we ask you to transform the Option field

2 "VAT Report Config. Code"

on Table 740 "VAT Report Header" to "Enum", in order to allow us to extend it with custom values.

Thank you !

**Comment by RadoArvay** [comment]
What version of BC are you talking about?? Because "VAT Report Configuration" enum already exists some time in W1.

**Comment by oldmat** [comment]
Business Central 21.0.46384.46844

740 "VAT Report Header":

```
table 740 "VAT Report Header"
{
    Caption = 'VAT Report Header';
    LookupPageID = "VAT Report List";

    fields
    {
        field(1; "No."; Code[20])
        {
            Caption = 'No.';

            trigger OnValidate()
            begin
                if "No." <> xRec."No." then begin
                    NoSeriesMgt.TestManual(GetNoSeriesCode());
                    "No. Series" := '';
                end;
            end;
        }
        field(2; "VAT Report Config. Code"; Option)
        {
            Caption = 'VAT Report Config. Code';
            Editable = true;
            **OptionCaption = ' ,VAT Transactions Report,Datifattura';
            OptionMembers = " ","VAT Transactions Report",Datifattura;**

            trigger OnValidate()
            begin
                CheckEditingAllowed();
            end;
        }
        field(3; "VAT Report Type"; Option)
        {
            Caption = 'VAT Report Type';
            OptionCaption = 'Standard,Corrective,,,,,,,,,Cancellation ';
            OptionMembers = Standard,Corrective,,,,,,,,,"Cancellation ";

            trigger OnValidate()
            var
```

**Comment by AlexanderYakunin** [comment]
Hello! We cannot make this change as IT option list is very different from W1. Can you share why do you need this change? We have Regulatory Feature team who is responsible for local requirements and VAT Reporting is not an area which should be updated by partners, this is MS responsibility. What are legal requirements we are missing here?

**Comment by oldmat** [comment]
Hello! We use the field 2 "VAT Report Config. Code" of the 740 table to manage the data to fulfill the italian fiscal requirement called "Esterometro". An italian company has to declare the received foreign purchase invoices choosing one method between the ordinary electronic invoicing and the "Esterometro".

**Comment by oldmat** [comment]
Ok, I'll follow that way.
