### ISSUE TITLE
[Event Request] - OnBeforeExitGetPartnerIDFromJobEntry in Record 263 "Intrastat Jnl. Line"

### ISSUE THREAD

**Issue by LucaRoesnick** [microsoft/ALAppExtensions#21103]
Hello, please consider adding the following event to the Record 263 "Intrastat Jnl. Line"

    [IntegrationEvent(false, false)]
    local procedure OnBeforeExitGetPartnerIDFromJobEntry(var IntrastatJnlLine: Record "Intrastat Jnl. Line"; var Customer: Record Customer);
    begin
    end;
>
    local procedure GetPartnerIDFromJobEntry(): Text[50]
    var
        Job: Record Job;
        JobLedgerEntry: Record "Job Ledger Entry";
        Customer: Record Customer;
    begin
        if not JobLedgerEntry.Get("Source Entry No.") then
            exit('');
        if not Job.Get(JobLedgerEntry."Job No.") then
            exit('');
        if not Customer.Get(Job."Bill-to Customer No.") then
            exit('');

        OnBeforeExitGetPartnerIDFromJobEntry(Rec, Customer);
        exit(
          GetPartnerIDForCountry(
            Customer."Country/Region Code", Customer."VAT Registration No.",
            Customer."Partner Type" = Customer."Partner Type"::Person, false));
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49832.
