### ISSUE TITLE
[Event Request] - OnFilterGLBudgetEntry in Codeunit 410 "Update Analysis View"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21105]
Hello, please consider adding the following event to Codeunit 410 "Update Analysis View"

    [IntegrationEvent(false, false)]
    local procedure OnFilterGLBudgetEntry(var GLBudgetEntry: Record "G/L Budget Entry"; var AnalysisView: Record "Analysis View")
    begin
    end;

and call it accordingly inside "UpdateBudgetEntries" procedure:

```
...
...
    local procedure UpdateBudgetEntries(DeleteFromEntry: Integer)
    begin
        AnalysisViewBudgetEntry.SetRange("Analysis View Code", AnalysisView.Code);
        AnalysisViewBudgetEntry.SetFilter("Entry No.", '>=%1', DeleteFromEntry);
        AnalysisViewBudgetEntry.DeleteAll();
        AnalysisViewBudgetEntry.Reset();

        if AnalysisView."Account Filter" <> '' then
            GLBudgetEntry.SetFilter("G/L Account No.", AnalysisView."Account Filter");
        if AnalysisView."Business Unit Filter" <> '' then
            GLBudgetEntry.SetFilter("Business Unit Code", AnalysisView."Business Unit Filter");

        **OnFilterGLBudgetEntry(GLBudgetEntry, AnalysisView);**

        if not GLBudgetEntry.FindSet(true) then
            exit;

        repeat
            if DimSetIDInFilter(GLBudgetEntry."Dimension Set ID", AnalysisView) then
...
...
```

Thank you !

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49832.
