### ISSUE TITLE
[Event Request] - OnBeforeGetUpdateFromSKU in Table 99000829 "Planning Component"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21112]
Hello, please consider adding the following event to Table 99000829 "Planning Component"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetUpdateFromSKU(var Rec: Record "Planning Component")
    begin
    end;
```

and call it accordingly inside "GetUpdateFromSKU" procedure:

```
    local procedure GetUpdateFromSKU()
    var
        SKU: Record "Stockkeeping Unit";
        GetPlanningParameters: Codeunit "Planning-Get Parameters";
    begin

        **OnBeforeGetUpdateFromSKU(Rec);** 

        GetPlanningParameters.AtSKU(SKU, "Item No.", "Variant Code", "Location Code");
        Validate("Flushing Method", SKU."Flushing Method");
    end;

```
Thank you !

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49832.
