### ISSUE TITLE
error in Eventsubscriber OnInsertItemLedgEntryOnCheckItemTracking on post Item

### ISSUE THREAD

**Issue by Tsmprintvis** [microsoft/ALAppExtensions#21118]
When trying to post an Item Journal, where the item has Lot no. tracking enabled,
It results in it erroring out with an error, that makes int impossible to post the line.
The error happens here:
codeunit 6516 "Package Management":
![Codeunit 6516 Package Management](https://user-images.githubusercontent.com/36735751/203300434-2c193949-493f-4f26-a610-bb0e6046571d.png)
 

Got 2 questions to this:
1.	Is it intended that there is an event in PackageManagement Codeunit 6516, that subscribes to 
        OnInsertItemLedgEntryOnCheckItemTracking. Where the ishandled parameter is not being set or checked?
2.	The code executed after the event check seen in Codeunit 22, line 2373 to 2777 does the same as the event subscriber located in 
        the Codeunit 6516 
extra:
- Is it intended that it is only allowed to Post an Item Tracking if it is related to “Purchase Receipt” or “Purchase Return Shipment”?

codeunit 22 "Item Jnl.-Post Line":
![Codeunit 22 Item Jnl -Post Line](https://user-images.githubusercontent.com/36735751/203300427-bf056553-3b63-4c32-aff3-c3ee42afea93.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53910.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 53932.
