### ISSUE TITLE
[EventRequest] OnAfterSetLastModifiedDateTime in Table 23 "Vendor"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21111]
Hello, please consider adding the following event to Table 23 "Vendor"

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetLastModifiedDateTime(var Rec: record Vendor)
    begin
    end;
```

and raise it accordingly inside the "SetLastModifiedDateTime" procedure:

```
    protected procedure SetLastModifiedDateTime()
    begin
        "Last Modified Date Time" := CurrentDateTime();
        "Last Date Modified" := Today();

        **OnAfterSetLastModifiedDateTime(Rec);** 
    end;
```

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 49832.
