### ISSUE TITLE
[Event Change] page 5740 "Transfer Order" - OnAfterTransferLinesEditable

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#21129]
While implementing my issue https://github.com/microsoft/ALAppExtensions/issues/17956 it was forgotten to set the two properties Editable and Enabled on the subpage TransferLines in page "Transfer Order".

            part(TransferLines; "Transfer Order Subform")
            {
                ApplicationArea = Location;
                //Event21.01.ns
                Editable = IsTransferLinesEditable;
                Enabled = IsTransferLinesEditable;
                //Event21.01.ne
                SubPageLink = "Document No." = FIELD("No."),
                              "Derived From Line No." = CONST(0);
                UpdatePropagation = Both;
            }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 50693.
