### ISSUE TITLE
GenerateBOMCompSubTree event request 

### ISSUE THREAD

**Issue by debmitchell-tnp** [microsoft/ALAppExtensions#21124]
In codeunit 5870 Calculate BOM Tree could we get a subscriber event to allow us to exit before a component is added to the buffer similar to how it already does for Replenishment System on the ParentItem variable but for custom properties on the ParentItem?

![image](https://user-images.githubusercontent.com/68606761/203336836-41d0039c-a98c-43ba-a26c-278d60730589.png)

**Comment by NavDeb** [comment]
Hi Alexander, 

Apologies.   Please see below to add in OnBeforeTransferBOMCoponentToBuffer event and IsHandled handling to the GenerateBOMCompSubTree function on CU5870.  New Lines (3, 4, 25 and 34-37 for the publisher).

1.                 if ParentItem."Replenishment System" <> ParentItem."Replenishment System"::Assembly then
2.                     exit(true);
3.                 **OnBeforeTransferBOMCoponentToBuffer(ParentItem, IsHandled)   //new
4.                 if notIsHandled then begin  //New**
5. 
6.                     repeat
7.                         if ("No." <> '') and ((Type = Type::Item) or (TreeType in [TreeType::" ", TreeType::Cost])) then begin
8.                             BOMBuffer.SetLocationVariantFiltersFrom(ItemFilter);
9.                             BOMBuffer.TransferFromBOMComp(
10.                             EntryNo, BOMComp, ParentBOMBuffer.Indentation + 1,
11.                             Round(
12.                                 ParentBOMBuffer."Qty. per Top Item" *
13.                                 UOMMgt.GetQtyPerUnitOfMeasure(ParentItem, ParentBOMBuffer."Unit of Measure Code"), UOMMgt.QtyRndPrecision()),
14.                             Round(
15.                                 ParentBOMBuffer."Scrap Qty. per Top Item" *
16.                                 UOMMgt.GetQtyPerUnitOfMeasure(ParentItem, ParentBOMBuffer."Unit of Measure Code"), UOMMgt.QtyRndPrecision()),
17.                             CalcCompDueDate(ParentBOMBuffer."Needed by Date", ParentItem, "Lead-Time Offset"),
18.                             ParentBOMBuffer."Location Code");
19.                             if Type = Type::Item then
20.                                 GenerateItemSubTree("No.", BOMBuffer);
21.                         end;
22.                     until Next() = 0;
23.                     BOMBuffer := ParentBOMBuffer;
24.                 
25.                 **end;  //New code**
26. 
27. 
28.                 exit(true);
29.             end;
30.         end;
31.     end;
32. 
33. 
34.     **[IntegrationEvent(false, false)]
35.     local procedure OnBeforeTransferBOMCoponentToBuffer(ParentItem: Record Item; var IsHandled: Boolean)
36.     begin
37.     end;**
38.

**Comment by NavDeb** [comment]
Any update on this please?
