### ISSUE TITLE
[Event Request] codeunit 5704 "TransferOrder-Post Shipment" - OnBeforeCheckHeaderShippingAdvice

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#21127]
Hi,

Can you add a event to override shipping advice check for transfer orders in codeunit 5704 "TransferOrder-Post Shipment"?

I need to override this code, and I need TransferHeader as parameter.
```
                if "Shipping Advice" = "Shipping Advice"::Complete then
                    if not GetShippingAdvice() then
                        Error(Text008);
```

Example:
See sales header:
```
    local procedure CheckHeaderShippingAdvice(var SalesHeader: Record "Sales Header")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckHeaderShippingAdvice(SalesHeader, WhseShip, IsHandled);
        if IsHandled then
            exit;

        if (SalesHeader."Shipping Advice" = SalesHeader."Shipping Advice"::Complete) and SalesHeader.Ship then
            SalesHeader.CheckShippingAdvice();
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51294.
