### ISSUE TITLE
[Event Change] table 5407 "Prod. Order Component" - OnBeforeCalcBaseQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#21128]
Parameter ProdOrderComponent: Record "Prod. Order Component" with property var please

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcBaseQty(var ProdOrderComponent: Record "Prod. Order Component"; CurrentFieldNo: integer; Qty: Decimal; FromFieldName: Text; ToFieldName: Text; var Result: Decimal; var IsHandled: Boolean)
    begin
        //A200F0000.Event.21.01 Parameter ProdOrderComponet as VAR
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 50693.
