### ISSUE TITLE
[EVENT CHANGE] T121 "Purch. Rcpt. Line" OnAfterInsertInvLineFromRcptLine

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#21125]
Can you please change the signature of the following publisher to expose the NextLineNo by var

    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertInvLineFromRcptLine(var PurchLine: Record "Purchase Line"; PurchOrderLine: Record "Purchase Line"; NextLineNo: Integer; PurchRcptLine: Record "Purch. Rcpt. Line")
    begin
    end;

to

    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertInvLineFromRcptLine(var PurchLine: Record "Purchase Line"; PurchOrderLine: Record "Purchase Line"; var NextLineNo: Integer; PurchRcptLine: Record "Purch. Rcpt. Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51294.
