### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnAfterSetQtyToHandleAndInvoiceOnBeforeReservEntryModify

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#21133]
I'm checking Issue #19091 in W1 22.0.49766.0 like I was asked by Andrei Panko and am seeing no change. I did however see a big performance gain by removing the "Reservation Status" loop while it is already sorted on that field. Congrats to us all for that.

I have requested OnAfterSetQtyToHandleAndInvoiceOnBeforeReservEntryModify in request #13465 but it should and must be set at two (2) places in the code, not one (1).

I have attached a picture with a comparison between 21.01 and 22.0.49766.0. Please take a close look at both green boxes.

Apart from that change you could also maybe change the Find('-') to FindLast() also. With my current knowledge of how BC21 works with AzureSQL that might also be a bit of performance gain.

New Code:

local procedure SetQtyToHandleAndInvoice(TrackingSpecification: Record "Tracking Specification")
    ...
        //if ReservEntry1.Find('-') then A109F0006.Event20.02.o
        //A109F0006.Event20.02.ns
        if ReservEntry1.FindFirst() then begin
            ModifyLine := false;
            //A109F0006.Event20.02.ne
            if (ReservEntry1."Qty. to Handle (Base)" <> TotalQtyToHandle) or
               (ReservEntry1."Qty. to Invoice (Base)" <> TotalQtyToInvoice) and not ReservEntry1.Correction
            then begin
                ReservEntry1."Qty. to Handle (Base)" := TotalQtyToHandle;
                ReservEntry1."Qty. to Invoice (Base)" := TotalQtyToInvoice;
                OnSetQtyToHandleAndInvoiceOnBeforeReservEntryModify(ReservEntry1, TrackingSpecification);
                //ReservEntry1.Modify(); A109F0006.Event20.02.o
                ModifyLine := true;
            end;
            //A200F0000.Event20.02.ns
            OnAfterSetQtyToHandleAndInvoiceOnBeforeReservEntryModify(ReservEntry1, TrackingSpecification, TotalTrackingSpecification, ModifyLine);
            if ModifyLine then
                ReservEntry1.Modify();
        end;
    //A200F0000.Event20.02.ne
Old Code:

local procedure SetQtyToHandleAndInvoice(TrackingSpecification: Record "Tracking Specification")
    ...
        if ReservEntry1.Find('-') then
            if (ReservEntry1."Qty. to Handle (Base)" <> TotalQtyToHandle) or
               (ReservEntry1."Qty. to Invoice (Base)" <> TotalQtyToInvoice) and not ReservEntry1.Correction
            then begin
                ReservEntry1."Qty. to Handle (Base)" := TotalQtyToHandle;
                ReservEntry1."Qty. to Invoice (Base)" := TotalQtyToInvoice;
                OnSetQtyToHandleAndInvoiceOnBeforeReservEntryModify(ReservEntry1, TrackingSpecification);
                ReservEntry1.Modify();
            end;
![Event Request  page 6510 Item Tracking Lines - OnAfterSetQtyToHandleAndInvoiceOnBeforeReservEntryModify](https://user-images.githubusercontent.com/30273162/203369537-2eca9843-84b5-47f3-acfb-93b4dffb6acd.jpg)

**Comment by AlexanderYakunin** [comment]
We cannot implement you suggestion for using ModifyLine in second part because you want to change default behavior and this is breaking change for other partners. Current behavior is to ReservEntry1.Modify, but you want to make it conditional using IF ModifyLine. Other partners will not know about your idea and ModiftLine will be false for their extensions. 

Please always consider that event implementation should not change existing business logic.
