### ISSUE TITLE
[Event Parameter Request] - report 7391 "Whse. Get Bin Content" - OnInsertItemJournalLineOnBeforeValidateEntryType

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#21134]
In issue https://github.com/microsoft/ALAppExtensions/issues/17292 I requested an event and asked for variables ItemJournalTempl, ItemJournalBatch to be fetched earlies but allas it was forgotten to put these two variables in the requested event.

It is needed to fix a bug in the base app to prioritize dimensions with field "Source Code" which is set after the validation of Item No.

Base code
"Source Code" := ItemJournalTemplate."Source Code";
must be put before the validation of any fields that put together a "Dimension Set ID".

    local procedure InsertItemJournalLine(BinContent: Record "Bin Content")
    var
        ItemLedgerEntryType: Enum "Item Ledger Entry Type";
        IsHandled: Boolean;
    begin
        with ItemJournalLine do begin
            Init();
            "Line No." := "Line No." + 10000;
            ItemLedgerEntryType := Enum::"Item Ledger Entry Type"::Transfer;
            OnInsertItemJournalLineOnBeforeValidateEntryType(ItemJournalLine, BinContent, ItemLedgerEntryType, ItemJournalTemplate, ItemJournalBatch);
            Validate("Entry Type", ItemLedgerEntryType);

    [IntegrationEvent(false, false)]
    local procedure OnInsertItemJournalLineOnBeforeValidateEntryType(
        var ItemJournalLine: Record "Item Journal Line"; var BinContent: Record "Bin Content"; var ItemLedgerEntryType: Enum "Item Ledger Entry Type";
        ItemJournalTemplate: Record "Item Journal Template"; ItemJournalBatch: Record "Item Journal Batch")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 50693.
