### ISSUE TITLE
[Event Request] report 6653 "Combine Return Receipts"

### ISSUE THREAD

**Issue by agirdhar007** [microsoft/ALAppExtensions#21132]
Hi,
We have base report 295 "Combine Shipments" in which we have procedure ShowResults, similar to that we have report 6653 "Combine Return Receipts" where the
procedure for ShowResult is different. In report 6653 "Combine Return Receipts" we don't have the boolean for HideDialog in the event 
"OnReturnReceiptHeaderOnAfterFinalizeSalesInvHeader" and code is also different in ShowResult function.
In report 6653 "Combine Return Receipts" I have changed the code as per report 295 "Combine Shipments", can you update the changes-->

local procedure ShowResult()
    begin
        OnBeforeShowResult(SalesHeader, NoOfSalesInvErrors, PostInv);

        if SalesHeader."No." <> '' then begin // Not the first time
            FinalizeSalesInvHeader();
//ALANSH <<
            OnReturnReceiptHeaderOnAfterFinalizeSalesInvHeader(SalesHeader, NoOfSalesInvErrors, PostInv, HideDialog);
            if (NoOfSalesInvErrors = 0) and not HideDialog then begin
                Message(Text010, NoOfSalesInv)
            else
		if not HideDialog then
                Message(Text007, NoOfSalesInvErrors)
        end else
		if not HideDialog then
            Message(Text008);
    end;
//ALANSH >>

//ALANSH<<
procedure SetHideDialog(NewHideDialog: Boolean)
    begin
        HideDialog := NewHideDialog;
    end;

var
HideDialog : Boolean;

[IntegrationEvent(false, false)]
    local procedure OnReturnReceiptHeaderOnAfterFinalizeSalesInvHeader(var SalesHeader: Record "Sales Header"; var NoOfSalesCrMemoErrors: Integer; PostInv: Boolean; var HideDialog: Boolean)
    begin
    end;
//ALANSH>>

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51294.
