### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - procedure CheckItem - OnCheckItemOnAfterItemTestField

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#21141]
Please add the following existing Event OnCheckItemOnAfterItemTestField to procedure CheckItem in Codeunit 22 Item Jnl.-Post Line

```
[Event Request] Codeunit 22 Item Jnl.-Post Line - procedure CheckItem
begin
    if GetItem(ItemNo, false) then begin
        if not CalledFromAdjustment then
            Item.TestField(Blocked, false);

        OnCheckItemOnAfterItemTestField(Item, ItemJnlLine, CalledFromAdjustment); // <-- NEW EVENT

    end else
        Item.Init();
end;
```

```
[IntegrationEvent(false,false)]
local procedure OnCheckItemOnAfterItemTestField(Item: Record Item; ItemJnlLine: Record "Item Journal Line"; CalledFromAdjustment: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52098.
