### ISSUE TITLE
[Access Change Request] Table 5050 - procedure ProcessNameChange

### ISSUE THREAD

**Issue by knkcgv** [microsoft/ALAppExtensions#21157]
Could you please change "local procedure ProcessNameChange" to "procedure ProcessNameChange" to give access to this procedure.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51059.
