### ISSUE TITLE
event request - table `G/L Account` - field `Totaling` - `OnBeforeIsTotalingCheck(Rec, IsHandled)` - to allow blank Totaling for non-Totals Account Type

### ISSUE THREAD

**Issue by dnpb** [microsoft/ALAppExtensions#21153]
Any time Totaling is validated, *even if it is to a blank string*, BC insists that the Account Type must be a Totals one.

This causes spurious errors if we import G/L Accounts and Validate all fields, and the Account Type is not a Totals type, even if the Totaling filter is blank :-(

It should be OK to have a non-Totals Account Type and validate the Totaling filter to empty. An empty Totaling is fine for non-Totals... in fact, it's the only value that is! So it shouldn't cause an error.

***

Duilio at MS suggested that because this code has been around for a long time in its current state, we should request an event instead (or perhaps, eventually alongside) changing the code.

Thus could we please request Duilio's suggested event, to at least enable opting out of this, in cases where we know it to be problematic (data imports, etc.)

emitted like:
```al
            trigger OnValidate()
            var
                IsHandled: Boolean; // NEW
            begin
                // <NEW>
                IsHandled := false;
                OnBeforeIsTotalingCheck(Rec, IsHandled);
                if not IsHandled then
                // </NEW>
                    if not IsTotaling() then
                        FieldError("Account Type");

                CalcFields(Balance);
            end;

```

published as:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsTotalingCheck(GLAccount: Record "G/L Account"; var IsHandled: Boolean)
    begin
    end;
```

***

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51686.
