### ISSUE TITLE
[Event Request] Codeunit 21 "Item Jnl.-Check Line" OnBeforeCheckVariantMandatory

### ISSUE THREAD

**Issue by stebruni** [microsoft/ALAppExtensions#21154]
Dear ALAppExtensions team,

On RunCheck function in Codeunit 21 I would like to request integration event 'OnBeforeCheckVariantMandatory' to modify the procedure to check Variant.

Thanks

  OnBeforeCheckVariantMandatory(ItemJnlLine, IsHandled)  //NEW
  if not IsHandled then begin  //NEW
    if Item.IsVariantMandatory(InvtSetup."Variant Mandatory if Exists") then
          TestField("Variant Code");
  end;   //NEW

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckVariantMandatory(var ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52098.
