### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" OnBeforeInitGLEntryVAT

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#21165]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnBeforeInitGLEntryVAT' to be changed in codeunit 12 "Gen. Jnl.-Post Line".

````
    [IntegrationEvent(false, false)]
    //local procedure OnBeforeInitGLEntryVAT(GenJnlLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry") //old
    local procedure OnBeforeInitGLEntryVAT(var GenJnlLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry") //new
    begin
    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51064.
