### ISSUE TITLE
[Code Change Request] Change Scope OnPrem to Cloud For Italian withholding management

### ISSUE THREAD

**Issue by DamianoCastagna** [microsoft/ALAppExtensions#21162]
Hello I'm asking for a scope change for procedures into table "Purch. Withh. Contribution" 
We are having an issue due to Universal code iniziative. 
Our app calls 3 functions from this table :
- ValorizzaRitenute
- ValorizzaINPS
- ValorizzaINAIL

These 3 function have scope OnPrem and we can no longer use them with the  cloud target.

![image](https://user-images.githubusercontent.com/118895493/203527308-3a7363f0-8bb4-45f3-aef7-95fe91e0989a.png)

We think that all procedures into this table must have scope Cloud

For us this is a critical issue and we hope you can add this in a minor release of the 21 version.

Thanks
Damiano

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51281.
