### ISSUE TITLE
[Enum Request] - Table 361 "Analysis by Dim. Parameters" - Field 20 "Show Actual/Budgets"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21171]
Hello,

we ask you to transform the Option field

20 "Show Actual/Budgets"

on Table 361 "Analysis by Dim. Parameters" to "Enum", in order to allow us to extend it with custom values.

Thank you !

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 50641.
