### ISSUE TITLE
[Code Change Request] page 5814 "Item Charge Assignment (Sales)", page 5805 "Item Charge Assignment (Purch)"

### ISSUE THREAD

**Issue by SteveKrisjanovsD365** [microsoft/ALAppExtensions#21174]
We need to extend item charge assignment functionality in Business Central, but in order to do so, there is one global variable in each of these pages that requires a modification in the Base Application:

page 5805 "Item Charge Assignment (Purch)":
global variable PurchLine2

page 5814 "Item Charge Assignment (Sales)"
global variable SalesLine2

Can you kindly make these these two variables **protected variables** in their respective pages? Currently we cannot extend these pages due to the current scope of these two variables.

**Comment by AlexanderYakunin** [comment]
Already done for v.22

**Comment by SteveKrisjanovsD365** [comment]
@AlexanderYakunin can you plz clarify? v.22?

The latest onprem version of BC we are currently targeting for our product is BC19.5 (2021 Wave 2)

**Comment by AlexanderYakunin** [comment]
Please read WIKI for this area, we implement requests for next major and one version before, right now it is 22.x and 21.x.

**Comment by SteveKrisjanovsD365** [comment]
@AlexanderYakunin 

Understood! We didn't have any expectations getting this change into 19.x (I just wanted to share with you the version we're currently using to avoid ambiguity). Fully aware that the change request window is closed for 19.x :)

If 21.x and 22.x are the active releases to receive change implementations, was this change brought into both or just 22.x per your original comments when this ticket was closed?

**Comment by AlexanderYakunin** [comment]
Just 22.x, as this is external request. We down port only event requests to 21.x
