### ISSUE TITLE
[Event Request] - OnBeforeCopyFromFAJournalAndPost in Codeunit 11 "Gen. Jnl.-Check Line"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21179]
Hello, please consider changing the signature of the "OnBeforeCopyFromFAJournalAndPost" event to Codeunit 11 "Gen. Jnl.-Check Line", from:

`OnBeforeCheckOperationOccurredDate(var GenJournalLine: Record "Gen. Journal Line")`

to:

`OnBeforeCheckOperationOccurredDate(var GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)`

and call it accordingly inside "CheckOperationOccurredDate" procedure:

```
 local procedure CheckOperationOccurredDate(var GenJnlLine: Record "Gen. Journal Line")
    var

        **IsHandled: Boolean;**

    begin

        **OnBeforeCheckOperationOccurredDate(GenJnlLine, IsHandled);
        if IsHandled then 
            exit;** 

        if GenJnlLine."Operation Occurred Date" = 0D then
            GenJnlLine."Operation Occurred Date" := GenJnlLine."Posting Date";
        if (GenJnlLine."Operation Occurred Date" < GLSetup."Last Gen. Jour. Printing Date") and (GenJnlLine.Amount <> 0) then
            GenJnlLine.FieldError("Operation Occurred Date", ErrorInfo.Create(StrSubstNo(Text12001, GLSetup."Last Gen. Jour. Printing Date")));

        OnAfterCheckOperationOccurredDate(GenJnlLine);
    end;
```

Thank you !

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52098.
