### ISSUE TITLE
[Event Request] Report 492 "Copy Purchase Document"- OnPreReportOnBeforeCopyPurchaseDoc

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21189]
Please include sender in the function OnPreReportOnBeforeCopyPurchaseDoc:

```
[IntegrationEvent(true, false)]
local procedure OnPreReportOnBeforeCopyPurchaseDoc(var CopyDocumentMgt: Codeunit "Copy Document Mgt."; UseRequestPage: Boolean; IncludeHeader: Boolean; RecalculateLines: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52178.
