### ISSUE TITLE
Potential bug in HttpClient/Request with gzip data in response and 4xx status

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/ALAppExtensions#21182]
I'm not sure if this is the correct place to submit this bug. I don't believe we have insight into the implementation of HttpClient, so I cannot pinpoint exactly what's going wrong. I think I read once that it is implemented via RestSharp, but that could be a false memory.

The API we are communicating with returns gzip responses. In this example FedEx. When we receive a 200 response, BC takes that response, inflates it, and we get the text representation of the json via HttpResponseMessage.Content().ReadAs(text). When the api returns a 4xx status, the same call will result in the gzip message being returned. This then results in a hard error when attempting to display the text. This hard error is probably a second issue the team would want to investigate, but normally we wouldn't just throw the response into an error message in our code. The workaround is to use the data compression codeunit. Then we can validate if it's gzip, inflate, and get the proper text value. We've found that if we through the data to the stream, it's never inflated for us, but if we throw it to text, it is, if it's a 200 status.

To reiterate, 200 status, gzip response is inflated. 4xx response, it is not. Curl requires the compressed flag either way, Postman handles all status codes correctly. Both curl and postman show the content-encoding as gzip, but BC does not show it in the headers. However BC does process the 200 correctly.

I've attached a small reproduction. When running "No Inflate" you'll hit hard crash as we are allowing base BC to handle the gzip. When running "Inflate" we circumvent this issue by manually inflating the gzip response. I couldn't include a 200 response as it requires secrets.

[HttpRequestBug.zip](https://github.com/microsoft/ALAppExtensions/files/10078083/HttpRequestBug.zip)

curl command (formatted for powershell):

`.\curl.exe --output .\zcurl-response.txt --cacert .\ca-bundle.crt --include --location --request POST 'https://apis-sandbox.fedex.com/rate/v1/rates/quotes' --header 'Authorization: Bearer none' --header 'Content-Type: application/json' --data-raw '{"accountNumber":{"value":"1234567"},"carrierCodes":["FDXE"]}'`

Add --compressed if you want to see the uncompressed output from curl.

**Comment by pri-kise** [comment]
@mjmatthiesen have tried set the `Accept-Encoding` Header explicit to `Accept-Encoding: gzip, deflate`

Maybe you can force by that the decompression.

Since the HttpClient is only a wrapper for the .net Class.
It is always useful to have look at the .net class.
https://github.com/dotnet/runtime/issues/21214

**Comment by mjmatthiesen** [comment]
@pri-kise 

Setting the header's accept-encoding doesn't change anything. That said, the thread you linked gave me enough information to close this issue. I used httpbin to reproduce the status 200, and it isn't inflating. Why the fedex response does, I don't know, but since we need to inflate for the 4xx responses it's honestly irrelevant anyway.
