### ISSUE TITLE
[Event Parameter Change] Codeunit 5816 Undo Return Receipt Line - procedure Code - event OnAfterInsertNewReceiptLine 

### ISSUE THREAD

**Issue by vdevmt** [microsoft/ALAppExtensions#21181]
We would like the PostedWhseRcptLineFound parameter to be passed by var (like other similar codeunits):

ORIGINAL:
    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertNewReceiptLine(var ReturnReceiptLine: Record "Return Receipt Line"; var PostedWhseReceiptLine: Record "Posted Whse. Receipt Line"; PostedWhseRcptLineFound: Boolean; DocLineNo: Integer)
    begin
    end;

NEW:
    [IntegrationEvent(false, false)]
    local procedure OnAfterInsertNewReceiptLine(var ReturnReceiptLine: Record "Return Receipt Line"; var PostedWhseReceiptLine: Record "Posted Whse. Receipt Line"; var PostedWhseRcptLineFound: Boolean; DocLineNo: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52027.
