### ISSUE TITLE
Bug - codeunit 7301 "Whse. Jnl.-Register Line" - InsertToBinContent

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#21187]
With Issue 17142 the Procedure InsertToBinContent  in codeunit 7301 "Whse. Jnl.-Register Line" was changed from local to global
(https://github.com/microsoft/ALAppExtensions/issues/17142).

When this procedure is now called from external code the Location Variable (global Variable) which is used in the Function is not set which can lead to incorrect Bin Content Data if a Location with "Directed Put-Away and Pick" is used.

A Call of the procedure GetLocation is missing before the marked Line: GetLocation("Location Code")

![image](https://user-images.githubusercontent.com/46991052/203748612-be779238-ff57-4ff8-b54d-52fec9f8a76a.png)

**Comment by AlexanderYakunin** [comment]
Already fixed

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
