### ISSUE TITLE
[Event Parameter Change] Codeunit 5815 "Undo Sales Shipment Line" - procedure Code - event OnAfterInsertNewShipmentLine

### ISSUE THREAD

**Issue by vdevmt** [microsoft/ALAppExtensions#21194]
We would like the PostedWhseShipmentLine parameter to be passed by var (like other similar codeunits):

ORIGINAL:
[IntegrationEvent(false, false)]
local procedure OnAfterInsertNewShipmentLine(var SalesShipmentLine: Record "Sales Shipment Line"; PostedWhseShipmentLine: Record "Posted Whse. Shipment Line"; var PostedWhseShptLineFound: Boolean; DocLineNo: Integer; ItemShptEntryNo: Integer)
begin
end;

NEW:
[IntegrationEvent(false, false)]
local procedure OnAfterInsertNewShipmentLine(var SalesShipmentLine: Record "Sales Shipment Line"; var PostedWhseShipmentLine: Record "Posted Whse. Shipment Line"; var PostedWhseShptLineFound: Boolean; DocLineNo: Integer; ItemShptEntryNo: Integer)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52027.
