### ISSUE TITLE
[Request for External] Codeunit 905 - "Assembly Line Management", local procedure 

### ISSUE THREAD

**Issue by SSZurmussen7112** [microsoft/ALAppExtensions#21193]
Hello Team,

in codeunit 905 "Assembly Line Management" two versions of procedure AddBOMLine exists. One of them is not local, has three parameters and calls the InsertAsmLine() and the AddBOMLine() procedure with six parameters. But this second AddBOMLine procedure is local.

I want to calculate the Assembly Order Lines on my own and want to decide, which Assembly BOM lines should be copied and which not. But this will only work inclusive all events if this second local AddBOMLine procedure could be called from external.

So, please could you make this change:

Old:
`local procedure AddBOMLine(AssemblyHeader: Record "Assembly Header"; var AssemblyLine: Record "Assembly Line"; AsmLineRecordIsTemporary: Boolean; BOMComponent: Record "BOM Component"; ShowDueDateBeforeWorkDateMessage: Boolean; QtyPerUoM: Decimal)`

New:
`procedure AddBOMLine(AssemblyHeader: Record "Assembly Header"; var AssemblyLine: Record "Assembly Line"; AsmLineRecordIsTemporary: Boolean; BOMComponent: Record "BOM Component"; ShowDueDateBeforeWorkDateMessage: Boolean; QtyPerUoM: Decimal)`

Thanks in advance and best regards,
Stephan

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51059.
