### ISSUE TITLE
Feature Request: Hash-Functions in AL

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/ALAppExtensions#212]
I have already requested this on Yammer, but I now have a very specific case where I need this: Regarding my issue #2699, I would like to become the primary key for Table 49 to be a 40 character hash string that is generated out of a number of fields, instead of concatenating the various fields together (and probably blows the 250 character limit). But we do not have any access to hash functions, be it MD5, SHA-1 or anything.

I've recently noticed the Codeunits in range 3000 .. 3026 that neatly wrap .NET features in C/AL Codeunits and thus allowing us to use them. Please add another Codeunit here that provides us with simplified access to hashing functions that take 1 string and return 1 string. Something like this:

````
CalculateSHA256(Value : Text) : Text
enc := enc.UTF8;
SHA256 := SHA256.SHA256Managed();
ba := enc.GetBytes(Value);
ba := SHA256.ComputeHash(ba);
EXIT(GetHexString(ba));
````

**Comment by JesperSchulz** [comment]
Sounds as if this issue has been resolved :-) Closing issue.
