### ISSUE TITLE
[Bug] Sharepoint Authorization Failing

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/ALAppExtensions#21208]
I do not mamange to get Sharepoint Authorisation with  procedure CreateUserCredentials(AadTenantId: Text; ClientId: Text; UserName: Text; Credential: Text; Scopes: List of [Text]): Interface "SharePoint Authorization";

When proceeding, a new browser window opens and seems to ask for approbation. But AAD Tenant ID missing.
URL called is https://login.microsoftonline.com//oauth2/v2.0/authorize?client_id=B968700E-D706-...
![2022-11-27_16-34-19](https://user-images.githubusercontent.com/30075742/204143735-c2dc8e0f-13e9-4b19-99fc-daa24078b0ae.png)

Version : FR Business Central 21.1 (plateforme 21.0.48357.49378 + application 21.1.48363.48789)

**Comment by pri-kise** [comment]
@YvesDesrumaux this was already fixed by my pull request, but isn't released yet.
https://github.com/microsoft/ALAppExtensions/pull/21002

**Comment by pri-kise** [comment]
@YvesDesrumaux can this issue be closed?
