### ISSUE TITLE
[Extensibility Request] Sharepoint Deletion,Copy

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/ALAppExtensions#21207]
Sharepoint module allows Create, List, upload and download...
Would be create to allow Deletion and copy too.

**Comment by jwikman** [comment]
@YvesDesrumaux we are working on the `delete file` capability for one of our apps. I will create a PR with that as soon as it's done.

I do not think there are any copy functionality in the REST API, you probably need to implement that by downloading the file, uploading to the new place and then delete the original file.

**Comment by jwikman** [comment]
You can follow the `delete file` PR at https://github.com/microsoft/ALAppExtensions/pull/22402
