### ISSUE TITLE
page 402 "Sales Order Statistics" var ProfitLCY, AdjProfitLCY and TotalAdjCostLCY

### ISSUE THREAD

**Issue by AllanEjlskov** [microsoft/ALAppExtensions#21200]
Is it possible to have the 3 variables ProfitLCY, AdjProfitLCY and TotalAdjCostLCY  as protected var?
![ProtectedVarOnSalesOrderStatistics](https://user-images.githubusercontent.com/119041061/203954214-f0abd460-a23c-4429-b95c-c6fabc29347e.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51059.
