### ISSUE TITLE
[Event Parameter Request] codeunit 7020 "Sales Line - Price" - OnAfterUpdate

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#21217]
in the same light as https://github.com/microsoft/ALAppExtensions/issues/21215 I would like to request an extra var parameter SalesHeader:

    procedure Update(AmountType: enum "Price Amount Type")
    begin
        if not SalesLine."Allow Line Disc." then
            SalesLine."Line Discount %" := 0;

        OnAfterUpdate(SalesLine, CurrPriceType, AmountType, SalesHeader);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdate(var SalesLine: Record "Sales Line"; CurrPriceType: Enum "Price Type"; AmountType: Enum "Price Amount Type"; var SalesHeader: Record "Sales Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52027.
