### ISSUE TITLE
[Event Change Request] Codeunit 22 - OnApplyItemLedgEntryOnBeforeModifyOldItemLedgEntry

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#2122]
This issue is related with #1560 

In **codeunit 22 Item Jnl.-Post Line**, function **ApplyItemLedgEntry**, please change the event OnApplyItemLedgEntryOnBeforeOldItemLedgEntryModify as follows:

```
[…]
    // >> MODIFY
    // OnApplyItemLedgEntryOnBeforeOldItemLedgEntryModify(ItemLedgEntry,OldItemLedgEntry);
    OnApplyItemLedgEntryOnBeforeOldItemLedgEntryModify(ItemJnlLine,ItemLedgEntry,OldItemLedgEntry);
    // << MODIFY
    OldItemLedgEntry.MODIFY;
[…]
```

**Comment by skeck** [comment]
Also could you please change ItemLedgEntry to VAR?

current:
`OnApplyItemLedgEntryOnBeforeOldItemLedgEntryModify(ItemLedgEntry,VAR OldItemLedgEntry);`

new:
`OnApplyItemLedgEntryOnBeforeOldItemLedgEntryModify(ItemJnlLine,**VAR** ItemLedgEntry,VAR OldItemLedgEntry);`

**Comment by NKarolak** [comment]
Note: updated as 
`LOCAL [IntegrationEvent] OnApplyItemLedgEntryOnBeforeOldItemLedgEntryModify(ItemLedgerEntry : Record "Item Ledger Entry";VAR OldItemLedgerEntry : Record "Item Ledger Entry";ItemJournalLine : Record "Item Journal Line")`

@skeck No `**VAR** ItemLedgEntry` as requested
