### ISSUE TITLE
[Event Parameter Request] codeunit 7020 "Sales Line - Price" - OnBeforeSetPrice

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#21221]
in the same light as https://github.com/microsoft/ALAppExtensions/issues/21215 I would like to request an extra var parameter SalesHeader:

    procedure SetPrice(AmountType: Enum "Price Amount Type"; PriceListLine: Record "Price List Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetPrice(SalesLine, PriceListLine, AmountType, IsHandled, SalesHeader);
        if IsHandled then
            exit;

        case AmountType of

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetPrice(var SalesLine: Record "Sales Line"; PriceListLine: Record "Price List Line"; AmountType: Enum "Price Amount Type"; var IsHandled: Boolean; var SalesHeader: Record "Sales Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51150.
