### ISSUE TITLE
[Event Request] - OnBeforeValidateWithholdingTaxCode in Table 12113 "Tmp Withholding Contribution"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21227]
Hello, please consider adding the following event to Table 12113 "Tmp Withholding Contribution"

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateWithholdingTaxCode(var Rec: Record "Tmp Withholding Contribution"; var xRec: record "Tmp Withholding Contribution"; var IsHandled: Boolean)
    begin
    end;

and call it accordingly inside the "OnValidate" trigger of field 30 "Withholding Tax Code"

            trigger OnValidate()

            **var
                IsHandled: Boolean;**

            begin

                **OnBeforeValidateWithholdingTaxCode(Rec, xRec, IsHandled);
                if IsHandled then
                    exit;**

                CalculateWithholdingTax();
                if "Social Security Code" <> '' then
                    CalculateSocialSecurity("Taxable Base");

                // INAIL START
                if "INAIL Code" <> '' then
                    CalcolaINAIL("Taxable Base");
                // INAIL END
            end;
Thank you !

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52143.
