### ISSUE TITLE
[Event Request] - "OnAfterGetBBan" in Table 288 "Vendor Bank Account"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21223]
Hello, please consider changing the signature of the OnAfterGetBBan event inside Table 288 "Vendor Bank Account", from:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterGetBBan(var IBAN: Code[50])
    begin
    end;
```

to: 

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterGetBBan(**var VendorBankAccount: Record "Vendor Bank Account";** var IBAN: Code[50])
    begin
    end;
```

and to call accordingly inside the "GetBBAN" procedure:

```
    procedure GetBBAN()
    begin
        if (ABI <> '') and (CAB <> '') and ("Bank Account No." <> '') then
            BBAN := AbiCabCodes.CalcBBAN(ABI, CAB, "Bank Account No.")
        else
            BBAN := '';
        IBAN := '';

        **OnAfterGetBBAN(Rec, IBAN);**

    end;
```

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52146.
