### ISSUE TITLE
[Event Request] Table 7316 - DeleteRelatedLines

### ISSUE THREAD

**Issue by GlicPi** [microsoft/ALAppExtensions#2123]
We need a new publisher in the function "DeleteRelatedLines".

![grafik](https://user-images.githubusercontent.com/34307263/56355340-56488680-61d6-11e9-8a31-cb422ef720bc.png)

**Comment by AlexanderYakunin** [comment]
We already have event OnBeforeDeleteWhseRcptRelatedLines(WhseRcptLine) to manage this scenario.
