### ISSUE TITLE
[Extensibility Enhancements] Procedure CopyLineToDoc() in in page 5850 "Posted Sales Document Lines" should not be OnPrem

### ISSUE THREAD

**Issue by PeterConijn** [microsoft/ALAppExtensions#21232]
The procedure CopyLineToDoc() in page 5850 "Posted Sales Document Lines" is marked as OnPrem, but I cannot see a reason in the code as to why it should be. 

Can the OnPrem tag be removed to make it available for cloud extensibility?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51059.
