### ISSUE TITLE
Report substitution

### ISSUE THREAD

**Issue by mou5a123** [microsoft/ALAppExtensions#2124]
The Report Substitution is possible whenever a report is invoked as the result of the user activating a page action that has the **RunObject** property set to a report or a report is invoked through one of the following static methods on the Report data type: (_**Run, RunModal, SaveAsHtml, SaveAsXml, SaveAsPdf, SaveAsExcel, SaveAsWord, RunRequestPage, Execute,Print,SaveAs**_) and for this methods if you declare a **DataType Report** and the use one of these it will not work.

Let's take this example : Page "Intrastat Journal" (311) Have this action GetEntries that contains a call for Report "Get Item Ledger Entries" (594) .

![1](https://user-images.githubusercontent.com/4316552/56290646-de218880-6123-11e9-99db-adbaf3ae943c.PNG)

In this case I want to use Report Substitution to Replace with a new Report :
![2](https://user-images.githubusercontent.com/4316552/56290793-348ec700-6124-11e9-9ffa-f837856afb81.PNG)
But this will not work until I change the Report Call with Report.RunModal(594) :

![3](https://user-images.githubusercontent.com/4316552/56291022-b8e14a00-6124-11e9-8a0c-9c6ef1d11ab9.PNG)
And this will be a problem because I will loose the Instance of "**GetItemEntries**" when I set the Rec **(GetItemEntries.SetIntrastatJnlLine(Rec**)).
Also a lot of Code are using this Terminology  **"Record_Data_Type".RUNMODAL** and not **Report.RUNMODAL(ReportNumber....)** so what do you suggest because I cannot touch the Nav Standard code like I did in Page "**Intrastat Journal**" (311)

**Comment by mou5a123** [comment]
@atoader I undrestand now that it only works for the **static methods** on the Report data type But what do you mean to expose the parameter RecordRef of the codeunit "Reporting Triggers" I knew that I should not directly subscribe to the events in these new 'system' codeunits . While technically possible as of now, Microsft will block this in the future. So I didn't get your point ?

**Comment by mou5a123** [comment]
@atoader Could you please give a hand Here !

**Comment by atoader** [comment]
@mou5a123 the system codeunit event has a parameter that exposes the record passed to the report. I think you can subscribe directly to the codeunit to get unblocked. @JesperSchulz can we add one more parameter to the event in codeunit 44 to expose the system trigger parameter?

**Comment by mou5a123** [comment]
@atoader When I use SubstituteReport event in codeunit 2000000005 it dosen't catch the Invoke of the Report subscription some as the event in codeunit 44 so It cannot event enter to parameter function or to it's parameters. I put a break point in this new system codeunit and it didn't even catch it 

![Capture](https://user-images.githubusercontent.com/4316552/56655682-c736e500-6693-11e9-9fab-9f584d8792d2.PNG)

So how can I use the RecordRef when I cannot enter to the codeunit function?

**Comment by ajkauffmann** [comment]
Related issue: https://github.com/Microsoft/ALAppExtensions/issues/1731

**Comment by ikoletic** [comment]
This issue is a question. Please submit your questions on [business central community ](https://community.dynamics.com/business/f/758) or on [BC development yammer groups](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035).

**Comment by Alokkul** [comment]
@mou5a123 how you had resolved this issue. i am also facing a same. please suggest.
