### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" -  MessageIfPurchLinesExist()

### ISSUE THREAD

**Issue by lv-rawesh** [microsoft/ALAppExtensions#21249]
We would like to request the following event in the purchase header in the MessageIfPurchLinesExist() function. We want to make it possible to disable this message as it is now possible in the sales header.

**Sales Header:**
![image](https://user-images.githubusercontent.com/119503032/204798520-31a0c3d7-852b-46b1-aa22-d515230d87ac.png)

**Purchase Header**
![image](https://user-images.githubusercontent.com/119503032/204798650-f2a88c82-ebe9-4dbc-a524-6f4645d0a8d3.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52485.
