### ISSUE TITLE
[Event Request] codeunit 5407 "Prod. Order Status Management" TransProdOrderRtngCmtLn

### ISSUE THREAD

**Issue by GaryFrostick2** [microsoft/ALAppExtensions#21255]
Would it be possible to have a new event in TransProdOrderRtngCmtLn in codeunit 5407?

 local procedure TransProdOrderRtngCmtLn(FromProdOrder: Record "Production Order")
    var
        FromProdOrderRtngComment: Record "Prod. Order Rtng Comment Line";
        ToProdOrderRtngComment: Record "Prod. Order Rtng Comment Line";
        IsHandled: Boolean;
    begin
       //New event
       OnBeforeTransProdOrderRtngCmtLn(FromProdOrder, ToProdOrder, IsHandled);
       If IsHandled then
          exit;
       with FromProdOrderRtngComment do begin
            SetRange(Status, FromProdOrder.Status);
            SetRange("Prod. Order No.", FromProdOrder."No.");

**Comment by AleksandricMarko** [comment]
Already implemented.
