### ISSUE TITLE
[Request for External] Table 37 "Sales Line" - Procedure CheckWarehouseForQtyToShip

### ISSUE THREAD

**Issue by solleap** [microsoft/ALAppExtensions#21257]
Hello, we need the following currently local procedure to be set as global. Can you please check this? Thank you!

`local procedure CheckWarehouseForQtyToShip()`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51059.
