### ISSUE TITLE
[Event Request] codeunit 5407 "Prod. Order Status Management" TransProdOrderCmtLine

### ISSUE THREAD

**Issue by GaryFrostick2** [microsoft/ALAppExtensions#21254]
Would it be possible to have a new event in the TransProdOrderCmtLine of codeunit 5407

 local procedure TransProdOrderCmtLine(FromProdOrder: Record "Production Order")
    var
        FromProdOrderCommentLine: Record "Prod. Order Comment Line";
        ToProdOrderCommentLine: Record "Prod. Order Comment Line";
        IsHandled: Boolean;
    begin
        //New Event
        OnBeforeTransProdOrderCmtLine(FromProdOrder, ToProdOrder, IsHandled);
        if IsHandled then
           exit;
        with FromProdOrderCommentLine do begin
            SetRange(Status, FromProdOrder.Status);
            SetRange("Prod. Order No.", FromProdOrder."No.");

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52143.
