### ISSUE TITLE
[Event Request] codeunit 5407 "Prod. Order Status Management" TransProdOrderBOMCmtLine

### ISSUE THREAD

**Issue by GaryFrostick2** [microsoft/ALAppExtensions#21256]
Would it be possible to have a new event in TransProdOrderBOMCmtLine of codeunit 5407?

    local procedure TransProdOrderBOMCmtLine(FromProdOrder: Record "Production Order")
    var
        FromProdOrderBOMComment: Record "Prod. Order Comp. Cmt Line";
        ToProdOrderBOMComment: Record "Prod. Order Comp. Cmt Line";
        IsHandled: Boolean;
    begin
        //New Event
        OnBeforeTransProdOrderBOMCmtLine(FromProdOrder, ToProdOrder, IsHandled);
        If IsHandled then
           exit;
        with FromProdOrderBOMComment do begin
            SetRange(Status, FromProdOrder.Status);
            SetRange("Prod. Order No.", FromProdOrder."No.");

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52143.
