### ISSUE TITLE
[Event Request] Page 161 "Purchase Statistics" OnCalculateTotalsOnAfterPurchPostSumPurchLinesTemp - Additional parameters needed

### ISSUE THREAD

**Issue by MetaK** [microsoft/ALAppExtensions#21268]
The event 'OnCalculateTotalsOnAfterPurchPostSumPurchLinesTemp' is supossed to be an event refering to the previous action:

PurchPost.SumPurchLinesTemp(Rec, TempPurchLine, 0, TotalPurchLine, TotalPurchLineLCY, VATAmount, VATAmountText);

But as u can see, the parameters that get changes in PurchPost.SumPurchLinesTemp are not accesible in the event commented (p.e: VATAmount)

![image](https://user-images.githubusercontent.com/10777971/205308453-b266c4c3-a8f8-46dc-a52e-49eb23c629cc.png)

In my case i just need VATAmount because the PIT TAX in ES,
But if is posible i would like to have TempPurchLine because is the parameter that is being modified and used in this function.

Moreover, Totalamount1 and TotalAmount2 seems a bit useless, since they will be modified in the next point:

![image](https://user-images.githubusercontent.com/10777971/205309203-cfeee6fd-032f-472e-a78a-f782e95ff908.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52143.
