### ISSUE TITLE
CreateSalesInvoiceJobTask on "Job Create-Invoice" codeunit

### ISSUE THREAD

**Issue by AntonioCapdevila480** [microsoft/ALAppExtensions#21265]
Hello, I have an issue, on codeunit 1002-"Job Create-Invoice" the call to CreateSalesHeader function sends the parameters: Job, PostingDate and JobPlanningLine.
...
SalesHeader2."Document Type" := SalesHeader2."Document Type"::Invoice;
CreateSalesHeader(Job, PostingDate, **JobPlanningLine**);
OnCreateSalesInvoiceJobTaskOnBeforeTempJobPlanningLineFind(JobTask, SalesHeader, InvoicePerTask, TempJobPlanningLine);
...
I think that JobPlanningLine variable it's a wrong variable at this point, TempJobPlanningLine must be used instead, because JobPlanningLine variable is not initialized.
Best regards.

Antonio Capdevila.

**Comment by AlexanderYakunin** [comment]
JobPlanningLine is prepared by this code

        JobPlanningLine.Copy(JobPlanningLineSource);
        JobPlanningLine.SetCurrentKey("Job No.", "Job Task No.", "Line No.");

        OnCreateSalesInvoiceLinesOnBeforeJobPlanningLineFindSet(JobPlanningLine, InvoiceNo, NewInvoice, PostingDate, CreditMemo);
        if JobPlanningLine.FindSet() then
            repeat
                if TransferLine(JobPlanningLine) then begin
                    LineCounter := LineCounter + 1;
                    if JobPlanningLine."Job No." <> JobNo then
                        LastError := StrSubstNo(Text009, JobPlanningLine.FieldCaption("Job No."));
                    OnCreateSalesInvoiceLinesOnAfterValidateJobPlanningLine(JobPlanningLine, LastError);
                    if LastError <> '' then
                        Error(LastError);
                    if NewInvoice then
                        TestExchangeRate(JobPlanningLine, PostingDate)
                    else
                        TestExchangeRate(JobPlanningLine, SalesHeader."Posting Date");
                end;
            until JobPlanningLine.Next() = 0;

before this call.
