### ISSUE TITLE
[Event Request] Undo Sales Shipment Line Codeunit 5815 OnBeforeDeleteServItemsQst

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/ALAppExtensions#21260]
Hello,

Please add an event on this location

Procedure Code
----
```
            FindFirst();
            repeat
                if not HideDialog then
                    Window.Open(Text003);
                CheckSalesShptLine(SalesShptLine);
            until Next() = 0;


            ServItem.SetCurrentKey("Sales/Serv. Shpt. Document No.");
            ServItem.SetRange("Sales/Serv. Shpt. Document No.", "Document No.");
            //+ChangeRequest
            Handled := false;
            OnBeforeDeleteServItemsQst(SalesShptLine,ServItem,HideDialog,DeleteServItems,Handled);
            if not Handled then
            //-ChangeRequest
                if ServItem.FindFirst() then
                    if not HideDialog then
                        DeleteServItems := Confirm(Text004, true)
                    else
                        DeleteServItems := true;

            Find('-');
```

----

Event:
`OnBeforeDeleteServItemsQst(SalesShptLine: Record "Sales Shipment Line"; var ServItem: Record "Service Item"; HideDialog: Boolean; var DeleteServItems: Boolean; var Handled: Boolean);`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52253.
