### ISSUE TITLE
[Request for External] Page 21 "Customer Card" - procedure ContactOnAfterValidate

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#21261]
Hello, we need the following currently local procedure to be set to global. Can you please check this? Thank you!

[Request-For-External] Page 21 "Customer Card" - procedure ContactOnAfterValidate

```
procedure ContactOnAfterValidate()
begin
    ActivateFields();
end;
```

**Comment by AlexanderYakunin** [comment]
Should we made protected local procedure ActivateFields() instead?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51059.
