### ISSUE TITLE
[Enum Request] - Table Reservation Entry - Field 11 "Source Subtype" 

### ISSUE THREAD

**Issue by DamianoCastagna** [microsoft/ALAppExtensions#21263]
Please change the field into Enum so it can be extensible

**Comment by AlexanderYakunin** [comment]
Sorry, this field cannot be transformed to enum, it does not make any sense. We only use Integer value of this field.

**Comment by DamianoCastagna** [comment]
Sorry but I don't understand. 
I want to create a new document type extending the enum Sales Document Type with my values 50000,50001. 
But when I use the reservation entry it's not possible to use these values because it's an option and not an integer

field(11; "Source Subtype"; Option)
        {
            Caption = 'Source Subtype';
            OptionCaption = '0,1,2,3,4,5,6,7,8,9,10';
            OptionMembers = "0","1","2","3","4","5","6","7","8","9","10";
        }
