### ISSUE TITLE
[Global Request] table 246 "Requisition Line" - FilterLinesWithItemToPlan

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#21267]
Please set local procedure FilterLinesWithItemToPlan to global like has already been done in all other planning entities (Just search for the word 'FilterLinesWithItemToPlan' in the base app)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51059.
