### ISSUE TITLE
[Event Request] - OnBeforeShowInconsistentEntries in Codeunit 12 "Gen. Jnl.-Post Line"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21278]
Hello, please consider adding the following event to Codeunit 12 "Gen. Jnl.-Post Line"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowInconsistentEntries(var TempGLEntryPreview: Record "G/L Entry" temporary; var IsHandled: Boolean)
    begin        
    end;
```

and call it accordingly inside the "ShowInconsistentEntries" procedure:

```
    procedure ShowInconsistentEntries()
    var
        **IsHandled: Boolean;**
    begin

        **OnBeforeShowInconsistentEntries(TempGLEntryPreview, IsHandled);
        if IsHandled then
            exit;**

        Page.Run(Page::"G/L Entries Preview", TempGLEntryPreview);
    end;
```

Thank you !

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51064.
