### ISSUE TITLE
[Change Event or Create New] codeunit 99000854 "Inventory Profile Offsetting" - 

### ISSUE THREAD

**Issue by extranrollo** [microsoft/ALAppExtensions#21275]
In codeunit 99000854 "Inventory Profile Offsetting" i need to skip the procedure BlanketOrderConsump as shown in the screenshot.

So please change the existing Event or create a new Event at the first line of the procedure to skip it completely

As new Parameters i need the variables 
- Item as var
- "IsHandeld" as var

![grafik](https://user-images.githubusercontent.com/36401349/205416103-6facb973-d996-496e-a8fe-5e686011e448.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52143.
