### ISSUE TITLE
[Event Request] - OnBeforeIsGLEntryInconsistent in Codeunit 12 "Gen. Jnl.-Post Line"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21276]
Hello, please consider adding the following event to Codeunit 12 "Gen. Jnl.-Post Line"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsGLEntryInconsistent(var GLEntryInconsistent: Boolean); 
    begin
    end;

```
and call it accordingly inside the "IsGLEntryInconsistent" procedure:

```
    procedure IsGLEntryInconsistent(): Boolean
    begin

        **OnBeforeIsGLEntryInconsistent(GLEntryInconsistent);**

        exit(GLEntryInconsistent);
    end;
```

Thank you !

**Comment by AlexanderYakunin** [comment]
Please explain why do you need this? We do not expect someone modify return value in this procedure, as value of GLEntryInconsistent should be changed instead.

**Comment by oldmat** [comment]
Hello,

i need to manage the consistency for C12, since we are trying to extend that codeunit (not easy at all).
You are maybe right about checking the "GLEntryInconsistent" variable value, but i can not see any useful event for that.

The "OnCodeOnBeforeFinishPosting" or the "OnAfterGLFinishPosting" would probably be good for that, but they don't manage the "GLEntryInconsistent" variable.
Should I ask you to modify the signature of one of these events?


Da: Alexander Yakunin ***@***.***>
Inviato: giovedì 12 gennaio 2023 17:28
A: microsoft/ALAppExtensions ***@***.***>
Cc: oldmat ***@***.***>; Author ***@***.***>
Oggetto: Re: [microsoft/ALAppExtensions] [Event Request] - OnBeforeIsGLEntryInconsistent in Codeunit 12 "Gen. Jnl.-Post Line" (Issue #21276)


Please explain why do you need this? We do not expect someone modify return value in this procedure, as value of GLEntryInconsistent should be changed instead.

-

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.
