### ISSUE TITLE
[Event Request] Codeunit 5856 "TransferOrder-Post Transfer"  InsertDirectTransLine

### ISSUE THREAD

**Issue by GaryFrostick2** [microsoft/ALAppExtensions#21272]
Would it be possible to have a new event in  Codeunit 5856 "TransferOrder-Post Transfer"  InsertDirectTransLine?

 local procedure InsertDirectTransLine(DirectTransHeader: Record "Direct Trans. Header"; TransLine: Record "Transfer Line")
    begin
        DirectTransLine.Init();
        DirectTransLine."Document No." := DirectTransHeader."No.";
        DirectTransLine."Line No." := TransLine."Line No.";
        DirectTransLine."Item No." := TransLine."Item No.";
        DirectTransLine.Description := TransLine.Description;
        DirectTransLine.Quantity := TransLine."Qty. to Ship";
        DirectTransLine."Unit of Measure" := TransLine."Unit of Measure";
        DirectTransLine."Shortcut Dimension 1 Code" := TransLine."Shortcut Dimension 1 Code";
        DirectTransLine."Shortcut Dimension 2 Code" := TransLine."Shortcut Dimension 2 Code";
        DirectTransLine."Dimension Set ID" := TransLine."Dimension Set ID";
        DirectTransLine."Gen. Prod. Posting Group" := TransLine."Gen. Prod. Posting Group";
        DirectTransLine."Inventory Posting Group" := TransLine."Inventory Posting Group";
        DirectTransLine.Quantity := TransLine.Quantity;
        DirectTransLine."Quantity (Base)" := TransLine."Quantity (Base)";
        DirectTransLine."Qty. per Unit of Measure" := TransLine."Qty. per Unit of Measure";
        DirectTransLine."Unit of Measure Code" := TransLine."Unit of Measure Code";
        DirectTransLine."Gross Weight" := TransLine."Gross Weight";
        DirectTransLine."Net Weight" := TransLine."Net Weight";
        DirectTransLine."Unit Volume" := TransLine."Unit Volume";
        DirectTransLine."Variant Code" := TransLine."Variant Code";
        DirectTransLine."Units per Parcel" := TransLine."Units per Parcel";
        DirectTransLine."Description 2" := TransLine."Description 2";
        DirectTransLine."Transfer Order No." := TransLine."Document No.";
        DirectTransLine."Transfer-from Code" := TransLine."Transfer-from Code";
        DirectTransLine."Transfer-to Code" := TransLine."Transfer-to Code";
        DirectTransLine."Transfer-from Bin Code" := TransLine."Transfer-from Bin Code";
        DirectTransLine."Item Category Code" := TransLine."Item Category Code";
        if TransLine.Quantity > 0 then begin
            OriginalQuantity := TransLine.Quantity;
            OriginalQuantityBase := TransLine."Quantity (Base)";
            PostItemJnlLine(TransLine, DirectTransHeader, DirectTransLine);
            DirectTransLine."Item Shpt. Entry No." := InsertShptEntryRelation(DirectTransLine);
            if WhseShip then
                PostWhseJnlLine(ItemJnlLine, OriginalQuantity, OriginalQuantityBase, TempHandlingSpecification, 0);
            if WhseReceive then
                PostWhseJnlLine(ItemJnlLine, OriginalQuantity, OriginalQuantityBase, TempHandlingSpecification, 1);
        end;
        DirectTransLine.Insert();
        //New Event
        OnAfterInsertTransShptLine(DirectTransLine, TransLine, DirectTransHeader);
    end;

**Comment by AlexanderYakunin** [comment]
This event already implemented: OnAfterInsertDirectTransLine(DirectTransLine, DirectTransHeader, TransLine)
