### ISSUE TITLE
[Event Request] - Event signature change OnPostOutputOnAfterSetMfgUnitCost in Codeunit 22 "Item Jnl.-Post Line"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21288]
Please, consider changing the signature of OnPostOutputOnAfterSetMfgUnitCost event in Codeunit 22 "Item Jnl.-Post Line" from:

    [IntegrationEvent(false, false)]
    local procedure OnPostOutputOnAfterSetMfgUnitCost(var ItemJournalLine: Record "Item Journal Line"; var MfgUnitCost: Decimal)
    begin
    end;

to:

    [IntegrationEvent(false, false)]
    local procedure OnPostOutputOnAfterSetMfgUnitCost(var ItemJournalLine: Record "Item Journal Line"; var ProdOrderLine: Record "Prod. Order Line"; var MfgUnitCost: Decimal)
    begin
    end;

and call it accordingly inside the "PostOutput" procedure:

```
...
...
                If not IsHandled THEN BEGIN
                    MfgItem.Get(ProdOrderLine."Item No.");
                    MfgItem.TestField("Gen. Prod. Posting Group");
                    if Subcontracting then
                        MfgUnitCost := ProdOrderLine."Unit Cost" / ProdOrderLine."Qty. per Unit of Measure"
                    else
                        if MfgSKU.Get(ProdOrderLine."Location Code", ProdOrderLine."Item No.", ProdOrderLine."Variant Code") then
                            MfgUnitCost := MfgSKU."Unit Cost"
                        else
                            MfgUnitCost := MfgItem."Unit Cost";

                    **OnPostOutputOnAfterSetMfgUnitCost(ItemJnlLine, ProdOrderLine, MfgUnitCost);**

                    Amount := "Output Quantity" * MfgUnitCost;
                    "Amount (ACY)" := ACYMgt.CalcACYAmt(Amount, "Posting Date", false);
                    OnPostOutputOnAfterUpdateAmounts(ItemJnlLine);
...
...
```

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52098.
