### ISSUE TITLE
[Event Request] Codeunit 7312 "Create Pick" OnBeforeDistributeReservedQtyByBins

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#21295]
Hi al team,

we need a publisher in function DistrubuteReservedQtyByBins with handled pattern. If possible we need this change for BC 20.

    local procedure DistrubuteReservedQtyByBins(var TempBinContentBuffer: Record "Bin Content Buffer" temporary)
        var
            TempBinContentBufferByBins: Record "Bin Content Buffer" temporary;
            TempBinContentBufferByBlockedBins: Record "Bin Content Buffer" temporary;
            WarehouseEntry: Record "Warehouse Entry";
            WhseItemTrackingSetup: Record "Item Tracking Setup";
            QtyLeftToDistribute: Decimal;
            QtyInBin: Decimal;
            IsHandled: Boolean;
        begin
            >>> new code begin
            OnBeforeDistributeReservedQtyByBins(TempBinContentBuffer, IsHandled);
            if IsHandled then
                exit;
            <<< new code end
            with TempBinContentBuffer do begin
                if FindSet() then
                    repeat

and the publisher:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDistributeReservedQtyByBins(var TempBinContentBuffer: Record "Bin Content Buffer" temporary; var IsHandled: Boolean)
    begin
    end;

**Comment by Vadim-Stepanenko** [comment]
We do not provide events into version that are not latest (so 21.x for now). This code doesn't exist in 21 so we can't provide event there too.
