### ISSUE TITLE
EB Payment Journal (Belgium) not suggesting payments for multiple ledger entries.

### ISSUE THREAD

**Issue by IulianSadoveac** [microsoft/ALAppExtensions#21297]
When posting multiple ledger entries on the same document number, the EB Payment Journal -> Suggest Vendor Payment creates just one payment entry, with the message below:
"Some payments were not suggested because there are still open payments in journal template <X>."

I understand the intentionality behind it but it's not ideal when you expect to have multiple ledger entries on the same document number. This can be easily done in the Gen. Journal today. 
Is there any chance this can be changed so that it will create payment lines for all the open ledger entries on the same document? 
Can't this be done better, so that the suggested payment line is a total of all the open ledger entries? 
Or, finding a better way to find duplicated payments, instead of throwing a general message?

Thank you.

Belgian localization
EB Payment Journal

**Comment by AlexanderYakunin** [comment]
Sorry, we are not processing requests for functional changes here. Please create support requests or even better new idea about this possibility on aka.ms/bcideas
