### ISSUE TITLE
[Event Request] report 7315 "Calculate Whse. Adjustment" - OnAfterGetRecordItemOnBeforeNextItemJournalLine

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#21308]
This yet another modification on issue https://github.com/microsoft/ALAppExtensions/issues/17267
It looks like in 21.02 that I received OnAfterGetRecordItemOnAfterAdjmtBinContentBufferModify (instead of my incorrectly named OnAfterModifyAdjmtBinQuantityBuffer) but allas it was set in the wrong place.
I need it outside the if statement:

                                        ReservationEntry.CalcSums("Qty. to Handle (Base)");
                                        if ReservationEntry."Qty. to Handle (Base)" <> 0 then begin
                                            "Qty. to Handle (Base)" += ReservationEntry."Qty. to Handle (Base)";
                                            OnBeforeAdjmtBinQuantityBufferModify(TempAdjmtBinContentBuffer, ReservationEntry);
                                            Modify();
                                            OnAfterGetRecordItemOnAfterAdjmtBinContentBufferModify(TempAdjmtBinContentBuffer, ItemJnlLine, ReservationEntry);
                                        end;
                                        OnAfterGetRecordItemOnBeforeNextItemJournalLine(TempAdjmtBinContentBuffer, ItemJnlLine, ReservationEntry); //A200F0000.Event20.00
                                    until ItemJnlLine.Next() = 0;
                            until Next() = 0;

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetRecordItemOnBeforeNextItemJournalLine(var TempAdjmtBinContentBuffer: Record "Bin Content Buffer"; var ItemJnlLine: Record "Item Journal Line"; var ReservationEntry: Record "Reservation Entry")
    begin
        //A200F0000.Event20.00
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 50693.
