### ISSUE TITLE
Run Excel Report from code issue (The current report operation is not supported for Excel Layout reports)

### ISSUE THREAD

**Issue by OleksiiAndoran** [microsoft/ALAppExtensions#21302]
We faced with an issue related to Excel report functionality.
We are trying to call report directly in the code through Report.Run(Number: Integer, [RequestWindow: Boolean], [SystemPrinter: Boolean], var [Record: Table]);
Such error occurs:
![image](https://user-images.githubusercontent.com/64095744/205752252-ca3969c2-44e9-4f91-a23c-12e02854c2fd.png)
**Will it be fixed anyhow in future releases or is there any workarounds for that?**

Small example for reproducing:
(super simple one, just to receive the error)

Report which should be generated:
```AL
report 70101 "Export Sales Order to Excel"
{
    ApplicationArea = All;
    Caption = 'Export Sales Order to Excel';
    DefaultLayout = Excel;
    ExcelLayout = 'TestExcel.xlsx';
    UsageCategory = ReportsAndAnalysis;

    dataset
    {
        dataitem("Sales Header"; "Sales Header")
        {
            PrintOnlyIfDetail = true;
            RequestFilterFields = "No.";

            column(DocumentNo_; "No.")
            {

            }
            column(Bill_to_Customer_No_; "Bill-to Customer No.")
            {

            }
            dataitem("Sales Line"; "Sales Line")
            {
                DataItemLink = "Document Type" = field("Document Type"), "Document No." = field("No.");

                column(No_; "No.")
                {

                }
                column(Quantity; Quantity)
                {

                }
            }
        }
    }
}
```

A place where the report should be created automatically:
```AL
[EventSubscriber(ObjectType::Page, Page::"Sales Order", 'OnAfterActionEvent', 'Release', true, true)]
local procedure SalesOrder_OnAfterRelease(var Rec: Record "Sales Header")
begin
    Report.Run(Report::"Export Sales Order to Excel", false, true, Rec);
end;
```

**Comment by pri-kise** [comment]
@OleksiiAndoran I understand your issue, but this repository isn't the right place to request such features.

It would be better if you ask for such a feature in the offical yammer partner group: https://www.yammer.com/dynamicsnavdev/

Or maybe you could go the AL Lanuage Repo (https://github.com/microsoft/AL) to request at least a warning for Reports that have the default layout excel, when they are called  like this in AL Code.

Addtionally you should maybe create or search for an idea on https://aka.ms/bcideas

Current solution right now might be to use SaveAs with ReportFormat Excel

**Comment by AlexanderYakunin** [comment]
We cannot process this requests here
