### ISSUE TITLE
IT Localization - Report Selection

### ISSUE THREAD

**Issue by Delpixe** [microsoft/ALAppExtensions#21304]
Hello,

For the IT Localization, I think it would be useful to add:
- on the Report Selections - Purchase -> "P. Subcontracting Order"
- on the Report Selection - Inventory -> "Subcontr. Transfer Order"
- on the Report Selections - Sales -> "S. Accomp Invoice"

Thanks in advance

**Comment by AlexanderYakunin** [comment]
This is not an extensibility ask, but one more idea. It should finally be added to W1, not IT. Please create this idea on aka.ms/bcideas (or if this is already created there, just vote for)
