### ISSUE TITLE
[Request for External] Report 292 "Copy Sales Document" - LookupDocNo

### ISSUE THREAD

**Issue by srol001195** [microsoft/ALAppExtensions#21314]
Dear ALAppExtensions Team,

Please consider changing the scope of LookupDocNo from local to global so that it can be used in fields/triggers added to the reportextension.

```
report 292 "Copy Sales Document"
{

...

    //local procedure LookupDocNo()
    //---------------------- CHANGE SCOPE <<
    procedure LookupDocNo()
    //---------------------- CHANGE SCOPE >>
```

Thank you,
SR

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51059.
