### ISSUE TITLE
[Events Request] codeunit 1340 "Undo Bank Statement (Yes/No)"

### ISSUE THREAD

**Issue by MetaK** [microsoft/ALAppExtensions#21328]
Please add events to the codeunit of the subject.

OnBeforeInsert/OnBeforeModify would be amazing:

![image](https://user-images.githubusercontent.com/10777971/206187683-04981507-15ec-4810-9250-2ca467a47164.png)

![image](https://user-images.githubusercontent.com/10777971/213394784-faccee33-3bee-4a98-8c96-383ba1c4f19c.png)

![image](https://user-images.githubusercontent.com/10777971/213394880-5a5282d7-b488-46e0-987b-2d7aacee4ac4.png)

OnAfter will force partners to do a modify() inside the event (if we can avoid it, better).

We are open to any event, but pls add some event to the codeunit.

**Comment by AlexanderYakunin** [comment]
Please define event placement in the code.

**Comment by MetaK** [comment]
Added the images suggested...

(BTW the codeunit has just 3 modify and 2 inserts that correspond to the events requested, dunno where was the confusion there...)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
