### ISSUE TITLE
[Event Request] Table 5965 "Service Contract Header" - OnAfterUpdateCont

### ISSUE THREAD

**Issue by knkcgv** [microsoft/ALAppExtensions#21321]
Hello,

could you please add a new event at the end of the procedure UpdateCont:

    procedure UpdateCont(CustomerNo: Code[20])
    var
        ContBusRel: Record "Contact Business Relation";
        Cont: Record Contact;
        Cust: Record Customer;
    begin
        if Cust.Get(CustomerNo) then begin
            ....
        end;
        // Start-----------
        OnAfterUpdateCont(Rec, CustomerNo);
        // Stop----------
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateCont(var ServiceContractHeader: Record "Service Contract Header"; CustomerNo: Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.
