### ISSUE TITLE
[Event Request] table 5767 "Warehouse Activity Line"

### ISSUE THREAD

**Issue by cbrandemann** [microsoft/ALAppExtensions#21324]
Please add event publisher OnAfterTransferFromJobPlanningLine in  table 5767 "Warehouse Activity Line" with the following signature:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterTransferFromJobPlanningLine(var WarehouseActivityLine: Record "Warehouse Activity Line"; JobPlanningLine: Record "Job Planning Line")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.
