### ISSUE TITLE
[Event Request] Report 11511 (NAVDACH)

### ISSUE THREAD

**Issue by GlicPi** [microsoft/ALAppExtensions#2132]
We need a new Publisher in Report 11511 "Item Copy", in the "CopyItem" function.

![grafik](https://user-images.githubusercontent.com/34307263/56359689-8c8c0300-61e2-11e9-8f0a-b4a9556a755f.png)

**Comment by AlexanderYakunin** [comment]
We don't have DACH report anymore, you are working with old code. Instead, we have W1 report 730 for same purpose, this event already exist here.
