### ISSUE TITLE
[Extensibility] PurchPost - OnPostUpdateCreditMemoLineOnAfterResetTempLines

### ISSUE THREAD

**Issue by alinat2022** [microsoft/ALAppExtensions#21340]
Hello,

In this issue #20198, it was requested for an event at the beginning of function` local procedure PostUpdateCreditMemoLine()` , that followed the same pattern as the event present at the beginning of function `local procedure PostUpdateInvoiceLine()`.

In version 21.2, we can see this event. 
Although it does not have the suggested name, the more important request is to please also allow for the variable TempPurchLine to be sent by reference. We need this in our code.

Currently, the event looks like this:
```
    [IntegrationEvent(false, false)]
    local procedure OnPostUpdateCreditMemoLineOnAfterResetTempLines(TempPurchLine: Record "Purchase Line" temporary; var IsHandled: Boolean)
    begin
    end;
```
 What we would like to have is this:
```
     [IntegrationEvent(false, false)]
    local procedure OnPostUpdateCreditMemoLineOnAfterResetTempLines(**var** TempPurchLine: Record "Purchase Line" temporary; var IsHandled: Boolean)
    begin
    end;
```
Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.
