### ISSUE TITLE
[Event Request] Codeunit 22"Item Jnl.-Post Line" update OnApplyItemLedgEntryOnBeforeStartApplication

### ISSUE THREAD

**Issue by vovazvv** [microsoft/ALAppExtensions#21342]
Please add the variable **AppliedQty** as **var** parameter to the event OnApplyItemLedgEntryOnBeforeStartApplication.

The reason: in some cases, need to have possibility to change sign
Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52253.
