### ISSUE TITLE
[Event Request] Codeunit 1304 "Sales-Quote to Invoice Yes/No" OnBeforeShowInvoice

### ISSUE THREAD

**Issue by SvenSakulowski** [microsoft/ALAppExtensions#21347]
Please add an event OnBeforeShowInvoice in Codeunit 1304 "Sales-Quote to Invoice Yes/No".

Suggested Event Definition:
    
    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowInvoice(var InvoiceSalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;

Suggested Code:

    trigger OnRun()
    var
        InvoiceSalesHeader: Record "Sales Header";
        SalesQuoteToInvoice: Codeunit "Sales-Quote to Invoice";
        OfficeMgt: Codeunit "Office Management";
    begin
        [...]
        Commit();
        
        if GuiAllowed then
            if OfficeMgt.AttachAvailable() then
                // Moved "PAGE.Run(PAGE::"Sales Invoice", InvoiceSalesHeader);" to new method Start
                ShowInvoice(InvoiceSalesHeader);
                // Moved "PAGE.Run(PAGE::"Sales Invoice", InvoiceSalesHeader);" to new method Stop
            else
                if Confirm(StrSubstNo(OpenNewInvoiceQst, InvoiceSalesHeader."No."), true) then
                    // Moved "PAGE.Run(PAGE::"Sales Invoice", InvoiceSalesHeader);" to new method Start
                    ShowInvoice(InvoiceSalesHeader);
                    // Moved "PAGE.Run(PAGE::"Sales Invoice", InvoiceSalesHeader);" to new method Stop
    end;

    //new method
    local procedure ShowInvoice(InvoiceSalesHeader: Record "Sales Header")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeShowInvoice(InvoiceSalesHeader, IsHandled);
        if IsHandled then
            exit;

        PAGE.Run(PAGE::"Sales Invoice", InvoiceSalesHeader);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.
