### ISSUE TITLE
[Event Request] Table 5092 "Opportunity" OnBeforeRunSalesQuotePage and OnBeforeRunModalSalesQuotePage

### ISSUE THREAD

**Issue by SvenSakulowski** [microsoft/ALAppExtensions#21343]
New events are needed for extensibility, to influence which page to run.
Please add events OnBeforeRunSalesQuotePage and OnBeforeRunModalSalesQuotePage in table 5092 "Opportunity" (or allow for extensibility in another way).

Suggested Event Definitions:
    
    [IntegrationEvent(false, false)]
    local procedure OnBeforeRunSalesQuotePage(SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeRunModalSalesQuotePage(SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;

Suggested Code:

    procedure CreateQuote()
    var
        [...]
    begin
        [...]
        OnCreateQuoteOnBeforePageRun(SalesHeader, Rec);

        //moved "PAGE.Run(PAGE::"Sales Quote", SalesHeader);" to new method Start
        RunSalesQuotePage(SalesHeader);
        //moved "PAGE.Run(PAGE::"Sales Quote", SalesHeader);" to new method Stop
    end;

    procedure ShowQuote()
    var
        SalesHeader: Record "Sales Header";
    begin
        if SalesHeader.Get(SalesHeader."Document Type"::Quote, "Sales Document No.") then
            //moved "PAGE.RunModal(PAGE::"Sales Quote", SalesHeader);" to new method Start
            RunModalSalesQuotePage(SalesHeader);
            //moved "PAGE.RunModal(PAGE::"Sales Quote", SalesHeader);" to new method Stop
    end;

    procedure ShowSalesQuoteWithCheck()
    var
        SalesHeader: Record "Sales Header";
    begin
        [...]
        if not SalesHeader.Get(SalesHeader."Document Type"::Quote, "Sales Document No.") then
            Error(Text004, "Sales Document No.");
        //moved "PAGE.Run(PAGE::"Sales Quote", SalesHeader);" to new method Start
        RunSalesQuotePage(SalesHeader);
        //moved "PAGE.Run(PAGE::"Sales Quote", SalesHeader);" to new method Stop
    end;

    //new method
    local procedure RunSalesQuotePage(SalesHeader: Record "Sales Header")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeRunSalesQuotePage(SalesHeader, IsHandled);
        if IsHandled then
            exit;

        PAGE.Run(PAGE::"Sales Quote", SalesHeader);
    end;

    //new method
    local procedure RunModalSalesQuotePage(SalesHeader: Record "Sales Header")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeRunModalSalesQuotePage(SalesHeader, IsHandled);
        if IsHandled then
            exit;

        PAGE.RunModal(PAGE::"Sales Quote", SalesHeader);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52253.
