### ISSUE TITLE
[Event Request] Codeunit 10860 "Payment Management" update OnPostInvPostingBufferOnBeforeGenJnlPostLineRunWithCheck

### ISSUE THREAD

**Issue by DAGOISAnthony** [microsoft/ALAppExtensions#21345]
Hello,

Please add the variable InvPostingBuffer as parameter to the event OnPostInvPostingBufferOnBeforeGenJnlPostLineRunWithCheck On codeunit Payment Management. (French Localisation)

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10741.
