### ISSUE TITLE
[Event Request] Page 9996 "Word Template Selection Wizard".action(Finish)

### ISSUE THREAD

**Issue by adejsy** [microsoft/ALAppExtensions#21350]
The Word Templates functionality is really useful but it is quite limited for us to be able to extend it.

It would be very useful to have an integration event in this module that allows us to get to the stream of the created document. It looks like it is possible, but we can not seem to "grab" it. For example you might want to automatically push the document to a document management solution or have another prompt for a user before the page closes.

Ideally we need an integration event at the point shown below that would allow us to get to the stream. We could get to the Rec on the usual OnClosePage event, but this won't expose the stream for us. We need an event before the page closes so we can get the stream. The code has an option "AsStream" but how are developers meant to access this?

                trigger OnAction()
                var
                    WordTemplates: Codeunit "Word Template";
                    InStream: InStream;
                begin
                    WordTemplates.Load(Rec.Code);
                    WordTemplates.Merge(DataVariant, SplitDocuments, SaveFormat);
                    if AsDocumentStream then begin
                        DocumentDataTempBlob.CreateOutStream(DocumentOutStream);
                        WordTemplates.GetDocument(InStream);
                        CopyStream(DocumentOutStream, InStream);
                        ##------------------------------##
                        WE NEED AN INTEGRATION EVENT AT THIS POINT SO WE CAN GET THE STREAM
                        ##------------------------------##
                    end else
                        WordTemplates.DownloadDocument();

                    FinishedWizard := true;
                    CurrPage.Close();
                end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12557.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 12931.
