### ISSUE TITLE
Slow performance when running Aged payable

### ISSUE THREAD

**Issue by Rama-M** [microsoft/ALAppExtensions#21353]
Slow performance was observed when running Aged payable.  Tracing the slowness seems to be caused by a bad use of key in codeunit 764 "Aged Acc. Payable" in base application.  SETCURRENTKEY command in CalculateAgedAccPayable function needs to be changed to reflect the fields get filtered especially with a large table like "Vendor Ledger Entry" it will progressively slow.  So please fix this issue in the next release.  I am attaching the proposed code change below

local procedure CalculateAgedAccPayable(StartDate: Date; PeriodLength: Text[1]; NoOfPeriods: Integer; var TempEntryNoAmountBuffer: Record "Entry No. Amount Buffer" temporary)
    var
        VendLedgEntry: Record "Vendor Ledger Entry";
        RemainingAmountLCY: Decimal;
        EndDate: Date;
        Index: Integer;
    begin
        VendLedgEntry.Reset();

       //Old Code >>
        //VendLedgEntry.SetCurrentKey("Vendor No.", Open, Positive, "Due Date");
       //Old Code <<

       //New Code >>
        //VendLedgEntry.SetCurrentKey(Open,"Due Date");
       //New Code <<

        VendLedgEntry.SetRange(Open, true);
        VendLedgEntry.SetAutoCalcFields("Remaining Amt. (LCY)");

        for Index := 0 to NoOfPeriods - 1 do begin
            RemainingAmountLCY := 0;
            VendLedgEntry.SetFilter(
              "Due Date",
              DateFilterByAge(Index, StartDate, PeriodLength, NoOfPeriods, EndDate));
            if VendLedgEntry.FindSet() then
                repeat
                    RemainingAmountLCY += VendLedgEntry."Remaining Amt. (LCY)";
                until VendLedgEntry.Next() = 0;

            InsertAmountBuffer(Index, '', -RemainingAmountLCY, StartDate, EndDate, TempEntryNoAmountBuffer)
        end;
    end;

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot process performance related requests here, as it is not obvious how you suggestion will affect performance. Please create support request for fixing this report performance instead.
