### ISSUE TITLE
[Event Request] page 5805 "Item Charge Assignment (Purch)"

### ISSUE THREAD

**Issue by SynPaul** [microsoft/ALAppExtensions#21365]
Can we please request some new events on page 5805:

action(GetReceiptLines)
                {
                    AccessByPermission = TableData "Purch. Rcpt. Header" = R;
                    ApplicationArea = ItemCharges;
                    Caption = 'Get &Receipt Lines';
                    Image = Receipt;
                    ToolTip = 'Select a posted purchase receipt for the item that you want to assign the item charge to, for example, if you received an invoice for the item charge after you posted the original purchase receipt.';

                    trigger OnAction()
                    var
                        ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)";
                        ReceiptLines: Page "Purch. Receipt Lines";
                        //-BEGIN
                        IsHandled: Boolean;
                        //+END
                    begin
                        PurchLine2.TestField("Qty. to Invoice");

                        ItemChargeAssgntPurch.SetRange("Document Type", Rec."Document Type");
                        ItemChargeAssgntPurch.SetRange("Document No.", Rec."Document No.");
                        ItemChargeAssgntPurch.SetRange("Document Line No.", Rec."Document Line No.");
                        OnGetReceiptLinesOnActionOnAfterItemChargeAssgntPurchSetFilters(Rec, PurchRcptLine, PurchLine);
                        //-BEGIN
                        OnBeforeReceiptLinesRunModal(Rec, PurchRcptLine, ItemChargeAssgntPurch, PurchLine2, IsHandled);
                        if IsHandled then
                            exit;
                        //+END
                        ReceiptLines.SetTableView(PurchRcptLine);
                        if ItemChargeAssgntPurch.FindLast() then
                            ReceiptLines.Initialize(ItemChargeAssgntPurch, PurchLine2."Unit Cost")
                        else
                            ReceiptLines.Initialize(Rec, PurchLine2."Unit Cost");

                        ReceiptLines.LookupMode(true);
                        ReceiptLines.RunModal();
                    end;
                }
                action(GetTransferReceiptLines)
                {
                    AccessByPermission = TableData "Transfer Header" = R;
                    ApplicationArea = Location;
                    Caption = 'Get &Transfer Receipt Lines';
                    Image = TransferReceipt;
                    ToolTip = 'Select a posted transfer receipt for the item that you want to assign the item charge to, for example, if you received an invoice for the item charge after you posted the original transfer receipt.';

                    trigger OnAction()
                    var
                        ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)";
                        PostedTransferReceiptLines: Page "Posted Transfer Receipt Lines";
                        //-BEGIN
                        IsHandled: Boolean;
                        //+END
                    begin
                        ItemChargeAssgntPurch.SetRange("Document Type", Rec."Document Type");
                        ItemChargeAssgntPurch.SetRange("Document No.", Rec."Document No.");
                        ItemChargeAssgntPurch.SetRange("Document Line No.", Rec."Document Line No.");

                        TransferRcptLine.FilterGroup(2);
                        TransferRcptLine.SetFilter("Item No.", '<>%1', '');
                        TransferRcptLine.SetFilter(Quantity, '<>0');
                        TransferRcptLine.FilterGroup(0);
                        OnGetTransferReceiptLinesOnActionOnAfterItemChargeAssgntPurchSetFilters(Rec, TransferRcptLine, PurchLine);
                        //-BEGIN
                        OnBeforePostedTransferReceiptLinesRunModal(Rec, TransferRcptLine, ItemChargeAssgntPurch, PurchLine2, IsHandled);
                        if IsHandled then
                            exit;
                        //+END

                        PostedTransferReceiptLines.SetTableView(TransferRcptLine);
                        if ItemChargeAssgntPurch.FindLast() then
                            PostedTransferReceiptLines.Initialize(ItemChargeAssgntPurch, PurchLine2."Unit Cost")
                        else
                            PostedTransferReceiptLines.Initialize(Rec, PurchLine2."Unit Cost");

                        PostedTransferReceiptLines.LookupMode(true);
                        PostedTransferReceiptLines.RunModal();
                    end;
                }
                action(GetReturnShipmentLines)
                {
                    AccessByPermission = TableData "Return Shipment Header" = R;
                    ApplicationArea = SalesReturnOrder;
                    Caption = 'Get Return &Shipment Lines';
                    Image = ReturnShipment;
                    ToolTip = 'Select a posted return shipment for the item that you want to assign the item charge to, for example, if you received an invoice for the item charge after you posted the original return shipment.';

                    trigger OnAction()
                    var
                        ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)";
                        ShipmentLines: Page "Return Shipment Lines";
                        //-BEGIN
                        IsHandled: Boolean;
                        //+END
                    begin
                        ItemChargeAssgntPurch.SetRange("Document Type", Rec."Document Type");
                        ItemChargeAssgntPurch.SetRange("Document No.", Rec."Document No.");
                        ItemChargeAssgntPurch.SetRange("Document Line No.", Rec."Document Line No.");
                        OnGetReturnShipmentLinesOnActionOnAfterItemChargeAssgntPurchSetFilters(Rec, ReturnShptLine, PurchLine);
                        //-BEGIN
                        OnBeforeShipmentLinesRunModal(Rec, ReturnShptLine, ItemChargeAssgntPurch, PurchLine2, IsHandled);
                        if IsHandled then
                            exit;
                        //+END

                        ShipmentLines.SetTableView(ReturnShptLine);
                        if ItemChargeAssgntPurch.FindLast() then
                            ShipmentLines.Initialize(ItemChargeAssgntPurch, PurchLine2."Unit Cost")
                        else
                            ShipmentLines.Initialize(Rec, PurchLine2."Unit Cost");

                        ShipmentLines.LookupMode(true);
                        ShipmentLines.RunModal();
                    end;
                }
                action(GetSalesShipmentLines)
                {
                    AccessByPermission = TableData "Sales Shipment Header" = R;
                    ApplicationArea = Basic, Suite;
                    Caption = 'Get S&ales Shipment Lines';
                    Image = SalesShipment;
                    ToolTip = 'Select a posted sales shipment for the item that you want to assign the item charge to, for example, if you received an invoice for the item charge after you posted the original sales shipment.';

                    trigger OnAction()
                    var
                        ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)";
                        SalesShipmentLines: Page "Sales Shipment Lines";
                        //-BEGIN
                        IsHandled: Boolean;
                        //+END
                    begin
                        ItemChargeAssgntPurch.SetRange("Document Type", Rec."Document Type");
                        ItemChargeAssgntPurch.SetRange("Document No.", Rec."Document No.");
                        ItemChargeAssgntPurch.SetRange("Document Line No.", Rec."Document Line No.");
                        OnGetSalesShipmentLinesOnActionOnAfterItemChargeAssgntPurchSetFilters(Rec, SalesShptLine, PurchLine);
                        //-BEGIN
                        OnBeforeSalesShipmentLinesRunModal(Rec, SalesShptLine, ItemChargeAssgntPurch, PurchLine2, IsHandled);
                        if IsHandled then
                            exit;
                        //+END

                        SalesShipmentLines.SetTableView(SalesShptLine);
                        if ItemChargeAssgntPurch.FindLast() then
                            SalesShipmentLines.InitializePurchase(ItemChargeAssgntPurch, PurchLine2."Unit Cost")
                        else
                            SalesShipmentLines.InitializePurchase(Rec, PurchLine2."Unit Cost");

                        SalesShipmentLines.LookupMode(true);
                        SalesShipmentLines.RunModal();
                    end;
                }
                action(GetReturnReceiptLines)
                {
                    AccessByPermission = TableData "Return Receipt Header" = R;
                    ApplicationArea = PurchReturnOrder;
                    Caption = 'Get Ret&urn Receipt Lines';
                    Image = ReturnReceipt;
                    ToolTip = 'Select a posted return receipt for the item that you want to assign the item charge to, for example, if you received an invoice for the item charge after you posted the original return receipt.';

                    trigger OnAction()
                    var
                        ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)";
                        ReturnRcptLines: Page "Return Receipt Lines";
                        //-BEGIN
                        IsHandled: Boolean;
                        //+END
                    begin
                        ItemChargeAssgntPurch.SetRange("Document Type", "Document Type");
                        ItemChargeAssgntPurch.SetRange("Document No.", "Document No.");
                        ItemChargeAssgntPurch.SetRange("Document Line No.", "Document Line No.");
                        OnGetReturnReceiptLinesOnActionOnAfterItemChargeAssgntPurchSetFilters(Rec, ReturnRcptLine, PurchLine);
                        //-BEGIN
                        OnBeforeReturnRcptLinesRunModal(Rec, ReturnRcptLine, ItemChargeAssgntPurch, PurchLine2, IsHandled);
                        if IsHandled then
                            exit;
                        //+END

                        ReturnRcptLines.SetTableView(ReturnRcptLine);
                        if ItemChargeAssgntPurch.FindLast() then
                            ReturnRcptLines.InitializePurchase(ItemChargeAssgntPurch, PurchLine2."Unit Cost")
                        else
                            ReturnRcptLines.InitializePurchase(Rec, PurchLine2."Unit Cost");

                        ReturnRcptLines.LookupMode(true);
                        ReturnRcptLines.RunModal();
                    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeReceiptLinesRunModal(var Rec: Record "Item Charge Assignment (Purch)"; var PurchRcptLine: Record "Purch. Rcpt. Line"; var ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)"; var PurchLine2: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostedTransferReceiptLinesRunModal(var Rec: Record "Item Charge Assignment (Purch)"; var TransferRcptLine: Record "Transfer Receipt Line"; var ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)"; var PurchLine2: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeShipmentLinesRunModal(var Rec: Record "Item Charge Assignment (Purch)"; var ReturnShptLine: Record "Return Shipment Line"; var ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)"; var PurchLine2: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesShipmentLinesRunModal(var Rec: Record "Item Charge Assignment (Purch)"; var SalesShptLine: Record "Sales Shipment Line"; var ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)"; var PurchLine2: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeReturnRcptLinesRunModal(var Rec: Record "Item Charge Assignment (Purch)"; var ReturnRcptLine: Record "Return Receipt Line"; var ItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)"; var PurchLine2: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10481.
