### ISSUE TITLE
SETCURRENTKEY missing when validating Description Field in Sales Line

### ISSUE THREAD

**Issue by Rama-M** [microsoft/ALAppExtensions#21364]
There is SETCURRENTKEY command is missing OnValidate of Description Field in sales line.  The code is fetching records from Item table and we have noticed this validation is slow due to lack of SETCURRENTKEY command.  This will hurt performance especially when there are a lot of item records.  So please apply the suggested fix in the base application (see below).

case Type of
                    Type::Item:
                        begin
                            if StrLen(Description) <= MaxStrLen(Item."No.") then
                                DescriptionIsNo := Item.Get(Description)
                            else
                                DescriptionIsNo := false;

                            if not DescriptionIsNo then begin
                                Item.SetRange(Blocked, false);
                                if not IsCreditDocType() then
                                    Item.SetRange("Sales Blocked", false);

                                // looking for an item with exact description

				//New Code >>
				Item.Setcurrentkey(Description);
				//New Code <<

                                Item.SetRange(Description, Description);
                                if Item.FindFirst() then begin
                                    Validate("No.", Item."No.");
                                    exit;
                                end;

                                // looking for an item with similar description
                                Item.SetFilter(Description, '''@' + ConvertStr(Description, '''', '?') + '''');
                                if Item.FindFirst() then begin

**Comment by RadoArvay** [comment]
Are you sure SQL Server does not use the SQL index for this retrieving of records anyway? Did you check, for example, database statistics during debugging? SetCurrentKey statement is not needed in every case to tell SQL Server to use a particular index.

**Comment by Rama-M** [comment]
Yes I have checked the SQL side and execution plan etc...  I can clearly see a table scan on Item table.  This is due to the the mis match of WHERE clause and ORDER BY clause.  Please note NAV/BC does issue ORDER BY clause for commands like all the FIND commands and other data retrievals such as when a page is ran.  So need a SETCURRENTKEY command to match the SETRANGE/SETFILTER commands.

It is a very common myth that we so not need to use SETCURRENTKEY command in NAV/BC.  The truth is you do for better performance.  Your suggestion is only true if NAV/BC stop issuing ORDER BY clause.  Which is not the case anyway for most of the cases.  Please note if a SETCURRENTKEY command is missing the primary key will be used for the ORDER BY clause.

**Comment by RadoArvay** [comment]
Yes, I am aware of that. But SQL Server can decide to retrieve records by the index and do sorting after that. So, no index hint in the sql statement, ok then.

**Comment by RadoArvay** [comment]
I think, there is a misunderstanding. There was not a request from Rama-M to create a new key but to use it. "Description" is already in an existing key.
