### ISSUE TITLE
[Event Request] - Change signature of event OnBeforeLockTables in Codeunit 90 "Purch.-Post"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21377]
Please, cosinder changin the signature of event "OnBeforeLockTables " in Codeunit 90 "Purch.-Post", from:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeLockTables(var PurchHeader: Record "Purchase Header"; PreviewMode: Boolean; CommitIsSuppressed: Boolean)
    begin
    end;
```

to:

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeLockTables(var PurchHeader: Record "Purchase Header"; PreviewMode: Boolean; CommitIsSuppressed: Boolean**; var IsHandled: Boolean**)
    begin
    end;
```

and the behaviour to call it inside the "LockTables" procedure:

    local procedure LockTables(var PurchHeader: Record "Purchase Header")
    var
        PurchLine: Record "Purchase Line";
        SalesLine: Record "Sales Line";
        InvSetup: Record "Inventory Setup";

        **IsHandled: Boolean;**
    begin
        **OnBeforeLockTables(PurchHeader, PreviewMode, SuppressCommit, IsHandled);
        If Ishandled then
            exit;**

        PurchLine.LockTable();
        SalesLine.LockTable();
        if not InvSetup.OptimGLEntLockForMultiuserEnv() then begin
            GLEntry.LockTable();
            if GLEntry.FindLast() then;
        end;
    end;

Thank you !

**Comment by AlexanderYakunin** [comment]
Please explain why do you want to skip locking?

**Comment by oldmat** [comment]
Because for certain contexts blocking sales when posting a purchase is not necessary. For instance a customer who doesn't use drop shipping or similar. 
Or why blocking GLEntries when posting sipments/receipts ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53591.
