### ISSUE TITLE
OnBeforeFinitelyLoadCapForward

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#21376]
codeunit calculate routing line
event OnBeforeFinitelyLoadCapForward

could it possible to have the same event parameters as in the
OnBeforeFinitelyLoadCapBackward event?
that event contains more parameters than the forward one.

**Comment by AlexanderYakunin** [comment]
Can you provide object name at least?

**Comment by bartpattijn** [comment]
See first line
Codeunit calculate routing line

**Comment by bartpattijn** [comment]
Any update on this?

**Comment by AlexanderYakunin** [comment]
We have long list of events to implement, it takes time

**Comment by bartpattijn** [comment]
No problem, main thing I need to know if it will be implemented. Otherwise we need to look for other solution, which would probably mean duplicating a lot of code.
