### ISSUE TITLE
[Remove Scope Request] table 11401 "CBG Statement Line" - "New Applies-to ID"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#21387]
NL localization issue:

In multiple PTE apps we are using procedure "New Applies-to ID":

    [Scope('OnPrem')]
    procedure "New Applies-to ID"() ID: Code[20]

Is it possible to remove scope OnPrem?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51059.
