### ISSUE TITLE
[Event Request] Codeunit 10750 "SII XML Creator" add two parameters to the event "OnPopulateXMLWithPurchInvoiceOnBeforeDesgloseFacturaNode".

### ISSUE THREAD

**Issue by JB92ARB** [microsoft/ALAppExtensions#21381]
Hello,

I need to add two more parameters to the event "OnPopulateXMLWithPurchInvoiceOnBeforeDesgloseFacturaNode":

The parameters are from the PopulateXMLWithPurchInvoice procedure:
TempVATEntryReverseChargeCalculated
TempVATEntryNormalCalculated
![image](https://user-images.githubusercontent.com/86236240/206921176-22c31b0b-9bdb-4e79-86d8-3c79a6eab2ec.png)

Thank you very much, best regards.

**Comment by JB92ARB** [comment]
![image](https://user-images.githubusercontent.com/86236240/206921243-f0f9c82e-8e62-4e21-a1b9-ab9033207d1a.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53246.
