### ISSUE TITLE
Report Result Incorrect : Item Age Composition - Value

### ISSUE THREAD

**Issue by BrianAPC** [microsoft/ALAppExtensions#21389]
Please include the following with each issue:

**1. Describe the bug**
When Running Report "Item Age Composition - Value", the value for specific time period is not showing correctly.

**2. To Reproduce**

1. Run report "Item Age Composition - Value"
2. enter the ending date which is within the period
3. The Value shows 0 while Value Entry do have Value.

**Note:** Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.

**3. Expected behavior**
Value Entry Result for specific Item:
![image](https://user-images.githubusercontent.com/102269776/206159934-58906559-3b26-411b-bfc8-6225ec2b0aaf.png)

Report Request Page Input:
![image](https://user-images.githubusercontent.com/102269776/206154008-b15a66d9-7ee9-4b31-a04d-061d9a1270bd.png)

This Value shows correct value as Value Entry Calculated result:
![image](https://user-images.githubusercontent.com/102269776/206159813-b16959b3-0351-43f0-85cb-6a4402eab108.png)

**4. Actual behavior**
Value Entry Result for specific Item:
![image](https://user-images.githubusercontent.com/102269776/206159946-a459f3c4-c2f0-46b8-b9ec-c4545fc2f565.png)

Report Request Page Input:
![image](https://user-images.githubusercontent.com/102269776/206155188-41498660-f9e7-497e-aa8d-f2f1df66b145.png)

This Value shows Incorrect value, but the ending date is still in the date period:
![image](https://user-images.githubusercontent.com/102269776/206160099-120a5a50-fba5-43b5-9ab6-61983a61d0ca.png)

**5. Versions:**

- AL Language: v10.2.719883
- Visual Studio Code: 1.73.1
- Business Central: v21.0.46256.46853
- List of Visual Studio Code extensions that you have installed: AL Language

### Final Checklist

Please remember to do the following:

* [x] Search the issue repository to ensure you are reporting a new issue

* [x] Reproduce the issue after disabling all extensions except the AL Language extension

* [x] Simplify your code around the issue to better isolate the problem

**Comment by AlexanderYakunin** [comment]
Sorry, we are not processing bug here, you should create support request for hotfix.
