### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnSetQtyToHandleAndInvoiceOnAfterSetQtyToHandleAndInvoiceOnFirstReservationEntry

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#21385]
Fourth time's the charm this case:
I requested something similar a year ago
https://github.com/microsoft/ALAppExtensions/issues/13465
then
https://github.com/microsoft/ALAppExtensions/issues/19091
then
https://github.com/microsoft/ALAppExtensions/issues/21133

When I asked the first time for OnAfterSetQtyToHandleAndInvoiceOnBeforeReservEntryModify it was not a problem that I asked for a 'breaking' change and it was implemented without any hesitation but it was forgottten to implement it in this particular place for a second time as was already done before me with event OnSetQtyToHandleAndInvoiceOnBeforeReservEntryModify. So I guess rules have changed. It doesn't matter we just keep asking again and make it slightly different.

Please can you create a new event OnSetQtyToHandleAndInvoiceOnAfterSetQtyToHandleAndInvoiceOnFirstReservationEntry (or any other name MS seems fit) in the following code:

    local procedure SetQtyToHandleAndInvoice(TrackingSpecification: Record "Tracking Specification")
        ...
        end else
            //if ReservEntry1.Find('-') then A109F0006.Event20.02.o
            if ReservEntry1.FindFirst() then begin //A109F0006.Event20.02.n
                if (ReservEntry1."Qty. to Handle (Base)" <> TotalQtyToHandle) or
                   (ReservEntry1."Qty. to Invoice (Base)" <> TotalQtyToInvoice) and not ReservEntry1.Correction
                then begin
                    ReservEntry1."Qty. to Handle (Base)" := TotalQtyToHandle;
                    ReservEntry1."Qty. to Invoice (Base)" := TotalQtyToInvoice;
                    OnSetQtyToHandleAndInvoiceOnBeforeReservEntryModify(ReservEntry1, TrackingSpecification);
                    ReservEntry1.Modify();
                end;
                //A200F0000.Event20.02.ns
                OnSetQtyToHandleAndInvoiceOnAfterSetQtyToHandleAndInvoiceOnFirstReservationEntry(ReservEntry1, TrackingSpecification, TotalTrackingSpecification);
            end;
        //A200F0000.Event20.02.ne
    end;

    [IntegrationEvent(false, false)]
    local procedure OnSetQtyToHandleAndInvoiceOnAfterSetQtyToHandleAndInvoiceOnFirstReservationEntry(var ReservEntry: Record "Reservation Entry"; var TrackingSpecification: Record "Tracking Specification"; var TotalTrackingSpecification: Record "Tracking Specification")
    begin
        //A109F0006.Event21.02
    end;

![image_8](https://user-images.githubusercontent.com/30273162/206996800-49c68e9c-b1a0-4145-87e0-6515d9fdda21.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52253.
