### ISSUE TITLE
Missing Change in Code for Issue 20015

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#21396]
I checked the latest available code for BC 21.2, but the requested change of issue isn't available there.

https://github.com/microsoft/ALAppExtensions/issues/20015

The issue was update on september therefore I would expted that this change is availbe in at least BC 21.2

**Comment by AlexanderYakunin** [comment]
As you have requested this change AFTER code freeze for 21.0, this change is available in 22.x only.
