### ISSUE TITLE
[Access Request] report 1305 "Standard Sales - Order Conf."

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#21392]
Could you please change the Access scope of the following variables to proteced 
```al
    protected var
        FirstLineHasBeenOutput: Boolan;
        LogInteraction: Boolean;
        ArchiveDocument: Boolean;
        DisplayAssemblyInformation: Boolean;
        TotalExclVATText: Text[50];
        TotalInclVATText: Text[50];
        TotalText: Text[50];
        CurrCode: Text[10];
        CurrSymbol: Text[10];
        FormattedLineAmount: Text;
        FormattedQuantity: Text;
        FormattedUnitPrice: Text;
        FormattedVATPct: Text;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51059.
