### ISSUE TITLE
Missing fields when creating orders from quotations with the "Create Order" function, which do not have a customer.

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/ALAppExtensions#214]
If you create a new order using the "Create Order" function and there was no customer in the original quotation, the system asks whether a new customer is created. If you confirm this with Yes, a new customer number is created from existing templates and then the new customer number is entered for all existing quotations. This works via Table 5050 in the "UpdateQuotes" function. However, several problems can arise here. The "Sell-To Customer No." and "Bill-To Customer No." are inserted but not validated. As a result, some fields in the sales header are not updated, such as the "Invoice Disc. Code". This exists in the newly created customer, but not in the original quote, and then not in the newly created sales order. This can have fatal consequences in postprocessing if some fields are not validated and information is simply missing. The error affects not only the current Business Central version, but also all NAV versions that are still supported. Here, too, a correction should be made.

**Comment by RomanZanizdra** [comment]
There are two new events provided.
OnAfterModifySellToCustomerNo(VAR SalesHeader : Record "Sales Header";VAR SalesLine : Record "Sales Line")
OnAfterModifyBillToCustomerNo(VAR SalesHeader : Record "Sales Header";VAR SalesLine : Record "Sales Line")
