### ISSUE TITLE
[Event Request] codeunit 13 "ProcessLines" - OnBeforeCheckLine

### ISSUE THREAD

**Issue by matteodelgatto** [microsoft/ALAppExtensions#21409]
Hi,
we need a new event on codeunit 13 "Gen. Jnl.-Post Batch", procedure ProcessLines()
We suggest to add the event OnBeforeCheckLine as shown in the example in order to manage the variable PostingAfterWorkingDateConfirmed without using MyNotifications

local procedure ProcessLines(var GenJnlLine: Record "Gen. Journal Line")
    var
        TempGenJnlLine: Record "Gen. Journal Line" temporary;
        GenJnlLineVATInfoSource: Record "Gen. Journal Line";
        UpdateAnalysisView: Codeunit "Update Analysis View";
        ICOutboxExport: Codeunit "IC Outbox Export";
        TypeHelper: Codeunit "Type Helper";
        ErrorContextElement: Codeunit "Error Context Element";
        ErrorMessageMgt: Codeunit "Error Message Management";
        RecRef: RecordRef;
        ICLastDocNo: Code[20];
        CurrentICPartner: Code[20];
        LastLineNo: Integer;
        LastICTransactionNo: Integer;
        ICTransactionNo: Integer;
        ICLastDocType: Enum "Gen. Journal Document Type";
        ICLastDate: Date;
        VATInfoSourceLineIsInserted: Boolean;
        SkippedLine: Boolean;
        PostingAfterWorkingDateConfirmed: Boolean;
        IsHandled: Boolean;
    begin
    ...

            // Check lines
            LineCount := 0;
            StartLineNo := "Line No.";
            NoOfRecords := CountGenJournalLines(GenJnlLine);
            GenJnlCheckLine.SetBatchMode(true);
            repeat
                LineCount := LineCount + 1;
                UpdateDialog(RefPostingState::"Checking lines", LineCount, NoOfRecords);

                OnBeforeCheckLine(GenJnlLine, PostingAfterWorkingDateConfirmed);

                CheckLine(GenJnlLine, PostingAfterWorkingDateConfirmed);
                TempGenJnlLine := GenJnlLine5;
                TempGenJnlLine.Insert();
                if Next() = 0 then
                    FindFirst();
            until "Line No." = StartLineNo;
    ...
    end;

[IntegrationEvent(false,false)]
local procedure OnBeforeCheckLine(var GenJnlLine: Record "Gen. Journal Line"; var PostingAfterWorkingDateConfirmed: Boolean)
begin
end;

Thank You

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52570.
