### ISSUE TITLE
[Protected var] IsNewOutbox on "Email Editor" page

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#21400]
One of our customers / developers is facing serious delays when **sending** emails via the **'Email Editor'**. When clicking the 'Send' action, the 'Email editor' page is frozen for minutes, keeping the user from continuing their normal tasks. We're still troubleshooting the source of the delays, but were looking into possible alternatives.

One of the ideas was not to 'Send' emails when closing the 'Email Editor', but to '**Enqueue**' emails for sending. This would send the email via a background task instead and allow the user to continue.

Currently the InBackground option is not supported when sending "Email Outbox" records via the "Email Editor"

_EmailEditor.SendOutbox > EmailImpl.Send > InBackground = false._

Instead, we would add an 'Enqueue' action to Enqueue the email and close the page. However, when closing the page, we get the CloseOptionsMenu, which is not wanted.

```
pageextension 50000 "TTT EmailEditor" extends "Email Editor"   //13
{
    actions
    {
        addafter(Send)
        {
            action(TTTEnqueue)
            {
                Promoted = true;
                PromotedOnly = true;
                PromotedCategory = Process;
                Caption = 'Enqueue Email';
                ApplicationArea = All;
                Image = SendMail;

                trigger OnAction()
                var
                    EmailMessage: Codeunit "Email Message";
                    Email: Codeunit Email;
                    MessageID: Guid;
                begin
                    MessageID := GetMessageId();
                    EmailMessage.Get(MessageId);
                    Email.Enqueue(EmailMessage);
                    IsNewOutbox := false;  /// << this is blocking us ...
                    CurrPage.Close();
                end;
            }
        }
    }
}
```

To overcome the issue, we would like to get access to the `IsNewOutbox` variable. (by moving it into the **protected** var section)

This customer is running BC 20.x OnPrem, so if a solution is provided, can you please backport this to the next BC 20 cumulative update?

@JesperSchulz Any other alternatives are welcomed too ;)

**Comment by fvet** [comment]
Related idea
https://experience.dynamics.com/ideas/idea/?ideaid=0be9edb8-d870-ed11-a76e-0003ff45ac6d

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51281.
