### ISSUE TITLE
page 490 "Acc. Schedule Overview" readd "CurrentSchedName"

### ISSUE THREAD

**Issue by jorland1** [microsoft/ALAppExtensions#21410]
Hi,
could you please readd the global variable `CurrentSchedName` as protected, analogous to how `CurrentColumnName` is implemented now?
We need this variable in a page extension and couldn't find another way to get it that wouldn't require a ton of new events. 
If there is an easier way to access this value we have overlooked, then please let us know.
Thanks.

**Comment by AlexanderYakunin** [comment]
Which version we are asking for?

**Comment by jorland1** [comment]
We need this for BC21 if possible.

**Comment by AlexanderYakunin** [comment]
There is no global variable CurrentSchedName in this page in v.21. Instead there is protected variable FinancialReportCode: Code[10], which has the same purpose. Can you review and close this request if not needed anymore.

**Comment by jorland1** [comment]
Yes, that did the trick. Thanks for your help.
