### ISSUE TITLE
Update to OnBeforePrint publisher in Page 490 "Acc. Schedule Overview" to pass in TempFinancialReport record instead of just TempFinancialReport."Financial Report Column Group" so the values populated on the page in TempFinancialReport record can be used.

### ISSUE THREAD

**Issue by Zaynil** [microsoft/ALAppExtensions#21412]
`action(Print)

            {

                ApplicationArea = Basic, Suite;

                Caption = 'Print';

                Ellipsis = true;

                Image = Print;

                ToolTip = 'Print the information in the window. A print request window opens where you can specify what to include on the print-out.';

                trigger OnAction()

                var

                    AccSched: Report "Account Schedule";

                    DateFilter2: Text;

                    GLBudgetFilter2: Text;

                    BusUnitFilter: Text;

                    CostBudgetFilter2: Text;

                    IsHandled: Boolean;

                begin

                    IsHandled := false;

                    **OnBeforePrint(Rec, TempFinancialReport."Financial Report Column Group", IsHandled); //CURRENT CODE
                    OnBeforePrint(Rec, TempFinancialReport, IsHandled); //NEW CODE**
                    if IsHandled then

                        exit;

                    if TempFinancialReport.Name <> '' then

                        AccSched.SetFinancialReportName(TempFinancialReport.Name)

                    else begin

                        AccSched.SetAccSchedName(TempFinancialReport."Financial Report Row Group");

                        AccSched.SetColumnLayoutName(TempFinancialReport."Financial Report Column Group");

                    end;

                    DateFilter2 := Rec.GetFilter("Date Filter");

                    GLBudgetFilter2 := Rec.GetFilter("G/L Budget Filter");

                    CostBudgetFilter2 := Rec.GetFilter("Cost Budget Filter");

                    BusUnitFilter := Rec.GetFilter("Business Unit Filter");

                    AccSched.SetFilters(DateFilter2, GLBudgetFilter2, CostBudgetFilter2, BusUnitFilter, TempFinancialReport.Dim1Filter, TempFinancialReport.Dim2Filter, TempFinancialReport.Dim3Filter, TempFinancialReport.Dim4Filter, TempFinancialReport.CashFlowFilter);

                    AccSched.Run();

                end;

            }`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51150.
