### ISSUE TITLE
Codeunit 99000845 Reservation Management - Event Request

### ISSUE THREAD

**Issue by NavDeb** [microsoft/ALAppExtensions#21423]
Please could I request following publisher:-

    [IntegrationEvent(false, false)]
    local procedure OnProcessValueArray(var CalcReservEntry: Record "Reservation Entry"; var ReservSummEntry: Record "Entry Summary"; var TotalQuantity: Decimal; HandleItemTracking2: Boolean; AvailabilityDate: Date; var QtyOnOutBound: Decimal)
    begin
    end;

added to the UpdateStatistics function within the CASE statement in Reservation Management codeunit please:-

            case ValueArray[i] of
                "Reservation Summary Type"::"Item Ledger Entry".AsInteger():
                    UpdateItemLedgEntryStats(CalcReservEntry, TempEntrySummary, TotalQuantity, HandleItemTracking2);
                "Reservation Summary Type"::"Item Tracking Line".AsInteger():
                    UpdateItemTrackingLineStats(CalcReservEntry, TempEntrySummary, AvailabilityDate);

                ****OnProcessValueArray(CalcReservEntry, TempEntrySummary, TotalQuantity, HandleItemTracking2, AvailabilityDate,** QtyOnOutBound);**
            end;

            OnUpdateStatistics(CalcReservEntry, TempEntrySummary, AvailabilityDate, Positive, TotalQuantity);
        end;

        OnAfterUpdateStatistics(TempEntrySummary, AvailabilityDate, TotalQuantity);

        if not TempEntrySummary.Get(CurrentEntryNo) then
            if TempEntrySummary.IsEmpty() then
                Clear(TempEntrySummary);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.
