### ISSUE TITLE
[Event Request]  table 210 "Job Journal Line" - OnBeforeRetrieveCostPrice ( parameters by Var

### ISSUE THREAD

**Issue by aconcato** [microsoft/ALAppExtensions#21426]
Current...

    [IntegrationEvent(false, false)]
    local procedure OnBeforeRetrieveCostPrice(JobJournalLine: Record "Job Journal Line"; xJobJournalLine: Record "Job Journal Line"; var ShouldRetrieveCostPrice: Boolean; var Result: Boolean; CalledByFieldNo: Integer)
    begin
    end;

   Suggested...

    [IntegrationEvent(false, false)]
    local procedure OnBeforeRetrieveCostPrice(var JobJournalLine: Record "Job Journal Line";var xJobJournalLine: Record "Job Journal Line"; var ShouldRetrieveCostPrice: Boolean; var Result: Boolean; CalledByFieldNo: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52136.
