### ISSUE TITLE
report 1322 "Standard Purchase - Order"

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#21433]
Could you please change the access scope of the following variables to protected?
```
        TempVATAmountLine: Record "VAT Amount Line" temporary;
        TempPrepmtVATAmountLine: Record "VAT Amount Line" temporary;
        TempPrepaymentInvLineBuffer: Record "Prepayment Inv. Line Buffer" temporary;
        TempPrePmtVATAmountLineDeduct: Record "VAT Amount Line" temporary;
        VendAddr: array[8] of Text[100];
        ShipToAddr: array[8] of Text[100];
        PurchaserText: Text[50];
        TotalText: Text[50];
        TotalInclVATText: Text[50];
        TotalExclVATText: Text[50];
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51200.
