### ISSUE TITLE
report 1308 "Standard Sales - Shipment"

### ISSUE THREAD

**Issue by samra-singhammer** [microsoft/ALAppExtensions#21437]
Could you please change the access scope of the following variables to protected?
```
        ShipToAddr: array[8] of Text[100];
        SalesPersonText: Text[50];
        ShowCustAddr: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51200.
