### ISSUE TITLE
[Event Request] Codeunit 8612- Config. Template Management - procedure TestKeyFields

### ISSUE THREAD

**Issue by lv-janpieter** [microsoft/ALAppExtensions#21439]
We have problems with the check on empty key fields. Somtimes this is allowed. We would be helped if we can make our implementation of this function. Can we have an OnBeforeTestKeyFields publisher which includes a handled pattern?

Also we would like the configuration template header, which currently is not part of the parameters however this is easy to add.

Many thanks

```
    local procedure TestKeyFields(**ConfigTemplateHeader: Record "Config. Template Header"**, var RecRef: RecordRef): Boolean
    var
        FieldRef: FieldRef;
        KeyRef: KeyRef;
        KeyFieldCount: Integer;
        IsHandled: Boolean;
        ResultValue: Boolean;
    begin
        // --> start requested code
        OnBeforeTestKeyFields(ConfigTemplateHeader: Record "Config. Template Header", VAR RecRef: RecordRef, VAR IsHandled: Boolean, VAR ResultValue: Boolean);
        if IsHandled then
            exit(ResultValue);
        // --> end requested code
        KeyRef := RecRef.KeyIndex(1);
        for KeyFieldCount := 1 to KeyRef.FieldCount do begin
            FieldRef := KeyRef.FieldIndex(KeyFieldCount);
            if Format(FieldRef.Value) = '' then
                exit(false);
        end;
        exit(true);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52544.
