### ISSUE TITLE
[Event Request] - OnBeforePerformChecksOnPostGenJnlLineCodeunit 1001 "Job Post-Line"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21448]
Hello, please consider adding the following event to Codeunit 1001 "Job Post-Line"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforePerformChecksOnPostGenJnlLine(var GenJnlLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; var IsHandled: Boolean)
    begin
    end;
```

and call it accordingly inside the "PostGenJnlLine" procedure:

```
    procedure PostGenJnlLine(GenJnlLine: Record "Gen. Journal Line"; GLEntry: Record "G/L Entry")
    var
        JobJnlLine: Record "Job Journal Line";
        Job: Record Job;
        JobTask: Record "Job Task";
        SourceCodeSetup: Record "Source Code Setup";
        JobTransferLine: Codeunit "Job Transfer Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePostGenJnlLine(JobJnlLine, GenJnlLine, GLEntry, IsHandled);
        if IsHandled then
            exit;

        **IsHandled := false;
        OnBeforePerformChecksOnPostGenJnlLine(GenJnlLine, GLEntry, IsHandled);
        if not IsHandled then begin**

            if GenJnlLine."System-Created Entry" then
                exit;
            if GenJnlLine."Job No." = '' then
                exit;
            SourceCodeSetup.Get();
            if GenJnlLine."Source Code" = SourceCodeSetup."Job G/L WIP" then
                exit;
            GenJnlLine.TestField("Job Task No.");
            GenJnlLine.TestField("Job Quantity");
            Job.LockTable();
            JobTask.LockTable();
            Job.Get(GenJnlLine."Job No.");
            GenJnlLine.TestField("Job Currency Code", Job."Currency Code");

            JobTask.Get(GenJnlLine."Job No.", GenJnlLine."Job Task No.");
            JobTask.TestField("Job Task Type", JobTask."Job Task Type"::Posting);

        **end;**

        JobTransferLine.FromGenJnlLineToJnlLine(GenJnlLine, JobJnlLine);
        OnPostGenJnlLineOnAfterTransferToJnlLine(JobJnlLine, GenJnlLine, JobJnlPostLine);

        JobJnlPostLine.SetGLEntryNo(GLEntry."Entry No.");
        JobJnlPostLine.RunWithCheck(JobJnlLine);
        JobJnlPostLine.SetGLEntryNo(0);
    end;
```

Thank you !

**Comment by oldmat** [comment]
Hi,

well, the event you're suggesting forces me to rewrite the entire "PostGenJnlLine" procedure, included the job posting block at the end of it:

        JobJnlPostLine.SetGLEntryNo(GLEntry."Entry No.");
        JobJnlPostLine.RunWithCheck(JobJnlLine);
        JobJnlPostLine.SetGLEntryNo(0);

I just need to avoid only the first part of the procedure, until the

JobTask.TestField("Job Task Type", JobTask."Job Task Type"::Posting);

line included.

The problem of rewriting the entire procedure is that from inside my extension i can not use the same "JobJnlPostLine" codeunit variable, and i have to instantiate a new one, creating a new "transaction" (applicative, not technical).

Otherwise i should ask you to change the signature of the "OnBeforePostGenJnlLine" event, adding the "JobJnlPostLine" variable by reference (var).

Do you think it's possible ?


Da: Vadim Stepanenko ***@***.***>
Inviato: mercoledì 18 gennaio 2023 10:02
A: microsoft/ALAppExtensions ***@***.***>
Cc: oldmat ***@***.***>; Author ***@***.***>
Oggetto: Re: [microsoft/ALAppExtensions] [Event Request] - OnBeforePerformChecksOnPostGenJnlLineCodeunit 1001 "Job Post-Line" (Issue #21448)


Can you use OnBeforePostGenJnlLine instead?

-

**Comment by Vadim-Stepanenko** [comment]
> Otherwise i should ask you to change the signature of the "OnBeforePostGenJnlLine" event, adding the "JobJnlPostLine" variable by reference (var).
Do you think it's possible ?
We will do that.
