### ISSUE TITLE
[Event Request] - OnBeforeGetServiceHeaderPageID Codeunit 700 "Page Management"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21445]
Hello, please consider adding the following event to Codeunit 700 "Page Management"

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetServiceHeaderPageID (var RecRef: RecordRef; var ServiceHeader: Record "Service Header"; var IsHandled: Boolean; var ResultID: Integer)
    begin
    end;

and call it accordingly inside the "GetServiceHeaderPageID" procedure:

    local procedure GetServiceHeaderPageID(RecRef: RecordRef): Integer
    var
        ServiceHeader: Record "Service Header";

        **IsHandled: Boolean;
           ResultID: Integer**

    begin

        **IsHandled := false;
        OnBeforeGetServiceHeaderPageID(RecRef, ServiceHeader, IsHandled, ResultID);
        if IsHandled then
            exit(ResultID);**

        RecRef.SetTable(ServiceHeader);
        case ServiceHeader."Document Type" of
            ServiceHeader."Document Type"::Quote:
                exit(PAGE::"Service Quote");
            ServiceHeader."Document Type"::Order:
                exit(PAGE::"Service Order");
            ServiceHeader."Document Type"::Invoice:
                exit(PAGE::"Service Invoice");
            ServiceHeader."Document Type"::"Credit Memo":
                exit(PAGE::"Service Credit Memo");
        end;
    end;
Thank you !

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52570.
