### ISSUE TITLE
[Event Request]Fault/Resol. Cod. Relationship page 5930 procedure UpdateOrginalRecord

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#21442]
![image](https://user-images.githubusercontent.com/49729094/208145625-5a7ff80e-e6d1-4c15-95d8-2db8c741ea61.png)

(1) Between line 215 and 216, please add an event so we can modify more customized field
There is a spelling error on 'Original'.  Should we keep the wrong spelling or correct it?  
OnUpdateOriginalRecordOnBeforeServitemLineModify(Rec, ServItemLine)

 [IntegrationEvent(false, false)]
    local procedure OnUpdateOriginalRecordOnBeforeServitemLineModif(FaultResolCodRel: Record "Fault/Resol. Cod. Relationship"; var ServItemLine:Record "Service Item Line")
    begin
    end;

(2) Between line 224 and 225, please add an event so we can modify more customized field
OnUpdateOriginalRecordOnBeforeServiInvineModify(Rec, ServInvLine)

 [IntegrationEvent(false, false)]
    local procedure OnUpdateOriginalRecordOnBeforeServInvLineModif(FaultResolCodRel: Record "Fault/Resol. Cod. Relationship"; var ServLine:Record "Service Line")
    begin
    end;

Thanks very much.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52511.
