### ISSUE TITLE
Data Archive extension has wrong dependencies

### ISSUE THREAD

**Issue by RonKopp** [microsoft/ALAppExtensions#21453]
Within our embed app solution we tried to publish the extension "Data archive". Which failed with following error:
**_Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Base Application', and a version compatible with '21.2.0.0' could not be loaded. Symbols for the requested app Base Application by Microsoft 21.2.0.0 could not be found in the database._**

Root cause of this is because the extension takes a direct dependency on the Microsoft Base Application. Which is not okay. It should use the application property instead.

"dependencies":  [
                         {
                             "id":  "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
                             "name":  "System Application",
                             "publisher":  "Microsoft",
                             "version":  "21.3.0.0"
                         },
                         {
                             "id":  "437dbf0e-84ff-417a-965d-ed2bb9650972",
                             "name":  "Base Application",
                             "publisher":  "Microsoft",
                             "version":  "21.3.0.0"
                         }
                     ],

**Comment by RonKopp** [comment]
Any ETA on this item?

**Comment by JesperSchulz** [comment]
Sorry for the delay on this one. I'll get it fixed right away.

**Comment by JesperSchulz** [comment]
It will ship with upcoming minor 21.4.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 52287.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52288.
