### ISSUE TITLE
[Event Change Request] report 1322 "Standard Purchase - Order" OnAfterFormatDocumentFields

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#21452]
Could you please change the event `OnAfterFormatDocumentFields` to include the sender?
```al
//+Change
//-[IntegrationEvent(false, false)]
[IntegrationEvent(true, false)]
//-Change
local procedure OnAfterFormatDocumentFields(var PurchaseHeader: Record "Purchase Header")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.
