### ISSUE TITLE
[Event Request] codeunit 1605 "PEPPOL Management" - OnAfterGetPaymentMeansInfo

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#21454]
Can you add OnAfterGetPaymentMeansInfo to procedure GetPaymentMeansInfo?

OnGetPaymentMeansInfo(SalesHeader, PaymentMeansCode, PaymentMeansListID, PaymentDueDate, PaymentChannelCode, PaymentID, PrimaryAccountNumberID, NetworkID);

All parameters except SalesHeader as reference.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52570.
