### ISSUE TITLE
Codeunit "Deferral Utilities", function RoundDeferralAmount() issue

### ISSUE THREAD

**Issue by PaulFurlet** [microsoft/ALAppExtensions#21459]
Hello. In the code there is implicit call
```DeferralHeader.Modify();```
If, for example run from Getn. Jnl. - Post Line, function PostDeferral(), this gives the error as no Deferral Header may exist for additionally created journal lines.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51299.
