### ISSUE TITLE
[Add Event Parameter]: Codeunit 5611 -->CalculateDeprAmount()

### ISSUE THREAD

**Issue by dharma534** [microsoft/ALAppExtensions#21450]
Dear Team,

can you please add function CalcDB1Amount() as a parameter for the below two event functions. This function required to calculate Japan country FA depreciation amount.

```ruby
else
    OnCalculateDeprAmountOnDeprMethodCaseLastEntry(FADeprBook, BookValue, DeprBasis, DeprYears, DaysInFiscalYear, 
                         NumberOfDays, Amount, DateFromProjection, UntilDate, CalcDB1Amount());
```

```ruby
else
   OnCalculateDeprAmountOnDeprMethodCaseLastDeprEntry(FADeprBook, BookValue, DeprBasis, DeprYears, DaysInFiscalYear, 
                       NumberOfDays, Amount, DateFromProjection, UntilDate, CalcDB1Amount());
```

**Comment by dharma534** [comment]
We are still waiting for this modification. there is no update since long. it is much appreciate if any feedback from you guys. thanks.

**Comment by dharma534** [comment]
what do you mean for expose the **CalcDB1Amount()** function. how is works?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53591.

**Comment by Vadim-Stepanenko** [comment]
> what do you mean for expose the **CalcDB1Amount()** function. how is works?

The function will not be local anymore, so you can use it in your subscriber.
