### ISSUE TITLE
[Event Request] Service Item Line table 5902 procedure CheckWarranty

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#21468]
![image](https://user-images.githubusercontent.com/49729094/208772244-e11b96c0-664a-46d0-82cd-061a262858f8.png)

On line 1652, calling OnCheckWarrantyOnAfterSetWarranty(Rec, IsHandled);  
Is it possible to pass the parameter 'Date' from the parameter from procedure CheckWarranty(Date: Date)?  

For Example,  
OnCheckWarrantyOnAfterSetWarranty(Rec, Date, IsHandled);  

Thanks very much!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52511.
