### ISSUE TITLE
[Event Request] Service Item Line table 5901 Field 26 Contract No. OnLookup trigger

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#21461]
![image](https://user-images.githubusercontent.com/49729094/208555861-4d97a2c5-b189-474f-ab1a-1b789b272458.png)
Could you please add an event between lines 793 and 794 so we can add more filters?   

OnContactNoLookupOnBeforeSetTableView(Rec, ServContractLine)

[IntegrationEvent(false, false)]
local procedure OnContactNoLookupOnBeforeSetTableView(ServiceitemLine: Record "ServiceItemLine"; var ServContractLine: Record "Service Contract Line")
begin
end;

Thanks very much.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52511.
