### ISSUE TITLE
[Event Request] - OnBeforeTestDirectedPutawayandPickFalse table 210 "Job Journal Line"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#21467]
Dear ALAppExtensions Team:

Please consider adding a new event publisher in table 210 "Job Journal Line"

NEW PUBLISHER:

 [IntegrationEvent(false, false)]
    local procedure OnBeforeTestDirectedPutawayandPickFalse(Location: Record Location; var IsHandled: Boolean)
    begin
    end;

The code in field 21 in table 210 "Job Journal Line" would be modified as follows:

OLD CODE:

....

  field(21; "Location Code"; Code[10])
        {
            Caption = 'Location Code';
            TableRelation = Location WHERE("Use As In-Transit" = CONST(false));

            trigger OnValidate()
            begin
                "Bin Code" := '';
                OnValidateLocationCodeOnBeforeGetLocation(Rec);
                GetLocation("Location Code");
                Location.TestField("Directed Put-away and Pick", false);
                Validate(Quantity);
                if (Type = Type::Item) and ("Location Code" <> xRec."Location Code") then
                    if ("Location Code" <> '') and ("No." <> '') then begin
                        GetItem();
                        if IsDefaultBin() and Item.IsInventoriableType() then
                            WMSManagement.GetDefaultBin("No.", "Variant Code", "Location Code", "Bin Code");
                    end;
            end;
        }

....

NEW CODE:

  field(21; "Location Code"; Code[10])
        {
            Caption = 'Location Code';
            TableRelation = Location WHERE("Use As In-Transit" = CONST(false));

            trigger OnValidate()
            var
	      IsHandled: Boolean;
            begin
                "Bin Code" := '';
                OnValidateLocationCodeOnBeforeGetLocation(Rec);
                GetLocation("Location Code");
               
                IsHandled := false;
                OnBeforeTestDirectedPutawayandPickFalse(Location, IsHandled);
                if not IsHandled then
	          Location.TestField("Directed Put-away and Pick", false);
        
	        Validate(Quantity);
                if (Type = Type::Item) and ("Location Code" <> xRec."Location Code") then
                  if ("Location Code" <> '') and ("No." <> '') then begin
                    GetItem();
                    if IsDefaultBin() and Item.IsInventoriableType() then
                      WMSManagement.GetDefaultBin("No.", "Variant Code", "Location Code", "Bin Code");
                   end;
            end;
        }

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.
