### ISSUE TITLE
Table Domiciliation Journal Line

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#21465]
there is a bug in table Domiciliation Journal Line in the procedure CustUpdatePayment
line:
 "Message 1" := CustLedgEntry."Document No.";

the field "Message 1" has a lenght of 15, but the CustLedgEntry."Document No." can be 20
the line should be like this:

"Message 1" := copystr(CustLedgEntry."Document No.",1,maxstrlen("Message 1"));

Or the "Message 1" field should be extended tot 20 characters.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13710.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 13736.
