### ISSUE TITLE
table 39, field(7; "Location Code"; Code[10]), OnValidate() set CurrFieldNo := FieldNo("Location Code");

### ISSUE THREAD

**Issue by iyiannak** [microsoft/ALAppExtensions#21469]
Hello! We would like to assign the CurrFieldNo := FieldNo("Location Code") at OnValidate trigger of field "Location Code" at table 39 - Purchase Line. We have subscribed on event OnValidateLocationCodeOnBeforeSpecialOrderError, but the CurrFieldNo parameter is 0

**Comment by iyiannak** [comment]
Dear Alexander, 
I am reverting to the same matter, because I think that there was a misunderstanding. My request was you add an assignment CurrFieldNo := FieldNo("Location Code") on the OnValidate trigger of field "Location Code" 
e.g. 
 field(7; "Location Code"; Code[10])
        {
            Caption = 'Location Code';
            TableRelation = Location WHERE("Use As In-Transit" = CONST(false));

            trigger OnValidate()
            var
                ConfirmManagement: Codeunit "Confirm Management";
                IsHandled: Boolean;
            begin
                TestStatusOpen();
                CurrFieldNo := FieldNo("Location Code")
                OnValidateLocationCodeOnAfterTestStatusOpen(Rec);
#if not CLEAN20  
                IsHandled := false;
                OnBeforeUpdateLocationCode(Rec, IsHandled);

similar to the one that already exists for instance at OnValidate of field(11; Description; Text[100]). I am including the code for your ease reference
               
 case Type of
                    Type::Item:
                        ValidateItemDescription();
                    else begin
                            ReturnValue := FindRecordMgt.FindNoByDescription(Type.AsInteger(), Description, true);
                            if ReturnValue <> '' then begin
                                CurrFieldNo := FieldNo("No.");
                                Validate("No.", CopyStr(ReturnValue, 1, MaxStrLen("No.")));
                            end;
                        end;
                end;

**Comment by AlexanderYakunin** [comment]
CurrFieldNo is equal to FieldNo("Location Code") in the OnValidate trigger of field "Location Code", this is provided by platform. If not, create hotfix requests for this. We have few places where we need to change CurrFieldNo in scope of another field, but this is different story.

Anyway, we cannot do such change as extensibility requests, as this is functional change and it should go via technical support request.

**Comment by iyiannak** [comment]
Ok noted. Thank you!
