### ISSUE TITLE
[Event Request] - OnBeforeCommitTracking Codeunit 99000854 "Inventory Profile Offsetting"

### ISSUE THREAD

**Issue by mberlickas** [microsoft/ALAppExtensions#21466]
Hi, please add new event publisher in Base Application for codeunit 99000854 "Inventory Profile Offsetting" with name OnBeforeCommitTracking:
```al
    local procedure CommitTracking()
    var
        PrevTempEntryNo: Integer;
        PrevInsertedEntryNo: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCommitTracking(IsHandled); //New event
        if IsHandled then
            exit;

        if not TempTrkgReservEntry.Find('-') then
            exit;
        ...
    end;
```

```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCommitTracking(var IsHandled)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52143.
