### ISSUE TITLE
[Event Request] codeunit 1255 "Match Bank Payments" and codeunit 1200 "Import Bank Statement"

### ISSUE THREAD

**Issue by kadrikekk** [microsoft/ALAppExtensions#21470]
Please consider adding Events to: 
codeunit 1255 "Match Bank Payments"
procedure FindMatchingEntries
![image](https://user-images.githubusercontent.com/53963253/208872492-40d7070d-e3dc-4db2-b36d-e84272b01a50.png)

[IntegrationEvent(false, false)]
local procedure OnBeforeFindMatchingEntriesTempLedgerEntryMatchingBuffer(var TempBankAccReconciliationLine: Record "Bank Acc. Reconciliation Line" temporary; var TempLedgerEntryMatchingBuffer: Record "Ledger Entry Matching Buffer" temporary; AccountType: Option; ApplyEntries: Boolean)
begin
end;

codeunit 1200 "Import Bank Statement"
trigger OnRun
![image](https://user-images.githubusercontent.com/53963253/208872817-f663ecf1-c79b-43cf-a44f-552195d8979c.png)

[IntegrationEvent(false, false)]
local procedure OnAfterOnRun(var Rec: Record "Data Exch.")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52577.
