### ISSUE TITLE
[Event Request] - OnBeforeSetNextJobQueueRunDate Codeunit 2160 "Calendar Event Mangement"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21475]
Hello, please consider adding the following event to Codeunit 2160 "Calendar Event Mangement"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetNextJobQueueRunDate(var JobQueueEntry: Record "Job Queue Entry"; NewDate: Date; var IsHandled: Boolean)
    begin
    end;
```

and call it accordingly inside the "SetNextJobQueueRunDate" procedure:

    local procedure SetNextJobQueueRunDate(var JobQueueEntry: Record "Job Queue Entry"; NewDate: Date)

    **var
        IsHandled: Boolean;**

    begin

        **OnBeforeSetNextJobQueueRunDate(JobQueueEntry, NewDate, IsHandled);
        if IsHandled then
            exit;**

        JobQueueEntry.LockTable(true);
        JobQueueEntry.Find();

        if NewDate <= Today then
            JobQueueEntry."Earliest Start Date/Time" := CreateDateTime(Today, Time + (5 * 1000))
        else
            JobQueueEntry."Earliest Start Date/Time" := CreateDateTime(NewDate, GetJobQueueRunTime());

        Clear(JobQueueEntry."User ID");

        if JobQueueEntry.Status <> JobQueueEntry.Status::Ready then
            JobQueueEntry.Status := JobQueueEntry.Status::Ready;

        JobQueueEntry.Modify(true);
    end;

Thank you !

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.
