### ISSUE TITLE
[Scope modification  Request] Codeunit 951 - Time Sheet Approval Management - PostAbsence

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#21484]
Dear ALAppExtensions team,

Through this issue we would like to request procedure `PostAbsence` in Codeunit 951 Time Sheet Approval Management to become global :
```al
    // local procedure PostAbsence(var TimeSheetLine: Record "Time Sheet Line") //Old
    procedure PostAbsence(var TimeSheetLine: Record "Time Sheet Line") //New
```

We would like to be able to postpone the Absence posting.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51596.
