### ISSUE TITLE
[Event Request] Codeunit 951 - Time Sheet Approval Management - OnBeforePostAbsence

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#21482]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforePostAbsence` to be added to Codeunit 951 Time Sheet Approval Management with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostAbsence(var TimeSheetLine: Record "Time Sheet Line"; var IsHandled: Boolean)
    begin
    end;
```

which would be called as follows from `PostAbsence`:
```al
    local procedure PostAbsence(var TimeSheetLine: Record "Time Sheet Line")
    var
        Resource: Record Resource;
        TimeSheetHeader: Record "Time Sheet Header";
        TimeSheetDetail: Record "Time Sheet Detail";
        Employee: Record Employee;
        EmployeeAbsence: Record "Employee Absence";
        TimeSheetMgt: Codeunit "Time Sheet Management";
        IsHandled: Boolean; //new
    begin
        //new start
        IsHandled := false;
        OnBeforePostAbsence(TimeSheetLine, IsHandled);
        if IsHandled then 
          exit;
        //new end
        TimeSheetHeader.Get(TimeSheetLine."Time Sheet No.");
```

We would like to be able to postpone the Absence posting.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52288.
