### ISSUE TITLE
[Refactoring Request] - Report 6036 - Create Contract Service Orders

### ISSUE THREAD

**Issue by bleisibach** [microsoft/ALAppExtensions#2148]
On report 6036 Create Contract Service Orders, we would like to give the user the opportunity to filter on the DataItem "Service Contract Line". Right now this is not possible, because on the DataItem, a key is defined. Removing the key would allow the user to add additional filters according to his need. The order of the dataitem itselves is not affected. The order defined is exactley the primary key, therefore the sorting keeps the same.

**Property**
`"Service Contract Line"."DataItemTableView"`

**Actual Value**
`SORTING(Contract Type,Contract No.,Line No.) ORDER(Ascending) WHERE(Service Period=FILTER(<>''))`

**New Value**
`WHERE(Service Period=FILTER(<>''))`

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
