### ISSUE TITLE
[Event Correction Request] Codeunit 99000830 - OnAfterReservEntryInsertNonSurplus

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#2149]
This is a correction of the event introduced with #1774 .

In **codeunit 99000830 Create Reserv. Entry**, you have added the following event:
`LOCAL [IntegrationEvent] OnAfterReservEntryInsertNonSurplus(VAR ReservationEntry : Record "Reservation Entry";VAR ReservationEntry2 : Record "Reservation Entry")`

Hence please fix the event call in function **CreateEntry** as follows:
```
    // >> MODIFY
    // OnAfterReservEntryInsertNonSurplus(ReservEntry2,ReservEntry);
    OnAfterReservEntryInsertNonSurplus(ReservEntry,ReservEntry2);
    // << MODIFY
```

**Comment by NKarolak** [comment]
![image](https://user-images.githubusercontent.com/34504100/62601202-19bda980-b8f1-11e9-8a90-bd87d1b749ff.png)

Hi @AlexanderYakunin , since my second request was "granted", but not implemented **again** - is it denied for some reason? The current implementation is definitely wrong and will cause unnecessary confusion.

**Comment by AlexanderYakunin** [comment]
This is breaking change, we cannot do such changes for production version. Instead we can implement another event in same place but I suppose better add parameter reservEntry into OnBefore event?

**Comment by NKarolak** [comment]
OnBefore is not interesting for us, but I guess it would not harm to add the second parameter there too..

Why do you consider it a breaking change? You do not need to change the publisher's signature, but "only" the calling code, in order to match parameter names and variable names. 

I remember that you had handled such a similar request (updating the calling code only) earlier without rejecting it. I just cannot find it, I've created too many ;-)

**Comment by AlexanderYakunin** [comment]
Because this event can be used by other extensions and it will break their business logic. Partners without knowledge about this change will be having issues which are difficult to fix.

**Comment by NKarolak** [comment]
Every correction is a breaking change, because the bug was breaking things. And the earlier it is fixed, the less people will have issues with it.

See this issue, that has already been corrected: https://github.com/microsoft/ALAppExtensions/issues/2196
Because OnBeforeInsertSalesOrderHeader has been moved in 14.2, my subscriber is broken since the update to 14.2. 
I have to switch it to another event (OnBeforeModifySalesOrderHeader). 
But I would still say it's good that it was corrected ;-)

**Comment by AlexanderYakunin** [comment]
This is already corrected for master and will be in next majour update:
![image](https://user-images.githubusercontent.com/31849120/62624797-8d30dc80-b92c-11e9-9595-d0088ce7e1af.png)
