### ISSUE TITLE
Change Scope OnPrem to Cloud for procedure "InvoiceDiscountAllowed" in Table "G/L Account"

### ISSUE THREAD

**Issue by DaRuizf** [microsoft/ALAppExtensions#21495]
Could you please change Scope('OnPrem') to Scope('Cloud') for procedure "InvoiceDiscountAllowed" in table "G/L Account"?
Thanks

**Comment by AlexanderYakunin** [comment]
No, we don't want to expose this procedure as it is ES only and this code may be refactored going forward. You can always use same two line code for checking it in your extension if needed
