### ISSUE TITLE
[Extensibiliy Request] codeunit 5051 SegManagement FindInteractTmplCode - Overload with Enum

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#21503]
Could maybe add an new procedure ` procedure FindInteractTmplCode(DocumentType:  Enum "Interaction Log Entry Document Type") `
similiar to the current procedure `FindInteractTmplCode` that supports the ` Enum "Interaction Log Entry Document Type"`
```al
procedure FindInteractTmplCode(DocumentType: Integer) InteractTmplCode: Code[10]
begin
...
end;
```
And could you make sure to call the same events, obsoleteing the old with simple integer.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51654.
