### ISSUE TITLE
[Enum Request] - Table Reservation Entry - Field 11 "Source Subtype" ex #21263

### ISSUE THREAD

**Issue by DamianoCastagna** [microsoft/ALAppExtensions#21504]
Hello, I retry with my request.
I was told the the fields is integer but it's not. It's an option. 
If Microsoft permit to extend Document Type for sales and purchase, I think that also this field, that represent the document type for reservation entry, must be an extendible enum or at least a pure integer. 
 

[DamianoCastagna](https://github.com/DamianoCastagna) commented [3 weeks ago](https://github.com/microsoft/ALAppExtensions/issues/21263#issue-1472644256)
Please change the field into Enum so it can be extensible

I want to create a new document type extending the enum Sales Document Type with my values 50000,50001.
But when I use the reservation entry it's not possible to use these values because it's an option and not an integer

field(11; "Source Subtype"; Option)
{
Caption = 'Source Subtype';
OptionCaption = '0,1,2,3,4,5,6,7,8,9,10';
OptionMembers = "0","1","2","3","4","5","6","7","8","9","10";
}

@AlexanderYakunin
Contributor
[AlexanderYakunin](https://github.com/AlexanderYakunin) commented [last week](https://github.com/microsoft/ALAppExtensions/issues/21263#issuecomment-1346832889)
Sorry, this field cannot be transformed to enum, it does not make any sense. We only use Integer value of this field.

@[AlexanderYakunin](https://github.com/AlexanderYakunin) AlexanderYakunin closed this as [completed](https://github.com/microsoft/ALAppExtensions/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [last week](https://github.com/microsoft/ALAppExtensions/issues/21263#event-8016071002)
@DamianoCastagna
Author
[DamianoCastagna](https://github.com/DamianoCastagna) commented [last week](https://github.com/microsoft/ALAppExtensions/issues/21263#issuecomment-1346843695)
Sorry but I don't understand.
I want to create a new document type extending the enum Sales Document Type with my values 50000,50001.
But when I use the reservation entry it's not possible to use these values because it's an option and not an integer

field(11; "Source Subtype"; Option)
{
Caption = 'Source Subtype';
OptionCaption = '0,1,2,3,4,5,6,7,8,9,10';
OptionMembers = "0","1","2","3","4","5","6","7","8","9","10";
}

**Comment by AlexanderYakunin** [comment]
Option is named Integer, you can assign Integer value to Option and Option value to Integer without any problem. 

Please understand that this field cannot be enum, as it will have different values for different source tables. And this field is already Integer in some tables.

**Comment by DamianoCastagna** [comment]
But I can't assign a value greater than 10

**Comment by AlexanderYakunin** [comment]
Why? You can assign any value, like "Source Subtype" = 50000;

**Comment by DamianoCastagna** [comment]
I'll try to put the value value into the flow but if I remember well if the option is passed to a procedure with a value that is not a Optionmember value Business Central will trhow an error. 
We'll start soon with this new app and I'll check.
Thank
