### ISSUE TITLE
Change Scope OnPrem to Cloud for procedure EUCountryFound in Table 9 "Country/Region"

### ISSUE THREAD

**Issue by DaRuizf** [microsoft/ALAppExtensions#21501]
Could you please change Scope('OnPrem') to Scope('Cloud') for procedure EUCountryFound  in table 9 "Country/Region"?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51596.
