### ISSUE TITLE
ABSOptionalParameters Getter Functions

### ISSUE THREAD

**Issue by tscottjendev** [microsoft/ALAppExtensions#21509]
In Modules/System/Azure Blob Services API/src/Helper/ABSOptionalParameters.Codeunit.al it would be nice to be able to get the values that were set.  It would be fairly straightforward.

You have this
```al
    /// <summary>
    /// Filters the results to return only blobs whose names begin with the specified prefix.
    /// </summary>
    /// <param name="Value">Prefix to search for</param>
    procedure Prefix("Value": Text)
    begin
        SetParameter('prefix', "Value");
    end;
```
We need for each setter a getter
```al
    /// <summary>
    /// Gets the prefix value set, if any.
    /// </summary>
    /// <returns>prefix, empty string if not set</returns>
    procedure Prefix(): Text
    begin
        exit(GetParameter('prefix'));
    end;

    internal procedure GetParameter(KeyName: Text) : Text
    var
        KeyValue: Text
    begin
        if Parameters.Get(KeyName, KeyValue) then
           exit(KeyValue);

        exit(''):
    end;
```

I'd be happy to contribute the change if this is something you would agree to.

**Comment by pri-kise** [comment]
@JesperSchulz is this something that would be acceptecd for the system application?

**Comment by darjoo** [comment]
@tscottjendev @pri-kise 
This sounds like a perfectly fine request. Go ahead and contribute it with a PR and I'll process it. 
I'll close this issue in the meantime but once the PR is open, feel free to @ me and link to this issue. :)

**Comment by tscottjendev** [comment]
I have the work completed but I can't compile the application I am getting these errors:

> Error | DotNet Aliases/src/dotnet.al | The type   'Microsoft.Dynamics.Nav.DocumentService.Types.ConflictBehavior' could not be   found in assembly 'Microsoft.Dynamics.Nav.DocumentService.Types,   Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' | [459:14]
> Error | DotNet Aliases/src/dotnet.al | The type 'Microsoft.Dynamics.Nav.DocumentService.Types.UploadedDocument'   could not be found in assembly 'Microsoft.Dynamics.Nav.DocumentService.Types,   Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' | [462:14]
> Error | DotNet Aliases/src/dotnet.al | The type 'Microsoft.Dynamics.Nav.LicensingService.Model.GroupInfo' could   not be found in assembly 'Microsoft.Dynamics.Nav.LicensingService.Model,   Version=1.0.57930.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35' | [584:14]
> Error | Server Settings/src/ServerSettingImpl.Codeunit.al | 'DotNet Microsoft.Dynamics.Nav.Types.ALConfigSettings"' does not   contain a definition for 'TestAutomationEnabled'" | [75:37]
> Error | Server Settings/src/ServerSettingImpl.Codeunit.al | 'DotNet Microsoft.Dynamics.Nav.Types.ALConfigSettings"' does not   contain a definition for 'UsePermissionsFromExtensions'" | [82:31]
> Error | Server Settings/src/ServerSettingImpl.Codeunit.al | 'DotNet Microsoft.Dynamics.Nav.Types.ALConfigSettings"' does not   contain a definition for 'IsSaaS'" | [88:31]
> 
I have added all the assembly probing paths and tried the Microsoft.Dynamics.Nav.Types dll from version 21 and 22.  What am I missing?
