### ISSUE TITLE
Change Scope OnPrem to Cloud for procedures in Codeunit 7000000 CarteraManagement

### ISSUE THREAD

**Issue by DaRuizf** [microsoft/ALAppExtensions#21502]
Could you please change Scope('OnPrem') to Scope('Cloud') for procedures 

- CategorizeDocs
- DecategorizeDocs
- CheckDiscCreditLimit
- CreateReceivableDocPayment
- NavigateDoc
- NavigatePostedDoc
- NavigateClosedDoc

in Codeunit 7000000 CarteraManagement?
Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51596.
