### ISSUE TITLE
[Event Request] - OnBeforeCalcAllItemFields Codeunit 5790 "Available to Promise"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21514]
Hello, please consider adding the following event to Codeunit 5790 "Available to Promise"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcAllItemFields(var Item: record Item; var IsHandled: Boolean; var AllFieldCalculated: Boolean; var PrevItemNo: Code[20]; var PrevItemFilters: Text)
    begin
    end;
```

and call it accordingly inside the "CalcAllItemFields" procedure:

```
    local procedure CalcAllItemFields(var Item: Record Item)
    var

        **IsHandled: Boolean;**

    begin

        **IsHandled := false;
        OnBeforeCalcAllItemFields(Item, IsHandled, AllFieldCalculated, PrevItemNo, PrevItemFilters);
        if IsHandled then
            exit;**

        if AllFieldCalculated and (PrevItemNo = Item."No.") and (PrevItemFilters = Item.GetFilters) then
            exit;
...
...
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52544.
