### ISSUE TITLE
[Event Request] - Change signature on event "OnBeforePost" in Codeunit 5707 "TransferOrder-Post + Print"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21513]
Please consider changing signature on event "OnBeforePost" in Codeunit 5707 "TransferOrder-Post + Print", from:

    [IntegrationEvent(false, false)]
    local procedure OnBeforePost(var TransHeader: Record "Transfer Header"; var IsHandled: Boolean)
    begin
    end;
to:

    [IntegrationEvent(false, false)]
    local procedure OnBeforePost(var TransHeader: Record "Transfer Header"; var TransferPostShipment: Codeunit "TransferOrder-Post Shipment"; var TransferPostReceipt: Codeunit "TransferOrder-Post Receipt"; var IsHandled: Boolean)
    begin
    end;
and call it accordingly in "Code" procedure:

    local procedure "Code"()
    var
        InventorySetup: Record "Inventory Setup";
        TransLine: Record "Transfer Line";
        TransferPostShipment: Codeunit "TransferOrder-Post Shipment";
        TransferPostReceipt: Codeunit "TransferOrder-Post Receipt";
        TransferPostTransfer: Codeunit "TransferOrder-Post Transfer";
        DefaultNumber: Integer;
        Selection: Option " ",Shipment,Receipt;
        IsHandled: Boolean;
    begin
        OnBeforePost(TransHeader, TransferPostShipment, TransferPostReceipt, IsHandled);

        if IsHandled then
            exit;

        DefaultNumber := 0;
        with TransHeader do begin
...
...

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.
