### ISSUE TITLE
[Event Request] Codeunit 13648 OnBeforeInsertPartyIdentification (DK localisation)

### ISSUE THREAD

**Issue by kmlGlobe** [microsoft/ALAppExtensions#21517]
Current Code:
InsertPartyIdentification(PartyElement, OIOUBLDocumentEncode.GetCustomerVATRegNoIncCustomerCountryCode(VATRegNo, PostalAddress."Country/Region Code"))

As VATRegNo is actually not mandatory for OIOUBL but could work with GLN instead we would be able to replace the tag with ones working on GLN with following event (replacing above code)

IsHandled := false;
OnBeforeInsertPartyIdentification(PartyElement, VATRegNo, PostalAddress."Country/Region Code", GLN, DocNameSpaceCAC, DocNameSpaceCBC, IsHandled);
if not IsHandled then
  InsertPartyIdentification(PartyElement, OIOUBLDocumentEncode.GetCustomerVATRegNoIncCustomerCountryCode(VATRegNo, PostalAddress."Country/Region Code"));

> 
[IntegrationEvent(true, false)]
local procedure OnBeforeInsertPartyIdentification(var PartyElement: XmlElement; VATRegNo: Text[20]; CountryRegionCode: Code[10]; GLN: Code[13]; DocNameSpaceCAC: Text[250]; DocNameSpaceCBC: Text[250]; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 57697.
