### ISSUE TITLE
[Event Request] Report 99003803 Copy Production Forecast - dataitem "Production Forecast Entry" trigger OnPreDataItem - OnBeforePreDataItemProductionForecastEntry

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#21527]
Please add the following existing Event OnBeforePreDataItemProductionForecastEntry to dataitem "Production Forecast Entry" trigger OnPreDataItem in Report 99003803 Copy Production Forecast

```
	trigger OnPreDataItem()
	begin
	    ToProdForecastEntry.TestField("Production Forecast Name");
	    IsHandled := FALSE;
            OnBeforePreDataItemProductionForecastEntry(IsHandled); <-- NEW EVENT
            if not IsHandled THEN <-- NEW CODE
		    if not Confirm(Text000, false) then
			    exit;

	    LockTable();

	    LastEntryNo := ProdForecastEntry2.GetLastEntryNo();
	    NextEntryNo := LastEntryNo + 1;
	end;

```

```
[IntegrationEvent(false, false)]
local procedure OnBeforePreDataItemProductionForecastEntry(VAR IsHandled : Boolean)
BEGIN
END
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52577.
