### ISSUE TITLE
[Event Request] Codeunit 10750 "SII XML Creator" add event in "BuildNonExemptTransactionType"

### ISSUE THREAD

**Issue by JB92ARB** [microsoft/ALAppExtensions#21539]
Hi,

We need to add an event in the codeunit 10750 "SII XML Creator":

- In the procedure called "BuildNonExemptTransactionType":
![image](https://user-images.githubusercontent.com/86236240/209669693-90d67f6c-c86e-42d9-a4ba-6ccd9a6b9ca7.png)
OnAfterBuildNonExemptTransactionType(VATEntry, TransactionType);

Integration event definition:
![image](https://user-images.githubusercontent.com/86236240/209669799-2ecaba21-bd1c-4e5a-a5d1-a0b942f5f53f.png)
[IntegrationEvent(false, false)]
local procedure OnAfterBuildNonExemptTransactionType(VATEntry: Record "VAT Entry"; var TransactionType: Option S1,S2,S3,Initial)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53246.
