### ISSUE TITLE
[Event Request] - Event signature change "OnMakeSingleLevelAdjmtOnAfterUpdateItemUnitCost" inside 5895 "Inventory Adjustment"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21536]
Please, consider changing the signature of the event "OnMakeSingleLevelAdjmtOnAfterUpdateItemUnitCost" inside 5895 "Inventory Adjustment", from:

    [IntegrationEvent(false, false)]
    local procedure OnMakeSingleLevelAdjmtOnAfterUpdateItemUnitCost(var TheItem: Record Item; var TempAvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point" temporary; var LevelExceeded: Boolean; IsOnlineAdjmt: Boolean)
    begin
    end;

to:

    [IntegrationEvent(false, false)]
    local procedure OnMakeSingleLevelAdjmtOnAfterUpdateItemUnitCost(var TheItem: Record Item; var TempAvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point" temporary; var LevelExceeded: Boolean; IsOnlineAdjmt: Boolean; var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line")
    begin
    end;

and call it accordingly inside the "MakeSingleLevelAdjmt" procedure:

```
    local procedure MakeSingleLevelAdjmt(var TheItem: Record Item; var TempAvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point" temporary)
    var
        IsFirstTime: Boolean;
    begin
        LevelNo[1] := LevelNo[1] + 1;

        UpDateWindow(LevelNo[1], WindowItem, WindowAdjust, WindowFWLevel, WindowEntry, 0);

        ConsumpAdjmtInPeriodWithOutput := 0D;

        TheItem.SetCurrentKey("Low-Level Code");
        if TheItem.FindLast() then
            TheItem.SetRange("Low-Level Code", TheItem."Low-Level Code");

        with Item do
            if TheItem.FindSet() then
                repeat
                    Item := TheItem;
                    GetItem("No.");
                    UpDateWindow(WindowAdjmtLevel, "No.", WindowAdjust, WindowFWLevel, WindowEntry, 0);

                    CollectAvgCostAdjmtEntryPointToUpdate(TempAvgCostAdjmtEntryPoint, TheItem."No.");
                    IsFirstTime := not AppliedEntryToAdjustBufExists(TheItem."No.");

                    repeat
                        LevelExceeded := false;
                        AdjustItemAppliedCost();
                    until not LevelExceeded;

                    AdjustItemAvgCost();
                    PostAdjmtBuf(TempAvgCostAdjmtEntryPoint);
                    UpdateItemUnitCost(TempAvgCostAdjmtEntryPoint, IsFirstTime);

                    **OnMakeSingleLevelAdjmtOnAfterUpdateItemUnitCost(TheItem, TempAvgCostAdjmtEntryPoint, LevelExceeded, IsOnlineAdjmt, ItemJnlPostLine);**

                until (TheItem.Next() = 0) or LevelExceeded;
    end;
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.
