### ISSUE TITLE
[Event Request] Codeunit 10750 "SII XML Creator" add event in "PopulateXMLWithSalesInvoice" and "PopulateXMLWithCollectionInCash"

### ISSUE THREAD

**Issue by JB92ARB** [microsoft/ALAppExtensions#21538]
Hello,

We need to add the following events in codeunit 10750 "SII XML Creator":

- In procedure called "PopulateXMLWithSalesInvoice":
![image](https://user-images.githubusercontent.com/86236240/209668323-035f9822-bad2-4058-8d0d-2b578d542aa4.png)

OnPopulateXMLWithSalesInvoiceOnAfterGetCustomer(CustLedgerEntry, Customer);

Integration event definition:
![image](https://user-images.githubusercontent.com/86236240/209668465-9825b360-1ea7-4fdf-8600-4733ce11de74.png)

    [IntegrationEvent(false, false)]
    local procedure OnPopulateXMLWithSalesInvoiceOnAfterGetCustomer(CustLedgerEntry: Record "Cust. Ledger Entry"; var Customer: Record Customer)
    begin
    end;

- In procedure called "PopulateXMLWithCollectionInCash":
![image](https://user-images.githubusercontent.com/86236240/209668554-81d98622-de2c-4909-9dec-323dfe073885.png)
OnPopulateXMLWithCollectionInCashOnAfterGetCustomer(CustLedgerEntry, Customer);

Integration event definition:
![image](https://user-images.githubusercontent.com/86236240/209668608-ab3b9d18-fd53-4602-b710-80d4a7f876d0.png)

    [IntegrationEvent(false, false)]
    local procedure OnPopulateXMLWithCollectionInCashOnAfterGetCustomer(CustLedgerEntry: Record "Cust. Ledger Entry"; var Customer: Record Customer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53246.
