### ISSUE TITLE
[Event Request] - New event OnBeforeOnRun inside codeunit  5904 "Service Cr. Memo-Printed"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21542]
Hello, please consider adding the following event to Codeunit 5904 "Service Cr. Memo-Printed"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnRun(var ServiceCrMemoHeader: Record "Service Cr.Memo Header"; var SuppressCommit: Boolean)
    begin
    end;
```

and call it inside the "OnRun" procedure:

```
    trigger OnRun()

    **var
        SuppressCommit: Boolean;
    begin
        OnBeforeOnRun(Rec, SuppressCommit);**


        Find();
        "No. Printed" := "No. Printed" + 1;
        OnBeforeModify(Rec);
        Modify();

        **if not SuppressCommit then**

              Commit();
    end;
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52511.
