### ISSUE TITLE
Event Request Page 99000816 Production Order Statistics

### ISSUE THREAD

**Issue by maheshroyal34** [microsoft/ALAppExtensions#2154]
Events - OnBeforeCalcVariance,OnAfterCalcVariance

Event:
LOCAL [IntegrationEvent] OnBeforeCalcVariance(VAR VarAmt:Decimal,VAR VarPct:Decimal,VAR StdCost:Decimal,VAR ActCost:Decimal,VAR IsHandled:Boolean);

Event:
LOCAL [IntegrationEvent] OnAfterCalcVariance(VAR VarAmt:Decimal,VAR VarPct:Decimal,VAR StdCost:Decimal,VAR ActCost:Decimal,VAR IsHandled:Boolean);

FOR i := 1 TO ARRAYLEN(VarAmt) DO BEGIN
  >>>New Code Start
  OnBeforeCalcVariance(VAR VarAmt:Decimal,VAR VarPct:Decimal,VAR StdCost:Decimal,VAR ActCost:Decimal,VAR IsHandled:Boolean);
  <<<New Code End 
  if Not IsHandled then Begin<<New Code
    VarAmt[i] := ActCost[i] - StdCost[i];
    VarPct[i] := CalcIndicatorPct(StdCost[i],ActCost[i]);
  END;<<New Code
  >>>New Code Start
  OnAfterCalcVariance(VAR VarAmt:Decimal,VAR VarPct:Decimal,VAR StdCost:Decimal,VAR ActCost:Decimal,VAR IsHandled:Boolean);
  <<<New Code End
END;

**Comment by AlexanderYakunin** [comment]
Please explain why do you need second event?

**Comment by maheshroyal34** [comment]
Hello,
The second event is not required.
