### ISSUE TITLE
[Event Request] OnBeforeInitPostingDescription in table 38 "Purchase Header"

### ISSUE THREAD

**Issue by TriangleSPV** [microsoft/ALAppExtensions#21553]
It is required that the assignation of the "Posting Description" works in "Purchase Header" equal than "Sales Header".

This is the proposal of the changes in the InitRecord() function of the table "Purchase Header":

        InitVATDate();

        OnInitRecordOnAfterAssignDates(Rec);

        ValidateEmptySellToCustomerAndLocation();

        if IsCreditDocType() then begin
            GLSetup.Get();
            Correction := GLSetup."Mark Cr. Memos as Corrections";
        end;

        //"Posting Description" := Format("Document Type") + ' ' + "No.";   <-- LINE TO MOVE
        InitPostingDescription();    //new procedure
        

The new procedure:

    procedure InitPostingDescription()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeInitPostingDescription(Rec, IsHandled);
        if IsHandled then
            exit;

        "Posting Description" := Format("Document Type") + ' ' + "No.";
    end;

The new integration event:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitPostingDescription(var table 38 "Purchase Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52485.
