### ISSUE TITLE
Codeunits 80 and 90 - InsertPostedHeaders

### ISSUE THREAD

**Issue by Sergisoft** [microsoft/ALAppExtensions#2155]
InsertPostedHeaders does not receive its parameter as VAR.

That's breaking the call stack sense of OnRun - CheckAndUpdate - InsertPostedHeaders - InsertReceiptHeader where all them use VAR except InsertPostedHeaders.

If any field on PurchHeader is changed on InsertReceiptHeader, this changes is not propagated back to OnRun due to InsertPostedHeaders does not receive its parameter as VAR.

**Comment by Sergisoft** [comment]
@AlexanderYakunin please let me know if you need any clarifications. I'm not sure if my explanation was clear enough.

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
