### ISSUE TITLE
[Event Request] - New event OnBeforeGetSalesOrderLineItem inside 5520 "Get Unplanned Demand"

### ISSUE THREAD

**Issue by ak-itint** [microsoft/ALAppExtensions#21552]
Hello, please consider adding the following event to Codeunit 5520 "Get Unplanned Demand"

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetSalesOrderLineItem(var TempItem: Record Item; SalesOrderLine: Record "Sales Line")
    begin
    end;

and call it inside the "SetFilterToSpecificSalesOrder" procedure:

        if SalesOrderLine.FindSet() then begin
            repeat
                **OnBeforeGetSalesOrderLineItem(TempItem, SalesOrderLine);
                // Find all the items needed to be planned and add it to a temp item bufffer
                if not TempItem.Get(SalesOrderLine."No.") then
                    if Item.Get(SalesOrderLine."No.") then begin
                        TempItem := Item;
                        TempItem.Insert();
                    end;
            until SalesOrderLine.Next() = 0;

            if TempItem.Count() >= (TypeHelper.GetMaxNumberOfParametersInSQLQuery() - 100) then
                exit;

Thanks !

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52717.
