### ISSUE TITLE
[Event Request] Page 6057 - Contract Line Selection - OnLookupOKOnPush

### ISSUE THREAD

**Issue by CHCH001** [microsoft/ALAppExtensions#21551]
We would like to request a new event called OnlookupOKPush(Var: OKButton,Rec) within the page Contract Line Selection, so we can customize accordingly please.

trigger OnQueryClosePage(CloseAction: Action): Boolean

    begin

        if CloseAction = ACTION::LookupOK then

            LookupOKOnPush();

      **OnlookupOkOnpush(OKButton, Rec);**

        if OKButton then begin

            ServContract.Get(ContractType, ContractNo);

            CurrPage.SetSelectionFilter(Rec);

            ServContractLine.HideDialogBox(true);

            if Find('-') then

                repeat

                    CheckServContractLine();

                until Next() = 0;

            CreateServContractLines();

            Commit();

        end;

    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52577.
