### ISSUE TITLE
Procedure Bug in "Capacity Ledger Entry" Table

### ISSUE THREAD

**Issue by vdevmt** [microsoft/ALAppExtensions#21550]
Table: Capacity Ledger Entry
Procedure:  GetCurrencyCode()

FROM:
    local procedure GetCurrencyCode(): Code[10]
    begin
        if GLSetupRead then begin
            GLSetup.Get();
            GLSetupRead := true;
        end;
        exit(GLSetup."Additional Reporting Currency");
    end;

TO:

    local procedure GetCurrencyCode(): Code[10]
    begin
        if **NOT** GLSetupRead then begin
            GLSetup.Get();
            GLSetupRead := true;
        end;
        exit(GLSetup."Additional Reporting Currency");
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 51686.
