### ISSUE TITLE
Get Correct Azure AD Auth End point

### ISSUE THREAD

**Issue by navaddins** [microsoft/ALAppExtensions#21561]
```
Authorization endpoint - used by client to obtain authorization from the resource owner.
https://login.microsoftonline.com/<issuer>/oauth2/v2.0/authorize
# Token endpoint - used by client to exchange an authorization grant or refresh token for an access token.
https://login.microsoftonline.com/<issuer>/oauth2/v2.0/token`

# NOTE: These are examples. Endpoint URI format may vary based on application type,
#       sign-in audience, and Azure cloud instance (global or national cloud).

#       The {issuer} value in the path of the request can be used to control who can sign into the application. 
#       The allowed values are **common** for both Microsoft accounts and work or school accounts, 
#       **organizations** for work or school accounts only, **consumers** for Microsoft accounts only, 
#       and **tenant identifiers** such as the tenant ID or domain name.
```

[MS documentation](https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols) said as per above, how to generate Authorization endpoint. 

[Here ](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-ad-openid-connect?tabs=multitenant%2Cadmintool) is how we can register the application on AAD.

`Specifies the accounts that you would like your application to support. If you're going to use different Azure AD tenants for different Business Central tenants, then select Accounts in any organizational directory (Any Azure AD directory - Multitenant). Otherwise, you can choose Accounts in this organizational directory only (Single tenant).`

However, codeunit 3704 "Url Helper Impl." is hard code to generate the ADAuthEndpoint and it's against with MS documentation. It is not working if we are not using "Multitenant" when we registered the application on AAD. We got the error as per below

```
AADSTS50194: Application 'xxxxxx-xxxxx-xxxx-xxxx-7'(Single Sign-On) is not configured as a multi-tenant application.
Usage of the /common endpoint is not supported for such applications created after '10/15/2018'.
Use a tenant-specific endpoint or configure the application to be multi-tenant.
```

Existing Code

```
  [Scope('OnPrem')]
  procedure GetAzureADAuthEndpoint() AuthEndpoint: Text
  var
      NavUserAccountHelper: DotNet NavUserAccountHelper;
  begin
      AuthEndpoint := NavUserAccountHelper.GetTokenAuthorityEndpointServerSetting();

      if AuthEndpoint = '' then begin
          Session.LogMessage('0000GN6', NoServerAuthEndpointTelemetryErr, Verbosity::Warning, DataClassification::SystemMetadata, TelemetryScope::ExtensionPublisher, 'Category', TelemetryCategoryLbl);

          if IsPPE() then
              AuthEndpoint := 'https://login.windows-ppe.net/'
          else
              AuthEndpoint := 'https://login.microsoftonline.com/';
      end;

      exit(DelChr(AuthEndpoint, '>', '/') + '/common/oauth2/authorize');
  end;
```
Propose

```
  [Scope('OnPrem')]
  procedure GetAzureADAuthEndpoint() AuthEndpoint: Text
  var
      NavUserAccountHelper: DotNet NavUserAccountHelper;
  begin
      AuthEndpoint := NavUserAccountHelper.GetTokenAuthorityEndpointServerSetting();

      if AuthEndpoint = '' then begin
          Session.LogMessage('0000GN6', NoServerAuthEndpointTelemetryErr, Verbosity::Warning, DataClassification::SystemMetadata, TelemetryScope::ExtensionPublisher, 'Category', TelemetryCategoryLbl);

          if IsPPE() then
              AuthEndpoint := 'https://login.windows-ppe.net/'
          else
              AuthEndpoint := 'https://login.microsoftonline.com/';

          AuthEndpoint := DelChr(AuthEndpoint, '>', '/') + '/common/oauth2/authorize'
      end;

      exit(AuthEndpoint);
  end;
```

**Comment by darjoo** [comment]
@navaddins Is this for OnPrem usage? As I can't seem to understand the change if it were for SaaS as `GetTokenAuthorityEndpointServerSetting` would always return an endpoint. 
 Inwhich case, the proposed function will always fail in SaaS as it's missing the `/common/oauth2/authorize` ending.

**Comment by navaddins** [comment]
@darjoo,

Thank for response.

This request for OnPrem usage.

I don't know what value is return from `NavUserAccountHelper.GetTokenAuthorityEndpointServerSetting()` when we call this function on SAAS version. New propose solution won't be miss `/common/oauth2/authorize` if there has no value is set on `TokenAuthorityEndpoint` in "CustomSettings.config" (SaaS or OnPrem). System should not change any value if we set the value in `TokenAuthorityEndpoint`. 

Eg. 
"CustomSettings.config"

`<add key="TokenAuthorityEndpoint" value="https://login.microsoftonline.com/MyTenantId/oauth2/v2.0/authorize" />`

Now, system added `/common/oauth2/authorize` ending become 

`https://login.microsoftonline.com/MyTenantId/oauth2/v2.0/common/oauth2/authorize
`

We are happy to accept any better solution on this topic.

**Comment by stkillen** [comment]
First of all, I'm sorry that this request has been open for a year with no response.

Unfortunately, I'll be closing this issue as we have no plans to extend OnPrem functionality in this area. The SaaS functionality works as expected and the suggested solutions would break SaaS functionality.

Additionally, since this was opened we have new repositories for these type of requests:
- If you are looking to contribute to the System Application or Developer Tools you can do so in the [BCApps](https://github.com/microsoft/BCApps) repository.
- If you are looking to contribute to the Base Application you can do so in the [BusinessCentralApps](https://github.com/microsoft/BusinessCentralApps/) repository. Please note, that this repository is private but you can request access by filling out [this form](https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR_Qj5hjzNeNOhBcvBoRIOltUOVBVTklZN1hBOTZJUU40OE5CUzNWNk1FQy4u).

If some functionality is broken in OnPrem, please report through proper channels and not through an extensibility request in this repository. This is not the right place to report product defects with customer impact to Microsoft.
