### ISSUE TITLE
Change Event OnAfterFilterCustLedgEntryReminderLevel in codeunit 392 "Reminder-Make"

### ISSUE THREAD

**Issue by AndreaRux** [microsoft/ALAppExtensions#21578]
Please add Parameter ReminderHeaderReq and ReminderHeader to Event

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterFilterCustLedgEntryReminderLevel(var CustLedgerEntry: Record "Cust. Ledger Entry"; var ReminderLevel: Record "Reminder Level"; ReminderTerms: Record "Reminder Terms"; Customer: Record Customer; ReminderHeaderReq: Record "Reminder Header"; ReminderHeader: Record "Reminder Header")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52728.
