### ISSUE TITLE
[Event Request] new Event OnAfterGetRecordReminderHeaderOnBeforeMakeReminder Report 189 Suggest Reminder Lines  

### ISSUE THREAD

**Issue by AndreaRux** [microsoft/ALAppExtensions#21576]
Please add new Event in Report 189

[IntegrationEvent(false, false)]
local procedure **OnAfterGetRecordReminderHeaderOnBeforeMakeReminder**(ReminderHeader: Record "Reminder Header"; var CustLedgEntry: Record "Cust. Ledger Entry"; OverdueEntriesOnly: Boolean; IncludeEntriesOnHold: Boolean; var CustLedgEntryLineFeeOn: Record "Cust. Ledger Entry"; var Result: Boolean; var IsHandled: Boolean)

and call it in the same way like in Report 188

trigger OnAfterGetRecord()
**var
    IsHandled: Boolean;
    Result: Boolean;**
begin
    RecordNo := RecordNo + 1;
    Clear(MakeReminder);
    MakeReminder.SuggestLines("Reminder Header", CustLedgEntry, OverdueEntriesOnly, IncludeEntriesOnHold, CustLedgEntryLineFeeOn);
    if NoOfRecords = 1 then begin
        **Result := false;
        IsHandled := false;
        OnAfterGetRecordReminderHeaderOnBeforeMakeReminder(
"Reminder Header", CustLedgEntry, OverdueEntriesOnly, IncludeEntriesOnHold, CustLedgEntryLineFeeOn, Result, IsHandled);
        if not IsHandled then**
          MakeReminder.Code();
        Mark := false;
    end else begin
        NewDateTime := CurrentDateTime;
        if (NewDateTime - OldDateTime > 100) or (NewDateTime < OldDateTime) then begin
          NewProgress := Round(RecordNo / NoOfRecords * 100, 1);
          if NewProgress <> OldProgress then begin
            Window.Update(1, NewProgress * 100);
            OldProgress := NewProgress;
          end;
           OldDateTime := CurrentDateTime;
        end;
        **Result := false;
        IsHandled := false;
        OnAfterGetRecordReminderHeaderOnBeforeMakeReminder(
"Reminder Header", CustLedgEntry, OverdueEntriesOnly, IncludeEntriesOnHold, CustLedgEntryLineFeeOn, Result, IsHandled);
        if IsHandled then
          Mark(Result)
        else**
          Mark := not MakeReminder.Code();
    end;
end;

**Comment by GeekEding** [comment]
Hi,
are there any updates on this event request? 
Would be a good event for the next release, if possible :)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10481.
