### ISSUE TITLE
[Event Request] - New event OnBeforeOnRun inside codeunit 12170 "Recall Customer Bill"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#21574]
Hello, please consider adding the following event to Codeunit 12170 "Recall Customer Bill"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnRun(var CustomerBillHeader: Record "Customer Bill Header"; var IsHandled: Boolean)
    begin
    end;
```

and call it inside the "OnRun" procedure:

```
    trigger OnRun()
    var

        **IsHandled: Boolean;**

    begin

        **IsHandled := false;
        OnBeforeOnRun(Rec, IsHandled);
        if IsHandled then
            exit;**

        if not Confirm(Text1130001) then
            exit;

        TestField("Payment Method Code");
        SalesSetup.Get();

        PaymentMethod.Get("Payment Method Code");
        Bill.Get(PaymentMethod."Bill Code");
...
...
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52146.
