### ISSUE TITLE
[Event Request] new Event OnBeforeRemoveLinesOfNegativeReminder in codeunit 392 "Reminder-Make"

### ISSUE THREAD

**Issue by AndreaRux** [microsoft/ALAppExtensions#21585]
Please add new Event in codeunit 392 "Reminder-Make"
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeRemoveLinesOfNegativeReminder(ReminderHeaderReq: Record "Reminder Header"; ReminderHeader: Record "Reminder Header"; Cust: Record Customer; var IsHandled: Boolean);
    begin
    end;
```
And call it in procedure MakeReminder like this

```
        IsHandled := false;
        OnBeforeRemoveLinesOfNegativeReminder(ReminderHeaderReq, ReminderHeader, Cust, IsHandled);
        if not IsHandled then
            RemoveLinesOfNegativeReminder(ReminderHeader);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52728.
