### ISSUE TITLE
[Event Request] Codeunit 5940 - ServContractManagement - OnCreateServHeaderOnBeforeModify

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#2159]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnCreateServHeaderOnBeforeModify` to be added to Codeunit 5940 ServContractManagement with the following signature:
```
LOCAL [IntegrationEvent] OnCreateServHeaderOnBeforeModify(VAR ServHeader : Record "Service Header"; ServContractHeader : Record "Service Contract Header")
```
with **VAR** parameter `ServHeader`.

which would be called as follows from `CreateServHeader`:
```pascal
[External] CreateServHeader(ServContract2 : Record "Service Contract Header";PostDate : Date;ContractExists : Boolean) ServInvNo : Code[20]
...

OnCreateServHeaderOnBeforeModify(ServHeader2, ServContract2); // << Call to new event
ServHeader2.MODIFY;
RecordLinkManagement.CopyLinks(ServContract2,ServHeader2);

CLEAR(ServDocReg);
ServDocReg.InsertServSalesDocument(
  ServDocReg."Source Document Type"::Contract,
  ServContract2."Contract No.",
  ServDocReg."Destination Document Type"::Invoice,
  ServHeader2."No.");

OnAfterCreateServHeader(ServHeader2,ServContract2);
```

**Comment by AlexanderYakunin** [comment]
We already have event OnBeforeServHeaderModify(ServHeader2,ServContract2) here.

**Comment by rvanbekkum** [comment]
Dear @AlexanderYakunin,
Thank you for your reply. The latest version I pulled at that time from the bcinsider master (bcsandbox-master) did not seem to have this event. Is this the correct branch to do event requests against, or should I make the requests against a different version?
