### ISSUE TITLE
[Protected var] Report 31039 "FA Assignment/Discharge".Employee

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#21598]
Please make global variable "Employee" as protected var.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10064.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 54962.
