### ISSUE TITLE
[Event Request + Requests for External] Table 11401 CBG Statement Line - OnBeforeCheckIdentification

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#21613]
Hello,

We made some requests in https://github.com/microsoft/ALAppExtensions/issues/19494 and saw they were approved at that moment and mentioned to be implemented in Build ID: 46663. 
We have version 21.2 and those requests are not implemented yet.

Could you please let us know when they will be implemented?

**Comment by AlexanderYakunin** [comment]
Event implemented and OnPrem removed. Please do not mess up requests for events and global procedures in the same request, we cannot process it together, as we implement events into master + previous version but other requests to master only. As result only part of original request have been implemented. Please verify the code and create NEW request for remaining changes if any.
