### ISSUE TITLE
[Event Request] Page 55 - Purch. Invoice Subform - OnBeforeDeleteRecord

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#21627]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnBeforeDeleteRecord` in Page 55 Purch. Invoice Subform with the following signature:
```AL
[IntegrationEvent(false,false)]
local procedure OnBeforeDeleteRecord(var PurchaseLine: Record "Purchase Line")
begin
end;
```
which would be called as follows in the global `OnDeleteRecord` trigger:
```AL
trigger OnDeleteRecord(): Boolean
var
    PurchLineReserve: Codeunit "Purch. Line-Reserve";
begin
    // >>>> New >>>>>>>>>>>>>>>>
    OnBeforeDeleteRecord(Rec);
    // <<<< New <<<<<<<<<<<<<<<<
    if (Quantity <> 0) and ItemExists("No.") then begin
        Commit();
        if not PurchLineReserve.DeleteLineConfirm(Rec) then
            exit(false);
        PurchLineReserve.DeleteLine(Rec);
    end;
    DocumentTotals.PurchaseDocTotalsNotUpToDate();
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52717.
