### ISSUE TITLE
[BUG] TableExt 30106 Shpfy Sales Shipment Header - Field 30102 "Shpfy Order No."

### ISSUE THREAD

**Issue by prubier** [microsoft/ALAppExtensions#21628]
Hi,

Can you please check if this field ID is an error or not?

`tableextension 30106 "Shpfy Sales Shipment Header" extends "Sales Shipment Header"
{
    fields
    {
        field(30100; "Shpfy Order Id"; BigInteger)
        {
            Caption = 'Shopify Order Id';
            DataClassification = CustomerContent;
            Editable = false;
        }

        field(**30102**; "Shpfy Order No."; Code[50])
        {
            Caption = 'Shopify Order No.';
            DataClassification = CustomerContent;
            Editable = false;
        }
        field(30103; "Shpfy Fulfillment Id"; BigInteger)
        {
            Caption = 'Shopify Fulfillment Id';
            DataClassification = CustomerContent;
            Editable = false;
        }
    }
}`

Into the table extension Sales Header and Sales Invoice Header, the field ID is 30101.
When posting the Shipment, the Shpfy Order No. don't follow with the transferfield.

To solve this issue temporary, I just add an event subscribber into Codeunit80.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10459.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 55336.

**Comment by AndersLarsenMicrosoft** [comment]
We will fix this for now by adding a subscriber to post shipment (similar to the current mitigation). hopefully we will be able to change field ids at a later state so we can correct this on a non breaking way
