### ISSUE TITLE
[Event Request] OnBeforeCalcBaseQty in table 7321 "Warehouse Shipment Line", table 7317 "Warehouse Receipt Line", table 7311 "Warehouse Journal Line" and table 5767 "Warehouse Activity Line"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#21629]
Please add a new trigger OnBeforeCalcBaseQty in table 7321 "Warehouse Shipment Line", table 7317 "Warehouse Receipt Line", table 7311 "Warehouse Journal Line" and table 5767 "Warehouse Activity Line", table 5741 "Transfer Line"
and make the procedure CalcBaseQty external to be available for our code in these tables and table 39 "Purchase Line" as this is already external in table 37 "Sales Line"

old:
    local procedure CalcBaseQty(Qty: Decimal; FromFieldName: Text; ToFieldName: Text): Decimal
    begin
        TestField("Qty. per Unit of Measure");
        exit(UOMMgt.CalcBaseQty(
            "Item No.", "Variant Code", "Unit of Measure Code", Qty, "Qty. per Unit of Measure", "Qty. Rounding Precision (Base)", FieldCaption("Qty. Rounding Precision"), FromFieldName, ToFieldName));
    end;

new:
    procedure CalcBaseQty(Qty: Decimal; FromFieldName: Text; ToFieldName: Text): Decimal
    begin
        TestField("Qty. per Unit of Measure");
        OnBeforeCalcBaseQty(Rec, Qty, FromFieldName, ToFieldName);
        exit(UOMMgt.CalcBaseQty(
            "Item No.", "Variant Code", "Unit of Measure Code", Qty, "Qty. per Unit of Measure", "Qty. Rounding Precision (Base)", FieldCaption("Qty. Rounding Precision"), FromFieldName, ToFieldName));
    end;

**Comment by AlexanderYakunin** [comment]
Events will be added soon to Master and V.22, but we cannot remove LOCAL in released version. Please create separate requests for events and external procedures, to process this timely and properly.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10481.
