### ISSUE TITLE
[Event Request] Page 31160 "Cash Document CZP".UpdateEditable

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#21623]
Please add new event

```
local procedure UpdateEditable()
begin
    DateEditable := Rec.Status = Rec.Status::Open;
    ReceiptEditable := Rec."Document Type" = Rec."Document Type"::Receipt;
    WithdrawalEditable := Rec."Document Type" = Rec."Document Type"::Withdrawal;
    //---------------------------------------OnAfterUpdateEditable:BEGIN
    OnAfterUpdateEditable(Rec);
    //---------------------------------------OnAfterUpdateEditable:END
end;


//---------------------------------------OnAfterUpdateEditable:BEGIN
[IntegrationEvent(true, false)]
local procedure OnAfterUpdateEditable(CashDocumentHeader: Record "Cash Document Header")
begin
end;
//---------------------------------------OnAfterUpdateEditable:END


```

**Comment by DavidHolusa** [comment]
Hi @fridrichovsky. The SetAppliesToID procedure doesn't exist in Cash Document CZP page. It looks like typo and some weird mix with the https://github.com/microsoft/ALAppExtensions/issues/21624 request. Could you clarify what do you exactly want in this page?

**Comment by fridrichovsky** [comment]
Hi @DavidHolusa I am sorry you are right. Code was from different event. I fixed code.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10068.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 54523.
