### ISSUE TITLE
SharePoint Client Download file into stream

### ISSUE THREAD

**Issue by dynagoDavidIstvan** [microsoft/ALAppExtensions#21637]
Hi,

I would like to ask to have possibility for SharePoint Client to be able to download file into stream. Currently it is only possible to download to client.

Thanks!

**Comment by jwikman** [comment]
@dynagoDavidIstvan, we need similar functionality for one of our apps, so we have implemented a new function with the following signature
`
DownloadFileContent(OdataId: Text; var TempBlob: Codeunit "Temp Blob"): Boolean
`
I will create a PR with this as soon as it's completed and tested.
