### ISSUE TITLE
Codeunit 6500 - Item Tracking Management - OnBeforeCannotMatchItemTrackingErr new event

### ISSUE THREAD

**Issue by DParkerRSM** [microsoft/ALAppExtensions#21630]
I am working on a modification to allow users to pick more than originally requested based on rleased production orders but there is an error I have not been able to circumnavigate. I want to record the quantity picked and then consume manually before then posting actual output and returning any unused inventory to the warehouse. 

I tried back tracking but could not find anything else to use with a "IsHandled" boolean and I would rather not copy the function to a custom area in case it changes in the future.

local procedure RegisterNewItemTrackingLines(var TempTrackingSpec: Record "Tracking Specification" temporary)
    var
        TrackingSpec: Record "Tracking Specification";
        ReservEntry: Record "Reservation Entry";
        ReservMgt: Codeunit "Reservation Management";
        ItemTrackingLines: Page "Item Tracking Lines";
        QtyToHandleInItemTracking: Decimal;
        QtyToHandleOnSourceDocLine: Decimal;
        QtyToHandleToNewRegister: Decimal;
    begin
        OnBeforeRegisterNewItemTrackingLines(TempTrackingSpec);

        TempTrackingSpec.SetCurrentKey(
          "Source ID", "Source Type", "Source Subtype", "Source Batch Name", "Source Prod. Order Line", "Source Ref. No.");

        if TempTrackingSpec.FindSet() then
            repeat
                TempTrackingSpec.SetSourceFilter(
                  TempTrackingSpec."Source Type", TempTrackingSpec."Source Subtype",
                  TempTrackingSpec."Source ID", TempTrackingSpec."Source Ref. No.", false);
                TempTrackingSpec.SetRange("Source Prod. Order Line", TempTrackingSpec."Source Prod. Order Line");

                TrackingSpec := TempTrackingSpec;
                TempTrackingSpec.CalcSums("Qty. to Handle (Base)");

                QtyToHandleToNewRegister := TempTrackingSpec."Qty. to Handle (Base)";
                ReservEntry.TransferFields(TempTrackingSpec);
                QtyToHandleInItemTracking :=
                  Abs(CalcQtyToHandleForTrackedQtyOnDocumentLine(
                      ReservEntry."Source Type", ReservEntry."Source Subtype", ReservEntry."Source ID", ReservEntry."Source Ref. No."));
                QtyToHandleOnSourceDocLine := ReservMgt.GetSourceRecordValue(ReservEntry, false, 0);

>> Add >>
OnBeforeCannotMatchItemTrackingErr(TempTrackingSpec, QtyToHandleToNewRegister, QtyToHandleInItemTracking, QtyToHandleOnSourceDocLine);
<< Add <<

                if QtyToHandleToNewRegister + QtyToHandleInItemTracking > QtyToHandleOnSourceDocLine then
                    Error(CannotMatchItemTrackingErr);

                TrackingSpec."Quantity (Base)" :=
                  TempTrackingSpec."Qty. to Handle (Base)" + Abs(ItemTrkgQtyPostedOnSource(TrackingSpec));

                OnBeforeRegisterItemTrackingLinesLoop(TrackingSpec, TempTrackingSpec);

                Clear(ItemTrackingLines);
                OnRegisterNewItemTrackingLinesOnAfterClearItemTrackingLines(ItemTrackingLines);
                ItemTrackingLines.SetCalledFromSynchWhseItemTrkg(true);
                OnRegisterNewItemTrackingLinesOnBeforeRegisterItemTrackingLines(TempTrackingSpecification, ItemTrackingLines);
                ItemTrackingLines.RegisterItemTrackingLines(TrackingSpec, TrackingSpec."Creation Date", TempTrackingSpec);
                TempTrackingSpec.ClearSourceFilter();
            until TempTrackingSpec.Next() = 0;

        TempTrackingSpec.SetCurrentKey("Entry No.");
    end;

>> Add >>
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCannotMatchItemTrackingErr(var TempTrackingSpecification: Record "Tracking Specification"; var QtyToHandleToNewRegister: Decimal; var QtyToHandleInItemTracking: Decimal; var QtyToHandleOnSourceDocLine: Decimal)
    begin
    end;
<< Add <<

**Comment by DParkerRSM** [comment]
Can I get an update on this event request?

**Comment by DParkerRSM** [comment]
Can I get an update on this event request?

**Comment by DParkerRSM** [comment]
Can I get an update on this event request?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10481.
