### ISSUE TITLE
CI/CD workflow failing

### ISSUE THREAD

**Issue by PeterConijn** [microsoft/ALAppExtensions#21632]
Recently, the CI/CD workflows for this repo have been failing on multiple PRs with the error below in the step "Calculate Artifact Names"

> The property 'number' cannot be found on this object. Verify that the property exists.
At D:\a\_temp\08d29175-9cdb-428f-a4e6-1bbf36abdd06.ps1:11 char:15
   $ref = "PR$($event.workflow_run.pull_requests[0].number)"
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
     FullyQualifiedErrorId : PropertyNotFoundStrict
 
The compile stage of the app appears to complete successfully.
As Johannes Wikman (GitHub will not allow me to tag him) suggests in his PR #21591:

> I suspect that it is the changes in #21330 that is causing this... Or what do you think, @aholstrup1?
_Originally posted by @jwikman in https://github.com/microsoft/ALAppExtensions/issues/21591

**Comment by aholstrup1** [comment]
Thank you for reporting this :) I believe this happened was failing when we were rolling out build modes to AL-GO. It should be fixed now
