### ISSUE TITLE
ObsoleteTag and pragma's issues in BaseApp

### ISSUE THREAD

**Issue by mberlickas** [microsoft/ALAppExtensions#21636]
Hi, there are some critical issues with pragma's and obsolete tags in BaseApp. As for example I want to expand "Item Cross Reference" table from BC21 version, which is ObsoleteState=Removed:
![image](https://user-images.githubusercontent.com/116627568/210778470-eadff192-0d99-49dd-b98d-22a39b2162b6.png)
However in my extension I receive a warning instead of error which is not how it should work:
![image](https://user-images.githubusercontent.com/116627568/210778969-2211582d-6488-4ef3-850b-a5e9cbacb5d7.png)
As you can see from picture it aims to take TAG18. 
I have read about "preprocessorSymbols" which can be set in app.json, however from extension it can't reach BaseApp pragma's and doesn't work.
Can you take a look into all pragma's in Base application so it would be updated correctly?

**Comment by AlexanderYakunin** [comment]
It is correct for v21. This table is NOT REMOVED yet in v21, but removed in v.22.

**Comment by mberlickas** [comment]
The issue is not about what has been removed, it is about how pragma's are shown in extension. As I stated i shown incorrectly, warning shows tag18 which is not related with BC21 version, it should show an error with TAG21 as stated in object.

**Comment by AlexanderYakunin** [comment]
You should ask this question in AL section, as this is language/compiler related.

**Comment by NKarolak** [comment]
@mberlickas 
This is the deprecation policy in the base app:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-deprecation-guidelines
The preprocessor symbols are set in the base App by Microsoft to plan and test later removals, but they are never activated in the app.json of a released BC version.
It means, that only and always the "#if **not** CLEANxx" part is relevant for you to read.
![image](https://user-images.githubusercontent.com/34504100/210966596-70f9bb15-3b32-4ad9-9e16-af15f81091c5.png)
Looking at the [Item Cross Reference table in BC 21](https://github.com/StefanMaron/MSDyn365BC.Code.History/blob/w1-21/BaseApp/Source/Base%20Application/ItemCrossReference.Table.al) above, we see that the obsolete state is Pending, not Removed.

The current warning you receive is correct. The warnings always contain the version in which ObsoleteState = Pending was first set. And it was first set in BC 18, see [here](https://github.com/StefanMaron/MSDyn365BC.Code.History/blob/w1-18/BaseApp/Source/Base%20Application/ItemCrossReference.Table.al) and compare with [BC 17](https://github.com/StefanMaron/MSDyn365BC.Code.History/blob/w1-17/BaseApp/Source/Base%20Application/ItemCrossReference.Table.al).

However, as Alexander said, the table is to be removed in BC 22 only, the #else part needs to be fixed, to be **set to ObsoleteTag = '22.0' instead.** @JesperSchulz , can you please take over?

**Comment by mberlickas** [comment]
Hi and thanks Natalie for explanation, now it makes more sense why it is showing like that.
