### ISSUE TITLE
[Event Request] table 27 Item - OnAfterIsAssemblyItem

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21631]
```
procedure IsAssemblyItem() Result: Boolean
begin
    Result := "Replenishment System" = "Replenishment System"::Assembly;
    OnAfterIsAssemblyItem(Rec, Result);
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnAfterIsAssemblyItem(Item: Record Item; var Result: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52717.
