### ISSUE TITLE
OnAfterInsertRecord right after commit in CRM sync

### ISSUE THREAD

**Issue by JohnFrostDP** [microsoft/ALAppExtensions#21639]
Hi,

I noticed that the onafterinsertRecord event on the CRM sync is right after a commit. This is very inconvenient when extending the CRM sync. We use this event to add extra data after the insertion of the record. If something fails after the commit, the record is inserted and all other needed information fails. This makes the solution a bit unsafe for transferring all the data. 

Partners need this event before the commit, because in some cases it is necessary that the record needs to be inserted first because of numbering, validation, etc. Of course, workarounds can be thought of, but are really messy and not easy to implement. 

Is it possible to make an extra event right before the commit? Or maybe move it before the commit. If something fails, all inserts will be rolled-back and tried again in next sync. Which is also a lot more data safe.
![image](https://user-images.githubusercontent.com/92578153/210814094-d817c3d8-9336-4d6a-810d-cc3c88cd975c.png)

I am talking about object: codeunit 5345 "Integration Rec. Synch. Invoke"

**Comment by AlexanderYakunin** [comment]
If you need an event, please provide event definition.

**Comment by JohnFrostDP** [comment]
Put the even after the applyconfigtemplate function and before the if <> fail. Please use the same parameters as onAfterInsertRecord in the screenshot. My suggestion would be:
OnAfterInsertBeforeCommit(IntegrationTableMapping: Record "Integration Table Mapping"; var SourceRecordRef: RecordRef; var DestinationRecordRef: RecordRef).

**Comment by JohnFrostDP** [comment]
@AlexanderYakunin is this up for re-evaluation?

**Comment by JohnFrostDP** [comment]
@AlexanderYakunin I am asking again. Is the information i provided enough for you to reevaluate? Is there any wiki how request should be formulated?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13655.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 13708.
