### ISSUE TITLE
Event Request Report 4 "Detail Trial Balance" OnAfterOnPreReport

### ISSUE THREAD

**Issue by zhan-dev** [microsoft/ALAppExtensions#21640]
Hello, could you please add var ExcludeBalanceOnly to exist event OnAfterOnPreReport or make ExcludeBalanceOnly like protected var?

```
trigger OnPreReport()
    begin
        StartDateTime := CurrentDateTime();
        GLFilter := "G/L Account".GetFilters();
        GLDateFilter := "G/L Account".GetFilter("Date Filter");

        OnAfterOnPreReport("G/L Account", ExcludeBalanceOnly); // new change
    end;

[IntegrationEvent(false, false)]
local procedure OnAfterOnPreReport(var GLAccount: Record "G/L Account"; ExcludeBalanceOnly: Boolean) // new change
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52717.
