### ISSUE TITLE
[Remove Scope Request] table 11401 "CBG Statement Line" - InitRecord and other functions

### ISSUE THREAD

**Issue by PeterBizz** [microsoft/ALAppExtensions#21647]
NL localization issue:

OnValidate of field Identification:
```
    ...
    CBGStatementLine := Rec;
    Init();
    InitRecord(CBGStatementLine);
    ... 
```
the function called "InitRecord" has scope OnPrem

``` 
    [Scope('OnPrem')]
    procedure InitRecord(LastRecord: Record "CBG Statement Line")
    begin
        OnBeforeInitRecord(Rec, LastRecord, CBGStatement);
        GetCBGStatementHeader();
    ...
```

This is the case for multiple procedures. 
Is this functionality not te be used OnPrem? 

Would like to be able to use this with Target:Cloud

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52209.
