### ISSUE TITLE
[Event Request] Report 393 - OnBeforeUpdateGnlJnlLineDimensionsFromVendorPaymentBuffer

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#21644]
change parameters from:

local procedure OnBeforeUpdateGnlJnlLineDimensionsFromVendorPaymentBuffer(
 var GenJournalLine: Record "Gen. Journal Line";
 TempVendorPaymentBuffer: Record "Vendor Payment Buffer" temporary;
 SummarizePerVend: Boolean)

to

local procedure OnBeforeUpdateGnlJnlLineDimensionsFromVendorPaymentBuffer(
 var GenJournalLine: Record "Gen. Journal Line";
 TempVendorPaymentBuffer: Record "Vendor Payment Buffer" temporary;
 SummarizePerVend: Boolean;
 DocNoPerLine: Boolean;
 var NextDocNo: Code[20])

This will allow inspection of the Vendor via TempVendorPaymentBuffer; and if vendor has requirements concerning NextDocNo (e.g. they want a single doc no. per invoice, whereas all other vendors are ok with Single doc. no per invoice), it can be handled here.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52728.

**Comment by grantbrimhall** [comment]
@JesperSchulz (Thank you for including build#... so helpful to track when clients are eagerly awaiting. Cheers.)
