### ISSUE TITLE
codeunit 7201 "CDS Integration Impl."

### ISSUE THREAD

**Issue by Random-PasserBy** [microsoft/ALAppExtensions#21646]
When adding functionality extending the dataverse connection it currently appears to be impossible to open the connection to dataverse (on opening custom pages / reports) as all procedures in codeunit 7201 "CDS Integration Impl." are Scope OnPrem. 

Could these procedures be made available for extension development? (Remove Scope OnPrem)

Thanx in advance.

**Comment by dcenic** [comment]
This is covered in https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-custom-cds-integration#to-create-a-list-page-to-display-dataverse-workers 
Look at the code example - the OnInit method has one line - that is the line that registers the connection to Dataverse for a custom object.
