### ISSUE TITLE
[Event Change] table 83 "Item Journal Line" - OnAfterCalcBaseQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#21658]
In the past Event OnAfterCalcBaseQty was made as an event to procedure CalcBaseQty.

There are four calls changed in T83 to accommodate for extra parameters to event OnAfterCalcBaseQty :

"Quantity (Base)" := CalcBaseQty(Quantity, FieldCaption(Quantity), FieldCaption("Quantity (Base)"));

"Invoiced Qty. (Base)" := CalcBaseQty("Invoiced Quantity", FieldCaption(Quantity), FieldCaption("Quantity (Base)"));

"Output Quantity (Base)" := CalcBaseQty("Output Quantity", FieldCaption("Output Quantity"), FieldCaption("Output Quantity (Base)"));

"Scrap Quantity (Base)" := CalcBaseQty("Scrap Quantity", FieldCaption("Scrap Quantity"), FieldCaption("Scrap Quantity (Base)"));

You can see that the call to "Invoiced Qty. (Base)" is incorrect (possibly a copy paste edit error), because it is not using the correct FieldCaption. It should be changed as follows:

"Invoiced Qty. (Base)" := CalcBaseQty("Invoiced Quantity", FieldCaption("Invoiced Quantity"), FieldCaption("Invoiced Qty. (Base)"));

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10481.
