### ISSUE TITLE
Variable CurrentJnlBatchName as Protected

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#21669]
Can you please the Global var CurrentJnlBatchName in Object Page 5636 „FA Reclass. Journal“ set as Protected var ?

    var
        FAReclassJnlManagement: Codeunit FAReclassJnlManagement;
        CurrentJnlBatchName: Code[10];
        FADescription: Text[100];
        NewFADescription: Text[100];
        grec_FA: Record "Fixed Asset";

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
