### ISSUE TITLE
[Event Request] table 290 "VAT Amount Line" - CalcVATFields

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#21660]
We need to be able to exclude certain (sales / purchase /...) lines from the payment discount calculation. E.g. freight charges, some specific items (used for packaging / returnables / ...), account lines of type 'warrant' / guarantee, ... should NOT be included. These lines will be marked with a specific VAT Identifier (E.g. G3* instead of G3) and/or specific VAT Product Posting Group.

However, in the entire BC calculation, payment discount % / VAT Base Discount % is a value on the header which is applied to all lines / VAT amount lines, making it very hard to exclude the lines from receiving the discounted / lowered VAT Base amount. Therefore, we'd like to get certain events to set the percentage fields to 0 for specific VAT Amount lines.

```
procedure CalcVATFields(NewCurrencyCode: Code[10]; NewPricesIncludingVAT: Boolean; NewVATBaseDiscPct: Decimal)
    begin
        OnBeforeCalcVATFields(Rec, NewVATBaseDiscPct); // Add event
        
        InitGlobals(NewCurrencyCode, false);

        "VAT Amount" := GetCalculatedVAT(NewCurrencyCode, NewPricesIncludingVAT, NewVATBaseDiscPct);

        if NewPricesIncludingVAT then begin
            if NewVATBaseDiscPct = 0 then begin
                "Amount Including VAT" := CalcLineAmount();
                "VAT Base" := "Amount Including VAT" - "VAT Amount";
            end else begin
                "VAT Base" :=
                  Round(CalcLineAmount() / (1 + "VAT %" / 100), Currency."Amount Rounding Precision");
                "Amount Including VAT" := "VAT Base" + "VAT Amount";
            end;
        end else begin
            "VAT Base" := CalcLineAmount();
            "Amount Including VAT" := "VAT Base" + "VAT Amount";
        end;
        "Calculated VAT Amount" := "VAT Amount";
        "VAT Difference" := 0;
        Modified := true;

        OnAfterCalcVATFields(Rec, NewPricesIncludingVAT, NewVATBaseDiscPct, Currency);
    end;
```

NewVATBaseDiscPct must be set to **var**, since we'd like to put it to zero based on a condition in Rec.

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeCalcVATFields(var Rec: Record "VAT Amount Line"; var NewVATBaseDiscPct: Decimal)
    begin
    end;
```

@ZepposBE

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52717.
