### ISSUE TITLE
[Event Request] report 780 "Certificate of Supply" - protected variables

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21675]
Reference to the old issue marked as complete:
https://github.com/microsoft/ALAppExtensions/issues/20634
Not included in the Build ID 51464 (Update 3 for BC 2022 Wave 2)

Please set varibles TempServiceShipmentHeader and TempServiceShipmentLine to protected in report 780 "Certificate of Supply"
```
protected var
    TempServiceShipmentHeader: Record "Service Shipment Header" temporary;
    TempServiceShipmentLine: Record "Service Shipment Line" temporary;
```

**Comment by AlexanderYakunin** [comment]
Done for master, please do not expect External requests to appear in PROD versions.
