### ISSUE TITLE
[Extensibility Request] Table 472 "Job Queue Entry" - CleanupAfterExecution

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21674]
Reference to the old issue marked as complete:
https://github.com/microsoft/ALAppExtensions/issues/20040
Not included in the Build ID 51464 (Update 3 for BC 2022 Wave 2)

Please make function CleanupAfterExecution externally available.
```
procedure CleanupAfterExecution()
var
    JobQueueDispatcher: Codeunit "Job Queue Dispatcher";
    SessionId: Integer;
    IsHandled: Boolean;
begin
```

**Comment by AlexanderYakunin** [comment]
This is done for v.22
