### ISSUE TITLE
[Exposure Request] Table 27 "Item" - variables ItemTrackingCode and ItemTrackingCode2

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21677]
Reference to the old issue marked as complete:
https://github.com/microsoft/ALAppExtensions/issues/20228
Not included in the Build ID 51464 (Update 3 for BC 2022 Wave 2)

Please mark variables ItemTrackingCode and ItemTrackingCode2 as protected variables so that those can be used on table extension.

**Comment by AlexanderYakunin** [comment]
This is done for v.22
