### ISSUE TITLE
[extensibility-bug] IsDefaultDimDefinedForTable skips event OnAfterInitDefaultDimensionSources in "Sales Line" & "Purchase Line"

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#21673]
We have a problem with the new function "IsDefaultDimDefinedForTable" in CreateDimFromDefaultDim. 
In BC 21.3 (we detected in our Next-Major CI-Test) you added a check on existing default dimensions before Init Default Dimension Sources:

![image](https://user-images.githubusercontent.com/34675109/211307076-01ae47ce-69f4-40c3-8946-38380346606b.png)

I Think I understand why you added this check. Because it's only necessary to overwrite default dimensions with line info if exists.
The problem is that our subscriber who added more Dimension Sources are not fired anymore as well.

This is the publisher we subscribed:
![image](https://user-images.githubusercontent.com/34675109/211307385-0d37c32e-c5fe-46c1-b306-1f96bd8f7f76.png)

I'm not sure what the solution is. In my opinion the check must be after the "InitDefaultDimensionSources" to check if any additional dim sources were added.
If not, we need at least an event to skip the check.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 20.

Build ID to track: 53033.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53041.
