### ISSUE TITLE
[Event Request] codeunit 6529 "Item Tracking Navigate Mgt." - OnBeforeFindJobLedgEntry

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21679]
Reference to the old issue marked as complete:
https://github.com/microsoft/ALAppExtensions/issues/19905
Not included in the Build ID 51464 (Update 3 for BC 2022 Wave 2)
please include sender in the event OnBeforeFindJobLedgEntry

```
[IntegrationEvent(true, false)]
local procedure OnBeforeFindJobLedgEntry(var TempJobLedgEntry: Record "Job Ledger Entry" temporary; var ItemFilters: Record Item; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52728.
