### ISSUE TITLE
[Exposure Request] [DE] report 11003 "Customer Total-Balance" - protected variables

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21689]
Reference to the old issues marked as complete:
https://github.com/microsoft/ALAppExtensions/issues/20628
Not included in the Build ID 51464 (Update 3 for BC 2022 Wave 2)

Please set variables PeriodEndBalance and EndBalanceType to protected in report 11003 "Customer Total-Balance" - german localization.

```
protected var
    PeriodEndBalance: Decimal;
    EndBalanceType: Option " ",Debit,Credit;

```

**Comment by AlexanderYakunin** [comment]
This is fixed in v.22
