### ISSUE TITLE
[Extensibility Request] Page 498 Reservation - Expose Methods

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21681]
Reference to the old issue marked as complete:
https://github.com/microsoft/ALAppExtensions/issues/20251
Not included in the Build ID 51464 (Update 3 for BC 2022 Wave 2)

Please expose following methods in page 498 as global procedures as the functions may be used when sender from the Events is being used. Currently those are set to protected:

```
procedure FilterReservEntry(var FilterReservEntry: Record "Reservation Entry"; ReservEntrySummary: Record "Entry Summary")
begin
```
```
procedure UpdateReservFrom()
var
```

**Comment by AlexanderYakunin** [comment]
This is done for v.22
