### ISSUE TITLE
codeunit 5057 "VendCont-Update" - InsertNewContact function 

### ISSUE THREAD

**Issue by yildiz-ozdemir** [microsoft/ALAppExtensions#21682]
Hi,

Could you add OnAfterContactInsert event after Insert line in codeunit 5057 "VendCont-Update" - InsertNewContact function.
I need this because when I want to use OnAfterInsert events belongs to Contact table, it did not trigger from api pages. 

Thank you.

![image](https://user-images.githubusercontent.com/49477543/211317434-6b0c085f-66da-4015-9693-1e034adb7a6d.png)

**Comment by AlexanderYakunin** [comment]
Sure, if you provide event parameters

**Comment by yildiz-ozdemir** [comment]
OnAfterContactInsert(Cont,Vend);

    [IntegrationEvent(true, false)]
    local procedure OnAfterContactInsert(var Cont: Record "Contact"; var Vend: Record "Vendor")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11030.
