### ISSUE TITLE
[Extensibility Request] page 5098 "Task Card" - EnableFields

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21687]
Reference to the old issue marked as complete:
https://github.com/microsoft/ALAppExtensions/issues/20252
Not included in the Build ID 51464 (Update 3 for BC 2022 Wave 2)

Please expose method EnableFields in page 5098 as global procedures as the function may be used when sender from the Events is being used.

**Comment by AlexanderYakunin** [comment]
This is done for v.22
