### ISSUE TITLE
[Event Request] Report 11971 "Calc. and Post VAT Settl. CZL"."Close VAT Entries".OnAfterGetRecord

### ISSUE THREAD

**Issue by michalone** [microsoft/ALAppExtensions#21680]
In specific cases, Czech legislation requires different reporting of input VAT in case of transferred tax liability - reverse charge. If the payer does not carry out an economic activity, it is not possible to claim a tax deduction on the input. Correct VAT reporting can be ensured by changes in standard VAT setup. What cannot be ensured by any setup is the function Calculate and Post VAT Settlement. That´s why we need to do the changes to this function but there are missing needed events.

Please add publisher after CopyAmounts in "Reverse Charge VAT" case for purchase entry type. E.g.:

```
"VAT Posting Setup"."VAT Calculation Type"::"Reverse Charge VAT":
    case VATType of
        VATEntry.Type::Purchase:
            begin
                GenJournalLine."Account No." := GetVATAccountNo(VATEntry, "VAT Posting Setup");
                CopyAmounts(GenJournalLine, VATEntry);
                // requested event:
                OnBeforePostGenJnlLineReverseChargeVATAccount(GenJournalLine, VATEntry, VATAmount, VATAmountAddCurr);
                if PostSettlement then
                    PostGenJnlLine(GenJournalLine);

                CreateGenJnlLine(SecondGenJournalLine, "VAT Posting Setup".GetRevChargeAccount(false));
                SetVatPostingSetupToGenJnlLine(SecondGenJournalLine, "VAT Posting Setup");
                if PostSettlement then
                    PostGenJnlLine(SecondGenJournalLine);
                ReversingEntry := true;
            end;
        VATEntry.Type::Sale:
            begin
                GenJournalLine."Account No." := GetVATAccountNo(VATEntry, "VAT Posting Setup");
                CopyAmounts(GenJournalLine, VATEntry);
                if PostSettlement then
                    PostGenJnlLine(GenJournalLine);
            end;
    end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforePostGenJnlLineReverseChargeVATAccount(var GenJournalLine: Record "Gen. Journal Line"; VATEntry: Record "VAT Entry"; var VATAmount: Decimal; var VATAmountAddCurr: Decimal)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10286.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 55135.
