### ISSUE TITLE
[Exposure Request] codeunit 64 "Sales-Get Shipment" - expose functions

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21683]
Reference to the old issues marked as complete:
https://github.com/microsoft/ALAppExtensions/issues/19992
https://github.com/microsoft/ALAppExtensions/issues/19993
https://github.com/microsoft/ALAppExtensions/issues/19994
https://github.com/microsoft/ALAppExtensions/issues/19995
Not included in the Build ID 51464 (Update 3 for BC 2022 Wave 2)

Please make following functions externally available:
InsertInvoiceLineFromShipmentLine
UpdateItemChargeLines
CalcInvoiceDiscount
AdjustPrepmtAmtToDeductRounding

**Comment by AlexanderYakunin** [comment]
We never provide external requests for already released versions, we only do this for next major release.
