### ISSUE TITLE
[Exposure Request] [DE] report 11002 "G/L Total-Balance" - protected variables

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#21690]
Reference to the old issues marked as complete:
https://github.com/microsoft/ALAppExtensions/issues/20630
Not included in the Build ID 51464 (Update 3 for BC 2022 Wave 2)

Please set varibles PeriodEndBalance and EndBalanceType to protected report 11002 "G/L Total-Balance" - german localization.

```
protected var
    PeriodEndBalance: Decimal;
    EndBalanceType: Option " ",Debit,Credit;
```

**Comment by AlexanderYakunin** [comment]
This is fixed in v.22
