### ISSUE TITLE
Сreate Event Request Table 39 "Purchase Line"  OnBeforeHandleDedicatedBin

### ISSUE THREAD

**Issue by Paskyal** [microsoft/ALAppExtensions#21695]
Hello, could you please create OnBeforeHandleDedicatedBin event in the GetDefaultBin procedure in the table 39 "Purchase Line"?

[IntegrationEvent(false, false)]
local procedure OnBeforeHandleDedicatedBin (var PurchaseLine: Record "Purchase Line"; var xPurchaseLine: Record      "Purchase Line")
    begin

    end;

local procedure GetDefaultBin()
    var
        WMSManagement: Codeunit "WMS Management";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetDefaultBin(Rec, IsHandled, xRec);
        if IsHandled then
            exit;

        if (Type <> Type::Item) or IsNonInventoriableItem() then
            exit;

        "Bin Code" := '';
        if "Drop Shipment" then
            exit;

        if ("Location Code" <> '') and ("No." <> '') then begin
            GetLocation("Location Code");
            if Location."Bin Mandatory" and not Location."Directed Put-away and Pick" then begin
                WMSManagement.GetDefaultBin("No.", "Variant Code", "Location Code", "Bin Code");
                OnBeforeHandleDedicatedBin(Rec, xRec);   /// NEW EVENT
                HandleDedicatedBin(false);
            end;
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52831.
