### ISSUE TITLE
Filter criteria is processed differently with Edit in Excel than on UI pages when using combined format expressions

### ISSUE THREAD

**Issue by vukbssi** [microsoft/ALAppExtensions#21693]
On a list page, when a filter is set on a field with the Either/Or (|) **and** closed Interval (..) operators, the filtered list in Edit in Excel does not match the page, as it seems to only apply one of the filters.
[https://learn.microsoft.com/en-us/dynamics365/business-central/ui-enter-criteria-filters#combined-format-expressions](https://learn.microsoft.com/en-us/dynamics365/business-central/ui-enter-criteria-filters#combined-format-expressions)

For example, on the Purchase Invoices page:

Setting the following filter on field "Buy-from Vendor No." works as expected on the page, and in Edit in Excel; showing all invoices matching the three Vendors:
**10000|30000|40000**

![image](https://user-images.githubusercontent.com/69273853/211437191-d13062a2-9a49-4cb9-8369-bf1e12511510.png)

**However**, setting the following similar filter on field "Buy-from Vendor No." works as expected on the page, but not in Edit in Excel where only invoices matching Vendor 10000 are shown:
**10000|30000..40000**
		
![image](https://user-images.githubusercontent.com/69273853/211437251-bc2723e3-eadc-44cf-8fda-2f0f0849e96d.png)

Version: US Business Central 21.3 (Platform 21.0.51393.51624 + Application 21.3.51409.51575)

**Comment by AlexanderYakunin** [comment]
Sorry, this forum is not suitable for bug reporting and should be used for extensibility related requests. If you have issues like this, should you report it to technical support to get the fix?
