### ISSUE TITLE
Сreate Event Request Table 5406 "Prod. Order Line" OnBeforeValidateRoutingNo

### ISSUE THREAD

**Issue by Paskyal** [microsoft/ALAppExtensions#21696]
Hello, could you please create OnBeforeValidateRoutingNo event in the OnValidate trigger of the field "Routing No." in the table 5406 "Prod. Order Line"?

[IntegrationEvent(false, false)]
    local procedure OnBeforeValidateRoutingNo(var ProdOrderLine: Record "Prod. Order Line"; xProdOrderLine: Record "Prod. Order Line"; CurrFieldNo: Integer; CheckCapLedgEntry: Boolean; CheckSubcontractPurchOrder: Boolean; var IsHandled: Boolean)
    begin
    end;

trigger OnValidate()
            var
                RoutingHeader: Record "Routing Header";
                ProdOrderRoutingLine: Record "Prod. Order Routing Line";
                CapLedgEntry: Record "Capacity Ledger Entry";
                PurchLine: Record "Purchase Line";
                ModifyRecord: Boolean;
                IsHandled: Boolean; /// NEW var
            begin
                IsHandled := false;
                OnBeforeValidateRoutingNo(Rec, xRec, CurrFieldNo, CheckCapLedgEntry, CheckSubcontractPurchOrder,IsHandled);
                if IsHandled then
                    exit;
                "Routing Version Code" := '';

                if "Routing No." <> xRec."Routing No." then begin
                    if Status = Status::Released then begin
                        if CheckCapLedgEntry then
                            Error(
                              Text99000004Err,
                              FieldCaption("Routing No."), xRec."Routing No.", CapLedgEntry.TableCaption);

                        if CheckSubcontractPurchOrder then
                            Error(
                              Text99000004Err,
                              FieldCaption("Routing No."), xRec."Routing No.", PurchLine.TableCaption);
                    end;

                    ModifyRecord := false;
                    OnBeforeDeleteProdOrderRtngLines(Rec, ModifyRecord);
                    if ModifyRecord then
                        Modify;

                    ProdOrderRoutingLine.SetRange(Status, Status);
                    ProdOrderRoutingLine.SetRange("Prod. Order No.", "Prod. Order No.");
                    ProdOrderRoutingLine.SetRange("Routing No.", xRec."Routing No.");
                    ProdOrderRoutingLine.SetRange("Routing Reference No.", "Line No.");
                    ProdOrderRoutingLine.DeleteAll(true);

                    OnAfterDeleteProdOrderRtngLines(Rec);
                end;
                if "Routing No." = '' then
                    exit;

                Validate("Routing Version Code", VersionMgt.GetRtngVersion("Routing No.", "Due Date", true));
                if "Routing Version Code" = '' then begin
                    RoutingHeader.Get("Routing No.");
                    RoutingHeader.TestField(Status, RoutingHeader.Status::Certified);
                    "Routing Type" := RoutingHeader.Type;
                end;
            end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52181.
