### ISSUE TITLE
EFT file -> stream

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#21699]
Hello, 
When an EFT file is created from Payment Journal, it uses the OnPrem procedure for download. we need not to download the file, but to send it to Azure storage and do further integrations. There is a publisher (line 196)
![image](https://user-images.githubusercontent.com/34686682/211491495-20724c49-ce68-43de-bfaa-de7a44894564.png)

where I can access the path to the file, but all procedures for working with files are tagged as OnPrem and there is no way to convert a file into the stream.
Could this be refactored to support cloud solutions?

I see in insider version 22, there is a new publisher in codeunit 10094 "Export EFT (ACH)"
![image](https://user-images.githubusercontent.com/34686682/211569693-7a823983-e785-415c-b911-e7ad5b80b2f5.png)
but TempNameValueBuffer."Value Blob" remains empty, it is not populated with a file content in previous steps of EFT file generation process, in codeunit 10094 "Export EFT (ACH)":
![image](https://user-images.githubusercontent.com/34686682/211571286-d4a9aaa6-2c4e-4eee-a823-60e11c37cd6a.png)
Maybe you could here update a content of "Value Blob" from the file which is specified in TempNameValueBuffer.Value field.

Thank you,
Radovan Dokić

**Comment by radovandokic** [comment]
Hi, what do you think, can we expect this at some point?

**Comment by JathanMoline** [comment]
I'm also in need of access to the stream.   
But my requirements are to encrypt the EFT prior to downloading so it can be forwarded to the bank.  

Rather than redirect, I want to have the opportunity to modify.  
 
Need a way to intercept the file and pass it to a separate service.  I will encrypt the EFT before the user downloads it.
This ticket appears to redirect the stream where I would redirect, modify, then continue downloading.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
