### ISSUE TITLE
[Extensibility Request] Make the TableRelation property of fields FULLY modifiable

### ISSUE THREAD

**Issue by Kryshi** [microsoft/ALAppExtensions#21698]
Hey there, I've been running into this issue more and more. Let's say I have a field, which has a standard defined TableRelation to the Item Table. I want to modify the TableRelation so that it points to a different table, if some condition is fulfilled. What I can do now is to essentially add a new TableRelation condition at the end, but I cannot overwrite the standard TableRelation, so this field will ALWAYS point to the Item table.

**Comment by AlexanderYakunin** [comment]
Hello! I don't think it is possible to make this kind of change in general. Maybe you need different design for your purpose? Do you have specific case to think about?

**Comment by Kryshi** [comment]
Thanks for the response. My case is this: I have extended the Item Unit of Measure table with an option field with 2 choices. Depending on the value in this field, I would like to have the "Item No." field have a table relation to either the Item table, or my custom table that I have created. By default, the Item No. field has the property "TableRelation = Item" and there is nothing I can do to change this to anything else. This is part of a migration project from NAV, where the "Item No." has the TableRelation property customised in the desired way.

**Comment by JesperSchulz** [comment]
Interesting idea! Unfortunately, this repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

For suggestions to the Business Central product group, please create a [BC Idea](https://aka.ms/bcideas).
