### ISSUE TITLE
Modify the Existing Integration Event in Codeunit 80

### ISSUE THREAD

**Issue by AshuBansal01** [microsoft/ALAppExtensions#21702]
Hi Team,
I need to modify the Existing Integration Event in CU-80.
Current Process:
Object Type: Codeunit
Object Name: Sales-Post
Function Name: SumSalesLines2
			  
                     if InsertSalesLine then begin
                        NewSalesLine := SalesLine;
                        OnSumSalesLines2OnBeforeNewSalesLineInsert(NewSalesLine);
                        NewSalesLine.Insert();
                    end;
![image](https://user-images.githubusercontent.com/96677845/211615863-9d73db89-ff84-4e39-b93f-7d028b43bfba.png)

[IntegrationEvent(false, false)]
    local procedure OnSumSalesLines2OnBeforeNewSalesLineInsert(var NewSalesLine: Record "Sales Line")
    begin
    end;

Required Changes:

Object Type: Codeunit
Object Name: Sales-Post
Function Name: SumSalesLines2

			  if InsertSalesLine then begin
				IsHandled := False;  //New Code
                        NewSalesLine := SalesLine;
                        OnSumSalesLines2OnBeforeNewSalesLineInsert(NewSalesLine,IsHandled); // Added IsHandled as a New Parameter
                        if not IsHandled then //New Code
  			    NewSalesLine.Insert();
                    end;
[IntegrationEvent(false, false)]   // Modified by adding IsHandled Parameter
    local procedure OnSumSalesLines2OnBeforeNewSalesLineInsert(var NewSalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by AshuBansal01** [comment]
@AlexanderYakunin Can you Please add the requested event asap?

**Comment by AlexanderYakunin** [comment]
Any justification for this ask? Which version are you asking?

**Comment by AshuBansal01** [comment]
While opening the Statistics Page on the Sales Order, I am getting the Error Sales Lines already Exist, it might be because of non-Microsoft extensions installed. So, we wanted to add some conditions before inserting the records into the Sales Line. That's why we requested to modify that event.
 I am using Version 21.2 BC SaaS.

**Comment by AshuBansal01** [comment]
Hi Team, any update on the above ask?

**Comment by AlexanderYakunin** [comment]
First of all, why this ask should take priority for any other asks here? Any justification please? If this is customer issue, why you didn't create service request via technical support? We have no SLA for processing event requests and currently have large backlog of much order requests here.

And I think this is not going to solve your issue, should you debug this issue first and understand who is adding another sales line here?

**Comment by AshuBansal01** [comment]
We created a service request, but it was working fine in the demo tenant without non-Microsoft applications. We have tested with non-Microsoft applications then we were able to replicate the Issue. In the Customer DB some modifications is done in the base object, to do the same in BC we are required to modify the base existing event. it would be helpful for us if the request is taken care.
