### ISSUE TITLE
[Extensibility Enhancement] Codeunit 7312 Create Pick in Function FindBWPickBin

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#21719]
Requesting additional parameters in existing Publisher **OnBeforeSetBinCodeFilter** called in Function **FindBWPickBin** In **Codeunit 7312 Create Pick**.

I wonder what the IsHandled parameter is for because in the current implmentation when you set IsHandled to true in a subscriber no filters will be set on BinContent.

Existing Publisher:
`
[IntegrationEvent(false, false)]
`
`
local procedure OnBeforeSetBinCodeFilter(var BinCodeFilterText: Text[250]; LocationCode: Code[10]; ItemNo: Code[20]; 
VariantCode: Code[10]; ToBinCode: Code[20]; var IsHandled: Boolean)
begin
end;
`

Modified Publisher:
`
[IntegrationEvent(false, false)]
`
`
local procedure OnBeforeSetBinCodeFilter(var BinCodeFilterText: Text[250]; LocationCode: Code[10]; ItemNo: Code[20]; VariantCode: Code[10]; ToBinCode: Code[20]; var IsHandled: Boolean; SourceType: Integer; SourceSubType: Option; SourceNo: Code[20]; SourceLineNo: integer; SourceSubLineNo: integer)
begin
end
`

We need these parameters because we need to get the related source document to determine if its a special order and do some other filtering to change the BinContent records that will be filtered.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52253.
