### ISSUE TITLE
[Access Request] table 37 "Sales Line"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#21717]
Could you please move the SalesHeader to the protected variables?
```al
    protected var
        HideValidationDialog: Boolean;
        StatusCheckSuspended: Boolean;
        PrePaymentLineAmountEntered: Boolean;
        SkipTaxCalculation: Boolean;
//+Change
        SalesHeader: Record "Sales Header";
//-Change
```

**Comment by MarkoTrn** [comment]
Hello,

Can you use global procedure GetSalesHeader defined under the Sales Line table?

**Comment by pri-kise** [comment]
The problem I have is, that the method GetSalesHeader does a record assignment.
Therefore any global variables on the Global SalesHeader are lost when the Global SalesHeader is assigned to the SalesHeader instance.
This is currently a plattform limitation an the only way to work around this issue is by using the same SalesHeader Instance.

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot do this change. It require refactoring of our app and demo tool code as internal SalesHeader variable become visible in their scope, and we get unexpected errors.
