### ISSUE TITLE
GetEmailAccount returns true even if scenario is not assigned.

### ISSUE THREAD

**Issue by mundanebcdev** [microsoft/ALAppExtensions#21718]
In the codeunit 8893 "Email Scenario" procedure GetEmailAccount will return true even if the requested scenario is not assigned. Provided that the default one exists.
Please see Line 30 of codeunit 8892 "Email Scenario Impl.". The return value should be false, as this case is invoked if the requested scenario is not assigned.
![image](https://user-images.githubusercontent.com/89254286/211850656-31b76724-25c4-4699-883a-acb3e5c5bb58.png)

Internal work item: [AB#524050](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524050)

**Comment by pri-kise** [comment]
@MakGM-FORTO that would be a breacking change, since the current behaviour is defined in the documentation.

```al
/// <summary>
/// Gets the email account used by the given email scenario.
/// If the no account is defined for the provided scenario, the default account (if defined) will be returned.
/// </summary>
/// <param name="Scenario">The scenario to look for.</param>
/// <param name="EmailAccount">Out parameter holding information about the email account.</param>
/// <returns>True if an account for the specified scenario was found; otherwise - false.</returns>
procedure GetEmailAccount(Scenario: Enum "Email Scenario"; var EmailAccount: Record "Email Account"): Boolean
begin
    exit(EmailScenarioImpl.GetEmailAccount(Scenario, EmailAccount));
end;
```

**Comment by MakGM-FORTO** [comment]
It should return the default account, but why with 'true'?

**Comment by MakGM-FORTO** [comment]
Isn`t that why we have two procedures GetDefaultEmailAccount and GetEmailAccount?

**Comment by MakGM-FORTO** [comment]
By the way, as you mentioned 'True if an account for the specified scenario was found;' In my case it is not found or am I misunderstanding what 'found' means?

**Comment by MakGM-FORTO** [comment]
I just want to check if there is an email account for the given scenario. But I can`t find a way to do it

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 18930.
