### ISSUE TITLE
codeunit::ReportManagement.OnCustomDocumentMergerEx() is not triggered when expected

### ISSUE THREAD

**Issue by justlucdewit** [microsoft/ALAppExtensions#21737]
In our codebase we were using the `codeunit::"Document Report Mgt.".OnBeforeMergeDocument` to take out the XML and send it to a webservice, when you go to any report, and do `print/send > print` or `print/send > preview`. This has worked great except for the fact that the chosen printer is only send by the arguments of the function if you pressed `print` but not if you pressed `preview`

The old event looked like this:
```
[EventSubscriber(ObjectType::Codeunit, Codeunit::"Document Report Mgt.", 'OnBeforeMergeDocument', '', true, true)]
local procedure OnBeforeMergeDocument(ReportID: Integer; ReportAction: Option; InStrXmlData: InStream; PrinterName: Text; OutStream: OutStream; var Handled: Boolean)
var
    OurApp: Codeunit "OurApp Connector";
begin
    Handled := true; // Set it to handled to cut off BC from generating any report
    OurApp.GenerateReport(...) // Generate the pdf manually by sending the XML to our own webserver
end;
```

However another issue is that this event has been Obsoleted for a while, and replaced with `codeunit::ReportManagement.OnCustomDocumentMerger()` which in turn was replaced with `codeunit::ReportManagement.OnCustomDocumentMergerEx()`.

The issue is, that unlike the OnBeforeMergeDocument event, the OnCustomDocumentMergerEx event doesnt trigger when i go to `print/send > print`

Am I misunderstanding when this event is triggered? Surely there should be a way to trigger the event, right? How could i replicate the old behaviour without the obsoleted event?

**Comment by rvanbekkum** [comment]
Hi @justlucdewit,

You can read more on the `OnCustomDocumentMergerEx` event in the online docs here: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-oncustomdocumentmergerex-event

It is intended for implementing a rendering implementation for a layout with Layout Format = Custom (aka "External") in the "Report Layouts" page (there is a sample in the docs).
The event was introduced with BC20 and since then it was not possible to use the `OnBeforeMergeDocument` event anymore (it was marked obsolete, but actually not available to use anymore, unless you toggled a setting on the server instance, ... which would only be possible for BC on-premise deployments, but not for BC online).

Also good to know: Please note that now (starting from BC21) the behaviour depends on whether "application rendering for Word layouts" in the _Feature Management_ page is enabled or disabled, which affects whether the `OnBeforeMergeDocument` event will be triggered or not. This 'feature' that allows you to temporarily switch back to 'the old implementation' (until Microsoft removes the obsoleted implementation) was introduced with BC21 (but ... also, know that there are some problems with the feature switch, see: https://www.yammer.com/dynamicsnavdev/threads/2020028553166848).

**Comment by justlucdewit** [comment]
@rvanbekkum thank you for your response,

What I noticed is that the `OnBeforeMergeDocument ` still worked for us, although the Feature Management page setting you just mentioned is a known thing for me,  and it doesn't work without it.

The reason I decided to change to the new `OnCustomDocumentMergerEx` event was mainly because 2 reasons
a) get rid of the dependency on the obsoleted event
b) the OnCustomDocumentMergerEx only sends the printername if you press print, but not when you press preview (I explicitly need it in both cases, and I was hoping that since the new event works with a ObjectPayload instead, it would just *always* send it, **could you validate for me if this will be the case in the new event, and if not, how should I do it instead?**)

also, since the OnCustomDocumentMergerEx was not triggering for me when I do print, could this have to do with that Feature Management setting?

**Comment by rvanbekkum** [comment]
> the OnCustomDocumentMergerEx only sends the printername if you press print, but not when you press preview (I explicitly need it in both cases, and I was hoping that since the new event works with a ObjectPayload instead, it would just always send it, could you validate for me if this will be the case in the new event, and if not, how should I do it instead?)

If I choose _Preview_ on a report request page, whilst using a "Cloud Printer" (e.g., "E-mail Printer" as an example) then it looks like it gives you the printer name in the `ObjectPayLoad` just fine:

```json
{
    // ... other properties
    "printername": "MYEMAILPRINTER",
    "duplex": false,
    "color": false,
    "defaultcopies": 1,
    "papertray": null,
    "intent": "Preview",
    // ... other properties
}
```

![image](https://user-images.githubusercontent.com/7383241/212283822-f2e829b6-44c5-4208-b471-24cc07884c9b.png)

> also, since the OnCustomDocumentMergerEx was not triggering for me when I do print, could this have to do with that Feature Management setting?

Possibly, I know there are some things that are not triggered depending on the switch/toggle/flag in Feature Management.

**Comment by justlucdewit** [comment]
> then it looks like it gives you the printer name in the ObjectPayLoad just fine
Wow, that seems to be awesome and exactly what I need

The only thing I need now, is the OnCustomDocumentMergerEx to be actually triggering, I tried setting the  "application rendering for Word layouts" setting in the Feature Management page to 'all users' like you mentioned, and it changed things, yet not in the way id hoped

With that setting on, and my account being reloaded by logging out and logging back in, I can now go to posted sales invoices, and go to print/send, then select a printer and press the `print` button, BC will think for like 1 second, and then send me to this very non helpfull error page, and my debugger will spontaneously quit

![image](https://user-images.githubusercontent.com/37410843/212306704-62c7b7c8-3d49-42d3-90c4-4750d0c979c2.png)

Very weird

**Comment by rvanbekkum** [comment]
If you use 'application rendering', then you will run into that issue when running a report with a Word report layout. I think it is a bug I have also reported on Microsoft Collaborate (see https://www.yammer.com/dynamicsnavdev/threads/2020028553166848).
Application rendering is obsoleted though, and platform rendering will become/is the replacement for Word rendering.

Note though, that OnCustomDocumentMergerEx is intended for implementing a renderer for new layout types, not for hooking into the rendering process of existing layout types like Word.
If you're trying to support a new layout type, then you can use OnCustomDocumentMergerEx event and read in the docs how to add support for a new layout type.

**Comment by justlucdewit** [comment]
What exactly do you mean with 'new layout types'? right now, we indeed have the report 1306 configured as a custom word layout (see screenshots)

![image](https://user-images.githubusercontent.com/37410843/212322102-57a8fec1-eef2-44da-bb9a-c3e939ef06c7.png)
![image](https://user-images.githubusercontent.com/37410843/212322393-1bcae4ea-9800-429c-8df8-c287c64f4b26.png)

am i being troubled by the bug u were describing? if so, are there ways around?

**Comment by rvanbekkum** [comment]
The `OnCustomDocumentMergerEx` event is intended for use with the new report layout tables, not with the legacy Custom Report Layout table (N.B. Microsoft is slowly moving away from the Custom Report Layout table in favor of the new report layout tables - the table is not obsoleted yet, which has its reasons as well...).

**Comment by rvanbekkum** [comment]
The `Report Layout` table is not a new table. The new tables are used by the `Report Layouts` page (`Report Layout Definition`, `Tenant Report Layout` and an auto-populated/virtual table `Report Layout List`), which supports 4 types/formats of layouts, RDLC, Word, Excel and External/Custom.
The docs page about the OnCustomDocumentMergerEx event provides you with all the further information you should need if you would like to implement a custom renderer.

**Comment by justlucdewit** [comment]
Small update: I got the event to work, very much thank you for that, i don't think I would've fixed this without your help

anyways, it only works when i enter a new report layout in the `report layout` page, using the new layout button:
![image](https://user-images.githubusercontent.com/37410843/213489002-87b8578c-3f38-4a44-8152-4bf7eeda958d.png)

However, the issue I'm having now is that i cant seem to do this action programmatically. Im trying to insert an entry in the `Report Layout List` table, but it says I cant because the table is read only

Do i have to put it in a different table? It does work when i do it manually via the button in the image

**Comment by justlucdewit** [comment]
Closing this issue considering its now resolved
