### ISSUE TITLE
A secure channel could no be established: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by antonioaayala** [microsoft/ALAppExtensions#21734]
### Discussed in https://github.com/microsoft/ALAppExtensions/discussions/21733

<div type='discussions-op-text'>

<sup>Originally posted by **antonioaayala** January 12, 2023</sup>
Hello,

I have an issue calling API from AL on SaaS, when I deploy my app on docker Onpremise container Client.Send works correctly, but whe i deploy to production or Sandox on SaaS, I got the error "Could not create SSL/TLS secure channel...."

My code is

var
    CB64: Codeunit "Base64 Convert";
    Client: HttpClient;

    Request: HttpRequestMessage;
    Content: HttpContent;
    Response: HttpResponseMessage;
    RequestHeaders: HttpHeaders;
    ContentHeaders: HttpHeaders;
    CertString: Text;
    ContentString: Text;
    ResponseString: Text;
    AuthString: Text;

begin
    Clear(Client);

    Request.SetRequestUri('https');
    Request.Method := 'GET';

    AuthString := 'Basic xxxxxxxxxxxxxxxxxx';
    Client.DefaultRequestHeaders.Add('Authorization', AuthString);
    Client.DefaultRequestHeaders.Add('User-Agent', 'Dynamics 365');
    Client.Get('https', Response);

    Response.Content.ReadAs(ResponseString);
    Message(Format(Response.HttpStatusCode));
    message(ResponseString);
end;
I have tried wiht Client.Send to

Thanks a lot</div>

**Comment by antonioaayala** [comment]
Hello,

IF external Endpoint use a SSL Certificate and has activated TSL 1.3 it works. But if TSL active is 1.2 or lower doesn't work.It only happens on SaaS environments, OnPremise doesn't happens.

Thanks

**Comment by AlexanderYakunin** [comment]
Hello! You are using wrong place to raise this issue. We are processing extensibility requests here, you should create support request (ICM) to get this fixed or get help.

**Comment by antonioaayala** [comment]
Ok , thanks
