### ISSUE TITLE
[Application Bug] Update the ShowMandatory expression on the No. field on sales / purchase subforms

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#21735]
The "Sales Line Type" field is an extensible enum, allowing us to add new options such as "**Internal Comment**". Via the `OnAfterHasTypeToFillMandatoryFields` on table "Sales Line", we're able to bypass the FillMandatoryFields check.

However, on the sales/purchase subforms, the `ShowMandatory` property of the `No.` field does not use this function.

We'd like BC to replace the condition (`Type <> Type::" ";`) by the `HasTypeToFillMandatoryFields` return value instead (which is already available on most pages via the `IsCommentLine` variable.)

![image](https://user-images.githubusercontent.com/25268332/212047595-a6d3bde6-1f49-4e8c-a617-5d09cc06e225.png)

So can you please review below pages ...

![image](https://user-images.githubusercontent.com/25268332/212048682-d427be03-2056-4f27-a38d-530098107b03.png)

... and change the property to 

`ShowMandatory = not IsCommentLine;`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53916.
