### ISSUE TITLE
[Application Bug] Purchase line description should use language of purchase header when getting return shipments

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#21741]
Following the '**Get Receipts**' function which creates purchase lines with a preceding line stating 'Receipt No. : %1' in the language of the purchase document, the same should be applied to the '**Get Return Shipments**' as well.

Now a purchase line with description 'Return Shipment No. %1' is added in the language of the **user** instead of the language of the **purchase document**.

![image](https://user-images.githubusercontent.com/25268332/212324782-14ffce74-7e3c-45f0-a847-2255f67e5bfe.png)

Suggested fix in table 6651

Before

_PurchLine.Description := StrSubstNo(Text000, "Document No.");_

After

_TranslationHelper.SetGlobalLanguageByCode(PurchHeader."Language Code");
PurchLine.Description := StrSubstNo(Text000, "Document No.");
TranslationHelper.RestoreGlobalLanguage();_

**Comment by AlexanderYakunin** [comment]
What happens if Text000 does not have translation for PurchHeader."Language Code"? Anyway, this is not an extensibility issue, but functional request which we cannot do.
