### ISSUE TITLE
codeunit 1303 "Correct Posted Sales Invoice" and 229 "Document-Print" new events

### ISSUE THREAD

**Issue by GregorJacobsen** [microsoft/ALAppExtensions#21744]
Hi @JesperSchulz 
this is more a question than a event request. Two event requests are listed below, that were approved ,marked as "Ships-in-future-update" (2-3 Month ago) and announced for specific builds (46663,48444) that i can't find in the latest public (21.3.51409.51464)  or the latest insider version (22.0.52025.0). Can You please provide an estimate when they will be available?

https://github.com/microsoft/ALAppExtensions/issues/19703  OnCreateCreditMemoOnBeforePostedPageRun (46663)
https://github.com/microsoft/ALAppExtensions/issues/20172 all events (48444)

**Comment by JesperSchulz** [comment]
Looks like @AlexanderYakunin will look into this once more, and if the events indeed are missing, he'll get them implemented.

**Comment by GregorJacobsen** [comment]
Hello @JesperSchulz @AlexanderYakunin 
do You have any news on the issues? These 2 are the last places we have knkPublishing related customizations in the Base Application. We planned to release a new version of our product with the upcoming new major release without any Base App customization.

**Comment by AlexanderYakunin** [comment]
We will add one missing event for https://github.com/microsoft/ALAppExtensions/issues/19703. 

As for second one, we have another design and one event to cover all your requirements here:

    local procedure RunSaveAsDocumentAttachment(ReportUsage: Integer; RecordVariant: Variant; DocumentNo: Code[20]; AccountNo: Code[20]; ShowNotificationAction: Boolean)
    var
        ReportSelections: Record "Report Selections";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeRunSaveAsDocumentAttachment(ReportUsage, RecordVariant, ShowNotificationAction, IsHandled);
        if IsHandled then
            exit;

        ReportSelections.SaveAsDocumentAttachment(ReportUsage, RecordVariant, DocumentNo, AccountNo, ShowNotificationAction);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10256.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10256.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 54783.
