### ISSUE TITLE
page 1630 "Office Contact Details Dlg" - change variables to protected

### ISSUE THREAD

**Issue by GregorJacobsen** [microsoft/ALAppExtensions#21743]
To access the variable in our product **knkPublishing**, we would like to have them as protected:

```
page 1630 "Office Contact Details Dlg"
{
    Caption = 'Create New Contact';
    PageType = StandardDialog;
    SourceTable = Contact;
    SourceTableTemporary = true;

    [...]
    
    //changes declaration
    protected var
        AssociateEnabled: Boolean;
        AssociateToCompany: Boolean;
    var
        MustSpecifyCompanyErr: Label 'You must specify the name of the company because the contact is a person and associated with a company.';

}
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52209.
