### ISSUE TITLE
add an event to the "Purchase Invoice Stats" AL object.

### ISSUE THREAD

**Issue by Simon-WK** [microsoft/ALAppExtensions#21742]
For external tax provider, we require exposed methods to update taxes correctly.

Context:
- Sales Invoices and Service Invoices, there is a method exposed for extension ‘OnAfterCalculateSalesTax(…)’.
- The above allows external tax provides to update necessary tax related fields after tax is calculated
 
BC (ERP) Code Issue:
- Purchase Invoices & Purchase Credit Memo do not have a similar method exposed as the above for extension.
- Due to this we cannot write out tax lines to Sales Tax Amount line tables.
- Note that we have noticed this issue for years.

Attached Word Doc with more details:
[Issue with Posted Purchase Invoice Statistics.docx](https://github.com/microsoft/ALAppExtensions/files/10414627/Issue.with.Posted.Purchase.Invoice.Statistics.docx)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10832.
