### ISSUE TITLE
[Extensibility-Bug] Page 5871 Item Availability by BOM Level

### ISSUE THREAD

**Issue by HHynynen** [microsoft/ALAppExtensions#21749]
I have extended the page with some flow field columns e.g. Item.Inventory.
Customer would like the extension to work also when Location Filter is set on page.
RefreshPage procedure does not refresh the extension page and there is no integration event to use either.
It would be best if RefreshPage would refresh also the extension page.
Could you please fix this, thank you!

**Comment by AlexanderYakunin** [comment]
Please provide information about what event(s) do you need here.

**Comment by HHynynen** [comment]
Please advice how this should be done.
If base page is refreshed by the function RefreshPage also the page extension should be refreshed. That´s why I marked this as extensibility-bug.
I´m not sure if it´s enough that you add events OnBeforeRefreshPage and OnAfterRefreshPage or if this should be solved otherwise.

**Comment by JesperSchulz** [comment]
This issue seems to have stranded. Please create a new issue if this still is relevant and we'll route the new ticket to the correct team for processing.
