### ISSUE TITLE
Сreate Event Request Codeunit 99000773 "Calculate Prod. Order" OnBeforeSetProdOrderLineBinCode

### ISSUE THREAD

**Issue by Paskyal** [microsoft/ALAppExtensions#21754]
Hello, could you please create OnBeforeSetProdOrderLineBinCode event in the SetProdOrderLineBinCode procedure in the Codeunit 99000773 "Calculate Prod. Order"?

local procedure SetProdOrderLineBinCode(var ProdOrderLine: Record "Prod. Order Line"; ParentBinCode: Code[20]; ParentLocationCode: Code[10])
    var
        Location: Record Location;
        FromProdBinCode: Code[20];
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetProdOrderLineBinCode(ProdOrderLine, ParentBinCode,ParentLocationCode, IsHandled); ///  NEW EVENT
        if IsHandled then
            exit;
        ProdOrder.Get(ProdOrderLine.Status, ProdOrderLine."Prod. Order No.");
        if (ProdOrder."Location Code" = ProdOrderLine."Location Code") and (ProdOrder."Bin Code" <> '') then begin
            ProdOrderLine.Validate("Bin Code", ProdOrder."Bin Code");
            exit;
        end;

        if ParentBinCode <> '' then
            ProdOrderLine.Validate("Bin Code", ParentBinCode)
        else
            if ProdOrderLine."Bin Code" = '' then begin
                if Location.Get(ParentLocationCode) then
                    FromProdBinCode := Location."From-Production Bin Code";
                if FromProdBinCode <> '' then
                    ProdOrderLine.Validate("Bin Code", FromProdBinCode)
                else
                    if Location."Bin Mandatory" and not Location."Directed Put-away and Pick" then
                        if WMSManagement.GetDefaultBin(ProdOrderLine."Item No.", ProdOrderLine."Variant Code", Location.Code, FromProdBinCode) then
                            ProdOrderLine.Validate("Bin Code", FromProdBinCode);
            end;
    end;

[IntegrationEvent(false, false)]
local procedure OnBeforeSetProdOrderLineBinCode(var ProdOrderLine: Record "Prod. Order Line"; ParentBinCode: Code[20]; ParentLocationCode: Code[10]; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52717.
