### ISSUE TITLE
Microsoft's Base translation apps don't work in 21.3, both OnPrem and SaaS

### ISSUE THREAD

**Issue by printvisdevelopment** [microsoft/ALAppExtensions#21751]
It seems that Microsoft's Base translation apps don't work in 21.3, both OnPrem and SaaS.
I've tested Danish, Swedish and French. Some pages are translated, but most are not.
![image](https://user-images.githubusercontent.com/36659849/212649521-7c0e13e8-388c-4724-a6b2-c3c547e788a9.png)

Noticed that if the Sandbox is created with the DK Country/Region, I do have Danish translations even without installing the Language app. Still, no other language translation app seems to work.
![image](https://user-images.githubusercontent.com/36659849/212649443-166df5e5-8e53-4cfc-969f-780d4c1acb32.png)

Started a yammer thread here: https://www.yammer.com/dynamicsnavdev/threads/2089482232487936 and more people are having the same issue.

**Comment by AlexanderYakunin** [comment]
We cannot help you here, please create request to technical support to fix issues.
