### ISSUE TITLE
Job WIP Method

### ISSUE THREAD

**Issue by Cath59** [microsoft/ALAppExtensions#21752]
Following Issue 20639, The fields "Recognized Costs" and "Recognized Sales" are still option.
Can you transform them to Enum ?
It is not still in Version BC 21.
Thank you,
Catherine

**Comment by AlexanderYakunin** [comment]
No, we cannot downgrade new enums to lower versions. If this is critical for you, you should create service request via technical support.

**Comment by Cath59** [comment]
Hi,
I don’t know if I can reply, but I don’t see the enum in the last version BC 21.3. When will it be available ?

***@***.***

BR,
Catherine

***@***.***
Catherine LANGE
Responsable Projets et Ingénierie Formation
P. +33 6 71 21 18 35
www.absyscyborg.com<https://cloud.letsignit.com/collect/bc/5f8332531c7fca0008b4f70a?p=PKJWbs_18dLjEdAMWw6PJ-KVah2mOOPWHcNokciIZMWGWK4bSi9z_TTqjvXCC3V7YoRf9rIMPFtCkrl4BOKXgOU_z5ON46A5aOWtw6zRNVwQ5e-ODTcCTOGY---4t2e4CIbdtwpmjrMPzYAmpvBMFw==>
[LinkedIn]<https://cloud.letsignit.com/collect/bc/5f8332531c7fca0008b4f70a?p=PKJWbs_18dLjEdAMWw6PJ-KVah2mOOPWHcNokciIZMWGWK4bSi9z_TTqjvXCC3V7YoRf9rIMPFtCkrl4BOKXgOU_z5ON46A5aOWtw6zRNVyvy0pX9yNRttpPsNkQHYPOkrnfGgNEPLuL51LJBgmKLmt3eP5DDduuLyzjFPjctOk=>
[YouTube]<https://cloud.letsignit.com/collect/bc/5f8332531c7fca0008b4f70a?p=PKJWbs_18dLjEdAMWw6PJ-KVah2mOOPWHcNokciIZMWGWK4bSi9z_TTqjvXCC3V7YoRf9rIMPFtCkrl4BOKXgOU_z5ON46A5aOWtw6zRNVz0Aaiq9696kd3Whqci1jTXSvOTNT01h9Fx2G-gEzEdvlDDXPAokbjzrr9q6afD_3BCbWatZF0008q61f8bR7ED>
[Twitter]<https://cloud.letsignit.com/collect/bc/5f8332531c7fca0008b4f70a?p=PKJWbs_18dLjEdAMWw6PJ-KVah2mOOPWHcNokciIZMWGWK4bSi9z_TTqjvXCC3V7YoRf9rIMPFtCkrl4BOKXgEeJLeCbA6VjiBw4QljAIyOR6Kj9QKYrifQ4PY6JPZBYKiFSlVgctAQxQSiekC1Mcw==>

[Vœux 2023]



De : Alexander Yakunin ***@***.***>
Envoyé : lundi 16 janvier 2023 20:52
À : microsoft/ALAppExtensions ***@***.***>
Cc : Catherine LANGE ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/ALAppExtensions] Job WIP Method (Issue #21752)


No, we cannot downgrade new enums to lower versions. If this is critical for you, you should create service request via technical support.

**Comment by AlexanderYakunin** [comment]
All new enums will be available in v.22 (April 2023)

**Comment by Cath59** [comment]
OK, thank you

***@***.***
Catherine LANGE
Responsable Projets et Ingénierie Formation
P. +33 6 71 21 18 35
www.absyscyborg.com<https://cloud.letsignit.com/collect/bc/5f8332531c7fca0008b4f70a?p=PKJWbs_18dLjEdAMWw6PJ-KVah2mOOPWHcNokciIZMWGWK4bSi9z_TTqjvXCC3V7YoRf9rIMPFtCkrl4BOKXgOU_z5ON46A5aOWtw6zRNVwQ5e-ODTcCTOGY---4t2e4CIbdtwpmjrMPzYAmpvBMFw==>
[LinkedIn]<https://cloud.letsignit.com/collect/bc/5f8332531c7fca0008b4f70a?p=PKJWbs_18dLjEdAMWw6PJ-KVah2mOOPWHcNokciIZMWGWK4bSi9z_TTqjvXCC3V7YoRf9rIMPFtCkrl4BOKXgOU_z5ON46A5aOWtw6zRNVyvy0pX9yNRttpPsNkQHYPOkrnfGgNEPLuL51LJBgmKLmt3eP5DDduuLyzjFPjctOk=>
[YouTube]<https://cloud.letsignit.com/collect/bc/5f8332531c7fca0008b4f70a?p=PKJWbs_18dLjEdAMWw6PJ-KVah2mOOPWHcNokciIZMWGWK4bSi9z_TTqjvXCC3V7YoRf9rIMPFtCkrl4BOKXgOU_z5ON46A5aOWtw6zRNVz0Aaiq9696kd3Whqci1jTXSvOTNT01h9Fx2G-gEzEdvlDDXPAokbjzrr9q6afD_3BCbWatZF0008q61f8bR7ED>
[Twitter]<https://cloud.letsignit.com/collect/bc/5f8332531c7fca0008b4f70a?p=PKJWbs_18dLjEdAMWw6PJ-KVah2mOOPWHcNokciIZMWGWK4bSi9z_TTqjvXCC3V7YoRf9rIMPFtCkrl4BOKXgEeJLeCbA6VjiBw4QljAIyOR6Kj9QKYrifQ4PY6JPZBYKiFSlVgctAQxQSiekC1Mcw==>

[Vœux 2023]



De : Alexander Yakunin ***@***.***>
Envoyé : mardi 17 janvier 2023 09:47
À : microsoft/ALAppExtensions ***@***.***>
Cc : Catherine LANGE ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/ALAppExtensions] Job WIP Method (Issue #21752)


All new enums will be available in v.22 (April 2023)
