### ISSUE TITLE
[Event Request] - Page 344 - GlobalVarAccess on OnAfterNavigateShowRecords / OnBeforeNavigateShowRecords

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#2176]
In https://github.com/Microsoft/AL/issues/3885 we've was asked to enable GlobalVarAccess on 3 functions. Issue had been closed, but apparently only one function was changed.

Please provide GlobalVarAccess in OnAfterNavigateShowRecords / OnBeforeNavigateShowRecords publishers on page 344.

**Comment by AlexanderYakunin** [comment]
Please let us know which global variables you need to access. We need to add them explicitly instead of GlonalVarAccess property.

**Comment by fvet** [comment]
We currently need only access to the globals listed below:

- SalesInvHeader
- SalesCrMemoHeader
- PurchInvHeader
- PurchCrMemoHeader
- SISalesHeader
- SCMSalesHeader
