### ISSUE TITLE
[Event Change Request] Codeunit 5812 "Calculate Standard Cost" OnCalcAssemblyItemOnAfterCalcItemCost

### ISSUE THREAD

**Issue by JosefKainz** [microsoft/ALAppExtensions#21771]
Can you please add the BOMComp and/or the ComponentQuantity Variable to the Event  OnCalcAssemblyItemOnAfterCalcItemCost in the Codeunit 5812 "Calculate Standard Cost" 

                Item."Rolled-up Mfg. Ovhd Cost" += ComponentQuantity * CompItem."Rolled-up Mfg. Ovhd Cost";
                Item."Rolled-up Subcontracted Cost" += ComponentQuantity * CompItem."Rolled-up Subcontracted Cost";
                Item."Single-Level Material Cost" += ComponentQuantity * CompItem."Standard Cost"
            end else begin
                Item."Rolled-up Material Cost" += ComponentQuantity * CompItem."Unit Cost";
                Item."Single-Level Material Cost" += ComponentQuantity * CompItem."Unit Cost"
            end;
        OnCalcAssemblyItemOnAfterCalcItemCost(Item, CompItem,BOMComp,ComponentQuantity );

    [IntegrationEvent(false, false)]
    local procedure OnCalcAssemblyItemOnAfterCalcItemCost(var Item: Record Item; CompItem: Record Item; BOMComp: Record "BOM Component"; ComponentQuantity: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52544.
