### ISSUE TITLE
[Event-Request] Report 202 - Sales Document - Test (CheckDimValuePosting)

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#2177]
Similar to the solution that will be delivered for https://github.com/Microsoft/ALAppExtensions/issues/1924, we'd like to be able to add extra dimensions before the CheckDimValuePosting in report 202. 

![image](https://user-images.githubusercontent.com/25268332/56445926-fd750d00-62ff-11e9-9db2-bbdadb7a8822.png)

(Guess this is an application wide pattern that needs review / publishers?)

**Comment by fvet** [comment]
Please also integrate the same pattern / publisher in report 402 Purchase Document - Test

![image](https://user-images.githubusercontent.com/25268332/56560853-d9d2f080-65a5-11e9-9365-65b03161dfd1.png)

**Comment by fvet** [comment]
@jobulsin Any possibility that this publisher will be backported to BC14? Couldn't find it in the latest sandbox image.

**Comment by AlexanderYakunin** [comment]
This is in 14.X since May 20, 2019:

    [External]
    PROCEDURE AddDimToTempLine@2(SalesLine@1000 : Record 37);
    VAR
      SourceCodeSetup@1002 : Record 242;
      TableID@1003 : ARRAY [10] OF Integer;
      No@1004 : ARRAY [10] OF Code[20];
    BEGIN
      SourceCodeSetup.GET;

      WITH SalesLine DO BEGIN
        TableID[1] := DimMgt.TypeToTableID3(Type);
        No[1] := "No.";
        TableID[2] := DATABASE::Job;
        No[2] := "Job No.";
        TableID[3] := DATABASE::"Responsibility Center";
        No[3] := "Responsibility Center";

        OnAfterCreateDimTableIDs(SalesLine,TableID,No);

        "Shortcut Dimension 1 Code" := '';
        "Shortcut Dimension 2 Code" := '';
        "Dimension Set ID" :=
          DimMgt.GetDefaultDimID(TableID,No,SourceCodeSetup.Sales,"Shortcut Dimension 1 Code","Shortcut Dimension 2 Code",
            "Dimension Set ID",DATABASE::Customer);
      END;
    END;
