### ISSUE TITLE
[Access Request] page 7001 "Price List Lines"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#21775]
Could you please change the access scope of the following procedures to protected?
```al
//+Change
//-local procedure SetSourceNoEnabled()
protected procedure SetSourceNoEnabled()
//-Change
var
    PriceSource: Record "Price Source";
begin
    PriceSource."Source Type" := Rec."Source Type";
    IsParentAllowed := PriceSource.IsParentSourceAllowed();
    SourceNoEnabled := Rec.IsSourceNoAllowed();
end;

//+Change
//-local procedure ValidateSourceType(SourceType: Integer)
protected procedure ValidateSourceType(SourceType: Integer)
//-Change
begin
    Rec.Validate("Source Type", SourceType);
    SetSourceNoEnabled();
    CurrPage.Update(true);
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52559.
