### ISSUE TITLE
[EventRequest] Report 11000012 "SEPA ISO20022 Pain 01.01.03".AddPaymentInformation for ServiceLevelCode change

### ISSUE THREAD

**Issue by ricardomeulendijks** [microsoft/ALAppExtensions#21772]
Hello, for our client we need to change the service level code in the "SEPA ISO20022 Pain 01.01.03" report. Could you please add the  following event? 

     begin
        BtchBookg := 'false';
        OnBeforeAddPaymentInformation(PaymentHistoryLine, BankAcc, BtchBookg);

        XMLParent := XMLNodeCurr;
        AddElement(XMLNodeCurr, 'PmtInf', '', '', XMLNewChild);
        XMLNodeCurr := XMLNewChild;
        TransactionMode.Get(PaymentHistoryLine."Account Type", PaymentHistoryLine."Transaction Mode");

        Worldpayment :=
            TransactionMode.WorldPayment or
            (GLSetup."Local Currency" = GLSetup."Local Currency"::Euro) and
            (PaymentHistoryLine."Currency Code" <> '') or
            (GLSetup."Local Currency" = GLSetup."Local Currency"::Other) and
            (PaymentHistoryLine."Currency Code" <> GLSetup."Currency Euro") or
            (PaymentHistoryLine."Foreign Amount" <> 0);

        if Worldpayment then begin
            ServiceLevelCode := 'SDVA';
            case true of
                (TransactionMode."Transfer Cost Domestic" = TransactionMode."Transfer Cost Domestic"::Principal) and
                (TransactionMode."Transfer Cost Foreign" = TransactionMode."Transfer Cost Foreign"::Principal):
                    ChargeBearer := 'DEBT';
                (TransactionMode."Transfer Cost Domestic" = TransactionMode."Transfer Cost Domestic"::"Balancing Account Holder") and
                (TransactionMode."Transfer Cost Foreign" = TransactionMode."Transfer Cost Foreign"::"Balancing Account Holder"):
                    ChargeBearer := 'CRED';
                else
                    ChargeBearer := 'SHAR';
            end;
        end else begin
            ServiceLevelCode := 'SEPA';
            ChargeBearer := 'SLEV';
        end;
     THIS EVENT ->>    OnAfterAddServiceLevelCode(ServiceLevelCode);         <<- THIS EVENT 

    [IntegrationEvent(false, false)]
    local procedure OnAfterAddServiceLevelCode(var ServiceLevelCode: Code[10])
    begin
    end;

`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53230.
