### ISSUE TITLE
[Event Request] Codeunit 90 "Purch.-Post" - OnBeforePrepareCheckDocument

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#21783]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnBeforePrepareCheckDocument' to be added to procedure 'PrepareCheckDocument' in codeunit 90 "Purch.-Post".

````
    procedure PrepareCheckDocument(var PurchaseHeader: Record "Purchase Header")
    begin
        OnBeforePrepareCheckDocument(PurchaseHeader); //new
        GetGLSetup();
        GetPurchSetup();
        GetInvoicePostingSetup();
        GetCurrency(PurchaseHeader."Currency Code");
        FillTempLines(PurchaseHeader, TempPurchLineGlobal);
        LogErrorMode := true;
    end;
````
````
    [IntegrationEvent(false, false)]
    local procedure OnBeforePrepareCheckDocument(var PurchaseHeader: Record "Purchase Header")
    begin
    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.
