### ISSUE TITLE
[Change Request] Post Code Management - CountryCode parameter as var

### ISSUE THREAD

**Issue by Aize-S** [microsoft/ALAppExtensions#21780]
L.S.,

In codeunit 11401 - "Post Code Mangement" are two procedures:
- FindStreetNameFromAddress
- FindStreetName

Both have a parameter CountryCode: Code[10] which is the only parameter that is not declared as _var_.

In the OnAfterFindStreetNameFromAddress event the same parameter CountryCode is also available and there it _is_ declared as _var_.

I didn't find the codeunit in this repo, so I wasn't able to create a PR for it.

Please add _var_ to the CountryCode parameter in procedure FindStreetName (or both).

Best regards,

Aize

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53230.
