### ISSUE TITLE
[Event Request] table 1382 "Item Templ." - OnAfterCopyFromTemplate

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#21788]
Could you please add the following event?
```al
procedure CopyFromTemplate(SourceItemTempl: Record "Item Templ.")
begin
    CopyTemplate(SourceItemTempl);
    CopyDimensions(SourceItemTempl);
    //+EVENT
    OnAfterCopyFromTemplate(SourceItemTempl, Rec);
    //-EVENT
end;

```

```al
[IntegrationEvent(false, false)]
local procedure OnAfterCopyFromTemplate(SourceItemTempl: Record "Item Templ."; var TargetItemTempl: Record "Item Templ.")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52552.
