### ISSUE TITLE
[Enum Request] For a field of Table 85 ("Acc. Schedule Line") 

### ISSUE THREAD

**Issue by JuditNavarro** [microsoft/ALAppExtensions#2179]
Hello ALAppExtensions-team, 

Could It be possible to make option field **"Totaling Type"** in Table 85 ("Acc. Schedule Line") extensible using enums?

Thank you!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
