### ISSUE TITLE
[Event Request]  page 344 Navigate  -  OnAfterOnInit

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#21790]
Hello, for an Page extension we need an new Event OnAfterOnInit.

```
trigger OnInit()
    begin
        SourceNameEnable := true;
        SourceNoEnable := true;
        SourceTypeEnable := true;
        DocTypeEnable := true;
        PrintEnable := true;
        ShowEnable := true;
        DocumentVisible := true;
        SearchBasedOn := SearchBasedOn::Document;
        OnAfterOnInit(Rec);
    end;
```

```
[IntegrationEvent(false, false)]
    local procedure OnAfterOnInit(var Rec: Record "Document Entry");
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52552.
