### ISSUE TITLE
Add field Vendor Invoice No. on table Purch. Rcpt. Header

### ISSUE THREAD

**Issue by RishtaCader** [Microsoft/ALAppExtensions#218]
Hello,

Is it possible to add the field Vendor Invoice No. (ID 68) from table Purchase Header (T38) to table Purch. Rcpt. Header (T120)? As i need the value of Vendor Invoice No. through transferfields from table 38 to table 120.

Thank you.
Kind regards.

**Comment by RHansenEpimatic** [comment]
This wouldn't make logical sense.  It would only work if you always receive and invoice at the same time.  Normally companies receive the shipment from the vendor at one time...then the invoice comes later.  So, at the time of posting the purchase receipt the vendor invoice number is not known.  How are you thinking this should work?  In your scenario do they always post the receipt and invoice at the same time?  I'd suggest rethinking whatever logic you're developing to work in a different way.

**Comment by JesperSchulz** [comment]
@RHansenEpimatic, thank you for your elaborate reply. We second your opinion. @RishtaCader, if you'd like to move forward with your idea in another way, please add your idea to http://aka.ms/bcideas.
