### ISSUE TITLE
Multiple published extensions match the specified parameter values

### ISSUE THREAD

**Issue by ABaludin** [microsoft/ALAppExtensions#2180]
Hi!
I have next scenario:
1. **Online** BC sandbox US Dynamics NAV 13.3 (29060)
2. I have 2 apps - main and dependent
3. I made some changes to main app. Not breaking schema change - just adding a few rows of code.
4. I unpublished dependent app
5. Trying to publish main app - got an error that I have to change version number
6. I increased version number, trying to publish main app again and getting an error - 
The request for path /v1.0/sandbox/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Multiple published extensions match the specified parameter values. You must specify more information to indicate which extension to use.
7. I could find my app not installed on Extensions Management page, click install - and it will work, but if I try to publish it from VS Code - I'll get the same error. Recreate helps - but I'm loosing all my data.

How to deal with it? Thanks in advance.

**Comment by ikoletic** [comment]
This issue is a question. Please submit your questions on [business central community ](https://community.dynamics.com/business/f/758) or on [BC development yammer groups](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035).

**Comment by finn777** [comment]
The error-la:
_Publishing AL application using launch configuration 'Microsoft cloud sandbox'.
…
The request for path /v2.0/SandboxCopy/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Multiple published extensions match the specified parameter values. You must specify more information to indicate which extension to use._

Can be relate to a conflict between Dev (VS Code) extension and PTE (Per-Tenant-Extension) extension.
A PTE (Per-Tenant-Extension) extension is an extension that is installed from the extension management page (web client) via uploading the app and a DEV extension is an app that is deployed via visual studio code. Right now.. there is a uniqueness requirements for coexistence of these 2 kinds of extensions. If a PTE extension is installed on an application service a DEV extension cannot be deployed there.
you can read about it here: [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-deploy-tenant-customization#extension-uniqueness-requirements](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-deploy-tenant-customization#extension-uniqueness-requirements)

Potential solution: unpublished the PTE in sandbox and changed the id, name, version and publisher of DEV extension

P.S. maybe Development base on 'Microsoft cloud sandbox' not best choice. I think better use docker container.

**Comment by ikoletic** [comment]
This issue is a question. Please submit your questions on business central community or on BC development yammer groups.

**Comment by tomggithub** [comment]
Just want to clarify:
The reported "cannot install extension" is **not** question, this is **issue**. We encounter this again from Business Central on cloud today. And used working for last few month.

Our customer has 3 sandbox and 1 production environment (in version 15.4), we developed and use VScode to publish to sandboxdev, after confirm this works, we upload same version .app file to sandbox and then production. This method worked for last few month until today. 

We published extension in sandboxdev works ok, and then uploaded .app file to sandbox, we got the msg :
"The request for path /v2.0/SandboxCopy/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Multiple published extensions match the specified parameter values. You must specify more information to indicate which extension to use".

We have to increase version # to publish to different sandbox environment and then increase again for production environment. And with multiple developers work on same project, very hard to tell why all environment with different version.

Can this issue be fixed? Thanks

**Comment by fommo** [comment]
I have the exact same issue. All worked perfectly fine until recently.
In my app.json I have the following dependencies:
  "dependencies": [
    {
      "appId": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
      "publisher": "Microsoft",
      "name": "System Application",
      "version": "1.0.0.0"
    },
    {
      "appId": "437dbf0e-84ff-417a-965d-ed2bb9650972",
      "publisher": "Microsoft",
      "name": "Base Application",
      "version": "15.0.0.0"
    }
  ],
  "platform": "15.0.0.0",
Has anything here changed? Do I need different dependencies?
I need the backward compatibility, hence the 15.0.0.0, although working with the BC Sandbox (currently 16.2.13509.14256 in the base application)

Please advice, or fix this as it's very annoying to not be able to deploy as before.

**Comment by fommo** [comment]
If I use "schemaUpdateMode": "Recreate" it does work, but then when I try to deploy using Synchronize it gives the same error again.
It's very annoying to use Recreate as all data needs to be inserted again.
I agree with @tomggithub that this is not a question, but an issue as this was introduced with some recent update. It was not a problem before. Please fix this again.
