### ISSUE TITLE
[Event change Request] page 344 Navigate  - OnAfterFindPostedDocuments

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#21806]
Hello, can you please add the Rec variable to the existing event OnAfterFindPostedDocuments?

`
OnAfterFindPostedDocuments(Rec, DocNoFilter, PostingDateFilter);
`

```
[IntegrationEvent(true, false)]
    local procedure OnAfterFindPostedDocuments(var Rec: Record "Document Entry"; var DocNoFilter: Text; var PostingDateFilter: Text)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52552.
