### ISSUE TITLE
Event Request:  table 904 "Assemble-to-Order Link" OnBeforeDeleteAsmQtyToAssembleZero

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#21825]
Please could we have the following event added:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteAsmQtyToAssembleZero(var NewSalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

    local procedure UpdateAsm(var NewSalesLine: Record "Sales Line"; AsmExists: Boolean)
    var
        SalesLine2: Record "Sales Line";
        InvtAdjmtEntryOrder: Record "Inventory Adjmt. Entry (Order)";
        IsHandled: Boolean;
    begin
        if AsmExists then begin
            if not NewSalesLine.IsAsmToOrderAllowed() then begin
                DeleteAsmFromSalesLine(NewSalesLine);
                exit;
            end;

            if NewSalesLine."Qty. to Assemble to Order" = 0 then begin
                IsHandled := false;
                OnBeforeDeleteAsmQtyToAssembleZero(NewSalesLine,IsHandled);
                if not IsHandled then begin
                    DeleteAsmFromSalesLine(NewSalesLine);
                    InvtAdjmtEntryOrder.SetRange("Order Type", InvtAdjmtEntryOrder."Order Type"::Assembly);
                    InvtAdjmtEntryOrder.SetRange("Order No.", "Assembly Document No.");
                    if ("Assembly Document Type" = "Assembly Document Type"::Order) and not InvtAdjmtEntryOrder.IsEmpty() then
                        Insert();
                    exit;
                end;
            end;
            if not GetAsmHeader() then begin

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52435.
