### ISSUE TITLE
Event Request: table 37 "Sales Line" OnBeforeIsAsmToOrderAllowed

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#21820]
Please could we have the following event added to allow us to activate Assembly for Credit Memos:
    procedure IsAsmToOrderAllowed(): Boolean
    var
      IsHandled: Boolean;
    begin
        OnBeforeIsAsmToOrderAllowed(Rec,Result,IsHandled)
        if IsHandled then
          exit(Result);

    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsAsmToOrderAllowed(var SalesLine: Record "Sales Line"; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52552.
