### ISSUE TITLE
Event Request: table 904 "Assemble-to-Order Link" OnBeforeShowAsmToOrderLines

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#21824]
Please could we have the following event added:
table 904 "Assemble-to-Order Link"
    procedure ShowAsmToOrderLines(SalesLine: Record "Sales Line")
    var
        AsmLine: Record "Assembly Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeShowAsmToOrderLines(SalesLine)
        if IsHandled then
            exit;

        SalesLine.TestField("Qty. to Asm. to Order (Base)");
        if AsmExistsForSalesLine(SalesLine) then begin
            AsmLine.FilterGroup := 2;
            AsmLine.SetRange("Document Type", "Assembly Document Type");
            AsmLine.SetRange("Document No.", "Assembly Document No.");
            AsmLine.FilterGroup := 0;
            PAGE.RunModal(PAGE::"Assemble-to-Order Lines", AsmLine);
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowAsmToOrderLines(SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52435.
