### ISSUE TITLE
[Event Change] Codeunit 90 - "Purch.-Post" event OnBeforeDeleteAfterPosting

### ISSUE THREAD

**Issue by iyiannak** [microsoft/ALAppExtensions#21833]
Could you please add as parameter (by var) the TempPurchLineGlobal on integration event OnBeforeDeleteAfterPosting at Codeunit 90 ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.
