### ISSUE TITLE
[Event Request] table 1383 "Vendor Templ." - OnAfterCopyFromTemplate

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#21838]
Could you please add the following event?
```al
procedure CopyFromTemplate(SourceVendorTempl: Record "Vendor Templ.")
begin
    CopyTemplate(SourceVendorTempl);
    CopyDimensions(SourceVendorTempl);
    //+EVENT
    OnAfterCopyFromTemplate(SourceVendorTempl, Rec);
    //+EVENT
end;
```
```al
[IntegrationEvent(false, false)]
local procedure OnAfterCopyFromTemplate(SourceVendorTempl: Record "Vendor Templ."; var VendorTempl: Record "Vendor Templ.")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52544.
