### ISSUE TITLE
[Event Request] table 38 "Purchase Header" - OnAfterCouldDimensionsBeKept

### ISSUE THREAD

**Issue by developerchristiaens** [microsoft/ALAppExtensions#21830]
Can you provide event OnAfterCouldDimensionsBeKept on Purchase Header (similar as on Sales Header):

	local procedure CouldDimensionsBeKept(): Boolean;
    begin
        if (xRec."Buy-from Vendor No." <> '') and (xRec."Buy-from Vendor No." <> Rec."Buy-from Vendor No.") then
            exit(false);
        if (xRec."Pay-to Vendor No." <> '') and (xRec."Pay-to Vendor No." <> Rec."Pay-to Vendor No.") then
            exit(false);

        if (Rec."Location Code" = '') and (xRec."Location Code" <> '') then
            exit(true);
        if (xRec."Location Code" <> '') and (xRec."location Code" <> Rec."Location Code") then
            exit(true);
        if (xRec."Purchaser Code" <> '') and (xRec."Purchaser Code" <> Rec."Purchaser Code") then
            exit(true);
        if (xRec."Responsibility Center" <> '') and (xRec."Responsibility Center" <> Rec."Responsibility Center") then
            exit(true);
			
	    OnAfterCouldDimensionsBeKept(Rec, xRec, Result);
    end;
	
    [IntegrationEvent(false, false)]
    local procedure OnAfterCouldDimensionsBeKept(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader: Record "Purchase Header"; var Result: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52485.
