### ISSUE TITLE
[Property Request]: Add Application Area and Usage Catalog to Page Work Center /Machine Center Task List

### ISSUE THREAD

**Issue by rickblommetjes** [microsoft/ALAppExtensions#21842]
We would like on request of several customers make the following pages accessable directly from the role center of the end users or throught the right upper searchbox:

page 99000915 "Work Center Task List"
page 99000916 "Machine Center Task List"

the properties added should be:

ApplicationArea = Manufacturing,Planning;
UsageCategory = Tasks;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52887.
