### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" OnBeforeRunItemJnlPostLineWithReservation

### ISSUE THREAD

**Issue by DanielSmutek** [microsoft/ALAppExtensions#21844]
Please, add new Event to Codeunit 90:

local procedure PostItemJnlLineJobConsumption(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; ItemJournalLine: Record "Item Journal Line"; var TempPurchReservEntry: Record "Reservation Entry" temporary; QtyToBeInvoiced: Decimal; QtyToBeReceived: Decimal; var TempTrackingSpecification: Record "Tracking Specification" temporary; PurchItemLedgEntryNo: Integer)
    var
        ItemLedgEntry: Record "Item Ledger Entry";
        TempReservationEntry: Record "Reservation Entry" temporary;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnPostItemJnlLineJobConsumption(
          PurchHeader, PurchLine, ItemJournalLine, TempPurchReservEntry, QtyToBeInvoiced, QtyToBeReceived,
          TempTrackingSpecification, PurchItemLedgEntryNo, IsHandled, ItemJnlPostLine, PurchInvHeader, PurchCrMemoHeader, SrcCode);
        if IsHandled then
            exit;

        with PurchLine do
            if "Job No." <> '' then begin
                ItemJournalLine."Entry Type" := ItemJournalLine."Entry Type"::"Negative Adjmt.";
                Job.Get("Job No.");
                ItemJournalLine."Source No." := Job."Bill-to Customer No.";
                if PurchHeader.Invoice then begin
                    ItemLedgEntry.Reset();
                    ItemLedgEntry.SetRange("Document Type", ItemLedgEntry."Document Type"::"Purchase Return Shipment");
                    if "Return Shipment No." <> '' then
                        ItemLedgEntry.SetRange("Document No.", "Return Shipment No.")
                    else
                        ItemLedgEntry.SetRange("Document No.", PurchHeader."Last Return Shipment No.");
                    ItemLedgEntry.SetRange("Item No.", "No.");
                    ItemLedgEntry.SetRange("Entry Type", ItemLedgEntry."Entry Type"::"Negative Adjmt.");
                    ItemLedgEntry.SetRange("Completely Invoiced", false);
                    OnPostItemJnlLineJobConsumptionOnAfterItemLedgEntrySetFilters(ItemLedgEntry, PurchLine, ItemJournalLine);
                    if ItemLedgEntry.FindFirst() then
                        ItemJournalLine."Item Shpt. Entry No." := ItemLedgEntry."Entry No.";
                end;
                ItemJournalLine."Source Type" := ItemJournalLine."Source Type"::Customer;
                ItemJournalLine."Discount Amount" := 0;

                GetAppliedItemLedgEntryNo(ItemJournalLine, "Quantity Received");

                if QtyToBeReceived <> 0 then
                    CopyJobConsumptionReservation(
                      TempReservationEntry, TempPurchReservEntry, ItemJournalLine, TempTrackingSpecification,
                      PurchItemLedgEntryNo, IsNonInventoriableItem());
                
                //+EVENT
                OnBeforeRunItemJnlPostLineWithReservation(ItemJournalLine, PurchLine, TempReservationEntry);
                //+EVENT

                RunItemJnlPostLineWithReservation(ItemJournalLine, TempReservationEntry);

    [IntegrationEvent(true, false)]
    local procedure OnBeforePostItemJnlLineJobConsumption(var ItemJournalLine: Record "Item Journal Line"; var PurchaseLine: Record "Purchase Line"; var TempReservationEntry: Record "Reservation Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52463.
