### ISSUE TITLE
[Events Request] Table::"Planning Routing Line" + Global procedures

### ISSUE THREAD

**Issue by vdevmt** [microsoft/ALAppExtensions#21848]
In Table "Planning Routing Line" we would like to have new event:

1. procedure CalcStartingEndingDates :

        IsHandled := false;
        OnBeforeCalcStartingEndingDates(Rec,  IsHandled);
        if IsHandled then
            exit;

2. procedure UpdateDatetime:
    OnAfterUpdateDateTime(Rec, xRec, CurrFieldNo);

In Table "Planning Routing Line" and "Prod. Order Routing Line" we would like to have CalculateRoutingBack and CalculateRoutingForward procedures declared as global

**Comment by AlexanderYakunin** [comment]
Please do not combine event requests with anything else, it blocks our processing rules. Create this as separate request:

In Table "Planning Routing Line" and "Prod. Order Routing Line" we would like to have CalculateRoutingBack and CalculateRoutingForward procedures declared as global
