### ISSUE TITLE
Images in the README.md don't seem to be found

### ISSUE THREAD

**Issue by bjarkihall** [microsoft/ALAppExtensions#21841]
Thought I'd let you know, the images in the README files are returning 404 Not Found:
https://github.com/microsoft/ALAppExtensions/blob/main/Modules/README.md

![image](https://user-images.githubusercontent.com/8615374/213589918-1ded39ff-1124-4e11-8a80-68035dc7a611.png)

The [raw file](https://raw.githubusercontent.com/microsoft/ALAppExtensions/main/Modules/README.md) shows that it's trying to show images from this endpoint, for example: https://cloudblogs.microsoft.com/uploads/prod/sites/4/2019/08/image015.png

This also happens at https://github.com/microsoft/ALAppExtensions/blob/main/Modules/System/README.md

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10874.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 57314.
