### ISSUE TITLE
The Attribute <xmlns> is unexpected.

### ISSUE THREAD

**Issue by Michel-up** [microsoft/ALAppExtensions#21859]
When using Xmlport.Run, i am getting "The Attribute <xmlns> is unexpected." 

XML sample:

```
<?xml version="1.0" encoding="UTF-8"?>
<Order xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:oasis:names:specification:ubl:schema:xsd:Order-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2">
 <cbc:UBLVersionID>2.1</cbc:UBLVersionID>
 <cbc:CustomizationID>Test</cbc:CustomizationID>
 </Order>
```

BC XMLPort sample :
```

xmlport 50001 "xmlporttest"
{
    Format = Xml;
    Caption = 'xmlport test';
    Direction = Import;
    Encoding = UTF8;
    Namespaces = "" = 'urn:oasis:names:specification:ubl:schema:xsd:Order-2', xs = 'http://www.w3.org/2001/XMLSchema', cac = 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2', cbc = 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2';
    UseRequestPage = false;
    DefaultNamespace = 'urn:oasis:names:specification:ubl:schema:xsd:Order-2';
    UseDefaultNamespace = true;
    

    schema
    {
        textelement(orderheader)
        {

            MaxOccurs = Once;
            XmlName = 'Order';

            textelement(UBLVersionID)
            {
                NamespacePrefix = 'cbc';
            }

            // SourceTableView = sorting(Number) where(Number = filter(1 ..));
            textelement(CustomizationID)
            {
                NamespacePrefix = 'cbc';
            }
        }
    }
}
```

i tried removing DefaultNamespace, and removing "" from Namespaces, changing UseDefaultNamespace true/false
but whatever i do, i still get the same error : "The Attribute <xmlns> is unexpected."

the error wont be displayed if xmlns="urn:oasis:names:specification:ubl:schema:xsd:Order-2" is removed from the XML file

**Comment by Michel-up** [comment]
@AlexanderYakunin this more a bug than a question, the DefaultNamespace doesnt seems to work on Direction=Import

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by AlexanderYakunin** [comment]
I am sorry, but this channel is not suitable for reporting bugs.
