### ISSUE TITLE
page 1351 "Posted Purch. Invoice - Update" - change scope of procedure SetRec

### ISSUE THREAD

**Issue by GregorJacobsen** [microsoft/ALAppExtensions#21854]
We use this procedure to prepare the call of the page on serveral pages in our product **knkPublishing**.
To be able to use the procedure with target "Cloud" the scope should be removed.

**change in page:**
```
page 1351 "Posted Purch. Invoice - Update"
{
    Caption = 'Posted Purch. Invoice - Update';
    DeleteAllowed = false;

    [...]
    //removed scope
    procedure SetRec(PurchInvHeader: Record "Purch. Inv. Header")
    begin
        Rec := PurchInvHeader;
        Insert();
    end;
    [...]
}
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52559.
