### ISSUE TITLE
[Event Request] Codeunit 7324 "Whse.-Activity-Post" - PostSourceDocument - OnPostSourceDocumentOnBeforeTransferPostRun

### ISSUE THREAD

**Issue by stephanpl** [microsoft/ALAppExtensions#21853]
In codeunit 7324 "Whse.-Activity-Post" there is a event publisher, OnPostSourceDocumentOnBeforeSalesPostRun, before the Sales-Post codeunit is called in local procedure PostSourceDocument.
We would like to have a similar event publisher before the transfer posting codeunits are called.
So, something like this:

                DATABASE::"Transfer Line":
                    begin
                        Clear(TransferPostReceipt);
                        if not SuppressCommit then
                            Commit();
                        OnPostSourceDocumentOnBeforeTransferPostRun(WhseActivHeader, TransferHeader);
                        if Type = Type::"Invt. Put-away" then begin
                            if HideDialog then
                                TransferPostReceipt.SetHideValidationDialog(HideDialog);
                            TransHeader."Posting from Whse. Ref." := PostingReference;
                            TransferPostReceipt.Run(TransHeader);
                            PostedSourceType := DATABASE::"Transfer Receipt Header";
                            PostedSourceNo := TransHeader."Last Receipt No.";
                        end else begin
                            if HideDialog then
                                TransferPostShip.SetHideValidationDialog(HideDialog);
                            TransHeader."Posting from Whse. Ref." := PostingReference;
                            if not TransHeader."Direct Transfer" then begin
                                TransferPostShip.Run(TransHeader);
                                PostedSourceType := DATABASE::"Transfer Shipment Header";
                                PostedSourceNo := TransHeader."Last Shipment No.";
                            end else begin
                                InventorySetup.Get();
                                InventorySetup.TestField("Direct Transfer Posting", InventorySetup."Direct Transfer Posting"::"Direct Transfer");
                                TransferPostTransfer.Run(TransHeader);
                                PostedSourceType := DATABASE::"Direct Trans. Header";
                                PostedSourceNo := TransHeader."Last Shipment No.";
                            end;
                        end;

                        OnPostSourceDocumentOnBeforeUpdateUnhandledTransLine(TransHeader, WhseActivHeader, PostingReference, HideDialog);
                        UpdateUnhandledTransLine(TransHeader."No.");
                        PostedSourceSubType := 0;
                    end;

    [IntegrationEvent(false, false)]
    local procedure OnPostSourceDocumentOnBeforeTransferPostRun(WarehouseActivityHeader: Record "Warehouse Activity Header"; var TransferHeader: Record "Transfer Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52570.
