### ISSUE TITLE
[Event Request] Table 39 Purchase Line - UpdateVATAmounts - OnUpdateVATAmountsOnBeforeCalcAmounts

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#21851]
We would like to get the same publisher in Purchase Line as in table Sales line in the `UpdateVATAmounts`  function.

Location

![image](https://user-images.githubusercontent.com/25268332/214002239-c1861466-ec5a-41a4-bd3f-b6de420a7f53.png)

```
OnUpdateVATAmountsOnBeforeCalcAmounts(
                Rec, PurchLine2, TotalAmount, TotalAmountInclVAT, TotalLineAmount, TotalInvDiscAmount, TotalVATBaseAmount, TotalQuantityBase, TotalVATDifference, IsHandled);
            if IsHandled then
                exit;

```

Signature 

```
 [IntegrationEvent(false, false)]
    local procedure OnUpdateVATAmountsOnBeforeCalcAmounts(var PurchaseLine: Record "Purchase Line"; var PurchaseLine2: Record "Purchase Line"; var TotalAmount: Decimal; TotalAmountInclVAT: Decimal; var TotalLineAmount: Decimal; var TotalInvDiscAmount: Decimal; var TotalVATBaseAmount: Decimal; var TotalQuantityBase: Decimal; TotalVATDifference: Decimal; var IsHandled: Boolean);
    begin
    end;
```

PS: Please see #21850 to ensure  including `TotalVATDifference`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10818.
