### ISSUE TITLE
Event Request: codeunit 1002 "Job Create-Invoice" OnBeforeCreateSalesLineCheckCurrency

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#21866]
Please could we have the following event added to allow us to implement multi-currency jobs, thank you:

[IntegrationEvent(false, false)]
    local procedure OnBeforeCreateSalesLineCheckCurrency(var Job: record Job;var JobPlanningLine: Record "Job Planning Line"; var SalesHeader: Record "Sales Header"; var SalesHeader2: Record "Sales Header"; var JobInvCurrency: Boolean; var IsHandled: Boolean)
    begin
    end;

    local procedure CreateSalesLine(var JobPlanningLine: Record "Job Planning Line")
    var
        Job: Record Job;
        Factor: Integer;
        IsHandled: Boolean;
    begin
        OnBeforeCreateSalesLine(JobPlanningLine, SalesHeader, SalesHeader2, JobInvCurrency);

        Factor := 1;
        if SalesHeader2."Document Type" = SalesHeader2."Document Type"::"Credit Memo" then
            Factor := -1;
        TestTransferred(JobPlanningLine);
        JobPlanningLine.TestField("Planning Date");
        Job.Get(JobPlanningLine."Job No.");
        Clear(SalesLine);
        SalesLine."Document Type" := SalesHeader2."Document Type";
        SalesLine."Document No." := SalesHeader."No.";

        IsHandled := false;
        OnBeforeCreateSalesLineCheckCurrency(Job,JobPlanningLine, SalesHeader, SalesHeader2, JobInvCurrency, IsHandled);
        if not IsHandled then
            if (not JobInvCurrency) and (JobPlanningLine.Type <> JobPlanningLine.Type::Text) then begin
                SalesHeader.TestField("Currency Code", JobPlanningLine."Currency Code");
                if (Job."Currency Code" <> '') and (JobPlanningLine."Currency Factor" <> SalesHeader."Currency Factor") then
                    if Confirm(Text011) then begin
                        JobPlanningLine.Validate("Currency Factor", SalesHeader."Currency Factor");
                        JobPlanningLine.Modify();
                    end else
                        Error(Text001);
                SalesHeader.TestField("Currency Code", Job."Currency Code");
            end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52878.
