### ISSUE TITLE
Bug on page 35516 "Cash Receipt Journal FactBox"

### ISSUE THREAD

**Issue by ViktorasDanielius** [microsoft/ALAppExtensions#21862]
Function UpdateInfoBox on page 35516 "Cash Receipt Journal FactBox" has following code:
``` 
            if Currency.Get("Currency Code") then
                Currency.InitRoundingPrecision;
```
This is wrong - it should be changed to if NOT:
``` 
            if not Currency.Get("Currency Code") then
                Currency.InitRoundingPrecision;
```
Same issue exist on page 35517 "Payment Journal FactBox"

Please fix

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52887.
