### ISSUE TITLE
[Event Request] Table 5612 "FA depreciation Book" - OnBeforeLinearMethod

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#21871]
Hello, we would like to get the following new Event OnBeforeLinearMethod in the procedure LinearMethod. Thanks!

```
protected procedure LinearMethod(): Boolean
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeLinearMethod(Rec, IsHandled);
        if IsHandled then
            exit(true);
        exit(
          "Depreciation Method" in
          ["Depreciation Method"::"Straight-Line",
           "Depreciation Method"::"DB1/SL",
          "Depreciation Method"::"DB2/SL"]);
    end;
```

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeLinearMethod(FADepreciationBook: Record "FA Depreciation Book"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52878.
