### ISSUE TITLE
[Event Request] Table 5612 "FA depreciation Book" - OnBeforeCalcBookValue

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#21873]
Hello, we would like to get the following new Event in the procedure CalcBookValue. Thanks!

```
procedure CalcBookValue()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalcBookValue(Rec, IsHandled);
        if not IsHandled then
            IF "Disposal Date" > 0D THEN
                "Book Value" := 0
            else
                CalcFields("Book Value");
    end;
```

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeCalcBookValue(var FADepreciationBook: Record "FA Depreciation Book"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52878.
