### ISSUE TITLE
[Code Change Request] Scope of FindConflicts() InsertFromConflict()  RemoveConflictingRecord() in from OnPrem to Cloud

### ISSUE THREAD

**Issue by ChrisChristophers** [microsoft/ALAppExtensions#21878]
Hello, this is a follow-up request to  https://github.com/microsoft/ALAppExtensions/issues/21095#issuecomment-1357440488_  
to change the scope for Universal Code Standard reasons for the following functions

MergeDuplicatesBuffer.InsertFromConflict()
MergeDuplicatesBuffer.RemoveConflictingRecord()
TempMergeDuplicatesLineBuffer.FindConflicts()

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52559.
