### ISSUE TITLE
[Extensibility Bug] codeunit 23 "Item Jnl.-Post Batch" - OpenProgressDialog - Open Window only if GuiAllowed

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#21887]
Could you please add an check for GuiAllowed() in the procedure `OpenProgressDialog`?

```al
local procedure OpenProgressDialog()
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeOpenProgressDialog(ItemJnlLine, Window, WindowIsOpen, IsHandled);
    if IsHandled then
        exit;
//+Change
if not GuiAllowed then
    exit;
//-Change

    if ItemJnlTemplate.Recurring then
        Window.Open(
            Text001 +
            Text002 +
            Text003 +
            Text004)
    else
        Window.Open(
            Text001 +
            Text002 +
            Text005);

    Window.Update(1, ItemJnlLine."Journal Batch Name");
    WindowIsOpen := true;
end;
```

Reference to an very old issue: https://github.com/microsoft/ALAppExtensions/issues/213

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52887.
