### ISSUE TITLE
[External Request] Table Price List Header (7000)

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#21883]
Hi, 

can you make the functions `CheckIfLinesExist` and `TestStatusDraft` public in table "Price List Header"?

Thanks in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52844.
