### ISSUE TITLE
[Bug][PermissionSet] Using security filter on table containing parenthesis in the caption

### ISSUE THREAD

**Issue by warlof** [microsoft/ALAppExtensions#21880]
Hello,

I would report an issue we encounter on table containing `(` or `)` characters in their caption when using Security Filter.
This is valid from all versions starting with at least 19.5.

1) Go into the permission sets page
2) Create a permission set and go into the objects permissions page
3) Add a permission on an object containing the character `(` or `)` (for example, let's use the `tabledata 5896 - "Inventory Adjmt. Entry (Order)"`
4) Grant full access to Read, Insert, Modify and Delete permissions (it does not matter)
5) Attempt to add a security filter on field `Order No.` with value `*TEST*`

=> You'll get the following error message

> The filter "@Inventory Adjmt. Entry (Order)" is not valid for the Object Name field on the AllObj table. An error occured while interpreting the filter: Did not expect '('. For more information, see https://go.microsoft.com/fwlink/?linkid=2158058.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/648753/214529183-acb72830-4bce-4944-a23d-b9331f5d141e.png)

**Comment by AlexanderYakunin** [comment]
I'm sorry but our team cannot process and fix bug reports here. We have technical support who is dedicated for that.

This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
