### ISSUE TITLE
[Suggestion] Create default github template with extra information?

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#21893]
We very often detect missing publishers on **sales** related object / processes, and thus create issues for these. 

Somewhat later, we discover the **same** events to be missing on the **purchase** side as well, forcing us to create another issue (ok) and waiting for the event to be included in a later build. (= additional delay)

It would be beneficial if the user (*) logging the event request, would be alerted to also check other 'related' objects, so all needed / related events can be added in the same build.

Maybe introducing a default github issue template might at least provide the user with some guidance on other 'domains' / objects to think of when logging issues?

> - Please verify the need for similar events in related objects. (e.g. sales vs purchase, customer vs vendor, invoice vs credit memo, ...)
> - Please search for functions with same name requiring a similar requested event.
> - ...

![image](https://user-images.githubusercontent.com/25268332/214792714-2f30fca2-3d1c-411e-81dc-06d9f450b82d.png)

_(*) Not sure if this would be possible to make this an internal rule as well for the **MS dev team** dealing with event request? Would be great if we compare sales and purchase objects, that (most) new events are always added in **both** (even if initially only requested on one side)_

**Comment by JesperSchulz** [comment]
Our templates are getting a do-over. We will consider this suggestion as well!
