### ISSUE TITLE
Post Code Lookup Country Code issue

### ISSUE THREAD

**Issue by debmitchell-tnp** [microsoft/ALAppExtensions#21890]
For post code lookup in GB version it is hard coded that country code should be GB on pages and there is no publisher to work around this. For many customers using GB version of NAV they have a country code set up of UK.  Also the web site for GetAddress.IO says "Simple APIs for UK Addresses".  The hardcoding limits how the functionality can currently be used.

The function below exists in few places for example customer card and contact card:-

    local procedure ShowPostcodeLookup(ShowInputFields: Boolean)
    var
        TempEnteredAutocompleteAddress: Record "Autocomplete Address" temporary;
        TempAutocompleteAddress: Record "Autocomplete Address" temporary;
        PostcodeBusinessLogic: Codeunit "Postcode Business Logic";
    begin
        if ("Country/Region Code" <> 'GB') and ("Country/Region Code" <> '') then
            exit;

        if not PostcodeBusinessLogic.IsConfigured or (("Post Code" = '') and not ShowInputFields) then
            exit;

        TempEnteredAutocompleteAddress.Address := Address;
        TempEnteredAutocompleteAddress.Postcode := "Post Code";

        if not PostcodeBusinessLogic.ShowLookupWindow(TempEnteredAutocompleteAddress, ShowInputFields, TempAutocompleteAddress) then
            exit;

        CopyAutocompleteFields(TempAutocompleteAddress);
        HandleAddressLookupVisibility();
    end;

Could this be changed to use a setup? Or publishers be added so that a different base country can be used?

**Comment by haoranpb** [comment]
Hi @debmitchell-tnp , thanks for reporting the issue!

We will be changing the hardcoded GB to include UK as well, the changes have been merged into master, we are current testing if everything works as expected before porting it down to 22.x branch

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56905.
