### ISSUE TITLE
Funktion SetExclReclEntries in Codeunit 5626 cannot be used for SaaS

### ISSUE THREAD

**Issue by t-jane** [microsoft/ALAppExtensions#21896]
Please change / delete the Scope OnPrem for this function, so that it can be used in extensions with Scope Cloud.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52844.
