### ISSUE TITLE
[Event Request] report 5405 "Calc. Consumption" - OnBeforeAssignItemTracking

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#21898]
local procedure AssignItemTracking(ProdOrderComponent: Record "Prod. Order Component"; ItemJournalLine: Record "Item Journal Line")
    var
        ...
        IsHandled: Boolean;
    begin
        //A200F0000.Event21.03.ns
        OnBeforeAssignItemTracking(ProdOrderComponent, ItemJournalLine, IsHandled);
        if IsHandled then
            exit;
        //A200F0000.Event21.03.ne

        if ItemJournalLine.Quantity >= 0 then
            ItemTrackingMgt.CopyItemTracking(ProdOrderComponent.RowID1(), ItemJournalLine.RowID1(), false)

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssignItemTracking(var ProdOrderComponent: Record "Prod. Order Component"; var ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52853.
