### ISSUE TITLE
Handle [Scope(onPrem)] in SaaS Version in spanish localization

### ISSUE THREAD

**Issue by mariomatilla** [microsoft/ALAppExtensions#21892]
Hi,
we need to call the codeunit 7000005 "Invoice-Split Payment" from our extension but I find that all the methods have the [Scope(OnPrem)] so I can't build it with target=Cloud.
![imagen](https://user-images.githubusercontent.com/37374313/214790842-3c6cd4c1-61b1-4de2-8f54-2ff7aededa03.png)

The same happens with this method on Payment Terms table, marked as [Scope(OnPrem)]
![imagen](https://user-images.githubusercontent.com/37374313/214792052-5b077353-93df-4c87-b74a-373e1d9e659c.png)

What surprises me is that standard execution on SaaS also uses this codeunit and methods without problems.
Thanks a lot in advance.

Kind regards,
Mario

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52844.
