### ISSUE TITLE
[Request for External] Page 490 Acc. Schedule Overview - request protected vars: NewCurrentSchedName + NewCurrentColumnName

### ISSUE THREAD

**Issue by srol001195** [microsoft/ALAppExtensions#21908]
Dear ALAppExtensions,

We would like to request the following vars as protected:

```
    var
        NewCurrentSchedName: Code[10];
        NewCurrentColumnName: Code[10];
```

Thank you,
SR

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52844.
