### ISSUE TITLE
[Event Request] table 246 "Requisition Line" - OnAfterUpdateDescription

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#21907]
Can you add event OnAfterUpdateDescription to the end of the UpdateDescription procedure in able 246 "Requisition Line"?
Rec as reference.

```
        if SalesLine.Get(SalesLine."Document Type"::Order, "Sales Order No.", "Sales Order Line No.") then begin
            Description := SalesLine.Description;
            "Description 2" := SalesLine."Description 2";
            OnUpdateDescriptionFromSalesLine(Rec, SalesLine);
        end;

        if "Vendor No." <> '' then
            UpdateItemReferenceDescription();

        // >>>>>>>>>>>>
        OnAfterUpdateDescription(Rec, Item, ItemVariant, CurrFieldNo);
        // <<<<<<<<<<<<
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52804.
