### ISSUE TITLE
[Event Request] Codeunit 10752 "SII Doc. Upload Management" add event in "XMLParseDocumentResponse"

### ISSUE THREAD

**Issue by JB92ARB** [microsoft/ALAppExtensions#21904]
Hi,

We need to add an event in the codeunit 10752 "SII Doc. Upload Management":

In the procedure called "XMLParseDocumentResponse":
![image](https://user-images.githubusercontent.com/86236240/214871981-04c08a29-b6bb-4804-a811-780939242e7b.png)

Event:
OnBeforeXMLParseDocumentResponse(XMLBuffer, SIIHistory, ParentEntryNo, IsHandled);

Integration Event:
[IntegrationEvent(false, false)]
local procedure OnBeforeXMLParseDocumentResponse(var XMLBuffer: Record "XML Buffer"; var SIIHistory: Record "SII History"; ParentEntryNo: Integer; var IsHandle: Boolean);
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53246.
