### ISSUE TITLE
[Event Request] Codeunit 10750 "SII XML Creator" add event in "PopulateXMLWithSalesInvoice" named "OnBeforeFillThirdPartyId"

### ISSUE THREAD

**Issue by JB92ARB** [microsoft/ALAppExtensions#21900]
Hi,

We need to add an event in the codeunit 10750 "SII XML Creator" named "OnBeforeFillThirdPartyId":

In the procedure called "PopulateXMLWithSalesInvoice":
![image](https://user-images.githubusercontent.com/86236240/214864138-dae7ef5e-29ef-419f-b854-9794a455da1e.png)

Event:
OnBeforeFillThirdPartyId(XMLNode, Customer."Country/Region Code", Customer.Name, Customer."VAT Registration No.", Customer."No.", true, SIIManagement.CustomerIsIntraCommunity(Customer."No."), Customer."Not in AEAT", SIIDocUploadState.IDType, CustLedgerEntry, IsHandled);

IntegrationEvent:
[IntegrationEvent(false, false)]
local procedure OnBeforeFillThirdPartyId(var XMLNode: DotNet XmlNode; CountryCode: Code[20]; Name: Text; VatNo: Code[20]; BackupVatId: Code[20]; NeedNombreRazon: Boolean; IsIntraCommunity: Boolean; IsNotInAEAT: Boolean; IDTypeInt: Integer; CustLedgerEntry: Record "Cust. Ledger Entry"; var IsHandled: Boolean)
begin
end;

**Comment by Vadim-Stepanenko** [comment]
We cannot provide events with dotnet parameters in them.
