### ISSUE TITLE
Add fieldgroups DropDown - Table "User Setup"

### ISSUE THREAD

**Issue by lorenzobuiatti** [microsoft/ALAppExtensions#21905]
It's possible to add a dropdown in User setup?

Why?
If a company has "User ID": domain\xyg43a1 
It would be convenient to have in the lookup view at least the "email" field to quickly find.
![image](https://user-images.githubusercontent.com/86967009/214874042-e87f23ba-1697-48f7-b140-7b00ea070fd9.png)

**Comment by JesperSchulz** [comment]
Sorry for leaving this one hanging for so long. It somehow got dropped on the floor.

This sounds like a great idea! However, this GitHub repository only handles issues with extending published apps, and extensibility in general, for the latest release of Business Central. I'd hence suggest you log your idea on [Business Central - Ideas](http://aka.ms/bcideas).
