### ISSUE TITLE
[Event Request] codeunit 7324 "Whse.-Activity-Post" OnReleaseSalesDocumentOnBeforeReopenSalesDocument

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#21917]
Can we please get the following event?
```al
local procedure ReleaseSalesDocument(var ModifyHeader: Boolean)
var
    SalesRelease: Codeunit "Release Sales Document";
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeReleaseSalesDocument(SalesHeader, WhseActivHeader, ModifyHeader, IsHandled);
    if IsHandled then
        exit;

    if (SalesHeader."Posting Date" <> WhseActivHeader."Posting Date") and (WhseActivHeader."Posting Date" <> 0D) then begin
        //+EVENT
        OnReleaseSalesDocumentOnBeforeReopenSalesDocument(SalesHeader, WhseActivHeader);
        //-EVENT
        SalesRelease.Reopen(SalesHeader);
        SalesRelease.SetSkipCheckReleaseRestrictions();
        SalesHeader.SetHideValidationDialog(true);
        SalesHeader.Validate("Posting Date", WhseActivHeader."Posting Date");
        OnReleaseSalesDocumentOnBeforeSalesReleaseRun(SalesHeader, WhseActivHeader);
        SalesRelease.Run(SalesHeader);
        OnReleaseSalesDocumentOnAfterSalesReleaseRun(SalesHeader, WhseActivHeader);
        ModifyHeader := true;
    end;
end;
```

```al
[IntegrationEvent(false, false)]
local procedure OnReleaseSalesDocumentOnBeforeReopenSalesDocument(var SalesHeader: Record "Sales Header"; WarehouseActivityHeader: Record "Warehouse Activity Header")
begin
end;
```

**Comment by Vadim-Stepanenko** [comment]
Can you use **OnBeforeReleaseSalesDocument** instead? Why you need this one?

**Comment by pri-kise** [comment]
@Vadim-Stepanenko we need to know in the Reopen of the Sales Document if the reopen was triggerd by the whse. acitivity posting. Therefore we set a single instance value before the reopening.
Currently we clear this single instance value in the event `OnReleaseSalesDocumentOnAfterSalesReleaseRun`.
Since, the OnBeforeReleaseSalesDocument provides a handled pattern, we can''t ensure that the event `OnReleaseSalesDocumentOnAfterSalesReleaseRun` is always triggered and that we reset our single instance value correctly.

Alternativly you could provide us with a new `OnAfterReleaseSalesDocument` Event that would get triggerd always; independed of the IsHandled Value.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
