### ISSUE TITLE
[Extensibility Enhancement] Enum 337 "Reservation Status" Extensible Property

### ISSUE THREAD

**Issue by UIBKH** [microsoft/ALAppExtensions#21913]
Dear Support,

We would like to be able to extend the Enum 337 "Reservation Status". This would allow us to migrate existing customizations.
Would it be possible to add the extensible property to it?

```
enum 337 "Reservation Status"
{
    AssignmentCompatibility = true;
    Extensible = true; //New Code

    value(0; "Reservation") { Caption = 'Reservation'; }
    value(1; "Tracking") { Caption = 'Tracking'; }
    value(2; "Surplus") { Caption = 'Surplus'; }
    value(3; "Prospect") { Caption = 'Prospect'; }
}
```

**Comment by UIBKH** [comment]
Any updates on this? Is it possible to make this enum extensible?

Thank you!

**Comment by UIBKH** [comment]
@AlexanderYakunin Any updates on this? Would it be possible to add the extensible property to this enum?

Thank you!

**Comment by AlexanderYakunin** [comment]
Yes, but not right now. We are at release phase for Wave 1 2023 and cannot take such changes into the code at this time.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53910.
