### ISSUE TITLE
[Event Request] Table 904 - "Assembly-to-Order Link" - OnBeforeReserveAsmToSale

### ISSUE THREAD

**Issue by UIBKH** [microsoft/ALAppExtensions#21910]
Dear Support,

We would like to add a new event OnBeforeReserveAsmToSale in the following function using the IsHandled pattern.
This would allow us to further customize the code and migrate existing customizations.

    procedure ReserveAsmToSale(var SalesLine: Record "Sales Line"; QtyToReserve: Decimal; QtyToReserveBase: Decimal)
    var
        ReservEntry: Record "Reservation Entry";
        TrackingSpecification: Record "Tracking Specification";
        AsmHeaderReserve: Codeunit "Assembly Header-Reserve";
        IsHandled: Boolean; //New  Code --++
    begin
        //New  Code --
        IsHandled := false;
        OnBeforeReserveAsmToSale(Rec, AsmHeader, SalesLine, TrackingSpecification, QtyToReserve, QtyToReserveBase, IsHandled);
        if IsHandled then
            exit;
        //New  Code ++
        if SalesLine."Document Type" <> SalesLine."Document Type"::Order then
            exit;

        if Type = Type::Sale then begin
            GetAsmHeader();

            AsmHeaderReserve.SetBinding(ReservEntry.Binding::"Order-to-Order");
            AsmHeaderReserve.SetDisallowCancellation(true);
            TrackingSpecification.InitTrackingSpecification(
                DATABASE::"Sales Line", SalesLine."Document Type".AsInteger(), SalesLine."Document No.", '', 0, SalesLine."Line No.",
                AsmHeader."Variant Code", AsmHeader."Location Code", AsmHeader."Qty. per Unit of Measure");
            AsmHeaderReserve.CreateReservationSetFrom(TrackingSpecification);
            AsmHeaderReserve.CreateReservation(AsmHeader, AsmHeader.Description, AsmHeader."Due Date", QtyToReserve, QtyToReserveBase);

            if SalesLine.Reserve = SalesLine.Reserve::Never then
                SalesLine.Reserve := SalesLine.Reserve::Optional;

            OnAfterReserveAsmToSale(Rec, AsmHeader, SalesLine, TrackingSpecification, QtyToReserve, QtyToReserveBase);
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeReserveAsmToSale(var AssembletoOrderLink: Record "Assemble-to-Order Link"; var AsmHeader: Record "Assembly Header"; var SalesLine: Record "Sales Line"; var TrackingSpecification: Record "Tracking Specification"; QtyToReserve: Decimal; QtyToReserveBase: Decimal; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52853.
