### ISSUE TITLE
Codeunit 1550 "Record Restriction Mgt." - OnCheckRecordHasUsageRestrictionsOnBeforeFindRecord

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#21925]
Can you please add the OnCheckRecordHasUsageRestrictionsOnBeforeFindRecord event to CheckRecordHasUsageRestrictions procedure in "Record Restriction Mgt." codeunit (1550)?

Actual Code:

    procedure CheckRecordHasUsageRestrictions(RecVar: Variant)
    var
        RestrictedRecord: Record "Restricted Record";
        RecRef: RecordRef;
        ErrorMessage: Text;
    begin
        RecRef.GetTable(RecVar);
        if RecRef.IsTemporary then
            exit;
        if RestrictedRecord.IsEmpty() then
            exit;

        RestrictedRecord.SetRange("Record ID", RecRef.RecordId);
        if not RestrictedRecord.FindFirst() then
            exit;

        ErrorMessage :=
          StrSubstNo(
            RecordRestrictedTxt,
            Format(Format(RestrictedRecord."Record ID", 0, 1))) + '\\' + RestrictedRecord.Details;

        Error(ErrorMessage);
    end;

Suggestion:

    procedure CheckRecordHasUsageRestrictions(RecVar: Variant)
    var
        RestrictedRecord: Record "Restricted Record";
        RecRef: RecordRef;
        ErrorMessage: Text;
    begin
        RecRef.GetTable(RecVar);
        if RecRef.IsTemporary then
            exit;
        if RestrictedRecord.IsEmpty() then
            exit;

        OnCheckRecordHasUsageRestrictionsOnBeforeFindRecord(RestrictedRecord, RecRef)
        RestrictedRecord.SetRange("Record ID", RecRef.RecordId);
        if not RestrictedRecord.FindFirst() then
            exit;

        ErrorMessage :=
          StrSubstNo(
            RecordRestrictedTxt,
            Format(Format(RestrictedRecord."Record ID", 0, 1))) + '\\' + RestrictedRecord.Details;

        Error(ErrorMessage);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCheckRecordHasUsageRestrictionsOnBeforeFindRecord (var RestrictedRecord: Record "Restricted Record"; RecRef: RecordRef)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52887.
