### ISSUE TITLE
page 422 "G/L Balance/Budget" - New Event request - OnBeforeOpenPage

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#21920]
We would like to request a new event on the "G/L Balance/Budget" page (422), in the OnOpenPage trigger.  We need the ability to override some fo the default actions the current code performs.

Thank you.

```
page 422 "G/L Balance/Budget"
...
    trigger OnOpenPage()
    var
        IsHandled: Boolean;  // New Variable
    begin
        // New Code
        IsHandled := false;
        OnBeforeOpenPage(Rec, IsHandled);
        if not IsHandled then begin
        // New Code end, next three lines indented
            GLSetup.Get();
            InitDefaultFilters();
            CODEUNIT.Run(CODEUNIT::"GLBudget-Open", Rec);
        end;  // New Code
        FindPeriod('');
    end;
...
    // New Event Definition
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOpenPage(var GLAccount: Record "G/L Account"; var IsHandled: Boolean)
    begin
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52887.
