### ISSUE TITLE
Codeunit 1550 "Record Restriction Mgt." - OnRestrictRecordUsageOnBeforeFindRecord

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#21922]
Can you please add the OnRestrictRecordUsageOnBeforeFindRecord event to RestrictRecordUsage procedure in "Record Restriction Mgt." codeunit (1550)?

Actual Code:

    procedure RestrictRecordUsage(RecVar: Variant; RestrictionDetails: Text)
    var
        RestrictedRecord: Record "Restricted Record";
        RecRef: RecordRef;
    begin
        RecRef.GetTable(RecVar);
        if RecRef.IsTemporary then
            exit;

        RestrictedRecord.SetRange("Record ID", RecRef.RecordId);
        if RestrictedRecord.FindFirst() then begin
            RestrictedRecord.Details := CopyStr(RestrictionDetails, 1, MaxStrLen(RestrictedRecord.Details));
            RestrictedRecord.Modify(true);
        end else begin
            RestrictedRecord.Init();
            RestrictedRecord."Record ID" := RecRef.RecordId;
            RestrictedRecord.Details := CopyStr(RestrictionDetails, 1, MaxStrLen(RestrictedRecord.Details));
            RestrictedRecord.Insert(true);
        end;
    end;

Suggestion:

    procedure RestrictRecordUsage(RecVar: Variant; RestrictionDetails: Text)
    var
        RestrictedRecord: Record "Restricted Record";
        RecRef: RecordRef;
    begin
        RecRef.GetTable(RecVar);
        if RecRef.IsTemporary then
            exit;

        OnRestrictRecordUsageOnBeforeFindRecord(RestrictedRecord, RecRef)
        RestrictedRecord.SetRange("Record ID", RecRef.RecordId);
        if RestrictedRecord.FindFirst() then begin
            RestrictedRecord.Details := CopyStr(RestrictionDetails, 1, MaxStrLen(RestrictedRecord.Details));
            RestrictedRecord.Modify(true);
        end else begin
            RestrictedRecord.Init();
            RestrictedRecord."Record ID" := RecRef.RecordId;
            RestrictedRecord.Details := CopyStr(RestrictionDetails, 1, MaxStrLen(RestrictedRecord.Details));
            RestrictedRecord.Insert(true);
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnRestrictRecordUsageOnBeforeFindRecord (var RestrictedRecord: Record "Restricted Record"; RecRef: RecordRef)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52887.
