### ISSUE TITLE
Codeunit 1535 "Approvals Mgmt." - OnIsGeneralJournalLineApprovalsWorkflowEnabled

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#21929]
Can you please add the OnIsGeneralJournalLineApprovalsWorkflowEnabled to IsGeneralJournalLineApprovalsWorkflowEnabled procedure in Codeunit "Approvals Mgmt." (1535)?

Actual Code:

    procedure IsGeneralJournalLineApprovalsWorkflowEnabled(var GenJournalLine: Record "Gen. Journal Line"): Boolean
    begin
        exit(WorkflowManagement.CanExecuteWorkflow(GenJournalLine,
            WorkflowEventHandling.RunWorkflowOnSendGeneralJournalLineForApprovalCode()));
    end;

Suggestion:

    procedure IsGeneralJournalLineApprovalsWorkflowEnabled(var GenJournalLine: Record "Gen. Journal Line") Result: Boolean
    var
        IsHandled: Boolean;
    begin
        OnIsGeneralJournalLineApprovalsWorkflowEnabled(GenJournalLine, IsHandled, Result);
        if IsHandled then
            exit(Result);
        exit(WorkflowManagement.CanExecuteWorkflow(GenJournalLine,
            WorkflowEventHandling.RunWorkflowOnSendGeneralJournalLineForApprovalCode()));
    end;

    [IntegrationEvent(false, false)]
     local procedure OnIsGeneralJournalLineApprovalsWorkflowEnabled(var GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean; var Result: Boolean)
     begin
     end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52887.
