### ISSUE TITLE
Codeunit 1535 "Approvals Mgmt." - OnIsGeneralJournalBatchApprovalsWorkflowEnabled

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#21928]
Can you please add the OnIsGeneralJournalBatchApprovalsWorkflowEnabled event to the IsGeneralJournalBatchApprovalsWorkflowEnabled procedure in Codeunit "Approvals Mgmt." (1535)?

Actual Code:

    procedure IsGeneralJournalBatchApprovalsWorkflowEnabled(var GenJournalBatch: Record "Gen. Journal Batch"): Boolean
    begin
        exit(WorkflowManagement.CanExecuteWorkflow(GenJournalBatch,
            WorkflowEventHandling.RunWorkflowOnSendGeneralJournalBatchForApprovalCode()));
    end;

Suggestion:

    procedure IsGeneralJournalBatchApprovalsWorkflowEnabled(var GenJournalBatch: Record "Gen. Journal Batch") Result: Boolean
    var
        IsHandled: Boolean;
    begin
        OnIsGeneralJournalBatchApprovalsWorkflowEnabled(GenJournalBatch, IsHandled, Result);
        if IsHandled then
            exit(Result)

        exit(WorkflowManagement.CanExecuteWorkflow(GenJournalBatch,
            WorkflowEventHandling.RunWorkflowOnSendGeneralJournalBatchForApprovalCode()));
    end;

    [IntegrationEvent(false, false)]
    local procedure OnIsGeneralJournalBatchApprovalsWorkflowEnabled(var GenJournalBatch: Record "Gen. Journal Batch"; var IsHandled: Boolean; var Result: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52887.
