### ISSUE TITLE
Codeunit 1550 "Record Restriction Mgt." - OnUpdateRestrictionOnBeforeModifyRecords

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#21924]
Can you please add the OnUpdateRestrictionOnBeforeModifyRecords event to UpdateRestriction procedure in "Record Restriction Mgt." codeunit (1550)?

Actual Code:

    procedure UpdateRestriction(RecVar: Variant; xRecVar: Variant)
    var
        RestrictedRecord: Record "Restricted Record";
        RecRef: RecordRef;
        xRecRef: RecordRef;
    begin
        xRecRef.GetTable(xRecVar);
        RecRef.GetTable(RecVar);

        if RecRef.IsTemporary then
            exit;

        if RestrictedRecord.IsEmpty() then
            exit;

        RestrictedRecord.SetRange("Record ID", xRecRef.RecordId);
        RestrictedRecord.ModifyAll("Record ID", RecRef.RecordId);
    end;

Suggestion:

    procedure UpdateRestriction(RecVar: Variant; xRecVar: Variant)
    var
        RestrictedRecord: Record "Restricted Record";
        RecRef: RecordRef;
        xRecRef: RecordRef;
    begin
        xRecRef.GetTable(xRecVar);
        RecRef.GetTable(RecVar);

        if RecRef.IsTemporary then
            exit;

        if RestrictedRecord.IsEmpty() then
            exit;

        OnUpdateRestrictionOnBeforeModifyRecords(RestrictedRecord, RecRef, xRecRef)
        RestrictedRecord.SetRange("Record ID", xRecRef.RecordId);
        RestrictedRecord.ModifyAll("Record ID", RecRef.RecordId);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnUpdateRestrictionOnBeforeModifyRecords (var RestrictedRecord: Record "Restricted Record"; RecRef: RecordRef, xRecRef: RecordRef)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52887.
