### ISSUE TITLE
Codeunit 1550 "Record Restriction Mgt." - OnAllowRecordUsageOnBeforeDeleteRecords 

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#21923]
Can you please add the OnAllowRecordUsageOnBeforeDeleteRecords event to AllowRecordUsage procedure in "Record Restriction Mgt." codeunit (1550)?

Actual Code:

    procedure AllowRecordUsage(RecVar: Variant)
    var
        RestrictedRecord: Record "Restricted Record";
        RecRef: RecordRef;
    begin
        RecRef.GetTable(RecVar);
        if RecRef.IsTemporary then
            exit;
        if RestrictedRecord.IsEmpty() then
            exit;

        RestrictedRecord.SetRange("Record ID", RecRef.RecordId);
        RestrictedRecord.LockTable(true);
        RestrictedRecord.DeleteAll(true);
    end;

Suggestion:

    procedure AllowRecordUsage(RecVar: Variant)
    var
        RestrictedRecord: Record "Restricted Record";
        RecRef: RecordRef;
    begin
        RecRef.GetTable(RecVar);
        if RecRef.IsTemporary then
            exit;
        if RestrictedRecord.IsEmpty() then
            exit;

        OnAllowRecordUsageOnBeforeDeleteRecords(RestrictedRecord, RecRef)
        RestrictedRecord.SetRange("Record ID", RecRef.RecordId);
        RestrictedRecord.LockTable(true);
        RestrictedRecord.DeleteAll(true);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAllowRecordUsageOnBeforeDeleteRecords (var RestrictedRecord: Record "Restricted Record"; RecRef: RecordRef)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52887.
