### ISSUE TITLE
Codeunit 1535 "Approvals Mgmt." - OnTrySendJournalLineApprovalRequests

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#21931]
Can you please add the OnBeforeTrySendJournalLineApprovalRequests and the  OnTrySendJournalLineApprovalRequests events to TrySendJournalLineApprovalRequests procedure in Codeunit "Approvals Mgmt." (1535)?

Actual Code:

    procedure TrySendJournalLineApprovalRequests(var GenJournalLine: Record "Gen. Journal Line")
    var
        LinesSent: Integer;
    begin
        if GenJournalLine.Count = 1 then
            CheckGeneralJournalLineApprovalsWorkflowEnabled(GenJournalLine);

        repeat
            if WorkflowManagement.CanExecuteWorkflow(GenJournalLine,
                 WorkflowEventHandling.RunWorkflowOnSendGeneralJournalLineForApprovalCode()) and
               not HasOpenApprovalEntries(GenJournalLine.RecordId)
            then begin
                OnSendGeneralJournalLineForApproval(GenJournalLine);
                LinesSent += 1;
            end;
        until GenJournalLine.Next() = 0;

        case LinesSent of
            0:
                Message(NoApprovalsSentMsg);
            GenJournalLine.Count:
                Message(PendingApprovalForSelectedLinesMsg);
            else
                Message(PendingApprovalForSomeSelectedLinesMsg);
        end;
    end;

Suggestion:

    procedure TrySendJournalLineApprovalRequests(var GenJournalLine: Record "Gen. Journal Line")
    var
        LinesSent: Integer;
    begin
        if GenJournalLine.Count = 1 then
            CheckGeneralJournalLineApprovalsWorkflowEnabled(GenJournalLine);

        OnBeforeTrySendJournalLineApprovalRequests(GenJournalLine);
        repeat
            OnTrySendJournalLineApprovalRequests(GenJournalLine);
            if WorkflowManagement.CanExecuteWorkflow(GenJournalLine,
                 WorkflowEventHandling.RunWorkflowOnSendGeneralJournalLineForApprovalCode()) and
               not HasOpenApprovalEntries(GenJournalLine.RecordId)
            then begin
                OnSendGeneralJournalLineForApproval(GenJournalLine);
                LinesSent += 1;
            end;
        until GenJournalLine.Next() = 0;

        case LinesSent of
            0:
                Message(NoApprovalsSentMsg);
            GenJournalLine.Count:
                Message(PendingApprovalForSelectedLinesMsg);
            else
                Message(PendingApprovalForSomeSelectedLinesMsg);
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTrySendJournalLineApprovalRequests(var GenJournalLine: Record "Gen. Journal Line")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnTrySendJournalLineApprovalRequests(var GenJournalLine: Record "Gen. Journal Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52887.
