### ISSUE TITLE
[Event Request] Table 349 "Dimension Value" - OnAfterCheckIfDimValueUsed

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#21936]
Hello, we would like to get the following new Event OnAfterCheckIfDimValueUsed in the procedure CheckIfDimValueUsed. Thanks!

```
    procedure CheckIfDimValueUsed(): Boolean
    var
        IsUsed: Boolean;
    begin
        DimSetEntry.SetCurrentKey("Dimension Value ID");
        DimSetEntry.SetRange("Dimension Value ID", "Dimension Value ID");
        IsUsed := not DimSetEntry.IsEmpty;
        OnAfterCheckIfDimValueUsed(Rec, IsUsed);
        exit(IsUsed);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckIfDimValueUsed(DimensionValue: Record "Dimension Value"; var IsUsed: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52890.
