### ISSUE TITLE
Codeunit 1105 "Transfer GL Entries to CA" - OnTransferGLtoCA

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#21932]
Can you please add the OnTransferGLtoCA event to TransferGLtoCA procedure in Codeunit "Transfer GL Entries to CA" (1105)?

Actual Code:

    procedure TransferGLtoCA()
    begin
        ClearAll();

        CostAccMgt.LinkCostTypesToGLAccounts();

        Window.Open(Text001);

        BatchRun := true;
        GetGLEntries();

        Window.Close();
    end;

Suggestion:

    procedure TransferGLtoCA()
    var
        SkipLinkCostTypesToGLAccounts: Boolean;
    begin
        ClearAll();

        OnTransferGLtoCA(SkipLinkCostTypesToGLAccounts)
        if not SkipLinkCostTypesToGLAccounts then
            CostAccMgt.LinkCostTypesToGLAccounts();

        Window.Open(Text001);

        BatchRun := true;
        GetGLEntries();

        Window.Close();
    end;

    [IntegrationEvent(false, false)]
    local procedure OnTransferGLtoCA(var SkipLinkCostTypesToGLAccounts: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52890.
