### ISSUE TITLE
[GB] Make Tax Digital - pageextension 10538 "MTD OAuth 2.0 Setup" - Important field hidden on SaaS

### ISSUE THREAD

**Issue by simteq-arturas** [microsoft/ALAppExtensions#21930]
**Localization**: GB
**Extension**: Making Tax Digital Localization for United Kingdom
**Version**: 21.3.51409.52252
**Environment type**: SaaS Production
**Object**: pageextension 10538 "MTD OAuth 2.0 Setup"

**Problem description**:
Make Tax Digital (MTD) extension for GB version of BC modifies extends "OAuth 2.0 Setup" card, aka "Service Connection".
The extension, among other things, modifies existing field:
```
        modify("Enter Authorization Code")
        {
            Visible = not IsSaaS and IsMTD;
        }
```
The idea is that users generate Authorization Code on HRMC website, return to BC and enter it there, since there is no automatic way to do it. However, with the field being hidden in SaaS environment, the task becomes impossible and prevents users from using MTD.
Moreover, the field might be used by other OAuth 2.0 Setup and should they require Authorization Code, they will fail as well, since both IsSaaS and IsMTD will be false

**Solution suggestion**:
Remove modification from page field "Enter Authorization Code"

**Comment by JesperSchulz** [comment]
Internally closed as "Won't Fix" by @ventselartur. Syncing state to GitHub.
