### ISSUE TITLE
[Request for External] "Azure AD Graph User".IsUserDelegatedAdmin/IsUserDelegatedHelpdesk

### ISSUE THREAD

**Issue by jwikman** [microsoft/ALAppExtensions#21942]
Please remove the OnPrem scope from functions `IsUserDelegatedAdmin()` and `IsUserDelegatedHelpdesk()` in codeunit 9024 "Azure AD Graph User".

`IsUserDelegatedAdmin()` is already available for SaaS in the "Identity Management" codeunit, but currently (with GDAP) I have no way to check if a user is a Delegated Helpdesk agent. 

So please remove the OnPrem scope from `IsUserDelegatedHelpdesk()` at least.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 12927.
