### ISSUE TITLE
Codeunit 235 "G/L Reg.-Gen. Ledger" - OnGLRegGenLedgOnBeforeRunPage

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#21948]
Can you please add the OnGLRegGenLedgOnBeforeRunPage event to the OnRun trigger in Codeunit "G/L Reg.-Gen. Ledger" (235)?

Actual Code:

    trigger OnRun()
    begin
        GLEntry.SetRange("Entry No.", "From Entry No.", "To Entry No.");
        PAGE.Run(PAGE::"General Ledger Entries", GLEntry);
    end;

Suggestion:

    trigger OnRun()
    begin
        GLEntry.SetRange("Entry No.", "From Entry No.", "To Entry No.");
        OnGLRegGenLedgOnBeforeRunPage(GLEntry)
        PAGE.Run(PAGE::"General Ledger Entries", GLEntry);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnGLRegGenLedgOnBeforeRunPage(var GLEntry: Record "G/L Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53049.
