### ISSUE TITLE
[Event Request] Table 5870 - "BOM Buffer" - OnBeforeTransferFromProdComp

### ISSUE THREAD

**Issue by FGRKH** [microsoft/ALAppExtensions#21945]
Dear Support,

We would like to add a new event OnBeforeTransferFromProdComp in the following Procedure below, using the IsHandled pattern.
This would allow us to further customize the code and migrate existing customizations.

    procedure TransferFromProdComp(var EntryNo: Integer; ProdBOMLine: Record "Production BOM Line"; NewIndentation: Integer; ParentQtyPer: Decimal; ParentScrapQtyPer: Decimal; ParentScrapPct: Decimal; NeedByDate: Date; ParentLocationCode: Code[10]; ParentItem: Record Item; BOMQtyPerUOM: Decimal)
    var
        BOMItem: Record Item;
        UOMMgt: Codeunit "Unit of Measure Management";
        CostCalculationMgt: Codeunit "Cost Calculation Management";
        IsHandled: Boolean;  //New  Code --++
    begin
        //New  Code --
        IsHandled := false;
        OnBeforeTransferFromProdComp(EntryNo, Rec, ProdBOMLine, ParentItem, ParentQtyPer, ParentScrapPct, ParentScrapQtyPer, BOMQtyPerUOM, ParentLocationCode, NewIndentation, NeedByDate, IsHandled);
        if IsHandled then
        exit;
        //New  Code ++
        Init();
        EntryNo += 1;
        "Entry No." := EntryNo;
        Type := Type::Item;

        BOMItem.Get(ProdBOMLine."No.");
        InitFromItem(BOMItem);

        if ParentItem."Lot Size" = 0 then
            ParentItem."Lot Size" := 1;

        Description := ProdBOMLine.Description;
        "Qty. per Parent" :=
          CostCalculationMgt.CalcCompItemQtyBase(
            ProdBOMLine, WorkDate(),
            CostCalculationMgt.CalcQtyAdjdForBOMScrap(ParentItem."Lot Size", ParentScrapPct), ParentItem."Routing No.", true) /
          UOMMgt.GetQtyPerUnitOfMeasure(BOMItem, ProdBOMLine."Unit of Measure Code") /
          BOMQtyPerUOM / ParentItem."Lot Size";
        "Qty. per Top Item" := Round(ParentQtyPer * "Qty. per Parent", UOMMgt.QtyRndPrecision());
        "Qty. per Parent" := Round("Qty. per Parent", UOMMgt.QtyRndPrecision());

        "Scrap Qty. per Parent" := "Qty. per Parent" - (ProdBOMLine.Quantity / BOMQtyPerUOM);
        "Scrap Qty. per Top Item" :=
          "Qty. per Top Item" -
          Round((ParentQtyPer - ParentScrapQtyPer) * ("Qty. per Parent" - "Scrap Qty. per Parent"), UOMMgt.QtyRndPrecision());
        "Scrap Qty. per Parent" := Round("Scrap Qty. per Parent", UOMMgt.QtyRndPrecision());

        "Qty. per BOM Line" := ProdBOMLine."Quantity per";
        "Unit of Measure Code" := ProdBOMLine."Unit of Measure Code";
        "Variant Code" := ProdBOMLine."Variant Code";
        "Location Code" := ParentLocationCode;
        "Lead-Time Offset" := ProdBOMLine."Lead-Time Offset";
        "Needed by Date" := NeedByDate;
        Indentation := NewIndentation;
        if ProdBOMLine."Calculation Formula" = ProdBOMLine."Calculation Formula"::"Fixed Quantity" then
            "Calculation Formula" := ProdBOMLine."Calculation Formula";

        OnTransferFromProdCompCopyFields(Rec, ProdBOMLine, ParentItem, ParentQtyPer);
        Insert(true);
        OnAfterTransferFromProdComp(Rec, ProdBOMLine, ParentItem, EntryNo)
    end;

Event Signature:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeTransferFromProdComp(var EntryNo: Integer; var BOMBuffer: Record "BOM Buffer"; ProdBOMLine: Record "Production BOM Line"; ParentItem: Record Item; ParentQtyPer: Decimal; ParentScrapPct: Decimal; ParentScrapQtyPer: Decimal; BOMQtyPerUOM: Decimal; ParentLocationCode: Code[10]; NewIndentation: Integer; NeedByDate: Date; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
