### ISSUE TITLE
[Event Request] Table 5870 - "BOM Buffer" - OnBeforeUpdateAbleToMake

### ISSUE THREAD

**Issue by FGRKH** [microsoft/ALAppExtensions#21947]
Dear Support,

We would like to add a new event OnBeforeUpdateAbleToMake in the following Procedure below, using the IsHandled pattern. This would allow us to further customize the code and migrate existing customizations.

    procedure UpdateAbleToMake(AvailQty: Decimal)
    var
        Item: Record Item;
        UOMMgt: Codeunit "Unit of Measure Management";
        QtyPerUOM: Decimal;
        IsHandled: Boolean;  //New  Code --++
    begin
        //New  Code --
        IsHandled := false;
        OnBeforeUpdateAbleToMake(Rec, AvailQty, IsHandled);
        if IsHandled then
        exit;
        //New  Code ++
        QtyPerUOM := 1;
        if Type = Type::Item then begin
            Item.Get("No.");
            QtyPerUOM := UOMMgt.GetQtyPerUnitOfMeasure(Item, "Unit of Measure Code");
        end;

        if "Is Leaf" then begin
            if "Qty. per Parent" <> 0 then
                "Able to Make Parent" := Round(AvailQty / ("Qty. per Parent" * QtyPerUOM), UOMMgt.QtyRndPrecision());
            if "Qty. per Top Item" <> 0 then
                "Able to Make Top Item" := Round(AvailQty / ("Qty. per Top Item" * QtyPerUOM), UOMMgt.QtyRndPrecision());
        end else
            if Indentation = 0 then begin
                "Able to Make Parent" := "Able to Make Parent";
                "Able to Make Top Item" := "Able to Make Top Item";
            end else begin
                if "Qty. per Parent" <> 0 then
                    "Able to Make Parent" :=
                      Round((AvailQty + "Able to Make Parent") / ("Qty. per Parent" * QtyPerUOM), UOMMgt.QtyRndPrecision());
                if "Qty. per Top Item" <> 0 then
                    "Able to Make Top Item" :=
                      Round(AvailQty / ("Qty. per Top Item" * QtyPerUOM) + "Able to Make Top Item", UOMMgt.QtyRndPrecision());
            end;

        SetAbleToMakeToZeroIfNegative();
    end;

Event Signature:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateAbleToMake(var BOMBuffer: Record "BOM Buffer"; var AvailQty: Decimal; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
