### ISSUE TITLE
[Event Request] Table 7302 - "Bin Content" - OnBeforeCalcQtyAvailToTakeUOM

### ISSUE THREAD

**Issue by FGRKH** [microsoft/ALAppExtensions#21951]
Dear Support,

We would like to add a new event OnBeforeCalcQtyAvailToTakeUOM in the following Procedure below, using the IsHandled pattern. This would allow us to further customize the code and migrate existing customizations.

    procedure CalcQtyAvailToTakeUOM(): Decimal
    var
        IsHandled: Boolean;  //New  Code --++
    begin
        //New  Code --
        IsHandled := false;
        OnBeforeCalcQtyAvailToTakeUOM(Rec, IsHandled);
        if IsHandled then
        exit;
        //New  Code ++
        GetItem("Item No.");
        if Item."No." <> '' then
            exit(
              Round(CalcQtyAvailToTake(0) / UOMMgt.GetQtyPerUnitOfMeasure(Item, "Unit of Measure Code"), UOMMgt.QtyRndPrecision()));
    end;

Event Signature:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCalcQtyAvailToTakeUOM(var BinContent: Record "Bin Content"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52890.
