### ISSUE TITLE
[Event Request] - OnBeforeCheckWhseQtyPicked codeunit 1011 "Job Jnl.-Check Line"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#21953]
Dear ALAppExtensions Team:

Please consider adding a new event publisher in codeunit 1011 "Job Jnl.-Check Line"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnBeforeCheckWhseQtyPicked(var JobJnlLine: Record "Job Journal Line"; var IsHandled: Boolean);
begin
end;

The code in procedure "CheckWhseQtyPicked" in codeunit 1011 "Job Jnl.-Check Line" would be modified as follows:

OLD CODE:

....

    local procedure CheckWhseQtyPicked(var JobJournalLine: Record "Job Journal Line")
    var
        JobPlanningLine: Record "Job Planning Line";
        WhseValidateSourceLine: Codeunit "Whse. Validate Source Line";
    begin
        if WhseValidateSourceLine.IsWhsePickRequiredForJobJnlLine(JobJournalLine) or WhseValidateSourceLine.IsInventoryPickRequiredForJobJnlLine(JobJournalLine) then
            if not CalledFromInvtPutawayPick then
                if JobPlanningLine.Get(JobJournalLine."Job No.", JobJournalLine."Job Task No.", JobJournalLine."Job Planning Line No.") and (JobPlanningLine."Qty. Picked" - JobPlanningLine."Qty. Posted" < JobJournalLine.Quantity) then
                    JobPlanningLine.FieldError("Qty. Picked", ErrorInfo.Create(StrSubstNo(WhseRemainQtyPickedErr, JobPlanningLine."Job No.", JobPlanningLine."Line No.", JobJournalLine.Quantity + JobPlanningLine."Qty. Posted" - JobPlanningLine."Qty. Picked"), true));
    end;

....

NEW CODE:

    local procedure CheckWhseQtyPicked(var JobJournalLine: Record "Job Journal Line")
    var
        JobPlanningLine: Record "Job Planning Line";
        WhseValidateSourceLine: Codeunit "Whse. Validate Source Line";
        IsHandled: Boolean;
    begin
       IsHandled := false;
        
       OnBeforeCheckWhseQtyPicked(JobJournalLine, IsHandled);

        if not IsHandled then
          if WhseValidateSourceLine.IsWhsePickRequiredForJobJnlLine(JobJournalLine) or 
              WhseValidateSourceLine.IsInventoryPickRequiredForJobJnlLine(JobJournalLine) then
                if not CalledFromInvtPutawayPick then
                   if JobPlanningLine.Get(JobJournalLine."Job No.", JobJournalLine."Job Task No.", JobJournalLine."Job Planning Line No.") 
                      and (JobPlanningLine."Qty. Picked" - JobPlanningLine."Qty. Posted" < JobJournalLine.Quantity) then
                            JobPlanningLine.FieldError("Qty. Picked", ErrorInfo.Create(StrSubstNo(WhseRemainQtyPickedErr, 
                             JobPlanningLine."Job No.", JobPlanningLine."Line No.", JobJournalLine.Quantity + JobPlanningLine."Qty. Posted" -                        
                              JobPlanningLine."Qty. Picked"), true));
    end;

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
