### ISSUE TITLE
[Event Request] Codeunit 5763 "Whse.-Post Shipment" - Function "HandleSalesLine" 

### ISSUE THREAD

**Issue by NilsGruettner** [microsoft/ALAppExtensions#21959]
Hi,

it would be great if you could add an event publisher to skip the following code block:

```
if (WhseShptHeader."Shipment Date" <> 0D) and
   (SalesLine."Shipment Date" <> WhseShptHeader."Shipment Date") and
   ("Qty. to Ship" = "Qty. Outstanding")
then begin
    SalesLine."Shipment Date" := WhseShptHeader."Shipment Date";
    ModifyLine := true;
    if ATOLineFound then
        if AsmHeader.Get(ATOLink."Assembly Document Type", ATOLink."Assembly Document No.") then begin
            AsmHeader."Due Date" := WhseShptHeader."Shipment Date";
            AsmHeader.Modify(true);
        end;
  end;
```

The update of the shipment date leads to problems with a custom planning tool, that also allows the creation of warehouse shipments for partial sales order lines. Especially the ATO sub-block is problematic, because this change can not simply be reverted in OnBeforeSalesLineModify, as the AsmHeader.Modify is performed instantly.

Right now, the only way to skip the code block is to tamper with the provided variables in OnBeforeHandleSalesLine, which could lead to problems in other event subscribers using those variable values.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
