### ISSUE TITLE
[Request for External] Report 12116 "Vendor Account Bills List" field OnlyOpened

### ISSUE THREAD

**Issue by FabioC34** [microsoft/ALAppExtensions#21958]
Hello, can you please set the variable "OnlyOpened" in R12116 (IT Localization) as protected var?

```
protected var
        OnlyOpened: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52844.
