### ISSUE TITLE
[Event Request] Table 7302 - "Bin Content" - OnBeforeCheckDecreaseBinContent

### ISSUE THREAD

**Issue by FGRKH** [microsoft/ALAppExtensions#21954]
Dear Support,

We would like to add a new event OnBeforeCheckDecreaseBinContent in the following Procedure below, using the IsHandled pattern. This would allow us to further customize the code and migrate existing customizations.

    procedure CheckDecreaseBinContent(Qty: Decimal; var QtyBase: Decimal; DecreaseQtyBase: Decimal)
    var
        WhseActivLine: Record "Warehouse Activity Line";
        QtyAvailToPickBase: Decimal;
        QtyAvailToPick: Decimal;
        IsHandled: Boolean;  //New  Code --++
    begin
        //New  Code --
        IsHandled := false;
        OnBeforeCheckDecreaseBinContent(Rec, Qty, QtyBase, DecreaseQtyBase, IsHandled);
        if IsHandled then
        exit;
        //New  Code ++
        if "Block Movement" in ["Block Movement"::Outbound, "Block Movement"::All] then
            FieldError("Block Movement");

        GetLocation("Location Code");
        if "Bin Code" = Location."Adjustment Bin Code" then
            exit;

        WhseActivLine.SetCurrentKey(
          "Item No.", "Bin Code", "Location Code", "Action Type",
          "Variant Code", "Unit of Measure Code", "Breakbulk No.",
          "Activity Type", "Lot No.", "Serial No.", "Original Breakbulk");
        WhseActivLine.SetRange("Item No.", "Item No.");
        WhseActivLine.SetRange("Bin Code", "Bin Code");
        WhseActivLine.SetRange("Location Code", "Location Code");
        WhseActivLine.SetRange("Unit of Measure Code", "Unit of Measure Code");
        WhseActivLine.SetRange("Variant Code", "Variant Code");

        if Location."Allow Breakbulk" then begin
            WhseActivLine.SetRange("Action Type", WhseActivLine."Action Type"::Take);
            WhseActivLine.SetRange("Original Breakbulk", true);
            WhseActivLine.SetRange("Breakbulk No.", 0);
            WhseActivLine.CalcSums("Qty. (Base)");
            DecreaseQtyBase := DecreaseQtyBase + WhseActivLine."Qty. (Base)";
        end;

        QtyAvailToPickBase := CalcTotalQtyAvailToTake(DecreaseQtyBase);
        OnCheckDecreaseBinContentOnAfterCalcTotalQtyAvailToTake(WhseActivLine, QtyAvailToPickBase, DecreaseQtyBase);
        if QtyAvailToPickBase < QtyBase then begin
            GetItem("Item No.");
            QtyAvailToPick :=
              Round(QtyAvailToPickBase / UOMMgt.GetQtyPerUnitOfMeasure(Item, "Unit of Measure Code"), UOMMgt.QtyRndPrecision());
            if QtyAvailToPick = Qty then
                QtyBase := QtyAvailToPickBase // rounding issue- qty is same, but not qty (base)
            else
                FieldError("Quantity (Base)", StrSubstNo(Text006, Abs(QtyBase)));
        end;
    end;

Event Signature:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckDecreaseBinContent(var BinContent: Record "Bin Content"; Qty: Decimal; var QtyBase: Decimal; DecreaseQtyBase: Decimal ; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52890.
