### ISSUE TITLE
Include the option to add password protection to PDFs.

### ISSUE THREAD

**Issue by maciejmlocek** [microsoft/ALAppExtensions#21965]
Hi!

It is common to create a report as a PDF file, set a password on it, and send it via email. All of these actions can be performed in Business Central, except for setting a password.

Although I am aware that an Azure Function can be used to achieve this, it seems inefficient to require an external service and incur additional costs just for password protection. Including [PDFSharp](https://github.com/empira/PDFsharp) DLL and creating wrapper codeunits for it, which can be invoked from AL, would solve this issue.

I don't know the amount of work required to make a DLL accessible, but if you're willing to do it, I can help with wrapping it into a module to ease the effort.

Sorry if this issue should have been raised elsewhere.

**Comment by AlexanderYakunin** [comment]
Yes, this is cannot be processed here, instead you can create new idea on aka.ms/bcideas portal.

**Comment by maciejmlocek** [comment]
Then I guess we close it?

**Comment by pri-kise** [comment]
@maciejmlocek there has been an post in yammer related to pdf improvements: https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1521728434880512&search_origin=global&scoring=linear1Y-prankie-group-private-higher&match=any-exact&search_sort=relevance&page=1&search=pdf%20improvements

Additionally there was a form to vote for PDF improvements for Business Central, too:
https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRznSZgt8x05Fgs5pWicNY_tURU9IRTBMNDBaVENMWk41NDlVNExCVkNUMi4u

**Comment by maciejmlocek** [comment]
> @maciejmlocek there has been an post in yammer related to pdf improvements: https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=1521728434880512&search_origin=global&scoring=linear1Y-prankie-group-private-higher&match=any-exact&search_sort=relevance&page=1&search=pdf%20improvements
> 
> 
> 
> Additionally there was a form to vote for PDF improvements for Business Central, too:
> 
> https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRznSZgt8x05Fgs5pWicNY_tURU9IRTBMNDBaVENMWk41NDlVNExCVkNUMi4u

Thanks for sharing this!
