### ISSUE TITLE
[Event Request] table 11000001 "Payment History" - OnBeforeGenerateExportfilename

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#21968]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnBeforeGenerateExportfilename' to be added to procedure 'GenerateExportfilename' in table 11000001 "Payment History" (NL version only).

````
    procedure GenerateExportfilename(New: Boolean) FileName: Text[250]
    begin
        OnBeforeGenerateExportfilename(Rec, New); //**4PS>MS.n
        if ("File on Disk" = '') or New then begin
            "Day Serial Nr." := GetNextDaySerialNo();
            "Sent On" := Today;
            "File on Disk" := GenerateNewFileName();
            "Sent By" := UserId();
        end else
            "Number of Copies" := "Number of Copies" + 1;

        Modify();
        exit("File on Disk");
    end;
````
````
    [IntegrationEvent(false, false)] 
    local procedure OnBeforeGenerateExportfilename(PaymentHistory: Record "Payment History"; New: Boolean)
    begin
    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53230.
