### ISSUE TITLE
Codeunit 13 "Gen. Jnl.-Post Batch" - OnBeforeCheckDocNoBasedOnNoSeries

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#21963]
Can you please add the OnBeforeCheckDocNoBasedOnNoSeries event to the ProcessBalanceOfLines procedure in Codeunit "Gen. Jnl.-Post Batch" (13)?

Actual Code:

    local procedure ProcessBalanceOfLines(var GenJnlLine: Record "Gen. Journal Line"; var GenJnlLineVATInfoSource: Record "Gen. Journal Line"; var VATInfoSourceLineIsInserted: Boolean; var LastLineNo: Integer; CurrentICPartner: Code[20])
    var
        VATPostingSetup: Record "VAT Posting Setup";
        BalVATPostingSetup: Record "VAT Posting Setup";
        ErrorMessage: Text;
        LastDocTypeOption: Option;
        ForceCheckBalance: Boolean;
        IsProcessingKeySet: Boolean;
        IsHandled: Boolean;
    begin
        IsProcessingKeySet := false;
        OnBeforeProcessBalanceOfLines(GenJnlLine, GenJnlBatch, GenJnlTemplate, IsProcessingKeySet);
        if not IsProcessingKeySet then
            if GenJnlTemplate."Force Doc. Balance" then
                GenJnlLine.SetCurrentKey("Document No.", "Posting Date");
        LineCount := 0;
        LastDate := 0D;
        LastDocType := LastDocType::" ";
        LastDocNo := '';
        LastFAAddCurrExchRate := 0;
        TempGenJnlLine3.Reset();
        TempGenJnlLine3.DeleteAll();
        VATEntryCreated := false;
        CurrentBalance := 0;
        CurrentBalanceReverse := 0;
        CurrencyBalance := 0;

        with GenJnlLine do begin
            FindSet(true, false);
            LastCurrencyCode := "Currency Code";

            repeat
                LineCount := LineCount + 1;
                UpdateDialog(RefPostingState::"Checking balance", LineCount, NoOfRecords);

                if not EmptyLine() then begin
                    if not PreviewMode then
                        CheckDocNoBasedOnNoSeries(LastDocNo, GenJnlBatch."No. Series", NoSeriesMgt);
                    if "Posting No. Series" <> '' then
                        TestField("Posting No. Series", GenJnlBatch."Posting No. Series");
                    CheckCorrection(GenJnlLine);
                end;
                LastDocTypeOption := LastDocType.AsInteger();
                OnBeforeIfCheckBalance(GenJnlTemplate, GenJnlLine, LastDocTypeOption, LastDocNo, LastDate, ForceCheckBalance, SuppressCommit, IsHandled);
                LastDocType := "Gen. Journal Document Type".FromInteger(LastDocTypeOption);
                if not IsHandled then
                    if ForceCheckBalance or ("Posting Date" <> LastDate) or GenJnlTemplate."Force Doc. Balance" and
                       (("Document Type" <> LastDocType) or ("Document No." <> LastDocNo))
                    then begin
                        CheckBalance(GenJnlLine);
                        CurrencyBalance := 0;
                        LastCurrencyCode := "Currency Code";
                        TempGenJnlLine3.Reset();
                        TempGenJnlLine3.DeleteAll();
                    end;

                if IsNonZeroAmount(GenJnlLine) then begin
                    if LastFAAddCurrExchRate <> "FA Add.-Currency Factor" then
                        CheckAddExchRateBalance(GenJnlLine);
                    if (CurrentBalance = 0) and (CurrentICPartner = '') then begin
                        TempGenJnlLine3.Reset();
                        TempGenJnlLine3.DeleteAll();
                        if VATEntryCreated and VATInfoSourceLineIsInserted then
                            UpdateGenJnlLineWithVATInfo(GenJnlLine, GenJnlLineVATInfoSource, StartLineNo, LastLineNo);
                        VATEntryCreated := false;
                        VATInfoSourceLineIsInserted := false;
                        StartLineNo := "Line No.";
                    end;
                    if CurrentBalanceReverse = 0 then
                        StartLineNoReverse := "Line No.";
                    UpdateLineBalance();
                    OnAfterUpdateLineBalance(GenJnlLine);
                    CurrentBalance := CurrentBalance + "Balance (LCY)";
                    if "Recurring Method".AsInteger() >= "Recurring Method"::"RF Reversing Fixed".AsInteger() then
                        CurrentBalanceReverse := CurrentBalanceReverse + "Balance (LCY)";

                    UpdateCurrencyBalanceForRecurringLine(GenJnlLine);
                end;

                LastDate := "Posting Date";
                LastDocType := "Document Type";
                if not EmptyLine() then
                    LastDocNo := "Document No.";
                LastFAAddCurrExchRate := "FA Add.-Currency Factor";
                if GenJnlTemplate."Force Doc. Balance" then begin
                    if not VATPostingSetup.Get("VAT Bus. Posting Group", "VAT Prod. Posting Group") then
                        Clear(VATPostingSetup);
                    if not BalVATPostingSetup.Get("Bal. VAT Bus. Posting Group", "Bal. VAT Prod. Posting Group") then
                        Clear(BalVATPostingSetup);
                    VATEntryCreated :=
                      VATEntryCreated or
                      (("Account Type" = "Account Type"::"G/L Account") and ("Account No." <> '') and
                       ("Gen. Posting Type" in ["Gen. Posting Type"::Purchase, "Gen. Posting Type"::Sale]) and
                       (VATPostingSetup."VAT %" <> 0)) or
                      (("Bal. Account Type" = "Bal. Account Type"::"G/L Account") and ("Bal. Account No." <> '') and
                       ("Bal. Gen. Posting Type" in ["Bal. Gen. Posting Type"::Purchase, "Bal. Gen. Posting Type"::Sale]) and
                       (BalVATPostingSetup."VAT %" <> 0));
                    if TempGenJnlLine3.IsCustVendICAdded(GenJnlLine) then begin
                        GenJnlLineVATInfoSource := GenJnlLine;
                        VATInfoSourceLineIsInserted := true;
                    end;
                    if (TempGenJnlLine3.Count > 1) and VATEntryCreated then begin
                        ErrorMessage := Text009 + Text010;
                        Error(ErrorMessage, "Document Type", "Document No.", "Posting Date");
                    end;
                    if (TempGenJnlLine3.Count > 1) and (CurrentICPartner <> '') and
                       (GenJnlTemplate.Type = GenJnlTemplate.Type::Intercompany)
                    then
                        Error(
                          Text029,
                          "Document Type", "Document No.", "Posting Date");
                    LastLineNo := "Line No.";
                end;
            until Next() = 0;
            CheckBalance(GenJnlLine);
            CopyFields(GenJnlLine);
            if VATEntryCreated and VATInfoSourceLineIsInserted then
                UpdateGenJnlLineWithVATInfo(GenJnlLine, GenJnlLineVATInfoSource, StartLineNo, LastLineNo);
        end;

        OnAfterProcessBalanceOfLines(GenJnlLine);
    end;

Suggestion:

    local procedure ProcessBalanceOfLines(var GenJnlLine: Record "Gen. Journal Line"; var GenJnlLineVATInfoSource: Record "Gen. Journal Line"; var VATInfoSourceLineIsInserted: Boolean; var LastLineNo: Integer; CurrentICPartner: Code[20])
    var
        VATPostingSetup: Record "VAT Posting Setup";
        BalVATPostingSetup: Record "VAT Posting Setup";
        ErrorMessage: Text;
        LastDocTypeOption: Option;
        ForceCheckBalance: Boolean;
        IsProcessingKeySet: Boolean;
        IsHandled: Boolean;
        IsChecked: Boolean;
    begin
        IsProcessingKeySet := false;
        OnBeforeProcessBalanceOfLines(GenJnlLine, GenJnlBatch, GenJnlTemplate, IsProcessingKeySet);
        if not IsProcessingKeySet then
            if GenJnlTemplate."Force Doc. Balance" then
                GenJnlLine.SetCurrentKey("Document No.", "Posting Date");
        LineCount := 0;
        LastDate := 0D;
        LastDocType := LastDocType::" ";
        LastDocNo := '';
        LastFAAddCurrExchRate := 0;
        TempGenJnlLine3.Reset();
        TempGenJnlLine3.DeleteAll();
        VATEntryCreated := false;
        CurrentBalance := 0;
        CurrentBalanceReverse := 0;
        CurrencyBalance := 0;

        with GenJnlLine do begin
            FindSet(true, false);
            LastCurrencyCode := "Currency Code";

            repeat
                LineCount := LineCount + 1;
                UpdateDialog(RefPostingState::"Checking balance", LineCount, NoOfRecords);

                IsChecked := false;
                if not EmptyLine() then begin
                    if not PreviewMode then begin
                        OnBeforeCheckDocNoBasedOnNoSeries(GenJnlLine, GenJnlBatch, IsChecked);
                        if not IsChecked then
                            CheckDocNoBasedOnNoSeries(LastDocNo, GenJnlBatch."No. Series", NoSeriesMgt);
                    end;
                    if "Posting No. Series" <> '' then
                        TestField("Posting No. Series", GenJnlBatch."Posting No. Series");
                    CheckCorrection(GenJnlLine);
                end;
                LastDocTypeOption := LastDocType.AsInteger();
                OnBeforeIfCheckBalance(GenJnlTemplate, GenJnlLine, LastDocTypeOption, LastDocNo, LastDate, ForceCheckBalance, SuppressCommit, IsHandled);
                LastDocType := "Gen. Journal Document Type".FromInteger(LastDocTypeOption);
                if not IsHandled then
                    if ForceCheckBalance or ("Posting Date" <> LastDate) or GenJnlTemplate."Force Doc. Balance" and
                       (("Document Type" <> LastDocType) or ("Document No." <> LastDocNo))
                    then begin
                        CheckBalance(GenJnlLine);
                        CurrencyBalance := 0;
                        LastCurrencyCode := "Currency Code";
                        TempGenJnlLine3.Reset();
                        TempGenJnlLine3.DeleteAll();
                    end;

                if IsNonZeroAmount(GenJnlLine) then begin
                    if LastFAAddCurrExchRate <> "FA Add.-Currency Factor" then
                        CheckAddExchRateBalance(GenJnlLine);
                    if (CurrentBalance = 0) and (CurrentICPartner = '') then begin
                        TempGenJnlLine3.Reset();
                        TempGenJnlLine3.DeleteAll();
                        if VATEntryCreated and VATInfoSourceLineIsInserted then
                            UpdateGenJnlLineWithVATInfo(GenJnlLine, GenJnlLineVATInfoSource, StartLineNo, LastLineNo);
                        VATEntryCreated := false;
                        VATInfoSourceLineIsInserted := false;
                        StartLineNo := "Line No.";
                    end;
                    if CurrentBalanceReverse = 0 then
                        StartLineNoReverse := "Line No.";
                    UpdateLineBalance();
                    OnAfterUpdateLineBalance(GenJnlLine);
                    CurrentBalance := CurrentBalance + "Balance (LCY)";
                    if "Recurring Method".AsInteger() >= "Recurring Method"::"RF Reversing Fixed".AsInteger() then
                        CurrentBalanceReverse := CurrentBalanceReverse + "Balance (LCY)";

                    UpdateCurrencyBalanceForRecurringLine(GenJnlLine);
                end;

                LastDate := "Posting Date";
                LastDocType := "Document Type";
                if not EmptyLine() then
                    LastDocNo := "Document No.";
                LastFAAddCurrExchRate := "FA Add.-Currency Factor";
                if GenJnlTemplate."Force Doc. Balance" then begin
                    if not VATPostingSetup.Get("VAT Bus. Posting Group", "VAT Prod. Posting Group") then
                        Clear(VATPostingSetup);
                    if not BalVATPostingSetup.Get("Bal. VAT Bus. Posting Group", "Bal. VAT Prod. Posting Group") then
                        Clear(BalVATPostingSetup);
                    VATEntryCreated :=
                      VATEntryCreated or
                      (("Account Type" = "Account Type"::"G/L Account") and ("Account No." <> '') and
                       ("Gen. Posting Type" in ["Gen. Posting Type"::Purchase, "Gen. Posting Type"::Sale]) and
                       (VATPostingSetup."VAT %" <> 0)) or
                      (("Bal. Account Type" = "Bal. Account Type"::"G/L Account") and ("Bal. Account No." <> '') and
                       ("Bal. Gen. Posting Type" in ["Bal. Gen. Posting Type"::Purchase, "Bal. Gen. Posting Type"::Sale]) and
                       (BalVATPostingSetup."VAT %" <> 0));
                    if TempGenJnlLine3.IsCustVendICAdded(GenJnlLine) then begin
                        GenJnlLineVATInfoSource := GenJnlLine;
                        VATInfoSourceLineIsInserted := true;
                    end;
                    if (TempGenJnlLine3.Count > 1) and VATEntryCreated then begin
                        ErrorMessage := Text009 + Text010;
                        Error(ErrorMessage, "Document Type", "Document No.", "Posting Date");
                    end;
                    if (TempGenJnlLine3.Count > 1) and (CurrentICPartner <> '') and
                       (GenJnlTemplate.Type = GenJnlTemplate.Type::Intercompany)
                    then
                        Error(
                          Text029,
                          "Document Type", "Document No.", "Posting Date");
                    LastLineNo := "Line No.";
                end;
            until Next() = 0;
            CheckBalance(GenJnlLine);
            CopyFields(GenJnlLine);
            if VATEntryCreated and VATInfoSourceLineIsInserted then
                UpdateGenJnlLineWithVATInfo(GenJnlLine, GenJnlLineVATInfoSource, StartLineNo, LastLineNo);
        end;

        OnAfterProcessBalanceOfLines(GenJnlLine);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckDocNoBasedOnNoSeries(var GenJnlLine: Record "Gen. Journal Line"; var GenJnlBatch: Record "Gen. Journal Batch"; var IsChecked: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53049.
