### ISSUE TITLE
[Event Request] Codeunit 74 change OnCopyItemChargeAssgntOnBeforeFindPurchLine2 event

### ISSUE THREAD

**Issue by bachii1010** [microsoft/ALAppExtensions#21966]
Hi All,

In Codeunit 74 "Purch.-Get Receipt" change the OnCopyItemChargeAssgntOnBeforeFindPurchLine2 publisher to add extra parameter as below:

before:
 [IntegrationEvent(false, false)]    local procedure OnCopyItemChargeAssgntOnBeforeFindPurchLine2(var PurchLine2: Record "Purchase Line"; var ItemChargeAssgntPurch2: Record "Item Charge Assignment (Purch)")    
begin    
end;

after
[IntegrationEvent(false, false)]    local procedure OnCopyItemChargeAssgntOnBeforeFindPurchLine2(var PurchLine2: Record "Purchase Line"; var ItemChargeAssgntPurch2: Record "Item Charge Assignment (Purch)"; PurchRcptLine: Record "Purch. Rcpt. Line")    
begin    
end;

Also where this publisher is called change it like this:
OnCopyItemChargeAssgntOnBeforeFindPurchLine2(PurchLine2, ItemChargeAssgntPurch2, PurchRcptLine);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53049.
