### ISSUE TITLE
FEFO picking cannot create pick when lot is on warehouse activity lines

### ISSUE THREAD

**Issue by developerchristiaens** [microsoft/ALAppExtensions#21976]
**Scenario:**
Having an Item with two different Lot Numbers (e.g. L001 and L002) both with the same expiration date (e.g. 12/12/2023) stored in pick bins of a location setup with Directed Put&Pick.
Then, create some warehouse movements to move everything from L001 to other pick bins.
Create a sales order to ship a small part of that item.
Create a warehouse shipment.
Try to create a warehouse pick. This will fail with the message there is nothing to handle.

This is wrong, because there is still lot number L002 to pick from, which is not on any warehouse movement or other warehouse activity lines.

**Cause of error**
The error is in Code-unit 7312 "Create Pick", where the local procedure CreateTempItemTrkgLines does not take into account the quantity that is already on take-lines of warehouse activity lines. This makes the QtyCanBePicked larger than what is available. 
The procedure stops looping the EntrySummary records as soon as RemQtyToPickBase = 0. 

**Possible Solution**
Maybe it is better to create TempItemTrkgLine records for each EntrySummary. Other solution can be to change the calculation of QtyCanBePicked.

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
