### ISSUE TITLE
[Event Request] Page 344 - Navigate - OnAfterFindCostEntries

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#21973]
Dear ALAppExtensions team,

through this issue we would like to request adding event publisher `OnAfterFindCostEntries` in Page 344 Navigate with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnAfterFindCostEntries(var DocumentEntry: Record "Document Entry"; DocNoFilter: Text; PostingDateFilter: Text)
begin
end;
```
which would be called as follows in `FindCostEntries`:
```AL
local procedure FindCostEntries()
begin
    if CostEntry.ReadPermission() then begin
        CostEntry.Reset();
        CostEntry.SetCurrentKey("Document No.", "Posting Date");
        CostEntry.SetFilter("Document No.", DocNoFilter);
        CostEntry.SetFilter("Posting Date", PostingDateFilter);
        InsertIntoDocEntry(Rec, DATABASE::"Cost Entry", CostEntry.TableCaption, CostEntry.Count);
    end;
    // >>>> New >>>>>>>>>>>>>>>>
    OnAfterFindCostEntries(Rec, DocNoFilter, PostingDateFilter);
    // <<<< New <<<<<<<<<<<<<<<<
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
