### ISSUE TITLE
[Funktion Request]  page 344 Navigate - ShowRecords

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#21971]
Hello, can you please set the following procedure as a global funktion.

`local procedure ShowRecords()`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53117.
