### ISSUE TITLE
[Funktion Request]  table 96 "G/L Budget Entry" - 

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#21975]
Hello, can you please set the following procedure as a global funktion?

`local procedure CheckIfBlocked()`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53117.
