### ISSUE TITLE
[Function Request] codeunit 80 "Sales-Post" CopyAndCheckItemCharge

### ISSUE THREAD

**Issue by Dym71** [microsoft/ALAppExtensions#21979]
Hello,
We would like to have CopyAndCheckItemCharge procedure declared as global. We use it in our document validation codeunit and we don't want to duplicate code.

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53117.
