### ISSUE TITLE
[Event Change Request]  page 344 Navigate - OnAfterSetSource

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#21972]
Hello,  can you add another variable PostingDateFilter in Event OnAfterSetSource?

```
DocTypeEnable := SourceType2 <> 0;
        SourceTypeEnable := SourceType2 <> 0;
        SourceNoEnable := SourceType2 <> 0;
        SourceNameEnable := SourceType2 <> 0;

        OnAfterSetSource(SourceType2, SourceType, SourceNo, SourceName, PostingDateFilter);
    end;

    local procedure SetSourceForPurchase()
```

```
 [IntegrationEvent(true, false)]
    local procedure OnAfterSetSource(var SourceType2: Integer; var SourceType: Text[30]; SourceNo: Code[20]; var SourceName: Text[100]; var PostingDateFilter: Text)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
