### ISSUE TITLE
Defferal Schedule Start Date validation on GL Allow Posting Dates, should be linked to Deferral dates instead 

### ISSUE THREAD

**Issue by Michel-up** [microsoft/ALAppExtensions#21978]
Start date in page Edit Deferral Shedule
![image](https://user-images.githubusercontent.com/92575139/216023733-1be437b8-722d-4a7b-b181-4faf45eb6b87.png)

When changing the start date in Deferral Schedule, error that Start date cannot be changed due to the limit dates in field Allow posting to in General ledger Setup/User setup. It should be limited by the field Allow deferral posting from.
The date limits seem to work for deferrals when posting, but not if changing the Start date in the Deferral Shedule if outside Allow posting from/to before posting.

![image](https://user-images.githubusercontent.com/92575139/216024007-748f13bf-2a7b-43ee-849f-7dcb3811148b.png)

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
