### ISSUE TITLE
[Event Request] table 7000 "Price List Header" - OnAfterBlankDefaults

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#21981]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnAfterBlankDefaults' to be added to procedure 'BlankDefaults' in table 7000 "Price List Header".

````
    procedure BlankDefaults()
    begin
        if Rec."Allow Updating Defaults" then begin
            Rec."Source Type" := Rec."Source Type"::All;
            SetSourceNo('', '');
            Rec."Currency Code" := '';
            Rec."Starting Date" := 0D;
            Rec."Ending Date" := 0D;
            OnAfterBlankDefaults(Rec); //**4PS>MS.n
        end;
    end;
````
````
    [IntegrationEvent(false, false)]
    local procedure OnAfterBlankDefaults(var PriceListHeader: Record "Price List Header")
    begin
    end;
````

**Comment by KlaasKleermaker** [comment]
If 'var PriceListHeader: Record "Price List Header"' is replaced with 'IncludeSender = true', that's fine for us too.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
