### ISSUE TITLE
[Event Request] Codeunit 103 - OnBeforeRunCustEntryEdit

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#2198]
We need the following Event in Codeunit 103 in OnRun:

![image](https://user-images.githubusercontent.com/47414309/56660016-cfe0e880-669e-11e9-9325-a693924dd4ff.png)

The signature should look like this:
**LOCAL [IntegrationEvent] OnBeforeRunCustEntryEdit(VAR Rec2 : Record "Cust. Ledger Entry";VAR CustLedgEntry2 : Record "Cust. Ledger Entry";VAR DtldCustLedgEntry2 : Record "Detailed Cust. Ledg. Entry")**
Please note that all parameters are used as VAR.
Thanks!

**Comment by AlexanderYakunin** [comment]
There is already event OnBeforeCustLedgEntryModify(CustLedgEntry,Rec) in this codeunit. Why do you need OnBefore event, assuming CustLedgEntry will be overwritten AFTER this event?

**Comment by AJasp** [comment]
With this event we would have the opportunity to do a CustLedgEntry.CHANGECOMPANY
