### ISSUE TITLE
[Event Request] table 7022 "Price Worksheet Line" - OnAfterCopySourceFrom

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#21983]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnAfterCopySourceFrom' to be added to procedure 'CopySourceFrom' in table 7022 "Price Worksheet Line".

````
    procedure CopySourceFrom(PriceListHeader: Record "Price List Header")
    begin
        "Source Group" := PriceListHeader."Source Group";
        "Source Type" := PriceListHeader."Source Type";
        SetSourceNo(PriceListHeader."Parent Source No.", PriceListHeader."Source No.");
        "Source ID" := PriceListHeader."Source ID";
        OnAfterCopySourceFrom(PriceListHeader, Rec);
    end;
````
````
    [IntegrationEvent(false, false)]
    local procedure OnAfterCopySourceFrom(PriceListHeader: Record "Price List Header"; var PriceWorksheetLine: Record "Price Worksheet Line")
    begin
    end;
````

**Comment by KlaasKleermaker** [comment]
If 'var PriceWorksheetLine: Record "Price Worksheet Line"' is replaced with 'IncludeSender = true', that's fine for us too.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
