### ISSUE TITLE
[Event Request] codeunit 7036 "Price Source - Job" - OnAfterFillAdditionalFields

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#21988]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnAfterFillAdditionalFields' to be added to procedure 'FillAdditionalFields' in codeunit 7036 "Price Source - Job".

````
    local procedure FillAdditionalFields(var PriceSource: Record "Price Source")
    begin
        PriceSource.Description := Job.Description;
        PriceSource."Currency Code" := Job."Currency Code";
        OnAfterFillAdditionalFields(PriceSource, Job); //**4PS>MS.n
    end;
````
````
    [IntegrationEvent(false, false)]
    local procedure OnAfterFillAdditionalFields(var PriceSource: Record "Price Source"; Job: Record Job)
    begin
    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
