### ISSUE TITLE
[Event Request] codeunit 7035 "Price Source - Vendor" - OnAfterFillAdditionalFields

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#21989]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnAfterFillAdditionalFields' to be added to procedure 'FillAdditionalFields' in codeunit 7035 "Price Source - Vendor".

````
    local procedure FillAdditionalFields(var PriceSource: Record "Price Source")
    begin
        PriceSource.Description := Vendor.Name;
        PriceSource."Currency Code" := Vendor."Currency Code";
        PriceSource."Price Includes VAT" := Vendor."Prices Including VAT";
        PriceSource."VAT Bus. Posting Gr. (Price)" := Vendor."VAT Bus. Posting Group";
        OnAfterFillAdditionalFields(PriceSource, Vendor); //**4PS>MS.n
    end;
````
````
    [IntegrationEvent(false, false)]
    local procedure OnAfterFillAdditionalFields(var PriceSource: Record "Price Source"; Vendor: Record Vendor)
    begin
    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
