### ISSUE TITLE
[Event Request] Table 11400 - "CBG Statement" - OnBeforeCheckBalance

### ISSUE THREAD

**Issue by FGRKH** [microsoft/ALAppExtensions#21980]
Dear Support,

We would like to add a new event OnBeforeCheckBalance in the following Procedure below, using the IsHandled pattern. This would allow us to further customize the code and migrate existing customizations.

    procedure CheckBalance()
    var
        IsHandled: Boolean;  //New  Code --++
    begin
        //New  Code --
        IsHandled := false;
        OnBeforeCheckBalance(Rec, IsHandled);
        if IsHandled then
        exit;
        //New  Code ++
        CalcFields("Net Change Debit", "Net Change Credit");

        if "Opening Balance" - "Net Change Debit" + "Net Change Credit" <> "Closing Balance" then
            if Confirm(
                 StrSubstNo(
                   Text1000005 +
                   Text1000006 +
                   Text1000007,
                   "Opening Balance",
                   -"Net Change Debit" + "Net Change Credit",
                   "Closing Balance", Abs("Opening Balance" - "Net Change Debit" + "Net Change Credit" - "Closing Balance")), false)
            then begin
                "Closing Balance" := "Opening Balance" - "Net Change Debit" + "Net Change Credit";
                Modify();
                Commit();
            end else
                Error(Text1000008);
    end;

Event Signature:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckBalance(var CBGStatement: Record "CBG Statement"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53230.
