### ISSUE TITLE
[Event Request] Report 5601 "Fixed Asset - List"

### ISSUE THREAD

**Issue by PeterSchoenmaker** [microsoft/ALAppExtensions#21997]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnBeforeOnAfterGetRecord' to be added to trgigger'OnAfterGetRecord' in report 5601 "Fixed Asset - List";

````
    trigger OnAfterGetRecord()
    var
        SkipFixedAsset: Boolean;
    begin
        SkipFixedAsset := Inactive;
        OnBeforeOnAfterGetRecord("Fixed Asset", SkipFixedAsset);
        if SkipFixedAsset then
            CurrReport.Skip();
         ---
    end;
            
            
           
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnAfterGetRecord(var FixedAsset: Record "Fixed Asset"; var SkipFixedAsset: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52838.
