### ISSUE TITLE
[Event Request] codeunit 7021 "Purchase Line - Price" - OnAfterIsDiscountAllowed

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#21990]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnAfterIsDiscountAllowed' to be added to procedure 'IsDiscountAllowed' in codeunit 7021 "Purchase Line - Price".

````
    procedure IsDiscountAllowed() Result: Boolean;
    begin
        Result := DiscountIsAllowed or not PriceCalculated;
        OnAfterIsDiscountAllowed(PurchaseLine, PriceCalculated, Result); //**4PS>MS.n
    end;
````
````
    [IntegrationEvent(false, false)]
    local procedure OnAfterIsDiscountAllowed(PurchaseLine: Record "Purchase Line"; PriceCalculated: Boolean; var Result: Boolean)
    begin
    end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
