### ISSUE TITLE
[Event Request] Table 5900 "Service Header" - OnBeforePriceMsgIfServLinesExist

### ISSUE THREAD

**Issue by srol001195** [microsoft/ALAppExtensions#21999]
Dear ALAppExtensions Team,

Please consider adding the following "IsHandled" event subscriber. We want to be able to bypass this message by default, even if service lines exist.

Event execution:
```
    local procedure PriceMsgIfServLinesExist(ChangedFieldName: Text[100])
    //<REQUEST> init IsHandled
    var
        IsHandled: Boolean;
    //</REQUEST>
    begin
        //<REQUEST>
        IsHandled := false;
        OnBeforePriceMsgIfServLinesExist(Rec, IsHandled);
        if IsHandled then
            exit;
        //</REQUEST>
        if ServLineExists then
            Message(
              Text019,
              ChangedFieldName);
    end;
```
Event Signature:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforePriceMsgIfServLinesExist(var ServiceHeader: Record "Service Header";var IsHandled: Boolean)
    begin
    end;
```

Thank you,
SR

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52890.
