### ISSUE TITLE
[Request For External] Remove scope OnPrem in Service Line - procedure ShowItemSub

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#21994]
Hi Team,

in order to be able to change app target to cloud, could the scope OnPrem be removed in Table "Service Line" for procedure ShowItemSub?

``` AL
 [Scope('OnPrem')]
    procedure ShowItemSub()
    var
        ItemSubstMgt: Codeunit "Item Subst.";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeShowItemSub(Rec, IsHandled);
        if IsHandled then
            exit;

        ItemSubstMgt.ItemServiceSubstGet(Rec);
    end;
```

Thanks,
Christian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52844.
