### ISSUE TITLE
Allow the Payment Reconciliation Journal to match against existing Bank Ledger Entries

### ISSUE THREAD

**Issue by geeknikolai** [Microsoft/ALAppExtensions#220]
I put an idea onto the ideas page (https://experience.dynamics.com/ideas/idea/?ideaid=89d21a1e-bc9a-e811-b96f-0003ff68935d) but I was suggested to put it here instead/as well. 

The Payment Reconciliation Journal has a severe limitation in that it does not recognise when a Bank Ledger has already been posted - the most common example is Vendor Payments. We should be able to match against these unreconciled Bank Ledger entries, and ideally it should try to auto-match as well. 

In comparison the Bank Acc. Reconciliation does do this - including the auto-match. Behind the scenes it uses the same Table and Posting Codeunit as the other Bank Rec so this should be possible?

**Comment by JesperSchulz** [comment]
Having the issue logged on the bcideas site is sufficient. Your request is getting tracked through that site. Closing this issue.
