### ISSUE TITLE
[Protected var] page 1572 "VAT Entries Preview Subform" - Emphasize

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#22006]
Can you please move `Emphasize` to the protected var section in page 1572 "VAT Entries Preview Subform" so we can reuse the same styling for page extension fields?

Same for page 1571 "G/L Entries Preview Subform" as well.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52844.
