### ISSUE TITLE
Request to add an UsageCategory to page 5096 "Task List"

### ISSUE THREAD

**Issue by DonHendriksen** [microsoft/ALAppExtensions#22005]
Hi,
There is no Task overview page which can be found via search. Hereby a request to add a UsageCategory to page 5096 "Task List" so it can be found via search as well.
Thanks in advance.
Regards, Don

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 52844.
