### ISSUE TITLE
[Event Change] Report 1320  OnSetReportFieldPlaceholders

### ISSUE THREAD

**Issue by AndriiHrynyuk** [microsoft/ALAppExtensions#2200]
Hi,
We need some modifications to an existing event OnSetReportFieldPlaceholders in **Report 1320 Notification Email**.  The Field3Label, Field3Value are necessary as parameters.
Current publisher:
` OnSetReportFieldPlaceholders(RecRef,Field1Label,Field1Value,Field2Label,Field2Value);  event`
Needed publisher
`OnSetReportFieldPlaceholders(RecRef,Field1Label,Field1Value,Field2Label,Field2Value,Field3Label,Field3Value); `

Could you please do this change?

Thanks,

**Comment by dtkb** [comment]
The problem I see is that said publisher passes `Field3Label, Field3Value` as `var` to subscribers, allowing us to set those fields to our own values - but then the `case "Notification Entry".Type` will override them in most cases, i.e. when `Type` is `Approval`.

A better fix than https://github.com/microsoft/ALAppExtensions/issues/10021 might be to add a `var Handled: Boolean` argument to `OnSetReportFieldPlaceholders()`, and only enter the `case` if we have `not Handled` setting the fields in a subscriber. But I guess I'll wait and see if this change lands and is sufficient for us.
