### ISSUE TITLE
Expanding functionality for storing EFT files in blob storage and sharepoint not only in local computer.

### ISSUE THREAD

**Issue by XhevatTafaj** [microsoft/ALAppExtensions#22000]
Dear ALAppExtensions Team,

We would like to request the expansion of the standard application for North America (NA) version.
Our client has a request that the EFT files generated by the Payment Journal can be stored in a blob storage.
Our client operates on SAAS and therefore we are limited in achieving our goal of sending EFT files to Blob storage or SharePoint.
The EFT file generation functionality stores the files in the server directory, so it physically stores them on the server.
We have investigated the code and have concluded that through some small changes to the standard code, we can achieve this goal.

Below I am writing the details of what exactly we want:
In codeunit 10094 "Export EFT (ACH)" there is a function("DownloadWebclientZip") that downloads files to the user's computer (takes the files from the server and downloads them to the local computer).
By extending the DownloadWebclientZip function we want to achieve the possibility of reading the contents of files and storing them in a blob.

### **Actual Code:**
 [Scope('OnPrem')]
    procedure DownloadWebclientZip(var TempNameValueBuffer: Record "Name/Value Buffer" temporary; ZipFileName: Text; var DataCompression: Codeunit "Data Compression")
    var
        TempBlob: Codeunit "Temp Blob";
        ZipTempBlob: Codeunit "Temp Blob";
        ServerTempFileInStream: InStream;
        ZipInStream: InStream;
        ZipOutStream: OutStream;
        ToFile: Text;
    begin
        OnBeforeDownloadWebclientZip(TempNameValueBuffer, TempEraseFileNameValueBuffer, ZipFileName, DataCompression);
        // Download the .zip file containing the reports if one was generated (usually from being on the web client)
        if (ZipFileName <> '') and TempNameValueBuffer.FindSet() then
            // If there's a single file, download it directly instead of the zip file
            if TempNameValueBuffer.Count = 1 then
                FileManagement.DownloadHandler(TempNameValueBuffer.Value, '', '', '', TempNameValueBuffer.Name)
            else begin
                repeat
                    FileManagement.BLOBImportFromServerFile(TempBlob, TempNameValueBuffer.Value);
                    TempBlob.CreateInStream(ServerTempFileInStream);
                    DataCompression.AddEntry(ServerTempFileInStream, TempNameValueBuffer.Name);
                    TempEraseFileNameValueBuffer.AddNewEntry(TempNameValueBuffer.Value, '');
                until TempNameValueBuffer.Next() = 0;
                ZipTempBlob.CreateOutStream(ZipOutStream);
                DataCompression.SaveZipArchive(ZipOutStream);
                DataCompression.CloseZipArchive();
                ZipTempBlob.CreateInStream(ZipInStream);
                ToFile := ZipDownloadTxt;
                DownloadFromStream(ZipInStream, '', '', '', ToFile);
            end;

        CleanupTempFiles();
    end;

The code snippet below is what we produced as our solution. We welcome any other solutions that achieve this goal.
### **Suggestion:**
procedure DownloadWebclientZip(var TempNameValueBuffer: Record "Name/Value Buffer" temporary; ZipFileName: Text; var DataCompression: Codeunit "Data Compression")
    var
        TempBlob: Codeunit "Temp Blob";
        ZipTempBlob: Codeunit "Temp Blob";
        ServerTempFileInStream: InStream;
        ZipInStream: InStream;
        ZipOutStream: OutStream;
        ToFile: Text;
        DownloadWebclient: Boolean;
    begin
        DownloadWebclient := True;
        OnBeforeDownloadWebclientZip(TempNameValueBuffer, TempEraseFileNameValueBuffer, ZipFileName, DataCompression, DownloadWebclient);
        // Download the .zip file containing the reports if one was generated (usually from being on the web client)
        if (ZipFileName <> '') and TempNameValueBuffer.FindSet() then
            if DownloadWebclient then begin
                // If there's a single file, download it directly instead of the zip file
                if TempNameValueBuffer.Count = 1 then
                    FileManagement.DownloadHandler(TempNameValueBuffer.Value, '', '', '', TempNameValueBuffer.Name)
                else begin
                    repeat
                        FileManagement.BLOBImportFromServerFile(TempBlob, TempNameValueBuffer.Value);
                        TempBlob.CreateInStream(ServerTempFileInStream);
                        DataCompression.AddEntry(ServerTempFileInStream, TempNameValueBuffer.Name);
                        TempEraseFileNameValueBuffer.AddNewEntry(TempNameValueBuffer.Value, '');
                    until TempNameValueBuffer.Next() = 0;
                    ZipTempBlob.CreateOutStream(ZipOutStream);
                    DataCompression.SaveZipArchive(ZipOutStream);
                    DataCompression.CloseZipArchive();
                    ZipTempBlob.CreateInStream(ZipInStream);
                    ToFile := ZipDownloadTxt;
                    DownloadFromStream(ZipInStream, '', '', '', ToFile);
                end;
            end else
                repeat
                    // We want here to have a posibility to import file content into stream.
                    FileManagement.BLOBImportFromServerFile(TempBlob, TempNameValueBuffer.Value);
                    OnAfterImportFileContentToStream(TempBlob);
                until TempNameValueBuffer.Next() = 0;

        CleanupTempFiles();
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDownloadWebclientZip(var TempNameValueBuffer: Record "Name/Value Buffer" temporary; TempEraseFileNameValueBuffer: Record "Name/Value              Buffer" temporary; ZipFileName: Text; var DataCompression: Codeunit "Data Compression"; var DownloadWebclient: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterImportFileContentToStream(var TempBlob: Codeunit "Temp Blob")
    begin
    end;

**Comment by XhevatTafaj** [comment]
Hi , 
Any news for this request.

Thanks.

**Comment by AndersLarsenMicrosoft** [comment]
If still relevant then create a new event request
