### ISSUE TITLE
[Request for External] Report 12176 "Suggest Customer Bills" field CustBillHeader

### ISSUE THREAD

**Issue by FabioC34** [microsoft/ALAppExtensions#22008]
Hello, can you please set the variable "CustBillHeader" in R12176 (IT Localization) as protected var?

```
protected var
        CustBillHeader: Record "Customer Bill Header";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53117.

**Comment by FabioC34** [comment]
Hi Jesper,
I just checked in CU22.1 but the modification is not yet available.
Could you please check?

Thank you
Fabio

**Comment by JesperSchulz** [comment]
It looks like something went wrong. I will ask the team addressing these requests to look into this once more.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10836.
