### ISSUE TITLE
[Event Change Request] codeunit 396 NoSeriesManagement - OnBeforeGetNextNo

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#22014]
Hello, can we get please a additinal variable LastNoSeriesLine for Event OnBeforeGetNextNo ?

`OnBeforeGetNextNo(NoSeriesCode, SeriesDate, ModifySeries, Result, IsHandled, LastNoSeriesLine);`

```
[IntegrationEvent(false, false)]
local procedure OnBeforeGetNextNo(var NoSeriesCode: Code[20]; var SeriesDate: Date; var ModifySeries: Boolean; var Result: Code[20]; var IsHandled: Boolean; var NoSeriesLine: Record "No. Series Line")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
