### ISSUE TITLE
[Event Request] Table 4 - Currency - OnBeforeResolveCurrencySymbol

### ISSUE THREAD

**Issue by UIBKH** [microsoft/ALAppExtensions#22019]
Dear Support,

We would like to add a new event OnBeforeResolveCurrencySymbol in the following Procedure below. This would allow us to further customize the code and migrate existing customizations.

    procedure ResolveCurrencySymbol(CurrencyCode: Code[10]): Text[10]
    var
        Currency: Record Currency;
        PoundChar: Char;
        EuroChar: Char;
        YenChar: Char;
    begin
        OnBeforeResolveCurrencySymbol(Rec, CurrencyCode); //New  Code --++
        if Currency.Get(CurrencyCode) then
            if Currency.Symbol <> '' then
                exit(Currency.Symbol);

        PoundChar := 163;
        YenChar := 165;
        EuroChar := 8364;

        case CurrencyCode of
            'AUD', 'BND', 'CAD', 'FJD', 'HKD', 'MXN', 'NZD', 'SBD', 'SGD', 'USD':
                exit('$');
            'GBP':
                exit(Format(PoundChar));
            'DKK', 'ISK', 'NOK', 'SEK':
                exit('kr');
            'EUR':
                exit(Format(EuroChar));
            'CNY', 'JPY':
                exit(Format(YenChar));
        end;

        exit('');
    end;

Event signature:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeResolveCurrencySymbol(var Currency: Record Currency; var CurrencyCode : Code[10])
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53084.
