### ISSUE TITLE
[Funktion Request] page 456 "No. Series"

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#22011]
Hello, can you please change the following procedure in page 456 as a global funktion?

`local procedure UpdateLineActionOnPage()`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53117.
