### ISSUE TITLE
[Event Request] Table 99000772 - "Production BOM Line" - OnBeforeGetQtyPerUnitOfMeasure

### ISSUE THREAD

**Issue by UIBKH** [microsoft/ALAppExtensions#22016]
Dear Support,

We would like to add a new event OnBeforeGetQtyPerUnitOfMeasure in the following Procedure below, using the IsHandled pattern. This would allow us to further customize the code and migrate existing customizations.

    procedure GetQtyPerUnitOfMeasure(): Decimal
    var
        Item: Record Item;
        UOMMgt: Codeunit "Unit of Measure Management";
        IsHandled: Boolean;  //New  Code --++
    begin
        //New  Code --
        IsHandled := false;
        OnBeforeGetQtyPerUnitOfMeasure(Rec, IsHandled);
        if IsHandled then
        exit;
        //New  Code ++
        if Type = Type::Item then begin
            Item.Get("No.");
            exit(
              UOMMgt.GetQtyPerUnitOfMeasure(Item, "Unit of Measure Code"));
        end;
        exit(1);
    end;

Event signature:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeGetQtyPerUnitOfMeasure(var ProductionBOMLine: Record "Production BOM Line"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
