### ISSUE TITLE
[Event Change Request] Table 37 "Sales Line" - OnCopyFromResourceOnBeforeTestBlocked

### ISSUE THREAD

**Issue by ViktorasDanielius** [microsoft/ALAppExtensions#22024]
Please add additional parameter to OnCopyFromResourceOnBeforeTestBlocked event:
var SalesLine: Record "Sales Line"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53084.
