### ISSUE TITLE
[Event Request] Page does not save after selecting new value from dropdown list

### ISSUE THREAD

**Issue by steffanmartin** [microsoft/ALAppExtensions#22020]
After updating a field from a dropdown list, the page is not automatically saved and the underlying record's onmodify trigger is not immediately triggered. Nevertheless, the page displays a "saved" tick in the corner. 

As a workaround we have added OnValidate triggers manually updating the page when a dropdown field is changed:
```
trigger OnValidate()
begin
    CurrPage.Update();
end;
```
Ideally, the page should automatically save just like when a text field is edited.

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
