### ISSUE TITLE
Codeunit 408 "DimensionManagement" - OnUpdateDefaultDimOnAfterAttributeGlobalDims

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#22033]
Can you please add the OnUpdateDefaultDimOnAfterAttributeGlobalDims event to the UpdateDefaultDim procedure in Codeunit DimensionManagement (408)?

ActualCode:

    procedure UpdateDefaultDim(TableID: Integer; No: Code[20]; var GlobalDim1Code: Code[20]; var GlobalDim2Code: Code[20])
    var
        DefaultDim: Record "Default Dimension";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateDefaultDim(TableID, No, GlobalDim1Code, GlobalDim2Code, IsHandled);
        if IsHandled then
            exit;

        GetGLSetup(GLSetupShortcutDimCode);
        if DefaultDim.Get(TableID, No, GLSetupShortcutDimCode[1]) then
            GlobalDim1Code := DefaultDim."Dimension Value Code"
        else
            GlobalDim1Code := '';
        if DefaultDim.Get(TableID, No, GLSetupShortcutDimCode[2]) then
            GlobalDim2Code := DefaultDim."Dimension Value Code"
        else
            GlobalDim2Code := '';
    end;

Suggestion:

    procedure UpdateDefaultDim(TableID: Integer; No: Code[20]; var GlobalDim1Code: Code[20]; var GlobalDim2Code: Code[20])
    var
        DefaultDim: Record "Default Dimension";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateDefaultDim(TableID, No, GlobalDim1Code, GlobalDim2Code, IsHandled);
        if IsHandled then
            exit;

        GetGLSetup(GLSetupShortcutDimCode);
        if DefaultDim.Get(TableID, No, GLSetupShortcutDimCode[1]) then
            GlobalDim1Code := DefaultDim."Dimension Value Code"
        else
            GlobalDim1Code := '';
        if DefaultDim.Get(TableID, No, GLSetupShortcutDimCode[2]) then
            GlobalDim2Code := DefaultDim."Dimension Value Code"
        else
            GlobalDim2Code := '';
        OnUpdateDefaultDimOnAfterAttributeGlobalDims(TableID, No, GlobalDim1Code, GlobalDIm2Code);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnUpdateDefaultDimOnAfterAttributeGlobalDims(TableID: Integer; No: Code[20]; var GlobalDim1Code: Code[20]; var GlobalDim2Code: Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
