### ISSUE TITLE
[Event Request] codeunit 1313 "Correct Posted Purch. Invoice" - TestIfAnyFreeNumberSeries

### ISSUE THREAD

**Issue by NicolasVanDerSpiegel** [microsoft/ALAppExtensions#22037]
Hello,

We would like to have the possibility to overrule the GenJournalTemplate in the function TestIfAnyFreeNumberSeries. 
Could it be possible to add an event in codeunit 1313 "Correct Posted Purch. Invoice" - TestIfAnyFreeNumberSeriesOnTestGenJournalTemplate(PurchaseInvHeader, Handled);

![image](https://user-images.githubusercontent.com/92102399/216966239-83c87225-f47f-4bfb-8671-38f9a75f4963.png)

Thanks in advance. 

Kind regards,
Nicolas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53649.
