### ISSUE TITLE
[Event Request] Codeunit 699 "Exch. Rate Adjmt. Process" - OnProcessBankAccountOnAfterCalcFields

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#22038]
Can you please provide a publisher for ProcessBankAccount. We have to substitute "Balance At Date" and "Balance At Date (LCY)", as we have a requirement, where not every bank account ledger entry should be considererd.

    local procedure ProcessBankAccount(var BankAccount: Record "Bank Account"; Currency: Record Currency)
    var
        NextBankAccount: Record "Bank Account";
        GroupTotal: Boolean;
    begin
        TempDimSetEntry.Reset();
        TempDimSetEntry.DeleteAll();
        TempDimBuf.Reset();
        TempDimBuf.DeleteAll();

        BankAccount.CalcFields("Balance at Date", "Balance at Date (LCY)");
        // -New
        OnProcessBankAccountOnAfterCalcFields(BankAccount, Currency);
        // +New
        CurrAdjBase := BankAccount."Balance at Date";
        CurrAdjBaseLCY := BankAccount."Balance at Date (LCY)";

--SIGNATURE

    //NEW
    [IntegrationEvent(false, false)]
    local procedure OnProcessBankAccountOnAfterCalcFields(var BankAccount: Record "Bank Account"; Currency: Record Currency);
    begin

    end;
    // +NEW

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53049.
