### ISSUE TITLE
[Suggestion] Improve LockTable behaviour in transfer posting

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#22030]
Hi Microsoft AL Development Team,

I would like to suggest logic improvement to the existing transfer posting codeunits. We found that standard transfer posting code has some bad locking behaviour which reduces system concurrency. 

Here is the current logic in **codeunit 5704 "TransferOrder-Post Shipment"** & **codeunit 5705 "TransferOrder-Post Receipt"**:

![image](https://user-images.githubusercontent.com/69611495/216889686-e8234229-f326-4afc-8a66-dbb752051b18.png)

![image](https://user-images.githubusercontent.com/69611495/216889702-8a66c405-7d98-43c3-91fa-26e5b6607fa4.png)

There is no criteria applied to the **No. Series Line** table which means a bunch of other stuff will be locked by SQL too, therefore affects concurrency on posting in Business Central.

And here is our suggested improvement in the codeunits:

**codeunit 5704 "TransferOrder-Post Shipment"** 

![image](https://user-images.githubusercontent.com/69611495/216889935-91e328b4-17ac-405a-9848-fe2ce14bc071.png)

**codeunit 5705 "TransferOrder-Post Receipt"**

![image](https://user-images.githubusercontent.com/69611495/216889953-263f49f5-cf59-435b-930e-24dde8ce516d.png)

Thank you and let us know if you require further clarification.

Kind regards,
Tuan Nguyen

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
