### ISSUE TITLE
Codeunit 408 "DimensionManagement" - OnGetDefaultDimIDOnAfterAttributeGlobalDims

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#22034]
Can you please add the OnGetDefaultDimIDOnAfterAttributeGlobalDims event to the GetDefaultDimID procedure in Codeunit DimensionManagement (408)?

Actual:

    procedure GetDefaultDimID(DefaultDimSource: List of [Dictionary of [Integer, Code[20]]]; SourceCode: Code[20]; var GlobalDim1Code: Code[20]; var GlobalDim2Code: Code[20]; InheritFromDimSetID: Integer; InheritFromTableNo: Integer): Integer
    var
        DimVal: Record "Dimension Value";
        DefaultDimPriority1: Record "Default Dimension Priority";
        DefaultDimPriority2: Record "Default Dimension Priority";
        DefaultDim: Record "Default Dimension";
        TempDimBuf: Record "Dimension Buffer" temporary;
        TempDimSetEntry: Record "Dimension Set Entry" temporary;
        TempDimSetEntry0: Record "Dimension Set Entry" temporary;
        i: Integer;
        j: Integer;
        NoFilter: array[2] of Code[20];
        NewDimSetID: Integer;
        IsHandled: Boolean;
        TableIds: List of [Integer];
        Nos: List of [Code[20]];
        TableId: Integer;
        No: Code[20];
        DimSource: Dictionary of [Integer, Code[20]];
    begin
    #if not CLEAN20
        RunEventOnBeforeGetDefaultDimID(DefaultDimSource, SourceCode, GlobalDim1Code, GlobalDim2Code, InheritFromDimSetID, InheritFromTableNo, DimVal);
    #endif
        OnBeforeGetDefaultDimIDProcedure(DefaultDimSource, SourceCode, GlobalDim1Code, GlobalDim2Code, InheritFromDimSetID, InheritFromTableNo, DimVal);

        GetGLSetup(GLSetupShortcutDimCode);
        if InheritFromDimSetID > 0 then
            GetDimensionSet(TempDimSetEntry0, InheritFromDimSetID);
        if TempDimSetEntry0.FindSet() then
            repeat
                InsertTempDimBufEntry(TempDimBuf, InheritFromTableNo, 0, TempDimSetEntry0."Dimension Code", TempDimSetEntry0."Dimension Value Code");
            until TempDimSetEntry0.Next() = 0;

        NoFilter[2] := '';
        for i := 1 to DefaultDimSource.Count do begin
            DimSource := DefaultDimSource.Get(i);
            TableIds := DimSource.Keys;
            Nos := DimSource.Values;
            TableId := TableIds.Get(1);
            No := Nos.Get(1);
            if (TableId <> 0) and (No <> '') then begin
                IsHandled := false;
                OnGetDefaultDimOnBeforeCreate(
                  TempDimBuf, TableId, No, GLSetupShortcutDimCode, GlobalDim1Code, GlobalDim2Code, IsHandled, SourceCode);
                if not IsHandled then begin
                    DefaultDim.SetRange("Table ID", TableId);
                    NoFilter[1] := No;
                    for j := 1 to 2 do begin
                        DefaultDim.SetRange("No.", NoFilter[j]);
                        if DefaultDim.FindSet() then
                            repeat
                                if DefaultDim."Dimension Value Code" <> '' then begin
                                    TempDimBuf.SetRange("Dimension Code", DefaultDim."Dimension Code");
                                    if not TempDimBuf.FindFirst() then
                                        InsertTempDimBufEntry(TempDimBuf, DefaultDim."Table ID", 0, DefaultDim."Dimension Code", DefaultDim."Dimension Value Code")
                                    else
                                        if DefaultDimPriority1.Get(SourceCode, DefaultDim."Table ID") then
                                            if DefaultDimPriority2.Get(SourceCode, TempDimBuf."Table ID") then begin
                                                if DefaultDimPriority1.Priority < DefaultDimPriority2.Priority then begin
                                                    TempDimBuf.Delete();
                                                    InsertTempDimBufEntry(TempDimBuf, DefaultDim."Table ID", 0, DefaultDim."Dimension Code", DefaultDim."Dimension Value Code");
                                                end;
                                            end else begin
                                                TempDimBuf.Delete();
                                                InsertTempDimBufEntry(TempDimBuf, DefaultDim."Table ID", 0, DefaultDim."Dimension Code", DefaultDim."Dimension Value Code");
                                            end;
                                    if GLSetupShortcutDimCode[1] = TempDimBuf."Dimension Code" then
                                        GlobalDim1Code := TempDimBuf."Dimension Value Code";
                                    if GLSetupShortcutDimCode[2] = TempDimBuf."Dimension Code" then
                                        GlobalDim2Code := TempDimBuf."Dimension Value Code";
                                end;
                            until DefaultDim.Next() = 0;
                    end;
                end;
            end;
        end;

    #if not CLEAN20
        RunEventOnGetDefaultDimIDOnBeforeFindNewDimSetID(TempDimBuf, DefaultDimSource, GlobalDim1Code, GlobalDim2Code);
    #endif
        OnGetDefaultDimIDOnBeforeFindNewDimSetIDProcedure(TempDimBuf, DefaultDimSource, GlobalDim1Code, GlobalDim2Code);

        TempDimBuf.Reset();
        if TempDimBuf.FindSet() then begin
            repeat
                DimVal.Get(TempDimBuf."Dimension Code", TempDimBuf."Dimension Value Code");
                TempDimSetEntry."Dimension Code" := TempDimBuf."Dimension Code";
                TempDimSetEntry."Dimension Value Code" := TempDimBuf."Dimension Value Code";
                TempDimSetEntry."Dimension Value ID" := DimVal."Dimension Value ID";
                OnGetDefaultDimIDOnBeforeTempDimSetEntryInsert(TempDimSetEntry, TempDimBuf, SourceCode);
                TempDimSetEntry.Insert();
            until TempDimBuf.Next() = 0;
            NewDimSetID := GetDimensionSetID(TempDimSetEntry);
        end;
        exit(NewDimSetID);
    end;

Suggestion:

    procedure GetDefaultDimID(DefaultDimSource: List of [Dictionary of [Integer, Code[20]]]; SourceCode: Code[20]; var GlobalDim1Code: Code[20]; var GlobalDim2Code: Code[20]; InheritFromDimSetID: Integer; InheritFromTableNo: Integer): Integer
    var
        DimVal: Record "Dimension Value";
        DefaultDimPriority1: Record "Default Dimension Priority";
        DefaultDimPriority2: Record "Default Dimension Priority";
        DefaultDim: Record "Default Dimension";
        TempDimBuf: Record "Dimension Buffer" temporary;
        TempDimSetEntry: Record "Dimension Set Entry" temporary;
        TempDimSetEntry0: Record "Dimension Set Entry" temporary;
        i: Integer;
        j: Integer;
        NoFilter: array[2] of Code[20];
        NewDimSetID: Integer;
        IsHandled: Boolean;
        TableIds: List of [Integer];
        Nos: List of [Code[20]];
        TableId: Integer;
        No: Code[20];
        DimSource: Dictionary of [Integer, Code[20]];
    begin
    #if not CLEAN20
        RunEventOnBeforeGetDefaultDimID(DefaultDimSource, SourceCode, GlobalDim1Code, GlobalDim2Code, InheritFromDimSetID, InheritFromTableNo, DimVal);
    #endif
        OnBeforeGetDefaultDimIDProcedure(DefaultDimSource, SourceCode, GlobalDim1Code, GlobalDim2Code, InheritFromDimSetID, InheritFromTableNo, DimVal);

        GetGLSetup(GLSetupShortcutDimCode);
        if InheritFromDimSetID > 0 then
            GetDimensionSet(TempDimSetEntry0, InheritFromDimSetID);
        if TempDimSetEntry0.FindSet() then
            repeat
                InsertTempDimBufEntry(TempDimBuf, InheritFromTableNo, 0, TempDimSetEntry0."Dimension Code", TempDimSetEntry0."Dimension Value Code");
            until TempDimSetEntry0.Next() = 0;

        NoFilter[2] := '';
        for i := 1 to DefaultDimSource.Count do begin
            DimSource := DefaultDimSource.Get(i);
            TableIds := DimSource.Keys;
            Nos := DimSource.Values;
            TableId := TableIds.Get(1);
            No := Nos.Get(1);
            if (TableId <> 0) and (No <> '') then begin
                IsHandled := false;
                OnGetDefaultDimOnBeforeCreate(
                  TempDimBuf, TableId, No, GLSetupShortcutDimCode, GlobalDim1Code, GlobalDim2Code, IsHandled, SourceCode);
                if not IsHandled then begin
                    DefaultDim.SetRange("Table ID", TableId);
                    NoFilter[1] := No;
                    for j := 1 to 2 do begin
                        DefaultDim.SetRange("No.", NoFilter[j]);
                        if DefaultDim.FindSet() then
                            repeat
                                if DefaultDim."Dimension Value Code" <> '' then begin
                                    TempDimBuf.SetRange("Dimension Code", DefaultDim."Dimension Code");
                                    if not TempDimBuf.FindFirst() then
                                        InsertTempDimBufEntry(TempDimBuf, DefaultDim."Table ID", 0, DefaultDim."Dimension Code", DefaultDim."Dimension Value Code")
                                    else
                                        if DefaultDimPriority1.Get(SourceCode, DefaultDim."Table ID") then
                                            if DefaultDimPriority2.Get(SourceCode, TempDimBuf."Table ID") then begin
                                                if DefaultDimPriority1.Priority < DefaultDimPriority2.Priority then begin
                                                    TempDimBuf.Delete();
                                                    InsertTempDimBufEntry(TempDimBuf, DefaultDim."Table ID", 0, DefaultDim."Dimension Code", DefaultDim."Dimension Value Code");
                                                end;
                                            end else begin
                                                TempDimBuf.Delete();
                                                InsertTempDimBufEntry(TempDimBuf, DefaultDim."Table ID", 0, DefaultDim."Dimension Code", DefaultDim."Dimension Value Code");
                                            end;
                                    if GLSetupShortcutDimCode[1] = TempDimBuf."Dimension Code" then
                                        GlobalDim1Code := TempDimBuf."Dimension Value Code";
                                    if GLSetupShortcutDimCode[2] = TempDimBuf."Dimension Code" then
                                        GlobalDim2Code := TempDimBuf."Dimension Value Code";
                                end;
                                OnGetDefaultDimIDOnAfterAttributeGlobalDims(GlobalDim1Code, GlobalDim2Code)
                            until DefaultDim.Next() = 0;
                    end;
                end;
            end;
        end;

    #if not CLEAN20
        RunEventOnGetDefaultDimIDOnBeforeFindNewDimSetID(TempDimBuf, DefaultDimSource, GlobalDim1Code, GlobalDim2Code);
    #endif
        OnGetDefaultDimIDOnBeforeFindNewDimSetIDProcedure(TempDimBuf, DefaultDimSource, GlobalDim1Code, GlobalDim2Code);

        TempDimBuf.Reset();
        if TempDimBuf.FindSet() then begin
            repeat
                DimVal.Get(TempDimBuf."Dimension Code", TempDimBuf."Dimension Value Code");
                TempDimSetEntry."Dimension Code" := TempDimBuf."Dimension Code";
                TempDimSetEntry."Dimension Value Code" := TempDimBuf."Dimension Value Code";
                TempDimSetEntry."Dimension Value ID" := DimVal."Dimension Value ID";
                OnGetDefaultDimIDOnBeforeTempDimSetEntryInsert(TempDimSetEntry, TempDimBuf, SourceCode);
                TempDimSetEntry.Insert();
            until TempDimBuf.Next() = 0;
            NewDimSetID := GetDimensionSetID(TempDimSetEntry);
        end;
        exit(NewDimSetID);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnGetDefaultDimIDOnAfterAttributeGlobalDims(var GlobalDim1Code: Code[20]; var GlobalDim2Code: Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
