### ISSUE TITLE
Event Request - codeunit 7322 "Create Inventory Pick/Movement" - OnAfterCreateATOPickLine

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#22032]
Please could we have the following event added:
   local procedure CreateATOPickLine(NewWhseActivLine: Record "Warehouse Activity Line"; BinCode: Code[20]; var RemQtyToPickBase: Decimal)
    begin
   ......
                   AssemblySetup.Get();
                if AssemblySetup."Create Movements Automatically" then
                    CreateATOInventoryMovementsAutomatically(AsmHeader, ATOInvtMovementsCreated, TotalATOInvtMovementsToBeCreated);
            end;

            OnAfterCreateATOPickLine(QtyToPickBase,AsmHeader,NewWhseActivLine,WhseActivHeader,RemQtyToPickBase)
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCreateATOPickLine(QtyToPickBase: Decimal;AsmHeader: Record "Assembly Header"; NewWhseActivLine: Record "Warehouse Activity Line";var WhseActivHeader: Record "Warehouse Activity Header";var RemQtyToPickBase: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
