### ISSUE TITLE
Codeunit 408 "DimensionManagement" - OnFinishCheckDimValue

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#22036]
Can you please add the OnFinishCheckDimValue event to the CheckDimValue procedure in Codeunit DimensionManagement (408)?

Actual Code:

    procedure CheckDimValue(DimCode: Code[20]; DimValCode: Code[20]): Boolean
    var
        DimVal: Record "Dimension Value";
        IsHandled: Boolean;
        Result: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckDimValue(DimCode, DimValCode, Result, IsHandled, DimVal);
        if IsHandled then
            exit(Result);

        if (DimCode <> '') and (DimValCode <> '') then
            if DimVal.Get(DimCode, DimValCode) then begin
                if DimVal.Blocked then begin
                    LogError(
                      DimVal.RecordId, DimVal.FieldNo(Blocked),
                      StrSubstNo(DimValueBlockedErr, DimVal.TableCaption(), DimCode, DimValCode), '');
                    exit(false);
                end;
                if not CheckDimValueAllowed(DimVal) then
                    exit(false);
            end else begin
                LogError(
                  DATABASE::"Dimension Value", 0,
                  StrSubstNo(DimValueMissingErr, DimVal.TableCaption(), DimCode, DimValCode), '');
                exit(false);
            end;
        exit(true);
    end;

Suggestion:

    procedure CheckDimValue(DimCode: Code[20]; DimValCode: Code[20]): Boolean
    var
        DimVal: Record "Dimension Value";
        IsHandled: Boolean;
        Result: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckDimValue(DimCode, DimValCode, Result, IsHandled, DimVal);
        if IsHandled then
            exit(Result);

        if (DimCode <> '') and (DimValCode <> '') then
            if DimVal.Get(DimCode, DimValCode) then begin
                if DimVal.Blocked then begin
                    LogError(
                      DimVal.RecordId, DimVal.FieldNo(Blocked),
                      StrSubstNo(DimValueBlockedErr, DimVal.TableCaption(), DimCode, DimValCode), '');
                    exit(false);
                end;
                if not CheckDimValueAllowed(DimVal) then
                    exit(false);
            end else begin
                LogError(
                  DATABASE::"Dimension Value", 0,
                  StrSubstNo(DimValueMissingErr, DimVal.TableCaption(), DimCode, DimValCode), '');
                exit(false);
            end;
            OnFinishCheckDimValue(DimCode, DimValCode);
        exit(true);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnFinishCheckDimValue(DimCode: Code[20]; DimValCode: Code[20])
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
