### ISSUE TITLE
Event Request - codeunit 7322 "Create Inventory Pick/Movement" - OnCreateATOPickLineBeforeQtyToPickBaseCheck

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#22031]
Please could you add the following event:
    local procedure CreateATOPickLine(NewWhseActivLine: Record "Warehouse Activity Line"; BinCode: Code[20]; var RemQtyToPickBase: Decimal)
    var
        ATOSalesLine: Record "Sales Line";
        AsmHeader: Record "Assembly Header";
        AssemblySetup: Record "Assembly Setup";
        ReservationEntry: Record "Reservation Entry";
        TempTrackingSpecification: Record "Tracking Specification" temporary;
        WhseItemTrackingSetup: Record "Item Tracking Setup";
        QtyToAsmBase: Decimal;
        QtyToPickBase: Decimal;
    begin
            ........
            WhseItemTrackingSetup.CopyTrackingFromWhseActivityLine(NewWhseActivLine);
            QtyToPickBase := QtyToAsmBase - WMSMgt.CalcQtyBaseOnATOInvtPick(ATOSalesLine, WhseItemTrackingSetup);
            OnCreateATOPickLineBeforeQtyToPickBaseCheck(RemQtyToPickBase,QtyToPickBase,ATOSalesLine)
            if QtyToPickBase > 0 then begin
            ......
  end;

    [IntegrationEvent(false, false)]
    local procedure OnCreateATOPickLineBeforeQtyToPickBaseCheck(var RemQtyToPickBase: Decimal;var QtyToPickBase: Decimal; ATOSalesLine: Record "Sales Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
