### ISSUE TITLE
Codeunit 408 "DimensionManagement" - OnValidateDimValueCodeOnAfterAttributeShortcutDimCode

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#22035]
Can you please add the OnValidateDimValueCodeOnAfterAttributeShortcutDimCode event to the ValidateDimValueCode procedure in Codeunit DimensionManagement (408)?

Actual Code:

    procedure ValidateDimValueCode(FieldNumber: Integer; var ShortcutDimCode: Code[20])
    var
        DimVal: Record "Dimension Value";
        GLSetup: Record "General Ledger Setup";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeValidateDimValueCode(FieldNumber, ShortcutDimCode, IsHandled, GLSetupShortcutDimCode, DimVal);
        if IsHandled then
            exit;

        GetGLSetup(GLSetupShortcutDimCode);
        if (GLSetupShortcutDimCode[FieldNumber] = '') and (ShortcutDimCode <> '') then
            Error(Text002, GLSetup.TableCaption());
        DimVal.SetRange("Dimension Code", GLSetupShortcutDimCode[FieldNumber]);
        if ShortcutDimCode <> '' then begin
            DimVal.SetRange(Code, ShortcutDimCode);
            if not DimVal.FindFirst() then begin
                DimVal.SetFilter(Code, StrSubstNo('%1*', ShortcutDimCode));
                if DimVal.FindFirst() then
                    ShortcutDimCode := DimVal.Code
                else
                    Error(
                      Text003,
                      ShortcutDimCode, DimVal.FieldCaption(Code));
            end;
        end;
    end;

Suggestion:

    procedure ValidateDimValueCode(FieldNumber: Integer; var ShortcutDimCode: Code[20])
    var
        DimVal: Record "Dimension Value";
        GLSetup: Record "General Ledger Setup";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeValidateDimValueCode(FieldNumber, ShortcutDimCode, IsHandled, GLSetupShortcutDimCode, DimVal);
        if IsHandled then
            exit;

        GetGLSetup(GLSetupShortcutDimCode);
        if (GLSetupShortcutDimCode[FieldNumber] = '') and (ShortcutDimCode <> '') then
            Error(Text002, GLSetup.TableCaption());
        DimVal.SetRange("Dimension Code", GLSetupShortcutDimCode[FieldNumber]);
        if ShortcutDimCode <> '' then begin
            DimVal.SetRange(Code, ShortcutDimCode);
            if not DimVal.FindFirst() then begin
                DimVal.SetFilter(Code, StrSubstNo('%1*', ShortcutDimCode));
                if DimVal.FindFirst() then
                    ShortcutDimCode := DimVal.Code
                else
                    Error(
                      Text003,
                      ShortcutDimCode, DimVal.FieldCaption(Code));
            end;
        end;
        OnValidateDimValueCodeOnAfterAttributeShortcutDimCode(FieldNumber, ShortcutDimCode, GLSetupShortcutDimCode, DimVal);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnValidateDimValueCodeOnAfterAttributeShortcutDimCode(FieldNumber: Integer; var ShortcutDimCode: Code[20]; var GLSetupShortcutDimCode: array[8] of Code[20]; var DimVal: Record "Dimension Value")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
