### ISSUE TITLE
[Function Request] COD 6501 Item Tracking Data Collection GetTempGlobalEntrys

### ISSUE THREAD

**Issue by SirBETE** [microsoft/ALAppExtensions#2204]
In COD 6501 Item Tracking Data Collection there's a function:
`[External] RetrieveLookupData(VAR TrackingSpecification : TEMPORARY Record "Tracking Specification";FullDataSet : Boolean)`.
This function fills in TempGlobalReservEntry and TempGlobalEntrySummary.

We want those 2 temp records.

We can subscribe on that function
`OnAfterRetrieveLookupData(TrackingSpecification,FullDataSet,TempGlobalReservEntry,TempGlobalEntrySummary);`

This will however be addressed in a new codeunit instance, so we lost our context of what we want to do with it.

Could a `GetTempGlobalReservEntry` and `GetTempGlobalEntrySummary` be created please?
(Or remove those global variables and add them to the function parameters via VAR. But this also means that all other functions will have to be refactored. So adding 2 get functions is easier to do. :) )

**Comment by AlexanderYakunin** [comment]
Closing this request as this is very old one (our sync from GitHub missed to create internal bug for this one) and no questions have been created for this area during last year. Sorry for possible inconvenience. If this is still active problem, please create new request with reference to this one.

**Comment by SirBETE** [comment]
I noticed in BC16.3 that `TempGlobalReservEntry` and `TempGlobalEntrySummary` are set to var.
So, if we still need this, we access those variables now.
`local procedure OnAfterRetrieveLookupData(var TrackingSpecification: Record "Tracking Specification"; FullDataSet: Boolean; var TempGlobalReservEntry: Record "Reservation Entry" temporary; var TempGlobalEntrySummary: Record "Entry Summary" temporary)`
Thanks! :D
