### ISSUE TITLE
[Event Request] - OnAfterLookupPostCode in Table 5051 "Contact Alt. Address"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#22049]
Hello, please consider adding the following event to Table 5051 "Contact Alt. Address"

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterLookupPostCode(var ContactAltAddress: Record "Contact Alt. Address"; var PostCodeRec: Record "Post Code")
    begin
    end;
```

and raise it accordingly inside "OnLookup" trigger of field 8 "Post Code":

```
        trigger OnLookup()
        begin
            PostCode.LookupPostCode(City, "Post Code", County, "Country/Region Code");

            **OnAfterLookupPostCode(Rec, PostCode);**
        end;
```

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53084.
