### ISSUE TITLE
[Var Request] Codeunit 1232 "SEPA DD-Prepare Source" - Event "OnBeforeCreateTempCollectionEntries" on CreateTempCollectionEntries - Change parameter IsHandled as var

### ISSUE THREAD

**Issue by FabioC34** [microsoft/ALAppExtensions#22040]
Hello, in the Event "OnBeforeCreateTempCollectionEntries" the parameter isHandled is not defined as "var"; in this way the event is useless, because the isHandled value if filled in the subscriber is not passed back and the "if IsHandled then exit" is never executed.
Could you please change the event:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateTempCollectionEntries(var FromDirectDebitCollectionEntry: Record "Direct Debit Collection Entry"; var ToDirectDebitCollectionEntry: Record "Direct Debit Collection Entry"; var IsHandled: Boolean)
    begin
    end;
```

Thank you
Fabio

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53049.
