### ISSUE TITLE
[Request for External] SearchBasedOn @ page 344 Navigate

### ISSUE THREAD

**Issue by J-KVS** [microsoft/ALAppExtensions#22056]
I'd like to propose to make the local variable `SearchBasedOn: Enum "Navigate Search Type";` in the Navigate Page protected.

**Comment by AlexanderYakunin** [comment]
This is already implemented

        SearchBasedOn: Enum "Navigate Search Type";

**Comment by J-KVS** [comment]
Hi @AlexanderYakunin,

maybe I was not clear enough or it might be implemented in an unreleased preview, but in the current version 21.4 the variable is not `protected`. I have attached you Code Samples of what I mean.

Kind Regards

**Current Code (W1 21.4)**

``` al
        SearchBasedOn: Enum "Navigate Search Type";
        [InDataSet]
        DocumentVisible: Boolean;
        [InDataSet]
        BusinessContactVisible: Boolean;
        [InDataSet]
        ItemReferenceVisible: Boolean;
        [InDataSet]
        FilterSelectionChangedTxtVisible: Boolean;
        PageCaptionTxt: Label 'Selected - %1';

    protected var
        [SecurityFiltering(SecurityFilter::Filtered)]
        SalesShptHeader: Record "Sales Shipment Header";
```

**Proposed Change**
``` al
        [InDataSet]
        DocumentVisible: Boolean;
        [InDataSet]
        BusinessContactVisible: Boolean;
        [InDataSet]
        ItemReferenceVisible: Boolean;
        [InDataSet]
        FilterSelectionChangedTxtVisible: Boolean;
        PageCaptionTxt: Label 'Selected - %1';

    protected var
        SearchBasedOn: Enum "Navigate Search Type";
        [SecurityFiltering(SecurityFilter::Filtered)]
        SalesShptHeader: Record "Sales Shipment Header";
```

**Comment by AlexanderYakunin** [comment]
Please read our WIKI, we do external requests (including protected var) for next major only. This is done for upcoming April release. Here is full list of protected vars in Navigate page:

    protected var
        [SecurityFiltering(SecurityFilter::Filtered)]
        SalesShptHeader: Record "Sales Shipment Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        SalesInvHeader: Record "Sales Invoice Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        ReturnRcptHeader: Record "Return Receipt Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        SalesCrMemoHeader: Record "Sales Cr.Memo Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        SQSalesHeader: Record "Sales Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        SOSalesHeader: Record "Sales Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        SISalesHeader: Record "Sales Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        SROSalesHeader: Record "Sales Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        SCMSalesHeader: Record "Sales Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        PQPurchaseHeader: Record "Purchase Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        POPurchaseHeader: Record "Purchase Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        PIPurchaseHeader: Record "Purchase Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        GenJnlLine: Record "Gen. Journal Line";
        [SecurityFiltering(SecurityFilter::Filtered)]
        SOServHeader: Record "Service Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        SIServHeader: Record "Service Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        SCMServHeader: Record "Service Header";
        [SecurityFiltering(SecurityFilter::Filtered)]
        PstdPhysInvtOrderHdr: Record "Pstd. Phys. Invt. Order Hdr";
        ContactNo: Code[250];
        ContactType: Enum "Navigate Contact Type";
        SearchBasedOn: Enum "Navigate Search Type";
        DocNoFilter: Text;
        PostingDateFilter: Text;
        ExtDocNo: Code[250];
        NewDocNo: Code[20];
        NewPostingDate: Date;
        NewSourceRecVar: Variant;
        SerialNoFilter: Text;
        LotNoFilter: Text;
        PackageNoFilter: Text;
