### ISSUE TITLE
[Event Request] Table 7302 - "Bin Content" - OnBeforeCalcQtyAvailToPickIncludingDedicated

### ISSUE THREAD

**Issue by FGRKH** [microsoft/ALAppExtensions#22050]
Dear Support,

We would like to add a new event OnBeforeCalcQtyAvailToPickIncludingDedicated in the following Procedure below, using the IsHandled pattern. This would allow us to further customize the code and migrate existing customizations.

    procedure CalcQtyAvailToPickIncludingDedicated(ExcludeQtyBase: Decimal): Decimal
    var
        IsHandled: Boolean;  //New  Code --++
    begin
        //New  Code --
        IsHandled := false;
        OnBeforeCalcQtyAvailToPickIncludingDedicated (Rec, ExcludeQtyBase, IsHandled);
        if IsHandled then
        exit;
        //New  Code ++
        if not ("Block Movement" in ["Block Movement"::Outbound, "Block Movement"::All]) then
            exit(CalcQtyAvailToTake(ExcludeQtyBase) - CalcQtyWithBlockedItemTracking());
    end;

Event Signature:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCalcQtyAvailToPickIncludingDedicated(var BinContent: Record "Bin Content"; ExcludeQtyBase: Decimal; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
