### ISSUE TITLE
[Event Request] Table 7302 - "Bin Content" - OnBeforeCalcTotalQtyAvailToTake

### ISSUE THREAD

**Issue by FGRKH** [microsoft/ALAppExtensions#22051]
Dear Support,

We would like to add a new event OnBeforeCalcTotalQtyAvailToTake in the following Procedure below, using the IsHandled pattern. This would allow us to further customize the code and migrate existing customizations.

    local procedure CalcTotalQtyAvailToTake(ExcludeQtyBase: Decimal): Decimal
    var
        TotalQtyBase: Decimal;
        TotalNegativeAdjmtQtyBase: Decimal;
        TotalATOComponentsPickQtyBase: Decimal;
        IsHandled: Boolean;  //New  Code --++
    begin
        //New  Code --
        IsHandled := false;
        OnBeforeCalcTotalQtyAvailToTake (Rec, ExcludeQtyBase, IsHandled);
        if IsHandled then
        exit;
        //New  Code ++
        TotalQtyBase := CalcTotalQtyBase();
        TotalNegativeAdjmtQtyBase := CalcTotalNegativeAdjmtQtyBase();
        TotalATOComponentsPickQtyBase := CalcTotalATOComponentsPickQtyBase();
        SetFilterOnUnitOfMeasure();
        CalcFields("Pick Quantity (Base)");
        OnCalcTotalQtyAvailToTakeOnAfterCalcPickQuantityBase(Rec, ExcludeQtyBase, TotalNegativeAdjmtQtyBase);
        exit(
          TotalQtyBase -
          ("Pick Quantity (Base)" + TotalATOComponentsPickQtyBase - ExcludeQtyBase + TotalNegativeAdjmtQtyBase));
    end;

Event Signature:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCalcTotalQtyAvailToTake(var BinContent: Record "Bin Content"; ExcludeQtyBase: Decimal; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53020.
