### ISSUE TITLE
Window operations in codeunit 80 Sales-Post without checks on GuiAllowed()

### ISSUE THREAD

**Issue by pieter-kok** [microsoft/ALAppExtensions#22057]
Currently we are doing a project with one of our customers that is automatically shipping orders from a job queue based on a customized process. 

We found out that the operations on the dialog are not always checking GuiAllowed(). 
In some circumstances this is the case, which is good practice in my perspective.

In other cases only the Boolean HideProgressWindow is checked, which can also be false in case GuiAllowed = false.
This can f.i. be the case when the value is overruled by a third party in the event OnBeforePostSalesDoc.
The latter leads then to an error during processing the job queue.

![error](https://user-images.githubusercontent.com/34770900/217307569-38523112-a4be-457d-954e-c58414ec29a9.png)

The English translation is something like: the operation has failed because the dialog is not open.

As part of incident SDT-26492-N5W5Q - TrackingID#2302060050002062, in which I was redirected to this repository, I created a code suggestion (SalesPost.Codeunit.zip) with the original and changed version based on BC21.4 NL version. 

[SalesPost.Codeunit.zip](https://github.com/microsoft/ALAppExtensions/files/10677379/SalesPost.Codeunit.zip)

I'm hoping you can help me further with this matter.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19015.
