### ISSUE TITLE
[Extensibility Bug]  codeunit 457 "Environment Information" - IsOnPrem

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#22059]
```al
/// <summary>
/// Checks the deployment type is OnPremises.
/// </summary>
/// <returns>True if the deployment type is OnPremises, false otherwise.</returns>
procedure IsOnPrem(): Boolean
begin
    exit(EnvironmentInformationImpl.IsOnPrem());
end;
```

In our Pipelines with Sandbox Dockers the procedure `IsOnPrem` returns `true`.

I would expect that we receive `false` for Sandbox Dockers and `true` for OnPrem Dockers.

as an alternative it might be helpful to know the difference if it is real OnPrem or only a docker for testing.
Internal work item: [AB#538600](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538600)

**Comment by JesperSchulz** [comment]
@freddydk, here's another issue related to Docker deployments. The assumption seems to be, that Sandbox Docker containers emulate that they're SaaS. In reality they aren't - they also don't have entitlements enabled etc. There seems to be some confusion / missing functionality we must address.

**Comment by freddydk** [comment]
For testing whether you are running on Saas or not you should use IsSaasInfrastructure.

**Comment by JesperSchulz** [comment]
In that case, I will close this issue. @pri-kise, please reopen if you disagree.
