### ISSUE TITLE
[Event Request] Codeunit "Calculate Prod. Order" Function TransferRouting

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#22053]
Hello,
we need a Publisher in Codeunit 99000773 "Calculate Prod. Order"
Function TransferRouting
Handler Pattern

RoutingLine.SetRange("Routing No.", ProdOrderLine."Routing No.");
RoutingLine.SetRange("Version Code", ProdOrderLine."Routing Version Code");
if RoutingLine.Find('-') then
   repeat
      _**OnBeforeInitProdOrderRouting(RoutingLine, ProdOrder, ProdOrderLine, isHandled);
      if not isHandled then begin**_
         RoutingLine.TestField(Recalculate, false);
         InitProdOrderRoutingLine(ProdOrderRoutingLine, RoutingLine);
         TransferTaskInfo(ProdOrderRoutingLine, ProdOrderLine."Routing Version Code");
      _**end;**_
   until RoutingLine.Next() = 0;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53649.
