### ISSUE TITLE
New Event to Table 1003 Job Planning Line

### ISSUE THREAD

**Issue by DanielSmutek** [microsoft/ALAppExtensions#22055]
Please add new Event to the end of local procedure **UpdateAmountsAndDiscounts**, Table 1003 Job Planning Line:

....
....
        "Line Amount (LCY)" := ConvertAmountToLCY("Line Amount", AmountRoundingPrecision);
        "Line Discount Amount (LCY)" := ConvertAmountToLCY("Line Discount Amount", AmountRoundingPrecision);
        //new code
        OnAfterUpdateAmountsAndDiscounts(Rec, xRec);
        //new code

Event Signature:
    [IntegrationEvent(false, false)]
    local procedure OnValidateNoOnAfterCopyFromAccount(var JobPlanningLine: Record "Job Planning Line"; var xJobPlanningLine: Record "Job Planning Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53187.
