### ISSUE TITLE
[Event Request] Page 5905 Service Lines, Procedure SetSelectionFilter

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#22058]
![image](https://user-images.githubusercontent.com/49729094/217350254-b15b1ca6-0c3a-4750-87dd-1c18835fd1ec.png)

Could you please add an event between lines 1287 and 1288 so we can add more filters?

OnAfterSetSelection(Rec, SelectionFilter)

[IntegrationEvent(false, false)]
local procedure OnAfterSetSelection(ServiceLine: Record "Service Line"; var SelectionFilter: Option "All Service Lines","Lines per Selected Service Item","Lines Not Item Related")
begin
end;

Thanks very much.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53123.
