### ISSUE TITLE
[EXTERNAL REQUEST] Call combine shipment logic for all sales orders

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#22054]
Hi,

we want to call the logic to create a combine shipment for all sales orders. The only change we need for this, is that the whole code in the `reports 295 "Combine Shipments"` is moved to a new codeunit similar to the `report 5754 "Create Pick"`.

I hope you can see the need of this change.

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot take this request. There are almost 20 events and this refactoring is breaking change for any other partner. You an create this ask as an idea on aka.ms/bcideas to let other partners support this ask. If so, we will be able to consider this change. 

Currently, you can ask about the smaller changes which you really need for this.
