### ISSUE TITLE
[Event Parameter Request] Table 37 Sales Line - procedure CreateDim - event OnBeforeCreateDim

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#22060]
We would like the parameter/-s CurrFieldNo, DefaultDimSource added to the following event.

Table 37 Sales Line - procedure CreateDim - event OnBeforeCreateDim

Original:

```
Table 37 Sales Line - procedure CreateDim - event OnBeforeCreateDim

OnBeforeCreateDim(IsHandled, Rec);

[IntegrationEvent(true, false)]
local procedure OnBeforeCreateDim(var IsHandled: Boolean; var SalesLine: Record "Sales Line")
begin
end;
```

Change:

```
OnBeforeCreateDim(IsHandled, Rec, CurrFieldNo, DefaultDimSource); // <-- ADDED

[IntegrationEvent(true, false)]
local procedure OnBeforeCreateDim(var IsHandled: Boolean; var SalesLine: Record "Sales Line"; CurrentFieldNo: Integer; DefaultDimSource: List of [Dictionary of [Integer, Code[20]]]) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53084.
