### ISSUE TITLE
[Event Request] Table 9500 Email Item - procedure SetAttachments - OnBeforeSetAttachments

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#22062]
Please add the following existing Event OnBeforeSetAttachments to procedure SetAttachments in Table 9500 Email Item

```
procedure SetAttachments(TempBlobList: Codeunit "Temp Blob List"; Names: List of [Text])
    begin
        // BEGIN
        OnBeforeSetAttachments(Rec,TempBlobList,Names);       
        // END
        Attachments := TempBlobList;
        AttachmentNames := Names;
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetAttachments(var EmailItem: Record "Email Item"; var TempBlobList: Codeunit "Temp Blob List"; var Names: List of [Text])
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53187.
