### ISSUE TITLE
[Event Parameter Request] Table 38 Purchase Header - procedure UpdatePurchLinesByFieldNo - event OnUpdatePurchLinesByChangedFieldName - Add xRec / xPurchHeader parameter

### ISSUE THREAD

**Issue by ZepposBE** [microsoft/ALAppExtensions#22074]
We would like to see some extra parameters added to the "OnUpdatePurchLinesByChangedFieldName" event, similar to the ones on the Sales Header event, in order to better evaluate the action to take on the PurchLine.

On the Sales Header, xRec (xSalesHeader) is already available, 
Table 36 Sales Header - procedure UpdateSalesLinesByFieldNo- event OnUpdateSalesLineByChangedFieldName
Existing code on sales header:

`OnUpdateSalesLineByChangedFieldName(Rec, SalesLine, Field.FieldName, ChangedFieldNo, xRec);`

```
 [IntegrationEvent(false, false)]
    local procedure OnUpdateSalesLineByChangedFieldName(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; ChangedFieldName: Text[100]; ChangedFieldNo: Integer; xSalesHeader: Record "Sales Header")
    begin
    end;
```

Existing code on Purchase Header:

Table 38 Purchase Header - procedure UpdatePurchLinesByFieldNo - event OnUpdatePurchLinesByChangedFieldName

**AS IS**

`OnUpdatePurchLinesByChangedFieldName(Rec, PurchLine, Field.FieldName, ChangedFieldNo);`
```
[IntegrationEvent(false, false)]
    local procedure OnUpdatePurchLinesByChangedFieldName(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; ChangedFieldName: Text[100]; ChangedFieldNo: Integer)
    begin
    end;
```

**TO BE:** Changed code on Purchase Header: (Added xRec in procedure and xPurchaseHeader in publisher)

`OnUpdatePurchLinesByChangedFieldName(Rec, PurchLine, Field.FieldName, ChangedFieldNo, xRec);`
```
[IntegrationEvent(false, false)]
    local procedure OnUpdatePurchLinesByChangedFieldName(PurchHeader: Record "Purchase Header"; var PurchLine: Record "Purchase Line"; ChangedFieldName: Text[100]; ChangedFieldNo: Integer; xPurchHeader: Record "Purchase Header")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53187.
