### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" OnBeforeMessageIfPurchLinesExist (Similar to sales side)

### ISSUE THREAD

**Issue by ZepposBE** [microsoft/ALAppExtensions#22073]
Hi Development Team,

Similar to the "OnBeforeMessageIfSalesLinesExist" event in table  36 "Sales Header", which was requested [here](https://github.com/microsoft/ALAppExtensions/issues/7313),  we would like to see the following event added on the Purchase Header table.

```
procedure MessageIfPurchLinesExist(ChangedFieldName: Text[100])
    var
        MessageText: Text;
        IsHandled: Boolean;
    begin
// >> New event call
        IsHandled := false;
        OnBeforeMessageIfPurchLinesExist(Rec, ChangedFieldName, IsHandled);
        if IsHandled then
            exit;
// << New event call

        if PurchLinesExist() and not GetHideValidationDialog() then begin
            MessageText := StrSubstNo(LinesNotUpdatedMsg, ChangedFieldName);
            MessageText := StrSubstNo(SplitMessageTxt, MessageText, Text020);
            Message(MessageText);
        end;
    end;

```

```
     [IntegrationEvent(false, false)]
    local procedure OnBeforeMessageIfPurchLinesExist(PurchaseHeader: Record "Purchase Header"; ChangedFieldName: Text; var IsHandled: Boolean)
    begin
    end;
```

This would allow for more detailed tuning of the messages without changing the 'HideValidationDialog' value on the header.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53187.
