### ISSUE TITLE
[Event Request] - Czech Advance Payments

### ISSUE THREAD

**Issue by KarelKoncel** [microsoft/ALAppExtensions#22078]
Hello, 
we need some events in czech extension
Microsoft_Advance Payments Localization for Czech

codeunit 31002 "SalesAdvLetterManagement CZZ"
Procedure PostAdvancePaymentUsage - Create integration event for Handling by our side

`procedure PostAdvancePaymentUsage
Var IsHandled: Boolean;
begin
OnBeforePostAdvancePaymentUsage (AdvLetterUsageDocTypeCZZ, DocumentNo, SalesInvoiceHeader, CustLedgerEntry, GenJnlPostLine, Preview, IsHandled);
        	if IsHandled then
           		 exit;
`
`[IntegrationEvent(true, false)]
    local procedure OnBeforePostAdvancePaymentUsage (AdvLetterUsageDocTypeCZZ: Enum "Adv. Letter Usage Doc.Type CZZ"; DocumentNo: Code[20]; var SalesInvoiceHeader: Record "Sales Invoice Header"; var CustLedgerEntry: Record "Cust. Ledger Entry"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; Preview: Boolean; IsHandled: Boolean)
    begin      
    end;
`
For change functio: CorrectDocumentAfterPaymentUsage

`procedure CorrectDocumentAfterPaymentUsage
Var IsHandled: Boolean;
begin
OnBeforeCorrectDocumentAfterPaymentUsage (DocumentNo, CustLedgerEntry, GenJnlPostLine, IsHandled);
       	 if IsHandled then
            		exit;
   
[IntegrationEvent(false, false)]
    local procedure OnBeforeCorrectDocumentAfterPaymentUsage (DocumentNo: Code[20]; var CustLedgerEntry: Record "Cust. Ledger Entry"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; IsHandled: Boolean)
    begin      
    end;
`

Next Object: 
page 31187 "Sales Adv. Usage FactBox CZZ"  

add to trigger OnAfterGetCurrRecord
`trigger OnAfterGetCurrRecord
Var IsHandled: Boolean;
begin
OnAfterGetCurrRecordEvent (Rec, IsHandled);
        if IsHandled then
            exit;
`

`[IntegrationEvent(false, false)]
    local procedure OnAfterGetCurrRecordEvent(var SalesLine:Record "Sales Line"; IsHandled: Boolean)
    begin      
    end;
`

And Same for Purchase Side of Advance
codeunit 31019 "PurchAdvLetterManagement CZZ"
Procedure PostAdvancePaymentUsage - Create integration event for Handling by our side

`procedure PostAdvancePaymentUsage
Var IsHandled: Boolean;
begin
OnBeforePostAdvancePaymentUsage (AdvLetterUsageDocTypeCZZ, DocumentNo, PurchInvHeader, VendorLedgerEntry, GenJnlPostLine, Preview, IsHandled);
        	if IsHandled then
           		 exit;
`
`[IntegrationEvent(true, false)]
    local procedure OnBeforePostAdvancePaymentUsage (AdvLetterUsageDocTypeCZZ: Enum "Adv. Letter Usage Doc.Type CZZ"; DocumentNo: Code[20]; var PurchInvHeader: Record "Purch. Inv. Header"; var VendorLedgerEntry: Record "Vendor Ledger Entry"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; Preview: Boolean; IsHandled: Boolean)
    begin      
    end;
`

And Purchase Factbox
page 31189 "Purch. Adv. Usage FactBox CZZ"
add to trigger OnAfterGetCurrRecord

`trigger OnAfterGetCurrRecord
Var IsHandled: Boolean;
begin
OnAfterGetCurrRecordEvent (Rec, IsHandled);
        	if IsHandled then
           		 exit;
`

`[IntegrationEvent(false, false)]
    local procedure OnAfterGetCurrRecordEvent(var PurchaseLine:Record " Purchase Line"; IsHandled: Boolean)
    begin      
    end;
`

Best Regards
Karel Končel

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10575.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 55780.
