### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134330 "ERM Purchase Credit Memo"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#22077]
[Event Request]Application “Tests-ERM”, Codeunit 134330 "ERM Purchase Credit Memo"

Could you please insert the OnTestInitialize Event at the beginning of the test procedure CrMemoGetPostedDocumentLinesPostedPurchShptUnitPrice?

![pic1](https://user-images.githubusercontent.com/45795262/217561700-692792f1-1bcd-4aab-8dd6-fb9d05c6f988.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53123.
