### ISSUE TITLE
The type or method 'CalculateForecast' cannot be used for 'Extension' development

### ISSUE THREAD

**Issue by Ferrer32** [microsoft/ALAppExtensions#2208]
I've converted the report 'Report 840 - Suggest Worksheet Lines' using Txt2AL tool and then there are an issue that don't let me continue developing.
These two methods throws the errors below:

**The type or method 'CalculateForecast' cannot be used for 'Extension' development**
and
**The type or method 'CalculateMaxDueDate' cannot be used for 'Extension' development**

- CashFlowForecastHandler.CalculateForecast => from the "Cash Flow Forecast Handler" Codeunit.
- PaymentTerms.CalculateMaxDueDate("Document Date") => a record from the "Payment Terms" table.

The point is if I can't use these methods, how can I work with the standard BC functionality? Or on the other hand If I must create my own method to replace the _forbidden methods_.

Thanks in advance

**Comment by Ferrer32** [comment]
Hi all.

I'm posting this to keep you all updated about the posible solution I've reached.

I've developed an EventSubscriber that subscribes to the event 'OnBeforeInsertSalesLine' from the Codeunit "Job Create-Invoice" so I can include there the functionality I want to do.

I think that Microsoft wants us to use more the events.

I hope this helps all of you with the same doubt as me.

**Comment by RomanZanizdra** [comment]
Hi Ferrer32. 
Short question, do you still have some issues with that functions are not external? I ask because the functions you mentioned are already external for a quite long time, at least they external in 14.x and you created your request in April. So the question is how it should be so?

**Comment by RomanZanizdra** [comment]
Hi Ferrer32. 
Let's close this issue at this moment, due to the reason mentioned in my previous post. If you still will experience any problems with these functions just let us know.

**Comment by Ferrer32** [comment]
Hi RomanZanizdra.

When I had those issues I was using 13.x version. At the moment I'm not having any other issue like that maybe due to the new 14.x version as you mentioned.

I will close the issue.
Thank you for the answer.
