### ISSUE TITLE
[Request For External] Remove scope OnPrem from Table 11000001 "Payment History" GenerateExportfilename

### ISSUE THREAD

**Issue by VPaas2** [microsoft/ALAppExtensions#22081]
In order to be able to change target to cloud, please remove the scope OnPrem from the function GenerateExportfilename. (The exportfilename is used to download to the client, not upload to the server)

```
[Scope('OnPrem')]
    procedure GenerateExportfilename(New: Boolean) FileName: Text[250]
    begin
        if ("File on Disk" = '') or New then begin
            "Day Serial Nr." := GetNextDaySerialNo();
            "Sent On" := Today;
            "File on Disk" := GenerateNewFileName();
            "Sent By" := UserId();
        end else
            "Number of Copies" := "Number of Copies" + 1;

        Modify();
        exit("File on Disk");
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53117.
