### ISSUE TITLE
[Request For External] Remove scope OnPrem from Codeunit 11000001 "Financial Interface Telebank" - "Initialize GJLine"

### ISSUE THREAD

**Issue by VPaas2** [microsoft/ALAppExtensions#22085]
In order to be able to change target to cloud, please remove the scope OnPrem from the following function:

 ```
   [Scope('OnPrem')]
    procedure "Initialize GJLine"(var GenJnlLine: Record "Gen. Journal Line")
    begin
        OnBeforeInitializeGJLine(GenJnlLine, "Journal template");
        if GenJnlLine.Find('+') then
            GenJnlLine."Line No." := GenJnlLine."Line No." + 1
        else
            GenJnlLine."Line No." := 1;
        GenJnlLine.Init();
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53117.
