### ISSUE TITLE
[New Event Request] CU 408 DimensionManagement - procedure AddDefaultDimensionAllowedDimensionValue

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#22088]
Hi- Two requests in same procedure:

existing code:

    procedure AddDefaultDimensionAllowedDimensionValue(DimensionValue: Record "Dimension Value")
    var
        DefaultDimension: Record "Default Dimension";
    begin
        DefaultDimension.SetRange("Dimension Code", DimensionValue."Dimension Code");
        DefaultDimension.SetRange("Value Posting", DefaultDimension."Value Posting"::"Code Mandatory");
        DefaultDimension.SetFilter("Allowed Values Filter", '<>%1', '');
        if DefaultDimension.FindSet(true) then
        ...
    end;

Requested Adjustment:

    procedure AddDefaultDimensionAllowedDimensionValue(DimensionValue: Record "Dimension Value")
    var
        DefaultDimension: Record "Default Dimension";
        IsHandled: Boolean;         // new var
    begin
        // new Event #1 >> BEGIN
        IsHandled := false;
        OnAddDefaultDimensionAllowedDimensionValueOnBeforeSetFilters(DimensionValue, IsHandled);
        if IsHandled then
            exit;
        // new Event #1 >> END
        DefaultDimension.SetRange("Dimension Code", DimensionValue."Dimension Code");
        DefaultDimension.SetRange("Value Posting", DefaultDimension."Value Posting"::"Code Mandatory");
        DefaultDimension.SetFilter("Allowed Values Filter", '<>%1', '');
        // new Event #2 >> BEGIN
        OnAddDefaultDimensionAllowedDimensionValueOnAfterSetFilters(DefaultDimension);
        // new Event #2 >> END
        if DefaultDimension.FindSet(true) then
        ...
    end;

    // signature for Event#1
    [IntegrationEvent(false, false)]
    local procedure OnAddDefaultDimensionAllowedDimensionValueOnBeforeSetFilters(DimensionValue: Record "Dimension Value"; IsHandled: Boolean);
    begin
    end;

    // signature for Event#2
    [IntegrationEvent(false, false)]
    local procedure OnAddDefaultDimensionAllowedDimensionValueOnAfterSetFilters(var DefaultDimension: Record "Default Dimension");
    begin
    end;

Use case (event#1): We have a client that does not like the automatic addition of allowed values in Default Dimension "Value Posting"::"Code Mandatory" records.

use case (event#2): gives ability to tailor the exact default dimension records that will receive an updated "Allowed Values Filter".

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53187.
