### ISSUE TITLE
[Event Request] Codeunit 423 Change Log Management - procedure LogModification - OnLogModificationOnAfterCheckSecurityFiltering

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#22091]
Please add the following existing Event OnLogModificationOnAfterCheckSecurityFiltering to procedure LogModification in Codeunit 423 Change Log Management

```
[Event Request] Codeunit 423 Change Log Management - procedure LogModification
var
    xRecRef: RecordRef;
    FldRef: FieldRef;
    xFldRef: FieldRef;
    i: Integer;
    IsReadable: Boolean;
begin
    OnBeforeLogModification(RecRef);
    if RecRef.IsTemporary then
        exit;

    if not IsLogActive(RecRef.Number, 0, 1) then
        exit;

    xRecRef.Open(RecRef.Number, false, RecRef.CurrentCompany());
    OnLogModificationOnBeforeCheckSecurityFiltering(xRecRef);
    xRecRef."SecurityFiltering" := SECURITYFILTER::Filtered;

    OnLogModificationOnAfterCheckSecurityFiltering(xRecRef); // <-- NEW EVENT

    if xRecRef.ReadPermission then begin
        IsReadable := true;
        if not xRecRef.Get(RecRef.RecordId) then
            exit;
    end;
    ...
```

```
[IntegrationEvent(false,false)]
local procedure OnLogModifcationOnAfterCheckSecurityFiltering(var xRecRef: RecordRef)
begin
end;
```

**Comment by AlexanderYakunin** [comment]
This ask looks like security issue, please provide explanation why you need this?

**Comment by MH1612** [comment]
@AlexanderYakunin  Our originally accepted event request was: https://github.com/microsoft/ALAppExtensions/issues/20724 and the event is now on the wrong line.
In our case, we overwrite the security filter in a special scenario for a Logging extension.
In the past there were scenarios in which the change log is not written correctly due to security filters. It's about writing the change log, where we want to log all changes, even if they may not have passed the security filter. The question here, wouldn't it make more sense to change the security filtering in the standard.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15512.
