### ISSUE TITLE
MakingTaxDigital - Excluded Fraud Prevention Header - Public Port

### ISSUE THREAD

**Issue by MatDDev** [microsoft/ALAppExtensions#22102]
Hello,

I would like to know, why the Gov-Client-Public-Port fraud prevention header is excluded from the MTD App, when sending the requests to the HMRC?

![image](https://user-images.githubusercontent.com/13900033/217844878-dd3e5592-af3d-4489-94c3-8c09bcaffc1c.png)

I know, or at least I assume it's not possible to retrieve the public port using BC SaaS, but HRMC is asking why this cannot be supplied to all the requests. Is there any documentation/information that clearly states that this fraud prevention header has been exlucded becasuse of...?

Mat

**Comment by AlexanderYakunin** [comment]
Hello! This is not an extensibility request, we cannot provide answers to such questions here. Please use Yammer for Partners or contact technical support to ask such question.
