### ISSUE TITLE
[Event Request] Codeunit 9510 Document Service Management 

### ISSUE THREAD

**Issue by mynavblog** [microsoft/ALAppExtensions#2211]
Dear Team,

Could you add the Event in Codeunit 9510 Document Service Management in function SetProperties?

It is needed to have event called:  OnBeforeSetProperties with parameter VAR DocumentServiceRec.  Like on screen below:

![image](https://user-images.githubusercontent.com/37371997/56748668-8bc61480-6780-11e9-827b-7886c532e335.png)

And add it before setting the properties. Place below:

![image](https://user-images.githubusercontent.com/37371997/56748760-adbf9700-6780-11e9-86ae-79d76993f607.png)

Thank you in advance.

Best regards,
Krzysztof

**Comment by AlexanderYakunin** [comment]
Can I ask how you would like to use this event for system table?

**Comment by mynavblog** [comment]
Hi,

I would like to change the value of the Folder field in the Record. It is needed to be able to write to custom folders (for example one per Service Order) instead of one fixed one. Now to accomplish so we needed to rewrite whole Codeunit to new one and also copy Dlls for service. Which is not good option.

Best regards,
Krzysztof

**Comment by AlexanderYakunin** [comment]
I assume Document Service is read-only table for application. Are you sure?

**Comment by mynavblog** [comment]
Hi Alexander,
My idea is to change this value in field Folder and do not modify the record. If you have other idea how to using this Codeunit put the files to different folders more than welcome. But It seems that some event is needed to fulfill requirement. In my opinion change the Folder value is the easiest one.

Best regards,
Krzysztof

**Comment by mynavblog** [comment]
Dear Team,
What is the status of this? Is there any way to get the event?

Best regards,
Krzysztof
