### ISSUE TITLE
[Access Request] report 11723 "Cust.- Bal. Reconciliation CZL"

### ISSUE THREAD

**Issue by jlorenc01** [microsoft/ALAppExtensions#22125]
Hi there,

could you please change the Access Scope of the `TempCVLedgerEntryBuffer: Record "CV Ledger Entry Buffer" temporary;` to protected?

```
protected var
    TempCVLedgerEntryBuffer: Record "CV Ledger Entry Buffer" temporary;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10306.
