### ISSUE TITLE
[Event Request] - New event OnBeforeIspUrchLineEmptyInQtyToRecIsZero inside Table 38 "Purchase Header"

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#22120]
Hello, please consider adding the following event to Table 38 "Purchase Header"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeIspUrchLineEmptyInQtyToRecIsZero(var PurchLine: Record "Purchase Line")
    begin
    end;
```

and call it inside the "QtyToReceiveIsZero" procedure:

```
    procedure QtyToReceiveIsZero(): Boolean
    begin
        PurchLine.Reset();
        PurchLine.SetRange("Document Type", "Document Type");
        PurchLine.SetRange("Document No.", "No.");
        PurchLine.SetFilter("Qty. to Receive", '<>0');

        **OnBeforeIspUrchLineEmptyInQtyToRecIsZero(PurchLine);**

        exit(PurchLine.IsEmpty);
    end;
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53447.
