### ISSUE TITLE
Codeunit 9064 "Stor. Serv. Auth. Shared Key" function GetHeaderValueOrEmpty throws an exception

### ISSUE THREAD

**Issue by PaulFurlet** [microsoft/ALAppExtensions#22132]
I am doing Customer Statement with own report that has communication to Azure Blob Storage and I encounter a problem that I am receiving an error in the end despite everything is fine: 
![image](https://user-images.githubusercontent.com/17279234/218460345-1053d08c-5a2c-4c57-8f3d-6e80baf3cbf5.png)
The codeunit function specified in topic is causing the issue (at least in the end). I cannot debug actual behavior because functions are set as non-debuggable.
I do not dare to do `ClearLastError()` after call `Resp := BlobClient.PutBlobBlockBlobStream(FileName, InStr);` because I could miss something definitely crucial.
The same behavior is for `BlobClient.GetBlobAsStream()`
To illustrate the issue I created small demo app

```al
pageextension 50100 CustomerListExt extends "Customer List"
{
    actions
    {
        addfirst(processing)
        {
            action(TestUpload)
            {
                Caption = 'Test Upload';
                ApplicationArea = All;
                trigger OnAction()
                var
                    InS: InStream;
                    FileName: Text;
                begin
                    if UploadIntoStream('', '', 'All files (*.*)|*.*', FileName, InS) then
                        SendFileToAzure(InS, FileName);
                end;
            }
        }
    }

    local procedure SendFileToAzure(var InStr: InStream; FileName: Text)
    var
        BlobClient: Codeunit "ABS Blob Client";
        Resp: Codeunit "ABS Operation Response";
        StorageAuth: Codeunit "Storage Service Authorization";
        Auth: Interface "Storage Service Authorization";
        AccountKey: Text;
        AccountName: Text;
        RequestUrl: Text;
        ContainerName: Text;
    begin
        GetBlobStorageParams(RequestUrl, AccountName, AccountKey, ContainerName);
        Auth := StorageAuth.CreateSharedKey(AccountKey);
        BlobClient.Initialize(AccountName, ContainerName, Auth);
        Resp := BlobClient.PutBlobBlockBlobStream(FileName, InStr); //here exception is thrown
        if not Resp.IsSuccessful() then
            Error(Resp.GetError())
        else
            Message('File is uploaded successfully.\Here is intermediate error:\%1\\Here is error stack:\%2', GetLastErrorText(), GetLastErrorCallStack());
    end;

    local procedure GetBlobStorageParams(var resourceurl: Text; var keyname: Text; var keyvalue: Text; var ContainerName: Text)
    var
        UrlLbl: Label '%1://%2.blob.%3/', Comment = '%1 - data after DefaultEndpointsProtocol=; %2 - Account Name; %3 - data after EndpointSuffix=';
        data: List of [Text];
        element: Text;
        endpoint, protocol : Text;
        AzureBlobConnectionString: Text;
    begin
        //actual ConnectionString is taken from setup
        AzureBlobConnectionString := 'DefaultEndpointsProtocol=https;AccountName=<YOURACCOUNTNAME>;AccountKey=<YOURACCOUNTKEY>;EndpointSuffix=core.windows.net';
        //actual ContainerName is taken from setup
        ContainerName := '<YOURCONTAINERNAME>';

        //parsing Connection String
        data := AzureBlobConnectionString.Split(';');
        resourceurl := '';
        keyname := '';
        keyvalue := '';
        foreach element in data do
            case true of
                element.Contains('DefaultEndpointsProtocol='):
                    protocol := element.Substring(StrLen('DefaultEndpointsProtocol=') + 1);
                element.Contains('EndpointSuffix='):
                    endpoint := element.Substring(StrLen('EndpointSuffix=') + 1);
                element.Contains('AccountName='):
                    keyname := element.Substring(StrLen('AccountName=') + 1);
                element.Contains('AccountKey='):
                    keyvalue := element.Substring(StrLen('AccountKey=') + 1);
            end;
        resourceurl := StrSubstNo(UrlLbl, protocol, keyname, endpoint);
    end;
/*
File is uploaded successfully.
Here is intermediate error:
Exception of type 'Microsoft.Dynamics.Nav.Types.Exceptions.NavNclInvalidHeaderException' was thrown.

Here is error stack:
"Stor. Serv. Auth. Shared Key"(CodeUnit 9064).GetHeaderValueOrEmpty line 4 - System Application by Microsoft
"Stor. Serv. Auth. Shared Key"(CodeUnit 9064).CreateSharedKeyStringToSign line 19 - System Application by Microsoft
"Stor. Serv. Auth. Shared Key"(CodeUnit 9064).GetSharedKeySignature - System Application by Microsoft
"Stor. Serv. Auth. Shared Key"(CodeUnit 9064).Authorize line 7 - System Application by Microsoft
"ABS Web Request Helper"(CodeUnit 9045).PrepareRequestMsg - System Application by Microsoft
"ABS Web Request Helper"(CodeUnit 9045).PrepareRequestMsg - System Application by Microsoft
"ABS Web Request Helper"(CodeUnit 9045).PutOperation - System Application by Microsoft
"ABS Client Impl."(CodeUnit 9051).PutBlobBlockBlob line 23 - System Application by Microsoft
"ABS Client Impl."(CodeUnit 9051).PutBlobBlockBlobStream line 10 - System Application by Microsoft
"ABS Blob Client"(CodeUnit 9053).PutBlobBlockBlobStream line 4 - System Application by Microsoft
CustomerListExt(PageExtension 50100).SendFileToAzure line 14 - ALProject1 by Default publisher
CustomerListExt(PageExtension 50100)."TestUpload - OnAction"(Trigger) line 6 - ALProject1 by Default publisher
*/
}
```

proof of work
Using access keys for the Azure Blob Container
![image](https://user-images.githubusercontent.com/17279234/218457481-ef02fb9a-1015-4a05-bf4b-f3b0808e2cf9.png)
running coded action
![image](https://user-images.githubusercontent.com/17279234/218458002-b89d712f-1a1c-4b89-ab0f-44572aa3e223.png)
selecting file for upload
![image](https://user-images.githubusercontent.com/17279234/218458100-4858004c-3076-4314-82ca-ea82f71fc875.png)
file uploaded successfully and message shown
![image](https://user-images.githubusercontent.com/17279234/218458366-b053653e-70d1-4d87-890f-510fccf9864b.png)
proof that file is in the container
![image](https://user-images.githubusercontent.com/17279234/218458163-742b7079-db05-4f5a-a3b9-224a7fe3993f.png)

**Comment by pri-kise** [comment]
@PaulFurlet thanks for you detailled example.

I guess, that I maybe found the source of the error by your callstack.

It's probably related to the following code path:

https://github.com/microsoft/ALAppExtensions/blob/41405db353de27492e4785694dfb8cb11bf57f8d/Modules/System/Azure%20Storage%20Services%20Authorization/src/SharedKey/StorServAuthSharedKey.Codeunit.al#L88

```al
    local procedure GetHeaderValueOrEmpty(Headers: HttpHeaders; HeaderKey: Text): Text
    var
        ReturnValue: array[1] of Text;
    begin
        if not Headers.GetValues(HeaderKey, ReturnValue) then
            exit('');

        if HeaderKey = 'Content-Length' then
            if ReturnValue[1] = '0' then
                exit('');

        exit(ReturnValue[1]);
    end;
```
Instead of using the return value of GetValues, it might be better to check for the existence of an header with the **.Contains** Method.
https://learn.microsoft.com/de-de/dynamics365/business-central/dev-itpro/developer/methods-auto/httpheaders/httpheaders-contains-method

Feel free to created a Pull Request for the system application to refactor this codeunit to call Contains before the call of `GetValues` and exit the procedure as early as possible.

**Comment by pri-kise** [comment]
@darjoo you have taken part at similiar issues for the storage service authorization, maybe you can have a look at this issue, too.

**Comment by PaulFurlet** [comment]
@pri-kise thanks for pointing, created PR #22139

**Comment by PaulFurlet** [comment]
@pri-kise is this normal behavior or did I do something wrong? https://github.com/microsoft/ALAppExtensions/actions/runs/4169770631/jobs/7218103696

**Comment by darjoo** [comment]
Thanks for the ping @pri-kise.

You're right that we should add `.contains.` before `.get` as it will always throw an exception if the key does not exist which can be caught and ignored but will show up in `GetLastError`. Whereas `.contains` will simply return true/false.

I'll review your PR today @PaulFurlet

**Comment by darjoo** [comment]
> @pri-kise is this normal behavior or did I do something wrong? https://github.com/microsoft/ALAppExtensions/actions/runs/4169770631/jobs/7218103696

It does not seem related to your changes, I'll ping the team who owns the pipeline infrastructure to take a look.

**Comment by JesperSchulz** [comment]
This appears to be resolved. Also, the System Application is now debuggable. If this issue persists, please create a new issue.
