### ISSUE TITLE
Integration Event OnAfterCalcAvailableQty is marked as OnPrem - Removal request codeunit 5400 'Available Management'

### ISSUE THREAD

**Issue by DanielBalanCgk** [microsoft/ALAppExtensions#22131]
Hello,

We would like to request _**changing the integration event**_ from _**codeunit 5400 Available Management**_  by **_removing the scope 'OnPrem'_** so this could be also used on the cloud version.

![image](https://user-images.githubusercontent.com/40453475/218450381-e0fb2843-c260-4c83-8bba-20ff7dfb8aa0.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10268.
