### ISSUE TITLE
[event request] OnBeforeValidateDropShipment field "Drop Shipment" in sales line table

### ISSUE THREAD

**Issue by RobertatK3** [microsoft/ALAppExtensions#22141]
We have extended the Enum Sales Line Type and want to be able to use drop shipment for that type. But because of a TestField on Type = Item this is not possible.
Therefor I like to request for an event publisher OnBeforeValidateDropShipment with an IsHandled boolean to skip the complete validation.

```
            trigger OnValidate()
            var
                IsHandled: Boolean;
            begin
                IsHandled := false;
                OnBeforeValidateDropShipment(Rec, xRec, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;

```
```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeValidateDropShipment(var SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line"; CurrentFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53447.
