### ISSUE TITLE
how to view license from business central ?

### ISSUE THREAD

**Issue by TharunMuthu** [microsoft/ALAppExtensions#2214]
Hi All,

Is it possible to see license from business central like RTC ? 

Regards,
Muthu

**Comment by ikoletic** [comment]
This issue is a question. Please submit your questions on [business central community ](https://community.dynamics.com/business/f/758) or on [BC development yammer groups](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035).
