### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - OnCopyFromSalesToPurchDocOnBeforePurchaseHeaderInsert

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#22145]
Hi, 

we need the parameter "VendorNo" to be passed as a additional parameter in the event publisher "OnCopyFromSalesToPurchDocOnBeforePurchaseHeaderInsert". Can you please check this? Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53388.
