### ISSUE TITLE
[Set External] SalesLine.SaveLookupSelection, SalesLine.RestoreLookupSelection

### ISSUE THREAD

**Issue by NKarolak** [microsoft/ALAppExtensions#22151]
`SalesLine.SaveLookupSelection` and `SalesLine.RestoreLookupSelection` are currently set to internal. Please set them to public, so that we can call them in local copies of a Sales Order page.
Consider for Purchase as well.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10134.
