### ISSUE TITLE
[Event Request] Codeunit  6620 "Copy Document Mgt." - Procedure: CopySalesShptLinesToDoc - Event: OnAfterCopySalesShptLinesToDoc

### ISSUE THREAD

**Issue by ZepposBE** [microsoft/ALAppExtensions#22156]
Hi Development Team,

We would like to see the following event added to the Codeunit  6620 "Copy Document Mgt.":
Similar to my other requests:

- [OnAfterCopySalesInvLinesToDoc](https://github.com/microsoft/ALAppExtensions/issues/22158)
- [OnAfterCopySalesCrMemoLinesToDoc](https://github.com/microsoft/ALAppExtensions/issues/22159)
- [OnAfterCopySalesReturnRcptLinesToDoc](https://github.com/microsoft/ALAppExtensions/issues/22160)
- [OnAfterCopyPurchRcptLinesToDoc](https://github.com/microsoft/ALAppExtensions/issues/22161)
- [OnAfterCopyPurchInvLinesToDoc](https://github.com/microsoft/ALAppExtensions/issues/22162)
- [OnAfterCopyPurchCrMemoLinesToDoc](https://github.com/microsoft/ALAppExtensions/issues/22164)
- [OnAfterCopyPurchReturnShptLinesToDoc](https://github.com/microsoft/ALAppExtensions/issues/22165)

The CopySalesShptLinesToDoc procedure is public and also used in automated testing when copying lines from different documents.
We are missing and 'end of lines loop'/ 'before end of procedure' event to process information which was gathered during the procedure.

The automated tests are also using these procedures to test a copy line from multiple documents, so for our feature, we are unable to write successful tests.

The code with the requested added event:

```
procedure CopySalesShptLinesToDoc(ToSalesHeader: Record "Sales Header"; var FromSalesShptLine: Record "Sales Shipment Line"; var LinesNotCopied: Integer; var MissingExCostRevLink: Boolean)
    var
        // vars
    begin 
        MissingExCostRevLink := false;
        InitCurrency(ToSalesHeader."Currency Code");
        OpenWindow();

        OnBeforeCopySalesShptLinesToDoc(TempDocSalesLine, ToSalesHeader, FromSalesShptLine);

        with FromSalesShptLine do
            if FindSet() then
                repeat

                // --- Code to handle the lines ---

                    OnCopySalesShptLinesToDocOnAfterCopySalesShptLineToSalesLine(FromSalesShptLine, ToSalesLine);
                until Next() = 0;
        >>>>>>> New Event <<<<<<<<
        OnAfterCopySalesShptLinesToDoc(ToSalesHeader, FromSalesShptLine, LinesNotCopied, MissingExCostRevLink);
        >>>>>>> New Event <<<<<<<<
        CloseWindow();
    end;

```

The new event:

```
  [IntegrationEvent(false, false)]
    local procedure OnAfterCopySalesShptLinesToDoc(ToSalesHeader: Record "Sales Header"; var FromSalesShptLine: Record "Sales Shipment Line"; var LinesNotCopied: Integer; var MissingExCostRevLink: Boolean)
    begin
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53388.
