### ISSUE TITLE
[Event Request] Codeunit 6620 "Copy Document Mgt." - Procedure: CopySalesInvLinesToDoc - Event: OnAfterCopySalesInvLinesToDoc

### ISSUE THREAD

**Issue by ZepposBE** [microsoft/ALAppExtensions#22158]
Hi Development Team,

We would like to see the following event added to the Codeunit 6620 "Copy Document Mgt.":
Similar to my other requests:

- [OnAfterCopySalesShptLinesToDoc](https://github.com/microsoft/ALAppExtensions/issues/22156)
- [OnAfterCopySalesCrMemoLinesToDoc](https://github.com/microsoft/ALAppExtensions/issues/22159)
- [OnAfterCopySalesReturnRcptLinesToDoc](https://github.com/microsoft/ALAppExtensions/issues/22160)
- [OnAfterCopyPurchRcptLinesToDoc](https://github.com/microsoft/ALAppExtensions/issues/22161)
- [OnAfterCopyPurchInvLinesToDoc](https://github.com/microsoft/ALAppExtensions/issues/22162)
- [OnAfterCopyPurchCrMemoLinesToDoc](https://github.com/microsoft/ALAppExtensions/issues/22164)
- [OnAfterCopyPurchReturnShptLinesToDoc](https://github.com/microsoft/ALAppExtensions/issues/22165)

The CopySalesInvLinesToDoc procedure is public and also used in automated testing when copying lines from different documents.
We are missing and 'end of lines loop'/ 'before end of procedure' event to process information which was gathered during the procedure.

The automated tests are also using these procedures to test a copy line from multiple documents, so for our feature, we are unable to write successful tests.

The code with the requested added event:

```
procedure CopySalesInvLinesToDoc(ToSalesHeader: Record "Sales Header"; var FromSalesInvLine: Record "Sales Invoice Line"; var LinesNotCopied: Integer; var MissingExCostRevLink: Boolean)
    var
        // vars
    begin
        IsHandled := false;
        OnBeforeCopySalesInvLinesToDoc(ToSalesHeader, FromSalesInvLine, CopyJobData, RecalculateLines, IsHandled);
        if IsHandled then
            exit;

        MissingExCostRevLink := false;
        InitCurrency(ToSalesHeader."Currency Code");
        TempSalesLineBuf.Reset();
        TempSalesLineBuf.DeleteAll();
        TempItemTrkgEntry.Reset();
        TempItemTrkgEntry.DeleteAll();
        OpenWindow();
        InitAsmCopyHandling(true);
        TempSalesInvLine.DeleteAll();

        OnBeforeCopySalesInvLines(TempDocSalesLine, ToSalesHeader, FromSalesInvLine, CopyJobData);

        // Fill sales line buffer
        SalesInvLineCount := 0;
        FirstLineText := false;
        with FromSalesInvLine do
            if FindSet() then
                repeat
                    
                    // --- Code to handle the FromSalesInvLines ---

                    OnAfterCopySalesInvLine(TempDocSalesLine, ToSalesHeader, TempSalesLineBuf, FromSalesInvLine);
                until Next() = 0;

        OnCopySalesInvLinesToDocOnAfterFillSalesLinesBuffer(ToSalesHeader);

        // Create sales line from buffer
        UpdateWindow(1, FromLineCounter);
        BufferCount := 0;
        FirstLineShipped := true;
        with TempSalesLineBuf do begin
            // Sorting according to Sales Line Document No.,Line No.
            SetCurrentKey("Line No.");
            SalesLineCount := 0;
            if FindSet() then
                repeat
                    if Type = Type::Item then
                        SalesLineCount += 1;
                until Next() = 0;
                if FindSet() then begin
            
                    // --- Code to handle the TempSalesLineBuf ---

                    OnCopySalesInvLinesToDocOnAfterCopySalesDocLine(ToSalesLine, FromSalesInvLine);
                until Next() = 0;
            end;
        end;
        >>>>>>> New Event <<<<<<<<
        OnAfterCopySalesInvLinesToDoc(ToSalesHeader, FromSalesInvLine, LinesNotCopied, MissingExCostRevLink);
        >>>>>>> New Event <<<<<<<<
        CloseWindow();
    end;
```

The new event:

```
[IntegrationEvent(false, false)]
    local procedure OnAfterCopySalesInvLinesToDoc(ToSalesHeader: Record "Sales Header"; var FromSalesInvLine: Record "Sales Invoice Line"; var LinesNotCopied: Integer; var MissingExCostRevLink: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53388.
