### ISSUE TITLE
[Extensibility Request] page 9843 "User Lookup"

### ISSUE THREAD

**Issue by SWE-Tina** [microsoft/ALAppExtensions#22168]
Please make page 9843 "User Lookup" extensible so code / filtering can be set in OnOpenPage e.g. and match to Users list.
Internal work item: [AB#538676](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538676)

**Comment by AlexanderYakunin** [comment]
Please request event or what is needed for you here.

**Comment by pri-kise** [comment]
This is very clear in my opinion an access request for the `page 9843 "User Lookup" ` in the system application.

See: https://github.com/microsoft/ALAppExtensions/blob/1470b365969e8c08eb1257d1fc85bba90cab66ad/Modules/System/User%20Selection/src/UserLookup.Page.al#L11

**Comment by SWE-Tina** [comment]
Exactly - Removing the "extensible = false" would be the best.

**Comment by Groenbech96** [comment]
Please create issue on BCApps for this. 
https://github.com/microsoft/BCApps/blob/1d9a16406a36be1c699a91ad8f92502ae54dbc2b/src/System%20Application/App/User%20Selection/src/UserLookup.Page.al#L4

The extensibility = false is by design, but ask there if it can be changed.
