### ISSUE TITLE
[Event Request] Checklist Execution / Video Played

### ISSUE THREAD

**Issue by DWarsop** [microsoft/ALAppExtensions#22178]
For our app we're trying to capture how well a user is progressing through our custom checklist. As a lot of the Checklist functionality/tables are internal this proves to be a tricky area. One area especially we want to track is users watching checklist videos. 

The simplest location (and least exposure as its Public already) would be the below:

Codeunit: 3710 Video, Procedure: Play()
![image](https://user-images.githubusercontent.com/35226476/219341801-e926caad-4d02-4bf0-b789-69cdb934fb7a.png)

Exposing something like "**OnAfterPlay(Url)**" so I could look back through my custom videos (based on the url, as I store them in a table) to find which one was played and log it. The event could either be here, or called from the VideoImpl codeunit Play().

![image](https://user-images.githubusercontent.com/35226476/219344796-4e0a9c90-c351-4287-afe1-65741d5f6a3a.png)

I notice there is the below event already in this codeunit, however this is only called on the manual drilldown on the Product Videos page. If the ChecklistBanner.RunVideo() procedure was fed through to that buffer table that would be handy in tracking which video was played aswell (but that's less of an event request and more a refactor):
![image](https://user-images.githubusercontent.com/35226476/219343330-3735d3fc-328e-4e11-a03b-a28ad345f24b.png)

The harder location (most exposure) but would be nice to have would be the below:

Codeunit: 1996 "Checklist Banner", Procedure: ExecuteChecklistItem()
![image](https://user-images.githubusercontent.com/35226476/219339833-979ea38a-e463-4508-b317-919f8070d335.png)

Exposing something like "**OnAfterExecuteChecklistItem(GuidedExperienceItem)**" so I could identify which item was completed and associate that back to the custom guided experience item I've inserted to log it. This would mean exposure of this codeunit/procedure and the guided experience item table so we can relate them however. Could also expose the IsChecklistItemComplete but not needed for my use case. Would be nice to have but appreciate thats a few.

![image](https://user-images.githubusercontent.com/35226476/219346665-d5442740-82f4-4cab-b7ab-191660746faa.png)

**Comment by Groenbech96** [comment]
The system module has been released on GitHub.  https://github.com/microsoft/BCApps
If these changes are still relevant to you, i would like to ask you to create a pull request with your suggested events. 
Please add @haoranpb and me.
