### ISSUE TITLE
[Event-Request] Table 37 "Sales Line" - OnCopyFromGLAccountOnBeforeTestDirectPosting

### ISSUE THREAD

**Issue by moomencegekadsa** [microsoft/ALAppExtensions#22171]
Hello Microsoft,

This request/question is in relation to #21292, this request is implemented differently in the 21.4 release as seen in code below (notice the added begin..end statement for IsHandled). 
First question is why this was implemented differently from our request? 
And if this was an intentional change; why include the **local** procedure  _InitDeferralCode()_ within this new begin..end statement? We cannot call this procedure from an external object if we want to implement our own customization. 
Also perhaps a small note, does the name of the event publisher still cover the implementation as below?
Please let us know if we can expect a new change on the code below or that we should refactor?

Thank you in advance for your reply

Kind regards,
Martin Oomen
Cegeka

```
local procedure CopyFromGLAccount()
    var
        IsHandled: Boolean;
    begin
        GLAcc.Get("No.");
        GLAcc.CheckGLAcc();
        IsHandled := false;
        OnCopyFromGLAccountOnBeforeTestDirectPosting(Rec, GLAcc, SalesHeader, IsHandled);

        if not IsHandled then ++begin
            if not "System-Created Entry" then
                GLAcc.TestField("Direct Posting", true);
            Description := GLAcc.Name;
            "Gen. Prod. Posting Group" := GLAcc."Gen. Prod. Posting Group";
            "VAT Prod. Posting Group" := GLAcc."VAT Prod. Posting Group";
            "Tax Group Code" := GLAcc."Tax Group Code";
            "Allow Invoice Disc." := false;
            "Allow Item Charge Assignment" := false;
            InitDeferralCode();
    ++end;
        OnAfterAssignGLAccountValues(Rec, GLAcc, SalesHeader);
    end;
```

**Comment by Vadim-Stepanenko** [comment]
Please just use existing version, obsoleting it now, to change again seems like adding to the mess, and without obsoleting it would be breaking for someone using it as is.

**Comment by Vadim-Stepanenko** [comment]
After more consideration we will obsolete this current event and introduce a new one you can use
OnBeforeTestDirectPosting

**Comment by moomencegekadsa** [comment]
Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53520.
