### ISSUE TITLE
[Extensibility Request] PEPPOL XMLPorts and PEPPOL Management 

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/ALAppExtensions#22175]
In all 3 Version of PEPPOL XML Ports thereis PartyIdentificationID present but not filled or fillable via event.
Please add a procedure in PEPPOL Management Codeunit to fill the field.

```
procedure GetPartyIdentificationID(SalesHeader:Record "Sales Header"; var PartyIdentificationID:Text)
begin
  PartyIdentificationID := '';
  OnAfterGetPartyIdentificationID(SalesHeader; PartyIdentificationID);
end;
```

Event;
`OnAfterGetPartyIdentificationID(SalesHeader:Record "Sales Header"; var PartyIdentificationID:Text);`

---------------

Additionally, in PEPPOL there exist a tag named "invoice/Delivery/DeliveryParty/PartyName/Name" which is not exported in Business Central. Which is not wrong because this tag is optional. But maybe you could add it optionally to be filled just like I requested above?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18389.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 18392.
