### ISSUE TITLE
[Event Request] - New event OnBeforeOKOnPush inside Page 12111 "Show Computed Withh. Contrib."

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#22181]
Hello, please consider adding the following event to Page 12111 "Show Computed Withh. Contrib."

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOKOnPush(var TmpWithHoldContr: Record "Tmp Withholding Contribution"; var IsHandled: Boolean)
    begin
    end;
```

and call it inside the "OKOnPush" procedure :

```
    local procedure OKOnPush()
    var
        **IsHandled: Boolean;**
    begin

        **IsHandled := false;
        OnBeforeOKOnPush(Rec, IsHandled);
        if IsHandled then
            exit;**

        GenJnlLine2.Reset();
        GenJnlLine2.SetRange("Journal Template Name", "Journal Template Name");
        GenJnlLine2.SetRange("Journal Batch Name", "Journal Batch Name");
        GenJnlLine2.SetRange("Line No.", "Line No.");
...
...

```
Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53542.
