### ISSUE TITLE
User Full Name in DropDown fieldgroup

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#22196]
Hello,

Please add the Full Name field to dropdown fieldgroup for table User. It 

Because user table is system, and we can't extend via tableextension.
It would be very user-friendly for selecting user name in system.

Thank you!
Internal work item: [AB#538677](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538677)

**Comment by JesperSchulz** [comment]
Closing this issue, as this is a platform request. I've created a bug for our platform team and hope they will accept it.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25.0.21004.0.
