### ISSUE TITLE
[Event-Request] Table 37 "Sales Line" - CopyFromResource

### ISSUE THREAD

**Issue by obermeiersinghammer** [microsoft/ALAppExtensions#22195]
we need a new event publisher in function CopyFromResource in table Sales Line

    local procedure CopyFromResource()
    var
        IsHandled: Boolean;
    begin
        Res.Get("No.");
        Res.CheckResourcePrivacyBlocked(false);
        IsHandled := false;
        OnCopyFromResourceOnBeforeTestBlocked(Res, IsHandled);
        if not IsHandled then
            Res.TestField(Blocked, false);
        Res.TestField("Gen. Prod. Posting Group");
        Description := Res.Name;
        "Description 2" := Res."Name 2";
        "Unit of Measure Code" := Res."Base Unit of Measure";
        "Unit Cost (LCY)" := Res."Unit Cost";
        "Gen. Prod. Posting Group" := Res."Gen. Prod. Posting Group";
        "VAT Prod. Posting Group" := Res."VAT Prod. Posting Group";
        "Tax Group Code" := Res."Tax Group Code";
        "Allow Item Charge Assignment" := false;
                                                                            **<======== OnBeforeApplyResUnitCost(Rec, Rec, SalesHeader)**
        ApplyResUnitCost(FieldNo("No."));
        InitDeferralCode();
        OnAfterAssignResourceValues(Rec, Res, SalesHeader);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53520.
