### ISSUE TITLE
[Event Request] codeunit 1262 "Pre & Post Process XML Import" - OnBeforePreProcessFile

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#22199]
Hello, can you please add the following Event OnBeforePreProcessFile to codeunit 1262 "Pre & Post Process XML Import"?

```
procedure PreProcessFile(DataExch: Record "Data Exch."; StatementIdPathFilter: Text)
   var
        Handled: Boolean;    
   begin
        Handled := false;
        OnBeforePreProcessFile(Handled, DataExch, StatementIdPathFilter);
        if Handled then
            exit;
        CheckMultipleStatements(DataExch, StatementIdPathFilter);
    end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforePreProcessFile(var Handled: Boolean; DataExch: Record "Data Exch."; StatementIdPathFilter: Text)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53520.
