### ISSUE TITLE
Some permission sets are empty.

### ISSUE THREAD

**Issue by JSebastianN** [microsoft/ALAppExtensions#222]
I.e.
P&P-Q/O/I/R/C, POST  "Post purchase orders, etc."

Perhaps this has been replaced with one of the new "D365xxx" Sets?

W1 13.0 (23896)
Docker image: microsoft/bcsandbox:base

**Comment by ikoletic** [comment]
This seems to have been a transient error. Both P&P-Q/O/I/R/C, POST and D365 PURCH DOC, POST permission sets contain permissions in BC.
