### ISSUE TITLE
[code-defect] Report 11005 VAT Statement Germany total with wrong date filter

### ISSUE THREAD

**Issue by BjEic** [microsoft/ALAppExtensions#22207]
In procedure CalcLineTotal in type "Account Totaling" goes to "Posting Date" in GLAccount."Net Change" instead of "VAT Date"

`                    if GLAcc.FindSet() and (VATStmtLine2."Account Totaling" <> '') then
                        repeat
                            GLAcc.CalcFields("Net Change", "Additional-Currency Net Change");
                            Amount := ConditionalAdd(Amount, GLAcc."Net Change", GLAcc."Additional-Currency Net Change");
                        until GLAcc.Next() = 0;
                    CalcTotalAmount(VATStmtLine2, TotalAmount, TotalEmpty, TotalBase, TotalUnrealizedAmount, TotalUnrealizedBase);`

this causes false sums in Page 475 "VAT Statement Preview". The DrillDown of the Amount filters to "VAT Date" is correct.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53903.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 21.

Build ID to track: 53931.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 53932.
