### ISSUE TITLE
[Event Change/Request] Codeunit 5764 "Whse.-Post Shipment" Event: "OnPostSourceDocumentOnBeforePostSalesHeader"

### ISSUE THREAD

**Issue by FavMY** [microsoft/ALAppExtensions#22209]
Hello everyone,

Since some customers are not trustworthy when paying for their goods, we would like to give these customers the option to also post the invoice directly on shipment.
Therefore we need in this event ("OnPostSourceDocumentOnBeforePostSalesHeader") the possibility to modify the SalesHeader and for further purposes also the Invoice.
Would this be possible to include?

So we need the change on that Event like the following (marked with **):
```
[IntegrationEvent(false, false)]
local procedure OnPostSourceDocumentOnBeforePostSalesHeader(var SalesPost: Codeunit "Sales-Post"**;var** SalesHeader: Record "Sales Header"; WhseShptHeader: Record "Warehouse Shipment Header"; var CounterSourceDocOK: Integer; SuppressCommit: Boolean; var IsHandled: Boolean;**var Invoice: Boolean**)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53539.
