### ISSUE TITLE
[Event Request] page 402 SalesOrderStatistics - Fct. RefreshOnAfterGetRecord

### ISSUE THREAD

**Issue by obermeiersinghammer** [microsoft/ALAppExtensions#22229]
we need a new event publisher in function RefreshOnAfterGetRecord in page 402 SalesOrderStatistics:

    local procedure RefreshOnAfterGetRecord()
    var
        SalesLine: Record "Sales Line";
        TempSalesLine: Record "Sales Line" temporary;
        SalesPostPrepayments: Codeunit "Sales-Post Prepayments";
        OptionValueOutOfRange: Integer;
    begin
        CurrPage.Caption(StrSubstNo(Text000, "Document Type"));

        if PrevNo = Rec."No." then
...
...
        TempVATAmountLine1.ModifyAll(Modified, false);
        TempVATAmountLine2.ModifyAll(Modified, false);
        TempVATAmountLine3.ModifyAll(Modified, false);
        TempVATAmountLine4.ModifyAll(Modified, false);

        OptionValueOutOfRange := -1;
        PrevTab := OptionValueOutOfRange;
                                                                    **<======== RefreshOnAfterGetRecordOnBeforeUpdateHeaderInfo(var Rec (Salesheader), var TotalSalesLine array[4] of SalesLine, var TotalSalesLineLCY: array[4] of Record "Sales Line",var ProfitPct array[4] of Decimal, var ProfitLCY array[4] of decimal)**
        UpdateHeaderInfo(2, TempVATAmountLine2);
                                                                    **<======== RefreshOnAfterGetRecordOnAfterUpdateHeaderInfo(var Rec (Salesheader), var TotalSalesLine array[4] of SalesLine, var TotalSalesLineLCY: array[4] of Record "Sales Line", var ProfitPct array[4] of Decimal, var ProfitLCY array[4] of decimal)**
    end;

**Comment by obermeiersinghammer** [comment]
Alternative:
Expose 
        ProfitLCY: array[3] of Decimal;
        ProfitPct: array[3] of Decimal;
as protected var

maybe then it is possible to use the existing publishers:

OnUpdateHeaderInfoOnBeforeSetAmount

and

OnAfterUpdateHeaderInfo(TotalSalesLineLCY, IndexNo);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53649.
