### ISSUE TITLE
[Event Request] table 4815 "Intrastat Report Sales Head."

### ISSUE THREAD

**Issue by RaKuNbg** [microsoft/ALAppExtensions#22228]
Could you please move the code from the OnAfterValidateTriggers to a function and add an IntegrationEvent with a "IsHandled"-Flag at the beginning of the function so that we can exit the functionality.

Code example:

    fields
    {
        modify("Sell-to Customer No.")
        {
            trigger OnAfterValidate()
            begin
                UpdateIntrastatFields();
            end;
        }
        modify("Bill-to Customer No.")
        {
            trigger OnAfterValidate()
            begin
                UpdateIntrastatFields();
            end;
        }
    }

    local procedure UpdateIntrastatFields()
    var
        IsHandled: Boolean;
    begin
        OnBeforeUpdateIntrastatFields(Rec, IsHandled);
        if IsHandled then
            exit;
        
        if IntrastatReportSetup.Get() then
            case IntrastatReportSetup."VAT No. Based On" of
                IntrastatReportSetup."VAT No. Based On"::"Sell-to VAT":
                    UpdateIntrastatFields("Sell-to Customer No.");
                IntrastatReportSetup."VAT No. Based On"::"Bill-to VAT":
                    UpdateIntrastatFields("Bill-to Customer No.");
            end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateIntrastatFields(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean);
    begin
    end;
}    
    
    
Same for
tableextension 4816 "Intrastat Report Serv. Head."
tableextension 4817 "Intrastat Report Purch. Head."

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11606.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 59136.
