### ISSUE TITLE
[Change Request] table 5644 "FA Posting Type" - procedure InsertRec

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#22236]
Hello, can you please change the procedure InsertRec as global?

```
    procedure InsertRec(EntryNo: Integer; FAPostingTypeNo: Integer; FAPostingTypeName: Text[80])
    begin
        "Entry No." := EntryNo;
        "FA Posting Type No." := FAPostingTypeNo;
        "FA Posting Type Name" := CopyStr(FAPostingTypeName, 1, MaxStrLen("FA Posting Type Name"));
        Insert();
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10134.
