### ISSUE TITLE
[Event Request] table 5640 "Main Asset Component" - OnBeforeDelete

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#22234]
Hello, for an table extension in table 5640 "Main Asset Component" we need an new Event OnBeforeDelete.

```
    trigger OnDelete()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeDelete(Rec, IsHandled);
        If IsHandled then
            exit;
        LockFixedAsset();
        if "FA No." <> '' then begin
            FA.Get("FA No.");
            UpdateMainAsset(FA, 0);
        end;
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDelete(var MainAssetComponent: Record "Main Asset Component"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53649.
