### ISSUE TITLE
[Enum Request]  table 5600 "Fixed Asset" - field(12; "Main Asset/Component"; Option)

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#22232]
Hello, can you please transform the Option field field(12; "Main Asset/Component"; Option) in table 5600 "Fixed Asset" to an Enum. We would like to extend this with custom values.

```
        field(12; "Main Asset/Component"; Option)
        {
            Caption = 'Main Asset/Component';
            Editable = false;
            OptionCaption = ' ,Main Asset,Component';
            OptionMembers = " ","Main Asset",Component;
        }
```

The Option is also used in table 5612 "FA Depreciation Book".

```
field(56; "Main Asset/Component"; Option)
        {
            Caption = 'Main Asset/Component';
            Editable = false;
            OptionCaption = ' ,Main Asset,Component';
            OptionMembers = " ","Main Asset",Component;
        }
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53910.
