### ISSUE TITLE
[Event Request] Page 344 Event Required on "FindRecords" Function

### ISSUE THREAD

**Issue by sainath654** [microsoft/ALAppExtensions#2223]
Hello Everyone,

Need a Integration Event on Page344 (OnBeforeFindRecords) for the function FindRecords

**New Integration Event:**
LOCAL [IntegrationEvent] **OnBeforeFindRecords**(VAR SkipWindowDialog : Boolean)

**Event Call:**
**When Funtion Starts**
OnBeforeFindRecords(HideDialogMsg);//New Event Call
IF NOT HideDialogMsg THEN //New Code Needed
  Window.OPEN(Text002);
RESET;
DELETEALL;

**Before Function Ends**
IF NOT HideDialogMsg THEN BEGIN //New Code Needed
IF UpdateForm THEN
  UpdateFormAfterFindRecords;
Window.CLOSE;
END; //New Code Needed

Thank you.

**Comment by StanPesotskiy** [comment]
Why do you want to make
```
IF UpdateForm THEN
  UpdateFormAfterFindRecords;
```
dependant on `HideDialogMsg`?

I would expect just:
```
IF NOT HideDialogMsg THEN
  Window.CLOSE;
```
