### ISSUE TITLE
[Change Request] table 5645 "FA Date Type" - procedure InsertRec

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#22237]
Hello, can you please change the procedure InsertRec in table table 5645 "FA Date Type" as global?

```
    procedure InsertRec(FAEntryNo: Integer; FADateTypeNo: Integer; FADateTypeName: Text[80])
    begin
        "Entry No." := FAEntryNo;
        "FA Date Type No." := FADateTypeNo;
        "FA Date Type Name" := CopyStr(FADateTypeName, 1, MaxStrLen("FA Date Type Name"));
        Insert();
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10134.
