### ISSUE TITLE
[EventRequest] Codeunit 1606 PEPPOL Management OnAfterGetAccountingCustomerPartyInfoByFormat

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/ALAppExtensions#22247]
Please add the event in the procedure GetAccountingCustomerPartyInfoByFormat

OnAfterGetAccountingCustomerPartyInfoByFormat(SalesHeader: Record "Sales Header"; var CustomerEndpointID: Text; var CustomerSchemeID: Text; var CustomerPartyIdentificationID: Text; var CustomerPartyIDSchemeID: Text; var CustomerName: Text; IsBISBilling: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53649.
