### ISSUE TITLE
Is there any possibility to publish directly to live environment  instead of sandbox ? 

### ISSUE THREAD

**Issue by TharunMuthu** [microsoft/ALAppExtensions#2224]
Hi,
1. Is there any possibility to publish directly to live environment  instead of sandbox ? 
if yes then please guide 
2. Is there any possibility debug in live environment  ?
regards,
Muthu

**Comment by frivadulla** [comment]
if you use AL Extension in Visual Studio, then config correctly launch.json. with AL:Go you can determine where do you want to deploy the extension.

**Comment by ikoletic** [comment]
This issue is a question. Please submit your questions on [business central community ](https://community.dynamics.com/business/f/758) or on [BC development yammer groups](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035).
