### ISSUE TITLE
[Event request] report 5753 "Get Source Documents" - OnAfterProcessDocumentLine

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#22248]
In #114, the **Service Line** dataitem was ignored.

As the Get Source Documents report can also be used for service orders,  please also raise the event **OnAfterProcessDocumentLine** in the OnPostDataItem trigger of the Service Line dataitem, similar to Sales Line / Purchase Line / Transfer Line.

Optionally, it might be relevant to calls the UpdateReceiptHeaderStatus / CheckFillQtyToHandle as well, similar to Sales Line / Purchase Line / Transfer Line. (not needed for me)

```
trigger OnPostDataItem()
begin
   // <<< optional
    if OneHeaderCreated or WhseHeaderCreated then begin
        UpdateReceiptHeaderStatus();
        CheckFillQtyToHandle();
    end;
   // >>> optional

    OnAfterProcessDocumentLine(WhseShptHeader, "Warehouse Request", LineCreated, WhseReceiptHeader);  // <<< required 
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53649.
