### ISSUE TITLE
[Event Request] Page 38 Item Ledger Entries - OnBeforeGetCaption

### ISSUE THREAD

**Issue by mvendert** [microsoft/ALAppExtensions#22242]
We want to be able to extend on the GetCaption functionality of Page 38 Item Ledger Entries to navigate to other entities and show this fact in the title. An OnBeforeGetCaption Event, with IsHandled parameter is requested.
Additional remark: Description variable need not te be limited to 100 characters but is acceptable.

```
    local procedure GetCaption(): Text
    var
        GLSetup: Record "General Ledger Setup";
        ObjTransl: Record "Object Translation";
        Item: Record Item;
        ProdOrder: Record "Production Order";
        Cust: Record Customer;
        Vend: Record Vendor;
        Dimension: Record Dimension;
        DimValue: Record "Dimension Value";
        SourceTableName: Text;
        SourceFilter: Text;
        Description: Text[100];
    begin
        Description := '';

        // MVE
        IsHandled := false;
        OnBeforeGetCaption(Rec, Description, IsHandled);        
        if IsHandled then
            exit(Description);
        // *
        . . .

    [IntegrationEvent(false,false)]
    local procedure OnBeforeGetCaption(ILE: Record "Item Ledger Entry"; var Description: Text[100]; var IsHandled:boolean);
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53649.
