### ISSUE TITLE
Report 2 General Journal - Test Add function with event into conditions

### ISSUE THREAD

**Issue by LubomirUrx** [microsoft/ALAppExtensions#22254]
Function TestFixedAsset :
Could you replace conditions (it appears in this function on two places)

`if "FA Posting Type" in
    ["FA Posting Type"::"Acquisition Cost", "FA Posting Type"::Disposal, "FA Posting Type"::Maintenance]`

with conditions 

`if IsAcquisitionCost() or ("FA Posting Type" in ["FA Posting Type"::Disposal, "FA Posting Type"::Maintenance]`

where IsAquisitionCost() is the function from table GenJournalLine.
The result will be the same but we can use the Event from function IsAquisitionCost().

In case if it is not possible to use function from GenJournalLine table, could you create similar function with event into this report?

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53798.
