### ISSUE TITLE
Table 38 Purchase Header - OnBeforeValidatePostingDate - New Event

### ISSUE THREAD

**Issue by DanielSmutek** [microsoft/ALAppExtensions#22252]
Please add new Event to Table 38, **OnBeforeValidatePostingDate**

        field(20; "Posting Date"; Date)
        {
            Caption = 'Posting Date';

            trigger OnValidate()
            var
                SkipJobCurrFactorUpdate: Boolean;
            begin
                // New Event Code
                IsHandled := false;
                OnBeforeValidatePostingDate(Rec, xRec, CurrFieldNo, IsHandled);
                if IsHandled then
                    exit;
                // New Event Code

                TestField("Posting Date");
                TestNoSeriesDate(

    [IntegrationEvent(false, false)]
    local procedure OnBeforeValidatePostingDate(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader: Record "Purchase Header"; CurrentFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53765.
