### ISSUE TITLE
Page 253 "Sales Journal" procedure SetControlVisibility on wrong "Allow Multiple Posting Groups" table

### ISSUE THREAD

**Issue by laurbag** [microsoft/ALAppExtensions#22251]
Hello,
In NextMajor BC22 (22.0.53441.0) I found an issue in the procedure SetControlVisibility used in "Sales Journal" page:
In that case the table used to verify "Allow Multiple Posting Groups" should be table 311 "Sales & Receivables Setup" and not table 312 "Purchases & Payables Setup".

![image](https://user-images.githubusercontent.com/79576552/221134262-56b00f95-4e35-48fa-9493-d6b8d0a3e92d.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53886.
