### ISSUE TITLE
[Event Request] Table 77 Report Selections: OnBeforeGetEmailBodyCustomText

### ISSUE THREAD

**Issue by Kowa63** [microsoft/ALAppExtensions#2225]
Function: GetEmailBodyCustomText
Publisher: OnBeforeGetEmailBodyCustomText
![grafik](https://user-images.githubusercontent.com/16236672/56881660-6c213b80-6a61-11e9-96d8-c9fa1c975a07.png)
![grafik](https://user-images.githubusercontent.com/16236672/56881668-704d5900-6a61-11e9-8792-cf6c6606f623.png)
Parameters
![grafik](https://user-images.githubusercontent.com/16236672/56881669-73e0e000-6a61-11e9-9f65-acaf4523c994.png)

**Comment by GeekEding** [comment]
Hi @jobulsin ,
this one is still missing too.
