### ISSUE TITLE
Event Request: codeunit 1002 "Job Create-Invoice" OnBeforeCheckCurrencyCreateSalesLine

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#22260]
Please could we have the following event added:
We need this to allow us to have multiple currencies on a Job, at Task level. Thanks

codeunit 1002 "Job Create-Invoice"
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckCurrencyCreateSalesLine(var Job: Record Job; var SalesHeader: Record "Sales Header" ;var SalesLine: Record "Sales Line"; var JobPlanningLine: Record "Job Planning Line";var JobInvCurrency: boolean; var IsHandled: Boolean)
    begin
    end;

    local procedure CreateSalesLine(var JobPlanningLine: Record "Job Planning Line")
    var
        Job: Record Job;
        Factor: Integer;
        IsHandled: Boolean;
    begin
        OnBeforeCreateSalesLine(JobPlanningLine, SalesHeader, SalesHeader2, JobInvCurrency);

        Factor := 1;
        if SalesHeader2."Document Type" = SalesHeader2."Document Type"::"Credit Memo" then
            Factor := -1;
        TestTransferred(JobPlanningLine);
        JobPlanningLine.TestField("Planning Date");
        Job.Get(JobPlanningLine."Job No.");
        Clear(SalesLine);
        SalesLine."Document Type" := SalesHeader2."Document Type";
        SalesLine."Document No." := SalesHeader."No.";

        IsHandled := false;
        OnBeforeCheckCurrencyCreateSalesLine(Job,SalesHeader,SalesLine,JobPlanningLine,JobInvCurrency,IsHandled);
        if not IsHandled then
            if (not JobInvCurrency) and (JobPlanningLine.Type <> JobPlanningLine.Type::Text) then begin
                SalesHeader.TestField("Currency Code", JobPlanningLine."Currency Code");
                if (Job."Currency Code" <> '') and (JobPlanningLine."Currency Factor" <> SalesHeader."Currency Factor") then
                    if Confirm(Text011) then begin
                        JobPlanningLine.Validate("Currency Factor", SalesHeader."Currency Factor");
                        JobPlanningLine.Modify();
                    end else
                        Error(Text001);
                SalesHeader.TestField("Currency Code", Job."Currency Code");
            end;
        if JobPlanningLine.Type = JobPlanningLine.Type::Text then
            SalesLine.Validate(Type, SalesLine.Type::" ");

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53765.
