### ISSUE TITLE
[Change Request]  codeunit 1373 "Batch Posting Print Mgt." - procedure PrintDocument

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#22269]
Hello, cou you please change the procedure PrintDocument as a global procedure?

```
local procedure PrintDocument(ReportUsage: Enum "Report Selection Usage"; RecVar: Variant; PrintViaJobQueue: Boolean; ReportOutputType: Option)
    var
        ReportSelections: Record "Report Selections";
        IsHandled: Boolean;
    begin
        IsHandled := false;
```

**Comment by AlexanderYakunin** [comment]
Already done for v.22

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10134.
