### ISSUE TITLE
[Event Request] - Codeunit 249 "VAT Registration Log Mgt." - OnBeforeUpdateRecordFromVATRegLog

### ISSUE THREAD

**Issue by nbuko** [microsoft/ALAppExtensions#22278]
Hello, could you please add the following event to the codeunit 249 "VAT Registration Log Mgt." into the procedure UpdateRecordFromVATRegLog?

Event:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateRecordFromVATRegLog(var RecordRef: RecordRef; RecordVariant: Variant; VATRegistrationLog: Record "VAT Registration Log"; var IsHandled: Boolean)
begin
end;
```

Event-Call:
```
procedure UpdateRecordFromVATRegLog(var RecordRef: RecordRef; RecordVariant: Variant; VATRegistrationLog: Record "VAT Registration Log")
//NEW START
var        
    IsHandled: Boolean;
    //NEW END
begin
    //NEW START
    OnBeforeUpdateRecordFromVATRegLog(RecordRef, RecordVariant, VATRegistrationLog, IsHandled);
    if IsHandled then
        exit;
    //NEW END
    if GuiAllowed() then begin
        ...
    end;
end;
```

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 53798.
