### ISSUE TITLE
[Protected Procedure Request] table 1382 "Item Templ." - ValidateItemField

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#22272]
We would like to use procedure ValidateItemField in our fields in a table extension of table "Item Templ."
Can you set the local property to protected?

Old code:
local procedure ValidateItemField(FieldId: Integer)

New code:
protected procedure ValidateItemField(FieldId: Integer)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10134.
