### ISSUE TITLE
codeunit 5895 "Inventory Adjustment"

### ISSUE THREAD

**Issue by GyAMultisoft** [microsoft/ALAppExtensions#22277]
Inventory Adjustment sometimes (randomly) turns into an infinite cycle. 
It stuck at line "until InbndValueEntry.Next() = 0", it cannot find the next record somehow. There are 2 records meet the filter criteria. 
There is an easy fix, just needed to add a line "if InbndValueEntry.FindSet() then" before the repeat-until cycle, so it gets the first record and can step forward.

The problematic procedure (with fix:) 

  local procedure CalcInbndDocOldCost(InbndValueEntry: Record "Value Entry"; var CostElementBuf: Record "Cost Element Buffer")
    begin
        CostElementBuf.DeleteAll();
        InbndValueEntry.SetCurrentKey("Item Ledger Entry No.", "Document No.");
        InbndValueEntry.SetRange("Item Ledger Entry No.", InbndValueEntry."Item Ledger Entry No.");
        InbndValueEntry.SetRange("Document No.", InbndValueEntry."Document No.");
        InbndValueEntry.SetRange("Document Line No.", InbndValueEntry."Document Line No.");
        if InbndValueEntry.FindSet() then `//this line is added`
            with CostElementBuf do
                repeat
                    if (InbndValueEntry."Entry Type" = InbndValueEntry."Entry Type"::"Direct Cost") and
                       (InbndValueEntry."Item Charge No." = '')
                    then begin
                        if TempInvtAdjmtBuf.Get(InbndValueEntry."Entry No.") then
                            InbndValueEntry.AddCost(TempInvtAdjmtBuf);
                        if InbndValueEntry."Expected Cost" then
                            AddExpectedCostElement("Cost Entry Type"::"Direct Cost", "Cost Variance Type"::" ", InbndValueEntry."Cost Amount (Expected)", InbndValueEntry."Cost Amount (Expected) (ACY)")
                        else begin
                            AddActualCostElement("Cost Entry Type"::"Direct Cost", "Cost Variance Type"::" ", InbndValueEntry."Cost Amount (Actual)", InbndValueEntry."Cost Amount (Actual) (ACY)");
                            if InbndValueEntry."Invoiced Quantity" <> 0 then begin
                                "Invoiced Quantity" := "Invoiced Quantity" + InbndValueEntry."Invoiced Quantity";
                                if not Modify then
                                    Insert();
                            end;
                        end;
                    end;
                until InbndValueEntry.Next() = 0;
    end;

Would you please verify and validate the modification?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10644.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56140.
