### ISSUE TITLE
Codeunit 427 ICInboxOutboxMgt - OutboxPurchHdrToInbox

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#2228]
Please Insert new Publisher in function OutboxPurchHdrToInbox

NEW - OnBeforeInsert(....)

ICInboxSalesHdr.INSERT;

NEW - OnAfterInsert(....)

**Comment by AlexanderYakunin** [comment]
Already here:

  OnBeforeICInboxSalesHeaderInsert(ICInboxSalesHeader,ICOutboxPurchHeader);
  INSERT;
  OnAfterICInboxSalesHeaderInsert(ICInboxSalesHeader,ICOutboxPurchHeader);
