### ISSUE TITLE
Codeunit 427 ICInboxOutboxMgt - OutboxSalesHdrToInbox

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#2229]
Please Insert new Publisher in function OutboxSalesHdrToInbox
NEW - OnBeforeInsert(....)

ICInboxPurchHdr.INSERT;

NEW - OnAfterInsert(....)

**Comment by AlexanderYakunin** [comment]
Already here, please use latest code from bcinsider

  OnBeforeICInboxPurchHeaderInsert(ICInboxPurchHeader,ICOutboxSalesHeader);
  INSERT;
  OnAfterICInboxPurchHeaderInsert(ICInboxPurchHeader,ICOutboxSalesHeader);
