### ISSUE TITLE
[Event Request] table 5972 "Contract/Service Discount" - OnBeforeVerifyContractOpen

### ISSUE THREAD

**Issue by alapenas** [microsoft/ALAppExtensions#22295]
Hello, would it be possible to add OnBeforeVerifyContractOpen event to table 5972 "Contract/Service Discount", like this: 
  
 ```al 
 local procedure VerifyContractOpen() 
 ... 
           ServiceContractHeader: Record "Service Contract Header";
          IsHandled: Boolean;
      begin
          IsHandled := false;
>         OnBeforeVerifyContractOpen(Rec, IsHandled); //New Event
          if IsHandled then
              exit;
  
          ServiceContractHeader.Get("Contract Type", "Contract No."); 
 ``` 
 ```al 
   
      [IntegrationEvent(false, false)]
      local procedure OnBeforeVerifyContractOpen(var ContractServiceDiscount: Record "Contract/Service Discount"; var IsHandled: Boolean) 
      begin
      end; 
 ```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 54020.
