### ISSUE TITLE
Codeunit 427 ICInboxOutboxMgt - OutboxSalesLineToInbox

### ISSUE THREAD

**Issue by ThorstenEngelsGOB** [microsoft/ALAppExtensions#2230]
Please Insert new Publisher in function OutboxSalesLineToInbox
NEW - OnBeforeInsert(....)

ICInboxPurchLine.INSERT;

NEW - OnAfterInsert(....)

**Comment by AlexanderYakunin** [comment]
Already here

  OnBeforeICInboxPurchLineInsert(ICInboxPurchLine,ICOutboxSalesLine);
  INSERT;
  OnAfterICInboxPurchLineInsert(ICInboxPurchLine,ICOutboxSalesLine);
