### ISSUE TITLE
[Event Request] report 698 "Get Sales Orders" - OnPostDataItemOnBeforeLineCount

### ISSUE THREAD

**Issue by alapenas** [microsoft/ALAppExtensions#22310]
Hello, would it be possible to add OnPostDataItemOnBeforeLineCount event to report 698 "Get Sales Orders", like this: 
  
 ```al 
 trigger OnPostDataItem() 
 ... 
               var
                  IsHandled: Boolean;
              begin
                  IsHandled := false;
>                 OnPostDataItemOnBeforeLineCount(LineCount, IsHandled); //New Event
                  if IsHandled then
                      exit;
                  if not HideDialog then
                      if LineCount = 0 then 
 ``` 
 ```al 
   
      [IntegrationEvent(false, false)]
      local procedure OnPostDataItemOnBeforeLineCount(LineCount: Integer; var IsHandled: Boolean) 
      begin
      end; 
 ```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10818.
