### ISSUE TITLE
[Event Request] table 83 "Item Journal Line" - OnBeforeSigned

### ISSUE THREAD

**Issue by alapenas** [microsoft/ALAppExtensions#22315]
Hello, would it be possible to add OnBeforeSigned event to table 83 "Item Journal Line", like this: 
  
 ```al 
 procedure Signed(Value: Decimal): Decimal 
 ... 
       var
          IsHandled: Boolean;
      begin
          IsHandled := false;
>         OnBeforeSigned(Rec, IsHandled, Value);  //New Event
          if IsHandled then
              exit(Value);
          case "Entry Type" of
              "Entry Type"::Purchase, 
 ``` 
 ```al 
   
      [IntegrationEvent(false, false)]
      local procedure OnBeforeSigned(ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean; var Value: Decimal)  
      begin
      end; 
 ```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 54020.
