### ISSUE TITLE
[Event Request] codeunit 99000835 "Item Jnl. Line-Reserve" - OnBeforeDeleteLine

### ISSUE THREAD

**Issue by alapenas** [microsoft/ALAppExtensions#22312]
Hello, would it be possible to add OnBeforeDeleteLine event to codeunit 99000835 "Item Jnl. Line-Reserve", like this: 
  
 ```al 
     procedure DeleteLine(var ItemJnlLine: Record "Item Journal Line") 
 ... 
       begin
          if Blocked then
              exit;
  
>         OnBeforeDeleteLine(ItemJnlLine); //New Event
  
          with ItemJnlLine do begin
              ReservMgt.SetReservSource(ItemJnlLine);
              if DeleteItemTracking then 
 ``` 
 ```al 
   
      [IntegrationEvent(false, false)]
      local procedure OnBeforeDeleteLine(var ItemJnlLine: Record "Item Journal Line") 
      begin
      end; 
 ```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 54020.
