### ISSUE TITLE
[Event Request] Table 77 Report Selections: OnBeforeGetEmailBodyVendorText

### ISSUE THREAD

**Issue by Kowa63** [microsoft/ALAppExtensions#2232]
Function: GetEmailBodyVendor
Publisher: OnBeforeGetEmailBodyVendorText
![grafik](https://user-images.githubusercontent.com/16236672/56901073-9130a100-6a97-11e9-83b6-6e00a325fa75.png)
![grafik](https://user-images.githubusercontent.com/16236672/56901084-942b9180-6a97-11e9-990c-05a1e23d5f0c.png)
Parameters
![grafik](https://user-images.githubusercontent.com/16236672/56901087-98f04580-6a97-11e9-9ced-c122aecf6802.png)

**Comment by GeekEding** [comment]
Hi @jobulsin ,
this one is still missing.

**Comment by lv-janpieter** [comment]
This one is indeed still missing, I don't think Microsoft is monitoring this subject. I will create a new issue for this.
