### ISSUE TITLE
[Event Request] codeunit 221 "Resource-Find Price" - OnBeforeOnRun

### ISSUE THREAD

**Issue by alapenas** [microsoft/ALAppExtensions#22331]
Hello, would it be possible to add OnBeforeOnRun event to codeunit 221 "Resource-Find Price", like this: 
  
 ```al 
 trigger OnRun() 
 ... 
       trigger OnRun()
      var
          IsHandled: Boolean;
      begin
>         OnBeforeOnRun(ResPrice, Rec, IsHandled); //New Event
          if IsHandled then
              exit;
          ResPrice.Copy(Rec);
          with ResPrice do 
 ``` 
 ```al 
   
      [IntegrationEvent(false, false)]
      local procedure OnBeforeOnRun(var ResPrice: Record "Resource Price"; var Rec: Record "Resource Price"; var IsHandled: Boolean)
      begin
      end; 
 ```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 54020.
