### ISSUE TITLE
Event Request Codeunit 12 Gen. Jnl.-Post Line - PrepareTempCustLedgEntry

### ISSUE THREAD

**Issue by maheshroyal34** [microsoft/ALAppExtensions#2233]
Event - OnBeforeSkipPositivetestField() , OnAfterSkipPositivetestField()

Code:-
>>New Code Start
OnBeforeSkipPositivetestField(Var GenJnlLine:” Gen. Journal Line”;Var IsHandled: Boolean)
<<New Code End

IF NOT IsHandled THEN >>New Code
  OldCustLedgEntry.TESTFIELD(Positive,NOT NewCVLedgEntryBuf.Positive);

>>New Code Start
OnAfterSkipPositivetestField (Var GenJnlLine:” Gen. Journal Line”;Var IsHandled: Boolean) 
<<New Code End

**Comment by AlexanderYakunin** [comment]
Why do you need to skip it?

**Comment by maheshroyal34** [comment]
The above requested event should be in the below location in Codeunit - 12 -Gen. jnl. -Post Line - Function - PrepareTempCustledgEntry().

![image](https://user-images.githubusercontent.com/49781885/57709335-714cd000-7688-11e9-9a80-eb1bbeecc6d7.png)


The Second Event is not required OnAfterSkipPositivetestField().

one of customer added an check before the line of code, so here we need an event to extend and check.
