### ISSUE TITLE
Event Request Codeunit 90 Purch.-Post :- ReleasePurchDocument

### ISSUE THREAD

**Issue by maheshroyal34** [microsoft/ALAppExtensions#2234]
Events - OnBeforeModifyPurchHeaderStatus(), OnAfterModifyPurchHeaderStatus() 

>>New Code Start
OnBeforeModifyPurchHeaderStatus (VAR PurchHeader : Record "Purchase Header";Var IsHandled: Boolean)
<<New Code End

IF NOT IsHandled THEN >>New Code
  Status := Status::Released;

>>New Code Start
OnAfterModifyPurchHeaderStatus (VAR PurchHeader : Record "Purchase Header";Var IsHandled: Boolean) 
<<New Code End

**Comment by AlexanderYakunin** [comment]
Please explain purpose of new events and provide their exact location in the code.

**Comment by maheshroyal34** [comment]
The above requested event should be in the below location in Codeunit - 90 - Purch. Post - Function - ReleasePurchDocument(). 

![image](https://user-images.githubusercontent.com/49781885/57707978-2c279e80-7686-11e9-825d-0758dd991e02.png)


one of the customer added some check before modify the status to Released, so here we required an event.


The second event - OnAfterModifyPurchHeaderStatus() is not required
