### ISSUE TITLE
Event Request Codeunit 10120 Bank Rec.-Post :- PostAdjustmentToGL

### ISSUE THREAD

**Issue by maheshroyal34** [microsoft/ALAppExtensions#2235]
Event - OnBeforeModifyCurrencyFactor(),OnAftermodifyCurrencyFactor() 
>>New Code Start
OnBeforeModifyCurrencyFactor (Var BankRecLine2: Record "Bank Rec. Line";Var GenJnlLine : Record Gen. journal line;Var IsHandled: Boolean)
<<New Code End

IF NOT IsHandled THEN >>New Code
  GenJnlLine."Currency Factor" := "Currency Factor";
	
>>New Code Start
OnAftermodifyCurrencyFactor(Var BankRecLine2 : Record "Bank Rec. Line"; Var GenJnlLine : Record Gen. journal line;Var IsHandled: Boolean) 
<<New Code End

**Comment by AlexanderYakunin** [comment]
Please explain what you are going to do with this event? Events should not alter application behavior if not used, but you want to assign Currency Factor is IsHandled = FALSE? This is wrong pattern. Second evewnt does not make sense with Handled pattern.

**Comment by maheshroyal34** [comment]
Hello,

This is customization made by one the customer, Where the "Currency Factor"is calculating with some other value(as not the actual code below), So now moving to BC we need an event to update that part with customized value

GenJnlLine."Currency Factor" := "Currency Factor";

**Comment by maheshroyal34** [comment]
Yes, The second event is not required.

**Comment by AlexanderYakunin** [comment]
Are you working with OnPrem customer?

**Comment by maheshroyal34** [comment]
We are migrating one of the customer DB from 2009 to BC On Prem.

**Comment by AlexanderYakunin** [comment]
Sorry, this is not an intended way of using events. We do not provide events for individual customers.
