### ISSUE TITLE
[Event Request] Page 9249 - "Analysis by Dimensions Matrix" - OnOpenPageAccountSourceElseCase

### ISSUE THREAD

**Issue by laurbag** [microsoft/ALAppExtensions#22369]
Hello,
We are extending "Account Source" (from Enum "Analysis Account Source") and we would like to use it in the OnOpenPage() trigger from the page 9249 - "Analysis by Dimension Matrix".
Would it be possible to manage a case statement on AnalysisView."Account Source" in order to fill LineDimCode according to our extended enum value?

**Existing**
````
        if (LineDimCode = '') and (ColumnDimCode = '') then begin
            if GLAccountSource then
                LineDimCode := GLAcc.TableCaption
            else
                LineDimCode := CashFlowForecast.TableCaption();
            ColumnDimCode := Text000;
        end;
````
**New Event**
````
    [IntegrationEvent(false, false)]
    local procedure OnOpenPageAccountSourceElseCase(AnalysisView: Record "Analysis View"; var LineDimCode: Text[30])
    begin
    end;
````
**Suggestion**
````
        if (LineDimCode = '') and (ColumnDimCode = '') then begin
            case AnalysisView."Account Source" of
                AnalysisView."Account Source"::"G/L Account":
                    LineDimCode := GLAcc.TableCaption;
                AnalysisView."Account Source"::"Cash Flow Account":
                    LineDimCode := CashFlowForecast.TableCaption;
                else
                    OnOpenPageAccountSourceElseCase(AnalysisView, LineDimCode);
            end;
            ColumnDimCode := Text000;
        end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11137.
