### ISSUE TITLE
[Global Procedure] table 7321 "Warehouse Shipment Line" - CalcBaseQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#22416]
We have two extension fields on table "Warehouse Shipment Line":
"Requested Qty. to Pick A109"
"Req. Qty. to Pick (Base) A109"
and would like to use code in the Validate trigger of one of them
:
"Req. Qty. to Pick (Base) A109" := CalcBaseQty("Requested Qty. to Pick A109", FieldCaption("Requested Qty. to Pick A109"), FieldCaption("Req. Qty. to Pick (Base) A109"));

but allas procedure CalcBaseQty is set as local. Could you make it global?

And if you want some extra work, search for 'local procedure CalcBaseQty' in the Base source and set them all to global.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10134.
