### ISSUE TITLE
[Request External] codeunit 386 "Reverse Payment Rec. Journal" - ErrorIfEntryIsNotReversable

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#22419]
We're creating a custom copy of the Customer / Vendor Ledger entries pages, including all actions. However, we can't copy the 'Reverse Transaction' action, due to restricted access to codeunit 386 "Reverse Payment Rec. Journal"

` Access = Internal;`

Can you please make the codeunit public, or at least expose `ErrorIfEntryIsNotReversable`?

Sample code from `page 29 "Vendor Ledger Entries"`

```
action(ReverseTransaction)
                {
                    ApplicationArea = Basic, Suite;
                    Caption = 'Reverse Transaction';
                    Ellipsis = true;
                    Image = ReverseRegister;
                    Scope = Repeater;
                    ToolTip = 'Reverse an erroneous vendor ledger entry.';

                    trigger OnAction()
                    var
                        ReversalEntry: Record "Reversal Entry";
                        ReversePaymentRec: Codeunit "Reverse Payment Rec. Journal";
                    begin
                        ReversePaymentRec.ErrorIfEntryIsNotReversable(Rec);
                        ReversalEntry.ReverseTransaction("Transaction No.");
                    end;
                }
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10134.
