### ISSUE TITLE
[Global Function] GetWord - Codeunit 5054 WordManagement

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#2243]
_Copy of #1007 -> Request for 'Global' function (to allow at least OnPrem with customized AL base app) instead of 'External'_ 

In the latest BCoP CU3 release, a fix is shipped to avoid pending Winword.exe sessions. The solution is using a new WordApplicationHandler codeunit, subscribing to events raised in codeunit 5054 WordManagment. 5 new functions are added, most of them external (Activate, IsActive, ...)

In our solution, we've heavily customized the WordManagement codeunits (in a separate object). However, we'd like to apply the same pattern / fix, using the new WordApplicationHandler codeunit. Therefore we re-use the new functions (Activate, IsActive, ...) from codeunit 5054. However, function GetWord is not global.

Sample code of our WordManagement codeunit (CreateWordAttachment function)

```
WordManagement.Activate(WordApplicationHandler,50000);
WordManagement.GetWord(WordApplication);  // GetWord is not Global
...
WordManagement.Deactivate(50000);
```
Can you please set 'GetWord' at least to Global, untill a final solution is available?

Still struggling with the original issue about how to extend Cu5054 and thus applying the standard pattern Activate (=External) / GetWord (=Local) / ... DoYourThing with Word ... / Deactivate (=External) without duplicating all code from Cu5054 / Cu5068.

**Comment by fvet** [comment]
@AlexanderYakunin, any status update on the above, setting 'GetWord' to global? 
I would like to avoid having to merge our custom WordManagement module to the standard BC one and request 100+ events :(

PS: Seems like COD 5054 contains an IntegrationEvent OnGetWord(VAR NewWordApplication : DotNet "Microsoft.Office.Interop.Word.ApplicationClass" RUNONCLIENT;VAR IsFound : Boolean), that allows the use DotNet parameters?

**Comment by AlexanderYakunin** [comment]
This is OnPrem feature, it will not work for cloud.

**Comment by fvet** [comment]
No longer needed ...
