### ISSUE TITLE
[follow-up] Codeunit 90 "Purch.-Post" - event OnBeforeCheckItemQuantityPurchCredit

### ISSUE THREAD

**Issue by alinat2022** [microsoft/ALAppExtensions#22434]
Hello,

Can you please tell us what is the status of this request: https://github.com/microsoft/ALAppExtensions/issues/19008 ?
In BC 21.4.52563.53143, it is still not implemented.

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11007.
