### ISSUE TITLE
Codeunit 13 "Gen. Jnl.-Post Batch" - increase the length of the array variable NoSeriesMgt2

### ISSUE THREAD

**Issue by AndreaDSC** [microsoft/ALAppExtensions#22446]
One of our customer  has about 50 stores, we receive store sales data and they are deposited in batches.
Each store must have its own numbering, consequently there are about 50 different Posting No. Series in the batch.
Previously in NAV, it was enough to extend the NoSeriesMgt2 variable from 10 to 100.
Now in BC it is not possible to do this and it is not even possible to intervene in the Check Documents function.

Is it possibile to increase the lenght of the array ? also because we do not understand this limitation

Without this "modification" we would have to get around the problem either by asking the customer to deposit the data in one batch for each shop, which is unacceptable for the customer who would have to register 50 batches compared to the only batch he had in NAV, or to develop a registration procedure which register 10 numbers at a time (very ugly, uncomfortable and non-performing).

Thank you very much.

 local procedure CheckDocumentNo(var GenJnlLine2: Record "Gen. Journal Line")
    begin
        with GenJnlLine2 do
            if "Posting No. Series" = '' then
                "Posting No. Series" := GenJnlBatch."No. Series"
            else
                if not EmptyLine() then
                    if ShouldSetDocNoToLastPosted(GenJnlLine2) then
                        "Document No." := LastPostedDocNo
                    else begin
                        if not TempNoSeries.Get("Posting No. Series") then begin
                            NoOfPostingNoSeries := NoOfPostingNoSeries + 1;
                            if NoOfPostingNoSeries > ArrayLen(NoSeriesMgt2) then
                                Error(
                                  Text025,
                                  ArrayLen(NoSeriesMgt2));
                            TempNoSeries.Code := "Posting No. Series";
                            TempNoSeries.Description := Format(NoOfPostingNoSeries);
                            TempNoSeries.Insert();
                        end;
                        LastDocNo := "Document No.";
                        Evaluate(PostingNoSeriesNo, TempNoSeries.Description);
                        "Document No." :=
                          NoSeriesMgt2[PostingNoSeriesNo].GetNextNo("Posting No. Series", "Posting Date", true);
                        LastPostedDocNo := "Document No.";
                    end;
        OnAfterCheckDocumentNo(GenJnlLine2, LastDocNo, LastPostedDocNo);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10720.
