### ISSUE TITLE
[Events Request] Codeunit 370 "Bank Acc. Reconciliation Post" procedure PostPaymentApplicationsSummary - PostPaymentApplicationsOnBeforePostCredit, PostPaymentApplicationsOnBeforePostDebit

### ISSUE THREAD

**Issue by ACJStopka** [microsoft/ALAppExtensions#22442]
Please add the two following Events to procedure PostPaymentApplicationsSummary in Codeunit 370

local procedure PostPaymentApplicationsSummary(BankAccRecon: Record "Bank Acc. Reconciliation"; Credit: Decimal; Debit: Decimal)
    var
        BankAccReconLine: Record "Bank Acc. Reconciliation Line";
        BankAcc: Record "Bank Account";
        GenJnlLine: Record "Gen. Journal Line";
        StatementDate: Date;
    begin
.
.
.
                "Shortcut Dimension 2 Code" := BankAccRecon."Shortcut Dimension 2 Code";
                "Dimension Set ID" := BankAccRecon."Dimension Set ID";
                
                PostPaymentApplicationsOnBeforePostCredit(GenJnlLine, BankAccRecon, BankAcc)

                GenJnlPostLine.RunWithCheck(GenJnlLine);
            end;

            // post debit
            if Debit <> 0 then begin
                Init();
                SetSuppressCommit(true); // NAVCZ
                "Posting Date" := StatementDate;
                "Account Type" := "Account Type"::"Bank Account";
                "Account No." := BankAccRecon."Bank Account No.";
                "Document No." := BankAccRecon."Statement No.";
                Validate("Currency Code", BankAcc."Currency Code");
                Validate(Amount, Debit);
                "Source Code" := SourceCode;
                "Shortcut Dimension 1 Code" := BankAccRecon."Shortcut Dimension 1 Code";
                "Shortcut Dimension 2 Code" := BankAccRecon."Shortcut Dimension 2 Code";
                "Dimension Set ID" := BankAccRecon."Dimension Set ID";
                
                PostPaymentApplicationsOnBeforePostDebit(GenJnlLine, BankAccRecon, BankAcc)

                GenJnlPostLine.RunWithCheck(GenJnlLine);
            end;
            
[IntegrationEvent(false, false)]
local procedure PostPaymentApplicationsOnBeforePostCredit(var GenJnlLine: Record "Gen. Journal Line"; BankAccRecon: Record "Bank Acc. Reconciliation"; BankAcc: Record "Bank Account")
    begin
    end;

**Comment by MarkoTrn** [comment]
Hello,

Thank you on your suggestion. Please, put the code sample again and make sure to take segment of code from version 22

**Comment by tomasevics** [comment]
Closed due inactivity.
