### ISSUE TITLE
[Application Enhancement] Codeunit 365 - Format Address - Country/Region Name based on Language Code of Document/Entity

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#2244]
Dear ALAppExtensions team,

Through this issue we would like to request the following change in the base application.
Currently, Country/Region translations are not used in codeunit 365 Format Address.
As a result, while all other columns and labels in reports are translated, the Country/Region part of the address on the document is displayed with the default, untranslated Country/Region description.
Therefore, we would suggest to make some changes to make sure the "Language Code" field of documents and entities are used to retrieve the corresponding translation.
(At first we were thinking about requesting an event to allow for this change as a customization, but it might be better to incorporate this into the application itself.)

A possible implementation of this could be as follows:
```pascal
[External] FormatAddr(VAR AddrArray : ARRAY [8] OF Text[100];Name : Text[100];Name2 : Text[100];Contact : Text[100];Addr : Text[100];Addr2 : Text[50];City : Text[50];PostCode : Code[20];County : Text[50];CountryCode : Code[10]; LanguageCode : Code[10])
// ^ Added parameter LanguageCode
CLEAR(AddrArray);

IF CountryCode = '' THEN BEGIN
  GLSetup.GET;
  CLEAR(Country);
  Country."Address Format" := GLSetup."Local Address Format";
  Country."Contact Address Format" := GLSetup."Local Cont. Addr. Format";
END ELSE BEGIN
  IF NOT Country.GET(CountryCode) THEN BEGIN
    Country.INIT;
    Country.Name := CountryCode;
  END;
// >> New code
  IF CountryRegionTranslation.GET(CountryCode, LanguageCode) THEN
    Country.Name := CountryRegionTranslation.Name;
// << New code
END;
...
```
alternatively, rather than adding a parameter to the existing `FormatAddr` procedure, adding a new procedure like `FormatAddrWithLanguageCode` might be an option;
Or, another alternative, let each procedure call a function `SetLanguageCode` that will set a global variable that is then used in the `FormatAddr` procedure.

Then, for each procedure in the codeunit, an argument would be added with the language code of the document or entity, here are two examples:
```pascal
[External] Customer(VAR AddrArray : ARRAY [8] OF Text[100];VAR Cust : Record Customer)
OnBeforeCustomer(AddrArray,Cust,Handled);
IF Handled THEN
  EXIT;

WITH Cust DO
  FormatAddr(
    AddrArray,Name,"Name 2",Contact,Address,"Address 2",
    City,"Post Code",County,"Country/Region Code", Cust."Language Code");

...

[External] SalesHeaderSellTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR SalesHeader : Record "Sales Header")
WITH SalesHeader DO
  FormatAddr(
    AddrArray,"Sell-to Customer Name","Sell-to Customer Name 2","Sell-to Contact","Sell-to Address","Sell-to Address 2",
    "Sell-to City","Sell-to Post Code","Sell-to County","Sell-to Country/Region Code", SalesHeader."Language Code");
```

or, alternatively, by calling a procedure that sets the language code that should be used, for the same two examples:
```pascal
[External] Customer(VAR AddrArray : ARRAY [8] OF Text[100];VAR Cust : Record Customer)
OnBeforeCustomer(AddrArray,Cust,Handled);
IF Handled THEN
  EXIT;

SetLanguageCode(Cust."Language Code"); // << Sets the language that FormatAddr should use
WITH Cust DO
  FormatAddr(
    AddrArray,Name,"Name 2",Contact,Address,"Address 2",
    City,"Post Code",County,"Country/Region Code");

...

[External] SalesHeaderSellTo(VAR AddrArray : ARRAY [8] OF Text[100];VAR SalesHeader : Record "Sales Header")
SetLanguageCode(SalesHeader."Language Code"); // << Sets the language that FormatAddr should use
WITH SalesHeader DO
  FormatAddr(
    AddrArray,"Sell-to Customer Name","Sell-to Customer Name 2","Sell-to Contact","Sell-to Address","Sell-to Address 2",
    "Sell-to City","Sell-to Post Code","Sell-to County","Sell-to Country/Region Code");
```

We hope to see your thoughts and/or feedback on this!

**Comment by RomanZanizdra** [comment]
Hi @rvanbekkum . 
There is the event OnAfterFormatAddress(...), please use it and let us know if you need additional ones.

**Comment by rvanbekkum** [comment]
Hi @RomanZanizdra,
I don't think this event can properly solve the issue. Thing is, you won't know which Language Code to use when coming from the `FormatAddr` procedure.

Currently `FormatAddr` will always return the address with the untranslated Country/Region, while everything else in our (**for example**) Sales documents is in the appropriate language (declared by `SalesHdr`."Language Code" in that case).
What we'd like is to be able to indicate which language should be used to retrieve the appropriate Country/Region translation.

What we currently have added on-prem is a procedure `FormatAddr.SetLanguageCode`, that will set the `LanguageCode` and store it as a global variable:
```
    procedure SetLanguageCode(pLanguageCode : Code[10])
    begin
        LanguageCode := pLanguageCode;
    end;
```
so that when the procedure `FormatAddr.FormatAddr` is called, the appropriate Country/Region translation is retrieved:
```pascal
procedure FormatAddr(var AddrArray : array[8] OF Text[100]; Name : Text[100]; Name2 : Text[100]; Contact : Text[100]; Addr : Text[100];Addr2 : Text[50]; City : Text[50]; PostCode : Code[20]; County : Text[50]; CountryCode : Code[10])
var
    ...
begin
    Clear(AddrArray);

    if CountryCode = '' then begin
        GLSetup.Get();
        CLEAR(Country);
        Country."Address Format" := GLSetup."Local Address Format";
        Country."Contact Address Format" := GLSetup."Local Cont. Addr. Format";
    end else begin
        if not Country.Get(CountryCode) then begin
            Country.Init();
            Country.Name := CountryCode;
        end;
        // >> New code
        if CountryRegionTranslation.Get(CountryCode, LanguageCode) then
            Country.Name := CountryRegionTranslation.Name;
        // << New code
    end;
    
    ...
    
end;
```

I am not saying this should necessarily be implemented in the same way in the MS "Base Application", but I do think it a bit odd there is nothing similar already present to have the Country/Region properly translated in documents.
Could you please let us know your thoughts on this?

**Comment by RomanZanizdra** [comment]
@rvanbekkum , there will be setter for language code (global variable) in the codeunit and this variable will be available via OnAfterFormatAddress(...) event. Is it ok?

**Comment by rvanbekkum** [comment]
That could work, yes.

It would mean that _for now_ we'd need to make an extension on the Base Application wherever/whenever we want to apply this. 
If we would like this (i.e., an option for Country/Region translation for Format Address) in the Base Application by default, then it's probably best if we add a request/idea on https://aka.ms/bcideas, is that correct?

**Comment by rvanbekkum** [comment]
An idea to have it in the Base Application by default already exists, by the way:
https://experience.dynamics.com/ideas/idea/?ideaid=03faf9fb-6449-e911-867a-0003ff68f3db

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
