### ISSUE TITLE
[Var Request] Report 12176 "Suggest Customer Bills" - Event "OnCreateLineOnBeforeInsert" on CreateLine - Change parameter CustomerBillLine as var

### ISSUE THREAD

**Issue by FabioC34** [microsoft/ALAppExtensions#22445]
Hello, in the Event "OnCreateLineOnBeforeInsert" the parameter CustomerBillLine is not defined as "var"; in this way the event is useless, because the fields value of Record if filled in the subscriber are not passed back and the Insert executed after the call will not consider the modification made in subscriber.
Could you please change the event as follows:

```
    [IntegrationEvent(false, false)]
    local procedure OnCreateLineOnBeforeInsert(var CustomerBillLine: Record "Customer Bill Line"; CustLedgerEntry: Record "Cust. Ledger Entry"; CustomerBillHeader: Record "Customer Bill Header")
    begin
    end;
```

Thank you
Fabio

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10818.
