### ISSUE TITLE
[Event Request] codeunit 5896 "Calc. Inventory Adjmt. - Order" OnCalcActualCapacityCostsOnAfterSetFilters

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#22454]
Can you add Subcontracting, ShareOfTotalCapCost and IsHandled parameters to OnCalcActualCapacityCostsOnAfterSetFilters?

``` 
            SetRange("Item No.", InvtAdjmtEntryOrder."Item No.");
            // >>>>>>>>>>>>>>>>>>>
            //OnCalcActualCapacityCostsOnAfterSetFilters(CapLedgEntry, InvtAdjmtEntryOrder);
            OnCalcActualCapacityCostsOnAfterSetFilters(CapLedgEntry, InvtAdjmtEntryOrder, Subcontracting, ShareOfTotalCapCost, IsHandled);
            if not IsHandled then
            // <<<<<<<<<<<<<<<<<<<
            if Find('-') then
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11199.
