### ISSUE TITLE
[Variable Scope request] Ability to add more parameters for Exch. Rate Adjustment feature

### ISSUE THREAD

**Issue by hgnamvn** [microsoft/ALAppExtensions#22455]
Please modify Report 596 "Exch. Rate Adjustment" so that we can add more parameter to this report and transfer to Adjustment process (Codeunit 699 "Exch. Rate Adjmt. Process").

With Report 596 "Exch. Rate Adjustment", on "RunAdjustmentProcess" procedure, please make variable ExchRateAdjmtParameters (Record "Exch. Rate Adjmt. Parameters") to GLOBAL PROTECTED variable.
So that, I can add more parameters into "Exch. Rate Adjmt. Parameters" and transfer to (use in) Codeunit 699 "Exch. Rate Adjmt. Process".

![image](https://user-images.githubusercontent.com/24407031/223371152-2a7036ee-adc5-438a-ba60-724e5b362771.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10719.
