### ISSUE TITLE
ODataV4 bound action with pageextension

### ISSUE THREAD

**Issue by HegedusZsolt** [microsoft/ALAppExtensions#22456]
We would like to add some new function to an existing page to reach them via ODataV4 protocol, but it seems it's not supported by Business Central.

I've found the following note in the documentation : "Bound actions cannot be added by extending an existing page that has been exposed as a web service."

It may available in the future releases or is there any workaround to do this?

**Comment by JesperSchulz** [comment]
Sorry, we'd like to help, but this just isn't the right team to ask. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/forums/thread/?groupid=e78817ab-a926-4d31-96cc-aef040a4eb04)
[mibuso forum](https://forum.mibuso.com/)
[Viva Engage](https://www.yammer.com/dynamicsnavdev)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
