### ISSUE TITLE
[Event Request] codeunit 5896 "Calc. Inventory Adjmt. - Order" OnCalcActualMaterialCostsOnAfterSetFilters

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#22452]
Can you add variabel CalcActualMaterialCostQuery in procedure CalcActualMaterialCosts to event OnCalcActualMaterialCostsOnAfterSetFilters as reference to be able to override filters?

Edit: can you also add IsHandled and make AdjustForRevNegCon global?

```
        CalcActualMaterialCostQuery.Open();

        // >>>>>>>>>>>>>>>>
        //OnCalcActualMaterialCostsOnAfterSetFilters(ItemLedgEntry, InvtAdjmtEntryOrder);
        OnCalcActualMaterialCostsOnAfterSetFilters(ItemLedgEntry, InvtAdjmtEntryOrder, CalcActualMaterialCostQuery, IsHandled);
        if not IsHandled then
        // <<<<<<<<<<<<<<<<

        while CalcActualMaterialCostQuery.Read() do begin
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10874.
