### ISSUE TITLE
[Event Request] codeunit 99000787 "Create Prod. Order Lines" OnAfterProdOrderLineInsert

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#22459]
Can you set IncludeSender to true for this event:
OnAfterProdOrderLineInsert
And make procedure InitProdOrderLine global to be able to call it from sender in the event.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10050.
