### ISSUE TITLE
[Event Request] codeunit 99000787 "Create Prod. Order Lines" OnAfterProdOrderLineInsert

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#22458]
Can you add ErrorOccured as parameter to event OnAfterProdOrderLineInsert.
As reference:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterProdOrderLineInsert(var ProdOrder: Record "Production Order"; var ProdOrderLine: Record "Prod. Order Line"; var NextProdOrderLineNo: Integer; var ErrorOccured: Boolean)
    begin
    end;
```

**Comment by tomasevics** [comment]
We can't forward parameter ErrorOccured from procedure InsertProdOrderLine().

**Comment by auzhhv** [comment]
> OnAfterProdOrderLineInsert

Is there a reason?
I need it to update if an error has occured when I create additional prod. order lines.

**Comment by tomasevics** [comment]
If we pass parameter ErrorOccured to procedure InsertProdOrderLine, than we would need also same parameter in procedure CheckMakeOrderLine, and also in CheckMultiLevelStructure and also in CheckStructure which we are not allowed to do, because procedure is public and that will be breaking change.
