### ISSUE TITLE
[Parameter Request] Add more parameter for OnPostGenJnlLineOnBeforeGenJnlPostLineRun event

### ISSUE THREAD

**Issue by hgnamvn** [microsoft/ALAppExtensions#22453]
Please add more parameter ExchRateAdjmtParameters: Record "Exch. Rate Adjmt. Parameters" into OnPostGenJnlLineOnBeforeGenJnlPostLineRun event of Codeunit 699 "Exch. Rate Adjmt. Process"

![image](https://user-images.githubusercontent.com/24407031/223307623-edfabe4d-2547-45e3-bbd0-4275851e3301.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10053.
