### ISSUE TITLE
[Event Request] on Sales-Post functions

### ISSUE THREAD

**Issue by FavMY** [microsoft/ALAppExtensions#22468]
Hey all,

due to some manual posting on assembly orders which refer to a sales order (also partial posting on that assembly order) and to be able to handle some changes afterwards, we need some events in the Sales-Post Codeunit (codeunit 80 "Sales-Post")

To be short, we need an OnBefore-Handled pattern in the functions below:
- FinalizePostATO
- DeleteATOLinks
- CheckATOLink

We need to skip some checks and the deletion of the ATO-Link. Hope it is understandable without code, if not just tell me here about that.

Thank you
Internal work item: [AB#536756](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536756)

**Comment by FavMY** [comment]
Hey all,

im not sure why here is a missing info tag. But let me show you what kind of Events we need:
So in Codeunit 80 "Sales-Post" procedure FinalizePostATO a Handled pattern like:

![image](https://github.com/microsoft/ALAppExtensions/assets/37626011/402b0ec3-1252-44eb-ae55-0ff23f8c86af)

in DeleteATOLinks:

![image](https://github.com/microsoft/ALAppExtensions/assets/37626011/cc0ccec3-fa05-4239-94e5-caead7875cfe)

and in CheckATOLink:

![image](https://github.com/microsoft/ALAppExtensions/assets/37626011/e9a31b3b-b4ec-4c17-9c7c-b86bea142f29)


Hope it is much clearer now.

With kind regards

**Comment by AleksandricMarko** [comment]
Hello @FavMY 
Just to check, is this still needed?
It popped up yesterday, but it is more than 1year old

**Comment by FavMY** [comment]
Hey.

yes pls. Its needed

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20421.
