### ISSUE TITLE
[Event Request] in codeunit 99000770 "Where-Used Management"

### ISSUE THREAD

**Issue by michuanni** [microsoft/ALAppExtensions#22461]
We need a subscriber in line 120 bevore if ProdBOMComponent.FindSet() then statement.

OnBeforeFindSetProdBOMComponent(var ProdBOMComponent) because of setting ProdBOMCompoenten.SetLoadFields for a better performance.

        ProdBOMComponent.SetCurrentKey(Type, "No.");
        ProdBOMComponent.SetRange(Type, Type);
        ProdBOMComponent.SetRange("No.", No);
        if CalcDate <> 0D then begin
            ProdBOMComponent.SetFilter("Starting Date", '%1|..%2', 0D, CalcDate);
            ProdBOMComponent.SetFilter("Ending Date", '%1|%2..', 0D, CalcDate);
        end;
        OnBeforeFindSetProdBOMComponent(ProdBOMComponent)
        if ProdBOMComponent.FindSet() then
            repeat
                if VersionMgt.GetBOMVersion(
                     ProdBOMComponent."Production BOM No.", CalcDate, true) =
                   ProdBOMComponent."Version Code"
                then begin
                    OnBuildWhereUsedListOnLoopProdBomComponent(ProdBOMComponent, TempWhereUsedList, NextWhereUsedEntryNo, No, CalcDate, Level);
                    if IsActiveProductionBOM(ProdBOMComponent) then
                        BuildWhereUsedList(
                          Enum::"Production BOM Line Type"::"Production BOM",
                          ProdBOMComponent."Production BOM No.",
                          CalcDate,
                          Level + 1,
                          CostCalcMgt.CalcCompItemQtyBase(ProdBOMComponent, CalcDate, Quantity, '', false));
                end;
            until ProdBOMComponent.Next() = 0;

        OnAfterBuildWhereUsedList(Type, No, CalcDate, TempWhereUsedList, NextWhereUsedEntryNo, Level, Quantity, MultiLevel);

With our extension this findset produce the following sql statement

SELECT TOP (@0) "5410"."timestamp"
	,"5410"."Status"
	,"5410"."Prod_ Order No_"
	,"5410"."Requested Only"
	,"5410"."Routing No_"
	,"5410"."Routing Reference No_"
	,"5410"."Operation No_"
	,"5410"."Line No_"
	,"5410"."Type"
	,"5410"."No_"
	,"5410"."Work Center No_"
	,"5410"."Work Center Group Code"
	,"5410"."Date"
	,"5410"."Starting Time"
	,"5410"."Ending Time"
	,"5410"."Allocated Time"
	,"5410"."Send-Ahead Type"
	,"5410"."Time Type"
	,"5410"."Needed Time"
	,"5410"."Needed Time (ms)"
	,"5410"."Lot Size"
	,"5410"."Concurrent Capacities"
	,"5410"."Efficiency"
	,"5410"."Starting Date-Time"
	,"5410"."Ending Date-Time"
	,"5410"."Worksheet Template Name"
	,"5410"."Worksheet Batch Name"
	,"5410"."Worksheet Line No_"
	,"5410"."Active"
	,"5410_e3"."KVSKW"
	,"5410"."$systemId"
	,"5410"."$systemCreatedAt"
	,"5410"."$systemCreatedBy"
	,"5410"."$systemModifiedAt"
	,"5410"."$systemModifiedBy"
FROM "BCTest".dbo."PIA Automation Austria GmbH$Prod_ Order Capacity Need$437dbf0e-84ff-417a-965d-ed2bb9650972" "5410" WITH (READUNCOMMITTED)
JOIN "BCTest".dbo."PIA Automation Austria GmbH$Prod_ Order Capacity Need$769d0762-06b1-42a0-aebe-3028d86cb96a" "5410_e3" WITH (READUNCOMMITTED) ON ("5410"."Status" = "5410_e3"."Status")
	AND ("5410"."Prod_ Order No_" = "5410_e3"."Prod_ Order No_")
	AND ("5410"."Requested Only" = "5410_e3"."Requested Only")
	AND ("5410"."Routing No_" = "5410_e3"."Routing No_")
	AND ("5410"."Routing Reference No_" = "5410_e3"."Routing Reference No_")
	AND ("5410"."Operation No_" = "5410_e3"."Operation No_")
	AND ("5410"."Line No_" = "5410_e3"."Line No_")
WHERE (
		"5410"."Worksheet Template Name" = @1
		AND "5410"."Worksheet Batch Name" = @2
		AND "5410"."Worksheet Line No_" = @3
		)
ORDER BY "Status" ASC
	,"Prod_ Order No_" ASC
	,"Requested Only" ASC
	,"Routing No_" ASC
	,"Routing Reference No_" ASC
	,"Operation No_" ASC
	,"Line No_" ASC
OPTION (FAST 50)

We have many data in this table and this statement takes over 20 seconds time. So we do not need this join therefore we want to use SetLoadFields

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10836.
