### ISSUE TITLE
[Event Request] Codeunit 7018 "Price UX Management" 

### ISSUE THREAD

**Issue by KnudScholer** [microsoft/ALAppExtensions#22460]
I would like to suggest a new publisher 

In Codeunit 7018 "Price UX Management"
procedure LookupPriceLists(SourceGroup: Enum "Price Source Group"; PriceType: Enum "Price Type"; var PriceListCode: Code[20]): Boolean;
After the Case sentence:
OnAfterLookupPriceLists(SourceGroup,PriceListHeader,PriceType,PriceListCode);

Reason: If you extend the solution so prices can be based on other than, Job, Customers or Vendors. We have a solution with 2 more types.

Best regards Knud

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10050.
