### ISSUE TITLE
[Function Expose] Table 60 Document Sending Profile: Send, SendVendor

### ISSUE THREAD

**Issue by Kowa63** [microsoft/ALAppExtensions#2247]
Would it be possible to change Send and SendVendor from 'Internal' to 'External', so that these may be called directly without having to select a profile beforehand?
![grafik](https://user-images.githubusercontent.com/16236672/56945016-d26f9200-6b25-11e9-8c50-23315e919f58.png)

**Comment by AlexanderYakunin** [comment]
We will investigate if this is possible

**Comment by GeekEding** [comment]
Are there some new information about this external request?

**Comment by RomanZanizdra** [comment]
This is done, requested functions are external.

**Comment by GeekEding** [comment]
In the current BC insider, they are still "Internal"
![grafik](https://user-images.githubusercontent.com/40355993/61939389-6f11c680-af93-11e9-8e8e-8eb5af5440cc.png)

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
