### ISSUE TITLE
[Enum Request] table 5109 "Purchase Header Archive" - field 120 Status

### ISSUE THREAD

**Issue by alapenas** [microsoft/ALAppExtensions#22480]
Hello, would it be possible to transform the Option field(120; Status; Option) in table 5109 "Purchase Header Archive" to an existing Enum "Purchase Document Status". We would like to extend this with custom values.

 ```al 
        field(120; Status; Option)
        {
            Caption = 'Status';
            OptionCaption = 'Open,Released,Pending Approval,Pending Prepayment';
            OptionMembers = Open,Released,"Pending Approval","Pending Prepayment";
        }
 ```

 ```al 
        field(120; Status; Enum "Purchase Document Status")
        {
            Caption = 'Status';
        }
 ```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10142.
