### ISSUE TITLE
[Enum Request] table 5972 "Contract/Service Discount" - field 4 Type

### ISSUE THREAD

**Issue by alapenas** [microsoft/ALAppExtensions#22482]
Hello, would it be possible to transform the Option field(4; Type; Option) in 5972 "Contract/Service Discount" to a new Enum "Service Release Status". We would like to extend this with custom values.

 ```al 
        field(4; Type; Option)
        {
            Caption = 'Type';
            OptionCaption = 'Service Item Group,Resource Group,Cost';
            OptionMembers = "Service Item Group","Resource Group",Cost;
        }
 ```

 ```al 
        field(4; Type; Enum "Contract/Service Discount Type")
        {
            Caption = 'Type';
        }
 ```

New Enum object suggestion:
 ```al 
enum XXX "Contract/Service Discount Type"
{
    Extensible = true;
    AssignmentCompatibility = true;
    
    value(0; "Service Item Group") { Caption = 'Service Item Group'; }
    value(1; "Resource Group") { Caption = 'Resource Group'; }
    value(2; "Cost") { Caption = 'Cost'; }
}
 ```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10142.
