### ISSUE TITLE
[Request for External] procedure IsQuantityChangedForPrice in table 1003 - "Job Planning Line"

### ISSUE THREAD

**Issue by MMueller1974** [microsoft/ALAppExtensions#22485]
Dear AL AppExtensionsTeam,

can you please remove the local prefix from the procedure IsQuantityChangedForPrice in table 1003 "Job Planning Line"?
Old signature
```AL
local procedure IsQuantityChangedForPrice(): Boolean;
```
New signature
```AL
procedure IsQuantityChangedForPrice(): Boolean;
```

Thank you in advance

**Comment by MMueller1974** [comment]
I was able to remove the dependency on this procedure, so this issue can be closed.

**Comment by AlexanderYakunin** [comment]
Thank you, closing
