### ISSUE TITLE
[Enum Request] table 5900 "Service Header" and table 5901 "Service Item Line" - field 130 "Release Status"

### ISSUE THREAD

**Issue by alapenas** [microsoft/ALAppExtensions#22481]
Hello, would it be possible to transform the Option field(130; "Release Status"; Option) in table 5900 "Service Header" and table 5901 "Service Item Line" to a new Enum "Service Release Status". We would like to extend this with custom values.

 ```al 
        field(130; "Release Status"; Option)
        {
            Caption = 'Release Status';
            OptionCaption = 'Open,Released to Ship';
            OptionMembers = Open,"Released to Ship";
        }
 ```

 ```al 
        field(130; "Release Status"; Enum "Service Release Status")
        {
            Caption = 'Release Status';
        }
 ```

New Enum object suggestion:
 ```al 
enum 5903 "Service Release Status"
{
    Extensible = true;
    AssignmentCompatibility = true;
    
    value(0; "Open") { Caption = 'Open'; }
    value(1; "Released to Ship") { Caption = 'Released to Ship'; }
}
 ```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10142.
