### ISSUE TITLE
[Change Request] page 209 "Units of Measure" - variable CRMIntegrationEnabled

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#22495]
Hello, can you pleas eset the variable CRMIntegrationEnabled as protected var?

```
    var
        CRMIsCoupledToRecord: Boolean;
 
   protected var
        CRMIntegrationEnabled: Boolean;
```

**Comment by AlexanderYakunin** [comment]
Please explain for that purpose?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10376.
