### ISSUE TITLE
[Change Request] table 220 "Business Unit" - procedure CheckGLAcc

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#22494]
Hello, can you please change the local procedure CheckGLAcc as global?

```
local procedure CheckGLAcc(AccNo: Code[20])
    var
        GLAcc: Record "G/L Account";
    begin
        if AccNo <> '' then begin
            GLAcc.Get(AccNo);
            GLAcc.CheckGLAcc();
        end;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10221.
