### ISSUE TITLE
REP7321 Inventory Movement - Report Selections

### ISSUE THREAD

**Issue by SirBETE** [microsoft/ALAppExtensions#2249]
Could report 7321 Inventory Movement be made adjustable via Report Selections?
We have copied the report into our product, and want to print our version of it.

Now the report is run directly from the PAG40 Item Journal via the 'Print' Action.
```
<Action70> - OnAction()
ItemJnlLine.COPY(Rec);
ItemJnlLine.SETRANGE("Journal Template Name","Journal Template Name");
ItemJnlLine.SETRANGE("Journal Batch Name","Journal Batch Name");
REPORT.RUNMODAL(REPORT::"Inventory Movement",TRUE,TRUE,ItemJnlLine);
```

For now we can run our modified report by copying the action in a page extension, change the report to our version and hide the BC button.
Modified in PAG40, PAG286, PAG393, PAG5510 (journal pages)
Print actions also exists in production module, but we don't use that module, so they are left unchanged

**Comment by AlexanderYakunin** [comment]
You can simply hide our action and add your action to ptint your report. This is easiest way to do it.

**Comment by SirBETE** [comment]
Yeah, that's like I said how I fixed it.
I still think that isn't the best way to do it.
I had to change now 4 (of the 8) pages ...
And what if MS decides to change the action, ours won't be updated...

**Comment by RomanZanizdra** [comment]
Hi @SirBETE . There will be enum "Report Selection Usage" which can be easily extended with the new value for "Inventory Movement" and as it was mentioned above you can also hide our action and use your own one.
