### ISSUE TITLE
[Scope Change] Table 9500 Procedure GetBodyText

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#22499]
Hello, we need the OnPrem-Scrope of the following procedure to be deleted.

```	
// #DEL# [Scope('OnPrem')]
    procedure GetBodyText() Value: Text
    var
        TempBlob: Codeunit "Temp Blob";
        FileManagement: Codeunit "File Management";
        BodyText: BigText;
        DataStream: InStream;
        BlobInStream: InStream;
        BodyOutStream: OutStream;
        IsHandled: Boolean;
    begin
	    ....
```

**Comment by darjoo** [comment]
Can you please provide the scenario you need this for?

**Comment by SKeiler** [comment]
I would here take over for my colleague once :-)

We want to read the existing Body Text of the E-Mail and replace some placeholder texts in the E-Mailbody with information out of the system like Name, Invoice No. etc. (and overwrite the E-Mailbody after that).

For us it would be enough to get the Body Text which in saved in the BLOB-table field (and not saved in in File System). But for that the GetBodyFunction should be splitted in 2 oder 3 parts (one to get the body text from file system, one to get the body text from BLOB) and one, which combines the 2 variants as follow up of the existing functions. So the easier way is to eliminate the OnPrem-Flag at this function. 

![image](https://user-images.githubusercontent.com/45033081/232700578-773d0f4c-7cad-43c1-8c4b-c0e529551688.png)

**Comment by darjoo** [comment]
I can provide a second function that only gets it from the BLOB. I won't be able to remove the scope due to the file access in the middle. I'd also like to avoid doing more refactoring than required for this.
Would that be sufficient? @SKeiler

**Comment by SKeiler** [comment]
Sounds great!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10613.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 55996.
