### ISSUE TITLE
[Event Request] Codeunit 1000 - "Job Calculate WIP" - OnCaclWIPOnAfterSetAmounts

### ISSUE THREAD

**Issue by ghost** [microsoft/ALAppExtensions#22505]
Dear ALAppExtensions team,

through this issue we would like to request adding a new event publisher `OnCaclWIPOnAfterSetAmounts` in Codeunit 1000 "Job Calculate WIP" with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnCaclWIPOnAfterSetAmounts(var JobTask: Record "Job Task")
begin
end;
```
which would be called as follows in `CalcWIP`:
```AL
local procedure CalcWIP(var JobTask: Record "Job Task"; JobWIPTotal: Record "Job WIP Total")
var
    JobWIPMethod: Record "Job WIP Method";
begin
    if JobComplete then begin
        JobTask."Recognized Sales Amount" := JobTask."Contract (Invoiced Price)";
        JobTask."Recognized Costs Amount" := JobTask."Usage (Total Cost)";
        // >>>> New >>>>>>>>>>>>>>>>
        OnCaclWIPOnAfterSetAmounts(JobTask);
        // <<<< New <<<<<<<<<<<<<<<<
        exit;
    end;
    JobWIPMethod.Get(JobWIPTotal."WIP Method");
    CalcRecognizedCosts(JobTask, JobWIPTotal, JobWIPMethod);
    CalcRecognizedSales(JobTask, JobWIPTotal, JobWIPMethod);
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10804.
