### ISSUE TITLE
table 273 "Bank Acc. Reconciliation" and table 274 "Bank Acc. Reconciliation Line" field(20; "Statement Type"; Option)

### ISSUE THREAD

**Issue by AndreaRux** [microsoft/ALAppExtensions#22508]
Hi,
would it be possible to change type of field 20 "Statement Type" form option to enum in
table 273 "Bank Acc. Reconciliation" and table 274 "Bank Acc. Reconciliation Line"?

```
        field(20; "Statement Type"; Option)
        {
            Caption = 'Statement Type';
            OptionCaption = 'Bank Reconciliation,Payment Application';
            OptionMembers = "Bank Reconciliation","Payment Application";
        }
```
```
        field(20; "Statement Type"; Enum "Recon. Statement Type")
        {
            Caption = 'Statement Type';
        }
```

```
enum XYZ "Recon. Statement Type"
{
    value(0; "Bank Reconciliation")
    {
        Caption = 'Bank Reconciliation';
    }
    value(1; "Payment Application")
    {
        Caption = 'Payment Application';
    }
}
```
Thanks in advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10142.
