### ISSUE TITLE
[New Function] GetParameters in Page 474 VAT Statement Preview

### ISSUE THREAD

**Issue by ernestasju** [microsoft/ALAppExtensions#2250]
Hello,

We need a way to get parameters set on page Page 474 VAT Statement Preview. They are stored in globals and AFAIK not accessible from extensions.

Please add new external function GetParameters to page Page 474 VAT Statement Preview.
![image](https://user-images.githubusercontent.com/3514528/53393479-28e51680-39a5-11e9-9998-6f177958a0e7.png)

Thanks.

**Comment by ernestasju** [comment]
Hello, what is the progress for this request?

**Comment by fvet** [comment]
@AlexanderYakunin Any status updated? Seems not included in BC 15.1 yet...

**Comment by fvet** [comment]
Also needed for Belgian localization extensions.... ;)

**Comment by AlexanderYakunin** [comment]
Seems this issue have been created in old repo and we already have #2250 for actual one. This is the reason why this change is not delivered yet. I'm closing this item and will track this change under #5821.
