### ISSUE TITLE
[Event Request] Codeunit 1000 - "Job Calculate WIP" - OnBeforeGetAppliedCostsWIPEntryAmount

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#22507]
Dear ALAppExtensions team,

through this issue we would like to request adding a new event publisher `OnBeforeGetAppliedCostsWIPEntryAmount` in Codeunit 1000 "Job Calculate WIP" with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeGetAppliedCostsWIPEntryAmount(JobTask: Record "Job Task"; JobWIPMethod: Record "Job WIP Method"; AppliedAccrued: Boolean; var Result: Decimal; var IsHandled: Boolean)
begin
end;
```
which would be called as follows in `GetAppliedCostsWIPEntryAmount`:
```AL
local procedure GetAppliedCostsWIPEntryAmount(JobTask: Record "Job Task"; JobWIPMethod: Record "Job WIP Method"; AppliedAccrued: Boolean): Decimal
    // >>>> New >>>>>>>>>>>>>>>>
    var
        IsHandled: Boolean;
        Result: Decimal;
    // <<<< New <<<<<<<<<<<<<<<<
    begin
        // >>>> New >>>>>>>>>>>>>>>>
        OnBeforeGetAppliedCostsWIPEntryAmount(JobTask, JobWIPMethod, AppliedAccrued, Result, IsHandled);
        if IsHandled then
            exit(Result);
        // <<<< New <<<<<<<<<<<<<<<<

        exit(GetAppliedCostsAmount(JobTask."Recognized Costs Amount", JobTask."Usage (Total Cost)", JobWIPMethod, AppliedAccrued));
    end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10804.
