### ISSUE TITLE
Event Request - table 77 Report Selections

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#22519]
Can we have an event in table 77 report selections
in procedure GetAccountNoFilterForCustomReportLayout

//code:
CustomReportSelection.SetRange("Source Type", TableNo);
CustomReportSelection.SetRange(Usage, TempReportSelections.Usage);
CustomReportSelection.SetRange("Report ID", TempReportSelections."Report ID");
CFLOnAfterSetCustomReportSelectionFilters(var CustomReportSelection,TempReportSelections) //event to add
ReportInvolvedInCustomSelection := not CustomReportSelection.IsEmpty();

because now there is an issue if you have custom report selections for a customer, where you do not use the "Custom Report Layout Code", but only for ex. the "Send To Email" field
we would need to set the filter
CustomReportSelection.setfilter("Custom Report Layout Code" '<>%1','')

because when you have for ex. 1 customer with email field filled in for ex. the invoice but no custom layout code
then then ReportInvolvedinCustomSelection becomes true, but in fact there is no custom report layout
when you multiselect invoices to print, then not all are printed because of that
althoug there is no reason to, because there are no different layouts.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10881.
