### ISSUE TITLE
[Events Request] Report 29 dataitem(Integer) trigger OnAfterGetRecord() OnAfterAccSchedLineSetFilter

### ISSUE THREAD

**Issue by ACJStopka** [microsoft/ALAppExtensions#22520]
Window.Update(1, 0);
    AccSchedLine.SetFilter(Show, '<>%1', AccSchedLine.Show::No);
    
    **OnAfterAccSchedLineSetFilter(AccSchedLine);**

    TotalRecNo := AccSchedLine.Count();
    RecNo := 0;

    **[IntegrationEvent(false, false)]
    local procedure OnAfterAccSchedLineSetFilter(var AccScheduleLine: Record "Acc. Schedule Line")
    begin
    end;**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10818.
