### ISSUE TITLE
[Access Request] Page 1292 "Payment Application"

### ISSUE THREAD

**Issue by Joneleth84** [microsoft/ALAppExtensions#22534]
Hello,

could you please changed access level of global var "BankAccReconLine" (Record "Bank Acc. Reconciliation Line") to protected, as it is typically externally set via SetBankAccReconcLine().

Best regards,
JG

**Comment by AlexanderYakunin** [comment]
Please explain your scenario. Do you need to get access to values in this variable in your extension? Or do you need to update it at  some points. If we make it protected now, it will be quite difficult to do more changes in this page, as this variable is heavily used in page controls
