### ISSUE TITLE
Format Address for Location

### ISSUE THREAD

**Issue by djurado-olivia** [microsoft/ALAppExtensions#22533]
Hello!

I work as an AL Developer and I have a request for you to implement a new standard procedure.

I'm asking if you could add to the codeunit 365 "Format Address" a new procedure copying the existing code you have for Vendors or Customers but for table 14 Location.

Right now this functionality can be done with the already existing procedure:
`FormatAddr(var AddrArray: array[8] of Text[100]; Name: Text[100]; Name2: Text[100]; Contact: Text[100]; Addr: Text[100]; Addr2: Text[50]; City: Text[50]; PostCode: Code[20]; County: Text[50]; CountryCode: Code[10])`

But since table 14 Location already has each required field to call that mentioned procedure, I was wondering if you could make it easier to call that procedure as you've done with Vendors or Customers, the call would look like:
`if Location.Get(LocationCode) then
            FormatAddr.Location(AddrArray, Location);`

I'm attaching a screenshot from my actual code where it's more clear to see what I'm refering to.

![FormatAddressLocation](https://user-images.githubusercontent.com/101122291/224669125-b5734b10-cecc-4a3d-b151-6e3eea0582ea.png)

Thank you!!!

Best regards,
David

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10730.
