### ISSUE TITLE
Page "Item Availability by UOM" variable AmountType not declared Protected

### ISSUE THREAD

**Issue by murielaimar** [microsoft/ALAppExtensions#22536]
In page "Item Availability by UOM" variable "AmountType" is not declared Protected and therefore cannot be used

In page "Item Availability by Location" or "Item Availability by Variant" it's ok

can you make the change ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10221.

**Comment by murielaimar** [comment]
Hi, we have just installed version 22 CU3 and the AmountType variable is still not protected. Can you keep me updated ? Thanks

**Comment by JesperSchulz** [comment]
Checked version 23.0:
![image](https://github.com/microsoft/ALAppExtensions/assets/19796701/f4e22210-830b-4a2b-80c1-9ed21828d7c8)
Just a few more weeks.
