### ISSUE TITLE
[Extensibility Enhancement] Usage of table 5612 "FA Depreciation Book"."Default FA Depreciation Book" field

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#22532]
There is the field `"Default FA Depreciation Book"` in `table 5612 "FA Depreciation Book"`. And this field is used in `procedure GetFADeprBook()` in `table 81 "Gen. Journal Line"` to get a FA decreciation book code after validating of an account of type "Fixed Asset". But it is used in this specific place only!

There are other places where, we think, the field should be used to serve its purpose:
- `table 39 "Purchase Line"` `procedure FindDefaultFADeprBook()`
- `table 37 "Sales Line"` `procedure GetFAPostingGroup()`
- `table 5621 "FA Journal Line"` `field "FA No." OnValidate()`
- another??

Of course, there are events that already exist and can be used to solve the situation but would be nice if the standard code does it instead. Could you consider it?

**Comment by Mike-1984** [comment]
We faced the same problem and had to use events to resolve it

**Comment by RadoArvay** [comment]
> We faced the same problem and had to use events to resolve it

Most (or all?) of them were already solved, I do not remember. I have not checked it for a while.

**Comment by AleksanderGladkov** [comment]
It was fixed on October 11th 2023.
