### ISSUE TITLE
[Event Request] Codeunit 89 - "Sales-Post + Email" - OnBeforeSendInvoiceDocumentReport

### ISSUE THREAD

**Issue by IanaAsofiei** [microsoft/ALAppExtensions#22542]
Dear Support,

We would like to add a new event OnBeforeSendInvoiceDocumentReport in the SendDocumentReport from function "Sales-Post + Email" codeunit. This would allow us to ensure that SalesInvHeader is set correctly in case of batch job.
local procedure SendDocumentReport(var SalesHeader: Record "Sales Header")
    var
    begin
        with SalesHeader do
            case "Document Type" of
                "Document Type"::Invoice:
                    begin
						OnBeforeSendInvoiceDocumentReport(SalesInvHeader);
                        if "Last Posting No." = '' then
                            SalesInvHeader."No." := "No."
                        else
                            SalesInvHeader."No." := "Last Posting No.";
                        SalesInvHeader.Find();
                        SalesInvHeader.SetRecFilter();
                        SalesInvHeader.EmailRecords(not HideMailDialog);
                    end;
                "Document Type"::"Credit Memo":
                    begin
                        if "Last Posting No." = '' then
                            SalesCrMemoHeader."No." := "No."
                        else
                            SalesCrMemoHeader."No." := "Last Posting No.";
                        SalesCrMemoHeader.Find();
                        SalesCrMemoHeader.SetRecFilter();
                        SalesCrMemoHeader.EmailRecords(not HideMailDialog);
                    end
            end
    end;
	
	
[IntegrationEvent(false, false)]
local procedure OnBeforeSendInvoiceDocumentReport(var SalesInvHeader: Record "Sales Invoice Header";)
begin
end;

**Comment by IanaAsofiei** [comment]
Hi,

Thank you very much for implementing other requested event subscribers.
Can you solve this one also, please?
We have a deadline from our client and we need this event subscriber to be implemented as soon as possible

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11076.
