### ISSUE TITLE
Option to Enum: Table 1112 "Cost Center" >>  Field(3; "Cost Subtype"; Option)

### ISSUE THREAD

**Issue by thomashoesel** [microsoft/ALAppExtensions#22556]
Hello there, please transform "Cost Subtype" option of table "Cost Center" to Enum. We're required to change its captions at least.

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10142.
