### ISSUE TITLE
GST Group code field length in HSN/SAC table is code[10].

### ISSUE THREAD

**Issue by YM409Ankit** [microsoft/ALAppExtensions#22555]
Here is the detail for the issue:-

Table Name --> "GST Group"  
Field name -->"Code" Length is code[20]

but in Table --> "HSN/SAC" 
Field Name --> "GST Group Code" Length is code[10]

while selecting the GST group code on purchase or sale line which greater than 10 length system is not allowing to provide
the lookup for HSN/SAC field in line level neither on sales nor on Purchase line.

See below image:--

![image](https://user-images.githubusercontent.com/126671512/222122902-05c07aad-4db3-4cd9-8733-62ed1d399ed5.png)

See HSN/SAC table image

![image](https://user-images.githubusercontent.com/126671512/222123146-5e7d5e23-2a0f-41bd-88c2-84eaa97b7e76.png)

See GST Group Table image

![image](https://user-images.githubusercontent.com/126671512/222123244-748a670c-b7fe-4e3b-84b6-636fdf4a2b2f.png)

See Purchase line HSN/SAC Table relation which is throwing an error while selecting the GST group greater than 10 length:-

![image](https://user-images.githubusercontent.com/126671512/222123854-5a44f4d3-df04-431b-8f0e-84cb05a87364.png)

Request you to please fix the issue of length mismatch in GST group table vs HSN/SAC table in BC21 version , we are checking on On-prem version.

Request you to please fix asap as this is impacting our upgrade for client..

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
