### ISSUE TITLE
[Extensibility Bug] Analysis by Dim. User Param, Load page settings

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#22553]
Hello,

When we open the page 554 "Analysis by Dimensions" in OnOpenPage trigger the code load the page parametrs that user use at the last time (on trigger OnQueryClosePage system save params to table "Analysis by Dim. User Param.")

But now, after the load function call system call procedure ValidateAnalysisViewCode() which clear the some fields like dimension filter.

So, I suggest you create a procedure DimOptionDimCode(DimOption: Enum "Analysis Dimension Option"): DimCode: Text[30] which have the revert logic like in DimCodeToDimOption(DimCode: Text[30]) and rewrite trigger OnOpenPage

` trigger OnOpenPage()`
`    var`
`        "Field": Record "Field";`
`        AnalysisByDimUserParam: Record "Analysis by Dim. User Param.";`
`    begin`
`        if (NewAnalysisViewCode <> '') and (NewAnalysisViewCode <> Rec."Analysis View Code") then`
`            Rec."Analysis View Code" := NewAnalysisViewCode;`

`        ValidateAnalysisViewCode();`

`        AnalysisByDimUserParam.Load(Rec, Page::"Analysis by Dimensions");`

`       LineDimCode := DimOptionToDimCode(Rec."Line Dim Option");`
`        ColumnDimCode := DimOptionToDimCode(Rec."Column Dim Option");`

`        GLSetup.Get();`
`        if GLSetup."Additional Reporting Currency" <> '' then`
`            Currency.Get(GLSetup."Additional Reporting Currency");`

`        if GLAccountSource then begin`
`            Field.Get(DATABASE::"G/L Account", 42);`
`            BusUnitFilterCaption := Field."Field Caption";`
`        end;`

`       FindPeriod('');`

`       CreateCaptionSet(TempDimensionCodeBuffer, Step::First, 32, PrimaryKeyFirstColInSet, ColumnCaptions, Rec."Column Set");`
`    end;`

**Comment by AndersLarsenMicrosoft** [comment]
Sorry for the late reply is this request still relevant then please create a new event request however is seems more like a "Change" or a "bug" request
