### ISSUE TITLE
[Event Parameter Request] Report 99003803 Copy Production Forecast - procedure ShowConfirm - event OnBeforeShowConfirm

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#22551]
We would like the Parameter/-s Confirmed added to the following event.

Report 99003803 Copy Production Forecast - procedure ShowConfirm - event OnBeforeShowConfirm

Original:

```
Report 99003803 Copy Production Forecast - procedure ShowConfirm - event OnBeforeShowConfirm

OnBeforeShowConfirm(IsHandled);

[IntegrationEvent(false, false)]
local procedure OnBeforeShowConfirm(var IsHandled: Boolean)
begin
end;
```

Change:

```
OnBeforeShowConfirm(IsHandled, Confirmed); // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnBeforeShowConfirm(var IsHandled: Boolean; var Confirmed: Boolean) // <-- ADDED
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10818.
