### ISSUE TITLE
[extensibility-bug] VAT Date not considered in table 11021 "Sales VAT Advance Notif." in Elster

### ISSUE THREAD

**Issue by BjEic** [microsoft/ALAppExtensions#22558]
In procedure CalcLineTotal(VATStmtLine2: Record "VAT Statement Line"; Level: Integer): Boolean of table 11021 "Sales VAT Advance Notif." type "Account Totaling" goes to "Posting Date" in GLAccount."Net Change" instead of "VAT Date" (line 555).

This causes wrong vat statements in Germany

**Comment by BjEic** [comment]
Hi @AlexanderYakunin,
are the ary news in this case?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10741.
