### ISSUE TITLE
[Event Request] On codeunit 1250 & 1252 function "ShowMatchSummary" just like codeunit 1255

### ISSUE THREAD

**Issue by iambjaved** [microsoft/ALAppExtensions#22567]
Hello,
 Codeunit 1250 & 1252 should have same overridden pattern as codeunit 1255. We need event in "ShowMatchSummary" function to suppress message dialog. Same event is already defined in codeunit 1255 but not available in 1250 & 1252.
 
 Codeunit 1252:
![codeunit 1252](https://user-images.githubusercontent.com/42057055/225122561-5c84b330-de1c-43be-879e-a89e04f7f477.jpg)

Codeunit 1250:
![Codeunit 1250](https://user-images.githubusercontent.com/42057055/225122759-e6c5b89c-9682-461c-a85c-bf9ad99ebb6d.jpg)

Codeunit 1255: This is how we like to have in Codeunit 1252 & 1250. Same overridden pattern.
![Codeunit 1255](https://user-images.githubusercontent.com/42057055/225123502-ae755866-8bd0-40b3-af0c-e983e3ea1f15.jpg)

Thanks.

**Comment by pri-kise** [comment]
@iambjaved in general it's better if you split your requests into one issue per request.
Additional it is better if you add the requested event signature as text, that can be easy copied instead of only some screenshots.

The better you prepare your request, the faster they can be implemented by someone of microsoft.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10846.
