### ISSUE TITLE
Navigate page OnFindRecordsOnOpenOnAfterSetDocuentFilters 

### ISSUE THREAD

**Issue by twbook** [microsoft/ALAppExtensions#22569]
On the Navigate page we have an event:
OnFindRecordsOnOpenOnAfterSetDocuentFilters 

this allows us to set the DocNoFilter as a var however the line of code after if clears it out 

`OnFindRecordsOnOpenOnAfterSetDocuentFilters(Rec, DocNoFilter, PostingDateFilter, ExtDocNo, `NewSourceRecVar);`
 `DocNoFilter := `'';`
  
Can the code that clears the DocNoFilter  be removed?

**Comment by AlexanderYakunin** [comment]
This is already fixed

                ClearContactInfo();
                ClearTrackingInfo();
                OnFindRecordsOnOpenOnAfterSetDocuentFilters(Rec, DocNoFilter, PostingDateFilter, ExtDocNo, NewSourceRecVar);
                FindRecords();
