### ISSUE TITLE
[Event Request] Codeunit 90 - Purch.-Post - DeleteItemChargeAssgnt

### ISSUE THREAD

**Issue by obermeiersinghammer** [microsoft/ALAppExtensions#22562]
New Publisher OnAfterDeleteItemChargeAssgnt(PurchHeader: Record "Purchase Header")

![image](https://user-images.githubusercontent.com/63410340/225024826-2c3079b8-a0e6-4c4f-989c-b1d91bfb9ab5.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11007.
