### ISSUE TITLE
[platform bug] Table 2000000141 Table Relations Metadata

### ISSUE THREAD

**Issue by bgestel** [microsoft/ALAppExtensions#22572]
Hi,  This bug isn't intuitive so it needs you to have an open mind ;) .

### part 1
The merge customer functionality on the customer card Merges two customers and then loops thru the Table 2000000141 to look for references to this customer so it can update them with the new merged customer no.  This happens in table 64 "Merge Duplicates Buffer" - FindRelatedFields() .

### part 2
Add an Extension to your environment that uses an external table connected to CRM (https://learn.microsoft.com/en-us/dynamics-nav/external-tables)   Notice that this table has no relation to Customer or contact or any table for ex:

table 50101 "DemoTableFDW"
{
    DataClassification = CustomerContent;
    TableType = CDS;
    
    fields
    {
        field(1; DemoField; Decimal)
        {
            DataClassification = CustomerContent;
            Caption = 'Demo Field';            
            DecimalPlaces = 0 : 5;
        }
    }
    
    keys
    {
        key(PK; DemoField)
        {
            Clustered = true;
        }
    }    
}

### part 3
make sure the Dataverse connection in your company is **disabled** , Try to merge a customer with the functionality in part 1.  Notice that this works as expected

### part 4

modify the external table from part 2 by adding a captionclass property to it

table 50101 "DemoTableFDW"
{
    DataClassification = CustomerContent;
    TableType = CDS;
    
    fields
    {
        field(1; DemoField; Decimal)
        {
            DataClassification = CustomerContent;
            Caption = 'Demo Field';
            CaptionClass = '70241646,1,' + Rec.FieldCaption(DemoField);
            DecimalPlaces = 0 : 5;
        }
    }
    
    keys
    {
        key(PK; DemoField)
        {
            Clustered = true;
        }
    }    
}

### part 5

repeat the merge customer as described in part 3 =>  now you will get an error  "Table connection for table type CRM must be registered using RegisterTableConnection ..." .  The call stack is showing that this error is thrown by calling .next on that table 2000000141   mentioned in part 1

### the Issue
We think it's a bug that iterating thru table 2000000141 , tries to instantiate a copy of table 50101 (part4) , when there is no relation between them whatsoever .  Even stanger , it only tries to do this when there is a captionclass property in the table 50101.
We expect this is an oversight in the implementation of virtual table 2000000141  in the platform. 

With kind regards

Bert Van Gestel

**Comment by AlexanderYakunin** [comment]
Hi! Please take a minute to read the guidelines for this repository https://github.com/microsoft/AL and our collection of frequently asked questions https://github.com/Microsoft/AL/wiki/frequently-Asked-Questions .
This repository is only for extensibility requests for Dynamics 365 Business Central. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
•	On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
•	On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by bgestel** [comment]
Hi @AlexanderYakunin , it was the support engineer who asked me to put it here .

**Comment by AlexanderYakunin** [comment]
Very strange, as we are not working with bugs here, but only do extensibility requests. I expect support to create bug for Platform in such case.
