### ISSUE TITLE
[Event Request] Codeunit 925 - Assembly Header-Reserve - OnBeforeDeleteLine

### ISSUE THREAD

**Issue by UIBKH** [microsoft/ALAppExtensions#22575]
Dear Support,

We would like to add a new event OnBeforeDeleteLine in the following function. This would allow us to further customize the code and migrate existing customizations.

    procedure DeleteLine(var AssemblyHeader: Record "Assembly Header")
    begin
        with AssemblyHeader do begin
            OnBeforeDeleteLine(AssemblyHeader); //New Code --++
            ReservMgt.SetReservSource(AssemblyHeader);
            if DeleteItemTracking then
                ReservMgt.SetItemTrackingHandling(1); // Allow Deletion
            ReservMgt.DeleteReservEntries(true, 0);
            ReservMgt.ClearActionMessageReferences();
            CalcFields("Reserved Qty. (Base)");
            AssignForPlanning(AssemblyHeader);
        end;
    end;

Event signature:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteLine(AssemblyHeader: Record "Assembly Header")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10845.
