### ISSUE TITLE
Сreate Event Request Table 37 "Sales Line" OnGetDefaultBinAfterWMSExtendedMgt

### ISSUE THREAD

**Issue by VladimirTkalich** [microsoft/ALAppExtensions#22570]
Hello, could you please create OnGetDefaultBinAfterWMSExtendedMgt event in the GetDefaultBin procedure in the table 37 "Sales Line"?

IntegrationEvent(false, false)]
local procedure OnGetDefaultBinAfterWMSExtendedMgt (var SalesLine: Record "Sales Line")
begin
end;

    procedure GetDefaultBin()
    var
        WMSManagement: Codeunit "WMS Management";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetDefaultBin(Rec, IsHandled);
        if IsHandled then
            exit;

        if (Type <> Type::Item) or IsNonInventoriableItem() then
            exit;

        "Bin Code" := '';
        if "Drop Shipment" then
            exit;

        if ("Location Code" <> '') and ("No." <> '') then begin
            GetLocation("Location Code");
            if Location."Bin Mandatory" and not Location."Directed Put-away and Pick" then begin
                if ("Qty. to Assemble to Order" > 0) or IsAsmToOrderRequired() then
                    if GetATOBin(Location, "Bin Code") then
                        exit;

                if not IsShipmentBinOverridesDefaultBin(Location) then begin
                    WMSManagement.GetDefaultBin("No.", "Variant Code", "Location Code", "Bin Code");
                    OnGetDefaultBinAfterWMSExtendedMgt (Rec);     /// NEW EVENT
                    HandleDedicatedBin(false);
                end;
            end;
        end;

        OnAfterGetDefaultBin(Rec);
    end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56629.
