### ISSUE TITLE
Table 5077 Segment Line - new function GetComments

### ISSUE THREAD

**Issue by rvicenteADV** [microsoft/ALAppExtensions#22576]
Please add new function in Segment Line table.

    procedure GetComments(var InterLogEntryCommentLine: Record "Inter. Log Entry Comment Line" temporary)
    begin
        InterLogEntryCommentLine.DeleteAll();

        if TempInterLogEntryCommentLine.FindSet() then
            repeat
                InterLogEntryCommentLine := TempInterLogEntryCommentLine;
                InterLogEntryCommentLine.Insert();
            until TempInterLogEntryCommentLine.Next() = 0;
    end;

Thank you!

**Comment by pri-kise** [comment]
@rvicenteADV could you please elaborate why this procedure should be added and would you be willing to contribute this enhancement (including a test) to the BaseApp by yourself?

@JesperSchulz is this some improvement that could be added via the BaseApp Contribution Pilot?

**Comment by rvicenteADV** [comment]
Hi,
I need to assign TempInterLogEntryCommentLine, it might also be valid to change it as protected. You tell me if I need to do a test.

Thank you.
