### ISSUE TITLE
[Event Request] Codeunit 415 - "Release Purchase Document" - OnCodeOnAfterPurchLineSetFilters

### ISSUE THREAD

**Issue by HendrikSittner** [microsoft/ALAppExtensions#22583]
Dear ALAppExtensions team,

through this issue we would like to request adding a parameter to event publisher `OnCodeOnAfterPurchLineSetFilters` in Codeunit 415 "Release Purchase Document" with the following signature:

```al
[IntegrationEvent(false, false)]
local procedure OnCodeOnAfterPurchLineSetFilters(PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
begin
end;
```

which would be used to control the execution of functionality related to `PurchLine.Find('-')` in procedure `CheckPurchLines` (comparable to the corresponding Event in Codeunit `Release Sales Document`) as follows:

```al
local procedure CheckPurchLines(var PurchLine: Record "Purchase Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckPurchLines(PurchaseHeader, PurchLine, IsHandled);
        if IsHandled then
            exit;

        PurchLine.SetRange("Document Type", PurchaseHeader."Document Type");
        PurchLine.SetRange("Document No.", PurchaseHeader."No.");
        PurchLine.SetFilter(Type, '>0');
        PurchLine.SetFilter(Quantity, '<>0');
        // >>>OLD>>>
        // OnCodeOnAfterPurchLineSetFilters(PurchaseHeader, PurchLine)
        // <<<OLD<<<
        // >>>NEW>>>
        IsHandled := false;
        OnCodeOnAfterPurchLineSetFilters(PurchaseHeader, PurchLine, IsHandled);
        if not IsHandled then
        // <<<NEW<<<
            if not PurchLine.Find('-') then
                Error(Text001, PurchaseHeader."Document Type", PurchaseHeader."No.");

        CheckMandatoryFields(PurchLine);
    end;
```

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11076.
