### ISSUE TITLE
[Event Request] Codeunit 7308 Replenishment - Function "ReplenishBin" - New Event OnBeforeReplenishBin

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#22582]
procedure ReplenishBin(ToBinContent: Record "Bin Content"; AllowBreakBulk: Boolean)
    var
        IsHandled: Boolean < ---- new event
    begin
        IsHandled := false; < ---- new event
        OnBeforeReplenishBin(ToBinContent, IsHandled, RemainQtyToReplenishBase, AllowBreakBulk); < ---- new event
        if IsHandled then < ---- new event
            exit; < ---- new event
            
        with ToBinContent do begin
            if not Fixed then
                FieldError(Fixed, StrSubstNo(Text000, FieldCaption(Fixed)));

            if BinBlockedInbound("Location Code", "Bin Code") then
                Bin.FieldError("Block Movement", StrSubstNo(Text000, Bin."Block Movement"));

            if not NeedToReplenish(0) then
                exit;

            RemainQtyToReplenishBase := CalcQtyToReplenish(0);
            if RemainQtyToReplenishBase <= 0 then
                exit;

            FindReplenishmtBin(ToBinContent, AllowBreakBulk);
        end;
    end;

    [IntegrationEvent(true, false)]
    local procedure OnBeforeReplenishBin(ToBinContent: Record "Bin Content";  var IsHandled: Boolean; RemainQtyToReplenishBase: Decimal; AllowBreakBulk: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10845.
