### ISSUE TITLE
[EVENT REQUEST] Codeunit 396 - SaveNoSeries- OnBeforeSaveNoSeries

### ISSUE THREAD

**Issue by UshakovIlya** [microsoft/ALAppExtensions#22585]
//Please, add event OnBeforeSaveNoSeries(LastNoSeriesLine, IsHandled), variable IsHandled and condition for IsHandled before "if LastNoSeriesLine."Series Code" <> '' then begin" in SaveNoSeries procedure

    procedure SaveNoSeries()
      var
	  IsHandled : boolean;
      begin

	  IsHandled := false;
	  OnBeforeSaveNoSeries(LastNoSeriesLine, IsHandled);
	  if IsHandled then
	    exit;

          if LastNoSeriesLine."Series Code" <> '' then begin
              if LastNoSeriesLine."Allow Gaps in Nos." then
                  if (LastNoSeriesLine."Last No. Used" <> '') and (LastNoSeriesLine."Last No. Used" > 
                LastNoSeriesLine.GetLastNoUsed()) then begin
                      LastNoSeriesLine.TestField("Sequence Name");
                      if NumberSequence.Exists(LastNoSeriesLine."Sequence Name") then
                          NumberSequence.Delete(LastNoSeriesLine."Sequence Name");
                      LastNoSeriesLine."Starting Sequence No." := 
                LastNoSeriesLine.ExtractNoFromCode(LastNoSeriesLine."Last No. Used");
                      LastNoSeriesLine.CreateNewSequence();
                  end;
              if not LastNoSeriesLine."Allow Gaps in Nos." or UpdateLastUsedDate then
                  ModifyNoSeriesLine(LastNoSeriesLine);
          end;
          OnAfterSaveNoSeries(LastNoSeriesLine);
      end;

     [IntegrationEvent(false, false)]
         local procedure OnBeforeSaveNoSeries(var NoSeriesLine: Record "No. Series Line"; var IsHandled: Boolean)
         begin
         end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10846.
