### ISSUE TITLE
[Event Request] Table 254 VAT Entry OnAfterCopyFromGenJnlLine

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/ALAppExtensions#22595]
Hello,

This event is set to Scope 'OnPrem'
please open it for Cloud development.

Best Regards
Bernhard Kloibmüller

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10893.
