### ISSUE TITLE
[Parameter] codeunit 6620 "Copy Document Mgt." - OnCopyArchSalesLineOnAfterToSalesLineInsert

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#22590]
After insertion of a new sales line copied from another sales line, we can add extra lines and update the `NextLineNo` via below publisher.

`OnAfterInsertToSalesLine(ToSalesLine, FromSalesLine, RecalculateLines, DocLineNo, FromSalesDocType, FromSalesHeader, NextLineNo);`

After insertion of a new sales line copied from another sales **archive** line, we can add extra lines but **NOT** set the `NextLineNo` via below publisher.

`OnCopyArchSalesLineOnAfterToSalesLineInsert(ToSalesLine, FromSalesLineArchive, RecalculateLines);`

Please add NextLineNo (var) to below publisher

```
[IntegrationEvent(false, false)]
    local procedure OnCopyArchSalesLineOnAfterToSalesLineInsert(var ToSalesLine: Record "Sales Line"; FromSalesLineArchive: Record "Sales Line Archive"; RecalculateLines: Boolean; var NextLineNo: Integer)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10804.
