### ISSUE TITLE
[event question] page 6510 "Item Tracking Lines" with event used twice inside completely different procedures?!?

### ISSUE THREAD

**Issue by thomashoesel** [microsoft/ALAppExtensions#22597]
Hello,
is it really on purpose that event **OnAfterCopyTrackingSpec**(TrackingSpecification, TrackingSpecification) is used in page 6510 "Item Tracking Lines" of Microsoft_Base Application_21.2.49946.49990 inside procedure **RegisterChange** and inside procedure **RegisterItemTrackingLines** as well?

Edit: And there's another one (**OnAfterClearTrackingSpec**) in the same object, called from an if ... and an else-branch as well. So you'll have to decide the if ... again in your extension?

I just wonder and I wanna make sure it's called at the right time ...

**Comment by alexei-dobriansky** [comment]
I was trying to find the commit that added those events, but this happened before version 11.0.
I see there are plenty of subscribers now, so we can't remove any of their occurrences.
