### ISSUE TITLE
[Event Request] Codeunit 12 - "Gen. Jnl.-Post Line" - OnBeforePostCust

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#22608]
Dear ALAppExtensions team,

through this issue we would like to request adding a new event publisher `OnBeforePostCust` in Codeunit 12 "Gen. Jnl.-Post Line" with the following signature:
```AL
[IntegrationEvent(false,false)]
local procedure OnBeforePostCust(var GenJnlLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
begin
end;
```
which would be called as follows in `PostCust`:
```AL
local procedure PostCust(var GenJnlLine: Record "Gen. Journal Line"; Balancing: Boolean)
var
    LineFeeNoteOnReportHist: Record "Line Fee Note on Report Hist.";
    Cust: Record Customer;
    CustPostingGr: Record "Customer Posting Group";
    CustLedgEntry: Record "Cust. Ledger Entry";
    CVLedgEntryBuf: Record "CV Ledger Entry Buffer";
    TempDtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer" temporary;
    DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry";
    SalesSetup: Record "Sales & Receivables Setup";
    ReceivablesAccount: Code[20];
    DtldLedgEntryInserted: Boolean;
    ShouldCheckDocNo: Boolean;
    // >>>> New >>>>>>>>>>>>>>>>
    IsHandled: Boolean;
    // <<<< New <<<<<<<<<<<<<<<<
begin
    // >>>> New >>>>>>>>>>>>>>>>
    IsHandled := false;
    OnBeforePostCust(GenJnlLine,IsHandled);
    if IsHandled then
        exit;

    // <<<< New <<<<<<<<<<<<<<<<
    SalesSetup.Get();
...
end;
```
Thanks in advance!

**Comment by AlexanderYakunin** [comment]
Please explain why do you need replacement for one of the major procedures in Gen. Jnl.-Post Line?

**Comment by KrunoslavPipic** [comment]
Hi @AlexanderYakunin and @tkr95 

Could you please reopen this case?

We have a user request wherein the user desires a custom modification to enable the entry of multiple payment methods on the invoice. Additionally, they would like each payment method to generate a separate entry in both the Customer Ledger Entry and Detailed Customer Ledger Entry tables.

I can see that events exists in other procedures in this codeunit: 
PostVend:
IsHandled := false;
      OnBeforePostVend(GenJournalLine, IsHandled);
      if IsHandled then
          exit;
           
PostBankAcc:
IsHandled := false;
      OnBeforePostBankAcc(GenJnlLine, IsHandled);
      if IsHandled then
          exit;

PostICPartner: 
IsHandled := false;
      OnBeforePostICPartner(GenJnlLine, IsHandled);
      if IsHandled then
          exit;
