### ISSUE TITLE
[Event Request] CodeUnit 99000886 - "Capable to Promise" - OnBeforeCheckTransferShptCTP

### ISSUE THREAD

**Issue by FGRKH** [microsoft/ALAppExtensions#22611]
Dear Support,

We would like to add a new event OnBeforeCheckTransferShptCTP in the following Procedure using the IsHandled pattern.
This would allow us to further customize the code and migrate existing customizations.

    local procedure CheckTransferShptCTP(ReqLine: Record "Requisition Line"; PeriodType: Enum "Analysis Period Type"): Boolean
    var
        Item: Record Item;
        RequisitionLine: Record "Requisition Line";
        DueDateOfReqLine: Date;
        IsHandled: Boolean;  //New  Code --++
    begin
        //New  Code --
        IsHandled := false;
        OnBeforeCheckTransferShptCTP(ReqLine, PeriodType, IsHandled);
        if IsHandled then
           exit;
        //New  Code ++
        with ReqLine do begin
            TestField("Replenishment System", "Replenishment System"::Transfer);
            Item.Get("No.");
            if Item.Critical then
                if not
                   ValidateCapableToPromise(
                     RequisitionLine, "No.", "Variant Code", "Transfer-from Code", "Transfer Shipment Date",
                     Quantity, "Unit of Measure Code", PeriodType, DueDateOfReqLine)
                then begin
                    OrderPromisingLineNo := OrderPromisingLineNo - 1;
                    exit(false);
                end;
        end;
        exit(true);
    end;

Event Signature:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckTransferShptCTP(ReqLine: Record "Requisition Line"; PeriodType: Enum "Analysis Period Type"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10845.
