### ISSUE TITLE
Event Request codeunit 99000856 "Planning Transparency" OnPublishSurplusOnBeforePlanningElementInsert

### ISSUE THREAD

**Issue by zhan-dev** [microsoft/ALAppExtensions#22617]
Hello, could you please add IsHandled to exist event OnPublishSurplusOnBeforePlanningElementInsert before PlanningElement.Insert();?

```
if not IsHandled then // new change
PlanningElement.Insert();

[IntegrationEvent(false, false)]
    local procedure OnPublishSurplusOnBeforePlanningElementInsert(var UntrackedPlanningElement: Record "Untracked Planning Element"; var IsHandled: Boolean) // new change
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10846.
