### ISSUE TITLE
[Code Refactoring] TAB 36 - InitRecord > GetPostingNoSeriesForInvoice

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#2261]
In the BE localisation, the No Series for sales invoices is taken from the Journal Template instead of the Sales Setup. We've made a customisation to skip the Journal Template approach (via a setting) and use the sales setup (=W1 behavior) instead. 

The only change we need is to modify 
`NoSeriesMgt.SetDefaultSeries("Posting No. Series",GenJournalTemplate."Posting No. Series");`
to
`NoSeriesMgt.SetDefaultSeries("Posting No. Series",SalesSetup."Posted Invoice Nos."); //NVTBE        `
We can achieve this with events, but need to copy quit some code. 

![image](https://user-images.githubusercontent.com/25268332/57091447-82512500-6d09-11e9-96f1-3a1fece223d4.png)

It would be better if we (and in future to support W1 / BE with a same codebase) could just have something like

`NoSeriesMgt.SetDefaultSeries("Posting No. Series",GetPostingNoSeriesForInvoice);`

GetPostingNoSeriesForInvoice would get the journal template, and have an OnBefore publisher with Handled pattern. Same applies for creditnotes and for T38.

PS: Even better would be to move away from the W1 / BE distinction and provide native support for both NoSeries via Journal Templates and Sales Setup.

**Comment by AlexanderYakunin** [comment]
We still have a plan to align BE to W1, but this is large refactoring and we cannot make it now. Please stay with you solution until we will be able to complete this work.
