### ISSUE TITLE
Button on page Extension Management (2500, List) missing elipsis

### ISSUE THREAD

**Issue by guidorobben** [microsoft/ALAppExtensions#22615]
Button Upload extension is missing elipsis property.

![image](https://user-images.githubusercontent.com/11609736/225912787-a7d6fe1f-1681-4b05-907d-c99f3d3dc621.png)

**Comment by JesperSchulz** [comment]
Fixed in 22.3.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10887.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 57217.
