### ISSUE TITLE
[Event-change Request] Codeunit 12- "Gen. Jnl.-Post Line" - OnPostCustOnBeforeTempDtldCVLedgEntryBufCopyFromGenJnlLine

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#22614]
Dear ALAppExtensions team,

through this issue we would like to request a change of event publisher `OnPostCustOnBeforeTempDtldCVLedgEntryBufCopyFromGenJnlLine` in Codeunit 12 "Gen. Jnl.-Post Line` from:
```AL
[IntegrationEvent(true, false)]
local procedure OnPostCustOnBeforeTempDtldCVLedgEntryBufCopyFromGenJnlLine(var GenJournalLine: Record "Gen. Journal Line"; var CustLedgEntry: Record "Cust. Ledger Entry"; var Cust: Record Customer; GLReg: Record "G/L Register")
begin
end;
```
to:
```AL
[IntegrationEvent(true, false)]
local procedure OnPostCustOnBeforeTempDtldCVLedgEntryBufCopyFromGenJnlLine(var GenJournalLine: Record "Gen. Journal Line"; var CustLedgEntry: Record "Cust. Ledger Entry"; var Cust: Record Customer; GLReg: Record "G/L Register"; var CVLedgEntryBuf: Record "CV Ledger Entry Buffer")
begin
end;
```
adding the var parameter CVLedgEntryBuff which would be implemented as follows in `PostCust`:
```AL
OnPostCustOnBeforeTempDtldCVLedgEntryBufCopyFromGenJnlLine(GenJnlLine, CustLedgEntry, Cust, GLReg, CVLedgEntryBuf);
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11010.
