### ISSUE TITLE
[Code Refactoring / Event Request] T38 - SetPostingDescription

### ISSUE THREAD

**Issue by fvet** [Microsoft/ALAppExtensions#2262]
In table 38, function InitRecord, we've changed line 

`"Posting Description" := FORMAT("Document Type") + ' ' + "No.";`

to 

`"Posting Description" := COPYSTR(FORMAT("Document Type"), 1, MAXSTRLEN("Posting Description") - STRLEN("No.") - 1)  + ' ' + "No.";`

Reason is an added 'Document Type' option that - once translated - can exceed 29 chars (Purchase Settlement Proposal Invoice). Given 29 chars for the doc. type + 1 space + 'No.' (20) is the maxlength of 50, (the last) part of the No. value is truncated in the posting description if our document type translation exceeds 29.

Solutions: 
- Extend 'posting description' (100?)
- update standard code to the copystr construction above
- Move code to a Setpostingdescription function, with OnBefore publisher and Handled pattern.

**Comment by SirBETE** [comment]
FYI: Posting description is already extended to text 100 in BC14.

**Comment by fvet** [comment]
@SirBETE Thanks for pointing me out, didn't check it on BC14 :(
Issue can be ignored.
