### ISSUE TITLE
[Events Request] Table 37 "Sales Line" procedure GetDate - OnBeforeGetDate 

### ISSUE THREAD

**Issue by ACJStopka** [microsoft/ALAppExtensions#22624]
procedure GetDate() ResultDate: Date
    var
        IsHandled: Boolean; 
    begin
        IsHandled := false;
        OnBeforeGetDate(ResultDate, IsHandled);
        if IsHandled then
            exit(ResultDate);

        GetSalesHeader();
        if SalesHeader."Posting Date" <> 0D then
            exit(SalesHeader."Posting Date");
        exit(WorkDate());
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetDate(var ResultDate: Date; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56629.
