### ISSUE TITLE
[Request for External] Codeunit 7380 "Phys. Invt. Count Management" - make SortingMethod protected

### ISSUE THREAD

**Issue by srol001195** [microsoft/ALAppExtensions#22622]
Dear ALAppExtensions,

We would like to request the following var as **protected** so it can be accessed through event subscribers:

```
    // var
    protected var
        SortingMethod: Option " ",Item,Bin;
```

Thank you,
SR

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot use protected in codeunits, only in pages and tables. See:

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-protected-variables
