### ISSUE TITLE
[Request for External] Table 5902 "Service Line" - UpdateRemainingCostsAndAmounts

### ISSUE THREAD

**Issue by srol001195** [microsoft/ALAppExtensions#22621]
Dear ALAppExtensions,

Please consider **removing** the **local** modifier from **UpdateRemainingCostsAndAmounts** on **Service Line**. We wish to be able to use this function in our extension triggers.

```
// local procedure UpdateRemainingCostsAndAmounts()
procedure UpdateRemainingCostsAndAmounts()
```

Thank you,
SR

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10221.
