### ISSUE TITLE
Request event in codeunit 12 "Gen. Jnl.-Post Line" 

### ISSUE THREAD

**Issue by Shortlife79** [microsoft/ALAppExtensions#22630]
In codeunit 12 "Gen. Jnl.-Post Line" I want to have an extra event publisher, because our customer is having troubles with securityfiltering.  In this certain code
we need to add following line in het event subscriber, before the findlast : DtldCVLedgEntryBuf.SecurityFiltering := DtldCVLedgEntryBuf.securityfiltering::ignored;

DtldCVLedgEntryBuf.SecurityFiltering := DtldCVLedgEntryBuf.securityfiltering::ignored;

codeunit 12 "Gen. Jnl.-Post Line"

procedure PostDtldVendLedgEntries(GenJnlLine: Record "Gen. Journal Line"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; VendPostingGr: Record "Vendor Posting Group"; LedgEntryInserted: Boolean) DtldLedgEntryInserted: Boolean
    var
        TempDimPostingBuffer: Record "Dimension Posting Buffer" temporary;
        DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry";
        AdjAmount: array[4] of Decimal;
        DtldVendLedgEntryNoOffset: Integer;
        SaveEntryNo: Integer;
        IsHandled: Boolean;
    begin
        if GenJnlLine."Account Type" <> GenJnlLine."Account Type"::Vendor then
            exit;

==> PostDtldVendLedgEntries_OnBeforeFindLastDtldVendLedgEntry(DtldVendLedgEntry);

        if DtldVendLedgEntry.FindLast then
            DtldVendLedgEntryNoOffset := DtldVendLedgEntry."Entry No."
        else
            DtldVendLedgEntryNoOffset := 0;

Event signature:

    [IntegrationEvent(false, false)]
    local procedure PostDtldVendLedgEntries_OnBeforeFindLastDtldVendLedgEntry(var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer")
    begin
    end;

**Comment by AlexanderYakunin** [comment]
I think you simply need to report this as request for hotfix. G/L Posting should ignore security filtering during search for next entry number.

**Comment by Shortlife79** [comment]
OK I will create a hotfix request.
