### ISSUE TITLE
[Expose Function] TAB 295 Reminder Header - InsertTextLines

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#2263]
We want to modify 'InsertEndTexts' to print the 'not due' amounts before the end text.

Code below can be managed via the 'OnBeforeInsertEndTexts' subscriber.

```
ReminderLevel.SETRANGE("Reminder Terms Code",ReminderHeader."Reminder Terms Code");
ReminderLevel.SETRANGE("No.",1,ReminderHeader."Reminder Level");
IF ReminderLevel.FINDLAST THEN BEGIN
  ReminderText.SETRANGE(
    "Reminder Terms Code",ReminderHeader."Reminder Terms Code");
  ReminderText.SETRANGE("Reminder Level",ReminderLevel."No.");
  ReminderText.SETRANGE(Position,ReminderText.Position::Ending);
  ReminderLine.RESET;
  ReminderLine.SETRANGE("Reminder No.",ReminderHeader."No.");
  //NVTBE-0086/End text after overdue entries/Begin
  //ReminderLine.SETFILTER(
  //  "Line Type",'%1|%2|%3',
  //  ReminderLine."Line Type"::ReminderLine,
  //  ReminderLine."Line Type"::"Additional Fee",
  //  ReminderLine."Line Type"::Rounding);
  ReminderLine.SETFILTER(
    "Line Type",'%1|%2|%3|%4',
    ReminderLine."Line Type"::"Reminder Line",
    ReminderLine."Line Type"::"Additional Fee",
    ReminderLine."Line Type"::Rounding,
    ReminderLine."Line Type"::"Not Due");
  //NVTBE-0086/End
  IF ReminderLine.FINDLAST THEN

```

However, we'd like to have access in the OnBeforeInsertEndTexts to call the  'InsertTextLines' function. Putting it to external is one thing, but please also provide parameters to pass the ReminderText, NextLineNo, LineSpacing values (instead of the current Global variables)

**Comment by AlexanderYakunin** [comment]
Events should be LOCAL. We do not expose events, we can only expose functions. I will provide another solution for this ask.

**Comment by fvet** [comment]
Maybe I was not clear enough in my request:
- Please set **function** 'InsertTextLines' to **External**
- Please remove the dependencies from global variables in 'InsertTextLines' and aad ReminderText, NextLineNo, LineSpacing as function parameters instead
- No need to change the OnBeforeInsertEndTexts event

**Comment by fvet** [comment]
@AlexanderYakunin any update if we could have InsertTextLines exposed as External?

**Comment by fvet** [comment]
@AlexanderYakunin Sorry for the bump up. 
Any chance of have this included as part of the next major update (BC 16)?

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by fvet** [comment]
@AlexanderYakunin How should we interprete the 'ships-in-future-update' labels of the bc-ghost updates '_current version or in the next major release_' ...

I'm especially interested in knowing if this has been fixed in the upcoming BC 16 cumulative update, or if I have to raise a support ticket to backport the fix, without actually having to investigate issue by issue.
