### ISSUE TITLE
[Event Request] Table 904 - UpdateAsm

### ISSUE THREAD

**Issue by GOB-Andrea** [microsoft/ALAppExtensions#2264]
Hi,
please add a publisher in function "UpdateAsm" in table "Assemble-to-Order Link" as follows:
(...)
// >>> new Code
`OnBeforeSynchronizeAsmFromSalesLine(Rec,AsmHeader,NewSalesLine);`
// <<< new Code
`SynchronizeAsmFromSalesLine(NewSalesLine);`
`INSERT;`
(...)

**Comment by ThomasBrodkorb** [comment]
Is it possible to request an update to this event? It is quite useless as long as the "AsmHeader" parameter is not defined as VAR.
