### ISSUE TITLE
[Event Request] Codeunit 1000 "Job Calculate WIP" - Add  an event with handled parameter in InsertWIPGL procedure

### ISSUE THREAD

**Issue by KuljitSinghParmar** [microsoft/ALAppExtensions#22646]
Hi Team ,

In Codeunit 1000 , we need to post the GL line separately in the procedure InsertWIPGL ,one line with Account and other with balancing account assigned . we need to do this because we need to assign different dimension for Account and Balancing account lines. Also need to have "JobWIPGLEntry" parameter passed into procedure InsertWIPGL so that we can get some values related to job in this procedure. 

local procedure InsertWIPGL(AccNo: Code[20]; BalAccNo: Code[20]; JnlPostingDate: Date; JnlDocNo: Code[20]; SourceCode: Code[10]; GLAmount: Decimal; JnlDescription: Text[100]; JobNo: Code[20]; JobWIPGLEntryDimSetID: Integer; **JobWIPGLEntry :Record "Job WIP G/L Entry"**)
var Handled : Boolean;
begin
  OnBeforeInsertWIPGL(AccNo, BalAccNo, JnlPostingDate, JnlDocNo, SourceCode, GLAmount, JnlDescription, JobNo, 
                                      JobWIPGLEntryDimSetID , **Handled , JobWIPGLEntry**)
  if Handled then 
     exit;
end 
    
 [IntegrationEvent(false, false)]
 local procedure OnBeforeInsertWIPGL(AccNo: Code[20]; BalAccNo: Code[20]; JnlPostingDate: Date; JnlDocNo: Code[20]; SourceCode: Code[10]; GLAmount: Decimal; JnlDescription: Text[100]; JobNo: Code[20]; JobWIPGLEntryDimSetID: Integer ; var Handled: Boolean ; JobWIPGLEntry :Record "Job WIP G/L Entry")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10804.
