### ISSUE TITLE
Event Modification Request: OnAfterCheckAnalysisView - codeunit 8 AccSchedManagement

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#22645]
Please could you add an additional parameter (AnalysisView) to the OnAfterCheckAnalysisView event in codeunit 8 AccSchedManagement

    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckAnalysisView(AccSchedName: Record "Acc. Schedule Name"; ColumnLayoutName: Record "Column Layout Name";Var AnalysisView: Record "Analysis View")
    begin
    end;

    procedure CheckAnalysisView(CurrentSchedName: Code[10]; CurrentColumnName: Code[10]; TestColumnName: Boolean)
    begin
       ..........
       OnAfterCheckAnalysisView(AccSchedName, ColumnLayoutName,AnalysisView);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10853.
