### ISSUE TITLE
[Event Parameter Request] Report 499 Delete Invoiced Purch. Orders - trigger OnAfterGetRecord - event OnBeforeDeletePurchaseHeader

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#22654]
We would like the Parameter/-s IncludeSender added to the following event.

Report 499 Delete Invoiced Purch. Orders - trigger OnAfterGetRecord - event OnBeforeDeletePurchaseHeader

Original:

```
Report 499 Delete Invoiced Purch. Orders - trigger OnAfterGetRecord - event OnBeforeDeletePurchaseHeader

OnBeforeDeletePurchaseHeader("Purchase Header");

[IntegrationEvent(false, false)]
local procedure OnBeforeDeletePurchaseHeader(var PurchaseHeader: Record "Purchase Header")
begin
end;
```

Change:

```
[IntegrationEvent(true, false)]  // <-- IncludeSender true ADDED
local procedure OnBeforeDeletePurchaseHeader(var PurchaseHeader: Record "Purchase Header")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10818.
