### ISSUE TITLE
[Request for external] procedure CheckReservationEntries() in table 167 - Job

### ISSUE THREAD

**Issue by MMueller1974** [microsoft/ALAppExtensions#22669]
Dear AL AppExtensionsTeam,

can you please remove the local prefix from the procedure CheckReservationEntries() in table 167 - Job?
Old signature

```AL
local procedure CheckReservationEntries(): Boolean
```
New signature
```AL
procedure CheckReservationEntries(): Boolean
```
Thank you in advance

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10221.
