### ISSUE TITLE
Optional ask question distribute amounts in service contract

### ISSUE THREAD

**Issue by renevanbeekum** [microsoft/ALAppExtensions#22683]
Below with marked old and new tags code change in routine DistributeAmounts in table Service Contract Header and event for the change asking.

    //NEW Begin
    local procedure AskContractAmountDistribution(var Result: Integer) OK: Boolean
    var
        ContractAmountDistribution: Page "Contract Amount Distribution";
        IsHandled: Boolean;
    begin
        OK := false;
        IsHandled := false;
        OnBeforeAskContractAmountDistribution(Rec, OK, Result, IsHandled);
        if NOT IsHandled then begin
            Clear(ContractAmountDistribution);
            ContractAmountDistribution.SetValues("Annual Amount", "Calcd. Annual Amount");
            if ContractAmountDistribution.RunModal = ACTION::Yes then begin
                Result := ContractAmountDistribution.GetResult;
                OK := true;
            end;
        end;
    end;
    //NEW End

    local procedure DistributeAmounts()
    var
        OldServContractLine: Record "Service Contract Line";
        //ContractAmountDistribution: Page "Contract Amount Distribution"; OLD
        Result: Integer;
    begin
        if not "Allow Unbalanced Amounts" then begin
            ServContractLine.Reset();
            ServContractLine.SetRange("Contract Type", "Contract Type");
            ServContractLine.SetRange("Contract No.", "Contract No.");
            if not ServContractLine.Find('-') and ("Annual Amount" <> 0) then
                Error(Text058);
            CalcFields("Calcd. Annual Amount");
            if "Annual Amount" <> "Calcd. Annual Amount" then begin
                ServContractLine.SetRange("Line Value", 0);
                if ServContractLine.Find('-') then
                    ServContractLine.TestField("Line Value");
                ServContractLine.SetRange("Line Value");
                if ServContractLine.Next <> 0 then begin
                    //OLD Begin
                    //Clear(ContractAmountDistribution);
                    //ContractAmountDistribution.SetValues("Annual Amount", "Calcd. Annual Amount");
                    //if ContractAmountDistribution.RunModal = ACTION::Yes then begin
                    //    Result := ContractAmountDistribution.GetResult;
                    ///OLD End
                    //NEW Begin
                    if AskContractAmountDistribution(Result) then begin
                        //NEW End
                        Currency.InitRoundingPrecision;
                        case Result of
                            0:
                                EvenDistribution(ServContractLine);
                            1:
                                ProfitBasedDistribution(ServContractLine);
                            2:
                                AmountBasedDistribution(ServContractLine);
                        end;
                        CalcFields("Calcd. Annual Amount");
                        if "Annual Amount" <> "Calcd. Annual Amount" then begin
                            ServContractLine.Validate(
                              "Line Amount",
                              ServContractLine."Line Amount" + "Annual Amount" - "Calcd. Annual Amount");
                            ServContractLine.Modify();
                        end;
                        ServContractLine.SetFilter("Line Amount", '<=0');
                        if ServContractLine.Find('-') then
                            Message(Text061, ServContractLine.FieldCaption("Line Amount"));
                    end else
                        Error('');
                end else begin
                    OldServContractLine := ServContractLine;
                    ServContractLine.Validate("Line Amount", "Annual Amount");
                    ServContractLine.Modify();
                    if ServMgtSetup."Register Contract Changes" then
                        ServContractLine.LogContractLineChanges(OldServContractLine);
                end;
            end;
        end;
    end;

    //NEW Begin
    //[IntegrationEvent(false, false)]
    local procedure OnBeforeAskContractAmountDistribution(var ServiceContractHeader: Record "Service Contract Header"; var OK: Boolean; var Result: Integer; var IsHandled: Boolean)
    begin
    end;
    //NEW End

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 57104.
