### ISSUE TITLE
[platform bug] Table 700 Error Message not properly cleaned up

### ISSUE THREAD

**Issue by Djordje-Arsic** [microsoft/ALAppExtensions#22682]
Hello,
we have encountered issues with table 700 "Error message" becoming to large due to errors related to Notification entries and Notification entry dispatcher.

Once there is one Notification Entry that cannot be sent for some reason, Job queue Notification Entry dispatcher will try sending that same notification over and over again, every few minutes or so. This leads to table Error message being populated pretty quickly, in matter of days, with millions of records. 

Even after problematic Notification Entry is fixed and is sent successfully, Error messages for that entry are not deleted. Notification Entry gets deleted and moved to Sent Notification entries, but Error messages are stuck and orphaned. 

Is there a solution for this scenario? I tried setting retention policy, but table 700 is not in the list of approved tables. 

As a workaround I added code in OnDelete() trigger of Notification Entry to find and delete Error Messages and related Error Registry. 

I was able to replicate this in v21 and v22. 
Thanks

**Comment by AlexanderYakunin** [comment]
Should you create hotfix request via technical support instead? This is not right place to report bugs.

**Comment by AlexanderYakunin** [comment]
Closing, as this is not an extensibility issue and we cannot process it here.
