### ISSUE TITLE
[Event Request] - OnBeforeServiceLineModify codeunit 5763 "Whse.-Post Shipment"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#22680]
Dear ALAppExtensions Team:

Please consider adding a new event publisher in codeunit 5763 "Whse.-Post Shipment"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnBeforeServiceLineModify(var ServiceLine: Record "Service Line"; var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var ModifyLine: Boolean; Invoice: Boolean)
begin
end;

The code in procedure "HandleServiceLine" in codeunit 5763 "Whse.-Post Shipment" would be modified as follows:

OLD CODE:

    local procedure HandleServiceLine(var WhseShptLine: Record "Warehouse Shipment Line")
    var
        ServLine: Record "Service Line";
        ModifyLine: Boolean;
    begin
        with WhseShptLine do begin
            ServLine.SetRange("Document Type", "Source Subtype");
            ServLine.SetRange("Document No.", "Source No.");
            if ServLine.Find('-') then
                repeat

         .
	 .
         .
                    if ModifyLine then
                        ServLine.Modify();
                until ServLine.Next() = 0;
        end;
    end;

NEW CODE:

    local procedure HandleServiceLine(var WhseShptLine: Record "Warehouse Shipment Line")
    var
        ServLine: Record "Service Line";
        ModifyLine: Boolean;
    begin
        with WhseShptLine do begin
            ServLine.SetRange("Document Type", "Source Subtype");
            ServLine.SetRange("Document No.", "Source No.");
            if ServLine.Find('-') then
                repeat

         .
	 .
         .

                    OnBeforeServiceLineModify(ServLine, WhseShptLine, ModifyLine, Invoice);

                    if ModifyLine then
                        ServLine.Modify();
                until ServLine.Next() = 0;
        end;
    end;
    
Thanks in advance!

**Comment by mcarmenvalera** [comment]
Hi!

Is there any news regarding this issue? I need the subscritor but I can not see it in the code for the latest version of business central.

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10820.
