### ISSUE TITLE
[Event Request] report 5405 "Calc. Consumption" - OnBeforeAssignItemTracking

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#22685]
In https://github.com/microsoft/ALAppExtensions/issues/21898 I requested the OnBeforeAssignItemTracking event. Allas the 'var' was forgotten when implementing the code in the base app. Please rectify it in the next minor 22.01 release...

Old Code:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssignItemTracking(ProdOrderComponent: Record "Prod. Order Component"; ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;

New Code:
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssignItemTracking(var ProdOrderComponent: Record "Prod. Order Component"; var ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10818.
