### ISSUE TITLE
[Event Request] Codeunit 12 - "Gen. Jnl.-Post Line" - OnBeforePostBankAcc

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#22681]
Dear ALAppExtensions team,

through this issue we would like to request adding a new event publisher `OnBeforePostBankAcc` in Codeunit 12 "Gen. Jnl.-Post Line" with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforePostBankAcc(var GenJnlLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
begin
end;
```
which would be called as follows in `PostBankAcc`:
```AL
local procedure PostBankAcc(var GenJnlLine: Record "Gen. Journal Line"; Balancing: Boolean)
var
    BankAcc: Record "Bank Account";
    BankAccLedgEntry: Record "Bank Account Ledger Entry";
    CheckLedgEntry: Record "Check Ledger Entry";
    CheckLedgEntry2: Record "Check Ledger Entry";
    BankAccPostingGr: Record "Bank Account Posting Group";
    IsHandled: Boolean;
begin
    // >>>> New >>>>>>>>>>>>>>>>
    IsHandled := false;
    OnBeforePostBankAcc(GenJnlLine, IsHandled);
    if IsHandled then
        exit;
    // <<<< New <<<<<<<<<<<<<<<<

    with GenJnlLine do begin
...
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11010.
