### ISSUE TITLE
[access request] "Payment Journal FactBox"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#22694]
Could you please change the access scope of the following global variables to protected?
```al
    protected var
        Balance: Decimal;
        TotalBalance: Decimal;
        AgeDays: Integer;
        PaymDiscDays: Integer;
        DueDays: Integer;
        OeRemainAmountFC: Decimal;
        PaymDiscDeductAmount: Decimal;
        RemainAfterPayment: Decimal;
        TotalPayAmount: Decimal;
        PmtDiscount: Decimal;
        AcceptedPaymentTol: Decimal;
        PostingDate: Date;
        DueDate: Date;
        PmtDiscDate: Date;
        PaymentAmt: Decimal;
        PaymentTerms: Code[10];
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10376.
