### ISSUE TITLE
[Access Request] page 9100 "Purchase Line FactBox" -  ShowDetails

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#22697]
Could you please change the access scope of the procedure `ShowDetails` to protected?
```al
    //+Change
    //-local procedure ShowDetails()
    protected procedure ShowDetails()
    //+Change
    var
        Item: Record Item;
    begin
        if Rec.Type = Rec.Type::Item then begin
            Item.Get(Rec."No.");
            PAGE.Run(PAGE::"Item Card", Item);
        end;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10376.
