### ISSUE TITLE
Page 99000883 CreateOrders

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/ALAppExtensions#227]
When you insert SETSELECTIONFILTER(Rec) on that line, you can plan only those lines that you had marked and want to plan and must not plan the full page full of lines:

![image](https://user-images.githubusercontent.com/42136602/44531001-028da800-a6f0-11e8-80db-fe752808cb15.png)

Can you please insert this SETSELECTIONFILTER?

**Comment by AndreiPanko** [comment]
It request to change current behavior. Currently system creates line(s) in production order(s) for all visible sales lines. After suggested change it will be for selected lines only (by default it is 1 line that is selected). It will introduces additional confusion, as before creation of order(s) system will ask if it should be Production Order per Item or per Sales Order (aka Project Order).

As work around, if you need it for your specific customer, I would suggest to subscribe for OnBeforeCreateProdOrder event and apply filter to Rec variable that is exposed in that event.
