### ISSUE TITLE
codeunit 23 "Item Jnl.-Post Batch" - PostLines function code Clearing Lot No

### ISSUE THREAD

**Issue by HFS-terryKane** [microsoft/ALAppExtensions#22709]
New code snippet introduced in object "codeunit 23 "Item Jnl.-Post Batch" function "PostLines(ItemJnlLine, PhysInvtCountMgt)" is clearing the "Lot No." field value. Thereby, has left our app functionality inoperable. There aren't any events for us to use to before or after the ItemJnlLine.CLearTracking() function. Could we either get an event onBefor and OnAfter this clearing with the ItemJnlLine previous and new ItemJnlLine Var parameters? So this way we can at least re-populate the "Lot No." field.
**BC 22:**
Microsoft_Base Application_22.0.53859.0.app
Microsoft_System Application_22.0.53859.0.app

**Code snippet that's the issue:**
`  if ItemJnlBatch."Item Tracking on Lines" then
                ItemJnlLine.CreateItemTrackingLines(false);
            ItemJnlLine.ClearTracking();
            ItemJnlLine.ClearDates();`

**Comment by HFS-terryKane** [comment]
Could we get some update on this please?

**Comment by aldobriansky** [comment]
OK, I'll add the requested event.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11127.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 57845.

**Comment by HFS-terryKane** [comment]
Awesome! This is great news! looking forward to it!
