### ISSUE TITLE
[Event Change Request] Codeunit 80 - "Sales-Post - OnBeforeCalcInvoice

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#22712]
Dear ALAppExtensions team,

through this issue we would like to request a change in the signature of the OnBeforeValidateShortcutDimCode event by adding `var` to the variable `TempSalesLineGlobal`.
old signature

```AL
local procedure OnBeforeCalcInvoice(SalesHeader: Record "Sales Header"; TempSalesLineGlobal: Record "Sales Line" temporary; var NewInvoice: Boolean; var IsHandled: Boolean)
```

new signature
```AL
local procedure OnBeforeCalcInvoice(SalesHeader: Record "Sales Header"; var TempSalesLineGlobal: Record "Sales Line" temporary; var NewInvoice: Boolean; var IsHandled: Boolean)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11007.
