### ISSUE TITLE
[Protected var request] report 38 "Trial Balance by Period"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#22716]
We would like the following variables set as protected variables in report 38 "Trial Balance by Period":

        PeriodStartingDate: Date;
        StartDate: array[20] of Date;
        EndDate: array[20] of Date;
        ColumnValuesAsText: array[13] of Text[30];
        RoundingText: Text[80];
        Header: array[13, 2] of Text[100];
        RoundingFactor: Enum "Analysis Rounding Factor";
        MaxCount: Integer;
        Indent: Option "None","0","1","2","3","4","5";

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10376.
