### ISSUE TITLE
OnValidatePostingDateOnBeforeCheckNeedUpdateCurrencyFactor and  OnValidatePostingDateOnAfterCheckNeedUpdateCurrencyFactor events for Purchase Header

### ISSUE THREAD

**Issue by yildiz-ozdemir** [microsoft/ALAppExtensions#22728]
Hi,

Can you add OnValidatePostingDateOnAfterCheckNeedUpdateCurrencyFactor and OnValidatePostingDateOnBeforeCheckNeedUpdateCurrencyFactor events in Posting Date field OnValidate code of Purchase Header table. 

![image](https://user-images.githubusercontent.com/49477543/228203822-273992a4-ff04-4b86-b344-4d263e95f301.png)

**Can you change the selected code in above jpeg like below code.**

NeedUpdateCurrencyFactor := "Currency Code" <> '';
OnValidatePostingDateOnBeforeCheckNeedUpdateCurrencyFactor(Rec, Confirmed, NeedUpdateCurrencyFactor, xRec);

if NeedUpdateCurrencyFactor then begin
                    UpdateCurrencyFactor();
                    if ("Currency Factor" <> xRec."Currency Factor") and not GetCalledFromWhseDoc() then
                        SkipJobCurrFactorUpdate := not ConfirmCurrencyFactorUpdate();
                end;

OnValidatePostingDateOnAfterCheckNeedUpdateCurrencyFactor(Rec, xRec, SkipJobCurrFactorUpdate);

**Related Integration events :**

    [IntegrationEvent(false, false)]
    local procedure OnValidatePostingDateOnBeforeCheckNeedUpdateCurrencyFactor(var PurchaseHeader: Record "PurchaseHeader"; 
    var IsConfirmed: Boolean; var NeedUpdateCurrencyFactor: Boolean; xPurchaseHeader: Record "Purchase Header")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnValidatePostingDateOnAfterCheckNeedUpdateCurrencyFactor(var PurchaseHeader: Record "Purchase Header"; 
    xPurchaseHeader: Record "Purchase Header"; var SkipJobCurrFactorUpdate: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10881.
