### ISSUE TITLE
[Enum request] Table 98 "General Ledger Setup" - field 57 "Local Address Format"

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#22726]
Dear ALAppExtension team,

through this issue we would like to request the following change to `field 57 - Local Address Format` in Table 98 - General Ledger Setup:

Old:
```AL
field(57; "Local Address Format"; Option)
{
    Caption = 'Local Address Format';
    OptionCaption = 'Post Code+City,City+Post Code,City+County+Post Code,Blank Line+Post Code+City';
    OptionMembers = "Post Code+City","City+Post Code","City+County+Post Code","Blank Line+Post Code+City";
}
```
New:
```AL
field(57; "Local Address Format"; Enum "Country/Region Address Format")
{
    Caption = 'Local Address Format';
}
```
using the Enum `Country/Region Address Format` for the field.
Thanks in advance!

**Comment by AlexanderYakunin** [comment]
Please explain why do you need this?

**Comment by tkr95** [comment]
We want you to implement this to extend this option with additional custom formats.

**Comment by pri-kise** [comment]
This request is more than a simple enum request in my opinion.
It's an extensiblity request to support custom address formats to the local address format.

There has already been an discussion on github on this topic: https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=2054837669871616

There are ideas on this topic, too:
- https://experience.dynamics.com/ideas/idea/?ideaid=873da89d-21a7-ea11-8b71-0003ff68c1c4
- https://experience.dynamics.com/ideas/idea/?ideaid=f84bf574-7617-ea11-b265-0003ff68f605

@tkr95 if you would be willing to add this feature (including) yourself to the baseapp, then this could maybe be suiteable for the BaseApp Contribution Pilot. Get in Contact with @JesperSchulz if you're intrested in contribution.

**Comment by AlexanderYakunin** [comment]
No, it is not simple. This field has different option values in different countries with conflicting options and we cannot implement new enum without obsoleting old field and adding new one. This is large work affecting a lot of code.

You already have a possibility to build custom format for any country code. Field Address Format in country list has value Custom and you have factbox "Custom Address Format Factbox" to show it. 

Please explain in details which custom format you need to add and in which country? We cannot do this change without knowing requirements.

**Comment by tkr95** [comment]
Hello,

we have been able to find a workaround for our issue. In order for that to work we would need you to modify two existing events in Codeunit 365 `Format Address` requested in this [issue](https://github.com/microsoft/ALAppExtensions/issues/22747).
