### ISSUE TITLE
[Event Change Request] report 296 "Batch Post Sales Orders"

### ISSUE THREAD

**Issue by NAVFreak** [microsoft/ALAppExtensions#22725]
Hi,
Can you please change the events (OnBeforeOpen and OnAfterOpen) here so it includes sender.
![image](https://user-images.githubusercontent.com/34970096/228187293-1083d055-3ab7-4ade-8c82-e5187c0680b0.png)

I can't find a way to modify these protected var before request page is open
![image](https://user-images.githubusercontent.com/34970096/228187790-1e3f4a5d-d23d-4ca0-aaa6-340802e198b2.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10818.
