### ISSUE TITLE
codeunit 1535 "Approvals Mgmt." - request that method CreateApprovalRequestForSpecificUser not be local

### ISSUE THREAD

**Issue by ChristiaanGroenewald** [microsoft/ALAppExtensions#22734]
Please change method CreateApprovalRequestForSpecificUser in codeunit 1535 "Approvals Mngt." so that it is no longer a local method.
When modifying a approvals it is often necessary to call this method and it is not desirable to duplicate the method in the custom code.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10376.
