### ISSUE TITLE
[Event Parameter] codeunit 5611 "Calculate Normal Depreciation" - OnAfterCalcFinalDeprAmount #20442

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#22730]
In #20442, a new parameter to the event was added. But the call of the event was mistaken. `NumberOfDays2` was asked to use but `NumberOfDays` was used instead. Would it be possible to change it?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10853.
