### ISSUE TITLE
[Event Request] Table 7001 "Price List Line" OnAfterCopyFromPriceListHeader Event

### ISSUE THREAD

**Issue by SvenSakulowski** [microsoft/ALAppExtensions#22736]
To enable partners to effectively interface with the `CopyFrom(PriceListHeader: Record "Price List Header"; ForceDefaults: Boolean)` procedure on the "Price List Line", please add `"ForceDefaults"` as a parameter to the `"OnAfterCopyFromPriceListHeader"` event as well.

Suggested modified Event Definition:
```
[IntegrationEvent(true, false)]
local procedure OnAfterCopyFromPriceListHeader(PriceListHeader: Record "Price List Header"; ForceDefaults: Boolean)
begin
end;
```
Suggested modified Code:
```
procedure CopyFrom(PriceListHeader: Record "Price List Header"; ForceDefaults: Boolean)
begin
    [...]
    OnAfterCopyFromPriceListHeader(PriceListHeader, ForceDefaults);
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10494.
