### ISSUE TITLE
[Event Request] codeunit 99000835 "Item Jnl. Line-Reserve" - OnBeforeCallItemTracking

### ISSUE THREAD

**Issue by Sara-Handerek** [microsoft/ALAppExtensions#22746]
See the document for all the information.
[BCADDON-109 - Extensibility Request - Open Item Tracking Lines - Item Journal.pdf](https://github.com/microsoft/ALAppExtensions/files/11100913/BCADDON-109.-.Extensibility.Request.-.Open.Item.Tracking.Lines.-.Item.Journal.pdf)

We would like the integration event wrapped by comment lines to be added to the standard code.
Both extensions would be good, otherwise the more centralized code in the “Reserve” codeUnit is sufficient.

### Standard code (BC21)
table 83 "Item Journal Line"

    procedure OpenItemTrackingLines(IsReclass: Boolean)
    Begin
              ItemJnlLineReserve.CallItemTracking(Rec, IsReclass);
    end;

codeunit 99000835 "Item Jnl. Line-Reserve"

    procedure CallItemTracking(var ItemJnlLine: Record "Item Journal Line"; IsReclass: Boolean)
    var
        TrackingSpecification: Record "Tracking Specification";
        ReservEntry: Record "Reservation Entry";
        ItemTrackingLines: Page "Item Tracking Lines";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCallItemTracking(ItemJnlLine, IsReclass, IsHandled);
        if IsHandled then
            exit;

        ItemJnlLine.TestField("Item No.");
        if not ItemJnlLine.ItemPosting() then begin
            ReservEntry.InitSortingAndFilters(false);
            ItemJnlLine.SetReservationFilters(ReservEntry);
            ReservEntry.ClearTrackingFilter();
            if ReservEntry.IsEmpty() then
                Error(Text006, ItemJnlLine.FieldCaption("Operation No."), ItemJnlLine."Operation No.");
        end;

        TrackingSpecification.InitFromItemJnlLine(ItemJnlLine);
        if IsReclass then
            ItemTrackingLines.SetRunMode("Item Tracking Run Mode"::Reclass);
        ItemTrackingLines.SetSourceSpec(TrackingSpecification, ItemJnlLine."Posting Date");
        ItemTrackingLines.SetInbound(ItemJnlLine.IsInbound());
        OnCallItemTrackingOnBeforeItemTrackingLinesRunModal(ItemJnlLine, ItemTrackingLines);
        ItemTrackingLines.RunModal();
    end;

### Extensibility request
table 83 "Item Journal Line"

    procedure OpenItemTrackingLines(IsReclass: Boolean)
    var
        // NEW - START
        IsHandled: Boolean;
        // NEW - END
    Begin
        // NEW - START
        IsHandled := false;
        OnBeforeCallItemTracking(Rec, IsHandled);
        if not IsHandled then
        // NEW - END
              ItemJnlLineReserve.CallItemTracking(Rec, IsReclass);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCallItemTracking(var ItemJrnlLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;

codeunit 99000835 "Item Jnl. Line-Reserve"

    procedure CallItemTracking(var ItemJnlLine: Record "Item Journal Line"; IsReclass: Boolean)
    var
        TrackingSpecification: Record "Tracking Specification";
        ReservEntry: Record "Reservation Entry";
        ItemTrackingLines: Page "Item Tracking Lines";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCallItemTracking(ItemJnlLine, IsReclass, IsHandled);
        if IsHandled then
            exit;

        ItemJnlLine.TestField("Item No.");
        if not ItemJnlLine.ItemPosting() then begin
            ReservEntry.InitSortingAndFilters(false);
            ItemJnlLine.SetReservationFilters(ReservEntry);
            ReservEntry.ClearTrackingFilter();
            if ReservEntry.IsEmpty() then
                Error(Text006, ItemJnlLine.FieldCaption("Operation No."), ItemJnlLine."Operation No.");
        end;

        // NEW - START
        IsHandled := false;
        OnBeforeCallItemTrackingJnlLine(ItemJnlLine, IsHandled);
        if IsHandled then
            exit;
        // NEW - END

        TrackingSpecification.InitFromItemJnlLine(ItemJnlLine);
        if IsReclass then
            ItemTrackingLines.SetRunMode("Item Tracking Run Mode"::Reclass);
        ItemTrackingLines.SetSourceSpec(TrackingSpecification, ItemJnlLine."Posting Date");
        ItemTrackingLines.SetInbound(ItemJnlLine.IsInbound());
        OnCallItemTrackingOnBeforeItemTrackingLinesRunModal(ItemJnlLine, ItemTrackingLines);
        ItemTrackingLines.RunModal();
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCallItemTrackingJnlLine(var ItemJnlLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10494.
