### ISSUE TITLE
[Event Change request] 6665 "Batch Post Purch. Ret. Orders" -  OnAfterOnOpenPage

### ISSUE THREAD

**Issue by NAVFreak** [microsoft/ALAppExtensions#22742]
With new VAT fields I'm missing the possibility to initilize these before the request page runs:
![image](https://user-images.githubusercontent.com/34970096/228516509-9f6d2ff4-4799-4cba-af81-d07b17f35059.png)

Add these fields to event:
   
```
[IntegrationEvent(false, false)]
    local procedure OnAfterOnOpenPage(var ShipReq: Boolean; var InvReq: Boolean; var PostingDateReq: Date; var ReplacePostingDate: Boolean; var ReplaceDocumentDate: Boolean; var CalcInvDisc: Boolean)
    begin
    end;

```
Or even better, change [IntegrationEvent(false, false)]  --> [IntegrationEvent(**true**, false)]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10494.
