### ISSUE TITLE
[Event Request] codeunit 99000834 "Purch. Line-Reserve" - OnBeforeCallItemTracking

### ISSUE THREAD

**Issue by Sara-Handerek** [microsoft/ALAppExtensions#22744]
See the document for all the information.
[BCADDON-109 - Extensibility Request - Open Item Tracking Lines - Purchase Order.pdf](https://github.com/microsoft/ALAppExtensions/files/11100710/BCADDON-109.-.Extensibility.Request.-.Open.Item.Tracking.Lines.-.Purchase.Order.pdf)

We would like the integration event wrapped by comment lines to be added to the standard code.
Both extensions would be good, otherwise the more centralized code in the “Reserve” codeUnit is sufficient.

### Standard code (BC21)
table 39 "Purchase Line"

    procedure OpenItemTrackingLines()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeOpenItemTrackingLines(Rec, IsHandled);
        if IsHandled then
            exit;

        TestField(Type, Type::Item);
        TestField("No.");
        if "Prod. Order No." <> '' then
            Error(Text031, "Prod. Order No.");

        TestField("Quantity (Base)");

        PurchLineReserve.CallItemTracking(Rec);
    end;

codeunit 99000834 "Purch. Line-Reserve"

    procedure CallItemTracking(var PurchLine: Record "Purchase Line")
    var
        TrackingSpecification: Record "Tracking Specification";
        ItemTrackingLines: Page "Item Tracking Lines";
        ShouldProcessDropShipment: Boolean;
    Begin
        TrackingSpecification.InitFromPurchLine(PurchLine);
        if ((PurchLine."Document Type" = PurchLine."Document Type"::Invoice) and
            (PurchLine."Receipt No." <> '')) or
           ((PurchLine."Document Type" = PurchLine."Document Type"::"Credit Memo") and
            (PurchLine."Return Shipment No." <> ''))
        then
            ItemTrackingLines.SetRunMode("Item Tracking Run Mode"::"Combined Ship/Rcpt");
        ShouldProcessDropShipment := PurchLine."Drop Shipment";
        OnCallItemTrackingOnAfterCalcShouldProcessDropShipment(PurchLine, ShouldProcessDropShipment, ItemTrackingLines);
        if ShouldProcessDropShipment then begin
            ItemTrackingLines.SetRunMode("Item Tracking Run Mode"::"Drop Shipment");
            if PurchLine."Sales Order No." <> '' then
                ItemTrackingLines.SetSecondSourceRowID(ItemTrackingMgt.ComposeRowID(DATABASE::"Sales Line",
                    1, PurchLine."Sales Order No.", '', 0, PurchLine."Sales Order Line No."));
        end;
        ItemTrackingLines.SetSourceSpec(TrackingSpecification, PurchLine."Expected Receipt Date");
        ItemTrackingLines.SetInbound(PurchLine.IsInbound());
        OnCallItemTrackingOnBeforeItemTrackingFormRunModal(PurchLine, ItemTrackingLines);
        RunItemTrackingLinesPage(ItemTrackingLines);
    end;

### Extensibility request
table 39 "Purchase Line"

    procedure OpenItemTrackingLines()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeOpenItemTrackingLines(Rec, IsHandled);
        if IsHandled then
            exit;

        TestField(Type, Type::Item);
        TestField("No.");
        if "Prod. Order No." <> '' then
            Error(Text031, "Prod. Order No.");

        TestField("Quantity (Base)");

        // NEW - START
        IsHandled := false;
        OnBeforeCallItemTracking(Rec, IsHandled);
        if not IsHandled then
        // NEW - END
              PurchLineReserve.CallItemTracking(Rec);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCallItemTracking(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

codeunit 99000834 "Purch. Line-Reserve"

    procedure CallItemTracking(var PurchLine: Record "Purchase Line")
    var
        TrackingSpecification: Record "Tracking Specification";
        ItemTrackingLines: Page "Item Tracking Lines";
        ShouldProcessDropShipment: Boolean;
        // NEW - START
        IsHandled: Boolean;
        // NEW - END
    Begin
        // NEW - START
        IsHandled := false;
        OnBeforeCallItemTracking(PurchLine, IsHandled);
        if IsHandled then
            exit;
        // NEW - END

        TrackingSpecification.InitFromPurchLine(PurchLine);
        if ((PurchLine."Document Type" = PurchLine."Document Type"::Invoice) and
            (PurchLine."Receipt No." <> '')) or
           ((PurchLine."Document Type" = PurchLine."Document Type"::"Credit Memo") and
            (PurchLine."Return Shipment No." <> ''))
        then
            ItemTrackingLines.SetRunMode("Item Tracking Run Mode"::"Combined Ship/Rcpt");
        ShouldProcessDropShipment := PurchLine."Drop Shipment";
        OnCallItemTrackingOnAfterCalcShouldProcessDropShipment(PurchLine, ShouldProcessDropShipment, ItemTrackingLines);
        if ShouldProcessDropShipment then begin
            ItemTrackingLines.SetRunMode("Item Tracking Run Mode"::"Drop Shipment");
            if PurchLine."Sales Order No." <> '' then
                ItemTrackingLines.SetSecondSourceRowID(ItemTrackingMgt.ComposeRowID(DATABASE::"Sales Line",
                    1, PurchLine."Sales Order No.", '', 0, PurchLine."Sales Order Line No."));
        end;
        ItemTrackingLines.SetSourceSpec(TrackingSpecification, PurchLine."Expected Receipt Date");
        ItemTrackingLines.SetInbound(PurchLine.IsInbound());
        OnCallItemTrackingOnBeforeItemTrackingFormRunModal(PurchLine, ItemTrackingLines);
        RunItemTrackingLinesPage(ItemTrackingLines);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCallItemTracking(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10494.
