### ISSUE TITLE
 [Event Request] codeunit 99000837 "Prod. Order Line-Reserve" - OnBeforeCallItemTracking

### ISSUE THREAD

**Issue by Sara-Handerek** [microsoft/ALAppExtensions#22745]
See the document for all the information.
[BCADDON-109 - Extensibility Request - Open Item Tracking Lines - Production Order.pdf](https://github.com/microsoft/ALAppExtensions/files/11100873/BCADDON-109.-.Extensibility.Request.-.Open.Item.Tracking.Lines.-.Production.Order.pdf)

We would like the integration event wrapped by comment lines to be added to the standard code.
Both extensions would be good, otherwise the more centralized code in the “Reserve” codeUnit is sufficient.

### Standard code (BC21)
table 5406 "Prod. Order Line"

    procedure OpenItemTrackingLines()
    begin
            ProdOrderLineReserve.CallItemTracking(Rec);
    end;

codeunit 99000837 "Prod. Order Line-Reserve"

    procedure CallItemTracking(var ProdOrderLine: Record "Prod. Order Line")
    var
        TrackingSpecification: Record "Tracking Specification";
        ItemTrackingDocMgt: Codeunit "Item Tracking Doc. Management";
        ItemTrackingLines: Page "Item Tracking Lines";
    begin
        if ProdOrderLine.Status = ProdOrderLine.Status::Finished then
            ItemTrackingDocMgt.ShowItemTrackingForProdOrderComp(DATABASE::"Prod. Order Line",
              ProdOrderLine."Prod. Order No.", ProdOrderLine."Line No.", 0)
        else begin
            ProdOrderLine.TestField("Item No.");
            TrackingSpecification.InitFromProdOrderLine(ProdOrderLine);
            ItemTrackingLines.SetSourceSpec(TrackingSpecification, ProdOrderLine."Due Date");
            ItemTrackingLines.SetInbound(ProdOrderLine.IsInbound());
            OnCallItemTrackingOnBeforeItemTrackingLinesRunModal(ProdOrderLine, ItemTrackingLines);
            ItemTrackingLines.RunModal();
        end;

        OnAfterCallItemTracking(ProdOrderLine);
    end;

### Extensibility request
table 5406 "Prod. Order Line"

    procedure OpenItemTrackingLines()
    var
        // NEW - START
        IsHandled: Boolean;
        // NEW - END
    begin
        // NEW - START
        IsHandled := false;
        OnBeforeCallItemTracking(Rec, IsHandled);
        if not IsHandled then
        // NEW - END
            ProdOrderLineReserve.CallItemTracking(Rec);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCallItemTracking(var ProdOrderLine: Record "Prod. Order Line"var IsHandled: Boolean)
    begin
    end;

codeunit 99000837 "Prod. Order Line-Reserve"

    procedure CallItemTracking(var ProdOrderLine: Record "Prod. Order Line")
    var
        TrackingSpecification: Record "Tracking Specification";
        ItemTrackingDocMgt: Codeunit "Item Tracking Doc. Management";
        ItemTrackingLines: Page "Item Tracking Lines";
    begin
        if ProdOrderLine.Status = ProdOrderLine.Status::Finished then
            ItemTrackingDocMgt.ShowItemTrackingForProdOrderComp(DATABASE::"Prod. Order Line",
              ProdOrderLine."Prod. Order No.", ProdOrderLine."Line No.", 0)
        else begin
            ProdOrderLine.TestField("Item No.");

            // NEW - START
            IsHandled := false;
            OnBeforeCallItemTracking(ProdOrderLine, IsHandled);
            if IsHandled then
            	exit;
            // NEW - END
            TrackingSpecification.InitFromProdOrderLine(ProdOrderLine);
            ItemTrackingLines.SetSourceSpec(TrackingSpecification, ProdOrderLine."Due Date");
            ItemTrackingLines.SetInbound(ProdOrderLine.IsInbound());
            OnCallItemTrackingOnBeforeItemTrackingLinesRunModal(ProdOrderLine, ItemTrackingLines);
            ItemTrackingLines.RunModal();
        end;

        OnAfterCallItemTracking(ProdOrderLine);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCallItemTracking(var ProdOrderLine: Record "Prod. Order Line")var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10494.
