### ISSUE TITLE
page 6510 "Item Tracking Lines" make RegisterChange global

### ISSUE THREAD

**Issue by SBiernat** [microsoft/ALAppExtensions#22748]
In Page 6510 "Item Tracking Lines":
Would it be possible to set the protected procedure RegisterChange to global, so that is accessible from outside without extending the page itself?

Requested in august 2022 but still not in :-(
https://github.com/microsoft/ALAppExtensions/issues/20050

**Comment by AlexanderYakunin** [comment]
This is already done in v.22, you are looking into old version but we never down port external changes to previous version.
