### ISSUE TITLE
[Parametr Request] Codeunit 311 "Item-Check Avail.", Function "SalesLineCheck" - New Event OnBeforeSalesLineCheck

### ISSUE THREAD

**Issue by Sv1N2S** [microsoft/ALAppExtensions#22757]
old:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSalesLineCheck(SalesLine: Record "Sales Line"; var Rollback: Boolean; var IsHandled: Boolean)
    begin
    end;
```
new:
```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeSalesLineCheck(SalesLine: Record "Sales Line"; var Rollback: Boolean; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10855.
