### ISSUE TITLE
[Event Request] Codeunit 365 - "Format Address" - OnBeforeUseCounty

### ISSUE THREAD

**Issue by tkr95** [microsoft/ALAppExtensions#22751]
Dear ALAppExtensions team,

through this issue we would like to request adding a new event publisher `OnBeforeUseCounty` in Codeunit 365 "Format Address" with the following signature:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeUseCounty(var CountryCode: Code[10]; var IsHandled: Boolean; var ReturnValue: Boolean)
begin
end;
```
which would be called as follows in `UseCounty`:
```AL
procedure UseCounty(CountryCode: Code[10]): Boolean
    var
        CountryRegion: Record "Country/Region";
        CustomAddressFormat: Record "Custom Address Format";
        // >>>> New >>>>>>>>>>>>>>>>
        IsHandled: Boolean;
        ReturnValue: Boolean;
    begin
        OnBeforeUseCounty(CountryCode, IsHandled, ReturnValue);
        if IsHandled then
            exit(ReturnValue);
        // <<<< New <<<<<<<<<<<<<<<<

        if CountryCode = '' then begin
            GetGLSetup();
            case true of
...
end;
```
Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10853.
