### ISSUE TITLE
[Event Request] Page 7018 "Purchase Price List" - OnQueryClosePageOnBeforeDraftLineCheck

### ISSUE THREAD

**Issue by caesarsit** [microsoft/ALAppExtensions#22754]
Hello ALAppExtension-Team,

We would like to change the checks when closing a PurchasePriceList through a new publisher `OnQueryClosePageOnBeforeDraftLineCheck`. 

Code in the page trigger:
```
trigger OnQueryClosePage(CloseAction: Action): Boolean;
var
    PriceListManagement: Codeunit "Price List Management";
    IsHandled: Boolean;
    Result: Boolean;
begin
    IsHandled := false;
    OnQueryClosePageOnBeforeDraftLineCheck(Rec, Result, IsHandled);
    if IsHandled then
        exit(Result);
    if Rec.Find() then
        if Rec.HasDraftLines() then begin
            PriceListManagement.SendVerifyLinesNotification(Rec);
            exit(false);
        end;
    exit(true)
end;
```
Event publisher signature:
```
[IntegrationEvent(false, false)]
local procedure OnQueryClosePageOnBeforeDraftLineCheck(PriceListHeader: Record "Price List Header"; var Result: Boolean; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10494.
