### ISSUE TITLE
[Change Request] codeunit 8 AccSchedManagement - FiscalStartDate

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#22752]
Hello, we need a way to set and read the variable FiscalStartDate in Codeunit 8. 
Can we get the 2 procedures for this in Codeunit 8?

```
    procedure SetFiscalStartDate(NewFiscalStartDate: Date)
    begin
        FiscalStartDate := NewFiscalStartDate;
    end;

    procedure GetFiscalStartDate(var OutputFiscalStartDate: Date)
    begin
        OutputFiscalStartDate := FiscalStartDate;
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10376.
