### ISSUE TITLE
Question regarding extending User table 

### ISSUE THREAD

**Issue by gntpet** [microsoft/ALAppExtensions#22762]
Business requirement:

**As IT Administrator, I would like to see user's "Last Login Date/Time" in the User list.** 

To implement this feature I would just add flowfield (based on "Session Event" table) to **User** table . But there's one issue

 - **User** table cannot be extended since it is system table (Compiler Error AL0525)

In BC14 C/AL, I could easily make this change. What would be the alternative now?

**Comment by NKarolak** [comment]
You could create a function instead and use that as source for a new _page_ field.

**Comment by gntpet** [comment]
> You could create a function instead and use that as source for a new _page_ field.

I could, but then user won't be able to sort by the field

**Comment by JesperSchulz** [comment]
As this is a rather old question, I'll close it.

Also, this isn't the best place to ask questions. Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/forums/thread/?groupid=e78817ab-a926-4d31-96cc-aef040a4eb04)
[mibuso forum](https://forum.mibuso.com/)
[Viva Engage](https://www.yammer.com/dynamicsnavdev)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.
