### ISSUE TITLE
[Event Request] Codeunit 80 - "Sales-Post" - OnAfterDeleteApprovalEntries

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#22776]
Dear ALAppExtensions team,

through this issue we would like to request adding a new event publisher 
`OnAfterDeleteApprovalEntries` in Codeunit 80 `Sales-Post` with the following signature:

```AL
[IntegrationEvent(false, false)]
local procedure OnAfterDeleteApprovalEntries(var SalesHeader: Record "Sales Header"; var SalesInvHeader: Record "Sales Invoice Header"; var SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var SalesShptHeader: Record "Sales Shipment Header"; var ReturnRcptHeader: Record "Return Receipt Header")
begin
end;
```

called in function `DeleteApprovalEntries`

```AL
local procedure DeleteApprovalEntries(var SalesHeader: Record "Sales Header")
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeDeleteApprovalEntries(SalesHeader, IsHandled);
    if IsHandled then
        exit;

    ApprovalsMgmt.DeleteApprovalEntries(SalesHeader.RecordId());

    >>>>>>>
    OnAfterDeleteApprovalEntries(SalesHeader, SalesInvHeader, SalesCrMemoHeader, SalesShptHeader, ReturnRcptHeader);
    <<<<<<<
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11007.
