### ISSUE TITLE
Event OnBeforeCompressBuffer

### ISSUE THREAD

**Issue by Cath59** [microsoft/ALAppExtensions#22770]
Hi,
In Table 461 "Prepayment Inv. Line Buffer", for the event OnBeforeCompressBuffer, it would be useful to have the table parameter in var

[IntegrationEvent(false, false)]
    local procedure OnBeforeCompressBuffer(PrepaymentInvLineBuffer: Record "Prepayment Inv. Line Buffer"; var IsHandled: Boolean)

I cannot modify how the buffer is compressed if the the table is not in var.

Thank you 
Catherine

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10494.
