### ISSUE TITLE
[Request for External] procedure FindJobLedgerEntriesByJobTask in codeunit 1000 "Job Calculate WIP"

### ISSUE THREAD

**Issue by MMueller1974** [microsoft/ALAppExtensions#22788]
Dear ALAppExtensions team,

Can you please remove local prefix from procedure FindJobLedgerEntriesByJobTask in codeunit 1000 "Job Calculate WIP"
Old signature
```al
local procedure FindJobLedgerEntriesByJobTask(var JobTask: Record "Job Task"; var JobWIPTotal: Record "Job WIP Total"; BufferType: Enum "Job WIP Buffer Type")
```
New signature
```al
procedure FindJobLedgerEntriesByJobTask(var JobTask: Record "Job Task"; var JobWIPTotal: Record "Job WIP Total"; BufferType: Enum "Job WIP Buffer Type")
```

This change is related to issue #22785

Thank you in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10376.
