### ISSUE TITLE
[Request for External] procedure CreateWIPBufferEntryFromTask in codeunit 1000 "Job Calculate WIP"

### ISSUE THREAD

**Issue by MMueller1974** [microsoft/ALAppExtensions#22787]
Dear ALAppExtensions team,

Can you please remove local prefix from procedure CreateWIPBufferEntryFromTask in codeunit 1000 "Job Calculate WIP"
Old signature
```al
local procedure CreateWIPBufferEntryFromTask(var JobTask: Record "Job Task"; var JobWIPTotal: Record "Job WIP Total"; BufferType: Enum "Job WIP Buffer Type"; AppliedAccrued: Boolean)
```
New signature
```al
procedure CreateWIPBufferEntryFromTask(var JobTask: Record "Job Task"; var JobWIPTotal: Record "Job WIP Total"; BufferType: Enum "Job WIP Buffer Type"; AppliedAccrued: Boolean)
```

This change is related to issue #22785

Thank you in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10376.

**Comment by MMueller1974** [comment]
Hi @JesperSchulz, @AlexanderYakunin I wanted to ask whether this adjustment has already been made. I can't see it in version 2304.

**Comment by AlexanderYakunin** [comment]
Thanks for asking! I rechecked and this is not implemented yet. Probably this bug had been mistakenly linked to another PR and therefore been resolved. Apologize for this case, we can fix it quickly, today it will be done for Master (=24.0). If you need this for 23.x please let us know.

**Comment by MMueller1974** [comment]
Thank you for checking. Version 24.0 is ok, no need to put it in version 23.x

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16430.
