### ISSUE TITLE
[Event Request] Table 1003 "Job Planning Line" OnBeforeLinesWithItemToPlanExist

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#22783]
Hello.  Could you please add the following "OnBeforeLinesWithItemToPlanExist" event to Table 1003 "Job Planning Line" into the procedure LinesWithItemToPlanExist? 

```al
    procedure LinesWithItemToPlanExist(var Item: Record Item): Boolean
    var
        IsHandled: Boolean;
        Result: Boolean;
    begin
       IsHandled := false;
       OnBeforeLinesWithItemToPlanExist(Item, Result, IsHandled)
       if IsHandled then
            exit(Result);

        FilterLinesWithItemToPlan(Item);
        exit(not IsEmpty);
    end;
```

```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeLinesWithItemToPlanExist(var Item: Record Item; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10392.
