### ISSUE TITLE
[Event Request] codeunit 29 "Error Message Handler" - OnBeforeActivateErrorMessageHandler

### ISSUE THREAD

**Issue by almatlansag** [microsoft/ALAppExtensions#22782]
Hello colleagues,

we would like to be able to log errors/warnings/infos in the active instance of "Error Message Handler" codeunit.
And then be able to show them all together if needed.
For example during preview posting this list is only shown when there was an error. But we would like to show our warnings and infos even if there were no errors.
Please create the following event:

```
procedure Activate(var ErrorMessageHandler: Codeunit "Error Message Handler"): Boolean
begin
    // >>>>>>>>>>>>>>>>
    OnBeforeActivateErrorMessageHandler(ErrorMessageHandler);
    // <<<<<<<<<<<<<<<<
    Active := BindSubscription(ErrorMessageHandler);
    exit(Active);
end;
```

Event signature:
```
IntegrationEvent(false, false)]
local procedure OnBeforeActivateErrorMessageHandler(var ErrorMessageHandler: Codeunit "Error Message Handler")
begin
end;
```

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10392.
