### ISSUE TITLE
[Event Request] Codeunit 1004 - FromPlanningLineToJnlLine

### ISSUE THREAD

**Issue by GOB-Andrea** [microsoft/ALAppExtensions#2279]
Hi,
please add a publisher in function "FromPlanningLineToJnlLine" in codeunit "Job Transfer Line" as follows:

```
(...)

JobJnlLine.INSERT(TRUE);

// >>> new code
OnAfterInsertJobJnlLine_FromPlanningLineToJnlLine(JobPlanningLine,JobJnlLine);
// <<< new code
```

**Comment by AlexanderYakunin** [comment]
We already have this event:

OnAfterFromPlanningLineToJnlLine(JobJnlLine,JobPlanningLine);
