### ISSUE TITLE
[Event Request] Codeunit 90 - "Purch.-Post" - OnBeforeCheckICPartnerBlocked

### ISSUE THREAD

**Issue by HendrikSittner** [microsoft/ALAppExtensions#22798]
Dear ALAppExtensions team,

through this issue we would like to request the addition of an event publisher `OnBeforeCheckICPartnerBlocked` in Codeunit 90 "Purch.-Post" with the following signature:

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckICPartnerBlocked(var PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
begin
end;
```

which would enable us to exit procedure `CheckICPartnerBlocked` as follows:

```al
local procedure CheckICPartnerBlocked(PurchHeader: Record "Purchase Header")
var
	ICPartner: Record "IC Partner";
	// >>>> New >>>>
	IsHandled: Boolean;
	// <<<< New <<<<
begin
	// >>>> New >>>>
	IsHandled := false;
	OnBeforeCheckICPartnerBlocked(PurchHeader, IsHandled);
	if IsHandled then
		exit;
	// <<<< New <<<<
	with PurchHeader do begin
		if "Buy-from IC Partner Code" <> '' then
			if ICPartner.Get("Buy-from IC Partner Code") then
				ICPartner.TestField(Blocked, false);
		if "Pay-to IC Partner Code" <> '' then
			if ICPartner.Get("Pay-to IC Partner Code") then
				ICPartner.TestField(Blocked, false);
	end;
end;
```

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10392.
