### ISSUE TITLE
[Request for External] procedure SumPurchLines2 in codeunit 90 "Purch.-Post"

### ISSUE THREAD

**Issue by HendrikSittner** [microsoft/ALAppExtensions#22799]
Dear ALAppExtensions team,

through this issue we would like to request the removal of the local prefix of procedure `SumPurchLines2` in Codeunit 90 `"Purch.-Post"` with the following signature:

Current signature:

```al
local procedure SumPurchLines2(PurchHeader: Record "Purchase Header"; var NewPurchLine: Record "Purchase Line"; var OldPurchLine: Record "Purchase Line"; QtyType: Option General,Invoicing,Shipping; InsertPurchLine: Boolean)
```

New signature:

```al
procedure SumPurchLines2(PurchHeader: Record "Purchase Header"; var NewPurchLine: Record "Purchase Line"; var OldPurchLine: Record "Purchase Line"; QtyType: Option General,Invoicing,Shipping; InsertPurchLine: Boolean)
```

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13561.
