### ISSUE TITLE
[Event Request] Codeunit 437 "IC Navigation" - NavigateToPurchaseDocument  and NavigateToSalesOrderDocument

### ISSUE THREAD

**Issue by CedPo** [microsoft/ALAppExtensions#22813]
Dear ALAppExtensions team,

through this issue we would like to request the addition of an event publisher OnNavigateToPurchaseDocumentOnDocumentTypeCaseElse in Codeunit 437 "IC Navigation" with the following signature:

[IntegrationEvent(false, false)]
local procedure OnNavigateToPurchaseDocumentOnDocumentTypeCaseElse (DocumentNo: Code[20]; ICDirectionType: Enum "IC Direction Type"; ICPartnerCode: Code[20]; DocumentType: Enum "IC Transaction Document Type"; var OpenDoc: Boolean)
begin
end;

which would be used to add an else branch to case DocumentType in procedure NavigateToPurchaseDocument as follows:		        

        case DocumentType of 
            DocumentType::Order:
                exit(NavigateToPurchaseOrderDocument(DocumentNo, ICDirectionType, ICPartnerCode));
            DocumentType::Invoice:
                exit(NavigateToPurchaseInvoiceDocument(DocumentNo, ICPartnerCode));
	  //>>>> New >>>>
	    else begin
		OnNavigateToPurchaseDocumentOnDocumentTypeCaseElse(DocumentNo, ICDirectionType, ICPartnerCode, OpenDoc);
		exit(OpenDoc);
            end;
	  //<<<< New <<<<

        end;
        exit(false);

And an addition of a second Event publisher (with the sames idea) on the procedure NavigateToSalesOrderDocument.	

Thanks in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10392.
