### ISSUE TITLE
[New procedure request] Set/GetHideValidationDialog in Table 37 "Purchase Line"

### ISSUE THREAD

**Issue by FedericoGalanti** [microsoft/ALAppExtensions#22829]
Hello!

I would like to request the following change:
- In table 39, "Purchase Line", add new accessories "**SetHideValidationDialog**" and "**GetHideValidationDialog**"

```
procedure SetHideValidationDialog(NewHideValidationDialog: Boolean)
    begin
        HideValidationDialog := NewHideValidationDialog;
    end;
```

```
    procedure GetHideValidationDialog(): Boolean
    begin
        exit(HideValidationDialog);
    end;
```

Reason for this change is:
- While creating Purchase Orders via procedures, there are a lot of dialogs happening, in particular the Warehouse dialogs which can't be turned off in case of just messages.
Since the twin table 37, Sales Line", offers these accessories methods to control dialogs visibility, it would be really handy to do so with Purchase Lines too.

Thank you very much for the attention. In case of feedback or further informations, feel free to @ me.

Federico

**Comment by AlexanderYakunin** [comment]
This is protected var and you don't need additional procedures here.

    protected var
        HideValidationDialog: Boolean;
