### ISSUE TITLE
Extensibility of codeunit 2000042 "Post Coded Bank Statement"

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#22824]
I'd like to reopen #191  

I'm charged with **improving** the standard Belgian CODA import logic and lack various publishers in order to do so. I would like to avoid to clone the codeunit and create my own version of it. Should I start logging the missing events of is MS open to accept contributions to the Belgian localisation too, following the suggested solution listed in #191 ( @JesperSchulz ) ?

**Comment by AlexanderYakunin** [comment]
Neither Foundation nor DCR team are responsible for this kind of changes. It cannot be done technically, without analyzing of requirements. GitHub is not good place for asking for this kind of changes, you should use Ideas and when it can go to App Finance and/or App Regulatory features team who can implement changes properly. 

I am not closing this issue to let @JesperSchulz reply with comments too.

**Comment by fvet** [comment]
We decided to clone the CODA Import codeunit.
