### ISSUE TITLE
[Event Parameter Request] Table 37 Sales Line - procedure CreateDim - OnAfterCreateDim

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#22820]
We would like the Parameter/-s DefaultDimSource added to the following event.

Table 37 Sales Line - procedure CreateDim - OnAfterCreateDim

Original:

```
Table 37 Sales Line - procedure CreateDim - OnAfterCreateDim

OnAfterCreateDim(Rec, CurrFieldNo, xRec);

    [IntegrationEvent(false, false)]
    local procedure OnAfterCreateDim(var SalesLine: Record "Sales Line"; CallingFieldNo: Integer; xSalesLine: Record "Sales Line");
    begin
    end;
```

Change:

```
OnAfterCreateDim(Rec, CurrFieldNo, xRec,DefaultDimSource);

    [IntegrationEvent(false, false)]
    local procedure OnAfterCreateDim(var SalesLine: Record "Sales Line"; CallingFieldNo: Integer; xSalesLine: Record "Sales Line";DefaultDimSource: List of [Dictionary of [Integer, Code[20]]]);
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10392.
