### ISSUE TITLE
[Event Parameter Request] Table 36 Sales Header - procedure RecreateSalesLines - event OnRecreateSalesLinesOnAfterSetSalesLineFilters

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#22826]
We would like the Parameter/-s Rec added to the following event.

Table 36 Sales Header - procedure RecreateSalesLines - event OnRecreateSalesLinesOnAfterSetSalesLineFilters

Original:

```
Table 36 Sales Header - procedure RecreateSalesLines - event OnRecreateSalesLinesOnAfterSetSalesLineFilters

OnRecreateSalesLinesOnAfterSetSalesLineFilters(SalesLine);

[IntegrationEvent(false, false)]
local procedure OnRecreateSalesLinesOnAfterSetSalesLineFilters(var SalesLine: Record "Sales Line")
begin
end;
```

Change:

```
OnRecreateSalesLinesOnAfterSetSalesLineFilters(SalesLine, Rec); // <-- ADDED Rec

[IntegrationEvent(false, false)]
local procedure OnRecreateSalesLinesOnAfterSetSalesLineFilters(var SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header") // <-- ADDED Rec/SalesHeader
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10392.
