### ISSUE TITLE
[Event Request] codeunit 90  "Purch.-Post" - OnDeleteAfterPostingBeforeDelete

### ISSUE THREAD

**Issue by gretanorv** [microsoft/ALAppExtensions#22842]
Hello, would it be possible to add OnDeleteAfterPostingBeforeDelete,  event to codeunit 90  "Purch.-Post", like this: 
  
 ```al 
     local procedure DeleteAfterPosting(var PurchHeader: Record "Purchase Header") 
 ... 
               exit;
  
          with PurchHeader do begin
              IsHandled := false;
>             OnDeleteAfterPostingBeforeDelete(PurchHeader, IsHandled);//New Event
              if not IsHandled then begin
                  if HasLinks then
                      DeleteLinks();
                  Delete(); 
              end;
 ``` 
 ```al 
   
      [IntegrationEvent(false, false)]
      local procedure OnDeleteAfterPostingBeforeDelete(var PurchHeader: Record "Purchase Header"; var IsHandled: Boolean)
      begin
      end; 
 ```

**Comment by AlexanderYakunin** [comment]
Can you provide full code of procedure, if you start with BEGIN, we need to understand where the BRGIN part should END? We cannot process this requests for now.

**Comment by gretanorv** [comment]
I have updated the request accordingly. END was added after Delete() statement

**Comment by AlexanderYakunin** [comment]
So you want to skip delete of header but still delete all lines? Did I understand this correctly?

Why do you need this event at all, you already can use this event and replace our code with yours?

        OnBeforeDeleteAfterPosting(PurchHeader, PurchInvHeader, PurchCrMemoHeader, SkipDelete, SuppressCommit, TempPurchLine, TempPurchLineGlobal);
        if SkipDelete then
            exit;

We do not want to add many small events for small pieces of code, this is very tricky to manage.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11042.
