### ISSUE TITLE
[Event Request] table 5965  "Service Contract Header" - OnAfterShowDocDim

### ISSUE THREAD

**Issue by gretanorv** [microsoft/ALAppExtensions#22879]
Hello, would it be possible to add OnAfterShowDocDim event to table 5965  "Service Contract Header", like this: 
  
 ```al 
     procedure ShowDocDim() 
 ... 
             DimMgt.EditDimensionSet(
              Rec, "Dimension Set ID", StrSubstNo('%1 %2', "Contract Type", "Contract No."),
              "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");
  
>         OnAfterShowDocDim(Rec); //New Event
      end;
  
      local procedure CalcInvPeriodDuration()
      begin 
 ``` 
 ```al 
   
      [IntegrationEvent(false, false)]
      local procedure OnAfterShowDocDim(var ServiceContractHeader: Record "Service Contract Header") 
      begin
      end; 
 ```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10531.
