### ISSUE TITLE
[Event Request] table 5965  "Service Contract Header" - OnBeforeCreateDim

### ISSUE THREAD

**Issue by gretanorv** [microsoft/ALAppExtensions#22878]
Hello, would it be possible to add OnBeforeCreateDim event to table 5965  "Service Contract Header", like this: 
  
 ```al 
     procedure CreateDim(DefaultDimSource: List of [Dictionary of [Integer, Code[20]]]) 
 ... 
           if "Change Status" <> "Change Status"::Open then
              exit;
  
          IsHandled := false;
>         OnBeforeCreateDim(Rec, IsHandled); //New Event
          if IsHandled then
              exit;
  
          SourceCodeSetup.Get(); 
 ``` 
 ```al 
   
      [IntegrationEvent(false, false)]
      local procedure OnBeforeCreateDim(var ServiceContractHeader: Record "Service Contract Header"; var IsHandled: Boolean) 
      begin
      end; 
 ```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10531.
