### ISSUE TITLE
[Event Request] table 5901  "Service Item Line" - OnBeforeCheckIfServHourExist

### ISSUE THREAD

**Issue by gretanorv** [microsoft/ALAppExtensions#22896]
Hello, would it be possible to add OnBeforeCheckIfServHourExist event to table 5901  "Service Item Line", like this: 
  
 ```al 
     procedure CheckIfServHourExist(ContractNo: Code[20]): Boolean 
 ... 
       var
          IsHandled: Boolean;
      begin
          IsHandled := false;
>         OnBeforeCheckIfServHourExist(Rec, ContractNo, IsHandled); //New Event
          if IsHandled then
              exit;
  
          if ContractNo = '' then 
 ``` 
 ```al 
   
      [IntegrationEvent(false, false)]
      local procedure OnBeforeCheckIfServHourExist(var ServItemLine: Record "Service Item Line"; ContractNo: Code[20]; var IsHandled: Boolean) 
      begin
      end; 
 ```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10531.
