### ISSUE TITLE
[Event Request] table 5901  "Service Item Line" - OnAfterUpdateResponseTimeHours

### ISSUE THREAD

**Issue by gretanorv** [microsoft/ALAppExtensions#22899]
Hello, would it be possible to add OnAfterUpdateResponseTimeHours event to table 5901  "Service Item Line", like this: 
  
 ```al 
     procedure UpdateResponseTimeHours() 
 ... 
                       "Response Time (Hours)" := CalculateResponseTimeHours();
              SkipResponseTimeHrsUpdate := false
          end;
  
>         OnAfterUpdateResponseTimeHours(Rec); //New Event
      end;
  
      procedure UpdateServiceOrderChangeLog(var OldServItemLine: Record "Service Item Line")
      begin 
 ``` 
 ```al 
   
      [IntegrationEvent(false, false)]
      local procedure OnAfterUpdateResponseTimeHours(var ServItemLine: Record "Service Item Line") 
      begin
      end; 
 ```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10531.
