### ISSUE TITLE
Code to function

### ISSUE THREAD

**Issue by LFlamme** [Microsoft/ALAppExtensions#229]
Hi,

we want to have code transfered to a new global function so we can use that function in Event Subscriber.
The Code we want to have in the new function is what is inside the repeat of those functions.

Codeunit 99000773 Calculate Prod. Order; Function  TransferRouting
Codeunit 99000773 Calculate Prod. Order; Function  TransferBOM

Codeunit 99000809 Planning Line Management; Function TransferRouting (the big repeat not the small one)
Codeunit 99000809 Planning Line Management; Function TransferBOM(also the big repeat)

_Thanks in Advance_

**Comment by JesperSchulz** [comment]
This issue has been resolved and will ship in a future update.
