### ISSUE TITLE
[Request for External] Codeunit 353 - "Item Availability Forms Mgt"

### ISSUE THREAD

**Issue by GOB-Andrea** [microsoft/ALAppExtensions#2291]
Hi,
could you please switch the following functions in codeunit "Item Availability Forms Mgt" to local = no and external?

- ShowItemAvailByEvent
- ShowItemAvailByLoc
- ShowItemAvailByDate
- ShowItemAvailVariant
- ShowItemAvailByBOMLevel
- FilterItem

**Comment by miljance** [comment]
We also need those functions externally exposed. Please let us know about the plan date.

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
