### ISSUE TITLE
Can local procedures InitSalesLineFields() and InitPurchLineFields() in "Copy Document Mgt." made global?

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/ALAppExtensions#22914]
Can local procedures InitSalesLineFields() and InitPurchLineFields() made global in codeunit 6620 "Copy Document Mgt."?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10449.
