### ISSUE TITLE
Can local procedure RequestFindContInPostDocuments() in report:"Add Contacts" made global?

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/ALAppExtensions#22917]
Can local procedure RequestFindContInPostDocuments() in report:5198:"Add Contacts" made global?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10449.
