### ISSUE TITLE
[Event Request or refactor req.]table 1382 "Item Templ.".TransferFieldValues

### ISSUE THREAD

**Issue by NAVFreak** [microsoft/ALAppExtensions#22923]
Hi,

Currently we have the scenario that we can't add new fields (ISV or Standard fields) with new field numbers to table 1382 "Item Templ.".

Scenario is that ISV haven't added the fields in "Item Templ." and when we as a VAR tries to add them with another number the code fails since every field  "Item Templ." has to be a direct match.

![image](https://user-images.githubusercontent.com/34970096/230322438-2a1a2165-d38f-4855-bf45-8ee86e2d6a85.png)

Then it fails in this function due to mismatching fields
![image](https://user-images.githubusercontent.com/34970096/230322672-50762e32-4eb8-40cb-b9ba-0a8d934cb116.png)

Can you at least add events so we can overide that not matching/not existing fields can be manually handled.
Best would be if you refactor/add a good error message if there is no handled and the target field is missing

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13655.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 13740.
