### ISSUE TITLE
Compilation errors with events from BC22 CH version of Table 475 - Vendor Payment Buffer

### ISSUE THREAD

**Issue by laurbag** [microsoft/ALAppExtensions#22924]
For one of our AppSource we are using 2 events from table 475 - Vendor Payment Buffer:
- OnCopyFieldsFromVendorLedgerEntry
- OnCopyFieldsToGenJournalLine
When submitting publication validation all countries are passed except CH.
![image](https://user-images.githubusercontent.com/79576552/230325885-7713d82e-4851-4a73-8285-8c8b7e33aad8.png)

The reason is a different naming of parameters.
**CH Version**
![image](https://user-images.githubusercontent.com/79576552/230323300-a147d8c0-7c3b-46c0-96fe-faecca0dc9d0.png)
**W1 Version**
![image](https://user-images.githubusercontent.com/79576552/230323415-d2e26809-86a7-49e6-a1ba-5cba322eceac.png)

Is there any temporary solution we can use to publish the AppSource before a fix?

**Comment by ProdwareCibsBCDevelopment** [comment]
Hi,
We still can't deploy our extension to CH environments in 22.2 BC version due to this persistent issue.
Is there any update you can share with us, or any idea for a  workaround?

**Comment by dcenic** [comment]
@AcererakTheLich @laurbag  In Business Central 24.x, we will add new events OnAfterCopyFieldsFromVendorLedgerEntry and OnAfterCopyFieldsToGenJournalLine. They will be raised right after the current ones and they will have aligned signatures across the Business Central country versions. For 24.x, you chould modify your code to subscribe to these new events, and you will be able to publish in CH.
