### ISSUE TITLE
[Extensibility bug] Report 511 "Complete IC Inbox Action"

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#22938]
Hello,

When we move two or more lines in Intercompany General Journal with auto accept lines in receiving company. We have an error with "Line No." field.

This happened because when the report running by Job Queue the function PageValidateJnl() is not called and the first line number is not specified.

Thank you!

**Comment by AlexanderYakunin** [comment]
Please be aware what you should report bugs to Technical Support to get it fixed according SLA. This issue will be converted to the bug  but no expectations for processing time can be promised.
