### ISSUE TITLE
[Request For External] Page 39 "General Journal" - CurrentJnlBatchName variable as protected

### ISSUE THREAD

**Issue by ZsomborCsaszi** [microsoft/ALAppExtensions#22933]
Dear Support,

Could you please set CurrentJnlBatchName as protected var? (Page 39 "General Journal")

```
var
     CurrentJnlBatchName: Code[10];
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10449.
