### ISSUE TITLE
[Event Parameter Change] Codeunit 99000768 Production BOM-Copy - procedure CopyBOM - event OnAfterCopyBOM

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#22930]
We would like the parameter/-s var CurrentBOMHeader added to the following events.

Codeunit 99000768 Production BOM-Copy - procedure CopyBOM - event OnAfterCopyBOM

Original:

```
Codeunit 99000768 Production BOM-Copy - procedure CopyBOM - event OnAfterCopyBOM

[IntegrationEvent(false, false)]
local procedure OnAfterCopyBOM(BOMHeaderNo: Code[20]; CurrentBOMHeader: Record "Production BOM Header"; FromVersionCode: Code[20]; ToVersionCode: Code[20])
begin
end;

```

Change:

```
we need CurrentBOMHeader to be set to var

[IntegrationEvent(false, false)]
local procedure OnAfterCopyBOM(BOMHeaderNo: Code[20]; var CurrentBOMHeader: Record "Production BOM Header"; FromVersionCode: Code[20]; ToVersionCode: Code[20])
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10855.
