### ISSUE TITLE
[Event Parameter Request] Codeunit 5632 FA Jnl.-Post Line - procedure GenJnlPostLine

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#22942]
Dear ALAppExtensions Team,

We would like to request the following change

    procedure GenJnlPostLine(GenJnlLine: Record "Gen. Journal Line"; FAAmount: Decimal; VATAmount: Decimal; NextTransactionNo: Integer; NextGLEntryNo: Integer; GLRegisterNo: Integer)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGenJnlPostLine(GenJnlLine, FAInsertLedgEntry, FAAmount, VATAmount, NextTransactionNo, NextGLEntryNo, GLRegisterNo, IsHandled);
        if not IsHandled then begin
            FAInsertLedgEntry.SetGLRegisterNo(GLRegisterNo);
            FAInsertLedgEntry.DeleteAllGLAcc();
            with GenJnlLine do begin

               ...............................................................................

                if "FA Posting Type" = "FA Posting Type"::Maintenance then begin
                    MakeMaintenanceLedgEntry.CopyFromGenJnlLine(MaintenanceLedgEntry, GenJnlLine);
                    MaintenanceLedgEntry.Amount := FAAmount;
                    MaintenanceLedgEntry."VAT Amount" := VATAmount;
                    MaintenanceLedgEntry."Transaction No." := NextTransactionNo;
                    MaintenanceLedgEntry."G/L Entry No." := NextGLEntryNo;
                    PostMaintenance();
                end else begin
                    MakeFALedgEntry.CopyFromGenJnlLine(FALedgEntry, GenJnlLine);
                    FALedgEntry.Amount := FAAmount;
                    FALedgEntry."VAT Amount" := VATAmount;
                    FALedgEntry."Transaction No." := NextTransactionNo;
                    FALedgEntry."G/L Entry No." := NextGLEntryNo;
                    **//--> change request GLReg parameter
                    //OnBeforePostFixedAssetFromGenJnlLine(GenJnlLine, FALedgEntry, FAAmount, VATAmount);
                    OnBeforePostFixedAssetFromGenJnlLine(GenJnlLine, FALedgEntry, FAAmount, VATAmount,GLRegisterNo);
                    //<-- change request**
                    PostFixedAsset();
                end;
            end;
        end;
    
        OnAfterGenJnlPostLine(GenJnlLine);
    end;

    **//--> change request GLRegisterNo parameter
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostFixedAssetFromGenJnlLine(var GenJournalLine: Record "Gen. Journal Line"; var FALedgerEntry: Record "FA Ledger Entry"; FAAmount: Decimal; VATAmount: Decimal;GLRegisterNo: Integer)
    begin
    end;
    //<-- change request**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10560.
