### ISSUE TITLE
Page 30028 (salesOrder API V2) Needs Rec. in all field names

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#22944]
@JesperSchulz 

How long until someone could put Rec. into all the API field definitions in all the API objects? Compilers seem to demand it now when I copy an API to make a custom one for a client. Thanks.

Followup question - will APIs ever be extensible?

Thanks.

**Comment by pri-kise** [comment]
@grantbrimhall APIs are currently not extensible by design. -> APIs are a well defined Interface that someone should be able rely on.

Additionally you can create a PR for the API App here and fix the implicti with warning.

**Comment by grantbrimhall** [comment]
that's just the concern ... well defined is often missing key fields (Location Code, Campaign, PaymentMethod, ShippingAgent/Service, etc.). And so while the core is functionally reliable, when clients need extra fields, to extend we have to make a copy, and go through adding the implicit variables. I would have hoped that if Microsoft is going away from implicit variables, that their core code base would reflect that direction, and not rely on PR from external contributors. ;)
