### ISSUE TITLE
[External Request] - Table Price List Line - Procedure TestStatusDraft

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#22953]
Could this procedure be global?
```
  local procedure TestStatusDraft()
    begin
        if not IsEditable() then
            TestField(Status, Status::Draft);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10762.
