### ISSUE TITLE
[Event Request] Table 14 Location - OnBeforeIsBinBWReceiveOrShip

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#22956]
We would like to change the `IsBinBWReceiveOrShip` return value, since we allow to specify **multiple** receipts bins on a same location. 

_(Use case is one warehouse / location that has separate zones, of which one is used for dealing with goods received under suspension of excise duty. In that case, the suggested receipt bin code should be different from the default receipt bin code. PS: Using 2 separate locations is also an option, but adds more complexity in other areas of the application)._

Can you please adjust `IsBinBWReceiveOrShip` to
- Have a named return parameter?
- Have a OnBefore event publisher with IsHandled pattern and option to overwrite the functions return value?

---

**As-is**

```
procedure IsBinBWReceiveOrShip(BinCode: Code[20]): Boolean
    begin
        exit(("Receipt Bin Code" <> '') and (BinCode = "Receipt Bin Code") or
          ("Shipment Bin Code" <> '') and (BinCode = "Shipment Bin Code"));
    end;
```

**Suggested code**

```
procedure IsBinBWReceiveOrShip(BinCode: Code[20]) BinBWReceiveOrShip: Boolean
    var
        IsHandled: Boolean;
    begin
        OnBeforeIsBinBWReceiveOrShip(Rec, BinCode, BinBWReceiveOrShip, IsHandled);
        if IsHandled then
            exit;
        
        BinBWReceiveOrShip := 
         (("Receipt Bin Code" <> '') and (BinCode = "Receipt Bin Code") or
          ("Shipment Bin Code" <> '') and (BinCode = "Shipment Bin Code"));
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsBinBWReceiveOrShip(Rec: Record Location; BinCode: Code[20]; var BinBWReceiveOrShip: Boolean; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10644.
