### ISSUE TITLE
Table 295 "Reminder Header" - "Additional Fee" - CalcFormula Issue

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#22957]
Dear ALAppExtensions team,

we came across an inconsistency of the `Additional Fee` - CalcFormula between `Reminder Header` and `Issued Reminder Header`.

`Reminder Header`:

```AL
CalcFormula = Sum("Reminder Line".Amount WHERE("Reminder No." = FIELD("No."),
                  Type = CONST("G/L Account"),
     =====>       "Line Type" = FILTER(<> "Not Due")));
```

`Issued Reminder Header`:

```AL
CalcFormula = Sum("Issued Reminder Line".Amount WHERE("Reminder No." = FIELD("No."),
                  Type = CONST("G/L Account")));
```

The `Line Type` - Filter is missing in the `Issued Reminder Header` - CalcFormula. Also, we believe the correct `Line Type` - Filter should be:

```AL
"Line Type" = CONST("Reminder Line")
```

**Comment by khamshot** [comment]
@AlexanderYakunin Hello again! Has anything happen regarding this ticket yet?

**Comment by KevinHermsdorf** [comment]
@AlexanderYakunin Hello again! Has anything happened regarding this ticket yet?

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 22187.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22184.
