### ISSUE TITLE
Table 295 "Reminder Header" - "VAT Amount" - CalcFormula Issue

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#22960]
Dear ALAppExtensions team,

we came across an inconsistency of the `VAT Amount` - CalcFormula between `Reminder Header` and `Issued Reminder Header`.

`Reminder Header`:

```AL
CalcFormula = Sum("Reminder Line"."VAT Amount" WHERE("Reminder No." = FIELD("No."),
                  "Detailed Interest Rates Entry" = CONST(false),
     =====>       "Line Type" = FILTER(<> "Not Due")));
```

`Issued Reminder Header`:

```AL
CalcFormula = Sum("Issued Reminder Line"."VAT Amount" WHERE("Reminder No." = FIELD("No."),
                  "Detailed Interest Rates Entry" = CONST(false)));
```

The `Line Type` - Filter is missing in the `Issued Reminder Header` - CalcFormula. Also, we believe the correct `Line Type` - Filter should be:

```AL
"Line Type" = CONST("Reminder Line")
```

**Comment by pri-kise** [comment]
@KevinHermsdorf 
This repository is only for extensibility requests for Dynamics 365 Business Central. Microsoft suggests that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:
• On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
• On line – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by khamshot** [comment]
@AlexanderYakunin Hello again! Has anything happen regarding this ticket yet?

**Comment by KevinHermsdorf** [comment]
@AlexanderYakunin Hello again! Has anything happened regarding this ticket yet?

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 22187.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22184.
