### ISSUE TITLE
Move ToSalesType and ToSalesCode to protected variables in report 7051 "Suggest Item Price on Wksh."

### ISSUE THREAD

**Issue by petemchlk** [microsoft/ALAppExtensions#22965]
Hi! Would it be possible to move ToSalesType and ToSalesCode to protected variables in report 7051 "Suggest Item Price on Wksh." like in example here?:

```al
 protected var
        ToSalesType: Option Customer,"Customer Price Group","All Customers",Campaign;
        ToSalesCode: Code[20];
```

Also ToSylesType could be type enum 7023 "Sales Price Type"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
