### ISSUE TITLE
Event Change Request - codeunit 1720 "Deferral Utilities" - OnBeforeCreateDeferralSchedule

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#22969]
Hi, can the following parameters please be changed to vars in this event:
codeunit 1720 "Deferral Utilities" - OnBeforeCreateDeferralSchedule
StartDate
NoOfPeriods
AdjustStartDate

**Comment by JeremyOrgan-DC** [comment]
Hi, Will this change be able to be done, this allows us to amend the start date and no of periods that the deferral is for. Customer requires this to be able to move to saas. thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10879.
