### ISSUE TITLE
[Event Request] codeunit 1605 "PEPPOL Management" - OnAfterGetContractDocRefInfo

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#22963]
Can you add event OnAfterGetContractDocRefInfo in procedure GetContractDocRefInfo?
Please include all parameters in the procedure as parameter in the event.
And set all parameters as reference. except SalesHeader.

```
    procedure GetContractDocRefInfo(SalesHeader: Record "Sales Header"; var ContractDocumentReferenceID: Text; var DocumentTypeCode: Text; var ContractRefDocTypeCodeListID: Text; var DocumentType: Text)
    begin
        ContractDocumentReferenceID := SalesHeader."No.";
        DocumentTypeCode := '';
        ContractRefDocTypeCodeListID := GetUNCL1001ListID();
        DocumentType := '';
        // >>>>>>>>>
        OnAfterGetContractDocRefInfo(SalesHeader, ContractDocumentReferenceID, DocumentTypeCode, ContractRefDocTypeCodeListID, DocumentType)
        // <<<<<<<<<
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10644.
