### ISSUE TITLE
Codeunit 1001 "Job Post-Line" - Allow exit from OnBeforePostInvoiceContractLine Event

### ISSUE THREAD

**Issue by DanielSmutek** [microsoft/ALAppExtensions#22964]
Please, allow handling in procedure PostInvoiceContractLine with OnBeforePostInvoiceContractLine Event

Thanks!

    **procedure PostInvoiceContractLine(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line")**
    var
        Job: Record Job;
        JobPlanningLine: Record "Job Planning Line";
        JobPlanningLineInvoice: Record "Job Planning Line Invoice";
        DummyJobLedgEntryNo: Integer;
        JobLineChecked: Boolean;
        IsHandled: Boolean;
    begin
        **//Event
        //OnBeforePostInvoiceContractLine(SalesHeader, SalesLine);  //Old Line
        IsHandled := false;
        OnBeforePostInvoiceContractLine(SalesHeader, SalesLine, IsHandled);
        if IsHandled then
            exit;
        //Event**

        JobPlanningLine.SetCurrentKey("Job Contract Entry No.");
        JobPlanningLine.SetRange("Job Contract Entry No.", SalesLine."Job Contract Entry No.");
        JobPlanningLine.FindFirst();
        Job.Get(JobPlanningLine."Job No.");

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10644.
