### ISSUE TITLE
[Event-Request] Codeunit 1620 "PEPPOL Validation" - OnBeforeCheckEmptyDescription

### ISSUE THREAD

**Issue by SomeWaterFlow** [microsoft/ALAppExtensions#22979]
Due to the datastructure in our customers Sales/ServiceLine, we need the ability to disable the Errors when posting empty descriptions in an electronic document.

    local procedure CheckSalesDocumentLine(SalesLine: Record "Sales Line")
    var
        GeneralLedgerSetup: Record "General Ledger Setup";
        VATPostingSetup: Record "VAT Posting Setup";
        PEPPOLMgt: Codeunit "PEPPOL Management";
        unitCode: Text;
        unitCodeListID: Text;
    #region Changes
        IsHandled: Boolean;
    #endregion Changes
    begin
        PEPPOLMgt.GetLineUnitCodeInfo(SalesLine, unitCode, unitCodeListID);
        with SalesLine do begin
            if (Type <> Type::" ") and ("No." <> '') and (unitCode = '') then
                Error(EmptyUnitOfMeasureErr, "Unit of Measure Code");

            
    #region Changes
            IsHandled := false;
            OnBeforeCheckEmptyDescription(SalesLine, IsHandled);
            if not IsHandled then
                if Description = '' then
                    Error(MissingDescriptionErr);
    #endregion Changes

            if (Type <> Type::" ") and ("No." <> '') then begin // Not a description line
                if GeneralLedgerSetup.UseVat() then
                    TestField("VAT Prod. Posting Group");
                VATPostingSetup.Get("VAT Bus. Posting Group", "VAT Prod. Posting Group");
                VATPostingSetup.TestField("Tax Category");
                if (Type = Type::Item) and ("Unit Price" < 0) then
                    if not ConfirmManagement.GetResponseOrDefault(StrSubstNo(NegativeUnitPriceErr, RecordId), false) then
                        Error('');
            end;
        end;
    end;

Event Signature:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckEmptyDescription(SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10855.
