### ISSUE TITLE
[Request for External] Move prepayment variables to protected var on Order Statistics pages

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#22977]
Hi Microsoft AL Development Team,

Could you please move these variables to **protected var**?

### page 402 "Sales Order Statistics"
![image](https://user-images.githubusercontent.com/69611495/231951330-40039f95-e9a7-41ed-ad6e-f967b5ff0900.png)

### page 403 "Purchase Order Statistics"
![image](https://user-images.githubusercontent.com/69611495/231951101-5708a7f0-60b9-44c5-aece-5ed0c286ac4c.png)

Thank you.

Kind regards,
Tuan Nguyen

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10652.
