### ISSUE TITLE
[Event Request] New events for Update Prepmt. Amount On Lines functions

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#22976]
Hi Microsoft AL Development Team,

Could you add the following events to Sales/Purch. Post-Prepayments codeunits?

### codeunit 442 "Sales-Post Prepayments"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdatePrepmtAmountOnSaleslines(SalesHeader: Record "Sales Header"; NewTotalPrepmtAmount: Decimal; var IsHandled: Boolean);
    begin
    end;
```

![image](https://user-images.githubusercontent.com/69611495/231949541-c1ac3d22-e861-4aa5-b512-b92da87d095a.png)

### codeunit 444 "Purchase-Post Prepayments"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdatePrepmtAmountOnPurchLines(PurchHeader: Record "Purchase Header"; NewTotalPrepmtAmount: Decimal; var IsHandled: Boolean);
    begin
    end;
```

![image](https://user-images.githubusercontent.com/69611495/231949579-e1029423-be8d-4f96-a872-83158582ce57.png)

Thank you.

Kind regards,
Tuan Nguyen

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10881.
