### ISSUE TITLE
[Event Parameter Request] Page 344 - OnBeforeFindRecordsSetSources

### ISSUE THREAD

**Issue by mdemaio9** [microsoft/ALAppExtensions#22984]
Hello,
We need the parameter "DocumentEntry" passed by Var in the event OnBeforeFindRecordsSetSources (page 344 Navigate).

`[IntegrationEvent(true, false)]
    local procedure OnBeforeFindRecordsSetSources(DocumentEntry: Record "Document Entry"; DocNoFilter: Text; PostingDateFilter: Text; ExtDocNo: Text; var IsHandled: Boolean)
    begin
    end;`

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56811.
