### ISSUE TITLE
[Event Request] New events for Export EFT (IAT)

### ISSUE THREAD

**Issue by GALKALACHE** [microsoft/ALAppExtensions#22985]
Hi Microsoft AL Development Team,

Could you add the following event to codeunit 10097 "Export EFT (IAT)":

[IntegrationEvent(false, false)]
local procedure OnStartExportFileOnBeforeACHUSHeaderModify(var ACHUSHeader: Record "ACH US Header"; var BankAccount: Record "Bank Account")
begin
end;

**Procedure StartExportFile**

OnStartExportFileOnBeforeACHUSHeaderModify(ACHUSHeader, BankAccount);

![image](https://user-images.githubusercontent.com/61793253/232062634-2a73fa23-11b5-4cdc-a918-ef6834bb5179.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10881.
