### ISSUE TITLE
[Event Change Request] Table 246 Requisition Line - IntegrationEvent OnValidateCurrencyCodeOnBeforeUpdateCurrencyFactor

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#22986]
Dear ALAppExtensions Team,

We would like to request the following change

[IntegrationEvent(false, false)]
**//--> change request VATPostingSetup parameter with "var"**
local procedure OnValidateCurrencyCodeOnBeforeUpdateCurrencyFactor(var ReqLine: Record "Requisition Line"; **var** CurrExchRate: Record "Currency Exchange Rate")
**//<-- change request VATPostingSetup parameter with "var"**
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10879.
