### ISSUE TITLE
Event for Available Companies

### ISSUE THREAD

**Issue by NEVARISDevelopment** [microsoft/ALAppExtensions#22987]
Base Application	Microsoft v. 21.5.53619.55215	
On the right side above there is an icon that offers the companies to open.
We would like to filter these companies before the user sees "Available Companies".
Is there en event that we can subscribe?

**Comment by jehelles** [comment]
What companies are shown in "Available Companies" is controlled using permissions. If a user is not supposed to see a specific company, remove the permissions for that company for that user.
