### ISSUE TITLE
[Request-For-External] Table 36 "Sales Header" - Procedure InitPostingNoSeries

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#22993]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

```
procedure InitPostingNoSeries()

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10652.
