### ISSUE TITLE
Event Request - codeunit 1026 "Job Link Usage" - OnHandleMatchUsageSpecifiedJobPlanningLineBeforeUpdateQuantity

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#22990]
Please could we have the following event added:
codeunit 1026 "Job Link Usage"
    [IntegrationEvent(false, false)]
    local procedure OnHandleMatchUsageSpecifiedJobPlanningLineBeforeUpdateQuantity(var JobPlanningLine: Record "Job Planning Line"; JobJournalLine: Record "Job Journal Line";Var UpdateQuantity: Boolean)
    begin
    end;

    procedure HandleMatchUsageSpecifiedJobPlanningLine(var JobPlanningLine: Record "Job Planning Line"; JobJournalLine: Record "Job Journal Line"; JobLedgerEntry: Record "Job Ledger Entry")
    var
        JobUsageLink: Record "Job Usage Link";
        PostedQtyBase: Decimal;
        TotalQtyBase: Decimal;
        TotalRemainingQtyPrePostBase: Decimal;
        PartialJobPlanningLineQuantityPosting: Boolean;
        UpdateQuantity: Boolean;
    begin
        PostedQtyBase := JobPlanningLine."Quantity (Base)" - JobPlanningLine."Remaining Qty. (Base)";
        TotalRemainingQtyPrePostBase := JobJournalLine."Quantity (Base)" + JobJournalLine."Remaining Qty. (Base)";
        TotalQtyBase := PostedQtyBase + TotalRemainingQtyPrePostBase;
        JobPlanningLine.SetBypassQtyValidation(true);

        if Abs(UOMMgt.CalcQtyFromBase(JobPlanningLine."No.", JobPlanningLine."Variant Code", JobPlanningLine."Unit of Measure Code", TotalQtyBase, JobPlanningLine."Qty. per Unit of Measure")) < Abs(JobPlanningLine.Quantity) then begin
            PartialJobPlanningLineQuantityPosting := (JobLedgerEntry."Serial No." <> '') or (JobLedgerEntry."Lot No." <> '');
            HandleMatchUsageSpecifiedJobPlanningLineOnAfterCalcPartialJobPlanningLineQuantityPosting(JobPlanningLine, JobJournalLine, JobLedgerEntry, PartialJobPlanningLineQuantityPosting);
        end;
        
        // CalledFromInvtPutawayPick - Skip this quantity validation for Inventory Pick posting as quantity cannot be updated with an active Warehouse Activity Line.
        UpdateQuantity := not (CalledFromInvtPutawayPick or PartialJobPlanningLineQuantityPosting);
        OnHandleMatchUsageSpecifiedJobPlanningLineBeforeUpdateQuantity(JobPlanningLine,JobJournalLine,UpdateQuantity);
        if UpdateQuantity then
            if (TotalQtyBase > JobPlanningLine.Quantity) or (JobPlanningLine.Quantity = 0) then
                JobPlanningLine.Validate(Quantity,
                    UOMMgt.CalcQtyFromBase(
                        JobPlanningLine."No.", JobPlanningLine."Variant Code", JobPlanningLine."Unit of Measure Code",
                        TotalQtyBase, JobPlanningLine."Qty. per Unit of Measure"));

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10804.
