### ISSUE TITLE
Description/Name not extended

### ISSUE THREAD

**Issue by SirBETE** [microsoft/ALAppExtensions#2299]
In BC14 Name, Description, Contact ... fields were extended to text[100].
I'm correcting these changes in our own extension, but notice that not everywhere in the base application this was changed:

- TAB841 Cash Flow Account.Name (f2, still text50, not text100)
- TAB841 Cash Flow Account."Search Name" (f3, still text50, not text100)
- TAB5402 Unit of Measure Translation.Description (f3, still text10, not text50)
(Although I'm unsure about this one. Whether or not it's the translation of Unit Of Measure.Code or  Unit Of Measure.Description ...)

Will these also be extended?

**Comment by AlexanderYakunin** [comment]
TAB841 - extended already
TAB5402 - will not be extended, no need for this.

**Comment by SirBETE** [comment]
Ok, thanks :)
