### ISSUE TITLE
Change to WhseLinesExist in Whse. Validate Source Line

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/ALAppExtensions#23]
BC OnPremise October 2018 Release

Was [Issue 4051](https://github.com/Microsoft/AL/issues/4051) in Microsoft/AL

In our extension we have added a new document called Manifest (similar Sales Quote/Order/Invoice/Cr. Memo), if the `WhseLinesExist` function in CU5777 Whse. Validate Source Line, had a VAR parameter for the `TableCaptionValue` variable then we could easily duplicate the `SalesLineVerifyChange` and `SaleLineDelete` functions without having to modify the CU.

**Comment by JesperSchulz** [comment]
Thank you for your request. We are currently setting up the process around handling of issues in this new GitHub repository and you should hence expect a short delay in the processing of this request. But we will be on your case shortly!

**Comment by JesperSchulz** [comment]
Adding a parameter to the function would require a lot of changes throughout the application. And most calls actually do not care about the TableCaptionValue and would need a dummy parameter for the call. I'd hence prefer an alternative solution. Perhaps a _new_ public function with the desired function signature would do? I'd have the new function with the TableCaptionValue call the original WhseLinesExist function. Or maybe you could get unblocked with an event or two in the WhsLinesExist function? Please consider alternative, non-breaking solutions.

**Comment by JesperSchulz** [comment]
Would adding the following function do the trick?

    [External]
    PROCEDURE WhseLinesExistWithTableCaptionOut@39(SourceType@1000 : Integer;SourceSubType@1001 : Option;SourceNo@1002 : Code[20];SourceLineNo@1003 : Integer;SourceSublineNo@1004 : Integer;SourceQty@1007 : Decimal;VAR TableCaptionValueOut@1005 : Text[100]) : Boolean;
    VAR
      Success@1006 : Boolean;
    BEGIN
      Success := WhseLinesExist(SourceType,SourceSubType,SourceNo,SourceLineNo,SourceSublineNo,SourceQty);
      TableCaptionValueOut := TableCaptionValue;
      EXIT(Success);
    END;
