### ISSUE TITLE
[Request-For-External] Table 37 "Sales Line" - Procedure InitDefaultDimensionSources

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#23005]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

```
procedure InitDefaultDimensionSources(var DefaultDimSource: List of [Dictionary of [Integer, Code[20]]]; FieldNo: Integer)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10652.
