### ISSUE TITLE
[New Event Request] Procedure isInbound on table 37/39

### ISSUE THREAD

**Issue by DamianoCastagna** [microsoft/ALAppExtensions#23003]
Hello, In asking for a new event into function isinbound on table 37 an 39.
As the document type enum is extensible, I think that the function isInbound must check also new values

Actually the function is (PurchaseLine)

procedure IsInbound(): Boolean
    begin
        case "Document Type" of
            "Document Type"::Order, "Document Type"::Invoice, "Document Type"::Quote, "Document Type"::"Blanket Order":
                exit("Quantity (Base)" > 0);
            "Document Type"::"Return Order", "Document Type"::"Credit Memo":
                exit("Quantity (Base)" < 0);
        end;
       
        exit(false);
    end;

I think that something like this shoud work

    procedure IsInbound(): Boolean
   var 
     isInboundValue : boolean

    begin
        case "Document Type" of
            "Document Type"::Order, "Document Type"::Invoice, "Document Type"::Quote, "Document Type"::"Blanket Order":
                exit("Quantity (Base)" > 0);
            "Document Type"::"Return Order", "Document Type"::"Credit Memo":
                exit("Quantity (Base)" < 0);
        end;
       // Check for new document Type and assign the value to a new variable an the exit the new variable value
       isInboundValue := False
       onAfterCheckPurchaseStandardDocumentType(Rec , isInBoundValue);
        exit(IsInboundValue)
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10924.
