### ISSUE TITLE
Open access to functions in "Job Planning Line" table

### ISSUE THREAD

**Issue by sergeyol** [microsoft/ALAppExtensions#23008]
```
table 1003 "Job Planning Line"
```

Please consider changing access modifier from **local** to (at least) **protected** for the following functions:

```
local procedure ValidateModification(FieldChanged: Boolean)
local procedure UpdateAllAmounts()
```
As a bonus, for these functions as well:
```
local procedure FindPriceAndDiscount(CalledByFieldNo: Integer)
local procedure UpdateAmountsAndDiscounts()
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10652.
