### ISSUE TITLE
[Event Parameter Request] Table 900 "Assembly Header", event OnBeforeValidateDates

### ISSUE THREAD

**Issue by LucVanDyck** [microsoft/ALAppExtensions#23016]
In the event

> [IntegrationEvent(false, false)]
> local procedure OnBeforeValidateDates(var AssemblyHeader: Record "Assembly Header"; FieldNumToCalculateFrom: Integer; DoNotValidateButJustAssign: Boolean; var IsHandled: Boolean)
>     begin
>     end;
> 

the parameter DoNotValidateButJustAssign should be defined as var so we are able to change te value.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10879.
