### ISSUE TITLE
[Event Request] OnUpdateSourceDocumentOnAfterGetTransLine in Codeunit 7324 "Whse.-Activity-Post"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#23015]
Please add a new event  OnUpdateSourceDocumentOnAfterGetTransLine in Codeunit 7324 "Whse.-Activity-Post" similar to the existing events OnUpdateSourceDocumentOnAfterGetSalesLine and OnUpdateSourceDocumentOnAfterGetPurchLine:

    [IntegrationEvent(false, false)]
    local procedure OnUpdateSourceDocumentOnAfterGetTransLine(var TransferLine: Record "Transfer Line"; TempWhseActivLine: Record "Warehouse Activity Line" temporary)
    begin
    end;

local procedure UpdateSourceDocument()
...
                DATABASE::"Transfer Line":
                    begin
                        TransHeader.Get("Source No.");
                        TransLine.Get("Source No.", "Source Line No.");
-->                   OnUpdateSourceDocumentOnAfterGetTransLine(TransLine, TempWhseActivLine);

**Comment by AleksandricMarko** [comment]
Already implemented
