### ISSUE TITLE
[Event Request] Table 37- "Sales Line" - OnBeforeCheckPrepmtAmounts

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#23011]
Dear ALAppExtensions team,

through this issue we would like to request adding additional parameters (`xSalesLine` and `CurrFieldNo`) to the event publisher
`OnBeforeCheckPrepmtAmounts` in Table 37 `Sales Line` with the following signature:
old:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckPrepmtAmounts(var SalesLine: Record "Sales Line"; var IsHandled: Boolean)
begin
end;
```

new:
```AL
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckPrepmtAmounts(var SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line"; CurrFieldNo: Integer; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56629.
