### ISSUE TITLE
[Event Change Request] report 296 "Batch Post Sales Orders"

### ISSUE THREAD

**Issue by IesMeulmeester** [microsoft/ALAppExtensions#23013]
Hi,

Can you please change in report 296 "Batch Post Sales Orders" the event OnAfterOpen and add VATDateReq and ReplaceVATDateReq parameter:
![image](https://user-images.githubusercontent.com/2750351/232728809-1d70be95-db61-4b3e-95f0-7df38acb5b60.png)

And also update the code implementation in the OnOpenPage:
![image](https://user-images.githubusercontent.com/2750351/232728464-4c74adca-16cd-4840-aa67-887686e2130e.png)
Add line ReplaceVATDateReq := false;
Add VATDateReq and ReplaceVATDateReq parameter to OnAfterOpen event

**Comment by AleksandricMarko** [comment]
Parameters ReplaceVATDateReq and VATDateReq already exist in event OnAfterOnOpenPage
Event already implemented by other request(s).
It is or will be available in some of the next releases.
