### ISSUE TITLE
[Access Request] table 27 Item IsVariantMandatory 

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23027]
Could you please remove the access scope of the procedure `IsVariantMandatory`?
```al
//+Change
//-internal procedure IsVariantMandatory(IsTypeItem: Boolean; ItemNo: Code[20]): Boolean
procedure IsVariantMandatory(IsTypeItem: Boolean; ItemNo: Code[20]): Boolean
//-Change
    begin
        if IsTypeItem and (ItemNo <> '') then
            exit(IsVariantMandatory(ItemNo));
        exit(false)
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10652.
