### ISSUE TITLE
[Event Request] Table 5741 "Transfer Line" 

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#23022]
Please add the xrec to the existing event OnValidateUnitofMeasureCodeOnBeforeValidateQuantity:

old:
    [IntegrationEvent(false, false)]
    local procedure OnValidateUnitofMeasureCodeOnBeforeValidateQuantity(var TransferLine: Record "Transfer Line"; Item: Record Item)
    begin
    end;

new:
    [IntegrationEvent(false, false)]
    local procedure OnValidateUnitofMeasureCodeOnBeforeValidateQuantity(var TransferLine: Record "Transfer Line"; Item: Record Item;xTransferLine: Record "Transfer Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10806.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56637.
