### ISSUE TITLE
[Event Request] table 5876 "Phys. Invt. Order Line" - OnBeforeCheckLine

### ISSUE THREAD

**Issue by iCutura** [microsoft/ALAppExtensions#23038]
procedure CheckLine()
    var
        IsHandled: Boolean; // NEW LINE
    begin
        // New code - start
        OnBeforeCheckLine(Rec, IsHandled);
        if IsHandled then
            exit;
        // New code - end
        TestField("Item No.");
        TestField("Qty. Exp. Calculated", true);
        TestQtyExpected();
        TestField("On Recording Lines", true);
        TestQtyRecorded();
    end;

    // New code - start
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckLine(var Rec: Record "Phys. Invt. Order Line"; var IsHandled: Boolean)
    begin
    end;
    // New code - end

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10881.
