### ISSUE TITLE
[Event Request] codeunit 5876 "Phys. Invt. Rec.-Finish"

### ISSUE THREAD

**Issue by iCutura** [microsoft/ALAppExtensions#23039]
LineCount := LineCount + 1;
                    if not HideProgressWindow then
                        Window.Update(2, LineCount);

                    if not PhysInvtRecordLine.EmptyLine() then begin
                        // New Code - start
                        IsHandled := false;
                        OnBeforeCheckPhysInvtRecLine(PhysInvtRecordLine, IsHandled);
                        if not IsHandled then begin
                        // New Code - end
                            PhysInvtRecordLine.TestField("Item No.");
                            PhysInvtRecordLine.TestField(Recorded, true);
                            if PhysInvtRecordLine."Location Code" <> '' then begin
                                Location.Get(PhysInvtRecordLine."Location Code");
                                CheckLocationDirectedPutAwayAndPick();
                                if Location."Bin Mandatory" then
                                    PhysInvtRecordLine.TestField("Bin Code")
                                else
                                    PhysInvtRecordLine.TestField("Bin Code", '');
                            end else begin
                                if InvtSetup."Location Mandatory" then
                                    PhysInvtRecordLine.TestField("Location Code");
                                PhysInvtRecordLine.TestField("Bin Code", '');
                            end;
                        end; // New Line
                        IsHandled := false;
                        OnBeforeGetSamePhysInvtOrderLine(PhysInvtOrderLine, PhysInvtRecordLine, NoOfOrderLines, ErrorText, IsHandled);

// Integration Event

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckPhysInvtRecLine(PhysInvtRecordLine: Record "Phys. Invt. Record Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10881.
