### ISSUE TITLE
Request for hotfix : securityfiltering

### ISSUE THREAD

**Issue by Shortlife79** [microsoft/ALAppExtensions#23033]
I am requesting a hotfix for following issue : 

In codeunit 12 "Gen. Jnl.-Post Line" our customer is having an issue when posting purchase invoice.

He's getting following error (translated from dutch) : 

"There is a security filtering executed on Detailed Vendor Ledger Entry.  Records which are outside this filter,...

==> before the findlast the following code must be added : DtldCVLedgEntryBuf.SecurityFiltering := DtldCVLedgEntryBuf.securityfiltering::ignored;

codeunit 12 "Gen. Jnl.-Post Line"

 procedure PostDtldVendLedgEntries(GenJnlLine: Record "Gen. Journal Line"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; VendPostingGr: Record "Vendor Posting Group"; LedgEntryInserted: Boolean) DtldLedgEntryInserted: Boolean
    var
        TempDimPostingBuffer: Record "Dimension Posting Buffer" temporary;
        DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry";
        AdjAmount: array[4] of Decimal;
        DtldVendLedgEntryNoOffset: Integer;
        SaveEntryNo: Integer;
        IsHandled: Boolean;
    begin
        if GenJnlLine."Account Type" <> GenJnlLine."Account Type"::Vendor then
            exit;

        if DtldVendLedgEntry.FindLast() then
            DtldVendLedgEntryNoOffset := DtldVendLedgEntry."Entry No."
        else
            DtldVendLedgEntryNoOffset := 0;

**Comment by AlexanderYakunin** [comment]
You are right, but hotfix should be requested using technical support, if you want to get it soon. We are not processing bug requests here and have no SLA for fixing such issues
