### ISSUE TITLE
[Access Change Request] table 39 "Purchase Line" - global variables "ItemReferenceMgt"

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#23032]
Hi,
could you change the access of the global variable `ItemReferenceMgt` in the `Purchase Line` table to protected please?
Thanks.

**Comment by AlexanderYakunin** [comment]
Can you simply define this variable in your extension? It is just code.

**Comment by KevinHermsdorf** [comment]
Okay i will try that. Thank you.
