### ISSUE TITLE
[Event Request] OnInitSourceDocumentOnBeforeTransLineLoopIteration in codeunit 7324 "Whse.-Activity-Post"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#23031]
Please add a new trigger OnInitSourceDocumentOnBeforeTransLineLoopIteration similar to OnInitSourceDocumentOnBeforePurchLineLoopIteration and OnInitSourceDocumentOnBeforeSalesLineLoopIteration in codeunit 7324 "Whse.-Activity-Post" in Procedure InitSourceDocument:

    [IntegrationEvent(false, false)]
    local procedure OnInitSourceDocumentOnBeforeTransLineLoopIteration(TransferHeader: Record "Transfer Header"; var TransferLine: Record "TransferLine"; WarehouseActivityHeader: Record "Warehouse Activity Header"; var IsHandled: Boolean)
    begin
    end;

local procedure InitSourceDocument()
...
                DATABASE::"Transfer Line":
                    begin
                        TransHeader.Get("Source No.");
                        TransLine.SetRange("Document No.", TransHeader."No.");
                        TransLine.SetRange("Derived From Line No.", 0);
                        TransLine.SetFilter("Item No.", '<>%1', '');
                        OnInitSourceDocumentOnAfterTransLineSetFilters(TransLine, TransHeader, WhseActivHeader);
                        if TransLine.Find('-') then
                            repeat
                                IsHandled := false;
                                OnInitSourceDocumentOnBeforeTransLineLoopIteration(TransHeader, TransLine, WhseActivHeader, IsHandled);
                                if not IsHandled then begin

                                   TransLine.Validate("Qty. to Ship", 0);
                                   TransLine.Validate("Qty. to Receive", 0);
                                   ModifyTransferLine(TransLine);
                                   OnAfterTransLineModify(TransLine);
                                 end;
                               until TransLine.Next() = 0;

                        OnInitSourceDocumentOnAfterTransferLineLoopIteration(TransLine, TransHeader, WhseActivHeader, ModifyHeader);

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10820.
