### ISSUE TITLE
[Suggestion] Show negative Credit amount on G/L Trial Balance report

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#23043]
Hi Microsoft AL Development Team,

The **G/L Trial Balance** report is not showing debit amount that was posted as negative credits. This is due to the 
`BlankNegAndZero` function on the Credit amount fields in the RLDC layout.

Clients can have negative credit amount posted when they apply a payment, unapply it and re-apply it, resulting in a negative credit amount.

![image](https://user-images.githubusercontent.com/69611495/233223237-7ed32ee0-c1eb-45e3-9b4d-b7b1907be4a9.png)

Could you change the following field to `BlankZero`?

![image](https://user-images.githubusercontent.com/69611495/233223619-23268cbc-b2b9-4ef2-a2ea-173f8f3104ce.png)

Thank you.

Kind regards,
Tuan Nguyen

**Comment by AlexanderYakunin** [comment]
We cannot help with functional issues, extensibility only.
