### ISSUE TITLE
[Event Request] table 36 "Sales Header" - Handled pattern before System.LogMessage

### ISSUE THREAD

**Issue by NAVFreak** [microsoft/ALAppExtensions#23042]
We are running a customer OnPrem and we have an oldschool sales price calculation by creating a temporary sales order with lines to get sales prices with all discounts and extra fees (partner extension).

The problem is that we generate thousands of sales prices by doing this and everytime we do it the eventviewer get clogged with Microsofts own telemetry data loggin from sales header. 
![image](https://user-images.githubusercontent.com/34970096/233191726-6e0cf994-fcae-4e7e-bfd1-17fd0ca8f639.png)

Currently we can't hardly troubleshoot in the eventviewer anymore because all these warnings fills upp the eventviewer so fast that we barely have time to look up the error we are troubleshooting before the eventviewer is truncated.
As you see here it fills upp very fast.
![image](https://user-images.githubusercontent.com/34970096/233192537-b9426640-9cc1-4a33-85c6-21c4e8d7e88e.png)

I know you have it for a reason but can you please add a handled pattern before EACH logging of this in salesheader so we who run onprem can turn it off so we can do proper troubleshooting in the eventlog.

In the version I'm in there are currently 5 logmessage that should get this
![image](https://user-images.githubusercontent.com/34970096/233193282-791c2e28-f12d-4ab3-bfcb-83ae9dd2d2e4.png)

**Comment by tomasevics** [comment]
We have added event on validate "VAT Base Discount %" field, so you can skip execution of procedure UpdateSalesLineAmounts. This procedure is called only on validate "VAT Base Discount %" field.
https://github.com/microsoft/ALAppExtensions/issues/23158
