### ISSUE TITLE
Intrastat issue(?) - Handling with temporary salesheader

### ISSUE THREAD

**Issue by NAVFreak** [microsoft/ALAppExtensions#23041]
I was investigating which ways led to Session.LogMessage('0000G95' and then I discoved that I ended up there via the intrastat app.

Suggestion is to add so this code won't execute if the salesheader.isTemporary() in [tableextension "Intrastat Report Sales head."](https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/Intrastat/app/src/IntrastatReportSalesHead.TableExt.al)

```
tableextension 4815 "Intrastat Report Sales Head." extends "Sales Header" 
{
    fields
    {
        modify("Sell-to Customer No.")
        {
            trigger OnAfterValidate()
            begin
                if IntrastatReportSetup.Get() and (IntrastatReportSetup."VAT No. Based On" = IntrastatReportSetup."VAT No. Based On"::"Sell-to VAT") then
                    UpdateIntrastatFields("Sell-to Customer No.");
            end;
        }
```

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56913.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10881.
