### ISSUE TITLE
[Event Request] Table 5740 "Transfer Header" - OnBeforeCreateDimFromDefaultDim

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#23040]
Request a new event in function CreateDimFromDefaultDim in table 5740 "Transfer Header":

```
procedure CreateDimFromDefaultDim(FieldNo: Integer)
var
    DefaultDimSource: List of [Dictionary of [Integer, Code[20]]];
    IsHandled: Boolean      //NEW
begin
    //NEW - start
    IsHandled := false;
    OnBeforeCreateDimFromDefaultDim(Rec, FieldNo, IsHandled);
    if IsHandled then
        exit;
    //NEW - end

    InitDefaultDimensionSources(DefaultDimSource, FieldNo);
    CreateDim(DefaultDimSource);
end;

//NEW
[IntegrationEvent(false, false)]
local procedure OnBeforeCreateDimFromDefaultDim(var TransferHeader: Record "Transfer Header"; FieldNo: Integer; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10806.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56637.
