### ISSUE TITLE
[Access Request] page 254 "Purchase Journal"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23056]
Could you please change the access scope for the following variable.
```al
protected var
    IsSimplePage: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10652.
