### ISSUE TITLE
[Access Request] page 9150 "My Customers"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23055]
Could you please change the access scope of the following variable to protected ?
```al
protected var
    Customer: Record Customer;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10652.
