### ISSUE TITLE
[Access Request] table 130 "Incoming Document" - RemoveIncomingDocumentEntryNoFromUnpostedDocument

### ISSUE THREAD

**Issue by LyndenWorrall** [microsoft/ALAppExtensions#23061]
Can local procedure RemoveIncomingDocumentEntryNoFromUnpostedDocument be made public?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10652.
