### ISSUE TITLE
MatrixPages

### ISSUE THREAD

**Issue by 4dimit** [microsoft/ALAppExtensions#23069]
I have a problem with matrixpages is giving an error.

Is it possible to change CU9200 til handle 100 columns instead of only 32 in these procedures?

procedure DimToCaptions
procedure GenerateMatrixData
procedure GenerateMatrixDataExtended
procedure GeneratePeriodMatrixData
procedure GeneratePeriodAndCaption
procedure GenerateDimColumnCaption

**Comment by AlexanderYakunin** [comment]
No, this is breaking change. If you have good business reason for that, you can create new Idea for this feature.

**Comment by 4dimit** [comment]
Yes we have a customer where they on a job create budgets(job planning lines) and has job task in rows and something they call modules in columns. All jobs has more than 100 job tasks and a job can have up to 99 modules, but in reality it is usally between 10 and 40.
It will be a deal breaker for them to upgrade without this functionality.

**Comment by AlexanderYakunin** [comment]
We cannot do that. but you can use your own page with such changes instead of ours. It is very easy and you can solve you problem without disturbing other customer and partners.
