### ISSUE TITLE
Request for Option to Enum Unit Cost Calculation

### ISSUE THREAD

**Issue by rickblommetjes** [microsoft/ALAppExtensions#23060]
For Table "Prod. Order Routing Line" 

field(76; "Unit Cost Calculation"; Option)
        {
            Caption = 'Unit Cost Calculation';
            OptionCaption = 'Time,Units';
            OptionMembers = Time,Units;
        }

We would like to have an extendable enum instead, so we can extend the way subcontracting is calculated with more options:

field(76;"Unit Cost Calculation";Option)
        {
            Caption = 'Unit Cost Calculation';
            Description = 'EMFGW113.00.01  Added option Weight, Area and Unit Volume';
            OptionCaption = 'Time,Units,Weight,Area,Unit Volume';
            OptionMembers = Time,Units,Weight,"Area","Unit Volume";
        }

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10585.
