### ISSUE TITLE
[Event Request] Codeunit Purch. Line-Reserve 99000834 FunctionReservQuantity

### ISSUE THREAD

**Issue by DamianoCastagna** [microsoft/ALAppExtensions#23064]
Please Add the event OnAfterReservQuantity into function ReservQuantity on codeunit Purch. Line-reserve

![PurchLine-Reserve](https://user-images.githubusercontent.com/118895493/233313639-2ea3244c-ae36-43d7-b689-6977a4cc6e0f.jpg)

Just like it is in codeunit Sales Line-reserve

![SalesLine-Reserve](https://user-images.githubusercontent.com/118895493/233313643-efcf9ac4-35d8-4ccd-a2be-578687757979.jpg)

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56679.
