### ISSUE TITLE
[Extensibility Enhancement] Enum 337 "Reservation Status" Extensible Property

### ISSUE THREAD

**Issue by UIBKH** [microsoft/ALAppExtensions#23070]
Dear team,

When will [#21913](https://github.com/microsoft/ALAppExtensions/issues/21913) be available in the base application?
It was closed and labelled with build ID 53910, but we cannot find it in the latest package. Was this skipped for a reason? This is becoming urgent for migrating our customizations.
![image](https://user-images.githubusercontent.com/123063346/233338991-f2839323-ade5-420e-bc7a-902025262793.png)

Thank you for your help.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 55756.
