### ISSUE TITLE
[Event Request] Page 42 - "Sales Order " - new events OnBeforeOnQueryClosePage and OnBeforeConfirmCloseUnposted

### ISSUE THREAD

**Issue by IanaAsofiei** [microsoft/ALAppExtensions#23076]
Dear Support,

We would like to add 2 new events OnBeforeOnQueryClosePage and OnBeforeConfirmCloseUnposted inside OnQueryClosePage trigger from "Sales Order" page. This would allow us to avoid pop-up messages on closiung a sales order page.

trigger OnQueryClosePage(CloseAction: Action): Boolean
var
	InstructionMgt: Codeunit "Instruction Mgt.";
begin
	OnBeforeOnQueryClosePage(DocumentIsScheduledForPosting);
	if not DocumentIsScheduledForPosting and ShowReleaseNotification() then
		if not InstructionMgt.ShowConfirmUnreleased() then
			exit(false);
	OnBeforeConfirmCloseUnposted(DocumentIsPosted);
	if not DocumentIsPosted then
		exit(ConfirmCloseUnposted());
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeOnQueryClosePage(var DocumentIsScheduledForPosting: Boolean)
begin
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeConfirmCloseUnposted(var DocumentIsPosted: Boolean)
begin
end;

**Comment by IanaAsofiei** [comment]
Hi,
Thank you very much for implementing the new requested event subscribers.
Can you let us know when the fix for these event subscribers will be published:
https://github.com/microsoft/ALAppExtensions/issues/23076
https://github.com/microsoft/ALAppExtensions/issues/23029

We have a deadline from our client and we need this event subscriber to be implemented also as soon as possible:
 https://github.com/microsoft/ALAppExtensions/issues/22542

Thank you.

**Comment by JesperSchulz** [comment]
The two implemented subscribers look to ship with 22.2 in a couple of days. I will ping our "event team" about the pending one.
