### ISSUE TITLE
[Event Request] - OnBeforeIsDefaultDimDefinedForTable Table 39 "Purchase Line"

### ISSUE THREAD

**Issue by dynavision-nj** [microsoft/ALAppExtensions#23085]
Hello, please consider adding the following event to Table 39 "Purchase Line"

    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsDefaultDimDefinedForTable(PurchaseLine: Record "Purchase Line"; DefaultDimSource: List of [Dictionary of [Integer, Code[20]]]; FieldNo: Integer; var IsHandled: Boolean)
    begin
    end;

and call it accordingly inside the "CreateDimFromDefaultDim" procedure:

    procedure CreateDimFromDefaultDim(FieldNo: Integer)
    var
        DefaultDimSource: List of [Dictionary of [Integer, Code[20]]];
    begin
        InitDefaultDimensionSources(DefaultDimSource, FieldNo);

        //Change
        IsHandled := false;
        OnBeforeIsDefaultDimDefinedForTable(Rec, DefaultDimSource, FieldNo, IsHandled);
        if IsHandled then
            exit;
        //Change

        if DimMgt.IsDefaultDimDefinedForTable(GetTableValuePair(FieldNo)) then
            CreateDim(DefaultDimSource);
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10788.
