### ISSUE TITLE
[Event Request] Page 113 Budget

### ISSUE THREAD

**Issue by PeterSchoenmaker** [microsoft/ALAppExtensions#23080]
Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnOpenPageOnBeforeSettingPeriodType' to be added to trigger 'OnOpenPage' in Page 113 "Budget";

----
        IsHandled := false;
        OnOpenPageOnBeforeSettingPeriodType(PeriodType, IsHandled);
        if not IsHandled then
----
            PeriodType := PeriodType::Month;

----
    [IntegrationEvent(false, false)]
    local procedure OnOpenPageOnBeforeSettingPeriodType(var PeriodType: Enum "Analysis Period Type"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56811.
