### ISSUE TITLE
[Event Update Request] - table 96 "G/L Budget Entry" - OnBeforeVerifyNoRelatedAnalysisViewBudgetEntries

### ISSUE THREAD

**Issue by LyndenWorrall** [microsoft/ALAppExtensions#23092]
Can existing integration event OnBeforeVerifyNoRelatedAnalysisViewBudgetEntries be modified to use the IsHandled pattern?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10881.
