### ISSUE TITLE
[Event Request] Table 37- "Purchase Line" - OnBeforeValidateJobTaskNo

### ISSUE THREAD

**Issue by KevinHermsdorf** [microsoft/ALAppExtensions#23099]
Dear ALAppExtensions team,

through this issue we would like to request adding the additional parameter (TempJobJnlLine) to the event publisher
`OnBeforeValidateJobTaskNo` in Table 39 `Purchase Line` with the following signature:
old:
```AL
[IntegrationEvent(true, false)]
local procedure OnBeforeValidateJobTaskNo(xPurchaseLine: Record "Purchase Line"; var IsHandled: Boolean; CurrentFieldNo: Integer)
begin
end;
```
new:
```AL
[IntegrationEvent(true, false)]
local procedure OnBeforeValidateJobTaskNo(xPurchaseLine: Record "Purchase Line"; var IsHandled: Boolean; CurrentFieldNo: Integer; var TempJobJnlLine: Record "Job Journal Line" temporary)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10788.
