### ISSUE TITLE
[Event Request] table 39 "Purchase Line" - OnAfterCreateDimFromDefaultDim

### ISSUE THREAD

**Issue by dynavision-nj** [microsoft/ALAppExtensions#23096]
Please add new integration event and call as follows:

    // ---- New code start ----
    [IntegrationEvent(false, false)]
    local procedure OnAfterCreateDimFromDefaultDim(var PurchaseLine: Record "Purchase Line"; var DefaultDimSource: List of [Dictionary of [Integer, Code[20]]]; FieldNo: Integer)
    begin
    end;
    // ---- New code end ----

    procedure CreateDimFromDefaultDim(FieldNo: Integer)
    var
        DefaultDimSource: List of [Dictionary of [Integer, Code[20]]];
    begin
        InitDefaultDimensionSources(DefaultDimSource, FieldNo);
        if DimMgt.IsDefaultDimDefinedForTable(GetTableValuePair(FieldNo)) then
            CreateDim(DefaultDimSource);
       
        // ---- New code start ----
        OnAfterCreateDimFromDefaultDim(Rec, DefaultDimSource, FieldNo); 
        // ---- New code end ----
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10788.
