### ISSUE TITLE
Show the Field to the page "Report Selection - Sales"

### ISSUE THREAD

**Issue by robertoscaringella** [Microsoft/ALAppExtensions#231]
Hi,
I suggest to show this field "Custom Report Layout Code" on the page "Report Selection - Sales" because it need to setup different layout for the same report.

The code for manage already exist, but without this field it' is impossible to use this functionality.
I suggest also to add the same field for the other "Report Selection" Pages.

Best Regards,
Roberto.

**Comment by JesperSchulz** [comment]
Thank you for your suggestion. However, this GitHub repository is dedicated to handling issues with published apps and extensibility requests for the latest release of Business Central only.

To register your idea please use one of the following resources:

- For functional improvements, go to [Business Central - Ideas](http://aka.ms/bcideas)
- For feature suggestions for AL compiler and developer tools, see [Github.com/Microsoft/AL](https://github.com/Microsoft/AL/issues)
