### ISSUE TITLE
codeunit 1105 "Transfer GL Entries to CA" - OnGetGLEntriesOnBeforeCombineEntries

### ISSUE THREAD

**Issue by Henriquantos** [microsoft/ALAppExtensions#23103]
Can you please add the argument <CostObjectCode> to the OnGetGLEntriesOnBeforeCombineEntries event in Codeunit "Transfer GL Entries to CA" (1105)? The name of the variable on the integration event is already CostObjectCode but in the code it is receiving CostCenterCode.

Actual Code:

    procedure GetGLEntries()
    var
        SourceCodeSetup: Record "Source Code Setup";
        CostCenterCode: Code[20];
        CostObjectCode: Code[20];
        CombinedEntryText: Text[50];
        CombineEntries: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetGLEntries(IsHandled);
        if IsHandled then
            exit;

        GetCostAccSetup();
        SourceCodeSetup.Get();
        SourceCodeSetup.TestField("G/L Entry to CA");

        if not BatchRun then begin
            if not CostAccSetup."Auto Transfer from G/L" then
                exit;
            TempCostJnlLine.DeleteAll();
            ClearAll();
            GetCostAccSetup();
        end;

        CostRegister.LockTable();
        CostRegister.SetCurrentKey(Source);
        CostRegister.SetRange(Source, CostRegister.Source::"Transfer from G/L");
        if CostRegister.FindLast() then
            FirstGLEntryNo := CostRegister."To G/L Entry No." + 1
        else
            FirstGLEntryNo := 1;

        if GLEntry.FindLast() then
            LastGLEntryNo := GLEntry."Entry No.";

        GLEntry.SetRange("Entry No.", FirstGLEntryNo, LastGLEntryNo);
        GLEntry.SetFilter("Posting Date", '%1..', CostAccSetup."Starting Date for G/L Transfer");
        OnGetGLEntriesOnAfterSetGLEntryFilters(GLEntry, FirstGLEntryNo, LastGLEntryNo, CostAccSetup."Starting Date for G/L Transfer");
        if GLEntry.FindSet() then
            repeat
                if BatchRun and ((GLEntry."Entry No." mod 100) = 0) then
                    Window.Update(1, Format(GLEntry."Entry No."));
                CostCenterCode := '';
                CostObjectCode := '';

                if not SkipGLEntry(GLEntry) then
                    case true of // only need Cost Center or Cost Object
                        GetCostCenterCode(GLEntry."Dimension Set ID", CostCenterCode),
                        GetCostObjectCode(GLEntry."Dimension Set ID", CostObjectCode):
                            begin
                                case CostType."Combine Entries" of
                                    CostType."Combine Entries"::None:
                                        PostingDate := GLEntry."Posting Date";
                                    CostType."Combine Entries"::Month:
                                        begin
                                            PostingDate := CalcDate('<CM>', GLEntry."Posting Date");
                                            CombinedEntryText := StrSubstNo(Text003, PostingDate);
                                        end;
                                    CostType."Combine Entries"::Day:
                                        begin
                                            PostingDate := GLEntry."Posting Date";
                                            CombinedEntryText := StrSubstNo(Text004, PostingDate);
                                        end;
                                end;

                                CombineEntries := CostType."Combine Entries" <> CostType."Combine Entries"::None;
                                OnGetGLEntriesOnBeforeCombineEntries(CostCenterCode, GLEntry, CostType, CombineEntries);
                                if CombineEntries then begin
                                    TempCostJnlLine.Reset();
                                    TempCostJnlLine.SetRange("Cost Type No.", CostType."No.");
                                    if CostCenterCode <> '' then
                                        TempCostJnlLine.SetRange("Cost Center Code", CostCenterCode)
                                    else
                                        TempCostJnlLine.SetRange("Cost Object Code", CostObjectCode);
                                    TempCostJnlLine.SetRange("Posting Date", PostingDate);
                                    if TempCostJnlLine.FindFirst() then
                                        ModifyCostJournalLine(CombinedEntryText)
                                    else
                                        InsertCostJournalLine(CostCenterCode, CostObjectCode);
                                end else
                                    InsertCostJournalLine(CostCenterCode, CostObjectCode);

                                if BatchRun and ((GLEntry."Entry No." mod 100) = 0) then begin
                                    Window.Update(2, CostType."No.");
                                    Window.Update(3, Format(NoOfCombinedEntries));
                                    Window.Update(4, Format(NoOfJnlLines));
                                end;
                            end;
                    end;
            until GLEntry.Next() = 0;

        OnAfterPrepareCostJournalLines(TempCostJnlLine, TotalDebit, TotalCredit, NoOfJnlLines, BatchRun);

        if NoOfJnlLines = 0 then begin
            if BatchRun then begin
                Window.Close();
                Error(Text005);
            end;
            exit;
        end;

        PostCostJournalLines();
    end;

    [IntegrationEvent(false, false)]
    local procedure OnGetGLEntriesOnBeforeCombineEntries(var CostObjectCode: Code[20]; GLEntry: Record "G/L Entry"; CostType: Record "Cost Type"; var CombineEntries: Boolean)
    begin
    end;

Suggestion:

    procedure GetGLEntries()
    var
        SourceCodeSetup: Record "Source Code Setup";
        CostCenterCode: Code[20];
        CostObjectCode: Code[20];
        CombinedEntryText: Text[50];
        CombineEntries: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetGLEntries(IsHandled);
        if IsHandled then
            exit;

        GetCostAccSetup();
        SourceCodeSetup.Get();
        SourceCodeSetup.TestField("G/L Entry to CA");

        if not BatchRun then begin
            if not CostAccSetup."Auto Transfer from G/L" then
                exit;
            TempCostJnlLine.DeleteAll();
            ClearAll();
            GetCostAccSetup();
        end;

        CostRegister.LockTable();
        CostRegister.SetCurrentKey(Source);
        CostRegister.SetRange(Source, CostRegister.Source::"Transfer from G/L");
        if CostRegister.FindLast() then
            FirstGLEntryNo := CostRegister."To G/L Entry No." + 1
        else
            FirstGLEntryNo := 1;

        if GLEntry.FindLast() then
            LastGLEntryNo := GLEntry."Entry No.";

        GLEntry.SetRange("Entry No.", FirstGLEntryNo, LastGLEntryNo);
        GLEntry.SetFilter("Posting Date", '%1..', CostAccSetup."Starting Date for G/L Transfer");
        OnGetGLEntriesOnAfterSetGLEntryFilters(GLEntry, FirstGLEntryNo, LastGLEntryNo, CostAccSetup."Starting Date for G/L Transfer");
        if GLEntry.FindSet() then
            repeat
                if BatchRun and ((GLEntry."Entry No." mod 100) = 0) then
                    Window.Update(1, Format(GLEntry."Entry No."));
                CostCenterCode := '';
                CostObjectCode := '';

                if not SkipGLEntry(GLEntry) then
                    case true of // only need Cost Center or Cost Object
                        GetCostCenterCode(GLEntry."Dimension Set ID", CostCenterCode),
                        GetCostObjectCode(GLEntry."Dimension Set ID", CostObjectCode):
                            begin
                                case CostType."Combine Entries" of
                                    CostType."Combine Entries"::None:
                                        PostingDate := GLEntry."Posting Date";
                                    CostType."Combine Entries"::Month:
                                        begin
                                            PostingDate := CalcDate('<CM>', GLEntry."Posting Date");
                                            CombinedEntryText := StrSubstNo(Text003, PostingDate);
                                        end;
                                    CostType."Combine Entries"::Day:
                                        begin
                                            PostingDate := GLEntry."Posting Date";
                                            CombinedEntryText := StrSubstNo(Text004, PostingDate);
                                        end;
                                end;

                                CombineEntries := CostType."Combine Entries" <> CostType."Combine Entries"::None;
                                OnGetGLEntriesOnBeforeCombineEntries(CostCenterCode, CostObjectCode, GLEntry, CostType, CombineEntries);
                                if CombineEntries then begin
                                    TempCostJnlLine.Reset();
                                    TempCostJnlLine.SetRange("Cost Type No.", CostType."No.");
                                    if CostCenterCode <> '' then
                                        TempCostJnlLine.SetRange("Cost Center Code", CostCenterCode)
                                    else
                                        TempCostJnlLine.SetRange("Cost Object Code", CostObjectCode);
                                    TempCostJnlLine.SetRange("Posting Date", PostingDate);
                                    if TempCostJnlLine.FindFirst() then
                                        ModifyCostJournalLine(CombinedEntryText)
                                    else
                                        InsertCostJournalLine(CostCenterCode, CostObjectCode);
                                end else
                                    InsertCostJournalLine(CostCenterCode, CostObjectCode);

                                if BatchRun and ((GLEntry."Entry No." mod 100) = 0) then begin
                                    Window.Update(2, CostType."No.");
                                    Window.Update(3, Format(NoOfCombinedEntries));
                                    Window.Update(4, Format(NoOfJnlLines));
                                end;
                            end;
                    end;
            until GLEntry.Next() = 0;

        OnAfterPrepareCostJournalLines(TempCostJnlLine, TotalDebit, TotalCredit, NoOfJnlLines, BatchRun);

        if NoOfJnlLines = 0 then begin
            if BatchRun then begin
                Window.Close();
                Error(Text005);
            end;
            exit;
        end;

        PostCostJournalLines();
    end;

    [IntegrationEvent(false, false)]
    local procedure OnGetGLEntriesOnBeforeCombineEntries(var CostCenterCode: Code[20]; var CostObjectCode: Code[20]; GLEntry: Record "G/L Entry"; CostType: Record "Cost Type"; var CombineEntries: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10806.
