### ISSUE TITLE
[Request-For-External] Page 7604 "Base Calendar Entries Subform" - Procedure from Internal to Global	

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#23105]
Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

[Request-For-External] Page 7604 "Base Calendar Entries Subform" - Procedure from Internal to Global
```
    procedure UpdateBaseCalendarChanges()
    var
        BaseCalendarChange: Record "Base Calendar Change";
    begin
        BaseCalendarChange.Reset();	
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10652.

**Comment by fvet** [comment]
@JesperSchulz Didn't find this one in 22.2. Any chance to backport to BC nextminor?

**Comment by JesperSchulz** [comment]
We normally don't backport these issues, but I'll make an exception for you :-) Expect the changes to be in 22.4.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 58563.
