### ISSUE TITLE
[Extensibility Enhancement] Page 30 "Item Card" - Protected Var ProfitEditable/PriceEditable

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#23100]
Hello,

I was wondering if you can make ProfitEditable and PriceEditable variables to protected var so we can handle them when add more enums to "Enum 19 "Item Price Profit Calculation""

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10652.
