### ISSUE TITLE
media.findophans() AL ErrorCode:OutOfMemory:TargetInvocation Connection type:WebClient Message

### ISSUE THREAD

**Issue by GregP-Navdna** [microsoft/ALAppExtensions#23104]
I'm receiving this error when I attempt to use the media.findorphans() function. 
 I'm just trying to count how many there are and am receiving an out of memory exception. 

the Tenant Media	records: 75,673,411	size(kb) 62,930,232
this is the codeunit I've created to find the orphans

codeunit 50025 FindOrphanedRecords
{
    SingleInstance = true;
    procedure FindOrphanedRecords()
    var
        orphanedrecords: list of [guid];
        orphanedguid: guid;
        tb: textbuilder;
        logcounter: integer;
        eventID: label 'orphan counter';
    begin
        orphanedrecords := media.findorphans();

        foreach orphanedguid in orphanedrecords do begin
            logcounter += 1;
            if (logcounter mod 100000) = 0 then
                Session.LogMessage(EventId, STRSUBSTNO('Counter reached %1', logcounter), Verbosity::Normal, DataClassification::ToBeClassified, TelemetryScope::All, '', '');
            tb.appendline(format(orphanedguid));
        end;
        exportorphanedRecords(tb);
    end;

    local procedure exportorphanedRecords(var tb: TextBuilder)
    var
        tempblob: Codeunit "Temp Blob";
        exportfilename: text;
        outstr: OutStream;
        instr: InStream;
    begin
        exportfilename := 'c:\temp\orphanedrecords.txt';
        tempblob.CreateOutStream(outstr);
        tempblob.createinstream(instr);
        outstr.writetext(tb.totext());
        copystream(outstr, instr);
        DownloadFromStream(instr, '', '', '', exportfilename);
    end;
}

 AL ErrorCode:OutOfMemory:TargetInvocation Connection type:WebClient Message: StackTrace: FindOrphanedRecords(CodeUnit 50025).FindOrphanedRecords line 8 - 1Con_Changes by 1Con "Media Table View"(Page 50008)."FindOrphans - OnAction"(Trigger) line 4 

please let me know if there's any thing that can be done about this. as you can see the media table is quite large and it's making it so the copy company function does not work.

**Comment by AlexanderYakunin** [comment]
This is not a right place to make this request, we cannot help you here. Instead you need to contact technical support and create ticket for this issue.
