### ISSUE TITLE
[Event Request] Codeunit 30174 "Shpfy Create Product" OnAfterFilterItemVariant

### ISSUE THREAD

**Issue by JBBernad** [microsoft/ALAppExtensions#23102]
Hello. Could you please add event OnAfterFilterItemVariant to codeunit 30174 in the CreateTempProduct function?

        Clear(TempShopifyProduct);
        TempShopifyProduct."Shop Code" := Shop.Code;
        TempShopifyProduct."Item SystemId" := Item.SystemId;
        ProductExport.FillInProductFields(Item, TempShopifyProduct);
        ICreateProductStatus := Shop."Status for Created Products";
        TempShopifyProduct.Status := ICreateProductStatus.GetStatus(Item);
        ItemVariant.SetRange("Item No.", Item."No.");
        OnAfterFilterItemVariant(ItemVariant)
        if ItemVariant.FindSet(false, false) then
            repeat
                TempShopifyProduct."Has Variants" := true;
                if Shop."UoM as Variant" then begin

```
[IntegrationEvent(false, false)]
local procedure OnAfterFilterItemVariant(var ItemVariant: Record "Item Variant")
begin
end;
```

**Comment by AndreiPanko** [comment]
@JBBernad 
Are you trying to exclude blocked variants (custom field)?
Feel free to submit PR directly, the Shopify Connector app is available in this repository.
Remember to update the https://github.com/microsoft/ALAppExtensions/tree/main/Apps/W1/Shopify#extensibility file.

Sincerely,
Andrei Panko
PM, Microsoft
