### ISSUE TITLE
[Event Parameter Request] Codeunit 63 "Sales-Explode BOM" - OnBeforeConfirmExplosion

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#23112]
We would like the parameter NoOfBOMComp (var) added to the following event OnBeforeConfirmExplosion (Codeunit 63)

Original:

`OnBeforeConfirmExplosion(Rec, Selection, HideDialog);`
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeConfirmExplosion(var SalesLine: Record "Sales Line"; var Selection: Integer; var HideDialog: Boolean)
    begin
    end;
```

Changed:

`OnBeforeConfirmExplosion(Rec, Selection, HideDialog, NoOfBOMComp);`

```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeConfirmExplosion(var SalesLine: Record "Sales Line"; var Selection: Integer; var HideDialog: Boolean; var NoOBOMComp: Integer)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10879.
