### ISSUE TITLE
Table 5902 Service Line - function CalcChargeableQty - new event

### ISSUE THREAD

**Issue by karolstb** [microsoft/ALAppExtensions#23114]
Hello,
Could You add new event in function CalcChargeableQty on table 5902 Service Line?
Needed for customization how customer is charge for service (Line Amount etc.).

actual code:
```al
    procedure CalcChargeableQty(): Decimal
    begin
        exit(Quantity - "Quantity Consumed" - "Qty. to Consume");
    end;
```

suggestion:
```al
    procedure CalcChargeableQty(): Decimal
    var
        ChargableQty: Decimal;
    begin
        ChargableQty := Quantity - "Quantity Consumed" - "Qty. to Consume";
        OnAfterCalculateChargableQty(Rec, ChargableQty);
        exit(ChargableQty);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalculateChargableQty(ServiceLine: Record "Service Line"; var ChargableQty: Decimal)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10879.
