### ISSUE TITLE
[Event Request] table 39 "Purchase Line" - OnBeforeValidateLineAmount

### ISSUE THREAD

**Issue by jorland1** [microsoft/ALAppExtensions#23115]
Hi,
could you please add an event publisher `OnBeforeValidateLineAmount` to the `OnValidate` trigger of the `"Line Amount"` field?

The call would be:
``` al
field(103; "Line Amount"; Decimal)
{
    ...
    trigger OnValidate()
    var
        MaxLineAmount: Decimal;
        // >>> NEW
        IsHandled: Boolean;
        // <<< NEW
    begin
        // >>> NEW
        IsHandled := false;
        OnBeforeValidateLineAmount(Rec, xRec, CurrFieldNo, IsHandled, Currency);
        if IsHandled then
            exit;
        // <<< NEW

        TestField(Type);
        TestField(Quantity);
        CheckDirectUnitCost();
        ...
    end;
}
```

The signature would be:
``` al
[IntegrationEvent(false, false)]
local procedure OnBeforeValidateLineAmount(var PurchLine: Record "Purchase Line"; xPurchLine: Record "Purchase Line"; CurrentFieldNo: Integer; var IsHandled: Boolean; Currency: Record Currency)
```

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10788.
