### ISSUE TITLE
[Event Request] #19037 codeunit 80 "Sales-Post" - OnAfterInvoiceRounding

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#23121]
In #19037, I have asked for similar solution in 2 methods but there is no change for SumSalesLines2 in 23.0.10539.0 yet. And current UpdateInvoiceRounding solution in not usable there. Is it in your backlog?

**Comment by AlexanderYakunin** [comment]
We already added this one

    local procedure UpdateInvoiceRounding(var SalesHeader: Record "Sales Header"; BiggestLineNo: Integer)
    begin
        if RoundingLineInserted then
            LastLineRetrieved := true
        else begin
            BiggestLineNo := MAX(BiggestLineNo, TempSalesLineGlobal."Line No.");
            LastLineRetrieved := TempSalesLineGlobal.Next() = 0;
            if LastLineRetrieved and SalesSetup."Invoice Rounding" then
                InvoiceRounding(SalesHeader, TempSalesLineGlobal, false, BiggestLineNo);
        end;

        OnAfterUpdateInvoiceRounding(SalesHeader, TotalSalesLine, TempSalesLineGlobal, Currency, BiggestLineNo, LastLineRetrieved, RoundingLineInserted, RoundingLineNo);
    end;

**Comment by RadoArvay** [comment]
I am aware of that method. But I was writting about `SumSalesLines2` method and that is still without change.

And `UpdateInvoiceRounding` method you mentioned is, unfortunately, strictly prepared for `ProcessPostingLines` loop because it uses global variables instead of parameters so even it cannot be used/implemented into SumSalesLines2.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11007.
