### ISSUE TITLE
table 38 "Purchase Header" - add integration event in procedure PrintRecords 

### ISSUE THREAD

**Issue by isolsona** [microsoft/ALAppExtensions#23126]
Similar to the event  in SendRecords functions in Purchase Header, please extends IntegrationEvent in function:

-  PrintRecords
- SendProfile

    procedure SendRecords()
    var
        DocumentSendingProfile: Record "Document Sending Profile";
        ReportSelections: Record "Report Selections";
        DocTxt: Text[150];
        IsHandled: Boolean;
    begin

        ****IsHandled := false;
        OnBeforeSendRecords(Rec, IsHandled);
        if IsHandled then
            exit;****

        CheckMixedDropShipment();
        OnSendRecordsOnAfterCheckMixedDropShipment(Rec);

    procedure PrintRecords(ShowRequestForm: Boolean)
    var
        DocumentSendingProfile: Record "Document Sending Profile";
        DummyReportSelections: Record "Report Selections";
        IsHandled: Boolean;
    begin

        ### //ADD Similar event

        CheckMixedDropShipment();
        OnPrintRecordsOnAfterCheckMixedDropShipment(Rec);

        IsHandled := false;
        OnPrintRecordsOnBeforeTrySendToPrinterVendor(Rec, IsHandled, ShowRequestForm);

    procedure SendProfile(var DocumentSendingProfile: Record "Document Sending Profile")
    var
        DummyReportSelections: Record "Report Selections";
        ReportDistributionMgt: Codeunit "Report Distribution Management";
        IsHandled: Boolean;
    begin

        ### //ADD Similar event
        CheckMixedDropShipment();
        IsHandled := false;
        OnSendProfileOnBeforeSendVendor(Rec, IsHandled);

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10881.
