### ISSUE TITLE
Remove scope OnPrem from page 12172 "Posted Payments" procedure UpdateAmount()

### ISSUE THREAD

**Issue by AngeloCopelli** [microsoft/ALAppExtensions#23129]
In order to be able to change target to cloud, please remove the scope OnPrem from the following function:

page 12172 "Posted Payments"

[Scope('OnPrem')]
procedure UpdateAmount()

Thank you very much

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10762.
