### ISSUE TITLE
[Event Parameter] codeunit 5780 "Whse. Cross-Dock Management" - OnCalcCrossDockToTransferOrderOnAfterTransferLineSetFilters

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#23125]
Can you please add parameter `WhseCrossDockOpp` (with var access) and `LocationCode` to OnCalcCrossDockToTransferOrderOnAfterTransferLineSetFilters in codeunit 5780 "Whse. Cross-Dock Management"? 

_Similar to how  `WhseCrossDockOpp` and `LocationCode` are already made available in OnCalcCrossDockToServiceOrderOnAfterServiceLineSetFilters and OnCalcCrossDockToSalesOrderOnAfterSalesLineSetFilters._

**Before**

`OnCalcCrossDockToTransferOrderOnAfterTransferLineSetFilters(TransferLine);`

**After**

`OnCalcCrossDockToTransferOrderOnAfterTransferLineSetFilters(TransferLine, WhseCrossDockOpp, LocationCode);`

---

PS: To avoid future issues on adding another batch of missing parameters, I would suggest to keep the event signature inline with the 2 above mentioned existing publishers for looping sales / service lines.

**After**

`OnCalcCrossDockToTransferOrderOnAfterTransferLineSetFilters(TransferLine, WhseCrossDockOpp, QtyOnPick, QtyPicked, ItemNo, VariantCode, LocationCode, CrossDockDate, LineNo);`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10820.
