### ISSUE TITLE
[Event Request] Codeunit 63 "Sales-Explode BOM" - OnBeforeExplodeBOMCompLines

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#23127]
Hello. Could you please add the following "OnBeforeExplodeBOMCompLines" event to Codeunit 63 "Sales-Explode BOM" into the OnRun trigger?

```al
IsHandled := false;
OnBeforeExplodeBOMCompLines(Rec, ToSalesLine, NoOfBOMComp, Selection, IsHandled)
if not IsHandled then
        ExplodeBOMCompLines(Rec);
```

```al
[IntegrationEvent(false, false)]
local procedure  OnBeforeExplodeBOMCompLines(var SalesLine: Record "Sales Line"; var ToSalesLine: Record "Sales Line";var NoOfBOMComp: Integer; var Selection: Integer; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10879.
