### ISSUE TITLE
[Event Request] Codeunit 5330 "CRM Integration Management" - OnBeforeFindCoupledToCRMField

### ISSUE THREAD

**Issue by robertbacu** [microsoft/ALAppExtensions#23144]
Hi MS team,

We need a new event in this piece of code, in Codeunit 5330 “CRM Integration Management” – FindCoupledToCRMField function, whereby an event should be raised so we can skip/override this call and exit with False if we don’t want to use the “Coupled to CRM” field.

This is because if the record syncs when users are still working on the record, users will lose their changes and they will be forced to refresh the page. This is valid on both standard and custom integrations.
Also this could be useful if at any point in time the field is added in a custom integration table and for the above reason you want to disable the field, then either a test should be added in the code to check if the field was Removed, or a custom subscriber would be used if the above event is added.
The event would be added in this piece of code:

```al
internal procedure FindCoupledToCRMField(var RecRef: RecordRef; var CoupledToCRMFldRef: FieldRef): Boolean
   var
       Field: Record "Field";
       Customer: Record Customer;
       TableNo: Integer;
       FieldNo: Integer;
       // >>>>>>>>>>>>>> 
       isHandled: boolean; 
       // <<<<<<<<<<<<<<
   begin
       TableNo := RecRef.Number();
       // >>>>>>>>>>>>>> 
       IsHandled := false; 
       OnBeforeFindCoupledToCRMField(TableNo,IsHandled); 
        If isHandled then
           exit(false);
       // <<<<<<<<<<<<<<
       if CachedCoupledToCRMFieldNo.ContainsKey(TableNo) then
           FieldNo := CachedCoupledToCRMFieldNo.Get(TableNo)
       else begin
           Field.SetRange(TableNo, TableNo);
           Field.SetRange(Type, Field.Type::Boolean);
           Field.SetRange(FieldName, Customer.FieldName("Coupled to CRM"));

           if Field.FindFirst() then
               FieldNo := Field."No."
           else
               FieldNo := 0;

           CachedCoupledToCRMFieldNo.Add(TableNo, FieldNo);
       end;

       if FieldNo = 0 then
           exit(false);

       CoupledToCRMFldRef := RecRef.Field(FieldNo);
       exit(true);
   end;
```

The Integration event would look like this:

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeFindCoupledToCRMField(TableNo: Integer; var IsHandled: Boolean)
begin
end;
```

Kind Regards,
Robert

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10868.
