### ISSUE TITLE
[Event request] Adding OnBeforeGetPurchLines integration event

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#23147]
Hi Microsoft AL Development Team,

Could you please add this integration event here to **codeunit 444 "Purchase-Post Prepayments"**?

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetPurchLines(PurchHeader: Record "Purchase Header"; DocumentType: Option Invoice,"Credit Memo",Statistic; var ToPurchLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;
```

![image](https://user-images.githubusercontent.com/69611495/235040583-2d8b675b-0b17-40f6-aa95-8311c70928a5.png)

The `GetSalesLines` function has already has a similar event in **codeunit 442 "Sales-Post Prepayments"**.

Thank you.

Kind regards,
Tuan Nguyen

Internal work item: [AB#501013](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501013)

**Comment by AlexanderYakunin** [comment]
Can you add the request title please?

**Comment by tuan-nguyen-fenwick** [comment]
> Can you add the request title please?

I have added the title

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16627.
