### ISSUE TITLE
EU VAT Registration No. Validation Service - Error using service creating new Vendor

### ISSUE THREAD

**Issue by NS-NN** [microsoft/ALAppExtensions#23154]
Hi,

Our customers are experienxing problems creating new Vendors using the EU VAT Registration No. Service.

**Please follow below steps to get the error:**
1. Activate EU VAT Registration No. Validation Service
2. Create new Vendor (EU)
3. Type Country/Region Code NL
4. Enter VAT Registraion No. (just use random valid Company VAT Registration No.)
5. Enter "OK"
6. Accept Name
7. Enter OK
8. Enter OK
9. Following Error Appear - in earlier versions the error do not appear, instead the vendor card opens.

**Error:**
The entered VAT Registration number is not in agreement with the format specified for Country/Region Code DK.
The following formats are acceptable: DK########, ########

What is the problem?

Thank you in advance.

**Comment by AlexanderYakunin** [comment]
This issue already fixed by application fix
