### ISSUE TITLE
[Event Request] Table 36 - "Sales Header" - OnBeforeValidatePaymentMethodCode

### ISSUE THREAD

**Issue by HendrikSittner** [microsoft/ALAppExtensions#23157]
Dear ALAppExtensions team,

through this issue we would like to request the addition of an event publisher `OnBeforeValidatePaymentMethodCode` in Table 36 "Sales Header" with the following signature:

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeValidatePaymentMethodCode(var SalesHeader: Record "Sales Header"; PaymentMethod: Record "Payment Method"; var IsHandled: Boolean)
begin
end;
```

which would be used in the OnValidate trigger of `"Payment Method Code"` as follows:

```al
trigger OnValidate()
var
	// >>>> New >>>>
	IsHandled: Boolean;
	// <<<< New <<<<
begin
	// >>>> New >>>>
	IsHandled := false;
	OnBeforeValidatePaymentMethodCode(Rec, PaymentMethod, IsHandled);
	if IsHandled then
		exit;
	// <<<< New <<<<
	UpdateDirectDebitPmtTermsCode();

	"Bal. Account Type" := PaymentMethod."Bal. Account Type";
	"Bal. Account No." := PaymentMethod."Bal. Account No.";
	if "Bal. Account No." <> '' then begin
		TestField("Applies-to Doc. No.", '');
		TestField("Applies-to ID", '');
		Clear("Payment Service Set ID");
	end;
end;
```

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10806.
