### ISSUE TITLE
Report 31004 (Adjust Exchange Rates CZL) - SaveValues property

### ISSUE THREAD

**Issue by hodnot** [microsoft/ALAppExtensions#23155]
Hi all, 
Unfortunately it is not possible to set the SaveValues property in an report extention. If we need it, we need to make a copy of the original report and it is not a good way.

Please add SaveValues= TRUE property on request page for thir report. 
# [extensibility-enhancement] label

Thank you in advance.
Petr

**Comment by DavidHolusa** [comment]
Hi @hodnot. What version of BC are you using? The SaveValues property was already added there. It should be available from version BC22.4.
