### ISSUE TITLE
[Question][Request for Modification] table 77 "Report Selections" - procedure "SendEmailInBackground" Scope "OnPrem"

### ISSUE THREAD

**Issue by PiGlic** [microsoft/ALAppExtensions#23153]
Hi,

I have a question and perhaps a modification request for the email module.
A little bit simplified there are two ways to send an email:
- Directly out of a document with a subpage that shows the mail
- Via the Job Queue Entry

In version 22 the needed function for sending via the Job Queue Entry is unfortunately tagged with OnPrem
![image](https://user-images.githubusercontent.com/36172313/235109141-d4129d7a-2a4b-482f-9923-f3ea86bf7d63.png)
(Scrennshot from Table 77 "Report Selections" -> The Function "SendEmailInBackground" is called from the OnRun Trigger in Codeunit 260 "Document-Mailing")

The actual functions that are responsible for sending the mail ("SendEmailToVendorDirectly" and "SendEmailToCustDirectly") are the same ones that are used for direct sending, so they are already running in the cloud.

Therefore my question
Is there a technical reason why sending via the Job Queue Entry is only available in OnPrem? 

If there is no reason for this, is it possible to modify the function and delete the "OnPrem" scope?

Greetings
Pierre

**Comment by JesperSchulz** [comment]
This issue has stranded.  Try posting your question to the following resources instead: 

[Business Central Community](https://community.dynamics.com/forums/thread/?groupid=e78817ab-a926-4d31-96cc-aef040a4eb04)
[mibuso forum](https://forum.mibuso.com/)
[Viva Engage](https://www.yammer.com/dynamicsnavdev)

This GitHub repository handles issues with extending published apps, and extensibility in general, for the latest release of Business Central.

If you'd like to suggest a pull request, please create an issue in the BCApp repo, where the email module resides :-)
