### ISSUE TITLE
Changes in the codeunit 5496 "Graph Mgt - Sales Order Buffer"

### ISSUE THREAD

**Issue by vkhutornyi** [microsoft/ALAppExtensions#23150]
After changes in the codeunit 5496 "Graph Mgt - Sales Order Buffer" in version 22.0
API endpoint salesOrders stop working properly when we tried to create Sales Order with Lines:

Request:
```
POST {{BaseURL}}v2.0/{{TenantID}}/{{EnvName}}/api/v2.0/companies({{companyId}})/salesOrders?$expand=salesOrderLines

{
    "customerNumber": "10000",
    "salesOrderLines": [
        {
            "sequence": 10000,
            "lineType": "Item",
            "lineObjectNumber": "1996-S",
            "quantity": 7,
            "unitPrice": 1197.3
        }
    ]
}
```
Response:
```
{
    "error": {
        "code": "Internal_ServerError",
        "message": "You cannot change the value of the SystemId field.\r\n\r\nTable: Sales Line\r\n\r\nIdentification fields and values:\r\nDocument Type='Order',Document No.='S-ORD101011',Line No.='10000'  CorrelationId:  6bb0e53c-3635-47d3-a50b-577f39a79a28."
    }
}
```
the changes causing the issue:

```
codeunit 5496 "Graph Mgt - Sales Order Buffer"

was
line 463         TransferSalesInvoiceLineAggregateToSalesLine(SalesInvoiceLineAggregate, SalesLine, TempFieldBuffer);
line 464         SalesLine.Insert(true);

became
line 464        SalesLine.Insert(true);
line 465        TransferSalesInvoiceLineAggregateToSalesLine(SalesInvoiceLineAggregate, SalesLine, TempFieldBuffer);
line 466        SalesLine.Modify(true);

```

**Comment by AndersLarsenMicrosoft** [comment]
Thanks this issue have been reported it is fixed and the fix will be released with 22.1 
            SalesLine."Line No." := SalesInvoiceLineAggregate."Line No.";
//delete this ->
        end else
// add this ->
        end else begin
            if SalesLine.Get(SalesLine."Document Type"::Order, SalesOrderEntityBuffer."No.", SalesInvoiceLineAggregate."Line No.") then
                Error(CannotInsertALineThatAlreadyExistsErr);
            SalesLine."Line No." := SalesInvoiceLineAggregate."Line No.";
        end;
// end of fix         
        SalesLine.Insert(true);
        TransferSalesInvoiceLineAggregateToSalesLine(SalesInvoiceLineAggregate, SalesLine, TempFieldBuffer);
        SalesLine.Modify(true);
