### ISSUE TITLE
[Event Request] Table 36 - "Sales Header" - OnBeforeOnInsert

### ISSUE THREAD

**Issue by HendrikSittner** [microsoft/ALAppExtensions#23160]
Dear ALAppExtensions team,

through this issue we would like to request the addition of an event publisher `OnBeforeOnInsert` in Table 36 "Sales Header" with the following signature:

```al
[IntegrationEvent(false, false)]
local procedure OnBeforeOnInsert(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
begin
end;
```

which would be used in the OnInsert trigger of `"Sales Header"` as follows:

```al
trigger OnInsert()
// >>>> New >>>>
var
	IsHandled: Boolean;
// <<<< New <<<<	
begin
	// >>>> New >>>>
	IsHandled := false;
	OnBeforeOnInsert(Rec, IsHandled);
	if IsHandled then
		exit;
	// <<<< New <<<<
	InitInsert;
	InsertMode := true;

	SetSellToCustomerFromFilter();

	if GetFilterContNo() <> '' then
		Validate("Sell-to Contact No.", GetFilterContNo());

	if "Salesperson Code" = '' then
		SetDefaultSalesperson();

	if "Sell-to Customer No." <> '' then
		StandardCodesMgtGlobal.CheckCreateSalesRecurringLines(Rec);

	// Remove view filters so that the cards does not show filtered view notification
	SetView('');

	OnAfterOnInsert(Rec);
end;
```

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10806.
