### ISSUE TITLE
ErrorIfAlreadySelectedSI - Add Conditional Logic

### ISSUE THREAD

**Issue by dkip05** [microsoft/ALAppExtensions#23168]
Add conditional logic to local procedure ErrorIfAlreadySelectedSI on Service Line table (5902)

`local procedure ErrorIfAlreadySelectedSI(ServItemLineNo: Integer)
    var
        Item: Record Item;
    begin
        if "Document Type" <> "Document Type"::Order then
            exit;
        if ServItemLineNo <> 0 then begin
            ServItemLine.Get("Document Type", "Document No.", ServItemLineNo);
            if (ServItemLine."Service Item No." = '') or
               (ServItemLine."Item No." = '') or
               (ServItemLine."Item No." <> "No.")
            then
                exit;
        end;

     ***** Proposed Change *****
     if (ServiceLine."Service Item No." <> '') then begin

             ServiceLine.Reset();
             ServiceLine.SetCurrentKey("Document Type", "Document No.", "Service Item Line No.", Type, "No.");
             ServiceLine.SetRange("Document Type", "Document Type");
             ServiceLine.SetRange("Document No.", "Document No.");
             ServiceLine.SetRange("Service Item Line No.", ServItemLineNo);
             ServiceLine.SetRange(Type, Type::Item);
             ServiceLine.SetFilter("Line No.", '<>%1', "Line No.");
             ServiceLine.SetRange("No.", "No.");
             if ServiceLine.FindFirst() then
                 Error(Text015, Item.TableCaption(), "No.");

             else
                  exit;
    end;`

The way the code is currently setup, we are unable to add multiple of the same Item to a Service Order, even if the Service Item No. is blank.

**Comment by dkip05** [comment]
An event to subscribe to with an IsHandled boolean logic step would also work here. Thanks!

**Comment by JakovljevicDusan** [comment]
Workaround provided by event publisher OnBeforeCheckErrorSelectedSI implemented for #24358.
