### ISSUE TITLE
[Protected Var Request] - page 6510 "Item Tracking Lines" IsDirectTransfer

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#23177]
Could you set var IsDirectTransfer: Boolean; under the protected var section? We need to know if we can make "New Carrier No. A200" visible or not. Quite the same as "New Lot No.";

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10762.
