### ISSUE TITLE
Take DST into account TypeHelper.GetTimezoneOffset

### ISSUE THREAD

**Issue by Wildrik** [microsoft/ALAppExtensions#23172]
Codeunit "Type Helper" contains a procedure GetTimeZoneOffset() which can be used to determine the offset to UTC of a specified timezone. Unfortunately this procedure does not take Daylight Saving Time (DST) into account. It merely determines the base offset of a time zone (using TimeZoneInfo.BaseUtcOffset). This is not sufficient for daily usage because the actual offset may be an hour off. This could be solved by exposing TimeZoneInfo.GetUtcOffset(DateTime) which returns the offset with DST for a specified date.

We need this procedure to convert times between time zones.

```
    procedure GetTimezoneOffset(var Duration: Duration; TimeZoneID: Text)
    var
        DotNet_DateTimeOffset: Codeunit DotNet_DateTimeOffset;
        TimeZoneInfo: DotNet TimeZoneInfo;
    begin
        Duration := DotNet_DateTimeOffset.GetOffset();
        if TimeZoneID <> '' then begin
            TimeZoneInfo := TimeZoneInfo.FindSystemTimeZoneById(TimeZoneID);
            Duration := TimeZoneInfo.BaseUtcOffset;
        end;
    end;
```

**Comment by pri-kise** [comment]
@Wildrik could you please take a look at the new time zone codeunit?
There were added some parts for timezone offset calculation.
https://github.com/microsoft/ALAppExtensions/blob/main/Modules/System/Date%20and%20Time/src/TimeZone.Codeunit.al

If you need more procedures there, then fell free to create a PR.

**Comment by Wildrik** [comment]
Thanks for bringing this new codeunit to my attention! That does solve our issue.

**Comment by pri-kise** [comment]
@Wildrik could you maybe tell me which of the procedures you are using instead?
I'm asking since it might be worth obsoleting the old procedure and referring to the new "correct" one.

**Comment by Wildrik** [comment]
We will be using:
- procedure GetTimezoneOffset(SourceDateTime: DateTime; TimeZoneId: Text): Duration
- procedure GetTimezoneOffset(SourceDateTime: DateTime): Duration

I think all procedures in this new codeunit are of use. The procedure in Type Helper mentioned in my starting post above could be obsoleted in my opinion. It is not very obvious that this procedure does not take DST into account.
