### ISSUE TITLE
Report 5752 "Picking List" | "Expiration Date"

### ISSUE THREAD

**Issue by LucaRoesnick** [microsoft/ALAppExtensions#23170]
The `Report 5752 "Picking List"` should include the `field(6503; "Expiration Date"; Date)` from the `table 5767 "Warehouse Activity Line"` with the **Serial No.** and **Lot No.**.

It would need to be implemented under the same conditions as the  **Serial No.** and **Lot No.** in the dataitems `WhseActLine` , `WhseActLine2` and the Layout since its an important field for the Item Tracking.

**Comment by AlexanderYakunin** [comment]
Hello! This is probably a good idea, bug we cannot process such requests here. It should be created on aka.ms/bcideas to get prioritized for implementation after partner voting.
