### ISSUE TITLE
[Application Bug] table 5741 "Transfer Line" - GetBin

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#23173]
While writing tests for transfer orders, I stumbled upon this bug, since my bins in both locations (Transfer-from Location Code / Transfer-From Bin Code and Transfer-to Location Code / Transfer-to Bin Code) where **named the same**.

The validation logic in the Transfer Line on the Transfer-**to** Bin Code fails, because the global Bin record is not refreshed (it still points to the Transfer-**From** Bin Code).

**Current code**

```
 local procedure GetBin(LocationCode: Code[10]; BinCode: Code[20])
    begin
        if BinCode = '' then
            Clear(Bin)
        else
            if Bin.Code <> BinCode then
                Bin.Get(LocationCode, BinCode);
    end;

```

**To be** 

(copied from table 83 "Item Journal Line")

```
 local procedure GetBin(LocationCode: Code[10]; BinCode: Code[20])
    begin
        if BinCode = '' then
            Clear(Bin)
        else
            if (Bin.Code <> BinCode) or (Bin."Location Code" <> LocationCode) then   // < Add check on changed Location Code
                Bin.Get(LocationCode, BinCode);
    end;
```

----

PS: Please review other similar occurences of GetBin procedures as well !

![image](https://user-images.githubusercontent.com/25268332/235606755-6c00c4b1-ec3c-4b38-8705-768e86c9aba0.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13151.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 13178.
