### ISSUE TITLE
GUIAllowed missing in Report 291 & 6661

### ISSUE THREAD

**Issue by frottke** [microsoft/ALAppExtensions#23178]
Report 291 and 6661 can not be scheduled as an job queue entry due to the fact that there is an Window.Open and Windows.Update without an GUIAllowed. See code example from Report 291

```
trigger OnAfterGetRecord()
var
    ATOLink: Record "Assemble-to-Order Link";
begin
    OnSalesHeaderOnBeforeOnAfterGetRecord("Sales Header");

    Window.Update(1, "No.");
```

I suggest that the following is added to the code
`if GUIAllowed then `

**Comment by frottke** [comment]
Is there an update regarding this bug?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13340.
