### ISSUE TITLE
[Application Bug] codeunit 7317 "Whse. Integration Management" - BinCodeFieldCaption

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#23185]
While extending the default bins on locations, I stumbled upon a bug, that can occur if you have added a field that has a fieldcaption of **more than 30 chars** that is integrated in the `CheckBinTypeCode` checks.

Comparing a text[30] field vs the table.FieldCaption might fail code from proper functioning in some cases.

```
case BinCodeFieldCaption of
                    WorkCenter.FieldCaption("Open Shop Floor Bin Code"),
                    WorkCenter.FieldCaption("To-Production Bin Code"):
                        AllowPutawayOrQCBinsOnly(BinType);
                    WorkCenter.FieldCaption("From-Production Bin Code"):
                        AllowPutawayPickOrQCBinsOnly(BinType);
                end;
```

Can you please fix by extending the `BinCodeFieldCaption` field length (> obsoleting / creating new function :(  ) ?

---

Important: Please review below cases as well, as they might be valid candidates for overflow errors too.

![image](https://user-images.githubusercontent.com/25268332/235686116-35ecf540-bbe2-458a-bddb-414d9e674d1d.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13701.
