### ISSUE TITLE
[Function Request] table 901 "Assembly Line" - GetHeader to return Assembly Header

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#23181]
Can you please add an overload on the table 901 "Assembly Line" - GetHeader that returns the assembly header global? 
Similar to purchase line, sales line, ....

New function

```
procedure GetHeader(): Record "Assembly Header"
    begin
        GetHeader();
        exit(AssemblyHeader);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10762.
