### ISSUE TITLE
codeunit 12 "Gen. Jnl.-Post Line" Include Sender -> Yes

### ISSUE THREAD

**Issue by xtiche** [microsoft/ALAppExtensions#23194]
Can you add sender to this event in `codeunit 12 "Gen. Jnl.-Post Line"`?
```
    [IntegrationEvent(false, false)] // -> [IntegrationEvent(true, false)]
    local procedure OnPostDtldEmplLedgEntriesOnAfterCreateGLEntriesForTotalAmounts(var TempGLEntryBuf: Record "G/L Entry" temporary; var GlobalGLEntry: Record "G/L Entry"; NextTransactionNo: Integer)
    begin
    end;
```
It's necessary for posting extra GenJnlLines after handling some buffer here
![image](https://user-images.githubusercontent.com/36332111/235912078-1212a3c0-471f-4f85-9ded-9b60c30df0b5.png)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10741.
