### ISSUE TITLE
[Extensibilit Request] - Tab. 1382 function ValidateItemField

### ISSUE THREAD

**Issue by RafaelKoch** [microsoft/ALAppExtensions#23192]
Tab. 1382 function ValidateItemField: Is executed when validating (almost) all fields in the item template. An assignment is performed using FieldRef for each field except for PK and description. This construct does not allow to create new fields in the item template without creating them under the same ID in the item at the same time, else an error is thrown.

![image](https://user-images.githubusercontent.com/25029667/235873173-e4060471-7efa-4fd1-ac41-fe9d3ef959fd.png)

Please refactor to accomodate ISV/PTE extensions. A good way to do it can be found in Codeunit "Item Templ. Mgt.", function "ApplyItemTemplate". Here, an exclusion list can be populated by subscriber and also a sesible check function is run prior to the actual assignments.

![image](https://user-images.githubusercontent.com/25029667/235873832-61ff95da-a127-4840-9220-f375deaa30da.png)

**Comment by JakovljevicDusan** [comment]
Hi @RafaelKoch ,

Seems like these events should help:
1. #26060 
2. #22923 

Thus, I am closing this issue, but feel free to open new issue with link to this one, if needed.
