### ISSUE TITLE
report 1306 "Standard Sales - Invoice" - Protection level of global variable - issue

### ISSUE THREAD

**Issue by tsgts22** [microsoft/ALAppExtensions#23202]
**Describe the bug**
I'm making a report extension, and when I try to access to a global variable of original report, there's no access.

**To Reproduce**
Create report extension of "Standard Sales - Invoice", if using variables TotalAmountInclVAT or TotalAmount to any new function it gets: 'TotalAmountInclVAT '/'TotalAmount ' is inaccessible due to its protection level.

**Expected behavior**
I would expect to access to a global variable of a report in a report extension.

**Screenshots**
Not applicable.

**Comment by pri-kise** [comment]
This should be solved with BC22.

https://github.com/microsoft/ALAppExtensions/issues/21473

**Comment by AlexanderYakunin** [comment]
Please consider difference between global and protected variables.
