### ISSUE TITLE
codeunit 12 "Gen. Jnl.-Post Line" make functions global

### ISSUE THREAD

**Issue by xtiche** [microsoft/ALAppExtensions#23205]
Please make the function `CalcCurrencyUnrealizedGainLoss` global.
It's necessary for implementing employee posting in currency.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
