### ISSUE TITLE
[Request for External] Page 6510 - "Item Tracking Lines"

### ISSUE THREAD

**Issue by GOB-Andrea** [microsoft/ALAppExtensions#2320]
Hi,
could you please switch the following functions in page "Item Tracking Lines" to local = no and external?

- CalculateSums 
<++Edit++> CalculateSums no longer necessary - I have already noticed that I can call the function by validating the "Line discount %" field. </++Edit++>
- TestTempSpecificationExists

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
