### ISSUE TITLE
[Extensibility Request] Page 360 "Document Sending Profile" - Use ElectronicFormat

### ISSUE THREAD

**Issue by jorispoppe** [microsoft/ALAppExtensions#23219]
We would like to extend the Document Sending Profile but we want to use the code for setting the LastFormat.

On Page 360 "Document Sending Profile", can we have the procedures public and the LastFormat variable protected.

**Variable to set protected:**
```
protected var
        LastFormat: Code[20];
```

**Procedures to make public:**
```
procedure LookupElectronicFormat(var ElectronicFormat: Code[20])
```
```
procedure GetFormat(): Code[20]
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
