### ISSUE TITLE
[Event Change Request] page 7011 "Purchase Price List Lines" - OnAfterUpdateColumnVisibility

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23218]
Could you please include the sender in the event `OnAfterUpdateColumnVisibility` as requested already (https://github.com/microsoft/ALAppExtensions/issues/21778)?
```al
//+Change
//-[IntegrationEvent(false, false)]
[IntegrationEvent(true, false)]
//-Change
local procedure OnAfterUpdateColumnVisibility(PriceListHeader: Record "Price List Header"; var SourceTypeVisible: Boolean; var JobSourceTypeVisible: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10741.
