### ISSUE TITLE
[Refactoring] Page 6510 - "Item Tracking Lines"

### ISSUE THREAD

**Issue by GOB-Andrea** [microsoft/ALAppExtensions#2321]
Hi, 
is it possible to make the source code in the OnInsert-Trigger accessible from the outside? E.g. by adding a new function "OnInsertPage".
The point is that we want to add our own line(s) to the page, but don't have access to the global variable "TempItemTrackLineInsert". We want to offer an action (via a PageExtension) that can create one or more "Item Tracking Line" according to a certain logic. 

The new function could look like this:
```
[External] OnInsertRecordPage()
IF "Entry No." <> 0 THEN
  EXIT;

"Entry No." := NextEntryNo;

TempItemTrackLineInsert.TRANSFERFIELDS(Rec);
TempItemTrackLineInsert.INSERT;
ItemTrackingDataCollection.UpdateTrackingDataSetWithChange(
  TempItemTrackLineInsert,CurrentSignFactor * SourceQuantityArray[1] < 0,CurrentSignFactor,0);
```
It is not necessary to trigger the function "CalculateSums" in the new function if "CalculateSums" is set to global/external (-> https://github.com/Microsoft/ALAppExtensions/issues/2320). Then it would be possible to create several lines in the page and then start the function "CalculateSums" once.

**Comment by AlexanderYakunin** [comment]
Closing this request as this is very old one (our sync from GitHub missed to create internal bug for this one) and no questions have been created for this area during last year. Sorry for possible inconvenience. If this is still active problem, please create new request with reference to this one.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
