### ISSUE TITLE
[Extensibility Request] Page 364 "Select Sending Options" - Use ElectronicFormat

### ISSUE THREAD

**Issue by jorispoppe** [microsoft/ALAppExtensions#23220]
We would like to extend the Document Sending Profile but we want to use the code for setting the LastFormat.

On Page 364 "Select Sending Options", can we have the procedures public and the LastFormat and CustomTxt variable protected.

**Variables to set protected:**
```
protected var
        CustomTxt: Label 'Custom';
        LastFormat: Code[20];
```

**Procedures to make public:**
```
procedure SetSendMethodToCustom()
```
```
procedure LookupFormat(): Code[20]
```
```
procedure GetFormat(): Code[20]
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10836.
