### ISSUE TITLE
Data Issue / Test Library: Accounting periods and Codeunit 131302 Library - Fiscal Year

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#2322]
There is a problem with how accounting periods in a CRONUS database (talking about the italian version here, but maybe the problem is generic) are shipped. This becomes apparent when one tries to use the function `Report 93 Create Fiscal Year` - either explicitly or by using `Codeunit 131302 Library - Fiscal Year`.

`Report 93 Create Fiscal Year` always creates an entire fiscal period + 1. For example: creating the year 2022 will create `01.01.2022 - 01.12.2022` (the period) and also `01.01.2023` (+1), marking the last period as `New Fiscal Year`.

When this report is invoked, we have the possibility (through `InitializeRequest`) to specify when we want the new fiscal period to start. But it does not always matter what we pass as `StartingDate` to that method, because it is ignored if there is already an accounting period present. In which case `StartingDate` is forced to be the last accounting period. Which _would be_ fine, because, as explained above, the report always creates the period + 1, and as such, the last record in that table _should_ always be the start of the next period.

This however is not the case in CRONUS data. The table ends with `01.12.20xx` and therefore creating a new fiscal year through `Report 93 Create Fiscal Year` fails because it starts at the wrong starting date.

**Comment by AlexanderYakunin** [comment]
Closing this request as this is very old one (our sync from GitHub missed to create internal bug for this one) and no questions have been created for this area during last year. Sorry for possible inconvenience. If this is still active problem, please create new request with reference to this one.
