### ISSUE TITLE
new event needed codeunit 6620

### ISSUE THREAD

**Issue by SahilGuptaBS** [microsoft/ALAppExtensions#2323]
Hi

please add more events on function

![image](https://user-images.githubusercontent.com/38460823/57215522-c21a5400-700a-11e9-869e-0afa1f2e4757.png)

here is the postion
![image](https://user-images.githubusercontent.com/38460823/57215548-d52d2400-700a-11e9-9aad-ccade6fabea4.png)

on the same way, for sales we already have
![image](https://user-images.githubusercontent.com/38460823/57215557-e2e2a980-700a-11e9-871c-270f1351d283.png)

i need new event with the same position on purchase too.

**Comment by AlexanderYakunin** [comment]
We have different structure of events for Purchase compared to Sales, due to Split. We already have 2 events here:

        END;
        OnAfterCopyPurchLineFromPurchCrMemoLineBuffer(
          ToPurchLine,FromPurchCrMemoLine,IncludeHeader,RecalculateLines,TempDocPurchaseLine,ToPurchHeader,FromPurchLineBuf);
      END;
      OnAfterCopyPurchCrMemoLine(FromPurchCrMemoLine,ToPurchLine);
    UNTIL NEXT = 0;
  END;
END;
