### ISSUE TITLE
[Event Request] Table 308 "No. Series"."Default Nos.".OnValidate

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#23233]
Please add new event:
```
field(3; "Default Nos."; Boolean)
{
    Caption = 'Default Nos.';

    trigger OnValidate()
    //---------------------------------------OnBeforeValidateDefaultNos:BEGIN
    var
        IsHandled: Boolean;
    //---------------------------------------OnBeforeValidateDefaultNos:END
    begin
    //---------------------------------------OnBeforeValidateDefaultNos:BEGIN
        OnBeforeValidateDefaultNos(Rec, IsHandled);
        if IsHandled then
            exit;
    //---------------------------------------OnBeforeValidateDefaultNos:END
        if ("Default Nos." = false) and (xRec."Default Nos." <> "Default Nos.") and ("Manual Nos." = false) then
            Validate("Manual Nos.", true);
    end;
}
field(4; "Manual Nos."; Boolean)
{
    Caption = 'Manual Nos.';

    trigger OnValidate()
    //---------------------------------------OnBeforeValidateManualNos:BEGIN
    var
        IsHandled: Boolean;
    //---------------------------------------OnBeforeValidateManualNos:END
    begin
    //---------------------------------------OnBeforeValidateManualNos:BEGIN
        OnBeforeValidateManualNos(Rec, IsHandled);
        if IsHandled then
            exit;
    //---------------------------------------OnBeforeValidateManualNos:END
        if ("Manual Nos." = false) and (xRec."Manual Nos." <> "Manual Nos.") and ("Default Nos." = false) then
            Validate("Default Nos.", true);
    end;
}


//---------------------------------------OnBeforeValidateDefaultNos:BEGIN
[IntegrationEvent(true, false)]
OnBeforeValidateDefaultNos(var DefaultNos: Record "No. Series"; var IsHandled: Boolean)
begin
end;
//---------------------------------------OnBeforeValidateDefaultNos:END


//---------------------------------------OnBeforeValidateManualNos:BEGIN
[IntegrationEvent(true, false)]
OnBeforeValidateManualNos(var DefaultNos: Record "No. Series"; var IsHandled: Boolean)
begin
end;
//---------------------------------------OnBeforeValidateManualNos:END
```

**Comment by grobyns** [comment]
@fridrichovsky Hi, 
could you let me know if, where and how you are using these events? With the next major release we have refactored No. Series and our data shows these events are not used. 
br/Gert

**Comment by fridrichovsky** [comment]
@grobyns we are using it OnPrem server. It was used for skip validation code because we have own code.

**Comment by grobyns** [comment]
Thx for the update :-)

**Comment by grobyns** [comment]
Hi again,
we have decided to obsolete and remove the two events. In order to bypass the field validation from the page you can create a page extension as shown below. That should achieve the same result as subscribing to those events. Please note this is just sample code, you will need to adjust it to your needs and test that everything works as expected. 

pageextension 50100 Bar extends "No. Series"
{
    layout
    {
        modify("Default Nos.")
        {
            Enabled = false;
            Visible = false;
        }
        modify("Manual Nos.")
        {
            Enabled = false;
            Visible = false;
        }
        addafter("Manual Nos.")
        {
            field(MyDefaultNos; DefaultNos)
            {
                Caption = 'My Default Nos.';
                ApplicationArea = All;

                trigger OnValidate()
                begin
                    Rec."Default Nos." := DefaultNos;
                end;
            }
            field(MyManualNos; ManualNos)
            {
                Caption = 'My Manual Nos.';
                ApplicationArea = All;

                trigger OnValidate()
                begin
                    Rec."Manual Nos." := ManualNos;
                end;
            }
        }
    }
    var
        DefaultNos, ManualNos : Boolean;

    trigger OnAfterGetRecord()
    begin
        DefaultNos := Rec."Default Nos.";
        ManualNos := Rec."Manual Nos.";
    end;
}
