### ISSUE TITLE
[Function Request] table 901 "Assembly Line" - SetAssemblyHeader

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#23236]
In relation to #23181, we would like to be able to set value of the global variable `AssemblyHeader`, similar to these other tables.

![image](https://user-images.githubusercontent.com/25268332/236472868-38da7e83-40b9-4c25-aa7c-4648bdc75ba2.png)

Can you please provide a function SetAssemblyHeader (or SetHeader) on table 901 "Assembly Line"?

```
procedure SetAssemblyHeader(NewAssemblyHeader: Record "Assembly Header")
    begin
        AssemblyHeader := NewAssemblyHeader;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10836.
