### ISSUE TITLE
[Access Request] page 1040 "Copy Job"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23244]
Could you please change the scope of the following variables to proctedted?
```al
protected var
    SourceJob: Record Job;
    SourceJobNo: Code[20];
    TargetJobNo: Code[20];
    TargetJobDescription: Text[100];
    TargetSellToCustomerNo: Code[20];
    TargetBillToCustomerNo: Code[20];
    CopyJobPrices: Boolean;
    CopyQuantity: Boolean;
    CopyDimensions: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10836.
