### ISSUE TITLE
[Event Request] Page 7018 Purchase Price List - GetDefaultSourceType needs a Publisher for own extensions

### ISSUE THREAD

**Issue by JonasPatto** [microsoft/ALAppExtensions#23245]
Hello Microsoft Team,

we are currently developing our own extension based on the new Pricing Feature.

We extended the Enums of this module for our own usage. if we try to open the page 7018 "Purchase Price List" with our new added context we get an "error". 

![image](https://user-images.githubusercontent.com/48987445/236797513-2703b3df-7add-44b2-8d3d-6e233a68778b.png)

The Code in the Background changes the context back to "Source Group" = Vendor even if we enter the Page 7018 from our new List-Page with our own Source Group.

![image](https://user-images.githubusercontent.com/48987445/236797782-6a3b68c8-4151-4463-906b-759fe61bf8fa.png)

Reason for this behaviour is simple:

When the code gets the Default Source Type with the procedure "GetDefaultSourceType" in page 7018 it does not know what to do with the new Value in the Enum-paramter SourceGroup. The exit Value for this procedure will be the default value of the Enum "Price Source Type" which equals "(All)". This small error leads to another error in the next procedure call. There it resets the Source Type and also access the wrong interface implementation.

![image](https://user-images.githubusercontent.com/48987445/236799016-a0e813fc-198a-4ebe-ab61-118948db8957.png)

To solve this wrong behaviour we simply need a Publisher at the end of the procedure:

    local procedure GetDefaultSourceType(SourceGroup: Enum "Price Source Group") DefaultSourceType: Enum "Price Source Type";
    begin
        case SourceGroup of
            SourceGroup::Vendor:
                DefaultSourceType := Rec."Source Type"::"All Vendors";
            SourceGroup::Job:
                DefaultSourceType := Rec."Source Type"::"All Jobs";
        end else
                OnGetDefaultSourceOnCaseElse(SourceGroup, DefaultSourceType);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnGetDefaultSourceOnCaseElse(SourceGroup: Enum "Price Source Group"; var DefaultSourceType: Enum "Price Source Type")
    begin
    end;

Another Solution would be to create a new procedure in the interface so that the Default Source Type could be received from own implementations as well. 

Kind Regards

Jonas

**Comment by pri-kise** [comment]
Isn't this issue a duplicate of my issue, that I created some days ago?
https://github.com/microsoft/ALAppExtensions/issues/23216

**Comment by JonasPatto** [comment]
> Isn't this issue a duplicate of my issue, that I created some days ago? #23216

yes it is. Only Placement is different. I'll close this issue and let Microsoft decide how to implement it.
