### ISSUE TITLE
[Access Request] page 7016 "Sales Price List"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23247]
Could you please change the access scope to protected of the following variables?
```al
    protected var
        [InDataSet]
        IsJobGroup: Boolean;
        [InDataSet]
        ParentSourceNoEnabled: Boolean;
        [InDataSet]
        ParentSourceNoVisible: Boolean;
        [InDataSet]
        SourceNoEnabled: Boolean;
        [InDataSet]
        ViewGroupIsVisible: Boolean;
        [InDataSet]
        UseCustomLookup: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10836.
