### ISSUE TITLE
Change in SalesLine.Table.al breaks salesCreditMemo API

### ISSUE THREAD

**Issue by tinfister** [microsoft/ALAppExtensions#23240]
In table 37 "Sales Line"  in function UpdateAmounts() there is change introduced in BC22.
Before it was

` "Recalculate Invoice Disc." := true;`
 
 Now it is
 
` "Recalculate Invoice Disc." := "Allow Invoice Disc.";`

 
![image](https://user-images.githubusercontent.com/29481795/236521849-bab30003-8dc5-4389-b847-d29584be0323.png)

When you insert Credit memo with line which is Type = GL Account and populate Quantity and Unit Price in the line, total is calculated on the document, but not propagated to  "Sales Cr. Memo Entity Buffer" and API page salesCreditMemo will return 0 for total fields for that document.

![image](https://user-images.githubusercontent.com/29481795/236522874-3eb33f6a-c091-44c1-ad76-65d25005ea3a.png)

That is happening because in table 37 "Sales Line"  function **CopyFromGLAccount** we have the line

` "Allow Invoice Disc." := false;`

 then in UpdateAmounts() we have mentioned line

`  "Recalculate Invoice Disc." := "Allow Invoice Disc.";`
 
and later in the process in codeunit 5508 "Graph Mgt - Sal. Cr. Memo Buf." in function **ModifyTotalsSalesLine** there is this line of code

```
if not SalesLine."Recalculate Invoice Disc." then
            exit;
```
![image](https://user-images.githubusercontent.com/29481795/236522507-9c966ce0-ff8f-4707-8ceb-f01f5fad04c9.png)

**How to reproduce**
1) Create sales credit Memo document
2) Populate header fields
3) Insert Line with Type = GL Account, some quantity and some amount
4) Make sure you are not updating and field in the header after you edit the line, this is important
5) Fetch that credit memo via API via salesCreditMemos page and values for totalAmountExcludingTax, totalTaxAmount and totalAmountIncludingTax should be 0

**How to reproduce v2**
1) Send POST request to salesCreditMemos API, one request with header and line
2) Values for totalAmountExcludingTax, totalTaxAmount and totalAmountIncludingTax should be 0

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11302.
