### ISSUE TITLE
[Question] How to use NotificationScope::GlobalScope?

### ISSUE THREAD

**Issue by christianbraeunlich** [microsoft/ALAppExtensions#23251]
Hello there,
since when is it possible to use the `NotificationScope::GlobalScope` (see following line of code) ?
https://github.com/microsoft/ALAppExtensions/blob/1429e6068f9ce2fea81c474d6cdd42d08cfb4101/Apps/W1/CompanyHub/app/src/ClientSummary/COHUBUrlTaskManager.Codeunit.al#L85

Shouldn't this be changed to `NotificationScope::LocalScope` according to: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/notificationscope/notificationscope-option

Maybe there is an alternative to use the notification bell?
![image](https://user-images.githubusercontent.com/25108568/236808444-34239e14-57b5-46eb-a7d2-4b03278ea6e8.png)

Thanks in advance
/Christian

**Comment by JesperSchulz** [comment]
Yeah, that's a minor bug. GlobalScope doesn't exist yet. We hope at some point to provide such capabilities; we'll let you know when support has been added ;-)
For now, I'll change the scope to local :-)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12375.
