### ISSUE TITLE
Event-Request in codeunit 7307 "Whse.-Activity-Register"

### ISSUE THREAD

**Issue by sanithshetty** [microsoft/ALAppExtensions#23253]
I need an event to skip this procedure CheckSourceDocumentForAvailableQty when registering the warehouse activity line.
It is very critical for our custom app and it is stopping the whole functionality of our app.

{
local procedure CheckSourceDocumentForAvailableQty(var GroupedWhseActivLine: Record "Warehouse Activity Line")
    var
        SourceProdOrderComp: Record "Prod. Order Component";
        SourceJobPlanningLine: Record "Job Planning Line";
        UOMMgt: Codeunit "Unit of Measure Management";
        RemainingQtyBase: Decimal;
        RemainingQtyUoM: Code[10];
    begin
        //---------------------------------------OnBeforeCheckSourceDocumentForAvailableQty:BEGIN
        OnBeforeCheckSourceDocumentForAvailableQty(GroupedWhseActivLine, IsHandled);
        if IsHandled then
             exit;
        //---------------------------------------OnBeforeCheckSourceDocumentForAvailableQty:END
        GroupedWhseActivLine.SetRange("Breakbulk No.", 0);
        if GroupedWhseActivLine.FindSet() then
            repeat
                case GroupedWhseActivLine."Source Document" of
                    "Warehouse Activity Source Document"::"Prod. Consumption":
                        begin
                            SourceProdOrderComp.SetLoadFields("Remaining Qty. (Base)", "Unit of Measure Code");
                            SourceProdOrderComp.Get(GroupedWhseActivLine."Source Subtype", GroupedWhseActivLine."Source No.", GroupedWhseActivLine."Source Line No.", GroupedWhseActivLine."Source Subline No.");
                            RemainingQtyBase := SourceProdOrderComp."Remaining Qty. (Base)";
                            RemainingQtyUoM := SourceProdOrderComp."Unit of Measure Code";
                        end;
                    "Warehouse Activity Source Document"::"Job Usage":
                        begin
                            SourceJobPlanningLine.SetCurrentKey("Job Contract Entry No.");
                            SourceJobPlanningLine.SetRange("Job Contract Entry No.", GroupedWhseActivLine."Source Line No.");
                            SourceJobPlanningLine.SetLoadFields("Remaining Qty. (Base)", "Unit of Measure Code");
                            SourceJobPlanningLine.FindFirst();
                            RemainingQtyBase := SourceJobPlanningLine."Remaining Qty. (Base)";
                            RemainingQtyUoM := SourceJobPlanningLine."Unit of Measure Code";
                        end;
                end;
                if UOMMgt.CalcBaseQty(GroupedWhseActivLine."Qty. to Handle", GroupedWhseActivLine."Qty. per Unit of Measure") > RemainingQtyBase then
                    Error(ItemAlreadyConsumedErr, RemainingQtyBase, RemainingQtyUoM, GroupedWhseActivLine.FieldCaption("Line No."), GroupedWhseActivLine."Line No.", GroupedWhseActivLine.FieldCaption("Item No."), GroupedWhseActivLine."Item No.", GroupedWhseActivLine."Source Document", GroupedWhseActivLine."Source No.", GroupedWhseActivLine.FieldCaption("Source Line No."), GroupedWhseActivLine."Source Line No.");
            until GroupedWhseActivLine.Next() = 0;
        GroupedWhseActivLine.SetRange("Breakbulk No.");
    end;
}
//---------------------------------------OnBeforeCheckSourceDocumentForAvailableQty:BEGIN
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckSourceDocumentForAvailableQty(var GroupedWhseActivLine: Record "Warehouse Activity Line"; var IsHandled: Boolean)
begin
end;
//---------------------------------------OnBeforeCheckSourceDocumentForAvailableQty:END

**Comment by sanithshetty** [comment]
@AlexanderYakunin can I get any update on this issue or when can I expect the update ?

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10820.
