### ISSUE TITLE
[Request for Modification] table 1173 "Document Attachment" - Replace fixed checks on Document Reference ID by a function with publishers

### ISSUE THREAD

**Issue by dsaveyn** [microsoft/ALAppExtensions#23273]
Currently, the Document Attachment table is not as flexible as we would want it to be.

In several places in the base app, there are fixed checks on the Document Reference ID field similar to this one:

```
        if not "Document Reference ID".HasValue() then
            Error(NoDocumentAttachedErr);
```

Please replace the usages/checks by functions with a publisher so we can implement custom behavior.

For example the OnInsert trigger of the Document Attachment table, currently looks as following:

```
    trigger OnInsert()
    begin
        ...

        if not "Document Reference ID".HasValue() then
            Error(NoDocumentAttachedErr);

        ...
    end;
```

It could be changed as following:

```
    trigger OnInsert()
    begin
        ...

        CheckAttachmentLinked();

        ...
    end;

    internal procedure CheckAttachmentLinked()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckAttachmentLinked(Rec, IsHandled);
        if IsHandled then
            exit;
    
        if not "Document Reference ID".HasValue() then
                Error(NoDocumentAttachedErr);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckAttachmentLinked(var DocumentAttachment: Record "Document Attachment"; var IsHandled: Boolean)
    begin
    end;
```

Please also review similar usages of the "Document Reference ID" and adjust them so we can use the Document Attachment table to implement external storage.

**Comment by fvet** [comment]
@JesperSchulz   Any chance on getting this one for BC 23.0 or 23.1?  When prepping the move away from storing document attachment inside the database (preferably by using the new system modules), we need the Base App to be better prepped to support other file storage scenarios.

**Comment by JesperSchulz** [comment]
Sorry, didn't see this request until now :-( I'm not monitoring ALAppExtensions much any more.

@AlexanderYakunin / @MarkoTrn, what's the status on this one?

**Comment by JesperSchulz** [comment]
Internal work item was closed with the following remark:
"This is already covered. Document Reference ID value is checked on 5 places in the Document Attachment table. On each place we already limited check with OnBefore publishers."

Given the internal work item is closed, I'm closing this issue too. If the solution isn't right, please create a new issue to have us take a 2nd look at it :-)
