### ISSUE TITLE
How to extend Option Field in CRM Invoice?

### ISSUE THREAD

**Issue by samsiddiquiz** [microsoft/ALAppExtensions#23284]
How to extend Option Field in CRM Invoice? We added new options in CRM Invoice Table Field StatusCode but that options are missing in Business Central?

![image](https://github.com/microsoft/AL/assets/32498803/4fa8d745-42b9-4c84-8149-40811ce7fb5f)

**Comment by pri-kise** [comment]
I think this isn't possible right now.
Check out the following ideas:
- https://experience.dynamics.com/ideas/idea/?ideaid=67e0463d-f5a2-ed11-9ac4-0003ff457d0a
- https://experience.dynamics.com/ideas/idea/?ideaid=32b55f22-0dcc-eb11-ba5e-0003ff458e62

Maybe you can create a new field on the same table via a table extension that incude the other values?

**Comment by onbuyuka** [comment]
It is not possible to extend option type fields. You can
- Create a new option field to include new values and update the integration field mapping

Updating integration field mappings:  (https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/administration-custom-cds-integration#add-new-integration-field-mapping-for-industry), make sure you map enum fields to enum fields and option fields to option fields (between CRM type tables and normal tables)
