### ISSUE TITLE
[Event Request] codeunit 5895 (Inventory Adjustment)

### ISSUE THREAD

**Issue by Alexbitl** [microsoft/ALAppExtensions#2328]
Dear ALAppExtensions team,

There are situations when we need to limit the execution time of the report 795 (Adjust Cost - Item Entries). To do this, please add an integration event to the **MakeSingleLevelAdjmt** function in codeunit 5895 (Inventory Adjustment) with the ability to pass additional parameter (for example, run duration or stop time).

In C/AL it looks like this:
![image](https://user-images.githubusercontent.com/48685414/57222842-bdef3600-700c-11e9-816f-253c9d9c6bdb.png)

**Comment by AlexanderYakunin** [comment]
Can you please be more specific and provide event definition, list of parameters and location in the code?

**Comment by Alexbitl** [comment]
I see such implementation:

1.	In the codeunit 5895 add global variable StopTime (datetime)
2.	At the end of local procedure InitializeAdjmt (cu5895) add integration event **OnAfterInitializeAdjmt(var StopTime :datetime)**  and we will be able to initialize new variable
3.	At the local procedure MakeSingleLevelAdjmt (cu5895) add integration event
**OnAfterItemAdjmt(var Item : Record «Item»)**

![image](https://user-images.githubusercontent.com/48685414/58316647-b1484b80-7e1c-11e9-9eec-deecadcf6dd0.png)

In this way we can interrupt processing and not wait for processing all items.

**Comment by AJasp** [comment]
Hi,
i would suggest an additional parameter for the suggested event "OnAfterItemAdjmt" - please consider the Boolean "IsOnlineAdjmt".

Thanks

**Comment by Alexbitl** [comment]
Hi,
I think an additional parameter is always useful. Thank you for your response.
