### ISSUE TITLE
[Event Parameter] codeunit "FA Jnl.-Check Line" - OnBeforeCheckFAPostingDate

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#23290]
Please add new parameters to the event `OnBeforeCheckFAPostingDate`.
```al
local procedure CheckFAPostingDate()
    ...
    OnBeforeCheckFAPostingDate(GenJnlLine, FAJnlLine, DeprBook, IsHandled, FADeprBook, GenJnlPosting);
    ...
end;
```
```al
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckFAPostingDate(GenJournalLine: Record "Gen. Journal Line"; FAJournalLine: Record "FA Journal Line"; DepreciationBook: Record "Depreciation Book"; var IsHandled: Boolean; FADepreciationBook: Record "FA Depreciation Book"; GenJnlPosting: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10816.
