### ISSUE TITLE
[Application Change / Event Request] COD 230 GenJnlManagement - TemplateSelection PageID

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#2330]
In case a journal template is to be selected (on a BE database), we don't always have the 'PageID' parameter as a context. When PageID is empty, we don't want to apply a filter on journal templates with 'Page ID' = 0.

Can you please either:
- add the "PageID <> 0" code line
- extend the 'OnTemplateSelectionSetFilter' event publisher with the PageID parameter (to be consistent with the PageTemplate parameter passing)?

![image](https://user-images.githubusercontent.com/25268332/57226201-bc267200-700e-11e9-81a6-61e06c9664df.png)

PS: In the meantime, I might use the GETFILTER approach on the 'Page ID' field as a workaround.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
