### ISSUE TITLE
[Extensibility-bug] CodeUnit 5610 "Calculate Depreciation" -> missing overloading

### ISSUE THREAD

**Issue by ArvinNube** [microsoft/ALAppExtensions#23302]
HI,
I think between the WW baseapp and the Italian one, an overloading is missing.
In CodeUnit 5610 "Calculate Depreciation":

WW -> procedure Calculate(var DeprAmount: Decimal; var Custom1Amount: Decimal; var NumberOfDays: Integer; var Custom1NumberOfDays: Integer; FANo: Code[20]; DeprBookCode: Code[10]; UntilDate: Date; EntryAmounts: array[4] of Decimal; DateFromProjection: Date; DaysInPeriod: Integer)

ITA -> procedure Calculate(var DeprAmount: Decimal; var Custom1Amount: Decimal; var NumberOfDays: Integer; var Custom1NumberOfDays: Integer; FANo: Code[20]; DeprBookCode: Code[10]; UntilDate: Date; EntryAmounts: array[4] of Decimal; DateFromProjection: Date; DaysInPeriod: Integer; UseCustom1: Boolean; UseCustom2: Boolean; var Custom2Amount: Decimal; ForcedPercent1: Decimal; ForcedPercent2: Decimal)

As you can see, the Italian version has more arguments and the ww version is not present.
Therefore, if I install a ww app that uses the "calculate" procedure in an Italian client, the app cannot be installed.
I think the correct solution would therefore be to add an overloading procedure of "calculate" in the Italian localization.

the same exact problem is in codeunit 5611 "Calculate Normal Depreciation".

Thanks

**Comment by pri-kise** [comment]
@ArvinNube you help microsoft to easier process your request if you add the object id / name and the procedure name to the title of your issue.

**Comment by ArvinNube** [comment]
news?

**Comment by ArvinNube** [comment]
hello, were you able to investigate the problem? thank you

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 18446.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18472.
