### ISSUE TITLE
Enhancement Request: Ability to Mark and Delete Records in Automated Testing via UI

### ISSUE THREAD

**Issue by sharan-lal** [microsoft/ALAppExtensions#23307]
Currently, we are unable to perform the following actions via the user interface when it comes to automated testing:

- Marking records
- Deleting records

Could this limitation please be addressed

Thank you,
Sharan

**Comment by AlexanderYakunin** [comment]
Sorry, we cannot process this request, as it is missing details about your scenario and what exactly you would like to improve? 

Please also consider that this is forum for extensibility requests, you can add your ideas to aka.ms/bcideas forum to be voted and processed.
