### ISSUE TITLE
TestTableRelation is obsolete

### ISSUE THREAD

**Issue by LFlamme** [microsoft/ALAppExtensions#2331]
Hi,

in AL we get the warning
"Property TestTableRelation is obsolete" .
So how can we replace it? 
As far as i see, Microsoft uses this as well.

Thanks in advance

**Comment by fvet** [comment]
Also curious to see how this will be changed on postcode / city related fields.

**Comment by ikoletic** [comment]
This issue is a question. Please submit your questions on [business central community ](https://community.dynamics.com/business/f/758) or on [BC development yammer groups](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035).

**Comment by fvet** [comment]
https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=199280292397056
