### ISSUE TITLE
[Change Request] codeunit 90 "Purch.-Post" - procedure CheckBlockedPostingGroups

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#23326]
Hello, can you please change the local procedure CheckBlockedPostingGroups as global?

```
    procedure CheckBlockedPostingGroups(PurchaseLine: Record "Purchase Line")
    var
        GeneralPostingSetup: Record "General Posting Setup";
        VATPostingSetup: Record "VAT Posting Setup";
        ForwardLinkMgt: Codeunit "Forward Link Mgt.";
    begin
        if not PurchaseLine.HasTypeToFillMandatoryFields() then
            exit;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
