### ISSUE TITLE
[Event Request] Codeunit 7307 "Whse.-Activity-Register" - OnBeforeCheckSourceDocumentForAvailableQty (BaseApp_22.0)

### ISSUE THREAD

**Issue by markborges** [microsoft/ALAppExtensions#23336]
A new function **CheckSourceDocumentForAvailableQty** (codeunit 7307 "Whse.-Activity-Register") was created in version 22.0 with no Event Subscribers at all to bypass, or manipulate this check.

Please create the following event subscriber:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckSourceDocumentForAvailableQty(var GroupedWhseActivLine: Record "Warehouse Activity Line"; var IsHandled: Boolean)
begin
end
```

And then do the following change on the function CheckSourceDocumentForAvailableQty:

```
     local procedure CheckSourceDocumentForAvailableQty(var GroupedWhseActivLine: Record "Warehouse Activity Line")
     var
         SourceProdOrderComp: Record "Prod. Order Component";
         SourceJobPlanningLine: Record "Job Planning Line";
         UOMMgt: Codeunit "Unit of Measure Management";
         RemainingQtyBase: Decimal;
         RemainingQtyUoM: Code[10];
+        IsHandled: Boolean;
     begin
+        IsHandled := false;
+        OnBeforeCheckSourceDocumentForAvailableQty(GroupedWhseActivLine, IsHandled);
+        if IsHandled then
+            exit;

         GroupedWhseActivLine.SetRange("Breakbulk No.", 0);
         if GroupedWhseActivLine.FindSet() then
```

Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10820.
