### ISSUE TITLE
[Event Request] Codeunit 5201 "Employee/Salesperson Update"

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#23346]
I can not find changes from my request #21322 in Microsoft_Base Application_22.0.54157.55195. Please do my requested changes

**Comment by AleksandricMarko** [comment]
Hello @fridrichovsky 
As far as I can see, 
OnSalesPersonUpdateOnBeforeModify is added.

OnBeforeDoSalesPersonUpdate(OldEmployee,Employee,Result,IsHandled); is missing as a part of procedure local procedure ShouldRunUpdate (procedure procedure DoSalesPersonUpdate does not exist anymore)

Also, a not, we are adding events just in BC 22 and master branches.
Please confirm that you want me to add second event.

**Comment by AleksandricMarko** [comment]
Hello @fridrichovsky 
Could you please review previous comment?

**Comment by fridrichovsky** [comment]
Hello @AleksandricMarko,
I do not know how I missed it. It looks OK.
Thank you.
