### ISSUE TITLE
[Event Request] Codeunit 212 "Res. Jnl.-Post Line".Code

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#23348]
Please add missinge event "OnCodeOnAfterRunCheck" from our event request #21310. We can use event from function RunCheck, because it will be called with each call. Our code have to be run only for code function.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11004.
