### ISSUE TITLE
[Event Request] Table 39 "Purchase Line"."No.".Validate

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#23344]
Please add events by our request #21367 or confirm that there are no unsaved values.

**Comment by fridrichovsky** [comment]
Hello @AleksandricMarko,
we asked for two events with PurchHeader. If you add Purchase Header parameter to OnAfterValidateNo  it will be OK. But we need same parameter to event JobTaskIsSet or new event  OnValidateNoOnBeforeJobTaskIsSet(PurchHeader, Rec, xRec, TempPurchLine.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11211.
