### ISSUE TITLE
[Event Request] Codeunit 1001 "Job Post-Line".PostGenJnlLine

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#23347]
Please do requested events in #21316. Problem is that event "OnBeforePostGenJnlLine" can not be used. Problem is that event OnPostGenJnlLineOnAfterTransferToJnlLine(JobJnlLine, GenJnlLine, JobJnlPostLine); is not called when we use "OnBeforePostGenJnlLine". We can duplicate code this way 
```
    JobTransferLine.FromGenJnlLineToJnlLine(GenJnlLine, JobJnlLine);
    //OnPostGenJnlLineOnAfterTransferToJnlLine(JobJnlLine, GenJnlLine, JobJnlPostLine);

    JobJnlPostLine.SetGLEntryNo(GLEntry."Entry No.");
    JobJnlPostLine.RunWithCheck(JobJnlLine);
    JobJnlPostLine.SetGLEntryNo(0);
```
Problem is that we can not "call" event "OnPostGenJnlLineOnAfterTransferToJnlLine" because it is local procedure. So we have to have option skip required code part. 

BIG Question. If we have own code in subscriber, where we have to duplicate code part because we used OnBeforeEvent with handled=true. But we need (have to) raise standard events how we can do it? All events are as local procedures so it can not be call from our extension. If we use OnBeforeEvent we destroy working code for another extensions that use standard events from skipped code.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10804.
