### ISSUE TITLE
[Event Request] codeunit 1000 "Job Calculate WIP" procedure CheckJobGLAcc()

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#23349]
Please can you add the following event/code at the start of the procedure...

```
OnBeforeCheckJobGLAcc(AccNo, IsHandled)
if IsHandled then
    exit;

```
with a local variable...

```
var
    IsHandled: Boolean

```
The event publisher would be...

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckJobGLAcc(AccNo: Code[20]; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10855.
