### ISSUE TITLE
[Event Request] Table 37 "Sales Line"."No."

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#23345]
Please add event as we required in #21355. I can not find event OnValidateNoOnAfterCreateDimFromDefaultDim. I can not use event from subfunction CreateDimFromDefaultDim, because my code have to work for validate trigger only not for subfunction.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56629.
