### ISSUE TITLE
Remove Scope OnPrem in function CalculateWithholdingTax table 12113 "Tmp Withholding Contribution"

### ISSUE THREAD

**Issue by Giumai** [microsoft/ALAppExtensions#23356]
In order to be able to change target to cloud, please remove the scope OnPrem from the following functions:
[Scope('OnPrem')]
CalculateWithholdingTax
table 12113 "Tmp Withholding Contribution"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10836.
