### ISSUE TITLE
Attachments_First() from codeunit 8904 "Email Message" is not working as expected

### ISSUE THREAD

**Issue by bineshsingh** [microsoft/ALAppExtensions#23358]
BC 21.5 US Saas.

I was trying to download the attachments from sent email Sample code is attached and 
codeunit 8904 "Email Message" called below procedure is not working as expected.

    /// <summary>
    /// Finds the first attachment of the email message.
    /// </summary>
    /// <returns>True if there is any attachment; otherwise - false.</returns>
    procedure Attachments_First(): Boolean
    begin
        exit(EmailMessageImpl.Attachments_First());
    end;
[Download Email Attachments.txt](https://github.com/microsoft/AL/files/11451724/Download.Email.Attachments.txt)

**Comment by pri-kise** [comment]
I think you have some misconception of streams in your code.
```al
// +--------------------------------------------------------------------------------------------------------+
// | Harger Customizations   (Development by Binesh  )                                  |
// +--------------------------------------------------------------------------------------------------------+
// | Job No.     Date       Description                                                                         |
// ---------------------------------------------------------------------------------------------------------+
//   HGR         05.08.2023 Added this object for Download All Attachments from Sent Emails.

pageextension 50226 "HG_Sent Emails" extends "Sent Emails"
{
    layout
    {

    }
    actions
    {
        addafter(ShowSourceRecord)
        {
            action(HG_DownloadAllAttachments)
            {
                ApplicationArea = All;
                Image = Download;
                Caption = 'Download All Attachments';
                ToolTip = 'Download All Attachments from this page.';


                trigger OnAction()
                var
                    EmailMessage: Codeunit "Email Message";
                    TempSentEmail: Record "Sent Email" temporary;
                    TempBlob, ZipTempBlob : Codeunit "Temp Blob";
                    AttachmentInstream, ZipInStream : InStream;
                    DataCompression: Codeunit "Data Compression";
                    ZipFileOutStream: OutStream;
                    ZipFileName, FileName : Text;
                    FileManagement: Codeunit "File Management";
                    Counter: Integer;
                    Window: Dialog;
                begin
                    ZipFileName := 'AllAttachments.zip';
                    TempSentEmail.Reset();
                    TempSentEmail.DeleteAll();
                    TempSentEmail.Copy(Rec, true);
                    if TempSentEmail.FindSet() then begin
                        Window.Open('Downloading attachments... #1####################\ #2##########');
                        Window.Update(2, TempSentEmail.Count);
                        Clear(ZipTempBlob);
                        Clear(DataCompression);
                        DataCompression.CreateZipArchive();
                        repeat
                            Clear(EmailMessage);
                            Clear(TempBlob);
                            if EmailMessage.Get(TempSentEmail.GetMessageId()) then begin
                                if EmailMessage.Attachments_First() then begin
                                    //+change
                                    //-TempBlob.CreateInStream(AttachmentInstream);
                                    //-EmailMessage.Attachments_GetContent(AttachmentInstream);
                                    //-if TempBlob.HasValue() then begin
                                    Clear(AttachmentInstream);
                                    EmailMessage.Attachments_GetContent(AttachmentInstream);
                                    if EmailMessage.Attachments_GetLength() > 0 then begin
                                    //-change
                                        DataCompression.AddEntry(AttachmentInstream, EmailMessage.Attachments_GetName());
                                        Counter += 1;
                                        Window.Update(1, Counter);
                                    end;
                                end;
                            end;
                        until TempSentEmail.Next() = 0;
                        if Counter > 0 then begin
                            ZipTempBlob.CreateOutStream(ZipFileOutStream);
                            DataCompression.SaveZipArchive(ZipFileOutStream);
                            DataCompression.CloseZipArchive();
                            ZipTempBlob.CreateInStream(ZipInStream);
                            DownloadFromStream(ZipInStream, '', '', '', ZipFileName);
                        end;
                        Window.Close();
                        message('[%1] attachments download successfully!',Counter);
                    end;
                end;
            }
        }
        addlast(Category_Process)
        {
            actionref(HG_DownloadAllAttachments_Promoted; HG_DownloadAllAttachments)
            {
            }
        }
    }
}

```

If you want TempBlob to retrun true for HasValue then you would have to create an outstream for temblob and add copyStream from the instream to the oustream
and afterwards you would have reload the instream from the tempBlob or use ResetPosition on the InStream.
Alternatively you could try as with the simplified version above.

**Comment by bineshsingh** [comment]
> I think you have some misconception of streams in your code.
> 
> ```al
> // +--------------------------------------------------------------------------------------------------------+
> // | Harger Customizations   (Development by Binesh  )                                  |
> // +--------------------------------------------------------------------------------------------------------+
> // | Job No.     Date       Description                                                                         |
> // ---------------------------------------------------------------------------------------------------------+
> //   HGR         05.08.2023 Added this object for Download All Attachments from Sent Emails.
> 
> pageextension 50226 "HG_Sent Emails" extends "Sent Emails"
> {
>     layout
>     {
> 
>     }
>     actions
>     {
>         addafter(ShowSourceRecord)
>         {
>             action(HG_DownloadAllAttachments)
>             {
>                 ApplicationArea = All;
>                 Image = Download;
>                 Caption = 'Download All Attachments';
>                 ToolTip = 'Download All Attachments from this page.';
> 
> 
>                 trigger OnAction()
>                 var
>                     EmailMessage: Codeunit "Email Message";
>                     TempSentEmail: Record "Sent Email" temporary;
>                     TempBlob, ZipTempBlob : Codeunit "Temp Blob";
>                     AttachmentInstream, ZipInStream : InStream;
>                     DataCompression: Codeunit "Data Compression";
>                     ZipFileOutStream: OutStream;
>                     ZipFileName, FileName : Text;
>                     FileManagement: Codeunit "File Management";
>                     Counter: Integer;
>                     Window: Dialog;
>                 begin
>                     ZipFileName := 'AllAttachments.zip';
>                     TempSentEmail.Reset();
>                     TempSentEmail.DeleteAll();
>                     TempSentEmail.Copy(Rec, true);
>                     if TempSentEmail.FindSet() then begin
>                         Window.Open('Downloading attachments... #1####################\ #2##########');
>                         Window.Update(2, TempSentEmail.Count);
>                         Clear(ZipTempBlob);
>                         Clear(DataCompression);
>                         DataCompression.CreateZipArchive();
>                         repeat
>                             Clear(EmailMessage);
>                             Clear(TempBlob);
>                             if EmailMessage.Get(TempSentEmail.GetMessageId()) then begin
>                                 if EmailMessage.Attachments_First() then begin
>                                     //+change
>                                     //-TempBlob.CreateInStream(AttachmentInstream);
>                                     //-EmailMessage.Attachments_GetContent(AttachmentInstream);
>                                     //-if TempBlob.HasValue() then begin
>                                     Clear(AttachmentInstream);
>                                     EmailMessage.Attachments_GetContent(AttachmentInstream);
>                                     if EmailMessage.Attachments_GetLength() > 0 then begin
>                                     //-change
>                                         DataCompression.AddEntry(AttachmentInstream, EmailMessage.Attachments_GetName());
>                                         Counter += 1;
>                                         Window.Update(1, Counter);
>                                     end;
>                                 end;
>                             end;
>                         until TempSentEmail.Next() = 0;
>                         if Counter > 0 then begin
>                             ZipTempBlob.CreateOutStream(ZipFileOutStream);
>                             DataCompression.SaveZipArchive(ZipFileOutStream);
>                             DataCompression.CloseZipArchive();
>                             ZipTempBlob.CreateInStream(ZipInStream);
>                             DownloadFromStream(ZipInStream, '', '', '', ZipFileName);
>                         end;
>                         Window.Close();
>                         message('[%1] attachments download successfully!',Counter);
>                     end;
>                 end;
>             }
>         }
>         addlast(Category_Process)
>         {
>             actionref(HG_DownloadAllAttachments_Promoted; HG_DownloadAllAttachments)
>             {
>             }
>         }
>     }
> }
> ```
> 
> If you want TempBlob to retrun true for HasValue then you would have to create an outstream for temblob and add copyStream from the instream to the oustream and afterwards you would have reload the instream from the tempBlob or use ResetPosition on the InStream. Alternatively you could try as with the simplified version above.

Thank you @pri-kise , it worked for me.
