### ISSUE TITLE
Remove OnPrem on table 12185 "Vendor Bill Withholding Tax" function ValidateWithhSocSec

### ISSUE THREAD

**Issue by Giumai** [microsoft/ALAppExtensions#23357]
In order to be able to change target to cloud, please remove the scope OnPrem from the following functions:

table 12185 "Vendor Bill Withholding Tax"

    [Scope('OnPrem')]
    procedure ValidateWithhSocSec()

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10836.
