### ISSUE TITLE
[BUG] Cannot Register Pick if Direct Transfer is Activ BC22

### ISSUE THREAD

**Issue by PiGlic** [microsoft/ALAppExtensions#23351]
Hi,

i hope this is the right place, found the following BUG in BC 22.1 OnPrem 

I just ran into the following problem when regesting picking process.
![image](https://github.com/microsoft/ALAppExtensions/assets/36172313/0167453a-c46d-4437-9531-302b9b85e9ee)
![image](https://github.com/microsoft/ALAppExtensions/assets/36172313/8fbaa357-fc83-4b03-b30b-1408d96e15eb)

The Function "CheckDirectTransfer" try's to Get the Transfer Header with the "Source No." but is missing a check if the "Source Type" is a Trasnfer Order.

In my case the picking would be created from a Warehouse Shipment that had a sales order as origin.
Because the function does not check whether the source type is a transfer order, the system performs an unintercepted get on the transfer headers with a sales order no.

The event should not be executed if the source type is not a transfer order, furthermore the get should at least be intercepted in the function or checked for type transfer beforehand.

**Comment by pri-kise** [comment]
@PiGlic have you reported this already via other support channels?
It's nice that you share the repo steps here, but this should totally be reported via normal support channels to get the required priority.

**Comment by AlexanderYakunin** [comment]
We have fixed this issue due to RFH created via support, please use support channels next time to get hotfixes.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
