### ISSUE TITLE
[Event Request] & [Extensibility Request] Codeunit 7322 - Create Inventory Pick/Movement

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#23368]
in our business solution there is the possibility to define serial no. >1 for an item.

To implement this properly we need two new Events and one change of a local function to a global one.

The function that must become global is the "MakeLine":

procedure MakeLine(var NewWhseActivLine: Record "Warehouse Activity Line"; TakeBinCode: Code[20]; QtyToPickBase: Decimal; var RemQtyToPickBase: Decimal)
![image](https://github.com/microsoft/ALAppExtensions/assets/9529836/f60a8170-4c02-4269-9cd7-a5dd4849b254)

the two publisher requests are created in #23875

**Comment by AlexanderYakunin** [comment]
Can you please create separate request for making procedure global? Or all this can be classified as external request and done for Master only?

**Comment by Busslar** [comment]
@AlexanderYakunin 
global function request and publisher requests are now separated

**Comment by tomasevics** [comment]
Do you think on procedure MakeLineWhenSNoReq in codeunit "Create Inventory Pick/Movement"?

**Comment by Busslar** [comment]
Just thinking of procedure MakeLine in Codeunit 7322 - Create Inventory Pick/Movement

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11478.
