### ISSUE TITLE
Remove OnPrem Function GetVATRegistrationNo table 38 "Purchase Header"

### ISSUE THREAD

**Issue by Giumai** [microsoft/ALAppExtensions#23366]
In order to be able to change target to cloud, please remove the scope OnPrem from the following functions:
[Scope('OnPrem')]

table 38 "Purchase Header"
    [Scope('OnPrem')]
    procedure GetVATRegistrationNo(VendorNo: Code[20]): Text[20]

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10836.
