### ISSUE TITLE
Remove OnPrem in function Code codeunit 12172 "Customer Bill - Post + Print"

### ISSUE THREAD

**Issue by Giumai** [microsoft/ALAppExtensions#23365]
In order to be able to change target to cloud, please remove the scope OnPrem from the following functions:
[Scope('OnPrem')]

codeunit 12172 "Customer Bill - Post + Print"
    [Scope('OnPrem')]
    procedure "Code"(var LocalCustomerBillHeader: Record "Customer Bill Header")

Thanl you

**Comment by AlexanderYakunin** [comment]
Why do you need this? You can run codeunit itself?

**Comment by Giumai** [comment]
Hi, because we call that function from another procedure in another App.
Thank you

**Comment by AlexanderYakunin** [comment]
The Code procedure is main procedure in such codeunits and supposed to be local. It is NOT local in IT localization due to legacy mistake. Why you cannot call it as Codeunit.Run()?

**Comment by Giumai** [comment]
Yes, It's a good suggestion.
We will change our code.

Thank you.
