### ISSUE TITLE
[Request for External] Report 12176 "Suggest Customer Bills" variable CustomerBillHeader

### ISSUE THREAD

**Issue by FabioC34** [microsoft/ALAppExtensions#23369]
Hello, can you please set the variable "CustomerBillHeader" in R12176 (IT Localization) as protected var?

```
protected var
        CustomerBillHeader: Record "Customer Bill Header";
```

I already requested this in issue #22008, it was approved and closed on 15th February, but I just checked in BC22.1 and it is not yet available
Could you please check?
Thank you
Best Regards
Fabio

**Comment by AlexanderYakunin** [comment]
We do not provide external requests for RELEASED version, we only do this for master

**Comment by FabioC34** [comment]
@AlexanderYakunin: For Master you mean the major release? In this case the request was approved on 15th February, months before BC22 release.
Do you mean I have to wait BC23 in order to use this report?

Thank you
Best regards
Fabio

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10836.
