### ISSUE TITLE
Event Request - OnBeforeUpdateBin - table 5407 "Prod. Order Component"

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#23379]
Please could we have the following event added, to allow us to bypass the Confirmation message:
table 5407 "Prod. Order Component"

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateBin(var ProdOrderComp: Record "Prod. Order Component"; FieldNo: Integer; FieldCaption: Text[30];var IsHandled : Boolean)
    begin
    end;

    local procedure UpdateBin(var ProdOrderComp: Record "Prod. Order Component"; FieldNo: Integer; FieldCaption: Text[30])
    var
        ProdOrderComp2: Record "Prod. Order Component";
        OverwriteBinCode: Boolean;
        IsHandled : Boolean;
    begin
        OnBeforeUpdateBin(ProdOrderComp,FieldNo,FieldCaption,IsHandled);
        if IsHandled then
          exit;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10868.
