### ISSUE TITLE
[PROTECTED VAR ACCESS] Access PrintDoc of report 296 "batch post sales orders"

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#23384]
Hi, 

can you make the variable PrintDoc if report 296 "batch post sales orders" protected so we can use it in our report extension?

New Code:
```
var
        VATReportingDateMgt: Codeunit "VAT Reporting Date Mgt";
        Text003: Label 'The exchange rate associated with the new posting date on the sales header will apply to the sales lines.';
        [InDataSet]
        PrintDocVisible: Boolean;
        VATDateEnabled: Boolean;
        PostInvoiceEditable: Boolean;

    protected var
        ShipReq: Boolean;
        InvReq: Boolean;
        PostingDateReq, VATDateReq: Date;
        ReplacePostingDate, ReplaceVATDateReq: Boolean;
        ReplaceDocumentDate: Boolean;
        CalcInvDisc: Boolean;
        PrintDoc: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10836.
