### ISSUE TITLE
[Protected Var Request] Page 54 "Purchase Order Subform"

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#23380]
Please set "Currency: Record Currency;" as protected var

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10836.
