### ISSUE TITLE
[Event Request] Codeunit 7010 Purch. Price Calc. Mgt. - OnBeforeFindCalcBestDirectUnitCostForJobJnlLinePriceItem

### ISSUE THREAD

**Issue by cosmo-skol** [microsoft/ALAppExtensions#2338]
Hello AL-Team,
we need a new publisher to add and remove specific purchase prices from TempPurchPrice:

[External] FindJobJnlLinePrice(VAR JobJnlLine : Record "Job Journal Line";CalledByFieldNo : Integer)

```
[...]
  CASE Type OF
    Type::Item:
      BEGIN
        Item.GET("No.");
        PriceInSKU := SKU.GET('',"No.","Variant Code");
        Job.GET("Job No.");

        FindPurchPrice(
          TempPurchPrice,'',"No.","Variant Code","Unit of Measure Code","Country/Region Code","Posting Date",FALSE);
        PricesInCurrency := FALSE;
        GLSetup.GET;
        // >> NEW
        OnBeforeFindCalcBestDirectUnitCostForJobJnlLinePriceItem(VAR JobJnlLine,VAR TempPurchPrice);
        // << NEW
        CalcBestDirectUnitCost(TempPurchPrice);
		
[...]
```

Publisher definition:
LOCAL [IntegrationEvent] OnBeforeFindCalcBestDirectUnitCostForJobJnlLinePriceItem(VAR JobJnlLine : Record "Job Journal Line";VAR PurchPrice : TEMPORARY Record "Purchase Price")

Publisher properties:
IncludeSender: FALSE
GlobaVarAccess: FALSE

**Comment by NKarolak** [comment]
Note: created as **OnFindJobJnlLinePriceOnBeforeCalcBestDirectUnitCost**
`LOCAL [IntegrationEvent] OnFindJobJnlLinePriceOnBeforeCalcBestDirectUnitCost(VAR JobJournalLine : Record "Job Journal Line";VAR TempPurchasePrice : TEMPORARY Record "Purchase Price")`
