### ISSUE TITLE
[Event Change Request] codeunit 825 "Sales Post Invoice Events" RunOnAfterGetSalesAccount / OnAfterGetSalesAccount

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23389]
Could you please add the SalesHeader to the event `OnAfterGetSalesAccount``?
```al
//+Change
//-procedure RunOnAfterGetSalesAccount(SalesLine: Record "Sales Line"; GenPostingSetup: Record "General Posting Setup"; var SalesAccountNo: Code[20])
procedure RunOnAfterGetSalesAccount(SalesHeader: Record "Sales Header";SalesLine: Record "Sales Line"; GenPostingSetup: Record "General Posting Setup"; var SalesAccountNo: Code[20])
//-Change
begin
    //+Change
    //-OnAfterGetSalesAccount(SalesLine, GenPostingSetup, SalesAccountNo);
    OnAfterGetSalesAccount(SalesHeader, SalesLine, GenPostingSetup, SalesAccountNo);
    //-Change
end;

[IntegrationEvent(false, false)]
//+Change
local procedure OnAfterGetSalesAccount(SalesLine: Record "Sales Line"; GenPostingSetup: Record "General Posting Setup"; var SalesAccountNo: Code[20])
local procedure OnAfterGetSalesAccount(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; GenPostingSetup: Record "General Posting Setup"; var SalesAccountNo: Code[20])
//-Change
begin
end;
```

You would have to transfer the "SalesHeader" from the procedure `PrepareLine` to the procedure `GetSalesAccount` in `codeunit 815 "Sales Post Invoice" implements "Invoice Posting"`, for this event change request.

**Comment by pri-kise** [comment]
@JesperSchulz  could this maybe be processed, since the old posting engine will be obsoleted and we try to replace this with the new one. Therefore the events should contain the same paramters.

**Comment by JesperSchulz** [comment]
I'll ask the team processing these event requests what the holdup is and provide feedback in this issue.

**Comment by AlexanderYakunin** [comment]
Sorry, old event in Sales Post does not have this parameter and I see no reason to add it to new implementation. You can get Sales Header any time as you have Document Type and No.in Sales Line.
