### ISSUE TITLE
6224 "XML DOM Management" & EnableDocument

### ISSUE THREAD

**Issue by iti-mikolaj-sledz** [microsoft/ALAppExtensions#23388]
Due to National System Of e-Invoice & Polish Localization App building, we wanted to implement xml visualization of e-invoice file. Unfortunately xsl files needed for this functionality includes execution of the 'document()' function, which is prohibited in this version of "dot net codeunit". Is there any possibility to use XsltSettings.EnableDocumentFunction property to enable it? can we ask for modify the "XML DOM Management" in a way that allows it?

**Comment by mikolajsledz** [comment]
Hi, what is the current status of this issues?

**Comment by mikolajsledz** [comment]
Hi, what is the current status of this issues?

**Comment by NKarolak** [comment]
I can only guess what's happening here: You have asked for a change in the XML DOM Management, but this is an old but technical codeunit that is still part of the Base App. As such, it is likely that it will be transferred into the System App "soon", or even removed because the content already exists in the System App, and no requests will be processed.

Have you already checked the XML* codeunits in the System App? Probably they already offer what you need.

**Comment by mikolajsledz** [comment]
Thanks, but unfortunately  i haven't found any code releated to visualization/xml transformation is System App.

**Comment by mikolajsledz** [comment]
I didn't find anything in the new release that could help me with my issue regarding the XSL file(execution of the 'document()'). Do you happen to know of any workaround for this problem?

**Comment by JesperSchulz** [comment]
Sorry about the long reply-time on this issue. I wasn't aware that this many bugs and questions had been filed here, and hence wasn't monitoring this repo.

Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the 1st party Business Central apps.

We have no plans of adding support of the above, so you'd be best advised creating a BC Idea (aka.ms/bcideas), or to participate in the code contribution projects we've got going.

If you'd like to add a module, supporting your request, you can create an issue (linked to an idea) on https://github.com/microsoft/bcapps. If you'd like to propose and make changes to the BaseApp, you can participate in the BaseApp contribution pilot: https://github.com/microsoft/businesscentralapps. For access to the pilot, please fill out the following form: https://forms.office.com/r/E9wyE5a58f.
