### ISSUE TITLE
[Translation]  page 5557 "Permission Conflicts" / page 5555 "Permission Conflicts Overview"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23392]
The following pages are missing a Caption and therefore they aren't translated.

**Comment by JesperSchulz** [comment]
Will get addressed with 22.4.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 58562.
