### ISSUE TITLE
[Event Parameter Request] codeunit 5950 "Service-Calc. Discount" - OnAfterCalcServDiscount

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#23398]
//OnAfterCalcServDiscount(ServHeader); Event22.00.o
OnAfterCalcServDiscount(ServHeader, TempVATAmountLine, ServiceLine2); //Event22.00.n

[IntegrationEvent(false, false)]
//local procedure OnAfterCalcServDiscount(var ServiceHeader: Record "Service Header") Event22.00.o
local procedure OnAfterCalcServDiscount(var ServiceHeader: Record "Service Header"; var TempVATAmountLine: Record "VAT Amount Line" temporary; var ServiceLine2: Record "Service Line") //Event22.00.n
begin
end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56756.
