### ISSUE TITLE
[Event Request]: Purchase Line, Procedure OnCopyFromItemOnAfterCheck

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#23393]
Hi AL-Team,
we suggest a change in the signature of OnCopyFromItemOnAfterCheck - please define Item as Var:

`[IntegrationEvent(false, false)]

local procedure OnCopyFromItemOnAfterCheck(var PurchaseLine: Record "Purchase Line"; var Item: Record Item; CallingFieldNo: Integer)
begin
end;
`
Thanks!

**Comment by AJasp** [comment]
Additional Question - why is this part of checking blocked item in purchase and sales different - that make no sense to me

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 57697.
