### ISSUE TITLE
[Bug?] Issue with planning worksheet (variants and stock keeping units)

### ISSUE THREAD

**Issue by benlkuma** [microsoft/ALAppExtensions#23394]
**How can the issue be traced (issue information in text form)?**

There is a purchase item with a variant. The reordering policy lot-by-lot with corresponding Order Modifier has been defined for the item under the register Planning. There is no stock keeping unit for the item without variant. 

For the variant, in turn, stock keeping unit has been defined. The reordering policy for the variant is "Fixed Reorder Quantity".

For both the item and the item variant, demands are generated by sales orders. In the planning worksheet, the variant of the item is planned correctly according to "Fixed order quantity". The item without a variant ignores the "Lot-by-Lot" reordering policy and associated modifiers. The item without variant is planned according to the standard BC logic.

**What is the current result?**

In the planning worksheet, the variant of the item is planned correctly according to "Fixed order quantity". The item without variant ignores the "Lot-by-lot" reordering policy and the associated modifiers. The item without variant is planned according to the standard BC logic.

**What is the expected outcome?**

The planning worksheet will take stock keeping units into account if any are available. If no stock keeping units are available. (In this case, the item without variant has no stock keeping units.) Then the planning parameters from the item card should apply. So "lot-by-lot".

Thank you for checking!

First Case:

![1](https://github.com/microsoft/ALAppExtensions/assets/133750403/74172c08-64dd-4c6a-ae63-20197df06275)
![2](https://github.com/microsoft/ALAppExtensions/assets/133750403/c4153f54-a33d-42bb-a9f5-a4b73a23f666)
![3](https://github.com/microsoft/ALAppExtensions/assets/133750403/fea059e7-d7dd-428b-b275-736c297429fc)
![4](https://github.com/microsoft/ALAppExtensions/assets/133750403/ca3f8fa8-e894-4932-ad18-0a967443f019)
![5](https://github.com/microsoft/ALAppExtensions/assets/133750403/26f2e26e-3629-4e4a-b18b-03b4181e395a)
![6](https://github.com/microsoft/ALAppExtensions/assets/133750403/ab1e9748-b73e-4fe0-993c-f26ca9c11135)

Second Case:

![1](https://github.com/microsoft/ALAppExtensions/assets/133750403/1a2ffc96-5775-435f-8f1f-91176af5b769)
![2](https://github.com/microsoft/ALAppExtensions/assets/133750403/6fc6f91d-46cc-44a4-9105-ce4240190f81)
![3](https://github.com/microsoft/ALAppExtensions/assets/133750403/bf3d0f8b-31d9-4d87-a994-bfb75488449e)
![4](https://github.com/microsoft/ALAppExtensions/assets/133750403/7ff4c994-7f31-4362-ab4f-128b75be811a)
![5](https://github.com/microsoft/ALAppExtensions/assets/133750403/9f7b8a76-d8db-49be-aac8-a06cf88473fb)
![6](https://github.com/microsoft/ALAppExtensions/assets/133750403/c55e0405-b813-404e-a3cf-7343c23a7da8)

**Comment by JakovljevicDusan** [comment]
Please open support ticket for these functional issues so dedicated team can check whether is this by design or bug.
