### ISSUE TITLE
CODEUNIT 2854. We need to add an event to be able to apply more filters to the analysis views that we want to update when modifying dimensions in the general ledger entries.

### ISSUE THREAD

**Issue by NekaneBachillerMayoral** [microsoft/ALAppExtensions#23403]
In the codeunit 2854 Dim Corr Analysis View in procedure UpdateSelectedAnalysisViews we need to add an event that allows us to apply additional filters to the analysis views that are going to be automatically updated from the project queue.

    local procedure UpdateSelectedAnalysisViews(var DimensionCorrection: Record "Dimension Correction")
    var
        AnalysisView: Record "Analysis View";

        UpdatedAnalysisView: Record "Analysis View";
        UpdateAnalysisView: Codeunit "Update Analysis View";
    begin
        AnalysisView.SetRange(Blocked, false);
        AnalysisView.SetRange("Account Source", AnalysisView."Account Source"::"G/L Account");

        **_OnUpdateSelectAnalysisView(AnalysisView.);_**
        
        if AnalysisView.IsEmpty() then
            exit;
        AnalysisView.FindSet();
        repeat
            if ShouldUpdateAnalysisView(AnalysisView, DimensionCorrection) then begin
                AnalysisView."Reset Needed" := true;
                AnalysisView.Modify();
            end;
        until AnalysisView.Next() = 0;
        Commit();

        AnalysisView.SetRange("Reset Needed", true);
        if AnalysisView.IsEmpty() then
            exit;

        AnalysisView.FindSet();
        repeat
            if AnalysisView."Update on Posting" or (DimensionCorrection."Analysis View Update Type" = DimensionCorrection."Analysis View Update Type"::All) then begin
                UpdatedAnalysisView.Get(AnalysisView.RecordId);
                UpdatedAnalysisView.AnalysisViewReset();
                UpdateAnalysisView.Update(UpdatedAnalysisView, 2, false);
                Commit();
            end;
        until AnalysisView.Next() = 0;
    end;

//NEW EVENT BEGIN
[IntegrationEvent(false, false)]
    local procedure OnUpdateSelectAnalysisView(Var AnalysisView: Record "Analysis View");
    begin
    end;
//NEW EVENT END

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56756.
