### ISSUE TITLE
[Event Request] Codeunit 7010 Purch. Price Calc. Mgt. - OnBeforeFindCalcBestDirectUnitCostForItemJnlLinePriceItem

### ISSUE THREAD

**Issue by cosmo-skol** [microsoft/ALAppExtensions#2340]
Hello AL-Team,
we need a new publisher to add and remove specific purchase prices from TempPurchPrice:

[External] FindItemJnlLinePrice(VAR ItemJnlLine : Record "Item Journal Line";CalledByFieldNo : Integer)

```
[...]

WITH ItemJnlLine DO BEGIN
  TESTFIELD("Qty. per Unit of Measure");
  SetCurrency('',0,0D);
  SetVAT(FALSE,0,'');
  SetUoM(ABS(Quantity),"Qty. per Unit of Measure");

  Item.GET("Item No.");
  PriceInSKU := SKU.GET("Location Code","Item No.","Variant Code");

  FindPurchPrice(
    TempPurchPrice,'',"Item No.","Variant Code",
    "Unit of Measure Code",'',"Posting Date",FALSE);

  // >> NEW
  OnBeforeFindCalcBestDirectUnitCostForItemJnlLinePriceItem(ItemJnlLine,TempPurchPrice);
  // << NEW
  CalcBestDirectUnitCost(TempPurchPrice);

		
[...]
```

Publisher definition:
LOCAL [IntegrationEvent] OnBeforeFindCalcBestDirectUnitCostForItemJnlLinePriceItem(VAR ItemJnlLine : Record "Item Journal Line";VAR PurchPrice : TEMPORARY Record "Purchase Price")

Publisher properties:
IncludeSender: FALSE
GlobaVarAccess: FALSE

**Comment by NKarolak** [comment]
Note: created as **OnFindItemJnlLinePriceOnBeforeCalcBestDirectUnitCost**
`LOCAL [IntegrationEvent] OnFindItemJnlLinePriceOnBeforeCalcBestDirectUnitCost(VAR ItemJournalLine : Record "Item Journal Line";VAR TempPurchasePrice : TEMPORARY Record "Purchase Price")`
