### ISSUE TITLE
[Event Request] codeunit 70 "Purch.-Calc.Discount" - OnCalculateInvoiceDiscountOnBeforePurchLine2DeleteTrue

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#23419]
The same as is already doen in "Sales-Calc. Discount":

procedure CalculateInvoiceDiscount(var PurchHeader: Record "Purchase Header"; var PurchLine2: Record "Purchase Line")
        ...
                        if (TempServiceChargeLine."Receipt No." = '') and (TempServiceChargeLine."Qty. Rcd. Not Invoiced (Base)" = 0) then begin
                            PurchLine2 := TempServiceChargeLine;
                            //Event22.00.ns
                            IsHandled := false;
                            OnCalculateInvoiceDiscountOnBeforePurchLine2DeleteTrue(UpdateHeader, PurchLine2, IsHandled);
                            if not IsHandled then
                                //Event22.00.ne
                                PurchLine2.Delete(true);
                        end;
        ...
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCalculateInvoiceDiscountOnBeforePurchLine2DeleteTrue(UpdateHeader: Boolean; var PurchLine2: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56756.
