### ISSUE TITLE
[Change Request] table 38 "Purchase Header" - procedure CouldDimensionsBeKept

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#23414]
Hello, can you please set the local procedure CouldDimensionsBeKept as global?

```
    procedure CouldDimensionsBeKept() Result: Boolean;
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCouldDimensionsBeKept(Rec, xRec, Result, IsHandled);
        if not IsHandled then begin
            if CurrFieldNo = 0 then
                exit(false);
            if (xRec."Buy-from Vendor No." <> '') and (xRec."Buy-from Vendor No." <> Rec."Buy-from Vendor No.") then
                exit(false);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10836.
