### ISSUE TITLE
Error in page 9200 "Personalized Pages" GenerateUserSidFilter BC22

### ISSUE THREAD

**Issue by LoneMH** [microsoft/ALAppExtensions#23425]
Version: DK Business Central 22.0 (Platform 22.0.55180.0 + Application 22.0.54157.55195)

It is not possible to open page 9200 "Personalized Pages" due to error in code.

Error message:
If requesting support, please provide the following details to help troubleshooting:

The filter "|{FA336AEC-25BC-462A-BFC8-F46A6AAAFA48}" is not valid for the User SID field on the User Page Metadata table. The left side of '|' operators cannot be empty.

Internal session ID: 
94c964fc-058e-457e-9497-8d568d1492d1

Application Insights session ID: 
377965cb-6cbe-48b0-be8f-1e43b4190f52

Client activity id: 
b7626a0f-e284-8346-b20f-c6c831e743ed

Time stamp on error: 
2023-05-17T06:22:13.7524149Z

AL call stack: 
"Personalized Pages"(Page 9200).OnOpenPage(Trigger) line 7 - Base Application by Microsoft
-----------------------------------------------------------------------
With this code it isn't possible NOT to start with | if any user exists.

    local procedure GenerateUserSidFilter() UserSidFilter: Text
    var
        User: Record User;
        UserSelection: Codeunit "User Selection";
    begin
        UserSidFilter := UserSecurityId();

        UserSelection.HideExternalUsers(User);

        if User.FindSet() then
            repeat
                UserSidFilter := '|' + User."User Security ID"; <----------
            until User.Next() = 0
    end;

**Comment by AlexanderYakunin** [comment]
This is already fixed in 22.1, if you need this fixed in 22.0 please create support ticket.
