### ISSUE TITLE
[Event Change Request] codeunit 7500 "Item Attribute Management" - "Item Attribute Management"

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/ALAppExtensions#23437]
Dear ALAppExtensions Team:

Please consider changing the call on the "Item" record as "**var** Item: Record Item" in the "InheritAttributesFromItemCategory" function:
**Old procedure definition:**
```
procedure InheritAttributesFromItemCategory(Item: Record Item; NewItemCategoryCode: Code[20]; OldItemCategoryCode: Code[20])
```
**New procedure definition:**
```
procedure InheritAttributesFromItemCategory(var Item: Record Item; NewItemCategoryCode: Code[20]; OldItemCategoryCode: Code[20])
```

**NB: in that case, it will be necessary to make the same change in the 2 functions OnBefore & OnAfter of Issue #23435 is approved.**

**Comment by YvesDesrumaux** [comment]
Hello, ALAppExtensions Team,
Do you have any idea of when the status could be set?
We need that change for an AppSource extension.
Thanks a lot

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11090.
