### ISSUE TITLE
[Event Request] - OnUpdateWithWarehouseShip_AfterCheckType table 5902 "Service Line"

### ISSUE THREAD

**Issue by mcarmenvalera** [microsoft/ALAppExtensions#23433]
Dear ALAppExtensions Team:

Please consider adding a new event publisher in table 5902 "Service Line"

NEW PUBLISHER:

[IntegrationEvent(false, false)]
local procedure OnUpdateWithWarehouseShip_AfterCheckType(var ServiceLine: Record "Service Line"; var IsHandled: Boolean)
begin
end;

The code in procedure "UpdateWithWarehouseShip" in table 5902 "Service Line" would be modified as follows:

OLD CODE:

    procedure UpdateWithWarehouseShip()
    begin
        if Type <> Type::Item then
            exit;
        if "Document Type" in ["Document Type"::Quote, "Document Type"::Order] then
.
.
.

NEW CODE:

    procedure UpdateWithWarehouseShip()
    var
       IsHandled: Boolean;
    begin
        if Type <> Type::Item then
            exit;

       IsHandled := false;
       OnUpdateWithWarehouseShip_AfterCheckType(Rec, IsHandled);

       if IsHandled then
         exit;

        if "Document Type" in ["Document Type"::Quote, "Document Type"::Order] then
.
.
.

Thanks in advance!

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56846.
