### ISSUE TITLE
[Event Request] OnBeforeTransShptLineModify in codeunit 9030 "Undo Transfer Shipment"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#23432]
Please add a new trigger OnBeforeTransShptLineModify in codeunit 9030 "Undo Transfer Shipment":

local procedure "Code"()
...
            UpdateOrderLine(TransShptLine);
            if PostedWhseShptLineFound then
                WhseUndoQty.UpdateShptSourceDocLines(PostedWhseShptLine);

            TransShptLine."Correction Line" := true;
--> OnBeforeTransShptLineModify(TransShptLine);
            TransShptLine.Modify();

        until TransShptLine.Next() = 0;

        MakeInventoryAdjustment();
        OnAfterCode(TransShptLine);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransShptLineModify(var TransShptLine: Record "TransferShipment Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56846.
