### ISSUE TITLE
[Event Request] OnBeforeNewTransShptLineInsert in codeunit 9030 "Undo Transfer Shipment"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#23431]
Please add a new event trigger OnBeforeNewTransShptLineInsert in codeunit 9030 "Undo Transfer Shipment" in procedure InsertNewShipmentLine:

    local procedure InsertNewShipmentLine(OldTransShptLine: Record "Transfer Shipment Line"; ItemShptEntryNo: Integer; DocLineNo: Integer)
    var
        NewTransShptLine: Record "Transfer Shipment Line";
    begin
        NewTransShptLine.Init();
        NewTransShptLine.Copy(OldTransShptLine);
        NewTransShptLine."Derived Trans. Order Line No." := 0;
        NewTransShptLine."Line No." := DocLineNo;
        NewTransShptLine."Item Shpt. Entry No." := ItemShptEntryNo;
        NewTransShptLine.Quantity := -OldTransShptLine.Quantity;
        NewTransShptLine."Quantity (Base)" := -OldTransShptLine."Quantity (Base)";
        NewTransShptLine."Correction Line" := true;
        NewTransShptLine."Dimension Set ID" := OldTransShptLine."Dimension Set ID";
-->  OnBeforeNewTransShptLineInsert(NewTransShptLine,OldTransShptLine);
        NewTransShptLine.Insert();

        InsertItemEntryRelation(TempGlobalItemEntryRelation, NewTransShptLine, OldTransShptLine."Trans. Order Line No.");
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeNewTransShptLineInsert(var NewTransShptLine: Record "Transfer Shipment Line"; OldTransShptLine: Record "Transfer Shipment Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56846.
