### ISSUE TITLE
[Event Request] OnAfterCopyItemJnlLineFromTransShpt in codeunit 9030 "Undo Transfer Shipment"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#23442]
Please add a new trigger OnAfterCopyItemJnlLineFromTransShpt in local procedure PostItemJnlLine in codeunit 9030 "Undo Transfer Shipment" similar to OnAfterCopyItemJnlLineFromSalesShpt in codeunit 5815 "Undo Sales Shipment Line":

local procedure PostItemJnlLine(TransShptLine: Record "Transfer Shipment Line"; var DocLineNo: Integer): Integer
...
        ItemJnlLine."Document Date" := TransShptHeader."Shipment Date";
        ItemJnlLine."Unit of Measure Code" := TransShptLine."Unit of Measure Code";

OnAfterCopyItemJnlLineFromTransShpt(ItemJournalLine,TransShptHeader,TransShptLine);

        WhseUndoQty.InsertTempWhseJnlLine(
                       ItemJnlLine,
                       Database::"Transfer Line", Direction::Outbound.AsInteger(), TransShptLine."Transfer Order No.", TransShptLine."Line No.",
                       TempWhseJnlLine."Reference Document"::"Posted Shipment".AsInteger(), TempWhseJnlLine, NextLineNo);

    [IntegrationEvent(false, false)]
    local procedure OnAfterCopyItemJnlLineFromTransShpt(var ItemJournalLine: Record "Item Journal Line"; TransShptHeader: Record "Transfer Shipment Header"; TransShptLine: Record "TransferShipment Line")
    begin
    end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56846.
