### ISSUE TITLE
[Event Request] CU80 OnBeforePostSalesDoc - IncludeSender

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#2344]
Please Include Sender for procedure OnBeforePostSalesDoc in CU80. In our case we have a need to call the function SetPostingFlags when using OnBeforePostSalesDoc. Alternatively the function SetPostingFlags could be called before the publisher.

**Comment by AlexanderYakunin** [comment]
Function SetPostingFlags already made external, it should resolve you case.
