### ISSUE TITLE
[Event Request] codeunit 1001 "Job Post-Line" procedure PostInvoiceContractLine() event OnBeforePostInvoiceContractLine

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#23445]
Can you please add a JobPlanningLine var parameter to the existing OnBeforePostInvoiceContractLine event...

Current

`
local procedure OnBeforePostInvoiceContractLine(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line")
`

New

`
local procedure OnBeforePostInvoiceContractLine(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; var JobPlanningLine: Record "Job Planning Line")
`

**Comment by AleksandricMarko** [comment]
Hi @kmistrytnp 
Could you explain us what the purpose is of adding "Job Planning Line"?
You want to put some additional filters on it before system "findfirst"?

**Comment by kmistrytnp** [comment]
Hi @AleksandricMarko , Yes, that's exactly what I want to do.

**Comment by AleksandricMarko** [comment]
Hi @kmistrytnp 

Then, maybe, it would be better to add another one.

JobPlanningLine.SetCurrentKey("Job Contract Entry No.");
JobPlanningLine.SetRange("Job Contract Entry No.", SalesLine."Job Contract Entry No.");
OnPostInvoiceContractLineOnBeforeJobPlanningLineFindFirst(SalesHeader, SalesLine, JobPlanningLine);  //NEW
JobPlanningLine.FindFirst();

![image](https://github.com/microsoft/ALAppExtensions/assets/133204513/69500067-0259-4a6f-b882-233c8b88841b)

**Comment by kmistrytnp** [comment]
I'm happy to have the new one you have suggested instead, just as good for me.  Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10907.
