### ISSUE TITLE
[Change Request] page 183 "Reverse Transaction Entries" - procedure Post

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#23453]
Hello, can you please change the procedure post as a global procedure ?

```
    procedure Post(PrintRegister: Boolean)
    var
        ReversalPost: Codeunit "Reversal-Post";
    begin
        ReversalPost.SetPrint(PrintRegister);
        ReversalPost.Run(Rec);
        CurrPage.Update(false);
        CurrPage.Close();
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11082.
