### ISSUE TITLE
[Event Request] codeunit 17 "Gen. Jnl.-Post Reverse" - OnReverseOnBeforeUpdateAnalysisView

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#23459]
Hello, can you please add a new Event OnReverseOnBeforeUpdateAnalysisView in codeunit 17 "Gen. Jnl.-Post Reverse" ?

```
        if GLReg2."No." <> 0 then
            if GLReg2.Find() then begin
                GLReg2.Reversed := true;
                GLReg2.Modify();
            end;

        DeleteReversalEntries(TransactionKey);

        IsHandled := false;
        OnReverseOnBeforeUpdateAnalysisView(IsHandled);
        if not IsHandled then
                UpdateAnalysisView.UpdateAll(0, true);

        OnAfterReverse(GLReg);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnReverseOnBeforeUpdateAnalysisView(var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10907.
