### ISSUE TITLE
Rec.CalcFields causes JIT Error on Page. 

### ISSUE THREAD

**Issue by jonaswre** [microsoft/ALAppExtensions#23452]
There seems to be an issue with the latest BC 22. 

If you run Rec.CalcFields on a page to "calculate" a blob. Next time you change Rec you will get the following error.

![1](https://github.com/microsoft/ALAppExtensions/assets/3731681/0012160a-46c0-4773-95f6-13185c18bbc5)

We've created a repo that reproduces this. 
https://github.com/byndit/Debug-JIT-Error#readme

Since this was working in 21. This is probably a bug.

**Comment by pri-kise** [comment]
@AlexanderYakunin you probably should add the foundation tag.
And maybe you can ask someone of the plattform team to check out this issue.
I can't find the release notes for the change on JIT loading, but I think there has been some improvements for BC 22 where they removed the loading of blob fields data length on pages. This was at least mentioned in the Business Central Launch Event by @KennieNP 
![image](https://github.com/microsoft/ALAppExtensions/assets/56249171/1e7af311-ac64-4d06-984e-6fa510ed81be)

I don't know if this is related, but I could be the case.

**Comment by arsag** [comment]
@pri-kise While it might be related, but in this case the Source Table isn't extended. The blob field is in the primary table.

**Comment by PhDuck** [comment]
@jonaswre I just tried out your well written reproductive steps on v24 and cannot reproduce it.

I'm pretty sure we hotfixed this in later versions of v22 and v23, could you please confirm if you can still reproduce this.
