### ISSUE TITLE
[Event Request] codeunit 386 "Reverse Payment Rec. Journal" - OnAfterReverseEntry

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#23450]
Hello, can you please add a new Event OnAfterReverseEntry in codeunit 386 "Reverse Payment Rec. Journal" ?

```
            PaymentRecRelatedEntry."Entry Type"::Employee:
                begin
                    EmployeeLedgerEntry.Get(PaymentRecRelatedEntry."Entry No.");
                    ErrorIfEntryIsNotReversable(EmployeeLedgerEntry);
                    ReversalEntry.ReverseTransaction(EmployeeLedgerEntry."Transaction No.");
                end;
        end;
        RefreshRelatedEntryReversalStatus(PaymentRecRelatedEntry);
        OnAfterReverseEntry();
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterReverseEntry();
    begin
    end;
```

**Comment by MarkoTrn** [comment]
Hello,

Do you need record parameter in OnAfterReverseEntry("Payment Rec. Related Entry")?

**Comment by ReneZiel** [comment]
No we don´t need a record parameter in this case.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10874.
