### ISSUE TITLE
[Change Request] codeunit 7017 "Price List Management" procedure FindDuplicatePrices

### ISSUE THREAD

**Issue by KaMu0608** [microsoft/ALAppExtensions#23465]
Hi, could you please change the procedure FindDuplicatePrices as a global procedure?

procedure FindDuplicatePrices(PriceListHeader: Record "Price List Header"; var PriceListLine: Record "Price List Line"; SearchInside: Boolean; var DuplicatePriceLine: Record "Duplicate Price Line") Found: Boolean;
    var
        DuplicatePriceListLine: Record "Price List Line";
        LineNo: Integer;
    begin
        DuplicatePriceLine.Reset();
        DuplicatePriceLine.DeleteAll();

        if PriceListLine.FindSet() then
            repeat
                FindDuplicatePrice(
                    PriceListLine, PriceListHeader."Allow Updating Defaults", SearchInside,
                    DuplicatePriceLine, LineNo, DuplicatePriceListLine);
            until PriceListLine.Next() = 0;
        Found := LineNo > 0;
    end;`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11478.
