### ISSUE TITLE
[Event Request] codeunit 1004 "Job Transfer Line" procedure FromGenJnlLineToJnlLine()

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#23461]
Please can you add the following event/code at the start of the above procedure...

```
OnBeforeFromGenJnlLineToJnlLine(JobPlanningLine, JobLedgEntry);
```

It is the same signature as the OnAfterFromGenJnlLineToJnlLine event but just called as the start of the procedure

The event publisher would be...

```
[IntegrationEvent(false, false)]
local procedure OnAfterFromGenJnlLineToJnlLine(var JobJnlLine: Record "Job Journal Line"; GenJnlLine: Record "Gen. Journal Line")
begin
end;
```

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 56846.
