### ISSUE TITLE
[Application Enhancement] Introduce report usage for Service Item Worksheet

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#2347]
Dear ALAppExtensions team,

Through this issue we would like to request a new report usage to be introduced by default, and have this usage used in the **Print** action ('Action4') of Page 5906 Service Item Worksheet rather than printing the standard "Service Item Worksheet" report.

**Comment by RomanZanizdra** [comment]
Hi rvanbekkum. Can you describe why do you need new Usage in Report Selection for this report? Yes, there is a direct call of a report but what will happen if we add a new usage, does it worth it, which of problems will it resolve?

**Comment by RomanZanizdra** [comment]
Hi rvanbekkum.
Sorry for boring you, is this still relevant for you? Can we close this issue?

**Comment by rvanbekkum** [comment]
Hi @RomanZanizdra, Thank you for your questions.
Yes, this is definitely relevant for us. This is a document that is **very** often customized for each of our customers, not simply in layout but in report object(s). Therefore, the standard report is often replaced with a custom report object. It is also a document that is used externally, i.e., send to and viewed by their customers.
Also, it sometimes, but less often, happens that our currently custom report selection/usage is configured to use multiple reports for the service item worksheet document.

Therefore we added the suggestion to add a usage in the base application for the service item worksheet, because it seems odd that all main sales, purchase and service documents are available in the report selections except for this document that is also often configured per customer.
Please let me know whether this answers your questions.

**Comment by RomanZanizdra** [comment]
Hi rvanbekkum. I'm not sure this is task for extensibility right now due to of Usage in Report Selection is full of everything, upgrade and all around. I believe this is quite important for you, so could you be so kind to log your suggestion on the ideas site (https://aka.ms/bcideas) and let others to review it and vote. In that case we will be able to process it and prioritize. If you don't have objections let's close this issue for now or let me know if you are required any events/externals which can help you in your situation.

**Comment by RomanZanizdra** [comment]
Hi rvanbekkum. Anything from your side, I plan to close this issue?

**Comment by rvanbekkum** [comment]
Hi RomanZanizdra, you can close the issue for now. I will post this improvement suggestion on the ideas site once I'm able to log in again.

**Comment by RomanZanizdra** [comment]
Thanks for collaboration.
