### ISSUE TITLE
SharePoint Client enhancement in PR #22988 are not suitable for use

### ISSUE THREAD

**Issue by glachana** [microsoft/ALAppExtensions#23470]
@JesperSchulz @pri-kise,

Hi all, 
I just download symbols with build id 56517 (Microsoft_System Application_22.2.56679.0.app), and it seems that several functions 
are missing in public implementation in codeunit 9100 "SharePoint Client".

-     procedure DownloadFileContent(OdataId: Text; var TempBlob: Codeunit "Temp Blob"): Boolean
-     procedure DownloadFileContentByServerRelativeUrl(ServerRelativeUrl: Text; var FileInStream: InStream): Boolean
-     procedure DownloadFileContentByServerRelativeUrl(ServerRelativeUrl: Text; FileName: Text): Boolean
-     procedure DownloadFileContentByServerRelativeUrl(ServerRelativeUrl: Text; var TempBlob: Codeunit "Temp Blob"): Boolean
-     procedure DeleteFile(OdataId: Text): Boolean
-     procedure DeleteFileByServerRelativeUrl(ServerRelativeUrl: Text): Boolean

There are all well added in codeunit 9101 "SharePoint Client Impl.". 

Is this normal ?

_Originally posted by @glachana in https://github.com/microsoft/ALAppExtensions/issues/22988#issuecomment-1551274415_

**Comment by pri-kise** [comment]
@JesperSchulz could yo please take a look at the following.
@glachana you're right these procedure are missing in the PR for latest changes of BC 22.1
https://github.com/microsoft/ALAppExtensions/pull/23630

**Comment by JesperSchulz** [comment]
We'll look into this!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10996.

**Comment by JesperSchulz** [comment]
Ready for release with 22.3.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 57808.
