### ISSUE TITLE
[Event Request] Codeunit 1105 - GetGLEntries

### ISSUE THREAD

**Issue by stephanweidmann** [microsoft/ALAppExtensions#23479]
In Combination with https://github.com/microsoft/ALAppExtensions/issues/23478,
-> allows filling both cost center and cost object, 
and checking a (customspecific) validity date range for a cost object.

                if not SkipGLEntry(GLEntry) then
                    case true of // only need Cost Center or Cost Object
                        GetCostCenterCode(GLEntry."Dimension Set ID", CostCenterCode),
                        GetCostObjectCode(GLEntry."Dimension Set ID", CostObjectCode):
                            begin
                                // New
                                ishandled := false;
                                OnBeforeProcessGLEntryInGetGLEntries(GLentry,CostCenterCode,CostObjectCode,BatchRun,IsHandled);
                                if not IsHandled then begin
                                // New
                                  case CostType."Combine Entries" of
                                      CostType."Combine Entries"::None:
                                          PostingDate := GLEntry."Posting Date";
                                      CostType."Combine Entries"::Month:
                                          begin
                                              PostingDate := CalcDate('<CM>', GLEntry."Posting Date");
                                              CombinedEntryText := StrSubstNo(Text003, PostingDate);
                                          end;
                                      CostType."Combine Entries"::Day:
                                          begin
                                              PostingDate := GLEntry."Posting Date";
                                              CombinedEntryText := StrSubstNo(Text004, PostingDate);
                                          end;
                                  end;
  
                                  CombineEntries := CostType."Combine Entries" <> CostType."Combine Entries"::None;
                                  OnGetGLEntriesOnBeforeCombineEntries(CostCenterCode, GLEntry, CostType, CombineEntries);
                                  if CombineEntries then begin
                                      TempCostJnlLine.Reset();
                                      TempCostJnlLine.SetRange("Cost Type No.", CostType."No.");
                                      if CostCenterCode <> '' then
                                          TempCostJnlLine.SetRange("Cost Center Code", CostCenterCode)
                                      else
                                          TempCostJnlLine.SetRange("Cost Object Code", CostObjectCode);
                                      TempCostJnlLine.SetRange("Posting Date", PostingDate);
                                      if TempCostJnlLine.FindFirst() then
                                          ModifyCostJournalLine(CombinedEntryText)
                                      else
                                          InsertCostJournalLine(CostCenterCode, CostObjectCode);
                                  end else
                                      InsertCostJournalLine(CostCenterCode, CostObjectCode);
  
                                  if BatchRun and ((GLEntry."Entry No." mod 100) = 0) then begin
                                      Window.Update(2, CostType."No.");
                                      Window.Update(3, Format(NoOfCombinedEntries));
                                      Window.Update(4, Format(NoOfJnlLines));
                                  end;
                                // new
                                end;
                                // new
                            end;
                            
                            
                            [IntegrationEvent(false, false)]
                            local procedure OnGetGLEntriesOnBeforeCombineEntries(var GLEntry: Record "G/L Entry"; var CostCenterCode: Code[20]; var CostObjectCode: Code[20];BatchRun: Boolean; var IsHandled: Boolean)
                            begin
                            end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10889.
