### ISSUE TITLE
[Event Request] codeunit 99000834 "Purch. Line-Reserve" - OnBeforeVerifyChange

### ISSUE THREAD

**Issue by BharatVelosio** [microsoft/ALAppExtensions#23474]
Hi Team,

In codeunit 99000834, please provide the possibility to have OnBeforeVerifyChange event in procedure.

 procedure VerifyChange(var NewPurchLine: Record "Purchase Line"; var OldPurchLine: Record "Purchase Line")

After begin at Line No 124

IsHandled := false;
OnBeforeVerifyChange(NewPurchaseLine, OldPurchaseLine, IsHandled);
if IsHandled then
   exit;

<img width="807" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/133997930/193780d5-67e1-4417-8ab6-8af751b39e40">

Event:
[IntegrationEvent(false, false)]
    local procedure OnBeforeVerifyChange(var NewPurchaseLine: Record "Purchase Line"; var OldPurchaseLine: Record "Purchase Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by BharatVelosio** [comment]
Hi Team,

Any update on the above request.

**Comment by BharatVelosio** [comment]
Hi Team

Any update on the above request.

**Comment by AleksandricMarko** [comment]
Event already implemented by other request(s).
It is or will be available in some of the next releases.
