### ISSUE TITLE
[Event Request] table 246 "Requisition Line" - OnAfterUpdateDescription

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#23480]
Add "var" to RequisitionLine parameter to us it as reference to be able to update values.

```
    [IntegrationEvent(false, false)]
    //local procedure OnAfterUpdateDescription(RequisitionLine: Record "Requisition Line"; Item: Record Item; ItemVariant: Record 
    local procedure OnAfterUpdateDescription(var RequisitionLine: Record "Requisition Line"; Item: Record Item; ItemVariant: Record "Item Variant"; FieldNo: Integer)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10874.
