### ISSUE TITLE
[Event Request] codeunit 5777 "Whse. Validate Source Line" OnWhseLinesExistOnAfterWhseShptLineSetFilters

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#23488]
Can you add IsHandled to event OnWhseLinesExistOnAfterWhseShptLineSetFilters?
I want to be able to override this check:

```
            OnWhseLinesExistOnAfterWhseShptLineSetFilters(WhseShptLine, SourceType, SourceSubType, SourceNo, SourceLineNo, SourceQty);
            if not WhseShptLine.IsEmpty() then begin
                TableCaptionValue := WhseShptLine.TableCaption();
                exit(true);
            end;
```

I have solved this today by using SetRange("Line No.",0), but I want to make the code better.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10874.
