### ISSUE TITLE
Codeunit 5901 - ServLoanerManagement - OnBeforeReceiveLoaner new event

### ISSUE THREAD

**Issue by DParkerRSM** [microsoft/ALAppExtensions#23482]
I am working on a modification to allow users ship and receive loaners for service management where item ledger entries are generated and used with the loaner. I already have the shipping portion working but now I am working on the return process.

procedure ReceiveLoaner(var ServItemLine: Record "Service Item Line")
    var
        Loaner: Record Loaner;
        LoanerEntry: Record "Loaner Entry";
        ServLogMgt: Codeunit ServLogManagement;
        ConfirmManagement: Codeunit "Confirm Management";
        Add >>
        IsHandled: Boolean;
        << Add <<
    begin

Add >>
OnBeforeReceiveLoaner(ServItemLine: Record "Service Item Line", IsHandled);
If IsHandled then
     exit();
<< Add <<

        if ServItemLine."Loaner No." <> '' then begin
            if not ConfirmManagement.GetResponseOrDefault(StrSubstNo(Text005, ServItemLine."Loaner No."), true) then
                exit;
            LoanerEntry.Reset();
            LoanerEntry.SetCurrentKey("Document Type", "Document No.", "Loaner No.", Lent);

Add >>
[IntegrationEvent(false, false)]
local procedure OnBeforeReceiveLoaner(var ServItemLine: Record "Service Item Line", var IsHandled: Boolean)
begin
end;
<< Add <<

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10874.
