### ISSUE TITLE
[Event Request] codeunit 17 "Gen. Jnl.-Post Reverse" - OnBeforeDeleteReversalEntries

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#23496]
Hello, can you please add a new Event OnBeforeDeleteReversalEntries in codeunit 17 "Gen. Jnl.-Post Reverse" ?

```
    local procedure DeleteReversalEntries(TransactionKey: Integer)
    var
        ReversalEntry: Record "Reversal Entry";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeDeleteReversalEntries(IsHandled);
        if IsHandled then
            exit;
        ReversalEntry.SetRange("Transaction No.", TransactionKey);
        ReversalEntry.DeleteAll();
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteReversalEntries(var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10907.
