### ISSUE TITLE
[Change Request] table 179 "Reversal Entry" - procedure InsertReversalEntry

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#23501]
Hello, can you please change the procedure InsertReversalEntry from local to global ?

```
    procedure InsertReversalEntry(Number: Integer; RevType: Option Transaction,Register)
    var
        TempRevertTransactionNo: Record "Integer" temporary;
        NextLineNo: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeInsertReversalEntry(Rec, Number, RevType, IsHandled);
        if IsHandled then
            exit;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11024.
