### ISSUE TITLE
[Change Request] table 179 "Reversal Entry" - procedure CheckPostingDate

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#23509]
Hello, can you please change the procedure CheckPostingDate from local to global ?

```
    procedure CheckPostingDate(PostingDate: Date; Caption: Text; EntryNo: Integer)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckPostingDate(PostingDate, CopyStr(Caption, 1, 50), EntryNo, IsHandled, Rec);
        if IsHandled then
            exit;

        if GenJnlCheckLine.DateNotAllowed(PostingDate) then
            Error(Text001, Caption, EntryNo);
        if PostingDate > MaxPostingDate then
            MaxPostingDate := PostingDate;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11024.
