### ISSUE TITLE
Wrong "Reference Document" in warehouse posting from Sales and Puchase Returns

### ISSUE THREAD

**Issue by DennyHW** [microsoft/ALAppExtensions#23535]
In **codeunit 80 "Sales-Post",** function CreateWhseJnlLine(...)
the "Reference Documents" is set to Posted Return Shipment instead of Posted Return Receipt
![immagine](https://github.com/microsoft/ALAppExtensions/assets/53569676/f74e1846-d88a-4aa8-90e8-27f93c35f969)

In **codeunit 90 "Purch.-Post",** function CreateWhseJnlLine(...)
the "Reference Documents" is set to Posted Return Receipt instead of Posted Return Shipment
![immagine](https://github.com/microsoft/ALAppExtensions/assets/53569676/7cd1270f-449c-4942-bcf5-3290395ce82c)

The values are clearly reversed.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18835.
