### ISSUE TITLE
[Event Request] table 1001 "Job Task" procedure JobLedgEntriesExist()

### ISSUE THREAD

**Issue by michaelarmanno-tnp** [microsoft/ALAppExtensions#23534]
Please can you add the following code/event to the above procedure...

```
local procedure JobLedgEntriesExist(): Boolean
var
    JobLedgEntry: Record "Job Ledger Entry";
begin
    JobLedgEntry.SetCurrentKey("Job No.", "Job Task No.");
    JobLedgEntry.SetRange("Job No.", "Job No.");
    JobLedgEntry.SetRange("Job Task No.", "Job Task No.");
    OnBeforeJobLedgerEntriesExistFindFirst(Rec, JobLedgEntry);  //NEW CODE
    exit(JobLedgEntry.FindFirst());
end;
```

The event publisher should be as follows...

```
[IntegrationEvent(false, false)]
local procedure OnBeforeJobLedgerEntriesExistFindFirst(var JobTask: Record "Job Task"; var JobLedgEntry: Record "Job Ledger Entry")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10889.
