### ISSUE TITLE
[Event Request] table 1002 "Job Task Dimension" procedure OnRename()

### ISSUE THREAD

**Issue by michaelarmanno-tnp** [microsoft/ALAppExtensions#23533]
Please can you add the following code/event to the above procedure...

```
trigger OnRename()
var
    IsHandled: Boolean;                 //NEW CODE
begin
    OnBeforeOnRename(Rec, IsHandled);   //NEW CODE
    if IsHandled then                   //NEW CODE
        exit;                           //NEW CODE

    Error(Text000, TableCaption);
end;
```

The event publisher should be as follows...

```
[IntegrationEvent(false, false)]
local procedure OnBeforeOnRename(var JobTaskDimension: Record "Job Task Dimension"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10889.
