### ISSUE TITLE
Infinite recursion i table 8616 "Config. Package Field", procedure GetUniqueElementName 

### ISSUE THREAD

**Issue by m2mal** [microsoft/ALAppExtensions#23539]
Infinite recursion occurs for the string 'ITI Full VAT Base Amount (LCY)' causing a memory overflow and crash.
Table 8616 "Config. Package Field", procedure GetUniqueElementName

This happens when the length of the parameter is equal to the maximum (here 30 characters), we add a suffix, and then we truncate the entire text to 30 characters - the starting position, to return this value again by calling the same function recursively.

Suggested solution
Shorten the text before incrementing by 1 if the string is maximally long (30 characters here)

**Comment by JesperSchulz** [comment]
That might just be a product defect! Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps). We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
