### ISSUE TITLE
[Event Request] table 249 "VAT Registration Log" - OnBeforeGetAccountRecordRef

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#23547]
Please add a new Publisher Call OnBeforeGetAccountRecordRef in Fct. GetAccountRecordRef of table 249 "VAT Registration Log"

Add local Var. in Fct. GetAccountRecordRef

````

IsHandled: Boolean;
Result: Boolean;

```` 

Add Publisher Call in Fct. GetAccountRecordRef:

````

    begin
+       IsHandled := false;
+       OnBeforeGetAccountRecordRef(Rec, RecordRef, IsHandled, Result);
+       if IsHandled then
+           exit(Result);
        Clear(RecordRef);
        case "Account Type" of

````

Add new Publisher:

````

+    [IntegrationEvent(false, false)]
+    local procedure OnBeforeGetAccountRecordRef(var VATRegistrationLog: Record "VAT Registration Log"; var RecordRef: RecordRef; var IsHandled: Boolean; var Result: Boolean)
+    begin
+    end;


````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10897.
