### ISSUE TITLE
[Request for External] codeunit 7322 "Create Inventory Pick/Movement" - multiple functions to be made global

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#23549]
Can the following functions be changed from local to global so that they can be used to create inventory picks using some custom logic...

CalcInvtAvailability
PickStrictExpirationPosting
UndefinedItemTrkg
CreateTempHandlingSpec
InsertPickOrMoveBinWhseActLine
SynchronizeWhseItemTracking
InsertShelfWhseActivLine
CreateATOPickLine
MakeHeader
MakeLine
FindNextLineNo

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11082.
