### ISSUE TITLE
[Event Request] codeunit 248 "VAT Lookup Ext. Data Hndl" - OnPrepareSOAPRequestBodyOnBeforeSetAccountDetails

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#23543]
Please add a new Publisher Call OnPrepareSOAPRequestBodyOnBeforeSetAccountDetails in Fct. PrepareSOAPRequestBody of codeunit 248 "VAT Lookup Ext. Data Hndl"

Add Publisher Call in Fct. PrepareSOAPRequestBody:

````

            AccountCity := GetField(RecordRef, Customer.FieldName(City));
+           OnPrepareSOAPRequestBodyOnBeforeSetAccountDetails(RecordRef, VATRegistrationLog, AccountName, AccountStreet, AccountPostCode, AccountCity);
            VATRegistrationLog.SetAccountDetails(AccountName, AccountStreet, AccountCity, AccountPostCode);

````

Add new Publisher:

````

+    [IntegrationEvent(false, false)]
+    local procedure OnPrepareSOAPRequestBodyOnBeforeSetAccountDetails(var RecordRef: RecordRef; var VATRegistrationLog: Record "VAT Registration Log"; var AccountName: Text; var AccountStreet: Text; var AccountCity: Text; var AccountPostCode: Text)
+    begin
+    end;


````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10897.
