### ISSUE TITLE
[Event Enhancement Request] Reuse logged Segments

### ISSUE THREAD

**Issue by PajakL** [microsoft/ALAppExtensions#23550]
Hello,

on the segment card, the "Reuse Segment" functionality is lacking events for the purpose of transfering information from the logged segment to the new one. 
![image](https://github.com/microsoft/ALAppExtensions/assets/134365984/f9e9883f-dee4-46ac-8a6b-2a9f2926131a)

Minimum requirement:
The publisher _"local procedure OnAfterReuseLogged(var SegmentHeader: Record "Segment Header")"_ in the segment header table would need an additional parameter for the segment that is reused.
![image](https://github.com/microsoft/ALAppExtensions/assets/134365984/3f1333bb-2c5c-48d6-b29a-b35f137751a7)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10893.
