### ISSUE TITLE
[Event Change Request] codeunit 5944 SignServContractDoc procedure SetInvoicing() event OnBeforeSetInvoicing

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#23555]
Please can you include the following parameters to the OnBeforeSetInvoicing event...

```
HideDialog
InvoiceNow
InvoiceFrom
InvoiceTo
InvoicingStartingPeriod
GoOut

```

The event publisher would be...

```
[IntegrationEvent(false, false)]
local procedure OnBeforeSetInvoicing(var ServiceContractHeader: Record "Service Contract Header"; var IsHandled: Boolean; HideDialog: Boolean; var InvoiceNow: Boolean; var InvoiceFrom: Date; var InvoiceTo: Date; var InvoicingStartingPeriod: Boolean; var GoOut: Boolean)
begin
end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10907.
