### ISSUE TITLE
[Event Request] Table 210 - Job Journal Line - OnBeforeCheckJobInJobNoOnValidate

### ISSUE THREAD

**Issue by cosmo-skol** [microsoft/ALAppExtensions#2356]
Hello AL-Team,
we need a new publisher to skip the default checks of the standard job module:

Trigger: Job No. - OnValidate()

```
[...]
GetJob;
Job.TestBlocked;

// >> NEW
IsHandled := FALSE;
OnBeforeCheckJobInJobNoOnValidate(Rec,xRec,Cust,IsHandled);
IF NOT IsHandled THEN BEGIN
// << NEW
  Job.TESTFIELD("Bill-to Customer No.");
  Cust.GET(Job."Bill-to Customer No.");
  VALIDATE("Job Task No.",'');
// >> NEW
END;
// << NEW

"Customer Price Group" := Job."Customer Price Group";
VALIDATE("Currency Code",Job."Currency Code");
CreateDim(
[...]

```

Publisher definition:
LOCAL [IntegrationEvent] OnBeforeCheckJobInJobNoOnValidate(VAR Rec : Record "Job Journal Line";xRec : Record "Job Journal Line";VAR Cust : Record Customer;VAR IsHandled : Boolean)

Publisher properties:
IncludeSender: FALSE
GlobaVarAccess: FALSE

**Comment by NKarolak** [comment]
Note: created as **OnValidateJobNoOnBeforeCheckJob**
`LOCAL [IntegrationEvent] OnValidateJobNoOnBeforeCheckJob(VAR JobJournalLine : Record "Job Journal Line";xJobJournalLine : Record "Job Journal Line";VAR Customer : Record Customer;VAR IsHandled : Boolean)`
