### ISSUE TITLE
[Event Request] table 5900 "Service Header" procedure Validate() field "Service Order Type"

### ISSUE THREAD

**Issue by michaelarmanno-tnp** [microsoft/ALAppExtensions#23567]
Please can you add the following code/event to the above procedure...

```
trigger OnValidate()
var
    IsHandled: Boolean;         //NEW CODE
begin
    IsHandled := false;         //NEW CODE
    OnValidateServiceOrderTypeOnBeforeCreateDim(Rec, xRec, IsHandled);      //NEW CODE
    if not IsHandled then       //NEW CODE
        CreateDimFromDefaultDim(Rec.FieldNo("Service Order Type"));
end;
```

The event publisher should be as follows...

```
[IntegrationEvent(false, false)]
local procedure OnValidateServiceOrderTypeOnBeforeCreateDim(var ServiceHeader: Record "Service Header"; xServiceHeader: Record "Service Header"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10893.
