### ISSUE TITLE
[Event Request] Table 472 "Job Queue Entry" - OnBeforeCheckErrorMessageWritePermission

### ISSUE THREAD

**Issue by shuyusheng** [microsoft/ALAppExtensions#23574]
Hi, could an event be added to allow for the error message permission check to be skipped? This check causes issues with team member licensed users from activating custom workflows which eventually triggers an job queue entry. Thanks.

```
internal procedure CheckRequiredPermissions()
var
    DummyJobQueueLogEntry: Record "Job Queue Log Entry";
    DummyErrorMessageRegister: Record "Error Message Register";
    DummyErrorMessage: Record "Error Message";
    IsHandled: Boolean;
begin
    if not DummyJobQueueLogEntry.WritePermission() then
        Error(NoPermissionsErr, DummyJobQueueLogEntry.TableName());

    if not DummyErrorMessageRegister.WritePermission() then
        Error(NoPermissionsErr, DummyErrorMessageRegister.TableName());
    
    OnBeforeCheckErrorMessageWritePermission(IsHandled);
    if not IsHandled then
        if not DummyErrorMessage.WritePermission() then
            Error(NoPermissionsErr, DummyErrorMessage.TableName());
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeCheckErrorMessageWritePermission(var IsHandled: Boolean)
begin
end;
```

**Comment by AlexanderYakunin** [comment]
Hello! Can you describe the issue, seems this is a bug to be fixed and we should not add events to skip mandatory checks?

**Comment by darjoo** [comment]
@shuyusheng Why would your team member not have permissions to the "Error Message" or "Error Message Register" tables? Those are given in the entitlements for team member. 
If you skip the check, this will cause problems down the line if the JQ fails which none of us want to deal with. Adding more events so you can "skip" the checks or not add to the tables would not be the way.

**Comment by shuyusheng** [comment]
It seems the team member permissions for error message table was added in Jan 2023, I'll have to check if that change is retrofitted for licenses generated for prior versions of BC. Previous for our on-premise clients this was the only compromise.

**Comment by darjoo** [comment]
I checked back to 20.5 and it is there. I'll close the issue with this and if there's further issues, reopen it.
