### ISSUE TITLE
How to disable code on OnQueryClosePage

### ISSUE THREAD

**Issue by j-wilder** [microsoft/ALAppExtensions#2358]
In NAV 2018 base code was added to OnQueryClosePage of Page 50 Purchase Order (in other similar pages as well) to pop up a message every time you leave the screen.  This is bizarre.  This code was bettered a bit in BC so it only pops up a message if the order is <> released.  In AL how can I stop this behavior?  (obviously in C/AL I could comment out the code).  If I add my own OnQueryClosePage trigger in AL it doesn't overwrite the existing base trigger but just adds to it.

I really wish there were an option when creating a page extension trigger to be OnBefore, OnAfter or InsteadOf.  For example something like this:
trigger InsteadOf OnQueryClosePage(CloseAction : Action) : Boolean;
or
trigger OnBefore OnQueryClosePage(CloseAction : Action) : Boolean;

I understand this becomes complicated when other extensions are involved but still looking for some kind of solution in this area.

**Comment by RomanZanizdra** [comment]
Hi Jason.
You need to go to the My Notifications page, find "Warn about unposted documents." notification and disable it. In that case you will not receive notifications about unposted documents at all or you can setup conditions for more precise tuning.
