### ISSUE TITLE
[Event request] Adding OnAfterUpdatePrePaymentAmounts integration event

### ISSUE THREAD

**Issue by daniel-williams-fenwick** [microsoft/ALAppExtensions#23599]
Hi Microsoft AL Development Team,

Could you add the following event to the table 39 "Purchase Line"?

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdatePrePaymentAmounts(var PurchaseLine: Record "Purchase Line")
    begin
    end;
```

![image](https://github.com/microsoft/ALAppExtensions/assets/134581763/9c7b4260-6162-422b-ba94-dd089ac1017d)

Thank you.

Kind regards,
Daniel Williams

**Comment by daniel-williams-fenwick** [comment]
The UpdatePrePaymentAmounts function has already has a similar event in table 37 "Sales Line".

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10952.
