### ISSUE TITLE
[Event Request] CodeUnit 5760 "Whse.-Post Receipt" 

### ISSUE THREAD

**Issue by Gwrsky** [microsoft/ALAppExtensions#23595]
Hello,
Could you please add the following events into PostSourceDocument procedure in CU5760?

     DATABASE::"Transfer Line":
                    begin
                      //START NEW CODE
                      OnPostSourceDocumentOnBeforePostTransferHeader(TransferHeader, WhseRcptHeader, SuppressCommit, 
                      CounterSourceDocOK, IsHandled);
                      if not IsHandled then begin
                      //END NEW CODE
                        if HideValidationDialog then
                            TransferPostReceipt.SetHideValidationDialog(HideValidationDialog);
                        TransferPostReceipt.SetWhseRcptHeader(WhseRcptHeader);
                        TransferPostReceipt.SetSuppressCommit(SuppressCommit or PreviewMode);
                        TransferPostReceipt.SetPreviewMode(PreviewMode);
                        TransferPostReceipt.SetCalledBy(Codeunit::"Whse.-Post Receipt");
                        if PreviewMode then
                            PostSourceTransferDocument(TransferPostReceipt)
                        else
                            case WhseSetup."Receipt Posting Policy" of
                                WhseSetup."Receipt Posting Policy"::"Posting errors are not processed":
                                    PostTransferErrorsNotProcessed(TransferPostReceipt);
                                WhseSetup."Receipt Posting Policy"::"Stop and show the first posting error":
                                    PostSourceTransferDocument(TransferPostReceipt);
                            end;
                        Clear(TransferPostReceipt);
                        //START NEW CODE
                        end;
                        OnPostSourceDocumentOnAfterTransferHeader(TransferHeader)
                        //END NEW CODE
                    end;

    [IntegrationEvent(false, false)]
    local procedure OnPostSourceDocumentOnBeforePostTransferHeader(var TransferHeader: Record "TransferHeader"; 
    WhseRcptHeader: Record "Warehouse Receipt Header"; SuppressCommit: Boolean; var CounterSourceDocOK: Integer; var 
    IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnPostSourceDocumentOnAfterPostTransferHeader(TransferHeader: Record "TransferHeader")
    begin
    end;

There're events for Sales and Purchase Source Types, but not for Transfer

**Comment by dannoe** [comment]
If you don't need ``SuppressCommit`` you could use ``OnBeforePostSourceDocument``.

**Comment by Gwrsky** [comment]
Hi
Unfortunately i cannot use that event, because i need the standard code in PostSourceDocument for Sales and Purchases, but for Transfer Order i need to use OnPostSourceDocumentOnBeforePostTransferHeader and return IsHandled value as true, so it doesn't process standard code .

I Could copy standard, use the Event you suggested and return isHandled=true, but then there're 4 publishers that will be gone, and i need that aswell for later development.

**Comment by Gwrsky** [comment]
Hi
Unfortunately i cannot use that event, because i need the standard code in PostSourceDocument for Sales and Purchases, but for Transfer Order i need to use OnPostSourceDocumentOnBeforePostTransferHeader and return IsHandled value as true, so it doesn't process standard code .

I Could copy standard, use the Event you suggested and return isHandled=true, but then there're 4 publishers that will be gone, and i need that aswell for later development.

**Comment by dannoe** [comment]
The event is called in a loop for every line, so you can check for the "Source Type" = Transfer Line (as in ``PostSourceDocument``).
Then you can set IsHandled to true and execute your own transfer line posting logic. The other cases (WhseRcptLine."Source Type" <> Transfer Line) will still be executed.

```al
[EventSubscriber(ObjectType::Codeunit, Codeunit::"Whse.-Post Receipt", OnBeforePostSourceDocument, '', false, false)]
    local procedure OnBeforePostSourceDocument(var WhseRcptLine: Record "Warehouse Receipt Line"; PurchaseHeader: Record "Purchase Header"; SalesHeader: Record "Sales Header"; TransferHeader: Record "Transfer Header"; var CounterSourceDocOK: Integer; HideValidationDialog: Boolean; var IsHandled: Boolean);
    begin
      if WhseRcptLine."Source Type" = Database::"Transfer Line" then begin
         IsHandled := true;

         // your special code for transfer lines

      end;
    end;
```

But you can keep the request open, I just wanted to help so you don't have to wait for the event.
PS: The mentioned "TransferHeader" variable in your event request does not exist in this method.

**Comment by Gwrsky** [comment]
Thank you for help!
I'll leave the request open, so the events are consistent through standard :D

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10952.
