### ISSUE TITLE
[Event Request] ccodeunit 8894 "Email Account" - New Event OnBeforeConvertEmailAddress

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#23590]
Hi Team,

we are trying to implement a Send-To Group Feature in Mail Editor (like in Outlook -> Add Groupname as Recipient), but the email address validation is blocking this scenario as the group is not a valid email address (e.g. accounting-group [contains n email-addresses]). Is it possible to introduce an event to handle email-address-validation?

My proposal in codeunit 8889 "Email Account Impl.":

``` AL
[TryFunction]
local procedure ConvertEmailAddress(var EmailAddress: Text)
var
    MailAddress: DotNet MailAddress;
    EmailAccount: Codeunit "Email Account";
    IsHandled: Boolean; // New Var
begin
    // New Event
    EmailAccount.OnBeforeConvertEmailAddress(EmailAddress,IsHandled);
    if IsHandled then 
        exit;
    // --
        
    // throws an exception if the address is invalid
    MailAddress := MailAddress.MailAddress(EmailAddress);

    EmailAddress := MailAddress.Address;
end;
```

Event definition in public codeunit 8894 "Email Account"

``` AL
[IntegrationEvent(false, false)]
internal procedure OnBeforeConvertEmailAddress(var EmailAddress: Text; var IsHandled: Boolean)
begin
end;
```

Thanks,
Christian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11004.
