### ISSUE TITLE
[Event change request] OnBeforeReleaseSalesDoc

### ISSUE THREAD

**Issue by PeterConijn** [microsoft/ALAppExtensions#23607]
In codeunit 414 - Release Sales Document, there is the following code:

``` AL
    OnBeforeReleaseSalesDoc(SalesHeader, PreviewMode, IsHandled, SkipCheckReleaseRestrictions);
    if IsHandled then
        exit;
    if not (PreviewMode or SkipCheckReleaseRestrictions) then
        CheckSalesReleaseRestrictions();
```

The event publisher signature, however, sends the final argument, SkipCheckReleaseRestrictions, by value instead of by reference, so it can never be changed prior to calling the CheckSalesReleaseRestricions() procedure, making the argument's inclusion mostly moot. 

``` AL
[IntegrationEvent(false, false)]
local procedure OnBeforeReleaseSalesDoc(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean; var IsHandled: Boolean; SkipCheckReleaseRestrictions: Boolean)
```

Request that the event publisher signature be changed to pass the SkipCheckReleaseRestrictions argument by reference:

``` AL
[IntegrationEvent(false, false)]
local procedure OnBeforeReleaseSalesDoc(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean; var IsHandled: Boolean; var SkipCheckReleaseRestrictions: Boolean)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10963.
