### ISSUE TITLE
[Event change request] Adding additional variables to OnBeforeCheckPrepmtAmounts integration event

### ISSUE THREAD

**Issue by daniel-williams-fenwick** [microsoft/ALAppExtensions#23601]
Hi Microsoft AL Development Team,

Could you please add these additional variables to integration event OnBeforeCheckPrepmtAmounts in table 37 "Sales Line"

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckPrepmtAmounts(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line"; CurrentFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;
```

![image](https://github.com/microsoft/ALAppExtensions/assets/134581763/2d8e9d6d-474f-485b-a3ea-f3e457c4f525)

We already have access to these variables OnBeforeCheckPrepmtAmounts in table 39 "Purchase Line"

Thank you,
Daniel Williams

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10952.
