### ISSUE TITLE
[Access Request] report 7391 "Whse. Get Bin Content" - InsertTempTrackingSpecification

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23618]
Could you please change the access scope of the following procedure to protected?
```al
//+Change
//-local procedure InsertTempTrackingSpecification(WarehouseEntry: Record "Warehouse Entry"; QtyOnBin: Decimal; var TempTrackingSpecification: Record "Tracking Specification" temporary)
protected procedure InsertTempTrackingSpecification(WarehouseEntry: Record "Warehouse Entry"; QtyOnBin: Decimal; var TempTrackingSpecification: Record "Tracking Specification" temporary)
//-Change
begin
    ...
end;
```

Original Issue for Reference: https://github.com/microsoft/ALAppExtensions/issues/20049

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11018.
