### ISSUE TITLE
[Event Request] * Line - Price OnBeforeSetPrice

### ISSUE THREAD

**Issue by chrischbo** [microsoft/ALAppExtensions#23610]
Hi,

could you please a the OnBeforeSetPrice Publisher to all Line - Price codeunits. We're missing them in
Codeunit::"Requition Line - Price"
Codeunit::"Job Planning Line - Price"
Codeunit::"Std. Item Jnl. Line - Price"
Codeunit::"Res. Journal Line - Price"

Signature should be the same as in the others:
[IntegrationEvent(false, false)]
    local procedure OnBeforeSetPrice(var XXXLine: Record "XXX Line"; PriceListLine: Record "Price List Line"; AmountType: Enum "Price Amount Type"; var IsHandled: Boolean; CurrPriceType: Enum "Price Type")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10963.
