### ISSUE TITLE
[Event Parameter Request] page 6510 "Item Tracking Lines" - OnBeforeSetWarehouseControls

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#23614]
Many, many years ago somebody requested untested https://github.com/microsoft/ALAppExtensions/issues/13457 and used the wrong variable in 
OnBeforeSetWarehouseControls(Rec, IsHandled); 
which should have been 
OnBeforeSetWarehouseControls(TrackingSpecification, IsHandled);
Has been like that since 18.04.

Alas that somebody is me and now our first heavy item tracking prod->sales->shipment->pick customer wants to test functionality that does work in NAV2013 but does not anymore in 22.01.
Could you please add the parameter TrackingSpecification to the event OnBeforeSetWarehouseControls? It would be very much appreciated. I suppose you don't want to make any changes by just replacing the calling variable but it makes it a bit difficult for the event procedure variable naming. I tried my best.

    local procedure SetWarehouseControls(TrackingSpecification: Record "Tracking Specification")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        //OnBeforeSetWarehouseControls(Rec, IsHandled); Event 22.01.o
        OnBeforeSetWarehouseControls(Rec, IsHandled, TrackingSpecification); //Event 22.01.n
        if IsHandled then
            exit;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetWarehouseControls(TrackingSpecification: Record "Tracking Specification"; var IsHandled: Boolean; var NewTrackingSpecification: Record "Tracking Specification")
    begin
        //Event22.01 NewTrackingSpecification
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10963.
