### ISSUE TITLE
[Event Change Request] report 7391 "Whse. Get Bin Content" OnInsertItemJournalLineOnBeforeValidateEntryType

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23615]
Could you please incude the sender in the event `OnInsertItemJournalLineOnBeforeValidateEntryType` as requested here:
https://github.com/microsoft/ALAppExtensions/issues/19700

```al
//+Change
//-[IntegrationEvent(false, false)]
[IntegrationEvent(true, false)]
//+-Change
local procedure OnInsertItemJournalLineOnBeforeValidateEntryType(var ItemJournalLine: Record "Item Journal Line"; var BinContent: Record "Bin Content"; var ItemLedgerEntryType: Enum "Item Ledger Entry Type"; ItemJournalTemplate: Record "Item Journal Template"; ItemJournalBatch: Record "Item Journal Batch")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10963.
