### ISSUE TITLE
[Event Change Reqeuest] report 7391 "Whse. Get Bin Content" OnInsertItemJournalLineOnBeforeValidateNewLocationCode

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23616]
Could you please incude the sender in the event `OnInsertItemJournalLineOnBeforeValidateNewLocationCode` as requested here:
https://github.com/microsoft/ALAppExtensions/issues/19701

```al
//+Change
//-[IntegrationEvent(false, false)]
[IntegrationEvent(true, false)]
//-Change
local procedure OnInsertItemJournalLineOnBeforeValidateNewLocationCode(var ItemJournalLine: Record "Item Journal Line"; var BinContent: Record "Bin Content"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10963.
