### ISSUE TITLE
[Event Request] table 39 "Purchase Line" - OnBlanketOrderIsRelatedOnAfterSetLoadFields

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#23624]
Please add a new Publisher Call OnBlanketOrderIsRelatedOnAfterSetLoadFields in Fct. BlanketOrderIsRelated of table 39 "Purchase Line"

Add Publisher Call in Fct. BlanketOrderIsRelated:

````

        BlanketOrderPurchaseLine.SetLoadFields("Direct Unit Cost", "Line Discount %");
+       OnBlanketOrderIsRelatedOnAfterSetLoadFields(BlanketOrderPurchaseLine);
        if BlanketOrderPurchaseLine.Get("Document Type"::"Blanket Order", "Blanket Order No.", "Blanket Order Line No.") then

````

Add new Publisher:

````

+   [IntegrationEvent(false,false)]
+   local procedure OnBlanketOrderIsRelatedOnAfterSetLoadFields(var BlanketOrderPurchaseLine: Record "Purchase Line")
+   begin
+   end;

````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10963.
