### ISSUE TITLE
[Enum Request] Table 11000006 (CBG Statement Line Add. Info.) for Field No. 6 (Information Type)

### ISSUE THREAD

**Issue by AnkithShah** [microsoft/ALAppExtensions#2362]
Please implement the field "Information Type" in Tab11000006 "CBG Statement Line Add. Info." as Enum.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
