### ISSUE TITLE
[Request for external] Remove OnPrem scope requests for external not in major 22x

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#23639]
We requested to remove the OnPrem scope from functions which do not contain OnPrem specific code.
Please have a look at the following requests for external. They are approved but we do not see any code changes in the major 22.1. 

#22081
#22084
#22087
#22198
#22129

**Comment by AlexanderYakunin** [comment]
Sorry, we never do that for released versions, we can only do external requests for next major.
