### ISSUE TITLE
[Event Parameter Request] Codeunit 12 - procedure InsertTempVATEntry - publisher OnInsertTempVATEntryBeforeInsert

### ISSUE THREAD

**Issue by stephanweidmann** [microsoft/ALAppExtensions#23637]
Please add VATEntry to the OnInsertTempVATEntryOnBeforeInsert - Publisher.
Under specific circumstances, i want to keep the vat entry closed.

`    local procedure InsertTempVATEntry(GenJnlLine: Record "Gen. Journal Line"; VATEntry: Record "VAT Entry"; var TempVATEntryNo: Integer; var TempVATEntry: Record "VAT Entry" temporary)
    begin
        TempVATEntry := VATEntry;
        with TempVATEntry do begin
            "Entry No." := TempVATEntryNo;
            TempVATEntryNo := TempVATEntryNo + 1;
            "Closed by Entry No." := 0;
            Closed := false;
            CopyAmountsFromVATEntry(VATEntry, true);
            "Posting Date" := GenJnlLine."Posting Date";
            "Document Date" := GenJnlLine."Document Date";
            "VAT Reporting Date" := GenJnlLine."VAT Reporting Date";
            "Document No." := GenJnlLine."Document No.";
            "User ID" := CopyStr(UserId(), 1, MaxStrLen("User ID"));
            "Transaction No." := NextTransactionNo;
            "G/L Acc. No." := '';
            OnInsertTempVATEntryOnBeforeInsert(TempVATEntry, GenJnlLine, VATEntry);
            Insert();
        end;
    end;`
    
        [IntegrationEvent(false, false)]
    local procedure OnInsertTempVATEntryOnBeforeInsert(var VATEntry: Record "VAT Entry"; GenJournalLine: Record "Gen. Journal Line";SourceVATEntry: Record "VAT Entry")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10998.
