### ISSUE TITLE
UpdateQtyPickedForOptionalWhsePick issue

### ISSUE THREAD

**Issue by simonezaganelli** [microsoft/ALAppExtensions#23632]
The procedure UpdateQtyPickedForOptionalWhsePick in codeunit 22 is incorrect: it is called with parameter 2 equal to ' QtyToPost + "Act. Consumption (Qty)" ', this value is expressed in the base unit of measure, but this value is used to set the "Qty. Picked" on the "Prod. Order Comp." table. 

The validation of the latter leads to a wrong conversion to set the field "Qty. Picked (Base)". In non-trivial situations ("Qty. per unit of measure" <> 1) this leads to an error.

Our situation is: item with Base unit of Measure = 'Kg', consumption set with 'g' uom, posted a value like 1,5g

![image](https://github.com/microsoft/ALAppExtensions/assets/134918377/b60b1e71-f22b-40dc-9c82-9dba3d9d3317)

![image](https://github.com/microsoft/ALAppExtensions/assets/134918377/4588f8a2-81d5-46c2-94f3-46b91d3b173c)

![image](https://github.com/microsoft/ALAppExtensions/assets/134918377/596aff94-fb87-40e0-bb08-e2c42789d02a)

**Comment by aldobriansky** [comment]
This has been fixed recently.
