### ISSUE TITLE
[Event Request] Codeunit 12 - PostDtldVendVATAdjustment - New Events

### ISSUE THREAD

**Issue by stephanweidmann** [microsoft/ALAppExtensions#23638]
Please implement publishers with handled patterns:
If new events with "includeSender" = true are not possible, please implement the following changes from Variant B)

(Variant A)
`local procedure PostDtldVendVATAdjustment(GenJnlLine: Record "Gen. Journal Line"; DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; OriginalTransactionNo: Integer)
    var
        VATPostingSetup: Record "VAT Posting Setup";
        TaxJurisdiction: Record "Tax Jurisdiction";
ishandled ; Boolean; //New
    begin
        with DtldCVLedgEntryBuf do begin
            FindVATEntry(VATEntry, OriginalTransactionNo);
            OnPostDtldVendVATAdjustmentOnAfterFindVATEntry(DtldCVLedgEntryBuf, VATEntry);

            case VATPostingSetup."VAT Calculation Type" of
                VATPostingSetup."VAT Calculation Type"::"Normal VAT",
                VATPostingSetup."VAT Calculation Type"::"Full VAT":
                    begin
                        VATPostingSetup.Get("VAT Bus. Posting Group", "VAT Prod. Posting Group");
                        VATPostingSetup.TestField("VAT Calculation Type", VATEntry."VAT Calculation Type");
                        OnBeforeCreateGLEntryNormalFullVATInPostDtldVendVATAdjustment((DtldCVLedgEntryBuf,VATEntry,GenJnlLine,IsHandled); //New
                        if not isHandled then // new
                        CreateGLEntry(
                          GenJnlLine, VATPostingSetup.GetPurchAccount(false), -"Amount (LCY)", -"Additional-Currency Amount", false);
                    end;
                VATPostingSetup."VAT Calculation Type"::"Reverse Charge VAT":
                    begin
                        VATPostingSetup.Get("VAT Bus. Posting Group", "VAT Prod. Posting Group");
                        VATPostingSetup.TestField("VAT Calculation Type", VATEntry."VAT Calculation Type");
                        OnBeforeCreateGLEntryReverseChargeVATInPostDtldVendVATAdjustment((DtldCVLedgEntryBuf,VATEntry,GenJnlLine,IsHandled); //New
                        if not isHandled then begin // new
                        CreateGLEntry(
                          GenJnlLine, VATPostingSetup.GetPurchAccount(false), -"Amount (LCY)", -"Additional-Currency Amount", false);
                        CreateGLEntry(
                          GenJnlLine, VATPostingSetup.GetRevChargeAccount(false), "Amount (LCY)", "Additional-Currency Amount", false);
                         end; // new
                    end;
                VATPostingSetup."VAT Calculation Type"::"Sales Tax":
                    begin
                        TaxJurisdiction.Get("Tax Jurisdiction Code");
OnBeforeCreateGLEntrySalesTaxInPostDtldVendVATAdjustment((DtldCVLedgEntryBuf,VATEntry,GenJnlLine,IsHandled); //New
                        if not isHandled then // new
                          if "Use Tax" then begin
                              CreateGLEntry(
                                GenJnlLine, TaxJurisdiction.GetPurchAccount(false), -"Amount (LCY)", -"Additional-Currency Amount", false);
                              CreateGLEntry(
                                GenJnlLine, TaxJurisdiction.GetRevChargeAccount(false), "Amount (LCY)", "Additional-Currency Amount", false);
                          end else
                              CreateGLEntry(
                                GenJnlLine, TaxJurisdiction.GetPurchAccount(false), -"Amount (LCY)", -"Additional-Currency Amount", false);
                    end;
            end;
        end;
        OnAfterPostDtldVendVATAdjustment(GenJnlLine, VATPostingSetup, DtldCVLedgEntryBuf, VATEntry);
    end;
    
        [IntegrationEvent(true, false)]
    OnBeforeCreateGLEntryNormalFullVATInPostDtldVendVATAdjustment(DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer";VATEntry; REcord "VAT Entry";GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
begin
end;

    [IntegrationEvent(true, false)]
    OnBeforeCreateGLEntryReverseChargeVATInPostDtldVendVATAdjustment(DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer";VATEntry; REcord "VAT Entry";GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
begin
end;
    [IntegrationEvent(true, false)]
    OnBeforeCreateGLEntrySalesTaxInPostDtldVendVATAdjustment(DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer";VATEntry; REcord "VAT Entry";GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
begin
end;
`

Variant B
`-> CreateGLEntry(GenJnlLine, VATPostingSetup.GetPurchAccount(false), -"Amount (LCY)", -"Additional-Currency Amount", false)

to
AccountNo := , VATPostingSetup.GetPurchAccount(false)
OnAfterFoundAccountNoNormalFullVATInPostDtldVendVATAdjustment(DtldCVLedgEntryBuf,VATEntry,Accountno) with the possibliity to change the account no.
CreateGLEntry(GenJnlLine, AccountNo, -"Amount (LCY)", -"Additional-Currency Amount", false);`

    [IntegrationEvent(true, false)]
    OnAfterFoundAccountNoNormalFullVATInPostDtldVendVATAdjustment(DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer";VATEntry; REcord "VAT Entry"; var AccountNo: Code[20)
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10998.
