### ISSUE TITLE
[Event Request] codeunit 99000854 "Inventory Profile Offsetting" - OnBeforeCheckScheduleIn

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#23640]
I have created evenmt procedure OnBeforeCheckScheduleIn in the same way as the existing OnBeforeCheckScheduleOut so the calling variables (SupplyInvtProfile and TempSKU) are not equal to the event parameters

    local procedure CheckScheduleIn(var SupplyInvtProfile: Record "Inventory Profile"; TargetDate: Date; var PossibleDate: Date; LimitedHorizon: Boolean) Result: Boolean
    var
        IsHandled: Boolean;
    begin
        //Event22.01.ns
        OnBeforeCheckScheduleIn(SupplyInvtProfile, TempSKU, TargetDate, PossibleDate, LimitedHorizon, Result, IsHandled);
        if IsHandled then
            exit(Result);
        //Event22.01.ne

        if SupplyInvtProfile."Planning Flexibility" <> SupplyInvtProfile."Planning Flexibility"::Unlimited then
            exit(false);

        if LimitedHorizon and not AllowScheduleIn(SupplyInvtProfile, TargetDate) then
            PossibleDate := SupplyInvtProfile."Due Date"
        else
            PossibleDate := TargetDate;

        exit(TargetDate = PossibleDate);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckScheduleIn(var InventoryProfile: Record "Inventory Profile"; var TempStockkeepingUnit: Record "Stockkeeping Unit" temporary; TargetDate: date; var PossibleDate: Date; LimitedHorizon: Boolean; var Result: Boolean; var IsHandled: Boolean)
    begin
        //Event22.01
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11004.
