### ISSUE TITLE
[Event Request] Report 12173 "Issued Cust Bills Floppy"

### ISSUE THREAD

**Issue by MicheleFarchetto** [microsoft/ALAppExtensions#23648]
Please add the following Events in Procedures as in the attached file:
- OnRECORD14OnAfterAssignOutText
- OnRECORD20OnAfterAssignOutText
- OnRECORD30OnAfterAssignOutText
- OnRECORD40OnAfterAssignOutText
- OnRECORD51OnAfterAssignOutText
- OnRECORD70OnAfterAssignOutText

Attached the file with the changes i think that could be right.
Thanks for your time.

[Report 12173 Issued Cust Bills Floppy.txt](https://github.com/microsoft/ALAppExtensions/files/11610472/Report.12173.Issued.Cust.Bills.Floppy.txt)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10998.
