### ISSUE TITLE
[Event Request]s in Table Bin Content 

### ISSUE THREAD

**Issue by frobiii** [microsoft/ALAppExtensions#23645]
In Table Bin Content there where a few global procedures with publishers where a filteres record is passed / the record itself which calls the procedure is filtered, but the publisher is using call by value so you do not have any filter access.

Can you please update the publisher, that "Rec" will be passed call by reference.
Thank you.

Example:
![image](https://github.com/microsoft/ALAppExtensions/assets/46748244/f5e49ee3-348c-4bbd-a4c0-5139155f3f7a)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10998.
