### ISSUE TITLE
[Event Parameter Request] page 6510 "Item Tracking Lines" - OnBeforeAssignNewPackageNo

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#23649]
New event parameter SourceTrackingSpecification

    local procedure AssignNewPackageNo()
    var
        InventorySetup: Record "Inventory Setup";
        IsHandled: Boolean;
    begin
        //OnBeforeAssignNewPackageNo(Rec, IsHandled); Event22.01.o
        OnBeforeAssignNewPackageNo(Rec, IsHandled, SourceTrackingSpecification); //Event22.01.n
        if IsHandled then
            exit;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssignNewPackageNo(var TrackingSpecification: Record "Tracking Specification"; var IsHandled: Boolean; var SourceTrackingSpecification: Record "Tracking Specification")
    begin
        //Event22.01 Parameter SourceTrackingSpecification
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10998.
