### ISSUE TITLE
[Extensibility Bug] External Events - Only if not preview.

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23646]
All External Events that are triggerd from posting routines should only call the external event if this event is not called by preview mode.

https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/ExternalEvents/app/src/APExternalEvents.Codeunit.al

**Comment by AndersLarsenMicrosoft** [comment]
it should be fixed by hotfix in 22.2

**Comment by JakovljevicDusan** [comment]
Closing, at it is fixed.
