### ISSUE TITLE
Direct Transfer Header Fields

### ISSUE THREAD

**Issue by yildiz-ozdemir** [microsoft/ALAppExtensions#23643]
Hello,

"Direct Trans. Header" (5856) table does not include "Shipping Agent Code" and "Shipping Agent Service Code" fields.
Could you add the relevant fields and transfer to data from Transfer Header ? 

Thank you.

**Comment by AlexanderYakunin** [comment]
Direct Transfer have not bee intended for real logistics, but just for logical reclassification of good without using logistics, so why do you need shipping fields here? Should you use regular transfer order in this case?

**Comment by yildiz-ozdemir** [comment]
Hi, 
We need these fields for the e-shipping module. Some of our customers want to use real logistics through this page
If you cannot add these fields in terms of operation, I must add as extension fields.

**Comment by AlexanderYakunin** [comment]
In my opinion this page should not be used for real logistics, but this is your decision. Yes, we are not going to add fields based on this request, please create extension with new fields if you need this.
