### ISSUE TITLE
[Event Parameter Request]  table 303 "Finance Charge Memo Line" - OnCalcFinChrgOnAfterFinChrgTermsInterestCalculationMethodCase

### ISSUE THREAD

**Issue by UshakovIlya** [microsoft/ALAppExtensions#23654]
Please, add "Rec" as a new paramether to the OnCalcFinChrgOnAfterFinChrgTermsInterestCalculationMethodCase event in CalcFinChrg function

Old:

local procedure CalcFinChrg()
    var
...
begin
...
        OnCalcFinChrgOnAfterFinChrgTermsInterestCalculationMethodCase(FinChrgMemoLine, FinChrgTerms, FinChrgMemoHeader);
...
end;

[IntegrationEvent(false, false)]
    local procedure OnCalcFinChrgOnAfterFinChrgTermsInterestCalculationMethodCase(var FinanceChargeMemoLine: Record "Finance Charge Memo Line"; FinanceChargeTerms: Record "Finance Charge Terms"; FinanceChargeMemoHeader: Record "Finance Charge Memo Header")
    begin
    end;

New:

local procedure CalcFinChrg()
    var
...
begin
...
        OnCalcFinChrgOnAfterFinChrgTermsInterestCalculationMethodCase(Rec, FinChrgMemoLine, FinChrgTerms, FinChrgMemoHeader);
...
end;

[IntegrationEvent(false, false)]
    local procedure OnCalcFinChrgOnAfterFinChrgTermsInterestCalculationMethodCase(var Rec: Record "Finance Charge Memo Line"; var FinanceChargeMemoLine: Record "Finance Charge Memo Line"; FinanceChargeTerms: Record "Finance Charge Terms"; FinanceChargeMemoHeader: Record "Finance Charge Memo Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10998.
