### ISSUE TITLE
[Request for External] codeunit 99000854 "Inventory Profile Offsetting" - multiple procedures

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#23658]
I'm implementing a new type of Reordering Policy and so need to amend the "Inventory Profile Offsetting" codeunit to handle this.  I would like the scope for the following procedures changed from local to global so that I can re-use the procedures.  I have tried replicating the needed procedures (not ideal) but still can't achieve what I need to do because I can't set/use some global variables like FutureSupplyWithinLeadtime, OverflowLevel, DampenerQty etc...

Please can you change the following procedures from local to global...

```
CreateDemand
InitSupply
CreateSupplyForward
CalcOrderQty
CalcReorderQty
CalcMaximumReorderQty
ScheduleForward
MaintainPlanningLine
SumUpProjectedSupply
DecreaseQty
CanDecreaseSupply
CheckNewOverflow
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11018.
