### ISSUE TITLE
[Event Change Request] report 5706 "Create Stockkeeping Unit" OnBeforeCreateSKU

### ISSUE THREAD

**Issue by jhoek** [microsoft/ALAppExtensions#23653]
Our code subscribes to the OnBeforeCreateSKU event in report 5706. 

The logic in our event subscriber depends on the chosen SKU Creation Method (global variable SKUCreationMethod), but we cannot find a way to access its value. Would you please consider adding it as an addittional parameter in the OnBeforeCreateSKU event publisher? 

As far as we can see, adding this parameter would not break any existing subscribers?

[Note to self: BCD-1278]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 10998.
