### ISSUE TITLE
[Event Request] codeunit 2624 "Stat. Acc. Jnl. Line Post" add OnBeforeStatisticalLedgerEntryInsert event

### ISSUE THREAD

**Issue by ekesteloot** [microsoft/ALAppExtensions#23668]
codeunit 2624 "Stat. Acc. Jnl. Line Post" in the Statistical Accounts extension

Original Code:

    internal procedure PostLine(var StatisticalAccJournalLine: Record "Statistical Acc. Journal Line"; var NextEntryNo: Integer; TransactionNumber: Integer)
    var
        StatisticalLedgerEntry: Record "Statistical Ledger Entry";
    begin
        StatisticalLedgerEntry."Entry No." := NextEntryNo;
        NextEntryNo += 1;
        StatisticalLedgerEntry."Transaction No." := TransactionNumber;
        TransferStatisticalAccJournalLineTo(StatisticalAccJournalLine, StatisticalLedgerEntry);
        StatisticalLedgerEntry.Insert(true);
    end;

Please add an OnBeforeStatisticalLedgerEntryInsert event:

    internal procedure PostLine(var StatisticalAccJournalLine: Record "Statistical Acc. Journal Line"; var NextEntryNo: Integer; TransactionNumber: Integer)
    var
        StatisticalLedgerEntry: Record "Statistical Ledger Entry";

        IsHandled: Boolean;
    begin
        StatisticalLedgerEntry."Entry No." := NextEntryNo;
        NextEntryNo += 1;
        StatisticalLedgerEntry."Transaction No." := TransactionNumber;
        TransferStatisticalAccJournalLineTo(StatisticalAccJournalLine, StatisticalLedgerEntry);

        OnBeforeStatisticalLedgerEntryInsert(StatisticalAccJournalLine, StatisticalLedgerEntry, NextEntryNo, TransactionNumber, IsHandled);
        if IsHandled then
            exit;

        StatisticalLedgerEntry.Insert(true);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeStatisticalLedgerEntryInsert(var StatisticalAccJournalLine: Record "Statistical Acc. Journal Line"; var StatisticalLedgerEntry: Record "Statistical Ledger Entry"; var NextEntryNo: Integer; TransactionNumber: Integer; var IsHandled: Boolean)
    begin
    end;

**Comment by RSMNishant** [comment]
Please add event 'OnBeforeInsertStatisticalLedgerEntry' in next release or in a fix.

**Comment by nikolakukrika** [comment]
Why does this event need to be handled? 
I dislike the part that we can skip inserting the line. What is the alternative for skipping the line?
Can the error be thrown so the posting of the line is skipped?

**Comment by nikolakukrika** [comment]
Please reactivate the issue if needed again and provide the justification on why do you need to skip the inserting the line during the posting.
