### ISSUE TITLE
[Function Expose] Codeunit 130401 AddTestCodeunits FunctionVisibility External

### ISSUE THREAD

**Issue by Schnieringer** [microsoft/ALAppExtensions#2366]
Hello,
it would be great if the function AddTestCodeunits in the Codeunit 130401 "CAL Test Management" would be set to External (FunctionVisibility)... then we would have the possibility to automatically create our own test suite with lines when installing a test app.

Thanks

**Comment by StanPesotskiy** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
