### ISSUE TITLE
[Event Change Request] codeunit 9000854 "Inventory Profile Offsetting" event OnBeforeCommonBalancing

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#23663]
Can you please add the following global variables as var parameters to the above event...

```
NewSupplyHasTakenOver
NeedOfPublishSurplus
FutureSupplyWithinLeadtime
OverflowLevel 

```
The publisher would then be as follows...

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCommonBalancing(var TempSKU: Record "Stockkeeping Unit" temporary; var DemandInvtProfile: Record "Inventory Profile"; var SupplyInvtProfile: Record "Inventory Profile"; PlanningStartDate: Date; ToDate: Date; var NewSupplyHasTakenOver: Boolean; var NeedOfPublishSurplus: Boolean; var FutureSupplyWithinLeadtime: Decimal; var OverflowLevel: Decimal)
    begin
    end;

```
I would like to potentially create a new supply entry so would need to update these global variables

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11004.
