### ISSUE TITLE
[Event] page 7016 "Sales Price List" - Event in OnQueryClosePage

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#23664]
To skip the check in the OnQueryClosePage we need a new eventpublisher:
 ``` diff
 trigger OnQueryClosePage(CloseAction: Action): Boolean;
 var
     PriceListManagement: Codeunit "Price List Management";
+     IsHandled: Boolean;
+     Result: Boolean;
 begin
+     IsHandled := false;
+     OnQueryClosePageOnBeforeDraftLineCheck(Rec, Result, IsHandled);
+     if IsHandled then
+         exit(Result);
     if Rec.Find() then
         if Rec.HasDraftLines() then begin
             PriceListManagement.SendVerifyLinesNotification(Rec);
             exit(false);
         end;
     exit(true)
 end;
 ```
  
 Event publisher signature:
 
 ```
 [IntegrationEvent(false, false)]
 local procedure OnQueryClosePageOnBeforeDraftLineCheck(PriceListHeader: Record "Price List Header"; var Result: Boolean; var IsHandled: Boolean)
 begin
 end;
 ```

**Comment by pri-kise** [comment]
Could you please specify why you need this event there?
@JesperSchulz could you check out this issue.
I think we have open PR on BaseApp Pilot for this notification and this check.

**Comment by dannoe** [comment]
We are implementing a workflow system for releasing/accepting prices. Currently it is not possible to close the ``Sales Price List`` page if there are unverified price lines. But we explicitly do want to allow this, because the price lines will be verified by another person at another time.

In BC22.1 there is already a OnQueryClosePageOnBeforeDraftLineCheck for the Purchase Price List.

PS: We do not want to override HasDraftLines() as this function is too generic and will be called from different positions.
