### ISSUE TITLE
[Event Request] codeunit 9000854 "Inventory Profile Offsetting" procedure FromLotAccumulationPeriodStartDate()

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#23665]
Please can you add the following event/code at the start of the above procedure...

```
OnStartFromLotAccumulationPeriodStartDate(LotAccumulationPeriodStartDate, DemandDueDate, Result, IsHandled);
if IsHandled then
    exit(Result);
```
with 2 local variables..

```
var
    Result: Boolean;
    IsHandled: Boolean;
```
The event publisher would be...

```
[IntegrationEvent(false, false)]
local procedure OnStartFromLotAccumulationPeriodStartDate(LotAccumulationPeriodStartDate: Date; DemandDueDate: Date; var Result: Boolean; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11004.
