### ISSUE TITLE
[Event Request] Table 37 OnBeforeAutoReserve

### ISSUE THREAD

**Issue by SteveyN** [microsoft/ALAppExtensions#2368]
Table 37 Sales Line has a function called AutoReserve.

Can we get an OnBeforeAutoReserve to perform checks please?

Would probably be useful for other tables that have an AutoReserve function too

![image](https://user-images.githubusercontent.com/10519634/57463420-ad3ff980-7272-11e9-99ef-5879952386cf.png)

**Comment by AlexanderYakunin** [comment]
We already have this event:

IsHandled := FALSE;
OnBeforeAutoReserve(Rec,IsHandled);
IF IsHandled THEN
  EXIT;
