### ISSUE TITLE
[Event Request] codeunit 2623 (Stat. Acc. Jnl Check Line):  OnBeforeRunCheck

### ISSUE THREAD

**Issue by ekesteloot** [microsoft/ALAppExtensions#23683]
Current code in codeunit 2623 (Stat. Acc. Jnl Check Line) in the Statistical Accounts extension:

    internal procedure RunCheck(var StatisticalAccJournalLine: Record "Statistical Acc. Journal Line")
    var
        StatisticalAccount: Record "Statistical Account";
        DimensionManagement: Codeunit DimensionManagement;
        TableID: array[10] of Integer;
        No: array[10] of Code[20];
    begin
        StatisticalAccJournalLine.TestField("Statistical Account No.");
        StatisticalAccJournalLine.TestField(Amount);
        StatisticalAccount.Get(StatisticalAccJournalLine."Statistical Account No.");
        if StatisticalAccount.Blocked then
            Error(StatisticalAccountIsBlockedErr, StatisticalAccJournalLine."Statistical Account No.", StatisticalAccJournalLine."Line No.");

        No[1] := StatisticalAccount."No.";
        TableID[1] := DATABASE::"Statistical Account";
        if not DimensionManagement.CheckDimValuePosting(TableID, No, StatisticalAccJournalLine."Dimension Set ID") then
            Error(DimensionManagement.GetDimErr());
    end;

Please add a OnBeforeRunCheck integration event:

    internal procedure RunCheck(var StatisticalAccJournalLine: Record "Statistical Acc. Journal Line")
    var
        StatisticalAccount: Record "Statistical Account";
        DimensionManagement: Codeunit DimensionManagement;
        TableID: array[10] of Integer;
        No: array[10] of Code[20];

        IsHandled: Boolean;
    begin
        OnBeforeRunCheck(StatisticalAccJournalLine, IsHandled);
        if IsHandled then
            exit;

        StatisticalAccJournalLine.TestField("Statistical Account No.");
        StatisticalAccJournalLine.TestField(Amount);
        StatisticalAccount.Get(StatisticalAccJournalLine."Statistical Account No.");
        if StatisticalAccount.Blocked then
            Error(StatisticalAccountIsBlockedErr, StatisticalAccJournalLine."Statistical Account No.", StatisticalAccJournalLine."Line No.");

        No[1] := StatisticalAccount."No.";
        TableID[1] := DATABASE::"Statistical Account";
        if not DimensionManagement.CheckDimValuePosting(TableID, No, StatisticalAccJournalLine."Dimension Set ID") then
            Error(DimensionManagement.GetDimErr());
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeRunCheck(var StatisticalAccJournalLine: Record "Statistical Acc. Journal Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by nikolakukrika** [comment]
Same question here, why do we need to override the existing behavior?
We should not skip blocked nor dimension management checks, this can break the validation logic.
Event to do additional checks can be added.

**Comment by nikolakukrika** [comment]
We are rejecting this request for now because we feel that it is unsafe to allow skipping of the dimensions check.
If you need the event please reactivate and provide justification on why it is needed to skip the check.
