### ISSUE TITLE
[Event Request] codeunit 2624 (Stat. Acc. Jnl. Line Post): OnAfterTransferStatisticalAccJournalLineTo

### ISSUE THREAD

**Issue by ekesteloot** [microsoft/ALAppExtensions#23681]
Current code in codeunit 2624 (Stat. Acc. Jnl. Line Post) in Statistical Accounts extension:

    local procedure TransferStatisticalAccJournalLineTo(var StatisticalAccJournalLine: Record "Statistical Acc. Journal Line"; var StatisticalLedgerEntry: Record "Statistical Ledger Entry")
    begin
        StatisticalLedgerEntry."Statistical Account No." := StatisticalAccJournalLine."Statistical Account No.";
        StatisticalLedgerEntry."Posting Date" := StatisticalAccJournalLine."Posting Date";
        StatisticalLedgerEntry.Description := StatisticalAccJournalLine.Description;
        StatisticalLedgerEntry.Amount := StatisticalAccJournalLine.Amount;
        StatisticalLedgerEntry."Journal Batch Name" := StatisticalAccJournalLine."Journal Batch Name";
        StatisticalLedgerEntry."Dimension Set ID" := StatisticalAccJournalLine."Dimension Set ID";
        StatisticalLedgerEntry."Document No." := StatisticalAccJournalLine."Document No.";
        StatisticalLedgerEntry."Global Dimension 1 Code" := StatisticalAccJournalLine."Shortcut Dimension 1 Code";
        StatisticalLedgerEntry."Global Dimension 2 Code" := StatisticalAccJournalLine."Shortcut Dimension 2 Code";
    end;

Please add a OnAfterTransferStatisticalAccJournalLineTo integration event:

    local procedure TransferStatisticalAccJournalLineTo(var StatisticalAccJournalLine: Record "Statistical Acc. Journal Line"; var StatisticalLedgerEntry: Record "Statistical Ledger Entry")
    begin
        StatisticalLedgerEntry."Statistical Account No." := StatisticalAccJournalLine."Statistical Account No.";
        StatisticalLedgerEntry."Posting Date" := StatisticalAccJournalLine."Posting Date";
        StatisticalLedgerEntry.Description := StatisticalAccJournalLine.Description;
        StatisticalLedgerEntry.Amount := StatisticalAccJournalLine.Amount;
        StatisticalLedgerEntry."Journal Batch Name" := StatisticalAccJournalLine."Journal Batch Name";
        StatisticalLedgerEntry."Dimension Set ID" := StatisticalAccJournalLine."Dimension Set ID";
        StatisticalLedgerEntry."Document No." := StatisticalAccJournalLine."Document No.";
        StatisticalLedgerEntry."Global Dimension 1 Code" := StatisticalAccJournalLine."Shortcut Dimension 1 Code";
        StatisticalLedgerEntry."Global Dimension 2 Code" := StatisticalAccJournalLine."Shortcut Dimension 2 Code";

        OnAfterTransferStatisticalAccJournalLineTo(StatisticalAccJournalLine, StatisticalLedgerEntry);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterTransferStatisticalAccJournalLineTo(var StatisticalAccJournalLine: Record "Statistical Acc. Journal Line"; var StatisticalLedgerEntry: Record "Statistical Ledger Entry")
    begin
    end;

**Comment by RSMNishant** [comment]
Please add a OnAfterTransferStatisticalAccJournalLineTo integration event

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17712.
