### ISSUE TITLE
[Event Request] codeunit 2626 (Stat. Acc. Post. Batch): OnBeforePostJournal

### ISSUE THREAD

**Issue by ekesteloot** [microsoft/ALAppExtensions#23684]
Original code in codeunit 2626 (Stat. Acc. Post. Batch) in the Statistical Accounts extension:

    local procedure PostJournal(var StatisticalAccJournalLine: Record "Statistical Acc. Journal Line")
    begin
        StatisticalAccJournalLine.SetRange("Journal Template Name", StatisticalAccJournalLine."Journal Template Name");
        StatisticalAccJournalLine.SetRange("Journal Batch Name", StatisticalAccJournalLine."Journal Batch Name");
        if StatisticalAccJournalLine.IsEmpty() then
            Error(NotingToPostErr);

        StatisticalAccJournalLine.LockTable();
        VerifyLines(StatisticalAccJournalLine);
        ProcessLines(StatisticalAccJournalLine);
        StatisticalAccJournalLine.DeleteAll();

        Commit();

        if not DoNotShowUI then
            if GuiAllowed() then
                Message(JournalLinesWereSuccesfullyRegisteredMsg);
    end;

Please add an OnBeforePostJournal integration event:

    local procedure PostJournal(var StatisticalAccJournalLine: Record "Statistical Acc. Journal Line")
    var
        IsHandled: Boolean;
    begin
        OnBeforePostJournal(StatisticalAccJournalLine, IsHandled);
        if IsHandled then
            exit;

        StatisticalAccJournalLine.SetRange("Journal Template Name", StatisticalAccJournalLine."Journal Template Name");
        StatisticalAccJournalLine.SetRange("Journal Batch Name", StatisticalAccJournalLine."Journal Batch Name");
        if StatisticalAccJournalLine.IsEmpty() then
            Error(NotingToPostErr);

        StatisticalAccJournalLine.LockTable();
        VerifyLines(StatisticalAccJournalLine);
        ProcessLines(StatisticalAccJournalLine);
        StatisticalAccJournalLine.DeleteAll();

        Commit();

        if not DoNotShowUI then
            if GuiAllowed() then
                Message(JournalLinesWereSuccesfullyRegisteredMsg);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostJournal(var StatisticalAccJournalLine: Record "Statistical Acc. Journal Line"; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 17714.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17712.
