### ISSUE TITLE
[Request for External] Table 39 "Purchase Line" - new procedure GetTrackingBlocked()

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#23695]
I have added a new field to the table and in the OnValidate code I need to check the value of TrackingBlocked (I want to call CheckDateConflict.PurchLineCheck() only when TrackingBlocked is false).  However as TrackingBlocked is a global variable I cannot access this value.  I would like a new procedure added to the table that would return the value of TrackingBlocked as follows...

```
procedure GetTrackingBlocked()
begin
    exit(TrackingBlocked);
end;

```

**Comment by AlexanderYakunin** [comment]
Adding TrackingBlocked to protected var instead.

**Comment by kmistrytnp** [comment]
Ah yes, hadn't thought of that - that would be perfect

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11082.
