### ISSUE TITLE
[bug] error during sales invoice canceling

### ISSUE THREAD

**Issue by JPicard90** [microsoft/ALAppExtensions#23697]
if we try to cancel a posted sales invoice using action correct -> cancel came out an error 

![image](https://github.com/microsoft/ALAppExtensions/assets/20781085/dda4bf7c-6fbd-4338-8a45-e806e31f820b)

it seems that in the last update (SAAS env. 22.1.55890.56216 swiss localization) you add this column in sales head
        field(180; "Rcvd-from Country/Region Code"; Code[10])
        {
            Caption = 'Received-from Country/Region Code';
            TableRelation = "Country/Region";
        }   

this messed up everything because in sales invoice header there is another column with same ID but different purpose (field(180; "Payment Reference"; Code[50]) ) ! 

could you please check and fix this bug ASAP?

**Comment by JPicard90** [comment]
thanks... do you know how to access to this yammer community? i've searched everywhere but cannot find any info

**Comment by pri-kise** [comment]
You have to be microsoft partner, then you should be able to request access via the following link:
[aka.ms/BCYammer](https://aka.ms/BCYammer)
