### ISSUE TITLE
[EVENT REQUEST] page 9271 "Qualification Overview Matrix"

### ISSUE THREAD

**Issue by HenrikJeltsch** [microsoft/ALAppExtensions#23698]
Hello,
we need an extension in page 9271 "Qualification Overview Matrix" to adapt the filter to the Employee Qualification.

    local procedure MatrixOnDrillDown(ColumnID: Integer)
    begin
        EmployeeQualification.SetRange("Employee No.", "No.");
        EmployeeQualification.SetRange("Qualification Code", MatrixRecords[ColumnID].Code);
        **OnBeforeFindEmployeeQualification(EmployeeQualification)**
        PAGE.Run(PAGE::"Qualified Employees", EmployeeQualification);
    end;
    
    local procedure MATRIX_OnAfterGetRecord(ColumnID: Integer)
    begin
        EmployeeQualification.SetRange("Employee No.", "No.");
        EmployeeQualification.SetRange("Qualification Code", MatrixRecords[ColumnID].Code);
        **OnBeforeFindEmployeeQualification(EmployeeQualification)**
        Qualified := EmployeeQualification.FindFirst();
        EmployeeQualification.SetRange("Employee No.");
        EmployeeQualification.SetRange("Qualification Code");
        **Reset();**
        MATRIX_CellData[ColumnID] := Qualified;
        SetVisible();
    end;
    
    
    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindEmployeeQualification(var EmployeeQualification: Record "Employee Qualification")
    begin
    end;

**Comment by AleksandricMarko** [comment]
Hello @HenrikJeltsch 
You probably want to add some additional filters on the EmployeeQualification record.
But for two procedures, we need to have two events (event both have same logic, parameters...)
What is the purpose of **Reset();**? We can`t change standard code, only add new events.

**Comment by HenrikJeltsch** [comment]
Hello @AleksandricMarko 
Yes, I want to add some additional filters on the EmployeeQualification record like the Expiration Date.
In my opinion the same event could be called in both procedures, because you'll always want the same filters to be attached to the DrillDown and the determination of the qualification in the matrix.
Due to the fact, that the EmployeeQualification is declared as a global variable, you'll need to reset all the filters that were attached. 
Actually it would be way better to use local variables in the procedures. In fact with the global var there should be a change in the procedure MatrixOnDrillDown too.

I would do it this way:

local procedure MatrixOnDrillDown(ColumnID: Integer)
var
    EmployeeQualification: Record "Employee Qualification"
begin
    EmployeeQualification.SetRange("Employee No.", "No.");
    EmployeeQualification.SetRange("Qualification Code", MatrixRecords[ColumnID].Code);
    OnBeforeFindEmployeeQualification(EmployeeQualification);
    PAGE.Run(PAGE::"Qualified Employees", EmployeeQualification);
end;

local procedure MATRIX_OnAfterGetRecord(ColumnID: Integer)
var
    EmployeeQualification: Record "Employee Qualification"
begin
    EmployeeQualification.SetRange("Employee No.", "No.");
    EmployeeQualification.SetRange("Qualification Code", MatrixRecords[ColumnID].Code);
    OnBeforeFindEmployeeQualification(EmployeeQualification);
    MATRIX_CellData[ColumnID] := EmployeeQualification.FindFirst();
    SetVisible();
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeFindEmployeeQualification(var EmployeeQualification: Record "Employee Qualification")
begin
end;

With this, you could easily remove both the global vars EmployeeQualification and Qualified as they are totally unnecessary.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11061.
