### ISSUE TITLE
[Request for external] Remove OnPrem scope requests for external approved but not removed

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#23690]
Issue  #23639 was closed so could not reply anymore

We requested to remove the OnPrem scope from functions which do not contain OnPrem specific code.
Please have a look at the following requests for external. They are approved before major 22x but we do not see any code changes in the major 22.1.
Please review if they are added and otherwise add them in a **next** major release. We required this for the universal code initiative that is required by Microsoft.

https://github.com/microsoft/ALAppExtensions/issues/22081
https://github.com/microsoft/ALAppExtensions/issues/22084
https://github.com/microsoft/ALAppExtensions/issues/22087
https://github.com/microsoft/ALAppExtensions/issues/22198
https://github.com/microsoft/ALAppExtensions/issues/22129

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
