### ISSUE TITLE
Send email via Job Queue

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#237]
Hi all,

When you want to send e.g. Purchase Orders via email, and there is more than one document for same vendor, only one document is sent when user decide to send emails in background. If user chooses to show dialog, all docs are sent.

Is this bug (or feature)?

Screen shot from T 77, function SendEmailToVendor
![image](https://user-images.githubusercontent.com/34686682/45680744-fe607900-bb3b-11e8-85e5-eabc0f453198.png)

**Comment by ikoletic** [comment]
Please have a look at [this ](https://github.com/microsoft/ALAppExtensions/blob/master/AddOns/UKSendRemittanceAdvice/app/src/pag29-ext4023.SendVendLedgerEntryRemitAdvice.al) code for inspiration. Here we're sending multiple emails with reports as attachment through job queues.
