### ISSUE TITLE
Changing order date on Purchase Order causes error if drop shipment

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/ALAppExtensions#23709]
Changing the order date on a drop-ship purchase order that is linked to a sales order causes an error because the process validates the "No." field of all purchase lines.

If one answers Yes to this question

![image](https://github.com/microsoft/ALAppExtensions/assets/35798628/3e49a70f-838b-46e3-b1b3-8e289fe51835)

The following code will be run (table Purchase Header):

![image](https://github.com/microsoft/ALAppExtensions/assets/35798628/bc460a41-e874-4c40-ab15-63f9a0d5600f)

**Why is the "No."-field revalidated?**

This causes an error down the line, since we cannot change the "No." field of a linked order. (Purchase Line)

![image](https://github.com/microsoft/ALAppExtensions/assets/35798628/6c6ed79b-42f8-45d2-b288-ea3118dfbf7f)

**This is definitely non-intentional behavior, since the Order Date on the Purchase Order can be changed if one answers "no" to the confirmation, and the Order Date -field on all the lines can also be manually changed.**

**Comment by AlexanderYakunin** [comment]
We cannot help with bug reports here, you are using wrong channel. Please report via support!
