### ISSUE TITLE
[Access Request] report 5884 "Calc. Phys. Invt. Order Count"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23703]
Could you please change the access scope of the follwoing variables to protected?
```al
protected var
        ZeroQty: Boolean;
        CalcQtyExpected: Boolean;
        OKPressed: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11082.
