### ISSUE TITLE
[Event Change] Codeunit 227 VendEntry-Apply Posted Entries 

### ISSUE THREAD

**Issue by Kowa63** [microsoft/ALAppExtensions#2371]
Please check if these modifications are possible:

A further parameter _GenJnlPostLine_ is required in publisher **OnAfterPostApplyVendLedgEntry**.

![grafik](https://user-images.githubusercontent.com/16236672/57463661-7de1ba80-727b-11e9-9762-144b50a75d64.png)

Also the same addition in **OnAfterPostUnapplyVendLedgEntry**.
![grafik](https://user-images.githubusercontent.com/16236672/57463787-c600dd00-727b-11e9-8bf6-9a0de1c8b276.png)

If you compare publisher **OnAfterPostGenJnlLine** in Codeunit 13, the parameter _GenJnlPostLine_ is already present there, so this would enable conformity in these related publishers. 
![grafik](https://user-images.githubusercontent.com/16236672/57464482-1cbae680-727d-11e9-88ce-ddc9b0ca210b.png)

The same applies to the corresponding publishers in Codeunit 226. Nothing that we need at present, but it would be nice to keep the debit and credit side in sync in this respect.

Thanks in advance.

**Comment by GeekEding** [comment]
Hi @jobulsin ,
the first one is done, but the second one is still missing - can you check it please?

**First one:**
![grafik](https://user-images.githubusercontent.com/40355993/61939072-be0b2c00-af92-11e9-872a-68960a596a12.png)


**Second one:**
![grafik](https://user-images.githubusercontent.com/40355993/61939098-cb281b00-af92-11e9-9dbb-f6058c8af164.png)
