### ISSUE TITLE
[Event Request] page 9253 "Dim. Value Combinations Matrix" - OnBeforeLoad

### ISSUE THREAD

**Issue by BharatVelosio** [microsoft/ALAppExtensions#23714]
Hi Team,

In  page 9253, please provide the possibility to have OnBeforeLoad event in procedure.

procedure Load(MatrixColumns1: array[32] of Text[1024]; var MatrixRecords1: array[32] of Record "Dimension Value"; _Row: Code[20]; CurrentNoOfMatrixColumn: Integer)

After begin at Line No 525

IsHandled := false;
OnBeforeLoad(MatrixColumns1, MatrixRecords1, _Row, CurrentNoOfMatrixColumn, IsHandled);
if IsHandled then
exit;

<img width="612" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/133997930/9465fa1a-124a-45f7-8a02-f35ed186eebb">

Event:
[IntegrationEvent(false, false)]
local procedure OnBeforeLoad(MatrixColumns1: array[32] of Text[1024]; var MatrixRecords1: array[32] of Record "Dimension Value"; _Row: Code[20]; CurrentNoOfMatrixColumn: Integer)
begin
end;

**Comment by BharatVelosio** [comment]
Hi Team,

Any update on the above request.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11061.
