### ISSUE TITLE
[Access Request] table 252 "General Posting Setup" LookupGLAccount

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23717]
Could you please change the access scope of the procedure `LookupGLAccount` to protected?
```al
    //+Change
    local procedure LookupGLAccount(var AccountNo: Code[20]; AccountCategory: Option; AccountSubcategoryFilter: Text)
    protected procedure LookupGLAccount(var AccountNo: Code[20]; AccountCategory: Option; AccountSubcategoryFilter: Text)
    //-Change
    begin
        GLAccountCategoryMgt.LookupGLAccount(Database::"General Posting Setup", CurrFieldNo, AccountNo, AccountCategory, AccountSubcategoryFilter);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
