### ISSUE TITLE
[Event Request] COD 80 / 90 - CalcDeferralAmounts - OnBeforeTempDeferralLineInsert

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#2372]
In COD 80 and 90, function CalcDeferralAmounts, we would like to include the **description of the purchase line** and **deferral no** vs the **total no. of deferrals** (e.g. 1/12) as part of the deferral description. To achieve this, we customized the TempDeferralLine.description. Not the most elegant way, but at least here we got access to DeferralCount and TotalDeferralCount

```
..
        //NVTBE/Deferral description from original line description
        TempDeferralLine.Description := COPYSTR(NVTBETools.StringReplace(DeferralLine.Description,'%99',PurchLine.Description),1,MAXSTRLEN(TempDeferralLine.Description));
        //NVTBE/Deferral description with No. of deferral mentioned
        TempDeferralLine.Description := COPYSTR(NVTBETools.StringReplace(TempDeferralLine.Description,'%98',STRSUBSTNO('%1/%2',DeferralCount,TotalDeferralCount)),1,MAXSTRLEN(TempDeferralLine.Description));

        >> Add OnBeforeTempDeferralLineInsert here
        TempDeferralLine.INSERT;
      UNTIL NEXT = 0;
...
```

Can you provide an OnBeforeTempDeferralLineInsert event with VAR access to TempDeferralLine, as well as access to PurchLine (cod 90), SalesLine (cod 80) DeferralCount, TotalDeferralCount?

_An alternative solution might be to already set the description in COD 1720 where 'CreateRecurringDescription' is called. However, this misses the 'Period No' vs 'Total Periods'. Would be interesting if we could subscribe to 'OnAfterCreateRecurringDescription' as well, with access to 'PeriodicCount' + total no. of periods._

**Comment by AlexanderYakunin** [comment]
We already have event here OnBeforeTempDeferralLineInsert(TempDeferralLine,DeferralLine,SalesLine,DeferralCount,TotalDeferralCount);
