### ISSUE TITLE
[Event Request] page 1030 "Job Cost Factbox" procedure OnDrillDown() field InvoicedPriceLCY

### ISSUE THREAD

**Issue by michaelarmanno-tnp** [microsoft/ALAppExtensions#23726]
Please can you add the following code/event to the above procedure...

```
trigger OnDrillDown()
var
    IsHandled: Boolean;     //NEW CODE
begin
    IsHandled := false;     //NEW CODE
    OnBeforeOnDrillDownInvoicedPriceLCY(Rec, IsHandled);    //NEW CODE
    if IsHandled then       //NEW CODE
        exit;               //NEW CODE

   JobCalcStatistics.ShowLedgEntry(1, false);
end;
```

The event publisher should be as follows...

```
[IntegrationEvent(true, false)]     //SENDER = TRUE
local procedure OnBeforeOnDrillDownInvoicedPriceLCY(var Job: Record Job; var IsHandled: Boolean);
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11061.
