### ISSUE TITLE
[Access Request] table 36 "Sales Header" - GetContactAsCompany

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23734]
Could you please change the access scope of the procedure  GetContactAsCompany to _protected_?
```al
   //+Change
    //-local procedure GetContactAsCompany(Contact: Record Contact; var SearchContact: Record Contact): Boolean;
    protected procedure GetContactAsCompany(Contact: Record Contact; var SearchContact: Record Contact): Boolean;
   //-Change
    var
        IsHandled: Boolean;
    begin
        OnBeforeGetContactAsCompany(Contact, SearchContact, IsHandled);
        if not IsHandled then
            if Contact."Company No." <> '' then
                exit(SearchContact.Get(Contact."Company No."));
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
