### ISSUE TITLE
CONFIRM in Microsoft code without GUIALLOWED

### ISSUE THREAD

**Issue by FabianBigler** [microsoft/ALAppExtensions#2374]
This is still an issue in the latest CU6:
In the Codeunit 7304 - Whse. Jnl.-Register Batch there is a CONFIRM within the function CheckItemAvailability.

CONFIRM is evil if I call the function via SOAP or ODATA (it will simply fail, whenever it hits CONFIRM).

I kindly ask you to fix this for **all** objects in the next CU the same way as in Sales-Post (with the ConfirmManagement CU).

Kind regards
Fabian

**Comment by JSebastianN** [comment]
I agree.

When posting via a Mobile Device communicating via Web Service.

codeunit 23 "Item Jnl.-Post Batch"
CheckItemAvailability(ItemJnlLine);

codeunit 7304 "Whse. Jnl.-Register Batch"
CheckItemAvailability(WhseJnlLine);

Are using CONFIRMs which makes using them impossible.

Also:
Functions are local
They have the same text message "One or more reservation entries exist for the item with..."
They both calculate Item."Reserved Qty. on Inventory", code could be centralized.

I would like to suggest a refactoring, opening these functions up for external use or support a web service use-case, like already suggested.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
