### ISSUE TITLE
[Event Request] codeunit 5940 ServContractManagement procedure CreateCreditLine()

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#23744]
The above procedure inserts 2 lines in the "Service Line" table.  The first line is a heading (Description only) and the 2nd line is a G/L Account.  There is a OnBeforeServLineInsert() event before the 2nd ServLine2.Insert(), but I would like a similar event added for the 1st ServLine2.Insert() (the heading/description).  This could be called OnBeforeServLineHeadingInsert as follows...

```
Clear(ServLine2);
ServLine2.Init();
ServLine2."Document Type" := ServHeader2."Document Type";
ServLine2."Document No." := ServHeader2."No.";
ServLine2.Type := ServLine2.Type::" ";
ServLine2.Description := StrSubstNo('%1 - %2', Format(PeriodStarts), Format(PeriodEnds));
ServLine2."Line No." := NextLine;
ServLine2."Posting Date" := PeriodStarts;

OnBeforeServLineHeadingInsert(ServLine2, ServHeader2, ServContract);    // NEW CODE/EVENT

ServLine2.Insert();

```
The event publisher would be...

```
[IntegrationEvent(false, false)]
local procedure OnBeforeServLineHeadingInsert(var ServiceLine: Record "Service Line"; ServiceHeader: Record "Service Header"; ServiceContractHeader: Record "Service Contract Header")
begin
end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11061.
