### ISSUE TITLE
codeunit 5856 "TransferOrder-Post Transfer" - make RunWithCheck public

### ISSUE THREAD

**Issue by xtiche** [microsoft/ALAppExtensions#23749]
Please make the function `RunWithCheck` not internal but public, as I need to post "Direct Transfer" in the middle of transaction and I cannot use Codeunit.Run, as it will occur Commit .

**Comment by AlexanderYakunin** [comment]
You can always run codeunit without commit, you only need commit before Page.Run or Report.Run
