### ISSUE TITLE
[Event Request] codeunit 5940 ServContractManagement procedure CreateServHeader()

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#23740]
Please can you add the following event/code just before the call to Cust.CheckBlockedCustOnDocs as follows

OLD CODE...
```
Cust.CheckBlockedCustOnDocs(Cust, ServHeader2."Document Type", false, false);
   
```
NEW CODE...
```
IsHandled := false;
OnBeforeCheckBlockedCustOnDocsForServiceInvoice(ServHeader2, ServContract2, IsHandled);
if not IsHandled then
    Cust.CheckBlockedCustOnDocs(Cust, ServHeader2."Document Type", false, false);
    
```

The event publisher would be...

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckBlockedCustOnDocsForServiceInvoice(var ServiceHeader: Record "Service Header"; ServContract2: Record "Service Contract Header"; var IsHandled: Boolean);
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11061.
