### ISSUE TITLE
[Event Request Extra Parameter] report 5914 "Delete Invoiced Service Orders" OnBeforeServiceHeaderOnAfterGetRecord

### ISSUE THREAD

**Issue by renevanbeekum** [microsoft/ALAppExtensions#23754]
Change like report 299 "Delete Invoiced Sales Orders"

Changes:
Old:
OnBeforeServiceHeaderOnAfterGetRecord("Service Header");

New
IsHandled := false;
OnBeforeServiceHeaderOnAfterGetRecord("Service Header", IsHandled);
if IsHandled then
  CurrReport.Skip();

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11076.
