### ISSUE TITLE
[Event Change] Table "Document Attachment", OnBeforeSaveAttachment

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#23757]
Hi Team,

is it possible to change signature of publisher OnBeforeSaveAttachment?

This request would change the publisher signature as follows:

``` AL
[IntegrationEvent(false, false)]
    local procedure OnBeforeSaveAttachment(var DocumentAttachment: Record "Document Attachment"; var RecRef: RecordRef; var FileName: Text; var TempBlob: Codeunit "Temp Blob")
    begin
    end;
```
Change: Parameter FileName changed to var-parameter. From my point of view, there are no more additional code changes needed.

``` AL
 [IntegrationEvent(false, false)]
    //local procedure OnBeforeSaveAttachment(var DocumentAttachment: Record "Document Attachment"; var RecRef: RecordRef; FileName: Text; var TempBlob: Codeunit "Temp Blob")
    local procedure OnBeforeSaveAttachment(var DocumentAttachment: Record "Document Attachment"; var RecRef: RecordRef; **var FileName: Text**; var TempBlob: Codeunit "Temp Blob")
    // --
    begin
    end;
```

Thanks in advance,
Christian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11076.
