### ISSUE TITLE
[Event Request] COD 427 - OnCreateSalesDocumentOnBeforeSalesHeaderInsert

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#2375]
In #2231 an OnBeforeCreateSalesDocument is requested, which can't be used for the case below.

![image](https://user-images.githubusercontent.com/25268332/57517644-97d0db00-7317-11e9-8b69-b3531ba00c4a.png)

We've added customisations to the No Series / Journal Template logic on Sales Documents. Most can be handled via the OnInitRecord, OnInsertRecord triggers / events in the Sales Header table. However, for creation of sales documents via IC, we need to be able to customize / predefine the Journal templates differently.  

Since we don't have the IC context upon SalesHeader.Insert ('IC Direction' is only set after the Insert statement), we can't deal with the journal template part in the OnInitRecord, OnInsertRecord triggers / events in the Sales Header table

Please provide an **OnCreateSalesDocumentOnBeforeSalesHeaderInsert** publisher with VAR access to SalesHeader and access to ICInboxSalesHeader.

The same applies to 'Create**Purch**Document' as well.

Please provide an **OnCreatePurchDocumentOnBeforePurchHeaderInsert** publisher with VAR access to PurchHeader and access to ICInboxPurchHeader.

**Comment by lv-janpieter** [comment]
We have the same requirement. I don't see why it is labeled refactoring? I only see event requests. Is that why this issue takes more time?

**Comment by AlexanderYakunin** [comment]
This is done, closing
