### ISSUE TITLE
[Event Request] page 43 "Sales Invoice" trigger OnDeleteRecord()

### ISSUE THREAD

**Issue by michaelarmanno-tnp** [microsoft/ALAppExtensions#23758]
Please can you add the following code/event to the above procedure...

```
trigger OnDeleteRecord(): Boolean
var
    IsHandled: Boolean;     //NEW CODE
    Result: Boolean;        //NEW CODE
begin
    CurrPage.SaveRecord();

    OnBeforeOnDeleteRecord(Rec, Result, IsHandled); //NEW CODE

    if IsHandled then       //NEW CODE
        exit(Result)        //NEW CODE
    else                    //NEW CODE
        exit(ConfirmDeletion());    
end;
```

The event publisher should be as follows...

```
[IntegrationEvent(true, false)]     //SENDER = TRUE
local procedure OnBeforeOnDeleteRecord(var SalesHeader: Record "Sales Header"; var Result: Boolean; var IsHandled: Boolean);
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11076.
