### ISSUE TITLE
[Event Change] Table  "Document Attachment", OnBeforeSaveAttachmentFromStream

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#23756]
Hi Team,

is it possible to change signature of publisher OnBeforeSaveAttachmentFromStream?

This request would change the publisher signature as follows:

``` AL
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSaveAttachmentFromStream(var DocumentAttachment: Record "Document Attachment"; var RecRef: RecordRef; var FileName: Text; var DocStream: InStream)
    begin
    end;
```
Change: Parameter **FileName** changed to var-parameter. From my point of view, there are no more additional code changes needed.

```
 [IntegrationEvent(false, false)]
    //local procedure OnBeforeSaveAttachmentFromStream(var DocumentAttachment: Record "Document Attachment"; var RecRef: RecordRef; FileName: Text; var DocStream: InStream)
    local procedure OnBeforeSaveAttachmentFromStream(var DocumentAttachment: Record "Document Attachment"; var RecRef: RecordRef; **var FileName: Text**; var DocStream: InStream)
    //--
    begin
    end;
```

Thanks in advance,
Christian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11076.
