### ISSUE TITLE
[Followup] Codeunit 12 "Gen. Jnl.-Post Line" - IsHandled pattern for OnBeforeApplyCustLedgEntry event.

### ISSUE THREAD

**Issue by CameliaPopescu** [microsoft/ALAppExtensions#23759]
Hello,

In https://github.com/microsoft/ALAppExtensions/issues/19201 we requested an IsHandled parameter for event OnBeforeApplyCustLedgEntry.

In the followup issue #21993, we were asked to provide an example why we need the IsHandled parameter.
We have some specific development and based on certain conditions, another custom function is called to create and post specific journal lines. 
So, the "Amount To Apply" can be different than zero and it would get through the standard code from ApplyCustLedgEntry as well as through our specific function. We need that IsHandled parameter to avoid getting through the standard code in certain conditions.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11076.
