### ISSUE TITLE
[Request for external] Workflow Step - ConvertEventConditionsToFilters

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#23752]
We would like to request to remove the OnPrem scope from table 1502 "Workflow Step" - Function: ConvertEventConditionsToFilters
This function uses Tempblob and should be able to be used in Cloud development as well. There is no OnPrem specific functionality in this procedure.
We would like to request the removal of the OnPrem tag from this function

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
