### ISSUE TITLE
Expose Function in Subforms

### ISSUE THREAD

**Issue by radovandokic** [microsoft/ALAppExtensions#2376]
Hi,

Can you please expose these functions:
NoOnAfterValidate;
UpdateTypeText;

in pages:
46 -Sales Order Subform
47 - Sales Invoice Subform
55 - Purch. Invoice Subform
95 - Sales Quote Subform
96 - Sales Cr. Memo Subform
97 - Purchase Quote Subform
98 - Purch. Cr. Memo Subform

We have our fields in extension, and we want to popper update depending native fields after validation

Thanks!

**Comment by AlexanderYakunin** [comment]
This is done, closing
