### ISSUE TITLE
[Request] Add GetBlobMetadata procedure to ABS Blob Client codeunit

### ISSUE THREAD

**Issue by EvaCegeka** [microsoft/ALAppExtensions#23764]
Hello,

In codeunit 9053 ABS Blob Client there is a procedure with several overloads GetBlobTags that allows us to get the tags associated with a particular blob in the Azure Blob Storage container. The tags can be retrieved as either an XmlDocument or Dictionary[Text, Text].

Is it possible to add similar procedures GetBlobMetadata to allow us to also get the metadata associated with a particular blob using ABS Blob Client?

Thanks in advance for your time.

**Comment by JesperSchulz** [comment]
That would be a perfect candidate for a contribution. Please feel free to create a pull request here on GitHub for the overloads that you require!
