### ISSUE TITLE
[Event Request] table 36 "Sales Header" - in InitDefaultDimensionSources procedure

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#23768]
If possible, could an event be added to the beginning of the InitDefaultDimensionSources procedure so we can make adjustments to the dimension sources.  We don't need an IsHandled code pattern with it, but I could see it not being a bad idea to do it.  Thank you.

```
    local procedure InitDefaultDimensionSources(var DefaultDimSource: List of [Dictionary of [Integer, Code[20]]]; FieldNo: Integer)
    begin
        OnBeforeInitDefaultDimensionSources(Rec, DefaultDimSource, FieldNo);  // << NEW EVENT

        DimMgt.AddDimSource(DefaultDimSource, Database::Customer, Rec."Bill-to Customer No.", FieldNo = Rec.FieldNo("Bill-to Customer 
...

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitDefaultDimensionSources(var SalesHeader: Record "Sales Header"; var DefaultDimSource: List of [Dictionary of [Integer, Code[20]]]; FieldNo: Integer)
    begin
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11076.
