### ISSUE TITLE
Report 91 - "Export Consolidation" cannot be scheduled (and email or ftps the file)

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/ALAppExtensions#23765]
We need to be able to **execute this process _in SaaS_ from the job queue and send the resulting file by Email o FTPS**, but in the current version (v22.2) it is impossible **without having to completely duplicate the Report, the XMLPort and some other standard functions**.

The problems we encountered in order to do so are the following:

a) The minimum desirable scenario would be to be able to schedule the execution from the UI, but it gives the following Error and stops when trying to download the generated file.

![image](https://github.com/microsoft/ALAppExtensions/assets/5801847/b9cb20fb-85d8-49a1-aabe-2beb1c1e2763)

![image](https://github.com/microsoft/ALAppExtensions/assets/5801847/f9bac0d5-a7d1-4d9f-9726-dfadb9dd03ca)

For other scenarios of customizations by code, we have that:

b) The **InitializeRequest()** function does not allow indicating the **Starting / Ending Dates, the Selected Dimensions or the Main Currency**.

c) Not being able to initialize these parameters from outside, the process gives an Error due to the existing checks in the "G/LAccount" event. OnPreDataItem()

![image](https://github.com/microsoft/ALAppExtensions/assets/5801847/057330a6-64d8-4e01-9886-3d6ac5c162ee)

![image](https://github.com/microsoft/ALAppExtensions/assets/5801847/53bad6bb-3aab-4374-bd18-74ca4ec4fc10)

d) Therefore, **cannot be executed under job queue in any way [.RunModal(), .Execute(PageParameters), .SaveAs(PageParameters,...), etc]**

d) Even if we managed to execute it, **there is no event or RequestPage option that allows us, in SaaS, to recover the content of the file at run time to send it by Email or FTPS (for example)**.

We request to improve this process in future versions to cover all those scenarios and use cases.
Thanks in advance.

**Comment by AlexanderYakunin** [comment]
Hello! We have BCIDEAS forum for this kind if improvements, this is actually feature request. Please use this place if you want to get it done.

**Comment by JavierFuentes** [comment]
Please, at least, add the missing RequestPage fields in the InitializeRequest() function and generally avoid the ERROR that throws the background Download of files:

```al
ExportConsolidation.InitializeRequest(
  FileFormat, 
  FileName, 
  ConsolidStartDate,  // missing
  ConsolidEndDate,  // missing
  ColumnDim,  // missing
  ParentCurrencyCode  // missing
);
```

```al
[EventSubscriber(ObjectType::Codeunit, Codeunit::"File Management", OnBeforeDownloadHandler, '', false, false)]
local procedure OnBeforeDownloadHandlerSubscriber
(
    var ToFolder: Text;
    ToFileName: Text;
    FromFileName: Text;
    var IsHandled: Boolean;
    var Downloaded: Boolean
);
begin
    if (not GuiAllowed()) then begin
        Downloaded := false;
        IsHandled := true;
    end;
end;
```

**Comment by JavierFuentes** [comment]
Great! 
The best response to solve the Bug of missing parameters in InitializeRequest() procedure.
