### ISSUE TITLE
[Event Request] codeunit 12 - "Gen. Jnl.-Post Line" - OnBeforeVendLedgEntryInsert

### ISSUE THREAD

**Issue by achowtc** [microsoft/ALAppExtensions#23766]
On the IntegrationEvent for OnBeforeVendLedgEntryInsert, can we add var to the GenJournalLine variable?
![image](https://github.com/microsoft/ALAppExtensions/assets/34691006/43775443-90e0-4662-b9a9-8bd63a14c16d)

I see that the OnBeforeCustLedgEntryInsert already has var added to the GenJournalLine variable.
![image](https://github.com/microsoft/ALAppExtensions/assets/34691006/fe605876-afa8-4820-a550-f5438b3d61fb)

This will allow us to create the same functionalitiesfor both the purchase and the sales side.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11076.
