### ISSUE TITLE
[Extensibility Request] Confirm Management

### ISSUE THREAD

**Issue by ivas-su** [microsoft/ALAppExtensions#23767]
Recently, I encountered a situation where I needed to handle the call of ConfirmManagement.GetResponseOrDefault(...) in the codeunit 225 "Gen. Jnl.-Apply" (line 628). I needed to ensure that under certain conditions, the Confirm call wouldn't happen. However, I couldn't find any information on how to achieve this. Therefore, I wanted to ask if there is a way to handle this. If it's not possible, could you please add such functionality? Thank you.

**Comment by dannoe** [comment]
You must then request a specific event within the codeunit. The ConfirmManagement currently does not offer the possibility to skip Confirms (except for tests from Microsoft).

**Comment by ivas-su** [comment]
@dannoe, do you mean that in this situation, should an event request be created for codeunit 225 "Gen. Jnl.-Apply"? Or for Confirm Management?

**Comment by dannoe** [comment]
Inside the Gen. Jnl.-Apply codeunit.

**Comment by ivas-su** [comment]
@dannoe, I have no further questions, thank you for the response)
