### ISSUE TITLE
[Request] Retrieving blob list based on tags filter using procedure ListBlobs from ABS Blob Client codeunit

### ISSUE THREAD

**Issue by EvaCegeka** [microsoft/ALAppExtensions#23762]
Hello,

We are running into the following issue with codeunit 9053 ABS Blob Client.

We need to retrieve a list of blobs from Azure Blob Storage, but in the result set we only want to see blobs where one of the tags has a specific value. E.g. I only want to see the blobs in a specific container where tag X is set to Y, and not A B C etc.

Currently using procedure ListBlobs does not seem to allow for any filtering using ABS Optional Parameters. We need to be able to set this where clause that is necessary for filtering according to documentation here using ABS Blob Client and ABS Optional Parameters codeunits:
![image](https://github.com/microsoft/ALAppExtensions/assets/99252301/1533f920-fb74-4e61-8b0e-faaf8e4f70f4)
https://learn.microsoft.com/en-us/rest/api/storageservices/find-blobs-by-tags?tabs=azure-ad#remarks

Thank you in advance for your time.

**Comment by pri-kise** [comment]
@EvaCegeka the system application is open for contribution.
If you really need this then you should create a pull request to set an addtional optional paramter for filtering.

**Comment by GTimmers** [comment]
Hi @pri-kise, another way to solve the problem is to create a new procedure in codeunit 9053 ABS Blob Client, called: Find Blobs by Tags in Container
https://learn.microsoft.com/en-us/rest/api/storageservices/find-blobs-by-tags-container?tabs=azure-ad

It will require more code, but it is a more direct solution.
Unless you think there is an issue with this, we will create a PR for this in the coming weeks.

**Comment by pri-kise** [comment]
@GTimmers fell free to create a PR for this addition.

**Comment by GTimmers** [comment]
> @GTimmers fell free to create a PR for this addition.

https://github.com/microsoft/ALAppExtensions/pull/24253

**Comment by GTimmers** [comment]
@pri-kise You are right! We decided to retrieve the blobs from a certain specified folder and now also include the tags in the parameters. 
We can do some filtering on them and thats a good solution for us.

**Comment by JesperSchulz** [comment]
If any work remains in this issue, feel free to create further pull requests addressing them.
