### ISSUE TITLE
Swiss QR-Bill Encode procedure AddPartyInfo Country empty

### ISSUE THREAD

**Issue by DominicSaladin** [microsoft/ALAppExtensions#23778]
App: QR-Bill Management for Switzerland

In the Swiss QR-Bill Encode codeunit, the procedure `AddPartyInfo(var TargetText: Text; Customer: Record Customer; AddressType: Enum "Swiss QR-Bill Address Type")` adds a empty Country/Region Code if the customer is from the local country.

That field must be filled out. So we either need a event to fill it out ourself or you use the value from the CompanyInformation table.
What would be the better option?

**Comment by AlexanderYakunin** [comment]
Hello! We have not received any support requests that this module is not working properly. We also use blank country code for local country in many places in application code, so probably this is not an issue. If you have any business scenario or repro steps to confirm this is an issue, you can create support request. Please also be aware that this is not an extensibility request and our team cannot process it.

**Comment by DominicSaladin** [comment]
That is definitely a issue, as the SIX Group (which defines the specifications for the QR-Bill) specifies that the country code must be filled. But then I will open a support request on mbs, correct?

**Comment by AlexanderYakunin** [comment]
This procedure contains last line to add Customer "Country/Region Code". 
            AddLine(TargetText, "Country/Region Code");

**Comment by DominicSaladin** [comment]
Correct, but as you said, the Country/Region Code is always empty for the local country. And in my opinion the Swiss QR-Bill App should build the correct qr code, so it should check for empty Country/Region Code.
But I will open a support request for that, if this is the wrong place for that.
