### ISSUE TITLE
[Event Request / Application Refactoring] COD 396 - DoGetNextNo - allow to insert 'reserved' numbers

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#2377]
We face following challenge:

To avoid gaps in the posted sales / purchase documents, BC adds **empty posted documents** when deleting a document that had already a posted doc. no. assigned. Our financial consultant is not in favor of these 'empty' documents, so we decided to **disable** the creation of these documents via an extension. The no. that would have been used for the posted document is stored in a custom table and is to be re-used later on when assigning a new posted no.

Scenario:
> - Document nos '1 / 2 / 3 / 4 / 5' assigned
> - No. series 'Last Used' = '5'
> - Delete Document '3' > BC will create a posted doc. with No. '3' > This has been disabled 
> - Creating a new document will get no. '6' > We would like to assign No. **'3'** instead (from a custom table)

To achieve the above, we added code in the 'DoGetNextNo' function in COD 396. Can you provide an event publisher to support migration to events?
```
...
IF ModifySeries THEN BEGIN
  //NVTBE/REQ2018-0570 Begin
  IF NOT DocumentNumbersToBeReused.GetNoTobeReused(NoSeriesLine."Series Code",NoSeriesLine."Line No.",NoSeriesLine."Last No. Used") THEN
  //NVTBE/REQ2018-0570 End
  >>> ADD EVENT HERE <<<
  NoSeriesLine.MODIFY
END ELSE
  LastNoSeriesLine := NoSeriesLine;

OnAfterGetNextNo3(NoSeriesLine);

EXIT(NoSeriesLine."Last No. Used");
...
```

_Alternative: Application refactoring: The above solution is not the most elegant. It would be better if the below part of the 'DoGetNextNo' code could be moved to a 'CreateNextNo' function, with OnBeforeDoGetNextNo publisher and Handled pattern, so we could change the No. to be used. However, result should be returned via variable instead of "Last No. Used" (to avoid the value of "Last No. Used" to be updated to '3' instead of leaving it to '5' in the above scenario). Also 'ModifySeries' should be false in this case. (Not sure about the 'LastNoSeriesLine = NoSeriesLine' statement)_

```
...
IF NoSeriesLine."Last No. Used" = '' THEN BEGIN
  IF NoErrorsOrWarnings AND (NoSeriesLine."Starting No." = '') THEN
    EXIT('');
  NoSeriesLine.TESTFIELD("Starting No.");
  NoSeriesLine."Last No. Used" := NoSeriesLine."Starting No.";
END ELSE
  IF NoSeriesLine."Increment-by No." <= 1 THEN
    NoSeriesLine."Last No. Used" := INCSTR(NoSeriesLine."Last No. Used")
  ELSE
    IncrementNoText(NoSeriesLine."Last No. Used",NoSeriesLine."Increment-by No.");
...
```

Open for any feedback / discussion!

PS: Please make sure solution is compatible with the future 'non-locking no. series' refactoring...

**Comment by AlexanderYakunin** [comment]
We already have event implemented in this place, actually in procedure ModifyNoSeriesLine:

    local procedure ModifyNoSeriesLine(var NoSeriesLine: Record "No. Series Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeModifyNoSeriesLine(NoSeriesLine, IsHandled);
        if IsHandled then
            exit;

        NoSeriesLine.Modify;
    end;

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
