### ISSUE TITLE
[Event Request]  page 253 "Sales Journal" - OnOpenPage procedure end event request

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#23771]
We would like to request an event be put at the end of the OnOpenPage trigger of the Sales Journal page, so we can perform some additional processing with the CurrentJnlBatchName variable.  Thank you.

```
page 253 "Sales Journal"

...

    trigger OnOpenPage()
    var
        ServerSetting: Codeunit "Server Setting";
        VATReportingDateMgt: Codeunit "VAT Reporting Date Mgt";

...

        GenJnlManagement.OpenJnl(CurrentJnlBatchName, Rec);
        SetControlAppearanceFromBatch();

        OnAfterOpenPage();
        // NEW EVENT CODE BEGIN
        OnAfterOnOpenPage(CurrentJnlBatchName);
        // NEW EVENT CODE END
    end;

...

    // NEW EVENT DEF BEGIN
    [IntegrationEvent(true, false)]
    local procedure OnAfterOnOpenPage(var CurrentJnlBatchName: Code[10])
    begin
    end;
    // NEW EVENT DEF END
}

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11076.
