### ISSUE TITLE
[Key request]Table 130450 "Test Method Line"

### ISSUE THREAD

**Issue by NAVFreak** [microsoft/ALAppExtensions#23772]
Many of us partners have A LOT of automated tests that we run daily in our pipelines.
Sometimes these fails and we troubleshoot by spinning a local docker with all apps and tests.

But as you can see here we only have the name of the failed test, but if we choose the call stack we also get the object id.
![image](https://github.com/microsoft/ALAppExtensions/assets/34970096/fe7b10b6-ff4b-4e7e-9c85-dc36fdd91576)

![image](https://github.com/microsoft/ALAppExtensions/assets/34970096/edacf51f-7f36-4c61-8d76-f3ca23f0fa0e)

Now to my request. I would like that you at least adds the codeunit id to the key because it has happened several time that the client froze because it had to do scan of the table to find my records (with codeunit id filter) which is slow performance wise.
Secondarily I would also like the name in the key but I would settle with the codeunit id :)

Current keys in table 130450 "Test Method Line" are:
![image](https://github.com/microsoft/ALAppExtensions/assets/34970096/7912ac18-ef62-49b5-930f-aecbffcc2f0c)

**Comment by nikolakukrika** [comment]
Feel free to add the extra Key yourself and to create a PR on the Github. You have the setup with a lot of tests, so you can see if it does the trick. We cannot change the Key1 nor Key2, we will need a new key to fix the sorting. Page when it opens it can set the different key as the primary key I see no harm in that. 

 When we run tests we do not load many test methods in a run, we try to keep it small.

**Comment by nikolakukrika** [comment]
As stated above, please create a PR on the Github with the new key and we will review the code.
