### ISSUE TITLE
[Change request] Passing TempPurchLine into CopyFromGLAccount() procedure and OnAfterAssignGLAccountValues() event

### ISSUE THREAD

**Issue by daniel-williams-fenwick** [microsoft/ALAppExtensions#23774]
Hi Microsoft AL Development Team,

Could you please pass the TempPurchLine temporary variable as a parameter into call to CopyFromGLAccount() procedure in the "No." fields OnValidate() trigger in table 39 "Purchase Line"?

![image](https://github.com/microsoft/ALAppExtensions/assets/134581763/d1eecb3a-c645-4afa-81dc-d2345b8f4100)

![image](https://github.com/microsoft/ALAppExtensions/assets/134581763/c0a33458-df16-40fb-bb5a-e80c42c40014)

Then in the CopyFromGLAccount() procedure, could you please pass TempPurchLine into the event OnAfterAssignGLAccountValues()

![image](https://github.com/microsoft/ALAppExtensions/assets/134581763/fe4ad3ee-1b92-4ad2-becc-3216fa9c281b)

Which will require the following logic update in the OnAfterAssignGLAccountValues event:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignGLAccountValues(var PurchLine: Record "Purchase Line"; GLAccount: Record "G/L Account"; PurchHeader: Record "Purchase Header"; 
    xPurchaseLine: Record "Purchase Line"; var TempPurchLine: Record "Purchase Line" temporary)
    begin
    end;
```

Thank you.

Kind regards,
Daniel Williams

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11211.
