### ISSUE TITLE
[Event Request] table 83 "Item Journal Line" - OnBeforeCheckItemTracking

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#23784]
This new Base functionality ItemJournalBatch."Item Tracking on Lines" is giving me sleepless nights. For 20 years now I've been using "Lot No." and "Serial No." on item journal line and now our whole addon is not working anymore. No events placed by any of the  Microsoft developers to bypass this collaboration idea. Only works on item journal and not were it has the most effect: reclassification and physical inventory journals.

    local procedure CheckItemTracking(CalledByFieldNo: Integer)
    var
        FieldCap: Text;
        IsHandled: Boolean;
    begin
        //Event22.01.ns
        OnBeforeCheckItemTracking(Rec, IsHandled);
        if IsHandled then
            exit;
        //Event22.01.ne

        if not IsItemTrackingEnabledInBatch() then begin
            ClearTracking();
            ClearDates();
            exit;
        end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckItemTracking(var ItemJournalLine: Record "Item Journal Line"; IsHandled: Boolean)
    begin
        //Event22.01
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11109.
