### ISSUE TITLE
[Request] Use of Package Item Tracking CaptionClass in page actions and groups

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#23785]
Since the introduction of field(70; "Package Specific Tracking"; Boolean) in table 6502 "Item Tracking Code", it is possible to change the caption of Package in the application. table 313 "Inventory Setup" has a field field(6500; "Package Caption"; Text[30]) which enables this mostly through the use of the property CaptionClass in codeunit 6512 "Item Tracking CaptionClass Mgt".

However, this is not (yet) possible with page Groups and Actions. Something like CaptionClass = '6,7'; is not possible at the moment to use in an action or group property.
Our customers (look at the images) find it strange that unlike Lot and/or Serial no. which are using the same captions in the whole application that Package does not accomplish that.

I hope that placing this issue on this github site is the right medium. The Ideas/Collaboration route is not my favorite.

page 6510 "Item Tracking Lines":
                action("Assign Package No.")
                {
                    ApplicationArea = ItemTracking;
                    Caption = 'Assign &Package No.';
                    CaptionClass = '6,7';
                    Visible = FunctionsSupplyVisible and PackageNoVisible;
                    Image = Lot;
                    ToolTip = 'Automatically assign the required package numbers from predefined number series.';

                    trigger OnAction()
                    begin
                        if InsertIsBlocked then
                            exit;
                        AssignPackageNo();
                    end;
                }

page 6512 "Item Tracking Code Card":
            group("Package Tracking")
            {
                Caption = 'Package Tracking';
                CaptionClass = '6,7';
                Visible = PackageTrackingVisible;

![image](https://github.com/microsoft/ALAppExtensions/assets/30273162/5fad8f15-27d9-4507-8a46-b2b153ba6fcf)
![image](https://github.com/microsoft/ALAppExtensions/assets/30273162/87c7ad5b-be90-4605-a6cb-36e8d6bcb5e7)

**Comment by pri-kise** [comment]
There are already two ideas:
You should share them and gather votes to get this addressed by microsoft:
- https://experience.dynamics.com/ideas/idea/?ideaid=af85ab9f-a8db-e911-b3b9-0003ff68f1ff
- https://experience.dynamics.com/ideas/idea/?ideaid=7a727ef5-957b-ed11-a76e-0003ff45e043

Another Idea for a ToolTipClass:
- https://experience.dynamics.com/ideas/idea/?ideaid=18b6e2ec-9ea5-ea11-8b71-0003ff68c1c1

**Comment by AlexanderYakunin** [comment]
Hello! We cannot address this ask as GitHub request, as there are currently no support of CaptionClass for actions and groups. I advise to use Ideas to promote this change to platform.
