### ISSUE TITLE
Open RDLC File in Visual Studio

### ISSUE THREAD

**Issue by stephanweidmann** [microsoft/ALAppExtensions#2378]
When I open the RDLC from Visual Code, the Visual Studio opens the file and shows the layout.

But, I am missing the possibility to build the file, to check the layout against the dataset.

In NAV 2018, the visual studio was opened differently:
There where several files created, and the visual studio was opened with 3 files:
First a sln-file, then a xsd-file, then the rdlc file.
Is there a possibility to add this behaviour to visual studio, or create it in the background automatically?

Without a possibility to validate a layout, developing gets very frustrating.
the al compilier itself does not check the layout.

Or is there any other possibility to check the layout before publishing and running?

**Comment by ikoletic** [comment]
This issue is a question. Please submit your questions on [business central community ](https://community.dynamics.com/business/f/758) or on [BC development yammer groups](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035).
