### ISSUE TITLE
[Bug] Posted Sales Invoices - Print - Send to ...- PDF Document

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#23783]
Posted Sales Invoices - Print - Send to ...- PDF Document
My settings:

    Region: Czech (Czechia)
    Language: Czech (Czechia)

Customer has on the field Language code value ENU.

There is created the posted sales invoice to this customer in BC online.
I choose on this document Print - Send to ... - PDF document.

The result is that the pdf file is in the Czech language. It is wrong.
The pdf file have to be in the customer's language - i.e. ENU.

When I use print or send by email I have document in correct language. It happens in BC online only. I tested it with On-Prem BC22.1 and there is everything OK.

**Comment by pri-kise** [comment]
1. This is the wrong place for product defects in production environments.
    Use the normal support channel for this.

2. This was already reported for other localizations. (Check out yammer ) and for us this was alredy sovled

**Comment by AlexanderYakunin** [comment]
Closing bug request. Please report to support channels, not here.
