### ISSUE TITLE
[Event Request] page 5900 "Service Order" trigger OnQueryClosePage()

### ISSUE THREAD

**Issue by michaelarmanno-tnp** [microsoft/ALAppExtensions#23787]
Please can you add the following code/event to the above procedure...

```
trigger OnQueryClosePage(CloseAction: Action): Boolean
var
    IsHandled: Boolean;     //NEW CODE
begin
    IsHandled := false;     //NEW CODE
    OnBeforeOnQueryClosePage(Rec, DocumentIsPosted, IsHandled); //NEW CODE
    if IsHandled then       //NEW CODE
        exit;               //NEW CODE

    if not DocumentIsPosted then
        exit(Rec.ConfirmCloseUnposted());
end;
```

The event publisher should be as follows...

```
[IntegrationEvent(true, false)]     //SENDER = TRUE
local procedure OnBeforeOnQueryClosePage(var ServiceHeader: Record "Service Header"; var DocumentIsPosted: Boolean; var IsHandled: Boolean);
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11115.
