### ISSUE TITLE
[Event Request] Codeunit 13 "Gen. Jnl.-Post Batch"- new Event at procedure ProcessBalanceOfLines

### ISSUE THREAD

**Issue by iyiannak** [microsoft/ALAppExtensions#23797]
Hello! Note that we have extended the "General Journal" page, and we have added the "Posting No. Series" field. We would like to be able to fill in the "Posting No. Series" field with a value different than the one of the corresponding selected batch. However, this is not currently possible due to the below validation at procedure ProcessBalanceOfLines of codeunit 13
                    if "Posting No. Series" <> '' then
                        TestField("Posting No. Series", GenJnlBatch."Posting No. Series");

Therefore, it would be nice if you could add an event before this validation e.g. OnBeforePostingNoSeriesCheck(GenJnlLine,  var skipPostingNoSeriesValidation)
and also modify your code so as to take into account the skipPostingNoSeriesValidation value

i.e. something like below
OnBeforePostingNoSeriesCheck(GenJnlLine,  var skipPostingNoSeriesValidation )
if "Posting No. Series" <> '' then
    if not skipPostingNoSeriesValidation then
        TestField("Posting No. Series", GenJnlBatch."Posting No. Series");

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 57697.
