### ISSUE TITLE
GET error - Table 37 & Table 39

### ISSUE THREAD

**Issue by Halilovast** [Microsoft/ALAppExtensions#238]
Could you change the following code in tables 37 and 39:
VAT Prod. Posting Group - OnValidate()
TestStatusOpen;
**// begin 
//VATPostingSetup.GET("VAT Bus. Posting Group","VAT Prod. Posting Group");
IF NOT VATPostingSetup.GET("VAT Bus. Posting Group","VAT Prod. Posting Group") THEN
  VATPostingSetup.INIT;
// end**

**Comment by JesperSchulz** [comment]
Issue closed by @AlexanderYakunin.
