### ISSUE TITLE
[Event Request] Application “Tests-ERM”, Codeunit 134152 "ERM Intercompany II"

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#23804]
[Event Request]Application “Tests-ERM”, Codeunit 134152 "ERM Intercompany II"

Could you please insert the Initialize procedure or raise the OnTestInitialize-Event at the beginning of the procedures 
•	PurchaseOrderToPurchaseInvoicePostBothInvoiceFirst
•	PurchaseOrderToPurchaseInvoicePostBothOrderFirst

![pic1](https://github.com/microsoft/ALAppExtensions/assets/45795262/de4b2ef1-972c-4c8f-891a-9652293001d3)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11320.
