### ISSUE TITLE
Microsoft Invoicing Module

### ISSUE THREAD

**Issue by peterslabiak** [microsoft/ALAppExtensions#23801]
Hi' Microsoft,

Can you offer a timeline for the deprecation of the Microsoft Invoicing Module i.e. "O365 Sales Invoice Mgmt" etc.?

https://learn.microsoft.com/en-us/dynamics365/business-central/application/base-application/codeunit/base-application-codeunit-o365-sales-invoice-mgmt

**Comment by JakovljevicDusan** [comment]
Hi,

As this is obsolete/discontinued from v21, it will be removed in v24 (2024 Wave 1).
