### ISSUE TITLE
[Event request] Passing TempSalesLine into CopyFromGLAccount() procedure and OnAfterAssignGLAccountValues() event

### ISSUE THREAD

**Issue by daniel-williams-fenwick** [microsoft/ALAppExtensions#23808]
Hi Microsoft AL Development Team,

Could you please pass the TempSalesLine variable as a parameter into the call to CopyFromGLAccount() procedure in the "No." field's OnValidate() trigger in table 37 "Sales Line"?

![image](https://github.com/microsoft/ALAppExtensions/assets/134581763/0be35229-fa6e-49cd-80f2-9c055e8d699f)

![image](https://github.com/microsoft/ALAppExtensions/assets/134581763/77287a41-5cc7-4e72-9af4-8ee27e28704d)

Then in the CopyFromGLAccount() procedure, could you please pass TempSalesLine into the event OnAfterAssignGLAccountValues()

![image](https://github.com/microsoft/ALAppExtensions/assets/134581763/0ef24e43-886b-4907-8883-3266fab26dea)

Which will require the following logic update in the OnAfterAssignGLAccountValues event:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterAssignGLAccountValues(var SalesLine: Record "Sales Line"; GLAccount: Record "G/L Account"; SalesHeader: Record "Sales Header";
    TempSalesLine: Record "Sales Line")
    begin
    end;
```

Thank you.

Kind regards,
Daniel Williams

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11199.
