### ISSUE TITLE
Can not filtering for empty time value with ODataV4

### ISSUE THREAD

**Issue by HegedusZsolt** [microsoft/ALAppExtensions#23810]
To reproduce, 
- publish the page 9318 as ODataV4 web service with name ServiceOrders
- create a new service order in the web client (no need to fill anything, just get the number)
- make sure the Response Time field is empty
- try to filter for this record with an ODataV4 url e.g. in Postman like this (<your_url>/ServiceOrders?$filter=%28Response_Time%20eq%20%2700%3A00%3A00%27%29)
- the result will be empty, the OData can't find the record

The reason is, the Response Time is initialized with 0T by default, but if you validate 000000T into the filed the previous filtering method will works.

It's really annoying, because the JSON response is 00:00:00 in both cases, so I can't differentiate in between, and I also don't know how can I filter to the empty value.

**Comment by onbuyuka** [comment]
You can filter by ServiceOrders?$filter='Response_Time' eq null

**Comment by HegedusZsolt** [comment]
> You can filter by ServiceOrders?$filter='Response_Time' eq null

I've tried. Response contains the whole, unfiltered record set.

Original issue still exist. Json response has 00:00:00 in case of 12:00 AM and empty value as well.

**Comment by onbuyuka** [comment]
Reactivating and creating an internal work item to follow

**Comment by carldybdahl-microsoft** [comment]
Oh, and this requires `$schemaversion=2.1`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
