### ISSUE TITLE
[Event Request] Codeunit 5980 Service-Post

### ISSUE THREAD

**Issue by fmoric** [microsoft/ALAppExtensions#23819]
Hi, 

in Codeunit 5980 Service-Post in procedure PostWithLines there is subscriber OnBeforePostWithLines that has IsHandled boolean witch skips whole posting code and the last subscriber has just Service Header as parameter, so there is no way to know what happened at the end of posting.

It has been added in issue: https://github.com/microsoft/ALAppExtensions/issues/17766 .

At least there could be IsHandeled in OnAfterPostWithLines(PassedServHeader, IsHandeled) at the end so that we can know that the code was skipped.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11199.
