### ISSUE TITLE
[Event Change Request] table 130 "Incoming Document" OnCreatePurchDocOnBeforeShowRecord

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23814]
Could you please pass the paramter `IncomingDocument: Record "Incoming Document"`  by reference instead of by value?
```al
[IntegrationEvent(false, false)]
//+Change
//-local procedure OnCreatePurchDocOnBeforeShowRecord(IncomingDocument: Record "Incoming Document"; var IsHandled: Boolean)
local procedure OnCreatePurchDocOnBeforeShowRecord(var IncomingDocument: Record "Incoming Document"; var IsHandled: Boolean)
//-Change
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11199.
