### ISSUE TITLE
[Request for External] codeunit 1034 "Job Planning Line - Calendar" variable ProjectManagerResource

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#23827]
The above event was added in BC22.2 as requested in https://github.com/microsoft/ALAppExtensions/issues/23353 - so thankyou.

However I did make a small edit to add an extra parameter which didn't make it through.  I need to change the global ProjectManagerResource so I requested that this be added as a parameter to the event but thinking about it now, it would be better to just make it a protected var.  

Can you please make ProjectManagerResource a protected var?

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 58698.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11479.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 58698.
