### ISSUE TITLE
Event Request codeunit "Whse. Activity Register" in procedure  CheckSourceDocumentForAvailableQty

### ISSUE THREAD

**Issue by rickblommetjes** [microsoft/ALAppExtensions#23828]
Finally upgrade some complex customers to BC22, but ran into a new check preventing them to pick more then required on production order consumption and Job Consumption. Its almost impossible to out run this new test in codeunit Whse. Activity Register.  The test is added in BC22 and was not there in BC21.5

 
local procedure CheckSourceDocumentForAvailableQty(var GroupedWhseActivLine: Record "Warehouse Activity Line")
    var
        SourceProdOrderComp: Record "Prod. Order Component";
        SourceJobPlanningLine: Record "Job Planning Line";
        UOMMgt: Codeunit "Unit of Measure Management";
        RemainingQtyBase: Decimal;
        RemainingQtyUoM: Code[10];
<<< Start
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckSourceDocumentForAvailableQty(GroupedWhseActivLine, IsHandled);
        if IsHandled then exit;
>>> End

        GroupedWhseActivLine.SetRange("Breakbulk No.", 0);
        if GroupedWhseActivLine.FindSet() then
            repeat
                case GroupedWhseActivLine."Source Document" of
                    "Warehouse Activity Source Document"::"Prod. Consumption":
                        begin
                            SourceProdOrderComp.SetLoadFields("Remaining Qty. (Base)", "Unit of Measure Code");
                            SourceProdOrderComp.Get(GroupedWhseActivLine."Source Subtype", GroupedWhseActivLine."Source No.", GroupedWhseActivLine."Source Line No.", GroupedWhseActivLine."Source Subline No.");
                            RemainingQtyBase := SourceProdOrderComp."Remaining Qty. (Base)";
                            RemainingQtyUoM := SourceProdOrderComp."Unit of Measure Code";
                        end;
                    "Warehouse Activity Source Document"::"Job Usage":
                        begin
                            SourceJobPlanningLine.SetCurrentKey("Job Contract Entry No.");
                            SourceJobPlanningLine.SetRange("Job Contract Entry No.", GroupedWhseActivLine."Source Line No.");
                            SourceJobPlanningLine.SetLoadFields("Remaining Qty. (Base)", "Unit of Measure Code");
                            SourceJobPlanningLine.FindFirst();
                            RemainingQtyBase := SourceJobPlanningLine."Remaining Qty. (Base)";
                            RemainingQtyUoM := SourceJobPlanningLine."Unit of Measure Code";
                        end;
                end;
                if UOMMgt.CalcBaseQty(GroupedWhseActivLine."Qty. to Handle", GroupedWhseActivLine."Qty. per Unit of Measure") > RemainingQtyBase then
                    Error(ItemAlreadyConsumedErr, RemainingQtyBase, RemainingQtyUoM, GroupedWhseActivLine.FieldCaption("Line No."), GroupedWhseActivLine."Line No.", GroupedWhseActivLine.FieldCaption("Item No."), GroupedWhseActivLine."Item No.", GroupedWhseActivLine."Source Document", GroupedWhseActivLine."Source No.", GroupedWhseActivLine.FieldCaption("Source Line No."), GroupedWhseActivLine."Source Line No.");
            until GroupedWhseActivLine.Next() = 0;
        GroupedWhseActivLine.SetRange("Breakbulk No.");
    end;

OnBeforeCheckSourceDocumentForAvailableQty(GroupedWhseActivLine: Record "Warehouse Activity Line", IsHandled : Boolean);

They all need it because they have to move/pick the whole lot no. to the machine to be processed, the remaining qty's are returned to stock. Any Idea how we quickly can add an event to skip this test?

**Comment by AleksandricMarko** [comment]
Hello @rickblommetjes 
I am not sure that I understand...
The event is already added in BC 22 (build 22.2.56698.0)

You want to add it in BC 21.5?
Or you have a problem because event OnBeforeCheckSourceDocumentForAvailableQty is added?

**Comment by rickblommetjes** [comment]
No it's blocking customers right noe, after the update from BC21.5.

I need a way to skip the test at least in BC22.3!!!! Because the customers are impacted after the update from BC21.5

**Comment by AleksandricMarko** [comment]
Hi @rickblommetjes 
Could you please explain how is customer blocked with the event?
