### ISSUE TITLE
[Event Request] Report 5854 "Roll Up Standard Cost"

### ISSUE THREAD

**Issue by Rihmz12** [microsoft/ALAppExtensions#23820]
I would like to request the following event:
Object: RollUpStandardCost.Report.al
Trigger: OnPreDataItem of DataItem "Item"
Where the event should be placed:

            trigger OnPreDataItem()
            begin
                StdCostWksh.LockTable();
                Clear(CalcStdCost);
                CalcStdCost.SetProperties(CalculationDate, true, false, false, ToStdCostWkshName, true);
                CalcStdCost.CalcItems(Item, TempItem);

                TempItem.SetFilter("Replenishment System", '%1|%2',
                  TempItem."Replenishment System"::"Prod. Order",
                  TempItem."Replenishment System"::Assembly);
                OnPreDataItemOnAfterSetTempItemFilter(TempItem);
                if TempItem.Find('-') then
                    repeat
                        UpdateStdCostWksh;
                        RolledUp := true;
                    until TempItem.Next() = 0;
            end;

Event Code:

    [IntegrationEvent(false, false)]
    local procedure OnPreDataItemOnAfterSetTempItemFilter(var TempItem: Record Item temporary)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11199.
