### ISSUE TITLE
[Access Request] 5753 "Get Source Documents"

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#23826]
Could you please change the following variables to protected?

```al
var
    OneHeaderCreated: Boolean;
    LineCreated: Boolean;
    WhseHeaderCreated: Boolean;
    SkipBlockedCustomer: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
