### ISSUE TITLE
QueryCategory in Job List page

### ISSUE THREAD

**Issue by Mario-Sopena** [microsoft/ALAppExtensions#23831]
Hello team,
I think it would be very usefull to include this property in this list page.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13074.
