### ISSUE TITLE
[Event Change Request] Add IsHandled to OnPrepareOrderToOrderLinkOnBeforeInventoryProfileModify, function PrepareOrderToOrderLink on codeunit 99000854 "Inventory Profile Offsetting"

### ISSUE THREAD

**Issue by jmartin93** [microsoft/ALAppExtensions#23830]
Hi, we asked for a change on an event and it was accepted #22911 but the code is still missing on BC 22.2 and 21.8

```
OnPrepareOrderToOrderLinkOnBeforeInventoryProfileModify(InventoryProfile, TempSKU);
InventoryProfile.Modify();
```

**Comment by AleksandricMarko** [comment]
Hello @jmartin93 
We are not adding new events in BC21
About 22.2 yes you are right, change is not integrated, it should be part of next minor releases.
