### ISSUE TITLE
Codeunit 7307 - Whse.-Activity-Register - OnBeforeCheckSourceDocumentForAvailableQty new event

### ISSUE THREAD

**Issue by DParkerRSM** [microsoft/ALAppExtensions#23832]
I am working on a modification that allows users to pick more than is required for a production order but I have run into an error in the CheckSourceDocumentForAvailableQty function in the Whse.-Activity-Register codeunit 7307. The user would pick more than is requested and then post consumption for actual usage. The user would then return unused inventory to the warehouse via a movement. 

local procedure CheckSourceDocumentForAvailableQty(var GroupedWhseActivLine: Record "Warehouse Activity Line")
    var
        SourceProdOrderComp: Record "Prod. Order Component";
        SourceJobPlanningLine: Record "Job Planning Line";
        UOMMgt: Codeunit "Unit of Measure Management";
        RemainingQtyBase: Decimal;
        RemainingQtyUoM: Code[10];
Add >>
IsHandled: Boolean;
<< Add <<
    begin

Add >>
OnBeforeCheckSourceDocumentForAvailableQty(GroupedWhseActivLine, IsHandled);
If IsHandled then
exit();
<< Add <<

        GroupedWhseActivLine.SetRange("Breakbulk No.", 0);
        if GroupedWhseActivLine.FindSet() then
            repeat
                case GroupedWhseActivLine."Source Document" of
                    "Warehouse Activity Source Document"::"Prod. Consumption":
                        begin
                            SourceProdOrderComp.SetLoadFields("Remaining Qty. (Base)", "Unit of Measure Code");
                            SourceProdOrderComp.Get(GroupedWhseActivLine."Source Subtype", GroupedWhseActivLine."Source No.", GroupedWhseActivLine."Source Line No.", GroupedWhseActivLine."Source Subline No.");
                            RemainingQtyBase := SourceProdOrderComp."Remaining Qty. (Base)";
                            RemainingQtyUoM := SourceProdOrderComp."Unit of Measure Code";
                        end;
                    "Warehouse Activity Source Document"::"Job Usage":
                        begin
                            SourceJobPlanningLine.SetCurrentKey("Job Contract Entry No.");
                            SourceJobPlanningLine.SetRange("Job Contract Entry No.", GroupedWhseActivLine."Source Line No.");
                            SourceJobPlanningLine.SetLoadFields("Remaining Qty. (Base)", "Unit of Measure Code");
                            SourceJobPlanningLine.FindFirst();
                            RemainingQtyBase := SourceJobPlanningLine."Remaining Qty. (Base)";
                            RemainingQtyUoM := SourceJobPlanningLine."Unit of Measure Code";
                        end;
                end;
                if UOMMgt.CalcBaseQty(GroupedWhseActivLine."Qty. to Handle", GroupedWhseActivLine."Qty. per Unit of Measure") > RemainingQtyBase then
                    Error(ItemAlreadyConsumedErr, RemainingQtyBase, RemainingQtyUoM, GroupedWhseActivLine.FieldCaption("Line No."), GroupedWhseActivLine."Line No.", GroupedWhseActivLine.FieldCaption("Item No."), GroupedWhseActivLine."Item No.", GroupedWhseActivLine."Source Document", GroupedWhseActivLine."Source No.", GroupedWhseActivLine.FieldCaption("Source Line No."), GroupedWhseActivLine."Source Line No.");
            until GroupedWhseActivLine.Next() = 0;
        GroupedWhseActivLine.SetRange("Breakbulk No.");
    end;

Add >>
[IntegrationEvent(false, false)]
OnBeforeCheckSourceDocumentForAvailableQty(var GroupedWhseActivLine: Record "Warehouse Activity Line", var IsHandled: Boolean)
begin
end;
<< Add <<

**Comment by AleksandricMarko** [comment]
Hello @DParkerRSM 

event OnBeforeCheckSourceDocumentForAvailableQty already implemented - BC 22.2
