### ISSUE TITLE
[Scope Request] table 5093 "Opportunity Entry" - remove OnPrem Scope, function InsertEntry

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#23838]
Please remove the OnPrem Scope from the function InsertEntry in the table 5093 "Opportunity Entry". I do not see a single reason why would this function be limited to OnPrem development.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
