### ISSUE TITLE
[Events Request] Codeunit 85 "Sales Post Batch via Job Queue" - OnBeforeSetJobQueueStatus and OnEnqueueJobEntryOnBeforeEnqueue

### ISSUE THREAD

**Issue by iti-michal-lyduch** [microsoft/ALAppExtensions#23849]
Hi AL-Team,

Because of customizations for our customer, we'd need new publishers in CU 85 ("Sales Post Batch via Job Queue").

Publishers we need would be the same as two ones in CU 88 ("Sales Post via Job Queue"):
- OnBeforeSetJobQueueStatus(SalesHeader: Record "Sales Header"; NewJobQueueStatus: Option " ","Scheduled for Posting",Error,Posting; JobQueueEntry: Record "Job Queue Entry")
- OnEnqueueJobEntryOnBeforeEnqueue(SalesHeader: Record "Sales Header"; var JobQueueEntry: Record "Job Queue Entry")

So we would need them in procedures "EnqueueJobEntry" and "SetJobQueueStatus"

**Comment by AleksandricMarko** [comment]
Hello @MichLyd92 
Please review your request.
Procedure 'EnqueueJobEntry' not exist in codeunit 85
procedure SetJobQueueStatus does not have access to a JobQueueEntry: Record "Job Queue Entry"

Be aware that we are adding events just in 22.x (next 22.3) and master branches.

**Comment by MichLyd92** [comment]
Hello @AleksandricMarko
thank you for your answer and comments, plesea review my feedback below:
- Procedure with same name does not exist in CU 85 but there is a similiar one called 'EnqueueJobQueueEntry', we'd need a publisher there, before "Codeunit.Run(Codeunit::"Job Queue - Enqueue", JobQueueEntry)", is it okay for you to add one? 
- Couldn't the access be added to the procedure and then the publisher inside it? The procedure is being used localy in 'PostSalesBatch' and there is a "Job Queue Entry" variable so access could be easily added.

I am aware of it, therefore would be nice if you could let me know if you'll be able add them at the next occasion.
