### ISSUE TITLE
[Scope Request] table 5092 Opportunity - remove OnPrem Scope, function FinishWizard

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#23841]
Please remove the OnPrem Scope from the function FinishWizard in the table 5092 Opportunity. I do not see a single reason why this function would be limited to OnPrem development.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
