### ISSUE TITLE
Codeunit 1290 "SOAP Web Service Request Mgt.". Why not usable in SaaS?

### ISSUE THREAD

**Issue by JavierFuentes** [microsoft/ALAppExtensions#23858]
We wonder why this codeunit to manage SOAP requests and responses cannot be used in SaaS because it has its main global procedures with `[Scope('OnPrem')]`:

- SendRequestToWebService()
- GetResponseContent()
- ProcessFaultResponse()

![image](https://github.com/microsoft/ALAppExtensions/assets/5801847/c07ea48f-e14f-448e-956f-de6d62c161ab)

Is there another codeunit alternative for SaaS?

PD.- To avoid answers that do not provide solutions indicating that SOAP is obsolete, the external system with which we have to communicate requires SOAP and on the other hand we have the **Universal Code Initiative from Microsoft** that forces us to setup `target = Cloud` in our extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15201.
