### ISSUE TITLE
[Event Request] Codeunit 5720 "Item Reference Management" - OnValidateSalesReferenceNoOnBeforeAssignNo (BaseApp_22.0)

### ISSUE THREAD

**Issue by tg-navcom** [microsoft/ALAppExtensions#23852]
Please add VAR to `ReturnedItemReference` in procedure `OnValidateSalesReferenceNoOnBeforeAssignNo` in `Codeunit 5720 "Item Reference Management"`
Change:
```al
    [IntegrationEvent(false, false)]
-   local procedure OnValidateSalesReferenceNoOnBeforeAssignNo(var SalesLine: Record "Sales Line"; ReturnedItemReference: Record "Item Reference");
+   local procedure OnValidateSalesReferenceNoOnBeforeAssignNo(var SalesLine: Record "Sales Line"; var ReturnedItemReference: Record "Item Reference");
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11238.
