### ISSUE TITLE
[Extensibility-bug] page 5600 "Fixed Asset Card"

### ISSUE THREAD

**Issue by ArvinNube** [microsoft/ALAppExtensions#23855]
Hi,
when i try to change the "FA Subclass Code", the code fails, saying the record "FA Depreciation Book" with "Depreciation Book Code" same as the one in "FA Setup" already exists. This is because it tries to insert it without checking if it already exists

![2023-06-19 11_59_03-Fixed Asset Card dal - NBT_OriginsCoreWW_AppSource - Visual Studio Code](https://github.com/microsoft/ALAppExtensions/assets/120565645/0fd74025-e30c-42c7-8b34-662b042501dd)

one more thing, the update of the "FA Posting Group" field is missing
of the "FA Depreciation Book" records linked to the "Fixed Asset"

Thanks

**Comment by ArvinNube** [comment]
news?

**Comment by AlexanderYakunin** [comment]
Hello! You are using wrong place to submit this request. This is functional issue, we need to know context and repro steps to understand what are you doing here. We also need something to write/update our test automation. We cannot process this kind of requests here properly, as we have another team fixing functional issues together with Customer support team. 

Please create hotfix requests using support channels and it will be fixed for next minor.

**Comment by ArvinNube** [comment]
could you give me a link where to report such a problem? Thank you

**Comment by AlexanderYakunin** [comment]
You can create support requests here:

https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f
