### ISSUE TITLE
[Bug] Page "Word Template Creation Wizard" (9995) - missing variable update leads to an error

### ISSUE THREAD

**Issue by cscheidsteff** [microsoft/ALAppExtensions#23867]
the number of fields that can be added to a Word Template in the "Word Template Creation Wizard"(9995) is limited to 250. This is checked in the integrated page part "Word Templates Related Part"(9987). However, the global variable `SelectedFieldsCount `used for the check is calculated only once and is not updated afterwards. 

```
    local procedure CalculateSelectedFields()
    var
        WordTemplateFieldSelection: Codeunit "Word Template Field Selection";
    begin
        if not SelectedFieldsCount.Get(Rec."Related Table ID", NumberOfSelectedFields) then begin // Cache custom fields since code may be executed on every call.
            NumberOfSelectedFields := WordTemplateFieldSelection.CalculateNoSelectedFields(Rec."Related Table ID", TempWordTemplateField);
            SelectedFieldsCount.Add(Rec."Related Table ID", NumberOfSelectedFields);
        end;
    end;
```

This leads to an error message even after reducing the number of selected fields by deleting entities or deselecting fields. Thus you will not be able to continue with the creation of the template (see screenshots below)

1.
![image](https://github.com/microsoft/ALAppExtensions/assets/105804990/0fdc2fc1-f24b-4e0b-a830-b1e41baa8aef)

2.
![image](https://github.com/microsoft/ALAppExtensions/assets/105804990/f4df09ca-5ddb-4099-a768-0d2a7a4bd7fb)

**Comment by JesperSchulz** [comment]
Sorry about the long reply-time on this issue. I wasn't aware that this many bugs had been filed here, and hence wasn't monitoring this repo.

This repository is normally only for extensibility requests for Dynamics 365 Business Central or pull requests towards the 1st party Business Central apps.

But I'll make an exception and log this issue as an internal bug, as this issue isn't critical.

Thanks for reporting!
