### ISSUE TITLE
[Event Request] codeunit 10085 "A/P Magnetic Media Management" - OnRun ending event request

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#23862]
Hello!  We are needing to add an event to the OnRun trigger of the A/P Mag Media Management codeunt.  We need to add an extra code for the 1099 NEC handling, and are requesting either an event be added (coded below), or if possible, just the line added to set the value in the array (NEC-02, noted below as well).  Thanks!

```
codeunit 10085 "A/P Magnetic Media Management"
{
    trigger OnRun()
    begin
        // Fill in the Codes used for 1099's
....
        Codes[4, 1] := 'NEC-01';
        Codes[4, 2] := 'NEC-02';  // << This is the code we are needing
        Codes[4, 4] := 'NEC-04';

        //event begin
        OnAfterInitCodeValues(Codes);
        //event end
    end;

....


    //event begin
    [IntegrationEvent(false, false)]
    local procedure OnAfterInitCodeValues(var Codes: array[4, 30] of Code[10]);
    begin
    end;
    //event end
}

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11238.
