### ISSUE TITLE
Make AzureAdMgt.GetAccessToken and UrlHelper.GetGraphUrl accessible

### ISSUE THREAD

**Issue by Gerdna** [microsoft/ALAppExtensions#23868]
Hello, 

we want to create a Mail Logging Application based on the graph api similar to the EmailLogging App. The EmailLogging App is not extensible and we have some different demands, so we can not use it. Therefore we created an own implementation in our app. 

I now have the issue that the procedure to get the AccessToken on a BC Online Environment have the scope OnPrem. The implementation is based on `codeunit 1686 "Email Logging OAuth Client"` and the issue occurs in `local procedure TryGetAccessTokenInternal(var AccessToken: Text)`. The following procedures have Scope OnPrem:
- `codeunit 6300 "Azure AD Mgt." - GetAccessToken`
- `codeunit 9005 "Url Helper" - procedure GetGraphUrl(): Text`

As a workaround I used the accessible procedure in the `Email - Outlook REST API` App in `codeunit 4507 "Email - OAuth Client"`, but it would be nice to not have the dependency on this app just for the purpose of getting the access token. 

Can you tell me if it is the intended way to get the Access Token with the procedure in the `Email - Outlook REST API` App? Or do you think it would make sense to make the needed procedures accessible? I could provide a PR to remove the Scope if it helps :)

Thanks in advance
Internal work item: [AB#524054](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524054)

**Comment by darjoo** [comment]
Hi @Gerdna, I'm sorry but we cannot open up the `GetAccessToken` procedure due to security reasons.

The `Email - Outlook REST API` wasn't meant to divulge the access token either, and that has been closed since. If you need to access Mail resources, you'd need to create an app which would request for the necessary permissions from the user.
