### ISSUE TITLE
[Event Request] codeunit 415 "Release Purchase Document" - OnAfterPerformManualCheckAndRelease

### ISSUE THREAD

**Issue by wweidl** [microsoft/ALAppExtensions#23860]
Please add a new Publisher Call OnAfterPerformManualCheckAndRelease in Fct. PerformManualCheckAndRelease of codeunit 415 "Release Purchase Document"

Add Publisher Call in Fct. PerformManualCheckAndRelease:
````
        IsHandled := false;
        OnBeforePerformManualRelease(PurchHeader, PreviewMode, IsHandled);
        if IsHandled then
            exit;

        CODEUNIT.Run(CODEUNIT::"Release Purchase Document", PurchHeader);
		
+      OnAfterPerformManualCheckAndRelease(PurchHeader);
    end;
````

Add new Publisher:
````
+   [IntegrationEvent(false, false)]
+   local procedure OnAfterPerformManualCheckAndRelease(var PurchHeader: Record "Purchase Header")
+   begin
+   end;
````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
