### ISSUE TITLE
[Event Requests] Codeunit 7322 - Create Inventory Pick/Movement 

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#23875]
in our business solution there is the possibility to define serial no. >1 for an item.

To implement this properly we need two new Events and one change of a local function to a global one.
The global function is created in issue #23368 

the two publishers would be:
1.
In function InsertPickOrMoveBinWhseActLine there is a check for 'if WhseItemTrackingSetup. "Serial No. Required" then begin'
before the repeat until loop we need a chance to skip the loop.
I suggest to call the subcriber OnBeforeMakeLineWhenSNoReq(NewWhseActivLine, WhseItemTrackingSetup, FromBinContent."Bin Code", QtyToPickBase, RemQtyToPickBase, QtyAvailToPickBase, IsHandled);
![image](https://github.com/microsoft/ALAppExtensions/assets/9529836/0d2f162b-26d6-46ee-b961-5825e19b754d)

![image](https://github.com/microsoft/ALAppExtensions/assets/9529836/ea74b3e4-c0a2-4f91-b0fc-d5f1972b598b)

Important is the IncludeSender Attribute.
2.
we need the same in function InsertShelfWhseActivLine
So i ask for a new Subcriber OnBeforeMakeShelfLineWhenSNoReq(NewWhseActivLine, WhseItemTrackingSetup, QtyToPickBase, RemQtyToPickBase, IsHandled);
after the "Serial No. Required" check.
![image](https://github.com/microsoft/ALAppExtensions/assets/9529836/55d035a3-25eb-4343-8deb-18cb752ef906)

![image](https://github.com/microsoft/ALAppExtensions/assets/9529836/ecf67153-1012-42e7-992a-ad9d264394a1)

IncludeSender must also be set here

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11255.
