### ISSUE TITLE
[Request for External] page 233 "Apply Vendor Entries" - Protected variables

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#23878]
Could you please change the Access scope of the following variables to protected?

```	
protected var
VendEntryApplID: Code[50];
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
