### ISSUE TITLE
[Request-For-External] codeunit 5707 "TransferOrder-Post + Print" - Procedure Suffix

### ISSUE THREAD

**Issue by SomeWaterFlow** [microsoft/ALAppExtensions#23883]
Dear ALAppExtension Team,
we would need some changes in codeunit 5707 "TransferOrder-Post + Print":

```
-    local procedure PrintShipment(DocNo: Code[20])
+    procedure PrintShipment(DocNo: Code[20])
      [...]

-    local procedure PrintReceipt(DocNo: Code[20])
+    procedure PrintReceipt(DocNo: Code[20])
      [...]

-    local procedure PrintDirectTransfer(DocNo: Code[20])
+    procedure PrintDirectTransfer(DocNo: Code[20])
      [...]
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
