### ISSUE TITLE
[Event Request] OnBeforeCopyDocumentAttachments CU 74 Purch.-Get Receipt

### ISSUE THREAD

**Issue by JPicard90** [microsoft/ALAppExtensions#23886]
Hi
Could you please update this function in CU 74 Purch.-Get Receipt
local procedure CopyDocumentAttachments(OrderNoList: List of [Code[20]]; var PurchaseHeader: Record "Purchase Header")

adding this lines of code:
```
    local procedure CopyDocumentAttachments(OrderNoList: List of [Code[20]]; var PurchaseHeader: Record "Purchase Header")
    var
        [..]
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCopyDocumentAttachments(OrderNoList,PurchaseHeader,IsHandled);
        If IsHandled then
            exit;
        [...]
     end
```
and adding the event at the end of codeunit:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCopyDocumentAttachments(var OrderNoList: List of [Code[20]]; var PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11255.
