### ISSUE TITLE
[Event Request] Report 5753 Get Source Documents - OnBeforePostReport

### ISSUE THREAD

**Issue by VMotin** [microsoft/ALAppExtensions#23880]
Hi, would it be possible to add the parameter WhseReceiptLine in OnBeforePostReport, like this : 

    trigger OnPostReport()
    begin
        OnBeforePostReport("Warehouse Request", RequestType, OneHeaderCreated, WhseShptHeader, WhseHeaderCreated, ErrorOccured, LineCreated, ActivitiesCreated, Location, WhseShptLine, WhseReceiptHeader, HideDialog, WhseReceiptLine);
        if not HideDialog then
            case RequestType of
                RequestType::Receive:
                    ShowReceiptDialog();
                RequestType::Ship:
                    ShowShipmentDialog();
            end;
        if SkippedSourceDoc > 0 then
            Message(CustomerIsBlockedMsg, SkippedSourceDoc);
        Completed := true;

        OnAfterPostReport("Warehouse Request", RequestType, OneHeaderCreated, WhseShptHeader, WhseHeaderCreated, ErrorOccured, LineCreated, ActivitiesCreated, Location, WhseShptLine);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostReport(WhseRequest: Record "Warehouse Request"; RequestType: Option; OneHeaderCreated: Boolean; var WhseShptHeader: Record "Warehouse Shipment Header"; var WhseHeaderCreated: Boolean; var ErrorOccured: Boolean; var LineCreated: Boolean; var ActivitiesCreated: Integer; Location: record Location; var WhseShptLine: record "Warehouse Shipment Line"; var WhseReceiptHeader: Record "Warehouse Receipt Header"; var HideDialog: Boolean; var WhseReceiptLine : record "Warehouse Receipt Line")
    begin
    end;

?

Thanks for your work

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11255.
