### ISSUE TITLE
New field "Registration text" in Company Information

### ISSUE THREAD

**Issue by abgrau** [microsoft/ALAppExtensions#23885]
We can't use the "Registration No." field, we need it to be larger, for exemple a text of 250 characters.
So, we need other field named "Registration text"

**Comment by pri-kise** [comment]
This repository isn't meant for new fields for some custom specific field requirents.

If this is some regulatory requirement for a specific country, then you should provide some more details otherwise create in your PTE by yourself.

**Comment by RadoArvay** [comment]
...or create a new Idea.

**Comment by AlexanderYakunin** [comment]
Please add field in your extension if you need it. If this is regulatory requirement, please create new Idea and it will be taken by Regulatory Feature team.
