### ISSUE TITLE
[Event Request] Table 37"Sales Line" - Procedure "UpdateVATAmounts"

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#23894]
Dear ALAppExtensions Team,

We would like to request the following change

-------------------------------------------------

    if SalesHeader."Prices Including VAT" then
      
      -------------------------------------------------

    else
      case "VAT Calculation Type" of
          "VAT Calculation Type"::"Normal VAT",
          "VAT Calculation Type"::"Reverse Charge VAT":
              begin
                  Amount := Round(CalcLineAmount(), Currency."Amount Rounding Precision");
                  "VAT Base Amount" :=
                    Round(Amount * (1 - GetVatBaseDiscountPct(SalesHeader) / 100), Currency."Amount Rounding Precision");
                  "Amount Including VAT" :=
                    TotalAmount + Amount +
                    Round(
                      (TotalAmount + Amount) * (1 - GetVatBaseDiscountPct(SalesHeader) / 100) * "VAT %" / 100,
                      Currency."Amount Rounding Precision", Currency.VATRoundingDirection()) -
                    TotalAmountInclVAT + TotalVATDifference;
                    **//--> event request
                    OnUpdateVATAmountsOnAfterCalculateNormalVAT(Rec, Currency);
                    **//<-- event request
              end;
          "VAT Calculation Type"::"Full VAT":
              begin
                  Amount := 0;
                  "VAT Base Amount" := 0;
                  "Amount Including VAT" := CalcLineAmount();
              end;
    
            ----------------------------------------------

        **//--> event request
        [IntegrationEvent(false, false)]
        local procedure OnUpdateVATAmountsOnAfterCalculateNormalVAT(var SalesLine: Record "Sales Line"; var Currency: Record Currency)
        begin
        end;
        **//<-- event request

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11267.
