### ISSUE TITLE
[Request-for-External] codeunit 1696 (Entry Application Mgt) make procedures external

### ISSUE THREAD

**Issue by ekesteloot** [microsoft/ALAppExtensions#23892]
Please make the GetAppliedCustEntries and GetAppliedVendEntries procedures in codeunit 1696 (Entry Application Mgt) external.  

We would like to call them from our own version of the "Bank Deposit" report.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11478.
