### ISSUE TITLE
[Application] Provide ForceUpdateContact on Vendor similar to Customer

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#23890]
The IsContactUpdateNeeded function on Customer table has force support via the ForceUpdateContact global. This behavior is not mirrored on the Vendor table. Please provide same support for Vendors too.

![image](https://github.com/microsoft/ALAppExtensions/assets/25268332/bc4f4118-873d-4ac7-9647-c804c1861332)

- Update IsContactUpdateNeeded with 

```
 if ForceUpdateContact then
            UpdateNeeded := true;
```

- Add parameter to OnBeforeIsContactUpdateNeeded

```
 [IntegrationEvent(false, false)]
    local procedure OnBeforeIsContactUpdateNeeded(Customer: Record Customer; xCustomer: Record Customer; var UpdateNeeded: Boolean; ForceUpdateContact: Boolean)
    begin
    end;
```

- Add SetForceUpdateContact function

```
procedure SetForceUpdateContact(NewForceUpdateContact: Boolean)
    begin
        ForceUpdateContact := NewForceUpdateContact;
    end;
```

- Update OnInsert trigger

```
if (not (InsertFromContact or (InsertFromTemplate and (Contact <> '')) or IsTemporary)) or ForceUpdateContact then
            UpdateContFromCust.OnInsert(Rec);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13701.
