### ISSUE TITLE
[Bug] Service Management: Quantity Shipped not updated after posting 

### ISSUE THREAD

**Issue by simonmeulebrouck** [microsoft/ALAppExtensions#23891]
After shipping Service Lines, the Quantity Shipped is not updated, however the shipment is created succesfully. 

![image](https://github.com/microsoft/ALAppExtensions/assets/137303955/fcf5ecc0-a3ea-40a3-ad7e-737af1fc723b)

It is even possible to undo the shipment, which will result in a negative "Quantity Shipped" and a "Qty. to Ship" which will be greater than the quantity. 

![image](https://github.com/microsoft/ALAppExtensions/assets/137303955/10c268f0-7685-46c9-94f1-4ca8fd23eb68)

**Comment by developerchristiaens** [comment]
Issue can be closed
