### ISSUE TITLE
[Property Request] Codeunit 63 Sales-Explode BOM - HideDialog

### ISSUE THREAD

**Issue by billyfuTC** [Microsoft/ALAppExtensions#239]
We need to explode BOM item in Sales Orders via Web Request and we can't perform a Manually Selection.

We found a CodeUnit 63 can help us to explode BOM but it need us to do manually selection on a poped-up Dialog .
We found the logic in the CodeUnit is just what we need when 'HideDialog ' is FALSE.

But unfortunately we can't set value to it.
![hddlg_1](https://user-images.githubusercontent.com/43436829/45807858-fa2c8b00-bcf6-11e8-97a5-dca3d2dddc84.png)
![hddlg_2](https://user-images.githubusercontent.com/43436829/45807869-fef13f00-bcf6-11e8-936e-fa1080be2618.png)

Does it possible to add a function like 'SetHideDialog()' to let us set value for 'HideDialog '?

Thanks

Billy

**Comment by JesperSchulz** [comment]
Closing issue, as the issue appears to be resolved. Please reopen if that isn't the case.
