### ISSUE TITLE
[Event Request] Table 49 "Invoice Post. Buffer" - Procedure "CalcDiscount"

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#23900]
Dear ALAppExtensions Team,

We would like to request the following change

    procedure CalcDiscount(PricesInclVAT: Boolean; DiscountAmount: Decimal; DiscountAmountACY: Decimal)
    var
        CurrencyLCY: Record Currency;
        CurrencyACY: Record Currency;
        GLSetup: Record "General Ledger Setup";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalcDiscount(Rec, IsHandled);
        if IsHandled then
            exit;
    
        CurrencyLCY.InitRoundingPrecision();
        GLSetup.Get();
        if GLSetup."Additional Reporting Currency" <> '' then
            CurrencyACY.Get(GLSetup."Additional Reporting Currency")
        else
            CurrencyACY := CurrencyLCY;
        "VAT Amount" := Round(
            CalcVATAmount(PricesInclVAT, DiscountAmount, "VAT %"),
            CurrencyLCY."Amount Rounding Precision",
            CurrencyLCY.VATRoundingDirection());
        "VAT Amount (ACY)" := Round(
            CalcVATAmount(PricesInclVAT, DiscountAmountACY, "VAT %"),
            CurrencyACY."Amount Rounding Precision",
            CurrencyACY.VATRoundingDirection());
        **//--> event request
        OnCalcDiscountUpdateVATAmount(Rec,PricesInclVAT,DiscountAmount,DiscountAmountACY);
        **//<-- event request
    
        if PricesInclVAT and ("VAT %" <> 0) then begin
            "VAT Base Amount" := DiscountAmount - "VAT Amount";
            "VAT Base Amount (ACY)" := DiscountAmountACY - "VAT Amount (ACY)";
        end else begin
            "VAT Base Amount" := DiscountAmount;
            "VAT Base Amount (ACY)" := DiscountAmountACY;
        end;
        Amount := "VAT Base Amount";
        "Amount (ACY)" := "VAT Base Amount (ACY)";
        "VAT Base Before Pmt. Disc." := "VAT Base Amount";
        NonDeductibleVAT.Calculate(Rec);
    end;

    **//--> event request
    [IntegrationEvent(false, false)]
    local procedure OnCalcDiscountUpdateVATAmount(var InvoicePostBuffer: Record "Invoice Post. Buffer"; PricesInclVAT: Boolean,DiscountAmount: Decimal,DiscountAmountACY: Decimal)
    begin
    end;
    **//<-- event request

**Comment by tomasevics** [comment]
Hi, we can't add publishers in obsolete procedures. They will be removed in next major release. Did you think to switch to Invoice Posting Buffer instead?

**Comment by Hakan-6Gen** [comment]
> 
Ok. I need the same build there as well. Can we add it there?

**Comment by tomasevics** [comment]
Yes, we will add publisher there.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11478.
