### ISSUE TITLE
Refactoring: VAT Amount Line

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#2391]
**Table 290 VAT Amount Line** is a core object for calculating amounts, VAT rates and documents sums. Being such a intergral part of amount calculation, it should become a lot more flexible and extendible.

1) The key should become a generic `Entry No.`, and no longer be a composite key, because that limits how we can decide over how those lines are grouped together.

3) `GetLine` would at that point become pretty useless, as it would then just translate to a plain `GET(EntryNo) `

2) the methods `InsertLine` and `InsertNewLine` should therefore no longer simply base their `FIND` on the current key, but should allow us to hook into it. Say with an event like the following:
    `OnBeforeFindExistingLine(VAR VATAmountLine, NewVATAmountLine, VAR Found: Boolean; VAR Handled: Boolean);`

4) The fact that a line is skipped or not (see `InsertLine`, where amounts are checked against 0) should also be subject to an event. This event should start off with the variable `SkipLine` preset with the way it currently decides if a line should be skipped. This way we can - if needed - override id without losing default behaviour.
    `OnAfterVerifySkipLine(VATAmountLine; VAR SkipLine: Boolean)`

5) The event `OnInsertLineOnBeforeModify` is fine, but only triggers if a new line is added that does **not** create a new line, but only updates an existing one. We need a generic event that triggers **whenever** a new line is added to the buffer, regardless if it get's merged into an existing one. In fact ... if the line gets merged or not could depend on values that get applied during this event:
    `OnBeforeAddLineToBuffer(VAR VATAmountLine; NewVATAmountLine);`
    This goes hand in hand with point 3 above.

**Comment by stefanoPrimo** [comment]
Hi @StanPesotskiy 
Could you please give some feedback about the events requested (see points 3-4-5)?
Because I've also the necessity to modify the VAT Amount Line, in particular, the method `InsertLine`.

**Comment by StanPesotskiy** [comment]
Hi @stefanoPrimo 
Such a request will not be implemented before the major release (October 2019). It will be (or not) included into the scope according to the priorities among all incoming work items. This item is not yet in progress, so I cannot give you a worthy feedback now without investigating this topic.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
