### ISSUE TITLE
Scope OnPrem in GenJnlManagement.Codeunit.al 

### ISSUE THREAD

**Issue by SBiernat** [microsoft/ALAppExtensions#23912]
Hello,
in the Codeunit GenJnlManagement.Codeunit.al  the Procedure CheckCurrencyCode is scope OnPrem.

This should not be App-exclusive.

Expected: Remove Line  [Scope('OnPrem')]

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
