### ISSUE TITLE
[Event Request] for Fixed Asset reports 5690 "Index Fixed Assets" & 5691 "Index Insurance"

### ISSUE THREAD

**Issue by thomashoesel** [microsoft/ALAppExtensions#23910]
Hello Base Appelopers,

please adapt the following two Fixed Asset reports 5690 "Index Fixed Assets" & 5691 "Index Insurance" in regard to events:

**report 5690 "Index Fixed Assets"**

 - make parameter **IndexAmount** of existing event **“OnBeforeInsertJournalLine”** a by-reference (var) 

   _[IntegrationEvent(true, false)]
    local procedure OnBeforeInsertJournalLine(FixedAsset: Record "Fixed Asset"; 
                **var** IndexAmount: Decimal; 
                var IsHandled: Boolean; 
                i: Integer; DeprBookCode: Code[10])_
  
**report 5691 "Index Insurance"**

- add an integration event (similar as in report 5690 „Index Fixed Assets“) inside the trigger OnAfterGetRecord at the marked spot including an IsHandled management:

        IsHandled := false;
        OnBeforeInsertJournalLine(FixedAsset, IndexFigure, IsHandled, InsCoverageLedgEntry);
        if IsHandled then
            exit;

![image](https://github.com/microsoft/ALAppExtensions/assets/127841954/54f2c9a1-ef86-42e6-af80-5d95a7588ea2)

   _[IntegrationEvent(true, false)]
    local procedure OnBeforeInsertJournalLine(FixedAsset: Record "Fixed Asset"; 
                 var IndexFigure: Decimal; 
                 var IsHandled: Boolean; 
                 InsCoverageLedgEntry: Record "Ins. Coverage Ledger Entry")_
    
Those two reports are also subject of **[Protection Level To Open Request] for Fixed Asset reports 5690 "Index Fixed Assets" & 5691 "Index Insurance" #23936**

Thank you.

**Comment by MarkoTrn** [comment]
Hello,

Please, for opening protection level open new request. For adding new event in report Index Insurance, please be more specific with event signature and position where event will be raised.

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11525.
