### ISSUE TITLE
[Event Request] codeunit 1323 "Cancel PstdSalesInv (Yes/No)" - procedure "CancelInvoice"

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#23915]
Dear ALAppExtensions Team,

We would like to request the following change

    procedure CancelInvoice(var SalesInvoiceHeader: Record "Sales Invoice Header"): Boolean
    var
        SalesCrMemoHeader: Record "Sales Cr.Memo Header";
        CancelledDocument: Record "Cancelled Document";
        CorrectPostedSalesInvoice: Codeunit "Correct Posted Sales Invoice";
        IsHandled: Boolean;
    begin
        **//--> event request
        IsHandled := false;
        OnCancelInvoiceOnBeforeTestCorrectInvoice(SalesInvoiceHeader, IsHandled);
        if not IsHandled then
        **//<-- event request
        CorrectPostedSalesInvoice.TestCorrectInvoiceIsAllowed(SalesInvoiceHeader, true);
        if Confirm(CancelPostedInvoiceQst) then
            if CorrectPostedSalesInvoice.CancelPostedInvoice(SalesInvoiceHeader) then
                if Confirm(OpenPostedCreditMemoQst) then begin
                    CancelledDocument.FindSalesCancelledInvoice(SalesInvoiceHeader."No.");
                    SalesCrMemoHeader.Get(CancelledDocument."Cancelled By Doc. No.");
                    IsHandled := false;
                    OnCancelInvoiceOnBeforePostedSalesCreditMemo(SalesCrMemoHeader, IsHandled);
                    if not IsHandled then
                        PAGE.Run(PAGE::"Posted Sales Credit Memo", SalesCrMemoHeader);
                    exit(true);
                end;
    
        exit(false);
    end;

    **//--> event request
    [IntegrationEvent(false, false)]
    local procedure OnCancelInvoiceOnBeforeTestCorrectInvoice(var SalesInvoiceHeader: Record "Sales Invoice Header"; var IsHandled: Boolean)
    begin
    end;
    **//<-- event request

**Comment by MarkoTrn** [comment]
Hello,

Please, can you explain to us, through the scenario, purpose of this request?

Thank you

**Comment by Hakan-6Gen** [comment]
Hello,
In the next step, the same function is already used again.

procedure CancelInvoice(var SalesInvoiceHeader: Record "Sales Invoice Header"): Boolean
    var
        SalesCrMemoHeader: Record "Sales Cr.Memo Header";
        CancelledDocument: Record "Cancelled Document";
        CorrectPostedSalesInvoice: Codeunit "Correct Posted Sales Invoice";
        IsHandled: Boolean;
    begin
        **CorrectPostedSalesInvoice.TestCorrectInvoiceIsAllowed**(SalesInvoiceHeader, true);
        if Confirm(CancelPostedInvoiceQst) then
            if **CorrectPostedSalesInvoice.CancelPostedInvoice**(SalesInvoiceHeader) then


---------------------------------------------------

procedure CancelPostedInvoice(var SalesInvoiceHeader: Record "Sales Invoice Header"): Boolean
    begin
        CancellingOnly := true;
        **exit(CreateCreditMemo(SalesInvoiceHeader));**
    end;

--------------------------------------------------------

local procedure CreateCreditMemo(var SalesInvoiceHeader: Record "Sales Invoice Header"): Boolean
var
    SalesHeader: Record "Sales Header";
    SalesCrMemoHeader: Record "Sales Cr.Memo Header";
    IsHandled: Boolean;
begin
    **TestCorrectInvoiceIsAllowed(SalesInvoiceHeader, CancellingOnly);**

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 58511.
