### ISSUE TITLE
[Event Request] codeunit 1303 "Correct Posted Sales Invoice" - trigger "OnRun"

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#23917]
Dear ALAppExtensions Team,

We would like to request the following change

    trigger OnRun()
    var
        SalesHeader: Record "Sales Header";
    begin
        UnapplyCostApplication("No.");
    
        OnBeforeCreateCorrectiveSalesCrMemo(Rec);
        CreateCopyDocument(Rec, SalesHeader, SalesHeader."Document Type"::"Credit Memo", false);
        OnAfterCreateCorrectiveSalesCrMemo(Rec, SalesHeader, CancellingOnly);
    
        if SalesInvoiceLinesContainJob("No.") then
            CreateAndProcessJobPlanningLines(SalesHeader);
    
        **//--> event request
        IsHandled := false;
        OnBeforePostCorrectiveSalesCrMemo(Rec, SalesHeader, IsHandled);
        if not IsHandled then begin
          CODEUNIT.Run(CODEUNIT::"Sales-Post", SalesHeader);
          SetTrackInfoForCancellation(Rec);
          UpdateSalesOrderLinesFromCancelledInvoice("No.");
        end;
        **//<-- event request
        OnOnRunOnAfterUpdateSalesOrderLinesFromCancelledInvoice(Rec, SalesHeader);
    
        Commit();
    end;

     **//--> event request
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostCorrectiveSalesCrMemo(var SalesInvoiceHeader: Record "Sales Invoice Header"; var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;
    **//<-- event request

**Comment by MarkoTrn** [comment]
Hello,

Please, explain scenario in which you would un-apply costs, create copy of document, optionally create and process job planning lines, and then skip posting of corrected document.

Thank you

**Comment by Hakan-6Gen** [comment]
Hello,

I want to use the following code structure.

// --> NAV6GEN HO Desc: 6GEN Core Localization
//CODEUNIT.Run(CODEUNIT::"Sales-Post", SalesHeader);
//SetTrackInfoForCancellation(Rec);
//UpdateSalesOrderLinesFromCancelledInvoice(Rec."No.");
**SalesPost.SetSuppressCommit(true);
SalesPost.Run(SalesHeader);**
**GetPostedDocumentRecord(SalesHeader, SalesCrMemoHeader);**
SetTrackInfoForCancellation(Rec, SalesCrMemoHeader);
**PstdDocReverseMgt.SetReversingTrackInfoForSalesInvoice(Rec);**
// <-- NAV6GEN HO Desc: 6GEN Core Localization

* prevent commit
* Reaching the corrective document without using Applis to ID.
local procedure GetPostedDocumentRecord(SalesHeader: Record "Sales Header"; var SalesCrMemoHeader: Record "Sales Cr.Memo Header")
var
    PostedSalesDocumentVariant: Variant;
begin
    if SalesHeader."Last Posting No." = '' then
        SalesCrMemoHeader.Get(SalesHeader."No.")
    else
        SalesCrMemoHeader.Get(SalesHeader."Last Posting No.");
end;
* Use my own code PstdDocReverseMgt.SetReversingTrackInfoForSalesInvoice(Rec);
Reverse tracking update for Cust/Vend Ledger Entry, G/L Entry, VAT Entry etc.
* I dont want to use "UpdateSalesOrderLinesFromCancelledInvoice" structure.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 58511.
