### ISSUE TITLE
[Event Change Request] Table 37 "Sales Line" - Field 90 "VAT Prod. Posting Group"

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#23914]
Dear ALAppExtensions Team,

We would like to request the following change

    IsHandled := false;
    OnValidateVATProdPostingGroupOnBeforeCheckVATCalcType(Rec, VATPostingSetup, IsHandled);
    if not IsHandled then
        case "VAT Calculation Type" of
            "VAT Calculation Type"::"Reverse Charge VAT",
            "VAT Calculation Type"::"Sales Tax":
                "VAT %" := 0;
            "VAT Calculation Type"::"Full VAT":
                begin
                    TestField(Type, Type::"G/L Account");
                    TestField("No.", VATPostingSetup.GetSalesAccount(false));
                end;
        end;

    **//--> event parameter change request "var" for VATPostingSetup
    [IntegrationEvent(false, false)]
    local procedure OnValidateVATProdPostingGroupOnBeforeCheckVATCalcType(var SalesLine: Record "Sales Line"; var VATPostingSetup: Record "VAT Posting Setup"; var IsHandled: Boolean)
    begin
    end;
    **//<-- event parameter change request "var" for VATPostingSetup

**Comment by MarkoTrn** [comment]
Hello,

Can you use OnValidateVATProdPostingGroupOnBeforeVATPostingSetupGet where VATPostingSetup is already passed by reference? If not, please provide explanation for this request.

Thank you

**Comment by Hakan-6Gen** [comment]
Hello,

I can use OnValidateVATProdPostingGroupOnBeforeVATPostingSetupGet event.

**Comment by MarkoTrn** [comment]
Great, thank you on your feedback. I'll close request then
