### ISSUE TITLE
Wrong Field Number in Table Extension

### ISSUE THREAD

**Issue by stephanweidmann** [microsoft/ALAppExtensions#23939]
https://github.com/microsoft/ALAppExtensions/blob/main/Apps/W1/StatisticalAccounts/app/src/StatAccSourceCodeSetup.TableExt.al
This TableExtension for Source Code Setup uses the wrong field number. This will conflict with customer extensions.
    {
        field(50050; "Statistical Account Journal"; Code[10])
        {
            Caption = 'Statistical Account Journal';
            TableRelation = "Source Code";
        }
    }

**Comment by JesperSchulz** [comment]
Unfortunately, this field was already released with 2023 Wave 1 and giving it a new ID would hence be a breaking change. The field has been deprecated and replaced with a new one in 2023 Wave 2. We'll see what we can do to prevent this from happening.
