### ISSUE TITLE
[Event Request] Report 5753 Get Source Documents 

### ISSUE THREAD

**Issue by IesMeulmeester** [microsoft/ALAppExtensions#23934]
Please add some events to report 5753 Get Source Documents 

**DataItem Sales Line -> OnPostDataItem**
- Add OnBeforeOnPostDataItemSalesLine

`OnBeforeOnPostDataItemSalesLine(WhseReceiptHeader, RequestType, OneHeaderCreated, WhseHeaderCreated, LineCreated, HideDialog);`

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnPostDataItemSalesLine(var WhseReceiptHeader: Record "Warehouse Receipt Header"; RequestType: Option Receive,Ship; OneHeaderCreated: Boolean; WhseHeaderCreated: Boolean; LineCreated: Boolean; HideDialog: Boolean)
    begin
    end;
```

- Extend OnAfterProcessDocumentLine with parameters: OneHeaderCreated, WhseHeaderCreated
![image](https://github.com/microsoft/ALAppExtensions/assets/2750351/1d5b4a80-27af-4531-b10a-a84e4379d57a)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterProcessDocumentLine(var WarehouseShipmentHeader: Record "Warehouse Shipment Header"; var WarehouseRequest: Record "Warehouse Request"; OneHeaderCreated: Boolean; WhseHeaderCreated: Boolean; var LineCreated: Boolean; WarehouseReceiptHeader: Record "Warehouse Receipt Header")
    begin
    end;
```

**DataItem Purchase Line -> OnPostDataItem**
- Add OnBeforeOnPostDataItemPurchaseLine

`OnBeforeOnPostDataItemPurchaseLine(WhseReceiptHeader, RequestType, OneHeaderCreated, WhseHeaderCreated, LineCreated, HideDialog);`

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnPostDataItemPurchaseLine(var WhseReceiptHeader: Record "Warehouse Receipt Header"; RequestType: Option Receive,Ship; OneHeaderCreated: Boolean; WhseHeaderCreated: Boolean; LineCreated: Boolean; HideDialog: Boolean)
    begin
    end;
```

- Extend OnAfterProcessDocumentLine with parameters: OneHeaderCreated, WhseHeaderCreated
![image](https://github.com/microsoft/ALAppExtensions/assets/2750351/2d9064f7-000e-4589-857c-8f213bf9c53e)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterProcessDocumentLine(var WarehouseShipmentHeader: Record "Warehouse Shipment Header"; var WarehouseRequest: Record "Warehouse Request"; OneHeaderCreated: Boolean; WhseHeaderCreated: Boolean; var LineCreated: Boolean; WarehouseReceiptHeader: Record "Warehouse Receipt Header")
    begin
    end;
```

**DataItem Transfer line -> OnPostDataItem**

- Extend OnAfterProcessDocumentLine with parameters: OneHeaderCreated, WhseHeaderCreated
![image](https://github.com/microsoft/ALAppExtensions/assets/2750351/cd085934-8b92-4a08-bc13-1d3ffc422b1f)

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterProcessDocumentLine(var WarehouseShipmentHeader: Record "Warehouse Shipment Header"; var WarehouseRequest: Record "Warehouse Request"; OneHeaderCreated: Boolean; WhseHeaderCreated: Boolean; var LineCreated: Boolean; WarehouseReceiptHeader: Record "Warehouse Receipt Header")
    begin
    end;
```

**Comment by MarkoTrn** [comment]
Hello,

Please provide signature for each requested event. Thank you

**Comment by IesMeulmeester** [comment]
> Hello,
> 
> Please provide signature for each requested event. Thank you

Signatures added for each event.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11320.
