### ISSUE TITLE
[Protection Level To Open Request] for Fixed Asset reports 5690 "Index Fixed Assets" & 5691 "Index Insurance"

### ISSUE THREAD

**Issue by thomashoesel** [microsoft/ALAppExtensions#23936]
Hello Base Appelopers,

please adapt the following two Fixed Asset reports 5690 "Index Fixed Assets" & 5691 "Index Insurance" in regard to protected variables:

report 5690 "Index Fixed Assets"

open the Protection Level for four global variables
• FAPostingDate: Date;
• IndexFigure: Decimal;
• PostingDescription: Text[100];
• DeprBookCode: Code[10];

report 5691 "Index Insurance"

open the Protection Level for four global variables
• PostingDate: Date;
• IndexFigure: Decimal;
• PostingDescription: Text[100];
• DeprBook: Record "Depreciation Book"

These two reports are also subject of **[Event Request] for Fixed Asset reports 5690 "Index Fixed Assets" & 5691 "Index Insurance"**

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
