### ISSUE TITLE
[Event Request] codeunit 242 "Item Jnl.-Post+Print"

### ISSUE THREAD

**Issue by TomFranzen** [microsoft/ALAppExtensions#23940]
Hello team,

I would like to have an additional event in CU 242 (like in CU 241)

here's the code of CU242 (procedure "Code"):
```
            TempJnlBatchName := "Journal Batch Name";

            ItemJnlPostBatch.SetSuppressCommit(SuppressCommit);
            ItemJnlPostBatch.Run(ItemJnlLine);

            OnAfterPostJournalBatch(ItemJnlLine);

```

This is the code of CU241 (procedure "Code"):
```
            TempJnlBatchName := "Journal Batch Name";

            ItemJnlPostBatch.SetSuppressCommit(SuppressCommit or PreviewMode);
 ----->     OnCodeOnBeforeItemJnlPostBatchRun(ItemJnlLine);
            ItemJnlPostBatch.Run(ItemJnlLine);

            OnCodeOnAfterItemJnlPostBatchRun(ItemJnlLine, HideDialog, SuppressCommit);

```
The event of CU241 marked with "----->" I'm missing in CU242.

Thanks a lot.
Thomas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11320.
