### ISSUE TITLE
[Bug] Shopify Order Customer Sync Name with Parenthesis

### ISSUE THREAD

**Issue by JaredKMiller** [microsoft/ALAppExtensions#23941]
We are syncing customers with the order import. If a customer has a parenthesis in their name, the Sync Orders from Shopify job queue errors out with:
`The filter "@First Last (Maiden)" is not valid for the Name field on the Contact table. An error occurred while interpreting the filter: Did not expect '('.`
Can this be addressed? Thanks!

**Comment by pri-kise** [comment]
@JaredKMiller if you don't want to save this by yourself, then you should create a Support Ticket via the normal support channels to get this addressed.

**Comment by JaredKMiller** [comment]
Sorry, I am happy to provide a PR for this as it seems like the a simple fix in codeunit 30163 "Shpfy Order Mapping" to add single quotation marks around the Contact filter applied in FindContactNo(). If this gets marked Ready for Implementation, I will submit a fix.

**Comment by AndreiPanko** [comment]
Thank you for reporting this.

I can see that was fixed starting from 22.3


    local procedure FindContactNo(ContactName: Text[100]; CustomerNo: Code[20]): Code[20]
    var
        Contact: Record Contact;
        ContactBusinessRelation: Record "Contact Business Relation";
    begin
        if ContactName = '' then
            exit('');
        ContactBusinessRelation.SetRange("Link to Table", "Contact Business Relation Link To Table"::Customer);
        ContactBusinessRelation.SetRange("No.", CustomerNo);
        if ContactBusinessRelation.FindFirst() then begin
            Contact.SetRange(Type, "contact Type"::Person);
            Contact.SetRange("Company No.", ContactBusinessRelation."Contact No.");
            Contact.SetFilter(Name, '''@' + ContactName.Replace('''', '''''') + '''');
            if Contact.FindFirst() then
                exit(Contact."No.");
        end;
    end;
