### ISSUE TITLE
[Access Request] table 2000000028 "Table Information"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#23952]
Could you please change the access scope for this table to Scope Cloud or alternativly provide access to this data via a  new codeunit?

We have some developments where we would like to know the number of records inside a table.
Currently we have to open this table via RecordRef and use the the count method there.

It would be very useful if we were able to create FlowFields on the Field "No. of Records" similiar to the `table 8622 "Config. Line"`.

```al
field(9; "No. of Records (Source Table)"; Integer)
        {
            BlankZero = true;
            CalcFormula = Sum("Table Information"."No. of Records" WHERE("Company Name" = FIELD("Company Filter (Source Table)"),
                                                                          "Table No." = FIELD("Table ID")));
            Caption = 'No. of Records (Source Table)';
            Editable = false;
            FieldClass = FlowField;
        }
```

Internal workitem: [AB#476908](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/476908)

**Comment by JesperSchulz** [comment]
The "Table Information" table is a platform table. Access must hence be changed in platform. We have hence forwarded your request to our platform team.
