### ISSUE TITLE
[Caption Request] Missing caption property on page 1171 "User Task Card"

### ISSUE THREAD

**Issue by PeterKevesRevol** [microsoft/ALAppExtensions#23960]
Please add caption property to General Group on page 1171 "User Task Card", because it is missing now. It helps to translate it in the localization translation app. Thank you!

page 1171 "User Task Card"

{

    Caption = 'User Task';

    PageType = Card;

    SourceTable = "User Task";

    layout

    {

        area(content)

        {

            group(General)

            {
                Caption = 'General'; //please add this line!!!!

                field(Title; Rec.Title)

**Comment by JesperSchulz** [comment]
Will get addressed with 22.4.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11397.
