### ISSUE TITLE
Add new Subscriber SetTrueOnSystemSetPostingPreviewActive codeunit 20 "Posting Preview Event Handler"

### ISSUE THREAD

**Issue by AndreaRux** [microsoft/ALAppExtensions#23967]
Hi there,
could/will you add a new subscriber in codeunit 20 "Posting Preview Event Handler".
So that the IsActive procedure in codeunit 373 "Bank. Acc. Recon. Post Preview" works, like the one for Codeunit 19 "Gen. Jnl.-Post Preview"
Or do I need to add the subscriber in my own app?

```
    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Bank. Acc. Recon. Post Preview", 'OnSystemSetPostingPreviewActive', '', false, false)]
    local procedure SetTrueOnSystemSetPostingPreviewActiveBankRecon(var Result: Boolean)
    begin
        Result := true;
    end;
```

**Comment by AndreaRux** [comment]
Hi there,
do you have any update for me?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13636.
