### ISSUE TITLE
"Zone Code" is not filled in codeunit 7312 "Create Pick", because wrong "GetBin" procedure is called due to "with" statement

### ISSUE THREAD

**Issue by yurim108** [microsoft/ALAppExtensions#23968]
**🕮 Describe the issue**

"Zone Code" and some other fields are NOT filled when creating a Warehouse Pick.

Application Version: 22.2.56969.57617

**🔧 To Reproduce**

1.     Setup location "L1" without "Directed Put-away and Pick",  
        with zone "Z1", bins "WS", "B1", warehouse shipment and warehouse pick.  
        Bin "B1" must have "Zone Code" = "Z1".  
        Set "WS" in the field "Shipment Bin Code" on location card.
2.     Post some inventory of item 1000 on location "L1", bin "B1".
3.     Create Sales Order for item 1000 and location "L1", bin "WS".
4.     Release Sales Order and create Warehouse Shipment.
5.     Create Warehouse Pick from Warehouse Shipment.
6.     Bug: The field "Zone Code" is NOT filled in Warehouse Activity Lines.

**📣 Expected behavior**

The field "Zone Code" should be filled in Warehouse Activity Lines.

**Screenshots**

![grafik](https://github.com/microsoft/ALAppExtensions/assets/70197815/2695fa6f-8fd0-4e79-8202-fc111bdba038)

![grafik](https://github.com/microsoft/ALAppExtensions/assets/70197815/17f5288c-0573-45a2-b403-0a5c66674325)

Workaround:
![grafik](https://github.com/microsoft/ALAppExtensions/assets/70197815/ed319174-f177-4e3b-bc37-fa268a72789c)

**Additional context**

**Comment by mynhardt7** [comment]
@yurim108 Did you log a support ticket for this with Microsoft?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13331.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 13377.
