### ISSUE TITLE
Tenant Media Thumbnails - Recurring Logo Uploads fill database

### ISSUE THREAD

**Issue by KevinKalla** [microsoft/ALAppExtensions#23969]
Hello together,

we have two own Extensions which have a dependency that we uploaded in AppSource which cause a very strange error. Since customers are already using these apps and are depending on it this problem has become very urgent. The Microsoft Partner Support advised us to ask in here for a solution.

The issue is that the database of an environment is constantly growing after installing the app “Document Inbound Simova” with a dependency to the “DMS by Simova” app. 

When installing DMS by Simova, no issues arise. However, after adding Document Inbound by Simova, which has a dependency to DMS by Simova, the following tables grow per second:

- Tenant Media Thumbnails – No. 2000000185
- Tenant Media – No. 2000000184

When looking at the tables, it becomes clear that these tables are filled every second with .png pictures of the size 70 x 70 and 240 x 240.

When using an own built extension we made just for investigation, we found out that the pictures are recurring uploads of the DMS by Simova and Document Inbound by Simova App icons/logo. The filenames can even be compared to the system IDs in the system.

We do have some additional information to give you more insight on what is happening:

Product Versions:

- Document Inbound by Simova 21.1.2.0 with Dependency to DMS by Simova (and CORE by Simova, but that is causing no issues)
- DMS by Simova 21.9.4.0 (Dependency to CORE by Simova, but that is causing no issues)

The issue itself does not arise in the Simova product code. It does not involve the App Icons at all and has no unusual Code in that regard, even after multiple checkings. 

The thing that was done is that as usually done with apps for the AppSource is that the App Icons were delivered with the upload of the App JSON. This is a standard procedure which only this case leads to the issue. Other Apps from Simova with a dependency to other Apps do not cause this.

As already stated, since customers are already using these apps and are depending on it this problem has become very urgent.

I would be happy about some feedback on this.

Best regards

Kevin Kalla

**Comment by AlexanderYakunin** [comment]
@JesperSchulz - please help to forward this information to right team

**Comment by JesperSchulz** [comment]
We've got a support case for this now. Closing this issue.
