### ISSUE TITLE
[Event Request] Codeunit 7322 - Create Inventory Pick/Movement - MakeLine

### ISSUE THREAD

**Issue by BadaboomDev** [microsoft/ALAppExtensions#23994]
The following events are required for this object:

```
    local procedure MakeLine(var NewWhseActivLine: Record "Warehouse Activity Line"; TakeBinCode: Code[20]; QtyToPickBase: Decimal; var RemQtyToPickBase: Decimal)
    var
        IsHandled: Boolean;
    begin
        // Request
        IsHandled := false;
        OnBeforeMakeLine(NewWhseActivLine, WhseActivHeader, RemQtyToPickBase, NextLineNo, Location, TakeBinCode, QtyToPickBase, IsInvtMovement, LineCreated, CompleteShipment, IsHandled);
        if IsHandled then
            exit;
        // Request

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeMakeLine(var NewWhseActivLine: Record "Warehouse Activity Line"; var WhseActivHeader: Record "Warehouse Activity Header"; var RemQtyToPickBase: Decimal; var NextLineNo: Integer; Location: Record Location; TakeBinCode: Code[20]; var QtyToPickBase: Decimal; IsInvtMovement: Boolean; var LineCreated: Boolean; CompleteShipment: Boolean; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 58533.
