### ISSUE TITLE
Change Request: Codeunit 5601 FA Insert G/L Account - GetGLAcc

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/ALAppExtensions#240]
The function `GetBalAcc` in Codeunit 5601 FA Insert G/L Account should get it's parameter `GenJnlLine` by reference.
So instead of this:

`[External] GetBalAcc(GenJnlLine : Record "Gen. Journal Line") : Integer`

it should be declared as

`[External] GetBalAcc(VAR GenJnlLine : Record "Gen. Journal Line") : Integer`

This enables us to use this function also on temporary records and buffers. Of course you need to make sure that the originally passed record is not modified.

An alternative would be, to write the newly created Gen. Journal Lines into a separate buffer that is passed in by reference. So we have full control over what happens to the created lines.

**Comment by IhorHandziuk** [comment]
Thank you for your request. We decided to introduce a separate function 
`GetBalAccBuffer(VAR GenJnlLine : Record "Gen. Journal Line") : Integer`  
for the described use-case. It should be available in the next update.
