### ISSUE TITLE
[Event Request] table 36 "Sales Header" - procedure "SetTrackInfoForCancellation"

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#24019]
**🕮 Describe the request**

    internal procedure SetTrackInfoForCancellation()
    var
        CancelledDocument: Record "Cancelled Document";
        SalesInvoiceHeader: Record "Sales Invoice Header";
        SalesCreditMemoHeader: Record "Sales Cr.Memo Header";
    begin
        if Rec."Applies-to Doc. Type" <> Rec."Applies-to Doc. Type"::Invoice then
            exit;
        SalesInvoiceHeader.SetLoadFields("No.");
        if not SalesInvoiceHeader.Get(Rec."Applies-to Doc. No.") then
            exit;
        SalesCreditMemoHeader.SetLoadFields("Pre-Assigned No.");
        SalesCreditMemoHeader.SetRange("Pre-Assigned No.", Rec."No.");
        if not SalesCreditMemoHeader.FindFirst() then
            exit;
        **//--> event request
        IsHandled := false;
        OnBeforeSetTrackInfoForCancellation(SalesCreditMemoHeader, IsHandled);
        if not IsHandled then
        **//<-- event request
          CancelledDocument.InsertSalesInvToCrMemoCancelledDocument(SalesInvoiceHeader."No.", SalesCreditMemoHeader."No.");
    end;

    **//--> event request
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetTrackInfoForCancellation(SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var IsHandled: boolean)
    begin
    end;
    **//<-- event request

**Additional context**

In Turkish localization, all Sales Cr. Memo documents are not accepted as cancellation documents.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
