### ISSUE TITLE
[Event Request] Codeunit 437 "IC Navigation" -  NavigateToSalesOrderDocument

### ISSUE THREAD

**Issue by CedPo** [microsoft/ALAppExtensions#24018]
Dear ALAppExtensions team,

through this issue we would like to request the addition of an event publisher OnNavigateToSalesDocumentOnDocumentTypeCaseElse in Codeunit 437 "IC Navigation" with the following signature:

[IntegrationEvent(false, false)]
local procedure OnNavigateToSalesDocumentOnDocumentTypeCaseElse (DocumentNo: Code[20]; ICDirectionType: Enum "IC Direction Type"; ICPartnerCode: Code[20]; DocumentType: Enum "IC Transaction Document Type"; var OpenDoc: Boolean)
begin
end;

which would be used to add an else branch to case DocumentType in procedure NavigateToSalesDocument(DocumentNo: Code[20]; ICDirectionType: Enum "IC Direction Type"; ICPartnerCode: Code[20]; DocumentType: Enum "IC Transaction Document Type"): Boolean
    begin
        case DocumentType of
            DocumentType::Order:
                exit(NavigateToSalesOrderDocument(DocumentNo, ICDirectionType, ICPartnerCode));
            DocumentType::Invoice:
                exit(NavigateToSalesInvoice(DocumentNo));
  //>>>> New >>>>
    else begin
	OnNavigateToSalesDocumentOnDocumentTypeCaseElse(DocumentNo, ICDirectionType, ICPartnerCode, OpenDoc);
	exit(OpenDoc);
        end;
  //<<<< New <<<<

    end;
    exit(false);

Thanks in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
