### ISSUE TITLE
[Event Request] Missing var in OnBeforeShowDeletedMessage table 5767 "Warehouse Activity Line"

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#24017]
Hi,

please add the missing var in the event.

Before:

[IntegrationEvent(false, false)]
local procedure OnBeforeShowDeletedMessage(WarehouseActivityLine: Record "Warehouse Activity Line"; var IsHandled: Boolean)
begin
end;

After:

[IntegrationEvent(false, false)]
local procedure OnBeforeShowDeletedMessage(**va**r WarehouseActivityLine: Record "Warehouse Activity Line"; var IsHandled: Boolean)
begin
end;

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
