### ISSUE TITLE
[Exposure request] Publisher Event "OnBeforeCalculateSalesTax" for Report 1305 / 1303 same like 1304

### ISSUE THREAD

**Issue by preetgor** [microsoft/ALAppExtensions#24012]
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Microsoft has marked reports (204, 205, 206, 207) as "Obsolete" with Obsolete status "Pending" and Reason "Replaced with the report below Standard.</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Report 204 will be replaced by Report 1304.<br style="box-sizing: border-box;">Report 205 will be replaced by Report 1305.<br style="box-sizing: border-box;">Report 206 will be replaced by Report 1306.<br style="box-sizing: border-box;">Report 207 will be replaced by Report 1307</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Current :<br style="box-sizing: border-box;">As reports will be replaced in future BC releases and we want to add integration to all respective Reports. Based on old git hub ticket MS added events to 1304 / 1306 / 1307 against<span> </span><a href="https://github.com/microsoft/ALAppExtensions/issues/6507" data-hovercard-type="issue" data-hovercard-url="/microsoft/ALAppExtensions/issues/6507/hovercard" style="box-sizing: border-box; background-color: transparent; color: var(--fgColor-accent, var(--color-accent-fg)); text-decoration: none;">6507<span> </span></a>and<span> </span><a href="https://github.com/microsoft/ALAppExtensions/issues/12884" data-hovercard-type="issue" data-hovercard-url="/microsoft/ALAppExtensions/issues/12884/hovercard" style="box-sizing: border-box; background-color: transparent; color: var(--fgColor-accent, var(--color-accent-fg)); text-decoration: none;">12884</a></p> and<span> </span> <a href="https://github.com/microsoft/ALAppExtensions/issues/22825" data-hovercard-type="issue" data-hovercard-url="/microsoft/ALAppExtensions/issues/22825/hovercard" style="box-sizing: border-box; background-color: transparent; color: var(--fgColor-accent, var(--color-accent-fg)); text-decoration: none;">22825</a></p>

Report | Comments
-- | --
report 1304 "Standard Sales - Quote" | MS made changes as requested OnAfterCalculateSalesTax / OnBeforeCalculateSalesTax
report 1305 "Standard Sales - Order Conf." | MS changes not found against #6507 and #12884
report 1306 "Standard Sales - Invoice" | MS made changes as requested OnAfterCalculateSalesTax / OnBeforeCalculateSalesTax
report 1307 "Standard Sales - Credit Memo" | MS made changes as requested OnAfterCalculateSalesTax / OnBeforeCalculateSalesTax

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Expected :<br style="box-sizing: border-box;">Need publisher event and respective code for OnAfterCalculateSalesTax / OnBeforeCalculateSalesTax on Report 1305<br style="box-sizing: border-box;">Need publisher event and respective code for OnAfterCalculateSalesTax / OnBeforeCalculateSalesTax on Report 1303</p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; color: rgb(230, 237, 243); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
</body>
</html>

As of the latest Business Central build (BC 22.2), the events requested for above reports are still missing. Please let us know the major/minor release details in which the fix is available. as of the latest ticket is it fixed in Build ID: 10902 https://github.com/microsoft/ALAppExtensions/issues/22825

Versions:
Version: US Business Central 22.2 (Platform 22.0.57579.0 + Application 22.2.56969.57617)

**Comment by MarkoTrn** [comment]
Hello,

In Reports 1303 and 1305 events were added before they are added in reports 1304, 1306 and 1307 but under the different name:

- OnHeaderOnAfterGetRecordOnAfterUpdateVATOnLines
- OnLineOnAfterGetRecordOnAfterCalcTotals

They are raised on the same place with the same number and type of parameters
