### ISSUE TITLE
Event Request Approved almost 1 year ago, but not yet deliverd 

### ISSUE THREAD

**Issue by monicasuica** [microsoft/ALAppExtensions#24013]
Hi,

Could you please check the event request https://github.com/microsoft/ALAppExtensions/issues/19719 .
It was approved 1 year ago and it is not delivered.

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11478.
