### ISSUE TITLE
[Exposure Request] page 5097 "Create Task" - function ValidateTypeField

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#24015]
Please change function ValidateTypeField to protected:

protected procedure ValidateTypeField()

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
