### ISSUE TITLE
[Protected Request] ApplyUnapplyParameters on "Unapply Customer Entries", "Unapply Vendor Entries", "Unapply Employee Entries" pages

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#24024]
A new argument table `"Apply Unapply Parameters"` was implemented but for `"Unapply XYZ Entries"` pages there is no way to extend it and use it.
Maybe you can find a better solution but right now I suggest this:
- pull out `ApplyUnapplyParameters: Record "Apply Unapply Parameters"` variables from Actions triggers, make it `global` and `protected`
- (even better) remove `DocNo` and `PostingDate` variables and use `ApplyUnapplyParameters` instead of - similar way like it is on page `"Post Application"` (plus fill in other fields of ApplyUnapplyParameters, like `"Entry No."` to identify the source and so on)
- (and much much better) add `"VAT Reporting Date"` field to `"Apply Unapply Parameters"` table and use it on `Unapply` and `"Post Application"` pages

**Comment by RadoArvay** [comment]
Is there any progress with this request?

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 22009.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22011.
