### ISSUE TITLE
Master Data Management - Cannot Debug - cannot make it work for some scenarios

### ISSUE THREAD

**Issue by faludigabor** [microsoft/ALAppExtensions#24027]
**🕮 Describe the issue**

I am using Master Data extension to sync master data to multiple companies. Its rather difficult to investigate why things dont work because, we cannot debug the extension. Its not downloaded in the main app symbols
 

We cannot debug as the symbols are not included in the BASE, SYSTEM, APP packages. Thus no self service to fix it .
Can you help me or assist me to someone so I can resolve this issue?

**🔧 To Reproduce**

Download symbols and see if the table 7231 "Master Data Mgt. Coupling" is included in the app files . IT is not.

**📣 Expected behavior**

I would like to be able to debug it and fix it, perhaps improve logging?

![image](https://github.com/microsoft/ALAppExtensions/assets/16480091/24958dc5-897e-4495-ba4a-f25eb2446b72)
![image](https://github.com/microsoft/ALAppExtensions/assets/16480091/b1f478ed-77ab-4334-ad74-7c9a418ac22e)
![image](https://github.com/microsoft/ALAppExtensions/assets/16480091/fc096843-a04d-4c11-9ca0-ad093528b918)

**Comment by faludigabor** [comment]
Actually I can download it in a separate package sorry, closing this

**Comment by dbezzant** [comment]
Hi - Just found this post - can you elaborate what you mean by you 'downloaded it in a separate package'?
