### ISSUE TITLE
[Event Request] Report 5197 "Remove Contacts - Reduce" - OnPreReport(): Need a new event OnBeforeRunReduceRefineSegment

### ISSUE THREAD

**Issue by monicasuica** [microsoft/ALAppExtensions#24025]
Hi Team,

Is it possible to add an event to OnPreReport() trigger of the report.

We have codes that set the filters for more dataitems before the Remove Contacts report is run. Also please make the variable ReduceRefineSegment accessible via report extension (protected var).

![image](https://github.com/microsoft/ALAppExtensions/assets/47560247/345182a5-4bd6-4949-8b34-7eec8d8b1d53)

**Comment by monicasuica** [comment]
The publisher has been deliverd in BC22.4, but the variable ReduceRefineSegment accessible via report extension (protected var) in not there yet. Is it possible to deliver that too? 

Thannk you!

**Comment by AleksandricMarko** [comment]
Hi @monicasuica 
As far as I can see, "protected" is part of master branch and will be in BC 23.1
Be aware that we are changing scope of variables just with new major version.
