### ISSUE TITLE
[Request for External] table 1511 "Notification Entry" - InsertRec

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#24020]
Can you make the InsertRec procedure global in table 1511 "Notification Entry"?
I want to create a entry without sending it.
I know I can do this by setting the fields manually.
I have already done that.
But I think it is better to use existing procedures if possible.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
