### ISSUE TITLE
[Event Request] Report 5196 "Remove Contacts - Refine" - OnPreReport(): Need a new event OnBeforeRunReduceRefineSegment

### ISSUE THREAD

**Issue by monicasuica** [microsoft/ALAppExtensions#24026]
Hi Team,

Is it possible to add an event to OnPreReport() trigger of the report.

We have codes that set the filters for more dataitems before the Remove Contacts report is run. Also please make the variable ReduceRefineSegment accessible via report extension (protected var).
![image](https://github.com/microsoft/ALAppExtensions/assets/47560247/04318bf0-ff96-4d43-8ff8-5f7eb4564527)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
