### ISSUE TITLE
[Event Request] table 39 "Purchase Line" - OnBeforeCheckLineAmount

### ISSUE THREAD

**Issue by BharatVelosio** [microsoft/ALAppExtensions#24023]
Hi Team,

In table 39 "Purchase Line", please provide one more parameter the possibility to have OnBeforeCheckLineAmount event in procedure.

local procedure CheckLineAmount(MaxLineAmount: Decimal)

After begin at Line No 4354

OnBeforeCheckLineAmount(Rec, MaxLineAmount, IsHandled,CurrFieldNo);

<img width="424" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/133997930/3a6e445a-b4e6-4a37-bb68-5e438399fb5b">

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckLineAmount(var PurchaseLine: Record "Purchase Line"; MaxLineAmount: Decimal; var IsHandled: Boolean;CalledByFieldNo: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
