### ISSUE TITLE
[Event Request] Report 5197 "Remove Contacts - Reduce" - OnPreReport(): Need a new event OnBeforeRunReduceRefineSegment #19144

### ISSUE THREAD

**Issue by monicasuica** [microsoft/ALAppExtensions#24022]
Please check the request https://github.com/microsoft/ALAppExtensions/issues/19144.

It has been approved but not implemented yet.

Thank you!

**Comment by MarkoTrn** [comment]
Hello,

For changing accessibility of variable, please open new request.

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11415.
