### ISSUE TITLE
[Event Request] codeunit 130509 "Library - Sales": OnBeforeInsertCustomer

### ISSUE THREAD

**Issue by jthoerner-tso** [microsoft/ALAppExtensions#24037]
Hi AL-Team,

we need an event in the method "CreateCustomer" of the code unit 130509 "Library - Sales" to set certain values before inserting the customer.

The event should be thrown after `Clear(Customer)` and before `Customer.Insert(true)`.
![image](https://github.com/microsoft/ALAppExtensions/assets/63199461/60aa2cc3-dc42-4419-ba71-8a45286d042d)

Example:
```
    [BusinessEvent(true)]
    local procedure OnBeforeInsertCustomer(var Customer: Record Customer)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 58649.
