### ISSUE TITLE
Missing versions for the Storage Service API Enum

### ISSUE THREAD

**Issue by Krajzys** [microsoft/ALAppExtensions#24043]
**🕮 Describe the issue**

New versions for the Azure Storage Service Authorization module disappeared. In a PR some time ago new versions for the Storage Service API enum were added but I cannot find them now in the current main branch.

**🔧 To Reproduce**

1. Go to the repository on the main branch
2. Navigate to the [ALAppExtensions/Modules/System/Azure Storage Services Authorization/src/StorageServiceAPIVersion.Enum.al](https://github.com/microsoft/ALAppExtensions/tree/main/Modules/System/Azure%20Storage%20Services%20Authorization/src/StorageServiceAPIVersion.Enum.al) File
3. There are only two versions in the enum

**📣 Expected behavior**

There should be more versions because they were added in this PR #23608

**Comment by pri-kise** [comment]
@Krajzys can you check the PR from today.
https://github.com/microsoft/ALAppExtensions/pull/24198

**Comment by Krajzys** [comment]
@pri-kise Yep, it's all there. Thanks a lot for noticing.
