### ISSUE TITLE
Protected Procedure Request - page 490 "Acc. Schedule Overview" - UpdateColumnCaptions

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#24041]
Please could we have the UpdateColumnCaptions on page 490 "Acc. Schedule Overview" made protected so that we can call this from an extension object where we have added a No of Columns to display option.
thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11478.
