### ISSUE TITLE
[Request for External] table 847 "Cash Flow Forecast Entry" - procedure ShowSource

### ISSUE THREAD

**Issue by Mike-1984** [microsoft/ALAppExtensions#24044]
Hello colleagues,

Could you please change/remove the scope of procedure ShowSource?
We would like to call it from our (cloud) extension:

Before change:
```
    [Scope('OnPrem')]
    procedure ShowSource(ShowDocument: Boolean)
    var
        CFManagement: Codeunit "Cash Flow Management";
    begin
        if ShowDocument then
            CFManagement.ShowSourceDocument(Rec)
        else
            CFManagement.ShowSource(Rec);
    end;
```
Requested change:
```
    procedure ShowSource(ShowDocument: Boolean)
    var
        CFManagement: Codeunit "Cash Flow Management";
    begin
        if ShowDocument then
            CFManagement.ShowSourceDocument(Rec)
        else
            CFManagement.ShowSource(Rec);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11478.
