### ISSUE TITLE
 [Enum Request] table 914 "Posted Assemble-to-Order Link" Field - "Document Type"

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#24049]
Hello there, 

Can we change "Document Type" option on table "Posted Assemble-to-Order Link" to an Enum. 

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12672.
