### ISSUE TITLE
[Request for External] codeunit 1373 "Batch Posting Print Mgt.". procedure PrintJournal(RecRef: RecordRef)

### ISSUE THREAD

**Issue by Mike-1984** [microsoft/ALAppExtensions#24057]
Hello colleagues,

Could you please change/remove the scope of procedure PrintJournal?
We would like to call it from our (cloud) extension:

Before change:
```
    [Scope('OnPrem')]
    procedure PrintJournal(RecRef: RecordRef)
```
Requested change:
```
    procedure PrintJournal(RecRef: RecordRef)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11478.
