### ISSUE TITLE
[Protected var] page 576 "VAT Specification Subform" - AllowInvDisc

### ISSUE THREAD

**Issue by SimonTwilfer** [microsoft/ALAppExtensions#24058]
Is it possible to make the global variable "AllowInvDisc" (or alternatively "InvoiceDiscountAmountEditable") in page 576 "VAT Specification Subform" a protected variable?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11478.
