### ISSUE TITLE
Table 1706 "Deferral Posting Buffer" - new event in the (obsolete) procedure 'Update'

### ISSUE THREAD

**Issue by jensthomsenEV** [microsoft/ALAppExtensions#24063]
In table 1706 "Deferral Posting Buffer" there are 2 versions of the 'Update' produre: One that has been obsoleted and an overloaded whith just one parameter. In the overloaded version, there exist this event:

![image](https://github.com/microsoft/ALAppExtensions/assets/36921101/3ae9f040-4ba5-496d-be52-1e9e91e38e6f)

could the same event be implemented in the obsolete version of Update:

![image](https://github.com/microsoft/ALAppExtensions/assets/36921101/37b25b70-3ac7-46a8-b47e-7bf278ba9c4c)

We need this for our OnPrem customer

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 58687.
