### ISSUE TITLE
[External Function] codeunit 802 "Online Map Management" - MakeSelectionIfMapEnabled

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#24066]
Can you please make the function `MakeSelectionIfMapEnabled` externally available?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11478.
