### ISSUE TITLE
Request to add RefreshOnActivate = true property on Customers / Vendors / Items / Chart of Accounts and Bank Accounts pages. 

### ISSUE THREAD

**Issue by ShalinTechcronus** [microsoft/ALAppExtensions#24060]

**Comment by JakovljevicDusan** [comment]
This might be doable, but we cannot process it here as it might have impact on execution logic and performance. You can submit idea with explanation of business value on aka.ms/bcideas (or vote if there is existing one). It will be processed for the scope of next releases.
