### ISSUE TITLE
[Event Request] codeunit 799 "VAT Reporting Date Mgt" - OnAfterUpdateLinkedEntries

### ISSUE THREAD

**Issue by Mike-1984** [microsoft/ALAppExtensions#24070]
Hello colleagues,

Could you please create an event in codeunit 799 "VAT Reporting Date Mgt".
We would like to update additional tables/entries after UpdateLinkedEntries.

```
    procedure UpdateLinkedEntries(VATEntry: Record "VAT Entry")
    begin
        FeatureTelemetry.LogUsage('0000I9D', VATDateFeatureTok, 'VAT Date field populated');

        UpdateVATEntries(VATEntry);
        UpdateGLEntries(VATEntry);
        UpdatePostedDocuments(VATEntry);
        // >>>>>>
        OnAfterUpdateLinkedEntries(VATEntry);
        // <<<<<<
    end;
```

```
   [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateLinkedEntries(VATEntry: Record "VAT Entry");
    begin
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11478.
