### ISSUE TITLE
[Access Request] table 1003 "Job Planning Line" - Job

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#24086]
**🕮 Describe the request**

Could you please change the access scope of the variable  `Job` to protected

```al
protected var
    Job: Record Job;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11482.
