### ISSUE TITLE
Event Change Request - table 951 "Time Sheet Line" - OnBeforeShowLineDetails

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#24099]
Please could you add a OnBeforeShowLineDetails event in table 951 "Time Sheet Line". this will allow us to show the detail for another line type or amend showing details for an existing line type and take into account the ManagerRole parameter

    procedure ShowLineDetails(ManagerRole: Boolean)
    var
        TimeSheetLineResDetail: Page "Time Sheet Line Res. Detail";
        TimeSheetLineJobDetail: Page "Time Sheet Line Job Detail";
        TimeSheetLineServiceDetail: Page "Time Sheet Line Service Detail";
        TimeSheetLineAssembDetail: Page "Time Sheet Line Assemb. Detail";
        TimeSheetLineAbsenceDetail: Page "Time Sheet Line Absence Detail";
        IsHandled: Boolean;
    begin
        OnBeforeShowLineDetails(Rec,ManagerRole, IsHandled);
        IF IsHandled THEN
            exit;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowLineDetails(var TimeSheetLine: Record "Time Sheet Line"; ManagerRole: Boolean; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11504.
