### ISSUE TITLE
Commit in Gen. Journal Line give inconsistent payment import in the Journal.

### ISSUE THREAD

**Issue by navlarste** [microsoft/ALAppExtensions#241]
We use the Gen. Journal a lot for import payments from the bank. 
If the import stops with an Error the import will be commit and the import is inconsistent.

It is a risk the user posts the inconsistent journal.

It will be great if we had an opportunity to switch of the Commit temporary as SetSuppressCommit() for COD80 or COD90

**This Code trigger the Commit in the Journal.**

![image](https://user-images.githubusercontent.com/32996357/46274488-efc18b00-c559-11e8-99e5-23a68538478d.png)

**Debug stop with a Commit**
![image](https://user-images.githubusercontent.com/32996357/46274597-475ff680-c55a-11e8-8e23-ade7efc58cae.png)

**Comment by AlexanderYakunin** [comment]
Similar requests already completed

**Comment by navlarste** [comment]
@AlexanderYakunin Hi Where can I find the Similar request that you closed this issue with?
