### ISSUE TITLE
Event Request - page 914 "Assemble-to-Order Lines" OnBeforeShowDocument

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#24105]
HI,

On Table page 914 "Assemble-to-Order Lines", can we add a new Event Request called OnBeforeShowDocument at the beginning of action "Show Document".

            action("Show Document")
            {
                ApplicationArea = Assembly;
                Caption = 'Show Document';
                Image = View;
                ToolTip = 'Open the document that the selected line exists on.';

                trigger OnAction()
                var
                    ATOLink: Record "Assemble-to-Order Link";
                    SalesLine: Record "Sales Line";
                    IsHandled: Boolean;  // NEW
                begin
                    // NEW +
                    IsHandled := false;
                    OnBeforeShowDocument(Rec, IsHandled);
                    if IsHandled then
                        exit;
                    // NEW -

                    ATOLink.Get("Document Type", "Document No.");
                    SalesLine.Get(ATOLink."Document Type", ATOLink."Document No.", ATOLink."Document Line No.");
                    ATOLink.ShowAsm(SalesLine);
                end;
            }

    // NEW +
    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowDocument(var AssemblyLine: Record "Assembly Line"; var IsHandled: boolean)
    begin
    end;
    // NEW -

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11504.
