### ISSUE TITLE
Protected Var Request - page 5114 "Contact Profile Answers" - Cont

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#24102]
Please can you make Cont variable a protected var on page 5114 "Contact Profile Answers" so that we can access it from a PageExtension

        protected var
        Cont: Record Contact;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11529.
