### ISSUE TITLE
[Change Request] codeunit 5601 "FA Insert G/L Account" -  procedure GetPostingType

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#24112]
Hello, can you please change the procedure GetPostingType from local to a global procedure?

```
    procedure GetPostingType(var FALedgEntry: Record "FA Ledger Entry"): Enum "FA Posting Group Account Type"
    begin
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11529.
