### ISSUE TITLE
[Change Request] codeunit 5600 "FA Insert Ledger Entry" - procedure FAName

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#24129]
Hello, can you please change the lokal procedure FAName to global?

```
    procedure FAName(DeprBookCode: Code[10]): Text[200]
    var
        DepreciationCalc: Codeunit "Depreciation Calculation";
    begin
        exit(DepreciationCalc.FAName(FA, DeprBookCode));
    end;
```

**Comment by JesperSchulz** [comment]
The internal work item was closed as "Won't Fix" without any justification. Given this issue is rather old, I'd suggest to open a new issue, if this request still is valid, and we will revisit it.
