### ISSUE TITLE
Event Request - OnBeforePostResJnlLineConsume - codeunit 5987 "Serv-Posting Journals Mgt.

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#24137]
**🕮 Describe the request**

Please could we have a OnBeforePostResJnlLineConsume event in codeunit 5987 "Serv-Posting Journals Mgt."

    procedure PostResJnlLineConsume(var ServiceLine: Record "Service Line"; var ServShptHeader: Record "Service Shipment Header")
    var
        ResJnlLine: Record "Res. Journal Line";
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforePostResJnlLineConsume (ServiceLine,ServShptHeader,IsHandled);
    if IsHandled then
      exit;

[IntegrationEvent(false, false)]
local procedure OnBeforePostResJnlLineConsume (var ServLine: Record "Service Line"; var ServShptHeader: Record "Service Shipment Header"; var IsHandled: Boolean)
begin
end;

**Additional context**

This will allow us to post the usage resource journal and timesheet using another method which happens before the document is posted,

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11525.
