### ISSUE TITLE
[request-for-external] codeunit 7320 "Whse. Undo Quantity", procedure InsertPostedWhseShptLine

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#24144]
**🕮 Describe the request**

We need to call the function `local procedure InsertPostedWhseShptLine(OldPostedWhseShptLine: Record "Posted Whse. Shipment Line")` in codeunit `codeunit 7320 "Whse. Undo Quantity"` from our app. Can you make the function public for us?

**Additional context**
We need this function to apply changes to a implement an extended solution to undo shipments and avoid code clonng.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11529.
