### ISSUE TITLE
Event Request - OnBeforeCalculateResponseTimeHours - table 5901 "Service Item Line"

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#24146]
**🕮 Describe the request**

Please could we have an OnBeforeCalculateResponseTimeHours added to  table 5901 "Service Item Line".

    procedure CalculateResponseTimeHours(): Decimal
    var
      IsHandled: Boolean;
      ResponseTimeHours: Decimal;
    begin
        IsHandled := false;
        OnBeforeCalculateResponseTimeHours(Rec, ResponseTimeHours, IsHandled);
        IF IsHandled THEN
            EXIT(ResponseTimeHours);

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculateResponseTimeHours(var ServiceItemLine: Record "Service Item Line"; var ResponseTimeHours: Decimal; var IsHandled: Boolean);
    begin
    end;

**Additional context**

This will allow us to change how the response is calculated, we have setup for this based on service order type and priority

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11547.
