### ISSUE TITLE
Protected Var Request - SkipResponseTimeHrsUpdate - table 5901 "Service Item Line"

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#24147]
**🕮 Describe the request**

Please could you make var SkipResponseTimeHrsUpdate on table 5901 "Service Item Line" a protected var
Protected Var
SkipResponseTimeHrsUpdate: Boolean;

**Additional context**

This will allow us to control this in an extension object to avoid UpdateResponseTimeHours

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
