### ISSUE TITLE
Event Request OnBeforeCalculateDiscount in table 5902 "Service Line"

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#24148]
**🕮 Describe the request**

Please could you add a OnBeforeCalculateDiscount in table 5902 "Service Line"

    local procedure CalculateDiscount()
    var
        Discounts: array[4] of Decimal;
        i: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalculateDiscount(Rec, CurrFieldNo, IsHandled);
        IF IsHandled THEN BEGIN
            OnAfterCalculateDiscount(Rec);
            exit;
        END;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculateDiscount(VAR ServiceLine: Record "Service Line"; CurrFieldNo: Integer; VAR IsHandled: Boolean)
    begin
    end;

**Additional context**

This allows us to calculate the discount in s slightly different way and still refer to the orginal discount value which we can not do with 
OnAfterCalculateDiscount

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11547.
