### ISSUE TITLE
[Access Request] report 1094 "Job Transfer to Sales Invoice"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#24141]
**🕮 Describe the request**
Could you please change the access scope of the variable `Job` to protected?
```al
protected var
//+Change
    Job: Record Job;
//-Change
    InvoiceNo: Code[20];
    NewInvoice: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11529.
