### ISSUE TITLE
[Enum Request] codeunit 6620 "Copy Document Mgt." / report 5979 "Copy Service Document [Service Contract Type From]

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#24151]
**🕮 Describe the request**
Could you please refactor the procedures in the `codeunit 6620 "Copy Document Mgt."` and in the report `report 5979 "Copy Service Document"` to a new Enum _Enum "Service Contry Type From"_

All Functions should be replaced by new ones, that accept the enum:
Additionally could you please add events at the specific locations.

e.g. the global in _report 5979 "Copy Service Document"_.
```al

//DocType: Option Quote,Contract; -> Should be replaced with New Enum
```

**Additional context**

It should be possible to extend the Copy Service document report with additional document types.

**Comment by pri-kise** [comment]
@JesperSchulz is there any chance that this Enum will make it into BC23?
I don't need all the necessary events -> Those can added in a CU, but since Enums are only added on major versions this would very helpful, if we don't have to wait until BC24

**Comment by JesperSchulz** [comment]
@AlexanderYakunin, will this enum request make it in time for BC23?

**Comment by AlexanderYakunin** [comment]
May be difficult, but let me check what is possible here.

**Comment by AlexanderYakunin** [comment]
I checked and can say that this change is not needed for CopyDocumentMgt at all, because procedure procedure ServContractHeaderDocType(DocType: Option): Integer is not used anywhere in base app and should be obsoleted and removed.

As for report Copy Service Document, I assume you want to extend enum "Service Contract Type" and therefore this enum should be implemented instead of option in variable DocType? Is this correct assumption?

**Comment by pri-kise** [comment]
@AlexanderYakunin no not exactly.

Currently the `report 5979 "Copy Service Document"` enables us to copy from a ServiceContractHeader of Type "Quote" Or "Contract". 
The enum `enum 5965 "Service Contract Type"` contains more values, than these two.

To add a new Enum Value to the `Service Contract Type` we would need an additional Enum _Enum "Service Contract Type From"_ to enable the copy from our new ServiceContractType.

Similiar to the `report 292 "Copy Sales Document"`, where we can add new values to the Enum `FromDocType: Enum "Sales Document Type From";`.

Additionally we would need appropriate events in the `report 5979 "Copy Service Document"`

e.g. here:
```al
local procedure ValidateDocNo()
begin
    if DocNo = '' then
        FromServContractHeader.Init()
    else begin
        FromServContractHeader.Init();
        //+Change
        //-FromServContractHeader.Get(DocType, DocNo);
        FromServContractHeader.Get(CopyDocMgt.GetServiceContractType(DocType), DocNo);
        //-Change
        if FromServContractHeader."Customer No." <> ServContractHeader."Customer No." then
            Error(Text002, ServContractHeader.FieldCaption("Customer No."));
        if FromServContractHeader."Currency Code" <> ServContractHeader."Currency Code" then
            Error(Text002, ServContractHeader.FieldCaption("Currency Code"));
        FromServContractHeader.CalcFields(Name);
    end;
end;
```

```al
//New Procedure in Copy Doc. Mgt.
procedure GetServiceContractType(FromDocType: Enum "Service Contract Type From") ToDocType : Enum "Service Contract Type"
var
    ServContractHeader: Record "Service Contract Header";
begin
    case DocType of
        ServDocType::Quote:
           ToDocType := Enum::"Service Contract Type"::Quote;
        ServDocType::Contract:
           ToDocType := Enum::"Service Contract Type"::Contract;
        else
            OnGetServiceContractTypeCaseElse(FromDocType, ToDocType);
    end;
end;
```

Hopefully it's now easier to understand what changes I request.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14443.
