### ISSUE TITLE
[access request] report 5979 "Copy Service Document"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#24152]
**🕮 Describe the request**

Could youp please change the access scope of the following varialbes to protected?

```al
protected var
    ServContractHeader: Record "Service Contract Header";
    FromServContractHeader: Record "Service Contract Header";
    //DocType: Option Quote,Contract; // Should be updated to new extensible Enum at first
    DocNo: Code[20];
```

Related Issue: https://github.com/microsoft/ALAppExtensions/issues/24151
The DocType (ServiceContractTypeFrom) should be made to protected, too. But at first this should be refactored to an extensible enum.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11551.
