### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line - OnBeforeCheckRunItemValuePosting

### ISSUE THREAD

**Issue by BadaboomDev** [microsoft/ALAppExtensions#24153]
The following event modification is required:

Set Sender to true

```
 [IntegrationEvent(true, false)]
    local procedure OnBeforeCheckRunItemValuePosting(var ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11547.
