### ISSUE TITLE
Call Existing Event OnValidateContractNoOnBeforeContractDiscountFind in table 5902 "Service Line"

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#24150]
**🕮 Describe the request**

Please could you call OnValidateContractNoOnBeforeContractDiscountFind in table 5902 "Service Line" from 2 more places in the code

field(5936; "Contract No."; Code[20])
trigger OnValidate()

                                        Type::Item:
                                            begin
                                                ContractServDisc.Init();
                                                ContractServDisc."Contract Type" := ContractServDisc."Contract Type"::Contract;
                                                ContractServDisc."Contract No." := ServContractHeader."Contract No.";
                                                ContractServDisc.Type := ContractServDisc.Type::"Service Item Group";
                                                ContractServDisc."No." := ServItem."Service Item Group Code";
                                                ContractServDisc."Starting Date" := "Posting Date";
                                                OnValidateContractNoOnBeforeContractDiscountFind(Rec, ContractServDisc, ServItem);
                                                CODEUNIT.Run(CODEUNIT::"ContractDiscount-Find", ContractServDisc);
                                                "Contract Disc. %" := ContractServDisc."Discount %";
                                            end;
                                        Type::Resource:
                                            begin
                                                Res.Get("No.");
                                                ContractServDisc.Init();
                                                ContractServDisc."Contract Type" := ContractServDisc."Contract Type"::Contract;
                                                ContractServDisc."Contract No." := ServContractHeader."Contract No.";
                                                ContractServDisc.Type := ContractServDisc.Type::"Resource Group";
                                                ContractServDisc."No." := Res."Resource Group No.";
                                                ContractServDisc."Starting Date" := "Posting Date";
                                                OnValidateContractNoOnBeforeContractDiscountFind(Rec, ContractServDisc, ServItem);
                                                CODEUNIT.Run(CODEUNIT::"ContractDiscount-Find", ContractServDisc);
                                                "Contract Disc. %" := ContractServDisc."Discount %";
                                            end;
                                        Type::Cost:
                                            begin
                                                ServCost.Get("No.");
                                                ContractServDisc.Init();
                                                ContractServDisc."Contract Type" := ContractServDisc."Contract Type"::Contract;
                                                ContractServDisc."Contract No." := ServContractHeader."Contract No.";
                                                ContractServDisc.Type := ContractServDisc.Type::Cost;
                                                ContractServDisc."No." := "No.";
                                                ContractServDisc."Starting Date" := "Posting Date";
                                                OnValidateContractNoOnBeforeContractDiscountFind(Rec, ContractServDisc, ServItem);
                                                CODEUNIT.Run(CODEUNIT::"ContractDiscount-Find", ContractServDisc);
                                                "Contract Disc. %" := ContractServDisc."Discount %";
                                            end;

**Additional context**

This will allow us to determine how the discounts are found for resources and Costs aswell as items

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11547.
