### ISSUE TITLE
Event Request - OnBeforeCalculateInvoiceDiscountBeforeIsServiceChargeUpdated - codeunit 5950 "Service-Calc. Discount"

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#24164]
**🕮 Describe the request**

Please can the event OnBeforeCalculateInvoiceDiscountBeforeIsServiceChargeUpdated  be added to codeunit 5950 "Service-Calc. Discount"

    local procedure CalculateInvoiceDiscount(var ServHeader: Record "Service Header"; var ServiceLine: Record "Service Line"; var ServiceLine2: Record "Service Line")
    var
        TempVATAmountLine: Record "VAT Amount Line" temporary;
        SalesSetup: Record "Sales & Receivables Setup";
        DiscountNotificationMgt: Codeunit "Discount Notification Mgt.";
        ServiceChargeLineNo: Integer;
        ApplyServiceCharge: Boolean;
        IsHandled: Boolean;
    begin
        OnBeforeCalcServDiscount(ServHeader);

        SalesSetup.Get();
        with ServiceLine do begin
            LockTable();
            ServHeader.TestField("Customer Posting Group");
            CustPostingGr.Get(ServHeader."Customer Posting Group");

            IsHandled := false;
            OnBeforeIsServiceChargeUpdated(ServiceLine,CustPostingGr,IsHandled);
            if not IsHandled then
                if not IsServiceChargeUpdated(ServiceLine) then begin
                    ServiceLine2.Reset();
                    ServiceLine2.SetRange("Document Type", "Document Type");
                    ServiceLine2.SetRange("Document No.", "Document No.");

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculateInvoiceDiscountBeforeIsServiceChargeUpdated(var ServiceLine: Record "Service Line";CustPostingGr: Record "Customer Posting Group";var IsHandled: Boolean)
    begin
    end;

**Additional context**

This will allow us to calculate service discount when the CustPostingGr."Service Charge Acc." = ''.  As it currently errors. we do not want a service charge line added but just to calculate the discount.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 58993.
