### ISSUE TITLE
[Event Change Request] table 111 "Sales Shipment Line" - change event parameter "OnInsertInvLineFromShptLineOnAfterCalcQuantities"

### ISSUE THREAD

**Issue by Kottika** [microsoft/ALAppExtensions#24165]
Hello, 

we need the variable SalesOrderLine in the event OnInsertInvLineFromShptLineOnAfterCalcQuantities as var. Can you set this please?

      [IntegrationEvent(false, false)]
      local procedure OnInsertInvLineFromShptLineOnAfterCalcQuantities(var SalesLine: Record "Sales Line"; var SalesOrderLine: Record "Sales Line")
      begin
      end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 58993.
