### ISSUE TITLE
[Access Request] report 1322 "Standard Purchase - Order"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#24178]
**🕮 Describe the request**

Could you please change the access scope of the following variables to protected?

```al
protected var    
    RespCenter: Record "Responsibility Center"; // Name to be changed to ResponsibilityCenter with making it protected
    BuyFromContact: Record Contact;
    PayToContact: Record Contact;
    TotalSubTotal: Decimal;
    TotalAmount: Decimal;
    TotalInvoiceDiscountAmount: Decimal;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11581.
