### ISSUE TITLE
[Translations/Extensbility Bug] report 1304 "Standard Sales - Quote" - ArchiveSalesDocument

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#24170]
**🕮 Describe the request**
The question to archive a sales quote isn't shown in the user language, when the "Language Code" of the SalesHeader is different.
Therefore I sugges the following change for the "Sales Quote Report".

```al
if not IsReportInPreviewMode() and
    (CurrReport.UseRequestPage and ArchiveDocument or
    not CurrReport.UseRequestPage and (SalesSetup."Archive Quotes" <> SalesSetup."Archive Quotes"::Never))
then
    case SalesSetup."Archive Quotes" of
        SalesSetup."Archive Quotes"::Always:
            ArchiveManagement.ArchSalesDocumentNoConfirm(Header);
        SalesSetup."Archive Quotes"::Question:
            //+Change
            //-ArchiveManagement.ArchiveSalesDocument(Header);
            begin
                SetLanguage(Language.GetUserLanguageCode()); //Set Language to the User Language
                ArchiveManagement.ArchiveSalesDocument(Header);
                SetLanguage("Language Code"); //Set Language to the Document Lanuage to remain extensibility for ReportExtensions, that expect, that language was changed.
            end;
            //-Change
    end;
```

**Additional context**
It is very confusing if a german user recieves this question in english or some other report language.

**Comment by pri-kise** [comment]
In my opinion this is a bug, but I would be willing to fix it as outlined above in the BaseApp Pilot.

I did post it here - at first only for a public place for discussion, if this is a bug or not.

**Comment by JesperSchulz** [comment]
Got it. But if it's a real bug, the issue can only be reported in two ways:
1) If a customer is affected by this, the issue must go through support. That way we ensure that SLAs are met and that all supported versions of Business Central will receive the fix.
2) No customer is as such affected by it / workarounds are in place: You can decide to fix the problem yourself or hope another member of the community does so, by logging an issue in the BaseApp Contribution Pilot.

In this repository we ideally only accept extensibility requests and extensibility bugs (bugs in extensibility requests we've processed). We do accept the occasional bug on other extensibility related issues, which don't have customer impact, but which are needed to be resolved for a partner to bring their extension to market. But we cannot commit to any timelines for these bugs and rather often, it takes quite a while for us to get to those issues.

I know you know most of this, but I thought I'd mention it once more for others who might stumble over this issue :-)

**Comment by JakovljevicDusan** [comment]
Closing as it is got implemented via related contribution to BaseApp Pilot (BusinessCentralApps repo).
