### ISSUE TITLE
[Event Change Request] report 99003802 "Copy Production Order Document" OnAfterCopyProdLines

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#24175]
**🕮 Describe the request**
Could please add the sender to the event OnAfterCopyProdLines, that we can access our own request page settings from this event?
```al
//+Change
//-[IntegrationEvent(false, false)]
[IntegrationEvent(true, false)]
//-Change
local procedure OnAfterCopyProdLines(var ToProdOrderLine: Record "Prod. Order Line"; FromProdOrderLine: Record "Prod. Order Line"; IncludeHeader: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 58995.
