### ISSUE TITLE
Event Change Request - codeunit 7322 "Create Inventory Pick/Movement" - OnCreateATOPickLineOnAfterCalcQtyToPickBase

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#24197]
**🕮 Describe the request**

in this Issue https://github.com/microsoft/ALAppExtensions/issues/22031 we reqeusted a similar event, but QtyToPickBase parameter was requested to be a var.

    [IntegrationEvent(false, false)]
    local procedure OnCreateATOPickLineOnAfterCalcQtyToPickBase(var RemQtyToPickBase: Decimal; var QtyToPickBase: Decimal; ATOSalesLine: Record "Sales Line")
    begin
    end;

**Additional context**

This allows us to amend the QtyToPickBase

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 59019.
