### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" -  procedure PostVAT

### ISSUE THREAD

**Issue by cdscala** [microsoft/ALAppExtensions#24191]
Dear ALAppExtensions Team,

We would like to request the following change. As parameter TaxDetail is a value the reference in the InsertVAT function that is calling the global is lost.
Global var TaxDetail as temporary.
For OnBeforePostVAT integrationevent, the var TaxDetail parameter is added.
For OnAfterPostVAT integrationevent, the parameter TaxDetail is a reference parameter in the change requested.
BC version 22.3.58346.58612

codeunit 12 "Gen. Jnl.-Post Line"

```
//-->original
var
        TaxDetail: Record "Tax Detail";
//<--original
**//--> change request
var
       TaxDetail: Record "Tax Detail" temporary;
//<-- change request**


[IntegrationEvent(true, false)]
//-->original
local procedure OnBeforePostVAT(var GenJnlLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; VATPostingSetup: Record "VAT Posting Setup"; var IsHandled: Boolean; var AddCurrGLEntryVATAmt: Decimal; var NextConnectionNo: Integer)
//<--original

**//--> change request
local procedure OnBeforePostVAT(var GenJnlLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; VATPostingSetup: Record "VAT Posting Setup"; var TaxDetail: Record "Tax Detail"; var IsHandled: Boolean; var AddCurrGLEntryVATAmt: Decimal; var NextConnectionNo: Integer)
//<-- change request**

-------------------------------------------------------------------------------------------------------------------------------------------

 [IntegrationEvent(true, false)]
//-->original
local procedure OnAfterPostVAT(GenJnlLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; VATPostingSetup: Record "VAT Posting Setup"; TaxDetail: Record "Tax Detail"; var NextConnectionNo: Integer; var AddCurrGLEntryVATAmt: Decimal; AddCurrencyCode: Code[10]; UseCurrFactorOnly: Boolean)
//<--original

**//--> change request
local procedure OnAfterPostVAT(GenJnlLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; VATPostingSetup: Record "VAT Posting Setup";var TaxDetail: Record "Tax Detail"; var NextConnectionNo: Integer; var AddCurrGLEntryVATAmt: Decimal; AddCurrencyCode: Code[10]; UseCurrFactorOnly: Boolean)
//<-- change request**
```

![image](https://github.com/microsoft/ALAppExtensions/assets/26973890/fe6e051e-4f05-4c51-910e-bc667bff3e62)
![image](https://github.com/microsoft/ALAppExtensions/assets/26973890/98cb7d05-783a-4a10-a8fc-9292a46c0b10)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15512.
