### ISSUE TITLE
Page 492 "Item Availability by Location" -> ItemPeriodLength Enum "Analysis Period Type" Need to be set as "protected var"

### ISSUE THREAD

**Issue by HRA007** [microsoft/ALAppExtensions#24190]
Hallo,

**🕮 Page 492 "Item Availability by Location" -> Enum "Analysis Period Type" should be protected var**

For our Customer we need the Variable (ItemPeriodLength: Enum "Analysis Period Type") in Page 492 "Item Availability by Location" to be "protected var" because we need to Validate it in a PageExt 

[PageExt.txt](https://github.com/microsoft/ALAppExtensions/files/12123649/PageExt.txt)

Kind Regards
Hesham

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11581.
