### ISSUE TITLE
Event Change Request codeunit 1026 "Job Link Usage" - OnMatchUsageUnspecifiedOnBeforeCheckPostedQty

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#24200]
**🕮 Describe the request**

Hi, is it possible to update the code used for this request https://github.com/microsoft/ALAppExtensions/issues/23208# please. it should have handled the actual if statement that checks the posted qty. aswell

It was meant to be:
 OnMatchUsageUnspecifiedOnBeforeCheckPostedQty(JobPlanningLine, JobLedgerEntry, RemainingQtyToMatch,IsHandled);
 if not IsHandled then begin
                RemainingQtyToMatchPerUoM := UOMMgt.CalcQtyFromBase(RemainingQtyToMatch, JobPlanningLine."Qty. per Unit of Measure");
                if (RemainingQtyToMatchPerUoM = JobPlanningLine."Qty. Posted") and (JobPlanningLine."Remaining Qty. (Base)" = 0) then
                    exit;
end;

**Additional context**
This allows us to have flexible time lines that do not need to have a remaining qty and still create the usage link to these lines.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11637.
