### ISSUE TITLE
Event Request: On `Table 5050 Contact` method `CreateSalesQuoteFromContact`

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#24205]
**🕮 Describe the request**
In the method `CreateSalesQuoteFromContact` on `Table 5050 Contact` I require events that triggers after the sales quote for the contact has been created, but before the page is shown. And one more. This is for multiple reasons
1) I would like to trigger interactive UI elements when a user creates a quote from this function, but only when using this function
2) I would like to be able to avoid the page being shown (Handled pattern).

I therefore request two new events as shown below:
- `OnAfterCreateSalesQuoteFromContactBeforeShowPage`: this allows me to prevent the page from showing, show a different one or do other kinds of processing **before** the page opens.
- `OnAfterCreateSalesQuoteFromContact`: this allows me to do things **after** the page has been opened to the user. The sales quite page is not ran modally, so this allows me to sneak in some interaction logic.

**Additional context**

````
    procedure CreateSalesQuoteFromContact()
    var
        SalesHeader: Record "Sales Header";
        IsHandled: Boolean; // new line
    begin
        ...
        SalesHeader.Insert(true);
        SalesHeader.Validate("Document Date", WorkDate());
        SalesHeader.Validate("Sell-to Contact No.", "No.");
        SalesHeader.Modify();
        OnAfterCreateSalesQuoteFromContactBeforeShowPage(Contact, SalesHeader, IsHandled); // new line
        if (IsHandled) then exit; // new line
        PAGE.Run(PAGE::"Sales Quote", SalesHeader);
        OnAfterCreateSalesQuoteFromContact(Contact, SalesHeader); // new line
    end;
````

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 59042.
