### ISSUE TITLE
[Enum Request] Table 99000754 Work Center - Field "Unit Cost Calculation"

### ISSUE THREAD

**Issue by tekoWeMa** [microsoft/ALAppExtensions#24210]
Hi
Can we change the Option Field "Unit Cost Calculation" to an Enum? 

We would like to extend this field in our Code.

Looking forward to your answer, thanks and best regards

**Comment by AlexanderYakunin** [comment]
This is already done for v.23

        field(50; "Unit Cost Calculation"; Enum "Unit Cost Calculation Type")
        {
            Caption = 'Unit Cost Calculation';
        }
