### ISSUE TITLE
[Event Parameter Change] Codeunit 333 "Req. Wksh.-Make Order" - OnBeforeCheckInsertFinalizePurchaseOrderHeader - (Reopened)

### ISSUE THREAD

**Issue by srol001195** [microsoft/ALAppExtensions#24218]
Dear ALAppExtensions,

We reviewed your response to our previous issue #23256, that the **CheckCustomer** parameter does not exist. However, we verified that as of **Update 22.3 for Dynamics 365 Business Central 2023 Release Wave 1** (Version 58453 released 7/10/2023), the **CheckCustomer** boolean is still a parameter for the local procedure **CheckInsertFinalizePurchaseOrderHeader** in **Codeunit 333 "Req. Wksh.-Make Order"**.

`local procedure CheckInsertFinalizePurchaseOrderHeader(RequisitionLine: Record "Requisition Line"; var PurchOrderHeader: Record "Purchase Header"; UpdateAddressDetails: Boolean; CheckCustomer: Boolean): Boolean`

With this clarification, please consider reviewing our event change request. I copied over the details from the previous request for convenience:

### REFERENCED REQUEST
Please consider adding the **CheckCustomer** Boolean parameter to the event signature for **OnBeforeCheckInsertFinalizePurchaseOrderHeader** in Codeunit 333 "**Req. Wksh.-Make Order**":

```
codeunit 333 "Req. Wksh.-Make Order"
{
...
local procedure CheckInsertFinalizePurchaseOrderHeader(RequisitionLine: Record "Requisition Line"; var PurchOrderHeader: Record "Purchase Header"; UpdateAddressDetails: Boolean; CheckCustomer: Boolean): Boolean
    var
        CheckInsert: Boolean;
    begin
...
        OnBeforeCheckInsertFinalizePurchaseOrderHeader(RequisitionLine, PurchOrderHeader, CheckInsert, OrderCounter, PrevPurchCode, PrevLocationCode, PrevShipToCode, UpdateAddressDetails, CheckCustomer); //<EVENT CHANGE>
        exit(CheckInsert);
    end;
...
[IntegrationEvent(true, false)]
    local procedure OnBeforeCheckInsertFinalizePurchaseOrderHeader(RequisitionLine: Record "Requisition Line"; var PurchaseHeader: Record "Purchase Header"; var CheckInsert: Boolean; var OrderCounter: Integer; var PrevPurchCode: Code[10]; PrevLocationCode: Code[10]; var PrevShipToCode: Code[10]; var UpdateAddressDetails: Boolean; CheckCustomer: Boolean) //<SIGNATURE CHANGE>
    begin
    end;
```

Thank you,
SR

**Comment by TKapitan** [comment]
Hi @srol001195 
I have checked the procedure, and it looks like that the parameter CheckCustomer is part of the localization you are using. 

Definition of this procedure from 22.3 W1

`local procedure CheckInsertFinalizePurchaseOrderHeader(RequisitionLine: Record "Requisition Line"; var PurchOrderHeader: Record "Purchase Header"; UpdateAddressDetails: Boolean): Boolean`

Unfortunately, this repo is for W1 functionality only; this was probably the reason why it was closed previously.

**Comment by srol001195** [comment]
@TKapitan,
Appreciate the explanation... surprised that localization differences would even involve things like this! Our team will search for a different solution then.
Thank you,
SR

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11637.
