### ISSUE TITLE
[extensibility request] Table "Transfer Line" protected var TrackingBlocked

### ISSUE THREAD

**Issue by tg-navcom** [microsoft/ALAppExtensions#24211]
Object: **Table 5741 "Transfer Line"**
Please make variable `TrackingBlocked` as protected var.

Reason: We are making a change for one of our clients, whose reservations work very differently than in the standard.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11640.
