### ISSUE TITLE
Wrongly constructed standard procedure causing wrong event trigger behavior in Sales Line table

### ISSUE THREAD

**Issue by PerVL** [microsoft/ALAppExtensions#24215]
**🕮 Describe the issue**

A clear and concise description of what the issue/improvement is, which you want to address.

**🔧 To Reproduce**

**📣 Expected behavior**

**Screenshots**

**Additional context**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11637.
