### ISSUE TITLE
[Event Parameter Request] Codeunit 5763 Whse.-Post Shipment - procedure PostSourceDocument - event OnPostSourceDocumentAfterGetWhseShptHeader   

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#24228]
We would like the parameter/-s WhseSetup (var) and  SuppressCommit to the following event.

Codeunit 5763 Whse.-Post Shipment - procedure PostSourceDocument - event OnPostSourceDocumentAfterGetWhseShptHeader  

Original:		
```
OnPostSourceDocumentAfterGetWhseShptHeader(WhseShptLine, WhseShptHeader);

    [IntegrationEvent(false, false)]
    local procedure OnPostSourceDocumentAfterGetWhseShptHeader(WhseShptLine: Record "Warehouse Shipment Line"; var WhseShptHeader: Record "Warehouse Shipment Header")
    begin
    end;
```	

Change:
```
OnPostSourceDocumentAfterGetWhseShptHeader(WhseShptLine, WhseShptHeader,WhseSetup,SuppressCommit);

    [IntegrationEvent(false, false)]
    local procedure OnPostSourceDocumentAfterGetWhseShptHeader(WhseShptLine: Record "Warehouse Shipment Line"; var WhseShptHeader: Record "Warehouse Shipment Header"; var WhseSetup: Record "Warehouse Setup"; SuppressCommit : Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11637.
