### ISSUE TITLE
[Event Parameter Request] Codeunit 80 Sales-Post - procedure PostUpdateOrderLine - event OnPostUpdateOrderLineOnBeforeGetQuantityShipped    

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#24227]
We would like the parameter/-s SalesHeader to the following event.

Codeunit 80 Sales-Post - procedure PostUpdateOrderLine - event OnPostUpdateOrderLineOnBeforeGetQuantityShipped  
		
Original:
```
OnPostUpdateOrderLineOnBeforeGetQuantityShipped(TempSalesLine, IsHandled);

[IntegrationEvent(false, false)]
local procedure OnPostUpdateOrderLineOnBeforeGetQuantityShipped(TempSalesLine: Record "Sales Line"; var IsHandled: Boolean)
begin
end;
```

Change:
```
OnPostUpdateOrderLineOnBeforeGetQuantityShipped(TempSalesLine, SalesHeader,IsHandled);

[IntegrationEvent(false, false)]
local procedure OnPostUpdateOrderLineOnBeforeGetQuantityShipped(TempSalesLine: Record "Sales Line"; var SalesHeader : Record "Sales Header"; var IsHandled: Boolean)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11826.
