### ISSUE TITLE
[Event-Request] codeunit 1012 "Job Jnl.-Post Line" - OnAfterItemPostingDone() 

### ISSUE THREAD

**Issue by moomencegekadsa** [microsoft/ALAppExtensions#24224]
Hello Microsoft,

In [https://github.com/microsoft/ALAppExtensions/issues/16110](https://github.com/microsoft/ALAppExtensions/issues/16110) we requested an additional event for codeunit 1012 "Job Jnl.-Post Line", which was approved. Unfortunately this event is not implemented yet, so we request again that you would do so. Thanks in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11653.
