### ISSUE TITLE
Table 5740 Transfer Header - OnBeforeVerifyNoInboundWhseHandlingOnLocation

### ISSUE THREAD

**Issue by dario-zaniboni** [microsoft/ALAppExtensions#24231]
I kindly request a new publisher within table 5740, in order to allow direct transfers even in the case of whse. mgt. on the inbound location (InvtSetup."Direct Transfer Posting"::"Direct Transfer" is not a valid option for process reasons).

	procedure VerifyNoInboundWhseHandlingOnLocation(LocationCode: Code[10])
	var
		Location: Record Location;
		//>> NEW
		IsHandled: Boolean;
		//<< NEW
	begin
		//>> NEW
		OnBeforeVerifyNoInboundWhseHandlingOnLocation(LocationCode, IsHandled);
		if IsHandled then
			exit;
		//<< NEW
		
		if not Location.Get(LocationCode) then
			exit;

		Location.TestField("Directed Put-away and Pick", false);

		GetInventorySetup();
		if InvtSetup."Direct Transfer Posting" = InvtSetup."Direct Transfer Posting"::"Direct Transfer" then
			exit;

		Location.TestField("Require Put-away", false);
		Location.TestField("Require Receive", false);
	end;

	//>> NEW
	[IntegrationEvent(false, false)]
	local procedure OnBeforeVerifyNoInboundWhseHandlingOnLocation(LocationCode: Code[10]; var IsHandled: Boolean)
	begin
	end;
	//<< NEW

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11637.
