### ISSUE TITLE
Table 5741 Transfer Line - OnCheckWarehouseOnBeforeShowDialog >> Change param

### ISSUE THREAD

**Issue by dario-zaniboni** [microsoft/ALAppExtensions#24242]
I kindly request to modify the existing publisher, passing variable "ShowDialog" in var:

```
//>> OLD
[IntegrationEvent(false, false)]
local procedure OnCheckWarehouseOnBeforeShowDialog(TransferLine: Record "Transfer Line"; Location: Record Location; ShowDialog: Option " ",Message,Error; var DialogText: Text[50])
begin
end;
//<< OLD

//>> NEW
[IntegrationEvent(false, false)]
local procedure OnCheckWarehouseOnBeforeShowDialog(TransferLine: Record "Transfer Line"; Location: Record Location; var ShowDialog: Option " ",Message,Error; var DialogText: Text[50])
begin
end;
//<< NEW
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11637.
