### ISSUE TITLE
Codeunit "Format Address" - internal procedure VendorRemitToAddress

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#24243]
**🕮 Describe the issue**

I don't think internal procedure VendorRemitToAddress should be internal. (Codeunit "Format Address")

**🔧 To Reproduce**

1. Make a copy of Report 10412 (extending reports with integer dataitems is next to impossible, so we made a copy)
2. we are on BC 22.2. Instantly get error on line 1192 "FormatAddr.VendorRemitToAddress(RemitAddress, CheckToAddress);" ... Cannot convert from 'Record "Remit-To Address"' to 'array[8] of Text[100]'.
3. I believe the intention was for the procedure call in line 1192 to use:
- "internal" procedure VendorRemitToAddress(var RemitAddress: Record "Remit Address"; var ArrayAddress: array[8] of Text[100])
-  But in my PTE object, it can't because the procedure is marked as internal.
-  it seems to point to procedure VendorRemitToAddressVendorRemitToAddress(var RemitAddress: Record "Remit Address"; var RemitAddressBuffer: Record "Remit Address Buffer") - hence the error about parameter types not being set correctly (or perhaps it's trying to use the obsolete one???).
4. can we remove the internal designation from this procedure? 

**📣 Expected behavior**

Copying Report 10412 to a new PTE report should not cause any problems. Workaround was to copy the internal procedure as a local procedure to my PTE report.

**Screenshots**

**Additional context**

Related question: why does the procedure below, when it calls FormatAddr, only reference the Buffer record for name and country/Region? why not for all 9 fields? to be honest, not sure the purpose of the RemitAddressBuffer in this context. But would be nice to have an event to correct any unintended consequences of the 7 fields not using RemitAddressBuffer.

    internal procedure VendorRemitToAddress(var RemitAddress: Record "Remit Address"; var ArrayAddress: array[8] of Text[100])
    var
        RemitAddressBuffer: Record "Remit Address Buffer";
        IsHandled: Boolean;   // new variable
    begin
        VendorRemitToAddress(RemitAddress, RemitAddressBuffer);

        // start new code >>

        OnBeforeFormatAddr(ArrayAddress, RemitAddress, RemitAddressBuffer, IsHandled);  <<-- New event would be nice.
        if IsHandled then
            exit;       

        // end new code <<

        FormatAddr(
            ArrayAddress,
            RemitAddressBuffer.Name,
            RemitAddress."Name 2",    <<-- why not RemitAddressBuffer
            RemitAddress.Contact,    <<-- why not RemitAddressBuffer
            RemitAddress.Address,    <<-- why not RemitAddressBuffer
            RemitAddress."Address 2",    <<-- why not RemitAddressBuffer
            RemitAddress.City,    <<-- why not RemitAddressBuffer
            RemitAddress."Post Code",    <<-- why not RemitAddressBuffer
            RemitAddress.County,    <<-- why not RemitAddressBuffer
            RemitAddressBuffer."Country/Region Code");

    end;

Also, why does procedure VendorRemitAddress below not set Name2?

    procedure VendorRemitToAddress(var RemitAddress: Record "Remit Address"; var RemitAddressBuffer: Record "Remit Address Buffer")
    begin
        RemitAddressBuffer.Name := RemitAddress.Name;
        RemitAddressBuffer.Address := RemitAddress.Address;
        RemitAddressBuffer."Address 2" := RemitAddress."Address 2";
        RemitAddressBuffer.City := RemitAddress.City;
        RemitAddressBuffer.County := RemitAddress.County;
        RemitAddressBuffer."Post Code" := RemitAddress."Post Code";
        RemitAddressBuffer."Country/Region Code" := RemitAddress."Country/Region Code";
        RemitAddressBuffer.Contact := RemitAddress.Contact;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14079.
