### ISSUE TITLE
Modify Clause OnPrem For Procedures InsertEntry CreateTask on table Opportunity Entry

### ISSUE THREAD

**Issue by afrancioli** [microsoft/ALAppExtensions#24247]
**🕮 Describe the request**

Modify Clause OnPrem For Procedures InsertEntry CreateTask on table Opportunity Entry.

table 5093 "Opportunity Entry"
[Scope('OnPrem')]
    procedure InsertEntry(var OppEntry: Record "Opportunity Entry"; CancelOldTask: Boolean; CreateNewTask: Boolean)

[Scope('OnPrem')]
    procedure CreateTask(CancelOldTask: Boolean; CreateNewTask: Boolean)

   

**Additional context**

We need that the two procedures can be called directly from our extension that manage the creation of opportunities.
Our extension provide a series of api that are used in by our web portal application.
we don't  see any security issue in the possibility to add entries from other applications than the standard CRM management.
We have just to insert the records under certain circumstances and then activate the standard logic.

Requestor: Action Network SA

**Comment by JesperSchulz** [comment]
This issue was resolved back in 08-23. Closing issue.
