### ISSUE TITLE
Typo in Event OnAfterCopyFromPriceAsset - Table 7001 Price List Line

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#24244]
There is a typo in the parameter of the price line. The parameter is currently just called riceListline.

Go to:
```
[IntegrationEvent(true, false)]
    local procedure OnAfterCopyFromPriceAsset(PriceAsset: Record "Price Asset"; var riceListLine: Record "Price List Line")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11653.
