### ISSUE TITLE
[Access Request] page 5005271 "Delivery Reminder Sub." -  InsertExtendedText

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#24241]
**🕮 Describe the request**
Could you please remove the scope OnPrem from the procedure `InsertExtendedText` on `page 5005271 "Delivery Reminder Sub."` that this function can be used from pageextensions.
```al
//+Change
//[Scope('OnPrem')]
//-Change
procedure InsertExtendedText(Unconditionally: Boolean)
begin
    OnBeforeInsertExtendedText(Rec);
    if TransferExtendedDelivRemText.ReminderCheckIfAnyExtText(Rec, Unconditionally) then begin
        CurrPage.SaveRecord();
        TransferExtendedDelivRemText.DelivReminInsertExtendedText(Rec);
    end;
    if TransferExtendedDelivRemText.MakeUpdate() then
        CurrPage.Update();
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11640.
