### ISSUE TITLE
[Access Request] table 37 "Sales Line" IsExtendedText

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#24252]
**🕮 Describe the request**

Could you please remove the internal access scope of the procedure.
We're working a lot with Extended Text Lines e.g. in Reports and therefore we would like to use the same function as the BaseApp does.

```al
//+Change
//-internal procedure IsExtendedText(): Boolean
procedure IsExtendedText(): Boolean
//-Change
begin
    exit((Type = Type::" ") and ("Attached to Line No." <> 0) and (Quantity = 0));
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11697.
