### ISSUE TITLE
[Event Request] Table 38 Purchase Header- trigger OnValidate field "Sell-to Customer No." - OnBeforeSellToCustomerNoValidate

### ISSUE THREAD

**Issue by zelhamri22** [microsoft/ALAppExtensions#24256]
Hi, would it be possible to get an event OnBeforeCheckPrepmtInfo in the trigger OnValidate of the field "Sell-to Customer No." in Table 38 (Purchase Header), like this:
field(72; "Sell-to Customer No."; Code[20])
        {
            Caption = 'Sell-to Customer No.';
            TableRelation = Customer;

            trigger OnValidate()
            begin
               IsHandled := false;
               OnBeforeSellToCustomerNoValidate(SalesLine,IsHandled); <-- NEW EVENT
if IsHandled then
 exit;
                if ("Document Type" = "Document Type"::Order) and
                   (xRec."Sell-to Customer No." <> "Sell-to Customer No.")
                then begin
                    PurchLine.SetRange("Document Type", PurchLine."Document Type"::Order);
                    PurchLine.SetRange("Document No.", "No.");
                    PurchLine.SetFilter("Sales Order Line No.", '<>0');
                    if not PurchLine.IsEmpty() then
                        Error(
                          YouCannotChangeFieldErr,
                          FieldCaption("Sell-to Customer No."));

                    CheckSpecialOrderSalesLineLink();
                end;

                if "Sell-to Customer No." = '' then
                    UpdateLocationCode('')
                else
                    SetShipToCodeEmpty();
            end;
        }
        
        
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSellToCustomerNoValidate(var PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by AleksandricMarko** [comment]
Hello @zelhamri22 
You probably forgot to add one more line...
What is a purpose of this IsHandled parameter in the event? To skip rest of code in trigger or just part of it?

**Comment by zelhamri22** [comment]
Hello AleksandricMarko,

Thank you for your reply, yeah I corrected the value.
