### ISSUE TITLE
[Extensibility Request] report 1316 "Standard Statement" - CompanyInfo

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#24289]
Hello,
Could we please change the CompanyInfo: Record "Company Information"; to be "Protected var" so that we can use this in report extention.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11697.
