### ISSUE TITLE
[Event Request] codeunit 5632 "FA Jnl.-Post Line" - OnBeforeUpdateRegNo

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#24295]
Hello, can you please add a new Event OnBeforeUpdateRegNo  in codeunit 5632 "FA Jnl.-Post Line"?

```
    procedure UpdateRegNo(GLRegNo: Integer)
    var
        FAReg: Record "FA Register";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateRegNo(GLRegNo, IsHandled);
        if IsHandled then
            exit;
        if FAReg.FindLast() then begin
            FAReg."G/L Register No." := GLRegNo;
            FAReg.Modify();
        end;
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateRegNo(GLRegNo: Integer; var IsHandled: Boolean);
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11703.
