### ISSUE TITLE
[Access Request] table 7001 "Price List Line" SetHeader

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#24298]
**🕮 Describe the request**
Could you please remove the access scope `internal` form the procedure `SetHeader` that we can use this function from custom price pages?

```al
//+Change
//-internal procedure SetHeader(var NewPriceListHeader: Record "Price List Header")
procedure SetHeader(var NewPriceListHeader: Record "Price List Header")
//-Change
begin
    PriceListHeader := NewPriceListHeader;
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11697.
