### ISSUE TITLE
[Event Change Request] codeunit 414 "Release Sales Document" - OnAfterReopenSalesDoc

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#24299]
**🕮 Describe the request**
Could you please add the parameter `SkipWhseRequestOperations ` to the event `OnAfterReopenSalesDoc`?

```al
procedure Reopen(var SalesHeader: Record "Sales Header")
var
    IsHandled: Boolean;
begin
   [...]

    //+Change
    //-OnAfterReopenSalesDoc(SalesHeader, PreviewMode);
    OnAfterReopenSalesDoc(SalesHeader, PreviewMode, SkipWhseRequestOperations);
    //-Change
end;
```

```al
[IntegrationEvent(false, false)]
//+Change
//-local procedure OnAfterReopenSalesDoc(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean)
local procedure OnAfterReopenSalesDoc(var SalesHeader: Record "Sales Header"; PreviewMode: Boolean; SkipWhseRequestOperations: Boolean)
//-Change
begin
end;
```
**Additional context**

Currenty we have to work with complex SingleInstance Codeunits to find out if the Release is triggered from a WhseRelease. 
With adding this parameter we could simplify our code-base.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11703.
