### ISSUE TITLE
[Application / refactoring] COD 5200 Employee/Resource Update

### ISSUE THREAD

**Issue by fvet** [Microsoft/ALAppExtensions#243]
Please include the Country + City fields in the Employee to Resource synchronisation in codeunit 5200.

Steps required:
1. (Application) Refactor the sync. similar to Contacts, using a procedure 'IsUpdateNeeded' + event publishers.
2. (Application) Refactor the current procedure 'HumanResToRes' (COD 5200) to include checks on changed Country + City values and remove the 'Post Code' validate in the ResUpdate procedure

**Comment by fvet** [comment]
Any update?

Please add following code to 'HumanResToRes' procedure

```
(OldEmployee."Country/Region Code" <> Employee."Country/Region Code") OR
(OldEmployee.City <> Employee.City) OR
```

Please add following code to 'ResUpdate' procedure
```

//NVT-BEGIN: first fill in country, post code & city before the validation
Res."Country/Region Code" := Employee."Country/Region Code";
Res."Post Code" := Employee."Post Code";
Res.City := Employee.City;
```

**Comment by ikoletic** [comment]
Will ship in April 19 release. Refactoring is checked in.
