### ISSUE TITLE
Modify TestField in "ImportPicture" action in EmployeePicture.Page.al

### ISSUE THREAD

**Issue by kalozoya-gregal** [microsoft/ALAppExtensions#24306]
**🕮 Describe the issue**

Cannot import the photo of an employee who does not have a second last name.

**🔧 To Reproduce**

We are using the Spanish version, which has the fields "Name", "First Family Name" and "Second Family Name" in "Employee" table.

- Edit an employee's card
- Enter value in "Name".
- Enter value in "First Family Name"
- Leave "Second Family Name" blank.
- In "Employee picture", perform the "Import" action.

**📣 Expected behavior**

Select the photo to upload.

**Screenshots**

![imagen](https://github.com/microsoft/ALAppExtensions/assets/47449787/8fec29b4-ec11-4d8e-9113-97da35c9c1d6)
![imagen](https://github.com/microsoft/ALAppExtensions/assets/47449787/b1627d8f-ecd3-4749-bbb3-c60e2944821e)

**Additional context**

Although most people in Spain have two last names, if they are foreigners you may not have a second last name.

In the international version of BC, TestField is performed on the "First Name" and "Last Name" fields, which would correspond to "Name" and "First Family Name" in the Spanish version.

International version: EmployeePicture.Page.al
```al
action(ImportPicture)
{
    ApplicationArea = Basic, Suite;
    Caption = 'Import';
    Image = Import;
    ToolTip = 'Import a picture file.';

    trigger OnAction()
    var
        FileManagement: Codeunit "File Management";
        FileName: Text;
        ClientFileName: Text;
    begin
        TestField("No.");
        TestField("First Name");
        TestField("Last Name");

        if Image.HasValue() then
            if not Confirm(OverrideImageQst) then
                exit;

        FileName := FileManagement.UploadFile(SelectPictureTxt, ClientFileName);
        if FileName = '' then
            exit;

        Clear(Image);
        Image.ImportFile(FileName, ClientFileName);
        Modify(true);

        if FileManagement.DeleteServerFile(FileName) then;
    end;
}
```

Spanish version: EmployeePicture.Page.al
```al
action(ImportPicture)
{
    ApplicationArea = Basic, Suite;
    Caption = 'Import';
    Image = Import;
    ToolTip = 'Import a picture file.';

    trigger OnAction()
    var
        FileManagement: Codeunit "File Management";
        FileName: Text;
        ClientFileName: Text;
    begin
        TestField("No.");
        TestField("First Family Name");
        TestField("Second Family Name");

        if Image.HasValue() then
            if not Confirm(OverrideImageQst) then
                exit;

        FileName := FileManagement.UploadFile(SelectPictureTxt, ClientFileName);
        if FileName = '' then
            exit;

        Clear(Image);
        Image.ImportFile(FileName, ClientFileName);
        Modify(true);

        if FileManagement.DeleteServerFile(FileName) then;
    end;
}
```

International version: Employee.Table.al
```al
field(2; "First Name"; Text[30])
{
    Caption = 'First Name';
}
field(3; "Middle Name"; Text[30])
{
    Caption = 'Middle Name';
}
field(4; "Last Name"; Text[30])
{
    Caption = 'Last Name';
}
```

Spanish version: Employee.Table.al
```al
field(2; Name; Text[30])
{
    Caption = 'Name';
}
field(3; "Second Family Name"; Text[30])
{
    Caption = 'Second Family Name';
}
field(4; "First Family Name"; Text[30])
{
    Caption = 'First Family Name';
}
```

Thanks

**Comment by pri-kise** [comment]
You did provide some very good documentation, but to get this fixed you should create a support case via the common support channel an link to this issue for the documenation in detail.

**Comment by kalozoya-gregal** [comment]
> You did provide some very good documentation, but to get this fixed you should create a support case via the common support channel an link to this issue for the documenation in detail.

Where is "the common support channel"?

**Comment by pri-kise** [comment]
You should check the following page:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/technical-support#summary-of-where-to-file-bugs-and-issues
and use the appropriate channel for your special case.
e.g. the partner center for BC SaaS Customers.

**Comment by AlexanderYakunin** [comment]
Thanks for pointing to right channel for reporting bugs! This way they will be fixed. Closing this request.
