### ISSUE TITLE
Codeunit 375 "Bank Acc. Entry Set Recon.-No."

### ISSUE THREAD

**Issue by MortenKSorensen** [microsoft/ALAppExtensions#24303]
Please add OnAfter events in the procedures ApplyEntries and RemoveApplication.

```
[IntegrationEvent(false, false)]
local procedure OnAfterApplyEntries(var BankAccReconciliationLine: Record "Bank Acc. Reconciliation Line"; var BankAccountLedgerEntry: Record "Bank Account Ledger Entry"; var Relation: Option "One-to-One","One-to-Many")
begin
end;

```
```
 [IntegrationEvent(false, false)]
 local procedure OnAfterRemoveApplication(var BankAccountLedgerEntry: Record "Bank Account Ledger Entry")
 begin
 end;
```

We have some supplementary tables that needs to be synchronized when a bank account ledger entry is manually matched or if a manual match is removed.

Thank you in advance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11703.
