### ISSUE TITLE
[Extend Field Length Request] Table 1103 "Cost Type" field 40 "G/L Account Range"

### ISSUE THREAD

**Issue by Dym71** [microsoft/ALAppExtensions#24307]
Hello,
We are in the process of upgrading one of our largest clients and would like the "G/L Account Range" field from the "Cost Type" table be longer.
Current field length: 50
Preferred field length: 1024 (currently the longest customer value is 643 characters, 1024 has SelectionFilter variable in OnLookup trigger).
<img width="563" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/63510710/579c54fe-0593-446d-8cb6-160ca33f822a">

The change for the base application is potentially safe (I don't see any problems with overflow):
<img width="505" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/63510710/f02c173d-a557-4481-8536-d9306036872a">

Thank you

**Comment by pri-kise** [comment]
Field Length of fields can't be changed as this might be a breaking change.
The only option is to obsolete a field and create a new one.

You should create a idea and ask other partners for votes, to replace the old field with a new one.
There are several discussions on yammer, that it's currently not possible to simple increase a field length.

You can add your idea to this issue and share it yammer to gather votes.

As long as this is no direct bug, there's no big chance that this will be fixed via a support case.

**Comment by AndersLarsenMicrosoft** [comment]
see the comments above
