### ISSUE TITLE
[Event Request] table 210 "Job Journal Line" - OnAfterInitTableValuePair

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#24310]
**🕮 Describe the request**
Could you please add the following event `OnAfterInitTableValuePair`?

And could you maybe add some documentation that if someone adds a default dimension via the event `OnAfterInitDefaultDimensionSources` this person should also integrate into the event `OnAfterInitTableValuePair`?

```al
local procedure GetTableValuePair(FieldNo: Integer) TableValuePair: Dictionary of [Integer, Code[20]]
begin
    case true of
        FieldNo = Rec.FieldNo("No."):
            TableValuePair.Add(DimMgt.TypeToTableID2(Rec.Type.AsInteger()), Rec."No.");
        FieldNo = Rec.FieldNo("Job No."):
            TableValuePair.Add(Database::Job, Rec."Job No.");
        FieldNo = Rec.FieldNo("Resource Group No."):
            TableValuePair.Add(Database::"Resource Group", Rec."Resource Group No.");
        FieldNo = Rec.FieldNo("Location Code"):
            TableValuePair.Add(Database::Location, Rec."Location Code");
    end;
    //+EVENT
    OnAfterInitTableValuePair(Rec, TableValuePair, FieldNo);
    //-EVENT
end;
```

```al
[IntegrationEvent(false, false)]
local procedure OnAfterInitTableValuePair(var JobJournalLine: Record "Job Journal Line"; var TableValuePair: Dictionary of [Integer, Code[20]]; FieldNo: Integer)
begin
end;
```

**Additional context**

Please align this function with the function in Sales/Purchase Line.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11703.
