### ISSUE TITLE
[Extensibility Request] page 8889 "Email Attachments" make vars protected

### ISSUE THREAD

**Issue by dam-pav** [microsoft/ALAppExtensions#24312]
Please make vars protected for those that can be so that they can be available to extensions.

    protected var
        [InDataSet]
        DeleteActionEnabled: Boolean;
        IsEmailEditable: Boolean;
        EditOptionVisible: Boolean;
        AttachmentFileSize: Text;
        EmailMessageId: Guid;
        EmailScenario: Enum "Email Scenario";

In our case we would like to add an action to he page, besides the existing _Upload_, _UploadFromScenario_, _SourceAttachments_ and _WordTemplate_. We aim to make it possible to add files from other sources. In order to make the user experience consistent (and the developer experience less painful) it would be nice to have access to information such as the Id of the current message, the current scenario and whether these options should be visible or available at all.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11720.
