### ISSUE TITLE
[Event Request] Codeunit 22 Item Jnl.-Post Line – MoveApplication

### ISSUE THREAD

**Issue by SimonTwilfer** [microsoft/ALAppExtensions#24321]
The requested Event from #2197 has changed in BC22.3. Was that on purpose?

The parameter variable OldItemLedgerEntry is no longer part of the event OnBeforeMoveApplication.

When the change was on purpose can you please add the parameter variable OldItemLedgerEntry in the event OnBeforeMoveApplication?

**Comment by AleksandricMarko** [comment]
Hello @SimonTwilfer 
As far as I can see, "OldItemLedgerEntry" is still parameter of  event  "OnBeforeMoveApplication".
Did you check it well?
Which layer you are looking at? (on W1 it exists) 

![image](https://github.com/microsoft/ALAppExtensions/assets/133204513/5f948641-38fa-48a3-96fb-9edd13c5cb3e)

**Comment by SimonTwilfer** [comment]
Hello @AleksandricMarko,
the parameter for the function MoveApplication was renamed to OldItemLedgerEntry, but the Event Call for OnBeforeMoveApplication was not adjusted - now the global variable OldItemLedgEntry is passed to OnBeforeMoveApplication.
The Event OnAfterMoveApplication for example was changed, here it is the parameter variable OldItemLedgerEntry.

**Comment by donmikele75** [comment]
Hello @JesperSchulz,

There is another issue with "MoveApplication" in CU22 - the parameter ItemLedgerEntry is a var (reference) parameter, which is used in the calling function "TestFirstApplyItemLedgEntry".
With the introduced changes in BC22.3 this variable is no more updated by the later .Get() command:


```
local procedure MoveApplication(var ItemLedgerEntry: Record "Item Ledger Entry"; var OldItemLedgerEntry: Record "Item Ledger Entry"): Boolean
[...]
                if ItemApplicationEntry.FindSet() then begin
                    repeat
                        if not ItemApplicationEntry.Fixed() then begin
                            UnApply(ItemApplicationEntry);
                            OldItemLedgEntry.Get(OldItemLedgerEntry."Entry No.");    <-- before 22.3 "OldItemLedg" has been the var parameter

```
