### ISSUE TITLE
[follow-up] Codeunit 90 "Purch.-Post" - event OnBeforeCheckItemQuantityPurchCredit 

### ISSUE THREAD

**Issue by alinat2022** [microsoft/ALAppExtensions#24326]
Hello,

In https://github.com/microsoft/ALAppExtensions/issues/22434 we requested an event.

It is still not implemented. Can you please let us know when it will be implemented? Thank you.

**Comment by AlexanderYakunin** [comment]
This is implemented in v.23

        IsHandled := false;
        OnBeforeCheckItemQuantityPurchCredit(PurchHeader, PurchLine, IsHandled);
        if IsHandled then
            exit;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
