### ISSUE TITLE
[Follow-up] codeunit 90 "Purch.-Post" - Procedure DecrementPrepmtAmtInvLCY made global 

### ISSUE THREAD

**Issue by alinat2022** [microsoft/ALAppExtensions#24327]
Hello,

In https://github.com/microsoft/ALAppExtensions/issues/23261 it was requested for procedure DecrementPrepmtAmtInvLCY to be made global. It is still not implemented. Can you please have a look? Thank you.

**Comment by tomasevics** [comment]
Hi,

This was done and it will be available from BC23. For all requests for external we are doing changes only for next major release, in order not to break anything.
