### ISSUE TITLE
[Event Request] Table 11401 CBG Statement Line - OnBeforeCheckIdentification

### ISSUE THREAD

**Issue by alinat2022** [microsoft/ALAppExtensions#24325]
Hello.

In https://github.com/microsoft/ALAppExtensions/issues/19494, it was requested an event (compliant to the IsHandled-pattern) to be able to skip the OnValidate-trigger of field "Identification".

In 22.3 version, this is still not implemented. Can you please have a look? Thank you.

**Comment by AleksandricMarko** [comment]
Hello @alinat2022 
Please check one more time.
Event publisher "OnValidateIdentificationOnBeforeCheck" is added from the version 21.1
The name is just not same as you sugessted - "OnBeforeCheckIdentification"
