### ISSUE TITLE
[bug] Codeunit "Item Jnl.-Post Line" - using boolean OnRun return

### ISSUE THREAD

**Issue by Mario-Sopena** [microsoft/ALAppExtensions#24339]
var
        JnlLine: Record "Item Journal Line";
        JnlLinePost: Codeunit "Item Jnl.-Post Line";        
    begin       
            JnlLine.Init();
            ...
            Validate needed fields in here...   
            ...      
                if JnlLinePost.Run(JnlLine) then begin 
                    ...
                end;
     end;

This _'if JnlLinePost.Run(JnlLine) then'_  kind of code was working fine until last friday but suddenly, the same extension in the same environment started to throw this error:

"Form.RunModal is not allowed in write transactions."

It is still working fine in a Sandbox copied from the productive environment.

The call is inside a repeat-until loop, but a commit is done after each loop, and I repeat, it was working fine until last friday

Thanks in advance!

**Comment by AlexanderYakunin** [comment]
Please create support ticket if you need this addressed. This is wrong place for this kind of requests.
