### ISSUE TITLE
DataTransfer.UpdateAuditFields should be accessed also from apps targeted for Cloud

### ISSUE THREAD

**Issue by alinat2022** [microsoft/ALAppExtensions#24333]
Hello,

We want to use in our app the procedure UpdateAuditFields, but this is set to be used only for OnPrem (doc: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/datatransfer/datatransfer-updateauditfields-method)

Can you please make it available also for Cloud? Thank you.

**Comment by pri-kise** [comment]
This would be very helpful.

**Comment by AlexanderYakunin** [comment]
`But this is system procedure, defined by platform data type DataTransfer? And I see no any limitation for using it OnPrem or Cloud, can you provide more details what exactly do you want us to do?

**Comment by alinat2022** [comment]
Hello, Alexander.

On the documentation from the link above, it says it is only for OnPrem:
![image](https://github.com/microsoft/ALAppExtensions/assets/101644980/d03f1dca-0dcb-4bb3-9277-b5194fa0720f)

Also, if you set your app with target=Cloud, then you will not be able to use this procedure inside that app (you will get an error).

What we want: to be able to use the procedure also in apps that have target = Cloud.

**Comment by JesperSchulz** [comment]
Given this is a platform function, we cannot process this through this repository. For suggestions to the Business Central platform, please create a [BC Idea](https://aka.ms/bcideas).

**Comment by pri-kise** [comment]
I've already created an idea to open this procedure for BC SaaS Development: https://experience.dynamics.com/ideas/idea/?ideaid=ba68543f-ff98-ee11-a81c-000d3a7a4389
