### ISSUE TITLE
[Event Request] table 37 "Sales Line" - extend existing event OnCalcVATAmountLinesOnAfterCalcShouldProcessRounding

### ISSUE THREAD

**Issue by Mike-1984** [microsoft/ALAppExtensions#24343]
Hello colleagues,

Could you please extend existing event OnCalcVATAmountLinesOnAfterCalcShouldProcessRounding in table 37 "Sales Line" by adding additional parameters VATAmountLine and TotalVATAmount (by reference).

```
        OnCalcVATAmountLinesOnAfterCalcShouldProcessRounding(SalesLine, VATAmountLine, TotalVATAmount, Currency, ShouldProcessRounding);
```
New event signature:
```
    [IntegrationEvent(false, false)]
    local procedure OnCalcVATAmountLinesOnAfterCalcShouldProcessRounding(var SalesLine: Record "Sales Line"; var VATAmountLine: Record "VAT Amount Line"; var TotalVATAmount: Decimal; Currency: Record Currency; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11820.
