### ISSUE TITLE
[Event Request] Codeunit 7326 "Whse. Item Tracking FEFO" OnAfterCreateEntrySummaryFEFO

### ISSUE THREAD

**Issue by DParkerRSM** [microsoft/ALAppExtensions#2434]
I would like to request a new event to allow us to manipulate the list of viable lot or serial numbers before displaying them to the user.

This would be last row in the CreateEntrySummaryFEFO function.

**Comment by AlexanderYakunin** [comment]
Please provide event definition and list of required parameters

**Comment by DParkerRSM** [comment]
Please see images for event details and call. I would like the global variable TempGlobalEntrySummary passed to the event as a variable so we can manipulate the entries and return them. 

![event](https://user-images.githubusercontent.com/50593101/58266068-f30ac080-7d4e-11e9-8ec2-f3dc4766060d.jpg)
![function call](https://user-images.githubusercontent.com/50593101/58266069-f30ac080-7d4e-11e9-8fa3-942e5746037f.jpg)
