### ISSUE TITLE
[Access Request] page 976 "Time Sheet Archive Subform"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#24361]
**🕮 Describe the request**
Could you please change the access scope of the following variable to protected?
```al
protected var
    TimeSheetHeaderArchive: Record "Time Sheet Header Archive";
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
