### ISSUE TITLE
Page 6630 "Sales Return Order", Action "GetPostedDocumentLinesToReverse" does not validate "Payment Method Code"

### ISSUE THREAD

**Issue by bokhimlin** [microsoft/ALAppExtensions#24367]
**🕮 Describe the issue**

When using the Page 6630 "Sales Return Order" with the action "GetPostedDocumentLinesToReverse", the Payment Method Code field is not validated after getting the Sales Lines, resulting in missing 1  Customer Ledger Entry for Refund. We can already see the missing posting in "Posting Preview".

**🔧 To Reproduce**

1. create a new sales return order
2. select any customer with Posted Invoices. Note: Payment Method Code is still empty, which is fine. 
3. Choose any Document, you want to reverse.
4. Payment method code is filled in.
5. If we look on posting preview in Customer Ledger Entries, there is only 1 entry for Credit memo, 0 for Refund.

**📣 Expected behavior**

If you validate the Payment Method code manually and look at the preview, there are 2 Customer Ledger Entries, 1 for credit memo, 1 for refund.

**Screenshots**
Wrong Behaviour missing refund entry
![image](https://github.com/microsoft/ALAppExtensions/assets/138206612/fb5f4c89-ae85-46e0-b0b7-ebf60d51dc8b)

Correct behaviour, after manual validate of Payment Method Code
![image](https://github.com/microsoft/ALAppExtensions/assets/138206612/fde0fc3e-62dd-4e6b-b68f-6cdb71980689)

**Additional context**

1. I analyzed the code but didn't find the right spot, where "Payment Method Code" is entered but not validated. The best guess is in codeunit 6620 "Copy Document Mgt.", function CopySalesInvLinesToDoc or deeper in code.

2. With a manual validate of the field "Payment Methode Code" the code in the Validate Trigger is run, guess this is missing.
_"Bal. Account Type" := PaymentMethod."Bal. Account Type";
"Bal. Account No." := PaymentMethod."Bal. Account No.";_

3. I guess all copy functions of where of Posted Shipments, Invoices, Return Receipts or Credit Memo have the same wrong behavior.

**Comment by tomasevics** [comment]
"Payment Method Code" should be inserted when Customer No. is validated. Is that the case in your scenario? If that is the case than it should not be a problem with missing validation.
Maybe I'm missing something but we are not updating sales header on GetPostedDocumentLinesToReverse action?

**Comment by bokhimlin** [comment]
Thank you for your advice and comment, we checked our code. We saw that we subscribed to an event to update the header but didn't validate "Payment Method Code". So it's a bug on our side.
