### ISSUE TITLE
Event Request - Table 904 "Assemble-to-Order Link" OnBeforeShowSales

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#24379]
**🕮 Describe the request**

On table 904 "Assemble-to-Order Link", can we add a new Event Request called OnBeforeShowSales at the beginning of procedure ShowSales

**Additional context**

    procedure ShowSales(AssemblyHeader: Record "Assembly Header")
    var
        SalesHeader: Record "Sales Header";
        IsHandled: Boolean;  // NEW
    begin
        // NEW +
        IsHandled := false;
        OnBeforeShowSales(AssemblyHeader, IsHandled);
        if IsHandled then
            exit;
        // NEW -

        if GetATOLink(AssemblyHeader) then begin
            SalesHeader.Get(Rec."Document Type", Rec."Document No.");
            case "Document Type" of
                "Document Type"::Quote:
                    PAGE.RunModal(PAGE::"Sales Quote", SalesHeader);
                "Document Type"::"Blanket Order":
                    PAGE.RunModal(PAGE::"Blanket Sales Order", SalesHeader);
                "Document Type"::Order:
                    PAGE.RunModal(PAGE::"Sales Order", SalesHeader);
            end;
        end;
    end;

    // NEW +
    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowSales(AssemblyHeader: Record "Assembly Header"; var IsHandled: Boolean)
    begin
    end;
    // NEW -

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11755.
