### ISSUE TITLE
Event Request - Table 904 "Assemble-to-Order Link" OnBeforeCheckQtyToAsm

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#24377]
**🕮 Describe the request**

On table 904 "Assemble-to-Order Link", can we add a new Event Request called OnBeforeCheckQtyToAsm at the beginning of procedure CheckQtyToAsm

**Additional context**

    procedure CheckQtyToAsm(AssemblyHeader: Record "Assembly Header")
    var
        SalesLine: Record "Sales Line";
        Location: Record Location;
        WhseActivityLine: Record "Warehouse Activity Line";
        WhseShptLine: Record "Warehouse Shipment Line";
        WMSMgt: Codeunit "WMS Management";
        MaxQty: Decimal;
        MinQty: Decimal;
        IsHandled: Boolean;  // NEW
    begin
        // NEW +
        IsHandled := false;
        OnBeforeCheckQtyToAsm(AssemblyHeader, IsHandled);
        if IsHandled then
            exit;
        // NEW -
        if GetATOLink(AssemblyHeader) then begin
            SalesLine.Get("Document Type", "Document No.", "Document Line No.");

            if Location.Get(AssemblyHeader."Location Code") then
                if Location."Require Shipment" then begin
                    AssemblyHeader.CalcFields("Assemble to Order");
                    if WMSMgt.ATOWhseShptExists(SalesLine) then
                        Error(
                          Text007, WhseShptLine.TableCaption(), AssemblyHeader."Document Type", AssemblyHeader.FieldCaption("Quantity to Assemble"),
                          WhseShptLine.FieldCaption("Qty. to Ship"));
                end else
                    if Location."Require Pick" then
                        if WMSMgt.ATOInvtPickExists(SalesLine) then
                            Error(Text005, WhseActivityLine."Activity Type"::"Invt. Pick", AssemblyHeader."Document Type");

            MinQty := MinQtyToAsm(SalesLine, AssemblyHeader);
            MaxQty := MaxQtyToAsm(SalesLine, AssemblyHeader);
            if (AssemblyHeader."Quantity to Assemble" < MinQty) or (AssemblyHeader."Quantity to Assemble" > MaxQty) then
                Error(
                  Text004, AssemblyHeader.FieldCaption("Quantity to Assemble"), MinQty, MaxQty, SalesLine.FieldCaption("Qty. to Ship"),
                  SalesLine.TableCaption());
        end;
    end;

    // NEW +
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckQtyToAsm(AssemblyHeader: Record "Assembly Header"; var IsHandled: Boolean)
    begin
    end;
    // NEW -

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11755.
