### ISSUE TITLE
[Event Request] Table 7000 "Price List Header" - UpdateStatus

### ISSUE THREAD

**Issue by stephanweidmann** [microsoft/ALAppExtensions#24373]
**🕮 Describe the request**

I want to skip the "Confirm New Status" Message when activating a price list.

Old:
`        if ConfirmManagement.GetResponse(StrSubstNo(StatusUpdateQst, Status), true) then
             PriceListLine.ModifyAll(Status, Status)
        else
            Updated := false`
New:
New local Variables
`Confirmed, IsHandled: Boolean`

`OnUpdateStatusOnBeforeConfirmStatus(Rec,Updated,Confirmed,IsHandled);
if Not IsHandled then
  Confirmed := ConfirmManagement.GetResponse(StrSubstNo(StatusUpdateQst, Status), true)

if Confirmed then
            PriceListLine.ModifyAll(Status, Status)
        else
            Updated := false
            
[IntegrationEvent(false,false)]            
       OnUpdateStatusOnBeforeConfirmStatus(PriceListHeader: Record "Price List HEader",Updated: Boolean,var Confirmed Boolean, var,IsHandled: Boolean);
begin
end;`
     
**Additional context**

I want to skip the "Confirm New Status" Message when activating a price list.

Alternative: New Function GetConfirmation with handled pattern.

Also think about adding the price list code to the question, with automated procedures, you don't know the context of the pricelist

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11755.
