### ISSUE TITLE
Event Request - Table 904 "Assemble-to-Order Link" OnBeforeUpdateQtyToAsmFromWhseShptLine

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#24375]
**🕮 Describe the request**

On table 904 "Assemble-to-Order Link", can we add a new Event Request called OnBeforeUpdateQtyToAsmFromWhseShptLine at the beginning of procedure UpdateQtyToAsmFromWhseShptLine

    procedure UpdateQtyToAsmFromWhseShptLine(WhseShptLine: Record "Warehouse Shipment Line")
    var
        Window: Dialog;
        IsHandled: Boolean;  // NEW
    begin
        // NEW +
        IsHandled := false;
        OnBeforeUpdateQtyToAsmFromWhseShptLine(WhseShptLine, IsHandled);
        if IsHandled then
            exit;
        // NEW -

        if AsmExistsForWhseShptLine(WhseShptLine) then
            if GetAsmHeader() then begin
                Window.Open(GetWindowOpenTextWhseShpt(WhseShptLine));
                UpdateQtyToAsm(WhseShptLine."Qty. to Ship");
                Window.Close();
            end;
    end;

    // NEW +
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateQtyToAsmFromWhseShptLine(WhseShptLine: Record "Warehouse Shipment Line"; var IsHandled: Boolean)
    begin
    end;
    // NEW -

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11755.
