### ISSUE TITLE
Event Request - Table 904 "Assemble-to-Order Link" OnBeforeInitQtyToAsm

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#24378]
**🕮 Describe the request**

On table 904 "Assemble-to-Order Link", can we add a new Event Request called OnBeforeInitQtyToAsm at the beginning of procedure InitQtyToAsm

**Additional context**

    procedure InitQtyToAsm(AssemblyHeader: Record "Assembly Header"; var QtyToAsm: Decimal; var QtyToAsmBase: Decimal)
    var
        SalesLine: Record "Sales Line";
        IsHandled: Boolean;  // NEW
    begin
        // NEW +
        IsHandled := false;
        OnBeforeInitQtyToAsm(AssemblyHeader, QtyToAsm, QtyToAsmBase, IsHandled);
        if IsHandled then
            exit;
        // NEW -
        if GetATOLink(AssemblyHeader) then begin
            SalesLine.Get("Document Type", "Document No.", "Document Line No.");
            QtyToAsm := MaxQtyToAsm(SalesLine, AssemblyHeader);
            QtyToAsmBase := MaxQtyToAsmBase(SalesLine, AssemblyHeader);
        end;
    end;

    // NEW +
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInitQtyToAsm(AssemblyHeader: Record "Assembly Header"; var QtyToAsm: Decimal; var QtyToAsmBase: Decimal; var IsHandled: Boolean)
    begin
    end;
    // NEW -

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11755.
