### ISSUE TITLE
GetDefaultAmountType in table 7005 "Price Source"

### ISSUE THREAD

**Issue by Giumai** [microsoft/ALAppExtensions#24374]
Hello,
I would to set the Default Amount Type to Any in the function GetDefaultAmountType of the table 7005 "Price Source".
I think it is necessary to add a new event
OnBeforeGetDefaultAmountType with IsHandled parameter

    procedure GetDefaultAmountType() AmountType: Enum "Price Amount Type";
    var
        AmountTypeInt: Integer;
    begin
        foreach AmountTypeInt in AmountType.Ordinals() do begin
            AmountType := "Price Amount Type".FromInteger(AmountTypeInt);
            if IsForAmountType(AmountType) then
                if AmountType <> AmountType::Any then
                    exit;
        end;
    end;

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11755.
