### ISSUE TITLE
Event Request - Table 904 "Assemble-to-Order Link" OnBeforeAsmExistsForWhseShptLine

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#24376]
**🕮 Describe the request**

On table 904 "Assemble-to-Order Link", can we add a new Event Request called OnBeforeAsmExistsForWhseShptLine at the beginning of procedure AsmExistsForWhseShptLine

**Additional context**

    procedure AsmExistsForWhseShptLine(WhseShptLine: Record "Warehouse Shipment Line"): Boolean
    var
        SalesLine: Record "Sales Line";
        // NEW +
        AsmExists: Boolean;
        IsHandled: Boolean;
    // NEW -
    begin
        // NEW +
        IsHandled := false;
        OnBeforeAsmExistsForWhseShptLine(Rec, WhseShptLine, AsmExists, IsHandled);
        if IsHandled then
            exit(AsmExists);
        // NEW -
        WhseShptLine.TestField("Assemble to Order", true);
        WhseShptLine.TestField("Source Type", DATABASE::"Sales Line");
        SalesLine.Get(WhseShptLine."Source Subtype", WhseShptLine."Source No.", WhseShptLine."Source Line No.");
        exit(AsmExistsForSalesLine(SalesLine));
    end;

    // NEW +
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAsmExistsForWhseShptLine(var AssembleToOrderLink: Record "Assemble-to-Order Link"; WhseShptLine: Record "Warehouse Shipment Line"; var AsmExists: Boolean; var IsHandled: Boolean)
    begin
    end;
    // NEW -

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11755.
