### ISSUE TITLE
[Event Request] Table 5406 Prod. Order Line OnBeforeRecalculate

### ISSUE THREAD

**Issue by mmjansen4** [microsoft/ALAppExtensions#24388]
On table 5406 Prod. Order Line, please add event:
` [IntegrationEvent(false, false)]
local procedure OnBeforeRecalculate(var ProdOrderLine: Record "Prod. Order Line"; var Direction: Option; var CallingFieldNo: Integer; var IsHandled: Boolean)`

and call it in **Ending Time - OnValidate**

`        field(51; "Ending Time"; Time)
        {
            Caption = 'Ending Time';

            trigger OnValidate()
            var
                ProdOrderLine: Record "Prod. Order Line";
            begin
                if ProdOrderLine.Get(Status, "Prod. Order No.", "Line No.") then begin
                    Modify();
                    //>>NEW
                    IsHandled := false;
                    OnBeforeRecalculate(Rec, 1, CurrFieldNo, IsHandled);
                    if IsHandled then
                        exit;
                    //<<NEW
                    CalcProdOrder.Recalculate(Rec, 1, true);

                    OnAfterRecalculate(Rec, 1, CurrFieldNo);

                    Get(Status, "Prod. Order No.", "Line No.");
                end;
                if CurrFieldNo <> 0 then
                    Validate("Due Date");

                UpdateDatetime();
            end;`

We use an external scheduling tool and do not want the order to recalculate in every case, and have not been able to identify an alternative.

**Comment by tomasevics** [comment]
Request is not complete. What Direction do you think? FieldNo? Did you think on CurrFieldNo?

**Comment by tomasevics** [comment]
Is it better to set event on beggining of OnValidate trigger? Or you need to get ProdOrderLine and Modify?

**Comment by mmjansen4** [comment]
In this case I need to get ProdOrderLine and Modify. 

It may be helpful to also have an OnBeforeValidate event before those lines with an IsHandled flag, though I do not have a use case for it currently.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11863.
