### ISSUE TITLE
Event Request - page 900 "Assembly Order" OnBeforeAsmToOrderWhseShptLine

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#24382]
**🕮 Describe the request**

HI,

On page 900 "Assembly Order", can we add a new Event Request called OnBeforeAsmToOrderWhseShptLine at the beginning of action "Asm.-to-Order Whse. Shpt. Line".

**Additional context**

                action("Asm.-to-Order Whse. Shpt. Line")
                {
                    ApplicationArea = Warehouse;
                    Caption = 'Asm.-to-Order Whse. Shpt. Line';
                    Enabled = NOT IsAsmToOrderEditable;
                    Image = ShipmentLines;
                    ToolTip = 'View the list of warehouse shipment lines that exist for sales orders that are linked to this assembly order as assemble-to-order links. ';

                    trigger OnAction()
                    var
                        ATOLink: Record "Assemble-to-Order Link";
                        WhseShptLine: Record "Warehouse Shipment Line";
                        // NEW +
                        IsHandled: Boolean;
                    // NEW -
                    begin
                        // NEW +
                        IsHandled := false;
                        OnBeforeAsmToOrderWhseShptLine(Rec, IsHandled);
                        if IsHandled then
                            exit;
                        // NEW -
                        Rec.TestField("Assemble to Order", true);
                        ATOLink.Get(Rec."Document Type", Rec."No.");
                        WhseShptLine.SetCurrentKey("Source Type", "Source Subtype", "Source No.", "Source Line No.", "Assemble to Order");
                        WhseShptLine.SetRange("Source Type", DATABASE::"Sales Line");
                        WhseShptLine.SetRange("Source Subtype", ATOLink."Document Type");
                        WhseShptLine.SetRange("Source No.", ATOLink."Document No.");
                        WhseShptLine.SetRange("Source Line No.", ATOLink."Document Line No.");
                        WhseShptLine.SetRange("Assemble to Order", true);
                        PAGE.RunModal(PAGE::"Asm.-to-Order Whse. Shpt. Line", WhseShptLine);
                    end;
                }

                // NEW +
                [IntegrationEvent(false, false)]
                local procedure OnBeforeAsmToOrderWhseShptLine(var AssemblyHeader: Record "Assembly Header"; var IsHandled: Boolean)
                begin
                end;
                // NEW -

**Comment by tomasevics** [comment]
What is the scenario that you want to cover? If you want to add your custom logic to this action, isn't it easier to add your custom action with page ext?

**Comment by MatthewMcCarthy7** [comment]
@tomasevics With all my recent events we are making it so that you can do Assemble to Order on Transfer Orders in our extension.  If you are on an Assembly Order that is ATO for a Transfer order and click that action it is filtering on Source Type Sales, and will not show those orders.  We want to be able to override this so that if the user clicks the action we can also override and switch to Source Type Transfer Line if the ATO is from a Transfer Order.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11755.
