### ISSUE TITLE
Event Request - page 7336 "Whse. Shipment Subform" OnBeforeOnBeforeAssembleToOrder

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#24381]
**🕮 Describe the request**

HI,

On Page 7336 "Whse. Shipment Subform", can we add a new Event Request called OnBeforeAssembleToOrder at the beginning of action "Assemble to Order".

**Additional context**

                action("Assemble to Order")
                {
                    AccessByPermission = TableData "BOM Component" = R;
                    ApplicationArea = Assembly;
                    Caption = 'Assemble to Order';
                    Image = AssemblyBOM;
                    ToolTip = 'View the linked assembly order if the shipment was for an assemble-to-order sale.';

                    trigger OnAction()
                    var
                        ATOLink: Record "Assemble-to-Order Link";
                        ATOSalesLine: Record "Sales Line";
                        // NEW +
                        IsHandled: Boolean;
                        // NEW -
                    begin
                        // NEW +
                        IsHandled := false;
                        OnBeforeAssembleToOrder(Rec, IsHandled);
                        if IsHandled then
                            exit;
                        // NEW -
                        Rec.TestField("Assemble to Order", true);
                        Rec.TestField("Source Type", DATABASE::"Sales Line");
                        ATOSalesLine.Get(Rec."Source Subtype", Rec."Source No.", Rec."Source Line No.");
                        ATOLink.ShowAsm(ATOSalesLine);
                    end;
                }

                    // NEW +
                    [IntegrationEvent(false, false)]
                    local procedure OnBeforeAssembleToOrder(var Warehouse ShipmentLine: Record "Warehouse Shipment Line"; var IsHandled: Boolean)
                    begin
                    end;
                    // NEW -

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11755.
