### ISSUE TITLE
[Code Change and Event Request] Codeunit 80 Sales-Post – OnRun

### ISSUE THREAD

**Issue by Olli-GITHUB** [microsoft/ALAppExtensions#2439]
Dear ALAppExtensions Team,

we would like to request the following code extension and event-publisher to be added in codeunit 80 Sales-Post in the function OnRun.

Code Change as followed
```
// Check that the invoice amount is zero or greater
//Old Code
//IF SalesHeader.Invoice THEN
//  IF "Document Type" IN ["Document Type"::Invoice,"Document Type"::Order] THEN BEGIN
//    TempSalesLineGlobal.CalcVATAmountLines(1,SalesHeader,TempSalesLineGlobal,TempVATAmountLine);
//    IF TempVATAmountLine.GetTotalLineAmount(FALSE,'') < 0 THEN
//      ERROR(TotalInvoiceAmountNegativeErr);
//  END;

// >> New Code
IF SalesHeader.Invoice THEN
  ErrorIfInvoiceAndNegativeAmt(SalesHeader,TempSalesLineGlobal);
// >> New Code
```

The publisher event is published in the new local function ErrorIfInvoiceAndNegativeAmt
```
LOCAL ErrorIfInvoiceAndNegativeAmt(VAR SalesHeader : Record "Sales Header";VAR TempSalesLineGlobal : Record "Sales Line")
OnBeforeErrorIfNegativeAmt(SalesHeader,TempSalesLineGlobal,RaiseError);
WITH SalesHeader DO BEGIN
  IF "Document Type" IN ["Document Type"::Invoice,"Document Type"::Order] THEN BEGIN
    TempSalesLineGlobal.CalcVATAmountLines(1,SalesHeader,TempSalesLineGlobal,TempVATAmountLine);
    IF (TempVATAmountLine.GetTotalLineAmount(FALSE,'') < 0) AND RaiseError THEN
      ERROR(TotalInvoiceAmountNegativeErr);
  END;
END;
```

**Comment by lv-janpieter** [comment]
We have exact the same requirement although I do believe there is no need to execute CalcVATAmountLines and GetTotalLineAmount in a case where we don't intend to raise the error.

And to me it seems strange that it is not allowed to invoice negative orders / invoices, however a negative credit memo and return order will not raise any error.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
