### ISSUE TITLE
[Event Change Request] codeunit 5703 "Catalog Item Management" - publisher

### ISSUE THREAD

**Issue by exnihiloo** [microsoft/ALAppExtensions#24394]
Hello, would it be possible to modify OnNonStockSalesOnBeforeProgWindowClose code (add IsHandled statement) to codeunit 5703 "Catalog Item Management", like this:
``````al
[Requested]
    procedure NonStockSales(var SalesLine2: Record "Sales Line") 
... 
              NonstockItemReference(NonStock);

         IsHandled := false;
         OnNonStockSalesOnBeforeProgWindowClose(NonStock, NewItem, IsHandled, SalesLine2);
         If not IsHandled then
           if GuiAllowed() then
             ProgWindow.Close();
     end;
 ``````

``````al
[Current]
if CheckLicensePermission(DATABASE::"Item Reference") then
            NonstockItemReference(NonStock);

        OnNonStockSalesOnBeforeProgWindowClose(NonStock, NewItem, SalesLine2, IsHandled);
        if GuiAllowed() then
            ProgWindow.Close();
    end;
``````

**Comment by tomasevics** [comment]
What is idea here? To skip close progres dialog? What about GuiAllowed()?

**Comment by exnihiloo** [comment]
@tomasevics I updated the request
``````al
If not IsHandled then
    if GuiAllowed() then
         ProgWindow.Close();
``````

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11863.
