### ISSUE TITLE
[Issue]Manufacturer Code in Page 5725 / 5726

### ISSUE THREAD

**Issue by hhfiddelke** [Microsoft/ALAppExtensions#244]
BC Fall Release:

The field "Manufacturer Code" in page 5725 and 5726 is marked with Applicaton Area #Manufacturing. 
The "Manufacturer Code" is used to identify the manufacturer of an item, which may be different from the vendor. It should be #All or somehing like that.
The field is used normaly only from NON manufacturing people, purchasers or sales people who want to select items by manufacturer. 
It's not special to Manufacturing.

**Comment by JesperSchulz** [comment]
This repository is meant to be for extensibility issues and blockers, while this request rather is "usual" bug. But since it's just changing an application area, I couldn't help myself and quickly fixed it. It will ship in a future update. Thanks for reporting :)
