### ISSUE TITLE
[EVENT REQUEST] Table 27 - OnModify - OnBeforePlanningAssignmentItemChange

### ISSUE THREAD

**Issue by NadiaMelnyk** [microsoft/ALAppExtensions#24402]
Hello. Could you please add OnBeforePlanningAssignmentItemChange and IsHandled?

We need to run PlanningAssignment.ItemChange(Rec, xRec); based on the custom condition, but not every time.

```
 trigger OnModify()
    var
        IsHandled: Boolean;
    begin
        UpdateReferencedIds();
        SetLastDateTimeModified();
      
        OnBeforePlanningAssignmentItemChange(Rec, xRec, PlanningAssignment, IsHandled);
        IsHandled := false;
	if not IsHandled then
           PlanningAssignment.ItemChange(Rec, xRec);

        UpdateItemUnitGroup();
    end;

 [IntegrationEvent(false, false)]
 local procedure OnBeforePlanningAssignmentItemChange(var Item: Record Item; xItem: Record Item; PlanningAssignment: Record "Planning Assignment"; var IsHandled: Boolean)
 begin
 end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11755.
