### ISSUE TITLE
[Event Request] OnPostBankAccOnBeforeCheckLedgEntry2Modify - missing parameter it attempts to modify

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/ALAppExtensions#24416]
**🕮 Describe the issue**

codeunit 12 Gen. Jnl.-Post+Line

**🔧 To Reproduce**

Event as called:

    OnPostBankAccOnBeforeCheckLedgEntry2Modify(CheckLedgEntry, BankAccLedgEntry);

Existing procedure:

    [IntegrationEvent(false, false)]
    local procedure OnPostBankAccOnBeforeCheckLedgEntry2Modify(var CheckLedgEntry: Record "Check Ledger Entry"; var BankAccLedgEntry: Record "Bank Account Ledger Entry")
    begin
    end;

**📣 Expected behavior**

New Event call:

    OnPostBankAccOnBeforeCheckLedgEntry2Modify(CheckLedgEntry, CheckLedgEntry2, BankAccLedgEntry);

New procedure:

    [IntegrationEvent(false, false)]
    local procedure OnPostBankAccOnBeforeCheckLedgEntry2Modify(CheckLedgEntry: Record "Check Ledger Entry", var CheckLedgEntry2: Record "Check Ledger Entry"; var BankAccLedgEntry: Record "Bank Account Ledger Entry")
    begin
    end;
    // no var on CheckLedgEntry, but yes var on CheckLedgEntry2

**Screenshots**

**Additional context**

based on event name (..."BeforeCheckLedgEntry2Modify"), I would presume the event would allow you to make additional adjustments to CheckLedgEntry2, but that record is not in the parameters. My suggestion would allow updates to CheckLedgEntry2.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11880.
