### ISSUE TITLE
[Event Request] Codeunit "Carry Out Action" - OnInsertProdOrderLineOnBeforeValidateUnitCost

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#24417]
Hi there,

I would like to ask you to add the following publisher to the procedure InsertProdOrderLine() to Codeunit 99000813 (Carry Out Action):

```al
 ProdOrderLine."Inventory Posting Group" := Item."Inventory Posting Group";
 //NEW CODE - BEGIN
 OnInsertProdOrderLineOnBeforeValidateUnitCost(ReqLine, ProdOrde, ProdOrderLiner, Item);
 //NEW CODE - END
 ProdOrderLine.Validate("Unit Cost", ReqLine."Unit Cost");
 ProdOrderLine."Routing No." := ReqLine."Routing No.";
```

```
    [IntegrationEvent(false, false)]
    local procedure OnInsertProdOrderLineOnBeforeValidateUnitCost(var ReqLine: Record "Requisition Line"; ProdOrder: Record "Production Order"; var ProdOrderLine: Record "Prod. Order Line"; Item: Record Item)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11863.
