### ISSUE TITLE
[Event Request] Codeunit "Create Reserv. Entry" - OnTransferReservEntryOnAfterTransferFields()

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#24419]
Hi there,

I would like to ask you to add the following publisher to the procedure TransferReservEntry() to Codeunit 99000830 "Create Reserv. Entry":
```al

NewReservEntry.TransferFields(OldReservEntry, false);
NewReservEntry."Entry No." := OldReservEntry."Entry No.";
// NEW CODE - START
OnTransferReservEntryOnAfterTransferFields(NewReservEntry, OldReservEntry, UseQtyToHandle, UseQtyToInvoice, CurrSignFactor)
// NEW CODE - STOP
NewReservEntry.Positive := OldReservEntry.Positive;

```

```al
[IntegrationEvent(false, false)]
local procedure OnTransferReservEntryOnAfterTransferFields(var NewReservationEntry: Record "Reservation Entry"; var OldReservationEntry: Record "Reservation Entry"; var UseQtyToHandle: Boolean; var UseQtyToInvoice: Boolean; var CurrSignFactor: Integer)
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11863.
