### ISSUE TITLE
[Event Request] Codeunit "Carry Out Action" - OnTransferBOMONAfterCopyProdBOMComments

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#24418]
Hi there,

I would like to ask you to add the following publisher to the procedure TransferBOM() to Codeunit 99000813 (Carry Out Action):

```al

ProdOrderComp2.Insert();
CopyProdBOMComments(ProdOrderComp2);
// New code - START
OnTransferBOMOnAfterCopyProdBOMComments(PlanningComponent, ProdOrderComp2);
// New code - END
ReservePlanningComponent.TransferPlanningCompToPOComp(PlanningComponent, ProdOrderComp2, 0, true);
```

```al
[IntegrationEvent(false, false)]
local procedure OnTransferBOMOnAfterCopyProdBOMComments(var PlanningComponent: Record "Planning Component"; var ProdOrderComponent: Record "Prod. Order Component")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11863.
