### ISSUE TITLE
Field Request for IC Transactions

### ISSUE THREAD

**Issue by pranav4186** [microsoft/ALAppExtensions#2441]
Hello,

Would you please add Description 2 field in IC Outbox Line and Handled IC Outbox line for Sales and Purchase transactions?

Thanks

**Comment by StanPesotskiy** [comment]
Hi,

How these fields are going to be filled?
If these new fields are not going to be part of the standard App code you better add them as part of your extension.

Best regards.

**Comment by StanPesotskiy** [comment]
"Description 2" field exists in tables 37/39 , so "Description 2" field will be added to tables:
- 427 IC Outbox Sales Line, 
- 429 IC Outbox Purchase Line
- 435 IC Inbox Sales Line
- 437 IC Inbox Purchase Line
- 439 Handled IC Inbox Sales Line
- 441 Handled IC Inbox Purch. Line
and assignments calls to be added to Codeunit 427 ICInboxOutboxMgt to pass "Description 2" from 37/39 to Outbox and back from Inbox.

**Comment by pranav4186** [comment]
Thank you.
