### ISSUE TITLE
[Event Request] codeunit 86 "Sales-Quote to Order" - OnAfterATOLinkMakeAsmOrderLinkedToSalesOrderLine and VAR for parameter

### ISSUE THREAD

**Issue by sandeepchapte** [microsoft/ALAppExtensions#24413]
Hello Team,

can we expect a new requests as below for Objects

**publisher** on below Object and image is for reference :

Object : **Code unit  86  "Sales-Quote to Order"**
Function : **TransferQuoteToOrderLines**
Line No. After : **325**
Publisher Name : **OnAfterATOLinkMakeAsmOrderLinkedToSalesOrderLine(SalesQuoteLine,var SalesOrderLine)**

![image](https://github.com/microsoft/ALAppExtensions/assets/36148210/777b6f58-da61-4007-9fdf-1c21487f4ae5)

request to parameter **ToSalesOrderLine** with **VAR**  
Object : table 904 "Assemble-to-Order Link"
Function : MakeAsmOrderLinkedToSalesOrderLine

![image](https://github.com/microsoft/ALAppExtensions/assets/36148210/2c9a24c2-ad02-4193-a89d-d18ffe968462)

This allows us to update data in New Sales Order Lines from Assembly Order. With Current process, the values from Sales Quotes is updating on Sales Order lines where SalesOrderLine object doesn't return values.

**Comment by AleksandricMarko** [comment]
Hello @sandeepchapte 
For the second part of request (var parameter in MakeAsmOrderLinkedToSalesOrderLine procedure) please make a new request as this one will be used for the new event request (can`t combine event requests with other type of requests).

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11863.
