### ISSUE TITLE
Add possibility to change attachment name for Report Selections

### ISSUE THREAD

**Issue by TeusV** [microsoft/ALAppExtensions#24425]
When using Report Selections to send document as attachments in e-mails, all attachments are getting the same name. We would like to customize this, making the attachment name dependent on the report that is being sent. In the following piece of code, EmailFile is called with '' for the AttachmentName  parameter, later on leading to DocName becoming the attachment name. For us to be able to change the attachment name, one of the following would work:
1. Have DocName available in one of the current events as var parameter (that would have to be in OnSendEmailDirectlyOnBeforeSaveReportAsPDFInTempBlob or OnSendEmailDirectlyOnBeforeEmailWithAttachment, because it's already a non-var parameter in OnSendEmailDirectlyOnBeforeSendFileLoop)
2. Add a local AttachmentName [Text] variable, send that one instead of '' when calling DocumentMailing.EmailFile, and expose it as var parameter in OnSendEmailDirectlyOnBeforeSendFileLoop, OnSendEmailDirectlyOnBeforeSaveReportAsPDFInTempBlob, or OnSendEmailDirectlyOnBeforeEmailWithAttachment.

table 77 "Report Selections".SendEmailDirectly

``` al
...
            with TempAttachReportSelections do begin
                OfficeAttachmentManager.IncrementCount(Count - 1);
                repeat
                    IsHandled := false;
                    OnSendEmailDirectlyOnBeforeSendFileLoop(ReportUsage, RecordVariant, DocNo, DocName, DefaultEmailAddress, ShowDialog, TempAttachReportSelections, CustomReportSelection, IsHandled);
                    if not IsHandled then begin
                        EmailAddress := CopyStr(
                            GetNextEmailAddressFromCustomReportSelection(CustomReportSelection, DefaultEmailAddress, Usage, Sequence),
                            1, MaxStrLen(EmailAddress));
                        Clear(TempBlob);
                        IsHandled := false;
                        OnSendEmailDirectlyOnBeforeSaveReportAsPDFInTempBlob(TempAttachReportSelections, DocumentRecord, ReportUsage, TempBlob, IsHandled);
                        if not IsHandled then
                            SaveReportAsPDFInTempBlob(TempBlob, "Report ID", DocumentRecord, "Custom Report Layout Code", ReportUsage);
                        TempBlob.CreateInStream(AttachmentStream);

                        OnSendEmailDirectlyOnBeforeEmailWithAttachment(RecordVariant, TempAttachReportSelections, TempBlob, DocumentMailing);
                        AllEmailsWereSuccessful :=
                            AllEmailsWereSuccessful and
                            DocumentMailing.EmailFile(
                                AttachmentStream, '', ServerEmailBodyFilePath,
                                DocNo, EmailAddress, DocName, not ShowDialog, ReportUsage.AsInteger(),
                                SourceTableIDs, SourceIDs, SourceRelationTypes);
                    end;
                until Next() = 0;
...
```

**Comment by AleksandricMarko** [comment]
Hi @TeusV 
In publisher OnSendEmailDirectlyOnBeforeSendFileLoop parameter DocName will be with VAR.

**Comment by TeusV** [comment]
Great, but isn't that an [AppSourceCop violation](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0077)?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11880.
