### ISSUE TITLE
[Event Request Change] Codeunit 7002 - OnFindLinesOnBefoerPriceSourceListGetMinMaxLevel

### ISSUE THREAD

**Issue by chrischbo** [microsoft/ALAppExtensions#24423]
HI,

we're working with hierarchical level price source in our solution and on actions like pick or count price we want to show all price list lines. With the actual solution in the FindLines procedure it isn't possible to do this. So we would like to have the ShowAll parameter to the OnFindLinesOnBefoerPriceSourceListGetMinMaxLevel publisher. So we can adjust our levels in this situation.

OnFindLinesOnBefoerPriceSourceListGetMinMaxLevel(PriceAssetList, PriceSourceList, AmountType, PriceCalculationBufferMgt, **ShowAll**);

Thanks in advance
Christian

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11948.
