### ISSUE TITLE
[External Request] "Config. Excel Exchange" - SetSelectedTables()

### ISSUE THREAD

**Issue by shuyusheng** [microsoft/ALAppExtensions#24422]
We would like to skip tables when importing config packages from Excel by calling `"Config. Excel Exchange" - SetSelectedTables()` beforehand.
Currently we are able to override which records are exported using `"Config. XML Exchange" - OnBeforeApplyPackageFilter()`, including being able to skip all records and just export a blank template. Being able to filter the specific rows/records from being imported is not required for this request.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
