### ISSUE TITLE
Leaving a Document message

### ISSUE THREAD

**Issue by j-wilder** [microsoft/ALAppExtensions#2443]
Starting in NAV 2018 and changed a little in BC there is a message stemming from the OnQueryClosePage trigger.  It asks "The Document No. has not been posted...". I have no control in AL to get rid of this functionality.  When we leave a document we do not want a message popping up ever no matter what the state (Open/Released) the order is in.  We go in and out of open documents all the time so I would like this code disabled.

Either can a publisher be added so I can exit before that code is called or can you make this based on a Setup option.  In C/AL easy enough to comment it out, in AL not possible (yet).  Examples are Page 42, 43, 50, 51 and a bunch more.

**Comment by louiskody** [comment]
We were able to turn this off in My Notifications.  The tweak is described here: https://www.solsyst.com/post/2017/10/11/changing-the-document-has-not-been-posted-notification-in-dynamics-nav

**Comment by j-wilder** [comment]
Perfect!  I totally missed that when tracing through how it worked.  It oddly doesn't use the My Notifications table but another table called User Preference which gets populated from disabling something in the My Notifications table.  This is solved, thanks a lot!
