### ISSUE TITLE
[Event Request] Add OnBeforeSetItem event integration for SetItem procedure in "Item Avail. by Lot No. Lines" page

### ISSUE THREAD

**Issue by jaromirchaloupka** [microsoft/ALAppExtensions#24437]
**🕮 Change Rec.SetRange(xxx) calls with Rec.SetFilter(xxx) calls**

Please change all Rec.SetRange(xxx) calls with Rec.SetFilter(xxx) in procedure SetItem in Page 514 "Item Avail. by Lot No. Lines" or add new event integration called OnBeforeSetItem(var Rec: Record "Availability Info. Buffer", var NewItem: Record Item, NewAmountType: Enum "Analysis Amount Type", var IsHandled: Boolean) in order to manage it via our own extension.

```
procedure SetItem(var NewItem: Record Item; NewAmountType: Enum "Analysis Amount Type")
begin
    Item.Copy(NewItem);
    GenerateLines();
    if Item.GetFilter("Location Filter") <> '' then
        Rec.SetRange("Location Code Filter", Item.GetFilter("Location Filter"));

    if Item.GetFilter("Variant Filter") <> '' then
        Rec.SetRange("Variant Code Filter", Item.GetFilter("Variant Filter"));

    if NewAmountType = NewAmountType::"Net Change" then
        Rec.SetRange("Date Filter", Item.GetRangeMin("Date Filter"), Item.GetRangeMax("Date Filter"))
    else
        Rec.SetRange("Date Filter", 0D, Item.GetRangeMax("Date Filter"));

    OnAfterSetItem(Item, NewAmountType);
    CurrPage.Update(false);
end;
```

**Additional context**

Current standard solution creates a warning in case "Location Filter" field from Item table is greater than 10 characters (which is the standard length of "Location Code Filter" field in "Availability Info. Buffer" table).

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11880.

**Comment by jchaloupka1** [comment]
@JesperSchulz: Thank you for adding OnBeforeSetItem event. Unfortunately we're still not able to fix our issue. At this moment we're unable to call GenerateLines(); procedure in OnBeforeSetItem event because it's local procedure. I reviewed the standard code in SetItem procedure and what will really help us is to change all SetRange calls to SetFilter for Location Filter and Variant Filter in SetItem procedure.

`procedure SetItem(var NewItem: Record Item; NewAmountType: Enum "Analysis Amount Type")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetItem(Rec, NewItem, NewAmountType, IsHandled);
        if not IsHandled then begin

            Item.Copy(NewItem);
            GenerateLines();
            if Item.GetFilter("Location Filter") <> '' then
                Rec.SetFilter("Location Code Filter", Item.GetFilter("Location Filter"));

            if Item.GetFilter("Variant Filter") <> '' then
                Rec.SetFilter("Variant Code Filter", Item.GetFilter("Variant Filter"));

            if NewAmountType = NewAmountType::"Net Change" then
                Rec.SetRange("Date Filter", Item.GetRangeMin("Date Filter"), Item.GetRangeMax("Date Filter"))
            else
                Rec.SetRange("Date Filter", 0D, Item.GetRangeMax("Date Filter"));
        end;
        OnAfterSetItem(Item, NewAmountType);
        CurrPage.Update(false);
    end;`

In that case it will work when we will set filter for Location which is greater than 10 characters like 'BLUE|GREEN|YELLOW|RED|SILVER|ORANGE|MAGENTA' and similar way filter for Variant.

**Comment by JesperSchulz** [comment]
Could you create a new issue for us to address what's left? We're not revisiting closed issues (for process reasons) ☹️
