### ISSUE TITLE
[Event Request] OnBeforeSetApplyingCustLedgEntry in page 232 "Apply Customer Entries"

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#24443]
Please change the parameter isHandled in OnBeforeSetApplyingCustLedgEntry to a var Parameter, so that it can be handled correctly on this event.

Old:
    [IntegrationEvent(true, false)]
    local procedure OnBeforeSetApplyingCustLedgEntry(var ApplyingCustLedgEntry: Record "Cust. Ledger Entry"; GenJournalLine: Record "Gen. Journal Line"; SalesHeader: Record "Sales Header"; var CalcType: Enum "Customer Apply Calculation Type"; ServHeader: Record "Service Header"; IsHandled: Boolean)
    begin
    end;

new:
    [IntegrationEvent(true, false)]
    local procedure OnBeforeSetApplyingCustLedgEntry(var ApplyingCustLedgEntry: Record "Cust. Ledger Entry"; GenJournalLine: Record "Gen. Journal Line"; SalesHeader: Record "Sales Header"; var CalcType: Enum "Customer Apply Calculation Type"; ServHeader: Record "Service Header"; var IsHandled: Boolean)
    begin
    end;

See also OnBeforeSetApplyingVendLedgEntry in page 233 "Apply Vendor Entries", where ishandled is correctly set as var parameter.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11936.
