### ISSUE TITLE
Codeunit 90 "Purch.-Post" - Publisher  "OnBeforeUpdateAssocOrder" - make Variable var

### ISSUE THREAD

**Issue by obermeiersinghammer** [microsoft/ALAppExtensions#24448]
[IntegrationEvent(true, false)]
    local procedure OnBeforeUpdateAssocOrder(var TempDropShptPostBuffer: Record "Drop Shpt. Post. Buffer" temporary; var IsHandled: Boolean; SuppressCommit: Boolean; **var** PurchaseHeader: Record "Purchase Header")
    begin
    end;

Set parameter to var in order to allow changes (e.g. "Expected Receipt Date") before UpdateAssocSalesOrder

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13321.
