### ISSUE TITLE
Report 5196 "Remove Contacts - Refine" -  make the variable ReduceRefineSegment accessible via report extension (protected var).

### ISSUE THREAD

**Issue by monicasuica** [microsoft/ALAppExtensions#24447]
Hi,

We have codes that set the filters for more dataitems before the Remove Contacts report is run. Please make the variable ReduceRefineSegment accessible via report extension (protected var).5

![image](https://github.com/microsoft/ALAppExtensions/assets/47560247/abb943f8-eae8-4bfe-9a01-01ada6c40989)

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
