### ISSUE TITLE
[Event Request] codeunit 5510 "Production Journal Mgt" - OnBeforeInsertComponents()

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#24442]
Can you add event OnBeforeInsertComponents to be able to use IsHandled to skip the code in this procedure?
IsHandled parameter as reference

At the moment I have used the next event to set a filter on line no. = 0 to skip the rest of the code.

```
    procedure InsertComponents(ProdOrderLine: Record "Prod. Order Line"; CheckRoutingLink: Boolean; Level: Integer)
    var
        ProdOrderComp: Record "Prod. Order Component";
        // >>>>>>>>>>>>>>>>>
        IsHandled: Boolean;
        // <<<<<<<<<<<<<<<<<
    begin
        // >>>>>>>>>>>>>>>>>
        OnBeforeInsertComponents(ProdOrderLine, CheckRoutingLink, Level, IsHandled);
        if IsHandled then
            exit;
        // <<<<<<<<<<<<<<<<<

        // Components with no Routing Link or illegal Routing Link
        ProdOrderComp.Reset();
        ProdOrderComp.SetRange(Status, ProdOrderLine.Status);
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11880.
