### ISSUE TITLE
[Parameter Request] - report 7318 "Whse.-Shipment - Create Pick" OnBeforeOnPreDataItemAssemblyHeader

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#24453]
**🕮 Describe the request**

Can you please add WarehouseShipmentLine to OnBeforeOnPreDataItemAssemblyHeader.

**Additional context**

    local procedure CheckIfAsmToOrderExists(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var AssemblyHeader: Record "Assembly Header")
    var
        SalesLine: Record "Sales Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeOnPreDataItemAssemblyHeader(AssemblyHeader, IsHandled); // Old
        OnBeforeOnPreDataItemAssemblyHeader(AssemblyHeader, IsHandled, WarehouseShipmentLine); // New
        if IsHandled then
            exit;

        SalesLine.Get(WarehouseShipmentLine."Source Subtype", WarehouseShipmentLine."Source No.", WarehouseShipmentLine."Source Line No.");
        SalesLine.AsmToOrderExists(AssemblyHeader);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnPreDataItemAssemblyHeader(var AssemblyHeader: Record "Assembly Header"; var IsHandled: Boolean)  // Old 
    local procedure OnBeforeOnPreDataItemAssemblyHeader(var AssemblyHeader: Record "Assembly Header"; var IsHandled: Boolean; var WarehouseShipmentLine: Record "Warehouse Shipment Line")  // NEW
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11936.
