### ISSUE TITLE
table 7000 "Price List Header" local procedure UpdateStatus() - ConfirmManagement.GetResponse

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#24457]
We have a product where we synchronize master data from a master company, which owns the data, to a subscriber. We can do the synchronization manually but often we choose to use a job queue entry to handle this.

We are facing an issue when we try to synchronize Price Lists. In our case we have made the setup that "price list header" needs to have the status “draft” before changing the lines. Therefore, we always send data to the subscribers that the status would be “Draft” before changing the lines and after changing the lines we send the information that the status would be the same as in the master company.

Although when we use job queue entries to do the synchronize then the dialogue box asking if you want to change the status of course do not appear due to GUIALLOWED check but as the code are now Business Central will take the default value  and now we have the problem as the status will not be changed and therefore the lines would not be verified etc.

There we would like to have done a small change. In the Local Procedure UpdateStatus() in table 7000, there is this code:

local procedure UpdateStatus() Updated: Boolean;

  var

      PriceListLine: Record "Price List Line";

      ConfirmManagement: Codeunit "Confirm Management";

      PriceListManagement: Codeunit "Price List Management";

      IsHandled: Boolean;

  begin

      IsHandled := false;

      OnBeforeUpdateStatus(Rec, Updated, IsHandled);

      if IsHandled then
          exit(Updated);

      if Status = Status::Active then
          VerifySource();

      Updated := true;
      PriceListLine.SetRange("Price List Code", Code);
      if PriceListLine.IsEmpty() then
          exit;
      if Status = Status::Active then begin
          PriceListManagement.VerifyLines(PriceListLine);
          if not PriceListManagement.ResolveDuplicatePrices(Rec) then
              exit(false);
      end;

      if ConfirmManagement.GetResponse(StrSubstNo(StatusUpdateQst, Status), true) then
          PriceListLine.ModifyAll(Status, Status)
      else
          Updated := false
  end;

**📣 Expected behavior**

We want to have it changed to this as the function now will use the default value instead. so use GetResponseOrDefault

see below :
` 
Local procedure UpdateStatus() Updated: Boolean;

    var
        PriceListLine: Record "Price List Line";

        ConfirmManagement: Codeunit "Confirm Management";

        PriceListManagement: Codeunit "Price List Management";

        IsHandled: Boolean;

    begin

        IsHandled := false;

        OnBeforeUpdateStatus(Rec, Updated, IsHandled);

        if IsHandled then
            exit(Updated);
 
        if Status = Status::Active then
            VerifySource();
 
        Updated := true;

        PriceListLine.SetRange("Price List Code", Code);

        if PriceListLine.IsEmpty() then
            exit;
 
        if Status = Status::Active then begin
            PriceListManagement.VerifyLines(PriceListLine);
            if not PriceListManagement.ResolveDuplicatePrices(Rec) then
                exit(false);
        end;
 
        if ConfirmManagement.GetResponseOrDefault(StrSubstNo(StatusUpdateQst, Status), true) then
            PriceListLine.ModifyAll(Status, Status)
        else
            Updated := false
    end;
`

**Comment by pri-kise** [comment]
It would be even more helpful if we could set a global variable when we want to supprress this confirmation on some bulk operations that triggered via UI.

**Comment by stephanweidmann** [comment]
https://github.com/microsoft/ALAppExtensions/issues/24373
i think you should be able to use the new publisher OnUpdateStatusOnBeforeConfirmStatus (22.5) for your own application/process, too.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13714.
