### ISSUE TITLE
[Request for External] Remove OnPrem from methods in "SOAP Web Service Request Mgt."

### ISSUE THREAD

**Issue by mynhardt7** [microsoft/ALAppExtensions#24456]
Codeunit 1290 "SOAP Web Service Request Mgt." is very useful, but unfortunately not usable in cloud environments.

Please can the Scope(OnPrem) be removed from the following three methods to fix that.

```AL
[TryFunction]
[Scope('OnPrem')]
procedure SendRequestToWebService()
```

```AL
[Scope('OnPrem')]
procedure GetResponseContent(var ResponseBodyInStream: InStream)
```

```AL
[Scope('OnPrem')]
procedure ProcessFaultResponse(SupportInfo: Text)
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15201.
