### ISSUE TITLE
[Event Parameter Request] table "VAT Clause" - OnGetDescriptionByExtendedTextOnBeforeReadExtTextLines

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#24458]
Please update (add reference to `LanguageCode` and `DocDate` and add new `RecRelatedVariant`) parameters of `OnGetDescriptionByExtendedTextOnBeforeReadExtTextLines` event in `table "VAT Clause"`:

```al
    local procedure GetDescriptionByExtendedText(RecRelatedVariant: Variant) Result: Text
    begin
    ...
+     OnGetDescriptionByExtendedTextOnBeforeReadExtTextLines(Rec, RecRef, ExtendedTextHeader, LanguageCode, DocDate, RecRelatedVariant);
    ...
    end;

    [IntegrationEvent(false, false)]
+   local procedure OnGetDescriptionByExtendedTextOnBeforeReadExtTextLines(var VATClause: Record "VAT Clause"; var RelatedRecordRef: RecordRef; var ExtendedTextHeader: Record "Extended Text Header"; var LanguageCode: Code[10]; var DocDate: Date; RecRelatedVariant: Variant)
    begin
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11936.
