### ISSUE TITLE
[Request for External] Remove OnPrem from method GetCurrentImportProtocol

### ISSUE THREAD

**Issue by mynhardt7** [microsoft/ALAppExtensions#24455]
Will you please remove the Scope(OnPrem) from function GetCurrentImportProtocol in codeunit 11000005 "Import Protocol Management". This codeunit is present in the NL version.

```AL
[Scope('OnPrem')]
procedure GetCurrentImportProtocol(var ImportProtocol: Record "Import Protocol"): Boolean
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
