### ISSUE TITLE
[Help] Preprocessor Symbols

### ISSUE THREAD

**Issue by josalm** [microsoft/ALAppExtensions#24469]
Hi

First of all, sorry if this isn't the right place to write this ticket.

If i want to use your preprocessor symbols how can i do that? I tried using the app.json property with no luck.
I.E.

![imagem](https://github.com/microsoft/ALAppExtensions/assets/14805835/0da31bda-8198-4f21-a485-c639a073b947)

I want to skip the "if UseLegacyInvoicePosting() then". How can i do that?

Best regad

**Comment by RadoArvay** [comment]
You cannot use symbols out of your app.

**Comment by josalm** [comment]
So, if i want to test the new feature regarding Invoice Posting, i need to wait until MS launch a beta version of 23?

**Comment by RadoArvay** [comment]
Hm, no, you don't I think. If you examine `UseLegacyInvoicePosting` method, you can see the functionality is blocked for Production only and you can switch it on by the feature.

Note: BC23 is already available in the insider program and using of a sandbox in a container you can test it.

**Comment by AlexanderYakunin** [comment]
You can test all in sandbox since version 20.
