### ISSUE TITLE
[Event Request] Table 5606 "FA Posting Group" - OnAfterCheckGLAcc - CheckGLAcc - OnAfterCheckGLAcc

### ISSUE THREAD

**Issue by ZsomborCsaszi** [microsoft/ALAppExtensions#24467]
Dear Support,
We would like to add a new event called "OnAfterCheckGLAcc" to FA Posting Group table, CheckGLAcc procedure.

```
    procedure CheckGLAcc(AccNo: Code[20]; DirectPosting: Boolean)
    begin
        if AccNo = '' then
            exit;
        GLAcc.Get(AccNo);
        GLAcc.CheckGLAcc();
        if DirectPosting then
            GLAcc.TestField("Direct Posting");

        //>>New Event
        OnAfterCheckGLAcc(AccNo, DirectPosting, Rec);
        //<<New Event
    end;
```

Event

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckGLAcc(AccNo: Code[20]; DirectPosting: Boolean; FAPostingGroup: Record "FA Posting Group")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11936.
