### ISSUE TITLE
[External Request] - Page Sales Invoice List - PostDocument

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#24464]
Could PostDocument be made global?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
