### ISSUE TITLE
[Bug / Breaking change] BC22.4 vs. BC23-Insider - report 5880 "Calc. Phys. Invt. Order Lines"

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#24476]
hi,

there is a breaking change between BC22.4 and BC23-insider releases.

**report 5880 "Calc. Phys. Invt. Order Lines"**

**page field 1.)**

before:
field(CalcQtyExpected; CalcQtyExpected)

after:
field(CalcQtyExpectedField; CalcQtyExpected)

**page field 2.)**

before:
field(ZeroQty; ZeroQty)

after:
field(ZeroQtyField; ZeroQty)
                    

see Screenshot:
![image](https://github.com/microsoft/ALAppExtensions/assets/34685182/52b88631-5dab-46b4-be21-13f10e1da206)

Please fix this for the preview.

**Comment by pri-kise** [comment]
@sschuh thanks for pointing this out.
This was mostly done by accident.
I've reported this to the people who were involved in this change and hopefully we get this fixed before BC 23 will be released.

**Comment by JesperSchulz** [comment]
Issue resolved in 23.0.
