### ISSUE TITLE
[Event Publisher Request] extend procedure UpdateDatesInLines in Table "Price List Header"

### ISSUE THREAD

**Issue by CarstenHeu** [microsoft/ALAppExtensions#24485]
I want to extend / change the filter of the PriceListLine Variable in the "UpdateDatesInLines" procedure in the "Price List Header" table before it calls the ModifyAll of the "Ending Date". Within the Publisher I need at least the PriceListLine Variable given as per reference Parameter. To add the Rec Variable as well perhaps could be usefull..

The Customer wants only to update the lines who do not have an ending date and not such who already have an other ending date as the new one. They use the option to change header values in the lines, but use the single Price List for all times. So they add new lines with new prices to the one existing Price List and want to set the Ending Date for the old Prices at the end over the Header value. But if they do it for the second time, they loose the history of the first ending date, because the standard would overwrite the old ending dates. So I would need a Eventpublisher to change the filter of the field "Ending Date" before calling the ModifyAll of the "Ending Date" statement.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11948.
