### ISSUE TITLE
Update procedure PopulateApprovalEntryArgument in codeunit 1535 "Approvals Mgmt."

### ISSUE THREAD

**Issue by complord** [microsoft/ALAppExtensions#24487]
Currently the procedure PopulateApprovalEntryArgument in codeunit 1535 calls an integration event with an IsHandled parameter that isn't used:

```
    begin
        OnBeforePopulateApprovalEntryArgument(WorkflowStepInstance, ApprovalEntryArgument, IsHandled);

        ApprovalEntryArgument.Init();
        ApprovalEntryArgument."Table ID" := RecRef.Number;
        .
        .

```

Request update to:

```
    begin
        IsHandled := false;
        OnBeforePopulateApprovalEntryArgument(WorkflowStepInstance, ApprovalEntryArgument, IsHandled);
        if IsHandled then
           exit;

        ApprovalEntryArgument.Init();
        ApprovalEntryArgument."Table ID" := RecRef.Number;
        .
        .

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11948.
