### ISSUE TITLE
Event Request - Codeunit 7024 "Job Planning Line - Price"

### ISSUE THREAD

**Issue by NS-NN** [microsoft/ALAppExtensions#24499]
Hi,
Is it possible to add "OnBeforeAddSources" or "OnAfterAddSources" in procedure "AddSources()" in codeunit "Job Planning Line - Price"?
It is possible in codeunit "Sales Line - Price" and "Job Journal Line - Price".

Thank you in advance.

**Comment by AleksandricMarko** [comment]
Hello @NS-NN 
It is possible. Which one better fits your needs?
Which parameters do you need as a part of event?

**Comment by NS-NN** [comment]
> Hello @NS-NN It is possible. Which one better fits your needs? Which parameters do you need as a part of event?

You decide. 
If I have to choose one of them, I prefer "OnAfterAddSources(JobJournalLine, CurrPriceType, PriceSourceList)".
If possible, you can implement both of them 👍

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11959.
