### ISSUE TITLE
[Event parameter request] table 27 Item - OnBeforeOnInsert- OnInsert 

### ISSUE THREAD

**Issue by CCOSR** [microsoft/ALAppExtensions#24501]
Dear Support,
We would like to add a new parameter to event "OnBeforeOnInsert" to table 27 Item, OnInsert procedure.

trigger OnInsert()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
   //>>New Event parameter xRec
        OnBeforeOnInsert(Rec, xRec, IsHandled);
//<<New Event parameter xRec
        if not IsHandled then begin
            if "No." = '' then begin
                GetInvtSetup();
                InventorySetup.TestField("Item Nos.");
                NoSeriesMgt.InitSeries(InventorySetup."Item Nos.", xRec."No. Series", 0D, "No.", "No. Series");
                "Costing Method" := InventorySetup."Default Costing Method";
            end;

            DimMgt.UpdateDefaultDim(
              DATABASE::Item, "No.",
              "Global Dimension 1 Code", "Global Dimension 2 Code");

            UpdateReferencedIds();
            SetLastDateTimeModified();

            UpdateItemUnitGroup();
        end;

        OnAfterOnInsert(Rec, xRec);
    end;

Event

    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnInsert(var Item: Record Item; xRec: Record Item; var IsHandled: Boolean)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11959.
