### ISSUE TITLE
Incorrect errors when Bank Account info does not match CODA File contents

### ISSUE THREAD

**Issue by dsaveyn** [microsoft/ALAppExtensions#24506]
**🕮 Describe the issue**

The CODA Import functionality throws some incorrect errors when the settings on the Bank Account differ from the ones in the CODA file:

![image](https://github.com/microsoft/ALAppExtensions/assets/92365904/b06928f8-6e43-4314-a1da-c2e7ceb428a0)

![image](https://github.com/microsoft/ALAppExtensions/assets/92365904/45f702cc-3777-416d-8adc-47f51b99c637)

**🔧 To Reproduce**

1. Go to a random Bank Account
2. On the Posting fasttab, set a Protocol No, Version or Version Code that differs from the CODA Fileyou want to import.
3. Click Import CODA File and upload a CODA File.
4. The errors above are thrown

**📣 Expected behavior**

A more meaningful error should be thrown, displaying the value configured on the Bank Account and the one included in the CODA File. This way, the user does not have to open the CODA File to see the actual values.

This can be easily solved by performing the following modification;

`codeunit 2000040 "Coda Import Management"`

**Before:**
`
Text003: Label 'Protocol number %1 of bank account %2 does not match protocol number %3 of %4 record.';
`

**After:**
`
Text003: Label '%1 %2 of %3 %4 does not match %1 %5 of %6 record.';
`

**Comment by fvet** [comment]
@dsaveyn Can you please update title to include [Application Bug], so it get's tagged properly?

To MS, this is a small change, no impact on business logic, but improves the UX and avoids partners from cloning Base app objects...

---

Some more context.

In `codeunit 2000040 "Coda Import Management"`, the `Text003` label contains **4** placeholders but it's called from code with **6** arguments (= Bug). The Text003` label should be updated as requested above.

Occurrences in Base App (Belgian localisation) of `Text003` (these can remain, as long as the label is properly updated to include 6 placeholders)

```
if ProtocolNo <> BankAcc."Protocol No." then
                Error(Text003,
                  BankAcc.FieldCaption("Protocol No."),
                  BankAcc."Protocol No.",
                  BankAcc.TableCaption(),
                  BankAcc."No.",
                  ProtocolNo,
                  ID);
            if VersionCode <> BankAcc."Version Code" then
                Error(Text003,
                  BankAcc.FieldCaption("Version Code"),
                  BankAcc."Version Code",
                  BankAcc.TableCaption(),
                  BankAcc."No.",
                  VersionCode,
                  ID);
```

Expected result:

- Protocol No. XXX of Bank Account YYY does not match Protocol No. ZZZ of ID record.
- Version Code XXX of Bank Account YYY does not match Version Code ZZZ of ID record.

**Comment by AlexanderYakunin** [comment]
Should you have created simple support ticket for that? This forum is not for bug reporting but for delivering extensibility related requests for partners.

**Comment by dsaveyn** [comment]
Okay now I'm confused because this github contains other bugs:

![image](https://github.com/microsoft/ALAppExtensions/assets/92365904/8242f3f9-9cd9-4527-9479-d2d8b6b6518d)

**Comment by dsaveyn** [comment]
@AlexanderYakunin @JesperSchulz 

I have created a support request (2310040030004160) for this. I thought this would be simple process since this is clearly a bug and a oneliner to fix (I even provided the fix).

 Little did I expect to have to explain in dozen's of e-mails what the problem was while this is clearly described in this github issue (I even referenced it in the support ticket). I even had a Teams Call in which I demonstrated the issue and even showed the fix. The person handling this did not understand the problem nor the fix. I was told to create an idea for this (really? for a bug?). 

Can this please be handled? I'm under the impression we're not taken seriously...

**Comment by JesperSchulz** [comment]
Sorry, I am no longer monitoring this repository that much anymore, and hence haven't seen your issue until now.

First of all, you are right. Processes have gotten a little blurry, as we haven't been quick enough to shut down bug reports on this repository. For that I apologize. This repo is for extensibility requests only. Product defects must indeed get reported through our support system, to ensure the proper handling of the issue. The "proper handling", however, doesn't seem to have happend in what you describe! I'll see what went wrong there.

In the meantime I can see, that your issue was fixed last months. You should hence soon receive it.

My apologies for the poor experience.
