### ISSUE TITLE
Create new integration event when API subscriptions are created/modified or deleted

### ISSUE THREAD

**Issue by RonKoppelaar** [microsoft/ALAppExtensions#24505]
When event subscribers are created in BC there's no way to get notified about the subscription being created / updated or deleted. Preferable an OnBefore<Action>/OnAfter<Action> event would make sense. All details about the event subscription being created/modified or deleted should be passed to the event publisher.

**Why do we need such**
At the moment there's no way to take action when these event subscriptions are being created. For the old events it's an internal table, voor the new business events its part of the platform.

Use case we see here, is to create/update/delete also an event grid subscription in case the a specific event subscriber is created in BC. To keep the subscriptions in Sync we need to know what happens with the events in BC.

**Comment by JesperSchulz** [comment]
Hi @RonKoppelaar,

this sounds like a bit more than we can handle through a normal event request. The idea is great, but it's not a simple "please add event" ask. Could I ask you to create a [BC Idea](https://aka.ms/bcideas) instead? Thanks a lot!

**Comment by JesperSchulz** [comment]
Idea created by Ron: https://experience.dynamics.com/ideas/idea/?ideaid=f72007e1-4d02-ef11-a73c-6045bdb93e93 🥳
