### ISSUE TITLE
[Change Request] codeunit 1013 "Job Jnl.-Post Batch" - GuiAllowed

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#24516]
Hello, can you please add the GuiAllowed condition to the local procedure UpdateAndDeleteLines() in codeunit 1013 "Job Jnl.-Post Batch"?

    local procedure UpdateAndDeleteLines()
    var
        IsHandled: Boolean;
    begin
        OnBeforeUpdateAndDeleteLines(JobJnlLine);

        with JobJnlLine do begin
            if JobRegNo <> 0 then
                if JobJnlTemplate.Recurring then begin
                    // Recurring journal
                    LineCount := 0;
                    JobJnlLine2.CopyFilters(JobJnlLine);
                    JobJnlLine2.Find('-');
                    repeat
                        LineCount := LineCount + 1;
                        if GuiAllowed then begin
                            Window.Update(5, LineCount);
                            Window.Update(6, Round(LineCount / NoOfRecords * 10000, 1));
                        end;
                        if JobJnlLine2."Posting Date" <> 0D then
                            JobJnlLine2.Validate("Posting Date", CalcDate(JobJnlLine2."Recurring Frequency", JobJnlLine2."Posting Date"));
                        if (JobJnlLine2."Recurring Method" = JobJnlLine2."Recurring Method"::Variable) and
                           (JobJnlLine2."No." <> '')
                        then

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13340.

**Comment by pri-kise** [comment]
@JesperSchulz is there any chance to get this into BC23.3?
I can only see those changes for BC24.0.
Our customer has the request to post some Job Journals via Job Queue, but this is currently not possible.

**Comment by JesperSchulz** [comment]
Sure :) Special favor coming right up! I'll push it to 23.x now.

**Comment by pri-kise** [comment]
Could you include the related issue https://github.com/microsoft/ALAppExtensions/issues/24515 there, too?

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 14861.
