### ISSUE TITLE
Event Request - codeunit 7024 "Job Planning Line - Price" - OnAfterAddSources

### ISSUE THREAD

**Issue by JeremyOrgan-DC** [microsoft/ALAppExtensions#24526]
**🕮 Describe the request**

Please could we have the following event added to codeunit 7024 "Job Planning Line - Price"

    [IntegrationEvent(false, false)]
    local procedure OnAfterAddSources(
        Job: Record Job; JobPlanningLine: Record "Job Planning Line";
        PriceType: Enum "Price Type"; var PriceSourceList: Codeunit "Price Source List")
    begin
    end;

    local procedure AddSources()
    var
        Job: Record Job;
        SourceType: Enum "Price Source Type";
    begin
        Job.Get(JobPlanningLine."Job No.");
        PriceSourceList.Init();
        case CurrPriceType of
            CurrPriceType::Sale:
                begin
                    PriceSourceList.Add(SourceType::"All Customers");
                    PriceSourceList.Add(SourceType::Customer, Job."Bill-to Customer No.");
                    PriceSourceList.Add(SourceType::Contact, Job."Bill-to Contact No.");
                    PriceSourceList.Add(SourceType::"Customer Price Group", JobPlanningLine."Customer Price Group");
                    PriceSourceList.Add(SourceType::"Customer Disc. Group", Job."Customer Disc. Group");
                end;
            CurrPriceType::Purchase:
                PriceSourceList.Add(SourceType::"All Vendors");
        end;
        PriceSourceList.AddJobAsSources(JobPlanningLine."Job No.", JobPlanningLine."Job Task No.");
        OnAfterAddSources(Job, JobPlanningLine, CurrPriceType, PriceSourceList);
    end;

**Additional context**

This will allow us to add additional sources and mimics the events available in Sales Line - Price

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11976.
