### ISSUE TITLE
[Event Request] Table 81 "Gen. Journal Line" - GetCustomerAccount

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24537]
Please add the following Event GetCustomerAccount in Table 81 "Gen. Journal Line"
```
local procedure GetCustomerAccount()
<...>
        CheckConfirmDifferentCustomerAndBillToCustomer(Cust, "Account No.");
        //>> Begin
        OnGetCustomerAccountOnBeforeValidatePaymentTermsCode(Rec, Cust, HideValidationDialog);
        //<< End
        Validate("Payment Terms Code");
```
```
    [IntegrationEvent(false, false)]
    local procedure OnGetCustomerAccountOnBeforeValidatePaymentTermsCode(var GenJournalLine: Record "Gen. Journal Line"; var Cust: Record Customer; HideValidationDialog: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12007.
