### ISSUE TITLE
[Event Request] Table 5196 "To-do Interaction Language" - OpenAttachment

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24531]
Please add the following Event OpenAttachment in Table 5196 "To-do Interaction Language"
```
procedure OpenAttachment(PageNotEditable: Boolean)
    var
        Attachment: Record Attachment;
        IsHandled: Boolean;
    begin
        //>> Begin
        IsHandled := false;
        OnBeforeOpenAttachment(Rec, PageNotEditable, IsHandled);
        if IsHandled then
            exit;
        //<< End
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOpenAttachment(var TodoInteractionLanguage: Record "To-do Interaction Language"; var PageNotEditable: Boolean; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 11976.
