### ISSUE TITLE
[Event Request] Page 392 "Phys. Inventory Journal" - OnDeleteRecord

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24540]
Please add the following Event OnDeleteRecord Page 392 "Phys. Inventory Journal"
```
trigger OnDeleteRecord(): Boolean
    var
        ItemJnlLineReserve: Codeunit "Item Jnl. Line-Reserve";
    begin
        //>> Begin
        OnBeforeDeleteRecordOnPage(Rec);
        //>> End
        Commit();
        if not ItemJnlLineReserve.DeleteLineConfirm(Rec) then
            exit(false);
        ItemJnlLineReserve.DeleteLine(Rec);
    end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteRecordOnPage(var ItemJournalLine: Record "Item Journal Line")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12007.
