### ISSUE TITLE
[Event Request] Codeunit 5705 "TransferOrder-Post Receipt" - RunWithCheck

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24548]
Please add the following Event RunWithCheck in Codeunit 5705 "TransferOrder-Post Receipt"
```
internal procedure RunWithCheck(var TransferHeader2: Record "Transfer Header")
<...>
            "Last Receipt No." := TransRcptHeader."No.";
            //>> Begin
            OnBeforeModifyTransferHeader(TransHeader);
            //<< End
            Modify();
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeModifyTransferHeader(var TransferHeader: Record "Transfer Header");
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12007.
