### ISSUE TITLE
[Event Request] Codeunit 5876 "Phys. Invt. Rec.-Finish" - "Code"

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24544]
Please add the following Event  "Code" in Codeunit 5876 "Phys. Invt. Rec.-Finish"
```
procedure "Code"()
    var
        IsHandled: Boolean;
    begin
<...>
            Status := Status::Finished;
            Modify();
        end;
        //>> Begin
        OnAfterCode(PhysInvtRecordHeader);
        //<< End
    end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCode(var PhysInvtRecordHeader : Record "Phys. Invt. Record Header");
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12007.
