### ISSUE TITLE
[Event Request] Table 7114 "Analysis Line" - OnLookupTotalingRangeCaseElse

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24558]
Please add the following Event OnLookupTotalingRangeCaseElse in Table 7114 "Analysis Line"
```
    procedure LookupTotalingRange(var Text: Text)Result: Boolean
<...>
                end;
            //>> Begin
            else
                OnLookupTotalingRangeCaseElse(Rec,Text,Result);
            //<< End
        end;
    end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnLookupTotalingRangeCaseElse(var AnalysisLine: Record "Analysis Line"; var Text: Text; var Result: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12025.
