### ISSUE TITLE
[Event Request] Report 1002 "Post Inventory Cost to G/L" - protected var

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24556]
Please add the following Variables PostMethod, DocNo, Post to protected var in Report 1002 "Post Inventory Cost to G/L" 
```
    //>> Begin
    protected var        
        PostMethod: Option "per Posting Group","per Entry";
        DocNo: Code[20];
        Post: Boolean;
    //<< End
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13579.
