### ISSUE TITLE
[Event Request] Codeunit 5720 "Item Reference Management" - OnBeforeCreateItemReference 

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24555]
Please add the following Event OnBeforeCreateItemReference in Codeunit 5720 "Item Reference Management"
```
    local procedure CreateItemReference(ItemVend: Record "Item Vendor")
    var
        ItemReference2: Record "Item Reference";
        IsHandled: Boolean;
    begin        
        //>> Begin
        OnBeforeCreateItemReference(ItemVend, IsHandled);
        if IsHandled then
            exit;
        //<< End

        FillItemReferenceFromItemVendor(ItemReference2, ItemVend);
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateItemReference(ItemVend : Record "Item Vendor";var IsHandled : Boolean);
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12025.
