### ISSUE TITLE
[Event Request] Table 81 "Gen. Journal Line" - OnBeforeCheckAdjustmentAppliesto

### ISSUE THREAD

**Issue by tuan-nguyen-fenwick** [microsoft/ALAppExtensions#24577]
Hi Microsoft AL Development Team,

Could you please the following integration event to the `CheckAdjustmentAppliesto` procedure in table 81 "Gen. Journal Line"?

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckAdjustmentAppliesto(GLSetup: Record "General Ledger Setup"; SourceCodeSetup: Record "Source Code Setup"; var IsHandled: Boolean)
    begin
    end;
```

![image](https://github.com/microsoft/ALAppExtensions/assets/69611495/553d62bb-6208-493f-8814-caaa631811b0)

When we try to enter a refund line, apply it to the customer payment and post the line in the **Cash Receipt Journal** page, we get this warning message and we would like to hide this pop-up message. Adding the new event would help us to achieve this.

![image](https://github.com/microsoft/ALAppExtensions/assets/69611495/bf8dd35a-5af4-4716-9680-15fc067f6d23)

Please let me know if you have any questions. 

Thank you.

Kind regards,
Tuan Nguyen

**Comment by AleksandricMarko** [comment]
Hello @tuan-nguyen-fenwick 
Is this some localization of GenJournalLine table? As in w1, procedure CheckAdjustmentAppliesto  not exist.
Also, we are adding new events just in the latest version of BC (currently BC22)

**Comment by tuan-nguyen-fenwick** [comment]
Hi @AleksandricMarko,

Yes, correct. We are using AU version of BC. Where can I raise this issue if it is a region-specific request?

Regards,
Tuan
