### ISSUE TITLE
[Event Request] Page 6648 "Get Return Shipment Lines" - OnBeforeIsFirstDocLine 

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24579]
Please add the following Event OnBeforeIsFirstDocLine in Page 6648 "Get Return Shipment Lines"
```
    local procedure IsFirstDocLine(): Boolean
    var
        ReturnShptLine: Record "Return Shipment Line";
    begin
        //>><< New event
        OnBeforeIsFirstDocLine(Rec, TempReturnShptLine);
        TempReturnShptLine.Reset();
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsFirstDocLine(var ReturnShipmentLine: Record "Return Shipment Line"; var TempReturnShptLine: Record "Return Shipment Line" temporary);
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12046.
