### ISSUE TITLE
[Event Request] Report 202 "Sales Document - Test" - OnBeforeVerifySellToCust

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24591]
Please add the following Event OnBeforeVerifySellToCust in Report 202 "Sales Document - Test"
```
            trigger OnAfterGetRecord()
<...>
                Receive := ShipReceiveOnNextPostReq;

                //>><< New event
                OnBeforeVerifySellToCust("Sales Header", ErrorText, ErrorCounter);

                VerifySellToCust("Sales Header");
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeVerifySellToCust(SalesHeader: Record "Sales Header"; var ErrorText: array[99] of Text[250]; var ErrorCounter: Integer)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12046.
