### ISSUE TITLE
[Event Request] Page 43 "Sales Invoice" - protected var

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24594]
Please move the following Variables SkipConfirmationDialogOnClosing, DocumentIsPosted to protected var in Page 43 "Sales Invoice"
```
    protected var
        ShipToOptions: Enum "Sales Ship-to Options";
        BillToOptions: Enum "Sales Bill-to Options";
        //>> New variables
        SkipConfirmationDialogOnClosing: Boolean;
        DocumentIsPosted: Boolean;
        //<< End
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
