### ISSUE TITLE
[Event Request] Codeunit 6638 "Sales-Get Return Receipts" - OnAfterTransferLinesToSalesDoc

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24592]
Please add the following Event OnAfterTransferLinesToSalesDoc in Codeunit 6638 "Sales-Get Return Receipts"
```
    procedure CreateInvLines(var ReturnRcptLine2: Record "Return Receipt Line")
<...>
                until Next() = 0;
                //>><< New event
                OnAfterTransferLinesToSalesDoc(SalesHeader);
            end;
        end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterTransferLinesToSalesDoc(VAR SalesHeader : Record "Sales Header");
    begin
    end;
```

**Comment by AleksandricMarko** [comment]
Hi @AdrijaSipaviciute 
You have existing OnAfterCreateInvLines(SalesHeader); which could be used here.
We can add just var if it is necessary.

**Comment by AdrijaSipaviciute** [comment]
Hi @AleksandricMarko 
I agree, we will use OnAfterCreateInvLines event. Var is not required. Issue can be closed.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12046.
