### ISSUE TITLE
Refactoring: Codeunit 226 CustEntry-Apply Posted Entries

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#2460]
`Codeunit 226 CustEntry-Apply Posted Entries` has a series of issues that prevent us from using it in the following case: 

We need to post and immediately & automatically apply a partial payment with special VAT setups during posting of an invoice. This is because of local fiscal regulations.

The problem is that this codeunit explicitly and implicitly issues COMMITs that might leave us with partially posted stuff.

1) Method `Apply` calls `PaymentToleranceMgt.PmtTolCust` which is full of `COMMIT`s. Are those really required? Please remove them. A `SetBlockCommit` might help in some cases, but not in ours, as this codeunit is not directly invoked by us.

2) Inside the codeunit itself in `CustPostApplyCustLedgEntry` there is an explicit `COMMIT`. I don't see why it would be required.

**Comment by Addice73** [comment]
Need this !

**Comment by AlexanderYakunin** [comment]
Since time of this request we implemented SetSuppressCommit() procedure here, so you can skip commits if needed.
