### ISSUE TITLE
Codeunit Data Compression utility methods

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#24604]
Duplicate of issue #419 from the `BusinessCentralApps` repo for implementation, has been approved over there by @JesperSchulz.

---- original issue ----

**🕮 Describe the issue**

The codeunit `Data Compression` is missing two handy utility methods:

1. `IsZip` that indicates whether a given stream actually is a ZIP stream. This comes in handy when a user has the ability to either provide a ZIP or a non-ZIP stream, and the code needs to react accordingly. This codeunit already has a method that does so for GZip streams, but not for ZIP.
2. An overload for `ExtractEntry` that creates TempBlob Codeunit instead of an outstream. Without this, I often find myself writing exactly this, because I need to pass along the decompressed data and receiving only an OutStream, I need to first manually write it it to a TempBlob to allow it being read further down my code.

**Comment by pri-kise** [comment]
I'm really looking forward to your PR to address this issue. :)
