### ISSUE TITLE
[Event Change Request] Codeunit 80 "Sales-Post" functions CreatePrepaymentLines and OnBeforeCreatePrepaymentLines

### ISSUE THREAD

**Issue by ViktorasDanielius** [microsoft/ALAppExtensions#24615]
Please change Codeunit 80 "Sales-Post" functions CreatePrepaymentLines and OnBeforeCreatePrepaymentLines to have SalesHeader parameter as "var":

procedure CreatePrepaymentLines(**VAR** SalesHeader: Record "Sales Header"; CompleteFunctionality: Boolean)

local procedure OnBeforeCreatePrepaymentLines(**VAR** SalesHeader: Record "Sales Header"; var TempPrepmtSalesLine: Record "Sales Line" temporary; CompleteFunctionality: Boolean; var IsHandled: Boolean; var TempSalesLineGlobal: Record "Sales Line" temporary)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13411.
