### ISSUE TITLE
Change OnPrem scope to Cloud (for some system tables)

### ISSUE THREAD

**Issue by waldo1001** [microsoft/ALAppExtensions#24613]
**🕮 Describe the issue**

For some tables, it's very interesting to be able to just show the data, to have an overview of the corresponding data.

However, some tables are set to "OnPrem" scope, while there (in my opinion) there is really no reason as the data is as interesting in the cloud as it is OnPrem.  Not only, it's misusing the attribute - it also prevents quite some scenarios, where the simplest to understand scenario is: show the data to analyze issues.

Here is a list of tables I'd like to change (if possible):
- "Api Webhook Entity"
- "API Webhook Subscription"
- "Webhook Notification"
- "Installed Application"
- "Application Dependency"
- "Extension Execution Info"
- "Isolated Storage"
- "Table Information"

I realize that it's not possible to make these pages "Cloud" scope in a pullrequest, as these are tables in the 2000000000-range (or is it?).

So - alternatively, I'd foresee "system-pages" that basically just publishes the data in a page - again - because it's interesting data ..

**Comment by pri-kise** [comment]
Missing access on TableInformation is really very annoying.
https://github.com/microsoft/ALAppExtensions/issues/23952

**Comment by Jonathanvdlustgraaf** [comment]
@waldo1001  If I may add...

I wanted to create a monitoring app so that we can see when clients have extensions that are uploaded as DEV and send a teams message, so that we can monitor who uploads extensions in the wrong way. 

There are no API's that I can use for this usecase within Power Automate, the ones that are provided by Microsoft don't trigger the Power Automate action. We can't make any API's ourselves, because all the related tables are locked behind Scope = Onprem. 

I tried to find a workaround by: 
[EventSubscriber(ObjectType::Table, Database::"NAV App Setting", 'OnAfterInsertEvent', '', False, False)]
    local procedure Onafter(var Rec: Record "NAV App Setting"; RunTrigger: Boolean)
    var
        PublishedApplication: Record "Published Application";
    begin
        //Get the App id and then get the information from published application. 
        
    end;
    
    But I can't get the information, because again it's locked behind Scope=Onprem...

**Comment by waldo1001** [comment]
And the funny thing is - it's just as "Cloud" as it is "OnPrem"...

**Comment by JesperSchulz** [comment]
I'll forward this request to our platform team.

**Comment by guidorobben** [comment]
It would be nice to be able to show the data of 
API Webhook Subscription
Webhook Subscription

**Comment by guidorobben** [comment]
@Jonathanvdlustgraaf 
> @waldo1001 If I may add...
> 
> I wanted to create a monitoring app so that we can see when clients have extensions that are uploaded as DEV and send a teams message, so that we can monitor who uploads extensions in the wrong way.
> 
> There are no API's that I can use for this usecase within Power Automate, the ones that are provided by Microsoft don't trigger the Power Automate action. We can't make any API's ourselves, because all the related tables are locked behind Scope = Onprem.
> 
> I tried to find a workaround by: [EventSubscriber(ObjectType::Table, Database::"NAV App Setting", 'OnAfterInsertEvent', '', False, False)] local procedure Onafter(var Rec: Record "NAV App Setting"; RunTrigger: Boolean) var PublishedApplication: Record "Published Application"; begin //Get the App id and then get the information from published application.
> 
> ```
> end;
> 
> But I can't get the information, because again it's locked behind Scope=Onprem... 
> ```

Cant you use NAV App Installed App for this?

**Comment by DonHendriksen** [comment]
On the 'Microsoft Idea' website there is topic named 'Exposing Object Metadata in Business Central Public Cloud' which requests to expose the 'Application Object Metadata' table data in cloud. Although this table is not mentioned in the initial post of Waldo I think it is in the same area. Might be good to vote this idea, and hopefully the rest will follow.
Follow [this link](https://experience.dynamics.com/ideas/idea/?ideaid=2824e8e7-e7c4-ea11-bf21-0003ff68992a) to the Microsoft Idea page.

**Comment by JesperSchulz** [comment]
Closing this issue, as platform requests can't get addressed through GitHub. I can see that the appropriate BC ideas have been created, which is the right way to request change in the platform. Closing this issue.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25.0.17043.0.

**Comment by waldo1001** [comment]
This is getting complicated :(
