### ISSUE TITLE
Global buffer variable for VAT entries in Codeunit 12

### ISSUE THREAD

**Issue by Kowa63** [microsoft/ALAppExtensions#2461]
Codeunit 12 already has several buffer variables like TempGLEntryBuf,CVLedgEntryBuf, DtldCVLedgEntryBuf to pass instances of temporary records throughout the application but currently none for the VAT entries (Table 254).

Would it be possible to introduce such a temporary record variable (in global scope) so that it may be used in planned new publishers and evaluated in likewise subscribers? Naturally, to avoid conflicts between other 3rd party extensions possibly using the same variable you would need to add some means of identification like a new field in a table extension for the VAT entries to ensure you only process your own records in the subscriber. 

Otherwise the normal instance of the VAT entries would have used as a parameter in the publishers which would make further processing much more challenging because temporary instances of VAT entries would have to be fully maintained outside of Codeunit 12.

**Comment by RomanZanizdra** [comment]
Hi Kowa63. You ask for very significant change. It's not on our radar now. If it is so important for you, can you describe a business case where you strongly required to work with global temporary VAT Entry? Just to understand the context.

**Comment by RomanZanizdra** [comment]
Hi Kowa63.
I plan to close this issue. Do you have any objections?

**Comment by Kowa63** [comment]
Currently we use this to enable unapplying a particular entry when one payment was used to settle several invoices. In the standard you can only unapply all of them ( i.e. all those which were posted in one transaction) but cannot select a specific one. That is an enhancement we introduced almost a decade ago.

That is a common requirement in the health insurance industry when invoices sent in by doctors and hospitals are all approved at first , but after closer examination of the treatments that were given it may be decided some days later that the cost of one which was included in the bunch is not covered by the regulations, so this particular one must be unapplied. In this situation is essential to evaluate the correct inverted VAT amounts  

We have recently introduced our own transaction no. to work our way around the limitations of using publishers and subcribers in situations like these. Not sure if this is going to work though.

**Comment by RomanZanizdra** [comment]
So requesting for implementation of temporary vat entry (by the way isn't it used in PostUnapply function) and requesting for events/global functions are different things. If you lack of some events or functions let us know, will see what can be done there.

**Comment by Kowa63** [comment]
Actually, Event Request/Function Expose were not the point of my question. We created several such issues in the last weeks as you see here (and there will be more to come) and luckily most were accepted ;-).
https://github.com/microsoft/ALAppExtensions/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3AKowa63+
TempVatEntry is used a parameter in PostUnapply. We do not want to intervene into handling these records in any way. The point was to have a global buffer that can be filled in any function and evaluated in any function whenever it may be necessary to determine how further processing will take place under certain conditions.

**Comment by RomanZanizdra** [comment]
Ok, I see. So as I mentioned above this is not extensibility task. Please put your suggestion on the https://aka.ms/bcideas to have a discussion on it with others or PMs.

**Comment by RomanZanizdra** [comment]
Hi Kai. Let's close this issue for now and please log your suggestion at the ideas.

**Comment by Kowa63** [comment]
Apparently there is something similar cooking here: #2557
