### ISSUE TITLE
[Event Request] codeunit 8618 "Config. Excel Exchange" function ExportExcel

### ISSUE THREAD

**Issue by ViktorasDanielius** [microsoft/ALAppExtensions#24620]
Please add new event on codeunit 8618 "Config. Excel Exchange" function ExportExcel:

```
                DataTableCounter += 2;
                //>><< NEW EVENT
                OnExportExcelOnBeforeExport(ConfigPackageTable, DataTableCounter);

                TableParts := WrkShtWriter.CreateTableParts(1);
```

```
    [IntegrationEvent(false, false)]
    local procedure OnExportExcelOnBeforeExport(var ConfigPackageTable: Record "Config. Package Table"; var DataTableCounter: Integer)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12349.
