### ISSUE TITLE
[Event Request] Page 6631 "Sales Return Order Subform" - OnBeforeOnDeleteRecord

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24623]
Please add the following Parameters DocumentTotals, Result, IsHandled to Event OnBeforeOnDeleteRecord in Page 6631 "Sales Return Order Subform" 
```
    trigger OnDeleteRecord(): Boolean
    var
        SalesLineReserve: Codeunit "Sales Line-Reserve";
        IsHandled: Boolean;
        Result: Boolean;
    begin
        //>> New event, more parameters
        IsHandled := false;
        OnBeforeOnDeleteRecord(Rec, DocumentTotals, Result, IsHandled);
        if IsHandled then
            exit(Result);
        //<< End

        if (Quantity <> 0) and ItemExists("No.") then begin
```
```
    [IntegrationEvent(false, false)]
    //>><< Modified line
    local procedure OnBeforeOnDeleteRecord(var SalesLine: Record "Sales Line"; var DocumentTotals: Codeunit "Document Totals"; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;
```

**Comment by AleksandricMarko** [comment]
Hello @AdrijaSipaviciute
please make new [External Requests] for changing scope of variable(s).
This one will be used for new event.

**Comment by AdrijaSipaviciute** [comment]
Hello @AleksandricMarko 
Changed according to your request.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12349.
