### ISSUE TITLE
[Event Request] table 83 "Item Journal Line" OnBeforeCheckNewTrackingIfRequired

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#24621]
Can you add event CheckNewTrackingIfRequired to table 83 "Item Journal Line" to be able to override the check.

```
    procedure CheckNewTrackingIfRequired(ItemTrackingSetup: Record "Item Tracking Setup")
    begin
        //>>>>>>>>>>>>>>
        OnBeforeCheckNewTrackingIfRequired(Rec, ItemTrackingSetup, IsHandled);
        if IsHandled then
            exit;
        //<<<<<<<<<<<<<<
        if ItemTrackingSetup."Serial No. Required" then
            TestField("New Serial No.");
        if ItemTrackingSetup."Lot No. Required" then
            TestField("New Lot No.");

        OnAfterCheckNewTrackingIfRequired(Rec, ItemTrackingSetup);
    end;
```

**Comment by AleksandricMarko** [comment]
Hello @auzhhv 
Unfortunately, we won't implement this event. 
It should be done on higher level, where this function is called.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
