### ISSUE TITLE
[Change Request] table 296 "Reminder Line" - procedure CalcFinChrg

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#24639]
Hello, can you please change the lokal procedure CalcFinChrg in table 296 "Reminder Line" to a global procedure?

```
    procedure CalcFinChrg()
    var
        DetailedCustLedgEntry: Record "Detailed Cust. Ledg. Entry";
        IssuedReminderHeader: Record "Issued Reminder Header";
        FinanceChargeInterestRate: Record "Finance Charge Interest Rate";
        ExtraReminderLine: Record "Reminder Line";
        InterestStartDate: Date;
        LineFee: Decimal;
        UseDueDate: Date;
        UseCalcDate: Date;
        UseInterestRate: Decimal;
        CumAmount: Decimal;
        IsHandled: Boolean;
        ShouldSkipCalcFinChrg: Boolean;
    begin
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
