### ISSUE TITLE
[Event Request] Page 233 "Apply Vendor Entries" - protected var

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24642]
Please move the following Variables ApplyingVendLedgEntry, GenJnlLine to protected var in [Event Request] Page 233 "Apply Vendor Entries"
```
    protected var
<...>
        //>> Begin
        ApplyingVendLedgEntry: Record "Vendor Ledger Entry" temporary;
        GenJnlLine: Record "Gen. Journal Line";
        //<< End
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
