### ISSUE TITLE
[Event Request] Table 60 "Document Sending Profile" - OnBeforeSendToPrinter

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24645]
Please add the following Event OnBeforeSendToPrinter in Table 60 "Document Sending Profile"
```
    procedure SendToPrinter(ReportUsage: Enum "Report Selection Usage"; RecordVariant: Variant; CustomerNoFieldNo: Integer)
<...>
    begin
        //>><< New event
        OnBeforeSendToPrinter(Rec, ReportSelections, RecordVariant);
        if Printer = Printer::No then
            exit;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSendToPrinter(var DocumentSendingProfile: Record "Document Sending Profile"; var ReportSelections: Record "Report Selections"; RecordVariant: Variant)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12406.
