### ISSUE TITLE
[Event Request] Page 344 Navigate - protected var, protected procedure

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24648]
Please move the following Variable DocExists to protected var and modify the following procedure UpdateFormAfterFindRecords to protected procedure in Page 344 Navigate
```
    protected var
<...>
        //>><< New variable
        DocExists: Boolean;
```
```
    //>><< local procedure -> protected procedure
    protected procedure UpdateFormAfterFindRecords()
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
