### ISSUE TITLE
[Event Request] Codeunit 6223 "OpenXML Management" - OnBeforeWriteCellValue

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24652]
Please add the following Event OnBeforeWriteCellValue in Codeunit 6223 "OpenXML Management"
```
    procedure WriteCellValue(var WrkShtWriter: DotNet WorksheetWriter; DataColumnDataType: Text; var DataRow: DotNet DataRow; RowsCount: Integer; ColumnsCount: Integer)
    begin
        //>><< New event
        OnBeforeWriteCellValue(RowsCount);

        case DataColumnDataType of
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeWriteCellValue(var RowsCount: Integer)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12406.
