### ISSUE TITLE
[Event Request] Codeunit 70 Purch.-Calc.Discount

### ISSUE THREAD

**Issue by SimonasDargis** [microsoft/ALAppExtensions#24672]
The following events are required for this object:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateHeader(var PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line")
    begin
    end;
```

```
    trigger OnRun()
    var
        TempPurchHeader: Record "Purchase Header";
        TempPurchLine: Record "Purchase Line";
    begin
        PurchLine.Copy(Rec);

        TempPurchHeader.Get("Document Type", "Document No.");
        OnBeforeUpdateHeader(TempPurchHeader, Rec); //EVENT REQUEST
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12399.
