### ISSUE TITLE
[Change Request] Codeunit 90 "Purch.-Post" - PostItemJnlLine

### ISSUE THREAD

**Issue by DBiernat** [microsoft/ALAppExtensions#24690]
In addition to #24408 we need the possibility to post additional G/L Entries if Automatic Cost Posting is activated. Posting those entries will end up in an error message (entry already exists) by using our own "Gen. Journal Line" and "Gen. Jnl.-Post Line variables". 

Posting is not possible, because there is no way to get the actual instance of the "Posting Inventory to G/L" Codeunit.

Adding a procedure call after throwing the event OnAfterPostItemJnlLine could solve that problem.

**Current Implementation**

        OnAfterPostItemJnlLine(ItemJnlLine, PurchLine, PurchHeader, ItemJnlPostLine);

        exit(ItemJnlLine."Item Shpt. Entry No.");

**Requested implementation**

        OnAfterPostItemJnlLine(ItemJnlLine, PurchLine, PurchHeader, ItemJnlPostLine);

        ItemJnlPostLine.CallOnPublishPostingInventoryToGL();

        exit(ItemJnlLine."Item Shpt. Entry No.");

**Additional context**

In order to be able to call the procedure CallOnPublishPostingInventoryToGL, it must be implemented in codeunit 22 "Item Jnl.-Post Line", in addition to the followed event.

    procedure CallOnPublishPostingInventoryToGL()
    begin
        OnPublishPostingInventoryToGL(ItemJnlLine, InventoryPostingToGL);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnPublishPostingInventoryToGL(ItemJournalLine: Record "Item Journal Line"; var InventoryPostingToGL: Codeunit "Inventory Posting To G/L")
    begin
    end;

If there is a better, or undiscovered solution, I would be happy to hear about it.

If this is the solution at the end, feel free to change the event name. It's always difficult to find the right names for events or procedures.

**Comment by DBiernat** [comment]
Are there any new insights here?

**Comment by DBiernat** [comment]
Any updates/comments on that case?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
