### ISSUE TITLE
[Event Request] codeunit 2680 "Data Search in Table" (App Data Search/ac14293f-1eb7-4a7b-9936-b280da31970b]

### ISSUE THREAD

**Issue by ttaeufer** [microsoft/ALAppExtensions#24691]
We needed an event at the following location to adjust the result set to our complex data structure.

Details: 
In our current solution, we have a central key value like table that we use to search master data. If we could get the event, we could combine this data structure with Data Search.
```
codeunit 2680 "Data Search in Table"
...
    local procedure SearchTable(TableNo: Integer; TableType: Integer; var FieldList: List of [Integer]; var SearchStrings: List of [Text]; var Results: Dictionary of [Text, Text])
    var
        [SecurityFiltering(SecurityFilter::Filtered)]
        RecRef: RecordRef;
        FldRef: FieldRef;
        Description: TextBuilder;
        i: Integer;
        more: Boolean;
        first: Boolean;
        UseTextSearch: Boolean;
        SearchString: Text;
        SearchString1: Text;
        FieldMatchString: Text;
        >>>>>>>>>>>>>>>>>>>>        
        IsHandled: Boolean;
        <<<<<<<<<<<<<<<<<<<<
    begin
        >>>>>>>>>>>>>>>>>>>>
        OnBeforeSearchTable(TableNo, TableType, FieldList, SearchString, Results, IsHandled);
        if IsHandled then
            exit;        
        <<<<<<<<<<<<<<<<<<<<
        ....
        ```
```        
    >>>>>>>>>>>>>>>>>>>>        
    local procedure OnBeforeSearchTable(var TableNo: Integer; var TableType: Integer; var FieldList: List of [Integer]; var SearchStrings: List of [Text]; var Results: Dictionary of [Text, Text]; var IsHandled: Boolean)
    begin         
    end;
    <<<<<<<<<<<<<<<<<<<<
```

**Comment by BardurKnudsen** [comment]
Good suggestion. Small edits:
In codeunit 2682 "Data Search Events"
internal procedure OnBeforeSearchTable(TableNo: Integer; TableType: Integer; var FieldList: List of [Integer]; var SearchStrings: List of [Text]; var Results: Dictionary of [Text, Text]; var IsHandled: Boolean)
begin         
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17376.
