### ISSUE TITLE
Suggestion to allow item attributes management for other tables

### ISSUE THREAD

**Issue by shlemonz** [microsoft/ALAppExtensions#247]
Code unit 7500 has some code that uses Table ID (integer) in some places where other ones are hard coded to Item table ID.

The attached code (Codeunit 7500 - Item Attribute Management.al) has the changes needed to be able to use it for other tables.
I have also attached Table 23036118 - Model.al and Codeunit 23036130 - Model Attribute Management.al to further clarify how to use the suggested code for Codeunit 7500 for custom table, example here is Model table.

[Codeunit 7500 - Item Attribute Management.zip](https://github.com/Microsoft/AL/files/2465074/Codeunit.7500.-.Item.Attribute.Management.zip)

**Comment by ikoletic** [comment]
This seems like a product suggestion. I'd kindly request to submit those to https://aka.ms/bcideas together with business scenario on when and how this would be useful. Thank you!

**Comment by NKarolak** [comment]
Just in case someone else is requesting this too (just like me now):
- [Vote for the idea](https://experience.dynamics.com/ideas/idea/?ideaid=52375f73-2205-e911-9461-0003ff68f3c6) / add a comment
- [Follow a discussion on Yammer](https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=574646598836224) (Dynamics 365 Business Central Development)
