### ISSUE TITLE
[Event Request] Page 7604 Base Calendar Entries Subform

### ISSUE THREAD

**Issue by SimonasDargis** [microsoft/ALAppExtensions#24758]
The following events are required for this object:

```
    [IntegrationEvent(false, false)]
    local procedure OnFilterDateRecordAfterOnOpenPage(var CustCalendarChange: Record "Customized Calendar Change"; var DateRec: Record Date)
    begin
    end;
```

```
    trigger OnOpenPage()
    begin
        DateRec.Reset();
        DateRec.SetFilter("Period Start", '>=%1', 00000101D);
        OnFilterDateRecordAfterOnOpenPage(Rec, DateRec); //EVENT REQUEST
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12501.
