### ISSUE TITLE
Job Queue Status on unposted documents is not extendable

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/ALAppExtensions#24764]
**🕮 Describe the request**

Document Headers that have field for Job Queue Status are of type Option.
I need to be able to use the Job Queue to make updates to the documents before releasing/posting.
These changes are done in Job Queue and by having this field using an extendable Enum I can add any job queue process and report the correct status to the user.

**Additional context**

Example from Sales Header table.

```
field(160; "Job Queue Status"; Option)
        {
            Caption = 'Job Queue Status';
            Editable = false;
            OptionCaption = ' ,Scheduled for Posting,Error,Posting';
            OptionMembers = " ","Scheduled for Posting",Error,Posting;

            trigger OnLookup()
            var
                JobQueueEntry: Record "Job Queue Entry";
            begin
                if "Job Queue Status" = "Job Queue Status"::" " then
                    exit;
                JobQueueEntry.ShowStatusMsg("Job Queue Entry ID");
            end;
        }
```
📣 Expected behavior

Please convert the "Job Queue Status" field to an extendable Enum.

**Comment by gunnargestsson** [comment]
Tables:
130 "Incoming Document"
181 "Posted Gen. Journal Line"
36   "Sales Header"
38   "Purchase Header"
81   "Gen. Journal Line"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12689.
