### ISSUE TITLE
[External Request] - Report Vendor/Item Purchases - variable ResetItemTotal

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#24768]
could ResetItemTotal be made protected var? I need to add more values from value entry based on that variable from onbeforeonaftergetrecord event in an report extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
