### ISSUE TITLE
[Request-For-External] Report 5753 Get Source Documents - Procedure from Local to Global

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#24767]
Hello, we need the following currently internal procedure to be set to external. Can you please check this? Thank you!

```
procedure CreateActivityFromSalesLine2ShptLine(WhseShptHeader: Record "Warehouse Shipment Header"; SalesLine: Record "Sales Line"): Boolean
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
