### ISSUE TITLE
OAuth2 with separate token endpoint

### ISSUE THREAD

**Issue by lktraser** [microsoft/ALAppExtensions#24760]
**🕮 Describe the issue**

A clear and concise description of what the issue/improvement is, which you want to address.

Hi, I want to use the OAuth2 Module to connect to several APIs. The OAuth implementation has separate endpoints to acquire the Auth Code and then the Access Token / Refresh Token. 

Example: 
authorityurl/authorize    <- used to get the Auth Code
authorityurl/token          <- used to get the Access Token with the Auth Code

The current implementation through 

`procedure AcquireTokenByAuthorizationCode(ClientId: Text; ClientSecret: Text; OAuthAuthorityUrl: Text; RedirectURL: Text; Scopes: List of [Text]; PromptInteraction: Enum "Prompt Interaction"; var AccessToken: Text; var AuthCodeErr: Text)`

gets me a valid login and Auth Code. But then the Auth Code is used in 

`procedure AcquireTokenByAuthorizationCodeWithCredentials(AuthorizationCode: Text; ClientId: Text; ClientSecret: Text; RedirectUrl: Text; OAuthAuthorityUrl: Text; Scopes: List of [Text]; var AccessToken: Text)`

by the `AuthFlow: DotNet ALAzureAdCodeGrantFlow;` instance. This does not yield an Access Token and no error either. Since this is blackbox to me I am not sure what's going on. My first instinct was that token endpoint isn't used since the codeunit only supports one AuthorityURL. But I copied the object and implemented this overload:

`procedure AcquireTokenByAuthorizationCode(ClientId: Text; ClientSecret: Text; OAuthAuthorityUrl: Text; OAuthTokenAuthorityUrl: Text; RedirectURL: Text; Scopes: List of [Text]; PromptInteraction: Enum "Prompt Interaction"; var AccessToken: Text; var AuthCodeErr: Text)`

This sets the OAuthTokenAuthorityUrl on the DotNet instance but I still do not receive a valid Access Token and no errors. Is there something I could improve here? I would like to ultimately produce a PR that enables the OAuth2 Module to handle this case.

In the meantime I will have to implement this entire OAuth flow myself without DotNet. This seems possible but a lot of work and rewriting of procedures from the OAuth2 Codeunit without use of DotNet.

This OAuth2 module is of great business value to us as we implement a lot of interfaces.

Any help or advice would be greatly appreciated.

**Comment by pri-kise** [comment]
@WaelAbuSeada can you maybe provide some insight on this topic?

**Comment by lktraser** [comment]
Hi everyone, is there any update on this topic? If I can provide any additional information I'd be happy to do so.

**Comment by pri-kise** [comment]
@lktraser it might be helpful to share this idea on yammer, too.
Currently this repository isn't watched by the platform team that might be responsible on this topic.
@JesperSchulz can maybe point this issue to the right people.

**Comment by lktraser** [comment]
Thanks @pri-kise, I'll start a conversation about it on yammer linking to this issue. Any people I should tag specifically?

**Comment by JesperSchulz** [comment]
I hope you got an answer. This repository is only for extensibility requests or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps). I'm hence closing this issue.

**Comment by lktraser** [comment]
Hi @JesperSchulz, seems like there has just been a development to this topic yesteday! My post on yammer was quoted by a localization topic from norway. Do you have any information if this change will roll out to the OAuth2 Module in general or just fix the issue for Norway?

https://www.yammer.com/dynamicsnavdev/threads/2666516937580544

**Comment by JesperSchulz** [comment]
This is news to me! I hope I can get some updates next week, when people are back in the office!
