### ISSUE TITLE
[Event Request] Page 6631 - protected var

### ISSUE THREAD

**Issue by AdrijaSipaviciute** [microsoft/ALAppExtensions#24763]
Please move the following Variable LocationCodeMandatory to protected var in Page 6631
```
    protected var
<...>
        //>><< New variable
        LocationCodeMandatory: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
