### ISSUE TITLE
Subscriber to the codeunit "SII XML Creator" event OnAfterAddPurchTail

### ISSUE THREAD

**Issue by abgrau** [microsoft/ALAppExtensions#24762]
In  #23396 the subscriber OnAfterAddPurchTail was added with the parameters XMLNode, VendorLedgerEntry.
We cannot access the  parameter XMLNode, it return error "DotNet 'System.Xml.XmlNode' is missing".
In cloud we cannot use Dotnet

**📣 Expected behavior**
We need to add elements to variable XMLNode

**Screenshots**
![error](https://github.com/microsoft/ALAppExtensions/assets/48214175/daa57ff2-bb65-4934-bf59-d556d21181da)

**Comment by AndersLarsenMicrosoft** [comment]
This is more a refactoring request and consider of off scope for extensibility request.
