### ISSUE TITLE
Table 11733 Cash Document Line CZP

### ISSUE THREAD

**Issue by DanielSmutek** [microsoft/ALAppExtensions#24761]
Please add new 4 Events to CZ localization table 11733 Cash Document Line CZP

Thank you!

Daniel

1) trigger OnLookup() of field "Applies-To Doc. No."

        field(15; "Applies-To Doc. No."; Code[20])
        {
            Caption = 'Applies-To Doc. No.';
            DataClassification = CustomerContent;

            trigger OnLookup()
            var
                GenJournalLine: Record "Gen. Journal Line";
                CashDocumentPostCZP: Codeunit "Cash Document-Post CZP";
                PaymentToleranceManagement: Codeunit "Payment Tolerance Management";
                AccountNo: Code[20];
                AccountType: Enum "Gen. Journal Account Type";
                PreviousAmount: Decimal;
                **// New Event >>
                IsHandled: Boolean;
            // New Event <<**
            begin
                GetCashDocumentHeaderCZP();
                CashDocumentPostCZP.InitGenJnlLine(CashDocumentHeaderCZP, Rec);
                CashDocumentPostCZP.GetGenJnlLine(GenJournalLine);
                PreviousAmount := GenJournalLine.Amount;

                if GenJournalLine."Bal. Account Type" in [GenJournalLine."Bal. Account Type"::Customer,
                                                      GenJournalLine."Bal. Account Type"::Vendor,
                                                      GenJournalLine."Bal. Account Type"::Employee]
                then begin
                    AccountNo := GenJournalLine."Bal. Account No.";
                    AccountType := GenJournalLine."Bal. Account Type";
                end else begin
                    AccountNo := GenJournalLine."Account No.";
                    AccountType := GenJournalLine."Account Type";
                end;

                if (AccountType.AsInteger() <> GenJournalLine."Account Type"::Customer.AsInteger()) and
                   (AccountType.AsInteger() <> GenJournalLine."Account Type"::Vendor.AsInteger()) and
                   (AccountType.AsInteger() <> GenJournalLine."Account Type"::Employee.AsInteger())
                then begin
                    AccountType := GenJournalLine."Bal. Account Type";
                    AccountNo := GenJournalLine."Bal. Account No.";
                end;
                case AccountType of
                    AccountType::Customer:
                        LookupApplyCustEntry(GenJournalLine, AccountNo);
                    AccountType::Vendor:
                        LookupApplyVendEntry(GenJournalLine, AccountNo);
                    AccountType::Employee:
                        LookupApplyEmplEntry(GenJournalLine, AccountNo);
                end;
                if GenJournalLine."Applies-to Doc. No." = '' then
                    exit;

                OnLookupAppliesToDocNoOnBeforeValidateAccountNo(GenJournalLine, Rec);
                if AccountNo = '' then
                    Validate("Account No.", GenJournalLine."Account No.");
                "Applies-To Doc. Type" := GenJournalLine."Applies-to Doc. Type";
                "Applies-To Doc. No." := GenJournalLine."Applies-to Doc. No.";
                "Applies-to ID" := GenJournalLine."Applies-to ID";
                OnLookupAppliesToDocNoOnAfterFillAppliesToDocNo(Rec, GenJournalLine);
                **// New Event >>
                OnLookupAppliesToDocNoOnBeforeValidateAmount(Rec, GenJournalLine, IsHandled);
                if not IsHandled then
                    // New Event <<**
                Validate(Amount, SignAmount() * GenJournalLine.Amount);
                if PreviousAmount <> 0 then begin
                    PaymentToleranceManagement.SetSuppressCommit(true);
                    if not PaymentToleranceManagement.PmtTolGenJnl(GenJournalLine) then
                        exit;
                end;
            end;

2) trigger OnValidate() of field "Applies-To Doc. No."

            trigger OnValidate()
            var
                GenJournalLine: Record "Gen. Journal Line";
                GenJournalBatch: Record "Gen. Journal Batch";
                CustLedgEntry: Record "Cust. Ledger Entry";
                VendorLedgEntry: Record "Vendor Ledger Entry";
                EmployeeLedgEntry: Record "Employee Ledger Entry";
                CashDocumentPostCZP: Codeunit "Cash Document-Post CZP";
                PaymentToleranceManagement: Codeunit "Payment Tolerance Management";
                **// New Event >>
                IsHandled: Boolean;
            // New Event <<**
            begin
                GetCashDocumentHeaderCZP();
                CashDocumentPostCZP.InitGenJnlLine(CashDocumentHeaderCZP, Rec);
                CashDocumentPostCZP.GetGenJnlLine(GenJournalLine);
                GenJournalLine.SetSuppressCommit(true);
                PaymentToleranceManagement.SetSuppressCommit(true);
                GenJournalBatch.Insert(); // only for "Applies-to Doc. No." validation
                GenJournalLine.Validate("Applies-to Doc. No.");
                GenJournalBatch.Delete();

                if ("Applies-To Doc. No." = '') and (xRec."Applies-To Doc. No." <> '') then begin
                    PaymentToleranceManagement.DelPmtTolApllnDocNo(GenJournalLine, xRec."Applies-To Doc. No.");

                    case "Account Type" of
                        "Account Type"::Customer:
                            begin
                                CustLedgEntry.SetCurrentKey("Document No.");
                                CustLedgEntry.SetRange("Document No.", xRec."Applies-To Doc. No.");
                                if not (xRec."Applies-To Doc. Type" = "Gen. Document Type"::" ") then
                                    CustLedgEntry.SetRange("Document Type", xRec."Applies-To Doc. Type");
                                CustLedgEntry.SetRange("Customer No.", "Account No.");
                                CustLedgEntry.SetRange(Open, true);
                                if CustLedgEntry.FindFirst() then
                                    if CustLedgEntry."Amount to Apply" <> 0 then begin
                                        CustLedgEntry."Amount to Apply" := 0;
                                        Codeunit.Run(Codeunit::"Cust. Entry-Edit", CustLedgEntry);
                                    end;
                            end;
                        "Account Type"::Vendor:
                            begin
                                VendorLedgEntry.SetCurrentKey("Document No.");
                                VendorLedgEntry.SetRange("Document No.", xRec."Applies-To Doc. No.");
                                if not (xRec."Applies-To Doc. Type" = "Gen. Document Type"::" ") then
                                    VendorLedgEntry.SetRange("Document Type", xRec."Applies-To Doc. Type");
                                VendorLedgEntry.SetRange("Vendor No.", "Account No.");
                                VendorLedgEntry.SetRange(Open, true);
                                if VendorLedgEntry.FindFirst() then
                                    if VendorLedgEntry."Amount to Apply" <> 0 then begin
                                        VendorLedgEntry."Amount to Apply" := 0;
                                        Codeunit.Run(Codeunit::"Vend. Entry-Edit", VendorLedgEntry);
                                    end;
                            end;
                        "Account Type"::Employee:
                            begin
                                EmployeeLedgEntry.SetCurrentKey("Document No.");
                                EmployeeLedgEntry.SetRange("Document No.", xRec."Applies-To Doc. No.");
                                if not (xRec."Applies-To Doc. Type" = "Gen. Document Type"::" ") then
                                    EmployeeLedgEntry.SetRange("Document Type", xRec."Applies-To Doc. Type");
                                EmployeeLedgEntry.SetRange("Employee No.", "Account No.");
                                EmployeeLedgEntry.SetRange(Open, true);
                                if EmployeeLedgEntry.FindFirst() then
                                    if EmployeeLedgEntry."Amount to Apply" <> 0 then begin
                                        EmployeeLedgEntry."Amount to Apply" := 0;
                                        Codeunit.Run(Codeunit::"Empl. Entry-Edit", EmployeeLedgEntry);
                                    end;
                            end;
                    end;
                end;

                if (Amount = 0) and ("Applies-To Doc. No." <> '') then begin
                    TestField("Currency Code", GenJournalLine."Currency Code");
                    Validate("Account No.", GenJournalLine."Account No.");

                    case "Account Type" of
                        "Account Type"::Customer:
                            ///GenJournalLine.Validate(Amount, GetAmtToApplyCust(CustLedgEntry, GenJournalLine));
                            GenJournalLine.Validate(Amount, GetAmtToApplyCust(GenJournalLine));
                        "Account Type"::Vendor:
                            GenJournalLine.Validate(Amount, GetAmtToApplyVend(GenJournalLine));
                        "Account Type"::Employee:
                            GenJournalLine.Validate(Amount, GetAmtToApplyEmpl(GenJournalLine));
                    end;
                    **// New Event >>
                    OnValidateAppliesToDocNoOnBeforeValidateAmount(Rec, GenJournalLine, IsHandled);
                    if not IsHandled then
                        // New Event <<**
                    Validate(Amount, SignAmount() * GenJournalLine.Amount);
                    "Applies-To Doc. Type" := GenJournalLine."Applies-to Doc. Type";
                    "Applies-To Doc. No." := GenJournalLine."Applies-to Doc. No.";
                    "Applies-to ID" := GenJournalLine."Applies-to ID";
                    OnValidateAppliesToDocNoOnAfterFillAppliesToDocNo(Rec, GenJournalLine);
                end;

                if ("Applies-To Doc. No." <> xRec."Applies-To Doc. No.") and (Amount <> 0) then begin
                    if xRec."Applies-To Doc. No." <> '' then
                        PaymentToleranceManagement.DelPmtTolApllnDocNo(GenJournalLine, xRec."Applies-To Doc. No.");
                    PaymentToleranceManagement.PmtTolGenJnl(GenJournalLine);
                end;
            end;

3) procedure UpdateDocumentType()

          procedure UpdateDocumentType()
          begin
              "Gen. Document Type" := "Gen. Document Type"::" ";
              if not ("Account Type" in ["Account Type"::Customer, "Account Type"::Vendor]) then
                  exit;
              if (("Document Type" = "Document Type"::Receipt) and ("Account Type" = "Account Type"::Customer)) or
                 (("Document Type" = "Document Type"::Withdrawal) and ("Account Type" = "Account Type"::Vendor))
              then
                  "Gen. Document Type" := "Gen. Document Type"::Payment;
              if (("Document Type" = "Document Type"::Withdrawal) and ("Account Type" = "Account Type"::Customer)) or
                 (("Document Type" = "Document Type"::Receipt) and ("Account Type" = "Account Type"::Vendor))
              then
                  "Gen. Document Type" := "Gen. Document Type"::Refund;
      
              **// New Event >>    
              OnAfterUpdateDocumentType(Rec);
              // New Event <<**
          end;

4) procedure SignAmount(): Integer

              procedure SignAmount(): Integer
              **// New Event >>
              var
                  IsHandled: Boolean;
                  Result: Integer;
              // New Event <<**
              begin
                  **// New Event >>
                  OnBeforeSignAmount(Rec, Result, IsHandled);
                  if IsHandled then
                      exit(Result);
                  // New Event <<**
          
                  if "Document Type" = "Document Type"::Receipt then
                      exit(-1);
                  exit(1);
              end;

Events definitions:

          [IntegrationEvent(false, false)]
          local procedure OnBeforeSignAmount(var CashDocumentLineCZP: Record "Cash Document Line CZP"; var Result: Integer; var IsHandled: Boolean)
          begin
          end;

          [IntegrationEvent(false, false)]
          local procedure OnAfterUpdateDocumentType(var CashDocumentLineCZP: Record "Cash Document Line CZP")
          begin
          end;

          [IntegrationEvent(false, false)]
          local procedure OnValidateAppliesToDocNoOnBeforeValidateAmount(var CashDocumentLineCZP: Record "Cash Document Line CZP"; var GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
          begin
          end;

          [IntegrationEvent(false, false)]
          local procedure OnLookupAppliesToDocNoOnBeforeValidateAmount(var CashDocumentLineCZP: Record "Cash Document Line CZP"; var GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
          begin
          end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12746.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 60981.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 12819.
