### ISSUE TITLE
[Event Request] OnAfterTransferBom in Codeunit 99000773

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#2477]
We need a new Event "OnAfterTransferBOM" in Codeunit 99000773 in Function TransferBom with the same parameters as in Publisher OnBeforeTransferBOM to handle ISV Code.

![image](https://user-images.githubusercontent.com/40287548/57849107-c698f680-77da-11e9-97aa-df831e38aafd.png)

Thanks

**Comment by AlexanderYakunin** [comment]
Why do you need IsHandled here?

**Comment by AndreBreitenbach** [comment]
Sorry, i just copied "OnBeforeTransferBom" and missed to delete "IsHandled".
We don't need Handled-Pattern here!
