### ISSUE TITLE
[Event Request] - New event "OnBeforeOnRun" inside codeunit 248 "VAT Lookup Ext. Data Hndl" 

### ISSUE THREAD

**Issue by oldmat** [microsoft/ALAppExtensions#24771]
Hello, please consider adding the following event to codeunit 248 "VAT Lookup Ext. Data Hndl":

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnRun(var VATRegistrationLog: Record "VAT Registration Log"; var IsHandled: Boolean)
    begin
    end;

```
and call it accordingly inside the "OnRun" procedure:

```
    trigger OnRun()
    var
        **IsHandled: Boolean;**
    begin
        VATRegistrationLog := Rec;

        **IsHandled := false;
        OnBeforeOnRun(VATRegistrationLog, IsHandled);
        if not IsHandled then**

            LookupVatRegistrationFromWebService(true);

        OnRunOnAfterLookupVatRegistrationFromWebService(VATRegistrationLog, Rec);

        Rec := VATRegistrationLog;
    end;

```
so that we can completely customize the VAT ID check procedure.

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12553.
