### ISSUE TITLE
Remove the local access modifier for a procedure

### ISSUE THREAD

**Issue by FadiAleid** [microsoft/ALAppExtensions#24782]
Hi
Can you please remove the local access modifier from procedure AssignPurchItemCharge in codeunit 5807 "Item Charge Assgnt. (Sales)"?

// >>>>>>>>>>
    local procedure AssignSalesItemCharge(var ItemChargeAssignmentSales: Record "Item Charge Assignment (Sales)"; ItemChargeAssignmentSales2: Record "Item Charge Assignment (Sales)"; Currency: Record Currency; var QtyRemaining: Decimal; var AmountRemaining: Decimal)
    begin
        ItemChargeAssignmentSales.Get(
          ItemChargeAssignmentSales2."Document Type",
          ItemChargeAssignmentSales2."Document No.",
          ItemChargeAssignmentSales2."Document Line No.",
          ItemChargeAssignmentSales2."Line No.");
        ItemChargeAssignmentSales."Qty. to Assign" :=
          Round(ItemChargeAssignmentSales2."Qty. to Assign", UOMMgt.QtyRndPrecision());
        ItemChargeAssignmentSales."Amount to Assign" :=
          ItemChargeAssignmentSales."Qty. to Assign" * ItemChargeAssignmentSales."Unit Cost" + AmountRemaining;
        AmountRemaining := ItemChargeAssignmentSales."Amount to Assign" -
          Round(ItemChargeAssignmentSales."Amount to Assign", Currency."Amount Rounding Precision");
        QtyRemaining := ItemChargeAssignmentSales2."Qty. to Assign" - ItemChargeAssignmentSales."Qty. to Assign";
        ItemChargeAssignmentSales."Amount to Assign" :=
          Round(ItemChargeAssignmentSales."Amount to Assign", Currency."Amount Rounding Precision");
        ItemChargeAssignmentSales."Qty. to Handle" := ItemChargeAssignmentSales."Qty. to Assign";
        ItemChargeAssignmentSales."Amount to Handle" := ItemChargeAssignmentSales."Amount to Assign";
        ItemChargeAssignmentSales.Modify();
    end;
// <<<<<<<<<<

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
