### ISSUE TITLE
[EVENT REQUEST]  Codeunit 99000815 "Reservation-Check Date Confl." - OnSalesLineCheckOnBeforeIssueError - new parameter

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#24780]
Hi there. Could you please add parameter ForceRequest to publisher OnSalesLineCheckOnBeforeIssueError to CU 99000815 "Reservation-Check Date Confl."?

New code:

```al

        IsHandled := false;
//NEW PARAMETER CODE BEGIN
        OnSalesLineCheckOnBeforeIssueError(ReservEntry, SalesLine, ForceRequest, IsHandled);
//NEW PARAMETER CODE END
        if not IsHandled then
            if DateConflict(SalesLine."Shipment Date", ForceRequest, ReservEntry) then
                if ForceRequest then
                    IssueError(SalesLine."Shipment Date");
```

```al
    [IntegrationEvent(false, false)]
    local procedure OnSalesLineCheckOnBeforeIssueError(ReservationEntry: Record "Reservation Entry"; SalesLine: Record "Sales Line"; var ForceRequest: Boolean; var IsHandled: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12615.
