### ISSUE TITLE
[Event Request] Codeunit 231 "Gen. Jnl.-Post" - OnAfterOnRun

### ISSUE THREAD

**Issue by iamcgomes** [microsoft/ALAppExtensions#24791]
Could you please add the following **OnAfterOnRun** event to trigger **OnRun** in **Codeunit 231 "Gen. Jnl.-Post"**?

Current
```AL
trigger OnRun()
var
    GenJnlLine: Record "Gen. Journal Line";
begin
    GenJnlLine.Copy(Rec);
    Code(GenJnlLine);
    Copy(GenJnlLine);
end;
```

Requested
```AL
trigger OnRun()
var
    GenJnlLine: Record "Gen. Journal Line";
begin
    GenJnlLine.Copy(Rec);
    Code(GenJnlLine);
    Copy(GenJnlLine);
    OnAfterOnRun(Rec); //New
end;
```
```AL
//> New 
[IntegrationEvent(false, false)]
local procedure OnAfterOnRun(var GenJournalLine: Record "Gen. Journal Line")
begin
end;
//< New 
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12553.
