### ISSUE TITLE
[Event Request] codeunit 7017 "Price List Management" - OnBeforeImplementNewPrices

### ISSUE THREAD

**Issue by ZepposBE** [microsoft/ALAppExtensions#24790]
**🕮 Describe the request**

We would like to be able to skip certain PriceWorksheetLine(s) as they will be implemented by another procedure.

```
procedure ImplementNewPrices(var PriceWorksheetLine: Record "Price Worksheet Line")
    var
        PriceListLine: Record "Price List Line";
        InsertedUpdatedLeft: array[3] of Integer;
    begin
        PriceWorksheetLine.SetFilter("Price List Code", '<>%1', '');
        OnBeforeImplementNewPrices(PriceWorksheetLine);
        if PriceWorksheetLine.FindSet(true) then begin
            repeat
                if not PriceWorksheetLine.TryVerify() then
                    InsertedUpdatedLeft[3] += 1
                else
                    if not ImplementNewPrice(PriceWorksheetLine, PriceListLine, InsertedUpdatedLeft) then
                        InsertedUpdatedLeft[3] += 1;
            until PriceWorksheetLine.Next() = 0;
            SendNotificationNewPriceImplementation(InsertedUpdatedLeft);
            if InsertedUpdatedLeft[1] + InsertedUpdatedLeft[2] > 0 then begin
                Commit();
                PriceListLine.MarkedOnly(true);
                ActivateDraftLines(PriceListLine);
            end;
        end;
    end;
```

```
[IntegrationEvent(false, false)]
    local procedure OnBeforeImplementNewPrices(var PriceWorksheetLine: Record "Price Worksheet Line")
    begin
    end;
```

**Additional context**

For now, we have no 100% working method to filter lines that will be implemented.

example: On the page "`Price Worksheet`", the action "` ImplementPriceChange`" does a `PriceWorksheetLine.Reset();` in case of only 1 selected line, to then continue with the implementation of all similar lines.
The new event would allow us to set extra filters for specific cases where lines would be implemented by other functionalities.

Also requesting a new event to allow skipping specific records when required.
Link to other request: [[Event Parameter Request] codeunit 7017 "Price List Management" - OnBeforeImplementNewPrice ](https://github.com/microsoft/ALAppExtensions/issues/24789)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12615.
