### ISSUE TITLE
Integration Product Event OnBeforeFindMapping does not work with Item Variants

### ISSUE THREAD

**Issue by bradlenahan** [microsoft/ALAppExtensions#24793]
In the Shopify Connector, Integration Event OnBeforeFindMapping in codeunit 30177 "Shpfy Product Events" does not pass the ItemVariant record by reference, so the calling mapping function(s) do not receive the mapped variant when this event is handled and an Item Variant is found. As a result, the Shopify Variant does not get mapped properly.

To support mapping Item Variants, the function signature should be changed from this:

`OnBeforeFindMapping(Direction: enum "Shpfy Mapping Direction"; var ShopifyProduct: Record "Shpfy Product"; var ShopifyVariant: Record "Shpfy Variant"; var Item: Record Item; ItemVariant: Record "Item Variant"; var Handled: Boolean);`

To this (add var keyword before ItemVariant variable to pass by reference):

`OnBeforeFindMapping(Direction: enum "Shpfy Mapping Direction"; var ShopifyProduct: Record "Shpfy Product"; var ShopifyVariant: Record "Shpfy Variant"; var Item: Record Item; var ItemVariant: Record "Item Variant"; var Handled: Boolean);`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12545.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 12571.
