### ISSUE TITLE
Field "Responsibility Center Code" missing on page "Company Information" Business Central

### ISSUE THREAD

**Issue by malue19** [Microsoft/ALAppExtensions#248]
Hey guys, I have a question about the Responsibility Center Code: from Standard NAV 2018 I know that I have on the card "Company Information" a field, which is called "Responsibility Center Code". In Business Center that field is missing...now I would like to know, why it is not there and how could I solve this problem? I already tried to personalize the page with the In-Client-Designer, but it does not show me any fields...

I thought it is standard...

Do I have to create an extension?

**Comment by JesperSchulz** [comment]
It was a wrong Application Area tag. The issue has been resolved. Thanks for reporting!
