### ISSUE TITLE
[Application Bug / Translation] 'Bacth' typo in codeunit 1372 "Purchase Batch Post Mgt."

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#24804]
![image](https://github.com/microsoft/ALAppExtensions/assets/25268332/30f1aadd-c8e4-419c-a478-d8f7be5f05bc)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12377.
