### ISSUE TITLE
[BUG] codeunit 1303 "Correct Posted Sales Invoice", function TestIfInvoiceIsPaid

### ISSUE THREAD

**Issue by aries-ts-indo** [microsoft/ALAppExtensions#24802]
**🕮 Describe the issue**

Cancelling an Open (not partially or fully paid) Posted Sales Invoice in AU Localization with WHT Posting Setup "WHT Realized Type" set to "Invoice" always fails.

**🔧 To Reproduce**

1. Use AU Localization, with one or more item uses WHT Posting Setup (from combination of WHT Bus. Group and WHT Prod. Group) where "WHT Realized Type" set to "Invoice" and "WHT %" is >0
2. Create a Sales Order/Sales Invoice with lines from step no. 1, then post Ship + Invoice
3. Open the Posted Sales Invoice created from step no. 2
4. Click the Cancel button from Correct menu on Posted Sales Invoice
![image](https://github.com/microsoft/ALAppExtensions/assets/130949813/2c656dca-6fb7-4b9d-b7da-7593282d369c)
5. Error will always appears even though Posted Sales Invoice has never been settled/paid partially nor fully

**📣 Expected behaviour**

When the Posted Sales Invoice has not yet been neither partially nor fully paid, the Cancel button will successfully create the Sales Credit Memo and then Post it automatically.

**Additional context**

The issue originated from function TestIfInvoiceIsPaid in codeunit 1303 "Correct Posted Sales Invoice"

It uses this code snippet:
``` 
SalesInvoiceHeader.CalcFields("Amount Including VAT");
SalesInvoiceHeader.CalcFields("Remaining Amount");
  if SalesInvoiceHeader."Amount Including VAT" <> SalesInvoiceHeader."Remaining Amount" then
      ErrorHelperHeader("Correct Sales Inv. Error Type"::IsPaid, SalesInvoiceHeader);
```

which it always yields difference when WHT is posted on invoice.

Suggested code is using amount and "remaining amount" from customer ledger entry instead:

``` 
  custLedgEntry.Reset();
  custLedgEntry.SetCurrentKey("Entry No.", "Document Type", "Document No.");
  custLedgEntry.SetRange("Document Type", custLedgEntry."Document Type"::Invoice);
  custLedgEntry.SetRange("Document No.", SalesInvoiceHeader."No.");
  if not custLedgEntry.FindFirst() then
      Error(ErrorCannotFindCustLedger, SalesInvoiceHeader."No.");

  custLedgEntry.CalcFields(Amount, "Remaining Amount");
  if custLedgEntry.Amount <> custLedgEntry."Remaining Amount" then
    Error(PostedInvoiceIsPaidCancelErr);
```

Which always calculate the correct difference if there's any partial or full payment on the invoice.

**Comment by AlexanderYakunin** [comment]
We are not fixing bugs, but delivering extensibility related requests. It can be fixed if you move this request to support ticket.
