### ISSUE TITLE
[Event Request] OnCallItemTrackingOnBeforeItemTrackingLinesRunModal missing in "Prod. Order Comp.-Reserve"

### ISSUE THREAD

**Issue by shadow747** [microsoft/ALAppExtensions#24800]
"Prod. Order Comp.-Reserve" codeunit is missing OnCallItemTrackingOnBeforeItemTrackingLinesRunModal publisher in function CallItemTracking just before calling ItemTrackingLines.RunModal(); but is present is other codeunits handling item tracking.

example screenshot of assembly line having the publisher :

<img width="512" alt="AssemblyLineItemTracking" src="https://github.com/microsoft/ALAppExtensions/assets/38912958/3b5cb12b-7c13-44d6-83d1-8d449f85a388">

screenshot of prod. order component missing the publisher:

<img width="565" alt="ProdOrderComponentItemTracking" src="https://github.com/microsoft/ALAppExtensions/assets/38912958/1f921150-1825-413b-b08e-821f86bf0b6c">

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12553.
