### ISSUE TITLE
[Protect variables request] report 99000756 "Detailed Calculation"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#24812]
We would like to have access to the following values in a report extension:

CompItem: Record Item;
ProdBOMLine: array[99] of Record "Production BOM Line";
PBOMNoList: array[99] of Code[20];
PBOMVersionCode: array[99] of Code[20];
Quantity: array[99] of Decimal;

CalculateDate: Date;
Level, NextLevel: Integer;
CostTime, ProdUnitCost, ProdTotalCost, FooterCostTotal,FooterProdTotalCost,  CompItemQtyBase, CostTotal, SingleLevelMfgOvhd: Decimal

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
