### ISSUE TITLE
Request to add the ApplicationArea property to page 5096 "Task List"

### ISSUE THREAD

**Issue by DonHendriksen** [microsoft/ALAppExtensions#24811]
Hi,
In #22005 we requested to add the UsageCategory because we want the page Task List to found by the search (Alt+Q) functionality. This Github request is resolved, but the page can still not be found because the ApplicationArea is missing.
Additional request to implement the following property to page 5096 "Task List":
_ApplicationArea = Basic, Suite;_
The caption of the page will get the value 'untitled' when the page is opened via search (tested locally). Maybe check this as well if there can be added a different, more meaningful caption.
Thanks in advance.
Regards, Don

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12340.
