### ISSUE TITLE
[Event Request] Add new event to apply filters on Approval Entry Record and Workflow Step Instance Record before Send Approval and Cancel approval for General Journal batch. 

### ISSUE THREAD

**Issue by arvindbinarystream** [microsoft/ALAppExtensions#24817]
Hi team, 

There is a new feature that I am working on for approvals based on General Journal batch.
In order to make our functionality work we will need additional events to apply filters on Approval Entry and Workflow Step Instance Records.

New Event Will be
1) **codeunit 1501 "Workflow Management"**

![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/ed8cf551-2f41-45fa-8543-271ecb00ad56)

- Event signature will be:-
- [IntegrationEvent(false, false)]
- local procedure OnFindWorkflowStepInstanceWithOptionalWorkflowStartOnAfterSetWorkflowStepInstanceLoopFilters(RecRef: RecordRef; var WorkflowStepInstanceLoop: Record "Workflow Step Instance"; FunctionName: Code[128]; StartWorkflow: Boolean)
- begin
- end;

2) **codeunit 1535 "Approvals Mgmt."**

1. 
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/f73349e3-e88d-49e2-a8ef-59e360228634)

- Event signature will be:-
- [IntegrationEvent(false, false)]
- local procedure OnHasOpenApprovalEntriesForCurrentUserOnAfterSetApprovalEntryFilters(var ApprovalEntry: Record "Approval Entry")
- begin
- end;

2. 
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/bffe233a-e4fb-435c-a30e-90710e23bebf)

- Event signature will be:-
- [IntegrationEvent(false, false)]
- local procedure OnAfterApproveSelectedApprovalRequest(var ApprovalEntry: Record "Approval Entry")
- begin
- end;

3. 
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/7593d16f-9b00-4b8d-aed1-593c8f9c80d1)

- Event signature will be:-
- [IntegrationEvent(false, false)]
- local procedure OnBeforeRejectSelectedApprovalRequest(var ApprovalEntry: Record "Approval Entry")
- begin
- end;

4. 
- ![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/4330d07f-5b0f-4036-9f54-acd441c457a6)

- Event signature will be:-
- [IntegrationEvent(false, false)]
- local procedure OnAfterDelegateSelectedApprovalRequest(var ApprovalEntry: Record "Approval Entry")
- begin
- end;

3) table 232 "Gen. Journal Batch"
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/9e38170e-0730-4302-8a41-b649fa217273)

- Event signature will be:-

- [IntegrationEvent(false, false)]
- local procedure OnGetBalanceOnAfterSetGenJournalLineFilters(var GenJournalLine: Record "Gen. Journal Line")
- begin
- end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12576.
