### ISSUE TITLE
[Event Requests] report 7000083 "Redraw Payable Bills"  DataItem VendorLedgerEntry - OnAfterGetRecord

### ISSUE THREAD

**Issue by operrui** [microsoft/ALAppExtensions#24826]
Hi Team,
In report 7000083 "Redraw Payable Bills",  could be included an integration event, in the OnAfterGetRecord trigger of the VendorLedgerEntry dataitem.  We need to apply another type of validation for the new expiration date.

The change would be as follows:

![image](https://github.com/microsoft/ALAppExtensions/assets/38982763/e92ba424-9e3a-4d8e-840a-b7b763242f92)

![image](https://github.com/microsoft/ALAppExtensions/assets/38982763/da5831fb-f9a6-4124-8907-a4ca47c1a57a)

Thank you in advance.
Best regards.

```[tasklist]
### Tasks
```

**Comment by operrui** [comment]
Sorry, I missed to include the NewDueDate field in the subscriber.

![image](https://github.com/microsoft/ALAppExtensions/assets/38982763/3c98fdd0-ddcf-494e-8782-ef2105f2e60d)

![image](https://github.com/microsoft/ALAppExtensions/assets/38982763/9327e60b-948a-491f-b5a4-2d9978b795b5)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12553.
