### ISSUE TITLE
New event in Stat. Acc. Jnl. Line Post codeunit

### ISSUE THREAD

**Issue by JeppeBylov** [microsoft/ALAppExtensions#24828]
**🕮 Describe the request**

Enable ability to set values of new fields on the Statistical Ledger Entry during posting.

**Additional context**

Trying to extend the Statistical Account module with some coupling with G/L, Purchasing and sales. As such i'm adding a couple of new fields to the Stat. Acc. Ledger Entry table. However i have no event to subscribe to, to populate the fields during posting, before insert.

![image](https://github.com/microsoft/ALAppExtensions/assets/968411/b1df5941-f7b7-4daf-b4be-5bd5049cd054)

**Comment by nikolakukrika** [comment]
Hi Jeppe,

I have implemented the event, but I have named it OnBeforeInsertStatisticalLedgerEntry. The name TransferTo is not good for a public event, also this event is just before insert. Let me know if this will work with you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12656.
