### ISSUE TITLE
[Event Requests] page 9252 "MyDim Value Combinations" - OnAfterLoad() , OnBeforeGenerateColumnCaptions()

### ISSUE THREAD

**Issue by ShaikAbdulRasheed** [microsoft/ALAppExtensions#24824]
Hi Team, 

In page 9252 "MyDim Value Combinations", Please provide  the possibility to have two integration events, OnAfterLoad() and OnBeforeGenerateColumnCaptions() events in Load() and GenerateColumnCaptions() procedures respectivly.

In Load() Procedure after 149 Line in Below image, 

![image](https://github.com/microsoft/ALAppExtensions/assets/110883968/9559f60f-42f5-48fd-b426-7f6c95a524c9)

![image](https://github.com/microsoft/ALAppExtensions/assets/110883968/35dccb32-0436-421e-93f4-8f549855e68a)

Event:
[IntegrationEvent]
local procedure OnAfterLoad(Var MatrixRecord: Record "Dimension Value";_Row: Code[20]; _Column: Code[20]; _ShowColumnName: Boolean)

In procedure GenerateColumnCaptions() after 156 line in below image,

![image](https://github.com/microsoft/ALAppExtensions/assets/110883968/57fd65ee-83a2-460d-a6a9-a34c32d4cee7)
![image](https://github.com/microsoft/ALAppExtensions/assets/110883968/1a23cdad-d26a-44b9-bc75-0df1289fc5ef)

Event:
[IntegrationEvent]
    local procedure OnBeforeGenerateColumnCaptions(Var MatrixRecord: Record "Dimension Value";StepType: Enum "Matrix Page Step Type")

**Comment by ShaikAbdulRasheed** [comment]
Hi Team, 

Do you have any update on the above request?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12553.
