### ISSUE TITLE
[Event Requests] codeunit "VAT Entry - Edit" - OnAfterVATEntryModify

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#24829]
Please add a new event to `codeunit "VAT Entry - Edit"`:
```al
  trigger OnRun()
  begin
        ...
	VATEntry.Modify();
+	OnAfterVATEntryModify(VATEntry, Rec);
	Rec := VATEntry;
  end;

+ [IntegrationEvent(false, false)]
+ local procedure OnAfterVATEntryModify(var VATEntry: Record "VAT Entry"; FromVATEntry: Record "VAT Entry")
+ begin
+ end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12553.
