### ISSUE TITLE
[Event Enum Issue] report 1308 "Standard Sales - Shipment"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#24827]
When updating an integer value for a readable enum parameter a copypaste bug was created in a previous release:

    local procedure InitLogInteraction()
    begin
        LogInteraction := SegManagement.FindInteractionTemplateCode("Interaction Log Entry Document Type"::"Sales Inv.") <> '';
    end;

should be

    local procedure InitLogInteraction()
    begin
        LogInteraction := SegManagement.FindInteractionTemplateCode("Interaction Log Entry Document Type"::"Sales Shpt. Note") <> '';
    end;

P.S. While we are at it:
Replace all occurrences of 
    SegManagement.LogDocument(<IntegerValue>,
with
    SegManagement.LogDocument(<EnumValue>,

**Comment by pri-kise** [comment]
@Duizy1971 i already fixed this via the BaseApp Pilot.
https://github.com/microsoft/ALAppExtensions/issues/24036
@JesperSchulz this issue can be closed

**Comment by JesperSchulz** [comment]
Awesome. Closing issue.
