### ISSUE TITLE
COD951 Time Sheet Approval Management, OnBeforeReject

### ISSUE THREAD

**Issue by ElmarFV** [microsoft/ALAppExtensions#24837]
Can we please have OnBeforeReject in the following way

`   procedure Reject(var TimeSheetLine: Record "Time Sheet Line")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeReject(TimeSheetLine, IsHandled);
        if IsHandled then
            exit;
`

Publisher:

`    [IntegrationEvent(false, false)]
    local procedure OnBeforeReject(var TimeSheetLine: Record "Time Sheet Line"; var IsHandled: Boolean)
    begin
    end;
`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12553.
