### ISSUE TITLE
[Enum Request] table 5901 "Service Item Line" - field 130 "Release Status"

### ISSUE THREAD

**Issue by alapenas** [microsoft/ALAppExtensions#24836]
Hello,

The ticket was already created for the missing Enum #22481 and approved, but the change is missing for table "Service Item Line" in the pre-release version 23.0.12034.12365 W1.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13983.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 13998.
