### ISSUE TITLE
[Event Request] table 83 "Item Journal Line" - OnBeforeCheckItemTracking (bug; missing var)

### ISSUE THREAD

**Issue by tg-navcom** [microsoft/ALAppExtensions#24839]
Related to #23784
Please add `var` to `IsHandled` in event `OnBeforeCheckItemTracking`:

```al
    [IntegrationEvent(false, false)]
-   local procedure OnBeforeCheckItemTracking(var ItemJournalLine: Record "Item Journal Line"; IsHandled: Boolean)
+   local procedure OnBeforeCheckItemTracking(var ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean)
    begin
    end;
```

Currently, the method call does not work properly.
However, no changes are required here:
```al
    local procedure CheckItemTracking(CalledByFieldNo: Integer)
    var
        FieldCap: Text;
        IsHandled: Boolean;
    begin
        OnBeforeCheckItemTracking(Rec, IsHandled);
        if IsHandled then
            exit;

        if not IsItemTrackingEnabledInBatch() then begin
            ClearTracking();
            ClearDates();
            exit;
        end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12553.
