### ISSUE TITLE
Allow adding all Tests from an App in AL Test Tool

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/ALAppExtensions#24845]
**🕮 Describe the issue**

Often partners want to run all tests of a specific app.
To add all relevant tests to a test suite, the user must either know the number range of the app (by heart) or filter the object list by prefix, which is not comfortable either.

It would be much easier to have a 'Get Test by App' action besides the 'Get Test Codeunits' and 'Get Test Codeunits by Range' Action.

**🔧 To Reproduce**

1. Go to 'AL Test Tool'
2. Add Tests

**📣 Expected behavior**

An Action in AL Test Tool to add all tests from an selected app.

**Comment by pri-kise** [comment]
@ChrisBlankDe if you're planning to add this action by yourself, then please update your issue with this information.
Then maybe @JesperSchulz can approve this issue that you add a PR with this fix.

**Comment by AlexanderYakunin** [comment]
Sorry, we are doing extensibility related changes and cannot help you with implementation of this idea. Please move this to aka.ms/bcideas to get it moving.

**Comment by ChrisBlankDe** [comment]
I hope it is seen there
https://experience.dynamics.com/ideas/idea/?ideaid=8a817894-ad62-ee11-a81c-6045bd86696b
