### ISSUE TITLE
General Journal batch posting locking out all users during delete journal deleteall

### ISSUE THREAD

**Issue by dmachanick** [microsoft/ALAppExtensions#24848]
**🕮 Describe the issue**

Posting a journal batch takes about 5% of the total time. This is because deletes are extremely slow (known SQL Server issue).
My solution is to separate the posting of the journals from the deletion after posting of the journals.
To do this, I would update a new flag on the journal batch when the journals have posted.
Then execute a separate routine that deletes all the journals which will result in the Ledger tables not being locked. This will avoid the lockouts that occur when users post a very large journal batch.
Recently had the problem where a user posted 47,000 journal lines and locked the system for over 2 hours.
By separating the posting (using an event), then deleting the journals in a separate process, I reduced the lockout to only about 5 minutes.

**🔧 To Reproduce**

1. Creaate a large G/L Journal batch (at least 10,000 lines).
2. Click the post.
3. The post will show 100% complete, then take much longer to finish (this is the Deleteall statement when it deletes the posted journal lines.)
4. No error - just very, very slow.

**📣 Expected behavior**

**Screenshots**

**Additional context**

**Comment by AlexanderYakunin** [comment]
This is probably good idea, but we cannot process it here. Should you create this idea on aka.ms/bcideas, it will be processed for the scope of next release.
