### ISSUE TITLE
System module for ClosedXML

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/ALAppExtensions#24849]
**🕮 Describe the issue**

I have a module that users Azure Function to create excel document using the ClosedXML dll.  I would like to move this functionality inside the System App but that required that I can have direct access (onPrem) to the ClosedXML dll in the system app.

**🔧 To Reproduce**

ClosedXML is available un GitHub: https://github.com/ClosedXML/ClosedXML

**Comment by pri-kise** [comment]
There have been some issues when I asked to use another DLL that was licensed by Apache and not by MIT.
https://github.com/microsoft/ALAppExtensions/discussions/20136

But your mentioned DLL seems to be licensed by MIT, therefore this might be possible.
Could you maybe outline what isn't possible via the excelbuffer (and the used DLLs there) and what will be added by this PR?
Then microsoft can decide better on this topic.
Adding @JesperSchulz  on this issue to forward this to the right people.

**Comment by gunnargestsson** [comment]
Short list:

- Alignment functions
- Border functions
- Color functions
- Fill functions
- Format functions
- Font functions

for Cells and Ranges

Page Setup functions

- Page Order
- Page Orientation
- Paper Size
- Footers
- Headers
- Freeze Row/Column
- Page Breaks
- Page Scaling
- Page Margins

**Comment by gunnargestsson** [comment]
This will not replace the Excel buffer.  
Excel sheets can be created both with Excel buffers and Excel Data Set from reports and then formatted by this module.

**Comment by JesperSchulz** [comment]
I will investigate if the ClosedXML project is trusted and can be used.

**Comment by gunnargestsson** [comment]
> There have been some issues when I asked to use another DLL that was licensed by Apache and not by MIT. #20136
> 
> But your mentioned DLL seems to be licensed by MIT, therefore this might be possible. Could you maybe outline what isn't possible via the excelbuffer (and the used DLLs there) and what will be added by this PR? Then microsoft can decide better on this topic. Adding @JesperSchulz on this issue to forward this to the right people.

Speaking about the Excel Buffer and the DLL used there.  It would help a lot of there is a function in that DLL that can save/print the Excel document as a PDF.  The combination of this module and Excel to PDF file would give us the possibility of creating a beautiful document and attach to emails.

**Comment by JesperSchulz** [comment]
Unfortunately we're currently not geared towards enabling the use of 3rd party assemblies for open source contributions :-( This will have to wait a little longer, until our processes have matured more.
