### ISSUE TITLE
Improve "Item avail by." extensibility - make calculated values protected

### ISSUE THREAD

**Issue by arudokvas** [microsoft/ALAppExtensions#24840]
Move variables to "protected var"
1) page 5417 "Item Avail. by UOM Lines":
```
    var
        ItemAvailFormsMgt: Codeunit "Item Availability Forms Mgt";

    protected var
        Item: Record Item;
        AmountType: Enum "Analysis Amount Type";
        PeriodStart: Date;
        PeriodEnd: Date;
        ExpectedInventory: Decimal;
        QtyAvailable: Decimal;
        PlannedOrderReleases: Decimal;
        GrossRequirement: Decimal;
        PlannedOrderRcpt: Decimal;
        ScheduledRcpt: Decimal;
        ProjAvailableBalance: Decimal;
```
2) page 5415 "Item Avail. by Variant Lines":
```
    var
        ItemAvailFormsMgt: Codeunit "Item Availability Forms Mgt";

    protected var
        Item: Record Item;
        AmountType: Enum "Analysis Amount Type";
        PeriodStart: Date;
        PeriodEnd: Date;
        ExpectedInventory: Decimal;
        QtyAvailable: Decimal;
        PlannedOrderReleases: Decimal;
        GrossRequirement: Decimal;
        PlannedOrderRcpt: Decimal;
        ScheduledRcpt: Decimal;
        ProjAvailableBalance: Decimal;
```

**Additional context**

I want to show values at my pageextension with different properties, for example, AutoFormatExpression. As workaround I can recalculate it again from my page extension. But probably not the best for performance.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12965.
