### ISSUE TITLE
ExtensibilityRequest Table 4812 "Intrastat Report Line" / procedure GetPartnerNo

### ISSUE THREAD

**Issue by RaKuNbg** [microsoft/ALAppExtensions#24841]
Could you please move the function GetPartnerNo to table 4810 "Intrastat Report Setup" and make scope global, so that it can be used from extensions.

In addition give the function two new parameters 
"CheckVATNoBasedOnMatch": Boolean 
VATNoBasedToCheck: Enum "Intrastat Report VAT No. Base"
then the function can also be used in the table extensions 4815 / 4816 / 4817 in the function UpdateIntrastatFields.

Last but not least the function should set a global Flag "SetupRead" (boolean) so that the setup is only once read if the function is called in a loop.

So in the end it should look like that:

    procedure GetPartnerNo(SellTo: Code[20]; BillTo: Code[20]; CheckVATNoBasedOnMatch: Boolean; VATNoBasedToCheck: Enum "Intrastat Report VAT No. Base") PartnerNo: Code[20]

    begin
        if not SetupRead then begin
            Get();
            SetupRead := true;
        end;
        if CheckVATNoBasedOnMatch and (VATNoBasedToCheck <> "VAT No. Based On") then
            exit('');

        case "VAT No. Based On" of
            "VAT No. Based On"::"Sell-to VAT":
                PartnerNo := SellTo;
            "VAT No. Based On"::"Bill-to VAT":
                PartnerNo := BillTo;
        end;
    end;    

    var
        SetupRead: Boolean;

Fixes [AB#484764](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/484764)

**Comment by JesperSchulz** [comment]
This will ship with 24.5 and 25.0.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 22964.
