### ISSUE TITLE
[Event Request] Page 256 "Payment Journal" - OnAfterSetControlAppearanceFromBatch

### ISSUE THREAD

**Issue by tgdoat44** [microsoft/ALAppExtensions#24859]
**🕮 Describe the request**

In Page 256 "Payment Journal", we requiere an OnAfter-trigger in the function SetControlAppearanceFromBatch:
![image](https://github.com/microsoft/ALAppExtensions/assets/72976203/b702d22e-625b-4010-a39d-f789ec3b2ff6)

```
[IntegrationEvent(true, false)]
local procedure OnAfterSetControlAppearanceFromBatch(var Rec: Record "Gen. Journal Line"; GenJournalBatch: Record "Gen. Journal Batch")
begin
end;
```

**Additional context**

We need to set additional variables.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12553.
