### ISSUE TITLE
VAT bypasses

### ISSUE THREAD

**Issue by DPAMHellemons** [microsoft/ALAppExtensions#2485]
At the moment the main problem concerns Non-Deductible VAT.
Currently the code is embedded in the standard code. This means that in every particular place where VAT is calculated, ND. VAT is also being calculated.
The following examples show the scenario.

Sample1: tab 36 – OnValidate from Filed Prices Including VAT

` IF NOT RecalculatePrice THEN BEGIN`
... 
VatFactor += SalesLine."ND %"  / 100;  //soft,n

--These recalculations on OnValidate fields.. would it be feasible by recreating the code on OnAfterValidate triggers?

Sample2: Cod 80 - Local Function DivideAmount

 LOCAL DivideAmount...
....
BEGIN 
 "VAT %" := TempVATAmountLine."VAT %"
"ND %" := TempVatAmountLine. "ND %";
...

Samples3: SumSalesLines2 function (also in Cod80)
DivideAmount...
BEGIN
TotalSalesLine."VAT %" := SalesLine."VAT %";
 TotalSalesLine."ND %" := SalesLine."ND %";

Note that there are 3 examples in this email but the whole scenario obliges us to make changes in about 200 different places.

What would be your suggestion for this cases?

**Comment by AlexanderYakunin** [comment]
Please describe you problem, I assume if you don't use ND VAT it will be zero. And let us know you country code please.

**Comment by DPAMHellemons** [comment]
Hi Alexander,

Thank you very much for your patience. I hope the detail I’m sending is enough. If not please let me know.

Regarding the Country Code it’s “PT” or is Microsoft looking for a specific code?

Regarding the detail, I’m sending a scenario that might help contextualize things.
The Goal of the functionality:
The ND VAT is a functionality that restricts the amount of VAT that can be deducted in the VAT statement

Setup:
Setup is done on the VAT Posting Setup where we can setup ND VAT %

Scenario:
Amount of invoice: 123 €
Base Amount= 100€
VAT% = 23
ND VAT% = 10%

In this scenario only 13% (23%-10%) is deductible so:

  *   VAT Entry
     *   VAT Entry Base Amount = 100€.
     *   VAT Entry Amount = 13€.
     *   VAT % = 13%
     *   ND VAT% = 10%
  *   G/L Entry
     *   G/L Amount regarding VAT = 13€
     *   G/L Amount regarding Purchase Account = 110€
     *   G/L Amount regarding Vendor = 123€.

For this to happen the code (which is legacy code from Microsoft itself from before NAV 2013) transfers this information to the temporary document Tables (Sales Line and Purchase Line) and during posting transfers this information to History Tables.

The possibilities to address this from a code perspective so far involves the following:

  *   Let MSFT Code Run and then force change data if needed to the desired output;
     *   Since the changes are located in more than 200 places it’s a crazy job for a small team;
     *   Also it’s not very pretty;
  *   Completely refactor the functionality;

We would like help in understanding if we really need to completely refactor the code or is there a way to do this adjusting some of the existing code.

We realize that the Code example we sent before was for the SalesLine part, but the truth is that it’s mainly used for the Purchases (The SalesLine code is legacy code that should have been removed).


Met vriendelijke groet | Best regards,​
​
Danny Hellemons

Schouw Informatisering B.V.
Bredaseweg 172
4872 LA
,
Etten‑Leur

+31 76 5042520<tel:+31765042520>
+31 6 36293689<tel:+31%206%2036293689>
www.schouw.nl<http://www.schouw.nl/>

Van: Alexander Yakunin <notifications@github.com>
Verzonden: vrijdag 17 mei 2019 08:49
Aan: microsoft/ALAppExtensions <ALAppExtensions@noreply.github.com>
CC: Danny Hellemons <dhellemons@schouw.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [microsoft/ALAppExtensions] VAT bypasses (#2485)


Please describe you problem, I assume if you don't use ND VAT it will be zero. And let us know you country code please.

**Comment by ikoletic** [comment]
This issue is a product suggestion already recorded and voted on [BC Ideas](https://experience.dynamics.com/ideas/idea/?ideaid=4647f6bd-2329-e911-9461-0003ff68daaf). Please add your votes/comments there.
