### ISSUE TITLE
[Event Request] Report 2000005 "File SEPA Payments" (BE)

### ISSUE THREAD

**Issue by FretDel** [microsoft/ALAppExtensions#24854]
Can we please get the event 'OnBeforePreReport' in Report 2000005 "File SEPA Payments" (localization BE) like the same event already there in Report 2000006 "File Non Euro SEPA Payments"   ?

![image](https://github.com/microsoft/ALAppExtensions/assets/136804189/82dd17e7-cd50-4b18-a8fa-fe93896aa873)

Thank you!

**Comment by FretDel** [comment]
I found in the histories that 2 Issues talk about this request but without having resolved them for Report 2000005.
#3772 and #15982

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12553.
