### ISSUE TITLE
[Event Change Request] Table 5870 BOM Buffer - Event OnAfterCalcUnitCost

### ISSUE THREAD

**Issue by StHillmann** [microsoft/ALAppExtensions#24853]
**🕮 Describe the request**

In order to allow changes to the BOMBuffer, the existing parameter "BOMBuffer" needs to be passed by reference.

Original:

```
[IntegrationEvent(false, false)]
local procedure OnAfterCalcUnitCost(BOMBuffer: Record "BOM Buffer")
begin
end;
```

Change:

```
[IntegrationEvent(false, false)]
local procedure OnAfterCalcUnitCost(var BOMBuffer: Record "BOM Buffer")
begin
end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12553.
