### ISSUE TITLE
[Event Parameter Request] Codeunit 99000832 - Sales Line-Reserve - OnTestSalesLineModificationOnBeforeTestVariantCode

### ISSUE THREAD

**Issue by UIBKH** [microsoft/ALAppExtensions#24867]
Dear Support,

We would need the ThrowError as parameter for the event OnTestSalesLineModificationOnBeforeTestVariantCode.

This is what we need:

- Original:
```
    [IntegrationEvent(false, false)]
    local procedure OnTestSalesLineModificationOnBeforeTestLocationCode(var NewSalesLine: Record "Sales Line"; var OldSalesLine: Record "Sales Line"; var IsHandled: Boolean; var HasError: Boolean)
    begin
    end;
```
- New:
```
    [IntegrationEvent(false, false)]
    local procedure OnTestSalesLineModificationOnBeforeTestLocationCode(var NewSalesLine: Record "Sales Line"; var OldSalesLine: Record "Sales Line"; var IsHandled: Boolean; var HasError: Boolean; ThrowError: Boolean)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12615.
