### ISSUE TITLE
Codeunit 706 Zip Stream Wrapper Encoding

### ISSUE THREAD

**Issue by amulaj** [microsoft/ALAppExtensions#24864]
The Zip Stream Wrapper Codeunit should be extended with a Encoding Parameter.
If the Zip content includes file names with special characters then you cant store the file name correctly.

To be able to use e specific codepage the OpenZipFromStream Function could look something like that:
variable gSystemTextEncoding = System.Text.Encoding.'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Code:
OpenZipFromStream(pInputStream : InStream;pZipArchiveModeIsUpdate : Boolean;pCodePageNumber : Integer)
CLEAR(gZipTempBlob);
gZipTempBlob.Blob.CREATEOUTSTREAM(OutputStream);
COPYSTREAM(OutputStream,pInputStream);

IF pZipArchiveModeIsUpdate THEN
gZipArchive := gZipArchive.ZipArchive(OutputStream,gZipArchiveMode.Update,FALSE,gSystemTextEncoding.GetEncoding(pCodePageNumber))
ELSE
gZipArchive := gZipArchive.ZipArchive(OutputStream,gZipArchiveMode.Read,FALSE,gSystemTextEncoding.GetEncoding(pCodePageNumber));

**Comment by JesperSchulz** [comment]
Unfortunately, this repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

For suggestions to the Business Central product group, please create a [BC Idea](https://aka.ms/bcideas).

If you want to log a support case, please visit:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
