### ISSUE TITLE
Handled Pattern codeunit 427 ICInboxOutboxMgt, procedure RejectAcceptedSalesHeader

### ISSUE THREAD

**Issue by frobiii** [microsoft/ALAppExtensions#24866]
Can you please add an handled pattern in codeunit 427 ICInboxOutboxMgt, procedure RejectAcceptedSalesHeader.

Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12576.
