### ISSUE TITLE
Missing namespace on table 823 Name/Value Buffer

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#24865]
on table 823 Name/Value Buffer there is no namespace

when developing extension with namespaces, vscode still compiles but when submutting this to appsource we get error that the table Name/Value buffer can not be found.

removing namespaces from the object where we are referencing the tables solves.
so the missing namespace seems to be the problem

**Comment by RadoArvay** [comment]
There are still many objects without namespaces, so I think it is "on the way".
