### ISSUE TITLE
Variable ItemPeriodLength and PeriodType not declared Protected in page "Item Availability by Location" and "Item Availability by UOM"

### ISSUE THREAD

**Issue by murielaimar** [microsoft/ALAppExtensions#24863]
In page "Item Availability by UOM" variable "PeriodType"  is not declared Protected and therefore cannot be used
In page "Item Availability by Location" variable ItemPeriodLength is not declared Protected and therefore cannot be used

can you make the change ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12965.
