### ISSUE TITLE
codeunit 1302 "Customer Mgt." CalculateShipToBillToOptions Option to Enum Problem

### ISSUE THREAD

**Issue by SBiernat** [microsoft/ALAppExtensions#24862]
**🕮 Describe the request**
In Codeunit 1302 - CalculateShipToBillToOptions the Parameter should change from Option to Enum
Reason:
In Page SalesHeader the Protected Var has changed from Option to Enum with Version 21

So this Code in Page 42 "SalesHeader" 
    procedure UpdateShipToBillToGroupVisibility()
    begin
        CustomerMgt.CalculateShipToBillToOptions(ShipToOptions, BillToOptions, Rec);
    end;
should throw also warning of implicit conversion , because the Protected Var ShipToOptions of Type Enum is passed to a function with option vars.

A clear and concise description of what the extensibility request is, which you want Microsoft to address.
Change the following in Codeunit 1302
Old:
procedure CalculateShipToBillToOptions(var ShipToOptions: Option "Default (Sell-to Address)","Alternate Shipping Address","Custom Address"; var BillToOptions: Option "Default (Customer)","Another Customer","Custom Address"; var SalesHeader: Record "Sales Header")
New:
procedure CalculateShipToBillToOptions(var ShipToOptions: Enum "Sales Ship-to Options"; var BillToOptions: Enum "Sales Bill-to Options"; var SalesHeader: Record "Sales Header")

Old:
    [IntegrationEvent(false, false)]
    local procedure OnAfterCalculateShipToBillToOptions(var ShipToOptions: Option "Default (Sell-to Address)","Alternate Shipping Address","Custom Address"; var BillToOptions: Option "Default (Customer)","Another Customer","Custom Address"; SalesHeader: Record "Sales Header")
    begin
    end;
New:
    [IntegrationEvent(false, false)]
    local procedure OnAfterCalculateShipToBillToOptions(var ShipToOptions: Enum "Sales Ship-to Options"; var BillToOptions: Enum "Sales Bill-to Options"; SalesHeader: Record "Sales Header")
    begin
    end;

**Additional context**

Explain why you need this request to be fulfilled. This will help Microsoft assess, if your request could get solved in other ways.
Because in my Page Extension i am Using the protected Vars and pass it to the Codeunit 1302 .

**Comment by SBiernat** [comment]
Hey @JesperSchulz could this become a problem in 23.1 when this is not fixed ?

Some days ago i got an email with the following content:
"Modify your extension so it’s compatible with the version 23.1.12403.0 We’re making changes in the next release (version 23.1.12403.0) of Dynamics 365 Business Central. These changes will render the CCO0 Main extension that’s installed in your Production (Production) environment incompatible.This incompatibility must be resolved before your environment can be updated to version 23.1.12403.0. You can find the compatibility error details and mitigation steps here.
....
Extension validation result:
src/SalesLine.TableExt.al (447,57) - Error AL0193: Argument 2: cannot convert from 'Enum Microsoft.Sales.Document."Sales Document Type"' to the type of Argument 1 'Enum "CCS DM Document Type"' src/SalesLine.TableExt.al (504,61) - Error AL0193: Argument 2: cannot convert from 'Enum Microsoft.Sales.Document."Sales Document Type"' to the type of Argument 1 'Enum "CCS DM Document Type"

So when 23.1 make this to an error, then this Problem should be fixed till then.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13151.
