### ISSUE TITLE
Service Line needs event OnAfterCheckItemAvailable in procedure CheckItemAvailable

### ISSUE THREAD

**Issue by MarcGeoerge** [microsoft/ALAppExtensions#24861]
Service Line needs event OnAfterCheckItemAvailable in procedure CheckItemAvailable

![image](https://github.com/microsoft/ALAppExtensions/assets/145436894/a9e34361-914e-4ef8-b6b8-fe029ac85f39)

        //>>> event request
        OnAfterCheckItemAvailable(Rec, CalledByFieldNo);
        //<<<

 Integration event

    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckItemAvailable(var Rec: Record "TSRM Service Line"; CalledByFieldNo: Integer)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12553.
