### ISSUE TITLE
[Event Request] - Report 10883 "SEPA ISO20022" - procedure OnPostReport()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#24872]
I would like to change the name of the generated file. So, I need an event to modify the Text009 label.

![image](https://github.com/microsoft/ALAppExtensions/assets/29279866/06f32beb-ef23-43e7-a44f-bc9c19155afd)

**Comment by CyrilleJsmt** [comment]
Can you confirm the feasibility for me please ?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13636.
