### ISSUE TITLE
[EVENT REQUEST] - Table 274 Bank Acc. Reconciliation Line - Function GetStyle()

### ISSUE THREAD

**Issue by aismel87** [microsoft/ALAppExtensions#24871]
Dear Al Development Team,

In codeunit 27, local function GetStyle, we need an event here:

![image](https://github.com/microsoft/ALAppExtensions/assets/93609371/dba8ae16-b3a3-4b5f-b4a6-f2622c78bf0d)

```
OLD CODE:
procedure GetStyle(): Text
    begin
        if "Applied Entries" <> 0 then
            exit('Favorable');

        exit('');
    end;

NEW CODE:
procedure GetStyle(): Text
// Init New Code
var
        IsHandled: Boolean;
// End New Code
    begin
        // Init New Code
        IsHandled := false;
        OnBeforeGetStyle(BankAccReconciliationLine, isHandled);
        if IsHandled then
            exit;
        // End New Code
        if "Applied Entries" <> 0 then
            exit('Favorable');

        exit('');
    end;

```

New publisher:
```
[IntegrationEvent(false, false)]
    local procedure OnBeforeGetStyle(var BankAccReconciliationLine: Record "Bank Acc. Reconciliation Line"; var IsHandled: Boolean)
    begin
    end;
```

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12615.
