### ISSUE TITLE
Codeunits 11, 80, 90, 393, 395 a 5988 - new event into CheckVATDate functions

### ISSUE THREAD

**Issue by LubomirUrx** [microsoft/ALAppExtensions#24879]
Please,
in all listed codeunits (11, 80, 90, 393, 395 a 5988) add new event into functions CheckVATDate functions.

**Example - CU 11**

```
local procedure CheckVATDate(var GenJournalLine: Record "Gen. Journal Line")
var
   GenJnlCheckLine: Codeunit "Gen. Jnl.-Check Line";
   SetupRecID: RecordID;
   IsHandled: Boolean;
begin
   IsHandled := false;
   OnBeforeCheckVATDate(GenJournalLine, IsHandled);
   if not IsHandled then begin
   // check whether VAT Date is within allowed VAT Periods
      GenJnlCheckLine.CheckVATDateAllowed(GenJournalLine."VAT Reporting Date");

   //Start new code
   OnCheckVATDateOnBeforeIsDateNotAllowed(IsHandled);
   If IsHandled then
      exit;
   //End new code

   // check whether VAT Date is within Allowed period fedined in Gen. Ledger Setup
      if GenJnlCheckLine.IsDateNotAllowed(GenJournalLine."VAT Reporting Date", SetupRecID, GenJournalLine."Journal Template Name") then
         GenJournalLine.FieldError(GenJournalLine."VAT Reporting Date", ErrorInfo.Create(VATDateNotAllowedErr, true));
   end;
end;
```

**New publisher**

```
[IntegrationEvent(false, false)]
local procedure OnCheckVATDateOnBeforeIsDateNotAllowed(var IsHandled: Boolean)
begin
end;
```

We need to suppress VAT Reporting Date checking for an accounting period.

Thank you

**Comment by AleksandricMarko** [comment]
Hello @LubomirUrx 

Please create request for every object separately.
Also, structure of the procedures is not the same in all mentioned objects.
For example, in codeunit 80 adding event OnCheckVATDateOnBeforeIsDateNotAllowed(IsHandled); in the procedure CheckVATDate(var SalesHeader: Record "Sales Header") does not have point as the structure of the procedure is
![image](https://github.com/microsoft/ALAppExtensions/assets/133204513/4fa8eb4c-48db-4c73-aef5-81059a3beb5f)

be aware that we are adding new events just in the latest version of the app (now BC23)
