### ISSUE TITLE
[Event Change Request] - Make the parameter "CalcAddCurr" on "OnBeforeCalcCellValue" of codeunit 8 AccSchedManagement as passed by reference.

### ISSUE THREAD

**Issue by omerfaruknav** [microsoft/ALAppExtensions#24877]
I need to have the parameter of CalcAddCurr of Event OnBeforeCalcCellValue of codeunit 8 AccSchedManagement as var ( by reference).

Please make this or provide an alternative event above/below of this event to satisfy this condition.

**Comment by AleksandricMarko** [comment]
Hello @omerfaruknav 
Do you need to update event OnBeforeCalcCellValue or OnBeforeCalcCell?
Or maybe both?

**Comment by omerfaruknav** [comment]
Sorry for this , I need this update for the event OnBeforeCalcCellValue only. ( will edit my post )

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12672.
