### ISSUE TITLE
[Request for Protected] Page   113 "Budget"

### ISSUE THREAD

**Issue by omerfaruknav** [microsoft/ALAppExtensions#24878]
Can the following variable become Protected:

- BusUnitFilter

thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12965.
