### ISSUE TITLE
[Event Request] Table 271 "Bank Account Ledger Entry" - OnAfterSetBankReconciliationCandidatesFilter in procedure SetBankReconciliationCandidatesFilter for applying or changing filters

### ISSUE THREAD

**Issue by rishiaurrishabh** [microsoft/ALAppExtensions#24880]
**Can we have a new event OnAfterSetBankReconciliationCandidatesFilter in bank account ledger entry table in procedure SetBankReconciliationCandidatesFilter for applying or changing filters**

There are requirements from customer where they want to apply additional filters on Bank account ledger entry table and also modify the existing applied filters. we have raised issued with Microsoft where customers were not able to reconcile Reversed records with auto matching action where Microsoft suggested that its by design but an additional event here can help. (I am putting there response in the additional context section.

**Response from Microsoft: TrackingID#2308240030003582
Hello Rishabh,

Please find the comments from the product group team.

“
For automatch there is no event they can currently use

An event in the file BankAccountLedgerEntry.Table.al could help, here:
![image](https://github.com/microsoft/ALAppExtensions/assets/39942971/8abc69d2-11c8-4a76-b030-dae5562a1e4f)

 
OnAfterSetBankReconciliationCandidatesFilter(var BankAccountLedgerEntry: Record "Bank Account Ledger Entry")

The subscriber would simple do `BankAccountLedgerEntry.SetRange(Reversed)`.

Since the event doesn't exist, partner can submit the GitHub PR to this part of the code with the subscriber. It would then be picked up by the SE team and incorporated in a future release.
**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12672.
