### ISSUE TITLE
Change global variable IsBankAccReconInitialized to a protected var on the Payment Reconciliation Journal Page (URGENT)

### ISSUE THREAD

**Issue by MortenKSorensen** [microsoft/ALAppExtensions#24881]
**🕮 Description**

When we extend the Payment Reconciliation Journal Page and change values on the Bank Account Reconciliation table then the page gives a runtime error due to the fact that the global variable on the page is not updated. We cannot influence this from a page extension as the variable controlling the update of the Bank Account Reconciliation is not accessible from the page extension.

This is breaking customers. I am open to creating a PR for the base app in order to fix the issue asap. 

**🔧 To Reproduce**

1. Go to 'Payment Reconciliation Journal Page'
2. Click on  'Some custom action'  that changes the Bank Account Reconciliation table
3.Do anything on the page that would cause the page to update

**📣 Expected behavior**

We would expect that it is possible to set the global variable **IsBankAccReconInitialized** to false and then the base app code will cause a new Get on the Bank Account Reconciliation table. Changing the global variable to a **protected global variable** would solve the problem.

**Screenshots**

The global variable:
![image](https://github.com/microsoft/ALAppExtensions/assets/38498939/b252565c-8a90-48a7-afd1-b9aa652212d3)

The runtime error shown on the page:
![image](https://github.com/microsoft/ALAppExtensions/assets/38498939/6035cf7c-b62b-492a-99a6-f98f38f88a00)

**Additional context**

The structure is breaking customers and causing runtime error. We hope to have this fixed ASAP. We are also open for creating a PR for the Base App ourselves to speedup the process. 
@JesperSchulz

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12965.
