### ISSUE TITLE
Codeunit 5988 Serv-Documents Mgt. - new event into CheckVATDate function

### ISSUE THREAD

**Issue by LubomirUrx** [microsoft/ALAppExtensions#24887]
Please,
in codeunit  5988 "Serv-Documents Mgt." add new event into functions CheckVATDate function.

    local procedure CheckVATDate(var ServiceHeader: Record "Service Header")
    var
        GLSetup: Record "General Ledger Setup";
        GenJnlCheckLine: Codeunit "Gen. Jnl.-Check Line";
        SetupRecID: RecordID;
        //Start new code
        IsHandled: Boolean;
        //End new code
    begin
        // ensure VAT Date is filled in
        If ServiceHeader."VAT Reporting Date" = 0D then begin
            ServiceHeader."VAT Reporting Date" := GLSetup.GetVATDate(ServiceHeader."Posting Date", ServiceHeader."Document Date");
            ServiceHeader.Modify();
        end;

        // check whether VAT Date is within allowed VAT Periods
        GenJnlCheckLine.CheckVATDateAllowed(ServiceHeader."VAT Reporting Date");

        //Start new code
        OnCheckVATDateOnBeforeIsDateNotAllowed(ServiceHeader, SetupRecID, IsHandled);
        if not IsHandled then
        //End new code

        // check whether VAT Date is within Allowed period defined in Gen. Ledger Setup
        if GenJnlCheckLine.IsDateNotAllowed(ServiceHeader."VAT Reporting Date", SetupRecID, ServiceHeader."Journal Templ. Name") then
            ServiceHeader.FieldError(ServiceHeader."VAT Reporting Date", VATDateNotAllowedErr);
    end;

**New publisher**

```
      [IntegrationEvent(false, false)]
      local procedure OnCheckVATDateOnBeforeIsDateNotAllowed(var ServiceHeader: Record "Service Header"; var SetupRecordID: 
      RecordID; var IsHandled: Boolean)
      begin
      end;
```

**Comment by AleksandricMarko** [comment]
Hello @LubomirUrx 

Please review request.
Procedure CheckVATDate  does not include any more code that you want to skip.

![image](https://github.com/microsoft/ALAppExtensions/assets/133204513/d142456d-3b2f-431e-a5e7-1227a1a2f02b)
