### ISSUE TITLE
[Events Request] at 699 "Exch. Rate Adjmt. Process" codeunit

### ISSUE THREAD

**Issue by iyiannak** [microsoft/ALAppExtensions#24888]
Hello! We are requesting the implementation of integration events at codeunit 699 "Exch. Rate Adjmt. Process" as per below

1. Add a new event **OnBeforeSetBankAccountFilters** to codeunit 699 "Exch. Rate Adjmt. Process" and call it in 2 places:

    local procedure AdjustCurrency(var ExchRateAdjmtParameters: Record "Exch. Rate Adjmt. Parameters" temporary)
    var
        BankAccount: Record "Bank Account";
    begin
        BankAccount.SetFilter("No.", ExchRateAdjmtParameters.GetFilter("Bank Account Filter"));
        BankAccount.FilterGroup(2);
        BankAccount.SetFilter("Currency Code", '<>%1', '');
		OnBeforeSetBankAccountFilters(BankAccount); <=== FIRST CALL
        BankAccount.FilterGroup(0);
        BankAccNoTotal := BankAccount.Count();
        BankAccount.Reset();

        Currency.SetView(ExchRateAdjmtParameters."Currency Filter");
        if Currency.FindSet() then begin
            Currency."Last Date Adjusted" := ExchRateAdjmtParameters."Posting Date";
            Currency.Modify();

            Currency."Currency Factor" := CurrExchRate.ExchangeRateAdjmt(ExchRateAdjmtParameters."Posting Date", Currency.Code);

            TempCurrencyToAdjust := Currency;
            TempCurrencyToAdjust.Insert();

            repeat
                BankAccount.SetCurrentKey("Bank Acc. Posting Group");
                BankAccount.SetRange("Currency Code", Currency.Code);
                BankAccount.SetRange("Date Filter", ExchRateAdjmtParameters."Start Date", ExchRateAdjmtParameters."End Date");
                OnBeforeSetBankAccountFilters(BankAccount) <=== SECOND CALL
                if BankAccount.FindSet() then
                ......

[IntegrationEvent(false, false)]
    local procedure OnBeforeSetBankAccountFilters(var BankAccount: Record "Bank Account";)
    begin
    end;
 

2. Add a new event **OnBeforeSetCustLedgerEntryFilters** to codeunit 699 "Exch. Rate Adjmt. Process" and call it in 2 places:

    local procedure PrepareTempCustLedgEntry(var Customer: Record Customer; var TempCustLedgerEntry: Record "Cust. Ledger Entry" temporary; CompanyCode: Code[20])
    var
        CustLedgerEntry2: Record "Cust. Ledger Entry";
        DtldCustLedgEntry2: Record "Detailed Cust. Ledg. Entry";
    begin
        TempCustLedgerEntry.DeleteAll();

        Currency.CopyFilter(Code, CustLedgerEntry2."Currency Code");
        CustLedgerEntry2.FilterGroup(2);
        CustLedgerEntry2.SetFilter("Currency Code", '<>%1', '');
        OnBeforeSetCustLedgerEntryFilters(CustLedgerEntry2); <=== FIRST CALL
        CustLedgerEntry2.FilterGroup(0);

        ......

        CustLedgerEntry2.SetCurrentKey("Customer No.", Open);
        CustLedgerEntry2.SetRange("Customer No.", Customer."No.");
        CustLedgerEntry2.SetRange(Open, true);
        CustLedgerEntry2.SetRange("Posting Date", 0D, ExchRateAdjmtParameters."End Date");
        OnBeforeSetCustLedgerEntryFilters(CustLedgerEntry2); <==SECOND CALL
        if CustLedgerEntry2.Find('-') then
        
 [IntegrationEvent(false, false)]
    local procedure OnBeforeSetCustLedgerEntryFilters(var CustLedgerEntry: Record "Cust. Ledger Entry")
    begin
    end;   
 

3. Add a new event **OnBeforeSetDtldCustLedgerEntryFilter**s to codeunit 699 "Exch. Rate Adjmt. Process" and call it in 1 place:

local procedure PrepareTempCustLedgEntry(var Customer: Record Customer; var TempCustLedgerEntry: Record "Cust. Ledger Entry" temporary; CompanyCode: Code[20])
    var
        CustLedgerEntry2: Record "Cust. Ledger Entry";
        DtldCustLedgEntry2: Record "Detailed Cust. Ledg. Entry";
    begin
        TempCustLedgerEntry.DeleteAll();
        .....
        DtldCustLedgEntry2.Reset();
        DtldCustLedgEntry2.SetCurrentKey("Customer No.", "Posting Date", "Entry Type");
        DtldCustLedgEntry2.SetRange("Customer No.", Customer."No.");
        DtldCustLedgEntry2.SetRange("Posting Date", CalcDate('<+1D>', ExchRateAdjmtParameters."End Date"), DMY2Date(31, 12, 9999));
        OnBeforeSetDtldCustLedgerEntryFilters(DtldCustLedgEntry2); <=== CALL
        if DtldCustLedgEntry2.Find('-') then
        
[IntegrationEvent(false, false)]
    local procedure OnBeforeSetDtldCustLedgEntryFilters(var DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry")
    begin
    end;
4. Add a new event **OnBeforeSetVendLedgerEntryFilters** to codeunit 699 "Exch. Rate Adjmt. Process" and call it in 2 places:

local procedure PrepareTempVendLedgEntry(var Vendor: Record Vendor; var TempVendorLedgerEntry: Record "Vendor Ledger Entry" temporary; CompanyCode: Code[20]);
    var
        VendorLedgerEntry2: Record "Vendor Ledger Entry";
        DtldVendLedgEntry2: Record "Detailed Vendor Ledg. Entry";
    begin
        TempVendorLedgerEntry.DeleteAll();

        Currency.CopyFilter(Code, VendorLedgerEntry2."Currency Code");
        VendorLedgerEntry2.FilterGroup(2);
        VendorLedgerEntry2.SetFilter("Currency Code", '<>%1', '');
        OnBeforeSetVendLedgerEntryFilters(VendorLedgerEntry2); <=== FIRST CALL
        VendorLedgerEntry2.FilterGroup(0);

        .....

        VendorLedgerEntry2.SetCurrentKey("Vendor No.", Open);
        VendorLedgerEntry2.SetRange("Vendor No.", Vendor."No.");
        VendorLedgerEntry2.SetRange(Open, true);
        VendorLedgerEntry2.SetRange("Posting Date", 0D, ExchRateAdjmtParameters."End Date");
        OnBeforeSetVendLedgerEntryFilters(VendorLedgerEntry2); <=== SECOND CALL
        if VendorLedgerEntry2.Find('-') then
            repeat
                TempVendorLedgerEntry."Entry No." := VendorLedgerEntry2."Entry No.";
                if TempVendorLedgerEntry.Insert() then;
            until VendorLedgerEntry2.Next() = 0;
        VendorLedgerEntry2.Reset();
    end;
    
 [IntegrationEvent(false, false)]
    local procedure OnBeforeSetVendLedgerEntryFilters(var VendLedgEntry: Record "Vendor Ledger Entry")
    begin
    end; 
      
 
5. Add a new event **OnBeforeSetDtldVendLedgerEntryFilters** to codeunit 699 "Exch. Rate Adjmt. Process" and call it in 1 place:

local procedure PrepareTempVendLedgEntry(var Vendor: Record Vendor; var TempVendorLedgerEntry: Record "Vendor Ledger Entry" temporary; CompanyCode: Code[20]);
    var
        VendorLedgerEntry2: Record "Vendor Ledger Entry";
        DtldVendLedgEntry2: Record "Detailed Vendor Ledg. Entry";
    begin
        TempVendorLedgerEntry.DeleteAll();
        .....
        DtldVendLedgEntry2.Reset();
        DtldVendLedgEntry2.SetCurrentKey("Vendor No.", "Posting Date", "Entry Type");
        DtldVendLedgEntry2.SetRange("Vendor No.", Vendor."No.");
        DtldVendLedgEntry2.SetRange("Posting Date", CalcDate('<+1D>', ExchRateAdjmtParameters."End Date"), DMY2Date(31, 12, 9999));
        OnBeforeSetDtldVendLedgerEntryFilters(DtldVendLedgEntry2)
        if DtldVendLedgEntry2.Find('-') then
            repeat
                VendorLedgerEntry2."Entry No." := DtldVendLedgEntry2."Vendor Ledger Entry No.";
                if VendorLedgerEntry2.Find('=') then
                    if (VendorLedgerEntry2."Posting Date" >= ExchRateAdjmtParameters."Start Date") and
                        (VendorLedgerEntry2."Posting Date" <= ExchRateAdjmtParameters."End Date")
                    then begin
                        TempVendorLedgerEntry."Entry No." := VendorLedgerEntry2."Entry No.";
                        if TempVendorLedgerEntry.Insert() then;
                    end;
            until DtldVendLedgEntry2.Next() = 0;
            
[IntegrationEvent(false, false)]
    local procedure OnBeforeSetDtldVendLedgEntryFilters(var DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry")
    begin
    end;
 

**We need also to pass a global variable of type Code[20] to the codeunit - this value will be used inside the filtering event handlers (Global Dimension 1 Code)**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12672.
