### ISSUE TITLE
[Event Request] Add new event to apply filters on Posted Approval Entry Record and Approval Comment Line record before deleting records on posting Journal Batch.

### ISSUE THREAD

**Issue by arvindbinarystream** [microsoft/ALAppExtensions#24890]
Hi team,

There is a new feature that I am working on for approvals based on General Journal batch.
In order to make our functionality work and for better user interaction we need some integration events.

Previously, I had raised an issue which is closed now ( https://github.com/microsoft/ALAppExtensions/issues/24817 ). Thanks for looking into it @JesperSchulz .

Below is the list of additional integration events that we need.
New Event Will be

1. codeunit 1521 "Workflow Response Handling"
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/98f7c031-9cc1-45dc-b9c8-b9146a9eeb12)

- Event signature will be:-
- [IntegrationEvent(false, false)]
- local procedure OnExecuteResponseOnBeforeShowMessage(WorkflowStepArgument: Record "Workflow Step Argument", var SuppressMessage:Boolean);
- begin
- end;

2. codeunit 1535 "Approvals Mgmt."
1.
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/f70dd61b-0f5c-4f0d-82f1-87ae79831bb7)

- Event signature will be:-
- [IntegrationEvent(false, false)]
- local procedure OnPostApprovalEntriesOnAfterSetApprovalEntryFilters(var ApprovalEntry: Record "Approval Entry"; TableNo: Integer)
- begin
- end;

2. 
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/4b3b2e8f-135b-476c-bc9d-94a4bcce5aee)

- Event signature will be:-
- [IntegrationEvent(false, false)]
- local procedure OnPostApprovalCommentLinesOnAfterSetApprovalCommentLineFilters(var ApprovalCommentLine: Record "Approval Comment Line"; TableNo: Integer)
- begin
- end;

3. 
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/3354fdf5-4171-41e7-9426-675ea6c31367)

- Event signature will be:-
- [IntegrationEvent(false, false)]
- local procedure OnDeleteApprovalCommentLinesOnAfterApprovalCommentLineSetFilters(var ApprovalCommentLine: Record "Approval Comment Line")
- begin
- end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12672.
