### ISSUE TITLE
[Event Change Request] Fix in CreateDim event - Table 5621 “FA Journal Line”

### ISSUE THREAD

**Issue by MassimoMarraSerinf** [microsoft/ALAppExtensions#24892]
Hello,
I find a not homogeneus behaviour in "CreateDim" function for Table 5621.
In the event "OnBeforeCreateDim" the "DefaultDimSource" parameter (in "var") is missing.
![image](https://github.com/microsoft/ALAppExtensions/assets/61522905/cd068f5e-73c5-481d-ad20-6a587f0758e9)

See event "OnBeforeCreateDim" in "purchase Header" or "Sales line" tables as example for what I expext:
![image](https://github.com/microsoft/ALAppExtensions/assets/61522905/e5451837-465d-42ec-81d9-ed17768bf184)
![image](https://github.com/microsoft/ALAppExtensions/assets/61522905/faebf06a-4efd-47d3-ac40-373bcb4c2e56)

All tables has "DefaultDimSource" parameter (in "var") in the "OnBeforeCreateDim" event of the "CreateDim" function.

Regards

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12672.
