### ISSUE TITLE
ABSBlobClient.ListBlobs(ABSContainerContent) duplicates directory names in storage accounts with hierarchical namespace

### ISSUE THREAD

**Issue by adrogin** [microsoft/ALAppExtensions#24891]
**Steps to reproduce**

1. Create an Azure storage account with Azure Data Lake Gen2 capabilities, make sure that the hierarchical namespace is enabled
![image](https://github.com/microsoft/ALAppExtensions/assets/42849285/a7d0ef05-ad1a-40fe-a715-3c061337a289)

2. Create a new container under this account
3. Open the container in the container browser on the Azure portal and create a directory ("Add Directory" action).
4. Upload a file into the directory.
5. Invoke the procedure ListBlobs(ABSContainerContent) from the codeunit "ABS Blob Client". Sample code is below.

```
    procedure ListBlobsInContainer(ContainerName: Text; var ABSContainerContent: Record "ABS Container Content")
    var
        ABSBlobClient: Codeunit "ABS Blob Client";
        ABSOperationResponse: Codeunit "ABS Operation Response";
        Authorization: Interface "Storage Service Authorization";
    begin
        Authorization := StorageServicesAuthorization.CreateSharedKey(GetSharedKey());
        ABSBlobClient.Initialize(GetStorageAccount(), ContainerName, Authorization);
        ABSOperationResponse := ABSBlobClient.ListBlobs(ABSContainerContent);
    end;
```
7. The returned list of BLOBs in the ABSContainerContent table contains two entries for the directory.

![image](https://github.com/microsoft/ALAppExtensions/assets/42849285/fa281fc1-3086-44e0-8404-7be37fa9b6be)

**Expected result**
The list in the screenshot must contain two entries for block blobs "foo" "foo/bar.txt".

**Cause**
"ABS Container Content Helper" splits the blob name interpreting each slash symbol as a delimiter for a  directory name, and returns a separate entry for each slash-delimited substring. This approach successfully imitates the directory structure for the flat container namespace. But if the hierarchical namespace is enabled, the API response already contains folder names, so the splitting of the BLOB name duplicates entries.
Other overloads of ListBlobs do not have this issue, because they do not call the splitting method and return the node list from the API response as is.

Here is the API response from Postman for the reference
```
<?xml version="1.0" encoding="utf-8"?>
<EnumerationResults ServiceEndpoint="https://***.blob.core.windows.net/" ContainerName="samplecontainer">
    <Blobs>
        <Blob>
            <Name>foo</Name>
            <Properties>
                <Creation-Time>Sat, 23 Sep 2023 21:04:18 GMT</Creation-Time>
                <Last-Modified>Sat, 23 Sep 2023 21:04:18 GMT</Last-Modified>
                <Etag>0x8DBBC78A6E95AF7</Etag>
                <ResourceType>directory</ResourceType>
                <Content-Length>0</Content-Length>
                <Content-Type>application/octet-stream</Content-Type>
                <Content-Encoding />
                <Content-Language />
                <Content-CRC64>AAAAAAAAAAA=</Content-CRC64>
                <Content-MD5 />
                <Cache-Control />
                <Content-Disposition />
                <BlobType>BlockBlob</BlobType>
                <AccessTier>Hot</AccessTier>
                <AccessTierInferred>true</AccessTierInferred>
                <LeaseStatus>unlocked</LeaseStatus>
                <LeaseState>available</LeaseState>
                <ServerEncrypted>true</ServerEncrypted>
            </Properties>
            <OrMetadata />
        </Blob>
        <Blob>
            <Name>foo/bar.txt</Name>
            <Properties>
                <Creation-Time>Wed, 27 Sep 2023 20:55:36 GMT</Creation-Time>
                <Last-Modified>Wed, 27 Sep 2023 20:55:36 GMT</Last-Modified>
                <Etag>0x8DBBF9C194887C4</Etag>
                <ResourceType>file</ResourceType>
                <Content-Length>1</Content-Length>
                <Content-Type>text/plain</Content-Type>
                <Content-Encoding />
                <Content-Language />
                <Content-CRC64 />
                <Content-MD5>dpT0pmMW5TyM3Z2ZVL1hHQ==</Content-MD5>
                <Cache-Control />
                <Content-Disposition />
                <BlobType>BlockBlob</BlobType>
                <AccessTier>Hot</AccessTier>
                <AccessTierInferred>true</AccessTierInferred>
                <LeaseStatus>unlocked</LeaseStatus>
                <LeaseState>available</LeaseState>
                <ServerEncrypted>true</ServerEncrypted>
            </Properties>
            <OrMetadata />
        </Blob>
    </Blobs>
    <NextMarker />
</EnumerationResults>
```

**Comment by pri-kise** [comment]
Sounds valid.
Currently hieracical namespaces cannot be tested with azurite https://github.com/Azure/Azurite/issues/553.
Therefore this response musted be mocked.

But I'm confused by the result for the "folder" **foo**.
Is there any way to find out which result (includuing folder names - on ADLS Gen2 with hieracical namespaces enabled) we are getting before processing the result?

**Comment by adrogin** [comment]
The sample XML is the complete response before starting the processing. The folder name here does not have any special tag - it's just another blob.
I sent a pull request with a proposed solution based on the response I am receiving, but now I found that the list request should explicitly return the resource type - file or directory. I'll check again why I am not receiving this property and update my solution.
As for testing, I would suggest to add a few tests on response parsing without Azurite.

**Comment by duichwer** [comment]
I wanted to write the same.
https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=azure-ad#response-body

The default version of this repo is 2020-10-02.
Therefore the resource type should be included if hierarchical namespaces is enabled.

> For version 2020-10-02 and later, for accounts with a hierarchical namespace enabled, List Blobs returns the ResourceType property element for the path. This can be either file or directory.

**Comment by adrogin** [comment]
Indeed, I was calling the wrong version of the API (missing the x-ms-version header. Fixed my request and updated the sample response in the issue description.
This is the same response that is received in BC, so we can rely on the ResourceType property in case of a hierarchical namespace. I updated the pull request accordingly.
