### ISSUE TITLE
[Event Request] New Event in Codeunit 13 - "Gen Jnl.-Post Batch" for VAT management.

### ISSUE THREAD

**Issue by MassimoMarraSerinf** [microsoft/ALAppExtensions#24893]
Hello,
we need a new event to manage specific behaviour in case of VAT management.

we suggest the following event at the beginning of function "UpdateGenJnlLineWithVATInfo" in Codeunit 13 (with "ishandled" management):

OnBeforeUpdateGenJnlLineWithVATInfo(var GenJournalLine: Record "Gen. Journal Line"; GenJournalLineVATInfoSource: Record "Gen. Journal Line"; StartLineNo: Integer; LastLineNo: Integer; var IsHandled: boolean)

![image](https://github.com/microsoft/ALAppExtensions/assets/61522905/1325cb7d-a9bf-48ed-80f2-b46f1f353bd5)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12672.
