### ISSUE TITLE
[Extensibility Bug] Page 392 Phys. Inventory Journal Report.RunModal Calculate Inventory

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#2489]
The CalculateInventory  Action on Page 392 Phys. Inventory Journal uses a variable for report 790 Calculate Inventory.  Can you please change this to use Report.RUNMODAL so that we can substitute a custom report without having to create a new page action in our extension?

We would like to take advantage of the OnAfterSubstituteReport event.

Thank you!

**Comment by StanPesotskiy** [comment]
In order to use Report.RUNMODAL and set the required internal globals in the codeunit we will have to do refactoring of the report 790. But the original idea here is not to run this report. 
So we suggest to extend the page, hide the action, and add another one that will do the right things.

**Comment by sboeve** [comment]
Thank you for your response.  Would you be able to tell me if there is another report or codeunit that should be run instead of this report?


Susan Boeve | Developer
p. 631.756.2700 x716
accessIT | contractERP

**Comment by StanPesotskiy** [comment]
In the initial request you wanted to substitute the standard report. We assumed you have something that do what you need instead of this report. Otherwise even Report.RUNMODAL won't help.

**Comment by sboeve** [comment]
I do, but was just curious to see what had replaced it.  Thanks!


Susan Boeve | Developer
p. 631.756.2700 x716
accessIT | contractERP
