### ISSUE TITLE
[Events Request] at 130454 Test Runner - Mgt Codeunit

### ISSUE THREAD

**Issue by JerryTyssen** [microsoft/ALAppExtensions#24894]
Hello! We are requesting the implementation of 2 new events at 130454 Test Runner - Mgt:

**1. Procedure GetTestCodeunit()** 

local procedure GetTestCodeunit(var CodeunitTestMethodLineFunction: Record "Test Method Line"; TestSuite: Code[10]; TestCodeunit: Integer): Boolean
    var
        TestMethodLineImpl: Codeunit TestMethodLineImpl;
    begin
+     OnBeforeGetTestCodeunit(var CodeunitTestMethodLineFunction: Record "Test Method Line")
    

**2. Procedure GetTestFunction()** 

local procedure GetTestFunction(var TestMethodLineFunction: Record "Test Method Line"; FunctionName: Text[128]; TestSuite: Code[10]; TestCodeunit: Integer; LineNoTestFilter: Text): Boolean
    var
        TestMethodLineImpl: Codeunit TestMethodLineImpl;
    begin
        TestMethodLineFunction.Reset();
+      OnBeforeGetTestFunction(var TestMethodLineFunction: Record "Test Method Line")

And the at the end of the codeunit:            

[IntegrationEvent(false, false)]
local procedure OnBeforeGetTestCodeunit(var TestMethodLine: Record "Test Method Line")
begin
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeGetTestFunction(var TestMethodLine: Record "Test Method Line")
begin
end;

**Note**: we don't need the IsHandled pattern, but can be added if needed.

**Background**: we added an internal test case id field in the table "Test Method Line" which we need to filter on in the 2 procedures above.

Thanks in advance,

Jerry Tyssen
Cegeka

**Comment by JesperSchulz** [comment]
Hi @JerryTyssen,

this issue somehow fell through the cracks! Is your event request still valid?

**Comment by JerryTyssen** [comment]
Hi Jesper,

Yes, it is still valid. The project I was working got postponed, but I still need the requested events.

**Comment by JerryTyssen** [comment]
@JesperSchulz: Hi Jesper, can you give an update on this event request? When can I expect it? Thanks!

**Comment by JesperSchulz** [comment]
> @JesperSchulz: Hi Jesper, can you give an update on this event request? When can I expect it? Thanks!

I'll ask about the status and push for a fix in version 25. @Aleyenda, is that possible?

**Comment by nikolakukrika** [comment]
> @JesperSchulz: Hi Jesper, can you give an update on this event request? When can I expect it? Thanks!

The issue with these two events is that they would extend the tool in a way that will make it hard for us to move to the managed API in the future. The overall goal is that these codeunits should eventually be moved to the platform, and we do not want extensibility in them that is nice to have. 

From our point of view the keys on the test method line are unique. Why you cannot use the keys that we have?
What is different in your own solution that makes these events needed?

**Comment by nikolakukrika** [comment]
Closing as not planned due to lack of feedback. Please reactivate with the answers to the question above.

**Comment by JerryTyssen** [comment]
Sorry for the late answer, but the internal project was postponed a couple of times.

A little background: we added a field to the "Test Method Line" table which stores a DevOps test case number which we link to a custom table which the user can use to setup data themselves. When running the unit tests, we need to access that custom table so the unit tests are run using the data the user has setup. In the end, we can reuse a test codeunit so it can be run multiple times, with different data and without interference of a developer.

Is this supported in the managed API solution? It is okay for us to wait until is there if it is supported. If not, please share your thoughts on a possible alternative to accomplish this.

Thanks in advance!

**Comment by nikolakukrika** [comment]
@JerryTyssen we have added the ability to run the data driven tests. Maybe you can plug into this?

**Comment by JerryTyssen** [comment]
@nikolakukrika: that sounds good. Is there any documentation already? Or has it already been released?

**Comment by nikolakukrika** [comment]
@JerryTyssen the AI test tool is using it you can watch it here
https://www.youtube.com/watch?v=eA7CENx7se0

Docs are being written.

The Data Drivent framework is independent of AI, you could use the same approach for regular AL tests. The idea is that you assign multiple inputs to the test codeunit and when you run it we will expand it into many tests that will use individual lines. On the Test Runner page you can find the actions under data driven tests, you can read the code from there.
