### ISSUE TITLE
Codeunit 5750 - event OnBeforeFromSalesLine2ShptLine - missing Header information

### ISSUE THREAD

**Issue by LukRod** [microsoft/ALAppExtensions#24908]
On codeunit 5750 "Whse.-Create Source Document"
Following event "OnBeforeFromSalesLine2ShptLine" have missing "WhseShptHeader" paramater in it.

[IntegrationEvent(false, false)]
    local procedure OnBeforeFromSalesLine2ShptLine(var SalesLine: Record "Sales Line"; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;

All other related events dose have it ie.:

[IntegrationEvent(false, false)]
    local procedure OnBeforeFromTransLine2ShptLine(var TransLine: Record "Transfer Line"; var Result: Boolean; var IsHandled: Boolean; WarehouseShipmentHeader: Record "Warehouse Shipment Header")
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14158.
