### ISSUE TITLE
Assigned Security Group Permission Set is not initialized correctly without lookup

### ISSUE THREAD

**Issue by kaspermoerch** [microsoft/ALAppExtensions#24909]
**🕮 Describe the issue**

If you type the full name of a Permission Set in the Security Groups Permission Sets and then tab out of the field (essentially not doing lookup) the inserted record is not initialized correctly because this code is placed in the OnAfterLookup trigger.

The consequence is that the effective permissions of the security group cannot be resolved correctly.

**🔧 To Reproduce**

1. Go to 'Security Groups'
2. Click on any record
3. Set the cursor in the Permission Set column
4. Type the full name of a Permission Set (e.g. SUPER).
5. Notice that Scope, App ID and Role Name are not assigned.

**📣 Expected behavior**

Scope, App ID and Role Name should match the selected Permission Set.

**Comment by JesperSchulz** [comment]
Sorry about the long reply-time on this issue. I wasn't aware that this many bugs had been filed here, and hence wasn't monitoring this repo.

Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the 1st party Business Central apps. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
