### ISSUE TITLE
[Change Request] page 508 "Blanket Sales Order Subform" - procedure "DeltaUpdateTotals"

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#24901]
**🕮 Describe the request**

    local procedure DeltaUpdateTotals()
    begin
        OnBeforeDeltaUpdateTotals(rec, xRec);
        DocumentTotals.SalesDeltaUpdateTotals(Rec, xRec, TotalSalesLine, VATAmount, InvoiceDiscountAmount, InvoiceDiscountPct);
        if Rec."Line Amount" <> xRec."Line Amount" then
            Rec.SendLineInvoiceDiscountResetNotification();
    end;

**Additional context**
I want to access this procedure from the extension. Can we make this procedure global? As in "SalesOrderSubform", "SalesInvoiceSubform".

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13402.
