### ISSUE TITLE
Report 1307 "Standard Sales - Credit Memo": Make CompanyBankAccount variable accessible to extensions.

### ISSUE THREAD

**Issue by epernst** [microsoft/ALAppExtensions#24907]
We like to add company bank account address and post code to our Sales Credit Memo reportextension (extends 1307), but due to its protection level it is not accessible. It works fine on the standard sales invoice report (1306).

So please add the "CompanyBankAccount" variable to the Protected vars, so that we can use it in our report extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13402.
