### ISSUE TITLE
We need an Event in table 1294 "Applied Payment Entry" - ApplyFromBankStmtMatchingBufOnBeforeInsert 

### ISSUE THREAD

**Issue by Johnson-Pat** [microsoft/ALAppExtensions#24906]
We need an event in the table Applied Payment Entry Procedure "ApplyFromBankStmtMatchingBuf" before inserting into the Applied Payment Entry record. 

Function - 
`procedure ApplyFromBankStmtMatchingBuf(BankAccReconLine: Record "Bank Acc. Reconciliation Line"; BankStmtMatchingBuffer: Record "Bank Statement Matching Buffer"; TextMapperAmount: Decimal; EntryNo: Integer)`

```
Validate("Match Confidence", BankPmtApplRule.GetMatchConfidence(BankStmtMatchingBuffer.Quality));
+ ApplyFromBankStmtMatchingBufOnBeforeInsert(BankAccReconLine, BankStmtMatchingBuffer, TextMapperAmount, EntryNo, AppliedPaymentEntry)
Insert(true);
```
```
+[IntegrationEvent(false, false)]
+local procedure ApplyFromBankStmtMatchingBufOnBeforeInsert(BankAccReconLine: Record "Bank Acc. Reconciliation Line"; +BankStmtMatchingBuffer: Record "Bank Statement Matching Buffer"; TextMapperAmount: Decimal; EntryNo: Integer; var +AppliedPaymentEntry: Record "Applied Payment Entry")
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12756.
