### ISSUE TITLE
[Protected] Report 2000030 "Import CODA Statement" - InStr, FileName (BE localisation)

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#24900]
We would like to save the imported CODA Statement file and link it as attachment to the CODA Statement record. Therefore, we need to have access to the stream / filename of the imported CODA Statement file in report 2000030 "Import CODA Statement".

Can you please put following 2 globals variables as protected, so we can access them via a report extension?

```
protected var
        InStr: InStream;
        FileName: Text;
```

For my reference:
- Currently solved by copying the report and setting the variables stated in a singleinstance codeunit via the OnPreReport trigger.

![image](https://github.com/microsoft/ALAppExtensions/assets/25268332/b1c8d4fa-59f6-4c4e-9089-68c94d0fcf99)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12965.
