### ISSUE TITLE
Invoice Posting Buffer feature issue

### ISSUE THREAD

**Issue by HegedusZsolt** [microsoft/ALAppExtensions#24919]
We have an app which is using the old version of the invoice posting buffer feature. We would like to upload a new version of our app to AppSource, but the validation failed, because BC23 does not support the old invoice posting method.

OK, no problem, let use the new method in BC22, but it is not possible because of the UseLegacyInvoicePosting function in cu 80.

The function above contains this little piece of code: 

        // new invoice posting interface in production environment is currently not allowed
        if EnvironmentInfo.IsProduction() then
            exit(true);

So I can't activate the new feature in BC22, and I also can't publish our app to AppSource with the old one because of the BC23 validation.

It's a deadlock. Right now we can't release any hotfixes for our app. The only option what we have, to wait the official release of BC23 and after that upgrade all of our clients to BC23 to apply the hotfixes.

Please let me know if there is an another option to pass the AppSource validation.

**Comment by pri-kise** [comment]
Yammer thread for reference: https://www.yammer.com/dynamicsnavdev/threads/2443219118866432

**Comment by AlexanderYakunin** [comment]
I hope all answered now and you fixed your app.
