### ISSUE TITLE
[PROTECTED VAR] - Page 397 & Page 398

### ISSUE THREAD

**Issue by aismel87** [microsoft/ALAppExtensions#24922]
Hi AL Dev Team!

At Pages 397 & 398, we need the next VAR's as PROTECTED VAR's to be able to use them in a page extension.

```
CustAmount: Decimal;
InvDiscAmount: Decimal;
PmtDiscAmount: Decimal;
```

![image](https://github.com/microsoft/ALAppExtensions/assets/93609371/e4aa3a86-cfa6-4aac-a9f8-5ce06a87f4d4)

Thank you!

Ismael.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12965.
