### ISSUE TITLE
[PROTECTED VAR] - Pages 133 & 135

### ISSUE THREAD

**Issue by aismel87** [microsoft/ALAppExtensions#24924]
Hi AL Dev Team!

At Pages 133 & 135, we need the next VAR as PROTECTED VAR to be able to use it in a page extension.

`VATAmount: Decimal;`

![image](https://github.com/microsoft/ALAppExtensions/assets/93609371/86ec1002-40d1-4eeb-b10d-a01463f82604)

Thank you!

Ismael

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12965.
