### ISSUE TITLE
[Event Request] Codeunit 99000842 - Service Line-Reserve - OnAfterReservQuantity

### ISSUE THREAD

**Issue by tvwijk** [microsoft/ALAppExtensions#24929]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnAfterReservQuantity` to be added to Codeunit 99000842 Service Line-Reserve with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnAfterReservQuantity(ServiceLine: Record "Service Line"; var QtyToReserve: Decimal; var QtyToReserveBase: Decimal)
    begin
    end;
```

which would be called as follows from `ReservQuantity`:
```al
    procedure ReservQuantity(ServLine: Record "Service Line"; var QtyToReserve: Decimal; var QtyToReserveBase: Decimal)
    begin
        case ServLine."Document Type" of
            ServLine."Document Type"::Quote,
            ServLine."Document Type"::Order,
            ServLine."Document Type"::Invoice:
                begin
                    QtyToReserve := ServLine."Outstanding Quantity";
                    QtyToReserveBase := ServLine."Outstanding Qty. (Base)";
                end;
            ServLine."Document Type"::"Credit Memo":
                begin
                    QtyToReserve := -ServLine."Outstanding Quantity";
                    QtyToReserveBase := -ServLine."Outstanding Qty. (Base)"
                end;
        end;

        OnAfterReservQuantity(ServLine, QtyToReserve, QtyToReserveBase); // << Call event
    end;
```

**Additional context**
This event is conform sales. We want to modify the QtyToReserve and/or QtyToReserveBase here.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12849.
