### ISSUE TITLE
[Event Change Request] Table 5407 - Prod. Order Component - OnBeforeAutoReserve

### ISSUE THREAD

**Issue by tvwijk** [microsoft/ALAppExtensions#24921]
Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeAutoReserve` in Table 5407 "Prod. Order Component" to be extended with the following parameter:
```al

    procedure AutoReserve()
    var
        Item: Record Item;
        FullAutoReservation: Boolean;
        IsHandled: Boolean;  // << IsHandled variable added
    begin
        if Status in [Status::Simulated, Status::Finished] then
            exit;

        TestField("Item No.");
        Item.Get("Item No.");
        IsHandled := false;   // << IsHandled variable set to false
        OnBeforeAutoReserve(Item, Rec, IsHandled); // << IsHandled parameter added
        if not IsHandled then begin // << IsHandled implementation (to ensure OnAfterAutoReserve is triggerd)
            if Item.Reserve <> Item.Reserve::Always then
                exit;

            if "Remaining Qty. (Base)" <> 0 then begin
                TestField("Due Date");
                ReservMgt.SetReservSource(Rec);
                ReservMgt.AutoReserve(FullAutoReservation, '', "Due Date", "Remaining Quantity", "Remaining Qty. (Base)");
                CalcFields("Reserved Quantity", "Reserved Qty. (Base)");
                Find();
                if not FullAutoReservation and
                (CurrFieldNo <> 0)
                then
                    if Confirm(Text99000009, true) then begin
                        Commit();
                        ShowReservation();
                        Find();
                    end;
            end;
        end; // << IsHandled implementation

        OnAfterAutoReserve(Item, Rec);
    end;

```
**Additional context**
The IsHandled parameter should be added as it is also available in other tables wich uses reservations (e.g. SalesLine, AssemblyLine etc.).  We want to stop the reservation in some cases.

**Comment by AleksandricMarko** [comment]
Hello @tvwijk 
In the procedure AutoReserve (codeunit Reservation Management) you already have an event OnBeforeAutoReserve with IsHandled pattern, which you can use to stop auto reserve.

**Comment by tvwijk** [comment]
Hi @AleksandricMarko , 

Thats correct, for now I can handle it the way you proposed but it would be more consistent (with service, sales) if the isHandled pattern is also implemented here.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13270.
