### ISSUE TITLE
[PROTECTED VAR] - Page 46, 47, 95, 96 & 6631

### ISSUE THREAD

**Issue by aismel87** [microsoft/ALAppExtensions#24923]
Hi AL Dev Team!

At Pages 46, 47, 95, 96 & 6631, we need the next VAR's as PROTECTED VAR's to be able to use them in a page extension.

```
Currency: Record Currency;
DocumentTotals: Codeunit "Document Totals";
```

![image](https://github.com/microsoft/ALAppExtensions/assets/93609371/55cf13ed-c7f2-4378-9d3f-ab99963fba39)

Thank you!

Ismael

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12965.
