### ISSUE TITLE
[Event Request] - Codeunit 22 "Item Jnl.-Post Line" - procedure OnBeforePostFlushedConsumpItemJnlLineAllocation

### ISSUE THREAD

**Issue by INNONAV** [microsoft/ALAppExtensions#24936]
**🕮 Describe the request**
For a large customer project that we need to migrate to the cloud, we need the following event/customization.

Please add the following event together with variable IsHandled for the whole customized logic on Repeat block to be added

![image](https://github.com/microsoft/ALAppExtensions/assets/62563638/15e69dac-d4ee-4d4a-b153-a84bcc18403e)

![image](https://github.com/microsoft/ALAppExtensions/assets/62563638/f05fa0fb-1d67-40b0-9d53-2cd7922064f3)

As Text:

    [IntegrationEvent(false, false)]
    local procedure OnPostFlushedConsumpOnBeforeTransferPOComToItemJnlLineAllocation(var ItemJnlLine: Record "Item Journal Line"; OldItemJnlLine: Record "Item Journal Line"; ProdOrderComp: Record "Prod. Order Component"; QtyToPost: Decimal; var PackageBuffer: Record "Item Journal Line" temporary; var TrackingPerPackageBuffer: Record "Item Journal Line" temporary; var IsPrepared: Boolean)
    begin
    end;

**Additional context**

**Comment by AleksandricMarko** [comment]
Hello @INNONAV 

same comments as for https://github.com/microsoft/ALAppExtensions/issues/24939

**Comment by tomasevics** [comment]
Closed due to inactivity.
