### ISSUE TITLE
MoveApplication / Codeunit 22 (Follow up of #24321)

### ISSUE THREAD

**Issue by donmikele75** [microsoft/ALAppExtensions#24931]
Hello @JesperSchulz,

There is another issue with "MoveApplication" in CU22 - the parameter ItemLedgerEntry is a var (reference) parameter, which is used in the calling function "TestFirstApplyItemLedgEntry".
With the introduced changes in BC22.3 this variable is no more updated by the later .Get() command:

```
local procedure MoveApplication(var ItemLedgerEntry: Record "Item Ledger Entry"; var OldItemLedgerEntry: Record "Item Ledger Entry"): Boolean
[...]
                if ItemApplicationEntry.FindSet() then begin
                    repeat
                        if not ItemApplicationEntry.Fixed() then begin
                            UnApply(ItemApplicationEntry);
                            OldItemLedgEntry.Get(OldItemLedgerEntry."Entry No.");    <-- before 22.3 "OldItemLedg" has been the var parameter

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13151.
