### ISSUE TITLE
[Event Request] - Codeunit 5520 "Get Unplanned Demand" - procedure OnCalcNeededDemandsAfterMoveUnplannedDemand

### ISSUE THREAD

**Issue by INNONAV** [microsoft/ALAppExtensions#24932]
**🕮 Describe the request**
For a large customer project that we need to migrate to the cloud, we need the following event/customization.

Please add the following event also variable AvailableInvMsgText should be added

![image](https://github.com/microsoft/ALAppExtensions/assets/62563638/5fba9981-40ae-4a72-97ca-b7a536420a22)

![image](https://github.com/microsoft/ALAppExtensions/assets/62563638/8649f961-72d4-4571-9a4d-47430b000cbc)

**Additional context**

**Comment by AleksandricMarko** [comment]
Hello @INNONAV 
What is the purpose of the new local variable AvailableInvMsgText?
From the image, it is just a variable that is passed as a parameter of the event.

Also, if may I ask you not to send the images, but copy of part of the code as it is too easier for handling and less chance to overlook something.

**Comment by AleksandricMarko** [comment]
Hi @INNONAV 

Where is the AvailableInvMsgText used in the procedure CalcNeededDemands()?
Beside it is a parameter in event publisher

**Comment by AleksandricMarko** [comment]
Closed due no activities.
