### ISSUE TITLE
[Event Request] - Codeunit 13 "Gen. Jnl.-Post Batch" - procedure OnBeforeUpdateCheckAmounts

### ISSUE THREAD

**Issue by INNONAV** [microsoft/ALAppExtensions#24930]
**🕮 Describe the request**
For a large customer project that we need to migrate to the cloud, we need the following event/customization.

Please add the following event

![image](https://github.com/microsoft/ALAppExtensions/assets/62563638/2dde7c39-322e-4ba7-bf75-3ac20434667f)

![image](https://github.com/microsoft/ALAppExtensions/assets/62563638/0fe67678-1bba-4642-880d-edb5b5cb0109)

**Additional context**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13636.
