### ISSUE TITLE
[Event Request] - Codeunit 99000854 "Inventory Profile Offsetting" - procedure OnBeforePlanItemNextStateMatchQty

### ISSUE THREAD

**Issue by INNONAV** [microsoft/ALAppExtensions#24934]
**🕮 Describe the request**
For a large customer project that we need to migrate to the cloud, we need the following event/customization.

Please add the following event together with variable CloseDemand and customized logic for that variable in PlanItemNextStateCloseSupply procedure

![image](https://github.com/microsoft/ALAppExtensions/assets/62563638/9215df06-b8af-4e36-ada9-a317b769c15c)

![image](https://github.com/microsoft/ALAppExtensions/assets/62563638/4a6fec36-4135-4c9c-9d5c-d02bca039401)

**Additional context**

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13270.
