### ISSUE TITLE
[Request for external] report 7300 "Calculate Bin Replenishment" - Protected var

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#24949]
Can you change the following variables to protected var in report 7300 "Calculate Bin Replenishment":

WhseWkshTemplateName
WhseWkshName
LocationCode
AllowBreakbulk
HideDialog
DoNotFillQtytoHandle

I need access to this for a customization.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12965.
