### ISSUE TITLE
[Event Request] Table 5092 "Opportunity" - procedure StartActivateFirstStage

### ISSUE THREAD

**Issue by Piotr-Grzybowski** [microsoft/ALAppExtensions#24942]
**🕮 Describe the request**

I tried to run the procedure 'StartActivateFirstStage()' through an API and bound action. Unfortunately, the whole procedure is packed up with a big if of confirmation dialog which without GUI returns always false. 
![image](https://github.com/microsoft/ALAppExtensions/assets/22132237/baabbed0-cc44-473c-91e8-e335e24877ed)

I tried copying code from the function to run it without that wrapper but many procedures have Scope "OnPrem" and it starts to get messy.

I can see that I can use the event 'OnAfterStartActivateFirstStage' but it doesn't solve my problem because I don't have access to the current Rec object.

**Additional context**

I need this request to be fulfilled so customers can activate and change the statuses of sales opportunities through an API or other external services like for example Power Automate.

**Comment by ABYSTREK** [comment]
+1

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12849.
