### ISSUE TITLE
[Request for external] codeunit 7308 Replenishment - FindBreakbulkBin

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#24950]
Can you change procedure FindBreakbulkBin to global in [Request for external] codeunit 7308 Replenishment?
I also need a way to set global variabl RemainQtyToReplenishBase.

Example:
```
    // >>>>>>>>>>>>>>>>
    procedure SetRemainQtyToReplenishBase(NewRemainQtyToReplenishBase: Decimal)
    begin
        RemainQtyToReplenishBase := NewRemainQtyToReplenishBase;
    end;

    //local procedure FindBreakbulkBin(ToBinContent: Record "Bin Content")
    procedure FindBreakbulkBin(ToBinContent: Record "Bin Content")
    // <<<<<<<<<<<<<<<<
    var
        FromBinContent: Record "Bin Content";
        WhseWkshLine2: Record "Whse. Worksheet Line";
        QtyAvailToTakeBase: Decimal;
        MovementQtyBase: Decimal;
    begin
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13402.
