### ISSUE TITLE
[Parameter Request] WarehouseShipmentLine to publisher OnCheckPostWhseShptLinesOnAfterWhseShptLinesFound - Codeunit 80 "Sales Post"

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#24959]
Could you please add parameter WarehouseShipmentLine to publisher  OnCheckPostWhseShptLinesOnAfterWhseShptLinesFound to Codeunit 80 "Sales Post"?
`
            OnCheckPostWhseShptLinesOnAfterWhseShptLinesFound(SalesShipmentLine, SalesLine, WhseShptLinesFound, WhseShptHeader, WhseRcptHeader, WhseShip, WhseReceive, WarehouseShipmentLine);`

```al
    [IntegrationEvent(false, false)]
    local procedure OnCheckPostWhseShptLinesOnAfterWhseShptLinesFound(var SalesShipmentLine: Record "Sales Shipment Line"; var SalesLine: Record "Sales Line"; var WhseShptLinesFound: Boolean; WarehouseShipmentHeader: Record "Warehouse Shipment Header"; WarehouseReceiptHeader: Record "Warehouse Receipt Header"; WhseShip: Boolean; WhseReceive: Boolean; var WarehouseShipmentLine: Record "Warehouse Shipment Line")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12849.
