### ISSUE TITLE
[Access Request] table 901 "Assembly Line" - StatusCheckSuspended

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#24954]
Hello. Could you please change the Access Scope of the StatusCheckSuspended: Boolean to protected?

```al
protected var
    StatusCheckSuspended: Boolean;
```

Or could you add procedure to return value of StatusCheckSuspended? For example:

```al
procedure GetStatusCheckSuspended(): Boolean
begin
    exit(StatusCheckSuspended);
end;
```

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: <None>.
