### ISSUE TITLE
[Event Request] - Table Segment Line

### ISSUE THREAD

**Issue by stephanweidmann** [microsoft/ALAppExtensions#24952]
**🕮 Describe the request**

in addition to https://github.com/microsoft/ALAppExtensions/issues/24910,

    local procedure CreateInteractionMergeData(var TempInteractionMergeData: Record "Interaction Merge Data" temporary)
    begin
        TempInteractionMergeData.Id := CreateGuid();
        TempInteractionMergeData."Contact No." := Rec."Contact No.";
        TempInteractionMergeData."Salesperson Code" := Rec."Salesperson Code";
OnAfterTransferSegmentLineToInterActionMergeData(TempInteractionMergeData, Rec);
        TempInteractionMergeData.Insert();
    end;

**Additional context**
Fill additional fields - for example, Job No. (needed for the merge of relations)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12849.
