### ISSUE TITLE
[Parameter Request] ToSalesLine to publisher OnRunOnAfterFromBOMCompSetFilters to CU "Sales-Explode BOM"

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#24958]
Could you please add parameter ToSalesLine to publisher OnRunOnBeforeExplodeBOMCompLines to CU "Sales-Explode BOM"?

`OnRunOnAfterFromBOMCompSetFilters(FromBOMComp, Rec, IsHandled, ToSalesLine);`
    
```al
[IntegrationEvent(false, false)]
    local procedure OnRunOnAfterFromBOMCompSetFilters(var BOMComponent: Record "BOM Component"; SalesLine: Record "Sales Line"; var IsHandled: Boolean; var ToSalesLine: Record "Sales Line")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12849.
