### ISSUE TITLE
[Parameter Request] BOMItemNo to publsiher OnRunOnBeforeExplodeBOMCompLines to CU "Sales-Explode BOM"

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#24957]
Could you please add parameter BOMItemNo to publisher OnRunOnBeforeExplodeBOMCompLines to CU "Sales-Explode BOM"?

`OnRunOnBeforeExplodeBOMCompLines(Rec, ToSalesLine, NoOfBOMComp, Selection, IsHandled, BOMItemNo);`

```al
    [IntegrationEvent(false, false)]
    local procedure OnRunOnBeforeExplodeBOMCompLines(var SalesLine: Record "Sales Line"; var ToSalesLine: Record "Sales Line"; var NoOfBOMComp: Integer; var Selection: Integer; var IsHandled: Boolean; var BOMItemNo: Code[20])
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12849.
