### ISSUE TITLE
[Event Request] Table 5870 "Bom Buffer" - Add parameter to OnTransferFromProdCompCopyFields

### ISSUE THREAD

**Issue by aismel87** [microsoft/ALAppExtensions#24955]
Hi AL Dev Team,

We need to add the parameter ParentScrapQtyPer to the Event OnTransferFromProdCompCopyFields.

```
Old Code:
OnTransferFromProdCompCopyFields(Rec, ProdBOMLine, ParentItem, ParentQtyPer);

New Code:
OnTransferFromProdCompCopyFields(Rec, ProdBOMLine, ParentItem, ParentQtyPer, ParentScrapQtyPer);
```

New publisher:

```
[IntegrationEvent(false, false)]
    local procedure OnTransferFromProdCompCopyFields(var BOMBuffer: Record "BOM Buffer"; ProductionBOMLine: Record "Production BOM Line"; ParentItem: Record Item; ParentQtyPer: Decimal; ParentScrapQtyPer: Decimal)
    begin
    end;

```
Thank you!

Ismael

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12849.
