### ISSUE TITLE
Modifications in local procedure InsertPurchRcptLine in codeunit 80 "Sales-Post"

### ISSUE THREAD

**Issue by marivalera** [microsoft/ALAppExtensions#24965]
Dear AL Development Team,

In codeunit 80 "Sales-Post", in procedure InsertPurchRcptLine, we need to control if a new line is inserted depending on some conditions (the same way is implemented in procedure SalesShptLineInsert for instance).

In order to achive this, we need to add a parameter ishandled and modify the subscription to event publisher OnBeforePurchRcptLineInsert. The changes needed would be these:

OLD CODE

    local procedure InsertPurchRcptLine(PurchRcptHeader: Record "Purch. Rcpt. Header"; PurchOrderLine: Record "Purchase Line"; DropShptPostBuffer: Record "Drop Shpt. Post. Buffer")
    var
        PurchRcptLine: Record "Purch. Rcpt. Line";
    begin
        with PurchRcptLine do begin
            Init();
.
.
.
            OnBeforePurchRcptLineInsert(PurchRcptLine, PurchRcptHeader, PurchOrderLine, DropShptPostBuffer, SuppressCommit);
            Insert();
            OnAfterPurchRcptLineInsert(PurchRcptLine, PurchRcptHeader, PurchOrderLine, DropShptPostBuffer, SuppressCommit, TempSalesLineGlobal);
        end;
    end;

NEW CODE

    local procedure InsertPurchRcptLine(PurchRcptHeader: Record "Purch. Rcpt. Header"; PurchOrderLine: Record "Purchase Line"; DropShptPostBuffer: Record "Drop Shpt. Post. Buffer")
    var
        PurchRcptLine: Record "Purch. Rcpt. Line";
--> begin new code
      **IsHandled:boolean**
--> end new code
    begin
        with PurchRcptLine do begin
            Init();
.
.
.
--> begin new code
           **IsHandled := false;
            OnBeforePurchRcptLineInsert(PurchRcptLine, PurchRcptHeader, PurchOrderLine, DropShptPostBuffer, SuppressCommit, TempSalesLineGlobal, IsHandled);
           if IsHandled then
             (exit);**
--> end new code
              Insert();
            OnAfterPurchRcptLineInsert(PurchRcptLine, PurchRcptHeader, PurchOrderLine, DropShptPostBuffer, SuppressCommit, TempSalesLineGlobal);
        end;
    end;

The event publisher OnBeforePurchRcptLineInsert will be modified as follows:

OLD CODE:
    [IntegrationEvent(false, false)]
    local procedure OnBeforePurchRcptLineInsert(var PurchRcptLine: Record "Purch. Rcpt. Line"; PurchRcptHeader: Record "Purch. Rcpt. Header"; PurchOrderLine: Record "Purchase Line"; DropShptPostBuffer: Record "Drop Shpt. Post. Buffer"; CommitIsSuppressed: Boolean)
    begin
    end;

NEW CODE:
    [IntegrationEvent(false, false)]
    local procedure OnBeforePurchRcptLineInsert(var PurchRcptLine: Record "Purch. Rcpt. Line"; PurchRcptHeader: Record "Purch. Rcpt. Header"; PurchOrderLine: Record "Purchase Line"; DropShptPostBuffer: Record "Drop Shpt. Post. Buffer"; CommitIsSuppressed: Boolean; **var TempSalesLineGlobal: Record "Sales Line" temporary; var IsHandled: Boolean**)
    begin
    end;

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13351.
