### ISSUE TITLE
[Event Change Request] Missing Changes with #23435 linked to #23437

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/ALAppExtensions#24961]
Dear ALAppExtensions Team:

Thank you for changing the "InheritAttributesFromItemCategory" function (#23437) in codeunit 7500 "Item Attribute Management".

In the same Event Changed Request was asked to change the **OnBefore & OnAfter** functions linked (created in #23435).

Unfortunately, this second part is not done yet. Please consider doing it asap.

**Comment by AleksandricMarko** [comment]
Hello @YvesDesrumaux 

Could you please provide us more information. As far as I can see, both events are added.

![image](https://github.com/microsoft/ALAppExtensions/assets/133204513/70e8401b-c793-4edb-b9ba-4976e5cae4f4)

**Comment by YvesDesrumaux** [comment]
Hello I do agree but the definition of the procedures are not using VAR for item record

What I would expected :
![image](https://github.com/microsoft/ALAppExtensions/assets/30075742/1f6b91ff-0c1f-4b2e-9de1-6b3606e0ac60)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13321.
