### ISSUE TITLE
Modifications in local procedure InsertShipmentLine in codeunit 80 "Sales-Post"

### ISSUE THREAD

**Issue by marivalera** [microsoft/ALAppExtensions#24963]
Dear AL Development Team

When creating a new sales shipment line in codeunit 80 "Sales-Post", we need to perform some calculations and update several customized fields that we have created in table Sales Header. In order to achive this, we need two modifications in local procedure InsertShipmentLine:

<img width="472" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/145558360/0caff126-19d0-462f-9aac-9a11b075ad9c">

We need that the parameter SalesHeader in local procedure InsertShipmentLine  is declared by reference:
 
OLD CODE:
  local procedure InsertShipmentLine(SalesHeader: Record "Sales Header"; SalesShptHeader: Record "Sales Shipment Header"; SalesLine: Record "Sales Line"; CostBaseAmount: Decimal; var TempServiceItem2: Record "Service Item" temporary; var TempServiceItemComp2: Record "Service Item Component" temporary)

NEW CODE:

  local procedure InsertShipmentLine(**var** SalesHeader: Record "Sales Header"; SalesShptHeader: Record "Sales Shipment Header"; SalesLine: Record "Sales Line"; CostBaseAmount: Decimal; var TempServiceItem2: Record "Service Item" temporary; var TempServiceItemComp2: Record "Service Item Component" temporary)

Related to this issue, we also need that parameter SalesHeader in the event publisher OnBeforeInsertShipmentLine in this same procedure is declared by reference too:

OLD CODE:
[IntegrationEvent(false, false)]
    local procedure OnBeforeInsertShipmentLine(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

NEW CODE:
[IntegrationEvent(false, false)]
    local procedure OnBeforeInsertShipmentLine(**var** SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;

Thanks in advance!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13351.
