### ISSUE TITLE
[Request Protected Var] report 1316 "Standard Statement" - Description

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#24969]
Could you add variable

Description: Text[100];

to the protected var section

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 12965.
