### ISSUE TITLE
Event request codeunit 1535 OnHasOpenApprovalEntriesForCurrentUserOnAfterApprovalEntrySetFilters

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/ALAppExtensions#24960]
can codeunit 1535 "Approvals Mgmt." be extended with an extra publisher?

**new event:**
    [IntegrationEvent(false, false)]
    local procedure OnHasOpenApprovalEntriesForCurrentUserOnAfterApprovalEntrySetFilters(var ApprovalEntry: Record "Approval Entry")
    begin
    end;
    
**called in **
in procedure HasOpenApprovalEntriesForCurrentUser before!! the first  if ApprovalEntry.IsEmpty() then

![image](https://github.com/microsoft/ALAppExtensions/assets/16033297/68b97513-13c5-48e4-af81-0aa356b041ee)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13351.
