### ISSUE TITLE
[Event Request] Codeunit 80 Sales-Post – FinalizePosting

### ISSUE THREAD

**Issue by Olli-GITHUB** [microsoft/ALAppExtensions#2496]
Dear ALAppExtensions Team,

we would like to request the following event-publisher to be added in codeunit 80 Sales-Post, FinalizePosting.

```
    UpdateAfterPosting(SalesHeader);
    UpdateEmailParameters(SalesHeader);
    UpdateWhseDocuments;
//Old Code
//    ArchiveManagement.AutoArchiveSalesDocument(SalesHeader);

// >> New Code
    OnFinalizePostingOnBeforeArchiveDocument(VAR SalesHeader,ArchiveDocNeeded); 
    IF ArchiveDocNeeded THEN
      ArchiveManagement.AutoArchiveSalesDocument(SalesHeader);
// >> New Code
    ApprovalsMgmt.DeleteApprovalEntries(RECORDID);
    IF NOT PreviewMode THEN
      DeleteAfterPosting(SalesHeader);
  END;

  InsertValueEntryRelation;
```

**Comment by AlexanderYakunin** [comment]
Are you aware what you can disable archiving in setup? Do you really need event for this?

**Comment by Olli-GITHUB** [comment]
We are archiving sales documents in our industry solution depending on a custom field in the sales header.  
The possibility to enable or disable archiving of documents in the setup is to general.
