### ISSUE TITLE
New event necesary in the Codeunit 6620 "Copy Document Mgt." in function CheckPurchRounding

### ISSUE THREAD

**Issue by MARBC** [microsoft/ALAppExtensions#24972]
Hi,
We need to do a change in in function CheckPurchRounding in Codeunit 6620 "Copy Document Mgt." . 
We hace this codeunit modified in theis way:
----------------------------------------------------------------
       PurchSetup.GET;
      IF PurchSetup."Invoice Rounding" THEN BEGIN
        //++SLB 17/04/18
        IF FromPurchLine."Pay-to Vendor No." = '' THEN
          Vendor.GET(FromPurchLine."Buy-from Vendor No.")
        ELSE
        //--SLB 17/04/18
          Vendor.GET(FromPurchLine."Pay-to Vendor No.");

----------------------------------------------------------------

In order to implement that change we should need add a new event in the funcion:

    local procedure CheckPurchRounding(FromPurchLine: Record "Purchase Line"; var RoundingLineInserted: Boolean)
    var
        PurchSetup: Record "Purchases & Payables Setup";
        Vendor: Record Vendor;
        VendorPostingGroup: Record "Vendor Posting Group";
    begin
        if (FromPurchLine.Type <> FromPurchLine.Type::"G/L Account") or (FromPurchLine."No." = '') then
            exit;
        if not FromPurchLine."System-Created Entry" then
            exit;

        PurchSetup.Get();
        if PurchSetup."Invoice Rounding" then begin
       >>>>>>> New Event <<<<<<<<
        OnBeforeGetVendor(FromPurchLine,Vendor,isGetVendor );
        if not isGetVendor then
        >>>>>>> New Event <<<<<<<<

            Vendor.Get(FromPurchLine."Pay-to Vendor No.");
            VendorPostingGroup.Get(Vendor."Vendor Posting Group");
            RoundingLineInserted := FromPurchLine."No." = VendorPostingGroup.GetInvRoundingAccount();
        end;
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
