### ISSUE TITLE
codeunit 22 "Item Jnl.-Post Line" - Function InsertCapValueEntry does not fill "Location Code" from ItemJnlLine

### ISSUE THREAD

**Issue by miracleerp** [microsoft/ALAppExtensions#24973]
The function InsertCapValueEntry creates ValueEntry record from ItemJnlLine.

It does not transfer the Location Code to the Value Entry which causes an error if there is no Inventory Posting Setup for an empty location code.

The following error will come up at posting output of a production order
The Inventory Posting Setup does not exist. Identification fields and values: Location Code='',Invt. Posting Group Code='xxx'

**Comment by AlexanderYakunin** [comment]
I am sorry, but we cannot help you with functional bugs. Please create support ticket to get it addressed.
