### ISSUE TITLE
[Change Request] codeunit 64 "Sales-Get Shipment" - CheckSalesShptLineVATBusPostingGroup

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#24983]
Hello, can you please change the lokal procedure CheckSalesShptLineVATBusPostingGroup to a global procedure?

```
    procedure CheckSalesShptLineVATBusPostingGroup(SalesShptLine: Record "Sales Shipment Line"; SalesHeader: Record "Sales Header")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeTestSalesShptLineVATBusPostingGroup(SalesShptLine, SalesHeader, IsHandled);
        if IsHandled then
            exit;

        SalesShptLine.TestField("VAT Bus. Posting Group", SalesHeader."VAT Bus. Posting Group");
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13402.
