### ISSUE TITLE
[Request for External] codeunit 5704 "TransferOrder-Post Shipment" - SetPreviewMode

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#24990]
Can you remove protected from procedure SetPreviewMode in codeunit 5704 "TransferOrder-Post Shipment"?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13402.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13402.
