### ISSUE TITLE
Event Request - Parameter by reference in table 5870 "BOM Buffer" event publisher OnAfterCalcUnitCost

### ISSUE THREAD

**Issue by marivalera** [microsoft/ALAppExtensions#24999]
Dear AL Development Team

In table 5870 "BOM Buffer" we need that in event publisher OnAfterCalcUnitCost the parameter BOMBuffer declared by reference.

OLD CODE:
   
[IntegrationEvent(false, false)]
    local procedure OnAfterCalcUnitCost(BOMBuffer: Record "BOM Buffer")
    begin
    end;

NEW CODE:

   [IntegrationEvent(false, false)]
    local procedure OnAfterCalcUnitCost(**var** BOMBuffer: Record "BOM Buffer")
    begin
    end;

Thanks in advance!

**Comment by tomasevics** [comment]
This is added and will be available from BC23.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
