### ISSUE TITLE
FieldGroups - tables "Item Reference"(5777), I need default DropDown and Brick FieldGroups

### ISSUE THREAD

**Issue by johnnpg** [microsoft/ALAppExtensions#24996]
I need extend a FieldGroups for table "Item Reference" (5777) but not possible because not have default FieldGroups .  

Could you please add the default DropDown and Brick fieldgroup to:
"Item Reference" (5777) 
Thank you in advance.

**Comment by pri-kise** [comment]
This should be possible with BC23.
https://learn.microsoft.com/en-us/dynamics365/release-plan/2023wave2/smb/dynamics365-business-central/add-new-fieldgroup-existing-table

**Comment by johnnpg** [comment]
> but not possible because not have default FieldGroups .

 but not possible because not have default FieldGroups.

**Comment by johnnpg** [comment]
> > but not possible because not have default FieldGroups .
> 
> but not possible because not have default FieldGroups.
![image](https://github.com/microsoft/ALAppExtensions/assets/6970855/ceca7b27-f3e1-49b0-80d6-2955eeb1ce56)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13730.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 13889.
