### ISSUE TITLE
[Request for External] codeunit 5706 "TransferOrder-Post (Yes/No)" - PostTransferOrder and SetPreviewMode

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#24991]
Can you change procedure PostTransferOrder and SetPreviewMode to global in codeunit 5706 "TransferOrder-Post (Yes/No)"?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13402.
