### ISSUE TITLE
[Event] codeunit 13629 "OIOUBL-Check Sales Header" , OnCheckSalesLinesOnBeforeConfirmEmptyLines

### ISSUE THREAD

**Issue by TaliaDamary** [microsoft/ALAppExtensions#24995]
Dear Developer Team, 

I would like to request an IntegrationEvent OnCheckSalesLinesOnBeforeConfirmEmptyLines:
![image](https://github.com/microsoft/ALAppExtensions/assets/146931708/0c3cfd01-0e8f-49dc-aefb-f7556212714b)

it should be placed here at the end of the CheckSalesLines procedure:
![image](https://github.com/microsoft/ALAppExtensions/assets/146931708/46f129f2-aa26-4800-985c-6b7b2d86a207)

and requires these variables to be added to local procedure CheckSalesLines:
![image](https://github.com/microsoft/ALAppExtensions/assets/146931708/2ded9637-1320-447c-9b1f-023c6262e3b1)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13791.
