### ISSUE TITLE
Forgotten Paramters after enlarging Serial No. and Lot No. to code 50

### ISSUE THREAD

**Issue by NAVRockClimber** [Microsoft/ALAppExtensions#25]
Hi,

I am not sure if am in the correct repo. 
In Table 5773 - Activity Type, Function "SetTrackingFilter" you forgot to change the parameters of the function after you changed Serial No. and Lot No. to code 50.

Current:
```
[External] SetTrackingFilter(SerialNo : Code[20];LotNo : Code[20])
```

Correct:
```
[External] SetTrackingFilter(SerialNo : Code[50];LotNo : Code[50])
```

Best regards,
Bert

**Comment by JesperSchulz** [comment]
In the fix goes! Thanks for the bug report!
