### ISSUE TITLE
[Request for External] Report 11728 "Cash Desk Book CZP" - protected var in Integer data item

### ISSUE THREAD

**Issue by jlorenc01** [microsoft/ALAppExtensions#25007]
Hi there,

could you please change the access scope of the variable TempCashDocumentHeaderCZP to protected? There is an Integer data item based on this variable and we need to access it in the trigger OnAfterAfterGetRecord() of this data item to be able to print additional data. Thank you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13461.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 13478.
