### ISSUE TITLE
Codeunit 900 "Assembly-Post"; GLEntry permissions

### ISSUE THREAD

**Issue by RIT-BAR** [microsoft/ALAppExtensions#25018]
`Assembly-Post` uses `GLEntry` in procedure `LockTables`, but this requires direct permissions to `"G/L Entry"`. Posting should be possible with only indirect permissions to `"G/L Entry"` (as with for example a sales order).
The `Permissions` property should include `TableData "G/L Entry" = r,` or the `LockTables` procedure should have inherent permissions.

Repro:
Create a user with permissions that allow them to post documents and assembly orders.
Give the user a new permission set where access to "G/L Entry" is reduced to indirect via excluding permissions.
Post an assembly order.

Result:
Sorry, the current permissions prevented the action. (TableData G/L Entry Read: Base Application)
```
AL call stack: 
"Assembly-Post"(CodeUnit 900).LockTables line 8 - Base Application by Microsoft
"Assembly-Post"(CodeUnit 900).Post line 12 - Base Application by Microsoft
"Assembly-Post"(CodeUnit 900).OnRun(Trigger) line 28 - Base Application by Microsoft
"Assembly-Post (Yes/No)"(CodeUnit 901).Code line 6 - Base Application by Microsoft
"Assembly-Post (Yes/No)"(CodeUnit 901).OnRun(Trigger) line 3 - Base Application by Microsoft
"Assembly Order"(Page 900)."P&ost - OnAction"(Trigger) line 2 - Base Application by Microsoft
```

Expected result:
Posting should succeed.

Version:
Country/region: DK
Application Version: 22.5.59966.60134

**Comment by pri-kise** [comment]
@RIT-BAR you should create a Support Case via the normal support channel to get this addressed.
This repository is mostly for event/extensibilty requests on the BaseApp.

**Comment by RIT-BAR** [comment]
Could you point me to that channel?

**Comment by RIT-BAR** [comment]
Thank you. 👍

**Comment by JakovljevicDusan** [comment]
Thanks for reporting this @RIT-BAR and @pri-kise for correct advise. @RIT-BAR, please create Support Case for this so we can fix this.
