### ISSUE TITLE
[Request for External] codeunit 6503 "Item Tracking Doc. Management" - AddTempRecordToSet

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#25014]
Can you change procedure AddTempRecordToSet to global in codeunit 6503 "Item Tracking Doc. Management"?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13402.
