### ISSUE TITLE
[Event Request] C1303 "Correct Posted Sales Invoice" extend CreateAndProcessJobPlanningLines

### ISSUE THREAD

**Issue by ChristianBouska** [microsoft/ALAppExtensions#25013]
**🕮 Describe the request**

    local procedure CreateAndProcessJobPlanningLines(SalesHeader: Record "Sales Header")
    var
        SalesLine: Record "Sales Line";
        // -new
        IsHandled: Boolean;
    // +new
    begin
        //New
        OnBeforeCreateAndProcessJobPlanningLines(SalesHeader, IsHandled);
        if IsHandled then
            exit;
        // +NEW
        SalesLine.SetRange("Document No.", SalesHeader."No.");
        SalesLine.SetRange("Document Type", SalesHeader."Document Type");
        SalesLine.SetFilter("Job Contract Entry No.", '<>0');
        if SalesLine.FindSet() then
            repeat
                SalesLine."Job Contract Entry No." := CreateJobPlanningLine(SalesHeader, SalesLine);
                SalesLine.Modify();
            until SalesLine.Next() = 0;
    end;

    // -NEW
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateAndProcessJobPlanningLines(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;
    // +NEW

**Additional context**
We have different logic to handle the creation of Job Planning Lines. Without this publisher one is forced to use the BaseApp logic.
The only possibility would be to double the actions on the page, which is bad design, if you want to rely on the remaining business  logic.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13199.
