### ISSUE TITLE
[Event Request] codeunit 5882 "Phys. Invt. Order-Reopen" - "Code"

### ISSUE THREAD

**Issue by Rihmz12** [microsoft/ALAppExtensions#25019]
I would like to request the following event:
Object: PhysInvtOrderReopen.Codeunit.al
Procedure: "Code"
Where the event should be placed:

```
                        PhysInvtOrderLine.Modify();
                    end;
                until PhysInvtOrderLine.Next() = 0;

            OnCodeOnBeforeSetStatusToOpen(PhysInvtOrderHeader);
            Status := Status::Open;
            Modify();
        end;
    end;
```

Event Code

```
    [IntegrationEvent(false, false)]
    local procedure OnCodeOnBeforeSetStatusToOpen(var PhysInvtOrderHeader: Record "Phys. Invt. Order Header")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13199.
