### ISSUE TITLE
[Protected] CurrentJnlBatchName in page 11300 Financial Journal

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#25011]
**🕮 Describe the request**

Can you please move variable `CurrentJnlBatchName` to the **protected** section in page 11300 Financial Journal? (BE localisation)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13402.
