### ISSUE TITLE
X509 XML Signing

### ISSUE THREAD

**Issue by fmoric** [microsoft/ALAppExtensions#2502]
I've been trying to sign XML through CU 6227 "Signed XML Mgt." with function SignXmlText, that you have been nice enough to write for us, but I've hit a road block (or i just don't know to use it).

Function requires "private key", and i don't see any way of getting that private key.

We have CU 3043 "DotNet_X509Certificate2" that has no external function to get private key, even if dotnet variable DotNetX509Certificate2 has privatekey method, to return private key.

To add, function that initializes CU X509Certificate2 does not work because one of the parameters is Codeunit "DotNet_X509KeyStorageFlags" that has no external functions so it cant be initialized.

So if you could be kind enough to help me solve this thing i'd be glad.

P.S. 
Another thing that i don't get is the "Isolated Certificate" or "Certificates". 
It is great, we can upload cert's to BC, see all the info, but from extensions we can't get to them, because they are in ISOLATEDSTORAGE.
As i figured only things uploaded to isolated storage form extension can be fetched in extension, so if it is uploaded from C/AL, we cant see it.

**Comment by gregoral** [comment]
The two functions below do what you need, but you first have to get the certificate into the isolated storage of the extension.

First you have to be aware of the fact that there are two tables:
T1262 "Isolated Certificate"
T2000000107 "Isolated Storage"

**"Isolated Certificate"**:
- stores information about the certificate
- is accessible to any extension
- **does not store the private key**

**"Isolated Storage"**:
- stores the private key and password
- **is only accessible to a single application/extension**

The way certificates are handled in BC is a little bit confusing at the moment.

Microsoft ( W1 ) already has certificate management built in, but your extension won't be able to touch the private key, because it is in isolated storage.

Isolated Storage prevents random extensions from getting access to private key data, which is good.

W1 has access only to W1 Isolated Storage.
ExtensionX has access only to ExtensionX Isolated Storage.
ExtensionY has access only to ExtensionY Isolated Storage.

But all of them share the information in Isolated Certificate, so I think this will be a mess, once we all start using certificates.

I can understand why this is needed, but as long as we need to get access to the private key data in extensions, this will be either:
a) confusing ( multiple copies of a private key for all extensions that need access to said private key )
b) insecure ( any extension can access the private key )

Perhaps MS could implement private key access list ( similar to the way how extensions need permission to access the web ).

Anyway I hope this helps you out.
Documentation related to certificate use in extensions is virtually non-existent.

Best regards,
Gregor

    procedure LoadCertFromIsolatedStorage(IsolatedCertificate: Record "Isolated Certificate"; var DotNet_X509Certificate2FISC: Codeunit "DotNet_X509Certificate2-AdFisc")
    var
        DotNet_X509KeyStorageFlags: Codeunit DotNet_X509KeyStorageFlags;
        DotNet_Array: Codeunit DotNet_Array;

        CertificateManagement: Codeunit "Certificate Management";
        DotNet_SecureString: Codeunit DotNet_SecureString;
        DotNet_Convert: Codeunit DotNet_Convert;
        cert64: Text;
    begin
        cert64 := CertificateManagement.GetCertAsBase64String(IsolatedCertificate);
        CertificateManagement.GetPasswordAsSecureString(DotNet_SecureString, IsolatedCertificate);
        DotNet_Convert.FromBase64String(cert64, DotNet_Array);
        DotNet_X509KeyStorageFlags.Exportable();
        DotNet_X509Certificate2FISC.X509Certificate2withSecurePassword(DotNet_Array, DotNet_SecureString, DotNet_X509KeyStorageFlags);
    end;

    procedure LoadCertificateFromIsolatedStorage(IsolatedCertificateCode: Code[20])
    begin
        IsolatedCertificate.GET(IsolatedCertificateCode);
        LoadCertFromIsolatedStorage(IsolatedCertificate, DotNet_X509Certificate2FISC);
        CertificatePrivateKey := DotNet_X509Certificate2FISC.GetCertPrivateKey();
    end;

**Comment by fmoric** [comment]
That part about Isolated Certificates (Storage) i understand, but from extension standpoint i don't see the use, and it is not the biggest worry, because as you said, it can be uploaded from extension.

Really my question was about XML signing, if it is possible from extension, and if it is, how?

I need it to send XML to TA, which is integral part of local functionality.

**Comment by gregoral** [comment]
procedure MySignXml(InputText: Text; IsolatedCertificateCode: Code[20]): Text;

    var
        SignXmlMgmt: Codeunit "Signed XML Mgt.";
        SignedXmlText: Text;
    begin
        CertificatePrivateKey := LoadCertificateFromIsolatedStorage(IsolatedCertificateCode);
        SignedXmlText := SignedXmlTextSignXmlMgmt.SignXmlText(InputText, CertificatePrivateKey);
        exit(SignedXmlText);
    end;

**Comment by fmoric** [comment]
Yes, fiskalizacija. :)

I found all needed components to create it but some functions are not external. I want to do it without touching source code.

**Comment by gregoral** [comment]
Did you solve the issue with connecting to https servers thet identify with self signed certificate?
Eg. test server certificate is signed by a self issued certificate?

**Comment by fmoric** [comment]
No, but i saw that issue somewhere, about security in HTTPClient.

I send echo to test server and it worked.

**Comment by ikoletic** [comment]
This issue is a question. Please submit your questions on [business central community ](https://community.dynamics.com/business/f/758) or on [BC development yammer groups](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035).

**Comment by tomasevicstefan** [comment]
> I've been trying to sign XML through CU 6227 "Signed XML Mgt." with function SignXmlText, that you have been nice enough to write for us, but I've hit a road block (or i just don't know to use it).
> 
> Function requires "private key", and i don't see any way of getting that private key.
> 
> We have CU 3043 "DotNet_X509Certificate2" that has no external function to get private key, even if dotnet variable DotNetX509Certificate2 has privatekey method, to return private key.
> 
> To add, function that initializes CU X509Certificate2 does not work because one of the parameters is Codeunit "DotNet_X509KeyStorageFlags" that has no external functions so it cant be initialized.
> 
> So if you could be kind enough to help me solve this thing i'd be glad.
> 
> P.S.
> Another thing that i don't get is the "Isolated Certificate" or "Certificates".
> It is great, we can upload cert's to BC, see all the info, but from extensions we can't get to them, because they are in ISOLATEDSTORAGE.
> As i figured only things uploaded to isolated storage form extension can be fetched in extension, so if it is uploaded from C/AL, we cant see it.

Did you find any suitable solution for using certificate from your extension?
Can we take that certificate before/after it is inserted into Isolated Certificate/Storage and save it within scope of our extension?

**Comment by p15-6117** [comment]
> The two functions below do what you need, but you first have to get the certificate into the isolated storage of the extension.
> 
> First you have to be aware of the fact that there are two tables: T1262 "Isolated Certificate" T2000000107 "Isolated Storage"
> 
> **"Isolated Certificate"**:
> 
> * stores information about the certificate
> * is accessible to any extension
> * **does not store the private key**
> 
> **"Isolated Storage"**:
> 
> * stores the private key and password
> * **is only accessible to a single application/extension**
> 
> On top of that the certificate might be locked to a "specific user", "specific company" or even "specific user in specific company".
> 
> The way certificates are handled in BC is a little bit confusing at the moment.
> 
> Microsoft ( W1 ) already has certificate management built in, but your extension won't be able to touch the private key, because it is in isolated storage.
> 
> Isolated Storage prevents random extensions from getting access to private key data, which is good.
> 
> W1 has access only to W1 Isolated Storage. ExtensionX has access only to ExtensionX Isolated Storage. ExtensionY has access only to ExtensionY Isolated Storage.
> 
> But all of them share the information in Isolated Certificate, so I think this will be a mess, once we all start using certificates.
> 
> I can understand why this is needed, but as long as we need to get access to the private key data in extensions, this will be either: a) confusing ( multiple copies of a private key for all extensions that need access to said private key ) b) insecure ( any extension can access the private key )
> 
> Perhaps MS could implement private key access list ( similar to the way how extensions need permission to access the web ).
> 
> Anyway I hope this helps you out. Documentation related to certificate use in extensions is virtually non-existent.
> 
> Best regards, Gregor
> 
> ```
> procedure LoadCertFromIsolatedStorage(IsolatedCertificate: Record "Isolated Certificate"; var DotNet_X509Certificate2: Codeunit "DotNet_X509Certificate2")
> var
>     DotNet_X509KeyStorageFlags: Codeunit DotNet_X509KeyStorageFlags;
>     DotNet_Array: Codeunit DotNet_Array;
> 
>     CertificateManagement: Codeunit "Certificate Management";
>     DotNet_SecureString: Codeunit DotNet_SecureString;
>     DotNet_Convert: Codeunit DotNet_Convert;
>     cert64: Text;
> begin
>     cert64 := CertificateManagement.GetCertAsBase64String(IsolatedCertificate);
>     CertificateManagement.GetPasswordAsSecureString(DotNet_SecureString, IsolatedCertificate);
>     DotNet_Convert.FromBase64String(cert64, DotNet_Array);
>     DotNet_X509KeyStorageFlags.Exportable();
>     DotNet_X509Certificate2FISC.X509Certificate2withSecurePassword(DotNet_Array, DotNet_SecureString, DotNet_X509KeyStorageFlags);
> end;
> 
> procedure LoadCertificateFromIsolatedStorage(IsolatedCertificateCode: Code[20])
> var
>     DotNet_X509Certificate2: Codeunit "DotNet_X509Certificate2"
> begin
>     IsolatedCertificate.GET(IsolatedCertificateCode);
>     LoadCertFromIsolatedStorage(IsolatedCertificate, DotNet_X509Certificate2);
>     CertificatePrivateKey := DotNet_X509Certificate2FISC.GetCertPrivateKey();
> end;
> ```

I couldn't find **GetCertPrivateKey()** in AL BC V19. Can you please tell where can I find this method. Thank you.
