### ISSUE TITLE
[Change Request] codeunit 442 "Sales-Post Prepayments" - procedure PrepmtDocTypeToDocType

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#25035]
Hello, can you please set the lokal procedure PrepmtDocTypeToDocType to global?

```
    procedure PrepmtDocTypeToDocType(DocumentType: Option Invoice,"Credit Memo"): Integer
    begin
        case DocumentType of
            DocumentType::Invoice:
                exit(2);
            DocumentType::"Credit Memo":
                exit(3);
        end;
        exit(2);
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13402.
