### ISSUE TITLE
Request to move Code in "Sales & Purch. Alloc. Acc. Mgt." to another Subscriber (BC23)

### ISSUE THREAD

**Issue by SandroKiedis** [microsoft/ALAppExtensions#25044]
Hello :)

I would like you to move the following code from the "OnBeforePostSalesDoc" / "OnBeforePostPurchaseDoc" Subscribers to another (later) event in the process.
![image](https://github.com/microsoft/ALAppExtensions/assets/47424839/68e725a2-ba35-4365-bbd9-2556d51deaa1)
![image](https://github.com/microsoft/ALAppExtensions/assets/47424839/fd83ac83-9b8b-453b-ac1c-af57835d8bc1)

We subscribed to this Eventsubscriber to let the user input any changes to Posting/Document/VAT Dates via Modal Page before posting (if GuiAllowed of course). Which worked fine for every BC Version before V23. Our app has been published into the MarketPlace for years now as well without facing any problems up until now. With your new Code we are not able to run ModalPages anymore. Yes, we could commit the data, but this is always a risk.
In my opinion these transactions in the Alloc. Acc. Mgt. Codeunits should be carried out AFTER the Sales / Purchase Prechecks in CU 80 and 90.
I really don't believe that we are the only partner facing this problem with BC23...

Please consider moving these transactions to a later point in the posting process. 
Please keep me updated in any case :)

**Comment by pri-kise** [comment]
We have similiar code, but we currently use the events inside the "Yes/No" codeunits.
Normally these codeunits are executed before the Purch./Post, Sales/Post

**Comment by JesperSchulz** [comment]
Internally closed as "Won't Fix" in 2023. Syncing state to GitHub.
If this issue persists, kindly create a new one to have us take another look at it.
