### ISSUE TITLE
Codeunit 3711 Translation new procedure 'ShowModal(...)'

### ISSUE THREAD

**Issue by IanSchofieldDeloitte** [microsoft/ALAppExtensions#25054]
**🕮 Describe the issue**

The codeunit 3711 Translation (with codeunit 3712 "Translation Implementation") has the procedure Show and ShowForAllRecords. Would it be a good idea to have similar procedures but for the TranslationPage.RunModal(), returning the [Action](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/action/action-option) from the procedure?

We have implemented the language translation functionality for a table via an action in a page which calls _Translation.Show(...)_ .  The client would also like certain commonly used languages on the page for quick updating which we have implemented with page variables.  

**📣 Expected behavior**
The issue we can see is that closing the page (_Translation.Show(...)_) from the action is not immediately updating the fields (page variables) on the parent page. The Show procedure does not run a page modally and adding a _CurrPage.Update()_ on the following line would execute immediately after the Show procedure call.

Regards
```[tasklist]
### Tasks
```

**Comment by pri-kise** [comment]
@IanSchofieldDeloitte why not?

I recently added a new property for the the Show function, to check the field length for the translation if set via UI.
https://github.com/microsoft/ALAppExtensions/pull/24667

I think you have a valid reason for this request and as long as you're willing to  provide some tests as well, then I think you can create the PR.

**Comment by JesperSchulz** [comment]
That change would have to be made in the System Application though, which is on https://github.com/microsoft/BCApps. If you'd like to make a contribution, please create a new issue, have it triaged and you can create a PR 😊
