### ISSUE TITLE
Page "simplifiction" gone wrong

### ISSUE THREAD

**Issue by hemisphera** [microsoft/ALAppExtensions#2505]
The "No." field on sales & purchase (among others) pages is not visible, if you have only one number series defined for the related document. This causes the first field on the page to be the customer (or vendor) number and therefore the first field that gets validated when creating a new document. At this point however, the document is not yet inserted and therefore it has not yet gotten a number.

It is quite commong to copy detail data from the customer (or vendor) to the document, whenever the customer is validated. This obviously happens at a moment, where do not yet have the document number and therefore are unable to copy data correctly.

This issue is nonexistant if you have two or more number series defined for a particular document, as that causes "No." to be visible, and to be able to get to insert the customer, you need to move focus, which triggers the insert and the assignment of the document number.

Apart from the fact that this is inconsistent behaviour for no valid reason, it also is the cause for a critical issue in a standard CRONUS database with italian localzation. Payment lines are created when the customer is validated, but when "No." is not visible, they are not created and it needs to be fixed manually.

**Comment by RomanZanizdra** [comment]
Hi @hemisphera .
Sorry, but it's not fully clear what are your expectations/suggestions and so on? If there is a bug in any version then please reach out relevant support channel.

**Comment by hemisphera** [comment]
OK, so let me iterate:
- Don't remove fields just for the sake of removing them when there is no real benefit to it.
- If you decide to do, please make sure you don't break things.
