### ISSUE TITLE
[Event request] table 77 "Report Selections" - OnAfterSaveReportAsPDF

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#25068]
Can you add ReportUsage to event OnAfterSaveReportAsPDF in table 77 "Report Selections". It has already been added to OnBeforeSaveReportAsPDF.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13192.
