### ISSUE TITLE
[Access Request]  report 2 "General Journal - Test"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#25062]
**🕮 Describe the request**

Could you please change the access scope of the following global variable to protected?
```al
protected var
        ShowDim: Boolean;
        GLAccNetChange: Record "G/L Account Net Change" temporary;
```

**Additional context**

We would like to to add a new colum in the DataSet with the variable `GLAccNetChange`.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13402.
