### ISSUE TITLE
XmlDocument.WriteTo always adds a declaration header. Request for omitDeclaration boolean parameter

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25063]
XMLDocument: XmlDocument;
XMLContentText: Text

When for example the XMLDocument contains below created message

        <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
            <s:Body s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                <q1:ExecuteTrigger xmlns:q1="http://tempuri.org/">
                    <text xsi:type="xsd:string">
                        01;Crate 5x6;.\printfile.prn
                    </text>
                    <wait xsi:type="xsd:boolean">true</wait>
                </q1:ExecuteTrigger>
            </s:Body>
        </s:Envelope>

and you use the AL statement:

XMLDocument.WriteTo(XMLContentText);

the variable XMLContentText does not contain the exact same message but

?xml version="1.0" encoding="utf8" standalone="yes"?

is added as declaration header. When communicating with other software this is not always accepted.

The request is: Can you add another XMLDocument method WriteTo with an extra parameter boolean value omitDeclaration

XMLDocument.WriteTo(XMLContentText, true);

**Comment by pri-kise** [comment]
@Duizy1971 you're on the wrong place for platform improvements.

You should better create an idea at https://aka.ms/bcideas to add support the XmlWriter property (https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmlwritersettings.omitxmldeclaration?view=net-7.0).

Afterwards share this idea here, on https://aka.ms/bcyammer and on other places to gather votes for this platform feature.
