### ISSUE TITLE
[Request for External] - Report Items per Job - Variable TempJobBuffer

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#25079]
Could tempjobbuffer and TempJobBuffer2 be made protected?

![image](https://github.com/microsoft/ALAppExtensions/assets/35260264/4ff0f319-80a2-42f4-949a-320ca4cec389)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13402.
