### ISSUE TITLE
Filter missing in OnAfterGetCurrRecord Page 9305 "Sales Order List".

### ISSUE THREAD

**Issue by camadorsummar** [microsoft/ALAppExtensions#25077]
Good morning,

We have a customer in BC 23 SaaS and he has quite a few records in table 36. To our surprise, in BC 23 version is calling the SetFilterToMultipleValues function with a variable called FilteredSalesHeader, which is never filtered, so when it is processed inside the function it goes through all the records in table 36 instead of only, in this case, the records of type Order.

I think this is an error and that the variable needs to be filtered by document type.

 ```
 trigger OnAfterGetCurrRecord()
    var
        FilteredSalesHeader: Record "Sales Header";
        CRMCouplingManagement: Codeunit "CRM Coupling Management";
    begin
        SetControlVisibility();
        CurrPage.IncomingDocAttachFactBox.PAGE.LoadDataFromRecord(Rec);

        if CRMIntegrationEnabled then
            CRMIsCoupledToRecord := CRMCouplingManagement.IsRecordCoupledToCRM(Rec.RecordId);

#if not CLEAN21
        // Contextual Power BI FactBox: send data to filter the report in the FactBox
        CurrPage."Power BI Report FactBox".PAGE.SetCurrentListSelection(Rec."No.", false, PowerBIVisible);
#endif
        // NEW LINE
        FilteredSalesHeader.SetRange("Document Type", "Document Type");
        //
        CurrPage.PowerBIEmbeddedReportPart.PAGE.SetFilterToMultipleValues(FilteredSalesHeader, FilteredSalesHeader.FieldNo("No."));
    end;
```

Thank you.
![micorosft](https://github.com/microsoft/ALAppExtensions/assets/67145347/4f2bc5c3-1e3b-4496-9eeb-6f27a58ea3e5)

**Comment by JakovljevicDusan** [comment]
@camadorsummar, thanks for reporting this.

This reported issue is linked to task for https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=2481357637435392&search_origin=global&scoring=linear1Y-prankie-group-private-higher&match=any-exact&search_sort=relevance&page=1&search=Upgrade%20v23%20-%20bug and I will close it now as a duplicate. 
There will be fix for it.
