### ISSUE TITLE
OAuth2 Authorization Code Flow with PKCE

### ISSUE THREAD

**Issue by domingosbarreto** [microsoft/ALAppExtensions#25082]
**🕮 Describe the issue**

Provide support for Authorization Code Flow with PKCE by adding overloads or procedures to codeunit 501 OAuth2 and codeunit 502 OAuth2Impl.

**📣 Expected behavior**

If an external party requires Authorization Code Flow with PKCE there is no method that allows to add additional query parmeters to the authorization URL.

The intention of this issue is to add overloads or procedures to provide functionality to allow the OAuth2 flow with `code_verifier` and `code_challenge` parameters.

**Comment by pri-kise** [comment]
@domingosbarreto if you're planning to solve this by yourself and contribute this to the system application then you should mention this in the issue.

**Comment by JesperSchulz** [comment]
Sorry to be sending you around. We're in the middle of redoing our contribution story. The good news: the system application has now landed on its final destination, which is https://github.com/microsoft/BCApps. If you would like to contribute with this issue to the system application, please create an issue in the BCApps repo and we will triage it.

**Comment by pri-kise** [comment]
Just for Reference: Someone created an issue at the BCApps repository now: https://github.com/microsoft/BCApps/issues/787
