### ISSUE TITLE
Add Contact table as explicit permission in SegManagement

### ISSUE THREAD

**Issue by monicasuica** [microsoft/ALAppExtensions#25087]
Hi!

In our solution the Interaction Log Entries are created via api post calls and we need limited permissions sets for the user.
Now it fails because it needs direct persmission ti read data from the Contact table.

To solve this problem a solution would be to add Contact table as explicit permission in the SegManagement codeunit:
codeunit 5051 SegManagement
{
    Permissions = TableData "Interaction Log Entry" = rimd,
                  tabledata "Interaction Template" = r,
                  tabledata Contact = r;   // new

Thank you!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13730.
