### ISSUE TITLE
[Request for External] Remove OnPrem from ProcessPaymReceived() in Codeunit: "Financial Interface Telebank"

### ISSUE THREAD

**Issue by JohanvdHeijden** [microsoft/ALAppExtensions#25085]
In order to be able to change target to cloud, please remove the scope OnPrem from the following function:

Codeunit: 11000001 "Financial Interface Telebank"

[Scope('OnPrem')]
procedure ProcessPaymReceived(var GenJnlLine: Record "Gen. Journal Line"; var PaymentHistLine: Record "Payment History Line"; CBGStatementline: Record "CBG Statement Line")

Thank you
Johan van der Heijden

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13402.
