### ISSUE TITLE
[EVENT REQUEST] - Table 840 "Cash Flow Forecast" - Function CalcAmount()

### ISSUE THREAD

**Issue by Luisarfu** [microsoft/ALAppExtensions#25089]
Dear AL Development Team,

In Table 840 "Cash Flow Forecast", function CalcAmount, we need an event here:
![image](https://github.com/microsoft/ALAppExtensions/assets/145032178/24b66b35-e9e6-493e-99b3-55d406b812f7)

```
//OLD CODE
procedure CalcAmount(): Decimal
begin
	CalcFields("Amount (LCY)");
	exit("Amount (LCY)");
end;

//NEW CODE
procedure CalcAmount(): Decimal
begin
	//Init New Code
	OnBeforeCalcAmount(Rec);
	//End New Code
	CalcFields("Amount (LCY)");
	exit("Amount (LCY)");
end;
```

New publisher:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeCalcAmount(var Rec: Record "Cash Flow Forecast")
begin
end;
```

Thank you.

Luis.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13321.
