### ISSUE TITLE
[BUG] Can not assign Job No to Purchase Line when the Purchase Order was generated by Requisition Worksheets from Job Planning Line

### ISSUE THREAD

**Issue by m2mal** [microsoft/ALAppExtensions#25094]
There is impossible to assign Job No to Purchase Line when the Purchase Order was generated by Requisition Worksheets from needs from Job Planning Line
It's a logical error in the purchase order in the context of assigning job to the purchase line:
In the OnValidate() trigger on field 45 "Job No." there is a function
```
if CheckReservationForJobNo() then
                     TestField("Job No.", '');
```
The problem is that it blocks not only reservation, **but also tracking.**

Please do not block tracking records. If the purchase line was created by a requisition journal that detected that some item was needed on the Job Planning Line, tracking lines are created and this is OK. It is natural that we want to post such a purchase to the appropriate job task.

Due to the above, also reservation records should not be blocked - because if the reservation is made for certain job, it is obvious and natural, that we will want to book the purchase item for this job.

1. Create new item with type "inventory" and setup it as material.
2. On this item, setup "Reording Policy" as "Order"
3. Create new Job for any customer, create Job Task and Job Planning Line for created Item for some quantity
4. Open Requisition Worksheets and run "Calculate Plan" with starting and ending same as date you entered in Job Planning Line
5. Run command "Cary out action message" to crete purchase order
6. Open the purchase order, go to lines an try assign created Job No.

**📣 Expected behavior**
We should assigne Job No to Purchase line, even if it was generated by the Requisition Worksheets, and even if it was reserved or tracked, as long as the reservation or tracking is for the same job.

Plese check the behavior to allow job assigment to purchase lines generated by Requisition Worksheets from Job Planning Line.

My proposition:
Checking whether the purchase line has not been reserved should be based on the "Order Tracking Entry" table, because it links the demand source (here, job planing line) with the method of supply (here, purchase line). The "Reservation Entry" table does not have this functionality.
```
    local procedure CheckReservationForJobNo(): Boolean
    var
        OrderTrackingEntry: Record "Order Tracking Entry";
        isHandled: Boolean;
        Result: Boolean;
    begin
        OnBeforeCheckReservationForJobNo(Rec, isHandled, Result);
        if isHandled then
            exit(Result);

        OrderTrackingEntry.SetRange("For Type", rec.RecordId.TableNo);
        OrderTrackingEntry.SetRange("For Subtype", rec."Document Type");
        OrderTrackingEntry.SetRange("For ID", rec."Document No.");
        OrderTrackingEntry.SetRange("For Ref. No.", rec."Line No.");

        OrderTrackingEntry.SetRange("From Type", Database::"Job Planning Line");
        OrderTrackingEntry.SetFilter("From ID", '<>%1|%2', Rec."Job No.", '');
        exit(not OrderTrackingEntry.IsEmpty);
    end;
```
**Screenshots**

![image](https://github.com/microsoft/ALAppExtensions/assets/20379506/69b3cc3c-f0f6-46c9-a67b-6484b8d0ff97)
![image](https://github.com/microsoft/ALAppExtensions/assets/20379506/ffde0692-3aea-4c5c-aef7-ea5a743b4e9b)
![image](https://github.com/microsoft/ALAppExtensions/assets/20379506/96778fdc-7e6b-404f-bf9c-a08f0d828bb6)

**Comment by JakovljevicDusan** [comment]
Hi @m2mal,

Thanks for reporting this, but this is not the right channel for fixing functional bugs. This repository is only for extensibility requests for Dynamics 365 Business Central.

Please report this bug via https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/technical-support#summary-of-where-to-file-bugs-and-issues, so dedicated teams can process it.
