### ISSUE TITLE
[Event Request] Add new Event in local procedure PostOutputAdjmtBuf in standard codeunit 5895 "Inventory Adjustment" implements "Inventory Adjustment"

### ISSUE THREAD

**Issue by margolui** [microsoft/ALAppExtensions#25099]
Hello.
Need new Event in local procedure PostOutputAdjmtBuf in standard codeunit 5895 "Inventory Adjustment" implements "Inventory Adjustment"
The Version: W1 22.1 (Platform 22.0.56380.0 + Application 15.0.36560.36649)
Function:
'
   
    local procedure PostOutputAdjmtBuf(var TempAvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point" temporary)
    // NEW >>
    var
        IsHandled: Boolean;
    // NEW <<
    begin
        with TempInvtAdjmtBuf do begin
            Reset();
            if FindSet() then
                repeat
                    // NEW >>
                    IsHandled := false;
                    OnBeforePostOutput(InvtSetup, TempInvtAdjmtBuf, TempAvgCostAdjmtEntryPoint, IsHandled);
                    if not IsHandled then
                        // NEW <<
                        PostOutput(TempInvtAdjmtBuf, TempAvgCostAdjmtEntryPoint);
                until Next() = 0;
            DeleteAll();
        end;
    end;
'

signature
'
[IntegrationEvent(false, false)]
    procedure OnBeforePostOutput(InvtSetup: Record "Inventory Setup"; var TempInvtAdjmtBuf: Record "Inventory Adjustment Buffer" temporary; var TempAvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point" temporary; var IsHandled: Boolean);
    begin
    end;
'

**Comment by tomasevics** [comment]
Hi,

Do you need publisher before loop, at the beginning of the procedure to skip whole logic, or you need event inside loop?

I don't think that it is a good practice to raise publisher on every rec in loop.
