### ISSUE TITLE
[Event Request] Add new Event in local procedure InitializeAdjmt in standard codeunit 5895 "Inventory Adjustment" implements "Inventory Adjustment" 

### ISSUE THREAD

**Issue by margolui** [microsoft/ALAppExtensions#25096]
Hello.
Need new Event in local procedure InitializeAdjmt in standard codeunit 5895 "Inventory Adjustment" implements "Inventory Adjustment" 
The Version: W1 22.1 (Platform 22.0.56380.0 + Application 15.0.36560.36649)
Function:

'

    local procedure InitializeAdjmt()
    begin
        Clear(LevelNo);
        MaxLevels := 100;
        WindowUpdateDateTime := CurrentDateTime;
        if not IsOnlineAdjmt then

            OpenWindow();
        Clear(ItemJnlPostLine);
        ItemJnlPostLine.SetCalledFromAdjustment(true, PostToGL);

        InvtSetup.Get();
        GLSetup.Get();

        OnInitializeAdjmt(GLSetup, InvtSetup, DimensionValueBuffer, LastDim2Value);

        PostingDateForClosedPeriod := GLSetup.FirstAllowedPostingDate();
        GetAddReportingCurrency();

        SourceCodeSetup.Get();

        ItemCostMgt.SetProperties(true, 0);
        TempJobToAdjustBuf.DeleteAll();
    end;
'
signature

'

[IntegrationEvent(false, false)]
    procedure OnInitializeAdjmt(GLSetup: Record "General Ledger Setup"; InvtSetup: Record "Inventory Setup"; var DimensionValueBuffer: Record "Dimension Value" temporary; var LastDim2Value: Code[20]);
    begin
    end;

'

**Comment by margolui** [comment]
@AleksandricMarko thanks for the answer

**Comment by AleksandricMarko** [comment]
Hi @margolui 
Are you going to close this request (probably several more that you created also for BC22) or you want to update events and we to implement them in BC23?
