### ISSUE TITLE
[Event Request] Add new Events in local procedure AdjustAppliedOutbndEntries in standard codeunit 5895 "Inventory Adjustment" implements "Inventory Adjustment"

### ISSUE THREAD

**Issue by margolui** [microsoft/ALAppExtensions#25097]
Hello.
We need new Events in local procedure AdjustAppliedOutbndEntries in standard codeunit 5895 "Inventory Adjustment" implements "Inventory Adjustment"
AdjustAppliedOutbndEntries
The Version: W1 22.1 (Platform 22.0.56380.0 + Application 15.0.36560.36649)

Function:
'

    local procedure AdjustAppliedOutbndEntries(OutbndItemLedgEntryNo: Integer; Recursion: Boolean; var InboundCompletelyInvoiced: Boolean): Boolean
        var
        OutbndItemLedgEntry: Record "Item Ledger Entry";
        OutbndValueEntry: Record "Value Entry";
        TempOutbndCostElementBuf: Record "Cost Element Buffer" temporary;
        TempOldCostElementBuf: Record "Cost Element Buffer" temporary;
        TempAdjustedCostElementBuf: Record "Cost Element Buffer" temporary;
        ItemApplnEntry: Record "Item Application Entry";
        StandardCostMirroring: Boolean;
        ExpectedCost: Boolean;
    begin
        OutbndItemLedgEntry.Get(OutbndItemLedgEntryNo);
        if Item."Costing Method" = Item."Costing Method"::Standard then
            StandardCostMirroring := UseStandardCostMirroring(OutbndItemLedgEntry);

        CalcOutbndCost(TempOutbndCostElementBuf, TempAdjustedCostElementBuf, OutbndItemLedgEntry, Recursion);

        with OutbndValueEntry do begin
            Reset();
            SetCurrentKey("Item Ledger Entry No.", "Document No.", "Document Line No.");
            SetRange("Item Ledger Entry No.", OutbndItemLedgEntryNo);
            for ExpectedCost := true downto false do begin
                SetRange("Expected Cost", ExpectedCost);
                if FindSet() then
                    repeat
                        if not (Adjustment or ExpCostIsCompletelyInvoiced(OutbndItemLedgEntry, OutbndValueEntry)) and
                           Inventoriable
                        then begin
                            SetRange("Document No.", "Document No.");
                            SetRange("Document Line No.", "Document Line No.");
                            CalcOutbndDocOldCost(
                              TempOldCostElementBuf, OutbndValueEntry,
                              OutbndItemLedgEntry.IsExactCostReversingPurchase() or OutbndItemLedgEntry.IsExactCostReversingOutput());
                             
                             OnBeforeCalcCostPerUnit(DimensionValueBuffer, OutbndValueEntry, InvtSetup);

                            CalcCostPerUnit(OutbndValueEntry, TempOutbndCostElementBuf, OutbndItemLedgEntry.Quantity);

                            if not "Expected Cost" then begin
                                TempOldCostElementBuf.GetElement("Cost Entry Type"::"Direct Cost", "Cost Variance Type"::" ");
                                "Invoiced Quantity" := TempOldCostElementBuf."Invoiced Quantity";
                                "Valued Quantity" := TempOldCostElementBuf."Invoiced Quantity";
                            end;

                            CalcOutbndDocNewCost(
                              TempAdjustedCostElementBuf, TempOutbndCostElementBuf,
                              OutbndValueEntry, OutbndItemLedgEntry.Quantity);

                            if "Expected Cost" then begin
                                TempOldCostElementBuf.GetElement(TempOldCostElementBuf.Type::Total, TempOldCostElementBuf."Variance Type"::" ");
                                TempAdjustedCostElementBuf."Actual Cost" := TempAdjustedCostElementBuf."Actual Cost" - TempOldCostElementBuf."Expected Cost";
                                TempAdjustedCostElementBuf."Actual Cost (ACY)" :=
                                  TempAdjustedCostElementBuf."Actual Cost (ACY)" - TempOldCostElementBuf."Expected Cost (ACY)";
                            end else begin
                                TempOldCostElementBuf.GetElement("Entry Type"::"Direct Cost", "Cost Variance Type"::" ");
                                TempAdjustedCostElementBuf."Actual Cost" := TempAdjustedCostElementBuf."Actual Cost" - TempOldCostElementBuf."Actual Cost";
                                TempAdjustedCostElementBuf."Actual Cost (ACY)" :=
                                  TempAdjustedCostElementBuf."Actual Cost (ACY)" - TempOldCostElementBuf."Actual Cost (ACY)";
                            end;

                            if StandardCostMirroring and not "Expected Cost" then
                                CreateCostAdjmtBuf(
                                  OutbndValueEntry, TempAdjustedCostElementBuf, OutbndItemLedgEntry."Posting Date", "Entry Type"::Variance)
                            else
                                CreateCostAdjmtBuf(
                                  OutbndValueEntry, TempAdjustedCostElementBuf, OutbndItemLedgEntry."Posting Date", "Entry Type");

                            if not "Expected Cost" then begin
                                CreateIndirectCostAdjmt(TempOldCostElementBuf, TempAdjustedCostElementBuf, OutbndValueEntry, "Entry Type"::"Indirect Cost");
                                CreateIndirectCostAdjmt(TempOldCostElementBuf, TempAdjustedCostElementBuf, OutbndValueEntry, "Entry Type"::Variance);
                            end;
                            FindLast();
                            SetRange("Document No.");
                            SetRange("Document Line No.");
                        end;
                    until Next() = 0;
            end;

            // Update transfers, consumptions
            if IsUpdateCompletelyInvoiced(
                 OutbndItemLedgEntry, TempOutbndCostElementBuf."Inbound Completely Invoiced")
            then
                OutbndItemLedgEntry.SetCompletelyInvoiced();

            ForwardAppliedCostRecursion(OutbndItemLedgEntry);
            
            IsHandled := false;
            OnPreSetInbuntToUpdate(DimensionValueBuffer, LastDim2Value, IsHandled);
            if not IsHandled then
            
            ItemApplnEntry.SetInboundToUpdated(OutbndItemLedgEntry);

            InboundCompletelyInvoiced := TempOutbndCostElementBuf."Inbound Completely Invoiced";
            exit(OutbndItemLedgEntry."Completely Invoiced");
        end;
    end;
'
New publishers:
'
[IntegrationEvent(false, false)]
    procedure OnBeforeCalcCostPerUnit(var DimensionValueBuffer: Record "Dimension Value" temporary; var ValueEntry: Record "Value Entry"; InvSetup: Record "Inventory Setup");
    begin
    end;
'
'
[IntegrationEvent(false, false)]
    procedure OnPreSetInbuntToUpdate(DimensionValueBuffer: Record "Dimension Value" temporary; LastDim2Value: Code[20]; var IsHandled: Boolean);
    begin
    end;
'

**Comment by tomasevics** [comment]
Hi,

I don't see "Dimension Value" table in this codeunit. Can't you check if your request is valid?

**Comment by tomasevics** [comment]
Closed due to inactivity.
