### ISSUE TITLE
[Event Change Request] Table 36 "Sales Header" - OnRecreateSalesLinesHandleSupplementTypesOnAfterCreateSalesLine

### ISSUE THREAD

**Issue by ViktorasDanielius** [microsoft/ALAppExtensions#25091]
Please make  TempSalesLine parameter as VAR on OnRecreateSalesLinesHandleSupplementTypesOnAfterCreateSalesLine event on Table 36 "Sales Header":
```
    [IntegrationEvent(false, false)]
    local procedure OnRecreateSalesLinesHandleSupplementTypesOnAfterCreateSalesLine(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; 
             VAR TempSalesLine: Record "Sales Line" temporary)
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13321.
