### ISSUE TITLE
[Event Request] Add new Events in local procedures: CalcTransEntryOldCost, CalcItemApplnEntryOldCost, CalcInbndDocOldCost, CalcInbndEntryAdjustedCost, CalcOutbndDocOldCost, CalcTransEntryNewRevAmt, CalcTransEntryOldRevAmt in standard codeunit 5895 "Inventory Adjustment" implements "Inventory Adjustment"

### ISSUE THREAD

**Issue by margolui** [microsoft/ALAppExtensions#25098]
Hello.
We need new Events in local procedures: CalcTransEntryOldCost, CalcItemApplnEntryOldCost, CalcInbndDocOldCost, CalcInbndEntryAdjustedCost, CalcOutbndDocOldCost, CalcTransEntryNewRevAmt, CalcTransEntryOldRevAmt in standard codeunit 5895 "Inventory Adjustment" implements "Inventory Adjustment"

The Version: W1 22.1 (Platform 22.0.56380.0 + Application 15.0.36560.36649)
Function:

Function 1:

'

    local procedure CalcTransEntryOldCost(var CostElementBuf: Record "Cost Element Buffer"; var TransValueEntry: Record "Value Entry"; ItemLedgEntryNo: Integer)
    var
        TransValueEntry2: Record "Value Entry";
        IsHandled: Boolean;
    begin
        Clear(CostElementBuf);
        with CostElementBuf do begin
            TransValueEntry2 := TransValueEntry;
            TransValueEntry.SetCurrentKey("Item Ledger Entry No.", "Entry Type");
            TransValueEntry.SetRange("Item Ledger Entry No.", ItemLedgEntryNo);
            TransValueEntry.SetRange("Entry Type", TransValueEntry."Entry Type"::"Direct Cost");
            TransValueEntry.Find('+');
            repeat
                if TransValueEntry."Item Charge No." = '' then begin
                // NEW >>
                    IsHandled := false;
                    OnBeforeUpdateIVECost(DimensionValueBuffer, TransValueEntry, TempInvtAdjmtBuf, InvtSetup, IsHandled);
                    if not IsHandled then
                // NEW <<
                        if TempInvtAdjmtBuf.Get(TransValueEntry."Entry No.") then
                            TransValueEntry.AddCost(TempInvtAdjmtBuf);
                    "Actual Cost" := "Actual Cost" + TransValueEntry."Cost Amount (Actual)";
                    "Actual Cost (ACY)" := "Actual Cost (ACY)" + TransValueEntry."Cost Amount (Actual) (ACY)";
                    TransValueEntry2 := TransValueEntry;
                end;
            until TransValueEntry.Next(-1) = 0;
            TransValueEntry := TransValueEntry2;
        end;
    end;
'

Function 2:
'
    
    local procedure CalcItemApplnEntryOldCost(var OldCostElementBuf: Record "Cost Element Buffer"; OutbndItemLedgEntry: Record "Item Ledger Entry"; ItemApplnEntryQty: Decimal)
    var
        OutbndValueEntry: Record "Value Entry";
        ShareOfExpectedCost: Decimal;
        IsHandled: Boolean;
    begin
        ShareOfExpectedCost :=
          (OutbndItemLedgEntry.Quantity - OutbndItemLedgEntry."Invoiced Quantity") / OutbndItemLedgEntry.Quantity;
         Clear(OldCostElementBuf);
        with OldCostElementBuf do begin
            OutbndValueEntry.SetCurrentKey("Item Ledger Entry No.");
            OutbndValueEntry.SetRange("Item Ledger Entry No.", OutbndItemLedgEntry."Entry No.");
            OutbndValueEntry.FindSet();
            repeat
                // NEW >>
                IsHandled := false;
                OnBeforeUpdateIVECost(DimensionValueBuffer, OutbndValueEntry, TempInvtAdjmtBuf, InvtSetup, IsHandled);
                if not IsHandled then
                    // NEW <<
                    if TempInvtAdjmtBuf.Get(OutbndValueEntry."Entry No.") then
                        OutbndValueEntry.AddCost(TempInvtAdjmtBuf);
                if OutbndValueEntry."Expected Cost" then begin
                    "Actual Cost" := "Actual Cost" + OutbndValueEntry."Cost Amount (Expected)" * ShareOfExpectedCost;
                    "Actual Cost (ACY)" := "Actual Cost (ACY)" + OutbndValueEntry."Cost Amount (Expected) (ACY)" * ShareOfExpectedCost;
                end else begin
                    "Actual Cost" := "Actual Cost" + OutbndValueEntry."Cost Amount (Actual)";
                    "Actual Cost (ACY)" := "Actual Cost (ACY)" + OutbndValueEntry."Cost Amount (Actual) (ACY)";
                end;
            until OutbndValueEntry.Next() = 0;

            RoundActualCost(
              ItemApplnEntryQty / OutbndItemLedgEntry.Quantity,
              GLSetup."Amount Rounding Precision", Currency."Amount Rounding Precision");
        end;
    end;

'

Function 3:
'
    
     local procedure CalcInbndDocOldCost(InbndValueEntry: Record "Value Entry"; var CostElementBuf: Record "Cost Element Buffer")
     var
        IsHandled: Boolean;
    begin
        CostElementBuf.DeleteAll();
        InbndValueEntry.SetCurrentKey("Item Ledger Entry No.", "Document No.");
        InbndValueEntry.SetRange("Item Ledger Entry No.", InbndValueEntry."Item Ledger Entry No.");
        InbndValueEntry.SetRange("Document No.", InbndValueEntry."Document No.");
        InbndValueEntry.SetRange("Document Line No.", InbndValueEntry."Document Line No.");
        with CostElementBuf do
            repeat
                if (InbndValueEntry."Entry Type" = InbndValueEntry."Entry Type"::"Direct Cost") and
                   (InbndValueEntry."Item Charge No." = '')
                then begin
                    // NEW >>
                    IsHandled := false;
                    OnBeforeUpdateIVECost(DimensionValueBuffer, InbndValueEntry, TempInvtAdjmtBuf, InvtSetup, IsHandled);
                    if not IsHandled then
                        // NEW <<
                        if TempInvtAdjmtBuf.Get(InbndValueEntry."Entry No.") then
                            InbndValueEntry.AddCost(TempInvtAdjmtBuf);
                    if InbndValueEntry."Expected Cost" then
                        AddExpectedCostElement("Cost Entry Type"::"Direct Cost", "Cost Variance Type"::" ", InbndValueEntry."Cost Amount (Expected)", InbndValueEntry."Cost Amount (Expected) (ACY)")
                    else begin
                        AddActualCostElement("Cost Entry Type"::"Direct Cost", "Cost Variance Type"::" ", InbndValueEntry."Cost Amount (Actual)", InbndValueEntry."Cost Amount (Actual) (ACY)");
                        if InbndValueEntry."Invoiced Quantity" <> 0 then begin
                            "Invoiced Quantity" := "Invoiced Quantity" + InbndValueEntry."Invoiced Quantity";
                            if not Modify() then
                                Insert();
                        end;
                    end;
                end;
            until InbndValueEntry.Next() = 0;
    end;
'
Function 4:

'
    
    local procedure CalcInbndEntryAdjustedCost(var AdjustedCostElementBuf: Record "Cost Element Buffer"; ItemApplnEntry: Record "Item Application Entry"; OutbndItemLedgEntryNo: Integer; InbndItemLedgEntryNo: Integer; ExactCostReversing: Boolean; Recursion: Boolean) CompletelyInvoiced: Boolean
    var
        InbndValueEntry: Record "Value Entry";
        InbndItemLedgEntry: Record "Item Ledger Entry";
        QtyNotInvoiced: Decimal;
        ShareOfTotalCost: Decimal;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalcInbndEntryAdjustedCost(AdjustedCostElementBuf, ItemApplnEntry, OutbndItemLedgEntryNo, InbndItemLedgEntryNo, ExactCostReversing, Recursion, CompletelyInvoiced, IsHandled);
        if not IsHandled then begin
            AdjustedCostElementBuf.DeleteAll();
            with InbndValueEntry do begin
                InbndItemLedgEntry.Get(InbndItemLedgEntryNo);
                SetCurrentKey("Item Ledger Entry No.");
                SetRange("Item Ledger Entry No.", InbndItemLedgEntryNo);
                QtyNotInvoiced := InbndItemLedgEntry.Quantity - InbndItemLedgEntry."Invoiced Quantity";
                FindSet();
                repeat
                    if IncludedInCostCalculation(InbndValueEntry, OutbndItemLedgEntryNo) and
                       not ExpCostIsCompletelyInvoiced(InbndItemLedgEntry, InbndValueEntry)
                    then begin
                       // NEW >>
                        IsHandled := false;
                        OnBeforeUpdateIVECost(DimensionValueBuffer, InbndValueEntry, TempInvtAdjmtBuf, InvtSetup, IsHandled);
                        if not IsHandled then
                            // NEW <<
                            if TempInvtAdjmtBuf.Get("Entry No.") then
                                AddCost(TempInvtAdjmtBuf);
                        case true of
                            IsInterimRevaluation(InbndValueEntry):
                                begin
                                    ShareOfTotalCost := InbndItemLedgEntry.Quantity / "Valued Quantity";
                                    AdjustedCostElementBuf.AddActualCostElement(
                                      AdjustedCostElementBuf.Type::"Direct Cost", AdjustedCostElementBuf."Variance Type"::" ",
                                      ("Cost Amount (Expected)" + "Cost Amount (Actual)") * ShareOfTotalCost,
                                      ("Cost Amount (Expected) (ACY)" + "Cost Amount (Actual) (ACY)") * ShareOfTotalCost);
                                end;
                            "Expected Cost":
                                begin
                                    ShareOfTotalCost := QtyNotInvoiced / "Valued Quantity";
                                    AdjustedCostElementBuf.AddActualCostElement(
                                      AdjustedCostElementBuf.Type::"Direct Cost", AdjustedCostElementBuf."Variance Type"::" ",
                                      "Cost Amount (Expected)" * ShareOfTotalCost,
                                      "Cost Amount (Expected) (ACY)" * ShareOfTotalCost);
                                end;
                            "Partial Revaluation":
                                begin
                                    ShareOfTotalCost := InbndItemLedgEntry.Quantity / "Valued Quantity";
                                    AdjustedCostElementBuf.AddActualCostElement(
                                      AdjustedCostElementBuf.Type::"Direct Cost", AdjustedCostElementBuf."Variance Type"::" ",
                                      "Cost Amount (Actual)" * ShareOfTotalCost,
                                      "Cost Amount (Actual) (ACY)" * ShareOfTotalCost);
                                end;
                            ("Entry Type".AsInteger() <= "Entry Type"::Revaluation.AsInteger()) or not ExactCostReversing:
                                AdjustedCostElementBuf.AddActualCostElement(
                                  AdjustedCostElementBuf.Type::"Direct Cost", AdjustedCostElementBuf."Variance Type"::" ",
                                  "Cost Amount (Actual)", "Cost Amount (Actual) (ACY)");
                            "Entry Type" = "Entry Type"::"Indirect Cost":
                                AdjustedCostElementBuf.AddActualCostElement(
                                  AdjustedCostElementBuf.Type::"Indirect Cost", AdjustedCostElementBuf."Variance Type"::" ",
                                  "Cost Amount (Actual)", "Cost Amount (Actual) (ACY)");
                            else
                                AdjustedCostElementBuf.AddActualCostElement(
                                  AdjustedCostElementBuf.Type::Variance, AdjustedCostElementBuf."Variance Type"::" ",
                                  "Cost Amount (Actual)", "Cost Amount (Actual) (ACY)");
                        end;
                    end;
                until Next() = 0;

                CalcNewAdjustedCost(AdjustedCostElementBuf, ItemApplnEntry.Quantity / InbndItemLedgEntry.Quantity);

                if AdjustAppliedCostEntry(ItemApplnEntry, InbndItemLedgEntryNo, Recursion) then
                    TempRndgResidualBuf.AddAdjustedCost(
                      ItemApplnEntry."Inbound Item Entry No.",
                      AdjustedCostElementBuf."Actual Cost", AdjustedCostElementBuf."Actual Cost (ACY)",
                      ItemApplnEntry."Output Completely Invd. Date" <> 0D);
            end;
            CompletelyInvoiced := InbndItemLedgEntry."Completely Invoiced";
        end;

        OnAfterCalcInbndEntryAdjustedCost(AdjustedCostElementBuf, InbndValueEntry, InbndItemLedgEntry, ItemApplnEntry, OutbndItemLedgEntryNo, CompletelyInvoiced);
    end;
'
Function 5:
'
    
    local procedure CalcOutbndDocOldCost(var CostElementBuf: Record "Cost Element Buffer"; OutbndValueEntry: Record "Value Entry"; ExactCostReversing: Boolean)
    var
        ValueEntry: Record "Value Entry";
        IsHandled: Boolean;
    begin
        CostElementBuf.DeleteAll();
        with ValueEntry do begin
            SetCurrentKey("Item Ledger Entry No.", "Document No.", "Document Line No.");
            SetRange("Item Ledger Entry No.", OutbndValueEntry."Item Ledger Entry No.");
            SetRange("Document No.", OutbndValueEntry."Document No.");
            SetRange("Document Line No.", OutbndValueEntry."Document Line No.");
            FindSet();
            repeat
                 // NEW >>
                IsHandled := false;
                OnBeforeUpdateIVECost(DimensionValueBuffer, ValueEntry, TempInvtAdjmtBuf, InvtSetup, IsHandled);
                if not IsHandled then
                    // NEW <<
                    if TempInvtAdjmtBuf.Get("Entry No.") then
                        AddCost(TempInvtAdjmtBuf);
                CostElementBuf.AddExpectedCostElement(
                  CostElementBuf.Type::Total, "Cost Variance Type"::" ", "Cost Amount (Expected)", "Cost Amount (Expected) (ACY)");
                if not "Expected Cost" then
                    case true of
                        ("Entry Type".AsInteger() <= "Entry Type"::Revaluation.AsInteger()) or not ExactCostReversing:
                            begin
                                CostElementBuf.AddActualCostElement(
                                  CostElementBuf.Type::"Direct Cost", CostElementBuf."Variance Type"::" ",
                                  "Cost Amount (Actual)", "Cost Amount (Actual) (ACY)");
                                if "Invoiced Quantity" <> 0 then begin
                                    CostElementBuf."Invoiced Quantity" := CostElementBuf."Invoiced Quantity" + "Invoiced Quantity";
                                    if not CostElementBuf.Modify() then
                                        CostElementBuf.Insert();
                                end;
                            end;
                        "Entry Type" = "Entry Type"::"Indirect Cost":
                            CostElementBuf.AddActualCostElement(
                              CostElementBuf.Type::"Indirect Cost", CostElementBuf."Variance Type"::" ",
                              "Cost Amount (Actual)", "Cost Amount (Actual) (ACY)");
                        else
                            CostElementBuf.AddActualCostElement(
                              CostElementBuf.Type::Variance, CostElementBuf."Variance Type"::" ",
                              "Cost Amount (Actual)", "Cost Amount (Actual) (ACY)");
                    end;
            until Next() = 0;
            CostElementBuf.CalcSums("Actual Cost", "Actual Cost (ACY)");
            CostElementBuf.AddActualCostElement(
              CostElementBuf.Type::Total, "Cost Variance Type"::" ", CostElementBuf."Actual Cost", CostElementBuf."Actual Cost (ACY)");
        end;
    end;
'
Function 6
'
    
    local procedure CalcTransEntryNewRevAmt(ItemLedgEntry: Record "Item Ledger Entry"; TransValueEntry: Record "Value Entry"; var AdjustedCostElementBuf: Record "Cost Element Buffer")
    var
        ValueEntry: Record "Value Entry";
        InvdQty: Decimal;
        OrigInvdQty: Decimal;
        ShareOfRevExpAmt: Decimal;
        OrigShareOfRevExpAmt: Decimal;
        IsHandled: Boolean;
    begin
        with ValueEntry do begin
            SetCurrentKey("Item Ledger Entry No.", "Entry Type");
            SetRange("Item Ledger Entry No.", ItemLedgEntry."Entry No.");
            SetRange("Entry Type", "Entry Type"::"Direct Cost");
            SetRange("Item Charge No.", '');
            if FindSet() then
                repeat
                    InvdQty := InvdQty + "Invoiced Quantity";
                    if "Entry No." < TransValueEntry."Entry No." then
                        OrigInvdQty := OrigInvdQty + "Invoiced Quantity";
                until Next() = 0;
            ShareOfRevExpAmt := (ItemLedgEntry.Quantity - InvdQty) / ItemLedgEntry.Quantity;
            OrigShareOfRevExpAmt := (ItemLedgEntry.Quantity - OrigInvdQty) / ItemLedgEntry.Quantity;
        end;
        // NEW >>
        IsHandled := false;
        OnBeforeUpdateIVECost(DimensionValueBuffer, TransValueEntry, TempInvtAdjmtBuf, InvtSetup, IsHandled);
        if not IsHandled then
            // NEW <<
            if TempInvtAdjmtBuf.Get(TransValueEntry."Entry No.") then
                TransValueEntry.AddCost(TempInvtAdjmtBuf);
        AdjustedCostElementBuf."Actual Cost" := Round(
            (ShareOfRevExpAmt - OrigShareOfRevExpAmt) * TransValueEntry."Cost Amount (Actual)", GLSetup."Amount Rounding Precision");
        AdjustedCostElementBuf."Actual Cost (ACY)" := Round(
            (ShareOfRevExpAmt - OrigShareOfRevExpAmt) *
            TransValueEntry."Cost Amount (Actual) (ACY)", Currency."Amount Rounding Precision");
    end;
'
Function 7:

'
   
    local procedure CalcTransEntryOldRevAmt(TransValueEntry: Record "Value Entry"; var CostElementBuf: Record "Cost Element Buffer")
    var
        IsHandled: Boolean;
    begin
        Clear(CostElementBuf);
      with CostElementBuf do begin
            TransValueEntry.SetCurrentKey("Item Ledger Entry No.", "Entry Type");
            TransValueEntry.SetRange("Item Ledger Entry No.", TransValueEntry."Item Ledger Entry No.");
            TransValueEntry.SetRange("Entry Type", TransValueEntry."Entry Type"::Revaluation);
            TransValueEntry.SetRange("Applies-to Entry", TransValueEntry."Entry No.");
            if TransValueEntry.FindSet() then
                repeat
                    //NEW >>
                    IsHandled := false;
                    OnBeforeUpdateIVECost(DimensionValueBuffer, TransValueEntry, TempInvtAdjmtBuf, InvtSetup, IsHandled);
                    if not IsHandled then
                        //NEW <<
                        if TempInvtAdjmtBuf.Get(TransValueEntry."Entry No.") then
                            TransValueEntry.AddCost(TempInvtAdjmtBuf);
                    "Actual Cost" := "Actual Cost" + TransValueEntry."Cost Amount (Actual)";
                    "Actual Cost (ACY)" := "Actual Cost (ACY)" + TransValueEntry."Cost Amount (Actual) (ACY)";
                until TransValueEntry.Next() = 0;
        end;
    end;
'

New publisher:

'
[IntegrationEvent(false, false)]
    procedure OnBeforeUpdateIVECost(var DimensionValueBuffer: Record "Dimension Value" temporary; var TransValueEntry: Record "Value Entry"; var TempInvtAdjmtBuf: Record "Inventory Adjustment Buffer" temporary; InvSetup: Record "Inventory Setup"; var IsHandled: Boolean);
    begin
    end;
'

**Comment by tomasevics** [comment]
Not valid request. Dimension Value record doesn't exist in _Inventory Adjustment_ codeunit.
