### ISSUE TITLE
codeunit 8617 "Config. Validate Management" EvaluateTextToFieldRefCodeText procedure limited to 1024 Characters

### ISSUE THREAD

**Issue by yannstlo** [microsoft/ALAppExtensions#25095]
**🕮 Describe the issue**

There are 2 text var declared in this procedure. Both of them are set to Text[1024].
I believe, this was not updated after the April 2019 release of Business Central and should be upgrade to Text[2048].

**🔧 To Reproduce**

Using the Configuration Packages, try to import more than 1024 characters into a text field that supports more than 1024 characters.

**📣 Expected behavior**

**Screenshots**

![image](https://github.com/microsoft/ALAppExtensions/assets/9088189/40915612-8eeb-4669-9708-63403117d995)

**Additional context**

none

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13658.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 13708.
