### ISSUE TITLE
[Event Request] Add new Event in local procedure RestoreValuesFromBuffers in standard codeunit 5895 "Inventory Adjustment" implements "Inventory Adjustment"

### ISSUE THREAD

**Issue by margolui** [microsoft/ALAppExtensions#25105]
Hello,

Could you add an event in local procedure RestoreValuesFromBuffers in standard codeunit 5895 "Inventory Adjustment" implements "Inventory Adjustment".

Function:
'
    
    local procedure RestoreValuesFromBuffers(var OutbndCostElementBuf: Record "Cost Element Buffer"; var AdjustedCostElementBuf: Record "Cost Element Buffer"; OutbndItemLedgEntryNo: Integer): Boolean
    begin
        with TempValueEntryCalcdOutbndCostBuf do begin
            Reset();
            // NEW >>
            OnBeforeResoreValuesFromBuffers(TempValueEntryCalcdOutbndCostBuf, DimensionValueBuffer);
            // NEW <<
            SetRange("Item Ledger Entry No.", OutbndItemLedgEntryNo);
            if IsEmpty() then
                exit(false);
            FindSet();
            CopyValueEntryBufToCostElementBuf(OutbndCostElementBuf, TempValueEntryCalcdOutbndCostBuf);

            Next();
            repeat
                CopyValueEntryBufToCostElementBuf(AdjustedCostElementBuf, TempValueEntryCalcdOutbndCostBuf);
            until Next() = 0;
        end;

        exit(true);
    end;
'
Event publisher
'
[IntegrationEvent(false, false)]
    local procedure OnBeforeResoreValuesFromBuffers(var ValueEntry: Record "Value Entry"; DimensionValueBuffer: Record "Dimension Value" temporary);
    begin
    end;
'

**Comment by AleksandricMarko** [comment]
Hello @margolui 
Please review this (and several more) event request as variable DimensionValueBuffer not exist.
Be aware that we are adding new events just in the latest BC version (BC23 currently)

**Comment by tomasevics** [comment]
Closed due to inactivity.
