### ISSUE TITLE
change access modifier in local procedure PostOutputAdjmtBuf in standard codeunit 5895 "Inventory Adjustment" implements "Inventory Adjustment"

### ISSUE THREAD

**Issue by margolui** [microsoft/ALAppExtensions#25104]
Hello.
We need to change access modifier in local procedure PostOutputAdjmtBuf in standard codeunit 5895 "Inventory Adjustment" implements "Inventory Adjustment"
The Version: W1 22.1 (Platform 22.0.56380.0 + Application 15.0.36560.36649)
Now function:
'
    
    local procedure PostOutputAdjmtBuf(var TempAvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point" temporary)
    begin
        with TempInvtAdjmtBuf do begin
            Reset();
            if FindSet() then
                repeat
                    PostOutput(TempInvtAdjmtBuf, TempAvgCostAdjmtEntryPoint);
                until Next() = 0;
            DeleteAll();
        end;
    end;
'
New function:
'

    procedure PostOutputAdjmtBuf(var TempAvgCostAdjmtEntryPoint: Record "Avg. Cost Adjmt. Entry Point" temporary)
    begin
        with TempInvtAdjmtBuf do begin
            Reset();
            if FindSet() then
                repeat
                    PostOutput(TempInvtAdjmtBuf, TempAvgCostAdjmtEntryPoint);
                until Next() = 0;
            DeleteAll();
        end;
    end;
'

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13402.
