### ISSUE TITLE
[Event Request] - Purchase Line - InitDeferralCode

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#25109]
Could these events be added

    procedure InitDeferralCode()
    var
        Item: Record Item;
        Resource: Record Resource;
        GLAccount: Record "G/L Account";
        DeferralCode: Code[10];
    begin

        if "Document Type" in
           ["Document Type"::Order, "Document Type"::Invoice, "Document Type"::"Credit Memo", "Document Type"::"Return Order"]
        then
            case Type of
                Type::"G/L Account":
                    begin
                        GLAccount.Get("No.");
                        //NewCode
                        DeferralCode := GLAccount."Default Deferral Template Code";
                        OnInitDeferralCodeOnBeforeValidateGLAccountDeferralCode(Rec,`GLAccount,DeferralCode);
                        //NewCode
                        Validate("Deferral Code", DeferralCode);
                    end;
                Type::Item:
                    begin
                        GetItem(Item);
                        //NewCode
                        DeferralCode := Item."Default Deferral Template Code";
                        OnInitDeferralCodeOnBeforeValidateItemDeferralCode(Rec,Item,DeferralCode);
                        //NewCode
                        Validate("Deferral Code", DeferralCode);
                    end;
                Type::Resource:
                    begin
                        GetResource(Resource);
                        //NewCode
                        DeferralCode := Resource."Default Deferral Template Code";
                        OnInitDeferralCodeOnBeforeValidateResourceItemDeferralCode(Rec,Resource,DeferralCode);
                        //NewCode
                        Validate("Deferral Code", DeferralCode);
                    end;
            end;
    end;

//Events
    [IntegrationEvent(false, false)]
    local procedure OnInitDeferralCodeOnBeforeValidateGLAccountDeferralCode(var PurchaseLine: Record "Purchase Line";Item:Record Item;var DeferralCode:Code[10])
    begin
    end;

     [IntegrationEvent(false, false)]
    local procedure OnInitDeferralCodeOnBeforeValidateItemDeferralCode(var PurchaseLine: Record "Purchase Line";Item:Record Item;var DeferralCode:Code[10])
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnInitDeferralCodeOnBeforeValidateResourceItemDeferralCode(var PurchaseLine: Record "Purchase Line";Item:Record Item;var DeferralCode:Code[10])
    begin
    end;    
//Events

**Comment by AleksandricMarko** [comment]
For this purpose, it is already added OnBeforeInitDeferralCode publisher.

![image](https://github.com/microsoft/ALAppExtensions/assets/133204513/16319d46-cfcf-45c1-8f45-ce3748b76c96)
