### ISSUE TITLE
RefreshOnActivate in "Inventory Picks" (9316) and "Inventory Put-aways" (9315) pages

### ISSUE THREAD

**Issue by TriangleSPV** [microsoft/ALAppExtensions#25103]
In other issues as https://github.com/microsoft/ALAppExtensions/issues/17516 I requested to add as standard the following property in the requested pages.

**RefreshOnActivate = true;**

This only can be done by standard because we cannot extend this property.

Thank you

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13682.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: <None>.
