### ISSUE TITLE
codeunit 5700 "User Setup Management" extra parameter "Document Type" to GetLocation and change IntegrationEvent

### ISSUE THREAD

**Issue by renevanbeekum** [microsoft/ALAppExtensions#25119]
Add extra parameter to procedures GetLocation and OnBeforeGetLocation "Document Type" of type Option
For sales is this quote, order etc.

Changes:
    //procedure GetLocation(DocType: Option Sales,Purchase,Service; AccLocation: Code[10]; RespCenterCode: Code[10]) LocationCode: Code[10] //Old
    procedure GetLocation(DocType: Option Sales,Purchase,Service; AccLocation: Code[10]; RespCenterCode: Code[10]; DocumentType: Option) LocationCode: Code[10] //New
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        //OnBeforeGetLocation(DocType, AccLocation, RespCenterCode, LocationCode, IsHandled); //Old
        OnBeforeGetLocation(DocType, AccLocation, RespCenterCode, LocationCode, IsHandled, DocumentType); //New
        if IsHandled then
            exit(LocationCode);

        case DocType of
            DocType::Sales:
                UserRespCenter := GetSalesFilter();
            DocType::Purchase:
                UserRespCenter := GetPurchasesFilter();
            DocType::Service:
                UserRespCenter := GetServiceFilter();
        end;
        if UserRespCenter <> '' then
            RespCenterCode := UserRespCenter;
        if RespCenter.Get(RespCenterCode) then
            if RespCenter."Location Code" <> '' then
                UserLocation := RespCenter."Location Code";
        if AccLocation <> '' then
            exit(AccLocation);

        exit(UserLocation);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetLocation(DocType: Option Sales,Purchase,Service; AccLocation: Code[10]; RespCenterCode: Code[10]; var LocationCode: Code[10]; var IsHandled: Boolean) //Old
    local procedure OnBeforeGetLocation(DocType: Option Sales,Purchase,Service; AccLocation: Code[10]; RespCenterCode: Code[10]; var LocationCode: Code[10]; var IsHandled: Boolean; DocumentType: Option) //New
    begin
    end;

Off cause te changes wher this routine is used, belowe a example for the Sales Header

    procedure UpdateLocationCode(LocationCode: Code[10])
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateLocationCode(Rec, LocationCode, IsHandled);
        if not IsHandled then
            //Validate("Location Code", UserSetupMgt.GetLocation(0, LocationCode, "Responsibility Center")); //Old
            Validate("Location Code", UserSetupMgt.GetLocation(0, LocationCode, "Responsibility Center", "Document Type")); //New
    end;

Internal work item: [AB#489297](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/489297)

**Comment by tomasevics** [comment]
Hi, 

This is a breaking change. We are not able to add parameter in public procedure. Try to change request, so it can be aligned with coding guidelines.

**Comment by renevanbeekum** [comment]
Proposed new changes, so no breaking change.:

    procedure GetLocation(DocType: Option Sales,Purchase,Service; AccLocation: Code[10]; RespCenterCode: Code[10]) LocationCode: Code[10]
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetLocation(DocType, AccLocation, RespCenterCode, LocationCode, IsHandled);
        if IsHandled then
            exit(LocationCode);

        exit(GetLocation(DocType, AccLocation, RespCenterCode, -1));
    end;

    procedure GetLocation(DocType: Option Sales,Purchase,Service; AccLocation: Code[10]; RespCenterCode: Code[10]; DocumentType: Integer) LocationCode: Code[10] //New
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetLocationDocumentType(DocType, DocumentType, AccLocation, RespCenterCode, LocationCode, IsHandled); //New
        if IsHandled then
            exit(LocationCode);

        case DocType of
            DocType::Sales:
                UserRespCenter := GetSalesFilter();
            DocType::Purchase:
                UserRespCenter := GetPurchasesFilter();
            DocType::Service:
                UserRespCenter := GetServiceFilter();
        end;
        if UserRespCenter <> '' then
            RespCenterCode := UserRespCenter;
        if RespCenter.Get(RespCenterCode) then
            if RespCenter."Location Code" <> '' then
                UserLocation := RespCenter."Location Code";
        if AccLocation <> '' then
            exit(AccLocation);

        exit(UserLocation);
    end;


    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetLocation(DocType: Option Sales,Purchase,Service; AccLocation: Code[10]; RespCenterCode: Code[10]; var LocationCode: Code[10]; var IsHandled: Boolean)
    begin
    end;

     //New Begin
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetLocationDocumentType(DocType: Option Sales,Purchase,Service; DocumentType: Integer; AccLocation: Code[10]; RespCenterCode: Code[10]; var LocationCode: Code[10]; var IsHandled: Boolean)
    begin
    end;
     //New End



Off cause te changes wher this routine is used, belowe a example for the Sales Header. Do this change also in Purchase and Service 

    procedure UpdateLocationCode(LocationCode: Code[10])
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateLocationCode(Rec, LocationCode, IsHandled);
        if not IsHandled then
            //Validate("Location Code", UserSetupMgt.GetLocation(0, LocationCode, "Responsibility Center")); //Old
            Validate("Location Code", UserSetupMgt.GetLocation(0, LocationCode, "Responsibility Center", "Document Type".AsInteger())); //New
    end;

**Comment by AlexanderYakunin** [comment]
Field Document Type in Sales, Purchases and Services modules use different enums and therefore different values.  We should not use Options anymore and combine this all together, instead we should obsolete these procedures and add new ones like GetSalesLocation, GetPurchaseLocation and GetServiceLocation. Request reclassified to Extensibility Enhancement.
