### ISSUE TITLE
[Event Request] table 36 "Sales Header" - OnBeforeLookupSellToContactNo

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#25114]
Can you add a parameter to event OnBeforeLookupSellToContactNo in table 36 "Sales Header" to be able to set the return value.

```
    procedure SelltoContactLookup(): Boolean
    var
        Contact: Record Contact;
        ContactBusinessRelation: Record "Contact Business Relation";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        // >>>>>>>>>>>>>>>>>
        //OnBeforeLookupSellToContactNo(Rec, xRec, IsHandled);
        //if IsHandled then
        //    exit;
        OnBeforeLookupSellToContactNo(Rec, xRec, IsHandled, ReturnValue);
        if IsHandled then
            exit(ReturnValue);
        // <<<<<<<<<<<<<<<<

        if "Sell-to Customer No." <> '' then
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13599.
