### ISSUE TITLE
[Event Request] New parameter for OnCreateInvLinesOnAfterReturnRcptLine2SetFilters in codeunit 6638 "Sales-Get Return Receipts"

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#25113]
Hello, please add the `SalesHeader` as a parameter to `OnCreateInvLinesOnAfterReturnRcptLine2SetFilters` passing it by var (as it's done in the specular `codeunit 64 "Sales-Get Shipment"`)

```
    [IntegrationEvent(false, false)]
    local procedure OnCreateInvLinesOnAfterReturnRcptLine2SetFilters(var ReturnReceiptLine: Record "Return Receipt Line"; var SalesHeader: Record "Sales Header")
    begin
    end;
```

```
    procedure CreateInvLines(var ReturnRcptLine2: Record "Return Receipt Line")
    var
        DifferentCurrencies: Boolean;
        ShouldInsertReturnRcptLine: Boolean;
    begin
        with ReturnRcptLine2 do begin
            SetFilter("Return Qty. Rcd. Not Invd.", '<>0');
            OnCreateInvLinesOnAfterReturnRcptLine2SetFilters(ReturnRcptLine2, SalesHeader);
            if Find('-') then begin
            [...]
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13411.
