### ISSUE TITLE
[Event Request] New parameter for OnCreateInvLinesOnAfterReturnShptLine2SetFilters in codeunit 6648 "Purch.-Get Return Shipments"

### ISSUE THREAD

**Issue by f0ffee** [microsoft/ALAppExtensions#25112]
Hello, please add the `PurchaseHeader` as a parameter to `OnCreateInvLinesOnAfterReturnShptLine2SetFilters` passing it by var (as it's done in the specular `codeunit 74 "Purch.-Get Receipt"`)

```
    [IntegrationEvent(false, false)]
    local procedure OnCreateInvLinesOnAfterReturnShptLine2SetFilters(var ReturnShipmentLine: Record "Return Shipment Line"; var PurchHeader: Record "Purchase Header")
    begin
    end;
```

```
    procedure CreateInvLines(var ReturnShptLine2: Record "Return Shipment Line")
    var
        DifferentCurrencies: Boolean;
        ShouldInsertReturnRcptLine: Boolean;
    begin
        with ReturnShptLine2 do begin
            SetFilter("Return Qty. Shipped Not Invd.", '<>0');
            OnCreateInvLinesOnAfterReturnShptLine2SetFilters(ReturnShptLine2, PurchHeader);
            if Find('-') then begin
            [...]
```

Thanks!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13411.
