### ISSUE TITLE
[Event Request] Codeunit 5530 "Calc. Item Availability" – GetPlanningEntries

### ISSUE THREAD

**Issue by DennyHW** [microsoft/ALAppExtensions#25120]
In functions ParentIsInPlanning and GetPlanningTransDemand we need to have new events to add custom filters to "Requisition Line" record as you did in function GetPlanningLines()

Existing code: 
![immagine](https://github.com/microsoft/ALAppExtensions/assets/53569676/dcf3e588-42af-4489-bd6e-921be3f9f35f)

Event requested in GetPlanningTransDemand 
![immagine](https://github.com/microsoft/ALAppExtensions/assets/53569676/6a8aefe7-957a-47c6-9be3-6b30dd217c64)

Event requested in ParentIsInPlanning 
![immagine](https://github.com/microsoft/ALAppExtensions/assets/53569676/c9cb16d0-31ae-4af1-851b-3ff33da397ee)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13599.
