### ISSUE TITLE
[Event Request] table 77 "Report Selections" - OnBeforeNewRecord

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#25125]
Hello, can you please add a new Event OnBeforeNewRecord in table 77 "Report Selections" ?

```
    procedure NewRecord()
    begin
        OnBeforeNewRecord(Rec, ReportSelection2);
        ReportSelection2.SetRange(Usage, Usage);
        if ReportSelection2.FindLast() and (ReportSelection2.Sequence <> '') then
            Sequence := IncStr(ReportSelection2.Sequence)
        else
            Sequence := '1';
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeNewRecord(var ReportSelections: Record "Report Selections"; var ReportSelections2: Record "Report Selections")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13591.
