### ISSUE TITLE
[Event Change Request] codeunit 9000854 "Inventory Profile Offsetting" event OnBeforeCommonBalancing #23663

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#25122]
The following extensibility request was raised (around BC22.3 time) and accepted and has been closed, but still hasn't been implemented as of the next major update (BC23)...

https://github.com/microsoft/ALAppExtensions/issues/23663

Any chance this could be done for the next minor update please?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13599.
