### ISSUE TITLE
[Event Parameter Request] codeunit 22 "Item Jnl.-Post Line" - OnItemValuePostingOnBeforeInsertOHValueEntry

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25121]
We would like to get the C22 global variable OverheadAmount and OverheadAmountACY added to existing event procedure
OnItemValuePostingOnBeforeInsertOHValueEntry. This event is called twice in code.

OnItemValuePostingOnBeforeInsertOHValueEntry(ItemJnlLine, GlobalValueEntry, GlobalItemLedgEntry, ValueEntryNo, IsHandled, VarianceAmount, VarianceAmountACY, OverheadAmount, OverheadAmountACY);

    [IntegrationEvent(true, false)]
    local procedure OnItemValuePostingOnBeforeInsertOHValueEntry(var ItemJnlLine: Record "Item Journal Line"; var GlobalValueEntry: Record "Value Entry"; var GlobalItemLedgEntry: Record "Item Ledger Entry"; var ValueEntryNo: Integer; var IsHandled: Boolean; var VarianceAmount: Decimal; var VarianceAmountACY: Decimal; var OverheadAmount: Decimal; var OverheadAmountACY: Decimal)
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13599.
