### ISSUE TITLE
[Event Request] codeunit 372 "Bank Acc. Recon. Post+Print" - OnBeforeRun

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#25142]
Hello, can you please add a new Event OnBeforeRun in codeunit 372 "Bank Acc. Recon. Post+Print" ?

```
    trigger OnRun()
    begin
        OnBeforeRun(Rec);
        BankAccRecon.Copy(Rec);

        if not Confirm(Text000, false) then
            exit;

        CODEUNIT.Run(CODEUNIT::"Bank Acc. Reconciliation Post", BankAccRecon);
        Rec := BankAccRecon;
        Commit();

        if BankAccStmt.Get(Rec."Bank Account No.", Rec."Statement No.") then
            DocPrint.PrintBankAccStmt(BankAccStmt);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeRun(var Rec: Record "Bank Acc. Reconciliation")
    begin
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13591.
