### ISSUE TITLE
Page "Warehouse Shipment": Lines editability

### ISSUE THREAD

**Issue by vdevmt** [microsoft/ALAppExtensions#25163]
Please, call ActivateControls procedure also in OnAfterGetCurrRecord Trigger.
Currently it is not possible to dynamically change the editability of lines part based on the value of a header field.

We have used OnAfterShipmentLinesEditable event of the "Warehouse Shipment Header" table but this not works because the procedure ActivateControls  of the page is called only in the OnOpenPage trigger

Thanks

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13730.
