### ISSUE TITLE
[Event Request] - Codeunit 5856 "TransferOrder-Post Transfer" OnBeforePostItem

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#25188]
### Describe the request

In Codeunit "TransferOrder-Post Transfer" can we add OnBefore Post in procedure PostItemJnlLine.  This is to match the same event in "TransferOrder-Post Shipment"

    local procedure PostItemJnlLine(var TransLine3: Record "Transfer Line"; DirectTransHeader2: Record "Direct Trans. Header"; DirectTransLine2: Record "Direct Trans. Line")
    // NEW +
    var
        IsHandled: Boolean;
    begin
        OnBeforePostItem(DirectTransHeader2, IsHandled, TransLine3, DirectTransLine2, WhseShip, WhseShptHeader, ItemJnlPostLine);
        if IsHandled then
            exit;
        // NEW -
        CreateItemJnlLine(TransLine3, DirectTransHeader2, DirectTransLine2);
        ReserveTransLine.TransferTransferToItemJnlLine(TransLine3,
          ItemJnlLine, ItemJnlLine."Quantity (Base)", Enum::"Transfer Direction"::Outbound, true);

        ItemJnlPostLine.RunWithCheck(ItemJnlLine);

        OnAfterPostItemJnlLine(TransLine3, DirectTransHeader2, DirectTransLine2, ItemJnlLine, ItemJnlPostLine);
    end;

    // New +
    [IntegrationEvent(false, false)]
    local procedure OnBeforePostItem(var DirectTransHeader2: Record "Direct Trans. Header"; var IsHandled: Boolean; var TransferLine3: Record "Transfer Line"; DirectTransLine2: Record "Direct Trans. Line"; WhseShip: Boolean; WhseShptHeader: Record "Warehouse Shipment Header"; var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line")
    begin
    end;
    // New -

### Additional context

We are creating Assembly Order for Transfer Orders, and need that event to Post the Assembly Order for that Transfer Order with The Item Jnl Post Line as a var to not interrupt the Global Entry No.  This also matches the same event in "TransferOrder-Post Shipment"

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13791.
