### ISSUE TITLE
[Scope Change] Table 7303 Bin Type - Add protected to CheckCombination function

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#25193]
### Describe the request

Please remove local and add protected to the following function:

```diff
-   local procedure CheckCombination(CalledByFieldNo: Integer)
+   protected procedure CheckCombination(CalledByFieldNo: Integer)
    var
        BinType: Record "Bin Type";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckCombination(Rec, CalledByFieldNo, IsHandled);
        if IsHandled then
            exit;

        ...
    end;
```

### Additional context

We want to call the check from the ``OnValidate`` trigger from our custom fields. I am also going to request an new event (see #25194) for the CalledByFieldNo = 0 case.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14079.
