### ISSUE TITLE
[Event Request] Codeunit 7322 Create Inventory Pick/Movement

### ISSUE THREAD

**Issue by cbrandemann** [microsoft/ALAppExtensions#25191]
### Describe the request

The following event is required for this object:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeNewWhseActivLineInsertFromJobPlanning(var WarehouseActivityLine: Record "Warehouse Activity Line"; var JobPlanningLine: Record "Job Planning Line"; var WarehouseActivityHeader: Record "Warehouse Activity Header"; var RemQtyToPickBase: Decimal)
    begin
    end;
```

### Additional context

For all other sources this publisher is available

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13909.
