### ISSUE TITLE
[Event Request] codeunit 419 "File Management" - OnBeforeBlobExport - additional parameter

### ISSUE THREAD

**Issue by jwikman** [microsoft/ALAppExtensions#25197]
### Describe the request

A lot of code that is calling `"File Management".BLOBExport()` is checking the return value to see if the file was really downloaded.
In the `BLOBExportWithEncoding()` procedure, the results of `OnBeforeBlobExportWithEncoding` is returned if the event IsHandled.

But in `BLOBExport()` it always returns an empty string if `OnBeforeBlobExport` IsHandled.

Please update `BLOBExport()` to return the result if IsHandled

```
    procedure BLOBExport(var TempBlob: Codeunit "Temp Blob"; Name: Text; CommonDialog: Boolean) Result: Text
    var
        NVInStream: InStream;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeBlobExport(TempBlob, Name, CommonDialog, IsHandled, Result);
        if IsHandled then
            exit(Result);

        TempBlob.CreateInStream(NVInStream);
        exit(BLOBExportLocal(NVInStream, Name, CommonDialog));
    end;
```
Update the `OnBeforeBlobExport` event to include the `Result` parameter, by reference:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeBlobExport(var TempBlob: Codeunit "Temp Blob"; Name: Text; CommonDialog: Boolean; var IsHandled: Boolean; var Result: Text)
    begin
    end;

```

### Additional context

We need this to be able to make a transparent use of the `OnBeforeBlobExport`. 
Often we cannot change the apps that is calling `BLOBExport()`, and they do check the results of the function and handle that as if the file was not downloaded at all (throwing errors or something like that).

Just look at all the usage of `BLOBExport()` in BaseApp, there are a lot of calls similar to `FileCreated := FileManagement.BLOBExport(TempBlob, FileName, UseCommonDialog) <> ''`, and as it is now we can never set `FileCreated` as `true` when handling the file via the `OnBeforeBlobExport` event.

This would also make the `OnBeforeBlobExport` event to behave similar as `OnBeforeBlobExportWithEncoding`.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13909.
