### ISSUE TITLE
Codeunit 415 - Change check on line

### ISSUE THREAD

**Issue by RaKuNbg** [microsoft/ALAppExtensions#2519]
I would suggestion to change the piece of code to check the lines as follows to be able to check all types of lines within one loop

![image](https://user-images.githubusercontent.com/46022628/58022352-8f458500-7b0d-11e9-9bfa-b7f0205c086f.png)

Function OnCheckPurchLine should be a publisher with the following parameters

![image](https://user-images.githubusercontent.com/46022628/58022556-f9f6c080-7b0d-11e9-9920-e52433812903.png)

**Comment by RomanZanizdra** [comment]
Hi @RaKuNbg .
If the request is still actual for you then let's do the following thing.
I suggest to leave code refactoring behind current request. And in terms of existing code (below) please let me know what event and where do you need? If the request is not actual for you then please close it.

...
            PurchLine.SetRange("Document Type", "Document Type");
            PurchLine.SetRange("Document No.", "No.");
            PurchLine.SetFilter(Type, '>0');
            PurchLine.SetFilter(Quantity, '<>0');
            if not PurchLine.Find('-') then
                Error(Text001, "Document Type", "No.");
            InvtSetup.Get();
            if InvtSetup."Location Mandatory" then begin
                PurchLine.SetRange(Type, PurchLine.Type::Item);
                if PurchLine.Find('-') then
                    repeat
                        if PurchLine.IsInventoriableItem then
                            PurchLine.TestField("Location Code");
                    until PurchLine.Next = 0;
                PurchLine.SetFilter(Type, '>0');
            end;

            OnCodeOnAfterCheck(PurchaseHeader, PurchLine, LinesWereModified);

            PurchLine.SetRange("Drop Shipment", false);
            NotOnlyDropShipment := PurchLine.Find('-');
            PurchLine.Reset();
...

**Comment by RaKuNbg** [comment]
Hi @RomanZanizdra,

without refactoring the code a new event within the current structure would not make sence because it would only work if
- InvtSetup."Location Mandatory" = TRUE
- Lines with Type = Item

For all other checks an additional loop over the lines is necessary (that could be done with the event OnCodeOnAfterCheck) but that's not the best solution with regard to performance. 

Microsoft is doing so much code refactoring in the last years so why do you want to stick to that old stuff in this case where you get a complete proposal of the new code structure that you just need to typewrite (yes I know it's still in old C/AL but my request is more then one year old)?

**Comment by RomanZanizdra** [comment]
Hi @RaKuNbg . Thank you very much for your reply and let me clarify some things.
There is no any problem to do a code refactoring in general if it make sense for the application. But in this particular case I see that you are asking for refactoring which make sense for you only. It's ok that you don't want to have one more loop for lines and use existing event. But following your suggestion we will decrease overall performance because two checks you mentioned above were done one time but after refactoring it will be done per each purchase line and lead to performance degradation. I cannot estimate this but it can be significant for the large number of lines. Dose it make sense, please let me know? So I suggest to use the existing event.

**Comment by RaKuNbg** [comment]
Hi @RomanZanizdra, 
I don't think that the refactoring I'm asking for is only for me but for everyone who does not only want to check item lines but also lines with other types.

What do you mean with 
...
because two checks you mentioned above were done one time but after refactoring it will be done per each purchase line
...
==> which two checks are you talking about? At least the check on InvtSetup."Location Mandatory" for every line doesn't cost any performance as the record is still read only once.

And if we talk about performance:
- PurchLine.SetFilter(Quantity, '<>0') isn't good for performance when there is a large number of lines (because it's not within a key)
- find('-') instead of IsEmpty to check if there are any lines is not "state of the art" regarding performance

**Comment by RomanZanizdra** [comment]
Current code:
if InvtSetup."Location Mandatory" = 1 time
if PurchLine.Type::Item = 0 time (I don't know how to convert "setfilter" into loop)
OnCodeOnAfterCheck = 1 time

Refactored code:
if InvtSetup."Location Mandatory" = n times = number of lines
if PurchLine.Type::Item = n times = number of lines
OnCodeOnAfterCheck = n times

You can provide particular numbers to estimate the difference if you want. You can also post this on the ideas site if you think the code should work for all types of line. For the current moment I don't see any reasons to change it.
And one more thing I forget to mention that changing numbers of run OnCodeOnAfterCheck() from 1 time to N times is actually a breaking change.
So again, I suggest to use the existing event and close the current issue. Any objections?
