### ISSUE TITLE
Event Request: OnBeforeTestTrackingIfRequired in fct. TestTrackingIfRequired of table 5767 "Warehouse Activity Line"

### ISSUE THREAD

**Issue by thomashoesel** [microsoft/ALAppExtensions#25198]
### Describe the request

Hello, 

We need a new event in the first line of function TestTrackingIfRequired of table 5767 "Warehouse Activity Line" like

OnBeforeTestTrackingIfRequired(Rec: Record "Warehouse Activity Line"; WhseItemTrackingSetup: Record "Item Tracking Setup"; IsHandled: Boolean)

... with an exit option in case IsHandled = true.

### Additional context

In our customer's industry is the base unit of measure not equally countable in pieces but we track it with lot numbers and serial numbers too. So we need an escape before TestField("Qty. (Base)", 1).

Best Regards
Thomas

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13909.
