### ISSUE TITLE
[Event Request] page 1007 "Job Planning Lines" - OnAfterSetEditable 

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#25196]
### Describe the request

Could you please add the following event `OnAfterSetEditable` and please **Include the sender** (the Page)?
```al
protected procedure SetEditable(Edit: Boolean)
begin
    PlanningDateEditable := Edit;
    CurrencyDateEditable := Edit;
    DocumentNoEditable := Edit;
    TypeEditable := Edit;
    NoEditable := Edit;
    DescriptionEditable := Edit;
    UnitOfMeasureCodeEditable := Edit;
    VariantCodeEditable := Edit;
    LocationCodeEditable := Edit;
    BinCodeEditable := Edit;
    WorkTypeCodeEditable := Edit;
    UnitPriceEditable := Edit;
    LineDiscountAmountEditable := Edit;
    LineDiscountPctEditable := Edit;
    LineAmountEditable := Edit;
    UnitCostEditable := Edit;
    OnAfterSetEditable(Edit, Rec); //NEW Event
end;
```

```al
[IntegrationEvent(true, false)]
local procedure OnAfterSetEditable(Edit: Boolean; var JobPlanningLine: Record "Job Planning Line");
begin
end;
```

### Additional context

When we get this event then we can subscribe to this event to disable edit of custom added fields.

Therefore we need the Sender, that we can set Global Variables for Editable of our custom fields via Setter Functions on the PageExtension Object.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13909.
