### ISSUE TITLE
Convert "Document Type" field  in "Sales Header" and "Sales Line" into ENUM

### ISSUE THREAD

**Issue by ThomasBrodkorb** [Microsoft/ALAppExtensions#252]
Convert the document type in sales header and sales line into an enum in order to allow for extending the options.
Make sure that all references (comparisons) which test the document type field are explicit tests ( = or IN), and not implicit (<> or < or >).

**Comment by JesperSchulz** [comment]
Unfortunately, "Document Type" is part of the primary key and is used in conditional table relations, which we cannot extend yet. We do have the feature in our backlog, but until we have extensible table relateions, we cannot turn "Document Type" into an extensible enum. I'm afraid this request will sit idle for now. I'm hence closing it here on GitHub, but we'll pick it up once we have all needed capabilities. Just a little more patience...
