### ISSUE TITLE
24824 - Status

### ISSUE THREAD

**Issue by ShaikAbdulRasheed** [microsoft/ALAppExtensions#25204]
### Describe the request

Requested the new event in issue 24824, but i can not see the request event. in which version i can expect the event.

Below is the link for request.

https://github.com/microsoft/ALAppExtensions/issues/24824

![image](https://github.com/microsoft/ALAppExtensions/assets/110883968/7b693706-36c3-4783-82e0-bd6e8aee5473)

### Additional context

https://github.com/microsoft/ALAppExtensions/issues/24824

**Comment by RadoArvay** [comment]
I can see them in nextmajor 24.0.13760.0; I didn't check in nextminor.

**Comment by JakovljevicDusan** [comment]
Event OnBeforeGenerateColumnCaptions is added in 23.1.
