### ISSUE TITLE
codeunit 7204 "CDS Setup Defaults" / procedure ResetConfiguration / Add event or fix possible bug

### ISSUE THREAD

**Issue by ttasala** [microsoft/ALAppExtensions#25205]
### Describe the request

Version: Platform 23.0.13698.0 + Application 23.0.12034.12676

Microsoft has added a new procedure under ResetConfiguration, called AddExtraIntegrationFieldMappings (BC 23). In my opinion this new procedure should be BEFORE the procedure call SetCustomIntegrationsTableMappings, since this is the only place where we can manipulate the integration mappings. 

Other option is to add a new event in procedure AddExtraIntegrationFieldMappings (e.g. OnAfterAddExtraIntegrationFieldMappings). 

![image](https://github.com/microsoft/ALAppExtensions/assets/110519926/ae093798-7ba5-4948-ae36-3ff195b97151)

### Additional context

We want to create a CRM integration which includes only those tables/fields which are agreed with the customer.

Now there is a new integration field mapping "Mobile Phone No." under integration table mapping "CUSTOMER" which can't be removed smoothly in the reset operation. I know that "Mobile Phone No." field Status = disabled and is not part of the replication, but still - we must have a way to create 1:1 setup which is agreed with the customer (i.e. without fields which aren't in the agreed scope).

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13909.
