### ISSUE TITLE
Option field to ENUM in table CostCenter - was announced in March 2023 as coming asap ...?!

### ISSUE THREAD

**Issue by thomashoesel** [microsoft/ALAppExtensions#25206]
### Describe the request

Hello @JesperSchulz, 

May I kindly ask what happend to our Option2Enum request?

https://github.com/microsoft/ALAppExtensions/issues/22556

### Additional context

We do really need this.

Best Regards
Thomas Hoesel

**Comment by JesperSchulz** [comment]
That is a good question. I just looked into the changes made, and can see that enum 1114 "Cost Center Subtype" was introduced, while the "Cost Center" table has remained unchanged. I will ask the responsible team to look into this!

**Comment by AlexanderYakunin** [comment]
Yes, this is clearly overlooked, we will fix this mistake asap

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 13981.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13980.
