### ISSUE TITLE
[Event Request] codeunit 10750 "SII XML Creator" - OnBeforeCalculateTotalVatAndBaseAmounts

### ISSUE THREAD

**Issue by GFlores11** [microsoft/ALAppExtensions#25212]
### Describe the request

    local procedure CalculateTotalVatAndBaseAmounts(LedgerEntryRecRef: RecordRef; var TotalBaseAmount: Decimal; var TotalNonExemptVATBaseAmount: Decimal; var TotalVATAmount: Decimal)
    var
        VATEntry: Record "VAT Entry";
        NoTaxableEntry: Record "No Taxable Entry";
        +IsHandled: Boolean; 
    begin
        +IsHandled := false;
        +OnBeforeCalculateTotalVatAndBaseAmounts(LedgerEntryRecRef: RecordRef; var TotalBaseAmount: Decimal; var TotalNonExemptVATBaseAmount: Decimal; var TotalVATAmount: Decimal, IsHandled);
        +if IsHandled then
        +    exit;

        TotalBaseAmount := 0;
        TotalVATAmount := 0;

        if SIIManagement.FindVatEntriesFromLedger(LedgerEntryRecRef, VATEntry) then begin
            repeat
                OnCalculateTotalVatAndBaseAmountsOnBeforeAssignTotalBaseAmount(LedgerEntryRecRef, VATEntry);
                TotalBaseAmount += VATEntry.Base + VATEntry."Unrealized Base";
                if VATEntry."VAT %" <> 0 then
                    TotalNonExemptVATBaseAmount += VATEntry.Base + VATEntry."Unrealized Base";
                if VATEntry."VAT Calculation Type" <> VATEntry."VAT Calculation Type"::"Reverse Charge VAT" then
                    TotalVATAmount += VATEntry.Amount + VATEntry."Unrealized Amount";
            until VATEntry.Next() = 0;
        end;
        SIIManagement.FindNoTaxableEntriesFromLedger(LedgerEntryRecRef, NoTaxableEntry);
        NoTaxableEntry.CalcSums(NoTaxableEntry."Base (LCY)");
        TotalBaseAmount += NoTaxableEntry."Base (LCY)";
    end;

    +[IntegrationEvent(false, false)]
    +local procedure OnBeforeCalculateTotalVatAndBaseAmounts(LedgerEntryRecRef: RecordRef; var TotalBaseAmount: Decimal; var TotalNonExemptVATBaseAmount: Decimal; var TotalVATAmount: Decimal, IsHandled)
    +begin
    +end;

### Additional context

We need to perform some special calculations on the variable "TotalNonExemptVATBaseAmount".

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 13909.
