### ISSUE TITLE
[Extensibility] table 5767 "Warehouse Activity Line" - Add method with overload

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#25210]
### Describe the request

Please add an overload to get the new warehouse activity line directly from splitting.

```diff
+    procedure SplitLine(var WarehouseActivityLine: Record "Warehouse Activity Line")
+    var
+        NewWarehouseActivityLine: Record "Warehouse Activity Line";
+    begin
+          SplitLine(WarehouseActivityLine, NewWarehouseActivityLine);
+    end

-    procedure SplitLine(var WarehouseActivityLine: Record "Warehouse Activity Line";)
+    procedure SplitLine(var WarehouseActivityLine: Record "Warehouse Activity Line"; var NewWarehouseActivityLine: Record "Warehouse Activity Line";)
    var
-        NewWarehouseActivityLine: Record "Warehouse Activity Line";
        LineSpacing: Integer;
        NewLineNo: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSplitLines(WarehouseActivityLine, IsHandled);
        if IsHandled then
            exit;

        ...
    end
```

### Additional context

We want to modify the split line immediately afterwards with information from the caller side.
Internal work item: [AB#495836](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/495836)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19015.
