### ISSUE TITLE
codeunit 99000770 "Where-Used Management" procedure BuildWhereUsedList add value to TempWhereUsedList."Production BOM No."

### ISSUE THREAD

**Issue by Michel-up** [microsoft/ALAppExtensions#25217]
### Describe the request

in codeunit 99000770 "Where-Used Management, procedure BuildWhereUsedList
the TempWhereUsedList."Production BOM No." is not being filled

i suggest to add below highlighted line

```
   TempWhereUsedList."Version Code" := VersionMgt.GetBOMVersion(No, CalcDate, true);
    //Add Line Below
    TempWhereUsedList."Production BOM No." := No;
 
   OnBeforeWhereUsedListInsert(TempWhereUsedList, ItemAssembly, CalcDate, Quantity);
   TempWhereUsedList.Insert();

```

### Additional context

The "Production BOM No." in Record "Where-Used Line"  is always empty,
when filled it will show in which "Production BOM No." the item is being used (Page Prod. BOM Where-Used (99000811, Worksheet)

**Comment by JakovljevicDusan** [comment]
Hi @Michel-up,

Thanks for reporting this. It seems like a bug, but this is not the right channel for fixing functional bugs. This repository is only for extensibility requests for Dynamics 365 Business Central.

Please report this bug via https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/technical-support#summary-of-where-to-file-bugs-and-issues, so dedicated teams can process it.
