### ISSUE TITLE
Expose SuppressTotals on Sales Order Subform

### ISSUE THREAD

**Issue by Joriek** [microsoft/ALAppExtensions#25216]
### Describe the request

Please put the "SuppressTotals" boolean on page 46 "Sales Order Subform" as protected so we can excess this via extensions.
This is already the case for the same boolean on page 95 "Sales Quote Subform".

Quote:
![image](https://github.com/microsoft/ALAppExtensions/assets/6583705/e8445968-2b72-4b36-a6a2-14b89046cc50)

Order:
![image](https://github.com/microsoft/ALAppExtensions/assets/6583705/315546f6-e4da-49a1-a9bd-ecb14afb49a8)

### Additional context

We want to disable the totals calculation on order, similar to what we made on quote. Currently we can only hide the fields, but not disable the calculation of them.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14079.
