### ISSUE TITLE
[Event Request] Table "Job Planning Line" procedure ControlUsageLink

### ISSUE THREAD

**Issue by LewisHyettTES** [microsoft/ALAppExtensions#25228]
### Describe the request

Please create the following event within the procedure "ControlUsageLink" within the "Job Planning Line" table.

`OnAfterControlUsageLink(Rec, Job, CurrFieldNo);`

 [IntegrationEvent(false, false)]
    local procedure OnAfterControlUsageLink(var JobPlanningLine: Record "Job Planning Line"; Job: Record Job; CallingFieldNo: Integer)
    begin
    end;

```
...
         Validate("Qty. to Transfer to Journal", Quantity - "Qty. Posted");
        UpdateRemainingCostsAndAmounts("Currency Date", "Currency Factor");

        UpdateQtyToTransfer();
        UpdateQtyToInvoice();

      // New Event
      OnAfterControlUsageLink(Rec, Job, CallingFieldNo);
     //
```

### Additional context

Many of the procedures in the Job Planning Line table are not extensible and restricting. We would like to recalculate bespoke fields inline with standard fields which isn't currently possible.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14041.
