### ISSUE TITLE
[Event Request] Provide IsHandled around event OnBeforeReplaceSIComponent [Codeunit - ServItemManagement]

### ISSUE THREAD

**Issue by LewisHyettTES** [microsoft/ALAppExtensions#25221]
### Describe the request

Please provide an IsHandled and exit clause to the existing event OnBeforeReplaceSIComponent within procedure AddOrReplaceSIComponent.

```
IsHandled := false;
OnBeforeReplaceSIComponent(ServLine, ServHeader, ServShptDocNo, ServShptLineNo, TempTrackingSpecification);
if IsHandled then exit;
```

### Additional context

Within codeunit 5920 ServItemManagement it is not possible to bypass standard functionality.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14041.
