### ISSUE TITLE
[Event Request] Report 12172 "Cust Bills Floppy"

### ISSUE THREAD

**Issue by Ponch18** [microsoft/ALAppExtensions#25227]
Can you please add the following events in Procedures as in report 12173?

OnRECORD14OnAfterAssignOutText
OnRECORD20OnAfterAssignOutText
OnRECORD30OnAfterAssignOutText
OnRECORD40OnAfterAssignOutText
OnRECORD50OnAfterAssignOutText
OnRECORD51OnAfterAssignOutText
OnRECORD70OnAfterAssignOutText

Similar event request in following issue: https://github.com/microsoft/ALAppExtensions/issues/23648

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14041.
