### ISSUE TITLE
Codeunit 427 ICInboxOutboxMgt - Procedures ShowDuplicateICDocumentWarning from internal to global

### ISSUE THREAD

**Issue by AlexanderWittek** [microsoft/ALAppExtensions#25224]
### Describe the request

Can the procedures please be set from internal to global.

`internal procedure ShowDuplicateICDocumentWarning(var PurchaseHeader: Record "Purchase Header")`

`internal procedure ShowDuplicateICDocumentWarning(var PurchaseHeader: Record "Purchase Header"; WarningMsg: Text)`

### Additional context

We would like to use this functionality in our document pages.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14079.
