### ISSUE TITLE
[Event Request] Page 12161 “Declaration of Intent Export”

### ISSUE THREAD

**Issue by fifr-reply** [microsoft/ALAppExtensions#25225]
### Describe the request

Could you please either remove `[Scope('OnPrem')]` from procedure `Initialize` in Page 12161 “Declaration of Intent Export” or add an event so one can change the underlying "VAT Exemption" record through extension?

```
trigger OnAction()
var
    DeclarationOfIntentReport: Report "Declaration of Intent Report";
    DeclarationOfIntentExport: Codeunit "Declaration of Intent Export";
begin
    OnBeforeDeclarationOfIntentExport(VATExemption); // <-- NEW EVENT

    if DeclarationOfIntentExport.Export(
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeDeclarationOfIntentExport(var VATExemption: Record "VAT Exemption")
begin
end;
```

### Additional context

Being able to control which VAT Exemption to use is a requirement for the development of a custom feature involving declarations of intent.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14079.
