### ISSUE TITLE
[Bug]: codeunit 5012 "Service Declaration Mgt." - Hard Get On Header leads to problems with Temporary Record

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#25222]
### Describe the issue

Currently there are a few Event Subscribers in the `codeunit 5012 "Service Declaration Mgt."`, that make a hard get on the SalesHeader, PurchHeader instead of using the GetHeader Functions.

This leads to problems with temporary SalesHeader for price calculations

### Expected behavior

Those event subscribers should use the GetHeader methods

### Steps to reproduce

Create a temporary Record for a SalesHeader an and then create a tempory sales line for a resource.

### Additional context

Temporary SalesHeader and Purch Header are often forgotten.

**Comment by paolomariatitta** [comment]
there are problems also with sales orders with customers with standard sales codes with item type service

**Comment by pri-kise** [comment]
@paolomariatitta we aren't working with Standard Sales Codes, but if this is the case, then this is a product defect and it could be useful create a Support Request to get this prioritized.

Our customers don't work with Standard Sales Codes, therefore we didn't had this issue there.

If you create an support request you can totally link to this issue and to my open PR.
Maybe this helps to get this merged faster.

At least for BC 23.2 this would be very helpful.

**Comment by paolomariatitta** [comment]
ok thank you

**Comment by JesperSchulz** [comment]
More code coming in. Re-opening issue.
