### ISSUE TITLE
Table 36 "Sales Header" - Procedure SetTrackInfoForCancellation from internal to global

### ISSUE THREAD

**Issue by AlexanderWittek** [microsoft/ALAppExtensions#25235]
### Describe the request

Can the procedure please be set from internal to global.

`internal procedure SetTrackInfoForCancellation()`

### Additional context

We would like to use this functionality in our document pages.

**Comment by AlexanderYakunin** [comment]
This procedure was part of the fix which we finally decided to revert due to other follow-up hotfix requests. As result of revert this procedure was obsoleted and we have no good cause to make it global. It is still available if you use added event to change this behavior.
