### ISSUE TITLE
Please add an OnNextRecOnBeforeCustomerFind and OnNextRecOnBeforeVendorFind  event  into the procedure NextRecord in codeunit 7130 "Item Budget Management" (Note that there is already an existing event at the item level.)

### ISSUE THREAD

**Issue by XKVX** [microsoft/ALAppExtensions#25233]
### Describe the request

Please add an OnNextRecOnBeforeCustomerFind and OnNextRecOnBeforeVendorFind  event  to the procedure NextRecord in codeunit 7130 "Item Budget Management" (Note that there is already an existing event at the item level. )

procedure NextRecord(ItemBudgetName: Record "Item Budget Name"; DimType: Enum "Item Budget Dimension Type"; var DimCodeBuf: Record "Dimension Code Buffer"; Steps: Integer; ItemFilter: Text; SourceNoFilter: Text; PeriodType: Enum "Analysis Period Type"; DateFilter: Text; GlobalDim1Filter: Text; GlobalDim2Filter: Text; BudgetDim1Filter: Text; BudgetDim2Filter: Text; BudgetDim3Filter: Text): Integer
    var
        Item: Record Item;
        Cust: Record Customer;
        Vend: Record Vendor;
        Location: Record Location;
        Period: Record Date;
        PeriodPageMgt: Codeunit PeriodPageManagement;
        ResultSteps: Integer;
    begin
        GetGLSetup();
        case DimType of
            GlobalDimType::Item:
                begin
                    Item."No." := DimCodeBuf.Code;
                    if ItemFilter <> '' then
                        Item.SetFilter("No.", ItemFilter);
                    OnNextRecOnBeforeItemFind(Item);
                    ResultSteps := Item.Next(Steps);
                    if ResultSteps <> 0 then
                        CopyItemToBuf(Item, DimCodeBuf);
                end;
            GlobalDimType::Customer:
                begin
                    Cust."No." := DimCodeBuf.Code;
                    if SourceNoFilter <> '' then
                        Cust.SetFilter("No.", SourceNoFilter);
	   **//new event begin
	    OnNextRecOnBeforeCustomerFind(Cust) 
	   //new event end**
                    ResultSteps := Cust.Next(Steps);
                    if ResultSteps <> 0 then
                        CopyCustToBuf(Cust, DimCodeBuf);
                end;
             GlobalDimType::Vendor:
                begin
                    Vend."No." := DimCodeBuf.Code;
                    if SourceNoFilter <> '' then
                        Vend.SetFilter("No.", SourceNoFilter);
	   **//new event begin
	    OnNextRecOnBeforeVendorFind(Vend)
	   //new event end**
                    ResultSteps := Vend.Next(Steps);
                    if ResultSteps <> 0 then
                        CopyVendToBuf(Vend, DimCodeBuf);
                end;

//New events begin
   [IntegrationEvent(false, false)]
    local procedure OnNextRecOnBeforeCustomerFind(var Customer: Record Customer)
    begin
    end;
   [IntegrationEvent(false, false)]
    local procedure OnNextRecOnBeforeVendorFind(var Vendor: Record Vendor)
    begin
    end

//New events end

### Additional context

We need to add additional filters.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14041.
