### ISSUE TITLE
Generic OnAfterValidate

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/ALAppExtensions#25244]
### Describe the request

Could we have a generic OnAfterValidate-event for a table that would be triggered by all fields and that would deliver a recref and fieldref (or corresponding numbers, and maybe runtrigger) to the field? Similar to OnAfterModifyRecord, that doesn't give us the field, as far as I can tell.

### Additional context

If for instance we need to handle modifications of all the ship-to-address fields on sales header in a similar fashion, currently we need to create something like 10 event subscribers instead of one that could handle everything.

**Comment by pri-kise** [comment]
You should create an idea for this on https://aka.ms/bcideas .

This repository is the wrong place for such platform feature requests.

**Comment by AleksandricMarko** [comment]
Hi @navdotnetreqs 
As @pri-kise mentioned, please create new "idea".
This one will be closed.
