### ISSUE TITLE
Report 7318 "Whse.-Shipment - Create Pick", set variable PrintDoc to protected

### ISSUE THREAD

**Issue by danieldetzel** [microsoft/ALAppExtensions#25249]
### Describe the request

Hello,

please set the variable PrintDoc to protected in Report 7318 "Whse.-Shipment - Create Pick"

### Additional context

Please set the variable PrintDoc to protected in Report 7318 "Whse.-Shipment - Create Pick"

```
    protected var
        HideValidationDialog: Boolean;
        PrintDoc: Boolean;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14079.
