### ISSUE TITLE
[Extensibility Request] CompanyInfo - Sales and Purchase Documents

### ISSUE THREAD

**Issue by TKapitan** [microsoft/ALAppExtensions#25247]
### Describe the request

Please make the CompanyInfo variable protected in all Standard Sales and Standard Purchase

- Standard Sales reports 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309
- Standard Purchase report 1322
- Old purchase documents that do not have new variant, reports 404, 406-408, 410
- Standard Statement 1316
- Reminder 117

### Additional context

This can be useful for use cases where the company has multiple trading names (for example, different in every state) so partners can just replace values in the company info in the report with the selected trading name/address without changing the layout/adding custom report columns.

**Comment by TKapitan** [comment]
I'm sorry, @AlexanderYakunin, I used the information from other developers without rechecking it.
So, the remaining reports are

 - Reports 404, 406-408, 410
 - Report 6636

The 6636 (Purchase - Return Shipment) is probably the only important one, as this is a vendor-facing document that is usually included in the return shipment package (it's not used often, but we have projects where we use return shipments). Can you please make the companyinfo available in all these reports, or at least in 6636?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14132.
