### ISSUE TITLE
[Change Request] page 5628 "Fixed Asset G/L Journal" -  procedure SetControlAppearanceFromBatch

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#25246]
### Describe the request

Hello, can you please change the procedure SetControlAppearanceFromBatch from local to global?

```
    procedure SetControlAppearanceFromBatch()
    var
        GenJournalBatch: Record "Gen. Journal Batch";
    begin
        if not GenJournalBatch.Get(Rec.GetRangeMax("Journal Template Name"), CurrentJnlBatchName) then
            exit;
        BackgroundErrorCheck := BackgroundErrorHandlingMgt.BackgroundValidationFeatureEnabled();
        ShowAllLinesEnabled := true;
        Rec.SwitchLinesWithErrorsFilter(ShowAllLinesEnabled);
        JournalErrorsMgt.SetFullBatchCheck(true);
    end;
```

### Additional context

We want to call the function from our extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14079.
