### ISSUE TITLE
[Request for extensibility] Codeunit 7321 "Create Inventory Put-away" Function "InsertWhseActiveLine"

### ISSUE THREAD

**Issue by SPinkow** [microsoft/ALAppExtensions#25258]
### Describe the request

Hi,
in Codeunit 7321 "Create Inventory Put-away" the NewWhseItemTrackingSetup parameter was previously used to pass an "Item Tracking Setup" record into the procedure InsertWhseActiveLine. This function has been obsoleted.

However, the new method has been made local, which means it can only be accessed within the same object. This restricts the ability to replace the implementation of the method in other parts of the codebase. Therefore, it's crucial to change the accessibility of the new InsertWhseActivLine method from local to global. This will allow the method to be accessed from other parts of the codebase, ensuring your code will continue to function correctly in version 23.0 and beyond.

Thank you for changing this in the next minor update!

![image](https://github.com/microsoft/ALAppExtensions/assets/45430404/05d53019-93a4-4c47-9628-037104ab2f2e)

### Additional context

We used the old method in one of our Apps. When the old method will be removed in a future version it will be a breaking change and our App will not compile anymore.

**Comment by AlexanderYakunin** [comment]
Even if we do this procedure global, it will not compile anyway because it use different number of parameters. So you will need to change you app code anyway.

**Comment by SPinkow** [comment]
Yes, I know that I have to change our App. That is what I am trying to do, but the local Method prevents me from using the overloaded new version of the method.
At the time Microsoft removes the obsoleted method it will be a breaking change for us and our app would not compile anymore because we had no chance to change our code. So all I am asking for is to remove the local modifier of the function so that we can change our code in time.

**Comment by SPinkow** [comment]
Can I please get an update on this request.
I have been waiting for several CU versions to be able to edit my warning in my code.
Is there a scheduled date for this request? Would be nice if this was changed in one of the next CU's. Thanks for a quick reply.

**Comment by AlexanderYakunin** [comment]
First, this change will not be done for any CU, but for master and next major only. We cannot downgrade external requests to PROD tenants. I will try to make it this week.

**Comment by AlexanderYakunin** [comment]
Please recheck, this is already done. This procedure is global

**Comment by SPinkow** [comment]
Thanks for the status.
Well, I checked it again and unfortunately the function is still local in my current (version 23.3.14876.15232) container.
I'm not talking about downgrade, but from the next CU if possible. Also, this is more of an obsoletion error in the BaseApp than a request for extensibility, because the function was originally available (incl. useless parameter), which is now no longer the case. If you remove the code that is now marked as obsolete (and dont remove the local modifier, my app will no longer work and it would therefore be a breaking change in the BaseApp. If you can ensure that the old code is still available via the next major release, I would be happy with the update in the next major release. If you can't ensure that, I would ask you to remove the little word local in the next CU. This is not a breaking change for anyone and it would bring back the original usability of this function in the codeunit.
Thank you very much!
