### ISSUE TITLE
[Bug]: Remove OnPrem annotation in codeunit 143000 "Library - NL Localization"

### ISSUE THREAD

**Issue by DonHendriksen** [microsoft/ALAppExtensions#25255]
### Describe the issue

Please remove the OnPrem annotation from all procedures in codeunit 143000 "Library - NL Localization". There is, to our opinion, no reason to have them as scope OnPrem, it perfectly works in Online as well.

### Expected behavior

We want our unit tests to be cloud ready too, which means the procedures in library codeunits should be without scope OnPrem annotation.

### Steps to reproduce

.

### Additional context

.<br /><br />Internal work item: AB#492784

**Comment by AlexanderYakunin** [comment]
Already done earlier, please check latest code
