### ISSUE TITLE
[Event Request] codeunit 5341 "CRM Int. Table. Subscriber" - UpdateCRMInvoiceBeforeInsertRecord

### ISSUE THREAD

**Issue by TKapitan** [microsoft/ALAppExtensions#25252]
### Describe the request

Please add a new event to codeunit 5341 "CRM Int. Table. Subscriber" UpdateCRMInvoiceBeforeInsertRecord

REASON: We need to default some data from CRM sales order similarly to existing fields

```
            CRMInvoice.CustomerId := CRMSalesorder.CustomerId;
            CRMInvoice.CustomerIdType := CRMSalesorder.CustomerIdType;
// -> EVENT REQUEST
            OnUpdateCRMInvoiceBeforeInsertRecordAfterSetCRMInvoicedCoupledToCRMSalesOrder(CRMInvoice, SalesInvoiceHeader);
// <- EVENT REQUEST
            DestinationRecordRef.GetTable(CRMInvoice);
            if CRMSalesorder.OwnerIdType = CRMSalesorder.OwnerIdType::systemuser then
                CDSIntegrationImpl.SetOwningUser(DestinationRecordRef, CRMSalesOrder.OwnerId, true)


    [IntegrationEvent(false, false)]
    local procedure OnUpdateCRMInvoiceBeforeInsertRecordAfterSetCRMInvoicedCoupledToCRMSalesOrder(var CRMInvoice: Record "CRM Invoice"; SalesInvoiceHeader: Record "Sales Invoice Header");
    begin
    end;
```

### Additional context

.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14158.
