### ISSUE TITLE
[Event Request] table 37 "Sales Line" - OnBeforeGetUnitCost

### ISSUE THREAD

**Issue by BharatVelosio** [microsoft/ALAppExtensions#25257]
### Describe the request

Hi Team,

In table 37 "Sales Line", please provide one more parameter the possibility to have OnBeforeGetUnitCost event in procedure.

procedure GetUnitCost()

After begin at Line No 5730

OnBeforeGetUnitCost(Rec, IsHandled,CurrFieldNo);

![image](https://github.com/microsoft/ALAppExtensions/assets/133997930/7b8b299a-f3df-4be0-b7a2-9095f3ce0b79)

[IntegrationEvent(true, false)]
    local procedure OnBeforeGetUnitCost(var SalesLine: Record "Sales Line"; var IsHandled: Boolean;CalledByFieldNo: Integer)
    begin
    end;

### Additional context

Client needs to restrict the validation of the unit cost from the location code.

**Comment by dannoe** [comment]
As a temporary workaround you can add a tableextension and add a getter function for CurrFieldNo. Inside your EventSubscriber you can then call ``SalesLine.ABCGetCurrFieldNo()`` to retrieve the no.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14158.
