### ISSUE TITLE
[Extensibility Enhancement] Report 83 "Export Budget to Excel" Protected Variables

### ISSUE THREAD

**Issue by MCHammerTNP** [microsoft/ALAppExtensions#25268]
### Describe the request

Can the following global variables be made [Protected] so that they can be updated from a Report Extension please;

- TempPeriod
- PeriodLength
- StartDate
- NoOfPeriods
- DimSelectionBuffer 

Many thanks in advance.

### Additional context

The variables need to be [Protected] so that values can be set from a Report Extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14132.
