### ISSUE TITLE
[Bug]: CU SubcontractingPricesMgt event OnGetSubcPriceForReqLineOnAfterSetFilters

### ISSUE THREAD

**Issue by lukone** [microsoft/ALAppExtensions#25262]
### Describe the issue

hi, the OnGetSubcPriceForReqLineOnAfterSetFilters event in the codeunit SubcontractingPricesMgt,
the var was not specified on the first parameter making the event itself useless.
Can you fix the call?

thanks

![image](https://github.com/microsoft/ALAppExtensions/assets/24915355/aac7448b-1a79-4309-8a8c-932dd0ec33bd)

### Expected behavior

return Record "Subcontractor Prices"

### Steps to reproduce

N/A

### Additional context

N/A<br /><br />Internal work item: AB#492783

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14606.
