### ISSUE TITLE
[Bug]: "Check Total" control is missing in BC23 IT Localization

### ISSUE THREAD

**Issue by simonezaganelli** [microsoft/ALAppExtensions#25261]
### Describe the issue

the check regarding the field "Check Total" ( IT localization) is now missing in Codeunit 90, BC23.1

### Expected behavior

Now the field is not checked anywhere in base application

### Steps to reproduce

try to post a purchase invoice with the field "Check Total" filled with a different value from the document total

### Additional context

Left -> BC 22, Right -> BC23.1
![image](https://github.com/microsoft/ALAppExtensions/assets/134918377/4d7eaf4f-cb13-4d5c-8a09-7c251f60d926)

**Comment by gpintaudi** [comment]
Hi @JesperSchulz could you please look into this issue?
This is a mandatory check in IT Localizations.
Thanks

**Comment by JesperSchulz** [comment]
I am sorry, but this is not the right place to report product defects. Product defects with customer impact must go through support. This repository is for extensibility requests only, or for issues you intend to fix yourself through an open source contribution. As we don't have an open source model for localizations, that's unfortunately not an open yet 😟
