### ISSUE TITLE
[Request For External] table "Sales Line" and "Purchase Line" - AddItems

### ISSUE THREAD

**Issue by pschwambornMC** [microsoft/ALAppExtensions#25273]
### Describe the request

can you please change the procedure AddItems(SelectionFilter: Text) in "Sales Line" and "Purchase Line" from local to global?

### Additional context

We want to call the function from our extension. We build our own SelectionFilter for a set of items and now want to use the base code as much as possible to generate the document lines to avoid problems with other apps.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14132.
