### ISSUE TITLE
[Event Request] table 5900 "Service Header" - OnRecreateServiceLinesOnBeforeCopyReservEntryFromTemp

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/ALAppExtensions#25270]
### Describe the request

Can we please get the following event? (just like a simular event in the salesheader)

    [IntegrationEvent(false, false)]
    local procedure OnRecreateServiceLinesOnBeforeCopyReservEntryFromTemp(var ServLine: Record "Service Line"; var TempServLine: Record "Service Line" temporary; var ServiceHeader: Record "Service Header"; xServiceHeader: Record "Service Header")
    begin
    end;
    
    this event can be called once before the  line "CopyReservEntryFromTemp(TempServLine, ServLine."Line No.");" in procedure CreateServiceLines

### Additional context

just like a simular event in the salesheader we need an event after the line insert has been executed

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14158.
