### ISSUE TITLE
[Request for Exernal] - Codeunit: Copy Doc. Mgt: Event: OnCopyPurchDocLineOnBeforeCopyThisLine

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#25283]
### Describe the request

 could NextLineNo be added to this event as a reference? 
 
```
 OnCopyPurchDocLineOnBeforeCopyThisLine(ToPurchLine, FromPurchLine, MoveNegLines, FromPurchDocType, LinesNotCopied, CopyThisLine, Result, IsHandled, ToPurchHeader, RecalculateLines,NextLineNo);
 
  [IntegrationEvent(false, false)]
    local procedure OnCopyPurchDocLineOnBeforeCopyThisLine(var ToPurchLine: Record "Purchase Line"; var FromPurchLine: Record "Purchase Line"; MoveNegLines: Boolean; FromPurchDocType: Enum "Purchase Document Type From"; var LinesNotCopied: Integer; var CopyThisLine: Boolean; var Result: Boolean; var IsHandled: Boolean; ToPurchaseHeader: Record "Purchase Header"; var RecalculateLines: Boolean;Var NextLineNo:Integer)
    begin
    end;
```

### Additional context

Because we have our own attach to. fields, and want to use it to insert attached lines.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14309.
