### ISSUE TITLE
New event request table 5095 Duplicate Search String Setup

### ISSUE THREAD

**Issue by monicasuica** [microsoft/ALAppExtensions#25286]
### Describe the request

Hi ,

Please add the following event publisher in the table 5095 Duplicate Search String Setup,
The reason: in NAV there were customizations made so that the users were able to select also field of type Date.
Now they want to upgrade to Business Central and it is not possible to migrate that customizations becase of the mentioned restriction.

```
 procedure LookupFieldName()
    var
        "Field": Record "Field";
        FieldSelection: Codeunit "Field Selection";
        IsHandled: Boolean;
    begin
        IsHandled := false;  //+
        OnBeforeLookupFieldName(Field, IsHandled); //+
        if IsHandled then //+
            exit; //+

        Field.SetRange(TableNo, DATABASE::Contact);
        Field.SetFilter(Type, '%1|%2', Field.Type::Text, Field.Type::Code);
        Field.SetRange(Class, Field.Class::Normal);
        if FieldSelection.Open(Field) then
            Validate("Field No.", Field."No.");

    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeLookupFieldName(var Field: Record "Field"; var IsHandled: Boolean)
    begin
    end;
```

Thank you!

### Additional context

In NAV there were customizations made so that the users were able to select also field of type Date.
Now they want to upgrade to Business Central and it is not possible to migrate that customizations becase of the mentioned restriction.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14309.
