### ISSUE TITLE
[EVENT REQUEST] Change Parameter to var on an Event

### ISSUE THREAD

**Issue by Muyigi** [microsoft/ALAppExtensions#25288]
### Describe the request

Hey everyone,

we need to change two Eventparameters to VAR-reference in the Event OnAfterInitNewWhseShptLine in Codeunit "Sales Warehouse Mgt.".
<img width="1289" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/148440388/11468e49-39fb-4405-a52f-3a635112732c">

Actually they are without an VAR-reference :(
<img width="1599" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/148440388/87357f2c-99ee-44c2-aeec-f05a5c64d531">

Would be nice if we can get it in the next CU Updates for BC23.
Thank you.

### Additional context

We already suggested this Event. But i think we doesnt mentioned the change of the VAR-reference directly (or not clear enough) here:
https://github.com/microsoft/ALAppExtensions/issues/24028

We want to skip the creation depending on the deliverability calculation assigned to WhseShptLineQty and WhseShptLineQtyBase

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14309.
