### ISSUE TITLE
[Event Request] Codeunit 5899 "Calc. Inventory Value-Check"

### ISSUE THREAD

**Issue by arturulfig** [microsoft/ALAppExtensions#25284]
### Describe the request

Our customer in the functionality in the inventory journal using the function of calculating the value of inventory would like to skip some inventory ledger entries. 

In NAV2009 this functionality was available, in BC14 we added in the standard object 5899 its event.

![obraz](https://github.com/microsoft/ALAppExtensions/assets/26385964/d6063365-67fc-4e17-a336-33a5e7a95cb3)

I would ask you to add an event that allows you to skip checking these records.

Proposed event design in object "Calc. Inventory Value-Check", function name: "FindOpenOutboundEntry"

![obraz](https://github.com/microsoft/ALAppExtensions/assets/26385964/8cfaffc6-b9cb-4e14-baf7-52b6cce98b0c)

### Additional context

I need this event in Business Central OnPrem 22, eventually 23.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14309.
