### ISSUE TITLE
[Change Request] page 380 "Bank Acc. Reconciliation Lines" - protected war

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#25296]
### Describe the request

Hello, can you please change the follow variables as protected var?
TotalDiff, Balance, TotalBalance

```
    var
        BankAccReconciliation: Record "Bank Acc. Reconciliation";
        StyleTxt: Text;
        TotalDiffEnable: Boolean;
        TotalBalanceEnable: Boolean;
        BalanceEnable: Boolean;

    protected var
        TotalDiff: Decimal;
        Balance: Decimal;
        TotalBalance: Decimal;
```

### Additional context

We would like access of the variable from our Page Extension.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14454.
