### ISSUE TITLE
[Event Parameter Change] codeunit 80 "Sales-Post" - OnPostUpdateOrderLineOnBeforeGetQuantityShipped & OnPostUpdateOrderLineOnBeforeGetReturnQtyReceived

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25292]
### Describe the request

The following existing event procedures in codeunit 80 "Sales-Post":
OnPostUpdateOrderLineOnBeforeGetReturnQtyReceived
OnPostUpdateOrderLineOnBeforeGetQuantityShipped

do not pass parameter TempSalesLine as 'var'. The latter is also missing the SalesHeader variable as parameter.

    [IntegrationEvent(false, false)]
    local procedure OnPostUpdateOrderLineOnBeforeGetQuantityShipped(var TempSalesLine: Record "Sales Line"; var IsHandled: Boolean; var SalesHeader: Record "Sales Header")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnPostUpdateOrderLineOnBeforeGetReturnQtyReceived(var TempSalesLine: Record "Sales Line"; var IsHandled: Boolean; var SalesHeader: Record "Sales Header")
    begin
    end;

### Additional context

In codeunit 90 "Purch.-Post" the same procedure PostUpdateOrderLine, you have pretty much the same events that I needed to use. Usually if you go there you need to do the same along the sales posting part and found out it did not work as expected.
I was happy that I could use OnPostUpdateOrderLineOnBeforeInitTempSalesLineQuantities but found it strange that events between sales<->purchase<->service are not kept in synch. It leads to much more work.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14309.
