### ISSUE TITLE
New validation triggers in "Phone No." fields are not designed properly.

### ISSUE THREAD

**Issue by ThomasBrodkorb** [Microsoft/ALAppExtensions#253]
For everybody who wants (needs to) apply the same tests as Microsoft now does in the phone number fields, the code cannot be copied to extensions as DotNet code is not supported.

Please consider redesign to test in a function in a "Validation" Codeunit instead:

DataValidationMgt.TestForValidPhoneNo("Phone No.");

**Comment by JesperSchulz** [comment]
Thank you for your suggestion! We are currently working on a bigger effort to make .NET functionality available to extensions. In the short run, this can either be achieved as you describe, by wrapping functions/functionality using .NET in APIs for extensions to call, or by wrapping the .NET call specifically for extensions to use. Your particular Phone No. example will be covered by that larger effort and you can hence expect an update of some sort in the upcoming release. I will close the issue for now, as we are aware of this issue in a broader perspective and are working on a generic solution.
Thanks a lot for reporting on your blockers!
