### ISSUE TITLE
[Protected var request] page 99000816 "Production Order Statistics" 

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25309]
<br /><br />Internal work item: AB#492584

Describe the request
protected var
StdCost: array[6] of Decimal;
ExpCost: array[6] of Decimal;
ActCost: array[6] of Decimal;

Additional context
Our customers also want a calculation of the variance between actual and expected cost.

**Comment by AlexanderYakunin** [comment]
Which vars do you need as protected?

**Comment by Duizy1971** [comment]
'Internal work item: AB#492584' were did all my text go? What did mazhelez been editing?

**Comment by Duizy1971** [comment]
![image](https://github.com/microsoft/ALAppExtensions/assets/30273162/d92075e0-6e9b-452e-a376-6f46c13a3863)
