### ISSUE TITLE
Request addition of UsageCategory in Pages 7341 "Whse. Shipment Lines" and 7342 Whse. Receipt Lines to allow search and bookmark

### ISSUE THREAD

**Issue by RobynGee** [microsoft/ALAppExtensions#25300]
### Describe the request

Request addition of UsageCategory in Pages 7341 "Whse. Shipment Lines" and 7342 Whse. Receipt Lines to allow search and bookmark

### Additional context

to allow users to search and bookmark the pages

**Comment by JakovljevicDusan** [comment]
Hi @RobynGee,

This is probably good idea, but we cannot process it here. Please submit this as idea at aka.ms/bcideas.
