### ISSUE TITLE
[EventModification] Codeunit 80 "Sales-Post" OnValidatePostingAndDocumentDateOnAfterCalcPostingDateExists

### ISSUE THREAD

**Issue by jchaloupka1** [microsoft/ALAppExtensions#25305]
<br /><br />Internal work item: AB#492511

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14309.
