### ISSUE TITLE
[Event Parameter Request] table 5870 "BOM Buffer" - OnAfterInitFromItem

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25320]
### Describe the request

    OnAfterInitFromItem(Rec, Item, SKU);
    
    [IntegrationEvent(false, false)]
    local procedure OnAfterInitFromItem(var BOMBuffer: Record "BOM Buffer"; Item: Record Item; SKU: Record "Stockkeeping Unit");
    begin
    end;

### Additional context

procedure GetSKUFromFilter is not global. Have to do a lot of code copy to get to the same record which is already retrived in Base code<br /><br />Internal work item: AB#492628

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14309.
