### ISSUE TITLE
[Event Request] Codeunit 1605 "PEPPOL Management" event to modify account supplier party info

### ISSUE THREAD

**Issue by CarlOhlsson** [microsoft/ALAppExtensions#25321]
### Describe the request

In Codeunit 1605 "PEPPOL Management" add this event in procedure "GetAccountingSupplierPartyInfoByFormat"

`[IntegrationEvent(false, false)]
local procedure OnAfterGetAccountingSupplierPartyInfoByFormat(var SupplierEndpointID: Text; var SupplierSchemeID: Text; var SupplierName: Text; IsBISBilling: Boolean)
begin
end;`

### Additional context

Currently many functions in this codeunit already have events for example "OnAfterGetAccountingSupplierPartyLegalEntityByFormat". But for some reason the procedure "GetAccountingSupplierPartyInfoByFormat" does not have any event. In order to make the peppol xmlport work right now i have to make my own copy of the santdard xmlport 1610  "Sales Invoice - PEPPOL BIS 3.0" or modify the generated xml file.
<br /><br />Internal work item: AB#492645

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14309.
