### ISSUE TITLE
[Var Request] Table 1003 "Job Planning Line".OnBeforeUpdateUnitCost

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#25326]
### Describe the request

Please add "var" to parameter in event
```
//------------------------------------------------------------OnBeforeUpdateUnitCost:BEGIN
[IntegrationEvent(false, false)]
//local procedure OnBeforeUpdateUnitCost(JobPlanningLine: Record "Job Planning Line"; var IsHandled: Boolean; xJobPlanningLine: Record "Job Planning Line")
local procedure OnBeforeUpdateUnitCost(var JobPlanningLine: Record "Job Planning Line"; var IsHandled: Boolean; xJobPlanningLine: Record "Job Planning Line")
begin
end;
//------------------------------------------------------------OnBeforeUpdateUnitCost:END
```

### Additional context

We need update value from subscriber.<br /><br />Internal work item: AB#492734

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14606.
