### ISSUE TITLE
Change scope OnPrem to Cloud for system table 2000000204 Page Info And Fields

### ISSUE THREAD

**Issue by EvaCegeka** [microsoft/ALAppExtensions#25332]
### Describe the request

System table 2000000204 Page Info And Fields has scope OnPrem. Can this property be removed from the table so it's accessible and viewable in cloud context as well? Looking at the table, there does not seem to be a reason for this table to be limited to OnPrem. It's also the source table for page inspection, which should be usable from cloud as well.

### Additional context

Page inspection should not be limited to OnPrem, but should be accessible from Cloud as well. There does not seem to be a reason for this table to be limited to scope OnPrem.<br /><br />Internal work item: [AB#492796](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/492796)

**Comment by DonHendriksen** [comment]
@AleksandricMarko, can you please give an update on this request. It is there for some month now without any progress. Thanks in advance.

**Comment by AlexanderYakunin** [comment]
The Page Info And Fields provider is designed specifically for the Page Inspector, and we do not intend to make it Cloud scope.
