### ISSUE TITLE
[Extensibility Bug] Codeunit 22 - "ApplyItemLedgEntry" SetLoadFields raises JIT load Error

### ISSUE THREAD

**Issue by mdemaio9** [microsoft/ALAppExtensions#25343]
Hello,
we found an Extensibility Bug in BC23 in the event "OnApplyItemLedgEntryOnAfterCloseReservEntry" of the procedure "ApplyItemLedgEntry" in the codeunit "Item Jnl.-Post Line" (22).
In this event, we have to read extended fields on the parameter Record "ReservEntry", but we receive a JIT error, because extended fields aren't loaded.
This is due to the fact that before the event there is a SetLoadFields on the Record "ReservEntry" and then this record is deleted.
We can't load extended fields then and it raises JIT load events.

![image](https://github.com/microsoft/ALAppExtensions/assets/92147701/22b35776-4a15-456b-9450-774728147b6a)

We need so an event "OnAfterSetLoadFieldsOnReservEntry", after the "SetLoadFields" on the "ReservEntry" to do "AddLoadFields".

`               
                
                ReservEntry.SetLoadFields("Entry No.", Positive, "Item No.", "Quantity (Base)");
                // Event here - start
                OnApplyItemLedgEntryOnAfterSetLoadFieldsOnReservEntry(ReservEntry);
                // Event here - end
                if not Handled then
                    if FirstReservation then begin
                        FirstReservation := false;
                        ReservEntry.Reset();
                        ReservEntry.SetCurrentKey(
                          "Source ID", "Source Ref. No.", "Source Type", "Source Subtype",
                          "Source Batch Name", "Source Prod. Order Line", "Reservation Status");
                        ReservEntry.SetRange("Reservation Status", ReservEntry."Reservation Status"::Reservation);
                        ItemJnlLine.SetReservationFilters(ReservEntry);
                        ReservEntry.SetRange("Item No.", ItemJnlLine."Item No.");
                    end;
               ......
                UseReservationApplication := ReservEntry.FindFirst();
               .......
                if UseReservationApplication then begin
                    ......
                    OnApplyItemLedgEntryOnBeforeCloseReservEntry(OldItemLedgEntry, ItemJnlLine, ItemLedgEntry);
                    ReservEngineMgt.CloseReservEntry(ReservEntry, false, false);
                    
                    OnApplyItemLedgEntryOnAfterCloseReservEntry(OldItemLedgEntry, ItemJnlLine, ItemLedgEntry, ReservEntry);

                    OldItemLedgEntry.CalcReservedQuantity();
                    AppliedQty := -Abs(ReservEntry."Quantity (Base)");`

[IntegrationEvent(false, false)]
    local procedure OnApplyItemLedgEntryOnAfterSetLoadFieldsOnReservEntry(var ReservEntry: Record "Reservation Entry")
    begin
    end;

### Additional context

This is business critical because we have an AppSource app and there isn't a workaround.<br /><br />Internal work item: AB#493050

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16016.
