### ISSUE TITLE
[Extensibility/Access Request] - table 1003 "Job Planning Line" - GetJob

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#25342]
### Describe the request

Could you please change the Access of the method `GetJob` to public, that we can call this methods from Event Subscribers (and Extensions).

Additionally please add the `Record Job` as return parameter. Then we can use this procedure to Get current Job withouth an additional SQL-Statement if the `Job` variable is still pointing to the correct Job.

```al
//+Change
//-local procedure GetJob()
procedure GetJob() : Record Job
//-Change
begin
    if ("Job No." <> Job."No.") and ("Job No." <> '') then
        Job.Get("Job No.");
    OnAfterGetJob(Rec, Job);
end;
```

### Additional context

This pattern would be very useful for extensibility.
The SalesHeader and the PurchHeader have equivalent methods for getting the Header Data Structure.<br /><br />Internal work item: AB#492960

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14454.
