### ISSUE TITLE
Page Sales Invoice Subform OnNewRecordEvent

### ISSUE THREAD

**Issue by benjaminknapper** [microsoft/ALAppExtensions#2534]
**Describe the bug**
Using the OnNewRecordEvent Event Subscriber I am unable to update the default line type from Item to G/L Account. This exact same process works for Sales Quote Subform and Sales Order Subform.

**To Reproduce**
1) Subscribe to OnNewRecordEvent of the Sales InvoiceSubform page
2) Set Rec.Type to G/L Account

``` AL Code to reproduce the issue ```
![image](https://user-images.githubusercontent.com/11381404/57955398-75acff00-78bb-11e9-9780-7647de8a1244.png)

**Expected behavior**
When I create a new Sales Invoice the default line type is G/L Account

**Versions:**

 - AL Language: 3.0.126610

 - Business Central: 
GB Dynamics NAV 13.5 (31962)
&
Platform 14.0.29530.32211 + Application 31808 (US Dynamics NAV 14.0)

**Comment by JohanStenberg100** [comment]
Hi @benjaminknapper! I have transferred this issue to our extensions repository. Thanks
