### ISSUE TITLE
[Event Request] Codeunit 449 "Job Queue Start Codeunit" Related with #24946 

### ISSUE THREAD

**Issue by TiagoVeigaTNP** [microsoft/ALAppExtensions#25344]
### Describe the request

update on #24946    

### Additional context

Hi,

can we've an update on #24946   

https://github.com/microsoft/ALAppExtensions/issues/24946

in October was marked as "Ships in future update" but it was not included in BC23.

Can you let us know when this will be released for SaaS?

thanks,
regards,

**Comment by pri-kise** [comment]
The feature freeze for BC23 was in September.
Therefore any event request in october can only be included in a cumulative update or BC24

**Comment by JakovljevicDusan** [comment]
Hi @TiagoVeigaTNP,

Event publisher OnBeforeActivateErrorMessageHandler is included in 23.1.
