### ISSUE TITLE
[Parameter Request] IsHandled to publisher OnBeforeCreateFromSalesOrder - codeunit 5752 "Get Source Doc. Outbound"

### ISSUE THREAD

**Issue by greexw** [microsoft/ALAppExtensions#25350]
### Describe the request

Hi there,

I would like to ask you to add additional parameter: IsHandled to publisher OnBeforeCreateFromSalesOrde - CU 5752 "Get Source Doc. Outbound":

Original code:
```al
    procedure CreateFromSalesOrder(SalesHeader: Record "Sales Header")
    begin
        OnBeforeCreateFromSalesOrder(SalesHeader);
        ShowResult(CreateFromSalesOrderHideDialog(SalesHeader));
    end;
```

Changed code:

```al
    procedure CreateFromSalesOrder(SalesHeader: Record "Sales Header")
    var 
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCreateFromSalesOrder(SalesHeader, IsHandled);
        if not IsHandled then
            ShowResult(CreateFromSalesOrderHideDialog(SalesHeader));
    end;
```

```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateFromSalesOrder(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

Upgrade<br /><br />Internal work item: AB#493221

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14606.
