### ISSUE TITLE
Sales Line - OnBeforeUpdatePlanned

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#25352]
### Describe the request

Table Sales Line needs an OnBefore event publisher, allowing to skip the UpdatePlanned procedure. (Maybe for some the return value would be required, for us it's not )

```
procedure UpdatePlanned(): Boolean
    var
        IsHandled: Boolean;
    begin
        OnBeforeUpdatePlanned(IsHandled); ///
        if IsHandled then
            exit;
        
        TestField("Qty. per Unit of Measure");
        CalcFields("Reserved Quantity");
        if Planned = ("Reserved Quantity" = "Outstanding Quantity") then
            exit(false);
        Planned := not Planned;
        exit(true);
    end;

     [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdatePlanned(var IsHandled: Boolean)
    begin
    end;
```

### Additional context

This is especially useful when creating **temporary** sales line record to simulate price calculation, allowing to skip the redundant "Reserved Quantity" calculation, which queries the Reservation Entry table
<br /><br />Internal work item: AB#493252

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14606.
