### ISSUE TITLE
[Protected Var Request] report 99000754 "Rolled-up Cost Shares"

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25357]
### Describe the request

protected var:
        ProdBOMLine: array[99] of Record "Production BOM Line";
        CalculateDate: Date;
        Level: Integer;
        Index: Integer;
        NextIndex: Integer;
        VersionCode: array[99] of Code[20];
        NoListType: array[99] of Option Item,"Production BOM";
        NoList: array[99] of Code[20];
        LotSize: array[99] of Decimal;
        MfgItemQtyBase: array[99] of Decimal;
        Quantity: array[99] of Decimal;

### Additional context

We have extensive "Routing Link Code", Recipe Factor and "Calculation Formula" enhancements in our addon which we cannot provide without these protected var. We have to resort to a report copy which we do not want.<br /><br />Internal work item: AB#493279

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14454.
