### ISSUE TITLE
Sales Header - OnBeforeSetCompanyBankAccount

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#25354]
### Describe the request

Table Sales Header needs an OnBefore event publisher, allowing to skip the SetCompanyBankAccount procedure.

```
local procedure SetCompanyBankAccount()
    var
        BankAccount: Record "Bank Account";
        IsHandled: Boolean;
    begin
        OnBeforeSetCompanyBankAccount(IsHandled); ////
        if IsHandled then
            exit;
        
        Validate("Company Bank Account Code", BankAccount.GetDefaultBankAccountNoForCurrency("Currency Code"));
        OnAfterSetCompanyBankAccount(Rec, xRec);
    end;

     [IntegrationEvent(false, false)]
    local procedure OnBeforeSetCompanyBankAccount(var IsHandled: Boolean)
    begin
    end;
```

### Additional context

This is especially useful when creating temporary sales header record to simulate price calculation, to skip the company bank account code<br /><br />Internal work item: AB#493255

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14606.
