### ISSUE TITLE
[Event Request] report 5852 "Suggest Capacity Standard Cost" - OnInsertStdCostWkshOnBeforeInsert

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25359]
### Describe the request

    local procedure InsertStdCostWksh(Type2: Option; No2: Code[20])
    begin
        with ToStdCostWksh do begin
            Init();
            Validate("Standard Cost Worksheet Name", ToStdCostWkshName);
            Validate(Type, Type2);
            Validate("No.", No2);

            Validate(
              "New Standard Cost",
              RoundAndAdjustAmt("Standard Cost", RoundingMethod[1], AmtAdjustFactor[1]));
            Validate(
              "New Indirect Cost %",
              RoundAndAdjustAmt("Indirect Cost %", RoundingMethod[2], AmtAdjustFactor[2]));
            Validate(
              "New Overhead Rate",
              RoundAndAdjustAmt("Overhead Rate", RoundingMethod[3], AmtAdjustFactor[3]));

            OnInsertStdCostWkshOnBeforeInsert(ToStdCostWksh, RoundingMethod, AmtAdjustFactor);
            if not Insert(true) then
                Modify(true);
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnInsertStdCostWkshOnBeforeInsert(var ToStdCostWksh: Record "Standard Cost Worksheet"; RoundingMethod: array[3] of Code[10]; AmtAdjustFactor: array[3] of Decimal)
    begin
    end;

### Additional context

Just because we need it...<br /><br />Internal work item: AB#493280

**Comment by Duizy1971** [comment]
Hmm, a bit of extra work here. It seems this event exists in W1 23.01 but not in the NL localization. How is that possible?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14606.
