### ISSUE TITLE
[Event Request] report 5706 "Create Stockkeeping Unit" - OnAfterCreateSKU

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25365]
### Describe the request

    procedure CreateSKU(var Item2: Record Item; LocationCode: Code[10]; VariantCode: Code[10])
    begin
        StockkeepingUnit.Init();
        ....
        OnBeforeStockkeepingUnitInsert(StockkeepingUnit, Item2);
        StockkeepingUnit.Insert(true);
        
        OnAfterCreateSKU(StockkeepingUnit, Item2);
    end;

    [IntegrationEvent(true, false)]
    local procedure OnAfterCreateSKU(var StockkeepingUnit: Record "Stockkeeping Unit"; Item: Record Item)
    begin
    end;        

### Additional context

The OnBeforeStockkeepingUnitInsert is not good enough to use because we need to validate the SKU."Standard Cost" with a new value as a customization and that Base field containts a Modify on Rec so the record must exist first.<br /><br />Internal work item: AB#493435

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14518.
