### ISSUE TITLE
[External Request] - codeunit 11518 "Swiss QR-Bill Mgt."

### ISSUE THREAD

**Issue by maerbeia** [microsoft/ALAppExtensions#25361]
### Describe the request

Would it be possible to change the visibility of the function DeleteTenantMedia in Codeunit 11518 to external?

```al
    internal procedure DeleteTenantMedia(MediaId: Guid)
    var
        TenantMedia: Record "Tenant Media";
    begin
        if TenantMedia.Get(MediaId) then
            TenantMedia.Delete();       // Tenant Media Thumbnails are also removed
    end;
``` 

### Additional context

We would like to use the functionality in a report extension, but we cannot use this procedure for cleanup after the report generate and it cause remanent media in the tenant media table.<br /><br />Internal work item: AB#493431

**Comment by AlexanderYakunin** [comment]
Sorry, I see no good reason to expose this very simple line of code. Can you simply add this code to your report to remove this record?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15971.
