### ISSUE TITLE
[Enum Request] report 5811 "Calc. Inventory Value - Test" - CalcBase

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25366]
### Describe the request

CalcBase: Option " ","Last Direct Unit Cost","Standard Cost - Assembly List","Standard Cost - Manufacturing";

Could you please make global var CalcBase in R5811 an Enum to existing enum 5899 "Inventory Value Calc. Base" like has been done previously in report 5899 "Calculate Inventory Value"?

### Additional context

We are in dire need for an extra enum value 'Standard Cost - Item/SKU' to supply a customer customization
Internal work item: AB#495835

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15245.
