### ISSUE TITLE
Inconsistent in Parameters on event OnCreateDimOnBeforeUpdateLines between objects

### ISSUE THREAD

**Issue by FBakkensen** [microsoft/ALAppExtensions#25372]
### Describe the request

The event `OnCreateDimOnBeforeUpdateLines` is found in 3 objects `Sales Header` , `Purchase Header` and `Service Header` but the list af parameters is different.

The event on `Sales Header` has the correct parameters.
`local procedure OnCreateDimOnBeforeUpdateLines(var SalesHeader: Record "Sales Header"; xSalesHeader: Record "Sales Header"; CurrentFieldNo: Integer; OldDimSetID: Integer; DefaultDimSource: List of [Dictionary of [Integer, Code[20]]])`

Both `Purchase Header` and `Service Header` is missing the last 2 parameters (OldDimSetID, DefaultDimSource)

`local procedure OnCreateDimOnBeforeUpdateLines(var PurchaseHeader: Record "Purchase Header"; xPurchaseHeader: Record "Purchase Header"; CurrentFieldNo: Integer)`

`local procedure OnCreateDimOnBeforeUpdateLines(var ServiceHeader: Record "Service Header"; xServiceHeader: Record "Service Header"; CurrentFieldNo: Integer)`

### Additional context

To handle the same issue in a consistent way on both Sales, Purchase and Service<br /><br />Internal work item: AB#493634

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14518.
