### ISSUE TITLE
[Event Request] Report 31287 "Create General Journal CZB" - procedure ApplyGeneralJournalLine()

### ISSUE THREAD

**Issue by jlorenc01** [microsoft/ALAppExtensions#25373]
### Describe the request

Hello,

I would like to ask for a new publisher in the report 31287 "Create General Journal CZB", procedure ApplyGeneralJournalLine(). We need to set additional filters on GenJournalLine. Thank you.

```
local procedure ApplyGeneralJournalLine(IssBankStatementHeaderCZB: Record "Iss. Bank Statement Header CZB") Result: Boolean
var
    GenJournalLine: Record "Gen. Journal Line";
begin
    Result := true;
    GetBankAccount(IssBankStatementHeaderCZB);
    GenJournalLine.SetRange("Journal Template Name", BankAccount."Payment Jnl. Template Name CZB");
    GenJournalLine.SetRange("Journal Batch Name", BankAccount."Payment Jnl. Batch Name CZB");
    GenJournalLine.SetRange("Document No.", IssBankStatementHeaderCZB."No.");
    OnApplyGeneralJournalLineOnAfterSetGenJournalLineFilters(GenJournalLine, IssBankStatementHeaderCZB, BankAccount); // NEW EVENT
    if GenJournalLine.FindSet() then begin
        Commit(); // the matching bank payment should not rollback already created general journal lines in case of error
        repeat
            ...
        until GenJournalLine.Next() = 0;
    end;
end;

// NEW EVENT
[IntegrationEvent(false, false)]
local procedure OnApplyGeneralJournalLineOnAfterSetGenJournalLineFilters(var GenJournalLine: Record "Gen. Journal Line"; IssBankStatementHeaderCZB: Record "Iss. Bank Statement Header CZB"; BankAccount: Record "Bank Account")
begin
end;
```

### Additional context

We need to set additional filters on GenJournalLine.<br /><br />Internal work item: AB#493646

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 14634.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14639.
