### ISSUE TITLE
Extensibility question - OnAfterUpdateItem and OnAfterUpdateItemVariant  - Possibility to update items through event

### ISSUE THREAD

**Issue by viktorglemne** [microsoft/ALAppExtensions#25377]
### Describe the request

Hi! 

I have mailed with Andrei Panko regarding the possibility to update items and item variants through Shopify event OnAfterUpdateItem and OnAfterUpdateItemVariant in Codeunit 30188 "Shpfy Update Item". The solutions today do not make it possible for extend if some specifik field is not updated, becouse of the function DoUpdateItem and DoUpdateItemVariant thats in the object codeunit 30188 "Shpfy Update Item". 

An solutions for this wolud be, to change line 37 and line 45 
![image](https://github.com/microsoft/ALAppExtensions/assets/54137375/308ae9a3-1a4a-431f-8cb8-720fa2833cab)

so it like this instead, 

`if not IsHandled then
      DoUpdateItem(ShopifyProduct, Item)
      ProductEvents.OnAfterUpdateItem(Shop, ShopifyProduct, Rec, Item);`
![image](https://github.com/microsoft/ALAppExtensions/assets/54137375/a0f38ce0-6698-45d1-9c21-7be753f9a3ab)

`
if not IsHandled then begin
                        CreateItem.CreateReferences(ShopifyProduct, Rec, Item, ItemVariant);
                        DoUpdateItemVariant(Rec, ItemVariant)
                        ProductEvents.OnAfterUpdateItemVariant(Shop, ShopifyProduct, Rec, Item, ItemVariant);
                    end;
`
![image](https://github.com/microsoft/ALAppExtensions/assets/54137375/5b575e4a-b025-4040-a2e7-4fdbc0a77f86)

and then the change DoUpdateItem and DoUpdateItemVariant should't have a return value, so instead of this 
![image](https://github.com/microsoft/ALAppExtensions/assets/54137375/258ce1e8-caf2-43b3-bf08-652a3a11a256)
it should look like this
![image](https://github.com/microsoft/ALAppExtensions/assets/54137375/7d7d9cd1-a076-4d02-a05a-e1e2a796ea96)

This is an issue for our customer and would be nice to have done. 
Hope I am clear on what i want and you understand me and maybe even have a better solution for it. 

### Additional context

Like described above this is for a customer that need to have diffrent field from shoipfy to BC Updated and right now i don't have any event for that. The email converstion can be found from Andrei Panko regarding subject _Shopify/BC New items does not get created in BC after sync_

**Comment by dannoe** [comment]
Just another idea: 
Why not put new events in DoUpdateItem and DoUpdateItemVariant right before the ``Modify`` calls?

```diff
 local procedure DoUpdateItem(var ShopifyProduct: Record "Shpfy Product"; var Item: Record Item): Boolean
    var
        ItemCategory: Record "Item Category";
        Vendor: Record Vendor;
        IsModified: Boolean;
    begin
        if Item.Description <> ShopifyProduct.Title then begin
            IsModified := true;
            Item.Description := ShopifyProduct.Title;
        end;
        if ShopifyProduct."Product Type" <> '' then begin
            ItemCategory.SetFilter(Description, '@' + ShopifyProduct."Product Type");
            if ItemCategory.FindFirst() then
                if Item."Item Category Code" <> ItemCategory.Code then begin
                    IsModified := true;
                    Item."Item Category Code" := ItemCategory.Code;
                end;
        end;
        if ShopifyProduct.Vendor <> '' then begin
            Vendor.SetFilter(Name, '@' + ShopifyProduct.Vendor);
            if Vendor.FindFirst() then
                if Item."Vendor No." <> Vendor."No." then begin
                    IsModified := true;
                    Item."Vendor No." := Vendor."No.";
                end;
        end;
+      ProductEvents.OnDoUpdateItemBeforeModify(Shop, ShopifyProduct, Item, IsModified);
        if IsModified then
            exit(item.Modify());
+      exit(false);
    end;

    local procedure DoUpdateItemVariant(ShopifyVariant: Record "Shpfy Variant"; var ItemVariant: Record "Item Variant"): Boolean
+   var
+      IsModified: Boolean;
    begin
        if ItemVariant.Description <> ShopifyVariant.Title then begin
            ItemVariant.Description := ShopifyVariant.Title;
-            exit(ItemVariant.Modify());
+           IsModified := true;
        end;
+       ProductEvents.OnDoUpdateItemVariantBeforeModify(Shop, ShopifyVariant, ItemVariant, IsModified);
+       if IsModified then
+           exit(ItemVariant.Modify());
+       exit(false);
    end;

+    [IntegrationEvent(false, false)]
+    internal procedure OnDoUpdateItemVariantBeforeModify(Shop: Record "Shpfy Shop"; var ShopifyProduct: Record "Shpfy Product"; ShopifyVariant: var Item: Record Item; var IsModified: Boolean);
+    begin
+    end;

+    [IntegrationEvent(false, false)]
+    internal procedure OnDoUpdateItemVariantBeforeModify(Shop: Record "Shpfy Shop"; ShopifyVariant: Record "Shpfy Variant"; var ItemVariant: Record "Item Variant"; var IsModified: Boolean);
+    begin
+    end;

```
