### ISSUE TITLE
[Event Request] Report 31287 "Create General Journal CZB" - procedure DeleteGeneralJournalLines()

### ISSUE THREAD

**Issue by jlorenc01** [microsoft/ALAppExtensions#25374]
### Describe the request

Hello,

I would like to ask for a new publisher in the report 31287 "Create General Journal CZB", procedure DeleteGeneralJournalLines(). We need to set additional filters on GenJournalLine. Thank you.

```
local procedure DeleteGeneralJournalLines(IssBankStatementHeaderCZB: Record "Iss. Bank Statement Header CZB")
var
    GenJournalLine: Record "Gen. Journal Line";
begin
    GenJournalLine.SetRange("Journal Template Name", BankAccount."Payment Jnl. Template Name CZB");
    GenJournalLine.SetRange("Journal Batch Name", BankAccount."Payment Jnl. Batch Name CZB");
    GenJournalLine.SetRange("Document No.", IssBankStatementHeaderCZB."No.");
    GenJournalLine.SetRange(Amount, 0);
    OnDeleteGeneralJournalLinesOnAfterSetGenJournalLineFilters(); // NEW EVENT
    GenJournalLine.DeleteAll(true);
end;

// NEW EVENT
[IntegrationEvent(false, false)]
local procedure OnDeleteGeneralJournalLinesOnAfterSetGenJournalLineFilters(var GenJournalLine: Record "Gen. Journal Line"; IssBankStatementHeaderCZB: Record "Iss. Bank Statement Header CZB"; BankAccount: Record "Bank Account")
begin
end;
```

### Additional context

We need to set additional filters on GenJournalLine.<br /><br />Internal work item: AB#493645

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 14634.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14639.
