### ISSUE TITLE
[Event Change Request] Codeunit 7322 "Create Inventory Pick/Movement" event OnBeforeAutoCreatePickOrMove

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#25370]
### Describe the request

Please can you set the IncludeSender parameter to true for the above event.

### Additional context

A while back I requested several functions in this codeunit to be changed from local to global so that I could use them to use my own logic to create pick lines. I have started using these now and am testing and have discovered problems because I need to call the functions on the same **instance** of the codeunit that the events were raised from (as there are several global variables which are needed/used in the called global function).<br /><br />Internal work item: AB#493578

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14518.
