### ISSUE TITLE
[Event Request] report 5855 "Implement Standard Cost Change" - OnUpdateSKUOnBeforeValidateStandardCost

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25375]
### Describe the request

    local procedure UpdateSKU(StdCostWksh: Record "Standard Cost Worksheet")
    var
        SKU: Record "Stockkeeping Unit";
        NewStandardCost: Decimal;
    begin
        with SKU do begin
            SetRange("Item No.", StdCostWksh."No.");
            if Find('-') then begin
                SKUCostsUpdated := true;
                repeat
                    //Validate("Standard Cost", StdCostWksh."New Standard Cost");
                    NewStandardCost := StdCostWksh."New Standard Cost";
                    OnUpdateSKUOnBeforeValidateStandardCost(SKU, StdCostWksh, NewStandardCost);
                    Validate("Standard Cost", NewStandardCost);
                    Modify(true);
                until Next() = 0;
            end;
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnUpdateSKUOnBeforeValidateStandardCost(var SKU: Record "Stockkeeping Unit"; var StandardCostWorksheet: Record "Standard Cost Worksheet"; var NewStandardCost: Decimal;)
    begin
    end;

### Additional context

A few of our customers  have some brilliant financial minds which requires some different approaches to the was Item and stockkeeping costs are handled. They go so far as having a customization SKU."Transfer Overhead Rate" and other kinds of extra cost variables.<br /><br />Internal work item: AB#493653

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14518.
