### ISSUE TITLE
[Variable Enum Request] CalculatePer: Option "Item Ledger Entry",Item

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25378]
### Describe the request

The variable CalculatePer: Option "Item Ledger Entry",Item is being used in:
codeunit 5899 "Calc. Inventory Value-Check"
report 5899 "Calculate Inventory Value"
report 5811 "Calc. Inventory Value - Test"
report 5855 "Implement Standard Cost Change"

we would like it to become an Enum in the Base for obvious reasons.

Both below mentioned procedures should also be set to obsolete and copied to a new procedure with Option->Enum as NewCalculatePer parameter

1. codeunit 5899 "Calc. Inventory Value-Check" procedure SetProperties(NewPostingDate: Date; NewCalculatePer: Option
2. report 5899 "Calculate Inventory Value" procedure InitializeRequest(NewPostingDate: Date; NewDocNo: Code[20]; NewHideDuplWarning: Boolean; NewCalculatePer: Option

### Additional context

It just needs to be an enum so we can call the initialize procedure more easily and can enhance the value for customization sake.<br /><br />Internal work item: AB#493701

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15245.
