### ISSUE TITLE
Event Request] CU- Page Management -OnBeforeValidateGetSalesHeaderPageID

### ISSUE THREAD

**Issue by ShivamLodhi795** [microsoft/ALAppExtensions#25389]
### Describe the request

local procedure GetSalesHeaderPageID(RecRef: RecordRef): Integer
    var
        SalesHeader: Record "Sales Header";
    begin
        RecRef.SetTable(SalesHeader);
        //Shivam++
        IsHandled1 := false;
        OnBeforeValidateGetSalesHeaderPageID(SalesHeader, IsHandled1);
        if not IsHandled1 then begin
            case SalesHeader."Document Type" of
                SalesHeader."Document Type"::Quote:
                    exit(PAGE::"Sales Quote");
                SalesHeader."Document Type"::Order:
                    exit(PAGE::"Sales Order");
                SalesHeader."Document Type"::Invoice:
                    exit(PAGE::"Sales Invoice");
                SalesHeader."Document Type"::"Credit Memo":
                    exit(PAGE::"Sales Credit Memo");
                SalesHeader."Document Type"::"Blanket Order":
                    exit(PAGE::"Blanket Sales Order");
                SalesHeader."Document Type"::"Return Order":
                    exit(PAGE::"Sales Return Order");
            end;
        end;
    end;

 [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateGetSalesHeaderPageID(var SalesHeader: Record "Sales Header"; var IsHandled1: Boolean)
    begin
    end;

### Additional context

We want to use custom code instead of base code.<br /><br />Internal work item: AB#493940

**Comment by AleksandricMarko** [comment]
Hello @ShivamLodhi795 
You already have available publisher OnBeforeGetConditionalCardPageID which can be used not just for Sales Documents.
