### ISSUE TITLE
[Event Change Request] table 77 "Report Selections" Event OnGetEmailBodyCustomerTextOnAfterNotFindEmailBodyUsage

### ISSUE THREAD

**Issue by kmistrytnp** [microsoft/ALAppExtensions#25386]
### Describe the request

Can the above event have another boolean parameter added (called EmailBodyUsageFound)  and if the event subscriber sets this to true then the code does not exit...

```
if not FindEmailBodyUsageForCust(ReportUsage, CustNo, TempBodyReportSelections) then begin
    IsHandled := false;
    EmailBodyUsageFound := false;   // NEW CODE
    OnGetEmailBodyCustomerTextOnAfterNotFindEmailBodyUsage(
        ReportUsage.AsInteger(), RecordVariant, CustNo, TempBodyReportSelections, IsHandled, EmailBodyUsageFound);   // PARAMETER ADDED
    if not EmailBodyUsageFound then begin   // NEW CODE
        if IsHandled then
            exit(true);
        exit(false);
    end;   // NEW CODE
end;
```

The EmailBodyUsageFound needs to be a var parameter

### Additional context

The reason for this is I want to use my own logic to populate the TempBodyReportSelections with the "Report ID" and the "Email Body Layout Code" of the report/layout I want to use for the email body.

The TempBodyReportSelections  is already a var parameter, but it can't be used at the moment because the code always exits and so the code further down that uses the TempBodyReportSelections never gets called<br /><br />Internal work item: AB#493773

**Comment by kmistrytnp** [comment]
@JesperSchulz Just to give a bit more additional context... I can subscribe to OnSendEmailDirectlyOnBeforeSaveReportAsPDFInTempBlob to run my own logic to use an alternative report/layout for the attachment when sending via email, but I'm currently unable to do the same to the email body.  The requested change will allow me to use my own logic to use an alternative report/layout for the email body.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14883.
