### ISSUE TITLE
[Event Change Request] table 27 Item - Event OnBeforeTestNoItemLedgEntiesExist

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#25384]
### Describe the request

Hello,
would it be possible to get Item as reference in this event. 
var Item: Record Item;

```   
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTestNoItemLedgEntiesExist(var Item: Record Item; CurrentFieldName: Text[100]; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

Need this event to be able to set values on the item with this event to keep the same instance of the item.<br /><br />Internal work item: AB#493707

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14518.
