### ISSUE TITLE
[Event Request} report 840 "Suggest Worksheet Lines" - OnInsertCFLineForPurchaseLineOnBeforeInsertTempCFWorksheetLine

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25385]
### Describe the request

    local procedure InsertCFLineForPurchaseLine()
    ....
                if "Cash Flow Forecast"."Consider CF Payment Terms" and (Vendor."Cash Flow Payment Terms Code" <> '') then
                    "Payment Terms Code" := Vendor."Cash Flow Payment Terms Code"
                else
                    "Payment Terms Code" := PurchHeader."Payment Terms Code";

                OnInsertCFLineForPurchaseLineOnBeforeInsertTempCFWorksheetLine(CFWorksheetLine2, PurchHeader, "Purchase Line");
                InsertTempCFWorksheetLine(CFWorksheetLine2, 0);
            end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnInsertCFLineForPurchaseLineOnBeforeInsertTempCFWorksheetLine(var CashFlowWorksheetLine: Record "Cash Flow Worksheet Line"; var PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line")
    begin
    end;

### Additional context

We need to add additional Purchase values<br /><br />Internal work item: AB#493708

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14518.
