### ISSUE TITLE
[Event Request] codeunit 410 "Update Analysis View" - OnUpdateAnalysisViewEntryOnAfterTempAnalysisViewEntryAssignment

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25387]
### Describe the request

    procedure UpdateAnalysisViewEntry(UpdAnalysisViewEntryBuffer: Record "Upd Analysis View Entry Buffer")
    ....
        TempAnalysisViewEntry."Entry No." := UpdAnalysisViewEntryBuffer.EntryNo;

        OnUpdateAnalysisViewEntryOnAfterTempAnalysisViewEntryAssignment(TempAnalysisViewEntry, AnalysisView, GLEntry, UpdAnalysisViewEntryBuffer);

        if TempAnalysisViewEntry.Find() then begin
        ....
    end;

    [IntegrationEvent(false, false)]
    local procedure OnUpdateAnalysisViewEntryOnAfterTempAnalysisViewEntryAssignment(TempAnalysisViewEntry: Record "Analysis View Entry"; var AnalysisView: Record "Analysis View"; var GLEntry: Record "G/L Entry"; var UpdAnalysisViewEntryBuffer: Record "Upd Analysis View Entry Buffer")
    begin
    end;

### Additional context

G/L Account analysis views has a compri value that is not in the dimensions. Besides that, the budget event is present and this one isn't.<br /><br />Internal work item: AB#493772

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14883.
