### ISSUE TITLE
[Event Request] Table 64 "Merge Duplicates Buffer" events

### ISSUE THREAD

**Issue by NagRus** [microsoft/ALAppExtensions#25390]
### Describe the request

  Hi, we need some standard events in table 64 "Merge Duplicates Buffer" procedures. IsHandled parameter is optional.
  
    local procedure MergeContacts()
    var
        IsHandled: Boolean;
        Contact: array[2] of Record Contact;
    begin
        OnBeforeMergeContacts(Rec, IsHandled);
        if IsHandled then
            exit;

        Contact[2].Get(Current);
        Contact[1].Get(Duplicate);

        MergeRecords(Contact[1].RecordId, Contact[2].RecordId, 0);
        Contact[2].Find();
        Contact[2].UpdateBusinessRelation();
        Contact[2].Modify();

        OnAfterMergeContacts(Rec, Contact);
    end;
    
    [IntegrationEvent(false, false)]
    local procedure OnBeforeMergeContacts(Rec: record "Merge Duplicates Buffer"; var IsHandled: Boolean)
    begin
    end;
    
    [IntegrationEvent(false, false)]
    local procedure OnAfterMergeContacts(Rec: record "Merge Duplicates Buffer"; var Contact: array[2] of Record Contact)
    begin
    end;
    
        local procedure MergeCustomers()
    var
        IsHandled: Boolean;
        Customer: array[2] of Record Customer;
    begin
        OnBeforeMergeCustomers(Rec, IsHandled);
        if IsHandled then
            exit;

        Customer[1].Get(Duplicate);
        Customer[2].Get(Current);
        MoveCommentLinesFromDuplicateToCurrent("Comment Line Table Name"::Customer, Customer[1]."No.", Customer[2]."No.");
        MergeRecords(Customer[1].RecordId, Customer[2].RecordId, Customer[1].FieldNo(SystemId));

        OnAfterMergeCustomers(Rec, Customer);
    end;
    
    [IntegrationEvent(false, false)]
    local procedure OnBeforeMergeCustomers(Rec: Record "Merge Duplicates Buffer"; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterMergeCustomers(Rec: Record "Merge Duplicates Buffer"; Customer: array[2] of Record Customer)
    begin
    end;
    
        local procedure MergeVendors()
    var
        IsHandled: Boolean;
        Vendor: array[2] of Record Vendor;
    begin
        OnBeforeMergeVendors(Rec, IsHandled);
        if IsHandled then
            exit;
        
        Vendor[2].Get(Current);
        Vendor[1].Get(Duplicate);
        MoveCommentLinesFromDuplicateToCurrent("Comment Line Table Name"::Vendor, Vendor[1]."No.", Vendor[2]."No.");
        MergeRecords(Vendor[1].RecordId, Vendor[2].RecordId, Vendor[1].FieldNo(SystemId));
        
        OnAfterMergeVendors(Rec, Vendor);
    end;
    
    [IntegrationEvent(false, false)]
    local procedure OnBeforeMergeVendors(Rec: Record "Merge Duplicates Buffer"; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterMergeVendors(Rec: Record "Merge Duplicates Buffer"; Vendor: array[2] of Record Vendor)
    begin
    end;

### Additional context

We need these events to handle some custom logic when merging customers, vendors and contacts and currently there aren't any events that fits our needs. When merging contacts we must know if customers and vendors of those contacts are already merged and after the merge we need to update fields in our extensions which aren't flowfields.<br /><br />Internal work item: AB#493936

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14883.
