### ISSUE TITLE
[Event Request] Table-Prod. Order Routing Line(trigger OnRename())-OnBeforeValidateRename

### ISSUE THREAD

**Issue by ShivamLodhi795** [microsoft/ALAppExtensions#25396]
### Describe the request

trigger OnRename()
    begin
        //Shivam++
        IsHandled := false;
        OnBeforeValidateRename(Rec, IsHandled);
        if not IsHandled then begin
            Error(Text001, TableCaption);
        end;
        //Shivam--

    end;

 [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateRename(var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var IsHandled: Boolean)
    begin
    end;

### Additional context

We want to comment base code.<br /><br />Internal work item: AB#493933

**Comment by AleksandricMarko** [comment]
Hello @ShivamLodhi795 
We can`t do this kind of change as renaming is forbidden with the purpose.
