### ISSUE TITLE
[Event Request] Table-Transfer Header(field(34; "Shipping Agent Code"; Code[10]))-OnBeforeValidateShippingAgentCode 

### ISSUE THREAD

**Issue by ShivamLodhi795** [microsoft/ALAppExtensions#25398]
### Describe the request

field(34; "Shipping Agent Code"; Code[10])
        {
            AccessByPermission = TableData "Shipping Agent Services" = R;
            Caption = 'Shipping Agent Code';
            TableRelation = "Shipping Agent";

            trigger OnValidate()
            begin
                //Shivam++
                IsHandled := false;
                OnBeforeValidateShippingAgentCode(TransferHeader, IsHandled);
                if not IsHandled then begin
                    TestStatusOpen();
                    if "Shipping Agent Code" <> xRec."Shipping Agent Code" then
                        Validate("Shipping Agent Service Code", '');
                end
                //Shivam--
                UpdateTransLines(Rec, FieldNo("Shipping Agent Code"));
            end;
        }

  [IntegrationEvent(false, false)]
    local procedure OnBeforeValidateShippingAgentCode(TransferHeader: Record "Transfer Header"; var IsHandled: Boolean)
    begin
    end;

### Additional context

We want to comment base code.<br /><br />Internal work item: AB#493929

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14883.
