### ISSUE TITLE
[Event Request] Table- Item Variant(trigger OnDelete())

### ISSUE THREAD

**Issue by ShivamLodhi795** [microsoft/ALAppExtensions#25393]
### Describe the request

//Shivam++
        IsHandled := false;
        OnBeforeError1(IsHandled);
        if not IsHandled then begin
            PurchOrderLine.Reset();
            PurchOrderLine.SetCurrentKey(Type, "No.");
            PurchOrderLine.SetRange(Type, PurchOrderLine.Type::Item);
            PurchOrderLine.SetRange("No.", "Item No.");
            PurchOrderLine.SetRange("Variant Code", Code);
            if not PurchOrderLine.IsEmpty() then
                Error(Text001, Code, PurchOrderLine.TableCaption());
        end;
        //Shivam

       //Shivam++
        IsHandled := false;
        OnBeforeError2(IsHandled);
        if not IsHandled then begin
            SalesOrderLine.Reset();
            SalesOrderLine.SetCurrentKey(Type, "No.");
            SalesOrderLine.SetRange(Type, SalesOrderLine.Type::Item);
            SalesOrderLine.SetRange("No.", "Item No.");
            SalesOrderLine.SetRange("Variant Code", Code);
            if not SalesOrderLine.IsEmpty() then
                Error(Text001, Code, SalesOrderLine.TableCaption());
        end;
        //Shivam--

   //Shivam++
        IsHandled := false;
        OnBeforeError3(IsHandled);
        if not IsHandled then begin
            ItemLedgerEntry.Reset();
            ItemLedgerEntry.SetCurrentKey("Item No.");
            ItemLedgerEntry.SetRange("Item No.", "Item No.");
            ItemLedgerEntry.SetRange("Variant Code", Code);
            if not ItemLedgerEntry.IsEmpty() then
                Error(Text001, Code, ItemLedgerEntry.TableCaption());
        end;
        //Shivam--

        //Shivam++
        IsHandled := false;
        OnBeforeError4(IsHandled);
        if not IsHandled then begin
            ValueEntry.Reset();
            ValueEntry.SetCurrentKey("Item No.");
            ValueEntry.SetRange("Item No.", "Item No.");
            ValueEntry.SetRange("Variant Code", Code);
            if not ValueEntry.IsEmpty() then
                Error(Text001, Code, ValueEntry.TableCaption());
        end;
        //Shivam--

[IntegrationEvent(false, false)]
    local procedure OnBeforeError1(var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeError2(var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeError3(var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeError4(var IsHandled: Boolean)
    begin
    end;

### Additional context

We want to comment base code.<br /><br />Internal work item: AB#493931

**Comment by AleksandricMarko** [comment]
Hello @ShivamLodhi795 
Could you provide us some additional info about your requests for better understanding, why you want to skip standard code in several places? (not just this request)

**Comment by ShivamLodhi795** [comment]
Hello Team,

Actually, I am working on upgrade project from NAV to BC. This code commented by one of our customer so I have to move this code to BC.

Thanks & Regards
Shivam Verma

**Comment by AleksandricMarko** [comment]
Hello @ShivamLodhi795 
Please check comment from request #25395 
If you just want to have same code as you had in old NAV, probably that is not right way.
You need to be sure why this kind of changes are really needed, to understand risks, to give us good reasons for changes, otherwise we will not provide publishers.

**Comment by ShivamLodhi795** [comment]
Hello Team,

I have discussed with our customer, he convinced to leave this code, so you can leave this request.
Thanks for your support.

Thanks & Regards
Shivam Verma
