### ISSUE TITLE
[Event Request] Table-Prod. Order Line(trigger OnRename())-OnBeforeValidateRename

### ISSUE THREAD

**Issue by ShivamLodhi795** [microsoft/ALAppExtensions#25395]
### Describe the request

 trigger OnRename()
    begin
        //Shivam++
        IsHandled := false;
        OnBeforeValidateRename(Rec, IsHandled);
        if not IsHandled then begin
            Error(Text99000001, TableCaption);
        end;
        //Shivam--
    end;

[IntegrationEvent(false, false)]
    local procedure OnBeforeValidateRename(var ProdOrderLine: Record "Prod. Order Line"; var IsHandled: Boolean)
    begin
    end;

### Additional context

We want to comment base code.
<br /><br />Internal work item: AB#493930

**Comment by AlexanderYakunin** [comment]
Hello! We do not allow renaming of document line records on good purpose and will reject this request if you cannot provide strong justification. If you provide it, we can analyze you case and make our decisions.

Please make sure you analyze risks involved with your design decisions which require this change.
