### ISSUE TITLE
[Event Request] Table 5062 Attachment - procedure WizEmbeddAttachment

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25405]
### Describe the request

    procedure WizEmbeddAttachment(FromAttachment: Record Attachment)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeWizEmbeddAttachment(Rec, FromAttachment, IsHandled); //CustPub
        if IsHandled then
            exit;

        Rec := FromAttachment;
        "No." := 0;
        "Storage Type" := "Storage Type"::Embedded;
        FromAttachment.TestField("No.");
        case FromAttachment."Storage Type" of
            FromAttachment."Storage Type"::"Disk File":
                ImportAttachmentFromServerFile(FromAttachment.ConstDiskFileName, true, false);
            FromAttachment."Storage Type"::Embedded:
                begin
                    FromAttachment.CalcFields("Attachment File");
                    if FromAttachment."Attachment File".HasValue then
                        "Attachment File" := FromAttachment."Attachment File";
                end;
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeWizEmbeddAttachment(var Attachment: Record Attachment; FromAttachment: Record Attachment; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494009

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
