### ISSUE TITLE
[Event Request] Table 5062 Attachment - procedure WizSaveAttachment

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25406]
### Describe the request

    procedure WizSaveAttachment()
    var
        Attachment2: Record Attachment;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeWizSaveAttachment(Rec, IsHandled); //CustPub
        if IsHandled then
            exit;

        with RMSetup do begin
            Get;
            if "Attachment Storage Type" = "Attachment Storage Type"::Embedded then begin
                "Storage Pointer" := '';
                exit;
            end;
        end;

        "Storage Pointer" := RMSetup."Attachment Storage Location";

        CopyAttachmentAsFile(Rec, Attachment2);

        Clear(Rec);
        Rec := Attachment2;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeWizSaveAttachment(var Attachment: Record Attachment; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494004

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
