### ISSUE TITLE
[Event Request] Table 64 "Merge Duplicates Buffer"(procedure Merge)-OnMergeOnElseCase

### ISSUE THREAD

**Issue by ArnisVe** [microsoft/ALAppExtensions#25401]
### Describe the request

Hello, we require a couple of changes for table 64 "Merge Duplicates Buffer".

    procedure Merge(): Boolean
    var
        ConfirmManagement: Codeunit "Confirm Management";
    begin
        if FindConflicts() then
            exit(false);
        if not ConfirmManagement.GetResponseOrDefault(ConfirmMergeTxt, true) then
            exit(false);
        case "Table ID" of
            DATABASE::Contact:
                MergeContacts();
            DATABASE::Customer:
                MergeCustomers();
            DATABASE::Vendor:
                MergeVendors();
            else
                OnMergeOnElseCase(Rec);
        end;
        exit(true);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnMergeOnElseCase(var MergeDuplicatesBuffer: Record "Merge Duplicates Buffer")
    begin
    end;

New event for else case in procedure Merge. 

### Additional context

We have our own custom table and would like to use the existing functionality for merging two records.<br /><br />Internal work item: AB#493926

**Comment by AleksandricMarko** [comment]
Hello @ArnisVe 
this request will be used for new event publisher.
To make procedure MergeRecords "global", please make new request

**Comment by ArnisVe** [comment]
@AleksandricMarko I have updated the original issue to only reflect the event.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14883.
