### ISSUE TITLE
[Event Request] Table- Warehouse Shipment Header(procedure GetDocumentStatus)-OnBeforeCheckStatus 

### ISSUE THREAD

**Issue by ShivamLodhi795** [microsoft/ALAppExtensions#25400]
### Describe the request

procedure GetDocumentStatus(LineNo: Integer): Integer
    var
        WhseShptLine: Record "Warehouse Shipment Line";
    begin
        WhseShptLine.SetRange("No.", "No.");
        if LineNo <> 0 then
            WhseShptLine.SetFilter("Line No.", '<>%1', LineNo);
        if not WhseShptLine.FindFirst() then
            exit(WhseShptLine.Status::" ");

        //Shivam++
        OnBeforeCheckStatus(Rec, WhseShptLine);
         //Shivam--

        WhseShptLine.SetRange(Status, WhseShptLine.Status::"Partially Shipped");
        if WhseShptLine.FindFirst() then
            exit(WhseShptLine.Status);

        WhseShptLine.SetRange(Status, WhseShptLine.Status::"Partially Picked");
        if WhseShptLine.FindFirst() then
            exit(WhseShptLine.Status);

        WhseShptLine.SetRange(Status, WhseShptLine.Status::"Completely Picked");
        if WhseShptLine.FindFirst() then begin
            WhseShptLine.SetFilter(Status, '<%1', WhseShptLine.Status::"Completely Picked");
            if WhseShptLine.FindFirst() then
                exit(WhseShptLine.Status::"Partially Picked");

            exit(WhseShptLine.Status);
        end;

        WhseShptLine.SetRange(Status, WhseShptLine.Status::"Completely Shipped");
        if WhseShptLine.FindFirst() then begin
            WhseShptLine.SetFilter(Status, '<%1', WhseShptLine.Status::"Completely Shipped");
            if WhseShptLine.FindFirst() then
                exit(WhseShptLine.Status::"Partially Shipped");

            exit(WhseShptLine.Status);
        end;

        exit(WhseShptLine.Status);
    end;

 [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckStatus(var WarehouseShipmentHeader: Record "Warehouse Shipment Header"; var WarehouseShipmentLine: Record "Warehouse Shipment Line")
    begin
    end;

### Additional context

We want add custom code.<br /><br />Internal work item: AB#493927

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14883.
