### ISSUE TITLE
[Event Request] Codeunit 423 "Change Log Management" - local procedure InsertLogEntry

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25409]
### Describe the request

    local procedure InsertLogEntry(var FldRef: FieldRef; var xFldRef: FieldRef; var RecRef: RecordRef; TypeOfChange: Enum "Change Log Entry Type"; IsReadable: Boolean)
    var
        ChangeLogEntry: Record "Change Log Entry";
        KeyFldRef: FieldRef;
        KeyRef1: KeyRef;
        i: Integer;
        AlwaysLog: Boolean;
        Handled: Boolean;
    begin
        if RecRef.CurrentCompany <> ChangeLogEntry.CurrentCompany then
            ChangeLogEntry.ChangeCompany(RecRef.CurrentCompany);

        if MonitorSensitiveFieldData.IsIgnoredMonitorField(RecRef, FldRef) then
            exit;

        OnInsertLogEntryOnBeforeInitChangeLogEntry(ChangeLogEntry); //CustPub
        ChangeLogEntry.Init();
        ChangeLogEntry."Date and Time" := CurrentDateTime;
        ChangeLogEntry.Time := DT2Time(ChangeLogEntry."Date and Time");

        ChangeLogEntry."User ID" := UserId;

    [IntegrationEvent(false, false)]
    local procedure OnInsertLogEntryOnBeforeInitChangeLogEntry(var ChangeLogEntry: Record "Change Log Entry") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494006

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
