### ISSUE TITLE
[Event Request] Page 9092 "Approval FactBox" - procedure UpdateApprovalEntriesFromSourceRecord

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25404]
### Describe the request

    procedure UpdateApprovalEntriesFromSourceRecord(SourceRecordID: RecordID)
    var
        ApprovalEntry: Record "Approval Entry";
    begin
        FilterGroup(2);
        SetRange("Record ID to Approve", SourceRecordID);
        ApprovalEntry.Copy(Rec);
        if ApprovalEntry.FindFirst() then
            SetFilter("Approver ID", '<>%1', ApprovalEntry."Sender ID");
        FilterGroup(0);
        OnUpdateApprovalEntriesOnAfterApprovalEntrySetFilter(ApprovalEntry); //CustPub
        if FindLast() then;
        CurrPage.Update(false);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnUpdateApprovalEntriesOnAfterApprovalEntrySetFilter(var ApprovalEntry: Record "Approval Entry") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.
<br /><br />Internal work item: AB#494005

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
