### ISSUE TITLE
[Event Request] codeunit 1535 "Approvals Mgmt." - OnFindApprovalEntryForCurrUserOnAfterApprovalEntrySetFilters

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25402]
### Describe the request

    procedure FindApprovalEntryForCurrUser(var ApprovalEntry: Record "Approval Entry"; RecordID: RecordID): Boolean
    begin
        ApprovalEntry.SetRange("Table ID", RecordID.TableNo);
        ApprovalEntry.SetRange("Record ID to Approve", RecordID);
        ApprovalEntry.SetRange("Approver ID", UserId);
        OnFindApprovalEntryForCurrUserOnAfterApprovalEntrySetFilters(ApprovalEntry);

        exit(ApprovalEntry.FindFirst());
    end;

    [IntegrationEvent(false, false)]
    local procedure OnFindApprovalEntryForCurrUserOnAfterApprovalEntrySetFilters(var ApprovalEntry: Record "Approval Entry")
    begin
    end;

### Additional context

Missing<br /><br />Internal work item: AB#493928

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14883.
