### ISSUE TITLE
[Event Request] Codeunit 1303 "Correct Posted Sales Invoice" - local procedure TestGenPostingSetup

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25411]
### Describe the request

    local procedure TestGenPostingSetup(SalesInvoiceLine: Record "Sales Invoice Line")
    var
        GenPostingSetup: Record "General Posting Setup";
        Item: Record Item;
        IsHandled: Boolean;
    begin
        if SalesInvoiceLine."VAT Calculation Type" = SalesInvoiceLine."VAT Calculation Type"::"Sales Tax" then
            exit;

        with GenPostingSetup do begin
            Get(SalesInvoiceLine."Gen. Bus. Posting Group", SalesInvoiceLine."Gen. Prod. Posting Group");
            if SalesInvoiceLine.Type <> SalesInvoiceLine.Type::"G/L Account" then begin
                TestField("Sales Account");
                TestGLAccount("Sales Account", SalesInvoiceLine);
                TestField("Sales Credit Memo Account");
                TestGLAccount("Sales Credit Memo Account", SalesInvoiceLine);
            end;
            if HasLineDiscountSetup(SalesInvoiceLine) then
                if "Sales Line Disc. Account" <> '' then
                    TestGLAccount("Sales Line Disc. Account", SalesInvoiceLine);
            IsHandled := false;
            OnTestGenPostingSetupTypeItem(SalesInvoiceLine, IsHandled); //CustPub
            if IsHandled then
                exit;
            if SalesInvoiceLine.Type = SalesInvoiceLine.Type::Item then begin
                Item.Get(SalesInvoiceLine."No.");
                if Item.IsInventoriableType then
                    TestGLAccount(GetCOGSAccount, SalesInvoiceLine);
            end;
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnTestGenPostingSetupTypeItem(SalesInvoiceLine: Record "Sales Invoice Line"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494014

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
