### ISSUE TITLE
[Event Request] Codeunit 449 "Job Queue Start Codeunit" - trigger OnRun()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25419]
### Describe the request

    trigger OnRun()
    var
        TempErrorMessage: Record "Error Message" temporary;
        ErrorMessageManagement: Codeunit "Error Message Management";
        ErrorMessageHandler: Codeunit "Error Message Handler";
        ErrorContextElement: Codeunit "Error Context Element";
        ErrorMessageRegisterId: Guid;
        Success: Boolean;
        LastError: DotNet LastError;
    begin
        OnBeforeRun(Rec); //CustPub

        if "User Language ID" <> 0 then
            GlobalLanguage("User Language ID");

    [IntegrationEvent(false, false)]
    local procedure OnBeforeRun(var JobQueueEntry: Record "Job Queue Entry") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494010

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
