### ISSUE TITLE
[Event Modification] Codeunit 5005271 "Create Delivery Reminder" - OnSuggestLinesOnAfterPurchHeaderSetFilters

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25413]
### Describe the request

    [Scope('OnPrem')]
    procedure SuggestLines(var DeliveryReminderHeader: Record "Delivery Reminder Header")
    var
        PurchHeader: Record "Purchase Header";
        PurchLine: Record "Purchase Line";
        DeliveryReminderTerms: Record "Delivery Reminder Term";
        DeliveryReminderLevel: Record "Delivery Reminder Level";
        DateOfTheCurrentDay: Date;
    begin
        DeliveryReminderHeader.TestField("Vendor No.");
        DeliveryReminderHeader.TestField("Reminder Terms Code");
        DeliveryReminderTerms.Get(DeliveryReminderHeader."Reminder Terms Code");
        DateOfTheCurrentDay := WorkDate;

        PurchHeader.Reset();
        PurchHeader.SetCurrentKey("Document Type", "Buy-from Vendor No.");
        PurchHeader.SetRange("Document Type", PurchLine."Document Type"::Order);
        PurchHeader.SetRange("Buy-from Vendor No.", DeliveryReminderHeader."Vendor No.");
        OnSuggestLinesOnAfterPurchHeaderSetFilters(PurchHeader);
        OnSuggestLinesOnAfterPurchHeaderSetFilters(PurchHeader, DeliveryReminderHeader); //CustPub

    [IntegrationEvent(false, false)]
    local procedure OnSuggestLinesOnAfterPurchHeaderSetFilters(var PurchHeader: Record "Purchase Header"; DeliveryReminderHeader: Record "Delivery Reminder Header") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.

Additional parameter DeliveryReminderHeader to already existing publisher OnSuggestLinesOnAfterPurchHeaderSetFilters<br /><br />Internal work item: AB#494016

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
