### ISSUE TITLE
[Event Modification] Table 846 "Cash Flow Worksheet Line" - OnCalculateCFAmountAndCFDateOnAfterAssignApplyCFPaymentTerm

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25414]
### Describe the request

    procedure CalculateCFAmountAndCFDate()
    var
        GeneralLedgerSetup: Record "General Ledger Setup";
        PaymentTerms: Record "Payment Terms";
        CashFlowForecast: Record "Cash Flow Forecast";
        DiscountDateCalculation: DateFormula;
        PaymentTermsToApply: Code[10];
        CFDiscountDate: Date;
        CheckCrMemo: Boolean;
        ApplyCFPaymentTerm: Boolean;
        IsHandled: Boolean;
    begin
        if "Document Date" = 0D then
            "Document Date" := WorkDate();
        if "Cash Flow Date" = 0D then
            "Cash Flow Date" := "Document Date";
        if "Amount (LCY)" = 0 then
            exit;

        case "Document Type" of
            "Document Type"::Invoice:
                CheckCrMemo := false;
            "Document Type"::"Credit Memo":
                CheckCrMemo := true;
            else
                exit;
        end;

        if not CashFlowForecast.Get("Cash Flow Forecast No.") then
            exit;

        PaymentTermsToApply := "Payment Terms Code";
        ApplyCFPaymentTerm := CashFlowForecast."Consider CF Payment Terms" and PaymentTerms.Get(PaymentTermsToApply);
        if "Source Type" in ["Source Type"::"Sales Orders", "Source Type"::"Purchase Orders", "Source Type"::"Service Orders",
                             "Source Type"::Job]
        then
            ApplyCFPaymentTerm := true;

        OnCalculateCFAmountAndCFDateOnAfterAssignApplyCFPaymentTerm(Rec, ApplyCFPaymentTerm);
        IsHandled := false;
        OnCalculateCFAmountAndCFDateOnAfterAssignApplyCFPaymentTerm(Rec, CheckCrMemo, IsHandled); //CustPub
        if IsHandled then
            exit;

    [IntegrationEvent(false, false)]
    local procedure OnCalculateCFAmountAndCFDateOnAfterAssignApplyCFPaymentTerm(CashFlowWorksheetLine: Record "Cash Flow Worksheet Line"; var CheckCrMemo: Boolean; var IsHandled: boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.

Additional parameter IsHandled to already existing publisher OnCalculateCFAmountAndCFDateOnAfterAssignApplyCFPaymentTerm with possibility to exit the procedure.<br /><br />Internal work item: AB#494012

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
