### ISSUE TITLE
[Event Request] Codeunit 5005271 "Create Delivery Reminder" - procedure CreateDelivRemindLine

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25412]
### Describe the request

    [Scope('OnPrem')]
    procedure CreateDelivRemindLine(DeliveryReminderHeader: Record "Delivery Reminder Header"; PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; DeliveryReminderTerms: Record "Delivery Reminder Term"; DeliveryReminderLevel: Record "Delivery Reminder Level"; DateOfTheCurrentDay: Date)
    var
        DeliveryReminderLine: Record "Delivery Reminder Line";
        NextLineNo: Integer;
        IsHandled: Boolean;
    begin
        PurchaseSetup.Get();
        PurchaseSetup.TestField("Default Del. Rem. Date Field");

        IsHandled := false;
        OnCreateDelivRemindLineBeforeInit(DeliveryReminderHeader, PurchHeader, IsHandled); //CustPub
        if IsHandled then
            exit;
        DeliveryReminderLine.Reset();
        DeliveryReminderLine.SetRange("Document No.", DeliveryReminderHeader."No.");
        if DeliveryReminderLine.FindLast() then
            NextLineNo := DeliveryReminderLine."Line No." + 10000
        else
            NextLineNo := 10000;

    [IntegrationEvent(false, false)]
    local procedure OnCreateDelivRemindLineBeforeInit(DeliveryReminderHeader: Record "Delivery Reminder Header"; PurchHeader: Record "Purchase Header"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494013

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
