### ISSUE TITLE
[Event Request] Table 23 Vendor - procedure OpenVendorLedgerEntries

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25416]
### Describe the request

    procedure OpenVendorLedgerEntries(FilterOnDueEntries: Boolean)
    var
        DetailedVendorLedgEntry: Record "Detailed Vendor Ledg. Entry";
        VendorLedgerEntry: Record "Vendor Ledger Entry";
        IsHandled: Boolean;
    begin
        OnBeforeOpenVendorLedgerEntries(Rec, DetailedVendorLedgEntry);
        DetailedVendorLedgEntry.SetRange("Vendor No.", "No.");
        CopyFilter("Global Dimension 1 Filter", DetailedVendorLedgEntry."Initial Entry Global Dim. 1");
        CopyFilter("Global Dimension 2 Filter", DetailedVendorLedgEntry."Initial Entry Global Dim. 2");
        if FilterOnDueEntries and (GetFilter("Date Filter") <> '') then begin
            CopyFilter("Date Filter", DetailedVendorLedgEntry."Initial Entry Due Date");
            DetailedVendorLedgEntry.SetFilter("Posting Date", '<=%1', GetRangeMax("Date Filter"));
        end;
        CopyFilter("Currency Filter", DetailedVendorLedgEntry."Currency Code");
        OnBeforeOpenVendorLedgerEntriesAfterFilters(DetailedVendorLedgEntry, FilterOnDueEntries, IsHandled); //CustPub
        if not IsHandled then
            VendorLedgerEntry.DrillDownOnEntries(DetailedVendorLedgEntry);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeOpenVendorLedgerEntriesAfterFilters(var DetailedVendorLedgEntry: Record "Detailed Vendor Ledg. Entry"; FilterOnDueEntries: Boolean; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494015

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
