### ISSUE TITLE
[Event Request] Codeunit 40 LogInManagement - local procedure LogInEnd()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25418]
### Describe the request

    local procedure LogInEnd()
    var
        UserSetup: Record "User Setup";
        UserTimeRegister: Record "User Time Register";
        LogOutDate: Date;
        LogOutTime: Time;
        Minutes: Integer;
        UserSetupFound: Boolean;
        RegisterTime: Boolean;
    begin
        OnBeforeLogInEnd(LogInDate, LogInTime); //CustPub
        if LogInDate = 0D then
            exit;

        if LogInWorkDate <> 0D then
            if LogInWorkDate = LogInDate then

    [IntegrationEvent(false, false)]
    local procedure OnBeforeLogInEnd(var LogInDate: Date; var LogInTime: Time) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494011

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
