### ISSUE TITLE
[Event Request] Table 5054 "Contact Business Relation" - trigger OnInsert()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25410]
### Describe the request

    trigger OnInsert()
    var
        ContBusRel: Record "Contact Business Relation";
        Cont: Record Contact;
        IsHandled: Boolean;
    begin
        if "No." <> '' then begin
            IsHandled := false;
            OnInsertOnBeforeFindByContact(Rec, IsHandled); //CustPub
            if not IsHandled then
                if ContBusRel.FindByContact("Link to Table", "Contact No.") then
                    Error(
                      Text000,
                      Cont.TableCaption, "Contact No.", TableCaption, "Link to Table", ContBusRel."No.");

            if ContBusRel.FindByRelation("Link to Table", "No.") then
                if GetContactBusinessRelation(ContBusRel) then
                    Error(
                      Text000,
                      "Link to Table", "No.", TableCaption, Cont.TableCaption, ContBusRel."Contact No.");

            ContBusRel.Reset();
            ContBusRel.SetRange("Contact No.", "Contact No.");
            ContBusRel.SetRange("Business Relation Code", "Business Relation Code");
            ContBusRel.SetRange("No.", '');
            ContBusRel.DeleteAll();
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnInsertOnBeforeFindByContact(ContactBusinessRelation: Record "Contact Business Relation"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494019

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
