### ISSUE TITLE
[Event Request] Codeunit 5624 "Cancel FA Ledger Entries" -  procedure TransferLine

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25415]
### Describe the request

    procedure TransferLine(var FALedgEntry: Record "FA Ledger Entry"; BalAccount: Boolean; NewPostingDate: Date)
    var
        IsHandled: Boolean;
    begin
        ClearAll;
        with FALedgEntry do begin
            if Find('+') then
                repeat
                    if DeprBookCode = '' then
                        DeprBookCode := "Depreciation Book Code";
                    if DeprBookCode <> "Depreciation Book Code" then
                        FieldError("Depreciation Book Code", Text001);
                    if "FA No." = '' then
                        Error(Text002, FieldCaption("Entry No."), "Entry No.");
                    FA.Get("FA No.");
                    DeprBook.Get("Depreciation Book Code");
                    IsHandled := false;
                    OnTransferLineOnBeforeIndexGLIntegration(DeprBook, IsHandled); //CustPub
                    if not IsHandled then begin
                        DeprBook.IndexGLIntegration(GLIntegration);
                        CheckType(FALedgEntry);
                        if NewPostingDate > 0D then begin
                            "Posting Date" := NewPostingDate;
                            DeprBook.TestField("Use Same FA+G/L Posting Dates", false);
                        end;
                        IsHandled := false;
                        OnTransferLineOnBeforeInsertJnlLine(FALedgEntry, BalAccount, FA."Budgeted Asset", IsHandled);
                        if not IsHandled then
                            if GLIntegration[ConvertPostingType + 1] and not FA."Budgeted Asset" then
                                InsertGenJnlLine(FALedgEntry, BalAccount)
                            else
                                InsertFAJnlLine(FALedgEntry);
                    end;
                until Next(-1) = 0;
        end;

    [IntegrationEvent(false, false)]
    local procedure OnTransferLineOnBeforeIndexGLIntegration(DeprBook: Record "Depreciation Book"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494017

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
