### ISSUE TITLE
[Event Request] Codeunit 420 "XBRL Management" - procedure CalcAmount

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25420]
### Describe the request

    procedure CalcAmount(var XBRLTaxonomyLine: Record "XBRL Taxonomy Line"): Decimal
    var
        GLEntry: Record "G/L Entry";
        GLAcc: Record "G/L Account";
        XBRLGLMapLine: Record "XBRL G/L Map Line";
        Amount: Decimal;
    begin
        Amount := 0;
        with XBRLGLMapLine do begin
            Reset;
            SetRange("XBRL Taxonomy Name", XBRLTaxonomyLine."XBRL Taxonomy Name");
            SetRange("XBRL Taxonomy Line No.", XBRLTaxonomyLine."Line No.");
            if Find('-') then
                repeat
                    GLEntry.Reset();
                    GLEntry.SetCurrentKey("G/L Account No.", "Posting Date");
                    GLEntry.SetFilter("G/L Account No.", "G/L Account Filter");
                    if ((XBRLTaxonomyLine.GetFilter("Business Unit Filter") <> '') or
                        (XBRLTaxonomyLine.GetFilter("Global Dimension 1 Filter") <> '') or
                        (XBRLTaxonomyLine.GetFilter("Global Dimension 2 Filter") <> ''))
                    then begin
                        GLEntry.SetCurrentKey(
                          "G/L Account No.", "Business Unit Code", "Global Dimension 1 Code", "Global Dimension 2 Code");
                        XBRLTaxonomyLine.CopyFilter("Business Unit Filter", GLEntry."Business Unit Code");
                        XBRLTaxonomyLine.CopyFilter("Global Dimension 1 Filter", GLEntry."Global Dimension 1 Code");
                        XBRLTaxonomyLine.CopyFilter("Global Dimension 2 Filter", GLEntry."Global Dimension 2 Code");
                    end;
                    GLEntry.FilterGroup(2);
                    if "Business Unit Filter" <> '' then begin
                        GLEntry.SetCurrentKey(
                          "G/L Account No.", "Business Unit Code", "Global Dimension 1 Code", "Global Dimension 2 Code");
                        GLEntry.SetFilter("Business Unit Code", "Business Unit Filter");
                    end;
                    if "Global Dimension 1 Filter" <> '' then begin
                        GLEntry.SetCurrentKey(
                          "G/L Account No.", "Business Unit Code", "Global Dimension 1 Code", "Global Dimension 2 Code");
                        GLEntry.SetFilter("Global Dimension 1 Code", "Global Dimension 1 Filter");
                    end;
                    if "Global Dimension 2 Filter" <> '' then begin
                        GLEntry.SetCurrentKey(
                          "G/L Account No.", "Business Unit Code", "Global Dimension 1 Code", "Global Dimension 2 Code");
                        GLEntry.SetFilter("Global Dimension 2 Code", "Global Dimension 2 Filter");
                    end;
                    OnCalcAmountOnAfterSetFilterGroup(XBRLGLMapLine, XBRLTaxonomyLine, GLEntry); //CustPub
                    GLEntry.FilterGroup(0);

    [IntegrationEvent(false, false)]
    local procedure OnCalcAmountOnAfterSetFilterGroup(var XBRLGLMapLine: Record "XBRL G/L Map Line"; var XBRLTaxonomyLine: Record "XBRL Taxonomy Line"; var GLEntry: Record "G/L Entry") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494039

**Comment by AleksandricMarko** [comment]
Codeunit "XBRL Management" is discontinued.
