### ISSUE TITLE
[Event Request] Codeunit 99000854 - Inventory Profile Offsetting - OnAfterPlanStepSettingOnCloseDemand

### ISSUE THREAD

**Issue by SchoKa** [microsoft/ALAppExtensions#2542]
Hello AL-Team,
please add the following Publisher in function "PlanItem":

LOCAL PlanItem(VAR DemandInvtProfile : Record "Inventory Profile";VAR SupplyInvtProfile : Record "Inventory Profile";PlanningStartDate : Date;ToDate : Date;RespectPlanningParm : Boolean)

```
              DemandInvtProfile.DELETE;

              // If just handled demand was safetystock
              IF DemandInvtProfile."Order Relation" = DemandInvtProfile."Order Relation"::"Safety Stock" THEN
                SupplyExists := SupplyInvtProfile.FINDSET(TRUE); // We assume that next profile is NOT safety stock

              DemandExists := DemandInvtProfile.NEXT <> 0;

              // >> New
              OnAfterPlanStepSettingOnCloseDemand(SupplyInvtProfile,SupplyExists);
              // << New
              NextState := NextState::StartOver;
            END;
          NextState::CloseSupply:
            BEGIN
              IF DemandExists AND (SupplyInvtProfile."Untracked Quantity" > 0) THEN BEGIN
                DemandInvtProfile."Untracked Quantity" -= SupplyInvtProfile."Untracked Quantity";
                DemandInvtProfile.MODIFY;
              END;

```

Publisher definition currently used by us
IncludeSender: false
GlobaVarAccess: false
LOCAL [IntegrationEvent] OnAfterPlanStepSettingOnCloseDemand(VAR SupplyInvtProfile : Record "Inventory Profile";VAR SupplyExists : Boolean)

**Comment by NKarolak** [comment]
Note: implemented as **OnAfterPlanItemNextStateCloseDemand**
`LOCAL [IntegrationEvent] OnAfterPlanItemNextStateCloseDemand(VAR SupplyInventoryProfile : Record "Inventory Profile";VAR SupplyExists : Boolean)
`
