### ISSUE TITLE
[Event Request] Table 5077 "Segment Line" - local procedure LoadTempAttachment

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25429]
### Describe the request

    local procedure LoadTempAttachment(ForceReload: Boolean)
    begin
        if not ForceReload and TempAttachment."Attachment File".HasValue then
            exit;
        Attachment.Get("Attachment No.");
        Attachment.CalcFields("Attachment File");
        TempAttachment.DeleteAll();
        TempAttachment.WizEmbeddAttachment(Attachment);
        TempAttachment."No." := 0;
        TempAttachment."Read Only" := false;
        if Attachment.IsHTML then
            TempAttachment."File Extension" := Attachment."File Extension";
        OnLoadTempAttachmentOnBeforeInsertTempAttachment(Rec, TempAttachment); //CustPub
        TempAttachment.Insert();
    end;

    [IntegrationEvent(false, false)]
    local procedure OnLoadTempAttachmentOnBeforeInsertTempAttachment(SegmentLine: Record "Segment Line"; var TempAttachment: Record Attachment temporary) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494020

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
