### ISSUE TITLE
[Event Request] Codeunit 422 "XBRL Import Taxonomy Spec. 2" - procedure ImportPresentation

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25422]
### Describe the request

    [Scope('OnPrem')]
    procedure ImportPresentation(var XBRLLinkbase: Record "XBRL Linkbase")
    var
        XBRLTaxonomyLine: Record "XBRL Taxonomy Line";
        XBRLTaxonomyLine2: Record "XBRL Taxonomy Line";
        XBRLSchema: Record "XBRL Schema";
        TempXBRLSchema: Record "XBRL Schema" temporary;
        LinkbaseDocument: DotNet XmlDocument;
        LinkbaseDocNode: DotNet XmlNode;
        XMLNodeList: DotNet XmlNodeList;
        XMLNode: DotNet XmlNode;
        Window: Dialog;
        CurrNodeIndex: Integer;
        i: Integer;
        Progress: Integer;
        NoOfRecords: Integer;
        Schemalocation: Text;
        FromSchemalocation: Text;
        ToSchemalocation: Text;
        fromLabel: Text[250];
        toLabel: Text[250];
        ToName: Text[250];
        t: Text[30];
        "Order": Decimal;
        UpdateParentPresentationLineNo: Boolean;
        LastXBRLLineNo: Integer;
        Counter: Integer;
    begin
        XBRLSchema.Get(XBRLLinkbase."XBRL Taxonomy Name", XBRLLinkbase."XBRL Schema Line No.");
        Window.Open(
          StrSubstNo(
            Text013, XBRLSchema.TableCaption, XBRLSchema.Description, XBRLLinkbase.TableCaption));
        Window.Update(4, XBRLLinkbase.Type);
        Window.Update(5, XBRLLinkbase.Description);

        LoadLinkbaseDocument(XBRLLinkbase, LinkbaseDocument);
        FindLinkbaseDocNode(LinkbaseDocument, LinkbaseDocNode);
        Schemalocation := GetAttribute('xsi:schemaLocation', LinkbaseDocNode);

        if Schemalocation = '' then
            Error(Text015);

        UpdateSchemaLocation(TempXBRLSchema, XBRLSchema, XBRLLinkbase, Schemalocation, FromSchemalocation);
        GetCommonXmnsPrefixes(LinkbaseDocNode);
        CreateNameSpaceManager(LinkbaseDocument);
        PopulateNamespaceManager(LinkbaseDocument.DocumentElement);
        PopulateNamespaceManager(LinkbaseDocNode.FirstChild);

        XBRLTaxonomyLine.SetRange("XBRL Taxonomy Name", XBRLLinkbase."XBRL Taxonomy Name");
        XBRLTaxonomyLine.SetRange("Presentation Linkbase Line No.", XBRLLinkbase."Line No.");
        XBRLTaxonomyLine.ModifyAll("Presentation Linkbase Line No.", 0);
        XBRLTaxonomyLine.SetRange("Presentation Linkbase Line No.");
        NoOfRecords := XBRLTaxonomyLine.Count();

        if XBRLTaxonomyLine.FindLast() then
            LastXBRLLineNo := XBRLTaxonomyLine."Line No.";

        InitTaxonomyLinesBuf(XBRLTaxonomyLine, TempXBRLLine);
        if TempXBRLLine.FindSet() then
            repeat
                Progress := Progress + 1;
                Window.Update(6, Round(Progress / NoOfRecords * 10000, 1));
                if TempXBRLSchema."Line No." <> TempXBRLLine."XBRL Schema Line No." then
                    TempXBRLSchema.Get(TempXBRLLine."XBRL Taxonomy Name", TempXBRLLine."XBRL Schema Line No.");
                FromSchemalocation := TempXBRLSchema.schemaLocation;
                XMLNode :=
                  LinkbaseDocNode.SelectSingleNode(
                    GetXPathForSelectLinkBases('presentationLink', FromSchemalocation, TempXBRLLine."Element ID"), NamespaceMgr);
                if not IsNull(XMLNode) then begin
                    fromLabel := GetAttribute(XLinkPrefix + 'label', XMLNode);
                    if XBRLSchema."xmlns:xbrli" = 'http://www.xbrl.org/2001/instance' then // spec. 2.0
                        XMLNodeList :=
                          LinkbaseDocNode.SelectNodes(
                            StrSubstNo(
                              '%3presentationLink/%3presentationArc[@%4from="%1" and @%4arcrole="%2"]',
                              fromLabel, 'http://www.xbrl.org/linkprops/arc/parent-child', LinkPrefix, XLinkPrefix), NamespaceMgr)
                    else // 'http://www.xbrl.org/2003/instance' // spec. 2.1
                        XMLNodeList :=
                          LinkbaseDocNode.SelectNodes(
                            StrSubstNo(
                              '%3presentationLink/%3presentationArc[@%4from="%1" and @%4arcrole="%2"]',
                              fromLabel, 'http://www.xbrl.org/2003/arcrole/parent-child', LinkPrefix, XLinkPrefix), NamespaceMgr);

                    for CurrNodeIndex := 0 to XMLNodeList.Count - 1 do begin
                        XMLNode := XMLNodeList.Item(CurrNodeIndex);
                        t := GetAttribute('order', XMLNode);
                        if t = '' then
                            Order := 1
                        else
                            Evaluate(Order, t);
                        OnImportPresentationOnAfterSettingOrderValue(Order, t); //CustPub
                        toLabel := GetAttribute(XLinkPrefix + 'to', XMLNode);

    [IntegrationEvent(false, false)]
    local procedure OnImportPresentationOnAfterSettingOrderValue(var "Order": Decimal; t: Text[30]) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494023

**Comment by AleksandricMarko** [comment]
Codeunit "XBRL Import Taxonomy Spec. 2" is discontinued.
