### ISSUE TITLE
[Event Modification] Table 5077 "Segment Line" - OnBeforeCheckStatus

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25427]
### Describe the request

    procedure CheckStatus()
    var
        InteractTmpl: Record "Interaction Template";
        SalutationFormula: Record "Salutation Formula";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckStatus(Rec, IsHandled);
        OnBeforeCheckStatus(Rec, IsHandled, TempAttachment); //CustPub
        if IsHandled then
            exit;

        if "Contact No." = '' then
            Error(Text009);

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckStatus(var SegmentLine: Record "Segment Line"; var IsHandled: Boolean; AttachmentTmp: Record Attachment temporary) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.

Additional parameter TempAttachment to already existing publisher OnBeforeCheckStatus<br /><br />Internal work item: AB#494042

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14693.
