### ISSUE TITLE
[Event Request] Codeunit 420 "XBRL Management" - procedure CalcAmount

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25421]
### Describe the request

procedure CalcAmount(var XBRLTaxonomyLine: Record "XBRL Taxonomy Line"): Decimal
    var
        GLEntry: Record "G/L Entry";
        GLAcc: Record "G/L Account";
        XBRLGLMapLine: Record "XBRL G/L Map Line";
        Amount: Decimal;
    begin
        Amount := 0;
        with XBRLGLMapLine do begin
            Reset;
            SetRange("XBRL Taxonomy Name", XBRLTaxonomyLine."XBRL Taxonomy Name");
            SetRange("XBRL Taxonomy Line No.", XBRLTaxonomyLine."Line No.");
            if Find('-') then
                repeat
                    GLEntry.Reset();
                    GLEntry.SetCurrentKey("G/L Account No.", "Posting Date");
                    GLEntry.SetFilter("G/L Account No.", "G/L Account Filter");
                    if ((XBRLTaxonomyLine.GetFilter("Business Unit Filter") <> '') or
                        (XBRLTaxonomyLine.GetFilter("Global Dimension 1 Filter") <> '') or
                        (XBRLTaxonomyLine.GetFilter("Global Dimension 2 Filter") <> ''))
                    then begin
                        GLEntry.SetCurrentKey(
                          "G/L Account No.", "Business Unit Code", "Global Dimension 1 Code", "Global Dimension 2 Code");
                        XBRLTaxonomyLine.CopyFilter("Business Unit Filter", GLEntry."Business Unit Code");
                        XBRLTaxonomyLine.CopyFilter("Global Dimension 1 Filter", GLEntry."Global Dimension 1 Code");
                        XBRLTaxonomyLine.CopyFilter("Global Dimension 2 Filter", GLEntry."Global Dimension 2 Code");
                    end;
                    GLEntry.FilterGroup(2);
                    if "Business Unit Filter" <> '' then begin
                        GLEntry.SetCurrentKey(
                          "G/L Account No.", "Business Unit Code", "Global Dimension 1 Code", "Global Dimension 2 Code");
                        GLEntry.SetFilter("Business Unit Code", "Business Unit Filter");
                    end;
                    if "Global Dimension 1 Filter" <> '' then begin
                        GLEntry.SetCurrentKey(
                          "G/L Account No.", "Business Unit Code", "Global Dimension 1 Code", "Global Dimension 2 Code");
                        GLEntry.SetFilter("Global Dimension 1 Code", "Global Dimension 1 Filter");
                    end;
                    if "Global Dimension 2 Filter" <> '' then begin
                        GLEntry.SetCurrentKey(
                          "G/L Account No.", "Business Unit Code", "Global Dimension 1 Code", "Global Dimension 2 Code");
                        GLEntry.SetFilter("Global Dimension 2 Code", "Global Dimension 2 Filter");
                    end;
                    OnCalcAmountOnAfterSetFilterGroup(XBRLGLMapLine, XBRLTaxonomyLine, GLEntry); //CustPub
                    GLEntry.FilterGroup(0);
                    case "Timeframe Type" of
                        "Timeframe Type"::"Net Change":
                            GLEntry.SetRange("Posting Date", PeriodStartDate, PeriodEndDate);
                        "Timeframe Type"::"Beginning Balance":
                            GLEntry.SetRange("Posting Date", 0D, ClosingDate(PeriodStartDate - 1));
                        "Timeframe Type"::"Ending Balance":
                            GLEntry.SetRange("Posting Date", 0D, PeriodEndDate);
                    end;
                    case "Amount Type" of
                        "Amount Type"::"Net Amount":
                            begin
                                GLEntry.CalcSums(Amount);
                                if (("Normal Balance" = "Normal Balance"::"Debit (positive)") and (GLEntry.Amount < 0) or
                                    ("Normal Balance" = "Normal Balance"::"Credit (negative)") and (GLEntry.Amount > 0))
                                then
                                    Amount := Amount - Abs(GLEntry.Amount)
                                else
                                    Amount := Amount + Abs(GLEntry.Amount);
                            end;
                        "Amount Type"::"Debits Only":
                            begin
                                GLEntry.CalcSums("Debit Amount");
                                Amount := Amount + GLEntry."Debit Amount";
                            end;
                        "Amount Type"::"Credits Only":
                            begin
                                GLEntry.CalcSums("Credit Amount");
                                Amount := Amount + GLEntry."Credit Amount";
                            end;
                    end;
                    with GLAcc do begin
                        SetFilter("No.", XBRLGLMapLine."G/L Account Filter");
                        SetFilter("Account Type", '%1|%2', "Account Type"::"End-Total", "Account Type"::Total);
                        GLEntry.CopyFilter("Posting Date", "Date Filter");
                        GLEntry.CopyFilter("Global Dimension 1 Code", "Global Dimension 1 Filter");
                        GLEntry.CopyFilter("Global Dimension 2 Code", "Global Dimension 2 Filter");
                        GLEntry.CopyFilter("Business Unit Code", "Business Unit Filter");
                        OnCalcAmountOnAfterGLEntrySetFilters(GLAcc, GLEntry);
                        if Find('-') then
                            repeat
                                case "Amount Type" of
                                    "Amount Type"::"Net Amount":
                                        begin
                                            CalcFields("Net Change");
                                            if (("Normal Balance" = "Normal Balance"::"Debit (positive)") and ("Net Change" < 0) or
                                                ("Normal Balance" = "Normal Balance"::"Credit (negative)") and ("Net Change" > 0))
                                            then
                                                Amount := Amount - Abs("Net Change")
                                            else
                                                Amount := Amount + Abs("Net Change");
                                        end;
                                    "Amount Type"::"Debits Only":
                                        begin
                                            CalcFields("Debit Amount");
                                            Amount := Amount + "Debit Amount";
                                        end;
                                    "Amount Type"::"Credits Only":
                                        begin
                                            CalcFields("Credit Amount");
                                            Amount := Amount + "Credit Amount";
                                        end;
                                end;
                            until Next() = 0;
                    end;
                until Next() = 0;
        end;
        OnAfterCalcAmount(XBRLTaxonomyLine, Amount); //CustPub
        exit(Amount);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcAmount(XBRLTaxonomyLine: Record "XBRL Taxonomy Line"; var Amount: Decimal) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494021

**Comment by AleksandricMarko** [comment]
Hello @StefanSosic 
Codeunit "XBRL Management" is discontinued.
We are adding new publisher just in master and latest release branch.
