### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" - procedure PostItemJnlLine

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25437]
### Describe the request

    procedure PostItemJnlLine(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; QtyToBeShipped: Decimal; QtyToBeShippedBase: Decimal; QtyToBeInvoiced: Decimal; QtyToBeInvoicedBase: Decimal; ItemLedgShptEntryNo: Integer; ItemChargeNo: Code[20]; TrackingSpecification: Record "Tracking Specification"; IsATO: Boolean) Result: Integer
    var
        ItemJnlLine: Record "Item Journal Line";
        TempWhseJnlLine: Record "Warehouse Journal Line" temporary;
        TempWhseTrackingSpecification: Record "Tracking Specification" temporary;
        OriginalItemJnlLine: Record "Item Journal Line";
        ItemShptEntryNo: Integer;
        PostWhseJnlLine: Boolean;
        IsHandled: Boolean;
        ShouldPostItemJnlLine: Boolean;
    begin
        IsHandled := false;
        OnBeforePostItemJnlLine(
          SalesHeader, SalesLine, QtyToBeShipped, QtyToBeShippedBase, QtyToBeInvoiced, QtyToBeInvoicedBase,
          ItemLedgShptEntryNo, ItemChargeNo, TrackingSpecification, IsATO, SuppressCommit, IsHandled, Result, TempTrackingSpecification, TempHandlingSpecification, TempValueEntryRelation, ItemJnlPostLine);
        if IsHandled then
            exit(Result);

        with ItemJnlLine do begin
            PostItemJnlLinePrepareJournalLine(ItemJnlLine, SalesHeader, SalesLine, QtyToBeShipped, QtyToBeShippedBase, QtyToBeInvoiced, QtyToBeInvoicedBase,
                ItemLedgShptEntryNo, ItemChargeNo, TrackingSpecification, IsATO);

            ShouldPostItemJnlLine := not JobContractLine;
            OnPostItemJnlLineOnBeforeIsJobContactLineCheck(ItemJnlLine, SalesHeader, SalesLine, ShouldPostItemJnlLine);

            IsHandled := false;
            OnSkipPostingOnPostItemJnlLine(SalesLine, ItemJnlLine, IsHandled); //CustPub
            if not IsHandled then begin
                if ShouldPostItemJnlLine then begin

    [IntegrationEvent(false, false)]
    local procedure OnSkipPostingOnPostItemJnlLine(SalesLine: Record "Sales Line"; ItemJournalLine: Record "Item Journal Line"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494041

**Comment by AleksandricMarko** [comment]
Hello @StefanSosic 
existing publisher OnPostItemJnlLineOnBeforeIsJobContactLineCheck can be used to update value of variable "ShouldPostItemJnlLine"
