### ISSUE TITLE
[Event Request] Table 37 "Sales Line" - procedure UpdateICPartner()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25439]
### Describe the request

    procedure UpdateICPartner()
    var
        ICPartner: Record "IC Partner";
        ShouldUpdateICPartner: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnUpdateICPartner(Rec, SalesHeader, IsHandled); //CustPub
        if IsHandled then 
            exit;

        ShouldUpdateICPartner :=
            SalesHeader."Send IC Document" and (SalesHeader."IC Direction" = SalesHeader."IC Direction"::Outgoing) and
            (SalesHeader."Bill-to IC Partner Code" <> '');

    [IntegrationEvent(false, false)]
    local procedure OnUpdateICPartner(var SalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494045

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14714.
