### ISSUE TITLE
[Event Modification] Codeunit 80 "Sales-Post" - OnPostInvoicePostBufferOnBeforeTempInvoicePostBufferDeleteAll

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25436]
### Describe the request

   [Obsolete('Moved to Sales Invoice Posting implementation.', '19.0')]
    local procedure PostInvoicePostBuffer(SalesHeader: Record "Sales Header"; var TotalAmount: Decimal)
    var
        LineCount: Integer;
        GLEntryNo: Integer;
    begin
        OnBeforePostInvoicePostBuffer(SalesHeader, TempInvoicePostBuffer, TotalSalesLine, TotalSalesLineLCY);

        LineCount := 0;
        if TempInvoicePostBuffer.Find('+') then
            repeat
                LineCount := LineCount + 1;
                if GuiAllowed and not HideProgressWindow then
                    Window.Update(3, LineCount);

                TempInvoicePostBuffer.ApplyRoundingForFinalPosting();
                GLEntryNo := PostInvoicePostBufferLine(SalesHeader, TempInvoicePostBuffer);

                if (TempInvoicePostBuffer."Job No." <> '') and
                   (TempInvoicePostBuffer.Type = TempInvoicePostBuffer.Type::"G/L Account")
                then
                    JobPostLine.PostSalesGLAccounts(TempInvoicePostBuffer, GLEntryNo);
                OnPostInvoicePostBufferOnAfterPostSalesGLAccounts(SalesHeader, TempInvoicePostBuffer, TotalSalesLine, TotalSalesLineLCY, GenJnlLineDocNo, GLEntryNo, SrcCode);

            until TempInvoicePostBuffer.Next(-1) = 0;

        TempInvoicePostBuffer.CalcSums(Amount);
        TotalAmount := -TempInvoicePostBuffer.Amount;

        OnPostInvoicePostBufferOnBeforeTempInvoicePostBufferDeleteAll(
            SalesHeader, GenJnlPostLine, TotalSalesLine, TotalSalesLineLCY, GenJnlLineDocType, GenJnlLineDocNo, GenJnlLineExtDocNo, SrcCode);
        OnPostInvoicePostBufferOnBeforeTempInvoicePostBufferDeleteAll(
            SalesHeader, GenJnlPostLine, TotalSalesLine, TotalSalesLineLCY, GenJnlLineDocType, GenJnlLineDocNo, GenJnlLineExtDocNo, SrcCode, TempInvoicePostBuffer); //CustPub
        TempInvoicePostBuffer.DeleteAll();
    end;

    [Obsolete('Moved to Sales Invoice Posting implementation.', '19.0')]
    [IntegrationEvent(false, false)]
    local procedure OnPostInvoicePostBufferOnBeforeTempInvoicePostBufferDeleteAll(var SalesHeader: Record "Sales Header"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; var TotalSalesLine: Record "Sales Line"; var TotalSalesLineLCY: Record "Sales Line"; GenJnlLineDocType: Enum "Gen. Journal Document Type"; GenJnlLineDocNo: Code[20]; GenJnlLineExtDocNo: Code[35]; SrcCode: Code[10]; TempInvoicePostBuffer: Record "Invoice Post. Buffer" temporary) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.

Additional parameter TempInvoicePostBuffer to already existing publisher OnPostInvoicePostBufferOnBeforeTempInvoicePostBufferDeleteAll<br /><br />Internal work item: AB#494033

**Comment by AleksandricMarko** [comment]
Hello @StefanSosic 
we are not adding new publishers in the obsoleted procedures.
