### ISSUE TITLE
[Event Request] Codeunit 7000 "Sales Price Calc. Mgt." - procedure SetResPrice

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25435]
### Describe the request

    procedure SetResPrice(Code2: Code[20]; WorkTypeCode: Code[10]; CurrencyCode: Code[10])
    begin
        with ResPrice do begin
            Init;
            OnSetResPriceOnAfterInit(ResPrice); //CustPub
            Code := Code2;
            "Work Type Code" := WorkTypeCode;
            "Currency Code" := CurrencyCode;
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnSetResPriceOnAfterInit(var ResPrice: Record "Resource Price") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494037

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14917.
