### ISSUE TITLE
[Event Request] Codeunit 7000 "Sales Price Calc. Mgt." - procedure FindSalesLinePrice

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25434]
### Describe the request

    procedure FindSalesLinePrice(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; CalledByFieldNo: Integer)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeFindSalesLinePrice(SalesLine, SalesHeader, CalledByFieldNo, IsHandled);
        if IsHandled then
            exit;

        with SalesLine do begin
            SetCurrency(
              SalesHeader."Currency Code", SalesHeader."Currency Factor", SalesHeaderExchDate(SalesHeader));
            SetVAT(SalesHeader."Prices Including VAT", "VAT %", "VAT Calculation Type".AsInteger(), "VAT Bus. Posting Group");
            SetUoM(Abs(Quantity), "Qty. per Unit of Measure");
            SetLineDisc("Line Discount %", "Allow Line Disc.", "Allow Invoice Disc.");
            OnFindSalesLinePriceOnAfterSetLineDisc(SalesLine);

            TestField("Qty. per Unit of Measure");
            if PricesInCurrency then
                SalesHeader.TestField("Currency Factor");

            case Type of
                Type::Item:
                    begin
                        Item.Get("No.");
                        SalesLinePriceExists(SalesHeader, SalesLine, false);
                        OnBeforeFindSalesLineItemPrice(SalesLine, TempSalesPrice); //CustPub
                        CalcBestUnitPrice(TempSalesPrice);
                        OnAfterFindSalesLineItemPrice(SalesLine, TempSalesPrice, FoundSalesPrice, CalledByFieldNo);

    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindSalesLineItemPrice(SalesLine: Record "Sales Line"; var TempSalesPrice: Record "Sales Price" temporary) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494046

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14917.
