### ISSUE TITLE
[Event Request] Table 113 "Sales Invoice Line" - 

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25440]
### Describe the request

        field(6; "No."; Code[20])
        {
            CaptionClass = GetCaptionClass(FieldNo("No."));
            Caption = 'No.';
            TableRelation = IF (Type = CONST("G/L Account")) "G/L Account"
            ELSE
            IF (Type = CONST(Item)) Item
            ELSE
            IF (Type = CONST(Resource)) Resource
            ELSE
            IF (Type = CONST("Fixed Asset")) "Fixed Asset"
            ELSE
            IF (Type = CONST("Charge (Item)")) "Item Charge";

            trigger OnLookup()
            begin
                OnLookupNo(Rec); //CustPub
            end;
        }

    [IntegrationEvent(false, false)]
    local procedure OnLookupNo(SalesInvLine: Record "Sales Invoice Line") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.

To add Lookup trigger with publisher.<br /><br />Internal work item: [AB#494044](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/494044)

**Comment by alexei-dobriansky** [comment]
This kind of change have impact on default lookup.
