### ISSUE TITLE
Codeunit 12 - Gen. Jnl.-Post Line - expose InitGLEntry & PostGenJnlLine functions

### ISSUE THREAD

**Issue by rgrygoryshchak** [microsoft/ALAppExtensions#2544]
Hi,

   Is it possible to mark functions InitGLEntry & PostGenJnlLine as **Global** in Codeunit 12 (Gen. Jnl.-Post Line)?

   We need to use requested functions from events originated from cu12 itself to post additional entries by passing instance of cu12 to handler with IncludeSender property.

  _In ideal world in addition to local and global access modifiers we should also have protected ;-)
And sender's protected members should be visible from event handlers._

  _It would be also beneficial to set IncludeSender by default on Integration events._
  
Regards, Roman.

**Comment by RomanZanizdra** [comment]
Hi Roman.
At this moment we don't plan to expose functions you mentioned. Why the standard way of General Journal creating and posting (like in sales/purchases) doesn't fit to your process? Can you describe your case so we can find out the appropriate way?

**Comment by rgrygoryshchak** [comment]
Hi Roman,
 
   What is the issue with exposing InitGLEntry? I understand it looks dodgy, but you already have exposed InsertGLEntry and this is more dangerous!

   As for reason why we need this please check related issue 2550 where I'm trying explain one of the usage:

> In this particular case after each Cust/Vend ledger application or unapplication based on application data we could generate additional G/L Entries.
> 
> The idea is:
> 
> Before application starts we record last Detailed Cust/Vend Ledger Entry No. and save it somewhere.
> 
> In OnBeforeFinishPosting event handler we analyse new Detailed Cust/Vend Ledger Entries and based on application data create new G/L Entries by Sender.InitGLEntry and Sender.InsertGLEntry
> 

We also need PostGenJnlLine for different scenario where we split original journal line into two.

But as I said before we want to use requested functions from inside events originated from cu12 itself.

Sorry for short explanation. I'm on holiday at the moment. Please let me know if you need more information.

Regards, Roman.

**Comment by RomanZanizdra** [comment]
Ok, then external CreateGLEntry should fit your requirements.
Please don't be in a hurry to answer anything, enjoy your vacations, we will talk later after you return back.

**Comment by rgrygoryshchak** [comment]
Hi Roman.

Thank you for your help.

   I'm aware about CreateGLEntry function, but the problem is that we need to populate some 'G/L Entry' fields between InitGLEntry and InsertGLEntry :-( 

Typical usage would be:
```
Sender.InitGLEntry
... populate 'G/L Entry' fields
Sender.InsertGLEntry
```
PS. I'm collecting details about  PostGenJnlLine requirements.

**Comment by RomanZanizdra** [comment]
Ok, there are two events "before/after" in InitGLEntry, I suppose you don't need events from all InitGLEntry calls, so you can do manual subscription via BINDSUBSCRIPTION and changes you need.

**Comment by rgrygoryshchak** [comment]
I see. And how would you suggest to pass any data into OnAfterInitGLEntry event? 

Small sample of existing code for you to understand:

```
        InitGLEntry(GenJnlLine,GlobalGLEntry,BusUnitMatrix."Debit G/L Account No.",AmountToApply*TransferMultiplier,0,FALSE,TRUE);
        GlobalGLEntry."Business Unit Code" := BusUnitMatrix."Debit Business Unit Code";
        CopyCustApplicationToGLEntry(CustLedgEntry);
        InsertGLEntry(GenJnlLine,GlobalGLEntry,TRUE);

        InitGLEntry(GenJnlLine,GlobalGLEntry,BusUnitMatrix."Credit G/L Account No.",-AmountToApply*TransferMultiplier,0,FALSE,TRUE);
        GlobalGLEntry."Business Unit Code" := BusUnitMatrix."Credit Business Unit Code";
        CopyCustApplicationToGLEntry(CustLedgEntry);
        InsertGLEntry(GenJnlLine,GlobalGLEntry,TRUE);

        InitGLEntry(GenJnlLine,GlobalGLEntry,CustPostingGr."Receivables Account",AmountToApply*PaymentMultiplier,0,FALSE,TRUE);
        GlobalGLEntry."Business Unit Code" := BusUnitAppPay."Initial Business Unit Code";
        CopyCustApplicationToGLEntry(CustLedgEntry);
        InsertGLEntry(GenJnlLine,GlobalGLEntry,TRUE);

        InitGLEntry(GenJnlLine,GlobalGLEntry,CustPostingGr."Receivables Account",-AmountToApply*PaymentMultiplier,0,FALSE,TRUE);
        GlobalGLEntry."Business Unit Code" := BusUnitAppInv."Initial Business Unit Code";
        CopyCustApplicationToGLEntry(CustLedgEntry);
        InsertGLEntry(GenJnlLine,GlobalGLEntry,TRUE);
```

```
LOCAL CopyCustApplicationToGLEntry(CustLedgEntry : Record "Cust. Ledger Entry")
GlobalGLEntry."Posting Reference" := CustLedgEntry."Posting Reference";
GlobalGLEntry."Document Type" := CustLedgEntry."Document Type";
GlobalGLEntry."Document Class" := CustLedgEntry."Document Class";
GlobalGLEntry."Source Code" := CustLedgEntry."Source Code";
GlobalGLEntry."Source Type" := GlobalGLEntry."Source Type"::Customer;
GlobalGLEntry."Source No." := CustLedgEntry."Customer No.";
GlobalGLEntry."Global Dimension 1 Code" := CustLedgEntry."Global Dimension 1 Code";
GlobalGLEntry."Global Dimension 2 Code" := CustLedgEntry."Global Dimension 2 Code";
GlobalGLEntry."Dimension Set ID" := CustLedgEntry."Dimension Set ID";
```

PS. I'm not saying this is impossible. We could for example add some dummy fields to GenJnlLine table, or store data in database or single instance codeunit. But this is very awkward programming in my opinion :-(

PS. I understand that you are trying to provide solution based on existing functionality, but I'm looking for some solid API to work with G/L entries in new D365BC.

Thank you for your help.

**Comment by rgrygoryshchak** [comment]
Any ideas how to use PostGenJnlLine function from inside of event originated from cu12?
Is it safe to call RunWithCheck/RunWithoutCheck function from inside of OnAfterGLFinishPosting event?
Regards, Roman.

**Comment by RomanZanizdra** [comment]
- About your example. 
You have a subscriber codeunit with manual type. Now you cannot call init/insert functions but you can call Createglentry. Before this (or if there any other obvious attributes) you can do BINDSUBSCRIPTION with your subscriber codeunit in order to process only required case and not all Inits. Then you will have OnAfterInit… event where you can change g/l entry (not the GlobalGLEntry). How you will pass additional information in subscriber - it's on your choice. After you call Create... then unbind. Do you any contradictions in the suggestion?
- About PostGen…. function
At this moment function is not planned to be external. You need somehow rework your solution. In my own opinion I would not use runwithcheck or without check directly from COD12 events. But it's also on your choice, may be it will perfectly for your case, because I don't know what you are going to achieve as a result.

**Comment by RomanZanizdra** [comment]
Hi Roman. Any update from your side, I plan to close this issue?

**Comment by rgrygoryshchak** [comment]
Thank you for your help. We could close this issue now.
Regards, Roman.

**Comment by RomanZanizdra** [comment]
Thanks for collaboration.
