### ISSUE TITLE
[Event Request] Page 233 "Apply Vendor Entries" - trigger OnQueryClosePage

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25445]
### Describe the request

    trigger OnQueryClosePage(CloseAction: Action): Boolean
    var
        RaiseError: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeOnQueryClosePage(CloseAction, TempApplyingVendLedgEntry, ApplnType, Rec, CalcType, IsHandled); //CustPub
        if not IsHandled then begin
            if CloseAction = ACTION::LookupOK then
                LookupOKOnPush();
            if ApplnType = ApplnType::"Applies-to Doc. No."

    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnQueryClosePage(CloseAction: Action; ApplyingVendLedgEntry: Record "Vendor Ledger Entry"; ApplnType: Enum "Vendor Apply-to Type"; Rec: Record "Vendor Ledger Entry"; CalcType: Enum "Vendor Apply Calculation Type"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494043

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14714.
