### ISSUE TITLE
[Event Request] Codeunit 97 "Blanket Purch. Order to Order" - trigger OnRun()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25449]
### Describe the request

    trigger OnRun()
    var
        Vend: Record Vendor;
        PurchCommentLine: Record "Purch. Comment Line";
        PrepmtMgt: Codeunit "Prepayment Mgt.";
        RecordLinkManagement: Codeunit "Record Link Management";
        PurchCalcDiscByType: Codeunit "Purch - Calc Disc. By Type";
        ShouldRedistributeInvoiceAmount: Boolean;
        IsHandled: Boolean;
    begin
        OnBeforeRun(Rec);

        TestField("Document Type", "Document Type"::"Blanket Order");
        ShouldRedistributeInvoiceAmount := PurchCalcDiscByType.ShouldRedistributeInvoiceDiscountAmount(Rec);

        Vend.Get("Buy-from Vendor No.");
        Vend.CheckBlockedVendOnDocs(Vend, false);

        ValidatePurchaserOnPurchHeader(Rec, true, false);

        CheckForBlockedLines;

        if QtyToReceiveIsZero then
            Error(Text002);

        PurchSetup.Get();

        CreatePurchHeader(Rec, Vend."Prepayment %");

        PurchBlanketOrderLine.Reset();
        PurchBlanketOrderLine.SetRange("Document Type", "Document Type");
        PurchBlanketOrderLine.SetRange("Document No.", "No.");
        OnRunOnAfterPurchBlanketOrderLineSetFilters(PurchBlanketOrderLine);
        if PurchBlanketOrderLine.FindSet() then
            repeat
                if (PurchBlanketOrderLine.Type = PurchBlanketOrderLine.Type::" ") or
                   (PurchBlanketOrderLine."Qty. to Receive" <> 0)
                then begin
                    CalcQuantityOnOrders();

                    CheckBlanketOrderLineQuantity();

                    PurchOrderLine := PurchBlanketOrderLine;
                    OnRunOnAfterInitPurchOrderLineFromBlanketOrderLine(PurchOrderLine);
                    ResetQuantityFields(PurchOrderLine);
                    PurchOrderLine."Document Type" := PurchOrderHeader."Document Type";
                    PurchOrderLine."Document No." := PurchOrderHeader."No.";
                    PurchOrderLine."Blanket Order No." := "No.";
                    PurchOrderLine."Blanket Order Line No." := PurchBlanketOrderLine."Line No.";

                    if (PurchOrderLine."No." <> '') and (PurchOrderLine.Type <> PurchOrderLine.Type::" ") then begin
                        PurchOrderLine.Amount := 0;
                        PurchOrderLine."Amount Including VAT" := 0;
                        PurchOrderLineValidateQuantity(PurchOrderLine, PurchBlanketOrderLine);
                        if PurchBlanketOrderLine."Expected Receipt Date" <> 0D then
                            PurchOrderLine.Validate("Expected Receipt Date", PurchBlanketOrderLine."Expected Receipt Date")
                        else
                            PurchOrderLine.Validate("Order Date", PurchOrderHeader."Order Date");
                        UpdatePurchOrderLineDirectUnitCost();
                        PurchOrderLineValidateLineDiscountPct(PurchOrderLine, PurchBlanketOrderLine);
                        if PurchOrderLine.Quantity <> 0 then
                            PurchOrderLine.Validate("Inv. Discount Amount", PurchBlanketOrderLine."Inv. Discount Amount");
                        PurchBlanketOrderLine.CalcFields("Reserved Qty. (Base)");
                        OnRunOnAfterCalcReservedQtyBase(Rec, PurchBlanketOrderLine, PurchOrderHeader, PurchOrderLine);
                        if PurchBlanketOrderLine."Reserved Qty. (Base)" <> 0 then
                            PurchLineReserve.TransferPurchLineToPurchLine(
                              PurchBlanketOrderLine, PurchOrderLine, -PurchBlanketOrderLine."Qty. to Receive (Base)");
                    end;

                    if Vend."Prepayment %" <> 0 then
                        PurchOrderLine."Prepayment %" := Vend."Prepayment %";
                    PrepmtMgt.SetPurchPrepaymentPct(PurchOrderLine, PurchOrderHeader."Posting Date");
                    PurchOrderLine.Validate("Prepayment %");

                    PurchOrderLine."Shortcut Dimension 1 Code" := PurchBlanketOrderLine."Shortcut Dimension 1 Code";
                    PurchOrderLine."Shortcut Dimension 2 Code" := PurchBlanketOrderLine."Shortcut Dimension 2 Code";
                    PurchOrderLine."Dimension Set ID" := PurchBlanketOrderLine."Dimension Set ID";
                    PurchOrderLine.DefaultDeferralCode;
                    if IsPurchOrderLineToBeInserted(PurchOrderLine) then begin
                        OnBeforeInsertPurchOrderLine(PurchOrderLine, PurchOrderHeader, PurchBlanketOrderLine, Rec);
                        PurchOrderLine.Insert();
                        OnAfterPurchOrderLineInsert(PurchOrderLine, PurchBlanketOrderLine);
                    end;

                    OnRunOnBeforeCheckModifyPurchBlanketOrderLine(PurchOrderLine, PurchBlanketOrderLine, PurchLine);
                    if PurchBlanketOrderLine."Qty. to Receive" <> 0 then begin
                        PurchBlanketOrderLine.Validate("Qty. to Receive", 0);
                        PurchBlanketOrderLine.Modify();
                    end;

                    OnRunOnAfterPurchBlanketOrderLineLoop(PurchOrderLine, PurchLine, PurchBlanketOrderLine);
                end;
            until PurchBlanketOrderLine.Next() = 0;

        OnAfterInsertAllPurchOrderLines(Rec, PurchOrderHeader);

        if PurchSetup."Default Posting Date" = PurchSetup."Default Posting Date"::"No Date" then begin
            PurchOrderHeader."Posting Date" := 0D;
            PurchOrderHeader.Modify();
        end;

        if PurchSetup."Copy Comments Blanket to Order" then begin
            PurchCommentLine.CopyComments(
                PurchCommentLine."Document Type"::"Blanket Order".AsInteger(),
                PurchOrderHeader."Document Type".AsInteger(), "No.", PurchOrderHeader."No.");
            RecordLinkManagement.CopyLinks(Rec, PurchOrderHeader);
        end;

        if not (ShouldRedistributeInvoiceAmount or PurchSetup."Calc. Inv. Discount") then
            PurchCalcDiscByType.ResetRecalculateInvoiceDisc(PurchOrderHeader);

        OnRunOnBeforeCommit(Rec, PurchOrderHeader); //CustPub
        Commit();

        OnAfterRun(Rec, PurchOrderHeader);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnRunOnBeforeCommit(var PurchaseHeader: Record "Purchase Header"; var PurchOrderHeader: Record "Purchase Header") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494049

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14667.
