### ISSUE TITLE
[Event Request] Page 233 "Apply Vendor Entries" - trigger OnModifyRecord

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25444]
### Describe the request

    trigger OnModifyRecord(): Boolean
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalcApplnAmountOnModifyRecord(CalcType, AppliedVendLedgEntry, IsHandled); //CustPub
        if not IsHandled then
            CODEUNIT.Run(CODEUNIT::"Vend. Entry-Edit", Rec);
        if Rec."Applies-to ID" <> xRec."Applies-to ID" then
            CalcApplnAmount();
        exit(false);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcApplnAmountOnModifyRecord(CalcType: Enum "Vendor Apply Calculation Type"; var Rec: Record "Vendor Ledger Entry"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494024

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14714.
