### ISSUE TITLE
[Event Modification] Codeunit 5611 "Calculate Normal Depreciation" - OnAfterBookValueRecalculateBookValue

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25456]
### Describe the request

  local procedure TransferValues()
    var
        IsHandled: Boolean;
    begin
        with FADeprBook do begin
            TestField("Depreciation Starting Date");
            if "Depreciation Method" = "Depreciation Method"::"User-Defined" then begin
                TestField("Depreciation Table Code");
                TestField("First User-Defined Depr. Date");
            end;
            case "Depreciation Method" of
                "Depreciation Method"::"Declining-Balance 1",
              "Depreciation Method"::"Declining-Balance 2",
              "Depreciation Method"::"DB1/SL",
              "Depreciation Method"::"DB2/SL":
                    if "Declining-Balance %" >= 100 then
                        Error(Text001, GetFAName(), FieldCaption("Declining-Balance %"));
            end;
            if (DeprBook."Periodic Depr. Date Calc." = DeprBook."Periodic Depr. Date Calc."::"Last Depr. Entry") and
               ("Depreciation Method" <> "Depreciation Method"::"Straight-Line")
            then begin
                "Depreciation Method" := "Depreciation Method"::"Straight-Line";
                Error(
                  Text002,
                  GetFAName(),
                  FieldCaption("Depreciation Method"),
                  "Depreciation Method",
                  DeprBook.TableCaption,
                  DeprBook.FieldCaption("Periodic Depr. Date Calc."),
                  DeprBook."Periodic Depr. Date Calc.");
            end;

            SetDeprMethod(FADeprBook);

            if DateFromProjection = 0D then begin
                CalcFields("Book Value");
                BookValue := "Book Value";
            end else
                BookValue := EntryAmounts[1];
            MinusBookValue := DepreciationCalc.GetMinusBookValue(FA."No.", DeprBookCode, 0D, 0D);
            CalcFields("Depreciable Basis", "Salvage Value");
            DeprBasis := "Depreciable Basis";
            SalvageValue := "Salvage Value";

            OnAfterBookValueRecalculateBookValue(FA, DeprBook, FALedgEntry, DeprBasis, BookValue, EndingDate, FADeprBook."Disposal Date");
            OnAfterBookValueRecalculateBookValue(FA, DeprBook, FALedgEntry, DeprBasis, BookValue, EndingDate, FADeprBook."Disposal Date", DateFromProjection); //CustPub

            BookValue2 := BookValue;
            SalvageValue2 := SalvageValue;

    [IntegrationEvent(false, false)]
    local procedure OnAfterBookValueRecalculateBookValue(FixedAsset: Record "Fixed Asset";DeprBook: Record "Depreciation Book";FAledgEntry2: Record "FA Ledger Entry";var DeprBasis: Decimal;var BookValue: Decimal;var DeprEndingDate: Date;DisposalDate: date;DateFromProjection: Date) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.

Additional parameter DateFromProjection to already existing publisher OnAfterBookValueRecalculateBookValue<br /><br />Internal work item: AB#494052

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14667.
