### ISSUE TITLE
[Event Request] Table 352 "Default Dimension" - procedure GetCaption()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25458]
### Describe the request

    procedure GetCaption(): Text[250]
    var
        ObjTransl: Record "Object Translation";
        CurrTableID: Integer;
        NewTableID: Integer;
        NewNo: Code[20];
        SourceTableName: Text[100];
        RetCaption: Text[250];
    begin
        if not Evaluate(NewTableID, GetFilter("Table ID")) then
            exit('');

        if NewTableID = 0 then
            if GetRangeMin("Table ID") = GetRangeMax("Table ID") then
                NewTableID := GetRangeMin("Table ID")
            else
                NewTableID := 0;

        if NewTableID <> CurrTableID then
            SourceTableName := ObjTransl.TranslateObject(ObjTransl."Object Type"::Table, NewTableID);
        CurrTableID := NewTableID;

        if GetFilter("No.") <> '' then
            if GetRangeMin("No.") = GetRangeMax("No.") then
                NewNo := GetRangeMin("No.")
            else
                NewNo := '';

        OnAfterGetCaption(NewTableID, SourceTableName, NewNo, RetCaption); //CustPub
        if RetCaption <> '' then
            exit(RetCaption);

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetCaption(NewTableID: Integer; SourceTableName: Text[100]; NewNo: Code[20]; var RetCaption: Text[250]) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494055

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14667.
