### ISSUE TITLE
[Event Request] Codeunit 5611 "Calculate Normal Depreciation" -  local procedure CalculateDeprAmount

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25452]
### Describe the request

local procedure CalculateDeprAmount(): Decimal
    var
        Amount: Decimal;
        IsHandled: Boolean;
    begin
        with FA do begin
            if DateFromProjection > 0D then
                FirstDeprDate := DateFromProjection
            else begin
                FirstDeprDate := DepreciationCalc.GetFirstDeprDate("No.", DeprBookCode, Year365Days);
                if FirstDeprDate > UntilDate then
                    exit(0);
                UseDeprStartingDate := DepreciationCalc.UseDeprStartingDate("No.", DeprBookCode);
                if UseDeprStartingDate then
                    FirstDeprDate := DeprStartingDate;
            end;
            if FirstDeprDate < DeprStartingDate then
                FirstDeprDate := DeprStartingDate;

            IsHandled := false;
            OnBeforeNumberofDayCalculateNumberofDays(FA, DeprBook, NumberofDays, FirstDeprDate, UntilDate, Year365Days, IsHandled, FADeprBook);
            if not IsHandled then
                NumberOfDays := DepreciationCalc.DeprDays(FirstDeprDate, UntilDate, Year365Days);

            Factor := 1;
            if NumberOfDays <= 0 then
                exit(0);
            ProcessDaysInPeriod();
            UseHalfYearConvention := SetHalfYearConventionMethod();

            UpdateDaysInFiscalYear(FA, DeprBook, NumberOfDays, DaysInFiscalYear, IsHandled);

            // Method Last Entry
            if UseDeprStartingDate or
               (DateFromProjection > 0D) or
               (DeprMethod = DeprMethod::"Below Zero") or
               (DeprBook."Periodic Depr. Date Calc." = DeprBook."Periodic Depr. Date Calc."::"Last Entry")
            then begin
                NumberOfDays2 := NumberOfDays;
                if UseHalfYearConvention then
                    Amount := CalcHalfYearConventionDepr()
                else
                    case DeprMethod of
                        DeprMethod::"Straight-Line":
                            Amount := CalcSLAmount;
                        DeprMethod::"Declining-Balance 1":
                            Amount := CalcDB1Amount;
                        DeprMethod::"Declining-Balance 2":
                            Amount := CalcDB2Amount;
                        DeprMethod::"DB1/SL",
                        DeprMethod::"DB2/SL":
                            Amount := CalcDBSLAmount;
                        DeprMethod::Manual:
                            Amount := 0;
                        DeprMethod::"User-Defined":
                            Amount := CalcUserDefinedAmount(UntilDate);
                        DeprMethod::"Below Zero":
                            Amount := DepreciationCalc.CalcRounding(DeprBookCode, CalcBelowZeroAmount());
                        DeprMethod::"Country Specific":
                            ; // Reserved for implementation of country specific methods
                        else
                            OnCalculateDeprAmountOnDeprMethodCaseLastEntry(
                                FADeprBook, BookValue, DeprBasis, DeprYears, DaysInFiscalYear, NumberOfDays, Amount, DateFromProjection, UntilDate);
                    end;
                OnCalculateDeprAmountOnAfterAssignAmountLastEntry(FADeprBook, UntilDate, DateFromProjection, BookValue, UseHalfYearConvention, DaysInFiscalYear, NumberOfDays);
            end
            // Method Last Depreciation Entry
            else begin
                if UseHalfYearConvention then
                    DeprBook.TestField(
                      "Periodic Depr. Date Calc.", DeprBook."Periodic Depr. Date Calc."::"Last Entry");
                Amount := 0;
                StartingDate := 0D;
                EndingDate := 0D;
                DepreciationCalc.GetDeprPeriod(
                  "No.", DeprBookCode, UntilDate, StartingDate, EndingDate, NumberOfDays, Year365Days);
                FirstDeprDate := StartingDate;
                NumberOfDays2 := DepreciationCalc.DeprDays(FirstDeprDate, UntilDate, Year365Days);
                while NumberOfDays > 0 do begin
                    DepreciationCalc.CalculateDeprInPeriod(
                      "No.", DeprBookCode, EndingDate, Amount, Sign,
                      BookValue, DeprBasis, SalvageValue, MinusBookValue);
                    if DepreciationCalc.GetSign(
                         BookValue, DeprBasis, SalvageValue, MinusBookValue) <> 1
                    then
                        exit(0);
                    case DeprMethod of
                        DeprMethod::"Straight-Line":
                            Amount := Amount + CalcSLAmount();
                        DeprMethod::"Declining-Balance 1":
                            Amount := Amount + CalcDB1Amount();
                        DeprMethod::"Declining-Balance 2":
                            Amount := Amount + CalcDB2Amount();
                        DeprMethod::Manual:
                            Amount := 0;
                        DeprMethod::"User-Defined":
                            Amount := Amount + CalcUserDefinedAmount(EndingDate);
                        DeprMethod::"Country Specific":
                            ; // Reserved for implementation of country specific
                        else
                            OnCalculateDeprAmountOnDeprMethodCaseLastDeprEntry(
                                FADeprBook, BookValue, DeprBasis, DeprYears, DaysInFiscalYear, NumberOfDays, Amount, DateFromProjection, UntilDate);
                    end;
                    DepreciationCalc.GetDeprPeriod(
                      "No.", DeprBookCode, UntilDate, StartingDate, EndingDate, NumberOfDays, Year365Days);
                    FirstDeprDate := StartingDate;
                end;
            end;
        end;

        IsHandled := false;
        OnBeforeCalculateDeprAmount(FA, SkipOnZero, DeprBookCode, Amount, BookValue2, -Abs(SalvageValue2), EndingBookValue, FinalRoundingAmount, IsHandled); //CustPub
        if IsHandled then
            exit(Round(Amount));

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalculateDeprAmount(FixedAsset: Record "Fixed Asset"; SkipOnZero: Boolean; DeprBookCode: Code[20]; var Amount: Decimal; BookValue: Decimal; SalvageValue: Decimal; EndingBookValue: Decimal; FinalRoundingAmount: Decimal; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494048

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14667.
