### ISSUE TITLE
[Event Request] Codeunit 5611 "Calculate Normal Depreciation" -  local procedure CalcDBSLAmount

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25455]
### Describe the request

    local procedure CalcDBSLAmount(): Decimal
    var
        FADateCalc: Codeunit "FA Date Calculation";
        SLAmount: Decimal;
        DBAmount: Decimal;
    begin
        if DeprMethod = DeprMethod::"DB1/SL" then
            DBAmount := CalcDB1Amount
        else
            DBAmount := CalcDB2Amount();
        if FADeprBook."Use DB% First Fiscal Year" then
            if FADateCalc.GetFiscalYear(DeprBookCode, UntilDate) =
               FADateCalc.GetFiscalYear(DeprBookCode, DeprStartingDate)
            then
                exit(DBAmount);
        SLAmount := CalcSLAmount();
        if SLAmount < DBAmount then
            exit(SLAmount);

        OnAfterCalcDBSLAmount(DBAmount, SLAmount, FADeprBook, DateFromProjection); //CustPub
        exit(DBAmount)
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcDBSLAmount(var DBAmount: Decimal; SLAmount: Decimal; FADeprBook: Record "FA Depreciation Book"; DateFromProjection: Date) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494051

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14667.
