### ISSUE TITLE
[Event Modification] Table 9500 "Email Item" - OnBeforeSend

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25463]
### Describe the request

    procedure Send(HideMailDialog: Boolean; EmailScenario: Enum "Email Scenario"): Boolean
    var
        MailManagement: Codeunit "Mail Management";
        IsHandled: Boolean;
        Result: Boolean;
    begin
        IsHandled := false;
        OnBeforeSend(Rec, HideMailDialog, MailManagement);
        OnBeforeSend(Rec, HideMailDialog, MailManagement, EmailScenario, Result, IsHandled); //CustPub
        if IsHandled then
            exit(Result);
        MailManagement.SendMailOrDownload(Rec, HideMailDialog, EmailScenario);
        exit(MailManagement.IsSent());
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSend(var EmailItem: Record "Email Item"; var HideMailDialog: Boolean; var MailManagement: Codeunit "Mail Management"; EmailScenario: Enum "Email Scenario"; var Result: Boolean; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.

Additional parameter EmailScenario, Result, IsHandled to already existing publisher OnBeforeSend<br /><br />Internal work item: AB#494071

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14714.
