### ISSUE TITLE
[Event Request] codeunit 5636 "FA. Jnl.-Post" -     local procedure "Code"()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25467]
### Describe the request

    local procedure "Code"()
    begin
        OnBeforeCode(FAJnlLine); //CustPub
        with FAJnlLine do begin
            FAJnlTemplate.Get("Journal Template Name");
            FAJnlTemplate.TestField("Force Posting Report", false);
            if FAJnlTemplate.Recurring and (GetFilter("FA Posting Date") <> '') then
                FieldError("FA Posting Date", Text000);

            if not ConfirmPost() then
                exit;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCode(var FAJournalLine: Record "FA Journal Line") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494066

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14714.
