### ISSUE TITLE
[Event Request] Codeunit 5616 "Depreciation Calculation" - procedure CalcEntryAmounts

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25461]
### Describe the request

    procedure CalcEntryAmounts(FANo: Code[20]; DeprBookCode: Code[10]; StartingDate: Date; EndingDate: Date; var EntryAmounts: array[4] of Decimal)
    var
        FALedgEntry: Record "FA Ledger Entry";
        I: Integer;
    begin
        if EndingDate = 0D then
            EndingDate := DMY2Date(31, 12, 9999);
        with FALedgEntry do begin
            SetFAFilter(FALedgEntry, FANo, DeprBookCode, true);
            SetRange("FA Posting Date", StartingDate, EndingDate);
            SetRange("Part of Book Value", true);
            for I := 1 to 4 do begin
                case I of
                    1:
                        SetRange("FA Posting Type", "FA Posting Type"::"Write-Down");
                    2:
                        SetRange("FA Posting Type", "FA Posting Type"::Appreciation);
                    3:
                        SetRange("FA Posting Type", "FA Posting Type"::"Custom 1");
                    4:
                        SetRange("FA Posting Type", "FA Posting Type"::"Custom 2");
                end;
                OnCalcEntryAmountsOnAfterSetFALedgEntryFilters(FALedgEntry, I); //CustPub
                CalcSums(Amount);
                EntryAmounts[I] := Amount;
            end;
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCalcEntryAmountsOnAfterSetFALedgEntryFilters(var FALedgEntry: Record "FA Ledger Entry"; I: Integer) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494053

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14667.
