### ISSUE TITLE
[Event Reqeust] codeunit 5644 "FA Reclass. Jnl.-Transfer" -    local procedure "Code"()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25469]
### Describe the request

    local procedure "Code"()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCode(FAReclassJnlLine, IsHandled); //CustPub;
        if IsHandled then
            exit;
            
        with FAReclassJnlLine do begin
            FAReclassJnlTempl.Get("Journal Template Name");

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCode(var FAReclassJnlLine: Record "FA Reclass. Journal Line"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494057

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14667.
