### ISSUE TITLE
[Event Request] Page 542 "Default Dimensions-Multiple" - local procedure GetDefaultDim

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25460]
### Describe the request

    local procedure GetDefaultDim()
    var
        Dim: Record Dimension;
        RecNo: Integer;
    begin
        Reset;
        DeleteAll();
        if Dim.Find('-') then
            repeat
                RecNo := 0;
                TempDefaultDim2.SetRange("Dimension Code", Dim.Code);
                SetRange("Dimension Code", Dim.Code);
                if TempDefaultDim2.Find('-') then
                    repeat
                        if FindFirst() then begin
                            if "Dimension Value Code" <> TempDefaultDim2."Dimension Value Code" then
                                if ("Multi Selection Action" <> 10) and
                                   ("Multi Selection Action" <> 21)
                                then begin
                                    "Multi Selection Action" :=
                                      "Multi Selection Action" + 10;
                                    "Dimension Value Code" := '';
                                end;
                            if "Value Posting" <> TempDefaultDim2."Value Posting" then
                                if ("Multi Selection Action" <> 11) and
                                   ("Multi Selection Action" <> 21)
                                then begin
                                    "Multi Selection Action" :=
                                      "Multi Selection Action" + 11;
                                    "Value Posting" := "Value Posting"::" ";
                                end;
                            OnGetDefaultDimOnSameCode(Rec, TempDefaultDim2); //CustPub
                            Modify;
                            RecNo := RecNo + 1;
                        end else begin

    [IntegrationEvent(false, false)]
    local procedure OnGetDefaultDimOnSameCode(var DefaultDimension: Record "Default Dimension"; var TmpDefaultDimension2: Record "Default Dimension") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494070

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14714.
