### ISSUE TITLE
[Event Request] codeunit 13 "Gen. Jnl.-Post Batch" - local procedure ProcessLines

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25479]
### Describe the request

   local procedure ProcessLines(var GenJnlLine: Record "Gen. Journal Line")
    var
        TempGenJnlLine: Record "Gen. Journal Line" temporary;
        GenJnlLineVATInfoSource: Record "Gen. Journal Line";
        UpdateAnalysisView: Codeunit "Update Analysis View";
        ICOutboxExport: Codeunit "IC Outbox Export";
        TypeHelper: Codeunit "Type Helper";
        ErrorContextElement: Codeunit "Error Context Element";
        ErrorMessageMgt: Codeunit "Error Message Management";
        RecRef: RecordRef;
        ICLastDocNo: Code[20];
        CurrentICPartner: Code[20];
        LastLineNo: Integer;
        LastICTransactionNo: Integer;
        ICTransactionNo: Integer;
        ICLastDocType: Enum "Gen. Journal Document Type";
        ICLastDate: Date;
        VATInfoSourceLineIsInserted: Boolean;
        SkippedLine: Boolean;
        PostingAfterWorkingDateConfirmed: Boolean;
        IsHandled: Boolean;
    begin
        OnBeforeProcessLines(GenJnlLine, PreviewMode, SuppressCommit);

        with GenJnlLine do begin
            if not Find('=><') then begin
                "Line No." := 0;
                if PreviewMode then
                    GenJnlPostPreview.ThrowError;
                if not SuppressCommit then
                    Commit();
                DeleteDimBalBatch(GenJnlLine, false);
                exit;
            end;

            if GuiAllowed() then begin
                Window.Open(PostingStateMsg);
                Window.Update(1, "Journal Batch Name");
            end;

            // Check lines
            LineCount := 0;
            StartLineNo := "Line No.";
            NoOfRecords := CountGenJournalLines(GenJnlLine);
            GenJnlCheckLine.SetBatchMode(true);
            repeat
                LineCount := LineCount + 1;
                UpdateDialog(RefPostingState::"Checking lines", LineCount, NoOfRecords);
                CheckLine(GenJnlLine, PostingAfterWorkingDateConfirmed);
                TempGenJnlLine := GenJnlLine5;
                TempGenJnlLine.Insert();
                if Next() = 0 then
                    FindFirst();
            until "Line No." = StartLineNo;
            if GenJnlTemplate.Type = GenJnlTemplate.Type::Intercompany then
                CheckICDocument(TempGenJnlLine);

            ProcessBalanceOfLines(GenJnlLine, GenJnlLineVATInfoSource, VATInfoSourceLineIsInserted, LastLineNo, CurrentICPartner);

            // Find next register no.
            GLEntry.LockTable();
            FindNextGLRegisterNo;

            // Post lines
            LineCount := 0;
            LastDocNo := '';
            LastPostedDocNo := '';
            LastICTransactionNo := 0;
            TempGenJnlLine4.DeleteAll();
            NoOfReversingRecords := 0;
            FindSet(true, false);
            FirstLine := true;
            repeat
                ErrorMessageMgt.PushContext(ErrorContextElement, RecordId, 0, PostingLinesMsg);
                ProcessICLines(CurrentICPartner, ICTransactionNo, ICLastDocNo, ICLastDate, ICLastDocType, GenJnlLine, TempGenJnlLine);
                ProcessICTransaction(LastICTransactionNo, ICTransactionNo);
                OnProcessLinesOnAfterProcessICTransaction(GenJnlLine); //CustPub
                GenJnlLine3 := GenJnlLine;
                if not PostGenJournalLine(GenJnlLine3, CurrentICPartner, ICTransactionNo) then
                    SkippedLine := true;
                ErrorMessageMgt.PopContext(ErrorContextElement);
            until Next() = 0;

    [IntegrationEvent(false, false)]
    local procedure OnProcessLinesOnAfterProcessICTransaction(var GenJnlLine: Record "Gen. Journal Line") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494081

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
