### ISSUE TITLE
[Event Request] codeunit 5643 "FA Reclass. Transfer Batch" -  local procedure "Code"()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25471]
### Describe the request

    local procedure "Code"()
    var
        IsHandled: Boolean;
    begin
        with FAReclassJnlLine do begin
            SetRange("Journal Template Name", "Journal Template Name");
            SetRange("Journal Batch Name", "Journal Batch Name");
            LockTable();

            FAReclassJnlTempl.Get("Journal Template Name");
            FAReclassJnlBatch.Get("Journal Template Name", "Journal Batch Name");

            if not Find('=><') then begin
                "Line No." := 0;
                exit;
            end;

            Window.Open(
              Text001 +
              Text002 +
              Text003);
            Window.Update(1, "Journal Batch Name");

            LineCounter := 0;
            StartLineNo := "Line No.";
            repeat
                LineCounter := LineCounter + 1;
                Window.Update(2, LineCounter);
                FAReclassCheckLine.Run(FAReclassJnlLine);
                if Next() = 0 then
                    Find('-');
            until "Line No." = StartLineNo;
            NoOfRecords := LineCounter;

            LineCounter := 0;
            OneFAReclassDone := false;
            SetCurrentKey("Journal Template Name", "Journal Batch Name", "FA Posting Date");
            Find('-');
            IsHandled := false;
            OnCodeOnBeforeFAReclassLine(FAReclassJnlLine, NoOfRecords, OneFAReclassDone, IsHandled); //CustPub
            if not IsHandled then
                repeat
                    LineCounter := LineCounter + 1;
                    Window.Update(3, LineCounter);
                    Window.Update(4, Round(LineCounter / NoOfRecords * 10000, 1));
                    FAReclassTransferLine.FAReclassLine(FAReclassJnlLine, OneFAReclassDone);
                until Next() = 0;

    [IntegrationEvent(false, false)]
    local procedure OnCodeOnBeforeFAReclassLine(var FAReclassJnlLine: Record "FA Reclass. Journal Line"; NoOfRecords: Integer; var OneFAReclassDone: Boolean; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494063

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14667.
