### ISSUE TITLE
[Event Request] page 5600 "Fixed Asset Card" - protected procedure SetDefaultDepreciationBook

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25474]
### Describe the request

    protected procedure SetDefaultDepreciationBook()
    var
        FASetup: Record "FA Setup";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetDefaultDepreciationBook(Rec, FADepreciationBook, Simple, FADepreciationBookOld, ShowAddMoreDeprBooksLbl, AllowEditDepBookCode, IsHandled); //CustPub
        if IsHandled then
            exit;
        if FADepreciationBook."Depreciation Book Code" = '' then begin
            FASetup.Get();
            FADepreciationBook.Validate("Depreciation Book Code", FASetup."Default Depr. Book");
            SaveSimpleDepreciationBook("No.");
            LoadFADepreciationBooks();
        end;
    end;

    [IntegrationEvent(true, false)]
    local procedure OnBeforeSetDefaultDepreciationBook(FixedAsset: Record "fixed Asset"; FADepreciationBook: Record "FA Depreciation Book"; var Simple: Boolean; var FADepreciationBookOld: Record "FA Depreciation Book"; var ShowAddMoreDeprBooksLbl: Boolean; var AllowEditDepBookCode: Boolean; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494084

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14714.
