### ISSUE TITLE
Codeunit 13 - Gen. Jnl.-Post Batch - OnAfterProcessLines event

### ISSUE THREAD

**Issue by rgrygoryshchak** [microsoft/ALAppExtensions#2547]
Please add new event **OnAfterProcessLines** to Codeunit 13 (Gen. Jnl.-Post Batch):

`LOCAL [IntegrationEvent] OnAfterProcessLines(VAR GenJnlPostLine : Codeunit "Gen. Jnl.-Post Line")`

Usage:

**LOCAL ProcessLines(VAR GenJnlLine : Record "Gen. Journal Line")**
```
OnBeforeProcessLines(GenJnlLine,PreviewMode,SuppressCommit);

WITH GenJnlLine DO BEGIN
  
   ...

  // Post reversing lines
  PostReversingLines(TempGenJnlLine4);

  ///New Code
  OnAfterProcessLines(GenJnlPostLine);

  // Copy register no. and current journal batch name to general journal
  IF NOT GLReg.FINDLAST OR (GLReg."No." <> GLRegNo) THEN
    GLRegNo := 0;

  ...

```

**Comment by AlexanderYakunin** [comment]
We already have more generic events OnProcessLinesOnAfterAssignGLNegNo(GenJnlLine,GLReg,GLRegNo);

**Comment by rgrygoryshchak** [comment]
Ok, but this event doesn't have (VAR GenJnlPostLine : Codeunit "Gen. Jnl.-Post Line") as parameter :-(
   And if you ask why we need this: At the end of each G/L Journal batch, Sales or Purchase document posting we analyse G/L entries created and if necessary post adjusting journal lines. Ideally adjustment G/L entries should belong to the same register and we want to use existing instance of  GenJnlPostLine codeunit.
   Codeunits 80 & 90 have OnRunOnBeforeFinalizePosting event with GenJnlPostLine codeunit exposed that could be used, But codeunit 13 does not have anything similar.
   Thank you.
