### ISSUE TITLE
[Event Request] codeunit 394 "FinChrgMemo-Make" -      procedure "Code"

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25473]
### Describe the request

    procedure "Code"(): Boolean
    var
        CustIsBlocked: Boolean;
        IsHandled: Boolean;
        Result: Boolean;
    begin
        IsHandled := false;
        OnBeforeCode(Cust, CustLedgEntry, FinChrgMemoHeaderReq, FinChrgMemoHeader, IsHandled, Result); //CustPub
        if IsHandled then
            exit(Result);

        with FinChrgMemoHeader do

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCode(Cust: Record Customer; var CustLedgEntry: Record "Cust. Ledger Entry"; FinChrgMemoHeaderReq: Record "Finance Charge Memo Header"; FinChrgMemoHeader: Record "Finance Charge Memo Header"; var IsHandled: Boolean; var Result: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494088

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14714.
