### ISSUE TITLE
[Event Modification] table 81 "Gen. Journal Line" - OnAfterAccountNoOnValidateGetFAAccount

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25482]
### Describe the request

    local procedure GetFAAccount()
    var
        FA: Record "Fixed Asset";
    begin
        FA.Get("Account No.");
        FA.TestField(Blocked, false);
        FA.TestField(Inactive, false);
        FA.TestField("Budgeted Asset", false);
        UpdateDescription(FA.Description);
        GetFADeprBook("Account No.");
        GetFAVATSetup;
        GetFAAddCurrExchRate;

        OnAfterAccountNoOnValidateGetFAAccount(Rec, FA);
        OnAfterAccountNoOnValidateGetFAAccount(Rec, FA, CurrFieldNo); //CustPub
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterAccountNoOnValidateGetFAAccount2(var GenJournalLine: Record "Gen. Journal Line"; var FixedAsset: Record "Fixed Asset"; CurrFieldNo: Integer) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.

Additional parameter CurrFieldNo to already existing publisher OnAfterAccountNoOnValidateGetFAAccount<br /><br />Internal work item: AB#494082

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
