### ISSUE TITLE
[Event Request] table 81 "Gen. Journal Line" -     procedure UpdateLineBalance()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25481]
### Describe the request

    procedure UpdateLineBalance()
    begin
        "Debit Amount" := 0;
        "Credit Amount" := 0;

        if ((Amount > 0) and (not Correction)) or
           ((Amount < 0) and Correction)
        then
            "Debit Amount" := Amount
        else
            if Amount <> 0 then
                "Credit Amount" := -Amount;

        if "Currency Code" = '' then
            "Amount (LCY)" := Amount;
        case true of
            ("Account No." <> '') and ("Bal. Account No." <> ''):
                "Balance (LCY)" := 0;
            "Bal. Account No." <> '':
                "Balance (LCY)" := -"Amount (LCY)";
            else
                "Balance (LCY)" := "Amount (LCY)";
        end;

        OnUpdateLineBalanceOnAfterAssignBalanceLCY("Balance (LCY)");

        Clear(GenJnlAlloc);
        GenJnlAlloc.UpdateAllocations(Rec);

        OnAfterUpdateAllocations(Rec); //CustPub
        UpdateSalesPurchLCY;

        if ("Deferral Code" <> '') and (Amount <> xRec.Amount) and ((Amount <> 0) and (xRec.Amount <> 0)) then
            Validate("Deferral Code");
    end;

    [IntegrationEvent(false, false)]
    procedure OnAfterUpdateAllocations(var GenJournalLine: Record "Gen. Journal Line") //CustPub
    Begin
    End;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494091

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
