### ISSUE TITLE
[Event Request] codeunit 393 "Reminder-Issue" - procedure DeleteHeader

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25489]
### Describe the request

    procedure DeleteHeader(ReminderHeader: Record "Reminder Header"; var IssuedReminderHeader: Record "Issued Reminder Header")
    var
        IsHandled: Boolean;
    begin
        with ReminderHeader do begin
            OnBeforeDeleteHeader(ReminderHeader, IssuedReminderHeader, IsHandled); //CustPub
            if IsHandled then
                exit;
            TestDeleteHeader(ReminderHeader, IssuedReminderHeader);
            if IssuedReminderHeader."No." <> '' then begin
                IssuedReminderHeader."Shortcut Dimension 1 Code" := '';
                IssuedReminderHeader."Shortcut Dimension 2 Code" := '';
                IssuedReminderHeader.Insert();
                IssuedReminderLine.Init();
                IssuedReminderLine."Reminder No." := "No.";
                IssuedReminderLine."Line No." := 10000;
                IssuedReminderLine.Description := SourceCode.Description;
                OnDeleteHeaderOnBeforeIssuedReminderLineInsert(IssuedReminderLine, IssuedReminderHeader);
                IssuedReminderLine.Insert();
            end;
        end;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDeleteHeader(ReminderHeader: Record "Reminder Header"; var IssuedReminderHeader: Record "Issued Reminder Header"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494090

**Comment by JesperSchulz** [comment]
This issue was resolved on the 15-12-2023.
