### ISSUE TITLE
[Event Request] page 44 "Sales Credit Memo" - trigger OnQueryClosePage

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25487]
### Describe the request

    trigger OnQueryClosePage(CloseAction: Action): Boolean
    var
        IsHandled: boolean;
    begin
        OnBeforeOnQueryClosePage(IsHandled); //CustPub
        if IsHandled then
            exit(true);
        if not DocumentIsPosted then
            exit(ConfirmCloseUnposted);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnQueryClosePage(var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494092

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
