### ISSUE TITLE
[Event Request] table 5065 "Interaction Log Entry" -  procedure ResumeInteraction

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25483]
### Describe the request

    procedure ResumeInteraction()
    var
        TempSegLine: Record "Segment Line" temporary;
    begin
        TempSegLine.CopyFromInteractLogEntry(Rec);
        TempSegLine.Validate(Date, WorkDate);
        OnResumeInteractionAfterValidation(TempSegLine); //CustPub

        if TempSegLine."To-do No." <> '' then
            TempSegLine.SetRange("To-do No.", TempSegLine."To-do No.");

    [IntegrationEvent(false, false)]
    local procedure OnResumeInteractionAfterValidation(var SegmentLine: Record "Segment Line") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494074

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14714.
