### ISSUE TITLE
[Event Request] table 295 "Reminder Header" - procedure InsertLines

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25491]
### Describe the request

    procedure InsertLines()
    var
        ReminderLine2: Record "Reminder Line";
        CurrencyForReminderLevel: Record "Currency for Reminder Level";
        TranslationHelper: Codeunit "Translation Helper";
        AdditionalFee: Decimal;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeInsertLines(Rec, IsHandled); //CustPub
        if IsHandled then
            exit;

        CurrencyForReminderLevel.Init();

    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertLines(var ReminderHeader: Record "Reminder Header"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494083

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14714.
