### ISSUE TITLE
[Event Request] codeunit 73 "Purch.-Explode BOM" - procedure ExplodeBOMCompLines

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25493]
### Describe the request

    local procedure ExplodeBOMCompLines(PurchLine: Record "Purchase Line")
    var
        PreviousPurchLine: Record "Purchase Line";
        Resource: Record Resource;
        InsertLinesBetween: Boolean;
        SkipComponent: Boolean;
    begin
        with PurchLine do begin
            ToPurchLine.Reset();
            ToPurchLine.SetRange("Document Type", "Document Type");
            ToPurchLine.SetRange("Document No.", "Document No.");
            ToPurchLine := PurchLine;
            NextLineNo := "Line No.";
            InsertLinesBetween := false;
            if ToPurchLine.Find('>') then
                if ToPurchLine."Attached to Line No." = "Line No." then begin
                    ToPurchLine.SetRange("Attached to Line No.", "Line No.");
                    ToPurchLine.FindLast();
                    ToPurchLine.SetRange("Attached to Line No.");
                    NextLineNo := ToPurchLine."Line No.";
                    InsertLinesBetween := ToPurchLine.Find('>');
                end else
                    InsertLinesBetween := true;
            if InsertLinesBetween then
                LineSpacing := (ToPurchLine."Line No." - NextLineNo) div (1 + NoOfBOMComp)
            else
                LineSpacing := 10000;
            if LineSpacing = 0 then
                Error(Text003);

            FromBOMComp.Find('-');
            OnExplodeBOMCompLinesOnBeforeLoopFromBOMComp(PurchLine, NextLineNo); //CustPub
            repeat

    [IntegrationEvent(false, false)]
    local procedure OnExplodeBOMCompLinesOnBeforeLoopFromBOMComp(PurchLine: Record "Purchase Line"; var NextLineNo: Integer) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494093

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14714.
