### ISSUE TITLE
[Event Request] table 39 "Purchase Line" - procedure CopyFromItem

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25495]
### Describe the request

    local procedure CopyFromItem()
    var
        Item: Record Item;
        PrepaymentMgt: Codeunit "Prepayment Mgt.";
        IsHandled: Boolean;
    begin
        GetItem(Item);
        GetGLSetup();
        OnBeforeCopyFromItem(Rec, Item);
        Item.TestField(Blocked, false);
        Item.TestField("Gen. Prod. Posting Group");
        if Item."Purchasing Blocked" then
            if IsCreditDocType() then
                SendBlockedItemNotification()
            else
                Error(PurchasingBlockedErr, Item."No.");
        if Item.Type = Item.Type::Inventory then begin
            Item.TestField("Inventory Posting Group");
            "Posting Group" := Item."Inventory Posting Group";
        end;

        OnCopyFromItemOnAfterCheck(Rec, Item, CurrFieldNo);

        Description := Item.Description;
        "Description 2" := Item."Description 2";
        UpdateUnitPriceLCYFromItem(Item);
        "Units per Parcel" := Item."Units per Parcel";
        "Indirect Cost %" := Item."Indirect Cost %";
        "Overhead Rate" := Item."Overhead Rate";
        "Allow Invoice Disc." := Item."Allow Invoice Disc.";
        "Gen. Prod. Posting Group" := Item."Gen. Prod. Posting Group";
        "VAT Prod. Posting Group" := Item."VAT Prod. Posting Group";
        "Tax Group Code" := Item."Tax Group Code";
        Nonstock := Item."Created From Nonstock Item";
        "Item Category Code" := Item."Item Category Code";
        "Allow Item Charge Assignment" := true;
        PrepaymentMgt.SetPurchPrepaymentPct(Rec, PurchHeader."Posting Date");
        if IsInventoriableItem then
            PostingSetupMgt.CheckInvtPostingSetupInventoryAccount("Location Code", "Posting Group");

        if Item."Price Includes VAT" then begin
            if not VATPostingSetup.Get(Item."VAT Bus. Posting Gr. (Price)", Item."VAT Prod. Posting Group") then
                VATPostingSetup.Init();
            case VATPostingSetup."VAT Calculation Type" of
                VATPostingSetup."VAT Calculation Type"::"Reverse Charge VAT":
                    VATPostingSetup."VAT %" := 0;
                VATPostingSetup."VAT Calculation Type"::"Sales Tax":
                    Error(
                      Text002,
                      VATPostingSetup.FieldCaption("VAT Calculation Type"),
                      VATPostingSetup."VAT Calculation Type");
            end;
            IsHandled := false;
            OnCopyFromItemOnBeforeAssignUnitPriceLCY(Rec, GLSetup, VATPostingSetup, IsHandled);
            if not IsHandled then
                "Unit Price (LCY)" :=
                  Round("Unit Price (LCY)" / (1 + VATPostingSetup."VAT %" / 100),
                    GLSetup."Unit-Amount Rounding Precision");
        end;

        if PurchHeader."Language Code" <> '' then
            GetItemTranslation;

        OnCopyFromItem(Rec, Item); //CustPub

    [IntegrationEvent(false, false)]
    local procedure OnCopyFromItem(var Rec: Record "Purchase Line"; var Item: Record Item) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494095

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14858.
