### ISSUE TITLE
[Event Request] codeunit 73 "Purch.-Explode BOM" - trigger OnRun()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25492]
### Describe the request

    trigger OnRun()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeOnRun(Rec, IsHandled);
        if IsHandled then
            exit;

        TestField(Type, Type::Item);
        TestField("Quantity Received", 0);
        TestField("Return Qty. Shipped", 0);

        CalcFields("Reserved Qty. (Base)");
        TestField("Reserved Qty. (Base)", 0);
        if "Sales Order No." <> '' then
            Error(
              Text000,
              "Sales Order No.");

        PurchHeader.Get("Document Type", "Document No.");
        PurchHeader.TestField(Status, PurchHeader.Status::Open);
        FromBOMComp.SetRange("Parent Item No.", "No.");
        NoOfBOMComp := FromBOMComp.Count();
        OnRunOnAfterSetNoOfBOMComp(FromBOMComp, Rec, NoOfBOMComp); //CustPub
        if NoOfBOMComp = 0 then
            Error(
              Text001,
              "No.");

    [IntegrationEvent(false, false)]
    local procedure OnRunOnAfterSetNoOfBOMComp(FromBOMComp: Record "BOM Component"; RecPurchLine: Record "Purchase Line"; var NoOfBOMComp: Integer) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494087

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14714.
