### ISSUE TITLE
Request to add event OnAfterCaption to page 5096 "Task List"

### ISSUE THREAD

**Issue by DonHendriksen** [microsoft/ALAppExtensions#25499]
### Describe the request

The caption of page 5096 "Task List" is composed via procedure GetCaption. We are able to influence the caption via the already existing OnBeforeCaption event. But in case our own code and the standard code does not return a caption we want to be able to influence the caption afterwords.
For this reason we request to add a new event OnAfterCaption to page 5096 "Task List" so we can influence the text 'untitled'.

    [IntegrationEvent(false, false)]
    local procedure OnAfterCaption(var ToDo: Record "To-do"; var CaptionStr: Text; var Handled: Boolean)
    begin
    end;

### Additional context

The ability to influence the caption also when the OnBeforeCaption event and the standard code are triggered.<br /><br />Internal work item: AB#494156

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
