### ISSUE TITLE
SendToAzureML procedure cannot be used for 'Extension' development

### ISSUE THREAD

**Issue by ABaludin** [Microsoft/ALAppExtensions#255]
Hi!
In NAV 2018 and BC Spring release SendToAzureML method in codeunit "Azure ML Connector" had "External" visibility. But in Fall release it became Internal. And now I can use it in AL Development only with target = internal. 
Is it a bug or now we need to use some other method?

Checked on sandbox and on-premise versions - both Internal.

**Comment by JesperSchulz** [comment]
SendToAzureML has been exposed again in the upcoming November release. Expect the release shortly!
