### ISSUE TITLE
"Persistent Blob" extensibility issues

### ISSUE THREAD

**Issue by gntpet** [microsoft/ALAppExtensions#25505]
### Describe the request

I would like to delete all records from Persistent Blob table. 

Currently this is not possible, since Persistent Blob interface does not offer **Deletall** function. It does offer Delete function, but for that you must know the KeyId. In my scenario, keyid is unknown (dealing with old legacy data), thus makes it impossible to delete the records from this table.

That's just another limitation of PersistentBlob API i have reported. In this request, I reported it's limitation with changecompany #17349 

It's a bit hard to understand, why there was a need to introduce PersistenbBlob api at all, and hide old good interface (record interfaced) that everyone was using? What benefits does it bring? 

### Additional context

All details provided in decription
Internal work item: [AB#500376](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500376)

**Comment by Groenbech96** [comment]
Will close as we have no effort planned to do this. 
Please feel free to create a PR that implements the idea, this way it could be uptaken.
