### ISSUE TITLE
Codeunit 12 - Gen. Jnl.-Post Line - new OnBeforeFinishPosting event

### ISSUE THREAD

**Issue by rgrygoryshchak** [microsoft/ALAppExtensions#2550]
Please add new event **OnBeforeFinishPosting** to Codeunit 12 (Gen. Jnl.-Post Line):

`LOCAL [IntegrationEvent] OnBeforeFinishPosting(VAR GenJnlLine : Record "Gen. Journal Line")`

**IncludeSender & GlobalVarAccess property set to Yes**

Usage:

**[External] FinishPosting(VAR GenJnlLine : Record "Gen. Journal Line") IsTransactionConsistent : Boolean**
```
///New Code
OnBeforeFinishPosting(GenJnlLine);

IsTransactionConsistent :=
  (BalanceCheckAmount = 0) AND (BalanceCheckAmount2 = 0) AND
  (BalanceCheckAddCurrAmount = 0) AND (BalanceCheckAddCurrAmount2 = 0);

OnAfterSettingIsTransactionConsistent(GenJnlLine,IsTransactionConsistent);
```

Signature of FinishPosting function should be changed from
_[External] FinishPosting(GenJnlLine : Record "Gen. Journal Line") IsTransactionConsistent : Boolean_
to
_[External] FinishPosting(**VAR** GenJnlLine : Record "Gen. Journal Line") IsTransactionConsistent : Boolean_

If change of FinishPosting signature is not possible OnBeforeFinishPosting should be called just before  FinishPosting.

Regards, Roman.

**Comment by AlexanderYakunin** [comment]
We do not provide GlobalVarAccess anymore, please specify explicitly what you need.

**Comment by AlexanderYakunin** [comment]
What country version are you working with?

**Comment by rgrygoryshchak** [comment]
Country - UK.

   GlobalVarAccess is not that important. **IncludeSender** is important.

   In this particular case after each Cust/Vend ledger application or unapplication based on application data we could generate additional G/L Entries.
   
   The idea is:

   Before application starts we record last Detailed Cust/Vend Ledger Entry No. and save it somewhere.

   In OnBeforeFinishPosting event handler we analyse new Detailed Cust/Vend Ledger Entries and based on application data create new G/L Entries by Sender.InitGLEntry and Sender.InsertGLEntry

Regards, Roman.

**Comment by rgrygoryshchak** [comment]
>> please specify _explicitly what you need._

   I'm sorry, but I think that many new events introduced on user's request are too specific and not generic enough! There are many potentials events that could be used, but they do not pass required data to event handler.

   I think that **IncludeSender** should be turned on by default allowing event handler to access sender's functionality and custom variables in future.

   I see OnBeforeFinishPosting as generic place to create additional G/L Entries after journal line posting is completed.

Regards, Roman.
