### ISSUE TITLE
[Event Request] codeunit 5895 "Inventory Adjustment" implements "Inventory Adjustment" -  local procedure CalcAvgCost

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25508]
### Describe the request

    local procedure CalcAvgCost(OutbndValueEntry: Record "Value Entry"; var CostElementBuf: Record "Cost Element Buffer"; var ExcludedValueEntry: Record "Value Entry"): Boolean
    var
        ValueEntry: Record "Value Entry";
        RoundingError: Decimal;
        RoundingErrorACY: Decimal;
    begin
        with ValueEntry do begin
            if OutbndValueEntry."Entry No." >= AvgCostBuf."Last Valid Value Entry No" then begin
                SumCostsTillValuationDate(OutbndValueEntry);
                TempInvtAdjmtBuf.SumCostsTillValuationDate(OutbndValueEntry);
                CostElementBuf."Remaining Quantity" := "Item Ledger Entry Quantity";
                CostElementBuf."Actual Cost" :=
                  "Cost Amount (Actual)" + "Cost Amount (Expected)" +
                  TempInvtAdjmtBuf."Cost Amount (Actual)" + TempInvtAdjmtBuf."Cost Amount (Expected)";
                CostElementBuf."Actual Cost (ACY)" :=
                  "Cost Amount (Actual) (ACY)" + "Cost Amount (Expected) (ACY)" +
                  TempInvtAdjmtBuf."Cost Amount (Actual) (ACY)" + TempInvtAdjmtBuf."Cost Amount (Expected) (ACY)";

                RoundingError := 0;
                RoundingErrorACY := 0;

                OnCalcAvgCostOnAfterAssignRoundingError(RoundingError, RoundingErrorACY, CostElementBuf); //CustPub

                ExcludeAvgCostOnValuationDate(CostElementBuf, OutbndValueEntry, ExcludedValueEntry);
                AvgCostBuf.UpdateAvgCostBuffer(
                  CostElementBuf, GetLastValidValueEntry(OutbndValueEntry."Entry No."));
            end else
                CostElementBuf.UpdateCostElementBuffer(AvgCostBuf);

    [IntegrationEvent(false, false)]
    local procedure OnCalcAvgCostOnAfterAssignRoundingError(var RoundingError: Decimal; var RoundingErrorACY: Decimal; CostElementBuf: Record "Cost Element Buffer") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494188

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14858.
