### ISSUE TITLE
[Event Request] codeunit 5895 "Inventory Adjustment" implements "Inventory Adjustment" - procedure AdjustOutbndAvgEntry

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25507]
### Describe the request

  local procedure AdjustOutbndAvgEntry(var OutbndValueEntry: Record "Value Entry"; var ExcludedValueEntry: Record "Value Entry")
    var
        OutbndItemLedgEntry: Record "Item Ledger Entry";
        OldCostElementBuf: Record "Cost Element Buffer" temporary;
        NewCostElementBuf: Record "Cost Element Buffer" temporary;
        EntryAdjusted: Boolean;
    begin
        OutbndItemLedgEntry.Get(OutbndValueEntry."Item Ledger Entry No.");
        if OutbndItemLedgEntry."Applies-to Entry" <> 0 then
            exit;
        if ExpCostIsCompletelyInvoiced(OutbndItemLedgEntry, OutbndValueEntry) then
            exit;

        with NewCostElementBuf do begin
            UpDateWindow(
              WindowAdjmtLevel, WindowItem, WindowAdjust, WindowFWLevel, OutbndValueEntry."Item Ledger Entry No.", WindowOutbndEntry);

            EntryAdjusted := OutbndItemLedgEntry.SetAvgTransCompletelyInvoiced;

            if CalcAvgCost(OutbndValueEntry, NewCostElementBuf, ExcludedValueEntry) then begin
                CalcOutbndDocOldCost(OldCostElementBuf, OutbndValueEntry, false);
                if OutbndValueEntry."Expected Cost" then begin
                    "Actual Cost" := "Actual Cost" - OldCostElementBuf."Expected Cost";
                    "Actual Cost (ACY)" := "Actual Cost (ACY)" - OldCostElementBuf."Expected Cost (ACY)";
                end else begin
                    "Actual Cost" := "Actual Cost" - OldCostElementBuf."Actual Cost";
                    "Actual Cost (ACY)" := "Actual Cost (ACY)" - OldCostElementBuf."Actual Cost (ACY)";
                    OnAdjustOutbndAvgEntryOnNewCostElementBuf(OutbndValueEntry); //CustPub
                end;
                if UpdateAdjmtBuf(
                     OutbndValueEntry, "Actual Cost", "Actual Cost (ACY)", OutbndItemLedgEntry."Posting Date", OutbndValueEntry."Entry Type")
                then
                    EntryAdjusted := true;
            end;

    [IntegrationEvent(false, false)]
    local procedure OnAdjustOutbndAvgEntryOnNewCostElementBuf(var OutbndValueEntry: Record "Value Entry") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494189

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14858.
