### ISSUE TITLE
[Request for External] report 5753 "Get Source Documents" - CreateActivityFromSalesLine2ShptLine

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#25500]
### Describe the request

Can you change procedure CreateActivityFromSalesLine2ShptLine in report 5753 "Get Source Documents" to global?
I know that I can WhseActivityCreate.FromSalesLine2ShptLine directly, but as there is an event in the beginning of the procedure, I want to call the function to future poof my solution.

### Additional context

Create warehouse shipment lines from additional sales lines.<br /><br />Internal work item: AB#494157

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
