### ISSUE TITLE
[Event Parameter Request] codeunit 99000773 "Calculate Prod. Order" - OnCalculateRoutingOnBeforeUpdateProdOrderRoutingLineDates

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25503]
### Describe the request

    local procedure CalculateRouting(Direction: Option Forward,Backward; LetDueDateDecrease: Boolean)
    var
        ....
        IsHandled: Boolean;
    begin
        ....
        if not ProdOrderRoutingLine.FindFirst() then begin
            OnCalculateRoutingOnBeforeSetLeadTime(ProdOrderLine);
            CalculateLeadTime(ProdOrderLine, Direction, LetDueDateDecrease);
            exit;
        end;

        IsHandled := false;
        OnCalculateRoutingOnBeforeUpdateProdOrderRoutingLineDates(ProdOrderRoutingLine, ProdOrderLine, IsHandled);
        if IsHandled then
            exit;

        if Direction = Direction::Forward then begin
            ProdOrderRoutingLine."Starting Date" := ProdOrderLine."Starting Date";
            ProdOrderRoutingLine."Starting Time" := ProdOrderLine."Starting Time";
        end else begin
            ProdOrderRoutingLine."Ending Date" := ProdOrderLine."Ending Date";
            ProdOrderRoutingLine."Ending Time" := ProdOrderLine."Ending Time";
        end;
        ....
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCalculateRoutingOnBeforeUpdateProdOrderRoutingLineDates(var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; var ProdOrderLine: Record "Prod. Order Line"; var IsHandled: Boolean)
    begin
    end;

### Additional context

....<br /><br />Internal work item: AB#494187

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14858.
