### ISSUE TITLE
[Event Parameter Request] codeunit 99000773 "Calculate Prod. Order" - OnBeforeTransferBOMComponent

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25502]
### Describe the request

Add variable Level: Integer to OnBeforeTransferBOMComponent

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferBOMComponent(ProdOrder: Record "Production Order"; ProdOrderLine: Record "Prod. Order Line"; var ProdBOMLine: Record "Production BOM Line"; var ErrorOccured: Boolean; var IsHandled: Boolean; Level: Integer)
    begin
    end;

### Additional context

....<br /><br />Internal work item: AB#494186

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14858.
