### ISSUE TITLE
[Procedure Request] Table 64 "Merge Duplicates Buffer" - procedure MergeRecords(DuplicateRecID: RecordID; CurrentRecID: RecordID; IdFieldId: Integer)

### ISSUE THREAD

**Issue by ArnisVe** [microsoft/ALAppExtensions#25504]
### Describe the request

In Table 64 "Merge Duplicates Buffer" - local procedure MergeRecords needs to be made to a global function so that we can do a merge of our custom entities.

```
procedure MergeRecords(DuplicateRecID: RecordID; CurrentRecID: RecordID; IdFieldId: Integer)
var
    RecordRef: array[2] of RecordRef;
    KeyValue: array[16] of Variant;
    KeyFieldCount: Integer;
    NewSystemID: Guid;
    OldSystemID: Guid;
begin
    RecordRef[2].Get(CurrentRecID);
    RecordRef[1].Get(DuplicateRecID);
    NewSystemID := RecordRef[2].Field(RecordRef[2].SystemIdNo).Value;
    OldSystemID := RecordRef[1].Field(RecordRef[1].SystemIdNo).Value;

    OverrideSelectedFields(RecordRef[2], RecordRef[1], false);

    RecordRef[2].Delete();
    KeyFieldCount := GetKeyValues(RecordRef[2], KeyValue);
    if not RenameRecord(RecordRef[1], KeyFieldCount, KeyValue) then
        Error(RenameErr, RecordRef[1].RecordId, RecordRef[2].RecordId);
    RestoreSystemID(RecordRef[1], NewSystemID);

    UpdateIDs(
      RecordRef[1].Number, IdFieldId, OldSystemID, NewSystemID);
end;
```

### Additional context

We have our own custom table and would like to use the existing functionality for merging two records.<br /><br />Internal work item: AB#494191

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15328.
