### ISSUE TITLE
[Event Request] codeunit 99000774 "Calculate Routing Line" - OnCreateLoadForwardOnAfterScheduleProdOrderRoutingLineManually

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25501]
### Describe the request

    local procedure CreateLoadForward(TimeType: Enum "Routing Time Type"; Write: Boolean; LoadFactor: Decimal)
    ....
                ProdStartingTime := EndingTime;
                ProdStartingDate := CalendarEntry.Date;
                ProdOrderRoutingLine."Ending Time" := EndingTime;
                ProdOrderRoutingLine."Ending Date" := CalendarEntry.Date;

                if ProdOrderRoutingLine."Schedule Manually" then begin
                    if TimeType = TimeType::"Setup Time" then
                        RunStartingDateTime := CreateDateTime(ProdStartingDate, ProdStartingTime);
                    if (RemainNeedQtyBase < 0) or (Round(RemainNeedQtyBase, CurrentRounding) = 0) then
                        RemainNeedQtyBase := 0;
                end;
                OnCreateLoadForwardOnAfterScheduleProdOrderRoutingLineManually(ProdOrderRoutingLine, TimeType, RunStartingDateTime, ProdStartingDate, ProdStartingTime, RemainNeedQtyBase);
                ....
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCreateLoadForwardOnAfterScheduleProdOrderRoutingLineManually(var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; TimeType: Enum "Routing Time Type"; var RunStartingDateTime: DateTime; var ProdStartingDate: Date; var ProdStartingTime: Time; var RemainNeedQtyBase: Decimal)
    begin
    end;

### Additional context

We are in dire need of this event<br /><br />Internal work item: AB#494158

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14858.
