### ISSUE TITLE
[Event Modification] codeunit 426 "Payment Tolerance Management" - OnBeforeCheckPmtDiscTolCust

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25515]
### Describe the request

    local procedure CheckPmtDiscTolCust(NewPostingdate: Date; NewDocType: Enum "Gen. Journal Document Type"; NewAmount: Decimal; OldCustLedgEntry: Record "Cust. Ledger Entry"; ApplnRoundingPrecision: Decimal; MaxPmtTolAmount: Decimal) Result: Boolean
    var
        ToleranceAmount: Decimal;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckPmtDiscTolCust(NewPostingdate, NewDocType, NewAmount, OldCustLedgEntry, ApplnRoundingPrecision, MaxPmtTolAmount, IsHandled, Result);
        OnBeforeCheckPmtDiscTolCust(NewPostingdate, NewDocType, NewAmount, OldCustLedgEntry, ApplnRoundingPrecision, MaxPmtTolAmount, IsHandled, Result, CalledFromBankPayment); //CustPub
        if IsHandled then
            exit;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckPmtDiscTolCust(NewPostingdate: Date; NewDocType: Enum "Gen. Journal Document Type"; NewAmount: Decimal; OldCustLedgEntry: Record "Cust. Ledger Entry"; ApplnRoundingPrecision: Decimal; MaxPmtTolAmount: Decimal; var IsHandled: Boolean; var Result: Boolean; CalledFromBankPayment: Boolean)//CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.

Additional parameter CalledFromBankPayment to already existing publisher OnBeforeCheckPmtDiscTolCust<br /><br />Internal work item: AB#494192

**Comment by AleksandricMarko** [comment]
Hello @StefanSosic 
variable CalledFromBankPayment is not available in the codeunit.
Please check it.

**Comment by StefanSosic** [comment]
Hi @AleksandricMarko 

Sorry for the confusion, its part of custom code.
This request isn't valid anymore, closing it now.
