### ISSUE TITLE
[Event Request] codeunit 426 "Payment Tolerance Management" - procedure PmtTolCustLedgEntry

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25512]
### Describe the request

    local procedure PmtTolCustLedgEntry(var NewCustLedgEntry: Record "Cust. Ledger Entry"; AccountNo: Code[20]; PostingDate: Date; DocNo: Code[20]; AppliesToID: Code[50]; AppliesToDocNo: Code[20]; CurrencyCode: Code[10]): Boolean
    var
        GLSetup: Record "General Ledger Setup";
        AppliedAmount: Decimal;
        OriginalAppliedAmount: Decimal;
        ApplyingAmount: Decimal;
        AmounttoApply: Decimal;
        PmtDiscAmount: Decimal;
        MaxPmtTolAmount: Decimal;
        ApplnRoundingPrecision: Decimal;
        IsHandled: Boolean;
    begin
        GLSetup.Get();
        CalcCustApplnAmount(
          NewCustLedgEntry, GLSetup, AppliedAmount, ApplyingAmount, AmounttoApply, PmtDiscAmount,
          MaxPmtTolAmount, AppliesToID, ApplnRoundingPrecision);

        OriginalAppliedAmount := AppliedAmount;

        IsHandled := false;
        OnPmtTolCustLedgEntryOnBeforeManagePaymentDiscToleranceWarningCustomer(CalledFromBankPayment, IsHandled); //CustPub
        if GLSetup."Pmt. Disc. Tolerance Warning" or IsHandled then
            if not ManagePaymentDiscToleranceWarningCustomer(NewCustLedgEntry, AppliesToID, AppliedAmount, AmounttoApply, AppliesToDocNo) then
                exit(false);

    [IntegrationEvent(false, false)]
    local procedure OnPmtTolCustLedgEntryOnBeforeManagePaymentDiscToleranceWarningCustomer(CalledFromBankPayment: Boolean; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494193

**Comment by AleksandricMarko** [comment]
Hello @StefanSosic
variable CalledFromBankPayment is not available in the codeunit.
Please check and review it.

**Comment by StefanSosic** [comment]
Hi @AleksandricMarko 

Sorry for the confusion, its part of custom code.
This request isn't valid anymore, closing it now.
