### ISSUE TITLE
[Event Request] codeunit 426 "Payment Tolerance Management" - procedure PmtTolGenJnl

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25511]
### Describe the request

    procedure PmtTolGenJnl(var NewGenJnlLine: Record "Gen. Journal Line") Result: Boolean
    var
        GenJnlLine: Record "Gen. Journal Line" temporary;
    begin
        GenJnlLine := NewGenJnlLine;

        if GenJnlLine."Check Printed" then
            exit(true);

        if GenJnlLine."Financial Void" then
            exit(true);

        if (GenJnlLine."Applies-to Doc. No." = '') and (GenJnlLine."Applies-to ID" = '') then
            exit(true);

        OnBeforePmtTolGenJnl(CalledFromBankPayment, DiffAmountTo); //CustPub

        case true of

    [IntegrationEvent(false, false)]
    local procedure OnBeforePmtTolGenJnl(var PCalledFromBankPayment: Boolean; var PDiffAmountTo: Decimal) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494194

**Comment by AleksandricMarko** [comment]
Hello @StefanSosic
variable CalledFromBankPayment is not available in the codeunit.
Please check and review it.

**Comment by StefanSosic** [comment]
Hi @AleksandricMarko 

Sorry for the confusion, its part of custom code.
This request isn't valid anymore, closing it now.
