### ISSUE TITLE
[Event Request] codeunit 5633 "FA Jnl.-Post Batch" - OnCodeOnAfterPostLines()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25518]
### Describe the request

New publisher call after posting lines:

// Post lines
PostLines;
OnCodeOnAfterPostLines(FAJnlLine); //CustPub

[IntegrationEvent(false, false)]
local procedure OnCodeOnAfterPostLines(var FAJnlLine: Record "FA Journal Line") //CustPub
begin
end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494253

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14915.
