### ISSUE TITLE
[Event Request] page 542 "Default Dimensions-Multiple" - OnBeforeSetCommonDefaultCopyFields()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25517]
### Describe the request

In local procedure SetCommonDefaultDim() add additional call to OnBeforeSetCommonDefaultCopyFields(Rec, TempDefaultDim2):

                        end else begin
                            DefaultDim.Init();
                            DefaultDim."Table ID" := TempDefaultDim3."Table ID";
                            DefaultDim."No." := TempDefaultDim3."No.";
                            DefaultDim."Dimension Code" := "Dimension Code";
                            DefaultDim."Dimension Value Code" := "Dimension Value Code";
                            DefaultDim."Value Posting" := "Value Posting";
                            UpdateDimValuePerAccount(DefaultDim);
                            OnBeforeSetCommonDefaultCopyFields(DefaultDim, Rec);
                            DefaultDim.Insert(true);
                        end;
                        OnBeforeSetCommonDefaultCopyFields(Rec, TempDefaultDim2) //CustPub
                    until TempDefaultDim3.Next() = 0;
            until Next() = 0;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494241

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14714.
