### ISSUE TITLE
[Event Request] codeunit 426 "Payment Tolerance Management" - procedure CallPmtTolWarning

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25516]
### Describe the request

    procedure CallPmtTolWarning(PostingDate: Date; No: Code[20]; DocNo: Code[20]; CurrencyCode: Code[10]; var Amount: Decimal; AppliedAmount: Decimal; AccountType: Enum "Payment Tolerance Account Type"): Boolean
    var
        GenJnlPostPreview: Codeunit "Gen. Jnl.-Post Preview";
        PmtTolWarning: Page "Payment Tolerance Warning";
        ActionType: Integer;
        IsHandled: Boolean;
        Result: Boolean;
    begin
        IsHandled := false;
        OnBeforeCallPmtTolWarning(CalledFromBankPayment, Result, IsHandled); //CustPub
        if IsHandled then
            exit(Result);

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCallPmtTolWarning(CalledFromBankPayment: Boolean; var Result: Boolean; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494196

**Comment by AleksandricMarko** [comment]
Hello @StefanSosic
variable CalledFromBankPayment is not available in the codeunit.
Please check and review it.

**Comment by StefanSosic** [comment]
Hi @AleksandricMarko 

Sorry for the confusion, its part of custom code.
This request isn't valid anymore, closing it now.
