### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnCustPostApplyCustLedgEntryOnBeforeRunCheck()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25527]
### Describe the request

            "Applies-to ID" := CustLedgEntryPostApply."Applies-to ID";

            OnCustPostApplyCustLedgEntryOnBeforeRunCheck(GenJnlLine, CustLedgEntryPostApply, CustLedgEntry); //CustPub
            GenJnlCheckLine.RunCheck(GenJnlLine);

    [IntegrationEvent(false, false)]
    local procedure OnCustPostApplyCustLedgEntryOnBeforeRunCheck(var GenJnlLine: Record "Gen. Journal Line"; var CustLedgEntryPostApply: Record "Cust. Ledger Entry"; var CustLedgEntry: Record "Cust. Ledger Entry") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494242

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
