### ISSUE TITLE
[Event Modification] codeunit 12 "Gen. Jnl.-Post Line" - OnCalcPmtDiscOnAfterCalcPmtDisc()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25524]
### Describe the request

            OnCalcPmtDiscOnAfterCalcPmtDisc(DtldCVLedgEntryBuf, OldCVLedgEntryBuf2, PmtDisc, PmtDiscLCY);
            OnCalcPmtDiscOnAfterCalcPmtDisc(DtldCVLedgEntryBuf, OldCVLedgEntryBuf2, PmtDisc, PmtDiscLCY, GenJnlLine); //CustPub

    [IntegrationEvent(false, false)]
    local procedure OnCalcPmtDiscOnAfterCalcPmtDisc(DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; OldCVLedgEntryBuf2: Record "CV Ledger Entry Buffer"; var PmtDisc: Decimal; var PmtDiscLCY: Decimal; var GenJournalLine: Record "Gen. Journal Line") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.

Additional parameter GenJournalLine by refrence<br /><br />Internal work item: AB#494254

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
