### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - multiple publishers

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25528]
### Describe the request

    // Post the application
    CustLedgEntry.CalcFields(
      Amount, "Amount (LCY)", "Remaining Amount", "Remaining Amt. (LCY)",
      "Original Amount", "Original Amt. (LCY)");
    OnCustPostApplyCustLedgEntryOnBeforeCopyFromCustLedgEntry(GenJnlLine, CVLedgEntryBuf, CustLedgEntry);
    CVLedgEntryBuf.CopyFromCustLedgEntry(CustLedgEntry);
    OnCustPostApplyCustLedgEntryOnBeforeApplication(CustLedgEntry); //CustPub
    ApplyCustLedgEntry(CVLedgEntryBuf, TempDtldCVLedgEntryBuf, GenJnlLine, Cust);
    OnCustPostApplyCustLedgEntryOnAfterApplyCustLedgEntry(GenJnlLine, TempDtldCVLedgEntryBuf);
    CustLedgEntry.CopyFromCVLedgEntryBuffer(CVLedgEntryBuf);
    OnCustPostApplyCustLedgEntryOnAfterApplication(CVLedgEntryBuf); //CustPub
    CustLedgEntry.Modify();

    [IntegrationEvent(false, false)]
    local procedure OnCustPostApplyCustLedgEntryOnBeforeApplication(var CustLedgerEntry: Record "Cust. Ledger Entry") //CustPub
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnCustPostApplyCustLedgEntryOnAfterApplication(var CVLedgerEntryBuffer: Record "CV Ledger Entry Buffer") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494255

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
