### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnBeforePostDtldCustLedgEntries()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25529]
### Describe the request

In procedure PostDtldCustLedgEntries        

        if GenJnlLine."Account Type" <> GenJnlLine."Account Type"::Customer then
            exit;

        OnBeforePostDtldCustLedgEntries(GenJnlLine, DtldCVLedgEntryBuf, CustPostingGr, LedgEntryInserted); //CustPub

    [IntegrationEvent(false, false)]
    local procedure OnBeforePostDtldCustLedgEntries(var GenJnlLine: Record "Gen. Journal Line"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; CustPostingGr: Record "Customer Posting Group"; LedgEntryInserted: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494240

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
