### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeCheckGLAccountBlocked()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25522]
### Describe the request

    procedure InitGLEntry(GenJnlLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; GLAccNo: Code[20]; Amount: Decimal; AmountAddCurr: Decimal; UseAmountAddCurr: Boolean; SystemCreatedEntry: Boolean)
    var
        GLAcc: Record "G/L Account";
        IsHandled: Boolean;
    begin
        OnBeforeInitGLEntry(GenJnlLine, GLAccNo, SystemCreatedEntry, Amount, AmountAddCurr);

        if GLAccNo <> '' then begin
            GLAcc.Get(GLAccNo);
            IsHandled := False;
            OnBeforeCheckGLAccountBlocked(GenJnlLine, GLAccNo, IsHandled); //CustPub
            if not IsHandled then
                GLAcc.TestField(Blocked, false);

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckGLAccountBlocked(GenJnlLine: Record "Gen. Journal Line"; GLAccNo: Code[20]; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494244

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
