### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnPostBankAccOnCheckingBankAccPostingGrGLAccountNo()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25521]
### Describe the request

            IsHandled := false;
            OnPostBankAccOnCheckingBankAccPostingGrGLAccountNo(IsHandled); //CustPub
            if not IsHandled then
                BankAccPostingGr.TestField("G/L Account No.");

    [IntegrationEvent(false, false)]
    local procedure OnPostBankAccOnCheckingBankAccPostingGrGLAccountNo(var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494238

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
