### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnPostDtldCustLedgEntriesOnBeforeNextEntryNo()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25531]
### Describe the request

In procedure PostDtldCustLedgEntries add new publisher call with handled pattern:

        if DtldCVLedgEntryBuf.FindSet() then begin
            IsHandled := false;
            OnPostDtldCustLedgEntriesOnBeforeNextEntryNo(GenJnlLine, DtldCVLedgEntryBuf, CustPostingGr, LedgEntryInserted, NextEntryNo, SaveEntryNo, IsHandled); //CustPub
            if not IsHandled then
                if LedgEntryInserted then begin
                    SaveEntryNo := NextEntryNo;
                    IncrNextEntryNo();
                end;

    [IntegrationEvent(false, false)]
    local procedure OnPostDtldCustLedgEntriesOnBeforeNextEntryNo(var GenJnlLine: Record "Gen. Journal Line"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; CustPostingGr: Record "Customer Posting Group"; LedgEntryInserted: Boolean; var NextEntryNo: Integer; var SavedEntryNo: Integer; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494235

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
