### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnPostDtldCustLedgEntriesOnAfterGetLastEntryNo()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25530]
### Describe the request

In procedure PostDtldCustLedgEntries

        if DtldCustLedgEntry.FindLast() then
            DtldCustLedgEntryNoOffset := DtldCustLedgEntry."Entry No."
        else
            DtldCustLedgEntryNoOffset := 0;

        OnPostDtldCustLedgEntriesOnAfterGetLastEntryNo(GenJnlLine, DtldCVLedgEntryBuf, CustPostingGr, LedgEntryInserted, NextEntryNo); //CustPub

    [IntegrationEvent(false, false)]
    local procedure OnPostDtldCustLedgEntriesOnAfterGetLastEntryNo(var GenJnlLine: Record "Gen. Journal Line"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; CustPostingGr: Record "Customer Posting Group"; LedgEntryInserted: Boolean; var NextEntryNo: Integer) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494250

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
