### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnUnapplyCustLedgEntryOnAfterUpdateCustLedgEntry()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25536]
### Describe the request

                UpdateCustLedgEntry(DtldCustLedgEntry2);
                OnUnapplyCustLedgEntryOnAfterUpdateCustLedgEntry(GenJnlLine, DtldCustLedgEntry2, NewDtldCustLedgEntry, CustPostingGr, GLEntry); //CustPub

    [IntegrationEvent(false, false)]
    local procedure OnUnapplyCustLedgEntryOnAfterUpdateCustLedgEntry(var GenJnlLine: Record "Gen. Journal Line"; DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; var NewDtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; CustPostingGr: Record "Customer Posting Group"; var GLEntry: Record "G/L Entry"); //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494220

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
