### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - OnOnUnapplyCustLedgEntryOnBeforeInsertDtldCustLedgEntryUnapply()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25535]
### Describe the request

In procedure UnapplyCustLedgEntry:

        // Look one more time
        OnOnUnapplyCustLedgEntryOnBeforeSecondLook(DtldCustLedgEntry2, NextDtldLedgEntryNo);
        DtldCustLedgEntry2.FindSet();
        TempDimPostingBuffer.DeleteAll();
        repeat
            IsHandled := false;
            OnOnUnapplyCustLedgEntryOnBeforeInsertDtldCustLedgEntryUnapply(DtldCustLedgEntry2, IsHandled); //CustPub
            if not IsHandled then begin

wrap code, with handled pattern, until the end of loop.

    [IntegrationEvent(false, false)]
    local procedure OnOnUnapplyCustLedgEntryOnBeforeInsertDtldCustLedgEntryUnapply(DtldCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494256

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
