### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - 

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25534]
### Describe the request

In procedure UnapplyCustLedgEntry:

        DtldCustLedgEntry2.Reset();
        DtldCustLedgEntry2.FindLast();
        NextDtldLedgEntryNo := DtldCustLedgEntry2."Entry No." + 1;
        OnUnapplyCustLedgEntryOnAfterGetNextDtldLedgEntryNo(GenJnlLine); //CustPub

    [IntegrationEvent(false, false)]
    local procedure OnUnapplyCustLedgEntryOnAfterGetNextDtldLedgEntryNo(var GenJnlLine: Record "Gen. Journal Line") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494246

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
