### ISSUE TITLE
[Event Request] codeunit 17 "Gen. Jnl.-Post Reverse" - OnReverseGLEntryOnBeforeTempCustLedgEntryCheckDimComb()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25539]
### Describe the request

In procedure ReverseGLEntry:

                    case true of
                        TempCustLedgEntry.Get("Entry No."):
                            begin
                                OnReverseGLEntryOnBeforeTempCustLedgEntryCheckDimComb(GLEntry2, TempCustLedgEntry); //CustPub
                                CheckDimComb("Entry No.", "Dimension Set ID",
                                  DATABASE::Customer, TempCustLedgEntry."Customer No.",
                                  DATABASE::"Salesperson/Purchaser", TempCustLedgEntry."Salesperson Code");
                                ReverseCustLedgEntry(
                                  TempCustLedgEntry, GLEntry."Entry No.", GenJnlLine.Correction, GenJnlLine."Source Code",
                                  NextDtldCustLedgEntryEntryNo);

    [IntegrationEvent(false, false)]
    local procedure OnReverseGLEntryOnBeforeTempCustLedgEntryCheckDimComb(var GLEntry: Record "G/L Entry"; var TempCustLedgerEntry: Record "Cust. Ledger Entry" temporary) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494221

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
