### ISSUE TITLE
[Event Request] codeunit 17 "Gen. Jnl.-Post Reverse" - multiple publishers

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25540]
### Describe the request

In procedure ReverseCustLedgEntry:

            if NextDtldCustLedgEntryEntryNo = 0 then begin
                OnResetFilter(Database::"Detailed Cust. Ledg. Entry"); //CustPub
                DtldCustLedgEntry.FindLast();
                NextDtldCustLedgEntryEntryNo := DtldCustLedgEntry."Entry No." + 1;
                OnSetGlobalFilter(Database::"Detailed Cust. Ledg. Entry", false); //CustPub
            end;

    [IntegrationEvent(false, false)]
    local procedure OnResetFilter(TableID: Integer) //CustPub
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnSetGlobalFilter(TableID: Integer; pLogin: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494219

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
