### ISSUE TITLE
[Event Request] codeunit 63 "Sales-Explode BOM" - OnExplodeBOMCompLinesOnBeforeFromBOMCompLoop()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25547]
### Describe the request

In procedure ExplodeBOMCompLines:

            FromBOMComp.Reset();
            FromBOMComp.SetRange("Parent Item No.", "No.");
            OnExplodeBOMCompLinesOnAfterFromBOMCompSetFilters(FromBOMComp, SalesLine, LineSpacing);
            FromBOMComp.FindSet();
            OnExplodeBOMCompLinesOnBeforeFromBOMCompLoop(SalesLine, NextLineNo); //CustPub
            repeat

    [IntegrationEvent(false, false)]
    local procedure OnExplodeBOMCompLinesOnBeforeFromBOMCompLoop(var SalesLine: Record "Sales Line"; var NextLineNo: Integer) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494222

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14915.
