### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" - OnUpdateItemLedgerEntryOnAfterSetAppliedEntryToAdjust()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25549]
### Describe the request

In procedure UpdateItemLedgEntry:

                if (Positive or "Job Purchase") and
                   (Quantity <> "Remaining Quantity") and not "Applied Entry to Adjust" and
                   (Item.Type = Item.Type::Inventory) and
                   (not CalledFromAdjustment or AppliedEntriesToReadjust(ItemLedgEntry))
                then begin
                    "Applied Entry to Adjust" := true;
                    ModifyEntry := true;
                    OnUpdateItemLedgerEntryOnAfterSetAppliedEntryToAdjust(ItemLedgEntry); //CustPub
                end;

    [IntegrationEvent(false, false)]
    local procedure OnUpdateItemLedgerEntryOnAfterSetAppliedEntryToAdjust(ItemLedgerEntry: Record "Item Ledger Entry") //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494228

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
