### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" - OnItemValuePostingOnBeforeInsertValueEntry()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25548]
### Describe the request

In procedure ItemValuePosting:

            IsHandled := false;
            OnItemValuePostingOnBeforeInsertValueEntry(ItemJnlLine, IsHandled); //CustPub
            if not IsHandled then
                InsertValueEntry(GlobalValueEntry, GlobalItemLedgEntry, false);

    [IntegrationEvent(false, false)]
    local procedure OnItemValuePostingOnBeforeInsertValueEntry(ItemJnlLine: Record "Item Journal Line"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494224

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
