### ISSUE TITLE
[Event Request] codeunit 49 GlobalTriggerManagement - OnDatabaseRenameOnBeforeLogRename()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25546]
### Describe the request

In event subscriber procedure OnDatabaseRename:

        IsHandled := false;
        OnDatabaseRenameOnBeforeLogRename(IsHandled); //CustPub
        if not IsHandled then
            // We don't want to allow anyone to disable change log management in normal execution context
            if GetExecutionContext() = ExecutionContext::Normal then
                ChangeLogMgt.LogRename(RecRef, xRecRef);

    [IntegrationEvent(false, false)]
    local procedure OnDatabaseRenameOnBeforeLogRename(var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494218

**Comment by AleksandricMarko** [comment]
Hello @StefanSosic 
We are not allowed to add this event into GlobalTriggerManagement codeunit.
