### ISSUE TITLE
[Event Request] codeunit 17 "Gen. Jnl.-Post Reverse" - OnApplyCustLedgEntryByReversal()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25541]
### Describe the request

In procedure ApplyCustLedgEntryByReversal:

        IsHandled := false;
        OnApplyCustLedgEntryByReversal(CustLedgEntry, CustLedgEntry2, DtldCustLedgEntry2, AppliedEntryNo, NextDtldCustLedgEntryEntryNo, GenJnlPostLine, IsHandled); //CustPub
        if IsHandled then
            exit;

    [IntegrationEvent(false, false)]
    local procedure OnApplyCustLedgEntryByReversal(CustLedgEntry: Record "Cust. Ledger Entry"; CustLedgEntry2: Record "Cust. Ledger Entry"; DtldCustLedgEntry2: Record "Detailed Cust. Ledg. Entry"; AppliedEntryNo: Integer; var NextDtldCustLedgEntryEntryNo: Integer; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494231

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
