### ISSUE TITLE
[Event Request] codeunit 49 GlobalTriggerManagement - OnBeforeGetDatabaseTableTriggerSetup()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25542]
### Describe the request

In event subscriber procedure GetDatabaseTableTriggerSetup:

        IsHandled := false;
        OnBeforeGetDatabaseTableTriggerSetup(TableId, OnDatabaseInsert, OnDatabaseModify, OnDatabaseDelete, OnDatabaseRename, IsHandled); //CustPub
        if not IsHandled then
            // We don't want to allow anyone to disable change log management in normal execution context
            if GetExecutionContext() = ExecutionContext::Normal then
                ChangeLogMgt.GetDatabaseTableTriggerSetup(TableId, OnDatabaseInsert, OnDatabaseModify, OnDatabaseDelete, OnDatabaseRename);

    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetDatabaseTableTriggerSetup(TableId: Integer; var OnDatabaseInsert: Boolean; var OnDatabaseModify: Boolean; var OnDatabaseDelete: Boolean; var OnDatabaseRename: Boolean; var Ishandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494226

**Comment by AleksandricMarko** [comment]
Hello @StefanSosic 
We are not allowed to add this event into GlobalTriggerManagement codeunit.
