### ISSUE TITLE
[Event Request] codeunit 426 "Payment Tolerance Management" - OnDelCustPmtTolAccOnBeforeFirstCommit()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25553]
### Describe the request

In procedure DelCustPmtTolAcc:

                IsHandled := false;
                OnDelCustPmtTolAccOnBeforeFirstCommit(CalledFromBankPayment, IsHandled); //CustPub
                if not IsHandled then
                    if not SuppressCommit then
                        Commit();

    [IntegrationEvent(false, false)]
    local procedure OnDelCustPmtTolAccOnBeforeFirstCommit(CalledFromBankPayment: Boolean; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494243

**Comment by AleksandricMarko** [comment]
Hello @StefanSosic
variable CalledFromBankPayment is not available in the codeunit.
Please check and review it.

**Comment by StefanSosic** [comment]
Hi @AleksandricMarko 

Sorry for the confusion, its part of custom code.
This request isn't valid anymore, closing it now.
