### ISSUE TITLE
[Event Request] codeunit 426 "Payment Tolerance Management" - OnCalcTolCustLedgEntryOnBeforeSetMaxPaymentTolerance()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25555]
### Describe the request

In procedure CalcToCustLedgEntry:

                OnCalcTolCustLedgEntryOnBeforeSetMaxPaymentTolerance(CustLedgEntry, CalledFromBankPayment, DiffAmountTo); //CustPub
                if Abs(CustLedgEntry.Amount) < Abs(CustLedgEntry."Max. Payment Tolerance") then
                    CustLedgEntry."Max. Payment Tolerance" := CustLedgEntry.Amount;

    [IntegrationEvent(false, false)]
    local procedure OnCalcTolCustLedgEntryOnBeforeSetMaxPaymentTolerance(var CustLedgEntry: Record "Cust. Ledger Entry"; CalledFromBankPayment: Boolean; DiffAmountTo: Decimal) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494245

**Comment by AleksandricMarko** [comment]
Hello @StefanSosic
variable CalledFromBankPayment is not available in the codeunit.
Please check and review it.

**Comment by StefanSosic** [comment]
Hi @AleksandricMarko 

Sorry for the confusion, its part of custom code.
This request isn't valid anymore, closing it now.
