### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnRunOnPostPurchLine()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25557]
### Describe the request

        PurchaseLinesProcessed := false;
        if TempPurchLineGlobal.FindSet() then
            repeat
                IsHandled := false;
                OnRunOnPostPurchLine(PurchHeader, TempPurchLineGlobal, IsHandled); //CustPub
                if not IsHandled then begin
                    OnRunOnBeforePostPurchLine(TempPurchLineGlobal, PurchHeader);
                    ErrorMessageMgt.PushContext(ErrorContextElementPostLine, TempPurchLineGlobal.RecordId, 0, PostDocumentLinesMsg);
                    ItemJnlRollRndg := false;
                    LineCount := LineCount + 1;
                    if GuiAllowed and not HideProgressWindow then
                        Window.Update(2, LineCount);

                    PostPurchLine(
                      PurchHeader, TempPurchLineGlobal, TempVATAmountLine, TempVATAmountLineRemainder,
                      TempDropShptPostBuffer, EverythingInvoiced, ICGenJnlLineNo);
                    OnRunOnAfterPostPurchLine(TempPurchLineGlobal);
                end;

    [IntegrationEvent(false, false)]
    local procedure OnRunOnPostPurchLine(var PurchaseHeader: Record "Purchase Header"; var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494232

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14917.
