### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnPostItemJnlLineOnAfterSetCheckApplToItemEntry()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25559]
### Describe the request

Wrap with handled pattern until the end of _with ItemJnlLine do begin_

            IsHandled := false;
            OnPostItemJnlLineOnAfterSetCheckApplToItemEntry(PurchLine, IsHandled); //CustPub
            if not IsHandled then begin
                PostWhseJnlLine := ShouldPostWhseJnlLine(PurchLine, ItemJnlLine, TempWhseJnlLine);

    [IntegrationEvent(false, false)]
    local procedure OnPostItemJnlLineOnAfterSetCheckApplToItemEntry(PurchLine: Record "Purchase Line"; var IsHandled: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494260

**Comment by AleksandricMarko** [comment]
Hello @StefanSosic 
Where is the END of this "if not IsHandled then begin"  ... block?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14917.
