### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" - OnAfterUpdateAvgCostAdjmtEntryPoint()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25550]
### Describe the request

In procedure UpdateAvgCostAdjmtBuffer:

        AvgCostEntryPointHandler.LockBuffer();
        AvgCostEntryPointHandler.UpdateValuationDate(ValueEntry);
        OnAfterUpdateAvgCostAdjmtEntryPoint(OldItemLedgEntry, ValueEntry, ValuationDate); //CustPub

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateAvgCostAdjmtEntryPoint(var pItemLedgerEntry: Record "Item Ledger Entry"; var pValueEntry: Record "Value Entry"; var pValuationDate: Date) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494237

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
