### ISSUE TITLE
[Event Request] codeunit 90 "Purch.-Post" - OnAfterPostPurchLineOnBeforeInsertReceiptLine

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25558]
### Describe the request

            if (Type <> Type::" ") and ("Qty. to Invoice" <> 0) then begin
                AdjustPrepmtAmountLCY(PurchHeader, PurchLine);
#if not CLEAN20
                if UseLegacyInvoicePosting() then begin
                    FillInvoicePostBuffer(PurchHeader, PurchLine, PurchLineACY);
                    InsertTempInvoicePostBufferReverseCharge(TempInvoicePostBuffer);
                end else
#endif
                InvoicePostingInterface.PrepareLine(PurchHeader, PurchLine, PurchLineACY);
            end;

            OnAfterPostPurchLineOnBeforeInsertReceiptLine(PurchHeader, PurchLine, SrcCode, PreviewMode); //CustPub

    [IntegrationEvent(false, false)]
    local procedure OnAfterPostPurchLineOnBeforeInsertReceiptLine(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; SrcCode: Code[10]; PreviewMode: Boolean) //CustPub
    begin
    end;

### Additional context

Publisher request marked with //CustPub tag.<br /><br />Internal work item: AB#494249

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14917.
