### ISSUE TITLE
[Event Request] Page 104 "Account Schedule" - OnBeforeSetupAccSchedLine

### ISSUE THREAD

**Issue by ReneZiel** [microsoft/ALAppExtensions#25563]
### Describe the request

Hello, can you please add a new Event OnBeforeSetupAccSchedLine in Page 104 "Account Schedule"?

```
    procedure SetupAccSchedLine(var AccSchedLine: Record "Acc. Schedule Line")
    var
        IsHandled: Boolean;
    begin
        AccSchedLine := Rec;
        OnBeforeSetupAccSchedLine(Rec, xRec, AccSchedLine, CurrentSchedName, IsHandled);
        If IsHandled then
            exit;
        if Rec."Line No." = 0 then begin
            AccSchedLine := xRec;
            AccSchedLine.SetRange("Schedule Name", CurrentSchedName);
            if AccSchedLine.Next() = 0 then
                AccSchedLine."Line No." := xRec."Line No." + 10000
            else begin
                if AccSchedLine.FindLast() then
                    AccSchedLine."Line No." += 10000;
                AccSchedLine.SetRange("Schedule Name");
            end;
        end;
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetupAccSchedLine(var Rec: Record "Acc. Schedule Line"; var xRec: Record "Acc. Schedule Line"; var AccSchedLine: Record "Acc. Schedule Line"; CurrentSchedName: Code[20]; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

An additional event is required in page 104 ("Account Schedule") to customize the insertion of Acc. Schedule Lines. The event needs to be able to override the default behaviour, using an IsHandled flag.<br /><br />Internal work item: AB#494284

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14858.
