### ISSUE TITLE
[Global Procedure and Parameter Request] codeunit 22 "Item Jnl.-Post Line" - InsertCapValueEntry

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25567]
### Describe the request

To support https://github.com/microsoft/ALAppExtensions/issues/25566 we are in dire need of

changing C22 procedure InsertCapValueEntry from

local procedure InsertCapValueEntry(var CapLedgEntry: Record "Capacity Ledger Entry"; ValueEntryType: Enum "Cost Entry Type"; ValuedQty: Decimal; InvdQty: Decimal; AdjdCost: Decimal)

to

procedure InsertCapValueEntry(var ItemJnlLine: Record "Item Journal Line"; var CapLedgEntry: Record "Capacity Ledger Entry"; ValueEntryType: Enum "Cost Entry Type"; ValuedQty: Decimal; InvdQty: Decimal; AdjdCost: Decimal)

I.e. remove 'local' and add ItemJnlLine as var parameter.
Four calls to InsertCapValueEntry should be modified accordingly in C22.

### Additional context

The original output capacity direct and indirect posting in two extra value entries need to become more to give financial people more insight in manufacturing cost on the Value and G/L entries.
Internal work item: [AB#495834](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/495834)

**Comment by Duizy1971** [comment]
Hello, We are in dire need of this event to get out customer from BC14 to BC23.04 and not much later. Can you please pick up this issue?

**Comment by Duizy1971** [comment]
I guess this won't be available in 23.04. Hopefully this issue can be fulfilled when 23.05 arrives...

**Comment by Duizy1971** [comment]
Our customer just had a meeting with Microsoft BC to get this 5 billion dollar manufacturing company moved to SaaS and we are stil waiting for more then two months on this issue to be fixed. People are getting quite anxious.
Is there a timeline when this request is resolved please...

**Comment by Duizy1971** [comment]
Allas, it is a month later and BC24.00 is almost released and this is particular issue is not resolved in 24.0.16410.17836.
Customer is getting upset with the lack of timely support from Microsoft in these changes. Can you please respond to this issue that is more then three months old.

**Comment by Duizy1971** [comment]
Anybody monitoring this issue? It is taken painstakingly long.

**Comment by ChethanT** [comment]
The fix went into master today and we will be backporting it to 24.x soon. We expect the fix will make it to 24.2.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19575.
