### ISSUE TITLE
[Event signature change] codeunit 22 "Item Jnl.-Post Line" - OnAfterInsertTransferEntry

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25561]
### Describe the request

IncludeSender = true and NewValueEntry + ValueEntryNo

local procedure InsertTransferEntry(var ItemLedgEntry: Record "Item Ledger Entry"; var OldItemLedgEntry: Record "Item Ledger Entry"; AppliedQty: Decimal)
    ....
    OnAfterInsertTransferEntry(ItemJnlLine, NewItemLedgEntry, OldItemLedgEntry, NewValueEntry, ValueEntryNo);
end;

    [IntegrationEvent(true, false)]
    local procedure OnAfterInsertTransferEntry(var ItemJournalLine: Record "Item Journal Line"; NewItemLedgerEntry: Record "Item Ledger Entry"; OldItemLedgerEntry: Record "Item Ledger Entry"; NewValueEntry: Record "Value Entry"; var ValueEntryNo: Integer)
    begin
    end;

### Additional context

Some financial genius thought of a transfer overhead rate on stockkeepingunit. Gotta make more Value and G/L entries because we can't get enough of those, can we.<br /><br />Internal work item: AB#494269

**Comment by Duizy1971** [comment]
PLEASE DO NOT FORGET TO SET THE:

IncludeSender = true !!!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
