### ISSUE TITLE
[Extensibility Request] Codeunit 7321 - Create Inventory Put-away

### ISSUE THREAD

**Issue by Busslar** [microsoft/ALAppExtensions#25564]
### Describe the request

referring to former issue #23361 changes in standard application have been made, so I need a change that my initial inquiry continues working.

the public procedure InsertWhseActivLine in codeunit 7321 - Create Inventory Put-away will be obsolete in the future. Instead, there is a new local one.

In our business solution, we still need a public procedure InsertWhseActivLine.
So it should look like this:

![image](https://github.com/microsoft/ALAppExtensions/assets/9529836/9f48a17a-c71a-4fcc-9807-78c861059305)

### Additional context

in our business solution there is the possibility to define serial no. >1 for an item.

<br /><br />Internal work item: AB#494976

**Comment by Busslar** [comment]
@AleksandricMarko

**Comment by AlexanderYakunin** [comment]
I checked and this procedure is global:

    procedure InsertWhseActivLine(var NewWarehouseActivityLine: Record "Warehouse Activity Line"; PutAwayQty: Decimal)
    var
        UnitOfMeasureManagement: Codeunit "Unit of Measure Management";
        CalculatedPutAway: Decimal;
        IsHandled: Boolean;
    begin
        if CurrLocation."Bin Mandatory" then
            NewWarehouseActivityLine."Action Type" := NewWarehouseActivityLine."Action Type"::Place;
.....

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
