### ISSUE TITLE
[Event Request] Table 23 Vendor - OnBeforeAssertValidCheckDigit13

### ISSUE THREAD

**Issue by vladsandortnp** [microsoft/ALAppExtensions#25569]
### Describe the request

Can you please add a new event OnBeforeAssertValidCheckDigit13 when validating the field value of GLN.
We would like to bypass this check.

The procedure would look like:

`        field(90; GLN; Code[13])
        {
            Caption = 'GLN';
            Numeric = true;

            trigger OnValidate()
            var
                GLNCalculator: Codeunit "GLN Calculator";
                IsHandled: Boolean;
            begin
                if GLN <> '' then
                    OnBeforeAssertValidCheckDigit13(Rec, xRec, IsHandled)
                    if not IsHandled then
                         GLNCalculator.AssertValidCheckDigit13(GLN);
            end;
 `

Event published:

`
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssertValidCheckDigit13(Rec: Record Vendor; xRec: Record:Vendor; var IsHandled: Boolean)
    begin
    end;
`

### Additional context

Can you please add a new event OnBeforeAssertValidCheckDigit13 when validating the field value of GLN.
We would like to bypass this check.<br /><br />Internal work item: AB#494288

**Comment by AleksandricMarko** [comment]
Hello @vladsandortnp 
You already have available publisher "OnBeforeIsValidCheckDigit" as part of codeunit 1607 "GLN Calculator"
