### ISSUE TITLE
[Event Signature Change Request] codeunit 22 "Item Jnl.-Post Line" - OnAfterPostItemJnlLine

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25562]
### Describe the request

Please add
var WhseJnlRegisterLine: Codeunit "Whse. Jnl.-Register Line"
to existing Event procedure OnAfterPostItemJnlLine

OnAfterPostItemJnlLine(ItemJnlLine, GlobalItemLedgEntry, ValueEntryNo, InventoryPostingToGL, CalledFromAdjustment, CalledFromInvtPutawayPick, ItemReg, ItemLedgEntryNo, ItemApplnEntryNo, WhseJnlRegisterLine);

    [IntegrationEvent(true, false)]
    local procedure OnAfterPostItemJnlLine(var ItemJournalLine: Record "Item Journal Line"; ItemLedgerEntry: Record "Item Ledger Entry"; var ValueEntryNo: Integer; var InventoryPostingToGL: Codeunit "Inventory Posting To G/L"; CalledFromAdjustment: Boolean; CalledFromInvtPutawayPick: Boolean; var ItemRegister: Record "Item Register"; var ItemLedgEntryNo: Integer; var ItemApplnEntryNo: Integer; var WhseJnlRegisterLine: Codeunit "Whse. Jnl.-Register Line")
    begin
    end;

### Additional context

On Output posting with a particular "Quality Measure Code" and no "Variant Code" the output ledger entry must be negative adjusted on "Variant Code" = {Empty} and positively adjusted on a Quality Variant Code. That is how the customer wants it.<br /><br />Internal work item: AB#494270

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
