### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" - OnPostOutputOnBeforeInsertCostValueEntries

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25566]
### Describe the request

    local procedure PostOutput()
    ....
            CalcDirAndIndirCostAmts(DirCostAmt, IndirCostAmt, ValuedQty, ItemJnlLine);

            OnPostOutputOnBeforeInsertCostValueEntries(ItemJnlLine, CapLedgEntry, ValuedQty, DirCostAmt, IndirCostAmt);

            InsertCapValueEntry(CapLedgEntry, "Value Entry Type"::"Direct Cost", ValuedQty, ValuedQty, DirCostAmt);
            InsertCapValueEntry(CapLedgEntry, "Value Entry Type"::"Indirect Cost", ValuedQty, 0, IndirCostAmt);
    ....
    end;

    [IntegrationEvent(true, false)]
    local procedure OnPostOutputOnBeforeInsertCostValueEntries(var ItemJournalLine: Record "Item Journal Line"; var CapLedgEntry: Record "Capacity Ledger Entry"; ValuedQty: Decimal; var DirCostAmt: Decimal; var IndirCostAmt: Decimal)
    begin
    end;

### Additional context

The standard total Direct and Indirect Capacity Cost must be posted with different rates to different "Gen. Prod. Posting Group" with multiple value entries.
Just to clarify: Please do not forget the IncludeSender = true property of the new event procedure.<br /><br />Internal work item: AB#494286

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
