### ISSUE TITLE
[Event Modification] codeunit 90 "Purch.-Post" - OnPostItemTrackingForReceiptOnAfterPurchRcptLineSetFilters()

### ISSUE THREAD

**Issue by StefanSosic** [microsoft/ALAppExtensions#25560]
### Describe the request

Include additional parameter

Old value:

OnPostItemTrackingForReceiptOnAfterPurchRcptLineSetFilters(PurchRcptLine, PurchLine);

New value:

OnPostItemTrackingForReceiptOnAfterPurchRcptLineSetFilters(PurchHeader, PurchRcptLine, PurchLine);

### Additional context

Publisher request marked with //CustPub tag.

Additional parameter PurchHeader by value<br /><br />Internal work item: AB#494259

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14917.
