### ISSUE TITLE
[Event Modification] Table 38 Purchase Header - OnBeforeShowPostedDocsToPrintCreatedMsg

### ISSUE THREAD

**Issue by vladsandortnp** [microsoft/ALAppExtensions#25576]
### Describe the request

Can you please add the sender, record or HideValidationDialog  in event OnBeforeShowPostedDocsToPrintCreatedMsg?

I would like to display PostedDocsToPrintCreatedMsg only if HideValidationDialog is set to false.

I would either need access to the Record, HideValidationDialog  or sender in OnBeforeShowPostedDocsToPrintCreatedMsg

How would the event look like:

`

    [IntegrationEvent(true, false)]
    local procedure OnBeforeShowPostedDocsToPrintCreatedMsg(var ShowPostedDocsToPrint: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowPostedDocsToPrintCreatedMsg(Rec: Record "Purchase Header"; var ShowPostedDocsToPrint: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowPostedDocsToPrintCreatedMsg(var ShowPostedDocsToPrint: Boolean; HideValidationDialog:Boolean)
    begin
    end;`

### Additional context

Can you please add the sender, record or HideValidationDialog in event OnBeforeShowPostedDocsToPrintCreatedMsg?

I would like to display PostedDocsToPrintCreatedMsg only if HideValidationDialog is set to false.

I would either need access to the Record, HideValidationDialog or sender in OnBeforeShowPostedDocsToPrintCreatedMsg<br /><br />Internal work item: AB#494526

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14915.
