### ISSUE TITLE
[Event Request] Table 36 Sales Header - OnCopyShipToCustomerAddressFieldsFromCustOnAfterAssignShipToCustomerAddress

### ISSUE THREAD

**Issue by vladsandortnp** [microsoft/ALAppExtensions#25575]
### Describe the request

Can you please add a new event OnCopyShipToCustomerAddressFieldsFromCustOnAfterAssignShipToCustomerAddress in procedure CopyShipToCustomerAddressFieldsFromCust from table 36 Sales Header?

We want to add some additional data to Sales Header after Ship to Addresses have been assinged. This would be similar to event OnCopySellToCustomerAddressFieldsFromCustomerOnAfterAssignSellToCustomerAddress

The event publisher would be:

`
    [IntegrationEvent(false, false)]
    procedure OnCopyShipToCustomerAddressFieldsFromCustOnAfterAssignShipToCustomerAddress(var SalesHeader: Record "Sales Header"; Customer: Record Customer)
    begin
    end;
`

The procedure would be:

`
 procedure CopyShipToCustomerAddressFieldsFromCust(var SellToCustomer: Record Customer)
    var
        CustomerTempl: Record "Customer Templ.";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCopyShipToCustomerAddressFieldsFromCustomer(Rec, SellToCustomer, IsHandled);
        if IsHandled then
            exit;

        "Ship-to Name" := SellToCustomer.Name;
        "Ship-to Name 2" := SellToCustomer."Name 2";
        if SellToCustomerIsReplaced() or
            ShipToAddressEqualsOldSellToAddress() or
            (HasDifferentShipToAddress(SellToCustomer) and SellToCustomer.HasAddress())
        then begin
            "Ship-to Address" := SellToCustomer.Address;
            "Ship-to Address 2" := SellToCustomer."Address 2";
            "Ship-to City" := SellToCustomer.City;
            "Ship-to Post Code" := SellToCustomer."Post Code";
            "Ship-to County" := SellToCustomer.County;
            Validate("Ship-to Country/Region Code", SellToCustomer."Country/Region Code");
            OnCopyShipToCustomerAddressFieldsFromCustOnAfterAssignShipToCustomerAddress 
        end;
.......
......
}
`

### Additional context

Can you please add a new event OnCopyShipToCustomerAddressFieldsFromCustOnAfterAssignShipToCustomerAddress in procedure CopyShipToCustomerAddressFieldsFromCust from table 36 Sales Header?

We want to add some additional data to Sales Header after Ship to Addresses have been assinged. This would be similar to event OnCopySellToCustomerAddressFieldsFromCustomerOnAfterAssignSellToCustomerAddress<br /><br />Internal work item: AB#494521

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14714.
