### ISSUE TITLE
[Event Request] Codeunit 1390 "Document Notifications" - OnCopyBuyFromVendorAddressFieldsFromSalesDocumentOnBeforeModify/ OnCopyPayToVendorAddressFieldsFromSalesDocumentOnBeforeModify

### ISSUE THREAD

**Issue by vladsandortnp** [microsoft/ALAppExtensions#25570]
### Describe the request

Can you please add 2 new event:

- OnCopyBuyFromVendorAddressFieldsFromSalesDocumentOnBeforeModify
- OnCopyPayToVendorAddressFieldsFromSalesDocumentOnBeforeModify 

similar to 

- OnCopyBillToCustomerAddressFieldsFromSalesDocumentOnBeforeModify
- OnCopySellToCustomerAddressFieldsFromSalesDocumentOnBeforeModify.

Want to modify the Purchase Header with additional values after SetAddress. Similar events are available for Sales.

Event publishers:

`
    [IntegrationEvent(false, false)]
    local procedure OnCopyPayToVendorAddressFieldsFromSalesDocumentOnBeforeModify(var Vendor: Record Vendor; PurchaseHeader: Record "PurchaseHeader")
    begin
    end;
`

`
    [IntegrationEvent(false, false)]
    local procedure OnCopyPayToVendorAddressFieldsFromSalesDocumentOnBeforeModify (var Vendor: Record Vendor; PurchaseHeader: Record "PurchaseHeader")
    begin
    end;
`

The procedures will look like:

`
procedure CopyPayToVendorAddressFieldsFromSalesDocument(ModifyVendorAddressNotification: Notification)
    var
        Vendor: Record Vendor;
        PurchaseHeader: Record "Purchase Header";
        UpdateAddress: Page "Update Address";
    begin
        if not ModifyVendorAddressNotification.HasData(PurchaseHeader.FieldName("Pay-to Vendor No.")) then
            exit;

        OnBeforeCopyPayToVendorAddressFieldsFromSalesDocument(ModifyVendorAddressNotification, PurchaseHeader);

        // Document Type
        Evaluate(PurchaseHeader."Document Type", ModifyVendorAddressNotification.GetData(PurchaseHeader.FieldName("Document Type")));
        PurchaseHeader.Get(PurchaseHeader."Document Type", ModifyVendorAddressNotification.GetData(PurchaseHeader.FieldName("No.")));
        if Vendor.Get(ModifyVendorAddressNotification.GetData(PurchaseHeader.FieldName("Pay-to Vendor No."))) then begin
            UpdateAddress.SetName(Vendor.Name);
            UpdateAddress.SetUpdatedAddress(GetPurchaseHeaderFullPayToAddress(PurchaseHeader));
            UpdateAddress.SetExistingAddress(GetVendorFullAddress(Vendor));

            if UpdateAddress.RunModal() in [ACTION::OK, ACTION::LookupOK] then begin
                Vendor.SetAddress(PurchaseHeader."Pay-to Address", PurchaseHeader."Pay-to Address 2",
                  PurchaseHeader."Pay-to Post Code", PurchaseHeader."Pay-to City", PurchaseHeader."Pay-to County",
                  PurchaseHeader."Pay-to Country/Region Code", PurchaseHeader."Pay-to Contact");
                OnCopyPayToVendorAddressFieldsFromSalesDocumentOnBeforeModify(Vendor, PurchaseHeader);
                Vendor.Modify(true);
            end;
        end;
    end;
`
and

`
    procedure CopyPayToVendorAddressFieldsFromSalesDocument(ModifyVendorAddressNotification: Notification)
    var
        Vendor: Record Vendor;
        PurchaseHeader: Record "Purchase Header";
        UpdateAddress: Page "Update Address";
    begin
        if not ModifyVendorAddressNotification.HasData(PurchaseHeader.FieldName("Pay-to Vendor No.")) then
            exit;

        OnBeforeCopyPayToVendorAddressFieldsFromSalesDocument(ModifyVendorAddressNotification, PurchaseHeader);

        // Document Type
        Evaluate(PurchaseHeader."Document Type", ModifyVendorAddressNotification.GetData(PurchaseHeader.FieldName("Document Type")));
        PurchaseHeader.Get(PurchaseHeader."Document Type", ModifyVendorAddressNotification.GetData(PurchaseHeader.FieldName("No.")));
        if Vendor.Get(ModifyVendorAddressNotification.GetData(PurchaseHeader.FieldName("Pay-to Vendor No."))) then begin
            UpdateAddress.SetName(Vendor.Name);
            UpdateAddress.SetUpdatedAddress(GetPurchaseHeaderFullPayToAddress(PurchaseHeader));
            UpdateAddress.SetExistingAddress(GetVendorFullAddress(Vendor));

            if UpdateAddress.RunModal() in [ACTION::OK, ACTION::LookupOK] then begin
                Vendor.SetAddress(PurchaseHeader."Pay-to Address", PurchaseHeader."Pay-to Address 2",
                  PurchaseHeader."Pay-to Post Code", PurchaseHeader."Pay-to City", PurchaseHeader."Pay-to County",
                  PurchaseHeader."Pay-to Country/Region Code", PurchaseHeader."Pay-to Contact");
                OnCopyPayToVendorAddressFieldsFromSalesDocumentOnBeforeModify(Vendor, PurchaseHeader);
                Vendor.Modify(true);
            end;
        end;
    end;
`

### Additional context

Can you please add 2 new event:

- OnCopyBuyFromVendorAddressFieldsFromSalesDocumentOnBeforeModify
- OnCopyPayToVendorAddressFieldsFromSalesDocumentOnBeforeModify 

similar to 

- OnCopyBillToCustomerAddressFieldsFromSalesDocumentOnBeforeModify
- OnCopySellToCustomerAddressFieldsFromSalesDocumentOnBeforeModify.

Want to modify the Purchase Header with additional values after SetAddress. Similar events are available for Sales.<br /><br />Internal work item: AB#494520

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14915.
