### ISSUE TITLE
[Event Modification] Codeunit 5807 "Item Charge Assgnt. (Sales)" - OnBeforeCreateShptChargeAssgnt

### ISSUE THREAD

**Issue by arzas89** [microsoft/ALAppExtensions#25579]
### Describe the request

Hi there,

We need the existing IsHandled variable in the 'OnBeforeCreateShptChargeAssgnt' publisher event in the "Item Charge Assgnt. (Sales)" codeunit. Currently, the call to the event is as follows: 

```
procedure CreateShptChargeAssgnt(var FromSalesShptLine: Record "Sales Shipment Line"; ItemChargeAssgntSales: Record "Item Charge Assignment (Sales)")
var
        ItemChargeAssgntSales2: Record "Item Charge Assignment (Sales)";
        Nextline: Integer;
        IsHandled: Boolean;
begin
        IsHandled := false;
        >>>>>>>>>>>>>>>>>>>
        OnBeforeCreateShptChargeAssgnt(FromSalesShptLine, ItemChargeAssgntSales);
        <<<<<<<<<<<<<<<<<<<
        if IsHandled then
            exit;

        Nextline := ItemChargeAssgntSales."Line No.";
        [...]
end;
```

It could be changed as follows:
```
procedure CreateShptChargeAssgnt(var FromSalesShptLine: Record "Sales Shipment Line"; ItemChargeAssgntSales: Record "Item Charge Assignment (Sales)")
var
        ItemChargeAssgntSales2: Record "Item Charge Assignment (Sales)";
        Nextline: Integer;
        IsHandled: Boolean;
begin
        IsHandled := false;
        >>>>>>>>>>>>>>>>>>>
        OnBeforeCreateShptChargeAssgnt(FromSalesShptLine, ItemChargeAssgntSales, IsHandled);
        <<<<<<<<<<<<<<<<<<<
        if IsHandled then
            exit;

        Nextline := ItemChargeAssgntSales."Line No.";
        [...]
end;
```

### Additional context

We need existing IsHandled variable in OnBeforeCreateShptChargeAssgnt publisher event on "Item Charge Assgnt. (Sales)" codeunit.<br /><br />Internal work item: AB#494528

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14915.
