### ISSUE TITLE
[Event Request] Table 38 Purchase Header - OnAfterIsShipToAddressEqualToCompanyShipToAddress

### ISSUE THREAD

**Issue by vladsandortnp** [microsoft/ALAppExtensions#25577]
### Describe the request

Can you please add event OnAfterIsShipToAddressEqualToCompanyShipToAddress in procedure IsShipToAddressEqualToCompanyShipToAddress from table 38 Purchase Header?

Want to enforce additional checks to IsShipToAddressEqualToCompanyShipToAddress.

How the event would look:

`

    [IntegrationEvent(false, false)]
    local procedure OnAfterHasDifferentBuyFromAddress(PurchaseHeader: Record "Purchase Header"; CompanyInformation: Record "Company Information"; var Result: Boolean)
    begin
    end;
`

How the procedure would look:

`
    local procedure IsShipToAddressEqualToCompanyShipToAddress(PurchaseHeader: Record "Purchase Header"; CompanyInformation: Record "Company Information") Result: Boolean
    begin
        Result := 
          (PurchaseHeader."Ship-to Address" = CompanyInformation."Ship-to Address") and
          (PurchaseHeader."Ship-to Address 2" = CompanyInformation."Ship-to Address 2") and
          (PurchaseHeader."Ship-to City" = CompanyInformation."Ship-to City") and
          (PurchaseHeader."Ship-to County" = CompanyInformation."Ship-to County") and
          (PurchaseHeader."Ship-to Post Code" = CompanyInformation."Ship-to Post Code") and
          (PurchaseHeader."Ship-to Country/Region Code" = CompanyInformation."Ship-to Country/Region Code") and
          (PurchaseHeader."Ship-to Name" = CompanyInformation."Ship-to Name"));

          OnAfterIsShipToAddressEqualToCompanyShipToAddress(PurchaseHeader, CompanyInformation, Result);
    end;
`

### Additional context

Can you please add event OnAfterIsShipToAddressEqualToCompanyShipToAddress in procedure IsShipToAddressEqualToCompanyShipToAddress from table 38 Purchase Header?

Want to enforce additional checks to IsShipToAddressEqualToCompanyShipToAddress.<br /><br />Internal work item: AB#494530

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14915.
