### ISSUE TITLE
[Event Request] Table 38 Purchase Header - OnAfterBuyFromAddressEqualsShipToAddress

### ISSUE THREAD

**Issue by vladsandortnp** [microsoft/ALAppExtensions#25578]
### Describe the request

Can you please add event OnAfterBuyFromAddressEqualsShipToAddress in procedure BuyFromAddressEqualsShipToAddress from table 38 Purchase Header?

Want to enforce additional checks to BuyFromAddressEqualsShipToAddress.

How the event would look:

`

    [IntegrationEvent(false, false)]
    local procedure OnAfterBuyFromAddressEqualsShipToAddress(PurchaseHeader: Record "Purchase Header"; var Result: Boolean)
    begin
    end;
`

How the procedure would look:

`

    procedure BuyFromAddressEqualsShipToAddress() Result: Boolean
    begin
        Result :=
          ("Ship-to Address" = "Buy-from Address") and
          ("Ship-to Address 2" = "Buy-from Address 2") and
          ("Ship-to City" = "Buy-from City") and
          ("Ship-to County" = "Buy-from County") and
          ("Ship-to Post Code" = "Buy-from Post Code") and
          ("Ship-to Country/Region Code" = "Buy-from Country/Region Code") and
          ("Ship-to Name" = "Buy-from Vendor Name"));

        OnAfterBuyFromAddressEqualsShipToAddress(Rec, Result);
    end;
`

### Additional context

Can you please add event OnAfterBuyFromAddressEqualsShipToAddress in procedure BuyFromAddressEqualsShipToAddress from table 38 Purchase Header?

Want to enforce additional checks to BuyFromAddressEqualsShipToAddress.<br /><br />Internal work item: AB#494531

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14915.
