### ISSUE TITLE
[Event Request] Codeunit 408 - "DimensionManagement" - OnCheckDimValueComb

### ISSUE THREAD

**Issue by matteodelgatto** [microsoft/ALAppExtensions#25574]
### Describe the request

local procedure CheckDimValueComb(Dim1: Code[20]; Dim1Value: Code[20]; Dim2: Code[20]; Dim2Value: Code[20]): Boolean
var
    DimValueCombination: Record "Dimension Value Combination";
    **IsHandled: boolean;**
begin
    OnBeforeCheckDimValueComb(DimValueCombination);

    if DimValueCombination.Get(Dim1, Dim1Value, Dim2, Dim2Value) then begin
       **OnCheckDimValueComb(Dim1, Dim1Value, Dim2, Dim2Value, IsHandled)**
       **if not IsHandled then begin**
          LogError(
             DimValueCombination.RecordId, 0, StrSubstNo(Text001, Dim1, Dim1Value, Dim2, Dim2Value), '');
           exit(false);
       **end**
   end;
   exit(true);
end;

**    [IntegrationEvent(false, false)]
    local procedure OnCheckDimValueComb(Dim1: Code[20]; Dim1Value: Code[20]; Dim2: Code[20]; Dim2Value: Code[20]; var IsHandled: Boolean)
    begin
    end;
**

### Additional context

Hi,
We need this new event in order to change the dimension combination behavior.
Our customer ask to have also a non-blocking warning message possibility.

have a nice day
Matteo<br /><br />Internal work item: AB#494522

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15815.
