### ISSUE TITLE
[Event Request] codeunit 13 "Gen. Jnl.-Post Batch" - OnBeforeCalcReversePostingDate

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25572]
### Describe the request

    local procedure CalcReversePostingDate(GenJournalLine: Record "Gen. Journal Line") PostingDate: Date
    begin
        OnBeforeCalcReversePostingDate(GenJournalLine);

        if Format(GenJournalLine."Reverse Date Calculation") <> '' then begin
            PostingDate := CalcDate(GenJournalLine."Reverse Date Calculation", GenJournalLine."Posting Date");
            if PostingDate <= GenJournalLine."Posting Date" then
                Error(ReversePostingDateErr, GenJournalLine."Posting Date" + 1);
        end else
            PostingDate := GenJournalLine."Posting Date" + 1;

        ....
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcReversePostingDate(var GenJournalLine: Record "Gen. Journal Line")
    begin
    end;

### Additional context

Financial manager wants to post recurring journal on an ultimo date.<br /><br />Internal work item: AB#494523

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14819.
