### ISSUE TITLE
[Event Request] codeunit 5884 "Phys. Invt. Order-Post"

### ISSUE THREAD

**Issue by xtiche** [microsoft/ALAppExtensions#25573]
### Describe the request

Please add new event directly before throwing error
```
codeunit 5884 "Phys. Invt. Order-Post"
...
procedure "Code"()
    var
        SourceCodeSetup: Record "Source Code Setup";
        InventorySetup: Record "Inventory Setup";
        PhysInvtCountMgt: Codeunit "Phys. Invt. Count.-Management";
        GenJnlPostPreview: Codeunit "Gen. Jnl.-Post Preview";
    begin
        OnBeforeCode(PhysInvtOrderHeader, HideProgressWindow, SuppressCommit);

             ....

            MakeInventoryAdjustment();
            
            // new event >>
            OnFinalizePostingOnBeforeGenJnlPostPreviewThrowError();
            // new event <<
            if PreviewMode then
                GenJnlPostPreview.ThrowError();
            FinalizePost("No.");
        end;
    end;
```
    

### Additional context

We are implementing the creation of G/L Correspondence to make it possible to see them in the preview posting, we need to subscribe after the creation of all possible G/L Entries, but before throwing an error.

<br /><br />Internal work item: AB#494525

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14915.
