### ISSUE TITLE
[Event Parameter Request] Codeunit "Variable Allocation Mgt." - GetAccountBalance

### ISSUE THREAD

**Issue by KennyTangBS** [microsoft/ALAppExtensions#25581]
### Describe the request

Please add a new record parameter `GenJournalLine` to `OnGetAccountBalance` event in `codeunit "Variable Allocation Mgt."`
```al
[IntegrationEvent(false, false)]
local procedure OnGetAccountBalance(var AllocAccountDistribution: Record "Alloc. Account Distribution"; StartDate: Date; EndDate: Date; var AccountBalance: Decimal; var ShareDistributions: Dictionary of [Guid, Decimal]; var TotalBalance: Decimal; var GenJournalLine: Record "Gen. Journal Line"; var Handled: Boolean);
    begin
    end;
```
The parameter is from the call stack:
`GetOrGenerateAllocationLines` (Codeunit 2677 "Gen. Journal Alloc. Acc. Mgt." line 18)
`AllocationAccountMgt.GenerateAllocationLines()` (Codeunit 2675 "Allocation Account Mgt." line 18)
`AllocationAccountMgt.GenerateVariableAllocationLines()` (Codeunit 2675 "Allocation Account Mgt." line 26)
`VariableAllocationMgt.CalculateAmountDistributions()` (Codeunit 2670 "Variable Allocation Mgt." line 11)
`VariableAllocationMgt.CalculateVariableBalance()` (Codeunit 2670 "Variable Allocation Mgt." line 81)
`VariableAllocationMgt.GetAccountBalance()` (Codeunit 2670 "Variable Allocation Mgt." line 102)

### Additional context

It enables to get the account balance by the dimension of the general journal line.<br /><br />Internal work item: AB#494527

**Comment by AleksandricMarko** [comment]
Hello @KennyTangBS 
variable GenJournalLine is not available in the procedure GetAccountBalance
Please review request

**Comment by AleksandricMarko** [comment]
Hi @KennyTangBS 

Unfortunately, we can`t do it like this, at least not as event request. Please try to find some other solution, maybe to create event publisher somewhere else.
