### ISSUE TITLE
 [Event Request] - Procedure CalculateAmtOfSaleLCY in report 119 - "Customer- Sales List"

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#25582]
### Describe the request

Hi

Can you please add the following event to procedure CalculateAmtOfSaleLCY in report 119 - "Customer- Sales List"?

```
local procedure CalculateAmtOfSaleLCY(): Decimal
var
    CustLedgEntry: Record "Cust. Ledger Entry";
    Amt: Decimal;
    i: Integer;
begin
    with CustLedgEntry do begin
        SetCurrentKey("Document Type", "Customer No.", "Posting Date");
        SetRange("Customer No.", Customer."No.");
        SetFilter("Posting Date", Customer.GetFilter("Date Filter"));
        //>>>>>>>>>>
        OnAfterSetCustLedgEntryFilters(CustLedgEntry, Customer);
        //<<<<<<<<<<
        for i := 1 to 2 do begin
```

```
[IntegrationEvent(false, false)]
local procedure OnAfterSetCustLedgEntryFilters(var CustLedgEntry: Record "Cust. Ledger Entry"; Customer: Record Customer)
begin
end;
```

### Additional context

This was a customer request to be able to set filters based on type customer type.<br /><br />Internal work item: AB#494564

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14883.
