### ISSUE TITLE
[Option2Enum]: Data Exch. Framework Data Type

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/ALAppExtensions#25583]
### Describe the request

Please change the Type of "field(5; "Data Type"; Option)" in the table "App/Layers/W1/BaseApp/System/DataExchange/DataExchColumnDef.Table.al" to an Enum.

I already made a pull request: https://github.com/microsoft/BusinessCentralApps/pull/536

### Additional context

I would like to add some "Data Type" for my JSON export, I need a boolean as the data type. This change entails modifying the current option to an enum type.

After a thorough analysis, I've determined that implementing this as a direct type change is more robust and less prone to errors compared to devising a temporary workaround. I have meticulously reviewed all instances where this option is utilized and have not identified any potential conflicts or issues arising from this modification.

Looking forward to your thoughts on this proposed change.

**Comment by JesperSchulz** [comment]
As this issue also is present on the BusinessCentralApps repository, let's close this one to avoid duplicate work.
