### ISSUE TITLE
[Event Request] Table 38 Purchase Header - OnAfterBuyFromAddressEqualsPayToAddress

### ISSUE THREAD

**Issue by vladsandortnp** [microsoft/ALAppExtensions#25580]
### Describe the request

Can you please add event OnAfterBuyFromAddressEqualsPayToAddress in procedure BuyFromAddressEqualsPayToAddress from table 38 Purchase Header?

Want to enforce additional checks to BuyFromAddressEqualsPayToAddress.

How the event would look:

`

    [IntegrationEvent(false, false)]
    local procedure OnAfterBuyFromAddressEqualsPayToAddress(PurchaseHeader: Record "Purchase Header"; var Result: Boolean)
    begin
    end;
`

The procedure would look like:

`

    procedure BuyFromAddressEqualsPayToAddress() Result: Boolean
    begin
        Result :=
          ("Pay-to Address" = "Buy-from Address") and
          ("Pay-to Address 2" = "Buy-from Address 2") and
          ("Pay-to City" = "Buy-from City") and
          ("Pay-to County" = "Buy-from County") and
          ("Pay-to Post Code" = "Buy-from Post Code") and
          ("Pay-to Country/Region Code" = "Buy-from Country/Region Code") and
          ("Pay-to Contact No." = "Buy-from Contact No.") and
          ("Pay-to Contact" = "Buy-from Contact"));

        OnAfterBuyFromAddressEqualsPayToAddress(Rec, Result);
    end;
`

### Additional context

Can you please add event OnAfterBuyFromAddressEqualsPayToAddress in procedure BuyFromAddressEqualsPayToAddress from table 38 Purchase Header?

Want to enforce additional checks to BuyFromAddressEqualsPayToAddress.<br /><br />Internal work item: AB#494529

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14915.
