### ISSUE TITLE
[Bug]: Intrastat BE: Nihil export isn't possible

### ISSUE THREAD

**Issue by PunkyGP** [microsoft/ALAppExtensions#25588]
### Describe the issue

The Intrastat BE extensions adds the ability to report a "Nihil" report.
In the export file the changes are done but you can not export a report without any intrastat lines due to the Intrastat Core.

### Expected behavior

When the "Nihil" boolean is enabled on a Intrastat Report Header you should be able to export a file.

### Steps to reproduce

Create a new Intrastat Report for a random period in a Belgian BC.
Then you enable "Nihil Declaration".
And finally you "export to file".

### Additional context

<img width="1355" alt="Screenshot 2023-12-13 at 14 25 15" src="https://github.com/microsoft/ALAppExtensions/assets/16012756/4c717219-c394-4db2-af79-08ac67eb9e6e">

**Comment by PunkyGP** [comment]
codeunit 4810 IntrastatReportManagement

  procedure ExportOneDataExchangeDef(IntrastatReportHeader: Record "Intrastat Report Header"; DataExchDefCode: Code[20]; ExportType: Integer; var DataExch: Record "Data Exch.")
    var
        DataExchFieldGrouping: Record "Data Exch. Field Grouping";
        IntrastatReportLine: Record "Intrastat Report Line";
        DataExchMapping: Record "Data Exch. Mapping";
        DataExchDef: Record "Data Exch. Def";
        RecordRefSrc: RecordRef;
        OutStreamFilters: OutStream;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeExportOneDataExchangeDef(IntrastatReportHeader, DataExchDefCode, ExportType, DataExch, IsHandled);
        if not IsHandled then begin
            DataExchMapping.SetRange("Data Exch. Def Code", DataExchDefCode);
            DataExchMapping.SetRange("Table ID", Database::"Intrastat Report Line");
            if not DataExchMapping.FindFirst() then
                Error(NoDataExchMappingErr, DataExchMapping.TableCaption, DataExchDef.TableCaption, DataExchDefCode);

            if DataExchMapping."Key Index" <> 0 then begin
                RecordRefSrc.GetTable(IntrastatReportLine);
                RecordRefSrc.CurrentKeyIndex(DataExchMapping."Key Index");
                RecordRefSrc.SetTable(IntrastatReportLine);
            end;

            IntrastatReportLine.SetRange("Intrastat No.", IntrastatReportHeader."No.");
            if ExportType = 1 then // Receipt
                IntrastatReportLine.SetRange(Type, IntrastatReportLine.Type::Receipt);
            if ExportType = 2 then // Shipment
                IntrastatReportLine.SetRange(Type, IntrastatReportLine.Type::Shipment);
            OnBeforeExportIntrastatReportLines(IntrastatReportLine, IntrastatReportHeader);

            **if not IntrastatReportLine.IsEmpty then begin**   ---> THIS LINE MUST BE REMOVED ???
                DataExchFieldGrouping.SetRange("Data Exch. Def Code", DataExchMapping."Data Exch. Def Code");
                DataExchFieldGrouping.SetRange("Data Exch. Line Def Code", DataExchMapping."Data Exch. Line Def Code");
                DataExchFieldGrouping.SetRange("Table ID", DataExchMapping."Table ID");
                SetInternalRefNo(IntrastatReportLine, DataExchFieldGrouping, IntrastatReportHeader);

                DataExch.Init();
                DataExch."Data Exch. Def Code" := DataExchMapping."Data Exch. Def Code";
                DataExch."Data Exch. Line Def Code" := DataExchMapping."Data Exch. Line Def Code";
                DataExch."Table Filters".CreateOutStream(OutStreamFilters);
                OutStreamFilters.WriteText(IntrastatReportLine.GetView());
                if DataExch.Insert(true) then
                    DataExch.ExportFromDataExch(DataExchMapping);
                DataExch.Modify(true);
            end;
        end;
    end;

**Comment by JesperSchulz** [comment]
That sounds like a product defect! Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the 1st party Business Central apps. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
