### ISSUE TITLE
[Procedure Parameter aligning request] codeunit 5610 "Calculate Depreciation" - Calculate

### ISSUE THREAD

**Issue by GeekEding** [microsoft/ALAppExtensions#25587]
### Describe the request

Hi,

we realized a missmatch between different localization versions of the procedure "Calculate" of codeunit "Calculate Depreciation". 

Code from W1 version:
`    procedure Calculate(var DeprAmount: Decimal; var Custom1Amount: Decimal; var NumberOfDays: Integer; var Custom1NumberOfDays: Integer; FANo: Code[20]; DeprBookCode: Code[10]; UntilDate: Date; EntryAmounts: array[4] of Decimal; DateFromProjection: Date; DaysInPeriod: Integer)`

Code from IT version: 
`    procedure Calculate(var DeprAmount: Decimal; var Custom1Amount: Decimal; var NumberOfDays: Integer; var Custom1NumberOfDays: Integer; FANo: Code[20]; DeprBookCode: Code[10]; UntilDate: Date; EntryAmounts: array[4] of Decimal; DateFromProjection: Date; DaysInPeriod: Integer; UseCustom1: Boolean; UseCustom2: Boolean; var Custom2Amount: Decimal; ForcedPercent1: Decimal; ForcedPercent2: Decimal)`

Because this function is used from our solution and we want to use in the same way for all countries, we would like to ask if it's possible to align this functions within in a new one containing all parameters, obsoleting the old one in the W1 or create a function overlay to call it with different parameters in the specific localization (Italy in this case).

Thanks and regards

### Additional context

We want to bring our solution in more and more markets and want to use the same code for all countries without having different localizations for only parameter missmatches.

It could be possible in other ways technically but we would say it makes more sense to have the same functionality in here for all versions. 
Internal work item: AB#495833

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18472.
