### ISSUE TITLE
[Bug]: Invt. Shipment - filling posted entry no field

### ISSUE THREAD

**Issue by xtiche** [microsoft/ALAppExtensions#25586]
### Describe the issue

There is no filling of the field "Invt. Shipment Line"."Item Shpt. Entry No.".

### Expected behavior

After posting "Invt. Document" system fills "Invt. Shipment Line"."Item Shpt. Entry No." by number of ILE."Entry No."

```
codeunit 5851 "Invt. Doc.-Post Shipment"
                    OnRunOnBeforeInvtShptLineInsert(InvtShptLine, InvtDocLine, InvtShptHeader, InvtDocHeader);
                    InvtShptLine.Insert();
                    OnRunOnAfterInvtShptLineInsert(InvtShptLine, InvtDocLine, InvtShptHeader, InvtDocHeader);

                    PostItemJnlLine(InvtShptHeader, InvtShptLine);
                    // add filling of "Invt. Shipment Line"."Item Shpt. Entry No.".
                    ItemJnlPostLine.CollectValueEntryRelation(TempValueEntryRelation, InvtShptLine.RowID1());
                until InvtDocLine.Next() = 0;
                
```                

### Steps to reproduce

Create Inv. Document with type Shipment, will any item, and post it.

### Additional context

![Screenshot_61](https://github.com/microsoft/ALAppExtensions/assets/36332111/93c28dee-62c8-4596-b833-d094c6d4991c)

**Comment by JesperSchulz** [comment]
That sounds like a product defect! Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the 1st party Business Central apps. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
