### ISSUE TITLE
[Event Parameter Request] table 5841 "Standard Cost Worksheet" - OnAfterUpdateCostShares

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25591]
### Describe the request

Add Ratio please

    OnAfterUpdateCostShares(Rec, Ratio);

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateCostShares(var StandardCostWorksheet: Record "Standard Cost Worksheet"; Ratio: Decimal)
    begin
    end;

### Additional context

....<br /><br />Internal work item: AB#494626

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14883.
