### ISSUE TITLE
[Request for External] Set "SortActivity" and "SortPick" to protected var in several reports

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#25592]
### Describe the request

Please set "SortActivity" and "SortPick" to protected var in the following reports:

report 7318 "Whse.-Shipment - Create Pick"
<img width="810" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/34685182/c824fa62-08d9-46a9-afca-e1800b947a65">

report 7305 "Whse.-Source - Create Document"
<img width="600" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/34685182/a86b9508-6661-46ab-b77b-869b8fc97715">

report 5754 "Create Pick"
<img width="714" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/34685182/b549c45b-750e-4d2d-b6cc-290a6a5e348d">

### Additional context

We want to set the sorting method from external.<br /><br />Internal work item: AB#494628

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15328.
