### ISSUE TITLE
[Procedure Var Parameter Request] codeunit 5812 "Calculate Standard Cost" - CalcProdBOMCost

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25597]
### Describe the request

The procedures CalcRtngCost and CalcProdBOMCost with all these decimal parameters are not extensible at all. Somebody in the recent past requested a var ParentItem for CalcRtngCost. We would like something similar for procedure CalcProdBOMCost. I don't think you are inclined to set MfgItem as a var which might lead to unexpected results so I would suggest to add 'var ParentItem: Record Item' as an extra parameter to CalcProdBOMCost

local procedure CalcProdBOMCost(MfgItem: Record Item; ProdBOMNo: Code[20]; RtngNo: Code[20]; MfgItemQtyBase: Decimal; IsTypeItem: Boolean; Level: Integer; var SLMat: Decimal; var RUMat: Decimal; var RUCap: Decimal; var RUSub: Decimal; var RUCapOvhd: Decimal; var RUMfgOvhd: Decimal; var ParentItem: Record Item)
...
                        Type::"Production BOM":
                            CalcProdBOMCost(
                              MfgItem, "No.", RtngNo, CompItemQtyBase, false, Level, SLMat, RUMat, RUCap, RUSub, RUCapOvhd, RUMfgOvhd, ParentItem);
                    end;
                until Next() = 0;
    end;

local procedure CalcMfgItem(ItemNo: Code[20]; var Item: Record Item; Level: Integer)
    ....
                    CalcProdBOMCost(
                  Item, "Production BOM No.", "Routing No.",
                  MfgItemQtyBase, true, Level, SLMat, RUMat, RUCap, RUSub, RUCapOvhd, RUMfgOvhd, Item);
    ....
end;

### Additional context

The use of all these Base decimal variables
        SLMat, SLCap, SLSub, SLCapOvhd, SLMfgOvhd, RUMat, RUCap, RUSub, RUCapOvhd, RUMfgOvhd: Decimal;
is a nightmare. Not extensible at all. No way we get our own variables past them
        SLCapRate, RUCapRate, SLCapOvhdRate, RUCapOvhdRate: Decimal;

I would remove all these parameters an use a var TotalItem: Record Item; with all these procedures. I don't think there is time and energy to do that. So I will request some extra parameters to get it done.

Internal work item: AB#495724

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15085.
