### ISSUE TITLE
Add 'OnAfterUpdateIntrastatFields' in Intrastat Core app

### ISSUE THREAD

**Issue by PunkyGP** [microsoft/ALAppExtensions#25594]
### Describe the request

Hello,

is it possible to add an "OnAfterUpdateIntrastatFields" event in tableextension 4815 "Intrastat Report Sales Head." extends "Sales Header" of the Intrastat Core App.

With this event we are able add extra fields based on the same customer.

Thanks in advance,
Gunter

### Additional context

  local procedure UpdateIntrastatFields(FieldNo: Integer)
    var
        Customer: Record Customer;
        IntrastatReportSetup: Record "Intrastat Report Setup";
        CustomerNo: Code[20];
        IsHandled: Boolean;
    begin
        OnBeforeUpdateIntrastatFields(Rec, FieldNo, IsHandled);
        if IsHandled then
            exit;

        if Rec.IsTemporary() then
            exit;

        if not IntrastatReportSetup.Get() then
            exit;

        if (FieldNo = FieldNo("Sell-to Customer No.")) and
           (IntrastatReportSetup."VAT No. Based On" = IntrastatReportSetup."VAT No. Based On"::"Sell-to VAT")
        then
            CustomerNo := "Sell-to Customer No.";

        if (FieldNo = FieldNo("Bill-to Customer No.")) and
           (IntrastatReportSetup."VAT No. Based On" = IntrastatReportSetup."VAT No. Based On"::"Bill-to VAT")
        then
            CustomerNo := "Bill-to Customer No.";

        if CustomerNo = '' then
            exit;

        if Customer.Get(CustomerNo) then begin
            Validate("Transport Method", Customer."Def. Transport Method");

            if "Document Type" in ["Document Type"::"Credit Memo", "Document Type"::"Return Order"] then
                if Customer."Default Trans. Type - Return" <> '' then
                    Validate("Transaction Type", Customer."Default Trans. Type - Return")
                else
                    Validate("Transaction Type", IntrastatReportSetup."Default Trans. - Return");

            if "Document Type" in ["Document Type"::Invoice, "Document Type"::Order] then
                if Customer."Default Trans. Type" <> '' then
                    Validate("Transaction Type", Customer."Default Trans. Type")
                else
                    Validate("Transaction Type", IntrastatReportSetup."Default Trans. - Purchase");
        end else begin
            Validate("Transport Method", '');
            Validate("Transaction Type", '');
        end;
        OnAfterUpdateIntrastatFields(Rec, FieldNo, Customer, IntrastatReportSetup);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateIntrastatFields(var SalesHeader: Record "Sales Header"; FieldNo: Integer; var IsHandled: Boolean);
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateIntrastatFields(var SalesHeader: Record "Sales Header"; FieldNo: Integer; var Customer: Record Customer; var IntrastatReportSetup: Record "Intrastat Report Setup");
    begin
    end;   <br /><br />Internal work item: AB#494629

**Comment by PunkyGP** [comment]
Is it possible to add the same event also to "Purchase Header" and "Service Header" please? Then every aspect of intrastat act the same. Thanks in advance

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 15337.
