### ISSUE TITLE
[Extensibility request] MX MEXICO | CFDI Tax identification type should be changed for ENUM

### ISSUE THREAD

**Issue by DanielMagMat** [microsoft/ALAppExtensions#25608]
### Describe the request

We are creating an extension that integrates with Dataverse and Dynamics 365 Sales but this particular field (TAX IDENTIFICATION TYPE) in MX Mexico localization is created as a Data Type Option and we require it to be converted to a type ENUM so developers extend the integration. Which is not possible if the Data Type is Option.

### Additional context

This field is available in the Customer Card and Vendor Card. And it is also used to validate if RFC number is a 12 or 13 character.

I have created an issue as a support ticket 2311030010002249 But was redirected to this request channel.

Thanks in advance for the help!<br /><br />Internal work item: AB#494889

**Comment by DanielMagMat** [comment]
Hello @AleksandricMarko are you moderating the issues here? Thank you! :)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15219.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 15250.
