### ISSUE TITLE
[Key Request] Table Extension 31040 "Iss. Payment Order Line CZZ"

### ISSUE THREAD

**Issue by jlorenc01** [microsoft/ALAppExtensions#25609]
### Describe the request

Hello,

would it possible to add a new key to the table extension 31040 "Iss. Payment Order Line CZZ" for the field "Purch. Advance Letter No. CZZ"? Thank you.

```
tableextension 31040 "Iss. Payment Order Line CZZ" extends "Iss. Payment Order Line CZB"
{
    fields
    {
        field(31000; "Purch. Advance Letter No. CZZ"; Code[20])
        {
            Caption = 'Purchase Advance Letter No.';
            DataClassification = CustomerContent;
            TableRelation = if (Type = const(Vendor)) "Purch. Adv. Letter Header CZZ"."No.";
        }
    }
    // NEW KEY:
    keys
    {
        key(Key31000CZZ; "Purch. Advance Letter No. CZZ")
        {
        }
    }
}
```

### Additional context

Currently in the new data model all fields from all extensions are in one database table, but we cannot create a cross-extension key yet.<br /><br />Internal work item: AB#495378

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17772.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 17773.
