### ISSUE TITLE
[Event Request] codeunit 5812 "Calculate Standard Cost" - OnCalcProdBOMCostOnBeforeCalcCompItemQtyBase

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25600]
### Describe the request

    local procedure CalcProdBOMCost(MfgItem: Record Item; ProdBOMNo: Code[20]; RtngNo: Code[20]; MfgItemQtyBase: Decimal; IsTypeItem: Boolean; Level: Integer; var SLMat: Decimal; var RUMat: Decimal; var RUCap: Decimal; var RUSub: Decimal; var RUCapOvhd: Decimal; var RUMfgOvhd: Decimal; var ParentItem: Record Item)
    ....
        with ProdBOMLine do
            if Find('-') then
                repeat
                    OnCalcProdBOMCostOnBeforeCalcCompItemQtyBase(
                      ProdBOMLine, ParentItem, CalculationDate, MfgItem, MfgItemQtyBase, IsTypeItem, CompItemQtyBase, RtngNo, UOMFactor);
                    
                    CompItemQtyBase :=
                      UOMMgt.RoundQty(
                        CostCalcMgt.CalcCompItemQtyBase(ProdBOMLine, CalculationDate, MfgItemQtyBase, RtngNo, IsTypeItem) / UOMFactor);

    ....
end;

    [IntegrationEvent(false, false)]
    local procedure OnCalcProdBOMCostOnBeforeCalcCompItemQtyBase(var ProdBOMLine: Record "Production BOM Line"; var ParentItem: Record Item; CalculationDate: Date; MfgItem: Record Item; MfgItemQtyBase: Decimal; IsTypeItem: Boolean; var CompItemQtyBase: Decimal; RtngNo: Code[20]; UOMFactor: Decimal)
    begin
    end;

### Additional context

Parameter ParentItem is from a previous request https://github.com/microsoft/ALAppExtensions/issues/25597<br /><br />Internal work item: AB#494741

**Comment by AleksandricMarko** [comment]
Hello @Duizy1971 
Please review request as ParentItem does not exist as a variable.
Be aware that new publishers we add just in the latest version BC23.

**Comment by Duizy1971** [comment]
Request https://github.com/microsoft/ALAppExtensions/issues/25597 is required first. That will give the ParentItem. I tried not to put everything in one issue, but issues must be done in order of request ID please.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15085.
