### ISSUE TITLE
[Extensibility Request] Default Dimension as columns in Config. Package

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#25607]
### Describe the request

In codeunit "Config. XML Exchange" 
I Suggest renaming this function GetDefaultDimensionKeyFieldIdFromTable and adding the event at the end of the function  OnAfterGetDefaultDimensionKeyFieldIdFromTable(TableID: Integer; var ResultFieldId: Integer)

### Additional context

If the table has a default dimension we need to subscribe to the one event Config. Management OnAfterIsDefaultDimTable
But it's not enough when Default Dimension is mapped by the not first key field because in codeunit "Config. XML Exchange" function GetPrimaryKeyFieldNumber returns the first key fieldid. 
Internal work item: [AB#495831](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/495831)

**Comment by Groenbech96** [comment]
I dont understand the issue. Can you explain using an example?

**Comment by Groenbech96** [comment]
I will close the ticket as stale. Please feel free to reopen ticket if needed.

**Comment by vlkov** [comment]
@Groenbech96, we need it for tables that have an assigned Default Dimension, but where the assigned field with code[20] is not the first primary key. For example, we have a table with a GUID primary key and use a non-primary unique field(with type code[20] ) to link the default dimension.
