### ISSUE TITLE
[Event Request] - Table Purchase Header - Function CheckMixedDropShipment

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#25605]
### Describe the request

```
 local procedure CheckMixedDropShipment()
    var
        IsHandled:Boolean;
    begin
        //NewEvent
        OnBeforeCheckMixedDropShipment(Rec,IsHandled);
        if IsHandled then
            exit;
        //NewEvent
        if HasMixedDropShipment() then
            Error(MixedDropshipmentErr);
    end;

```

```
 [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckMixedDropShipment(var PurchaseHeader:Record "Purchase Header" var IsHandled: Boolean)
    begin
    end;
```

### Additional context

I need this event to skip the check<br /><br />Internal work item: AB#494822

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14915.
