### ISSUE TITLE
[EVENT REQUEST] for mapping shopify B2B customers

### ISSUE THREAD

**Issue by FrankAuwers** [microsoft/ALAppExtensions#25604]
### Describe the request

Make the following event as Integration Event.

     [InternalEvent(false)]
    /// <summary> 
    /// Description for OnBeforeMapCustomer.
    /// </summary>
    /// <param name="ShopifyOrderHeader">Parameter of type Record "Shopify Order Header".</param>
    /// <param name="Handled">Parameter of type Boolean.</param>
    internal procedure OnBeforeMapCustomer(var ShopifyOrderHeader: Record "Shpfy Order Header"; var Handled: Boolean)
    begin
    end;

### Additional context

We want to use this for mapping B2B customers. But if it is not a B2B customer it must follow the standard for B2C Customers.<br /><br />Internal work item: AB#494821

**Comment by pri-kise** [comment]
I thought there were some discussions on adding a B2B feature for the Shopify Connector by microsoft.
https://www.yammer.com/dynamicsnavdev/threads/2445981539434496

Additionally the IsHandled pattern should be avoided for the Shopify connector.
We should think how extensibility can be achived by Interfaces .

@AndreiPanko

**Comment by AndreiPanko** [comment]
Yes, we discussed it here: https://github.com/microsoft/ALAppExtensions/pull/24967

The current way of mapping is not extensible enough and should reconsider it.

The B2B work is already in progress and you can see some of it (customer) in insider builds. Not yet completed.
