### ISSUE TITLE
[Bug]: Filtering problem with pipe (|)

### ISSUE THREAD

**Issue by Dym71** [microsoft/ALAppExtensions#25606]
### Describe the issue

Filtering with pipe char (|) has 2 problems/bugs. It doesn't matter if it's a page or a report request page.
When you apply a more complex filter for a field with table relation, you start typing the first part, select the value and it works perfectly. Then you type a pipe and start typing a second value:
1) The system doesn't prompt you / show you values (except you type the entire word).
2) Even if you type an entire word and select the value it replaces your filter with just only selected value.

We are upgrading one of our biggest client from NAV2015 where everything works perfectly and it's a real problem for them.

### Expected behavior

It should work like before (when you select the next value after pipe, the value should be added at the end).
And of course, it should suggest values when you type.

### Steps to reproduce

Run any page and try to filter any field with table relation.

### Additional context

NAV2015:
![NAV2015](https://github.com/microsoft/ALAppExtensions/assets/63510710/b556aaf0-4117-4ea3-8039-ec8ffa220ef5)

BC23:
![BC23](https://github.com/microsoft/ALAppExtensions/assets/63510710/cd27b6ea-1d5c-4489-a624-5c2c5d29a128)

**Comment by pri-kise** [comment]
You should add votes to the following idea an linked ideas there.
https://experience.dynamics.com/ideas/idea/?ideaid=613b26d0-a9e2-ea11-bf21-0003ff68d4dd
This repository is only for event request and extensibility requests.

**Comment by JesperSchulz** [comment]
This repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the 1st party Business Central apps (which the templates are for).

When you've found a product defect, you believe Microsoft should address, I suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

For suggestions to the Business Central product group, please create a [BC Idea](https://aka.ms/bcideas)
