### ISSUE TITLE
[Event Parameter Request] codeunit 5812 "Calculate Standard Cost" - OnCalcProdBOMCostOnAfterCalcMfgItem

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25601]
### Describe the request

Add var ParentItem: Record Item to OnCalcProdBOMCostOnAfterCalcMfgItem

    [IntegrationEvent(false, false)]
    local procedure OnCalcProdBOMCostOnAfterCalcMfgItem(var ProdBOMLine: Record "Production BOM Line"; MfgItem: Record Item; MfgItemQtyBase: Decimal; CompItem: Record Item; CompItemQtyBase: Decimal; Level: Integer; IsTypeItem: Boolean; UOMFactor: Decimal; var ParentItem: Record Item)
    begin
    end;

### Additional context

Request https://github.com/microsoft/ALAppExtensions/issues/25597 is required first.<br /><br />Internal work item: AB#494742

**Comment by AleksandricMarko** [comment]
Hello @Duizy1971 
Procedure  CalcProdBOMCost containes 2 Item variables - MfgItem and CompItem and both of them are already part of the event publisher. Please review request.

**Comment by Duizy1971** [comment]
Request https://github.com/microsoft/ALAppExtensions/issues/25597 must first be done before #25601

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15085.
