### ISSUE TITLE
[Event Request] Codeunit 5705 "TransferOrder-Post Receipt" OnBeforeOnRun

### ISSUE THREAD

**Issue by GOBNilsGruettner** [microsoft/ALAppExtensions#25618]
### Describe the request

Hi,

the event publisher OnBeforeOnRun in Codeunit 5705 "TransferOrder-Post Receipt" contains a parameter "HideValidationDialog" that should be call-by-ref, but it is not:

`local procedure OnBeforeOnRun(var TransferHeader2: Record "Transfer Header"; HideValidationDialog: Boolean; SuppressCommit: Boolean; var IsHandled: Boolean)`

### Additional context

As is, the parameter does not serve any purpose, please change it to call-by-ref.
The event publisher's signature should match the identifcally named publisher in codeunit 5705 "TransferOrder-Post Receipt".<br /><br />Internal work item: AB#495173

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14858.
