### ISSUE TITLE
codeunit 1605 "PEPPOL Management" - IsRoundingLine

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#25614]
### Describe the request

Can you change procedure IsRoundingLine to global in codeunit 1605 "PEPPOL Management"?

### Additional context

I need this to check whether a line is rounding line in a customization. And I do not want to duplicate the code if I can avoid it.<br /><br />Internal work item: AB#495053

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15328.
