### ISSUE TITLE
[Event Request]: ItemCostManagement, Procedure: CalculatePreciseCostAmounts

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#25610]
### Describe the request

Hi,
to filter Item Ledger Entry in procedure CalculatePreciseCostAmounts it would be great have the following new event: **OnCalculatePreciseCostAmountsOnAfterFilterOpenInboundItemLedgerEntry(OpenInbndItemLedgEntry,Item)**

![image](https://github.com/microsoft/ALAppExtensions/assets/47414309/572d8488-9d9a-4c7f-9ee1-388962dbab77)

The signature of the event looks like this:
  
```
[IntegrationEvent(false, false)]
local procedure OnCalculatePreciseCostAmountsOnAfterFilterOpenInboundItemLedgerEntry(OpenInbndItemLedgEntry: Record "Item Ledger Entry"; var Item: Record Item)
begin
end;

```
Thanks!

### Additional context

We want to filter the open inbound item Ledger Entry in the procedure CalculatePreciseCostAmounts - this additinal filters are needet to be able to filter item ledger entries according to further criteria.<br /><br />Internal work item: AB#494890

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14917.
