### ISSUE TITLE
[Event Request] Codeunit 5857 "Copy Invt. Document Mgt."

### ISSUE THREAD

**Issue by alext0rn** [microsoft/ALAppExtensions#25626]
### Describe the request

Please can you add this event at the end of the procedure CopyInvtDocLine in object Codeunit 5857 "Copy Invt. Document Mgt.":

### Additional context

 

            OnCopyInvtDocLineOnBeforeCopyItemTrackingAndAppliesValues(ToInvtDocHeader, ToInvtDocLine, FromInvtDocHeader, FromInvtDocLine, GlobalFromDocType, CopyThisLine, IsHandled);
            if not IsHandled then begin
                case GlobalFromDocType of
                    GlobalFromDocType::"Posted Receipt":
                        GetItemLedgEntries(Enum::"Item Ledger Document Type"::"Inventory Receipt", FromInvtDocLine."Document No.", FromInvtDocLine."Line No.", TempItemLedgerEntry, true);
                    GlobalFromDocType::"Posted Shipment":
                        GetItemLedgEntries(Enum::"Item Ledger Document Type"::"Inventory Shipment", FromInvtDocLine."Document No.", FromInvtDocLine."Line No.", TempItemLedgerEntry, true);
                end;

                UpdateInvtDocumentLineWithTrackingAndAppliesValue(TempItemLedgerEntry, ToInvtDocLine, ToInvtDocHeader, FillAppliesFields, LinesSkipApplies);
            end;
        end;

        if CopyThisLine then
            ToInvtDocLine.Insert()
        else
            LinesNotCopied := LinesNotCopied + 1;

        OnAfterCopyInvtDocLine(ToInvtDocLine, FromInvtDocHeader, FromInvtDocLine);
    end;

    
    [IntegrationEvent(false, false)]
    local procedure  OnAfterCopyInvtDocLine(var ToInvtDocLine: Record "Invt. Document Line"; var FromInvtDocHeader: Record "Invt. Document Header"; var FromInvtDocLine: Record "Invt. Document Line")
    begin
    end;`<br /><br />Internal work item: AB#495253

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14917.
