### ISSUE TITLE
[Request For External] Remove scope OnPrem in MergeDuplicatesLineBuffer.Table.al and MergeDuplicatesConflict.Table.al

### ISSUE THREAD

**Issue by MAC-Christian** [microsoft/ALAppExtensions#25629]
### Describe the request

Hi Team,

in order to be able to change app target to cloud, could the scope OnPrem be removed in following objects and procedures? 

#### MergeDuplicatesLineBuffer.Table.al
Procedure FindConflicts
``` AL
[Scope('OnPrem')]
procedure FindConflicts(OldKey: Text; NewKey: Text; var TempMergeDuplicatesConflict: Record "Merge Duplicates Conflict" temporary): Integer
```
Procedure HasModifiedField
``` AL
[Scope('OnPrem')]
procedure HasModifiedField() Result: Boolean
```
#### MergeDuplicatesConflict.Table.al
 Procedure Merge 
``` AL
[Scope('OnPrem')]
procedure Merge(): Boolean
```

Thanks,
Christian

### Additional context

Procedures cannot be used in apps with target = cloud.<br /><br />Internal work item: AB#495301

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15328.
