### ISSUE TITLE
[Event Request] Report 5850 "Copy Invt. Document"

### ISSUE THREAD

**Issue by alext0rn** [microsoft/ALAppExtensions#25627]
### Describe the request

Please can you add this event to the trigger OnPreReport() in object Report 5850 "Copy Invt. Document":

### Additional context

    trigger OnPreReport()
    begin

      CheckInputParameters();
  
      CopyInvtDocMgt.SetProperties(IncludeHeader, RecalculateLines, false, false, AutoFillAppliesFields);
      CopyInvtDocMgt.CopyAsCorrection(CopyAsCorrection);
      CopyInvtDocMgt.SetCopyItemTracking(CopyItemTracking);
      CopyInvtDocMgt.CopyItemDoc(DocType, DocNo, InvtDocHeader);
      OnAfterOnPreReport(InvtDocHeader, DocType, DocNo);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterOnPreReport(var InvtDocHeader: Record "Invt. Document Header";DocType: Enum "Invt. Doc. Document Type From";  DocNo: Code[20])
    begin
    end;<br /><br />Internal work item: AB#495254

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14917.
