### ISSUE TITLE
[Event Change Request] table 81 "Gen. Journal Line" - OnAfterCreateDim

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#25628]
### Describe the request

Could you please update the event `OnAfterCreateDim` in `table 81 "Gen. Journal Line"` to include some additional parameters?

```al
    procedure CreateDim(DefaultDimSource: List of [Dictionary of [Integer, Code[20]]])
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCreateDim(Rec, IsHandled, CurrFieldNo);
        if IsHandled then
            exit;

        "Shortcut Dimension 1 Code" := '';
        "Shortcut Dimension 2 Code" := '';
        OldDimSetID := Rec."Dimension Set ID"; //CHANGE
        "Dimension Set ID" :=
          DimMgt.GetRecDefaultDimID(
            Rec, CurrFieldNo, DefaultDimSource, "Source Code", "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code", 0, 0);

        //+CHANGE
        //-OnAfterCreateDim(Rec, CurrFieldNo);
        OnAfterCreateDim(Rec, CurrFieldNo, xRec, OldDimSetID, DefaultDimSource);
        //-CHANGE
    end;
```

```al
[IntegrationEvent(false, false)]
//+Change
//-local procedure OnAfterCreateDim(var GenJournalLine: Record "Gen. Journal Line"; CurrFieldNo: Integer)
local procedure OnAfterCreateDim(var GenJournalLine: Record "Gen. Journal Line"; CurrFieldNo: Integer; xGenJournalLine: Record "Gen. Journal Line"; OldDimSetID: Integer; DefaultDimSource: List of [Dictionary of [Integer, Code[20]]])
//-Change
begin
end;
```

### Additional context

We already have those additional parameters in similiar events in `table 36 "Sales Header"`.

With the additional parameters we're able to restore some Dimensions, that are manually entered for specific dimensions.
Those values are cleared by recreating the DimensionsSetID from the DefaultDimSource List.<br /><br />Internal work item: AB#495256

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14917.
