### ISSUE TITLE
[Event Request / Extensiblity Request] codeunit 6651 "Return Shipment - Printed" - OnBeforeOnRun

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#25624]
### Describe the request

Could you please provid a similiar event to all other _Printed_ Codeunits to suppress the Commit in `codeunit 6651 "Return Shipment - Printed"`?
```al
codeunit 6651 "Return Shipment - Printed"
{
    Permissions = TableData "Return Shipment Header" = rimd;
    TableNo = "Return Shipment Header";

    trigger OnRun()
    var
        
    begin
        OnBeforeOnRun(Rec, SuppressCommit); //New Event
        Rec.Find();
        Rec."No. Printed" := Rec."No. Printed" + 1;
        OnBeforeModify(Rec);
        Rec.Modify();
        if not SuppressCommit then //CHANGE
            Commit();
    end;
//+Change
    var
        SuppressCommit: Boolean;

    procedure SetSuppressCommit(NewSuppressCommit: Boolean)
    begin
        SuppressCommit := NewSuppressCommit;
    end;
//-Change
}
```

```al


    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnRun(var ReturnShipmentHeader: Record "Return Shipment Header"; var SuppressCommit: Boolean)
    begin
    end;
```

### Additional context

In some scenarios we'd like to suppress the Commit here.

This already possible in a similiar codeunit `codeunit 314 "Sales Shpt.-Printed"`.<br /><br />Internal work item: AB#495250

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14917.
