### ISSUE TITLE
[Event Request / Extensiblity Request] codeunit 5903 "Service Shpt.-Printed"- OnBeforeOnRun

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#25625]
### Describe the request

Could you please provid a similiar event to all other _Printed_ Codeunits to suppress the Commit in `codeunit 5903 "Service Shpt.-Printed"`?

```al
codeunit 5903 "Service Shpt.-Printed"
{
    Permissions = TableData "Service Shipment Header" = rimd;
    TableNo = "Service Shipment Header";

    trigger OnRun()
    begin
        OnBeforeRun(Rec, SuppressCommit); //New Event
        Rec.Find();
        Rec."No. Printed" := Rec."No. Printed" + 1;
        OnBeforeModify(Rec);
        Rec.Modify();
        if not SuppressCommit then //Change
            Commit();
    end;

//+Change
    var
        SuppressCommit: Boolean;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeRun(var  ServiceShipmentHeader: Record  "Service Shipment Header"; var SuppressCommit: Boolean)
    begin
    end;
//-Change
}
```

### Additional context

In some scenarios we'd like to suppress the Commit here.

This already possible in a similiar codeunit `codeunit 5904 "Service Cr. Memo-Printed"`.<br /><br />Internal work item: AB#495255

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14917.
