### ISSUE TITLE
[Extensibility Bug ] table 295 "Reminder Header" -OnBeforeGetNoSeriesCode

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#25620]
### Describe the request

Could you change the following?
```al
procedure GetNoSeriesCode(): Code[20]
var
    NoSeriesCode: Code[20];
    IsHandled: Boolean;
begin
    SalesSetup.Get();
    IsHandled := false;
    OnBeforeGetNoSeriesCode(Rec, SalesSetup, NoSeriesCode, IsHandled);
    if IsHandled then
        //+CHANGE
        //-exit;
        exit(NoSeriesCode);
        //-CHANGE

    NoSeriesCode := SalesSetup."Reminder Nos.";

    OnAfterGetNoSeriesCode(Rec, SalesSetup, NoSeriesCode);
    exit(NoSeriesMgt.GetNoSeriesWithCheck(NoSeriesCode, SelectNoSeriesAllowed, "No. Series"));
end;
```

### Additional context

The event `OnBeforeGetNoSeriesCode` is useless in its current form, since the exit does not return the `NoSeriesCode`.<br /><br />Internal work item: AB#495249

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14915.
