### ISSUE TITLE
[Extensibility Bug ] table 5740 "Transfer Header" -OnBeforeGetNoSeriesCode

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#25623]
### Describe the request

```al
local procedure GetNoSeriesCode(): Code[20]
var
    NoSeriesCode: Code[20];
    IsHandled: Boolean;
begin
    GetInventorySetup();
    IsHandled := false;
    OnBeforeGetNoSeriesCode(Rec, InvtSetup, NoSeriesCode, IsHandled);
    if IsHandled then
        //+CHANGE
        //-exit;
        exit(NoSeriesCode);
        //-CHANGE

    NoSeriesCode := InvtSetup."Transfer Order Nos.";
    OnAfterGetNoSeriesCode(Rec, NoSeriesCode);
    exit(NoSeriesCode);
end;
```

### Additional context

The event `OnBeforeGetNoSeriesCode` is useless in its current form, since the exit does not return the `NoSeriesCode`.<br /><br />Internal work item: AB#495252

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 14915.
