### ISSUE TITLE
report 1306 "Standard Sales - Order Conf."

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#25637]
### Describe the request

Please set the variable LineDiscountPctText to protected in the report report 1306 "Standard Sales - Order Conf."

### Additional context

the value may be changed in the report extension.<br /><br />Internal work item: AB#495414

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15328.
