### ISSUE TITLE
[Event Request] Report 31004 "Adjust Exchange Rates CZL" - procedure PostGenJnlLine()

### ISSUE THREAD

**Issue by jlorenc01** [microsoft/ALAppExtensions#25636]
### Describe the request

Hello,

I would like to ask for a new publisher in the report 31004 "Adjust Exchange Rates CZL", procedure PostGenJnlLine(). We need to call the procedure SetOverrideDimErr() from the codeunit 12 "Gen. Jnl.-Post Line" before posting. Thank you.

```
local procedure PostGenJnlLine(var GenJournalLine: Record "Gen. Journal Line"; var DimensionSetEntry: Record "Dimension Set Entry"): Integer
var
    DefaultDimSource: List of [Dictionary of [Integer, Code[20]]];
begin
    ...

    if Post then begin
        OnPostGenJnlLineOnBeforeGenJnlPostLineRun(GenJnlPostLine, GenJournalLine, DimensionSetEntry); // NEW EVENT
        GenJnlPostLine.Run(GenJournalLine);
        exit(GenJnlPostLine.GetNextTransactionNo());
    end;
end;

// NEW EVENT
[IntegrationEvent(true, false)]
local procedure OnPostGenJnlLineOnBeforeGenJnlPostLineRun(var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; var GenJournalLine: Record "Gen. Journal Line"; var DimensionSetEntry: Record "Dimension Set Entry")
begin
end;
```

### Additional context

We need to call the procedure SetOverrideDimErr() from the codeunit 12 "Gen. Jnl.-Post Line" before posting.<br /><br />Internal work item: AB#495394

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 15273.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15270.
