### ISSUE TITLE
[Request for External] Remove OnPrem from method OnCheckGenJournalLineExportRestrictions

### ISSUE THREAD

**Issue by mynhardt7** [microsoft/ALAppExtensions#25639]
### Describe the request

Will you please remove the Scope(OnPrem) from function OnCheckGenJournalLineExportRestrictions in table 232 "Gen. Journal Batch".

```AL
[IntegrationEvent(TRUE, false)]
[Scope('OnPrem')]
procedure OnCheckGenJournalLineExportRestrictions()
begin
end;
```

### Additional context

Since the event is marked OnPrem it cannot by triggered by Cloud/Universal Code.<br /><br />Internal work item: AB#495423

**Comment by AlexanderYakunin** [comment]
Sorry, you should not call this event as procedure. Event should be used via subscribers.
