### ISSUE TITLE
[Event Change Request] Codeunit 99 "Posting Selection Management" OnConfirmPostSalesDocumentOnBeforeSalesOrderGetSalesInvoicePostingPolicy

### ISSUE THREAD

**Issue by sgiordy** [microsoft/ALAppExtensions#25645]
### Describe the request

Hello,

the various events in CU 99:

- OnConfirmPostSalesDocumentOnBeforeSalesOrderGetSalesInvoicePostingPolicy
- OnConfirmPostSalesDocumentOnBeforeSalesOrderReturnGetSalesInvoicePostingPolicy
- ...

are unuseful because the following method overrides the custom behaviour. Example:

![image](https://github.com/microsoft/ALAppExtensions/assets/17341714/0502d472-f1e5-4a31-ba20-9ce50b233c54)

I suggest to change the order of the events or to add a new event.

**The events are missing in the purchase area, please complete.**

Thank you,
Simone

### Additional context

We need to manage Invoice Posting Policy per document type.<br /><br />Internal work item: AB#495474

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15201.
