### ISSUE TITLE
[Event Change Request] codeunit 5063 ArchiveManagement - OnRestoreSalesDocumentOnAfterSalesHeaderInsert

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#25641]
### Describe the request

Could you please change the following event in `codeunit 5063 ArchiveManagement` to include the `SalesHeaderArchive` by reference?

```al
[IntegrationEvent(false, false)]
//+Change
//-local procedure OnRestoreSalesDocumentOnAfterSalesHeaderInsert(var SalesHeader: Record "Sales Header"; SalesHeaderArchive: Record "Sales Header Archive")
local procedure OnRestoreSalesDocumentOnAfterSalesHeaderInsert(var SalesHeader: Record "Sales Header"; var SalesHeaderArchive: Record "Sales Header Archive")
//-Change
begin
end;
```

### Additional context

With this change we could simple call CalcFields on Custom PTE Fields before  the TransferFields is executed.<br /><br />Internal work item: AB#495447

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15085.
