### ISSUE TITLE
[Request for External] Set "DoNotFillQtytoHandle" to protected var in several reports

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#25640]
### Describe the request

Hi,

report 7318 "Whse.-Shipment - Create Pick"
please set "DoNotFillQtytoHandle" to protected vars.

<img width="505" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/34685182/c430d7eb-704b-48b4-9801-d2c8fbf8043f">

report 7305 "Whse.-Source - Create Document"
please set "DoNotFillQtytoHandle" to protected vars.

<img width="504" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/34685182/3f553635-953a-45a9-911c-dfd679c02aa0">

report 5754 "Create Pick"
please set "DoNotFillQtytoHandle" to protected vars.
<img width="762" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/34685182/74614a45-da4c-4ba0-883e-dbf352512372">

### Additional context

We need to modify the flags "DoNotFillQtytoHandle" on open the pages.<br /><br />Internal work item: AB#495424

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15328.
