### ISSUE TITLE
Table 5900 Service Header - procedure SetDefaultSalesperson

### ISSUE THREAD

**Issue by GregEnns** [microsoft/ALAppExtensions#25658]
### Describe the request

Can we please get OnBeforeSetDefaultSalesperson publisher added at the beginning of SetDefaultSalesperson procedure?
```
    local procedure SetDefaultSalesperson()
    var
        UserSetup: Record "User Setup";
    begin
        >>>>>>>>
        OnBeforeSetDefaultSalesperson(Rec, IsHandled);
        <<<<<<<<
        if not UserSetup.Get(UserId) then
            exit;
        if UserSetup."Salespers./Purch. Code" <> '' then
            Validate("Salesperson Code", UserSetup."Salespers./Purch. Code");
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetDefaultSalesperson(var ServiceHeader: Record "Service Header"; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

We have custom code which determines the Salesperson Code--and sometimes we want it to be blank. We are currently subscribing to OnAfterInsert which is slow and not always necessary. 
Internal work item: AB#495744

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15201.
