### ISSUE TITLE
[Event Request] table 2631 "Statistical Acc. Journal Line" - OnAfterCreateDimensions

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#25650]
### Describe the request

Could you please add the event `OnAfterCreateDimensions` in `table 81 "Gen. Journal Line"` and include the specified parameters?

```al
local procedure CreateDimensions(DefaultDimSource: List of [Dictionary of [Integer, Code[20]]])
var
    SourceCodeSetup: Record "Source Code Setup";
    DimensionManagement: Codeunit DimensionManagement;
    OldDimSetID: Integer; //NEW
begin
    "Shortcut Dimension 1 Code" := '';
    "Shortcut Dimension 2 Code" := '';
    OldDimSetID := "Dimension Set ID" ; //NEW
    "Dimension Set ID" :=
        DimensionManagement.GetRecDefaultDimID(
        Rec, CurrFieldNo, DefaultDimSource, SourceCodeSetup.GetSourceCodeSetupSafe(), "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code", 0, 0);
    //+Event
    OnAfterCreateDimensions(Rec, xRec, CurrFieldNo, OldDimSetID, DefaultDimSource);
    //-Event
end;
````

```al
[IntegrationEvent(false, false)]
local procedure OnAfterCreateDimensions(var StatisticalAccJournalLine: Record "Statistical Acc. Journal Line"; xStatisticalAccJournalLine: Record "Statistical Acc. Journal Line"; CurrentFieldNo: Integer; OldDimSetID: Integer; DefaultDimSource: List of [Dictionary of [Integer, Code[20]]])
begin
end;
```

### Additional context

We already have those additional parameters in similiar events in `table 36 "Sales Header"`.

With the additional parameters we're able to restore some Dimensions, that are manually entered for specific dimensions.
Those values are cleared by recreating the DimensionsSetID from the DefaultDimSource List.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15085.
