### ISSUE TITLE
[Event Parameter Request] table 111 "Sales Shipment Line" - procedure "InsertInvLineFromShptLine"

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#25657]
### Describe the request

    **//--> event parameter request
    OnInsertInvLineFromShptLineOnAfterSalesOrderHeaderGet(SalesOrderHeader, SalesInvHeader,SalesOrderLine);
    **//<-- event parameter request

    PrepaymentMgt.TestSalesOrderLineForGetShptLines(SalesOrderLine);
    InitCurrency("Currency Code");
    
    if SalesInvHeader."Prices Including VAT" then begin
        if not SalesOrderHeader."Prices Including VAT" then
            SalesOrderLine."Unit Price" :=
              Round(
                SalesOrderLine."Unit Price" * (1 + SalesOrderLine."VAT %" / 100),
                Currency."Unit-Amount Rounding Precision");
    end else
        if SalesOrderHeader."Prices Including VAT" then
            SalesOrderLine."Unit Price" :=
              Round(
                SalesOrderLine."Unit Price" / (1 + SalesOrderLine."VAT %" / 100),
                Currency."Unit-Amount Rounding Precision");

    **//--> event parameter request
    [IntegrationEvent(false, false)]
    local procedure OnInsertInvLineFromShptLineOnAfterSalesOrderHeaderGet(var SalesOrderHeader: Record "Sales Header"; var SalesInvHeader: Record "Sales Header";var SalesOrderLine: Record "Sales Line")
    begin
    end;
    **//<-- event parameter request

### Additional context

In Turkish localization, it is necessary to make a calculation similar to the one below.

    if SalesInvHeader."Prices Including VAT" then begin
            if not SalesOrderHeader."Prices Including VAT" then
                SalesOrderLine."Unit Price" :=
                  Round(
                    SalesOrderLine."Unit Price" * (1 + SalesOrderLine."VAT %" / 100),
                    Currency."Unit-Amount Rounding Precision");
        end else
            if SalesOrderHeader."Prices Including VAT" then
                SalesOrderLine."Unit Price" :=
                  Round(
                    SalesOrderLine."Unit Price" / (1 + SalesOrderLine."VAT %" / 100),
                    Currency."Unit-Amount Rounding Precision");
Internal work item: AB#495729

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15201.
