### ISSUE TITLE
Events for skipping commits in codeunit 31354 "Issue Payment Order YesNo CZB" and codeunit 31355 "Issue Payment Order Print CZB"

### ISSUE THREAD

**Issue by DanielSmutek** [microsoft/ALAppExtensions#25661]
### Describe the request

Please, add events for skipping Commit() as bellow. Thanks!!
Daniel

**codeunit 31354 "Issue Payment Order YesNo CZB"**

    local procedure Code()
    var
        IssPaymentOrderHeaderCZB: Record "Iss. Payment Order Header CZB";
        Selection: Integer;
    begin
        Selection := StrMenu(IssueQst, 1);
        if Selection = 0 then
            exit;

        Codeunit.Run(Codeunit::"Issue Payment Order CZB", PaymentOrderHeaderCZB);
        // new code >>
        OnBeforeCommit(SkipCommit);
        if not SkipCommit then
        // new code <<
        Commit();
        Message(IssuedSuccesfullyMsg);

        IssPaymentOrderHeaderCZB.Get(PaymentOrderHeaderCZB."Last Issuing No.");
        IssPaymentOrderHeaderCZB.SetRecFilter();
        if Selection = 2 then
            IssPaymentOrderHeaderCZB.ExportPaymentOrder();
        IssPaymentOrderHeaderCZB.PrintRecords(false);
    end;

**codeunit 31355 "Issue Payment Order Print CZB"**

    local procedure Code()
    var
        IssPaymentOrderHeaderCZB: Record "Iss. Payment Order Header CZB";
        Selection: Integer;
    begin
        Selection := StrMenu(IssueQst, 1);
        if Selection = 0 then
            exit;

        Codeunit.Run(Codeunit::"Issue Payment Order CZB", PaymentOrderHeaderCZB);
        // new code >>
        OnBeforeCommit(SkipCommit);
        if not SkipCommit then
        // new code <<
        Commit();
        Message(IssuedSuccesfullyMsg);

        IssPaymentOrderHeaderCZB.Get(PaymentOrderHeaderCZB."Last Issuing No.");
        IssPaymentOrderHeaderCZB.SetRecFilter();
        if Selection = 2 then
            IssPaymentOrderHeaderCZB.ExportPaymentOrder();
        IssPaymentOrderHeaderCZB.PrintRecords(false);
    end;

### Additional context

We need rooling back transaction if export codeunit throws error after Issuing Payment Order
Internal work item: AB#495802

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 15281.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
