### ISSUE TITLE
Event Request - codeunit 5763 "Whse.-Post Shipment" OnBeforeCheckTransferLineQtyToShip

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#25669]
### Describe the request

In codeunit 5763 "Whse.-Post Shipment" can we add OnBeforeValidateTransferLineQtyToShip in procedure HandleTransferLine. 

    local procedure HandleTransferLine(var WhseShptLine: Record "Warehouse Shipment Line")
    var
        TransLine: Record "Transfer Line";
        ModifyLine: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeHandleTransferLine(WhseShptLine, TransLine, WhseShptHeader, ModifyLine, IsHandled);
        if IsHandled then
            exit;

        with WhseShptLine do begin
            TransLine.SetRange("Document No.", "Source No.");
            TransLine.SetRange("Derived From Line No.", 0);
            if TransLine.Find('-') then
                repeat
                    SetRange("Source Line No.", TransLine."Line No.");
                    if Find('-') then begin
                        // NEW +
                        IsHandled := false;
                        OnBeforeCheckTransferLineQtyToShip(WhseShptLine, TransLine, IsHandled);
                        if not IsHandled then begin
                            // NEW -
                            OnAfterFindWhseShptLineForTransLine(WhseShptLine, TransLine);
                            ModifyLine := TransLine."Qty. to Ship" <> "Qty. to Ship";
                            if ModifyLine then
                                ValidateTransferLineQtyToShip(TransLine, WhseShptLine);
                        end; // NEW
                        if (WhseShptHeader."Shipment Date" <> 0D) and
                           (TransLine."Shipment Date" <> WhseShptHeader."Shipment Date") and
                           ("Qty. to Ship" = "Qty. Outstanding")
                        then begin
                            TransLine."Shipment Date" := WhseShptHeader."Shipment Date";
                            ModifyLine := true;
                        end;
                        if TransLine."Transfer-from Bin Code" <> "Bin Code" then begin
                            TransLine."Transfer-from Bin Code" := "Bin Code";
                            ModifyLine := true;
                        end;
                    end else begin
                        ModifyLine := TransLine."Qty. to Ship" <> 0;
                        if ModifyLine then begin
                            TransLine.Validate("Qty. to Ship", 0);
                            TransLine.Validate("Qty. to Receive", 0);
                        end;
                    end;
                    OnBeforeTransLineModify(TransLine, WhseShptLine, ModifyLine);
                    if ModifyLine then
                        TransLine.Modify();
                until TransLine.Next() = 0;
        end;
    end;

    // NEW +
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckTransferLineQtyToShip(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var TransferLine: Record "Transfer Line"; var IsHandled: Boolean)
    begin
    end;
    // NEW -

### Additional context

We are creating Assembly Order for Transfer Orders, and need that event to Post a Transfer Line from warehouse Shipment that has both ATO and Non ATO, Like Sales Order Has
Internal work item: AB#495928

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15656.
