### ISSUE TITLE
[Event Request]  OnAfterFilterFALedgerEntry - procedure SetFAFilter of coudeunit  5616 "Depreciation Calculation"

### ISSUE THREAD

**Issue by omerfaruknav** [microsoft/ALAppExtensions#25668]
### Describe the request

Hi, could you add following publisher to the  end of procedure SetFAFilter of coudeunit  5616 "Depreciation Calculation" ? 

```al
            SetRange(Reversed, false);
        end;
       //NEW CODE START 
        OnAfterFilterFALedgerEntry(FALedgEntry);
        //NEW CODE END 
``` 

```al
    [IntegrationEvent(false, false)]
    local procedure OnAfterFilterFALedgerEntry(var FALedgEntry: Record "FA Ledger Entry")
    begin
    end;
``` 

### Additional context

We need to apply a filter for a custom field.
Internal work item: AB#495914

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15201.
