### ISSUE TITLE
[Access Request ] table 472 "Job Queue Entry" - IsNextRunDateFormulaSet

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#25662]
### Describe the request

Could you please remove Scope OnPrem from procedure `IsNextRunDateFormulaSet` in `table 472 "Job Queue Entry"`?
```al
//+Change
//[Scope('OnPrem')]
//-Change
procedure IsNextRunDateFormulaSet(): Boolean
begin
    exit(Format("Next Run Date Formula") <> '');
end;
```

### Additional context

We'd like to use this procedure in our code and there is no reason, why this procedure has Scope OnPrem.
Internal work item: AB#495803

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15328.
