### ISSUE TITLE
[Event Request] Add OrderNoList to OnBeforeCopyDocumentAttachments i CU 64 "Sales-Get Shipment"

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#25660]
### Describe the request

Hi 

Can you please add the parameter OrderNoList to OnBeforeCopyDocumentAttachments i Codeunit 64 "Sales-Get Shipment"?

You've already done it in Codeunit 74 "Purch.-Get Receipt".

```
local procedure CopyDocumentAttachments(OrderNoList: List of [Code[20]]; var SalesHeader2: Record "Sales Header")
var
    OrderSalesHeader: Record "Sales Header";
    DocumentAttachmentMgmt: Codeunit "Document Attachment Mgmt";
    OrderNo: Code[20];
    Handled: Boolean;
begin
    // >>>>>>>>>>
    //OnBeforeCopyDocumentAttachments(SalesHeader2, Handled);
    OnBeforeCopyDocumentAttachments(OrderNoList, SalesHeader2, Handled);
    // <<<<<<<<<<
    if Handled then
        exit;
```

```
[IntegrationEvent(false, false)]
// >>>>>>>>>>
local procedure OnBeforeCopyDocumentAttachments(var OrderNoList: List of [Code[20]]; var DestinationSalesHeader: Record "Sales Header"; var Handled: Boolean)
//local procedure OnBeforeCopyDocumentAttachments(var DestinationSalesHeader: Record "Sales Header"; var Handled: Boolean)
// <<<<<<<<<<
begin
end;
```

Thanks in advance.

### Additional context

Required for custom code implmentation without rewriting code,
Internal work item: AB#495763

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15201.
