### ISSUE TITLE
[Event Request]  codeunit 22 "Item Jnl.-Post Line" -  OnUpdateUnitCostOnBeforeUpdateUnitCost

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#25673]
### Describe the request

Hello,
Can we please get the Item record as reference in this event ?

Like this:  **var Item: Record Item;**
```
 [IntegrationEvent(false, false)]
    local procedure OnUpdateUnitCostOnBeforeUpdateUnitCost(ItemJournalLine: Record "Item Journal Line"; ValueEntry: Record "Value Entry"; var Item: Record Item; var UpdateSKU: Boolean)
    begin
    end;
```

### Additional context

Need this to be able to set a date field on the item without breaking the code.
Internal work item: AB#496035

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15512.
