### ISSUE TITLE
[Event Request] codeunit 1255 "Match Bank Payments" - OnApplyLedgerEntriesToStatementLines_OnAfterUpdatePaymentMatchDetails

### ISSUE THREAD

**Issue by vervast** [microsoft/ALAppExtensions#25675]
### Describe the request

Please add Event incodeunit 1255 "Match Bank Payments", Procedure ApplyLedgerEntriesToStatementLines

```
local procedure ApplyLedgerEntriesToStatementLines(var BankAccReconciliationLine: Record "Bank Acc. Reconciliation Line"; Overwrite: Boolean)
...
 UpdatePaymentMatchDetails(BankAccReconciliationLine);
        OnApplyLedgerEntriesToStatementLines_OnAfterUpdatePaymentMatchDetails(BankAccReconciliation,BankAccReconciliationLine,Overwrite);  //>>> New Event
        Window.Close();
   
...

[IntegrationEvent(false, false)]
    local procedure OnApplyLedgerEntriesToStatementLines_OnAfterUpdatePaymentMatchDetails(BankAccReconciliation: Record "Bank Acc. Reconciliation"; var BankAccReconciliationLine: Record "Bank Acc. Reconciliation Line"; Overwrite: Boolean)
    begin
    end;
```

### Additional context

Some extra actions when applying 
Internal work item: AB#496034

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15656.
