### ISSUE TITLE
[Event Request] OnCreateAppliedEntries_OnBeforeTempBankStatementMatchingBufferFindset - Procedure CreateAppliedEntries, codeunit 1255 "Match Bank Payments"

### ISSUE THREAD

**Issue by vervast** [microsoft/ALAppExtensions#25671]
### Describe the request

Please add extra event in codeunit 1255 "Match Bank Payments", Procedure: CreateAppliedEntries

_local procedure CreateAppliedEntries(BankAccReconciliation: Record "Bank Acc. Reconciliation")
    var
        BankAccReconciliationLine: Record "Bank Acc. Reconciliation Line";
    begin
        TempBankStatementMatchingBuffer.Reset();
        TempBankStatementMatchingBuffer.SetCurrentKey(Quality, "No. of Entries");
        TempBankStatementMatchingBuffer.Ascending(false);
**OnCreateAppliedEntries_OnBeforeTempBankStatementMatchingBufferFindset(BankAccReconciliation,TempBankStatementMatchingBuffer,TempBankStmtMultipleMatchLine);**
        TempBankStmtMultipleMatchLine.SetCurrentKey("Due Date");

        if TempBankStatementMatchingBuffer.FindSet() then
            repeat
                BankAccReconciliationLine.Get(
                  BankAccReconciliation."Statement Type", BankAccReconciliation."Bank Account No.", BankAccReconciliation."Statement No.",
                  TempBankStatementMatchingBuffer."Line No.");

                if not StatementLineAlreadyApplied(TempBankStatementMatchingBuffer, BankAccReconciliationLine) then begin
                    PrepareLedgerEntryForApplication(BankAccReconciliationLine);
                    ApplyRecords(BankAccReconciliationLine, TempBankStatementMatchingBuffer);
                end;
            until TempBankStatementMatchingBuffer.Next() = 0;
    end;_

**[IntegrationEvent(false, false)]
    local procedure OnCreateAppliedEntries_OnBeforeTempBankStatementMatchingBufferFindset(BankAccReconciliation: Record "Bank Acc. Reconciliation"; var TempBankStatementMatchingBuffer: Record "Bank Statement Matching Buffer" temporary; var TempBankStmtMultipleMatchLine: Record "Bank Stmt Multiple Match Line" temporary)
    begin
    end;**

### Additional context

We like to change the sorting in the buffer.
Internal work item: AB#496006

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15656.
