### ISSUE TITLE
[Event Request] OnBeforeInsertLine - Procedure InsertLine, table 1249 "Bank Stmt Multiple Match Line" 

### ISSUE THREAD

**Issue by vervast** [microsoft/ALAppExtensions#25670]
### Describe the request

Please add Event on table 1249 "Bank Stmt Multiple Match Line" in procedure "InsertLine", before inserting the record:

_procedure InsertLine(TempLedgerEntryMatchingBuffer: Record "Ledger Entry Matching Buffer" temporary; LineNo: Integer; AccountType: Enum "Gen. Journal Account Type")
    begin
        "Line No." := LineNo;
        "Account Type" := AccountType.AsInteger();
        "Account No." := TempLedgerEntryMatchingBuffer."Account No.";
        "Entry No." := TempLedgerEntryMatchingBuffer."Entry No.";
        "Due Date" := TempLedgerEntryMatchingBuffer."Due Date";
        "Document No." := TempLedgerEntryMatchingBuffer."Document No.";
        **OnBeforeInsertLine(Rec,TempLedgerEntryMatchingBuffer,LineNo,AccountType);**
        Insert();
    end;_

**
[IntegrationEvent(false, false)]

    local procedure OnBeforeInsertLine(var BankStmtMultipleMatchLine: Record "Bank Stmt Multiple Match Line"; TempLedgerEntryMatchingBuffer: Record "Ledger Entry Matching Buffer" temporary; LineNo: Integer; AccountType: Enum "Gen. Journal Account Type")
    begin
    end;
**

### Additional context

We need to fill out extra fields in table for sorting.
Internal work item: AB#496005

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15656.
