### ISSUE TITLE
Codeunit 367 - CheckManagement - new OnFinancialVoidCheckOnBeforePostAccount event

### ISSUE THREAD

**Issue by rgrygoryshchak** [microsoft/ALAppExtensions#2567]
Please add new event **OnFinancialVoidCheckOnBeforePostAccount** to codeunit 367 (CheckManagement):

`LOCAL [IntegrationEvent] OnFinancialVoidCheckOnBeforePostAccount(VAR GenJournalLine : Record "Gen. Journal Line";VAR GLEntry : Record "G/L Entry")`

Usage:

**[External] FinancialVoidCheck(VAR CheckLedgEntry : Record "Check Ledger Entry")**
```
OnBeforeFinancialVoidCheck(CheckLedgEntry);

...

CASE CheckLedgEntry."Bal. Account Type" OF
  CheckLedgEntry."Bal. Account Type"::"G/L Account":
    WITH GLEntry DO BEGIN
      SETCURRENTKEY("Transaction No.");

      ...

      IF FINDSET THEN
        REPEAT
          GenJnlLine2.VALIDATE("Account No.","G/L Account No.");

          ...

          ///New Code 
          OnFinancialVoidCheckOnBeforePostAccount(GenJnlLine2,GLEntry);

          GenJnlPostLine.RunWithCheck(GenJnlLine2);
        UNTIL NEXT = 0;
    END;

```

**Comment by AlexanderYakunin** [comment]
Please use latest version of code, I cannot accept you suggestion for older versions.

**Comment by rgrygoryshchak** [comment]
Thank you. Will check when I back from holiday ;-)
