### ISSUE TITLE
[Event Request]  Codeunit "Service Line-Reserve" CreateReservation

### ISSUE THREAD

**Issue by GaryFrostick2** [microsoft/ALAppExtensions#25689]
### Describe the request

Can we add the events OnCreateReservationOnBeforeCreateReservEntry(ServiceLine, Quantity, QuantityBase, ForReservEntry, IsHandled) and OnAfterCreateReservation(ServiceLine) to the Service Line-Reserve codeunit CreateReservation to mirror the events in the "Sales Line-Reserve" codeunit

### Additional context

Consistency with Sales line-Reserve
Internal work item: AB#496592

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15512.
