### ISSUE TITLE
[Event Change] Add var to parameter of OnValidatePurchaseReferenceNoOnBeforeAssignNo

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#25686]
### Describe the request

```diff
   [IntegrationEvent(false, false)]
-   local procedure OnValidatePurchaseReferenceNoOnBeforeAssignNo(var PurchaseLine: Record "Purchase Line"; ReturnedItemReference: Record "Item Reference")
+   local procedure OnValidatePurchaseReferenceNoOnBeforeAssignNo(var PurchaseLine: Record "Purchase Line"; var ReturnedItemReference: Record "Item Reference") 
    begin
    end;
```

### Additional context

We need to transfer some state between two events (OnBeforeReferenceLookupPurchaseItem and OnValidatePurchaseReferenceNoOnBeforeAssignNo). Workaround would be to use a single instance codeunit, but we would appreciate the change to var.
Internal work item: AB#496170

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15512.
