### ISSUE TITLE
[Event Change Request] codeunit 11 - "Gen. Jnl.-Check Line" - CheckSalesDocNoIsNotUsed

### ISSUE THREAD

**Issue by achowtc** [microsoft/ALAppExtensions#25682]
### Describe the request

Can the variable OldCustLedgEntry be implemented for all regions? 

![image](https://github.com/microsoft/ALAppExtensions/assets/34691006/3161086f-dce1-41ba-8d4f-97fb0ff1b803)

### Additional context

There are apps that are created that will need to check whether the same document numbers are in the system. If this is not updated for all regions, some of the apps will not function properly. 
Internal work item: AB#496098

**Comment by AlexanderYakunin** [comment]
Which country do you have in mind? This event is the same for all countries.

**Comment by achowtc** [comment]
Sorry, we updated the app to v23 and it was resolved.
