### ISSUE TITLE
[Event Request] CopyAttachments - OnBeforeCopyAttachments

### ISSUE THREAD

**Issue by dsaveyn** [microsoft/ALAppExtensions#25688]
### Describe the request

The Document Flow Sales/Document Flow Purchase Fields are used to copy attachments to the related Sales/Purchase documents. Currently there's no easy way to deactivate this functionality. Therefore, a OnBeforeCopyAttachments for the CopyAttachments function in codeunit "Document Attachment Mgmt" would be handy. Can this be added?

Before:

```
codeunit 1173 "Document Attachment Mgmt"
{

    procedure CopyAttachments(var FromRecRef: RecordRef; var ToRecRef: RecordRef)
    var
        FromDocumentAttachment: Record "Document Attachment";
        ToDocumentAttachment: Record "Document Attachment";
        FromFieldRef: FieldRef;
        ToFieldRef: FieldRef;
        FromDocumentType: Enum "Incoming Document Type";
        FromLineNo: Integer;
        FromNo: Code[20];
        ToNo: Code[20];
        ToDocumentType: Enum "Incoming Document Type";
        ToLineNo: Integer;
    begin
        ...
    end;
```

After:

```
codeunit 1173 "Document Attachment Mgmt"
{

    procedure CopyAttachments(var FromRecRef: RecordRef; var ToRecRef: RecordRef)
    var
        FromDocumentAttachment: Record "Document Attachment";
        ToDocumentAttachment: Record "Document Attachment";
        FromFieldRef: FieldRef;
        ToFieldRef: FieldRef;
        FromDocumentType: Enum "Incoming Document Type";
        FromLineNo: Integer;
        FromNo: Code[20];
        ToNo: Code[20];
        ToDocumentType: Enum "Incoming Document Type";
        ToLineNo: Integer;
        Handled: Boolean;        
    begin
        OnBeforeCopyAttachments(FromRecRef, ToRecRef, Handled);
        if Handled then
            exit;

        ...
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCopyAttachments(var FromRecRef: RecordRef; var ToRecRef: RecordRef; var Handled: Boolean)
    begin
    end;
```

### Additional context

In our case we want to create invoices without copying the attachments since it only contains internal invoices from our POS system. The attachments here are not relevant.
Internal work item: AB#496569

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15512.
