### ISSUE TITLE
[Event Request] Codeunit 5752 "Get Source Doc. Outbound" - OnBeforeCreateWhseShipmentHeaderFromWhseRequest

### ISSUE THREAD

**Issue by ans-bar-bm** [microsoft/ALAppExtensions#25685]
### Describe the request

Not sure if this is the right place / issue template to report this, but as it is basically a problem with the event parameter i figured it's the best fit.

The `OnBeforeCreateWhseShipmentHeaderFromWhseRequest` currently has the parameter `GetSourceDocuments` by reference (`var`), indicating that changes to the variable should be possible.
However, shortly after the event is called, this variable is cleared: `Clear(GetSourceDocuments);`
As such, any changes to the variable set in the event are lost.

Would it be possible to i.e. move the clearing of the variable before the event publisher, such that changed values are retained?
Or some other solution to this problem if moving the clearing is not possible (a new event, etc.)?

Before:
```
IsHandled := false;
OnBeforeCreateWhseShipmentHeaderFromWhseRequest(WarehouseRequest, Result, IsHandled, GetSourceDocuments);
if IsHandled then
    exit(Result);

if WarehouseRequest.IsEmpty() then
    exit(false);

Clear(GetSourceDocuments);
GetSourceDocuments.UseRequestPage(false);
[...]
OnAfterCreateWhseShipmentHeaderFromWhseRequest(WarehouseRequest, WhseShptHeader);
```
After:
```
Clear(GetSourceDocuments);
IsHandled := false;
OnBeforeCreateWhseShipmentHeaderFromWhseRequest(WarehouseRequest, Result, IsHandled, GetSourceDocuments);
if IsHandled then
    exit(Result);

if WarehouseRequest.IsEmpty() then
    exit(false);

GetSourceDocuments.UseRequestPage(false);
[...]
OnAfterCreateWhseShipmentHeaderFromWhseRequest(WarehouseRequest, WhseShptHeader);
```

### Additional context

We want to set a parameter for this report variable, which currently is not possible (other than handling the entire event - loosing the `OnAfterCreateWhseShipmentHeaderFromWhseRequest` event call where other apps might be subscribed).
Internal work item: AB#496147

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15656.
