### ISSUE TITLE
Codeunit 2675 "Allocation Account Mgt." -  GenerateVariableAllocationLines - Add "AllocationLineOnAfterInsert"

### ISSUE THREAD

**Issue by LeegeorgeH** [microsoft/ALAppExtensions#25681]
### Describe the request

Would like the event adding so that We can copy custom values from the allocation distribution record to the allocation Line record.

### Additional context

Need to pass in custom fields to the allocation line so that these can be passed on the the Created purchase Lines
Internal work item: AB#496136

**Comment by JakovljevicDusan** [comment]
Hi @LeegeorgeH,

To avoid misunderstanding, please specify parameters of event publisher.
Something like https://github.com/microsoft/ALAppExtensions/issues/25679

**Comment by LeegeorgeH** [comment]
I was looking for something like this to subscribe to:

[IntegrationEvent(false, false)]
Local procedure OnAfterInsertVariableAllocationLine(var AllocationLine: Record "Allocation Line"; var AllocAccountDistibution: Record "Alloc. Account Distribution")
begin
end

called from GenerateVariableAllocationLines

    repeat
        AllocationLine."Allocation Account No." := AllocAccountDistribution."Allocation Account No.";
        AllocationLine."Line No." += 10000;
        AllocationLine."Destination Account Type" := AllocAccountDistribution."Destination Account Type";
        AllocationLine."Destination Account Number" := AllocAccountDistribution."Destination Account Number";
        AllocationLine."Destination Account Name" := AllocAccountDistribution.LookupDistributionAccountName();
        AllocationLine.Percentage := AllocAccountDistribution.Percent;
        AllocationLine.Amount := Round(AllocationLine.Percentage * AmountToDistribute / 100, AmountRoundingPercision);
        AllocatedAmount += AllocationLine.Amount;
        AllocationLine."Dimension Set ID" := AllocAccountDistribution."Dimension Set ID";
        AllocationLine."Global Dimension 1 Code" := AllocAccountDistribution."Global Dimension 1 Code";
        AllocationLine."Global Dimension 2 Code" := AllocAccountDistribution."Global Dimension 2 Code";
        CombineDimensionSetIds(ExistingDimensionSetId, AllocationLine);

        AllocationLine.Insert();
       
      **//Insert Here           
       OnAfterInsertVariableAllocationLine(AllocationLine,AllocAccountDistribution);**

    until AllocAccountDistribution.Next() = 0;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15656.
