### ISSUE TITLE
[Event Request] Table 339  "Item Application Entry" add event in SetInboundToUpdated

### ISSUE THREAD

**Issue by AmirandaLopez** [microsoft/ALAppExtensions#25683]
### Describe the request

Hi ALAppExtensions team.

We need a new event to add filters in SetInboundToUpdated procedure.

New Code:

```
procedure SetInboundToUpdated(ItemLedgEntry: Record "Item Ledger Entry")
var
        ItemApplnEntry: Record "Item Application Entry";
begin
        // >>>> New >>>>>>>>>>>>>>>>
        OnBeforeFilterItemApplicationEntry(ItemApplnEntry);
        // <<<< New <<<<<<<<<<<<<<<<
        ItemApplnEntry.SetRange("Outbound Item Entry No.", ItemLedgEntry."Entry No.");
        if ItemLedgEntry."Completely Invoiced" then
            if ItemApplnEntry.Count = 1 then begin
                ItemApplnEntry.FindFirst();
                ItemApplnEntry."Outbound Entry is Updated" := true;
                ItemApplnEntry.Modify();
            end;
    end;

[IntegrationEvent(false, false)]
local procedure OnBeforeFilterItemApplicationEntry(var ItemApplicationEntry : Record "Item Application Entry")
begin
end;
```

Thanks!

### Additional context

We need add new filters in this procedure
Internal work item: AB#496148

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15512.
