### ISSUE TITLE
[Event Request] Table 5900 - Service Header - OnAfterSetCustomerFromFilter

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#25693]
### Describe the request

Dear ALAppExtensions team,

Through this issue we would like to request event `OnAfterSetCustomerFromFilter` to be added to table "Service Header" with the following signature:

```al
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetCustomerFromFilter(var ServiceHeader: Record "Service Header")
    begin
    end;
```

which would be called as follows from procedure `SetCustomerFromFilter`:

```al
    procedure SetCustomerFromFilter()
    var
        CustomerNo: Code[20];
    begin
        CustomerNo := GetFilterCustNo();
        if CustomerNo = '' then begin
            FilterGroup(2);
            CustomerNo := GetFilterCustNo();
            FilterGroup(0);
        end;
        if CustomerNo <> '' then
            Validate("Customer No.", CustomerNo);
            
        OnAfterSetCustomerFromFilter(Rec);
    end;
 ```

### Additional context

For sales and purchase documents we can already do additional initialization when a document is created from the Customer/Vendor card, but for service documents the appropriate event publisher is missing.

Similarly to how there is an `"Sales Header".OnAfterSetSellToCustomerFromFilter` and `"Purchase Header".OnAfterSetBuyFromVendorFromFilter` we should therefore also have a `"Service Header".OnAfterSetCustomerFromFilter` event publisher.
Internal work item: AB#496594

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15512.
