### ISSUE TITLE
Event Request - Table 900 Assembly Header - CreateDim procedure

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#25695]
### Describe the request

Hello, we would like to request an event in the Assembly Header table, Create Dim procedure to support some of our additional processing of dimension values.  Thank you!

```
....
table 900 "Assembly Header"
....
    procedure CreateDim(DefaultDimSource: List of [Dictionary of [Integer, Code[20]]])
    var
        SourceCodeSetup: Record "Source Code Setup";
        DimMgt: Codeunit DimensionManagement;
        IsHandled: Boolean; // << New var
    begin
        //New Event code begin
        IsHandled := false;
        OnCreateDimBeforeDimensionSetID(Rec, CurrFieldNo, DefaultDimSource, IsHandled);
        if IsHandled then
            exit;
        //New event code end

        SourceCodeSetup.Get();

        "Shortcut Dimension 1 Code" := '';
        "Shortcut Dimension 2 Code" := '';
....

    //new event definition begin
    [IntegrationEvent(false, false)]
    local procedure OnCreateDimBeforeDimensionSetID(var AssemblyHeader: Record "Assembly Header"; CallingFieldNo: Integer; DefaultDimSource: List of [Dictionary of [Integer, Code[20]]]; var IsHandled: Boolean);
    begin
    end;
    //new event definition end
}

```

### Additional context

We have made requests for this type of event before, we just missed requesting it for this table.
Internal work item: AB#496595

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15512.
