### ISSUE TITLE
[Bug]: OnPrem - Sending EMails from JobTasks [RunOnClient] and the OutlookMessageFactory

### ISSUE THREAD

**Issue by wisa1** [microsoft/ALAppExtensions#25691]
### Describe the issue

Half-Bug / Half-Question

Testing On-Prem: BC23.1

Create a To-Do for an existing Object, and add Some Contacts/Salespeople. Navigate to the Page "Attendee Schedule" and try to send out Invitations. 
AlDotnetNotAllowedException when sending E-Mail Appointments from Page 5197 "Attendee Scheduling".
![image](https://github.com/microsoft/ALAppExtensions/assets/19393084/7e8d5518-04ca-4321-9157-5b345e452066)

Is the OutlookMessageFactory actually supposed to be run on the client? - see Screenshot below.
I have tried this with an old BC19 database and the same error occurs. 
Am i missing some setup that I am not aware of, or is this obsolete code from the WinClient-days. 

### Expected behavior

Invitations are sent, or a meaningful error is displayed.

### Steps to reproduce

Create a To-Do for an existing Object, and add Some Contacts/Salespeople. Navigate to the Page "Attendee Schedule" and try to send out Invitations. 

### Additional context

![image](https://github.com/microsoft/ALAppExtensions/assets/19393084/563c0ca5-21df-4f49-82cb-928912a20b4b)

**Comment by JesperSchulz** [comment]
That sounds like a product defect! Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the 1st party Business Central apps. We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
