### ISSUE TITLE
[Event Request] Codeunit 1303, OnBeforeInsertSalesHeaderFromCreateCopyDocument#

### ISSUE THREAD

**Issue by GOBEG** [microsoft/ALAppExtensions#2569]
Dear ALAppExtensions team,

when we call the Standard function "Create Corrective Credit Memo" from a posted Sales invoice, we need the new credit Memo number to be drawn from a custom No. Series if the Sales Invoice Header contains specific information. 

Therefore we need a publisher OnBeforeInsertSalesHeader in the local function CreateCopyDocument with the following Information

Required Information: Sales Invoice Header and (var) Sales Header

**Comment by AlexanderYakunin** [comment]
This is already implemented
