### ISSUE TITLE
[Event Request] codeunit 1255 "Match Bank Payments" - OnMatchEntriesOnAfterCalcTotalTimeDocumentNoMatching - AddDocumentMatchedInfoText

### ISSUE THREAD

**Issue by vervast** [microsoft/ALAppExtensions#25694]
### Describe the request

Please add parameter "DocumentMatchedInfoText" To existing Event 'OnMatchEntriesOnAfterCalcTotalTimeDocumentNoMatching" in codeunit 1255 "Match Bank Payments".

` 
[IntegrationEvent(false, false)]
    local procedure OnMatchEntriesOnAfterCalcTotalTimeDocumentNoMatching(var BankPmtApplRule: Record "Bank Pmt. Appl. Rule"; BankAccReconciliationLine: Record "Bank Acc. Reconciliation Line"; TempLedgerEntryMatchingBuffer: Record "Ledger Entry Matching Buffer" temporary; AccountType: Enum "Gen. Journal Account Type"; TempBankStatementMatchingBuffer: Record "Bank Statement Matching Buffer" temporary; var TotalTimeRelatedPartyMatching: Duration; var TotalTimeAmountMatching: Duration; var RemainingAmount: Decimal; var RelatedPartyMatchedInfoText: Text; LogInfoText: Boolean; var TotalTimeStringNearness: Duration; UsePaymentDiscounts: Boolean; OneToManyTempBankStatementMatchingBuffer: Record "Bank Statement Matching Buffer" temporary; var TempCustomerLedgerEntryMatchingBuffer: Record "Ledger Entry Matching Buffer" temporary; var TempVendorLedgerEntryMatchingBuffer: Record "Ledger Entry Matching Buffer" temporary; var TempEmployeeLedgerEntryMatchingBuffer: Record "Ledger Entry Matching Buffer" temporary; var TempBankAccLedgerEntryMatchingBuffer: Record "Ledger Entry Matching Buffer" temporary; var DocumentMatchedInfoText: Text; var IsHandled: Boolean)
    begin
    end;
`

### Additional context

Set MatchedDocument text on extra matching
Internal work item: AB#496596

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15656.
