### ISSUE TITLE
[Request for External] Report 11703 "Accounting Sheets CZL" - protected var GroupGLAccounts

### ISSUE THREAD

**Issue by jlorenc01** [microsoft/ALAppExtensions#25702]
### Describe the request

Hello,

could you please change the access scope of the variable GroupGLAccounts to protected? We need to change the value of this variable in our extension. Thank you.

### Additional context

We need to change the value of this variable in our extension.
Internal work item: AB#496820

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15718.
