### ISSUE TITLE
[Event Change Request] Codeunit 13 "Gen. Jnl.-Post Batch" - OnAfterPostGenJournalLine

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#25707]
### Describe the request

Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnAfterPostGenJournalLine' to be changed in procedure 'PostGenJournalLine' in codeunit 13 "Gen. Jnl.-Post Batch".
````
    local procedure PostGenJournalLine(var GenJournalLine: Record "Gen. Journal Line"; CurrentICPartner: Code[20]; ICTransactionNo: Integer) Result: Boolean
    var
        IsPosted: Boolean;
        SavedPostingDate: Date;
        SavedVATReportingDate: Date;
    begin
        with GenJournalLine do begin
            if NeedCheckZeroAmount() and (Amount = 0) and IsRecurring() then
                exit(false);
.
.
.
            PostAllocations(GenJournalLine, false);
        end;
        Result := true;
        //OnAfterPostGenJournalLine(GenJournalLine, Result); //old
        OnAfterPostGenJournalLine(GenJournalLine, Result, GenJnlPostLine); //new
    end;
````
````
    [IntegrationEvent(false, false)]
    //local procedure OnAfterPostGenJournalLine(var GenJournalLine: Record "Gen. Journal Line"; var Result: Boolean) //old
    local procedure OnAfterPostGenJournalLine(var GenJournalLine: Record "Gen. Journal Line"; var Result: Boolean; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line") //new
    begin
    end;
````

### Additional context

We need to post some extra general journal lines in the event subscriber of OnAfterPostGenJournalLine. Therefore we need the instance of codeunit "Gen. Jnl.-Post Line" that is used in "Gen. Jnl.-Post Batch".
Internal work item: AB#496845

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15512.
