### ISSUE TITLE
[Event Change Request] Codeunit 13 "Gen. Jnl.-Post Batch" - OnAfterPostAllocations

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#25705]
### Describe the request

Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnAfterPostAllocations' to be changed in procedure 'PostAllocations' in codeunit 13 "Gen. Jnl.-Post Batch".
````
    local procedure PostAllocations(var AllocateGenJnlLine: Record "Gen. Journal Line"; Reversing: Boolean)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePostAllocations(AllocateGenJnlLine, Reversing, IsHandled);
        if IsHandled then
            exit;

        with AllocateGenJnlLine do
            if "Account No." <> '' then begin
.
.
.
           end;

        //OnAfterPostAllocations(AllocateGenJnlLine, Reversing, SuppressCommit); //old
        OnAfterPostAllocations(AllocateGenJnlLine, Reversing, SuppressCommit, GenJnlPostLine); //new
    end;
````
````
    [IntegrationEvent(false, false)]
    //local procedure OnAfterPostAllocations(GenJournalLine: Record "Gen. Journal Line"; Reversing: Boolean; CommitIsSuppressed: Boolean) //old
    local procedure OnAfterPostAllocations(GenJournalLine: Record "Gen. Journal Line"; Reversing: Boolean; CommitIsSuppressed: Boolean; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line") //new
    begin
    end;
````

### Additional context

We need to post some extra general journal lines in the event subscriber of OnAfterPostAllocations. Therefore we need the instance of codeunit "Gen. Jnl.-Post Line" that is used in "Gen. Jnl.-Post Batch".
Internal work item: AB#496843

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15512.
