### ISSUE TITLE
[Event Change Request] Codeunit 13 "Gen. Jnl.-Post Batch" - OnBeforePostGenJnlLine

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#25709]
### Describe the request

Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnBeforePostGenJnlLine' to be changed in codeunit 13 "Gen. Jnl.-Post Batch".
````
    [IntegrationEvent(false, false)]
    //[IntegrationEvent(false, false)] //old
    [IntegrationEvent(true, false)] //new
    local procedure OnBeforePostGenJnlLine(var GenJournalLine: Record "Gen. Journal Line"; CommitIsSuppressed: Boolean; var Posted: Boolean; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; var PostingGenJournalLine: Record "Gen. Journal Line")
    begin
    end;
````

### Additional context

We need to call the procedure InsertPostedGenJnlLine of "Gen. Jnl.-Post Batch" in the event subscriber of OnBeforePostGenJnlLine. The problem is that this procedure uses some global variables. Therefore we need the instance of codeunit "Gen. Jnl.-Post Batch" (=Sender).
Internal work item: AB#496848

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15512.
