### ISSUE TITLE
[Request for external] - Codeunit Peppol Management - Function GetVATScheme

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#25706]
### Describe the request

Could this be made global?
```
    local procedure GetVATScheme(CountryRegionCode: Code[10]): Text
    var
        CountryRegion: Record "Country/Region";
        CompanyInfo: Record "Company Information";
    begin
        if CountryRegionCode = '' then begin
            CompanyInfo.Get();
            CompanyInfo.TestField("Country/Region Code");
            CountryRegion.Get(CompanyInfo."Country/Region Code");
        end else
            CountryRegion.Get(CountryRegionCode);
        exit(CountryRegion."VAT Scheme");
    end;

```

### Additional context

Because then i can call this function when making changes in the peppolbiz3.0-format.
Internal work item: AB#496844

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15971.
