### ISSUE TITLE
[Bug]: Wrong German translation of field "Job Title" of table "Contact"

### ISSUE THREAD

**Issue by thomashoesel** [microsoft/ALAppExtensions#25703]
### Describe the issue

Hello, for German speakers, the translation of field "Job Title" of table 5050 "Contact" is misleading when it reads "Titel" instead of "Funktion". Please compare value 1 of Enum "Salutation Formula Name" where "Job Title" is correctly translated with "Funktion" already.

### Expected behavior

Field "Job Title" of table 5050 "Contact" should be labelled "Funktion" on all referring pages and messages.

It's made as expected here:
![image](https://github.com/microsoft/ALAppExtensions/assets/127841954/f583addf-1641-499a-8a7d-7fbaa5fa24de)

### Steps to reproduce

Open e.g. Contact Card of version: DE Business Central 23.2 (Plattform 23.0.15175.0 + Anwendung 23.2.14098.14274)

![image](https://github.com/microsoft/ALAppExtensions/assets/127841954/a016fef1-eb5c-47a5-98e2-2c599e4294ac)

### Additional context

[none]

**Comment by thomashoesel** [comment]
Better screenshot with problem:

![image](https://github.com/microsoft/ALAppExtensions/assets/127841954/c1953700-354d-4dbc-b7c4-1c5e5ada5f45)

**Comment by JesperSchulz** [comment]
This repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

But I've forwarded your issue to the translation team, who will look into your issue.

**Comment by thomashoesel** [comment]
Thanks a lot, Jesper!
