### ISSUE TITLE
[Event Request] Codeunit 31362 "Match Bank Payment CZB" - procedure FillMatchBankPaymentBufferCustomer()

### ISSUE THREAD

**Issue by jlorenc01** [microsoft/ALAppExtensions#25708]
### Describe the request

Hello,

I would like to ask for a new publisher in the codeunit 31362 "Match Bank Payment CZB", procedure FillMatchBankPaymentBufferCustomer(). We need to use additional fields from "Search Rule Line CZB" to filter customer ledger entries.

```
local procedure FillMatchBankPaymentBufferCustomer()
var
    CustomerBankAccount: Record "Customer Bank Account";
    UsePaymentDiscounts: Boolean;
begin
    ...
    OnFillMatchBankPaymentBufferCustomerOnAfterCustLedgerEntrySetFilters(CustLedgerEntry, SearchRuleLineCZB, GenJournalLine); // NEW EVENT
    if CustLedgerEntry.FindSet() then
        repeat
            TempMatchBankPaymentBufferCZB.InsertFromCustomerLedgerEntry(CustLedgerEntry, true, UsePaymentDiscounts);
        until CustLedgerEntry.Next() = 0;
end;

// NEW EVENT
[IntegrationEvent(true, false)]
local procedure OnFillMatchBankPaymentBufferCustomerOnAfterCustLedgerEntrySetFilters(var CustLedgerEntry: Record "Cust. Ledger Entry"; SearchRuleLineCZB: Record "Search Rule Line CZB"; var GenJournalLine: Record "Gen. Journal Line")
begin
end;
```

### Additional context

We need to use additional fields to filter customer ledger entries. We need to use additional fields from "Search Rule Line CZB" to filter customer ledger entries.
Internal work item: AB#496849

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15718.
