### ISSUE TITLE
[Event Request] Report 11703 "Accounting Sheets CZL" - trigger OnInitReport()

### ISSUE THREAD

**Issue by jlorenc01** [microsoft/ALAppExtensions#25701]
### Describe the request

Hello,

I would like to ask for a new publisher in the report 11703 "Accounting Sheets CZL", trigger OnInitReport(). We need to change a value of the GroupGLAccounts. Thank you.

```
trigger OnInitReport()
begin
    GroupGLAccounts := true;
    OnAfterOnInitReport(GroupGLAccounts);
end;

// NEW EVENT
[IntegrationEvent(true, false)]
local procedure OnAfterOnInitReport(var GroupGLAccounts: Boolean)
begin
end;
```

### Additional context

We need to change a value of the GroupGLAccounts.
Internal work item: AB#496821

**Comment by DavidHolusa** [comment]
@jlorenc01Hello. Is it really necessary to add this event when request [25702](https://github.com/microsoft/ALAppExtensions/issues/25702) asks for change the access scope of the variable GroupGLAccounts to protected?

**Comment by DavidHolusa** [comment]
@jlorenc01 The solution for you would be to add the InitializeRequest function (see below).

    procedure InitializeRequest(NewGroupGLAccounts: Boolean)
    begin
        GroupGLAccounts := NewGroupGLAccounts;
    end;

Is it ok for you?

**Comment by jlorenc01** [comment]
@DavidHolusa No, it is not a solution. We are talking about the action "Post and Print" on the page 51 "Purchase Invoice", it means the CU 92 "Purch.-Post + Print". After the document is posted, reports are printed via the procedure **PrintRecords(ShowRequestPage: Boolean)** defined in the table 122 "Purch. Inv. Header".
![image](https://github.com/microsoft/ALAppExtensions/assets/9115764/92b3ad05-3ec3-413d-94f8-3f9efb4393b2)

It finds all reports with the defined report usage (in our case "P.Invoice") and print reports via **Report.RunModal(ReportId, ...)**. So we do not have the report as the variable to be able to call some procedure within the report.
![image](https://github.com/microsoft/ALAppExtensions/assets/9115764/cfed83e3-23f4-4ca4-976b-65cd482595ee)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15718.
