### ISSUE TITLE
[Event Request] Codeunit 31362 "Match Bank Payment CZB" - procedure FillMatchBankPaymentBufferVendor()

### ISSUE THREAD

**Issue by jlorenc01** [microsoft/ALAppExtensions#25710]
### Describe the request

Hello,

I would like to ask for a new publisher in the codeunit 31362 "Match Bank Payment CZB", procedure FillMatchBankPaymentBufferVendor(). We need to use additional fields from "Search Rule Line CZB" to filter vendor ledger entries.

```
local procedure FillMatchBankPaymentBufferVendor()
var
    VendorBankAccount: Record "Vendor Bank Account";
    UsePaymentDiscounts: Boolean;
begin
    ...
    OnFillMatchBankPaymentBufferVendorOnAfterVendorLedgerEntrySetFilters(VendorLedgerEntry, SearchRuleLineCZB, GenJournalLine); // NEW EVENT
    if VendorLedgerEntry.FindSet() then
        repeat
            TempMatchBankPaymentBufferCZB.InsertFromVendorLedgerEntry(VendorLedgerEntry, true, UsePaymentDiscounts);
        until VendorLedgerEntry.Next() = 0;
end;

// NEW EVENT
[IntegrationEvent(true, false)]
local procedure OnFillMatchBankPaymentBufferVendorOnAfterVendorLedgerEntrySetFilters(var VendorLedgerEntry: Record "Vendor Ledger Entry"; SearchRuleLineCZB: Record "Search Rule Line CZB"; var GenJournalLine: Record "Gen. Journal Line")
begin
end;
```

### Additional context

We need to use additional fields from "Search Rule Line CZB" to filter vendor ledger entries.
Internal work item: AB#496847

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15718.
