### ISSUE TITLE
[External Reques] - Codeunit Whse.-Activity-Register - Function CheckBinContentQtyToHandle

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#25718]
### Describe the request

Could globalwarehouseactivityheader be added to this event?

```
IsHandled := false;
        OnBeforeCheckBinContentQtyToHandle(TempBinContentBuffer, BinContent, Item, IsHandled, BreakBulkQtyBaseToPlace,GlobalWhseActivHeader);
        if IsHandled then
            exit;
```

```
  [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckBinContentQtyToHandle(var TempBinContentBuffer: Record "Bin Content Buffer" temporary; var BinContent: Record "Bin Content"; Item: Record Item; var IsHandled: Boolean; BreakBulkQtyBaseToPlace: Decimal; WarehouseActivityHeader:Record "Warehouse Activity Header")
    begin
    end;
```

### Additional context

I need to check values from the activity header.
Internal work item: AB#496934

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15656.
