### ISSUE TITLE
[Bug]: report "Exchange Production BOM Item" fails when same Item No. is used more than once in the same Production BOM

### ISSUE THREAD

**Issue by yurim108** [microsoft/ALAppExtensions#25711]
### Describe the issue

Exchanging an Item in Production BOMs (using report 99001043 "Exchange Production BOM Item") fails when the same Item No. is defined on several Production BOM Lines of the same Production BOM and the option "Create New Version" is selected.

### Expected behavior

All occurences of Item No. are exchanged correctly without an error.

### Steps to reproduce

Create a Production BOM with two lines with the same No. = 1600:

![grafik](https://github.com/microsoft/ALAppExtensions/assets/70197815/263985b9-8c4a-47ec-b175-7e2c0afdc2ba)

Execute report "Exchange Production BOM Item" with the following parameters:

![grafik](https://github.com/microsoft/ALAppExtensions/assets/70197815/2e9ff43f-2fe1-475a-b5ad-299927b9af59)

Get the following error (the values might differ depending on test data):

![grafik](https://github.com/microsoft/ALAppExtensions/assets/70197815/658e1c4e-d61c-4655-b293-51178381e25e)

Suggested solution:

![grafik](https://github.com/microsoft/ALAppExtensions/assets/70197815/a5aaeb7d-e257-4e2f-a7be-13f6dd3f317a)

### Additional context

Another bug in the same report:

![grafik](https://github.com/microsoft/ALAppExtensions/assets/70197815/4a4c877f-36e6-46e1-8271-442981d348cd)

**Comment by JesperSchulz** [comment]
That could be a product defect and must hence get reported to support, to ensure it is addressed within the right SLA and in all supported versions of Business Central.

This repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).
