### ISSUE TITLE
Expose Shopify JSON on Products

### ISSUE THREAD

**Issue by eivindgiske** [microsoft/ALAppExtensions#25719]
### Describe the request

We need an event that exposes the JSON coming from Shopify to parse custom data in Shopify, and handle accordingly.

Please add an event OnAfterRetrieveShopifyProduct in "Shpfy Product API" exposing Json From Shopify with Record "Shopify Product"

### Additional context

Business case: We need to pull extra data from the Shopify Product JSON into BC.
Internal work item: AB#496932

**Comment by AndreiPanko** [comment]
Thank you for reaching out,

We don't plan to expose json files received or being sent to Shopify.
Maybe you can specify which fields or objects you need? I assume they are already requested, as what is included is defined by Graph query and what you are missing is this information stored or accessible in database.

**Comment by eivindgiske** [comment]
This specific request is about the "images" section of the product JSON. Standard connector seems to be downloading image data, not storing anything in the GQL or Shopify tables, and updating item cards directly, but we need the image URLs to forward to other external systems (namely a WMS).

Example product JSON:
'''json
 "image": {
            "id": 31338332192965,
            "alt": null,
            "position": 1,
            "product_id": 7167334645957,
            "created_at": "2022-05-13T15:16:39+02:00",
            "updated_at": "2022-05-13T15:17:05+02:00",
            "admin_graphql_api_id": "gid://shopify/ProductImage/313383965",
            "width": 2200,
            "height": 2200,
            "src": "https://cdn.shopify.com/s/files/1/1513/8164/products/80536_qt_1.png?v=165225",
            "variant_ids": []
'''

**Comment by AndreiPanko** [comment]
I see, I don't think event will work,

Product query has Image node, but it only returns image Id, no extra details.
codeunit 30146 "Shpfy GQL ProductById" implements "Shpfy IGraphQL"

        exit('{"query":"{product(id: \"gid://shopify/Product/{{ProductId}}\") {createdAt updatedAt hasOnlyDefaultVariant description(truncateAt: {{MaxLengthDescription}}) descriptionHtml onlineStorePreviewUrl onlineStoreUrl productType status tags title vendor seo{description, title} images(first: 1) {edges{node{id}}} metafields(namespace: \"Microsoft.Dynamics365.BusinessCentral\", first: 10) {edges {node {id namespace type legacyResourceId key value}}}}}"}');
    end;


This is query:
{"query":"{product(id: \"gid://shopify/Product/8815284846890\") {createdAt updatedAt hasOnlyDefaultVariant description(truncateAt: 250) descriptionHtml onlineStorePreviewUrl onlineStoreUrl productType status tags title vendor seo{description, title} **images(first: 1)** {edges{node{id}}} metafields(namespace: \"Microsoft.Dynamics365.BusinessCentral\", first: 10) {edges {node {id namespace type legacyResourceId key value}}}}}"}

And this is response:
{"data":{"product":{"createdAt":"2023-12-12T13:27:57Z","updatedAt":"2024-01-16T17:06:05Z","hasOnlyDefaultVariant":false,"description":"1","descriptionHtml":"1","onlineStorePreviewUrl":"https://andreipa-teststore2.myshopify.com/products/00-images","onlineStoreUrl":null,"productType":"","status":"ACTIVE","tags":[],"title":"00-Images","vendor":"andreipa-teststore3","seo":{"description":null,"title":null},"i**mages":{"edges":[{"node":{"id":"gid://shopify/ProductImage/43467648303402"}}]**},"metafields":{"edges":[]}}},"extensions":{"cost":{"requestedQueryCost":17,"actualQueryCost":7,"throttleStatus":{"maximumAvailable":2000.0,"currentlyAvailable":1993,"restoreRate":100.0}}}} 


As you can see it only contains ID. 

The actual image info is processed separately via image sync logic.

I suggest looking at     local procedure ImportImages() in codeunit 30184 "Shpfy Sync Product Image"

Maybe you need event there
