### ISSUE TITLE
[Extension Request] Page 6550 "Document Line Tracking"

### ISSUE THREAD

**Issue by thomashoesel** [microsoft/ALAppExtensions#25713]
### Describe the request

Page 6550 "Document Line Tracking" (formerly NAVDACH page ID 5005399 Document Lines Tracking) needs several event publishers in order to enable either standard business cases not covered yet (e.g. correction credit memo for sales sales invoice without return order) or customer specific documents.

Therefore we suggest at least to changes or add:
 - make variable SourceDocType an Enum to extend it with more document types
 - functions FindRecords, AssignLineFieldFromDocument() und ShowRecords() should each provide an event at the end of its CASE block (to handle some more document types):
 
    OnFindRecordsAfterCase(SourceDocNo: Code[20], SourceDocLineNo: Integer, SourceDocBlanketOrderNo: Code[20], SourceDocBlanketOrderLineNo: Integer, var TempDocumentEntry: Record "Document Entry" temporary)

    OnAssignLineFieldFromDocumentAfterCase(var DocType: Text[30]; var DocNo: Code[20]; var DocArchive: Text[30]; var DocLineType: Text[30]; var DocLineItemNo: Code[20]; var DocLineDescription: Text[100]; var DocLineQuantity: Decimal; var DocLineUnit: Code[10])

    OnShowRecordsAfterCase(TempDocumentEntry: Record "Document Entry" temporary)
    
 - procedures FindRecordsRelatedToSalesOrder, FindRecordsRelatedToPurchaseOrder, FindRecordsRelatedToSalesReturnOrder should have an event at the end to show correction credit memos and prepayment docs:
 
    OnFindRecordsRelatedToSalesOrderFindAdditionalDocuments(DocNo: Code[20]; DocLineNo: Integer, var TempDocumentEntry: Record "Document Entry" temporary)
    OnFindRecordsRelatedToPurchaseOrderFindAdditionalDocuments(DocNo: Code[20]; DocLineNo: Integer, var TempDocumentEntry: Record "Document Entry" temporary)

   OnFindRecordsRelatedToSalesReturnOrderFindAdditionalDocuments(DocNo: Code[20]; DocLineNo: Integer, var TempDocumentEntry: Record "Document Entry" temporary)

### Additional context

[everything described above]
Internal work item: AB#496877

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15565.
