### ISSUE TITLE
[Bug]: Codeunit 9852 Assignment of Code[30] to Code[20] Permission Conflicts Overview

### ISSUE THREAD

**Issue by KuMs2019** [microsoft/ALAppExtensions#25712]
### Describe the issue

Table 5555 "Permission Conflicts Overview" has field: field(1; PermissionSetID; Code[20])
Table 2000000250 "Metadata Permission Set" has field: "Role ID"; Code[30].

In Codeunit 9852 "Effective Permissions Mgt." field with Code[30] is assigned to field with Code[20] in line 184.
![image](https://github.com/microsoft/ALAppExtensions/assets/132908770/e139a55c-de43-4662-99f8-53ac1b712f65)

This leads to an error e.g. by opening page "Permission Conflicts Overview".

### Expected behavior

Page should be opened, even if the field is filled with more than 20 characters.

### Steps to reproduce

Open Page 9802 "Permission Sets", use Action "Show Permission Conflicts Overview".

### Additional context

![image](https://github.com/microsoft/ALAppExtensions/assets/132908770/e139a55c-de43-4662-99f8-53ac1b712f65)

**Comment by pri-kise** [comment]
@KuMs2019 do you have an example for an permissionset with this error?

**Comment by KuMs2019** [comment]
Hello!
I think, when opening the page, all permission sets are checked and handled.
The first error is in this line with following variables:

![image](https://github.com/microsoft/ALAppExtensions/assets/132908770/3038836d-753f-4cf9-937e-4109f69a3241)

**Comment by pri-kise** [comment]
I created a support request, since we have the same issue for our BC SaaS customer that use BC23.2

@KuMs2019 if a customer is impacted then you should create a support request via the common support channels.

This repository is onyl for extensibility requests not for Bug Reports.

**Comment by KuMs2019** [comment]
Ok, sorry, will do my best next time.

**Comment by JesperSchulz** [comment]
@pri-kise, thanks for creating a support request. The repository is indeed only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps), hence closing issue.
