### ISSUE TITLE
[Request-for-External]Table 5900 Service Header/5965 Service Contract Header procedure SetSalespersonCode

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/ALAppExtensions#25717]
### Describe the request

Please make in table 5900 Service Header as well in Table 5965 Service Contact Header the procedure SetSalespersonCode a global procedure just like in the Table 36 Sales Header

### Additional context

If you want to change from where you set the Salesperson Code you would need this procedure as global just like in the sales.
Internal work item: AB#496896

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15971.
