### ISSUE TITLE
[Event Request] Table Payment Application Proposal - OnAfterCreateBankStmtMatchingBuffer

### ISSUE THREAD

**Issue by tkroes** [microsoft/ALAppExtensions#25723]
### Describe the request

An event at the end of the procedure `CreateFromBankStmtMacthingBuffer` on table 1293 "Payment Application Proposal" in order to be able to transfer more information from the matching buffer to the resulting proposal line.

### Additional context

We are trying to create ways to fetch payment proposals using other fields from existing data sources, e.g. creating a Customer Posting Group account type and matching the values in the customer ledger entries that are already being fetched by the system with the account no. set to the relevant posting group. The idea was to transfer this field from the customer ledger entry to the Ledger Entry Matching Buffer and then over to the Payment Application Proposal record, and then change the filter in the OnOpenPageEvent for the Payment Application page in order to change the filter to the new field containing the posting group in order to show the relevant entries, but there is currently no place with an event available where we can add fields to the Payment Application Proposal record during transfer of data from the Ledger Entry Matching Buffer.
Internal work item: AB#496945

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15656.
