### ISSUE TITLE
Business Central Reports Add a Foreign Currency Exchange Rates

### ISSUE THREAD

**Issue by salamehelie** [microsoft/ALAppExtensions#25724]
### Describe the request

Dears,

Kindly advice if there is a way to use the operation date current exchange rate value inside the invoice reports as we have received a mandatory requirement from finance ministry to add the Currency exchange rate of the operation day vs the LCY currency on all invoices.

is this something that can be done from the data set? or is it possible that it is already available there in the sales reports but for some reason I couldn't find it?

if you can help me shed some light on this topic I would really appreciate it

if it is something that requires manual coding or addition to our report code I would really like to have some assistance if possible on how to do it. 

thank you in advance,

best regards,

Elie

### Additional context

we have requirements from our ministry of finance when declaring our invoice using foreign currencies for external companies to declare also the exchange rates used on the operation date with it as well, as we are having a lot of fluctuation in our exchange rates in the Lebanese market and now we are forced to do it in this manner.

**Comment by pri-kise** [comment]
For regulatory requirements please use the shortlink : https://aka.ms/BCAlerts

@altotovi 
See: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/readiness/readiness-ready-to-go#latest-release-and-updates

This repository is only for extensibility requests (and improvements for First-Party Apps, that aren't moved to the BCApps repository and where you'd like to contribute something by yourself)

**Comment by altotovi** [comment]
I see this. This is alerting for new regulatory features from partners

/Totovic

**Comment by JesperSchulz** [comment]
Issue seems to be tracked, hence closing.

This repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).
