### ISSUE TITLE
[Event Request] Report 13630/13631 "OIOUBL-Create Elec. Invoices"/"OIOUBL-Create Elec. Cr. Memos"  skip Succesfully Messsage

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#25726]
### Describe the request

We would like an event to be able to skip this Message upon OnPostDataItem  for both Report 13630 "OIOUBL-Create Elec. Invoices"  and 13631 "OIOUBL-Create Elec. Cr. Memos"  The Event should be added in both report.

Suggestion: 
```
report 13630 "OIOUBL-Create Elec. Invoices"
{

            trigger OnPostDataItem();
            begin
           OnAfterCreateElectronicInvoice(SkipMessage);
          if not SkipMessage then
                MESSAGE(SuccessMsg, Counter);
            end;

      SuccessMsg: Label 'Successfully created %1 electronic invoice(s).', Comment = '%1 = amount of electronic invoices created';
```

```
report 13631 "OIOUBL-Create Elec. Cr. Memos"
{
            trigger OnPostDataItem();
            begin
            OnAfterCreateElectronicCrMemo(SkipMessage);
            if not SkipMessage then
                MESSAGE(SuccessMsg, Counter);
            end;
      SuccessMsg: Label 'Successfully created %1 electronic cr. Memo(s).', Comment = '%1 = amount of electronic cr. Memos created';
```

### Additional context

We have an extension that can send electronic Invoice Directly to Sproom API and it is tedious to press okey for each document that are sent if the customer are using batch posting, A boolean field is already updated on the document that an electronic invoice has been created which should be enough info.
Internal work item: [AB#496985](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/496985)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17376.
