### ISSUE TITLE
[Event Request] Table330: Add publisher "OnExchangeRateOnAfterSetRelationalExchRateAmount"

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#25725]
### Describe the request

Hi team,
On Table 330-Currency Exchange Rate, funtion ExchangeRate. I would like to add publisher OnExchangeRateOnAfterSetRelationalExchRateAmount after assignment "Relational Exch. Rate Amount" value.
So that I can control the exchange rate follow my specific rule.

![image](https://github.com/microsoft/ALAppExtensions/assets/91654106/3c31db3b-517d-4301-9ef4-f1f5e5dead5a)

Thank you in advance.

### Additional context

My business don't follow the standard role so I need to customize 
Internal work item: AB#496986

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15680.
