### ISSUE TITLE
[Bug]: codeunit 22 "Item Jnl.-Post Line", procedure SetupSplitJnlLine

### ISSUE THREAD

**Issue by DParkerRSM** [microsoft/ALAppExtensions#25738]
### Describe the issue

When using an item tracking code if you setup that the expiration date is required and want to allow BC to calculate the expiration date based on the expiration date calculation you get an error that the expiration date is missing.

If you set item tracking to use expiration dates but do not put in an expiration calculation on the item then the resulting item ledger entry has no expiration date.

Require Expiration date and Expiration Calculation are not working together.

### Expected behavior

I would expect that the expiration date calculation formula would calculate an expiration date for any lot where the expiration date is not defined by the user.

I would expect an error if the expiration date is required but the item tracking lines does not have an expiration date and the item does not have an expiration calculation.

### Steps to reproduce

create a new item
Assign the LOTWHSEEXP item tracking code which requires lot numbers and expiration dates
Enter an expiration calculation of +1M
Create a new purrchase order for the item
Enter a lot number for the item but leave the expiration date blank
try to post the purchase order to receive missing expiration date error (Expiration date should really get assign from expiration calculation)

### Additional context

This happens for any positive item ledger entry. I replicated it in manufacturing output and item journal. I used a location with no warehousing functionality turned on. With current events I can do the calculation and apply the new date but felt it should be addressed in base product.

**Comment by JesperSchulz** [comment]
That could be a product defect and must hence get reported to support, to ensure it is addressed within the right SLA and in all supported versions of Business Central.

This repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).
