### ISSUE TITLE
Fields missing in Pages "Blanket Sales Order" and "Blanket Purchase Order"

### ISSUE THREAD

**Issue by PiGlic** [microsoft/ALAppExtensions#25731]
### Describe the request

I have noticed that the number of fields in the following localization does not match the W1 version. 

On Page "Blanket Purchase Order" the two Fields
- "Pay-to Country/Region Code"
- "Buy-from Country/Region Code"

On Page "Blanket Sales Order" the two Fields
- "Bill-to Country/Region Code"
-  "Sell-to Country/Region Code"

Are at least missing in the following localizations: 
ca, gb, mx, ex, us

For example, the w1 and us version with the Blankes Sales Order
[W1 Blanket Sales Order](https://github.com/StefanMaron/MSDyn365BC.Code.History/blob/w1-23/BaseApp/Source/Base%20Application/Sales/Document/BlanketSalesOrder.Page.al)

[US Blanket Sales Order](https://github.com/StefanMaron/MSDyn365BC.Code.History/blob/us-23/BaseApp/Source/Base%20Application/Sales/Document/BlanketSalesOrder.Page.al)

### Additional context

 We should have at least the W1 fields in the country localizations????
Internal work item: [AB#497352](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/497352)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18805.
