### ISSUE TITLE
[Event Request] Codeunit 8 (AccSchedManagement): Add a new event in procedure HasCostDimFilter

### ISSUE THREAD

**Issue by KlausMaxSchwab** [microsoft/ALAppExtensions#25732]
### Describe the request

I would like to request Microsoft Dynamics Business Central AL team to publish a new event with the need of handling Custom Filterfields (Record "Acc. Schedule Line") in procedure HasCostDimFilter in Codeunit 8 as shown in below code snippet which is requested as a new event with the tags // NEW EVENT and also attaching the further details for the requirement at the end of this request. 

Many thanks.

![image](https://github.com/microsoft/ALAppExtensions/assets/136571688/e7743459-7137-435c-ad77-8c6bc2aed952)

-----------------------------------

![image](https://github.com/microsoft/ALAppExtensions/assets/136571688/e071b524-0cec-46ed-80f9-5ea36e98654b)

-----------------------------------

![image](https://github.com/microsoft/ALAppExtensions/assets/136571688/5be2bb4b-a871-43d9-a664-4c414b3cef03)

### Additional context

We need to check these Custom Field Filters too:

![image](https://github.com/microsoft/ALAppExtensions/assets/136571688/e918d524-f611-488e-b513-f88c12b0e79d)

Internal work item: AB#497044

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15656.
