### ISSUE TITLE
[Bug]: API 2.0 filtering by "In a list of values" not working i.e. /items?$filter=number in ("1000", "1001") 

### ISSUE THREAD

**Issue by etobod** [microsoft/ALAppExtensions#25734]
### Describe the issue

Using Filter Expressions in OData URIs I discovered that filtering by "in a list of values" doesn't work. Microsoft documentation provided an [example ](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/use-filter-expressions-in-odata-uris#filter-expressions)$filter=EntryNo in (610, 612, 614) but it doesn't work. You can find community posts of Yun Zhu [here ](https://community.dynamics.com/forums/thread/details/?threadid=8a0bf90f-64b0-ee11-a569-00224827e5d4) with details. The system is not reporting any error but is returning the full table without any filter applied. 

### Expected behavior

Please correct it, and make working properly as described in official documentation

### Steps to reproduce

By using Postman you can reproduce the problem with this link https://api.businesscentral.dynamics.com/v2.0/2dd50b5d-cfbd-4f7a-b067-b6f02d188f84/CRONUS/api/v2.0/companies(a3935ba2-66ca-ec11-8e7e-000d3a4c9a19)/items?$filter=number in ("1000", "1001")

### Additional context

The system is not returning any error, but is returning a full list of items without any filter applied

**Comment by JanMoller81** [comment]
I am experiencing the same thing in v.1.0

**Comment by JesperSchulz** [comment]
That could be a product defect and must hence get reported to support, to ensure it is addressed within the right SLA and in all supported versions of Business Central.

This repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

**Comment by hbunjes** [comment]
@etobod  This feature exists since April 2, 2024: https://learn.microsoft.com/en-us/dynamics365/release-plan/2024wave1/smb/dynamics365-business-central/use-odata-v4-operator-web-service-queries

Here you find more about the official support if it still does not work: https://learn.microsoft.com/en-us/dynamics365/business-central/product-help-and-support

**Comment by etobod** [comment]
Thank you! @hbunjes :)
