### ISSUE TITLE
Add procedure to codeunit 5510 "Production Journal Mgt"

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [microsoft/ALAppExtensions#25735]
### Describe the request

We would like to add the following procedure to be able to define the Journal Template Name and the Journal Batch Name. 

`
procedure SetJnlTemplateAndBatchName(TemplateName: Code[10]; BatchName: Code[10])
    begin
        ToTemplateName := TemplateName;
        ToBatchName := BatchName;
    end;
`

### Additional context

This will make the Codeunit usable for other scenarios. Not only when opening the production journal from production order line.  It will decrease the duplication of code. 
Internal work item: AB#497129

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15971.
