### ISSUE TITLE
[Event Request] Codeunit 80 "Sales-Post" add SalesHeader Record as param for event OnPostInvoiceOnBeforeBalAccountNoWindowUpdate

### ISSUE THREAD

**Issue by nicdiblasi** [microsoft/ALAppExtensions#25741]
### Describe the request

Request: 
Please add the SalesHeader variable as a parameter for event OnPostInvoiceOnBeforeBalAccountNoWindowUpdate() in codeunit 80 "Sales-Post".

### Additional context

I intend on skipping the posting of the balance account ledger entry using the event OnPostInvoiceOnBeforePostBalancingEntry(). I will do this by setting the IsHandled variable to true, if the SalesHeader contains a payment method code i'm specifically looking for. This means I need to also skip the updating of the progress dialog that occurs beforehand using the event OnPostInvoiceOnBeforeBalAccountNoWindowUpdate(). Although, I need the SalesHeader as a param for this event to check the payment method code. 

![image](https://github.com/microsoft/ALAppExtensions/assets/55171283/4dd350fe-3eaf-4988-8722-625bf363fdd5)

Can this please be added? 
Internal work item: AB#497208

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15767.
