### ISSUE TITLE
Codeunit 22 "Item Jnl.-Post Line" add event in UpdateItemApplnEntry procedure

### ISSUE THREAD

**Issue by AmirandaLopez** [microsoft/ALAppExtensions#25743]
### Describe the request

Hi ALAppExtensions team.

We need a new event to extend code in UpdateItemApplnEntry procedure.

New Code:
```
local procedure UpdateItemApplnEntry(ItemLedgEntryNo: Integer; PostingDate: Date)
var
        ItemApplnEntry: Record "Item Application Entry";
begin
        with ItemApplnEntry do begin
            SetRange("Item Ledger Entry No.", ItemLedgEntryNo);
            SetRange("Output Completely Invd. Date", 0D);
            // >>>> New >>>>>>>>>>>>>>>>
            OnAfterFilterItemApplicationEntry(ItemApplnEntry);
            // <<<< New <<<<<<<<<<<<<<<<
            if not IsEmpty() then
                ModifyAll("Output Completely Invd. Date", PostingDate);
        end;
end;

[IntegrationEvent(false,false)]
local procedure OnAfterFilterItemApplicationEntry(var ItemApplnEntry: Record "Item Application Entry")
begin
end;
```

### Additional context

We need add modifyall for another field 
Internal work item: AB#497209

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15680.
