### ISSUE TITLE
[Event Request] Codeunit 99000856 (Planning Transparency): Add a new event in procedure PublishSurplus

### ISSUE THREAD

**Issue by avneetwadhwa** [microsoft/ALAppExtensions#25748]
### Describe the request

I would like to request Microsoft Dynamics Business Central AL team to publish a new event with the need of having access of global record type variables `SupplyInvProfile, SKU, ReqLine, ReservEntry` in the `Procedure PublishSurplus` of Codeunit 99000856 as shown in the below code snippet which is requested with a new event with the tag `// NEW EVENT` and also attaching the further details for the requirement at end of this request.

Thank you!

```
procedure PublishSurplus(var SupplyInvProfile: Record "Inventory Profile"; var SKU: Record "Stockkeeping Unit"; var ReqLine: Record "Requisition Line"; var ReservEntry: Record "Reservation Entry")
begin
    ------
    ------
    ------
    TempInvProfileTrack.SetRange("Line No.");
    TempInvProfileTrack.SetRange("Warning Level");
    CleanLog(SupplyInvProfile."Line No.");
    OnAfterPublishSurplus(SupplyInvProfile, SKU, ReqLine, ReservEntry); //  NEW EVENT
    ------
    ------
    ------
end;

--------------------

// NEW EVENT
[IntegrationEvent(false, false)]
local procedure OnAfterPublishSurplus(var InventoryProfile : Record "Inventory Profile"; var StockkeepingUnit : Record "Stockkeeping Unit"; var RequisitionLine : Record "Requisition Line"; var ReservationEntry : Record "Reservation Entry")
begin
end;
```

![CU99000856_Proc_PublishSurplus_1](https://github.com/microsoft/ALAppExtensions/assets/156719646/726fe744-4a40-42e0-be77-0eabd0b72569)

### Additional context

The new event is needed to have the access for active table objects as shown in the below custom code with the tag of `// NEW CUSTOM CODE`.

```
procedure PublishSurplus(var SupplyInvProfile: Record "Inventory Profile"; var SKU: Record "Stockkeeping Unit"; var ReqLine: Record "Requisition Line"; var ReservEntry: Record "Reservation Entry")
begin
    ------
    ------
    ------
    TempInvProfileTrack.SetRange("Line No.");
    TempInvProfileTrack.SetRange("Warning Level");
    CleanLog(SupplyInvProfile."Line No.");
    ReqLine.CalculateForecastQty;   //  NEW CUSTOM CODE

    ------
    ------
    ------
end;
```
Internal work item: AB#497329

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15767.
