### ISSUE TITLE
[Bug]: Codeunit 31315 "Gen.Jnl. Post Line Handler CZL"

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#25745]
### Describe the issue

When running the report R11971 we are encountering an error message in BC23:
Sorry, the current permissions prevented the action.
(TableData 254 VAT Entry VAT Entry Delete: Core Localization Pack for Czech)

Problem raise with BC23 where is new event. Event subscriber do not have indirect permissions.

### Expected behavior

Please add permissions to codeunit 31315 "Gen.Jnl. Post Line Handler CZL"
                  TableData "G/L Entry - VAT Entry Link" = rimd,
                  TableData "VAT Entry" = Rimd,

### Steps to reproduce

Run the report R11971

### Additional context

AL call stack
"Gen.Jnl. Post Line Handler CZL"(CodeUnit 31315).DeleteSettlementReverseVATEntryOnAfterInsertVATEntry line 7 - Core Localization Pack for Czech by Microsoft
"Gen. Jnl.-Post Line"(CodeUnit 12).OnAfterInsertVATEntry(Event) line 2 - Base Application by Microsoft
"Gen. Jnl.-Post Line"(CodeUnit 12).InsertVAT line 144 - Base Application by Microsoft
"Gen. Jnl.-Post Line"(CodeUnit 12).PostVAT line 33 - Base Application by Microsoft
"Gen. Jnl.-Post Line"(CodeUnit 12).PostGLAcc line 41 - Base Application by Microsoft
"Gen. Jnl.-Post Line"(CodeUnit 12).PostGenJnlLine line 7 - Base Application by Microsoft
"Gen. Jnl.-Post Line"(CodeUnit 12).Code line 67 - Base Application by Microsoft
"Gen. Jnl.-Post Line"(CodeUnit 12).RunWithCheck line 7 - Base Application by Microsoft
"Gen. Jnl.-Post Line"(CodeUnit 12).OnRun(Trigger) line 3 - Base Application by Microsoft
"Calc. and Post VAT Settl. CZL"(Report 11971).PostGenJnlLine line 9 - Core Localization Pack for Czech by Microsoft
"Calc. and Post VAT Settl. CZL"(Report 11971)."Close VAT Entries - OnAfterGetRecord"(Trigger) line 36 - Core Localization Pack for Czech by Microsoft

**Comment by fridrichovsky** [comment]
Hello @JesperSchulz I would like ask you if you can check if this bug is in investigation/fix. This is critical problem connected with VAT and our customers ask us for solution.

**Comment by JesperSchulz** [comment]
Unfortunately this isn't the right place to log bugs with customer impact! This repo is only for extensibility related issues in the upcoming release. I suggest that you open a support case or file a bug in Collaborate, to unblock your customers as quickly as possible!

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.
