### ISSUE TITLE
[Event Request] Table 9650 - Custom Report Layout - OnCopyBuiltInLayoutFromReportLayoutLookup

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/ALAppExtensions#2574]
Dear ALAppExtensions team,

Through this event we would like to request event publisher `OnCopyBuiltInLayoutFromReportLayoutLookup` to be added to table 9650 Custom Report layout with the following signature:
```
LOCAL [IntegrationEvent] OnCopyBuiltInLayoutFromReportLayoutLookup(VAR ReportLayoutLookup : Page "Report Layout Lookup";VAR IsHandled : Boolean)
```
with a Page parameter `ReportLayoutLookup` and **VAR** parameters `IsHandled` that will allow us to leverage additional options that are added (through a page extension).

which would be called from procedure `CopyBuiltInLayout` (with a minor adjustment in the code so that it won't give the message and exit too early):
```pascal
CopyBuiltInLayout()
FILTERGROUP(4);
IF GETFILTER("Report ID") = '' THEN
  FILTERGROUP(0);
IF GETFILTER("Report ID") <> '' THEN
  IF EVALUATE(ReportID,GETFILTER("Report ID")) THEN
    ReportLayoutLookup.SetReportID(ReportID);
FILTERGROUP(0);
IF ReportLayoutLookup.RUNMODAL = ACTION::OK THEN BEGIN
  // >> OLD CODE
  // IF NOT ReportLayoutLookup.SelectedAddWordLayot AND NOT ReportLayoutLookup.SelectedAddRdlcLayot THEN BEGIN
  //   MESSAGE(NoLayoutSelectedMsg);
  //   EXIT;
  // END;
  // << OLD CODE

  IF ReportLayoutLookup.SelectedAddWordLayot THEN
    InitBuiltInLayout(ReportLayoutLookup.SelectedReportID,Type::Word);
  IF ReportLayoutLookup.SelectedAddRdlcLayot THEN
    InitBuiltInLayout(ReportLayoutLookup.SelectedReportID,Type::RDLC);

  // >> NEW CODE
  IsHandled := ReportLayoutLookup.SelectedAddRdlcLayot OR ReportLayoutLookup.SelectedAddWordLayot;
  OnCopyBuiltInLayoutFromReportLayoutLookup(ReportLayoutLookup, IsHandled);
  IF NOT IsHandled THEN
    MESSAGE(NoLayoutSelectedMsg);
  // << NEW CODE
END;
```

**Comment by AlexanderYakunin** [comment]
Page cannot be used as parameter of event. Please close this request and come up with another solution for your case.

**Comment by rvanbekkum** [comment]
You are right, my apologies. I think I changed my initial request later on to something that seemed like a better solution (using the page parameter), simply assuming this would be possible without testing it.
I will close the issue and will make an adjusted requested in a new issue.

**Comment by rvanbekkum** [comment]
I have added the new request in issue #2778.
