### ISSUE TITLE
[Request for External] Page 50 "Purchase Order" - SaveInvoiceDiscountAmount

### ISSUE THREAD

**Issue by iamcgomes** [microsoft/ALAppExtensions#25758]
### Describe the request

Could you please change the scope of the procedure **"SaveInvoiceDiscountAmount"** to protected in **Page 50 "Purchase Order""**?

Current
```AL
local procedure SaveInvoiceDiscountAmount()
var
    DocumentTotals: Codeunit "Document Totals";
begin
    CurrPage.SaveRecord();
    DocumentTotals.PurchaseRedistributeInvoiceDiscountAmountsOnDocument(Rec);
    CurrPage.Update(false);
end;
```

Requested
```AL
protected procedure SaveInvoiceDiscountAmount()
var
    DocumentTotals: Codeunit "Document Totals";
begin
    CurrPage.SaveRecord();
    DocumentTotals.PurchaseRedistributeInvoiceDiscountAmountsOnDocument(Rec);
    CurrPage.Update(false);
end;
```

### Additional context

We need to access the procedure "SaveInvoiceDiscountAmount" from the Page Extension.
Internal work item: AB#497556

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15971.
