### ISSUE TITLE
[Event Request] codeunit 12 "Gen. Jnl.-Post Line" - procedure "CreateNormalVATGLEntries"

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#25750]
### Describe the request

    local procedure CreateNormalVATGLEntries(GenJnlLine: Record "Gen. Journal Line"; VATPostingSetup: Record "VAT Posting Setup"; VATPostingParameters: Record "VAT Posting Parameters")
    var
        LastNextEntryNo: Integer;
    begin
        **//--> event request
        OnBeforeCreateNormalVATGLEntries(GenJnlLine,VATPostingSetup);
        **//<-- event request
        if VATPostingParameters."Unrealized VAT" or (VATPostingParameters."Non-Deductible VAT %" <> 100) then
            CreateGLEntry(
                GenJnlLine, VATPostingSetup.GetPurchAccount(VATPostingParameters."Unrealized VAT"),
                VATPostingParameters."Deductible VAT Amount", VATPostingParameters."Deductible VAT Amount ACY", true);
        if VATPostingParameters."Non-Deductible VAT %" <> 0 then
            if VATPostingParameters."Non-Ded. Purchase VAT Account" = '' then begin
                if GenJnlLine."Account Type" = GenJnlLine."Account Type"::"Fixed Asset" then begin
                    LastNextEntryNo := NextEntryNo;
                    CreateGLEntry(
                        GenJnlLine, GenJnlLine."FA G/L Account No.",
                        VATPostingParameters."Non-Deductible VAT Amount", VATPostingParameters."Non-Deductible VAT Amount ACY", true);
                    PostFAJnlLineWithGLEntryBufUpdate(GenJnlLine, VATPostingParameters, LastNextEntryNo);
                end else
                    CreateGLEntry(
                        GenJnlLine, GenJnlLine."Account No.",
                        VATPostingParameters."Non-Deductible VAT Amount", VATPostingParameters."Non-Deductible VAT Amount ACY", true);
            end else begin
                LastNextEntryNo := NextEntryNo;
                CreateGLEntry(
                    GenJnlLine, VATPostingParameters."Non-Ded. Purchase VAT Account",
                    VATPostingParameters."Non-Deductible VAT Amount", VATPostingParameters."Non-Deductible VAT Amount ACY", true);
                if GenJnlLine."Account Type" = GenJnlLine."Account Type"::"Fixed Asset" then
                    PostFAJnlLineWithGLEntryBufUpdate(GenJnlLine, VATPostingParameters, LastNextEntryNo);
            end;
    
        OnAfterCreateNormalVATGLEntries(GenJnlLine);
    end;

    **//--> event request VATPostingSetup parameter with var.
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateNormalVATGLEntries(GenJournalLine: Record "Gen. Journal Line"; var VATPostingSetup: Record "VAT Posting Setup")
    begin
    end;
    **//<-- event request

### Additional context

In Turkish localization, Cr. Memo document VATAccount calculation is different from Invoice document VATAccount.
Internal work item: AB#497350

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15680.
