### ISSUE TITLE
Event request codeunit 30184 "Shpfy Sync Product Image".UpdateItemImage

### ISSUE THREAD

**Issue by dagviggobyx** [microsoft/ALAppExtensions#25756]
### Describe the request

Hi, could you add OnBefore/OnAfter events for procedure "UpdateItemImage"?
![image](https://github.com/microsoft/ALAppExtensions/assets/104152494/a7dcf687-f3db-4286-89aa-f3a11639262b)

### Additional context

We need the image URLs to forward to other external systems (namely a WMS)
Internal work item: AB#497554

**Comment by onbuyuka** [comment]
Hi @dagviggobyx, if you only want to forward the URL, why do you need to both OnBefore and OnAfter? Do you also expect an IsHandled pattern to change URL/image?

**Comment by dagviggobyx** [comment]
Don't need both, just thought it was good practice, only need OnAfter (or OnBeforeModifyItem) with [var] Item, ImageUrl and InStream

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15689.
