### ISSUE TITLE
[Extensiblity Request] codeunit 30184 "Shpfy Sync Product Image" - UpdateItemImage

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#25759]
### Describe the request

We have some integrations where we need to know if the Picture of an Item has changed.

Therefore we currently subscribe to the OnModify Trigger of the Item.

```al
/// <summary> 
/// Update Item Image.
/// </summary>
/// <param name="Item">Parameter of type Record Item.</param>
/// <param name="ImageUrl">Parameter of type Text.</param>
/// <returns>Return value of type Boolean.</returns>
local procedure UpdateItemImage(Item: Record Item; ImageUrl: Text): Boolean
var
    HttpClient: HttpClient;
    HttpResponseMessage: HttpResponseMessage;
    InStream: InStream;
begin
    if HttpClient.Get(ImageUrl, HttpResponseMessage) then begin
        HttpResponseMessage.Content.ReadAs(InStream);
        Clear(Item.Picture);
        Item.Picture.ImportStream(InStream, Item.Description);
        //+Change
        //-Item.Modify();
        Item.Modify(true);
        //-Change
    end;
end;
```

Therefore I'd like to change the modify of the Item to Runtrigger= true.

### Additional context

The Actions of the `page 346 "Item Picture"` use always the RunTrigger and I don't see any good reason to not use the RunTrigger in the place above.
Internal work item: AB#497579

**Comment by JakovljevicDusan** [comment]
Related to #25756

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15664.
