### ISSUE TITLE
Pass Sales Header by reference in Event OnBeforeMessageIfSalesLinesExist - Table 36 - Sales Header

### ISSUE THREAD

**Issue by SarkeSrb** [microsoft/ALAppExtensions#25766]
### Describe the request

Current: 
```
[IntegrationEvent(false, false)]
local procedure OnBeforeMessageIfSalesLinesExist(SalesHeader: Record "Sales Header"; ChangedFieldCaption: Text; var IsHandled: Boolean)
begin
end;
```

Should be:
```
[IntegrationEvent(false, false)]
local procedure OnBeforeMessageIfSalesLinesExist(var SalesHeader: Record "Sales Header"; ChangedFieldCaption: Text; var IsHandled: Boolean)
begin
end;
```

### Additional context

Pass parameter SalesHeader: Record "Sales Header" as a reference in Event OnBeforeMessageIfSalesLinesExist - Table 36 - Sales Header It will allow modifying Sales Header by subscribing to the event. Since same subscriber in Purchase Header is already passed by reference.
Internal work item: AB#497695

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15680.
