### ISSUE TITLE
[Report] Add SaveValues = true to report 5885 "Calc. Phys. Invt. Order (Bins)"

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#25769]
### Describe the request

Please add ``SaveValues =true`` to the requestpage of report 5885 "Calc. Phys. Invt. Order (Bins)".

As of now we can not change this (or any other) property on request pages via report extensions.
```diff
report 5885 "Calc. Phys. Invt. Order (Bins)"
{
    Caption = 'Calc. Phys. Invt. Order (Bins)';
    ProcessingOnly = true;

    dataset
    {
       ...
    }

    requestpage
    {
+       SaveValues = true;

        layout
        {
            area(content)
            {
                ...
            }
       ...
```

### Additional context

Our customer does physical inventory on a daily basis and it is annoying for the end users to have to set the options for each run.
Internal work item: [AB#500375](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500375)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18805.
