### ISSUE TITLE
Table 37 "Sales Line" OnBeforeValidateUnitPrice

### ISSUE THREAD

**Issue by simona-ur** [microsoft/ALAppExtensions#25760]
Hello, would it be possible to add OnBeforeValidateUnitPrice event on field "Unit Price" in OnValidate trigger in table 37 "Sales Line", like this:

```
field(22; "Unit Price"; Decimal)
        {
            AutoFormatExpression = Rec."Currency Code";
            AutoFormatType = 2;
            CaptionClass = GetCaptionClass(FieldNo("Unit Price"));
            Caption = 'Unit Price';

            trigger OnValidate()
            begin
              IsHandled := false;
     >       OnBeforeValidateUnitPrice(Rec, CurrFieldNo, IsHandled) //New event
              if not IsHandled then
                  Validate("Line Discount %");
            end;
```

```
local procedure OnBeforeValidateUnitPrice(var SalesLine: Record "Sales Line"; CurrentFieldNo: Integer; var IsHandled: Boolean)
```

### Additional context

We need to override the trigger.
Internal work item: AB#497580

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15680.
