### ISSUE TITLE
[Bug]: ReportLayoutSelection.SetTempLayoutSelectedName() gives error "Report XXXXXXX does not have a valid layout. Valid layout types are: Word, RDLC, Excel, and Custom." when you have rendering section in report code. 

### ISSUE THREAD

**Issue by KuljitSinghParmar** [microsoft/ALAppExtensions#25761]
### Describe the issue

I am trying to use function "ReportLayoutSelection.SetTempLayoutSelectedName("Report Name") " to select the the layout before  report request page is opened.  It works fine as it set the selected layout onto the report page correctly but when you click on the "Print" button it gives error "Report XXXXXXX does not have a valid layout. Valid layout types are: Word, RDLC, Excel, and Custom" .

This only happens if in my report i add "rendering" section and add multiple layouts inside it. If i remove this section and use old  syntax "DefaultLayout"  and "RDLCLayout" , Print button works fine.

### Expected behavior

It should not give the error and print the report set by function "ReportLayoutSelection.SetTempLayoutSelectedName("Report Name"). 

### Steps to reproduce

Add the below event with the report layout which you want to select on report request page. . 

    [EventSubscriber(ObjectType::Table, Database::"Report Selections", 'OnBeforePrintDocument', '', false, false)]
    local procedure OnBeforePrintDocument(TempReportSelections: Record "Report Selections" temporary; IsGUI: Boolean; var RecVarToPrint: Variant; var IsHandled: Boolean)
    var
        ReportLayoutSelection: Record "Report Layout Selection";
    begin
        if TempReportSelections."Report ID" = 50200 then
            ReportLayoutSelection.SetTempLayoutSelectedName('Test');
    end;

Make in your report you have rendering section added with multiple layout added in it. 

 rendering
    {
        layout("CheckTest.rdlc")
        {
            Type = RDLC;
            LayoutFile = './Layout/Check.rdl';
            Caption = 'Test';
        }
        layout("Check1.rdlc")
        {
            Type = RDLC;
            LayoutFile = './Layout/Check1.rdl';
            Caption = 'Test1';
        }
    }

when you run the report , Test will be selected on the Report request page 

<img width="632" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/61985025/5297b65b-f187-4c67-b561-714639bce39f">

but when you click print button  you will get error - 

<img width="391" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/61985025/06b9577d-c10a-48b9-be65-0f460d354324">

### Additional context

<img width="391" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/61985025/090ac213-08c2-4869-832c-69fe9feb2eca">

**Comment by BardurKnudsen** [comment]
Did you also try with ReportLayoutSelection.SetTempLayoutSelectedName('CheckTest.rdlc'); ?

**Comment by KuljitSinghParmar** [comment]
> Did you also try with ReportLayoutSelection.SetTempLayoutSelectedName('CheckTest.rdlc'); ?

same error 

![image](https://github.com/microsoft/ALAppExtensions/assets/61985025/b68b6ec3-60ff-41f1-a13c-d45c13f16b5e)
![image](https://github.com/microsoft/ALAppExtensions/assets/61985025/fa62b5c0-c2cf-4c72-a308-f51481ee6a7e)

**Comment by KuljitSinghParmar** [comment]
> > Did you also try with ReportLayoutSelection.SetTempLayoutSelectedName('CheckTest.rdlc'); ?
> 
> I think it worked . Thanks . will do more testing and if any issues other will let you know .

its working now . thanks i will close the ticket.
