### ISSUE TITLE
[Bug]: Global Field Not Populating via OnOpenPage Trigger on a page using Temporary Table

### ISSUE THREAD

**Issue by yannstlo** [microsoft/ALAppExtensions#25768]
### Describe the issue

I created a new page where the SourceTable is a temporary table. 
I added a field on the page which is bound to a Global Var on the page.
I am trying to populate the Global var so that the field displays the value.
When the page opens, the field is blank.

### Expected behavior

The field should be populated with the value that I being passed to it in the OnOpenPage trigger.

### Steps to reproduce

In the example below the SourceTable I'm using is defined as temporary. 

`
page 50112 PageName
{
    PageType = List;
    ApplicationArea = All;
    UsageCategory = Lists;
    SourceTable = [A TEMPORARY TABLE];
    SourceTableTemporary = true;

    layout
    {
        area(Content)
        {
            field("Start Date"; StartDate)
            {
                ApplicationArea = All;
                Caption = 'Start Date';
                ToolTip = 'Start Date';
            }
        }
        area(Factboxes)
        {

        }
    }

    trigger OnOpenPage();
    var
    begin
        StartDate := CalcDate('<-CM>');
    end;

    var
        StartDate: Date;
}
`

### Additional context

I've tried the exact same code but using the Customer Table without the SourceTableTemporary = true and it works as expected.

**Comment by yannstlo** [comment]
After doing further tests, I discovered that this is related to the table being empty. 
I'm not sure if this is by design so I will leave the ticket open for now.

Thanks
Yann

**Comment by pri-kise** [comment]
This is the wrong place for such issues.

This repository is meant only for Event/Extensibility Requests.

If you aren't sure if this is a bug, then use https://aka.ms/BCYammer for such topics.

**Comment by JesperSchulz** [comment]
It this is a product defect, it must get reported to support, to ensure it is addressed within the right SLA and in all supported versions of Business Central.

This repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).
