### ISSUE TITLE
Event Request codeunit 80 "Sales-Post" OnValidatePostingAndDocumentDateOnBeforeSalesHeaderModify

### ISSUE THREAD

**Issue by Pieterheinevdm** [microsoft/ALAppExtensions#25764]
### Describe the request

can the event below be added?

[IntegrationEvent(false, false)]
local procedure OnValidatePostingAndDocumentDateOnBeforeSalesHeaderModify(var SalesHeader: Record "Sales Header"; var ModifyHeader: Boolean)
begin
end;
    
This event should be called from procedure ValidatePostingAndDocumentDate just before if ModifyHeader then SalesHeader.Modify();
    
OnValidatePostingAndDocumentDateOnBeforeSalesHeaderModify(SalesHeader, ModifyHeader);
if ModifyHeader then
  SalesHeader.Modify();

### Additional context

same event as in codeunit 90
Internal work item: AB#497673

**Comment by Pieterheinevdm** [comment]
![image](https://github.com/microsoft/ALAppExtensions/assets/16033297/71815d27-6343-4606-9968-88c44d8233ff)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15767.
