### ISSUE TITLE
[Bug]: AL Test Tool

### ISSUE THREAD

**Issue by ManDaGmbH-MDuda** [microsoft/ALAppExtensions#25763]
### Describe the issue

Dear Colleguess I have wery strange behavion on AppTestTool.

 

I created a App and I can open Manualy. If I use AL Test Tool then I get a error 

 
![Screenshot 2024-01-23 094009](https://github.com/microsoft/ALAppExtensions/assets/146007344/770d246a-4f0d-4981-b3a9-e680d3e7ee8b)

I am a super user (it exist just one Super user with DEV Lizense).

Code that I use (snip).

 
![Screenshot 2024-01-23 094102](https://github.com/microsoft/ALAppExtensions/assets/146007344/5543e033-8235-4b4c-9ed3-bc16a77ae708)

the same issue i have if I try to Open a setup Page in setup Page OnOpenPage trigger is standard code

If not get then 
insert;

 

have some one the solution?

### Expected behavior

It creates a Test Data without permision Error

### Steps to reproduce

I do not know what creates theis error

### Additional context

I do not have futher Information

**Comment by ManDaGmbH-MDuda** [comment]
Problem found, but no one mention this
TestPermissions = Disabled;

**Comment by JesperSchulz** [comment]
Glad you found a solution. Going forward, please use Viva Engage for such questions, as this repository only is for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).
