### ISSUE TITLE
[BC Idea]: Allocation Accounts on Invoices using Get Receipt Lines and Purchase Receipts

### ISSUE THREAD

**Issue by KristofVervaeke** [microsoft/ALAppExtensions#25762]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=af053a8d-e3b5-ee11-92bd-000d3a0f8799

### Description

Hi,

We have a problem with allocation accounts on invoices using "Get Receipt Lines".
Here are the steps to reproduce the problem we are facing.

- Create a purchase order witha G/L account. Do not enter an cost accounting account no.
- Receive this purchase order
- Create a purchase  invoice and get the purchase receipt lines of the order by using "Get Receipt Lines".
- Now enter a allocation account no. on the invoice line.
 
If you release this invoice and try to post it, you get a error that the invoice must be open.
If you leave the inovice open, and try to post it, you get the error that the receipt no. must be blank.

So you can never post an invoice from a purhase receipt.
Can this be fixed, please?

Kind regards.

**Comment by AlexanderYakunin** [comment]
@nikolakukrika - for your attention

**Comment by nikolakukrika** [comment]
Opened a bug to investigate and potentially fix this issue.
We have implemented a new functionality on the allocation accounts for 23.4. It will be possible to split the line on the purchase invoice, so you can modify each of the lines as you like
