### ISSUE TITLE
[event request] for table "Item Journal Line", Quantity_OnValidate: OnBeforeCheckSerialNoQty

### ISSUE THREAD

**Issue by thomashoesel** [microsoft/ALAppExtensions#25775]
### Describe the request

Hello,

We need a new event for table "Item Journal Line", trigger OnValidate of field Quantity immediately before line CheckSerialNoQty() like

OnBeforeCheckSerialNoQty(Rec: Record "Item Journal Line"; IsHandled: Boolean)

... with a skip option for line CheckSerialNoQty() in case IsHandled = true.

### Additional context

It has the same background as in https://github.com/microsoft/ALAppExtensions/issues/25198:

In our customer's industry is the base unit of measure not equally countable in pieces but we track it with lot numbers and serial numbers too. So we need an escape before TestField("Qty. (Base)", 1).

Best Regards
Thomas

Internal work item: AB#497931

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15767.
