### ISSUE TITLE
Add param PurchaseInvoceHeader in OnAfterCreatePurchCopyDocument on Codeunit::"Correct Posted Purch. Invoice"

### ISSUE THREAD

**Issue by cr998** [microsoft/ALAppExtensions#25774]
### Describe the request

Inside codeunit "Correct Posted Sales Invoice" dedicatd on copy dales document exist and event "OnAfterCreateCopyDocument" whit two params

![image](https://github.com/microsoft/ALAppExtensions/assets/6900835/3402b63e-3af9-46db-9c97-622c5ea65ce5)

But in the oposite, codeunit "Correct Posted Purch. Invoice" the same event "OnAfterCreateCopyDocument" there is not the secod parameter

![image](https://github.com/microsoft/ALAppExtensions/assets/6900835/20d983d5-c067-4838-9eb4-ba015803db79)

### Additional context

i need a special functionality on copying data from purchase invoice to purchase cr memo
Internal work item: AB#497905

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15767.
