### ISSUE TITLE
Adding the SuppressCommit function to the remaining print codeunits

### ISSUE THREAD

**Issue by ACPJanousek** [microsoft/ALAppExtensions#25772]
### Describe the request

Adding the SuppressCommit function to the remaining print codeunits Please modify the following codeunits as well as other similar printing CUs. 
codeunit 5779 Whse.-Printed 
codeunit 5903 Service Shpt.-Printed 
codeunit 5905 Service-Printed 
codeunit 6651 "Return Shipment - Printed" 

Similarly as it is solved for example in: codeunit 6661 "Return Receipt - Printed" 

codeunit 6661 "Return Receipt - Printed"
trigger OnRun()
    begin
        OnBeforeOnRun(Rec, SuppressCommit);
        Rec.Find();
        Rec."No. Printed" := Rec."No. Printed" + 1;
        OnBeforeModify(Rec);
        Rec.Modify();
        if not SuppressCommit then
            Commit();
    end;
[IntegrationEvent(false, false)]
local procedure OnBeforeOnRun(var ReturnReceiptHeader: Record "Return Receipt Header"; var SuppressCommit: Boolean)
    begin
    end;

It is similar as these requetsts:

- request [[Event Request / Extensiblity Request] codeunit 5903 "Service Shpt.-Printed"- OnBeforeOnRun ?? Issue #25625 ?? microsoft/ALAppExtensions ?? GitHub](https://github.com/microsoft/ALAppExtensions/issues/25625) and 
- [[Event Request / Extensiblity Request] codeunit 6651 "Return Shipment - Printed" - OnBeforeOnRun ?? Issue #25624 ?? microsoft/ALAppExtensions ?? GitHub](https://github.com/microsoft/ALAppExtensions/issues/25624)

### Additional context

It should be similar as it is solved for example in: codeunit 6661 "Return Receipt - Printed".

 
Internal work item: AB#497845

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15767.
