### ISSUE TITLE
[EventRequest] report 7305 "Whse.-Source - Create Document"

### ISSUE THREAD

**Issue by fvanderhek** [microsoft/ALAppExtensions#25771]
### Describe the request

Requesting a new event publisher on Report 7305 "Whse.-Source - Create Document"

Event
`OnPreDataItemJobPlanningLineOnAfterSetFilters(VAR JobPlanningLine: Record "Job Planning Line", Job: Record Job)`

**Code**
```
dataitem("Job Planning Line"; "Job Planning Line")
        {
            DataItemTableView = SORTING("Job No.", "Job Contract Entry No.") WHERE("Line Type" = FILTER("Budget" | "Both Budget and Billable"), Type = const(Item));
```
            trigger OnAfterGetRecord()
            var
                Item: Record Item;
                WMSMgt: Codeunit "WMS Management";
                QtyToPick: Decimal;
                QtyToPickBase: Decimal;
            begin
                Item.Get("No.");
                if Item.IsNonInventoriableType() then
                    CurrReport.Skip();

                WMSMgt.CheckInboundBlockedBin("Location Code", "Bin Code", "No.", "Variant Code", "Unit of Measure Code");

                WhseWkshLine.SetRange("Source Line No.", "Job Contract Entry No.");
                WhseWkshLine.SetRange("Source Subline No.", "Line No.");
                if WhseWkshLine.IsEmpty() then begin
                    TestField("Qty. per Unit of Measure");
                    CalcFields("Pick Qty.");

                    QtyToPick := Quantity - "Qty. Picked" - "Pick Qty.";
                    QtyToPickBase := UOMMgt.CalcBaseQty("No.", "Variant Code", "Unit of Measure Code", QtyToPick, "Qty. per Unit of Measure");

                    if QtyToPick > 0 then begin
                        CreatePick.SetJobPlanningLine("Job Planning Line");
                        CreatePick.SetTempWhseItemTrkgLine(
                          "Job Planning Line"."Job No.", Database::"Job Planning Line", '', 0, "Job Contract Entry No.", "Location Code");
                        CreatePick.CreateTempLine("Location Code", "No.", "Variant Code", "Unit of Measure Code", '', "Bin Code", "Qty. per Unit of Measure", "Qty. Rounding Precision", "Qty. Rounding Precision (Base)", QtyToPick, QtyToPickBase);
                    end;
                end else
                    WhseWkshLineFound := true;
            end;

            trigger OnPreDataItem()
            begin
                if WhseDoc <> WhseDoc::Job then
                    CurrReport.Break();

                WhseSetup.Get();

                Clear(CreatePickParameters);
                CreatePickParameters."Assigned ID" := AssignedID;
                CreatePickParameters."Sorting Method" := SortActivity;
                CreatePickParameters."Max No. of Lines" := 0;
                CreatePickParameters."Max No. of Source Doc." := 0;
                CreatePickParameters."Do Not Fill Qty. to Handle" := DoNotFillQtytoHandle;
                CreatePickParameters."Breakbulk Filter" := BreakbulkFilter;
                CreatePickParameters."Per Bin" := false;
                CreatePickParameters."Per Zone" := false;
                CreatePickParameters."Whse. Document" := CreatePickParameters."Whse. Document"::Job;
                CreatePickParameters."Whse. Document Type" := CreatePickParameters."Whse. Document Type"::Pick;
                CreatePick.SetParameters(CreatePickParameters);

                SetRange("Job No.", JobHeader."No.");
                SetFilter(Quantity, '>0');

                **>>> New Code**
                OnPreDataItemJobPlanningLineOnAfterSetFilters("Job Planning Line", JobHeader);
                **<<< New Code End**

                WhseWkshLine.SetCurrentKey("Source Type", "Source Subtype", "Source No.", "Source Line No.", "Source Subline No.");
                WhseWkshLine.SetRange("Source Type", DATABASE::Job);
                WhseWkshLine.SetRange("Source Subtype", 0);
                WhseWkshLine.SetRange("Source No.", JobHeader."No.");
            end;
        }

### Additional context

With the requested publisher we can set additional filters on the Job Planning Line DataItem and influence the Job Planning Records which will be processed in the OnAfterGetRecord of the Job Planning Line DataItem.
Internal work item: AB#497827

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15767.
