### ISSUE TITLE
[Procedure Change Request] XmlPort "1010 SEPA DD pain.008.001.02" procedure GetOrgIdOthrId

### ISSUE THREAD

**Issue by jazadv** [microsoft/ALAppExtensions#25784]
### Describe the request

Can you change the procedure GetOrgIdOthrId to be able to assign a value to CreditorNo based on PaymentExportData fields? 
A possible solution would be to change the "Payment Export Data" record as a parameter instead of actual BankAccountNo. parameter
And additionally add an event in this procedure with "Payment Export Data" Record and CreditorNo as parameters to allow us to change the value of CreditorNo depending on the data in the record

### Additional context

We have a problem since the value of the CreditorNo to export must be different depending on whether Sepa Partner Type is 'CORE' or B2B. With the current implementation we cannot modify it since the procedure GetOrgIdOthrId where this value is assigned only has the bank code as a parameter and has no events.
Internal work item: [AB#500365](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500365)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 18588.
