### ISSUE TITLE
Page 1290 "Payment Reconciliation Journal" OnValidate "Account No."

### ISSUE THREAD

**Issue by AndreaRux** [microsoft/ALAppExtensions#25787]
### Describe the request

Hi all,
on page 1290 "Payment Reconciliation Journal" in the OnValidate trigger of "Account No.", the procedure TransferRemainingAmountToAccount() is called without any further condition as Difference <> 0.
Shouldn't there be an action on the page that transfers the remainig amount to the account? But at least there should be an IsHandled event so that the procedure can be suppressed.

```
                field("Account No."; Rec."Account No.")
                {
                    ApplicationArea = Basic, Suite;
                    ToolTip = 'Specifies the account number that the payment application will be posted to when you post the worksheet.';

                    trigger OnValidate()
                    var
                        IsHandled: Boolean;
                    begin
                        CurrPage.Update();
                        OnBeforeTransferRemainingAmountToAccount(Rec, IsHandled);
                        if not IsHandled then
                           if Rec.Difference <> 0 then
                               Rec.TransferRemainingAmountToAccount();
                    end;
                }
....

    [IntegrationEvent(false, false)]
    local procedure OnBeforeTransferRemainingAmountToAccount(BankAccReconciliationLine: Record "Bank Acc. Reconciliation Line"; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

It causes some extra work, e.g. when changing the account no. again.
![image](https://github.com/microsoft/ALAppExtensions/assets/34539583/d1629ab2-1324-4e09-bfdf-026216ab2075)
or try to apply a specific entry.
The remainig amount should only be transfered on a specific request.
Internal work item: AB#498099

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15815.
