### ISSUE TITLE
page 5135 "Customer Link" / Protected variable

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#25780]
### Describe the request

Please make variable CurrMasterFields in the page 5135 "Customer Link" protected so that it can be used on page extension.

### Additional context

We want to set default to CurrMasterFields::Customer when the page is opened. Currently the field value is defaulted to CurrMasterFields::Contact.
Internal work item: AB#497970

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15971.
