### ISSUE TITLE
codeunit 12 "Gen. Jnl.-Post Line" - procedure scope requests (#24355)

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#25798]
### Describe the request

Hello, we need to be able to access some common functions and to be able to get back into the base code execution chain from our event subscribers, so we would like to have a number of procedures changed to not be local in scope:

procedure GLCalcAddCurrency
procedure HandleDtldAdjustment
procedure DeferralPosting

Having these not local will ensure that we can influence the posting codeunit properly so that when our event code runs, the internal variables and states are up to date with the code we ran, and be able to come back to base code to take advantage of the base code we do not need modifications to.

Thank you.

### Additional context

This had been requested before but as an addition to the original request (24355), so it probably got lost in the process.  Thank you.
Internal work item: AB#498160

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15971.
