### ISSUE TITLE
Document Notifications - Copy Address from Sales Document

### ISSUE THREAD

**Issue by ikickicts** [microsoft/ALAppExtensions#25794]
### Describe the request

In codeunit 1390 "Document Notifications",would it be possible to have 2 new events added to function CopyBuyFromVendorAddressFieldsFromSalesDocument and CopyPayToVendorAddressFieldsFromSalesDocument to mirror what is in place in the equivalent customer functions. It would be useful to have 

OnCopyBuyFromVendorAddressFieldsFromSalesDocumentOnBeforeModify(Vendor,PurchaseHeader)
OnCopyPayToVendorAddressFieldsFromSalesDocumentOnBeforeModify(Vendor,PurchaseHeader)

### Additional context

Useful to add consistency across the documents.
Internal work item: AB#498115

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15815.
