### ISSUE TITLE
[Event Change Request]  table 77 "Report Selections" event OnSendEmailDirectlyOnBeforeSendFileLoop()

### ISSUE THREAD

**Issue by peterz84** [microsoft/ALAppExtensions#25795]
### Describe the request

Could you add the parameter ServerEmailBodyFilePath **as var** to the OnSendEmailDirectlyOnBeforeSendFileLoop event in table 77. Could you add this so we can overwrite it with the "Email Body Layout Code" from the (existing) TempAttachReportSelections parameter.

### Additional context

In document layouts (related to a customer) it is by standard BC possible to check "Use for e-mail body" on just one (main) record. We made it possible to check this boolean on multiple lines. So our goal is to get the e-mail body of the current record, instead of the "main" record.

![image](https://github.com/microsoft/ALAppExtensions/assets/25202313/a1cafd98-8a62-4486-b9c0-27d0be364d67)

Now the problem we have in the customization is that the e-mail body is determined/created before the sending loop is reached, because the intention of standard BC is that there is only one record with the boolean checked. Therefore we would like the possibility to change the created e-mail body, per attachment record and need an event change.
Internal work item: AB#498116

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15815.
