### ISSUE TITLE
[Change Request] page 255 "Cash Receipt Journal"

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#25792]
### Describe the request

Hello, can you please change the lokal procedure SetControlAppearanceFromBatch as global in page 255 "Cash Receipt Journal"?

```
    procedure SetControlAppearanceFromBatch()
    begin
        SetApprovalStateForBatch();
        BackgroundErrorCheck := BackgroundErrorHandlingMgt.BackgroundValidationFeatureEnabled();
        ShowAllLinesEnabled := true;
        Rec.SwitchLinesWithErrorsFilter(ShowAllLinesEnabled);
        JournalErrorsMgt.SetFullBatchCheck(true);
    end;
```

### Additional context

We would like to access the funktion from a page extension.
Internal work item: AB#498105

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15971.
