### ISSUE TITLE
[event request] please extend existing event with one more parameter in codeunit 97 "Blanket Purch. Order to Order": OnBeforeCreatePurchHeader

### ISSUE THREAD

**Issue by thomashoesel** [microsoft/ALAppExtensions#25790]
### Describe the request

Hello,
please add a parameter PurchaseOrderHeader to event OnBeforeCreatePurchHeader in codeunit 97 "Blanket Purch. Order to Order" like this: 

_local procedure OnBeforeCreatePurchHeader(var PurchaseHeader: Record "Purchase Header"; **var PurchaseOrderHeader: Record "Purchase Header"**; PrepmtPercent: Decimal; var IsHandled: Boolean)_

![image](https://github.com/microsoft/ALAppExtensions/assets/127841954/7b1ca865-c8fa-48a9-be82-40a53e8504cf)

![image](https://github.com/microsoft/ALAppExtensions/assets/127841954/069c78e0-915b-4d66-bddf-7583cd78e1d8)

### Additional context

In codeunit 97 "Blanket Purch. Order to Order" the Rec (Blanket Purchase Header) is used to create and insert a new PurchaseOrderHeader. That's actually done inside procedure CreatePurchHeader. 

In our customer's scenario it is sometimes necessary to use an existing (e.g. imported) PurchaseOrderHeader instead of a new one. It's our responsibility to make this PurchaseOrderHeader look like it's been created from this Blanket Order.

But although we're able to skip the insertion of a new PurchaseOrderHeader via event OnBeforeCreatePurchHeader we're not able to load this existing purchase order into the global variable PurchaseOrderHeader. To achieve this, we'd like to have an additional parameter called by ref.
Internal work item: AB#498100

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15815.
