### ISSUE TITLE
codeunit 12 "Gen. Jnl.-Post Line" - PostGLAcc event alteration request (#24335)

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#25799]
### Describe the request

Hello, we would like to change the OnBeforePostGLAcc event at the beginning of the PostGLAcc procedure to include the Sender parameter with it. We need access to this to post additional entries and call additional code.

    //Event Change begin
    //[IntegrationEvent(false, false)]
    [IntegrationEvent(true, false)]
    //Event Change end
    local procedure OnBeforePostGLAcc(GenJournalLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; var GLEntryNo: Integer; var IsHandled: Boolean; var TempGLEntryBuf: Record "G/L Entry" temporary)
    begin
    end;

Thank you.

### Additional context

This was originally requested in #24335, but got lost in the mix somewhere.  If you could please add the Sender option please.  Thank you.
Internal work item: AB#498161

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15815.
