### ISSUE TITLE
[Event Request] Table 11733 "Cash Document Line CZP".Amount.OnValidate

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#25793]
### Describe the request

Please add new event

```
field(20; Amount; Decimal)
{
    Caption = 'Amount';
    DataClassification = CustomerContent;

    trigger OnValidate()
    //-----------------------------------------OnValidateAmountOnBeforeTestField:BEGIN
    var
        IsHandled: Boolean;
    //-----------------------------------------OnValidateAmountOnBeforeTestField:END
    begin
        //-----------------------------------------OnValidateAmountOnBeforeTestField:BEGIN
        IsHandled := false;
        OnValidateAmountOnBeforeTestField(IsHandled, Rec);
        if not IsHandled then begin
        //-----------------------------------------OnValidateAmountOnBeforeTestField:END
            TestField("Account Type");
            TestField("Account No.");
        //-----------------------------------------OnValidateAmountOnBeforeTestField:BEGIN
        end;
        //-----------------------------------------OnValidateAmountOnBeforeTestField:END
        UpdateAmounts();
    end;
}

//-----------------------------------------OnValidateAmountOnBeforeTestField:BEGIN
[IntegrationEvent(true, false)]
local procedure OnValidateAmountOnBeforeTestField(var CashDocumentLineCZP: Record "Cash Document Line CZP"; var IsHandled: Boolean)
begin
end;
//-----------------------------------------OnValidateAmountOnBeforeTestField:END
```

### Additional context

We need skip tests because we are using different process for account filling.
Internal work item: [AB#498104](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498104)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16679.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 16942.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.0.

Build ID to track: 16937.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 17036.
