### ISSUE TITLE
[Event Request] Codeunit "Service Line - Price" missing publishers

### ISSUE THREAD

**Issue by chrischbo** [microsoft/ALAppExtensions#25797]
### Describe the request

We would like to have the same publishers as we have in the "Sales Line - Price" codeunit. Actual it isn't consistent. For example we're missing the "OnAfterValidatePrice" and "OnAfterUpdate" publisher. Is it possible to keep the "xxx line - price" logic mostly the same regarding the publishers. So it will be easier to handle because you can subscribe the known publishers to have more or less the same result.

Thanks in advance
Christian

### Additional context

Handle code the same way as we did in sales and puchase.
Internal work item: AB#498141

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15815.
