### ISSUE TITLE
[Event Request] OnCommit event

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/ALAppExtensions#258]
Could we get a new global event for "OnCommit" that would trigger whenever database changes are going to be committed, whether because of an explicit COMMIT call or because the logic has finished executing?  I would need the ability to subscribe to this event and then raise an error to prevent the commit from happening (we would have logic to check conditions before allowing the commit).

This request is related to migrating a registered NAV add-on to D365 BC where we need to check special G/L balancing conditions before allowing any transaction to be committed to the database.

**Comment by AlexanderYakunin** [comment]
No, we have no such plans for global event

**Comment by JesperSchulz** [comment]
As this isn't a usual "event request" which can be resolved through application code, I'd like to refer you to our ideas page, where great ideas such as this can be published. The link is http://aka.ms/bcideas. If you could post it there, it will get added to our ideas backlog for possible future implementation.
