### ISSUE TITLE
[Event Request] Report 10412 - Check (Check/Stub/Stub) - OnAfterPreDataItemOfPrintSettledLoop

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/ALAppExtensions#25808]
### Describe the request

Hi,

I would like to request the following event publisher in Report 10412 - Check (Check/Stub/Stub) -

OnAfterPreDataItemOfPrintSettledLoop  - **trigger OnPreDataItem()**

                    trigger OnPreDataItem()
                    begin
                        PrintCheckHelper.PrintSettledLoopHelper(CustLedgEntry, VendLedgEntry, GenJnlLine, BalancingType.AsInteger(), BalancingNo,
                          FoundLast, TestPrint, FirstPage, FoundNegative, ApplyMethod);
                        if PreprintedStub then
                            TotalText := ''
                        else begin
                            TotalText := Text019Txt;
                            Stub2DocNoHeader := USText011Txt;
                            Stub2DocDateHeader := USText012Txt;
                            Stub2AmountHeader := USText013Txt;
                            Stub2DiscountHeader := USText014Txt;
                            Stub2NetAmountHeader := USText015Txt;
                            Stub2PostingDescHeader := USText017Txt;
                        end;
                        GLSetup.Get();
                        PageNo := PageNo + 1;

                        `if TestPrint then begin
                            BankTransitNo := Text003Txt;
                            BankAccountNo := Text003Txt;
                        end;
                        BankTransitNo := BankAcc2."Transit No.";
                        BankAccountNo := BankAcc2."Bank Account No.";
                        OnAfterPreDataItemOfPrintSettledLoop(GenJnlLine, BalancingType, ApplyMethod); //Publisher
                    end;`

**Below are the event details**
    [IntegrationEvent(false, false)]
    `local procedure OnAfterPreDataItemOfPrintSettledLoop(GenJnlLine: Record "Gen. Journal Line"; BalancingType: Enum "Gen. Journal Account Type"; ApplyMethod: Option)
    begin
    end;`

### Additional context

Publisher request marked with //Publisher tag.
Internal work item: AB#498281

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15987.
