### ISSUE TITLE
New Event for SignServContractDoc CU

### ISSUE THREAD

**Issue by PJohnstonSysco** [microsoft/ALAppExtensions#25804]
### Describe the request

A new event at the end of the SetInvoicing procedure which gives access to the same variables in the OnBeforeSetInvoicing Event within CU 5944 (SignServContractDoc)

### Additional context

This is needed due to bespoke functionality which depends on if InvoiceNow is true after the confirm message has been shown.
Internal work item: AB#498224

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15815.
