### ISSUE TITLE
[Event Request] Codeunit 1254 "Match Bank Pmt. Appl." OnBeforeMatchNoOverwriteIfManualOrAccepted 

### ISSUE THREAD

**Issue by MCHammerTNP** [microsoft/ALAppExtensions#25805]
### Describe the request

Please can you add a new event OnBeforeMatchNoOverwriteOfManualOrAccepted to the procedure MatchNoOverwriteOfManualOrAccepted in Codeunit 1254 "Match Bank Pmt. Appl."

```
    procedure MatchNoOverwriteOfManualOrAccepted(BankAccReconciliation: Record "Bank Acc. Reconciliation")
    var
        MatchBankPayments: Codeunit "Match Bank Payments";
        IsHandled: Boolean;  //NEW CODE
    begin

        //NEW CODE -
        IsHandled := false;
        OnBeforeMatchNoOverwriteOfManualOrAccepted(BankAccReconciliation, IsHandled);
        if IsHandled then
            exit;
        //NEW CODE +

        BankAccReconciliationLine.FilterBankRecLines(BankAccReconciliation);

```

With the corresponding Event

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeMatchNoOverwriteOfManualOrAccepted(var BankAccReconciliation: Record "Bank Acc. Reconciliation"; var IsHandled: Boolean)
    begin
    end;

```

### Additional context

This is similar to the OnBeforeRun event and is required to have the option to run custom bank payment matching code.
Internal work item: AB#498223

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15815.
