### ISSUE TITLE
Table 36 "Sales Header" OnBeforeValidateShipmentDate

### ISSUE THREAD

**Issue by simona-ur** [microsoft/ALAppExtensions#25809]
### Describe the request

Hello, would it be possible to add OnBeforeValidateShipmentDate event on field "Shipment Date" in OnValidate trigger in table 36 "Sales Header", like this:
```
         field(21; "Shipment Date"; Date)
         {
            Caption = 'Shipment Date';

            trigger OnValidate()
            begin
>               OnBeforeValidateShipmentDate(Rec, CurrFieldNo, IsHandled)
                if not IsHandled then
                  UpdateSalesLinesByFieldNo(FieldNo("Shipment Date"), CurrFieldNo <> 0);
            end;
```
```
local procedure OnBeforeValidateShipmentDate (var SalesHeader: Record "Sales Header"; CurrentFieldNo: Integer; var IsHandled: Boolean)
```

### Additional context

We need to override the trigger.
Internal work item: AB#498282

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15987.
