### ISSUE TITLE
codeunit 12 "Gen. Jnl.-Post Line" - event alteration request in procedure PostDtldVendLedgEntries (#24814)

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#25801]
### Describe the request

Hello. We would like to request that the OnPostDtldVendLedgEntriesOnBeforeCreateGLEntriesForTotalAmounts in the PostDtldVendLedgEntries procedure be altered to add the  sender parameter to the event. We need to do some different processing that requires us to override the CreateGLEntriesForTotalAmounts, so we need a lot of info to be passed into it to perform our task (most has been done already in the original request). 

codeunit 12 "Gen. Jnl.-Post Line"
.....
    // event definition change begin
    // [IntegrationEvent(false, false)]
    [IntegrationEvent(true, false)]
    // event definition change end
    local procedure OnPostDtldVendLedgEntriesOnBeforeCreateGLEntriesForTotalAmounts(var VendPostingGr: Record "Vendor Posting Group"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; GenJournalLine: Record "Gen. Journal Line"; var TempDimensionPostingBuffer: Record "Dimension Posting Buffer" temporary; AdjAmountBuf: array[4] of Decimal; SavedEntryNo: Integer; LedgEntryInserted: Boolean; var IsHandled: Boolean)
    begin
    end;

Thanks!

### Additional context

This was originally requested in #24814, but I made a mistake in my example code and did not include the passing of the Sender parameter in the event definition.  Thanks.
Internal work item: AB#498163

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15815.
