### ISSUE TITLE
[Event Request] Page 41 Sales Quote - OnAfterOnAfterGetRecord(Rec);

### ISSUE THREAD

**Issue by josalm** [microsoft/ALAppExtensions#25814]
### Describe the request

Hi,
On Page 41 Sales Quote it should exist the OnAfterOnAfterGetRecord(Rec) event to match other similar pages like Sales Order, Sales Invoice and Sales Credit Memo.

Best regards

### Additional context

I want to assess the state after the OnAfterGetRecord(Rec) in a Sales Quote
Internal work item: AB#498373

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15987.
