### ISSUE TITLE
[Event Request] Missing OnTestInitialize in Codeunit 134831 "Alloc. Acc. Purch. E2E Tests", Application "Tests-ERM"

### ISSUE THREAD

**Issue by JoergPernberg** [microsoft/ALAppExtensions#25817]
### Describe the request

Could you please insert the OnTestInitialize Event at the beginning of the Initialize procedure?

### Additional context

![image](https://github.com/microsoft/ALAppExtensions/assets/53136356/227b2795-8fea-4a04-8aad-44a5288368ee)

Internal work item: AB#498419

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16192.
