### ISSUE TITLE
Codeunit 12 - Gen-Jnl.-Post Line - InsertDtldVendLedgEntryUnapply procedure variable accessibility change

### ISSUE THREAD

**Issue by SER-denisg** [microsoft/ALAppExtensions#25815]
### Describe the request

Hello, we would like to make a request to make a change to the accessibility of a parameter on the InsertDtldVendLedgEntryUnapply procedure in Codeunit 12.  The OldDtldVendLedgEntry is currently passed in by value and we would like it passed in by reference.
 
```
codeunit 12 "Gen. Jnl.-Post Line"
...
    //procedure change begin
    //local procedure InsertDtldVendLedgEntryUnapply(GenJnlLine: Record "Gen. Journal Line"; var NewDtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; OldDtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; var NextDtldLedgEntryNo: Integer)
    local procedure InsertDtldVendLedgEntryUnapply(GenJnlLine: Record "Gen. Journal Line"; var NewDtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; var OldDtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; var NextDtldLedgEntryNo: Integer)
    //procedure change end
...

```

### Additional context

We have some code that adjust the value in this variable, but because it is passed in by value, it does not pass our changes back up to the calling procedure.  One of the events in this procedure passes the OldDtldVendLedgEntry variable by reference, which we modify it, and we need it to be returned to the calling procedure to be able to process our changes.

Thank you.
Internal work item: [AB#498402](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498402)

**Comment by AlexanderYakunin** [comment]
Can you explain your case in details? We need justification to make this kind of changes, and it possible we would like not to make it, but find another solution for your code.

**Comment by SER-denisg** [comment]
My aplologies for the delay in replying, I am trying to analyze the code and have possibly found some possibilties to adjust code.  If you could leave this open, I will update you hopfully within a week.  Thanks.
