### ISSUE TITLE
Event Request - Table 7021 "Price Line Filters"

### ISSUE THREAD

**Issue by NS-NN** [microsoft/ALAppExtensions#25819]
### Describe the request

Hi,
Is it possible to add event "OnAfterSetFilterPageBuilder" in procedure "EditPriceLineFilter()" in table 7021 "Price Line Filters"?
You can add parameters (TableCaptionValue: Text, PriceListLine: Record "Price List Line", FilterPageBuilder: FilterPageBuilder).

Thank you in advance.

![Picture 1](https://github.com/microsoft/ALAppExtensions/assets/57817172/969e4a6d-97cd-4ec5-8bc8-5f199f4e6755)
![image](https://github.com/microsoft/ALAppExtensions/assets/57817172/bd328b69-6cae-442e-b8ab-5462a2ad0c60)

### Additional context

We have to add default filters when you open from Price Worksheet Copy Lines.
Internal work item: AB#498456

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15987.
