### ISSUE TITLE
[Event Request] Missing OnTestInitialize in 134315 "Workflow Queuing Tests", Application "Tests-Workflow"

### ISSUE THREAD

**Issue by JoergPernberg** [microsoft/ALAppExtensions#25818]
### Describe the request

Could you please insert the OnTestInitialize-Event at the beginning of the test procedure TestEventQueuingWithIncDocWorkflow?

### Additional context

![image](https://github.com/microsoft/ALAppExtensions/assets/53136356/a0c6edb7-de76-4b5f-8de8-66ec18c6744a)

Internal work item: AB#498420

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16192.
