### ISSUE TITLE
[Event Request] Report 10412 - Check (Check/Stub/Stub) - OnPreDataItemOfCheckPages

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/ALAppExtensions#25820]
### Describe the request

Hi,

I would like to request the following event publisher in Report 10412 - Check (Check/Stub/Stub) - **OnPreDataItemOfCheckPages** - trigger -- OnPreDataItem

                trigger OnPreDataItem()
                begin
                    FirstPage := true;
                    FoundLast := false;
                    TotalLineAmount := 0;
                    TotalLineDiscount := 0;
                    AddedRemainingAmount := true;
                    OnPreDataItemOfCheckPages(GenJnlLine); //Publisher
                end;
                
**Below are event details**
```
    [IntegrationEvent(false, false)]
    local procedure OnPreDataItemOfCheckPages(GenJnlLine: Record "Gen. Journal Line")
    begin
    end;
```

### Additional context

Publisher request marked with //Publisher tag.
Internal work item: AB#498455

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15987.
