### ISSUE TITLE
[Event Request] codeunit 7313 "Create Put-away" - OnCalcQtyToPutAwayOnAfterSetQtyToPutAwayBase

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#25821]
### Describe the request

Can you add NewBinContent to event OnCalcQtyToPutAwayOnAfterSetQtyToPutAwayBase?
And change CurrLocation to reference (VAR)?

```
    [IntegrationEvent(false, false)]
    local procedure OnCalcQtyToPutAwayOnAfterSetQtyToPutAwayBase(PostedWhseRcptLine: Record "Posted Whse. Receipt Line"; var Location: Record Location; Bin: Record Bin; CrossDockInfo: Option; EmptyZoneBin: Boolean; var QtyToPutAwayBase: Decimal; var EverythingHandled: Boolean; var RemQtyToPutAwayBase: Decimal; NewBinContent: Boolean)
    begin
    end;

```

### Additional context

I want to change "Directed Put-away and Pick" for CurrLocation to be able to trigger CreateBinContent only when NewBinContent is true.
Internal work item: AB#498476

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15987.
