### ISSUE TITLE
[Request for External] codeunit 404 "IC Feedback" - ShowIntercompanyMessage

### ISSUE THREAD

**Issue by VPaas2** [microsoft/ALAppExtensions#25822]
### Describe the request

Please remove the internal keyword on function "ShowIntercompanyMessage" and its overloads in codeunit 404 "IC Feedback" so they  can be used from other apps.

### Additional context

Extensions to IC posting need to be able to give feedback to the user.
Internal work item: AB#498475

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15971.
