### ISSUE TITLE
[Request for external] codeunit 7313 "Create Put-away" FindBin and IsFloatingBin

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#25825]
### Describe the request

Is it possible to be able to use the procedures FindBin and IsFloatingBin in codeunit 7313 "Create Put-away" without duplicating them? FindBin with Bin record in return and IsFloatingBin with Bin as parameter.

### Additional context

We have some custom code that is ran at the same time as Create Put-away. Then we need the use the same procedure and get CurrBin in return. We want to do this because we don't want to check the procedure for each release to check if it has been changed.
Internal work item: AB#498608

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15971.
