### ISSUE TITLE
[Request for External] codeunit 7308 Replenishment CreateWhseWkshLine

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#25824]
### Describe the request

Can you change procedure CreateWhseWkshLine to global in codeunit 7308 Replenishment CreateWhseWkshLine?
And add another procedure to get the contents of TempWhseWkshLine?

```
    procedure GetTempWhseWkshLine(var TempWhseWorksheetLineOut: Record "Whse. Worksheet Line" temporary)
    begin
        TempWhseWorksheetLineOut.Reset();        
        TempWhseWorksheetLineOut.Copy(TempWhseWkshLine, true);
    end;
```

### Additional context

I need this as we want to add additional lines from our custom code, and we want to be able to get the data and change it at some point.
Internal work item: AB#498609

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15971.
