### ISSUE TITLE
[Event Request] Codeunit 99000769 "Production BOM-Check" procedure CheckCircularReferencesInProductionBOM

### ISSUE THREAD

**Issue by KonnosPB** [microsoft/ALAppExtensions#25826]
### Describe the request

Could we please have a new event OnCheckCircRefInPBOMOnAfterProdBOMLineSetFilters` in
procedure `CheckCircularReferencesInProductionBOM` in `codeunit 99000769 "Production BOM-Check"`?

Example:
``` AL
local procedure CheckCircularReferencesInProductionBOM(var TempProductionBOMHeader: Record "Production BOM Header" temporary; VersionCode: Code[20])
var
      ProductionBOMHeader: Record "Production BOM Header";
      ProductionBOMLine: Record "Production BOM Line";
      ProdItem: Record Item;
      ProductionBOMNo: Code[20];
      NextVersionCode: Code[20];
      CheckNextLevel: Boolean;
begin
      ProductionBOMLine.SetRange("Production BOM No.", TempProductionBOMHeader."No.");
      ProductionBOMLine.SetRange("Version Code", VersionCode);
      ProductionBOMLine.SetFilter("No.", '<>%1', '');
      >>>>>>>>>>>>>>>>>
      OnCheckCircRefInPBOMOnAfterProdBOMLineSetFilters(ProductionBOMLine, TempProductionBOMHeader, VersionCode)
      <<<<<<<<<<<<<<<<<
      if ProductionBOMLine.FindSet() then
            repeat
                  if ProductionBOMLine.Type = ProductionBOMLine.Type::Item then begin
                        ProdItem.SetLoadFields("Production BOM No.");
      ...
end;

>>>>>>>>>>>>>>>>>
[IntegrationEvent(false, false)]
local procedure OnCheckCircRefInPBOMOnAfterProdBOMLineSetFilters(var ProductionBOMLine: Record "Production BOM Line; TempProductionBOMHeader: Record "Production BOM Header" temporary; VersionCode: Code[20])
begin
end;
<<<<<<<<<<<<<<<<<
```

### Additional context

Due to a modification in our software solution, an error occurs when calling up the "Cost Shares" page from the item card. The Microsoft standard assumes in the source code that if the type is not an item, it is a production BOM. Retrieving the BOM header then leads to an error.
To solve this problem, the filter in the production BOM lines needs to be influenced so that, for example, the provided group is no longer available in the production BOM for resolution. For this purpose, we have created this event request. As soon as this event is available, it can be subscribed and commented on with the search term
Internal work item: AB#498591

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15987.
