### ISSUE TITLE
[Event Request] T246 Requisition Line - Handle new 'Type' enum values

### ISSUE THREAD

**Issue by Aize-S** [microsoft/ALAppExtensions#25832]
### Describe the request

Table 246 "Requisition Line" has a "Type" field of type Enum "Requisition Line Type", which is an extensible Enum.

But in the corresponding "No." field, there is no event to handle any new Types:
![image](https://github.com/microsoft/ALAppExtensions/assets/24434095/bdbbe990-3c04-4841-be26-54cd10964bb1)

For instance, table 37 "Sales Line" has an OnAfterAssignFieldsForNo(...):
![image](https://github.com/microsoft/ALAppExtensions/assets/24434095/f2c9d078-2f18-4fc1-b906-9f08d388fe4e)

Please add a similar event to the "Requisition Line".

### Additional context

"Requisition Line".Type is an extensible Enum, but validation of "Requisition Line"."No." does not implement this extensibility.
Internal work item: AB#498745

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15987.
