### ISSUE TITLE
[Request for External] Report 1404 "Bank Acc. - Detail Trial Bal." - protected vars

### ISSUE THREAD

**Issue by jlorenc01** [microsoft/ALAppExtensions#25834]
### Describe the request

Hello,

could you please change the access scope of some variables below to protected? We need at least:
```
protected var
    BankAccLedgEntryExists
    StartBalance
    PrintOnlyOnePerPage
    ExcludeBalanceOnly
    PrintReversedEntries
```

Thank you.

### Additional context

We need to read the value of those variables.
Internal work item: AB#498756

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17192.
