### ISSUE TITLE
[Bug]: Inventory Document Line - Shipment in non-base UOM

### ISSUE THREAD

**Issue by xtiche** [microsoft/ALAppExtensions#25837]
### Describe the issue

In case we want to create a line with UOM "Q-ty per Item" <> 1, then we have doubled amounts in field "Amount" on validation of "Quantity":
![image](https://github.com/microsoft/ALAppExtensions/assets/36332111/a1a8ee61-11c1-40a0-8d9a-5ed0f915a5d5)
First time we multiply amounts in "Unit Cost" based on "Qty. per Unit of Measure"
![image](https://github.com/microsoft/ALAppExtensions/assets/36332111/d0b6f876-013e-435f-9e0e-220c91116e86)
After that we do it again for field "Unit Amount"
![image](https://github.com/microsoft/ALAppExtensions/assets/36332111/007a4401-c8b0-4a85-9572-bfb01cafd76e)
And during update of the field "Amount" we again multiply it by Quantity
![image](https://github.com/microsoft/ALAppExtensions/assets/36332111/b62df364-77bc-4b8e-9d77-d06499897e26)

As a result, if we have next params in line: Qunatity = 2, "Qty. per Unit of Measure" = 2, and Item."Unit Cost" = 200 then
Unit Cost will be 400
Unit Amount will be 800 
Amount will be 1600

### Expected behavior

we expect the next calculation:  if we have the next params in line: Qunatity = 2, "Qty. per Unit of Measure" = 2, and Item."Unit Cost" = 200 then result should be following:
Unit Cost will be 400
Unit Amount will be 400
Amount will be 800

### Steps to reproduce

Create Item with 2 UOM, the second should have "Qty. per Unit of Measure" <> 1
![image](https://github.com/microsoft/ALAppExtensions/assets/36332111/89db2c30-3b98-4f21-b551-50441c9c92f1)

Create Inv. Shipment with this item, and the second UOM
Check field Amount

### Additional context

Second and third lines in result have same ledgers, but has wrong values in field "Amount"
![image](https://github.com/microsoft/ALAppExtensions/assets/36332111/5793d175-0a8a-466c-8ec7-269c07aa0091)
![image](https://github.com/microsoft/ALAppExtensions/assets/36332111/70cc8d9f-b600-4f68-a04c-07409ecc5538)

To solve the problem remove doubled multiplying in GetUnitAmount
```
    procedure GetUnitAmount(CalledByFieldNo: Integer)
    begin
        RetrieveCosts();
        "Unit Cost" := UnitCost;

        case "Document Type" of
            "Document Type"::Receipt:
                "Unit Amount" := FindInvtDocLinePrice(CalledByFieldNo);
            "Document Type"::Shipment:
                "Unit Amount" := UnitCost;  // * "Qty. per Unit of Measure"; // remove here
        end;
    end;
```

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
That could be a product defect and must hence get reported to support, to ensure it is addressed within the right SLA and in all supported versions of Business Central.

This repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).
