### ISSUE TITLE
Make QuantityOnAfterValidate function consistent in all sales subforms

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#25839]
### Describe the request

The function `QuantityOnAfterValidate` is protected public in the sales order subform, quote subform etc, but NOT in the sales invoice subform. Can you add it there with protected public as well?

Also the event `OnAfterQuantityOnAfterValidate` exists in the "Sales Quote Subform", "Sales Order Subform" and "Sales Return Order Subform". It is missing in the "Sales Invoice Subform", "Sales Cr. Memo Subform" and "Blanket Sales Order Subform". Can you add the event there and make this function consistent in these pages that it always looks like this in all of this six pages (Maybe you will also find a solution to move the code to the sales line)? 

```
    protected procedure QuantityOnAfterValidate()
    begin
        OnBeforeQuantityOnAfterValidate(Rec, xRec);

...

        OnAfterQuantityOnAfterValidate(Rec, xRec);
    end;

// with
    [IntegrationEvent(true, false)]
    local procedure OnBeforeQuantityOnAfterValidate(var SalesLine: Record "Sales Line"; var xSalesLine: Record "Sales Line")
    begin
    end;

    [IntegrationEvent(true, false)]
    local procedure OnAfterQuantityOnAfterValidate(var SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line")
    begin
    end;

```

### Additional context

Maybe also consider changing other functions which are similar in these pages. You could check the purchase pages as well.
Internal work item: [AB#498796](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498796)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16192.
