### ISSUE TITLE
[Event Request] Report 10412 - Check (Check/Stub/Stub) - OnAfterGetRecordOfGenJnlLine

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/ALAppExtensions#25833]
### Describe the request

Hi,

I would like to request the following event publisher in Report 10412 - Check (Check/Stub/Stub) - OnAfterGetRecordOfGenJnlLine - trigger -- **OnAfterGetRecord of Data item GenJnlLine**

                                  BankAcc2."Country/Region Code",
                                  BankAcc."Bank Communication",
                                  CheckToAddr[1],
                                  CheckDateFormat,
                                  DateSeparator,
                                  CheckLanguage,
                                  CheckStyle);
                            end;
                        BalancingType::Employee:
                            ApplyBalancingTypeOfEmployee();
                    end;

                    CheckDateText :=
                      CheckTranslationManagement.FormatDate("Posting Date", CheckDateFormat, DateSeparator, CheckLanguage, DateIndicator);
                end else begin
                    if ChecksPrinted > 0 then
                        CurrReport.Break();
                    CheckTranslationManagement.SetCheckPrintParams(
                      BankAcc2."Check Date Format",
                      BankAcc2."Check Date Separator",
                      BankAcc2."Country/Region Code",
                      BankAcc2."Bank Communication",
                      CheckToAddr[1],
                      CheckDateFormat,
                      DateSeparator,
                      CheckLanguage,
                      CheckStyle);
                    BalancingType := BalancingType::Vendor;
                    BalancingNo := Text010Txt;
                    Clear(CheckToAddr);
                    for i := 1 to 5 do
                        CheckToAddr[i] := Text003Txt;
                    Clear(SalespersonPurchaser);
                    CheckNoText := Text011Txt;
                    if CheckStyle = CheckStyle::CA then
                        CheckDateText := DateIndicator
                    else
                        CheckDateText := Text010Txt;
                end;
                OnAfterGetRecordOfGenJnlLine(GenJnlLine, RemitAddress, CheckToAddr, BalancingType, ApplyMethod); **//Publisher**
            end;

            trigger OnPreDataItem()
            var
                CompanyInfo: Record "Company Information";

![image](https://github.com/microsoft/ALAppExtensions/assets/28556102/a619dd67-6279-4337-9fcf-1592e4fe352c)

**Below are event details** 

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetRecordOfGenJnlLine(GenJnlLine: Record "Gen. Journal Line"; var RemitAddress: Record "Remit Address"; var CheckToAddr: array[8] of Text[100]; BalancingType: Enum "Gen. Journal Account Type"; ApplyMethod: Option)
    begin
    end;

### Additional context

**Publisher request marked with //Publisher tag**
Internal work item: AB#498744

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 15987.
