### ISSUE TITLE
[Event Request] "Price Helper - V16" Procedure DeletePrices

### ISSUE THREAD

**Issue by chrischbo** [microsoft/ALAppExtensions#25838]
### Describe the request

We would like to take care of our price lists and don't want them to be deleted without furhter checks if a corresponding entity will be deleted.
Actual if the procedure is called it will delete the Price List Header without any checks and a delete(false). If there are lines for a different source type you will end up with Price List Lines without a related header. Also there is no notification or something that a price list was deleted or a confirm that a related price list will be deleted.

So please give us the option to handle this.
 
    local procedure DeletePrices(SourceType: Enum "Price Source Type"; SourceNo: Code[20]; ParentSourceNo: Code[20])
    var
        PriceListHeader: Record "Price List Header";
        PriceListLine: Record "Price List Line";
        PriceWorksheetLine: Record "Price Worksheet Line";
        isHandled: Boolean; // new
    begin
        // new Start
        OnBeforeDeletePrices(SourceType, SourceNo, ParentSourceNo, isHandled);
        if not isHandled then begin
        // new End

        PriceListHeader.SetRange("Source Type", SourceType);
        PriceListHeader.SetRange("Parent Source No.", ParentSourceNo);
        PriceListHeader.SetRange("Source No.", SourceNo);
        if not PriceListHeader.IsEmpty() then
            PriceListHeader.DeleteAll();        

        end; // new

        PriceListLine.SetRange("Source Type", SourceType);
        PriceListLine.SetRange("Parent Source No.", ParentSourceNo);
        PriceListLine.SetRange("Source No.", SourceNo);
        if not PriceListLine.IsEmpty() then
            PriceListLine.DeleteAll();

        PriceWorksheetLine.SetRange("Source Type", SourceType);
        PriceWorksheetLine.SetRange("Parent Source No.", ParentSourceNo);
        PriceWorksheetLine.SetRange("Source No.", SourceNo);
        if not PriceWorksheetLine.IsEmpty() then
            PriceWorksheetLine.DeleteAll();

        OnAfterDeletePrices(SourceType, SourceNo, ParentSourceNo); // new
    end;

Thanks in advance

### Additional context

Better handling and no more headless lines
Internal work item: AB#498795

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16024.
