### ISSUE TITLE
[Event Request] Page 143 "Posted Sales Invoices"

### ISSUE THREAD

**Issue by GMATest** [microsoft/ALAppExtensions#25849]
### Describe the request

Hello, would it be possible to add OnBeforeAfterGetCurrRecord event on OnAfterGetCurrRecord() trigger in page 143 "Posted Sales Invoices", like this:
```
    trigger OnAfterGetCurrRecord()
    var
        CRMCouplingManagement: Codeunit "CRM Coupling Management";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeAfterGetCurrRecord(Rec, IsHandled, HasPostedSalesInvoices, CRMIsCoupledToRecord, CRMIntegrationEnabled);  //New event
        if IsHandled then
            exit;

        HasPostedSalesInvoices := true;
        if not GuiAllowed() then
            exit;

        CurrPage.IncomingDocAttachFactBox.PAGE.LoadDataFromRecord(Rec);
        CRMIsCoupledToRecord := CRMIntegrationEnabled;
        if CRMIsCoupledToRecord then
            CRMIsCoupledToRecord := CRMCouplingManagement.IsRecordCoupledToCRM(RecordId);
    end;
```
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeAfterGetCurrRecord(var SalesInvoiceHeader: Record "Sales Invoice Header"; var IsHandled: Boolean; var HasPostedSalesInvoices: Boolean; var CRMIsCoupledToRecord: Boolean; var CRMIntegrationEnabled: Boolean) //CustPub
    begin
    end;
```

### Additional context

We need to override the trigger.
Internal work item: [AB#498851](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498851)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16024.
