### ISSUE TITLE
 [Event Request] codeunit 81 "Sales-Post (Yes/No)" -  OnAfterPost

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#25841]
### Describe the request

Hello,

Would it be possible to include/add PostAndSend in this event.
```
    [IntegrationEvent(false, false)]
    local procedure OnAfterPost(var SalesHeader: Record "Sales Header"; PostAndSend: Boolean)
    begin
    end;
```

### Additional context

Makes it possible to check if code is ran from PostAndSend procedure. 
Internal work item: [AB#498820](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498820)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16024.
