### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" OnBeforeConfirmReceivedShippedItemDimChange

### ISSUE THREAD

**Issue by GMATest** [microsoft/ALAppExtensions#25846]
### Describe the request

Hello, would it be possible to add OnBeforeConfirmReceivedShippedItemDimChange event on ConfirmReceivedShippedItemDimChange() procedure in table 39 "Purchase Line", like this:
```
    procedure ConfirmReceivedShippedItemDimChange(): Boolean
    var
        ConfirmManagement: Codeunit "Confirm Management";
        IsHandled: Boolean;
        Result: Boolean;
    begin
        IsHandled := false;
        OnBeforeConfirmReceivedShippedItemDimChange(Rec, IsHandled, Result); //New event
        if IsHandled then
            exit(Result);

        if not ConfirmManagement.GetResponseOrDefault(StrSubstNo(Text049, TableCaption), true) then
            Error(Text050);

        exit(true);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeConfirmReceivedShippedItemDimChange(var PurchaseLine: Record "Purchase Line"; var IsHandled: Boolean; var Result: Boolean)
    begin
    end;
```

### Additional context

We need to skip confirm if PurchaseLine.GetSystemCalledDimensionUpdate() returns true.
Internal work item: [AB#498858](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498858)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16024.
