### ISSUE TITLE
[Event Parameter Request] Codeunit 1380 Batch Processing Mgt. - procedure BatchProcess - event OnBatchProcessOnBeforeShowMessage

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#25844]
### Describe the request

We would like the Parameter/-s  ErrorMessageHandler, ErrorMessageMgt and FullBatchProcessed added to the following event.

Codeunit 1380 Batch Processing Mgt. - procedure BatchProcess - event OnBatchProcessOnBeforeShowMessage

Original:
``` 
OnBatchProcessOnBeforeShowMessage(CounterPosted, CounterTotal, IsHandled);

    [IntegrationEvent(true, false)]
    local procedure OnBatchProcessOnBeforeShowMessage(CounterPosted: Integer; CounterTotal: Integer; var IsHandled: Boolean)
    begin
    end;
``` 
	
Change:
``` 
OnBatchProcessOnBeforeShowMessage(CounterPosted, CounterTotal, ErrorMessageHandler, ErrorMessageMgt, FullBatchProcessed, IsHandled);

    [IntegrationEvent(true, false)]
    local procedure OnBatchProcessOnBeforeShowMessage(CounterPosted: Integer; CounterTotal: Integer; var ErrorMessageHandler: Codeunit "Error Message Handler"; var ErrorMessageMgt : Codeunit "Error Message Management"; FullBatchProcessed : Boolean; var IsHandled: Boolean)
    begin
    end;
``` 	

### Additional context

We need the error message in our own log
Internal work item: AB#498848

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16024.
