### ISSUE TITLE
[Event Request] fix parameter on events in COD87 and COD97

### ISSUE THREAD

**Issue by NavNab** [microsoft/ALAppExtensions#25840]
### Describe the request

Hello,

Last time I requested two events and you already shipped them in v23.3. Thank you very much.
https://github.com/microsoft/ALAppExtensions/issues/25617
https://github.com/microsoft/ALAppExtensions/issues/25616

I noticed that I used the wrong parameter. Oups ????

In COD87, the event should be called like:

- OK: OnBeforeCreateSalesHeader(***SalesOrderHeader***, CreditLimitExceeded, IsHandled);
- NOT OK: OnBeforeCreateSalesHeader(***SalesHeader***, CreditLimitExceeded, IsHandled);

In COD97, the event should be called like:
- OK: OnBeforeCreatePurchHeader(***PurchOrderHeader***, IsHandled);
- NOT OK: OnBeforeCreatePurchHeader(***PurchHeader***, IsHandled);

Please let me know if this is enough details to fix it. Or if I can fix it myself.
Thank you

### Additional context

https://github.com/microsoft/ALAppExtensions/issues/25617
https://github.com/microsoft/ALAppExtensions/issues/25616
Internal work item: [AB#498807](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498807)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16024.
