### ISSUE TITLE
[Event Request] Table 700 - Error Messages - Procedure ShowErrorMessages

### ISSUE THREAD

**Issue by ChrSt89** [microsoft/ALAppExtensions#25857]
### Describe the request

Please add an Event OnBeforeShowErrorMessages in Function ShowErrorMessages in Table 700

```            
    procedure ShowErrorMessages(RollBackOnError: Boolean) ErrorString: Text
    var
        ErrorMessages: Page "Error Messages";
    begin
        AssertRecordTemporaryOrInContext();

        ClearFilters();
        SetContextFilter();
        SetRange(Context, false);
        if IsEmpty() then
            exit;

      // NEW
     IsHandled := FALSE;
     OnBeforeShowErrorMessages(Rec,IsHandled);
     IF IsHandled THEN 
      EXIT;
     // NEW

        if GuiAllowed then begin
            ErrorMessages.SetRecords(Rec);
            ErrorMessages.Run();
        end;

        ErrorString := ToString();

        if RollBackOnError then
            if HasErrors(false) then
                Error('');

        exit;
    end;
``` 

``` 
    [IntegrationEvent(false, false)]
    local procedure OnDrillDownSource(var ErrorMessage: Record "Error Message"; var IsHandled: Boolean)
    begin
    end;
``` 	

### Additional context

We need the error message in our own log
Internal work item: [AB#498923](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498923)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16024.
