### ISSUE TITLE
[Event Request] - Table Purchase Header - Function CheckShipToCodeChange

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#25855]
### Describe the request

Could xRec be added to this event "OnBeforeCheckShipToCodeChange"?

```
 local procedure CheckShipToCodeChange(PurchHeader: Record "Purchase Header")
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCheckShipToCodeChange(PurchHeader,xRec, IsHandled);
        if IsHandled then
            exit;

        with PurchHeader do begin
            if ("Document Type" = "Document Type"::Order) and (xRec."Ship-to Code" <> "Ship-to Code") then begin
                PurchLine.SetRange("Document Type", PurchLine."Document Type"::Order);
                PurchLine.SetRange("Document No.", "No.");
                PurchLine.SetFilter("Sales Order Line No.", '<>0');
                if not PurchLine.IsEmpty() then
                    Error(YouCannotChangeFieldErr, FieldCaption("Ship-to Code"));
            end;
        end;
    end;
```

### Additional context

I need to check xrec values to rec values
Internal work item: [AB#498855](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498855)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16024.
