### ISSUE TITLE
[Event Request] [BE] codeunit 2000040 "Coda Import Management"

### ISSUE THREAD

**Issue by louagej** [microsoft/ALAppExtensions#25850]
### Describe the request

In Belgium bank statement comes in a specific format, namely CODA.
These files are imported with the BE localization as a typical header line combination (`CODA Statement` and `CODA Statement Line`.)
The primary key of the `CODA Statement` table consists of the `Bank Account No.`, `Statement No.` fields.
The Statement No. field is filled with a value received from within the CODA file (makes sense).
The problem here is that banks reset the Statement No. every year back to one (`001` always 3 characters long).
So after a year your overwrite the already imported CODA data again.

To prevent this, I would like to have an extra Event in the codeunit 2000040 `Coda Import Management`
In Procedure 
```AL
procedure CheckOldBalance(var CodedBankStmtSrcLine: Record "CODA Statement Source Line"): Boolean
var
        BankAccountNo: Text[30];
        IBANNumber: Text[34];
    begin
        CodBankStmtSrcLine := CodedBankStmtSrcLine;
        with CodBankStmtSrcLine do begin
            Evaluate("Statement No.", CopyStr(Data, 3, 3));
            //Line above shows the Statment No. received from the content of the file
           ...
        end;
        CodedBankStmtSrcLine := CodBankStmtSrcLine;
        //[Event Request] Add Event here to influence Statement No.
        OnAfterCheckOldBalance(CodedBankStmtSrcLine);
        exit(true);
    end;
```

:octocat:

### Additional context

An event `OnAfterCheckOldBalance` would let us add e.g. a year prefix or suffix tot the `Statement No.` in order to keep every CODA file unique over the years.
Internal work item: [AB#498852](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498852)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16024.
