### ISSUE TITLE
[Event Request] "Invt. Document Line" New event in GetUnitAmount

### ISSUE THREAD

**Issue by xtiche** [microsoft/ALAppExtensions#25851]
### Describe the request

procedure GetUnitAmount(CalledByFieldNo: Integer)
    begin
        RetrieveCosts();
        "Unit Cost" := UnitCost;

        case "Document Type" of
            "Document Type"::Receipt:
                "Unit Amount" := FindInvtDocLinePrice(CalledByFieldNo);
            "Document Type"::Shipment:
                "Unit Amount" := UnitCost * "Qty. per Unit of Measure";
        end;

        OnAfterGetUnitAmount(Rec, UnitCost, CalledByFieldNo); // new event
    end;

    local procedure OnAfterGetUnitAmount(var Rec: Record "Invt. Document Line"; UnitCost: Decimal; CalledByFieldNo: integer)
    begin

    end;

### Additional context

We need to change the calculation of "Unit Amount", but cannot do in on OnAfterValidateTrigger, as we need to change this logic before "Amount" will be updated.
Internal work item: [AB#498853](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498853)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16024.
