### ISSUE TITLE
EventRequest Whse. Post Shipment, GetSource Documents

### ISSUE THREAD

**Issue by Gwrsky** [microsoft/ALAppExtensions#25852]
### Describe the request

Hello,
I'm preparing the functionality for our client - for negative Shipments and negative Receipts.
For negative Receipts, publishers provided are sufficent and i was expecting the same publishers to be on the Shipment Side, as it's symmetrical case.

In Particular:
![image](https://github.com/microsoft/ALAppExtensions/assets/72869582/e352e157-93fa-4672-9260-7d1e358f74c7)
In Receipt version(left-hand side), i'm using the Event marked as 1.
In Shipment version(right-hand side), i'm unable to use event marked as 2, as there's SetFilter in the line 104.

Could i have symmetrical version of event 1 in the Shipment version?

Same goes for Whse.-Sales Release vs Whse.-Purch. Release:

![image](https://github.com/microsoft/ALAppExtensions/assets/72869582/16ad9adb-2237-49f6-a8da-90b754697e7a)
Event marked as 3 have PurchaseHeader in Parameters,  but Event marked as 4 doesnt - i need to change WhseType based on the Header.

Could i have symmetrical version of event 3 in Sales Side?

In Report::"Get Source Documents"
![image](https://github.com/microsoft/ALAppExtensions/assets/72869582/31d51e43-a3c8-4b27-b04a-9601445d873d)
Here its minor issue, but if we're fixing symmetrical versions of Shipment/Receipt then we could use symmetrical event to the selected (line 655) in line 639.

Same goes for:
codeunit 5750 "Whse.-Create Source Document"
![image](https://github.com/microsoft/ALAppExtensions/assets/72869582/7e0d79ab-164c-4095-b3a1-984a4ffae2bb)
Selected Event exists in procedure SetQtysOnRcptLine, but there's no similar in SetQtysOnShptLine.

I've made workaround by copying a lot of standard code for shipment. For Receipt, whole modification if fullfilled by handfull of Events.

### Additional context

Events would be symmetrical for symmetrical functionalities, i wouldn't have to copy a lot of standard code.
Internal work item: [AB#498856](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498856)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16024.
