### ISSUE TITLE
[Event Request] page 6510 "Item Tracking Lines" - OnBeforeAssignPackageNo

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25864]
### Describe the request

    protected procedure AssignPackageNo()
    var
        QtyToCreate: Decimal;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeAssignPackageNo(Rec, TempItemTrackLineInsert, SourceQuantityArray, IsHandled);
        if IsHandled then begin
            CalculateSums();
            exit;
        end;

        if ZeroLineExists() then
            Rec.Delete();

    [IntegrationEvent(false, false)]
    local procedure OnBeforeAssignPackageNo(var TrackingSpecification: Record "Tracking Specification"; var TempItemTrackLineInsert: Record "Tracking Specification" temporary; SourceQuantityArray: array[5] of Decimal; var IsHandled: Boolean)
    begin
    end;

### Additional context

Because OnBeforeAssignLotNo also exists but not one for Package No.
Internal work item: [AB#498957](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498957)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16024.
