### ISSUE TITLE
[Extensibility Request] Sales Statistic and Sales Order Statistc 

### ISSUE THREAD

**Issue by AJasp** [microsoft/ALAppExtensions#25869]
### Describe the request

Hi,
we want to influence the Profit (% and Amount) on the "Sales Statistic" and "Sales Order Statistic" - we have to skip some voucher lines and for this requirement we analyze the existing extension possibilities. With the current possibilies we cannot implement this requirement.

The only way to do it, is to clone the existing object - that is not a good solution, especially for maintaining this clone. 

So we want to suggest to use protected global vars (like ProfitLCY) to visualize every Information on these pages. Code like this Example of the information `"Cost Adjmt. Amount (LCY)"` is not extensible:
`Field("TotalAdjCostLCY[1] - TotalSalesLineLCY[1].""Unit Cost (LCY)"""; TotalAdjCostLCY[1] - TotalSalesLineLCY[1]."Unit Cost (LCY)")`

Please refactor these pages to give partners a possibility to meet customers expectations - and no - a new idea on the Ideas-Portal ist not a solution...

Thanks!

### Additional context

Change of Profit Amount and Percent
Internal work item: [AB#499090](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499090)

**Comment by AlexanderYakunin** [comment]
We already have ALL variables as protected in Sales Statistics page in 24.0:

    protected var
        TotalSalesLine: Record "Sales Line";
        TotalSalesLineLCY: Record "Sales Line";
        Cust: Record Customer;
        TempVATAmountLine: Record "VAT Amount Line" temporary;
        SalesPost: Codeunit "Sales-Post";
        TotalAmount1: Decimal;
        TotalAmount2: Decimal;
        VATAmountText: Text[30];
        ProfitLCY: Decimal;
        ProfitPct: Decimal;
        AdjProfitLCY: Decimal;
        AdjProfitPct: Decimal;
        TotalAdjCostLCY: Decimal;
        CreditLimitLCYExpendedPct: Decimal;
        PrevNo: Code[20];
        AllowInvDisc: Boolean;
        AllowVATDifference: Boolean;
        VATAmount: Decimal;
