### ISSUE TITLE
Page 9110 "Item Attributes Factbox" - Expose variables

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#25866]
### Describe the request

Please expose the global vars on Page 9110 "Item Attributes Factbox" as protected vars:

- ContextType: Option "None",Item,Category;
- ContextValue: Code[20];
- IsItem: Boolean;
- IsVisible: Boolean;
- ItemAttCode: Code[20];
- CategoryAttCode: Code[20];

### Additional context

- We want to re-use the 'Item Attributes' framework/pages to assign item attributes to item variants. Therefore, we need access to the context in the "Item Attributes Factbox"
- In addition, we want to copy the code from the 'Edit' action, and move it the the attribute name ondrilldown trigger to have one-click access to the editor page (instead of 2 clicks)
Internal work item: [AB#499064](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499064)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17192.
