### ISSUE TITLE
[Request Local Procedure] table 7317 "Warehouse Receipt Line" - CalcBaseQty

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25862]
### Describe the request

    Old code:
    local procedure CalcBaseQty(Qty: Decimal; FromFieldName: Text; ToFieldName: Text): Decimal
    
    New code:
    procedure CalcBaseQty(Qty: Decimal; FromFieldName: Text; ToFieldName: Text): Decimal

### Additional context

In table 7321 "Warehouse Shipment Line" the local procedure CalcBaseQty has been made global in an earlier release. Why not perform the same action on the receipt side
Internal work item: [AB#498959](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/498959)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18704.
