### ISSUE TITLE
[Event Request] table 81 "Gen. Journal Line" - OnBeforeCheckDirectPostingCheckGLAccount

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#25876]
### Describe the request

Hello, can you please add a new event OnBeforeCheckDirectPostingCheckGLAccount to table 81 "Gen. Journal Line"?

```
    local procedure CheckGLAcc(GLAcc: Record "G/L Account")
    var
        IsHandled: Boolean;
    begin
        GLAcc.CheckGLAcc();
        IsHandled := false;
        OnBeforeCheckDirectPostingCheckGLAccount(Rec, GLAcc, IsHandled);
        If IsHandled then
            exit;
        if GLAcc."Direct Posting" or ("Journal Template Name" = '') or "System-Created Entry" then
            exit;
        if Rec."Posting Date" <> 0D then
            if "Posting Date" = ClosingDate("Posting Date") then
                exit;

        CheckDirectPosting(GLAcc);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckDirectPostingCheckGLAccount(var GenJournalLine: Record "Gen. Journal Line"; var GLAccount: Record "G/L Account"; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

Enable different GLAccChecks. We need access to the Rec and the event OnBeforeCheckDirectPosting doesn???t have access 
either.

Internal work item: [AB#499108](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499108)

**Comment by AleksandricMarko** [comment]
Hello @RZ440 
As OnBeforeCheckDirectPosting event now has Rec as parameter, this request is not needed

 
![image](https://github.com/microsoft/ALAppExtensions/assets/133204513/ca4866a8-9b0d-40aa-9efe-c996fea7881e)
