### ISSUE TITLE
[Change Request] table 81 "Gen. Journal Line" - procedure CheckGLAcc

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#25874]
### Describe the request

Hello, can you please change the local procedure CheckGLAcc to protected?

```
    protected procedure CheckGLAcc(GLAcc: Record "G/L Account")
    begin
        GLAcc.CheckGLAcc();
        if GLAcc."Direct Posting" or ("Journal Template Name" = '') or "System-Created Entry" then
            exit;
        if Rec."Posting Date" <> 0D then
            if "Posting Date" = ClosingDate("Posting Date") then
                exit;

        CheckDirectPosting(GLAcc);
    end;
```

### Additional context

Use CheckGLAcc on TableExt, because we use the GLAccount as well and want to know that it is valid.
Internal work item: [AB#499109](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499109)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17192.
