### ISSUE TITLE
[Event Request] table 81 "Gen. Journal Line" - OnBeforeSetDescriptionFromGLAcc

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#25884]
### Describe the request

Hello, can you please add a new event OnBeforeSetDescriptionFromGLAcc to table 81 "Gen. Journal Line"?

```
    local procedure SetDescriptionFromGLAcc(GLAccount: Record "G/L Account")
    begin
        OnBeforeSetDescriptionFromGLAcc(Rec, GLAccount);
        if ReplaceDescription() and (not GLAccount."Omit Default Descr. in Jnl.") then
            UpdateDescription(GLAccount.Name)
        else
            if GLAccount."Omit Default Descr. in Jnl." then
                Description := '';
        OnAfterSetDescriptionFromGLAcc(Rec, GLAccount)
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetDescriptionFromGLAcc(var GenJournalLine: Record "Gen. Journal Line"; var GLAccount: Record "G/L Account")
    begin
    end;
```

### Additional context

In specific cases set ???GLAcc."Omit Default Descr. in Jnl." := false;??? before setting the description.
Internal work item: [AB#499135](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499135)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16151.
