### ISSUE TITLE
[Event Request] table 81 "Gen. Journal Line" - OnBeforeExportPaymentFile

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#25880]
### Describe the request

Hello, can you please add a new event OnBeforeExportPaymentFile to table 81 "Gen. Journal Line"?

```
    procedure ExportPaymentFile()
    var
        BankAcc: Record "Bank Account";
        ConfirmManagement: Codeunit "Confirm Management";
        IsHandled: Boolean;
    begin
        if not FindSet() then
            Error(NothingToExportErr);

        IsHandled := false;
        OnBeforeExportPaymentFile(Rec, IsHandled);
        If IsHandled then
            exit;

        SetRange("Journal Template Name", "Journal Template Name");
        SetRange("Journal Batch Name", "Journal Batch Name");
        TestField("Check Printed", false);
        TestField("Document Type");
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeExportPaymentFile(var GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

Add a confirm if a paymentFile was already created, to check if the customer wants to create it again.
Internal work item: [AB#499124](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499124)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16151.
