### ISSUE TITLE
[Event Request] table 80 "Gen. Journal Template" - OnAfterCheckGLAcc

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#25885]
### Describe the request

Hello, can you please add a new event OnAfterCheckGLAcc to table 80 "Gen. Journal Template"?

```
    local procedure CheckGLAcc(AccNo: Code[20])
    var
        GLAcc: Record "G/L Account";
    begin
        if AccNo <> '' then begin
            GLAcc.Get(AccNo);
            GLAcc.CheckGLAcc();
            GLAcc.TestField("Direct Posting", true);
            OnAfterCheckGLAcc(Rec, GLAcc);
        end;
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckGLAcc(var GenJournalTemplate: Record "Gen. Journal Template"; GLAccount: Record "G/L Account")
    begin
    end;
```

### Additional context

GLAccount check according to ???Posting Date??? in the Rec.
Internal work item: [AB#499133](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499133)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16151.
