### ISSUE TITLE
[Change Request] table 81 "Gen. Journal Line" - procedure CopyVATSetupToJnlLines

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#25881]
### Describe the request

Hello, can you please change the local procedure CopyVATSetupToJnlLines to global?

```
    procedure CopyVATSetupToJnlLines(): Boolean
    begin
        if ("Journal Template Name" <> '') and ("Journal Batch Name" <> '') then
            if GenJnlBatch.Get(Rec."Journal Template Name", Rec."Journal Batch Name") then
                exit(GenJnlBatch."Copy VAT Setup to Jnl. Lines");
        exit("Copy VAT Setup to Jnl. Lines");
    end;
```

### Additional context

We want to access this function from within a subscriber codeunit.
Internal work item: [AB#499127](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499127)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17192.
