### ISSUE TITLE
[Event Request] table 751 "Standard General Journal Line" - OnAfterCheckGLAcc

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#25888]
### Describe the request

Hello, can you please add a new event OnAfterCheckGLAcc to table 751 "Standard General Journal Line"?

```
    local procedure CheckGLAcc(GLAcc: Record "G/L Account")
    begin
        GLAcc.CheckGLAcc();
        if GLAcc."Direct Posting" or ("Journal Template Name" = '') then
            exit;
        GLAcc.TestField("Direct Posting", true);
        OnAfterCheckGLAcc(Rec, GLAcc);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterCheckGLAcc(var StandardGeneralJournalLine: Record "Standard General Journal Line"; GLAcc: Record "G/L Account")
    begin
    end;
```

### Additional context

GLAccount validity check according to Rec.???Posting Date???.
Internal work item: [AB#499144](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499144)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16151.
