### ISSUE TITLE
[Event Request] New OnBefore event in "Item-Check Avail." - ShowWarning

### ISSUE THREAD

**Issue by NAVFreak** [microsoft/ALAppExtensions#25897]
### Describe the request

In function[ ShowWarning ](https://github.com/microsoft/BusinessCentralApps/blob/6ca598e56cbc8a2da9065c72ba16a811424f58d4/App/Layers/W1/BaseApp/Inventory/Availability/ItemCheckAvail.Codeunit.al#L697 ) in "Item-Check Avail." you can see that item.get() happens before the OnBefore event so I can't handle/skip that database write.

What I want is another event in the beginning of the function
```
IsHandled := false;
  **OnBeforeShowWarningForThisItemBeforeItemGet(ItemNo, ShowWarning, IsHandled);**
   if not Item.Get(ItemNo) then
            exit(false);
```

### Additional context

The issue that I'm having is that I'm trying to write automated tests without doing any database reads/write since they are slow, the the mentioned function stops me from doing that.

Currently our automated tests takes 30-40 minutes, so we are very keen to that new tests won't do any db operations during test.

Internal work item: [AB#499433](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499433)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16192.
