### ISSUE TITLE
[Scope Change] codeunit "VAT Reporting Date Mgt".CheckDateAllowed()

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/ALAppExtensions#25894]
### Describe the request

Please change `CheckDateAllowed` method scope in `codeunit "VAT Reporting Date Mgt"` to public:
```al
internal procedure CheckDateAllowed(VATDate: Date; ContextFieldNo: Integer)
```

### Additional context

The tests of `VAT Reporting Date` against allowed date ranges in document posting routines (sales/purchase/...) were not implemented. Or will be? We want to do that the same way as `Posting Date` tests are done and we do not want to duplicate the code.
Internal work item: [AB#499198](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499198)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21326.

**Comment by JesperSchulz** [comment]
@RadoArvay, seems like only the scope change was done (from what I quickly can tell).
