### ISSUE TITLE
[Event Request] Codeunit 5341 "CRM Int. Table. Subscriber" - ApplySalesLineTax -> IsHandled Pattern

### ISSUE THREAD

**Issue by JDEnergieversum** [microsoft/ALAppExtensions#25896]
### Describe the request

Hello, we need an IsHandled Pattern in the "ApplySalesLineTax" function in Codeunit 5341 "CRM Int. Table Subscriber".

As example:

local procedure ApplySalesLineTax(SourceRecordRef: RecordRef; var DestinationRecordRef: RecordRef)
    var
        SalesLine: Record "Sales Line";
        CRMSalesorderdetail: Record "CRM Salesorderdetail";
        IsHandled: Boolean;
    begin
        SourceRecordRef.SetTable(SalesLine);
        DestinationRecordRef.SetTable(CRMSalesorderdetail);
         "OnBeforeApplySalesLineTax(VAR CRMSalesorderdetail: "CRM Salesorderdetail"; VAR SalesLine: "Sales Line"; VAR IsHandled: Boolean);
        If IsHandled then
          exit;
        CRMSalesorderdetail.Tax := SalesLine."Amount Including VAT" - SalesLine.Amount;
        DestinationRecordRef.GetTable(CRMSalesorderdetail);
    end;

### Additional context

We use the Integration to D365 Customer Engagement.
We have an industry solution in our CRM System, which uses a different field to calculate the tax.
With this piece of code, it calculates the tax again and overwrites the net amount to the gross amount, which makes the branch solution recalculate their tax.
I am currently fixing this by scheduling an SQL Query which sets the Tax field to zero.
But this is producing unnecessary traffic and synchronisations between our CRM und BC.
Internal work item: [AB#499200](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499200)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16192.
