### ISSUE TITLE
[Request For External] Report 10412 - Check (Check/Stub/Stub) - Variables

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/ALAppExtensions#25898]
### Describe the request

Hello, 

Can you please move the variables from **Report 10412**  to **Protected**

Here is the list of variables to be updated to Protected

```
protected var

PreprintedStub: Boolean;
OneCheckPrVendor: Boolean;
ApplyMethod: Option Payment,OneLineOneEntry,OneLineID,MoreLinesOneEntry;
BalancingType: Enum "Gen. Journal Account Type";
CompanyAddr: array[8] of Text[100];
CheckToAddr: array[8] of Text[100];
CustLedgEntry: Record "Cust. Ledger Entry";
VendLedgEntry: Record "Vendor Ledger Entry";
RemainingAmount: Decimal;
CurrentLineAmount: Decimal;
LineAmount: Decimal;
LineDiscount: Decimal;
TotalLineAmount: Decimal;
UseCheckNo: Code[20];
BalancingNo: Code[20];
CheckNoText: Text[30];
CheckDateText: Text[30];
CheckAmountText: Text[30];
Stub2LineNo: Integer;
Stub2DocNo: array[50] of Text[35];
Stub2DocDate: array[50] of Date;
Stub2LineAmount: array[50] of Decimal;
Stub2LineDiscount: array[50] of Decimal;
Stub2PostingDesc: array[50] of Text[100];
Stub2DocNoHeader: Text[30];
Stub2DocDateHeader: Text[30];
Stub2AmountHeader: Text[30];
Stub2DiscountHeader: Text[30];
Stub2NetAmountHeader: Text[30];
Stub2PostingDescHeader: Text[30];
DescriptionLine: array[2] of Text[80];
```

### Additional context

We would like use for extension
Internal work item: [AB#499270](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/499270)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
