### ISSUE TITLE
[Event Request] page 22 "Customer List" - OnBeforeGetSelectionFilterForCustomer

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#25904]
### Describe the request

Hello, can you please add a new event OnBeforeGetSelectionFilterForCustomer to page 22 "Customer List"?

```
    procedure GetSelectionFilter(): Text
    var
        Cust: Record Customer;
        SelectionFilterManagement: Codeunit SelectionFilterManagement;
        SelectionFilterForCustomer: Text;
        IsHandled: Boolean;
    begin
        CurrPage.SetSelectionFilter(Cust);
        IsHandled := false;
        OnBeforeGetSelectionFilterForCustomer(Cust, SelectionFilterForCustomer, IsHandled);
        if IsHandled then
            exit(SelectionFilterForCustomer);
        exit(SelectionFilterManagement.GetSelectionFilterForCustomer(Cust));
    end;
```

```
    [IntegrationEvent(false, false)]
    procedure OnBeforeGetSelectionFilterForCustomer(Cust: Record Customer; var SelectionFilterForCustomer: Text; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

An event is required to intercept the customer filtering and apply additional filters. 
Internal work item: [AB#500341](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500341)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16192.
