### ISSUE TITLE
[ChangeRequest] page 253 "Sales Journal"

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#25902]
### Describe the request

Hello, can you please change the local procedure SetJobQueueVisibility to protected?

```
    protected procedure SetJobQueueVisibility()
    begin
        JobQueueVisible := Rec."Job Queue Status" = Rec."Job Queue Status"::"Scheduled for Posting";
        JobQueuesUsed := GeneralLedgerSetup.JobQueueActive();
    end;
```

### Additional context

The local procedure SetJobQueueVisibility should at least be set to protected to allow page extensions to modify the visibility of page elements after data updates.
Internal work item: [AB#500340](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500340)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17192.
