### ISSUE TITLE
[Event Request] Table 233 "Item Journal Batch"

### ISSUE THREAD

**Issue by mdemaio9** [microsoft/ALAppExtensions#25906]
### Describe the request

Hello,
we need an event in the table 233 "Item Journal Batch" in the validate trigger of the field 6500 "Item Tracking on Lines" to avoid the execution of the standard code.

`       

        field(6500; "Item Tracking on Lines"; Boolean)
        {
            Caption = 'Item Tracking on Lines';

            trigger OnValidate()
            var
                 IsHandled: boolean;
            begin
                // start event
                OnValidateItemTrackingOnLinesOnBeforeTestItemJnlTemplate(Rec,IsHandled);
                // end event
                if not IsHandled then begin
                     ItemJnlTemplate.Get("Journal Template Name");
                     ItemJnlTemplate.TestField(Type, ItemJnlTemplate.Type::Item);
                     ItemJnlTemplate.TestField(Recurring, false);
                end;
            end;
        }`
 
[IntegrationEvent(false, false)]
    local procedure OnValidateItemTrackingOnLinesOnBeforeTestItemJnlTemplate(var ItemJournalBatch: Record "Item Journal Batch"; var IsHandled: Boolean)
    begin
    end;

### Additional context

We saw that in this trigger the code has been changed in the version 23.3 of Business Central. 
We need the event to restore the code previously executed by the standard and skip the code inserted in 23.3.

This is business critical because we have an AppSource app and there isn't a workaround.
Internal work item: [AB#500382](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500382)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16192.
