### ISSUE TITLE
[EVENT REQUEST] codeunit 333 "Req. Wksh.-Make Order" OnBeforeCheckLocation

### ISSUE THREAD

**Issue by AlexCeg** [microsoft/ALAppExtensions#25916]
### Describe the request

We need an Event OnBeforeCheckLocation in the function CheckLocation in codeunit 333 "Req. Wksh.-Make Order":

```
    local procedure CheckLocation(RequisitionLine: Record "Requisition Line")
    var
        InventorySetup: Record "Inventory Setup";
        IsHandled: Boolean;
    begin
//-----> START
         OnBeforeCheckLocation(RequisitionLine, IsHandled);
         if IsHandled then
            exit;
//-----> END
        InventorySetup.Get();
        if InventorySetup."Location Mandatory" then
            RequisitionLine.TestField("Location Code");
    end;

...

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckLocation(var RequisitionLine: Record "Requisition Line"; var IsHandled: Boolean)
    begin
    end;
```

Can you implement this? Thank you in advance.

### Additional context

Wee need to skip the check if special conditions for the requisition lines are met. We extend this conditions in our app.
Internal work item: [AB#500551](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500551)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16418.
