### ISSUE TITLE
Make "Effective Permissions Mgt." functions extensible 

### ISSUE THREAD

**Issue by shuyusheng** [microsoft/ALAppExtensions#25911]
### Request 1

In `"Effective Permissions Mgt."` the `InsertEffectivePermissionForObject` function currently gives a warning for the parameter `var Permission: Record Permission`, which is pending obsolete. Could an overload of this function be created using the `Expanded Permission` table instead, as suggested by the obsolete reason from the `Permission` table.

Example
```
procedure PopulatePermissionBufferWithEffectivePermissionsForObject(var PermissionBuffer: Record "Permission Buffer"; PassedUserID: Guid; PassedCompanyName: Text[50]; PassedObjectType: Option; PassedObjectId: Integer)
...
```

### Request 2
Im `"Effective Permissions Mgt."` could a function be created to allow us to call `UserAccountHelper.GetEntitlementPermissionForObject`, this is currently accessible indirectly via the function`PopulatePermissionBuffer`. We would like access this directly similar to `InsertEffectivePermissionForObject`.

Example
```
procedure PopulatePermissionBufferWithEntitlementPermissionsForObject(var PermissionBuffer: Record "Permission Buffer"; PassedUserID: Guid; PassedObjectType: Option; PassedObjectId: Integer)
var
    PermissionCommaStr: Text;
    Read, Insert, Modify, Delete, Execute : Integer;
begin
    if not EnvironmentInfo.IsSaaS() then
        exit;
    PermissionBuffer.Init();
    PermissionBuffer.Source := PermissionBuffer.Source::Entitlement;
    PermissionBuffer."Permission Set" := '';
    PermissionBuffer.Type := PermissionBuffer.Type::System;
    PermissionCommaStr := UserAccountHelper.GetEntitlementPermissionForObject(PassedUserID, PassedObjectType, PassedObjectId);
    ExtractPermissionsFromText(PermissionCommaStr, Read, Insert, Modify, Delete, Execute);
    PermissionBuffer."Read Permission" := Read;
    PermissionBuffer."Insert Permission" := Insert;
    PermissionBuffer."Modify Permission" := Modify;
    PermissionBuffer."Delete Permission" := Delete;
    PermissionBuffer."Execute Permission" := Execute;
    PermissionBuffer.Insert();
end;
```

### Additional context

We are currently implementing licensing and entitlements for our apps [selling through appSource](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-sell-apps-appsource), and find these functions crucial in implementing side-by-side licensing support with our current licensing engine.
Internal work item: [AB#524052](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524052)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25227.
