### ISSUE TITLE
OnGetIntegrationTableMappingFromCRMIDOnBeforeFindTableID, pass TableID by reference

### ISSUE THREAD

**Issue by TKapitan** [microsoft/ALAppExtensions#25910]
### Describe the request

Update the following publisher in GetIntegrationTableMappingFromCRMID, Codeunit 5330 "CRM Integration Management". Pass TableID as a reference (var) to allow changing the integration table. When I designed this event, I somehow missed this...The IsHandle pattern now has no usage without the ability to return a custom TableID.

Current:
```
    [IntegrationEvent(false, false)]
    local procedure OnGetIntegrationTableMappingFromCRMIDOnBeforeFindTableID(var IntegrationTableMapping: Record "Integration Table Mapping"; TableID: Integer; CRMID: Guid; var IsHandled: Boolean)
    begin
    end;
```

New:
```
    [IntegrationEvent(false, false)]
    local procedure OnGetIntegrationTableMappingFromCRMIDOnBeforeFindTableID(var IntegrationTableMapping: Record "Integration Table Mapping"; var TableID: Integer; CRMID: Guid; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

Without the ability to return the TableID the IsHandle pattern is not usable.
Internal work item: [AB#500431](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500431)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17295.
