### ISSUE TITLE
[Change Request] codeunit 227 "VendEntry-Apply Posted Entries" - OnBeforeUnApplyVendor

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#25913]
### Describe the request

Hello, can you please add the IsHandled parameter to  event OnBeforeUnApplyVendor?

```
    local procedure UnApplyVendor(DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry")
    var
        UnapplyVendEntries: Page "Unapply Vendor Entries";
	IsHandled: Boolean;
    begin
	IsHandled := false;
	OnBeforeUnApplyVendor(DtldVendLedgEntry, IsHandled);
	if IsHandled then
		exit;

        DtldVendLedgEntry.TestField("Entry Type", DtldVendLedgEntry."Entry Type"::Application);
        DtldVendLedgEntry.TestField(Unapplied, false);
        UnapplyVendEntries.SetDtldVendLedgEntry(DtldVendLedgEntry."Entry No.");
        UnapplyVendEntries.LookupMode(true);
        UnapplyVendEntries.RunModal();

        OnAfterUnApplyVendor(DtldVendLedgEntry);
    end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeUnApplyVendor(DtldVendLedgEntry: Record "Detailed Vendor Ledg. Entry"; var IsHandled: Boolean);
begin
end;

```

### Additional context

We want to skip unapplying in certain scenarios.
Internal work item: [AB#500434](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500434)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16418.
