### ISSUE TITLE
[EVENT REQUEST] report 5899 "Calculate Inventory Value" – OnBeforeCheckNegCost |  codeunit 5804 ItemCostManagement – OnBeforeCheckNegCost

### ISSUE THREAD

**Issue by aleobi** [microsoft/ALAppExtensions#25919]
### Describe the request

We necessarily need a possibility to bypass setting the "Unit Cost" field to zero on Item Card, as soon it becomes negative and also (even more important!) to bypass setting the "Inventory Value (Calculated)" to zero in the Revaluation Journal, as soon as it becomes negative:

report 5899 "Calculate Inventory Value":
```
local procedure CalcAverageUnitCost(BufferQty: Decimal; var InvtValueCalc: Decimal; var AppliedAmount: Decimal)
var
    ...
    //> New
    IsHandled: boolean;
    //< New
begin
    ...
           
    if AverageQty <> 0 then begin
        AverageUnitCostLCY := AverageCost / AverageQty;
        //> New
        IsHandled := false;
        OnBeforeCheckNegCost(AverageUnitCostLCY, IsHandled);
        if not IsHandled then
        //< New
            if AverageUnitCostLCY < 0 then
                AverageUnitCostLCY := 0;
    end else
        AverageUnitCostLCY := 0;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckNegCost(var AverageUnitCostLCY: Decimal; var IsHandled: Boolean)
begin
end;
```

codeunit 5804 ItemCostManagement:

```
procedure CalculateAverageCost(var Item: Record Item; var AverageCost: Decimal; var AverageCostACY: Decimal): Boolean
var
    ...
    //> New
    IsHandled: boolean;
    //< New
begin
    ...
    if AverageQty <> 0 then begin
        ...
        //> New        
        IsHandled := false;
        OnBeforeCheckNegCost(AverageCost, AverageCostACY, IsHandled);
        if not IsHandled then begin
        //< New
            if AverageCost < 0 then
                AverageCost := 0;
            if AverageCostACY < 0 then
                AverageCostACY := 0;
        //> New
        end;  
        //< New
    end else begin
        AverageCost := 0;
        AverageCostACY := 0;
    end;
    if AverageQty <= 0 then
        exit(false);

    exit(true);
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckNegCost(var AverageCost: Decimal; var AverageCostACY: Decimal; var IsHandled: Boolean)
begin
end;

```

Really looking forward to your help! Thank you!

### Additional context

Most of our customers are coming from waste industries, where receiving money for incoming material is a realistic and also everyday scenario ??? therefore our customers have the really need to be able to handle negative inventory values in Business Central. This mainly works in BC, except those both mentioned code lines where negative values are set to zero.
Internal work item: [AB#500553](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500553)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16418.
