### ISSUE TITLE
[Event Request] codeunit 1313 "Correct Posted Purch. Invoice" - OnBeforeTestPurchaseInvoiceHeaderAmount

### ISSUE THREAD

**Issue by AlexanderWittek** [microsoft/ALAppExtensions#25926]
### Describe the request

As in the sales area, we need a new IntegrationEvent "OnBeforeTestPurchaseInvoiceHeaderAmount" to cancel purchase invoices with zero amount.

codeunit 1313 "Correct Posted Purch. Invoice"

    procedure TestCorrectInvoiceIsAllowed(var PurchInvHeader: Record "Purch. Inv. Header"; Cancelling: Boolean)
    begin
        CancellingOnly := Cancelling;

	// Start
        TestPurchaseInvoiceHeaderAmount(PurchInvHeader, Cancelling);
	// Stop
        TestIfPostingIsAllowed(PurchInvHeader);
        TestIfInvoiceIsCorrectedOnce(PurchInvHeader);
        TestIfInvoiceIsNotCorrectiveDoc(PurchInvHeader);
        TestIfInvoiceIsPaid(PurchInvHeader);
        TestIfVendorIsBlocked(PurchInvHeader, PurchInvHeader."Buy-from Vendor No.");
        TestIfVendorIsBlocked(PurchInvHeader, PurchInvHeader."Pay-to Vendor No.");
        TestVendorDimension(PurchInvHeader, PurchInvHeader."Pay-to Vendor No.");
        TestDimensionOnHeader(PurchInvHeader);
        TestPurchaseLines(PurchInvHeader);
        TestIfAnyFreeNumberSeries(PurchInvHeader);
        TestExternalDocument(PurchInvHeader);
        TestInventoryPostingClosed(PurchInvHeader);

        OnAfterTestCorrectInvoiceIsAllowed(PurchInvHeader, Cancelling);
    end;

    // Start
    local procedure TestPurchaseInvoiceHeaderAmount(var PurchInvHeader: Record "Purch. Inv. Header"; Cancelling: Boolean)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeTestPurchaseInvoiceHeaderAmount(PurchInvHeader, Cancelling, IsHandled);
        if IsHandled then
            exit;

        PurchInvHeader.CalcFields(Amount);
        PurchInvHeader.TestField(Amount);
    end;
    // Stop

...

    // Start
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTestPurchaseInvoiceHeaderAmount(var var PurchInvHeader: Record "Purch. Inv. Header"; Cancelling: Boolean; var IsHandled: Boolean)
    begin
    end;
    // Stop

### Additional context

As in the sales area, we need a new IntegrationEvent "OnBeforeTestPurchaseInvoiceHeaderAmount" to cancel purchase invoices with zero amount.
Internal work item: [AB#500665](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500665)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16418.
