### ISSUE TITLE
[Event Request] codeunit 432 Consolidate - OnCheckAmountArrayOnBeforeReportError

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#25929]
### Describe the request

Hello, can you please add a new event OnCheckAmountArrayOnBeforeReportError to codeunit 432 Consolidate?

```
    local procedure CheckAmountArray()
    var
        idx: Integer;
	IsHandled: Boolean;
    begin
        for idx := 1 to MaxDeletedIndex do
            if DeletedAmounts[idx] <> 0 then
		IsHandled := false;
		OnCheckAmountArrayOnBeforeReportError(DeletedAmounts, DeletedDates, idx, IsHandled);
		if not IsHandled then
                    ReportError(StrSubstNo(Text010 + Text011, DeletedAmounts[idx], DeletedDates[idx]));
    end;
```

```
[IntegrationEvent(false, false)]
local procedure OnCheckAmountArrayOnBeforeReportError(var DeletedAmountsArray: array[500] of Decimal; var DeletedDatesArray: array[500] of Date; DeletedIndex: Integer; var IsHandled: Boolean)
begin
end;
```

### Additional context

We want to skip errors in certain scenarios.
Internal work item: [AB#500732](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500732)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16418.
