### ISSUE TITLE
[Request for External] "Master Data Full Synch. R. Ln." - Generate() and Start()

### ISSUE THREAD

**Issue by neverbeam** [microsoft/ALAppExtensions#25922]
### Describe the request

We would like to request the change of function scope from Internal to Global.
Currently the Master Data Managenent extension has a lot of internal procedures and can hardly be used for extension development. We would like to setup the tool for our customers from code. For this we need 2 function scopes changed.

Extension: Master Data Management
Object: table 7233 "Master Data Full Synch. R. Ln."

We would like to request the following 2 interal function to be changed to global so that they can be used for extension development.

    internal procedure Generate(var InitialSynchRecommendations: Dictionary of [Code[20], Integer]; SkipEntitiesNotFullSyncReady: Boolean; DeletedLines: List of [Code[20]])

    internal procedure Start()

### Additional context

We would like to setup the tool for our customers from code. Currently the extension Master Data Mangement is very closed and extensibility is very limited.
Internal work item: [AB#500603](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500603)

**Comment by dcenic** [comment]
This is checked in and will be available in Business Central 24.1. I have also added an event in codeunit "Master Data Management". This is raised when Master Data Full Synch Review Lines are generated. Append your custom mappings to the filter so that the custom tables are included in the initial synch. Remember to set "Dependency Filter" on the mapping, to specify which one should it run after (this applies only to the initial synch - delta synch runs randomly, as changes happen in the source).

    [IntegrationEvent(false, false)]
    internal procedure OnAfterSetIntegrationTableMappingFilterForInitialSynch(var IntegrationTableMappingFilter: Text)
    begin
        // append the names of the custom table mappings to the IntegrationTableMappingFilter: it is an 'or' filter, so concatenate the names by |
    end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 18092.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18090.
