### ISSUE TITLE
[BC Idea]: Modify Table Property NotBlank

### ISSUE THREAD

**Issue by KarelKoncel** [microsoft/ALAppExtensions#25921]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=9ba37144-6bca-ee11-92bd-6045bdba960a

### Description

Hi,
Would it be possible to have the NotBlank parameter editable from the table extension?
We want to create No. Series on table Ship-To Address, but it is not posible, becouse field Code on table is set NotBlank = TRUE.
Best Regards

Karel Koncel

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea

**Comment by JesperSchulz** [comment]
Interesting idea! Unfortunately, this repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

For suggestions to the Business Central product group, please create a [BC Idea](https://aka.ms/bcideas).
