### ISSUE TITLE
[Parameter Request] - Codeunit 5763 "Whse.-Post Shipment" OnAfterFindWhseShptLineForTransLine

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#25927]
### Describe the request

Can you please add ModifyLine to OnAfterFindWhseShptLineForTransLine

### Additional context

    local procedure HandleTransferLine(var WhseShptLine: Record "Warehouse Shipment Line")
    var
        TransLine: Record "Transfer Line";
        ModifyLine: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeHandleTransferLine(WhseShptLine, TransLine, WhseShptHeader, ModifyLine, IsHandled);
        if IsHandled then
            exit;

        TransLine.SetRange("Document No.", WhseShptLine."Source No.");
        TransLine.SetRange("Derived From Line No.", 0);
        if TransLine.Find('-') then
            repeat
                WhseShptLine.SetRange(WhseShptLine."Source Line No.", TransLine."Line No.");
                if WhseShptLine.Find('-') then begin
                    IsHandled := false;
                    //OnAfterFindWhseShptLineForTransLine(WhseShptLine, TransLine, IsHandled);  // OLD
                    OnAfterFindWhseShptLineForTransLine(WhseShptLine, TransLine, IsHandled, ModifyLine);   // NEW
                    if not IsHandled then begin
                        ModifyLine := TransLine."Qty. to Ship" <> WhseShptLine."Qty. to Ship";
                        if ModifyLine then
                            ValidateTransferLineQtyToShip(TransLine, WhseShptLine);
                    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterFindWhseShptLineForTransLine(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var TransferLine: Record "Transfer Line"; var IsHandled: Boolean; var ModifyLine: Boolean)   // NEW
    //local procedure OnAfterFindWhseShptLineForTransLine(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var TransferLine: Record "Transfer Line"; var IsHandled: Boolean)  // OLD
    begin
    end;
Internal work item: [AB#500731](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500731)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16418.
