### ISSUE TITLE
[Event Request] "Price Helper - V16" Procedure DeletePrices -> Make it better

### ISSUE THREAD

**Issue by chrischbo** [microsoft/ALAppExtensions#25936]
### Describe the request

Hi,

regarding the old issue https://github.com/microsoft/ALAppExtensions/issues/25838 it would be helpful to get the handled pattern as requested. Your addition of the publishers are a great help but the price list header will still be deleted anyway so we can't handle this. The code in this section is still wrong and a price list header should never be deleted if there are lines that may have other conditions than the header.

So please add a check and don't delete the header or give us at least the option to handle it.

OnBeforeDeletePrices(SourceType, SourceNo, ParentSourceNo, **isHandled**);  // add isHandled
**if not isHandled then begin  // new**
    PriceListHeader.SetRange("Source Type", SourceType);
    PriceListHeader.SetRange("Parent Source No.", ParentSourceNo);
    PriceListHeader.SetRange("Source No.", SourceNo);
    if not PriceListHeader.IsEmpty() then
        PriceListHeader.DeleteAll();        
**end; // new**

Thanks and kind regards,
Christian

### Additional context

DO NOT delete price list headers which still have line data
Internal work item: [AB#500781](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500781)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17376.
