### ISSUE TITLE
[Change Request] codeunit 432 Consolidate - procedure CreateAndPostGenJnlLine

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#25935]
### Describe the request

Hello, can you please change the local procedure CreateAndPostGenJnlLine to global?

```
procedure CreateAndPostGenJnlLine(GenJnlLine: Record "Gen. Journal Line"; var GLEntry: Record "G/L Entry"; var DimBuf: Record "Dimension Buffer")
var
	TempDimSetEntry2: Record "Dimension Set Entry" temporary;
	DimValue: Record "Dimension Value";
	ConsolidAmount: Decimal;
	AmountToPost: Decimal;
	AdjustAmount: Decimal;
	ClosingAmount: Decimal;
	TranslationNeeded: Boolean;
	idx: Integer;
	OriginalTranslationMethod: Integer;
begin
```

### Additional context

We want to access from custom extension.
Internal work item: [AB#500752](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500752)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17192.
