### ISSUE TITLE
Bypass shipping time management on sales (lines) and transfer (order and lines)

### ISSUE THREAD

**Issue by jfpanarotto** [microsoft/ALAppExtensions#25942]
### Describe the request

Hello

**For the management of sales lines**
There is an OnBeforeValidateShippingAgentServiceCode event but if we use it to bypass your shipping time management, we will not have any future changes of your shipping agent service management.
Please, would it be possible to put the shipping time management of the Sales Line table in a GetShippingTime function with an OnBeforeGetShippingTime event as is done on the Sales Header table?
![image](https://github.com/microsoft/ALAppExtensions/assets/47528116/14ac2996-a2e6-4c97-87c5-71cdcbc626a7)

**For the management of transfer orders**
Please, would it be possible to add an OnBeforeGetShippingTime event in the GetShippingTime function of the Transfer Route table as there is one in the same function of the Sales Header table?
![image](https://github.com/microsoft/ALAppExtensions/assets/47528116/c3d2523c-bfb2-450a-a7ef-f55c1775c9ef)
  
Thank you in advance for your response

### Additional context

We manage the shipping time of sales orders and transfer orders via information other than the customer or the shipping agent service. So, we need to bypass standard management.
Internal work item: [AB#501008](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501008)
Internal work item: [AB#501008](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501008)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19985.
