### ISSUE TITLE
Codeunit 444 "Purchase-Post Prepayments" - CheckOpenPrepaymentLines

### ISSUE THREAD

**Issue by JOUAIRY** [microsoft/ALAppExtensions#25945]
### Describe the request

`    procedure CheckOpenPrepaymentLines(PurchHeader: Record "Purchase Header"; DocumentType: Option) Found: Boolean
    var
        PurchLine: Record "Purchase Line";
    begin
        with PurchLine do begin
            ApplyFilter(PurchHeader, DocumentType, PurchLine);
            if Find('-') then
                repeat
                    if not Found then
                        Found := PrepmtAmount(PurchLine, DocumentType) <> 0;
                    if "Prepmt. Amt. Inv." = 0 then begin
                        UpdatePrepmtSetupFields();
                        Modify();
                    end;
                until Next() = 0;
        end;
        exit(Found);
    end;`

### Additional context

Could you please add the event OnBefore and OnAfter on Codeunit 444 "Purchase-Post Prepayments"
Internal work item: [AB#501338](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501338)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16627.
