### ISSUE TITLE
[Change Request] codeunit 99000774 "Calculate Routing Line" - procedures CalcRoutingLineBack and CalcRoutingLineForward

### ISSUE THREAD

**Issue by TineNickel** [microsoft/ALAppExtensions#25943]
### Describe the request

Hello, can you please change the local procedures CalcRoutingLineBack and CalcRoutingLineForwardto global so that we can avoid copying code?

### Additional context

We want to access from a Codeunit.
Internal work item: [AB#501009](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501009)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19985.
