### ISSUE TITLE
[Bug]: Filter for related Check Ledger Entry from Bank Acconut Ledger Entry

### ISSUE THREAD

**Issue by lkatrei** [microsoft/ALAppExtensions#25949]
### Describe the issue

Hi,

we created our own functionality for the creation and handling of "Check Ledger Entry" and tried to allign it as much as possible with Business Central standard. In BC standard "Check No." and "Document No." are the same. In our case "Check No." is also filled from "Last Check No. used" from "Bank Acconut", but "Document No." is filled through a numberseries. When creating and posting a bank account ledger entry and trying to find and connect it with the created check ledger entry, the entry can not be found, as the SetRange is set on "Check No." instead of "Document No.

### Expected behavior

Suggestion: the marked CheckLedgerEntry (procedure PostBankAcc in codeunit "Gen. Jnl.-Post Line" should be filtered on "Document No." instead of "Check No." (replace CheckLedgEntry.Setrange("Check No.", "Document No." with CheckLedgEntry.Setrange("Document No., "Document No.");)
![grafik](https://github.com/microsoft/ALAppExtensions/assets/77351342/2f46102c-0a01-46e3-8a48-e5edfc4bccf1)

### Steps to reproduce

- create a Gen. Journal Line with relevant check fields filled ("Account Type"::"Bank Account", "Check printed" = true, "Bank Payment Type"::"Computer Check")
- create and print a Check Ledger Entry with a "Check No." and fill "Document No." with "Gen. Journal Line"."Document No."
- post the Gen. Journal Line (and Bank Account Ledger Entry is created)
- procedure PostBankAcc in codeunit "Gen. Jnl.-Post Line" is called. The created "Check Ledger Entry" can not be found, as the filter is set on "Check No." instead of "Document No."

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
That sounds like a product defect! Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps). We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
