### ISSUE TITLE
[Event Parameter Request] Codeunit 5870 "Calculate BOM Tree" - Event "OnGenerateProdCompSubTreeOnAfterBOMBufferModify"

### ISSUE THREAD

**Issue by mdemaio9** [microsoft/ALAppExtensions#25946]
### Describe the request

Hello,
we need the global variable "TreeType" of the Codeunit 5870 "Calculate BOM Tree" as parameter in the event "OnGenerateProdCompSubTreeOnAfterBOMBufferModify".

`[IntegrationEvent(false, false)]
    local procedure OnGenerateProdCompSubTreeOnAfterBOMBufferModify(var BOMBuffer: Record "BOM Buffer"; RoutingLine: Record "Routing Line"; LotSize: Decimal; ParentItem: Record Item; ParentBOMBuffer: Record "BOM Buffer")
    begin
    end;`

### Additional context

.
Internal work item: [AB#501507](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501507)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16627.
