### ISSUE TITLE
codeunit 248 "VAT Lookup Ext. Data Hndl" - OnPrepareSOAPRequestBodyOnBeforeSetAccountDetails

### ISSUE THREAD

**Issue by FSchneiderYav** [microsoft/ALAppExtensions#25948]
### Describe the request

In codeunit 248 "VAT Lookup Ext. Data Hndl" is the publisher OnPrepareSOAPRequestBodyOnBeforeSetAccountDetails called with false parameters

### Additional context

```
        if VATRegistrationLog.GetAccountRecordRef(RecordRef) then begin
            AccountName := GetField(RecordRef, Customer.FieldName(Name));
            AccountStreet := GetField(RecordRef, Customer.FieldName(Address));
            AccountPostCode := GetField(RecordRef, Customer.FieldName("Post Code"));
            AccountCity := GetField(RecordRef, Customer.FieldName(City));
-           OnPrepareSOAPRequestBodyOnBeforeSetAccountDetails(RecordRef, VATRegistrationLog, AccountName, AccountStreet, AccountPostCode, AccountCity);
+           OnPrepareSOAPRequestBodyOnBeforeSetAccountDetails(RecordRef, VATRegistrationLog, AccountName, AccountStreet, AccountCity, AccountPostCode);
            VATRegistrationLog.SetAccountDetails(AccountName, AccountStreet, AccountCity, AccountPostCode);
        end;
```
Internal work item: [AB#501571](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501571)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16627.
