### ISSUE TITLE
[Event Change Request] Codeunit 80 Sales-Post - procedure PostUpdateOrderLine - event OnPostUpdateOrderLineOnBeforeGetQuantityShipped

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#25940]
### Describe the request

We would like the Parameter/-s TempSalesLine as var added to the following event.

Original:

```
Codeunit 80 Sales-Post - procedure PostUpdateOrderLine - event OnPostUpdateOrderLineOnBeforeGetQuantityShipped

OnPostUpdateOrderLineOnBeforeGetQuantityShipped(TempSalesLine, IsHandled, SalesHeader);

[IntegrationEvent(false, false)]
local procedure OnPostUpdateOrderLineOnBeforeGetQuantityShipped(TempSalesLine: Record "Sales Line"; var IsHandled: Boolean; var SalesHeader: Record "Sales Header")
begin
end;

```

Change:

```
[IntegrationEvent(false, false)]
local procedure OnPostUpdateOrderLineOnBeforeGetQuantityShipped(var TempSalesLine: Record "Sales Line"; var IsHandled: Boolean; var SalesHeader: Record "Sales Header") // <-- we need parameter TempSalesLine to be set to var
begin
end;

```

### Additional context

Parameter TempSalesLine needs to be changed by our own functionality - that's why var is necessary
Internal work item: [AB#500794](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/500794)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17295.
