### ISSUE TITLE
codeunit 1385 "Vendor Templ. Mgt." - OnBeforeInitVendorNo

### ISSUE THREAD

**Issue by angelocitro** [microsoft/ALAppExtensions#25944]
### Describe the request

procedure InitVendorNo(var Vendor: Record Vendor; VendorTempl: Record "Vendor Templ.")
    var
        NoSeriesManagement: Codeunit NoSeriesManagement;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeVendorItemNo(Item, ItemTempl, IsHandled);
        if IsHandled then
            exit;

        if VendorTempl."No. Series" = '' then
            exit;

        NoSeriesManagement.InitSeries(VendorTempl."No. Series", '', 0D, Vendor."No.", Vendor."No. Series");
    end;

### Additional context

Could you please add the event OnBeforeVendorItemNo in InitVendorNo procedure for codeunit 1385 "Vendor Templ. Mgt."?
Internal work item: [AB#501673](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501673)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16627.
