### ISSUE TITLE
Demand acces to procedure "TransferDimensionSetID" in codeunit 2679 "Purchase Alloc. Acc. Mgt."

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#25947]
### Describe the request

is it possible to open up the procedure TransferDimensionSetID in the codeunit 2679 "Purchase Alloc. Acc. Mgt.".

### Additional context

when we use the event "OnBeforeCreatePurchaseLine" to validate additional fields on the pruchase line, we validate a field that has an default dimension attached. validating that, removes the dimension from the allocation account. so we would be able to restore these dimensions with that function.

in addition, when validating fields on a purchase line that have default dimension attached, always seems to remove any dimensions that ware placed manually on the line/dimensions that not come from default dimensions.
maybe these dimensions should not be removed?
Internal work item: [AB#501508](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501508)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21326.
