### ISSUE TITLE
Page 233 "Apply Vendor Entries" - procedure PostDirectApplication(PreviewMode: Boolean) - OnPostDirectApplicationOnBeforeCheckApplicationDate

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#25956]
### Describe the request

Could You please, add the following event to the Page 233 "Apply Vendor Entries"

Object: Page 233 "Apply Vendor Entries"
procedure PostDirectApplication(PreviewMode: Boolean)

Microsoft_Base Application_23.4.15643.16092.app

Publisher Event: OnPostDirectApplicationOnBeforeCheckApplicationDate(NewApplyUnapplyParameters, ApplicationDate, PreviewMode, IsHandled)

Reason: To implement custom business logic and permit avoid the checking of ApplyingDate
Where is the event placed (see image attached)?:
![image](https://github.com/microsoft/ALAppExtensions/assets/73465025/a75950c6-be1e-4c26-acff-80779a1fee07)

Just before the line 1475: if NewApplyUnapplyParameters."Posting Date" < ApplicationDate then
Insert the next lines:
                    IsHandled := false;
                    OnPostDirectApplicationOnBeforeCheckApplicationDate(Rec, NewApplyUnapplyParameters, ApplicationDate, PreviewMode, IsHandled);
                    if not IsHandled then

![image](https://github.com/microsoft/ALAppExtensions/assets/73465025/575b0690-f784-4f0e-9f43-688a4b0feffe)

Event code:
    [IntegrationEvent(TRUE, false)]
    local procedure OnPostDirectApplicationOnBeforeCheckApplicationDate(VendorLedgerEntry: Record "Vendor Ledger Entry"; NewApplyUnapplyParameters: Record "Apply Unapply Parameters"; ApplicationDate: Date; PreviewMode: Boolean; var IsHandled: Boolean)
    begin
    end;

Thanks in advance.

### Additional context

Our customer needs to apply vendor entries when the "Application Date" is greater than the "Posting Date".
Internal work item: [AB#501681](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501681)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16627.
