### ISSUE TITLE
[Event Change] Add ForceConfirm to OnBeforeConfirmUpdateCurrencyFactor in Purchase Header

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#25954]
### Describe the request

It's not a good practice to set HideValidationDialog to true, just to skip the currency factor update confirmation. Please add a parameter to just confirm this specific dialog.

```diff
    procedure ConfirmCurrencyFactorUpdate(): Boolean
    begin
-        OnBeforeConfirmUpdateCurrencyFactor(Rec, HideValidationDialog);
+        OnBeforeConfirmUpdateCurrencyFactor(Rec, HideValidationDialog, ForceConfirm); 
-        if GetHideValidationDialog() or not GuiAllowed then
+        if GetHideValidationDialog() or not GuiAllowed() or ForceConfirm then 
            Confirmed := true
        else
            Confirmed := Confirm(Text022, false);
        if Confirmed then
            Validate("Currency Factor")
        else
            "Currency Factor" := xRec."Currency Factor";
        OnAfterConfirmUpdateCurrencyFactor(Rec, HideValidationDialog);
        exit(Confirmed);
    end;
```

```diff
[IntegrationEvent(false, false)]
-    local procedure OnBeforeConfirmUpdateCurrencyFactor(var PurchaseHeader: Record "Purchase Header"; var HideValidationDialog: Boolean)
+    local procedure OnBeforeConfirmUpdateCurrencyFactor(var PurchaseHeader: Record "Purchase Header"; var HideValidationDialog: Boolean; var ForceConfirm: Boolea) 
    begin
    end;
```

### Additional context

We could reset the HideValidationDialog via ``OnAfterConfirmUpdateCurrencyFactor`` afterwards, but we would have to keep the previous state in memory with a SingleInstance codeunit.
Internal work item: [AB#501637](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501637)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16627.
