### ISSUE TITLE
[Event Change] Add ForceConfirm to OnBeforeConfirmUpdateCurrencyFactor in Sales Header

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#25953]
### Describe the request

It's not a good practice to set HideValidationDialog to true, just to skip the currency factor update confirmation. Please add a parameter to just confirm this specific dialog.

```diff
    procedure ConfirmCurrencyFactorUpdate()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
-        OnBeforeConfirmUpdateCurrencyFactor(Rec, HideValidationDialog, xRec, IsHandled);
+        OnBeforeConfirmUpdateCurrencyFactor(Rec, HideValidationDialog, xRec, IsHandled, ForceConfirm);
        if IsHandled then
            exit;

-        if GetHideValidationDialog() or not GuiAllowed() then
+        if GetHideValidationDialog() or not GuiAllowed() or ForceConfirm then
            Confirmed := true
        else
            Confirmed := Confirm(Text021, false);
        if Confirmed then
            Validate("Currency Factor")
        else
            "Currency Factor" := xRec."Currency Factor";

        OnAfterConfirmCurrencyFactorUpdate(Rec, Confirmed);
    end;
```

```diff
[IntegrationEvent(false, false)]
-    local procedure OnBeforeConfirmUpdateCurrencyFactor(var SalesHeader: Record "Sales Header"; var HideValidationDialog: Boolean; var xSalesHeader: Record "Sales Header"; var IsHandled: Boolean)
+    local procedure OnBeforeConfirmUpdateCurrencyFactor(var SalesHeader: Record "Sales Header"; var HideValidationDialog: Boolean; var xSalesHeader: Record "Sales Header"; var IsHandled: Boolean; var ForceConfirm: Boolean)
    begin
    end;
```

### Additional context

We could reset the HideValidationDialog via ``OnAfterConfirmCurrencyFactorUpdate`` afterwards, but we would have to keep the previous state in memory with a SingleInstance codeunit.
Internal work item: [AB#501636](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501636)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16506.
