### ISSUE TITLE
Access Factboxes from Extensions with CurrPage

### ISSUE THREAD

**Issue by Regatoni** [microsoft/ALAppExtensions#25955]
### Describe the request

When trying to access a Function on a Factbox, that is not in the Base App, but in another Extension, it is not possible to access it through CurrPage.[FACTBOX].Page.[FUNCTION NAME].
The Following Error is beign thrown:
![grafik](https://github.com/microsoft/ALAppExtensions/assets/160514563/4fc15490-f3a4-48a9-beb3-ae3fb3fe51af)
The Function "Refresh" is a global Function on the Factbox Page. The Factbox can be accessed with modify in the Layout Section. 

Base App Factboxes can be accessed with CurrPage:
![grafik](https://github.com/microsoft/ALAppExtensions/assets/160514563/98325fbc-b80a-465a-b161-e6a71eb17395)

### Additional context

We have Code that needs to be Updated while the User is on the Page. A normal CurrPage.Update() does not suffice

**Comment by JesperSchulz** [comment]
Unfortunately, this repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

For suggestions to the Business Central product group, please create a [BC Idea](https://aka.ms/bcideas).

If you want to log a support case, please visit:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
