### ISSUE TITLE
[Event Request] Table 167 Resource ExistUnprocessedTimeSheets

### ISSUE THREAD

**Issue by LewisHyettTES** [microsoft/ALAppExtensions#25952]
### Describe the request

Please add the following event to the 167 "Resource" procedure ExistUnprocessedTimeSheets

```
local procedure ExistUnprocessedTimeSheets(): Boolean
var
	TimeSheetHeader: Record "Time Sheet Header";
	TimeSheetLine: Record "Time Sheet Line";
	Result: boolean;
	IsHandled: Boolean;
begin
	OnBeforeExistsUnprocessedTimeSheets(Rec, Result, IsHandled);
	if IsHandled then
		exit(Result);
		
	TimeSheetHeader.SetCurrentKey("Resource No.");
	TimeSheetHeader.SetRange("Resource No.", "No.");
	if TimeSheetHeader.FindSet() then
		repeat
			TimeSheetLine.SetRange("Time Sheet No.", TimeSheetHeader."No.");
			TimeSheetLine.SetRange(Posted, false);
			if not TimeSheetLine.IsEmpty() then
				exit(true);
		until TimeSheetHeader.Next() = 0;

	exit(false);
end;
```
```
[EventSubscriber(ObjectType::Table, Database::"Resource",OnBeforeExistsUnprocessedTimeSheets, '', false, false)]
local procedure OnBeforeExistsUnprocessedTimeSheets(Rec: Record Resource; var Result: Boolean; var IsHandled: boolean);
begin
end;
```

### Additional context

We would like to allow the modification of assigned users when unposted timesheets exist. 
Internal work item: [AB#501638](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501638)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16627.
