### ISSUE TITLE
Enhancement Request - Increase Size of EndtoEndIdTxt Variable and Add Event for Report SEPA ISO20022

### ISSUE THREAD

**Issue by AymanAYDI** [microsoft/ALAppExtensions#25965]
### Describe the request

Report ID: 10883 
Report Name: SEPA ISO20022
 
At the local procedure **ExportPaymentInformation()** for the **SEPA ISO20022** report, there is a need to enhance the functionality by increasing the size of the **EndtoEndIdTxt** variable from **Text[30]** to **Text[35]**. Additionally, an event named **OnBeforeAddEndtoEndIdToXmlAsElement** needs to be introduced after the initialization of the `EndtoEndIdTxt` variable and before the execution of the `AddElement` function. This event is essential for allowing users to modify the value of the `EndtoEndIdTxt` variable based on certain conditions.
 
**Details:**
 
```al
// Inside the local procedure "Export Payment Information"
 
// Existing code
EndtoEndIdTxt := PaymentLine."Document No.";
if DelChr(EndtoEndIdTxt, '<>') = '' then
    EndtoEndIdTxt := 'NOTPROVIDED';
 
// New requirement
OnBeforeAddEndtoEndIdToXmlAsElement(EndtoEndIdTxt, PaymentLine);
 
AddElement(XMLNodeCurr, 'EndToEndId', CopyStr(EndtoEndIdTxt, 1, 35), '', XMLNewChild);
 
// New event definition
[IntegrationEvent(false, false)]
local procedure OnBeforeAddEndtoEndIdToXmlAsElement(var EndtoEndIdTxt: Text[35]; var PaymentLine: Record "Payment Line")
begin
    // User-defined logic goes here
end;
```

### Additional context

**Additional Information:**
 
- The `EndtoEndIdTxt` variable should be expanded from `Text[30]` to `Text[35]`.
- The `OnBeforeAddEndtoEndIdToXmlAsElement` event should be triggered after the initialization of `EndtoEndIdTxt` and before the `AddElement` function.
- Users need the ability to customize the value of `EndtoEndIdTxt` based on specific conditions within the event.
 
This enhancement will provide greater flexibility for users to customize the behavior of the SEPA ISO20022 export process.

Dispose d???un menu contextuel
Internal work item: [AB#501828](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501828)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 18665.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18666.
