### ISSUE TITLE
[Event Parameters Request] table 5406 "Prod. Order Line" - OnAfterGetUpdateFromSKU

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#25964]
### Describe the request

We would like to get the Item and SKU variables as well. It prevents the extra Gets ourselves when the Base code has already retrieved them.

    local procedure GetUpdateFromSKU()
    ....
        OnAfterGetUpdateFromSKU(Rec, Item, SKU);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetUpdateFromSKU(var ProdOrderLine: Record "Prod. Order Line"; var Item: Record Item; var SKU: Record "Stockkeeping Unit")
    begin
    end;

### Additional context

We have added "Scrap %" to Stockkeepingunit
Internal work item: [AB#501814](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501814)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16506.
