### ISSUE TITLE
[Event Request] Codeunit 1535 "Approvals Mgmt." - OnCalcPurchaseDocAmountOnAfterPurchPostGetPurchLines

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#25960]
### Describe the request

Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnCalcPurchaseDocAmountOnAfterPurchPostGetPurchLines' to be added to procedure CalcPurchaseDocAmount in codeunit 1535 "Approvals Mgmt.".

````
procedure CalcPurchaseDocAmount(PurchaseHeader: Record "Purchase Header"; var ApprovalAmount: Decimal; var ApprovalAmountLCY: Decimal)
    var
        TempPurchaseLine: Record "Purchase Line" temporary;
        TotalPurchaseLine: Record "Purchase Line";
        TotalPurchaseLineLCY: Record "Purchase Line";
        PurchPost: Codeunit "Purch.-Post";
        TempAmount: Decimal;
        VAtText: Text[30];
    begin
        PurchaseHeader.CalcInvDiscForHeader();
        PurchPost.GetPurchLines(PurchaseHeader, TempPurchaseLine, 0);
        OnCalcPurchaseDocAmountOnAfterPurchPostGetPurchLines(TempPurchaseLine); //new
        Clear(PurchPost);
        PurchPost.SumPurchLinesTemp(
          PurchaseHeader, TempPurchaseLine, 0, TotalPurchaseLine, TotalPurchaseLineLCY,
          TempAmount, VAtText);
        ApprovalAmount := TotalPurchaseLine.Amount;
        ApprovalAmountLCY := TotalPurchaseLineLCY.Amount;
 
        OnAfterCalcPurchaseDocAmount(PurchaseHeader, TotalPurchaseLine, TotalPurchaseLineLCY, ApprovalAmount, ApprovalAmountLCY);
    end;
````
````
[IntegrationEvent(false, false)]
    local procedure OnCalcPurchaseDocAmountOnAfterPurchPostGetPurchLines(var TempPurchaseLine: Record "Purchase Line" temporary)
    begin
      //new
    end;
````

### Additional context

To determine the amount of the purchase order, we want to exclude the purchase lines that are already approved from the TempPurchaseLine so the correct amount is used in the approval entries.
Internal work item: [AB#501763](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501763)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16627.
