### ISSUE TITLE
[Event Request] report 94 "Close Income Statement" at local procedure ValidateEndDate

### ISSUE THREAD

**Issue by iyiannak** [microsoft/ALAppExtensions#25963]
### Describe the request

On report 94 "Close Income Statement" at local procedure ValidateEndDatewe would like to add an event OnValidateEndDate(EndDateReq: Date; var FiscalYearStartDate: Date; var FiscYearClosingDate: Date; var OK: Boolean; var IsHandled: Boolean)

and modify the procedure ValidateEndDate as per below:

local procedure ValidateEndDate(RealMode: Boolean): Boolean
var
    OK: Boolean;
    IsHandled: Boolean;
begin
    if EndDateReq = 0D then
        exit;
        
    OnValidateEndDate(EndDateReq, FiscalYearStartDate, FiscYearClosingDate, OK, IsHandled);
    
    if not IsHandled then begin
      OK := AccountingPeriod.Get(EndDateReq + 1);
      if OK then
          OK := AccountingPeriod."New Fiscal Year";
      if OK then begin
          if not AccountingPeriod."Date Locked" then begin
              if not RealMode then
                  exit;
              Error(Text014);
          end;
          FiscYearClosingDate := ClosingDate(EndDateReq);
          AccountingPeriod.SetRange("New Fiscal Year", true);
          OK := AccountingPeriod.Find('<');
          FiscalYearStartDate := AccountingPeriod."Starting Date";
      end;
    end;
    if not OK then begin
        if not RealMode then
            exit;
        Error(Text015);
    end;
    exit(true);
end;

[IntegrationEvent(false, false)]
local procedure OnValidateEndDate(EndDateReq: Date; var FiscalYearStartDate: Date; var FiscYearClosingDate: Date; var OK: Boolean; var IsHandled: Boolean);
begin
end;

Internal work item: [AB#501795](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501795)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16627.
