### ISSUE TITLE
[Event Request] Reports 10401 "Check (Stub/Stub/Check)" - OnAfterGetRecordOfPrintSettledLoop &  10411 "Check (Stub/Check/Stub)" - OnAfterGetRecordOfPrintSettledLoop

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/ALAppExtensions#25973]
### Describe the request

Hi,

I would like to request the following event publisher in 
**Report 10401 "Check (Stub/Stub/Check)" - OnAfterGetRecordOfPrintSettledLoop**  &&  

**Report 10411 "Check (Stub/Check/Stub)" - OnAfterGetRecordOfPrintSettledLoop**

trigger - **PrintSettledLoop**  OnAfterGetRecord

                 if DocNo = '' then
                    CurrencyCode2 := GenJnlLine."Currency Code";

                    Stub2LineNo := Stub2LineNo + 1;
                    Stub2DocNo[Stub2LineNo] := DocNo;
                    Stub2DocDate[Stub2LineNo] := DocDate;
                    Stub2LineAmount[Stub2LineNo] := LineAmount;
                    Stub2LineDiscount[Stub2LineNo] := LineDiscount;
                    Stub2PostingDesc[Stub2LineNo] := PostingDesc;
                    **OnAfterGetRecordOfPrintSettledLoop(GenJnlLine2, TotalLineAmount, CurrentLineAmount, TotalLineDiscount, LineDiscount, BalancingType, ApplyMethod) //Publisher**
                end;

                trigger OnPreDataItem()
                begin
                    PrintCheckHelper.PrintSettledLoopHelper(CustLedgEntry, VendLedgEntry, GenJnlLine, BalancingType.AsInteger(), BalancingNo,
                      FoundLast, TestPrint, FirstPage, FoundNegative, ApplyMethod);
                    if PreprintedStub then
                        TotalText := ''
                    else begin
                        TotalText := Text019Txt;
                        Stub2DocNoHeader := USText011Txt;
                        Stub2DocDateHeader := USText012Txt;
                        Stub2AmountHeader := USText013Txt;
                        Stub2DiscountHeader := USText014Txt;
                        Stub2NetAmountHeader := USText015Txt;
                        Stub2PostingDescHeader := USText017Txt;
                    end;

**Below are the Event Details**
`    [IntegrationEvent(false, false)] local procedure OnAfterGetRecordOfPrintSettledLoop(GenJnlLine2: Record "Gen. Journal Line"; var TotalLineAmount: Decimal; var CurrentLineAmount: Decimal; var TotalLineDiscount: Decimal; var LineDiscount: Decimal; BalancingType: Enum "Gen. Journal Account Type"; ApplyMethod: Option) begin end;`
    
    

### Additional context

Publisher request marked with //Publisher tag.
Internal work item: [AB#501889](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501889)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16506.
