### ISSUE TITLE
[Event Request] Reports 10401 "Check (Stub/Stub/Check)" - OnPreDataItemOfCheckPages && Report 10411 "Check (Stub/Check/Stub)" - OnPreDataItemOfCheckPages

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/ALAppExtensions#25976]
### Describe the request

Hi,

I would like to request the following event publisher in 
**Report 10401 "Check (Stub/Stub/Check)" - OnPreDataItemOfCheckPages** && 
**Report 10411 "Check (Stub/Check/Stub)" - OnPreDataItemOfCheckPages**

**trigger** - OnPredataItem of **CheckPages**
            trigger **OnPreDataItem**()
            begin
                FirstPage := true;
                FoundLast := false;
                TotalLineAmount := 0;
                TotalLineDiscount := 0;
                AddedRemainingAmount := true;
                OnPreDataItemOfCheckPages(GenJnlLine); _**//Publisher**_
            end;

**Below are event details**

    [IntegrationEvent(false, false)]
    local procedure OnPreDataItemOfCheckPages(GenJnlLine: Record "Gen. Journal Line")
    begin
    end;

### Additional context

_Publisher request_ marked with **//Publisher tag.**
Internal work item: [AB#501890](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501890)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16506.
