### ISSUE TITLE
[Event Request] Reports 10401 "Check (Stub/Stub/Check)" - OnAfterGetRecordOfPrintCheck && 10411 "Check (Stub/Check/Stub)" - OnAfterGetRecordOfPrintCheck

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/ALAppExtensions#25975]
### Describe the request

Hi,

I would like to request the following event publisher in 
 **Reports 10401 "Check (Stub/Stub/Check)" - OnAfterGetRecordOfPrintCheck** && 
**Report 10411 "Check (Stub/Check/Stub)" - OnAfterGetRecordOfPrintCheck**

OnAfterGetRecordOfPrintCheck- trigger **OnAfterGetRecord()** of **PrintCheck**

                    if NewLen <> StartingLen then
                        CheckAmountText :=
                          CopyStr(CheckAmountText, StartingLen + 1) +
                          CopyStr(CheckAmountText, 1, StartingLen);
                    PrnChkCheckAmountText[CheckStyle] :=
                      DollarSignBefore + CheckAmountText + DollarSignAfter;

                    if CheckStyle = CheckStyle::CA then
                        CheckStyleIndex := 0
                    else
                        CheckStyleIndex := 1;
                    OnAfterGetRecordOfPrintCheck(GenJnlLine); **// Publisher**

**Below are event details**
[IntegrationEvent(false, false)]

    local procedure OnAfterGetRecordOfPrintCheck(GenJnlLine: Record "Gen. Journal Line")
    begin

    end;

### Additional context

**Publisher request** marked with **//Publisher tag.**
Internal work item: [AB#501888](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501888)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16506.
