### ISSUE TITLE
[Request for External] - Codeunit Create Pick - Function GetLocation

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#25986]
### Describe the request

Could this function be made global?

```
 local procedure GetLocation(LocationCode: Code[10])
    begin
        if LocationCode = '' then
            CurrLocation := WhseSetupLocation
        else
            if CurrLocation.Code <> LocationCode then
                CurrLocation.Get(LocationCode);

        OnAfterGetLocation(LocationCode);
    end;

```

### Additional context

I need to call this function
Internal work item: [AB#501984](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501984)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18704.
