### ISSUE TITLE
[Event Reuest] - Codeunit Create Pick - Function UpdateFromQtyToPick

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#25983]
### Describe the request

Could ToQtyToPick and ToQtyToPickBase be made as reference?

```
 //AZ21883+
    //procedure UpdateFromQtyToPick(QtyAvailableBase: Decimal; FromQtyPerUOM: Decimal; var FromQtyToPick: Decimal; var FromQtyToPickBase: Decimal; ToQtyPerUOM: Decimal; ToQtyToPick: Decimal; ToQtyToPickBase: Decimal)
    procedure UpdateFromQtyToPick(QtyAvailableBase: Decimal; FromQtyPerUOM: Decimal; var FromQtyToPick: Decimal; var FromQtyToPickBase: Decimal; ToQtyPerUOM: Decimal; var ToQtyToPick: Decimal; var ToQtyToPickBase: Decimal)
    var
        IsHandled: Boolean;
    //AZ21883-
    begin
        case FromQtyPerUOM of
            ToQtyPerUOM:
                begin
                    FromQtyToPick := ToQtyToPick;
                    FromQtyToPickBase := ToQtyToPickBase;
                end;
            0 .. ToQtyPerUOM:
                begin
                    FromQtyToPick := Round(ToQtyToPickBase / FromQtyPerUOM, UnitOfMeasureManagement.QtyRndPrecision());
                    FromQtyToPickBase := ToQtyToPickBase;
                end;
            else
                //AZ218883+
                IsHandled := false;
                OnUpdateFromQtyToPickOnBeforeCalcFromQtyToPickBase(FromQtyToPick, FromQtyToPickBase, ToQtyToPick, ToQtyToPickBase, FromQtyPerUOM, IsHandled);
                if IsHandled then
                    exit;
                //AZ218883-
                FromQtyToPick := Round(ToQtyToPickBase / FromQtyPerUOM, 1, '>');
                FromQtyToPickBase := FromQtyToPick * FromQtyPerUOM;
                if FromQtyToPickBase > QtyAvailableBase then begin
                    FromQtyToPickBase := ToQtyToPickBase;
                    FromQtyToPick := Round(FromQtyToPickBase / FromQtyPerUOM, UnitOfMeasureManagement.QtyRndPrecision());
                end;
        end;
    end;
```

```
   [IntegrationEvent(true, false)]
    local procedure OnUpdateFromQtyToPickOnBeforeCalcFromQtyToPickBase(var FromQtyToPick: Decimal; var FromQtyToPickBase: Decimal; var ToQtyToPick: Decimal; var ToQtyToPickBase: Decimal; FromQtyPerUOM: Decimal; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

I need this to change ToQtyToPick
Internal work item: [AB#501962](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501962)

**Comment by AleksandricMarko** [comment]
Hello @DanielHaglo 
Instead adding "pass by reference" for ToQtyToPick and ToQtyToPickBase
Please think about adding publisher in UpdateToQtyToPick or just after calling it

**Comment by alexei-dobriansky** [comment]
Introduced a new event in the beginning of UpdateQuantitiesToPick function.

`   
procedure UpdateQuantitiesToPick(QtyAvailableBase: Decimal; FromQtyPerUOM: Decimal; var FromQtyToPick: Decimal; var FromQtyToPickBase: Decimal; ToQtyPerUOM: Decimal; var ToQtyToPick: Decimal; var ToQtyToPickBase: Decimal; var TotalQtyToPick: Decimal; var TotalQtyToPickBase: Decimal)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateQuantitiesToPick(QtyAvailableBase, FromQtyPerUOM, FromQtyToPick, FromQtyToPickBase, ToQtyPerUOM, ToQtyToPick, ToQtyToPickBase, TotalQtyToPick, TotalQtyToPickBase, IsHandled);
        if IsHandled then
            exit;

        UpdateToQtyToPick(QtyAvailableBase, ToQtyPerUOM, ToQtyToPick, ToQtyToPickBase, TotalQtyToPick, TotalQtyToPickBase);
        UpdateFromQtyToPick(QtyAvailableBase, FromQtyPerUOM, FromQtyToPick, FromQtyToPickBase, ToQtyPerUOM, ToQtyToPick, ToQtyToPickBase);
        UpdateTotalQtyToPick(ToQtyToPick, ToQtyToPickBase, TotalQtyToPick, TotalQtyToPickBase);
    end;
`

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18608.
