### ISSUE TITLE
codeunit 1336 "Item Templ. Mgt." publisher OnBeforeSelectItemTemplate ItemTempl parameter should be passed as VAR

### ISSUE THREAD

**Issue by nikolajovicic** [microsoft/ALAppExtensions#25984]
### Describe the issue

In codeunit 1336 "Item Templ. Mgt." there is publisher OnBeforeSelectItemTemplate but first parameter ItemTemplate is not passed as var, so we are not able to do anything to change way of selecting item templates. For example to add some filters to filter only specific Item Templates but not all.

Current code:
`[IntegrationEvent(false, false)]
    local procedure OnBeforeSelectItemTemplate(ItemTempl: Record "Item Templ."; var IsHandled: Boolean; var Result: Boolean)
    begin
    end;`

This code is in current Base App version: 23.4.15643.16092

### Expected behavior

Code should be:

``[IntegrationEvent(false, false)]
    local procedure OnBeforeSelectItemTemplate(var ItemTempl: Record "Item Templ."; var IsHandled: Boolean; var Result: Boolean)
    begin
    end;``

### Steps to reproduce

Open base app source code, navigate to codeunit 1336 and search for subscriber OnBeforeSelectItemTemplate.

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Unfortunately, this repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

For suggestions to the Business Central product group, please create a [BC Idea](https://aka.ms/bcideas).

If you want to log a support case, please visit:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
