### ISSUE TITLE
[Event Request] CU 395 "FinChrgMemo-Issue" change OnRunOnBeforeGLAccountGenJnlLineInsert

### ISSUE THREAD

**Issue by sgiordy** [microsoft/ALAppExtensions#25989]
### Describe the request

The current event is missing the originating Finance Charge Memo Line:

`local procedure OnRunOnBeforeGLAccountGenJnlLineInsert(var GenJournalLine: Record "Gen. Journal Line")`

It should be refactored with a new parameter:

`local procedure OnRunOnBeforeGLAccountGenJnlLineInsert(var GenJournalLine: Record "Gen. Journal Line"; FinChrgMemoLine: Record "Finance Charge Memo Line")`

### Additional context

Without the originating line the event is unuseful because you don't know how to handle the generic General Journal Line.
Internal work item: [AB#501994](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/501994)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16627.
