### ISSUE TITLE
[Bug]: Exporting Intrastat report in fr-BE language gives error

### ISSUE THREAD

**Issue by bartpattijn** [microsoft/ALAppExtensions#25987]
### Describe the issue

when exporting the intrastat report in the fr-BE language we get an error
"La légende Code pays/région origine est ambiguë entre plusieurs champs de la table Ligne de l’état de déclaration d’échanges de biens."

### Expected behavior

should not error

### Steps to reproduce

export an intrastat report in the fr-BE language

### Additional context

there are 2 fields that have the same translation. 
thereby system errors on setview
the field Country/Region of Payment Code has the wrong translation
in addition it would be better to do a getview(false) in codeunit 4810 IntrastatReportManagement line 631
then the view would use fieldnumbers and would not error on duplicate field names

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
That sounds like a product defect! Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps). We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
