### ISSUE TITLE
[Protected Request] Mark SetEditable in page 7011 Purchase Price List Lines as protected

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#25998]
### Describe the request

Please mark ``SetEditable`` in ``page 7011 "Purchase Price List Lines"`` as ``protected``.

```diff
-   local procedure SetEditable()
+   protected procedure SetEditable() 
    begin
        AmountTypeIsEditable := Rec."Asset Type" <> Rec."Asset Type"::"Item Discount Group";
        AmountEditable := Rec.IsAmountSupported();
        UOMEditable := Rec.IsUOMSupported();
        ItemAsset := Rec.IsAssetItem();
        ResourceAsset := Rec.IsAssetResource();
        GLAccountAsset := Rec."Asset Type" = Rec."Asset Type"::"G/L Account";
        UnitCostEditable := AmountEditable and (ResourceAsset or GLAccountAsset);
    end;
```

### Additional context

We have to call this in a pageextension to enable inserting via excel/webservice.
Internal work item: [AB#502142](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502142)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17192.
