### ISSUE TITLE
[Request for External] - Record Bin Content - Function CalcTotalQtyBase

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#25992]
### Describe the request

Could this be made global?

```
local procedure CalcTotalQtyBase(): Decimal
    var
        WarehouseEntry: Record "Warehouse Entry";
    begin
        WarehouseEntry.SetRange("Location Code", "Location Code");
        WarehouseEntry.SetRange("Bin Code", "Bin Code");
        WarehouseEntry.SetRange("Item No.", "Item No.");
        WarehouseEntry.SetRange("Variant Code", "Variant Code");
        WarehouseEntry.SetTrackingFilterFromBinContent(Rec);
        OnCalcTotalQtyBaseOnAfterSetFilters(WarehouseEntry, Rec);
        WarehouseEntry.CalcSums("Qty. (Base)");
        exit(WarehouseEntry."Qty. (Base)");
    end;
```

### Additional context

I need to call this function
Internal work item: [AB#502094](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502094)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18704.
