### ISSUE TITLE
[Request for External] - Codeunit Get Source Doc. Outbound

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#25993]
### Describe the request

Could this function be made global?

```
local procedure FindWarehouseRequestForSalesOrder(var WhseRqst: Record "Warehouse Request"; SalesHeader: Record "Sales Header")
    begin
        with SalesHeader do begin
            TestField(Status, Status::Released);
            CheckWhseShipmentConflict(SalesHeader);
            CheckSalesHeader(SalesHeader, true);
            WhseRqst.SetRange(Type, WhseRqst.Type::Outbound);
            WhseRqst.SetSourceFilter(Database::"Sales Line", "Document Type".AsInteger(), "No.");
            WhseRqst.SetRange("Document Status", WhseRqst."Document Status"::Released);
            OnFindWarehouseRequestForSalesOrderOnAfterWhseRqstSetFilters(WhseRqst, SalesHeader);
            GetRequireShipRqst(WhseRqst);
        end;

        OnAfterFindWarehouseRequestForSalesOrder(WhseRqst, SalesHeader);
    end;
```

### Additional context

I need to call this function
Internal work item: [AB#502095](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502095)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18615.
