### ISSUE TITLE
codeunit 5700 "User Setup Management" extra parameter "Document Type" to GetLocation and change IntegrationEvent

### ISSUE THREAD

**Issue by renevanbeekum** [microsoft/ALAppExtensions#25997]
### Describe the request

Proposed new changes, so no breaking change.:

procedure GetLocation(DocType: Option Sales,Purchase,Service; AccLocation: Code[10]; RespCenterCode: Code[10]) LocationCode: Code[10]
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeGetLocation(DocType, AccLocation, RespCenterCode, LocationCode, IsHandled);
    if IsHandled then
        exit(LocationCode);

    exit(GetLocation(DocType, AccLocation, RespCenterCode, -1));
end;

procedure GetLocation(DocType: Option Sales,Purchase,Service; AccLocation: Code[10]; RespCenterCode: Code[10]; DocumentType: Integer) LocationCode: Code[10] //New
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeGetLocationDocumentType(DocType, DocumentType, AccLocation, RespCenterCode, LocationCode, IsHandled); //New
    if IsHandled then
        exit(LocationCode);

    case DocType of
        DocType::Sales:
            UserRespCenter := GetSalesFilter();
        DocType::Purchase:
            UserRespCenter := GetPurchasesFilter();
        DocType::Service:
            UserRespCenter := GetServiceFilter();
    end;
    if UserRespCenter <> '' then
        RespCenterCode := UserRespCenter;
    if RespCenter.Get(RespCenterCode) then
        if RespCenter."Location Code" <> '' then
            UserLocation := RespCenter."Location Code";
    if AccLocation <> '' then
        exit(AccLocation);

    exit(UserLocation);
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeGetLocation(DocType: Option Sales,Purchase,Service; AccLocation: Code[10]; RespCenterCode: Code[10]; var LocationCode: Code[10]; var IsHandled: Boolean)
begin
end;

 //New Begin
[IntegrationEvent(false, false)]
local procedure OnBeforeGetLocationDocumentType(DocType: Option; Sales,Purchase,Service; DocumentType: Integer; AccLocation: Code[10]; RespCenterCode: Code[10]; var LocationCode: Code[10]; var IsHandled: Boolean)
begin
end;
 //New End

Off cause te changes wher this routine is used, belowe a example for the Sales Header. Do this change also in Purchase and Service

procedure UpdateLocationCode(LocationCode: Code[10])
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeUpdateLocationCode(Rec, LocationCode, IsHandled);
    if not IsHandled then
        //Validate("Location Code", UserSetupMgt.GetLocation(0, LocationCode, "Responsibility Center")); //Old
        Validate("Location Code", UserSetupMgt.GetLocation(0, LocationCode, "Responsibility Center", "Document Type".AsInteger())); //New
end;

### Additional context

To get different default locations for order and return order.
Internal work item: [AB#502133](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502133)

**Comment by haoranpb** [comment]
Hi @renevanbeekum 

Thanks for opening an event request.

After reviewing the proposed event and provided context, I understand you'd like to customize the `Localiztion Code` basing on the `Document Type` of Sales/Purchase/Service.

I can see there is already an event `OnBeforeUpdateLocationCode` inside the `procedure UpdateLocationCode` for all 3 scenarios. Could that be helpful in your use case? 

You will have access to everything in `Rec`, and write you logic (potentially re-use some standard procedures from `User Setup Management` codeunit.

I will close this issue for now, if you have follow-up questions or requests, we do not monitor closed issues, so please create a new issue where you reference this one.
