### ISSUE TITLE
[Bug]: "Source Currency Amount" is not populated in PostAutoAcc

### ISSUE THREAD

**Issue by mstjernfelt** [microsoft/ALAppExtensions#25995]
### Describe the issue

When posting Gen Journals in foreign currency and with a Automatic Account Group specified the field Source Currency Amount is omitted and not populated. The total currency amount should be saved in this field on the last Automatic Account Line during posting.

### Expected behavior

The last posted "Automatic Account Line" field "Source Currency Amount" should be populated with total in the last. Same as the field LCY amount field is.

### Steps to reproduce

Post a general journal with a currency and Automatic Account Group specified. The field "Source Currency Amount" is not populated on the last total G/L Entry.

### I will provide a fix for a bug

- [x] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
That sounds like a product defect! Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps). We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by mstjernfelt** [comment]
@JesperSchulz This bug request is for the W1 AutomaticAccountCodes app, perhaps this is the correct repo after all? :)

Apps/W1/AutomaticAccountCodes

**Comment by JesperSchulz** [comment]
I'm so sorry! It _is_! Easy to get confused with all the different repositories we've got 😉 Need to do something about that...

In that case, let me re-open this issue and approve it instead 🚀

**Comment by mstjernfelt** [comment]
Awesome :) how do I create a pull request connected to this issue?

**Comment by JesperSchulz** [comment]
You simply create a PR here on GitHub. In the description of the PR you write "Fixes #25995", and it will link the PR to this issue.
