### ISSUE TITLE
[EVENT REQUEST] Codeunit 1005 Job Calculate Batches - OnBeforeChangeCurrencyDateOnBeforeDateChanged

### ISSUE THREAD

**Issue by Imbapriest** [microsoft/ALAppExtensions#26003]
### Describe the request

We need the possiblity to change the currency date from partly invoiced planning lines

Suggested Integration Event:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeChangeCurrencyDateOnBeforeDateChanged(var JobPlanningLine: Record "Job Planning Line"; var IsHandled: Boolean)
    begin
    end;
```

Suggested Code solution:

```
 procedure ChangeCurrencyDates(JT: Record "Job Task"; scheduleLine: Boolean; ContractLine: Boolean; PeriodLength: DateFormula; FixedDate: Date; StartingDate: Date; EndingDate: Date)
    var

...

                JobPlanningLine.CalcFields("Qty. Transferred to Invoice");
+              IsHandled := false;
+              OnBeforeChangeCurrencyDateOnBeforeDateChanged(JobPlanningLine, IsHandeld)
+              if (JobPlanningLine."Qty. Transferred to Invoice" = 0) or (IsHandled) then begin
-               if JobPlanningLine."Qty. Transferred to Invoice" = 0 then begin
                    JobPlanningLine.TestField("Planning Date");
```

### Additional context

A customer is calculating the WIP based on changing local currency.  So a part of their projects that invoiced in foreign Currency are set in the option to change the local currency if the currency date is changed.

If there is a partly invoiced job planning line where the "to be invoiced" rest is higher than 0 the Line will not changed to the current currency exchange rate. That's also in case that 1% of this job planning line was invoiced. 
That is based on design because the currency date is calculated for the Line. 

An exception is if a secound Invoice is placed to this partly invoiced job planning Line.
In this case the currency date is changed to the new date, what in contrast is to the function of the Codeunit that are only changing this date if the "Invoced Amount" is 0.

For our customer its may helpfull to have a chance to configure via app that these partially invoiced lines will be changed to the current currency date.
It's clear that fully invoiced lines has not to be changed.

The current business Solution is to have a copy of the Report "Change Job Dates". But thats not a good Solution in case there are changes in a future releases. Because these have no effect.

Internal work item: [AB#502256](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502256)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16679.

**Comment by Imbapriest** [comment]
Thank you very much :)
