### ISSUE TITLE
table 81 "Gen. Journal Line"

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#26005]
### Describe the request

Could You please, add the following event to the table 81 "Gen. Journal Line"

Object: table 81 "Gen. Journal Line"
procedure ShowDimensions() IsChanged: Boolean

Microsoft_Base Application_23.4.15643.16092.app

Publisher Event: OnShowDimensionsOnAfterEditDimensionSet(Rec, OldDimSetID);

Reason: To implement custom business logic and permit manage additional dimension fields
Where is the event placed (see image attached)?:
![image](https://github.com/microsoft/ALAppExtensions/assets/73465025/a125eb74-1178-4794-9928-b6fc8bc3f6b8)

Just after the line 4613:             "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");
Insert the next line:
OnShowDimensionsOnAfterEditDimensionSet(Rec, OldDimSetID);

![image](https://github.com/microsoft/ALAppExtensions/assets/73465025/01bc7631-9862-465d-912b-85d8f78adc0e)

Event code:
    [IntegrationEvent(false, false)]
    local procedure OnShowDimensionsOnAfterEditDimensionSet(var GenJournalLine: Record "Gen. Journal Line"; OldDimensionSetId: Integer)
    begin
    end;

Thanks in advance

### Additional context

Our Customer needs to manage additional dimension fields in the table 81.
Internal work item: [AB#502471](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502471)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16827.
