### ISSUE TITLE
[Bug]: Failing Page 31169 "Report Selection Cash Desk CZP"

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#26007]
### Describe the issue

Page 31169 "Report Selection Cash Desk CZP" content field
```
                field("Report ID"; Rec."Report ID")
                {
                    ApplicationArea = Basic, Suite;
                    LookupPageID = Objects;
                    ToolTip = 'Specifies the ID of the report that the program will print.';
                }
```
This field i defined in table 11748 "Cash Desk Rep. Selections CZP"

```
        field(3; "Report ID"; Integer)
        {
            Caption = 'Report ID';
            TableRelation = AllObj."Object ID" where("Object Type" = const(Report));
            DataClassification = CustomerContent;
 
            trigger OnValidate()
            begin
                CalcFields("Report Caption");
            end;
        }
```

Problem is that defined LookupPageID on page use Page where is source table AllObjectsWithCaption, but table relation use AllObj table. It rasie unhandled error. 

### Expected behavior

It should work without error.

### Steps to reproduce

1.  Go to page Report Selection Cash Desk  in web client
2. Click to lookup in Report ID
3. It sows you small dropdown table (it works)
4. If you use Choose from full list it opens lookup page
5. Choose some record and confirm
6. Raise error with unhandled error.

### I will provide a fix for a bug

- [x] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
That might just be a product defect! Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps). We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview

**Comment by fridrichovsky** [comment]
Hello @JesperSchulz,
problem is not in platform, but in app. This table Apps/CZ/CashDeskLocalization/app/Src/Tables/CashDeskRepSelectionsCZP.Table.al use TableRelation with different table than LookupPageID in Apps/CZ/CashDeskLocalization/app/Src/Pages/ReportSelectionCashDeskCZP.Page.al. 

You can only change in Apps/CZ/CashDeskLocalization/app/Src/Tables/CashDeskRepSelectionsCZP.Table.al

`"TableRelation = AllObj."Object ID" where("Object Type" = const(Report));"`

to

`TableRelation = AllObjWithCaption."Object ID" where("Object Type" = const(Report));`

and it will work.

**Comment by JesperSchulz** [comment]
Sorry, I thought this was a BaseApp problem! My bad 😊 In that case, I'm of course reopening this issue and am allowing you to create a PR which introduces the change. I just did a quick search in the code base and found another place where AllObj was used as table relation. It's in table CompensReportSelectionsCZC.Table.al. Should that get changed as well, while at it?

Anyway, I'm of course approving this issue and am expecting a pull request 🙌🏻
