### ISSUE TITLE
[Allow Multiple Posting Groups Bug] codeunit 12 PostDtldVendLedgEntries

### ISSUE THREAD

**Issue by GFlores11** [microsoft/ALAppExtensions#26006]
### Describe the request

I believe there is an issue related to the Multiple posting groups functionality with vendors; When applying documents from the payment journal, the balance accounting entries are not generated between the different accounts of the different posting groups (different posting group in invoice and payment).

We believe that a call to the procedure "PostDtldVendLedgEntry" is missing in the procedure "PostDtldVendLedgEntries" in Codeunit 12:

![image](https://github.com/microsoft/ALAppExtensions/assets/93582039/4b39e6aa-9ae4-4a48-b713-a6d7995e4746)

We also believe that the MultiplePostingGroups check should be moved before the Bill control in same procedure (to avoid the check with the filtered record):

![image](https://github.com/microsoft/ALAppExtensions/assets/93582039/634e2adc-11b1-4596-8cef-af3295d21918)

### Additional context

Posting a vendor payment in payment journal, applying against an invoice, when the vendor posting group is different in the invoice and in the journal line, when posting it does not generate the additional G/L Entries of the Multiple Posting Group functionality.

**Comment by JesperSchulz** [comment]
That might just be a product defect! Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps). We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
