### ISSUE TITLE
[Request for External] report 840 "Suggest Worksheet Lines" - procedure InsertCFLineForTax

### ISSUE THREAD

**Issue by Sameer-Utekar** [microsoft/ALAppExtensions#26009]
### Describe the request

Hello Colleagues,

Could you kindly remove the "local" prefix from the procedure InsertCFLineForTax in report 840 "Suggest Worksheet Lines"
Old Signature
`local procedure InsertCFLineForTax(SourceTableNum: Integer)`

New Signature
`procedure InsertCFLineForTax(SourceTableNum: Integer)`

Thanks in advance,
Sameer

### Additional context

We're looking to divide the data item "VAT Entry" into two separate items: "VAT Entry Sales" and "VAT Entry Purchase." We intend to utilize this procedure there.
Internal work item: [AB#502629](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502629)

**Comment by dcenic** [comment]
This is checked in and available in Business Central 24.1

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 18627.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18626.
