### ISSUE TITLE
[Event Change Request] table 77 "Report Selections" - OnSendEmailDirectlyOnBeforeEmailWithAttachment

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#26004]
### Describe the request

Add new parameters:
DocNo: Code[20]
DocName: Text[150]
EmailAddress: Text[250]

    [IntegrationEvent(false, false)]
    local procedure OnSendEmailDirectlyOnBeforeEmailWithAttachment(RecordVariant: Variant; ReportSelection: Record "Report Selections"; var TempBlob: Codeunit "Temp Blob"; var DocumentMailing: Codeunit "Document-Mailing"; DocNo: Code[20]; DocName: Text[150]; EmailAddress: Text[250])
    begin
    end;

### Additional context

Customer wants to log all email activities
Internal work item: [AB#502404](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502404)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16827.
