### ISSUE TITLE
[Event Request] Codeunit 7304 OnAfterCreateItemJnlLine

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#2600]
we Need a new Event OnAfterCreateItemJnlLine in codeunit 7304 in Procedure CreateItemJnlLine:

LOCAL CreateItemJnlLine(WhseJnlLine2 : Record "Warehouse Journal Line";VAR ItemJnlLine : Record "Item Journal Line") : Boolean
...
    IF QtyToHandleBase <> 0 THEN BEGIN
      ItemJnlLine."Document No." := "Whse. Document No.";
      ItemJnlLine.VALIDATE("Posting Date","Registering Date");
      ItemJnlLine.VALIDATE("Item No.","Item No.");
      ItemJnlLine.VALIDATE("Variant Code","Variant Code");
      ItemJnlLine.VALIDATE("Location Code","Location Code");
      ItemJnlLine.VALIDATE("Unit of Measure Code","Unit of Measure Code");
      ItemJnlLine.VALIDATE(Quantity,ROUND(QtyToHandleBase / "Qty. per Unit of Measure",0.00001));
      ItemJnlLine.Description := Description;
      ItemJnlLine."Source Type" := ItemJnlLine."Source Type"::Item;
      ItemJnlLine."Source No." := "Item No.";
      ItemJnlLine."Source Code" := "Source Code";
      ItemJnlLine."Reason Code" := "Reason Code";
      ItemJnlLine."Warehouse Adjustment" := TRUE;
      ItemJnlLine."Line No." := "Line No.";
    END;
  END;
  //+++++++++++++++++++++++++++++++++++
  OnAfterCreateItemJnlLine(VAR ItemJnlLine;WhseJnlLine2);
  //-----------------------------------
END;

EXIT(QtyToHandleBase <> 0);

**Comment by AlexanderYakunin** [comment]
We already have same event OnAfterCreateItemJnlLine(ItemJnlLine,WhseItemTrkgLine) after ItemJnlLine."Line No." := "Line No.";

Do you really need new event before EXIT or I can simply add WhseJnlLine2 as parameter?

**Comment by GuntherGebauer** [comment]
I think it should fit if WhseJnlLine2 is added as additional parameter
