### ISSUE TITLE
[Event Request] report 840 "Suggest Worksheet Lines" - Create new event OnInsertCFLineForFixedAssetsDisposalOnBeforeInsertTempCFWorksheetLine

### ISSUE THREAD

**Issue by Sameer-Utekar** [microsoft/ALAppExtensions#26018]
### Describe the request

Could we please have a new event OnInsertCFLineForFixedAssetsDisposalOnBeforeInsertTempCFWorksheetLine
in the function, InsertCFLineForFixedAssetsDisposal from report 840 "Suggest Worksheet Lines"

this is similar to an existing event named "OnInsertCFLineForCustLedgerEntryOnBeforeInsertTempCFWorksheetLine" in the procedure InsertCFLineForCustLedgerEntry

Code:

```
local procedure InsertCFLineForFixedAssetsDisposal()
    begin
        with CFWorksheetLine2 do begin
            Init();
            "Source Type" := "Source Type"::"Fixed Assets Disposal";
            "Source No." := SaleFixedAsset."No.";
            "Document No." := SaleFixedAsset."No.";
            "Cash Flow Account No." := CFSetup."FA Disposal CF Account No.";
            Description :=
              CopyStr(
                StrSubstNo(
                  Text027, SaleFixedAsset."No.", Format(FADeprBook."Projected Proceeds on Disposal")),
                1, MaxStrLen(Description));
            SetCashFlowDate(CFWorksheetLine2, FADeprBook."Projected Disposal Date");
            "Amount (LCY)" := FADeprBook."Projected Proceeds on Disposal";
            "Shortcut Dimension 2 Code" := SaleFixedAsset."Global Dimension 2 Code";
            "Shortcut Dimension 1 Code" := SaleFixedAsset."Global Dimension 1 Code";
            MoveDefualtDimToJnlLineDim(DATABASE::"Fixed Asset", SaleFixedAsset."No.", "Dimension Set ID");
			
	//>>>>
            OnInsertCFLineForFixedAssetsDisposalOnBeforeInsertTempCFWorksheetLine(CFWorksheetLine2, "Cash Flow Forecast", SaleFixedAsset); 
	//<<<<
			
            InsertTempCFWorksheetLine(CFWorksheetLine2, 0);
        end;
    end;
```

			
			

Event signature:

```
[IntegrationEvent(false, false)]
    local procedure OnInsertCFLineForFixedAssetsDisposalOnBeforeInsertTempCFWorksheetLine(var CFWorksheetLine: Record "Cash Flow Worksheet Line"; "Cash Flow Forecast": Record "Cash Flow Forecast"; SaleFixedAsset: Record "Fixed Asset")
    begin
    end;
```

Thanks in advance,
Sameer

### Additional context

We require updating some fields in CFWorksheetLine before performing the insertion.
Internal work item: [AB#502636](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502636)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16827.
