### ISSUE TITLE
[Request for External] report 840 "Suggest Worksheet Lines" - procedure SetCashFlowDate

### ISSUE THREAD

**Issue by Sameer-Utekar** [microsoft/ALAppExtensions#26013]
### Describe the request

Hello Colleagues,

Can you please remove the local prefix from procedure SetCashFlowDate in report 840 "Suggest Worksheet Lines"

Old signature

 `local procedure SetCashFlowDate(var CashFlowWorksheetLine: Record "Cash Flow Worksheet Line"; CashFlowDate: Date)`

New Signature

` procedure SetCashFlowDate(var CashFlowWorksheetLine: Record "Cash Flow Worksheet Line"; CashFlowDate: Date)`

Thanks in advance,
Sameer

### Additional context

We've introduced a new data item in the extension where we need to utilize this procedure.
Internal work item: [AB#502640](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502640)

**Comment by dcenic** [comment]
This is checked in and available in Business Central 24.1

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18626.
