### ISSUE TITLE
[Global Procedure Request] table 5406 "Prod. Order Line" - GetUpdateFromSKU

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#26011]
### Describe the request

Could you set the local procedure GetUpdateFromSKU() to global in table 5406 "Prod. Order Line".

Current Code:
local procedure GetUpdateFromSKU()

Updated Code:
procedure GetUpdateFromSKU()

### Additional context

We do not only have a "Production BOM No." and "Production BOM No." on Item and Stockkeeping Unit but also Technical variants within one Location because not all Machine and Work Centers perform precisely the same. We need to be able to change the "Production BOM No." and "Routing No." on technical variant setup but also be able to undo such setup and apply the base procedure GetUpdateFromSKU() in certain cases.

                if "Technical Variant PTE" <> xRec."Technical Variant PTE" then
                    if "Technical Variant PTE" <> '' then begin
                        TechnicalVariant.Get("Item No.", "Technical Variant PTE");
                        TechnicalVariant.TestField(Status, TechnicalVariant.Status::Certified);
                        Validate("Routing No.", TechnicalVariant."Routing No.");
                        Validate("Production BOM No.", TechnicalVariant."Production BOM No.");
                    end else
                        GetUpdateFromSKU();

Internal work item: [AB#502628](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502628)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18615.
