### ISSUE TITLE
Make Varables protected - report 99001020 "Carry Out Action Msg. - Plan."

### ISSUE THREAD

**Issue by SarkeSrb** [microsoft/ALAppExtensions#26024]
### Describe the request

protected var
  NoPlanningResiliency: Boolean;
  CurrReqWkshTemp: Code[10];
  CurrReqWkshName: Code[10];

### Additional context

We need these variables to be protected: 
The values of these variables are set depending on our additional fields in the report extension.
Internal work item: [AB#502864](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502864)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17192.
