### ISSUE TITLE
[Event Request] OnBeforeSetFiltersBlankTypeItemRef @ codeunit 5720 "Item Reference Management"

### ISSUE THREAD

**Issue by J-KVS** [microsoft/ALAppExtensions#26027]
### Describe the request

I'd like to propose the following event:

``` al
    local procedure SetFiltersBlankTypeItemRef(var ItemReference: Record "Item Reference")
        // START
    var
        IsHandled: Boolean;
        // STOP
    begin
        // START
        OnBeforeSetFiltersBlankTypeItemRef(ItemReference, IsHandled);
        if IsHandled then
            exit;

        // STOP
        ItemReference.SetFilter("Reference Type", '%1|%2', ItemReference."Reference Type"::" ", ItemReference."Reference Type"::"Bar Code");
        ItemReference.SetRange("Reference Type No.");
    end;

    // START
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetFiltersBlankTypeItemRef(var ItemReference: Record "Item Reference"; var IsHandled: Boolean)
    begin
    end;
    // STOP
```

### Additional context

We wan't to extend the enum `"Item Reference Type"` with a similiar behavior as the type `Barcode`.
Internal work item: [AB#502920](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/502920)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16993.
