### ISSUE TITLE
[Request for External] Make variables protected var in report 25 "Account Schedule"

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#26034]
### Describe the request

Hi

Can you please move these variables from "var" to "protected var" in report 25 "Account Schedule".

AccSchedName: Code[10];
FinancialReportName: Code[10];
ColumnLayoutName: Code[10];

Alternatively, add an OnBeforeOnPreReport-event to the same report with these 3 variables?

```
trigger OnPreReport()
var
    FinancialReportMgt: Codeunit "Financial Report Mgt.";
begin
    // >>>>>>>>>>
    OnBeforeOnPreReport(AccSchedName, FinancialReportName, ColumnLayoutName);
    // <<<<<<<<<<
    FinancialReportMgt.Initialize();
    TransferValues();
    UpdateFilters();
    InitAccSched();
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeOnPreReport(var AccSchedName: Code[10]; var FinancialReportName: Code[10]; var ColumnLayoutName: Code[10])
begin
end;
```

### Additional context

We're currently working with a customer to implement a permission based access for financial reports, and need it to verify wheter the logged on user has enough permissions to run the report.
Internal work item: [AB#503051](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/503051)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17192.
