### ISSUE TITLE
table 39 "Purchase Line" - make local procedure InitHeaderDefaults() global

### ISSUE THREAD

**Issue by deerware** [microsoft/ALAppExtensions#26037]
### Describe the request

Hi,
Is it possible to change the now local procedure `InitHeaderDefaults` in `table 39 Purchase Line` into a global one?
The procedure is already global on `Sales Line`, so I hope it won't be an issue.

There is the extra `TempPurchLine` parameter, which is not used anywhere inside the function apart from the publisher, which is also not called from any Microsoft app (as far as I could find), so maybe a public overload without it would be favorable, but I'll leave that up to you.
We just need to reinit the defaults.

Thank you!

### Additional context

```diff
@@ -4366,7 +4366,7 @@ table 39 "Purchase Line"
     local procedure InitItemAppl()
     begin
         "Appl.-to Item Entry" := 0;
     end;
 
-    local procedure InitHeaderDefaults(PurchHeader: Record "Purchase Header"; var TempPurchLine: Record "Purchase Line" temporary)
+    procedure InitHeaderDefaults(PurchHeader: Record "Purchase Header"; var TempPurchLine: Record "Purchase Line" temporary)
     var
         IsHandled: Boolean;
     begin
         CheckBuyFromVendorNo(PurchHeader);
 
         "Buy-from Vendor No." := PurchHeader."Buy-from Vendor No.";
```
Internal work item: [AB#503095](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/503095)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17192.
