### ISSUE TITLE
[Event Request] Add OnBeforeDeleteJnlLinesOnAfterSetFilters to procedure DeleteJnlLines in codeunit 5510 "Production Journal Mgt"

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#26039]
### Describe the request

Hi

Can you please add event OnBeforeDeleteJnlLinesOnAfterSetFilters to procedure DeleteJnlLines in codeunit 5510 "Production Journal Mgt"?

```
procedure DeleteJnlLines(TemplateName: Code[10]; BatchName: Code[10]; ProdOrderNo: Code[20]; ProdOrderLineNo: Integer)
var
    ItemJnlLine2: Record "Item Journal Line";
    ReservEntry: Record "Reservation Entry";
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeDeleteJnlLines(TemplateName, BatchName, ProdOrderNo, ProdOrderLineNo, IsHandled);
    if IsHandled then
        exit;
    ItemJnlLine2.Reset();
    ItemJnlLine2.SetRange("Journal Template Name", TemplateName);
    ItemJnlLine2.SetRange("Journal Batch Name", BatchName);
    ItemJnlLine2.SetRange("Order Type", ItemJnlLine2."Order Type"::Production);
    ItemJnlLine2.SetRange("Order No.", ProdOrderNo);
    if ProdOrderLineNo <> 0 then
        ItemJnlLine2.SetRange("Order Line No.", ProdOrderLineNo);
    // >>>>>>>>>>
    OnBeforeDeleteJnlLinesOnAfterSetFilters(ItemJnlLine2);
    // <<<<<<<<<<
    if ItemJnlLine2.Find('-') then begin
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeDeleteJnlLinesOnAfterSetFilters(var ItemJnlLine: Record "Item Journal Line")
begin
end;
```

### Additional context

We need to be able to use the delete jnl lines without having to specify a production order no.
Internal work item: [AB#503168](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/503168)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16993.
