### ISSUE TITLE
Page 1505 "Workflow Templates". Make variable and procedure Protected

### ISSUE THREAD

**Issue by LubomirUrx** [microsoft/ALAppExtensions#26036]
### Describe the request

Could you make variable IsLookupMode and procedure Initialize as Protected.
Thank you

### Additional context

We are going to use it in page extension based on page 1505.
Internal work item: [AB#503049](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/503049)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17192.
