### ISSUE TITLE
[Protected var] Report 1007 "Job - Transaction Detail"

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#26047]
### Describe the request

Please set variables from RequestPage as protected var. 
Mainly we need:
CurrencyFieldReq: Option "Local Currency","Foreign Currency"

### Additional context

We need decide in our subscriber that way code choose by this option.
Internal work item: [AB#504099](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504099)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17192.
