### ISSUE TITLE
[Event Request] Codeunit 229 "Document-Print" OnBeforePrintSalesOrderOnBeforeGetSalesOrderUsage

### ISSUE THREAD

**Issue by GMATest** [microsoft/ALAppExtensions#26048]
### Describe the request

Hello, would it be possible to add OnBeforePrintSalesOrderOnBeforeGetSalesOrderUsage event on PrintSalesOrder() procedure in codeunit 229 "Document-Print", like this:

```
    procedure PrintSalesOrder(SalesHeader: Record "Sales Header"; Usage: Option "Order Confirmation","Work Order","Pick Instruction")
    var
        ReportSelection: Record "Report Selections";
        ReportUsage: Enum "Report Selection Usage";
        IsPrinted: Boolean;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforePrintSalesOrderOnBeforeGetSalesOrderUsage(SalesHeader, Usage, IsHandled); // New event
        if IsHandled then
            exit;

        if SalesHeader."Document Type" <> SalesHeader."Document Type"::Order then
            exit;

        ReportUsage := GetSalesOrderUsage(Usage);

        SalesHeader.SetRecFilter();
        CalcSalesDisc(SalesHeader);
        OnBeforePrintSalesOrder(SalesHeader, ReportUsage.AsInteger(), IsPrinted);
        if IsPrinted then
            exit;

        ReportSelection.PrintWithDialogForCust(
            ReportUsage, SalesHeader, GuiAllowed, SalesHeader.FieldNo("Bill-to Customer No."));
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforePrintSalesOrderOnBeforeGetSalesOrderUsage(var SalesHeader: Record "Sales Header"; Usage: Option "Order Confirmation","Work Order","Pick Instruction"; var IsHandled: Boolean) // New event
    begin
    end;
```

### Additional context

We have cases where we need to exist PrintSalesOrder() procedure based on the Sales Header Document Type before the CalcSalesDisc() procedure. The event at the beginning of CalcSalesDisc() does not fit our needs because CalcSalesDisc() is also used in other code places where we need a standard flow of this procedure.
Internal work item: [AB#504112](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504112)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16993.
