### ISSUE TITLE
[Extensibility Request] Blanket Sales / Purchase Subform Pages

### ISSUE THREAD

**Issue by chrischbo** [microsoft/ALAppExtensions#26049]
### Describe the request

Hi,

due to the same issue as explained here (https://github.com/microsoft/ALAppExtensions/issues/20801), we would kindly request to add an CurrPage.Update() to the "Item Reference No." field on blanket sales order and blanket purchase order document subforms. We need this to have an existing record to run our code for the new price calculation.

Min. requested pages:

page 510 "Blanket Purchase Order Subform"
page 508 "Blanket Sales Order Subform"

### Additional context

Handle price calculation
Internal work item: [AB#504156](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504156)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18666.
