### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - OnBeforeOnInsert 

### ISSUE THREAD

**Issue by AnastasiiaBarvinok** [microsoft/ALAppExtensions#26043]
### Describe the request

Hi, would it be possible to modify the **OnBeforeOnInsert** event in **table 36** (Sales Header) by adding the **InsertMode** parameter, like this: 

```
    trigger OnInsert()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        // Modified Event begin
        // OnBeforeOnInsert(Rec, IsHandled);
        OnBeforeOnInsert(Rec, IsHandled, InsertMode);
        // Modified Event end
        if IsHandled then
            exit;

        InitInsert();
        InsertMode := true;

        Rec.SetSellToCustomerFromFilter();

        if GetFilterContNo() <> '' then
            Validate("Sell-to Contact No.", GetFilterContNo());

        if "Salesperson Code" = '' then
            SetDefaultSalesperson();

        if "Sell-to Customer No." <> '' then
            StandardCodesMgtGlobal.CheckCreateSalesRecurringLines(Rec);

        // Remove view filters so that the cards does not show filtered view notification
        SetView('');

        OnAfterOnInsert(Rec);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeOnInsert(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean; var InsertMode: Boolean)
    begin
    end;
```

### Additional context

The customization requires handling the insertion of Sales Header on the OnBeforeOnInsert event while also save setting the InsertMode variable.
Internal work item: [AB#504094](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504094)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16993.
