### ISSUE TITLE
[Global Request] Codeunit 99000787 "Create Prod. Order Lines".InitProdOrderLine

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#26046]
### Describe the request

Please do function InitProdOrderLine as global.

### Additional context

We need call this function from our solution.
Internal work item: [AB#504101](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504101)

**Comment by AleksandricMarko** [comment]
Hello @fridrichovsky 
Could you please provide us with more details related to your usage of this procedure.
Main concern is related to a fetching proper ProdOrder record.

**Comment by fridrichovsky** [comment]
Hello @AleksandricMarko,
I am sorry I missed one function. We need two function as global  InitProdOrderLine a InsertProdOrderLine. We have small integration and we would like create Prod. Order Lines with its standard init and insert functions.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19986.
