### ISSUE TITLE
[Request for External] procedures in codeunit 900 "Assembly-Post"

### ISSUE THREAD

**Issue by sschuh** [microsoft/ALAppExtensions#26044]
### Describe the request

hi,

please make these functions accessable:

```
local procedure ValidatePostingDate(var AssemblyHeader: Record "Assembly Header")

local procedure OpenWindow(DocType: Enum "Assembly Document Type")

local procedure InitPost(var AssemblyHeader: Record "Assembly Header")

local procedure Post(var AssemblyHeader: Record "Assembly Header"; var ItemJnlPostLine: Codeunit "Item Jnl.-Post Line"; var ResJnlPostLine: Codeunit "Res. Jnl.-Post Line"; var WhseJnlRegisterLine: Codeunit "Whse. Jnl.-Register Line"; NeedUpdateUnitCost: Boolean)

local procedure FinalizePost(AssemblyHeader: Record "Assembly Header")
```

### Additional context

We need this to do some extra stuff with Assembly Orders.
Internal work item: [AB#504093](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504093)

**Comment by ChethanT** [comment]
@sschuh all these methods seem to depend on one or more global variables to be set, making those methods as public increases the risk of those methods failing or returning undesired results.
Can you please explain the use cases for better understanding?

**Comment by sschuh** [comment]
Hi, sure.

We need some different logic on specific items. (called "Sales Display Items")

The user taps in "Quantity to Assemble" with value 10 in the Assembly header and start posting the document.

We now need to post the document 10 times with a "Quantity to Assemble" with value 1. (Serial Tracking)
Th approach is, that we can match the assembled item and it's components in the item ledger entries.

If you disagree with this change, we need to search for another solution.

**Comment by ChethanT** [comment]
@sschuh sounds like an improvement that we should provide to the posting process. Can you give us more details about the issue you are trying to fix by us exposing those mentioned methods? 
This is what I have tried
1. Create a item 'Assembled Item 1' with replenishment system as 'Assembly'
2. Add Assembly BOM with 2 random items(ensure the items in in stock)
3. Mark the item as an serially tracked item by setting the 'Item Tracking Code'
4. Create 'Assembly Order' and set the Item No. to be the one from 'Assembled Item 1'. This will add the BOM items as assembly lines
5. Set 'Quantity' as 5.....sets 'Quantity to Assemble' as 5
6. Open 'Item Tracking Lines' and assign serial numbers
7. Run 'Preview Posting' ...... works fine and seem to create ledger entries for all 5 output items.
8. Post....seems to work fine whout a need to post 5 times.

**Comment by sschuh** [comment]
@ChethanT 
Your examples work fine.

But here is our scenario:
Assembly Item "Sales Display" (with Serial Tracking)
Components:
10x Red Wine
10x White White

The assembly order has been posted with 2 serial items.

You can see two output lines.
And the cumulated consumption of 20x Red Wine and 20x White Wine.
![image](https://github.com/microsoft/ALAppExtensions/assets/34685182/ebf73f3a-1062-412e-92de-980ea4bd7491)

The cumulated consumption is our problem.


We need following result:

One Ledger Entry for the output item with serial no. SER00001280
One Ledger Entry with consumption of 10x Red wine
One Ledger Entry with consumption of 10x White wine

We need this structure for tracking the components that belongs to SER00001280.

One Ledger Entry for the output item with serial no. SER00001279
One Ledger Entry with consumption of 10x Red wine
One Ledger Entry with consumption of 10x White wine

We need this structure for tracking the components that belongs to SER00001279.

**Comment by ChethanT** [comment]
@sschuh unfortunately, we cannot make this change as increases the chances of public methods being used wrongly. Eventhough the scenario is a valid one, we do not plan to support this at this point. Please post it on ideas site if you have not done it yet.
Input from our PM is that you can use the manufacturing module and create individual prod order line per PCS, so that you can register consumption for exact output or have an alternate solution.
