### ISSUE TITLE
[EVENT REQUEST] codeunit 4810 IntrastatReportManagement – OnBeforeGetIntrastatBaseCountryCode

### ISSUE THREAD

**Issue by elweilando** [microsoft/ALAppExtensions#26040]
### Describe the request

Please add a new in event in GetIntrastatBaseCountryCode

    procedure GetIntrastatBaseCountryCode(ItemLedgEntry: Record "Item Ledger Entry") CountryCode: Code[10]
    var
[...]
// START 
IsHandled : Boolean;
// STOP

    begin
        IntrastatReportSetup.Get();
// START

IsHandled := false;
OnBeforeGetIntrastatBaseCountryCode(ItemLedgEntry, IntrastatReportSetup, CountryCode, IsHandled);
if IsHandled then
    exit;

// STOP

    // START
    [IntegrationEvent(false, false)]
    local procedure OnBeforeGetIntrastatBaseCountryCode(ItemLedgEntry: Record "Item Ledger Entry"; IntrastatReportSetup: Record "Intrastat Report Setup"; var CountryCode: Code[10]; var IsHandeled: Boolean)
    begin
    end;
    // STOP

### Additional context

In some cases, delivery to an EU customer is made to a domestic warehouse operated by the EU customer. These items are for domestic shipment but for EU declaration. With this event, it is possible to adjust the standard processing if necessary.
Internal work item: [AB#504073](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504073)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 16993.
