### ISSUE TITLE
[Request for External] Make procedure VerifyAddress accessible in codeunit 28000 "Post Code Check"

### ISSUE THREAD

**Issue by daniel-williams-fenwick** [microsoft/ALAppExtensions#26054]
### Describe the request

Please make the VerifyAddress procedure accessible - 
![image](https://github.com/microsoft/ALAppExtensions/assets/134581763/c1cd1a62-c978-4bc0-8eaa-34994e9302dd)

### Additional context

We had a reference to the ValidateAddress procedure, but when attempting to upgrade our Microsoft Hosted Clients to version 24.1.16924.0, we get the warning that this procedure is Obsolete. 
![image](https://github.com/microsoft/ALAppExtensions/assets/134581763/547a9a8d-f721-4668-ab2b-5e34da6305e9)

When attempting to update the referenced procedure to the new version (VerifyAddress), we are unable to do so due to inaccessibility:
![image](https://github.com/microsoft/ALAppExtensions/assets/134581763/79351db4-6014-4e47-b8f7-b30d4a2abdc9)

Additionally, it appears the Obsolete tag is incorrect, it references a 'VerifyAddressField' procedure which doesn't exist. Please change this to the correct value of 'VerifyAddress'.
![image](https://github.com/microsoft/ALAppExtensions/assets/134581763/3052871e-e64c-4a50-94f0-c4f34b9ffa0f)

Internal work item: [AB#504230](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504230)

**Comment by daniel-williams-fenwick** [comment]
@AleksandricMarko is there any update on this?

**Comment by willwoodhams** [comment]
@AleksandricMarko Hi there, as it has been 3 months and no response I was hoping you could give any sort of update on this one.

**Comment by AleksandricMarko** [comment]
Hello @willwoodhams 
As far as I can see, this is done (for unknown reason completion is not shown within GitHub)
Still, it is not available in the releases branches, but it should be soon.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
