### ISSUE TITLE
[Extensibility Request] Field "Reason" on table 12116 "Withholding Tax" 

### ISSUE THREAD

**Issue by ArvinNube** [microsoft/ALAppExtensions#26058]
### Describe the request

hello, 
is it possible to convert the Reason field in table 12116 "Withholding Tax" to an Enum? So that it can be extended to fulfill the new types related to Italian taxation?

### Additional context

Each year the taxation could be updated, including new options
Internal work item: [AB#504344](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504344)

**Comment by ArvinNube** [comment]
with Enum Type we can use the enum extension

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17909.
