### ISSUE TITLE
[Event Request] Report 31287 "Create General Journal CZB"

### ISSUE THREAD

**Issue by michalone** [microsoft/ALAppExtensions#26057]
### Describe the request

Hello,

I would like to ask for a new event in report 31287 "Create General Journal CZB" (Czech version of BC) after a bank account record is get. 

```al
local procedure GetBankAccount(IssBankStatementHeaderCZB: Record "Iss. Bank Statement Header CZB")
begin
    IssBankStatementHeaderCZB.TestField("Bank Account No.");
    if BankAccount."No." <> IssBankStatementHeaderCZB."Bank Account No." then begin
        BankAccount.Get(IssBankStatementHeaderCZB."Bank Account No.");
        // START
        OnAfterGetBankAccount(IssBankStatementHeaderCZB, BankAccount);
        // END
        BankAccount.TestField("Payment Jnl. Template Name CZB");
        BankAccount.TestField("Payment Jnl. Batch Name CZB");
        BankAccount.TestField("Non Assoc. Payment Account CZB");
    end;
end;
``` 

```al
[IntegrationEvent(false, false)]
local procedure OnAfterGetBankAccount(IssBankStatementHeaderCZB: Record "Iss. Bank Statement Header CZB"; var BankAccount: Record "Bank Account")
begin
end;
``` 

Thank you.

### Additional context

We need to use multiple payment journal batches - not only one from the bank account card. It means we need to change values in bank account record instance.
Internal work item: [AB#504348](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504348)

**Comment by DavidHolusa** [comment]
Hi @michalone. Would it be possible to place the event a little lower after the testfields?

```
local procedure GetBankAccount(IssBankStatementHeaderCZB: Record "Iss. Bank Statement Header CZB")
begin
    IssBankStatementHeaderCZB.TestField("Bank Account No.");
    if BankAccount."No." <> IssBankStatementHeaderCZB."Bank Account No." then begin
        BankAccount.Get(IssBankStatementHeaderCZB."Bank Account No.");
        BankAccount.TestField("Payment Jnl. Template Name CZB");
        BankAccount.TestField("Payment Jnl. Batch Name CZB");
        BankAccount.TestField("Non Assoc. Payment Account CZB");
    end;
    // START
    OnAfterGetBankAccount(IssBankStatementHeaderCZB, BankAccount);
    // END
end;
```

**Comment by michalone** [comment]
Hi @DavidHolusa,
yes, it could be placed lower as you suggest.
Thanks.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17410.
