### ISSUE TITLE
[Event Request] Codeunit 7017 "Price List Management" OnBeforeResolveDuplicatePrices(PriceListHeader, DuplicatePriceList)

### ISSUE THREAD

**Issue by AbsolutelyFreeWeb** [microsoft/ALAppExtensions#26053]
### Describe the request

Function below throws a pop-up:
ResolveDuplicatePrices(PriceListHeader: Record "Price List Header"; var DuplicatePriceLine: Record "Duplicate Price Line") Resolved: Boolean

Requesting an event with handled boolean to handle the functionality with logic instead of popup

### Additional context

In function 
ResolveDuplicatePrices(PriceListHeader: Record "Price List Header"; var DuplicatePriceLine: Record "Duplicate Price Line") Resolved: Boolean

Have an event OnBeforeResolveDuplicatePrices(PriceListHeader, DuplicatePriceList, handled, resolved) 

if handled then exit(resolved)
Internal work item: [AB#504228](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504228)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17376.
