### ISSUE TITLE
[Event Request] report 5692 "Calculate Depreciation" - procedure SetSuppressCommit

### ISSUE THREAD

**Issue by Sameer-Utekar** [microsoft/ALAppExtensions#26069]
### Describe the request

Hello colleagues,

In report 5692 "Calculate Depreciation" we need a facility to suppress the commit provided in the trigger OnPostDataItem() of data-item "Fixed Asset"

To do so,
1. We need a global variable "SuppressCommmit"
```
var
SuppressCommmit: Boolean;
```

2. We need a new global function to set a value to this global variable
```
  procedure SetSuppressCommit(NewSuppressCommmit: Boolean)
    begin
        SuppressCommmit := NewSuppressCommmit
    end;

```
3. We require an additional check alongside the NeedCommit check to verify the value of SuppressCommit which will skip the commit for us when set to true

Current:
```
  dataitem("Fixed Asset"; "Fixed Asset")

...
trigger OnPostDataItem()
            ...
                OnAfterPostDataItem();
                if NeedCommit then
                    Commit();
            end;
```

Requested change:
 ```
 dataitem("Fixed Asset"; "Fixed Asset")

...
trigger OnPostDataItem()
            ...
                OnAfterPostDataItem();
                ***********************
                if NeedCommit and (not SuppressCommmit) then
                    Commit();
                ***********************
            end;
```

Additionally, you can find a similar solution in the procedure CreateReceiptHeader of report 5753 "Get Source Documents"

### Additional context

We need to skip the Commit() process for certain reasons.

Regards,
Sameer
Internal work item: [AB#505651](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/505651)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17295.
