### ISSUE TITLE
[Scope Request] Table 39 "Purchase Line".InitDeferralCode

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#26062]
### Describe the request

Please change asked and approved OnPrem scope. We asked for this in this issue, but it still not in code. https://github.com/microsoft/ALAppExtensions/issues/25311

### Additional context

We need call function from our module and there is no reason why function is OnPrem it should work in cloud also.
Internal work item: [AB#504544](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/504544)

**Comment by AlexanderYakunin** [comment]
Already done for 24.0
