### ISSUE TITLE
Missing events in ES version (Unable to deploy to appsource)

### ISSUE THREAD

**Issue by leegeurts** [microsoft/ALAppExtensions#26065]
### Describe the request

In the following Object
codeunit 12 "Gen. Jnl.-Post Line"

The following events are missing, they are available in W1. 

OnBeforeCalcPmtDiscPossible
and 
OnCalcPmtDiscPossibleOnBeforeOriginalPmtDiscPossible

Funfact: OnAfterCalcPmtDiscPossible this one is actually available (never called, but it is at least there, so we can at least deploy)

I think that all events that are available in W1 should be available in all localizations. 

Is it possible to add this in:
23.0
23.1
23.2
23.3
23.4
23.5
24.0

### Additional context

This is actually very urgent for us, we made a commitment to our customers, but now are not able to upload it to appsource.

Can you please help us out on this one?
Internal work item: [AB#505108](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/505108)
Internal work item: [AB#505108](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/505108)

**Comment by dcenic** [comment]
It is not only the event that is missing in ES version, but in GenJnlPostLine.PostCust, the entire check CalcPmtDiscPossible(GenJournalLine, CVLedgEntryBuf);
is not present in Business Central ES. There is local Spanish functionality for ignoring discounts on G/L Accounts https://learn.microsoft.com/en-us/dynamics365/business-central/localfunctionality/spain/how-to-ignore-discounts-in-general-ledger-accounts
We will get back to you with more details about this.

**Comment by leegeurts** [comment]
> [counts](https://learn.microsoft.com/en-us/dynamics365/business-central/localfunctionality/spain/how-to-ignore-discounts-in-general-ledger-accounts)
> We will get back to you with more details about this.

I agree that the whole function is missing, I still think the event should be there. Just do not call it.

In the function there are 3 events. 1 is available. 2 are not. I think the other 2 should be at least there (but not called)

**Comment by JesperSchulz** [comment]
This one seems to have stranded. If there's any work pending, could you create a new issue for us and we'll revisit!
