### ISSUE TITLE
codeunit 2053 "Extension Management" - add procedure to retrieve GUID of not installed apps

### ISSUE THREAD

**Issue by toanic** [microsoft/ALAppExtensions#26064]
### Describe the request

The procedure would work similarly to the existing procedure GetLatestVersionPackageIdByAppId on the codeunit 2503. But instead of getting the latest Version it would get the PackageIDs of all the versions of the App, which are no longer installed but still published.
This procedure would have to be accesible through codeunit 2504.

### Additional context

This would immensely simplify the process of deleting all the deprecated PTEs which are left behind when publishing new apps to a sandbox. Currently it is possible to delete the PTEs by running a loop over all possible versions with the procedure: GetSpecificVersionPackageIdByAppId . That is very inefficient or would have to be modified regularly to remain performant.
Internal work item: [AB#505109](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/505109)

**Comment by onbuyuka** [comment]
Hi @toanic! Extension Management is part of System Application and it is available at [BcApps](https://github.com/microsoft/BCApps) where we welcome all open source contributions. We would love for your contribution on this issue as well.
