### ISSUE TITLE
[Exposure Request] codeunit 6140 "E-Doc. Import" - procedure ReceiveDocument

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#26070]
### Describe the request

Please expose the function ReceiveDocument. Currently the function is marked as internal.

### Additional context

The function is currently called either from the codeunit running on the Job Queue Entry or from a Microsoft page. It is desired to have a same function available on other pages.
Internal work item: [AB#506092](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506092)

**Comment by Groenbech96** [comment]
That is by design. Please provide more information about what and why.
