### ISSUE TITLE
[Procedure] Service Line - GetServHeader

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26082]
### Describe the request

Please align the GetServHeader function from 'Service Line' with the GetSalesHeader function from 'Sales Line'.

![image](https://github.com/microsoft/ALAppExtensions/assets/25268332/11f078ae-03c7-499c-a57c-667004d1ec83)

Current function:

```
procedure GetServHeader()
    begin
        TestField("Document No.");
        if ("Document Type" <> ServHeader."Document Type") or ("Document No." <> ServHeader."No.") then begin
            ServHeader.Get(Rec."Document Type", Rec."Document No.");
            if ServHeader."Currency Code" = '' then
                Currency.InitRoundingPrecision()
            else begin
                ServHeader.TestField("Currency Factor");
                Currency.Get(ServHeader."Currency Code");
                Currency.TestField("Amount Rounding Precision");
            end;
        end;
    end;
```

Add **new** function (overload with a return value)

```
procedure GetServHeader(): Record "ServiceHeader"
    begin
        GetServHeader();
        exit(ServHeader);
    end;
```

### Additional context

Streamlined experience between Sales / Service.
Access the ServHeader global from other objects.
Internal work item: [AB#506156](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506156)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18756.
