### ISSUE TITLE
Add IsHandled Parameter | Include Sender in Event - Report "Get Demand To Reserve" (302) "OnSalesOrderLineOnAfterGetRecordOnBeforeSetTempSalesLine"

### ISSUE THREAD

**Issue by PatrickFariaDaSilva** [microsoft/ALAppExtensions#26080]
### Describe the request

Hello,

I either need the IsHandled variable or the sender variable included so that I can decide whether the data record should be inserted or not. In the current event, the SalesOrder data record is always inserted.  

![image](https://github.com/microsoft/ALAppExtensions/assets/136334275/ef9c05af-ee8f-4a3d-866e-3409e77b37c8)

![image](https://github.com/microsoft/ALAppExtensions/assets/136334275/249d268b-9a54-4436-b7fc-38cc052982fc)

Reference to completed request:

[Event Request] Report "Get Demand To Reserve" (302) #25770 

### Additional context

I need this request to decide if the incoming salesorderlines should be inserted in the temp variable or not. 
Internal work item: [AB#506154](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506154)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17295.
