### ISSUE TITLE
[Event Request] Codeunit 5763 "Whse.-Post Shipment" - procedure PrintDocuments() - event OnPrintDocumentsOnAfterPrintServiceShipment

### ISSUE THREAD

**Issue by PWE2118** [microsoft/ALAppExtensions#26084]
### Describe the request

Please add a new Event for table ServiceShptHeader like "Sales Shipment Header"

![image](https://github.com/microsoft/ALAppExtensions/assets/104819817/11aae142-67be-4594-a9a4-7b3a5ef560ce)

New event

* OnPrintDocumentsOnAfterPrintServiceShipment

Old Code:
```
        ServiceShptHeader.MarkedOnly(true);
        if not ServiceShptHeader.IsEmpty() then begin
            ServiceShptHeader.PrintRecords(false);
	end;
```

New Code:
```
        ServiceShptHeader.MarkedOnly(true);
        if not ServiceShptHeader.IsEmpty() then begin
            ServiceShptHeader.PrintRecords(false);
            OnPrintDocumentsOnAfterPrintServiceShipment(ServiceShptHeader."No.");
	end;
```

### Additional context

**Procedure PrintDocuments()**
Only "Sales Shipment Header" has OnPrintDocumentsOnAfterPrint event.
Internal work item: [AB#506180](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506180)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17295.
