### ISSUE TITLE
[Event Request] Codeunit 5763 "Whse.-Post Shipment" - procedure HandleServiceLine - event publisher OnBeforeHandleServiceLine

### ISSUE THREAD

**Issue by katarina-cvetkovic** [microsoft/ALAppExtensions#26085]
### Describe the request

Could you please add the following event and code to Codeunit  5763 "Whse.-Post Shipment" - procedure HandleServiceLine

    IsHandled := false;
    OnBeforeHandleServiceLine(WarehouseShipmentLine, ServiceLine, ModifyLine, IsHandled);
    if IsHandled then
        exit;

Example (code with **):
   ```
 local procedure HandleServiceLine(var WarehouseShipmentLine: Record "Warehouse Shipment Line")
    var
        ServLine: Record "Service Line";
        ModifyLine: Boolean;
        ** IsHandled: Boolean; **
    begin
    ** IsHandled := false;
       OnBeforeHandleServiceLine(WarehouseShipmentLine, ServiceLine, ModifyLine, IsHandled);
       if IsHandled then
          exit; **

        ServLine.SetRange("Document Type", WarehouseShipmentLine."Source Subtype");
        ServLine.SetRange("Document No.", WarehouseShipmentLine."Source No.");
        ....
```
Publisher:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeHandleServiceLine(var WarehouseShipmentLine: Record "Warehouse Shipment Line"; var ServiceLine: Record "Service Line"; var ModifyLine: Boolean; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

Same thing already exists for Sales Line, Purchase Line and Transfer Line. Would need it for Service Line too.
Internal work item: [AB#506296](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506296)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17295.
