### ISSUE TITLE
[Event Request] Italian Base App - table 288 "Vendor Bank Account" - OnModify - Please add an Event

### ISSUE THREAD

**Issue by Jbb93** [microsoft/ALAppExtensions#26081]
### Describe the request

Hi,

in the italian Version of the BC Base App, there is some Code in the OnModify() - Trigger of Table 288 "Vendor Bank Account".
The code is the following:

`
trigger OnModify()
    var
        Confirmed: Boolean;
    begin
        if IBAN = '' then begin
            if not GuiAllowed then
                Confirmed := true
            else
                Confirmed := Confirm(StrSubstNo('%1%2', Text12100, Text12101), false);
            if not Confirmed then begin
                IBAN := xRec.IBAN;
                Modify();
                Commit();
                Error(Text12102);
            end;
        end;
    end;
`

Could please add an Event? Something like the known "IsHandeled"-Pattern, so that we can deacivate this code?

Thank you! 

### Additional context

We would like to deactivate this Code, because this is very painful, if the user wants to modify a lot of records. He has to confirm very often.
Internal work item: [AB#506155](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506155)

**Comment by Jbb93** [comment]
![ITA1](https://github.com/microsoft/ALAppExtensions/assets/57138407/18bf42fd-9c85-4cff-b89d-7c1e7a0cf95a)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17295.
