### ISSUE TITLE
[Event Request] codeunit 90 - "Purch.-Post" - OnAfterPostPurchaseDoc

### ISSUE THREAD

**Issue by achowtc** [microsoft/ALAppExtensions#26095]
### Describe the request

On the IntegrationEvent for OnAfterPostPurchaseDoc, can we add var VendLedgEntry to the function?
![image](https://github.com/microsoft/ALAppExtensions/assets/34691006/afb5aa14-af66-46c7-9d7a-f72d0b0c662b)

I see that the "Sales-Post" codeunit on the OnAfterPostSalesDoc has more variables like CustLedgEntry table that we can extend off of.
![image](https://github.com/microsoft/ALAppExtensions/assets/34691006/83527270-1c40-42b5-a5c7-f58b4cbceda6)

Can we make both integration events with similar variables? 

### Additional context

This will allow us to create functions that works the same way for the purchase and sales side
Internal work item: [AB#506606](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506606)

**Comment by AleksandricMarko** [comment]
Hello @achowtc 

Unfortunately, OnAfterPostPurchaseDoc is global procedure and can`t be changed.
Does some other publisher fits to you?
