### ISSUE TITLE
[Event Request] Codeunit 442 "Sales-Post Prepayments" - OnBeforePrepmtAmount in BC22

### ISSUE THREAD

**Issue by MarkoMilosavljevic** [microsoft/ALAppExtensions#26097]
### Describe the request

Hello, I raised case #26088 which is approved for the current version, or it will be applied in the next major release. What I missed checking is if that publisher can also be created in BC22?
As I understand the reply from Mr. Schulz the publisher will be published in the current version (BC23) or the next major release (BC24).
Did I get this right(regarding BC versions)? And if I did, my question is can this publisher also be created for BC22, or should I adjust the extensibility request?

Best regards,
Marko

### Additional context

We also need this publisher in BC22.
Internal work item: [AB#506770](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506770)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 22.

Build ID to track: 64685.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 23.

Build ID to track: 21893.
