### ISSUE TITLE
[Event Request] codeunit 12 - "Gen. Jnl.-Post Line" - var on GenJournalLine for PostVend function

### ISSUE THREAD

**Issue by achowtc** [microsoft/ALAppExtensions#26096]
### Describe the request

On the function for PostVend, can we add var to the GenJournalLine variable?
![image](https://github.com/microsoft/ALAppExtensions/assets/34691006/a3b2757e-e805-4a3b-93de-8a5aa3032a58)

I noticed the var is available for the PostCust. 
![image](https://github.com/microsoft/ALAppExtensions/assets/34691006/fcad09bf-e912-4d23-848d-c03bad0d5846)

### Additional context

This will allow us to create the same functionalities for both the purchase and the sales side.
Internal work item: [AB#506774](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506774)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19454.
