### ISSUE TITLE
[Event Request] Events in CU12

### ISSUE THREAD

**Issue by Gwrsky** [microsoft/ALAppExtensions#26098]
### Describe the request

Hey,
I'm developing a modification for a client, which skips the applying the payment discounts, as in Polish TAX law you have to post a Credit memo for each discount. We want to skip the applying the payment discount, and then create a credit memo for that discount. We've prepared a report which creates Credit Memos based on those non-applies discounts, but that doesn't matter for this issue.

We've already made that modification in NAV2015 and it works perfectly, but in BC23 i don't have the same ability to modify code.

Below is the modification in NAV2015:
![image](https://github.com/microsoft/ALAppExtensions/assets/72869582/028ca586-99f6-4ab9-b600-b3e2f5b5f7c3)

Would it be possible to get the events like to match our solution in 2015?

CU12:
In Line 2843 after then: begin
Add New Line, After line 2844, OnAfterSetAppliedAmountFromRemainingAmount(OldCVLedgEntryBuf2, AppliedAmount, GenJnlLine);
in line 2845 end else;

Add New Line, After Line 2861: OnAfterSetAppliedAmountFromRemainingAmountOnEmptyFilter(OldCVLedgEntryBuf2, AppliedAmount, GenJnlLine);

Add param GenJnlLine in procedure: FindAmtForAppln.
In Line 2286, Add Event OnBeforeInitDetailedCVLedgEntryBuff with isHandled, and if not IsHandled then Do line 2287.

I'd really appreciate the positive feedback as this functionality is crucial to our customer.

### Additional context

In Polish TAX law you have to post Credit Memo for every Payment discount given. This is important for our customer as he's processing a lot of Sales Credit Memos because of Payment Discounts.
Internal work item: [AB#521442](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521442)

**Comment by AleksandricMarko** [comment]
Hello @Gwrsky 

Be aware that we currently adding new event requests just to BC24.
Does that fit for you?

**Comment by Gwrsky** [comment]
@AleksandricMarko Hi,
Yes, that's ok as we're in process of upgrading - final version will be determined by ending date of projekt - not  earlier than 07.2024

**Comment by AleksandricMarko** [comment]
Hi @Gwrsky 
Please define structure of the wanted publishers to be sure that you will get expected values (pass by reference, etc...)

**Comment by Gwrsky** [comment]
Hi @AleksandricMarko 

In procedure FindAmtForAppln Please add Parameter GenJnlLine, for me without VAR is sufficient, but you might wanna add it with VAR for another developers.
And then, the provided Publishers:

[IntegrationEvent(false, false)]
local procedure OnAfterSetAppliedAmountFromRemainingAmount(OldCVLedgEntryBuf2: Record "382"; var AppliedAmount: Decimal; GenJnlLine: Record "81")
    begin
    end;

[IntegrationEvent(false, false)]
local procedure OnAfterSetAppliedAmountFromRemainingAmountOnEmptyFilter(OldCVLedgEntryBuf2: Record "382"; var AppliedAmount: Decimal; GenJnlLine: Record "81")
    begin
    end;

[IntegrationEvent(false,false)]
local procedure OnBeforeInitDetailedCVLedgEntryBuff(var IsHandled: Boolean; GenJnlLine: Record "Gen. Journal Line")
    begin
    end;
/\/\/\ For me this is enough, but you might wanna add rest of params for further use:
var NewCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; var OldCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; var OldCVLedgEntryBuf2: Record "CV Ledger Entry Buffer"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer";



and in next lines if isHandled = true then please skip the procedure DtldCVLedgEntryBuf.InitDetailedCVLedgEntryBuf

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19454.
