### ISSUE TITLE
[Event Request] - Codeunit 1393 "Cancel Issued Reminder" - Function DecreaseCustomerLedgerEntryLastIssuedReminderLevel

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#26102]
### Describe the request

```
  local procedure DecreaseCustomerLedgerEntryLastIssuedReminderLevel(EntryNo: Integer)
    var
        CustLedgerEntry: Record "Cust. Ledger Entry";
    begin
        CustLedgerEntry.Get(EntryNo);
        CustLedgerEntry."Last Issued Reminder Level" := GetLastReminderLevel(EntryNo);
        //NewEvent
        OnDecreaseCustomerLedgerEntryLastIssuedReminderLevelOnBeforeModify(CustLedgerEntry);
        //NewEvent
        CustLedgerEntry.Modify();
    end;
```

```
[IntegrationEvent(false, false)]
    local procedure OnDecreaseCustomerLedgerEntryLastIssuedReminderLevelOnBeforeModify(var CustLedgerEntry: Record "Cust. Ledger Entry")
    begin
    end;
```

### Additional context

Because i want to update a custom table after last issued reminder level is set. 
Internal work item: [AB#506996](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506996)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18666.
