### ISSUE TITLE
[Change Event] codeunit 12 "Gen. Jnl.-Post Line" - publisher OnAfterSetDtldVendLedgEntryNoOffset and publisher OnAfterSetDtldCustLedgEntryNoOffset

### ISSUE THREAD

**Issue by Payal5522** [microsoft/ALAppExtensions#26104]
### Describe the request

Hello Colleagues,

Could we please incorporate the parameter 'DtldVendLedgEntryNoOffset' into the publisher OnAfterSetDtldVendLedgEntryNoOffset of codeunit 12 'Gen. Jnl.-Post Line', and similarly, include the parameter 'DtldCustLedgEntryNoOffset' in the publisher OnAfterSetDtldCustLedgEntryNoOffset of codeunit 12 'Gen. Jnl.-Post Line'?

Before change:
```
   [IntegrationEvent(false, false)]
    local procedure OnAfterSetDtldVendLedgEntryNoOffset(var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer")
    begin
    end; 
    
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetDtldCustLedgEntryNoOffset(var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer")
    begin
    end;
```

Requested change:
```
  [IntegrationEvent(false, false)]
    local procedure OnAfterSetDtldVendLedgEntryNoOffset(var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer";var DtldVendLedgEntryNoOffset:Integer)
    begin
    end; 
    
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetDtldCustLedgEntryNoOffset(var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer";var DtldCustLedgEntryNoOffset:Integer)
    begin
    end;
```

### Additional context

The reason is that we aim to read the DtldVendLedgEntryNoOffset and DtldCustLedgEntryNoOffset within the subscription. so it can be passed by value.
Internal work item: [AB#507355](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/507355)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
