### ISSUE TITLE
[Event Request] - Add Parameter in OnCheckAndUpdateOnBeforeSetPostingFlags in Codeunit 80 "Sales-Post"

### ISSUE THREAD

**Issue by riccardodellantonio** [microsoft/ALAppExtensions#26106]
### Describe the request

Hello ALAppExtensions Team,
could you add a parameter to hide the dialog window in the Sales-Post Codeunit when performing Sales Document Checks?

```
procedure CheckSalesDocument(var SalesHeader: Record "Sales Header")
// ...... //
begin
        // ...... //
        if (SalesHeader."Last Prepayment No." <> '') or (SalesHeader."Last Prepmt. Cr. Memo No." <> '') then
            SalesHeader.CheckIfCompressPrepaymentCanBeUsed();

        OnCheckAndUpdateOnBeforeSetPostingFlags(SalesHeader, TempSalesLineGlobal, ModifyHeader, HideProgressWindow);

        // ...... //

        if not HideProgressWindow then
            InitProgressWindow(SalesHeader);

        // ...... //
```

```
[IntegrationEvent(true, false)]
local procedure OnCheckAndUpdateOnBeforeSetPostingFlags(var SalesHeader: Record "Sales Header"; var TempSalesLineGlobal: Record "Sales Line" temporary; var ModifyHeader: Boolean; var HideProgressWindow: Boolean);
begin
end;
```

Or in another event before the "In not HideProgressWindow then" line (including the one in the "PrepareCheckDocument" procedure).

### Additional context

I want to perform checks on the sales document before the actual posting procedure. I'm doing it with an "ErrorBehaviour::Collect" procedure which calls the standard codeunit - 9071 "Check Sales Document".
The codeunit then calls directly the "CheckSalesDocument" procedure in the "Sales-Post" codeunit, so it's not possible to set the parameter "HideProgressWindow" elsewhere.
Internal work item: [AB#507354](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/507354)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17842.
