### ISSUE TITLE
[Event Request] Codeunit 1535 "Approvals Mgmt." - ApproveSelectedApprovalRequest - add event before calling OnApproveApprovalRequest

### ISSUE THREAD

**Issue by sergeyol** [microsoft/ALAppExtensions#26101]
### Describe the request

We ask to add an event just before calling OnApproveApprovalRequest in ApproveSelectedApprovalRequest function:

```
local procedure ApproveSelectedApprovalRequest(var ApprovalEntry: Record "Approval Entry")
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeApproveSelectedApprovalRequest(ApprovalEntry, IsHandled);
    if IsHandled then
        exit;
    CheckOpenStatus(ApprovalEntry, "Approval Action"::Approve, ApproveOnlyOpenRequestsErr);

    if ApprovalEntry."Approver ID" <> UserId then
        CheckUserAsApprovalAdministrator(ApprovalEntry);

    ApprovalEntry.Validate(Status, ApprovalEntry.Status::Approved);
    ApprovalEntry.Modify(true);

    OnBeforeOnApproveApprovalRequest(ApprovalEntry);

    OnApproveApprovalRequest(ApprovalEntry);
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeOnApproveApprovalRequest(var ApprovalEntry: Record "Approval Entry")
begin
end;
```

It can additionally be enriched with IsHandled pattern though we do not need it.

### Additional context

OnApproveApprovalRequest event is actually a not good extensibility point because it is actively being used by the approval engine itself, and we are not able to control the order of events execution.

We need to add a subscriber that is guaranteed to run **before** OnApproveApprovalRequest subscribers from the base app and other apps.
Internal work item: [AB#506772](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/506772)

**Comment by haoranpb** [comment]
Hi @sergeyol ,

Thanks for opening an event request.

After reviewing the proposed event and provided context, we want to suggest the alternative event: `OnBeforeRunWorkflowOnApproveApprovalRequest`.

You should be able to find it inside the `WorkflowEventHandling.Codeunit.al`, and it is run before the first-party subscriber.

I will close this issue for now, if you have follow-up questions or requests, we do not monitor closed issues, so please create a new issue where you reference this one.
