### ISSUE TITLE
IT - codeunit "Vend. Bill List-Change Status" remove procedures scope OnPrem

### ISSUE THREAD

**Issue by rmurriero-alterna** [microsoft/ALAppExtensions#26116]
### Describe the request

Hi, we would need the "OnPrem" scope present in methods "FromOpenToSent" and "FromOpenToSent" of the codeunit with IT localization "Vend. Bill List-Change Status" to be removed.

```
codeunit 12171 "Vend. Bill List-Change Status"

...

[Scope('OnPrem')]        // remove this line
procedure FromOpenToSent(var VendorBillHeader: Record "Vendor Bill Header")

...

[Scope('OnPrem')]        // remove this line
procedure FromSentToOpen(var VendorBillHeader: Record "Vendor Bill Header")
```
Thank you

### Additional context

We need to be able to send vendor bills (and undo sent vendor bills) without user interaction.
Internal work item: [AB#507530](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/507530)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
