### ISSUE TITLE
[Request for External] page 99000811 "Prod. BOM Where-Used" Item

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#26115]
### Describe the request

page 99000811 "Prod. BOM Where-Used"
Can you make the global variabel Item protected var?
Or create a procedure to be able to get the item variabel.

### Additional context

We use this variabel to find additional information
Internal work item: [AB#507528](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/507528)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18615.
