### ISSUE TITLE
Change protection level of variables ShipToAddr and  CompanyInfo in Report 1309 "Standard Sales - Return Rcpt.", Report 6636 "Purchase - Return Shipment", Report 407 "Purchase - Credit Memo", Report 408 "Purchase - Receipt" 

### ISSUE THREAD

**Issue by SerhiiKorniichuk1** [microsoft/ALAppExtensions#26118]
### Describe the request

Hello, please, change these var to protected var:

**1.Report 1309 "Standard Sales - Return Rcpt."**

Current:
var
ShipToAddr: array[8] of Text[100];

Should be:
protected var
ShipToAddr: array[8] of Text[100];

**2.Report 6636 "Purchase - Return Shipment"**

Current:
var
ShipToAddr: array[8] of Text[100];
CompanyInfo: Record "Company Information";

Should be:
protected var
ShipToAddr: array[8] of Text[100];
CompanyInfo: Record "Company Information";

**3.Report 407 "Purchase - Credit Memo"**

Current:
var
ShipToAddr: array[8] of Text[100];
CompanyInfo: Record "Company Information";

Should be:
protected var
ShipToAddr: array[8] of Text[100];
CompanyInfo: Record "Company Information";

**4.Report 408 "Purchase - Receipt"**

Current:
var
ShipToAddr: array[8] of Text[100];
CompanyInfo: Record "Company Information";

Should be:
protected var
ShipToAddr: array[8] of Text[100];
CompanyInfo: Record "Company Information";

### Additional context

This is necessary to enable the ability to set parameters in procedure 
GetCompanyAddr(... var CompanyInfo: Record "Company Information", var CompanyAddr: array[8] of Text[100]) to improve the functionality required to perform tasks.
Internal work item: [AB#507529](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/507529)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18615.
