### ISSUE TITLE
[Event Request] Event on CalcTimeDelta in codeunit 7600 "Calendar Management"

### ISSUE THREAD

**Issue by Aize-S** [microsoft/ALAppExtensions#26121]
### Describe the request

Please implement an OnBeforeCalcTimeDelta event:
```
    procedure CalcTimeDelta(EndingTime: Time; StartingTime: Time) Result: Integer
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCalcTimeDelta(EndingTime, StartingTime, Result, IsHandled);
        if IsHandled then
            exit;

        Result := EndingTime - StartingTime;
        if (Result <> 0) and (EndingTime = 235959T) then
            Result += 1000;
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcTimeDelta(EndingTime: Time; StartingTime: Time; var Result: Integer; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

Sometimes CalcTimeDelta in Calendar Management is called with an empty EndingTime and/or StartingTime. Resulting in a runtime error. For instance when "Response Time (Hours)" is validated on a Service Order with "Order Time" 0T. The resulting error message is also strange, as it says "The date is invalid.".
Internal work item: [AB#507786](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/507786)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17842.
