### ISSUE TITLE
[Change Request] page 1190 "Create Payment" - procedure UpdateDimensions

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#26129]
### Describe the request

Hello, can you please change the local procedure UpdateDimensions to protected procedure?

```
    protected procedure UpdateDimensions(var GenJnlLine: Record "Gen. Journal Line"; TempVendorPaymentBuffer: Record "Vendor Payment Buffer" temporary)
    var
        DimBuf: Record "Dimension Buffer";
        TempDimSetEntry: Record "Dimension Set Entry" temporary;
        DimVal: Record "Dimension Value";
        DimBufMgt: Codeunit "Dimension Buffer Management";
        DimMgt: Codeunit DimensionManagement;
        NewDimensionID: Integer;
        DimSetIDArr: array[10] of Integer;
    begin
        if GenJnlLine."Dimension Set ID" = 0 then begin
            NewDimensionID := GenJnlLine."Dimension Set ID";

            DimBuf.Reset();
            DimBuf.DeleteAll();
```

### Additional context

This allow page extensions to modify the visibility of page elements after data updates.
Internal work item: [AB#507945](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/507945)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18941.
