### ISSUE TITLE
[Event Request] Event on UpdateBank from codeunit 370 "Bank Acc. Reconciliation Post"

### ISSUE THREAD

**Issue by jmartin93** [microsoft/ALAppExtensions#26120]
### Describe the request

Hi,

We need and event on codeunit 370 "Bank Acc. Reconciliation Post", procedure UpdateBank:

This is the code now:
```
local procedure UpdateBank(BankAccRecon: Record "Bank Acc. Reconciliation"; Amt: Decimal)
    begin
        with BankAcc do begin
            LockTable();
            Get(BankAccRecon."Bank Account No.");
            TestField(Blocked, false);
            "Last Statement No." := PostedStamentNo;
            "Balance Last Statement" := BankAccRecon."Balance Last Statement" + Amt;
            Modify();
        end;
    end;
```

And we need it like this:

```
local procedure UpdateBank(BankAccRecon: Record "Bank Acc. Reconciliation"; Amt: Decimal)
    >>>>>>>>>>>>>>>>>>>>>
    var
        IsHandled: Boolean;
    <<<<<<<<<<<<<<<<<<<<
    begin
        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        IsHandled := false;
        OnBeforeUpdateBank(BankAccRecon, IsHandled);
        if IsHandled then
            exit;
        <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        with BankAcc do begin
            LockTable();
            Get(BankAccRecon."Bank Account No.");
            TestField(Blocked, false);
            "Last Statement No." := PostedStamentNo;
            "Balance Last Statement" := BankAccRecon."Balance Last Statement" + Amt;
            Modify();
        end;
    end;

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateBank(var BankAccRecon: Record "Bank Acc. Reconciliation"; var IsHandled: Boolean)
    begin
    end;
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

### Additional context

We need to skip the change on "Last Statement No." because if a customer posts an older Conciliation this will change the Last Number and the new Conciliation number could be a number that was already used. 
Example: 
1) we have Conciliations with Statement No. 24 and 25.
2) we post 24 and the Last Statement No. updates to 24.
3) We create a new Conciliation, it tries to give the number 25 but it already exists and we get an error
Internal work item: [AB#507675](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/507675)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18975.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 18977.
