### ISSUE TITLE
[Event Request] codeunit 5780 "Whse. Cross-Dock Management" - OnAfterFilterWhseRcptLine

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26137]
### Describe the request

```
local procedure FilterWhseRcptLine(var WarehouseReceiptLine: Record "Warehouse Receipt Line")
    begin
        with WarehouseReceiptLine do begin
            SetRange("No.", NameNo);
            SetRange("Location Code", LocationCode);
            SetFilter("Qty. to Receive", '>0');
        end;

        OnAfterFilterWhseRcptLine(WarehouseReceiptLine, NameNo, LocationCode); // NEW Event here
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterFilterWhseRcptLine(var WarehouseReceiptLine: Record "Warehouse Receipt Line"; NameNo: Code[20]; LocationCode: Code[10])
    begin
    end;
```

### Additional context

We would like to exclude certain whse receipt lines from being used in the crossdock calculation logic.
Internal work item: [AB#521246](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521246)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17842.
