### ISSUE TITLE
[Bug]: Incorrect return value in prodecure GetNoTaxableSalesAmount in codeunit 10756 "SII Management"

### ISSUE THREAD

**Issue by RamonCobo** [microsoft/ALAppExtensions#26138]
### Describe the issue

On the prodecure GetNoTaxableSalesAmount at codeunit 10756 "SII Management" 

```
    IsHandled := false;
        OnBeforeGetNoTaxableSalesAmount(
            NoTaxableEntry, SourceNo, DocumentType, DocumentNo, PostingDate, IsService,
            UseNoTaxableType, IsLocalRule, NoTaxableAmount, Result, IsHandled);
        if IsHandled then
            exit(false);

```
The exit value should be `Result` not `false`

Thanks.

### Expected behavior

```
    IsHandled := false;
        OnBeforeGetNoTaxableSalesAmount(
            NoTaxableEntry, SourceNo, DocumentType, DocumentNo, PostingDate, IsService,
            UseNoTaxableType, IsLocalRule, NoTaxableAmount, Result, IsHandled);
        if IsHandled then
            exit(Result);

```

### Steps to reproduce

subcribe to the event OnBeforeGetNoTaxableSalesAmount and set the result value to true

### I will provide a fix for a bug

- [X] I will provide a fix for a bug
Internal work item: [AB#522794](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/522794)

**Comment by JesperSchulz** [comment]
As this code is in a local version, it's not a candidate for code contribution 😔 But given the detailed description of your fix, I'll quickly do the change myself 😉 This is normally not the right place to report bugs to the product group, but let's make an exception here... Closing issue. Fix will be provided.
