### ISSUE TITLE
[Event Request] Table 5050 "Contact" - OnBeforeCreateBankAccountLink

### ISSUE THREAD

**Issue by iamcgomes** [microsoft/ALAppExtensions#26148]
### Describe the request

Could you please add the following **OnBeforeCreateBankAccountLink** event to procedure **CreateBankAccountLink** in **Table 5050 "Contact"**?

Current
```AL
procedure CreateBankAccountLink()
var
    ContBusRel: Record "Contact Business Relation";
begin
    CheckIfPrivacyBlockedGeneric();
    TestField("Company No.");
    RMSetup.Get();
    RMSetup.TestField("Bus. Rel. Code for Bank Accs.");
    CreateLink(
        PAGE::"Bank Account Link",
        RMSetup."Bus. Rel. Code for Bank Accs.",
        ContBusRel."Link to Table"::"Bank Account");
end;
```

Requested
```AL
procedure CreateBankAccountLink()
var
    ContBusRel: Record "Contact Business Relation";
    IsHandled: Boolean; //New
begin
    //> New
    IsHandled := false;
    OnBeforeCreateBankAccountLink(Rec, IsHandled);
    if IsHandled then
        exit;
    //< New

    CheckIfPrivacyBlockedGeneric();
    TestField("Company No.");
    RMSetup.Get();
    RMSetup.TestField("Bus. Rel. Code for Bank Accs.");
    CreateLink(
        PAGE::"Bank Account Link",
        RMSetup."Bus. Rel. Code for Bank Accs.",
        ContBusRel."Link to Table"::"Bank Account");
end;
```
```AL
//> New
[IntegrationEvent(false, false)]
local procedure OnBeforeCreateBankAccountLink(var Contact: Record Contact; var IsHandled: Boolean)
begin
end;
//< New
```

### Additional context

We need override the procedure "CreateBankAccountLink".
Similar events exists in the procedures: CreateCustomerLink and CreateVendorLink
Internal work item: [AB#521295](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521295)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17842.
