### ISSUE TITLE
Variant Code in Family Lines and Create Prod. Order Lines

### ISSUE THREAD

**Issue by RamonDiazBlanco** [microsoft/ALAppExtensions#26143]
### Describe the request

The extension of manufacturing management to products with variants, should add "Variant Code" in table "99000774 Family Line" and modify in codeunit "99000787 Create Prod. Order Lines" the CopyFromFamily procedure.
In this procedure should modify call to InitProdOrderLine adding the "Variant Code"

### Additional context

local procedure CopyFromFamily(): Boolean
    var
        Family: Record Family;
        FamilyLine: Record "Family Line";
        ErrorOccured: Boolean;
    begin
        Family.Get(ProdOrder."Source No.");
        FamilyLine.SetCurrentKey("Low-Level Code");
        FamilyLine.SetRange("Family No.", ProdOrder."Source No.");
        OnCopyFromFamilyOnAfterFamilyLineSetFilters(FamilyLine, ProdOrder);

        if FamilyLine.FindSet() then
            repeat
                if FamilyLine."Item No." <> '' then begin
//Original
//                    InitProdOrderLine(FamilyLine."Item No.", '', ProdOrder."Location Code");
//New
                    InitProdOrderLine(FamilyLine."Item No.", "Variant Code'', ProdOrder."Location Code");
//End
                    OnCopyFromFamilyOnAfterInitProdOrderLine(ProdOrder, FamilyLine, ProdOrderLine);
                    ProdOrderLine.Description := FamilyLine.Description;
                    ProdOrderLine."Description 2" := FamilyLine."Description 2";

**Comment by onbuyuka** [comment]
That might just be a product defect! Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps). We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
