### ISSUE TITLE
[Public function] codeunit 5780 "Whse. Cross-Dock Management" - expose CalcCrossDockedQtyInPostedReceipt

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26142]
### Describe the request

Can you please expose function CalcCrossDockedQtyInPostedReceipt in codeunit 5780 "Whse. Cross-Dock Management"?

### Additional context

.
Internal work item: [AB#521284](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521284)

**Comment by fvet** [comment]
@onbuyuka 

Can you please add a publisher as well (as there seems to be a bug / unsupported scenarios in the crossdocked qty calculation when the putaway crossdock bin would be different then the bin from the posted whse receipt line)?

```
procedure CalcCrossDockedQtyInPostedReceipt(PostedWhseReceiptLine: Record "Posted Whse. Receipt Line"): Decimal
    var
        WarehouseEntry: Record "Warehouse Entry";
    begin
        WarehouseEntry.SetRange("Whse. Document Type", WarehouseEntry."Whse. Document Type"::Receipt);
        WarehouseEntry.SetRange("Whse. Document No.", PostedWhseReceiptLine."No.");
        WarehouseEntry.SetRange("Whse. Document Line No.", PostedWhseReceiptLine."Line No.");

        // BUG ?? - This is probably incorrect as the user can still change the cross dock bin on the putaway line ...
        // Better would be to check on cross-dock zone instead (or all 'cross-dock' bins)
        WarehouseEntry.SetFilter("Bin Code", PostedWhseReceiptLine."Cross-Dock Bin Code");

        OnCalcCrossDockedQtyInPostedReceiptOnBeforeSetWarehouseEntryFilters(PostedWhseReceiptLine, WarehouseEntry); // <<< ADD event here

        WarehouseEntry.CalcSums("Qty. (Base)");
        exit(WarehouseEntry."Qty. (Base)");
    end;
```

```
[IntegrationEvent(false, false)]
    local procedure OnCalcCrossDockedQtyInPostedReceiptOnBeforeSetWarehouseEntryFilters(PostedWhseReceiptLine: Record "Posted Whse. Receipt Line"; var WarehouseEntry: Record "Warehouse Entry")
    begin
    end;
```

**Comment by JakovljevicDusan** [comment]
@fvet, please create new issue for event request

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18704.
