### ISSUE TITLE
[Request for External] - Report 840 Suggest Worksheet Lines - Function SetCashflowDate

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#26149]
### Describe the request

Could SelectionCashFlowForecast be added as a parameter to the OnBeforeSetCashFlowDate publisher event?

```
    local procedure SetCashFlowDate(var CashFlowWorksheetLine: Record "Cash Flow Worksheet Line"; CashFlowDate: Date)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetCashFlowDate(CashFlowWorksheetLine,SelectionCashFlowForecast, IsHandled);
        if IsHandled then
            exit;

        CashFlowWorksheetLine."Cash Flow Date" := CashFlowDate;
        if CashFlowDate < WorkDate() then begin
            if SelectionCashFlowForecast."Overdue CF Dates to Work Date" then
                CashFlowWorksheetLine."Cash Flow Date" := WorkDate();
            CashFlowWorksheetLine.Overdue := true;
        end
    end;
```

```
 [IntegrationEvent(false, false)]
    local procedure OnBeforeSetCashFlowDate(var CashFlowWorksheetLine: Record "Cash Flow Worksheet Line";SelectionCashFlowForecast: Record "Cash Flow Forecast";; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

We override the date and set ishandled, but i want to still be able to use SelectionCashFlowForecast."Overdue CF Dates to Work Date" - if i get this parameter i dont have to get the cashflowforecast and check the value.
Internal work item: [AB#521370](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521370)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17842.
