### ISSUE TITLE
Variant Code in page 99000886 Subcontracting whorksheet

### ISSUE THREAD

**Issue by RamonDiazBlanco** [microsoft/ALAppExtensions#26144]
### Describe the request

The extension of manufacturing management to products with variants, should add "Variant Code" in "page 99000886 subcontracting worksheet"

### Additional context

In other worksheets pages is possible show "Variant Code" baut in this page is not possible

**Comment by onbuyuka** [comment]
That might just be a product defect! Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps). We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
