### ISSUE TITLE
[Event Request] report 11016 "Create XML-File VAT Adv.Notif." - New Event "OnSalesVATAdvanceNotifAfterGetRecordOnAfterVATStmtNameSetFilters"

### ISSUE THREAD

**Issue by Mike-1984** [microsoft/ALAppExtensions#26159]
### Describe the request

Hello colleagues,

Could you please create an event in report 11016 "Create XML-File VAT Adv.Notif." in trigger OnAfterGetRecord() of dataitem "Sales VAT Advance Notif."
```
        dataitem("Sales VAT Advance Notif."; "Sales VAT Advance Notif.")
        {
            ....
            trigger OnAfterGetRecord()
            var
            ....
            begin
                .....
                VATStmtName.SetRange("Sales VAT Adv. Notif.", true);
========>       OnSalesVATAdvanceNotifAfterGetRecordOnAfterVATStmtNameSetFilters("Sales VAT Advance Notif.", VATStmtName);
                VATStmtName.FindFirst();

```
New event signature:
```
    [IntegrationEvent(false, false)]
    local procedure OnSalesVATAdvanceNotifAfterGetRecordOnAfterVATStmtNameSetFilters(var SalesVATAdvNotif: Record "Sales VAT Advance Notif."; var VATStmtName: Record "VAT Statement Name")
    begin
    end;


```

### Additional context

We are implementing a solution that will enable the creation of a unified VAT Export for a cluster of associated companies that belong to a single fiscal entity.

We need additional/custom filtering for a "VAT Statement Name" which will be used for XML generation.
Internal work item: [AB#521596](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521596)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
