### ISSUE TITLE
[Event Request] Codeunit 7600 "Calendar Management" - OnBeforeSetSource

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#26152]
### Describe the request

Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnBeforeSetSource' to be added to procedure SetSource in codeunit 7600 "Calendar Management".

````
    procedure SetSource(SourceVariant: Variant; var NewCustomCalendarChange: Record "Customized Calendar Change")
    begin
        OnBeforeSetSource(SourceVariant, NewCustomCalendarChange); //new
        if not SourceVariant.IsRecord then
            Error(SourceErr);

        FillSource(SourceVariant, NewCustomCalendarChange);
        CombineChanges(NewCustomCalendarChange, TempCustChange)
    end;

````
````
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetSource(SourceVariant: Variant; var NewCustomizedCalendarChange: Record "Customized Calendar Change")
    begin
        //new
    end;
````

### Additional context

In some scenario's we use the calendar of a different company. Therefore we should be able to call NewCustomizedCalendarChange.ChangeCompany().
Internal work item: [AB#521543](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521543)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18489.
