### ISSUE TITLE
[Event Request] Table "Sales VAT Advance Notif." - New Event "OnBeforeCalcLineTotal"

### ISSUE THREAD

**Issue by Mike-1984** [microsoft/ALAppExtensions#26158]
### Describe the request

Hello colleagues,

Could you please create an event in table 11021 "Sales VAT Advance Notif." in function CalcLineTotal

```
    local procedure CalcLineTotal(VATStmtLine2: Record "VAT Statement Line"; Level: Integer): Boolean
    var
        ...
        IsHandled: Boolean;  <===========
    begin
        OnBeforeCalcLineTotal(Rec, VATStmtLine2, Level, IsHandled); <===========
        if isHandled then <===========
            exit; <===========
```
New event signature:
```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcLineTotal(Rec: Record "Sales VAT Advance Notif."; VATStmtLine2: Record "VAT Statement Line"; Level: Integer; var IsHandled: Boolean)
    begin

    end;

```

### Additional context

We are implementing a solution that will enable the creation of a unified VAT Export for a cluster of associated companies that belong to a single fiscal entity.

Additionaly to standard calculations, we need to calculate and add amounts from other companies.
Internal work item: [AB#521597](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521597)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
