### ISSUE TITLE
[Request for External] Codeunit 815 Sales Post Invoice function RunOnPrepareLineOnBeforePrepareDeferralLine

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#26157]
### Describe the request

Could DeferralAcount and SalesAccount be added to this function, and the event in that function as var?

```
if SalesLine."Deferral Code" <> '' then begin
            SalesPostInvoiceEvents.RunOnPrepareLineOnBeforePrepareDeferralLine(
                SalesLine, InvoicePostingBuffer, SalesHeader.GetUseDate(), InvDefLineNo, DeferralLineNo, SuppressCommit,DeferralAccount, SalesAccount);
```

### Additional context

I need to change the accounts
Internal work item: [AB#521544](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/521544)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
