### ISSUE TITLE
Access to event BeforeRetrieveTrackingUrl

### ISSUE THREAD

**Issue by eivindgiske** [microsoft/ALAppExtensions#26167]
### Describe the request

Hi, we need control over the tracking urls updated into Shopfiy shipments. Codeunit 30192 has an event, set to internal, which seems not to be in use, and would be perfect for us. Please make this event accessible.

https://github.com/microsoft/ALAppExtensions/blob/3ba9bae2c72ae1935a7c6eeb18b88bff617664a6/Apps/W1/Shopify/app/src/Shipping/Codeunits/ShpfyShippingEvents.Codeunit.al#L11

### Additional context

The Shopify connector only updates Transport Method, and does not provide very much control over Shipment Methods. When using a more complex scenario with an external Transport Administration system, we need more control over tracking urls than what's currently possible in the Shopify Connector
Internal work item: [AB#522698](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/522698)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 18571.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
