### ISSUE TITLE
[Event Request] Add Event for Correcting OCR Data. 

### ISSUE THREAD

**Issue by JohanvdHeijden** [microsoft/ALAppExtensions#26168]
### Describe the request

Add Event for Correcting OCR Data. 
We have unique fields for our clients in the Incoming Documents, that we want to correct using the OCR Correct Data page/action. After receiving the scanned document back from the Kofax/OCR functionality. Currently we don???t have the possibility to correct our own unique fields, because there are no event subscribers where we can change the values of our own fields.

We like to request an event:
-	On the Codeunit: ???Pre Map Incoming Purch Doc??? - Codeunit in the procedure: ???CorrectHeaderData???. We would like an new event: OnAfterCorrectHeaderData(EntryNo: Integer, Table: Variant, FieldNo: Integer, FieldRef). So we can correct our own fields.

### Additional context

Without this request we can not change our own unique fields from Business Central itself and our clients have to send the document back to Kofax to change it again, which is quite annoying for our customers.
Internal work item: [AB#522695](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/522695)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
