### ISSUE TITLE
[Request for External] InsertIntegrationFieldMapping(...) in 5334 "CRM Setup Defaults"

### ISSUE THREAD

**Issue by TKapitan** [microsoft/ALAppExtensions#26171]
### Describe the request

Please make this procedure public so it can be reused by custom integration incl. the existing event.

Codeunit 5334 "CRM Setup Defaults"

```
    local procedure InsertIntegrationFieldMapping(IntegrationTableMappingName: Code[20]; TableFieldNo: Integer; IntegrationTableFieldNo: Integer; SynchDirection: Option; ConstValue: Text; ValidateField: Boolean; ValidateIntegrationTableField: Boolean)
    var
        IntegrationFieldMapping: Record "Integration Field Mapping";
        IsHandled: Boolean;
    begin
        OnBeforeInsertIntegrationFieldMapping(IntegrationTableMappingName, TableFieldNo, IntegrationTableFieldNo, SynchDirection, ConstValue,
          ValidateField, ValidateIntegrationTableField, IsHandled);

        if IsHandled then
            exit;

        IntegrationFieldMapping.CreateRecord(IntegrationTableMappingName, TableFieldNo, IntegrationTableFieldNo, SynchDirection,
          ConstValue, ValidateField, ValidateIntegrationTableField);
    end;
```

### Additional context

Useful for custom integration to use the same approach as is used for OOTB mappings, including existing events.
Internal work item: [AB#522697](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/522697)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18615.
