### ISSUE TITLE
Make "Shpfy Order Line Attribute" publicly available 

### ISSUE THREAD

**Issue by JeppeBylov** [microsoft/ALAppExtensions#26175]
### Describe the request

Remove "Access = Internal" from Shpfy Order Line Attribute
![image](https://github.com/microsoft/ALAppExtensions/assets/968411/ebf93c57-329a-4ee4-8727-943ded969ec0)

### Additional context

**General observation**
In general, i believe that attributes will become/if not already is a great pattern to do customized logic in the integration between BC and Shopify. Therefore, i believe that similarly to "Shpfy Order Attribute" then "Shpfy Order Line Attribute" should also become available to use.

**Current Scenario**
We have a client that is selling items in bundle packages. All the bundling is handled in Shopify, which means that in BC the order must just consist of the individual items within the bundle.
The "bundle" parent item along with the individual items within are all sent as order lines. And information about which line is the parent and which are items to be sold is shared as attributes.

I need the attributes to develop the processing logic needed to handle pricing, overwriting values etc. before the sales order is ready to be processed.

<img width="866" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/968411/c0cc4dfe-44be-445f-a192-52bbd36ec1e9">

Internal work item: [AB#522636](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/522636)

**Comment by JesperSchulz** [comment]
Your issue has been approved. We'll prepare a PR ourselves. I'm hence closing this issue 🙂

**Comment by JesperSchulz** [comment]
24.1 i very likely 🙂

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 17909.
