### ISSUE TITLE
[Request for External] RecreateJobQueueEntry(...) in 5334 "CRM Setup Defaults"

### ISSUE THREAD

**Issue by TKapitan** [microsoft/ALAppExtensions#26172]
### Describe the request

Please make this procedure public so it can be reused by custom integration incl. the existing event.

Codeunit 5334 "CRM Setup Defaults"

```
    local procedure RecreateJobQueueEntry(EnqueueJobQueEntry: Boolean; CodeunitId: Integer; MinutesBetweenRun: Integer; EntryDescription: Text; StatusReady: Boolean)
    var
        JobQueueEntry: Record "Job Queue Entry";
    begin
        with JobQueueEntry do begin
            SetRange("Object Type to Run", "Object Type to Run"::Codeunit);
            SetRange("Object ID to Run", CodeunitId);
            DeleteTasks();

            InitRecurringJob(MinutesBetweenRun);
            "Object Type to Run" := "Object Type to Run"::Codeunit;
            "Object ID to Run" := CodeunitId;
            Description := CopyStr(EntryDescription, 1, MaxStrLen(Description));
            "Maximum No. of Attempts to Run" := 2;
            if StatusReady then
                Status := Status::Ready
            else begin
                Status := Status::"On Hold with Inactivity Timeout";
                "Inactivity Timeout Period" := MinutesBetweenRun;
            end;
            "Rerun Delay (sec.)" := 30;
            if EnqueueJobQueEntry then
                CODEUNIT.Run(CODEUNIT::"Job Queue - Enqueue", JobQueueEntry)
            else
                Insert(true);
        end;
    end;
```

### Additional context

Useful for custom integration jobs that should follow the same design as standard integration jobs. An example of custom integration job is synchronization of the available credit or for custom document types.
Internal work item: [AB#522696](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/522696)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18615.
