### ISSUE TITLE
[Extensibility Request] Field "Item Tracking on Lines" (6500) - Table "Item Journal Batch" (233)

### ISSUE THREAD

**Issue by Mariangela-DeMaio-EOS** [microsoft/ALAppExtensions#26177]
### Describe the request

Hi,
In Business Central 22 Microsoft introduced the flag "Item Tracking on Lines" (6500) in the table "Item Journal Batch" (233) to enable the possibility to set the tracking on the lines of the journal.

From Business Central 23.3 we can't enable it for the page "Phys. Inventory Journal" (392), because it returns this error 
_"Type must be equal to 'Item'  in Item Journal Template: Name=INV. FIS.. Current value is 'Phys. Inventory'."_

AL call stack: 
"Item Journal Batch"(Table 233)."Item Tracking on Lines - OnValidate"(Trigger) line 3 - Base Application by Microsoft

![Item Track on lines](https://github.com/microsoft/ALAppExtensions/assets/92147701/5415db9f-6c26-4450-8ce2-a1a6fa7cc8b2)

We would like to enable this feature for the Physical Inventory Journals.

Is there a reason to disable this flag for the Physical Inventory Journals?

### Additional context

This is business critical because we have an AppSource app and for our customers this feature is very useful and important to use the Physical Inventory.

**Comment by stkillen** [comment]
This looks like a design change. Only the following types of requests should be submitted in this repository:

- Add new integration events – Get the event you need to hook-in to a process.
- Change function visibility – For example, make a public function external or a similar change so you can call it from your extension and reuse the business logic.
- Replace Option with Enum – Replace a specific option with an enum that supports your extension. The new type enum is extensible, but all code was written for non-extensible options.
- Extensibility enhancements – Request changes in the application code that will improve extensibility.
