### ISSUE TITLE
[Event Change Request] codeunit 5815 Undo Sales Shipment Line - procedure Code - event OnAfterSalesShptLineModify

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26187]
### Describe the request

We would like HideDialog added to the following event.

Original:

```
codeunit 5815 - Undo Sales Shipment Line - procedure Code - event OnAfterSalesShptLineModify

OnAfterSalesShptLineModify(SalesShipmentLine, DocLineNo);

[IntegrationEvent(false, false)]
local procedure OnAfterSalesShptLineModify(var SalesShptLine: Record "Sales Shipment Line"; DocLineNo: Integer)
begin
end;

```

Change:

```
OnAfterSalesShptLineModify(SalesShipmentLine, DocLineNo, HideDialog); // <-- ADDED

[IntegrationEvent(false, false)]
local procedure OnAfterSalesShptLineModify(var SalesShptLine: Record "Sales Shipment Line"; DocLineNo: Integer; HideDialog: Boolean) // <-- ADDED
begin
end;

```

### Additional context

for our own additional functionality we need the user to choose further action if not HideDialog is active
Internal work item: [AB#523671](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523671)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18286.
