### ISSUE TITLE
[Bug]: Report 699 "Calculate Plan - Req. Wksh." ignores Price Calculation Method

### ISSUE THREAD

**Issue by chrischbo** [microsoft/ALAppExtensions#26180]
### Describe the issue

If you run the mentioned report it is possible to set a price calculation method. This method will be temporary set for the requisition line in "Inventory Profile Offsetting" (MaintainPlanningLine)
![image](https://github.com/microsoft/ALAppExtensions/assets/15926999/3ee3d23e-270f-4db5-8582-5c40f1235548)
with the shown "Validate("No.")" the system run multiple actions and end up on validating the replenishment system, see call stack below:
![image](https://github.com/microsoft/ALAppExtensions/assets/15926999/1db85121-2c95-4384-a446-378d2743540a)
This will lead to validating the "Vendor No." if the replenishment system is purchase and this causes the system to overwrite the set price calculation method from above with the vendors default setting
![image](https://github.com/microsoft/ALAppExtensions/assets/15926999/12e08a07-ad56-443a-9e59-3f0d47dab828)

### Expected behavior

Keep the price calculation method from the report

### Steps to reproduce

Needs a second price calc. method
Needs active new price calculation

Open "Requisition Worksheets"
Run "Calculate Plan"
Starting Date - 1/1/2025
Ending Date - 12/31/2025
Use Forecast - 2025
Price Calculation Method - new Method
Item No. - LS-120

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
That might just be a product defect! Unfortunately, this repository is only for extensibility requests for Dynamics 365 Business Central or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps). We suggest that you open a support case or file a bug to ensure that all Business Central users benefit from your catch as soon as possible:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
