### ISSUE TITLE
[Event Request] Two events in codeunit 5059 ProfileManagement

### ISSUE THREAD

**Issue by jhoek** [microsoft/ALAppExtensions#26184]
### Describe the request

Many thanks for considering the following suggested event publishers:

- Codeunit 5059 **ProfileManagement**, procedure **ShowContactQuestionnaireCard**: at the very start of the procedure, with an IsHandled flag (thus allowing us to bypass the existing functionality). 

- Codeunit 5059 **ProfileManagement**, procedure **FindLegalProfileQuestionnaire**: within the repeat...until loop, immediately after the repeat keyword, with **Cont** and **ProfileQuestnHeader** as parameters. Here, IsHandled is not needed for our purposes, but might accommodate other developers'. 

### Additional context

Needed in order to convert our BC14 customizations to AL event subscribers (as part of our SaaS migration).
Internal work item: [AB#522689](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/522689)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18286.
