### ISSUE TITLE
[Event Request] report 499 - Delete Invoiced Purch. Orders - dataitem "Purchase Header" - trigger OnAfterGetRecord - event OnAfterDeletePurchaseHeaderOnBeforeCommit

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26189]
### Describe the request

Please add the following Event/-s OnAfterDeletePurchaseHeaderOnBeforeCommit to dataitem "Purchase Header" in report 499 - Delete Invoiced Purch. Orders

```
[event request] report 499 - Delete Invoiced Purch. Orders - dataitem "Purchase Header" - trigger OnAfterGetRecord

...
...
    IsHandled := false;
    OnBeforeDeletePurchaseHeader("Purchase Header", IsHandled);
    if not IsHandled then
        Delete();
    OnAfterDeletePurchaseHeader("Purchase Header");

    IsHandled := false;  // <-- ADDED
    OnAfterDeletePurchaseHeaderOnBeforeCommit("Purchase Header", IsHandled); // <-- NEW EVENT
    if not IsHandled then  // <-- ADDED

        Commit();
end;

```

```
[IntegrationEvent(true, false)] // <- IncludeSender true
local procedure OnAfterDeletePurchaseHeaderOnBeforeCommit(var PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean) 
begin
end;
```

### Additional context

we need the commit to be conditional
Internal work item: [AB#523674](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523674)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18286.
