### ISSUE TITLE
[Request-For-External] Codeunit 5836 "Cost Calculation Management" - procedure from local to global

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26194]
### Describe the request

Hello, we need the following currently local procedure to be set to global. Can you please check this? Thank you!
```
CalcSalesLineShptAdjCostLCY(SalesLine: Record "Sales Line"; QtyType: Option General,Invoicing; var TotalAdjCostLCY: Decimal; var PostedQtyBase: Decimal; var RemQtyToCalcBase: Decimal)

```

```
procedure CalcSalesLineRcptAdjCostLCY(SalesLine: Record "Sales Line"; QtyType: Option General,Invoicing; var TotalAdjCostLCY: Decimal; var PostedQtyBase: Decimal; var RemQtyToCalcBase: Decimal)

```

### Additional context

Invoice Return Receipts in Invoices
Internal work item: [AB#523917](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523917)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18877.
