### ISSUE TITLE
[Event Change Request] Codeunit 80 Sales Post - procedure PostUpdateInvoiceLine - Event OnAfterPostUpdateInvoiceLine

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26198]
### Describe the request

We would like var SalesHeader added to the following event.

Original:

```
Codeunit 80 - Sales Post - procedure PostUpdateInvoiceLine - Event OnAfterPostUpdateInvoiceLine

OnAfterPostUpdateInvoiceLine(TempSalesLine);

[IntegrationEvent(TRUE, false)] 

    [IntegrationEvent(true, false)]
    local procedure OnAfterPostUpdateInvoiceLine(var TempSalesLine: Record "Sales Line" temporary)
    begin
    end;

```

Change:

```
OnAfterPostUpdateInvoiceLine(TempSalesLine,SalesHeader);

[IntegrationEvent(TRUE, false)] 

    [IntegrationEvent(true, false)]
    local procedure OnAfterPostUpdateInvoiceLine(var TempSalesLine: Record "Sales Line" temporary; var SalesHeader : Record "Sales Header")
    begin
    end;
```

### Additional context

Post Invoice with Return Receipts
Internal work item: [AB#523916](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523916)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18389.
