### ISSUE TITLE
[Event Change Request] Codeunit 90 Delete Invoiced Purch. Orders - event OnAfterPostUpdateInvoiceLine

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26196]
### Describe the request

We would like IncludeSender added to the following event.

Original:

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterPostUpdateInvoiceLine(var PurchaseLine: Record "Purchase Line" temporary)
    begin
    end;
```

Change:

```
    [IntegrationEvent(true, false)]
    local procedure OnAfterPostUpdateInvoiceLine(var PurchaseLine: Record "Purchase Line" temporary)
    begin
    end;
```

### Additional context

Similar to COD80 Sales-Post
Internal work item: [AB#523919](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523919)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18389.
