### ISSUE TITLE
[Event Change Request] Report 499 Delete Invoiced Purch. Orders - event OnAfterSetPurchLineFilters

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26190]
### Describe the request

We would like IncludeSender added to the following event.

Original:

```
[IntegrationEvent(false, false)]
local procedure OnAfterSetPurchLineFilters(var PurchaseLine: Record "Purchase Line")
begin
end;

```

Change:

```
[IntegrationEvent(true, false)]  // <-- IncludeSender true
local procedure OnAfterSetPurchLineFilters(var PurchaseLine: Record "Purchase Line")
begin
end;

```

### Additional context

to get variables from our reportextension the publisher has to be set to IncludeSender true
Internal work item: [AB#523675](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523675)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18286.
