### ISSUE TITLE
[Change Request] Codeunit 7312 "Create Pick" - OnBeforeCreateWhseDocument

### ISSUE THREAD

**Issue by ZsomborCsaszi** [microsoft/ALAppExtensions#26206]
### Describe the request

Dear ALAppExtensions Team,
We would like to ask for new parameters in OnBeforeCreateWhseDocument event. (Codeunit 7312 "Create Pick").
We would like to add IsMovementWorksheet, FirstWhseDocNo, LastWhseDocNo, CreatePickParameters variables to the event.

New Event
```
OnBeforeCreateWhseDocument(TempWarehouseActivityLine, CreatePickParameters."Whse. Document", IsHandled, 
     IsMovementWorksheet, FirstWhseDocNo, LastWhseDocNo, CreatePickParameters);
```
```
[IntegrationEvent(false, false)]
local procedure OnBeforeCreateWhseDocument(var TempWhseActivLine: Record "Warehouse Activity Line" temporary; WhseSource: Option "Pick Worksheet",Shipment,"Movement Worksheet","Internal Pick",Production,Assembly; var IsHandled: Boolean; IsMovementWorksheet: Boolean; var FirstWhseDocNo: Code[20]; var LastWhseDocNo: Code[20]; CreatePickParameters: Record "Create Pick Parameters")
begin
end;
```

### Additional context

We would like to modify the CreateWhseDocument procedure but cannot access these important variables that's why we've asked for these new parameters.
Internal work item: [AB#523880](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523880)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18389.
