### ISSUE TITLE
[Change Request] Page 5784 "Filters to Get Source Docs."

### ISSUE THREAD

**Issue by Ilke415** [microsoft/ALAppExtensions#26205]
### Describe the request

Hello, can you please move the WhseReceiptHeader variable to protected? 

### Additional context

```al
  var
        WhseReceiptHeader: Record "Warehouse Receipt Header";
        DataCaption: Text[250];
        ShowRequestForm: Boolean;

   protected var
        WhseShptHeader: Record "Warehouse Shipment Header";
        RequestType: Option Receive,Ship;
```
This variable is not currently available in pageextension. We need the access for this variable in order to set some custom filters in preprocessing.

Internal work item: [AB#523878](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523878)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18615.
