### ISSUE TITLE
[Bug]: Wrong translation

### ISSUE THREAD

**Issue by davidebarea** [microsoft/ALAppExtensions#26202]
### Describe the issue

Table 27, field 19,  value '2' of the linked enum: the italian translation of "No Relationship" is wrong.

### Expected behavior

In the table 27 (Item), field 19 (Price/Profit Calculation), the value '2' of the enum: the italian translation of "No Relationship" is wrong. At the moment it is translated in "Nr. relazione" but the correct translation in this case is "Nessuna relazione" (as it was on Nav 2017)

### Steps to reproduce

you can see the error everytime you have to use the field

### Additional context

![image](https://github.com/microsoft/ALAppExtensions/assets/165174782/4c09f2ce-ea8d-4d38-8328-eeeff9e98c9c)

you can see here the problem

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug
Internal work item: [AB#523941](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523941)

**Comment by JesperSchulz** [comment]
Bug logged. Closing issue. Thanks for reporting.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
