### ISSUE TITLE
Allow Alphanumeric characters in Bank Code field in Vendor Bank Account Card page.

### ISSUE THREAD

**Issue by SudinERP** [microsoft/ALAppExtensions#26217]
We were able to enter alphanumeric characters in the “Bank Code” field in “Vendor Bank Account Card” Page until Business Central (BC) version 22.5. After we updated version to 23.0+, the field no longer allows alphanumeric characters. It only allows numeric characters. See screenshots below from BC version 23.5.

The Microsoft Support engineer mentioned this change was implemented by Microsoft development team to fix bug ID 466409. Please refer to that bug ID.

This is a major issue for us because this field is utilized in customizations that require this field to have Alphanumeric characters. There is no quick way for us to re-design the customization. At this time, we can use workaround to use “Edit in Excel” function to update the Bank Code with “Alphanumeric” Characters, but we need to be able to enter Alphanumeric characters from “Vendor Bank Account card” page.

Please add feature to allow us to enter Alphanumeric characters in Bank Code. If the default setting has to be only “Numeric”, please give us Toggle button in Setup Page to turn off that restriction.

![image](https://github.com/microsoft/AL/assets/165412811/1d464f06-040c-4240-bcfe-7b0e8434f57b)
![image](https://github.com/microsoft/AL/assets/165412811/4217c9da-5d6c-4fae-998b-85f98734330c)

Thank you.

**Comment by JesperSchulz** [comment]
It would appear that you leveraged a bug in the compiler to your advantage. Now that the bug has been resolved and the "Numeric = true" is respected, that backdoor has been closed - leading to the problem explained here. I have asked our Finance team, if they see it as an option to reopen the field for alphanumerical characters. Waiting for a reply.

**Comment by JesperSchulz** [comment]
@SudinERP, I've tried to follow up on your case and we might be willing to change the Bank Code from from Numeric to Alphanumeric, given you can show where a bank is requiring Alphanumeric characters. Could you provide that detail for us?

**Comment by JesperSchulz** [comment]
FYI: I have routed this issue to the BC Escalation Engineer and he will manage it going forward. We'll look into possible fixes.

**Comment by SudinERP** [comment]
> @SudinERP, I've tried to follow up on your case and we might be willing to change the Bank Code from from Numeric to Alphanumeric, given you can show where a bank is requiring Alphanumeric characters. Could you provide that detail for us?

Thank you for you review. I don't have example of Bank that require Alphanumeric Character for "Bank Code". That "Bank Code" is used in customized EFT file, and it has been working fine for 3 years. Please allow to enter Alphanumeric Character in "Bank Code".

**Comment by JesperSchulz** [comment]
> > @SudinERP, I've tried to follow up on your case and we might be willing to change the Bank Code from from Numeric to Alphanumeric, given you can show where a bank is requiring Alphanumeric characters. Could you provide that detail for us?
> 
> Thank you for you review. I don't have example of Bank that require Alphanumeric Character for "Bank Code". That "Bank Code" is used in customized EFT file, and it has been working fine for 3 years. Please allow to enter Alphanumeric Character in "Bank Code".

It's been working fine due to bug in the product. But yes, we will look into possible solutions - as long as they are correct!

**Comment by JesperSchulz** [comment]
Closing as this issue is handled through a support case (as it should).
