### ISSUE TITLE
[Event Request] Codeunit 5813 "Undo Purchase Receipt Line" - OnCheckPurchRcptLineOnBeforeCollectItemLedgEntries 

### ISSUE THREAD

**Issue by dorinbirsan** [microsoft/ALAppExtensions#26218]
### Describe the request

Could you please add the following OnCheckPurchRcptLineOnBeforeCollectItemLedgEntries event to procedure CheckPurchRcptLine in Codeunit 5813 "Undo Purchase Receipt Line"? 
This event request is motivated by the fact that we need to extend only a piece of the code and not the whole function. This way we can keep what we extend to a minimum.

Current:

        with PurchRcptLine do begin
            if Correction then
                Error(AlreadyReversedErr);
            if "Qty. Rcd. Not Invoiced" <> Quantity then
                if HasInvoicedNotReturnedQuantity(PurchRcptLine) then
                    Error(Text004);
            if Type = Type::Item then begin
                TestField("Prod. Order No.", '');
                TestField("Sales Order No.", '');
                TestField("Sales Order Line No.", 0);

                UndoPostingMgt.TestPurchRcptLine(PurchRcptLine);
                UndoPostingMgt.CollectItemLedgEntries(TempItemLedgEntry, DATABASE::"Purch. Rcpt. Line",
                  "Document No.", "Line No.", "Quantity (Base)", "Item Rcpt. Entry No.");
                UndoPostingMgt.CheckItemLedgEntries(TempItemLedgEntry, "Line No.", "Qty. Rcd. Not Invoiced" <> Quantity);
            end;
        end;

Requested:

        with PurchRcptLine do begin
            if Correction then
                Error(AlreadyReversedErr);
            if "Qty. Rcd. Not Invoiced" <> Quantity then
                if HasInvoicedNotReturnedQuantity(PurchRcptLine) then
                    Error(Text004);
            if Type = Type::Item then begin
                TestField("Prod. Order No.", '');
                TestField("Sales Order No.", '');
                TestField("Sales Order Line No.", 0);

                UndoPostingMgt.TestPurchRcptLine(PurchRcptLine);
                IsHandled := false;
                OnCheckPurchRcptLineOnBeforeCollectItemLedgEntries(PurchRcptLine, TempItemLedgEntry, IsHandled);
                if not IsHandled then begin
                     UndoPostingMgt.CollectItemLedgEntries(TempItemLedgEntry, DATABASE::"Purch. Rcpt. Line",
                       "Document No.", "Line No.", "Quantity (Base)", "Item Rcpt. Entry No.");
                     UndoPostingMgt.CheckItemLedgEntries(TempItemLedgEntry, "Line No.", "Qty. Rcd. Not Invoiced" <> Quantity);                   
                end;
            end;
        end;
       
        ...
        [IntegrationEvent(false, false)]
        local procedure OnCheckPurchRcptLineOnBeforeCollectItemLedgEntries(var PurchRcptLine: Record "Purch. Rcpt. Line"; var TempItemLedgEntry: Record "Item Ledger Entry" temporary; var IsHandled: Boolean)
        begin
        end;

### Additional context

This event request is motivated by the fact that we need to extend only a piece of the code from Codeunit 5813 "Undo Purchase Receipt Line" and not the whole procedure (CheckPurchRcptLine ). This way we can keep what we extend to a minimum, and also better respect the development guidelines.
Internal work item: [AB#523886](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523886)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18389.
