### ISSUE TITLE
[Event Parameter Request] Table 5095 "Duplicate Search String Setup" - Need to add a new parameter DuplicateSearchStringSetup to OnBeforeLookupFieldName() event

### ISSUE THREAD

**Issue by Mahibabu1993** [microsoft/ALAppExtensions#26211]
### Describe the request

Hi Team,

We need a new parameter to be added to the event OnBeforeLookupFieldName(). We are using this event to adjust filters to the field lists that opens during this lookup. We also need to assign the value selected from the lookup to the record, so we need a new parameter for the record in this event.

`OnBeforeLookupFieldName(Rec, Field, IsHandled);`

    [IntegrationEvent(false, false)]
    local procedure OnBeforeLookupFieldName(var DuplicateSearchStringSetup: Record "Duplicate Search String Setup"; var Field: Record "Field"; var IsHandled: Boolean)
    begin
    end;

### Additional context

We want to display also the fields of type Date on the lookup for which we use event OnBeforeLookupFieldName() to adjust the filters and open field list and we set IsHandled to true. When the user selects a field from the lookup, we need to assign that field no. to the Field No. field of that record.
Internal work item: [AB#523883](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523883)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18872.
