### ISSUE TITLE
[Event Request] Table 7001 "Price List Line" - OnBeforeCopyFilteredLinesToTemporaryBuffer

### ISSUE THREAD

**Issue by AnastasiiaBarvinok** [microsoft/ALAppExtensions#26226]
### Describe the request

Hi, would it be possible to get the OnBeforeCopyFilteredLinesToTemporaryBuffer event in table 7001 (Price List Line), like this:

```
    procedure CopyFilteredLinesToTemporaryBuffer(var TempPriceListLine: Record "Price List Line" temporary) Copied: Boolean;
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCopyFilteredLinesToTemporaryBuffer(Rec, TempPriceListLine, Copied, IsHandled);
        if IsHandled then
            exit;

        if FindSet() then
            repeat
                TempPriceListLine := Rec;
                OnCopyFilteredLinesToTemporaryBufferOnBeforeInsert(TempPriceListLine);
                if TempPriceListLine.Insert() then
                    Copied := true;
            until Next() = 0;

        OnAfterCopyFilteredLinesToTemporaryBuffer(TempPriceListLine);
    end;
```
```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeCopyFilteredLinesToTemporaryBuffer(var TempPriceListLine: Record "Price List Line" temporary; var Copied: Boolean; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

Customization requires to implement calculation depending of Sales Setup
Internal work item: [AB#523892](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523892)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18389.
