### ISSUE TITLE
[Event Request] Table 472 "Job Queue Entry" - procedure HandleExecutionError()

### ISSUE THREAD

**Issue by jlorenc01** [microsoft/ALAppExtensions#26228]
### Describe the request

Hello,

I would like to ask for new publisher in the table 472 "Job Queue Entry", procedure HandleExecutionError(). Thank you.
```
local procedure HandleExecutionError()
var
    ...
begin
    IsHandled := false;
    ...
    
    OnAfterHandleExecutionError(Rec); // NEW EVENT
end;
    

// NEW EVENT
[IntegrationEvent(false, false)]
local procedure OnAfterHandleExecutionError(var JobQueueEntry: Record "Job Queue Entry")
begin
end;
```

### Additional context

We need to update our data after this procedure is executed.
Internal work item: [AB#524053](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524053)

**Comment by haoranpb** [comment]
Hi @jlorenc01 

Thanks for opening an event request.

After reviewing the proposed event and provided context, I assume the event `OnAfterFinalizeRun` might be what you are looking for? You can find it at the bottom of the `FinalizeRun` procedure inside `JobQueueEntry.Table.al`. You will need to do a if statement on the `Status` field.

I will close this issue for now, if you have follow-up questions or requests, we do not monitor closed issues, so please create a new issue where you reference this one.
