### ISSUE TITLE
Record "Page Info and Fields" is OnPrem

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/ALAppExtensions#26224]
### Describe the request

Record "Page Info and Fields" is locked for OnPrem development. Why is this, could it be opened for Saas?

### Additional context

We would need access to the (currently active) page's tooltips in code, and I see no other way to get to them.
Internal work item: [AB#523921](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/523921)

**Comment by navdotnetreqs** [comment]
"Page Table Field" would work as well, probably

**Comment by JesperSchulz** [comment]
Those are platform tables. I will forward your request to our platform team.

**Comment by jehelles** [comment]
Duplicate #25332
