### ISSUE TITLE
[Enum Request] Field Schedule in table 6751 "Reminder Action Group"

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#26234]
### Describe the request

Could you please change this Option in `table 6751 "Reminder Action Group"` to an extensible enum?
```al
        field(3; Schedule; Option)
        {
            OptionMembers = Manual,"Weekly","Monthly","Custom schedule";
        }
```
Please also add events on places where the Option is used or alternatively provide a good interface that we can implement.

e.g. 
```al
interface "Reminder Action Schedule"
{
  procedure GetNextRunDate(): DateTime
  procedure IsManual(): Boolean
}
```

### Additional context

We would like to implement our own logic for the next schedule calculation.

Internal work item: [AB#524156](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524156)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18482.
