### ISSUE TITLE
[Event Request] Table 179 "Reversal Entry" - procedure Caption()

### ISSUE THREAD

**Issue by Roberto-Lucarelli-EOS** [microsoft/ALAppExtensions#26230]
### Describe the request

I would need a new event in function Caption of table 179 Reversal Entry.
The event should be placed at the beginning of the function (for example onBeforeCaption) and as parameters it should have the Rec (Reversal Entry), the IsHandled variable and a return parameter that contains the new Caption.
Exited from the event, if IsHandled = true it must exit the function by placing the new caption in the exit

for example :
onBeforeCaption(Rec, NewCaption, IsHandled)
if IsHandled then
  exit(NewCaption)

thank you

### Additional context

For one of our apps we need to modify the caption that is displayed on page 183 Reverse Transaction Entries
Internal work item: [AB#524158](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524158)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21326.
