### ISSUE TITLE
Missing complete definition of the field relations in the standard table Table Relations Metadata

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/ALAppExtensions#26235]
### Describe the request

As reported five years ago at https://github.com/microsoft/AL/issues/5512

We need access to the real and full table relations in AL Code. As far as I can tell, this is not currently possible, since Table Relations Metadata is incomplete and does not include information about relationship filters. Eg. I find that Customer.Ship-to Address is related to the Ship-to Address table, but not the fact that the customer no. field must be linked for the relationship to be valid.

### Additional context

For any sort of generic and abstract code, instead of copy-paste, it's imperative to be able to iterate records, tables and fields with complete information.

**Comment by AndersLarsenMicrosoft** [comment]
This is not an event request. please use bcidea
