### ISSUE TITLE
[Event Change Request] Reports 10401 "Check (Stub/Stub/Check)" - OnAfterOnAfterGetRecordOfGenJnlLine && Report 10411 "Check (Stub/Check/Stub)" - OnAfterOnAfterGetRecordOfGenJnlLine

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/ALAppExtensions#26239]
### Describe the request

We would like var OneCheckPrVendor added to the following event.

for the Reports 10401 "Check (Stub/Stub/Check)" - OnAfterOnAfterGetRecordOfGenJnlLine && Report 10411 "Check (Stub/Check/Stub)" - OnAfterOnAfterGetRecordOfGenJnlLine

Original :

    [IntegrationEvent(false, false)]
    local procedure OnAfterOnAfterGetRecordOfGenJnlLine(GenJournalLine: Record "Gen. Journal Line"; var RemitAddress: Record "Remit Address"; var CheckToAddr: array[8] of Text[100]; BalancingType: Enum "Gen. Journal Account Type"; ApplyMethod: Option)
    begin
    end;

Change : 

    [IntegrationEvent(false, false)]
    local procedure OnAfterOnAfterGetRecordOfGenJnlLine(GenJournalLine: Record "Gen. Journal Line"; var RemitAddress: Record "Remit Address"; var CheckToAddr: array[8] of Text[100]; BalancingType: Enum "Gen. Journal Account Type"; ApplyMethod: Option; var OneCheckPrVendor )
    begin
    end;

### Additional context

Event change request
Internal work item: [AB#524444](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524444)

**Comment by dcenic** [comment]
Added, will be available in the next minor release of Business Central 24

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18782.
