### ISSUE TITLE
[Bug]: CheckDimensions function from Codeunit 11 crashes on conditional codeunit or TryFunction

### ISSUE THREAD

**Issue by fgilsc** [microsoft/ALAppExtensions#26231]
### Describe the issue

Hi,

I'm migrating a process that auto posts Journal Lines for Job Queue Entry. I use the codeunit "Gen. Jnl.-Post", calling it with a conditional statement:

 if GenJnlPost.Run(GenJnlLine) then [...]

I see the process crashes on function CheckDimensions  from codeunit 11 "Gen. Jnl.-Check Line" althougt I use a conditional statement or handling it with a TryFunction. This should not happen.

This was working perfectly on BC14. 
I use Business Central 23.1 (Platform 23.0.13804.0 + Application 23.1.13431.13812)

### Expected behavior

Running codeunit "Gen. Jnl.-Post" with conditional statements should not crash in case of error.

### Steps to reproduce

Running codeunit "Gen. Jnl.-Post" with conditional statements

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug

**Comment by pri-kise** [comment]
You should better create a support request to get this addressed.
Make sure that you can reproduce the issue on the latest available version (currently BC24.0)

**Comment by AndersLarsenMicrosoft** [comment]
Please create a support request, this is not an event request
