### ISSUE TITLE
[Event Parameter Request] Codeunit 80 "Sales-Post" - Need to add a parameter PreviewMode to OnRunOnBeforeFinalizePosting() event

### ISSUE THREAD

**Issue by Arlem999** [microsoft/ALAppExtensions#26237]
### Describe the request

Hi Team,

We need  to add a parameter PreviewMode to OnRunOnBeforeFinalizePosting() event in Codeunit 80 "Sales-Post". 

### Additional context

We use this Event to handle additional clients logic, and we need a PreviewMode parameter in this Event.
Internal work item: [AB#524443](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524443)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18666.
