### ISSUE TITLE
[Event Request] Codeunit 7009 CopyFromToPriceListLine - OnBeforeInsertPriceListLine

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#26233]
### Describe the request

Dear ALAppExtensions team,

On behalf of 4PS I would like to request integration event 'OnBeforeInsertPriceListLine' to be added to procedure InsertPriceListLine in codeunit 7009 CopyFromToPriceListLine.

````
    local procedure InsertPriceListLine(var PriceListLine: Record "Price List Line")
    begin
        InitLineNo(PriceListLine);
        OnBeforeInsertPriceListLine(PriceListLine); //new
        PriceListLine.Insert(true);
    end;
````
````
    [IntegrationEvent(false, false)]
    local procedure OnBeforeInsertPriceListLine(var PriceListLine: Record "Price List Line")
    begin
        //new
    end;
````

### Additional context

We have functionality to make it possible to have the same Price List Lines in several companies. Therefore we have added some code to the OnInsert of Price List Line that takes care of inserting the Price List Line in other companies.

But when the procedure InsertPriceListLine of codeunit 7009 CopyFromToPriceListLine is called, inserting the Price List Line should not be done in other companies. Therefore we need an event on this place, to make sure that inserting in other companies is skipped. Unfortunately we cannot use the event OnAfterInitLineNo, because this event is also called in situations where it is necessary to insert the Price List Line in other companies.

When inserting the Price List Header, we have the same issue, but there is already an event OnBeforeInsertHeader.
Internal work item: [AB#524157](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524157)

**Comment by JesperSchulz** [comment]
Work completed on the 11-04-2024.
