### ISSUE TITLE
[Enum Request]: table 5841 "Standard Cost Worksheet" field(3; Type; Option)

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#26245]
### Describe the request

table 5841 "Standard Cost Worksheet"
field(3; Type; Option)
OptionMembers = Item,"Work Center","Machine Center",Resource;

Could you make this an enum?

### Additional context

An Enum says it all why. We like to reuse it to enhance the "Standard Cost Worksheet" functionality. StockKeepingUnit "Standard Cost" are not handled as well as it should.
Internal work item: [AB#524417](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524417)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18482.
