### ISSUE TITLE
[Event Request] page 474 "VAT Statement Preview" - OnBeforeUpdateSubForm

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#26244]
### Describe the request

Hello, can you please add a new Event OnBeforeUpdateSubForm in page 474 "VAT Statement Preview" ?

```
    procedure UpdateSubForm()
    begin
        OnBeforeUpdateSubForm(Rec);
        CurrPage.VATStatementLineSubForm.PAGE.UpdateForm(Rec, Selection, PeriodSelection, UseAmtsInAddCurr);
    end;
```

```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeUpdateSubForm(var VATStatementName: Record "VAT Statement Name")
    begin
    end;
```

### Additional context

Allow modification of the page record before it is being processed in the subform.
Internal work item: [AB#524416](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524416)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21326.
