### ISSUE TITLE
[Event Change Request] Report 10412 - Check (Check/Stub/Stub) - OnAfterOnAfterGetRecordOfGenJnlLine

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/ALAppExtensions#26241]
### Describe the request

We would like var OneCheckPrVendor added to the following event.

for the Report 10412 - Check (Check/Stub/Stub) - OnAfterOnAfterGetRecordOfGenJnlLine

Original : 

    [IntegrationEvent(false, false)]
    local procedure OnAfterOnAfterGetRecordOfGenJnlLine(var GenJournalLine: Record "Gen. Journal Line"; var RemitAddress: Record "Remit Address"; var CheckToAddr: array[8] of Text[100]; BalancingType: Enum "Gen. Journal Account Type"; ApplyMethod: Option Payment,OneLineOneEntry,OneLineID,MoreLinesOneEntry)
    begin
    end;

change :

    [IntegrationEvent(false, false)]
    local procedure OnAfterOnAfterGetRecordOfGenJnlLine(var GenJournalLine: Record "Gen. Journal Line"; var RemitAddress: Record "Remit Address"; var CheckToAddr: array[8] of Text[100]; BalancingType: Enum "Gen. Journal Account Type"; ApplyMethod: Option Payment,OneLineOneEntry,OneLineID,MoreLinesOneEntry; var OneCheckPrVendor)
    begin
    end;

### Additional context

Event Change Request
Internal work item: [AB#524420](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524420)

**Comment by dcenic** [comment]
Added, will be available in the next minor release of Business Central 24

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 18783.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18782.
