### ISSUE TITLE
[Protected Var] Report 99001017 "Calculate Plan - Plan. Wksh."

### ISSUE THREAD

**Issue by cc-chku** [microsoft/ALAppExtensions#26242]
### Describe the request

Can you please set the following variables to protected (Report 99001017 "Calculate Plan - Plan. Wksh.")?
In the according "sibling" report (699 "Calculate Plan - Req. Wksh.") the variables are protected.

CurrTemplateName: Code[10];
CurrWorksheetName: Code[10];
NetChange: Boolean;
MPS: Boolean;
MRP: Boolean;
NoPlanningResiliency: Boolean;
FromDate: Date;
ToDate: Date;
ExcludeForecastBefore: Date;
UseForecast: Code[10];
RespectPlanningParm: Boolean;

### Additional context

I need the values from this variables and work with them
Internal work item: [AB#524419](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524419)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18615.
