### ISSUE TITLE
[Event Change Request] Report 10412 - Check (Check/Stub/Stub) - OnAfterGetRecordOfPrintSettledLoop

### ISSUE THREAD

**Issue by tejabalusu** [microsoft/ALAppExtensions#26240]
### Describe the request

We would like var OneCheckPrVendor added to the following event.

for the  Report 10412 - Check (Check/Stub/Stub) - OnAfterGetRecordOfPrintSettledLoop

Original :

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetRecordOfPrintSettledLoop(GenJournalLine2: Record "Gen. Journal Line"; var TotalLineAmount: Decimal; var CurrentLineAmount: Decimal; var TotalLineDiscount: Decimal; var LineDiscount: Decimal; BalancingType: Enum "Gen. Journal Account Type"; ApplyMethod: Option)
    begin
    end;

change : 

    [IntegrationEvent(false, false)]
    local procedure OnAfterGetRecordOfPrintSettledLoop(GenJournalLine2: Record "Gen. Journal Line"; var TotalLineAmount: Decimal; var CurrentLineAmount: Decimal; var TotalLineDiscount: Decimal; var LineDiscount: Decimal; BalancingType: Enum "Gen. Journal Account Type"; ApplyMethod: Option; var OneCheckPrVendor)
    begin
    end;

### Additional context

Event Change request
Internal work item: [AB#524433](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524433)

**Comment by dcenic** [comment]
Added, will be available in the next minor release of Business Central 24

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18782.
