### ISSUE TITLE
[Event Request] table 1003 "Job Planning Line" - CopyFromResource

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#26252]
### Describe the request

Could you please add the following event?

```al
local procedure CopyFromResource()
var
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeCopyFromResource(Rec, xRec, IsHandled);
    if IsHandled then
        exit;

    Res.Get("No.");
    Res.CheckResourcePrivacyBlocked(false);
    Res.TestField(Blocked, false);
    Res.TestField("Gen. Prod. Posting Group");
    if Description = '' then
        Description := Res.Name;
    if "Description 2" = '' then
        "Description 2" := Res."Name 2";
    "Gen. Prod. Posting Group" := Res."Gen. Prod. Posting Group";
    "Resource Group No." := Res."Resource Group No.";
    Validate("Unit of Measure Code", Res."Base Unit of Measure");
    //+EVENT
    OnAfterCopyCopyFromResource(Rec, Job, Res);
    //-EVENT
end;
```

```al
[IntegrationEvent(false, false)]
local procedure OnAfterCopyCopyFromResource(var JobPlanningLine: Record "Job Planning Line"; Job: Record Job; Resource: Record Resource;)
begin
end;
```

### Additional context

We would like to transfer custom fields similiar to the Event `OnAfterCopyFromItem` or `OnAfterCopyFromGLAccount`. 
Internal work item: [AB#524720](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524720)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18489.
