### ISSUE TITLE
[Event Change Request] table 77 "Report Selections" Event OnGetEmailBodyVendorTextOnAfterNotFindEmailBodyUsage

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26253]
### Describe the request

In #25386, a parameter EmailBodyUsageFound has been added to OnGetEmailBodyCustomerTextOnAfterNotFindEmailBodyUsage . Same requirement is needed for OnGetEmailBodyVendorTextOnAfterNotFindEmailBodyUsage as well ...

**Reference code for OnGetEmailBodyCustomerTextOnAfterNotFindEmailBodyUsage (as solved by #25386)**

```
if not FindEmailBodyUsageForCust(ReportUsage, CustNo, TempBodyReportSelections) then begin
            IsHandled := false;
            EmailBodyUsageFound := false;
            OnGetEmailBodyCustomerTextOnAfterNotFindEmailBodyUsage(
                ReportUsage.AsInteger(), RecordVariant, CustNo, TempBodyReportSelections, IsHandled, EmailBodyUsageFound);
            if not EmailBodyUsageFound then begin
                if IsHandled then
                    exit(true);
                exit(false);
            end;
        end;
```

**Current code for OnGetEmailBodyVendorTextOnAfterNotFindEmailBodyUsage (as-is)** 

```
if not FindEmailBodyUsageForVend(ReportUsage, VendorNo, TempBodyReportSelections) then begin
            IsHandled := false;
            OnGetEmailBodyVendorTextOnAfterNotFindEmailBodyUsage(
              ReportUsage.AsInteger(), RecordVariant, VendorNo, TempBodyReportSelections, IsHandled);
            if IsHandled then
                exit(true);
            exit(false);
        end;
```

**Required code for OnGetEmailBodyVendorTextOnAfterNotFindEmailBodyUsage (to-be)** 

```
if not FindEmailBodyUsageForVend(ReportUsage, VendorNo, TempBodyReportSelections) then begin
            IsHandled := false;
            EmailBodyUsageFound := false; // ADD
            OnGetEmailBodyVendorTextOnAfterNotFindEmailBodyUsage(
              ReportUsage.AsInteger(), RecordVariant, VendorNo, TempBodyReportSelections, IsHandled, EmailBodyUsageFound); // ADD EmailBodyUsageFound
            if not EmailBodyUsageFound then begin // ADD
                if IsHandled then
                    exit(true);
                exit(false);
            end;
        end;
```

PS: Would be great if event publishers we're updated, to review 'similar' event publishers as well (we often see changes for sales / customers events, which are not ported to purchase / vendor)

### Additional context

The reason for this is I want to use my own logic to populate the TempBodyReportSelections with the "Report ID" and the "Email Body Layout Code" of the report/layout I want to use for the email body.

The TempBodyReportSelections is already a var parameter, but it can't be used at the moment because the code always exits and so the code further down that uses the TempBodyReportSelections never gets called
Internal work item: [AB#524723](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524723)

**Comment by Groenbech96** [comment]
Created PR in BaseApp. Change will go into 25.1

**Comment by Groenbech96** [comment]
Build version 24613

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24617.
