### ISSUE TITLE
[Event Request] Codeunit 13 "Gen. Jnl.-Post Batch" - OnBeforeCheckPmtApplnAllowed

### ISSUE THREAD

**Issue by sklingele** [microsoft/ALAppExtensions#26268]
### Describe the request

Hello,

can you please add a new Event OnBeforeCheckPmtApplnAllowed in  Codeunit 13 "Gen. Jnl.-Post Batch"?

Event in existing procedure:
```
local procedure CheckPmtApplnAllowed(var PaymentApplication: Boolean; var PaymentBalanceVAT: Boolean; GenJournalLine: Record "Gen. Journal Line")
var
      IsHandled: Boolean;
begin
      IsHandled := false;
      OnBeforeCheckPmtApplnAllowed(PaymentApplication,PaymentBalanceVAT,GenJournalLine, IsHandled);
      if IsHandled then
          exit;

      with GenJournalLine do
          if PaymentApplication and PaymentBalanceVAT then begin
              PaymentApplication := false;
              PaymentBalanceVAT := false;
              Error(PmtApplnErr, "Journal Template Name", "Journal Batch Name", "Line No.");
          end;
end;
```
new Event:

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckPmtApplnAllowed((var PaymentApplication: Boolean; var PaymentBalanceVAT: Boolean; GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
begin
end;
```

### Additional context

Allows to decide whether the CheckPmtApplAllowed should be processed or not
Internal work item: [AB#524731](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524731)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21087.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 21100.
