### ISSUE TITLE
Codeunit 31362 "Match Bank Payment CZB" - procedure FillMatchBankPaymentBufferVendor() - BC version 23

### ISSUE THREAD

**Issue by helmealex** [microsoft/ALAppExtensions#26264]
### Describe the request

I would like to request the same publisher described in issue #25710 but for the version 23 of BC.

### Additional context

We have the same scenario, but for Business Central Version 23.

**Comment by mynjj** [comment]
Hi,

Unfortunately the process for event requests is only for the next minor, backporting this to 23 versions would require hotfixing the already released 24.0 to avoid breaking the dependent extension. We do not usually hotfix events unless they are causing a livesite issue.

I'll close this issue as "Won't fix".

FYI: @JesperSchulz
