### ISSUE TITLE
[Bug]: [SHOPIFY] Missing Payment Transaction Type

### ISSUE THREAD

**Issue by daniloziva** [microsoft/ALAppExtensions#26261]
### Describe the issue

Shopify Payment Transaction Table sets blank value for "Type" field for Shop Cash Credit transaction in BC Shopify Payout.

![image](https://github.com/microsoft/ALAppExtensions/assets/123086474/2bf1af90-be69-4ce4-92ab-67b2245192d5)

![image](https://github.com/microsoft/ALAppExtensions/assets/123086474/d10a23b4-98a7-4928-950f-de941c24e4e4)

### Expected behavior

Add a new "Shpfy Payment Trans. Type" enum value, or map the value to a current Type.

### Steps to reproduce

Synchronize a Shopify Payout that has at least one transaction line with type "Shop Cash Credit"

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
@onbuyuka, please triage.

**Comment by JesperSchulz** [comment]
This was fixed by the product group, to be released with 24.1!
