### ISSUE TITLE
[Enum Request]: Page 50 "Purchase Order" - ShipToOptions

### ISSUE THREAD

**Issue by developerchristiaens** [microsoft/ALAppExtensions#26267]
### Describe the request

Page 50 Purchase Order

ShipToOptions: Option "Default (Company Address)",Location,"Customer Address","Custom Address";

Could u make this an enum? Like u did on Sales Order.

### Additional context

With an Enum we can extend this the same way we could on Sales Order.
Internal work item: [AB#524727](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524727)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20110.
