### ISSUE TITLE
[Event Request] - Table Job Planning Line - Function UpdateQtyToTransfer

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#26270]
### Describe the request

```
procedure UpdateQtyToTransfer()
var 
IsHandled:Boolean;    
begin
     //NewEvent
        OnBeforeUpdateQtyToTransfer(Rec, CurrFieldNo,IsHandled);
        if IsHandled then
           exit;
        //NewEvent
        if "Contract Line" then begin
            CalcFields("Qty. Transferred to Invoice");
            Validate("Qty. to Transfer to Invoice", Quantity - "Qty. Transferred to Invoice");
        end else
            Validate("Qty. to Transfer to Invoice", 0);
    end;

[IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateQtyToTransfer(var JobPlanningLine: Record "Job Planning Line"; CurrFieldNo: Integer;var IsHandled:Boolean)
    begin
    end;
```

### Additional context

Could this event be added? Need it to override qty. to transfer to Invoice field.
Internal work item: [AB#524725](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524725)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18489.
