### ISSUE TITLE
[Event Request] Add new event to apply filters on Approval Entry Record that sets controller appearance on different windows as expected with business central approach.

### ISSUE THREAD

**Issue by arvindbinarystream** [microsoft/ALAppExtensions#26275]
### Describe the request

**1. codeunit 1535 "Approvals Mgmt."**

![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/885aaf63-8a21-4770-a200-519f36b61945)

- Event signature will be:
- [IntegrationEvent(false, false)]
- local procedure OnHasApprovalEntriesSentByCurrentUserOnAfterSetApprovalEntryFilters(var ApprovalEntry: Record "Approval Entry"; TableNo: Integer)
- begin
- end;

![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/e2d13815-4b59-4f5b-89bc-3565b32763a3)

- Event signature will be:
- [IntegrationEvent(false,false)]
- local procedure OnFindApprovalEntryByRecordIdOnAfterSetApprovalEntryFilters(var ApprovalEntry: Record "Approval Entry")
- begin
- end;

![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/fa925a79-b171-4801-90cd-2a2162c600cc)

- Event signature will be:
- [InternalEvent(false, false)]
- local procedure OnGetApprovalStatusFromApprovalEntryOnAfterSetRestrictedRecordFilter(var RestrictedRecord: Record "Restricted Record");
- begin
- end;
- 
- [InternalEvent(false, false)]
- local procedure OnGetApprovalStatusFromApprovalEntryOnAfterSetGenJournalLineFilter(var GenJournalLine: Record "Gen. Journal Line");
- begin
- end;

![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/62341b6d-aa3a-4107-88dd-ab976a317699)

- [IntegrationEvent(false, false)]
- local OnHasOpenOrPendingApprovalEntriesOnAfterSetApprovalEntryFilters(var ApprovalEntry: Record "Approval Entry", TableNo: Integer);
- begin
- end;
- 
- [IntegrationEvent(false, false)]
- local OnHasOpenOrPendingApprovalEntriesForCurrentUserOnAfterSetApprovalEntryFilters(var ApprovalEntry: Record "Approval Entry", TableNo: Integer);
- begin
- end;
- 
- [IntegrationEvent(false, false)]
- local OnHasApprovedApprovalEntriesOnAfterSetApprovalEntryFilters(var ApprovalEntry: Record "Approval Entry", TableNo: Integer);
- begin
- end;

_Also, there are a few integration events that needs to be added with additional arguments.
**Existing Integration events that are available**:_
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/3d419046-0834-4d97-930d-4d62be908adc)
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/b3b8ed98-4470-4e1f-bf48-e77b89008c60)

_**Expected Integration events :**_
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/4a2ea150-408a-49df-9a54-1d65df0869ad)
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/ae81dec4-7f4a-4c3e-91d2-8dac5c76eba6)

**2. codeunit 1550 "Record Restriction Mgt."**

![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/5e9e17c4-0595-47d2-98ad-c67d86512f6c)

- Event signature will be:
- [InternalEvent(false,false)]
- local procedure OnAllowGenJournalBatchUsageOnAfterSetGenJournalLineFilter(var GenJournalLine:Record "Gen. Journal Line");
- begin
- end;

![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/c98558d6-ff8c-45ab-b917-8edffbecb294)

- Event signature will be:
- [InternalEvent(false, false)]
- local procedure OnCheckGenJournalBatchHasUsageRestrictionsOnAfterSetGenJournalLineFilter(var GenJournalLine: Record "Gen. Journal Line");
- begin
- end;

**3. page 1528 "Workflow Status FactBox"**

![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/41a54d04-8c66-43c9-a00f-461e792e5203)

3) **page 1528 "Workflow Status FactBox"**
 
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/fcd23045-9f99-4fa6-917a-6b00d8eac8c2)

- Event signature will be:
- [IntegrationEvent(false, false)]
- local procedure SetFilterOnWorkflowRecordOnAfterSetWorkflowStepInstanceFilters(var WorkflowStepInstance: Record "Workflow Step Instance";WorkflowStepRecID: RecordID)
- begin
- end;

### Additional context

With our product, we introduced a new feature that allows users to send approvals based on General Journal Batch which is differentiated based on additional fields from our product.

To make sure our feature is aligned with business central functionality we need some events

[Event Request.docx](https://github.com/microsoft/ALAppExtensions/files/15003846/Event.Request.docx)

Internal work item: [AB#524796](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524796)

**Comment by haoranpb** [comment]
Hi @arvindbinarystream 

Thanks for opening an event request.

After reviewing the proposed events and provided context, my understanding is that your solution has some customized fields on `Approval Entry` table, and you would like to tweak the appearance of some standard Business Central pages basing on that?

Given the number of events requested, can you elaborate bit more on your scenario? Would it make sense to use page extensions? Or maybe an event on the page itself (so that you can modify the variables that control the appearance directly)?

I will close this issue for now, if you have follow-up questions or requests, we do not monitor closed issues, so please create a new issue where you reference this one.
