### ISSUE TITLE
[BC Idea]: table 6214 "Sustainability Jnl. Line" - Extensibility for Default Dimensions

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#26273]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=0471c555-fdf7-ee11-a73c-0022484ddea9

### Description

Currently there is no useful integration event for `table 6214 "Sustainability Jnl. Line"`.

I'd like to add similiar events and procedure as there are for `table 81 "Gen. Journal Line"`

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea
Internal work item: [AB#525140](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/525140)

**Comment by JesperSchulz** [comment]
@altotovi, please triage.

**Comment by altotovi** [comment]
I'm OK with this one.
