### ISSUE TITLE
Allow FieldRef.Validate to generate Collectible errors

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/ALAppExtensions#26277]
### Describe the request

FieldRef.Validate("Field", "Value", ErrorInfo)
and
FieldRef.Validate("Field", ErrorInfo)

as exists for TestField and Error.

### Additional context

As far as I can tell, there is no way to call Field(Ref).Validate so that potential errors would be caught and handled instead of stopping the process. This is illogical and in stark contrast with TestField() that does take ErrorInfo as a parameter and thus allows Collectible errors.

And before anyone says "use a TryFunction", that does not work for anything even remotely complex.

For example, if you run 
SalesHeader.Validate("Sell-to Customer No.") in a TryFunction, you will get a runtime error since there is a Locktable being called in ArchiveManagement. Stack:
ArchiveManagement(CodeUnit 5063).GetNextOccurrenceNo line 8 - Base Application by Microsoft
"Sales Header"(Table 36).InitRecord line 56 - Base Application by Microsoft
"Sales Header"(Table 36)."Sell-to Customer No. - OnValidate"(Trigger) line 9 - Base Application by Microsoft

It is important that we are able to validate field values without terminating execution in all sorts of batch jobs.

**Comment by navdotnetreqs** [comment]
For anyone who's wondering, this can be roughly accomplished (minding write-transactions..) by using a solution from navision and 15 years ago, namely a separate codeunit and if codeunit.run() ...

**Comment by JesperSchulz** [comment]
Unfortunately, this repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

For suggestions to the Business Central product group, please create a [BC Idea](https://aka.ms/bcideas).

If you want to log a support case, please visit:

On premises - https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=93d37907-ad94-d591-22e9-593cfa09dd3f

Cloud – contact your partner, or if you are a partner open a support incident through Partner Center - https://partner.microsoft.com/en-us/pcv/dashboard/overview
