### ISSUE TITLE
[Event Request] Codeunit 5616 "Depreciation Calculation" - OnGetFirstDeprDateOnAfterSetFAFilter

### ISSUE THREAD

**Issue by KlaasKleermaker** [microsoft/ALAppExtensions#26287]
### Describe the request

    procedure GetFirstDeprDate(FANo: Code[20]; DeprBookCode: Code[10]; Year365Days: Boolean): Date
    var
        FALedgEntry: Record "FA Ledger Entry";
        EntryDates: array[4] of Date;
        LocalDate: Date;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeGetFirstDeprDate(FANo, DeprBookCode, Year365Days, LocalDate, IsHandled);
        if IsHandled then
            exit(LocalDate);

        with FALedgEntry do begin
            SetFAFilter(FALedgEntry, FANo, DeprBookCode, true);
            OnGetFirstDeprDateOnAfterSetFAFilter(FALedgEntry); //new
            SetRange("FA Posting Type", "FA Posting Type"::"Acquisition Cost");
            if FindLast() then
                if "FA Posting Date" > LocalDate then
                    LocalDate := "FA Posting Date";
            SetRange("FA Posting Type", "FA Posting Type"::"Salvage Value");
            if FindLast() then
                if "FA Posting Date" > LocalDate then
                    LocalDate := "FA Posting Date";
            SetRange("FA Posting Type", "FA Posting Type"::Depreciation);
            if FindLast() then
                if ToMorrow("FA Posting Date", Year365Days) > LocalDate then
                    LocalDate := ToMorrow("FA Posting Date", Year365Days);
            GetLastEntryDates(FANo, DeprBookCode, EntryDates);
            FindMaxDate(FALedgEntry, EntryDates, LocalDate, Year365Days);
        end;
        exit(LocalDate);
    end;
````
````
    [IntegrationEvent(false, false)]
    local procedure OnGetFirstDeprDateOnAfterSetFAFilter(var FALedgerEntry: Record "FA Ledger Entry")
    begin
        //new
    end;
````


### Additional context

We need to add an extra filter to FALedgEntry. This cannot be done in OnBeforeGetFirstDeprDate, because in SetFAFilter a FALedgEntry.Reset() is done.  

Internal work item: [AB#525465](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/525465)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 18616.
