### ISSUE TITLE
[Event Request] Table 31005 "Sales Adv. Letter Line CZZ" - procedure UpdateAmounts()

### ISSUE THREAD

**Issue by jlorenc01** [microsoft/ALAppExtensions#26284]
### Describe the request

Hello,

I would like to ask for a new publisher in the table 31005 "SSales Adv. Letter Line CZZ", procedure UpdateAmounts(). Other possibility would be to move the event OnBeforeUpdateAmounts() to the beginning of the procedure. Thank you.

```
local procedure UpdateAmounts()
var
    CurrencyExchangeRate: Record "Currency Exchange Rate";
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnUpdateAmountsOnBeforeTestFieldVATProdPostingGroup(Rec, xRec, CurrFieldNo, IsHandled); // NEW EVENT
    if not IsHandled then
        TestField("VAT Prod. Posting Group");

    IsHandled := false;
    OnBeforeUpdateAmounts(Rec, xRec, CurrFieldNo, IsHandled);
    if IsHandled then
        exit;
    ...
end;

// NEW EVENT
[IntegrationEvent(false, false)]
local procedure OnUpdateAmountsOnBeforeTestFieldVATProdPostingGroup(var SalesAdvLetterLineCZZ: Record "Sales Adv. Letter Line CZZ"; xSalesAdvLetterLineCZZ: Record "Sales Adv. Letter Line CZZ"; CurrentFieldNo: Integer; var IsHandled: Boolean)
begin
end;
```

### Additional context

We are using "comment" lines on the sales advance, similarly as on the sales line with the empty **Type**. Those line are without **VAT Prod. Posting Group** so we are facing the problem.
Internal work item: [AB#525463](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/525463)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 20491.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20474.
