### ISSUE TITLE
[Event Request] new publisher in Report "Copy Production Order Document"

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#26281]
Please add an Publisher in report "Copy Production Order Document" in local procedure CopyProdLines.
```
ToProdOrderLine.SetRange(Status, ToProdOrder.Status);
ToProdOrderLine.SetRange("Prod. Order No.", ToProdOrder."No.");
if ToProdOrderLine.FindLast() then
    LineNo := ToProdOrderLine."Line No." + 10000
else
    LineNo := 10000;
FromProdOrderLine.SetRange(Status, StatusType);
FromProdOrderLine.SetRange("Prod. Order No.", DocNo);
################## new Publisher START ####################
OnAfterFilterFromProdOrderLine(FromProdOrderLine, StatusType, DocNo);
################## new Publisher END ####################
if FromProdOrderLine.Find('-') then
    repeat
```

Please parameter FromProdOrderLine as var and do not forget to add sender!

### Additional context

We need to have the possibility to filter production order lines before looping through all production order lines.
Internal work item: [AB#524990](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/524990)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18666.
