### ISSUE TITLE
[Event Request] Page 6013 "Resource Capacity Settings"

### ISSUE THREAD

**Issue by kristjano** [microsoft/ALAppExtensions#26286]
### Describe the request

I need event in method SelectCapacity()
`OnBeforeSelectCapacity(TempDate: Date; CustomizedCalendarChange: Record "Customized Calendar Change"; var WorkTemplateRec: Record "Work-Hour Template"; var Hours: Decimal; var IsHandled: Boolean)`

### Additional context

In customized calendar change, in our extension, user can make a change to the capacity/work hours for that day/date. That change should be reflected when updating capacity. E.g. user is setting up capacity for resource in December (1.12-31.12) user makes changes in calendar for dates 23.12 +2 (extra 2 hours) 24.12 -4 (4 hours reduced capacity). User sets up basic 8 hour work days in Resource Capacity Settings and updates capacity. The hours for 23.12 should be 10 and 24.12 4.
Internal work item: [AB#525462](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/525462)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18666.
