### ISSUE TITLE
[Event Change Request] codeunit 760 "Trailing Sales Orders Mgt." - OnDrillDownOnBeforeRunPage

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#26294]
### Describe the request

Hello, could we get SalesHeader as reference in this event?

like this:
  [IntegrationEvent(false, false)]
    local procedure OnDrillDownOnBeforeRunPage( **va**r SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
    begin
    end;
   

### Additional context

We need this to be able to set filter on the salesheader before it opens the page.
Internal work item: [AB#527156](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527156)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18867.
