### ISSUE TITLE
Setting "resourceExposurePolicy" in "Essential Business Headlines" to allow debugging

### ISSUE THREAD

**Issue by GrzegorzLewicz** [microsoft/ALAppExtensions#26298]
### Describe the request

Please change the "allowDebugging" property to true in the manifest file of "Essential Business Headlines"

```
"resourceExposurePolicy": {
"allowDebugging": true,
"allowDownloadingSource": true,
"includeSourceInSymbolFile": true
}
```

It will make it easier for partners to find the root cause of some issues. One of our customers (Version: W1 20.4) receives the following error: "Cannot call SetAscending on field Amount because it is not part of the current sorting." in the "RC Headlines Executor" job. The callstack show the issue in "Essential Bus. Headline Mgt."(CodeUnit 1437).TryHandleLargestOrder but when with no possibility to see the code in debugger, it's hard to prepare a fix or workaround.

### Additional context

https://github.com/microsoft/ALAppExtensions/discussions/26265 
Internal work item: [AB#525527](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/525527)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18769.
