### ISSUE TITLE
[Bug]: Typo in enum 77 "Report Selection Usage"

### ISSUE THREAD

**Issue by metabo-cstuber** [microsoft/ALAppExtensions#26299]
### Describe the issue

Typo in caption for `value(46; "S.Arch.Order") { Caption = 'Sales Archice Order'; }`
![image](https://github.com/microsoft/ALAppExtensions/assets/167206866/2148f86c-326c-4348-ad5b-024bc38fb2ce)

Versions 23.6 and 24.0

### Expected behavior

Caption should be 'Sales Archive Order'

### Steps to reproduce

Open enum 77 "Report Selection Usage" e.g. in page Report Selection

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Normally, this isn't the right place to report bugs. But here I'll make an exception 😉 I'll fix the typo. Case closed! Thanks for reporting.
