### ISSUE TITLE
CU12179 Export FatturaPA Document - Wrong GetVATType (IT Version)

### ISSUE THREAD

**Issue by dsgobba** [Microsoft/ALAppExtensions#263]
Hi team,

The method in CU 12179

**GetVATType(TypeValue : Option;DocTypeValue : Option;DocNoValue : Code[20];IsSplitPaymentDoc : Boolean)**

is called with wrong parameters by **PopulateLineVATData** method

GetVATType(1,1,FORMAT(LineRecRef.FIELD(LineNoFieldNo).VALUE),IsSplitPaymentDoc)

TypeValue = must be 2 (sales)
DocTypeValue = must be 2 (invoice) or 3 (credit memo)
DocNoValue = must be passed FORMAT(LineRecRef.FIELD(DocNoFieldNo).VALUE)

Could be fixed with new CU?
Thanks

**Comment by mazhelez** [comment]
Hi @dsgobba,

The code in _vNext_ has been changed and does _not_ match your requests any more. If you want to report bug for the current version please open support request and specify the needed version. 

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company
