### ISSUE TITLE
[Event Request] Table 39 Purchase Line - trigger OnInsert - event OnAfterOnInsert

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26304]
### Describe the request

Please add the following Event/-s OnAfterOnInsert to trigger OnInsert in Table 39 Purchase Line

```
[Event Request] Table 39 Purchase Line - trigger OnInsert
trigger OnInsert()
begin
    TestStatusOpen();
    if Quantity <> 0 then begin
        OnBeforeVerifyReservedQty(Rec, xRec, 0);
        PurchLineReserve.VerifyQuantity(Rec, xRec);
    end;
    LockTable();
    if ("Deferral Code" <> '') and (GetDeferralAmount() <> 0) then
        UpdateDeferralAmounts();
    PurchHeader."No." := '';

    OnAfterOnInsert(Rec); // <-- NEW EVENT

end;
```

```
[IntegrationEvent(false, false)]
local procedure OnAfterOnInsert(var PurchaseLine: Record "Purchase Line")
begin
end;
```

### Additional context

we need the possibility to call additional functionality after the insert without additional modify on the record
Internal work item: [AB#527519](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527519)

**Comment by alexei-dobriansky** [comment]
For this purpose, the system OnAfterInsertEvent should work, see here:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/triggers-auto/events/table/devenv-onafterinsertevent-table-trigger
