### ISSUE TITLE
[Event Request] - Table Sales Line - Function UpdateVATPercent

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#26308]
### Describe the request

```
 local procedure UpdateVATPercent(BaseAmount: Decimal; VATAmount: Decimal)
    begin
        if BaseAmount <> 0 then
            "VAT %" := Round(100 * VATAmount / BaseAmount, 0.00001)
        else
            "VAT %" := 0;

        //New Event
        OnAfterUpdateVATPercent(Rec);
        //New Event
    end;
```

```
 [IntegrationEvent(false, false)]
    local procedure OnAfterUpdateVATPercent(var SalesLine: Record "Sales Line")
    begin
    end;
```

### Additional context

i have code dependent on vat %
Internal work item: [AB#527520](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527520)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
