### ISSUE TITLE
[Event Request] Table 36 "Sales Header"

### ISSUE THREAD

**Issue by NilsKagel** [microsoft/ALAppExtensions#26302]
### Describe the request

Could you please add the following event to Table 36 "Sales Header" at Function "UpdateSalesOrderLineIfExist":
```
        IsHandled := false;
        OnBeforeUpdateSalesOrderLineIfExist(Rec, IsHandled);
        if IsHandled then
            exit;

```
Example (new code with >>><<<):
```
    internal procedure UpdateSalesOrderLineIfExist()
    var
        SalesInvoiceHeader: Record "Sales Invoice Header";
        SalesCreditMemoHeader: Record "Sales Cr.Memo Header";
        CorrectPostedSalesInvoice: Codeunit "Correct Posted Sales Invoice";
    begin
        SalesInvoiceHeader.SetLoadFields("No.");
        if not SalesInvoiceHeader.Get(Rec."Applies-to Doc. No.") then
            exit;
        SalesCreditMemoHeader.SetLoadFields("Pre-Assigned No.", "Cust. Ledger Entry No.");
        SalesCreditMemoHeader.SetRange("Pre-Assigned No.", Rec."No.");
        if not SalesCreditMemoHeader.FindFirst() then
            exit;
        if IsNotFullyCancelled(SalesCreditMemoHeader) then
            exit;
>>>
        IsHandled := false;
        OnBeforeUpdateSalesOrderLineIfExist(Rec, IsHandled);
        if IsHandled then
            exit;
<<<
        CorrectPostedSalesInvoice.UpdateSalesOrderLineIfExist(SalesCreditMemoHeader."No.");
    end;
```

### Additional context

We need this event to create a save way to integrate our own function to correct invoices.
Internal work item: [AB#527522](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527522)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
