### ISSUE TITLE
Page 2678 "Redistribute Acc. Allocations" - Procedures SetParentSystemId and SetParentTableId from internal to global

### ISSUE THREAD

**Issue by AlexanderWittek** [microsoft/ALAppExtensions#26314]
### Describe the request

Can the procedures please be set from internal to global.

```
page 2678 "Redistribute Acc. Allocations"
internal procedure SetParentSystemId(NewParentSystemId: Guid)
internal procedure SetParentTableId(NewParentTableId: Integer)
```

### Additional context

We would like to use this functionality in our document pages.
Internal work item: [AB#527527](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527527)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21326.
