### ISSUE TITLE
[Event Request] Additional publishers for Excise Functionality in Bulgaria

### ISSUE THREAD

**Issue by krasivarna** [microsoft/ALAppExtensions#26319]
### Describe the request

For calculating Excise amount in Bulgaria localization we have to modify calculations of amount. The VATAmount is calculated differently. Therefore we need to modify the amount in procedure SumSalesLinesTemp in codeunit "Sales Post". In page "Sales Order Statistics" we also need to modify calculations. There we need to add publisher in procedure RefreshOnAfterGetRecord and procedure UpdateHeaderInfo. In second procedure I add two publishers, because if I add only one I must to transfer more parameters

### Additional context

We have customer on version Navision 2015 which we upgrade to Business Central last version. 

We have pull request  with number  #732, in Base App
Internal work item: [AB#527190](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527190)

**Comment by krasivarna** [comment]
Second object which I want to add event is SalesOrderStatistics.Page.al

local procedure RefreshOnAfterGetRecord()
.........
if Rec."Prices Including VAT" then begin
                TotalAmount2[i] := TotalSalesLine[i].Amount;
                TotalAmount1[i] := TotalAmount2[i] + VATAmount[i];
                TotalSalesLine[i]."Line Amount" := TotalAmount1[i] + TotalSalesLine[i]."Inv. Discount Amount";
            end else begin
                TotalAmount1[i] := TotalSalesLine[i].Amount;
                TotalAmount2[i] := TotalSalesLine[i]."Amount Including VAT";
            end;
//-----Begin New Code
            OnAfterSetTotalAmounts(TotalAmount1,TotalAmount2,TotalSalesLine);
//-----End New Code
        end;

        OnAfterCalculateTotalAmounts(TempSalesLine, TempVATAmountLine1);

................

New Event is
[IntegrationEvent(false,false)]
    local procedure OnAfterSetTotalAmounts(var TotalAmount1:array[3] of decimal;var TotalAmount2:array[3] of decimal;var TotalSalesLine:array[3] of record "sales line")
    begin
    end;




In the same page in procedure UpdateHeaderInfo I want two events or one events with more parameters, which I shall use to refactor parts of current code

procedure UpdateHeaderInfo(IndexNo: Integer; var VATAmountLine: Record "VAT Amount Line")
    var
        CurrExchRate: Record "Currency Exchange Rate";
        UseDate: Date;
        IsHandled:boolean;
    begin
        TotalSalesLine[IndexNo]."Inv. Discount Amount" := VATAmountLine.GetTotalInvDiscAmount();
        TotalAmount1[IndexNo] := TotalSalesLine[IndexNo]."Line Amount" - TotalSalesLine[IndexNo]."Inv. Discount Amount";
//----Begin new code
        OnUpdateHeaderInfoOnAfterSetTotalAmount(IndexNo,TotalAmount1,TotalSalesLine);
//---End New code
        VATAmount[IndexNo] := VATAmountLine.GetTotalVATAmount();       

        if Rec."Prices Including VAT" then begin
            TotalAmount1[IndexNo] := VATAmountLine.GetTotalAmountInclVAT();
            TotalAmount2[IndexNo] := TotalAmount1[IndexNo] - VATAmount[IndexNo];
//---Begin new code
            IsHandled:=false;
            OnUpdateHeaderInfoOnBeforeSetLineAmount(TotalSalesLine,TotalAmount1,IndexNo,IsHandled);
            if not IsHandled then
//---End new code
                TotalSalesLine[IndexNo]."Line Amount" :=
                  TotalAmount1[IndexNo] + TotalSalesLine[IndexNo]."Inv. Discount Amount";
        end else
            TotalAmount2[IndexNo] := TotalAmount1[IndexNo] + VATAmount[IndexNo];
        
        OnUpdateHeaderInfoOnBeforeSetAmount(IndexNo);

...................

These are both new events

[IntegrationEvent(false,false)]
    local procedure OnUpdateHeaderInfoOnAfterSetTotalAmount(IndexNo:integer;var TotalAmount1:array[3] of decimal;var TotalSalesLine:array[3] of record "sales line")
    begin
    end;

    [IntegrationEvent(false,false)]
    local procedure OnUpdateHeaderInfoOnBeforeSetLineAmount(var TotalSalesLine:array[3] of record "sales line";var TotalAmount1:array[3] of decimal;IndexNo:integer;var IsHandled:boolean)
    begin
    end;

**Comment by krasivarna** [comment]
Hello, when you will be able to view the required event request. In 24.1 not exists

**Comment by krasivarna** [comment]
Hello Is anybody work of this issue. When I can expect answer or decision of these

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21851.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 21891.
