### ISSUE TITLE
[Event Request] Master Data Management

### ISSUE THREAD

**Issue by Bertverbeek4PS** [microsoft/ALAppExtensions#26311]
### Describe the request

Codeunit 7231 "Integration Master Data Synch.???

?? Before Line: 79 Integration Event:

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line: 166 Integration Event:

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line: 206 Integration Event:

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line: 262 Integration Event:

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

Codeunit 7233 "Master Data Management"

?? Before Line 308 Integration Event

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line 330 Integration Event

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line: 337 Integration Event

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line: 345 Integration Event

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line: 663 Integration Event

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line: 851 Integration Event

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line: 869 Integration Event

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line: 1961 Integration Event

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line: 2013 Integration Event

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line 2045 Integration Event:

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? In Procedure GetIntegrationRecRefCount Line 2050: Integration event added at begin

OnSetMasterCompany(var MasterCompany: Text; TableID: Integer)

Note: Instead of ChangeCompany(MasterDataManagementSetup."Company Name") Use new variable MasterCompany: Text

?? Before Line 2152 Integration Event:

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line 2178 Integration Event:

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

Codeunit 7235 "Master Data Mgt. Table Couple"

?? Before Line: 118 Integration Event:

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

Codeunit 7236 "Master Data Mgt. Tbl. Uncouple"

?? Before Line: 84 Integration Event:

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

Codeunit 7237 "Master Data Mgt. Subscribers"

?? Before Line: 102 Integration Event:

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line: 170 Integration Event:

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line: 352 Integration Event:

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line: 498 Integration Event:

IntegrationRecordRefBeforeChangeCompany(var IntegrationRecordRef: RecordRef; var IsHandled: Boolean)

?? Before Line: 528 Integration Event:

OnSetMasterCompany(var MasterCompany: Text; TableID: Integer) Note: ContactTableID is used

Note: Instead of ChangeCompany(MasterDataManagementSetup."Company Name") Use new variable MasterCompany: Text

?? Before Line: 557 Integration Event:

OnSetMasterCompany(var MasterCompany: Text; TableID: Integer) Note: ContactTableID is used

Note: Instead of ChangeCompany(MasterDataManagementSetup."Company Name") Use new variable MasterCompany: Text

?? Before Line: 586 Integration Event:

OnSetMasterCompany(var MasterCompany: Text; TableID: Integer) Note: ContactTableID is used

Note: Instead of ChangeCompany(MasterDataManagementSetup."Company Name") Use new variable MasterCompany: Text

?? Procedure FixPrimaryContactNo Line 671 Integration Event added at begin

OnSetMasterCompany(var MasterCompany: Text; TableID: Integer)

Note: Instead of ChangeCompany(MasterDataManagementSetup."Company Name") Use new variable MasterCompany: Text

?? Procedure UpdateChildContactsParentCompany Line 772 Integration Event added at begin

OnSetMasterCompany(var MasterCompany: Text; TableID: Integer)

Note: Instead of ChangeCompany(MasterDataManagementSetup."Company Name") Use new variable MasterCompany: Text

### Additional context

Master Data Management is just for one single company. We have a solution like Master Data Management but then you can choose per table which central company managed the data.
We need to convert our solution to Master Data Management and this is currently not possible.
So this is way we request the events. 
Another way is to enrich the Master Data Management with this feature.

@dcenic as discussed.
Internal work item: [AB#527523](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527523)

**Comment by dcenic** [comment]
@Bertverbeek4PS In order not to narrow down the terminology to ChangeCompany function, I will name the events IntegrationRecordRefBeforeChangeCompany as 'OnGetSourceRecordRef', because the purpose is to populate the RecordRef with the record from the source company (if it's in the same environment then it is ChangeCompany, if it is cross-environment then it is something else). One day, when we get approval to go for cross-environment, we could use these events to do a cross-environment call instead of just ChangeCompany calls). Or we could use an interface... But that is in the future.

**Comment by dcenic** [comment]
@Bertverbeek4PS By examining the code, I found out that we already have various events MasterDataManagement.OnGetIntegrationRecordRefByIntegrationSystemId and
MasterDataManagement.OnGetIntegrationRecordRef
that both take IntegrationTableMapping. But we just don't raise them in enough places. That said, they might get handy for cross-environment work.
But I think for your scenario: allowing a source company per table id, I think we should do it uniformly like this:
before calling ChangeCompany, raise event OnSetSourceCompany(SourceCompanyName, TableID).
if it is handled, change company with that SourceCompanyName. You requested that in a subset of cases we do it like this, and other subset we do it differently. I think we should do it like this in all the places that you pointed out. You just subscribe to OnSetSourceCompany and set the company name based on Table ID.

**Comment by Bertverbeek4PS** [comment]
Thanks @dcenic! Indeed that would be very usefull! 
But then in the other way we do it now with a custom field and events.
Would it not be better to have such a scenario in the base? 
And indeed for cross company you also need the events.

**Comment by dcenic** [comment]
@Bertverbeek4PS It didn't look right to enable this by allowing the custom setting of source company name in half of the occurrences, and to raise a OnGetIntegrationRecordRef in half of the other occurrences. Across the app, there are various ways that source record ref is gotten (by RecordId, by Guid, by text, by filtering and then findfirst etc), so we need to think more about how to raise these events that will be useful for cross-env. For now, you just need to subscribe and return the source company depending on the Table No. - and it will support having source company per table (within the same environment of course).

**Comment by Bertverbeek4PS** [comment]
Thanks @dcenic !
