### ISSUE TITLE
[Event Request] Table 5050 Contact: adjust  ublisher in function UpdateCompanyNo

### ISSUE THREAD

**Issue by FalkGraefenGOB** [microsoft/ALAppExtensions#26315]
### Describe the request

H! We would like to request a change to the following publisher in table 5050 Contact: 

  ```
  local procedure UpdateCompanyNo()
    var
        Cont: Record Contact;
        ContBusRel: Record "Contact Business Relation";
        InteractLogEntry: Record "Interaction Log Entry";
        Opp: Record Opportunity;
        OppEntry: Record "Opportunity Entry";
        SalesHeader: Record "Sales Header";
        Task: Record "To-do";
    begin
        OnBeforeUpdateCompanyNo(Rec, xRec);
```

We would like to request an IsHandled pattern so that we can circumvent the logic thereafter, e.g. like this. 

```
 local procedure UpdateCompanyNo()
    var
        Cont: Record Contact;
        ContBusRel: Record "Contact Business Relation";
        InteractLogEntry: Record "Interaction Log Entry";
        Opp: Record Opportunity;
        OppEntry: Record "Opportunity Entry";
        SalesHeader: Record "Sales Header";
        Task: Record "To-do";
        IsHandled: Boolean;
    begin
        OnBeforeUpdateCompanyNo(Rec, xRec, IsHandled);
        If Ishandled then 
           exit;
```

### Additional context

We would need this publisher adjustment to be able to adjust the application's behaviour when changing the Comapny No. of a Contact. 

We work with customers that are  focussed on person-contacts. And with the MS Standard behaviour, a lot of subtables to a contact (e.g. InteractionLogEntries or Tasks) loose their relation to the person-contact when a person-contact's Company No. is changed. We need to be able to provide an alternatoive logic to these tables, as our customers wish to keep the person-contact related correspondence at the person-contact.. 
Internal work item: [AB#527485](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527485)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
