### ISSUE TITLE
[Bug]: API Enums spaces as _x0020_ , enum parsing API.

### ISSUE THREAD

**Issue by Klechaa** [microsoft/ALAppExtensions#26318]
### Describe the issue

All space signs are converted to 
![image](https://github.com/microsoft/ALAppExtensions/assets/4472075/8f377516-ccd8-4908-8567-f273ed77dcc7)

Therefore enums are not working as expected. For example blocked enum " " was parsed to "_0020_"

Some endpoints are not even recreated, there are not existent in metadata when API has field with enum datatype..

### Expected behavior

Parsing should be fixed.

### Steps to reproduce

Create enum with space in name of value.
Create Page api with such enum field.
Check endpoint data with http GET query.

### Additional context

![image](https://github.com/microsoft/ALAppExtensions/assets/4472075/e56e4408-9b56-4e1e-990f-8ca832dcdaf0)

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by joandrsn** [comment]
Hi @Klechaa. We have just experienced this issue by a customer.

Is there any information on when this version should be live for OnPrem installations? Also any additional information would be great to provide some context on why this happens.

AJ mentions this on his blog, but provides no further explaination on the values:
https://www.kauffmann.nl/2020/12/10/business-central-api-v2-0/
