### ISSUE TITLE
[Procedure Var Parameter Request] codeunit 5812 "Calculate Standard Cost" - CalcRtngLineCost

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#26317]
### Describe the request

Please add variable
ParentItem: Record Item to the parameters of function CalcRtngLineCost.

local procedure CalcRtngCost(RtngHeaderNo: Code[20]; MfgItemQtyBase: Decimal; var SLCap: Decimal; var SLSub: Decimal; var SLCapOvhd: Decimal; var ParentItem: Record Item)
....
            CalcRtngLineCost(RtngLine, MfgItemQtyBase, SLCap, SLSub, SLCapOvhd, ParentItem);
....
end;

procedure CalcRtngLineCost(RoutingLine: Record "Routing Line"; MfgItemQtyBase: Decimal; var SLCap: Decimal; var SLSub: Decimal; var SLCapOvhd: Decimal; var ParentItem: Record Item)
....
end;

### Additional context

This issue needs to be solved to allow the solving of another issue which will be issued when this issue will finally be solved.
Related to https://github.com/microsoft/ALAppExtensions/issues/25598 which I will close because it seems to be on hold indefinitely.
Internal work item: [AB#527489](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527489)

**Comment by alexei-dobriansky** [comment]
Please specify how you will use this ParentItem in the CalcRtngLineCost. The compiler won't allow me to add a parameter which is never used.

**Comment by alexei-dobriansky** [comment]
Please specify how you'll be using this ParentItem variable. The compiler won't allow be to add an unused parameter.

**Comment by Duizy1971** [comment]
If you have read the 'Additional context' of this issue, then that will explain why I'm asking for this extra parameter. I have created multiple previous issues and either merging them in one or splitting them in multiple, nobody seems to be able to act on those issues so I have closed them. This issue is a fresh start of a couple of other issues that I will send.

But just to clarify:
I will be using the ParentItem in Event OnAfterCalcRtngLineCost as var.

**Comment by alexei-dobriansky** [comment]
If this is a fresh start, would you add here the code or event publishers that you'll need in the CalcRtngLineCost function? As I said, I can't add the ParentItem parameter if it's not used anywhere in the function.

I found out that we have the parameter you're requesting in Italian localization of codeunit 5812. I'm attaching it here. Do you plan to use it similarly?
[CalculateStandardCost.Codeunit.txt](https://github.com/microsoft/ALAppExtensions/files/15247724/CalculateStandardCost.Codeunit.txt)

**Comment by Duizy1971** [comment]
The IT localization is using it in CalcRoutingCostPerUnit. I need it in OnAfterCalcRtngLineCost as stated in https://github.com/microsoft/ALAppExtensions/issues/25599 which could not be solved at your end at the time:

Add variables ParentItem and CostTime to event procedure OnAfterCalcRtngLineCost:
    
procedure CalcRtngLineCost(RoutingLine: Record "Routing Line"; MfgItemQtyBase: Decimal; var SLCap: Decimal; var SLSub: Decimal; var SLCapOvhd: Decimal; var ParentItem: Record Item)
....

    OnAfterCalcRtngLineCost(RoutingLine, MfgItemQtyBase, SLCap, SLSub, SLCapOvhd, StdCostWkshName, ParentItem, CostTime);
end;

[IntegrationEvent(false, false)]
local procedure OnAfterCalcRtngLineCost(RoutingLine: Record "Routing Line"; MfgItemQtyBase: Decimal; var SLCap: Decimal; var SLSub: Decimal; var SLCapOvhd: Decimal; var StdCostWkshName: Text[50]; var ParentItem: Record Item; CostTime: Decimal)
begin
end;

**Comment by Duizy1971** [comment]
Hi Alexei,

I'm looking in de 25.x daily and it seems something has changed already. If this is the proposed solution to my request, I'm still not being helped. I need the calculations in CalcRtngLineCost and OnAfterCalcRtngLineCost.


    local procedure CalcRtngCost(RtngHeaderNo: Code[20]; MfgItemQtyBase: Decimal; var SLCap: Decimal; var SLSub: Decimal; var SLCapOvhd: Decimal; var ParentItem: Record Item)
    var
        RtngLine: Record "Routing Line";
        RtngHeader: Record "Routing Header";
        IsHandled: Boolean;
    begin
        if RtngLine.CertifiedRoutingVersionExists(RtngHeaderNo, CalculationDate) then begin
            if RtngLine."Version Code" = '' then begin
                RtngHeader.Get(RtngHeaderNo);
                TestRtngVersionIsCertified(RtngLine."Version Code", RtngHeader);
            end;

            repeat
                IsHandled := false;
                OnCalcRtngCostOnBeforeCalcRtngLineCost(RtngLine, ParentItem, LogErrors, IsHandled);
                if not IsHandled then
                    CalcRtngLineCost(RtngLine, MfgItemQtyBase, SLCap, SLSub, SLCapOvhd);
            until RtngLine.Next() = 0;
        end;
    end;

**Comment by Duizy1971** [comment]
Also in new event OnCalcRtngCostOnBeforeCalcRtngLineCost the ParentItem variable is not as var as requested. This had for now no use at all I'm afraid. Another bad day for our PM with our customer.

**Comment by Duizy1971** [comment]
Allas, this issue is, again, unresolved. Closing this one and creating another new one.
