### ISSUE TITLE
[Access Request]  page 1001 "Job Task Lines Subform" - PerTaskBillingFieldsVisible

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#26329]
### Describe the request

Could you please change the access scope of the following variable to protected?
```al
protected var
    PerTaskBillingFieldsVisible: Boolean;
```

### Additional context

We would like to hide and show custom fields depending on this value. Therefore we need access to those variable.
Internal work item: [AB#527180](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527180)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18872.
