### ISSUE TITLE
[Request for External] - Report Calculate Inventory - ValidatePostingDate

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#26322]
### Describe the request

```
    local procedure ValidatePostingDate()
    begin
        if not ItemJnlBatch.Get(ItemJnlLine."Journal Template Name", ItemJnlLine."Journal Batch Name") then
            exit;

        if ItemJnlBatch."No. Series" = '' then begin
            DocumentNoInputMandatory := true;
            NextDocNo := ''
        end else begin
            DocumentNoInputMandatory := false;
            NextDocNo := NoSeriesMgt.GetNextNo(ItemJnlBatch."No. Series", PostingDate, false);
            Clear(NoSeriesMgt);
        end;
    end;
```

### Additional context

Could this function be made global? I need to call it, because we override posting date and itemjnlline in onprereport
Internal work item: [AB#527187](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527187)

**Comment by ChethanT** [comment]
@DanielHaglo method seem to depend on one or more global variables to be set, making that method as public increases the risk of it failing or returning undesired results.
Can you please explain the use cases for better understanding?

**Comment by DanielHaglo** [comment]
We have implementet a solution to automatically set the journal template name and batch name when running in background (job queue for this example), and we are changing the posting date. Therefore we also want to call this function.

I understand there are dependencies on global variables, but all of them, except DocumentNoInputMandatory, is protected var. 

As long as we have control over the protected variables, i think we should be fine for now.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19575.
