### ISSUE TITLE
[Event Request]  table 167 Job - OnAfterSyncShipToWithSellTo

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#26324]
### Describe the request

Could you please add the following event?
```al
    procedure SyncShipToWithSellTo()
    begin
        Rec."Ship-to Name" := Rec."Sell-to Customer Name";
        Rec."Ship-to Name 2" := Rec."Sell-to Customer Name 2";
        Rec."Ship-to Address" := Rec."Sell-to Address";
        Rec."Ship-to Address 2" := Rec."Sell-to Address 2";
        Rec."Ship-to City" := Rec."Sell-to City";
        Rec."Ship-to County" := Rec."Sell-to County";
        Rec."Ship-to Post Code" := Rec."Sell-to Post Code";
        Rec."Ship-to Country/Region Code" := Rec."Sell-to Country/Region Code";
        Rec."Ship-to Contact" := Rec."Sell-to Contact";
        Rec."Ship-to Code" := '';
        OnAfterSyncShipToWithSellTo(Rec);
    end;
```

```al

[IntegrationEvent(false, false)]
local procedure OnAfterSyncShipToWithSellTo(var Job: Record Job)
begin
end;
```

### Additional context

We would like to sync custom fields.
Internal work item: [AB#527183](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527183)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18867.
