### ISSUE TITLE
[Access Request] page 1003 "Job Task Card" - ShipToOptions, BillToOptions, ShouldSearchForCustByName, etc.

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#26328]
### Describe the request

Could you please change the access scope of the following variables to protected?
```al
protected var
    ShipToOptions: Enum "Sales Ship-to Options";
    BillToOptions: Enum "Sales Bill-to Options";
    ShouldSearchForCustByName: Boolean;
    PerTaskBillingFieldsVisible: Boolean;
```

### Additional context

We would like to hide and show custom fields. Therefore we need access to those varialbes (similiar to Job Card, Sales Order Page, etc.)
Internal work item: [AB#527488](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527488)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
