### ISSUE TITLE
[Event Change Request] codeunit 226 "CustEntry-Apply Posted Entries" - OnApplyApplyCustEntryFormEntryOnAfterCustLedgEntrySetFilters

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#26337]
### Describe the request

Hello, can you please add the variable CustEntryApplID to the OnApplyApplyCustEntryFormEntryOnAfterCustLedgEntrySetFilters event?

```
    local procedure RunApplyCustEntries(var CustLedgEntry: Record "Cust. Ledger Entry"; var ApplyingCustLedgEntry: Record "Cust. Ledger Entry"; CustEntryApplID: Code[50])
    var
        ApplyCustEntries: Page "Apply Customer Entries";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnApplyApplyCustEntryFormEntryOnAfterCustLedgEntrySetFilters(CustLedgEntry, ApplyingCustLedgEntry, IsHandled, CustEntryApplID);
        if IsHandled then
            exit;

        if CustLedgEntry.FindFirst() then begin
```

```
    [IntegrationEvent(false, false)]
    local procedure OnApplyApplyCustEntryFormEntryOnAfterCustLedgEntrySetFilters(var CustLedgerEntry: Record "Cust. Ledger Entry"; var ApplyingCustLedgerEntry: Record "Cust. Ledger Entry" temporary; var IsHandled: Boolean; var CustEntryApplID: Code[50]);
    begin
    end;
```

### Additional context

We would like also set the variable in our function. Otherwise the variable is not set.
Internal work item: [AB#527166](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527166)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 18867.
