### ISSUE TITLE
[Request-For-External] Table 38 "Purchase Header" - Procedures from Local to Global

### ISSUE THREAD

**Issue by AlexanderWittek** [microsoft/ALAppExtensions#26348]
### Describe the request

Can the procedures please be set from internal to global.

```
table 38 "Purchase Header"

procedure PerformManualRelease(var PurchaseHeader: Record "Purchase Header")
procedure PerformManualRelease()
procedure PerformManualReopen(var PurchaseHeader: Record "Purchase Header")
```

This has already been done in the sales area.

### Additional context

We would like to use this functionality in our document pages.
Internal work item: [AB#527541](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527541)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
