### ISSUE TITLE
[Event Change Request] Add parameter Invoice to OnHandleSalesLineOnAfterValidateRetQtytoReceive, codeunit 5763 "Whse.-Post Shipment"

### ISSUE THREAD

**Issue by TarasKozachenko** [microsoft/ALAppExtensions#26345]
### Describe the request

1. Add global variable "Invoice" to publisher OnHandleSalesLineOnAfterValidateRetQtytoReceive
```
    [IntegrationEvent(false, false)]
    local procedure OnHandleSalesLineOnAfterValidateRetQtytoReceive(var SalesLine: Record "Sales Line"; var WhseShptLine: Record "Warehouse Shipment Line")
    begin
    end;
    >>>>>>>>>>>>>
    local procedure OnHandleSalesLineOnAfterValidateRetQtytoReceive(var SalesLine: Record "Sales Line"; var WhseShptLine: Record "Warehouse Shipment Line"; Invoice: Boolean)
    <<<<<<<<<<<<
    begin
    end;
```

2. Add global variable "Invoice"

```
OnHandleSalesLineOnAfterValidateRetQtytoReceive(SalesLine, WhseShptLine);
    >>>>>>>>>>>>>
OnHandleSalesLineOnAfterValidateRetQtytoReceive(SalesLine, WhseShptLine, Invoice);
    <<<<<<<<<<<<
```

### Additional context

We need to add parameter "Invoice" to OnHandleSalesLineOnAfterValidateRetQtytoReceive, codeunit 5763 "Whse.-Post Shipment" as this value impacts the correct counting of our additional fields
Internal work item: [AB#527536](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527536)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
