### ISSUE TITLE
[Event Change Request] codeunit 225 "Gen. Jnl.-Apply" - OnApplyVendorLedgerEntryOnAfterSetVendorAppliesToDocNo

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#26344]
### Describe the request

Hello, we have requested two events in codeunit codeunit 225 "Gen. Jnl.-Apply".
OnAfterSetVendorAppliesToDocNo  with Issue number 25890
OnAfterSetCustomerAppliesToDocNo with Issue number 25889.
OnAfterSetCustomerAppliesToDocNo  was with BC 24.0 implemented with Event  ApplyCustomerLedgerEntryOnAfterSetCustomerAppliesToDocNo in the function ApplyCustomerLedgerEntry.
OnAfterSetVendorAppliesToDocNo was not implemented in the funktion ApplyVendorLedgerEntry, but a new event OnApplyVendorLedgerEntryOnAfterSetVendorAppliesToDocNo in the funktion ApplyVendorLedgerEntryAPI was implemented.

Could it be that the event was accidentally integrated into the wrong function and actually belongs in ApplyVendorLedgerEntry?

And can please set the record variable VendorLedgerEntry as var?

```
    [IntegrationEvent(false, false)]
    local procedure OnApplyVendorLedgerEntryOnAfterSetVendorAppliesToDocNo(var GenJournalLine: Record "Gen. Journal Line"; var VendorLedgerEntry: Record "Vendor Ledger Entry")
    begin
    end;
```

### Additional context

We need the Event OnApplyVendorLedgerEntryOnAfterSetVendorAppliesToDocNo in function ApplyVendorLedgerEntry.
Internal work item: [AB#527533](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527533)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
