### ISSUE TITLE
[Event Change Request] Add parameter to OnBeforeFilterByQuantityPer event in Codeunit 5870 "Calculate BOM Tree"

### ISSUE THREAD

**Issue by mfferrari** [microsoft/ALAppExtensions#26347]
### Describe the request

Hi team, we need a new parameter into the event OnBeforeFilterByQuantityPer in the procedure GenerateProdCompSubTree of Codeunit 5870. The parameter to add is the variabile ParentBOMBuffer or, alternatively, BOMBuffer. So finally the event should change in this way

Existing Event:
[IntegrationEvent(false, false)]
    local procedure OnBeforeFilterByQuantityPer(var ProductionBOMLine: Record "Production BOM Line"; var IsHandled: Boolean)
    begin
    end;

New Event:
[IntegrationEvent(false, false)]
    local procedure OnBeforeFilterByQuantityPer(var ProductionBOMLine: Record "Production BOM Line"; var IsHandled: Boolean; ParentBOMBuffer: Record "BOM Buffer")
    begin
    end;

### Additional context

With the new parameter it will be possibile to change the filters applied to the ProdBOMLine variable, or to add new filters by using the fields of the ParentBOMBuffer variable, before calling the FindSet instruction.
Internal work item: [AB#527535](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527535)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
