### ISSUE TITLE
[Change Request] report 5801 "Invt. Valuation - Cost Spec."

### ISSUE THREAD

**Issue by Ilke415** [microsoft/ALAppExtensions#26359]
### Describe the request

Hello, can you please move the following variables to the protected?

-         ValuationDate
-         ResultForTotalRemAvg
-         ResultForAvgCost
-         RemainingQty

### Additional context

```al
var
        ValueEntry: Record "Value Entry";
        EntryTypeDescription: array[5] of Text[30];
        i: Integer;
        NoOfEntries: array[5] of Decimal;
        PosQty: Decimal;
        TotalCostTotal: array[5] of Decimal;
        TotalRemAvg: Decimal;
        TotalCostAvg: array[5] of Decimal;
        TotalCost: Decimal;
        IsPositive: Boolean;
        ResultForTotalCostTotal: array[5] of Decimal;
        ResultForUnitCost: array[5] of Decimal;
        ResultForTotalCostAvg: array[5] of Decimal;
        ResultForTotalCost: Decimal;
        ResultForRemainingQty: Decimal;

        Text000: Label 'As of %1';
        Text001: Label 'Enter the valuation date.';

    protected var
        ValuationDate: Date;
        ResultForTotalRemAvg: Decimal;
        ResultForAvgCost: Decimal;
        RemainingQty: Decimal;
```
We need them for performing our custom calculations.
Internal work item: [AB#527548](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527548)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
