### ISSUE TITLE
[Event Change Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeCheckDetVendLedgEntryMultiplePostingGrOnBeforeUnapply and OnBeforeCheckDetCustLedgEntryMultiplePostingGrOnBeforeUnapply

### ISSUE THREAD

**Issue by Kelly-cn** [microsoft/ALAppExtensions#26357]
### Describe the request

In the Codeunit 12 "Gen. Jnl.-Post Line", we need to have two integration events which similar like OnBeforeCheckCustMultiplePostingGroups to check the multiple posting groups in procedure CheckDetVendLedgEntryMultiplePostingGrOnBeforeUnapply and CheckDetCustLedgEntryMultiplePostingGrOnBeforeUnapply.

local procedure CheckDetVendLedgEntryMultiplePostingGrOnBeforeUnapply(var DetailedVendorLedgEntry2: Record "Detailed Vendor Ledg. Entry"; var DetailedVendorLedgEntry: Record "Detailed Vendor Ledg. Entry"): Boolean
    begin
**OnBeforeCheckDetVendLedgEntryMultiplePostingGrOnBeforeUnapply(DetailedVendorLedgEntry2,  DetailedVendorLedgEntry, IsMultiplePostingGroups, IsHandled); 
if IsHandled then
            exit(IsMultiplePostingGroups);**   //new event
        DetailedVendorLedgEntry2.SetRange("Entry Type", DetailedVendorLedgEntry2."Entry Type"::Application);
        DetailedVendorLedgEntry2.FindSet();
        repeat
            if DetailedVendorLedgEntry2."Posting Group" <> DetailedVendorLedgEntry."Posting Group" then
                exit(true);
        until DetailedVendorLedgEntry2.Next() = 0;
        exit(false);
    end;

local procedure CheckDetCustLedgEntryMultiplePostingGrOnBeforeUnapply(var DetailedCustLedgEntry2: Record "Detailed Cust. Ledg. Entry"; DetailedCustLedgEntry: Record "Detailed Cust. Ledg. Entry"): Boolean
    begin
**OnBeforeCheckDetCustLedgEntryMultiplePostingGrOnBeforeUnapply(DetailedCustLedgEntry2,  DetailedCustLedgEntry, IsMultiplePostingGroups, IsHandled); 
if IsHandled then
            exit(IsMultiplePostingGroups);**   //new event
        DetailedCustLedgEntry2.SetRange("Entry Type", DetailedCustLedgEntry2."Entry Type"::Application);
        DetailedCustLedgEntry2.FindSet();
        repeat
            if DetailedCustLedgEntry2."Posting Group" <> DetailedCustLedgEntry."Posting Group" then
                exit(true);
        until DetailedCustLedgEntry2.Next() = 0;
        exit(false);
    end;

**[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckDetVendLedgEntryMultiplePostingGrOnBeforeUnapply(var DetailedVendorLedgEntry2: Record "Detailed Vendor Ledg. Entry"; var DetailedVendorLedgEntry: Record "Detailed Vendor Ledg. Entry"; var IsMultiplePostingGroups: Boolean; var IsHandled: Boolean)
    begin
    end;**
**[IntegrationEvent(false, false)]
local procedure OnBeforeCheckDetCustLedgEntryMultiplePostingGrOnBeforeUnapply(var DetailedCustLedgEntry2: Record "Detailed Cust. Ledg. Entry"; DetailedCustLedgEntry: Record "Detailed Cust. Ledg. Entry"; var IsMultiplePostingGroups: Boolean; var IsHandled: Boolean)
  begin
    end;**

### Additional context

We need this event to check if the unapply process also involves different dimension documents to decide whether create G/L entries or not.
```[tasklist]
### Tasks
```

Internal work item: [AB#527480](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527480)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19454.
