### ISSUE TITLE
Different field size in localizations

### ISSUE THREAD

**Issue by ABaludin** [microsoft/ALAppExtensions#2635]
Business central Spring release
RU and US localizations
Need to have same fields length in all localizations.
Due to the next differences in tables Intelligent Cloud don't want to replicate next situations:
 
1) Table 85 Acc. Schedule Line
Field "Row No."
RU localization - Code[20]
US localization - Code[10]

2) Table 334 Column Layout
Field "Column Header"
RU localization - Text[50]
US localization - Text[30]

3) Table 1223 Data Exch. Column Def
Field "Constant"
RU localization - Text[250]
US localization - Text[30]

4) Table 5200 Employee
Field "Job Title"
RU localization - Text[50]
US localization - Text[30]

**Comment by AlexanderYakunin** [comment]
We do not consider or support this scenario. Why do you need this?

**Comment by ABaludin** [comment]
But this scenario almost works. We just need to have same size for fields or not throwing an error when we replicating bigger field to smaller (just cut field values).

We have 2 databases - operational on premise RU localization and consolidation US database in the cloud. Intelligent Edge is the easiest way to replicate data from on premise to cloud. 
I reduced some fields size in on premise database now and everything works but I don't want to do it in future :)
