### ISSUE TITLE
Question for (closed) Event Request #26080 

### ISSUE THREAD

**Issue by PatrickFariaDaSilva** [microsoft/ALAppExtensions#26358]
### Describe the request

Hello, I reported this request about 1 month ago. The ticket has already been closed and suggests that the event has already been adjusted. However, I cannot find the adjustments in one of the new BC versions. Can you tell me approximately when the event will be adjusted?

Reference Ticket:
#26080 

### Additional context

It would be good if the adjustments were included in one of the next updates

**Comment by JesperSchulz** [comment]
From the upcoming minor release, the code looks as follows:
```
                IsHandled := false;
                OnSalesOrderLineOnAfterGetRecordOnBeforeSetTempSalesLine(SalesOrderLine, IsHandled);
                if not IsHandled then begin
                    TempSalesLine := SalesOrderLine;
                    TempSalesLine.Insert();
                end;
```
