### ISSUE TITLE
Report 13630/13631 "OIOUBL-Create Elec. Invoices"/"OIOUBL-Create Elec. Cr. Memos requested events still not in new version.

### ISSUE THREAD

**Issue by MortenRa** [microsoft/ALAppExtensions#26351]
### Describe the request

I can not see that this has been implemented in the major BC24 Microsoft_OIOUBL_24.0.16410.18040, could you let me know which build I can expect this to be in.

https://github.com/microsoft/ALAppExtensions/issues/25726

### Additional context

Reference https://github.com/microsoft/ALAppExtensions/issues/25726

Internal work item: [AB#527543](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527543)

**Comment by Vadim-Stepanenko** [comment]
It did not make it into 24.0, it is in 24.1
