### ISSUE TITLE
[Event Request] Add event OnBeforeTransferFieldsFromCustToCont to "CustCont-Update" codeunit

### ISSUE THREAD

**Issue by rmurriero-alterna** [microsoft/ALAppExtensions#26354]
### Describe the request

Hi, we need an event before the TransferFields between Customer and Contact. 
Object is Codeunit 5056 "CustCont-Update"

```
procedure OnModify(var Cust: Record Customer)
        ...
        NoSeries := Cont."No. Series";
        Cont.Validate("E-Mail", Cust."E-Mail");

        OnBeforeTransferFieldsFromCustToCont(Cont, Cust);    // Add this event call
        Cont.TransferFields(Cust);
        Cont."No." := ContNo;
        Cont."No. Series" := NoSeries;
        OnAfterTransferFieldsFromCustToCont(Cont, Cust);
        ...
end;
```

```
// add this integration event
[IntegrationEvent(false, false)]
local procedure OnBeforeTransferFieldsFromCustToCont(var Contact: Record Contact; Customer: Record Customer)
begin
end;
```

### Additional context

We want some custom fields present on both Contact and Customer not to be transferred during the TransferFields. To do this, we need an event "before" the operation to save the field values, and a subsequent event (already existing) to put the saved values ??????back.
Internal work item: [AB#527491](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527491)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
