### ISSUE TITLE
[Event Change Request] Codeunit 80 Sales Post - Event OnBeforeDivideAmount

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26366]
### Describe the request

We would like add IncludeSender to the following events.

Original:

```
Codeunit 80 Sales Post - Event OnBeforeDivideAmount

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDivideAmount(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; QtyType: Option General,Invoicing,Shipping; var SalesLineQty: Decimal; var TempVATAmountLine: Record "VAT Amount Line" temporary; var TempVATAmountLineRemainder: Record "VAT Amount Line" temporary; var IsHandled: Boolean; var TempPrepmtDeductLCYSalesLine: Record "Sales Line" temporary)
    begin
    end;
```

Change:

```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeDivideAmount(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; QtyType: Option General,Invoicing,Shipping; var SalesLineQty: Decimal; var TempVATAmountLine: Record "VAT Amount Line" temporary; var TempVATAmountLineRemainder: Record "VAT Amount Line" temporary; var IsHandled: Boolean; var TempPrepmtDeductLCYSalesLine: Record "Sales Line" temporary)
    begin
    end;
```

### Additional context

Call DivideAmount from outside out of an Event
Internal work item: [AB#527648](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527648)

**Comment by alexei-dobriansky** [comment]
DivideAmount can't be global with the current implementation. Please explain the scenario and if these events would be a help if DivideAmount remains local?

**Comment by SKeiler** [comment]
Hi,

we would like to call DivideAmount ot of an COD80-Subsriver-Event where IncludeSender is Set. We want to change to parameters which are used to call DivideAmount (get it also calced for the Qty. to Ship) and it is not neccessary to copy an critical COD80-procedure. So we need DivideAmount set to global and the IncludeSender-Property activated. In this case we can call DivideAmount out of an COD80-Event in the instance of current posting. 

In COD90 DivideAmount is already set to global!

There is also a Event request to expose DivideAmount as global --> https://github.com/microsoft/ALAppExtensions/issues/26368

**Comment by alexei-dobriansky** [comment]
DivideAmount in Codeunit 80 relies on global variables mentioned in the request #26368 be initialized and we don't have global functions to initialize those yet.
Local functions are tightly connected to their surrounding code. They exist within a specific scope, depend on variables initialized elsewhere in the code. Exposing local functions, especially in posting codeunits, requires double caution. If someone misuses it, that can be hard to fix the consequences.
