### ISSUE TITLE
[Request for External] table 99000772 "Production BOM Line" - protected variable

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26363]
### Describe the request

Hello, we need the following currently global variable/-s to be set as protected. Can you please check this? Thank you!

```
protected var
    ProdBOMHeader: Record "Production BOM Header";
```	

### Additional context

we need access to global variable ProdBOMHeader from our tableextension to guarantuee we work with the same header as the baseapp
Internal work item: [AB#527646](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527646)

**Comment by alexei-dobriansky** [comment]
Can you please provide a sample code? I see that this ProdBOMHeader is likely global by mistake. The local procedures in that table declare their own ProdBOMHeader instance and confuse the compiler, so I'm inclined to delete this global var.

**Comment by MH1612** [comment]
@alexei-dobriansky  the problem is procedure TestStatus where the baseapp is getting the global ProdBOMHeader variable; 
we call procedure TestStatus from various validates in our own fields in the tableextension and need to add functionality working with the ProdBOMHeader from TestStatus; 
we would prefer to use the tableextension instead of working with subscribers in yet another object; right now we are using a workaround to "mirror" the Get in TestStatus but of course we'd prefer the protected global variable set via procedureTestStatus

**Comment by alexei-dobriansky** [comment]
Thanks for clarification!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22633.
