### ISSUE TITLE
[Event Change Request] Codeunit 80 Sales Post - procedure UpdateQtyToBeInvoicedForReturnReceipt - Event OnBeforeUpdateQtyToBeInvoicedForReturnReceipt

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26365]
### Describe the request

We would like add RemQtyToBeInvoiced, RemQtyToBeInvoicedBase added to the following events.

Original:

```
Codeunit 80 Sales Post - procedure UpdateQtyToBeInvoicedForReturnReceipt - Event OnBeforeUpdateQtyToBeInvoicedForReturnReceipt

        IsHandled := false;
        OnBeforeUpdateQtyToBeInvoicedForReturnReceipt(
            QtyToBeInvoiced, QtyToBeInvoicedBase, TrackingSpecificationExists, SalesLine, ReturnReceiptLine,
            InvoicingTrackingSpecification, QtyToBeInvoiced, QtyToBeInvoicedBase, IsHandled);

```

Change:

```
        IsHandled := false;
        OnBeforeUpdateQtyToBeInvoicedForReturnReceipt(
            QtyToBeInvoiced, QtyToBeInvoicedBase, TrackingSpecificationExists, SalesLine, ReturnReceiptLine,
            InvoicingTrackingSpecification, RemQtyToBeInvoiced, RemQtyToBeInvoicedBase, IsHandled);
```

### Additional context

Wrong Parameter used.

QtyToBeInvoiced and QtyToBeInvoicedBase are doubled. It seem's that the second Set of variables should be used for RemQtyToBeInvoiced and RemQtyToBeInvoicedBase (that's the name of the target parameter variables)
Internal work item: [AB#527647](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527647)

**Comment by RupeshBhandari** [comment]
@haoranpb could this issue be moved to base app issue so that I could create a PR.

**Comment by haoranpb** [comment]
Hi @RupeshBhandari , thanks for reaching out. I believe @alexei-dobriansky can help answer that

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
