### ISSUE TITLE
Codeunit 82 Sales-Post + Print - procedure PrintShip - Change Parameter to var

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26367]
### Describe the request

Hello, we need to change the parameter to var. Can you please check this? Thank you!

```
      // OLD 
    procedure PrintShip(SalesHeader: Record "Sales Header")

    // NEW
    procedure PrintShip(var SalesHeader: Record "Sales Header")

```

### Additional context

Set a Binding on Sales Header.
Internal work item: [AB#527649](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527649)

**Comment by alexei-dobriansky** [comment]
Please explain the purpose. What about PrintInvoice, PrintReceive, PrintCrMemo functions?
If that requires filtering or modification of sales header, we have publishers OnBeforeGetReport, OnBeforePrintShip, OnAfterGetReport

**Comment by SKeiler** [comment]
Hi,

We have no problem if the other procedure will also be expanded. 

In our case more than one Sales Shipment Header is created and we would like to print all of them (therefore we use the binding to save a temp table with all sales shipment's to print). For that we need a Binding on Sales Header-Record. To get the binding "at life", we would like the change, that the SalesHeader-Parameter is set to var.

**Comment by alexei-dobriansky** [comment]
Thanks for clarification

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19985.
