### ISSUE TITLE
[Request-For-External] Codeunit 80 "Sales-Post" - Procedure from Internal to Global

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26368]
### Describe the request

Hello, we need the following currently local procedure to be set to global. Can you please check this? Thank you!

```
local procedure DivideAmount(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; QtyType: Option General,Invoicing,Shipping; SalesLineQty: Decimal; var TempVATAmountLine: Record "VAT Amount Line" temporary; var TempVATAmountLineRemainder: Record "VAT Amount Line" temporary; IncludePrepayments: Boolean)
```

### Additional context

Set Function to Global to call it out of an Event
Internal work item: [AB#527650](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/527650)

**Comment by alexei-dobriansky** [comment]
This local procedure uses global variables such as: RoundingLineInserted, RoundingLineNo, InvoicePostingInterface. They'll be inaccessible after making DivideAmount global.

**Comment by alexei-dobriansky** [comment]
.

**Comment by alexei-dobriansky** [comment]
.

**Comment by SKeiler** [comment]
Hi,

we would like to call DivideAmount ot of an COD80-Subsriver-Event where IncludeSender is Set. We want to change to parameters which are used to call DivideAmount (get it also calced for the Qty. to Ship) and it is not neccessary to copy an critical COD80-procedure. So we need DivideAmount set to global and the IncludeSender-Property activated. In this case we can call DivideAmount out of an COD80-Event in the instance of current posting. 

In COD90 DivideAmount is already set to global!

There is also a Event request to get the IncludeSender-Property activated for relevant Events --> https://github.com/microsoft/ALAppExtensions/issues/26366
