### ISSUE TITLE
[Extensibility Request] Blanket Sales / Purchase Subform Pages

### ISSUE THREAD

**Issue by chrischbo** [microsoft/ALAppExtensions#26370]
### Describe the request

https://github.com/microsoft/ALAppExtensions/issues/26049

It is not fixed in the mentioned build version and it's still missing in the latest available build version 24.1.18924.0

### Additional context

Handle price calculation

**Comment by chrischbo** [comment]
Any news on this? I'm still missing the CurrPage.Update, checked in latest insider build.

Kind regards,
Christian

**Comment by JesperSchulz** [comment]
As this is a extensibility-enhancement, it will ship with the upcoming major release of Business Central (Wave 2 2024). We usually do not backport enhancements for release with the current versions.
