### ISSUE TITLE
Downgrading work item: AB#525527 to BC 20 - "Essential Business Headlines" app

### ISSUE THREAD

**Issue by GrzegorzLewicz** [microsoft/ALAppExtensions#26376]
### BC Idea Link

https://github.com/microsoft/ALAppExtensions/issues/26298

### Description

Hi,

please let me know if I understand correctly the answer to issue 26298:
https://github.com/microsoft/ALAppExtensions/issues/26298

In oder for us to see the code in debugger in the "Essential Business Headlines" app, our customer will need to first upgrade to the newest BC version? Or, is there a chance that we can download the higher version of this app for BC 20? Our customer is currently using v. 20.4.44313.44365 of "Essential Business Headlines" app OnPrem. 

Do you see any alternative to assist the customer before they upgrade the newest BC? 

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea

**Comment by JesperSchulz** [comment]
I'm afraid we won't be backporting changes to version 20.0. But given this is an on-prem installation, can you not create a debuggable version of the app yourself?

**Comment by GrzegorzLewicz** [comment]
Thank you, creating debuggable version of the app works in onprem. I'm sorry, I couldn't test it earlier. Please close this case.
