### ISSUE TITLE
[Event Change Request] Table 39 - Purchase Header need the ability to bypass the confirmation message that is triggered when prepayment has been processed

### ISSUE THREAD

**Issue by achowtc** [microsoft/ALAppExtensions#26374]
### Describe the request

![image](https://github.com/microsoft/ALAppExtensions/assets/34691006/71c60a3b-48b3-4407-a172-8b88b5f1fa42)

Can we add the a IsHandled boolean so we can skip the confirmation message if the Location Code is changed?

### Additional context

Sometimes the location code on the purchase headers will need to be updated because of storage problems in the original final destination. If the process is done via code, the user will get this confirmation for all of the purchase orders they're trying to change into.

If you can add a boolean so we can skip the confirmation, it will save the user a lot of confirmation messages. 
Internal work item: [AB#538693](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538693)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21593.
