### ISSUE TITLE
[Protected var] page 6510 "Item Tracking Lines" - QtyRoundingPerBase

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26378]
### Describe the request

Can you make **QtyRoundingPerBase** accessible via page extensions by making it a protected variable?

### Additional context

We would like to create lot numbers in batch, duplicating some of the AssignLotNo logic, requiring access to QtyRoundingPerBase.
Internal work item: [AB#538697](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538697)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21499.
