### ISSUE TITLE
[Event Change Request] Codeunit 22 "Item Jnl.-Post Line" - Event OnBeforeItemApplnEntryInsert

### ISSUE THREAD

**Issue by Medson99** [microsoft/ALAppExtensions#26372]
### Describe the request

I would like add ItemApplnEntryNo added to the following event.

Orginal:
```al
[IntegrationEvent(false, false)] 
local procedure OnBeforeItemApplnEntryInsert(var ItemApplicationEntry: Record "Item Application Entry"; GlobalItemLedgerEntry: Record "Item Ledger Entry"; OldItemLedgerEntry: Record "Item Ledger Entry") 
begin 
end;
``` 

Change:
```al
[IntegrationEvent(false, false)] 
local procedure OnBeforeItemApplnEntryInsert(var ItemApplicationEntry: Record "Item Application Entry"; GlobalItemLedgerEntry: Record "Item Ledger Entry"; OldItemLedgerEntry: Record "Item Ledger Entry"; var ItemApplnEntryNo: Integer) 
begin 
end;
``` 

### Additional context

In some cases we need to split "Item Application Entry" on 2 or more records. So in next "Item Application Entry" insert we get an error, that record with Entry No. already exists.
Internal work item: [AB#538691](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538691)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21073.
