### ISSUE TITLE
[Protected Var] Page 422 "G/L Balance/Budget" - ClosingEntryFilter and DateFilter

### ISSUE THREAD

**Issue by MCHammerTNP** [microsoft/ALAppExtensions#26383]
### Describe the request

Can the following global variables be made Protected Var on Page 422 "G/L Balance/Budget"

- ClosingEntryFilter
- DateFilter

### Additional context

We need to be able to update them from a Page extension
Internal work item: [AB#538698](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538698)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21326.
