### ISSUE TITLE
[Protected Var] page 5510 "Production Journal"

### ISSUE THREAD

**Issue by innonav-dev** [microsoft/ALAppExtensions#26388]
### Describe the request

Would it be possible to provide the variables

```
        ProdOrder: Record "Production Order";
        ProdOrderLine: Record "Prod. Order Line";
        FlushingFilter: Enum "Flushing Method Filter";
        ProdOrderLineNo: Integer;
```

as protected var?

### Additional context

We could use to access those variables from a page extension. 
Internal work item: [AB#538702](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538702)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21499.
