### ISSUE TITLE
[Protected Var] Page 415 "G/L Account Balance" - PeriodType, AmountType, ClosingEntryFilter, and DebitCreditTotals

### ISSUE THREAD

**Issue by MCHammerTNP** [microsoft/ALAppExtensions#26382]
### Describe the request

Can the following global variables be made protected variables please on Page 415 "G/L Account Balance"

- PeriodType
- AmountType
- ClosingEntryFilter
- DebitCreditTotals

### Additional context

We need to be able to access these variables from a page extension in order to call the SetLines Procedure of the GLBalanceLines sub-page.
Internal work item: [AB#538695](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538695)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21326.
