### ISSUE TITLE
[Public Procedure] codeunit 5708 "Release Transfer Document" - Release

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26380]
### Describe the request

Please make the **Release** procedure in codeunit 5708 "Release Transfer Document" **public** (similar to the Reopen function and other posting codeunits of other application areas)

### Additional context

Please make the **Release** procedure in codeunit 5708 "Release Transfer Document" **public** (similar to the Reopen function and other posting codeunits of other application areas)
Internal work item: [AB#538696](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538696)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21499.
