### ISSUE TITLE
[Protected Var] Page 154 "G/L Account Balance/Budget" - PeriodType, AmountType, and ClosingEntryFilter

### ISSUE THREAD

**Issue by MCHammerTNP** [microsoft/ALAppExtensions#26384]
### Describe the request

Can the following global variables be made Protected Vars on Page 154 "G/L Account Balance/Budget" please

- PeriodType
- AmountType
- ClosingEntryFilter

### Additional context

We need to be able to access then from a page extension and to be able to call the SetLines procedure against the part-page GLBalanceLines.  
Internal work item: [AB#538700](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538700)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21326.
