### ISSUE TITLE
[Public Procedure] codeunit 56 "Sales - Calc Discount By Type"

### ISSUE THREAD

**Issue by innonav-dev** [microsoft/ALAppExtensions#26393]
### Describe the request

Is it possible to set the protection level to public fpr procedure CustInvDiscRecExists like following:

`procedure CustInvDiscRecExists(InvDiscCode: Code[20]): Boolean`

### Additional context

It is an resulting necessity for an existing Event Request.
Internal work item: [AB#538731](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538731)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21453.
