### ISSUE TITLE
[Protected Var] Report 31244 "Fixed Asset - Book Value 1 CZF"

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#26397]
### Describe the request

Please change the following global variables to protected global variables:
-GroupHeadLine
-GroupTotals

### Additional context

We need use variables.
Internal work item: [AB#538722](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538722)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21998.
