### ISSUE TITLE
[Event Request] codeunit 4810 IntrastatReportManagement - Extra events for setup

### ISSUE THREAD

**Issue by PunkyGP** [microsoft/ALAppExtensions#26398]
### Describe the request

Dear Team,

is it possible to add some extra Event to the IntrastatReportManagement Codeunit please?

_Our proposal:_

    procedure GetIntrastatBaseCountryCode(JobLedgerEntry: Record "Job Ledger Entry") CountryCode: Code[10]
    var
        IntrastatReportSetup: Record "Intrastat Report Setup";
        Job: Record Job;
        // ADDED
        IsHandled: Boolean;
        // ADDED
    begin
        IntrastatReportSetup.Get();

        // ADDED
        IsHandled := false;
        OnBeforeGetIntrastatBaseCountryCodeFromJLE(JobLedgerEntry, IntrastatReportSetup, CountryCode, IsHandled);
        if IsHandled then
            exit(CountryCode);
        // ADDED

    procedure GetIntrastatBaseCountryCode(FALedgerEntry: Record "FA Ledger Entry") CountryCode: Code[10]
    var
        IntrastatReportSetup: Record "Intrastat Report Setup";
        PurchInvHeader: Record "Purch. Inv. Header";
        PurchCrMemoHdr: Record "Purch. Cr. Memo Hdr.";
        SalesInvHeader: Record "Sales Invoice Header";
        SalesCrMemoHeader: Record "Sales Cr.Memo Header";
        // ADDED
        IsHandled: Boolean;
         // ADDED
    begin
        IntrastatReportSetup.Get();

        // ADDED
        IsHandled := false;
        OnBeforeGetIntrastatBaseCountryCodeFromFLE(FALedgerEntry, IntrastatReportSetup, CountryCode, IsHandled);
        if IsHandled then
            exit(CountryCode);
        // ADDED
        CountryCode := '';

    procedure GetCompanyVATRegNo(): Text[50]
    var
        CompanyInformation: Record "Company Information";
        IntrastatReportSetup: Record "Intrastat Report Setup";
    begin
        CompanyInformation.Get();
        if not IntrastatReportSetup.Get() then
            exit(CompanyInformation."VAT Registration No.");     
        // ADDED   
        OnGetCompanyVATRegNo_AfterGetIntrastatReportSetup(CompanyInformation, IntrastatReportSetup);
        // ADDED
        exit(
          GetVATRegNo(
            CompanyInformation."Country/Region Code", CompanyInformation."VAT Registration No.",
            IntrastatReportSetup."Company VAT No. on File"));
    end;

    procedure ExportWithDataExch(IntrastatReportHeader: Record "Intrastat Report Header"; ExportType: Integer)
    var
        DataExch1: Record "Data Exch.";
        DataExch2: Record "Data Exch.";
        IntrastatReportSetup: Record "Intrastat Report Setup";
        TempBlob: Codeunit "Temp Blob";
        Selection: Integer;
        IsHandled: Boolean;
        FileName: Text;
        ReceptFileName: Text;
        ShipmentFileName: Text;
        ZipFileName: Text;
    begin
        IsHandled := false;
        OnBeforeExportIntrastatHeader(IntrastatReportHeader, IsHandled);
        if IsHandled then
            exit;

        if IntrastatReportHeader.Reported then
            if not Confirm(PeriodAlreadyReportedQst) then
                exit;

        OnBeforeDefineFileNames(IntrastatReportHeader, FileName, ReceptFileName, ShipmentFileName, ZipFileName, IsHandled);
        if not IsHandled then begin
            FileName := StrSubstNo(FileNameLbl, IntrastatReportHeader."Statistics Period");
            ReceptFileName := StrSubstNo(ReceptFileNameLbl, IntrastatReportHeader."Statistics Period");
            ShipmentFileName := StrSubstNo(ShipmentFileNameLbl, IntrastatReportHeader."Statistics Period");
            ZipFileName := StrSubstNo(ZipFileNameLbl, IntrastatReportHeader."Statistics Period");
        end;

        IntrastatReportSetup.Get();
        // ADDED   
        OnExportWithDataExch_AfterGetIntrastatReportSetup(IntrastatReportSetup, IntrastatReportHeader);
        // ADDED   
        if IntrastatReportSetup."Split Files" then begin
            IntrastatReportSetup.TestField("Data Exch. Def. Code - Receipt");
            IntrastatReportSetup.TestField("Data Exch. Def. Code - Shpt.");
            FileName := ReceptFileName;

### Additional context

Currently we are implementing some new intrastat functions and we need to have a different IntrastatReportSetup depending of the responsibility center.
So instead of updating the setup before executing, we would like to do this inline with a new event.

Hereby we don't need to manipulate the setup and we can act differently per responsibility center.

For example the DataExchDefCode. One division can have a different setup then the other.

Thanks in advance,
Gunter
Internal work item: [AB#538723](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538723)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21140.
