### ISSUE TITLE
[Event Request] codeunit 5510 Production Journal Mgt - OnBeforeDataHasChanged

### ISSUE THREAD

**Issue by Hilbekale** [microsoft/ALAppExtensions#26399]
### Describe the request

Hello,

we need an event to handle the return value of the function DataHasChanged. This will allow us to block the 
`LeaveForm := Confirm(Text001, true); `
in specific situations.

```
local procedure DataHasChanged(TemplateName: Code[10]; BatchName: Code[10]; ProdOrderNo: Code[20]; ProdOrderLineNo: Integer): Boolean
    var
        ItemJnlLine2: Record "Item Journal Line";
        ReservEntry: Record "Reservation Entry";
        HasChanged: Boolean;
    begin
        OnBeforeDataHasChanged(TemplateName, BatchName, ProdOrderNo, ProdOrderLineNo, HasChanged, IsHandled);
        if IsHandled then
            exit(HasChanged);

        ItemJnlLine2.Reset();
        ItemJnlLine2.SetRange("Journal Template Name", TemplateName);
        ItemJnlLine2.SetRange("Journal Batch Name", BatchName);
        ItemJnlLine2.SetRange("Order Type", ItemJnlLine2."Order Type"::Production);
        ItemJnlLine2.SetRange("Order No.", ProdOrderNo);
        if ProdOrderLineNo <> 0 then
            ItemJnlLine2.SetRange("Order Line No.", ProdOrderLineNo);
        if ItemJnlLine2.Find('-') then
            repeat
                if ItemJnlLine2."Changed by User" then
                    exit(true);
                if ReservEntryExist(ItemJnlLine2, ReservEntry) then
                    exit(true);
            until ItemJnlLine2.Next() = 0;

        HasChanged := false;
        OnAfterDataHasChanged(ItemJnlLine2, ProdOrderLineNo, HasChanged);
        exit(HasChanged);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeDataHasChanged(emplateName: Code[10]; BatchName: Code[10]; ProdOrderNo: Code[20]; ProdOrderLineNo: Integer; var HasChanged: Boolean; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

The Production Journal is used by many users. Sometimes it will be just checked without anychanges. However the confirm of leaving the production journal always occurs if you work with item tracking and reservations.

```
if ReservEntryExist(ItemJnlLine2, ReservEntry) then
    exit(true);
```

This also happens if the user does not changed anything. Therefore we would like to skip the confirm in some situations. We do not want to subscribe to OnBeforeRunProductionJnl(ToTemplateName, ToBatchName, ProdOrder, ActualLineNo, PostingDate, IsHandled) because we do not want to change the general behaviour of the journal and to avoid problems with future changes on this code.

It would be also ok if the event is not created an alternative function (e.g. setup) is applied for this problem. 
Internal work item: [AB#538719](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538719)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21140.
