### ISSUE TITLE
[Protected var] page 5530 "Item Availability by Event"

### ISSUE THREAD

**Issue by innonav-dev** [microsoft/ALAppExtensions#26394]
### Describe the request

Would it be possible, to add an protected var for

`TempInvtPageData: Record "Inventory Page Data" temporary;`

on page 5530 "Item Availability by Event"?

### Additional context

We could use a possibility to have access from an extension.
Internal work item: [AB#538727](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538727)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21453.
