### ISSUE TITLE
[Event Request] Codeunit 5777 OnAfterPurchaseLineVerifyChange and OnAfterProdOrderLineVerifyChange

### ISSUE THREAD

**Issue by GuntherGebauer** [microsoft/ALAppExtensions#2639]
In Codeunit 5777 all VerifyChange Event trigger have Parameters with recordref (e.g. OnAfterServiceLineVerifyChange, OnAfterSalesLineVerifyChange), OnAfterPurchaseLineVerifyChange and OnAfterProdOrderLineVerifyChange submit Parameters as records.

Please Change the Parameters of OnAfterPurchaseLineVerifyChange and OnAfterProdOrderLineVerifyChange to recordref as well, so that VerifyFieldNotChanged can directly be called from an Extension with the submitted parameters:

old:
OnAfterPurchaseLineVerifyChange(NewPurchLine,OldPurchLine);
New:
OnAfterPurchaseLineVerifyChange(NewRecRef,OldRecRef););

**Comment by AlexanderYakunin** [comment]
I can only add recref parameters to existing events

**Comment by GuntherGebauer** [comment]
why are the calls OnAfterVerifyChange different for different tables, they should all have the same structure either records or recordrefs - otherwise the Extension must do different programming with different tables, what is neither case logical

**Comment by AlexanderYakunin** [comment]
We cannot change event signatures in production version. You suggestion is breaking change, it can be done for future version only.
