### ISSUE TITLE
Functions Expose Request

### ISSUE THREAD

**Issue by srinivasGangadhara** [Microsoft/ALAppExtensions#264]
Hi,
Please expose functions for below objects 

Object --- Report 5899 Calculate Inventory Value .
Functions----
     SetItemJnlLine  
     InitializeRequest

Object --- Report 5706 Create Stockkeeping Unit
Functions ---- 
      InitializeRequest

Object --- Codeunit 414 Release Sales Document
Functions ---- 
                     PerformManualCheckAndRelease

thanks!
srinivas

**Comment by JesperSchulz** [comment]
Good news! In a recent fix pack, we've exposed many public, safe functions. The following will be fixed as part of that pack in the upcoming minor and major update: SetItemJnlLine, InitializeRequest (x2).
PerformManualCheckAndRelease was not part of the fix pack, but PerformManualRelease is exposed. Will that not do? I will also expose PerformManualCheckAndRelease for the next major release.
