### ISSUE TITLE
Codeunit 225 "Gen. Jnl.-Apply" events

### ISSUE THREAD

**Issue by johnodonovan4ps** [microsoft/ALAppExtensions#26400]
### Describe the request

Hello,

On behalf of 4PS I would like to request extra integration events be added to the  "Gen. Jnl.-Apply" Codeunit please.

We need an event OnAfterUpdateVendLedgEntry to be called at the end of the UpdateVendLedgEntry procedure :
//New Event Requested
OnAfterUpdateVendLedgEntry(GenJnlLine, VendLedgEntry);

[IntegrationEvent(false, false)]
local procedure OnAfterUpdateVendLedgEntry(var GenJournalLine: Record "Gen. Journal Line"; var VendorLedgerEntry: Record "Vendor Ledger Entry");
    begin
    end;
    
We also need an event OnBeforeApplyVendorLedgerEntryAPIValidateAmount to be called in the ApplyVendorLedgerEntryAPI procedure before the Amount field is validated:
                if (GenJnlLine."Bal. Account Type" = GenJnlLine."Bal. Account Type"::Customer) or (GenJnlLine."Bal. Account Type" = GenJnlLine."Bal. Account Type"::Vendor) then
                    GenJnlLine.Amount := -GenJnlLine.Amount;
                    
                //New Event Requested  
                OnBeforeApplyVendorLedgerEntryAPIValidateAmount(GenJnlLine);
                
                GenJnlLine.Validate(Amount);
    
    [IntegrationEvent(false, false)]
    local procedure OnBeforeApplyVendorLedgerEntryAPIValidateAmount(var GenJournalLine: Record "Gen. Journal Line");
    begin
    end;

and a similar event in the ApplyVendorLedgerEntry procedure also called before the Amount field is validated :
                    if ("Bal. Account Type" = "Bal. Account Type"::Customer) or ("Bal. Account Type" = "Bal. Account Type"::Vendor) then
                        Amount := -Amount;

                    //New Event Requested
                    OnBeforeApplyVendorLedgerEntryValidateAmount(GenJnlLine);

                    Validate(Amount);

    //4PSUK Event Request
    [IntegrationEvent(false, false)]
    local procedure OnBeforeApplyVendorLedgerEntryValidateAmount(var GenJournalLine: Record "Gen. Journal Line");
    begin
    end;

### Additional context

We need to update extra amounts on the General Journal Line from the applied Vendor Ledger Entry and need the extra events  to be added to the "Gen. Jnl.-Apply" Codeunit to support this .
Internal work item: [AB#538718](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538718)

**Comment by johnodonovan4ps** [comment]
We also need an event added to the SetVendApplIdAPI procedure after the Remaining Amount is set:

        TempApplyingVendorLedgerEntry."Currency Code" := GenJournalLine."Currency Code";
        TempApplyingVendorLedgerEntry.Amount := GenJournalLine.Amount;
        TempApplyingVendorLedgerEntry."Remaining Amount" := GenJournalLine.Amount;

        //New Event Required
        OnBeforeSetVendApplIdAPICheckPostingDate(TempApplyingVendorLedgerEntry, GenJournalLine, VendorLedgerEntry);

        if TempApplyingVendorLedgerEntry."Posting Date" < VendorLedgerEntry."Posting Date" then
            Error(
                EarlierPostingDateErr, TempApplyingVendorLedgerEntry."Document Type", TempApplyingVendorLedgerEntry."Document No.",
                VendorLedgerEntry."Document Type", VendorLedgerEntry."Document No.");


[IntegrationEvent(false, false)]
 local procedure OnBeforeSetVendApplIdAPICheckPostingDate(var TempApplyingVendorLedgerEntry: Record "Vendor Ledger Entry"; GenJournalLine: Record "Gen. Journal Line"; var VendorLedgerEntry: Record "Vendor Ledger Entry")    
    begin
    end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21140.
