### ISSUE TITLE
[Request for External] Report 20 "Calc. and Post VAT Settlement" - Protected variables

### ISSUE THREAD

**Issue by iamcgomes** [microsoft/ALAppExtensions#26414]
### Describe the request

Could you please change the scope of the global variables **"EntrdStartDate"** and  **"EnteredEndDate"** to protected in **Report 20 "Calc. and Post VAT Settlement"**?

Current
```AL
var
    EntrdStartDate: Date;
    EnteredEndDate: Date;
```

Requested
```AL
protected var
    EntrdStartDate: Date;
    EnteredEndDate: Date;
```

### Additional context

We need to access the global variables "EntrdStartDate" and "EnteredEndDate" from the Report Extension.
Internal work item: [AB#538706](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538706)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21326.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21326.
