### ISSUE TITLE
[Protected var] page 1328 "Purch. Order From Sales Order" - OrderNo

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26419]
### Describe the request

Can you please make variable '**OrderNo**' in page 1328 "Purch. Order From Sales Order" available as **protected** variable?

### Additional context

We'd like to get access to the originating sales order no on page 1328 "Purch. Order From Sales Order"
Internal work item: [AB#534606](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534606)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
