### ISSUE TITLE
[Event Request] Table 27 - OnBeforeCheckStdCostWksh

### ISSUE THREAD

**Issue by Aize-S** [microsoft/ALAppExtensions#26410]
### Describe the request

In two of the three procedures called from CheckJournalsAndWorksheets(...) an _OnBefore..._ event was implemented. In CheckStdCostWksh this is missing. Please add.

```
    local procedure CheckStdCostWksh(CurrentFieldNo: Integer)
    var
        StandardCostWorksheet: Record "Standard Cost Worksheet";
        IsHandled: Boolean;
    begin
        // New Event >>
        if "No." = '' then
            exit;

        IsHandled := false;
        OnBeforeCheckStdCostWksh(Rec, CurrentFieldNo, IsHandled);
        if IsHandled then
            exit;
        // New Event <<

        StandardCostWorksheet.Reset();
        StandardCostWorksheet.SetRange(Type, StandardCostWorksheet.Type::Item);
        StandardCostWorksheet.SetRange("No.", "No.");
        if not StandardCostWorksheet.IsEmpty() then
            if CurrentFieldNo = 0 then
                Error(Text023, TableCaption(), "No.", StandardCostWorksheet.TableCaption());
    end;

    // New Event >>
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckStdCostWksh(Item: Record Item; CurrentFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;
    // New Event <<
```

### Additional context

We want this functionality to handle CheckJournalsAndWorksheets(...) in the same way for all underlying checks.
Internal work item: [AB#538710](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538710)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21073.
