### ISSUE TITLE
[Event Request] Report selections: allow multiple prints with same Report ID

### ISSUE THREAD

**Issue by rmurriero-alterna** [microsoft/ALAppExtensions#26423]
### Describe the request

Hi, we need to be able to print the same report multiple times via Report Selections. By default the same Usage-ReportID pair is excluded if it exists more than once. We would need to add custom logic that allows multiple printing of the same report.

The logic is contained in the object **Table 77 Report Selections**, procedure **SelectTempReportSelectionsToPrint**.

```
procedure SelectTempReportSelectionsToPrint(var TempReportSelections: Record "Report Selections" temporary; var TempNameValueBuffer: Record "Name/Value Buffer" temporary; WithCheck: Boolean; ReportUsage: Enum "Report Selection Usage"; TableNo: Integer)
    var
        TempReportSelectionsAccount: Record "Report Selections" temporary;
        AccountNo: Code[20];
        LastSequence: Code[10];
    begin
        if TempNameValueBuffer.FindSet() then
            repeat
                AccountNo := CopyStr(TempNameValueBuffer.Name, 1, MaxStrLen(AccountNo));
                TempReportSelectionsAccount.Reset();
                TempReportSelectionsAccount.DeleteAll();
                SelectTempReportSelections(TempReportSelectionsAccount, AccountNo, WithCheck, ReportUsage, TableNo);
                if TempReportSelectionsAccount.FindSet() then
                    repeat
                        LastSequence := GetLastSequenceNo(TempReportSelections, ReportUsage);
                        // ---- Start old version ---->
                        if not HasReportWithUsage(TempReportSelections, ReportUsage, TempReportSelectionsAccount."Report ID") then begin
                        // <---- End old version ----
                            TempReportSelections := TempReportSelectionsAccount;
                            if LastSequence = '' then
                                TempReportSelections.Sequence := '1'
                            else
                                TempReportSelections.Sequence := IncStr(LastSequence);
                            TempReportSelections.Insert();
                        end;
                    until TempReportSelectionsAccount.Next() = 0;
            until TempNameValueBuffer.Next() = 0;
    end;
```

To get the expected result you could save the current logic in a variable, check the value of that variable for insertion, with the addition of an event just before the check, where we can change the value of the variable.

```
procedure SelectTempReportSelectionsToPrint(var TempReportSelections: Record "Report Selections" temporary; var TempNameValueBuffer: Record "Name/Value Buffer" temporary; WithCheck: Boolean; ReportUsage: Enum "Report Selection Usage"; TableNo: Integer)
    var
        TempReportSelectionsAccount: Record "Report Selections" temporary;
        AccountNo: Code[20];
        LastSequence: Code[10];
        // ---- New variables ---->
        InsertReportSelection: Boolean;
        // <--- End new variables ----
    begin
        if TempNameValueBuffer.FindSet() then
            repeat
                AccountNo := CopyStr(TempNameValueBuffer.Name, 1, MaxStrLen(AccountNo));
                TempReportSelectionsAccount.Reset();
                TempReportSelectionsAccount.DeleteAll();
                SelectTempReportSelections(TempReportSelectionsAccount, AccountNo, WithCheck, ReportUsage, TableNo);
                if TempReportSelectionsAccount.FindSet() then
                    repeat
                        LastSequence := GetLastSequenceNo(TempReportSelections, ReportUsage);
                        // ---- Start new version ---->
                        InsertReportSelection := not HasReportWithUsage(TempReportSelections, ReportUsage, TempReportSelectionsAccount."Report ID");
                        OnBeforeCheckInsertReportSelectionToPrint(TempReportSelections, ReportUsage, TempReportSelectionsAccount, InsertReportSelection);
                        if InsertReportSelection then begin
                        // <---- End new version ----
                            TempReportSelections := TempReportSelectionsAccount;
                            if LastSequence = '' then
                                TempReportSelections.Sequence := '1'
                            else
                                TempReportSelections.Sequence := IncStr(LastSequence);
                            TempReportSelections.Insert();
                        end;
                    until TempReportSelectionsAccount.Next() = 0;
            until TempNameValueBuffer.Next() = 0;
    end;

...

[IntegrationEvent(false,false)]
local procedure OnBeforeCheckInsertReportSelectionToPrint(var TempReportSelections: Record "Report Selections" temporary; ReportUsage: Enum "Report Selection Usage"; TempReportSelectionsAccount: Record "Report Selections" temporary; var InsertReportSelection: Boolean)
begin
end;
```

**Alternatively**, you could directly modify the HasReportWithUsage method to handle the entire Report Selection record as a parameter (and not just the ID), adding an event before FindFirst(), allowing us to add our custom filters to the source record.

```
local procedure HasReportWithUsage(var TempReportSelectionsSource: Record "Report Selections" temporary; ReportUsage: Enum "Report Selection Usage"; TempReportSelectionsAccount: Record "Report Selections" temporary): Boolean
    var
        TempReportSelections: Record "Report Selections" temporary;
    begin
        TempReportSelections.Copy(TempReportSelectionsSource, true);
        TempReportSelections.SetRange(Usage, ReportUsage);
        TempReportSelections.SetRange("Report ID", ReportID);
        OnBeforeHasReportWithUsageFindReportSelections(TempReportSelectionsSource, ReportUsage, TempReportSelectionsAccount);
        exit(TempReportSelections.FindFirst());
    end;

...

[IntegrationEvent(false,false)]
local procedure OnBeforeHasReportWithUsageFindReportSelections(var TempReportSelectionsSource: Record "Report Selections" temporary; ReportUsage: Enum "Report Selection Usage"; TempReportSelectionsAccount: Record "Report Selections" temporary)
begin
end;
```

### Additional context

A custom extension adds a report capable of printing documents in different ways, by modifying parameters in the "Report Selections" record linked to the document. At the moment, if the customer wants to print the document through the custom report in two different ways with our same custom report, the aforementioned standard logic prevents it from working.
Internal work item: [AB#534602](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534602)

**Comment by Groenbech96** [comment]
Can you write some custom logic on top that calls this twice? If you need two prints?

**Comment by rmurriero-alterna** [comment]
> Can you write some custom logic on top that calls this twice? If you need two prints?

Unfortunately, no... The call to this procedure is a consequence of the standard "Print" button present in all documents connected to the report selection. 

Assuming it is possible to replicate the call to the print procedure, the standard report selection method would still return the first report both times, and not both of those set, with the consequence of printing the first allowed report twice.

Replicating the entire standard report selection block and custom adding a button for every single existing document (and non-existing ones, since our extension also allows the printing of custom documents with a setup), makes no sense.

The addition of an event in the report selection, which allows you to add custom logic to the decision on whether or not to use a report selection record in printing, would allow us to "apply an extra filter" to the record, and manage all the cases.

---

I try to add further context on our extension: we have added a Code field to the Report Selection record, the need would be to modify the grouping that the standard logic uses in printing (Report ID) and manage the pair (Report ID, custom Code field), so as to allow the printing of the same report in different report selection records, as long as our custom field is different from one of those already inserted.

**Comment by Groenbech96** [comment]
You have multiple report selection records for the same report? 
And the standard print always pick the first one, is that correctly understood?  

Seems to me that we should look into supporting multiple report selections when printing, like your scenario.

**Comment by rmurriero-alterna** [comment]
> You have multiple report selection records for the same report? And the standard print always pick the first one, is that correctly understood?
> 
> Seems to me that we should look into supporting multiple report selections when printing, like your scenario.

That's right, our documents might have multiple Report Selection records with the same Report ID, and we want to print both of them. At the moment, since you have implemented a logic whereby only one record per Report ID is added to the list of "records to print", this is not possible.

Since the report selection allows the insertion of multiple records for the same document, even if the Report ID is the same, yes: I was hoping that this type of functionality would be supported.

**Comment by Groenbech96** [comment]
Super. I created an internal work item for us to track this effort. AB#551054
I want it to be build in the design rather than doing it as an event. 
Will close this request as non-planned.
