### ISSUE TITLE
Primary Key 7002 Sales price

### ISSUE THREAD

**Issue by TxusMoyano** [microsoft/ALAppExtensions#2642]
In BC / AL Extensions, we need to include some extension fields in the Sales Price functionality, so we have to change the primary key of the "7002 Sales Price" table. There is no way to make this change, is that correct? Is there a way to solve it?

**Comment by AlexanderYakunin** [comment]
We cannot change primary keys for any table in extension.

**Comment by ikoletic** [comment]
This seems like a product suggestion already added and voted on in [BC Ideas](https://experience.dynamics.com/ideas/idea/?ideaid=5a2cfc87-1f52-e911-b047-0003ff68d113). Please vote for this there.
