### ISSUE TITLE
[Event Request] Table Job: Add "OnBeforeUpdateSellToCust" in local procedure UpdateSellToCust

### ISSUE THREAD

**Issue by someC0d3r** [microsoft/ALAppExtensions#26420]
Hello.

Please add an event before executing the procedure 'UpdateSellToCust' in table 167 Job.

Example:
```al
local procedure UpdateSellToCust(ContactNo: Code[20])
var
    Customer: Record Customer;
    Contact: Record Contact;
    ContactBusinessRelation: Record "Contact Business Relation";
    ContactBusinessRelationFound: Boolean;
    IsHandled: Boolean;
begin
    OnBeforeUpdateSellToCust(Rec, ContactNo, IsHandled);
    if IsHandled then
        exit;
    [...]
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateSellToCust(var Job: Record Job; var ContactNo: Code[20]; var IsHandled: Boolean)
begin
end;
```

Diff:

![image](https://github.com/microsoft/ALAppExtensions/assets/88825803/76678dd6-0cd8-452e-abe0-048327868fd0)

### Additional context

We need to handle this procedure as there should be a possibility for us to enter a "Sell-to Contact No." without having a customer at the time. Unfortunately our process results in an error because of the new procedure call from the validation of "Sell-to Contact No." - which was introduced with BC24.0.
An event would help us to better control the handling between Sell-to Contact & Customer regarding our solution.
Internal work item: [AB#534610](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534610)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
