### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - New events OnBeforeLinkSalesDocWithOpportunity (BaseApp 24.0)

### ISSUE THREAD

**Issue by tg-navcom** [microsoft/ALAppExtensions#26430]
### Describe the request

Table 36 "Sales Header"
Please add new event `OnBeforeLinkSalesDocWithOpportunity`
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeLinkSalesDocWithOpportunity(var SalesHeader: Record "Sales Header"; OldOpportunityNo: Code[20]; var IsHandled: Boolean)
    begin
    end;
```

Change:
```al
    procedure LinkSalesDocWithOpportunity(OldOpportunityNo: Code[20])
    var
        SalesHeader: Record "Sales Header";
        Opportunity: Record Opportunity;
+       IsHandled: Boolean;
    begin
+       IsHandled := false;
+       OnBeforeLinkSalesDocWithOpportunity(Rec, OldOpportunityNo, IsHandled);
+       if IsHandled then
+           exit;

        if "Opportunity No." <> OldOpportunityNo then begin
            if "Opportunity No." <> '' then
```

### Additional context

We need overwrite default procedure `LinkSalesDocWithOpportunity`, because customer use non-standard linking opportunities with sales quotes and orders.
Internal work item: [AB#534604](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534604)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
