### ISSUE TITLE
[Event Parameter Change Request] table 81 "Gen. Journal Line" - field "Currency Code" trigger OnValidate()

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#26443]
### Describe the request

    if "Currency Code" <> '' then begin
      CheckCurrencyForEmployee(
          ("Bal. Account Type" = "Bal. Account Type"::Employee) or ("Account Type" = "Account Type"::Employee));
      GetCurrency();
      if ("Currency Code" <> xRec."Currency Code") or
         ("Posting Date" <> xRec."Posting Date") or
         (CurrFieldNo = FieldNo("Currency Code")) or
         ("Currency Factor" = 0)
      then begin
          **//--> event parameter change "var CurrExchRate" request
          OnValidateCurrencyCodeOnBeforeUpdateCurrencyFactor(Rec, CurrExchRate);
          **//<-- event parameter change "var CurrExchRate" request
          "Currency Factor" := CurrExchRate.ExchangeRate("Posting Date", "Currency Code");
      end;
    end else
      "Currency Factor" := 0;
    Validate("Currency Factor");

    **//--> event parameter change "var CurrExchRate" request
    [IntegrationEvent(false, false)]
    local procedure OnValidateCurrencyCodeOnBeforeUpdateCurrencyFactor(var GenJournalLine: Record "Gen. Journal Line"; **var** CurrExchRate: Record "Currency Exchange Rate")
    begin
    end;
    **//<-- event parameter change "var CurrExchRate" request

### Additional context

In Turkish localization, it is necessary to make a calculation.
Internal work item: [AB#534590](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534590)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20597.
