### ISSUE TITLE
[Event Request] Table 36 "Sales Header" - UpdateSellToCust - OnUpdateSellToCustOnBeforeValidateBillToContactNo

### ISSUE THREAD

**Issue by viktorhartlieb** [microsoft/ALAppExtensions#26441]
### Describe the request

1. In procedure UpdateSellToCust new event OnUpdateSellToCustOnBeforeValidateBillToContactNo
```al
procedure UpdateSellToCust(ContactNo: Code[20])
begin
 ...
+     IsHandled:= false;
+     OnUpdateSellToCustOnBeforeValidateBillToContactNo(Rec, IsHandled);
+     if not IsHandled then
         if ("Sell-to Customer No." = "Bill-to Customer No.") or
           ("Bill-to Customer No." = '')
        then
            Validate("Bill-to Contact No.", "Sell-to Contact No.");

end;

+    [IntegrationEvent(false, false)]
+    local procedure OnUpdateSellToCustOnBeforeValidateBillToContactNo(var SalesHeader: Record "Sales Header"; var IsHandled: Boolean)
+    begin
+    end;
``` 

### Additional context

On Change of  Sell-To Contact No., do not change Bill to-Contact No.
Call by: 
```AL
 field(5052; "Sell-to Contact No."  ......
             if ("Sell-to Contact No." <> xRec."Sell-to Contact No.") then
                    UpdateSellToCust("Sell-to Contact No.");
```
Internal work item: [AB#534589](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534589)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21460.
