### ISSUE TITLE
[Event Request] Codeunit 5802 "Inventory Posting To G/L" - Change OnBeforeGetInvPostingGroupCode (BaseApp 24.0)

### ISSUE THREAD

**Issue by tg-navcom** [microsoft/ALAppExtensions#26440]
### Describe the request

Codeunit 5802 "Inventory Posting To G/L"
Please add `IsHandled` to `OnBeforeGetInvPostingGroupCode`:
```al
    [IntegrationEvent(false, false)]
-   local procedure OnBeforeGetInvPostingGroupCode(var ValueEntry: Record "Value Entry"; var InvPostingGroupCode: Code[20])
+   local procedure OnBeforeGetInvPostingGroupCode(var ValueEntry: Record "Value Entry"; var InvPostingGroupCode: Code[20]; var IsHandled: Boolean)
    begin
    end;
```

Change in `GetInvPostingGroupCode`:
```al
    local procedure GetInvPostingGroupCode(ValueEntry: Record "Value Entry"; WIPInventory: Boolean; InvPostingGroupCode: Code[20]): Code[20]
    var
        Item: Record Item;
+       IsHandled: Boolean;
    begin
        if WIPInventory then begin
-           OnBeforeGetInvPostingGroupCode(ValueEntry, InvPostingGroupCode);
+           OnBeforeGetInvPostingGroupCode(ValueEntry, InvPostingGroupCode, IsHandled);
+           if IsHandled then
+               exit(InvPostingGroupCode);
            if (ValueEntry."Source Type" = ValueEntry."Source Type"::Item) and (ValueEntry."Source No." <> ValueEntry."Item No.") then begin
                Item.SetLoadFields("Inventory Posting Group");
                if Item.Get(ValueEntry."Source No.") then
                    exit(Item."Inventory Posting Group");
            end;
        end;

        exit(InvPostingGroupCode);
    end;
```

### Additional context

Allow to change Inventory Posting Group in WIP cost posting.
Adding an `IsHandle` along with returning an `InvPostingGroupCode` is a clean way to achieve this.
Internal work item: [AB#534591](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534591)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19932.
