### ISSUE TITLE
[Event Parameter Request] table 37 "Sales Line" - field "VAT Prod. Posting Group" trigger OnValidate()

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#26444]
### Describe the request

    IsHandled := FALSE;
    **//--> event parameter "xRec, SalesHeader" request
    OnValidateVATProdPostingGroupOnBeforeUpdateUnitPrice(Rec, xRec, SalesHeader, VATPostingSetup, IsHandled);
    **//<-- event parameter "xRec, SalesHeader" request
    if not IsHandled then
        if SalesHeader."Prices Including VAT" and (Type in [Type::Item, Type::Resource]) then
            Validate("Unit Price",
                Round(
                    "Unit Price" * (100 + "VAT %") / (100 + xRec."VAT %"),
            Currency."Unit-Amount Rounding Precision"));

    **//--> event parameter "xRec, SalesHeader" request
    [IntegrationEvent(false, false)]
    local procedure OnValidateVATProdPostingGroupOnBeforeUpdateUnitPrice(var SalesLine: Record "Sales Line"; xSalesLine: Record "Sales Line"; SalesHeader: Record "Sales Header"; VATPostingSetup: Record "VAT Posting Setup"; var IsHandled: Boolean)
    begin
    end;
    **//<-- event parameter "xRec, SalesHeader" request

### Additional context

In Turkish localization, it is necessary to make a calculation.
Internal work item: [AB#534592](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534592)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20597.
