### ISSUE TITLE
[Change Request] report 6697 "Create Ret.-Related Documents"

### ISSUE THREAD

**Issue by gordanarakovac** [microsoft/ALAppExtensions#26445]
### Describe the request

Could you please move the TempRetRelDoc variable to be set as protected?

    var
        Vend: Record Vendor;
        CopyDocMgt: Codeunit "Copy Document Mgt.";

    protected var
        TempRetRelDoc: Record "Returns-Related Document" temporary;    
        POPurchHeader: Record "Purchase Header";
        PROPurchHeader: Record "Purchase Header";
        SOSalesHeader: Record "Sales Header";
        SROSalesHeader: Record "Sales Header";
        CreatePRO: Boolean;
        CreatePO: Boolean;
        CreateSO: Boolean;
        VendorNo: Code[20];

### Additional context

We need this variable to be protected, because we want to create other types of documents and we need to insert other documents into that table.
Internal work item: [AB#534677](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534677)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19985.
