### ISSUE TITLE
[Bug]: German Translation misttake

### ISSUE THREAD

**Issue by MLadewig78** [microsoft/ALAppExtensions#26459]
### Describe the issue

The German translation can't be understand
![image](https://github.com/microsoft/ALAppExtensions/assets/54710141/82a2e527-15e2-4484-ba81-a2c3f7e86625)

Current Value is:
Die Artikel wurden kommissioniert. Wenn Sie Zeile %1 stornieren machen, verbleiben die Artikel im Versandbereich, bis sie eingelagert werden.\M??chten Sie den Warenausgang wirklich stornieren machen?

Value should be:
Die Artikel wurden kommissioniert. Wenn Sie die Zeile %1 stornieren, verbleiben die Artikel im Versandbereich, bis sie eingelagert werden.\M??chten Sie den Warenausgang wirklich stornieren?

### Expected behavior

On undo a shipment of a posted SalesShipment the second Message in German are not readable.

### Steps to reproduce

Create a Sales Shipment with a Outgoing Warehouse Shipment
An undo the shipment from the posted Sales Shipment

### Additional context

The Translation of this Variabl??e must be Changed
![image](https://github.com/microsoft/ALAppExtensions/assets/54710141/8d612e9e-7b6e-4889-9d81-5c5a234b9257)

### I will provide a fix for a bug

- [X] I will provide a fix for a bug
Internal work item: [AB#536533](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536533)

**Comment by JesperSchulz** [comment]
This is normally not the right place to report such issues. But I will make an exception and will send a bug to our translation team 😊
