### ISSUE TITLE
[Event Request] at codeunit 699 "Exch. Rate Adjmt. Process"

### ISSUE THREAD

**Issue by iyiannak** [microsoft/ALAppExtensions#26455]
### Describe the request

Could you please add the **OnSetPostingDimensionsOnSourceEntryDimensions()** integration event at procedure SetPostingDimensions of codeunit 699 "Exch. Rate Adjmt. Process" as per below?

    local procedure SetPostingDimensions(var GenJournalLine: Record "Gen. Journal Line"; var DimensionSetEntry: Record "Dimension Set Entry")
    var
        DefaultDimSource: List of [Dictionary of [Integer, Code[20]]];
    begin
        case ExchRateAdjmtParameters."Dimension Posting" of
            "Exch. Rate Adjmt. Dimensions"::"No Dimensions":
                ...
            "Exch. Rate Adjmt. Dimensions"::"Source Entry Dimensions":
                begin
                    GenJournalLine."Shortcut Dimension 1 Code" := GetGlobalDimVal(GLSetup."Global Dimension 1 Code", DimensionSetEntry);
                    GenJournalLine."Shortcut Dimension 2 Code" := GetGlobalDimVal(GLSetup."Global Dimension 2 Code", DimensionSetEntry);
                    GenJournalLine."Dimension Set ID" := DimMgt.GetDimensionSetID(TempDimSetEntry);
                    OnSetPostingDimensionsOnSourceEntryDimensions(GenJournalLine, DimensionSetEntry);
                end;
            "Exch. Rate Adjmt. Dimensions"::"G/L Account Dimensions":
                ...
            else
                ...
        end;
    end;

  [IntegrationEvent(false, false)]
    local procedure OnSetPostingDimensionsOnSourceEntryDimensions(var GenJournalLine: Record "Gen. Journal Line"; var DimensionSetEntry: Record "Dimension Set Entry")
    begin
    end;

### Additional context

since there is no way to affect it
Internal work item: [AB#534798](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534798)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20288.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 20346.
