### ISSUE TITLE
[Change Request] add missing case for Production Order Status "Finished"

### ISSUE THREAD

**Issue by AndreBreitenbach** [microsoft/ALAppExtensions#26456]
### Describe the request

In report 99003802 "Copy Production Order Document" the case for "Finished" Production Order Status is missing.

![image](https://github.com/microsoft/ALAppExtensions/assets/40287548/e5f0b208-1f97-4c52-b2fa-9f6fb5cb42f1)

Additionally consider implementing some Publishers to make this whole report more extensible (one request for a new publisher is already accepted).

### Additional context

This makes it impossible to preset the value of RequestPage Control "DocNo" if coming from a Finished Production Order.
For all other Production Order Status this works fine.
Internal work item: [AB#534799](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/534799)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19986.
