### ISSUE TITLE
[Event Request] Codeunit 31390 "Match Bank Payment Handler CZZ" - procedure FillMatchBankPaymentBufferPurchaseAdvance() and FillMatchBankPaymentBufferSalesAdvance()

### ISSUE THREAD

**Issue by helmealex** [microsoft/ALAppExtensions#26458]
### Describe the request

Hello,

We need new integration events to filter `SalesAdvLetterHeaderCZZ: Record "Sales Adv. Letter Header CZZ"` and `PurchAdvLetterHeaderCZZ: Record "Purch. Adv. Letter Header CZZ"` using other fields in the procedures `FillMatchBankPaymentBufferPurchaseAdvance()` and `FillMatchBankPaymentBufferSalesAdvance()` of `Codeunit 31390 "Match Bank Payment Handler CZZ"`

### Additional context

Similar to this [issue](https://github.com/microsoft/ALAppExtensions/issues/25708)
Internal work item: [AB#535526](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535526)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19923.
