### ISSUE TITLE
[Change Request] codeunit 8800 "Custom Layout Reporting" SaveReportRequestPageParameters save stream as UTF8

### ISSUE THREAD

**Issue by AldisB** [microsoft/ALAppExtensions#26464]
### Describe the request

by default stream in saved in MSDos encoding which causes problems for non ENG characters. Please add UTF8 encoding before saving request page to BLOB field:
In procedure SaveReportRequestPageParameters  change line 
ObjectOptions."Option Data".CreateOutStream(OutStr);
to
"Option Data".CreateOutStream(OutStr, TextEncoding::UTF8);

### Additional context

When we retrieve request page which was previously saved and contained Latvian special characters, they are displayed incorrectly for example:
STR??DNIEKS is retrieved as STR?????DNIEKS
Internal work item: [AB#535531](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535531)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24623.
