### ISSUE TITLE
[Event Request] codeunit 232 "Gen. Jnl.-Post+Print" - OnBeforeUpdateIncomingDocument

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/ALAppExtensions#26467]
### Describe the request

Hi,
please add IsHandled to OnBeforeUpdateIncomingDocument:
```AL
codeunit 13 "Gen. Jnl.-Post Batch"
{
[..]
    local procedure UpdateIncomingDocument(var GenJnlLine: Record "Gen. Journal Line")
    var
        IncomingDocument: Record "Incoming Document";
        IsHandled: Boolean;
    begin
        OnBeforeUpdateIncomingDocument(GenJnlLine, IsHandled);
        if IsHandled then
            exit;
        IncomingDocument.UpdateIncomingDocumentFromPosting(
          GenJnlLine."Incoming Document Entry No.", GenJnlLine."Posting Date", GenJnlLine."Document No.");
    end;
[..]
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateIncomingDocument(var GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean)
    begin
    end;
[..]

```

### Additional context

Currently Business Central does not have [Multiple Journal Line Support for Incoming Documents](https://experience.dynamics.com/ideas/idea/?ideaid=66bd2391-0712-ef11-989a-000d3a7afa6b). In order to achieve this, we need this event to correctly handle the Business Central standard business logic.
Internal work item: [AB#535500](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535500)

**Comment by Groenbech96** [comment]
Correct solution is to look at ideas ticket, and not fix it short term with this IsHandled event. 
Please reach out to PM for more information about teams capacity to pick up that functionality request.

**Comment by DanielGoehler** [comment]
@Groenbech96 My idea is linked in the text above. I reached out to PM and received the following response:

> Thank you for your feedback. We are not considering the suggestion at this time due to the following reason:
As the e-invoicing becomes mandated in majority of countries (if not yet), we are strategically focused to continue investment in enriching new E-Documents framework, so if similar requests exist they can be required in the context of E-Documents framework.


> Sincerely,
Aleksandar Totovic
PM, Microsoft

I haven’t received a solution from the PM, nor have I received the event request. Is the goal here to frustrate me?

**Comment by DanielGoehler** [comment]
@Groenbech96 Any update here?

**Comment by DanielGoehler** [comment]
Like #26468 I've created an issue on BusinessCentralApps: [https://github.com/microsoft/BusinessCentralApps/issues/1367](https://github.com/microsoft/BusinessCentralApps/issues/1367)  
Once it's approved, I'll move forward with the implementation. This event is no longer need on my end.
