### ISSUE TITLE
[Event Request] CU1012 "Job Jnl.-Post Line" - local procedure "Code"

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#26469]
### Describe the request

Add two events in CU1012 "Job Jnl.-Post Line" - local procedure "Code"

### Additional context

local procedure "Code"(CheckLine: Boolean): Integer
.....
.....
----------------------- ADD EVENT ----------------------
OnBeforeOnNextEntryNo(VAR JobLedgEntry)

            if JobLedgEntry."Entry No." = 0 then begin
                JobLedgEntry.LockTable();
                NextEntryNo := JobLedgEntry.GetLastEntryNo() + 1;
            end;

----------------------- ADD EVENT ----------------------
OnAfterOnNextEntryNo(VAR JobLedgEntry, VAR NextEntryNo)
Internal work item: [AB#535521](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535521)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20282.
