### ISSUE TITLE
[Event Request] codeunit 378 "Transfer Extended Text" - OnDeleteJobPlanningLinesOnAfterSetFilters

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#26475]
### Describe the request

Could you please add the following event?
```al
local procedure DeleteJobPlanningLines(var JobPlanningLine: Record "Job Planning Line"): Boolean
var
    JobPlanningLine2: Record "Job Planning Line";
begin
    JobPlanningLine2.SetRange("Job No.", JobPlanningLine."Job No.");
    JobPlanningLine2.SetRange("Job Task No.", JobPlanningLine."Job Task No.");
    JobPlanningLine2.SetRange("Attached to Line No.", JobPlanningLine."Line No.");
    //>>Change for Event
    OnDeleteDeleteJobPlanningLinesOnAfterSetFilters(JobPlanningLine2, JobPlanningLine);
    //<<Change for Event
    JobPlanningLine2 := JobPlanningLine;
    if JobPlanningLine2.Find('>') then begin
        repeat
            JobPlanningLine2.Delete(true);
        until JobPlanningLine2.Next() = 0;
        exit(true);
    end;
end;
```

```al
[IntegrationEvent(false, false)]
local procedure OnDeleteJobPlanningLinesOnAfterSetFilters(var ToJobPlanningLine: Record "Job Planning Line"; FromJobPlanningLine: Record "Job Planning Line")
begin
end;
```

### Additional context

We need this event to delete custom records similiar to the event `OnDeleteSalesLinesOnAfterSetFilters`.
Internal work item: [AB#535524](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535524)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19932.
