### ISSUE TITLE
[Bug]: Problem SEPA file to SAAS version since update 24.0.

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#26479]
### Describe the issue

Problem SEPA file to SAAS version since update 24.0.

### Expected behavior

Hello,

The SEPA file has changed "XMLport 1000 - SEPA CT pain.001.001.09" to SAAS version since update 24.0.

This poses a problem for our customers.

While in Onprem the file has not changed "XMLport 1000 - SEPA pain.001.001.03"

How can I resolve this problem?

Best regards.

### Steps to reproduce

Current Version 24.0.16410.17628

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug

**Comment by BertOostenbrug** [comment]
Also in NL localization:
Default export Report 11000012 now creates 001.001.09 format. XSD used to create the XML is not correct.
For example <BIC> must be <BICFI>.
Versie: NL Business Central 24.0 (platform 24.0.19373.0 + toepassing 24.0.16410.17628)

**Comment by JesperSchulz** [comment]
Nice catch! Let's get the issue to a team who will fix and backport it, as this repo only is for extensibility related issues in the upcoming release. We suggest that you open a support case or file a bug in Collaborate, to ensure that all Business Central users benefit from your catch as soon as possible.

To open a support case, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.

Thanks for reporting the issue.
