### ISSUE TITLE
[Event Request] CU12 "Gen. Jnl.-Post Line" - local procedure InitNextEntryNo()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#26470]
### Describe the request

Add two events in CU12 "Gen. Jnl.-Post Line" - local procedure InitNextEntryNo()

### Additional context

local procedure InitNextEntryNo()

----------------------- ADD EVENT ----------------------
OnBeforeInitNextEntryNo(VAR GLEntry)

GLEntry.LockTable();
        GLEntry.GetLastEntry(LastEntryNo, LastTransactionNo);
        NextEntryNo := LastEntryNo + 1;
        NextTransactionNo := LastTransactionNo + 1;

----------------------- ADD EVENT ----------------------
OnAfterInitNextEntryNo(VAR GLEntry, VAR NextEntryNo , VAR NextTransactionNo)
Internal work item: [AB#535519](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535519)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 20229.
