### ISSUE TITLE
[Event Request] CU12 "Gen. Jnl.-Post Line" - local procedure PostDtldVendLedgEntries()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#26472]
### Describe the request

Add two events in CU12 "Gen. Jnl.-Post Line" - local procedure PostDtldVendLedgEntries()

### Additional context

local procedure PostDtldVendLedgEntries()

----------------------- ADD EVENT ----------------------
OnBeforeDtldVendLedgEntryNoOffset(VAR DetailedVendorLedgEntry)

        if DetailedVendorLedgEntry.FindLast() then
            DtldVendLedgEntryNoOffset := DetailedVendorLedgEntry."Entry No."
        else
            DtldVendLedgEntryNoOffset := 0;

----------------------- ADD EVENT ----------------------
OnAfterDtldVendLedgEntryNoOffset(VAR DetailedVendorLedgEntry, VAR DtldVendLedgEntryNoOffset)
Internal work item: [AB#535525](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535525)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 20229.
