### ISSUE TITLE
New publisher OnBeforeCheckOldBalance in CODA Import Management

### ISSUE THREAD

**Issue by dsaveyn** [microsoft/ALAppExtensions#26477]
### Describe the request

Please add a new publisher OnBeforeCheckOldBalance for the procedure CheckOldBalance in the CODA Import Management codeunit (BE Localization)

Current Code:
```
procedure CheckOldBalance(var CodedBankStmtSrcLine: Record "CODA Statement Source Line"): Boolean
var
    BankAccountNo: Text[30];
    IBANNumber: Text[34];
begin
    CodBankStmtSrcLine := CodedBankStmtSrcLine;
    // ...
end;	
```

Suggested Code
```
procedure CheckOldBalance(var CodedBankStmtSrcLine: Record "CODA Statement Source Line") OK: Boolean
var
    IsHandled: Boolean;
    BankAccountNo: Text[30];
    IBANNumber: Text[34];
begin
    OnBeforeCheckOldBalance(CodedBankStmtSrcLine, OK, IsHandled);
    if IsHandled then
        exit;

    CodBankStmtSrcLine := CodedBankStmtSrcLine;
    // ...
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeCheckOldBalance(var CodedBankStmtSrcLine: Record "CODA Statement Source Line"; var OK: Boolean; var IsHandled: Boolean)
begin
end;
```

### Additional context

We want to alter the logic so that foreign bank accounts (Account Type = 3) are also supported:

![image](https://github.com/microsoft/ALAppExtensions/assets/92365904/f8ec69b2-5e80-4cde-b6d3-c05221685ca1)

Internal work item: [AB#535512](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535512)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19923.
