### ISSUE TITLE
[EVENT REQUEST] - Codeunit 80 Sales-Post - Add parameters to OnRoundAmountOnAfterAssignSalesLines

### ISSUE THREAD

**Issue by aismel87** [microsoft/ALAppExtensions#26480]
### Describe the request

Hi AL Dev Team,

We need to add the parameters TotalSalesLine and TotalSalesLineLCY to the Event OnRoundAmountOnAfterAssignSalesLines.

Old Code
`OnRoundAmountOnAfterAssignSalesLines(xSalesLine, SalesLineACY, SalesHeader, IsHandled);`

New Code
`OnRoundAmountOnAfterAssignSalesLines(xSalesLine, SalesLineACY, SalesHeader, IsHandled, TotalSalesLine , TotalSalesLineLCY );`

New publisher:

`[IntegrationEvent(false, false)]`
    `local procedure OnRoundAmountOnAfterAssignSalesLines(var xSalesLine: Record "Sales Line"; var SalesLineACY: Record "Sales Line"; SalesHeader: Record "Sales Header"; var IsHandled: Boolean; TotalSalesLines: Record "Sales Line"; TotalSalesLineLCY: Record "Sales Line");`
    `begin`
    `end;`

### Additional context

fasfadfasdfasfasdfasdfasdfdsaf

fasdfa
Internal work item: [AB#535513](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535513)

**Comment by aismel87** [comment]
Additional Context: I need this parameters for rounding with the  "Document date" instead of the "Posting Date":

SalesLine."Amount Including VAT" :=
                  Round(
                    CurrExchRate.ExchangeAmtFCYToLCY(
                      **SalesHeader.GetUseDate(),** SalesHeader."Currency Code",
                      TotalSalesLine."Amount Including VAT", SalesHeader."Currency Factor")) -
                  TotalSalesLineLCY."Amount Including VAT";
...

**Comment by aismel87** [comment]
Hello, 

Sorry, I need the SalesLine parameter too, passed by reference.

New Code
OnRoundAmountOnAfterAssignSalesLines(xSalesLine, SalesLineACY, SalesHeader, IsHandled, TotalSalesLine , TotalSalesLineLCY, SalesLine);

New publisher:

[IntegrationEvent(false, false)]
local procedure OnRoundAmountOnAfterAssignSalesLines(var xSalesLine: Record "Sales Line"; var SalesLineACY: Record "Sales Line"; SalesHeader: Record "Sales Header"; var IsHandled: Boolean; TotalSalesLines: Record "Sales Line"; TotalSalesLineLCY: Record "Sales Line"; var SalesLine: Record "Sales Line");
begin
end;

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 20602.
