### ISSUE TITLE
[Event Request] Codeunit 5407 "Prod. Order Status Management"

### ISSUE THREAD

**Issue by Chris9821-Work** [microsoft/ALAppExtensions#26486]
### Describe the request

We need an event in codeunit 5407: 
-in function TransProdOrderLine: 

```al
OnTransProdOrderLineOnAfterFromProdOrderLineSetFilters(var FromProdOrderLine: Record "Prod. Order Line"; FromProdOrder: Record "Production Order"; NewUpdateUnitCost: Boolean)
``` 
![image](https://github.com/microsoft/ALAppExtensions/assets/154224441/6385ee6c-14ed-41a0-b6f1-1a7b10be557f)

-In function InsertProdOrderLine it could make sense to add ToProdOrder as parameter, adding it to OnBeforeInsertProdOrderLine and OnAfterInsertProdOrderLine as well. 

### Additional context

We need it to change the filters on the lines and to set different keys based on NewUpdateUnitCost flag
The extra parameter in our case is useful because we need to bring some custom fields from the header to the line
Internal work item: [AB#535499](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535499)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 19932.
