### ISSUE TITLE
[EVENT REQUEST] - Codeunit 90 Purch.-Post - Add parameters to OnRoundAmountOnBeforeCalculateLCYAmounts

### ISSUE THREAD

**Issue by aismel87** [microsoft/ALAppExtensions#26481]
### Describe the request

Hi AL Dev Team,

We need to add the parameters TotalPurchLine and TotalPurchLineLCY to the Event OnRoundAmountOnBeforeCalculateLCYAmounts.

Old Code
`OnRoundAmountOnBeforeCalculateLCYAmounts(xPurchLine, PurchLineACY, PurchaseHeader, IsHandled);`

New Code
`OnRoundAmountOnBeforeCalculateLCYAmounts(xPurchLine, PurchLineACY, PurchaseHeader, IsHandled, TotalPurchLine, TotalPurchLineLCY);`

New publisher:

`[IntegrationEvent(false, false)]`
 `local procedure OnRoundAmountOnBeforeCalculateLCYAmounts(var xPurchLine: Record "Purchase Line"; var PurchLineACY: Record "Purchase Line"; PurchHeader: Record "Purchase Header"; var IsHandled: Boolean; TotalPurchLine: Record "Purchase Line"; TotalPurchLineLCY: Record "Purchase Line")`
    `begin`
    `end;`

Thank you!!!

Ismael

### Additional context

 I need this parameters for rounding with the "Document date" instead of the "Posting Date":

PurchaseLine."Amount Including VAT" :=
            Round(
                CurrExchRate.ExchangeAmtFCYToLCY(
                    **PurchaseHeader.GetUseDate()**, PurchaseHeader."Currency Code",
                    TotalPurchLine."Amount Including VAT", PurchaseHeader."Currency Factor")) -
                TotalPurchLineLCY."Amount Including VAT";

etc.
Internal work item: [AB#535509](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/535509)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 20602.
