### ISSUE TITLE
[Bug]: Bank Deposit posting inconsistency

### ISSUE THREAD

**Issue by Drakonian** [microsoft/ALAppExtensions#26485]
### Describe the issue

I encountered that in version BC24, an extra commit was added to BankDeposit posting codeunit which can lead to terrible consequences.

After this commit, any error results in a Bank Deposit remaining and a new created Posted Bank Deposit being saved!
https://github.com/microsoft/ALAppExtensions/blob/2b14106f65decf433e2f6c373895ce0db0a862b2/Apps/W1/BankDeposits/app/src/codeunits/BankDepositPost.Codeunit.al#L115

Just imagine, any business rule with error in BatchPost or etc and our Bank Deposit just broken.
https://github.com/microsoft/ALAppExtensions/blob/2b14106f65decf433e2f6c373895ce0db0a862b2/Apps/W1/BankDeposits/app/src/codeunits/BankDepositPost.Codeunit.al#L118

I am currently facing an error related to the Correction Gen. Journal Line. I'm not yet sure of the cause of the error itself. But I am definitely sure that this commit is very dangerous and it needs to be removed.

### Expected behavior

Posting transaction must be consistent

### Steps to reproduce

1.Create Bank Deposit
2.Add something which will throw business error after https://github.com/microsoft/ALAppExtensions/blob/2b14106f65decf433e2f6c373895ce0db0a862b2/Apps/W1/BankDeposits/app/src/codeunits/BankDepositPost.Codeunit.al#L115
and before
https://github.com/microsoft/ALAppExtensions/blob/2b14106f65decf433e2f6c373895ce0db0a862b2/Apps/W1/BankDeposits/app/src/codeunits/BankDepositPost.Codeunit.al#L134
3.As result you will have Posted and Unposted Bank Account!

### Additional context

My current error which is just give the result from main description. I am not sure about this error and in process of investigation.

```
Correction must be the same on all lines for the same document in Gen. Journal Line Journal Template Name='BNKDEPOSIT',Journal Batch Name='BNKDEPOSIT',Line No.='20000'

"Gen. Jnl.-Post Batch"(CodeUnit 13).CheckCorrection line 15 - Base Application by Microsoft
"Gen. Jnl.-Post Batch"(CodeUnit 13).ProcessBalanceOfLines line 64 - Base Application by Microsoft
"Gen. Jnl.-Post Batch"(CodeUnit 13).ProcessLines line 59 - Base Application by Microsoft
"Gen. Jnl.-Post Batch"(CodeUnit 13).Code line 30 - Base Application by Microsoft
"Gen. Jnl.-Post Batch"(CodeUnit 13).OnRun(Trigger) line 9 - Base Application by Microsoft
"Bank Deposit-Post"(CodeUnit 1690).OnRun(Trigger) line 88 - _Exclude_Bank Deposits by Microsoft
"Bank Deposit-Post (Yes/No)"(CodeUnit 1692).OnRun(Trigger) line 7 - _Exclude_Bank Deposits by Microsoft
```

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by Drakonian** [comment]
I am sure this is huge problem.

**Comment by JesperSchulz** [comment]
Hi @Drakonian, that doesn't sound good. But did you register the issue the right place? If this indeed can have terrible consequences, shouldn't you rather log a support case? Also, this doesn't strike me as an extensibility issue for a 1st party app. If you'd like to address this issue, you should probably have logged it in the [BaseApp contribution pilot](https://github.com/microsoft/BusinessCentralApps). Let me know what you think!

**Comment by Drakonian** [comment]
Hi @JesperSchulz 
This is the only place I found codeunit 1690 “Bank Deposit-Post.” where problem is located. 
BaseApp repos doesn't contain these objects.

About the support ticket, I can't get it registered as this luxury is only for Microsoft Partner 😞

**Comment by Drakonian** [comment]
@JesperSchulz 
I also found a simple way to cause an error that will result in Bank Deposit Inconsistency.

This error should probably be made into a separate issue. But I'll wait for your verdict on where to send it.

**Comment by JesperSchulz** [comment]
Ah, so this is actually due to an 1st party app - as you clearly describe in the issue description. Sorry, didn't pay close enough attention. I'd still suggest this is more of a support case, but if you cannot create one, this is the 2nd best option. Approved for PR. When you've created one, I'll make sure to backport to released versions.

**Comment by Drakonian** [comment]
@JesperSchulz it's already fixed in this PR https://github.com/microsoft/ALAppExtensions/pull/26546
![image](https://github.com/microsoft/ALAppExtensions/assets/16802407/739da2f3-3f39-4538-90f4-1c3601a5cdd3)
