### ISSUE TITLE
[Event Request] codeunit 1339 "Cancel Posted Sales Cr. Memo" - OnBeforeTestIfCrMemoIsCorrectiveDoc

### ISSUE THREAD

**Issue by AlexanderWittek** [microsoft/ALAppExtensions#26493]
### Describe the request

As in the purchase area, we need a new IntegrationEvent "OnBeforeTestIfCrMemoIsCorrectiveDoc" to cancel normal sales credit memos.

codeunit 1339 "Cancel Posted Sales Cr. Memo"

```
    local procedure TestIfCrMemoIsCorrectiveDoc(SalesCrMemoHeader: Record "Sales Cr.Memo Header")
    var
        CancelledDocument: Record "Cancelled Document";
// Start
        IsHandled: Boolean;
// Stop
    begin
// Start
        IsHandled := false;
        OnBeforeTestIfCrMemoIsCorrectiveDoc(SalesCrMemoHeader, IsHandled);
        if IsHandled then
            exit;
// Stop

        if not CancelledDocument.FindSalesCorrectiveCrMemo(SalesCrMemoHeader."No.") then
            ErrorHelperHeader(ErrorType::IsCanceled, SalesCrMemoHeader);
    end;
```

...

```
// Start
    [IntegrationEvent(false, false)]
    local procedure OnBeforeTestIfCrMemoIsCorrectiveDoc(SalesCrMemoHeader: Record "Sales Cr.Memo Header"; var IsHandled: Boolean)
    begin
    end;
// Stop
```

### Additional context

We would like to use this event to cancel normal sales credit memos.
Internal work item: [AB#538758](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538758)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 21676.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21691.
