### ISSUE TITLE
Internal procedures in Coduenit 7312 Create Pick

### ISSUE THREAD

**Issue by evamariamartingomez** [microsoft/ALAppExtensions#26496]
### Describe the request

We need to develop a particular process to generate Pickings from Prod. Order components. From this process we the call Create Pick coduenit in order to system creates the corresponded Pickigs, but in BC24 some procedures in codeunit id. 7312  are defined as internal, so we can call them. Specifically, it is about the following:

  -  InsertSkippedLinesToCalculationSummary
  -  SetSaveSummary
  -  SetSummaryPageMessage
  -  ShowCalculationSummary

Would it be possible to make them accessible from outside modules, please?

Thank you!

### Additional context

We need to develop a particular process to generate Pickings from Prod. Order components. From this process we the call Create Pick coduenit in order to system creates the corresponded Pickigs, but in BC24 some procedures in codeunit id. 7312  are defined as internal, so we can call them.
Internal work item: [AB#538753](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538753)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.

**Comment by t-prda** [comment]
We are not yet ready to make these public and will wait for more feedback on this new page. These procedures would be made public potentially in 26.0 or in some minor version of 25.
