### ISSUE TITLE
[Event Request] Codeunit 13652 FIK_MatchGenJournalLines - OnFindMatchingCustEntries

### ISSUE THREAD

**Issue by MantasGurinas** [microsoft/ALAppExtensions#26492]
### Describe the request

Hello Team,

In Codeunit 13652 we need possibility to have our additional checks and/or avoid using standard code. Having event in procedure `FindMatchingCustEntries` would be a perfect solution:

![image](https://github.com/microsoft/ALAppExtensions/assets/70525691/d7c19d74-8487-4969-897c-9dfa8567172a)

```
[IntegrationEvent(false, false)]
local procedure OnFindMatchingCustEntries(var CustLedgerEntry: Record "Cust. Ledger Entry"; VAR TempBankStatementMatchingBuffer: Record "Bank Statement Matching Buffer" temporary; VAR TempGenJournalLine: Record "Gen. Journal Line" temporary)
begin
end;
```

### Additional context

We would like to add additional filtering options on the variable CustLedgerEntry to reflect our needed changes.
Internal work item: [AB#538737](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538737)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 23162.
