### ISSUE TITLE
Codeunit 7000 "Sales Price Calc. Mgt." event on procedure GetSalesLineLineDisc

### ISSUE THREAD

**Issue by exnihiloo** [microsoft/ALAppExtensions#26507]
### Describe the request

Hello, would it be possible to add OnBeforeValidateSalesLine event on the procedure GetSalesLineLineDisc to codeunit 7000 like this:

``````al
procedure GetSalesLineLineDisc(SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line")
...
if PAGE.RunModal(PAGE::"Get Sales Line Disc.", TempSalesLineDisc) = ACTION::LookupOK then begin
            SetCurrency(SalesHeader."Currency Code", 0, 0D);
            SetUoM(Abs(SalesLine.Quantity), SalesLine."Qty. per Unit of Measure");
            ...
            SalesLine.TestField("Allow Line Disc.");
            IsHandled := false;
            OnBeforeValidateSalesLine(SalesLine, TempSalesLineDisc, IsHandled); //New Event
            if not IsHandled then
                 SalesLine.Validate("Line Discount %", TempSalesLineDisc."Line Discount %");
end;

OnAfterGetSalesLineLineDisc(SalesLine, TempSalesLineDisc);
``````

``````al
[IntegrationEvent(false, false)]
local procedure OnBeforeValidateSalesLine(var SalesLine: Record "Sales Line"; var SalesLineDiscount: Record "Sales Line Discount"; var IsHandled: Boolean)
begin
end;
``````

Internal work item: [AB#538768](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538768)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 21676.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21691.
