### ISSUE TITLE
Add event OnBeforeTestDate into codeunit 396 NoSeriesManagement

### ISSUE THREAD

**Issue by NBTPaolinoMattia** [microsoft/ALAppExtensions#26503]
### Describe the request

The code should be like this:

````
[Scope('OnPrem')]
    procedure TestDateOrder(NoSeriesCode: Code[20])
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeTestDate(NoSeries,IsHandled);
        if IsHandled then
            exit;

        NoSeries.Get(NoSeriesCode);
        NoSeries.TestField("Date Order");
    end;
````

````
[IntegrationEvent(false, false)]
local procedure OnBeforeTestDate(var NoSeries: Record "No. Series" ; var IsHandled: Boolean)
begin
end;
````

### Additional context

We need to add this event before execute TestField in case we have the necessity to skip this control or change the program locig.
Internal work item: [AB#538764](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538764)

**Comment by grobyns** [comment]
Hi @NBTPaolinoMattia 
The only place I found a method called TestDateOrder looks like this:

```
    [Obsolete('Call TestField on the "No. Series" record, "Date Order" field directly.', '24.0')]
    [Scope('OnPrem')]
    procedure TestDateOrder(NoSeriesCode: Code[20])
    begin
        GlobalNoSeries.Get(NoSeriesCode);
        GlobalNoSeries.TestField("Date Order");
    end;
```

The method is obsolete and is no longer called from Baseapp code. We won't add an event in obsolete code that is not used.
