### ISSUE TITLE
[Bug]: change the calculation of: - Amount (17) in G/L Entry (17)  - Base (8) and Amount (9) in VAT Entry (254)  when posting an invoice in foreign currency.

### ISSUE THREAD

**Issue by SerhiiKorniichuk1** [microsoft/ALAppExtensions#26508]
### Describe the issue

When posting a sales invoice in a foreign currency, the G/L Entry are created:
to the G/L account specified in General Posting Setup (252) - in field Sales Account (10) - the VAT base amount is calculated in the LCY
to the account specified in VAT Posting Setup (325) - in field Sales VAT Account (7) - the VAT amount is calculated in the LCY
+
VAT Entry (254) is created, in which Base (8)= the VAT base amount is calculated in the LCY and Amount (9)=the VAT amount is calculated in the LCY

### Expected behavior

Current:
 
The VAT base amount in the LCY is calculated as the VAT base amount in foreign currency multiplied by the exchange rate
The VAT amount in LCY is calculated as the difference between the (Amount Including VAT - Amount Excluding VAT) multiplied by the exchange rate

Should be:

The VAT base amount in the LCY should be calculated as Amount Including VAT (LCY)/ (1+VAT%/100)
The VAT amount in LCY should be calculated as Amount Including VAT (LCY) - Amount Excluding VAT (LCY)
 
Additional context
This is necessary to because in some cases the amount of the calculated VAT base amount (LCY) + VAT amount (LCY) is not equal to the Amount Including VAT(LCY), also the Amount Excluding VAT (LCY)* VAT%/100 is NOT equal to the VAT amount (LCY).

### Steps to reproduce

When posting a sales invoice in a foreign currency, the G/L Entry are created:
to the G/L account specified in General Posting Setup (252) - in field Sales Account (10) - the VAT base amount is calculated in the LCY
to the account specified in VAT Posting Setup (325) - in field Sales VAT Account (7) - the VAT amount is calculated in the LCY
+
VAT Entry (254) is created, in which Base (8)= the VAT base amount is calculated in the LCY and Amount (9)=the VAT amount is calculated in the LCY

### Additional context

For example 
Amount Excluding VAT= 1573,11
VAT%=20%
Amount Including VAT=1887,73
VAT amount=314,62
exchange rate=42,2079
 
Now we receive on the posting 
Amount Excluding VAT(LCY)= 1573,11*42,2079=66397,67
Amount Including VAT(LCY)=1887,73*42,2079= 79677,12
VAT amount(LCY)=314,62*42,2079=13279,45
 
but it should be 
Amount Excluding VAT(LCY)=79677,12/(1+20/100)=66397,6
VAT amount(LCY)=79677,12-66397,6=13279,52

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug

**Comment by RadoArvay** [comment]
Probably, it is not a bug. Every legislation has a different way to calculate VAT. This standard calculation is from W1, I asume.
You did not specified a country version of BC which you expect the behaviour for.

**Comment by JesperSchulz** [comment]
Also, this isn't an issue related to extensibility. If you'd like to create a support request, you can:

- Open a support request to CSS through the PartnerSource portal 
- Contact your Service Account Manager (SAM) in your local subsidiary to understand what is included in your contract as of support incident and PAH (Partner Advisory Hours). Your SAM might also direct you "step by step" how to open a support request or how to get credentials, if this is the first time for you or your company

If you file the bug in Collaborate, remember to include steps to reproduce the issue, and the Business Central build number and country version you're using. Here's a link to Collaborate: https://developer.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/create.
