### ISSUE TITLE
[Bug]: "IsHandled" does not exit the "DeleteAssemblyDocument" function .

### ISSUE THREAD

**Issue by lorenzfleerackers** [microsoft/ALAppExtensions#26501]
### Describe the issue

A client of mine wanted the assembly orders not to be deleted. For the deletion of the assembly document, there is an event to set an ishandled. However, after this event, an exit was never added, which results in the .Reset of the local assembly line not being executed. I suspect this was overlooked when creating the event. Is it possible to add an exit here?
![image](https://github.com/microsoft/ALAppExtensions/assets/28091845/448fe7d2-8bec-40ad-8849-52b92244e07c)

### Expected behavior

An exit of the "DeleteAssemblyDocument" function.

### Steps to reproduce

Set the ishandled on in the "OnBeforeDeleteAssemblyDocument" event in the "Assembly Post" codeunit.

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JakovljevicDusan** [comment]
Hi @lorenzfleerackers,

Thanks for pointing at this. This is bug introduced in 24.x with "with" statement removal. HotFix will be included in 24.2.
