### ISSUE TITLE
"Currency Exchange Rate"."Fix Exchange Rate Amount" - Option to Enum

### ISSUE THREAD

**Issue by xtiche** [microsoft/ALAppExtensions#26506]
### Describe the request

Please convert option to enum:
```
table 330 "Currency Exchange Rate"

...

field(7; "Fix Exchange Rate Amount"; Option)
{
    Caption = 'Fix Exchange Rate Amount';
    OptionCaption = 'Currency,Relational Currency,Both';
    OptionMembers = Currency,"Relational Currency",Both;
}
```

### Additional context

We need to add same setup on other table
Internal work item: [AB#538740](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538740)

**Comment by mmmurdered** [comment]
// todo rewrite on enum

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21183.
