### ISSUE TITLE
[Access Request] page 11502 "Swiss QR-Bill Create Vend Bank" - SetDetails / SetDetails

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#26505]
### Describe the request
Could you please remove the internal access from the following two procedures.
```al
    //+Change
    //-internal procedure SetDetails(VendorBankAccount: Record "Vendor Bank Account")
    procedure SetDetails(VendorBankAccount: Record "Vendor Bank Account")
    //+Change
    begin
        if Delete() then;
        TransferFields(VendorBankAccount);
        Insert();
    end;

    //+Change
    //-internal procedure SetDetails(var VendorBankAccount: Record "Vendor Bank Account")
    procedure GetDetails(var VendorBankAccount: Record "Vendor Bank Account")
    //+Change
    begin
        VendorBankAccount := Rec;
    end;
```

### Additional context

We would like to use this page from our custom code.
Currenlty this is not possible without the Getter and Setter procedure
Internal work item: [AB#538766](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538766)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 21676.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21691.
