### ISSUE TITLE
Report 722 "Phys. Inventory List" - move TempReservationEntryBuffer variable to protected

### ISSUE THREAD

**Issue by SzabolcsGyorkeTNP** [microsoft/ALAppExtensions#26504]
### Describe the request

Please move the TempReservationEntryBuffer variable to protected so the report extension can pick and add fields to the Item Tracking section.

### Additional context

The customer has additional fields on Item Tracking and currently we can't add them to the dataset without copynig the report.
Internal work item: [AB#538755](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538755)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21453.
