### ISSUE TITLE
[EVENT REQUEST] codeunit 5804 ItemCostManagement – OnBeforeCheckNegCost

### ISSUE THREAD

**Issue by aleobi** [microsoft/ALAppExtensions#26502]
### Describe the request

With #25919 we asked for two IntegrationEvents. We are really thankful for the new event OnCalcAverageUnitCostOnBeforeCheckNegCost in the report "Calculate Inventory Value" to be able to have negative inventory values in the Revaluation Journal, but we are still missing a possibility to bypass setting the "Unit Cost" field to zero on Item Card as soon as it turns negative:

codeunit 5804 ItemCostManagement:

```
procedure CalculateAverageCost(var Item: Record Item; var AverageCost: Decimal; var AverageCostACY: Decimal): Boolean
var
    ...
    //> New
    IsHandled: boolean;
    //< New
begin
    ...
    if AverageQty <> 0 then begin
        ...
        //> New        
        IsHandled := false;
        OnBeforeCheckNegCost(AverageCost, AverageCostACY, IsHandled);
        if not IsHandled then begin
        //< New
            if AverageCost < 0 then
                AverageCost := 0;
            if AverageCostACY < 0 then
                AverageCostACY := 0;
        //> New
        end;  
        //< New
    end else begin
        AverageCost := 0;
        AverageCostACY := 0;
    end;
    if AverageQty <= 0 then
        exit(false);

    exit(true);
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCheckNegCost(var AverageCost: Decimal; var AverageCostACY: Decimal; var IsHandled: Boolean)
begin
end;
```

Really looking forward to your help! Thank you!

### Additional context

Most of our customers are coming from waste industries, where receiving money for incoming material is a realistic and also everyday scenario - therefore our customers have the really need to be able to handle negative inventory values in Business Central. This mainly works in BC, except setting the field "Unit Cost" to zero on the item card as soon as it becomes negative.
Internal work item: [AB#538763](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538763)

**Comment by tomasevicst** [comment]
Hi,

We already have publisher OnCalculateAverageCostOnAfterCalculateAverage on the place that you need. Can you use that one, and if you need we can add IsHandled parameter?

```
AverageCost := CostAmt / AverageQty;
AverageCostACY := CostAmtACY / AverageQty;

OnCalculateAverageCostOnAfterCalculateAverage(Item, AverageCost, AverageCostACY);

if AverageCost < 0 then
     AverageCost := 0;
if AverageCostACY < 0 then
     AverageCostACY := 0;
```

**Comment by aleobi** [comment]
Hi, 

that would also be fine - as long as we can prevent setting the AverageCost variables to 0 when they turn negative!

Thank you

**Comment by aleobi** [comment]
One addition, and this would also be needed for updating the Unit Cost on SKUs (UpdateUnitCostSKU in codeunit 5804 ItemCostManagement). Thank you very much and hope to hear from you soon!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21460.

**Comment by aleobi** [comment]
Hi,

I just checked the latest preview and were happy to have the IntegrationEvent OnCalculateAverageCostOnAfterCalculateAverage in place to avoid setting Unit Cost on zero when it turns negative on Item Card. As already mentioned we have the same issue for SKUs, which you agreed on. But that Integration Event seems still to be missing? Would be really helpful to have a similar IntegrationEvent also here in place directly before setting the negative Unit Costs to zero:

![image](https://github.com/user-attachments/assets/aaef658e-af41-42ee-a31d-e951a4012997)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25082.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 25754.
