### ISSUE TITLE
Add event OnBeforeDimCodeNotAllowed into codeunit 7130 "Item Budget Management"

### ISSUE THREAD

**Issue by NBTPaolinoMattia** [microsoft/ALAppExtensions#26518]
### Describe the request

The code should be like this:

````
procedure DimCodeNotAllowed(DimCode: Text[30]; ItemBudgetName: Record "Item Budget Name"): Boolean
var
    Item: Record Item;
    Cust: Record Customer;
    Vend: Record Vendor;
    Location: Record Location;
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeDimCodeNotAllowed(DimCode,  ItemBudgetName, Result, IsHandled);
    if IsHandled then
      exit(Result);

    GetGLSetup();
    exit(
      not (UpperCase(DimCode) in
           [UpperCase(Item.TableCaption()),
            UpperCase(Cust.TableCaption()),
            UpperCase(Vend.TableCaption()),
            UpperCase(Location.TableCaption()),
            UpperCase(Text003),
            ItemBudgetName."Budget Dimension 1 Code",
            ItemBudgetName."Budget Dimension 2 Code",
            ItemBudgetName."Budget Dimension 3 Code",
            GLSetup."Global Dimension 1 Code",
            GLSetup."Global Dimension 2 Code",
            '']));
end;
````

````
[IntegrationEvent(false, false)]
local procedure OnBeforeDimCodeNotAllowed(DimCode: Text[30]; ItemBudgetName: Record "Item Budget Name"; var Result: Boolean; var IsHandled: Boolean)
begin
end;
````

### Additional context

Like codeunit 7153 "Item Analysis Management" this event in usefull if anyone want to change the Result expression.
Internal work item: [AB#538747](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538747)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21278.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 21287.
