### ISSUE TITLE
Add event OnAfterCopyPeriodToBuf into codeunit 7153 "Item Analysis Management"

### ISSUE THREAD

**Issue by NBTPaolinoMattia** [microsoft/ALAppExtensions#26510]
### Describe the request

The code should be like this:

````
local procedure CopyPeriodToBuf(var Period: Record Date; var DimCodeBuf: Record "Dimension Code Buffer"; DateFilter: Text[30])
    var
        Period2: Record Date;
    begin
        with DimCodeBuf do begin
            Init();
            Code := Format(Period."Period Start");
            "Period Start" := Period."Period Start";
            "Period End" := Period."Period End";
            if DateFilter <> '' then begin
                Period2.SetFilter("Period End", DateFilter);
                if Period2.GetRangeMax("Period End") < "Period End" then
                    "Period End" := Period2.GetRangeMax("Period End");
            end;
            Name := Period."Period Name";
            OnAfterCopyPeriodToBuf(Period,DimCodeBuf,DateFilter);
        end;
    end;
````

````
[IntegrationEvent(false, false)]
local procedure OnAfterCopyPeriodToBuf(var Period: Record Date; var DimCodeBuf: Record "Dimension Code Buffer"; DateFilter: Text[30])
begin
end;
````

### Additional context

In this way we can manipulate intormations inside the DimCodeBuf record before insert istruction.
Internal work item: [AB#538748](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538748)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21283.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 21287.
