### ISSUE TITLE
Add event OnBeforeSetLineAndColumnDim into codeunit 7153 "Item Analysis Management"

### ISSUE THREAD

**Issue by NBTPaolinoMattia** [microsoft/ALAppExtensions#26511]
### Describe the request

The code should be like this:

````
procedure SetLineAndColumnDim(ItemAnalysisView: Record "Item Analysis View"; var LineDimCode: Text[30]; var LineDimType: Enum "Item Analysis Dimension Type"; var ColumnDimCode: Text[30]; var ColumnDimType: Enum "Item Analysis Dimension Type")
var
    Item: Record Item;
begin
    if (LineDimCode = '') and (ColumnDimCode = '') then begin
        LineDimCode := Item.TableCaption();
        ColumnDimCode := Text000;
    end;

    OnbeforeSetLineAndColumnDim(ItemAnalysisView, LineDimCode, LineDimType, ColumnDimCode, ColumnDimType);

    LineDimType := DimCodeToType(LineDimCode, ItemAnalysisView);
    ColumnDimType := DimCodeToType(ColumnDimCode, ItemAnalysisView);

    OnAfterSetLineAndColumnDim(ItemAnalysisView, LineDimCode, LineDimType, ColumnDimCode, ColumnDimType);
end;
````

````
[IntegrationEvent(false, false)]
local procedure OnBeforeSetLineAndColumnDim(ItemAnalysisView: Record "Item Analysis View"; var LineDimCode: Text[30]; var LineDimType: Enum "Item Analysis Dimension Type"; var ColumnDimCode: Text[30]; var ColumnDimType: Enum "Item Analysis Dimension Type")
begin
end;
````

### Additional context

We need this event because we can change the LineDimType or ColumnDimType value before the DimCodeToType function.
Internal work item: [AB#538769](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538769)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21283.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 21287.
