### ISSUE TITLE
[EVENT REQUEST] - Codeunit 80 "Sales-Post" - Function PostItemTrackingForReceipt

### ISSUE THREAD

**Issue by sanangi** [microsoft/ALAppExtensions#26522]
### Describe the request

Dear AL Development Team,

We would like to request the modification of a current event located in Codeunit 80 "Sales-Post" inside the function PostItemTrackingForReceipt

Old code:
```
                    OnPostItemTrackingForReceiptOnBeforeReturnRcptLineModify(SalesHeader, ReturnRcptLine, SalesLine);
                    ReturnRcptLine.Modify();

                    OnBeforePostItemTrackingReturnRcpt(
                      SalesInvHeader, SalesShptLine, TempTrackingSpecification, TrackingSpecificationExists,
                      SalesCrMemoHeader, ReturnRcptLine, SalesLine, QtyToBeInvoiced, QtyToBeInvoicedBase);
```

Requested Code:
```
                    IsHandled := false;
                    OnPostItemTrackingForReceiptOnBeforeReturnRcptLineModify(SalesHeader, ReturnRcptLine, SalesLine, IsHandled);
                    
                    if not IsHandled then
                        ReturnRcptLine.Modify();

                    OnBeforePostItemTrackingReturnRcpt(
                      SalesInvHeader, SalesShptLine, TempTrackingSpecification, TrackingSpecificationExists,
                      SalesCrMemoHeader, ReturnRcptLine, SalesLine, QtyToBeInvoiced, QtyToBeInvoicedBase);
```
Modified Publisher:
```
    [IntegrationEvent(false, false)]
    local procedure OnPostItemTrackingForReceiptOnBeforeReturnRcptLineModify(SalesHeader: Record "Sales Header"; var ReturnRcptLine: Record "Return Receipt Line"; SalesLine: Record "Sales Line"; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

We need an additional IsHandled to the current event OnPostItemTrackingForReceiptOnBeforeReturnRcptLineModify inside the function PostItemTrackingForReceipt.

Thank you in advance.
Internal work item: [AB#538739](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538739)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21140.
