### ISSUE TITLE
Add event OnBeforeSendEmailNotificationOfSensitiveFieldChange into codeunit 1368 "Monitored Field Notification"

### ISSUE THREAD

**Issue by AigarsAvotins** [microsoft/ALAppExtensions#26529]
### Describe the request

Need new event before send e-mail:

Exsisting:

```
procedure SendEmailNotificationOfSensitiveFieldChange(RecRef: RecordRef; var ChangeLogEntry: Record "Change Log Entry"; var MonitorFieldNotification: Enum "Monitor Field Notification")
    var
        FieldMonitoringSetup: record "Field Monitoring Setup";
        UseNewEmailFeature: Boolean;
    begin
        if not IsMonitorReadyToSendEmails(FieldMonitoringSetup, UseNewEmailFeature) then begin
            MonitorFieldNotification := MonitorFieldNotification::"Sending Email Failed";
            exit;
        end;

        if SendEmail(FieldMonitoringSetup, RecRef, ChangeLogEntry, UseNewEmailFeature) then begin
            if UseNewEmailFeature then
                MonitorFieldNotification := MonitorFieldNotification::"Email Enqueued"
            else
                MonitorFieldNotification := MonitorFieldNotification::"Email Sent";

        end else
            MonitorFieldNotification := MonitorFieldNotification::"Sending Email Failed";
    end;
```

New:

procedure SendEmailNotificationOfSensitiveFieldChange(RecRef: RecordRef; var ChangeLogEntry: Record "Change Log Entry"; var MonitorFieldNotification: Enum "Monitor Field Notification")
    var
        FieldMonitoringSetup: record "Field Monitoring Setup";
        UseNewEmailFeature: Boolean;
         IsHandled: Boolean;
    begin
        if not IsMonitorReadyToSendEmails(FieldMonitoringSetup, UseNewEmailFeature) then begin
            MonitorFieldNotification := MonitorFieldNotification::"Sending Email Failed";
            exit;
        end;

       OnBeforeSendEmailNotificationOfSensitiveFieldChange(var ChangeLogEntry: Record "Change Log Entry"; var FieldMonitoringSetup: record "Field Monitoring Setup"; var IsHandled);
       if IsHandled then 
          Exit;

        if SendEmail(FieldMonitoringSetup, RecRef, ChangeLogEntry, UseNewEmailFeature) then begin
            if UseNewEmailFeature then
                MonitorFieldNotification := MonitorFieldNotification::"Email Enqueued"
            else
                MonitorFieldNotification := MonitorFieldNotification::"Email Sent";

        end else
            MonitorFieldNotification := MonitorFieldNotification::"Sending Email Failed";
    end;

[IntegrationEvent(false, false)]
local procedure OnBeforeSendEmailNotificationOfSensitiveFieldChange(var ChangeLogEntry: Record "Change Log Entry"; var FieldMonitoringSetup: record "Field Monitoring Setup"; var IsHandled)
begin
end;

### Additional context

Ned to skip some changes and change E-mail body.
Internal work item: [AB#536473](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536473)

**Comment by Groenbech96** [comment]
Im not going to introduce an ishandled pattern in this critical code path for the monitor fields feature.
This logic has to be controlled, and this event will allow bypass. 
Do you have any other suggestions?
