### ISSUE TITLE
Silencing posting journal lines in microsoft sustainability

### ISSUE THREAD

**Issue by vallzter** [microsoft/ALAppExtensions#26520]
### Describe the request

When posting Sustainability journal entries through codeunit 6213 can I get an event that silences the confirm message? I am currently hooking into that codeunit and am posting many journal lines so I would like to avoid having to click yes multiple times.

### Additional context

I need this so that the user does not have to click yes multiple times to post the lines.
Internal work item: [AB#538738](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538738)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25563.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 25584.
