### ISSUE TITLE
Add event OnBeforeGetScenario in codeunit 8892 "Email Scenario Impl." in procedure GetDefaultAccount

### ISSUE THREAD

**Issue by DELNicoJdl** [microsoft/ALAppExtensions#26539]
### Describe the request

Hello,

Could it be possible to add the event OnBeforeGetScenario(EmailAccount,IsHandled) in procedure GetDefaultAccount in codeunit 8892 "Email Scenario Impl."

```
local procedure GetDefaultAccount(var EmailAccount: Record "Email Account")
    var
        Scenario: Record "Email Scenario";
    begin
        if not Scenario.Get(Enum::"Email Scenario"::Default) then
            exit;

        EmailAccount."Account Id" := Scenario."Account Id";
        EmailAccount.Connector := Scenario.Connector;
    end;

```

Become :

```

local procedure GetDefaultAccount(var EmailAccount: Record "Email Account")
    var
        Scenario: Record "Email Scenario";
    begin
        OnBeforeGetScenario(EmailAccount,IsHandled);
        if IsHandled then exit;
        if not Scenario.Get(Enum::"Email Scenario"::Default) then
            exit;

        EmailAccount."Account Id" := Scenario."Account Id";
        EmailAccount.Connector := Scenario.Connector;
    end;

 [IntegrationEvent(false, false)]
 local procedure OnBeforeGetScenario(var EmailAccount: Record "Email Account"; var IsHandled: Boolean)
 begin
 end;
```

### Additional context

This event would able us to define a generic sender email by user.
The idea is to have one default email account per group of user.
Internal work item: [AB#536598](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536598)

**Comment by Groenbech96** [comment]
I like the idea of default email per user group. Can you open an issue on BCApps repo with this? And then lets look at if we can have this as actual built in feature instead of event...
