### ISSUE TITLE
[Event Request] Add event to OnAfterGetRecord in report 5802 "Inventory Valuation - WIP"

### ISSUE THREAD

**Issue by andersws** [microsoft/ALAppExtensions#26537]
### Describe the request

Hi

Can you please add the following event to OnAfterGetRecord on dataitem "Value Entry" in report 5802 "Inventory Valuation - WIP"?

```
trigger OnAfterGetRecord()
// >>>>>>>>>>
var
    SkipDataItem: Boolean;
// <<<<<<<<<
begin
....
        NcValueOfRevalCostPstd := 0;
        NcValueOfCostPstdToGL := 0;
    end;
end;

// >>>>>>>>>>
OnBeforeCalculateTotals(SkipDataItem, ValueOfCostPstdToGL, AtLastDate);
if SkipDataItem
    CurrReport.Skip();
// <<<<<<<<<<

TotalValueOfCostPstdToGL := TotalValueOfCostPstdToGL + ValueOfCostPstdToGL;
TotalValueOfOutput := TotalValueOfOutput + ValueOfOutput;
TotalValueOfCap := TotalValueOfCap + ValueOfCap;
TotalValueOfMatConsump := TotalValueOfMatConsump + ValueOfMatConsump;
TotalValueOfWIP := TotalValueOfWIP + ValueOfWIP;
TotalLastOutput := TotalLastOutput + LastOutput;
TotalAtLastDate := TotalAtLastDate + AtLastDate;
TotalLastWIP := TotalLastWIP + LastWIP;
if CountRecord <> LengthRecord then
    CurrReport.Skip();
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeCalculateTotals(var SkipDataItem: Boolean; ValueOfCostPstdToGL: Decimal; AtLastDate: Decimal)
begin
end;
```

### Additional context

To be able to skip dataitems with zero values in AtLastDate and ValueOfCostPstdToGL.
Internal work item: [AB#536478](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536478)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20237.
