### ISSUE TITLE
[Event Request] Codeunit 11 "Gen. Jnl.-Check Line"

### ISSUE THREAD

**Issue by Chris9821-Work** [microsoft/ALAppExtensions#26536]
### Describe the request

In codeunit 11 "Gen. Jnl.-Check Line": 
in function RunCheck we need an event to skip the check on "Account Type" and "Bal. Account Type": 
![image](https://github.com/microsoft/ALAppExtensions/assets/154224441/83355f7c-4ca7-4632-be4f-e237df193812)

and in the same function an event to skip the TestField on "Applies-to ID"
![image](https://github.com/microsoft/ALAppExtensions/assets/154224441/9f6be04a-ca03-4f81-a69a-a43d92498447)

### Additional context

We need the first one to allow the same account type on debit and credit amount and the second one to change the condition on which to perform the testfield
Internal work item: [AB#536477](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536477)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20276.
