### ISSUE TITLE
[Event Request] codeunit 5751 "Get Source Doc. Inbound" - OnGetSingleWhsePutAwayDocOnAfterGetResultWhsePutAwayRqst

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#26533]
### Describe the request

Hi,

the event "OnGetSingleWhsePutAwayDocOnAfterGetResultWhsePutAwayRqst(WhsePutAwayRequest: Record "Whse. Put-away Request")" is currently not useful. The parameter has to be declared by **var**.

### Additional context

In procedure GetSingleWhsePutAwayDoc the event is called like this:

        WhsePutAwayDocSelection.LookupMode(true);
        WhsePutAwayDocSelection.SetTableView(WhsePutAwayRqst);
        if WhsePutAwayDocSelection.RunModal() <> ACTION::LookupOK then
            exit;

        WhsePutAwayDocSelection.GetResult(WhsePutAwayRqst);

        OnGetSingleWhsePutAwayDocOnAfterGetResultWhsePutAwayRqst(WhsePutAwayRqst);

The variable WhsePutAwayRqst is not initialized but filters are set.
Internal work item: [AB#536475](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536475)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20237.
