### ISSUE TITLE
[Event Request] codeunit 5704 "TransferOrder-Post Shipment"

### ISSUE THREAD

**Issue by Chris9821-Work** [microsoft/ALAppExtensions#26548]
### Describe the request

We need an event in codeunit 5704 "TransferOrder-Post Shipment": 
in function TransferTracking:
```al
OnTransferTrackingOnAfterTransferToTransfer(var TempHandlingSpecification: Record "Tracking Specification", var FromTransLine: Record "Transfer Line"; var ToTransLine: Record "Transfer Line")
``` 
![image](https://github.com/microsoft/ALAppExtensions/assets/154224441/38d7bebe-f974-446c-b55a-3ec95f481f3a)

### Additional context

We need it to change quantity(base) in TempHandlingSpecification based on some checks to perform on Transfer Lines

Internal work item: [AB#536752](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536752)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20246.
