### ISSUE TITLE
Create event to change the "VAT Base Discount %" on Purchase and Service Documents

### ISSUE THREAD

**Issue by MarliesVandeput** [microsoft/ALAppExtensions#26549]
### Describe the request

In Sales Line, there's a function called GetVatBaseDiscountPct(SalesHeader).
This function has a publisher to be able to change this.

In Purchase Line and Service Line there's no function, it goes directly to the "VAT Base Discount %", so we're not able to customize this.

Can this be added to these tables?

### Additional context

For some taxes (G/L Account) there's no payment discount allowed
Internal work item: [AB#536753](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536753)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20246.
