### ISSUE TITLE
[Event Parameter Request] Add parameters to OnBeforeSplitPurchInvCreateBills on codunit 7000005 "Invoice-Split Payment"

### ISSUE THREAD

**Issue by jmorenodynamizatic** [microsoft/ALAppExtensions#26540]
### Describe the request

Add parameters Installment: Record Installment; CurrDocNo: Integer; PaymentTerms: Record "Payment Terms"; RemainingAmount: Decimal; RemainingAmountLCY: Decimal to OnBeforeSplitPurchInvCreateBills like salesvent OnBeforeSplitSalesInvCreateBills.

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSplitPurchInvCreateBills(var GenJournalLine: Record "Gen. Journal Line"; PurchaseHeader: Record "Purchase Header")
    begin
    end;
    >>>>>>>>>>>>>
    local procedure OnBeforeSplitPurchInvCreateBills(var GenJournalLine: Record "Gen. Journal Line"; PurchaseHeader: Record "Purchase Header";Installment: Record Installment; CurrDocNo: Integer; PaymentTerms: Record "Payment Terms"; RemainingAmount: Decimal; RemainingAmountLCY: Decimal)
    <<<<<<<<<<<<    
    begin
    end;

    OnBeforeSplitPurchInvCreateBills(GenJnlLine, PurchHeader);
    >>>>>>>>>>>>>
    OnBeforeSplitPurchInvCreateBills(GenJnlLine, PurchHeader, Installment, CurrDocNo, PaymentTerms, RemainingAmount,     RemainingAmountLCY);
    <<<<<<<<<<<<    

### Additional context

The same event exists for sales

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSplitSalesInvCreateBills(var GenJournalLine: Record "Gen. Journal Line"; SalesHeader: Record "Sales Header"; Installment: Record Installment; CurrDocNo: Integer; PaymentTerms: Record "Payment Terms"; RemainingAmount: Decimal; RemainingAmountLCY: Decimal)
    begin
    end;

    OnBeforeSplitSalesInvCreateBills(GenJnlLine, SalesHeader, Installment, CurrDocNo, PaymentTerms, RemainingAmount, RemainingAmountLCY);
Internal work item: [AB#536597](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536597)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 20279.
