### ISSUE TITLE
[Event Request] Codeunit 10750 "SII XML Creator" - FillThirdPartyId

### ISSUE THREAD

**Issue by BadaboomDev** [microsoft/ALAppExtensions#26543]
### Describe the request

Please add the IsIntraCommunity within the OnFillThirdPartyIdOnBeforeAssignValues Event

```
    local procedure FillThirdPartyId(var XMLNode: DotNet XmlNode; CountryCode: Code[20]; Name: Text; VatNo: Code[20]; BackupVatId: Code[20]; NeedNombreRazon: Boolean; IsIntraCommunity: Boolean; IsNotInAEAT: Boolean; IDTypeInt: Enum "SII ID Type"; SIIDocUploadState: Record "SII Doc. Upload State")
    var
        TempXMLNode: DotNet XmlNode;
        IDType: Text[30];
    begin
        OnFillThirdPartyIdOnBeforeAssignValues(SIIDocUploadState, CountryCode, Name, VatNo);
```

New Integration Event with added Boolean:
```
   [IntegrationEvent(false, false)]
    local procedure OnFillThirdPartyIdOnBeforeAssignValues(SIIDocUploadState: Record "SII Doc. Upload State"; var CountryCode: Code[20]; var Name: Text; var VatNo: Code[20];IsIntraCommunity: Boolean)
    begin
    end;
```

### Additional context

As we use the Vat Registration No., County Code which could differ from the "Buy-to Vendor" we need to inject the correct data including the IsIntraCommunity before writing the Information.
Internal work item: [AB#536600](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536600)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 20594.
