### ISSUE TITLE
Add a new event in the CheckAmountMatchedToAppliedLines() procedure of the Payment Journal page (Page 256) or make this control configurable to be able to skip it.

### ISSUE THREAD

**Issue by NekaneBachillerMayoral** [microsoft/ALAppExtensions#26553]
### Describe the request

Add a new event in the CheckAmountMatchedToAppliedLines() procedure of the Payment Journal page (Page 256) or make this control configurable to be able to skip it.

If you decide to create an event instead of making it configurable we think the code would be:

**Old Code**

    local procedure CheckAmountMatchedToAppliedLines()
    var
        VendorLedgerEntryMarkedToApply: Record ???Vendor Ledger Entry???;
        CustLedgEntryMarkedToApply: Record ???Cust. Ledger Entry???;
        CustEntrySetApplId: Codeunit ???Cust. Entry-SetAppl.ID???;
        VendEntrySetApplId: Codeunit ???Vend. Entry-SetAppl.ID???;
        SmallestLineAmountToApply: Decimal;
        JournalAmount: Decimal;
        AmountToApply: Decimal;
        AmountToApplyMissMatchMsg: Label 'Amount assigned on Apply Entries (%1) is bigger then the amount on the line (%2). System will remove all related Applies-to ID. Do you want to proceed?', Comment = '%1 - Amount to apply, %2 - Amount on the line';
    begin
        if Rec. ???Document Type??? <> Rec. ???Document Type???:: ???Payment??? then
            exit;
......

**Proposed code**

    local procedure CheckAmountMatchedToAppliedLines()
    var
        VendorLedgerEntryMarkedToApply: Record ???Vendor Ledger Entry???;
        CustLedgEntryMarkedToApply: Record ???Cust. Ledger Entry???;
        CustEntrySetApplId: Codeunit ???Cust. Entry-SetAppl.ID???;
        VendEntrySetApplId: Codeunit ???Vend. Entry-SetAppl.ID???;
        SmallestLineAmountToApply: Decimal;
        JournalAmount: Decimal;
        AmountToApply: Decimal;
        _**IsHandled: Boolean;**_
        AmountToApplyMissMatchMsg: Label 'Amount assigned on Apply Entries (%1) is bigger then the amount on the line (%2). System will remove all related Applies-to ID. Do you want to proceed?', Comment = '%1 - Amount to apply, %2 - Amount on the line';
    begin

        _**OnBeforeCheckAmountMatchedToAppliedLines(isHandled);
        if isHandled then
           exit;**_
        if Rec. ???Document Type??? <> Rec. ???Document Type???:: ???Payment??? then
            exit;
.....

### Additional context

The reason is that the process becomes very slow for the user when there are hundreds of payment lines settling debt whose amount is always higher than the amount to be settled since there must be a remainder of those payments.

With this event proposal in some customers we could skip this control that slows down their work.

However, ideally this control should be configurable, so that the customer can decide whether to apply it or not and change his mind later.

Internal work item: [AB#536981](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536981)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 20539.
