### ISSUE TITLE
[Event Request] codeunit 5611 "Calculate Normal Depreciation"

### ISSUE THREAD

**Issue by Chris9821-Work** [microsoft/ALAppExtensions#26558]
### Describe the request

In codeunit 5611 "Calculate Normal Depreciation": 
add parameter DeprMethod to events OnCalculateDeprAmountOnDeprMethodCaseLastEntry and OnCalculateDeprAmountOnDeprMethodCaseLastDeprEntry to handle enum extensions

### Additional context

It's useful to handle enum extension
Internal work item: [AB#536985](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536985)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20439.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 20444.
