### ISSUE TITLE
Add event OnBeforeReservationEntryFindLast into codeunit 99000835 "Item Jnl. Line-Reserve"

### ISSUE THREAD

**Issue by NBTPaolinoMattia** [microsoft/ALAppExtensions#26561]
### Describe the request

The code should be like this:

````
procedure FindReservEntry(ItemJournalLine: Record "Item Journal Line"; var ReservationEntry: Record "Reservation Entry"): Boolean
begin
    ReservationEntry.InitSortingAndFilters(false);
    ItemJournalLine.SetReservationFilters(ReservationEntry);
    OnBeforeReservationEntryFindLast(ReservationEntry,ItemJournalLine);
    exit(ReservationEntry.FindLast());
end;
````

````
[IntegrationEvent(false, false)]
local procedure OnBeforeReservationEntryFindLast(var ReservationEntry: Record "Reservation Entry"; ItemJournalLine: Record "Item Journal Line")
begin
end;
````

### Additional context

This code is usefull for anyone want to modify filters on "Reservation Entry" record before execute FindLast() function.
Internal work item: [AB#536975](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536975)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20256.
