### ISSUE TITLE
[Event Request] New event publisher in OnRun-trigger of Codeunit 395 "FinChrgMemo-Issue"

### ISSUE THREAD

**Issue by GOB-MarcelMo** [microsoft/ALAppExtensions#26568]
### Describe the request

Hello, to be able to use alternative methods of calculation for the variables FinChrgMemoInterestAmount and/or FinChrgMemoInterestVATAmount during the OnRun-trigger of codeunit 395 "FinChrgMemo-Issue", I need a way to access those two variables before they are further used. To achieve this, I request the following publisher: 

Current code:
```
codeunit 395 "FinChrgMemo-Issue"
[???]
trigger OnRun()
[???]
         OnAfterGetFinChrgMemoLine(FinChrgMemoLine, DocNo, CurrencyExchangeRate.ExchangeRate(FinChrgMemoHeader."Posting Date", FinChrgMemoHeader."Currency Code"));
    until FinChrgMemoLine.Next() = 0;

if (FinChrgMemoInterestAmount <> 0) and "Post Interest" then begin
[???]
```

New code:
```
codeunit 395 "FinChrgMemo-Issue"
[???]
trigger OnRun()
[???]
         OnAfterGetFinChrgMemoLine(FinChrgMemoLine, DocNo, CurrencyExchangeRate.ExchangeRate(FinChrgMemoHeader."Posting Date", FinChrgMemoHeader."Currency Code"));
    until FinChrgMemoLine.Next() = 0;

// +++ Begin new code +++
OnAfterCalculateFinChrgMemoInterestAmounts(FinChrgMemoHeader, FinChrgMemoInterestAmount, FinChrgMemoInterestVATAmount);
// +++ End new code +++

if (FinChrgMemoInterestAmount <> 0) and "Post Interest" then begin
[???]

// New publisher
[IntegrationEvent(false, false)]
local procedure OnAfterCalculateFinChrgMemoInterestAmounts(var FinChargeMemoHeader: Record "Finance Charge Memo Header"; var FinChrgMemoInterestAmount: Decimal; var FinChrgMemoInterestVATAmount: Decimal)
begin
end;
```

### Additional context

For our scenario, we want to calculate the variables FinChrgMemoInterestAmount and FinChrgMemoInterestVATAmount differently from the given way while keeping the remainder of the process intact. The existing publisher OnAfterGetFinChrgMemoLine inside the loop is no good fit, as it does not contain the variables and would require us to recalculate the values again through every run of the loop, which would be detrimental to performance. Thus an OnAfter-publisher after the loop is finished seems to be the most sensible option.
Internal work item: [AB#536974](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536974)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20439.
