### ISSUE TITLE
[Event Request] Extension of existing event publisher OnAfterFinChrgMemoLineCreated in Codeunit 394 "FinChrgMemo-Make"

### ISSUE THREAD

**Issue by GOB-MarcelMo** [microsoft/ALAppExtensions#26567]
### Describe the request

Hello, for our implementation I want to request the extension of the existing event publisher OnAfterFinChrgMemoLineCreated in function MakeLines2 of codeunit 394 "FinChrgMemo-Make". The parameters "CurrencyCode" and "TempCurrency2" need to be available at the named publisher.

Current code:
```
codeunit 394 "FinChrgMemo-Make"
[...]
local procedure MakeLines2(CurrencyCode: Code[10]; Checking: Boolean)
[...]
if FinChrgMemoLine.Amount <> 0 then
    if not Checking then
        FinChrgMemoLine.Insert()
    else begin
        TempCurrency2.Code := CurrencyCode;
        if TempCurrency2.Insert() then;
            end;
        OnAfterFinChrgMemoLineCreated(FinChrgMemoLine, Checking);
    until CustLedgEntry.Next() = 0;
end;
[...]
[IntegrationEvent(false, false)]
local procedure OnAfterFinChrgMemoLineCreated(var FinanceChargeMemoLine: Record "Finance Charge Memo Line"; Checking: Boolean)
begin
end;
```

New code:
```
codeunit 394 "FinChrgMemo-Make"
[...]
local procedure MakeLines2(CurrencyCode: Code[10]; Checking: Boolean)
[...]
if FinChrgMemoLine.Amount <> 0 then
    if not Checking then
        FinChrgMemoLine.Insert()
    else begin
        TempCurrency2.Code := CurrencyCode;
        if TempCurrency2.Insert() then;
            end;
        // BEGIN additional parameters
        OnAfterFinChrgMemoLineCreated(FinChrgMemoLine, Checking, CurrencyCode, TempCurrency2);
        // END additional parameters
    until CustLedgEntry.Next() = 0;
end;
[...]
[IntegrationEvent(false, false)]
// New parameters
local procedure OnAfterFinChrgMemoLineCreated(var FinanceChargeMemoLine: Record "Finance Charge Memo Line"; Checking: Boolean; CurrencyCode: Code[10]; var TempCurrency2: Record Currency temporary)
begin
end;
```

### Additional context

We have additional conditions for which we want to either insert the FinChrgMemoLine or add the given currency code to the TempCurrency2-record, depending on if the given Checking-paramter is true or not. To be able to do this, we need access to both the parameter "CurrencyCode" of the function MakeLines2 aswell as the global temporary record "TempCurrency2".
Internal work item: [AB#536988](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536988)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 20504.
