### ISSUE TITLE
[Event Request] Table 904 - Assemble-to-Order Link - NeedsSynchronization(JobPlanningLine: Record Job Planning Line)

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#26569]
### Describe the request

Dear ALAppExtensions team,

Through this issue we would like to request event publisher ``OnBeforeNeedsSynchronization`` to be added to Table 904 "Assemble-to-Order Link" with the following signature:
``````al
    [IntegrationEvent(true, false)]
    local procedure OnBeforeNeedsSynchronization(AssemblyHeader: Record "Assembly Header"; JobPlanningLine: Record "Job Planning Line"; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;

``````

which would be called as follows from ``NeedsSynchronization(JobPlanningLine: Record "Job Planning Line")``:
``````al
    local procedure NeedsSynchronization(JobPlanningLine: Record "Job Planning Line"): Boolean
    var
        IsHandled: Boolean; //New
    begin
        GetAsmHeader();
        //New start
        IsHandled := false;
        OnBeforeNeedsSynchronization(AsmHeader, JobPlanningLine, Result, IsHandled);
        if IsHandled then
            exit(Result); 
        //New end
        AsmHeader.CalcFields("Reserved Qty. (Base)");
``````

### Additional context

Just like for ATO Type Sales we would like to be able to intercept for ATO Type Project.
Unluckily standard BC 24 Assemble-to-Order Link NeedsSynchronization(JobPlanningLine: Record Job Planning Line)  returns false if  the "Job Planning Line" field "Planning Date" is modified.
Internal work item: [AB#536984](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536984)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20256.
