### ISSUE TITLE
Codeunit 2000042 "Post Coded Bank Statement" – New event “OnBeforeSearchVendLedgEntry”

### ISSUE THREAD

**Issue by vanmito** [microsoft/ALAppExtensions#26573]
### Describe the request

Hello,

**Could we please have a new event ???OnBeforeSearchVendLedgEntry??? in function ???SearchVendLedgEntry??? of Codeunit 2000042 "Post Coded Bank Statement"?

    local procedure SearchVendLedgEntry()
    var
        VendLedgEntry2: Record "Vendor Ledger Entry";
        Found: Integer;
        IsHandled: Boolean;
    begin
    // --- Begin New Code ---
        OnBeforeSearchVendLedgEntry(CodBankStmtLine, IsHandled);
        if IsHandled then exit();
    // --- End New Code ---

        Clear(VendLedgEntry);
        with CodBankStmtLine do begin
            if SearchVendor then begin
                VendLedgEntry2.SetCurrentKey("Vendor No.", Open, Positive);
                VendLedgEntry2.SetRange("Vendor No.", Vend."No.");
                VendLedgEntry2.SetRange(Open, true);
                VendLedgEntry2.SetRange(Positive, "Statement Amount" > 0);
                if VendLedgEntry2.FindSet() then
                    repeat
                        VendLedgEntry2.CalcFields("Remaining Amount");
                        if VendLedgEntry2."Remaining Amount" = "Statement Amount" then begin
                            Found := Found + 1;
                            VendLedgEntry := VendLedgEntry2
                        end;
                    until VendLedgEntry2.Next() = 0;

                // Multiple Entries with Same Amount: Do Not Assign

...

...

[IntegrationEvent(false, false)]
local procedure OnBeforeSearchVendLedgEntry(var CODAStatementLine: Record "CODA Statement Line"; var IsHandled: Boolean)
begin
end;

### Additional context

We could like to add this event so we can extend the Vendor Payment functionality of the CODA Statement Line.
Eg.: if we would like a separate handling of the wages.
Internal work item: [AB#536968](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536968)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20607.
