### ISSUE TITLE
[Event Request] table 83 "Item Journal Line" OnAfterShowDimensions

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#26574]
### Describe the request

Can you add xRec to event OnAfterShowDimensions in table 83 "Item Journal Line"?

### Additional context

Need it to check what the dimension set id was before edit dimension set was called.
Internal work item: [AB#536967](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536967)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20421.
