### ISSUE TITLE
[Event Request] PAGE 9800 "Users" - trigger action("Update users from Office")

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#26572]
### Describe the request

Add event in PAGE 9800 "Users" - trigger action("Update users from Office")

### Additional context

action("Update users from Office")

trigger OnAction()
    .......
    if Rec.Count() > UserCountBeforeUpdate then
        CurrPage."Inherited Permission Sets".Page.Refresh();

----------------------- ADD EVENT ----------------------
    OnAfterOnActionUpdateUsersFromOffice(Rec, UserCountBeforeUpdate);
end;
Internal work item: [AB#536965](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536965)

**Comment by mildddd** [comment]
Hello,

I will close the request as there is standard solution. If you there is need for the new event, please create the new request.

Best regards,
Milica

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
