### ISSUE TITLE
[Event Request] table 5405 "Production Order" OnValidateShortcutDimCodeOnBeforeUpdateUpdateAllLineDim

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#26578]
### Describe the request

Can you add event after it checks whether a change has been made?

``` 
    procedure ValidateShortcutDimCode(FieldNumber: Integer; var ShortcutDimCode: Code[20])
    var
        OldDimSetID: Integer;
    begin
        OnBeforeValidateShortcutDimCode(Rec, xRec, FieldNumber, ShortcutDimCode);

        OldDimSetID := "Dimension Set ID";
        DimMgt.ValidateShortcutDimValues(FieldNumber, ShortcutDimCode, "Dimension Set ID");

        if OldDimSetID <> "Dimension Set ID" then begin
            // >>>>>>>>>>>>>>>>>>
            OnValidateShortcutDimCodeOnBeforeUpdateUpdateAllLineDim(Rec, xRec);
            // <<<<<<<<<<<<<<<<<<            
            if Status = Status::Finished then
                Error(Text011);
            Modify();
            if ProdOrderLineExist() then
                UpdateAllLineDim("Dimension Set ID", OldDimSetID);
        end;

        OnAfterValidateShortcutDimCode(Rec, xRec, FieldNumber, ShortcutDimCode);
    end;
```

### Additional context

I'm going to update other dimensions when some dimensions had been updated.
To be able to make UpdateAllLineDim work OldDimSetID must be the dimension set id before i change it.
Otherwise only the dimension updated by BC will be updated to the lines.
Internal work item: [AB#536963](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536963)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20282.
