### ISSUE TITLE
Add integration event for the Danish OIOUBL app

### ISSUE THREAD

**Issue by Lhoumann** [microsoft/ALAppExtensions#26571]
### Describe the request

Add an a new event  "OnAfterExportXMLFile(SalesInvoiceHeader, TempBlob, FileName);" in the codeunits:
codeunit 13636 "OIOUBL-Export Sales Invoice"
codeunit 13637 "OIOUBL-Export Sales Cr. Memo

 
**location is shown in the following for the invoice codunit, but must also be implemented similar for the cr.memo**:
procedure ExportXML(SalesInvoiceHeader: Record "Sales Invoice Header");
    var
        SalesInvHeader2: Record "Sales Invoice Header";
        ElectronicDocumentFormat: Record "Electronic Document Format";
        OIOUBLManagement: Codeunit "OIOUBL-Management";
        TempBlob: Codeunit "Temp Blob";
        FileOutStream: OutStream;
        FileName: Text[250];
    begin
        TempBlob.CreateOutStream(FileOutStream);
        CreateXML(SalesInvoiceHeader, FileOutStream);

        SalesSetup.Get();

        FileName := ElectronicDocumentFormat.GetAttachmentFileName(SalesInvoiceHeader, SalesInvoiceHeader."No.", 'Invoice', 'xml');
        OIOUBLManagement.UpdateRecordExportBuffer(SalesInvoiceHeader.RecordId(), TempBlob, FileName);

        OIOUBLManagement.ExportXMLFile(SalesInvoiceHeader."No.", TempBlob, SalesSetup."OIOUBL-Invoice Path", FileName);
        
**OnAfterExportXMLFile(SalesInvoiceHeader, TempBlob, FileName);**

        SalesInvHeader2.Get(SalesInvoiceHeader."No.");
        SalesInvHeader2."OIOUBL-Electronic Invoice Created" := true;
        SalesInvHeader2.Modify();

        Codeunit.Run(Codeunit::"Sales Inv.-Printed", SalesInvHeader2);
    end;

### Additional context

Please add an event to allow postprocssing after document has been exported in the following CUs:
codeunit 13636 "OIOUBL-Export Sales Invoice"
codeunit 13637 "OIOUBL-Export Sales Cr. Memo
Internal work item: [AB#536966](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536966)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 20287.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20285.
