### ISSUE TITLE
[Event Request] table 5405 "Production Order" OnShowDocDimOnAfterSetDimensionSetID

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#26577]
### Describe the request

Can you add event OnShowDocDimOnAfterSetDimensionSetID to procedure ShowDocDim in "Production Order" OnShowDocDimOnAfterSetDimensionSetID?

```
    procedure ShowDocDim()
    var
        OldDimSetID: Integer;
    begin
        OldDimSetID := "Dimension Set ID";
        TestField("No.");
        "Dimension Set ID" :=
          DimMgt.EditDimensionSet(
            Rec, "Dimension Set ID", StrSubstNo('%1 %2', TableCaption(), "No."),
            "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");
        // >>>>>>>>>>>>>
        OnShowDocDimOnAfterSetDimensionSetID(Rec, xRec); // Rec as reference
        // <<<<<<<<<<<<<
        if OldDimSetID <> "Dimension Set ID" then begin
            if Status = Status::Finished then
                Error(Text011);
            Modify();
            if ProdOrderLineExist() then
                UpdateAllLineDim("Dimension Set ID", OldDimSetID);
        end;
    end;
```

### Additional context

I'm going to update other dimensions when some dimensions had been updated. 
Internal work item: [AB#536964](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/536964)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20282.
