### ISSUE TITLE
Add Integration Events to work with Excel reports.

### ISSUE THREAD

**Issue by arvindbinarystream** [microsoft/ALAppExtensions#26581]
### Describe the request

There is an integration event that I would like to request to support "Dynamics BC Excel Report" with our product.
With our product we are extending these report using report extensions, however we need a integration event to be added on few reports in order to implement our logic. Also, I would like to make another request, mark procedure **AddGLToDataset** as global. So, I can access it with the integration event. 

Required Integration Events are as follows.

1. Report 4405 "EXR Trial Balance Excel"
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/92b6d0b0-21f3-4b8e-a8a9-36db8deac141)

- Event Signature will be 
- [IntegrationEvent(true, false)]
-     local procedure OnBeforeInsertGLAccountData(GLAccount:Record "G/L Account"; DimensionValue1: Record "Dimension Value"; DimensionValue2: Record "Dimension Value"; var Handled:Boolean)
-     begin
-     end; 

2. Report 4406 "EXR Trial BalanceBudgetExcel"
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/1eb13361-0d3d-4949-85e1-220fe1ebc843)

- Event Signature will be 
- [IntegrationEvent(true, false)]
-     local procedure OnBeforeInsertGLAccountData(GLAccount:Record "G/L Account"; DimensionValue1: Record "Dimension Value"; DimensionValue2: Record "Dimension Value"; var Handled:Boolean)
-     begin
-     end; 

3. Report 4407 "EXR Trial Bal. Prev Year Excel"
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/1eb13361-0d3d-4949-85e1-220fe1ebc843)

- Event Signature will be 
- [IntegrationEvent(true, false)]
-     local procedure OnBeforeInsertGLAccountData(GLAccount:Record "G/L Account"; DimensionValue1: Record "Dimension Value"; DimensionValue2: Record "Dimension Value"; var Handled:Boolean)
-     begin
-     end; 

4. Report 4408 "EXR Trial Bal by Period Excel"
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/c05dfe37-2bd7-4077-be95-8bff60f39587)

- Event Signature will be 
- [IntegrationEvent(true, false)]
-     local procedure OnBeforeInsertGLAccountData(ReportingPeriodStartDate: List of [Date]; ReportingPeriodEndDate: List of [Date]; GLAccount:Record "G/L Account"; DimensionValue1: Record "Dimension Value"; DimensionValue2: Record "Dimension Value"; var Handled:Boolean)
-     begin
-     end;

### Additional context

With our product we filters transaction data with Dimension 1 or Dimension 2 values (depending on how it has been setup) while calculating trial balance.

Example: Our product have been setup with Dimension 1, in that case when user runs trial balance report, it must calculate trial balance for the transaction data that has non empty "Global Dimension 1 Code" value assigned.

On excel reports while running trial balance report, business central add all transactions data with or without Dimension value assigned while calculating trial balance.

Internal work item: [AB#537213](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537213)

**Comment by mynjj** [comment]
Trial Balance related reports have had some fixes, and the logic is now "centralized" in a codeunit.

The changes requested here are no longer applicable.

Please have a look at how the implementation changed in v25 and if you still have extensibility needs let us know. Sorry for the delay.
