### ISSUE TITLE
[Event Request] codeunit 311 "Item-Check Avail." OnCalculateOnBeforeCalcInitialQtyAvailable 

### ISSUE THREAD

**Issue by Kryshi** [microsoft/ALAppExtensions#26582]
### Describe the request

Please add the variable "InventoryQty" as a var to this event 

### Additional context

Our use case requires us to modify this variable conditionally after the standard calculation in procedure QtyAvailToPromise, however, currently the only way to access this variable is to access it through event OnBeforeQtyAvailToPromise in procedure QtyAvailToPromise and overwrite the standard code. Alternatively, an event OnAfterQtyAvailToPromise exposing the calculated variables would also be helpful.
Internal work item: [AB#537212](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537212)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20421.
