### ISSUE TITLE
[Bug]: Issue while calculating balance in trial balance excel reports.

### ISSUE THREAD

**Issue by arvindbinarystream** [microsoft/ALAppExtensions#26580]
### Describe the issue

In new excel reports that business central added with v24 in "Dynamics BC Excel Reports" extension seems to have some bugs.
1) report 4405 **"EXR Trial Balance Excel"**
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/c5517f37-a801-4725-b38e-817af5057432)
To calculate correct value of **"Net Change"**, **"Balance at Date"**, **"Additional-Currency Net Change"**, **"Add.-Currency Balance at Date"** for a G/L Account record, filters must be set to flow filters fields **"Global Dimension 1 Filter"** and **"Global Dimension 2 Filter"** of G/L Account record.
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/437014d6-5033-4b25-9360-0feb99b59278)

Same issue happens in report 4406 **"EXR Trial BalanceBudgetExcel"** and report 4408 **"EXR Trial Bal by Period Excel"**.

### Expected behavior

"Trial balance Excel (Preview)" report should calculate correct netchange , Balance values for all chart of account with Dimension combinations.

Result in Business central: For chart of account **14130** for Dimension Combination **Dimension1Code: '' and Dimension2Code:''**
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/6464a1ac-1a69-49c5-ac01-563aecbb4331)

Result in Business central: For chart of account **14130** for Dimension Combination **Dimension1Code: '000' and Dimension2Code:'LARGE'**
![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/ad92fd1f-26ac-4cc5-b0d1-300e58dd2ba5)

### Steps to reproduce

Run report **"Trial Balance Excel (Preview)"**.
Once excel file is downloads, open and verify **TrialBalanceData** sheet in excel file.
For example, I have uploaded my result from my data here.
Result in report: For chart of account **14130**, NetChange and Balance values are exactly same for all dimension combinations.

![image](https://github.com/microsoft/ALAppExtensions/assets/103695453/d502dbd5-eef7-4b88-a411-ef7056dc1e9a)

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
You might be on to something here, but since the code you are referring to is in the BaseApp, you'd have to suggest and fix this code in the BaseApp contribution pilot: https://github.com/microsoft/businesscentralapps. For access to the pilot, please fill out the following form: https://forms.office.com/r/E9wyE5a58f.

This repository is only for extensibility requests or pull requests towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps).

Would you like me to move the issue to the contribution pilot for you?

**IMPORTANT:** Microsoft is not going to address the reported issue for you. You will have to get the issue approved, and then push a pull request with the suggested changes yourself. If you would like Microsoft to address the issue, please create a support request.

**Comment by arvindbinarystream** [comment]
@JesperSchulzm thanks for your response. It seems that the change I am requesting is not in the Base App but in the "Dynamics BC Excel Reports" extension. Please guide me how can I request for this extension.

**Comment by JesperSchulz** [comment]
Ah, sorry, I thought report 4405 was in the BaseApp, but my query was wrong. The report is of course in the "Dynamics BC Excel Reports" app, which is a 1st party app. That app is in this repository, so all good 😊. Based on that, I approve this issue.

**Comment by arvindbinarystream** [comment]
@JesperSchulz , thanks for the response. Should I create a PR for the above issue?

**Comment by Cath59** [comment]
The same problem for Excel report 4406 "EXR Trial BalanceBudgetExcel"

The procedure 'AddGLToDataset' is correct in the report 4407 "EXR Trial Bal. Prev Year Excel"

**Comment by JesperSchulz** [comment]
You are most welcome to do so!

**Comment by arvindbinarystream** [comment]
@JesperSchulz Thanks for your response. Looking at the latest code in this repository it seems that correct logic is implemented now. So, the issue I mentioned above will be resolved and I don't need to create a PR for anymore.

**Comment by mynjj** [comment]
Closing, the bug has been implemented and it will be shipped in a future release.

**Comment by PaddyB69** [comment]
Hi 

Can i point out this bug also appears on  report 10023.
Variable PrintAmount[i] needs to be cleared too.

I checked ver14 to ver24

**Comment by mynjj** [comment]
hi @PaddyB69 , thanks for reporting, this report has been updated for v27 too.
