### ISSUE TITLE
[Request for External] Codeunit AccSchedManagement - Function DrillDownOnGlAccCatFilter

### ISSUE THREAD

**Issue by DanielHaglo** [microsoft/ALAppExtensions#26597]
### Describe the request

Could GLAccAnalysisView be added to the event as VAR?

```
 end else begin
                    OnDrillDownOnGLAccountOnBeforeCopyFiltersWithAnalysisView(AccScheduleLine, TempColumnLayout, GLAcc,GLAccAnalysisView);
                    GLAcc.CopyFilter("Date Filter", GLAccAnalysisView."Date Filter");
                    GLAcc.CopyFilter("Budget Filter", GLAccAnalysisView."Budget Filter");
                    GLAcc.CopyFilter("Business Unit Filter", GLAccAnalysisView."Business Unit Filter");
```

```
    [IntegrationEvent(false, false)]
    local procedure OnDrillDownOnGLAccountOnBeforeCopyFiltersWithAnalysisView(var AccScheduleLine: Record "Acc. Schedule Line"; var TempColumnLayout: Record "Column Layout"; var GLAcc: Record "G/L Account",var GLAccAnalysisView: Record "G/L Account (Analysis View)";)
    begin
    end;
```

### Additional context

I need to set filter on the record
Internal work item: [AB#537231](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537231)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20457.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 20491.
