### ISSUE TITLE
[Parameter Request] COD 225 - OnSelectCustLedgEntryOnAfterSetFilters(AccNo)

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#2660]
In COD 225, function SelectCustLedgEntry, we'd like to allow selecting customer ledger entries in case the customer (AccNo) is not filled on the journal line as well. We've implemented a feature of 'head' customers to group customers from a same master company together. When applying, we might not know the exact customer, so we want to filter the ledger entries on 'head' / group customer instead to allow easier retrieval of the right customer.

Therefore, following code line is added in SelectCustLedgEntry
```
IF (AccNo <> '') THEN //NVTBE-0064/Apply also via headcustomer
  CustLedgEntry.SETRANGE("Customer No.",AccNo);  

```
The new publisher OnSelectCustLedgEntryOnAfterSetFilters could support us in moving this code away, but therefore we need access to the '**AccNo**' value in the publisher

LOCAL [IntegrationEvent] OnSelectCustLedgEntryOnAfterSetFilters(VAR CustLedgerEntry : Record "Cust. Ledger Entry";GenJournalLine : Record "Gen. Journal Line"; **AccNo**)

_Please update the OnSelectEmplLedgEntryOnAfterSetFilters, OnSelectVendLedgEntryOnAfterSetFilters events accordingly._

**Comment by AlexanderYakunin** [comment]
You already have events to implement this here

**Comment by fvet** [comment]
@AlexanderYakunin. Do'nt know how I can workaround the suggested code, but I think I would at least need access to the 'AccNo' variable in the 'OnSelectCustLedgEntryOnAfterSetFilters' pusblisher (or GlobalVarAccess?), which is not available in BC 140 Cu1 as far as I could see...

**Comment by fvet** [comment]
@jobulsin Not sure based on the comments of AlexanderYakunin vs the Label 'ships-in-future-update' if the requested parameter is accepted?

**Comment by AlexanderYakunin** [comment]
You don't need this change. Field Customer No. in CustLedgEntry already filtered by AccNo, so you can easily do GETFILTER to get AccNo in your code.
