### ISSUE TITLE
[Event Request] Add Purchase Invoice Record to the OnCancelPostedInvoiceOnBeforeShowPurchaseInvoice event in "Correct PstdPurchInv (Yes/No)"

### ISSUE THREAD

**Issue by diogoviegas2855** [microsoft/ALAppExtensions#26605]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=30db9185-8222-ef11-8ee8-00224852faff

### Description

Add Purchase Invoice Record to the OnCancelPostedInvoiceOnBeforeShowPurchaseInvoice event in "Correct PstdPurchInv (Yes/No

### I will provide the implementation for this BC Idea

- [ ] I will provide the implementation for this BC Idea
Internal work item: [AB#538576](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538576)

**Comment by diogoviegas2855** [comment]
Hi
Can you please Add Purchase Invoice Record to the OnCancelPostedInvoiceOnBeforeShowPurchaseInvoice event in "Correct PstdPurchInv (Yes/No)"

Actual Code:

local procedure CancelPostedInvoiceAndOpenNewPurchaseInvoice(var PurchInvHeader: Record "Purch. Inv. Header"): Boolean
    var
        PurchaseHeader: Record "Purchase Header";
        ConfirmManagement: Codeunit "Confirm Management";
        CorrectPostedPurchInvoice: Codeunit "Correct Posted Purch. Invoice";
        IsHandled: Boolean;
    begin
        if ConfirmManagement.GetResponse(CorrectPostedInvoiceQst, false) then begin
            CorrectPostedPurchInvoice.CancelPostedInvoiceStartNewInvoice(PurchInvHeader, PurchaseHeader);
            IsHandled := false;
            OnCancelPostedInvoiceOnBeforeShowPurchaseInvoice(PurchaseHeader, IsHandled);
            if not IsHandled then
                PAGE.Run(PAGE::"Purchase Invoice", PurchaseHeader);
            exit(true);
        end;

        exit(false);
    end;

[IntegrationEvent(false, false)]
    local procedure OnCancelPostedInvoiceOnBeforeShowPurchaseInvoice(var PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
    begin
    end;

**Comment by diogoviegas2855** [comment]
Suggestion Code:

local procedure CancelPostedInvoiceAndOpenNewPurchaseInvoice(var PurchInvHeader: Record "Purch. Inv. Header"): Boolean
var
PurchaseHeader: Record "Purchase Header";
ConfirmManagement: Codeunit "Confirm Management";
CorrectPostedPurchInvoice: Codeunit "Correct Posted Purch. Invoice";
IsHandled: Boolean;
begin
if ConfirmManagement.GetResponse(CorrectPostedInvoiceQst, false) then begin
CorrectPostedPurchInvoice.CancelPostedInvoiceStartNewInvoice(PurchInvHeader, PurchaseHeader);
IsHandled := false;
OnCancelPostedInvoiceOnBeforeShowPurchaseInvoice(PurchaseHeader, PurchInvHeader, IsHandled);
if not IsHandled then
PAGE.Run(PAGE::"Purchase Invoice", PurchaseHeader);
exit(true);
end;

    exit(false);
end;
[IntegrationEvent(false, false)]
local procedure OnCancelPostedInvoiceOnBeforeShowPurchaseInvoice(var PurchaseHeader: Record "Purchase Header"; PurchInvHeader: Record "Purch. Inv. Header"; var IsHandled: Boolean)
begin
end;

**Comment by JesperSchulz** [comment]
@diogoviegas2855, this is a simple event request. No need to create a BCIdea for those. We'll triage and get back to you.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21022.
