### ISSUE TITLE
[Event Request] table 5406 "Prod. Order Line" OnShowDimensionsOnAfterEditDimensionSet

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#26619]
### Describe the request

Can you add event OnShowDimensionsOnAfterEditDimensionSet

```
    procedure ShowDimensions()
    var
        OldDimSetID: Integer;
    begin
        OldDimSetID := "Dimension Set ID";
        "Dimension Set ID" :=
          DimMgt.EditDimensionSet(
            Rec, "Dimension Set ID", StrSubstNo('%1 %2 %3', Status, "Prod. Order No.", "Line No."),
            "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");
// >>>>>>>>>>>>>>>>
OnShowDimensionsOnAfterEditDimensionSet(Rec, OldDimSetID); // Rec as reference
// <<<<<<<<<<<<<<<<
        if OldDimSetID <> "Dimension Set ID" then begin
            Modify();
            if ProdOrderCompExist() then
                UpdateProdOrderCompDim("Dimension Set ID", OldDimSetID);
        end;
    end;
```

### Additional context

To be able to check and update other dimensions.
Internal work item: [AB#537651](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537651)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21842.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 21929.
