### ISSUE TITLE
[Event Request] codeunit 5522 "Order Planning Mgt." - OnSetFilterOnBeforeFindUnplannedDemandForInsertDemandLines

### ISSUE THREAD

**Issue by mtaanquist** [microsoft/ALAppExtensions#26615]
### Describe the request

To affect the final ordering or output of the Order Planning page, it would be helpful to have a means to change the sorting or filters before the Requisition Line is created from the Unplanned Demand.

Code changes in codeunit 5522 "Order Planning Mgt."
```diff
    local procedure InsertDemandLines(var ReqLine: Record "Requisition Line")
    var
        UnplannedDemand: Record "Unplanned Demand";
        Item: Record Item;
        HeaderExists: Boolean;
    begin
        UnplannedDemand.Copy(TempUnplannedDemand);

        TempUnplannedDemand.Reset();
        TempUnplannedDemand.SetRecFilter();
        TempUnplannedDemand.SetRange("Demand Line No.");
        TempUnplannedDemand.SetRange("Demand Ref. No.");
        TempUnplannedDemand.SetRange(Level, 1);
+       OnSetFilterOnBeforeFindUnplannedDemandForInsertDemandLines(TempUnplannedDemand, ReqLine);
        TempUnplannedDemand.Find('-');
        HeaderExists := false;

        repeat
            if DemandType in [TempUnplannedDemand."Demand Type", DemandType::" "] then begin
                if not HeaderExists then
                    InsertDemandHeader(UnplannedDemand, ReqLine);
                HeaderExists := true;

                ReqLine.TransferFromUnplannedDemand(TempUnplannedDemand);
                ReqLine.SetSupplyQty(TempUnplannedDemand."Quantity (Base)", TempUnplannedDemand."Needed Qty. (Base)");
                ReqLine.SetSupplyDates(TempUnplannedDemand."Demand Date");
                InsertReqLineFromUnplannedDemand(ReqLine, Item);
            end;
            TempUnplannedDemand.Delete();
        until TempUnplannedDemand.Next() = 0;

        TempUnplannedDemand.Copy(UnplannedDemand);
    end;
```

Event publisher:
```
[IntegrationEvent(false, false)]
local procedure OnSetFilterOnBeforeFindUnplannedDemandForInsertDemandLines(var TempUnplannedDemand: Record "Unplanned Demand" tempory; var RequisitionLine: Record "Requisition Line")
begin
end;  
```

### Additional context

We have customers where they had hoped to be able to sort the "level 1" lines based on the demand dates for Projects, but it appears only the top level of the orders in the Order Planning is sorted by date. Once you expand a project in the planning view, the sorting is done by the order in which the job lines were created. This would help 
Internal work item: [AB#537648](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537648)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20692.
