### ISSUE TITLE
Add "LastCreatedDocumentId" in the "OnBeforeCreateSalesHeader" in Shopify Connector

### ISSUE THREAD

**Issue by CaianiRiccardo** [microsoft/ALAppExtensions#26618]
### Describe the request

Add the GUID variable "LastCreatedDocumentId" in the OnBeforeCreateSalesHeader event for the Shopify connector in the codeunit 30166 "Shpfy Process Order".

### Additional context

As of today if someone subcribe to the event but something go wrong and there is a runtime error the system has no way to use the standard function to clean the documents created and multiple error documents can be created.

Here is a portion of the standard code where the event is called and the LastCreatedDocumentId is set ( in a if not IsHandled condition )
```
OrderEvents.OnBeforeCreateSalesHeader(ShopifyOrderHeader, SalesHeader, IsHandled);
        if not IsHandled then begin
            ShopifyOrderHeader.TestField("Sell-to Customer No.");
            SalesHeader.Init();
            SalesHeader.SetHideValidationDialog(true);
            if ShopifyOrderHeader."Fulfillment Status" = ShopifyOrderHeader."Fulfillment Status"::Fulfilled then
                SalesHeader.Validate("Document Type", SalesHeader."Document Type"::Invoice)
            else
                SalesHeader.Validate("Document Type", SalesHeader."Document Type"::Order);
            SalesHeader.Insert(true);
            LastCreatedDocumentId := SalesHeader.SystemId;
```

This is the standard entry point for the creation of the document
```
internal procedure ProcessShopifyOrder(ShopifyOrderHeader: Record "Shpfy Order Header")
    var
        ProcessOrder: Codeunit "Shpfy Process Order";
    begin
        if not ShopifyOrderHeader.Processed then begin
            if not ProcessOrder.Run(ShopifyOrderHeader) then begin
                ShopifyOrderHeader.Get(ShopifyOrderHeader."Shopify Order Id");
                ShopifyOrderHeader."Has Error" := true;
                ShopifyOrderHeader."Error Message" := CopyStr(Format(Time) + ' ' + GetLastErrorText(), 1, MaxStrLen(ShopifyOrderHeader."Error Message"));
                ShopifyOrderHeader."Sales Order No." := '';
                ShopifyOrderHeader."Sales Invoice No." := '';
                ProcessOrder.CleanUpLastCreatedDocument();   // cannot be correctly be processed for lack of guid
            end else begin
                ShopifyOrderHeader.Get(ShopifyOrderHeader."Shopify Order Id");
                ShopifyOrderHeader."Has Error" := false;
                ShopifyOrderHeader."Error Message" := '';
                ShopifyOrderHeader.Processed := true;
            end;
            ShopifyOrderHeader.Modify(true);
            Commit();
        end;
    end;
```
Internal work item: [AB#537652](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537652)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21234.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 21329.
