### ISSUE TITLE
[Scope change] table 8620 "Config. Tmpl. Selection Rules" - FindTemplateBasedOnRecordFields

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26611]
### Describe the request

Can you please remove the 'OnPrem' scope of function FindTemplateBasedOnRecordFields in table 8620 "Config. Tmpl. Selection Rules"?

### Additional context

We'd like to use the 'API Setup' framework for custom development
Internal work item: [AB#537583](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537583)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24627.
