### ISSUE TITLE
[Event Request] table 81 "Gen. Journal Line" OnAfterShowDimensions

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#26617]
### Describe the request

Can you add event OnAfterShowDimensions:

```
    procedure ShowDimensions() IsChanged: Boolean
    var
        OldDimSetID: Integer;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeShowDimensions(Rec, xRec, IsHandled);
        if IsHandled then
            exit;

        OldDimSetID := "Dimension Set ID";
        "Dimension Set ID" :=
          DimMgt.EditDimensionSet(
            Rec, "Dimension Set ID", StrSubstNo('%1 %2 %3', "Journal Template Name", "Journal Batch Name", "Line No."),
            "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");

        IsChanged := OldDimSetID <> "Dimension Set ID";

        // >>>>>>>>>>>>>>>>>
        OnAfterShowDimensions(Rec, xRec, OldDimSetID, IsChanged); // Rec and IsChanged as reference
        // <<<<<<<<<<<<<<<<<
    end;
```

### Additional context

I need this to be able to update and check additional dimensions after the user has changed dimensions.
Internal work item: [AB#537650](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537650)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20812.
