### ISSUE TITLE
[Event Request] table 5902 "Service Line" OnAfterShowDimensions

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#26620]
### Describe the request

```
    procedure ShowDimensions()
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeShowDimensions(Rec, xRec, IsHandled);
        if IsHandled then
            exit;

        if ("Contract No." <> '') and ("Appl.-to Service Entry" <> 0) then
            ViewDimensionSetEntries()
        else
            "Dimension Set ID" :=
              DimMgt.EditDimensionSet(
                Rec, "Dimension Set ID", StrSubstNo('%1 %2 %3', "Document Type", "Document No.", "Line No."),
                "Shortcut Dimension 1 Code", "Shortcut Dimension 2 Code");
// >>>>>>>>>>>
OnAfterShowDimensions(Rec, xRec); //Rec as reference
// <<<<<<<<<<<
    end;
```

### Additional context

Need to check and update other dimensions
Internal work item: [AB#537649](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537649)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 20806.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: <None>.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20812.
