### ISSUE TITLE
[Event Request] Missing requested event - Page 143 "Posted Sales Invoices"

### ISSUE THREAD

**Issue by GMatuleviciute** [microsoft/ALAppExtensions#26628]
### Describe the request

Hello, 

In February I requested the OnBeforeAfterGetCurrRecord event on the OnAfterGetCurrRecord() trigger on page 143 "Posted Sales Invoices" (link to request: https://github.com/microsoft/ALAppExtensions/issues/25849).  The request was approved.

Other requested events in February with the same assigned build ID have already been added. But, this one is still missing. I have checked versions 23.8.20231.0 and 24.1.18927.19498, but I could not find it. Could you please let me know why this might have happened?

I really appreciate your help. Thank you very much!

### Additional context

We need this event to override the trigger.
Internal work item: [AB#538371](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538371)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20959.
