### ISSUE TITLE
[Event Request] table 5901 "Service Item Line"

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#26621]
### Describe the request

Add xRec to OnShowDimensionsOnBeforeServiceItemLineModify

### Additional context

I need this to get the old dimension set id
Internal work item: [AB#537655](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/537655)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20812.
