### ISSUE TITLE
Add event OnAfterGetGLSetup into codeunit 12 "Gen. Jnl.-Post Line"

### ISSUE THREAD

**Issue by NBTPaolinoMattia** [microsoft/ALAppExtensions#26627]
### Describe the request

The code should be like this:

````
procedure GetGLSetup()
begin
    if GLSetupRead then
        exit;

    GLSetup.Get();
    GLSetupRead := true;

    AddCurrencyCode := GLSetup."Additional Reporting Currency";
    OnAfterGetGLSetup(GLSetup, GLSetupRead, AddCurrencyCode);
end;
````

````
[IntegrationEvent(false, false)]
local procedure OnAfterGetGLSetup(var GLSetup: Record "General Ledger Setup"; var  GLSetupRead: Boolean;; AddCurrencyCode: Code[10])
begin
end;
````

### Additional context

This event is usefull for anyone want to do more program logic after getting GLSetup.
Internal work item: [AB#538370](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538370)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 21537.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21545.
