### ISSUE TITLE
[Event Request] OnAfterSetDtldEmplLedgEntryNoOffset at codeunit 12 "Gen. Jnl.-Post Line"

### ISSUE THREAD

**Issue by vlkov** [microsoft/ALAppExtensions#26639]
### Describe the request

Create add a new events in codeunit 12 "Gen. Jnl.-Post Line"
Add events like a OnAfterSetDtldCustLedgEntryNoOffset for employee accounts, raise at PostDtldEmplLedgEntries before DtldCVLedgEntryBuf.FindSet line 

OnAfterSetDtldEmplLedgEntryNoOffset(DtldCVLedgEntryBuf);

### Additional context

`[IntegrationEvent(false, false)]`
`local procedure OnAfterSetDtldEmplLedgEntryNoOffset(var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer")`
`begin`
`end;`
Internal work item: [AB#538380](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538380)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 21537.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21545.
