### ISSUE TITLE
Add event OnBeforeSetSources into codeunit 6501 "Item Tracking Data Collection" 

### ISSUE THREAD

**Issue by Flavioide** [microsoft/ALAppExtensions#26632]
### Describe the request

procedure LookupTrackingAvailability(var TempTrackingSpecification: Record "Tracking Specification" temporary; LookupMode: Enum "Item Tracking Type")
    var
        ItemTrackingSummaryForm: Page "Item Tracking Summary";
        Window: Dialog;
    begin
        if ShouldExitLookupTrackingAvailability(TempTrackingSpecification, LookupMode) then
            exit;

        Clear(ItemTrackingSummaryForm);
        Window.Open(Text004);
        TempGlobalChangedEntrySummary.Reset();

        if not (PartialGlobalDataSetExists or FullGlobalDataSetExists) then
            RetrieveLookupData(TempTrackingSpecification, true);

        TempGlobalEntrySummary.Reset();
        TempGlobalEntrySummary.SetTrackingKey();

        TempGlobalReservEntry.Reset();

        case LookupMode of
            LookupMode::"Serial No.":
                begin
                    TempGlobalEntrySummary.SetRange("Serial No.", TempTrackingSpecification."Serial No.");
                    TempGlobalEntrySummary.SetFilter("Table ID", '<>%1', 0); // Filter out summations
                    TempGlobalReservEntry.SetRange("Serial No.", TempTrackingSpecification."Serial No.");
                    ItemTrackingSummaryForm.Caption := StrSubstNo(
                        AvailabilityText, TempTrackingSpecification.FieldCaption("Serial No."), TempTrackingSpecification."Serial No.");
                end;
            LookupMode::"Lot No.":
                begin
                    TempGlobalEntrySummary.SetRange("Serial No.", '');
                    TempGlobalEntrySummary.SetRange("Lot No.", TempTrackingSpecification."Lot No.");
                    TempGlobalReservEntry.SetRange("Lot No.", TempTrackingSpecification."Lot No.");
                    ItemTrackingSummaryForm.Caption := StrSubstNo(
                        AvailabilityText, TempTrackingSpecification.FieldCaption("Lot No."), TempTrackingSpecification."Lot No.");
                end;
            else
                OnLookupTrackingAvailabilityOnSetFiltersElseCase(
                    TempGlobalEntrySummary, TempGlobalReservEntry, TempTrackingSpecification, ItemTrackingSummaryForm, LookupMode);
        end;
       OnBeforeSetSources(TempGlobalEntrySummary, TempTrackingSpecification, LookupMode)
        ItemTrackingSummaryForm.SetSources(TempGlobalReservEntry, TempGlobalEntrySummary);
        ItemTrackingSummaryForm.SetCurrentBinAndItemTrkgCode(CurrBinCode, CurrItemTrackingCode);
        ItemTrackingSummaryForm.LookupMode(false);
        ItemTrackingSummaryForm.SetSelectionMode(false);
        Window.Close();
        ItemTrackingSummaryForm.RunModal();
    end;

````
[IntegrationEvent(false, false)]
local procedure OnBeforeSetSources(var TempGlobalEntrySummary: Record "Entry Summary" temporary; TempTrackingSpecification: Record "Tracking Specification" temporary; LookupMode: Enum "Item Tracking Type")
begin
end;


### Additional context

This event is usefull for anyone want to add/modify filters
Internal work item: [AB#538374](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538374)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20959.
