### ISSUE TITLE
[EVENT REQUEST] Table 5802 "Inventory Posting To G/L" OnBeforeBufferCapacityPosting

### ISSUE THREAD

**Issue by OWaechter** [microsoft/ALAppExtensions#26635]
### Describe the request

Please add an OnBefore Event for the BufferCapacityPosting function in Table 5802, similar to the BufferConsumptionPosting. It should look like the following.   

```al
 local procedure BufferCapacityPosting(ValueEntry: Record "Value Entry"; CostToPost: Decimal; CostToPostACY: Decimal; ExpCostToPost: Decimal; ExpCostToPostACY: Decimal)
    var
       IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeBufferCapacityPosting(ValueEntry, TempGlobalInvtPostingBuffer, CostToPost, CostToPostACY, ExpCostToPost, ExpCostToPostACY, IsHandled);
        if IsHandled then
           exit;

        with ValueEntry do
``` 

The IntegrationEvent
```al
    [IntegrationEvent(TRUE, false)]
    local procedure OnBeforeBufferCapacityPosting(var ValueEntry: Record "Value Entry"; var GlobalInvtPostBuf: Record "Invt. Posting Buffer"; CostToPost: Decimal; CostToPostACY: Decimal; ExpCostToPost: Decimal; ExpCostToPostACY: Decimal; var IsHandled: Boolean)
    begin
    end;
``` 

### Additional context

Just like for Consumption and Output Postings it should be possible to Substitute the standard code.
Internal work item: [AB#538377](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538377)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21820.
