### ISSUE TITLE
codeunit 5851 "Invt. Doc.-Post Shipment" - procedure SetPreviewMode - request for the protection level change

### ISSUE THREAD

**Issue by MaksymRud** [microsoft/ALAppExtensions#26636]
### Describe the request

During the development of an extension that requires the use of the preview mode of **codeunit 5851 "Invt. Doc.-Post Shipment"**, we encountered an issue due to the current protection level of the **SetPreviewMode** procedure. The existing protection level (**internal**) prevents us from modifying this behavior.
![image](https://github.com/microsoft/ALAppExtensions/assets/47670164/a2ee1439-6d38-495b-bd07-388e32249ef2)
We kindly request that the protection level of the **SetPreviewMode** procedure be adjusted to **public**. 

### Additional context

The main issue is that without proper usage of the preview mode, the previewed document is deleted during posting (we rollback the changes afterward), causing the document page to close. The current protection level of the **SetPreviewMode** procedure forbids us from correcting this behavior.
![image](https://github.com/microsoft/ALAppExtensions/assets/47670164/26b3c3d2-e523-4d77-9a68-88d9d0b526e4)
The requested change will enable us to effectively utilize the preview mode in our extension, improving a user experience.
Internal work item: [AB#538378](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538378)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21170.
