### ISSUE TITLE
Add event OnBeforeUpdateBinContent into codeunit 6501 "Item Tracking Data Collection"

### ISSUE THREAD

**Issue by Flavioide** [microsoft/ALAppExtensions#26634]
### Describe the request

 local procedure UpdateBinContent(var TempEntrySummary: Record "Entry Summary" temporary)
    var
        WarehouseEntry: Record "Warehouse Entry";
        WhseItemTrackingSetup: Record "Item Tracking Setup";
        IsHandled: Boolean;
    begin

         OnBeforeUpdateBinContent (TempEntrySummary, CurrItemTrackingCode,IsHandled);
        if IsHandled then exit;

        if CurrBinCode = '' then
            exit;
````
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateBinContent (var TempEntrySummary: Record "Entry Summary" temporary; CurrItemTrackingCode: Record "Item Tracking Code";var IsHandled:boolean)
begin
end;


### Additional context



This event is usefull for anyone want to skip or manage the bin content
Internal work item: [AB#538375](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538375)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20959.
