### ISSUE TITLE
Access to global vars in page 12161 "Declaration of Intent Export"

### ISSUE THREAD

**Issue by fifr-reply** [microsoft/ALAppExtensions#26645]
### Describe the request

Could you please set all global variables in page 12161 "Declaration of Intent Export" as `protected`, so they can be accessed from pageextensions?
```
 var
        VATExemption: Record "VAT Exemption";
        AmountToDeclare: Decimal;
        CeilingType: Option "Fixed",Mobile;
        SigningCompanyOfficialsNo: Code[20];
        ExportFlags: array[6] of Boolean;
        SupplementaryReturn: Boolean;
        DescriptionOfGoods: Text[100];
        TaxAuthorityReceiptsNo: Text[17];
        TaxAuthorityDocNo: Text[6];

    procedure Initialize(var VATExemption2: Record "VAT Exemption")
    begin
        VATExemption := VATExemption2;
    end;
```

Alternatively, getter/setter procedures may be added in analogy to what `Initialize` does for `VATExemption`.

### Additional context

Having access to the page variables allows us to develop custom logic based on them without duplicating the entire object.
Internal work item: [AB#538388](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538388)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21087.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 21100.
