### ISSUE TITLE
[Bug]: GetNoSeriesLine - Error when searching for the last record, missing setcurrentkey

### ISSUE THREAD

**Issue by mpachecodynamizatic** [microsoft/ALAppExtensions#26646]
### Describe the issue

With the latest change 24.0.1610.20505 it does not return the next serial number correctly.
Even if you have a line with today's date it returns the last record of the table because the SetCurrentKey("Series Code", "Starting Date") is missing with NoSeriesLine.

### Expected behavior

If I have a record in the table "No. Series Line" with start date = '01/01/2023' and another line with start date = '01/01/2024' it should return as next number one of the line '01/01/2024'.
![image](https://github.com/microsoft/ALAppExtensions/assets/124427841/14e658e2-f34c-49b8-955f-e26579abf77f)

### Steps to reproduce

With the following configuration the calculation of the next number returns FC16-12153 instead of FC24-01135.
![image](https://github.com/microsoft/ALAppExtensions/assets/124427841/1835994e-8e53-4a3e-8218-f35e6cb08171)

### Additional context

The problem is that with the variable NoSeriesLine2 it uses the SetCurrentKey("Series Code", "Starting Date"); but when copying the filters to the variable NoSeriesLine, it does not apply the SetCurrentKey("Series Code", "Starting Date");

And then does a NoSeriesLine.findlast so it keeps the line with the highest value in the NoSeriesLine field and not the one with the correct date.
![image](https://github.com/microsoft/ALAppExtensions/assets/124427841/99b146b1-6950-418d-a539-6b48de3f6932)

After the copyfilters there should be the following code:

NoSeriesLine.SetCurrentKey("Series Code", "Starting Date");
### I will provide a fix for a bug

- [X] I will provide a fix for a bug
Internal work item: [AB#538577](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538577)

**Comment by JesperSchulz** [comment]
Given we've changed the implementation of "No. Series" in the 24 release, we'll have to investigate this one. We'll look into it!

Closing GitHub issue, as this issue isn't related to extensibility or a PR towards 1st party apps.

**Comment by grobyns** [comment]
FYI, the issue was fixed here https://github.com/microsoft/BCApps/pull/1315
and backported to all 24.x branches.
