### ISSUE TITLE
[Event Request] table 39 "Purchase Line" OnAfterUpdateDimensionsFromJobTask

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#26644]
### Describe the request

Can you add a event at the end of procedure UpdateDimensionsFromJobTask with Rec as reference.

### Additional context

To be able to update additional custom shortcut dimension fields
Internal work item: [AB#538387](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538387)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20959.
