### ISSUE TITLE
[Event Request] table 37 "Sales Line" - procedure CalcVATAmountLines()

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#26647]
### Describe the request

    if FindSet() then
      repeat
          if not ZeroAmountLine(QtyType) then begin
              **//--> event request
              OnCalcVATAmountLinesOnBeforeProcessSalesLine(SalesLine);
              //<-- event request**
              if (Type = Type::"G/L Account") and not "Prepayment Line" and "System-Created Entry" and not RoundingLineInserted then
                  RoundingLineInserted := ("No." = GetCPGInvRoundAcc(SalesHeader));
              if "VAT Calculation Type" in
                 ["VAT Calculation Type"::"Reverse Charge VAT", "VAT Calculation Type"::"Sales Tax"]
              then
                  "VAT %" := 0;
              if not VATAmountLine.Get(
                   "VAT Identifier", "VAT Calculation Type", "Tax Group Code", false, "Line Amount" >= 0)
              then begin
                  VATAmountLine.InsertNewLine(
                    "VAT Identifier", "VAT Calculation Type", "Tax Group Code", false, "VAT %", "Line Amount" >= 0, false, 0);
                  **//--> event request
                  OnCalcVATAmountLinesAfterVATAmountLineInsertNewLine(SalesLine, VATAmountLine);
                  //<-- event request**
              end;
      
              OnCalcVATAmountLinesOnBeforeQtyTypeCase(VATAmountLine, SalesLine, SalesHeader);
              
              .................................................................................................
                  
      until Next() = 0;

      **[IntegrationEvent(false, false)]
      local procedure OnCalcVATAmountLinesOnBeforeProcessSalesLine(var SalesLine: Record "Sales Line")
      begin
      end;**
      **[IntegrationEvent(false, false)]
      local procedure OnCalcVATAmountLinesAfterVATAmountLineInsertNewLine(var SalesLine: Record "Sales Line"; var VATAmountLine: Record "VAT Amount Line")
      begin
      end;**

### Additional context

    In Turkish localization, it is necessary to make a calculation. Like Purchase Line.
    
    if FindSet() then
      repeat
          if not ZeroAmountLine(QtyType) then begin
              **OnCalcVATAmountLinesOnBeforeProcessPurchLine(PurchLine, PurchHeader, VATAmountLine, QtyType);**
              if (Type = Type::"G/L Account") and not "Prepayment Line" then
                  RoundingLineInserted := (("No." = GetVPGInvRoundAcc(PurchHeader)) and "System-Created Entry") or RoundingLineInserted;
              if "VAT Calculation Type" in
                 ["VAT Calculation Type"::"Reverse Charge VAT", "VAT Calculation Type"::"Sales Tax"]
              then
                  "VAT %" := 0;
              if not VATAmountLine.Get(
                   "VAT Identifier", "VAT Calculation Type", "Tax Group Code", "Use Tax", "Line Amount" >= 0)
              then begin
                  VATAmountLine.InsertNewLine(
                    "VAT Identifier", "VAT Calculation Type", "Tax Group Code", "Use Tax", "VAT %", "Line Amount" >= 0, false, "Non-Deductible VAT %");
                  **OnCalcVATAmountLinesAfterVATAmountLineInsertNewLine(PurchLine, VATAmountLine);**
              end;
    
              .....................................................................................................................
    
      until Next() = 0;
Internal work item: [AB#538389](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538389)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20959.
