### ISSUE TITLE
[Event Request] codeunit 99000813 "Carry Out Action"

### ISSUE THREAD

**Issue by innonav-dev** [microsoft/ALAppExtensions#26657]
### Describe the request

We could use a new publisher in codeunit 99000813 "Carry Out Action" in OnRun trigger. Our suggestion is following:

```
trigger OnRun()
    var
        IsHandled: Boolean;
    begin
        OnBeforeRun(Rec);
    [...]

    [IntegrationEvent(false, true)]
    local procedure OnBeforeRun(var Rec: Record "Requisition Line")
    begin
    end;
```

### Additional context

We need to precheck Requisition Line in that case.
Internal work item: [AB#538404](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538404)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20959.
