### ISSUE TITLE
[Change Request] page 5530 "Item Availability by Event" - Add Parameter OnBeforeOnOpenPage

### ISSUE THREAD

**Issue by innonav-dev** [microsoft/ALAppExtensions#26653]
### Describe the request

In page 5530 "Item Availability by Event"  - on existing publisher OnBeforeOnOpenPage we could use another parameter for var Item and LocationFilter.

Existing code is:

```
    local procedure OnBeforeOnOpenPage(var IncludeBlanketOrders: Boolean; var PeriodType: Option)
    begin
    end;
```

Our suggestion:

```
    local procedure OnBeforeOnOpenPage(var IncludeBlanketOrders: Boolean; var PeriodType: Option; var Item: Record Item; var LocationFilter: Text)
    begin
    end;
```

### Additional context

We could use this, to fit our customers needs more precisely.
Internal work item: [AB#538398](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538398)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20959.
