### ISSUE TITLE
[Event Request] table 37 "Sales Line" - procedure UpdateVATOnLines()

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#26659]
### Describe the request

    if QtyType = QtyType::General then begin
      if not "Prepayment Line" then
          UpdatePrepmtAmounts();
      UpdateBaseAmounts(NewAmount, Round(NewAmountIncludingVAT, Currency."Amount Rounding Precision"), NewVATBaseAmount);
      **//--> event request
      OnUpdateVATOnLinesOnAfterUpdateBaseAmounts(SalesHeader, SalesLine, TempVATAmountLineRemainder, VATAmountLine, Currency);
      //<-- event request**
    end;

     **//--> event request
    [IntegrationEvent(false, false)]
    local procedure OnUpdateVATOnLinesOnAfterUpdateBaseAmounts(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; var TempVATAmountLineRemainder: Record "VAT Amount Line" temporary; var VATAmountLine: Record "VAT Amount Line"; Currency: Record Currency)
    begin
    end;
    //<-- event request**

### Additional context

    In Turkish localization, it is necessary to make a calculation. Like Purchase Line.
    
    if QtyType = QtyType::General then begin
      if not "Prepayment Line" then
          UpdatePrepmtAmounts();
      UpdateBaseAmounts(NewAmount, Round(NewAmountIncludingVAT, Currency."Amount Rounding Precision"), NewVATBaseAmount);
      NonDeductibleVAT.SetNonDedVATAmountInPurchLine(PurchLine, NonDedVATAmount);
      OnUpdateVATOnLinesOnAfterUpdateBaseAmounts(PurchHeader, PurchLine, TempVATAmountLineRemainder, VATAmountLine, Currency);
    end;
Internal work item: [AB#538406](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538406)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20959.
