### ISSUE TITLE
[Change Request] table 5870 "BOM Buffer" - Add parameter to existing publisher

### ISSUE THREAD

**Issue by innonav-dev** [microsoft/ALAppExtensions#26655]
### Describe the request

In publisher OnBeforeIsLowLevelOk and OnBeforeIsBOMOk we could use additional parameter.

Existing code is:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsBOMOk(var BOMBuffer: Record "BOM Buffer"; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsLowLevelOk(var BOMBuffer: Record "BOM Buffer"; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;
```

Our suggestion:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsBOMOk(var BOMBuffer: Record "BOM Buffer"; var Result: Boolean; var IsHandled: Boolean; var LogWarning: Boolean; var BOMWarningLog: Record "BOM Warning Log")
    begin
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeIsLowLevelOk(var BOMBuffer: Record "BOM Buffer"; var Result: Boolean; var IsHandled: Boolean; var LogWarning: Boolean; var BOMWarningLog: Record "BOM Warning Log")
    begin
    end;
```

### Additional context

We could really use this, to make additional checks and fit our customers needs.
Internal work item: [AB#538397](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538397)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20959.
