### ISSUE TITLE
[Event Request] codeunit 22 "Item Jnl.-Post Line" OnCheckItemTrackingOnAfterCheckRequiredTrackingNos

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#26662]
### Describe the request

Can you add IsHandled to OnCheckItemTrackingOnAfterCheckRequiredTrackingNos in procedure CheckItemTracking to be able to override check
```
// >>>>>>>>>>>>
if not IsHandled then
// <<<<<<<<<<<<
        if ItemJnlLine."Entry Type" = ItemJnlLine."Entry Type"::Transfer then
            ItemJnlLine.CheckNewTrackingIfRequired(GlobalItemTrackingSetup);
```

### Additional context

We have created custom code so we dont need the check.
Internal work item: [AB#538409](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538409)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 20959.
