### ISSUE TITLE
 [Variable Access Request] Page 253 - Sales Journal - variable CurrentJnlBatchName

### ISSUE THREAD

**Issue by KacMac** [microsoft/ALAppExtensions#26661]
### Describe the request

Hi AL-Team,
due to customer customization on the Sales Journal page (253) we need an access to a global variable CurrentJnlBatchName. Please can you make it a protected var so we can access it in a pageextension, similar to the General Journal page (39) where same variable is accessible

### Additional context

We are going to overwrite standard OnLookup procedure for CurrentJnlBatchName field in order to achieve additional filtering, and that's why we need access to that variable
Internal work item: [AB#538408](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538408)

**Comment by tomasevicst** [comment]
Hi,

This is already done for this github request https://github.com/microsoft/ALAppExtensions/issues/25901
and it is available from BC24.1
