### ISSUE TITLE
[Change Request] codeunit 6501 "Item Tracking Data Collection" - Add Parameter

### ISSUE THREAD

**Issue by innonav-dev** [microsoft/ALAppExtensions#26664]
### Describe the request

In codeunit 6501 "Item Tracking Data Collection" we could use some new paramter.

In procedure CreateEntrySummary2 on publisher OnBeforeUpdateBinContent existing code is:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateBinContent(var TempEntrySummary: Record "Entry Summary" temporary; var TempReservationEntry: Record "Reservation Entry" temporary)
    begin
    end;
```

Our suggestion:

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeUpdateBinContent(var TempEntrySummary: Record "Entry Summary" temporary; var TempReservationEntry: Record "Reservation Entry" temporary; var CurrBinCode: Code[20]; var CurrItemTrackingCode: Record "Item Tracking Code")
    begin
    end;
```

### Additional context

We use it to make tracking summary per bin code on all tracking specification.
Internal work item: [AB#538560](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538560)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21022.
