### ISSUE TITLE
[Change Request] page 5522 "Order Planning"

### ISSUE THREAD

**Issue by innonav-dev** [microsoft/ALAppExtensions#26663]
### Describe the request

Is there a possibility to switch following variables to protected var?

```
    protected var
        ProdOrder: Record "Production Order";
        MfgUserTempl: Record "Manufacturing User Template";
        OrderPlanningMgt: Codeunit "Order Planning Mgt.";
        DemandOrderFilter: Option "All Demands","Production Demand","Sales Demand","Service Demand","Job Demand","Assembly Demand";
        [InDataSet]
        DemandOrderFilterCtrlEnable: Boolean;
```

### Additional context

We need to access these, to implement our customer specific handling.
Internal work item: [AB#538557](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538557)

**Comment by tomasevicst** [comment]
Hi,

ProdOrder variable is under a CLEAN25 tag, and it is used in procedure that is obsolete. Is there any other variable that we can move to pretected instead of ProdOrder? Maybe DemandOrderNo?

```
#if not CLEAN25
        SalesHeader: Record Microsoft.Sales.Document."Sales Header";
        ProdOrder: Record Microsoft.Manufacturing.Document."Production Order";
```

```
#if not CLEAN25
    [Obsolete('This procedure replaced by procedure SetProdOrderDemand()', '25.0')]
    procedure SetProdOrder(ProdOrder2: Record Microsoft.Manufacturing.Document."Production Order")
    begin
        ProdOrder := ProdOrder2;
        DemandOrderFilter := DemandOrderFilter::"Production Demand";
        DemandOrderFilterCtrlEnable := false;
    end;
#endif

    procedure SetProdOrderDemand(NewDemandSubtype: Integer; NewDemandOrderNo: Code[20])
    begin
        DemandSubtype := NewDemandSubtype;
        DemandOrderNo := NewDemandOrderNo;
        DemandOrderFilter := DemandOrderFilter::"Production Demand";
        DemandOrderFilterCtrlEnable := false;
    end;
```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22119.
