### ISSUE TITLE
[Change Request] page 6510 "Item Tracking Lines" - procedure GetItem

### ISSUE THREAD

**Issue by innonav-dev** [microsoft/ALAppExtensions#26667]
### Describe the request

On page 6510 "Item Tracking Lines" in procedure GetItem, we suggest following:

Switching from local to protected procedure:

```
    local procedure GetItem(ItemNo: Code[20])
    begin
        if Item."No." <> ItemNo then begin
            Item.Get(ItemNo);
            Item.TestField("Item Tracking Code");
            if ItemTrackingCode.Code <> Item."Item Tracking Code" then
                ItemTrackingCode.Get(Item."Item Tracking Code");
        end;
    end;
```

### Additional context

On this page we try to cover some customer specific needs in handling tracking specification.
Internal work item: [AB#538562](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538562)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22119.
