### ISSUE TITLE
[Bug]: URL maximum length in E-Document Integration

### ISSUE THREAD

**Issue by pluethi** [microsoft/ALAppExtensions#26672]
### Describe the issue

When implementing the interface Microsoft.eServices.EDocument."E-Document Integration" to Send E-Documents we came across the issue that request URIs which are longer than 250 characters lead to an error in procedure InsertIntegrationLog of Codeunit 6132 "E-Document Log" due to the validation of the URL record field 7 of table 6127 "E-Document Integration Log" which is limited to 250 characters.

### Expected behavior

The supported maximum length of the URL should be longer.

### Steps to reproduce

1. Create a Codeunit which implements "E-Document Integration"
2. Implement procedure "Send" using a request URI with more than 250 characters in parameter HttpRequest
3. Error will be raised by the field validation in the subsequent call to the procedure InsertLog in codeunit 6132 "E-Document Log" due to the length of the RequestUri which is longer than 250 characters.

![image](https://github.com/microsoft/ALAppExtensions/assets/5007085/b6b29336-cd6a-408d-8c79-7a8d7c9218cf)

### Additional context

The .NET System.Uri class limits the maximum length of a URI for the System.Net.Http.HttpClient to [65519 characters](https://learn.microsoft.com/en-us/dotnet/api/system.uri.-ctor?view=net-8.0#system-uri-ctor(system-string)). Per [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110#section-4.1-5) (published in June 2022) there is no fixed limit for URIs, but it is recommended to support, "at a minimum, URIs with lengths of 8000 octets in protocol elements". Given the Business Central context, we would argue for URIs limited to not more than 2048 characters as an expected limit.

As a workaround we currently update the request URI of the HttpRequest parameter before exiting the procedure as follows:

![image](https://github.com/microsoft/ALAppExtensions/assets/5007085/aef99d48-0acd-488c-9811-033f67f8b281)

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Sounds fair to present a clear error message in this case. Approved.

**Comment by JesperSchulz** [comment]
Please allow me to discuss internally! I will get back to you soon!

**Comment by JesperSchulz** [comment]
We agree that a 250 char limit on URLs is sub-optimal and we would be open for improvements here 😊 As you know, the maximum length of a Text field in the database is 2048 characters. Would that suffice? Or are you looking for even longer strings?

**Comment by pluethi** [comment]
As written in the original post (Additional context), our team believes that a limit of 2048 characters is an expected limit in the context of Business Central and, at best, no one will notice this limit in the future.

**Comment by JesperSchulz** [comment]
OK, needed to make sure I got that right. So if the plan is to increase the URL field from 250 to 2048, I approve! You can go ahead and make the change.
The solution you describe would be the right one! Given this is a log table, I could be tempted to ask for a breaking change exception, but it wouldn't be the "right" solution... the table is public and we hence must deprecate the old field, create a new one, copy the data, keep them in sync... Again given it's a log, you could consider if it's OK to truncate the URL and put it into the old field for backwards compatibility. By the book, the logs wouldn't support longer URLs until the old field is deprecated "removed" in 3 releases from now - but usually people cannot wait that long 😉
Anyway, looking forward to what you come up with!
