### ISSUE TITLE
[Event Change Request] codeunit 826 "Purch. Post Invoice Events" - procedure RunOnPrepareLineOnAfterUpdateInvoicePostingBuffer()

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#26678]
### Describe the request

    **//--> event parameter cahange request for "var" InvoicePostingBuffer
    procedure RunOnPrepareLineOnAfterUpdateInvoicePostingBuffer(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; **var InvoicePostingBuffer: Record "Invoice Posting Buffer"**; var TempInvoicePostingBuffer: Record "Invoice Posting Buffer" temporary)
    begin
        OnPrepareLineOnAfterUpdateInvoicePostingBuffer(PurchHeader, PurchLine, InvoicePostingBuffer, TempInvoicePostingBuffer);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnPrepareLineOnAfterUpdateInvoicePostingBuffer(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; **var InvoicePostingBuffer: Record "Invoice Posting Buffer"**; var TempInvoicePostingBuffer: Record "Invoice Posting Buffer" temporary)
    begin
    end;
    **//<-- event parameter cahange request for "var" InvoicePostingBuffer

### Additional context

    In Turkish localization, it is necessary to make some VAT calculation.
Internal work item: [AB#538572](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538572)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21022.
