### ISSUE TITLE
[Event Change Request] codeunit 825 "Sales Post Invoice Events" - procedure RunOnPrepareLineOnAfterUpdateInvoicePostingBuffer()

### ISSUE THREAD

**Issue by Hakan-6Gen** [microsoft/ALAppExtensions#26679]
### Describe the request
    **//--> event parameter cahange request for "var" InvoicePostingBuffer
    procedure RunOnPrepareLineOnAfterUpdateInvoicePostingBuffer(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; **var InvoicePostingBuffer: Record "Invoice Posting Buffer"**; var TempInvoicePostingBuffer: Record "Invoice Posting Buffer" temporary)
    begin
        OnPrepareLineOnAfterUpdateInvoicePostingBuffer(SalesHeader, SalesLine, InvoicePostingBuffer, TempInvoicePostingBuffer);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnPrepareLineOnAfterUpdateInvoicePostingBuffer(SalesHeader: Record "Sales Header"; SalesLine: Record "Sales Line"; **var InvoicePostingBuffer: Record "Invoice Posting Buffer"**; var TempInvoicePostingBuffer: Record "Invoice Posting Buffer" temporary)
    begin
    end;
    **//<-- event parameter cahange request for "var" InvoicePostingBuffer
### Additional context

In Turkish localization, it is necessary to make some VAT calculation.
Internal work item: [AB#538571](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538571)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 25754.
