### ISSUE TITLE
[Event Request] Table 6650 "Return Shipment Header" - PrintRecords

### ISSUE THREAD

**Issue by ans-bar-bm** [microsoft/ALAppExtensions#26674]
### Describe the request

The `Return Shipment Header` table is missing a `OnBeforePrintRecords` event that is present in most other document tables. The `ReturnShptHeader` record and `IsHandled` event parameters should be referenced with `var`.
```
procedure PrintRecords(ShowRequestForm: Boolean)
    var
        ReportSelection: Record "Report Selections";
    begin
        ReturnShptHeader.Copy(Rec);

        // new code start
        OnBeforePrintRecords(ReturnShptHeader, ShowRequestForm, IsHandled);
        if IsHandled then
            exit;
        // new code end

        ReportSelection.PrintWithDialogForVend(
          ReportSelection.Usage::"P.Ret.Shpt.", ReturnShptHeader, ShowRequestForm, ReturnShptHeader.FieldNo("Buy-from Vendor No."));
    end;
```

### Additional context

Needed for consistent integration to all the `OnBeforePrintRecords` events across sales / service / purchase tables.
Internal work item: [AB#538565](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538565)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21022.
