### ISSUE TITLE
Report 302 "Get Demand To Reserve" - OnBeforeSetTempLine for all other dataitems / temp lines

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26688]
### Describe the request

In #26080 , below event has been added:

```
                IsHandled := false;
                OnSalesOrderLineOnAfterGetRecordOnBeforeSetTempSalesLine(SalesOrderLine, IsHandled);
                if not IsHandled then begin
                    TempSalesLine := SalesOrderLine;
                    TempSalesLine.Insert();
                end;
```

We would like to have the same IsHandled pattern applied to the other temp records in the report as well:

- TempTransferLine
- TempServiceLine
- TempJobPlanningLine
- TempAssemblyLine
- TempProdOrderComponent

### Additional context

We would not only like to conditionally skip sales lines, but other source lines as well.
Internal work item: [AB#538783](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538783)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21520.
