### ISSUE TITLE
[Enum Request] Table DACH Report Selections - Usage

### ISSUE THREAD

**Issue by dannoe** [microsoft/ALAppExtensions#26686]
### Describe the request

Why was #16270 closed as "Won't fix"?

### Additional context

We would appreciate if this becomes an enum extension of ``enum 77 "Report Selection Usage"``. Or is something else planned?
Internal work item: [AB#538854](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538854)

**Comment by JesperSchulz** [comment]
The internal work item had been closed as "Won't Fix", meaning no one would ever have picked up the issue. I'm currently synchronizing all GitHub issues according to their corresponding DevOps work items. Creating a new issue was the right thing to do, if the request still is valid.
@ventselartur, could you shed some light on why the previous request was closed as "Won't Fix"?

**Comment by ventselartur** [comment]
@dannoe , i apologize for not explaining the reason of closing your request, The reason is that this request been inactive for a long period of time. As Jesper mentioned, if the request is still valid, please reactivate.

**Comment by dannoe** [comment]
@ventselartur No Problem. Yes the request is still valid. Should I copy the text of the original issue to this issue or is the link enough?

**Comment by ventselartur** [comment]
@dannoe , the link is enough. Thank you for understanding!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21907.
