### ISSUE TITLE
report 300 "Carry Out Reservation" - Set DemandType

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26691]
### Describe the request

We would like to run the report 300 "Carry Out Reservation" via AL code, without showing the requestpage. Therefore we would like to set the value of the DemandType global variable.

Suggested function:

```
procedure SetDemandType(NewDemandType: Enum "Reservation Demand Type")
begin
    DemandType := NewDemandType;
end;
```

PS: To be verified if the SaveValues would not overrule the set value.

### Additional context

We would like to run the report 300 "Carry Out Reservation" via AL code, to automatically make the reservations / without user input, allowing to set the DemandType value
Internal work item: [AB#538787](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538787)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22874.
