### ISSUE TITLE
page 305 "Reservation Worksheet" - SetCurrentWkshBatchName

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26690]
### Describe the request

We would like to open the page 305 "Reservation Worksheet" for a specific Wksh. Batch Name. Therefore, a function should be added which allows to set the value of the global CurrentWkshBatchName variable.

Suggested function:

```
procedure SetCurrentWkshBatchName(NewCurrentWkshBatchName: Code[10])
begin
    CurrentWkshBatchName := NewCurrentWkshBatchName;
    ReservationWorksheetMgt.SetName(CurrentWkshBatchName, Rec);
end;
```

### Additional context

Aim is to be able to launch the page 305 "Reservation Worksheet" from AL code and preset the 'Batch Name' (and record filters)
Internal work item: [AB#538786](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538786)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27840.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 27926.
