### ISSUE TITLE
[Request for External] codeunit 5988 "Serv-Documents Mgt." - CheckCloseCondition

### ISSUE THREAD

**Issue by AlaAuz** [microsoft/ALAppExtensions#26696]
### Describe the request

Hello, Would it be possible to remove "local" infront of  the procedure "CheckCloseCondition" so that we are able to use this outside the codeunit ? 

### Additional context

Need this so we are able to use this procedure outside "serv-documents mgt." instead of needing to dupplicate the code.
Internal work item: [AB#538852](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538852)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21820.
