### ISSUE TITLE
report 302 "Get Demand To Reserve" - AutoAllocate

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26694]
### Describe the request

We would like to run the report 302 "Get Demand To Reserve" via AL code, without showing the requestpage. Therefore we would like to set the value of the AutoAllocate global variable.

Suggested function:

```
procedure SetAutoAllocate(NewAutoAllocate : boolean)
begin
    AutoAllocate  := NewAutoAllocate ;
end;
```

PS: To be verified if the SaveValues would not overrule the set value.
PS : Ideally, pls apply a similar pattern as other 'Get ... / Fetch ...' reports by providing a SetParameters function, allowing to set ALL parameters the request options page by code. (this would allow others e.g. to also set the DemandType value by code)

### Additional context

We would like to run the report 302 "Get Demand To Reserve" via AL code, to automatically get the demand to reserve / without user input, allowing to set the AutoAllocate  value
Internal work item: [AB#538791](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538791)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21453.
