### ISSUE TITLE
[Event Parameter Request] codeunit 5812 "Calculate Standard Cost" - OnAfterCalcRtngLineCost

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#26695]
### Describe the request

We have tried to request the changes described in the attachments in a couple of ways and not received what we requested and needed yet.
https://github.com/microsoft/ALAppExtensions/issues/25598
https://github.com/microsoft/ALAppExtensions/issues/25599
https://github.com/microsoft/ALAppExtensions/issues/26317

Could you please apply the mentioned changes in:
CalculateStandardCost-25.0.20421.0.Codeunit.al
and
CalculateBOMTree-25.0.20421.0.Codeunit.al

If the assigned developer somehow manages to not create the requested parameters and still signs this issue off, I would like to be informed beforehand. It is close to six months now and we have run out-of options with our customer. We postponed the BC14->BC24 dataupgrade partially because of the missing events. It will now take place in November with BC25.

    [IntegrationEvent(false, false)]
    local procedure OnAfterCalcRtngLineCost(RoutingLine: Record "Routing Line"; MfgItemQtyBase: Decimal; var SLCap: Decimal; var SLSub: Decimal; var SLCapOvhd: Decimal; var StdCostWkshName: Text[50]; var ParentItem: Record Item; CostTime: Decimal)
    begin
    end;

### Additional context

 var SLCap: Decimal; var SLSub: Decimal; var SLCapOvhd: Decimal are not extensible to create extra manafucaturing cost or want to split work and machine center cots. All those values are present in T27 Item.
[CalculateBOMTree-25.0.20421.0.Codeunit.al.txt](https://github.com/user-attachments/files/15887476/CalculateBOMTree-25.0.20421.0.Codeunit.al.txt)
[CalculateBOMTree-25.0.20421.0.Org.Codeunit.al.txt](https://github.com/user-attachments/files/15887477/CalculateBOMTree-25.0.20421.0.Org.Codeunit.al.txt)
[CalculateStandardCost-25.0.20421.0.Codeunit.al.txt](https://github.com/user-attachments/files/15887478/CalculateStandardCost-25.0.20421.0.Codeunit.al.txt)
[CalculateStandardCost-25.0.20421.0.Org.Codeunit.al.txt](https://github.com/user-attachments/files/15887479/CalculateStandardCost-25.0.20421.0.Org.Codeunit.al.txt)

Internal work item: [AB#538853](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538853)

**Comment by JakovljevicDusan** [comment]
Included in v25

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22240.
