### ISSUE TITLE
[Event Request] table 83 "Item Journal Line" - OnAfterSetReservEntrySourceFilters

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#26698]
### Describe the request

```
    internal procedure SetReservEntrySourceFilters(var ReservEntry: Record "Reservation Entry"; SourceKey: Boolean)
    begin
        if IsSourceSales() then
            ReservEntry.SetSourceFilter(Database::"Item Journal Line", "Entry Type".AsInteger(), "Document No.", "Document Line No.", SourceKey)
        else
            ReservEntry.SetSourceFilter(Database::"Item Journal Line", "Entry Type".AsInteger(), "Journal Template Name", "Line No.", SourceKey);
        ReservEntry.SetSourceFilter("Journal Batch Name", 0);
        OnAfterSetReservEntrySourceFilters(ReservEntry, SourceKey);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetReservEntrySourceFilters(var ReservEntry: Record "Reservation Entry"; SourceKey: Boolean);
    begin
    end;
```

### Additional context

The change is needed as the function SetReservEntrySourceFilters has been introduced in BC24. This function did not exist prior to BC 24 and the filtering was always on Journal Template Name and Line No. With introduction of the function in BC24 the solution stopped working as the error did appear as no Reservation Entries were found during posting of inventory entries involved in sales process. Therefore, we need a possibility to fallback to old behavior in certain scenarios when Serial No.s are posted in sales area.

```
ReservEntry.SetSourceFilter(Database::"Item Journal Line", "Entry Type".AsInteger(), "Journal Template Name", "Line No.", SourceKey);
```
Internal work item: [AB#538874](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/538874)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21140.
