### ISSUE TITLE
Missing events

### ISSUE THREAD

**Issue by superjma** [Microsoft/ALAppExtensions#267]
Hi

I am missing 2 events in NAV2018.

In Codeunit 7302 in function InitWhseJnlLine I need an OnAfterInitWhseJnlLine with the parameters ItemJnlLine and WhseJnlLine.

In Codeunit 7301 in function InitWhseEntry I need an OnAfterInitWhseEntry with the parameters WhseEntry and WhseJnlLine.

Regards

Jan Andersen

**Comment by AlexanderYakunin** [comment]
#1 - event OnInitWhseJnlLineCopyFromItemJnlLine(WhseJnlLine,ItemJnlLine) already exist
#2 - event OnInitWhseEntryCopyFromWhseJnlLine(WhseEntry,WhseJnlLine,OnMovement) already exist
