### ISSUE TITLE
[Event Request] Add parameter PreviewMode in event "OnAfterPostPurchaseDoc" in codeunit "Purch.-Post"

### ISSUE THREAD

**Issue by diogoviegas2855** [microsoft/ALAppExtensions#26705]
### Describe the request

Hi
Can you add the parameter PreviewMode in event "OnAfterPostPurchaseDoc" in codeunit "Purch.-Post" similar to what already happens in event "OnAfterPostSalesDoc" in codeunit "Sales-Post"

Actual Code:
```
[IntegrationEvent(false, false)]
 procedure OnAfterPostPurchaseDoc(var PurchaseHeader: Record "Purchase Header"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; PurchRcpHdrNo: Code[20]; RetShptHdrNo: Code[20]; PurchInvHdrNo: Code[20]; PurchCrMemoHdrNo: Code[20]; CommitIsSupressed: Boolean)
begin
end;
```
Suggestion Code:
```
[IntegrationEvent(false, false)]
 procedure OnAfterPostPurchaseDoc(var PurchaseHeader: Record "Purchase Header"; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; PurchRcpHdrNo: Code[20]; RetShptHdrNo: Code[20]; PurchInvHdrNo: Code[20]; PurchCrMemoHdrNo: Code[20]; CommitIsSupressed: Boolean; PreviewMode: Boolean)
begin
end;
```

### Additional context

Need this parameter in order to control if it is a preview or posting after the posting is done
Internal work item: [AB#539217](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539217)

**Comment by AleksandricMarko** [comment]
Hello @diogoviegas2855 
Event OnAfterPostPurchaseDoc is created as a global and it is not possible to add new parameters in it (as it would be breaking change). Please consider other solutions and in case you need new event, create new requests.
