### ISSUE TITLE
[Event Request] Codeunit 5900 ServOrderManagement - CopyComponentsFromBOM

### ISSUE THREAD

**Issue by ISliceUrPanties** [microsoft/ALAppExtensions#26704]
### Describe the request

Hello, could you please add an event in function CopyComponentsFromBOM with the handled-pattern.

```
local procedure CopyComponentsFromBOM(var NewServItem: Record "Service Item")
var
    // New +
    IsHandled: Boolean;
    // New -
begin
    // New +
    IsHandled := false;
    OnBeforeCopyComponentsFromBOM(NewServItem, IsHandled);
    if IsHandled then
        exit;
    // New -
    CODEUNIT.Run(CODEUNIT::"ServComponent-Copy from BOM", NewServItem);
end;
```

Event definition
```
[IntegrationEvent(false, false)]
local procedure OnBeforeCopyComponentsFromBOM(var ServiceItem: Record "Service Item"; var IsHandled: Boolean)
begin
end;
```

Thanks in advance

### Additional context

We want to be able to use our own logic to copy service item components from BOM.
Internal work item: [AB#539218](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539218)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21509.
