### ISSUE TITLE
[Event Request] Add the event OnAfterCreateCorrPurchaseInvoice in codeunit "Correct Posted Purch. Invoice" similar to the already existing one for sales in codeunit "Correct Posted Sales Invoice"

### ISSUE THREAD

**Issue by diogoviegas2855** [microsoft/ALAppExtensions#26702]
### Describe the request

Hi
Can you please add the event OnAfterCreateCorrPurchaseInvoice in codeunit "Correct Posted Purch. Invoice" similar to the already existing one for sales in codeunit "Correct Posted Sales Invoice"

Actual Code:

```
procedure CancelPostedInvoiceStartNewInvoice(var PurchInvHeader: Record "Purch. Inv. Header"; var PurchaseHeader: Record "Purchase Header")
begin
    CancellingOnly := false;

    if CreateCreditMemo(PurchInvHeader) then begin
        CreateCopyDocument(PurchInvHeader, PurchaseHeader, PurchaseHeader."Document Type"::Invoice, true);
        Commit();
    end;
end;
```
Suggestion Code:
```
procedure CancelPostedInvoiceStartNewInvoice(var PurchInvHeader: Record "Purch. Inv. Header"; var PurchaseHeader: Record "Purchase Header")
begin
    CancellingOnly := false;

    if CreateCreditMemo(PurchInvHeader) then begin
        CreateCopyDocument(PurchInvHeader, PurchaseHeader, PurchaseHeader."Document Type"::Invoice, true);
        OnAfterCreateCorrPurchaseInvoice(PurchaseHeader, PurchInvHeader);
        Commit();
    end;
end;

[IntegrationEvent(false, false)]
    local procedure OnAfterCreateCorrPurchaseInvoice(var PurchaseHeader: Record "Purchase Header"; var PurchInvHeader: Record "Purch. Inv. Header")
begin
end;

```

### Additional context

Need this event to control what happens after the creation of the corrective purchase invoice
Internal work item: [AB#539216](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539216)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21509.
