### ISSUE TITLE
Company Hub - additional fields/data

### ISSUE THREAD

**Issue by henrikohmatev** [microsoft/ALAppExtensions#26700]
### Describe the request

Hi,
Missing the ability to add extra fields/data due to the lack of extensibility in the parse-code and InvokeAPI code.

### Additional context

So much more interesting data to fetch cross environment and present to a user group.
Internal work item: [AB#546693](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/546693)

**Comment by JesperSchulz** [comment]
We would need you to be a bit more specific as to what you are missing in order for us to take action on this issue. Could you tell us which changes you would want us to make in the AL code?

**Comment by henrikohmatev** [comment]
Hi Jesper,
Current transfers of data via Company Hub seems to be: Tasks, Activities and Finance. 
As a company is much more than this i.e. planning and production data, global warehousing, IT areas (job queue...) and more it seems that the product could be extendible for such data?
Best,
Henrik

**Comment by AndersLarsenMicrosoft** [comment]
We would need you to be a way more specific. This seems like a good candidate for contribution

**Comment by henrikohmatev** [comment]
Hi Anders,

Company Hub functionality.

**Current solution:**
* Transfers financial + sales + purchase data selected (fields/cues) by Microsoft.
* Not extendable with more fields/cues/etc. - not possible to have overview of production data, warehouse data, job queues etc. in the hub per user personlization.

**Future solution:**
* Transfers financial + sales + purchase data selected (fields/cues) by Microsoft - should be extendable for new customer specific fields etc.
* Transfers other data from production, warehouse, job queues, service module, fashion extension, .... any module, any extension

Best,
Henrik

**Comment by AndersLarsenMicrosoft** [comment]
Hi Henrik 

Yes, we do know that for now Company Hub supports financial, sales, and   purchase data.
As you ask still is a bit week. (Make this feature extensible for “all”) we won’t start this work now. I suggest that you submit an idea or consider code contribution.

Thanks 
Aners

**Comment by henrikohmatev** [comment]
Hi @AndersLarsenMicrosoft 

https://experience.dynamics.com/ideas/idea/?ideaid=8ab7e427-a5a5-ef11-95f5-000d3a04161c

Thank you for the reply. It's up to you really, but our customers cannot use only the standard functionality and if an area is not customizable then usually we don't recommend it. For the "hub" functionality we will continue to recommend PowerBI and other solutions to support reporting purposes instead of Company Hub. Company Hub does not support dimensions/locations-filtering, bespoke fields, 3rd party fields and more, and will therefore not really be usable for our customers in general. 

Best,
Henrik
