### ISSUE TITLE
[Bug]: Page SourceTableTemporary property not being respected when called from an OnDrillDown trigger

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#26710]
### Describe the issue

When calling a page runmodally (or not; I haven't checked that) from an OnDrillDown trigger the SourceTableTemporary property of that page is not being used.
It might also have something to do with the fact (see in attached example AL workspace) that it is being called from a cuegroup.

### Expected behavior

However a page is called it should respect the SourceTableTemporary setting.

### Steps to reproduce

Attached is an AL workspace which has a page "Item Reclassification Card PTE" with source table T83 "Item Journal Line" set as SourceTableTemporary=true.
It is setup in the launch as startupObjectId and then an error is not being presented in
TempItemJournalLine.Copy(Rec, true); when publish the app from VSC.

But when you call it from the rolcenter page 71001 "Warehouse Scanning PTE" (Please set that page up in Roles (Profiles) and use as default or your Settings) clicking on Activity 'Item Reclassification' it does present you with an error.

The use of
DrillDown = true;
trigger OnDrillDown()

are the only triggers that can be used.

Lookup = true;
trigger OnLookup(var Text: Text): Boolean

or

AssistEdit = true;
trigger OnAssistEdit()

also do not work in cue activities.
[SourceTableTemporaryIssue.zip](https://github.com/user-attachments/files/15911167/SourceTableTemporaryIssue.zip)

### Additional context

We are in the process of creating a barcode scanning solution with the mobile app and using cues and activities is the only way to present a warehouse user with finger clickable features.

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Sorry about the late reply on this one @Duizy1971. What fix exactly are you proposing to make here? This does more sound like a bug report for the product group, or am I mistaken?

**Comment by Duizy1971** [comment]
I'm sorry Jesper,

I don't know in which way I should issue these kind of framework bugs to Microsoft. If you say it should be a bug report for the product group, then I probably agree. I'm not supplying any kind of fix.

**Comment by JesperSchulz** [comment]
In that case the bug report should go through our support channel 😊 I hope the following link gets you started: https://aka.ms/bcsupport.

**Comment by Duizy1971** [comment]
What a terrible suggestion. The links on https://aka.ms/bcsupport resorts to more links and ten of them link to support for issues not releated to BC. I am so confused by the way all the different kind of support is being handled. Can you please give me the direct link to the actual place were I can post this issue? I do have ServiceHub support but they do not want to help me with this type of case. BCIdeas is not the place . ALAppExtensions is, I guess, not the place. So were can I go then?

**Comment by JesperSchulz** [comment]
Sorry that the link did not help. I thought the section ["Summary of where to file bugs and issues"](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/help-and-support#bugs) would point you in the right direction.

As I am from the product group, I can only refer to that page, hoping it is informative enough for partners to take further action. I cannot myself initiate a support case for you.

This repository is only for Business Central extensibility requests or code contributions towards the [1st party Business Central apps](https://github.com/microsoft/ALAppExtensions/tree/main/Apps). This is also why we clearly show the following template when you create a new issue:

⚠️⚠️ BEFORE WE GET STARTED ⚠️⚠️
This is not the right place to report product defects with customer impact to Microsoft! Issues reported in this repository do not fall under SLAs (Service Level Agreements) and hence have no guaranteed time to mitigation. If your customers are experiencing product defects or you have discovered a severe issue in the product, please follow the steps outlined in https://learn.microsoft.com/dynamics365/business-central/dev-itpro/technical-support to get your issue routed to the right team at Microsoft and to get it treated with the right priority.

We can try to forward this bug to the AL repository, given your request is somewhat related to compilation, and given that support seemingly does not want to assist with this issue.
