### ISSUE TITLE
Add CurrPage as parameter in OnAfterInitializeFromNotification(Rec, AvailabilityCheckNotification) present in page 1872 "Item Availability Check"

### ISSUE THREAD

**Issue by krishnaGottuparthi** [microsoft/ALAppExtensions#26717]
### Describe the request

Need CurrPage as parameter in IntegrationEvent **OnAfterInitializeFromNotification(Rec, AvailabilityCheckNotification)** present in **page 1872 "Item Availability Check"**

**Before** 
[IntegrationEvent(false, false)]
    local procedure OnAfterInitializeFromNotification(var Item: Record Item; var AvailabilityCheckNotification: Notification)
    begin
    end;

**After**
[IntegrationEvent(false, false)]
    local procedure OnAfterInitializeFromNotification(var Item: Record Item; var AvailabilityCheckNotification: Notification;var CurrPage: Page "Item Availability Check")
    begin
    end;

### Additional context

Cannot access subpage **AvailabilityCheckDetails** as the integrationevent OnAfterInitializeFromNotification doesnt have parameter **Currpage: page "Item Availability Check"**
Internal work item: [AB#539239](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539239)

**Comment by AleksandricMarko** [comment]
Hello @krishnaGottuparthi 
It is not possible to pass CurrPage as a parameter.
Please try to find a different way how to accomplish needed and in case some new events needed, create new requests.
