### ISSUE TITLE
Remove OnPrem Scope for procedure InitializeFromNotification(AvailabilityCheckNotification: Notification) in Page 1872 "Item Availability Check"

### ISSUE THREAD

**Issue by krishnaGottuparthi** [microsoft/ALAppExtensions#26716]
### Describe the request

Remove **OnPrem** Scope for procedure **InitializeFromNotification(AvailabilityCheckNotification: Notification)** in Page 1872 "Item Availability Check"

### Additional context

Please remove OnPrem scope of to customize Item Availability Check page. 
Internal work item: [AB#539240](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539240)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21453.
