### ISSUE TITLE
[Event Request] Codeunit 7044 "Price Asset - Resource Group" - OnAfterFillAdditionalFields

### ISSUE THREAD

**Issue by ZepposBE** [microsoft/ALAppExtensions#26724]
### Describe the request

Hello development team,

For some of our features we would like to see the new event added as in the example code below.

```
local procedure FillAdditionalFields(var PriceAsset: Record "Price Asset")
    begin
        PriceAsset.Description := ResourceGroup.Name;
        PriceAsset."Unit of Measure Code" := '';
        PriceAsset."Variant Code" := '';
        PriceAsset."Work Type Code" := '';

        >>> New Event
        OnAfterFillAdditionalFields(PriceAsset, ResourceGroup);
        <<< New Event
    end;

```

 ```
   [IntegrationEvent(false, false)]
    local procedure OnAfterFillAdditionalFields(var PriceAsset: Record "Price Asset" temporary; ResourceGroup: Record "Resource Group")
    begin
    end;
```

There is only one caveat to this code example, the name of the variable in the OnAfterFillAdditionalFields event will have to be different because it's the same as the global variable, but I will leave this naming up to you according to your conventions.

### Additional context

For some of our features we need to populate extra data from the Item Disc. Group into the Price Asset record.
Business Central already already has these similar events for Item and Resource, but not for these other "Price Asset Types":

- [Item Discount Group](https://github.com/microsoft/ALAppExtensions/issues/26723) 
- [Resource Group ](https://github.com/microsoft/ALAppExtensions/issues/26724)(this request)
- [Service Cost](https://github.com/microsoft/ALAppExtensions/issues/26726)
- [G/L Account ](https://github.com/microsoft/ALAppExtensions/issues/26727)
Internal work item: [AB#539235](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539235)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21487.
