### ISSUE TITLE
[Event Change Request] Codeunit 22 "Item Jnl.-Post Line" - Event OnAfterIsPostToGL

### ISSUE THREAD

**Issue by Medson99** [microsoft/ALAppExtensions#26720]
### Describe the request

I would like add PostToGL added to the following event.

Orginal:
```al
[IntegrationEvent(false, false)]
local procedure OnAfterIsPostToGL(ValueEntry: Record "Value Entry"; var Result: Boolean)
begin
end;
``` 

Change:
```al
[IntegrationEvent(false, false)]
local procedure OnAfterIsPostToGL(ValueEntry: Record "Value Entry"; PostToGL: Boolean; var Result: Boolean)
begin
end;
``` 

### Additional context

We need to add additional parameter to allow post to GL, but we need use standard PostToGL param, as in current check
Internal work item: [AB#539237](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539237)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21509.
