### ISSUE TITLE
[Event Request] codeunit 5139 "Job Archive Management" - OnRestoreSingleJobTaskOnBeforeInsertJobTask

### ISSUE THREAD

**Issue by pri-kise** [microsoft/ALAppExtensions#26722]
### Describe the request

Could you please add the following event?
```al
local procedure RestoreSingleJobTask(JobTaskArchive: Record "Job Task Archive"; Job: Record Job)
var
    JobTask: Record "Job Task";
    JobTaskDimension: Record "Job Task Dimension";
begin
    JobTaskDimension.SetRange("Job No.", Job."No.");
    JobTaskDimension.SetRange("Job Task No.", JobTaskArchive."Job Task No.");
    JobTaskDimension.DeleteAll();

    JobTask.Init();
    JobTask.TransferFields(JobTaskArchive);
    OnRestoreSingleJobTaskOnBeforeInsertJobTask(JobTaskArchive, JobTask);
    JobTask.Insert(true);
    RecordLinkManagement.CopyLinks(JobTaskArchive, JobTask);
    JobTask.Modify(true);
    OnAfterRestoreSingleJobTask(JobTaskArchive, JobTask);
end;
```

```al

[IntegrationEvent(false, false)]
local procedure OnRestoreSingleJobTaskOnBeforeInsertJobTask(JobTaskArchive: Record "Job Task Archive"; var JobTask: Record "Job Task")
begin
end;
```

### Additional context

We would like to change some custom fields after the TransferFields before the Insert(true) is executed.
Internal work item: [AB#539232](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539232)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21464.
