### ISSUE TITLE
[Bug]: Discrepancies in the BC System Table "Field" Between OnPrem and SaaS

### ISSUE THREAD

**Issue by KonnosPB** [microsoft/ALAppExtensions#26736]
We have observed that the BC system table "Field" can provide different data between OnPrem and SaaS environments. Specifically, the fields "RelationTableNo" and "RelationFieldNo" may contain varying data. This behavior can be reproduced in both every OnPrem [https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/onprem/24.2.20227.20424/de] and Sandbox [https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.2.20227.20579/de] environment.

Example:
- OnPrem: The fields "RelationTableNo" and "RelationFieldNo" .
<img width="960" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/38393288/848a150a-472d-440a-a6d2-c9aa998904cc">

- SaaS: The same fields return different values compared to OnPrem.
<img width="954" alt="image" src="https://github.com/microsoft/ALAppExtensions/assets/38393288/a6516d94-bac6-4e46-8aaf-d5977e8fce11">

Since we are fortunately able to rely on the "Table Relations Metadata" table, we do not have a specific problem at the moment. Please consider this issue as a friendly suggestion, giving you the opportunity to review this behavior and potentially improve the product.

### Expected behavior

The fields "RelationTableNo" and "RelationFieldNo" in the system table "Field" should provide the same data in both OnPrem and SaaS environments.

### Steps to reproduce

1. Open the "Field" table in an OnPrem environment and examine any fields with table relations, such as Table No. 18, Field 5792.
2. Repeat the process in a SaaS or Sandbox environment.
3. Compare the data in the fields "RelationTableNo" and "RelationFieldNo".

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug
Internal work item: [AB#539953](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539953)

**Comment by jehelles** [comment]
There is no difference in logic between SaaS and OnPrem. The difference is that a change was hotfixed to SaaS and not shipped on-prem yet. This change makes table relations show up in the field table even if there are filters as long as there are no conditions (IE. relation to one table only).

It will be in the next 24 CU.
