### ISSUE TITLE
Access to ConstructUri for Azure Blob Storage and Azure File Share management

### ISSUE THREAD

**Issue by DennyHW** [microsoft/ALAppExtensions#26739]
### Describe the request

The codeunit 9051 "ABS Client Impl." and codeunit 8951 "AFS File Client Impl."
calculates the URL of a resource dynamically, through functions called ConstructUri and stored in other objects.

These functions should also be accessible  from the outside because for calls like CopyBlob or CopyFile the source parameter must be a full URI and therefore we must externally recreate the same address calculation logic.
Furthermore  (at least for blob storage) it is also possible to set a SetBaseUrl().

![immagine](https://github.com/microsoft/ALAppExtensions/assets/53569676/69958a39-5e8c-4ad5-9c68-da26cacfa5dd)

### Additional context

Always use the same function should be better to standardize the code
Internal work item: [AB#539366](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539366)

**Comment by Groenbech96** [comment]
Please create issue and pull request on BCApps, as this code belongs there. I am not sure if they will accept the change as it. Maybe this could be moved to a new function, that allows you to create the url.
