### ISSUE TITLE
Codeunit 12 Gen. Jnl.-Post Line Set procedure PostUnrealVATEntry as public.

### ISSUE THREAD

**Issue by LubomirUrx** [microsoft/ALAppExtensions#26732]
### Describe the request

Please, set procedure PostUnrealVATEntry in codeunit 12 Gen. Jnl.-Post Line as public.

### Additional context

We need external access to the procedure.
Internal work item: [AB#539361](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539361)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 21676.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21691.
