### ISSUE TITLE
[Event Request] Page 700 Page Management - Procedure GetSalesHeaderPageID - OnBeforeGetSalesHeaderPageID

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26749]
### Describe the request

Please add the following Event/-s OnBeforeGetSalesHeaderPageID to procedure GetSalesHeaderPageID in Page 700 Page Management

```
[Event Request] Page 700 Page Management - Procedure GetSalesHeaderPageID
    local procedure GetSalesHeaderPageID(RecRef: RecordRef): Integer
    var
        SalesHeader: Record "Sales Header";
        IsHandled : Boolean:
    begin
        // NEW
        IsHandled := FALSE;
        OnBeforeGetSalesHeaderPageID(RecRef,IsHandled);
        IF IsHandled  THEN
          EXIT;
        // NEW
        
        RecRef.SetTable(SalesHeader);
        case SalesHeader."Document Type" of
            SalesHeader."Document Type"::Quote:
                exit(PAGE::"Sales Quote");
            SalesHeader."Document Type"::Order:
                exit(PAGE::"Sales Order");
            SalesHeader."Document Type"::Invoice:
                exit(PAGE::"Sales Invoice");
            SalesHeader."Document Type"::"Credit Memo":
                exit(PAGE::"Sales Credit Memo");
            SalesHeader."Document Type"::"Blanket Order":
                exit(PAGE::"Blanket Sales Order");
            SalesHeader."Document Type"::"Return Order":
                exit(PAGE::"Sales Return Order");
        end;
    end;

```

```
 [IntegrationEvent(false, false)]
 local procedure OnBeforeGetSalesHeaderPageID(RecRef: RecordRef,var IsHandled : Boolean)
    begin
    end;
```

### Additional context

Preparation for use of rebooking orders
Internal work item: [AB#539823](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539823)

**Comment by Groenbech96** [comment]
The design is to use 
OnBeforeGetConditionalCardPageID(RecRef, CardPageID, IsHandled);
in page management. 

Can you use that instead? Im not really up for adding this event, as we then also have to think about other scenarios. Like purchase and service.

Cant you create your own Booking Document?

**Comment by SKeiler** [comment]
We don't have a own booking document, we have in some cases a special Order Document with a own Page/List. 

The use of the OnBeforeGetConditionalCardPageID-Event would be an option, but would require that the GetSalesHeaderPageID will never get other call points and never will be global.

**Comment by Groenbech96** [comment]
Ok. 
We wont introduce this event. If you mark IsHandled true in OnBeforeGetConditionalCardPageID, then it will never get other call points.
