### ISSUE TITLE
[Event Request] codeunit 99000854 "Inventory Profile Offsetting" - OnAfterCommitTracking

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#26744]
### Describe the request

    local procedure CommitTracking()
    ....
            TempTrkgReservEntry.Delete();
        until TempTrkgReservEntry.Next() = 0;
        Clear(TempTrkgReservEntry);

        OnAfterCommitTracking(TempItemTrkgEntry);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterCommitTracking(var TempItemTrkgEntry: Record "Reservation Entry" temporary)
    begin
    end;

### Additional context

Using the MRP in requisition or planning worksheet creates havoc in the T337 reservation entry table when it concerns item tracking. Many times item tracking lines just get deleted when running a MRP. This is especially with Prod. Order Component related item tracking lines. We want to be able to use telemetry to find out which specific type of item tracking lines are not getting back into T337 and maybe find a problem area in codeunit 99000854.
Internal work item: [AB#539665](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539665)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21464.
