### ISSUE TITLE
[Request-For-External] TAB39 "Purchase Line" - procedure AddItems

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26754]
### Describe the request

Hello, we need the following currently local/internal procedure to be set to global, so we can call it from a subscriber. Can you please check this? Thank you!

```
procedure AddItems(SelectionFilter: Text)
```	

### Additional context

Call it from a custom Item Lookup.
Internal work item: [AB#539826](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539826)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21453.
