### ISSUE TITLE
[Event Request] Page 46 - Sales Order Subform -OnDeleteRecord

### ISSUE THREAD

**Issue by hhout** [microsoft/ALAppExtensions#2675]
Hi,

We would like to request an event for Page 46 Sales Order Subform, function OnDeleteRecord().

**Event:**
```
OnDeleteRecord() : Boolean
IF (Quantity <> 0) AND ItemExists("No.") THEN BEGIN
  COMMIT;
  IF NOT ReserveSalesLine.DeleteLineConfirm(Rec) THEN
    EXIT(FALSE);
  // START EVENT ++
  OnBeforeDeleteReservationEntries(Rec);
  // END EVENT --
  ReserveSalesLine.DeleteLine(Rec);
END;
DocumentTotals.SalesDocTotalsNotUpToDate;
```

**Publisher function:**
```
LOCAL [IntegrationEvent] OnBeforeDeleteReservationEntries (VAR SalesLine : Record "Sales Line")
```

Thanks in advance!

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.

**Comment by bc-ghost** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. We will update this issue with information about availability.
