### ISSUE TITLE
[Change Request] Report 121 "Customer - Balance to Date" - changing the protected level of variables

### ISSUE THREAD

**Issue by Halilovast** [microsoft/ALAppExtensions#26767]
### Describe the request

report 121 "Customer - Balance to Date"

**old:**
var
        TempCurrencyTotalBuffer: Record "Currency Total Buffer" temporary;
        TempCurrencyTotalBuffer2: Record "Currency Total Buffer" temporary;

**new:**
protected var
        TempCurrencyTotalBuffer: Record "Currency Total Buffer" temporary;
        TempCurrencyTotalBuffer2: Record "Currency Total Buffer" temporary;

### Additional context

To extend Report 121 we cannot access the Buffer tables. Please move to the protected var section.
Internal work item: [AB#539932](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539932)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21499.
