### ISSUE TITLE
[Bug]: Table "Location" -> "Bin Mandatory" OnValidate -> Dialog not closed.

### ISSUE THREAD

**Issue by Doriano-Ponzo-EOS** [microsoft/ALAppExtensions#26769]
### Describe the issue

The Dialog with label "'Checking item ledger entries for open entries...'" appears after "Bin Mandatory" validation on "Location" table, but never close.

Please fix this behaviour or please add the possibility to skip Dialog or close it with an integration event.

### Expected behavior

Dialog close after the check finish.

### Steps to reproduce

Validate field "Bin Mandatory" on "Location".

**Comment by JesperSchulz** [comment]
This is usually not the right place to report product defects, but given the simplicity of this bug, I'll just quickly fix it an move on 😊 Thanks for reporting.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21484.
