### ISSUE TITLE
[Event Request] 8623 "Dimensions Notifications" - OnBeforeConfirmPackageHasDimensionsWarning

### ISSUE THREAD

**Issue by Doriano-Ponzo-EOS** [microsoft/ALAppExtensions#26765]
### Describe the request

Add an event at the start of the procedure ConfirmPackageHasDimensionsWarning to avoid warning modal.

### Additional context

To run import of packages without warnings.
Internal work item: [AB#539837](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539837)

**Comment by Groenbech96** [comment]
This function is designed to show warnings. This wont be changed.
