### ISSUE TITLE
[Event Request] page 5404 "Item Units of Measure" - OnAfterSetStyle

### ISSUE THREAD

**Issue by auzhhv** [microsoft/ALAppExtensions#26766]
### Describe the request

Can you include sender for this event?

### Additional context

I need this to check other criteria on the page to override style.
Internal work item: [AB#539839](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539839)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21487.
