### ISSUE TITLE
Codeunit 5988 Serv-Documents Mgt. - OnPostDocumentLinesAfterCheckServItemRepairStatus

### ISSUE THREAD

**Issue by LaChris123** [microsoft/ALAppExtensions#26770]
### Describe the request

The following events are required for this object:
    
    [IntegrationEvent(false, false)]
    local procedure OnPostDocumentLinesAfterCheckServItemRepairStatus(var ServiceLine: Record "Service Line")
    begin
    end;	

### Additional context

     procedure PostDocumentLines(var Window: Dialog)
      begin
        ServLine.Reset();
        SortLines(ServLine);
        OnPostDocumentLinesOnAfterSortLines(ServHeader, ServLine);
        ServLedgEntryNo := FindFirstServLedgEntry(ServLine);
        if ServLine.Find('-') then
            repeat
                ServPostingJnlsMgt.SetItemJnlRollRndg(false);
                if ServLine.Type = ServLine.Type::Item then
                    DummyTrackingSpecification.CheckItemTrackingQuantity(
                      DATABASE::"Service Line", ServLine."Document Type".AsInteger(), ServLine."Document No.", ServLine."Line No.",
                      ServLine."Qty. to Ship (Base)", ServLine."Qty. to Invoice (Base)", Ship, Invoice);
                LineCount += 1;
                    Window.Update(2, LineCount);

                with ServLine do begin
                    OnPostDocumentLinesOnBeforeCheckServLine(ServHeader, ServLine, Ship, Invoice);

                    if Ship and ("Qty. to Ship" <> 0) or Invoice and ("Qty. to Invoice" <> 0) then
                        ServOrderMgt.CheckServItemRepairStatus(ServHeader, ServItemLine, ServLine);

                    OnPostDocumentLinesAfterCheckServItemRepairStatus(ServLine); //EVENT REQUEST
                    ServLineOld := ServLine;
    
    
    
    
Internal work item: [AB#539996](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539996)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21513.
