### ISSUE TITLE
[Event Request] COD456 Job Queue Management - Procedure ScheduleReport - OnBeforeScheduleReport

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26778]
### Describe the request

Please add the following Event/-s OnBeforeScheduleReport to procedure ScheduleReport in COD456 Job Queue Management

```
[Event Request] COD456 Job Queue Management - Procedure ScheduleReport - OnBeforeScheduleReport
    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Reporting Triggers", 'ScheduleReport', '', false, false)]
    local procedure ScheduleReport(ReportId: Integer; RequestPageXml: Text; var Scheduled: Boolean)
    var
        ScheduleAReport: Page "Schedule a Report";
        IsHandled : Boolean;
    begin
       IsHandled := FALSE;
        OnBeforeScheduleReport(ReportId;Scheduled,IsHandled)
        IF IsHandled THEN
          EXIT;

       Scheduled := ScheduleAReport.ScheduleAReport(ReportId, RequestPageXml);
    end;
```

```
 [IntegrationEvent(false, false)]
 local procedure OnBeforeScheduleReport(ReportId: Integer; RequestPageXml: Text; var Scheduled: Boolean; var IsHandled : Boolean)
    begin
    end;
```

### Additional context

Use a own Page to Schedule a Report
Internal work item: [AB#540599](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540599)

**Comment by nikolakukrika** [comment]
We do not want to introduce the extensibility in this place. It is simply wrong to be able to override the report from running. Use report selections or other standard setup that we have to override the report that is being run. Alternative is hide our actions and introduce your own.

**Comment by SKeiler** [comment]
Hi @nikolakukrika,

you missread my explination. We don't want to schedule another report, we want to use a own page (!) to schedule a report and want to replace the standard page.

**Comment by nikolakukrika** [comment]
@SKeiler The source of the problem is that this kind of event allows you to do anything. You may use it in one way, but after we implement it and ship it, it becomes available to everyone. This is an extensibility in a wrong place.  

You could subcribe to the event of the OnPageOpen of the Schedule Report page and run a different page with an Error('') to close original page. Alternative is to customize Schedule Report page via page customizations.
