### ISSUE TITLE
[Event Request] PAG682 Schedule a Report - Procedure ScheduleAReport - OnBeforeScheduleAReport

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26779]
### Describe the request

Please add the following Event/-s OnBeforeScheduleAReport to procedure ScheduleAReport in PAG682 Schedule a Report

```
[Event Request] PAG682 Schedule a Report - Procedure ScheduleAReport - OnBeforeScheduleAReport
    procedure ScheduleAReport(ReportId: Integer; RequestPageXml: Text): Boolean
    var
        ScheduleAReport: Page "Schedule a Report";
    begin
        OnBeforeScheduleAReport(ScheduleAReport);

        ScheduleAReport.SetParameters(ReportId, RequestPageXml);
        exit(ScheduleAReport.RunModal() = ACTION::OK);
    end;
```

```
 [IntegrationEvent(true, false)]
 local procedure OnBeforeScheduleAReport(var ScheduleAReport: Page "Schedule a Report")
    begin
    end;
```

### Additional context

Set Additional Parameters to Schedule a Report

As Alternative to the event it would be great if ScheduleAReport would not create a new instance of the page and instead would use the Current Instance (eliminate the local ScheduleAReport-Variable)
Internal work item: [AB#540590](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540590)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24662.
