### ISSUE TITLE
Table 5901 "Service Item Line" - Add event (OnAfterCreateDim) in function CreateDim

### ISSUE THREAD

**Issue by NunoLidd** [microsoft/ALAppExtensions#26771]
### Describe the request

We need an OnAfterCreateDim (similar to what you have in table 37 or table 5902) in function CreateDim

### Additional context

We need the ability to add an extra dimension to a service item line and the create dim function clears all dimensions and just puts the default ones
Internal work item: [AB#539930](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/539930)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21487.
