### ISSUE TITLE
[Request For External] codeunit 7304 "Whse. Jnl.-Register Batch" - CopyFieldsFromWhseJnlLineToItemJnlLine

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/ALAppExtensions#26776]
### Describe the request

Can you make  CopyFieldsFromWhseJnlLineToItemJnlLine a Global Function please

  local procedure CopyFieldsFromWhseJnlLineToItemJnlLine(WarehouseJournalLine: Record "Warehouse Journal Line"; var 

### Additional context

We are also trying to do an Item Reclass from Warehouse if something is changed on the Lines, that is not related to Whse Item Tracking Lines
Internal work item: [AB#540596](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540596)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21820.
