### ISSUE TITLE
OnAfterGetAvailabilityFilter2 in the Codeunit 99000845 "Reservation Management" should return a Result

### ISSUE THREAD

**Issue by miljance** [microsoft/ALAppExtensions#26781]
### Describe the request

Ther Event OnAfterGetAvailabilityFilter2 should return Result as var.
```
local procedure GetAvailabilityFilter2(AvailabilityDate: Date; SearchForSupply: Boolean) Result: Text[80]
var
    ReservEntry2: Record "Reservation Entry";
begin
    if SearchForSupply then
        ReservEntry2.SetFilter("Expected Receipt Date", '..%1', AvailabilityDate)
    else
        ReservEntry2.SetFilter("Expected Receipt Date", '>=%1', AvailabilityDate);

    Result := ReservEntry2.GetFilter("Expected Receipt Date");
    OnAfterGetAvailabilityFilter2(ReservEntry2, AvailabilityDate, SearchForSupply, Result);
end;

```

```
[IntegrationEvent(false, false)]
local procedure OnAfterGetAvailabilityFilter2(var ReservationEntry: Record "Reservation Entry"; AvailabilityDate: Date; SearchForSupply: Boolean; Result: Text[80])
begin
end;
```

### Additional context

We subscribe to this IntegrationEvent and it is currently not possible to return a different result.
Internal work item: [AB#540043](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540043)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21513.
