### ISSUE TITLE
[Bug]: Digital Voucher problem posting sale & purchase

### ISSUE THREAD

**Issue by NS-NN** [microsoft/ALAppExtensions#26780]
### Describe the issue

Microsoft implemented new functionality in connection with the new bookkeeping act in Denmark in Business Central version 24.2.
In connection with this, companies were stopped in posting sales & purchase if no incoming documents are attached.

**Sales**
It is possible to setup, that the system have to generate a document automatically and then it is possible to post.
The problem is that the normal invoice attachment is attached + a corresponding attachment called DigitalVoucher.
Can you please make an adjustment that makes it possible to avoid this?

**Purchase**
You are forced to attach incoming document when posting purchase order/invoice/credit memo or posting general journal with account type "Vendor". I know it will be a requirement, but as you see at the link below described by "Erhvervsstyrelsen" not all companies forced to do so yet (as I understand it).
Can you please tell me why it is required for all companies now or if it is possible to disable until it will be required?

https://erhvervsstyrelsen.dk/tidsplan-for-virksomheders-digitale-bogfoering
![image](https://github.com/microsoft/ALAppExtensions/assets/57817172/42e2072b-fedb-40d2-8d4f-b493b1c90ea8)

Thank you in advance.

### Expected behavior

Not possible to post sale & purchase

### Steps to reproduce

1. Open "Sales order", "Purchase Order" or "General Journal with account type Vendor".
2. Post document.
3. If no incoming document has been attached you will get an error.

### I will provide a fix for a bug

- [X] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Thank you very much for the detailed report and your suggestion to address the issue. However, I am happy to tell you that we've already hotfixed the issue and that you should receive a fix in the near future. You can get more details here: https://www.yammer.com/dynamicsnavdev/#/threads/show?threadId=2869519068225536
