### ISSUE TITLE
[Request For External] report 95 "Date Compress VAT Entries" - 'make EntrdDateComprReg' protected

### ISSUE THREAD

**Issue by ViPaas** [microsoft/ALAppExtensions#26782]
### Describe the request

We request to make the variable 'EntrdDateComprReg' protected in report 95 "Date Compress VAT Entries". 

### Additional context

We want to create a report extension and put additional checks on these settings before our customers run the report as we have found not all settings are compatible performance wise. 

Internal work item: [AB#540588](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540588)

**Comment by WJMSmit** [comment]
Additionally: expose all RequestPage-fields for every "Date Compress"-report, to be able to extend the behavior via ReportExtensions.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22878.
