### ISSUE TITLE
Codeunit 12 Gen. Jnl.-Post Line Set procedure InitGLEntryVATCopy as public.

### ISSUE THREAD

**Issue by LubomirUrx** [microsoft/ALAppExtensions#26792]
### Describe the request

Please, set procedure InitGLEntryVATCopy in codeunit 12 Gen. Jnl.-Post Line as public.

### Additional context

We need external access to the procedure.
Internal work item: [AB#540601](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540601)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21842.
