### ISSUE TITLE
[Event Request] codeunit 7017 "Price List Management" - OnAfterClearSourceFilters

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#26790]
### Describe the request

    local procedure ClearSourceFilters(var PriceListLine: Record "Price List Line")
    begin
        PriceListLine.SetRange("Source Type");
        PriceListLine.SetRange("Source No.");
        PriceListLine.SetRange("Parent Source No.");

        OnAfterClearSourceFilters(PriceListLine);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnAfterClearSourceFilters(var PriceListLine: Record "Price List Line")
    begin
    end;

### Additional context

Easy-peasy request I'd say.
Internal work item: [AB#540592](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540592)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21720.
