### ISSUE TITLE
[Enum Request] - "Average Cost Period" to enum so it can be extensible.

### ISSUE THREAD

**Issue by minaskats** [microsoft/ALAppExtensions#26795]
### Describe the request

Hello MSTeam

We would like the option of "Average Cost Period" to be converted as enum so it can be extensible.
Its is tables "Inventory Setup" & "Accounting Period".

### Additional context

We use also an option "Inventory Period" to our localization , in order to calculate costs differently.
Internal work item: [AB#540606](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540606)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21735.
