### ISSUE TITLE
[Feature Request] Codeunit 6620 Copy Document Mgt. - SetSkipCopyFromDescription

### ISSUE THREAD

**Issue by bcmako** [microsoft/ALAppExtensions#2679]
Dear AL team,

we need to set the flag "SkipCopyFromDescription" from external. Currently, the field can only be set using the SetPropertiesForInvoiceCorrection function, which is not sufficient.

**Comment by OlegRomashkov** [comment]
Hi bcmako,

There could be another option to skip creating "copy from" line: we can extend 2 events (OnBeforeInsertOldSalesDocNoLine and OnBeforeInsertOldPurchDocNoLine) by adding IsHandled parameter and skip inserting document line.

Are you ok with this solution?

Rgds,
Oleg.
