### ISSUE TITLE
[Request for External] Codeunit 1002 - "Job Create-Invoice" - procedures CreateNewInvoice, CreateSalesHeader, TestExchangeRate, TransferLine, CreateSalesLine

### ISSUE THREAD

**Issue by mrabus** [microsoft/ALAppExtensions#26794]
### Describe the request

To do a customization efficiently, I request to expose the following procedures in codeunit "Job Create-Invoice" as external: 

- CreateNewInvoice
- CreateSalesHeader
- TestExchangeRate
- TransferLine
- CreateSalesLine

### Additional context

Exposing these methods allows to create invoices without the need to copy all the functions 
Internal work item: [AB#540603](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540603)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21820.
