### ISSUE TITLE
suggestion: "SFTP Client" codeunit for NAV2018

### ISSUE THREAD

**Issue by CanuckNav74** [Microsoft/ALAppExtensions#268]
With filesystem access off-limits for AL 2.0 for now, this poses a big problem upgrading clients who have legacy customizations that transfer files to/from NAV and third party customers/vendors/banks/etc. as well as transfer files to/from third party software (e.g. Barcode label automation, Shipping Software, etc).

Many of these third party solutions are not able to integrate via http rest and rely on file transfers, making them nearly impossible to use from an extension. 

Proposal:

Can Microsoft create an "SFTP Client" Codeunit in NAV? Sample functionality includes (but not limited to) login/logout, list remote files, download a file, upload a file, delete a remote file, etc (if local client/server file system access is a security concern then use instream/outstream/memorystream when possible).

This would really open up NAV's integration capability.

**Comment by JesperSchulz** [comment]
@mrabus, spot on! Please create the needed wrappers for us to add to the product.
