### ISSUE TITLE
[Event change request] Codeunit 1535 "Approvals Mgmt." - CreateApprovalRequestForApprover - OnCreateApprovalRequestForApproverOnAfterCheckUserSetupUserID

### ISSUE THREAD

**Issue by UrbMigle** [microsoft/ALAppExtensions#26804]
### Describe the request

Hi,

Please add IsHandled pattern to the publisher OnCreateApprovalRequestForApproverOnAfterCheckUserSetupUserID (currently there is none) in CreateApprovalRequestForApprover, "Approvals Mgmt." codeunit.

```
       if not UserSetup.Get(UserId) then
            Error(UserIdNotInSetupErr, UsrId);

        OnCreateApprovalRequestForApproverOnAfterCheckUserSetupUserID(UserSetup, WorkflowStepArgument, ApprovalEntryArgument, IsHandled);

        if IsHandled then
            exit;

        UsrId := UserSetup."Approver ID";
        if not UserSetup.Get(UsrId) then begin
            if not UserSetup."Approval Administrator" then
                Error(ApproverUserIdNotInSetupErr, UserSetup."User ID");
            UsrId := UserId;
        end;

    [IntegrationEvent(false, false)]
    local procedure OnCreateApprovalRequestForApproverOnAfterCheckUserSetupUserID(var UserSetup: Record "User Setup"; WorkflowStepArgument: Record "Workflow Step Argument"; ApprovalEntryArgument: Record "Approval Entry"; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

In the conditional statement after the suggested event change, we want to not only check `if not UserSetup."Approval Administrator"`, but also add some additional conditions. However, there is currently no way to do so.
Internal work item: [AB#540610](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540610)

**Comment by Groenbech96** [comment]
What about 
IsAllowed := True;
OnCreateApprovalRequestForApproverIsUserAllowedApprover(IsAllowedApprover)
if (not UserSetup."Approval Administrator") and (not IsAllowedApprover) then

`

I dont want to skip the entire logic here.
Could this work?

**Comment by UrbMigle** [comment]
This could work, but Allowed Approver is not always Approval Administrator. So could an OR be used instead of an AND?

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25608.
