### ISSUE TITLE
Add a parameter to new event OnBeforeUpdateBinContent into codeunit 6501 "Item Tracking Data Collection

### ISSUE THREAD

**Issue by Flavioide** [microsoft/ALAppExtensions#26800]
[IntegrationEvent(false, false)]
local procedure OnBeforeUpdateBinContent (var TempEntrySummary: Record "Entry Summary" temporary; CurrItemTrackingCode: Record "Item Tracking Code";var IsHandled:boolean;TempGlobalReservEntry: Record "Reservation Entry")
begin
end;
 
````
OnBeforeUpdateBinContent (TempEntrySummary, CurrItemTrackingCode,IsHandled,TempGlobalReservEntry);
    if IsHandled then exit;

    if CurrBinCode = '' then
        exit;
Internal work item: [AB#540602](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540602)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21820.
