### ISSUE TITLE
Table 380 "Detailed Vendor Ledg. Entry" - EventRequest "OnBeforeSetLedgerEntryAmount"

### ISSUE THREAD

**Issue by joaorosadev** [microsoft/ALAppExtensions#26808]
### Describe the request

Greetings,

I'd like to know if it's possible to add the event "OnBeforeSetLedgerEntryAmount" on table 380 "Detailed Vendor Ledg. Entry", just as it is in table 379 "Detailed Cust. Ledg. Entry"?

Best Regards,
Jo??o Rosa

### Additional context

We would like to add extra custom entry types validation to determine the field "Ledger Entry Amount", just as is possible in the cust. table.
Internal work item: [AB#540608](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540608)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21752.
