### ISSUE TITLE
[Expose procedure] Table 27 Item - CalcVAT

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26801]
### Describe the request

Can you please expose function CalcVAT in table 27 Item? (make global instead of local)

### Additional context

We would like to store other 'price' related fields that should follow similar logic to calculate the price with/without VAT, using the "VAT Bus. Posting Gr. (Price)" logic, supported by the CalcVAT function.
Internal work item: [AB#540612](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540612)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21842.
