### ISSUE TITLE
[Event Request] Codeunit 1535 "Approvals Mgmt." - DelegateApprovalRequests  -  OnAfterDelegateApprovalRequestOnBeforeShowApprovalDelegatedMessage

### ISSUE THREAD

**Issue by UrbMigle** [microsoft/ALAppExtensions#26803]
### Describe the request

Hi,

Please add a new event publisher OnAfterDelegateApprovalRequestOnBeforeShowApprovalDelegatedMessage in DelegateApprovalRequests of codeunit 1535 "Approvals Mgmt." .

```
        if ApprovalEntry.FindSet() then begin
            repeat
                ApprovalEntryToUpdate := ApprovalEntry;
                DelegateSelectedApprovalRequest(ApprovalEntryToUpdate, true);
            until ApprovalEntry.Next() = 0;

            OnAfterDelegateApprovalRequestOnBeforeShowApprovalDelegatedMessage(ApprovalEntry, IsHandled);
            if not IsHandled then
                Message(ApprovalsDelegatedMsg);
        end;


    [IntegrationEvent(false, false)]
    local procedure OnAfterDelegateApprovalRequestOnBeforeShowApprovalDelegatedMessage(ApprovalEntry: Record "Approval Entry"; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

Currently there is no way to skip the message about successful approval delegation without skipping the whole code in the procedure.
Internal work item: [AB#540609](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540609)

**Comment by Groenbech96** [comment]
What is the scenario? 
Why do you need to skip the message?

**Comment by Groenbech96** [comment]
I suggest to create a BC Ideas for enabling support for batch delegation. We wont introduce an IsHandled event..
