### ISSUE TITLE
Events in  "TransferOrder-Post Transfer"

### ISSUE THREAD

**Issue by Kvamer** [microsoft/ALAppExtensions#26807]
### Describe the request

Just like in "TransferOrder-Post Shipment"   before the Transferline.Find

            TransShptLine.LockTable();
            TransLine.SetRange(Quantity);
            TransLine.SetRange("Qty. to Ship");
            OnRunOnAfterTransLineSetFiltersForShptLines(TransLine, TransHeader, Location, WhseShip);
            if TransLine.Find('-') then

In  "TransferOrder-Post Transfer" there are two place were this should be added to filter the TransferLine when you don't want alle lines to be processed

Line 74 and next gives   and before the Findset there should be an avent
        TransLine.Reset();
        TransLine.SetRange("Document No.", TransHeader."No.");
        TransLine.SetRange("Derived From Line No.", 0);
        TransLine.SetFilter(Quantity, '<>%1', 0);
//>>   New Event
        if TransLine.FindSet() then
            repeat

the same on line 133
        TransLine.SetRange(Quantity);
//>> New Event
        if TransLine.FindSet() then
            repeat

### Additional context

In a situation you don't want to process all transferlines you can't add additional filtering to the transferline.

Internal work item: [AB#540611](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540611)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21720.
