### ISSUE TITLE
Table 38 Purchase Header - [EventRequest] "OnValidatePayToVendorNoOnAfterConfirmed"

### ISSUE THREAD

**Issue by joaorosadev** [microsoft/ALAppExtensions#26809]
### Describe the request

Greetings,

I'd like to know if it's possible to add the event "OnValidatePayToVendorNoOnAfterConfirmed" to table 38 "Purchase Header".
The event would be similar to the event "OnValidateBillToCustomerNoOnAfterConfirmed" of table 36 "Sales Header".

Best Regards,
Jo??o Rosa

### Additional context

We would like to extend some custom sales functionality into purchases.
Internal work item: [AB#540613](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540613)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22165.
