### ISSUE TITLE
[Event Request] CU1381 "Customer Templ. Mgt." - local procedure CreateCustomerFromTemplate()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#26812]
### Describe the request

Add a event in CU1381 "Customer Templ. Mgt." - local procedure CreateCustomerFromTemplate()

### Additional context

procedure CreateCustomerFromTemplate()

...
Customer.SetInsertFromTemplate(true);
Customer.Init();

----------------------- ADD EVENT ----------------------
OnBeforeInitCustomerNo(VAR Customer)

InitCustomerNo(Customer, CustomerTempl);
...
Internal work item: [AB#540875](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540875)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21820.
