### ISSUE TITLE
[Event Request] CU1385 "Vendor Templ. Mgt." - local procedure CreateVendorFromTemplate()

### ISSUE THREAD

**Issue by CyrilleJsmt** [microsoft/ALAppExtensions#26813]
### Describe the request

Add a event in CU1385 "Vendor Templ. Mgt." - local procedure CreateVendorFromTemplate()

### Additional context

procedure CreateVendorFromTemplate()

...
Vendor.SetInsertFromTemplate(true);
Vendor.Init();

----------------------- ADD EVENT ----------------------
OnBeforeInitVendorNo(VAR Vendor)

InitVendorNo(Vendor, VendorTempl);
Internal work item: [AB#540877](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540877)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21820.
