### ISSUE TITLE
[Event/External Request] Codeunit 7324 Whse.-Activity-Post

### ISSUE THREAD

**Issue by shuyusheng** [microsoft/ALAppExtensions#26810]
### Describe the request

Hi team, we'd like the following 2 extensibility changes made to Codeunit 7324 Whse.-Activity-Post

- Expose `GetLocation` function as public.
- Add event `OnPostWhseActivityLineOnBeforeCreatePostedActivHeader` with `IncludeSender = true`.
  - Call this right before `CreatePostedActivHeader` in function `PostWhseActivityLine`.
  - `IncludeSender` is required so we can call `GetLocation` on this codeunit ourselves.

```
// Expose Function
procedure GetLocation(LocationCode: Code[10])
begin
    if LocationCode = '' then
        Clear(Location)
    else
        if Location.Code <> LocationCode then
            Location.Get(LocationCode);
end;

local procedure PostWhseActivityLine(WhseActivHeader: Record "Warehouse Activity Header"; var WhseActivLine: Record "Warehouse Activity Line")
// ...
 // New Event Call
OnPostWhseActivityLineOnBeforeCreatePostedActivHeader(WhseActivHeader);
CreatePostedActivHeader(WhseActivHeader, PostedInvtPutAwayHeader, PostedInvtPickHeader);

// ...

// Include Sender Required
[IntegrationEvent(true, false)]
// New Event
local procedure OnPostWhseActivityLineOnBeforeCreatePostedActivHeader(var WhseActivHeader: Record "Warehouse Activity Header")
begin
end;
```

Thanks

### Additional context

This will help us modify the warehouse activity header location code as before it's posted.
Internal work item: [AB#540876](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540876)

**Comment by JakovljevicDusan** [comment]
Event will be added in the next minor in v24.
Exposing GetLocation as global will have to wait until v25.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21820.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21820.
