### ISSUE TITLE
[Event Request] - Table 167 Job Status OnValidate

### ISSUE THREAD

**Issue by LewisHyettTES** [microsoft/ALAppExtensions#26818]
### Describe the request

Within the OnValidate of the Status field on Table 167 Job the following call is made:

TimeSheetLine.CheckIfTimeSheetLineLinkExist(Rec);

We would like to bypass this check but there is currently no way to achieve this. 

I would like the following event:

```
OnBeforeCheckTimeSheetLineLinkExists(Rec, Ishandled);
if not IsHandled then
TimeSheetLine.CheckIfTimeSheetLineLinkExist(Rec);
```

```
 [IntegrationEvent(false, false)]
    local procedure OnBeforeCheckTimeSheetLineLinkExists(var Job: Record Job; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

Our customer may Open a job to post an Individual Invoice but then set the status back to Planning. This is to lock the Job down again to prevent further activity. 
Internal work item: [AB#541682](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/541682)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21820.
