### ISSUE TITLE
Cannot create a permission set for page inspection because page 9631 Page Inspection cannot be accessed on Cloud

### ISSUE THREAD

**Issue by Mahibabu1993** [microsoft/ALAppExtensions#26814]
### Describe the request

We need a permission set which only includes the page inspection objects. The new permission set should include below permissions. 

```
Permissions = System "Tools, Zoom" = X,
                  page "Page Inspection" = X,
                  page "Page Inspection Fields" = X,
                  page "Page Inspection Filters" = X;
```

We tried to create a permission set for this on our extension but we cannot use page 9631 "Page Inspection" on our cloud extension. So we are blocked here. We either need a page inspection permission set from Microsoft on our BaseApp or the page "Page Inspection" should be accessible in Cloud.

### Additional context

We need a permission set only for page inspection. We want to provide page inspection permission to certain users but we don't want them to have permission for all pages. So we need to be able to create a new permission set with only page inspection objects.
Internal work item: [AB#540882](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/540882)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25201.
