### ISSUE TITLE
[Event Parameter Request] Codeunit 22 "Item Jnl.-Post Line" - Event "OnInsertConsumpEntryOnBeforePostItem" 

### ISSUE THREAD

**Issue by Mariangela-DeMaio-EOS** [microsoft/ALAppExtensions#26815]
### Describe the request

Hello,
we need the variable "PostWhseJnlLine" and the record "WhseJnlLine" of the procedure "InsertConsumpEntry" as parameters in the event "OnInsertConsumpEntryOnBeforePostItem" of the codeunit 22 "Item Jnl.-Post Line".

We need the record WhseJnlLine passed by var to modify it.

`

     local procedure InsertConsumpEntry(var ProdOrderComp: Record "Prod. Order Component"; ProdOrderCompLineNo: 
                               Integer; QtyBase: Decimal; ModifyProdOrderComp: Boolean)
    var
        PostWhseJnlLine: Boolean;
        GetItemResult: Boolean;
    begin
        OnBeforeInsertConsumpEntry(ProdOrderComp, QtyBase, ModifyProdOrderComp, ItemJnlLine, TempSplitItemJnlLine);

        ItemJnlLine.Quantity := QtyBase;
        ItemJnlLine."Quantity (Base)" := QtyBase;
        ItemJnlLine."Invoiced Quantity" := QtyBase;
        ItemJnlLine."Invoiced Qty. (Base)" := QtyBase;
        ItemJnlLine."Prod. Order Comp. Line No." := ProdOrderCompLineNo;
        if ModifyProdOrderComp then begin
            if not CalledFromInvtPutawayPick then
                ProdOrderCompReserve.TransferPOCompToItemJnlLine(ProdOrderComp, ItemJnlLine, QtyBase);
            OnBeforeProdOrderCompModify(ProdOrderComp, ItemJnlLine);
            ProdOrderComp.Modify();
        end;

        if ItemJnlLine."Value Entry Type" <> ItemJnlLine."Value Entry Type"::Revaluation then begin
            GetLocation(ItemJnlLine."Location Code");
            if Location."Bin Mandatory" and (not CalledFromInvtPutawayPick) then begin
                GetItemResult := GetItem(ItemJnlLine."Item No.", false);
                if GetItemResult and Item.IsInventoriableType() then begin
                    ProdOrderWarehouseMgt.CreateWhseJnlLineFromConsumptionJournal(ItemJnlLine, WhseJnlLine);
                    WMSManagement.CheckWhseJnlLine(WhseJnlLine, 3, 0, false);
                    PostWhseJnlLine := true;
                end;
            end;
        end;

        // Add PostWhseJnlLine and WhseJnlLine to event
        OnInsertConsumpEntryOnBeforePostItem(ItemJnlLine, ProdOrderComp);

        PostItem();
        if PostWhseJnlLine then
            WhseJnlRegisterLine.RegisterWhseJnlLine(WhseJnlLine);

        OnAfterInsertConsumpEntry(WhseJnlLine, ProdOrderComp, QtyBase, PostWhseJnlLine, ItemJnlLine, ItemLedgEntryNo);
    end;`

### Additional context

**Event**
```
[IntegrationEvent(false, false)]
    local procedure OnInsertConsumpEntryOnBeforePostItem(var ItemJournalLine: Record "Item Journal Line"; ProdOrderComponent: Record "Prod. Order Component")
    begin
    end;
```

**New Event**

```
[IntegrationEvent(false, false)]
    local procedure OnInsertConsumpEntryOnBeforePostItem(var ItemJournalLine: Record "Item Journal Line"; ProdOrderComponent: Record "Prod. Order Component"; PostWhseJnlLine: Boolean; var WarehouseJournalLine: Record "Warehouse Journal Line")
    begin
    end;
```
Internal work item: [AB#541681](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/541681)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21820.
