### ISSUE TITLE
Request two events in report 34 "Change Payment Tolerance"

### ISSUE THREAD

**Issue by selmiislem** [microsoft/ALAppExtensions#26817]
### Describe the request

Greetings,

I'd like to know if it's possible to add the event OnBeforeModifyCustLedgEntryOnChangeCustLedgEntries(var CustLedgEntry: Record "Cust. Ledger Entry")  in function  ChangeCustLedgEntries()  and the event  OnBeforeModifyVendLedgEntryOnChangeVendLedgEntries(var  VendLedgEntry: Record "Vendor Ledger Entry")  in function  ChangeVendLedgEntries() to trigger OnPostReport() in report 34 "Change Payment Tolerance"

Best Regards,

### Additional context

This is related to the Max Payment Tolerance Amount when the calculated Max. payment Tolerance Amount is higher (absolute value) then the Max. Payment Tolerance Amount is taken from the setup. This needs to be related to the sign of the Customer/Vendor ledger entry.
Internal work item: [AB#541679](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/541679)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21851.
