### ISSUE TITLE
[Event Parameter Request] Table 167 "Job" - Event "OnBeforeSellToCustomerNoUpdated"

### ISSUE THREAD

**Issue by JosefKainzSHB** [microsoft/ALAppExtensions#26816]
### Describe the request

Can we get the variable SkipSellToContact as a parameter in the event OnBeforeSellToCustomerNoUpdated in the job table

**Event**
```
[IntegrationEvent(false, false)]
    local procedure OnBeforeSellToCustomerNoUpdated(var Job: Record Job; var xJob: Record Job; CallingFieldNo: Integer; var IsHandled: Boolean)
    begin
    end;
```

**New Event**
```
[IntegrationEvent(false, false)]
    local procedure OnBeforeSellToCustomerNoUpdated(var Job: Record Job; var xJob: Record Job; CallingFieldNo: Integer; var IsHandled: Boolean; var SkipSellToContact: Boolean)
    begin
    end;
```

### Additional context

We need this parameter to differentiate if the procedure is called from the UpdateSellToCust procedure in the job table.
Internal work item: [AB#541680](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/541680)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21820.
