### ISSUE TITLE
[Internal] Shopify Contributions

### ISSUE THREAD

**Issue by JesperSchulz** [microsoft/ALAppExtensions#26819]
Placeholder issue for work on the Shopify connector.

**Comment by JesperSchulz** [comment]
This one is still needed, as further open PRs exist.

**Comment by JesperSchulz** [comment]
More PRs coming. Reopening.

**Comment by onbuyuka** [comment]
Still got one more PR

**Comment by aholstrup1** [comment]
Shopify app has been moved to https://github.com/microsoft/BCApps/tree/main/src/Apps/W1/Shopify. Please create your contributions there
