### ISSUE TITLE
[Event Request] Codeunit 7314 - Warehouse Availability Mgt. - OnBeforeCalcQtyPickedNotShipped

### ISSUE THREAD

**Issue by passion4dev** [microsoft/ALAppExtensions#26820]
### Describe the request

Dear ALAppExtensions team,

Through this issue we would like to request event publisher `OnBeforeCalcQtyPickedNotShipped` to be added to Codeunit 7314 Warehouse Availability Mgt. with the following signature:
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeCalcQtyPickedNotShipped(SourceType: Integer; SourceSubType: Option; SourceID: Code[20]; SourceRefNo: Integer, var QtyPickedNotShippedBase, var IsHandled)
    begin
    end;
```

which would be called as follows from `CalcQtyPickedNotShipped`:
```al
    local procedure CalcQtyPickedNotShipped(SourceType: Integer; SourceSubType: Option; SourceID: Code[20]; SourceRefNo: Integer): Decimal
    var
        WarehouseEntry: Record "Warehouse Entry";
        QtyPickedBase: Decimal;
        QtyShippedBase: Decimal;
        IsHandled: Boolean; //new
    begin
        //new start
        IsHandled := false; 
        OnBeforeCalcQtyPickedNotShipped(SourceType, SourceSubType, SourceID, SourceRefNo, QtyPickedBase, IsHandled)
        if IsHandled then
          exit(QtyPickedBase);
        //new end
        WarehouseEntry.Reset();
```

### Additional context

We need to be able to take more WarehouseEntry records into account on calculating the Qty Picked Not Shipped.
Internal work item: [AB#541678](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/541678)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 21820.
