### ISSUE TITLE
Report 393 "Suggest Vendor Payments" events

### ISSUE THREAD

**Issue by andrestambek4ps** [microsoft/ALAppExtensions#26829]
### Describe the request

Hi,
On behalf of 4PS I would like to request  two existing integration events be amended and four added to report 393 ???Suggest Vendor Payments??? please.

Could TempPayableVendorlLedgerEntry be added as a parameter to the existing events below:

            [IntegrationEvent(false, false)]
            //request for TempPayableVendorLedgerEntry to be added
            local procedure OnMakeGenJnlLinesOnBeforeVendorPaymentBufferInsertNonSummarize(var TempVendorPaymentBuffer: Record "Vendor Payment Buffer" temporary; VendorLederEntry: Record "Vendor Ledger Entry"; var SummarizePerVend: Boolean; var NextDocNo: Code[20]; **var TempPayableVendorLedgerEntry: Record "Payable Vendor Ledger Entry" temporary**)
            begin
            end;

and

            [IntegrationEvent(false, false)]
            //Request for TempPayableVendorLedgerEntry to be added
            local procedure OnMakeGenJnlLinesOnBeforeVendorPaymentBufferModify(var TempVendorPaymentBuffer: Record "Vendor Payment Buffer" temporary; VendorLederEntry: Record "Vendor Ledger Entry"; **var TempPayableVendorLedgerEntry: Record "Payable Vendor Ledger Entry" temporary**)
            begin
            end;

Additionally could the following events be added:

1. Event in PostDataItem trigger after LastLineNo is assigned value:

            if GenJnlLine.FindLast() then begin
	            LastLineNo := GenJnlLine."Line No.";
	            GenJnlLine.Init();
            end;
            **//New event requested
            OnPostDataItemOnBeforeMakeGenJnlLines(GenJnlLine, GenJnlBatch, TempVendorLedgerEntry);**
            Window2.Open(Text008);
            
Event signature:

            [IntegrationEvent(false, false)]
            local procedure OnPostDataItemOnBeforeMakeGenJnlLines(var GenJnlLine: Record "Gen. Journal Line"; var GenJnlBatch: Record "Gen. Journal Batch"; var TempPayableVendorLedgEntry: Record "Vendor Ledger Entry" temporary)
            begin
            end;
            

2. Event in MakeGenJnlLines procedure before ???Vend. Entry-Edit??? codeunit is run:

            
            VendLedgEntry."Amount to Apply" := VendLedgEntry."Remaining Amount";
            **//New event requested
            OnMakeGenJnlLinesOnBeforeModifyVendorLedgerEntry(VendLedgEntry);**
            CODEUNIT.Run(CODEUNIT::"Vend. Entry-Edit", VendLedgEntry);
            
Event signature:

            [IntegrationEvent(false, false)]
            local procedure OnMakeGenJnlLinesOnBeforeModifyVendorLedgerEntry(var VendLedgEntry: Record "Vendor Ledger Entry")
            begin
            end;

3. Event with IsHandled in InsertGenJnlLine procedure after ???Posting No. Series??? gets assigned:

            "Posting No. Series" := GenJnlBatch."Posting No. Series";
            **//New event requested with IsHandled >>
            OnInsertGenJournalLineOnBeforeAssignDocumentNo(GenJnlLine, GenJnlLine2, GenJnlBatch, TempVendorPaymentBuffer, NextDocNo, BankPmtType, DocNoPerLine, TempOldVendorPaymentBuffer, SummarizePerVend, IsHandled);
            if not IsHandled then begin
                //New event requested with IsHandled <<**
                if SummarizePerVend then
                    "Document No." := TempVendorPaymentBuffer."Document No."
                else
                    if DocNoPerLine then begin
                        if TempVendorPaymentBuffer.Amount < 0 then
                            "Document Type" := "Document Type"::Refund;

                        "Document No." := NextDocNo;
                        RunIncrementDocumentNo(false);
                    end else
                        if (GenJnlLine2."Bal. Account No." = '') and not DocNoPerLine then
                            "Document No." := NextDocNo
                        else
                            if (TempVendorPaymentBuffer."Vendor No." = TempOldVendorPaymentBuffer."Vendor No.") and
                               (TempVendorPaymentBuffer."Currency Code" = TempOldVendorPaymentBuffer."Currency Code")
                            then
                                "Document No." := TempOldVendorPaymentBuffer."Document No."
                            else begin
                                "Document No." := NextDocNo;
                                RunIncrementDocumentNo(false);
                                TempOldVendorPaymentBuffer := TempVendorPaymentBuffer;
                                TempOldVendorPaymentBuffer."Document No." := "Document No.";
                            end;
            **end; //New event requested with IsHandled**

Event signature:

            [IntegrationEvent(false, false)]
            local procedure OnInsertGenJournalLineOnBeforeAssignDocumentNo(var GenJournalLine: record "Gen. Journal Line"; var GenJournalLine2: record "Gen. Journal Line"; var GenJournalBatch: record "Gen. Journal Batch"; var TempVendorPaymentBuffer: record "Vendor Payment Buffer" temporary; var NextDocNo: Code[20]; BankPmtType: Enum "Bank Payment Type"; DocNoPerLine: Boolean; var TempOldVendorPaymentBuffer: Record "Vendor Payment Buffer" temporary; SummarizePerVend: Boolean; var IsHandled: Boolean)
                begin
                end;

4. Event at the start of  SetBankAccCurrencyFilter procedure

              local procedure SetBankAccCurrencyFilter(BalAccType: Enum "Gen. Journal Account Type"; BalAccNo: Code[20]; var TempPayableVendorLedgerEntry: Record "Payable Vendor Ledger Entry")
              var
	              BankAcc: Record "Bank Account";
              begin
	              **//New event requested
	              OnBeforeSetBankAccCurrencyFilter(BalAccType, BalAccNo, TempPayableVendorLedgerEntry);** 
	              if BalAccType = BalAccType::"Bank Account" then

Event signature:

            [IntegrationEvent(false, false)]
            local procedure OnBeforeSetBankAccCurrencyFilter(BalAccType: Enum Microsoft.Finance.GeneralLedger.Journal."Gen. Journal Account Type"; BalAccNo: Code[20]; var TempPayableVendorLedgerEntry: Record "Payable Vendor Ledger Entry" temporary)
            begin
            end;

### Additional context

The request stems form the need to
 - perform additional checks on Vendor Ledger Entries related to subcontractors
 - update additional amounts  and other custom fields on Gen. Journal Line from TempPayableLedgerEntry
 - handle document number incrementation in fringe scenarios
 - apply additional project specific filtering on Bank Account No. 
Internal work item: [AB#542008](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542008)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24752.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 24761.
