### ISSUE TITLE
[Event Request] Codeunit 5616 "Depreciation Calculation".CalcRounding

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/ALAppExtensions#26825]
### Describe the request

Please add new parameter to existing event:
```
procedure CalcRounding(DeprBookCode: Code[10]; DeprAmount: Decimal): Decimal
var
DeprBook: Record "Depreciation Book";
IsHandled: Boolean;
begin
with DeprBook do begin
Get(DeprBookCode);

IsHandled := false;
//------------------------------------OnBeforeCalcRounding
//OnBeforeCalcRounding(DeprBook, DeprAmount, IsHandled);
OnBeforeCalcRounding(DeprBook, DeprAmount, DeprAmount, IsHandled);
//------------------------------------OnBeforeCalcRounding
if IsHandled then
exit(DeprAmount);

if "Use Rounding in Periodic Depr." then
exit(Round(DeprAmount, 1));

exit(Round(DeprAmount));
end;
end;

[IntegrationEvent(false, false)]
//------------------------------------OnBeforeCalcRounding
//local procedure OnBeforeCalcRounding(DeprBook: Record "Depreciation Book"; var DeprAmount: Decimal; var IsHandled: Boolean)
local procedure OnBeforeCalcRounding(DeprBook: Record "Depreciation Book"; OrigDeprAmount: Decimal; var DeprAmount: Decimal; var IsHandled: Boolean)
//------------------------------------OnBeforeCalcRounding
begin
end;
```

### Additional context

We need new parameter for our custom rounding. Problem is that for CZ legislation exist subscriber for OnBeforeCalcRounding. This subscriber rounding amount. After that is called our subscriber, but amount is rounded from previous subscriber. So our event cant round amount properly by customized setup. We need to know original amount that was send to event.
Internal work item: [AB#542016](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542016)

**Comment by fridrichovsky** [comment]
Hello @JesperSchulz , please can you check this issue?

**Comment by fridrichovsky** [comment]
Hello  @AndersLarsenMicrosoft , please can you check this event we are waiting for it.

**Comment by JesperSchulz** [comment]
I will ping the owning team and ask them to look into this request. Not sure why it hasn't been picked up yet.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26425.
