### ISSUE TITLE
[Function Expose] Table 39 Purchase Line - CheckAssosiatedSalesOrder

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26822]
### Describe the request

Table 37 has the function CheckAssocPurchOrder exposed. (OK)
Table 39 does not have the equivalent function **CheckAssosiatedSalesOrder** exposed. Can you please make this function public?

![image](https://github.com/microsoft/ALAppExtensions/assets/25268332/7565d192-97fc-4898-8aa3-1f93511d8882)

PS: It would be great if requests for Sales would be reviewed to be applied on Purchase / Service and vice versa. Having similar events / function (signature) in all domains would benefit a lot.

### Additional context

*
Internal work item: [AB#542020](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542020)

**Comment by fvet** [comment]
PS: Please fix the typo as well and rename the local function to CheckAsso**c**iatedSalesOrder before exposing

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22165.
