### ISSUE TITLE
Request for function Scope('OnPrem') removal

### ISSUE THREAD

**Issue by RowaldNieswaag** [microsoft/ALAppExtensions#26843]
### Describe the request

There are currently a lot of functions in the latest dutch (nl) version of the base application that have a OnPrem scope without any reason. Could you remove these so we can avoid duplicating code and use these functions?

This is a list of functions that we've run into, but there are way more functions in localization objects that are incorrectly flagged as OnPrem.

**Table 79 Company Information:**
- GetVATIdentificationNo()

![image](https://github.com/user-attachments/assets/720e1bc4-c396-403a-8d74-d88da6f71904)

**Table 11409 "Elec. Tax Declaration Header":**
-  InsertLine()
- ClearLines()
- FormatDateTime()

![image](https://github.com/user-attachments/assets/9546d08e-2c2e-48e9-89d1-2a47c503ebe2)

**Table 11411 "Elec. Tax Decl. VAT Category"**
- GetCategoryCode()

![image](https://github.com/user-attachments/assets/99cf3c32-13d9-4a37-ab61-f76f05738fae)

**Report 12 "VAT Statement"**
- SetElectronicVAT()

![image](https://github.com/user-attachments/assets/1a8d8f59-b2a8-4537-92a3-396d0bd36fe5)

**Codeunit 1220 "SEPA CT-Export File"**
- Export()

![image](https://github.com/user-attachments/assets/b914ed3d-f8b7-4536-bc01-15614ac173a5)

**Table 11307 "G/L Entry Application Buffer"**
- ShowDimensions()
- Undo()
- RealEntryChanged()
- GetAppliedEntries()

![image](https://github.com/user-attachments/assets/09e57e69-7331-4637-941c-17c2cd5231df)
![image](https://github.com/user-attachments/assets/9102c513-5ab8-4625-abd4-29d6844dc5c3)

**Table 11000002 "Payment History Line"**
- GetUnstrRemitInfo()
- WillBeSent()

![image](https://github.com/user-attachments/assets/e296d7e0-c177-47b4-b82f-e1c131b72fa3)
![image](https://github.com/user-attachments/assets/f67e4700-c070-4026-8d7f-abe1c2247072)

**Codeunit 11000006 "CBG Statement Reconciliation"**
- ResetNumbers()

![image](https://github.com/user-attachments/assets/cd34addc-2399-4530-8d16-6f7daaf7d872)

**Codeunit 11400 "Local Functionality Mgt."**
- GetPmtHistLineCountAndAmtForSEPAISO20022Pain()
- GetPmtHistLineCountAndAmt()

![image](https://github.com/user-attachments/assets/bc04185f-d907-476b-8932-6bb61e66cb16)
![image](https://github.com/user-attachments/assets/9bb1c54b-1fa2-468f-855e-c8cb7004e177)

### Additional context

We are currently in the proces of changing our app targets to Cloud and are running into some issues calling functionality in de base application (dutch localization objects).

[OnPrem.xlsx](https://github.com/user-attachments/files/16232759/OnPrem.xlsx)
Internal work item: [AB#542072](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542072)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25286.
