### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnCustPostApplyCustLedgEntryOnBeforeCheckPostUnrealizedVAT

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#26846]
### Describe the request

Hello, can you please add a new Event OnCustPostApplyCustLedgEntryOnBeforeCheckPostUnrealizedVAT in Codeunit 12 "Gen. Jnl.-Post Line"?

```
    procedure CustPostApplyCustLedgEntry(var GenJnlLinePostApply: Record "Gen. Journal Line"; var CustLedgEntryPostApply: Record "Cust. Ledger Entry")
.
.
.
        // Post the Dtld customer entry
        OnCustPostApplyCustLedgEntryOnBeforePostDtldCustLedgEntries(CustLedgEntry);
        DtldLedgEntryInserted := PostDtldCustLedgEntries(GenJnlLine, TempDtldCVLedgEntryBuf, CustPostingGr, false);

        OnCustPostApplyCustLedgEntryOnBeforeCheckPostUnrealizedVAT(GenJnlLine, TempDtldCVLedgEntryBuf, DtldLedgEntryInserted);
        CheckPostUnrealizedVAT(GenJnlLine, true);

        if DtldLedgEntryInserted then
            if IsTempGLEntryBufEmpty() then
                DtldCustLedgEntry.SetZeroTransNo(NextTransactionNo);

        OnCustPostApplyCustLedgEntryOnBeforeFinishPosting(GenJnlLine, CustLedgEntry);

        FinishPosting(GenJnlLine);

        OnAfterCustPostApplyCustLedgEntry(GenJnlLine, GLReg, CustLedgEntry);
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnCustPostApplyCustLedgEntryOnBeforeCheckPostUnrealizedVAT(var GenJournalLine: Record "Gen. Journal Line"; var DtldCVLedgEntryBuffer: Record "Detailed CV Ledg. Entry Buffer"; var DtldLedgEntryInserted: Boolean)
    begin
    end;
```

### Additional context

We???d like to modify the GenJournalLine with values from the DtldCVLedgEntryBuffer, and in some special cases we???d like to change the value of DtldLedgEntryInserted.
Internal work item: [AB#542077](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542077)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22922.
