### ISSUE TITLE
[Event Request] Codeunit 5700 User Setup Management GetLocation

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#2684]
We have the need to change the UserRespCenter for DocType::Sales.  We'd like an event added to the DocType::Sales portion of the case statement in the GetLocation function of the User SEtup Management codeunit.

OnBeforeGetLocationDocTypeSales(VAR AccLocation, VAR RespCenterCode, VAR UserLocation, VAR IsHandled)

Example:
CASE DocType OF
  DocType::Sales:
    BEGIN    
    
 CERP_OnBeforeGetLocationDocTypeSales(AccLocation,RespCenterCode,UserLocation,Handled);  
      IF NOT Handled THEN
        UserRespCenter := GetSalesFilter;
    END;
  DocType::Purchase:
    UserRespCenter := GetPurchasesFilter;
  DocType::Service:
    UserRespCenter := GetServiceFilter;
END;

**Comment by AlexanderYakunin** [comment]
You already have this possibility in 
[External] GetSalesFilter2(UserCode : Code[50]) : Code[10]
IF NOT HasGotSalesUserSetup THEN BEGIN
  IsHandled := FALSE;
  OnBeforeGetSalesFilter2(UserCode,UserLocation,SalesUserRespCenter,IsHandled);
  IF IsHandled THEN
    EXIT(SalesUserRespCenter);

  CompanyInfo.GET;
  SalesUserRespCenter := CompanyInfo."Responsibility Center";
  UserLocation := CompanyInfo."Location Code";
  IF UserSetup.GET(UserCode) AND (UserCode <> '') THEN
    IF UserSetup."Sales Resp. Ctr. Filter" <> '' THEN
      SalesUserRespCenter := UserSetup."Sales Resp. Ctr. Filter";
  OnAfterGetSalesFilter2(UserSetup,SalesUserRespCenter);
  HasGotSalesUserSetup := TRUE;
END;
EXIT(SalesUserRespCenter);

**Comment by AlexanderYakunin** [comment]
Please close this issue if this works for you or let me know why it does not work.
