### ISSUE TITLE
[Event Request] Codeunit 12 "Gen. Jnl.-Post Line" - OnApplyVendLedgEntryOnBeforeCopyFromCVLedgEntryBuffer

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#26850]
### Describe the request

Hello, can you please add a new Event OnApplyVendLedgEntryOnBeforeCopyFromCVLedgEntryBuffer in Codeunit 12 "Gen. Jnl.-Post Line"?

```
    procedure ApplyVendLedgEntry(var NewCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; var DtldCVLedgEntryBuf: Record "Detailed CV Ledg. Entry Buffer"; GenJnlLine: Record "Gen. Journal Line"; Vend: Record Vendor)
.
.
.
            // Update the Old Entry
            OnApplyVendLedgEntryOnBeforeCopyFromCVLedgEntryBuffer(OldCVLedgEntryBuf, AppliedAmount, GenJnlLine);
            TempOldVendLedgEntry.CopyFromCVLedgEntryBuffer(OldCVLedgEntryBuf);
            OldVendLedgEntry := TempOldVendLedgEntry;
            if GenJnlLine."On Hold" = OldVendLedgEntry."On Hold" then
                OldVendLedgEntry."On Hold" := '';
            OldVendLedgEntry."Amount to Apply" := OldCVLedgEntryBuf."Amount to Apply";
            if OldVendLedgEntry."Amount to Apply" = 0 then
                OldVendLedgEntry."Applies-to ID" := ''
            else begin
                TempVendorLedgerEntry := OldVendLedgEntry;
                if TempVendorLedgerEntry.Insert() then;
            end;
            OnApplyVendLedgEntryOnBeforeOldVendLedgEntryModify(GenJnlLine, OldVendLedgEntry, NewCVLedgEntryBuf, AppliedAmount);
            OldVendLedgEntry.Modify();
```

```
    [IntegrationEvent(false, false)]
    local procedure OnApplyVendLedgEntryOnBeforeCopyFromCVLedgEntryBuffer(var OldCVLedgEntryBuf: Record "CV Ledger Entry Buffer"; AppliedAmount: Decimal; GenJournalLine: Record "Gen. Journal Line")
    begin
    end;
```

### Additional context

In some cases we???d like to modify some fields in the old C/V Ledger Entry with values from the GenJournalLine.
Internal work item: [AB#542075](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542075)

**Comment by AndersLarsenMicrosoft** [comment]
It looks like the existing event will meet your need 


            // Update the Old Entry
            TempOldVendLedgEntry.CopyFromCVLedgEntryBuffer(OldCVLedgEntryBuf);
            OldVendLedgEntry := TempOldVendLedgEntry;
            if GenJnlLine."On Hold" = OldVendLedgEntry."On Hold" then
                OldVendLedgEntry."On Hold" := '';
            OldVendLedgEntry."Amount to Apply" := OldCVLedgEntryBuf."Amount to Apply";
            if OldVendLedgEntry."Amount to Apply" = 0 then
                OldVendLedgEntry."Applies-to ID" := ''
            else begin
                TempVendorLedgerEntry := OldVendLedgEntry;
                if TempVendorLedgerEntry.Insert() then;
            end;
            OnApplyVendLedgEntryOnBeforeOldVendLedgEntryModify(GenJnlLine, OldVendLedgEntry, NewCVLedgEntryBuf, AppliedAmount);
