### ISSUE TITLE
[Event Request] Report 99000756 Detailed Calculation - trigger OnInitReport - OnBeforeOnInitReport

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26868]
### Describe the request

Please add the following Event/-s OnBeforeOnInitReport to trigger OnInitReport in Report 99000756 Detailed Calculation.

```
[Event Request] Report 99000756 Detailed Calculation - trigger OnInitReport
trigger OnInitReport()
begin

    OnBeforeOnInitReport(Item); // <-- NEW EVENT

    MfgSetup.Get();
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeOnInitReport(Item: Record Item)
begin
end;
```

### Additional context

We need a possibility to stop executing the report before processing
Internal work item: [AB#542276](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542276)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22007.
