### ISSUE TITLE
[Event Request] Codeunit 414 (Release Sales Document) - OnBeforeTestSalesPrepayment

### ISSUE THREAD

**Issue by MattiLE** [microsoft/ALAppExtensions#2686]
Hi AL-Team,
we need a new event in Codeunit 414 to perform our own TestSalesPrepayment and not leave the function "code" afterwards. 

`LOCAL Code() LinesWereModified : Boolean
...
  IsHandled := FALSE;
  OnBeforeModifySalesDoc(SalesHeader,PreviewMode,IsHandled);
  IF IsHandled THEN
    EXIT;

  // >> NEW
  IsHandled := FALSE;
  OnBeforeTestSalesPrepayment(SalesHeader,PreviewMode,IsHandled);
  IF NOT IsHandled THEN BEGIN
  // << NEW
    IF PrepaymentMgt.TestSalesPrepayment(SalesHeader) AND ("Document Type" = "Document 
    Type"::Order) THEN BEGIN
      Status := Status::"Pending Prepayment";
      MODIFY(TRUE);
      OnAfterReleaseSalesDoc(SalesHeader,PreviewMode,LinesWereModified);
      EXIT;
    END;
    Status := Status::Released;
  // >> NEW
  END;
  // >> NEW
...`

**Comment by AlexanderYakunin** [comment]
You already have event in PrepaymentMgt.:
[External] TestSalesPrepayment(SalesHeader : Record "Sales Header") : Boolean
IsHandled := FALSE;
OnBeforeTestSalesPrepayment(SalesHeader,TestResult,IsHandled);
IF IsHandled THEN
  EXIT(TestResult);

SalesLine.SETRANGE("Document Type",SalesHeader."Document Type");
SalesLine.SETRANGE("Document No.",SalesHeader."No.");
SalesLine.SETFILTER("Prepmt. Line Amount",'<>%1',0);
IF SalesLine.FINDSET THEN
  REPEAT
    IF SalesLine."Prepmt. Amt. Inv." <> SalesLine."Prepmt. Line Amount" THEN
      EXIT(TRUE);
  UNTIL SalesLine.NEXT = 0;

**Comment by AlexanderYakunin** [comment]
Please us this one
