### ISSUE TITLE
[Event Request] Report 99000754 Rolled-up Cost Shares - trigger OnPreReport  - OnBeforeOnPreReport

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26871]
### Describe the request

Please add the following Event/-s OnBeforeOnPreReport to trigger OnPreReport in Report 99000754 Rolled-up Cost Shares.

```
[Event Request] Report 99000754 Rolled-up Cost Shares - trigger OnPreReport 
trigger OnPreReport() // <-- NEW TRIGGER
begin

    OnBeforeOnPreReport(Item); // <-- NEW EVENT

    CalculateDate := WorkDate();
end;
```

```
[IntegrationEvent(false, false)]
local procedure OnBeforeOnPreReport(Item: Record Item)
begin
end;
```

### Additional context

We need a possibility to stop executing the report before processing
Internal work item: [AB#542267](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542267)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22007.
