### ISSUE TITLE
[Event Request] Report 299 Delete Invoiced Sales Orders - trigger dataitem - OnBeforeFirstSalesOrderLineFind

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26874]
### Describe the request

Please add the following Event/-s OnBeforeFirstSalesOrderLineFind to dataitem in Report 299 Delete Invoiced Sales Orders.

```
        dataitem("Sales Header"; "Sales Header")
        {
            DataItemTableView = sorting("Document Type", "No.") where("Document Type" = const(Order));
            RequestFilterFields = "No.", "Sell-to Customer No.", "Bill-to Customer No.";
            RequestFilterHeading = 'Sales Order';

            trigger OnAfterGetRecord()
            var
                ATOLink: Record "Assemble-to-Order Link";
                SalesLineReserve: Codeunit "Sales Line-Reserve";
                ApprovalsMgmt: Codeunit "Approvals Mgmt.";
                PostSalesDelete: Codeunit "PostSales-Delete";
                IsHandled: Boolean;
            begin
                IsHandled := false;
                OnBeforeSalesHeaderOnAfterGetRecord("Sales Header", IsHandled);
                if IsHandled then
                    CurrReport.Skip();

                if GuiAllowed() then
                    Window.Update(1, "No.");

                AllLinesDeleted := true;
                ItemChargeAssgntSales.Reset();
                ItemChargeAssgntSales.SetRange("Document Type", "Document Type");
                ItemChargeAssgntSales.SetRange("Document No.", "No.");
                SalesOrderLine.Reset();
                SalesOrderLine.SetRange("Document Type", "Document Type");
                SalesOrderLine.SetRange("Document No.", "No.");
                SalesOrderLine.SetFilter("Quantity Invoiced", '<>0');
                // new
                IsHandled := false;
                OnBeforeFirstSalesOrderLineFind(SalesOrderLine,IsHandled);
                IF not IsHandled then
                // new
                if SalesOrderLine.Find('-') then begin
```

```
 [IntegrationEvent(true, false)]
 local procedure OnBeforeFirstSalesOrderLineFind(var SalesOrderLine : Record "Sales Line"; var IsHandled : Boolean)
    begin
    end;
```

### Additional context

Add an additional Filter and skip the search in some situations.
Internal work item: [AB#542165](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542165)

**Comment by JakovljevicDusan** [comment]
Hi @MH1612,

It seems that this event does not bring much value. Please use OnBeforeSalesHeaderOnAfterGetRecord instead (it will have Progress dialog window as additional variable).

**Comment by SKeiler** [comment]
Hi @JakovljevicDusan ,

we want to change the filters set on Sales Line. For that we need that event. If we would use OnBeforeSalesHeaderOnAfterGetRecord, we would have to copy the whole report (only to add one filter). 

The similar reports to REP299 (for example REP499) did have exactly such an event after Quantity Invoiced is filtert.

**Comment by JakovljevicDusan** [comment]
Hi @SKeiler ,
Ok, clear. I will only change IsHandled to SkipLine or something like that.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22007.
