### ISSUE TITLE
[Request for External] REP299 "Delete Invoiced Sales Orders" - Protected variables

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26878]
### Describe the request

Hello, we need the following currently global variable/-s to be set as protected. Can you please check this? Thank you!

```
[Request for External] REP299 "Delete Invoiced Sales Orders" - Protected variables

protected var 
        Window: Dialog;
```	

### Additional context

Close the Window on Post Report (it's missing in the report)
Internal work item: [AB#542169](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542169)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22016.
