### ISSUE TITLE
[Request for External] REP6651 "Delete Invd Sales Ret. Orders" - Protected variables

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26879]
### Describe the request

Hello, we need the following currently global variable/-s to be set as protected. Can you please check this? Thank you!

```
protected var 
  Window
```	

### Additional context

Close the window in OnPostReport (It's missing in BaseApp)
Internal work item: [AB#542171](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542171)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22016.
