### ISSUE TITLE
[Event Change Request] codeunit 1255 "Match Bank Payments"

### ISSUE THREAD

**Issue by Halilovast** [microsoft/ALAppExtensions#26880]
### Describe the request

Please, can you change the parameters to be by reference

old code:

    [IntegrationEvent(false, false)]
    local procedure OnFindBankAccLedgerEntryForTextToAccountMapping(Handled: Boolean; Found: Boolean; var BankAccLedgerEntry: Record "Bank Account Ledger Entry"; BankAccReconciliationLine: Record "Bank Acc. Reconciliation Line"; TextToAccountMapping: Record "Text-to-Account Mapping"; BalAccountNo: Code[20])
    begin
    end;

new code:

    [IntegrationEvent(false, false)]
    local procedure OnFindBankAccLedgerEntryForTextToAccountMapping(var Handled: Boolean; var Found: Boolean; var BankAccLedgerEntry: Record "Bank Account Ledger Entry"; BankAccReconciliationLine: Record "Bank Acc. Reconciliation Line"; TextToAccountMapping: Record "Text-to-Account Mapping"; BalAccountNo: Code[20])
    begin
    end;

### Additional context

parameters are unusable without a reference
Internal work item: [AB#542409](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542409)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22993.
