### ISSUE TITLE
[Request for External] Page 193 "Incoming Doc. Attach. FactBox" - Protected variables

### ISSUE THREAD

**Issue by iamcgomes** [microsoft/ALAppExtensions#26887]
### Describe the request

Could you please change the scope of the global variables **"MainRecordRef"**, **"GlobalRecordID"**, **"GlobalDocumentNo"** and  **"GlobalPostingDate"** to protected in **Page 193 "Incoming Doc. Attach. FactBox"**?

Current
```AL
var
    MainRecordRef: RecordRef;
    GlobalRecordID: RecordID;
    GlobalDocumentNo: text;
    GlobalPostingDate: Date;
```

Requested
```AL
protected var
    MainRecordRef: RecordRef;
    GlobalRecordID: RecordID;
    GlobalDocumentNo: text;
    GlobalPostingDate: Date;
```

### Additional context

We need to access the global variables "MainRecordRef", "GlobalRecordID", "GlobalDocumentNo" and "GlobalPostingDate" from the Page Extension.
Internal work item: [AB#542413](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542413)

**Comment by Groenbech96** [comment]
Instead, can you have the same variables (different names obviously), only for your page extension?

**Comment by iamcgomes** [comment]
Hi @Groenbech96 

I considered that, but it is not possible to keep standard behavior for all variables. For example, variables "GlobalDocumentNo" and "GlobalPostingDate" are initialized in the procedure "LoadDataFromOnFindRecord" and this procedure is called in the trigger "OnFindRecord". 
Currently it's not possible extend the trigger "OnFindRecord" in a PageExtension.

However, this request was to allow the development of a feature to import multiple files. This feature was recently announced for the BC25: https://learn.microsoft.com/en-us/dynamics365/release-plan/2024wave2/smb/dynamics365-business-central/use-drag-drop-attach-multiple-files

So, if you want, you can close this request for now.

**Comment by Groenbech96** [comment]
Right, then it definitely makes sense to stop this request. Will close as non planned.
