### ISSUE TITLE
[Event Request] COD487 Job Queue Start Report - Procedure ProcessPrint - OnAfterProcessPrint

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26881]
### Describe the request

Please add the following Event/-s OnAfterProcessPrint to Procedure ProcessPrint in COD487 Job Queue Start Report.

```
[Event Request] COD487 Job Queue Start Report - Procedure ProcessPrint
    local procedure ProcessPrint(ReportID: Integer; var JobQueueEntry: Record "Job Queue Entry"; RunOnRec: Boolean; var RecRef: RecordRef)
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeProcessPrint(ReportID, JobQueueEntry, IsHandled);
        if IsHandled then
            exit;

        if RunOnRec then
            REPORT.Print(ReportID, JobQueueEntry.GetReportParameters(), JobQueueEntry."Printer Name", RecRef)
        else
            REPORT.Print(ReportID, JobQueueEntry.GetReportParameters(), JobQueueEntry."Printer Name");
  
  // New
  OnAfterProcessPrint(ReportId, JobQueueEntry,RunOnRec);
  // New  

  end;
```

```
 [IntegrationEvent(false, false)]
 local procedure OnAfterProcessPrint(ReportID: Integer; var JobQueueEntry: Record "Job Queue Entry"; RunOnRec: Boolean)
    begin
    end;
```

### Additional context

Start the Print of additional reports
Internal work item: [AB#542410](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542410)

**Comment by Groenbech96** [comment]
This function is only printing one function. 
Cant you solve this somehow else?

**Comment by SKeiler** [comment]
Hi @Groenbech96,

we want to optionally print copies of report in this event. The alternative is to use OnBeforeProcessPrint and use the IsHandled-Event and copy the whole procedure, but I would prefer to use the standard source code and have the possibility to optionally add a secord run.

**Comment by Groenbech96** [comment]
Can you run the codeunit multiple times instead do do multiple prints?

**Comment by SKeiler** [comment]
Would be a possiblity if the main procedure ProcessPrint is set to global. Currently this procedure is global. Also I would need more parameters in the OnRunReportOnAfterProcessDifferentReportOutputTypes-Event. 

I think a new event (which is part of the styleguide that a procedure should have a OnPre/OnPost-Event) is easier for all of us :-)

**Comment by Groenbech96** [comment]
I agree. This event serves a clear purpose, and does not violate the logic.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25608.
