### ISSUE TITLE
[Event Request] Report 7318 Whse.-Shipment - Create Pick

### ISSUE THREAD

**Issue by agszuf** [microsoft/ALAppExtensions#26885]
### Describe the request

Hi AL-Team,

Due to customer customization, we need one extra parameter in publisher in report 7318  (Whse.-Shipment - Create Pick).

Function: SetWhseShipmentLine

Current code:
 OnAfterSetWhseShipmentLine(WhseShptLine, WhseShptHeader, SortingMethod);

Requested code:
 OnAfterSetWhseShipmentLine(WhseShptLine, WhseShptHeader, SortingMethod, AssignedID);

Current Publisher signature:     [IntegrationEvent(false, false)]
    local procedure OnAfterSetWhseShipmentLine(WhseShptLine: Record "Warehouse Shipment Line"; WhseShptHeader: Record "Warehouse Shipment Header"; var SortActivity: Option)

Requested Publisher signature:     [IntegrationEvent(false, false)]
   local procedure OnAfterSetWhseShipmentLine(WhseShptLine: Record "Warehouse Shipment Line"; WhseShptHeader: Record "Warehouse Shipment Header"; var SortActivity: Option; var AssignedID: Code[50])

### Additional context

We need to update AssignedID as a part of customization
Internal work item: [AB#542412](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542412)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22165.
