### ISSUE TITLE
Event Request- Codeunit  6520 Item Tracing Mgt.

### ISSUE THREAD

**Issue by gopubala** [microsoft/ALAppExtensions#26899]
### Describe the request

Need to allow  custom code in function FindRecords()
could you please add the New Event with parameter (TempTrackEntry,Direction,ShowComponents) to allow custom tracking 
![image](https://github.com/user-attachments/assets/4299f91e-5345-43b6-ba31-33f7fe130265)

### Additional context

![image](https://github.com/user-attachments/assets/788d74a7-d7d0-498f-84bd-ac51f60ace3a)

Internal work item: [AB#542661](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542661)

**Comment by gopubala** [comment]
we want to allow custom tracking, could you please add new event.
[IntegrationEvent(false, false)]
local procedure OnAfterFindRecords(var TempTrackEntry : Record "Item Tracing Buffer";Direction : 'backward';ShowComponents : 'No,Item-tracked only,All')
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23752.
