### ISSUE TITLE
Questions regarding Issue #24690

### ISSUE THREAD

**Issue by DBiernat** [microsoft/ALAppExtensions#26895]
### Describe the request

Follow Up questions regarding Issue #24690.

### Additional context

Is there a timeframe available, in which the Issue #24690 will be implemented into the system? There is currently no Build ID assigned to the Issue. Also I would like to know how the current solution looks like.

**Comment by darjoo** [comment]
From what I checked, it recently went in, a month ago. There is no plan for backport, as such it's going to be available in the next major, v25.
