### ISSUE TITLE
Event Request - Codeunit 99000757 Update Prod. Order Cost 

### ISSUE THREAD

**Issue by gopubala** [microsoft/ALAppExtensions#26896]
### Describe the request

Could you please allow to the custom code in function ModifySourceLineCost()

please add  the Event publisher to allow code
![image](https://github.com/user-attachments/assets/1e39bed9-6892-4acf-a267-3ddc71d796f6)

### Additional context

add the event 
![image](https://github.com/user-attachments/assets/86d28527-00f6-4ee6-8a20-2c76f25fca2d)

Internal work item: [AB#542652](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542652)

**Comment by AleksandricMarko** [comment]
Hello @gopubala 

Please define structure of the event (parameters, using VAR, etc...)
Also if you can give us some short explanation what is the purpose of the desired event

**Comment by gopubala** [comment]
The purpose of the event is customer wants to insert "Prod. Order Line" data in Custom table.
[IntegrationEvent(false, false)]
local procedure OnAfterModifySourceLineCost(ReservEntry: Record "Reservation Entry";ProdOrderLine: Record "Prod. Order Line";)
begin
end;

**Comment by AleksandricMarko** [comment]
Hello @gopubala 
Procedure ModifySourceLineCost is under the construction (code is going to be divided into different procedures) so we can`t add events currently. Please check new structure (when it is available) and if you still need new event, please create request again
