### ISSUE TITLE
[Event request] Job Queue Entry - Bypass replacing Report Output Type (IsSaas / Print)

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26891]
### Describe the request

In SaaS, when creating a job queue entry and specifying the report output type to '**Print**', the report output type is not accepted and reset to **PDF** each time, accompanied by a message '_You cannot select a printer from this online product. Instead, save as PDF, or another format, which you can print later._'

As we're using PrintNode for printing in SaaS, job queue **should** be able to **print** reports instead of using PDF.

Currently, we have cumbersome workaround to enforce report output type to be set to Print, but we'd like the base app to allow to bypass the PDF replacement.

![image](https://github.com/user-attachments/assets/924d6820-646f-40f1-a5e2-03a1d720619b)

Possible solution:

Replace above code by:

```
if EnvironmentInfo.IsSaaS() then begin
    ShowPrintNotAllowedInSaaS()
end else
```

and add a function with publisher to bypass the code.

```
local procedure ShowPrintNotAllowedInSaaS()
    var
        IsHandled: Boolean;
    begin
        OnBeforeShowPrintNotAllowedInSaaS(IsHandled);
        if IsHandled then
            exit;
        
        "Report Output Type" := "Report Output Type"::PDF;
        Message(NoPrintOnSaaSMsg);
    end;

    [IntegrationEvent(false, false)]
    local procedure OnBeforeShowPrintNotAllowedInSaaS(var IsHandled: Boolean)
    begin
    end;
```

### Additional context

x
Internal work item: [AB#542561](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542561)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22249.
