### ISSUE TITLE
Event Request- Codeunit 7312 Create Pick

### ISSUE THREAD

**Issue by gopubala** [microsoft/ALAppExtensions#26898]
### Describe the request

we want to skip the the condition in function CreateTempLine().

could you please add the event  OnBeforePickAccordingToFEFO() with  required parameter to allow the code  line NO 142 to 146.
![image](https://github.com/user-attachments/assets/8d08adfb-998d-4822-91e4-a00343d3fdfa)

 

### Additional context

need to allow below custom code
![image](https://github.com/user-attachments/assets/e533e905-34d2-46b6-9736-e6fe046c4e12)

Internal work item: [AB#542657](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542657)

**Comment by AleksandricMarko** [comment]
Hello @gopubala 
You already have an event OnAfterPickAccordingToFEFO (procedure PickAccordingToFEFO) which you can use for the mentioned purpose
