### ISSUE TITLE
Event Request -Codeunit 99000854 Inventory Profile Offsetting

### ISSUE THREAD

**Issue by gopubala** [microsoft/ALAppExtensions#26897]
### Describe the request

not able to write the Custom code in function  TransRcptTransLineToProfile()

could you please provide the OnAfterEvent() with  parameter  InventoryProfile & TransferLine

![image](https://github.com/user-attachments/assets/b8318620-9315-48c4-b44d-3d58a7ad7e1d)

### Additional context

please  provide the  AfterEvent() inside Repeat until
Internal work item: [AB#542658](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542658)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22249.
