### ISSUE TITLE
[Event Request] codeunit 950 "Time Sheet Management" new event OnBeforeToTimeSheetLineInsertFromTimeSheetLineArchive

### ISSUE THREAD

**Issue by alexlang24** [microsoft/ALAppExtensions#26893]
### Describe the request

Please add a new event before inserting the time sheet line from time sheet line archive when copying time sheet lines:

`local procedure CopyTimeSheetLineArchive(ToTimeSheetHeader: Record "Time Sheet Header"; FromTimeSheetLineArchive: Record "Time Sheet Line Archive"; CopyComments: Boolean; var NextLineNo: Integer)`

     var
        ToTimeSheetLine: Record "Time Sheet Line";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeCopyTimeSheetLineArchive(ToTimeSheetHeader, FromTimeSheetLineArchive, CopyComments, NextLineNo, IsHandled);
        if not IsHandled then begin
            NextLineNo := NextLineNo + 10000;

            ToTimeSheetLine.Init();
            ToTimeSheetLine."Time Sheet No." := ToTimeSheetHeader."No.";
            ToTimeSheetLine."Line No." := NextLineNo;
            ToTimeSheetLine."Time Sheet Starting Date" := ToTimeSheetHeader."Starting Date";
            ToTimeSheetLine.Type := FromTimeSheetLineArchive.Type;
            case ToTimeSheetLine.Type of
                ToTimeSheetLine.Type::Job:
                    begin
                        ToTimeSheetLine.Validate("Job No.", FromTimeSheetLineArchive."Job No.");
                        ToTimeSheetLine.Validate("Job Task No.", FromTimeSheetLineArchive."Job Task No.");
                    end;
                ToTimeSheetLine.Type::Absence:
                    ToTimeSheetLine.Validate("Cause of Absence Code", FromTimeSheetLineArchive."Cause of Absence Code");
            end;
            ToTimeSheetLine.Description := FromTimeSheetLineArchive.Description;
            ToTimeSheetLine.Chargeable := FromTimeSheetLineArchive.Chargeable;
            ToTimeSheetLine."Work Type Code" := FromTimeSheetLineArchive."Work Type Code";
            // >> Event Request
            OnBeforeToTimeSheetLineInsertFromTimeSheetLineArchive(ToTimeSheetLine, FromTimeSheetLineArchive);
            // << Eevent Request
            ToTimeSheetLine.Insert();

            CopyTimeSheetLineArchiveDetails(ToTimeSheetLine, FromTimeSheetLineArchive);

            if CopyComments then
                CopyTimeSheetLineArchiveComments(ToTimeSheetLine, FromTimeSheetLineArchive);
        end;

`[IntegrationEvent(false, false)]`

```
local procedure OnBeforeToTimeSheetLineInsertFromTimeSheetLineArchive(var ToTimeSheetLine: Record "Time Sheet Line"; FromTimeSheetLineArchive: Record "Time Sheet Line Archive")
    begin
    end;
```

### Additional context

The same kind of event is available for copying time sheet lines which are not archived. We need to add our product individual fields on that, too.
Internal work item: [AB#542560](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542560)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22165.
