### ISSUE TITLE
[EventRequest] Table 1294 "Applied Payment Entry" - OnAfterFilterEntryAppliedToOtherStmtLines

### ISSUE THREAD

**Issue by vladsandortnp** [microsoft/ALAppExtensions#26904]
### Describe the request

Can you please add event OnAfterFilterEntryAppliedToOtherStmtLines in procedure FilterEntryAppliedToOtherStmtLines

Event Publisher would be

`    [IntegrationEvent(false, false)]
    local procedure OnAfterFilterEntryAppliedToOtherStmtLines(var AppliedPaymentEntry: Record "Applied Payment Entry")
    begin
    end;
`

The procedure would look like:

`    procedure FilterEntryAppliedToOtherStmtLines()
    begin
        Reset();
        SetRange("Statement Type", "Statement Type");
        SetRange("Bank Account No.", "Bank Account No.");
        SetRange("Statement No.", "Statement No.");
        SetFilter("Statement Line No.", '<>%1', "Statement Line No.");
        SetRange("Account Type", "Account Type");
        SetRange("Account No.", "Account No.");
        SetRange("Applies-to Entry No.", "Applies-to Entry No.");
        OnAfterFilterEntryAppliedToOtherStmtLines(Rec);
    end;`

### Additional context

We want to be able to apply additional filters to the record
Internal work item: [AB#542664](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542664)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22786.
