### ISSUE TITLE
[EventRequest] Table 1294 "Applied Payment Entry" - OnBeforeCheckCurrentMatchesExistingAppln

### ISSUE THREAD

**Issue by vladsandortnp** [microsoft/ALAppExtensions#26903]
### Describe the request

Can you please add event OnBeforeCheckCurrentMatchesExistingAppln in procedure CheckCurrentMatchesExistingAppln

Event Publisher would be
`[IntegrationEvent(false, false)]
    local procedure OnBeforeCheckCurrentMatchesExistingAppln(ExistingAppliedPmtEntry: Record "Applied Payment Entry"; var IsHandled: Boolean)
    begin
    end;`

The procedure would look like:

` local procedure CheckCurrentMatchesExistingAppln(ExistingAppliedPmtEntry: Record "Applied Payment Entry")
    var
        IsHandled: Boolean;
    begin
        OnBeforeCheckCurrentMatchesExistingAppln(ExistingAppliedPmtEntry, IsHandled);
        if IsHandled then
            exit;
`       
     if ("Account Type" = ExistingAppliedPmtEntry."Account Type") and
           ("Account No." = ExistingAppliedPmtEntry."Account No.")
        then
            exit;

        Error(
          CannotApplyStmtLineErr,
          "Account Type", "Account No.",
          ExistingAppliedPmtEntry."Account Type",
          ExistingAppliedPmtEntry."Account No.");
    end;`

### Additional context

We would like to skip the error check for particular account types and specific conditions
Internal work item: [AB#542666](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542666)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 22777.
