### ISSUE TITLE
[EventRequest] Codeunit 90 "Purch.-Post" - OnBeforeTestPostingDate

### ISSUE THREAD

**Issue by vladsandortnp** [microsoft/ALAppExtensions#26908]
### Describe the request

Can you please add event OnBeforeTestPostingDate in procedure ValidatePostingAndDocumentDate

Event Publisher would be:

` [IntegrationEvent(false, false)]
    local procedure OnBeforeTestPostingDate(PurchaseHeader: Record "Purchase Header"; PostingDateExists: Boolean; var SkipTestPostingDate: Boolean)
    begin
    end;
`

The procedure would look like:

` local procedure ValidatePostingAndDocumentDate(var PurchaseHeader: Record "Purchase Header")
    var
        SkipTestPostingDate: Boolean;
    begin
        .....
        .....

        if not ReplacePostingDate then begin
            OnBeforeTestPostingDate(PurchaseHeader, PostingDateExists, SkipTestPostingDate);
            if not SkipTestPostingDate then
                PurchaseHeader.TestPostingDate(PostingDateExists);
        end;
        ......
        ......
        
    end;`

### Additional context

We would like to skip the test of posting date in some specific posting routines and cases. We need an event in the posting codeunit because we will not be able to subscribe to the table function as it is marked OnPrem.
Internal work item: [AB#542671](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542671)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22249.
