### ISSUE TITLE
Event Request - Codeunit  5813 Undo Purchase Receipt Line

### ISSUE THREAD

**Issue by gopubala** [microsoft/ALAppExtensions#26900]
### Describe the request

Could you please add the extra parameter TempWhseJnlLine  for this Event OnBeforePostItemJnlLine() to allow custom Code.
![image](https://github.com/user-attachments/assets/1ee878dc-bf99-4342-bc6a-84c553e42475)
 

### Additional context

Please add the new parameter
```[tasklist]
### Tasks
```

Internal work item: [AB#542662](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542662)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22249.
