### ISSUE TITLE
Event Request Code unit 12 Gen. Jnl.-Post Line

### ISSUE THREAD

**Issue by gopubala** [microsoft/ALAppExtensions#26914]
### Describe the request

Hello, in Code unit 12 "Gen. Jnl.-Post Line" in procedure "PostBankAcc()", we need a new event with Ishandled
customer want to add more conditions
![image](https://github.com/user-attachments/assets/a621ba23-b18b-4966-97ac-3a5026c32ef3)

Need new Event in Porcedure CalcPmtDisc() to allow custom code, customer want town condition PmtDisc
![image](https://github.com/user-attachments/assets/bbce66d3-0608-40df-b73f-ba329e6ba6e6)

### Additional context

Please provide the new events
Internal work item: [AB#542667](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542667)

**Comment by gopubala** [comment]
1. The purpose of the event is customer wants to add more conditions to allow in function PostBankAcc().
could you please add more parameters  IsHandled  OnPostBankAccOnAfterBankAccLedgEntryInsert()
[IntegrationEvent(false, false)]
local procedure OnPostBankAccOnAfterBankAccLedgEntryInsert(var BankAccountLedgerEntry: Record "Bank Account Ledger Entry"; var GenJournalLine: Record "Gen. Journal Line"; BankAccount: Record "Bank Account"; IsHandled : boolean)
begin
end;

skip only case "Bank Payment Type" of
  end;


2.

**Comment by mildddd** [comment]
Hello @gopubala,

Could you please elaborate your requests and send us the explanation how you will implement them?

**Comment by mildddd** [comment]
Hi @gopubala,

If you still require the events, kindly submit a new request with additional details.

Best regards,
Milica
