### ISSUE TITLE
[Bug]: Budget (113) SaveValues page property

### ISSUE THREAD

**Issue by BergantINC** [microsoft/ALAppExtensions#26913]
### Describe the issue

The page Budget (113) had the property SaveValues set to true until BC19, then it disappeared. I tried to find a reason as to why that happened, but i couldn't find anything, there is no documentation on this change.
Unfortunatly this can't be fixed with a page extension and the work neccesary to fix the lack of this property is quite big. I would appreciate if this property could be added back in a future update or at least if there is some reason as to why it was removed.

Thank you very much

### Expected behavior

The page Budget (113) has the property SaveValues set to **true**.

### Steps to reproduce

Open the page on a version that is newer than BC18.

### I will provide a fix for a bug

- [ ] I will provide a fix for a bug

**Comment by JesperSchulz** [comment]
Here's the reason why SaveValues was removed:

Merged PR: G/L budget dimensions filters are being pulled into a budget of a separate company

PROBLEM

Defined filters on page Budget are visible on same page in another company when user opens another company directly from Budget page even if same dimension filter does not exist on it.

CAUSE

"SaveValue" property is causing this situation.

SOLUTION

"SaveValue" property removed from page 113 Budget (suggested by Platform Team)
