### ISSUE TITLE
[Event Request] TAB472 Job Queue Entry - Procedure SetStatusValue - OnAfterSetStatusValue

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26916]
### Describe the request

Please add the following Event/-s OnAfterSetStatusValue to Procedure SetStatusValue in TAB472 Job Queue Entry.

```
[Event Request] TAB472 Job Queue Entry - Procedure SetStatusValue
    local procedure SetStatusValue(NewStatus: Option)
    var
        JobQueueDispatcher: Codeunit "Job Queue Dispatcher";
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeSetStatusValue(Rec, xRec, NewStatus, IsHandled);
        if IsHandled then
            exit;

        if NewStatus = Status then
            exit;
        case NewStatus of
            Status::Ready:
                begin
                    SetDefaultValues(false);
                    "Earliest Start Date/Time" := JobQueueDispatcher.CalcInitialRunTime(Rec, CurrentDateTime);
                    EnqueueTask();
                end;
            Status::"On Hold":
                CancelTask();
            Status::"On Hold with Inactivity Timeout":
                if "Inactivity Timeout Period" > 0 then begin
                    SetDefaultValues(false);
                    "Earliest Start Date/Time" := JobQueueDispatcher.CalcNextRunTimeHoldDuetoInactivityJob(Rec, CurrentDateTime);
                    EnqueueTask();
                end;
        end;
        Status := NewStatus;
        Modify();

       // NEW
       OnAfterSetStatusValue(Rec, xRec) 
       // NEW
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnAfterSetStatusValue(var JobQueueEntry: Record "Job Queue Entry"; var xJobQueueEntry: Record "Job Queue Entry")
    begin
    end;
```

### Additional context

Save a notification
Internal work item: [AB#542994](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542994)

**Comment by Groenbech96** [comment]
What about validate trigger for Status instead? 
If we add Rec.Validate(Status, NewStatus) ?

**Comment by SKeiler** [comment]
Hi @Groenbech96,

I'm not sure if a Status-Validate will have some other effects which will be more critical so the event will be the more uncritical. Otherwise it will be an option...

**Comment by SKeiler** [comment]
Hi @Groenbech96 ,

there are a lot of Modify-Actions on the Job Queue Entry. And I'm not sure if I have there the correct xRec (before the status set, not before the start of the Modify trigger). That sound's like an really instabil solution.

What's the reason why a simple event which fits with the standard rules (OnBefore and OnAfter a procedure) ?!

**Comment by Groenbech96** [comment]
At the time of modify this should be the exact same as the event would provide. 
Please try this in your solution. 

We dont want to introduce an event that could be done with existing design.

**Comment by SKeiler** [comment]
Hi @Groenbech96 ,

I was now able to test it. As suspected if I use the OnAfterModifyEvent I don't have access to the correct xRec-Value. In this case the Status of the xRec and the Rec are the same :-(

Is it now possible that the event is implemented?

**Comment by SKeiler** [comment]
Hi @Groenbech96,

we needed the modified job Queue Entry (include the executed Modify-Trigger) to provide the status message, include the old Status to send our type of notfication. 

If you want I can send our source code to you. Than you are able to think about a solution and tests (!) which fulfilled all of our requirements as in the requested very simple (!) event. Otherwise you have to believe me that we need the event at this point as requested and all of your suggestions costs a lot of time and money, but didn't bring a step into a solution...

@JesperSchulz : Could you here also support? The event request of a simple and unspectacular event costs a lot of time (and money for my company...) and we didn't any step into a solution...

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 25608.

**Comment by JesperSchulz** [comment]
@SKeiler, the event has been added as requested. Going forward you may experience a few more discussions though, as the rate in which we're adding redundant events is alarming. Rather often we find that existing events could have been used, if the developer had just looked one level down or 5 lines up/down the code. I am in no way saying that this was the case here, but you will find that developers will question events to a higher degree going forward.
We will update our documentation and issue templates in the coming weeks, just as you will see us hosting sessions on events etc. Hopefully it will all make sense to you then.
For this case though, the requested event was added, so all should be fine now.
