### ISSUE TITLE
Event Request Codeunit 80 sales Post

### ISSUE THREAD

**Issue by gopubala** [microsoft/ALAppExtensions#26911]
### Describe the request

Hello, in Codeunit 80 "Sales.-Post" in procedure "FinalizePosting", we need a new event with parameter SalesHeader,TempDropShptPostBuffer
![image](https://github.com/user-attachments/assets/df899d5a-4f9c-46c7-9483-f5c4cc4a9df9)

could you please add the parameter TempSalesLineForSalesTax  for this Event  OnAfterDivideAmount()
![image](https://github.com/user-attachments/assets/66dce949-73f1-4429-9d2b-178f5dbccb1a)

Another Event is Required under function AddSalesTaxLineToSalesTaxCalc() before insert to allow Custom code
Like OnBeforeAddSalesTaxLineToSalesTaxCalcinsert(salesheader ,salesLIne)
![image](https://github.com/user-attachments/assets/f4647e89-4b78-4fad-a7e3-3a16cb749822)

Need New event under function SetTaxType()
Like OnAfterSetTaxType(salesLine)
![image](https://github.com/user-attachments/assets/df9b99ad-0849-43e2-848c-400a45d5d7c4)

### Additional context

Please provide the New events
Internal work item: [AB#542672](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542672)

**Comment by AleksandricMarko** [comment]
Hello @gopubala 

Please define full structure of the needed events (parameters, using VAR, etc...) and also short explanation what is the purpose of the desired events.

**Comment by gopubala** [comment]
1. the purpose of the add parameter as TempSalesLineForSalesTax, we want to calculation for custom fields

[IntegrationEvent(false, false)]
local procedure OnAfterDivideAmount(var SalesHeader: Record "Sales Header"; var SalesLine: Record "Sales Line"; QtyType: 
         Option General,Invoicing,Shipping; SalesLineQty: Decimal; var TempVATAmountLine: Record "VAT Amount Line" 
         temporary; var TempVATAmountLineRemainder: Record "VAT Amount Line" temporary; TempSalesLineForSalesTax: Record "Sales Line")
begin
end;

2. Event is Required under function AddSalesTaxLineToSalesTaxCalc() before insert to allow Custom field data into temp table.
 [IntegrationEvent(false, false)]
local procedure OnBeforeTempSalesLineForSalesTaxInsert(SalesHeader : Record "Sales Header";SalesLine : Record "Sales Line")
begin
end;

3. Need New event under function SetTaxType()- we want to allow Sales Line data to buffer table.
Note:  Event is required before Salesline.Next() =0;
[IntegrationEvent(false, false)]
 local procedure OnAfterSetTaxType(SalesLine : Record "Sales Line")
begin
end;

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22697.
