### ISSUE TITLE
[Request-For-External] COD448 Job Queue Dispatcher - Procedure CalcRunTimeForRecurringJob

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26918]
### Describe the request

Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

```
procedure CalcRunTimeForRecurringJob(var JobQueueEntry: Record "Job Queue Entry"; StartingDateTime: DateTime) NewRunDateTime: DateTime
```	

### Additional context

Call it out of an Event from COD448
Internal work item: [AB#542997](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542997)

**Comment by Groenbech96** [comment]
What is the scenario you are trying to make work? 
I would need more information.

**Comment by SKeiler** [comment]
Hi @Groenbech96,

we did serveral changes on the CalcNextRunTimeForRecurringJob-procedure and used the IsNextRecurringRunTimeCalculated/OnBeforeCalcNextRunTimeForRecurringJob-event for that with a is Handled (especially to calc the next run time). But at the end we need the CalcRunTimeForRecurringJob-procedure to plan the next execution date. 

There is currently a workaround to use the CalcNextRunTimeHoldDuetoInactivityJob-Procedure (with a Inactivity-Period auf zero minutes). But it would be better to directly use the CalcRunTimeForRecurringJob-Procedure. I think there is no reason why this procedures should be called from outside...

**Comment by Groenbech96** [comment]
We wont make this function public. I would suggest you to just copy the source to solve your issue.

**Comment by SKeiler** [comment]
Hi @Groenbech96 ,

could you tell me the reason? Why shoud we xopy the whole procedure instead of making it global? 

@JesperSchulz Could you please mediate the problem?!
