### ISSUE TITLE
Event Request Codeunit 5805 Item Charge Assgnt. (Purch.)

### ISSUE THREAD

**Issue by gopubala** [microsoft/ALAppExtensions#26923]
### Describe the request

The purpose of event is customer want to skip the standard code & allow to custom code under function CreateDocChargeAssgnt()

can you add the IsHandled() as parameter

 [IntegrationEvent(false, false)]
  local procedure OnBeforeCreateDocChargeAssgn(var LastItemChargeAssgntPurch: Record "Item Charge Assignment (Purch)"; var FromPurchLine: Record "Purchase Line"; isHandled: boolean)
    begin
    end;

if IsHandled then
exit;

![image](https://github.com/user-attachments/assets/fe96129b-7cff-40a8-850f-fd23a12100c7)

### Additional context

Please provide the ishandled parameter
Internal work item: [AB#543003](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543003)

**Comment by JakovljevicDusan** [comment]
Already implemented with #26902
