### ISSUE TITLE
New events in codeunit 132 "Release Incoming Document"

### ISSUE THREAD

**Issue by iCutura** [microsoft/ALAppExtensions#26921]
### Describe the request

Add same events that codeunit 414 "Release Sales Document" has to codeunit 132 "Release Incoming Document"

### Additional context

For example there is no way to implement our own Incoming Document Release logic. We need something like this:

        IsHandled := false;
        OnBeforeReleaseIncomingDoc(IncomingDocument, PreviewMode, IsHandled, SkipCheckReleaseRestrictions);
        if IsHandled then
            exit;
            
            
    [IntegrationEvent(false, false)]
    local procedure OnBeforeReleaseIncomingDoc(var IncomingDocument: Record "Incoming Document"; PreviewMode: Boolean; var IsHandled: Boolean; var SkipCheckReleaseRestrictions: Boolean)
    begin
    end;
Internal work item: [AB#542995](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/542995)

**Comment by Groenbech96** [comment]
I need more information about what logic you need to override?

**Comment by iCutura** [comment]
We have some custom solution that extends Incoming Documents.

For example one of the features is to allow Incoming Documents without attachments:

This was our NAV code:

// <SP.463>
IncomingDocumentsSetup.Get();
if not IncomingDocumentsSetup."ReleaseWithoutAttachmentIdrBET" then
    // </SP.463>
    if not Rec.IsADocumentAttached() then
        ERROR(NothingToReleaseErr, Rec."Entry No.");


This is the code on BC:

if not Rec.IsADocumentAttached() then
    Error(NothingToReleaseErr, Rec."Entry No.");

There is no way to bypass this error. Also one of the other features is some custom approval workflows but I guess we can do that through OnCheckIncomingDocReleaseRestrictions.

**Comment by Groenbech96** [comment]
We wont introduce this as it violates the design. 
I can see that design is that something should be in URL, in that case the check for document attachments are disregarded.

Let me know if you can get that to work.

**Comment by iCutura** [comment]
Hello,

The main issue is because of this. We have custom release actions on page, but the problem is with workflow. There is an action in the workflow that changes document status to released when document is approved. It calls Microsoft action to Release the document.

I'll try to create custom workflow event that will call our release action.

But incoming document should have a lot more events. For example Sales Document release has 50 events. You can bypass everything and violate the design.

Incoming document has 3 events in release codeunit.
