### ISSUE TITLE
[Event Requests] Codeunit 398 "Sales Tax Calculate" - AddSalesLineOnAfterSetSalesTaxAmountLineFilter(), AddSalesLineOnBeforeModifySalesTaxAmountLine(), OnEndSalesTaxCalculationBeforeDeleteTaxAmountLine(), OnEndSalesTaxCalculationOnBeforeSalesTaxAmountLine2Copy() and OnDistTaxOverSalesLinesAfterSetSalesLineFilters()

### ISSUE THREAD

**Issue by Anirudh053** [microsoft/ALAppExtensions#26925]
### Describe the request

Hi Team,

In Codeunit 398 "Sales Tax Calculate", Please provide the possibility to have five integration events in AddSalesLine() and EndSalesTaxCalculation() and DistTaxOverSalesLines() procedures respectively.

In AddSalesLine() Procedure after 725 Line in Below image,

![image](https://github.com/user-attachments/assets/614a611b-f81f-4bb9-83b2-1fb8a1afe348)

![image](https://github.com/user-attachments/assets/6f705407-3f1b-4fa8-93bc-d28810fe10af)

Integration Event
    [IntegrationEvent(false, false)]
    local procedure AddSalesLineOnAfterSetSalesTaxAmountLineFilter(var TempSalesTaxAmountLine: Record "Sales Tax Amount Line" temporary; SalesLine: Record "Sales Line"; TaxAreaLine: Record "Tax Area Line");
    begin
    end;

In AddSalesLine() Procedure after 752 Line in Below image,

![image](https://github.com/user-attachments/assets/c965e725-60cb-4104-a7b5-268b0231ed4d)

![image](https://github.com/user-attachments/assets/f6050c1a-afde-42ee-94d6-ea19b38630ea)

Integration Event
    [IntegrationEvent(false, false)]
    local procedure AddSalesLineOnBeforeModifySalesTaxAmountLine(var TempSalesTaxAmountLine: Record "Sales Tax Amount Line" temporary; SalesLine: Record "Sales Line");
    begin
    end;
    
In Procedure EndSalesTaxCalculation() after 1159 Line in below image.

![image](https://github.com/user-attachments/assets/2d224621-e0a4-4d1f-8e14-23cbd35226b4)

![image](https://github.com/user-attachments/assets/37e71d3b-15b3-4539-acee-d24c032a2b38)

Integration Event
    [IntegrationEvent(false, false)]
    local procedure EndSalesTaxCalculationBeforeDeleteTaxAmountLine(var TempSalesTaxAmountLine: Record "Sales Tax Amount Line" temporary; Date: Date; var IsHandled: Boolean);
    begin
    end;

In Procedure EndSalesTaxCalculation() after 1255 Line in below image.

![image](https://github.com/user-attachments/assets/0bc1a7a1-b370-4ed4-8dc0-a774854dd60d)

![image](https://github.com/user-attachments/assets/d3efb47d-0027-4f20-9ead-53e59b9043ee)

Integration Event
    [IntegrationEvent(false, false)]
    local procedure OnEndSalesTaxCalculationOnBeforeSalesTaxAmountLine2Copy(var TempSalesTaxAmountLine: Record "Sales Tax Amount Line" temporary; var TaxBaseAmt: Decimal; var AddedTaxAmount: Decimal; var TotalTaxAmount: Decimal);
    begin
    end;
    
In Procedure DistTaxOverSalesLines() after 1462 Line in below image.

![image](https://github.com/user-attachments/assets/d9598e72-45a5-4001-84ee-83c432b791d2)

![image](https://github.com/user-attachments/assets/1e829e8a-0377-4ce3-9dad-95333b4c4b4a)

Integration Event
    [IntegrationEvent(false, false)]
    local procedure DistTaxOverSalesLinesAfterSetSalesLineFilters(var SalesLine: Record "Sales Line"; var TempSalesTaxAmountLine: Record "Sales Tax Amount Line" temporary);
    begin
    end;

### Additional context

We need these events to handle the custom code for various clients related to implementation of Excise Tax.
Internal work item: [AB#543002](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543002)

**Comment by Anirudh053** [comment]
Hi @haoranpb any update on this, please?

**Comment by mildddd** [comment]
Hello @Anirudh053 ,

Can you please explain event EndSalesTaxCalculationBeforeDeleteTaxAmountLine? Please, send the suggestion of the implementation in the procedure EndSalesTaxCalculation.
E.g. IsHandled is not used, but you want to have it in EndSalesTaxCalculationBeforeDeleteTaxAmountLine, can you please elaborate? Also, why the suggestion line 1159?

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 27069.

**Comment by Anirudh053** [comment]
> Hello [@Anirudh053](https://github.com/Anirudh053) ,
> 
> Can you please explain event EndSalesTaxCalculationBeforeDeleteTaxAmountLine? Please, send the suggestion of the implementation in the procedure EndSalesTaxCalculation. E.g. IsHandled is not used, but you want to have it in EndSalesTaxCalculationBeforeDeleteTaxAmountLine, can you please elaborate? Also, why the suggestion line 1159?

Sorry for the delay in response. We need IsHanlded there. I think I missed it
