### ISSUE TITLE
[Event request] codeunit 12184 Fattura Doc Helper: BuildSelfBillingDocPageSource procedure

### ISSUE THREAD

**Issue by 19sam88** [microsoft/ALAppExtensions#26939]
### Describe the request

Hello,
we would like to make a request for an event in codeunit 12184 for the function BuildSelfBillingDocPageSource.

    procedure BuildSelfBillingDocPageSource(var TempVATEntry: Record "VAT Entry" temporary; DateFilter: Text[30])
    var
        FatturaSetup: Record "Fattura Setup";
        VATEntry: Record "VAT Entry";
    begin
        FatturaSetup.VerifyAndSetData();
        TempVATEntry.Reset();
        TempVATEntry.DeleteAll();

        VATEntry.SetCurrentKey("Document No.", "Posting Date", "Unrealized VAT Entry No.");
        VATEntry.SetRange("VAT Bus. Posting Group", FatturaSetup."Self-Billing VAT Bus. Group");
        VATEntry.SetRange(Type, VATEntry.Type::Sale);
        VATEntry.SetRange("VAT Calculation Type", VATEntry."VAT Calculation Type"::"Reverse Charge VAT");
        VATEntry.SetFilter("Document Type", '%1|%2', VATEntry."Document Type"::Invoice, VATEntry."Document Type"::"Credit Memo");
        VATEntry.SetFilter("Posting Date", DateFilter);

  _add an event here to set or change other filters_
**onBeforeBuildVATEntryBufferWithLinks(TempVATEntry, VATEntry)**

        BuildVATEntryBufferWithLinks(TempVATEntry, VATEntry);
    end;

### Additional context

The scope is to let filter once all reverse charge VAT Business Groups.
Now the user must set in Fattura Setup every single posting group
Internal work item: [AB#543322](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543322)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24337.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 24351.
