### ISSUE TITLE
Event Request Page 99000914 Change Production Order Status

### ISSUE THREAD

**Issue by gopubala** [microsoft/ALAppExtensions#26934]
### Describe the request

The purpose of the Event is to allow custom code under function BuildPage()

 [IntegrationEvent(false, false)]
  local procedure OnBeforeBuildPagefilter(Rec: Record "Production Order")
    begin
    end;
![image](https://github.com/user-attachments/assets/9beb56f1-e5a4-42ac-9674-23552233713d)
 

### Additional context

Please provide the event
Internal work item: [AB#543329](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543329)

**Comment by Groenbech96** [comment]
So you want this event after Rec.FilterGroup(0)?

**Comment by gopubala** [comment]
Yes, please add after Rec.Filtergroup

**Comment by Groenbech96** [comment]
What other options do you have than this? 
Why do you need it after the filter group.

**Comment by Groenbech96** [comment]
Also. 
You can subscribe to the open page, and field validation triggers, to achieve the same.

**Comment by Groenbech96** [comment]
Feel free to reopen issue if needed.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
