### ISSUE TITLE
[Event Requests] Codeunit 12 "Gen. Jnl.-Post Line" - OnBeforeSkipFindTaxDetail()

### ISSUE THREAD

**Issue by Anirudh053** [microsoft/ALAppExtensions#26930]
### Describe the request

Hi Team,

In Codeunit 12 "Gen. Jnl.-Post Line" Please provide the possibility to have an integration event in SkipFindTaxDetail() Procedure after Line number 7763 in the image below
![image](https://github.com/user-attachments/assets/cc719d7b-4236-4e2e-a245-8062910779bf)

IntegrationEvent:

    [IntegrationEvent(false, false)]
    local procedure OnBeforeSkipFindTaxDetail(var TaxDetail: Record "Tax Detail"; GenJournalLine: Record "Gen. Journal Line"; var IsHandled: Boolean; var ReturnValue: Boolean)
    begin
    end;

### Additional context

We need these events to handle the custom code for various clients related to implementation of Excise Tax.
Internal work item: [AB#543326](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543326)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 23509.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23540.
