### ISSUE TITLE
[Event Request] Codeunit 5988 "Serv-Documents Mgt." –  OnBeforeRemoveLinesNotSatisfyPosting

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#26932]
### Describe the request

[Event Request] Codeunit 5988 "Serv-Documents Mgt." ???  OnBeforeRemoveLinesNotSatisfyPosting

Could we please have a publisher OnBeforeRemoveLinesNotSatisfyPosting  in function RemoveLinesNotSatisfyPosting Codeunit 5988 "Serv-Documents Mgt."?
```
    local procedure RemoveLinesNotSatisfyPosting()
    var
        ServiceLine2: Record "Service Line";
        IsHandled: Boolean;
    begin
// >>>>>>>>
        IsHandled := false;
        OnBeforeRemoveLinesNotSatisfyPosting(ServHeader, ServLine, Ship, Consume, Invoice, IsHandled);
// >>>>>>>>


        // Find ServLines not selected to post, and check if they were completely posted
        if ServLine.FindFirst() then begin

// >>>>>>>>
    [IntegrationEvent(false, false)]
    local procedure OnBeforeRemoveLinesNotSatisfyPosting(var ServiceHeader: Record "Service Header"; var ServiceLine: Record "Service Line"; Ship: Boolean; Consume: Boolean; Invoice: Boolean; var IsHandled: Boolean);
    begin
    end;
// <<<<<<<< 

```

### Additional context

We have to transfer further lines to the documents.
Internal work item: [AB#543327](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543327)

**Comment by AleksandricMarko** [comment]
Hello @TMEKUMA 
Whit this event, do you want to skip whole procedure or just first block or something else?

**Comment by TMEKUMA** [comment]
Hello @AleksandricMarko,
I would like to skip the function completely and replace it with my own code.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24072.
