### ISSUE TITLE
[Event Request] Table 77 "Report Selections" –  OnFindPrintUsageInternalOnAfterSetFilter

### ISSUE THREAD

**Issue by TMEKUMA** [microsoft/ALAppExtensions#26931]
### Describe the request

[Event Request] Table 77 "Report Selections" ???  OnFindPrintUsageInternalOnAfterSetFilter

Could we please have a publisher OnFindPrintUsageInternalOnAfterSetFilter  in function FindPrintUsageInternal Table 77 "Report Selections"?
```
    local procedure FindPrintUsageInternal(ReportUsage: Enum "Report Selection Usage"; AccountNo: Code[20]; var TempReportSelections: Record "Report Selections" temporary; TableNo: Integer)
    begin
        Reset();
        SetRange(Usage, ReportUsage);
        SetFilter("Report ID", '<>0');

// >>>>>>>>
        OnFindPrintUsageInternalOnAfterSetFilter(Rec, ReportUsage, AccountNo, TempReportSelections, TableNo);
// >>>>>>>>

        FindReportSelections(TempReportSelections, AccountNo, TableNo);
        TempReportSelections.FindSet();
    end;



// >>>>>>>>
    [IntegrationEvent(false, false)]
    local procedure OnFindPrintUsageInternalOnAfterSetFilter(var ReportSelections: Record "Report Selections"; ReportUsage: Enum "Report Selection Usage"; AccountNo: Code[20]; var TempReportSelections: Record "Report Selections" temporary; TableNo: Integer)
    begin
    end;
// <<<<<<<< 

```

### Additional context

We need to filter another field that is only intended for print.
Internal work item: [AB#543325](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543325)

**Comment by Groenbech96** [comment]
I think you can use OnFindReportSelections that is called in FindReportSelections. 
The record is passed here. 

If i am mistaken please reopen and describe what you need to filter, and why this event is not enough 👍
