### ISSUE TITLE
Table 5199 Attendee - Need read permission to contact table

### ISSUE THREAD

**Issue by Mahibabu1993** [microsoft/ALAppExtensions#26938]
### Describe the request

Hi,

In our solution, we have the possibility to create interaction log entries and todos via api post calls. We need to assign limited permissions to the user. When creating todos, the system tries to create attendee and it fails because of the permission to Contact table. We have indirect permissions to contact table.

To resolve this issue, a solution would be to add explicit read permission to contact table in the object table 5199 Attendee.
In our solution the Interaction Log Entries are created via api post calls and we need limited permissions sets for the user.

```
table 5199 Attendee
{
    Caption = 'Attendee';
    DataClassification = CustomerContent;
    Permissions = tabledata "Salesperson/Purchaser" = R,
                           tabledata Contact = R;   // New Line

    fields
    {
        field(1; "To-do No."; Code[20])
```

Is it okay to add the permission to Contact table on this object?

Thanks

### Additional context

In our solution, we have the possibility to create interaction log entries and todos via api post calls. We need to assign limited permissions to the user. When creating todos, the system tries to create attendee and it fails onvalidate Attendee No. of table 5199 Attendee because of not having permission to Contact table. Currently we have indirect permission to contact table.
Internal work item: [AB#543333](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543333)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22874.
