### ISSUE TITLE
[Event Change Request] TAB36 Sales Header - procedure CreateSalesLine - Event OnCreateSalesLineOnBeforeAssignType

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26946]
### Describe the request

We would like add SalesHeader(var) to the following events.

Original:

```
TAB36 Sales Header - procedure CreateSalesLine - Event OnCreateSalesLineOnBeforeAssignType

    [IntegrationEvent(false, false)]
    local procedure OnCreateSalesLineOnBeforeAssignType(var SalesLine: Record "Sales Line"; TempSalesLine: Record "Sales Line" temporary; SalesHeader: Record "Sales Header")
    begin
    end;
```

Change:

```
    [IntegrationEvent(false, false)]
    local procedure OnCreateSalesLineOnBeforeAssignType(var SalesLine: Record "Sales Line"; TempSalesLine: Record "Sales Line" temporary; var SalesHeader: Record "Sales Header")
    begin
    end;
```

### Additional context

Get a Variable which is Bind on Sales Header
Internal work item: [AB#543565](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543565)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22874.
