### ISSUE TITLE
[Event request] codeunit 444 "Purchase-Post Prepayments": BuildInvLineBuffer procedure

### ISSUE THREAD

**Issue by tguyonnet** [microsoft/ALAppExtensions#26948]
### Describe the request

`
    var
        PrepmtInvLineBuf2: Record "Prepayment Inv. Line Buffer";
        TotalPrepmtInvLineBuffer: Record "Prepayment Inv. Line Buffer";
        TotalPrepmtInvLineBufferDummy: Record "Prepayment Inv. Line Buffer";
        PurchSetup: Record "Purchases & Payables Setup";
// >>>>>>>>
        IsHandled: Boolean;
// <<<<<<<< 
    begin
        TempGlobalPrepmtInvLineBuf.Reset();
        TempGlobalPrepmtInvLineBuf.DeleteAll();
        TempPurchaseLine.Reset();
        TempPurchaseLine.DeleteAll();
        PurchSetup.Get();
        ApplyFilter(PurchHeader, DocumentType, PurchLine);
        if PurchLine.Find('-') then
            repeat
// >>>>>>>>
                 IsHandled := false;
                 OnBeforePrepmtAmountOnBuildInvLineBuffer(PurchHeader, PurchLine, PrepmtInvLineBuf2, PrepmtInvLineBuf, TempPurchaseLine);
                 if not IsHandled then
// <<<<<<<< 

                if PrepmtAmount(PurchLine, DocumentType) <> 0 then begin
                    FillInvLineBuffer(PurchHeader, PurchLine, PrepmtInvLineBuf2);
                    if UpdateLines then
                        TempGlobalPrepmtInvLineBuf.CopyWithLineNo(PrepmtInvLineBuf2, PurchLine."Line No.");
                    PrepmtInvLineBuf.InsertInvLineBuffer(PrepmtInvLineBuf2);
                    if PurchSetup."Invoice Rounding" then
                        RoundAmounts(
                          PurchHeader, PrepmtInvLineBuf2, TotalPrepmtInvLineBuffer, TotalPrepmtInvLineBufferDummy);
                    TempPurchaseLine := PurchLine;
                    TempPurchaseLine.Insert();
                end;
            until PurchLine.Next() = 0;

`

// >>>>>>>>
    [IntegrationEvent(false, false)]
    local procedure OnBeforePrepmtAmountOnBuildInvLineBuffer(PurchHeader: Record "Purchase Header"; PurchLine: Record "Purchase Line"; var PrepmtInvLineBuf: Record "Prepayment Inv. Line Buffer"; var PrepmtInvLineBuf: Record "Prepayment Inv. Line Buffer"; var TempPurchaseLineSource: Record "Purchase Line" temporary);
    begin
    end;
// <<<<<<<< 

### Additional context

Transfert from purch order to purch invoice lines with type = " "
Internal work item: [AB#543569](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543569)

**Comment by AleksandricMarko** [comment]
Hello @tguyonnet 
Does this structure fit your need
![image](https://github.com/user-attachments/assets/a840a614-1dab-4e23-b155-650a45a51734)

**Comment by tguyonnet** [comment]
yes it fit, perfect!

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23098.
