### ISSUE TITLE
[Request-For-External] TAB37 "Sales Line" - Procedure ThrowWrongAmountError

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26942]
### Describe the request

Hello, we need the following currently Internal procedure to be set as Global. Can you please check this? Thank you!

```
[Request-For-External] TAB37 "Sales Line" - Procedure from Internal to Global

procedure ThrowWrongAmountError()
```	

### Additional context

Use it out of an TAB37-Event
Internal work item: [AB#543561](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543561)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22874.
