### ISSUE TITLE
Request to add publishers control testing "Prices Including VAT" field on codeunit "Copy Document Mgt."

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#26956]
### Describe the request

Dear team,

In codeunit "Copy Document Mgt.", function CopyPurchRcptLinesToDoc, I'd like to have an subscriber to control if need to test OriginalPurchHeader."Price Including VAT" or not. Please help me to add new publisher OnCopyPurchRcptLinesToDocOnBeforeTestPriveInclVAT(ToPurchHeader, IncludeHeader, Recalculculatelines, FromPurchRcptHeader, Ishandle) just like below to meet the requirement.

![image](https://github.com/user-attachments/assets/0b55a834-33e6-4b93-ad14-2a2202d1e56d)

I also need publishers with same purpose on functions: CopyPurchInvLinesToDoc, CopyPurchCrMemoLinesToDoc, CopyPurchReturnShptLinesToDoc. Please consider to add.

![image](https://github.com/user-attachments/assets/51e31414-3572-4b0a-83b3-664b5e40feae)
![image](https://github.com/user-attachments/assets/b5e867cc-91ce-4d6b-b789-1454a97d15b9)
![image](https://github.com/user-attachments/assets/84a7d9b6-b24a-44e4-a105-6aba85887d2f)
![image](https://github.com/user-attachments/assets/4b238f9f-2e02-4d30-b2cb-9b0c56fe8065)

### Additional context

In our business, I just don't check the "Price Including VAT" when we copy document

Thank you in advance!
Internal work item: [AB#543728](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543728)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22874.
