### ISSUE TITLE
Convert the procedure into a global functions in codeunit "Purch. Price Calc. Mgt."

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#26957]
### Describe the request

Dear team,

Could you please help turning these procedures IsInMinQty, ConvertPriceToVAT, ConvertPriceToUoM, PurchHeaderExchDate, PurchHeaderStartDate to global fucntion?

### Additional context

I would like to call these functions outside the codeunit.

Thank you for your considering and effort.
Internal work item: [AB#543727](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543727)

**Comment by AleksandricMarko** [comment]
Hello @GiangLNT56 
The codeunit 7010 "Purch. Price Calc. Mgt." is deprecated so this kind of changes are not allowed
