### ISSUE TITLE
[Request procedure] codeunit 99000836 "Transfer Line-Reserve" - SetBinding

### ISSUE THREAD

**Issue by Duizy1971** [microsoft/ALAppExtensions#26952]
### Describe the request

I'm working on BC25 stuff and I'm seeing a lot of changes in de 'Reserve' codeunits. All good but for our addon I'm missing one specific procedure in codeunit 99000836 "Transfer Line-Reserve":

    procedure SetBinding(Binding: Enum "Reservation Binding")
    begin
        CreateReservEntry.SetBinding(Binding);
    end;

It exists in eight Reserve codeunits but allas not in this one.

### Additional context

This procedure will allow me to Obsolete a lot of code in my codeunit and correctly use existing Base code which is now replicated.
Internal work item: [AB#543571](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543571)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22874.
