### ISSUE TITLE
[Event Request] Table 5050 - Contact - TouchContact

### ISSUE THREAD

**Issue by JanineBluemelGOB** [microsoft/ALAppExtensions#26951]
### Describe the request

Hello,
Please add an event in table 5050 for the function "TouchContact".

The event should call "OnBeforeTouchContact". I marked the new Code in the code below with //Start New Code and //End New Code. 

 procedure TouchContact(ContactNo: Code[20])
    var
        Cont: Record Contact;
         IsHandled: Boolean; //New Code
    begin
        //Start New Code
        OnBeforeTouchContact(Rec, IsHandled);
        if IsHandeled then
            exit;
        //End New Code

        Cont.LockTable();
        if Cont.Get(ContactNo) then begin
            Cont.SetLastDateTimeModified();
            Cont.Modify();
        end;
    end;

### Additional context

Skip the modification of the Contact.
Internal work item: [AB#543558](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543558)

**Comment by AleksandricMarko** [comment]
Already implemented
![image](https://github.com/user-attachments/assets/fb420545-bb58-48de-8458-0726f9fcb39d)
