### ISSUE TITLE
Add publisher OnAfterGetSalesHeaderPageID on codeunit "Page Management"

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#26955]
### Describe the request

Dear team,

On Codeunit "Page Management", please help to add publisher OnAfterGetSalesHeaderPageID(RecRef, SalesHeader, Result) place after function GetSalesHeaderPageID

![image](https://github.com/user-attachments/assets/1fc04e05-a808-4673-98a4-b93f5f68e2fd)

### Additional context

I'd like to add logic for extension options of Document Type. The new publisher will work just like current OnAfterGetPurchaseHeaderPageID

Thank you in advance!
Internal work item: [AB#543729](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543729)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22874.
