### ISSUE TITLE
[Event Request] REP5880 Calc. Phys. Invt. Order Lines - DataItem Item - OnBeforeCheckItemBlocked

### ISSUE THREAD

**Issue by MH1612** [microsoft/ALAppExtensions#26969]
### Describe the request

Please add the following Event/-s OnBeforeCheckItemBlocked to DataItem Item in REP5880 Calc. Phys. Invt. Order Lines.

```
[Event Request] REP5880 Calc. Phys. Invt. Order Lines - DataItem Item - OnBeforeCheckItemBlocked
        dataitem(Item; Item)
        {
            RequestFilterFields = "No.", "Inventory Posting Group", "Gen. Prod. Posting Group", "Item Category Code", "Variant Filter", "Location Filter", "Bin Filter", "Date Filter";

            trigger OnAfterGetRecord()
            begin
                if not HideValidationDialog then
                    Window.Update(1, "No.");

                Clear(LastItemLedgEntry);

                // NEW
                // if not Blocked then
                ItemBlockedL := Blocked;
                OnBeforeCheckItemBlocked(Item,PhysInvtOrderHeader,ItemBlockedL);
                if not ItemBlockedL then
                // NEW    
                    CalcItemPhysInvtOrderLines()
                else
                    ItemsBlocked := true;
            end;
```

```
 [IntegrationEvent(false, false)]
 local procedure OnBeforeCheckItemBlocked(var Item : Record Item; PhysInvtOrderHeader: Record "Phys. Invt. Order Header"; var ItemBlockedL : Boolean)
    begin
    end;
```

### Additional context

Do an Additional Blocking-Check
Internal work item: [AB#544504](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544504)

**Comment by AleksandricMarko** [comment]
Hello @MH1612 
In procedure CalcItemPhysInvtOrderLines() you have OnBeforeCalcItemPhysInvtOrderLines which you can use to make additional check on item

**Comment by MH1612** [comment]
Hello
I will forward the request internally. My colleague is currently still on vacation, we will answer next week.

**Comment by SKeiler** [comment]
Hi @AleksandricMarko 

We also need the IsHandled-Event because in some cases we want also to create inventory lines for blocked items. So the OnBeforeCalcItemPhysInvtOrderLines -Event is unfortunaly to late for us :-(

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24072.
