### ISSUE TITLE
[Protected] page 1570 "Extended G/L Posting Preview" - ShowHierarchicalView

### ISSUE THREAD

**Issue by fvet** [microsoft/ALAppExtensions#26966]
### Describe the request

Can you please make global var `ShowHierarchicalView` protected, so we can read the value in page extensions?

### Additional context

*
Internal work item: [AB#544446](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544446)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26058.
