### ISSUE TITLE
[Event Request] Customer Card - OnBeforeStartBackgroundCalculations

### ISSUE THREAD

**Issue by BernhardKloibmueller** [microsoft/ALAppExtensions#26960]
### Describe the request

Old:
```
    local procedure OnAfterGetCurrRecordFunc()
    var
        WorkflowStepInstance: Record "Workflow Step Instance";
        CRMCouplingManagement: Codeunit "CRM Coupling Management";
        WorkflowWebhookManagement: Codeunit "Workflow Webhook Management";
    begin
        if NewMode then
            CreateCustomerFromTemplate()
        else
            StartBackgroundCalculations();
        ActivateFields();
        SetCreditLimitStyle();
```

New:
```
    local procedure OnAfterGetCurrRecordFunc()
    var
        WorkflowStepInstance: Record "Workflow Step Instance";
        CRMCouplingManagement: Codeunit "CRM Coupling Management";
        WorkflowWebhookManagement: Codeunit "Workflow Webhook Management";
        IsHandled: Boolean;                                                           // << NEW
    begin
        if NewMode then
            CreateCustomerFromTemplate()
        else begin                                                                         // << CHANGE
            OnBeforeStartBackgroundCalculations(Rec, IsHandled); // << NEW
            if not IsHandled then                                                    // << NEW
                StartBackgroundCalculations();
        end;                                                                                  // << CHANGE
        ActivateFields();
        SetCreditLimitStyle();
.................

    [IntegrationEvent(true, false)]
    local procedure OnBeforeStartBackgroundCalculations(var Customer: Record Customer; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

I was looking into some unnecessary calculation on one of my customer's environments and found that the customer statistic fasttab uses some values the customer does not need. He event removed the fasttab though personalization.

So I would like a new event to remove it through a PTE.
I know that not all values are in the statistic fasttab, but I have rather some fields which I need to calculate again than the additional sessions.

Thank you for maybe providing an event.
Internal work item: [AB#543726](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543726)

**Comment by BernhardKloibmueller** [comment]
Alternatively I can raise a Base Application Contribution where I would redesign the parameter given to the background task where I would introduce an event where I could manipulate which fields I want to calculate. Maybe this is better?

Came into my mind now after writing the request.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22874.
