### ISSUE TITLE
 SAT UTILITIES AND ELECTRONIC INVOICE

### ISSUE THREAD

**Issue by Julietkipsang** [microsoft/ALAppExtensions#26967]
### Describe the request

Make some changes in codeunit 27030 SAT Utilities. Also allow accessaible to some local procedures in  Codeunit "E-Invoice Mgt." and  Codeunit "Certificate Management".

Replace procedure GetSATItemClassification with a similar one having Enum parameter instead of Option like in the example below:
procedure GetSATItemClassification(Type: Option " ","G/L Account",Item,Resource,"Fixed Asset","Charge (Item)"; ItemNumber: Code[20]): Code[10]

procedure GetSATClassification(Type: Enum "Sales Line Type"; No: Code[20]): Code[10]

Add an event in the GetSATClassification function.
local procedure OnBeforeGetSATClassification(LineType: Enum "Sales Line Type"; No: Code[20]; var SATClassification: Code[10]; var IsHandled: Boolean)

### Additional context

To add a classification code to resource table  and be able to generate the xml with classification code in the resource table  and sign and send it to PAC.

Internal work item: [AB#545283](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545283)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 24.

Build ID to track: 23383.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23506.

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 23501.
