### ISSUE TITLE
Codeunit 227 "VendEntry-Apply Posted Entries" - procedure  PostUnApplyVendorCommit(DtldVendLedgEntry2: Record "Detailed Vendor Ledg. Entry"; ApplyUnapplyParameters: Record "Apply Unapply Parameters"; CommitChanges: Boolean) - OnPostUnApplyVendorCommitOnBeforeCheckApplicationDate

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#26964]
### Describe the request

Could You please, add the following event to the Codeunit 227 "VendEntry-Apply Posted Entries"
	
	Object: Codeunit 227 "VendEntry-Apply Posted Entries"
	
	procedure PostUnApplyVendorCommit(DtldVendLedgEntry2: Record "Detailed Vendor Ledg. Entry"; ApplyUnapplyParameters: Record "Apply Unapply Parameters"; CommitChanges: Boolean)
	
	Microsoft_Base Application_24.3.21374.22567.app
	
	Publisher Event: OnPostUnApplyVendorCommitOnBeforeCheckApplicationDate(ApplyUnapplyParameters, DtldVendLedgEntry2, PreviewMode, IsHandled)
	
	Reason: To implement custom business logic and permit avoid the checking of ApplyingDate
	Where is the event placed (see image attached)?:
	
![image](https://github.com/user-attachments/assets/79d89854-45a6-44bb-972a-f8123cf7219b)

	
	Just before the line 348: 
		if NewApplyUnapplyParameters."Posting Date" <  DtldVendLedgEntry2."Posting Date" then 
	
	Insert the next lines:
	IsHandled := false;
	OnPostUnApplyVendorCommitOnBeforeCheckApplicationDate(ApplyUnapplyParameters, DtldVendLedgEntry2, PreviewMode, IsHandled);
	if not IsHandled then
![image](https://github.com/user-attachments/assets/ac398e23-4117-41b5-8a29-029eb2f08c25)

![image](https://github.com/user-attachments/assets/75883f6f-7840-4c43-84a5-1880e7601225)
	Event code:
	
	    [IntegrationEvent(false, false)]
	    local procedure OnPostUnApplyVendorCommitOnBeforeCheckApplicationDate(var ApplyUnapplyParameters: Record "Apply Unapply Parameters" temporary; DtldVendLedgEntry2: Record "Detailed Vendor Ledg. Entry"; PreviewMode: Boolean; var IsHandled: Boolean)
	    begin
	    end;
	
	Thanks in advance.

### Additional context

Our customer needs to unapply vendor entries when the "Application Date" is greater than the "Posting Date".
Internal work item: [AB#543724](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543724)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22874.
