### ISSUE TITLE
[Event Request] Codeunit 1313 - "Correct Posted Purch. Invoice" - OnAfterIsCommentLine()

### ISSUE THREAD

**Issue by MutluhanGulenc** [microsoft/ALAppExtensions#26968]
### Describe the request

Please add OnAfterIsCommentLine() event to  Codeunit 1313 - "Correct Posted Purch. Invoice" just like Codeunit 1303 "Correct Posted Sales Invoice" and update IsCommentLine() procedure same way.

> [IntegrationEvent(false, false)]
    local procedure OnAfterIsCommentLine(SalesInvoiceLine: Record "Sales Invoice Line"; var Result: Boolean)
    begin
    end;

![image](https://github.com/user-attachments/assets/c2e8ad72-7006-4b70-8dc2-7c8e82d9ca18)

![image](https://github.com/user-attachments/assets/afec95c1-42e6-4b87-8803-d7699864aef1)

### Additional context

Skip controls for a extended Purchase Line Type enum.
Internal work item: [AB#544507](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544507)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23098.
