### ISSUE TITLE
	Codeunit 227 "VendEntry-Apply Posted Entries" - procedure Apply(VendLedgEntry: Record "Vendor Ledger Entry"; ApplyUnapplyParameters: Record "Apply Unapply Parameters"): Boolean - OnApplyOnBeforeCheckApplicationDate 

### ISSUE THREAD

**Issue by IgnacioPeq** [microsoft/ALAppExtensions#26963]
### Describe the request

Could You please, add the following event to the Codeunit 227 "VendEntry-Apply Posted Entries"
	
	Object: Codeunit 227 "VendEntry-Apply Posted Entries"
	
	procedure Apply(VendLedgEntry: Record "Vendor Ledger Entry"; ApplyUnapplyParameters: Record "Apply Unapply Parameters"): Boolean
	
	Microsoft_Base Application_24.3.21374.22567.app
	
	Publisher Event: OnApplyOnBeforeCheckApplicationDate(ApplyUnapplyParameters, VendLedgEntry, PreviewMode, IsHandled)
	
	Reason: To implement custom business logic and permit avoid the checking of ApplyingDate
	Where is the event placed (see image attached)?:

![image](https://github.com/user-attachments/assets/068c4d3b-6f01-4ada-b618-4bd311e6b7eb)

The line 98 must be replaced by: else begin

	After the line 100 add a new line with: end;
	Just before the line 99: 
		if NewApplyUnapplyParameters."Posting Date" <  GetApplicationDate(VendLedgEntry) then 
	
	Insert the next lines:
	IsHandled := false;
	OnApplyOnBeforeCheckApplicationDate(ApplyUnapplyParameters, VendLedgEntry, PreviewMode, IsHandled);
	if not IsHandled then
![image](https://github.com/user-attachments/assets/f0df0b34-d577-41ab-bc00-59c99b6814c4)

Event code:
	
	[IntegrationEvent(false, false)]
	    local procedure OnApplyOnBeforeCheckApplicationDate(var ApplyUnapplyParameters: Record "Apply Unapply Parameters" temporary; VendLedgEntry: Record "Vendor Ledger Entry"; PreviewMode: Boolean; var IsHandled: Boolean)
	    begin
	    end;
	
	Thanks in advance.

### Additional context

Our customer needs to apply vendor entries when the "Application Date" is greater than the "Posting Date".
Internal work item: [AB#543723](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/543723)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 22874.
