### ISSUE TITLE
add event in codeunit 1605 "PEPPOL Management" OnAfterFindNextInvoiceLineRec

### ISSUE THREAD

**Issue by Michel-up** [microsoft/ALAppExtensions#26970]
### Describe the request

In codeunit 1605 "PEPPOL Management" in FindNextInvoiceLineRec procedure add OnBeforeFindNextInvoiceLineRec event 

[IntegrationEvent(false, false)] local procedure OnBeforeFindNextInvoiceLineRec(var SalesInvoiceLine: Record "Sales Invoice Line"; var ServiceInvoiceLine: Record "Service Invoice Line"; var SalesLine: Record "Sales Line"; ProcessedDocType: Option Sale,Service; ProcessedDocType: Option Sale,Service; Position: Integer) ;

### Additional context

 procedure FindNextInvoiceLineRec(var SalesInvoiceLine: Record "Sales Invoice Line"; var ServiceInvoiceLine: Record "Service Invoice Line"; var SalesLine: Record "Sales Line"; ProcessedDocType: Option Sale,Service; Position: Integer): Boolean
    var
        Found: Boolean;
    begin

//add the below event at the end of GetAccountingSupplierPartyLegalEntityByFormat
OnBeforeFindNextInvoiceLineRec(SalesInvoiceLine, ServiceInvoiceLine, SalesLine, ProcessedDocType, Position);

        case ProcessedDocType of
            ProcessedDocType::Sale:
                begin
                    if Position = 1 then
                        Found := SalesInvoiceLine.Find('-')
                    else
                        Found := SalesInvoiceLine.Next() <> 0;
                    if Found then
                        SalesLine.TransferFields(SalesInvoiceLine);
                end;
          .....

        OnAfterFindNextInvoiceLineRec(SalesInvoiceLine, ServiceInvoiceLine, SalesLine, ProcessedDocType, Found);
        exit(Found);
    end;

[IntegrationEvent(false, false)] local procedure OnBeforeFindNextInvoiceLineRec(var SalesInvoiceLine: Record "Sales Invoice Line"; var ServiceInvoiceLine: Record "Service Invoice Line"; var SalesLine: Record "Sales Line"; ProcessedDocType: Option Sale,Service; ProcessedDocType: Option Sale,Service; Position: Integer) ;
Internal work item: [AB#545281](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545281)

**Comment by Groenbech96** [comment]
I will need some information about why and what scenario you are doing.

**Comment by Michel-up** [comment]
the scenario is when we have lines with 0 quantities , we dont want the Peppol file to include lines with 0 quantities.

**Comment by Groenbech96** [comment]
Why cant you set found = false, on the on after event?

**Comment by Michel-up** [comment]
> Why cant you set found = false, on the on after event?

because all remaning lines wont be included. 
example:
if we have a invoice with 5 lines and the second line has quantity 0, 
when setting found = false, then all remaining lines(3,4,5) will be excluded

**Comment by Groenbech96** [comment]
Is there really not any way to set filters on the SalesInvoiceLine in the XML ports that use this code. 
Problem with adding your event is that we have to accomodate this for sales and service, and i would rather have some other approach to setting specific filters on the SalesInvoiceLine variable

**Comment by Michel-up** [comment]
if thats the case then you can explore if you can add a new function in Peppol management that contains a new IntegrationEvent, and this function is then called from within the Initialize of the xmlport, below more details:


in xmlport 1610 "Sales Invoice - PEPPOL BIS 3.0"

```
 procedure Initialize(DocVariant: Variant)
    var
        RecRef: RecordRef;
    begin
        RecRef.GetTable(DocVariant);
        case RecRef.Number of
            DATABASE::"Sales Invoice Header":
                begin
                    RecRef.SetTable(SalesInvoiceHeader);
                    if SalesInvoiceHeader."No." = '' then
                        Error(SpecifyASalesInvoiceNoErr);
                    SalesInvoiceHeader.SetRecFilter();
                    SalesInvoiceLine.SetRange("Document No.", SalesInvoiceHeader."No.");
                    SalesInvoiceLine.SetFilter(Type, '<>%1', SalesInvoiceLine.Type::" ");


                    // ** Call new function below in codeunit 1605 "PEPPOL Management"**
                    PEPPOLMgt.AddSalesInvoiceLineFilter(SalesInvoiceLine);

                    if SalesInvoiceLine.FindSet() then
                        repeat
                            SalesLine.TransferFields(SalesInvoiceLine);
                            PEPPOLMgt.GetInvoiceRoundingLine(TempSalesLineRounding, SalesLine);
                        until SalesInvoiceLine.Next() = 0;
                    if TempSalesLineRounding."Line No." <> 0 then
                        SalesInvoiceLine.SetFilter("Line No.", '<>%1', TempSalesLineRounding."Line No.");

                    ProcessedDocType := ProcessedDocType::Sale;
                end;

```

and in codeunit 1605 "PEPPOL Management"

```
 procedure AddSalesInvoiceLineFilter(var SalesInvoiceLine: Record "Sales Invoice Line")
    begin
      OnAddSalesInvoiceLineFilter(SalesInvoiceLine)
    end;

```

```
 [IntegrationEvent(false, false)]
    local procedure OnAddSalesInvoiceLineFilter(var SalesInvoiceLine: Record "Sales Invoice Line")
    begin
    end;

```

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 27448.
