### ISSUE TITLE
[Event Change Request] codeunit 99000809 "Planning Line Management"

### ISSUE THREAD

**Issue by bachii1010** [microsoft/ALAppExtensions#26978]
### Describe the request

**BEFORE**
[IntegrationEvent(false, false)]
    local procedure OnTransferBOMOnAfterCalculateReqQty(var ReqQty: Decimal; ProductionBOMLine: Record "Production BOM Line");
    begin
    end;

**AFTER:**
[IntegrationEvent(false, false)]
    local procedure OnTransferBOMOnAfterCalculateReqQty(ProductionBOMLine: Record "Production BOM Line"; PlanningRoutingLine: Record "Planning Routing Line"; var ReqQty: Decimal; LineQtyPerUOM: Decimal; ItemQtyPerUOM: Decimal)
    begin
    end;

### Additional context

We request this event since we need to calculate some fields in BOM Line from planning worksheet similar to the Create prod. order from Sales Order . so to make it possible in two ways as now it is possible only while creating production order from sales order.
Internal work item: [AB#544506](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544506)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23098.
