### ISSUE TITLE
[Event Change Request] codeunit 5752 "Get Source Doc. Outbound" - event OnBeforeCreateFromPurchaseReturnOrder 

### ISSUE THREAD

**Issue by dorinbirsan** [microsoft/ALAppExtensions#26971]
### Describe the request

The current event change would benefit the fact that we could add IsHandled and thus handle the respective section of code, like OnBeforeCreateFromSalesOrder already has, so that we can skip the warehouse creation for the other documents as well.

This event change happens in codeunit 5752 "Get Source Doc. Outbound" for procedure CreateFromPurchaseReturnOrder

Current:
```
    procedure CreateFromPurchaseReturnOrder(PurchHeader: Record "Purchase Header")
    begin
        OnBeforeCreateFromPurchaseReturnOrder(PurchHeader);
        ShowResult(CreateFromPurchReturnOrderHideDialog(PurchHeader));
    end;
```

Requested:
```
    ...

    procedure CreateFromPurchaseReturnOrder(PurchHeader: Record "Purchase Header")
    var
        IsHandled: Boolean;
    begin
        OnBeforeCreateFromPurchaseReturnOrder(PurchHeader, IsHandled);
        if IsHandled then
            exit;
            
        ShowResult(CreateFromPurchReturnOrderHideDialog(PurchHeader));
    end;

    ...

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateFromPurchaseReturnOrder(PurchaseHeader: Record "Purchase Header"; var IsHandled: Boolean)
    begin
    end;

    ...
```

### Additional context

Justification: we request the event since in BC22 it was introduced that in the actions Create Warehouse Shipment and Create Warehouse receipt the document is released automatically in case it was open.
That conflicts now with existing custom logic, that the warehouse document is created already after the release of a document, leading to the issue that it is now tried two times to create the warehouse document.
Internal work item: [AB#544508](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544508)

**Comment by AleksandricMarko** [comment]
Hello @dorinbirsan
Please use event OnBeforeCreateWhseShipmentHeaderFromWhseRequest to skip further processing
