### ISSUE TITLE
[Procedure Request] Codeunit 7322 Create Inventory Pick/Movement

### ISSUE THREAD

**Issue by 365cycle** [microsoft/ALAppExtensions#26977]
### Describe the request

Please add a procedure _GetWhseActivHeader(var WhseActivHeader: Record "Warehouse Activity Header")_ to Codeunit 7322 Create Inventory Pick/Movement.

Also, a procedure to _SetHideDialog_ would be a nice to have (there is a workaround, but it's not very beautiful).

![image](https://github.com/user-attachments/assets/8cf624ca-46e8-4beb-961d-9c3cd7c4b71a)

![image](https://github.com/user-attachments/assets/1b86291e-0869-41da-8998-5adbb5b98ffb)

### Additional context

We are currently converting some add-on code from C/Side to BC24.
In Codeunit 7322, we added a procedure called _CreateInvtMvmtWithoutSourceHideDlg_ that allowed us to switch HideDialog to true and then call standard procedure _CreateInvtMvmtWithoutSource_ , after which we could return the global var Warehouse Activity Header record to the multiple procedures from which it was called. The original code in _CreateInvtMvmtWithoutSource_ does not allow us to access the Warehouse Activity Header, so we cannot get this code extension ready now.

As far as I could find, there is no way to get access to those global vars in cu 7322, so we'd like to see a procedure that allows us to pick up the new Warehouse Activity Header (and of course to hide the dialogs).

Suggestions could be:

1. SetWhseActivityHeader
Add an overload to SetWhseActivHeader. Parameters should be:
- Warehouse Activity Header, but passed ByVar (doing this in the standard function is potentially a breaking change, hence the overload). This way we can call the function and use the returned record;
- HideDialog (which can then be used to set HideDialog to true)

2. GetWhseActivityHeader & SetHideDialog
- We can also use a GetWhseActivityHeader procedure, which should then simple assign the global CurrWarehouseActivityHeader record to the ByVar parameter Warehouse Activity Header;
- Alongside this, we'd like to see a SetHideDialog procedure with which we can switch off the GUI. 
Internal work item: [AB#544502](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544502)

**Comment by 365cycle** [comment]
Thanks for already creating a work item!
Is it possible to predict anything about if and when this will be picked up, and what the solution would look like?
This object is a blocker in our upgrade from BC14 to BC24.

**Comment by ChethanT** [comment]
When you have GetWhseActivityHeader method why do you need SetWhseActivityHeader with WarehouseActivityHeader as var?
Isn't GetWhseActivityHeader and SetHideDialog enough for your need?

**Comment by 365cycle** [comment]
Thanks for responding.
I don't need both, I just suggested 2 ways to solve the issue. So yes, GetWhseActivityHeader + SetHideDialog would work.

**Comment by 365cycle** [comment]
Sorry for pushing this subject again, but has any decision been taken in this story? If so, can you please add it here? Then at least we can prepare the cu for our go live.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24752.
