### ISSUE TITLE
table 5901 Service Item No. On Validate trigger

### ISSUE THREAD

**Issue by Teming** [microsoft/ALAppExtensions#2697]
![image](https://user-images.githubusercontent.com/49729094/58809590-3b956a00-85ea-11e9-978a-f9f9e0670493.png)

Section 2 checks "Service Item No. ".  Would it make more sense to have it happen before Section 1?

**Comment by StanPesotskiy** [comment]
The error in line 198 should be thrown regardless of "Service Item No." value, it could be blank or not, as this value cannot be changed in a linked line. This check should go first. Then if the line is not linked, the value can be blanked and should blank other fields (lines 219-222).
