### ISSUE TITLE
[Event Request] Edit event OnBeforeSetNoSeries in Codeunit 5988 "Serv-Documents Mgt."

### ISSUE THREAD

**Issue by Chris9821-Work** [microsoft/ALAppExtensions#26972]
### Describe the request

Hi, 
I need two additional parameters in this event, the flag Ship and the variable PServHeader
```al
    [IntegrationEvent(false, false)]
    local procedure OnBeforeSetNoSeries(var ServHeader: Record "Service Header" temporary; var PServHeader: Record "Service Header"; Ship: Boolean; Invoice: Boolean; Consume: Boolean; var Result: Boolean; var IsHandled: Boolean)
    begin
    end;
``` 
![image](https://github.com/user-attachments/assets/a304ea09-4d7a-4ced-bc38-b11187c972fe)

### Additional context

I need these changes to perform some checks based on the Ship flag and to be able to edit the PServHeader as well
Internal work item: [AB#544501](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544501)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23098.
