### ISSUE TITLE
[Event Change Request] codeunit 5752 "Get Source Doc. Outbound" - event OnBeforeCreateFromOutbndTransferOrder

### ISSUE THREAD

**Issue by dorinbirsan** [microsoft/ALAppExtensions#26973]
### Describe the request

The current event change would benefit the fact that we could add IsHandled and thus handle the respective section of code, like OnBeforeCreateFromSalesOrder already has, so that we can skip the warehouse creation for the other documents as well.

This event change happens in codeunit 5752 "Get Source Doc. Outbound" for procedure CreateFromOutbndTransferOrder

Current:

```
    procedure CreateFromOutbndTransferOrder(TransHeader: Record "Transfer Header")
    begin
        OnBeforeCreateFromOutbndTransferOrder(TransHeader);
        ShowResult(CreateFromOutbndTransferOrderHideDialog(TransHeader));
    end;
```

Requested:

```
    ...

    procedure CreateFromOutbndTransferOrder(TransHeader: Record "Transfer Header")
    var
        IsHandled: Boolean;
    begin
        OnBeforeCreateFromOutbndTransferOrder(TransHeader, IsHandled);
        if IsHandled then
            exit;
            
        ShowResult(CreateFromOutbndTransferOrderHideDialog(TransHeader));
    end;

    ...

    [IntegrationEvent(false, false)]
    local procedure OnBeforeCreateFromOutbndTransferOrder(TransferHeader: Record "Transfer Header"; var IsHandled: Boolean)
    begin
    end;
 
   ...

```

### Additional context

Justification: we request the event since in BC22 it was introduced that in the actions Create Warehouse Shipment and Create Warehouse receipt the document is released automatically in case it was open.
That conflicts now with existing custom logic, that the warehouse document is created already after the release of a document, leading to the issue that it is now tried two times to create the warehouse document.
Internal work item: [AB#544503](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544503)

**Comment by AleksandricMarko** [comment]
Hello @dorinbirsan 
Please use event OnBeforeCreateWhseShipmentHeaderFromWhseRequest to skip further processing
