### ISSUE TITLE
[Event Request] codeunit 5876 "Phys. Invt. Rec.-Finish" - "Code"

### ISSUE THREAD

**Issue by Rihmz12** [microsoft/ALAppExtensions#26988]
### Describe the request

I would like to request the following event:
Object: PhysInvtRecFinish.Codeunit.al
Procedure: "Code"
Where the event should be placed:

        PhysInvtRecordLine.Reset();
        PhysInvtRecordLine.SetRange("Order No.", PhysInvtRecordHeader."Order No.");
        PhysInvtRecordLine.SetRange("Recording No.", PhysInvtRecordHeader."Recording No.");
        PhysInvtRecordLine.SetFilter("Item No.", '<>%1', '');

        IsHandled := false;
        OnCodeOnBeforeFindPhysInvtRecordLine(PhysInvtRecordHeader, IsHandled);
        if not IsHandled then
            if not PhysInvtRecordLine.Find('-') then
                Error(NoLinesRecordedErr);

        if not HideProgressWindow then begin
            Window.Open('#1#################################\\' + FinishingLinesMsg);
            Window.Update(1, StrSubstNo('%1 %2', PhysInvtRecordHeader.TableCaption(), PhysInvtRecordHeader."Order No."));
        end;

Event Code

    [IntegrationEvent(false, false)]
    local procedure OnCodeOnBeforeFindPhysInvtRecordLine(var PhysInvtRecordHeader: Record "Phys. Invt. Record Header"; var IsHandled: Boolean)
    begin
    end;

### Additional context

We want to extend the phys. inventory order and phys. inventory recording so that we can also post our own lines (no items) if no item lines exist
Internal work item: [AB#544594](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544594)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23210.
