### ISSUE TITLE
[Event Request] Table 5902 Service Line UpdateUnitPrice()

### ISSUE THREAD

**Issue by sboeve** [microsoft/ALAppExtensions#2698]
We have customized the logic in SalesPriceCalcMgt codeunit 7000 for FindServLinePrice function.
Would like to request an event in the Service Line table 5902 within the UpdateUnitPrice function that would allow us to bypass the standard NAV FindServLinePrice function.

Similar functionality exists in the Sales Line table's UpdateUnitPrice function.
event - onUpdateUnitPriceOnBeforeFindPrice(ServHeader, VAR ServLine, CalledByFieldNo, CurrFieldNo, IsHandled);

Example:
CalculateDiscount;
IsHandled := FALSE;
CERP_OnUpdateUnitPriceOnBeforeFindPrice(ServHeader,Rec,CalledByFieldNo,CurrFieldNo,IsHandled);
IF NOT IsHandled THEN
  SalesPriceCalcMgt.FindServLinePrice(ServHeader,Rec,CalledByFieldNo);
VALIDATE("Unit Price");

**Comment by AlexanderYakunin** [comment]
You already have event here and can change behavior of whole function in obe place:

[External] FindServLinePrice(ServHeader : Record "Service Header";VAR ServLine : Record "Service Line";CalledByFieldNo : Integer)
IsHandled := FALSE;
OnBeforeFindServLinePrice(ServLine,ServHeader,CalledByFieldNo,IsHandled);
IF IsHandled THEN
  EXIT;
