### ISSUE TITLE
[BC Idea]: Enhancing Shopify Connector for Accurate Price Synchronization with Business Central based on Customer

### ISSUE THREAD

**Issue by VijayErpEff** [microsoft/ALAppExtensions#26980]
### BC Idea Link

https://experience.dynamics.com/ideas/idea/?ideaid=34dcafc6-5c57-ef11-b4ac-6045bd8476a6

### Description

Currently, there is a need to synchronize prices between Business Central and Shopify, where prices are determined by the lowest pricing logic applied in Business Central. This involves complex pricing scenarios like customer-specific discounts, item discount groups, and other discount mechanisms. However, the existing Shopify Connector does not account for these complexities, leading to potential discrepancies between the prices in Business Central and those displayed in Shopify.

### I will provide the implementation for this BC Idea

- [X] I will provide the implementation for this BC Idea
Internal work item: [AB#544010](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544010)

**Comment by JesperSchulz** [comment]
@AndreiPanko, could you triage this idea?
