### ISSUE TITLE
[Protected] report 1316 "Standard Statement"; protected requestpage fields

### ISSUE THREAD

**Issue by TKapitan** [microsoft/ALAppExtensions#26983]
### Describe the request

Please make the following two variables protected.

```
        DateChoice: Option "Due Date","Posting Date";
        StatementStyle: Option "Balance","Open Item";
```

### Additional context

This will allow you to write custom code based on selected options on the request page. Without access to these fields, the code can't be written easily for both variants at the same time.
Internal work item: [AB#545277](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545277)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26614.
