### ISSUE TITLE
[Event Change Request] Codeunit 5611 "Calculate Normal Depreciation" - CalculateDeprAmount, OnCalculateDeprAmountOnBeforeCalculateDeprAmount

### ISSUE THREAD

**Issue by UrbMigle** [microsoft/ALAppExtensions#26991]
### Describe the request

Hello,

Please add two additional parameters to the event OnCalculateDeprAmountOnBeforeCalculateDeprAmount. They are needed for us to change the value of the Amount variable. 
                
```
        IsHandled := false;
        OnAfterCalculateFinalAmount(DeprBook, Amount, IsHandled);
        if not IsHandled then
            if Amount >= 0 then
                exit(0);

        IsHandled := false;
        OnCalculateDeprAmountOnBeforeCalculateDeprAmount(FA, SkipOnZero, DeprBookCode, Amount, BookValue2, SalvageValue2, EndingBookValue, FinalRoundingAmount, IsHandled, BookValue, UntilDate); <--- New Parameters Added
        if IsHandled then
            exit(Amount);

        if not SkipOnZero then
            DepreciationCalc.AdjustDepr(
              DeprBookCode, Amount, Abs(BookValue2), -Abs(SalvageValue2),
              EndingBookValue, FinalRoundingAmount);

```

```
    [IntegrationEvent(false, false)]
    local procedure OnCalculateDeprAmountOnBeforeCalculateDeprAmount(FixedAsset: Record "Fixed Asset"; SkipOnZero: Boolean; DeprBookCode: Code[20]; var Amount: Decimal; BookValue: Decimal; SalvageValue2: Decimal; EndingBookValue: Decimal; FinalRoundingAmount: Decimal; var IsHandled: Boolean; BookValue: Decimal; UntilDate: Date)
    begin
    end;
```

### Additional context

We want to change calculation of the amount, but are missing the parameters to do so, could you please add them to the event publisher? Thank you
Internal work item: [AB#545278](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545278)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
