### ISSUE TITLE
[Event Request] Codeunit 13 "Gen. Jnl.-Post Batch" - OnProcessLinesOnBeforeFindNextGLRegisterNo

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#26995]
### Describe the request

Hello, can you please add a new event OnProcessLinesOnBeforeFindNextGLRegisterNo in codeunit 13 "Gen. Jnl.-Post Batch"?

```
local procedure ProcessLines(var GenJnlLine: Record "Gen. Journal Line")
.
.
.
        if GenJnlTemplate.Type = GenJnlTemplate.Type::Intercompany then
            CheckICDocument(TempGenJnlLine);

        ProcessBalanceOfLines(GenJnlLine, GenJnlLineVATInfoSource, VATInfoSourceLineIsInserted, LastLineNo, CurrentICPartner);

       OnProcessLinesOnBeforeFindNextGLRegisterNo(GenJnlLine, GenJnlBatch);

        // Find next register no.
        GLEntry.LockTable();
        FindNextGLRegisterNo();

        // Post lines
```

```
    [IntegrationEvent(false, false)]
    local procedure OnProcessLinesOnBeforeFindNextGLRegisterNo(GenJournalLine: Record "Gen. Journal Line"; GenJournalBatch: Record "Gen. Journal Batch")
    begin
    end;
```

### Additional context

We would like to perform some preparative actions after all the checks and before posting.
Internal work item: [AB#545274](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545274)

**Comment by mildddd** [comment]
Hi @RZ440,

Please, use the existing event OnAfterProcessBalanceOfLines. There is no need for additional events.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
