### ISSUE TITLE
[Event Request]  Codeunit 13 "Gen. Jnl.-Post Batch" - OnBeforeFindNextGLRegisterNo

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27002]
### Describe the request

Hello, can you please add a new event OnBeforeFindNextGLRegisterNo in codeunit 13 "Gen. Jnl.-Post Batch"?

```
    local procedure FindNextGLRegisterNo()
    var
        IsHandled: Boolean;
    begin
        GLReg.LockTable();
        IsHandled := false;
        OnBeforeFindNextGLRegisterNo(GLReg, GLRegNo, IsHandled);
        if not IsHandled then
            GLRegNo := GLReg.GetLastEntryNo() + 1;
    end;
```

```
    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindNextGLRegisterNo(var GLRegister: Record "G/L Register"; var GLRegNo: Integer; var IsHandled: Boolean)
    begin
    end;
```

### Additional context

If several postings logically belong together we would like to use the same G/L Register as before instead of creating a new one.
Internal work item: [AB#545266](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545266)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26360.
