### ISSUE TITLE
[Event Change Request] Codeunit 13 "Gen. Jnl.-Post Batch" – OnBeforePostGenJnlLine

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27008]
### Describe the request

Hello, can you please add ???GLRegNo??? to the event OnBeforePostGenJnlLine in codeunit 13 "Gen. Jnl.-Post Batch"?

```
    local procedure PostGenJournalLine(var GenJournalLine: Record "Gen. Journal Line"; CurrentICPartner: Code[20]; ICTransactionNo: Integer) Result: Boolean
.
.
.
        UpdateIncomingDocument(GenJnlLine5);
        UpdateDimBalBatchName(GenJnlLine5);
        OnBeforePostGenJnlLine(GenJnlLine5, SuppressCommit, IsPosted, GenJnlPostLine, GenJournalLine, GLRegNo);
        if not IsPosted then begin
            GenJnlPostLine.RunWithoutCheck(GenJnlLine5);
            InsertPostedGenJnlLine(GenJournalLine);
            RemoveRecordLink(GenJournalLine);
        end;
```

```
    [IntegrationEvent(true, false)]
    local procedure OnBeforePostGenJnlLine(var GenJournalLine: Record "Gen. Journal Line"; CommitIsSuppressed: Boolean; var Posted: Boolean; var GenJnlPostLine: Codeunit "Gen. Jnl.-Post Line"; var PostingGenJournalLine: Record "Gen. Journal Line"; GLRegNo: Integer)
    begin
    end;
```

### Additional context

We would like to add own entries to the G/L Register.
Internal work item: [AB#545258](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545258)

**Comment by mildddd** [comment]
Hi,

You have information about "Gen. Journal Template" in GenJournalLine. No need for changing the event.

I will close the ticket.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
