### ISSUE TITLE
Do we need prefix or suffix in methods?

### ISSUE THREAD

**Issue by KonnosPB** [microsoft/ALAppExtensions#2700]
I have the constellation that two apps with one table extension each referencing the same table use the same method name and signature.
If I want to call the method I'll get that then:

> error AL0196: The call is ambiguous between the following methods or properties: 'SkipCommit(Boolean)' and 'SkipCommit(Boolean)'

On the site [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-prefix-suffix](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-prefix-suffix) there is only a hint that object and fieldnames need a prefix or suffix. Am I doing something wrong or is the documentation out of date?

**Comment by ikoletic** [comment]
This issue is a question. Please submit your questions on [business central community ](https://community.dynamics.com/business/f/758) or on [BC development yammer groups](https://www.yammer.com/dynamicsnavdev/#/threads/inGroup?type=in_group&feedId=5059035).
