### ISSUE TITLE
[Event Change Request] Codeunit 13 "Gen. Jnl.-Post Batch" – OnBeforeUpdateAndDeleteLines

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27004]
### Describe the request

Hello, can you please add "GenJnlLine2", "GenJnlTemplate", and "GenJnlBatch" to the event OnBeforeUpdateAndDeleteLines in codeunit 13 "Gen. Jnl.-Post Batch"?

```
    local procedure UpdateAndDeleteLines(var GenJnlLine: Record "Gen. Journal Line")
    var
        TempGenJnlLine2: Record "Gen. Journal Line" temporary;
        RecordLinkManagement: Codeunit "Record Link Management";
        OldVATAmount: Decimal;
        OldVATPct: Decimal;
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeUpdateAndDeleteLines(GenJnlLine, SuppressCommit, IsHandled, GenJnlLine2, GenJnlTemplate, GenJnlBatch);
        if IsHandled then
            exit;
```

```
    [IntegrationEvent(true, false)]
    local procedure OnBeforeUpdateAndDeleteLines(var GenJournalLine: Record "Gen. Journal Line"; CommitIsSuppressed: Boolean; var IsHandled: Boolean; var GenJournalLine2: Record "Gen. Journal Line"; GenJournalTemplate: Record "Gen. Journal Template"; var GenJournalBatch: Record "Gen. Journal Batch")
    begin
    end;
```

### Additional context

We would like to set global variables in GenJournalLine2, check some values of GenJournalTemplate, and in some cases modify GenJournalBatch.
Internal work item: [AB#545260](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545260)

**Comment by mildddd** [comment]
Hello,

In the procedure UpdateAndDeleteLines, after event OnBeforeUpdateAndDeleteLines, GenJnlLine2 is copied from GenJnlLine, so changing GenJnlLine2 is not relevant here. GenJnlTemplate and GenJnlBatch you can get from GenJnlLine.

I will close the request. If you still need it, please open the new one with more information.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: <None>.
