### ISSUE TITLE
[Event Request] Codeunit 5996 "Prod. Order Warehouse Mgt." - OnBeforeGetMachineCenterBinCode

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27018]
### Describe the request

I would like to handle the retrieval of the machine center bin code with my own business logic. Therefore, I request the following event:
```
local procedure GetMachineCenterBinCode(MachineCenterNo: Code[20]; LocationCode: Code[10]; UseFlushingMethod: Boolean; FlushingMethod: Enum "Flushing Method"): Code[20]
var
    MachineCenter: Record "Machine Center";
    // NEW BEGIN
    IsHandled: Boolean;
    Result: Boolean;
begin
    IsHandled := false;
    OnBeforeGetMachineCenterBinCode(MachineCenterNo, LocationCode, UseFlushingMethod, FlushingMethod, Result, IsHandled);
    if IsHandled then
        exit(Result);
    // NEW END
    if MachineCenter.Get(MachineCenterNo) then begin
        if MachineCenter."Location Code" = LocationCode then
            exit(MachineCenter.GetBinCodeForFlushingMethod(UseFlushingMethod, FlushingMethod));

        exit(GetWorkCenterBinCode(MachineCenter."Work Center No.", LocationCode, UseFlushingMethod, FlushingMethod));
    end;
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeGetMachineCenterBinCode(MachineCenterNo: Code[20]; LocationCode: Code[10]; UseFlushingMethod: Boolean; FlushingMethod: Enum "Flushing Method"; var Result: Code[20]; var IsHandled: Boolean)
begin
end;
```

### Additional context

I want the flushing method bin code to be retrieved only if the machine center "From-Production Bin Code" field is filled.
Internal work item: [AB#544576](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544576)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23210.
