### ISSUE TITLE
[Event Request] Codeunit 1901 "Report Selection Mgt." - OnBeforeInsertRepSelection

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27015]
### Describe the request

I would like to handle the report selection insert with my own business logic. Therefore, I request the following event:
```
local procedure InsertRepSelection(ReportUsage: Enum "Report Selection Usage"; Sequence: Code[10]; ReportID: Integer)
var
    ReportSelections: Record "Report Selections";
    // NEW BEGIN
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeInsertRepSelection(ReportUsage, Sequence, ReportID, IsHandled);
    if IsHandled then
        exit;
    // NEW END
    if not ReportSelections.Get(ReportUsage, Sequence) then begin
        ReportSelections.Init();
        ReportSelections.Usage := ReportUsage;
        ReportSelections.Sequence := Sequence;
        ReportSelections."Report ID" := ReportID;
        ReportSelections.Insert();
    end;
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeInsertRepSelection(ReportUsage: Integer; Sequence: Code[10]; ReportID: Integer; var IsHandled: Boolean)
begin
end;
```

### Additional context

When a Report Selection record is found, I want to modify the ReportID.
Internal work item: [AB#544381](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544381)

**Comment by Groenbech96** [comment]
Looking at the code, it dont think this event should be added. Instead you should add an entry in App/Layers/W1/BaseApp/Foundation/Reporting/ReportSelectionUsage.Enum.al for your scenario, and then subscribe to the event that gets fired when custom enum values are given. This way you can customize.
