### ISSUE TITLE
[Event Request] Codeunit 1901 "Report Selection Mgt." - OnBeforeInsertRepSelectionWhse

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27016]
### Describe the request

I would like to handle the Whse. Report Selection insert with my own business logic. Therefore, I request the following event:

```
procedure InsertReportSelectionWhse(ReportUsage: Enum "Report Selection Warehouse Usage"; Sequence: Code[10]; ReportID: Integer)
var
    ReportSelectionWhse: Record "Report Selection Warehouse";
    // NEW BEGIN
    IsHandled: Boolean;
begin
    IsHandled := false;
    OnBeforeInsertRepSelectionWhse(ReportUsage, Sequence, ReportID, IsHandled);
    if IsHandled then
        exit;
    // NEW END
    if not ReportSelectionWhse.Get(ReportUsage, Sequence) then begin
        ReportSelectionWhse.Init();
        ReportSelectionWhse.Usage := ReportUsage;
        ReportSelectionWhse.Sequence := Sequence;
        ReportSelectionWhse."Report ID" := ReportID;
        ReportSelectionWhse.Insert();
    end;
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeInsertRepSelectionWhse(ReportUsage: Integer; Sequence: Code[10]; ReportID: Integer; var IsHandled: Boolean)
begin
end;
```

### Additional context

When a Whse. Report Selection record is found, I want to modify the ReportID.
Internal work item: [AB#544385](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544385)

**Comment by AndersLarsenMicrosoft** [comment]
please disregard ny comment above - sorry

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24752.
