### ISSUE TITLE
[Event Request] Codeunit 99000774 "Calculate Routing Line" - OnAfterSetCalendarEntryDateFilterOnReturnNextCalendarEntry

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27024]
### Describe the request

I want to remove additional calendar entry filters. Therefore, I request the following event:
```
procedure ReturnNextCalendarEntry(var CalendarEntry2: Record "Calendar Entry"; OldCalendarEntry: Record "Calendar Entry"; Direction: Option Backward,Forward)
begin
    CalendarEntry2 := OldCalendarEntry;
    CalendarEntry2.SetRange(Date, CalendarEntry2.Date);
    // NEW BEGIN
    OnAfterSetCalendarEntryDateFiltersOnReturnNextCalendarEntry(CalendarEntry);
    // NEW END
    if Direction = Direction::Backward then begin
        CalendarEntry2.Find('-');           // rewind within the same day
        // ...
end;

[IntegrationEvent(false, false)]
local procedure OnAfterSetCalendarEntryDateFilterOnReturnNextCalendarEntry(var CalendarEntry: Record "Calendar Entry")
begin
end;
```

### Additional context

I want to remove a calendar entry filter (for "Capacity (Effective)").
Internal work item: [AB#544575](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544575)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23210.
