### ISSUE TITLE
[Change Request] codeunit 5600 "FA Insert Ledger Entry" - procedure FAName

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27027]
### Describe the request

Hello, can you please set the lokal procedure FAName to global?

```
    procedure FAName(DeprBookCode: Code[10]): Text[200]
    var
        DepreciationCalc: Codeunit "Depreciation Calculation";
    begin
        exit(DepreciationCalc.FAName(FA, DeprBookCode));
    end;
```

### Additional context

We would like access from our extension.
Internal work item: [AB#545034](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545034)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26058.
