### ISSUE TITLE
[Event Change Request] table 5621 "FA Journal Line" - OnBeforeValidateShortcutDimCode

### ISSUE THREAD

**Issue by RZ440** [microsoft/ALAppExtensions#27029]
### Describe the request

Hello, can you please set the initial value for the IsHandled variable?

```
procedure ValidateShortcutDimCode(FieldNumber: Integer; var ShortcutDimCode: Code[20])
    var
        IsHandled: Boolean;
    begin
        IsHandled := false;
        OnBeforeValidateShortcutDimCode(Rec, xRec, FieldNumber, ShortcutDimCode, IsHandled);
        if IsHandled then
            exit;
```

### Additional context

The initial value shoud be set to false.
Internal work item: [AB#545032](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/545032)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24354.
