### ISSUE TITLE
[Event Change Request] Codeunit 900 "Assembly-Post" - OnAfterUndoInitPost

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27037]
### Describe the request

I want to enable the user to change the PostingDate to the WorkDate(). Therefore, I request to add the PostingDate as a new Parameter to the OnAfterUndoInitPostevent:
```
local procedure UndoInitPost(var PostedAsmHeader: Record "Posted Assembly Header")
begin
	PostingDate := PostedAsmHeader."Posting Date";

	CheckPossibleToUndo(PostedAsmHeader);

	GetSourceCode(PostedAsmHeader.IsAsmToOrder());

	TempItemLedgEntry.Reset();
	TempItemLedgEntry.DeleteAll();
	// NEW BEGIN
	OnAfterUndoInitPost(PostedAsmHeader, PostingDate);
	// NEW END
end;

[IntegrationEvent(false, false)]
local procedure OnAfterUndoInitPost(var PostedAssemblyHeader: Record "Posted Assembly Header"; var PostingDate: Date)
begin
end;
```

### Additional context

I want to enable the user to change the PostingDate to the WorkDate(). 
Internal work item: [AB#544564](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544564)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23103.
