### ISSUE TITLE
[Event Change Request] Codeunit 7312 "Create Pick" - OnBeforeTempWhseActivLineInsert

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27032]
### Describe the request

I want to overwrite the TempWarehouseActivityLine "Shelf No." when the WhseSource2 equals Assembly. Therefore, I request to add WhseSource2 as a new Parameter to the OnBeforeTempWhseActivLineInsert event:
```
procedure CreateTempActivityLine(
	LocationCode: Code[10]; BinCode: Code[20]; UOMCode: Code[10]; QtyPerUOM: Decimal; QtyToPick: Decimal; QtyToPickBase: Decimal; ActionType: Integer; BreakBulkNo: Integer; QtyRndPrec: Decimal; QtyRndPrecBase: Decimal)
var
	WhseSource2: Option;
	ShouldCalcMaxQty: Boolean;
begin
	// ...
	TransferItemTrkgFields(TempWarehouseActivityLine, TempWhseItemTrackingLine);

	if (BreakBulkNo = 0) and (ActionType <> 2) then
		TotalQtyPickedBase += QtyToPickBase;
	// NEW BEGIN
	OnBeforeTempWhseActivLineInsert(TempWarehouseActivityLine, ActionType, WhseSource2);
	// NEW END
	TempWarehouseActivityLine.Insert();
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeTempWhseActivLineInsert(var TempWarehouseActivityLine: Record "Warehouse Activity Line" temporary; ActionType: Integer; WhseSource2: Option)
begin
end;
```

### Additional context

I want to overwrite the TempWarehouseActivityLine "Shelf No." when the WhseSource2 equals Assembly.
Internal work item: [AB#544583](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544583)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23054.
