### ISSUE TITLE
[Event Request] Codeunit 1620 "PEPPOL Validation" - OnAfterSetServiceLineFilter

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27045]
### Describe the request

I would like to add a filter for a custom field on the Service Line record. Therefore, I request the following event:
```
procedure CheckServiceHeader(ServiceHeader: Record "Service Header")
var
	ServiceLine: Record "Service Line";
	SalesHeader: Record "Sales Header";
	SalesLine: Record "Sales Line";
begin
	PEPPOLManagement.TransferHeaderToSalesHeader(ServiceHeader, SalesHeader);
	SalesHeader."Shipment Date" := SalesHeader."Posting Date";
	CheckSalesDocument(SalesHeader);
	ServiceLine.SetRange("Document No.", ServiceHeader."No.");
	//NEW BEGIN
	OnAfterSetServiceLineFilter(ServiceLine, ServiceHeader);
	//NEW END
	if ServiceLine.FindSet() then
		repeat
			PEPPOLManagement.TransferLineToSalesLine(ServiceLine, SalesLine);
			OnCheckServiceHeaderOnBeforeCheckSalesDocumentLine(SalesLine, ServiceLine);
			CheckSalesDocumentLine(SalesLine);
		until ServiceLine.Next() = 0;
end;

[IntegrationEvent(false, false)]
local procedure OnAfterSetServiceLineFilter(var ServiceLine: Record "Service Line"; ServiceHeader: Record "Service Header")
begin
end;
```

### Additional context

I would like to add a filter for a custom field on the Service Line record.
Internal work item: [AB#544599](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544599)

**Comment by Groenbech96** [comment]
Added in build 24750

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24747.
