### ISSUE TITLE
[Event Request] Codeunit 7181 "Purchases Info-Pane Management" - OnBeforeGetItemOnPurchasesInfoPaneManagement

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27047]
### Describe the request

I would like to handle the GetItem result if the Puchase Line Type is Ressource. Therefore, I request the following event:
```
local procedure GetItem(var PurchLine: Record "Purchase Line"): Boolean
//NEW BEGIN
var
	IsHandled: Boolean;
	Result: Boolean;
begin
	IsHandled := false;
	OnBeforeGetItemOnPurchasesInfoPaneManagement(PurchaseLine, Result, IsHandled);
	if IsHandled then
		exit(Result);
//NEW END
	if (PurchLine.Type <> PurchLine.Type::Item) or (PurchLine."No." = '') then
		exit(false);

	if PurchLine."No." <> Item."No." then
		Item.Get(PurchLine."No.");
	exit(true);
end;

[IntegrationEvent(false, false)]
local procedure OnBeforeGetItemOnPurchasesInfoPaneManagement(var PurchaseLine: Record "Purchase Line"; var Result: Boolean; var IsHandled: Boolean)
begin
end;
```

### Additional context

If the Purchase Line Type equals Ressource i want the GetItem procedure to exit true.
Internal work item: [AB#544598](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544598)

**Comment by AleksandricMarko** [comment]
Hello @1languste 
I assume that you want to calc availability for resource lines and using OnBeforeCalcAvailability event as well, but maybe it would better for you to have OnCalcAvailabilityOnCantGetItem(PurchLine, Result) event in procedure CalcAvailability?

**Comment by 1languste** [comment]
Hello @AleksandricMarko 
we dont use the OnBeforeCalcAvailability and we are fine with the default code being executed.
Your suggestion would work as well but in that case we would have to copy the default code.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24752.
