### ISSUE TITLE
[Event Request] Codeunit 1012 "Job Jnl.-Post Line" - OnAfterUpdateJobJnlLineTotalAmounts

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27041]
### Describe the request

I want to calculate the Total Cost & Price (LCY) on the AmtRoundingPrecision and not the GLSetup."Amount Rounding Precision". Therefore, I request the following event:
```
local procedure UpdateJobJnlLineTotalAmounts(var JobJnlLineToUpdate: Record "Job Journal Line"; AmtRoundingPrecision: Decimal)
begin
	JobJnlLineToUpdate."Total Cost" := Round(JobJnlLineToUpdate."Unit Cost" * JobJnlLineToUpdate.Quantity, AmtRoundingPrecision);
	JobJnlLineToUpdate."Total Cost (LCY)" := Round(JobJnlLineToUpdate."Unit Cost (LCY)" * JobJnlLineToUpdate.Quantity, GLSetup."Amount Rounding Precision");
	JobJnlLineToUpdate."Total Price" := Round(JobJnlLineToUpdate."Unit Price" * JobJnlLineToUpdate.Quantity, AmtRoundingPrecision);
	JobJnlLineToUpdate."Total Price (LCY)" := Round(JobJnlLineToUpdate."Unit Price (LCY)" * JobJnlLineToUpdate.Quantity, GLSetup."Amount Rounding Precision");
	//NEW BEGIN
	OnAfterUpdateJobJnlLineTotalAmounts(JobJnlLineToUpdate, AmtRoundingPrecision, GLSetup."Amount Rounding Precision");
	//NEW END
end;

[IntegrationEvent(false, false)]
local procedure OnAfterUpdateJobJnlLineTotalAmounts(var JobJnlLineToUpdate: Record "Job Journal Line"; AmtRoundingPrecision: Decimal; GLAmtRoundingPrecision: Decimal)
begin
end;
```

### Additional context

I want to calculate the Total Cost & Price (LCY) on the AmtRoundingPrecision and not the GLSetup."Amount Rounding Precision".
Internal work item: [AB#544565](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544565)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23206.
