### ISSUE TITLE
[Event Change Request] Codeunit 442 "Sales-Post Prepayments" - OnCodeOnAfterPostingDescriptionSet

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27052]
### Describe the request

I want to change the Posting Description with my own business logic. Therefore, I request to add the PostingDescription as a parameter to the OnCodeOnAfterPostingDescriptionSet event:
```
local procedure "Code"(var SalesHeader2: Record "Sales Header"; DocumentType: Option Invoice,"Credit Memo")
var
	//...
begin
	//...
	SourceCodeSetup.Get();
	SrcCode := SourceCodeSetup.Sales;
	if SalesHeader."Prepmt. Posting Description" <> '' then
		PostingDescription := SalesHeader."Prepmt. Posting Description"
	else
		PostingDescription :=
		  CopyStr(
			StrSubstNo(Text012, SelectStr(1 + DocumentType, Text019), SalesHeader."Document Type", SalesHeader."No."),
			1, MaxStrLen(SalesHeader."Posting Description"));
	//NEW BEGIN
	OnCodeOnAfterPostingDescriptionSet(SalesHeader, DocumentType, PostingDescription);
	//NEW END
	// Create posted header
	if SalesSetup."Ext. Doc. No. Mandatory" then
		SalesHeader.TestField("External Document No.");
	//...

[IntegrationEvent(false, false)]
local procedure OnCodeOnAfterPostingDescriptionSet(var SalesHeader: Record "Sales Header"; DocumentType: Option Invoice,"Credit Memo"; var PostingDescription: Text[100])
begin
end;
```

### Additional context

I want to change the Posting Description with my own business logic.
Internal work item: [AB#544595](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544595)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23210.
