### ISSUE TITLE
[Event Request] Codeunit 5057 "VendCont-Update" - OnBeforeFillSalespersonCode 

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27053]
### Describe the request

I want to handle whether the SalespersonCode is set or not. Therefore, I request the following Event:
```
procedure OnModify(var Vend: Record Vendor)
var
	Cont: Record Contact;
	OldCont: Record Contact;
	ContBusRel: Record "Contact Business Relation";
	ContNo: Code[20];
	NoSeries: Code[20];
	SalespersonCode: Code[20];
	IsHandled: Boolean;
begin
	//...
	if not Cont.Get(ContBusRel."Contact No.") then begin
		ContBusRel.Delete();
		Session.LogMessage('0000B36', VendContactUpdateTelemetryMsg, Verbosity::Normal, DataClassification::SystemMetadata, TelemetryScope::ExtensionPublisher, 'Category', VendContactUpdateCategoryTxt);
		exit;
	end;
	OldCont := Cont;

	ContNo := Cont."No.";
	NoSeries := Cont."No. Series";
	//NEW BEGIN
	IsHandled := false;
	OnBeforeFillSalespersonCode(Contact, IsHandled);
	if not IsHandled then;
		SalespersonCode := Cont."Salesperson Code";
	//NEW END
	OnBeforeTransferFieldsFromVendToCont(Cont, Vend);
	Cont.Validate("E-Mail", Vend."E-Mail");
	//...

[IntegrationEvent(false, false)]
local procedure OnBeforeFillSalespersonCode(var Contact: Record Contact; var IsHandled: Boolean)
begin
end;
```

### Additional context

I want to handle whether the SalespersonCode is set or not.
Internal work item: [AB#544587](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544587)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23210.
