### ISSUE TITLE
Need to add parameter on publisher OnModifyOnBeforeTestCheckPrinted on table 81-Gen. Journal Line

### ISSUE THREAD

**Issue by GiangLNT56** [microsoft/ALAppExtensions#27061]
### Describe the request

Dear team,
I would like to add new parameter on publisher OnModifyOnBeforeTestCheckPrinted to get the xRec value
![2024-08-15_17h24_22](https://github.com/user-attachments/assets/1f732680-20d3-4369-ac56-23091be01344)
Thank you in advance.

### Additional context

N/A
Internal work item: [AB#544581](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544581)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 26357.
