### ISSUE TITLE
[Event Change Request] Table 904 "Assemble-to-Order Link" - OnSynchronizeAsmFromSalesLineOnAfterGetAsmHeader

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27069]
### Describe the request

I want to hide the window GUI for quote sales lines. Therefore, I request to add a GUIEnabled variable to the OnSynchronizeAsmFromSalesLineOnAfterGetAsmHeader event:
```
local procedure SynchronizeAsmFromSalesLine(var NewSalesLine: Record "Sales Line")
var
	TempTrackingSpecification: Record "Tracking Specification" temporary;
	SalesHeader: Record "Sales Header";
	Window: Dialog;
	QtyTracked: Decimal;
	QtyTrackedBase: Decimal;
	//NEW BEGIN
	GUIEnabled: Boolean;
	//NEW END
begin
	GetAsmHeader();
	//NEW BEGIN
	GUIEnabled := true;
	OnSynchronizeAsmFromSalesLineOnAfterGetAsmHeader(NewSalesLine, AsmHeader, GUIEnabled);
	if GUIEnabled then
	//NEW END
		Window.Open(GetWindowOpenTextSale(NewSalesLine));

	CaptureItemTracking(TempTrackingSpecification, QtyTracked, QtyTrackedBase);
	
	//...
	
	NewSalesLine.CheckAsmToOrder(AsmHeader);
	//NEW BEGIN
	if GUIEnabled then
	//NEW END
		Window.Close();

	AsmHeader.SetWarningsOn();
	AsmHeader.ShowDueDateBeforeWorkDateMsg();
end;
[IntegrationEvent(false, false)]
local procedure OnSynchronizeAsmFromSalesLineOnAfterGetAsmHeader(var NewSalesLine: Record "Sales Line"; var AssemblyHeader: Record "Assembly Header"; var GUIEnabled: Boolean)
begin
end;
```

### Additional context

Allows you to handle whether the GUI is shown or not.
Internal work item: [AB#544554](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544554)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23103.
