### ISSUE TITLE
[Event Request] Page 9255 "Tasks Matrix" - OnBeforePageRunOnMatrixOnDrillDown

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27065]
### Describe the request

I want to run a custom page instead of the default "Task List". Therefore, I request the following event:
```
local procedure MatrixOnDrillDown(ColumnID: Integer)
//NEW BEGIN
var
	IsHandled: Boolean;
//NEW END
begin
	//...
	Task.SetFilter("Salesperson Code", Rec.GetFilter("Salesperson Filter"));
	Task.SetFilter("Team Code", Rec.GetFilter("Team Filter"));
	Task.SetFilter("Contact Company No.", Rec.GetFilter("Contact Company Filter"));
	Task.SetFilter(Status, Rec.GetFilter("Task Status Filter"));
	Task.SetFilter(Closed, Rec.GetFilter("Task Closed Filter"));
	Task.SetFilter(Priority, Rec.GetFilter("Priority Filter"));
	Task.SetFilter("System To-do Type", Rec.GetFilter("System Task Type Filter"));
	//NEW BEGIN
	IsHandled := false;
	OnBeforePageRunOnMatrixOnDrillDown(Rec.Task, IsHandled);
	if not IsHandled then
	//NEW END
		PAGE.RunModal(PAGE::"Task List", Task);
end;
[IntegrationEvent(false, false)]
local procedure OnBeforePageRunOnMatrixOnDrillDown(Task: Record "To-do"; var IsHandled: Boolean)
begin
end;
```

### Additional context

I want to run a custom page instead of the default "Task List" on the Matrix Drill Down.
Internal work item: [AB#544568](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544568)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23206.
