### ISSUE TITLE
[Request-For-External] [Event Request] Page 9223 "Item Statistics Matrix"

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27062]
### Describe the request

I want to calculate and display quantity values in the Item Stat. Matrix. Therefore, I request to add a new OnBeforeCalculation event and to change the global IncludeExpected variable to protected.
```
local procedure Calculate(SetColumnFilter: Boolean) Amount: Decimal
begin
	//NEW BEGIN
	OnBeforeCalculation(ItemBuffer, Amount, Qty, Rec.Name, SetColumnFilter);
	//NEW END
	case ItemBuffer."Line Option" of
		ItemBuffer."Line Option"::"Profit Calculation",
		ItemBuffer."Line Option"::"Cost Specification":
			case Rec.Name of
				ItemBuffer.FieldCaption("Sales (LCY)"):
					Amount := CalcSalesAmount(SetColumnFilter);
				ItemBuffer.FieldCaption("COGS (LCY)"):
					Amount := CalcCostAmount(SetColumnFilter);
	//...
[IntegrationEvent(true, false)]
local procedure OnBeforeCalculation(var ItemBuffer: Record "Item Statistics Buffer"; var Amount: Decimal; var Qty: Decimal; Name: Text; SetColumnFilter: Boolean)
begin
end;
```

```
//NEW BEGIN
protected var
        IncludeExpected: Boolean;
//NEW END
```

### Additional context

I want to calculate and display quantity values in the Item Stat. Matrix. 
I can add them to the Dim. Code Buffer, but in order to calculate the values i need a new event before the default calculation and also access to the global IncludeExpected variable.
Internal work item: [AB#544578](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544578)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23210.
