### ISSUE TITLE
[Event Request] Page 5769 "Whse. Receipt Subform" - OnAfterWhsePostRcptYesNo

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27066]
### Describe the request

I want to run custom business logic after the WhsePostRcptYesNo procedure. Therefore, I request the following Event:
```
procedure WhsePostRcptYesNo()
var
	WhseRcptLine: Record "Warehouse Receipt Line";
begin
	WhseRcptLine.Copy(Rec);
	CODEUNIT.Run(CODEUNIT::"Whse.-Post Receipt (Yes/No)", WhseRcptLine);
	Rec.Reset();
	Rec.SetCurrentKey("No.", "Sorting Sequence No.");
	CurrPage.Update(false);
	//NEW BEGIN
	OnAfterWhsePostRcptYesNo(Rec);
	//NEW END
end;
[IntegrationEvent(false, false)]
local procedure OnAfterWhsePostRcptYesNo(var WarehouseReceiptLine: Record "Warehouse Receipt Line")
begin
end;
```

### Additional context

This allows code to be run after the WhsePostRcptYesNo procedure.
Internal work item: [AB#544557](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544557)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23103.
