### ISSUE TITLE
[Event Request] Page 5769 "Whse. Receipt Subform" - OnAfterWhsePostRcptPrintPostedRcpt

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27068]
### Describe the request

I want to run custom business logic after the WhsePostRcptPrintPostedRcpt procedure. Therefore, I request the following Event:
```
procedure WhsePostRcptPrintPostedRcpt()
var
	WhseRcptLine: Record "Warehouse Receipt Line";
begin
	WhseRcptLine.Copy(Rec);
	CODEUNIT.Run(CODEUNIT::"Whse.-Post Receipt + Pr. Pos.", WhseRcptLine);
	Rec.Reset();
	CurrPage.Update(false);
	//NEW BEGIN
	OnAfterWhsePostRcptPrintPostedRcpt(Rec);
	//NEW END
end;
[IntegrationEvent(false, false)]
local procedure OnAfterWhsePostRcptPrintPostedRcpt(var WarehouseReceiptLine: Record "Warehouse Receipt Line")
begin
end;
```

### Additional context

This allows code to be run after the WhsePostRcptPrintPostedRcpt procedure.
Internal work item: [AB#544555](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544555)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23103.
