### ISSUE TITLE
[Event Request] Table 38 "Purchase Header" - OnBeforeConfirmUpdateAllLineDim

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27076]
### Describe the request

I want to be able to change the default value of the change dimension confirm. Therefore, I request the following event and code change:
```
procedure UpdateAllLineDim(NewParentDimSetID: Integer; OldParentDimSetID: Integer)
var
	ConfirmManagement: Codeunit "Confirm Management";
	NewDimSetID: Integer;
	ReceivedShippedItemLineDimChangeConfirmed: Boolean;
	//NEW BEGIN
	DefaultAnswer: Boolean;
	//NEW END
	IsHandled: Boolean;
begin
	IsHandled := false;
	OnBeforeUpdateAllLineDim(Rec, NewParentDimSetID, OldParentDimSetID, IsHandled, xRec);
	if IsHandled then
		exit;

	if NewParentDimSetID = OldParentDimSetID then
		exit;
	//NEW BEGIN
	if not GetHideValidationDialog() then begin
		DefaultAnswer := true;
		OnBeforeConfirmUpdateAllLineDim(Rec, DefaultAnswer);
		if not ConfirmManagement.GetResponseOrDefault(Text051, DefaultAnswer) then
			exit;
	end;
	//NEW END
	PurchLine.Reset();
	PurchLine.SetRange("Document Type", "Document Type");
	PurchLine.SetRange("Document No.", "No.");
	OnUpdateAllLineDimOnAfterPurchLineSetFilters(PurchLine);
	PurchLine.LockTable();
	//...
[IntegrationEvent(false, false)]
local procedure OnBeforeConfirmUpdateAllLineDim(PurchaseHeader: Record "Purchase Header"; var DefaultAnswer: Boolean)
begin
end;
```

### Additional context

Allows to change the default answer of the dimension change confirm.
Internal work item: [AB#544547](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544547)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23103.
