### ISSUE TITLE
[Event Request] Table 77 "Report Selections" - OnBeforeonvertReportUsageToSalesDocumentType

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27079]
### Describe the request

I extended the ReportUsage Enum with custom values and I need to extend the ConvertReportUsageToSalesDocumentType procedure to take them in account. Therefore, I request the following event:
```
procedure ConvertReportUsageToSalesDocumentType(var DocumentType: Enum "Sales Document Type"; ReportUsage: Enum "Report Selection Usage"): Boolean
//NEW BEGIN
var
	IsHandled: Boolean;
	Result: Boolean;
begin
	IsHandled := false;
	OnBeforeConvertReportUsageToSalesDocumentType(Usage, ReportUsage.AsInteger(), DocumentType, SalesHeader, IsHandled, Result);
	if IsHandled then
		exit(Result);
//NEW END
	case ReportUsage of
		Usage::"S.Invoice", Usage::"S.Invoice Draft", Usage::"P.Invoice":
			DocumentType := "Sales Document Type"::Invoice;
		Usage::"S.Quote", Usage::"P.Quote":
			DocumentType := "Sales Document Type"::Quote;
		Usage::"S.Cr.Memo", Usage::"P.Cr.Memo":
			DocumentType := "Sales Document Type"::"Credit Memo";
		Usage::"S.Order", Usage::"P.Order":
			DocumentType := "Sales Document Type"::Order;
		else
			exit(false);
	end;
	exit(true);
end;
[IntegrationEvent(false, false)]
local procedure OnBeforeConvertReportUsageToSalesDocumentType(var Usage: Enum "Report Selection Usage"; ReportUsage: Integer; var DocumentType: Option; SalesHeader: Record "Sales Header"; var IsHandled: Boolean; var Result: Boolean)
begin
end;
```

### Additional context

Allows you to mange your own ReportUsage Enum values or change the behavior of the procedure with custom business logic.
Internal work item: [AB#544541](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544541)

**Comment by JakovljevicDusan** [comment]
Event changed to more generic 
    local procedure OnBeforeConvertReportUsageToSalesDocumentType(var ReportSelections: Record "Report Selections"; var DocumentType: Enum "Sales Document Type"; ReportUsage: Enum "Report Selection Usage"; var IsHandled: Boolean; var Result: Boolean)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24822.
