### ISSUE TITLE
[Event Request] Table 5409 "Prod. Order Routing Line" - OnBeforeFillDescriptionMachineCtrTransferFields

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27075]
### Describe the request

I want to prevent the description value from being overwritten. Therefore, I request the following event:
```
local procedure MachineCtrTransferFields()
//NEW BEGIN
var
	IsHandled: Boolean;
//NEW END
begin
	WorkCenter.Get(MachineCenter."Work Center No.");
	WorkCenterTransferFields();
	//NEW BEGIN
	IsHandled := false;
	OnBeforeFillDescriptionMachineCtrTransferFields(Rec, WorkCenter, IsHandled);
	if not IsHandled then
	//NEW END
		Description := MachineCenter.Name;
	"Setup Time" := MachineCenter."Setup Time";
	"Wait Time" := MachineCenter."Wait Time";
	"Move Time" := MachineCenter."Move Time";
	//...
end;
[IntegrationEvent(false, false)]
local procedure OnBeforeFillDescriptionMachineCtrTransferFields(var ProdOrderRoutingLine: Record "Prod. Order Routing Line"; WorkCenter: Record "Work Center"; var IsHandled: Boolean)
begin
end;
```

### Additional context

Allows you to change the description to a custom value or prevent it from being overwritten.
Internal work item: [AB#544548](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544548)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23103.
