### ISSUE TITLE
[Event Request] Codeunit 1393 "Cancel Issued Reminder"

### ISSUE THREAD

**Issue by bogdangarkusha** [microsoft/ALAppExtensions#27070]
### Describe the request

I would like to ask you to create an Integration event in Codeunit 1393 "Cancel Issued Reminder", in procedure "SetReminderEntryCancelled()".

```
    local procedure SetReminderEntryCancelled(IssuedReminderLine: Record "Issued Reminder Line")
    var
        ReminderFinChargeEntry: Record "Reminder/Fin. Charge Entry";
    begin
        ReminderFinChargeEntry.SetRange("No.", IssuedReminderLine."Reminder No.");
        ReminderFinChargeEntry.SetRange("Customer Entry No.", IssuedReminderLine."Entry No.");
        if ReminderFinChargeEntry.FindFirst() then begin
            ReminderFinChargeEntry.Canceled := true;
            // >>
            OnSetReminderEntryCancelledOnBeforeReminderFinChargeEntryModify(ReminderFinChargeEntry,IssuedReminderLine);
            // <<
            ReminderFinChargeEntry.Modify();
        end;
    end;
```

Event signature:

`    [IntegrationEvent(false, false)]
    local procedure OnSetReminderEntryCancelledOnBeforeReminderFinChargeEntryModify(var ReminderFinChargeEntry: Record "Reminder/Fin. Charge Entry"; IssuedReminderLine: Record "Issued Reminder Line")
    begin
    end;
`

### Additional context

I would like extra cancelation information to a Reminder Entry after a Reminder is cancelled.
Internal work item: [AB#544552](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544552)

**Comment by JesperSchulz** [comment]
Availability update: We will publish a fix for this issue in the next update for release 25.

Build ID to track: 25892.
