### ISSUE TITLE
[Event Request] Table 39 "Purchase Line" - OnAfterReversedInternalLeadTimeDays

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27077]
### Describe the request

I want to be able to change the result of the procedure with custom business logic. Therefore, I request the following event:
```
local procedure ReversedInternalLeadTimeDays(PurchDate: Date): Text[30]
var
	TotalDays: DateFormula;
	ReversedSafetyLeadTime: DateFormula;
	ReversedWhseHandlingTime: DateFormula;
begin
	CalendarMgmt.ReverseDateFormula(ReversedSafetyLeadTime, "Safety Lead Time");
	CalendarMgmt.ReverseDateFormula(ReversedWhseHandlingTime, "Inbound Whse. Handling Time");
	Evaluate(
	  TotalDays, '<' + Format(PurchDate - CalcDate(ReversedWhseHandlingTime, CalcDate(ReversedSafetyLeadTime, PurchDate))) + 'D>');
	//NEW BEGIN
	OnAfterReversedInternalLeadTimeDays(Rec, PurchDate, ReversedWhseHandlingTime, TotalDays);
	//NEW END
	exit(Format(TotalDays));
end;
[IntegrationEvent(false, false)]
local procedure OnAfterReversedInternalLeadTimeDays(PurchaseLine: Record "Purchase Line"; PurchDate: Date; ReversedWhseHandlingTime: DateFormula; var TotalDays: DateFormula)
begin
end;
```

### Additional context

Allows you to do handle this procedure or change the result based on own business logic.
Internal work item: [AB#544546](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544546)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23103.
