### ISSUE TITLE
[Event Request] Table 5970 "Filed Service Contract Header" - OnBeforeFiledContractLineTransferFields

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27072]
### Describe the request

I want to calculate a FlowField so that it is copied before the TransferFields. Therefore, I request the following Event:
```
procedure FileContract(ServContractHeader: Record "Service Contract Header")
var
	ServContractLine: Record "Service Contract Line";
	NextEntryNo: Integer;
begin
	//...
	ServContractLine.Reset();
	ServContractLine.SetRange("Contract Type", ServContractHeader."Contract Type");
	ServContractLine.SetRange("Contract No.", ServContractHeader."Contract No.");
	if ServContractLine.Find('-') then
		repeat
			FiledContractLine.Init();
			FiledContractLine."Entry No." := FiledServContractHeader."Entry No.";
			//NEW BEGIN
			OnBeforeFiledContractLineTransferFields(ServContractLine);
			//NEW END
			FiledContractLine.TransferFields(ServContractLine);
			FiledContractLine.Insert();
		until ServContractLine.Next() = 0;

	OnAfterFileContract(FiledServContractHeader, ServContractHeader);
end;
local procedure OnBeforeFiledContractLineTransferFields(var ServContractLine: Record "Service Contract Line")
begin
end;
```

### Additional context

Allows you to change field values or calculate flowfield before the TransferFields.
Internal work item: [AB#544551](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544551)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23752.
