### ISSUE TITLE
[Event Request] Table 27 Item - OnAfterUpdateItemCategoryId

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27073]
### Describe the request

I want to perform custom business logic after the UpdateItemCategoryId event. Therefore, I request the following event:
```
procedure UpdateItemCategoryId()
var
	ItemCategory: Record "Item Category";
	GraphMgtGeneralTools: Codeunit "Graph Mgt - General Tools";
begin
	if IsTemporary then
		exit;

	if not GraphMgtGeneralTools.IsApiEnabled() then
		exit;

	if "Item Category Code" = '' then begin
		Clear("Item Category Id");
		exit;
	end;

	if not ItemCategory.Get("Item Category Code") then
		exit;

	"Item Category Id" := ItemCategory.SystemId;
	//NEW BEGIN
	OnAfterUpdateItemCategoryId(Rec, ItemCategory);
	//NEW END
end;
[IntegrationEvent(false, false)]
local procedure OnAfterUpdateItemCategoryId(var Item: Record Item; ItemCategory: Record "Item Category")
begin
end;
```

### Additional context

I want to copy field values from the item category to the item record in this event.
Internal work item: [AB#544550](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544550)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 23103.
