### ISSUE TITLE
[Event Request] Table 77 "Report Selections" - OnAfterFoundAttachment

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27078]
### Describe the request

I want to change the DefaultEmailAddress based on custom business logic. Therefore, I request the following event:
```
local procedure SendEmailDirectly(ReportUsage: Enum "Report Selection Usage"; RecordVariant: Variant;
	DocNo: Code[20];
	DocName: Text[150];
	FoundBody: Boolean;
	FoundAttachment: Boolean;
	ServerEmailBodyFilePath: Text[250]; var DefaultEmailAddress: Text[250]; ShowDialog: Boolean; var TempAttachReportSelections: Record "Report Selections" temporary; var CustomReportSelection: Record "Custom Report Selection") AllEmailsWereSuccessful: Boolean
var
	//...
begin
	//...
	if FoundAttachment then begin
		//NEW BEGIN
		IsHandled := false;
        OnAfterFoundAttachment(Rec, Usage, ReportUsage.AsInteger(), CustomReportSelection, DefaultEmailAddress, IsHandled);
        if not IsHandled then
		//NEW END
			if ReportUsage = Usage::JQ then begin
				Usage := ReportUsage;
				CustomReportSelection.SetFilter(Usage, GetFilter(Usage));
				if CustomReportSelection.FindFirst() then
					if CustomReportSelection.GetSendToEmail(true) <> '' then
						DefaultEmailAddress := CustomReportSelection."Send To Email";
			end;

		OnSendEmailDirectlyOnBeforeSendFiles(
		  ReportUsage.AsInteger(), RecordVariant, DefaultEmailAddress, TempAttachReportSelections, CustomReportSelection);
		OfficeAttachmentManager.IncrementCount(TempAttachReportSelections.Count - 1);
		repeat
	//...
[IntegrationEvent(false, false)]
local procedure OnAfterFoundAttachment(ReportSelections: Record "Report Selections"; var Usage: Enum "Report Selection Usage"; ReportUsage: Integer; var CustomReportSelection: Record "Custom Report Selection"; var DefaultEmailAddress: Text[250]; var IsHandled: Boolean)
begin
end;
```

### Additional context

Allows you to set the DefaultEmailAddress on with own business logic.
Internal work item: [AB#544545](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544545)

**Comment by JakovljevicDusan** [comment]
Hi @1languste,

Can you use OnSendEmailDirectlyOnBeforeSendFiles for this purpose or please check if we can add parameters to this event publisher, so it can be used?

**Comment by 1languste** [comment]
Hi @JakovljevicDusan,

if you can add the current Rec (Report Selection Record) as a new parameter to the OnSendEmailDirectlyOnBeforeSendFiles Event it should work for me.

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24822.
