### ISSUE TITLE
Make Varables protected - report 99001014 "Update Unit Cost"

### ISSUE THREAD

**Issue by KatarinaRaskovic** [microsoft/ALAppExtensions#27071]
### Describe the request

protected var
    CalcMethod: Option "One Level","All Levels";
    UpdateReservations: Boolean;

### Additional context

We need these variables to be protected:
The values of these variables are needed to be used in additional functionality in report extension
Internal work item: [AB#544556](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544556)

**Comment by JesperSchulz** [comment]
Thanks for reporting this. We agree, and we’ll publish a fix asap, either in an update for the current version or in the next major release. Please do not reply to this, as we do not monitor closed issues. If you have follow-up questions or requests, please create a new issue where you reference this one.

Build ID: 24752.
