### ISSUE TITLE
[Event Request] Table 5902 "Service Line" - OnRenameServiceLine

### ISSUE THREAD

**Issue by 1languste** [microsoft/ALAppExtensions#27081]
### Describe the request

I want to be able to rename Service Lines. Therefore, I request the following event:
```
trigger OnRename()
//NEW BEGIN
var
	IsHandled: Boolean;
begin
	IsHandled := false;
	OnRenameServiceLine(Rec, IsHandled);
	if IsHandled then
		exit;
//NEW END
	Error(Text002, TableCaption);
end;
[IntegrationEvent(false, false)]
local procedure OnRenameServiceLine(var ServiceLine: Record "Service Line"; var IsHandled: Boolean)
begin
end;
```

### Additional context

Allows you to suppress the OnRename error.
Internal work item: [AB#544540](https://dynamicssmb2.visualstudio.com/1fcb79e7-ab07-432a-a3c6-6cf5a88ba4a5/_workitems/edit/544540)

**Comment by AleksandricMarko** [comment]
We are not providing this kind of events. 
Renaming is forbidden with the reason.
